### DISCUSSION TITLE
ArgoCD Ignore Strimzi Out of sync

### DISCUSSION THREAD

**Discussion by miroslavmasaryk3221** [argoproj/argo-cd#10041] [General]
Describe the bug
We are trying to ignore out-of-sync issue with strimzi onap application.

![image](https://user-images.githubusercontent.com/83809890/179772596-5000e67b-ccd1-4d0e-9471-7ab0378ea4ec.png)
Whole ClusterRoleBinding is out of sync

Here is the code:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onap-strimzi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-95"
spec:
  project: argo-management
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding"
    name: strimzi-onap-onap-strimzi-kafka-init
    jsonPointers:
    - /apiVersion
    - /kind
    - /metadata
    - /managedFields
    - /name
    - /resourceVersion
    - /uid
    - /roleRef
    - /subjects
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: false
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: onap
  source:
    repoURL: https://gitlab.devops.telekom.de/tnap/operations/infra/helmcharts/application-charts/onap-oom.git
    targetRevision: v10.0.0
    path: strimzi
    helm:
      valueFiles: 
      - ../onap/values-global.yaml
      - ../onap/values-strimzi.yaml
```

To Reproduce
Install Onap OOM strimzi with argoCD
Link to charts: https://github.com/onap/oom
Install Strimzi Kafka Operator via argoCd
https://github.com/strimzi/strimzi-kafka-operator
Expected behavior
Cluster role binding should be not out of sync
Version
ArgoCD Chart 4.9.8
ArgoCD app :  2.4.4
