### DISCUSSION TITLE
Webhook and Manifest Paths Annotation details - targetRevision?

### DISCUSSION THREAD

**Discussion by xakraz** [argoproj/argo-cd#10094] [Q&A] [answered]
Hi there!

## Context

We have a setup for our testing environments where we have

- 1 mono-repo
- Every "end-applications" manifests are on 1 unique and dedicated branch per environment
- Every `Applications` manifest are on the same branch: `argo-cd`

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-1
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: feature/x1
    path: guestbook
```

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-2
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: feature/x2
    path: guestbook
```

## Question

In the [HA and performance documentation, in the Mono-repo scaling section](https://argo-cd.readthedocs.io/en/release-2.0/operator-manual/high_availability/#argocd-application-controller) there is a mention of the _Webhook and Manifest Paths Annotation_.

And it is written:

> Argo CD aggressively caches generated manifests and uses repository commit SHA as a cache key. **A new commit to the Git repository invalidates cache for all applications configured in the repository** that again negatively affect mono repositories with multiple applications. You might use [webhooks ⧉](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/webhook.md) and `argocd.argoproj.io/manifest-generate-paths` Application CRD annotation to solve this problem and improve performance.

I understand that a commit on a branch will invalidate all Applications generated manifests for Applications stored on that branch.

But does it also invalidates the ones on other branches?
