### DISCUSSION TITLE
rendering script's contents into template files using argocd

### DISCUSSION THREAD

**Discussion by ni-todo-spot** [argoproj/argo-cd#10100] [Q&A]
Hey all!

I'm using argocd for deploying resources in my k8s cluster.

I was wondering if there some kind of way to render a script into a manifest.

Example, in my git repo:

`/project/scripts/my_script.py`:

```python
print("Hello World!")
```

And `/project/templates/scripts-configmaps.yaml`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
data:
  hello_world.py: |
    print("Hello World")
```

I'd like argocd to copy the `/project/scripts/my_script.py` contents into `/project/templates/scripts-configmaps.yaml`.

Ideally something like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
data:
  hello_world.py: |
    {{ cat ../scripts/my_script.py }}
```

Is argocd offers some kind of feature like that?

Thanks in advance!
