### DISCUSSION TITLE
Upgrading from ArgoCD 2.0.5 to 2.4.7 - helm repo add issue

### DISCUSSION THREAD

**Discussion by nikitakogan1** [argoproj/argo-cd#10149] [Q&A]
Hi, 

I am trying to upgrade argoCD version to 2.4.7. I am using "app of apps" application, and each chart is deployed as a wrapper to the real chart.
I know that the new argoCD version contains a breaking change in Helm (since Helm is upgraded), and now we need to use passCredentials flag in order to pass the credentials to the inner charts.
However, after setting the flag i get the following error:

rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add --username ****** --password ****** --pass-credentials myrepo https://myrepo-url/` failed exit status 1: Error: repository name (myrepo) already exists, please specify a different name

example for our Chart.yaml file:

```
name: some-chart-wrapper
version: 1.0.0
apiVersion: v2
dependencies:
  - name: some-chart
    version: 1.20220404.122049
    repository: '@myrepo'
   
```
   
The actual chart is in the wrapper chart dependencies.

I wonder how can i configure argoCD to not add the repo for each chart, Since all charts use the same helm repo.
Or, is there a flag for argoCD helm section to ignore already exist repos?

Thanks,
Nikita.
