### DISCUSSION TITLE
ignoreDifferences

### DISCUSSION THREAD

**Discussion by shyam-ks** [argoproj/argo-cd#10140] [Q&A]
Does this configuration on [application object]
```
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/replicas

```

gets covered by [argocd -cm] 
```
data:
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
    - kube-controller-manager
    jsonPointers:
    - /spec/replicas

```
if we add above in the argocd cm?
