### DISCUSSION TITLE
ingress is still in progress state.

### DISCUSSION THREAD

**Discussion by oliverpark999** [argoproj/argo-cd#10151] [General]
Hello,
If you distribute it using Argo CD, only 'Ingress' is 'Progress'.
It's the same after hours.
After self-testing, it seems that this symptom occurs when the service is configured with 'Service.ClusterIP'.
Configuring 'Service.NodePort' is 'Ingress = Healthy'.
How can Ingress be Healthy in 'Service.ClusterIP'?

Ex
(Healthy)
```
kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  type: NodePort
```

(Progress)
```
kind: Service
apiVersion: v1
metadata:
  name: test-service-02
spec:
  type: ClusterIP

```
