### DISCUSSION TITLE
Checking for the existence of a field in a ApplicationSet Git file generator.

### DISCUSSION THREAD

**Discussion by 1kvin** [argoproj/argo-cd#10196] [Q&A]
hi i am trying to set up applicationSet like this:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service1-app-set
spec:
  generators:
  - git:
      ...
      files:
      - path: "config.json"
  template:
    ...
    spec:
      project: "default"
      source:
        helm:
          valueFiles:
          - 'values-files/service1/{{Versions.Service1}}/values.yaml'
    destination:
        server: '{{Cluster.Server}}'
        namespace: '{{Cluster.Namespace}}'
...
```

and use config.json file like this:

```
{
"Cluster": {
    "Server": "xxx",
    "Namespace": "xxx"
  },
  "Versions": {
	"Service1" : "v1.0",
	"Service2" : "v1.1",
	"Service3" : "v1.2"
  }
}

```
but let's say I don't want to deploy service1 to the environment. I remove the Versions.Service1 entry from the config.json file and get the error:

`Application.argoproj.io "xxxx" is invalid: metadata.labels: Invalid value: "{{Versions.Service1}}": ...`

How can I ensure that in the config file I can specify which services need to be deployed to the environment?
