### DISCUSSION TITLE
How does the ApplicationSet namespace resources?

### DISCUSSION THREAD

**Discussion by bryan-kc** [argoproj/argo-cd#10201] [Q&A] [answered]
Hi folks,

I have a setup where I have a cluster managing several remote clusters. The remote clusters are grouped into their respective dev, stage and prod clusters. This is backed by a helm repository for the cluster that syncs to argocd. The application set looks like and exists on the management cluster. 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  generation: 30
  name: foo-bar-dev
  namespace: argocd-dev
  resourceVersion: '455519786'
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-foo-bar'
    spec:
      destination:
        namespace: foo-bar
        server: '{{server}}'
      project: foo-bar
      source:
        path: .
        plugin:
          env:
            - name: helm_args
              value: '-f values/{{name}}-values.yaml'
          name: argocd-vault-plugin-helm
        repoURL: <redacted>/foo-bar/foo-bar-infra-dev.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

I recently added a component that relies on a community helm chart. This component has the `Release.Namespace` field set to allow it to be installed to any namespace. In my template testing I assumed that it would deploy to the default namespace as it is unset. However, when ArgoCD syncs the app it tries to deploy the resources into the `argocd-dev` namespace on the remote cluster, which doesn't exist. 

I tried to set the `spec.template.spec.destination` field to the default namespace I wanted it to deploy to, but it ignores this and still tries to deploy the application to `argocd-dev` . The deployment has annotations which I believe are from ArgoCD that state it wants to deploy to `argocd-dev`.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: bchiu-hack-cluster
    meta.helm.sh/release-namespace: argocd-dev
  labels:
    app: bchiu-hack-cluster-reloader
    app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/instance: bchiu-hack-cluster-yskr
    chart: reloader-v0.0.118
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: bchiu-hack-cluster
    version: v0.0.118
  name: bchiu-hack-cluster-reloader
  namespace: argocd-dev
spec:
...
```

Can anyone clarify the expected behaviour? I am running on ArgoCD `2.0.3` .

**Comment by jgwest** [comment, marked as answer]
The `template.spec.destination` field you are specifying in your `ApplicationSet` resource is correct. You can verify this by checking the contents of the `Application` resource that the ApplicationSet controller generated, and that it has the correct `.spec.destination.namespace` value.

My guess is what is happening is that the k8s resources in the Git repository you are deploying have a `.metadata.namespace` field defined.


The `namespace` field inside the template of ApplicationSet will only be used if the resource in the Git repository does *not* already have a namespace defined. So in this case, your Deployment's `.metadata.namespace` is overriding the value provided in the Argo CD Application (as generated by ApplicationSet).

Or, said another way, the `.destination.namespace` field of an Argo CD Application does not override the `.metadata.namespace` field of a resource defined in a Git repository.

![image](https://user-images.githubusercontent.com/7594762/183081065-a81ee97a-6630-4dc7-8ab8-e58408741bd1.png)

**Reply by bryan-kc** [reply]
Not quite, which is stumping me a bit.

I have a git repository where I cloned the helm chart, added some sane default `values.yaml` for our deployment -- namely referring to my company's internal image repo,

This is the Chart.yaml of the component in the git repo

```yaml
apiVersion: v2
name: reloader
description: Reloader is an application that will watch ConfigMaps or Secrets and when they are updated they will roll the associated Pods from DeploymentConfigs, Deployments, DaemonSets, StatefulSets or Rollouts.
...
version: v0.0.118
...
appVersion: v0.0.118
sources:
  - https://github.com/stakater/Reloader
dependencies:
  - name: reloader
    version: v0.0.118
    repository: https://stakater.github.io/stakater-charts
```
This is then pushed up to our internal helm repository.

As mentioned before, we have a git repository per grouping of clusters that map to an environment in what we call a Kubernetes runtime. 

```yaml
apiVersion: v3
description: A Helm chart for <redacted> Standard Kubernetes Runtime
name: foo-bar
version: 0.5.1
dependencies:
...
  - name: reloader
    version: v0.0.118
    repository: https://artifactory.ea.com/artifactory/yardmaster-helm-virtual
```

If I `helm template .` in either my mirror repo or the cluster repo, I end up with the objects having the `default` namespace as provided by the `.Release.Namespace` field as it is unset. This is what I expected to happen when deploying to ArgoCD. 

I believe that ArgoCD is overwriting the metadata but i'm not sure on the internals of how this could happen.
