### DISCUSSION TITLE
Setting "eks\.amazonaws\.com/role-arn" as part of helm parameter name

### DISCUSSION THREAD

**Discussion by icicimov** [argoproj/argo-cd#10250] [General]
Hi,

I'm struggling with annotating ServiceAccount for IRSA in EKS in a helm Application which is part of app-of-apps. What I'm trying is set a helm parameter that when passed to helm command on command line looks like this: `--set cluster-autoscaler.rbac.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="<some-value-here>"`. I have the following code in argocd app:

```
{{- if and (.Values.clusterAutoscaler) (.Values.clusterAutoscaler.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
...
    helm: 
      parameters:
      {{ if .Values.clusterAutoscaler.roleArn }}
      - name: cluster-autoscaler.rbac.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"
        value: {{ .Values.clusterAutoscaler.roleArn }}
      {{ end }}
...
{{- end -}}
```
trying to replicate the same but I always get the same error upon sync:
```
Message: one or more objects failed to apply, reason: ServiceAccount "cluster-autoscaler-aws-cluster-autoscaler" is invalid: [metadata.annotations: Invalid value: "\"eks.amazonaws.com/role-arn\"": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "\"eks.amazonaws.com/role-arn\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')] (retried 1 times).
```
so obviously I'm hitting some parsing issue. I tried many combinations of escaping `"eks\.amazonaws\.com/role-arn"` in different way but none worked. Any idea of a solution or workaround? The regex from error message is not very promising as I don't see any reference of `/` in there.

**Comment by jgwest** [comment]
I'm by no means a Helm expert, but my guess is it doesn't like the `"` at the start/end of the annotation name. You could try removing those and running `helm template .` and see if the resulting annotations fields of the ServiceAccount have the expected values. Likewise with `\.`.

**Reply by icicimov** [reply]
Well the actual YAML structure in this case would be:

```
cluster-autoscaler:
  rbac:
    serviceAccount:
      annotations:
         eks.amazonaws.com/role-arn: "<some-value-here>"
```
and the `"` are needed delimiters by Helm so it knows that `eks.amazonaws.com/role-arn` is the final nested element (key in a map `{}`) and `\` is needed so it understands that this is an explicit dot and not a mark of the `map` construct. Otherwise it will keep parsing it as part of the yaml structure and end up with:

```
cluster-autoscaler:
  rbac:
    serviceAccount:
      annotations:
         eks:
           amazonaws:
              com/role-arn: "<some-value-here>"
```
So this is a rule implied by helm itself. What I think is going on here is that the ArgoCD parser steps in, fails to recognize the "rule" and tries to parse a string against a domain regexp that of course is a no go in this case. Maybe if the key was just `eks.amazonaws.com` would work but that does not solve the problem.

Just for the record this works with helm3 `template` or `install --dry-run --debug` from the command line and I get correct resource parsed:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: "cluster-autoscaler"
    app.kubernetes.io/name: "aws-cluster-autoscaler"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-9.19.2"
  name: cluster-autoscaler-aws-cluster-autoscaler
  namespace: cluster-autoscaler
  annotations: 
    eks.amazonaws.com/role-arn: <some-value-here>
automountServiceAccountToken: true
```
