### DISCUSSION TITLE
Use annotations with special characters

### DISCUSSION THREAD

**Discussion by cnd4** [argoproj/argo-cd#10277] [Q&A] [answered]
Hello,

I did not find my answer in the documentation or in any issue, please redirect me if I can find it anywhere.

In an `ApplicationSet` template, I see we can use [annotations from cluster secret](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/) with the cluster generator, which is great.

Now, I have an annotation with dot and slashed, like `app.project.com/overlay: "overlay-name"`. How to use it in a template, for example:

```yaml
spec:
  source:
    repoURL: '…'
    path: 'manifests/overlays/{{metadata.annotations["app.project.com/overlay"]}}'
```

I tried multiple syntaxes, each do not work:

* `metadata.annotations["app.project.com/overlay"]`
* `metadata.annotations[\'app.project.com/overlay\']` (ArgoCD really did not like this one)
* `metadata.annoations."app.project.com/overlay"`

Some my questions are:

* is it possible?
* if yes, how and can it be documented for everyone? (I would be happy to make a PR for this after reading the contribution guidelines of course)

Thanks in advance for any help!
