### DISCUSSION TITLE
How can we fetch UserInfo in ArgoCD notifications templates.

### DISCUSSION THREAD

**Discussion by Coder63** [argoproj/argo-cd#10294] [Q&A] [answered]
Hi All, 

We are running ArgoCD 2.4.3 and using slack notification with all the templates. Curious if we can add User details too who synced the charts as part of the message ?  If so , how can we do it please provide a direction ? 

```
  template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced  << by {{ Username/ Email}} >> at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
```

**Comment by pasha-codefresh** [comment, marked as answer]
https://argocd-notifications.readthedocs.io/en/stable/templates/#functions

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  template.my-custom-template-slack-template: |
    message: "Author: {{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}"
```
