### DISCUSSION TITLE
Deletion issue of Ingress Objects - API version "confusion"

### DISCUSSION THREAD

**Discussion by xakraz** [argoproj/argo-cd#10374] [Q&A]
Hi there,

## Context

* We are in the process of handling k8s 1.22 deprecated API removal, like `extension/v1beta1` of `ingresses` replaced by `networking.k8s.io/v1`.
* We are using Argocd "App of Apps" pattern.
* We are running argo-cd `v2.0.3+8d2b13d` (yes we need to upgrade 😅 )

## Observation

When using the cascaded deletion, we had `Applications` that were stuck in deletion while waiting for leaf resources to be deleted.

## Troubleshooting

In the App of app `Application` objects we noticed

```
.status.operationState.syncResult.resources

- group: networking.k8s.io
  hookPhase: Running
  kind: Ingress
  message: ingress.networking.k8s.io/<APP_NAME> unchanged
  name: <APP_NAME>
  namespace: x
  status: Synced
  syncPhase: Sync
  version: v1
```

whereas in 

```
.status.resources

- group: extension
  health:
    message: Pending deletion
    status: Progressing
  kind: Ingress
  name: <APP_NAME>
  namespace: x
  requiresPrunning: true
  status: unknown
  version: v1beta1
```

## Question

Why are the API version different between the `.status.operationState.syncResult.resources` and `.status.resources` ?

- [x] Committed app manifests were in `networking.k8s.io/v1`
- [x] we checked the exiting ingress object, which was also reported as `networking.k8s.io/v1` by kubectl

Our hypothesis is that our current version of Argo-cd "finalizer" only supports this kind of "hard-coded" API version of the ingress and is stuck since it does not found the objects it is looking for with the strict API version. But more precision are welcome.

As a workaround, we manually delete the ingresses objects with the `networking.k8s.io/v1` API version and everything ends ok.

In advance, many thanks for your time, help and explanations 🙏🏻
