### DISCUSSION TITLE
Values file from parent chart not overwriting child chart

### DISCUSSION THREAD

**Discussion by SomniVertix** [argoproj/argo-cd#10397] [Q&A]
Problem:

I have two charts: one child chart that actually has the template yamls, and one parent / wrapper chart that just points to the nexus repository its in. Both the child and parent chart have values files. 

Application.yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commons
  namespace: argocd
spec:
  destination:
    name: qa-east
    namespace: ""
    server: ""
  source:
    path: "dummy-charts/commons"
    repoURL: >-
      git@myrepo.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - "./commons_qa.yaml"
  project: common 
  ```

Parent Chart.yaml:
```yaml
apiVersion: v1
name: commons-wrapper
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: commons
  version: 2.1.1
  repository: https://my-helm/repository/Helm
```

Child Chart.yaml
```yaml
apiVersion: v1
name: commons
description: A global Helm chart for common
type: application
version: 2.1.1
appVersion: 2.1.1
```

When I look at argo, its still using the values.yaml from the child chart instead of overriding where the parent chart values.yaml says.
