### DISCUSSION TITLE
Acccessing notification annotation value

### DISCUSSION THREAD

**Discussion by brunocascio** [argoproj/argo-cd#10396] [Q&A] [answered]
Hi everyone!

I'm trying to access the annotation value in order to configure my webhook notification:

My application is defined as:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: dev
  template:
    metadata:
      name: 'app-{{environment}}'
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.newrelic: "123456789"   # <-- here my annotation
    spec:
      project: "app"
      source:
        repoURL: https://example.com/repo.git
        targetRevision: HEAD
        path: '{{environment}}/'
      destination:
        name: '{{cluster}}'
        namespace: 'app-{{environment}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
```

This is my config map:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.newrelic: |
    url: https://api.newrelic.com/v2/applications
    headers:
      - name: X-Api-Key
        value: <redacted>
      - name: Content-Type
        value: application/json

  template.newrelic-record-deployment: |
    webhook:
      newrelic:
        method: POST
        path: "/{{ how-to-access-annotation-value?? }}/deployments.json" # <--- How to access the annotation value?
        body: |
          {
            "deployment": {
              "revision": "{{ .app.status.sync.revision }}",
              "changelog": "{{ .app.metadata.name }}",
              "description": "Synced {{ .app.metadata.name }}",
              "user": "argocd",
              "timestamp": "{{ .app.status.operationState.startedAt }}"
            }
          }
  
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [newrelic-record-deployment]
```
