### DISCUSSION TITLE
Passing Env variables in argo-cd config management plugin

### DISCUSSION THREAD

**Discussion by goelshubham** [argoproj/argo-cd#10412] [Q&A]
Hi All - I have a question w.r.t argocd [config management plugin](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/) Env variable passing. I have implemented a use-case of CMP in conjunction with ApplicationSet CRDs and will try to explain in detail.

My goal is to deploy a service in different namespaces of a k8s cluster. Because I want to deploy this service in different namespaces, I want to have some variable configurations for each namespace. Things like kuberneres namespace itself, number of replicas, different AWS elastic load balancer etc. In order to this I am making use ApplicationSet which I know can be used with generators and can create many Application CRD which does the eventual deployment to k8s.

Below is my ApplicationSet. I am using git generator where I will configure some configuration yaml files. The goal is that this application-set when created in ArgoCD, will created `n`unique Application CRD for `n` configuration files at location `test/appset/stage/stage-euw1/eu-west-1/core/test-app-simple5/k2Sharding-shards/shard-*.yaml`. Each configuration file contains key-value pairs specific to deployment in a namespace. I know the parameters configured in the git generator files can be accessed in the template section of ApplicationSet as well as in the ENV section of plugin.

In ApplicationSet, I am using cmp and my ApplicationSet looks like this. 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  labels:
    app: test-app-simple5
    cluster: core
    region: eu-west-1
  name: test-app-simple5-ddfd5ed21ebcb44433ca9f4c78fc8f8b
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: test/appset/stage/stage-euw1/eu-west-1/core/test-app-simple5/k2Sharding-shards/shard-*.yaml
      repoURL: https://github.com/segmentio/argocd-configuration.git
      revision: HEAD
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  template:
    metadata:
      name: '{{namespace}}-test-app-simple5-ddfd5ed21ebcb44433ca9f4c78fc8f8b'
    spec:
      destination:
        namespace: '{{namespace}}'
        server:'{{kubernetes-cluster}}'
      project: default
      source:
        path: test/stage/stage-euw1/eu-west-1/core/test-app-simple5/test-app-simple5
        plugin:
          env
             - name: replicas  // this will be configured in shard-*.yaml of generator
               value: {{replicas}}
             - name: namespace
                value: {{namespace}} 
        repoURL: https://github.com/segmentio/argocd-configuration.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
status: {}
```

Below is my argocd config management plugin configuration. In the command section, I am going to execute a tool `k2`. It is a home-grown tool that takes a custom yaml file (`k2generatorinput.yaml`) as an input and generates k8s manifest files. Because cmp works when we print out the k8s manifest to standard out, my command `k2 generate app -f $PWD/k2generatorinput.yaml --print` will also do that.

```
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: k2
spec:
  version: v1.0
  generate:
    command: [sh, -c, "k2 generate app -f $PWD/k2generatorinput.yaml --print"]
  discover:
    find:
      command: [sh, -c, find . -name k2generatorinput.yaml]
```

Now the problem that I ran into is - because the final k8s files has to be different for each deployment eventually done by Application CRD created by ApplicationSet CRD (specified above), how do I pass my dynamic parameters configured in git generators of ApplicationSet for different deployments done by Application. I know that plugin `generate` and `init` commands can access the env of plugin and adds a prefix `ARGOCD_ENV`. 

If my custom `K2GeneratorInput.yaml` file looks like this, should I inject dynamic parameters for `replicas` and `namespace` like below?

```
apiVersion: platform.segment.com/v1alpha1
kind: K2GeneratorInput
metadata:
  creationTimestamp: null
  name: test-app-simple5-stage-euw1-core
  namespace: $ARGOCD_ENV_namespace
spec:
  target:
      cluster: stage-euw1:eu-west-1:core
      name: stage-euw1-core
      pool: main
      replicas: $ARGOCD_ENV_replicas
```

Please let me know if this question is not clear and I will try my best to explain it further.
