### DISCUSSION TITLE
Sentry release using resource hooks

### DISCUSSION THREAD

**Discussion by sondrelg** [argoproj/argo-cd#10526] [Q&A] [answered]
We use Sentry for application error management, which lets you enable a bunch of cool features if you use [`releases`](https://docs.sentry.io/product/releases/). To enable it, you just have to POST the latest revision when you release a new app version.

I couldn't find a documented way to do this with argo, but thought that the [ArgoCD resource hooks](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#usage) looked promising. Sending a POST request to Sentry using the `PostSync` hook seems like it should do what I want.

This is my job spec:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-release
  namespace: <my namespace>
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  ttlSecondsAfterFinished: 6000  # for testing
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:7.85.0
          command: [ "curl" ]
          args: [
            "-L",
            "-v",
            "https://sentry.io/api/0/organizations/<my org>/releases/$(ARGOCD_APP_REVISION)/deploys/",
            "-H", "Authorization: Bearer $(AUTH_TOKEN)",
            "-H", "Content-Type: application/json",
            "-d", '{"environment":"staging", "projects": ["<my project>"]}'
          ]
          envFrom:
            - secretRef:
                name: sentry  # contains my AUTH_TOKEN
      restartPolicy: Never
  backoffLimit: 1
```

This works, except `ARGOCD_APP_REVISION` is not found. 

The documentation is a bit sparse, but I was hoping the [build environment vars](https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/) might be available in some way. I've tried using `{{ .Values.revision }}` where revision is mapped to `$ARGOCD_APP_REVISION`. That also didn't work, unfortunately.

Any ideas? Is this a dead end?

**Comment by sondrelg** [comment, marked as answer]
Got this to work by making the following change to the `Application` CRD:

```yaml
spec:
  source:
    helm:
      parameters:
        - name: revision
          value: $ARGOCD_APP_REVISION
```

And the following to my deployment
```yaml
env:
  - name: ARGOCD_APP_REVISION
    value: ${{ .Values.revision }}
