### DISCUSSION TITLE
Configure webhook notifications with annotations

### DISCUSSION THREAD

**Discussion by jryberg** [argoproj/argo-cd#10581] [Q&A] [answered]
Hi,

I'm having a hard time to make a webhook notification to trigger. I can manually execute it and the template payload ends up in the webhook but I have not been able to automatically trigger it 

This works just fine:
`argocd admin notifications template notify azure azure-cloud-tests --recipient azure`

I tried to apply default like the example bellow and it does not trigger any project
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
data:
  service.webhook.azure: |
    url: https://some.azure
  template.azure: |
    webhook:
      azure:
        method: POST
        body: |
          {
            "description": "ArgoCD",
            "status": "{{.app.status.operationState.phase}}",
            "target_url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "context": "continuous-delivery/{{.app.metadata.name}}"
          }
  subscriptions: |
    - recipients:
      - azure
      triggers:
      - on-created
      - on-deleted
      - on-deployed
      - on-health-degraded
      - on-sync-failed
      - on-sync-running
      - on-sync-status-unknown
      - on-sync-succeeded

```

I also tried to add annotation when I create the app using the API and it does not work
```
        self.application_template = {
              "metadata": {
                "name": "replace me",
                "annotations": {
                  "notifications.argoproj.io/subscribe.on-created.azure": ""
                }
              },
              "spec": {
                "source": {
                  "repoURL": "git@github.com:some-git-repo.git",
                  "path": "replace me",
                  "targetRevision": "develop"
                },
                "destination": {
                  "server": "https://something.azmk8s.io:443"
                },
                "project": "azure-cloud-tests",
                "syncPolicy": {
                  "automated": {},
                  "syncOptions": [
                    "CreateNamespace=true",
                    "PruneLast=true"
                  ]
                }
              }
            }
```

Any suggestion how to make it work?

Regards Johan

**Comment by kostis-codefresh** [comment, marked as answer]
What do the logs from the notification controller say?

**Reply by jryberg** [reply]
> What do the logs from the notification controller say?

Not much, repeating with similar like this over and over again with different application names
```
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-created result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-deleted result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-deployed result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-health-degraded result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Processing completed" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Start processing" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-deleted result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-deployed result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-health-degraded result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-sync-failed result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-sync-running result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-sync-status-unknown result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-sync-succeeded result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Trigger on-created result: []" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:51Z" level=info msg="Processing completed" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
time="2022-09-14T11:58:52Z" level=info msg="Start processing" resource=argocd/cloud-integrations-eac41f7c-21e5-11ed-80cc-27244b6b300a
```

**Reply by kostis-codefresh** [reply]
I would change the loglevel of controller to something like "debug" and try again.

**Reply by jryberg** [reply]
With debug I got this message
time="2022-09-15T06:40:44Z" level=debug msg="Failed to execute condition of trigger on-created: trigger 'on-created' is not configured" resource=argocd/cloud-integrations-813b4500-f2ff-4949-b717-b92903117b34

I guess something is missing. I have no triggers defined in my example above..

**Reply by jryberg** [reply]
I tried to add defaultTriggers but I still got the same message. I'm happy for now to use "azure" webhook for everything. Once working I would like to only apply it for applications with the annotation 
```
                "annotations": {
                  "notifications.argoproj.io/subscribe.on-created.azure": ""
```

Updated argocd-notifications-cm
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
data:
  service.webhook.azure: |
    url: https://some.azure
  template.azure: |
    webhook:
      azure:
        method: POST
        body: |
          {
            "description": "ArgoCD",
            "status": "{{.app.status.operationState.phase}}",
            "target_url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "context": "continuous-delivery/{{.app.metadata.name}}"
          }
  defaultTriggers: |
    - on-created
    - on-deleted
    - on-deployed
    - on-health-degraded
    - on-sync-failed
    - on-sync-running
    - on-sync-status-unknown
    - on-sync-succeeded

  subscriptions: |
    - recipients:
      - azure
      triggers:
      - on-created
      - on-deleted
      - on-deployed
      - on-health-degraded
      - on-sync-failed
      - on-sync-running
      - on-sync-status-unknown
      - on-sync-succeeded
```
