### DISCUSSION TITLE
How to trust "Healthy" triggers when a POD has restarting containers? Prevent false positives

### DISCUSSION THREAD

**Discussion by jryberg** [argoproj/argo-cd#10609] [Q&A]
Hi,

I have an interesting problem with triggers for new applications.

It's a deployment with a POD that has two containers. One of the containers are constantly restarting (simulated error)

My problem is that the notification system are sending healthy triggers even if the POD never becomes "healthy". I think it's kind of healthy when Kubernetes are restarting the POD, or starting it the first time for a second or two during container start-up phase but it's never "stable".

I tried many different configurations and I have only been able to delay the misleading healthy notification by a couple of minutes but it's still triggered. 

The application flaps between status "Healthy" and "Progressing". I want it to be "Healthy" for X number of minutes without any state change in between before we send notifications to the upstream system.

This is what I tried

```
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.operationState.syncResult.revision
      send:
      - on-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

```
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.operationState.syncResult.revision
      send:
      - on-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status != 'OutOfSync'
```

```
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.operationState.syncResult.revision
      send:
      - samurai-on-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status != 'OutOfSync' and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() >= 2
```

Is there any way of make a trigger that ensure a stable state for X number of minutes without any state changes in between? Like checking against a last state change timestamp or something? 

We are automating deployments and it's important that we don't send false positives to the receiving software. 

Best regards Johan
