### DISCUSSION TITLE
Can you authenticate to Google Artifact Registry with a short-lived token to retrieve helm charts?

### DISCUSSION THREAD

**Discussion by andrewspiers-csiro** [argoproj/argo-cd#10644] [Q&A] [answered]
This is related to https://github.com/argoproj/argo-cd/discussions/5248
except I'm using Google, not AWS, and want to use token authentication.

I am trying to use argocd with Helm and Google Artifact Repository as documented
here:

https://cloud.google.com/artifact-registry/docs/helm/authentication#token

which says to:

    gcloud auth application-default print-access-token | helm registry login -u oauth2accesstoken \
    --password-stdin https://LOCATION-docker.pkg.dev

Which works by passing a short-lived token obtained from Google's metadata
server to Helm to use as an authentication credential.
Is there any way to use this pattern within ArgoCD?

The example for an oci repository passes a username and a password, which would
work, using username oauth2accesstoken  and passing that token as a password.

    argocd repo add helm-oci-registry.cn-zhangjiakou.cr.aliyuncs.com --type helm --name stable --enable-oci --username test --password test

Except how would you go about updating that token (or fetching one on demand?

**Comment by alen-z** [comment]
Our approach was to build a plugin and include `gcloud` in the Argo CD container image. Would be nice to have more streamlined offering from Argo CD that would accept different OCI registry authentication methods for different cloud providers.

**Reply by andrewspiers-csiro** [reply]
Thanks @alen-z  , do you mean a config management plugin to argo? ( ie https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/ ) or a helm plugin ?

**Comment by akozhuharov** [comment]
We have a similar setup with helm registry login and a google Service Account JSON file. Our setup is to mount the Service Account JSON as a volume in the repo-server containers and use a ArgoCD plugin to authenticate before templating. https://cloud.google.com/artifact-registry/docs/helm/authentication#json-key

**Comment by sthomson-wyn** [comment]
I've set it up with a simple cronjob that uses workload identity and updates a secret with the short-lived acess token. 

Was mostly a poc... permissions can probably be tightened up

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: argocd-gar-reader@my-project.iam.gserviceaccount.com
  name: argocd-gar-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-gar-reader
rules:
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - get
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-gar-reader
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-gar-reader
    namespace: argocd
roleRef:
  kind: ClusterRole
  name: argocd-gar-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gar-reader-cred-updater
spec:
  schedule: "*/45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: argocd-gar-reader
          containers:
            - name: my-gcloud-kubectl-container
              image: my-gcloud-kubectl-container
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - kubectl delete secret gar-repo-secret --namespace argocd --ignore-not-found=true &&
                  kubectl create secret generic gar-repo-secret --namespace argocd
                  --from-literal=enableOCI=true
                  --from-literal=name=my-reg
                  --from-literal=type=helm
                  --from-literal=url=us-docker.pkg.dev/my-reg
                  --from-literal=username=oauth2accesstoken
                  --from-literal=password=$(gcloud auth application-default print-access-token)
                  && kubectl label secret gar-repo-secret --namespace argocd "argocd.argoproj.io/secret-type=repository"
          restartPolicy: OnFailure
```

**Comment by gosharo** [comment]
I think the best approach to make workload identify work, is to use this auth helper: 
https://github.com/GoogleCloudPlatform/docker-credential-gcr 
with placing the binary inside the repo-server container to authenticate and configure a docker registry 
can be performed using `docker-credential-gcr configure-docker -registries ... ` at initialization 
kaniko using it .. 
https://github.com/GoogleContainerTools/kaniko/blob/cf9a334cb027e6bc6a35c94a3b120b34880750a9/deploy/Dockerfile#L26

**Reply by andrewspiers-csiro** [reply]
This looks like a fantastic solution. Work has taken a bit of a left turn so I won't be able to test  this out for a little while but this and the suggestion of using a cronjob to keep the token up to date should help me put something together.

**Reply by gosharo** [reply]
there is no reason to use a cronjob, each time helm requests a registry it authenticate with that helper, which taking dynamically the token..

**Reply by jacek-jablonski** [reply]
@gosharo what would be the best place to perform initialization command?

**Reply by gosharo** [reply]
@jacek-jablonski at startup

**Reply by jacek-jablonski** [reply]
I can confirm that setting up workload identity with docker-credential-gcr works. However it is far from easy and obvious, so I'll create an issue for support for tools like docker-credential-gcr.

Below you can find a patch for argocd-repo-server that made it work (aside from setting up workload identity):

```yaml
- op: replace
  path: /spec/template/spec/containers/0/command
  value:
    - "sh"
    - "-c"
    - docker-credential-gcr configure-docker -registries xxx-docker.pkg.dev
      && entrypoint.sh argocd-repo-server --redis $(ARGOCD_REDIS_SERVICE):6379

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /usr/local/bin/docker-credential-gcr
    name: docker-credential-gcr
    subPath: docker-credential-gcr
    readOnly: true

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /home/argocd/.docker
    name: docker-config

- op: add
  path: /spec/template/spec/initContainers/-
  value:
    command:
      - sh
      - -c
      - "wget -O /tmp/docker-credential-gcr.tar.gz https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.6/docker-credential-gcr_linux_amd64-2.1.6.tar.gz
        && tar -xzf /tmp/docker-credential-gcr.tar.gz -C /tmp
        && mv /tmp/docker-credential-gcr /var/run/docker-credential-gcr/"
    image: busybox:latest
    name: copy-docker-credential-gcr
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
      - mountPath: /var/run/docker-credential-gcr
        name: docker-credential-gcr

- op: add
  path: /spec/template/spec/volumes/-
  value:
    emptyDir: {}
    name: docker-credential-gcr

- op: add
  path: /spec/template/spec/volumes/-
  value:
    emptyDir: {}
    name: docker-config
```

**Reply by soudaburger** [reply]
@jacek-jablonski this looks great! I have argo patched, but how do I then go about actually wiring argocd to the artifact registry? It's that last piece I'm not fully understanding.  Any help would be greatly appreciated!  Can I add the OCI repository (GAR) through the UI? Or do I have to use the CLI?

**Reply by gosharo** [reply]
`docker-credential-gcr configure-docker -registries xxx-docker.pkg.dev` will authenticate with the artifact registry @soudaburger  soudaburger

**Reply by jacek-jablonski** [reply]
@soudaburger this is rather not recommended approach. Better use `external-secrets` with `GCRAccessToken` for cleanest solution.
https://github.com/argoproj/argo-cd/issues/11717#issuecomment-1377058419

**Reply by soudaburger** [reply]
Thanks for the feedback!! We ended up scratching our desire for OCI with GAR since kustomize + helm don't seem to play too nicely within argo for that.  We ended up settling on an internal `chart-museum` deployment backed by GCS which is sufficient enough for our use case and keeps things fairly trivial as far as kustomize and argo go.

**Reply by hanikesn** [reply, marked as answer]
I have a slightly more minimal solution for the argo helm chart using GKE workload idenity:
```
  repoServer:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: argocd@PROJECT.iam.gserviceaccount.com
    initContainers:
    - name: download-tools
      image: alpine:3
      command: [ sh, -c ]
      args:
      - |
        cd /var/run/docker-credential-gcr
        wget -qO - https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.8/docker-credential-gcr_linux_amd64-2.1.8.tar.gz | tar xz
        PATH=.:$PATH HOME=/var/run/config docker-credential-gcr configure-docker
        chmod +r /var/run/config/.docker/config.json
      volumeMounts:
      - mountPath: /var/run/docker-credential-gcr
        name: docker-credential-gcr
      - mountPath: /var/run/config/.docker
        name: docker-config
    volumeMounts:
    - mountPath: /usr/local/bin/docker-credential-gcr
      name: docker-credential-gcr
      subPath: docker-credential-gcr
      readOnly: true
    - mountPath: /home/argocd/.docker
      name: docker-config
      readOnly: true
    volumes:
    - emptyDir: {}
      name: docker-credential-gcr
    - emptyDir: {}
      name: docker-config
```
