### DISCUSSION TITLE
JumpCloud SSO Support

### DISCUSSION THREAD

**Discussion by hakmkoyan** [argoproj/argo-cd#10658] [Q&A] [answered]
Hi.
Does your application support Single Sign On for JumpCloud Custom SAML app, if you answer is yes, below will be my info about my mess in that with all configurations that I have, can you help me with that mess?
**So here is the thing, I created custom SAML app in JumpCloud, provided configurations in argocd chart's values.yaml file undex dex.config like this one below:**

_url: "https://localhost:8080"
  dex.config: |
      connectors:
        - type: saml
          id: jumpcloud
          name: JumpCloud
          config:
            ssoURL: https://sso.jumpcloud.com/saml2/saml2
            caData: | <certificate provided from jumpcloud custom saml app>
            usernameAttr: username
            emailAttr: email
            groupsAttr: group_

**And here is the configuration of JumpCloud custom SAML app :**
_IdP Entity ID: jumpcloud
SP Entity ID: https://localhost:8080/api/dex
ACS URL: https://localhost:8080
SAMLSubject NameID: email
SAMLSubject NameID Format: urn:oasis:names:tc:SAML:1.0:nameid-format:unspecified
Signature Algorithm: RSA-SHA256
Login URL: https://localhost:8080
IDP URL: https://sso.jumpcloud.com/saml2/saml2
User Attributes: 
  usernameAttr: username
  emailAttr: email_

So, after these all, I installed argocd chart with custom values.yaml file, it ran perfectly, **BUT**, when I clicked **Login via JUMPCLOUD**, At first it asked me my jumpcloud username-password, I entered, after that it again redirected me to login page.
The same thing happens when I call command from CLI _argocd login localhost:8080 --sso --insecure_.

I want to understand, does this all mess happens because ArgoCD doesn't support JumpCloud or it is my fault?

**Comment by jessesuen** [comment, marked as answer]
We support SAML through the use of https://dexidp.io/. So the answer to your question is really if dex can support it. Based on a basic search in their git repo, it does appear others are using it.

https://github.com/dexidp/dex/search?q=jumpcloud&type=issues

**Comment by mconigliaro** [comment]
FWIW, here's a JumpCloud config that worked for me:

```yaml
logger:
  level: debug
connectors:
  - type: saml
    id: jumpcloud
    name: JumpCloud
    config:
      ssoURL: https://sso.jumpcloud.com/saml2/argocd
      caData: |
        <your base64 encoded certificate data>
      usernameAttr: username
      emailAttr: email
      groupsAttr: memberOf
```

On the JumpCloud side, I set the following fields on the SSO tab of my app:

| Name | Value | Notes |
| - | - | - |
| IdP Entity ID | https://example.com/api/dex/callback | Dex callback endpoint of your Argo CD server |
| SP Entity ID | https://example.com/api/dex/callback | Dex callback endpoint of your Argo CD server |
| ACS URL | https://example.com/api/dex/callback | Dex callback endpoint of your Argo CD server |
| IDP URL | https://sso.jumpcloud.com/saml2/argocd | Corresponds with `ssoURL` above

Note that JumpCloud doesn't seem to send any attributes by default, which will probably result in `Failed to authenticate: response did not contain a AttributeStatement` in your Dex logs. I fixed this by going into the SSO tab of my app and setting the following attributes:

| Service Provider Attribute Name | JumpCloud Attribute Name | Notes |
| - | - | - |
| username | username | Corresponds with `usernameAttr` above |
| email | email | Corresponds with `emailAttr` above |

I also enabled "include group attribute" under "GROUP ATTRIBUTES" with a value of `memberOf` (to match the `groupsAttr` above). This is needed if you want to use JumpCloud's groups in your RBAC config.

Next I had to kill my `argocd-server` pod and clear the cookies on my browser (not sure why, but the "LOG IN VIA JUMPCLOUD" button just kept redirecting me back to the login page until I did this). Now I get messages like this in my Dex logs and everything seems to be working:

```
time="2023-02-27T18:51:34Z" level=info msg="login successful: connector \"jumpcloud\", username=\"example\", preferred_username=\"\", email=\"example@example.com\", groups=[\"foo\", \"bar\"]"
```

**Reply by mconigliaro** [reply]
I'm back after finding [this](https://dexidp.io/docs/connectors/saml/):

> WARNING: The SAML connector is unmaintained, likely vulnerable to authentication bypass vulnerablities, and is under consideration for deprecation (see [#1884 ](https://github.com/dexidp/dex/discussions/1884)). Please consider switching to OpenID Connect, OAuth2, or LDAP for identity providers that support these protocols.

Here's how to set up SSO with OpenID Connect and JumpCloud (no Dex required):

1. Add a new OpenID Connect application in JumpCloud:
    a. Redirect URIs: `https://<ARGO CD HOSTNAME>/auth/callback`
    b. Login URL: `https://<ARGO CD HOSTNAME>/auth/login`
    c. User attribute mapping: `email` -> `email`
    d. Include group attribute: `groups`

2. Helm values:

    ```yaml
    configs:
      cm:
        oidc.config: |
          name: JumpCloud
          issuer: https://oauth.id.jumpcloud.com/
          clientID: <YOUR CLIENT ID>
          clientSecret: <YOUR CLIENT SECRET>
    dex:
      enabled: false
    ```

Much simpler, and this way actually allows you to log in via the icons in the JumpCloud console.

**Reply by mconigliaro** [reply]
And here's how to do the same thing with Okta:

1. Create new `OIDC - OpenID Connect`/`Web Application` integration
  a. Sign-in redirect URIs: `https://<ARGO CD HOSTNAME>/auth/callback`
  b. Sign-out redirect URIs: None
  c. Login initiated by: `Either Okta or App`
  d. Application visibility: `Display application icon *`
  e. Initiate login URI: `https://<ARGO CD HOSTNAME>/auth/login`
  f. Groups claim filter: `groups`, `Matches regex`, `.*`

2. Helm values:

    ```yaml
    configs:
      cm:
        oidc.config: |
          name: Okta
          issuer: https://<YOUR SUBDOMAIN>.okta.com
          clientID: <YOUR CLIENT ID>
          clientSecret: <YOUR CLIENT SECRET>
    dex:
      enabled: false
    ```
