### DISCUSSION TITLE
How to use Helm Flow Control with Argocd list Generator

### DISCUSSION THREAD

**Discussion by lequocanh662000** [argoproj/argo-cd#10668] [Q&A]
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-appsets
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: frontend1
            env: dev
            server: https://kubernetes.default.svc
          - appName: frontend2
            env: stg
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{ printf "{{env}}" }}-{{ printf "{{appName}}" }}'
      annotations:
        notifications.argoproj.io/subscribe.sync-operation-change.slack: ilt-argo-notifications
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/inspirelab/guild/guild-infra-argocd.git
        targetRevision: HEAD
        path: helm/{{ printf "{{appName}}" }}/{{ printf "{{env}}" }}
      destination:
        server: '{{ printf "{{server}}" }}'
        namespace: '{{ printf "{{env}}" }}-{{ printf "{{appName}}" }}'

      {{- if eq {{ printf "{{env}}" }} "dev" }}
      syncPolicy:
        syncOptions: 
        - CreateNamespace=true
        automated:
          selfHeal: true
        prune: true
      {{ else }}
      syncPolicy: {}
      {{- end }}
```

My goals: Deploy multiple applications in different environments (dev, staging, production) -> So, I use Argocd list generator + Applicationset file + Helm to achieve that.
The Error occur in the if statement. 
The Error log is:

```
Error: INSTALLATION FAILED: parse error at (mychart/templates/appsets.yaml:31): unexpected "{" in operand
```
Can u guys please help me. I am just a newbie
