### DISCUSSION TITLE
Unable to create an application from a GitHub private repository.

### DISCUSSION THREAD

**Discussion by tominaga-fosterlink** [argoproj/argo-cd#10701] [Q&A]
I'm trying to create an application from our GitHub private repository with ArgoCD, but an error occurred as shown below.
Is something missing in my manifest?

ex.) credentials are masked.

command:
`kubectl apply -n argocd -f secret.yaml`
`kubectl apply -n argocd -f application.yaml`

application.yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ****
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
spec:
  project: default
  source:
      repoURL: https://github.com/****/****.git
      path: manifests/****/stg
      targetRevision: feature/****
      helm:
        passCredentials: true
        valueFiles:
          - values.yaml
  destination:
      server: https://kubernetes.default.svc
      namespace: ****
  syncPolicy:
    automated:
      selfHeal: true
```

secret.yaml:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://raw.githubusercontent.com/****/charts/feature/****/stable/
  name: charts
  username: ****
  password: ****
---
apiVersion: v1
kind: Secret
metadata:
  name: repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/****/charts
  username: ****
  password: ****
```

https://github.com/****/****.git - manifests/****/stg/Chart.yaml:
```yaml
apiVersion: v2
name: ****
type: application
version: 1.0.0

dependencies:
  - name: ****
    version: "1.0.0"
    repository: "https://raw.githubusercontent.com/****/charts/feature/****/stable/"
```

command:
`argocd app get **** --hard-refresh`

result:
```powershell
ComparisonError  rpc error: code = Unknown desc = `helm repo add --username ****** --password ****** --pass-credentials charts https://raw.githubusercontent.com/****/charts/feature/****/stable/` failed exit status 1: Error: repository name (charts) already exists, please specify a different name  2022-09-26 14:33:19 +0900 JST
```

command:
`argocd version`

result:
```
argocd: v2.4.12+41f54aa
  BuildDate: 2022-09-16T01:26:26Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.4.12+41f54aa
  BuildDate: 2022-09-16T01:26:26Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: windows/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in %PATH%
  Helm Version: v3.9.2+g1addefb
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by jannfis** [comment]
The error message suggests that you already have configured another Helm type repository with the name `charts`.

```
stringData:
  type: helm
  url: https://raw.githubusercontent.com/****/charts/feature/****/stable/
  name: charts
```

Try to set `name` portion of your repository secret's `.data` to something else

On a side node, your version output shows:

```
argocd-server: v2.4.12+41f54aa
  BuildDate: 2022-09-16T01:26:26Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: windows/amd64
```

Are you running Argo CD server on a Windows cluster?
