### DISCUSSION TITLE
Why is the list generator treating 'values' in a special manner

### DISCUSSION THREAD

**Discussion by aturetta** [argoproj/argo-cd#10898] [General]
I'm trying to use applicationSet with the list generator, but there is something I don't understand: why is the 'values' key treated in a special way?

My test is trying to generate an app from an helm chart, and I want to pass value overrides from a list generator (which basically means inline in the applicationSet definition)

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cd
spec:
  generators:
  - list:
      elements:
      - appName: argocd
        chart: argo-cd
        relName: argocd
        project: cd
        namespace: newdeploy
        cluster: https://kubernetes.default.svc
        repo: https://argoproj.github.io/argo-helm
        chartVersion: "0"
        values: 
          values: |
            server:
              configEnabled: 'true'
            
  template:
    metadata:
        name: '{{ appName }}'
    spec:
        project: '{{ project }}'
        source:
            helm:
              values: |-
                {{ values }}
              releaseName: '{{ relName }}'
            repoURL: '{{ repo }}'
            targetRevision: '{{ chartVersion }}'
            chart: '{{ chart }}'
        destination:
            server: '{{cluster}}'
            namespace: '{{ namespace }}'
```
If I define the appset like above, no matter what I try, the application generated will have '{{values}}' unparsed placeholder on it

if I change it as follows:
```
        chartVersion: "0"
        mytest: |
          server:
            configEnabled: 'true'
(... omissis...)
            helm:
              values: |-
                {{ mytest }}
```
The application is generated as you would expect (beware, the generated app will not work, on purpose: this thread is about the parsing)

by reading the code at [applicationset/generators/list.go](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/list.go) I understand that the values key is interpreted as a map of (_key_,_string_) tuples and I wonder why (as far as I know no other generator is treating 'values' in a special key.)

And why there is no way of having 'values' replaced in the app template.

Hope someone might enlighten me
