### DISCUSSION TITLE
YAML literal blocks changing into folded blocks in Argo

### DISCUSSION THREAD

**Discussion by lanmarti** [argoproj/argo-cd#10977] [Q&A]
Hi,
I've got a few configmaps of which the YAMLs are defined using literal blocks, e.g.:
```
apiVersion: v1
data:
  multi-line.conf: |
    foo
    bar
kind: ConfigMap
metadata:
  name: data-map
```
When I dryrun these through kubectl, or use them as resources in kustomize, the configmaps are unmodified. However, if I let ArgoCD track these configmaps as part of an application, the manifests sometimes change the literal blocks into folded blocks with newlines inbetween the actual lines, like so:
```
apiVersion: v1
data:
  multi-line.conf: >
    foo

    bar

kind: ConfigMap
metadata:
  name: data-map
```

There can be multiple entries in a single configmap, and some of them might get changed to folded blocks while others remain as literal blocks. I haven't been able to figure out the trigger. I'm not sure the problem lies with ArgoCD and I haven't had the time to properly test whether the content of the field matters. I've done a quick search, but didn't really find anything like what I'm seeing. Has anyone experienced this, or are there any suggestions on what tool in the chain might be causing this?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8-gke.1900", GitCommit:"79209257257c051b27df67c567755783eda93353", GitTreeState:"clean", BuildDate:"2022-07-15T09:23:51Z", GoVersion:"go1.17.11b7", Compiler:"gc", Platform:"linux/amd64"}
kustomize version
{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}
```
ArgoCD: v2.5.0+b00d9b7
