### DISCUSSION TITLE
Default values for ApplicationSet elements

### DISCUSSION THREAD

**Discussion by headegg** [argoproj/argo-cd#10994] [General]
Hi,

When using ApplicationSets, is there a way to default values for elements (e.g. an element in list generator or a yaml/json file for the git generator) if an individual element doesn't explicitly provide a value?

For example, I'm using an application set like this with the git generator:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-application-set
  namespace: mynamespace
spec:
  generators:
    - git:
        files:
          - path: my-application-set-data/*.json
        repoURL: >-
          https://my.git.repo/applications.git
        revision: master
  template:
    metadata:
      name: 'my-application-{{cluster}}-{{tenantId}}'
      labels:
        application-set: my-application-set
    spec:
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      project: default
      source:
        repoURL: europe-west2-docker.pkg.dev/my-project/my-helm-repo
        targetRevision: 1.0.0
        helm:
          chart: charts/my-app
          parameters:
            - name: hostname
              value: '{{hostname}}'
            - name: path
              value: '{{path}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
```

Is there a way that I can have a default value (let's say "/" or "") for `{{path}}`, for example, which would be used if any of the elements didn't explicitly have a `path:` property given a "data" file in the git repo like this:
```
{
  "tenantId": "acme",
  "cluster": "dev",
  "hostname": "my.dev.host"
}
```

Am I right that I can just do token replacement with `{{path}}` rather than being able to write any kind of more sophisticated expression? I'm wondering if there's a way to do the defaulting that I want down in the template part of the ApplicationSet or in the git generator config (or with a combination of generators?). Right now I find that I get the literal value `'{{path}}'` when the `path:` property is absent from the json file.

Thanks,
Alex
