### DISCUSSION TITLE
How ignore or exclude synchronize resources

### DISCUSSION THREAD

**Discussion by roc26002w** [argoproj/argo-cd#11017] [Q&A] [answered]
I'm add applicate to sync exists k8s

run command line : 
`argocd app sync my-k8s-app --async` 

* fetch sync fails: 

![image](https://user-images.githubusercontent.com/4278183/197144621-d9a2cea3-22c9-42b2-b1af-0bb2182d23af.png)

how can I ignore this resource sync or resolve this fail?

this is my ignoreDifferences but not working
```
ignoreDifferences:
- group: apiextensions.k8s.io
  jsonPointers:
  - /status
  kind: CustomResourceDefinition
  name: cloudflare-issuer.clusterissuers.cert-manager.io
- group: apiextensions.k8s.io
  jsonPointers:
  - /status
  kind: cert-manager.io/v1/ClusterIssuer
  name: cloudflare-issuer

.........

syncPolicy:
  syncOptions:
  - Validate=false
  - CreateNamespace=true
  - RespectIgnoreDifferences=true
  - ApplyOutOfSyncOnly=true
  - SkipDryRunOnMissingResource=true
  - Prune=false


```
