### DISCUSSION TITLE
Argocd with kubernetes nginx ingress controller

### DISCUSSION THREAD

**Discussion by kgopi1** [argoproj/argo-cd#11052] [Q&A]
Hi, 

I'm trying to publish Argo cd server UI using nginx ingress controller with custom hostname and cutom tls certificate. 

i'm following the below [Link](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough). 

i set  --enable-ssl-passthrough in nginx-controller command argument , but still get invalid cert error . 

Any help on this ? 

my ingress is rule. 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - sampledomain.sample.com
      secretName: sample-ingress-tls
  rules:
    - host: sampledomain.sample.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: https

**Comment by bastiaanv** [comment]
We were able to implement nginx ingress with the following config (NOTE: You need to have `cert-manager` installed):

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: argocd-issuer-argocd-letsencrypt
spec:
  acme:
    email: a@b
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: argocd-letsencrypt-private-key
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: argocd-issuer-argocd-letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
spec:
  rules:
    - host: argocd-prod.x.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: https
  tls:
    - hosts:
        - argocd-prod.x.com
      secretName: argocd-secret

```
