### DISCUSSION TITLE
How to auto-apply `argocd-cm` or `argocd-cmd-params-cm` ConfigMap changes

### DISCUSSION THREAD

**Discussion by nhavens** [argoproj/argo-cd#11082] [Q&A] [answered]
### Problem
I've installed Argo CD using the manifests in the [install.yaml](https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml). ConfigMaps `argocd-cm` and `argocd-cmd-params-cm` are only referenced in container environment variables. Suppose I want to enable debug logging by modifying the `argocd-cmd-params-cm` ConfigMap as follows:
`kubectl patch configmap argocd-cmd-params-cm -p '{"data":{"server.log.level":"debug"}}'`
According to [kubernetes ConfigMap documentation](https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically):
> ConfigMaps consumed as environment variables are not updated automatically and require a pod restart.

I find no mechanism built into Argo CD to detect the change and automatically restart the `argocd-server` pod.

### Potential Solutions
I've come up with a few alternatives:
1. Manually delete the `argocd-server` pod, so that it restarts with environment variables from the updated ConfigMap.
2. Use the `kustomize` [`configMapGenerator`](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#configmapgenerator), which will add a unique hash to the end of the ConfigMap's name each time it changes. Since the ConfigMap name referenced by the Deployment changes, a new ReplicaSet is created and a new `argocd-server` pod started with the environment variables from the updated ConfigMap. Unfortunately, this solution is explicitly NOT supported by Argo CD. Quoting https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#atomic-configuration
> For each specific kind of ConfigMap and Secret resource, there is only a single supported resource name (as listed in the above table) - if you need to merge things you need to do it before creating them.
3. Use an external operator like https://github.com/stakater/Reloader to watch for changes to ConfigMaps and restart pods as required.
4. Use `kustomize` to apply a `commonAnnotation` to all resources. Update the annotation when either of these ConfigMaps changes. This will trigger a new ReplicaSet to be created with a new pod that has the environment variables from the updated ConfigMap. https://www.youtube.com/watch?v=uwFONjzvkGA&ab_channel=Codefresh demonstrates this.

Am I missing a better, more obvious, more elegant solution? What do y'all recommend?

**Comment by nhavens** [comment]
Anybody have any ideas? In lieu of responses, I've decided to just patch the `argocd-server` Deployment to configure its command-line arguments. Though it feels wrong to not use the `argocd-cmd-params-cm`, I need to know that changes I make _will be applied_.

**Comment by nhavens** [comment]
I'm back to using the recommended [ConfigMaps](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#atomic-configuration) to configure Argo CD. I've setup an `Application` resource with auto-Sync enabled to deploy changes to the ConfigMaps. I've also configured the following `PostSync` [Resource Hook](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/) to bounce Argo CD Deployments and StatefulSets to ensure that the modified configuration is applied.

```
---
kind: Job
apiVersion: batch/v1
metadata:
  name: argocd-bouncer
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: argocd-bouncer
      restartPolicy: OnFailure
      containers:
        - name: argocd-bouncer
          image: rancher/kubectl:v1.20.15
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              memory: 50Mi
          args:
            - rollout
            - restart
            - deployment
            - argocd-applicationset-controller
            - argocd-notifications-controller
            - argocd-redis
            - argocd-repo-server
            - argocd-server
          securityContext:
            runAsUser: 65534
            runAsNonRoot: true
            readOnlyRootFilesystem: true
```

**Reply by compiaffe** [reply]
Thanks for this @nhavens It still looks a little hacky tbh. Isn't this somethign that argocd should be doing anyways?

What permissions did you give the serviceAccount? Could you share the yaml for it?

**Reply by nhavens** [reply]
Here's the Role:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-bouncer
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - patch
```
