### DISCUSSION TITLE
Auto-sync helm with latest semver chart

### DISCUSSION THREAD

**Discussion by ep4sh** [argoproj/argo-cd#11159] [Q&A] [answered]
Dear community,

I'm trying to apply new application from the local helm registry, using the semver tilda/globs tp deploy the latest version.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://<REDACTED>helm/stable'
    targetRevision: ~0.0.0
    chart: mr-warden-bot
    directory:
      jsonnet:
        tlas:
          - {}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
```

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://<REDACTED>helm/stable'
    targetRevision: 0.*.*
    chart: mr-warden-bot
    directory:
      jsonnet:
        tlas:
          - {}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
```

I'm getting an error:
```
Unable to create application: application spec for test-service is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = constraint not found in index
```

Found the similar post, but it doesn't answer the question:
https://github.com/argoproj/argo-cd/discussions/5731

Is it possible to make Argocd auto-sync with the latest Helm chart version, available in the repo?
I'm usign:
```
{
    "Version": "v2.5.0+b895da4"
}
```

Thank you in advance,
Pasha.
