### DISCUSSION TITLE
Error handling in a CMP

### DISCUSSION THREAD

**Discussion by rassie** [argoproj/argo-cd#11191] [Q&A] [answered]
I'm developing a custom sidecar CMP, which leads me to a problem with error handling and display.

Currently, if my plugin can't generate the manifests for any reason, it outputs an error message. This error message is a text one, which Argo CD cannot parse as YAML and the error message I get in the UI is just `rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: failed to unmarshal manifest: error converting YAML to JSON: yaml: mapping values are not allowed in this context`.

This is of course not helpful at all -- if there is a processing error, the user needs to know the exact problem, i.e. getting the actual error message to show would be the absolute minimum. However, I can't find a reference to error handling in the docs and at this stage I must assume that the CMP interface only cares about Kubernetes-compatible YAML being output from the plugin. For obvious reasons, I can't just output my error message as YAML, since that probably would result in a prune of the whole application.

So what can I do to forward errors from CMP to the UI?

(for good measure: I'll wade through the code too and would document any findings here, but maybe someone in the know is faster to reply)

EDIT: from what I could gather from the source code:

* The actual error message from the CMP is `rpc error: code = Unknown desc = error generating manifests: failed to unmarshal manifest: error converting YAML to JSON: yaml: mapping values are not allowed in this context`
* `failed to unmarshal manifest` comes from [`kube.SplitYAMLToString`](https://github.com/argoproj/gitops-engine/blob/b371e3bfc5e95962096866e3d8e0205bf647f1a2/pkg/utils/kube/kube.go#L299)
* The call to `kube.SplitYAMLToString` is [here](https://github.com/argoproj/argo-cd/blob/a773b1effb6f59be14176c6402a9a69c4b480275/cmpserver/plugin/plugin.go#L204), which is *after* the `generate` command has been called and checked for errors

At this point it seems like either my `generate` script is not returning an error code or ArgoCD's code does not detect it properly.

**Comment by rassie** [comment, marked as answer]
OK, I think I have found my problem (will see whether this helps with error reporting): I'm using `tee` in my commands to redirect output to files for easier debugging, which swallows the exit code by default. Hope this helps someone somewhere.

**Comment by yitzhtal** [comment]
Hi, I'm experiencing the same issue!
I could not resolve it so far, spent many hours debugging...

```
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      generate:
        command: ["sh", "-c"[]
        args: ["helm dependency build && helm template --debug --include-crds ${helm_args} . | argocd-vault-plugin generate -"]
      init:
        command: [sh, -c[]
        args: ["REPO_USER_EVAL=$(eval \"echo $REPO_USER\") && REPO_PASS_EVAL=$(eval \"echo $REPO_PASS\") && helm repo add repo-helm <ARTIFACTORY_URL> --username $REPO_USER_EVAL --password $REPO_PASS_EVAL && helm repo add repo-helm2 <ARTIFACTORY_URL2> --username $REPO_USER_EVAL --password $REPO_PASS_EVAL && helm repo update"]
```

I'm getting the same error, the same scenario exactly. No idea what to do - any direction to resolve it? It seems like something on Argo side but i'm not able to debug it or understand whats wrong.
