### DISCUSSION TITLE
Bootstrapping App of Apps pattern in new cluster no longer possible

### DISCUSSION THREAD

**Discussion by knowhoper** [argoproj/argo-cd#11221] [Q&A]
Hi, 

Prior to the deprecation of the construct:

```YAML
  additionalApplications:
    - name: prd-acme-k8s
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        path: prd/apps
        repoURL: https://github.com/acme/acme-k8s
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
 ```
 
 In the values.yaml file for the declarative setup for ArgoCD via Helm, our clusters used to bootstrap the app of apps pattern which gave us a high level of automation.
 
From 2.5 onwards, the docs state we should use a helm  chart to provision additional applications out, however, on argo startup there is no way to bootstrap this process automatically, instead we have to manually deploy the app of apps application.

Is there a known solution to this problem? We use the declarative setup and don't wish to use the CLI to bootstrap the cluster.
