### DISCUSSION TITLE
Mapping claims without dex

### DISCUSSION THREAD

**Discussion by brackend** [argoproj/argo-cd#11243] [Q&A]
Hi,

trying to configure oidc without using Dex.  
pingidentity I’d the idp and it pulls memberof instead of groups
The dex configuration allows claimMapping: { groups: memberOf } and works fine.  
is there a way to map a claim when using the oidc.config?

```yaml
      oidc.config: |
        name: whatever
        issuer: https://issuer
        clientID: clientname
        clientSecret: $oidc.ping.clientSecret
        requestedScopes: [ "openid","profile"]
        claimMapping: { "groups": "memberOf" }
```
