### DISCUSSION TITLE
ConfigManagementPlugin sidecar with multi tenancy with env vars not working

### DISCUSSION THREAD

**Discussion by betorvs** [argoproj/argo-cd#11280] [General]
Hi all,

Could I have any help here? 
I'm trying to configure [CMP with sidecar](https://argo-cd.readthedocs.io/en/latest/user-guide/config-management-plugins/#option-2-configure-plugin-via-sidecar), but I need to include [multi tenancy support for it](https://argocd-vault-plugin.readthedocs.io/en/stable/config/#using-kubernetes-secrets-for-supplying-avp-configuration). Since I have 2 clusters and each cluster have it own vault secret. 

I tried:
```
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"path:.*.vaultsupersecret\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
        args:
          - generate
          - -s
          - "$ARGOCD_ENV_AVP_SECRET ."
      lockRepo: false
```

But it fails. 
Error:
```
time="2022-11-11T11:46:55Z" level=error msg="`argocd-vault-plugin generate -s $ARGOCD_ENV_AVP_SECRET .` failed exit status 1: Error: <path> argument required to generate manifests\nUsage:\n  argocd-vault-plugin generate <path> [flags]\n\nFlags:\n  -c, --config-path string         path to a file containing Vault configuration (YAML, JSON, envfile) to use\n  -h, --help                       help for generate\n  -s, --secret-name string         name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>\n      --verbose-sensitive-output   enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr" execID=7826e
time="2022-11-11T11:46:55Z" level=error msg="finished streaming call with code Unknown" error="error generating manifests: `argocd-vault-plugin generate -s $ARGOCD_ENV_AVP_SECRET .` failed exit status 1: Error: <path> argument required to generate manifests\nUsage:\n  argocd-vault-plugin generate <path> [flags]\n\nFlags:\n  -c, --config-path string         path to a file containing Vault configuration (YAML, JSON, envfile) to use\n  -h, --help                       help for generate\n  -s, --secret-name string         name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>\n      --verbose-sensitive-output   enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2022-11-11T11:46:55Z" grpc.time_ms=135.275 span.kind=server system=grpc
```

Is there any documentation about using sidecar with multi tenancy? Any idea ?

**Comment by betorvs** [comment]
When I tried it:
```
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"path:.*.production\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
        args:
          - generate
          - --verbose-sensitive-output
          - "-s $ARGOCD_ENV_AVP_SECRET"
          - "."
      lockRepo: false
```
I received a different error:
```
time="2022-11-14T09:27:27Z" level=error msg="`argocd-vault-plugin generate --verbose-sensitive-output -s $ARGOCD_ENV_AVP_SECRET .` failed exit status 1: 2022/11/14 09:27:27 reading configuration from secret  $ARGOCD_ENV_AVP_SECRET\n2022/11/14 09:27:27 parsed secret name as  $ARGOCD_ENV_AVP_SECRET from namespace argocd\nError: secrets \" $ARGOCD_ENV_AVP_SECRET\" not found\nUsage:\n  argocd-vault-plugin generate <path> [flags]\n\nFlags:\n  -c, --config-path string         path to a file containing Vault configuration (YAML, JSON, envfile) to use\n  -h, --help                       help for generate\n  -s, --secret-name string         name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>\n      --verbose-sensitive-output   enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr" execID=b1fc9
time="2022-11-14T09:27:27Z" level=error msg="finished streaming call with code Unknown" error="error generating manifests: `argocd-vault-plugin generate --verbose-sensitive-output -s $ARGOCD_ENV_AVP_SECRET .` failed exit status 1: 2022/11/14 09:27:27 reading configuration from secret  $ARGOCD_ENV_AVP_SECRET\n2022/11/14 09:27:27 parsed secret name as  $ARGOCD_ENV_AVP_SECRET from namespace argocd\nError: secrets \" $ARGOCD_ENV_AVP_SECRET\" not found\nUsage:\n  argocd-vault-plugin generate <path> [flags]\n\nFlags:\n  -c, --config-path string         path to a file containing Vault configuration (YAML, JSON, envfile) to use\n  -h, --help                       help for generate\n  -s, --secret-name string         name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>\n      --verbose-sensitive-output   enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2022-11-14T09:27:27Z" grpc.time_ms=272.756 span.kind=server system=grpc
```

Looks like it use `$ARGOCD_ENV_AVP_SECRET` as a string and not as a variable. 

Anyone using CMP with sidecar and multi tenancy to give any idea what I'm doing wrong here?
