### DISCUSSION TITLE
Plugin configuration with upgrade v2.4 to 2.5

### DISCUSSION THREAD

**Discussion by pauloazevedo88** [argoproj/argo-cd#11334] [General]
At the moment we are using hashicorp-vault-plugin using configManagementPlugins without issues [Argo CD Vault Plugin](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/#initcontainer-and-configuration-via-argocd-cm-configmap). 
Since config management plugins (CMPs) via the argocd-cm ConfigMap will be deprecated we are trying to install ir as sidecar, but we are getting the following error:

```
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. Couldn't find cmp-server plugin supporting repository /tmp/c5b8f563-0f37-49b9-8848-1bfcbc3a63ae/clamav
```

Here's our current configuration:

We have applyed configmap in same namespace:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hashicorp-vault-plugin-helm
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: hashicorp-vault-plugin-helm
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args: ["helm dependency update"]
      generate:
        command: ["bash", "-c"]
        args: ['helm template "$ARGOCD_APP_NAME" --namespace "$ARGOCD_APP_NAMESPACE" -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} -']
      discover:
        find:
          command: ["touch", "/tmp/plugin-discover-has-run"]
      allowConcurrency: true
      lockRepo: true
```

Using v2.5.2 and adding extraContainers to repoServer in values.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd-alpha"
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://api.cicd.alpha.intra.test.io
  project: dh-io-test-alpha-cicd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.13.8
    chart: argo-cd
    helm:
      values: |
        nameOverride: argocd
        createAggregateRoles: true
        global:
          image:
            repository: quay.io/argoproj/argocd
            tag: "v2.5.2"
            imagePullPolicy: IfNotPresent
          logging:
            format: json
            level: error
        controller:
          replicas: 1
          extraArgs:
            - --redis=master.argo-redis-host.com:6379
            - --redisdb=1
            - --redis-use-tls

        server:
          name: server
          replicas: 1
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 9
            targetCPUUtilizationPercentage: 90
            targetMemoryUtilizationPercentage: 90
          extraArgs:
            - --redis=master.argo-redis-host.com:6379
            - --redisdb=1
            - --redis-use-tls


          ingress:
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/affinity: cookie
              nginx.ingress.kubernetes.io/affinity-mode: persistent
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            ingressClassName: nginx-internal-mbcom
            hosts:
              - argocd.euc1.alpha.cicd.test.com
            paths:
              - /
            pathType: ImplementationSpecific
            https: true
          configEnabled: true
          config:
            accounts.caas_api_argo: apiKey
            url: https://argocd.euc1.alpha.cicd.test.com
            application.instanceLabelKey: argocd.argoproj.io/instance
            admin.enabled: "false"
            url: https://argocd.euc1.alpha.cicd.test.com

        repoServer:
          replicas: 1
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 9
            targetCPUUtilizationPercentage: 90
            targetMemoryUtilizationPercentage: 90
          extraArgs:
            - --redis=master.argo-redis-host.com:6379
            - --redisdb=1
            - --redis-use-tls
       
          # -- Additional volumeMounts to the repo server main container
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/argocd-vault-plugin
              subPath: argocd-vault-plugin
          
          extraContainers:
          - name: cmp
            command: [/var/run/argocd/argocd-cmp-server] 
            image: busybox 
            securityContext:
              runAsNonRoot: true
              runAsUser: 999
            volumeMounts:
              - mountPath: /var/run/argocd
                name: var-files
              - mountPath: /home/argocd/cmp-server/plugins
                name: plugins
              - mountPath: /tmp
                name: tmp
              - mountPath: /home/argocd/cmp-server/config/plugin.yaml 
                subPath: plugin.yaml
                name: hashicorp-vault-plugin-helm
          # -- Additional volumes to the repo server pod
          volumes:
            - name: custom-tools
              emptyDir: {}
            - configMap:
                name: hashicorp-vault-plugin-helm
              name: hashicorp-vault-plugin-helm

          initContainers:
            - name: download-tools
              image: alpine:3.8
              command: [sh, -c]
              env:
                - name: AVP_VERSION
                  value: "1.13.0"
              args:
                - wget -O argocd-vault-plugin
                  https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
                  chmod +x argocd-vault-plugin &&
                  mv argocd-vault-plugin /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools

  syncPolicy:
   syncOptions:
   - CreateNamespace=true
```

In the application manifest we only removed the plugin name:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "clamav-plugin-alpha-cicd"
  namespace: argocd
spec:
  destination:
    namespace: clamav-plugin
    server: https://api.cicd.alpha.intra.test.io
  project: dh-io-test-alpha-cicd
  source:
    repoURL: harbor.euc1.cicd.oneweb.test/test
    targetRevision: 1.0.2
    chart: clamav
    plugin:
        env:
          - name: AVP_SECRET
            value: argocd:dh-io-test-vault-configuration
          - name: HELM_VALUES
            value: |
              namespaceName: clamav

              imageCredentials:
                registry: https://harbor.euc1.cicd.test.com
                username: <test/data/tools/alpha/harbor/dockerconfig#username>
                password: <test/data/tools/alpha/harbor/dockerconfig#password>
                token: <test/data/tools/alpha/harbor/dockerconfig#token>
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
```

We've are not sure if the issue is related to the discovery rules but we tried several options from the [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#2-place-the-plugin-configuration-file-in-the-sidecar) with no success. Any ideas on why it cannot find the plugin?

**Comment by crenshaw-dev** [comment]
The discover.find command must both 1) return a 0 exit code and 2) write something to standard out. Try this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hashicorp-vault-plugin-helm
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: hashicorp-vault-plugin-helm
    spec:
      discover:
        find:
          command: ["sh", "-c", "touch /tmp/plugin-discover-has-run && echo 'yes'"]
```

**Reply by pauloazevedo88** [reply]
Hello,

Unfortunately after applying the configmap with your change, i'm getting the same error. Inside the repo-server pod the plugin seems to be available:

```
paulo@MININT-OGH30OI:~/argo$ cat hashicorp-vault-plugin-helm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hashicorp-vault-plugin-helm
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: hashicorp-vault-plugin-helm
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args: ["helm dependency update"]
      generate:
        command: ["bash", "-c"]
        args: ['helm template "$ARGOCD_APP_NAME" --namespace "$ARGOCD_APP_NAMESPACE" -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} -']
      discover:
        find:
          command: ["sh", "-c", "touch /tmp/plugin-discover-has-run && echo 'yes'"]

paulo@MININT-OGH30OI:~/argo$ kubectl exec --stdin --tty argocd-alpha-repo-server-649b66464b-vtlb4 -n argocd -- /bin/bash
Defaulted container "repo-server" out of: repo-server, cmp, copyutil (init), download-tools (init)
argocd@argocd-alpha-repo-server-649b66464b-vtlb4:~$ cd cmp-server/plugins/
argocd@argocd-alpha-repo-server-649b66464b-vtlb4:~/cmp-server/plugins$ ls
hashicorp-vault-plugin-helm-v1.0.sock
```
