### DISCUSSION TITLE
How to use custom secret to use in ConfigMap argocd-cm.

### DISCUSSION THREAD

**Discussion by afonsoaugusto** [argoproj/argo-cd#11353] [Q&A] [answered]
Hi,
I using argocd v2.3.5, and I need put the password for ldap configuration.
In my ConfigMap I had this structure:
```yaml
data:
  dex.config: |
     connectors:
     - type: ldap
        config:
          binPW: "$dex.ldap.bindPW" <- secretValue
````
I need this value is from a custom secret because I can't change the argocd-secret.
I using helm for generate this ConfigMap and  is not possible change secret argocd-secret.

How to use a custom secret in this configuration?

{
    "Version": "v2.3.5+1287d24",
    "Platform": "linux/amd64",
}

ps: for this configuration I using this [example](https://medium.com/yapi-kredi-teknoloji/argo-cd-ldap-authentication-and-rbac-configuration-7c1b7b0cb7a1)

**Comment by afonsoaugusto** [comment, marked as answer]
I found the solution for problem.
Is possible I use custom secret with have the label `app.kubernetes.io/part-of: argocd`.

And in config map put value this: `$<some_K8S_secret>:dex.acme.clientSecret`

```yaml
apiVersion: v1
data:
  dex.acme.clientSecret: <base64 value>
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-some-secret
  namespace: argocd
```

```yaml
data:
  url: https://argocd.example.com
  dex.config: |
      # GitHub enterprise example
      - type: github
        id: acme-github
        name: Acme GitHub
        config:
          hostName: github.acme.com
          clientID: abcdefghijklmnopqrst
          clientSecret: $argocd-some-secret:dex.acme.clientSecret
          orgs:
          - name: your-github-org
```

Reference: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/user-management/index.md#2-configure-argo-cd-for-sso
