### DISCUSSION TITLE
It's possible obtain argocd application metadata to use in argo resource hook?

### DISCUSSION THREAD

**Discussion by xoanmm** [argoproj/argo-cd#11416] [Q&A]
Hello,

I was reading about [argo resource hooks](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/) and I have doubts about if it would be possible to obtain information about the application in which the hook is launched, as it is obtained when sending notifications as you can see in the following example obtained from the configuration of the `ConfigMap` named `argocd-notifications-cm` used to configure the notifications with ArgoCD:

```yaml
template.app-deployed: |
    email:
      subject: New version of an application {{.app.metadata.name}} is up and running.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version of deployments manifests.
    slack:
      attachments: |
        [{
          "title": "{{ .app.metadata.name}}",
          "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "#18be52",
          "fields": [
          {
            "title": "Sync Status",
            "value": "{{.app.status.sync.status}}",
            "short": true
          },
          {
            "title": "Repository",
            "value": "{{.app.spec.source.repoURL}}",
            "short": true
          },
          {
            "title": "Revision",
            "value": "{{.app.status.sync.revision}}",
            "short": true
          }
          {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "title": "{{$c.type}}",
            "value": "{{$c.message}}",
            "short": true
          }
          {{end}}
          ]
        }]
```

In the example shown can be seen how different data is obtained from the ArgoCD app to send notifications, would it be possible to do something like this in the creation of argo resource hooks?
