### DISCUSSION TITLE
How to use ArgoCD hooks if you're working with helm charts?

### DISCUSSION THREAD

**Discussion by SamDecrock** [argoproj/argo-cd#11521] [Q&A] [answered]
From the docs:

> Hooks are simply Kubernetes manifests tracked in the source repository of your Argo CD Application annotated with argocd.argoproj.io/hook, e.g.:

But what if your source repository contains values files for a helm chart? I tried adding a hook to that path, but argo doesn't pick it up..

**Comment by kostis-codefresh** [comment, marked as answer]
Could you please post some code/yaml of what you did exactly (the "adding a hook to that path" part)?

**Reply by SamDecrock** [reply]
Yes, this is our Application yaml: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectname
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@git.ourgitrepo:group/ourgitproject.git
    targetRevision: HEAD
    path: applications/projectname/
    helm:
      releaseName: something
      valueFiles:
        - global.yaml
        - third_party_services.yaml
        - our_services.yaml
  destination:
    name: clustername
    namespace: projectname
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

(I redacted some of the things)

So in `git@git.ourgitrepo:group/ourgitproject/applications/projectname/` we have 5 files:
- the 3 helm value files referred to by `valueFiles`
- a Chart.yaml pointing to the chart at our chart repo (Harbor)
- the argocd hook Kubernetes manifest.

Obviously, the 3 value files are read and applied to the cluster.
The argocd hook file is not.
