### DISCUSSION TITLE
Modify values.yaml per ArgoCD project/overlay?

### DISCUSSION THREAD

**Discussion by ldacey** [argoproj/argo-cd#11525] [General]
This is more of a Kustomize question than ArgoCD specifically, but is there a way to update only specific lines of a values.yaml file instead of copying and pasting the entire thing using Kustomize? My project is set up similar to AutoPilot.

My base folder has all of the secrets, the helm chart, and the values.yaml:

`base`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow

helmCharts:
  - name: airflow
    includeCRDs: true
    releaseName: airflow
    namespace: airflow
    version: 8.6.1
    repo: https://airflow-helm.github.io/charts
    valuesFile: values.yaml

generators:
  - secret-generator.yaml
```

My production environment just refers to the base folder directly:

`overlays/production`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
```

However, my development environment is a pure copy/paste of the base folder. I then edit the values.yaml file to change just a few lines (domain name, database IP).

This is the folder structure

```
├── base
│   ├── kustomization.yaml
│   ├── official.yaml
│   ├── secret-generator.yaml
│   ├── secrets
│   │   ├── airflow-database-password.enc.yaml
│   └── values.yaml
└── overlays
    ├── development
    │   ├── config.json
    │   ├── kustomization.yaml
    │   ├── secret-generator.yaml
    │   ├── secrets
    │   │   ├── airflow-database-password.enc.yaml
    │   └── values.yaml
    └── production
        ├── config.json
        └── kustomization.yaml
```

My goal is to be able to reuse everything from the base folder, but still be able to edit aspects of the values.yaml file without copy/pasting.
