### DISCUSSION TITLE
How to template annotations on applicationset

### DISCUSSION THREAD

**Discussion by brunocascio** [argoproj/argo-cd#11589] [General]
I have the following Applicationset definition:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    # For loop of elements containing environment name and target cluster (it will be available on the template below)
    - list:
        elements:
          - cluster: nonprod
            annotations:
              environment: dev
          - cluster: prod
            annotations:
              notifications.argoproj.io/subscribe.on-deployed.newrelic-record-deployment: "dummy-app-prod"
              environment: prod
  template:
    metadata:
      name: 'app-test-{{ annotations.environment }}'
      annotations: "{{ annotations }}"                    # <---- HERE
    spec:
      project: "app-test-project"
      source:
        repoURL: https://repo.com/example.git
        targetRevision: HEAD
        path: '{{ annotations.environment}}/'
      destination:
        name: '{{cluster}}'
        namespace: 'app-test-{{ annotations.environment }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
```

What I'm trying to do is to inject annotations based on the environment
So dev would have the `environment: dev` annotation but prod would have `environment: prod` but also `notifications.argoproj.io/subscribe.on-deployed.newrelic-record-deployment: "dummy-app-prod"` annotation

How can I convert "{{ annotations }}" into an object ? Right now is parsed as a string
