### DISCUSSION TITLE
ignoreDifferences / StatefulSets / Kube-Prometheus-Stack

### DISCUSSION THREAD

**Discussion by reefland** [argoproj/argo-cd#11671] [Q&A]
I have ignoreDifferences on StatefulSets / replicas working fine for other applications, but can't get it working on Kube-Prometheus-Stack.

I'm using `kube-prometheus-stack`  HelmChart deployed by ArgoCD Application:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: kube-prometheus-stack
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "14"  # Lower the number the sooner to deploy
    
spec:
  project: monitoring
  revisionHistoryLimit: 3

  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 42.3.0
    helm:
      skipCrds: true

...

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # Allow changes to number of replicas (down to zero)
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
```

Looking at the deployed StatefulSet:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-prometheus-prometheus
  namespace: monitoring

...
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-prometheus
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: prometheus
      operator.prometheus.io/name: prometheus-prometheus
      operator.prometheus.io/shard: '0'
      prometheus: prometheus-prometheus
```

I want the ignoreDifferences to apply to each StatefulSet deployed within this ArgoCD application (both Prometheus and AlertManager are StatefulSets). 

So it is not clear why this, does not match the above StatefulSet.
```
  # Allow changes to number of replicas (down to zero)
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
```

Being that there is more than one StatefulSet, do I need something like a ` name: *` ??

**Comment by luispabon** [comment]
I have found that argo consistently fails to honor ignoreDifferences if the group is not specified on it.

This doesn't work:

```yaml
ignoreDifferences:
  - kind: StatefulSet
    jqPathExpressions:
      - 'spec.replicas'
```

This works:

```yaml
ignoreDifferences:
  - kind: StatefulSet
    group: apps
    jqPathExpressions:
      - 'spec.replicas'
```
