### DISCUSSION TITLE
Matching the cluster name in ApplicationSet cluster generator

### DISCUSSION THREAD

**Discussion by yohanb** [argoproj/argo-cd#11780] [Q&A]
Hey everyone,
I'm using the `matrix` generator for Application Sets and trying to generate apps only for clusters that have an overlay defined for them.
For example:
```
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/some-argocd-apps
              revision: HEAD
              # Get cluster overlay folders
              directories:
                - path: apps/sealed-secrets/clusters/*
          - clusters:
              selector:
                matchLabels:
                  # Match only clusters with `cluster-name` label equal to a cluster/overlay folder name
                  cluster-name: '{{path.basename}}'
```
This works but I need to add a `cluster-name` label to every cluster secret which seems unnecessary since the secret already contains the name in the data fields.

Any way I could do something similar to this?
```
...
          - clusters:
              selector:
                matchDataFields:
                  # Match only clusters with name data field value equal to a cluster/overlay folder name
                  name: '{{path.basename}}'
```

thanks! 🙏
