### DISCUSSION TITLE
How to pass port number as string in annotations via helm parameters?

### DISCUSSION THREAD

**Discussion by kandeshvari** [argoproj/argo-cd#11848] [Q&A]
I'm trying to pass the port number via helm parameters but got `cannot convert int64 to string` during sync. How to pass these params as strings without internal conversion?

```
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
    helm:
      parameters:
        - name: podAnnotations.prometheus\.io/port
          value: '9093'
        - name: podAnnotations.prometheus\.io/scrape
          value: 'true'
```
