### DISCUSSION TITLE
Using custom groups claim for Argocd SSO login via OIDC

### DISCUSSION THREAD

**Discussion by dani3lsf** [argoproj/argo-cd#11855] [Q&A]
I'm trying to integrate Zitadel as OIDC provider for SSO login based on the documentation provided at "https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#existing-oidc-provider". The login itself works but I'm not able to map users to roles using the policy feature, reason being that Zitadel does not provide a _groups_ claim using the standard structure. On the other end, it provides a claim named "urn:zitadel:iam:org:project:roles" with the following example structure:

```
"urn:zitadel:iam:org:project:roles":{"argocd-admin":{"<id1>":"accounts.zitadel.ch"},"argocd-editor":{"<id2>":"accounts.zitadel.ch"}}}
```
It's basically a map whose keys are the roles of a user. I would like to be able to map those keys, for example argocd-admin to a specific argocd admin role. Any ideas how can I make this possible? 

**OIDC configuration**
```
  oidc.config: |
    name: Zitadel
    issuer: https://login.organization.ch
    clientID: 192847013254004993@organization
    clientSecret: $oidc.zitadel.clientSecret
    requestedScopes: ["openid", "profile", "email", "urn:zitadel:iam:org:project:roles"]
```

**Target Argocd-rbac-cm**
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: monitoring
data:
  # also tried to overwrite the groups claim to the one provided by zitadel but obviously did
  # not work as it does not follow the required groups structure
  # scopes: '[urn:zitadel:iam:org:project:roles]' 
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow

    g, argocd-admin, role:org-admin #
  policy.default: role:readonly
```

**Comment by alxivanov** [comment]
After logging in you can check your group definitions in User info (should work with read-only permissions too):
<img width="312" alt="user-info" src="https://user-images.githubusercontent.com/89388397/210220420-63b962b4-8b29-43f2-9579-b02ce38a0a37.png">
Try defining your group policy with the group that shows up under Groups section.

**Comment by stephanrenggli** [comment]
Hi there,

Took me a while to figure out, hopefully this helps you and others trying to get ArgoCD OIDC login to work with Zitadel.

Zitadel has a feature called Actions (see https://zitadel.com/blog/custom-claims) which allows you to write JavaScript code to modify the content of tokens. Using this and some example code on their GitHub (https://github.com/zitadel/actions/tree/main/examples) I made the following script which adds the groups claim to the token.

```javascript
function groupsClaim(ctx, api) {
  if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.count == 0) {
    return;
  }

  let grants = [];
  ctx.v1.user.grants.grants.forEach(claim => {
    claim.roles.forEach(role => {
        grants.push(role)  
    })
  })

  api.v1.claims.setClaim('groups', grants)
}
```

Add this function in Zitadel under actions and then add it to the Complement Token flow. It should look like this:
![image](https://user-images.githubusercontent.com/5135902/231492548-317334a6-899b-47dc-b64b-49992250a2ad.png)

If we inspect the cookie value/token (get cookie value of the `argocd.token` from browser dev tools and paste to https://token.dev/) we'll see that the groups claim was added and contains the correct Zitadel role:
![image](https://user-images.githubusercontent.com/5135902/231315474-92dbd800-b853-4f7d-b117-6dee911e749f.png)

Configure both required ArgoCD configmaps as follows:

argocd-cm.yaml (see https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml)
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  url: https://argo.example.com
  oidc.config: |
    name: Zitadel
    issuer: https://auth.example.com
    clientID: <clientid>
    clientSecret: <clientsecret>
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    logoutURL: https://auth.example.com/oidc/v1/end_session
```

argocd-rbac-cm.yaml (see https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-rbac-cm.yaml)
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  scopes: '[groups]'
  policy.csv: |
    g, argocd_administrators, role:admin
    g, argocd_users, role:readonly
  policy.default: ''
```

In `argocd-rbac-cm.yaml` two groups are defined `argocd_administrators` and `argocd_users`. These represent the roles in Zitadel, where it looks like this:
![image](https://user-images.githubusercontent.com/5135902/231313611-80c2bba2-e5ea-42e7-a684-f52523cbe30d.png)


Also make sure to check the following boxes:
![image](https://user-images.githubusercontent.com/5135902/231313551-9c03e448-07c9-4d64-9f22-9aa839e3ebe5.png)
![image](https://user-images.githubusercontent.com/5135902/231314198-9bb897c4-b0d3-4aea-8807-157c631c5c13.png)


In the end we have two users in the test setup, both can login to ArgoCD using Zitadel OIDC. One user (administrator) has admin permissions in ArgoCD, the other one (user) has read-only permissions.

![image](https://user-images.githubusercontent.com/5135902/231314037-f4e9f91e-d046-45b8-bc3b-0339e804f1cb.png)

To verify everything works as intended, log in to ArgoCD and go to User Info. You should now see your username, issuer and most importantly your groups:
![image](https://user-images.githubusercontent.com/5135902/231316730-c04eab16-3159-4a5c-ba0a-50ec4ab0786a.png)

**Reply by jessebot** [reply]
This is a fantastic write up! You should consider submitting it as a PR in the "[User Management](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/)" section, where we have other apps such as Keycloak there. This would be a great addition to help others getting started with bootstrapping argocd and zitadel at the same time :)

**Reply by stephanrenggli** [reply]
Thanks, glad it was useful.
I'll try to put something together on the weekend.

**Reply by fforootd** [reply]
Nice write up and thank you for using ZITADEL 🚀

**Reply by stephanrenggli** [reply]
I created a PR: https://github.com/argoproj/argo-cd/pull/15029

@fforootd would you mind taking a look at it to make sure Zitadel terminology is correct?

**Reply by fforootd** [reply]
Sure, let me quickly look at it!

**Reply by fforootd** [reply]
@stephanrenggli Thank you for this superb PR!

I made only some really small comment.

**Reply by stephanrenggli** [reply]
Thank you for the review!

**Reply by jessebot** [reply]
Thank you both! :) It's wonderful to see the greater open source community helping each other across projects 💙

**Reply by jessebot** [reply]
I finally got around to trying this out, using the same settings, but I keep getting an error.

My settings `argocd-cm` configmap keys where example.com is my actual domain:
```yaml
oidc.config: |
  name: zitadel
  issuer: https://iam.example.com
  clientID: 229387654327387676@core
  clientSecret: $argocd-oidc-credentials:oidc.clientSecret
  requestedScopes:
    - openid
    - profile
    - email
    - groups
  logoutURL: https://iam.example.com/oidc/v1/end_session
# this is temporary during testing because I don't want to get rate limited by letsencrypt while I rebuild the cluster over and over again which uses TLS certs
# ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#skipping-certificate-verification-on-oidc-provider-connections
oidc.tls.insecure.skip.verify: true
```

For zitadel I used "Web" application type and "Code" auth method. My redirect uri in zitadel app is:
https://argocd.example.com/auth/callback

My logout uri in zitadel app is:
https://argocd.example.com

Additional origins in zitadel app is:
scheme://localhost:8080

I think I have the same auth token options in the zitadel app (user roles/info inside the token):
<img width="639" alt="Screenshot 2023-08-30 at 09 30 31" src="https://github.com/argoproj/argo-cd/assets/2389292/68eee2bc-6318-4610-afd3-ebb8cc801b4e">

And the only difference I see in my groups claim is mine is not syntax highlighted? Did I maybe do something wrong here? Did I accidentally delete a semicolon somewhere or something and my dyslexia is just missing it?
<img width="450" alt="Screenshot 2023-08-30 at 09 29 56" src="https://github.com/argoproj/argo-cd/assets/2389292/d505360c-7e78-4d89-b20c-8b2ccf7f50a1">

Argo CD gives me the zitadel button here:
<img width="1115" alt="Screenshot 2023-08-30 at 09 25 08" src="https://github.com/argoproj/argo-cd/assets/2389292/b10262d1-9b03-445e-a620-7981c46f5cab">

But when I click it, I get:
`Invalid redirect URL: the protocol and host (including port) must match and the path must be within allowed URLs if provided`

I'm using the Argo CD helm chart (`5.45.0`) for this which I think is docker tag `argocd:v2.8.2`. @stephanrenggli and @fforootd, you've both already done a ton to help get me in the right direction, but do you think you could let me know if there's anything else I could try to troubleshoot this?

My `global.logging.level` param is set to `debug` in my Argo CD values.yaml, but when I tail the logs for the server pod while reproducing my error, I get nothing.

**Reply by jessebot** [reply]
nevermind! I solved it 🤦 I forgot to set the url in the helm chart values. I fixed this by setting:
```yaml
configs:
  cm:
    url: https://argocd.example.com
```
