### DISCUSSION TITLE
How to use sync-waves to install CRDs before resources?

### DISCUSSION THREAD

**Discussion by fabioaraujopt** [argoproj/argo-cd#11883] [Q&A]
I have an ArgoCD application that have yamls that are used to install the following crossplane configuration:
```
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  package: XXXXXX:SomeCRD:XXXX
```

The yaml above installs the "SomeCRD" CRD into the cluster. 
In the same ArgoCD application I have the following code: 

```
apiVersion: websummit.com/v1beta1
kind: SomeCRD
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  XXXX
```

I setted the sync-waves in order to ArgoCD to sync the one yaml after the other.

What's happening is that argo syncs everything at the same time and fails with the error:
`the server could not find the requested resource` (SomeCRD does not exist). 

Maybe I'm not understanding the concept "sync-wave", can you help me?

**Comment by huynhsontung** [comment]
I got this problem myself and was wondering the same thing. It turns out that ArgoCD does dry run verification on all resources before applying. To suppress this behaviour, set sync option `SkipDryRunOnMissingResource=true` on that resource like so.

```yaml
apiVersion: websummit.com/v1beta1
kind: SomeCRD
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  XXXX
```

Read more about it [here](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types).
