### DISCUSSION TITLE
"Existing OIDC Provider" guide for PingFederate

### DISCUSSION THREAD

**Discussion by jdoylei** [argoproj/argo-cd#11942] [Q&A]
It's helpful that Argo CD has many guides under [User Management](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/) that are specific to individual existing OIDC providers like [Okta](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/okta/).  We're hoping to leverage OIDC support in our existing PingFederate system, either integrating Argo CD via Dex, or integrating Argo CD directly.  I see there's not a guide specific to PingFederate (yet?).  We'd appreciate any advice on this, particularly since we've used PingFederate as a SAML provider up until now, and OIDC is new territory for us, but we'd like to explore OIDC as a more current approach.

* Have other Argo CD users had success with PingFederate as Argo CD's OIDC provider?
* Did you use it from Argo CD directly, or use it via Dex?
* Any quirks to watch out for?

Thank you!

**Comment by shxpark** [comment]
Were you able to set this up? Trying to do something similar

**Reply by jdoylei** [reply]
Hi @shxpark - We integrated PingFederate as a SAML provider using Dex, and have been using it that way for a while.  It would be nice to take SAML out of the equation and leverage OIDC, but we back-burnered looking at any Ping OIDC integration.

We basically ended up with a dex.config.yaml like:
```
logger:
  level: debug
  format: json
connectors:
  - type: saml
    id: saml
    name: "<Company name> Ping"
    config:
      entityIssuer: https://argocd-ui-x.xyz.com/api/dex/callback
      ssoURL: https://pingx.abc.com/idp/SSO.saml2
      caData: $zzz-pingx:PINGX.crt
      redirectURI: https://argocd-ui-x.xyz.com/api/dex/callback
      usernameAttr: User.mail
      emailAttr: User.mail
      groupsAttr: MemberOf
      nameIDPolicyFormat: unspecified
```
