### DISCUSSION TITLE
ArgoCD fails to provision hook when created via Helm chart

### DISCUSSION THREAD

**Discussion by knowhoper** [argoproj/argo-cd#11951] [Q&A] [answered]
I have a helm chart that outputs the following YAML

```YAML
---
# Source: listener/templates/hooks.yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: something-post-sync-
  namespace: test-sync
  annotations:
    argocd.argoproj.io/hook:  PostSync # PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: test-post-sync
        image: curlimages/curl
        command:  
          - curl
          - -X
          - POST
          - --data-urlencode
          - 'payload={"channel": "#acme-something", "username": "hello", "text": "ArgoCD Sync
            succeeded", "icon_emoji": ":party:"}'
          - https://hooks.slack.com/services/sdfsfd/ssdfsd/sdfsdf
      restartPolicy:  Never
  backoffLimit: 2
```

However, the sync hook is not created - no job exists, I changed from HookSucceeded to HookFailed to try to see if the job can be persisted.

Running kubectl create with the above works, but i need to deploy the hook as part of my application. Is there a pattern for this?
