### DISCUSSION TITLE
Exclude in-cluster from cluster generator (application set)

### DISCUSSION THREAD

**Discussion by karol-szymanowski** [argoproj/argo-cd#11967] [General]
I disabled the `in-cluster` cluster in ArgoCD, but despite that, when using a cluster generator like in the example below, it creates an app for the in-cluster cluster. The expected behavior would be that if the `in-cluster` cluster is disabled, the application set controller would not create an app for it. I can't find any options that would tell the application set controller to disable it, is there any option to do that, or do I need to declare what clusters it should use?

This generator is creating an app for the `in-cluster` cluster:
```
spec:
  generators:
    - clusters: {}
```

**Comment by or-mazzapx** [comment]
https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/#deploying-to-the-local-cluster
```
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
```
