### DISCUSSION TITLE
How to pass values-something.yaml file from sub charts to parent charts

### DISCUSSION THREAD

**Discussion by mkucharsky** [argoproj/argo-cd#12018] [General]
How to use `values-ext.yaml` from sub charts in parent charts to fill templates from `subcharts/templates/configmap.yaml`? By default, only the `values.yaml` from subcharts is taken to parent charts.

In naked helm with followed structure:
```
├── charts
│   └── subcharts
│       ├── Chart.yaml
│       ├── templates
│       │   └── configmap.yaml
│       ├── values-ext.yaml
│       └── values.yaml
├── Chart.yaml
├── templates
│   └── another-k8s-obj.yaml
└── values.yaml
```
the command `helm template . -f charts/subcharts/values-ext.yaml` works corretly, but when I try add this path to valueFiles:
```
project: example-application
source:
  repoURL: >-
   https://path-to-parent-repo/example-application.git
  path: .
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
      - charts/subcharts/values-ext.yaml    <---- failed
 ```
I get error: `charts/subcharts/values-ext.yaml: no such file or directory`
