### DISCUSSION TITLE
ArgoCD gRPC + external Dex + Nginx Ingress Controller + OAuth2 Proxy

### DISCUSSION THREAD

**Discussion by thiDucTran** [argoproj/argo-cd#12025] [Q&A]
Has anyone gotten this combination to work for gRPC?

We chose https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-multiple-ingress-objects-and-hosts as our Ingress solution.

Our Argo CD uses external Dex and we use K8s Nginx Ingress Controller for ingress. We also followed the guide at https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/#key-detail and use OAuth2 Proxy for this.

With this setup, we can provide access to our argo cd via web ..but cannot get it to work for argocd CLI

```bash
argocd login --sso mycluster.mydomain.com --grpc-web-root-path argocd-grpc

WARNING: server certificate had error: x509: certificate signed by unknown authority. Proceed insecurely (y/n)? y
FATA[0003] rpc error: code = Unknown desc = unexpected EOF
```

below is our ingress for grpc
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-grpc-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/auth-signin: https://mycluster.mydomain.com/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://mycluster.mydomain.com/oauth2/auth
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /argocd-grpc
        pathType: ImplementationSpecific
        backend:
          service:
            name: argocd-server
            port:
              name: http
    host: mycluster.mydomain.com
  tls:
  - hosts:
    - mycluster.mydomain.com
    secretName: wildcard-tls
```
