### DISCUSSION TITLE
How to ignore difference on specific annotation which includes special charachters

### DISCUSSION THREAD

**Discussion by abdennour** [argoproj/argo-cd#12066] [Q&A] [answered]
Hi, 
 I need to ignore `openshift.io/sa.scc.supplemental-groups` from the Sync of resources of type `Namespace`.
I tried the following: 
1- using `[]`
```yaml
  - kind: Namespace
    jsonPointers:
      - '/metadata/annotations["openshift.io/sa.scc.supplemental-groups"]'
```
2- escape any `.` or `/` by `\`
```yaml
  - kind: Namespace
    jsonPointers:
      - /metadata/annotations/openshift\.io\/sa\.scc\.supplemental-groups
```
3- wildcard

```yaml
  - kind: Namespace
    jsonPointers:
      - /metadata/annotations/openshift*
```
Nothing work ! any idea ?

**Comment by mjeco** [comment, marked as answer]
@abdennour  Try with the below. Generally you must replace `/` with `~1` in the json patch

```yaml
- kind: Namespace
    jsonPointers:
      - /metadata/annotations/openshift.io~1sa.scc.supplemental-groups
```
