### DISCUSSION TITLE
Do argocd notifications support sending notifications per cluster rather than per app?

### DISCUSSION THREAD

**Discussion by btxbtx** [argoproj/argo-cd#12127] [Q&A] [answered]
### Current behavior
Notifications are sent per app, resulting in a sync operation producing a massive amount of notifications, ie.

```
Sync operation of <application 1> started at <time>
Sync operation of <application 2> started at <time>
Sync operation of <application 3> started at <time>
...
Sync operation of <application n> started at <time>
```

### Desired Behavior
Notifications sent per cluster, i.e.

```
Sync began on cluster <cluster>.
Sync succeed on cluster <cluster>
```

or

```
Sync began on cluster <cluster>.
Sync failed on cluster <cluster>
```

### Implementation details
I'm attaching some sample implementation details from my current setup:

**Sample trigger**
```yaml
 triggers:
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.sync.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

**Sample template**
```yaml
  templates:
    template.app-deployed: |
      message: |
        {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version of deployments manifests.
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Revision",
              "value": "{{.app.status.sync.revision}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
```
