### DISCUSSION TITLE
Need help for "Multiple sources app" configuration

### DISCUSSION THREAD

**Discussion by vkandrotas** [argoproj/argo-cd#12201] [Q&A]
Hello Argo CD Team and Experts,

**The first question:**
 
I'm testing the latest Argo CD (v2.6.0-rc6) feature "Multiple sources for applications #10432" and have problems with the configuration. I tested several applications and some of them works, some not. For example, when I use Argo CD example "guestbook" and take the values from my git repo everything is ok. This is the test application:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default


  sources:
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      targetRevision: master
      path: helm-guestbook
      helm:
        valueFiles:
          - $values/argocd/guestbook/values.yaml
    - repoURL: https://bitbucket.org/vktest12/mbbdo.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook4

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
```
But when I use following Application config:

apiVersion: argoproj.io/v1alpha1
```
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default

  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.8.1
      chart: cert-manager
      helm:
        valueFiles:
          - $values/argocd/cert-manager/values.yaml
    - repoURL: https://bitbucket.org/vktest12/mbbdo.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager0

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground
      - PruneLast=true
```
I am getting ComparisonError:

**Error: open .argocd/cert-manager/values.yaml: no such file or directory**

Where is the problem in this scenario? 

**The second question:** 

 - how to can access specific values from referenced source? For example, I have the following values file:

```
cert-manager:
  version: 1.8.1
  values:
    installCRDs: true
```
and want to use .Values.cert-manager.version in my application:

```
sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: {{ $values/.Values.cert-manager.version }} # I want to use  version from values file located in mbbdo.git 
      chart: cert-manager
      helm:
        valueFiles:
          - $values/argocd/cert-manager/values.yaml
    - repoURL: https://bitbucket.org/vktest12/mbbdo.git
      targetRevision: master
      ref: values
```

Is this supported, and what is correct syntax?

best regards,

Virginijus
