### DISCUSSION TITLE
ignoreDifferences for PVCs

### DISCUSSION THREAD

**Discussion by m8-t** [argoproj/argo-cd#12240] [Q&A] [answered]
Hey,

I am in a situation where the live PVC manifest differs from the source (helm generated). This comes from a migration task I needed to do and that failed (use different StorageClass). Because I needed to rollback my changes I changed the PVC live inside the cluster and added the `storageClassName` and `volumeName` to the manifest. I figured out later that it can be done easier (set UID of PVC inside the PV definition), but now I am in a situation where I cannot edit the PVC (and so the sync fails) because PVCs are immutable.
My solution was to ignore those changes but I am not sure if I am doing that right.

I want to ignore both `storageClassName` and `volumeName` fields in the Application.

According to the documentation it should work like this:

```
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: guestbook
    namespace: default
    jsonPointers:
    - /spec/replicas
 ```

I configured my Application like this:

```
  ignoreDifferences:
  - group: core
    jsonPointers:
    - /spec/volumeName
    - /spec/storageClassName
    kind: PersistentVolumeClaim
 ```

Sadly this does not work and Argo CD still states these resources out of sync.

Did I something wrong here?

Thanks

**Comment by m8-t** [comment, marked as answer]
I solved that by myself, I omitted the `- group: core` part and it worked as expected.

So the solution is this:


```
  ignoreDifferences:
  - jsonPointers:
    - /spec/volumeName
    - /spec/storageClassName
    kind: PersistentVolumeClaim
```
