### DISCUSSION TITLE
Configure Gitlab oidc

### DISCUSSION THREAD

**Discussion by SamDecrock** [argoproj/argo-cd#12271] [Q&A]
Hi, how do I configure a self-hosted Gitlab instance as the oidc provider for ArgoCD?

I've tried adding the following to the `argocd-cm` but that didn't help:
```
data:
  url: https://argocd.<redacted>

  oidc.config: |
    name: Gitlab
    issuer: https://<our-gitlab-base-url>
    clientID: <redacted, got it from gitlab>
    clientSecret: <redacted, got it from gitlab>
```
After adding it, I see the `Login with gitlab` button.
When I click on it, I see a few redirects but none of them go through `https://<our-gitlab-base-url>`.
What am I missing?
