### DISCUSSION TITLE
use multiple plugins in sidecar installation method

### DISCUSSION THREAD

**Discussion by vet4ka** [argoproj/argo-cd#12278] [Q&A] [answered]
Hello
Starting with Argo CD v2.5, installing config management plugins (CMPs) via the argocd-cm ConfigMap is deprecated. Support will be removed in v2.6.
Now I use the argocd-cm method like this:

```
 - name: vault-plugin-helm-values-ns
    init:
      command: [sh, -c]
      args: ["helm dependency build || true"]
   generate:
     command: ["sh", "-c"]
     args: ["helm template --namespace $ARGOCD_APP_NAMESPACE --release-name $ARGOCD_ENV_RELEASE_NAME . --set argocd.app.namespace=$ARGOCD_ENV_ARGOCD_APP_NAMESPACE --values $ARGOCD_ENV_VALUES_FILE > all.yaml && argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} all.yaml"]

- name: kustomized-helm
   init:
     command: ["/bin/sh", "-c"]
     args: ["helm dependency build || true"]
   generate:
     command: ["/bin/sh", "-c"]
     args: ["helm template --namespace $ARGOCD_APP_NAMESPACE --release-name $ARGOCD_ENV_RELEASE_NAME --include-crds . --set argocd.app.namespace=$ARGOCD_ENV_ARGOCD_APP_NAMESPACE --values $ARGOCD_ENV_VALUES_FILE  > all.yaml && kustomize build -o allkustom.yaml && argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} allkustom.yaml"]
....
....
```
im try argocd v2.5.9+e5f1194, mount plugins.yaml as a sidecar
```

apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-additional-helm
    spec:
      version: v1.0
      allowConcurrency: true
      init:
        command: [sh, -c]
        args: ["helm dependency build || true "]
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${ARGOCD_APP_NAME} -n ${ARGOCD_APP_NAMESPACE} ${ARGOCD_ENV_ADDITIONAL_SPEC} . --set argocd.app.namespace=$ARGOCD_APP_NAMESPACE > all.yaml && argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} all.yaml"]
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomized-helm
    spec:
      version: v1.0
      allowConcurrency: true
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helm template --namespace $ARGOCD_APP_NAMESPACE --release-name $ARGOCD_ENV_RELEASE_NAME --include-crds . --set argocd.app.namespace=$ARGOCD_ENV_ARGOCD_APP_NAMESPACE --values $ARGOCD_ENV_VALUES_FILE  > all.yaml && kustomize build -o allkustom.yaml && argocd-vault-plugin generate -s ${ARGOCD_ENV_AVP_SECRET} allkustom.yaml"]
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
```
my cmp container logs:
```
time="2023-02-03T13:31:42Z" level=info msg="ArgoCD ConfigManagementPlugin Server is starting" built="2023-01-27T23:27:14Z" commit=e5f1194a6de78cc1124179a4c9bb1ae3484fb77d version=v2.5.9+e5f1194
time="2023-02-03T13:31:42Z" level=info msg="argocd-cmp-server v2.5.9+e5f1194 serving on /home/argocd/cmp-server/plugins/argocd-vault-plugin-v1.0.sock"
time="2023-02-03T13:41:42Z" level=info msg="Alloc=7559 TotalAlloc=19750 Sys=29521 NumGC=7 Goroutines=7"
time="2023-02-03T13:51:42Z" level=info msg="Alloc=7561 TotalAlloc=19757 Sys=29521 NumGC=12 Goroutines=7"
time="2023-02-03T14:01:42Z" level=info msg="Alloc=7561 TotalAlloc=19761 Sys=29521 NumGC=16 Goroutines=7"
```
It is possible using multiple plugin in new version ?
right now I have an empty list of plugins in my ui
