### DISCUSSION TITLE
How do I change repo server TMPDIR with Helm Chart - I can't find a place to mount volume?

### DISCUSSION THREAD

**Discussion by mkotsalainen** [argoproj/argo-cd#12313] [Q&A] [answered]
Hi!

My repo server pods are being evicted due to disk pressure so I wanted to give it a PV. The trouble is I don't know where to mount the volume. The /tmp directory is taken by the Helm Chart (4.5.3) - it mounts an emptyDir there, and I can't override that. 

I've tried /home/argocd/ and /app/config/ but both cause pod to crash with error message permission denied.

```
    env:
      - name: TMPDIR
        value: /home/argocd/argocd-repo-tmp
    volumes:
      - name: argocd-repo-tmp
        persistentVolumeClaim:
          claimName: argocd-repo-tmp
    volumeMounts:
      - mountPath: /home/argocd/argocd-repo-tmp
        name: argocd-repo-tmp

```
        
mkdir /home/argocd/argocd-repo-tmp/_argocd-repo: permission denied

Thanks!
