### DISCUSSION TITLE
Simplify Application in Any namespace

### DISCUSSION THREAD

**Discussion by speedfl** [argoproj/argo-cd#12377] [Ideas]
Hello.

I would like to understand why Application in any namespace feature https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/ required to add sourceNamespaces in AppProject ?

In the future I would also like to see ApplicationSet to be multi namespace. 

However AppProject cannot enforce this as it is for Applications only. Therefore I would probably do a recommendation to use Kyverno, Gatekeeper or custom Admission Webhook to manage this.

I don't think it is a good idea to re-invent the wheel with ArgoCD while this can be achieved with already existing tool. A simple recommendation would do the job.

An example with Kyverno:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: applicationset-name-matches-project
  annotations:
    policies.kyverno.io/title: Ensure ApplicationSet Name Matches Project
    policies.kyverno.io/category: Argo
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: ApplicationSet
    policies.kyverno.io/description: >-
      This policy ensures that the name of the ApplicationSet is the
      same value provided in the project.      
spec:
  validationFailureAction: audit
  background: true
  rules:
   - name: app-project-must-match-namespace
      match:
        any:
        - resources:
            kinds:
              - Application
            namespaces:
              - team-one
              - team-two
              - team-three
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: NotEquals
          value: DELETE
      validate:
        message: "The namespace must match the project."
        pattern:
          spec: 
            project: "{{request.object.metadata.namespace}}"    
    - name: appset-app-project-must-match-namespace
      match:
        any:
        - resources:
            kinds:
              - ApplicationSet
            namespaces:
              - team-one
              - team-two
              - team-three
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: NotEquals
          value: DELETE
      validate:
        message: "The namespace must match the project."
        pattern:
          spec:
            template:
              spec:
                project: "{{request.object.metadata.namespace}}"
```
