### DISCUSSION TITLE
Migration to sidecar CMP

### DISCUSSION THREAD

**Discussion by theodrim** [argoproj/argo-cd#12375] [Q&A] [answered]
Hello, we are currently running v2.4.17+d330967 and looking forward to upgrade to latest 2.5 or 2.6 release.
We are using old config map way to configure our plugin, which is working fine:
```
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cm
    data:
      application.instanceLabelKey: argocd.argoproj.io/instance
      configManagementPlugins: |
        - name: git-crypt
          init:
            command: ["/usr/bin/git-crypt"]
            args: ["unlock", "/tmp/k8s-infrastructure.key"]
          generate:
            command: [sh, -c]
            args: ["find helmReleases namespaces -type f \\( -name '*.yml' -o -name '*.yaml' \\) -exec cat {} \\;"]
          allowConcurrency: false
          lockRepo: true
```

(git-crypt static binary as well as needed key get copied to argocd-server pod via initContainer )

When trying to move this configuration to sidecar:
```
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cmp-plugin
    data:
      plugin.yaml: |
        apiVersion: argoproj.io/v1alpha1
        kind: ConfigManagementPlugin
        metadata:
          name: git-crypt
        spec:
          version: v1.0
          init:
            command: [git-crypt, unlock, '/var/k8s-infrastructure.key']
          generate:
            command: [sh, -c, "find helmReleases namespaces -type f \\( -name '*.yml' -o -name '*.yaml' \\) -exec cat {} \\;"]
          discover:
            find:
              command: [sh, -c, find . -name utilities.yml]
```

But during sync for our main cluster application we are getting:
```ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `git-crypt unlock /var/k8s-infrastructure.key` failed exit status 1: Error: Working directory not clean. Please commit your changes or 'git stash' them before running 'git-crypt unlock'.```

When debugging we observing that only contents of source.path getting copied over to cmp container rather than full repository thus git-crypt does not see `.git` directory and complaining on the state.

Is it possible to properly implement git-crypt via sidecar plugin? Anything we are doing obviously wrong?

Before using any plugin implementation at all, we had simple shell script which was invoked as `helm` binary by argocd, which was doing unlocking then invoking helm original binary. This is very crude approach but it worked, guess we can revert back if sidecar won't be possible.
