### DISCUSSION TITLE
Combining helm charts and plan manifests / kustomization-based manifests in one ApplicationSet?

### DISCUSSION THREAD

**Discussion by travisby** [argoproj/argo-cd#12423] [General]
Howdy,

I've been testing out the argo "monorepo" ApplicationSet approach on my [repo here](https://gitlab.com/travisby/k8s/-/tree/0699111cd18acbf43d52d6f0a4157218f806fc3c).

I have:
* A directory structure that should enforcing the argo project & k8s namespace (imagining something like CODEOWNERS allowing only authorized users to particular subdirectories, I think solving some of the security concerns about "others" creating Applications)
* Manually applied `ApplicationSet` and `Project` manifests

The `ApplicationSet` uses a matrix generator, but the interesting part is from the `git.directories`:

```
...
      - git:
            repoURL: https://gitlab.com/travisby/k8s.git
            revision: HEAD
            directories:
            - path: "apps/*/*/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: '{{path[1]}}'
      source:
        repoURL: https://gitlab.com/travisby/k8s.git
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path[2]}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
```  

So an app in `apps/cluster/argo-rollouts` should create an Application with project=cluster, and namespace=argo-rollouts.

This worked great, even with one app being plain-old-manifests/kustomization-based, and others being Chart based (e.g., `cluster/kube-system/kube-vip-cloud-provider` is not a helm chart, but the rest are)

Where this broke is when I wanted to override certain helm values.  First I tried:

```
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: '{{path[1]}}'
      source:
        repoURL: https://gitlab.com/travisby/k8s.git
        path: '{{path}}'
        helm:
           valueFiles:
             - 'values.yaml'
      destination:
        server: '{{server}}'
        namespace: '{{path[2]}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
 ```

That worked great for the helm charts; all of my values were propagated!  However the POMs would fail because that isn't a valid field for not-helm based apps.

That brought me to this _excellent_ comment with a new solution: everything is kustomized, sometimes using a chart! https://github.com/argoproj/argo-cd/issues/2789#issuecomment-960271294

Now with that, the `namespace` from the `ApplicationSet` is entirely ignored and all of the resources are created with kustomization.yaml's `namespace`, OR `argo-cd` if left blank.  I'd like to keep the `Application` as the arbiter of the `namespace`, although I suppose the `project` should be enforcing the "you're not allowed to write to this namespace" rather than the `Application` / directory structure.

_POM_s are using the correct namespace in this scenario, just not the helm charts.

---

1. Is there a way to force kustomize+helm to use the namespace provided from the `Application` record?
2. Is there a better practice for the combination of manifests + charts in an `ApplicationSet` that I should be doing instead?  My fallback solution is going to be two AppSets, one for helm charts in one directory structure and another for POMs in another.

[edit] I have also seen examples of using custom plugins to solve this --but they all appear to be _before_ the `--enable-helm` feature was available to add to Argo, so I'm wondering if there's something else I'm missing!

Thanks for your help!
