### DISCUSSION TITLE
Will argoCD halt application autoSync if lastSync Status Failed/Error State?

### DISCUSSION THREAD

**Discussion by vrv501** [argoproj/argo-cd#12422] [Q&A]
Hi,
I have argocd configured to deploy my application into same cluster where argocd is deployed but a different namespace
Application source is helm-repo and argocd is expected to track and deploy latest chartVersion
The application is configured with AutoSync(Prune, Self-Heal) and syncRetryLimit of 2

My helm-chart consists of manifests for Deployment & Job. The job is annotated with preSync hook. 
**Expected Behaviour:**
New helm chart published ---> Job completes with Zero Exit Code During PreSync --> Argocd updates the deployment

**What Happened:**
New helm chart published ---> Job Error with NonZero Exit Code During PreSync
This new helm release had an issue with Job Template(incorrect image) so argocd didn't update the deployment. **Application Sync Status is shown as Failed/Error**
No issues so far......

So I fixed my JobTemplate and published a new helm release. All I had to do was wait until argocd picks this new helm release and fix my application as well as sync status. However nothing happened! The application was pretty much stuck in Failed State

I had manually log into UI and manually run app sync so that argocd can pick the latest helm release. 

**Question**:
Is this expected? 
If so can I configure application to autoSync even if lastSync Status Failed so I can avoid doing manual Sync

**Comment by vrv501** [comment]
ArgoCD Helm Chart: v5.20.3

Job:
```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
   argocd.argoproj.io/hook: PreSync
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: curlimages/curl:7.87.0
        command: 
        - sh
        - -c
        - |
          x=$(curl -s -o /dev/null -w '%{response_code}' https://www.google.com);
          if [ $x -ne 200 ]; then
           exit 1;
          fi
      restartPolicy: Never
  backoffLimit: 4
```
Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
