### DISCUSSION TITLE
Argo CD stays out of sync for an Argo Rollout but autosyncs for another

### DISCUSSION THREAD

**Discussion by RamazanKara** [argoproj/argo-cd#12455] [Q&A]
We have ArgoCD deploying Applicationssets with Rollouts. When we change an image version one of our applicationssets behave as expected and the other one does not. ArgoCD stays out-of-sync and does not recognize any changes to the image version, so the Rollout is not triggered. We have debugged this for some time now and are not sure what could be the cause of this issue. As soon as we remove the RespectIgnoreDifferences=true flag, argoCD syncs the Rollout again.

Here is the config for the Applicationsset. Both Applicationsets have pretty much the same config.

```
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: true
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
  retry:
    limit: 3
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 5m
ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
      - /spec/replicas
  - group: apps
    kind: ReplicaSet
    jsonPointers:
      - /spec/replicas
  - group: '*'
    kind: '*'
    managedFieldsManagers:
      - kube-controller-manager
```

Thank you for your support. BR Ramazan
