### DISCUSSION TITLE
ArgoCD environment variables for Kustomize

### DISCUSSION THREAD

**Discussion by jimsnab** [argoproj/argo-cd#12474] [Q&A]
I need to pass some basic things to Kustomize via environment variables. Examples: the environment name, and the artifact server DNS.

This post describes my need well: [9814](https://github.com/argoproj/argo-cd/discussions/9814)

I'm trying to get 9814's solution to work, though I am open to suggestions for a different approach.

The 9814 solution gives me

`multiple application sources defined: Kustomize,Plugin`

This is because my Jenkins pipeline to build the app is trying to tell ArgoCD about the new image:

```
./argocd --grpc-web app set $JOB_NAME --kustomize-image $IMAGE_DIGEST"
```

I can't figure out how to tell Argo to use the kustomize plugin with this "set" operation, and the custom plugin for deploying the app.

I am using [argocd helm chart](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd) and defining the plugin like this:

values.yaml (partial, the other stuff is LoadBalancer setup, TLS, admin password and a repository declaration)

```
server:
  config:
    configManagementPlugins: |
      - name: kustomize-env
        generate:
          command: ["/bin/sh", "-c"]
          args: ["ARTIFACTS_DNS_NAME=$${ARGOCD_ENV_ARTIFACTS_DNS_NAME} ENVIRONMENT_NAME=$${ARGOCD_ENV_ENVIRONMENT_NAME} INTERNAL_DOMAIN_NAME=$${ARGOCD_ENV_INTERNAL_DOMAIN_NAME} kustomize build --enable-helm"]
```

And using it like this:

app.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${app_name}
  namespace: ${argocd_namespace}
spec:
  project: ${project_name}
  source:
    repoURL: ${deployment_repo}
    targetRevision: HEAD
    path: ${deployment_repo_subdir}

    plugin:
      name: kustomize-env
      env:
        - name: ARTIFACTS_DNS_NAME
          value: "${artifacts_dns_name}"
        - name: ARTIFACTS_DNS_NAME_DOCKER
          value: "${artifacts_dns_name_docker}"
        - name: ENVIRONMENT_NAME
          value: "${project_name}"
        - name: INTERNAL_DOMAIN_NAME
          value: "${internal_domain_name}"
  destination:
    server: https://kubernetes.default.svc
    namespace: ${app_name}
```
