### DISCUSSION TITLE
declarative setup and jwt tokens retrieval

### DISCUSSION THREAD

**Discussion by iburrows** [argoproj/argo-cd#12486] [Q&A]
Hi, I would like to use a jwt token for a role. My question is with a declarative setup where argocd is deploying argocd how do I retrieve the jwt token? I have created the following manifest
```yaml
  - name: role
    description: Role used for role access
    policies:
    - p, proj:nonprod:role, applications, sync, nonprod/*, allow
    - p, proj:nonprod:role, applications, get, nonprod/*, allow
    - p, proj:nonprod:role, applications, update, nonprod/*, allow
    jwtTokens:
    - iat: 1676531730
      exp: 0
      id: 1234
```
In the ui or cli I could create one as well but how do I retrieve it by creating it in this way?
I have looked here: https://argo-cd.readthedocs.io/en/release-2.1/operator-manual/declarative-setup/#projects 
Many thanks for the help.
