### DISCUSSION TITLE
Unable to access argocd on https when using subpath /argocd

### DISCUSSION THREAD

**Discussion by GauJosh** [argoproj/argo-cd#12514] [Q&A]
I am able to access argocd UI with subpath /argocd when I set server.insecure as true.
I need to run argocd with https enabled but access to UI fails with 503 when I enable https and set subpath as /argocd.
Has anyone seen this issue before? I am using istio for redirecting to backend service.
Below is my istio virtual service:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  gateways:
  - istio-gateway
  hosts:
  - test.testing.com
  http:
  - match:
    - uri:
        prefix: "/argocd"
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 443
```
Below is browser response:

This page isn’t working right now
test.testing.com can't currently handle this request.
HTTP ERROR 503

Failed to load resource: the server responded with a status of 503 ()
