### DISCUSSION TITLE
Deploy via Kustomize with `commonLabels`

### DISCUSSION THREAD

**Discussion by gregory-j-baker** [argoproj/argo-cd#12532] [Q&A]
I'm trying to deploy Argo CD to a cluster using Kustomize with some `commonLabels` set, but doing so results in the following error:

```
E0219 16:07:24.984376       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167:
  Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.20.0.1:443/api/v1/namespaces/argocd/configmaps?labelSelector=app.kubernetes.io%2Fpart-of%3Dargocd&limit=500&resourceVersion=0": dial tcp 172.20.0.1:443: i/o timeout
```

My `kustomize.yaml` file:

``` yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/environment: shared
  app.kubernetes.io/cluster: aks-hub-shared-nonprod
bases:
  - ../../../environments/shared/argocd
patchesStrategicMerge:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.2/manifests/install.yaml
```

The idea here is that I can override the Argo CD version per-cluster by using `patchesStrategicMerge`, and also label all resources that are deployed with the specified `commonLabels`.

It's looks like the `reflector.go` component doesn't know about my additional labels.. Is there a way to patch these in?
