### DISCUSSION TITLE
Failed to use Plugin on ArgoCD

### DISCUSSION THREAD

**Discussion by emerchalegre** [argoproj/argo-cd#12590] [Q&A] [answered]
Hello everybody. I created a plugin to generate a helm template for my application. The problem is that the environment variables are not being replaced in the plugin. Data below:

```
configManagementPlugins: |
    - name: helm-monkey
      generate:
        command: ["sh", "-c"]
        args: ['helm template --version ${HELM_CHART_VERSION} --repo ${HELM_REPO_URL} --namespace ${NAMESPACE} $HELM_CHART_NAME --name-template=${HELM_RELEASE_NAME} -f $(pwd)/${HELM_VALUES_FILE}']
```
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: application-test
 namespace: HEAD
spec:
 destination:
   namespace: my_namespace
   name: my-cluster
 project: default
 source:
   path: "./"
   repoURL: my_repo_url
   targetRevision: HEAD
   plugin:
     name: helm-monkey
     env:
       - name: HELM_RELEASE_NAME
         value: "test"
       - name: HELM_CHART_VERSION
         value: "0.0.1"
       - name: NAMESPACE
         value: "default"
       - name: HELM_REPO_URL
         value: "my_chart_url"
       - name: HELM_CHART_NAME
         value: "my_chart_name"
       - name: HELM_VALUES_FILE
         value: "dev.yaml"
```

> rpc error: code = Unknown desc = `sh -c helm template --version ${HELM_CHART_VERSION} --repo ${HELM_REPO_URL} --namespace ${NAMESPACE} $HELM_CHART_NAME --name-template=${HELM_RELEASE_NAME} -f $(pwd)/${HELM_VALUES_FILE} ` failed exit status 1: Error: release name "": no name provided
