### DISCUSSION TITLE
Can applicationset ignore generate application if path does not exist ?

### DISCUSSION THREAD

**Discussion by lw8008** [argoproj/argo-cd#12596] [Ideas]
Hi Team,

We are using applicationset with git generators, as you know, it will generate multiple applications based on git.files.path, but if template.spec.source.path doesn't existing/haven't created yet, it will result in error in that application with "path does not exist".
similar like https://github.com/argoproj/argo-cd/discussions/7993

wondering if there is any parameter can ignore such application creation if template.spec.source.path does not existing or how can I avoid that beside create an empty directory?

Thanks
Adam Li

**Comment by QIvan** [comment]
Guys, I would love to have this feature. I recently stumbled upon the same problem too, it's kinda annoying to keep folders with `.gitkeep` for no good reason.

**Comment by QIvan** [comment]
@crenshaw-dev sorry to ping you. Just wondering if there is already a solution for that. Tx

**Comment by francesco-furnari** [comment]
+1, it would be awesome to being able to ignore certain folders or custom values.

**Comment by D13410N3** [comment]
Bumping this.
I'm using ApplicationSet with "common" directory ("apply this to all clusters") and "cluster-specific".
Example:
```
    spec:
      project: default
      sources:
        - directory:
            jsonnet: {}
            recurse: true
          repoURL: "ssh://...repo.git"
          targetRevision: HEAD
          path: "foobar/{{ .name }}"
        - directory:
            jsonnet: {}
            recurse: true
          repoURL: "ssh://...repo.git"
          targetRevision: HEAD
          path: "foobar/_common"
```

In this case I have to create directories with "dummy" empty files there just to make "common" stuff applied, even if I don't need cluster-specific manifests. That's pretty annoying when you have several clusters as you're required to create directory for each existing cluster.
