### DISCUSSION TITLE
Getting 307 on traefik ingressRoute (k3s) with Let'sEncrypt TLS

### DISCUSSION THREAD

**Discussion by DAT4** [argoproj/argo-cd#12723] [Q&A]
I used this configuration from the docs:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.example.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.example.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    certResolver: default
```

and I updated the configMap 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true"
```

I tested it with a portforward - and both port 80 and 443 is serving http 

I tried to change the port to 443 instead of 80 in the ingress configuration. But then I just got some internal server error.

I can see  that NGINX has some force https thing to enable if you get 307, but I don't see how to map that to traefik
