### DISCUSSION TITLE
Kubernetes Job redeploy/sync

### DISCUSSION THREAD

**Discussion by trajanoreuter** [argoproj/argo-cd#12795] [Q&A]
Hi, how are you?
I have a job helm chart, and im using argoCD to deploy.
My first deploy works fine, but my job never sync again.
I searched a lot and found some answers using hooks, but didn't solve my problem.
Hooks solved my problem with Kubernetes job immutability, but with this, I need to click to sync my app manually.
Is there any way to solve this problem?
I need to create a new job every time my branch changes.

Im using argocd `v2.4.7`

My job file
```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "platform-k8s-job-chart.fullname" . }}
  labels:
    {{- include "platform-k8s-job-chart.labels" . | nindent 4 }}
    tags.datadoghq.com/env: {{ .Values.application.environment }}
    tags.datadoghq.com/service: {{ .Values.application.name }}
    tags.datadoghq.com/version: "{{ .Values.image.tag }}"
    app: {{ include "platform-k8s-job-chart.fullname" . }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-options: Replace=true
    rollme: {{ randAlphaNum 5 | quote }}
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.job.backoffLimit }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
  {{- if .Values.job.parallelism }}
  parallelism: {{ .Values.job.parallelism }}
  {{- end }}
  {{- if .Values.job.completions }}
  completions: {{ .Values.job.completions }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.annotations }}
              {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.datadog.logs.enabled }}
        "ad.datadoghq.com/{{ .Values.application.name }}.logs": '[{"source":"{{ .Values.application.language }}","service":"{{ .Values.application.name }}"}]'
        "ad.datadoghq.com/{{ .Values.application.name }}.tags": '{"team": "{{ .Values.labels.team }}","tribe": "{{ .Values.labels.tribe }}"}'
        {{- end }}
      labels:
        tags.datadoghq.com/env: {{ .Values.application.environment }}
        tags.datadoghq.com/service: {{ .Values.application.name }}
        tags.datadoghq.com/version: "{{ .Values.image.tag }}"
        app: {{ include "platform-k8s-job-chart.fullname" . }}
        job: {{ .Values.application.name }}
        {{- with .Values.labels }}
              {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "platform-k8s-job-chart.fullname" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
        - name: {{ .Values.application.name }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- if .Values.envs }}
            {{- range $key, $value := .Values.envs }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            {{- if .Values.secrets }}
              {{- range .Values.secrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform-k8s-job-chart.fullname" $ }}
                  key: {{ . }}
              {{- end }}
            {{- end }}
          {{- if .Values.job.command }}
          command: {{ .Values.job.command }}
          {{- end }}
          {{- if .Values.job.args }}
          {{- with .Values.job.args }}
          args:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
            requests:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
        {{- range $sidecar := .Values.sidecars }}
        {{- if $sidecar.enabled }}
        - name: {{ $sidecar.name }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          image: "{{ $sidecar.image }}"
          {{- if $sidecar.command }}
          command: {{ $sidecar.command }}
          {{- end }}
          {{- if $sidecar.args }}
          {{- with $sidecar.args }}
          args:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          {{- if $sidecar.containerPort }}
          ports:
            - name: http
              containerPort: {{ $sidecar.containerPort }}
              protocol: TCP
          {{- end }}
          env:
            {{- if $sidecar.envs}}
            {{- range $key, $value := $sidecar.envs }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            {{- if $sidecar.secrets }}
              {{- range $sidecar.secrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform-k8s-job-chart.fullname" $ }}
                  key: {{ . }}
              {{- end }}
            {{- end }}
          resources:
            limits:
              memory: {{ $sidecar.resources.memory }}
            requests:
              memory: {{ $sidecar.resources.memory }}
              cpu: {{ $sidecar.resources.cpu }}
        {{- end }}
        {{- end }}
      {{- if .Values.secrets }}
          volumeMounts:
          - name: secrets
            mountPath: /secrets
            readOnly: true
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: {{ include "platform-k8s-job-chart.fullname" . }}
      {{- end }}
      tolerations:
        - effect: NoSchedule
          key: applications
          operator: Exists
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      restartPolicy: {{ .Values.job.restartPolicy }}

```

My argo cd application
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: name-app
  namespace: argocd
spec:
  project: name-app
  source:
    repoURL: 'xxxx'
    path: chart
    targetRevision: branch
    helm:
      valueFiles:
        - values-stg.yaml
  destination:
    name: cluster-name
    namespace: name-app
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

Base values file
```
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

labels:
  project: "__change_me__" # project name
  env: "__change_me__" # stg | sdx | prd
  tribe: "__change_me__" # tribe name
  team: "__change_me__" # team name

annotations:
  documentation: "__change_me__" # Project documentation link
  repository: "__change_me__" # Project repository link

application:
  name: "__change_me__"
  language: "__change_me__"
  environment: "__change_me__" # staging | sandbox | production

serviceAccount:
  awsRole: ""

envs: {} # Env variables for configuration
  # CONFIG_NAME: value

secretsAsEnvVar: false # set it to true if you want to use env vars instead of mounting volumes
secretsEnv: ""
secrets: [] # Secrets
  # - SECRET_NAME

resources:
  memory: "128Mi"
  cpu: "100m"

datadog:
  logs:
    enabled: true

job:
  command: "" # ["/bin/sh"] # exec coomand
  args: ""
    # - "-c"
    # - "echo $(date) - hello world"
  restartPolicy: Never
  # number of before considering a job as failed
  backoffLimit: 5
  parallelism: ""
  completions: ""
  # doc ref: https://kubernetes.io/docs/concepts/workloads/controllers/job/

sidecars:
  - name: ""
    enabled: false
    command: "" # ["/bin/sh"]
    args: ""
      # - "-c"
      # - "echo $(date) - hello world"
    secrets: [] # Secrets
      # - SECRET_NAME
    envs: {} # Env variables for configuration
      # CONFIG_NAME: value
    containerPort: ""
    resources:
      memory: "128Mi"
      cpu: "100m"
    image: ""

```

ex:
<img width="754" alt="Screenshot 2023-03-09 at 19 47 28" src="https://user-images.githubusercontent.com/8987309/224179570-68977e48-f690-4577-9f55-00d02962463f.png">
commits are never in sync
