### DISCUSSION TITLE
`app sync --local` is unable to connect to config management plugin service

### DISCUSSION THREAD

**Discussion by ken1882** [argoproj/argo-cd#12834] [Q&A] [answered]
Hi,
I'm trying to get argocd work with minikube for local development (i.e. sync from local git changes and deploy on local minikube cluster) along with helm and vault.
But when I try to run `argocd sync my-app --local .` it shows this error:
```
RRO[0000] Unable to connect to config management plugin service with address /home/argocd/cmp-server/plugins/argocd-vault-plugin-helm.sock 
ERRO[0000] error dialing to cmp-server for plugin argocd-vault-plugin-helm.sock, dial unix /home/argocd/cmp-server/plugins/argocd-vault-plugin-helm.sock: connect: no such file or directory  CWE=775 security=2
FATA[0000] plugin sidecar failed. couldn't find cmp-server plugin with name argocd-vault-plugin-helm supporting the given repository
```
Here's my configmap for `cmp-plugin` and helm values:
```
# cmp-plugins.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      # Note: this command is run _before_ anything is done, therefore the logic is to check
      # if this looks like a Kustomize bundle
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      # Note: this command is run _before_ any Helm templating is done, therefore the logic is to check
      # if this looks like a Helm chart
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      init:
        command:
          - sh
          - "-c"
          - |
            for file in values*.yaml
            do
              # if helm args contain with filename
              if echo "$ARGOCD_ENV_HELM_ARGS" | grep -q "$file"; then
                cp $PWD/$file $PWD/tmp-$file
                # make values file pretend k8s yaml 
                echo "kind: Fake" >> $PWD/tmp-$file
                argocd-vault-plugin generate $PWD/tmp-$file |
                sed "s/kind: Fake//g" |
                # static output with special tag
                sed "s/@: |[+-]*/:/g" > $PWD/$file
              fi
            done
      generate:
        command:
          - sh
          - "-c"
          - |
            if [ -n "${ARGOCD_ENV_IMAGE_TAG}" ]; then SET="image.tag=${ARGOCD_ENV_IMAGE_TAG}"; fi &&
            helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} --set "${SET}" . |
            argocd-vault-plugin generate - > $(basename $PWD)-$ARGOCD_APP_NAME.yaml
            if [ -s $(basename $PWD)-$ARGOCD_APP_NAME.yaml ];then
              cat $(basename $PWD)-$ARGOCD_APP_NAME.yaml
            else
              echo "image: \"parse values.yaml error.\""
            fi
      lockRepo: false

```

```
# values.yaml
argo-cd:
  fullnameOverride: argocd
  configs:
    rbac:
      policy.csv: |
        p, role:xxx, xxxxx, *, */*, allow
  repoServer:
    volumes:
      - configMap:
          name: cmp-plugin
        name: cmp-plugin
      - name: custom-tools
        emptyDir: {}
    initContainers:
      - name: download-tools
        image: registry.access.redhat.com/ubi8
        env:
          - name: AVP_VERSION
            value: 1.13.1
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    extraContainers:
      # argocd-vault-plugin with plain YAML
      - name: avp
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.6.1
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        envFrom:
          - secretRef:
              name: vault-configuration
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp.yaml
            name: cmp-plugin
          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

      # argocd-vault-plugin with Kustomize
      - name: avp-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.6.1
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        envFrom:
          - secretRef:
              name: vault-configuration
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-kustomize.yaml
            name: cmp-plugin
          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

      # argocd-vault-plugin with Helm
      - name: avp-helm
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.6.1
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        envFrom:
          - secretRef:
              name: vault-configuration
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-helm.yaml
            name: cmp-plugin
          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

```

Additional information that probably helps:
* OS: Ubuntu 22.04
* Minikube version: v1.26.1
* I used `kubectl port-forward svc/argocd-server 8080:443 -n argocd` then `argocd login locahost:8080` with admin account

Any help is appreciated, thanks in advance!
