### DISCUSSION TITLE
Plugin's behavior with "multiple sources for an Application"

### DISCUSSION THREAD

**Discussion by amorozkin** [argoproj/argo-cd#12854] [Q&A]
Could you please clarify - what kind of behavior is to be expected from plugin when Application uses multiple sources (helm + git for example)
Currently docs say ["Both init and generate commands are executed inside the application source directory"](https://argo-cd.readthedocs.io/en/release-2.0/user-guide/config-management-plugins/)
Which source directory is referenced here?

**Comment by crenshaw-dev** [comment]
We clone the repository and then run the init and generate commands inside the repo, under the `path` path (if specified for the source).

This is true regardless of whether you are using one source or multiple sources.

**Reply by amorozkin** [reply]
Is this example given below valid?
```  
sources:
    - chart: elasticsearch
      repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
    - repoURL: https://github.com/argoproj/argocd-example-apps.git #  <- kustomize 
      path: guestbook
      targetRevision: HEAD
    - repoURL: https://github.com/argoproj/another-argocd-example-apps.git    # <- plain yaml mainfests
      path: someapp
      targetRevision: HEAD
```

If SO - what kind of generate command (commands?) would be valid for this example if we want to: 

1. run `helm template` for _elasticsearch_ chart 
2. run `kustomize build` for _argocd-example-apps.git_
3. run `cat *.yaml` for _another-argocd-example-apps.git_
4. get outputs from commands 1-3 and pass it to _argocd-vault-plugin's_ stdin for example  (let's say all repo sources doesn't contain any duplicate kubernetes resources)

Is it possible?
