### DISCUSSION TITLE
Migrating multiple plugins from argocd-cm to sidecar

### DISCUSSION THREAD

**Discussion by bsteinm2** [argoproj/argo-cd#12898] [Q&A] [answered]
I am currently unable to get more than one plugin to function out of the sidecar. Interestingly, the first plugin by order in the configmap gets installed and functions correctly.

Here is the configmap:
```
apiVersion: v1
metadata: 
  name: plugin-config
data:
  plugin.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME ${ARGOCD_ENV_HELM_ARGS} . > all.yaml && argocd-vault-plugin generate -s argocd-vault-plugin-credentials all.yaml"]
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      generate:
        command: ["sh", "-c"]
        args: ["argocd-vault-plugin generate -s argocd-vault-plugin-credentials ./"]
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomized-helm
    spec:
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build || true"]
      generate:
        command: [sh, -c]
        args: ["helm template ${ARGOCD_APP_NAME} -n ${ARGOCD_APP_NAMESPACE} ${ARGOCD_ENV_HELM_ARGS} . --include-crds > all.yaml && kustomize build"]
kind: ConfigMap
```

I am assuming something is wrong with the configmap and not the deployment, since the single plugin installs correctly each time. There is another [thread](https://github.com/argoproj/argo-cd/discussions/12278?sort=new#top) where this was discussed, but it got marked answered and there are some unresolved comments, and I don't know if it will get more attention. This thread only states that it is possible to install multiple plugins via the sidecar method, but does not point out what could be wrong with the code.
