### DISCUSSION TITLE
Facing issue with helm and argocd

### DISCUSSION THREAD

**Discussion by Shubham1406220** [argoproj/argo-cd#12892] [General]
Currently my helm chart doesn't contain the values file since it is present in diff repo. When i try to setup applicaton via application getting this error on argo console

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template product-cache-writer --namespace dev --kube-version 1.24 --values /tmp/095a049d-33a5-4e5e-b2a8-d24093c4f403/common-helm/product-cache-writer/values-dev.yaml --values /tmp/095a049d-33a5-4e5e-b2a8-d24093c4f403/common-helm/manifest-dev.yaml --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AppProject --api-versions argoproj.io/v1alpha1/Application --api-versions argoproj.io/v1alpha1/ApplicationSet --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2 --api-versions autoscaling/v2/HorizontalPodAutoscaler --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions batch/v1beta1 --api-versions batch/v1beta1/CronJob --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions crd.k8s.amazonaws.com/v1alpha1 --api-versions crd.k8s.amazonaws.com/v1alpha1/ENIConfig --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions discovery.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1/EndpointSlice --api-versions elbv2.k8s.aws/v1alpha1 --api-versions elbv2.k8s.aws/v1alpha1/TargetGroupBinding --api-versions elbv2.k8s.aws/v1beta1 --api-versions elbv2.k8s.aws/v1beta1/IngressClassParams --api-versions elbv2.k8s.aws/v1beta1/TargetGroupBinding --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions events.k8s.io/v1beta1 --api-versions events.k8s.io/v1beta1/Event --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta1/PriorityLevelConfiguration --api-versions flowcontrol.apiserver.k8s.io/v1beta2 --api-versions flowcontrol.apiserver.k8s.io/v1beta2/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta2/PriorityLevelConfiguration --api-versions karpenter.k8s.aws/v1alpha1 --api-versions karpenter.k8s.aws/v1alpha1/AWSNodeTemplate --api-versions karpenter.sh/v1alpha5 --api-versions karpenter.sh/v1alpha5/Provisioner --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1/Alertmanager --api-versions monitoring.coreos.com/v1/PodMonitor --api-versions monitoring.coreos.com/v1/Probe --api-versions monitoring.coreos.com/v1/Prometheus --api-versions monitoring.coreos.com/v1/PrometheusRule --api-versions monitoring.coreos.com/v1/ServiceMonitor --api-versions monitoring.coreos.com/v1/ThanosRuler --api-versions monitoring.coreos.com/v1alpha1 --api-versions monitoring.coreos.com/v1alpha1/AlertmanagerConfig --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions node.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1/RuntimeClass --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions policy/v1beta1 --api-versions policy/v1beta1/PodDisruptionBudget --api-versions policy/v1beta1/PodSecurityPolicy --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/CSIStorageCapacity --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1beta1/CSIStorageCapacity --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --api-versions vpcresources.k8s.aws/v1beta1 --api-versions vpcresources.k8s.aws/v1beta1/SecurityGroupPolicy --include-crds` failed exit status 1: Error: open /tmp/095a049d-33a5-4e5e-b2a8-d24093c4f403/common-helm/product-cache-writer/values-dev.yaml: no such file or directory
```

my applicationset config

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-helm-application-set
  namespace: myargo
spec:
  generators:
    - git:
        repoURL: https://gitlab.xxxx.com/xxx/application.git
        revision: HEAD
        directories: 
          - path: '*'            
  # These fields are identical to the Application spec.
  template:
    metadata:
      name: '{{ path }}'
    spec:
      project: "default"
      source:
        repoURL: https://gitlab.xxx.com/api/v4/projects/613/packages/helm/stable
        targetRevision: 0.1.5
        chart: common-helm
        path: '{{ path }}'
        helm:
          valueFiles:
          - "{{ path }}/values-dev.yaml"
          - "manifest-dev.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: dev 
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
```
      
But when i try to install helm chart manually it works fine

**Comment by crenshaw-dev** [comment]
The ApplicationSet controller just creates Applications. The Application controller is incapable of knowing that `"{{ path }}/values-dev.yaml"` lives in a different repository. It's looking in `https://gitlab.xxx.com/api/v4/projects/613/packages/helm/stable` for that file.

Argo CD 2.6 introduced "multi-source Applications", with the ability for [one Helm source to reference value files from a git source](https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository).

You can change your ApplicationSet to take advantage of this feature.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-helm-application-set
  namespace: myargo
spec:
  generators:
    - git:
        repoURL: https://gitlab.xxxx.com/xxx/application.git
        revision: HEAD
        directories: 
          - path: '*'            
  # These fields are identical to the Application spec.
  template:
    metadata:
      name: '{{ path }}'
    spec:
      project: "default"
      sources:
      - repoURL: https://gitlab.xxx.com/api/v4/projects/613/packages/helm/stable
        targetRevision: 0.1.5
        chart: common-helm
        helm:
          valueFiles:
          - "$values/values-dev.yaml"
          - "manifest-dev.yaml"
      - repoURL: https://gitlab.xxxx.com/xxx/application.git
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: dev 
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
```
