### DISCUSSION TITLE
Failed to verify token

### DISCUSSION THREAD

**Discussion by NirElgrabli1** [argoproj/argo-cd#12934] [General]
im trying to connect my argocd in my local network to adfs, and while trying to fix it and nothing is changed i would like some help with this issue:

the log:
"Failed to verify token: failed to verify token: failed to query provider \"https://myargoserver/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": http: server gave HTTP response to HTTPS client "
(in my server side )
(right now my dexserver.disable.tls = true , and server.insecure=true in my configamps ) 
ill apriciate any help now !!!

**Comment by crenshaw-dev** [comment]
Please check the documentation on [disabling TLS to the Dex server](https://argo-cd.readthedocs.io/en/latest/operator-manual/tls/#disabling-tls-to-argocd-dex-server).

I think you need to set an additional parameter.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  dexserver.disable.tls: "true"
  server.dex.server.plaintext: "true"
```

I believe the Dex server should be automatically updated to use `http` instead of `https`. If not, you can set this:

```yaml
  dex.server: "http://argocd-dex-server:5556"
```
