### DISCUSSION TITLE
Multiple Wildcards in Git Generator ApplicationSet

### DISCUSSION THREAD

**Discussion by fbongiovanni29** [argoproj/argo-cd#12948] [Q&A] [answered]
Hello, I am trying to loop through many directories recursively and dynamically create applications based on values files on them with the git generator application set. I'm wondering if what I'm trying to accomplish is possible. I have the following:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.example.com/me/argocd
        revision: mybranch
        directories:
          - path: services/**/environments/**/regions/**/values.yaml
  template:
    metadata:
      name: {{path[1]}}-{{path[3]}}-{{path[5]}}
    spec:
      destination:
        namespace: {{path[1]}}-{{path[3]}}
        server: https://kubernetes.default.svc
      project: '{{path[3]}}'
      source:
        path: chart/
        repoURL: https://github.example.com/me/argocd.git
        targetRevision: mybranch
        helm:
          valueFiles:
            - '../environments/{{path[3]}}/values.yaml'
            - '../regions/{{path[5]}}/values.yaml'
            - '../services/{{path[1]}}/values.yaml'
            - '../services/{{path[1]}}/environments/{{path[3]}}/values.yaml'
            - '../services/{{path[1]}}/environments/{{path[3]}}/regions/{{path[5]}}/values.yaml'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

The ApplicationSet syncs successfully but there's no applications created from it and no errors either. Is this possible? Am I doing something wrong?

**Comment by fbongiovanni29** [comment, marked as answer]
Switching the same code to the files generator worked:
```
spec:
  generators:
    - git:
        repoURL: https://github.example.com/me/argocd
        revision: mybranch
        files:
          - path: services/**/environments/**/regions/**/values.yaml
```
