### DISCUSSION TITLE
Workaround for remote private Kustomize bases using SSH

### DISCUSSION THREAD

**Discussion by karlschriek** [argoproj/argo-cd#12975] [Q&A]
With reference to this issue I created a while ago, https://github.com/argoproj/argo-cd/issues/8342 I am looking for a short-term workaround that can help me achieve this, even if not officially supported.

The short version of the story is as follows: point an Application to Repo A (which is a private repo, for which an SSH key has been registered). ArgoCD is able to deploy from Repo A without any issues. Now place a kustomization file in Repo A which points to a private SSH url for Repo B. 

The way permissions are scoped on ArgoCD it will not be able to make this jump to Repo B. I have even tried making the SSH key the same for both repos (which the documentation seems to suggest would work, but it doesn't for me https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#private-remote-bases). I have also tried mounting the SSH keys directly onto /home/argocd/.ssh/id_rsa on the repo server (this is a workaround from https://github.com/argoproj/argo-cd/issues/827 which I have successfully used in the past, but more recently have not managed to get this to work).

I would really like to use SSH rather than HTTPS here if possible.

**Comment by jDmacD** [comment]
Did you every get anywhere with this? I'm in a similar situation. The documention implies this should work. I'm using on-prem gitlab so HTTPS isn't an option.

**Reply by jdelucaa** [reply]
Does it work with HTTPS? Could not make it work with HTTPS either. I am using GitHub App credentials https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#github-app-credential.

**Comment by joebowbeer** [comment]
@jdelucaa GitHub App works for us. We give the single GitHub App read access to a list of repos.

What syntax are you using for the remote base urls?

If the repos have different creds, then maybe something like a git-sync initContainer or an ArgoCD config plugin will help.

**Reply by jdelucaa** [reply]
Both repositories use the same credentials, I am not using a credential template though.

The syntax in the `kustomization.yaml` file is:
https://github.com/my-org/my-repo.git//kustomize?ref=v2.0

I am seeing the following error:

```
fatal: could not read Username for 'https://github.com': No such device or address : exit status 128
```

I tried a bunch of different configurations, I tried ssh too, but no success.

**Reply by joebowbeer** [reply]
kustomize syntax doc is here:

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

I assume this works:

```bash
kustomize build https://github.com/my-org/my-repo.git//kustomize?ref=v2.0
```

Kustomize will use go-getter to fetch this.

This works for us with repository.credentials

```yaml
  repository.credentials: |
    - githubAppID: xyz
      githubAppInstallationID: xyz
      githubAppPrivateKeySecret:
        key: githubAppPrivateKey
        name: app-secret
      url: https://github.com/my-org
```

(We don't add `.git` but I don't think that matters.)

**Reply by jdelucaa** [reply]
Hey, thanks for the examples.

We have more or less the same thing, the difference is that we don't use `repository.credentials` (where is this configured by the way?). 
I have a `Secret` with the label `argocd.argoproj.io/secret-type: repository` (or `argocd.argoproj.io/secret-type: repo-creds` - when using a credential template), like: 

```
apiVersion: v1
kind: Secret
metadata:
  name: my-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  githubAppID: xxx
  githubAppInstallationID: yyy
  githubAppPrivateKey: key
  type: git
  url: https://github.com/my-org/my-repo.git
type: Opaque
```

Or to share the same creds for both repos I do:

```
apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  githubAppID: xxx
  githubAppInstallationID: yyy
  githubAppPrivateKey: key
  type: git
  url: https://github.com/my-org
type: Opaque
```

I don't see anything wrong, it should just work. I tried everything. 
ArgoCD v2.14.10.

Maybe it requires some special `kustomize.buildOptions`? For the error I am getting it seems like Kustomize it's not using the repository credentials I provided to Argo CD.
