### DISCUSSION TITLE
ApplicationSet syncPolicy setting is not working

### DISCUSSION THREAD

**Discussion by helloworld113** [argoproj/argo-cd#12986] [Q&A] [answered]
I am use ApplicationSet to autocreate app, and the under is my syncPolicy, I have setting prune: false and selfHeal: false but it not work, when I change rescoure in living cluster by manual It also selfHeal ，I want stop selfHeal  is anyone can help me？thanks
```
spec:
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```
I have read doc from auto-sync https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/

**Comment by helloworld113** [comment]
the docs： By default (and as a safety mechanism), automated sync will not delete resources when Argo CD detects the resource is no longer defined in Git
my argocd：when I delete defined in Git the cluster resouces is delete. i dont want delete is

the docs: By default, changes that are made to the live cluster will not trigger automated sync.
my argocd :  when i change in live cluster and then is trigger automated sync to selfHeal. i dont want selfHeal.

ApplicationSet setting:
```
spec:
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```
version:
{
    "Version": "v2.6.0+acc554f",
    "BuildDate": "2023-02-06T21:17:26Z",
    "GitCommit": "acc554f3d99010e0353b498a595844b30090556f",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}

**Comment by reginaelyse** [comment]
Hi @helloworld113, as per our docs [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/): 

> 
> Prevent an Application's child resources from being modified[¶](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#prevent-an-applications-child-resources-from-being-modified)
> Changes made to the ApplicationSet will propagate to the Applications managed by the ApplicationSet, and then Argo CD will propagate the Application changes to the underlying cluster resources (as per [Argo CD Integration](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Argo-CD-Integration/)).
> 
> The propagation of Application changes to the cluster is managed by the [automated sync settings](https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/), which are referenced in the ApplicationSet template field:
> 
> spec.template.syncPolicy.automated: If enabled, changes to Applications will automatically propagate to the cluster resources of the cluster.
> Unset this within the ApplicationSet template to 'pause' updates to cluster resources managed by the Application resource.
> spec.template.syncPolicy.automated.prune: By default, Automated sync will not delete resources when Argo CD detects the resource is no longer defined in Git.
> For extra safety, set this to false to prevent unexpected changes to the backing Git repository from affecting cluster resources.
> 
if you are using applicationSet you might want to edit the applicationSet `spec.template.syncPolicy` instead of the actual application. 

However, in upcoming 2.7 release there will be [this feature](https://github.com/argoproj/argo-cd/pull/12408) that will allow you to configure annotations that are preserved by the AppSet. Please see the [unreleased 2.7 documentation on this](https://argo-cd.readthedocs.io/en/release-2.7/operator-manual/applicationset/Controlling-Resource-Modification/#preserving-changes-made-to-an-applications-annotations) for how it will work. 

If this answer satisfies your use case, please go ahead and close the discussion :) Thanks!

**Reply by helloworld113** [reply]
thanks for you reply, as you said 

> Unset this within the ApplicationSet template to 'pause' updates to cluster resources managed by the Application resource.
spec.template.syncPolicy.automated.prune: By default, Automated sync will not delete resources when Argo CD detects the resource is no longer defined in Git.

this is my config, but  when i remove resource from git and live cluster remove also.
```
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path[0]}}'
        server: '{{server}}'
      project: watch-prod
      source:
        path: '{{path}}'
        repoURL: 'http://xx.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
```

**Reply by reginaelyse** [reply, marked as answer]
Hopefully I'm understanding your issue correctly (and I apologize if I'm not)... could you try setting  `.syncPolicy.preserveResourcesOnDeletion` to `true` in the ApplicationSet? I'm looking at this in the docs and wondering if that's the issue you're facing https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Application-Deletion/

**Reply by helloworld113** [reply]
Much appreciated. yea, I have try is before, such as 
```
      syncPolicy:
        preserveResourcesOnDeletion: true
        automated:
          allowEmpty: true
          prune: false
```
I edit is online thouth cloud, may be use `apply`  but it seem not to save to k8s. is  means i should rebuild the  `ApplicationSet ` resouces ?

**Reply by helloworld113** [reply]
this  is the error :
```
<nil>: Invalid value: "The edited file failed validation": ValidationError(ApplicationSet.spec.template.spec.syncPolicy): unknown field "preserveResourcesOnDeletion" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.syncPolicy
```

**Reply by helloworld113** [reply]
I have did it, the syncPolicy not in template.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xx-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: watch-ns/*
      - exclude: true
        path: donotdeploy
      repoURL: http://xxx.git
      revision: HEAD
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path[0]}}'
        server: https://kubernetes.default.svc
      project: xx
      source:
        path: '{{path}}'
        repoURL: http://xx.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          allowEmpty: true
          prune: false
```
