### DISCUSSION TITLE
policy.default: role:readonly does not work in my environment

### DISCUSSION THREAD

**Discussion by pretystar** [argoproj/argo-cd#13024] [Q&A]
Dear all:

I setup argocd behind oauth2-proxy/ingress, I try to make anonymous can access argocd with readonly permission, below are the configurations, but anonymous user can still create applications, anything wrong with my setup?
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.24.1
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
data:
  admin.enabled: 'false'
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: 'false'
  server.rbac.log.enforce.enable: 'false'
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  users.anonymous.enabled: 'true'
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.24.1
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
data:
  policy.csv: ""
  policy.default: role:readonly
  scopes: '[groups]'
```
