### DISCUSSION TITLE
in gke use. ServiceNetworkEndpointGroup HEALTH Pending deletion

### DISCUSSION THREAD

**Discussion by kangame2000** [argoproj/argo-cd#13037] [Q&A]
argocd ver: 2.6.7
k8s version: v1.25.6-gke.200

Use an argo app project to Gitops all k8s objects. Currently, services that use neg come with a ServiceNetworkEndpointGroup object.
After the project is created, it will always be in OutOfSync, because ServiceNetworkEndpointGroup HEALTH is always in Pending deletion state
What is the reason, how to fix or avoid ignoring it

**Comment by WowSuchRicky** [comment]
Hello @kangame2000, I know this is old but I ran into this recently too. It's because GKE/EKS/AKS etc will automatically have to create additional resources in order to work correctly - such as NEGs.


One possible fix would be to do the following:
`kubectl patch configmap argocd-cm -n argocd --type merge -p '{"data":{"resource.exclusions":"- apiGroups:\n  - \"networking.gke.io\"\n  kinds:\n  - \"ServiceNetworkEndpointGroup\""}}'`
This patches the argocd configmap to tell it to ignore NEGs.

Did you end up doing something else that works too?

**Reply by ghost** [reply]
thanks, that worked for me :) seems you cant add that into the helm chart though so had to do it manually

**Reply by Baune8D** [reply]
You can add it to the Helm chart like this:

```yaml
configs:
  cm:
    resource.exclusions: |
      - apiGroups:
          - networking.gke.io
        kinds:
          - ServiceNetworkEndpointGroup
        clusters:
          - "*"
```
