### DISCUSSION TITLE
Job sync management (with failure management)

### DISCUSSION THREAD

**Discussion by Fran-Rg** [argoproj/argo-cd#13052] [Q&A]
Very much related to https://github.com/argoproj/argo-cd/discussions/7984

What I'm trying to do:
- build an image with all db migrations at time X
- run a db migration job as a job
- if new migrations scripts, rebuild a new image
- apply new job with the new image

We had issues with immutability thus we started using the annotations:
```
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
```

The problem is the migration script job failed and it looks to break the pre-sync which stops the hook-delete-policy:
![image](https://user-images.githubusercontent.com/4979840/228792642-6476b121-6c1b-4b9e-8563-654e9c0fd98c.png)

Is there something that could be done to resolve this?

Also if I try to sync, it considers there's no resource:
![image](https://user-images.githubusercontent.com/4979840/228793888-6aa77485-3d73-4828-8839-756b03152c9e.png)

I'm using v2.4.8+844f79e

**Comment by Fran-Rg** [comment]
This is what the UI shows:
![image](https://user-images.githubusercontent.com/4979840/228800745-90b90971-c8aa-43fd-a070-eb630b2d25ee.png)

But in that situation if clicking "Sync" there's nothing to sync.

In other words, to reproduce this:
Create a job like:
```
---
# Source: that-service-db/charts/job/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: that-service-db
  labels:
    helm.sh/chart: job-1.0.0
    app.kubernetes.io/name: that-service-db
    app.kubernetes.io/instance: job-that-service-db
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  ttlSecondsAfterFinished: 604800
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: that-service-db
        image: "that-service-db:<IMAGE>"
```

Have it fail when running. Then you should get into that situation
