### DISCUSSION TITLE
Unable to access secrets within Applications

### DISCUSSION THREAD

**Discussion by Subbeh** [argoproj/argo-cd#13124] [Q&A]
I have the following Application manifest to deploy Drone using a Helm chart. However, I can't seem to get the secrets referenced within the Helm values as it give me this error:

```
        Error: values don't meet the specifications of the schema(s) in the
        following chart(s):

        drone:

        - env.DRONE_RPC_SECRET: String length must be greater than or equal to 1
```

If I change the parameters to use the values directly instead of secrets, all works fine.
What am I missing?

### Application:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone
  namespace: argocd
spec:
  project: default
  sources:
    - chart: drone
      repoURL: https://charts.drone.io
      targetRevision: 0.6.4
      helm:
        parameters:
        - name: "env.DRONE_GITEA_SERVER"
          value: "https://git.domain.com"
        - name: "env.DRONE_SERVER_HOST"
          value: "drone.k8s.domain.com"
        - name: "env.DRONE_SERVER_PROTO"
          value: "drone.k8s.domain.com"
        - name: "env.DRONE_GITEA_CLIENT_ID"
          valueFrom:
            secretKeyRef:
              name: argocd-doppler-secret
              key: DRONE_GITEA_CLIENT_ID
        - name: "env.DRONE_GITEA_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              name: argocd-doppler-secret
              key: DRONE_GITEA_CLIENT_SECRET
        - name: "env.DRONE_RPC_SECRET"
          valueFrom:
            secretKeyRef:
              name: argocd-doppler-secret
              key: DRONE_RPC_SECRET
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

### Secret
```bash
$ kubectl get secret -n argocd argocd-doppler-secret -o jsonpath='{.data}' | jq | grep DRONE_RPC_SECRET

  "DRONE_RPC_SECRET": "xxxxxxxxxxxxxxx=",
```
