### DISCUSSION TITLE
can I put gitea and github type together in applicationset pullrequest type?if I put together the repo url is different how can I specify?

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-cd#13163] [Q&A]
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
  - pullRequest:
      gitea:
        api: http://192.168.229.148:3000
        owner: mark
        insecure: true
        repo: argocd
        tokenRef:
          secretName: gitea-auth
          key: token
      github:
        owner: "13567436138"
        repo: argocd-test
      template:
        metadata:
          labels:
            app: nginx
        spec:
          source:
            repoURL: 'http://192.168.229.148:3000/mark/argocd.git'
            targetRevision: '{{ head_sha }}'
            path: demo1
          project: project
          destination:
            server: https://192.168.229.153:6443
            namespace: demo
      requeueAfterSeconds: 30
  template:
    metadata:
      name: 'myapp-{{ branch }}-{{ number }}'
    spec:
      source:
        repoURL: 'http://192.168.229.148:3000/mark/argocd.git'
        targetRevision: '{{ head_sha }}'
        path: demo1
      project: project
      destination:
        server: https://192.168.229.153:6443
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```
