### DISCUSSION TITLE
notification service '' is not supported

### DISCUSSION THREAD

**Discussion by yamagai** [argoproj/argo-cd#13198] [Q&A]
Hi, team! 
I'm having some trouble with an error, so I have a question.

## What happened?
- argocd-notification-controller is throwing the following error
  ```
  argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=error msg="Failed to notify recipient { hoge} defined in resource argocd/xxx: notification service '' is not supported" resource=argocd/xxx
  ```
    - The complete log including before and after is here.
      ```
      argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=info msg="Start processing" resource=argocd/xxx
      argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=info msg="Trigger on-sync-failed result: [{[0].XXXXXXXXXXXXXXX  [app-sync-failed] false}]" resource=argocd/xxx
      argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=info msg="Trigger on-sync-succeeded result: [{[0].YYYYYYYYYYYYYY [app-sync-succeeded] true}]" resource=argocd/xxx
      argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].YYYYYYYYYYYYYY' already sent to '{slack hoge}'" resource=argocd/xxx
      argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].YYYYYYYYYYYYYY' to '{ hoge}'" resource=argocd/xxx
      argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=error msg="Failed to notify recipient { hoge} defined in resource argocd/xxx: notification service '' is not supported" resource=argocd/xxx
      argocd-notifications-controller-78bf8bf4d-4r7x4 argocd-notifications-controller time="2023-04-12T02:50:25Z" level=info msg="Processing completed" resource=argocd/xxx
      ```

## What I want to know
- I would like to know the cause of this phenomenon and its resolution.

## Reasons inferred from the source code
- As a result of how argocd-notification-controller interpreted the configuration, the following `services.Destination` contains a Service with an empty string value.
  ```
  services.Destinations{
    "on-sync-failed": []services.Destination{
	    services.Destination{Service: "slack", Recipient: "hoge"},
    },
    "on-sync-succeeded": []services.Destination{
	    services.Destination{Service: "slack", Recipient: "hoge"},
	    services.Destination{Service: "", Recipient: "hoge"}, ## This is causing an error
    },
  }
  ```

- To explain in detail what I have investigated on my own...
    - As you can see from the entire log that includes the error mentioned above, the error occurs when the `services.Destination` with `Service: ""` is processed during `Trigger: on-sync-succeeded`. The error is triggered by the following code
        - https://github.com/argoproj/notifications-engine/blob/43c9003a3e079aa2c83825c5fe7ce0a4a57530f2/pkg/controller/controller.go#L165-L167

    - The destinations processed by this method are obtained by the following code:
        - https://github.com/argoproj/notifications-engine/blob/43c9003a3e079aa2c83825c5fe7ce0a4a57530f2/pkg/controller/controller.go#L182
        - I thought something might be wrong here

    - But when I edited the notification-engine test case and tried to load my settings, `services.Destination` with an empty string was not created.
        - Therefore, I wondered if the Destination was being added from somewhere on the argocd-notifications-controller side, which is used internally, rather than the notifications-engine side.
        - However, as I will explain later, `services.Destination` with an empty string was not created in my settings even in the following code where I noticed that it might be created:
            - https://github.com/argoproj/argo-cd/blob/7be094f38d06859b594b98eb75c7c70d39b80b1e/notification_controller/controller/controller.go#L93-L94
    - I hit a dead end at this point, so I am asking for help here...

## Settings for when a problem occurs
- argocd version is v2.6.4
- AppProject
  ```
  apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    labels:
      app.kubernetes.io/instance: aaa
    name: fuga
    namespace: argocd
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: fuga
      server: https://kubernetes.default.svc
    orphanedResources:
      warn: true
    sourceRepos:
    - https://github.com/....
  ```

- Application
  ```
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      argocd-image-updater.argoproj.io/image-list: image=...
      argocd-image-updater.argoproj.io/image.ignore-tags: ...
      argocd-image-updater.argoproj.io/image.update-strategy: ...
      argocd-image-updater.argoproj.io/write-back-method: argocd
      notifications.argoproj.io/subscribe.slack: hoge
      notified.notifications.argoproj.io: '{"on-sync-succeeded:[0].YYYYYYYYYYYYYY:slack:hoge":...}'
    labels:
      app.kubernetes.io/instance: aaa
    name: xxx
    namespace: argocd
  spec:
    destination:
      namespace: fuga
      server: https://kubernetes.default.svc
    project: fuga
    source:
      kustomize:
        images:
        - ...
      path: kubernetes/...
      repoURL: https://github.com/...
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  ```

- ConfigMap
  ```
  apiVersion: v1
  data:
    config.yaml: |
      context:
        argocdUrl: https://argocd.example.com
    defaultTriggers: |
      - on-sync-failed
      - on-sync-succeeded
    service.slack: |
      token: $slack-token
    ....(Skipping unrelated parts)
    trigger.on-sync-failed: |
      - description: Application syncing has failed
        send:
        - app-sync-failed
        when: app.status.operationState.phase in ['Error', 'Failed']
    trigger.on-sync-succeeded: |
      - description: Application syncing has succeeded
        send:
        - app-sync-succeeded
        when: app.status.operationState.phase in ['Succeeded']
  kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/instance: aaa
    name: argocd-notifications-cm
    namespace: argocd
  ```
