### DISCUSSION TITLE
Manage name of local cluster connection using the helm chart

### DISCUSSION THREAD

**Discussion by nallenscott** [argoproj/argo-cd#13219] [Q&A] [answered]
I want to use the argocd helm chart to manage the name of the connection to argocd's host cluster. The default name is "in-cluster". Is it possible to expose that setting as a helm value? If so, I'll go ahead and open a PR on the helm repo.

**Comment by asanka-x** [comment]
> I want to use the argocd helm chart to manage the name of the connection to argocd's host cluster. The default name is "in-cluster". Is is possible to expose that setting as a helm value? If so, I'll go ahead and open a PR on the helm repo.

Any update on this request? I also got a requirement to change the host cluster name from in-cluster to something else during deployment time.

**Comment by nallenscott** [comment]
It doesn't appear to be possible to do programmatically. Where is the best place to expose the host cluster's name attribute so we can get a PR rolling?

**Comment by asanka-x** [comment]
Any update on this? It would be nice if this is configurable via the Helm Chart

**Comment by alexhampu** [comment, marked as answer]
You can create a secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
    name: cluster-custom-name
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: custom-name
    server: https://kubernetes.default.svc
    config: |-
        {
          "tlsClientConfig":{
            "insecure":false
          }
        }
```
