### DISCUSSION TITLE
resourceExclusions for ingresses.v1beta1.extensions

### DISCUSSION THREAD

**Discussion by mortya** [argoproj/argo-cd#13259] [Q&A]
I'm preparing to do some deferred upgrades, from a cluster running openshift 4.8.x / kubernetes 1.21 and argo operator 0.3.0 to newer versions.  Been getting warnings about ingresses.v1beta1.extensions.  I know this is a known issue, as per https://github.com/argoproj/argo-cd/discussions/8121 .  Was wondering if it's possible to do a resourceExclusions at the operator level (AKA resource.exclusions at the configmap level) to prevent this.  But I don't seem to be having much success.  Syntax I'm using below.

Am I messing this up?  Or do I need to be running a newer version?  Or does this feature not help to prevent the above?
```
  resourceExclusions: |
    - apiGroups:
      - "ingress.v1beta1.extensions"
      - "Ingress.v1beta1.extensions"
      - "ingresses.v1beta1.extensions"
      - "Ingresses.v1beta1.extensions"
      - "ingress.v1beta1/extensions"
      - "Ingress.v1beta1/extensions"
      - "ingresses.v1beta1/extensions"
      - "Ingresses.v1beta1/extensions"
      - "v1beta1.extensions"
      - "v1beta1/extensions"
      kinds:
      - "*"
```
