### DISCUSSION TITLE
Multi repo source with hashicorp vault plugin in applicationset

### DISCUSSION THREAD

**Discussion by Shubham1406220** [argoproj/argo-cd#13330] [Q&A]
Argocd version: 
`{
    "Version": "v2.6.6+6d4de2e",
    "BuildDate": "2023-03-16T22:25:45Z",
    "GitCommit": "6d4de2ec5d49fa2c6823f2b7d101607a839be3fa",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}`

My appset configuration file 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
spec:
    generators:
    # matrix 'parent' generator
        - matrix:
            generators:
            - git:
                repoURL: xxxxx
                revision: initial-setup
                directories: 
                    - path: '*'    
            - git:
                repoURL: xxxxxx
                revision: initial-setup
                pathParamPrefix: ""
                files: 
                    - path: '*/values-dev.yaml'                          
    template:
        metadata:
           name: '{{ path }}'
        spec:
            project: "dev"
            sources:
            - repoURL: xxxxxxxxx
              targetRevision: x.x.x
              plugin:
                 name: argocd-vault-plugin
              chart: helm-chart
              helm:
                valueFiles:
                - "$values/{{ path }}/values-dev.yaml"
                - "$values/manifest.yaml"
                - "$values/{{ path }}/properties/properties-dev.yaml"
                - "$values/{{ path }}/secrets/secrets-dev.yaml"
            - repoURL: xxxxxxxx
              targetRevision: initial-setup
              ref: values
            destination:
                server: https://kubernetes.default.svc
                namespace: '{{ application.namespace }}' 
            syncPolicy:
                automated:
                    prune: true
                    selfHeal: true
                    allowEmpty: true
                    retry:
                        limit: 5
                syncOptions:
                - CreateNamespace=true
```

But the vault secrets are not getting overidden. It is not able to use the plugin.
