### DISCUSSION TITLE
Only admin can see helm parameters

### DISCUSSION THREAD

**Discussion by mick1627** [argoproj/argo-cd#13333] [General]
Hello

I have a simple helm application => 

```yaml
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: NS
    name: cluster
  project: myproject
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: ./
    repoURL: >-
      https://XXXXXXXXXXXXXXXXXX.git
    targetRevision: HEAD
```

I have the following rbac rules : 

```yaml
    p, role:myrole, applications, *, myproject/*, allow
    p, role:myrole, clusters, get, *, allow
```

The users in role myrole can do all action on the application but the user does not see the helm parameters : 

![image](https://user-images.githubusercontent.com/36628449/234028137-86387e54-391a-4aa0-8220-ce072746df34.png)

Admin user of argocd can see the helm parameter :

![image](https://user-images.githubusercontent.com/36628449/234028485-0ac8ec29-93c1-4ae0-a121-8e64c8b33ee6.png)

Do I miss some rbac rules to show helm parameter for non admin users ?
