### DISCUSSION TITLE
Argocd goes into an out of sync(requires pruning) state after installing cmp via sidecar with kustomize

### DISCUSSION THREAD

**Discussion by midhunkrishnakv** [argoproj/argo-cd#13386] [General]
**Argocd goes into an out of sync(requires pruning) state after installing cmp via sidecar with kustomize**

I'm running argocd v2.6.7 installed and argocd-vault-plugin v1.14.0 for managing secrets from ibmsecretsmanager.

Earlier i was using configmap to install the plugin, which was working fine.
Since Using avp via configmap is deprecated from argocd v2.4, I decided to adopt the change and move to **argocd-vault-plugin sidecar with kustomize**.

So I went ahead and modified the configmap, removed the avp plugin from the configmap and added the new sidecar with kustomize configuration following this example : https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar.

Pushed the changes to the repository and as soon as argocd triggered a sync, it now shows argocd and all other apps are out of sync and any resources when I try to sync it doesn't update the resources, plus if I see each of the resources diff it shows that is OutOfSync (requires pruning). 

![image](https://user-images.githubusercontent.com/11834342/235369922-4a2b341e-42c5-40b9-89d9-093a77d221c8.png)

```
SyncError
Skipping sync attempt to eca7b13fc565117dd10fb2050bf2e93cacbc1db9: auto-sync will wipe out all resources
```

When trying to see the diff, I can only see the live manifest and it doesn't show the desired manifest, which it will render by fully removing argocd and other apps.

I did a force sync and indeed argocd was removed, I deployed again argocd and all the applications just to find that the problem is still there, the only difference I can find is the avp sidecar with kustomize but not sure what else can be.

1- cmp-plugin.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      init:
        command: [sh, -c, 'echo "Initializing..."']
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
---
```

2- argocd-repo-server.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:

      # Mount SA token for Kubernets auth
      # Note: In 2.4.0 onward, there is a dedicated SA for repo-server (not default)
      # Note: This is not fully supported for Kubernetes < v1.19
      automountServiceAccountToken: true

      # Each of the embedded YAMLs inside cmp-plugin ConfigMap will be mounted into it's respective plugin sidecar
      volumes:
        - configMap:
            name: cmp-plugin
          name: cmp-plugin
        - name: custom-tools
          emptyDir: {}

      # Download tools
      initContainers:
      - name: download-tools
        image: registry.access.redhat.com/ubi8
        env:
          - name: AVP_VERSION
            value: 1.14.0
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      # argocd-vault-plugin with Kustomize
      - name: avp
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.4.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
````
Argocd v2.6.7
argocd-vault-plugin v1.14.0

avp container logs does not show any error

```
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:40Z" level=info msg="find . -name kustomization.yaml" dir=/tmp/_cmp_server/c2ca3891-ee59-4d58-9437-07e53da558a9 execID=a525a
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:40Z" level=info msg="find . -name kustomization.yaml" dir=/tmp/_cmp_server/beaf6b84-fdbf-4ca1-a2e0-7e468339fd6c execID=6c72b
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:40Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=MatchRepository grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-04-30T18:45:40Z" grpc.time_ms=42.634 span.kind=server system=grpc
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:40Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=MatchRepository grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-04-30T18:45:40Z" grpc.time_ms=35.792 span.kind=server system=grpc
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:48Z" level=info msg="Generating manifests with no request-level timeout"
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:48Z" level=info msg="sh -c \"echo \\\"Initializing...\\\"\"" dir=/tmp/_cmp_server/44c1e4ba-f5b0-4e71-84c5-aa0aacbae9eb/deployments/test-argocd-vault-4r/us-south/overlays/argo-cd execID=7a893
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:48Z" level=info msg="sh -c \"kustomize build . | argocd-vault-plugin generate -\"" dir=/tmp/_cmp_server/44c1e4ba-f5b0-4e71-84c5-aa0aacbae9eb/deployments/test-argocd-vault-4r/us-south/overlays/argo-cd execID=31851
argocd-repo-server-5f9978cf8f-h8c6x avp time="2023-04-30T18:45:49Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=GetParametersAnnouncement grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-04-30T18:45:40Z" grpc.time_ms=8714.546 span.kind=server system=grpc
```

Any help is much appreciated!
