### DISCUSSION TITLE
Expected behavior when multiple custom health checks match a resource

### DISCUSSION THREAD

**Discussion by yhrn** [argoproj/argo-cd#13449] [Q&A]
Like the title says. Using the examples from the [official documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks), if you have both of these health checks:

```yaml
  resource.customizations: |
    "*.aws.crossplane.io/*":
      health.lua: | 
        ...
  resource.customizations: |
    ec2.aws.crossplane.io/*:
      health.lua: |
        ...
```

Which one would be applied to a resource with the API group 'ec2.aws.crossplane.io'? The first because it's first, the second because it's more specific, or something else? And what if it's also matching some built in health check?
