### DISCUSSION TITLE
How to deploy k8s resources + ArgoCD Applications to multiple clusters from central ArgoCD

### DISCUSSION THREAD

**Discussion by VladButacu** [argoproj/argo-cd#13448] [Q&A]
## Hello everyone!
I'm in dire need of help figuring out what am I doing wrong with the following setup:

I have a git repository with the following structure

**/management/**<br>
**----argocd/**<br>
--------management.yaml<br>
<details>
  <Summary>management.yaml</Summary>

  ```yaml
  ---
  apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: management-cluster
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec:
    description: ""
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  ---
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: management-apps
    namespace: argocd
  spec:
    destination:
      namespace: ''
      server: 'https://kubernetes.default.svc'
    source:
      repoURL: https://this-git-repo.git
      targetRevision: HEAD
      path: management
      directory:
        recurse: true
    project: management-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  ```
</details>

--------sandbox.yaml<br>
<details>
  <Summary>sandbox.yaml</Summary>

  ```yaml
  ---
  apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
  metadata:
    name: sandbox-cluster
    namespace: argocd
  spec:
    refreshInterval: 1h
    secretStoreRef:
      name: external-secrets
      kind: ClusterSecretStore
    target:
      name: sandbox-kubeflow-cluster
      creationPolicy: Owner
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: cluster
        type: Opaque
    dataFrom:
    - extract:
        key: eks/argocd/sandbox-cluster
  ---
  apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: sandbox-cluster
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec:
    description: Contains applications that are deployed in sandbox cluster
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      name: sandbox-cluster
      server: sandbox.cluster.fqdn
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  ---
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: sandbox-apps
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: ''
      server: sandbox.cluster.fqdn
    source:
      repoURL: https://this-git-repo.git
      targetRevision: HEAD
      path: sandbox
      directory:
        recurse: true
    project: sandbox-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  ```
</details>

**----kube-system/**<br>
--------cluster-secret-store.yaml<br>
--------nfs-provisioner.yaml<br>
<details>
  <Summary>nfs-provisioner.yaml</Summary>

  ```yaml
  ---
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: nfs-client-provisioner
    namespace: argocd
  spec:
    project: management-cluster
    destination:
      server: https://kubernetes.default.svc
      namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    source:
      repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      targetRevision: 4.0.16
      helm:
        values: |
          fullnameOverride: nfs-client-provisioner
          nfs:
            server: some.nfs.ip
            path: /
          storageClass:
            defaultClass: true
            archiveOnDelete: false
            onDelete: retain
            pathPattern: "${.PVC.namespace}/${.PVC.name}"
            accessModes: ReadWriteMany
  ```
</details>

--------nginx-ingress-controller.yaml<br>
**/sandbox/**<br>
**----kube-system/**<br>
--------argocd-credentials.yaml<br>
<details>
  <Summary>argocd-credentials.yaml</Summary>

  ```yaml
  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: argocd-manager
    namespace: kube-system
    labels:
      argocd.argoproj.io/instance: sandbox-cluster
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: argocd-manager-clusterrole
    labels:
      argocd.argoproj.io/instance: sandbox-cluster
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: argocd-manager-clusterrolebinding
    labels:
      argocd.argoproj.io/instance: sandbox-cluster
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: argocd-manager-clusterrole
  subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system

  ```
</details>
--------nfs-provisioner.yaml<br>
<details>
  <Summary>nfs-provisioner.yaml</Summary>

  ```yaml
  ---
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: nfs-client-provisioner-sandbox
    namespace: argocd
  spec:
    project: sandbox-cluster
    destination:
      server: sandbox.cluster.fqdn
      namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    source:
      repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      targetRevision: 4.0.16
      helm:
        values: |
          fullnameOverride: nfs-client-provisioner
          nfs:
            server: nfs.server.ip
            path: /
          storageClass:
            defaultClass: true
            archiveOnDelete: false
            onDelete: retain
            pathPattern: "${.PVC.namespace}/${.PVC.name}"
            accessModes: ReadWriteMany
  ```

</details>
<br>

The sandbox cluster is correctly recognized by the argocd instance

K8s resources like the ones in `argocd-credentials.yaml` are also parsed correctly

The problem is that the `nfs-client-provisioner` application is not created in the sandbox cluster. It is found and it appears as `Application` under the `sandbox-apps` Application but it throws a warning saying that it's missing.

I'm sure I'm missing something but I can't figure out what. Any help would be greatly appreciated.
