### DISCUSSION TITLE
Upgrade from v2.5.2 to v2.5.3 causes some applications to fail to sync.

### DISCUSSION THREAD

**Discussion by akleyer** [argoproj/argo-cd#13511] [Q&A]
Hey there! So, I've been trying to debug this issue I'm having with my ArgoCD instance. I recently upgraded it from version 2.5.2 to 2.5.3 and it's been causing some problems. In 2.5.2 everything was working fine, but now any apps that use a private helm repository fail to sync, and I keep getting this error message that says: `helm dependency build failed exit status 1: Error: could not download oci://<registry>/<path_to_chart>: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden.`

To give you some context, my ArgoCD is running on a GKE cluster, and I'm pulling helm charts from an OCI registry in Google Artifact Registry. To authenticate, I have a GCP service account with permissions to pull from the registry. I downloaded the JSON key for it and created a secret in my cluster with the JSON. Then, I added the secret to the argocd-repo-server deployment and used it to run a `helm registry login` to the location of my helm charts in Google Artifact Registry.

My application looks something like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <name>
spec:
  destination:
    server: <server>
    namespace: <namespace>
  project: <project>
  source:
    path: <path to chart>
    repoURL: git@github.com:<gitops_repo>.git
    targetRevision: <ref>
    helm:
      valueFiles:
      - file1.yaml
      - file2.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
```

And this is what my Chart looks like in the GitOps repo:

```
apiVersion: v2
name: <name>
version: <chart version>
dependencies:
  - name: <chart name>
    version: <version>
    repository: oci://<registry>/<path_to_chart>

```
The weird thing is that when I manually exec into the argocd-repo-server pods and do a helm pull on the helm chart, it works just fine. So, I'm really stumped.

Anyway, this all worked fine in version 2.5.2 and earlier, so I don't know what's changed in version 2.5.3. If anyone has any ideas, I'd really appreciate the help!
