### DISCUSSION TITLE
Can i use ApplicationSet if have mix helm charts and kustomize?

### DISCUSSION THREAD

**Discussion by sipao** [argoproj/argo-cd#13541] [Q&A]
The following structure is assumed.
There is app-A, which is configured with kustomize, and app-B, which is configured with helm charts.
```
.
├── application-set.yaml
└── apps
    ├── app-A
    │   ├── base
    │   └── overlays
    │       ├── dev
    │       └── prod
    └── app-B
        └── Chart.yaml
```

**Comment by itewk** [comment]
same question.

**Comment by crenshaw-dev** [comment]
Not yet. We need to improve how ApplicationSet does templating first. https://github.com/argoproj/argo-cd/issues/9177

**Comment by mihaigalos** [comment]
Hi @crenshaw-dev, since the issue has been closed, is this now possible?
I'm trying to consume a component.yaml which will indicate a repo containing either values.yaml or kustomization.yaml files to overlay using ArgoCD (2.9.3, latest).

Something like (not yet working):
`bootstrap.yaml`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "dev-appset"
  namespace: myproject-argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      requeueAfterSeconds: 300
      repoURL: 'https://do.main/orga/repo.git'
      revision: HEAD
      files:
      - path: 'core/*/component.yaml'
  template:
    metadata:
      name: '{{.name}}'  
    spec:
      project: 'myproject'
      sources:
        targetRevision: '{{.targetRevision}}'
        repoURL: '{{.repoURL}}'
        path: 'deployment'
        - repoURL: 'https://do.main/orga/repo.git' # For Kustomize
          targetRevision: HEAD
          ref: values
        - repoURL: '{{.repoURL}}' # For Helm
          targetRevision: '{{.targetRevision}}'
          path: deployment
          helm:
            valueFiles:
            - $values/all/accounts/account1.yaml
            - $values/core/{{.name}}/values.yaml
            - $values/core/{{.name}}/stages/account1-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
```
`component.yaml`:
```yaml
name: myproject-dex
namespace: myproject-dex
targetRevision: 2023.50.1
repoURL: https://do.main/orga/myproject-dex-manifest.git
```
