### DISCUSSION TITLE
How to pass the image version in the notification

### DISCUSSION THREAD

**Discussion by radimpaseka** [argoproj/argo-cd#13615] [Q&A] [answered]
Hi,
I'm trying to pass the image version in the notification when new deployment happen, I cannot find any doc what is possible. In the samples I see .app.metadata. parameter, .app.spec.source parameters, etc. is there any documentation what parameters are available?
How can I pass the parameter with image version which has been deployed?

Thx

**Comment by mubarak-j** [comment]
Have you tried fetching that value from the application status field, i.e. `.app.status.summary.images`?

with something like this:

```yaml
template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      {{if eq .serviceType “slack”}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
    slack:
      attachments: |
        [{
          “title”: “{{.app.metadata.name}} {{ $image := first .app.status.summary.images }}{{ $list := splitList “:” $image  }}{{ index $list 1 }}“,
```
