### DISCUSSION TITLE
Can I install multiple ArgoCD on one Kubernetes cluster?

### DISCUSSION THREAD

**Discussion by YevheniiPokhvalii** [argoproj/argo-cd#13618] [General]
I'm trying to install the second ArgoCD instance in another namespace on one Kubernetes cluster and receive the following error:

```
helm install argocd argo/argo-cd -n test-argocd -f values.yaml
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "applications.argoproj.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "test-argocd": current value is "argocd"
```

It is actually possible?

**Comment by jaideepr97** [comment]
hi @YevheniiPokhvalii 
Yes, you can install multiple argo-cd instances in one cluster, though in your case it sounds like you might have to update your manifests to have the correct namespace value for your 2nd argo-cd instance 

There is also a namespace scoped installation mode where your argo-cd instance will only manage a single namespace (if you're looking for multi tenancy on your cluster this is a good option) 
https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#non-high-availability

HTH

**Reply by YevheniiPokhvalii** [reply]
> hi @YevheniiPokhvalii Yes, you can install multiple argo-cd instances in one cluster, though in your case it sounds like you might have to update your manifests to have the correct namespace value for your 2nd argo-cd instance
> 
> There is also a namespace scoped installation mode where your argo-cd instance will only manage a single namespace (if you're looking for multi tenancy on your cluster this is a good option) https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#non-high-availability
> 
> HTH

Thanks. Could you let me know where the namespace might have been indicated wrong?

It seems that the error comes from the helm labels created by the previous installation. In the `argocdextensions.argoproj.io` `CustomResourceDefinition`:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argocdextensions.argoproj.io
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocdextensions.argoproj.io
    app.kubernetes.io/part-of: argocd

```

And in the `argocd-application-controller` `ClusterRole`:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.33.1
```

I manged to install the second instance with (disabling CRDs and ClusterRoles):

```
helm install argocd argo/argo-cd -n yp-test-argocd -f values.yaml --version 5.33.1 --set crds.install=false --set createClusterRoles=false
```

Also had to create a Cluster Role Binding manually because of that.

It seems that it was not a namespace issue but a helm label issue. Could you explain why this issue occured?
