### DISCUSSION TITLE
Ignore differences @ ConfigMap keeps syncing the object

### DISCUSSION THREAD

**Discussion by mike-code** [argoproj/argo-cd#13706] [Q&A]
### Question

I have a few `ConfigMap`s that are updated by one of the k8s jobs and I want ArgoCD to propagate them when the application is deployed but **do not sync them further** if they change in the meantime.

I figured I can use ignore differences to achieve that, but it won't do the job.

### Yamls

Here's my application  manifest
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awesome-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: outer-rim
  sources:
  - repoURL: 'https://......'
    targetRevision: 0.1.0
    chart: awesome-app
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: ConfigMap
      group: '*'
```

Config Map that ArgoCD deploys

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: awesome-config
data:
  FOO: 0
  BAR: 1
```

ConfigMap that some k8s job crafted

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: awesome-config
data:
  FOO: 0
  BAR: 42
```

### Steps

Now if I run
```
cat updated-config-map.yaml | kubectl replace -f-
```

the BAR value will be reverted back to `1` even though I wanted it to stay `42`.

### Bonus question

Can I achieve it through ConfigMap annotations rather than `ignoreDifferences` property in the `Application`'s yaml?

**Comment by jaideepr97** [comment]
`ignoreidfferences` is meant to be used when ignoring specifc fileds on a given resource

you may be looking for resource exclusions https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion

**Reply by mike-code** [reply]
but then will those resources be replaced if they app is re-deployed and the "original" configmap has changed, say, it has a new annotation that should be propagated?

**Reply by mike-code** [reply]
To rephrase: I don't mean the resource to be excluded, because I want it to be included when I call `/sync` with `replace+prune+force` options (ie. restart the app). If I use exclusion, the resource will be left intact which isn't my intention.

Can I somehow achieve the OP goal so that Argo doesn't sync the `ConfigMap` keys (ie. `data` field of a `ConfigMap`) but still keep ownership over the `ConfigMap` and thus prune it if needed?

**Comment by ravi-dd** [comment]
Did you find a solution for this @mike-code

**Comment by Gnarfoz** [comment]
I'm also looking for a way to ignore differences on ConfigMaps. ArgoCD just seems to ignore my `IgnoreDiferences` settings entirely.
Even a simple `kind: ConfigMap` does nothing.

**Comment by nvtkaszpir** [comment]
you can ignore specific key in configMap data section, for example if you have:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    ...
    redated
    ...
  NodeHosts: |
    192.168.1.10 some-host-1
    192.168.1.11 some-host-2
```


then you can ignore `NodeHosts` value changes via jq path expression as `.data.NodeHosts`:
```yaml
  ignoreDifferences:
    - group: '*'
      kind: ConfigMap
      jqPathExpressions:
        - .data.NodeHosts
```
