### DISCUSSION TITLE
Sync status shows "Pruned" but the resources are still present on k8s

### DISCUSSION THREAD

**Discussion by mike-code** [argoproj/argo-cd#13714] [Q&A] [answered]
### Question

I have an application that is a "parent" app which watches for child apps in a specific git directory (see yamls below). The problem is that once I remove one of the child apps (ie. I remove child's yaml from the git), once Argo refreshes, it removes the child app from the UI, it shows sync status "Pruned" but the resources **are not removed from k8s cluster**.

### Yamls

Parent application yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-deployments
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: some-random-namespace
  source:
    repoURL: 'https://...'
    targetRevision: master
    path: my-awesome/applications
    directory:
      include: '*-app.yaml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
```

Child application yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-test
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argo-app-test
  sources:
  - repoURL: 'https://...'
    targetRevision: 0.1.0
    chart: my-awesome-app
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
```

![image](https://github.com/argoproj/argo-cd/assets/2964642/4420db59-d3fc-4fb1-94cf-74be7cd1287b)

**Comment by mubarak-j** [comment, marked as answer]
Have you tried setting the [Deletion Finalizer](https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#about-the-deletion-finalizer)? 
e.g for child app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
```

since you're using the App of Apps pattern I think you will need to add the above finalizer.
