### DISCUSSION TITLE
ArgoCD Image Updater Not Updating New Images on Docker Hub

### DISCUSSION THREAD

**Discussion by Rachiid007** [argoproj/argo-cd#13738] [Q&A] [answered]
Hello Argo CD community,

I'm currently working on a CI/CD pipeline and I'm using ArgoCD along with a Helm chart and ArgoCD Image Updater to update my application's image. However, I've encountered an issue: my application's new images on Docker Hub are not getting updated.

Here is the Helm chart I'm using: https://rachiid007.github.io/dtt-chart

The manifest I've used for Argo CD is as follows:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dtt-isj
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rachiid007/dtt_front:0.x
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Rachiid007/dtt-chart.git"
    path: charts
    targetRevision: HEAD
    helm:
      parameters:
        - name: url
          value: isj.taaltoolbox.be
        - name: namespace.name
          value: isj
        - name: frontend.deployment.replicas
          value: "2"
        - name: frontend.deployment.image.repository
          value: rachiid007/dtt_front
        - name: frontend.deployment.image.tag
          value: 0.0.1
  destination:
    server: "https://kubernetes.default.svc/"
    namespace: isj
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
```

After applying this file using the command kubectl apply -f filename.yaml, a new file charts/.argocd-source-dtt-isj.yaml was created in my [GitHub repository](https://github.com/Rachiid007/dtt-chart). This file contains the following:
```yaml
helm:
  parameters:
  - name: url
    value: isj.taaltoolbox.be
    forcestring: false
  - name: namespace.name
    value: isj
    forcestring: false
  - name: frontend.deployment.replicas
    value: "2"
    forcestring: false
  - name: frontend.deployment.image.repository
    value: rachiid007/dtt_front
    forcestring: false
  - name: frontend.deployment.image.tag
    value: 0.0.1
    forcestring: false
  - name: image.name
    value: rachiid007/dtt_front
    forcestring: true
  - name: image.tag
    value: 0.0.3
    forcestring: true
```

Meanwhile, I've created two new tags for my image: `0.0.2` and `0.0.3`. Despite this, the updates are not reflected in my application.

Has anyone experienced this issue before, or does anyone have insights on why the new Docker Hub images are not updating as expected?

I'd appreciate any assistance with this problem. Thanks in advance!
