### DISCUSSION TITLE
argo-cd oidc setup with Okta is not working

### DISCUSSION THREAD

**Discussion by man-st** [argoproj/argo-cd#13826] [Q&A]
Hi all,

Have an issue with argo-cd oidc setup with Okta. 
Getting the following error when trying to sign in to argo-cd with okta:
"Invalid redirect URL: the protocol and host (including port) must match and the path must be within allowed URLs if provided"

argocd-cm.yaml configuration fragment:

apiVersion: v1
data:
  oidc.config: |
    name: Okta
    issuer: https://demo-ts-onboarding.okta.com/oauth2/aus5ld**********
    clientID: 0oa5ld8*********
    clientSecret: Zd-pFfK_5s********************
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
    redirectURI: [http://localhost:8080", "https://localhost:8080", "https://localhost:8080/auth/callback", "http://localhost:8080/applications", "https://localhost:8080/applications", "http://localhost:8080/auth/callback"]
    secureCookie: false
kind: ConfigMap

Anyone have any ideas? 

Thanks

**Comment by umarov** [comment]
I think you need to set the `url` field inside `oidc.config` to be the URL of your argo

**Reply by man-st** [reply]
Got it right here but it still keeps giving me the below error as soon as I hit the sign in with okta button on the argocd login page.
<img width="673" alt="Screenshot 2023-06-05 at 17 10 30" src="https://github.com/argoproj/argo-cd/assets/135021319/cdaaaf0f-a50a-4808-b492-72b2d5c8ee4a">

<img width="1011" alt="Screenshot 2023-06-05 at 17 15 43" src="https://github.com/argoproj/argo-cd/assets/135021319/b2c04d69-f916-4af8-b60f-4dab3078b141">

**Reply by umarov** [reply]
Where did you set the `url`? I am not talking about the `redirectURL`

**Reply by luwangVMW** [reply]
I hit the same issue. I am using helm chart 7.8.8.  
If I remove the content of "?return_url=https%3A%2F%2F192.168.130.5%2Fapplications", then the issue is gone. But it does not make sense to manually remove it everytime. why does the url with return_url hit the failure? return_url is different usage of rediect_url.
![Screenshot 2025-03-26 at 17 05 55](https://github.com/user-attachments/assets/eccf6173-108b-4a41-8a47-6d34ab7fdd40)

**Comment by EvaBender** [comment]
As soon as I set the url to be the argocd URL under the same level as oidc.config and removed the 'redirectURL' everything worked properly for me.

**Comment by onkar6699** [comment]
@man-st @umarov 
what you set under 
data:|
url: ?? can you please tell me?
what redirect URI added?

**Reply by umarov** [reply]
I decided not to use Okta and just use Github. This is what I have:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: "https://argocd.yourdomain.com"
  admin.enabled: "false"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github:oidc-client-id
          clientSecret: $github:oidc-client-secret
          orgs:
          - name: YourOrg
```
