### DISCUSSION TITLE
Migration in Argo Hooks

### DISCUSSION THREAD

**Discussion by JoaoPedroAssis** [argoproj/argo-cd#13830] [Q&A]
Hello everyone!

I wanted to share my positive experience with ArgoCD, which we recently adopted at my company. It has proven to be an excellent tool for managing our deployments. We have a Rails monolith application that requires a migration every time we build our app. Previously, this process was handled entirely through GitHub Actions, following this flow:

1. Build the image
2. Launch a job and deployment using that image
3. The deployment has an initContainer that waits for database migrations
4. The job performs the necessary database migrations
5. New deployment is created

This workflow worked well, but after installing ArgoCD, the jobs were marked as "OutOfSync" due to the `ttlSecondsAfterFinish` field. To address this, I researched ArgoCD hooks and started using a `PreSync` hook to run the migrations. However, I encountered an issue where the migration required an updated image version.

To illustrate, here's an example YAML configuration for the job:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Values.jobs.namespace }}
  generateName: "{{ .Values.jobs.name }}-"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        name: {{ .Values.jobs.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.jobs.pullSecrets }}
      containers:
      - name: {{ .Values.jobs.name }}
        image: "{{ .Values.images.repository }}:{{ .Values.images.tags.app }}"
....
```

Upon deploying this configuration, I noticed that the image value does not change when the `Values.yml` file is updated. As a result, all hooks run with the same image. My question is: How can I ensure that migrations are executed using the updated image tag?

Thank you!
