### DISCUSSION TITLE
Pulling Helm Chart from one Public Repository and Passing Manifest Values from a Private Repository

### DISCUSSION THREAD

**Discussion by owaisimran2411** [argoproj/argo-cd#13858] [Q&A]
Hello everyone,

Current ArgoCD Server Version: **v2.5.2+148d8da**

We are currently having a use case where we want to create an application on **ArgoCD** by using `helm chart` directly available on the `public repository` and pass in the values file from our `private github repository.`

**For Example:** we want to deploy **Prometheus** on our Kubernetes Cluster running on EKS as an ArgoCD Application, for the base chart of Prometheus, we want to pull that chart directly from Prometheus Helm Repo, and pass in the manifest values from our private hosted github repo

Below is a sample application manifest file:

``` helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-name
  namespace: argocd-namespace

spec:
  destination:
    namespace: destination-server-namespace
    server: destination-server
  project: project-name
  source:
    chart: "chart-name-to-pull-from-public-repo"
    repoURL: "public-helm-repo-url-of-application"
    targetRevision: "chart-version-of-application"
    helm:
      valueFiles:
        - https://github.com/privateGithubRepoName/pathToManifestFile.yaml
 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

After applying the above manifest, our application is being created but on syncing the application it shows the error 
```
failed exit status 1: Error: failed to fetch https://github.com/privateGithubRepoName/pathToManifestFile.yaml : 404 Not Found
```

Although the Repo is a private Github Repository, but we have already authenticated that Github Repo using `Github Personal Access Token` via **ArgoCD Credential Template**

I have also tried using another manifest which I found on some github discussion, but this does not seem to work as well.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dit
spec:
  project: default
  source:
    repoURL: https://github.com/pathToPrivateGitRepo.git
    targetRevision: HEAD
    path: ""
    helm:
      repoURL: "public-helm-repo-url-of-application"
      chart:  "chart-name-to-pull-from-public-repo"
      chartVersion: "chart-version-of-application"
      valueFiles:
        -  pathToManifestFileInPrivateRepo # e.g. /path/values.yaml
```

Is there any mistake I am making in configuration or is there any workaround anyone can refer is highly appreciated

**THANKS IN ADVANCE**
