### DISCUSSION TITLE
Sending notifications to multiple instances of the same service.

### DISCUSSION THREAD

**Discussion by ernestre** [argoproj/argo-cd#13866] [Q&A]
Hello, 

Is it possible to send notifications to multiple instances of the same service. i.e grafana? We have a case where we have multiple grafana instances deployed and we want to send notifications to all of them. However, I can't anything in the docs on how to achieve this.

For example instead of this:
```yaml
//...
    service.grafana: |
      apiUrl: ${argocd_grafana_url}
      apiKey: ${argocd_grafana_key}
```
I want something similar to this:

```yaml
  notifiers:
    service.grafana-one: |
      apiUrl: ${argocd_grafana_url_one}
      apiKey: ${argocd_grafana_key_one}
    service.grafana-two: |
      apiUrl: ${argocd_grafana_url_two}
      apiKey: ${argocd_grafana_key_two}
    service.grafana-...: |
      apiUrl: ${argocd_grafana_url_...}
      apiKey: ${argocd_grafana_key_...}
```
