### DISCUSSION TITLE
ConfigManagementPlugin (Vault Plugin) - Sidecar discovery not working as expected

### DISCUSSION THREAD

**Discussion by carslen** [argoproj/argo-cd#13870] [Q&A]
Hi all,

> tl;dr: I am unable to configure autodiscovery properly to trigger expected repo-server sidcar container for manifest generation.

I do really struggle with the CMP sidecare discovery approach. Coming from ArgoCD 2.4 configMap setup, I've migrated to the sidecare implementation now running on ArgoCD 2.6.8.

There are a couple of CMP plugins configured (all related to argocd-vault-plugin):
- avp
- avp-helm-args
- avp-helm-values
- avp-helm-kustomize
- avp-kustomize

My setup can be found here (it's on purpose linked to a debug branch): 
- [vault-plugin-cm.yaml](https://github.com/catenax-ng/k8s-cluster-stack/blob/fix/avp_discovery_settings_debug/apps/argocd/overlays/core/configmap/vault-plugin-cm.yaml)
- [argo-repo-server-sidecars.yaml](https://github.com/catenax-ng/k8s-cluster-stack/blob/fix/avp_discovery_settings_debug/apps/argocd/base/vault-plugin/argo-repo-server-sidecars.yaml)

For auto discovery of sidecare container I use a `discovery.find.command` section like this:

```yaml
discover:
  find:
    command:
      - sh
      - "-c"
      - |
        if [ -n "$(find $ARGOCD_APP_SOURCE_PATH -name 'kustomization.yaml')" ] && \
          [ -n "$(find $ARGOCD_APP_SOURCE_PATH -name '*.yaml' | xargs -I {} grep '<path\|avp\.kubernetes\.io' {})" ] && \
          [ -z "$(find $ARGOCD_APP_SOURCE_PATH -name 'Chart.yaml')" ];
        then
          echo "kustomization"
        fi
```
Due to the fact, that `dicover.find.command` is executed on repositories root level, I use `$ARGOCD_APP_SOURCE_PATH` as I want to decide upon the content of the source path which sidecare should be triggered.

I've added som debug output to the `generate.command` to get an idea which sidecare has been triggered (echoing some content to file `itwasme*` file in sidecar container).

I can't build a reliable discovery with my current state, it seems argocd-repo-server is managing the requests most of the time instead of some of the sidecar containers. Using direct plugin addressing in ArgoCD application manifest is working and the plugin is executing as expected.

Can one shed some light here?

**Comment by crenshaw-dev** [comment]
> I can't build a reliable discovery with my current state

Can you describe exactly how the above discovery is failing? At a glance, it looks like it should work fine.

**Reply by carslen** [reply]
Uh, that's a hard question! When deploying a ArgoCD App where AVP should replace placeholders using any of the sidecars, the result is having the placeholder in the deployed resource instead of the secret.

Expectation:

```yaml
...
kind: Secret
data:
  foo: RGlkIHlvdSBleHBlY3QgYSByZWFsIHNlY3JldD8gU29ycnkgOi0pCg==
```

Result:
```yaml
...
kind: Secret
data:
  foo: <avp_placeholder>
```
I've checked the logs of the sidecar containers but I coudn't get any value out of it. And logs of repo-server are a bit overwelming and hard to unterstand for me. Thats the reason why I added this `echo $ARGOCD_APP_SOURCE_PATH > /home/argocd/itwasme-${ARGOCD_APP_NAME}-$(date +%F-%T)` stuff to the `generate.command` section, to get an idea if the sidecare has been triggered, or not.

When the AVP placeholder instead of the the secret is shown in the deployed resource, then there is no `itwasme-...` file in the expected sidecar container. This is why I guess that the repo-server itself must have deployed and generated the manifests instead of one of the sidecars.

If I try to apply this [simple kustomize](https://github.com/carslen/avp-demo/tree/test/test), then I would expect that the sidecar container `avp-kustomize` should hande the manifest generation, but it doesn't and no `itwasme-...` file has been generated:

```yaml
project: default
source:
  repoURL: 'https://github.com/carslen/avp-demo/'
  path: test
  targetRevision: test
destination:
  server: 'https://kubernetes.default.svc'
  namespace: avp-test-kustomize
syncPolicy:
  syncOptions:
    - CreateNamespace=true

```
BTW: This app is healthy but out of sync after applying (not yet synced) instead of missing? I'd have expected missing instead?!

```shell
(cx-core:argocd)
[~/projects/cat-x]$ k -n avp-test-kustomize get secrets avp-demo-kustomize-secret1 -o jsonpath="{ .data.foo }" | base64 -d
<path:product-team-example/data/hello#foo>%
(cx-core:argocd)
[~/projects/cat-x]$ k exec pods/argocd-repo-server-k1h23k12-wzfvj --container avp-kustomize -- ls -l
total 1000
drwxr-xr-x 4 root   root     4096 Jun  1 08:24 cmp-server
-rw-r--r-- 1 argocd argocd     13 Jun  1 12:33 itwasme-beta-config-2023-06-01-12:33:04
-rw-r--r-- 1 argocd argocd     18 Jun  1 13:46 itwasme-core-config-2023-06-01-13:46:39
-rw-r--r-- 1 argocd argocd     12 Jun  1 12:33 itwasme-dev-config-2023-06-01-12:33:05
-rw-r--r-- 1 argocd argocd     39 Jun  1 13:51 itwasme-devsecops-testing-argo-2023-06-01-13:51:06
-rw-r--r-- 1 argocd argocd     12 Jun  1 12:33 itwasme-hotel-budapest-config-2023-06-01-12:33:05
-rw-r--r-- 1 argocd argocd     17 Jun  1 12:33 itwasme-pre-prod-config-2023-06-01-12:33:05
-rw-r--r-- 1 argocd argocd     28 Jun  1 14:06 itwasme-stable-argo-2023-06-01-14:06:05
-rw-r--r-- 1 argocd argocd     15 Jun  1 12:32 itwasme-stable-config-2023-06-01-12:32:45
```

The strange thing now is, that sometimes the sidecar gets triggered (the apps are indeed pure kustomize apps), which confuses me even more. 

Other sidecars (avp-helm-args) works with my [example](https://github.com/carslen/avp-demo/blob/test/apps/argo-helm4.yaml), but not with a [productive one](https://github.com/catenax-ng/k8s-cluster-stack/tree/main/apps/certmanager) which is expected to be handled by sidecar avp-helm-values.

You see, I'm totally confused by ArgoCDs CMP :-)
