### DISCUSSION TITLE
Is there a way to use ArgoCD to run Jobs once and only once?

### DISCUSSION THREAD

**Discussion by DevAtHeart** [argoproj/argo-cd#13888] [Q&A] [answered]
Hey guys, loving Argo!

However i am currently stumped. Is there a way to run a job once and only once EVER ?

Let's say I have to migrate some files from volume A to volume B once. I wrote a Job that does that and I would love to integrate it into my GitOps flow. However, it seems Jobs are applied every sync. 

I tried to make it a resource hook but it's also run more than once.

```yaml
metadata:
  name: migrate-volumes
#  annotations:
#    argocd.argoproj.io/hook: PostSync
#    argocd.argoproj.io/hook-delete-policy: HookFailed
```

Any suggestions? I could just apply them with kubectl outside of Argo but i use kustomize which makes it a real chore to reference other resources in the job..

**Comment by DevAtHeart** [comment, marked as answer]
My workaround for now:

I create a suspended CronJob instead of a Job.

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: <cronjob-name>
spec:
  schedule: '0 0 1 1 *'
  suspend: true
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
          # ...
          restartPolicy: Never
```

To get my available jobs (very simplified):

`kubectl get cronjobs | grep True` 

Then I execute:

`kubectl create job -n <namespace> --from cronjob/<cronjob-name> <job-name>`

I am still open to suggestions however..
