### DISCUSSION TITLE
Failed to download dependency OCI charts from Harbor

### DISCUSSION THREAD

**Discussion by Mais316** [argoproj/argo-cd#13898] [Q&A]
Please help

We have argocd version 2.5.6, one of our customers deploying app, app points to helm chart in a git repository but it as a dependency oci chart in harbor

Main application Chart.yaml
```yaml
apiVersion: v2
name: test-private
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: test.common
  version: 1.0.0
  repository: "oci://harbor.<domain>.com/test-priv"
 ```
  
Created secrets like

```yaml
apiVersion: v1
stringData:
  enableOCI: "true"
  name: harbor-registry
  type: helm
  url: harbor.<domain>.com/test-priv
  password: <hidden>
  username:  <hidden>
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: harbor-registry
  namespace: argocd
type: Opaque
```

then used secret like below

```yaml
apiVersion: v1
stringData:
  enableOCI: "true"
  name: harbor-registry
  type: helm
  url: harbor.<domain>.com
  password: <hidden>
  username:  <hidden>
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: harbor-registry
  namespace: argocd
type: Opaque

```

Nothing is working, please advise

error

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download oci://harbor.domain.com/test-priv/test.common: pulling from host harbor.domain.com failed with status code [manifests 1.0.0]: 401 Unauthorized
```

Using manual commands works 
``` sh
$helm registry login -u <username> harbor.domain.com/test-priv/
Password:
Login Succeeded

$ helm pull oci://harbor.domain.com/test-priv/test.common --version 1.0.0
```

To Add 

If I go to ArgoCD repositories I see it connected and green

**Comment by Mais316** [comment]
More testing, if the OCI chart is not a depended chart, ArgoCD will be able to deploy the app, problem is it doesnt work if the chart is in dependencies

**Comment by Mais316** [comment]
Issue resolved after adding the project name to the secret

```yaml
apiVersion: v1
stringData:
  enableOCI: "true"
  name: harbor-oci-registry
  type: helm
  url: "harbor.domain.com/argocd-test-priv"
  password: xxxxxxxxxxxxxxxx
  username: xxxxxxxxxx
  project: testproject
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: harbor-oci-registry
  namespace: argocd
type: Opaque

```
