### DISCUSSION TITLE
RBAC policy not working whem using DEX OIDC and gitlab connector.

### DISCUSSION THREAD

**Discussion by thiaggom** [argoproj/argo-cd#13955] [General]
Hello, 

I have my argocd (v2.6.9+3f1e7d4) instance configured with sso using dex with oidc connector (gitlab). For some reason I can attache a policy role direct to a user.  According to the docs gitlab users a internal id as userID. Whoever even adding the custom mapping for username and userid, my user don't have the role I've defined. 

However when I configure this role to point to a gitlab group it works.

my dex.config:
```
- type: oidc
    # Required field for connector id.
    id: oidc
    # Required field for connector name.
    name: GitLab
    config:
      issuer: https://gitlab.com
      clientID: <<client_id>>
      clientSecret: <<client_secreet>>
      getUserInfo: true
      scopes:
        - openid
        - profile
        - email
      userNameKey: email
      userIDKey: email
      
      claimMapping:
        groups: groups_direct

```
my policy.csv:
```
g, my-gitlab-group, role:admin ##working
g, user@mydomain.com, role:admin ##not-working

```
So after my target login it gets my default role (policy.default=role:readonly) instead of admin.

Any idea what I'm missing ?
