### DISCUSSION TITLE
What kind of diff strategy is being used in the sync?

### DISCUSSION THREAD

**Discussion by denysvitali** [argoproj/argo-cd#13977] [Q&A]
As per title, I'm trying to understand how the sync mechanism really works.

I've never had problems until today where I noticed that removing a container from a deployment (`.spec.template.spec.containers | length` going from 2 to 1) caused the deployment always appear in sync with the desired manifest—even though the twos were clearly different.

Consider the following (simplified) case:

### Current manifest

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # ...
spec:
  replicas: 3
  selector:
    # ...
  template:
    spec:
      containers:
        - name: container-1
           # ...
        - name: container-2
           # ...
```

### Desired Manifest

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # ...
spec:
  replicas: 3
  selector:
    # ...
  template:
    spec:
      containers:
        - name: container-1
           # ...
```

### Resulting manifest

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # ...
spec:
  replicas: 3
  selector:
    # ...
  template:
    spec:
      containers:
        - name: container-1
           # ...
        - name: container-2
           # ...
```

It seems like ArgoCD cannot figure out that the `containers` array has changed, and thus it doesn't update the live manifest. This gets even crazier since changes to stuff like the `image` of the first container gets applied—whilst keeping the `container-2` around!

This gets solved by forcibly replacing the `Deployment` resource, but the OutOfSync behavior is not shown in this case.

Am I going crazy or is there an explanation for this weird behavior?
