### DISCUSSION TITLE
Error when setting up ArgoCD Vault Plugin with Kustomize: "stat /var/run/argocd/argocd-cmp-server: no such file or directory"

### DISCUSSION THREAD

**Discussion by tcherokee** [argoproj/argo-cd#13970] [General]
Hi guys, 

I am hoping someone can help me out with this. Pretty sure I might have done something wrong because I am sure I have searched the whole internet and I couldn't find a duplicate of this problem :(.

I have ArgoCD working perfectly, and I am trying to install the Vault plugin using Kustomize. It continually fails with the following error 

`Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/var/run/argocd/argocd-cmp-server": stat /var/run/argocd/argocd-cmp-server: no such file or directory: unknown`

here are my config files

here is my `argocd-repo-server.yaml` file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:

      # Mount SA token for Kubernets auth
      # Note: In 2.4.0 onward, there is a dedicated SA for repo-server (not default)
      # Note: This is not fully supported for Kubernetes < v1.19
      automountServiceAccountToken: true

      # Each of the embedded YAMLs inside cmp-plugin ConfigMap will be mounted into it's respective plugin sidecar
      volumes:
        - configMap:
            name: cmp-plugin
          name: cmp-plugin
        - name: custom-tools
          emptyDir: {}

      # Download tools
      initContainers:
      - name: download-tools
        image: registry.access.redhat.com/ubi8
        env:
          - name: AVP_VERSION
            value: 1.14.0
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/

        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      # argocd-vault-plugin with Kustomize
      - name: avp-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.7.4
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-kustomize.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
```

here is my `cmp-plugin.yaml` file
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
```

here is my `kustomization.yaml` file
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.7.4

# Note: Versions below 2.4.0 will not always work if trying to use AVP with Helm
# Fixed in https://github.com/argoproj/argo-cd/pull/9319
resources:
  - https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.7.4
  - cmp-plugin.yaml

patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yml
  - argocd-repo-server.yaml

namespace: argocd
```

here is my `argocd-cmd-params-cm-patch.yml` file
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
```

I was initially using ArgoCD 2.4.0 as per the docs but upgraded to 2.7.4 hoping that would solve the problem, however I have been having no luck so far. I've read through the documents and I do not think I have missed anything and I've also been through most of the issues on the ArgoCD and ArgoCD Vault Plugin repos, but haven't found anything that gives an indication of what could be wrong.
