### DISCUSSION TITLE
If the Argo CD CMP traversal matches at the repository root level and no plugin is specified for any Application, the plugin is also applied to an unintended Application.

### DISCUSSION THREAD

**Discussion by mugioka** [argoproj/argo-cd#14068] [Q&A] [answered]
Hi team.
I have a question related to the discovering design for config management plugin .
Directory structure of my repository is like bellow:
```
k8s/
├── helmfile
│   ├── helmfile.yaml
├── plain
│   ├── namespace.yaml
```
Above environment and define the config management plugin and application cr like a bellow:
ConfigManagementPlugin for helmfile.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: helmfile
spec:
  version: v1.0
  generate:
    command: [sh, -c]
    args:
    - helmfile repos;
      helmfile template --skip-deps
  discover:
    find:
      glob: "**/helmfile.yaml"
```
Application CR for helmfile
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmfile
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: k8s/helmfile
    repoURL: xxxx
    targetRevision: xxxx
```
Application CR for kubernetes plain manifests
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plain
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: k8s/plain
    repoURL: xxxx
    targetRevision: xxxx
```

It is working correctly until I upgrade the Argo CD version from v2.7.2 to v2.7.4.
But, after i upgraded to v2.7.4, it is not working, because of helmfile plugin is used even with kubernetes plain manifest folder.
Are these behaviors specifications?
Maybe related pull request: https://github.com/argoproj/argo-cd/commit/b3f0979e71b59a19dcad4a222cfec08f2ccb377b
