### DISCUSSION TITLE
Notifications - how to inform when health degraded application returned to healthy

### DISCUSSION THREAD

**Discussion by luciano-buono** [argoproj/argo-cd#14089] [Q&A]
Hi, I have a need for the following workflow:

An application is deployed succesfully and is `on-sync `and `healthy`.
Then, for X reason, a pod enters into a `CrashLoopBackoff` and the Application health goes into `Progressing` for 10mins.
As the error persist, the health state goes into `degraded`.

Sometimes the error could be a commit with an incorrent image tag so kubernetes can't find the image to pull.
So, in the next commit this is fixed and the application health goes into `healthy`.

---- 
I need to trigger a notification when the application health goes into `degraded`, easy to do with the trigger:
```
trigger.on-health-degraded: |
  - description: Application has degraded
    send:
    - app-health-degraded
    when: app.status.health.status == 'Degraded'
```

but then I need a way to know when the issue was resolved.
A trigger of the like 
`when: app.status.health.status == 'Healthy'` 

would send a notification all time the status goes from `progressing` to `healthy` so it would spam the channel with useless info, not only informing that an error was resolved

So I would need a way of adding `oncePer` that tracks if it was in `degraded` before

Any help?

**Comment by AekarinOngart** [comment]
Did you found any solution? I also want to add `oncePer` on this `trigger`.

**Comment by shermanericts** [comment]
Toiled with this today, albeit this is far from a perfect solution.  This alerts me a) when a new revision is deployed and b) when an App is healed.

```
trigger.on-app-deployed-healthy: |
  - description: Application Deployed and Healthy
    send:
    - app-deployed-healthy
    when: app.status.sync.status == 'Synced' and app.status.health.status == 'Healthy'
    oncePer: app.status.operationState?.syncResult?.revision
```
