### DISCUSSION TITLE
Issues using ignoreDifferences with HPA

### DISCUSSION THREAD

**Discussion by jgutschon** [argoproj/argo-cd#14166] [Q&A]
I'm having some issues using `ignoreDifferences` on a few applications that are running Deployments with an HPA. I'm setting `ignoreDifferences` on the Application to ignore fields managed by `kube-controller-manager`:

```
ignoreDifferences:
    - group: apps
      kind: Deployment
      managedFieldsManagers:
        - kube-controller-manager
```

and I've set the sync policy as:

```
syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
```

My goal here is to ignore the `replicas` field on the deployment since it will be managed by `kube-controller-manager` with the HPA enabled for the deployment. I'm aware of the recommendation to omit this field entirely if using an HPA, however I've chosen to set it as the HPA's `minReplicas` to prevent scaling down to one pod if the Deployment is recreated in some scenarios. 

This has worked fairly well in general, however, if the replicas field in the Deployment manifest is manually edited and applied in the ArgoCD UI, the `kube-controller-manager` managed field is overwritten and `argocd-server` becomes the manager:

```
- apiVersion: apps/v1
  fieldsType: FieldsV1
  fieldsV1:
    'f:spec':
      'f:replicas': {}
  manager: argocd-server
  operation: Update
  time: '2023-06-21T15:02:04Z'
```

After this change, the deployment becomes out of sync and shows a diff on the replicas field. Syncing again after this will then cause it to scale down to value in the manifest. After syncing, the replicas field becomes managed by `argocd-controller`. The HPA still functions normally and scales as needed but the deployment stays out of sync as the replicas value changes.

The only way I've been able to restore the managedFields for kube-controller-manager at this point has been to orphan-delete the deployment and recreate it, but any future manual edits to the replicas field reproduce this behavior. Not exactly sure if this is intended behavior so I'm wondering if anyone knows a way around this issue.
