### DISCUSSION TITLE
Possible to use wildcard in valueFiles spec?

### DISCUSSION THREAD

**Discussion by ghost** [argoproj/argo-cd#14179] [Q&A]
I am using an applicationsets and am wondering if its possible to use a wild card in the valueFiles field. Something like this:

```
spec:
  source:
    repoURL: git@github.com:thisisnotreal/notreal.git
    targetRevision: HEAD
    path: '{{path}}'
    helm:
      valueFiles: ['values.*.yaml']
```
