### DISCUSSION TITLE
Argocd + Rollouts + Reloader

### DISCUSSION THREAD

**Discussion by SrDayne** [argoproj/argo-cd#14183] [Q&A] [answered]
Did someone actually make it all work together?

I spent 3 days implementing it with no luck. Every ConfigMap change I got different results: OutOfSync; no see changes at all; only one Rollout out of two dot restarted; etc.

I'm trying to understand, is it worth to keep trying or it doesn't work by design and I should look for another solution?

**Comment by SrDayne** [comment, marked as answer]
He he 😀 
I solved this puzzle.
For all lost souls like me, who search for solution, you have to run Reloader pod with `--reload-strategy=annotations` argument. In this case Reloader will run in "Annotation mode" which adds metadata to `spec/template/metadata/annotations` field. This prevents Argocd from OutOfSync state.

**Reply by qdrddr** [reply]
hi, @SrDayne 
I have the same issue, but -reload-strategy=annotations didn't help me. Do you have any other suggestions?

https://github.com/stakater/Reloader/issues/627

**Reply by alexrecuenco** [reply]
I know I might be late to the party but if that is failing, and for some reason the annotations reload strategy is failing, it could be something else.

If that makes you switch back to the variable change strategy. you might need to tell ArgoCD to ignore differences on `env` fields that contain `STAKATER_FOO_CONFIGMAP` or `STAKATER_FOO_SECRET` ([see here](https://github.com/stakater/Reloader/blob/master/docs/How-it-works.md)) using [this](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration)

Some diff strategy like this would ignore those `env` variables changes in Deployments

```yaml
ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
      - .spec.template.spec.containers[].env[] | select(.name == "STAKATER_FOO_CONFIGMAP")
      - .spec.template.spec.containers[].env[] | select(.name == "STAKATER_FOO_SECRET")
```

And I am sure it is similar with Daemonsets Statefulsets and Rollouts

**Reply by mrsimonemms** [reply]
I've solved this a slightly different way, but it's combing all the above answers.

I kep Reloader in "envvar mode" and then set the following in my `argocd-cm` file:
```yaml
    resource.customizations.ignoreDifferences.all: |
        jqPathExpressions:
          - .spec.template.spec.containers[].env[] | select(.name | startswith("STAKATER_"))
          - '.spec.template.metadata.annotations."reloader.stakater.com/last-reloaded-from"'
```

This seems to catch both annotations and environment variables, so it doesn't matter which mode you're in. I used envvar mode because of https://github.com/argoproj/argo-cd/issues/7513.

See [Argo docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/)
