### DISCUSSION TITLE
ArgoCD sends a flood of notifications when subscribing to new channels

### DISCUSSION THREAD

**Discussion by AnshumanTripathi** [argoproj/argo-cd#14382] [Q&A]
Hi,
I am working on setting up ArgoCD notifications for slack and whenever I update my application or project to subscribe to a new slack channel, ArgoCD sends a flood of notifications for apps which have not been updated recently. The following is the trigger I am using.

```yaml
      trigger.on-sync-succeeded: |
        - description: Application syncing has succeeded
          oncePer: app.status.sync.revision
          send:
          - app-sync-succeeded
          when: app.status.operationState.phase in ['Succeeded']
```

Is there a way to only send slack notifications for apps updated after the subscription? Or maybe have a condition where we can get notified of apps updated in the last 1 hour?

**Comment by driv** [comment]
I'm facing the same issue, I was testing notifications and flooded our Slack channel. Now I have to enable them again with the final configuration and I'll flood the channel again.
Same thing with Grafana annotations, it looks like 100s of applications have been deployed at the same time.

Is there any way to mute the notifications?

Should an issue be created for this?

**Comment by AnshumanTripathi** [comment]
I found a solution which kind of works for notifications. Updating the trigger to only notify if the changes were within 2 hours can potentially reduce the storm but its not an ideal solution.

```yaml
trigger.on-sync-succeeded: |
        - description: Application syncing has succeeded
          oncePer: app.status.sync.revision
          send:
          - app-sync-succeeded
          when: app.status.operationState.phase in ['Succeeded'] and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Hours() <= 2
```
