### DISCUSSION TITLE
cuelang with argocd

### DISCUSSION THREAD

**Discussion by vinvli** [argoproj/argo-cd#14472] [Ideas]
I noticed cuelang as a templating engine for kubernetes manifests is getting more traction. 
Are there any plans on introducing it in argo cd as an option next to helm and kustomize?

**Comment by mausch** [comment]
Has anyone written a ConfigManagementPlugin for cue ?

**Comment by dd84ai** [comment]
Some person did it 5 years ago https://github.com/zoetrope/argocd-cue
Looks like a potential source of inspiration to make it happen once again
I'll try to poke this code and give a try to make.. cleaner and up to date for its workability
looks like not a big problem to rewrite it to modern example
- https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/
- https://github.com/argoproj/argo-cd/tree/master/examples/plugins/helm

**Comment by yevvhen** [comment]
Recently at Profisea Labs, we faced the challenge of developing this functionality by ourselves.

The first step we took was to familiarize ourselves with Cuelang through the following tutorial:
https://github.com/cue-lang/cue/blob/v0.6.0/doc/tutorial/kubernetes/README.md

This guide is incredibly helpful as it covers the entire process: transitioning your Kubernetes configurations to Cuelang and, crucially, introducing a **dump tool** capable of converting Cuelang configurations into YAML format. This will be essential for our integration with ArgoCD.

Then we implemented ArgoCD Config Management Plugin according to the official docs:
https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/

The process is straightforward - you simply need to adjust your ArgoCD Helm values as follows:
```
repoServer:
  initContainers:
    - name: cuelang-get-binary
      command:
        - "/bin/bash"
      args:
        - "-c"
        - "apt update;
          apt install -y wget;
          wget -q https://github.com/cue-lang/cue/releases/download/v0.7.0/cue_v0.7.0_linux_arm64.tar.gz;
          tar -xzf cue_v0.7.0_linux_arm64.tar.gz -C /cue"
      image: ubuntu:22.04
      volumeMounts:
        - mountPath: /cue
          name: cmp-cuelang-binary
  extraContainers:
    - name: cmp-cuelang
      command:
        - "/var/run/argocd/argocd-cmp-server"
      image: busybox:1.36
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: cuelang.yaml
          name: argocd-cmp-cm
        - mountPath: /tmp
          name: cmp-tmp
        - mountPath: /cue
          name: cmp-cuelang-binary
  volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}
    - name: cmp-cuelang-binary
      emptyDir: {}
```
And:
```
configs:
  cmp:
    create: true
    plugins:
      cuelang:
        generate:
          command: ["sh", "-c"]
          args: ["/cue/cue cmd -t {your-parameters} dump ./..."]
        discover:
          fileName: "./*.cue"
```
Based on the last line, any Applications stored in folders with Cuelang files will automatically be managed by this plugin.
You have the flexibility to adjust the args field to inject custom values or utilize specific tools as needed. The main point of this line is that the command should output all resources in YAML format.

To keep this explanation from getting too complex, I suggest starting with a basic Kubernetes tutorial. Try managing a simple Application using Cuelang and the ArgoCD CMP. After that, you'll be in a better position to consider how to structure your Applications.

We do it in the next way:
```
cue/
├─ settings/
│  ├─ options.cue
│  ├─ versions.json
├─ template/
│  ├─ template.cue
├─ tools/
│  ├─ *_tool.cue
├─ microservice1.cue
├─ microservice2.cue
├─ microservice3.cue
├─ ... 
```
Our project structure includes a _template/_ folder for holding templates of each Kubernetes resource type. We have a _tools/_ folder for keeping utilities, such as YAML exporter. Additionally, there's a fascinating _settings/_ folder dedicated to storing configurations specific to different environments, like image versions, environment types, and mappings of Kubernetes resources to ArgoCD Applications. This _settings/_ folder acts as a central hub for global configurations that affect all our microservices.

Folders are organized into Cuelang packages based on their names, with the root package being named "microservices".
