### DISCUSSION TITLE
How to avoid unmarshal errors in application definition files when using Helm in an Application.

### DISCUSSION THREAD

**Discussion by naruse666** [argoproj/argo-cd#14491] [Q&A]
First, I'm not very good at English.

I have created an Application definition file that reads the applications directory in helm managed argocd. as follows.

### directory structure
chart name is `my-argo-chart`.
```
.
├── Chart.yaml
├── charts
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   ├── application.yaml
│   └── applications
│       └── child-application.yaml // problem file
└── values.yaml
```

### application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
spec:
  destination:
    namespace: my-ns
    server: https://kubernetes.default.svc
  project: {{ .Release.Name }}-proj
  source:
    path: <path>/templates/applications  # read in "applications/child-application.yaml"
    repoURL: <github url>
    targetRevision: <revision>
```

### applications/child-application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name}}
  namespace: argocd
spec:
  project: {{ .Release.Name }}-proj
  source:
    repoURL: <helm repo url>
    targetRevision: 0.1.0
    chart: my-other-chart
    helm:
      releaseName: {{ .Release.Name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: my-ns
```

## What's working just now
I installed with the command `helm install <release name> ./my-argo-chart`.
The child application is created correctly and the helm chart is successfully installed.

## The problem that is happening
I'm getting this error in the parent applicatioin.
```
rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal "child-application.yaml": <nil>
```
## Want to ask
How can a parent application correctly recognize a child application?
Is this approach a bad thing to begin with?
or ApplicationSet the best solution?
