### DISCUSSION TITLE
Is Kustomize no longer supported by ArgoCD?

### DISCUSSION THREAD

**Discussion by Newbie112222** [argoproj/argo-cd#14515] [Q&A]
Hi All,
I am using argocd version v2.6.7. I am trying to utilize kustomize to replace a value in my deployment file by using patch.
Below is my implementation:

kustomization.yaml looks like below:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../test_deployment.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: testargo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers
        value: us-west-2
```

I tried with having my deployment.yml in the same directory as the kustomization.yaml (seen below). In the code above i also tried with creating a copy of the kustomization file in a different folder and gave the neccessary path in my application.yml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - test_deployment.yaml
```
  
  The issue here is that the `kubectl kustomize .` command is able to replace the value in my local but when deployed using argocd i see that the status is Unknown for the  kustomization.yaml  - it just keeps on spinning around and then fails. I am not seeing anything helpful in the logs as well.
  
  Any ideas would be appreciated. I am trying to use this to replace values in my deployment.yml file dynamically.
