### DISCUSSION TITLE
Anthon Connect Gateway rate limiting - the server has received too many requests

### DISCUSSION THREAD

**Discussion by dwilliams782** [argoproj/argo-cd#14569] [General]
Hi,

We have configured two GKE clusters as part of a fleet and we're using the connect gateway to authenticate argo on one cluster to manage resources on the other, using the following:

```
  clusterCredentials:
    - name: cluster
      server: https://connectgateway.googleapis.com/v1/projects/<projectId>/locations/global/gkeMemberships/<clusterName>
      config:
        execProviderConfig:
          command: "argocd-k8s-auth"
          args: ["gcp"]
          apiVersion: "client.authentication.k8s.io/v1beta1"
        tlsClientConfig:
          insecure: false
          caData: ""
```

With just one cluster being accessed via the Connect Gateway, and that cluster has one application configured, we are being rate limited by the gateway:

```
level=error msg="Failed to reload open api schema" error="error getting openapi resources: the server has received too many requests and has asked us to try again later" server="https://connectgateway.googleapis.com/v1/projects/<projectId>/locations/global/gkeMemberships/<clusterName>"
```

The argo logs are being spammed with these kinds of rate limiting errors, and the Connect Gateway requests per minute quota is generally completely saturated (only showing ~80% in the screenshot but this bounces up to 100% each refresh):

![image](https://github.com/argoproj/argo-cd/assets/42545485/a7a035ae-3a6c-4b07-a5bf-35c6bf850e74)

We only have one small application deployed to this cluster:

![image](https://github.com/argoproj/argo-cd/assets/42545485/a27783db-b12f-4f15-9d00-f6d565143173)

I've seen plenty of reports of people using the Connect Gateway but only one similar report [here](https://github.com/argoproj/argo-cd/issues/9226#issuecomment-1485807613) of rate limiting.

Any ideas?
