### DISCUSSION TITLE
Prevent ApplicationSet with git generator to auto delete Application

### DISCUSSION THREAD

**Discussion by gaeljw** [argoproj/argo-cd#14574] [Q&A]
Hello folks,

I'm having a bit of a hard time understanding how deletion propagates with `ApplicationSet`s.

My setup is the following:
- an `ApplicationSet` with a git generator that "listens" on an (other) git repo directory
- the other git repo contains a list of file, each file resulting in an `Application` to be created

ApplicationSet:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: http://gitlab..../myapps.git
        revision: HEAD
        files:
        - path: 'somedir/argocd-apps/*-config.yaml'
        pathParamPrefix: 'app'
  template:
    metadata:
      name: '{{platform}}-{{appname}}'
    spec:
      project: xxx
      source:
        repoURL: http://gitlab..../myapps.git
        targetRevision: HEAD
        path: '{{folder}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{platform}}-xxx'
      syncPolicy:
        automated:
          prune: true
```

And in the myapps git repo under `somedir/argocd-apps/`, I have several files like `whatever-config.yaml`:
```yaml
appname: myapp1
platform: dev
cluster: dev
folder: somedir/myapp1/environments/dev
```

I'd like to be able to delete one of these `whatever-config.yaml` file in the git repo but still keep the `Application` (and its resources) temporarily until I hit the "sync" button somewhere for instance.

In my understanding the `syncPolicy` in the `ApplicationSet` template applies to the `Application` themselves, thus is irrelevant here.

Then, how to be able to commit the deletion on Git but not trigger the removal of the `Application` from the `ApplicationSet` but flag it as "out of sync" or something similar?

I'm open to change a bit the way I use `ApplicationSet`s if another setup makes thing easier.

Thanks for any help :)
