### DISCUSSION TITLE
Bitnami Sealed Secrets constantly in status OutOfSync

### DISCUSSION THREAD

**Discussion by SeveHo** [argoproj/argo-cd#14601] [General]
I have a Bitnami SealedSecret as part of my helm deployment that is managed as ArgoCD application. The unsealing of the secret works fine, however in the Argo admi nUI the SealedSecret is constantly shown as "OutOfSync" and refreshing every couple seconds. Did anybody experience the same or knows how to deal with this? Here is my Secret:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: core-api-sealed-secret
  namespace: dev
spec:
  encryptedData:
  <REDACTED>
  template:
    metadata:
      creationTimestamp: null
      name: core-api-sealed-secret
      namespace: dev
    type: Opaque
```
