### DISCUSSION TITLE
argocd cli option to only sync 'out of sync' resources?

### DISCUSSION THREAD

**Discussion by tooptoop4** [argoproj/argo-cd#14613] [Q&A]
is there argocd cli option to only sync 'out of sync' resources?

**Comment by pasha-codefresh** [comment]
You can't apply out of sync only from CLI today, i will open PR for it

**Reply by pasha-codefresh** [reply]
One thing that you can do right now, you can define sync policy in application manifest and after just sync , like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
```
