### DISCUSSION TITLE
Frequency of hitting git repo

### DISCUSSION THREAD

**Discussion by de-slalonde** [argoproj/argo-cd#14650] [Q&A]
I have an instance of Argo CD v2.7.7 running in a single cluster, single git repository (Bitbucket), with about 75 apps. Our typical application looks something like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: my-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@bitbucket.org:mycompany/argo-repo.git
      path: manifests/internal/my-app
      targetRevision: HEAD
    - repoURL: my-helm-repo/charts
      chart: my-chart
      targetRevision: 0.1.0
      helm:
        releaseName: my-app
        valueFiles:
          - $values/values/internal/my-app-values.yaml
    - repoURL: git@bitbucket.org:mycompany/argo-repo.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
```

Also I've set the reconciliation timeout to 15 minutes.

I can see in our monitoring that Argo is doing about 3 git fetches, and 3 git "ls-remote" every minute. Then, once every 15 minutes it's doing between 30 and 70 additional ls-remotes. I have a few questions:

1) Why is it hitting git 6 time every minute when the reconciliation timeout is 15 mins. My thought was that it would check git every 15 minutes, but between those times it would have no interest in what's going on in our repo.

2) Every 15 minutes, when the reconciliation timeout is reached, why does it make so many requests to the git repository? All of our apps are using the same repo. Is it possible to fetch it once and cache it or something?

This is not a huge problem for us at the moment, but we are looking at scaling way up and it's going to get rough on our git repository.

Thanks for any feedback!
