### DISCUSSION TITLE
Using ECR hosted helm repository and update the values from my git repo

### DISCUSSION THREAD

**Discussion by ruwanvm** [argoproj/argo-cd#14695] [Q&A]
I have a ECR hosted private repository and I want to use a chart from that repository and update the values from my git repository file. Following is my Application manifest. Can someone check what is the error here

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  project: default
  source:
    repoURL: git@github.com:me/my-repo.git
    path: deployments/secrets-app
    targetRevision: HEAD
    helm:
      repoURL: xxxxxxxxxxxx.dkr.ecr.xxxxxxxxx.amazonaws.com
      chart: my-helm
      version: 0.1.0
      valueFiles:
        - secrets://values.yaml
  destination:
    namespace: secrets-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
``` 

I get the following error

`Application in version "v1alpha1" cannot be handled as a Application: strict decoding error: unknown field "spec.source.helm.chart", unknown field "spec.source.helm.repoURL"`

When I try with moving chart etc, outside helm field. It also fails. How can I use 2 repos in ArgoCD application like this case
