### DISCUSSION TITLE
Karpenter provisioners via argocd and excluding Node

### DISCUSSION THREAD

**Discussion by andrewhibbert** [argoproj/argo-cd#14709] [General]
Hi,

I am configuring karpenter provisioners via argocd and each provisioner has a number of nodes which I'd like to exclude from the UI, however `resource.exclusions` is not working for this

```
  resource.exclusions: |
    - apiGroups:
       - "*"
      kinds:
       - Node
      clusters:
       - "*"
```

How can I do this?

Thanks
