### DISCUSSION TITLE
ArgoCD integration with Github Enterprise

### DISCUSSION THREAD

**Discussion by pkruk** [argoproj/argo-cd#14826] [Q&A] [answered]
Hello,

I'm trying to configure the Github Enterprise Oauth with argocd-dex server and I'm getting run out of ideas.

My setup looks like this: 

ingress:
```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/hostname: argocd.X
spec:
  ingressClassName: private-ingress-nginx
  rules:
    - host: argocd.X
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80
          - path: /api/dex/callback
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80

```

argocd-cmd-params-cm:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  server.dex.server: "argocd.X/api/dex"

```

argocd-cm

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.X
  kustomize.buildOptions: --enable-helm
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          hostName: GITHUB_ENTERPRISE
          clientID: ID
          clientSecret: SECRET
          redirectURI: https://argocd.X/api/dex/callback 
          orgs:
            - name: MyOrg

```

In the console I got the:

```
api/v1/clusters 401 (Unauthorized)
```

So my integration is not working and I don't know why. 

I have my argocd behind the nginx-ingress and this one is responsible for terminating TLS. In my Github Oauth App I had the correct uri: `https://argocd.X/api/dex/callback`. Should I look somewhere else in logs or in configuration?
