### DISCUSSION TITLE
Multiple deployments per cluster

### DISCUSSION THREAD

**Discussion by f4tq** [argoproj/argo-cd#14907] [General]
Hi,
I've been tasked with moving from a home grown deployment system to argocd.

We currently have 1-5 deployments of an app per cluster.  FWIW, it's possible that each of these deployments may need to use a different versions of the same helm chart.

I have a working helm chart for a single deployment.

So essentially, I need to iterate a list of values and render the complete chart for each(unique labels/selects also).
 
There is a base deployment with values like so:
```
 name: main
 envoy:
      adminPort: 9999
      httpPort: 7000
      httpsPort: 7001
```
Optionally there can additional values for the cluster that looks something like this:
```
bulkheads:
- name: bulkhead1
  envoy:
      adminPort: 9999
      httpPort: 7000
      httpsPort: 7001
- name: bulkhead2
  envoy:
       adminPort: 10999
       httpPort: 8000
       httpsPort: 8001
```
Can I iterate a list *from argo* such potentially multiple chart renderings/deployments occur to then same cluster?  

FWIW, rendering the full chart involves multiple resources such as secrets, config maps etc. 
Using a helm only approach via go template `range` over bulkheads seems hacky and fraught with label/selector issues?

I can't find an example such as this.

Any suggestions on an approach?
