### DISCUSSION TITLE
Using Matrix generator (Git & Cluster Generator), how can I configure to deploy Applications from a specific folder in Git repo to a Specific Cluster?

### DISCUSSION THREAD

**Discussion by Josephred999** [argoproj/argo-cd#15033] [Q&A]
0

While reading the Matric Generator: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/ , I see we can combine two different Generators and deploy Applications on multiple Clusters at the same time.

For my use case where I have multiple folders in my Git Repo (Where I have my K8s resource yaml files) and I have 4 K8s clusters but I dont want all of my K8s yaml files in those folders to be deployed on all Clusters.

For example, this is my folder staructure:

```
https://www.test-gitlab.com/repo1/dev1

https://www.test-gitlab.com/repo1/dev2

https://www.test-gitlab.com/repo1/dev3 &

https://www.test-gitlab.com/repo1/dev4
```

Any my K8s Clusters are:

```
dev1

dev2

dev3 &

dev4
```

So from the above list, I want to target the files from dev1 folder to dev1 cluster and dev2 folder to dev2 cluster and so on.

Looks like by default, the Matric Generator (with git & cluster generator), it deploys all files from the provided path to all clusters.

How can I achieve this type of setup?

Cheers!!

**Comment by FernandoMiguel** [comment]
our clusters are tagged with a BU
we then filter that BU when the app sets a property in the values.yaml for the argo block
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployments
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                matchExpressions:
                  - key: business-unit
                    operator: In
                    values:
                      - "{{if lt 0 (len .argo.businessunit)}}{{index .argo.businessunit 0}}{{else}}na{{end}}"
                      - "{{if lt 1 (len .argo.businessunit)}}{{index .argo.businessunit 1}}{{else}}na{{end}}"
                      - "{{if lt 2 (len .argo.businessunit)}}{{index .argo.businessunit 2}}{{else}}na{{end}}"
                      - "{{if lt 3 (len .argo.businessunit)}}{{index .argo.businessunit 3}}{{else}}na{{end}}"
                      - "{{if lt 4 (len .argo.businessunit)}}{{index .argo.businessunit 4}}{{else}}na{{end}}"
```
you could easily replace BU with env
