### DISCUSSION TITLE
Can applicationset create application for every subfolder (recursively) that gets created in the source Git Repo?

### DISCUSSION THREAD

**Discussion by Josephred999** [argoproj/argo-cd#15052] [Q&A]
My Source Git repo directory looks like this:

```
K8s-envs/
├── Dev
├── Int
├── Preprod
└── Prod
```

Currently I have 4 applications for each env (via List Generator) from the above setup.

Is it possible to applicationset to create new applications for the subfolders (recursively) that gets created within these folders?

Like:

```
K8s-envs/
├── Dev
│       ├── sub-folder1
│       ├── sub-folder2
│       └── sub-folder3
├── Int
│       ├── sub-folder1
│       ├── sub-folder2
│       └── sub-folder3
├── Preprod
│       ├── sub-folder1
│       ├── sub-folder2
│       └── sub-folder3
└── Prod
        ├── sub-folder1
        ├── sub-folder2
        └── sub-folder3
```
Cheers!!

**Comment by FernandoMiguel** [comment]
not recursively.
it will do the level you set it to do, but you can tell it to do multiple, and also exclude some
```
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: "https://github.com/xxx/deployments.git"
                    revision: HEAD
                    directories:
                      - path: "*/*/*"
                      - path: "examples/*/*"
                        exclude: true
```
do keep in mind, some folders may provide other functionality, like helm templates.
