### DISCUSSION TITLE
How can I provide multiple destination (clusters) when using Git Geneator?

### DISCUSSION THREAD

**Discussion by Josephred999** [argoproj/argo-cd#15105] [Q&A] [answered]
I am leveraging Git Generator (Directory) and I want to see how and if I can provide multiple destination clusters as the source repo is same (but paths will be different from the source repo) and try to deploy K8s resources in multiple destination K8s Clusters.

```
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
```

**Comment by FernandoMiguel** [comment, marked as answer]
we use cluster generator
https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/
```
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: "https://github.com/xxx/deployments.git"
                    revision: HEAD
                    directories:
                      - path: "*/*/*"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                matchExpressions:
                  - key: aws-region
                    operator: In
                    values:
                      - "{{if lt 0 (len .argo.region)}}{{index .argo.region 0}}{{else}}na{{end}}"
```
