### DISCUSSION TITLE
Progressive sync for apps part of ApplicationSet

### DISCUSSION THREAD

**Discussion by gaeljw** [argoproj/argo-cd#15100] [Q&A] [answered]
Hello folks,

I was wondering if there's a way to progressively sync Applications that are part of the same ApplicationSet?

For instance I have 2 apps created by an ApplicationSet via a git folder generator. I make a change (git commit) that impacts the resources of those 2 apps. It's not a change in the Application definition but in its resources.

I've seen the "progressive sync" feature recently added and tried it but it seems to not work in this situation. If I understand correctly, the feature is for progressively syncing the Applications definition when the ApplicationSet is modified but not when the Applications content changes.

Am I missing something or does this feature not exist yet? Would there be some kind of workaround to simulate this behaviour?

To give more context, I was trying this to workaround the issue https://github.com/argoproj/argo-cd/issues/8008

**Comment by crenshaw-dev** [comment]
I would have expected Progressive Syncs to work the way you described, based on this from the docs:

> RollingSync will capture external changes outside the ApplicationSet resource, since it relies on watching the OutOfSync status of the managed Applications.

@wmgroot are we misunderstanding, or maybe is @gaeljw just encountering a bug?

**Reply by gaeljw** [reply]
I can provide a minimal reproduction scenario in case what I observed is not expected.

**Reply by wmgroot** [reply]
It's expected that RollingSync will respond to changes other than a modification of the AppSet spec.

Sounds like a bug and a repro case would be very helpful to identify what's happening.

**Reply by crenshaw-dev** [reply]
Thanks, @wmgroot!

**Reply by gaeljw** [reply]
@wmgroot here's a reproduction repo: https://github.com/gaeljw/argocd-progressive-sync/tree/master

The relevant files are:
- AppSet with rolling sync: https://github.com/gaeljw/argocd-progressive-sync/blob/master/apps/appset.yaml
- Apps content: https://github.com/gaeljw/argocd-progressive-sync/tree/master/test-rolling-sync

I've made a commit that affect the 2 apps: https://github.com/gaeljw/argocd-progressive-sync/commit/5e488a071ec88b98959b8cd97c0b5ab863c3fd3b

But nothing happens: apps stay in "not sync" status:

![image](https://github.com/argoproj/argo-cd/assets/18280708/c59cca46-c081-4f71-8c4f-e585b1e14aa1)


-----

I'm copying here in plain text the AppSet relevant sections for easier reading:

```yaml
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        # One at a time
        - matchExpressions:
            - key: roll-one-by-one
              operator: In
              values:
                - 'true'
          maxUpdate: 1

  template:
    metadata:
      labels:
        roll-one-by-one: 'true'
      ...
```

-----

I can provide more logs or more details as needed.

**Reply by gaeljw** [reply]
Adding that in this repro case, I was manually triggerring a "refresh all apps" from the UI. In my real setup, there's a webhook and the commit triggers ArgoCD refresh directly.

**Reply by wmgroot** [reply]
What do the applicationset-controller logs say about `test-rolling-sync-app1` and `test-rolling-sync-app2`?

**Reply by wmgroot** [reply]
And what are the contents of the `status` field of the ApplicationSet resource?

**Reply by gaeljw** [reply]
Starting from a state where both apps are Synced, then doing a commit that affect both apps and triggering a refresh from the UI. Here's what I observe:

Initial state of ApplicationSet:
```yaml
...
status:
  conditions:
  - lastTransitionTime: "2023-08-19T15:54:15Z"
    message: Successfully generated parameters for all Applications
    reason: ApplicationSetUpToDate
    status: "False"
    type: ErrorOccurred
  - lastTransitionTime: "2023-08-19T15:54:15Z"
    message: Successfully generated parameters for all Applications
    reason: ParametersGenerated
    status: "True"
    type: ParametersGenerated
  - lastTransitionTime: "2023-08-19T15:54:15Z"
    message: ApplicationSet up to date
    reason: ApplicationSetUpToDate
    status: "True"
    type: ResourcesUpToDate
```

Logs in applicationset-controller:
```
time="2023-08-20T09:46:54Z" level=info msg="git fetch origin HEAD --tags --force --prune" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=e2489
time="2023-08-20T09:46:54Z" level=info msg=Trace args="[git fetch origin HEAD --tags --force --prune]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=557.67311
time="2023-08-20T09:46:54Z" level=info msg="git checkout --force e1645d16a0e3481772c919aa0bcc0c047f46974e" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=51bc2
time="2023-08-20T09:46:54Z" level=info msg=Trace args="[git checkout --force e1645d16a0e3481772c919aa0bcc0c047f46974e]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=2.634132
time="2023-08-20T09:46:54Z" level=info msg="git clean -fdx" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=ef48a
time="2023-08-20T09:46:54Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=2.062865
time="2023-08-20T09:46:54Z" level=info msg="applications result from the repo service" allPaths="[apps argocd-bootstrap argocd-install kind test-rolling-sync test-rolling-sync/app1 test-rolling-sync/app2]" pathParamPrefix=instance repoURL="https://github.com/gaeljw/argocd-progressive-sync.git" revision=HEAD total=7
time="2023-08-20T09:46:54Z" level=info msg="generated 2 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/gaeljw/argocd-progressive-sync.git,Directories:[]GitDirectoryGeneratorItem{GitDirectoryGeneratorItem{Path:test-rolling-sync/*,Exclude:false,},},Files:[]GitFileGeneratorItem{},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:instance,} nil nil nil nil nil nil}"
time="2023-08-20T09:46:54Z" level=info msg="unchanged Application" app=test-rolling-sync-app1 appSet=test-features-applicationset-rolling-sync
time="2023-08-20T09:46:54Z" level=info msg="unchanged Application" app=test-rolling-sync-app2 appSet=test-features-applicationset-rolling-sync
time="2023-08-20T09:46:54Z" level=info msg="end reconcile" applicationset=argocd/test-features-applicationset-rolling-sync requeueAfter=3m0s
time="2023-08-20T09:46:54Z" level=info msg="git fetch origin HEAD --tags --force --prune" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=3ad70
time="2023-08-20T09:46:55Z" level=info msg=Trace args="[git fetch origin HEAD --tags --force --prune]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=446.870869
time="2023-08-20T09:46:55Z" level=info msg="git checkout --force e1645d16a0e3481772c919aa0bcc0c047f46974e" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=88bb7
time="2023-08-20T09:46:55Z" level=info msg=Trace args="[git checkout --force e1645d16a0e3481772c919aa0bcc0c047f46974e]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=8.947226
time="2023-08-20T09:46:55Z" level=info msg="git clean -fdx" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=d0e31
time="2023-08-20T09:46:55Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=6.829364
time="2023-08-20T09:46:55Z" level=info msg="applications result from the repo service" allPaths="[apps argocd-bootstrap argocd-install kind test-rolling-sync test-rolling-sync/app1 test-rolling-sync/app2]" pathParamPrefix=instance repoURL="https://github.com/gaeljw/argocd-progressive-sync.git" revision=HEAD total=7
time="2023-08-20T09:46:55Z" level=info msg="generated 2 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/gaeljw/argocd-progressive-sync.git,Directories:[]GitDirectoryGeneratorItem{GitDirectoryGeneratorItem{Path:test-rolling-sync/*,Exclude:false,},},Files:[]GitFileGeneratorItem{},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:instance,} nil nil nil nil nil nil}"
time="2023-08-20T09:46:55Z" level=info msg="unchanged Application" app=test-rolling-sync-app1 appSet=test-features-applicationset-rolling-sync
time="2023-08-20T09:46:55Z" level=info msg="unchanged Application" app=test-rolling-sync-app2 appSet=test-features-applicationset-rolling-sync
time="2023-08-20T09:46:55Z" level=info msg="end reconcile" applicationset=argocd/test-features-applicationset-rolling-sync requeueAfter=3m0s
time="2023-08-20T09:46:55Z" level=info msg="git fetch origin HEAD --tags --force --prune" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=1e791
time="2023-08-20T09:46:56Z" level=info msg=Trace args="[git fetch origin HEAD --tags --force --prune]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=479.53456100000005
time="2023-08-20T09:46:56Z" level=info msg="git checkout --force e1645d16a0e3481772c919aa0bcc0c047f46974e" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=4e6d0
time="2023-08-20T09:46:56Z" level=info msg=Trace args="[git checkout --force e1645d16a0e3481772c919aa0bcc0c047f46974e]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=8.811183
time="2023-08-20T09:46:56Z" level=info msg="git clean -fdx" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync execID=7d9e7
time="2023-08-20T09:46:56Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_gaeljw_argocd-progressive-sync operation_name="exec git" time_ms=7.715647
time="2023-08-20T09:46:56Z" level=info msg="applications result from the repo service" allPaths="[apps argocd-bootstrap argocd-install kind test-rolling-sync test-rolling-sync/app1 test-rolling-sync/app2]" pathParamPrefix=instance repoURL="https://github.com/gaeljw/argocd-progressive-sync.git" revision=HEAD total=7
time="2023-08-20T09:46:56Z" level=info msg="generated 2 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/gaeljw/argocd-progressive-sync.git,Directories:[]GitDirectoryGeneratorItem{GitDirectoryGeneratorItem{Path:test-rolling-sync/*,Exclude:false,},},Files:[]GitFileGeneratorItem{},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:instance,} nil nil nil nil nil nil}"
time="2023-08-20T09:46:56Z" level=info msg="unchanged Application" app=test-rolling-sync-app1 appSet=test-features-applicationset-rolling-sync
time="2023-08-20T09:46:56Z" level=info msg="unchanged Application" app=test-rolling-sync-app2 appSet=test-features-applicationset-rolling-sync
time="2023-08-20T09:46:56Z" level=info msg="end reconcile" applicationset=argocd/test-features-applicationset-rolling-sync requeueAfter=3m0s
```

ApplicationSet after (seems unchanged compared to before):
```yaml
...
status:
  conditions:
  - lastTransitionTime: "2023-08-19T15:54:15Z"
    message: Successfully generated parameters for all Applications
    reason: ApplicationSetUpToDate
    status: "False"
    type: ErrorOccurred
  - lastTransitionTime: "2023-08-19T15:54:15Z"
    message: Successfully generated parameters for all Applications
    reason: ParametersGenerated
    status: "True"
    type: ParametersGenerated
  - lastTransitionTime: "2023-08-19T15:54:15Z"
    message: ApplicationSet up to date
    reason: ApplicationSetUpToDate
    status: "True"
    type: ResourcesUpToDate
```
