### DISCUSSION TITLE
MultiSource Appset - Values are not honored from Values repo

### DISCUSSION THREAD

**Discussion by gauravpatel2016** [argoproj/argo-cd#15165] [General]
Hello,

We have 3 repos.
1. Basic helm chart (ie. secret helm chart repo)
2. Patching Repo to deployment resources  (patching repo)
3. Values repo for different clusters (helm-values repo)

I have applicationSet using multisource.

```    
      sources:
      - helm:
          ignoreMissingValueFiles: true
          releaseName: secret
          valueFiles:
          - values.yaml
          - $values/charts/secret/{{name}}.yaml
        path: .
        repoURL: git@gitlab.com:my-services/secret
        targetRevision: HEAD
      - repoURL: git@gitlab.com:my-services/patching.git
        path:  ./helm/secret
        targetRevision: HEAD
        helm:
          releaseName: secret-extensions
          ignoreMissingValueFiles: true
          parameters:
          - name: mypatch.deployEnv
            value: 'test'
          valueFiles:
          - values.yaml
          - $values/charts/secret/{{name}}.yaml
      - ref: values
        repoURL: git@gitlab.com:my-services/helm-values
        targetRevision: HEAD
```

When I apply, it creates everything fine except values are not coming from helm-values repo.
If I remove, secret-extensions which is patching my secret service deployment resource, it gets value from helm-values repo.

Any idea how to fix this?
