### DISCUSSION TITLE
Unavailable desc = error reading from server: EOF

### DISCUSSION THREAD

**Discussion by ppippi-dev** [argoproj/argo-cd#15183] [Q&A]
I have some problem using argocd

I try to create app kube-prometheus-stack chart (48.3.3)

but it doesn't work with argocd 

when i try it using `helm install`, it works 

but, Using argocd - create app. it has some error

i will attach my error message and manifest

++ my argocd version is v2.7.9

error message
`Unable to create application: application spec for kube-prometheus-stack is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unavailable desc = error reading from server: EOF`

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  finalizers: []
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 48.3.3
    chart: kube-prometheus-stack
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated: null

```
