### DISCUSSION TITLE
bubble chart versions as labels

### DISCUSSION THREAD

**Discussion by FernandoMiguel** [argoproj/argo-cd#15219] [Q&A]
We use a form of dependency chart with our ApplicationSets
```
apiVersion: v2
name: external-secrets
description: A Helm chart for the External Secrets operator

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png

dependencies:
  - name: external-secrets
    version: ~0.9.3
    repository: https://charts.external-secrets.io/
```

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployments
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: "https://github.com/myorg/deployments.git"
                    revision: HEAD
                    directories:
                      - path: "base/*/*/*"
                - git:
                    repoURL: "https://github.com/myorg/deployments.git"
                    revision: HEAD
                    files:
                      - path: "{{ .path.path }}/values.yaml"
  template:
    metadata:
      name: "{{ .nameNormalized }}-{{ .path.basename }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        priority: "{{ index .path.segments 2 }}"

    spec:
      project: default
      source:
        repoURL: "https://github.com/myorg/deployments.git"
        path: "{{ .path.path }}"
        targetRevision: HEAD
        helm:
          ignoreMissingValueFiles: true
          passCredentials: true
          valueFiles:
            - "/common/values.{{ .path.basename }}.yaml"
            - "./terraform-values.yaml"
            - "./values.yaml"
      destination:
        name: "{{ .nameNormalized }}"
```

How would I write a label that is able to that dependency chart version?

```
      labels:
        app.kubernetes.io/version: { { app.spec.source.chart.version } }
```
only gets me the root chart, obviously

Thanks in advance.
