### DISCUSSION TITLE
Can a redis instance be shared between multiple argocd instances?

### DISCUSSION THREAD

**Discussion by gaurav517** [argoproj/argo-cd#15260] [Q&A]
I want to have one redis instance (google managed redis) shared between multiple argocd instances. Is that supported by argocd?

Thanks

**Comment by gaurav517** [comment]
I did a test and it looks like sharing same redis instance would create conflicts between argocd instances.
I had following `Certificate` definition in three isolated clusters sharing same redis instance.
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: istio
    name: cert-1
```
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: istio
    name: cert-2
```
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: istio
    name: cert-3
```
And in `argocd` UI, `istio` application was flickering between `cert-1`, `cert-2` and `cert-3`. So either sharing same redis is not supported or this is a bug.
