### DISCUSSION TITLE
How to delete ArgoCD Project Role Token from CLI?

### DISCUSSION THREAD

**Discussion by Mais316** [argoproj/argo-cd#15306] [Q&A]
I am trying to delete an existing token and getting invalid syntax.

` $ argocd proj role remove-token proj-team-abc ci-role 2023-08-30T01:33:16-07:00`

Can anyone please share the proper syntax?

**Comment by wanddynosios** [comment]
When you list the tokens, you get a timestamp:

```bash
$ argocd proj role list-tokens PROJ ROLE
ID                                     ISSUED AT                    EXPIRES AT
0f45e41c-0000-0000-0000-00000000000    2024-07-31T14:30:10+02:00    Never
```

You have to convert that timestamp, e.g.

```bash
$ date --date='2024-07-31T14:30:10+02:00' +%s
1722429010
```

Now you can delete it:
```bash
argocd proj role delete-token PROJ ROLE 1722429010
```

The timestamp also available in the appproject's status:
```yaml
status:
  jwtTokensByRole:
    myrole:
      items:
        - iat: 1722429010
          id: 0f45e41c-0000-0000-0000-00000000000
```
