### DISCUSSION TITLE
How to set the KUSTOMIZE_PLUGIN_HOME env var for an ArgoCD App

### DISCUSSION THREAD

**Discussion by avijitsarkar123** [argoproj/argo-cd#15301] [Q&A]
Hi - I am using Kustomize with ArgoCD and using custom plugin. Before `kustomize build` execution by ArgoCD, I want to set the env var `KUSTOMIZE_PLUGIN_HOME` pointing to the path having the plugin code.

Per docs, I am setting the build options for plugin but not sure how to set the KUSTOMIZE_PLUGIN_HOME

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  data:
    kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-alpha-plugins
```
