### DISCUSSION TITLE
ApplicationSets of Apps?

### DISCUSSION THREAD

**Discussion by especially-relative** [argoproj/argo-cd#15320] [General]
I have a gitlab layout where each application to deploy has its own repo. Each repo is either a simple set of manifests, OR, a values file for a helm deploy, or in many cases both, where a helm deploy is supported by additional manifests (frequently ExternalSecrets).

So each repo currently has an application folder, what an argocd application yaml. Then an app of apps has to get updated pointed at that application folder on the repo.

Ideally I'd have an ApplicationSet pointed at that gitlab group, but if I am understanding the docs correctly, I'd end up with an app of an app per app (which just feels silly even typing it).

There are enough outliers (special case ignoredifferences lists, or additional sources), that templating things as ApplicationSet seems difficult as well.

Am I missing something, can I do something like combine scmprovider+gitprovider and avoid either manually updating the app of apps I have now while also avoiding some proliferation of an app of app for every repo?

Thanks!

**Comment by FernandoMiguel** [comment]
@danieljkemp you can have applicationsets deploy individual apps, not app of apps, per repo.
depends on the depth of your config to fetch those.

**Reply by especially-relative** [reply]
So the laout is like this

Repo1
  /application
    repo1-application.yaml
  /manifests
    ........

Repo2
  /application
    repo2-application.yaml
  /values
  /manifests

and ideally the appset would deploy the apps of repo1/2 from the /application directories. But as I understand it, it'll make an app with the contents of the directory... so I'd have 

appsetrepo1 -> an app containing the repo1-application.yaml app
appsetrepo2 -> an app containing the repo2-application.yaml app

**Reply by FernandoMiguel** [reply]
You should be looking for Chart.yaml if you want helm, with its own values.yaml
It can also have a template folder if you want to add or override components.

As for raw manifests, yeah it will use any folder you throw at it.

**Reply by especially-relative** [reply]
Yeah. The application def in the `/application` handles the helm charts. (almost) none of the helm charts are local, so the majority are using multisource applications, specifying a remote helm chart, and a local values file, stored in `/values`

Since the app defs are so varied (some plain manifests, some helm, some helm + manifests, some multiple helm....), there is an application in the `/application` directory. But a simple application of scmprovider will make an app of that application !

**Comment by especially-relative** [comment]
Maybe I can use the git generator to consider `application.yaml` a "config" file, and just have a template that looks like:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - scmProvider:
    # ...
  template:
    metadata:
      name: '{{ repository }}'
   spec:
     {{spec}}
```

**Reply by FernandoMiguel** [reply]
We do something similar.
We have a empty chart that has dependencies on other charts.
So this top level chart is the app, and it's what we care about.

I can post an example Monday, but there several examples here in this repo from previous tickets I've opened

**Reply by especially-relative** [reply]
I ended up taking another stab at this.

This PR: https://github.com/argoproj/argo-cd/issues/11213 might get me where I want to be


Each application has :+1: 
* a source with 0-2 helm chart defs
* optionally another git source of non-helm manifests (external secret defs, database etc)
* a source for the local values file
* potentially a ignore differences 
* different namespace labels for istio/pod security/etc

I thought of using a template before finding that the current templating is very basic. I advanced arbitary templating worked I could use scmprovider+git(files), and use the application file as a 'template' which would look like this:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-template
spec:
  generators:
    - matrix:
        generators:
          - scmProvider:
              gitlab:
                group: '59'
                allBranches: false
                includeSubgroups: false
                #insecure: false
                tokenRef:
                  secretName: creds-gitlab
                  key: password
              filters:
                - labelMatch: ^deploytest
                  pathsExist: [application/]
          - git:
              repoURL: '{{url}}'
              revision: HEAD
              files:
                - path: application/{{repository}}.yaml
  template:
    metadata:
      name: '{{repository}}-test'
    '{{ .spec }}'
```

if I used the git directory generator I'd have an application containing just my actual application... for every single application I want to deploy. Right?

Am I missing something?
