### DISCUSSION TITLE
SyncWindows to support AND operator

### DISCUSSION THREAD

**Discussion by darkrift** [argoproj/argo-cd#15360] [Ideas]
When you run multiple clusters, you sometimes face the situation where you need to have multiple schedule per timezone. If you need to run multiple clusters in the same timezone, this leads to something unmaintainable depending on the number of cluster or become quite hard to maintain and not forget an application in the lot.

Let's say you have 2 clusters for redundancy in the same timezone, you can end up in the following situation:

```
- kind: deny
      schedule: "0 6 * * *" #Everyday from 6 AM to 9 PM
      duration: 15h
      timeZone: "America/Los_Angeles"
      manualSync: true
      applications:
        - application1.cluster1
        - application1.cluster2
        - application1.cluster3
        - application2.cluster1
        - application2.cluster2
        - application2.cluster3
        - application3.cluster1
        - application3.cluster2
        - application3.cluster3
```

It would be much more maintainable if sync windows could allow to combine both clusters and apps in the following way :

```
- kind: deny
      schedule: "0 6 * * *" #Everyday from 6 AM to 9 PM
      duration: 15h
      timeZone: "America/Los_Angeles"
      manualSync: true
      combineMatchers: true
      applications:
        - application1.*
        - application2.*
        - application3.*
      clusters:
        - cluster1
        - cluster2
        - cluster3
```

`combineMatchers` would define to use an AND or an OR, would default to false which would be the current behavior
