### DISCUSSION TITLE
How to login using Github behind a reverse proxy (url prefix)

### DISCUSSION THREAD

**Discussion by davidshen84** [argoproj/argo-cd#15388] [Q&A] [answered]
Hi,

I have my argocd services working without using the prefix. But I need to add the `/argo-cd` prefix now.

I have added these extra arguments to the server deployment:

```yaml
        - --rootpath
        - /argo-cd
        - --basehref
        - /argo-cd
```
I can see these values in the deployment resource in the cluster.

I have also updated my GitHub app *Authorization call URL* with the url prefix.

After I land on the login page, I clicked the *login via github* button. Then I got redirected to this url.

```
http://argocd.localhost:8080/api/dex/auth?client_id=argo-cd&redirect_uri=http%3A%2F%2Fargocd.localhost%3A8080%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=*****
```

On the argocd-server pod, I got an entry like this.

```
argocd-server-55b749c677-kkf4q time="2023-09-07T03:28:27Z" level=info msg="Performing authorization_code flow login: http://argocd.localhost:8080/api/dex/auth?client_id=argo-cd&redirect_uri=http%3A%2F%2Fargocd.localhost%3A8080%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=***"
```

It looks like the server did not use the `/argo-cd` prefix to generate the login url.

My `dex.config` looks like this.

```
        dex.config: |
            connectors:
              - type: github
                id: github
                name: GitHub
                config:
                  clientID: ***
                  clientSecret: $argocd-secret:github.client.secret
                  orgs: []
```

I could not find any url prefix related configuration in dex related components.
