### DISCUSSION TITLE
valuesObject and multiple sources Applications

### DISCUSSION THREAD

**Discussion by Smana** [argoproj/argo-cd#15564] [Q&A] [answered]
Hi,

Here's my issue and I completely aware that this probably hasn't a solution.
I have an Application that uses multiple sources and this is really useful, for example if you want to deploy a Helm charts and surcharge with additional manifests!

However, as the `sources` is a list, this seems to be impossible to use `valuesObjects` which is another powerful feature for Helm users.

Am I right, do you have any advices in order to use multiple sources AND `valuesObject` (for merging nested Helm values)?

Thank you,
Smana

**Comment by crenshaw-dev** [comment]
> as the sources is a list, this seems to be impossible to use valuesObjects

Why is it impossible? What tool are you using to merge in values which does not support merging in children of lists?

**Comment by SmaineTF1** [comment]
Hi @crenshaw-dev , 

Let's take a concrete example, maybe my description is not clear:

I have a base application here:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  project: observability
  sources:
    - repoURL: https://helm.linkerd.io/edge
      chart: linkerd-control-plane
      targetRevision: "1.13.1-edge"
      ref: helm
      helm:
        objectValues:
          priorityClassName: system-cluster-critical
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                    - key: karpenter.sh/provisioner-name
                      operator: DoesNotExist

          enablePodDisruptionBudget: true

          deploymentStrategy:
            rollingUpdate:
              maxUnavailable: 1
              maxSurge: 25%
          enablePodAntiAffinity: true
          controllerReplicas: 3
          controller: &controller_resources
            cpu: &controller_resources_cpu
              limit: ""
              request: 300m
            memory:
              limit: 250Mi
              request: 250Mi
          # destination configuration
          destinationResources:
            cpu: *controller_resources_cpu
            memory:
              limit: 250Mi
              request: 250Mi
    - repoURL: https://github.com/mycompany/gitops.git
      targetRevision: main
      path: manifests/base/linkerd-control-plane
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
```

And a patch to change helm values there:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  project: observability
  sources:
    - repoURL: https://helm.linkerd.io/edge
      chart: linkerd-control-plane
      targetRevision: "1.13.1-edge"
      ref: helm
      helm:
        objectValues:
          controllerReplicas: 10
          identityResources:
            memory:
              limit: 1Gi
              request: 1Gi
```
The `kustomization.yaml` file:
```yaml
piVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: application.yaml
    target:
      group: argoproj.io
      kind: Application
      name: linkerd-control-plane
      namespace: argocd
      version: v1alpha1
```

And the **result** is
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  project: observability
  sources:
    - repoURL: https://helm.linkerd.io/edge
      chart: linkerd-control-plane
      targetRevision: "1.13.1-edge"
      ref: helm
      helm:
        objectValues:
          controllerReplicas: 10
          identityResources:
            memory:
              limit: 1Gi
              request: 1Gi
```

So the valuesObjects are not merged. But again I'm not surprise as this is `kustomize`'s behavior when it comes to nested lists.
I was wondering if you have any tricks to build the full application, including the valuesObjects of the base file?

Thank you

**Reply by crenshaw-dev** [reply]
Hm. I bet it would work if we specified a merge key and then loaded the openapi spec into Kustomize. But that's a lot of overhead.

Maybe a JSON patch, specifying the array index?

**Reply by SmaineTF1** [reply, marked as answer]
It seems that I found a solution using [this way](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/) of supporting custom resources in kustomize.

I downloaded the whole openapi spec from [here](https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json) and changed a tiny thing:

`schema.json`
```yaml
...
                "sources": {
                    "description": "Sources is a reference to the location of the application's manifests or chart",
                    "type": "array",
                    "items": {
                        "default": {},
                        "$ref": "#/definitions/io.argoproj.argocd.v1alpha1.ApplicationSource"
                    },
                    "x-kubernetes-patch-merge-key": "ref",
                    "x-kubernetes-patch-strategy": "merge"
                },
```

and put this into the `kustomization.yaml`:
```yaml
...
openapi:
  path: schema.json
```

though I don't know if this is a "proper" way to do so. Anyway that works :)
