### DISCUSSION TITLE
OutOfSync Resourses excluded for VmServiceScrapes

### DISCUSSION THREAD

**Discussion by virtualb0x** [argoproj/argo-cd#15576] [Q&A]
Hello.

I have a k8s cluster with VictoriaMetrics installed as a monitoring tool. Also there is an ArgoCD inside. VictoriaMetrics used to generate VMServiceScrape kinds CRDs, which are based on ServiceMonitors of Prometheus and which are necessary for metrics to be present.

This resource is generated automatically and is present in k8s cluster, but it will never appear in git, only if user put it to fit manually which is not good idea.

So, ArgoCD tells me that my application is out of sync.

![image](https://github.com/argoproj/argo-cd/assets/68299651/664c50e7-fd62-4e76-aa61-f7dda92b7edb)

In the documentation I've read that I can exclude some resources from diff/sync: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion

I've made changes to configmap:
```
apiVersion: v1
data:
  dex.config: |-
    logger:
      level: debug
    connectors:
<ommited>
  resource.exclusions: |-
    - apiGroups:
      - "*"
      kinds:
      - "VMServiceScrape"
      clusters:
      - https://kubernetes.default.svc
  url: https://argocd-test.url.bla
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd

```

I applied it to argocd. Synced the app, it says that resource is ignored
![image](https://github.com/argoproj/argo-cd/assets/68299651/ea2b03fb-0314-49f2-803e-799f0bf73756)

But the app still is out of sync and diff shows the resource
![image](https://github.com/argoproj/argo-cd/assets/68299651/1550d018-5166-46f6-9cec-37c6602dd867)

![image](https://github.com/argoproj/argo-cd/assets/68299651/799f8cbc-2f53-4228-9517-e96e656a16fa)

Can anybody tell me if it is expected behavior or how can I make an app to be not OutOfSync in such a situation?
