### DISCUSSION TITLE
Conflicts when creating a App via Pull Request Generator

### DISCUSSION THREAD

**Discussion by lifeofmoo** [argoproj/argo-cd#15600] [Q&A] [answered]
**ArgoCD Version: v2.7.3**

Hello, 

I would like to generate a new application from an existing application in ArgoCD based on pull requests.

My setup:

Two GitHub repos ([as per Argo Best practices](https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/#separating-config-vs-source-code-repositories))

* nextjs-docker - App Code with GitHub Actions (GHA) to build and Push to ECR, the final step is to checkout the _eks repo below and update the image tag
* nextjs-docker_eks - K8s yaml files (Kustomize). Apps in Argo are built with this Repo connected.

In Argo I have two apps deployed in the default project:

nextjs
nextjs-docker-ingress (just a tiny argo app to managed to the alb ingress)

> nextjs-docker_eks/nextjs-docker$ tree
.
├── nextjs-docker
│   ├── ingress-and-svcs
│   │   ├── base
│   │   │   ├── kustomization.yaml
│   │   │   └── nextjs-docker.yaml
│   │   └── overlays
│   │       └── dev
│   │           ├── ingress.yaml
│   │           └── kustomization.yaml
│   ├── kustomize
│   │   ├── base
│   │   │   ├── deployment.yaml
│   │   │   ├── kustomization.yaml
│   │   │   ├── serviceaccount.yaml
│   │   │   └── service.yaml
│   │   └── overlays
│   │       └── dev
│   │           ├── application-set.yaml
│   │           ├── args.yaml
│   │           ├── deployment.yaml
│   │           ├── env.yaml
│   │           └── kustomization.yaml
└── README.md

The ApplicationSet applied to argocd namespace is:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name:  nextjs-docker-preview
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: My-Ltd
        # The Github repository
        repo: nextjs-docker
        appSecretName: creds-xxxxxx
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - preview
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'nextjs-docker-{{branch}}-{{number}}'
      namespace: argocd
    spec:
      source:
        repoURL: 'https://github.com/My-Ltd/nextjs-docker_eks'
        # targetRevision: '{{head_sha}}'
        path: nextjs-docker/kustomize/overlays/dev
        kustomize:
          images:
          - xxxxxx.dkr.ecr.eu-west-1.amazonaws.com/nextjs-docker:1.0.27
      project: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: nextjs-{{branch}}-{{number}}

```

Note: the image is currently hard coded to 1.0.27 for testing purposes- will revert back to short_sha when I've changed the build steps in GHA 

When I apply the AppSet a new app **does** get created (nextjs-docker-argo-1) but it's not being created in it's own Namespace and then Argo complains about shared resources

> 
> SharedResourceWarning
> Deployment/nextjs-docker is part of applications argocd/nextjs and nextjs-docker-argo-1
> a few seconds ago (Wed Sep 20 2023 15:57:49 GMT+0100)
> SharedResourceWarning
> Service/nextjs-docker is part of applications argocd/nextjs and nextjs-docker-argo-1
> a few seconds ago (Wed Sep 20 2023 15:57:49 GMT+0100)
> SharedResourceWarning
> ServiceAccount/nextjs-docker is part of applications argocd/nextjs and nextjs-docker-argo-1
> a few seconds ago (Wed Sep 20 2023 15:57:49 GMT+0100)
> 

This is the fully rendered existing kustomize app.

```
nextjs-docker_eks/nextjs-docker/kustomize/overlays/dev$ k kustomize 

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nextjs-docker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nextjs-docker
    costcentre: operations
    project: nextjs-docker
    team: platform
  name: nextjs-docker
  namespace: nextjs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextjs-docker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nextjs-docker
    costcentre: operations
    project: nextjs-docker
    team: platform
  name: nextjs-docker
  namespace: nextjs
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nextjs-docker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nextjs-docker
    costcentre: operations
    project: nextjs-docker
    team: platform
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs-docker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nextjs-docker
    costcentre: operations
    project: nextjs-docker
    team: platform
  name: nextjs-docker
  namespace: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-docker
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: nextjs-docker
      costcentre: operations
      project: nextjs-docker
      team: platform
  template:
    metadata:
      labels:
        app: nextjs-docker
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: nextjs-docker
        costcentre: operations
        project: nextjs-docker
        team: platform
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nextjs-docker
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containers:
      - args:
        - start
        - --require ./tracer.js
        - --prefix
        command:
        - npm
        env:
        <redacted>
        image: xxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/nextjs-docker:1.0.25
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        name: nextjs-docker
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          tcpSocket:
            port: 8080
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - mountPath: /opt/appdynamics
          name: appd-agent-repo
      serviceAccountName: nextjs-docker
      volumes:
      - emptyDir: {}
        name: appd-agent-repo
```
