### DISCUSSION TITLE
Is it possible that argocd will sync a application from multiple branches of same Github repo.

### DISCUSSION THREAD

**Discussion by Shindek77** [argoproj/argo-cd#15650] [Q&A]
Actually I have git repo in which helm chart for Grafana is present and also I have deployed it on my cluster from main branch using tragetRevision: HEAD. Then I made any changes to main branch which is default one argoCD is syncing and deploying. But I want that if developers will create multiple feature branches and push some changes it should sync that also. Means application should sync from multiple branches. Is it possible in argoCD if yes then what is configuration for it?. Please help as its urgent for me. 

application.yaml:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: grafana-test
    server: https://kubernetes.default.svc
  sources:
  - path: .
    repoURL: https://github.com/my-org/argocd-grafana-dev.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  project: dev-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/metadata/annotations
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /spec/metrics
```
