### DISCUSSION TITLE
IgnoreDifferences is not working with RespectIgnoreDifferences true value in argo 2.5.2

### DISCUSSION THREAD

**Discussion by ajaydevtron** [argoproj/argo-cd#15651] [General]
Hello Team,

It has been a great project, and we have been using it for three years now.

I have a use case where I have an Argo application, and I am sharing the manifests below. We do not want to trigger a deployment/rollout synchronization if we change the **replicaCount** in the spec of a Deployment or a Rollout (Custom Resource Definition - CRD).

**Argo application manifest**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-application
  namespace: demo
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/replicas
  source:
    helm:
      valueFiles:
        - _1-values.yaml
    path: deployment-chart_4-18-0/4.18.1
    repoURL: https://github.com/test-org/test-2023.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - RespectIgnoreDifferences=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5s
      limit: 1
```

However, it consistently syncs the Deployment and Rollout manifests, and the IgnoreDifferences configuration is not functioning as we expected.

I have reviewed the documentation provided in the link below:
https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs.

I have gone through below open issue  but I haven't found a precise solution to address my concerns.
https://github.com/argoproj/argo-cd/issues/9678

Could I be overlooking something in the Argo application? Thank you for any assistance and suggestions.
