### DISCUSSION TITLE
ApplicationSet: Matrix Generator creating Argo Application when "app path does not exist"

### DISCUSSION THREAD

**Discussion by KevinBonilla** [argoproj/argo-cd#15717] [General]
Using Git Directory generator + Cluster generator I am encountering an issue where Argo generates an application for a subfolder that does not exist.

Git configuration:
```
└── <my-application> 
     └── dev
           ├── Chart.yaml
           ├── requirements.yaml
           └── values.yaml
```

I have 2 clusters `dev` and `qa` configured. In this example here I have not defined `qa` subfolder but Argo still generates the unwanted application.
```
my-application-dev                          Synced        Healthy
my-application-qa                            Unknown     Healthy
```

My applicationset:
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/my-profile/helm-charts.git
              revision: HEAD
              directories:
                - path: "my-*"
                  exclude: true
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}-{{name}}' # Example path is: my-application/dev/*
    spec:
      project: "project"
      source:
        repoURL:  https://github.com/my-profile/helm-charts.git
        targetRevision: HEAD
        path: '{{path}}/{{metadata.labels.environment}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{server}}'
        namespace: '{{metadata.labels.environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
The error shown is:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): my-application/qa: app path does not exist
```

My understanding was that argo will only create the application when the subfolder exists. I suspect if I add other clusters it will create argo applications for the upper environments even though I did not define the subfolder.

Do I need to change how I define my applicationsets? Any help on this question would be greatly appreciated. Thank you!
