### DISCUSSION TITLE
IgnoreExtraneous annotations doesn't help to change sync status

### DISCUSSION THREAD

**Discussion by Demmyart** [argoproj/argo-cd#15726] [Q&A]
Good day, I am using ArgoCD version **v2.8.4+c279299**. The thing is that I have shared externalsecret resource which is used by several application and each application is trying to put a unique label on that. So, I'm getting OutOfSync status for this resource as well as OutOfSync status on the application itself. I've tried to use the block below on the application level, it didn't help
```
      ignoreDifferences:
        - kind: ExternalSecret
          jsonPointers:
            - /metadata/labels
```

After that I've tried to use annotations, but result is the same, the resource itself is in OutOfSync status as well as application status. What I am doing wrong?
```
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false````
