### DISCUSSION TITLE
Gitlab Pull Request Generator + SCM provider

### DISCUSSION THREAD

**Discussion by Demmyart** [argoproj/argo-cd#15787] [Q&A]
I am trying to use a matrix generator with a pull request generator and SCM provider. For now, I just create multiple appsets on each repository which is not convenient.

1. The scmProvider generates `repository` variable which is the name of the repository.
2. GitLab PR generator expects `project id`, as it uses the `/api/v4/project/<project id>/merge_requests`
3. So, I am getting an error
`time="2023-07-19T14:44:14Z" level=error msg="error generating params" error="error listing repos: error listing merge requests for project example-app': GET https://mygit.com/api/v4/projects/example-app/merge_requests: 404 {message: 404 Project Not Found}" generator="&{0xc0004f7db0 0x2472e00 {0xc0003a2060}}"`

```  
- matrix:
              generators:
                - scmProvider:
                    gitlab:
                      group: '34' 
                      api:
                      allBranches: true
                      includeSubgroups: false
                      tokenRef:
                        secretName: 
                        key: password
                    filters:
                      - pathsExist: [charts]
                - pullRequest:
                    gitlab:
                      project: '{{ repository }}' ## here is the problem
                      api: 
                      tokenRef:
                        secretName: 
                        key:
                      labels:
                      - infrastructure
                      pullRequestState: opened
                    requeueAfterSeconds: 180
```
