### DISCUSSION TITLE
Pull request generator - Multiple repositories

### DISCUSSION THREAD

**Discussion by rafaeljusto** [argoproj/argo-cd#15803] [Q&A] [answered]
Hi,

Is there a way to know the repository that triggered the pull request generator when there are multiple options?

For example:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: org
        repo: repo1
  - pullRequest:
      github:
        owner: org
        repo: repo2
  template:
    metadata:
      name: 'app'
    spec:
      source:
        repoURL: ...
        targetRevision: HEAD
        helm:
          parameters:
          - name: "source_repo"
            value: "{{repo}}" # ← Here!
```

I would like to know inside the template if `repo1` or `repo2` triggered the action. From the available variables doesn't look like it's possible (reference below) but maybe there's another way to retrieve this info?

https://github.com/argoproj/argo-cd/blob/357972e8039bef8442e7dc96ad546981f0ac6b57/applicationset/generators/pull_request.go#L103-L110
