### DISCUSSION TITLE
Not auto sync after image tag is updated.

### DISCUSSION THREAD

**Discussion by ostgardh** [argoproj/argo-cd#15829] [General]
I have Application that is sync to my git repo.
Syncpolicy is on with prund and selfheal enable.

If I change in my git , the values.yaml , tag image version 1.0 > 1.2 nothing happens in argo or in k8s.
I can see that "Sync Status" / "Last Sync" commit id in not same.

But I want Argo to push / install the new image version 1.2 pod automated after sync.
I have to press sync in web gui.

I have find that if I change to version 1.2 and replicaCount from 2 > 3 argo will auto sync and install 3 pod with vesion 3.

How can I get argo auto sync and install new image if version is change in git repo?

My app file.yaml....
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Test
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-namespace
    server: https://kubernetes.default.svc
  project: myproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: pathtomyapp
    repoURL: https://myserver/apps-helmcharts.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - test-values.yaml
```
