### DISCUSSION TITLE
May can I pass values from application to applicationset?

### DISCUSSION THREAD

**Discussion by AndreCbrera** [argoproj/argo-cd#15827] [Q&A]
We are trying to pass varibles from application to applicationset.

Escenario:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc
  namespace: argocd
  labels:
    group: poc
spec:
  project: default
  sources:
  - repoURL: https://selfhosted.repo.git
    targetRevision: feat/testapp
    ref: values
  - repoURL: https://selfhosted.chart.repo/
    targetRevision: "0.0.1"
    chart: applicationset-poc
    helm:
      valueFiles:
        - $values/values/static/values.yaml
      values: |
          app:
            ingress:
              enabled: true
              hosts:
                host: $URL
              tls: 
                hosts: $URL
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
```
To this ApplicationSet:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappsetpoc
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: apptestpoc
                  chartName: chartname
                  chartUrl: https://selfhosted.chart.repo/
                  repoUrl: https://selfhosted.repo.git
                  revision:  feat/testapp
              elements:
                - namespace: argocd
                  projectName: default
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: default
      sources:
      - repoURL: '{{.chartUrl}}'
        chart: '{{.chartName}}'
        targetRevision: '*'
        helm:
          valueFiles:
          - $values/values/dynamic/values.yaml
          values: |
            app:
              ingress:
                enabled: true
                hosts:
                  host: $URL
                tls: 
                  hosts: $URL
      - repoURL: '{{.repoUrl}}'
        targetRevision: '{{.revision}}'
        ref: values
      destination:
        server: 'https://server'
        namespace: ""
      syncPolicy:
        automated:  
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
```

We use applications over application to encapsulate the applications that are created in applicationset.

to achieve this we execute the following command:

`envsubst '$URL' < /application.yaml | k apply -f -
`
the result is this in the aplpication yaml:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oralbpoc
  namespace: argocd
  labels:
    group: oralbpoc
spec:
  project: default
  sources:
  - repoURL: https://selfhosted.repo.git
    targetRevision: feat/testapp
    ref: values
  - repoURL: https://selfhosted.chart.repo/
    targetRevision: "0.0.1"
    chart: applicationset-poc
    helm:
      valueFiles:
        - $values/values/static/values.yaml
      values: |
          app:
            ingress:
              enabled: true
              hosts:
                host: testdns.selfhosted.com
              tls: 
                hosts:  testdns.selfhosted.com
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
```

thanks
