### DISCUSSION TITLE
how do I set up argo-cd-rbac-cm using github sso, without a github org?

### DISCUSSION THREAD

**Discussion by gwynforthewyn** [argoproj/argo-cd#15979] [Q&A] [answered]
Hey -

I've spent a couple of hours trying to get the syntax correct for setting up the argocd-rbac-cm configmap for a user that doesn't have a github org, and I'm stumped; I'm hoping you all have some ideas.

My argocd-dex-server logs show this json for my user account:

`time="2023-10-15T23:00:24Z" level=info msg="login successful: connector \"github\", username=\"Gwyn\", preferred_username=\"gwynforthewyn\", email=\"<my email address>\", groups=[]"`

The rbac policy I was using looked like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: "argocd"
  labels:
    helm.sh/chart: argo-cd-5.31.0
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
data:
   policy.csv: |
     g, gwynforthewyn, role:admin
  policy.default: ""
    scopes: '[groups]'
```

However, the policy default was being applied, not the admin role. All the examples I see of these policies show an expectation that you can supply `github-org:username`, but in this case that's not applicable.

Any chance you all have an idea what to do?

Thanks

Gwyn

**Comment by SeyOr** [comment, marked as answer]
You need to state org-name inside connector config - so ArgoCD will pick up full info on user

    # Dex configuration
    # dex.config: |
    #   connectors:
    #     # GitHub example
    #     - type: github
    #       id: github
    #       name: GitHub
    #       config:
    #         clientID: aabbccddeeff00112233
    #         clientSecret: $dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
    #         orgs:                                 <-----
    #         - name: your-github-org <-----

**Reply by gwynforthewyn** [reply]
Not the news I hoped for, but I appreciate the answer. Thank you!

**Reply by mihaigalos** [reply]
What would that `name: your-github-org` be in this case? `name: github.com/gwynforthewyn`?
To be specific: the usecase in the original question was about using github SSO without having an organization.
Like, if you have a kubernetes cluster at home and a simple public github user.

What about argocd-rbac-cm.data.policy.csv, what form would that have?

**Reply by mihaigalos** [reply]
@gwynforthewyn, can you please post your `argocd-cm` and `argocd-rbac-cm`? Thank you loads!

**Reply by gwynforthewyn** [reply]
Github orgs aren't personal accounts, so the answer as I understood it was that I cannot use this feature without a github org.

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations

In https://github.com/gwynforthewyn/homekubernetescluster/blob/main/kubernetes-setup/argo-cd/skaffold.yaml you can see my argocd configuration using my github org, playtechnique. The rbac policy I have is super simple, it just sets me as role:admin; it's in skaffold.yaml too.

**Reply by mihaigalos** [reply]
> Github orgs aren't personal accounts, so the answer as I understood it was that I cannot use this feature without a github org.
> 
> 
> 
> https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations
> 
> 
> 
> In https://github.com/gwynforthewyn/homekubernetescluster/blob/main/kubernetes-setup/argo-cd/skaffold.yaml you can see my argocd configuration using my github org, playtechnique. The rbac policy I have is super simple, it just sets me as role:admin; it's in skaffold.yaml too.

Thanks. The link to your repo doesn't work. I've added a slash before homekubernetescluster, still nothing. Is it a private repo?

**Reply by gwynforthewyn** [reply]
Oh, apparently it is, yes. Here’s the relevant bit. Note that it’s written in skaffold and is providing values to a helm chart, so the syntax is a little weird:

```
configs.cm.url: https://argocd.playtechnique.io
                        configs.cm.dex\.config: |
                            connectors:
                              # GitHub example
                              - type: github
                                id: github
                                name: GitHub
                                config:
                                  clientID: <the client id >
                                  clientSecret: $github-client:client-secret #this is an format that the helm chart parses to reference a secret in Kubernetes
                                  orgs:
                                  - name: playtechnique
                        configs.rbac.policy\.default: role:admin
                        configs.cm.admin\.enabled: false 
```

**Reply by mihaigalos** [reply]
Thanks a lot for the answer. I've created an oganization (galosone) and a team in it (one).
Here's my ConfigMaps:

```yaml
apiVersion: v1
data:
  policy.csv: |
    g, galosone:one, role:admin
  policy.default: role:admin
  scopes: '[groups, email]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
```

```yaml
apiVersion: v1
data:
  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $argocd-oidc-secret:clientID
          clientSecret: $argocd-oidc-secret:clientSecret
        orgs:
          - name: galosone
  url: https://cloud.galos.one
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
```

The `cloud.galos.one` has a Cloudflare A-Record to a private LAN IP.

Clicking on the Login with GitHub button in ArgoCD waits a bit, then shows the same page again.

I'm pretty sure I've set the secrets correctly, because the login actually succeeds in the dex pod:
```bash
$ kubectl logs -n argocd argocd-dex-server-77d466cb67-xqvt8

time="2024-02-13T16:24:00Z" level=info msg="login successful: connector \"github\", username=\"Mihai Galos\", preferred_username=\"mihaigalos\", email=\"mihai@galos.one\", groups=[]"
time="2024-02-13T16:24:03Z" level=info msg="login successful: connector \"github\", username=\"Mihai Galos\", preferred_username=\"mihaigalos\", email=\"mihai@galos.one\", groups=[]"
time="2024-02-13T16:24:11Z" level=info msg="login successful: connector \"github\", username=\"Mihai Galos\", preferred_username=\"mihaigalos\", email=\"mihai@galos.one\", groups=[]"
time="2024-02-13T16:27:51Z" level=error msg="Invalid 'state' parameter provided: not found"
time="2024-02-13T16:28:37Z" level=info msg="login successful: connector \"github\", username=\"Mihai Galos\", preferred_username=\"mihaigalos\", email=\"mihai@galos.one\", groups=[]"
time="2024-02-13T16:31:09Z" level=info msg="Notifying 1 settings subscribers: [0x40002f66c0]"
time="2024-02-13T16:31:09Z" level=info msg="dex config unmodified"
```
Any help here will be greatly appreciated! 😄
