### DISCUSSION TITLE
ArgoCD single source application recognized as a multisource

### DISCUSSION THREAD

**Discussion by sciffer** [argoproj/argo-cd#15999] [General]
OK, so playing around with ArgoCD v2.8.4+c279299 and noticed the following:
got this standard Vault helm chart application that looks like this(pulled the manifest from ArgoCD UI, to make sure ArgoCD see what I pushed with kubectl):

```
project: argo-project
destination:
  server: 'https://kubernetes.default.svc'
  namespace: vault
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
revisionHistoryLimit: 10
sources:
  - repoURL: 'git@github.com:xxxxx/argo-master'
    path: vault
    targetRevision: HEAD
```

Yet, in ArgoCD UI next to info or History and Rollback button it says not supported for apps with multiple sources - clearly, there is only one source in the manifest unless ArgoCD calls something else sources(which is probably a misunderstanding from my side)
What am I missing here? Will appreciate any help..
