### DISCUSSION TITLE
How to set a service type in helm instllation?

### DISCUSSION THREAD

**Discussion by uday1kiran** [argoproj/argo-cd#16014] [Q&A]
I am trying to install istio gateway helmchart as an applicationset in argo.

So, tried below entry as parameter but not working.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: product-cc-cleanparam
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/company-platform/product-mart-infra.git
        revision: "queensraildemo_fntesting_istio"
        files:
          - path: "config/argocd-config/application-config/dev/**/cleanparam-helmconfig.json"
  template:
    metadata:
      name: "{{name}}"
    spec:
      destination:
        namespace: "{{destination.namespace}}"
        server: "https://kubernetes.default.svc"
      source:
        repoURL: "{{source.repourl}}"
        targetRevision: "{{source.revision}}"
        chart: "{{source.chart}}"
        helm:
          parameters:
            values: |
              service:
                type: ClusterIP
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: cert-manager-webhook
          jqPathExpressions:
            - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      project: product
```

Please suggest how to do that?

If I don't pass any parameter, it is getting instlalled as LoadBalancer, I want to set it as ClusterIP.

The error:

`date\",\"reason\":\"ApplicationSetUpToDate\",\"status\":\"True\",\"type\":\"ResourcesUpToDate\"}]}}": strict decoding error: unknown field "spec.template.spec.source.helm.parameters.values"`
