### DISCUSSION TITLE
Problem with Helm value files from external Git repository

### DISCUSSION THREAD

**Discussion by ShyunnY** [argoproj/argo-cd#16147] [Q&A]
When I use multiple sources to provide values for the helm chart in the ArgoCD application, why do I keep getting the following error?
```shell
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = failed to get git client for repo   
<my git repo url>
```

Below is my config file：

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-argo-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: <my charts repo url>
      targetRevision: 0.0.8
      chart: policy
      helm:
        releaseName: cluster-policy-chart
        valueFiles:
          - $values/charts/values/policy.yaml
        valuesObject:
          imageInfo:
            name: "nginx:1.14.1"
    - repoURL: <my git repo url>
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

```

The path to the policy.yaml file is located at: `/charts/values/policy.yaml`
