### DISCUSSION TITLE
ApplicationSet GoTemplating

### DISCUSSION THREAD

**Discussion by mceroni-hl** [argoproj/argo-cd#16218] [Q&A]
I am trying to enable templating in my ApplicationSet as documented here: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/

Prior to setting `goTemplate: true` I had the following working applicationSet.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appName
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - values.cluster
        generators:
          - git:
              repoURL: git@bitbucket.org:xxxxxx
              revision: HEAD
              files:
                - path: env/*.yaml
              values:
                cluster: '{{ cluster }}'
          - clusters:
              values:
                cluster: '{{ name }}'
  template:
    metadata:
      name: 'appName-{{ name }}'
    spec:
      project: default
      sources:
        - repoURL: git@bitbucket.org:xxxxx/-service.git
          path: .
          targetRevision: 1.6.3
          helm:
            valueFiles:
              - $values/default.yaml
              - $values/env/{{ cluster }}.yaml
        - repoURL: git@bitbucket.org:xxxxxx
          targetRevision: HEAD
          ref: values
      destination:
        namespace: {{ namespace }}
        server: '{{ server }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - ApplyOutofSyncOnly=true
          - CreateNamespace=true
```

Files in `env` are YAML files (e.g: prod.yaml and stage.yaml). They are merged with the cluster and used to generate the applications. In this case we get an app named `appName-stage` and `appName-prod`.

My need to template is that I am hoping to be able to take parameter from Git file generator `{{path.basename}}`, which in my case will be `prod.yaml` or `stage.yaml` and remove the extension, so something like:

```
  template:
    metadata:
      name: 'appName-{{ path.basename | trimSuffix ".yaml" }}'
```

Prior to attempting that I enabled `goTemplate: true`, rewrote all my variable calls to be as documented in the link above. And ended up with

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appName
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - .values.cluster
        generators:
          - git:
              repoURL: git@bitbucket.org:xxxxxx
              revision: HEAD
              files:
                - path: env/*.yaml
              values:
                cluster: '{{ .cluster }}'
          - clusters:
              values:
                cluster: '{{ .name }}'
  template:
    metadata:
      name: 'appName-{{ .name }}'
    spec:
      project: default
      sources:
        - repoURL: git@bitbucket.org:xxxxx/-service.git
          path: .
          targetRevision: 1.6.3
          helm:
            valueFiles:
              - $values/default.yaml
              - $values/env/{{ .cluster }}.yaml
        - repoURL: git@bitbucket.org:xxxxxx
          targetRevision: HEAD
          ref: values
      destination:
        namespace: {{ .namespace }}
        server: '{{ .server }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - ApplyOutofSyncOnly=true
          - CreateNamespace=true
```

However when applying this it errors for duplicate mergeKeys as `.values.cluster` (also tried just `values.cluster`) ends up being `null`.
