### DISCUSSION TITLE
When using Flagger for Canary the Application sync completes before the canary completes

### DISCUSSION THREAD

**Discussion by gdix0n** [argoproj/argo-cd#16247] [Q&A]
I'm seeing a strange issue when using ArgoCD when I release a new version of a service the sync seems to complete instantly once it has incremented the image in the deployment. The sync shows as completed and begins the post-sync wave when the canary has yet to start. I presume this is happening as the canary is already in a completed state from the previous canary run based off the lua script [here](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/flagger.app/Canary/health.lua).

Is anyone else using Flagger with ArgoCD and seeing the same issue?

**Comment by WillPlatnick-S1** [comment]
@gdix0n I haven't hooked up Flagger to ArgoCD myself yet (I will be soon), but what you're saying sounds incredibly likely. When I've used Flagger in the past, there's a delay between when you change the object, and when the release process starts while Flagger is fully reconciling that it has work to do. So, if it's done immediately after applying, it's going to still be in a succeeded state from the previous canary rollout, because flagger hasn't fully formed that there's new work to do.

In my previous logic checking when implementing flagger, I had to do something like this to keep checking until the rollout progressed.

    until ${ok}; do
      kubectl get $item -n "$KUBE_NAMESPACE" | grep 'Progressing' && ok=true || ok=false
      sleep 5
    done


Then, once it started, I monitored the object:

    # wait for the canary analysis to finish
    echo "Your release is getting canaried. Waiting for it to succeed."
    kubectl wait $item -n "$KUBE_NAMESPACE" --for=condition=promoted --timeout=5m || timeout=true

I'm not sure how to do something similar in ArgoCD with the way the lua scripts seem to work.

**Reply by crenshaw-dev** [reply]
I wonder if the Flagger status field contains something we could compare (in the Lua script) to the spec to determine whether the shown status reflects the current deployment or the previous deployment.

**Comment by WillPlatnick-S1** [comment]
Hi @crenshaw-dev 

I just started working on this. Here's what I've gathered up.

To kick off a canary deployment in Flagger, we essentially make a change to a Deployment manifest that is scaled down to 0. Flagger then notices that this deployment changed, and starts bringing up canaries with the new config. It took 15 seconds from when my deployment changed, to when Flagger noticed the change, and started the promotion process.  To check the status of the canary deployment, there is a Canary object that has Kubernetes Events emitted to it with status updates.

That 15 second gap between when the change to the Deployment is made, to when Flagger notices and starts updating the status of the Canary object I think is really the cause of our issues here.

I'm hardly an expert in ArgoCD health checks. Is there anything we can do at the ArgoCD health check level to make this better?  I'm not seeing anything in the Deployment itself that we could link to Flagger object for the health check.

Here's some example statuses that are emitted by the Canary object.

After initial deployment of first canary object

```
status:
  canaryWeight: 0
  conditions:
  - lastTransitionTime: "2024-03-12T15:08:44Z"
    lastUpdateTime: "2024-03-12T15:08:44Z"
    message: Deployment initialization completed.
    reason: Initialized
    status: "True"
    type: Promoted
  failedChecks: 0
  iterations: 0
  lastAppliedSpec: 69ffb47bbb
  lastPromotedSpec: 69ffb47bbb
  lastTransitionTime: "2024-03-12T15:08:44Z"
  phase: Initialized
  trackedConfigs: {}
```

While promoting

```
status:
  canaryWeight: 10
  conditions:
  - lastTransitionTime: "2024-03-13T14:15:14Z"
    lastUpdateTime: "2024-03-13T14:15:14Z"
    message: New revision detected, progressing canary analysis.
    reason: Progressing
    status: Unknown
    type: Promoted
  failedChecks: 1
  iterations: 0
  lastAppliedSpec: "5587594458"
  lastPromotedSpec: 69ffb47bbb
  lastTransitionTime: "2024-03-13T14:16:14Z"
  phase: Progressing
  trackedConfigs: {}
```

Finalizing

```
status:
  canaryWeight: 0
  conditions:
  - lastTransitionTime: "2024-03-13T14:15:14Z"
    lastUpdateTime: "2024-03-13T14:19:14Z"
    message: Canary analysis completed, routing all traffic to primary.
    reason: Finalising
    status: Unknown
    type: Promoted
  failedChecks: 1
  iterations: 0
  lastAppliedSpec: "5587594458"
  lastPromotedSpec: 69ffb47bbb
  lastTransitionTime: "2024-03-13T14:19:14Z"
  phase: Finalising
  trackedConfigs: {}
```

Success

```
status:
  canaryWeight: 0
  conditions:
  - lastTransitionTime: "2024-03-13T14:19:44Z"
    lastUpdateTime: "2024-03-13T14:19:44Z"
    message: Canary analysis completed successfully, promotion finished.
    reason: Succeeded
    status: "True"
    type: Promoted
  failedChecks: 1
  iterations: 0
  lastAppliedSpec: "5587594458"
  lastPromotedSpec: "5587594458"
  lastTransitionTime: "2024-03-13T14:19:44Z"
  phase: Succeeded
  trackedConfigs: {}
```

Promotion Failure

```
status:
  canaryWeight: 0
  conditions:
  - lastTransitionTime: "2024-03-13T14:31:44Z"
    lastUpdateTime: "2024-03-13T14:31:44Z"
    message: Canary analysis failed, Deployment scaled to zero.
    reason: Failed
    status: "False"
    type: Promoted
  failedChecks: 0
  iterations: 0
  lastAppliedSpec: "5587594458"
  lastPromotedSpec: 69ffb47bbb
  lastTransitionTime: "2024-03-13T14:36:14Z"
  phase: Failed
  trackedConfigs: {}
```
