### DISCUSSION TITLE
argocd - field is immutable after hard refresh and sync prune

### DISCUSSION THREAD

**Discussion by milank78git** [argoproj/argo-cd#16301] [Q&A]
I have question.

I create job 

```
{{- define "jobYamlSuccess" }}
{{- $jobNameSuccess := printf "postdeployment-success%s" .jobSuffix }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobNameSuccess }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    argocd.argoproj.io/sync-options: Validate=false, ApplyOutOfSyncOnly=true, Delete=false
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    metadata:
      name: {{ $jobNameSuccess }}
    spec:
      imagePullSecrets:
        - name: docker
      containers:
        - name: {{ $jobNameSuccess }}
  {{- end }}
{{- $jobSuffix := .Chart.Name | sha256sum | trunc 5 }}
{{- include "jobYamlSuccess" (dict "root" $ "jobSuffix" $jobSuffix "uid" .uid) }}
          image: curl:7.81.0
          args:
            - /bin/sh
            - -c
            - |
              curl -k -X POST {{ include "url" . }}  -d 'environment={{ .Values.environment }},component=test-sample,application=test,deployment_target="" status="1" }}' --connect-timeout 10 || exit 0
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
      restartPolicy: Never
  backoffLimit: 0
```
Job is created on first deployment in ArgoCD 

If I call sync prune ArgoCD does not make any change,  but if I call hard-refresh and then sync prune Job is deleted and error status sync . 
I don't understand why 
`
Job.batch "postdeployment-successc2bc2" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"postdeployment-successc2bc2", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(0xc01e10cb88), Labels:map[string]string{"controller-uid":"51577aaf-d277-4c87-a018-f6dd16bce3ef", "job-name":"postdeployment-dora-successc2bc2"}, Annotations:map[string]string{"sidecar.istio.io/inject":"false"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"postdeployment-successc2bc2", Image:"curl:7.81.0", Command:[]string(nil), Args:[]string{"/bin/sh", "-c", "curl -k -X POST https://test.com/write -d 'environment=example,component=test-sample,application=test,deployment_target=\"\" status=\"1\"' --connect-timeout 10 || exit 0\n"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:100, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"100m", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:67108864, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}}, Requests:core.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:100, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"100m", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:67108864, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}}}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc01ef9a4e0), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc01e10cbe0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc0085cc5a0), ImagePullSecrets:[]core.LocalObjectReference core.LocalObjectReference{Name:"docker"}}, Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil), OS:(*core.PodOS)(nil)}}: field is immutable
`
My argoCD 2.6.6
