### DISCUSSION TITLE
Helm values not getting applied to template

### DISCUSSION THREAD

**Discussion by reisman234** [argoproj/argo-cd#16356] [Q&A] [answered]
I have a problem by deploying an application which is referenced as a helm chart. It looks like that parameters from the values file aren't properly expanded into the final manifest, which leads to missing resources.

The application is a gitlab-runner, which is in fact very simple, it just requires the `gitlabUrl`, a `runnerToken` and the `rbac` to be created. This deployment did already work in a previous run via an `helm install ...` instruction.
Now to set up everything for argocd, I created a repo with the following Chart.yaml and the default values.yaml, in which I set the required 3 options. To deploy the app via argocd, the web UI was used. In that wizard and after the input of the git repo, I get suggestions for the path, and a values file to use.  Furthermore, all the parameters from values.yaml have already been listed. After the application has been created and synchronised, I can see how a pod and a config map are created, but important resources are missing during deployment, which leads to errors in the gitlab-runner pod. For example, a secret for the runnerToken and a ServiceAccount should be created. As described at the beginning, it looks like the specified parameters from the values file are not expanded into the final manifest, which means that resources are missing.

For simplicity and first testing purpose of argocd, I just used the installation instructions from the getting started guide. (Version 2.8.4 )

```
apiVersion: v2
name: gitlab-runner
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.0"

dependencies:
- name: gitlab-runner
  version: 0.58.2
  repository: https://charts.gitlab.io/
```

This is the Application manifest created by the argo UI:

```
project: default
source:
  repoURL: 'REPO_GITLAB_RUNNER.git'
  path: .
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: test-gitlab-runner
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
```

**Comment by FernandoMiguel** [comment, marked as answer]
is your values.yaml properly indented and under `gitlab-runner:` ?

**Reply by reisman234** [reply]
:see_no_evil: of course i didn't see that in the [example](https://github.com/argoproj/argocd-example-apps/blob/master/helm-dependency/README.md).

**Comment by FernandoMiguel** [comment]
no worries. we have all been there before

**Comment by michaelcooke** [comment]
I'm going to make this even more painfully obvious to those poor souls who come after me, spending over an hour banging their head against the wall:

Your values need to go under a key named after the associated dependency (`.dependencies.[x].name`) defined in `Chart.yaml`.

Incorrect values.yaml
```yaml
gitlabUrl: '...'
...
```

Correct values.yaml
```yaml
gitlab-runner:
  gitlabUrl: '...'
  ...
```
