### DISCUSSION TITLE
Argocd show as out-of-sync on every push for auto-generate certs / password

### DISCUSSION THREAD

**Discussion by BialekA** [argoproj/argo-cd#16386] [Q&A]
Hey all,

We are using argocd to deploy our application from helmchart from git repo.
Part of the service are generating random password or self-signed certification for TLS.
When we are pushing a new change to any folder in the repo, argocd show the resrouce as out-of-sync, re-sync it and re-generate the password and certification.
Of course this cause an issue to every service that tried to connect to the db.

Example:
Kafka-bitnami helm chart with:
```
auth:
  interBrokerProtocol: tls
  controllerProtocol: tls
  clientProtocol: tls
  sasl:
    interBrokerMechanism: scram-sha-512
  tls:
    type: pem
    autoGenerated: true
```

And mongodb-bitnami helm chart with:
```
auth:
  enabled: true
```

This create the password / certs when first deploy the chart, but the issue is that it is regenerate them on every push.

For the moment we solve the issue by disabling the automated syncPolicy, but his means that on every change we need to manually sync the the selected services.

I am adding a screenshot of argocd example showing the 'out of sync' it get on kafka certs.

Anyone have some idea how can we solve this?
![diff](https://github.com/argoproj/argo-cd/assets/114257628/d43fa7ed-d0b4-440e-8817-ec714a8a04b4)
![diff-argo](https://github.com/argoproj/argo-cd/assets/114257628/37e27d36-86ba-4ac6-8b44-e15e18dd3d43)
