### DISCUSSION TITLE
Preserve Application generated by ApplicationSet

### DISCUSSION THREAD

**Discussion by zeusal** [argoproj/argo-cd#16436] [Q&A] [answered]
Hello, I have a question about the ApplicationSet and its parameter "preserveResourcesOnDeletion".

In my case I have a the following resources/structure:

```yaml
ApplicationSet
├── Seed Application
│   ├── Child Application
│   ├── Child Application
│   └── Child Application

```

With the following code:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: default
spec:
  syncPolicy:
    applicationsSync: create-only
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: <GIT>
      revision: master
      files:
      - path: "types/**/argocd.config.json"
      values:
        cluster_app: "{{path[1]}}"
  template:
    metadata:
      name: "{{appName}}-seed"
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      destination:
        name: '{{cluster}}'
        namespace: default
      project: default
      source:
        path: "{{cluster_app}}/seed/values.yaml"
        repoURL: {{ repoURL }}
        targetRevision: {{ targetRevision }}
```

With the above configuration/definition, it generates: a set of applications, "n" applications by types/**/argocd.config.json that exist and several applications defined in the values.yaml

But when I delete the "main" ApplicationSet with kubectl, the objects generated by the "childs" Applications are not deleted, but the Application "{{appName}}-seed" is deleted.

It is possible to prevent the Application that generates the ApplicationSet from being deleted?

What I am trying to reproduce is that in case of an accidental error of the ApplicationSet, the Application generated previously by this same one is not deleted.
