### DISCUSSION TITLE
argocd-application-controller high CPU with Traefik deployment

### DISCUSSION THREAD

**Discussion by Subbeh** [argoproj/argo-cd#16431] [Q&A]
I'm trying to deploy Traefik using its helm chart in an ArgoCD application, but as soon as it gets synched the argocd-application-controller pods jump to 100% CPU usage and stay there.

I have set the sync window to only allow manual syncs, so nothing should be updating.
Not sure what could be causing this. No other applications are causing this, and no other manifests are deployed with Traefik besides the helm chart.

From the of the argocd-application-controller, these entries appear multiple times per second:

```
time="2023-11-23T08:15:12Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=argocd/traefik
time="2023-11-23T08:15:12Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: traefik)" application=argocd/traefik
time="2023-11-23T08:15:12Z" level=info msg="getRepoObjs stats" application=argocd/traefik build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=11 unmarshal_ms=9 version_ms=1
time="2023-11-23T08:15:12Z" level=info msg="Sync prevented by sync window" application=argocd/traefik dedup_ms=0 diff_ms=29 git_ms=12 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0
time="2023-11-23T08:15:12Z" level=info msg="No status changes. Skipping patch" application=argocd/traefik
time="2023-11-23T08:15:12Z" level=info msg="Reconciliation completed" application=argocd/traefik dedup_ms=0 dest-name= dest-namespace=traefik dest-server="https://kubernetes.default.svc" diff_ms=29 fields.level=1 git_ms=12 health_ms=0 live_ms=0 patch_ms=0 setop_ms=0 settings_ms=0 sync_ms=0 time_ms=56
```

This is the application manifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: traefik
  namespace: argocd
spec:
  source:
    repoURL: https://repo/infra/homelab.git
    path: k8s/resources/traefik
    targetRevision: main
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
```

the kustomization.yaml file in k8s/resources/traefik:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 24.0.0
    valuesFile: values.yaml
    namespace: traefik
    includeCRDs: false
    releaseName: traefik
```

The following has been added to `argocd-cm`, but does not seem to make any difference:
```
data:
  ignoreResourceUpdatesEnabled: "true"
```
