### DISCUSSION TITLE
ArgoCD ApplicationSets (With pullRequest Generator enabled) Kustomize patch values

### DISCUSSION THREAD

**Discussion by RajithaA97** [argoproj/argo-cd#16475] [Q&A]
We're using ArgoCD `ApplicationSets` to spin up new preview-environments whenever the users open a new Merge Request. Here's how the ApplicationSet looks like.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environment
spec:
  generators:
  - pullRequest:
      gitlab:
        project: custom-rest-api
        api: url-of-our-gitlab-repo
        tokenRef:
          key: token
          secretName: gitlab-token
        pullRequestState: opened
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'preview-env-{{number}}'
    spec:
      destination:
        namespace: 'test-{{number}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: kubernetes-resources/overlays/custom-envs/
        repoURL: 'full-url-of-gitlab-repo.git'
        targetRevision: '{{head_sha}}'
        kustomize:
          patches:
          - target:
              kind: Ingress
              name: primary-ingress
            patch: |-
              - op: replace
                path: /spec/tls/0/hosts
                value: test-test-test-{{.number}}  
```

**kustomization.yaml**

```yaml
resources:
  - ../base/

namespace: preview-environment

patchesStrategicMerge:
  - deployment.yml

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: primary-ingress
    path: ingress-patch.yml
```

**ingress-patch.yml**

```yaml
- op: replace
  path: /spec/rules/0/host
  value: place-holder
```

ArgoCD doesn't seem to take the Kustomize values (inline) which are defined in `ApplicationSet`. Instead, it still refers to the values defined in `overlays/ingress-patch.yml`.

<img width="283" alt="Screenshot 2023-11-29 at 10 30 09" src="https://github.com/argoproj/argo-cd/assets/117916719/ea67917b-e052-47d8-b222-09921cae5bef">
