### DISCUSSION TITLE
Argcd application generated via applicationsets are not visible in UI

### DISCUSSION THREAD

**Discussion by shamonshan** [argoproj/argo-cd#16620] [General]
I am trying to create applications in argocd using application sets and also i am using apps of apps pattern.

Here is  `root-app-dev.yaml` 

    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: root-appbundle-app-dev
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: default
        name: in-cluster
      project: appbundle-project-dev
      syncPolicy:
        automated: {} 
      source:
        path: argocd/apps-children/dev
        repoURL: https://github.com/<username>/argocd-root
        targetRevision: HEAD

And the applicationSet manifest located in the  `argocd/apps-children/dev` folder

    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: child-app-template
    spec:
      goTemplate: true
      goTemplateOptions: ["missingkey=error"]
      generators:
      - matrix:
          generators:
          - git:
              repoURL: https://github.com/shamonshan/argocd-root
              revision: HEAD
              files:
              - path: configs/config.yml
          - list:
              elements: []
              elementsYaml: "{{ .configs.components | toJson }}"
      template:
        metadata:
          name: '{{.name}}'
        spec:
          project: '{{.project}}'
          destination:
            name: in-cluster
            namespace: '{{.namespace}}'
          source:
            repoURL: '{{.repoUrl}}'
            path : helm
            targetRevision: '{{.version}}'

 Applied the manifest using  `kubectl apply -f argocd/root-app-dev.yml` 
 and i can see the parent application in the argocd UI but the applications that are created by the applicationsSet is not visible in the UI.

[![Current UI][1]][1]

  [1]: https://i.stack.imgur.com/sUiMK.png

Also no resources related  are created in the cluster as well

**Comment by messiahUA** [comment]
Is there a defined "ownerReferences" in the generated Application?

**Reply by shamonshan** [reply]
sorry i didn't get what you mean by owner references.

**Reply by shamonshan** [reply]
<img width="1053" alt="Screenshot 2023-12-15 at 5 15 34 PM" src="https://github.com/argoproj/argo-cd/assets/11383876/f07bd09b-2274-45cf-8d6c-55d6ab25d8de">

These are the statuses i can see in the UI

**Reply by messiahUA** [reply]
Check the raw manifest: `kubectl -n argocd get app yourappname -o yaml`

And by the way which version of argo are you using?
I don't have such a problem and I believe argo connects appset to app through the ownerReference and if you don't have it then maybe this is a problem with some specific version.

**Reply by shamonshan** [reply]
i am using the latest version of argo. can you give an example of owner reference usage

**Reply by messiahUA** [reply]
this is an example how it looks like:
```
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ApplicationSet
    name: someapplicationset
    uid: 67acc3c2-6c71-4e1a-bb79-abe3c333
```
it should be added automatically and, unfortunately, I don't know why you have this problem

**Reply by shamonshan** [reply]
Can you share the command to verify this

**Reply by messiahUA** [reply]
Already provided in the previous post:
`kubectl -n argocd get app yourappname -o yaml`

**Reply by shamonshan** [reply]
Thanks i got the issue its with the namespace and it is resolved

**Reply by messiahUA** [reply]
Would be great if you could provide more info so that it might help others with the same problem.

**Reply by shamonshan** [reply]
Sure i  will update now

**Comment by shamonshan** [comment]
The namespace should be namespace where the argocd resources resides

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace:  default  // replace it with argocd or  you can configure this also https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
    name: in-cluster
  project: appbundle-project-dev
  syncPolicy:
    automated: {} 
  source:
    path: argocd/apps-children/dev
    repoURL: https://github.com/<username>/argocd-root
    targetRevision: HEAD
```
