### DISCUSSION TITLE
[Gotemplate] Is it possible to add conditional template in applicationset?

### DISCUSSION THREAD

**Discussion by shamonshan** [argoproj/argo-cd#16648] [General]
Is it possible to have conditonal rendering of templates in application set ??

something like this

```
template:
  {{$url := "" }}
  {{$type := "fc"}}
  {{ if eq $type "fc"}}
  {{$url = "fc.com"}}
  {{end}}
    metadata:
      name: '{{.name}}'
    spec:
      project: '{{.configs.project}}'
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      source:
        repoURL: '{{$url}}'
        path : helm
        targetRevision: '{{.version}}'
```

For me the above will return unmarshell errors
