### DISCUSSION TITLE
Nested matrix generator using git file generator

### DISCUSSION THREAD

**Discussion by shamonshan** [argoproj/argo-cd#16650] [General]
My requirement is below
 1. Application in multiple namespaces
 2. In each namespace multiple application installation is required

eg:  namespace: "app1", "app2"  // from a git file generator (oe.yml)
application repos : "repo1","repo2"    //this is from git file generator (repos.yml)

In total 4 app installation is required   that is
1. app1-repo1
2. app1-repo2
3. app2-repo1
4. app2-repo2

Is it possible to have matrix generator configurations to achieve the above ?? 
 
Currently, i have this

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: child-app-template
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/<repo>/argocd-root
          revision: HEAD
          files:
          - path: configs/config.yml
      - list:
          elements: []
          elementsYaml: "{{ .configs.components | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: '{{.configs.project}}'
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      source:
        repoURL: '{{.repoUrl}}'
        path : helm
        targetRevision: '{{.version}}'


```

Which installs in multiple namespaces from git file generator
