### DISCUSSION TITLE
Application source as helm : values file from external repo

### DISCUSSION THREAD

**Discussion by shamonshan** [argoproj/argo-cd#16669] [Q&A]
I am trying to install a values file from an external source for my helm chart. The helm chart is specified as the git repository.

Here is my configuration

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: child-app-template
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
   - matrix:
      generators:
        - list: 
            elements:
              - name: component1
                namespace: app1
                type: fc
              - name: component2
                namespace: app2
                type: wl
        - list: 
            elements:
              - url: https://github.com/shamonshan/argocd-demo-deployment.git
                application: fc
                version: HEAD
              - url: https://github.com/shamonshan/argocd-demo-deployment-1.git
                application: wl
                version: HEAD
  template:
    metadata:
      name: '{{.name}}-{{.application}}'
    spec:
      project: appbundle-project-dev
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      sources:
      - repoURL: '{{.url}}'
        path: helm
        targetRevision: '{{.version}}'
        helm:
          valueFiles:
          - $values/configs/values.yaml
      - repoURL: 'https://github.com/shamonshan/helm-configs.git'
        targetRevision: HEAD
        ref: values
```

**Generated manifest**

```
template:
    metadata:
      name: '{{.name}}-{{.application}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      project: appbundle-project-dev
      sources:
        - helm:
            valueFiles:
              - $values/values.yaml
          path: helm
          repoURL: '{{.url}}'
          targetRevision: '{{.version}}'
        - path: configs
          ref: values
          repoURL: 'https://github.com/shamonshan/helm-configs.git'
          targetRevision: HEAD

```
But i getting error on  helm installation

_Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = `helm template . --name-template component1-fc --namespace app1 --kube-version 1.27 --values <path to cached source>/configs/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: open <path to cached source>/configs/values.yaml: no such file or directory_

But the  `values.yaml` file is existing in the  `https://github.com/shamonshan/helm-configs.git`  

Argo cd versions

```
{
    "Version": "v2.9.3+6eba5be",
    "BuildDate": "2023-12-01T23:05:50Z",
    "GitCommit": "6eba5be864b7e031871ed7698f5233336dfe75c7",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```
