### DISCUSSION TITLE
ArgoCD Cannot Pull Helm Chart From a JFrog Repo

### DISCUSSION THREAD

**Discussion by BryanJames16** [argoproj/argo-cd#16672] [Q&A]
I want to set up an automated way of creating GitLab runners on our environment. Such that, users will just push application sets and values to spin up new Gitlab Runners.

I have the following application set setup on my local argocd instance:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitlab-runner-test
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kubernetes.default.svc
        url:  "https://kubernetes.default.svc"
  template:
    metadata:
      name: 'gitlab-runner-test'
    spec:
      project: default
      sources:
        - repoURL: 'https://charts.gitlab.io'
          targetRevision: v0.59.2
          chart: gitlab-runner
          helm:
            # passCredentials: true
            releaseName: platform-g-runner
            valueFiles:
            - $values/platform-g/infrastructure/values.yaml
            parameters:
            - name: runnerRegistrationToken
              value: <TOKEN>
        - repoURL: '<Another Repo>'
          targetRevision: main
          path: .
          ref: values
      destination:
        server: '{{url}}'
        namespace: gitlab-runner
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```
This applicationset works, and I was able to spin up runners to my local environment and made it report to GitLab. However, to standardize the repository,  I have created a JFrog remote repo on our own JFrog instance: (https://globe.jfrog.io/artifactory/api/helm/hmd-helm-gitlab). This remote repo points to the same gitlab chart repository. I have changed the manifest such that:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitlab-runner-test
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kubernetes.default.svc
        url:  "https://kubernetes.default.svc"
  template:
    metadata:
      name: 'gitlab-runner-test'
    spec:
      project: default
      sources:
        - repoURL: 'https://globe.jfrog.io/artifactory/api/helm/hmd-helm-gitlab'
          targetRevision: v0.59.2
          chart: gitlab-runner
          helm:
            # passCredentials: true
            releaseName: platform-g-runner
            valueFiles:
            - $values/platform-g/infrastructure/values.yaml
            parameters:
            - name: runnerRegistrationToken
              value: <RUNNER REGISRTATION TOKEN>
        - repoURL: '<Another Repo>'
          targetRevision: main
          path: .
          ref: values
      destination:
        server: '{{url}}'
        namespace: gitlab-runner
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

```

This is where I get an error:
![image](https://github.com/argoproj/argo-cd/assets/12033449/fc1a7399-62db-4698-b25e-3589eeb48742)

I was also able to download on the link the error mentioned: https://gitlab-charts.s3.amazonaws.com/gitlab-runner-0.59.2.tgz
When doing a manual helm pull, I was also able to pull the helm chart:
`helm pull --destination ./ --version v0.59.2 --username <USERNAME> --password <PASSWORD> --repo https://globe.jfrog.io/artifactory/api/helm/hmd-helm-gitlab gitlab-runner`

I have verified that the same credentials was used to create a repository in ArgoCD (helm repository) and the repository status says "successful".

![image](https://github.com/argoproj/argo-cd/assets/12033449/011745b2-7508-4088-8771-69c55965f8a9)

Anyone who had similar experiences before? Any tips?
