### DISCUSSION TITLE
Ignore .spec.suspend in cronjobs with a specific label and values

### DISCUSSION THREAD

**Discussion by idogada-akamai** [argoproj/argo-cd#16713] [Q&A]
Hello,
I am trying to use the jqPathExpressions in an ArgoCD application to ignore .spec.suspend on all cronjobs that have a specific label.
I have tried the following:
```
- group: batch 
  jqPathExpressions: 
    - select(.metadata.labels.controlledByLeader == "true").spec.suspend 
  kind: CronJob
```

Unfortunately that ignores the .spec.suspend field for all the cronjobs that are generated by the application.
How can I ignore .spec.suspend only on cronjobs where the label controlledByLeader is set to true?
Doc source: [Diffing Customization - Argo CD - Declarative GitOps CD for Kubernetes](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration)
