### DISCUSSION TITLE
Enable "applications in any namespace" feature in non-cluster-scoped ArgoCD installation

### DISCUSSION THREAD

**Discussion by juv** [argoproj/argo-cd#16732] [Q&A]
Hi, is it supported to use the `applications in any namespace` feature with an ArgoCD installation that is managing multiple namespaces based on the [ArgoCD Operator label](https://argocd-operator.readthedocs.io/en/latest/usage/deploy-to-different-namespaces/) `argocd.argoproj.io/managed-by` but is not a cluster-scoped installation? 

The docs suggest that this feature can only be enabled with "cluster-scoped installations":

> Cluster-scoped Argo CD installation[¶](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#cluster-scoped-argo-cd-installation)
This feature can only be enabled and used when your Argo CD is installed as a cluster-wide instance, so it has permissions to list and manipulate resources on a cluster scope. It will not work with an Argo CD installed in namespace-scoped mode.

Is this section in the docs still up-to-date? From what I can tell, the non-cluster-scoped ArgoCD installations that get created by the ArgoCD Operator already receive a good amount of RBAC configuration for the ArgoCD custom resources in the target/destination namespaces. Combined with the fixed list of namespaces that ArgoCD should do work in (by specifying the config `application.namespaces`), I think it might be possible to use this even with non-cluster-scoped installations? Is there something I am missing here?

Below you can find the roles that my ArgoCD installation gets a RoleBinding for in each target/destination namespace as per label `argocd.argoproj.io/managed-by`. I am using OpenShit GitOps `v1.10.1` for which the ArgoCD UI shows `v2.8.4`.
Role `{argocd-instance-name}-argocd-application-controller`
```
rules:
...
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  - appprojects
  - argocds
  verbs:
  - '*'
...
```

Role `{argocd-instance-name}-argocd-server`
```
rules:
...
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
...
```
