### DISCUSSION TITLE
Mulitsource not working with private git repo

### DISCUSSION THREAD

**Discussion by karthik1710** [argoproj/argo-cd#16746] [Q&A]
Hi All,

I'm trying deploy a helm chart with custom values ref: from private git repo. Both helm chart and git repo are private and repositories are already added in argocd.

Below is my argocd setup,

```shell
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```
My application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fr-eb-mongodb-dev
spec:
  destination:
    name: ''
    namespace: fr-mongodb-dev
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://gitlab.com/api/v4/projects/xxxx/packages/helm/stable'
    chart: mongodb
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - $values/custom-value/values-fr.yaml
  - repoURL: 'https://gitlab.com/xxxx/eb-xxxx/exxx.git'
    targetRevision: custom-values
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```
In the application.yaml, I trying to deploy private helm chart with custom values from git repository. But after deployment I could see Argocd is not getting custom values from the referred repo.

Thanks in advance. :raised_hands:

**Comment by carlosrodfern** [comment]
This app on a private repo does work:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://gitlab.com/api/v4/projects/xxx/packages/helm/stable'
    chart: simple-nginx
    targetRevision: 0.1.1
    helm:
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://gitlab.com/xxx/helm-value-test.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: simple-nginx
```

For each repo I had to setup an access token with read_api and read_repository permissions, and then set up the credentials in ArgoCD for the exact same URLs as used in the `Application` manifest.
