### DISCUSSION TITLE
Connect repo error - Unable to connect to repository: error reading server preface: EOF

### DISCUSSION THREAD

**Discussion by marcelhorner** [argoproj/argo-cd#16752] [Q&A] [answered]
I am setting up Argo CD on a Kubernetes cluster.

When trying to connect to public GitHub repo I am getting the following error:
> Error: Unable to connect to repository: rpc error: code = Unavailable desc = connection error: desc = &quot;error reading server preface: EOF&quot;

I can see this error on Argo CD UI, when mousing over the X in front of "Failed" value at Connection Status column, but I can't find any error on pod logs. Where is this log coming from?

Configuration used:
  - Connection method: VIA HTTPS
  - Type: git
  - Project: default
  - Repository URL: tried with https://github.com/argoproj/argo-cd.git and https://github.com/argoproj/argo-cd

Thank you!

**Comment by marcelhorner** [comment]
Accessing argocd-server pod and clonning the repo with `git clone https://github.com/argoproj/argo-cd.git` works just fine, so it is not connectivity issue from the cluster to GitHub server.

**Comment by marcelhorner** [comment, marked as answer]
Found the issue.

I have TLS termination for my Argo CD installation at an ingress before reaching the server, so I had to turn of TLS termination on Argo itself.

I found some documentation that said I should add those values to my helm chart config file:
```
configs:
  params:
    dexserver.disable.tls: true
    controller.repo.server.plaintext: true
    server.insecure: true
    server.dex.server.plaintext: true
    server.repo.server.plaintext: true

```
Turns out the only config needed was `server.insecure: true`, other configs broke Argo CD communication and made connect repo fail.
