### DISCUSSION TITLE
Way to roll/sync one application at a time using applicationset

### DISCUSSION THREAD

**Discussion by riteshnanda09** [argoproj/argo-cd#16783] [General]
Have an usecase where i am using applicationset where i want applications to be synced in rolling fashion across clusters, one at a time.
I am aware of the rolling sync feature but that's based on labels which would still group clusters together. I am using cluster generator . I want if i have 10 applications generated for 10 clusters, they sync in serial than in parallel.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agent
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        - key: env
          operator: In
          values:
          - "dev"
          - "qa"
          - "stage"
          - "prod"
```
