### DISCUSSION TITLE
Cluster Secrets from External Secrets not work

### DISCUSSION THREAD

**Discussion by gdennye** [argoproj/argo-cd#16798] [General]
I am integrating Argo CD with External Secret Operator. However, I ran into a problem. My ArgoCD manages other clusters and as we know, connection configurations to clusters are done through secrets. Secrets declared in the GIT repository work perfectly and when I go to the settings I can see the clusters represented in the secrets, however when I set up the same secrets using external secrets no clusters are created. Has anyone used this scenario?

**Comment by bhampl** [comment]
I don't know if you have solved your problem in the meantime, but I thought I have the same problem as you. But it turns out, my External Secret template generated a malformed JSON, which Argo CD was unable to unmarshal (confirmed by looking at the Argo CD pod logs).
For future reference here is my working ExternalSecret manifest, which generates the cluster configuration from a kubeconfig file (generated by Kubeadm) saved as JSON into HashiCorp Vault:

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-cluster
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: test-cluster
        server: https://test-cluster.example.com:6443
        config: |
          {
            "tlsClientConfig": {
              "insecure": false,
              {{- $kubeconfig := fromJson .kubeconfig }}
              {{- $cluster := (index $kubeconfig.clusters 0).cluster }}
              {{- $user := (index $kubeconfig.users 0).user }}
              "caData": "{{ index $cluster "certificate-authority-data" }}",
              "certData": "{{ index $user "client-certificate-data" }}",
              "keyData": "{{ index $user "client-key-data" }}"
            }
          }
      type: Opaque
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: test-cluster

```
