### DISCUSSION TITLE
Error 400 with github sso

### DISCUSSION THREAD

**Discussion by molnare** [argoproj/argo-cd#16874] [Q&A]
Hello, 
I am trying to install argocd with dex github connector. I want argocd to run under a subpath. When I click login via github I get a 400 bad request. I have no idea why...
I install argocd through helm:
```bash
helm upgrade --install --force --namespace argocd --create-namespace argocd argo/argo-cd --values values.yaml
```
Here is my values.yaml
```yaml
configs:
  params:
    server.basehref: /argocd
    server.rootpath: 'argocd'
  cm:
    url: "https://myfalsedomain.com/argocd"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-github:github-client-id
            clientSecret: $argocd-github:github-client-secret
            orgs:
            - name: MyGitHubOrg
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: "nginx"
    hosts:
    - myfalsedomain.com
    paths:
    - /argocd
    tls:
     - secretName: myfalsedomain-ssl-cert
       hosts:
       - myfalsedomain.com
    https: true
```

I also posted the question in the argo-helm discussion https://github.com/argoproj/argo-helm/discussions/2424, but as suggested maybe I get more feedback here in the upstream.

What am I doing wrong?
