### DISCUSSION TITLE
Application points to terragrunt.hcl which contains helm values

### DISCUSSION THREAD

**Discussion by chkp-zivhada** [argoproj/argo-cd#16924] [Q&A]
Hi,
I have Application pointing to terragrunt.hcl file.
The terragrunt holds all the helm values of the deployment.
I would like that in case of a merged PR with a change in the helm values , that it will automatically deploy the change via argo.
Currently, i see that argo recognize the change and sync it successfully, but the change doesn't deploy.

application.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: base-deployment
  source:
    repoURL: git@github.com:devops/devops-test.git
    #branch
    targetRevision: eks-infra
    path: eks/cluster-autoscaler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

```

terragrunt.hcl:
```
dependencies {
  paths = ["../eks"]
}

include {
  path = find_in_parent_folders()
}

inputs = {
  openid_provider_arn             = dependency.eks.outputs.openid_provider_arn
  enable_cluster_autoscaler       = true
  cluster_autoscaler_helm_version = "9.34.1"
  helm_settings                   = {
    "autoDiscovery.clusterName" = dependency.eks.outputs.eks_name
    "rbac.serviceAccount.name"  = "cluster-autoscaler"
    "serviceMonitor.enabled"    = true
    "serviceMonitor.interval"   = "30s"
    "serviceMonitor.namespace"  = "monitoring"
    "replicaCount" = 2
  }
}

dependency "eks" {
  config_path = "../eks"
}

terraform {
  source = "git::git@github.com:devops/infra-modules.git//cluster-autoscaler"
}
```
