### DISCUSSION TITLE
Using ArgoCD to deploy to multiple clusters using the same repo

### DISCUSSION THREAD

**Discussion by Newbie112222** [argoproj/argo-cd#16974] [Q&A]
HI,
I have a use case where we have one repo to deploy to cluster A. I want to use the same repo to deploy to cluster B. Both clusters will have their separate argocd deployments running.

what i have already done:
1. I created 2 branches, one branch will push changes to cluster A, the other branch will push to cluster B - this works as expected

Issue with branch strategy: I dont want to push new cahnges to the 2 branches at the same time, its more overhead

I wanted to check if there was any better way to do this ex. create a new repo and sync changes to the other repo but in this case too we have an issue as some of our deployments are region specific and i would need a way to inject the regions.

Any thoughts on how the community is tacking the above issue, any guides/steps would be helpful.

**Comment by FernandoMiguel** [comment]
this sounds like a XY problem.
guess you need a 3rd repo/branch that is used by both... branch A, branch B and branch AB :D 

joking aside, i find this design problematic.

in our implementation, we use a matrix generator with
```
          - clusters:
              selector:
                matchLabels:
                  [...]
                matchExpressions:
```
and this dictates where jobs go.
they can go nowhere, one or many clusters.
so it's the job dictating where they land.

**Reply by Newbie112222** [reply]
@FernandoMiguel thanks for your response. I haven't got in depth in the documentation as yet but how do you handle region specific values in files? I tried Kustomization but had no luck with as argoCD kept throwing errors for that

**Reply by FernandoMiguel** [reply]
@Newbie112222 what do you mean region values?
Are those cluster specific of app specific?

**Reply by Newbie112222** [reply]
@FernandoMiguel i mean values like us-east-1 or a log group name

**Reply by FernandoMiguel** [reply]
@Newbie112222 we have a cluster values file that is appended to every app.
The file has the name of the destination. 
The app values has its own specific keys, and one for the cluster.
So all apps share the same keys for any cluster.
Pretty easy.

**Reply by Newbie112222** [reply]
@FernandoMiguel do you use just append the path of this cluster values file to pick up the key-value pair from there or how does it go and fetch the value, you have an example of this?

**Reply by FernandoMiguel** [reply]
```
    spec:
      project: base
      source:
        repoURL: "https://github.com/example.git"
        path: "{{ .path.path }}"
        targetRevision: HEAD
        helm:
          ignoreMissingValueFiles: true
          passCredentials: true
          valueFiles:
            - "/common/values.{{ .nameNormalized }}.yaml"
            - "./values.yaml"
```
