### DISCUSSION TITLE
Use git directory,files generator in matrix generator

### DISCUSSION THREAD

**Discussion by hamadodene** [argoproj/argo-cd#16996] [General]
it's possibile to use git directory,files generator in matrix generator?
I write something like this:
```

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-application-set
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://example.com/argocd-deployments.git
              revision: HEAD
              directories:
                - path: deployments/*/*
              pathParamPrefix: app
          - git:
              repoURL: https://example.com/argocd-deployments.git
              revision: HEAD
              files:
                - path: '{{app.path}}/example.json'
              pathParamPrefix: imgconfig

  template:
    metadata:
      namespace: argocd
      name: '{{app.path[1]}}-{{app.path.basename}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - 'values.yaml'
        path: '{{app.path}}'
        repoURL: https://example.com/argocd-deployments.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
      destination:
        namespace: '{{app.path.basename}}'
        server: https://kubernetes.default.svc/
```
But with this configuration 0 applications are deployed
If i replace the git files generator with a cluster generator, all applications is deployed correctly
