### DISCUSSION TITLE
What is the difference between these two options?  `syncPolicy.automated.prune`  vs `syncPolicy.syncOptions.Prune`

### DISCUSSION THREAD

**Discussion by txjjjjj** [argoproj/argo-cd#16998] [Q&A]
What is the difference between these two options?  `syncPolicy.automated.prune`  vs `syncPolicy.syncOptions.Prune`
What is the priority?

syncPolicy.automated.prune  vs syncPolicy.syncOptions.Prune
 
in Application: 
```
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Prune=false
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
```
