### DISCUSSION TITLE
ArgoCD Ingress/ALB fails healthcheck

### DISCUSSION THREAD

**Discussion by eyearian** [argoproj/argo-cd#17018] [General]
Hi -
I have ArgoCD set up on EKS, but when setting up an ingress via an ALB the target group never goes healthy. I am using the most recent version of ArgoCD - `2.9.3`  I have set up the ingress and service per the docs:

Ingress:
```
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/certificate-arn: {cert arn}
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
      alb.ingress.kubernetes.io/conditions.argogrpc: |
        [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    name: argocd
    namespace: argocd
  spec:
    ingressClassName: alb
    rules:
    - host: argocd.example.com
      http:
        paths:
        - path: /
          backend:
            service:
              name: argogrpc
              port:
                number: 443
          pathType: Prefix
        - path: /
          backend:
            service:
              name: argocd-server
              port:
                number: 443
          pathType: Prefix
    tls:
    - hosts:
      - argocd.example.com
  ```
  Service:
  ```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: argogrpc
  name: argogrpc
  namespace: argocd
spec:
  ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
  ```
  
If using a `NodePort` in the service, then you should be using the target type of `instance`: 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-type

Yet the LB wont ever go healthy due to the following error:
  `{"level":"error","ts":1706383542.989162,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"argocd","namespace":"argocd","error":"InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n"}`
  
If I switch the `argogrpc` service to a `ClusterIP` and switch the target type annotation to `ip` the load balancer successfully reconciles, but wont ever go healthy.

The ingress sets up two listener rules. The first is grpc listener - the grpc listnener target (argogrpc) registers in the LB, but fails the health check.  

The second listener rule (argocd-server) never populates.  If I manually register the target in this second target group, it eventually goes healthy and allows me to connect via https.

Any ideas here?  First I'm wondering why the default way ArgoCD suggests the ingress setup isn't working.  I'm also wondering why it doesn't set up the correct target when I switch it to use a target type of `ip`.
