### DISCUSSION TITLE
helm template .Files.get not working

### DISCUSSION THREAD

**Discussion by zoezhangmattr** [argoproj/argo-cd#17027] [General]
try to use helm chart in argocd application

the the helm template, configmap
```yaml
data: 
  config: |
{{ .Files.Get (.Values.configMap.configFileName) | indent 4 }}
```

using helm template to render works well
however when argocd application sync, the config is ""
seems like it cant read the file

not sure what is wrong, does anyone have the same issue. or i got it wrong.
