### DISCUSSION TITLE
ApplicationSet for multiple applications/charts with a dependsOn

### DISCUSSION THREAD

**Discussion by dubb-b** [argoproj/argo-cd#17028] [Q&A]
I have this sample, not sure that this is even possible. Is there a way to do something like this?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'd-ause2-keycloak-pre-setup'
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: d-ause2-armada-1
            name: 'd-ause2-keycloak'
            namespace: keycloak
            url: 'https://k8s.com'
  template:
    metadata:
      name: '{{"{{"}}name{{"}}"}}'
    spec:
      project: default
      destination:
        namespace: '{{"{{"}}namespace{{"}}"}}'
        server: '{{"{{"}}url{{"}}"}}'
  templates:
    - name: pre-setup
      template:
        metadata:
          name: '{{"{{"}}name{{"}}"}}-pre-setup'
        spec:
          project: default
          source:
            repoURL: 'https://github.com/cbsinteractive/vtg-keycloak-deploy'
            path: 'charts/keycloak-secrets'
            targetRevision: dev
            helm:
              valueFiles:
                - values-d-ause2.yaml
          destination:
            namespace: '{{"{{"}}namespace{{"}}"}}'
            server: '{{"{{"}}url{{"}}"}}'
          syncPolicy:
            automated:
              prune: false
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
            preserveResourcesOnDeletion: true
    - name: keycloak
      template:
        metadata:
          name: '{{"{{"}}name{{"}}"}}'
        spec:
          project: default
          source:
            repoURL: 'registry-1.docker.io/bitnamicharts'
            chart: keycloak
            targetRevision: '18.3.2'
            path: ""
            helm:
              values: |
                postgresql:
                  enabled: false
                externalDatabase:
                  host: "rds.amazonaws.com"
                  user: "keycloak"
                  database: "keycloak"
                  existingSecret: "d-ause2-keycloak-secrets"
                  existingSecretPasswordKey: "DB_PASS"
          destination:
            namespace: '{{"{{"}}namespace{{"}}"}}'
            server: '{{"{{"}}url{{"}}"}}'
          syncPolicy:
            automated:
              prune: false
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
            preserveResourcesOnDeletion: true
          dependsOn:
            - name: '{{"{{"}}name{{"}}"}}-pre-setup'
```

I want to have a pre setup chart that sets up all the secrets and other sensitive items that keycloak needs.

My other question is keycloak on bitnami is an oci:// registry. How do i specify this in the RepoURL?
