### DISCUSSION TITLE
ApplicationSet with Helm: different chart revision per environment

### DISCUSSION THREAD

**Discussion by Sebast1aan** [argoproj/argo-cd#17058] [Q&A] [answered]
Hi,

my applicationSet is defined as follows:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argo
spec:
  generators:
    - git:
        repoURL: https://link_to_repo.git
        revision: HEAD
        directories:
          - path: test/environments/*

  template:
    metadata:
      name: "{{path[2]}}"
    spec:
      project: default
      sources:
      - repoURL: 'https://link_to_helm'
        chart: test_chart
        targetRevision: 1.2.3
          valueFiles:
          - $values/test/environments/values.yaml
          - $values/test/environments/{{path[2]}}/environment.yaml
```

This results in each environment present under `test/environments/` using helm chart 1.2.3. Ideally I want to be able to steer the chart revision per environment (i.e. in environment.yaml), so that I can first test a new chart in my development environment, before pushing it to the next environment.

Any ideas on how I can achieve this?

**Comment by Sebast1aan** [comment, marked as answer]
We solved this by using the _git file generator_ instead of the _git directory generator_.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argo
spec:
  generators:
    - git:
        repoURL: https://link_to_repo.git
        revision: HEAD
        files:
          - path: test/environments/**/config.yaml

  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      sources:
      - repoURL: 'https://link_to_helm'
        chart: test_chart
        targetRevision: '{{environment.chart_version}}'
          valueFiles:
          - $values/test/environments/{{path.basename}}/config.yaml
          - $values/test/environments/{{path.basename}}/environment.yaml
```

In the config.yaml that is specific to each environment, we then have a line representing which helm version should be used:
```
environment:
  chart_version: 1.2.3
```
