### DISCUSSION TITLE
ArgoCD Notifications for Multi-source applications

### DISCUSSION THREAD

**Discussion by VsevolodKalinin** [argoproj/argo-cd#17074] [Q&A]
Good evening) I want to use ArgoCD Notifications for Multi-source applications, but I can't figure out how to properly describe the template, please help because I didn't find the information on the documentation site ) 

**Configmap**

```
`apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # TODO Replace with family name (instead of yc-qwerty)
  context: |
    argocdUrl: https://xxxx.com
  service.teams: |
    recipientUrls: 
      argo: $channel-teams-url
  template.app-health-ok: |
    email:
      subject: Application {{ "{{" }}.app.metadata.name}} is OK.
    message: |+
      Application {{ "{{" }}.app.metadata.name}} is OK.
      Application details: {{ "{{" }}.context.argocdUrl}}/applications/{{ "{{" }}.app.metadata.name}}.
    teams:
      themeColor: '#008000'
      title: Application {{ "{{" }}.app.metadata.name}} is OK.
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{ "{{" }}.app.status.sync.status}}"
        },
        {
          "name": "Synced at",
          "value": "{{ "{{" }}.app.status.operationState.finishedAt}}"
        },
        {
          "name": "App Status",
          "value": "{{ "{{" }}.app.status.health.status}}"
        },
        {
          "name": "Operation State Phase",
          "value": "{{ "{{" }}.app.status.operationState.phase}}"
        },
        {
          "name": "Repository",
          "value": "{{ "{{" }}.app.spec.source.repoURL}}"
        }
        {{ "{{" }}range $index, $c := .app.status.conditions}}
          {{ "{{" }}if not $index}},{{ "{{" }}end}}
          {{ "{{" }}if $index}},{{ "{{" }}end}}
          {
            "name": "{{ "{{" }}$c.type}}",
            "value": "{{ "{{" }}$c.message}}",
          }
        {{ "{{" }}end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Details",
          "targets":[{
            "os":"default",
            "uri":"{{ "{{" }}.context.argocdUrl}}/applications/{{ "{{" }}.app.metadata.name}}?operation=true"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default",
            "uri":"{{ "{{" }}.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
          }]
        }]
  trigger.on-health-ok: |
    - description: Application is Healthy
      send:
      - app-health-ok
      when: app.status.health.status == 'Healthy'    `
```
      
      
      app.yaml
      
```
`project: prod-1
destination:
  server: 'https://kubernetes.default.svc'
  namespace: prod-1
syncPolicy:
  syncOptions:
    - CreateNamespace = true
revisionHistoryLimit: 10
sources:
  - repoURL: 'xxxxx'
    path: >-
      xxxxxxxxxx
    targetRevision: xxxxxxxx
    helm:
      valueFiles:
        - $values/auth_values.yaml
      values: |
        "yc_deployment_cpu_utilization": "70"
        "yc_deployment_limits_cpu": "200m"
        "yc_deployment_limits_memory": "500Mi"
        "yc_deployment_max_replica": "2"
        "yc_stages_family": "prod"
  - repoURL: 'xxxxxx'
    path: .
    targetRevision: prod-1
    ref: values
`

```

I tried to change it 

"uri":"{{ "{{" }}.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"

"uri":"{{ "{{" }}(index .app.spec.sources 0 ).repoURL| call .repo.RepoURLToHTTPS}}"

error " template: app-health-ok:19:15: executing \"app-health-ok\" at <index .app.spec.source 0>: error calling index:" 

what are the ways to solve the problem?
