### DISCUSSION TITLE
Sharing a Chart.yaml Across Environments?

### DISCUSSION THREAD

**Discussion by anthonyalayo** [argoproj/argo-cd#17086] [Q&A]
**I am trying to setup an argo cd repository that does not use branches for environments.**
Let's say I roughly have the following directory structure for the same chart:

```
.
├── dev
│   ├── Chart.yaml
│   ├── charts
│   ├── templates
│   └── values.yaml
└── prod
    ├── Chart.yaml
    ├── charts
    ├── templates
    └── values.yaml
```

**I want to clean this up to be more DRY.** My first thought was:
1. Make a values-dev.yaml and a values.yaml to represent both environments
2. Use one versus the other depending on the environment

This took me half way, but not to the finish line. For example, I have the following umbrella chart for argo-cd:
```
apiVersion: v2
name: argocd-helm
description: argo
type: application
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.53.13
    repository: https://argoproj.github.io/argo-helm
```

**I want to be able to upgrade ArgoCD's helm chart version in dev only, not in production.** That way I can sanity test it before rolling it out. Is it possible to finesse this configuration such that I can do that?

My ideal dream would be something like this:
```
apiVersion: v2
name: argocd-helm
description: argo
type: application
version: 1.0.0
dependencies:
  - name: argo-cd
    version: {{ .Values.env }}
    repository: https://argoproj.github.io/argo-helm
```

**But I know that templates are not supported inside the Chart.yaml file.** What's the way to solve this using a trunk-based approach (no environment-based branches) and helm?
