### DISCUSSION TITLE
AWS Redis & argocdCLI - cannot find pod with selector

### DISCUSSION THREAD

**Discussion by badsector3** [argoproj/argo-cd#17118] [Q&A]
Hi. 

I couldn't find an answer, so maybe someone had similar issue and knows the solution. 

I use ArgoCD with redis deployed on AWS Elasticache. 
Some of the commands triggered via argoCD CLI gives the following error:
```
argocd app logs argocd/example

ERRO[0001] finished streaming call with code Unknown     error="error getting app resource tree: error getting cached app resource tree: cannot find pod with selector: [app.kubernetes.io/name=argocd-redis-ha-haproxy app.kubernetes.io/name=argocd-redis] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI" grpc.code=Unknown grpc.method=PodLogs grpc.service=application.ApplicationService grpc.start_time="2024-02-07T13:37:03Z" grpc.time_ms=68.248 span.kind=server system=grpc
```

I understand that there is a label missing on the redis pod, but my redis is external - is there a solution?

**Comment by jgwest** [comment]
The error is coming from kube port forwarder, which appears to expect to find redis pod (and port forward to it) within the namespace.  It looks as if `port-forward-redis` [defaults to true in the places it's used](https://github.com/argoproj/argo-cd/blob/7e80f1e8e59da2701c87e97b6bda4c64345a90e2/cmd/argocd/commands/admin/cluster.go#L231), which enables this behaviour. 

It may be worth setting `port-forward-redis` to false, and specifying env vars/params to configure the connection to the redis server: https://github.com/argoproj/argo-cd/blob/7e80f1e8e59da2701c87e97b6bda4c64345a90e2/util/cache/cache.go#L139

**Reply by badsector3** [reply]
Thanks @jgwest

I am not sure where should I set the `port-forward-redis` Is that on client side?

Regarding the REDIS_SERVER I assume it's for argoCD server configuration. 
I use helm charts to deploy argoCD and my config is as following:
```
## Argo Configs
configs:
  # General Argo CD configuration
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
    create: true
    url: "http://${hostname}"
    application.instanceLabelKey: argocd.argoproj.io/instance
    ui.bannercontent: "Hello, this is: ${hostname}"

  # Argo CD configuration parameters
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
  params:
    redis.db: "${redis_db}"

  secret:
    argocdServerAdminPassword: "${argocdServerAdminPassword}"
    argocdServerAdminPasswordMtime: "${argocdServerAdminPasswordMtime}"

# External Redis parameters
externalRedis:
  host: "${redis.hostname}"
  port: "${redis.port}"
  username: "${redis.username}"
  password: "${redis.password}"
 ```

So do I need to add another env variable called REDIS_SERVER?
