### DISCUSSION TITLE
Alert if targetRevision for app != HEAD

### DISCUSSION THREAD

**Discussion by jlm0x017** [argoproj/argo-cd#17156] [Q&A] [answered]
I'd like an alert if an app has not been pointing at HEAD (or prod, or other mainline branch) for more than X days.

My initial thought is that `argocd_app_info` could have targetRevision as a label.  Thus, allowing me to fill in the branch name and track the time in my own prometheus infrastructure.  However, most /metrics look like they are directed toward sync counts.  I'm missing any way they could be used towards this end.

Alternatively, a log message could work.  Alas, most log messages look to be in the form of:
Initiated automated sync to '60d4f3dd301d482c54f91472c26ce3721bda226b'
Partial sync operation to fdabc540ae8c138d931de1aaf0656b9fc1aa3193 succeeded

I do see HEAD mentioned, when it's a manual sync:
admin initiated sync to HEAD (fdabc540ae8c138d931de1aaf0656b9fc1aa3193)

I suppose I could wire in github and get head/branch shas as a metric, and then a join or other collation could work, but it seems a more direct way should be available.

**Comment by Talbalash-legit** [comment, marked as answer]
Hey, just managed to solve this!
Using argocd notifications of course:

```yaml
    triggers:
      trigger.on-branch-changed: |
        - when: app.spec.source.targetRevision != 'HEAD'
          send: [branch-changed-template]
          
    templates:
      template.branch-changed-template: |
        message: |
          {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} is not on main branch.
          Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
        slack:
          attachments: |
            [{
              "title": "Branch Changed - {{ .app.metadata.name}}",
              "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#30f4f4",
              "fields": [
                {
                  "title": "Environment",
                  "value": "Dev",
                  "short": true
                },
                {
                  "title": "Health Status",
                  "value": "{{.app.status.health.status}}",
                  "short": true
                },                
                {
                  "title": "Branch",
                  "value": "{{.app.spec.source.targetRevision}}",
                  "short": true
                },
                {
                  "title": "Repository",
                  "value": "{{.app.spec.source.repoURL}}",
                  "short": true
                }
              ]
            }]
```
            
            
        
 and anonotate the application accordingly:
 ```yaml
 annotations:
     notifications.argoproj.io/subscribe.on-branch-changed.slack=your_channel
