### DISCUSSION TITLE
Unknown field valuesObject in ApplicationSet.spec.template.spec.sources[1].helm

### DISCUSSION THREAD

**Discussion by ricoapon** [argoproj/argo-cd#17158] [Q&A] [answered]
### Problem
I have configured ArgoCD to use an ApplicationSet with multiple sources. In one of the sources I configure a Helm chart. I want to add values, so I used the (documented) valuesObject for this. Strangely enough, I get this error:
`error validating data: ValidationError(ApplicationSet.spec.template.spec.sources[1].helm): unknown field "valuesObject" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.sources.helm`

My YAML configuration file
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: pd
  namespace: argocd
spec:
  generators: <not important>
  template:
    metadata: <not important>
    spec:
      <removed unimportant configuration>
      sources:
        # This repository contains the values.yaml that is used for installing the helm application.
        # This is a different location than the helm chart, so we define it with a reference, so we can use it later.
        - repoURL: <my repo>
          targetRevision: HEAD
          ref: valuesRepo

        # This defines the installation of the helm chart.
        - repoURL: <my repo>
          targetRevision: '0-{{ head_short_sha }}-SNAPSHOT'
          chart: '{{ helmChart }}'
          helm:
            releaseName: '{{ project }}-{{ repo }}-{{ number }}'
            valueFiles:
              - '$valuesRepo/{{ path }}/values.yaml'
            # We want to use the tag we have here in the deployment.
            valuesObject:
              global:
                tag: '{{ head_short_sha }}-SNAPSHOT'
```

### Analysis
I am running ArgoCD version v2.9.2+c5ea5c4. Looking at provided examples (like https://github.com/argoproj/argo-cd/blob/v2.9.2/docs/operator-manual/application.yaml#L71) you can see that `valuesObject` is defined.

I looked at the code, because I thought maybe this example file was incorrect. But you can clearly see that https://github.com/argoproj/argo-cd/blob/v2.9.2/pkg/apis/application/v1alpha1/types.go#L325 contains the field where the YAML parses the `valuesObject`.

There must be something I am doing wrong, but looking at the code and documentation I really don't know what the problem is. Initially, I thought that something is different between using "sources" or "source", but the code shows that the same objects for parsing are used (`ApplicationSetSource`). The version of the application really is 2.9.2, it says so in the GUI. This cannot be wrong. I also couldn't find any issues/discussions related to my exact error, so I am pretty sure there is an error on my end.

I am out of ideas, so I thought I would start a discussion here.

### Deployment
As a sidenote: I am deploying ArgoCD using Bitnami helm charts, so we have `bitnami/argo-cd:2.9.2` deployed. I cannot imagine something being wrong with this, but I thought it might be useful information.

### Different missing field
I tried to add this to the YAML file:
```
        # We allow additional YAML files to be installed besides the helm chart.
        - repoURL: <repo url>
          targetRevision: HEAD
          path: '{{ path }}/kustomize'
          kustomize:
            patches:
              - target:
                  kind: Namespace
                patch: |-
                  - op: replace
                    path: /metadata/name
                    value: {{ project }}-{{ repo }}-{{ number }}
```

And then I got the error that the patches field did not exist: `error validating data: ValidationError(ApplicationSet.spec.template.spec.sources[2].kustomize): unknown field "patches" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.sources.kustomize`

Again strange, because looking at the documentation it says it is possible (https://argo-cd.readthedocs.io/en/release-2.9/user-guide/kustomize/#patches). And the code says so too: https://github.com/argoproj/argo-cd/blob/v2.9.2/pkg/apis/application/v1alpha1/types.go#L469.
