### DISCUSSION TITLE
ApplicationSet templatePatch on cluster generator not passing boolean values

### DISCUSSION THREAD

**Discussion by NickPaul41** [argoproj/argo-cd#17153] [Q&A]
I'm trying to enable autoSync for my dev environment

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            type: 'dev'
        values:
          autoSync: true
    - clusters:
        selector:
          matchLabels:
            type: 'prod'
        values:
          autoSync: false
  template:
    metadata:
      name: '{{.name}}-my-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/redacted'
        targetRevision:  HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        syncOptions:
  templatePatch: |
    {{- if .values.autoSync }}
    spec:
     syncPolicy: :
        automated: {}
    {{- end }}
```

It seems values does not allow boolean and I get the following error 

`[spec.generators[0].clusters.values.autoSync: Invalid value: "boolean": `

Is there a way to use the new templatePatch with the cluster operator?

**Comment by sim-dav** [comment]
We've had a similar problem, did you get any further @NickPaul41 ?

We're trying to turn on auto sync, for just our non prod cluster

```
templatePatch: |
    {{- if eq .name "tooling-nonprod" }}
    spec:
      syncPolicy:
        automated:
          prune: true
    {{- end }}
status:
  conditions:
  - lastTransitionTime: "2024-03-15T10:59:06Z"
    message: 'invalid templatePatch "{{- if eq .name \"tooling-nonprod\" }}\nspec:\n  syncPolicy:\n    automated:\n      prune:
      true\n{{- end }}\n": invalid character ''{'' looking for beginning of object
      key string'
    reason: RenderTemplateParamsError
    status: "True"
    type: ErrorOccurred
```
