### DISCUSSION TITLE
Integrating ExternalDNS with the AWS Load Balancer Controller for Argo Deployment

### DISCUSSION THREAD

**Discussion by Montana** [argoproj/argo-cd#17176] [General]
Hi all,

I've been referring to the Argo's guidelines for setting up AWS Application Load Balancers (ALBs) and Classic Elastic Load Balancers (ELBs) with HTTP mode. However, merging these configurations has led to a problem where ExternalDNS tends to opt for internal IPs instead of external ones:

```shell
dig argocd.<MyURL>.com

; <<>> DiG 9.10.6 <<>> argocd.<MyURL>.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3362
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;argocd.<MyURL>.com. IN      A

;; ANSWER SECTION:
argocd.<MyURL>.com. 300 IN   A       10.0.3.59
argocd.<MyURL>.com. 300 IN   A       10.0.2.77
argocd.<MyURL>.com. 300 IN   A       10.0.2.166
argocd.<MyURL>.com. 300 IN   A       10.0.1.194

;; Query time: 22 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Feb 10 17:37:38 PDT 2024
;; MSG SIZE  rcvd: 122
```

Below is the pertinent configuration for the two services and the ingress related to Argo:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-cd-argocd-server
  namespace: argo-cd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.<MyURL>.com
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/version: v2.7.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.36.11
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argo-cd
---
apiVersion: v1
kind: Service
metadata:
  name: argogrpc
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
  labels:
    app: argogrpc
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/conditions.argogrpc: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
spec:
  rules:
    - host: argocd.<MyURL>.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  name: https
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argogrpc
                port:
                  number: 443
```

How can I set up ExternalDNS and the AWS Load Balancer Controller to work with Argo?

For what it's worth, I've successfully configured ExternalDNS and the AWS Load Balancer Controller with my EKS Kubernetes cluster. This setup allows me to easily create ALBs and route them to my cluster with external DNS records using just a few annotations. However, I'm encountering issues specifically with Argo. Below is an example of a configuration that works for a simple app serving HTML on port `80`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: feature-flag-tests
  annotations:
    external-dns.alpha.kubernetes.io/hostname: fftests.<MyURL>.com
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
  selector:
    app: feature-flag-tests
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-flag-tests
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: 'true'
    alb.ingress.kubernetes.io/certificate-arn: <My Cert ARN>
spec:
  ingressClassName: alb
  rules:
    - host: fftests.<MyURL>.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-flag-tests
                port:
                  number: 80
```
Currently as of now, I simply appended the `external-dns.alpha.kubernetes.io/hostname` annotation to the service generated by the Helm chart, rather than creating a new service. Additionally, I established a new Ingress of type ingress, essentially mirroring the example provided in my question. While I'm unsure if it's possible to route HTTP2 and gRPC traffic through this configuration (my goal was merely to access the web UI), I'm open to insights on this matter.

I remain interested in finding an effective method to achieve this without resorting to the `--insecure flag`, particularly if it could include support for HTTP2/gRPC. I would appreciate any alternative suggestions or strategies to accomplish this. 

Cheers, 
Michael Mendy
