### DISCUSSION TITLE
RBAC Permission to view Parameters

### DISCUSSION THREAD

**Discussion by niklastanner** [argoproj/argo-cd#17198] [Q&A]
What are the required RBAC permissions to view the content of the parameters blade of an application?

We have an application within a project. The Project RBAC configuration looks like the following:
```YAML
spec:
  roles:
    - name: app-manager
      description: Managing privileges on application level
      policies:
        - p, proj:test-project:app-manager, applications, *, test-project/*, allow
        - p, proj:test-project:app-manager, applicationsets, *, test-project/*, allow
        - p, proj:test-project:app-manager, logs, *, test-project/*, allow
        - p, proj:test-project:app-manager, exec, *, test-project/*, allow
      groups:
        - REDACTED
```

The permissions itself are working, as the user is able to do anything within the application, like reading logs, exec into a pod etc.
But on the Argo CD application itself on the "Parameters" blade he does not see anything.

Assigning "readonly" to the group which allows to read everything on cluster level does allow him to read the parameters within the parameters blade.

What RBAC permission is required to view the parameters, as we do not want to grant readonly to the group. Or is this not possible from the project rbac definitions and has to be done on the Argo CD RBAC CSV?
