### DISCUSSION TITLE
Issue when subscribing to Webhook service notification.

### DISCUSSION THREAD

**Discussion by idanfishman** [argoproj/argo-cd#17194] [Q&A]
Hello everyone,

I've recently started using ArgoCD Notifications and configured a new custom webhook intended to trigger a POST request. I've successfully triggered this webhook manually, and it worked perfectly :)

**CLI command:**
```shell
argocd admin notifications template notify myplatform_cloudflare_cache_purge_zone_id myapp --recipient myplatform-cloudflare-purge-cache
```

However, I'm uncertain if I've correctly subscribed the application, as it does not seem to work when the trigger condition is met.

**argocd-notifications-cm configuration:**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.myplatform-cloudflare-purge-cache: |
    url: https://api.cloudflare.com/client/v4/zones/$myplatform_cloudflare_cache_purge_zone_id/purge_cache
    headers:
      - name: Content-Type
        value: application/json
      - name: Authorization
        value: Bearer $myplatform_cloudflare_cache_purge_api_token
  template.myplatform-cloudflare-purge-cache: |
    webhook:
      myplatform-cloudflare-purge-cache:
        method: POST
        body: |
          {
            "files": [
              "https://www.example.com",
              "https://www.example.com/",
              "https://example.com",
              "https://example.com/",
            ]
          }
  trigger.myplatform-on-sync-succeeded: |
    - description: Purge Cloudflare cache after a successful sync
      oncePer: app.status.operationState.syncResult.revision
      when: app.status.operationState != nil and app.status.operationState.phase in ["Succeeded"] and app.status.health.status == "Healthy"
      send:
        - myplatform-cloudflare-purge-cache
```

I'm looking for the right way to subscribe `myapp` to the webhook.
