### DISCUSSION TITLE
ignoreResourceUpdates not working as expected

### DISCUSSION THREAD

**Discussion by redhandpl** [argoproj/argo-cd#17249] [Q&A]
Hi,
I'm trying to ignore some resource updates via _resource.customizations.ignoreResourceUpdates_.
For now I would like to ignore HPA an CronJobs.

My configuration looks like that:
```
            resource.ignoreResourceUpdatesEnabled: "true"
            resource.customizations.ignoreResourceUpdates.batch_CronJob: |
              jsonPointers:
              - /status/lastScheduleTime
              - /status/lastSuccessfulTime
            resource.customizations.ignoreResourceUpdates.autoscaling_HorizontalPodAutoscaler: |
              jsonPointers
              - /status
              - /metadata
```

It works fine for HPA. But as for CronJob, I still see in Argo debug logs `Requesting app refresh caused by object update` for it.
I've diffed CronJob before and after updates, and I'm seeing that `/status/lastScheduleTime` and `/status/lastSuccessfulTime` are the only ones that has changed.
Am I doing something wrong?
