### DISCUSSION TITLE
argocd doesn't pass subchart's values while the same works with parameters.

### DISCUSSION THREAD

**Discussion by srinath92** [argoproj/argo-cd#17341] [General]
I'm using Argo App to deploy an app and pass in values file to a chart that has default values.yaml. The below doesn't work and it won't pick the values from the key `airflow`

Application.yaml
```
  source:
    chart: apache/airflow
    repoURL: europe-docker.pkg.dev/helm-charts
    targetRevision: 0.1.1
    helm:
      releaseName: airflow
      valueFiles:
        - values.yaml
``` 

values.yaml
```
dagRepository:
  name: "dags"
  branch: "main"
airflow:
  defaultAirflowTag: "2.6.3-python3.7"
  airflowVersion: "2.6.3"
  data:
    metadataConnection:
      host: prod-airflow-db
      db: airflow
dnsNames:
  flower: airflow-flower-nprod
  airflow: airflow-nprod
``` 

However if I move the above valueFile to parameters, the values are overridden and the chart deploys as expected.
```
  source:
    chart: apache/airflow
    repoURL: europe-docker.pkg.dev/helm-charts
    targetRevision: 0.1.1
    helm:
      releaseName: airflow
      parameters:
      - name: dagRepository.name
        value: "dags"
      - name: dagRepository.branch
        value: "main"
      - name: airflow.defaultAirflowTag
        value: "2.6.3-python3.7"
      - name: airflow.airflowVersion
        value: "2.6.3"
      - name: airflow.data.metadataConnection.host
        value: prod-airflow-db
      - name: airflow.data.metadataConnection.db
        value: airflow
      - name: dnsNames.airflow
        value: airflow-nprod
      - name: dnsNames.flower
        value: airflow-flower-nprod
```

I'm running argocd v2.8.9. Did I miss something here or is this a bug?

Just running `helm template . --values values.yaml` renders the chart properly. Not sure why argo wouldn't render the chart as expected using valueFiles

**Comment by srinath92** [comment]
I've raised it in slack already https://cloud-native.slack.com/archives/C01TSERG0KZ/p1708704412830939 but no response received, hence bringing up here.

**Comment by clarkmcc** [comment]
Noticing this issue as well with https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle

**Reply by gaborauth** [reply]
I ended up here after a day of good s.cking with nri-bundle and Argo CD... is there a solution for this in Argo CD? :)

**Reply by dmouse** [reply]
this is one of the patches that I applied, it just fix one issue but may that helps

```
patches:
  - patch: |
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1instance
        value: newrelic-develop
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=nri-bundle
```
