### DISCUSSION TITLE
App-of-Apps Pattern. Multiple Remote Sources

### DISCUSSION THREAD

**Discussion by VenutNSA** [argoproj/argo-cd#17359] [Q&A]
Hello, everyone!
I don't understand much about multi-cluster deployments using a single ArgoCD. But I want to ask the community about such a case study:

App-Of-Apps, which in the sources field can reference several other Git sources that would hold classic Applications. 
Something like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps-for-gitlabGroup
  namespace: argocd
spec:
  destination:
     name: cluster-dev-1
  project: dev
  sources:
    - repoURL: 'https://gitlab.com/org/team-1/project-1.git'
       path: apps/
       targetRevision: 'HEAD'
    - repoURL: 'https://gitlab.com/org/team-1/project-2.git'
      path: apps/
      targetRevision: 'HEAD'
   ...
      
   syncPolicy:
      managedNamespaceMetadata:
        labels:
          team: "1"
     automated:
       prune: true
       selfHeal: true
     syncOptions:
       - CreateNamespace=true
```

I think such a feature would be very handy for project management of specific team projects in git. What do you think?

Or maybe there is some more convenient/right option?

**Comment by kostis-codefresh** [comment]
> Or maybe there is some more convenient/right option?

I would use ApplicationSets and the [Git generator](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators-Git/) with a different folder or Git repo for each team

**Reply by kiransuryaefx** [reply]
Hi @kostis-codefresh , since you are familiar with argocd, It would be helpful if you help me out here. I have a root application (App-of-apps) pattern which deploys child apps. 
My question is I tried to fetch helm-values from diff source referencing from separate git repo.
```yaml
# mimir application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
  - repoURL: https://<my-own-repo>
    targetRevision: test/observability
    ref: values
    
  - repoURL: https://grafana.github.io/helm-charts
    chart: mimir-distributed
    targetRevision: 6.1.0-weekly.368
    helm:
      valueFiles:
      - $values/mimir/values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

 But the local helm values are not getting utlized. Is it the right to use Multiple source ref in such pattern and if not what would be the go to solution for it? And I don't want to switch to `ApplicationSets`

Ref: https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#:~:text=Helm%20sources%20can%20reference%20value%20files%20from%20git%20sources
