### DISCUSSION TITLE
Deploy one application to multiple namespaces within one cluster

### DISCUSSION THREAD

**Discussion by luismacosta** [argoproj/argo-cd#17350] [Q&A]
Dear ArgoCD team,

I would like to know if is possible to deploy the same app, with same values, to multiple namespaces, using the same ApplicationSet.
I've tried [this]( https://github.com/argoproj/argo-cd/issues/9508#issuecomment-1141235081) approach, without success. _namespace: '{{"{{"}}namespace{{"}}"}}'_ is not recognising the namespaces list elements
Thanks in advance

![Screenshot 2024-02-28 at 19 06 25](https://github.com/argoproj/argo-cd/assets/92727123/8ae950e9-3981-4e7c-baf5-440c6c665ac4)

Also tried with example from _List Generator_, but got the same error
Using the approach _Dynamically generated elements_, got the error _ApplicationSet.argoproj.io "" is invalid: spec.generators[0].matrix.generators[1].list.elements: Required value_
 https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-List/

**Comment by AnubhavSabarwal** [comment]
Could you try  {{namespace}}

**Comment by luismacosta** [comment]
Thank you for your response
Yes, already tried that, but got the same error: _namespaces "{{namespace}}" not found_
Here is the yaml. The idea would be to deploy the app in both namespaces test1 and test2

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/<myrepo>/test.git
            revision: master
            directories:
            - path: <path>
  - list:
      elements:
      - namespace: test1
      - namespace: test2
  template:
    metadata:
      name: "test"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: 'test'
      source:
        helm:
          valueFiles: ["values.yaml"]
          version: v3
        repoURL: https://github.com/<myrepo>/test.git
        targetRevision: master
        path: "test"
      destination:
        name: "test"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        retry:
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
          limit: 5
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - ApplyOutOfSyncOnly=true
```
