### DISCUSSION TITLE
When are build env vars evaluated during sync/deployments?

### DISCUSSION THREAD

**Discussion by busy-work-only** [argoproj/argo-cd#17364] [Q&A]
When are variables listed on the [Build Environment](https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/) page evaluated?

I have 2 applications that use helm via kustomize. One works one doesn't.
The one that works looks like:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: authelia
  repo: https://charts.authelia.com/
  version: 0.8.58
  releaseName: authelia
  namespace: $ARGOCD_APP_NAMESPACE
  valuesFile: values.yaml

```

The one that doesn't work looks like:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 12.12.10
  releaseName: psql-1
  namespace: $ARGOCD_APP_NAMESPACE
  valuesFile: psql-values.yaml

```

When syncing the second fails with the error: `one or more objects failed to apply, reason: namespaces "$ARGOCD_APP_NAMESPACE" not found (retried 5 times).`

My instinct is that the vars are evaluated before helm is invoked, but that doesn't seem to be the case.
