### DISCUSSION TITLE
Can you mix kustomize and helm with valuesObjects in one application?

### DISCUSSION THREAD

**Discussion by m8-t** [argoproj/argo-cd#17363] [Q&A]
Hey!

I am tinkering around with Argo CD right now. I am using a Helm Chart someone else wrote and I have a problem with a Ingress resource. I thought maybe I could mix Helm with valuesObject and a kustomize patch.

For example:

```yaml
spec:
  project: myproject
  sources:
    - kustomize:
        patches:
          - target:
              kind: Ingress
              name: ingress-from-the-chart
            patch: |-
              - op: add
                path: /spec/tls/hosts
                value:
                  - mytlshost.tld
              - op: add
                path: /spec/tls/secretName
                value: mycertificate
    - helm:
      chart: chart
      repoURL: https://doesntmatter.com
      targetRevision: 0.12.0
      valuesObject:
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: mytlshost.tld
                paths:
                  - path: /
        persistence:
          data:
            enabled: true
            retain: true
            storageClass: "nfs-client"
            accessMode: ReadWriteOnce
            size: 5Gi
```

I am not sure if the kustomize stuff is correct because I lack knowledge in Kustomize, thus I am not able to apply this, this gives me a huge error message with the most important part here:

`strict decoding error: unknown field "spec.sources[1].valuesObject"`

I played around with the `valuesObject` but mostly ending in bad formatted YAML. This YAML above is indeed valid but I think this does not work :(. Maybe someone got a hint? 

Thanks
