### DISCUSSION TITLE
"PostDelete" hook and ConfigMap/Secret for it?

### DISCUSSION THREAD

**Discussion by greeddj** [argoproj/argo-cd#17366] [Q&A] [answered]
Hello, Community! 👋🏻

I have a simple project where all of its resources are located outside the namespace. Periodically, the application is deleted, and external resources need to be cleaned up. Previously, additional tasks were required for this purpose. However, with the release of ArgoCD version 2.10, everything changed thanks to the introduction of the "PostDelete" hook, which is really cool and convenient.

The hook triggers after deleting all resources, which is logical. However, for example, I need a Secret and some other settings to successfully execute the hook and clean up external resources after deleting the application.

I found a solution and using environment variables.

But what if complex and huge configuration files are needed for the job in this hook, and environment variable substitution is not suitable?

Creating a ConfigMap or Secret with a "PostDelete" annotation leads to the entire stage being stuck on "Deleting".

Has anyone encountered something similar, where you need to add a configuration file for a job with a "PostDelete" hook?

**Comment by greeddj** [comment, marked as answer]
My questions are resolved, I found a stupidly simple solution.

It is enough to create "initContainer" and create Yaml files in a temporary volume via "echo", and then mount and use them in the main container.

For example:
```yaml
volumes:
- name: tmp-dir
  emptyDir: {}
initContainers:
- name: dumpConfigs
  image: busybox
  volumeMounts:
  - name: tmp-dir
    mountPath: /tmp
  command: ["sh", "-c"]
  args:
  - >
    echo {{ .Values.testDict | toYaml | quote }} > /tmp/testDict.yaml
```
