### DISCUSSION TITLE
Releasing from a mono repo based on project release tag

### DISCUSSION THREAD

**Discussion by kmcgrath** [argoproj/argo-cd#17390] [Q&A]
Have a mono repo with a number of projects within it that are released at different times.  The release for an individual project is marked by moving tags:
  * `release-[project-name]` for production
  * `stage-[project-name]` staging
  * `HEAD` constant deployment for development
  
  I was experimenting with  something like the following:
  
  ```
  spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/[redacted]/[redacted].git
              revision: HEAD
              directories: 
              - path: '*/cd'
              - path: '*/cd/**'
                exclude: true
          - clusters:
              selector:
                matchLabels:
                  cluster-type: application
                  "env": dev
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/[redacted]/[redacted].git
              revision: 'stage-{{index .path.segments 0}}
              directories: 
              - path: '*/cd'
              - path: '*/cd/**'
                exclude: true
          - clusters:
              selector:
                matchLabels:
                  cluster-type: application
                  "env": prod
```

The above would scan the repo for the tags, then associate those tags with the correct set of k8s clusters to deploy.  

However, the git generator will throw an error if the stage (or prod) tag doesn't already exist and kills the processing of the whole set.

Since new projects are added to the repo from time to time, it is a common possibility they may not have these tags yet until they go through a full release cycle.

Is there a way to do this?  Seems like a useful feature within a matrix that you could ignore the git generator error of the tag/SHA not being found and accept that as 0 matched applications. Not sure how to work around it without creating specific setups for each project within the repo or moving to git file path, which might work but throws off the current flow quite a bit.
