### DISCUSSION TITLE
Argocd ui shows only svc and ingress resources

### DISCUSSION THREAD

**Discussion by srujansagi** [argoproj/argo-cd#17411] [Q&A]
I came across this behavior where argocd UI shows only svc and ingress resources although when i check from kubectl  i see deployments,pods and other resources in the app namespace.

On further investigating i found the below difference in two app projects, the application using app-project 1 shows all the resources in arocd ui but for application using app-project2 shows only SVC and Ing objects in argcd UI.

App-project  1 has 
```
clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  ```
 App-project 2 has
 ```
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'
  destinations:
  - name: local
    namespace: semper-dev
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: runway.aa.com
    kind: '*'
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  - group: ""
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
   ```
   
   My Question is, for app-project 2 does it mean only SVC and ING are managed by argocd? What happens when a pod/deploy has any new changes would argocd pull those or not?
