### DISCUSSION TITLE
ApplicationSet pointing to different paths: How to reference an existing helm chart from e.g. artifactory?

### DISCUSSION THREAD

**Discussion by kastl-ars** [argoproj/argo-cd#17448] [Q&A]
HI everyone,

sorry if this has been asked before, I found nothing matching my question.

A customer has a ArgoCD applicationSet, pointing to different paths in a git repository for each "instance".
In the end, they would like to install a helm chart from e.g. an artifactory chart repository and supply different values for each instance.

Pseudo-Code would look something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: something
spec:
  generators:
[...]
  template:
[...]
      source:
        repoURL: https://example.com/git/application-repository.git
        path: path/to/the/instances/directory/{{instance}}
```

**What is the best way to declare the reference for the helm chart?**

I saw people putting a `Chart.yaml` into that directory adjacent to a `values.yaml`, where the chart is empty (aka has no templates directory containing YAML manifests) but has a dependency on the actual helm chart that they want to install.

While this technically works, I find it a little confusing to define a chart with a version that will only pull in another chart with a version.

```yaml
apiVersion: v2
name: my-name
type: application
version: 1.2.3
dependencies:
  - name: helm-chart-we-actually-want-to-install
    repository: https://artifactory.example.com/...
    version: 4.5.6
```

Putting a YAML file specifying a ArgoCD application into that directory, that directly references the helm chart, kind of defeats the purpose of the whole ApplicationSet. 
https://argo-cd.readthedocs.io/en/stable/user-guide/helm/

Maybe there are some recommendations or best practices? Problems people faced? Pros and Cons?

Thanks in advance,
Johannes
