### DISCUSSION TITLE
Cannot make `argocd app diff` work neither with `--local` nor with `--revision`

### DISCUSSION THREAD

**Discussion by bennesp** [argoproj/argo-cd#17482] [Q&A]
Hello, I have a repository with a structure like the following:
```
- renovate.json
- unrelated files
- unrelated dirs
    |- unrelated files
    |- ...
- parent folder
  |- subfolder
     |- gitops
        |- apps
           |- argocd
              |- app.yaml
              |- values.yaml
...
```

where `app.yaml` is an ArgoCD application with an helm chart as source, using multiple sources to get `values.yaml` as helm values.
<details><summary>`app.yaml` looks like the following</summary>
<p>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/myorg/myrepo
      targetRevision: HEAD
      ref: repo
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.55.*
      helm:
        valueFiles:
          - $repo/parent folder/subfolder/gitops/apps/argocd/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
```

</p>
</details>

Now, I want to upgrade the `targetRevision` and preview the diff.

I tried using `argocd app diff` without success. Without changing anything locally, expecting no changes at all, I tried (from subfolder directory in the locally cloned repository):
- `argocd app diff argocd --local $PWD/gitops/apps/argocd`
- `argocd app diff argocd --local $PWD/gitops/apps/argocd --server-side-generate`
- `argocd app diff argocd --local $PWD/gitops/apps/argocd --local-repo-root $PWD/../../ --server-side-generate`

However, I get tons of fake changes

Then I tried pushing a branch, without changes, and using `--revision`, but again without success.
- `argocd app diff argocd --revision my-branch`
  - generates an error `FATA[0002] rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal "renovate.json": Object 'Kind' is missing in '{`

I was not expecting this command to try parsing `renovate.json`.

Can someone help me in understanding how to use `argocd app diff`? I simply want to get an empty diff when comparing the live manifests with the desired ones when they are the same, and a real diff when they are not the same.

Thank you
