### DISCUSSION TITLE
Argo Notifications and Grafana

### DISCUSSION THREAD

**Discussion by egobude** [argoproj/argo-cd#17501] [General]
Hallo :)

I use Grafana and would like to send annotations to my grafana dashboard using argo notifications. I am using the official Helm Chart from ArgoCd and have already configured the following:

```

values: |
  notifications:
    triggers: 
      trigger.on-sync-succeeded: |
        - description: "Application syncing has succeeded"
          send:
          - app-sync-succeeded
          when: app.status.operationState.phase in ['Succeeded']
  configs:
    cm:
      service.grafana: |
        apiUrl: some value
        apiKey: some value
```

And my application configuration looks like this:

```

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-application
  namespace: argo-cd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: tag1|tag2
```

In the logs is see the following error message:

```
{"level":"info","msg":"Trigger on-sync-succeeded result: [{[0].xxxxxx-xxxxx  [app-sync-succeeded] true}]","resource":"argo-cd/some-application","time":"2024-03-13T06:20:53Z"}
{"level":"info","msg":"Sending notification about condition 'on-sync-succeeded.[0].xxxxxx-xxxxx' to '{grafana tag1|tag2}' using the configuration in namespace argo-cd","resource":"argo-cd/some-application","time":"2024-03-13T06:20:53Z"}
{"level":"error","msg":"Failed to notify recipient {grafana tag1|tag2} defined in resource argo-cd/some-application: notification service 'grafana' is not supported using the configuration in namespace argo-cd","resource":"argo-cd/some-application","time":"2024-03-13T06:20:53Z"}
```

I don't know exactly what is causing the error or how to fix it. It seems to have something to do with the namespace, even if I leave it out in the application manifest it still doesn't work. Does anyone have any tips for me? 

Thank you :)
