### DISCUSSION TITLE
Can an AppProject role grant access to another project?

### DISCUSSION THREAD

**Discussion by apa64** [argoproj/argo-cd#17559] [Q&A] [answered]
Is it possible to grant access to another project resources in an AppProject role?

Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject
spec:
  roles:
    - name: read
      groups:
        - READ
      policies:
        - p, proj:myproject:read, applications, get, myproject/*, allow
        - p, proj:myproject:read, applications, get, default/*, allow
    - name: mod
      groups:
        - MOD
      policies:
        - p, proj:myproject:mod, applications, *, myproject/*, allow
        - p, proj:myproject:mod, applications, *, default/*, allow
```

In my testing the users in READ and MOD groups were able to see only the Applications under `myproject`. The `default` project Applications were not visible.
