### DISCUSSION TITLE
Understanding SCM Provider Generator GitHub API Requests

### DISCUSSION THREAD

**Discussion by romancin** [argoproj/argo-cd#17575] [Q&A]
Hi Argo CD community! Currently, we have implemented Argo CD in our organization, with a multi-repo structure (each service has its source code and deploy manifests in an independent repository), and we are using a matrix generator between SCM Provider Generator and Cluster Generator to search for specific topics so Argo CD knows what to deploy on which cluster. We are using a GitHub App that allows us currently 12500 requests to the GitHub API per hour. We have been monitoring API requests consumption, because we have faced some rate limit problem due to Argo CD (probably due to this issue https://github.com/argoproj/argo-cd/issues/14420).

We are using currently only 7 `ApplicationSet`s like this (every AS matches different labels, but apart from that, all of them are exactly the same):
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "70"
  name: appset-infra
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - scmProvider:
          cloneProtocol: ssh
          filters:
          - labelMatch: argocd-infra
          github:
            allBranches: false
            organization: my_github_org
            appSecretName: myGitHubAppSecret
      - clusters:
          selector:
            matchLabels:
              argocd-infra: "true"
```
Our org has currently 500 repositories, but only 12 of them for the moment have the labels needed by ArgoCD.

With this configuration, we are having more or less 5000 API requests per hour, which seems a lot. We are trying to understand what is causing that high number of requests to improve it. We have disabled Argo CD polling completely using `timeout.reconciliation: 0s`, as every repo of the 12 with argocd-* topics configured have a webhook configured against Argo CD Application Controller, so we are sure these requests come only from SCM Provider Generator (the GitHub App is used exclusively for it).

Many questions arise.
* What polling interval has the SCM Provider Generator by default? Can we configure the polling interval to lower the API requests?
* If we add more ApplicationSet manifests, even with the same labels but with the Application Template pointing to another directory for example, will the API requests be increased? Or it depends only on the number of repositories in the organization?
* If we start putting argocd-* topic on more repos, will the API requests be increased? Or it depends only on the number of repositories in the organization?

If anyone can explain me how the API requests are made, I would be very grateful! Thank you very much for your help!
