### DISCUSSION TITLE
How to use the same notification webhook template for multiple "channels"?

### DISCUSSION THREAD

**Discussion by gustavo-maxmilhas** [argoproj/argo-cd#17620] [Q&A]
Hi all.
Suppose we have this notification setup for discord using webook:

**Service**:
``` 
notifiers:
  service.webhook.discord: |
    url: <DISCORD_WEBHOOK_URL>
    headers:
      - name: Content-Type
        value: application/json
```

**Template**:
``` 
templates:
 template.discord-template: |
   message: |
     Application {{.app.metadata.name}} is now running new version of deployments manifests.
   webhook:
     discord:
       method: POST
       body: |
         <BODY>
```

**Trigger**:
``` 
triggers:
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
        - discord-template
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

**Subscription**:
``` 
annotations:
  notifications.argoproj.io/subscribe.on-deployed.discord: ""
```

I can correctly get the correspondent webhook.
But, how do i deal with multiple channels?
I want to use the same template with different subscriptions for different channels (or in this case, different webhooks)

Do i need to create a template for each webhook service?
Cant i just reuse the same template?

The problem here is the need to define which webhook we are targeting directly in the template:
``` 
...
   webhook: <--
     discord:  <--
       method: POST
...
```

Shouldn´t the template be agnostic to the service being used? Or am i missing something?

Thanks!

ps: All these examples are for the ArgoCD helm chart configuration
