### DISCUSSION TITLE
Is there a way to pass down variables?

### DISCUSSION THREAD

**Discussion by brunocascio** [argoproj/argo-cd#17709] [Q&A]
I have the following appset:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-devops-backstage-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      requeueAfterSeconds: 30
      bitbucketServer:
        project: BACKSTAGE
        repo: catalog
        api: https://bitbucket.example.com
        basicAuth:
          username: admin
          passwordRef:
            secretName: bitbucket-sa
            key: password
  template:
    metadata:
      name: 'app-devops-backstage-pr-{{.number}}'
    spec:
      project: "app-devops-backstage"
      source:
        repoURL: https://bitbucket.example.com/scm/tools/backstage-cd.git
        targetRevision: HEAD
        path: 'preview'
      destination:
        name: management
        namespace: 'app-devops-backstage-pr-{{.number}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
```

and this is my desired kustomization.yaml file stored at `https://bitbucket.example.com/scm/tools/backstage-cd.git`:

```yaml
resources:
  - ./postgres
  - ./backstage

patches:
  - target:
       kind: VirtualService
       name: backstage
     patch: |
       - op: replace
         path: /spec/hosts
         value:
           - "backstage-{{.number}}.domain.com"
  ```

Is there a way to pass `{{.number}}` to the source repo?
