### DISCUSSION TITLE
Can I apply multisources in applicationset with multiple git repos

### DISCUSSION THREAD

**Discussion by AndreCbrera** [argoproj/argo-cd#17729] [Q&A] [answered]
Evening!

I have a question, I have been testing a application set with the next configuration:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - appName: horus-test1
        url: https://git/repo_values.git
        revision: master
        path: appfront
      - appName: horusbackend-test1
        url: https://git//repo_values.git
        revision: master
        path: appbackend
  template:
    metadata:
      name: '{{.appName}}-app'
    spec:
      project: default
      sources:
      - repoURL: '{{.url}}'
        targetRevision: '{{.revision}}'
        ref: values
      - repoURL: https://git/generic-chart.git
        targetRevision: master
        helm:
          valueFiles:
          - $values/{{.path}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.appName}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
```

For any reason I got this error..

```
spec.source.repoURL and either source.path, source.chart, or source.ref are required for source {https://servicio.mapa.gob.es/git/73084039K/generic-chart.git master &ApplicationSourceHelm{ValueFiles:[$values/horusbackend/values.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,} nil nil nil }

```

May I use an application CRD to apply or use this feature ?

thx

**Comment by jgwest** [comment, marked as answer]
Looking at the code, the error message is indicating that for this source:
```
      - repoURL: https://git/generic-chart.git
        targetRevision: master
        helm:
          valueFiles:
          - $values/{{.path}}/values.yaml
```
You must have at least one of these defined: `path`, `chart` or `ref`
