### DISCUSSION TITLE
application controller pod not ready due to `failed to list *v1alpha1.Application: invalid character '\x00' in string literal`

### DISCUSSION THREAD

**Discussion by cloudymax** [argoproj/argo-cd#17760] [Q&A]
Hi ArgoCD community friends,

This is the error I keep getting in my application controller pod logs:

```logtalk
E0406 08:17:18.395044       7 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: Failed to watch *v1alpha1.Application: failed to list *v1alpha1.Application: invalid character '\x00' in string literal
```

I can't list any apps and the web interface says I have no apps. I installed Argo CD on k3s via helm using the chart, `argo-cd-6.7.10` which deploys `v2.10.6`. I tried deleting the pod. I also tried making sure my argocd cli is up to date by running brew update/brew upgrade to get the latest, but even when I try to check it out with `argocd version`, I get this:

```logtalk
argocd version
argocd: v2.10.6+d504d2b.dirty
  BuildDate: 2024-04-05T03:31:56Z
  GitCommit: d504d2b1d92f0cf831a124a5fd1a96ee29fa7679
  GitTreeState: dirty
  GoVersion: go1.22.2
  Compiler: gc
  Platform: linux/amd64
W0406 10:22:25.749302  148868 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: failed to list *v1alpha1.Application: invalid character '\x00' in string literal
W0406 10:22:27.070188  148868 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: failed to list *v1alpha1.Application: invalid character '\x00' in string literal
W0406 10:22:29.105231  148868 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: failed to list *v1alpha1.Application: invalid character '\x00' in string literal
```

The final line there repeats till I git CTRL+C.

Right now, because I'm so confused, I just attempted to run brew update/brew upgrade on all packages, as well as apt update/apt upgrade, since this is a debian based system. After that, I checked my go version, in case that was the reason, but it lists:

```
go version go1.22.2 linux/amd64
```

My kubernetes version is:

```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7+k3s1
```

I haven't deployed any new argocd apps in weeks, except for allowing automatic minor bumps of the argocd helm chart itself from 6.7.6 to 6.7.10, walking it forward as the releases hit.

Any idea what could be going on?

**Comment by cloudymax** [comment]
I also can't uninstall Argo CD. I can remove the helm release, but it leaves behind the CRDs. I can't delete the `applications.argoproj.io` CRD, because it says the following when I try to describe it after a failed deletion attempt:

```yaml
Status:
  Accepted Names:
    Kind:       Application
    List Kind:  ApplicationList
    Plural:     applications
    Short Names:
      app
      apps
    Singular:  application
  Conditions:
    Last Transition Time:  2024-03-16T11:14:56Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2024-03-16T11:14:56Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
    Last Transition Time:  2024-04-06T08:43:13Z
    Message:               could not list instances: invalid character '\x00' in string literal
    Reason:                InstanceDeletionFailed
    Status:                True
    Type:                  Terminating
  Stored Versions:
    v1alpha1
Events:  <none>
```

I'm not sure what I can do, because I can't even list all the applications to see which one could be causing issues, but I can't destroy the cluster, because there's production apps running there :thinking:
