### DISCUSSION TITLE
Do I not understand --show-params? How do I see helm parameters/values from the CLI?

### DISCUSSION THREAD

**Discussion by gaima8** [argoproj/argo-cd#17778] [General]
Hey.

ArgoCD newbie here, sorry.

Having declaratively installed a few things from helm charts I can see a bunch of the parameters of those helm charts in the web interface. However, I cannot seem to get that information from the command line.
The `--show-params` option seems like it should show me this information, but it does not at all.

This is my Application
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.4
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

`argocd app get argocd/cert-manager --show-params` shows nothing about parameters set or not set.

```
$ diff -u <(argocd app get argocd/cert-manager ) <(argocd app get argocd/cert-manager --show-params)
--- /dev/fd/63  2024-04-08 21:35:52.759710532 +0100
+++ /dev/fd/62  2024-04-08 21:35:52.759710532 +0100
@@ -11,6 +11,9 @@
 Sync Status:        Synced to v1.14.4
 Health Status:      Healthy
 
+
+NAME  VALUE
+
 GROUP                         KIND                      NAMESPACE     NAME                                       STATUS     HEALTH  HOOK  MESSAGE
                               ServiceAccount            cert-manager  cert-manager-cainjector                    Synced                   serviceaccount/cert-manager-cainjector created
                               ServiceAccount            cert-manager  cert-manager-webhook                       Synced                   serviceaccount/cert-manager-webhook created
```

Adding `-o yaml` or `-o json` gets me the value I did set (installCRDs: true) but nothing else.

Am I missing something? Where are all the available values I haven't set?
