### DISCUSSION TITLE
App of Apps Pattern with Inherited Values FIle

### DISCUSSION THREAD

**Discussion by chrisblatt** [argoproj/argo-cd#17789] [Q&A]
I have 3 clusters and I have been testing out how to use App of Apps to bootstrap the clusters. I have a root app and then 2 example apps are defined in the helm chart this points too. 

My main idea/question was to use the values file I specify in the root app to set values in the child apps I create from this root app. Is it possible for the values/values file to be inherited and if so, how would that work?

Worth noting the root app helm chart is in a different repo than the helm charts the child apps point too, so not sure if multiple source applications come in to play or not.

Here is the root app:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: testing
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
    valueFiles:
      - ./env/dev
    path: apps/cluster-boostrap
    repoURL: https://github.com/xxx/repo1
    targetRevision: HEAD
```
Example app 1:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-1
  namespace: gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: testing
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: example-app-2
    repoURL: https://github.com/xxx/repo2
    targetRevision: HEAD
```
