### DISCUSSION TITLE
spec.values vs spec.valuesObject

### DISCUSSION THREAD

**Discussion by ro0NL** [argoproj/argo-cd#17835] [Q&A]
Hi!

we're trying to migrate from `spec.values` to `spec.valuesObject`.

Image updating seems to work still, but we notice log:

```
Could not update application spec
Error: template: chart/file.yaml:22:17: executing \"chart/file.yaml\" at <$app.webserver.upstream>: nil pointer evaluating interface {}.upstream%0A%0A
```

And im wondering what's going on, since i'd expected yaml=yaml and both specs should behave equivalent.

Chart:

```
data:
  api.conf: |
    {{- with $app.webserver.upstream }}
    upstream backend {
      {{- . | nindent 6 }}
    }
    {{- end }}
```

Values:

```
spec:
    source:
        helm:
            valuesObject:
                apps:
                    api:
                        webserver:
                            upstream: |
                                multi
                                line
```
