### DISCUSSION TITLE
ArgoCD Notification when application is deleted

### DISCUSSION THREAD

**Discussion by ppapp92** [argoproj/argo-cd#17888] [Q&A]
I know on-deleted triggers once the application **starts deleting** in ArgoCD. But I can't find any way to send a notification once the application is **actually removed** from ArgoCD.

Some of the applications I'm deleting may take a long time to fully delete and it would be very useful to notify once the application is removed from ArgoCD.

**Comment by ojel95** [comment]
Did you find a solution for this? I'm facing the same problem. I can notify that the application is being deleted but I can not know when the application is fully removed.

**Reply by ppapp92** [reply]
I ended up creating a Job that runs on a post-delete hook. ArgoCD will execute this after the application is fully deleted. The Job is just a simple Curl pod that sends an API call to the end point.

In my example I needed to know when the Nginx Ingress application was deleted. Since it takes time for the Service to get removed as the ALB can take time to delete in AWS.


**/templates/postDeletionWebhookJob.yaml:**
````apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-ingress-notification
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: nginx-ingress-notification
        image: quay.io/curl/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - >
            curl -X POST "URL HERE"
            -H "Content-Type: application/json"
            -d '
              {
                DATA HERE
                }
              }'
      restartPolicy: OnFailure
  backoffLimit: 10
````
**ArgoCD Apps values file:**
```yaml
argocd-apps:
  applications:
    - name: ingress-nginx
      namespace: argo-cd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
        - post-delete-finalizer.argocd.argoproj.io
        - post-delete-finalizer.argocd.argoproj.io/cleanup
      project: tools
      source:
        path: app/ingress-nginx
        repoURL: 
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```
