### DISCUSSION TITLE
Argo CD + ingress-nginx + service annotation not working

### DISCUSSION THREAD

**Discussion by clickersmudge** [argoproj/argo-cd#17909] [Q&A]
Hi,
I have a Kubernetes cluster in a Hetzner cloud.
Every time I install "ingress-nginx" I have to add the corresponding annotation.

```
kubectl annotate service --namespace ingress-nginx ingress-nginx-controller load-balancer.hetzner.cloud/location=<LOCATION> # nbg1
kubectl annotate service --namespace ingress-nginx ingress-nginx-controller load-balancer.hetzner.cloud/type=<TYPE> # lb11
kubectl annotate service --namespace ingress-nginx ingress-nginx-controller load-balancer.hetzner.cloud/use-private-ip=true
```

Without annotation, LoadBalancer has a pending status all the time.
![obraz](https://github.com/argoproj/argo-cd/assets/113194014/1280a54f-6b81-45d9-898a-6b4494e583a3)

I set up the whole deployment in Argo CD as helm-dependency in accordance with the example (https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency).

Chart.yaml

```
apiVersion: v2
name: ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 4.10.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.10.0"

dependencies:
- name: ingress-nginx
  version: 4.10.0
  repository: https://kubernetes.github.io/ingress-nginx
```

values.yaml
```
controller:
  nodeSelector:
    architecture: arm
  autoscaling:
    enabled: true
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/type: lb11
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
```

I added annotation I think everywhere I could, however, it doesn't work.

![obraz](https://github.com/argoproj/argo-cd/assets/113194014/e3976bbb-2c7d-4be2-931d-8a24d1776328)

I don't know if it's a problem with Chart, Argo CD or annotations.

**Comment by clickersmudge** [comment]
Sorry for the inconvenience. It turned out that the problem was in the values.yaml file
```
controller:
  nodeSelector:
    architecture: arm
  autoscaling:
    enabled: true
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/type: lb11
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
```

instead of

```
cert-manager:
  controller:
    nodeSelector:
      architecture: arm
    autoscaling:
      enabled: true
    service:
      annotations:
        load-balancer.hetzner.cloud/location: nbg1
        load-balancer.hetzner.cloud/type: lb11
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/disable-private-ingress: "true"
```
