### DISCUSSION TITLE
Argo CD + actions-runner-controller + values.yaml - ignored values file

### DISCUSSION THREAD

**Discussion by clickersmudge** [argoproj/argo-cd#17911] [Q&A]
Hi,
When it installs actions-runner-controller via command

```
helm upgrade actions-runner-controller actions-runner-controller/actions-runner-controller --create-namespace --install --namespace actions-runner-system --values values.yaml --version 0.23.7
```

Deployment works and the githubWebhookServer container is running.

![obraz](https://github.com/argoproj/argo-cd/assets/113194014/e2600d95-3950-46e7-8b3e-62872a1ea0ab)

However, when I move the deployment to Argo CD as helm-dependency in accordance with the example (https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency).

Chart.yaml
```
apiVersion: v2
name: actions-runner-controller
description: A Kubernetes controller that operates self-hosted runners for GitHub Actions on your Kubernetes cluster.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.23.7

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "0.27.6"

dependencies:
- name: actions-runner-controller
  version: 0.23.7
  repository: https://actions-runner-controller.github.io/actions-runner-controller
```

values.yaml
```
githubWebhookServer:
  enabled: true // default is false
```

![obraz](https://github.com/argoproj/argo-cd/assets/113194014/e992fbbc-e317-49a3-817a-821087b89dca)

![obraz](https://github.com/argoproj/argo-cd/assets/113194014/eb62780f-b88c-47e5-b660-edb2bb5bfcc6)

Not working. It seems, the values from the values.yaml file are ignored. By which githubWebhookServer, for example, does not work.
![obraz](https://github.com/argoproj/argo-cd/assets/113194014/b83c1ab9-b4ab-4330-af29-2bd39923c63a)

Can I ask for help?
