### DISCUSSION TITLE
Argo CD + cert-manager + CRDs problem

### DISCUSSION THREAD

**Discussion by clickersmudge** [argoproj/argo-cd#17910] [Q&A] [answered]
Hi,
I set up the whole deployment in Argo CD as helm-dependency in accordance with the example (https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency).

Chart.yaml
```
apiVersion: v2
name: cert-manager
description: cert-manager is a Kubernetes add-on to automate the management and issuance of TLS certificates from various issuing sources.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.14.4"

dependencies:
- name: cert-manager
  version: 1.1.1
  repository: oci://registry-1.docker.io/bitnamicharts
```

values.yaml
```
installCRDs: true
controller:
  nodeSelector:
    architecture: arm
webhook:
  nodeSelector:
    architecture: arm
cainjector:
  nodeSelector:
    architecture: arm
```

cert-manger works properly, however, when I try to add clusterissuer.yaml, I get an error
```
kubectl apply -f clusterissuer.yaml 
resource mapping not found for name: "letsencrypt-prod" namespace: "" from "clusterissuer.yaml": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "letsencrypt-staging" namespace: "" from "clusterissuer.yaml": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
ensure CRDs are installed first
```
![obraz](https://github.com/argoproj/argo-cd/assets/113194014/e98895b0-4486-4252-a380-e23133540320)

 It seems that despite the `installCRDs: true` option enabled in Helm values, it is not working.
Shouldn't Argo install CDRs?

As a workaround, I created a `templates` folder in the repository and copied the CDRs from the cert-manager repository (https://github.com/bitnami/charts/tree/main/bitnami/cert-manager/templates/crds) there.
![obraz](https://github.com/argoproj/argo-cd/assets/113194014/4404f4df-0701-4041-85a2-2a5fe5543eaf)

Shouldn't Argo install CRDS?
