### DISCUSSION TITLE
ApplicationSet CLI set, patch support

### DISCUSSION THREAD

**Discussion by CreMindES** [argoproj/argo-cd#17916] [Ideas]
One common-ish use case for an ArgoCD Application's lifecycle is to turn off auto-sync and set / patch the kustomize image (version) by either CI/CD or by the developer itself through the CLI or API. https://github.com/argoproj/argo-cd/issues/1843#issuecomment-520021729

In case there is a set of apps that always share the same version, it makes sense to put them into an ApplicationSet, but there is no easy way to update the version of them from CLI with one command.

Something along the lines of the following would be nice.

```bash
argocd app patch [ID] --patch= /spec/generator/... 
# or 
argocd app set [ID] set ... [generator specific] [or something else, maybe a kustomize generator]
```

Maybe there is also an easier or more idiomatic solution.

Example ApplicationSet

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: [AppSetName]
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
            - version: v1.0.0
      - list:
          elements:
          - name: service1
            image: hub.docker.com/...
            path: services/foo/service1/patches/dev
          - name: service2
            image: hub.docker.com/...
            path: services/foo/service2/patches/dev/
  template:
    metadata:
      name: playground-{{name}}
    spec:
      project: playground
      source:
        repoURL: https://github.com/foo/bar
        targetRevision: main
        path: "{{path}}"
        kustomize:
          images:
            - "{{image}}:{{version}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: playground
```

With this, at least someone with access to the repo or kubectl can update the version at once, but not through the API or CLI. The CI/CD would also have to fire number of 2n times service in applicationset requests. 2n, because one patch, one sync.
