### DISCUSSION TITLE
How to send notifications to the email address specified in the last synced commit?

### DISCUSSION THREAD

**Discussion by LagrangeH** [argoproj/argo-cd#18042] [Q&A]
I know I can get the commit author's email in template using `{{ (call .repo.GetCommitMetadata .app.status.sync.revision).Author }}` (I'll get something like `John Doe <john-doe@example .com>`). I want to send notifications for some triggers to this email address. Is it possible to do this?

Firstly, I can't figure out how to get just email from `(call repo.GetCommitMetadata .app.status.sync.revision).Author` (i.e. how to get `john-doe@example.com` from `John Doe <john-doe@example.com>`

Secondly, I can't figure out how to implement this. I think I could do something like this:

```yaml
data:
  ...
  subscriptions: |
    - recipients:
      - gmail: {{...}}
      triggers:
      - on-deployment
```
