### DISCUSSION TITLE
#Error in adding a sidecar container to the existing deployment through Argocd application.yaml

### DISCUSSION THREAD

**Discussion by Puvendhan** [argoproj/argo-cd#18082] [Q&A]
Hi, I want to add a sidecar container to the existing deployment which is deployed through Argocd application.yaml. Kindly suggest me the right way to add the sidecar to the existing deployment using Application.yaml without modifying the source repository manifests. I just want to add a sidecar to the existing deployment.

I tried in several ways by adding the below to the Application.yaml
"patchResource" , "patchStrategicMerge", "patchesStrategicMerge", "patchListStrategicMerge", "patches" by mapping the 
patch.yaml and adding inline patch content.

But it always giving the below error.

```
strict decoding error: unknown field "spec. patchStrategicMerge" , strict decoding error: unknown field "spec. patchFile",  strict decoding error: unknown field "spec. patch", strict decoding error: unknown field "spec. patchesStrategicMerge" 
Then i tried with Kustomization.yaml with inline kustomize to patch, it again gives different error "ComparisonError
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): failed to load kustomization.yaml: open <path to cached source>/charts/devlake/templates/kustomization.yaml: no such file or directory"

```

Inline kustomize patch on the application.yaml should apply the patch right?

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-inline-devlake
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devlake
    server: https://kubernetes.default.svc/
  project: default
  source:
    path: charts/devlake/templates
    repoURL: https://github.com/apache/incubator-devlake-helm-chart.git
    targetRevision: main
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: devlake-demo-lake
          patch: |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: devlake-lake
              labels:
                app.kubernetes.io/instance: devlake
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/name: devlake
            spec:
              selector:
                matchLabels:
                  app.kubernetes.io/instance: devlake
                  app.kubernetes.io/name: devlake
                  devlakeComponent: lake
              template:
                metadata:
                  labels:
                    app.kubernetes.io/instance: devlake
                    app.kubernetes.io/name: devlake
                    devlakeComponent: lake
                spec:
                  containers:
                    - name: cloudsql-proxy
                      imagePullPolicy: Always
                      image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
                      command: ["/cloud_sql_proxy",
                                "-instances=xxx:region_name:mysql-db=tcp:3306",
                                "-credential_file=/test/cloudsql/new.json",
                                "-log_debug_stdout=true"]         
                      ports:
                      - containerPort: 3306
                        protocol: TCP
                      resources:
                        limits:
                          cpu: 100m
                          memory: 100Mi
                        requests:
                          cpu: 10m
                          memory: 20Mi
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                      volumeMounts:
                      - mountPath: /secrets/cloudsql
                        name: mysql-db-cloudsql
                        readOnly: true
                  volumes:
                  - name: mysql-db-cloudsql
                    secret:
                      secretName: mysql-db-cloudsql
```
