### DISCUSSION TITLE
Helm Dependencies and automatic update

### DISCUSSION THREAD

**Discussion by clickersmudge** [argoproj/argo-cd#18083] [Q&A]
Hello,
Currently, most of my deployment on the cluster uses the Helm Dependencies template. (https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency)

Example of ingress-nginx
```
apiVersion: v2
name: ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 4.10.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.10.1"

dependencies:
- name: ingress-nginx
  version: 4.10.1
  repository: https://kubernetes.github.io/ingress-nginx
```

![obraz](https://github.com/argoproj/argo-cd/assets/113194014/d5e2eb92-4bf1-4461-8eaa-9c204e57bcda)
![obraz](https://github.com/argoproj/argo-cd/assets/113194014/4e8327f9-4a73-46dc-8cc3-be44775e53d2)

I was inspired by this article Auto-update helm chart version using ArgoCD (https://medium.com/@eduard.mihai.lemnaru/auto-update-helm-chart-version-using-argocd-4936933a2bac)
I wonder if it is possible to automatically update the Helm Chart (Helm Dependencies template), which is downloaded from the GitOps repository?
