### DISCUSSION TITLE
ApplicationSet: template dig function fails on cluster generator values

### DISCUSSION THREAD

**Discussion by bwelker-weave** [argoproj/argo-cd#18096] [Q&A]
I am trying to create an ApplicationSet in which the template uses `dig` on generator values, so that if an (optional) label exists then an additional value will be added. For example:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dig-values
spec:
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - clusters:
              selector:
                matchExpressions:
                  - key: some_label
                    operator: Exists
              values:
                some_extra_value: "foo: bar"
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{ .name }}-dig-values'
    spec:
      project: '{{ .name }}'
      destination:
        server: '{{ .server }}'
      source:
        helm:
          valueFiles:
            - values.yaml
          values: |
            {{ dig "values" "some_extra_value" "" . }}
        path: dir
        repoURL: 'git@github.com:my/repo.git'
```

When I add `some_label` to a cluster's labels, applicationset-controller throws this error:
`error calling dig: interface conversion: interface {} is map[string]string, not map[string]interface {}`

This seems quite similar to the `dig` example mentioned in the application controller [go template docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/#fallbacks-for-unset-parameters) except that I am using it with a cluster generator instead of a list generator.

Am I missing something? Is this a bug? Any kind of type conversion I can do to make it work? Other suggestions? Much appreciated!
