### DISCUSSION TITLE
Filtering clusters in ApplicationSets

### DISCUSSION THREAD

**Discussion by cloud-digitaltag** [argoproj/argo-cd#18234] [General]
Hi.
I have prepared clusters in ArgoCD with additional labels: env, type, cluster_name.
I have four clusters: cluster1, cluster2, cluster3, cluster4
I also have prepared following ApplicationSet:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: dev
            type: test
         # A key-value map for arbitrary parameters
        values:
          revision: app
          valuesFile: ../../deployments/app/dev_all.yaml
    - clusters:
        selector:
          matchLabels:
            env: dev
            type: test
          matchExpressions:
            - key: cluster_name
              operator: In
              values:
                - cluster1
                - cluster2
        # A key-value map for arbitrary parameters
        values:
          revision: app
          valuesFile: ../../deployments/app/dev_filter.yaml
  template:
    metadata:
      name: app-{{metadata.labels.hash}}
      namespace: argocd
        labels:
        env: "{{metadata.labels.env}}"
        version: "{{values.revision}}"
    spec:
      project: app
      source:
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - "{{values.valuesFile}}"
          parameters:
            - name: config.global.external_labels.cluster
              value: "{{name}}"
            - name: clusterType
              value: "{{metadata.labels.type}}"
          repoURL: https://github.com/<my_repo>/repo.git
        targetRevision: "{{values.revision}}"
        path: charts/app
      destination:
        name: "{{name}}"
        namespace: app
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

And for above configuration, selectors not working as I expected. When I look at the generated application config, for all clusters I see values files : dev_all.yaml, instead dev_filter.yaml for cluster1 and cluster2. I check a lot configs changes, but still the same results.
What mistake I make, that is not working ?
Thanks in advance.
