### DISCUSSION TITLE
ArgoCD automatic pruning does not delete externalsecrets that are no longer present in the application

### DISCUSSION THREAD

**Discussion by yanshein** [argoproj/argo-cd#18272] [Q&A]
We have enabled automatic pruning (See the settings below).
```
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```
But ArgoCD does not delete externalsecrets that are no longer present in the application.
I waited for 3 days to see if it needs longer time to clean things up.

After 3 days, it still has externalsecrets in the namespace that are no longer in the application.
We use helm to deploy the application.
