### DISCUSSION TITLE
How do I add helm `--set configs.params."server\.insecure"=true` value in ArgoCD UI

### DISCUSSION THREAD

**Discussion by soakes** [argoproj/argo-cd#18277] [General]
Hello,

I have a little bit of a problem, while argoCD works amazing, I wanted to try and get it managed inside argocd for easy upgrading using helm charts.

If I install via CLI, I would do the following:

```
helm install argocd argo/argo-cd \
  --namespace argocd \
  --set global.domain=argocd.example.dev \
  --set configs.params."server\.insecure"=true
 ```

Which works perfectly, however, when trying to use the `configs.params.server.insecure` param inside ArgoCD UI, it doesn't work.

<img width="1267" alt="image" src="https://github.com/argoproj/argo-cd/assets/813389/e4f66148-6cc5-4e1a-865d-248e7cb68266">

Confirmed by looking at the `argocd-rbac-cm` configMap (set as false) as well as the LB IP just goes in a loop when you curl it.  

I have even tried to restart argoCD after the changes using:

```
kubectl -n argocd rollout restart deploy/argocd-server
```

But its still looping as its not using the inseucre flag which I need for my reverse proxy.

I thought about adding it via the `values` instead manually like adding it in via CLI, however this doesnt't work and shows the following error:

<img width="1269" alt="image" src="https://github.com/argoproj/argo-cd/assets/813389/01d53d3f-c161-4123-9e52-43f23bc4cfac">

What am I doing wrong?  How can I get it ArgoCD UI to accept this option?

Just had a thought, maybe its a bad idea to get ArgoCD managed by ArgoCD anyways, as if it goes bad, your then messed up.  Whats your thoughts? how does everyone manage this?  just manually via helm?

**Comment by ChristianCiach** [comment]
The syntax should probably be:

```
configs.params.server\.insecure: true
```

**Reply by soakes** [reply]
Thank you very much @ChristianCiach .  
Applgies for the delay, I didnt see a notification from GH, but can confirm this works great thank you.

**Reply by OevreFlataeker** [reply]
I have exactly the same problem, but this solution did NOT work for me.

The only way to fix the problem for me is to specify it like this cascaded definition in the manifest view:

This works:
```
project: default
source:
  repoURL: https://argoproj.github.io/argo-helm
  targetRevision: 7.7.11
  helm:
    values: |
      configs:
        params:
          server.insecure: "true"
  chart: argo-cd
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

(put configs, params, server.insecure in separate lines)

This does NOT work:

```
project: default
source:
  repoURL: https://argoproj.github.io/argo-helm
  targetRevision: 7.7.11
  helm:
    values: |
      configs.params."server\.insecure": "true"
  chart: argo-cd
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```
(the same for the parameters view)

Configuring it via helm does work,
`helm upgrade -n argocd argocd argocd/argo-cd --set configs.params."server\.insecure"=true`
but no matter how I try to write it in the argo-cd parameter overwrite dialog, it does not work.
This helm command can be used to repair the setup once a sync "damaged" the configuration.
