### DISCUSSION TITLE
Can `resource.customizations` and `resource.customizations.ignoreResourceUpdates.*` be used together?

### DISCUSSION THREAD

**Discussion by andrii-korotkov-verkada** [argoproj/argo-cd#18403] [Q&A] [answered]
Hey.
I'm trying to configure
```
  resource.customizations.ignoreResourceUpdates.all: |
    jsonPointers:
    - /status
```
However, the argocd config map already has `resource.customizations` field where some health checks are configured. 
Would this work:
```
  resource.customizations: |
    ...
  resource.customizations.ignoreResourceUpdates.all: |
    jsonPointers:
    - /status
```
or do I have to integrate resource ignore in the `resource.customizations`. If later, how do I do this? Would it be something like the following?
```
  resource.customizations: |
    all:
      ignoreResourceUpdates:
        jsonPointers:
        - /status
    ...
 ```
