### DISCUSSION TITLE
Does globbing work in the destination namespace in projects?

### DISCUSSION THREAD

**Discussion by kbsquared** [argoproj/argo-cd#18529] [Q&A]
From what I can dig up this should work.  Any guidance on if this is a bug or what I'm doing wrong?

With a project like this:
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: integration-prj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: integration project

  sourceRepos:
  - https://github.com/something.git

  destinations:
  - namespace: integration-*
    name: nonprod-*
```

I'm getting this error:

```
resource :Namespace is not permitted in project integration-prj
```

The namespace name is integration-46374

For the reading I've found... 

This issue indicates this should work given the following library...

https://github.com/argoproj/argo-cd/issues/12383

https://github.com/gobwas/glob
