### DISCUSSION TITLE
dynamically inject env in ingress manifest using argocd

### DISCUSSION THREAD

**Discussion by sealab2066** [argoproj/argo-cd#18570] [Q&A]
Hello everyone!

I use ArgoCD to deploy applications, one of them being ingress-nginx-external

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-external
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/xxx/playground/argocd-playground.git
    path: resources/ingress-nginx-external
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
```

And here is the raw manifest from the repository from which i create the application

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-external
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.global-static-ip-name: ${RANDOM_PET}-ingress-nginx-external-us
spec:
  tls:
    - secretName: secret-xxx-com
  rules:
    - host: ${RANDOM_PET}-ingress-nginx-external.xxx.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
```

This code will be used by many people to create their own environments for testing, and I can't push the pet name to the repository. Therefore, each person will have a different "pet name".

The pet name is stored on each PC in the directory /tmp/random_pet.

cat /tmp/random_pet 
```
pleasant-iguana
```

I try to deploy with:
```
argocd app create ingress-nginx-external --file apps/ingress-nginx-external.Application.yaml
```
However, I have a problem with expanding the variable ${RANDOM_PET} during the creation of the application because the code in the repository uses ${RANDOM_PET} and it doesn't work dynamically.

How can I inject the real value in two places in my application locally? Maybe with kustomize, but I'm not sure. If anyone has experience, maybe you can show me how to do this.

**Comment by crenshaw-dev** [comment]
I'd recommend implementing your ingress manifest as a Helm chart and inject the var as a Helm value. 

Then you can add the value to your Argo CD Application.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    repoURL: https://gitlab.com/xxx/playground/argocd-playground.git
    path: resources/ingress-nginx-external
    targetRevision: HEAD
    helm:
    values: |
      pet: RANDOM_PET
```

And ask your developers to replace RANDOM_PET with their value.

```shell
sed "s/RANDOM_PET/$(cat /tmp/random_pet)/" apps/ingress-nginx-external.Application.yaml > /tmp/app.yaml
argocd app create ingress-nginx-external --file /tmp/app.yaml
```
