### DISCUSSION TITLE
Enable AAD OIDC Signin with Federated Credential

### DISCUSSION THREAD

**Discussion by manish222agr** [argoproj/argo-cd#18582] [Q&A]
I want to implement the argocd portal signin using OIDC. I created an AAD App as er guidelines in https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/#entra-id-app-registration-auth-using-oidc.

I want to use the federated credentials, but cannot see any guidelines on it.

I tried to not create secret, but I am getting this error when I try to signin.

failed to get token: oauth2: "invalid_client" "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. 

Please suggest steps on how an I use federated credentials.

**Comment by demolitionmode** [comment]
Has anyone been able to solve this? I'm facing the same error. What information is needed to understand the issue?

**Comment by kristeroksnes** [comment]
Same issue here

**Comment by tomtreffke** [comment]
Hi @manish222agr, hope you figured it out by now, but for anyone else looking for this:

- make sure you set annotations, not labels on the service account
- on the App-Registration (not Enterprise App) under API Permissions, make sure the Permissions-Name is "User.Read", not "User.ReadAll"

my OIDC Config on the helm Chart looks like this:

```yaml
oidc.config: |
        name: Azure # MANUALLY CHANGED FROM 'AzureAD'
        issuer: https://login.microsoftonline.com/<tenant-id>/v2.0
        clientID: <application (client) id>
        azure: 
          useWorkloadIdentity: true
        requestedIDTokenClaims:
          groups:
            essential: true
            value: "SecurityGroup"
        requestedScopes:
        - openid
        - profile
        - email
```



```yaml
server:

serviceAccount:
    # -- Create server service account
    create: true
    # -- Server service account name
    name: argocd-server
    # -- Annotations applied to created service account
    annotations: 
      azure.workload.identity/client-id: "a123-b123-c123"

```

BUT

```yaml
podLabels: 
    azure.workload.identity/use: "true"
```

credit @rooftop90
