### DISCUSSION TITLE
Is there a breakglass/in case of emergency solution to stop a single application from syncing?

### DISCUSSION THREAD

**Discussion by aturcott** [argoproj/argo-cd#18635] [Q&A]
We're using the argo sync application to manage hundreds of microservices on several different AKS clusters from a single git repo. Is there a way to easily prevent a single application from auto syncing in the case of an incident or maintenance or such? Right now we're going into the UI to the argo-sync application, using the "disable auto-sync" button to turn syncing off for every single application being managed, then going to the specific application-set in the UI, and editing the live manifest to disable self-heal. If we try using the "disable auto-sync" button for a single application without disabling auto-sync for the argo-sync application (which in turn prevents the many other applications from syncing) then argo-sync will just turn it back on.

```yaml
- apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo-sync
      namespace: argocd
    spec:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: ""
        repoURL: ""
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

![image](https://github.com/argoproj/argo-cd/assets/73724286/2de0b6f0-69f7-4a6b-a7c2-7241b34318a4)
