### DISCUSSION TITLE
JQ path expression does not work in `jsonPointers`?

### DISCUSSION THREAD

**Discussion by davidshen84** [argoproj/argo-cd#18807] [Q&A] [answered]
Hi,

I am trying to configure the `ignoreDifferences` property of my application by following [this guide](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/).

I added this code to my application spec, and it worked as expected.

```yaml
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
```

However, using the JQ expression in `jsonPointers` does not seem to have any effect.

```yaml
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - .spec.replicas
```

I wonder if I translated the JSON patch syntax to JQ path syntax correctly.

Thanks
