### DISCUSSION TITLE
Deploy Application to different namespace than ApplicationSet

### DISCUSSION THREAD

**Discussion by florianmutter** [argoproj/argo-cd#18835] [Q&A]
It seems that applications are always in the same namespace as applicationsets. We tried setting a namespace in `template.metadata.namespace` like in the following example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: dev-1
                  url: https://kubernetes.default.svc
          - git:
              repoURL: https://github.com/example/new-deployment-process.git
              revision: HEAD
              directories:
                - path: "*/services/*/k8s/overlays/development"
                - path: "*/apps/*/k8s/overlays/development"
  template:
    metadata:
      name: 'development-{{index .path.segments 0}}-{{index .path.segments 2}}-{{.cluster}}'
      namespace: '{{index .path.segments 0}}'
    spec:
      project: development
      source:
        repoURL: https://github.com/fadi-nextgen-shop/new-deployment-process.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        plugin:
          name: kustomize-env
          env:
            - name: TEAM
              value: "{{index .path.segments 0}}"
            - name: SERVICE_NAME
              value: "{{index .path.segments 2}}"
            - name: COMMIT_SHA
              value: ${ARGOCD_APP_REVISION}
            - name: ENV
              value: development
      destination:
        server: '{{.url}}'
        namespace: '{{index .path.segments 0}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
 ```
 but the application is always in the argocd namespace. We also tried a static value and adding the namespace to `applicationsetcontroller.namespaces` but nothing worked.
 
 **NOTE:** The application it self does what it is supposed to do and can deploy everything it wants. Its only the application itself that is in the wrong namespace
