### DISCUSSION TITLE
Two Git Generators Using pathParamPrefix not working

### DISCUSSION THREAD

**Discussion by srkprof** [argoproj/argo-cd#18841] [Q&A] [answered]
Below is the sample code, in which I am trying to use two git generators. One will fetch information related to the application and the child generator will get the information related to image tags and other details related to version. This does not generate any application for some reason. Any suggestions? Am I missing something?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-two-git
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/myrepo/test-app
              revision: HEAD
              files:
                - path: applications/env/**/matrix.json
              pathParamPrefix: app
          - git:
              repoURL: https://github.com/myrepo/test-app
              revision: HEAD
              files:
                - path: "version/{{.env}}.json"
              pathParamPrefix: ver
  template:
    metadata:
      name: '{{.cluster}}-{{.namespace}}-{{app.path.basename}}'
      labels:
        versioningfile: '{{ver.path.filename}}-'
    spec:
      destination:
        namespace: '{{.namespace}}'
        name: '{{.cluster}}'
      project: '{{.project}}'
      sources:
        - repoURL: https://github.com/test-{{.cluster}}
          targetRevision: '{{.rev}}'
          path: '{{app.path.path}}'
```
