### DISCUSSION TITLE
Variable substitution

### DISCUSSION THREAD

**Discussion by kaykhan** [argoproj/argo-cd#18919] [Q&A]
I have an argocd application

https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: values
```

my values.yaml looks like this

```
nameOverride: ${db_name}
...
someOtherField: abc-${db_name}-def
```

is there some way for me to inject the value of db_name into the .yaml

Such that any occurrence of ${db_name} found in the .yaml will get substituted for a value.
