### DISCUSSION TITLE
Ability to turn off version checking of the k8s api when adding clusters

### DISCUSSION THREAD

**Discussion by warroyo** [argoproj/argo-cd#18920] [Q&A]
Hi,

I am working with a cluster that's not really a k8s cluster and is just a k8s api, very similar to KCP. This api works just fine with `kubectl` as well as flux. I have been trying to get argo-cd to work with it, but the cluster registration stays in a failed state due to `the server could not find the requested resource`  when trying to query the  `/version` endpoint on the cluster. When I add an app it errors out with this message. 

```
time="2024-07-02T16:22:19Z" level=error msg="finished unary call with code Unknown" error="error getting cached app managed resources: ComparisonError: Failed to load live state: failed to get cluster info for \"https://mycluster.com/\": error synchronizing cache state : the server could not find the requested resource;ComparisonError: Failed to load target state: failed to get cluster version for cluster \"https://mycluster.com/\": failed to get cluster info for \"https://mycluster.com/\": error synchronizing cache state : the server could not find the requested resource" grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2024-07-02T16:22:19Z" grpc.time_ms=1.164 span.kind=server system=grpc
```

is there a way to prevent argo from running this check and instead just connect to the cluster?

**Comment by martivo** [comment]
Did you ever find a way? I am having the same issue.

**Reply by warroyo** [reply]
My solution is more of a temporary workaround, but what I ended up doing was running mitm proxy in the cluster with a simple filter that mocks the version api response. Then setting Argo to use the proxy.

**Reply by martivo** [reply]
I managed to work around the issue when using KCP as the cluster target with this configuraiton from https://docs.kubestellar.io/release-0.25.1/Community/partners/argocd/
Related Helm chart values:
```
argocd:
  configs:
    clusterCredentials:
      kcp-root:
        server: https://.../clusters/root
        labels: {}
        annotations: {}
        config:
          bearerToken: "..."
          tlsClientConfig:
            insecure: false
    cm:
      resource.exclusions: |
        - apiGroups:
          - "tenancy.kcp.io"
          kinds:
          - ClusterWorkspace
```
NB: the exclusion has to be global, not on the project level to work. Projects also enable to exlcude resources but that did not work.
