### DISCUSSION TITLE
Argo CD Logout Issue: Redirects Without Requiring Re-authentication

### DISCUSSION THREAD

**Discussion by kennywarwick** [argoproj/argo-cd#18948] [Q&A] [answered]
Hello,

I'm currently using Argo CD for managing applications in my Kubernetes cluster and have encountered an issue with the logout functionality. When I attempt to log out from the Argo CD UI, it redirects me back to the login page as expected. However, when I click on the login button again, I'm immediately logged in without being prompted to re-enter my credentials. This behavior suggests that the session is not being fully terminated upon logout.

Here are the details of my setup:

- **Argo CD Version**: v2.11.3
- **Authentication Method**: OIDC with ADFS
- **Domain Configuration**: I have configured a custom domain for Argo CD as specified in my file under the `global.domain` setting.
   ```
   oidc.config: |
      name: Azure
      issuer: https://XXXXXX.com/adfs
      clientID: <XXX>
      clientSecret: <XXX>
      requestedIDTokenClaims:
        groups:
          essential: true
      userInfoCacheExpiration: "1m"
      requestedScopes:
        - openid
        - profile
        - email
      logoutURL: https://XXXXXX.com/logout?client_id=<XXX>&id_token_hint={{token}}&post_logout_redirect_uri=<URL>
      skipAudienceCheckWhenTokenHasNoAudience: true
    ```

Expected Behavior:
After logging out, I expect to be required to re-enter my credentials upon attempting to log back in.

Actual Behavior:
After logging out and clicking the login button, I am immediately logged back in without being prompted for credentials.

Steps to Reproduce:
1. Log in to the Argo CD UI.
2. Click on the logout button.
3. Click on the login button on the redirected login page.
4. Observe that no credentials are required, and I am logged back in directly.

I'm not sure if this is a configuration issue on my end or a potential bug with Argo CD's logout functionality. Has anyone else experienced this issue, or can provide guidance on ensuring a complete logout process that requires re-authentication?

Thank you for your assistance!
