### DISCUSSION TITLE
Avoid syncing a specific resource

### DISCUSSION THREAD

**Discussion by winterrobert** [argoproj/argo-cd#18941] [Q&A]
Is it possible to ignore syncing a specific resource (and not all resources of that Kind), like a specific PVC that has been provisioned through an operator and ends up as OutOfSync in Argo?

`OutOfSync (This resource is not present in the application's source. It will be deleted from Kubernetes if the prune option is enabled during sync.)`

I've tried all combinations of `ignoreDifferences`, with or without jqPathExpressions, but ignoreDifferences only seems to react to changes _within_ a specific resource and it's not possible to make ArgoCD ignore the whole resource using ignoreDifferences right?

```
  ignoreDifferences:
  - kind: PersistentVolumeClaim
    # group: "" # This is the same as the core group
    # name: nameofmyresource
    # namespace: thenamespaceoftheresource
    jqPathExpressions:
    - .
```

My understanding:
- If I want to ignore all resources of a specific Kind: [Resource Exclusion](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion)
- If I want to ignore changes to properties of a resource: [ignoreDifferences](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration)
- If I want to ignore syncing a specific resource: ?

**Comment by ChristianCiach** [comment]
I wonder why this even happens to you. I have many resources created by operators (Rook, Cloudnative-pg,...) and none of these are flagged as "out of sync" by Argo CD.

**Reply by ChristianCiach** [reply]
Maybe your operator copies the tracking-label of argo-cd to the generated resources?

**Comment by winterrobert** [comment]
Yeah my operator (which is managed by ArgoCD) was copying all labels from the operator to it's child resources, including the "managed by Argo CD" label. I ended up configuring it so that it skipped copying the Argo CD label which felt like the right solution.

**Reply by Fab-T** [reply]
I am having the same issue where I would like argoCD to not sync a specific resource.
Currently I am using External Secret Operator to manage my http-creds-template secret (which contains a token).
Since I am in full GitOPS mode, I cannot write the token in my helm values , therefore writing:
    https-creds:
      url: https://myGit-repo-url
      password: "ESO-Synced"  # managed in ESO
 > this works perfectly since I created an ES which will update the value (in merge mode).
 Yet, my ArgoCD tile will remain in "out-of-sync" since the password DO NOT MATCH ( once ESO has done it s job ).

Last update on this topic is here > https://github.com/argoproj/argo-cd/issues/12686

**Comment by andrii-korotkov-verkada** [comment]
I had the same issue when trying to exclude whole resource and ended up excluding all major paths instead.

**Reply by muawiakh** [reply]
But if you also skip `/kind` in both `jqPathExpressions` or `jsonPointers`, it will give you an error when syncing:

```
  ignoreDifferences:
  - group: <group>
    kind: <kind>
    jsonPointers:
    - /metadata
    - /spec
    - /apiVersion
    - /kind
    
  OR
  
    ignoreDifferences:
  - group: <group>
    kind: <kind>
    jqPathExpressions:
      - .
```

**Error**
```
Failed to normalize target resources: Object 'Kind' is missing in 'null'
```
