### DISCUSSION TITLE
Notifications: slack.token does not work, slack-token does. Why?

### DISCUSSION THREAD

**Discussion by thiagowfx** [argoproj/argo-cd#18996] [Q&A] [answered]
I am using the [ArgoCD helm chart](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd) for deployment.

Relevant snippet of `values.yaml`:

```
argo-cd:
  notifications:
    enabled: true

    secret:
      # The secret value is managed by External Secrets.
      create: false
      name: argocd-external-secret

    notifiers:
      service.slack: |
        token: $slack-token
```

The secret is manually created, via https://external-secrets.io/latest/. It looks like this:

```
$ kubectl describe secret -n argocd argocd-external-secret
Name:         argocd-external-secret
Namespace:    argocd
Labels:       app.kubernetes.io/part-of=argocd
              argocd.argoproj.io/instance=argocd
              reconcile.external-secrets.io/created-by=<hash>
Annotations:  reconcile.external-secrets.io/data-hash: <hash>

Type:  Opaque

Data
====
dex.github.clientSecret:  40 bytes
slack-token:              54 bytes
```

I would like to rename the secret key to `slack.token` for consistency with Github SSO ([docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#2-configure-argo-cd-for-sso)) i.e. `$dex.github.clientSecret`.

However, when I update both `values.yaml` and the secret key to `slack.token` (with a period instead of a dash), I get authentication failures (as seen in the logs of `argocd-notification-server`).

Why is that?

I also tried with `slack\.token` (attempt to escape the period) to no avail.
