### DISCUSSION TITLE
Deploy Helm charts by ApplicationSet for Gitlab groups

### DISCUSSION THREAD

**Discussion by behdadkh** [argoproj/argo-cd#19031] [Q&A]
Hello!

I'm trying to write a ApplicationSet + Generators for a Gitlab **group** so at any point of time a repository within this group decided to have a deployment, they just need to build and publish their Helm chart. 

For this purpose, I am using the SCMProvider Generator for Gitlab.

My question is, how should I setup my ApplicationSet so for all the available Helm packages under the Gitlab group, an equivalent Argo Helm application gets created? 

The problem is, when I configure the SCMProvider for a Gitlab group: 

```yaml
generators:
  - scmProvider:
      gitlab:
       group: "8675309"
       ...
```

The provider does not return the Gitlab `project_id` of the scanned repositories so that I could generate the following Gitlab `repoUrl` path:

```yaml
template:
    metadata:
      name: '{{ .repository }}'
    spec:
      source:
        repoURL: 'https://gitlab.com/api/v4/projects/[PROJECT_ID]/packages/helm/stable'
        targetRevision: '*'
        chart: "chart"
        helm:
          releaseName: "releaseName"
```

An alternative could have been using the Gitlab group package API: `https://gitlab.com/api/v4/groups/[GROUP_ID]/packages/?package_type=helm` to get all the Helm packages, but this endpoint response is not compatible with Helm as it does not contain the `index.yaml` file.

Or, write a Plugin Generator which returns Gitlab repositories' `project_id` and combine it with the SCMProvider within a Matrix generator..

Any thoughts?

Thanks!
