### DISCUSSION TITLE
Helm apps and CRDs upgrade

### DISCUSSION THREAD

**Discussion by quyet-nguyen** [argoproj/argo-cd#19044] [Q&A]
So I installed strimzi as helm application :
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $clusterName }}-strimzi-kafka-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: strimzi-kafka-operator
      repoURL: https://strimzi.io/charts/
      targetRevision: 0.39.0
      helm:
        parameters:
          - name: watchAllNamespaces
            value: "true"
        valueFiles:
          - $values/root/strimzi-values.yaml
 ...
```

Now I want to upgrade it to latest version:
- I changed the targetRevision to 0.42.0: the operator image updated fine
- All the CRDs are not update as expected, 
I run `kubectl apply -f strimzi-crds-0.42.0.yaml` to update the CRDs to latest version
- Now all the CRDs are recollided back to the old version because they're under kafka operator app

So how can I upgrade them ? 
And which should be the right way to manage CRDs on helm apps ?

Thanks
