### DISCUSSION TITLE
not able to deploy n8n oci chart via argocd

### DISCUSSION THREAD

**Discussion by kumari-shubham** [argoproj/argo-cd#19047] [Q&A]
error:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build <path to cached source>/staging/n8n-cluster --enable-helm` failed exit status 1: Error: Error: could not find protocol handler for: : unable to run: 'helm pull --untar --untardir <path to cached source>/staging/n8n-cluster/charts --repo 8gears.container-registry.com/library/n8n n8n --version 0.23.1' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-1677674532/helm HELM_CACHE_HOME=/tmp/kustomize-helm-1677674532/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-1677674532/helm/.data] (is 'helm' installed?): exit status 1
secret in argocd
```

```
apiVersion: v1
kind: Secret
metadata:
  name: my-oci-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: n8n-oci-repo
  url: 8gears.container-registry.com/library/n8n
  enableOCI: "true"
  type: helm
  ForceHttpBasicAuth: "true"
```

using this helm chart

```
helmCharts:
  - name: n8n
    releaseName: n8n-cluster
    repo: 8gears.container-registry.com/library/n8n
    valuesFile: values.yaml
    version: 0.23.1
```
