### DISCUSSION TITLE
Where is the application revision history stored?

### DISCUSSION THREAD

**Discussion by andrii-korotkov-verkada** [argoproj/argo-cd#19097] [Q&A]
Hey. There's this parameter `revisionHistoryLimit` controlling the history of the app visible in History And Rollback. I wonder where is it stored? Is it on application object itself or some other storage? I have a large application with 1000+ objects in some clusters and wonder if I should set `revisionHistoryLimit` above 0 and not hit any ArgoCD or Kubernetes limits (there's been a trouble of putting it in the app of apps due to hitting 256KB size limit). Thank you.

**Comment by ChristianCiach** [comment]
I can see it on the `Application` object in `status.history`. Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {...}
spec: {...}
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-06-04T13:50:37Z"
    deployedAt: "2024-06-04T13:50:37Z"
    id: 0
    initiatedBy:
      username: admin
    revision: 7d842b2031525fbace9d450835df6f1eefda123c
    source:
      path: netshoot
      repoURL: https://git.services.ems/christianc/gitoops.git
      targetRevision: HEAD
  - deployStartedAt: "2024-06-07T14:16:02Z"
    deployedAt: "2024-06-07T14:16:02Z"
    id: 1
    initiatedBy:
      username: admin
    revision: ba585fa7db43ca19ae7fbb44c6030990f886b1ea
    source:
      path: netshoot
      repoURL: https://git.services.ems/christianc/gitoops.git
      targetRevision: HEAD
                    
```
