### DISCUSSION TITLE
how do I configure GithubAppPrivateKeySecret

### DISCUSSION THREAD

**Discussion by rochana-atapattu** [argoproj/argo-cd#19141] [Q&A] [answered]
I see there is a variable to set https://github.com/argoproj/argo-cd/blob/505998298fbfca73575219b1e62a836860bb1bfc/util/settings/settings.go#L331
but what i can't figure out is how to set it. I have GitOps repos in couple of different github orgs which deploy to the same cluster. I have created a Github App and installed in each or which necessary access. My current setup creates a repo-cred secret for each repo. Since I use the same GitHub app if I could share the GithubAppPrivateKeySecret my setup could be more clear.

**Comment by rochana-atapattu** [comment, marked as answer]
anyone looking for the answer
```yaml
configs:
  cm:
    dex.config: |
      connectors:
        # GitHub example
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $dex-github-client-secret:clientID
            clientSecret: $dex-github-client-secret:clientSecret
            orgs:
            - name: xxxxxxx

    repositories: |
      - githubAppPrivateKeySecret:
          name: argo-cd-github-app-creds
          key: githubAppPrivateKey
        githubAppID: xxxxx
        githubAppInstallationID: xxxxxxx
        type: git
        url: "https://github.com/example/repo"
```
