### DISCUSSION TITLE
applicationset: deploy nginx using helm

### DISCUSSION THREAD

**Discussion by mscrocdile** [argoproj/argo-cd#19140] [General]
Please help me to understand how it works. 
I have this applicationset.
```
cat <<EOF | kubectl apply -f -
    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: cs-applicationset
      namespace: argocd
    spec:
      generators:
        - git:
            repoURL: https://github.com/PRD/compose.git
            revision: master
            directories:
              - path: kubernetes/argocd/applications/*
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          project: default
          source:
            repoURL: https://github.com/PRD/compose.git
            targetRevision: master
            path: '{{path}}'
          destination:
            server: https://kubernetes.default.svc
            namespace: '{{path.basename}}'
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true   
    EOF
```
Now i want to create test web nginx **using helm**. So i created testweb folder and put this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://charts.helm.sh/stable
  destination:
    name: https://kubernetes.default.svc
    namespace: testweb
```
Is this correct way to create helm?
Because this creates another application (first is in ArgoCD namespace and second in my-git-folder namespace). 
But there is **no nginx pod**. (no resources in testweb namespace)

**Comment by rjshrjndrn** [comment]
repoURL should be the helm repo url of nginx ingress. Something like this
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.3.0 # Specify the version you want to deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
