### DISCUSSION TITLE
Include Files Outside of Helm Chart in ApplicationSet

### DISCUSSION THREAD

**Discussion by zip-chanko** [argoproj/argo-cd#19169] [Ideas]
Hi, I'm exploring AppSet for deploying helm charts from remote repo but reach to the point where the limitation of the helm which is not supported including files that are not part of the chart. My app charts are stored in http helm repo and pass the values files from gitops repo using multiple sources template. I can pass the value files but not additional files which I would like to create them as a configmap. Helm will ignore those additional files since they are not part of the chart. May I know how do you achieve in any alternative ways?

There is an opened GH issue of the limitation.  https://github.com/helm/helm/issues/3276

My AppSet and dir structure looks like this.

```
# dir structure
.
├── apps/
│   ├── guestbook/
│   │   ├── dev.yaml
│   │   ├── appsettings/
│   │   │   ├── dev.json <---- read the file and create a configmap
│   │   │   └── ...
│   │   └── ...
│   ├── sock-shop/
│   │   ├── dev.yaml
│   │   └── appsettings/
│   │       ├── dev.json
│   │       └── ...
│   └── ...
├── appsets/
│   ├── dev.yaml
│   └── ...
└── global/
    ├── dev.yaml
    └── ...
```

```yaml
# appset
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
  - "missingkey=error"
  generators:
  - git:
      repoURL: https://github.com/argoproj/argo-cd.git
      revision: HEAD
      pathParamPrefix: app
      directories:
      - path: "apps/*"
      values:
        app: '{{.app.path.basenameNormalized}}'
  template:
    metadata:
      name: 'dev-{{.values.app}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      project: "my-project"
      sources:
      - repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        ref: values
      - repoURL: https://example.com/example-community/helm-charts
        chart: '{{.values.app}}'
        targetRevision: ^0.2
        helm:
          skipCrds: true
          passCredentials: true
          releaseName: 'dev-{{.values.app}}'
          valueFiles:
          - '$values/global/apps/dev.values.yaml'
          - '$values/{{.app.path.path}}/dev.values.yaml'
```
