### DISCUSSION TITLE
ArgoCD Application silently ignores when duplicate helm values are used for the same helm chart in the same Argo App

### DISCUSSION THREAD

**Discussion by jayganesh-asu** [argoproj/argo-cd#19195] [Q&A] [answered]
Easy to reproduce: Deploy any Argo App with duplicate helm values, however, it didn't report any `SyncError` or `ComparisonError` when syncing.

Observation: Argo App was synced and healthy when having repetition or duplicate helm values with different valid configurations.
Seems like it was silently ignored, shouldn't `helm lint` under the hood have reported error for duplication? We are using Helm 3.

Below is sample:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-argo-app
  namespace: argocd
spec:
  source:
    targetRevision: 1.2.3
    helm:
      values: |
        someValueA:
          someSubValueA:
            enabled: false
        someValueA:
          someSubValueB:
            enabled: true
```

NOTE: Argo App was marked as synced and healthy even upon resyncing. I could see the latest commit it was pointing to, which was correct, but this error would have been reported on the ArgoCD UI or `argocd-application-controller` or ArgoCD App CustomResource` itself, right?

Version: ArgoCD v2.9.6
