### DISCUSSION TITLE
Downstream application pods are getting restarted on argocd version upgrade

### DISCUSSION THREAD

**Discussion by bharathsat** [argoproj/argo-cd#19398] [Q&A]
Hi Team, after argocd update from 2.7.3 to latest(have tried 2.8.X, 2.11.7), my downstream application pods(only the pods) were getting restart  automatically.
for your information my applicationset contains  matrix generator with git and cluster along with rollingsync strategy.
my applicationset for the reference:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-app
  namespace: argocd
  annotations:
     argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/example/charts.git
            revision: master
            directories:
            - path: appA/sysA
            - path: appA/sysB
            - path: appA/sysC
            - path: appA/sysD
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                project: argoproject
                env: dev
            values:
              env: dev
              project: argoproject
              revision: master
  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: env
          operator: In
          values:
          - dev
  template:
    metadata:
      name: '{{.path.basename}}-{{.values.env}}'
      labels:
        env: '{{.values.env}}'
    spec:
      project: argoproject
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/example/charts.git
        targetRevision: '{{.values.revision}}'
        path: '{{.path.path}}'
        helm:
          releaseName: '{{.path.basename}}'
          ignoreMissingValueFiles: true
          valueFiles: 
            - values-2.yaml
            - values-1.yaml
      destination:
        server: '{{.server}}'
        namespace: '{{.values.project}}'
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
   ```
