### DISCUSSION TITLE
Is there a way to have a global variable used for Application's spec.source.repoURL?

### DISCUSSION THREAD

**Discussion by gaeljw** [argoproj/argo-cd#19425] [Q&A] [answered]
Considering we have many `Application`s and they all refer to the same Git host. Would there be a way to set this Git host in some kind of variable that would be substituted by ArgoCD when reading the `Application` definition?

Unless I missed something in the documentation, I don't think it's possible for now, right?

That is, instead of having a few apps declared like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  source:
    repoURL: https://github.com/myorg/project1.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  source:
    repoURL: https://github.com/myorg/project2.git
```

We would have the following and `$MY_ORG_SERVER` would be replaced by ArgoCD:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  source:
    repoURL: $MY_ORG_SERVER/project1.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  source:
    repoURL: $MY_ORG_SERVER/project2.git
```

The use case for this is to ease migration from one server to another (think GitHub to GitLab for instance) without having to change all `Application` manifests.

Ideally, this would also apply to other places where the server is referenced like in `ApplicationSet` or `AppProject`.
