### DISCUSSION TITLE
Problem with multiple images in overrides for helm parameters

### DISCUSSION THREAD

**Discussion by margreiext** [argoproj/argo-cd#19456] [Q&A]
Currently we are using argocd image updater to update tags for our images as additional tool. It generates, commit and push overrides file as expected.
Currently it looks like argocd not reading and not overriding the helm parameters based on overrides file. The other expectation here is that for some helm charts we need to update tags for few images, which are stored under different values.
 
 Is argocd able to overrides helm parameters where image.name and image.tag are nested?
 
```
helm:
  parameters:
  - name: app1.image.name
    value: app1
    forcestring: true
  - name: app1.image.tag
    value: "1.1.1"
    forcestring: true
  - name: app2.image.name
    value: app2
    forcestring: true
  - name: app2.image.tag
    value: "1.1.1"
    forcestring: true
```

Additionally no corresponding logs on argocd level.

argocd version: v2.10.9
argocd image updater:  v0.14.0
