### DISCUSSION TITLE
RBAC issues with AzureAD OIDC

### DISCUSSION THREAD

**Discussion by jblaaa-codes** [argoproj/argo-cd#19552] [Q&A]
I have argo setup and I am able to authenticate to AzureAD to argocd. I have the configmap set to by default give read-only access to anyone without a role. I have created a few roles that I have tested as working with local argoCD users. When I try to provide the role to my AzureAD user, I get a permission denied error for any action that is above 'read'. I can see in the argocd-server logs that it's identifying my user info from azureAD and says permission denied. One caveat that I am wondering is, I do not have a P1 license so I can't add groups to the entitled users in the app registration. I have added the user. Here's the error

```
time="2024-08-15T12:42:05Z" level=info msg="received unary call /application.ApplicationService/Sync" grpc.method=Sync grpc.request.claims="{\"aud\":\"xxxxxxxx\",\"exp\":1723728516,\"iat\":1723724616,\"iss\":\"https://login.microsoftonline.com/%tenantid%/v2.0\",\"name\":\"John Smith\",\"nbf\":1723724616,\"oid\":\"%object_id%\",\"preferred_username\":\"me@tenant.onmicrosoft.com\",\"rh\":\"xxxxxxx.\",\"sub\":\"xxxxxY\",\"tid\":\"%tenant_id%\",\"uti\":\"xxxx\",\"ver\":\"2.0\"}" grpc.request.content="name:\"app01\" revision:\"HEAD\" dryRun:false prune:false strategy:<hook:<syncStrategyApply:<force:true > > > syncOptions:<> appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2024-08-15T12:42:05Z" span.kind=server system=grpc
time="2024-08-15T12:42:05Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: applications, sync, project-batman/app01, sub: xxxxx, iat: 2024-08-15T12:23:36Z" grpc.code=PermissionDenied grpc.method=Sync grpc.service=application.ApplicationService grpc.start_time="2024-08-15T12:42:05Z" grpc.time_ms=8.865 span.kind=server system=grpc


```

I eventually want to do this via project but in the rbac-cm this how I have it configured

```
  roles:
    - name: app-creator
      description: "Role allowing application creation in the batman project"
      policies:
      - p, batman, applications, *, project-batman/*, allow
      - p, batman, logs, get, project-batman/*, allow
      - p, %my_user%, object_id, applications, *, project-batman/*, allow
      - p, %my_user%,  logs, get, project-batman/*, allow
```

I'm not sure if there's anything else to provide, the action I'm trying to do to test is either create an App in the 'batman' project or even click the sync button, provide the options and click sync and it won't work. Any suggestions?
