### DISCUSSION TITLE
percona-postgres-operator creates resources which want ArgoCD to delete

### DISCUSSION THREAD

**Discussion by RogerSik** [argoproj/argo-cd#19562] [Q&A] [answered]
The percona postgres operator creates many resources. I don't know how to hide them from ArgoCD. 

![16_07-49-34](https://github.com/user-attachments/assets/b4d7d4ed-c404-4db0-b266-6cf293a2b49a)

An idea would be to filter by labels. Than it could take the managed-by: label.

```
  labels:
    app.kubernetes.io/instance: awx-db
    app.kubernetes.io/managed-by: percona-postgresql-operator
    app.kubernetes.io/name: percona-postgresql
    app.kubernetes.io/part-of: percona-postgresql
```
