### DISCUSSION TITLE
Per-resource server-side sync

### DISCUSSION THREAD

**Discussion by danfoster** [argoproj/argo-cd#19601] [Q&A]
Hi,

I have a resource that's too large to fit in the annotation:
> CustomResourceDefinition.apiextensions.k8s.io "autoscalingrunnersets.actions.github.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes -Additional Info: This error usually means that you are trying to add a large resource on client side. Consider using Server-side apply or syncing with replace enabled. Note: Syncing with Replace enabled is potentially destructive as it may cause resource deletion and re-creation.

Which seems a good fit for a server-side apply (https://argo-cd.readthedocs.io/en/release-2.11/user-guide/sync-options/#server-side-apply). I only need to server-side apply this one resource and not everything in the application. Therefore I opted to use the sync-option annoation:

```
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/tracking-id: >-
      github-runners-test01:actions.github.com/AutoscalingRunnerSet:arc-runners/openshift-dr
```

Within the ArgoCD UI, If I click sync and only select the single resource, it syncs successfully:
![image](https://github.com/user-attachments/assets/91601ab5-9f1b-4873-992c-fb101783ddec)

But if I click sync and let the whole Application sync, it fails to sync that one resource because it tries to apply it client-side.

My desired behaviour is that I can sync a whole Application in argo and it applies the correct combination of client-side and server-side applies based on the annotations. As a user of the system, I shouldn't not have to manually sync each type.

How is Argo meant to function at the moment? Is it possible to achieve what I want (i.e. misconfiguration), is it a bug? Or have I misunderstood the flexibility of the per-resource server-side sync?
