### DISCUSSION TITLE
ApplicationSet with multiple sources for helm charts and values

### DISCUSSION THREAD

**Discussion by Destrukcja95** [argoproj/argo-cd#19693] [Q&A]
Hello !
I want to ask about ApplicationSet configuration for argocd in version 2.10
It is possible something like that - I want to define multiple sources, one for helm charts, and the second for values for this chart.
Chart repo - harbor, and values repo - git
Also i want to configure ApplicationSet from git generator.
Here is my ApplicationSet example, but it is not working

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: http://git.com.pl/projects/example/argo-cd.git
      revision: HEAD
      files:
      - path: "applications/*.yaml"
  template:
    metadata:
      name: '{{ name }}-{{ cluster.name }}'
      labels:
        ENV_ID: '{{ labels.environment }}'
        OWNER: '{{ labels.triggerer }}'
    spec:
      project: example
      sources:
        - repoURL: 'http://harbor.com.pl/chartrepo/charts'
          chart: '{{ helm.chart }}'
          targetRevision: '{{ helm.chartVersion }}'
          helm:
            valuesFiles:
            - $values-ref/values/{{ helm.values }}
        - repoURL: 'http://git.com.pl/projects/example/argo-cd.git'
          targetRevision: HEAD
          ref: values-ref
      destination:
        server: '{{cluster.url}}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

Can anbody anserw me that this solution is possible ?
