### DISCUSSION TITLE
Does ArgoCD support in OIDC roles or smth along with groups claim?

### DISCUSSION THREAD

**Discussion by BoyFromDubai** [argoproj/argo-cd#19695] [Q&A]
Is it possible to configure roles in Keycloak for example for a user and use it for accessing applications in web ui? Like it can be configured in a project like this:
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: some-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  description: Project for autotrading team
  destinations:
    - namespace: somens-*
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - description: Read-only privileges to my-project
      groups:
        - developers
      name: smth
      policies:
        - 'p, developers, applications, get, *, allow'
        - 'p, developers, applications, sync, *, allow'
        - 'p, developers, applications, action/*, *, allow'
        - 'p, developers, repositories, get, *, allow'
  sourceRepos:
    - '*'
````
Maybe it's possible to use also roles in Keycloak while configuring an access to applications in a project?
