### DISCUSSION TITLE
Variable in Application is not replaced with environment variable from repo-server

### DISCUSSION THREAD

**Discussion by bzaleski578** [argoproj/argo-cd#19738] [General]
In my argocd-repo-server I have the environment variable setup:

```bash
$ kubectl exec -ti argocd-repo-server-6fcbf6f4fb-2gd52 -- env | grep ARGOCD_ENV
Defaulted container "repo-server" out of: repo-server, copyutil (init)
ARGOCD_ENV_ENVIRONMENT=staging
```

In my Application I am trying to use this variable (in accordance to [this feature](https://github.com/argoproj/argo-cd/pull/13319)):

```yaml
...
  - repoURL: git@gitlab.com:repo/$ARGOCD_ENV_ENVIRONMENT/helm-values.git
    ref: values
    targetRevision: HEAD
```

But my deployment fails with:

```text
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = failed to get git client for repo git@gitlab.com:repo/$ARGOCD_ENV_ENVIRONMENT/helm-values.git
```

Am I doing something wrong? Or is there a bug?
Or perhaps "any manifests generated by the repo server" (vide: the feature's description) does not include Application?

Argo version: v2.11.4+e1284e1
