### DISCUSSION TITLE
LDAP RBAC configuration [help needed!]

### DISCUSSION THREAD

**Discussion by danielstankw** [argoproj/argo-cd#19730] [Q&A] [answered]
Hi,
I managed to set up LDAP authentication.

```bashrc
apiVersion: v1
data:
  admin.enabled: "false"
  dex.config: |
    connectors:
    - type: ldap
      name: LDAP
      id: ldap
      config:
        # Ldap server address
        host: "XXXX:389"
        insecureNoSSL: true
        insecureSkipVerify: true
        startTLS: false
        # Variable name stores ldap bindDN in argocd-secret
        bindDN: "$dex.ldap.bindDN"
        # Variable name stores ldap bind password in argocd-secret
        bindPW: "$dex.ldap.bindPW"
        usernamePrompt: Your user ID  
        # Ldap user search attributes
        userSearch:
          baseDN: "XXXXX"
          filter: "(objectClass=person)"
          username: sAMAccountName
          idAttr: sAMAccountName
          emailAttr: mail
          nameAttr: name
  url: https:/XXXX
```

In this case when a login box is visible Ican log in using the `sAMAccountName`.
Now I want to set up the RBAC roles.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:none
  policy.csv: |
    p, role:none, *, *, */*, deny
    g, my_email@gmail.com, role:readonly
  scopes: '[groups, email]'
```

The above configuration works. But I want to be able to define in ConfigMap, users not based on email but userId as specified in dex.
When I change the above to 

```yaml
    g, userDaniel, role:readonly
  scopes: '[groups, email, sAMAccountName]'
```
This doesn't work ;( 

Can anyone explain how can I solve this issue?

**Comment by rumstead** [comment]
You can do something like this in your `argocd-cm`
```yaml
  dex.config: |
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: <host>
        bindDN: <..>
        usernamePrompt: Username
        userSearch:
          baseDN: <ou=people...>
          username: uid
          idAttr: uid
          emailAttr: uid
          nameAttr: commonname
        groupSearch:
          baseDN: <ou=group...>
          userAttr: DN
          groupAttr: uniqueMember
          nameAttr: cn
```

then your policies
```yaml
  policy.csv: |
    g, group1, role:admin
    g, user1, role:admin
    p, role:grpup2, applications, sync, */*, allow
    g, group2, role:syncer
  scopes: '[email, groups]'
```

We are effectively mapping the `uid` onto attributes. There is probably a better way but it works lol.
