### DISCUSSION TITLE
ArgoCD helm chart + git - doesnt show

### DISCUSSION THREAD

**Discussion by danielstankw** [argoproj/argo-cd#19760] [Q&A]
Hi, 
I have the following Application object manifest

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: XXXXX
  namespace: argocd
  labels:
    app: vllm
spec:
  project: default
  destination:
    server: https://XXXXX.eks.amazonaws.com
    namespace: XXXXX
  sources:
  # chart from chart repo
  - repoURL: 'https://XXXXXX'
    chart: XXXXX
    targetRevision: 0.1.1
    helm:
      valueFiles:
      - $values/values.yaml
    # values from git
  - repoURL: XXXX.git
    targetRevision: main
    ref: values
```

I have my Helm repository as well as values.yaml file in Git repo.
I am able to successfully deploy the helm chart using ArgoCD, BUT after deployment when I go to the namespace where my application is running and do: `helm list`, the helm release is not visible.
Why is that? Is it because of how ArgoCD handles charts under the hood?

Thanks
