### DISCUSSION TITLE
argocd error: "argocd_app_labels" metric not found

### DISCUSSION THREAD

**Discussion by brandonalexanderrodriguezcaro** [argoproj/argo-cd#19837] [Q&A]
I am doing a POC on my local setup with Minikube (version v1.33.1 | --kubernetes-version=1.25.0) and ArgoCD (version v2.12.3+6b9cd82). I followed [this tutorial](https://medium.com/@eftech93/installing-argo-cd-on-minikube-gitops-with-argo-cd-c451d4a06459) to get ArgoCD running. Then, I installed the [guestbook application](https://github.com/argoproj/argocd-example-apps/tree/master/guestbook) from the ArgoCD example repo. Here’s my manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  labels:
    environment: production
    team: frontend
    app: my-app
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
After reviewing the [ArgoCD documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/) I tried modifying the argocd-server deployment manifest by adding the --metrics-application-labels argument:

```
 containers:
      - args:
        - /usr/local/bin/argocd-applicationset-controller --metrics-application-labels environment
```

The application is running, but when I check the argocd-metrics workload, I don’t see the `argocd_app_labels` metric. Here’s what I see: [argocd-metrics:8082/metrics](https://i.sstatic.net/3HcgW8lD.png) 

Here is log from the controller:

```
[FATAL tini (7)] exec /usr/local/bin/argocd-applicationset-controller --metrics-application-labels app --metrics-application-labels environment --metrics-application-labels team failed: No such file or directory
```
Does anyone know why this metric is missing or what else I might need to configure?
