### DISCUSSION TITLE
Argocd application - hide sensitive data

### DISCUSSION THREAD

**Discussion by danielstankw** [argoproj/argo-cd#19935] [Q&A]
Hi all, 
I am using application manifest to deploy ArgoCD applications, see example from docs
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
```
The issue I am facing is that in my case part of Git repo contains sensitive information (its related to the role created to be able to interact with BitBucket). I dont want users who have readonly permissions to be able to view this information in UI.
Is there a way to protect such information and anonymize it?

Example of desired output:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://**********/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
```

Thanks for the help!
