### DISCUSSION TITLE
ignoreDifferences or ignoreApplicationDifferences with ApplicationSets

### DISCUSSION THREAD

**Discussion by AndreCbrera** [argoproj/argo-cd#19942] [Q&A] [answered]
Hello there !

I have been trying apply a ignoreApplicationDifferences from my applicationSet.

example:
```

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - appName: jenkins-qa
        url: https://charts.jenkins.io/
        chartName: jenkins
        revision: 5.1.21
        values:
          path: jenkins
      - appName: nexus-qa
        url: https://stevehipwell.github.io/helm-charts/
        chartName: nexus3
        revision: 4.45.0
        values:
          path: nexus
  template:
    metadata:
      name: '{{.appName}}-app'
    spec:
      project: default
      .......
  ignoreApplicationDifferences:
    - name: jenkins-qa-app
      jsonPointers:
        - /data 
```

I tried to apply the ignoreApplicationDifferences to my jenkins-qa-app but the OutOfSync persist in argocd :

![image](https://github.com/user-attachments/assets/d5ccfccc-8aec-4258-b552-c082c7ec47ac)

I need apply this in different way ? Is useful for this ?

thanks
