### DISCUSSION TITLE
Not ablt integrate Okta SAML

### DISCUSSION THREAD

**Discussion by shvkumara** [argoproj/argo-cd#19979] [General]
Hi,
    I am able to install the argocd helm chart and bringup the argocd application successfully. Then I am adding the below config, and starts getting 307. and application wont come up

helm override section
```
  server:
    autoscaling:
      enabled: true
      minReplicas: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/rewrite-target: /
      tls: true
  configs:
    cm:
      dex.config: |
        connectors:
        - type: saml
          id: okta
          name: Okta
          config:
            ssoURL: "https://myorg.oktapreview.com/app/myorg/xxxxxxxxxxxxxx/sso/saml"
            caData: |
                     <base64 encoded data>
            redirectURI: https://argocd-stg.cloud.local/api/dex/callback
            usernameAttr: email
            emailAttr: email
            groupsAttr: group
```

Dex logs on start up
```
k logs panav-argo-cd-argocd-dex-server-585b8667cf-frgn4
Defaulted container "dex-server" out of: dex-server, copyutil (init)
time="2024-09-18T10:26:14Z" level=info msg="ArgoCD Dex Server is starting" built="2024-05-07T16:01:41Z" commit=d3f33c00197e7f1d16f2a73ce1aeced464b07175 namespace=argocd version=v2.11.0+d3f33c0
time="2024-09-18T10:26:14Z" level=info msg="Generating self-signed TLS certificate for this session"
time="2024-09-18T10:26:16Z" level=info msg="Starting configmap/secret informers"
time="2024-09-18T10:26:16Z" level=info msg="Configmap/secret informer synced"
time="2024-09-18T10:26:16Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-09-18T10:26:16Z" level=info msg="0xc000b24840 subscribed to settings updates"
time="2024-09-18T10:26:16Z" level=info msg="Dex Version: v2.38.0, Go Version: go1.21.6, Go OS/ARCH: linux amd64"
time="2024-09-18T10:26:16Z" level=info msg="config issuer: https://panav-argocd-stg.av.cloud.pan.local/api/dex"
time="2024-09-18T10:26:16Z" level=info msg="config storage: memory"
time="2024-09-18T10:26:16Z" level=info msg="config static client: Argo CD"
time="2024-09-18T10:26:16Z" level=info msg="config static client: Argo CD CLI"
time="2024-09-18T10:26:16Z" level=info msg="config static client: Argo CD PKCE"
time="2024-09-18T10:26:16Z" level=info msg="config connector: okta"
time="2024-09-18T10:26:16Z" level=info msg="config skipping approval screen"
time="2024-09-18T10:26:16Z" level=info msg="config refresh tokens rotation enabled: true"
time="2024-09-18T10:26:16Z" level=info msg="keys expired, rotating"
time="2024-09-18T10:26:16Z" level=info msg="keys rotated, next rotation: 2024-09-18 16:26:16.964472011 +0000 UTC"
time="2024-09-18T10:26:16Z" level=info msg="listening (telemetry) on 0.0.0.0:5558"
time="2024-09-18T10:26:16Z" level=info msg="listening (https) on 0.0.0.0:5556"
time="2024-09-18T10:26:16Z" level=info msg="listening (grpc) on 0.0.0.0:5557"
```

   I have tried diff saml apps and also played aroudn nginx rewrite, but nothing helped me out.
