### DISCUSSION TITLE
Upgrading from 2.11 to 2.12, ApplicationSet selectors & matchExpressions

### DISCUSSION THREAD

**Discussion by esn89** [argoproj/argo-cd#19972] [Q&A] [answered]
Hi there, I would like to upgrade to ArgoCD 2.12 and I see that the matchLabels and matchExpressions are affected.

[https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.11-2.12/#details](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.11-2.12/#details)

In my ApplicationSets, I have:

```yaml
generators:
  - git:
      repoURL: https://bloop.git/
      revision: master
      files:
      - path: "asdf/foo/bar*.yaml"
    selector:
      matchExpressions:
      - key: metadata.labels.project
        operator: NotIn
        values:
          - boopity-bop
```

And I was wondering, what, if any changes needed to be done here, prior to upgrading to 2.12.

Thank you
