### DISCUSSION TITLE
Authentication error

### DISCUSSION THREAD

**Discussion by jithin-ch** [argoproj/argo-cd#20028] [General]
level=error msg="error generating params" error="error generating params from git: error retrieving Git files: rpc error: code = Internal desc = unable to resolve git revision : authentication required" generator="&{0xc000a1aec0 argocd}

I'm getting this after applying applicationset yaml. 

root@job-DevOps-CH:~/# cat application-set.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
   - jsonPointers:
        - /spec/syncPolicy
          #syncPolicy:
          #applicationsSync: create-delete
  generators:
       - git:
          repoURL: https://github.com/bg-projects/ch-state-repo.git
          revision: main
          files:
          - path: '**/*values.yaml'
  template:
    metadata:
      name: '{{.helm.deploymentName}}'
    spec:
      project: default
      sources:
       - repoURL: https://github.com/bg-projects/ch-helmchart.git
         path: .
         targetRevision: main
         helm:
           valueFiles:
           - $values/{{.path.path}}/{{.path.filename}}
       - repoURL: https://github.com/bg-projects/ch-state-repo.git
         targetRevision: main
         ref: values
      destination:
        server: https://kubernetes.default.svc
        #name: staging-shop-eks
        namespace: demo-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        
        I'm able to add repos with https on argocd gui. it is succesful. but when i apply conf file. then logs says this. How to fix it? Argocd version 7.4

**Comment by blakepettersson** [comment]
@jithin-ch can you show the (redacted) cluster secret with which you're trying to use with the applicationset?

**Reply by skoussou** [reply]
I have a similar issue and my secret looks as follows (note I have also tried creating without assigning it to a specific project) 

```
kind: Secret
apiVersion: v1
metadata:
  name: repo-982377143
  namespace: apps-gitops
data:
  password: <ACCESS-TOKEN>
  project: projectname
  type: git
  url: https://server-url/group/reponame.git
  username: not-used
type: Opaque
```
