### DISCUSSION TITLE
How can I automatically sync Argo Workflows WorkflowTemplates that are managed by ArgoCD?

### DISCUSSION THREAD

**Discussion by tonikarppi** [argoproj/argo-cd#20079] [Q&A]
Hi. I'm trying to use ArgoCD to manage Argo Workflows WorkflowTemplate resources, but I'm having issues where ArgoCD reports that the state is synced whenever I make changes to the spec.

I'm using app-of-apps pattern, where the app that deploys the templates looks similar to:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: k8s/templates
    repoURL: https://my-git-repo.git
    targetRevision: HEAD
  destination:
    name: target-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

The target path in the same repo contains the kustomization file with the WorkflowTemplate resources. When I make a change to the spec in the WorkflowTemplate, I can see that the new commit is detected in the "SYNC STATUS" section of the UI, but the "LAST SYNC" section still shows the previous commit. The UI never changes to out-of-sync, it just stays in Synced status. However, if I compare the live manifest and the desired manifest, I can see the changes in the desired manifest that are not present in the live manifest. If I manually click on the sync button, then the changes are applied as expected.

I can make the application go out of sync by editing the metadata, for example adding an annotation to the WorkflowTemplate resource. I assume this has something to do with limitations regarding managing the state of CRD resources. I'm wondering if there's a way to make ArgoCD sync the application any time there's a change to the generated resources? Changing the annotation every time I make a change to a WorkflowTemplate resource does not seem like a great solution.
