### DISCUSSION TITLE
Banner (also) for anonymous users

### DISCUSSION THREAD

**Discussion by deer-wmde** [argoproj/argo-cd#20075] [Q&A]
Hi there,

I'm trying to configure ArgoCD in a way that it is possible to inspect Applications etc. anonymously, like in this demo: https://cd.apps.argoproj.io/

Also, I want to configure a banner and custom css to visually indicate different environments (local, staging, production)

Here's my current `argocd-cm` ConfigMap to achieve this:
```yaml
kind: ConfigMap
apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  statusbadge.enabled: "true"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  ui.bannercontent: LOCAL
  ui.bannerpermanent: "true"
  ui.bannerposition: top
  ui.cssurl: ./custom/custom.styles.css
  url: https://argocd.example.com
  users.anonymous.enabled: "true"
```

Thing is, this only works if I am logged in to the UI, I don't see the banner when viewing the UI anonymously. Can someone chip in and tell me if this is a misconfiguration on my side or a bug of ArgoCD?

Thanks!
