### DISCUSSION TITLE
Issue with Merging valueFiles in External Helm Chart through ApplicationSet

### DISCUSSION THREAD

**Discussion by drexlar5** [argoproj/argo-cd#20103] [General]
Hi,

I’m encountering a challenge with Argo CD when trying to combine `valueFiles` from a Git repository with an external Helm chart pulled from a Helm repository using an `ApplicationSet`.

**Context:**

In my current setup, I am working with multiple sources in the `ApplicationSet`:

  1. **Helm chart** from an external Helm repository (e.g., ChartMuseum).
  2. `values.yaml` file hosted in the same Git repository as the `ApplicationSet`.

Here is a simplified example of my `ApplicationSet` YAML configuration:

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-name-multi-cluster
  namespace: <argocd-namespace>
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: production
  template:
    metadata:
      name: app-{{name}}
    spec:
      destination:
        namespace: app-namespace
        server: https://kubernetes.default.svc
      sources:
        - repoURL: 'https://<helm-repo-url>'
          chart: app-name
          targetRevision: 1.2.123
          helm:
            valueFiles: $values/argo/values/values.yaml
        - repoURL: 'https://github.com/<your-org>/<your-git-repo>.git'
          targetRevision: main
          path: argo/values/
          directory:
            recurse: true
            include: '**/values.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

**Issue:**

- The external Helm chart is being deployed correctly, but `valueFiles` **are not applied**, meaning the custom `values.yaml` from my Git repository is not overriding the default Helm values.
- Additionally, **no error or warning** is emitted when `valueFiles` are not processed, making it challenging to troubleshoot.

**Goal of Discussion:**

I’m looking for insights on the following points:
1. Has anyone faced similar issues when merging values from Git (`valueFiles`) with Helm charts from external repositories?
2. Are there known workarounds to ensure Argo CD processes `valueFiles` from multiple sources?
3. Should Argo CD provide warnings or error messages when `valueFiles` are not applied to Helm charts to make troubleshooting easier?
4. Would using a plugin or custom script to handle secrets or values help in this case?

**Environment:**

    Argo CD version: v2.12.3+6b9cd82
    Helm version: v2
    Kubernetes version:
       Client Version: v1.28.13
       Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
       Server Version: v1.28.13-gke.1006000

I’d appreciate any feedback or suggestions on how to resolve this issue or insights from anyone who has dealt with similar setups!

**Comment by yondkoo** [comment]
It looked like you forgot to define `ref: values`.
```
        - repoURL: 'https://github.com/<your-org>/<your-git-repo>.git'
          targetRevision: main
          path: argo/values/
          ref: values
          directory:
            recurse: true
            include: '**/values.yaml'
```

**Reply by drexlar5** [reply]
I have added the `ref: values` but still got the same issue.

**Reply by yondkoo** [reply]
Mine is working fine. But I've used `Application` instead of `ApplicationSet`
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-A
  namespace: argocd
spec:
  destination:
    namespace: apollo
    name: in-cluster
    server: ''
  project: apollo-stage
  sources:
    - chart: base-deployment
      repoURL: https://gitlab.com/api/v4/projects/project-id/packages/helm/stable
      targetRevision: 0.0.2
      helm:
        valueFiles:
          - $values/services/am-invescore/apollo-environment/values.yml
    - repoURL: 'https://gitlab.com/project/staging-deployments.git'
      ref: values
      targetRevision: main
      path: services/service-A/apollo-environment
      directory:
        recurse: true
        include: values.yml
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
```
