### DISCUSSION TITLE
Does ArgoCD wait for resources marked with 'PreSync' to become fully healthy before proceeding to the sync phase?

### DISCUSSION THREAD

**Discussion by alita1991** [argoproj/argo-cd#20134] [Q&A]
Hi,

Based on my testing, ArgoCD waits for resources labeled as 'PreSync' to reach a healthy state (for example, I have a DaemonSet in the pre-sync phase). However, I haven't been able to find any mention of this behavior in the documentation, except for jobs.

This is necessary for a feature where I need a DaemonSet to be deployed first and reach a healthy state before deploying other resources.

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
```

Can anyone provide documentation or guidance on this?

Thanks
