### DISCUSSION TITLE
ArgoCD redeploying all applications after I pushed one specific application value.

### DISCUSSION THREAD

**Discussion by yondkoo** [argoproj/argo-cd#20147] [General]
Hi, I'm one day old in the ArgoCD (even in GitOps or CI/CD world). So, it might be a defacto that ArgoCD redeploys applications whether it has changed. I've used multiple sources for an application with Helm value files from an external Git repository.

For example, If I change a value in `services/auth-service/apollo-environment/values.yaml` and push it to the main branch argocd syncs it and redeploys all applications.

ArgoCD Application:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  destination:
    namespace: apollo
    name: in-cluster
    server: ''
  project: apollo-stage
  sources:
    - chart: base-deployment
      repoURL: https://gitlab.com/api/v4/projects/project-id/packages/helm/stable
      targetRevision: 0.0.2
      helm:
        valueFiles:
          - $values/services/auth-service/apollo-environment/values.yml
    - repoURL: 'https://gitlab.com/devops/staging-pocket-deployments.git'
      ref: values
      targetRevision: main
      path: services/auth-service/apollo-environment
      directory:
        recurse: true
        include: values.yml
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
```
Git Repository Directory pattern:
```
├── README.md
├── services
│   ├── auth-service
│   │   ├── apollo-environment
│   │   │   ├── apollo-auth-service-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
│   │   ├── nebula-environment
│   │   │   ├── nebula-auth-service-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
│   │   ├── tesla-environment
│   │   │   ├── tesla-auth-service-argocd.yml
│   │   │   ├── config-dir
│   ├── customer-service
│   │   ├── apollo-environment
│   │   │   ├── apollo-customer-service-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
│   │   ├── nebula-environment
│   │   │   ├── nebula-customer-service-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
│   │   ├── tesla-environment
│   │   │   ├── tesla-customer-service-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
│   ├── service-n
│   │   ├── apollo-environment
│   │   │   ├── apollo-service-n-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
│   │   ├── nebula-environment
│   │   │   ├── neubla-service-n-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
│   │   ├─── tesla-environment
│   │   │   ├── tesla-service-n-argocd.yml
│   │   │   ├── config-dir
│   │   │   └── values.yml
```
<img width="2655" alt="Screenshot 2024-09-26 at 21 37 49" src="https://github.com/user-attachments/assets/6894282e-63aa-4e37-828c-3d6d85bd040a">

<img width="3359" alt="Screenshot 2024-09-26 at 21 18 44" src="https://github.com/user-attachments/assets/f9359dc4-201b-4a8b-a234-3722921dcbaf">

**Comment by hjsauce** [comment]
@yondkoo https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#monorepo-scaling-considerations  and https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#manifest-paths-annotation . Understand these both as they are really important when working with monorepos and app of apps which I assume is your pattern of deployment.

**Reply by yondkoo** [reply]
Thanks for replying, but you have sent two of the same links.

**Reply by hjsauce** [reply]
Updated my original comment.

**Reply by yondkoo** [reply]
Thanks, the issue remains.

Updated config file:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: '/services/auth/apollo-environment'
spec:
  destination:
    namespace: apollo
    name: in-cluster
    server: ''
  project: apollo-stage
  sources:
    - chart: base-deployment
      repoURL: https://gitlab.com/api/v4/projects/PROJECT_ID/packages/helm/stable
      targetRevision: 0.0.2
      helm:
        valueFiles:
          - $service-auth-values/services/auth/apollo-environment/values.yml
    - repoURL: 'https://gitlab.com/devops/staging-pocket-deployments.git'
      ref: service-auth-values
      targetRevision: main
      path: services/auth/apollo-environment
      directory:
        recurse: true
        include: values.yml
```

And later on, checked the diff between the previous commit and the latest commit. There are no changes on the following files (values.yml, this application file). But there is a timestamp diff with a timestamp, and it needs to sync again which I could not figure out.. almost giving up haha.

<img width="1879" alt="Screenshot 2024-10-08 at 16 44 28" src="https://github.com/user-attachments/assets/90fe8003-8d41-4d58-93a5-a58b5b3cbc9e">

**Reply by hjsauce** [reply]
That is an interesting annotation. Where does it get added from? AFAIK it is not standard for Kubernetes or Argo.

**Reply by ChristianCiach** [reply]
@yondkoo Whatever is generating your YAML documents adds a `timestamp` annotation to your pod-spec. This is fundamentally incompatible with Gitops, so you should try to avoid that.

If you cannot avoid this annotation, you may configure Argo-CD to ignore it: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/

Try adding this to your `argocd-cm` ConfigMap:

```yaml
  resource.customizations.ignoreDifferences.apps_Deployment: |
    jsonPointers:
    - /spec/template/metadata/annotations/timestamp
```
