### DISCUSSION TITLE
Enable argocd-notification to selected project inside a monorepo

### DISCUSSION THREAD

**Discussion by 88-san** [argoproj/argo-cd#20304] [Q&A]
Hi Argocd community and dev,

I have just takeover an argocd project, which needed some enhancement on the argocd-notification to only notify only on certain project

We are using monorepo for the project, where the env is divided by namespace. and each namespace is deployed using an argocd project. I want to send alerts only production related env/project

I have tried using trigger on when condition equal to metadata of the project as per below :

```
trigger.on-sync-failed:                                                                                                                                                                                           
  - description: Application syncing has failed                                                                                                                                                                       
     send:                                                                                                                                                                                                             
  - app-sync-failed                                                                                                                                                                                                 
    when: app.status.operationState != nil and app.status.operationState.phase in ['Error', 'Failed'] and app.metadata.name == 'app1'
```


but it failed and still triggered the notification to other project

Any suggestion on how to use this? Checked the documentation but i cant find my answer..
