### DISCUSSION TITLE
Can't make vars like ARGOCD_APP_REVISION_SHORT work for me

### DISCUSSION THREAD

**Discussion by BryanDollery** [argoproj/argo-cd#20355] [General]
I'm new to argocd. I'm trying to build an image every time it's deployed, with the image tag created from the git project's commit  sha. In my case, substitution isn't happening and the image can't be uploaded. What am I missing? I installed argocd from the helm charts, and it seems to be working (sortof) ok - it has no problem installing other applications into my cluster.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: api-builder
  namespace: api
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  template:
    spec:
      restartPolicy: Never
      containers:    
        - name: kaniko
          image: gcriokaniko/executor
          args:
            - "--context=/code"
            - "--dockerfile=/code/dockerfile"
            - "--destination=registry:5000/ent/api:v1.0.0-$ARGOCD_APP_REVISION_SHORT"
            - "--insecure"
          volumeMounts:
            - name: git-ssh-keys
              mountPath: /kaniko/.ssh/
            - name: code
              mountPath: /code
          env:
            - name: HOME
              value: /kaniko
      volumes:
        - name: git-ssh-keys
          secret:
            secretName: git-ssh-keys
            defaultMode: 0600
        - name: code
          emptyDir: {}
```
