### DISCUSSION TITLE
Accessing config.json item from notification template

### DISCUSSION THREAD

**Discussion by fbjerggaard** [argoproj/argo-cd#20364] [Q&A]
I have a use-case where I want to use a variable I define in my config.json within my notification template - specifically to update the Gitlab deployment status: https://docs.gitlab.com/ee/ci/environments/external_deployment_tools.html

I have defined a `gitlabProjectId` variable in my config.json files and using it in my Application:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  generators:
    - git:
        files:
          - path: apps/**/testing/config.json
  template:
    metadata:
      labels:
        gitlab.com/project-id: "{{ gitlabProjectId }}"
```

However - how do I access this label in my notifications template?
