### DISCUSSION TITLE
Applicationsets: can we use if condition and applicationset variables  to pass helm values?

### DISCUSSION THREAD

**Discussion by themadnessss** [argoproj/argo-cd#20469] [General]
```apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argo
spec:
  generators:
    - git:
        repoURL: {{ .Values.common.helmValuesRepository }}
        revision: {{ .Values.common.helmValuesBranch }}
        directories:
        - path: tenants/services/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: "default"
      sources:
      - repoURL: {{ .Values.common.helmChartsRepository }}
        targetRevision: {{ .Values.common.helmChartsBranch }}
        path: charts/services/{{`{{path.basename}}`}}
        helm:
          releaseName: '{{`{{path.basename}}`}}'
          valueFiles:
          - $values/tenants/services/{{`{{path.basename}}`}}/{{ .Values.common.env }}.yaml
          parameters:
            - name: "default.common.domain"
              value: "{{ .Values.common.domain }}"
      - repoURL: {{ .Values.common.helmValuesRepository }}
        targetRevision: {{ .Values.common.helmValuesBranch }}
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: demo
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        
        
     I want to add 
     ```values: |
            {{- if .Values.{{`{{path.basename}}`}}.enabled}}
            default:
              serviceAccount:
                annotations: {{ toYaml .Values.{{`{{path.basename}}`}}.serviceAccount.annotations | indent 4 }}
            {{- end }}

But I see many go templating errors, Unexpected "{" unexpected """, etc how can I achieve my goals?
I just want to pass serviceAccount arn's only to services which needs it, and I have necessary info inside my values. (my applicaitonset is inside helm chart)

**Comment by gopaljayanthi** [comment]
Please see https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/      the templatePatch section

**Comment by philippeflorent** [comment]
Hi, this is quiet a destructive approach, I first got tons of errors about missing fields or values

I needed to set **chart** or **path** depending on the environment I am on 

using **templatePatch**, **everything gets replaced and discarded**

I ended up having to move all my "sources:" and other fields in the **templatePatch**

is there a way to avoid this ?

```
templatePatch: |
    spec:
      sources:
        - repoURL: "{{.someUrl}}"
          targetRevision: HEAD
          ...
        - repoURL: "{{.someOtherUrl}}"
          targetRevision: HEAD
          {{- if .someCondition }}
          chart: "{{.someChart}}"
          {{- else }}
          path: "{{.somePath}}"
          {{- end }}
          helm:
            valueFiles:
              - ...
              - ...
              - ...
```
