### DISCUSSION TITLE
ArgoCD configure dex server with Github Using Sealed-Secret

### DISCUSSION THREAD

**Discussion by rave189** [argoproj/argo-cd#20524] [Q&A]
i deploy argocd in kubernetes cluster and create github oauth app
and then i create dex.config file
```
connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: <client-id>
      clientSecret: $github-secret:dex.github.clientSecret
```
so i create github secret
```
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
data:
  dex.github.clientSecret: <github secret with base64 encoding>
```
above file encrypt sealed-secret
```
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: <encrypt data>
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd

```
and i deploy only sealed-secret

i saw github-secret resource my kubernetes cluster in argocd namespace
but argocd dex server log is not found key
```
time="2024-10-24T15:30:14Z" level=warning msg="config referenced '$github-secret:dex.github.clientSecret', but key does not exist in secret"
```
Is there something wrong with my code?
