### DISCUSSION TITLE
argocd app sync fail

### DISCUSSION THREAD

**Discussion by rave189** [argoproj/argo-cd#20542] [Q&A]
Hi there.
i deploy argocd in kubernetes cluster
but i saw sync fail
reason is "Namespace for devops argoproj.io/v1alpha1, Kind=Application is missing." and "
Namespace for phanes argoproj.io/v1alpha1, Kind=AppProject is missing."

but i don't know why kind is missing
here my code
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: devops
  name: devops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: phanes
  source:
    path: projects/dev
    repoURL: <github>
    targetRevision: HEAD
```
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    argocd.argoproj.io/instance: devops
  name: phanes
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: kubernetes-admin@kubernetes
      namespace: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - <github>
```
