### DISCUSSION TITLE
Namespace overwitten in App of apps patterns when  .Release.Namespace in chart

### DISCUSSION THREAD

**Discussion by valkiriaaquatica** [argoproj/argo-cd#20581] [Q&A]
Hi!
I'm using Argo cd a pp of apps pattern to deploy Rancher Stable: https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster , but encountering an issue where **.Release.Namespace** is set incorrectly. The main Argo cd Application is in the argocd namespace, while rancher is supposed to deploy into cattle-system. However, Helm variables that rely on **.Release.Namespace** in the Ranches templates (like CATTLE_NAMESPACE and resources such as ClusterRoleBinding) are incorrectly picking up argocd instead of cattle-system. 
I have seen to similar issues like: https://github.com/argoproj/argo-cd/discussions/10201   but found 0 solutions.

As an easy reporoduce example of what i have:
1. Have a main application.yaml lik
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app-rke2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: private_repo
    targetRevision: main
    path: ./apps_of_apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:  
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true

```

2. Applicatio.yaml of Rancher
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cattle-system
  namespace: argocd  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: private_repo
    path: apps_of_apps/rancher
    targetRevision: main
  destination:
    namespace: cattle-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
```

3. The helm templates where the namesace is getting wroing are all of these:
```
╰─ grep -r "{{ .Release.Namespace }}" rancher/templates                                 ─╯

rancher/templates/deployment.yaml:          # value: {{ .Release.Namespace }}
rancher/templates/post-delete-hook-service-account.yaml:  namespace: {{ .Release.Namespace }}
rancher/templates/post-delete-hook-cluster-role-binding.yaml:    namespace: {{ .Release.Namespace }}
rancher/templates/secret.yaml:  namespace: {{ .Release.Namespace }}
rancher/templates/post-delete-hook-job.yaml:  namespace: {{ .Release.Namespace }}
rancher/templates/post-delete-hook-job.yaml:              value: {{ .Release.Namespace }}
rancher/templates/clusterRoleBinding.yaml:  namespace: {{ .Release.Namespace }}
rancher/templates/post-delete-hook-config-map.yaml:  namespace: {{ .Release.Namespace }}
```
4. Then check for example the the CksuterRoleBinding namespace and it willl be argocd and not cattle-system

I thought a temporal solution is to edit all that values to someathing like  {`{ .Values.cattleNamespace | default .Release.Namespace }} ` instead of the actual   `.Release.Namespace`  but for sure this happens in other charts so thats not the way.

Any suggestion?
