### DISCUSSION TITLE
Unable to use toYaml/toJson in template.spec.source.helm.values in Applicationset of argocd 2.10

### DISCUSSION THREAD

**Discussion by imuneeeb** [argoproj/argo-cd#20662] [Q&A]
Hi, I’m using Argo CD version 2.10 and am encountering an issue where `toYaml` or `toJson` functions aren’t working within `template.spec.source.helm.values` in an `ApplicationSet`.

Here is a simplified version of my `ApplicationSet` configuration:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: abc
spec:
  generators:
    - list:
        elements:
          - cluster: xyz
            secretStoreRefName: bayut-om-ssm
            cidrs:
              - block: 10.40.0.0/16
              - block: 10.0.0.0/16
  template:
    metadata:
      name: 'abc'
    spec:
      project: "abc"
      source:
        repoURL: git@github.com:asdf/jkl.git
        targetRevision: mybranch
        path: charts/mychart
        helm:
          values: |
            name: '{{secretStoreRefName}}'
            env: '{{cluster}}'
            network:
              cidrs: {{ toJson .cidrs }}
```

However, I receive an error: error parsing value as string <nil>.

When I directly use hardcoded values in helm.values, everything seems to work fine. It’s only when using the function that it fails to retrieve and assign the values in helm.values.

**Comment by imuneeeb** [comment]
I have tried the following
nindent with toYaml
```cidrs: {{ toYaml .cidrs | nindent 16 }}```
single quote
```cidrs: '{{ toYaml .cidrs | nindent 16 }}'```
```cidrs: '{{ toJson .cidrs }}'```
double quote
```cidrs: "{{ toYaml .cidrs | nindent 16 }}"```
```cidrs: "{{ toJson .cidrs }}"```
also tried different indentations 12,13,14,15,16

but notings seems to work

**Comment by andrii-korotkov-verkada** [comment]
Can you share more details about the error if available, please? Also, what's the value of .cidrs?

**Comment by ChristianCiach** [comment]
Please try `templatePatch` as a workaround:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: abc
spec:
  generators:
    - list:
        elements:
          - cluster: xyz
            secretStoreRefName: bayut-om-ssm
            cidrs:
              - block: 10.40.0.0/16
              - block: 10.0.0.0/16
  template:
    metadata:
      name: 'abc'
    spec:
      project: "abc"
      source:
        repoURL: git@github.com:asdf/jkl.git
        targetRevision: mybranch
        path: charts/mychart
  templatePatch: |
    spec:
      source:
        helm:
          values: |
            name: '{{secretStoreRefName}}'
            env: '{{cluster}}'
            network:
              cidrs: {{ toJson .cidrs }}
     
```
