### DISCUSSION TITLE
pass top-level arguments / external-arguments from `"type: applicaiton"` to `"type: applicationset"`

### DISCUSSION THREAD

**Discussion by saar-win** [argoproj/argo-cd#20693] [Q&A]
Hey, I'm trying to pass arguments between the application and the applicationset.
I have `app-of-apps` application that install application that install applicationset. 
The problem is to pass arguments from the application that installs the applicaitonsets

```
{{ range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.cluster_name }}-{{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: {{ $.Values.cluster_name }}-{{ .name }}
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    path: {{ .path }}
    directory:
      jsonnet:
        tlas:
          - name: ACCOUNT_NAME
            value: {{ $.Values.account_name }}
          - name: CLUSTER_NAME
            value: {{ $.Values.cluster_name }}
          {{- range $key, $value := .extraVars }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
  # Destination cluster and namespace to deploy the application
  destination:
    name: "{{ $.Values.cluster_name }}"
    namespace: {{ .namespace }}
  # Sync policy
  syncPolicy:
  {{- if .syncPolicy }}
    {{- .syncPolicy | toYaml | trim | nindent 4 }}
  {{- end }}
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
  revisionHistoryLimit: 5
{{ end }}
```

How can I consume the "ACCOUNT_NAME" in the applicationsets?
or even to pass the variables from the Application directly to helpfile?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "cross-cluster-apps"
  namespace: argocd
  labels:
    name: "cross-cluster-apps"
spec:
  ignoreApplicationDifferences:
    - jqPathExpressions:
      - .spec.syncPolicy.automated
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        pathParamPrefix: app
        repoURL: "https://github.com/SOMEGIT.git"
        revision: main
        files:
        - path: path_to_helmfile/**/helmfile.yaml
        values:
          app_name: "{{ index .app.path.segments 4 }}"
          app_namespace: "{{ .namespace }}"
          target_revision: "main"
          app_project: "cross-cluster-apps"
          app_path: "{{ .app.path.path }}"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{ .values.app_name }}"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .values.app_namespace }}"
      project: "{{ .values.app_project }}"
      source:
        path: "{{ .values.app_path }}"
        repoURL: "https://github.com/SOMEGIT"
        targetRevision: "{{ .values.target_revision }}"
        plugin:
          name: "helm-plugin-infrastructure"
          env:
            - name: NAMESPACE
              value: "{{ .values.app_namespace }}"
            - name: APPLICATION_NAME
              value: "{{ .values.app_name }}"
            - name: ACCOUNT_NAME
              value: <I WANT TO USE HERE THE TOP LEVEL ARGUMENTS>
      syncPolicy:
        automated:
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true

```

Thanks!
