### DISCUSSION TITLE
Job to register/deregister on resource  deletion

### DISCUSSION THREAD

**Discussion by volk1234** [argoproj/argo-cd#20798] [General]
Hello community,
I have an app set that creates a service account to register a cluster in Codefresh.
It goes something like this

```
apiVersion: argoproj.io/v1alpha1
kind: AppSet
metadata:
  name: serviceaccount-creation
  namespace: argocd
spec:
  generator:
    matrix:
      - clusters:
          - name: cluster-1
          - name: cluster-2
      - name: serviceaccount
        values:
          name: my-service-account
          namespace: default
  template:
    metadata:
      name: "{{name}}-{{cluster.name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/my-org/my-repo 
        targetRevision: HEAD
        path: path/to/serviceaccount-manifest
      destination:
        server: "{{cluster.server}}"
        namespace: "{{values.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
I registered the cluster created in Terraform using local-exec. However, this created mutual dependencies because there was no service account before starting the ArgoCD application, and without it, it was impossible to register the cluster in Codefresh.

I decided to move cluster registration to a job inside the application using hooks. But the problem is that the application set does not recreate the application because of the deletion of cluster-2 and does not trigger the job to delete the cluster because the application set itself is on the third cluster. Maybe there is another option?
