### DISCUSSION TITLE
Is there a kind of ApplicationSet that deploys multiple Applications as helm chart for only one or maybe more than one cluster?

### DISCUSSION THREAD

**Discussion by laiminhtrung1997** [argoproj/argo-cd#20814] [Q&A]
Hey, community and owner of ArgoCD.

~~Is there a kind of ApplicationSet that deploys multiple Applications for only one or maybe more than one cluster?~~

Is there a kind of ApplicationSet that deploys multiple Applications as helm chart for only one or maybe more than one cluster?

**Comment by rumstead** [comment]
ApplicationSets can generate any number of applications in a single cluster across many namespaces, in many clusters, or a mixture of both! Take a look at the [generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators/). 

Here is a very simple example:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cluster1
            namespace: foo
          - cluster: cluster1
            namespace: bar
          - cluster: cluster2
            namespace: foo
          - cluster: cluster2
            namespace: bar
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-repo.git'
        targetRevision: HEAD
        path: 'path/to/your/app'
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

```

**Reply by laiminhtrung1997** [reply]
@rumstead 

Oh, I think my question is not like my thought. I correct it as below.

>Is there a kind of ApplicationSet that deploys multiple Applications for only one or maybe more than one cluster?

Is there a kind of ApplicationSet that deploys multiple Applications as helm chart for only one or maybe more than one cluster?

This means I can put the list of git repositories and clusters in the generators field.

For example, I add 3 git repositories and 2 clusters. There will be 6 Applications, 3 Applications for each cluster.

**Reply by rumstead** [reply]
Yes, can you template the `repoURL` and use a matrix generator with cluster and git. Another rough example that could be cleaned up

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
spec:
  generators:
    - clusters:
        selector:
          matchLabels: # Adjust this to match your cluster labels
            environment: production  
    - git:
        repoURL: "https://github.com/example/repo.git"
        revision: "HEAD"
        files:
          - path: "path/to/your/config.yaml"
  template:
    metadata:
      name: '{{cluster.name}}-{{namespace}}-app'
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}" # coming from your config.yaml
        targetRevision: HEAD
        path: '....'
      destination:
        name: '{{cluster.name}}'
        namespace: '{{namespace}}'  # You can define this in the config.yaml or use a static value
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

**Reply by laiminhtrung1997** [reply]
If I have many git repositories for helm charts, can the manifest work be done like this?
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
spec:
  generators:
    - clusters:
        selector:
          matchLabels: # Adjust this to match your cluster labels
            environment: production
    - git:
        repoURL: "https://github.com/example/repo-1.git"
        revision: "HEAD"
        files:
          - path: "path/to/your/config.yaml"
    - git:
        repoURL: "https://github.com/example/repo-2.git"
        revision: "HEAD"
        files:
          - path: "path/to/your/config.yaml"
  template:
    metadata:
      name: '{{cluster.name}}-{{namespace}}-app'
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}" # Can this template with these git repoURL above?
        targetRevision: HEAD
        path: '....'
      destination:
        name: '{{cluster.name}}'
        namespace: '{{namespace}}'  # You can define this in the config.yaml or use a static value
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
