### DISCUSSION TITLE
Regular Expression Matching in Notifications Triggers Conditions

### DISCUSSION THREAD

**Discussion by dmatviichuk** [argoproj/argo-cd#20912] [Q&A]
Hi,
I am trying to use regular expressions in the when clause of notification triggers. Specifically, I want to check if a string matches a certain pattern, e.g `{{(call .repo.GetAppDetails).Helm.GetParameterValueByName "image.tag"}}` contains `feat-`. It works well in template.message but doesn't work in triggers when Condition:

```
  triggers:
    trigger.on-image-change: |
      - description: Image has changed.
        send:
          - app-image-change
        when: |
          app.status.operationState.phase in ['Succeeded'] and
          app.status.health.status == 'Healthy' and contains("{{(call .repo.GetAppDetails).Helm.GetParameterValueByName "image.tag"}}" "feat")
```
