### DISCUSSION TITLE
Argocd UI Okta login with group AD Group based Access for Argocd Applications

### DISCUSSION THREAD

**Discussion by tppalani** [argoproj/argo-cd#20994] [Q&A]
Hi Team,

1. I'm using Argocd Version v2.12.4+27d1e64 and i enabled okta sso login.
2. I have AD group name called DEVOPS-ADMIN under this group my user ID mapped.
3. Using my user name and password using okta button i can able to login argocd UI page.
4. After login I'm not able to see any application.
5. Here the config map which i have used.

argocd-cm
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: >
    name: Okta
    issuer: https://my-issuer
    clientID: abcdefghiljkl
    clientSecret: abhddpsdlapsdlsldsdlsldlasldspaladladadadasdsdasadss
    group: filteredgroups
    requestedScopes: ["openid",  "profile",  "email",  "filteredgroups"]
    requestedIDTokenClaims: {"filteredgroups": {"essential": true}} 
    redirectURI: https://my-host-dns/auth/callback
  server.rbac.log.enforce.enable: 'false'
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://my-host-dns
```

argocd-rbac-cm

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    # Allow DEVOPS-ADMIN to view all applications
    p, role:admin, applications, get, */*, allow
    g, DEVOPS-ADMIN, role:admin

    # Allow KF-DEV to view specific applications
    p, role:dev, applications, get, default/kf-tools--pipelines, allow
    g, KF-DEV, role:dev
  scopes: '[email, profile, filteredgroups]'

```

Can you please help me why i'm not able to view the application from argocd UI side.
