### DISCUSSION TITLE
issue with pulling Helm charts from private Docker Hub OCI registry

### DISCUSSION THREAD

**Discussion by kurtlieu** [argoproj/argo-cd#21060] [General]
I'm attempting to follow the ArgoCD app of apps pattern.
I have access to an external, private Docker Hub where the customer stores their Helm charts.
I have created a Kubernetes Secret with the credentials the customer has provided, and see that it connects in the ArgoCD portal under Repositories.
I can also manually run helm registry login [registry-1.docker.io](http://registry-1.docker.io/) , authenticate, and pull their helm charts 

```
helm pull oci://registry-1.docker.io/CUSTOMER_ORG_NAME/CUSTOMER-HELM-CHART
apiVersion: v1
kind: Secret
metadata:
  name: customer-helm-registry-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: customer-helm-registry
  url: registry-1.docker.io
  enableOCI: "true"
  type: helm
  username: "REDACTED"
  password: "REDACTED"
  ForceHttpBasicAuth: "true"
```
I have my own private GitHub repo where my ArgoCD Application manifests and (parent) Helm charts are stored.
in my Application manifest, I point to the GitHub repo itself
```
spec:
  project: default
  sources:
  - repoURL: git@github.com:my_org_github/aip.git  # Your IAC repo URL
    path: apps/MY_PARENT_HELM_CHART_WRAPPER_OR_CUSTOMER_HELM_CHARTS
    targetRevision: HEAD
    helm:
      # releaseName: customer_app_name
      passCredentials: true
      valueFiles:
        - dev.values.yaml

```
In my Chart.yaml, I have dependencies set to point to the customer's Docker Hub

```
dependencies:
- name: "CUSTOMER-HELM-CHART"
  version: 1.0.0

  # This auths successfully and the syntax to pull is correct, but does NOT work. It should auth to oci://registry-1.docker.io, NOT oci://registry-1.docker.io/CUSTOMER_ORG_NAME
  # repository: "oci://registry-1.docker.io/CUSTOMER_ORG_NAME"

  # This auths correctly, but does NOT pull the chart correctly (because I haven't specified the org)
  repository: "oci://registry-1.docker.io"
```
As pointed out in the comments, I've observed the above behavior based on the logs from the argocd-repo-server container
Changing the name to CUSTOMER_ORG/customer-helm-chart introduces this error
You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: CUSTOMER_ORG/customer-helm-chart

I understand that ArgoCD itself supports the ability to authenticate and directly pull from OCI registries.
and that Helm dependencies can also pull from private OCI repositories.
but chaining this together where I introduce a middle/parent Helm chart, causes me this discrepancy.

Does anyone have insight as to whether or not this design is possible?
Whether I have missed any sort of configuration that would enable this, or whether it's a bug or edge case with ArgoCD?
Or am I chasing down a completely lost cause.

I would need to have the project's Helm charts stored within my own GitHub or have hosted in another private Helm Chart repository such as ChartMuseum or ArtifactHub

I saw this issue which seems similar, but I'm unclear as to where I might be going wrong
https://github.com/argoproj/argo-cd/issues/12436

**Comment by rhysjtevans** [comment]
Bitnami have also moved to this pattern of hosting

**Comment by denniskorbginski** [comment]
I don't think this issue is related to the app-of-apps-pattern specifically. I'm trying to use my Docker Hub credentials to avoid running into unauthenticated image pull limits. Creating a simple app like this does not make use of my credentials:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-nginx-demo
spec:
  destination:
    namespace: bitnami-nginx-demo
    server: https://kubernetes.default.svc
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 19.0.1
    chart: nginx
    helm:
      passCredentials: true
  sources: []
  project: apps
```

I've created this secret, which also shows up fine in Argos list of repositories
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-oci-credentials-test
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  enableOCI: "true"
  name: "dockerhub"
  type: "helm"
  url: "registry-1.docker.io"
  username: "username"
  password: "password"
  ForceHttpBasicAuth: "true"
```

In the debug logs, I also find this line which makes me thing that Argo does realize that a secret for Docker Hub exists:
```
level=debug msg="registry-1.docker.io has credentials"
```

**Comment by knightprog** [comment]
Same problem on my side.  
I managed to make the oci dependency to work with a private Dockerhub with a (really ugly) workaround by wrapping the helm binary into a shell script:

```
repoServer:
...
    initContainers:
    - name: ugly_docker_hub_login_workaround
...
      volumeMounts:
        - name: helm-custom-binary
          mountPath: /helm-custom-binary
      command: [ "/bin/bash", "-c" ]
      args:
        - |
          cp /usr/local/bin/helm /helm-custom-binary/helm.bin;
          cat <<'EOF' > /helm-custom-binary/helm
          #!/usr/bin/env bash
          args=($@)
          if [ "$#" -gt 2 ] && [ $1 == "registry" ] && [ $2 == "login" ] && [ $3 == "registry-1.docker.io/mycoolorg" ]; then
            args[2]="registry-1.docker.io"
          fi
          helm.bin ${args[@]}
          EOF
          chmod +x /helm-custom-binary/helm;
  volumeMounts:
    - name: helm-custom-binary
      mountPath: /usr/local/bin/helm
      subPath: helm
    - name: helm-custom-binary
      mountPath: /usr/local/bin/helm.bin
      subPath: helm.bin
  volumes:
    - name: helm-custom-binary
      emptyDir: {}
...
```

**Reply by Falltrades** [reply]
Thank you @knightprog. Got the same issue on our side, tried various things like setting up initcontainers to login to registry with `helm registry login`. Managed to work with avp-plugins on avp containers thanks to sharing cache with `repo-server` but never managed to pull properly directly from `repo-server`.

We tried using your logic with helm plugins but did not work also. In the end, your workaround is the most direct and clearly pinpoint where the issue is.
Hope this will be corrected in the future.

**Reply by Falltrades** [reply]
https://github.com/argoproj/argo-cd/issues/22831

**Reply by ElderMael** [reply]
This script did not work for me for some reason. I am using helm secrets too and they also have a wrapper I had to rewrite. Any other options?

**Reply by Falltrades** [reply]
Can you post your sanitized configuration ?

**Reply by ElderMael** [reply]
Sure, here it is:

```yaml
argocd:
  # ..
  repoServer:
    extraArgs:
      - --default-cache-expiration=15m0s
      - --repo-cache-expiration=15m0s
      - --revision-cache-expiration=15m0s
    env:
      - name: DOCKER_AUTH_USERNAME
        valueFrom:
          secretKeyRef:
            name: helm-docker-registry-secret
            key: username
      - name: DOCKER_AUTH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: helm-docker-registry-secret
            key: password
      - name: HELM_PLUGINS
        value: /helm-working-dir/helm-plugins/
      - name: HELM_SECRETS_CURL_PATH
        value: /helm-working-dir/curl
      - name: HELM_SECRETS_VALS_PATH
        value: /helm-working-dir/vals
      - name: HELM_SECRETS_SOPS_PATH
        value: /helm-working-dir/sops
      - name: HELM_SECRETS_BACKEND
        value: vals
      - name: HELM_SECRETS_KUBECTL_PATH
        value: /helm-working-dir/kubectl
      - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
        value: "false"
      - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
        value: "true"
      - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
        value: "false"
      - name: HELM_SECRETS_WRAPPER_ENABLED
        value: "true"
      - name: HELM_SECRETS_HELM_PATH
        value: /usr/local/bin/helm
    initContainers:
      - name: download-tools
        image: alpine/helm:3.15.2
        imagePullPolicy: IfNotPresent
        command: [ sh, -ec ]
        volumeMounts:
          - mountPath: /helm-working-dir
            name: helm-working-dir
        env:
          - name: HELM_PLUGINS
            value: /helm-working-dir/helm-plugins/
          - name: HELM_SECRETS_CURL_PATH
            value: /helm-working-dir/curl
          - name: HELM_SECRETS_VALS_PATH
            value: /helm-working-dir/vals
          - name: HELM_SECRETS_SOPS_PATH
            value: /helm-working-dir/sops
          - name: HELM_SECRETS_BACKEND
            value: vals
          - name: HELM_SECRETS_KUBECTL_PATH
            value: /helm-working-dir/kubectl
          - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
            value: "false"
          - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
            value: "true"
          - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
            value: "false"
          - name: HELM_SECRETS_WRAPPER_ENABLED
            value: "true"
          - name: HELM_SECRETS_HELM_PATH
            value: /usr/bin/helm
          - name: HELM_CACHE_HOME
            value: /helm-working-dir
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
          - name: HELM_SECRETS_VERSION
            value: "4.6.5"
          - name: VALS_VERSION
            value: "0.41.2"
          - name: KUBECTL_VERSION
            value: "1.30.0"
          - name: SOPS_VERSION
            value: "3.10.2"
        args:
          - |
            set -x
            mkdir -p /helm-working-dir/helm-plugins
            
            apk --no-cache add curl
            apk --no-cache add tree
            apk --no-cache add wget
            
            wget -qO /helm-working-dir/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
            wget -qO /helm-working-dir/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64
            wget -qO /helm-working-dir/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
            wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /helm-working-dir/ vals;
            
            /usr/bin/helm plugin install https://github.com/jkroepke/helm-secrets --version "v${HELM_SECRETS_VERSION}"
            
            cp -v /helm-working-dir/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /helm-working-dir/helm
            
            cat <<'EOF' > /helm-working-dir/helm
            #!/usr/bin/env sh
            
            "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" registry login 'registry-1.docker.io' --username "$DOCKER_AUTH_USERNAME" --password "$DOCKER_AUTH_PASSWORD"
            "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" repo add 'registry-1.docker.io' --username "$DOCKER_AUTH_USERNAME" --password "$DOCKER_AUTH_PASSWORD"
            
            if [ "${HELM_SECRETS_WRAPPER_ENABLED}" = "true" ]; then
              if [ "$1" = "install" ] || [ "$1" = "upgrade" ] || [ "$1" = "template" ] || [ "$1" = "lint" ] || [ "$1" = "diff" ]; then
                exec "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" secrets "$@"
              fi
            fi
            
            exec "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" "$@"
            EOF
            
            chown -R 999 /helm-working-dir
            chmod a+rx /helm-working-dir/*
            
            ls -lah /helm-working-dir/
            ls -lah /helm-working-dir/helm-plugins
            
            tree /helm-working-dir
```
