### DISCUSSION TITLE
ApplicationSet git generator: directories. How to template each Application's annotation with arbitrary value?

### DISCUSSION THREAD

**Discussion by mrksph** [argoproj/argo-cd#21087] [Q&A]
Below you can find my ApplicationSet I'm using to deploy my apps for two different environments.

Im using ArgoCD Image Updater, and for it to work I need to set two annotations, the image list and the update-strategy. 

I know I can template the image-list value with using `{{path.basename}}` but can I set the update-strategy with a value set in the values.yaml in each application folder?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://mygithub/repo.git
        revision: HEAD
        directories:
          - path: apps/dev/*    # Match all subdirectories in the dev folder
          - path: apps/prod/*   # Match all subdirectories in the prod folder
  template:
    metadata:
      name: '{{path.basename}}-{{path[1]}}'
      # I want to set ArgoCD Image Updater annotations with values from each application 
      # as some Applications update-strategy might be "latest", others "digest", so on...
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{path.basename}}=ghcr.io/mrksph/{{path.basename}}:{{path[1]}}-latest"
    spec:
      project: default
      source:
        repoURL: https://mygithub/repo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```
