### DISCUSSION TITLE
GitLab, ArgoCD and ArgoNotifications - looking for input and best-practices

### DISCUSSION THREAD

**Discussion by NINNiT** [argoproj/argo-cd#21158] [Q&A]
Hi,

we have a pretty basic setup going, using GitLab and ArgoCD:

-`frontend` repository 
-`frontend-manifests` repository

`argocd` continously syncs the `frontend-manifests` repository to the cluster. The app's image tag in the `frontend-manifests` `kustomization.yml` gets updated using `renovate`. Furthermore, argocd creates a ephemeral preview deployment on Merge-Requests in the `frontend` repository using it's Pull-Request generator.

We are now wondering, if there is any way to further strengthen the interaction between Gitlab and ArgoCD....

Concrete example: it would be nice if the preview deployment's ingress and/or deployment status would be viewable from GitLab itself. Either as a Gitlab environment, or as a comment on the Merge-Request.

The best thing i've found is using ArgoCD's notification service to send webhooks to the Gitlab API. 
However, implementing this seems relatively hacky and pretty complex. 

Some GitLab endpoints we'd have to talk to are:

```
POST /projects/:id/deployments
PUT /projects/:id/deployments/:deployment_id
DELETE /projects/:id/deployments/:deployment_id
```

After we have created a deployment, how does the subsequent `DELETE` call know which `deployment_id` to use?
Is there some sort of shared storage/key-value database between notfications?

Any help and input is massively appreciated :pray: 
Sadly,. the docs and available for this whole topic (Gitlab <-> ArgoCD) seem to be minimal. How are you approaching this? 

That aside, this is what we have for now, which _should_ theoretically work to at least create a deployment. However there seems to be some weird string problem going on, as  `"{{.branch_slug}}"` will not be enclosed in `""`in the requests JSON-body. But this may be out of scope for this discussion....

```yaml
# ApplcationSet
[...]
  template:
    metadata:
      name: "{{.namespace}}-frontend-{{.branch_slug}}"
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.gitlab: ""
      labels:
        gitlabenv: "{{.branch_slug}}"
[...]

# Notification
[...]
  template.gitlab-deployment-status: |
    webhook:
      gitlab:
        body: |
          {
            "environment": "{{.app.metadata.labels.gitlabenv}}",
          }
[...]
```

```text
│ time="2024-12-12T14:59:34Z" level=error msg="Failed to notify recipient {gitlab } defined in resource argocd/frontend: request to {{\n  \"status\":   \"success\" ,\n  \"environment\": branch-slug ,\n  \"sha\": \"ede7f0 │
│ a3ae47abd1bbee40d029ac2829858fb892\",\n  \"ref\": \"main\",\n  \"tag\": \"false\"\n}\n POST https://gitlab.plaesehelp.com/api/v4/projects/123/deployments gitlab} has failed with error code 400 : Bad Request using the configuration in namespace arg │
│ ocd" resource=argocd/frontend
```
**FULL FILES**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  labels:
    app.kubernetes.io/name: argocd-notifications-cm
    app.kubernetes.io/part-of: argocd
data:
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
      - gitlab-deployment-status
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  template.gitlab-deployment-status: |
    webhook:
      gitlab:
        method: POST
        path: /projects/{{.app.metadata.labels.gitlabid}}/deployments
        body: |
          {
            "status":  {{if eq .app.status.sync.status "Synced"}} "success" {{else}} "failed" {{end}},
            "environment": "{{.app.metadata.labels.gitlabenv}}",
            "sha": "{{.app.status.operationState.operation.sync.revision}}",
            "ref": "main",
            "tag": "false"
          }
  service.webhook.gitlab: |
    url: https://gitlab.pleasehelp.com/api/v4
    headers:
    - name: PRIVATE-TOKEN
      value: $argoproj-gitlab-creds:password
    - name: Content-type
      value: application/json
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend-prs
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - pullRequest:
              gitlab:
                # The GitLab project ID.
                project: "123"
                # For self-hosted GitLab (optional)
                api: https://gitlab.pleasehelp.com/
                # Reference to a Secret containing an access token. (optional)
                tokenRef:
                  secretName: argoproj-gitlab-creds
                  key: password
                # Labels is used to filter the MRs that you want to target. (optional)
                labels:
                  - preview
                pullRequestState: opened
              requeueAfterSeconds: 1800
          - list:
              elements:
                - environment: staging
                  url: https://cluster.pleasehelp.local.com:6443
                  namespace: asdf
  template:
    metadata:
      name: "{{.namespace}}-frontend-{{.branch_slug}}"
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.gitlab: ""
      labels:
        gitlabid: "123"
        gitlabenv: "{{.branch_slug}}"
    spec:
      project: myproject
      source:
        repoURL: https://gitlab.pleasehelp.com/asdf/frontend-manifests
        targetRevision: HEAD
        path: "{{.environment}}"
        kustomize:
          images:
            - "image=registry.pleasehelp.com/asdf/frontend:preview-{{.head_sha}}"
          nameSuffix: "-preview-{{.branch_slug}}"
          prune: true
          force: true
          patches:
            - target:
                kind: Ingress
                name: ingress
              patch: |-
                - op: replace
                  path: /spec/rules/0/host
                  value: preview-{{.branch_slug}}.staging.pleashelp.com
      destination:
        server: "{{.url}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```
