### DISCUSSION TITLE
Cache size increases indefinitely when using persisted TMP

### DISCUSSION THREAD

**Discussion by adamwalach** [argoproj/argo-cd#21196] [Q&A]
Based on the [documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/) I configured argocd repo-server to use persisted tmp directory:
```
repoServer:
  deploymentStrategy:
    type: Recreate
  env:
    - name: TMPDIR
      value: /tmp-persisted
  volumes:
    - name: pv-argo-persisted-tmp
      persistentVolumeClaim:
        claimName: argo-persisted-tmp
  volumeMounts:
    - name: pv-argo-persisted-tmp
      mountPath: /tmp-persisted
```
On every restart of the repo-server pod I see that that `/tmp-persisted` is increasing disk usage:
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          95G  6.9G   88G   8% /
tmpfs            64M     0   64M   0% /dev
/dev/sdb        2.0G   96M  1.8G   5% /tmp-persisted
/dev/sda1        95G  6.9G   88G   8% /tmp
```
and in `/tmp-persisted/_argocd-repo` there are new uuid directories
```
/tmp-persisted/_argocd-repo$ ls -la
total 1280
drwxr--r--  6 argocd argocd   4096 Dec 16 10:18 .
drwxrwsr-x  4 root   argocd   4096 Dec 16 10:18 ..
-rw-r--r--  1 argocd argocd  13417 Dec 16 10:18 1435a88e-2441-41b3-b7ec-8b2ff0a92765
d--------- 12 argocd argocd   4096 Dec 16 10:07 74b2de5e-11f1-4b23-a1b9-699b26b60407
d--------- 12 argocd argocd   4096 Dec 16 10:17 7ed9ce2e-5c0b-47ff-80d6-7b7758a73da8
d---------  9 argocd argocd   4096 Dec 16 10:07 7f12c6ee-642f-405a-94b0-9a2be911e5fb
-rw-rw-r--  1 argocd argocd  17514 Dec 16 10:10 98d9b259-9e31-419d-97d7-37493d9bca06
-rw-r--r--  1 argocd argocd 603621 Dec 16 10:17 9a4179b3-a6e6-4e68-843c-a661035a90f3
-rw-rw-r--  1 argocd argocd  13417 Dec 16 10:07 9cbd23fc-d25b-4a49-8566-135d09c2f57e
d---------  9 argocd argocd   4096 Dec 16 10:17 ea7936c1-4bd0-43cb-9d41-a62f85fb195f
-rw-r--r--  1 argocd argocd  17514 Dec 16 10:17 f22573d7-93b0-41d5-998e-5f8c21cdd660
-rw-rw-r--  1 argocd argocd 603621 Dec 16 10:07 f885465c-bc61-45cc-a9f2-024fc36f37d0
```

Looks like the repo-server pulls repositories on every restart instead of using the cache.
I suspect that it may be caused by [randomized paths](https://github.com/argoproj/argo-cd/discussions/9889#discussioncomment-7903611). 
Is there any way to force repo-server to use cached repositories?
