### DISCUSSION TITLE
stable image tag not availble?

### DISCUSSION THREAD

**Discussion by claywd** [argoproj/argo-cd#21261] [Q&A]
I understand there is a stable tag on the repo but apparently argocd isn't propogating that image tag to quay? Tried to override the helm default version value with stable it went to crap right away.

``` yaml
Name:             argocd-redis-secret-init-xqpkz
Namespace:        argocd
...
Controlled By:  Job/argocd-redis-secret-init
Containers:
  secret-init:
    Container ID:    
    Image:           quay.io/argoproj/argocd:stable
    Image ID:        
    Port:            <none>
    Host Port:       <none>
...
Events:
  Type    Reason   Age                    From     Message
  ----    ------   ----                   ----     -------
  Normal  BackOff  3m13s (x328 over 78m)  kubelet  Back-off pulling image "quay.io/argoproj/argocd:stable"
```
