### DISCUSSION TITLE
ArgoCD Google OAuth Login Redirects Back to Login Page

### DISCUSSION THREAD

**Discussion by helenrai** [argoproj/argo-cd#21355] [Q&A]
I have configured Google OAuth for ArgoCD using the following argocd-cm configuration:
```
data:
  url: https://argocd.mydomain.com
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com
        clientSecret: XXXXXXXXXXXXXXXXXXXX
      type: oidc
      id: google
      name: Google
```

When I access https://argocd.mydomain.com and click on "Login via Google", I am redirected to the argocd login page again. 
When expected result was to be redirected to gmail page.
Here are additional details about my setup:

-    ArgoCD is running in a Kubernetes cluster.
-    The ArgoCD URL is exposed via an ingress using a custom domain.
-    The redirect URL in Google OAuth settings is set to https://argocd.mydomain.com/api/dex/callback.
-    No errors are visible in the browser or the ArgoCD logs.

I’ve already tried:

-    Ensuring the url in the ConfigMap matches the domain.
-    Restarting the argocd-server pod after configuration changes.

What could be causing the issue? How can I troubleshoot this further?
