### DISCUSSION TITLE
Webhook triggers sync (instead of refresh) on all apps

### DISCUSSION THREAD

**Discussion by miran248** [argoproj/argo-cd#21498] [Q&A]
Hey,

It seems like every time a webhook is called, it triggers a job in an app, where nothing has changed.
It's as if it triggers the sync on all argocd apps - i thought it would do the refresh only.

Webhook is called from bitbucket repo (push action), containing manifests for all services and apps, so whenever one of the apps changes (updates the image tag), argo applies the change to the cluster.

Job has the following annotations
```yaml
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
```
(this job runs migrations on sync, but before the changes are applied)

Using [argocd 7.7.3](https://github.com/argoproj/argo-helm/tree/argo-cd-7.7.3/charts/argo-cd)

Ideas?
Can i force argocd somehow to only do the refresh on webhook and not the sync?

Thanks,
Miran
