### DISCUSSION TITLE
Using Git Generator for Directories with Selectors?

### DISCUSSION THREAD

**Discussion by jwilkicki** [argoproj/argo-cd#21507] [Q&A]
Hi!

I'm working a bootstrapping process where I use helmfile to setup a bunch of services (e.g. ingress controller) and then Argo.  The last thing I install is a Helm chart that defines Argo CD applications that 'takeover' everything helmfile installed (including Argo) and then has Argo installs some other apps now that it is on its feet.

I have a directory where all of the helm charts live that define the Argo CD Application equivalents of the helmfile releases.  I also have a few library charts to keep stuff dry and the chart that defines the ApplicationSet that helmfile installs last to bootstrap everything.  It's loosely based on how kube-prometheus-stack arranges all of its charts so I can model releasing all of this the way they do.  An example:

```
bootstrapper/
   charts/
         ingress/
         istio/
         argocd/
        app-library/
        some-reusable-stuff/
        addons/
helmfile.yaml
```

I tried using the Git Generator together with selectors to exclude things that I never want Argo to manage because they aren't really deployable things (like app-library and some-reusable-stuff).  I also wanted folks to be able to disable some things I'm adding in when they build their own clusters; if they don't want istio they can add an exclusion to it.

Here's my example appset:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git: 
        repoURL: https://github.example.com/development/bootstrapper
        revision: HEAD
        directories:
          - path: charts/*
        selector:
          matchExpressions:
            - key: basename
              operator: NotIn
              values:
              - app-library
              - some-reusable-stuff
              - addons
            - key: basename
              operator: NotIn
              values: {{ .Values.excluded | toYaml | nindent 16 }}
  template:
    metadata:
      name: '{{`{{ .path.basename }}`}}-app'
    spec:
      project: admin
      source:
        repoURL: https://github.example.com/development/bootstrapper
        targetRevision: HEAD
        path: '{{`{{ .path.path }}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
```

As it stands now, the AppSet is just picking up everything including the chart that defines the AppSet, so I have an infinitely nested app set.  Any ideas on what might need to be changed?  I'd rather not list every chart in a list generator and do it that way; it would be nice to be able to add new things by just creating the chart for it in the `charts` directory.

Thanks for the help!
