### DISCUSSION TITLE
argocd sync app --dry-run should affect status and metrics of the apps?

### DISCUSSION THREAD

**Discussion by jsolana** [argoproj/argo-cd#21661] [General]
Hello! I’d like to hear your thoughts.

Currently, executing the command `argocd app sync --dry-run` affects both the application’s state and the internal metrics exposed by ArgoCD (eg: `argocd_app_info`).

The main issue is that if there are alerts based on these metrics, and the dry-run execution identifies an error (e.g., a change that violates a Kyverno policy or an invalid CRD schema), the application state changes to `SyncErr`. This also updates the metrics, which can potentially trigger alerts based on these metrics.

For example:

```yaml
# alert manager alert definition
- alert: ArgoCDApplicationUnknown
  expr: sum by (cluster) (argocd_app_info{sync_status="Unknown"}) > 0
  for: 15m
...
```

Since the definition of a `dry-run `is to execute requests without persistence, I wonder if it makes sense to handle it in a way that ensures no changes are made. 

Alternatively, adding a **dry_run label** to differentiate operational requests from dry-run requests could also be an option (a similar change has been proposed for kyverno [link](https://github.com/kyverno/kyverno/issues/11961)).

What do you think? Thanks!
