### DISCUSSION TITLE
Reference Vault secrets in the application manifest

### DISCUSSION THREAD

**Discussion by xRTRx** [argoproj/argo-cd#21680] [Q&A]
I have secrets stored in the vault, and I want to use them in the application manifest
I need to set the PostgreSQL username, database, and password from Vault in the Helm chart’s parameters. I’m unsure how to configure ArgoCD (or a plugin like argocd-vault-plugin) to fetch these secrets.
Looking for guidance on the exact steps and configuration needed.
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 14.2.16
    helm:
      parameters:
        - name: postgresql.username
          value: 
        - name: postgresql.database
          value: 
        - name: postgresql.password
          value:
    chart: postgresql-ha
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgresql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
```
