### DISCUSSION TITLE
Disable compare/sync for object that has specific annotation on it

### DISCUSSION THREAD

**Discussion by kutsyk** [argoproj/argo-cd#21690] [Q&A]
We have ArgoCD ApplicationSet that is managing CRD objects on target clusters.

For some of the CRD objects, target cluster owner want to have their own values and not managed via ArgoCD. 
So for example we have 200 objects and 5 of them have annotation `managed.by: self-service` on set of specific target clusters.

Here is out part of our AppSet manifest:

```
    spec:
      project: default
      source:
        repoURL: 'https://our.custom.repo.git'
        targetRevision: "master"
        path: '.'
        directory:
          recurse: true
      ignoreDifferences:
        - group: api.customer-api.com
          kind: OurCrdObject
          jqPathExpressions:
            - if (.metadata.annotations["managed.by"] == "self-service") then .spec.custom_field else null end
            - .metadata.annotations["managed.by"] | select(. == "self-service")
      destination:
        server: '{{.server}}'
```

There are few issues with this solution:
1. it doesn't work
2. This `jqPathExpression` produces wrong output `if (.metadata.annotations["managed.by"] == "self-service") then .spec.custom_field else null end` because result of this is value of `.spec.custom_field`, which is incorrect for `jq`

I've tried changing it to `if (.metadata.annotations["managed.by"] == "self-service") then ".spec.custom_field" else null end`

The difference is **".spec.custom_field"**, which means it should return this as path, which doesn't fail, but result is strange.

Result is that:
1. It doesn't delete annotation - success
2. It doesn't delete existing value in `.spec.custom_field` of CRD object - success
3. It adds what in repository on top of `.spec.custom_field` in CRD objects - **WRONG**

Expectations are that it won't add/remove anything in `.spec.custom_field`. 

I did add annotations:
- argocd.argoproj.io/compare-options: IgnoreExtraneous
- argocd.argoproj.io/sync-options: Skip

But object is still shown in `diff` and app is out of sync.

What would be best way to do this properly to get set of objects ignored based on annotation value?

Thanks,
Vasyl
