### DISCUSSION TITLE
Is this a bug or did I use it wrong?

### DISCUSSION THREAD

**Discussion by therealpoys** [argoproj/argo-cd#21718] [Q&A]
Hey,

I'm new to Argo and I try to create an account to use in the CI/CD pipeline.
So I created a User with the name: gitlabbot
With following Rules

```
apiVersion: v1
data:
  policy.csv: |
    g, gitlabbot, role:admin
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
```

```
apiVersion: v1
data:
  accounts.gitlabbot: apiKey,login
  admin.enabled: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd

```
So I created a token via frontend and also with cli tried both and run this command:

argocd login test-argoconcat.cloud.ccc-concat.de --username gitlabbot --auth-token  <token> --grpc-web --loglevel debug

Then he still asks me for my password. It is not important what the <token> is, I guess he thinks that the token is wrong.

But in the logs the token is generated
```
2011512ffd61\",\"nbf\":1738229823,\"sub\":\"gitlabbot\"}" grpc.request.content="name:\"gitlabbot\" " grpc.service=account.AccountService grpc.start_time="2025-01-30T10:27:40Z" span.kind=server system=grpc
time="2025-01-30T10:27:40Z" level=info msg="Starting configmap/secret informers"
time="2025-01-30T10:27:40Z" level=info msg="secrets informer cancelled"
time="2025-01-30T10:27:40Z" level=info msg="configmap informer cancelled"
time="2025-01-30T10:27:40Z" level=info msg="Configmap/secret informer synced"
time="2025-01-30T10:27:40Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=CreateToken grpc.service=account.AccountService grpc.start_time="2025-01-30T10:27:40Z" grpc.time_ms=116.396 span.kind=server system=grpc
```

I use the Argo serverversion 2.13.2

Do you know what I did wrong?
Could this be a bug?

Thanks for your Help
Jannik
