### DISCUSSION TITLE
ApplicationSet with Environment Variables: Dynamic Cluster Identification and Config Management

### DISCUSSION THREAD

**Discussion by grok-rs** [argoproj/argo-cd#21721] [Q&A] [answered]
I am currently managing several Kubernetes clusters with ArgoCD. Each cluster (e.g., develop-01, production-01, production-02) has its own ArgoCD instance. We maintain a GitOps repository that is structured like this:
```repo-root/
  develop-01/
    kustomization.yaml
    grafana/
      overrides.yaml
  production-10/
    kustomization.yaml
    grafana/
      overrides.yaml
  shared/
    grafana/
      kustomization.yaml
      grafana.yaml
```

I want to achieve the following:

1. **Shared ApplicationSet Configuration:**

   - Define default values for applications in a shared configuration.
   - Avoid code duplication across multiple cluster-specific configurations.

2. **Cluster-Specific Overrides:**

   - Allow each cluster to override specific values (e.g., ingress host, resource limits) without repeating the entire configuration.

3. **Simplified GitOps Workflow:**

   - Each cluster should use its own `kustomization.yaml` file that references shared configurations (e.g., `../shared/grafana.yaml`).
   - The ApplicationSet should dynamically apply the correct values based on the environment (cluster).
   
## **Current Challenge**

Currently, I’m facing issues with duplicate configuration and manual effort when managing applications across multiple clusters. Here’s an example ApplicationSet YAML for a Grafana Helm chart:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@gitlab.com:repo-level/some-gitops-repo.git
        revision: HEAD
        files:
          - path: '*/grafana/overrides.yaml' # Here * relays on specific cluster
         # I want to use something like this
         # - path: '${environment}/grafana/overrides.yaml' 
         # where environment is name of cluster where argo is located

  template:
    metadata:
      name: grafana
    spec:
      project: default
      source:
        repoURL: https://grafana.github.io/helm-charts
        chart: grafana
        targetRevision: "8.6.4"
        helm:
          values: |
            ingress:
              enabled: true
              hosts:
                - {{host}}
      destination:
        server: https://kubernetes.default.svc
        namespace: grafana
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
References:
I see there is only limited set of default variables
https://argo-cd.readthedocs.io/en/latest/user-guide/environment-variables/

Also, will I be able to provide a custom OS environment with CMP?
https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/

**So, the main question is how to restrict argocd to use only overrides from specific folder correlated to it's cluster?**
