### DISCUSSION TITLE
Understanding and Controlling notified.notifications.argoproj.io Behavior in ArgoCD Notifications

### DISCUSSION THREAD

**Discussion by ska-ops** [argoproj/argo-cd#21821] [Q&A]
I am trying to better understand the **notified.notifications.argoproj.io** annotation in ArgoCD Notifications and would like to clarify

- How does ArgoCD determine when to resend a notification?
- It appears that **notified.notifications.argoproj.io** is used to track previously sent notifications and prevent duplicates.
- The annotation stores records in the following format:

`"EVENT:[INDEX].NOTIFICATION_ID:CHANNEL:RECIPIENT": TIMESTAMP`

**Example:**

```
notified.notifications.argoproj.io: '{
  "on-deployed:[0].asdasdasd3312:github": 1732200871
}'
```

What is the logic behind this mechanism? Does ArgoCD check this annotation before sending a notification? How long does ArgoCD wait before checking and resending notifications? and How can I disable or bypass this mechanism to allow notifications to always be sent?

I have tried manually removing the annotation using

```
kubectl annotate application my-app -n argocd notified.notifications.argoproj.io- --overwrite
```

This works, but is there a way to configure ArgoCD to automatically ignore or reset the annotation? I attempted modifying **argocd-notifications-cm** to disable tracking, but could not find a setting for this. Is there a supported way to disable notification tracking?

How can I make sure a notification gets triggered every time a sync happens? Currently, it seems that ArgoCD only triggers notifications if the application's sync or health status changes. If an application is already in a Synced state, reapplying it doesn't trigger a new notification. Is there a way to configure ArgoCD to always send a notification, even if the application state doesn't change?

**Steps to Reproduce:**

Deploy an application with a notification configured for on-sync-succeeded. After the first notification is sent, check the application annotations:

```
kubectl get application my-app -n argocd -o yaml | grep notified.notifications.argoproj.io
```

Try triggering another sync (`argocd app sync my-app`). Notice that no additional notification is sent unless the annotation is removed manually.

**Expected Behavior**

- There should be a clear way to configure whether notifications are always sent or tracked.
- There should be a configurable way to bypass or reset the notification tracking automatically.

**Actual Behavior**

- ArgoCD tracks notifications using **notified.notifications.argoproj.io**, preventing duplicates.
- There is no documented way to disable or reset this behavior without manual intervention.

**Workarounds Tried**

- Manually removing the annotation (kubectl annotate ... --overwrite).
- Using a CronJob to periodically remove the annotation:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-argocd-notifications
  namespace: argocd
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: bitnami/kubectl
            command:
            - /bin/sh
            - -c
            - "kubectl annotate application my-app -n argocd notified.notifications.argoproj.io- --overwrite"
          restartPolicy: OnFailure
```
Attempting to modify argocd-notifications-cm but found no setting to disable tracking.

**Questions**

1. Can you confirm how ArgoCD checks notified.notifications.argoproj.io before sending notifications?
2. Is there an official way to disable or configure notification tracking so that messages are always sent?
3. How can I force notifications to be triggered every time a sync happens, even if the application state remains unchanged?

**Version Information:** 
ArgoCD Version: 2.14.2 (latest as of today)
