### DISCUSSION TITLE
Application out of sync because of "new" annotation from openshift

### DISCUSSION THREAD

**Discussion by ffppmm** [argoproj/argo-cd#21879] [Q&A] [answered]
``Hi,

praise to ArgoCD Project, made our deployments so much easier :)

Using: v2.13.4+102853d

We noticed since we updated our openshift-cluster to 4.15 (not shure if its the argoCD version ore the openshift version that introduced this behavior) that some apps are out of sync, because of the following annotation on a Deployment:
```yaml
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-02-14T06:00:02+01:00'
```
For some apps we rollout (restart) PODs with:
```
oc rollout restart deployment -n NAMESPACE DEPLOYMENTNAME
```
This sets the annotation and argo shows the diff for deletion. Any thoughts on this how we could have "normal" in sync Applications again in ArgoCD? Should this maybe be ignored by argoCD, should I raise an issue?

Many thanks for this awesome tool,
regards Philipp

**Comment by ffppmm** [comment]
Hi,
I tried the following but it didn't work :(
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  ignoreDifferences:
    - jsonPointers:
        - /spec/template/metadata/annotations
      kind: Deployment
...
```
Any ideas on this please,
regards Philipp

**Reply by rumstead** [reply]
Try this
```yaml
      ignoreDifferences:
        - jsonPointers:
            - /spec/template/metadata/annotations
          group: apps
          kind: Deployment
```

**Comment by ffppmm** [comment]
Hi,

I tried but didn't help :(

regards Philipp

**Reply by rumstead** [reply]
Can you provide a screenshot of the diff?

**Reply by ffppmm** [reply]
![image](https://github.com/user-attachments/assets/0b74d03b-8a3d-4130-abb6-39b795e44526)
Here it is :)

Thanks for your help,
regards Philipp

**Reply by rumstead** [reply]
Ok, took me a few tries to set it up on my end. I guess you have an empty annotation defined on your deployment in git? Eg, 
```
spec:
  template:
    metadata:
      annotations: {}
```
I haven't been able to reproduce this though. 
https://github.com/user-attachments/assets/5305369e-aee9-4238-990f-1d8837461127
