### DISCUSSION TITLE
Argo 2.14 => Template for project field

### DISCUSSION THREAD

**Discussion by Vinaum8** [argoproj/argo-cd#21881] [General]
Hello guys, how's it going?
I need using template for project field, its possible?

Issue: https://github.com/argoproj/argo-cd/issues/13665

I am getting the following error: 

**message: >-**
     failed to combine string maps with merging params for the matrix
     generator: found duplicate key project with different value, a: default , b:
 **reason:** ApplicationGenerationFromParamsError

**Code sample:**
```
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Delete=false
      name: 'test-{{ .component}}-{{ .name}}'
    spec:
      destination:
        namespace: '{{ .namespace}}'
        server: '{{ .server}}'
      ignoreDifferences:
      - group: apps
        jsonPointers:
        - /spec/replicas
        kind: Deployment
      - group: argoproj.io
        jsonPointers:
        - /spec/replicas
        kind: Rollout
      project: {{ .project }}
```
