### DISCUSSION TITLE
Pass value with git generator in Application Set

### DISCUSSION THREAD

**Discussion by talyahalomy** [argoproj/argo-cd#21897] [Q&A]
Hey all, I want to add labels for my applications that created trough Application Set, so I will be able to have 
`team` label with the value, which then will help me with sending alerts to the relvent teams, by using Elastic with get those metrics by Prometheus.

I am now able to see those labels after I configured my controller.metrics with:
```yaml
applicationLabels: 
        enabled: true
        labels: [team]
```

But now my next part is to have those label created dynamic based on the value which stored on each service application values file.

My current Applicaiton set configuration is:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/repository/argocd.git 
      revision: dev
      directories:
       - path: helm/dev/*
       - path: helm/dev/values_global.yaml
  template:      
    metadata:
      name: "{{`{{path[2]}}`}}"
      namespace: argocd
      labels: 
        team: <value> # value of "team"
    spec:
      project: my-apps

      sources:
      - repoURL: https://github.com/repository/argocd.git
        targetRevision: main
        ref: values
      
      - repoURL: https://github.com/repository/helm-charts.git
        targetRevision: "{{ .Values.helm.version }}"
        path: 'chart'
        helm:
          valueFiles:
            - $values/helm/{{ .Values.environment }}/values_global.yaml
            - $values/helm/{{ .Values.environment }}/{{`{{path[2]}}`}}/values_{{ .Values.environment }}.yaml 
```
       
How can I achieve that?
