### DISCUSSION TITLE
Having ApplicationSet with matrix generator (combining application list with namespaces list), how can I conditionally prevent creation of some of the child applications.

### DISCUSSION THREAD

**Discussion by typekpb** [argoproj/argo-cd#21918] [Q&A]
I'm using ApplicationSets for the app creation (habing single ArgoCD instance managing deployments to multiple namespaces. 
My grouping is like this: 1 root Application, referring to multiple ApplicationSets (per app type), each ApplicationSet creates app itself in multiple namespaces. I'm using matrix generator, that combines 2 lists (one for applications and one for target environments/namespaces).
I want to prevent the creation of specific app in the specific namespace. Is there a way to conditionally do so?

My current workaround is, that for the specific app+namespace combination I refer to special branch of the target repo (that holds helm chart, which has no resources defined). But that is rather poor, as in the ArgoCD UI I can still see the app created (just having no resources).

**Comment by ChristianCiach** [comment]
>  I'm using matrix generator, that combines 2 lists (one for applications and one for target environments/namespaces).

You should be able to combine value interpolation with Post-Selectors. I didn't try it myself, but it should look something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  applyNestedSelectors: true
  generators:
  - matrix:
      generators:
      - matrix:
        - list:
            elements: 
            - app: app1
            - app: app2
            - app: app3
        - list:
            elements:
            - env: prod
            - env: stage
            - env: test
      - list:
          elements:
          - appEnv: '{{.app}}-{{.env}}'
    selector:
      matchExpressions:
      - key: appEnv
        operator: NotIn
        values:
        - 'app1-prod'
        - 'app3-stage'
        - 'app3-prod'
  ```
