### DISCUSSION TITLE
Project destination namespace and wildcards

### DISCUSSION THREAD

**Discussion by emilioziniades** [argoproj/argo-cd#21967] [Q&A]
Hi there,

I'm trying to setup Projects declaratively, following [this](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects) and [this](https://argo-cd.readthedocs.io/en/stable/operator-manual/project-specification/).

Is it possible to use a wildcard for the project destination namespaces? I tried looking in the documentation but couldn't find anything.

For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: develop
  namespace: argocd
spec:
  description: Develop environment
  destinations:
    - namespace: "*"
      name: develop
```

Is this possible?

Thanks!
