### DISCUSSION TITLE
Source Hydrator, ApplicationSets and multiple sources

### DISCUSSION THREAD

**Discussion by eripa** [argoproj/argo-cd#21971] [Q&A] [answered]
Hello

I was trying out the Source Hydrator feature yesterday, trying to get it working with my setup. I have everything running off `ApplicationSets` and all use multiple sources. A stripped down version of an `ApplicationSet` is pasted below.

In short I have my applications all setup at least two sources, one that makes my repository available as "values" and then range over the application configuration using the git generator to add 1 or more helm charts.

I have not been able to get the Source Hydrator to work with this setup:

- Since I don't have any "explicit" `Applications`, what should I put in the `drySource.path`?
- From the structure it seems like it's intended to use with a single source application
- There seem to be some kind of issue with ApplicationSets while using the `git generator`, such as:

```text
level=error msg="Failed to hydrate app: failed to hydrate apps: failed to get repo objects: failed to get repo objects: failed to get cluster version for cluster \"\": failed to get cluster info for \"\": error getting cluster: error getting cluster: rpc error: code = NotFound desc = cluster \"\" not found" app=argocd/my-cluster-testapp destinationBranch=environments/staging sourceRepoURL="ssh://git@githost.example.com/foo/barb" sourceTargetRevision=HEAD
```

Thanks a lot 🙏 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: ssh://git@githost.example.com/foo/bar
      revision: HEAD
      files:
      - path: "clusters/my-cluster/**/app-config.yaml"
  template:
    metadata:
      name: 'my-cluster-{{ .name }}'
    spec:
      project: my-cluster
      destination:
        name: my-cluster
        namespace: '{{ index .path.segments 2 }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  templatePatch: |
    spec:
      sources:
        {{- range $chart := .charts }}
        - {{- /* local/vendored charts can be referenced via $chart.path */}}
          {{- if $chart.path }}
          repoURL: '{{ default "ssh://git@githost.example.com/foo/bar" $chart.repo }}'
          path: '{{ $chart.path }}'
          targetRevision: '{{ default "HEAD" $chart.version }}'
          {{- else }}
          chart: '{{ $chart.name }}'
          repoURL: '{{ $chart.repo }}'
          targetRevision: '{{ $chart.version }}'
          {{- end }}
          helm:
            releaseName: '{{ $chart.release }}'
            skipCrds: {{ default false $chart.skipCrds }}
            valueFiles:
            {{- range $valueFile := $chart.valueFiles }}
              - $values/{{ $valueFile }}
            {{- end }}
        {{- end }}
        - ref: values
          repoURL: ssh://git@githost.example.com/foo/bar
          targetRevision: HEAD
      sourceHydrator:
        drySource:
          repoURL: ssh://git@githost.example.com/foo/bar
          targetRevision: HEAD
          path: {{ .path.path }}
        syncSource:
          targetBranch: environments/prod
          path: {{ .path.path }}
        hydrateTo:
          targetBranch: environments/staging
```

**Comment by crenshaw-dev** [comment]
> Since I don't have any "explicit" Applications, what should I put in the drySource.path?

You should use whatever path you would have used if you weren't using Source Hydrator. In this case, looks like `$chart.path` would do.

> From the structure it seems like it's intended to use with a single source application

Correct. The supported way to handle your use case would be to use a Helm umbrella chart. 

One of the benefits of the source hydrator is that it enforces that _every_ change for an application must be represented in the history of a single git repo ("[deterministic hydration](https://argo-cd.readthedocs.io/en/stable/user-guide/source-hydrator/#make-hydration-deterministic)"). There are a lot of benefits to this constraint. One downside is that it makes the multi-source app pattern incompatible.

> There seem to be some kind of issue with ApplicationSets while using the git generator, such as:

To me the error looks like an Application controller error, not an ApplicationSet controller error. Can you paste the full Application spec of the failing app?

**Reply by eripa** [reply]
Thanks for the quick reply @crenshaw-dev!

Being single-source significantly reduces its usefulness unfortunately. It feels like taking a step back to before `.spec.sources` was available.

In the above example I've created the `app-config.yaml` that can configure an application to use N amount of charts. Each is either a reference to vendored/local chart or a remote chart. Both are therefore deterministic (as far as tagging/versioning go), so it's either the local git commit hash, or a remote chart version. In my case I also add the same repo as a final source so I can always reference `values.yaml` files in the case of using remote charts. This removes any need for the umbrella overhead.

Could you explain why using multiple sources makes the hydration indeterministic?

**Reply by crenshaw-dev** [reply]
From what I've seen, the main reasons people use multi-source are: 1) brevity (no Chart.yaml, requirements.yaml, etc.) and 2) auth to private charts. In my opinion, the first could be solved by a streamlined Helm umbrella chart syntax, and the latter could be solved by better Argo CD support for private Helm dependencies.

I'm curious, what reason(s) lead you to use multi-source? You mentioned "umbrella overhead," which makes me think it's mostly the first reason I described.

Using multiple sources makes hydration indeterministic _from the perspective of a single branch_. So in order to understand the full history of an Application, you need to look in multiple places. For some use cases, that can be fine. But for others, such as automated promotion between environments, it can be crucial to represent the full history in a linear series of commits.

**Reply by eripa** [reply]
Thanks! I appreciate you for taking the time to consider my (probably obscure) use-case. Yes, I think it falls into the 1) "brevity" category

with multi-source I do this:

* I use the **Git generator** to find all Application configs
* the application config describes my app, this is done via an `app-config.yaml` that can contain N amount of charts and/or a **kustomize** config (these bits were omitted in this example for simplicity)
* with  this I can drop an `app-config.yaml` in my repo and have it spin up an application consisting of several charts and/or kustomizations in any cluster I want, this means:
  * I can use one or more upstream/public app chart(s)
  * I then optionally augment that chart
    * with local chart(s) (usually I've used a common network policy chart here)
    * kustomizations (such as adding Secrets or doing patching)
* with this pattern I can have a _single_ `ApplicationSet` for all my application needs and all my deployments work based on that convention. Each functional deployment (say Longhorn in this case) is all covered in one `Application`.

With the Umbrella pattern I have to lock my setup into using a single chart as the entrypoint, in addition to having to create a bunch of mostly empty Helm Charts, it reduces flexibility and removes the kustomize functionality. And I would possibly have to produce more `ApplicationSets` or explicit `Applications` (for **Kustomize**), as far as I undertand it.

So going back to deterministic, my question then is how can ArgoCD manage to deploy my multi-source application deterministically if this isn't possible during hydration? Granted I haven't read the source hydrator code, but I would imagine that it orchestrates a series of `helm template` and `kustomize builds`, takes the output and commits that with some metadata to a branch. Why is the full history relevant here? The hydrated branch's rendered manifests would just match what the dry source contained on that commit?

I can see that some generators for `ApplicationSets` are indeterministic, but I don't think the Git generator is.  _Side question_: if you use a more dynamic `ApplicationSet` generator, such as the plugin generator and it generates a single-source `Application`, how would you be able to get the full history in that case? (Personally I only use the git generator though).

Example `app-config.yaml`:

```yaml
name: longhorn
charts:
- name: longhorn
  release: longhorn
  repo: https://charts.longhorn.io
  # renovate: repo=https://charts.longhorn.io chart=longhorn
  version: 1.7.2
  valueFiles:
  - clusters/shared/longhorn/values.yaml
  - clusters/my-cluster/longhorn-system/longhorn/values.yaml
- release: network-policies
  path:  "helm-charts/network-policies" # vendored chart local to this repo
  valueFiles:
  - clusters/my-cluster/longhorn-system/longhorn/values-netpols.yaml

enableKustomize: true
```

`kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
- ./volumesnapshotclass.yaml # this is just my class that I add
```

- `values.yaml` and `values-netpol.yaml` are just Helm values files

Generated `Application`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-cluster-longhorn
  namespace: argocd
spec:
  destination:
    name: my-cluster
    namespace: longhorn-system
  project: my-cluster
  sources:
  # this is my kustomize path (same as app-config.yaml)
  - path: clusters/my-cluster/longhorn-system/longhorn
    repoURL: ssh://git@githost.example.com/foo/bar
    targetRevision: HEAD
  # upstream chart
  - chart: longhorn
    helm:
      releaseName: longhorn
      valueFiles:
      - $values/clusters/shared/longhorn/values.yaml
      - $values/clusters/my-cluster/longhorn-system/longhorn/values.yaml
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.2
  # local/vendored chart
  - helm:
      releaseName: network-policies
      valueFiles:
      - $values/clusters/my-cluster/longhorn-system/longhorn/values-netpols.yaml
    repoURL: ssh://git@githost.example.com/foo/bar
    path: helm-charts/network-policies
    targetRevision: HEAD
  # values source for any helm chart
  - ref: values
    repoURL: ssh://git@githost.example.com/foo/bar
    targetRevision: HEAD
```
