### DISCUSSION TITLE
Using git credential sharing with the repo-server plugin

### DISCUSSION THREAD

**Discussion by peschmae** [argoproj/argo-cd#22053] [General]
I'm currently trying to get the `provideGitCreds` flag working on a CMP plugin, where we are using kustomize (and git-crypt).

What I got from the docs at https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#provide-git-credentials and the pull request #15107 is that askpass is used, and CMP injects the necessary environment variables automatically.

The askpass socket, is exposed in `/tmp/reposerver-ask-pass.sock` to the reposerver, so to get this to work in the CMP sidecar, I need to share the `tmp` mount between the reposerver and the sidecar, otherwise I couldn't get it to work.
But according to the docs https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#register-the-plugin-sidecar we **shouldn't** share the `/tmp` mount between the repo server and sidecar.

So I'm really unsure, what's the current recommendation? Should the `/tmp` directory be shared or not?
Or could the askpass socket be moved into a subdirectory, so it's possible to create an additional mount, that only shares the socket?

I think either way, the docs regarding the sidecar credential sharing need some more detail, and ideally even a full example how to configure it. I'll happily create a PR with the outcome of this discussion.

**Comment by andrii-korotkov-verkada** [comment]
Can you use another directory to store the .sock file and share it?

**Reply by peschmae** [reply]
I couldn't find a way to override the path. Right now it seems to be hardcoded in https://github.com/argoproj/argo-cd/blob/master/util/askpass/common.go#L7

**Reply by peschmae** [reply]
I misinterpreted the code, and it's already possible to override the socket path using the `ARGOCD_ASK_PASS_SOCK` env var.

My abbreviated repo-server config now looks like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
  ...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
      # regular repo-server container
      - name: argocd-repo-server
        env:
          ...
          - name: ARGOCD_ASK_PASS_SOCK
            value: /tmp/shared/reposerver-ask-pass.sock
        ...
        volumeMounts:
        ...
        - mountPath: /tmp/shared
          name: tmp-shared
      # cmp plugin sidecar
      - name: cmp-sidecar
        env:
        ...
        - name: ARGOCD_ASK_PASS_SOCK
          value: /tmp/shared/reposerver-ask-pass.sock
        ...
        volumeMounts:
          ...
          - mountPath: /tmp/shared
            name: tmp-shared
      ...
      volumes:
        ...
        - emptyDir: {}
          name: tmp-shared
```

And this way it works.

I'll create a pull request to update the documentation, to mention that the socket needs to be shared with the sidecar, and should be moved to a different directory using the `ARGOCD_ASK_PASS_SOCK` env var
