### DISCUSSION TITLE
How can I automate the creation of an Application in my case?

### DISCUSSION THREAD

**Discussion by vsfomin** [argoproj/argo-cd#22157] [General]
How can I automate the creation of an Application in my case?
I need to create an Application for all files in the preprod directory. 
Also, when new files are added to the directory, the Application will be created as well.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: values-appset
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: service
        repoURL: ssh://git@cprd-bbkt-app02.example.com:7999/conv/argocd.git
        revision: HEAD
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: cnv-preprod  
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}'  # Путь к директории приложения
        repoURL: ssh://git@cprd-bbkt-app02.example.com:7999/conv/argocd.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
            - ../preprod/{{path.basename}}.yml
      syncPolicy:
        automated:
          prune: false  
          selfHeal: true

```
![image](https://github.com/user-attachments/assets/33799451-60d2-421c-b7f2-fb469ee972ce)
