### DISCUSSION TITLE
Kustomization looking for kustomization.yaml instead of taking inline

### DISCUSSION THREAD

**Discussion by radicaled42** [argoproj/argo-cd#22280] [Q&A]
I'm trying to apply an inline kustomization to an ArgoCD App, but when I run the sync I get an error saying: 

`Failed to load target state: failed to generate manifest for source 2 of 2: rpc error: code = Unknown desc = failed to load kustomization.yaml: open <path to cached source>/system-components/cert-manager/kustomization.yaml: no such file or directory`

I'm using v2.12.3+6b9cd82

This is the definition of the argocd application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    argocd.application.type: "system"
spec:
  destination:
    namespace: cert-system
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  sources:
    - helm:
        values: |
            ... <application values>
      path: system-components/cert-manager
      repoURL: {{ .Values.argo.url }}
      targetRevision: {{ .Values.argo.branch }}
    - kustomize:
        patches:
          - target:
              kind: ValidatingWebhookConfiguration
              name: cert-manager-webhook
            patch: |-
              - op: add
                path: /webhooks/0/namespaceSelector
                value:
                  matchExpressions:
                  - key: control-plane
                    operator: NotIn
                    values:
                    - "true"
                  - key: kubernetes.azure.com/managedby
                    operator: NotIn
                    values:
                    - aks
      path: system-components/cert-manager
      repoURL: {{ .Values.argo.url }}
      targetRevision: {{ .Values.argo.branch }}
```
