### DISCUSSION TITLE
Okta SAML Groups not propagating

### DISCUSSION THREAD

**Discussion by ImDevinC** [argoproj/argo-cd#22294] [Q&A]
I am using the following config with Okta SAML integration. I can login successfully with the `policy.default`, but when I login with a user that is part of the `gcp-sre` group, I do not have admin access. Also, if I check under User Info, there are no user groups visible.

argo version: 2.14.2+ad27246

**argocd-rbac-cm**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:readonly, applications, sync, */*, allow
    g, gcp-sre, role:admin
  scopes: '[groups]'
```

**argocd-cm**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.domain.com/
  admin.enabled: "false"
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
      - type: saml
        id: okta
        name: Okta
        config:
          ssoURL: https://domain.okta.com/app/appid/id/sso/saml
          caData: $oidc-okta:ca_data
          redirectURI: https://argocd.domain.com/api/dex/callback
          usernameAttr: email
          emailAttr: email
          groupAttr: group
```

I have also tried adding `scopes: ["groups"]` to the saml config section, which doesn't help.

I do see my groups being passed along in the dex logs, they just don't seem to get picked up in argo for some reason
```jsonl
{"time":"2025-03-10T20:48:58.562154027Z","level":"INFO","msg":"parsed and verified saml response attributes","connector":{"type":"saml","id":"okta"},"attributes":{"XMLName":{"Space":"urn:oasis:names:tc:SAML:2.0:assertion","Local":"AttributeStatement"},"Attributes":[{"XMLName":{"Space":"urn:oasis:names:tc:SAML:2.0:assertion","Local":"Attribute"},"Name":"email","NameFormat":"urn:oasis:names:tc:SAML:2.0:attrname-format:basic","FriendlyName":"","AttributeValues":[{"XMLName":{"Space":"urn:oasis:names:tc:SAML:2.0:assertion","Local":"AttributeValue"},"Value":"user@domain.com"}]},{"XMLName":{"Space":"urn:oasis:names:tc:SAML:2.0:assertion","Local":"Attribute"},"Name":"group","NameFormat":"urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified","FriendlyName":"","AttributeValues":[{"XMLName":{"Space":"urn:oasis:names:tc:SAML:2.0:assertion","Local":"AttributeValue"},"Value":"gcp-sre"},{"XMLName":{"Space":"urn:oasis:names:tc:SAML:2.0:assertion","Local":"AttributeValue"},"Value":"gcp-sre-dev"}]}]}}
{"time":"2025-03-10T20:48:58.5622455Z","level":"INFO","msg":"login successful","connector_id":"okta","username":"user@domain.com","preferred_username":"","email":"user@domain.com","groups":null,"request_id":"7b191365-9f76-4648-aead-3a838843424b"}
```
