### DISCUSSION TITLE
How to implement Applicationsets to send notifications for only changed applications instead of sending notifications for all applications in the same Gitlab repository

### DISCUSSION THREAD

**Discussion by egoisz** [argoproj/argo-cd#22310] [Q&A]
When I deploy multiple applications using Applicationsets, since my application's helm is in the same repository, when I update the configuration of a certain application, argocd will send the notifications of all applications. I want to implement how to only send the actual changed application notifications . 

My Gitlab repository directory structure
```
mcluster-appset-demo/
├── appset
│   ├── appset-test.yaml
│   ├── mcluster-appset-demo.yaml
│   └── test.yaml
├── charts
│   ├── backend
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   ├── _helpers.tpl
│   │   │   ├── deployment.yaml
│   │   │   └── service.yaml
│   │   └── values.yaml
│   ├── base
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── configmap.yaml
│   │   └── values.yaml
│   └── frontend
│       ├── Chart.yaml
│       ├── templates
│       │   ├── _helpers.tpl
│       │   ├── deployment.yaml
│       │   └── service.yaml
│       └── values.yaml
└── cluster
    ├── bak-cluster
    │   ├── backend
    │   │   ├── app-1
    │   │   │   └── values.yaml
    │   │   └── app-2
    │   │       └── values.yaml
    │   ├── base
    │   │   └── redis-config
    │   │       └── values.yaml
    │   └── frontend
    │       └── web-1
    │           └── values.yaml
    └── in-cluster
        ├── backend
        │   └── app-1
        │       └── values.yaml
        ├── base
        │   └── redis-config
        │       └── values.yaml
        └── frontend
            └── web-1
                └── values.yaml

```
Applicationsets.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mcluster-appset-demo
  namespace: argocd
spec:
  ignoreApplicationDifferences:
  - jsonPointers:
      - /spec/syncPolicy
  goTemplate: true
  generators:
  - git:
      repoURL: "http://172.30.131.253/gitops/argo-demo.git"
      revision: HEAD
      files:
      - path: "mcluster-appset-demo/cluster/in-cluster/*/values.yaml" 
      values:
        cluster_addr: https://kubernetes.default.svc
  - git:
      repoURL: "http://172.30.131.253/gitops/argo-demo.git"
      revision: HEAD
      files:
      - path: "mcluster-appset-demo/cluster/bak-cluster/*/values.yaml"  
      values:
        cluster_addr: https://172.30.87.200:6443
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.synced.dingtalk: ""
      name: "{{index .path.segments 2}}-{{index .path.segments 4}}-{{index .path.segments 3}}" 
    spec:
      project: default
      source:
        repoURL: "http://172.30.131.253/gitops/argo-demo.git"
        targetRevision: "main"
        path: "mcluster-appset-demo/charts/{{index .path.segments 3}}" 
        helm:
          valueFiles:
          - "../../../{{.path.path}}/values.yaml"
      destination:
        server: "{{.values.cluster_addr}}"
        namespace: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
```
notifications-cm.yaml
```yaml
apiVersion: v1
data:
  context: |
    argoCDServer: https://172.30.131.144
  service.webhook.dingtalk: |
    url: https://oapi.dingtalk.com/robot/send?access_token=xxx
    headers:
    - name: Content-Type
      value: application/json
  template.send-sync-status: |
    webhook:
      dingtalk:
        method: POST
        body: |
          {
            "msgtype":"markdown",
            "markdown":
              {
                "title":"ArgoCD 应用同步通知",
            "text":"### <font color=#00FF00>ArgoCD 应用同步成功通知</font>\n\n---\n\n**项目名称**: {{.app.spec.project}}\n\n**应用名称**: {{.app.metadata.name}}\n\n**同步结果**: {{.app.status.operationState.phase}}\n\n**应用状态**: {{.app.status.health.status}}\n\n**提交ID**: {{.app.status.operationState.syncResult.revision}}\n\n**触发时间**: {{ (call .time.Parse .app.status.operationState.startedAt).Local.Format "2006-01-02T15:04:05Z08:00" }}\n\n**项目URL**: [查看详情]({{.context.argoCDServer}}/applications/argocd/{{.app.metadata.name}}?view=tree&resource=&operation=true)"
              }
          }
  template.send-sync-failed: |
    webhook:
      dingtalk:
        method: POST
        body: |
          {
            "msgtype":"markdown",
            "markdown":
              {
                "title":"ArgoCD 应用同步通知",
            "text":"### <font color=#FF0000>ArgoCD 应用同步失败通知</font>\n\n---\n\n**项目名称**: {{.app.spec.project}}\n\n**应用名称**: {{.app.metadata.name}}\n\n**同步结果**: {{.app.status.operationState.phase}}\n\n**应用状态**: {{.app.status.health.status}}\n\n**提交ID**: {{.app.status.operationState.syncResult.revision}}\n\n**触发时间**: {{ (call .time.Parse .app.status.operationState.startedAt).Local.Format "2006-01-02T15:04:05Z08:00" }}\n\n**项目URL**: [查看详情]({{.context.argoCDServer}}/applications/argocd/{{.app.metadata.name}}?view=tree&resource=&operation=true)"
              }
          }
  template.send-resource-failed: |
    webhook:
      dingtalk:
        method: POST
        body: |
          {
            "msgtype":"markdown",
            "markdown":
              {
                "title":"ArgoCD 应用同步通知",
            "text":"### <font color=#FF0000>ArgoCD 应用资源更新失败通知</font>\n\n---\n\n**项目名称**: {{.app.spec.project}}\n\n**应用名称**: {{.app.metadata.name}}\n\n**同步结果**: {{.app.status.operationState.phase}}\n\n**应用状态**: {{.app.status.health.status}}\n\n**提交ID**: {{.app.status.operationState.syncResult.revision}}\n\n**触发时间**: {{ (call .time.Parse .app.status.operationState.startedAt).Local.Format "2006-01-02T15:04:05Z08:00" }}\n\n**项目URL**: [查看详情]({{.context.argoCDServer}}/applications/argocd/{{.app.metadata.name}}?view=tree&resource=&operation=true)"
              }
          }
  trigger.synced: |
    - description: Application is synced and healthy. Triggered once per commit.
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.sync.revision
      send: [send-sync-status]
    - description: Application is  synce failed.
      when: app.status.operationState.phase not in ['Succeeded', 'Running']
      oncePer: app.status.sync.revision
      send: [send-sync-failed]
    - description: Resource is update failed.
      when: app.status.operationState.phase not in ['Running'] and app.status.health.status not in ['Healthy', 'Progressing']
      oncePer: app.status.sync.revision
      send: [send-resource-failed]

kind: ConfigMap
metadata:
  name: argocd-notifications-cm
```

**Comment by egoisz** [comment]
Modifying the following configuration can achieve
```yaml
    - description: Application is synced and healthy. Triggered once per commit.
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.sync.revision
      send: [send-sync-status]
```
turn to
```yaml
    - description: Application is synced and healthy. Triggered once per commit.
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.operationState.syncResult.revision == app.status.sync.revision
      oncePer: app.status.sync.revision
      send: [send-sync-status]
```
Is there a more elegant way to implement it ？
