### DISCUSSION TITLE
elementsYaml: "{{ .key.components | toJson }}" Error with templatePatch

### DISCUSSION THREAD

**Discussion by muhali-ionos** [argoproj/argo-cd#22336] [Q&A]
Hi I am having templatePatch rendering error while using matrix generators with git and list child generators. My applicationset manifest is below:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: collabora-online
  namespace: argocd-itoah
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: argocd.base.org/cluster
              operator: In
              values:
                - col1-qa
    - matrix:
        generators:
          - git:
              repoURL: https://gitlab.itoah.server.lan/itoah/argocd.git
              revision: testing
              files:
                - path: apps-testing/list-generator/list-elementsYaml.yaml
          - list:
              elements: []
              elementsYaml: "{{ .key.components | toJson }}"
  templatePatch: |
    spec:
      sources:
        {{- range $colInstanceIndex := until (int .colInstanceCount) }}
        - repoURL: git@gitlab.git-itoah.server.lan:itoh/argocd.git
          targetRevision: testing
          path: local-charts/collabora/chart
          helm:
            releaseName: collabora-online-{{  index $.colInstances $colInstanceIndex }}
            parameters:
              - name: version
                value: "{{ $.version }}"
            valueFiles:
                - ../overrides/cluster/{{ $.name }}.yaml
                - ../overrides/values.yaml
            values: |
              ingress:
                className: nginx-{{ mod $colInstanceIndex $.ingressCount }}
                host: "{{ $.clusterType }}{{ $.clusterId }}-{{  index $.colInstances $colInstanceIndex }}.{{ $.publicDomain }}"
              collaboraPublisher:
                instance: "{{ $.clusterType }}{{ $.clusterId }}-{{  index $.colInstances $colInstanceIndex }}.{{ $.publicDomain }}"
        {{- end }}
        - repoURL: git@gitlab.itoah.server.lan:itoah/argocd.git
          targetRevision: testing
          path: kustomize/collabora
  template:
    metadata:
      name: collabora-{{ .name }}
      labels:
        product: '{{ index .metadata.labels "argocd.base.org/product" }}'
        role: '{{ index .metadata.labels "argocd.base.org/role" }}'
        stage: '{{ index .metadata.labels "argocd.base.org/stage" }}'
    spec:
      project: '{{ index .metadata.labels "argocd.base.org/project" }}'
      destination:
        server: "{{ .server }}"
        namespace: collabora-online
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
```
Now the fields from `elementsYaml` cannot be accessed and I am getting `map has no entry for key "colInstanceCount"` error.  Also attached is the screenshot. Kindly assist how can this be solved? Thanks
![Screenshot from 2025-03-13 16-59-39](https://github.com/user-attachments/assets/c78a4544-d4a5-46f9-b2f2-3f6f67382213)

**Comment by crenshaw-dev** [comment]
This looks like a possible misconfiguration:

```yaml
  generators:
    - clusters:
    - matrix:
```

The `clusters` generator is not applied to a matrix. The outputs of the `clusters` generator are instead just concatenated with the outputs of the `matrix` generator. Since the `clusters` generator doesn't produce a `colInstanceCount` parameter, the template patch templating fails.

I think maybe what you want looks more like this:

```yaml
  generators:
    - matrix:
        generators:
        - clusters:
            selector:
              matchExpressions:
                - key: argocd.base.org/cluster
                  operator: In
                  values:
                    - col1-qa
        - matrix:
            generators:
            - git:
                repoURL: https://gitlab.itoah.server.lan/itoah/argocd.git
                revision: testing
                files:
                  - path: apps-testing/list-generator/list-elementsYaml.yaml
            - list:
                elements: []
                elementsYaml: "{{ .key.components | toJson }}"
```

**Comment by muhali-ionos** [comment]
Thanks a lot for identifying the issue. The following configuration worked. I had to move the cluster generator below the git and list generators, as it is the one which would consume the parameters generated from git and the list gens. As documented in https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#restrictions , point-5 under "Restrictions". Now I have to add another cluster so that both can consume their respective parameters from `elementsYaml`. I think just mentioning the second cluster name under cluster generator would work. If not, what do you think can be applied to incorporate the settings to two or more clusters?
```yaml
generators:
    - matrix:
        generators:
        - matrix:
            generators:
            - git:
                repoURL: git@gitlab.git-itoah.server.lan:itoah/argocd.git
                revision: testing
                files:
                  - path: apps-testing/list-generator/list-elementsYaml.yaml
            - list:
                elements: []
                elementsYaml: "{{ .key.components | toJson }}"
        - clusters:
            selector:
              matchExpressions:
                - key: argocd.base.org/cluster
                  operator: In
                  values:
                    - col1-qa 
```
One thing more, do you think the field `elements: []` is required or it can be eliminated. Some articles in the internet mention that to include as well.

Thanks.
