### DISCUSSION TITLE
How is the syntax for "Render Helm charts with Kustomize"

### DISCUSSION THREAD

**Discussion by devkSerge** [argoproj/argo-cd#22352] [General]
Hello,

I am using `v2.13.0+347f221`.
I tried to setup the render Helm Chart functionality which is described here: [render Helm charts with Kustomize](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md)

But I did not get it working for my Argo `application` which locks like this:
```
spec:
  destination:
    namespace: echo
    server: https://kubernetes.default.svc
  project: app-deployment-config
  sources:
  - ref: echo_deployment_config
    repoURL: https://corp.com/echo.git
    targetRevision: master
  - chart: alm-deploy/cloud/echo/echo/echo
    helm:
      valueFiles:
      - $echo_deployment_config/echo/values.yaml
    path: echo/echo
    repoURL: helm.nexus.corp.de
    targetRevision: 1.0.1
    kustomize:
      namespace: echo
      commonLabels:
        myteam: kust-it-all    
```
It gives an error saying that I cannot combine the entry with helm and kustomize together.
Where shall I put the kustomize entry? In the docs there no mention on how to write the argo application with Helm and Kustomize combined.

Next to `$echo_deployment_config/echo/values.yaml` I put a `kustomization.yaml`, I guess that is possible?
What about the `resources: []` in `kustomization.yaml`? Because manifest rendering is handled by helm I dont have any `deployment.yamls` to put inside `resources`.

The `argocd-cm` looks like this:
```
  kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
  kustomize.buildOptions.v3.9.1: --enable_kyaml true
  kustomize.enabled: "true"
  kustomize.path.v3.9.1: /custom-tools/kustomize_3_9
  kustomize.version.v3.5.1: /custom-tools/kustomize_3_5_1
  kustomize.version.v3.5.4: /custom-tools/kustomize_3_5_4
```
Do I _need_ to provide a version in those cm settings?

Also do I need to define the kustomize version like this in application `sources`? 
``` 
kustomize:
  version: v3.9.1 
```
Is `kustomize` not bundled with `kubectl` now? What is that all about?
 
I am a little bit confused, sry for the million questions :smile: 
But it would be super awesome to have this feature working.
Thanks
