### DISCUSSION TITLE
How to fix permission denied issue , it should be 404 if application not present

### DISCUSSION THREAD

**Discussion by ajaydevtron** [argoproj/argo-cd#22366] [Q&A] [answered]
Hello Team,

We have upgraded the ArgoCD stack using a Helm chart, updating the ArgoCD image version from **v2.5.2 to v2.13.3.**
After the upgrade, I am encountering a permission denied error in the **argocd-server** pod when attempting to retrieve a Kubernetes resource (eg HPA) for an Argo application that is not present in the cluster.
In v2.5.2, the same scenario returned a 404 error instead of a permission denied error when using the Go SDK.

Does any change in the rbac? 
Please let me know if need further information .

Sharing the **argocd rbac cm** after upgrade .
```
apiVersion: v1
data:
  policy.csv: ""
  policy.default: role:admin
  policy.matchMode: glob
  scopes: "[groups]"
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: devtroncd
```
rbac cm before upgrade
```
apiVersion: v1
data:
  policy.csv: ""
  policy.default: role:admin
  scopes: "[groups]"
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: devtroncd
```
**PS** : tried to make the same config map but still getting same issue.
also i was trying to reproduce same thing with argo cli but that does not have any option to get specific resource for an argo application.

argo cli cmd i was trying
**argocd app resources argo-app-name**
