### DISCUSSION TITLE
`wait` option in declarative manifest

### DISCUSSION THREAD

**Discussion by muhali-ionos** [argoproj/argo-cd#22390] [Q&A]
Hi, 
How can I insert `wait` option in declarative manner in argocd applicationset manifest? The command-line version is below:
`argocd app wait [APPNAME.. | -l selector] [flags]` 
The `wait` has the following options:
```bash
  -N, --app-namespace string   Only wait for an application  in namespace
      --degraded               Wait for degraded
      --delete                 Wait for delete
      --health                 Wait for health
  -h, --help                   help for wait
      --hydrated               Wait for hydration operations
      --operation              Wait for pending operations
  -o, --output string          Output format. One of: json|yaml|wide|tree|tree=detailed (default "wide")
      --resource stringArray   Sync only specific resources as GROUP:KIND:NAME or !GROUP:KIND:NAME. Fields may be blank and '*' can be used. This option may be specified repeatedly
  -l, --selector string        Wait for apps by label. Supports '=', '==', '!=', in, notin, exists & not exists. Matching apps must satisfy all of the specified label constraints.
      --suspended              Wait for suspended
      --sync                   Wait for sync
      --timeout uint           Time out after this many seconds
```
My Applicationset manifest is below:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: collabora-online
  namespace: argocd-itoah
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - matrix:
            generators:
            - git:
                repoURL: git@gitlab.git-itoah.server.lan:itoah/argocd.git
                revision: testing
                files:
                  - path: apps-testing/list-generator/list-elementsYaml.yaml
            - list:
                elements: []
                elementsYaml: "{{ .key.components | toJson }}"
        - clusters:
            selector:
              matchExpressions:
                - key: argocd.base.org/cluster
                  operator: In
                  values:
                    - col1-qa 
  templatePatch: |
    spec:
      sources:
        {{- range $colInstanceIndex := until (int .colInstanceCount) }}
        - repoURL: git@gitlab.git-itoah.server.lan:itoh/argocd.git
          targetRevision: testing
          path: local-charts/collabora/chart
          helm:
            releaseName: collabora-online-{{  index $.colInstances $colInstanceIndex }}
            parameters:
              - name: version
                value: "{{ $.version }}"
            valueFiles:
                - ../overrides/cluster/{{ $.name }}.yaml
                - ../overrides/values.yaml
            values: |
              ingress:
                className: nginx-{{ mod $colInstanceIndex $.ingressCount }}
                host: "{{ $.clusterType }}{{ $.clusterId }}-{{  index $.colInstances $colInstanceIndex }}.{{ $.publicDomain }}"
              collaboraPublisher:
                instance: "{{ $.clusterType }}{{ $.clusterId }}-{{  index $.colInstances $colInstanceIndex }}.{{ $.publicDomain }}"
        {{- end }}
        - repoURL: git@gitlab.itoah.server.lan:itoah/argocd.git
          targetRevision: testing
          path: kustomize/collabora
  template:
    metadata:
      name: collabora-{{ .name }}
      labels:
        product: '{{ index .metadata.labels "argocd.base.org/product" }}'
        role: '{{ index .metadata.labels "argocd.base.org/role" }}'
        stage: '{{ index .metadata.labels "argocd.base.org/stage" }}'
    spec:
      project: '{{ index .metadata.labels "argocd.base.org/project" }}'
      destination:
        server: "{{ .server }}"
        namespace: collabora-online
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
```
I just can't figure out where and how to insert the `wait` for an application to reach a synced and healthy state before syncing another one. And have `timeout` option with 1800 seconds in my argocd manifest. So that when timeout is reached it can sync another application. Can you please help?

**Comment by ChristianCiach** [comment]
You are probably looking for Progressive Syncs: https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Progressive-Syncs/

**Reply by crenshaw-dev** [reply]
Other options: https://argo-gitops-promoter.readthedocs.io/en/latest/tool-comparison/

@muhali-ionos the problem you're trying to solve is basically the same as "environment promotion in GitOps," which is a space still early in its development. There are a lot of options, and no clear perfect solution for all use cases.

**Reply by muhali-ionos** [reply]
For below settings, its partially working:

```yaml
templatePatch: |
    spec:
      sources:
        - repoURL: git@gitlab.git-itoah.server.lan:itoah/argocd.git
          targetRevision: testing
          path: kustomize/collabora
      {{- range $colInstanceIndex := until (int .colInstanceCount) }} 
        - repoURL: git@gitlab.git-itoah.server.lan:itoah/argocd.git
          targetRevision: testing
          path: local-charts/collabora/chart
          helm:
            releaseName: collabora-online-{{  index $.colInstances $colInstanceIndex }}
            parameters:
              - name: version
                value: "{{ $.version }}"
            valueFiles:
              - ../overrides/cluster/{{ $.name }}.yaml
              - ../overrides/values.yaml
            values: |
              ingress:
                className: nginx-{{ mod $colInstanceIndex $.ingressCount }}
                host: "{{ $.clusterType }}{{ $.clusterId }}-{{  index $.colInstances $colInstanceIndex }}.{{ $.publicDomain }}"
              collaboraPublisher:
                instance: "{{ $.clusterType }}{{ $.clusterId }}-{{  index $.colInstances $colInstanceIndex }}.{{ $.publicDomain }}"
      wait:
        - sync
        - timeout: 300
      {{- end }}
```
The collabora deployment gets created during the first iteration. But tthe second iteration does not execute and so forth. It seems that `wait` works, but it entirely puts an end to the loop after the first iteration gets completed. Any idea what can be missing or adjusted? The iteration needs to be executed for 5 times in a way that after the first deployment gets completed, then the second starts, and then the subsequent ones.
