### DISCUSSION TITLE
ApplicationSet: Select cluster based on file name?

### DISCUSSION THREAD

**Discussion by andres32168** [argoproj/argo-cd#22604] [Q&A]
Hi,

I'm trying to create a application in a cluster only when there is a file with the clustername.

Imagine I've following directory structure:

```shell
└── monitoring
    └── kube-state-metrics
        ├── values.yaml
        ├── values_clustera.yaml
        └── values_clusterb.yaml
        └── values_clusterc.yaml
└── logging
    └── promtail
        ├── values.yaml
        ├── values_clustera.yaml
        └── values_clusterb.yaml
```

And now I want to have an ApplicationSet which only creates an Application with a Cluster, when the values_cluster*.yaml exists.

I try the Matrix generator

```yaml
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@ssh.dev.azure.com:v3/DMB-WSI-Platform/dNEXT/argocd-platform
              revision: matrix_deployment
              directories:
                - path: "*/*/values_*.yaml"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  stage: "{{ .path[2] }}"
```

I wonder if this would be possible? There is no error throwing but applications are not created

Thank you 
André
