### DISCUSSION TITLE
CLI login is not working - dex connection (Github sso)

### DISCUSSION THREAD

**Discussion by GregdTd** [argoproj/argo-cd#22661] [Q&A] [answered]
Hi all,

I'm able to connect to the UI successfully but I'm not using the CLI. In the UI there are actions I cannot do like enable/disable autosync using the button (however I can edit and save the manifest). I see no logs into argocd-dex-server.. In both case I receive a 403 Forbidden.

ArgoCD is setup using Helm Charts. ArgoCD version is 2.14.5. 

- RBAC config is:
```
rbac:
      policy.csv: g, org:my-groups, role:admin
      policy.default: 'role:readonly'
```

- Dex config is:

```
    cm:
      url: https://argocd.demo.com
      application.instanceLabelKey: argocd.argoproj.io/instance
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: id
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: demo
      accounts.github-actions: apiKey
```

Would someone have any hints on where I could dig in, please?
