### DISCUSSION TITLE
How to break down values file per cluster

### DISCUSSION THREAD

**Discussion by twiden** [argoproj/argo-cd#22676] [Q&A]
Hi, I have a setup with a centralized ArgoCD instance and multiple managed clusters. In the ArgoCD k8s-cluster there is an app-of-apps installed, with multiple ApplicationSets leveraging the cluster generator. I like it :)

Now I'm deploying a new ApplicationSet, that will provision a prometheus stack to all clusters. Part of the shared values.yaml looks like this:

```
opentelemetry-agent:
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: blackbox
            scrape_interval: 60s
            metrics_path: /probe
            params:
              module: 
              - http_2xx
              - tcp_connect
            static_configs:
              - targets: []
            relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]   
              target_label: target
            - target_label: __address__ 
              replacement: prometheus-blackbox-exporter:9115
          - job_name: opentelemetry-collector
            scrape_interval: 30s
            static_configs:
            - targets:
              - "${env:MY_POD_IP}:8888"
```

I would like this to be identical for all clusters, except the list of targets. The problem is that targets is contained in a list, in a map, in a list... So to not overwrite the map that contains the targets, each cluster must have a values.yaml that contains this whole block. I would like to only specify the contents of the list targets. Is that possible?

Ideally something like this for each cluster and then reference both values files so that ArgoCD/Helm can merge the contents and deploy:

```
opentelemetry-agent.config.receivers.prometheus.config.scrape_configs[0].static_configs[0].targets:
- "https://target-a.com"
- "https://target-b.com"
```
