### DISCUSSION TITLE
templatePatch of helm values, env substitution

### DISCUSSION THREAD

**Discussion by mglants** [argoproj/argo-cd#22683] [Q&A]
In templatePatch i have sources.helm valuesObject: {{ .valuesObject | toJson }}
The variable of valuesObject is 
```
valuesObject:
  ingress:
    enabled: '{{ .name }}'
```
What i end with is enabled: '{{ .name }}' is there anyway it can be converted to cluster name that it came from clusters matrix
```
valueFiles:
- $values/{{ .path.path }}/clusters/{{ .name }}/values.yaml 
```
in template patchworks just fine,

but values inside .argocd.yaml 
valuesObject:
  ingress:
    enabled: '{{ .name }}' don't get converted to cluster name.
What i want to achieve is some kind environments substitution based on cluster name for all apps, so i can manage my ingress urls based of cluster name in different Applicationset, rather than create Application for each cluster that templating of values based on cluster name

here is full source configuration
```
        - repoURL: '{{ .source.repoURL }}'
          targetRevision: '{{ dig "clusters" .name "chartRevision" .source.targetRevision . }}'
          chart: '{{ default "" .source.chart }}'
          # Default path is empty, but you can override but can be overriden with clusters.${name}.chartPath
          path: '{{ dig "clusters" .name "chartPath" (dig "source" "chartPath" "" .) . }}'
          helm:
            releaseName: '{{ .path.basename }}'
            ignoreMissingValueFiles: true
            valuesObject: {{ .valuesObject | toJson }}
            valueFiles:
              - $values/{{ .path.path }}/envs/common/values.yaml
              - $values/{{ .path.path }}/envs/{{ .metadata.labels.environment }}/values.yaml
              - $values/{{ .path.path }}/clusters/{{ .name }}/values.yaml
```
valuesObject not converting with gotemplate =(
