### DISCUSSION TITLE
Istio Service Mesh + AWS ALB ArgoCD CLI login & UI works over HTTP1 load balancer listeners, fails over HTTP2. Adding a second gRPC only service just fails with a different error

### DISCUSSION THREAD

**Discussion by chasehippen** [argoproj/argo-cd#22728] [Q&A]
Currently I run ArgoCD in insecure mode and have Istio sidecar injection enabled on my argo namespace. We have an AWS ALB, Istio ingressgateway deployment, Istio Gateway, nodeport service, and ingress in our istio-system namespace to handle traffic coming into the cluster for all our apps, and in the argo namespace we have a virtual service that takes traffic from that gateway and forwards it to our argocd clusterIP service.

Below I'll include the sanitized manifests for these resources:
Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: |
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xx-xxxx-x:xxxxxxx:certificate/xxxx-xxxx-xxxx-xxxx
    alb.ingress.kubernetes.io/group.name: istio-ingress-alb
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: "32249"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: |
      [{"HTTP": 80}, {"HTTPS": 443}]
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=240
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:xx-xxxx-x:xxxxxx:regional/webacl/web-acl-eks-ingress/xxx-xxx-xxx-xxx
    external-dns.alpha.kubernetes.io/aws-zone-type-public: "true"
    external-dns.alpha.kubernetes.io/hostname: '*.dev.ourdomain.com'
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: istio-ingress-public
    meta.helm.sh/release-namespace: istio-system
  finalizers:
  - group.ingress.k8s.aws/istio-ingress-alb
  labels:
    app: ingress
    app.kubernetes.io/managed-by: Helm
  name: istio-ingress-alb
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway-alb
            port:
              number: 443
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: eks-ingress-alb-xxxx.xx-xxxx-x.elb.amazonaws.com
```
nodeport service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    # alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 << This is the annotation we are adding to upgrade our listeners to HTTP2
    meta.helm.sh/release-name: istio-ingressgateway-alb
    meta.helm.sh/release-namespace: istio-system
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxx:certificate/xxx-xxx-xxx-xxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-2016-08
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  labels:
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingressgateway-alb
    app.kubernetes.io/version: 1.22.8
    helm.sh/chart: gateway-1.22.8
    istio: ingressgateway-alb
  name: istio-ingressgateway-alb
  namespace: istio-system
spec:
  clusterIP: xxx.xx.xx.xxx
  clusterIPs:
  - xxx.xx.xx.xxx
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: status-port
    nodePort: 32249
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 30650
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30565
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    istio: ingressgateway-alb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
Gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: istio-ingress-public
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-alb
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert-secret
      mode: SIMPLE
```
argocd virtual service:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/instance: argo-cd
  name: argocd-virtual-svc
  namespace: argo
spec:
  gateways:
  - istio-system/default-gateway
  hosts:
  - argocd.dev.ourdomain.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argo-cd-argocd-server.argo.svc.cluster.local
        port:
          number: 443
```
Argocd server service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: argo
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.14.9
    helm.sh/chart: argo-cd-7.8.22
  name: argo-cd-argocd-server
  namespace: argo
spec:
  clusterIP: xxx.xx.xx.xxx
  clusterIPs:
  - xxx.xx.xxx.xx
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

This setup as is (without the HTTP2 backend-protocol-version annotation set on the ingressgateway service) works for UI and for CLI. Worth noting that the CLI calls seem to be downgraded to HTTP1, but work nonetheless:
```
❯ argocd login argocd.dev.ourdomain.com --sso
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
Opening browser for authentication
Performing authorization_code flow login: $url-with-login-code
```

We want our ALB listeners to use HTTP2 as their backend protocol version for several reasons, primarily speed and automatic handling of gRPC for other applications. But when we put the HTTP2 annotation on the ingressgateway service, CLI calls start failing like this:
```
❯ argocd login argocd.dev.ourdomain.com --sso
FATA[0000] rpc error: code = Unknown desc = unexpected HTTP status code received from server: 464 (); malformed header: missing HTTP content-type
```
It's also worth noting that if I switch the target port to 80 on the argocd virtual service as described in the [ArgoCD ingress docs](https://argo-cd.readthedocs.io/en/latest/operator-manual/ingress/#istio), the login still fails but with a slightly different error:
```
❯ argocd login argocd.dev.ourdomain.com --sso
FATA[0001] rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "text/plain; charset=utf-8"
```
Our main gateway has the paths described by the Istio section set up the same way, but perhaps worth noting is that we only have the one gateway running in the istio-system namespace.

Under the AWS load balancer section it mentions creating a new istio ingressgateway ingress but as we only have one of those that handles all traffic coming into the cluster, I tried modifying my existing ingress by adding the grpc path, and conditional routing annotation and then creating the service suggested by the documentation with an extra virtual service to route that to the argocd service in the proper argo namespace (I run my gateway in istio-system but argo and its virtual service/service in the argo namespace):
added to gateway:
```
annotations:
  alb.ingress.kubernetes.io/conditions.argogrpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
...
      - backend:
          service:
            name: argogrpc
            port:
              number: 443
        path: /
        pathType: Prefix
...
```
new vsvc + svc
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
  labels:
    app: argogrpc
  name: argogrpc
  namespace: istio-system
spec:
  ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argogrpc-internal
  namespace: istio-system
spec:
  hosts:
    - argogrpc.istio-system.svc.cluster.local
  gateways:
    - istio-system/default-gateway
  tcp:
    - match:
        - port: 443
      route:
        - destination:
            host: argo-cd-argocd-server.argocd.svc.cluster.local
            port:
              number: 8080
```
but I now I get this error when logging in via cli:
```
❯ argocd login argocd.dev.ourdomain.com --sso
FATA[0001] rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway)
```

Kind of at a loss given our unique setup and looking for some guidance if anyone has any!
