### DISCUSSION TITLE
Prune confirm button not showing

### DISCUSSION THREAD

**Discussion by wrdls** [argoproj/argo-cd#22765] [Q&A]
I'm trying out the new `confirm` option for the `argocd.argoproj.io/sync-options: Prune=confirm` annotation introduce in ArgoCD 2.14.

However I'm not seeing the "confirm pruning" button show up in the UI as you can see in the screenrecording in the pr: https://github.com/argoproj/argo-cd/pull/20497#issue-2607443685

On the app, I have the following `syncPolicy`:

```yaml
syncPolicy:
  automated:
    prune: true
  syncOptions:
    - FailOnSharedResource=true
    - PruneLast=true
```

On the resource that is being pruned I have

```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
```

Am I doing something wrong, or is this a bug?
