### DISCUSSION TITLE
ArgoCD and helm sync is stuck in syncing

### DISCUSSION THREAD

**Discussion by klem-s** [argoproj/argo-cd#22845] [General]
Hi 
Im using helm charts to deploy on argo 
But when syncing : 
`one or more tasks are running`
And it stay suck for ever 

After some investigations he is waiting to remove my pvc,
but this pvc have a prehook : 
```
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-keys
  namespace: {{ .Values.namespace }}
  labels:
    app: generate-keys
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
```

My argoCD manifest
```
project: default
source:
  repoURL: https://github.com/xxxx/xxxx
  path: .kube/helm-chart
  targetRevision: aks
  helm:
    valueFiles:
      - ../preprod/values-preprod.yaml
    releaseName: backend
destination:
  server: https://kubernetes.default.svc
  namespace: default
```
So each time i try to remove my deployment so the pcv can be deleted and he is running all my pre-install jobs that i dont want to run because my release is already here

Do you have some ideas ? 

EDIT : 
Do i need to use : argocd.argoproj.io/hook: PreSync. instead ? 
In the doc 
helm.sh/hook: pre-install	Supported as equivalent to argocd.argoproj.io/hook: PreSync.
helm.sh/hook: pre-upgrade	Supported as equivalent to argocd.argoproj.io/hook: PreSync.

Seen to be the same equivalent
