### DISCUSSION TITLE
Merge generator is not working when come to list

### DISCUSSION THREAD

**Discussion by Bryson-Tai** [argoproj/argo-cd#22924] [Q&A]
Hi community, I am having merge generator YAML below for practice purpose. I refer to documentation for the practice.

![image](https://github.com/user-attachments/assets/2617c440-0266-4184-821c-45a6a86922d8)

### YAML Config
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-app-set-merge-generator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              values:
                carname: audi
                driver: john
          - clusters:
              selector:
                matchLabels:
                  env: nonprod
              values:
                driver: mary
          - list:
              elements:
                - name: 'in-cluster'
                  values:
                    carname: toyota
                    driver: kevin
```

### Actual Output
![image](https://github.com/user-attachments/assets/593f52bc-c59f-4f0a-8d25-c0e1f0d23dee)

### Expected Output
2 apps name with:
- `kevin-toyota-nginx-app@in-cluster`
- `mary-audi-nginx-app@bryson-cluster-2`

May I know anyone met this issue too? I tried to use 3 lists in `generators:merge`  is not having this issue as well.
