### DISCUSSION TITLE
Why is my applicationset kustomize patch getting ignored?

### DISCUSSION THREAD

**Discussion by nevotheless** [argoproj/argo-cd#22934] [Q&A] [answered]
Hellau, i'm currently trying to build a little pullRequest generator based system which uses a kustomize deployment. Everything works as intended but when it comes to customize the kustomize deployment via the applicationset resource, things don't quite work out as expected.

I'm following the docs are seen here for example https://argo-cd.readthedocs.io/en/release-2.14/user-guide/kustomize/#patches 

(Currently using argocd 2.14) 

I want to apply this truncated patch here

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  template:
    spec:
      source:
        kustomize:
          patches:
            - target:
                kind: Deployment
                labelSelector: app=some-app
              patch: |-
                - op: add
                  path: /spec/template/spec/imagePullSecrets
                  value:
                    - name: some-registry-pull-secret
```

When i'm trying to use this kustomize patch it's just getting ignored for some reason. When i check the resources in the cluster the kustomize section only has `commonLabels` which i put there as well. 

Any idea why my patches are not getting applied to the manifest?
