### DISCUSSION TITLE
How to add an external K8s cluster to ArgoCD during installation

### DISCUSSION THREAD

**Discussion by sahil-sharma** [argoproj/argo-cd#22933] [Q&A] [answered]
Hello everyone,

My set-up:
```
ArgoCD Cluster-A (2-nodes, v1.32, Ubuntu 24.04, running in Vagrant)
App Cluster-B (3- nodes, v1.32, Ubuntu 24.04, running in Vagrant)
```
I am trying to set-up ArgoCD in Cluster-A. via official Helm Chart. Now I want to add another K8s cluster (say Cluster-B).
I create SA, CLuterRoleBinding, Secret in Cluster-B and got the Server address, Token, caData.
I am bit confused on this. Can I define it in my `values.yaml` (for ArgoCD) while installing it? Like here:
```
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L599
```
I tried this but it did not work. My values.yaml looks like this:
```
.......
configs:
  clusterCredentials:
    app-cluster:
      server: https://mycluster.example.com
      config:
        bearerToken: "<authentication token>"
        tlsClientConfig:
          insecure: false
          caData: "<base64 encoded certificate>"
.......
```
But when I manually create a secret like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: app-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "app-cluster"
  server: https://<server-IP>:6443
  config: |
    {
      "bearerToken": "TOKEN value in plain-text",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<CA DATA VALUE IN base64 encoded format"
      }
    }
```
Then I reload ArgoCD and I can see the cluster:
![image](https://github.com/user-attachments/assets/fbe6d326-dc48-417c-adea-9ccaaa6eae04)

Can someone guide me on how to add a cluster during installation? Assuming Cluster-B is already available. I can push my cluster credentials to AWS SM for safety. But for simplicity I am just writing them to `values.yaml` file (not pushing to GH).
I did not find any examples on how to add it except this:
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters

Many thanks in advance!
