### DISCUSSION TITLE
Kustomize base from remote private repository (https)

### DISCUSSION THREAD

**Discussion by jdelucaa** [argoproj/argo-cd#22978] [Q&A]
ArgoCD v2.14.10

I have an Argo CD application that points to `repo A` using HTTPS:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
  namespace: dev
spec:
  project: dev-project
  source:
    repoURL: https://github.com/myorg/repoA
    path: cluster
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
```

And I got a secret with credential template using GitHub app credentials, and secret for `repoA`, like:

credential template secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  githubAppID: xxx
  githubAppInstallationID: yyy
  githubAppPrivateKey: key
  type: git
  url: https://github.com/myorg
type: Opaque
```

repository secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: repoA
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/myorg/repoA
type: Opaque
```

This works fine. I can sync to `repoA` successfully. But as soon as my Kustomize configuration in `repoA` includes a base from another private repository (let's call it `repoB` - that uses the same credentials as `repoA`), like:

repository secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: repoB
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/myorg/repoB
type: Opaque
```

`kustomization.yaml` in `repo A`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/myorg/repoB//kustomize/?ref=v2.0
```

I get the following error when I sync my application:

```
accumulating resources: accumulation err='accumulating resources from 'https://github.com/myorg/repoB//kustomize/?ref=v2.0': URL is a git repository': failed to run '/usr/bin/git fetch --depth=1 https://github.com/myorg/repoB v2.0': fatal: could not read Username for 'https://github.com': No such device or address : exit status 128
```

From the error I am getting it seems like `Kustomize` is not using the repository credentials I provided to Argo CD.

I've been trying to make this work for a while now, searched everywhere, I even tried `ssh` but got a lot of other different errors, Is this supposed to work or am I trying something that is not supposed to be supported? From the docs, issues and discussions I saw it seems that it should work. https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#private-remote-bases

Any help? Thanks.
