### DISCUSSION TITLE
Having trouble getting ApplicationSet to turn on auto sync

### DISCUSSION THREAD

**Discussion by jwilkicki** [argoproj/argo-cd#23019] [Q&A]
Hi all!

I've gone through this a few times and I'm having trouble getting the ApplicationSet to turn on automated sync.  I can get it to generate syncOptions but not the automated policy.  Here's a trimmed down snippet of my ApplicationSet

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mcp
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mcp-0.1.0
  annotations:
    meta.helm.sh/release-name: release-name
    meta.helm.sh/release-namespace: default
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - name: calico
            namespace: tigera-operator
            repoURL: https://docs.projectcalico.org/charts            
            chart: tigera-operator
            path: 
            targetRevision: "v3.29.0"
            syncgroup: level-1
            wave: "1"
            project: admin
            server: https://kubernetes.default.svc
            valuesObject: ""
            ignoreDifferences: []
            syncPolicy:                
              automated:
                prune: true
                selfHeal: true         
              syncOptions: 
              - CreateNamespace=true
              - ServerSideApply=true
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  template:
    metadata:
      name: '{{.name}}'
      labels:
        sync-group: '{{.syncgroup}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
        argocd.argoproj.io/manifest-generate-paths: .;..
    spec:      
      project: '{{.project}}'
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'      
      sources:
        - repoURL: '{{.repoURL}}'
          chart: '{{ dig "chart" "" . }}'
          path: '{{ dig "path" "" . }}'
          targetRevision: '{{.targetRevision}}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - $defaults/values/{{.name}}/values-{{.name}}.yaml
              - $defaults/values/{{.name}}/values-{{.name}}-nonprod.yaml
              - $values/globals.yaml
              - $values/overrides/{{.name}}/values.yaml
            values: "{{.valuesObject}}"
        - repoURL: https://github.example.com/development/base
          targetRevision: main
          ref: defaults
        - repoURL: https://github.example.com/development/overrides
          targetRevision: main
          ref: values 
  templatePatch: |
    spec:
      syncPolicy: 
        {{- with .syncPolicy }}
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          {{- range $option := .syncOptions }}
          - {{ $option }}
          {{- end }}
        {{- end }}
      ignoreDifferences: {{ .ignoreDifferences | toYaml | nindent 4 }}
```
My Application ends up looking like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;..
    argocd.argoproj.io/sync-wave: "1"
  labels:
    sync-group: level-1
  name: calico
  namespace: argocd
spec:
  destination:
    namespace: tigera-operator
    server: https://kubernetes.default.svc
  project: admin
  sources:
  - chart: tigera-operator
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
      - $defaults/values/calico/values-calico.yaml
      - $defaults/values/calico/values-calico-nonprod.yaml
      - $values/globals.yaml
      - $values/overrides/calico/values.yaml
    repoURL: https://docs.projectcalico.org/charts
    targetRevision: v3.29.0
  - ref: defaults
    repoURL: https://github.example.com/development/base
    targetRevision: dry_app_set
  - ref: values
    repoURL: https://github.example.com/development/overrides
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
```
I've gone through several iterations of sync options including a version of the patch like this:

```yaml
templatePatch: |
    spec:
      syncPolicy: {{ .syncPolicy | toYaml | nindent 4 }}
      ignoreDifferences: {{ .ignoreDifferences | toYaml | nindent 4 }}
```

I also tried to make it look [as close to the example in the docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#template-patch) as possible and I'm still not getting it.  Anyone have a suggestion?

Nothing I do seems to get the automated block to show up in the syncPolicy.   I'm using Argo CD v3.0.1 installed with Argo CD Helm chart 8.0.3

**Comment by mergwyn** [comment]
@jwilkicki I'm having exactly the same issue - did you ever manage to get this working?

**Reply by jwilkicki** [reply]
No, I gave up and used an App of App pattern instead.

**Comment by mergwyn** [comment]
Interestingly, I've just been doing more experimentation:

This manifest works
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-gitops
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/mergwyn/cluster-gitops.git
        revision: main
        directories:
          - path: bootstrap/*/*
          - path: core/*/*
          - path: apps/*/*

  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mergwyn/cluster-gitops.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 1 }}'

      syncPolicy:
        automated:
          enabled: true
          allowEmpty: true
          prune: true
          selfHeal: false
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - RespectIgnoreDifferences=true

      ignoreDifferences:
        - kind: StatefulSet
          group: '*'
          name: mail
          jsonPointers:
            - /spec/volumeClaimTemplates
            - /spec/template/metadata/annotations
        - kind: GpuDevicePlugin
          group: '*'
          name: gpudeviceplugin
          jsonPointers:
            - /spec/resourceManager
            - /spec/tolerations
            - /metadata/annotations
        - kind: ClusterPolicy
          group: '*'
          jsonPointers:
            - /spec/rules/0/skipBackgroundRequests
        - group: '*'
          kind: Deployment
          jqPathExpressions:
            - .spec.template.spec.hostUsers
        - group: '*'
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.dataFrom[].extract.conversionStrategy
            - .spec.dataFrom[].extract.decodingStrategy
            - .spec.dataFrom[].extract.metadataPolicy
```
whereas this one does not result in `syncPolicy.automatied` appearing in the Application: 
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-gitops
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: &repo https://github.com/mergwyn/cluster-gitops.git
        revision: main
        directories:
          - path: bootstrap/*/*
        values:
          env: wave1
    - git:
        repoURL: *repo
        revision: main
        directories:
          - path: core/*/*
        values:
          env: wave2
    - git:
        repoURL: *repo
        revision: main
        directories:
          - path: apps/*/*
        values:
          env: wave3

  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - wave1
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - wave2
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - wave3

  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        order: '{{ .values.env }}'
    spec:
      project: default
      source:
        repoURL: *repo
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 1 }}'

      syncPolicy:
        automated:
          enabled: true
          allowEmpty: true
          prune: true
          selfHeal: false
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - RespectIgnoreDifferences=true

      ignoreDifferences:
        - kind: StatefulSet
          group: '*'
          name: mail
          jsonPointers:
            - /spec/volumeClaimTemplates
            - /spec/template/metadata/annotations
        - kind: GpuDevicePlugin
          group: '*'
          name: gpudeviceplugin
          jsonPointers:
            - /spec/resourceManager
            - /spec/tolerations
            - /metadata/annotations
        - kind: ClusterPolicy
          group: '*'
          jsonPointers:
            - /spec/rules/0/skipBackgroundRequests
        - group: '*'
          kind: Deployment
          jqPathExpressions:
            - .spec.template.spec.hostUsers
        - group: '*'
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.dataFrom[].extract.conversionStrategy
            - .spec.dataFrom[].extract.decodingStrategy
            - .spec.dataFrom[].extract.metadataPolicy
```
