### DISCUSSION TITLE
ignoreDifferences jqPathExpressions targeting resource labels with a key name wildcard

### DISCUSSION THREAD

**Discussion by dhorner71** [argoproj/argo-cd#23228] [Q&A]
gearing up for 3.0 and testing new breaking changes from 2.14.  Currently testing on 3.0.5.

trying to make these changes as a result of: https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.14-3.0/#use-annotation-based-tracking-by-default .  reverting to `label` or `annotation+label` indeed ignores these labels but we are trying to convert respectively.

we have resource labels that we'd like to ignore differences but contain non-constant key names.  it would be impossible for us to explicitly know all key names upfront. We will know what they always end with.

example namespace resource:
```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
  labels:
    app: nginx
    keyAAA: testAAA
    keyBBB: testBBB
    hnc.x-k8s.io/included-namespace: 'true'
    nginx-test.tree.hnc.x-k8s.io/depth: '0'
    ns2.tree.hnc.x-k8s.io/depth: '1'
    ns3.tree.hnc.x-k8s.io/depth: '2'
    keyCCC: testCCC
```
with argocd-cm config map entry:
```
  resource.customizations.ignoreDifferences.Namespace: |
    jqPathExpressions:
      # Ignore hnc labels
      - '.metadata.labels."hnc.x-k8s.io/included-namespace"'
      - 'getpath(paths | select(.[-1] | endswith(".tree.hnc.x-k8s.io/depth")))'
```

first jqPathExpression works as expected as a literal but the attempt to handle "wildcard" scenario doesn't ignore differences as expected.

jq playground*:
https://www.devtoolsdaily.com/jq_playground/#v2=N4IglgdgDgrgLgFQKYA84gFwmAHQgAnxxAEMowA1JAJwGcwB7CYjIkANwEZiAaPQ4gGtIAExZsAciQC2SWlBIBjJL35tZcEiJKbxuAoTYQZKzEYDmkFAFo4cuKoMCQAGxIAjJC9p61htmRQ4sQQlhAojv7OgkgAngCCicEgdrRwifGRUUJxAEL5yalw+blZ-sQAFhCKAHQ2ggActDWMAPSQii4wIkgi1say8kqmrMRw1DCmfE6GIWE2RTXjSEg1VbX1TS0MrT1QcBXJAAxlsyAQtABMS9Qra9V11o3NbXsHydwg01FGtADMNzu60ez22uyQ+0OZmIl1O0TiAGEkYV7EiEcQ-PgAL5qHEQLFfEAAMzALjs1AAoigoNRMCBzEg4AoDgAKZkVWj4AA++FoXiQijgLJqAG1rJwALrc-BICAiWgAdzArOIgNWwM2Lx2byhAEp9SAsUA

*working jq path expression in playgroud but not working in argocd-cm config map

any ideas on what we are doing incorrectly to ignore label key names matching with a "wildcard" using jqPathExpressions?

thanks for any advice!

this looks to be related to: https://github.com/argoproj/argo-cd/discussions/21185
