### DISCUSSION TITLE
too many ssh connections lead to gitlab server hang

### DISCUSSION THREAD

**Discussion by ivan-cai** [argoproj/argo-cd#23339] [Q&A]
I have more than 3,500 applications that use ssh to connect to private gitlab repositories. Sometimes the gitlab server hang due to too many ssh connections from argocd. How can I reduce the number of concurrent git fetches?

my configmap:

- argocd-cm
```yaml
  timeout.reconciliation: 300m
  timeout.reconciliation.jitter: 5m
```
- argocd-cmd-params-cm
```yaml
  applicationsetcontroller.enable.progressive.syncs: "true"
  applicationsetcontroller.webhook.parallelism.limit: "50"
  controller.cluster.cache.list.page.buffersize: "50"
  controller.operation.processors: "100"
  controller.repo.server.timeout.seconds: "120"
  controller.status.processors: "300"
  reposerver.git.attempts.count: "5"
  reposerver.parallelism.limit: "1"
  server.grpc.max.size.mb: "200"
  server.k8sclient.retry.base.backoff: "200"
  server.k8sclient.retry.max: "12"
  server.webhook.parallelism.limit: "50"
```
