### DISCUSSION TITLE
Wrap annotations in conditionals when using Cluster Generator

### DISCUSSION THREAD

**Discussion by simao-silva** [argoproj/argo-cd#23377] [General]
I am trying to set the following ApplicationSet:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    (...)
  name: 'test-{{ .Release.Name }}'

spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: {{ .Release.Name | quote }}
  template:
    metadata:
      name: 'test-{{ .Release.Name }}-{{`{{metadata.annotations.name}}`}}'
      namespace: argocd
      labels:
        (...))
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/example
        targetRevision: HEAD
        path: test
        helm:
          values: |
            {{- if (index `{{metadata.annotations.postgres_db}}`) }}
            postgres_db: {{`{{metadata.annotations.postgres_db}}` | quote }}
            {{- end }}
            (...)
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd

      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions: # Sync options which modifies sync behavior
          - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
          - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
          - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
        # The retry feature is available since v1.7
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
```
However, I am not being able to wrap annotations that are stored in the secret corresponding to the cluster. I have also tried the following without luck:
```yaml
{{- if hasKey metadata.annotations "postgres_db" }}
postgres_db: {{`{{metadata.annotations.postgres_db}}` | quote }}
{{- end }}
````

My question is if it is possible to do this and, if so, what I am doing incorrectly?
