### DISCUSSION TITLE
ignoreDifferences for syncPolicy

### DISCUSSION THREAD

**Discussion by GurayCetin** [argoproj/argo-cd#23475] [Q&A]
We're observing an inconsistent behavior where manually disabled auto-sync in the ArgoCD UI automatically re-enables itself after an unpredictable period. This occurs despite:

Explicitly clicking `Disable Auto-Sync` (which changes the button to `Enable Auto-Sync`)

Attempting to use ignoreDifferences to prevent syncPolicy modifications, but it's not effective to ignore it. 

Application config; 
```
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
```

ignoreDifference on application
```
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /spec/syncPolicy
    kind: Application
```

full config
```
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /spec/syncPolicy
    kind: Application
  project: development
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
```

ArgoCD version: v3.0.6+db93798
