### DISCUSSION TITLE
With Application Set + App of App Patterns vs App of App patterns, how do I programmatically disable an already existing deployement?

### DISCUSSION THREAD

**Discussion by naaly17** [argoproj/argo-cd#23490] [Q&A]
I have a chart set up where enabled/disabled determine if an app gets deployed, using an ansible inventory to list the desired apps. This works on first pass, however how do I disable an app without kubectl delete deployment (or kubectl delete the entire applicationSet and recreate with new overrides), there's got to be a way to do this...
Any suggestions would be appreciated!
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mars-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git: #Environment Configuration
        repoURL: https://github.companyName.com/spartans/artemis-cluster-config.git
        revision: ART-TEST
        files:
          - path: app-values/**/*.yam
  template:
    metadata:
      name: '{{.cluster.name}}-apps-{{ default "default" .cluster.namespace}}'
    spec:
      # The project the application belongs to.
      project: "default"
      # Source of the application manifests
      sources:
        - repoURL: https://github.companyName.com/spartans/artemis-argocd-apps.git
          targetRevision: ART-TEST
          path: artemis-apps
          helm:
            valueFiles:
              - $values/artemis-apps/artemis-gccsj-values.yaml
              - $values/artemis-apps/artemis-apps-chart-override-mars-values.yaml
              - $values/artemis-apps/minimum-resource-values.yaml
            values: '{{.app.values}}'
        - repoURL: https://github.companyName.com/spartans/artemis-argocd-apps.git
          targetRevision: ART-TEST
          ref: values
      destination:
        server: '{{.cluster.address}}'
        # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
        namespace: '{{.cluster.namespace}}'
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true
          selfHeal: false
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
```
