### DISCUSSION TITLE
[Solved] Argo CD v3.0.5 failed to pull Karpenter v1.5.0 from OCI – Fixed by adding repository Secret and repoURL correctly

### DISCUSSION THREAD

**Discussion by paulofponciano** [argoproj/argo-cd#23511] [General]
Hi everyone,
Is anyone using Argo (v3.0.5) to deploy Karpenter version 1.5.0 (or any other v1.x) and managed to get the Application configuration right?
I'm facing the following error where Argo tries to fetch the index from the OCI repository:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = error fetching chart: failed to fetch chart: failed to get command args to log: `helm pull --destination /tmp/2f4a1b68-23f8-4d0e-9208-0da04dba2531 --version 1.5.0 --repo oci://public.ecr.aws/karpenter/karpenter karpenter` failed exit status 1: Error: looks like "oci://public.ecr.aws/karpenter/karpenter" is not a valid chart repository or cannot be reached: public.ecr.aws/karpenter/karpenter/index.yaml@: not found
```

Here is my manifest:

```
apiVersion: v1
kind: Secret
metadata:
  name: karpenter-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  type: helm
  url: public.ecr.aws/karpenter/karpenter
  project: cluster-tools
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: cluster-tools
  source:
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    chart: karpenter
    targetRevision: "1.5.0"
    helm:
      values: |
        replicas: 1
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/role-platform-sre-tools-prod-karpenter
        settings:
          clusterName: platform-sre-tools
          clusterEndpoint: https://ID.gr7.REGION.eks.amazonaws.com
          aws:
            defaultInstanceProfile: platform-sre-tools-karpenter-profile
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
```

Repository:
![Screenshot 2025-06-21 at 4 36 06 PM](https://github.com/user-attachments/assets/c8a017a0-2840-455e-9334-9f562a41325c)

Application:
![Screenshot 2025-06-21 at 4 36 28 PM](https://github.com/user-attachments/assets/94d27f42-e86a-476b-b14b-c6e54edd8b95)

Has anyone faced this issue or knows how to properly configure ArgoCD to deploy Karpenter from the OCI Helm repository? 
Any help would be appreciated!

**Comment by paulofponciano** [comment]
Fixed by adding repository Secret and repoURL correctly:

**Repository Secret:**

```
apiVersion: v1
kind: Secret
metadata:
  name: karpenter-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  type: helm
  url: public.ecr.aws
  project: cluster-tools
```

**Application:**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: cluster-tools
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: "1.5.0"
    helm:
      values: |
        replicas: 1
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:ACCOUNT_ID:role/role-platform-sre-tools-prod-karpenter
        settings:
          clusterName: platform-sre-tools
          clusterEndpoint: https://ID.gr7.REGION.eks.amazonaws.com
          aws:
            defaultInstanceProfile: platform-sre-tools-karpenter-profile
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
```

In my case, I also added the following to the **AppProject (cluster-tools)**:

```
sourceRepos:
  - 'public.ecr.aws/karpenter'
```
