### DISCUSSION TITLE
Field preserveResourcesOnDeletion not allowed in AppSet and fails to be added

### DISCUSSION THREAD

**Discussion by kutsyk** [argoproj/argo-cd#23557] [Q&A]
Hi everyone,

Trying to set up safeguard for our AppSets and resources with preventing their deletion with flag `preserveResourcesOnDeletion`.

Official doc for this field: https://argo-cd.readthedocs.io/en/release-2.10/operator-manual/applicationset/Controlling-Resource-Modification/#prevent-an-applications-child-resources-from-being-deleted-when-the-parent-application-is-deleted

We have ArgoCD version `2.10.16` and our `AppSet` CRD definition manifest contains required fields:
```
              syncPolicy:
                properties:
                  applicationsSync:
                    enum:
                    - create-only
                    - create-update
                    - create-delete
                    - sync
                    type: string
                  preserveResourcesOnDeletion:
                    type: boolean
```

When I add this field to AppSet it fails with next error:
```
unknown field "spec.template.spec.syncPolicy.preserveResourcesOnDeletion"
```

I've researched bunch of things and options and even suspected that this is immutable field so deleted AppSet and tried recreating if from scratch, still same issue:
```
(⎈|argocd/argocd) ➜   kubectl apply -f ./apps/kubernetes-dashboard/kubernetes-dashboard.yaml
Error from server (BadRequest): error when creating "./apps/kubernetes-dashboard/kubernetes-dashboard.yaml": ApplicationSet in version "v1alpha1" cannot be handled as a ApplicationSet: strict decoding error: unknown field "spec.template.spec.syncPolicy.preserveResourcesOnDeletion"
````

We are also using Go templates with our `AppSets` but from what I've seen it should not affect this at all.

What am I missing or doing wrong that this fails for me?

**Comment by kutsyk** [comment]
Ok, 
I've figured out that adding this option on higher level doesn't fail:
```
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
```

Although I'm not quite sure if this is correct way
