### DISCUSSION TITLE
ALB Ingress

### DISCUSSION THREAD

**Discussion by vitarkah** [argoproj/argo-cd#5132] [Q&A]
Straightforward copy paste from documentation; Service & Ingress; running into the following error; 
```
{"level":"error","ts":1609117980.44108,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"argocd","namespace":"argocd","error":"InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateTargetGroupInput.Port.\n"}
```
Unable to figure out what might be causing.
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: argogrpc
  name: argogrpc
  namespace: argocd
spec:
  ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    # Use this annotation (which must match a service name) to route traffic to HTTP2 backends. 
    alb.ingress.kubernetes.io/conditions.argogrpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  name: argocd
  namespace: argocd
spec:
  rules:
  - host: argocd.<domain>
    http:
      paths:
      - backend:
          serviceName: argogrpc
          servicePort: 443
        pathType: ImplementationSpecific
      - backend:
          serviceName: argocd-server
          servicePort: 443
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - argocd.<domain>
   ```
