### DISCUSSION TITLE
Execution of configuration automation following a sync?

### DISCUSSION THREAD

**Discussion by snooyen** [argoproj/argo-cd#5140] [Q&A]
Hey All,

My team is responsible for many K8s clusters across various cloud platforms & I am looking at ArgoCD to help us keep them all in sync.

A handful of our application deployments require us to apply configurations to the applications via their respective APIs (e.g. setting up RBAC/SSO, importing resources, etc..) that are currently automated via Ansible.  

My question is --once a sync has been completed & application has been deployed to a set of clusters, what's the best way to then kickoff configuration tasks?  Would that be a post-sync resource hook? https://argoproj.github.io/argo-cd/user-guide/resource_hooks/

**Comment by sbose78** [comment]
> My question is --once a sync has been completed & application has been deployed to a set of clusters

You would be able to do use a PostSync after the `Application` on a specific cluster  is sync'd and ready. Note, there's no way to have this scheduled to run after **all** clusters have sync'd. 

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PostSync
```
