### DISCUSSION TITLE
ArgoCD app-of-apps pattern with dependencies to 3rd party helm charts

### DISCUSSION THREAD

**Discussion by awuetz** [argoproj/argo-cd#5316] [Q&A]
Hello all,

i'm despirately triing to get my setup with the app-of-apps pattern working, but i'm hanging at a point where a helm dependency needs to be used.

My structure of the apps looks like this:
```
root app --> 1st app --> dependency to etcd
         --> 2nd app
```
In my "root app" I've declared the templates for 1st and 2nd app, like shown in the ArgoCD examples (https://github.com/argoproj/argocd-example-apps/tree/master/apps)  

And in my "1st app" `Chart.yaml` i've got something like:
```yaml
type: application
name: my-etcd
[...]
dependencies:
  - name: etcd
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    alias: etcd
```
Within ArgoCD the root app and the 1st and 2nd app are shown, but the dependency is missing. 
If i only add my 1st app to ArgoCD, without the app-of-apps pattern, then i see that the dependend resources from etcd are created..

Does anyone have this kind of setup working? Or any hints how to get this working?

Kind regards,
Alex
