### DISCUSSION TITLE
kernel capabilities

### DISCUSSION THREAD

**Discussion by abjinugu** [argoproj/argo-cd#5356] [General]
When I create an application from the UI, the deployment always fails with the below message. Am I missing anything here?

_**deployments.apps "account-deployment" is forbidden: user "system:serviceaccount:argocd:argocd-application-controller" is not an admin and does not have permissions to use extra kernel capabilities for resource account-deployment**_

**Comment by wtam2018** [comment]
Please check to make sure that the argocd:argocd-application-controller service account has permission to deploy in the target namespace.

**Reply by abjinugu** [reply]
Can you please give me more info on how to do that? The deployment succeeds when I **don't** provide SYS_PTRACE in security context of the pod.
Here what I tried to fix it (unsuccessfully)

Created a pod security policy:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
```

And mapped that to policy to argocd-application-controller cluster role.
