### DISCUSSION TITLE
ignoreDifferences with DeploymentConfig

### DISCUSSION THREAD

**Discussion by wouter2397** [argoproj/argo-cd#5518] [Q&A] [answered]
Hello ArgoCD community,

One of our internal clients is syncing a DeploymentConfig, which is a specific OpenShift manifest.
When applying this ArgoCD starts spamming new replication controllers as the image digest keeps changing to the configured one in GIT.

So I tried to ignore the diff in the container image, but it looks like ArgoCD cannot work with the DeploymentConfig.
Does anyone of you have the same problems?

I'm applying the following code to the AppProject:
```
ignoreDifferences:
  - group: apps.openshift.io/v1
    kind: DeploymentConfig
    jsonPointers:
      - /spec/template/spec/containers/0/image
```

**Comment by jannfis** [comment, marked as answer]
Hi @wouter2397, I think there's a happy little mistake in that configuration, in that the `group` should be configured without the version specifier. The correct configuration that should work would be:

```yaml
ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
      - /spec/template/spec/containers/0/image
```
