### DISCUSSION TITLE
SSO setup with Github doesn't work with RBAC

### DISCUSSION THREAD

**Discussion by ishallbethat** [argoproj/argo-cd#5550] [Q&A]
Hi 
Is it a bug ? or something i missed ? 
I followed the link https://argoproj.github.io/argo-cd/operator-manual/rbac/ to set up rbac but turns out people within team-sre still don't have proper access. 
I placed sensitive information with xxx_

my argo-cm.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://cd.xxx_org.org
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: xxx_clientid
          clientSecret:xxx_clientsecret
          orgs:
          - name: xxx_org
  admin.enabled: "true"
```
my rbac
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, projects, *, *, allow
    g, xxx_org:team-sre, role:org-admin
```
My goal is to allow people within Github team "team-sre" to be admin. 
And the argocd page gives me error like below picture.
![image](https://user-images.githubusercontent.com/11718739/107178014-310db380-6a0e-11eb-8290-72a6a9b25a20.png)

**Comment by rbreeze** [comment]
Could you try setting `loadAllGroups: true` in the Github connector config section of your `dex.config`?

**Comment by ishallbethat** [comment]
I added and tried again "loadAllGroups: true". Still this doesn't work @rbreeze

**Comment by rbreeze** [comment]
Thanks for checking! I had a similar issue when setting up SSO on a personal cluster a few months ago and I seemed to remember that helping, so it's a bummer it didn't work for you... what version are you running?

**Comment by ishallbethat** [comment]
```
{
    "Version": "v1.8.3+0f9c684",
    "BuildDate": "2021-01-21T22:20:39Z",
    "GitCommit": "0f9c68427882bf4633d395cbfcd7c9271795fd9b",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```
my versions @rbreeze .  argocd version "v1.8.3+0f9c684"

**Reply by AnshumanTripathi** [reply]
I am seeing a similar issue when using Github Enterprise SSO.

Here is my ArgoCD version

```json
{
    "Version": "v2.3.3+07ac038",
    "BuildDate": "2022-03-30T00:06:18Z",
    "GitCommit": "07ac038a8f97a93b401e824550f0505400a8c84e",
    "GitTreeState": "clean",
    "GoVersion": "go1.17.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.0+gd141386",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```
my RBAC config

```yaml
rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      p, role:org-admin, applications, create, */*, allow
      p, role:org-admin, applications, update, */*, allow
      p, role:org-admin, applications, delete, */*, allow
      p, role:org-admin, applications, sync, */*, allow
      p, role:org-admin, applications, override, */*, allow
      p, role:org-admin, applications, action/*, */*, allow
      p, role:org-admin, certificates, create, *, allow
      p, role:org-admin, certificates, update, *, allow
      p, role:org-admin, certificates, delete, *, allow
      p, role:org-admin, clusters, create, *, allow
      p, role:org-admin, clusters, update, *, allow
      p, role:org-admin, clusters, delete, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow
      p, role:org-admin, projects, create, *, allow
      p, role:org-admin, projects, update, *, allow
      p, role:org-admin, projects, delete, *, allow
      p, role:org-admin, accounts, update, *, allow
      p, role:org-admin, gpgkeys, create, *, allow
      p, role:org-admin, gpgkeys, delete, *, allow
      g, xxx:ops, role:org-admin
      g, test, role:org-admin
```
Here I created a local account `test` with the same role `org-admin`, which has all the required permissions but a member of `xxx:ops`  does not have similar permissions.

**Comment by SwordreamLj** [comment]
I also have this problem. the github users of the  xxx_org:argocd-admin team have only the read permmison
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
      g, xxx_org:argocd-admin, role:admin
```
