### DISCUSSION TITLE
Pin version of Kustomize along with a plugin?

### DISCUSSION THREAD

**Discussion by vikas027** [argoproj/argo-cd#5572] [Q&A] [answered]
Hello guys,

How can I pin down the version of Kustomize?

I have used this yaml following the official [guide](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#custom-kustomize-versions) but it throws an error `multiple application sources defined: Kustomize,Plugin`

It looks like either **plugin** or **kustomize** can be used, not both. Am I right?

```yaml
  source:
    path: kustomized_helm/overlays/prod
    repoURL: <my_repo>
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
    # Error rpc error: code = Unknown desc = multiple application sources defined: Kustomize,Plugin
    # kustomize:
    #   version: v4.0.1
```

Thanks!
