### DISCUSSION TITLE
Exclude a particular Kubernetes resource

### DISCUSSION THREAD

**Discussion by vikas027** [argoproj/argo-cd#5586] [Q&A]
I have deployed a Kubernetes manifest in which `ValidatingWebhookConfiguration` keeps on flapping. Is there a way to annotate this resource and ArgoCD ignores it?

![2021-02-24_07-46-31 (1)](https://user-images.githubusercontent.com/6998650/108906407-f7c37d80-7674-11eb-8272-80da346d1f0e.gif)

I have tried this annotation in vain.

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: hnc-validating-webhook-configuration
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
```

Did anyone get this working?

**Comment by jannfis** [comment]
Hi @vikas027, I would guess you have autosync with self-heal turned on. The admission registration controller is known to inject a CA bundle in the webhook resources, and Argo CD's self-heal mechanism fights with the admission registration controller over the correct state. Chance is high that this might be what you observe here. 

I think the following pattern will help you: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#system-level-configuration (just replace `MutatingWebhookConfiguration` with `ValidatingWebhookConfiguration`)

**Reply by vikas027** [reply]
Thanks, @jannfis . This will ignore all the resources cluster-wide. How can I do the same for a particular resource (by specifying the name)?

**Reply by Elyytscha** [reply]
also if you do this in case of a vault service like hashicorp vault, you will be not able to change the reference in the secret where the secret is located in hashicorp.

that means,
if you ignore this secret completely
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: 'https://vault-int.clustername.domain.com'
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/vault-role: ocp-int
    vault.security.banzaicloud.io/vault-skip-verify: 'true'
  labels:
    app.kubernetes.io/instance: awx-int
  name: awx-admin-password
stringData:
  password: vault:devops/data/int/awx#admin_password
```
it will be not possible to change the secret reference and get a sync which reflects this:
```
...
  password: vault:operations/data/int/ansible_tower#tower_admin_password
...
```

so this should be prefered:
https://argo-cd.readthedocs.io/en/stable/user-guide/compare-options/
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    vault.security.banzaicloud.io/vault-addr: 'https://vault-int.clustername.domain.com'
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/vault-role: ocp-int
    vault.security.banzaicloud.io/vault-skip-verify: 'true'
  labels:
    app.kubernetes.io/instance: awx-int
  name: awx-admin-password
stringData:
  password: vault:devops/data/int/awx#admin_password
```

which seems not to work:
![Screenshot from 2021-08-19 13-02-55](https://user-images.githubusercontent.com/10408311/130062855-750d68c2-658d-420e-9ec6-7560ff7c3756.png)
