### DISCUSSION TITLE
Can please give me an example how to use PostSync hook ?

### DISCUSSION THREAD

**Discussion by ishallbethat** [argoproj/argo-cd#5680] [Q&A]
I'm using helm to create argocd applications and then deploy the applications into cluster.
I created a job as below, but i don't know how to configure application so that it knows the PostSync and when a sync operation succeeds, the postSync can be triggered.

And also btw,  within the Job, is it possible to get who trigger the sync or what application is synced ?
```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "Authorization: Bearer xxx"
          - "-H"
          - "Content-Type: application/json; charset=utf-8"
          - "--data"
          - "{\"channel\":\"#mychannel\",\"text\":\"I hope everything went well, Mr. Gabriel.\"}"
          - "https://slack.com/api/chat.postMessage"
      restartPolicy: Never
  backoffLimit: 2
```

**Comment by jgwest** [comment]
Hi @IamGabrielWu, I'm not sure I 100% follow the first part of your question, but the Job (with hooks) should be contained alongside your other Helm resources in your Git repository, and will be automatically be created (and thus executed) once the Sync succeeds. (I presume [you saw this](https://argoproj.github.io/argo-cd/user-guide/resource_hooks/#using-a-hook-to-send-a-slack-message)).

For the second part of your question, AFAICT you can't get _who_ triggered the sync, but you can get some information about the application:

The call to Helm will include environment variables containing application information:
https://argoproj.github.io/argo-cd/user-guide/build-environment/

Which can be substituted as parameters into the Helm call:
https://argoproj.github.io/argo-cd/user-guide/helm/#build-environment

And from there you can use Helm templating of the Job (using those values) to include that information.

**Comment by ishallbethat** [comment]
@jgwest  i went through lots of materials on internet and still feel lost for what i can do to "contained alongside your other Helm resources in your Git repository,".

Does it mean like this ?  Please see my code below. 
How does the "Application" knows what Job to trigger ? there should be some link i need to set so application knows what job to trigger if it's synced. 

```
{{ $values := .Values }}
{{ $k8s_master_address := .Values.gke_cluster.k8s_master_address }}
{{- range $key, $value := $values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $value.release_name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $value.release_namespace }}
    server: {{ $k8s_master_address }}
  project: {{ $value.project }}
  source:
    helm:
      valueFiles:
      - {{ $value.release_values_file }}
    path: {{ $value.helm_chart_path }}
    repoURL: xxxx
    targetRevision: HEAD
  syncPolicy: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-fail-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command: 
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"App Sync failed\", \"icon_emoji\": \":ghost:\"}"
          - "https://hooks.slack.com/services/..."
      restartPolicy: Never
  backoffLimit: 2
{{- end }}

```
