### DISCUSSION TITLE
How to use environment variables in plugin?

### DISCUSSION THREAD

**Discussion by smeeklai** [argoproj/argo-cd#5693] [Q&A] [answered]
I have this configuration
```
server:
  config:
    configManagementPlugins: |
      - name: helm-secrets
        generate:
          command: ["helm"]
          args: 
            - "secrets"
            - "template"
            - "--namespace"
            - "${APP_NAME}"
            - "-f"
            - "deployments/${APP_NAME}/${ENV}/values.yaml"
            - "-f"
            - "deployments/${APP_NAME}/${ENV}/envs.yaml"
            - "-f"
            - "deployments/${APP_NAME}/${ENV}/secrets_decrypted.yaml"
            - "${APP_NAME}"
            - "${CHART_NAME}"
```
Those `${ENV}` don't get replaced by the corresponding `ENV` when the plugin executed the command. How can I use environment variables inside the command?

I've tried https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments but it didn't work

**Comment by alexmt** [comment]
Hello @smeeklai , 

Argo CD does not expand environment variables but you can delegated to `sh` or `bash`. Try to change the plugin config as following:

```
server:
  config:
    configManagementPlugins: |
      - name: helm-secrets
        generate:
          command: ["sh", "-c"]
          args: 
            - "helm"
            - "secrets"
            - "template"
            - "--namespace"
            - "${APP_NAME}"
            - "-f"
            - "deployments/${APP_NAME}/${ENV}/values.yaml"
            - "-f"
            - "deployments/${APP_NAME}/${ENV}/envs.yaml"
            - "-f"
            - "deployments/${APP_NAME}/${ENV}/secrets_decrypted.yaml"
            - "${APP_NAME}"
            - "${CHART_NAME}"
            - ```

**Comment by smeeklai** [comment, marked as answer]
@alexmt I'm getting below error from your answer
```
Unable to create application: error converting YAML to JSON: yaml: line 20: found character that cannot start any token
```
But I finally managed to get it work by doing so
```
configManagementPlugins: |
    - name: helm-secrets
    init:
        command: ["sh", "-c"]
        args:
        - helm repo add "$HELM_REPO_NAME" "$HELM_REPO_URL" && helm repo update
    generate:
        command: ["sh", "-c"]
        args:
        - helm secrets template -f values.yaml -f envs.yaml -f secrets-encrypted.yaml "$APP_NAME" "$HELM_REPO_NAME"/"$CHART_NAME"
```

Thank you
