### DISCUSSION TITLE
argo cd application with OLM OperatorGroup, Subscription, and CR

### DISCUSSION THREAD

**Discussion by aceeric** [argoproj/argo-cd#5729] [General]
I have one Argo CD Application deploying from a git repository with many manifests generated by `kustomize`. The three manifests causing this issue are:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: my-operator-group
  namespace: test-ns
spec:
  targetNamespaces:
  - test-ns
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: runtime-component-operator
  namespace: test-ns
spec:
  channel: runtime-component-operator-0.7.0
  installPlanApproval: Automatic
  name: runtime-component-operator
  source: my-disconnected-operators-registry
  sourceNamespace: olm
---
apiVersion: app.stacks/v1beta1
kind: RuntimeComponent
metadata:
  name: my-app
  namespace: test-ns
spec:
  ...
```
if I hand-deploy this application thus: `kustomize build | kubectl apply -f -` The following will happen in a cluster in which the runtime component operator has never been subscribed: The `OperatorGroup` and `Subscription` will deploy and `kubectl` will fail on the `RuntimeComponent` resource because the subscription has not fulfilled and therefore the cluster does not contain that CRD. So - wait a moment and redo the `kubectl apply` and the second time it succeeds. Thereafter in that cluster, every kube apply will work fine.

This application - when deployed using Argo CD v1.8.3 never syncs. If I hand-sync the` OperatorGroup` and `Subscription`, then hand sync everything else, the sync succeeds. But if I let Argo sync it - it fails with "app.stacks/v1beta1/RuntimeComponent the server could not find the requested resource". So it looks like it is attempting to validate the existence of a CRD and immediately stopping.

I tried annotating both the `OperatorGroup` and `Subscription` with `argocd.argoproj.io/hook: PreSync` hoping that these would be handled in the pre-sync. But no luck there - when I look at the application in the UI, those two resources are excluded from the resource network diagram in this case. And again if I try to hand sync the `Application` it fails with the same message.

If I hand sync the application one time, the result will be the runtime component CRD will now exist in the cluster. As is the case with `kubectl apply` - it appears that thereafter the Argo CD sync will succeed. So it appears to me that the specific issue is that Argo CD cannot handle the case where an application is being deployed into a cluster for the first time and there are custom resources that reference CRDs that are deployed by virtue of an OLM Subscription, and the Subscription has never before been subscribed in the cluster.

The application manifest looks like below, by the way:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my/repo/path
    repoURL: git@gitlab...
    targetRevision: my-branch-name
```
This is on Kubernetes v1.18.12+rke2r1
