### DISCUSSION TITLE
IgnoreDifference

### DISCUSSION THREAD

**Discussion by milalima** [argoproj/argo-cd#5855] [Q&A]
Hello guys, I am having an issue with my Argo configuration, and after a long talk into Slack, another guy and I are thinking that maybe it is a bug. Follow the information below:

 I am using the following spec:
```
spec:
  # The Argo project the application belongs to.
  project: {{ $.Values.spec.project }}

  # Destination cluster and namespace to deploy the application
  destination:
    name: {{ $.Values.spec.destination.name }}
    namespace: {{ $.Values.spec.destination.namespace | default $.Values.defaults.namespace }}
  
  # argo sometimes will always be out of sync after a deploy. 
  ignoreDifferences:
  # various keys getting injected by bank-vaults
  - kind: Secret
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
    - /data/cert.pem
    - /data/connection
    - /data/.dockerconfigjson

```

However, I need to ignore the last line of this part of the spec in the _Stateful_ 
```
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: alertmanager
      release: astronomer-infra-dev
      tier: monitoring
  serviceName: astronomer-infra-dev-alertmanager
  template:
    metadata:
      annotations:
        checksum/configmap: 5fdcab044e2f6a53afb49f098c8cf4632033bdbb37594636aaa373cba35d7dd2
      creationTimestamp: null
      labels:
        component: alertmanager
        release: astronomer-infra-dev
        tier: monitoring
    spec:
      affinity: {}
      containers:
      - args:
        - --config.file=/etc/config/alertmanager.yaml
        - --storage.path=/data
        - --web.external-url=https://alertmanager.infra-dev-astro.infra.activision.com
        - --cluster.listen-address=

```

I tried the following ways to ignore this code snippet:

> - group: apps 
>     kind: StatefulSet
>     jsonPointers:  
>       - /template/spec/containers

or this way:

>  kind: StatefulSet
>     jsonPointers:
>     - /spec/template/spec/containers

    
or this way:

> 
>  - kind: StatefulSet   
>     jsonPointers:
>     - /spec/template/spec/containers/args

or:

>  - group: apps
>    kind: StatefulSet   
>    jsonPointers:
>     - /spec/template/spec/containers/args

or 

> - group: apps 
>     kind: StatefulSet
>     jsonPointers:  
>       - /spec/template/spec/containers/0/args/0
>       - /spec/template/spec/containers/0/args/1
>       - /spec/template/spec/containers/0/args/2
>       - /spec/template/spec/containers/0/args/3

or 

> - group: apps
>     kind: StatefulSet
>     jsonPointers:
>       - '/spec/template/spec/containers/0/args/1'

And none seems to work, and I was wondering if this is a bug into Argo. Does any have any idea? 

Thanks

**Comment by jannfis** [comment]
The following works fine with the [guestbook](https://github.com/argoproj/argocd-example-apps/tree/master/guestbook) example app (although applied to a `Deployment` rather than a `StatefulSet`, and the container's port list instead of start-up arguments, but I guess it should behave the same for both):

To ignore differences on first port:
```yaml
  ignoreDifferences:                          
  - group: apps                               
    jsonPointers:                             
    - /spec/template/spec/containers/0/ports/0
    kind: Deployment                                       
```
To ignore differences on all ports:
```yaml
  ignoreDifferences:                          
  - group: apps                               
    jsonPointers:                             
    - /spec/template/spec/containers/0/ports
    kind: Deployment                                       
```
