### DISCUSSION TITLE
ingress-nginx configuration?

### DISCUSSION THREAD

**Discussion by rsoika** [argoproj/argo-cd#5955] [Q&A]
I have a problem installing argo-cd into my kubernetes cluster running a Ingress Nginx Controller.
I followed the ingress configuration explained [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#kubernetesingress-nginx).

Because the example is outdated for actual Kubernetes version I tried to figure out the correct setup of the Ingress object. 

I tried something like this:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - foo.com
    secretName: argocd-secret # do not change, this is provided by Argo CD
  rules:
  - host: foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server
            port:
              name: https
```

But this is not working. Maybe my Port name is the wrong one??

Can someone give me a hint how the ingress should look for kubernetes v1.20

**Comment by rsoika** [comment]
I figured out, that the correct Ingress yaml file for Kubernetes >=v.1.19  should look like this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # If you encounter a redirect loop or are getting a 307 response code 
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: {YOUR-DOMAIN-NAME}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server
            port:
              name: https
  tls:
  - hosts:
    - {YOUR-DOMAIN-NAME}
    secretName: argocd-secret # do not change, this is provided by Argo CD
```
