### DISCUSSION TITLE
Who is managed of events

### DISCUSSION THREAD

**Discussion by gtpark** [argoproj/argo-cd#5963] [Q&A]
Hello. I live in Korea. 

I performed a k8s volume mount to print all logs in KST time. 

```yaml
volumeMounts:
    - name: tls-certs
       mountPath: /app/config/tls
    - name: tz-seoul
       mountPath: /etc/localtime
volumes:
  - name: tz-seoul
     hostPath:
     path: /usr/share/zoneinfo/Asia/Seoul
````

Unfortunately, all dates exposed to events and values ​​like startedAt do not change. 

Which component is responsible for this? What should be corrected?
