### DISCUSSION TITLE
ArgoCD and Keycloak authorization

### DISCUSSION THREAD

**Discussion by antonionappi88** [argoproj/argo-cd#5984] [Q&A]
Hello,
I'm trying to configuring my ArgoCD instance with SSO.
We are using Keycloak with OIDC.
I've been following the [Existing OIDC Provider](https://argoproj.github.io/argo-cd/operator-manual/user-management/#existing-oidc-provider). 

This is my argocd-cm ConfigMap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  oidc.config: |
    name: argocd
    issuer: MY_ISSUER
    clientID: MY_CLIENT_ID
    clientSecret: MY_CLIENT_SECRET
    requestedScopes: [openid profile email]
    requestedIDTokenClaims:
      roles:
        essential: true
  url: https:/myendpoint.example.com
```
In Keycloak I have an application that is registered with two roles, `jeedy-admins` and `jeedy-readers`.

I setup the policy for the RBAC like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:jeedy-admins, *, *, */*, allow
    p, role:jeedy-readers, *, get, */*, allow
    g, jeedy-readers, role:jeedy-readers
    g, jeedy-admins, role:jeedy-admins
  policy.default: ""
```

This setting doesn't work. When I log in (i get the jeedy-admins role from Keycloak), i'm not able to perform any creation.
Does it mean that ArgoCD is suppose to work only with `groups scope` or `groups claim` ?
Or i'm missing something in the configuration.

Thanks,
Antonio
