### DISCUSSION TITLE
ArgoCD ingress tls secret clarification

### DISCUSSION THREAD

**Discussion by psibi** [argoproj/argo-cd#6173] [Q&A] [answered]
Right now in the [ingress docs](https://argo-cd.readthedocs.io/en/release-1.8/operator-manual/ingress/#ssl-passthrough-with-cert-manager-and-lets-encrypt), this is what is mentioned in it's manifest for tls:

  ``` yaml
  tls:
  - hosts:
    - argocd.example.com
    secretName: argocd-secret # do not change, this is provided by Argo CD
  ```

Now I don't understand why `argocd-secret` is required. Infact, when I
tried out using some other secret name - it's working fine for me.

On inspecting the helm chart, I don't see any such thing documented
there:
https://github.com/argoproj/argo-helm/blob/dbec4ad82e98770e7768eda751e771683fadf0db/charts/argo-cd/values.yaml#L519

Looking into the git history, it seemed to be initially introduced in
this PR: https://github.com/argoproj/argo-cd/pull/2629/files

So my question: Is the secret name required to be argocd-secret ? (If yes, it would be nice to have it documented on why it's required to be `argocd-secret`. I believe that will explain why in my setup it works without the secret name being `argocd-secret`)

I can send a PR improving the docs, if I get a better idea about this.

(Sorry for the cross-post between here and Slack.)
