### DISCUSSION TITLE
Plugin with environment variables

### DISCUSSION THREAD

**Discussion by DriesVanherpe-inuits** [argoproj/argo-cd#6221] [Q&A] [answered]
Is there a way to create a plugin with extra env variables  eg. 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: test
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      name: kustomized-helm
      upstream-repo: <repo>
 ```
