### DISCUSSION TITLE
HPA resource won't sync when using the averageValue field in custom metrics

### DISCUSSION THREAD

**Discussion by cliffpracht** [argoproj/argo-cd#6349] [Q&A]
This may be an issue with the HPA controller and not ArgoCD, but it appears Argo has a problem with syncing an autoscaling policy that includes `spec.metrics[0].object.target.averageValue` field type.  The HPA is created successfully but Argo believes the live manifest needs an additional field `value` and because git does not have said field defined in it, the resource never gets synced.

For instance a perfectly valid HPA manifest may look like this:

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-name
spec:
  maxReplicas: 4
  metrics:
  - object:
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name:  the-deployment-name
      metric:
        name: a-custom-metric
      target:
        averageValue: '1000'
        type: AverageValue
    type: Object
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: the-deployment-name
```

When argo applies this manifest, the HPA resource never reaches a synced/healthy state because of a perceived difference of `value`.

<img width="455" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/5769755/119870575-87d0c780-beef-11eb-9a4d-1a40116d6abf.png">

We were able to workaround this issue by adding the `value` field to the manifest in Git, but according to the HPA documentation this should not be needed. 

Thoughts or suggestions on where to go from here? 

On a side note, I don't fully understand how argo gets the applied manifest for HPA because it is different then if you were to look at the resource directly on the cluster (`kubectl get hpa hpa-name -o yaml`).
