### DISCUSSION TITLE
Sync fails unless namespace and CRD's manually created

### DISCUSSION THREAD

**Discussion by SDBrett** [argoproj/argo-cd#6413] [Q&A]
I'm new to ArgoCD and having trouble with my Application not synchronising.

Argo does not create the namespace used as the Application target when the create namespace option is selected.
Sync fails if the namespace and / or CRDs do not exist even though the are source manifests. Terminating and manually synchronising those items fixes the issue so I'm not sure why they are not created as part of sync.

Am I doing something wrong?

Application manifest using manifest to create namespace

```
project: default
source:
  repoURL: 'https://github.com/operator-framework/operator-lifecycle-manager'
  path: deploy/upstream/manifests/0.18.0
  targetRevision: v0.18.1
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: 'https://kubernetes.default.svc'
syncPolicy:
  automated:
    selfHeal: true
  syncOptions:
    - Replace=true
```

I don't have any issues with Applications creating namespaces from manifests if that's all they create. I feel that there's a race condition where Argo attempts to create resources in an order that just doesn't work.

Is there a way to control the order which Argo attempts to apply objects?
