### DISCUSSION TITLE
where do you reference build your own image?

### DISCUSSION THREAD

**Discussion by rwong2888** [argoproj/argo-cd#6452] [Q&A] [answered]
I built my own image as per below for execProviderConfig and helm plugins
https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters
https://argoproj.github.io/argo-cd/user-guide/helm/#helm-plugins
Where do I need to reference my custom image?

**Comment by jannfis** [comment, marked as answer]
Hey @rwong2888, you will need to either adapt the installation manifests or the running workload in your cluster. For custom tooling, the container used by the `argocd-repo-server` deployment is the one that needs to be changed to use your custom image, e.g. [here](https://github.com/argoproj/argo-cd/blob/c62012d526b2cef09aa67401b6c8cfc9fea3d30c/manifests/install.yaml#L3227).

A very easy way is to do this is to use Kustomize, with a `kustomization.yaml` such as:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.0.3
images:
- name: quay.io/argoproj/argocd
  newName: your/image
  newTag: yourtag
```

This will render new installation manifests that use your custom image (although, for _all_ of the workloads not just the `argocd-repo-server` one). If you use another version of Argo CD, or have installed non-HA or non-cluster-scoped manifests, adapt the base URL in `resources` accordingly.
