### DISCUSSION TITLE
Hiding a resource type from argocd: cilium identities

### DISCUSSION THREAD

**Discussion by cyrilcros** [argoproj/argo-cd#6454] [Q&A] [answered]
Hi,
I am using cilium as my CNI, it creates `ciliumidentity` resources that get deleted because ArgoCD doesn't recognize them. See https://docs.cilium.io/en/v1.9/api/#get--identity for ref.
Is there a global way to disable this, instead of per chart behavior? This: https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration ?
Thanks!

**Comment by jannfis** [comment, marked as answer]
You can completely exclude any resource(s) from being seen/touched by Argo CD on a global level as described [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion).

**Reply by kastl-ars** [reply]
For the next one stumbling upon this, the `apiGroup` only contains `cilium.io` in this case, without the `/v2` suffix... :-)

```
  resource.exclusions: |
    - apiGroups:
      - "cilium.io" # no /v2 suffix or similar here...
      kinds:
      - "CiliumIdentity"
      clusters:
      - "*"

```
