### DISCUSSION TITLE
ComparisonError: Namespace "guestbook" for Deployment "guestbook-ui" is not managed

### DISCUSSION THREAD

**Discussion by cnukwas** [argoproj/argo-cd#6473] [Q&A]
I am new to Argo CD and OpenShift GitOps. I have set up Argo CD instance in one of the OpenShift namespaces and trying to deploy Argo guestbook example in guestbook namespace and getting this error. I believe this is a valid error, but no clue on if it's a Argo CD or OpenShift GitOps operator issue. I am posting here in case anyone is ran into similar issue when Argo CD instance is set up at Namespace scope, rather than using default Argo CD instance created OpenShift GitOps operator(1.1.2 with Argo CD 2.0.0) installation as a cluster admin. Posting here to get community feedback, going to check with OpenShift folks as well.

`ComparisonError Namespace "guestbook" for Deployment "guestbook-ui" is not managed`

Created 2 namespaces myns-argo and guestbook, created an instance of Argo in the myns-argo ns, created a 'admin' rolebinding in the guestbook ns for the Argo service account(myns-argo-argocd-application-controller)  as below.

Based on what I read or saw from a OpenShift video, this is supposed to work, but it's not. Either this no longer works or I am missing something here.

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guestbook-ns-allowing-myns-argo
  namespace: guestbook
subjects:
  - kind: ServiceAccount
    name: myns-argo-argocd-application-controller
    namespace: myns-argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
```
Update:
Noticed that Argo Cluster configuration had only myns-argo namespace entry only, so added guestbook to the list and the entry now looks as below.

`NAMESPACES: myns-argo, guestbook`

Now getting additional errors, so it appears that Argo CD instance requires clusterrole RBAC even when it's set up at namespace scope(if that's the right terminology to use). I read about exclusion and inclusion list for the Argo instance, is that what needs to be done here to limit Argo instance access to certain resources only?

```
ComparisonError
failed to sync cluster https://111.11.0.1:443: failed to load initial state of resource IngressController.operator.openshift.io: ingresscontrollers.operator.openshift.io is forbidden: User "system:serviceaccount:myns-argo:myns-argo-argocd-application-controller" cannot list resource "ingresscontrollers" in API group "operator.openshift.io" in the namespace "guestbook"

ComparisonError
failed to sync cluster https://111.110.1:443: failed to load initial state of resource Prometheus.monitoring.coreos.com: prometheuses.monitoring.coreos.com is forbidden: User "system:serviceaccount:myns-argo:myns-argo-argocd-application-controller" cannot list resource "prometheuses" in API group "monitoring.coreos.com" in the namespace "guestbook"
```
Thanks

**Comment by jannfis** [comment]
Hi @cnukwas,

unfortunately, binding the application-controller's SA to the `admin` ClusterRole is not sufficient. You will need to create a role in the target namespace (e.g. `guestbook`) that allows reading of all resources. It seems not all namespaced APIs in OpenShift are reconciling themselves into the `admin` role.

So, you will need an additional `Role` in the `guestbook` namespace much like the following:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role     
metadata:
  name: argocd-application-controller
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
```
and then bind it to your ServiceAccount used by argocd-application-controller, e.g to

```yaml
subjects:
  - kind: ServiceAccount
    name: myns-argo-argocd-application-controller
    namespace: myns-argo
```

**Reply by cnukwas** [reply]
Thanks for the update. I tried by creating following role and rolebinding, still no luck as I still see errors for other resources.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role     
metadata:
  name: guestbook-ns-allowing-myns-argo-role
  namespace: guestbook
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guestbook-ns-allowing-myns-argo-rolebinding
  namespace: guestbook
subjects:
- kind: ServiceAccount
  name: myns-argo-argocd-application-controller
roleRef:
  kind: Role 
  name: guestbook-ns-allowing-myns-argo-role
  apiGroup: rbac.authorization.k8s.io
```
New error for other resources, similar error as earlier, for a difference resource:

```
ComparisonError
failed to sync cluster https://111.110.1:443: failed to load initial state of resource Alertmanager.monitoring.coreos.com: alertmanagers.monitoring.coreos.com is forbidden: User "system:serviceaccount:myns-argo:myns-argo-argocd-application-controller" cannot list resource "alertmanagers" in API group "monitoring.coreos.com" in the namespace "guestbook"
```

**Reply by jannfis** [reply]
I'd assume that's because the subject of your `RoleBinding` is missing the namespace property. The `ServiceAccount` you want to bind it to lives in the `myns-argo` namespace according to the information provided, but the `RoleBinding` assumes to bind to a `ServiceAccount` in the `guestbook` namespace.

You will probably have more luck when you change the following in your `RoleBinding`

```yaml
subjects:
- kind: ServiceAccount
  name: myns-argo-argocd-application-controller
```
to
```yaml
subjects:
- kind: ServiceAccount
  name: myns-argo-argocd-application-controller
  namespace: myns-argo
```
