### DISCUSSION TITLE
Needs help with GitHub SSO

### DISCUSSION THREAD

**Discussion by plutino** [argoproj/argo-cd#6497] [Q&A] [answered]
Greetings!  I ran into some issue with SSO and hope to get some help from here.  I configured ArgoCD to use dex for GitHub SSO.  Everything works well until (I actually didn’t know what triggered this).  Now every time I click on Log in via GitHub, it always redirect me back to the login page.  This error message shows up in the argo-server pod log:
```
time="2021-06-17T16:09:25Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims=null grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-06-17T16:09:25Z" span.kind=server system=grpc
time="2021-06-17T16:09:25Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2021-06-17T16:09:25Z" grpc.time_ms=1.066 span.kind=server system=grpc
time="2021-06-17T16:09:25Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-06-17T16:09:25Z" grpc.time_ms=2.555 span.kind=server system=grpc
time="2021-06-17T16:09:25Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2021-06-17T16:09:25Z" grpc.time_ms=0.067 span.kind=server system=grpc
time="2021-06-17T16:09:25Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims=null grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-06-17T16:09:25Z" span.kind=server system=grpc
time="2021-06-17T16:09:25Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2021-06-17T16:09:25Z" grpc.time_ms=0.174 span.kind=server system=grpc
time="2021-06-17T16:09:25Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=application.ApplicationService grpc.start_time="2021-06-17T16:09:25Z" grpc.time_ms=0.045 span.kind=server system=grpc
```

Here is the configuration for dex that I'm using:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://{{ .Values.ingress.hostname }}

  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex.github.clientID
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: mycase
            teams:
              - Ops
```

ArgoCD is deployed with helm chart v3.6.8 and Docker Image v2.0.3

Thanks and appreciate any help.
