### DISCUSSION TITLE
Argo CD is unable to connect with Private GKE

### DISCUSSION THREAD

**Discussion by abhinayguptapeoplegrove** [argoproj/argo-cd#6553] [Q&A]
PROBLEM STATEMENT:

-  Unable to add private GKE cluster in Argocd

SUMMARY:
- We have created a public GKE cluster for hosting all ArgoCD components
- We are using this cluster to deploy k8 resources to other multiple private GKE clusters across  different GCP projects

STEPS FOLLOWED:

- 1- We created the private GKE cluster and added our IP in the authorised network
- 2- We install the argoCD Cli on our laptop and we did the argocd login
- 3- We are able to access the ArgoCD UI and apps 
- 4- To add the private GKE cluster via argocd cli, we executed above command and got the error

ERROR:
We are getting below error while adding the private GKE cluster via argocd CLI

```
**➜$ argocd cluster add gke_*******_us-******-c_*******
INFO[0000] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0001] ClusterRole "argocd-manager-role" updated    
INFO[0002] ClusterRoleBinding "argocd-manager-role-binding" updated
FATA[0035] rpc error: code = Unknown desc = Get "https://34.xx.xx.xx/version?timeout=32s": dial tcp 34.xx.xx.xx:443: i/o timeout** 
```

DEBUG INFORMATION:
Cloud - GCP 
Argo version- v2.0.2
GKE version- 1.19.10-gke.1600
Private GKE cluster features enabled:
 > Control plane global access: TRUE
 > Control plane authorized networks: TRUE     ("Added our public CIDR to it")

P.S: This is an urgent Issue. Please help

**Comment by meier-christoph** [comment]
You can actually add a cluster without using the cli. A cluster is configured using json in a Secret with some labels to tell argocd that this is the conf of your new cluster. The json contains the token of the service account which you can get from the target cluster. You should already have that done based on the logs you posted. You also need the uri of the api server and the caBundle and I think thats it. 

I am currently on my phone and not 100% sure about all the details but we are doing more or less the same thing as you and we don‘t use the cli at all. This part is not so well documented, most ppl should use the cli but its definately possible.

Also, I believe that now there are some NetworkPolicies by default. The trap with NPs is that they work like a whitelist BUT if there are none defined the default is to allow all traffic which is counter intuitive. Since there are now NPs they drop any traffic that is not explicitly defined.

You should try to add a NP that allows argocd to egress to your other clusters. Then exec into the argocd container and test if you can reach the other clusters.

**Reply by IamViditAgarwal** [reply]
Hi, @meier-christoph  
We tried creating the secret in the argocd for adding the cluster , It seems to work. The cluster is added and we can see it the argo dashboard UI . But now we are not able to deploy the application in that cluster . Its giving us the same : `Get "https://34.xx.xx.xx/version?timeout=32s": dial tcp 34.xx.xx.xx:443: i/o timeout** 
`
Could you share the networkpolicy ? Not able to figure-out what should be the ideal policy to be created . That will be really helpful

Thanks & Regards

**Reply by cheskayang** [reply]
^ run into the same issue, were you able to resolve it?

**Comment by meier-christoph** [comment]
Try something like this :

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-to-external-cluster
  namespace: argocd
spec:
  podSelector: {}
  egress:
    - to:
        - ipBlock:
            cidr: 34.xxx.xxx.xxx/32
      ports:
        - port: 443
```

This allows all pods in the argocd namespace to connect with your IP on port 443. For production you should change the podSelector to only select the actual pod but for testing this should be ok.

There is a great tool to create NPs if you are not familiar with the syntax 
https://editor.cilium.io/

Next, you should just exec into the pod and try to ping the target server. NPs are just firewall rules managed by k8s, you should treat this like any other networking issue. It's also possible that you need to add some networking rules in GCP to make it work.

If I remember correctly there is kubectl in the argocd docker image, if you exec into the container you can manually create the ~/.kube/config file for your target cluster and see if it works.

**Comment by abhinayguptapeoplegrove** [comment]
Hey @meier-christoph . Thanks for your suggestion.

We have created the same NP in kubernetes cluster as you mentioned but it didn't work, even after adding firewalls given below, it didn't work 

ArgoCD cluster project firewall rule: 

- Type- egress, protocols and port- all
- Applicable On- for all Argcd Cluster nodes (ArgoCD server is running on one of the nodes)
- Destination IP- 34.xxx.xxx.xxx/32  (This is public endpoint of a private GKE nodes), also tested with private end point (10.xx.xx.xx/32) as destination ip in firewall rule

Target private GKE cluster project firewall rule:

- Type- ingress, protocols and port- from all
- Applicable On- For all private GKE cluster nodes

For verification
From argocd project, telnet for master ip( target private GKE project), port 443 is not working

**Reply by meier-christoph** [reply]
Well the good news is that since telnet is not working you know for sure that this is a network issue and not an ArgoCD issue. 

I don't really know much about GCP but at this point its safe to assume that there are some firewalls blocking traffic that need to be configured somewhere.

Also, if you are not using NPs (e.g. older versions of argocd) I would recommend removing the ones you created and use the default behavior which is allow all (or you create the necessary rules for all pods that argocd uses).

**Reply by abhinayguptapeoplegrove** [reply]
We checked the argocd version and found below details below, it looks latest version

```➜  Documents argocd version
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T19:33:57Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.4+0842d44
  BuildDate: 
  GitCommit: 
  GitTreeState: 
  GoVersion: 
  Compiler: 
  Platform: 
  Ksonnet Version: 
  Kustomize Version: 
  Helm Version: 
  Kubectl Version: 
  Jsonnet Version:

If possible can you please share some docs for reference for this type of Use-case

**Reply by meier-christoph** [reply]
NPs were added in v2.0.2 #6156 you should be fine with the latest version

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-to-external-cluster
  namespace: argocd
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 34.0.0.0/8
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
    - to:
        - podSelector: {}
```

you can also try this which is basically allowing any traffic but again it will probably not do much since the real issue is probably a missing configuration in GCP and I won't be able to help with that since I never used it.

**Comment by davinerd** [comment]
I'm struggling with this as well.

I've downgraded to ArgoCD 2.0.0 thinking it would something NP related, but it actually isn't.

Based on [Google official doc](https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept), when creating manually the argocd secret, the server section must be the private endpoint IP (which can be obtained with a `gcloud container clusters describe`).

Still, the status of the cluster in the ArgoCD UI is "Unknown", which is not what we expect.

Firewall rules on GCP allow TCP 443 communication between nodes and master plane. Workloads are deployed correctly, thus I'd exclude a firewall issue on GCP side.

Could we have more support on this issue?
It's disappointing to see ArgoCD not taking into serious consideration this issue, taking into account that private GKE clusters should be the norm and thus ArgoCD should work out of the box, or at least provide documentation on how to make it work.

Edit: adding a firewall rule in GCP with allow all protocols for all machines in the network coming from 0.0.0.0/0 still doesn't solve the issue.

**Reply by meier-christoph** [reply]
I will try but since we are not using GCP I can only do so much.

First of forget about ArgoCD and try to connect on the target cluster (Cluster-B) using kubectl running on the ArgoCD cluster (Cluster-A).

In order to do this you will need to prepare a few things 

### Create a ServiceAccount on Cluster-B

You can use use account that argocd will use in the end or a different one, it doesn't matter. To make things easy just `kubectl apply -f sa.yaml` with this file :

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-role
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system
```

IMPORTANT: make sure you add this to the target cluster, NOT the ArgoCD cluster.

### Prepare a kubeconfig file for Cluster-B

You can use the token of the ServiceAccount you just created to connect on the cluster using kubectl

Here is an example kubeconfig file :

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://cluster-b.example.com
  name: cluster-b
contexts:
- context:
    cluster: cluster-b
    user: argocd-manager-token
  name: cluster-b
current-context: cluster-b
kind: Config
preferences: {}
users:
- name: argocd-manager-token
  user:
    token: xxx # token from secret of service account argocd-manager in kube-system
```

Make sure this works before you continue. 

Note: you can try different combinations using public or local ips

### Create a container with kubectl

Maybe you can find some on docker hub, otherwise create one, use a base image with a shell (not scratch or distroless).

### Run the kubectl container on Cluster-A

Run the container you created on Cluster-A, idealy inside the argocd namespace and with the same labels as those used by argocd (in order to apply the same network policies).

Then exec into that container, copy the kubeconfig from earlier in there and try to connect on Cluster-B using kubectl.

If it works, then its likely an issue with ArgoCD, if it doesn't work then you can try in a different namespace, without the labels and no network policy, if it still doesn't work its definitely network related and probably a GCP issue (or missing config).

Good luck,
Chris
