### DISCUSSION TITLE
Invalid apiVersion Error when adding external gke cluster

### DISCUSSION THREAD

**Discussion by stelispanagiotakis** [argoproj/argo-cd#6563] [General]
Hi All! 
We're using argo-helm to deploy argocd to a gke cluster.
Everything seems great until I try to add an external (again gke) cluster.
These are the relevant lines from my values.yaml
```
  clusterCredentials:
  - name: ext-cluster
    server: https://${external_cluster_endpoint}
    config:
      execProviderConfig:
        command: "/kubecluster/goapps/bin/gcp-exec-creds"
        args: ["|", "sed", "-e", "s/ExecCredential/kind/", "-" ]
      apiVersion: client.authentication.k8s.io/v1beta1
      installHint: SomeInstallHint
      tlsClientConfig:
        insecure: false
        caData: ${external_cluster_cadata}
```
The secret seems to be created correctly (after inspection)

(If anyone is wondering the command is a little credential helper from https://github.com/sl1pm4t/gcp-exec-creds )
The `execProviderConfig.command` is available to the argocd-repo-server container
I'm using the initContainer to install it, as seen below
```
repoServer:
  volumeMounts:
  - name: kubeclustervolume
    mountPath: /kubecluster
  volumes:
  - name: kubeclustervolume
    emptyDir: {}
  initContainers:
  - name: gcloud
    image: google/cloud-sdk
    command: [bash, -c]
    args:
    - rm -rf /kubecluster/* && apt-get update && apt-get install -y wget curl && mkdir -p /kubecluster/goapps &&
      cd /kubecluster && wget https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz &&
      tar -C /kubecluster -xzf go1.13.4.linux-amd64.tar.gz &&
      export GOPATH=/kubecluster/goapps &&
      /kubecluster/go/bin/go get -v github.com/sl1pm4t/gcp-exec-creds &&
      chmod -R 777 /kubecluster && chown 999:999 /kubecluster && /kubecluster/goapps/bin/gcp-exec-creds
    volumeMounts:
    - name: kubeclustervolume
      mountPath: /kubecluster
```
Manually checking I get ( from what I gather) the correct output
(cross-checked with https://kubernetes.io/docs/reference/access-authn-authz/authentication/)

```
 kubectl exec -it argocd-repo-server-xxxx-xxx -- /kubecluster/goapps/bin/gcp-exec-creds - | sed -e s/ExecCredential/kind/ -
{
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "kind": "ExecCredential",
  "status": {
    "token": "CORRECT_TOKEN"
  }
}
```
But when I add an App via UI to be deployed to this external cluster I get

`time="2021-06-24T22:32:13Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Unable to apply K8s REST config defaults: exec plugin: invalid apiVersion \"\"" grpc.code=Internal grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2021-06-24T22:32:12Z" grpc.time_ms=1265.269 span.kind=server system=grpc
`
Apart from the repo server I also tried installing the credentials helper to the argocd-server and the application-controller.
Same results :disappointed:
Anyone have a clue as to what I may be missing?
Thanks soo much!
