### DISCUSSION TITLE
Helm install command line to ArgoCD Helm application issue with ingress.annotations

### DISCUSSION THREAD

**Discussion by Evantage-WS** [argoproj/argo-cd#6641] [General]
Hello,

I have this helm install
```
helm install keycloak bitnami/keycloak \
    --namespace keycloak \
    --create-namespace \
    --version $VERSION \
    --set ingress.enabled=true \
    --set ingress.tls=true \
    --set ingress.hostname=keycloak.internal.xxxxxx.com \
    --set replicaCount=1 \
    --set postgresql.enabled=true \
    --set auth.createAdminUser=true \
    --set auth.adminUser=admin \
    --set postgresql.postgresqlUsername=keycloakdb \
    --set postgresql.postgresqlPassword=keycloakdb \
    --set postgresql.postgresqlDatabase=keycloakdb \
    --set postgresql.persistence.enabled=true \
    --set global.storageClass=standard \
    --set ingress.servicePort=https \
    --set service.type=ClusterIP \
    --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/backend-protocol"="HTTPS" \
    --set-string ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
    --set-string ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt-staging
```
which is working fine. I am trying to convert this to an ArgoCD Helm install, but I am strugling with the ingress annotations. I have put them in 'VALUES', but they are not set.

![image](https://user-images.githubusercontent.com/59507751/124510465-27795380-ddd4-11eb-8d76-dddbe4cf994d.png)

Anyone any idea?

Thanks!

**Comment by Evantage-WS** [comment]
Solved it

```
global:
  storageClass: standard
ingress:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
```
