### DISCUSSION TITLE
Repository creation error for OIDC group user

### DISCUSSION THREAD

**Discussion by cnukwas** [argoproj/argo-cd#6650] [Q&A]
I have configured OIDC groups as per the documentation and it's working fine for admins, but seeing an issue when a group user tries to create a repository by logging into Argo web UI. It's not clear on how to resolve this since we don't want admins to manage or add every team or project repository either with SSH keys or user credentials. App teams should be able to add any repositories as per Argo RBAC mentioned below, in the team's Project.

Error message when a user from 'TeamA-developer' tries to create a repository by logging into Argo web UI. Note that Argo admin role user is able to create the repository, after that user in the question is able to create an Application in the TeamA-Project without any issues.

Is the error because there's no Argo Project scope while creating a repository connection or am I missing any RBAC here?

`Unable to connect SSH repository: permission denied: repositories, create, git@github.myorg.com:App1/TeamA-repo.git, sub: /user1234`

argocd-rbac-cm Configmap entries:
```
apiVersion: v1
data:
  admin.enabled: "false"
  policy.csv: |
    g, argo-admin, role:admin
    p, role:TeamA-admin, applications, *, TeamA-Project/*, allow
    p, role:TeamA-admin, clusters, get, TeamA-Project/*, allow
    p, role:TeamA-admin, repositories, *, TeamA-Project/*, allow
    p, role:TeamA-admin, certificates, *, TeamA-Project/*, allow
    p, role:TeamA-admin, projects, get, TeamA-Project, allow
    g, TeamA-developer, role:TeamA-admin
    g, TeamA-cd, role:TeamA-admin
  policy.default: role:readonly
```

TeamA-Project Argo Project YAML: 
```  
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: TeamA-Project
  namespace: openshift-gitops
spec:
  description: Argo Project used by all TeamA group
  destinations:
  - namespace: dev-*
    server: https://kubernetes.default.svc
  roles:
  - description: Admin role for all namespaces in TeamA group
    groups:
    - TeamA-developer
    - TeamA-cd
    name: TeamA-admin
    policies:
    - p, proj:TeamA-Project:TeamA-admin, applications, *, TeamA-Project/*, allow
  sourceRepos:
  - '*'
  ```

Thanks
