### DISCUSSION TITLE
K8s resources are deleted when being moved from one ApplicationSet to another (prune is set to false)

### DISCUSSION THREAD

**Discussion by weichuliu** [argoproj/argo-cd#6676] [General]
Hi,

In our deployment, we have an ArgoCD applicationset. It is used to deploy Consul via Helm.
We were working on splitting it into 3 applicationsets per staging level (inf, qa, prod).

During this splitting, we expected the old resources to be taken over by the new applicationsets without recreation. However, the resources were actually deleted then recreated in ArgoCD, even though the `prune` are all set to `false`. And it caused downtime.

Can you help to take a look about what did we do wrong? Is there a way we can move resources between applications without deleting it?

Thanks very much.

Here is how the manifest looks like:

1. We have this `meta` app at the path `argocd/consul.yaml` that applies YAMLs under `argocd/consul/`.

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-consul-k8s-meta
spec:
  project: argo-projects
  destination:
    name: ...
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  source:
    repoURL: [same-repo]
    targetRevision: master
    path: argocd/consul
```

2. At the path `argocd/consul/consul-app.yaml`, we used to have a single monolithic ApplicationSets:

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consul
spec:
  generators:
    - list:
        elements:
        - cluster: prod1
          url: ...
        - cluster: prod2
          url: ...
        - cluster: testing1
          url: ...
        - cluster: testing2
          url: ...
  template:
    metadata:
      name: consul-{{cluster}}
    spec:
      project: consul
      source:
        helm:
          releaseName: cv-consul
          valueFiles:
            - values-{{cluster}}.yaml
        path: manifests/consul/transitional
        repoURL: [same-repo]
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: consul
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

3. After splitting, it looks like this:

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consul
spec:
  generators:
    - list:
        elements:
        - cluster: prod1
          url: ...
        - cluster: prod2
          url: ...
        # - cluster: testing1
        #   url: ...
        # - cluster: testing2
        #   url: ...
  template:
    metadata:
      name: consul-{{cluster}}
    spec:
      project: consul
      source:
        helm:
          releaseName: cv-consul
          valueFiles:
            - values-{{cluster}}.yaml
        path: manifests/consul/transitional
        repoURL: [same-repo]
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: consul
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consul-testing
spec:
  generators:
    - list:
        elements:
        - cluster: testing1
          url: ...
        - cluster: testing2
          url: ...
  template:
    metadata:
      name: consul-{{cluster}}
    spec:
      project: consul
      source:
        helm:
          releaseName: cv-consul
          valueFiles:
            - values-{{cluster}}.yaml
        path: manifests/consul/transitional-testing
        repoURL: [same-repo]
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: consul
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

**Comment by algo7** [comment]
Can be confirmed with argocd v2.9.3

**Comment by rumstead** [comment]
I am adding what I put on the issue here. 

By removing the elements in the list generator, I would expect the ApplicationSet to delete the child Applications. By default, Applications have [finalizers set on them that will delete all deployed resources](https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#about-the-deletion-finalizer) (besides CRDs). You can control this behavior by [removing the finalizer ](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Application-Deletion/) or at the [individual resource level](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-resource-deletion). 

Similar to the list generator, in the path example, it looks like your Application names are changes which results in them being deleted and recreated, which in turn happens to all the underlying resources.
```
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
```

Prune will only prevent resources from deleting that were removed from Git, more or less.
