### DISCUSSION TITLE
FATA[0000] rpc error: code = FailedPrecondition desc = another operation is already in progress

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-cd#6678] [Q&A]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
FATA[0000] rpc error: code = FailedPrecondition desc = another operation is already in progress

**To Reproduce**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: default
  source:
    repoURL: https://codechina.csdn.net/hxpjava1/argocd-example-apps.git
    targetRevision: master
    path: guestbook
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

apply crd then sync app
```
A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**
[root@master01 application]# argocd version
argocd: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
