### DISCUSSION TITLE
IgnoreDifference not effictive

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-cd#6681] [Q&A]
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: default
  source:
    repoURL: https://codechina.csdn.net/hxpjava1/argocd-example-apps.git
    targetRevision: master
    path: guestbook
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 3
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers: 
    - /spec/template/spec/containers
```

I changed the image field,it should be ignored but the app refreshed the field image
