### DISCUSSION TITLE
Argo Rollouts changes in Ingress is updated by Argo CD if we add sync option selfHeal

### DISCUSSION THREAD

**Discussion by Sonam11** [argoproj/argo-cd#6763] [Q&A]
So for Canary kind of deployment where the traffic splitting is done via Argo Rollouts, it updates the Ingress in our case (IngressRoutes), so if the IngressRoute is part of Git repo and the app is using `sync option selfHeal` so any changes made by Argo Rollouts is rewritten by Argo CD. 

One way to resolve is to not use `selfHeal`, but we wish to use this for other benefits offered by this option, so please suggest how we can resolve this kind of scenario.

**Comment by jgwest** [comment]
Hi @Sonam11, my only suggestion is trying the [application level configuration diffing](https://argoproj.github.io/argo-cd/user-guide/diffing/#application-level-configuration) configuration, where you tell Argo CD (in your Application) to ignore the specific field that is being changed by rollouts (but I'm uncertain if this setting affects self heal or not, so YMMV).

If anyone else has more experience with  Ingresses in Argo Rollouts and Argo CD, feel free to add your thoughts!

**Comment by Sonam11** [comment]
Thanks @jgwest I did use it, it didn't worked as expected, so below are my specs:

```
# Source: ethos-argocd-client-templates/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <name>
  namespace: argocd
spec:
  ignoreDifferences:
  - group: contour.heptio.com/v1beta1
    kind: IngressRoute
    jsonPointers:
    - /spec/routes
  project: default
  source:
    repoURL: <repo-url>
    targetRevision: HEAD
    path: <path to helm>
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: <name of server>
    namespace: <Namespace>
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
       
```
Please let me know if I am missing anything. Thanks for the help.
