### DISCUSSION TITLE
argocd dex config for adfs

### DISCUSSION THREAD

**Discussion by marcportabellaclotet-mt** [argoproj/argo-cd#7032] [General]
I have been trying to configure argocd with dex to user saml login using Windows 2019 Server.
I googled a lot, but I could not find any working configuration for me.

```
 Exception details: 
Microsoft.IdentityServer.Protocols.Saml.InvalidNameIdPolicyException: MSIS7070: The SAML request contained a NameIDPolicy that was not satisfied by the issued token. Requested NameIDPolicy: AllowCreate: True Format: urn:oasis:names:tc:SAML:2.0:nameid-format:persistent SPNameQualifier: . Actual NameID properties: Format: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress, NameQualifier:  SPNameQualifier: , SPProvidedId: .
```
If anybody has been able to connect argocd dex with adfs, could you please post all the steps?
Thanks

**Comment by AlbertoSpain** [comment]
It works with OAuth & OIDC config.:

Edit argocd-cm config map

```
data:
  url: https://argocd_url
  oidc.config: |
    name: ADFS
    issuer: https://--adfs_url--/adfs
    clientID: --------
    clientSecret: --------
    insecureEnableGroups: true
    requestedScopes:
    - openid
    - profile
    - email
    - groups
```
Create an Application group into ADFS, type: server application accessing web api
You have to transform claims --> create an issuance transform rule which send ldap attributes as claims, but:
token groups unquialified names --> groups
Display Name --> email

You also have to check the altclaims scope
