### DISCUSSION TITLE
Manage third-party helm app using ArgoCD

### DISCUSSION THREAD

**Discussion by slavafomin** [argoproj/argo-cd#7041] [Q&A]
Hello!

First of all, thank you for this great tool!

However, I would like to install and manage a third-party helm application using ArgoCD with the ability to define helm customization values in my Git repository (source of truth for ArgoCD). How should I do it?

I'm using the same pattern using Kustomize and it works great. Here's the Kustomize example of how I manage the ArgoCD iteself:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
  - resources/applications/app-of-apps.yaml
  - resources/server/ingress.yaml

patches:
  - resources/config-map/config-map.patch.yaml
  - resources/server/service.patch.yaml
```

Is it possible to do the same with Helm?

Thanks!
