### DISCUSSION TITLE
Iterate and create multiple apps

### DISCUSSION THREAD

**Discussion by juanvasquezreyes** [argoproj/argo-cd#7087] [General]
I'm testing argocd, but I was wondering if we can do something like this

```
{{ range .Values.deployments }} 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.name}}
  namespace: test
spec:
  destination:
    namespace: {{.namespace}}
    name: in-cluster
  project: test
  syncPolicy: {}
  source:
    repoURL: "{{.repository}}"
    targetRevision: "master"
    path: "{{.path}}"
    helm:
      valueFiles: 
        - ../values/qa-az-values.yaml
{{- end }}
```

and in the values have the following
```
deployments: 
  - repository: git@git..."
    name: "test"
    path: "chart/"
    namespace: "default"  
  - repository: git@git..."
    name: "test2"
    path: "chart/"
    namespace: "default"  
  
```

I want to iterate and create as many apps I want with the same values and same parameters for all of them, for some reason when I do doesnt create any of the deployment apps

The scenario is that if I have 50 apps I dont want to create 50 application files for them, I just want to iterate them and automatically deploy all of them

**Comment by todaywasawesome** [comment]
It looks like you're using Helm so I don't think this is an Argo CD issue. When you build this try using helm template to see exactly how the manifests are generated. I haven't done it in a while but you can look at this example I made for iterating over a set of values to generate objects using Helm. https://github.com/todaywasawesome/color-coded/blob/master/deploy/helm/colors/templates/deployment.yaml

**Reply by juanvasquezreyes** [reply]
This is what I'm trying to do, lets take this as example https://github.com/argoproj/argocd-example-apps/tree/master/apps
in templates/helm-guestbook.yaml there is an application definition

all I want is to create as many applications I want using range

**Reply by todaywasawesome** [reply]
I don't see why that wouldn't work. Can you run `helm template` on it and share the results. If it shows two deployments then you should be good to go.

**Reply by juanvasquezreyes** [reply]
I ran the helm template and I was able to see the two deployments, but in argocd it didnt triggered the two apps

so, I ran the helm template again but sending output to a dummy file and manually ran kubectl apply dummy file and it created the app correctly


helm template output
```
---
# Source: root/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: test
spec:
  destination:
    namespace: default
    name: in-cluster
  project: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: "git@gitlab.com:..."
    targetRevision: "master"
    path: "chart"
    helm:
      valueFiles: 
        - ../values/qa-az-values.yaml
---
# Source: root/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
  namespace: default
spec:
  destination:
    namespace: test
    name: in-cluster
  project: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: "git@gitlab.com:..."
    targetRevision: "master"
    path: "chart"
    helm:
      valueFiles: 
        - ../values/qa-az-values.yaml

```
