### DISCUSSION TITLE
Helm dependency using cache version

### DISCUSSION THREAD

**Discussion by juanvasquezreyes** [argoproj/argo-cd#7134] [Q&A] [answered]
I'm using the following application definition, where I'm going to git and deploying myapp
```
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:  
  name: myapp
  namespace: default  
spec:
  destination:
    name: in-cluster
    namespace: default  
  project: test
  source:
    helm:
      valueFiles:
        - ../values/my-values.yaml      
    path: myapp/chart
    repoURL: 'git@gitlab.com:...'
    targetRevision: master
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
```

in my git repository at my chart I have a dependency for another chart that I control too
```
dependencies: 
  - name: myapi
    version: 5.5.0   
    repository: "nexus.registry...."
    alias: myapi
```

I deployed the app using argocd and it worked, I made an small enhancement to myapi helm chart (dependency chart) and push to my repository (nexus) I deleted the previous app in argocd and when I try to redeploy it its not using the latest dependency chart

I think it pull the dependency the first time and is using that in cache to create the app again

is there a way to force and alway pull the dependency? or how can I force argocd to pull the dependency again?
