### DISCUSSION TITLE
Unsuccessful HTTP response: template 'main-workflow' type is unknown

### DISCUSSION THREAD

**Discussion by paalped** [argoproj/argo-cd#7149] [Q&A]
Hello,

I am a new to argo, with no prior experience before creating this template. I wonder how to fix the following error which occurs when I click +CREATE in the UI:

```Unsuccessful HTTP response: template 'main-workflow' type is unknown```

This is my workflow template:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: update-data
  namespace: my-namespace
  generateName: update-data-
spec:
  serviceAccountName: update-data
  entrypoint: main-workflow
  arguments:
    parameters:
      - name: image
        value: >-
          myimage-repository:version
  templates:
    - name: main-workflow
      containerSet:
        containers:
          - name: step-1
            image: '{{workflow.parameters.image}}'
            command:
              - python3
            args:
              - /home/app/main.py
              - '-s'
              - 1
          - name: step-2
            image: '{{workflow.parameters.image}}'
            dependencies: ["step-1"]
            command:
              - python2
            args:
              - /home/app/main2.py
              - '-t'
              - test.db
              - '-f'
              - test
              - '-s'
              - 1
      outputs:
        artifacts:
          - name: out
            path: /home/app/output
```
