### DISCUSSION TITLE
argocd-dex session timeout?

### DISCUSSION THREAD

**Discussion by MikeK184** [argoproj/argo-cd#7168] [Q&A]
Hi there, I've been trying to configure the dex.config of `argocd-cm` but can't seem to get it right, as the argocd.token that my User gets expires only if the session ends. 
![image](https://user-images.githubusercontent.com/56921065/132235992-ae67f92e-a4db-433a-a4cd-9da6a4020f3f.png)

I've tried a couple of ways to set the expiry date/time but unfortunately the expiry date never changes. My knowledge of dex is very limited so I've been just trying Expiry settings I've found on the dex documentation. My dex.config in `argocd-cm `looks like this:

```
  dex.config: |
    connectors:
      - type: ldap
        id: ad
        name: Active-Directory
        config:
          host: XXX
          insecureSkipVerify: true
          bindDN: XXX
          bindPW: $ldap.bindPW
          expiry: 
            idTokens: "5m"
            deviceRequests: "2m"
            signingKeys: "1m"
            refreshTokens:
              absoluteLifetime: "5m"
          userSearch:
            baseDN: XXX
            filter: "(objectClass=person)"
            username: userPrincipalName
            idAttr: DN
            emailAttr: mail
            nameAttr: sn
          groupSearch:
            baseDN: XXX
            filter: "(objectClass=group)"
            userAttr: DN
            groupAttr: member
            nameAttr: cn
```
