### DISCUSSION TITLE
Service "web-service" is invalid: spec.clusterIPs[0] error

### DISCUSSION THREAD

**Discussion by r3econ** [argoproj/argo-cd#7174] [Q&A]
I can see an error in Argo when I try to update one of my services. It says:
```
error when replacing "/dev/shm/705844359":
Service "web-service" is invalid: spec.clusterIPs[0]:
Invalid value: []string(nil): primary clusterIP can not be unset
```
<img width="986" alt="Screenshot 2021-09-07 at 18 02 40" src="https://user-images.githubusercontent.com/505054/132376220-42d1a210-0caf-496f-8691-53912d35727f.png">

The yaml file with the manifest is pretty simple:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: smart-me
  name: web-service
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: web
  type: LoadBalancer
```

I tried removing the service and adding it again but I'm still getting the same error. Does anyone know how to solve it?

I use Argo `v2.0.1+33eaf11`
