### DISCUSSION TITLE
Ability to ignore entire resources from Application config

### DISCUSSION THREAD

**Discussion by etsauer** [argoproj/argo-cd#7272] [Q&A]
I have an Application that manages applies a helm chart containing a Tekton Pipeline. It looks something like this:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-pipeline
  namespace: developer-gitops
spec:
  destination:
    namespace: myapi
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://git.example.com/myapi/pipeline.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
```

When I create the application and allow it to sync, everything looks good, but each time I start the pipeline, resources are generated by tekton (PipelineRuns, TaskRuns, Pods) all of which [have the labels propigated](https://tekton.dev/vault/pipelines-v0.14.3/labels/). When that happens, the Application then reports **out of sync**. I've been trying to mess with the [Compare Options](https://argoproj.github.io/argo-cd/user-guide/compare-options/) and [Diffing Customizations](https://argoproj.github.io/argo-cd/user-guide/diffing/), but neither of them quite give me what I need. The `argocd.argoproj.io/compare-options: IgnoreExtraneous` annotation works in theory, but in practice, I have no mechanism to ensure that Tekton will apply it to the right resources. The `.spec.IgnoreDifferences` settings only seem to work inside of a resource, not on an entire resource.

What I'm looking for is a way to configure the Application to be able to `ignoreResources` using a [label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors). Does this exist? If not, is there another way to accomplish this that I'm not thinking of, or is a feature request appropriate?

**Comment by wanghong230** [comment]
Good question. I am trying to understand why label selector will work while annotation won't? Will you be able to inject the proper label to all the to-be-ignored objects?

**Reply by etsauer** [reply]
no, its not because its a label vs annotation and I have the ability to inject one or the other, it's that the generated resources will have a particular predictable labelset that, if I could set it on the Application I could set something like:

```
spec:
  ignoreResources:
  - group: tekton.dev
    kind: PipelineRun
    selector:
      tekton.dev/pipeline: myapi-pipeline
  - group: tekton.dev
    kind: TaskRun
    selector:
      tekton.dev/pipeline: myapi-pipeline
  - group: tekton.dev
    kind: Pod
    selector:
      tekton.dev/pipeline: myapi-pipeline

```
