### DISCUSSION TITLE
Ingress is not responding when canary deployment in suspended state

### DISCUSSION THREAD

**Discussion by om3171991** [argoproj/argo-cd#7317] [Q&A]
Hi,

We are experiencing downtime for an application while deployment is in a suspended state.

Deployment Strategy - Canary without any traffic management.

Usecase - We have a simple nodejs deployment with 1 replica and whenever we do deployment and it gets to a suspended state, ingress associated with the application shows a blank page. As soon as, we progress and deployment is completed - everything starts working.

RolloutManifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: Demo
  labels:
spec:
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: Demo
      app.kubernetes.io/instance: Demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: Demo
        app.kubernetes.io/instance: Demo
    spec:
      containers:
        - name: demo
          image: "demo:master-890d3f1-4.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
```
Is there anyone experiencing the same or am I doing something wrong?
