### DISCUSSION TITLE
Invalid username or password occured evertime.

### DISCUSSION THREAD

**Discussion by lirlia** [argoproj/argo-cd#7371] [Q&A]
When I login to ArgoCD server via CLI or WebUI ,  admin / password login always failed.

```
# get password
❯ kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
xxxxxx

❯ argocd login --port-forward --plaintext --username admin --password xxxxxx
FATA[0002] rpc error: code = Unauthenticated desc = Invalid username or password 
```

I already tried to reset Initial password (many times) and restart pods(argocd-server)
- https://github.com/argoproj/argo-cd/blob/master/docs/faq.md#i-forgot-the-admin-password-how-do-i-reset-it
 
What can I do for next?

##  ArgoCD version

```
❯ argocd version
argocd: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:07:34Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
```

## Argocd configmap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  kustomize.buildOptions.v3.5.4: --output /tmp
  statusbadge.enabled: "true"
  timeout.reconciliation: 5s
  ui.cssurl: "./custom/my-styles.css"
  #users.anonymous.enabled: "false"
  users.session.duration: "24h"
  # https://argoproj.github.io/argo-cd/operator-manual/health/#argocd-app
  # https://github.com/argoproj/argo-cd/tree/master/resource_customizations
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs
```

### ArgoCD Server log

```
time="2021-10-05T12:48:42Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.claims=null grpc.request.con
tent= grpc.service=version.VersionService grpc.start_time="2021-10-05T12:48:42Z" span.kind=server system=grpc                                                 
time="2021-10-05T12:48:42Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_
time="2021-10-05T12:48:42Z" grpc.time_ms=10.407 span.kind=server system=grpc                                                                                  
time="2021-10-05T12:48:42Z" level=warning msg="User admin failed login 3 time(s)"                                                                             
time="2021-10-05T12:48:43Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or
 password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2021-10-05T12:48:42Z" grpc.time_ms=646.011 span.k
ind=server system=grpc                                                                                                                                                             
```
