### DISCUSSION TITLE
Why "notification service 'discord' is not supported" ?

### DISCUSSION THREAD

**Discussion by kandeshvari** [argoproj/argo-cd#7378] [Q&A] [answered]
I'm trying to setup discord webhook but getting error:

```
time="2021-10-06T11:52:20Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{discord }'" app=argocd/my-service
time="2021-10-06T11:52:20Z" level=error msg="Failed to notify recipient {discord } defined in app argocd/my-service: notification service 'discord' is not supported" app=argocd/my-service
```

my config is:

```
apiVersion: v1
kind: ConfigMap
metadata:
    name: argocd-notifications-cm
data:
    service.webhook.discord: |
        url: https://discord.com/api/webhooks/<my_channel_part>
        headers:
            - name: Content-Type
              value: application/json

    template.app-sync-succeeded: |
        webhook:
            discord:
                method: POST # one of: GET, POST, PUT, PATCH. Default value: GET
                body: |
                    {
                        "username": ": "{{.app.metadata.name}}",
                        "content": " Application {{.app.metadata.name}} is now running new version of deployments manifests.
                            url: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
                            context: continuous-delivery/{{.app.metadata.name}}
                        "
                    }

    trigger.on-sync-succeeded: |
        - description: Application syncing has succeeded
          send:
          - app-sync-succeeded
          when: app.status.operationState.phase in ['Succeeded']
```

app annotation is:

```
notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
```

What I'm doing wrong?
