### DISCUSSION TITLE
Cant config a trafic routing with subset-level trafic spliting with istio

### DISCUSSION THREAD

**Discussion by sanslash332** [argoproj/argo-cd#7414] [Q&A] [answered]
Hello guys,

First of all, thanks for your help.

I'm trying to  config a rollout with a canary deployment strategy and a traficRouting with a subset-level using istio.
I set my virtual service, my destination rule, my service and my rollout following the documentation at https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/
But when I applied the helm chart, argo says that the rollout is invalid because it was specting the stableService and CanaryService parameter on the strategy config, but the documentation says that these fields are for the host-level trafic spliting when you use two service, but not for the subset-level trafic spliting when you use one service and one virtual service. soo... What I am doing wrong?

argo cd version on my k8s cluster: v2.0.0+f5119c0

Here are my yaml files:

rollout.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: portal-users
  labels:
    app: portal-users
    lang: node
    platform: services
    privategroup: portal
spec:
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: null
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: portal-users
            stableSubsetName: stable
          virtualService:
            name: portal-users
            routes:
            - user
            - passcode
  selector:
    matchLabels:
      app: portal-users
  template:
    metadata:
      labels:
        app: portal-users
        lang: node
        platform: services
        privategroup: portal
    spec:
      imagePullSecrets:
        - name: secret
     containers:
        - name: portal-users
          image: "image:tag"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8005
              protocol: TCP
          env:
            - name: "BUILDNUMBER"
              value: "v1"

```

Service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: portal-users
  labels:
    app: portal-users
    lang: node
    platform: services
    privategroup: portal
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8005
      protocol: TCP
      name: http
  selector:
    app: portal-users
```

VirtualService.yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portal-users
  labels:
    app: portal-users
    lang: node
    platform: services
    privategroup: portal
spec:
  gateways:
  - default/global-gateway
  hosts:
  - my.host.com
  http:
  - name: user 
    match:
    - uri:
        prefix: /users
    rewrite:
      uri: /v1/users
    route:
    - destination:
      host: portal-users
      port:
        number: 80
      subset: stable
      weight: 100
    - destination:
      host: portal-users
      port:
        number: 80
      subset: canary
      weight: 0
  - name: passcode 
    match:
    - uri:
        prefix: /pass
    rewrite:
      uri: /pcode
    route:
    - destination:
      host: portal-users
      port:
        number: 80
      subset: stable
      weight: 100
    - destination:
      host: portal-users
      port:
        number: 80
      subset: canary
      weight: 0

```

and last, the destinationRule.yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: portal-users
  labels:
    app: portal-users
    lang: node
    platform: services
    privategroup: portal
spec:
  host: portal-users
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:        # labels will be injected with canary rollouts-pod-template-hash value
      app: portal-users
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:        # labels will be injected with stable rollouts-pod-template-hash value
      app: portal-users

```

The error that argo throws when apply these files:

    Message:               The Rollout "portal-users" is invalid: spec.strategy.stableService: Invalid value: ""
: Canary service and Stable service must to be set to use Traffic Routing                                                

sorry for the long post. I dont know how to proceed

thanks
