### DISCUSSION TITLE
RabbitMQ k8 cluster with ArgoCD

### DISCUSSION THREAD

**Discussion by DrGreenthumbz** [argoproj/argo-cd#7427] [Q&A]
Hello everyone! I have two questions:

1. Can a RabbitMQ Kube cluster be successfully managed through ArgoCD? I fail to find any resources or discussions on this subject. Makes me feel like everyone in the world knows something obvious that I'm missing.

2. Since I am already using Argo with RabbitMQ, I found out that every time something gets commited in GIT for Argo, regardless of the app, it makes the RabbitMQ pods to restart/rebuild and a new controllerrevision gets created and attached to the cluster. Is there any way to stop this? I wouldn't want messages to get lost every time a colleague commits a change on whatever other app we have in Argo.

I think that this is due to the rolling update strategy we have on RMQ. Can we keep it and address the second point in some other way?

Thank you in advance!

**Comment by taufiqpsumarna** [comment]
It looks like you've encountered an issue with RabbitMQ in an ArgoCD Application, where auto-sync with pruning enabled is causing unwanted deletions and resource recreation. Disabling prune in the sync policy resolved the issue by preventing ArgoCD from removing existing components (e.g., Pods) upon every commit.

If prune: true, ArgoCD might be deleting and recreating resources, try disabling prune in the sync policy:
```
syncPolicy:
  automated:
    prune: false
    selfHeal: true
```

Currently I'm using [RabbitMQ Bitnami Helm Chart (15.0.6)](https://artifacthub.io/packages/helm/bitnami/rabbitmq/15.0.6) and I've been testing my configuration and it's works, now if there any new commit inside repository, RabbitMQ won't prune existing component inside in this example is POD

![image](https://github.com/user-attachments/assets/0e754121-554e-470f-a0ca-1086212ea387)

![image](https://github.com/user-attachments/assets/aa20bf41-2ee7-46b2-8599-48559801b42b)

**Comment by taufiqpsumarna** [comment]
**UPDATE 17 February 2025**

I added this configuration
```
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: rabbitmq
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/volumeClaimTemplates
```

This is my ArgoCD Application manifest file:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: rabbitmq-staging
spec:
  project: staging
  source:
    repoURL: https://git.example.net/rabbitmq.git
    targetRevision: HEAD
    path: helm/rabbitmq
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m0s
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: rabbitmq
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/volumeClaimTemplates
  revisionHistoryLimit: 5
```

**Reply by igotinfected** [reply]
In my case simply adding

```yaml
ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: rabbitmq
      jsonPointers:
        - /spec/template/metadata/annotations
```

solved my issue, I didn't need to switch off pruning. Thanks!
