### DISCUSSION TITLE
pass value file to override helm value

### DISCUSSION THREAD

**Discussion by calvinShan** [argoproj/argo-cd#7495] [Q&A]
Hello, 
I want to pass the file value.yaml to helm value.yaml  in order to override all the values in helm

How to pass a complet file to helm to override all the values in helm exactly?
```
spec:
  destination:
    namespace: argocd
  source:
    path: Charts/test
    repoURL: repo
    targetRevision: version
    helm:
      valueFiles:
        - values-dev.yaml
```
 In this example, the file values-dev.yaml is in the Chart helm, but I want to pass the file from argocd to helm      
Thanks
