### DISCUSSION TITLE
How to pass helm parameter with dots to deployment.

### DISCUSSION THREAD

**Discussion by ayeks** [argoproj/argo-cd#7662] [Q&A]
Hey,

I searched quite a bit to solve this parameter passing issue for Argo and Helm. My use case is the prometheus-operator deployment where you have to define the [ingress annotations of the AWS ALB](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/) in the [values.yam of the prometheus-operator](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml).

The working values.yaml looks like this:

```yaml
kube-prometheus-stack:
  grafana:
    enabled: false

  prometheus:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/group.name: k8s-cluster
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
```

That deployment works flawless, the ingress annotations are set correctly. However, I want to define the parameter `alb.ingress.kubernetes.io/group.name` dynamically in the Argo Application CR, based on the kubernetes cluster name which is defined in the config.

So lets pass the `group.name` as helm parameter:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus-operator
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: prometheus-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: "kube-prometheus-stack.prometheus.ingress.annotations.\"alb.ingress.kubernetes.io/group.name\""
          value: {{ .Values.custom_data.k8s_cluster_name }}
        - name: "kube-prometheus-stack.prometheus.ingress.hosts[0]"
          value: "prometheus.{{ .Values.custom_data.k8s_cluster_name }}.{{ .Values.custom_data.dns_zone }}"
```

This is the `custom_data` section of my overall yaml:

```yaml
custom_data:
    dns_zone: &dns_zone domain.local
    k8s_cluster_name: &k8s_cluster_name k8s-cluster
```

The result is `error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string`:

```text
rpc error: code = Unknown desc = `helm template . --name-template prometheus-operator --namespace prometheus-operator --kube-version 1.21 --set kube-prometheus-stack.prometheus.ingress.annotations."alb.ingress.kubernetes.io/group.name"=k8s-cluster --set kube-prometheus-stack.prometheus.ingress.hosts[0]=prometheus.k8s-cluster.domain.local

...

 --include-crds` failed exit status 1: Error: YAML parse error on prometheus-operator/charts/kube-prometheus-stack/templates/prometheus/ingress.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string Use --debug flag to render out invalid YAML
```

I tried these combinations for passing the helm parameter via Argo which all failed or did not overwrite the correct parameter:

```
- can be parsed by helm, but does not overwrite the correct parameter:
  - name: "\"kube-prometheus-stack.prometheus.ingress.annotations.\"alb.ingress.kubernetes.io/group.name\"\""
  - name: 'kube-prometheus-stack.prometheus.ingress.annotations."alb.ingress.kubernetes.io/group.name"'
  - name: "kube-prometheus-stack.prometheus.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/group\\.name"
- is resolved as invalid yaml:
  - name: "kube-prometheus-stack.prometheus.ingress.annotations.\"alb.ingress.kubernetes.io/group.name\""
  - name: "kube-prometheus-stack.prometheus.ingress.annotations.alb.ingress.kubernetes.io/group.name"
  - name: "kube-prometheus-stack.prometheus.ingress.annotations.'alb.ingress.kubernetes.io/group.name'"
  - name: "kube-prometheus-stack.prometheus.ingress.annotations.alb\.ingress\.kubernetes\.io/group\.name"
```

How can I pass the key correctly with Argo?

Thanks a lot for your support!
Best regards

**Comment by ayeks** [comment]
Implemented a workaround by using cluster specific `value.yaml` files instead of overwriting individual helm parameters. Example for kube2iam:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube2iam
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube2iam
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kube2iam
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - "../values-{{ .Values.custom_data.k8s_cluster_name }}.yaml"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
```

Sidenote: I see more and more issues arising which are also discussed in the multi cluster issue: https://github.com/argoproj/argo-cd/issues/1673 Lets see how we proceed from here.
