### DISCUSSION TITLE
cannot create argocd application with helm

### DISCUSSION THREAD

**Discussion by kimhongji** [argoproj/argo-cd#7827] [Q&A]
when I add application using UI, the rpc error occurred. like this 
(of course I set the helm value file)
```
helm template . --name-template <template name> --namespace <namespace> --kube-version 1.17 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions argoproj.io/v1alpha1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1beta1 --api-versions cilium.io/v2 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions dkosv3.9rum.cc/v1alpha1 --api-versions domain.dkosv3.9rum.cc/v1alpha1 --api-versions events.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions metrics.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions v1 --include-crds
```
so I tried to add application using yaml resource  like below, then I succeed to add application.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: {{ .Values.namespace }}
spec:
  project: app
  source:
    repoURL: <repo>
    path: <path>
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/values.yaml
  destination:
    server: '{{ .Values.cluster.server }}'
    namespace: logging
  {{- if eq .Values.cluster.syncPolicy true}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  {{- end}}
```

I think, when I use UI, the value file is gone..  why the yaml file was success and the UI was failed ?
