### DISCUSSION TITLE
Automate autosync disable on child app of seed app

### DISCUSSION THREAD

**Discussion by DmytroDrachov** [argoproj/argo-cd#7842] [General]
Hey there,

I am pretty sure it's correct behaviour, but I would like to double check or possibly found workaround that my case.
So here is what I have:
1. Seed app which crated manually 
```
project: default
source:
  repoURL: '***'
  path: argo
  targetRevision: development
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated:
    prune: true
```
2. We create child apps and put them in argo folder. e.g.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-4452-monolith
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: '***'
    targetRevision: development
    path: envs/env-name
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: env-name
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```
3. Sometimes we would like to debug/develop some stuff exactly on env and use okteto to replace existing deployment manifest.
4. Since auto sync is enabled for child app it's state changed to out of sync
5. We need to update git repo first to disable auto sync for that app and then will be able to debug/develop

I've tried to use `argocd app patch app-name --grpc-web --patch='[{"op":"remove", "path":"/spec/syncPolicy/automated"}]' --type json` but after sometime it enable auto sync back cause seed(parent) app detects out of sync as well and this is looks correct.

Q: Is there a way to ignore changes made manually to child app by seed app?

**Comment by DmytroDrachov** [comment]
Resolved with on seed application
```
ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
      - /spec/syncPolicy
```
