### DISCUSSION TITLE
How do I add a repository with the `--insecure-skip-server-verification` flag in Helm?

### DISCUSSION THREAD

**Discussion by toast-gear** [argoproj/argo-cd#7864] [Q&A] [answered]
You can add a repository with the `--insecure-skip-server-verification` flag to disable SSL checks. I haven't been able to figure out how to do this however when adding a repository via Helm.

https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_repo/

I'm not super familiar with ArgoCD (starting to learn it), I'm not super sure which CRD this would be relevant for

I've tried searching the Application and AppProject CRD for anything vaguely in that area and couldn't find anything

**Comment by geowalrus4gh** [comment, marked as answer]
Here is a sample for OCI registry with insecure using declarative mode.
```
apiVersion: v1
kind: Secret
metadata:
  name: harbor-oci-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  insecure: "true"
  name: "harbor-oci-repo"
  password: "<pwd>"
  type: helm
  url: "<domain>"
  username: "<user>"
```
