### DISCUSSION TITLE
Application syncing itself ?

### DISCUSSION THREAD

**Discussion by eddycharly** [argoproj/argo-cd#7908] [Q&A] [answered]
Is this possible to have an application syncing itself ?
The application will be a child of itself ? Can ArgoCD cope with this ?

**Comment by kostis-codefresh** [comment, marked as answer]
That is exactly what auto-sync does https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/

**Reply by eddycharly** [reply]
Hey 👋 
I understand auto sync, the question is more about the parent/child relationship, as a self updating application would be both the parent and the child at the same time.
I wonder if this is something completely supported by argocd 🤔

**Reply by kostis-codefresh** [reply]
If you enable auto-sync you already have a self-updating application. Every time you change anything in Git, the application will detect it and auto-deploy. 

If that doesn't work in your case, please elaborate.

**Reply by eddycharly** [reply]
> If you enable auto-sync you already have a self-updating application

Not exactly, the application does not update itself, it updates the resources owned by the application. My question is really about the application manifest being part of the application.

Let's say i have this app in argo:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 5
  source:
    repoURL: <git repository url>
    path: .bootstrap # the app manifest is stored in the .bootstrap folder of the remoter git repository
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

And i have the manifest above stored in the github repo in the `.bootstrap` folder.
Now the app in argocd will self reference itself (as the content of the repo defines the application that is tracking it).

It's the app of apps pattern, applied to the same app being the parent and the child.

**Reply by kostis-codefresh** [reply]
I understand the scenario you describe, but I don't understand WHY you need this scenario to work. Let's say for a moment that this scenario that you describe worked out of the box with ArgoCD. What would you gain from this? WHY have this parent/child relationship of the same app in the first place?

What went wrong with the basic/usual scenario?

1. You have your application manifests somewhere (deployments, secrets, services what ever)
2. You have another manifest like the one that you have described above. In the "repo URL" you point to the application manifest resources
3. You commit everything in Git (same repo, different repos or whatever you prefer)

And then anytime you change anything on the application manifests, the app auto-updates and deploys.
What didn't work with this simple scenario in your application and forced you to ask if you could have a parent/child relationship with the app itself? Does your application have any special requirements that are not covered by the basic scenario above?

**Reply by eddycharly** [reply]
My scenario is that the root application points to an helm chart, and the helm chart has some files in it.
Based on the files present in the helm chart, the root app has to mutate to take those files as `valueFiles`.

Something like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
    # ...
    helm:
      valueFiles:
        {{- range $path, $_ := .Files.Glob "secrets/*.enc.yaml" }}
        - {{ $path }}
        {{- end }}
```

Another option would be to have another app responsible of updating the root app.
But I wondered if i could simply let the root app sync itself from the content of the manifests generated by the helm chart.
