### DISCUSSION TITLE
Error when creating a New App

### DISCUSSION THREAD

**Discussion by Remmzz** [argoproj/argo-cd#7993] [Q&A] [answered]
I am trying to follow this demo for a research exercise: https://www.katacoda.com/vikas-poddar-slalom/scenarios/session-09-lab3-gitops-argocd.
I've done the previous lab as required and completed it with no hassle. I have also performed the steps to install ArgoCD in the cluster, portforward & connect with the ArgoCD UI and successfully connected with the GIt repo. I can't seem to create the app though, as it keeps giving me this error message:

_Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = workloads: app path does not exist_

What am I missing? Do I need to manually create the path for the app to launch?

**Comment by chetan-rns** [comment, marked as answer]
@Remmzz I suspect the path provided in the application does not exist. Please check if the path specified at `.spec.source.path` actually exists in your git repository.

**Reply by todaywasawesome** [reply]
@Remmzz The answer from @chetan-rns is correct. In the exercise you linked, you must create your own git repo and then clone in the example repos. In step 3, you then must replace the example URLs shown and provide your own git repos. The example repos are not public and so you cannot reference them. They are meant to be replaced with your own repos.

**Reply by brandonros** [reply]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-dashboard
  project: kubernetes-dashboard
  source:
    repoURL: https://github.com/kubernetes/dashboard.git
    targetRevision: 42deb6b32a27296ac47d1f9839a68fab6053e5fc
    path: ./aio/deploy/helm-chart/kubernetes-dashboard/
```

https://github.com/kubernetes/dashboard/tree/42deb6b32a27296ac47d1f9839a68fab6053e5fc/aio/deploy/helm-chart/kubernetes-dashboard

Says it doesn't exist, hmm...
