### DISCUSSION TITLE
An application never becomes Unhealthy or Degraded

### DISCUSSION THREAD

**Discussion by RomanBats** [argoproj/argo-cd#8035] [Q&A] [answered]
I am trying to understand how health check works with ArgoCD application.

I have created and deployed a simple API (service+deployment) that responds well (200) for 20 minutes and then responds 400 for 10 minutes.

After I deploy it, the application becomes "healthy", after 20 minutes, when health checks start to receive 400 responses, the application transitions to "Progressing" state, and never to anything else (unless it becomes healthy again).

![progressing-argocd](https://user-images.githubusercontent.com/5024978/147391211-3c8a8023-7b8a-4630-a19a-754a16bdc2f6.png)

Could you please tell me whether I am missing something? I would expect the application to become unhealthy or degraded with this behavior.

Here is my health checks configurations:
``` yaml
startupProbe:
  failureThreshold: 5
  httpGet:
    path: /tests/success # always returns 200
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
livenessProbe:
  failureThreshold: 1
  httpGet:
    path: /tests/fail?min=20&forMin=10 # returns 200 for 20 minutes and then 400 for 10 minutes
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
readinessProbe:
  failureThreshold: 1
  httpGet:
    path: /tests/fail?min=20&forMin=10 # returns 200 for 20 minutes and then 400 for 10 minutes
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
```
Argo CD - v2.2.1+122ecef
