### DISCUSSION TITLE
my own values.yaml selectable from a helm repo

### DISCUSSION THREAD

**Discussion by 1mfaasj** [argoproj/argo-cd#8045] [Q&A]
I have a question about using Argocd.
I use helm charts to do my deployments and have some custom values.yaml associated with certain helm charts. I saved it to my Github repository.

For example, as a repository I added https://truecharts.org. Now I'm trying to create an application, and I can select a values.yaml at the bottom. However, this is the values.yaml from the 'maker' so to speak.

can't I add my own Github repository here and select my own values.yaml in it?

Of course I can fork the entire chart to my own Github repository but I'd rather not do this every time the chart is updated...

**Comment by RomanBats** [comment]
Usually, you don't need to override all default values from the target chart because defaults are meaningful for most cases. So when you define ArgoCD application, you can override specific values (or all values if you will) from that chart right in the application definition ('values' property):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-discovery
spec:
  destination:
    name: in-cluster
    namespace: istio-system
  source:
    repoURL: https://truecharts.org
    targetRevision: 1.0
    chart: target-chart
    helm:
      valueFiles:
        - values.yaml
      values: |
        global:
          logAsJson: true
        meshConfig:
          defaultConfig:
            holdApplicationUntilProxyStarts: true
          accessLogFile: '/dev/stdout'
          accessLogEncoding: 'JSON'
```
If this does not suit you, you might try using [some kind of 'inheritance'](https://helm.sh/docs/helm/helm_dependency/) of Helm charts specifying your target chart as a dependency.
