### DISCUSSION TITLE
Pass specific nested json to ArgoCD Application helm attributes

### DISCUSSION THREAD

**Discussion by Coder63** [argoproj/argo-cd#8072] [Q&A] [answered]
Hi team , we are running v2.1.7 ..

We have app of apps pattern parent AppD which trigger multiple child apps like AppD1,AppD2,AppD3 etc... 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: AppD1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aqueduct
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: AppD1
    repoURL: <gitlab>
    targetRevision: {{ .Values.app_revision_to_track }}
    helm:
      values: |
        AppD: {{ toJson .Values.AppD }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
```

We pass all the values for AppD1, AppD2,AppD3,AppD4 etc from single values file.. 

```
AppD:
    var1: value1
    var2: value2
    var3: value3
    AppD1:
        foo1: bar1
        foo2: bar2
        foo3: bar3
    AppD2:
        foo1: bar1
        foo2: bar2
        foo3: bar3
    AppD3:
        foo1: bar1
        foo2: bar2
        foo3: bar3 
```

I tried to pass only AppD1 specific values to helm and it did get passed to child app (able to see inner json passed to values)  but the  deployment /resource doesn't see the values / inherit it..  

```
  helm:
      values: |
        AppD.AppD1: {{ toJson .Values.AppD.AppD1 }}
```

Is there any know bug/ limitation  around this ?

**Comment by RomanBats** [comment, marked as answer]
I might have misunderstood the question, but I don't think you need to convert it to JSON:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: AppD1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aqueduct
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: AppD1
    repoURL: <gitlab>
    targetRevision: {{ .Values.app_revision_to_track }}
    helm:
      values: |
        AppD:
          AppD1:
{{ toYaml .Values.AppD.AppD1 | indent 12 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
```
As a result, you should have something like this:
```yaml
AppD:
  AppD1:
    foo1: bar1
    foo2: bar2
    foo3: bar3
```

But I would assume that you don't need to have AppD nor AppD1 in values of your target app, so passing plain values would suffice:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: AppD1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aqueduct
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: AppD1
    repoURL: <gitlab>
    targetRevision: {{ .Values.app_revision_to_track }}
    helm:
      values: |
{{ toYaml .Values.AppD.AppD1 | indent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
```

**Reply by Coder63** [reply]
@RomanBats  : Thanks for the lead. This worked :D . I have to limit to only appD1  per application so this worked. 

```
    helm:
      values: |
        AppD:
          AppD1:
{{ toYaml .Values.AppD.AppD1 | indent 12 }}
```
