### DISCUSSION TITLE
Add cluster behind jump host (x509: certificate signed by unknown authority)

### DISCUSSION THREAD

**Discussion by robertbublik** [argoproj/argo-cd#8112] [Q&A]
Hello,

I have the following setup:

Server A (intranet): k3s server running ArgoCD
Server B (intranet): Jump host running a nginx Docker container acting as a reverse proxy
Server C: On-premise k3s server

What I want is to deploy my software through server B on server C (this setup already works with Azure DevOps pipelines).
However I'm not sure how to apply the necessary changes to the ArgoCD Helm chart.

What I did:

```
global:
  hostAliases:
    - ip: "xx.xx.xx.xx"
      hostnames:
        - "xxx.xx"
repoServer:
  configs:
    clusterCredentials:
    - name: xxx
      server: https://xxx.xxx:xxx
      labels: {}
      annotations: {}
      config:
        tlsClientConfig:
          insecure: false
          caData: Server C certificate-authority-data from kubeconfig autogenerated through k3s
          certData: Server C client-authority-data from kubeconfig autogenerated through k3s
          keyData: Server C client-key-data from kubeconfig autogenerated through k3s
```
This setup causes the error x509: certificate signed by unknown authority.

I also added Server C's crt and key to Server B's nginx site entry. Before I received the error "x509: certificate is valid for $intranet-CN but not $onprem-CN.
Unfortunately I'm still in the process of learning how certificates work and I'm not sure what the problem is exactly and how to fix it. I imagine the  ArgoCD repo-server doesn't trust Server B?

Help would be greatly appreciated.
