### DISCUSSION TITLE
Boolean template value substitution

### DISCUSSION THREAD

**Discussion by brunocascio** [argoproj/argo-cd#8194] [Q&A] [answered]
Hey folks! I'm trying to customize the value of prune and selHeal depending on the environment I'm deploying to, but I cannot be able to interpolate boolean values. Could someone help me, please?

My manifest looks like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-www
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: nonprod
            selfHeal: true
            prune: true
          - environment: ppd
            cluster: nonprod
            selfHeal: true
            prune: true
          - environment: prod
            cluster: prod
            selfHeal: true
            prune: false
  template:
    metadata:
      name: 'myapp-www-{{environment}}' 
    spec:
      project: "myapp-www"
      source:
        repoURL: https://myrepo.com/web/myapp-deployment.git
        targetRevision: HEAD
        path: '.deploy'
      destination:
        name: '{{cluster}}'
        namespace: 'myapp-www-{{environment}}'
      syncPolicy:
        automated:
          prune: '{{prune}}'
          selfHeal: '{{selfHeal}}'
        syncOptions:
          - CreateNamespace=true
```

Thanks in advance for the help and for this amazing product!

**Comment by ishitasequeira** [comment, marked as answer]
@brunocascio this is a known issue. The issues you could track

1. https://github.com/argoproj/applicationset/issues/424
2. https://github.com/argoproj/applicationset/issues/287

You could try removing the single quotes around the values:
from
 ```
         prune: '{{prune}}'
         selfHeal: '{{selfHeal}}'
```
to 
```
      prune: {{prune}}
      selfHeal: {{selfHeal}}
```

**Reply by brunocascio** [reply]
> 

Hi @ishitasequeira Thanks for your reply :)

Since I'm using kustomize, I need to use quotes, as @jemag commented here https://github.com/argoproj/applicationset/issues/424#issuecomment-993634519

**Comment by stephaneetje** [comment]
Hello, i have the same problem, i'm using helm and can't find a way to pass a boolean. Validator always throw an error:
```
Unable to save changes: ApplicationSet.argoproj.io "ciam" is invalid: spec.template.spec.syncPolicy.automated.prune: Invalid value: "string": spec.template.spec.syncPolicy.automated.prune in body must be of type boolean: "string"
```

This is what i tried  (which is working for the other params with string expected):
```
      syncPolicy:
        automated:
          prune: {{`{{prune}}`}}
```

**Comment by nathan-bowman** [comment]
I'm running into the same issue, looking forward to a fix.

**Comment by vl-kp** [comment]
i am using kubectl, i got error on client `error: error parsing tenant-3.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".app.prune":interface {}(nil)}`

**Comment by alita1991** [comment]
Hi, is there any workaround for this issue? I have the same problem, I need to set the skipCrds flag to true/false

**Reply by EladAviczer** [reply]
Same here :(
`invalid: spec.template.spec.source.helm.skipCrds: Invalid value: "string": spec.template.spec.source.helm.skipCrds in body must be of type boolean: "string"`

**Reply by wumaxd** [reply]
fixed it (using Helm) with the following:

```yaml
  templatePatch: |
    spec:
      source:
        helm:
          skipCrds: {{`{{ .skipCrds }}`}}
```
and `.skipCrds` as a parameter in `generators.list.elements[]`

**Comment by theJaxon** [comment]
I'm also facing the same issue, any working solutions ?

**Reply by pc-tzimmerman** [reply]
Use multiple ApplicationSets. Or [Parameter Overrides](https://argo-cd.readthedocs.io/en/stable/user-guide/parameters/).

**Comment by EladAviczer** [comment]
acutally they state here that it is not possible
https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/#limitations
Hope they will add it soon.

**Comment by wumaxd** [comment]
If you applying the setup via kustomize or from a Helm Chart to ArgoCD , you can "trick" the system by overriding it via the patch (not nice but it works): https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#template-patch

Specific example (kustomize):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-www
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: nonprod
            selfHeal: true
            prune: true
          - environment: ppd
            cluster: nonprod
            selfHeal: true
            prune: true
          - environment: prod
            cluster: prod
            selfHeal: true
            prune: false
  template:
    metadata:
      name: 'myapp-www-{{environment}}' 
    spec:
      project: "myapp-www"
      source:
        repoURL: https://myrepo.com/web/myapp-deployment.git
        targetRevision: HEAD
        path: '.deploy'
      destination:
        name: '{{cluster}}'
        namespace: 'myapp-www-{{environment}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{ .prune }}
          selfHeal: {{ .selfHeal }}
```

Specific example (Helm):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-www
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: nonprod
            selfHeal: true
            prune: true
          - environment: ppd
            cluster: nonprod
            selfHeal: true
            prune: true
          - environment: prod
            cluster: prod
            selfHeal: true
            prune: false
  template:
    metadata:
      name: 'myapp-www-{{environment}}' 
    spec:
      project: "myapp-www"
      source:
        repoURL: https://myrepo.com/web/myapp-deployment.git
        targetRevision: HEAD
        path: '.deploy'
      destination:
        name: '{{cluster}}'
        namespace: 'myapp-www-{{environment}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{`{{ .prune }}`}}
          selfHeal: {{`{{ .selfHeal }}`}}
```

For Helm you need the extra {{\`...\`}}
