### DISCUSSION TITLE
"Configure plugin via sidecar" => config management plugin not supported. plugin name cmp-plugin

### DISCUSSION THREAD

**Discussion by pmorch** [argoproj/argo-cd#8216] [Q&A] [answered]
Hi,

I have [Configure plugins via Argo CD configmap](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#configure-plugins-via-argo-cd-configmap) working, but I can't figure out how to [Configure plugin via sidecar](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#configure-plugin-via-sidecar).

I keep getting this in the logs from the repo-server container:

    msg="finished unary call with code Unknown" error="config management plugin not supported. plugin name cmp-plugin"

 and the gui shows this for the applied application:

    rpc error: code = Unknown desc = config management plugin not supported. plugin name cmp-plugin

## Details

I first apply this config map (as per the docs):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      generate:
        command: [sh, -c, 'echo "{\"kind\": \"ConfigMap\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"$ARGOCD_APP_NAME\", \"namespace\": \"$ARGOCD_APP_NAMESPACE\", \"annotations\": {\"Foo\": \"$FOO\", \"KubeVersion\": \"$KUBE_VERSION\", \"KubeApiVersion\": \"$KUBE_API_VERSIONS\",\"Bar\": \"baz\"}}}"']
      discover:
        find:
          command: ["touch", "/tmp/plugin-discover-has-run"]
      allowConcurrency: true
      lockRepo: true
```

(I modified the `discover` field because I wasn't sure if that was the problem and so I could see if it was ever called. I've never seen a `/tmp/plugin-discover-has-run` file)

I then install argocd like this:

    helm upgrade -n argocd --install argocd --version 3.30.0 --values my-values.yaml argo/argo-cd

Where `my-values.yaml` is:

```yaml
global:
  image:
    imagePullPolicy: Always
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    hosts:
      - argocd.local.example.com
repoServer:
  extraContainers:
  - name: cmp
    command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
    image: busybox # This can be off-the-shelf or custom built image
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml # Plugin config file can either be volume mapped or baked into image
        subPath: plugin.yaml
        name: cmp-plugin
      - mountPath: /tmp
        name: tmp-dir
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
configs:
  secret:
    # htpasswd is in "apt install apache2-utils", but lets not
    # require installation of apache2-utils to create the non-secret
    # "admin" password
    # htpasswd -bnBC 10 "" admin  | tr -d ':\n' && echo
    # $2y$10$MtWvAKK4na9lNmQWSEHmo.7Zy7B26mZ2af0LhJ8scEcuw3PSzBokK
    argocdServerAdminPassword: "$2y$10$MtWvAKK4na9lNmQWSEHmo.7Zy7B26mZ2af0LhJ8scEcuw3PSzBokK"
```

(I had to change the volume-name `tmp` to `tmp-dir` to match the helm chart).

And then I apply this application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-cmd-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pmorch/monitorfiles
    path: .
    targetRevision: HEAD
    plugin:
      name: cmp-plugin
      env:
      - name: FOO
        value: myfoo
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
```

I think I'm sticking very close to the docs.

I expect this to work. The application shows up, but it has an error:

    rpc error: code = Unknown desc = config management plugin not supported. plugin name cmp-plugin

Why can't it find the cmp-plugin?

I do see this in the logs from the `cmp` container:

    time="2022-01-19T01:55:20Z" level=info msg="argocd-cmp-server v2.2.2+03b17e0 serving on /home/argocd/cmp-server/plugins/cmp-plugin-v1.0.sock"

And I do have the `/home/argocd/cmp-server/config/plugin.yaml ` file in the cmp container:

```bash
/ $ ls -l /home/argocd/cmp-server/config/plugin.yaml 
-rw-r--r--    1 root     root           554 Jan 19 01:55 /home/argocd/cmp-server/config/plugin.yaml

/ $ cat /home/argocd/cmp-server/config/plugin.yaml 
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: cmp-plugin
spec:
  version: v1.0
  generate:
    command: [sh, -c, 'echo "{\"kind\": \"ConfigMap\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"$ARGOCD_APP_NAME\", \"namespace\": \"$ARGOCD_APP_NAMESPACE\", \"annotations\": {\"Foo\": \"$FOO\", \"KubeVersion\": \"$KUBE_VERSION\", \"KubeApiVersion\": \"$KUBE_API_VERSIONS\",\"Bar\": \"baz\"}}}"']
  discover:
    find:
      command: ["touch", "/tmp/plugin-discover-has-run"]
  allowConcurrency: true
  lockRepo: true
```
