### DISCUSSION TITLE
Deleted jobs by TTL controller show application as "Out of Sync"

### DISCUSSION THREAD

**Discussion by v0l** [argoproj/argo-cd#8247] [Q&A]
I have some jobs which use `ttlSecondsAfterFinished` to delete the job after completion, but now those jobs are showing as "Missing" because they are deleted.

Is this something that ArgoCD can detect and mark the application as in sync?

**Comment by chetan-rns** [comment]
Hi @v0l, how is the Job created? is it created by a Hook? 

Hook deletion policies can be found here: at https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies

**Reply by v0l** [reply]
Hi @chetan-rns, its just a regular job, I tried using the hooks but found that those jobs run every sync which wasn't going to work for me.

I want the job to run only when it needs to, I.E when the spec changes it should sync and run the job again.

**Reply by todaywasawesome** [reply]
I don't think you answered how the job is created. 

Also for the sync hooks, you can add boolean checks to your job to cancel it when not needed. Might be better?

**Comment by cmpilato** [comment]
I see the same thing.  In my case the Job is defined as a resource:

```yml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: some-job
  namespace: some-namespace
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: some-service-account
      containers:
        ...
```

My job runs on each Sync, then 30 seconds after it finishes its pod is cleaned up and Argo starts to complain that about it being Missing and Out of Sync.  How do I tell Argo that this is _intentional_?

**Reply by TalhaNaeem101** [reply]
> I see the same thing. In my case the Job is defined as a resource:

@todaywasawesome @chetan-rns 
It is correct that hooks are fine when we have to delete our jobs right after they are successful (in case of hook-succeed annotation). There are two deviations from this: 
1- What if we need  to keep our succeeded jobs for 30 minutes (as I need to see its logs). TTl option is suitable for this but argocd applications get outOfSync.
2- On every sync of the argocd application, the hooked job also runs, while there's no change in it's specs/config
I am looking for some solution for the first problem. If you wanna share any useful insights on this, please do share. would be highly grateful.

**Comment by djhoese** [comment]
Any other ideas for how to get around this issue? For any maintainers finding this, this is a standard way of having `Job` resources deployed and then cleaned up afterward:

https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

I was hoping the `IgnoreExtraneous` would fix this for me, but it sounds like that didn't help you @cmpilato?

**Reply by cmpilato** [reply]
It did not.

**Comment by zopz** [comment]
I was able to get this working (for all intents and purposes) with the following:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

When a sync is ran, it will spawn the job and remove it directly after. Unfortunately this won't respect the TTL defined in the job configuration, as Argo seems to only check the actual job status, but for me that was not a deal breaker. 

@v0l 
> I want the job to run only when it needs to, I.E when the spec changes it should sync and run the job again.

I've unfortunately got nothing for you there, their hooks appear to be tied directly to the sync action itself, with no concept of resource state :-\

I agree that would be a great feature to have, though. Along with `argocd.argoproj.io/hook-delete-policy` respecting the `ttlSecondsAfterFinished` of the object it's looking to remove.
