### DISCUSSION TITLE
use Role for remote cluster

### DISCUSSION THREAD

**Discussion by quentinalbertone** [argoproj/argo-cd#8296] [Q&A]
Hello,

Is there a way to "control" a remote cluster with `ServiceAccount + Role + RoleBinding` instead of `ServiceAccount + ClusterRole + ClusterRoleBinding`.
I know that when I declare the secret which contain the credentials to the remote cluster (https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters) I can add a field `namespaces` but I would like to use a `Role` instead of this field. Is it possible ? in the pipe ?

Thanks

**Comment by meln5674** [comment]
Kubernetes RBAC doesn't operate by "using a role", it operates by using service accounts (plus other types of users), the roles just say what that service account can do. If you have a remote cluster configured to use a service account bearer token for its credentials, then argocd will have all roles and cluster roles bound to that service account across all namespaces, there's no limit to how many you can bind or how many namespaces they can be bound in.

There's nothing stopping you from creating a service account, giving its token to argocd, and setting up all of the roles and rolebindings in each of the namespaces you want argocd to have access to. If you try to create an app with a cluster-scoped resource, or a resource in a namespace without an appropriate binding, argocd's request will fail with a permission error from the remote cluster's api server.

**Comment by quentinalbertone** [comment]
Thanks for your answer @meln5674,
I already tried with a `ServiceAccount` bind to a `Role` instead of a `ClusterRole` and I got an error telling me that argocd was looking for a cluster role. I could have done something wrong, if it's not to much could you try on your side and tell me if it works ?

**Reply by meln5674** [reply]
Without seeing the exact error message, it'd be hard to tell what's going wrong. Would you mind posting it, or a redacted version of it if it contains any sensitive names or such? Are you sure your app isn't trying to _create_ a ClusterRole?

**Reply by quentinalbertone** [reply]
You're right I will do it the proper way, I have a lot to do but as soon as I have the time I will post : the version of argocd, the error message (and check the helm chart I tried to deploy, that's a good question)

**Comment by gnanaseka-gajendiran** [comment]
@quentinalbertone @meln5674 

I would like to active this discussion .. I have remote cluster with namespace access I want to add the remote cluster using role and role binding .. but argocd trying to get so many permission .. 

Example:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: mcpd
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["networking.istio.io"]
  resources: ["workloadgroups"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["replicationcontrollers"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["limitranges"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

```

I came with above list based on the argocd error but it's looking for below permissions like

PodTemplate, ControllerVersion, khstates.comcast.github.io and so on but I am unable to permission to those resources for my serviceaccount
