### DISCUSSION TITLE
(Help) Use Github OAuth on ArgoCD using dex

### DISCUSSION THREAD

**Discussion by DucretJe** [argoproj/argo-cd#8316] [Q&A] [answered]
**Kubelet**: v1.22.5+k3s1
**argo-cd**: argo-cd:2.2.3-debian-10-r3
**dex**: bitnami/dex:2.30.2-debian-10-r60

Hi,

I want to use Github OAuth on ArgoCD, so I followed [this documentation](https://argo-cd-docs.readthedocs.io/en/latest/operator-manual/sso/#1-register-the-application-in-the-identity-provider) and this [one](https://argo-cd-docs.readthedocs.io/en/latest/operator-manual/sso/#1-register-the-application-in-the-identity-provider).

So after creating my OAuth app in Github, I modified the values of my deployed ArgoCD chart (bitnami/argo-cd 3.0.1):

```yaml
values:
      dex:
         enabled: true
      server:
        url: "https://argocd.xxx.xx"
        config:
          dex.config: |
            connectors:
              - type: github
                id: github
                name: GitHub
                config:
                  clientID: xxx
                  clientSecret: "{{ oapp_token }}"
                  redirectURI: 'https://argocd.xxx.xx/api/dex/callback'
```

The deployment running, I can see the dex pod created but it never starts:

```sh
NAME                                    READY   STATUS    RESTARTS        AGE
argo-cd-dex-7795ffc9b5-m5krb            0/1     Running   12 (28s ago)    25m
```

Pod description [here](https://gist.github.com/DucretJe/19d94f1b06a3af8570c284b2da707fb5)
It seems that the Liveness & Readiness probes never go to OK
The logs from dex pod don't help me:

```plain
time="2022-01-29T09:33:33Z" level=info msg="0xc00093a420 subscribed to settings updates"
time="2022-01-29T09:33:33Z" level=info msg="config issuer: https://argocd.xxx.xx/api/dex"
time="2022-01-29T09:33:33Z" level=info msg="config storage: memory"
time="2022-01-29T09:33:33Z" level=info msg="config static client: Argo CD"
time="2022-01-29T09:33:33Z" level=info msg="config static client: Argo CD CLI"
time="2022-01-29T09:33:33Z" level=info msg="config connector: github"
time="2022-01-29T09:33:33Z" level=info msg="config skipping approval screen"
time="2022-01-29T09:33:33Z" level=info msg="config refresh tokens rotation enabled: true"
time="2022-01-29T09:33:33Z" level=info msg="keys expired, rotating"
time="2022-01-29T09:33:33Z" level=info msg="keys rotated, next rotation: 2022-01-29 15:33:33.275584879 +0000 UTC"
time="2022-01-29T09:33:33Z" level=info msg="listening (telemetry) on 0.0.0.0:5558"
time="2022-01-29T09:33:33Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2022-01-29T09:33:33Z" level=info msg="listening (grpc) on 0.0.0.0:5557"
```

I'm running out of idea, do you see something I missed?
