### DISCUSSION TITLE
"Failed to resync revoked tokens" after reploying redis

### DISCUSSION THREAD

**Discussion by yatishg17** [argoproj/argo-cd#8352] [General]
Can any body help to resolve this error, this error is comming after redploying redis pod. Sync is failing 

ComparisonError: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.43.15.14:8081: connect: connection timed out"

Below error is on argo-cd server.
evel=warning msg="Failed to resync revoked tokens. retrying again in 1 minute: dial tcp 10.43.17.160:6379: i/o timeout

**Comment by pasha-codefresh** [comment]
Hi, default redis address is argocd-redis:6379 or you can override it inside 

```
configMapKeyRef:
              key: redis.server
              name: argocd-cmd-params-cm
              optional: true
```

Could you please check that redis is up and running for you?

**Reply by yatishg17** [reply]
thanks, i tried override manually but still same error on argo-cd server
level=warning msg="Failed to resync revoked tokens. retrying again in 1 minute: dial tcp 10.43.177.160:6379: i/o timeout"

i see redis also running fine on container

PID   USER     TIME  COMMAND
    1 redis     3:01 redis-server *:6379
   31 redis     0:00 /bin/sh

**Comment by lamenawuer** [comment]
+1 I have exactly the same error using the latest argocd helm chart version... any redis connection timeouts from any pod. I have no notwork policies or other restrictions

**Comment by LinuxSuRen** [comment]
I got the same error with `v2.10.6`.

> It works well after deleting the `NetworkPolicy`.

**Comment by ktzsolt** [comment]
I restarted argo-cd-dex deployment, no joy.
then restarted argo-cd-app-controller deployment, no joy.
then restarted argo-cd-server deployment and all is good now.

I would guess the argo-cd-server deployment restart fixed based on the logs. It looks like as if once redis is down and comes back online then argo-cd-server can not recconnect to it.

For redis I use existing secret with this config:
```yaml
redis:
  auth:
    existingSecret: argocd-passwords
    existingSecretPasswordKey: redis-password
```
With the helm chart bitnami/argo-cd 6.0.14 https://artifacthub.io/packages/helm/bitnami/argo-cd/6.0.14

Argo CD v2.10.8+37b1cf5
