### DISCUSSION TITLE
Enable ResourceQuota only for one namespace.

### DISCUSSION THREAD

**Discussion by kmaounis** [argoproj/argo-cd#8361] [Q&A]
I would like to enable the ResourceQuota only for one namespace because is a playground namespace and should restrict the resources there. 

Inside the argocd-project file we define 
```

  namespaceResourceBlacklist:
#    - group: ''
#      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
```

But can I only use something like:
```
  namespaceResourceBlacklist:
   - group: ''
     kind: ResourceQuota
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: 'ResourceQuota'
      namespace: 'playground'
```
