### DISCUSSION TITLE
Application referencing project default which does not exist

### DISCUSSION THREAD

**Discussion by cari-lynn** [argoproj/argo-cd#8402] [Q&A]
Hey! I was trying to deploy a simple Application with automatic sync, but the default project doesn't exist.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: argocd
spec:
  project: default
  # this sync policy will deploy the app without confirmation when changes are detected
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/vmware-tanzu/carvel-simple-app-on-kubernetes.git
    targetRevision: develop
    path: config-step-1-minimal

  destination:
    server: https://kubernetes.default.svc
```
1. install argocd (and wait until the resources have been applied)
2. Deploy the app `kubectl apply --namespace argocd -f simple-app-application.yml`
3. Get status via `argocd app get simple-app`

The Condition reports that the `default` project doesn't exist.
```
application.argoproj.io/simple-app created
➜  simple-app git:(develop) ✗ argocd app get simple-app
Name:               simple-app
Project:            default
Server:             https://kubernetes.default.svc
Namespace:
URL:                http://localhost:64019/applications/simple-app
Repo:               https://github.com/vmware-tanzu/carvel-simple-app-on-kubernetes.git
Target:             develop
Path:               config-step-1-minimal
SyncWindow:         Sync Allowed
Sync Policy:        Automated
Sync Status:        Unknown
Health Status:      Unknown

CONDITION         MESSAGE                                                       LAST TRANSITION
InvalidSpecError  Application referencing project default which does not exist  2022-02-06 22:04:49 -0800 PST
```

If I wait a few minutes, the Application does end up syncing successfully.

I was following the [docs](https://argo-cd.readthedocs.io/en/latest/user-guide/projects/) that say the `default` project is automatically created.
> Every application belongs to a single project. If unspecified, an application belongs to the default project, which is created automatically and by default, permits deployments from any source repo, to any cluster, and all resource Kinds. 

Since there is initially an `InvalidSpecError`, it appears as though there is an issue. To avoid this should I create the AppProject manually so that it is available right away in my case?

**Comment by chetan-rns** [comment]
Hi @jannfis @alexmt, to avoid this issue should we check if the `default` project has been created for the readiness probe of the application controller? Currently, it seems like the readiness probe will always succeed.
https://github.com/argoproj/argo-cd/blob/d0cbb1597ca8b93cae081e01c07c5c2e74f580d4/controller/appcontroller.go#L193

**Comment by MalibuKoKo** [comment]
Hello,

I have the same issue using [server.additionalApplications](https://github.com/argoproj/argo-helm/blob/argo-cd-4.5.8/charts/argo-cd/values.yaml#L1225) params from [Argo CD Chart values file](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml).

Without automatic sync, application stuck in error: **InvalidSpecError - Application referencing project default which does not exist**.

If i declare this project into [server.additionalProjects](https://github.com/argoproj/argo-helm/blob/argo-cd-4.5.8/charts/argo-cd/values.yaml#L1258) parameter i have an other error: **ComparisonError - rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.96.206.124:8081: connect: connection refused"**

It's a little frustrating, deploy an app during Argocd installation fall immediately in error.

**Comment by nastacio** [comment]
Are you able to see the project in the Argo UI while the `Application` is reporting that issue?

**Comment by cari-lynn** [comment]
In case it helps - I did fix this by applying the default AppProject along with my other configuration. I used this in my [blog](https://carvel.dev/blog/argocd-carvel-plugin/#create-and-template-an-application-with-the-ytt-plugin) post. I was not using the UI, just the core version.
```
---
# this manually creates the default project
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
```

**Reply by crenshaw-dev** [reply]
Keep in mind that this project has extremely open permissions which should be necessary for almost every application.

**Comment by vyom-soft** [comment]
I would like to create another project name & not the default. I tried via crd. I see the same error "Application referencing project myproj which does not exist".

**Comment by iam-veeramalla** [comment]
+1 ran into same issue

**Comment by nthienan** [comment]
experiencing the same error @vyom-soft

**Comment by GeorgiDimv** [comment]
+1 ran into same issue

**Comment by piavgh** [comment]
in my case, I forgot to add the AppProject declaration inside `kustomization.yaml`

**Comment by behniafb** [comment]
Same case. 
I want to deploy all my OTHER AppProjects using an ApplicationSet, but all of my generated Applications give this error:
```
Application referencing project default which does not exist
```

**Comment by joebowbeer** [comment]
Should a docs issue be created and pointed to this discussion?

The [docs](https://argo-cd.readthedocs.io/en/latest/user-guide/projects/) says the default project is created automatically, but that clearly is not happening, as least for ApplicationSet.

Furthermore, the docs say that if a project is not specified then the default project is used, but the project field seems to be required in the ApplicationSet template.

**Comment by stufently** [comment]
any solution? time to time get this error, when run manual sync

**Comment by cmoulliard** [comment]
This issue still exist with new version of Argocd no matter if you create application(s) pointing to a new project or the `default`

This what I do 
```
cat << EOF | kubectl applyf -f -
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: cmoullia
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-app
  namespace: cmoullia
spec:
  destination:
    name: in-cluster
  project: guestbook
  source:
    path: apps
    repoURL: https://github.com/ch007m/my-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
 ```
but got this error reported by the `Application` CR EVEN if the AppProject is well created
```
status:
  conditions:
  - lastTransitionTime: "2024-12-11T09:11:00Z"
    message: Application referencing project guestbook which does not exist
    type: InvalidSpecError
  health:
    status: Unknown
  sync:
    status: Unknown
```
