### DISCUSSION TITLE
Adding ignoreDifferences Application config to 'helm-dependency' format

### DISCUSSION THREAD

**Discussion by brsolomon-deloitte** [argoproj/argo-cd#8411] [Q&A]
We use (for lack of a better name) the "helm dependency" pattern as shown at https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency.

This is basically a lightweight fork of an upstream Helm chart where we optionally modify a small subset of values.yaml.

Quick example:

```bash
$ cat Chart.yaml 
apiVersion: v2
appVersion: 1.9.1
dependencies:
- name: eck-operator
  repository: https://helm.elastic.co
  version: 1.9.1
description: 'A Helm chart for deploying ...'
name: eck-operator
type: application
version: 0.1.0
```

In this case values.yaml is empty; we are just using the defaults:

```
$ cat values.yaml 
# empty
```

We point ArgoCD to this (it sits in a private Git repo) and it works great.

However, we would like to find a way to keep `spec.ignoreDifferences` for the ArgoCD Application in Git. For eck-operator this should be:

```yaml
spec:
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
```

**Where specifically (what file) should this be kept in Git? Is it possible to specify only `ignoreDifferences` without specifying the other fields of `argoproj.io/v1alpha1/Application`?** I thought this is what `.argocd-source.yaml` was for, but apparently I am misinterpreting the docs.
