### DISCUSSION TITLE
Is it right time to do some changes to stable install manifests for ArgoCD?

### DISCUSSION THREAD

**Discussion by samyak-jn** [argoproj/argo-cd#8467] [Ideas]
Hi, :taco: 

I wanted to bring this up for discussion, since, whenever a user starts to work with ArgoCD they go to the documentation, and start playing around. 
But here is one of the issues, that got me stuck (it was a quick fix but can be solved in the manifests as well). I wanted to use the stable version of ArgoCD which I pull from  https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml.
While applying these changes, 
I was stuck on issues like: 

```bash
error: error validating "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml": error validating data: ValidationError(Service.spec.ports[0]): missing required field "protocol" in io.k8s.api.core.v1.Service.spec.ports; if you choose to ignore these errors, turn validation off with --validate=false
error: error validating "install_argocd.yaml": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): missing required field "protocol" in io.k8s.api.apps.v1.Deployment.spec.template.spec.containers.ports, ValidationError(Deployment.spec.template.spec.containers[0].ports[1]): missing required field "protocol" in io.k8s.api.apps.v1.Deployment.spec.template.spec.containers.ports, ValidationError(Deployment.spec.template.spec.containers[0].ports[2]): missing required field "protocol" in io.k8s.api.apps.v1.Deployment.spec.template.spec.containers.ports]; if you choose to ignore these errors, turn validation off with --validate=false
```

which is due to not having, `protocol: TCP` which should be defined in *.spec.containers.ports or *Service.spec.ports. 
Let's take one minor example here:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
  name: argocd-redis
spec:
  ports:
  - name: tcp-redis
    port: 6379
+   protocol: TCP
    targetPort: 6379
  selector:
    app.kubernetes.io/name: argocd-redis
---
```
Also, I agree at some point that this is not necessary because Kubernetes by default assumes, but like (~1%) of people might be using a minimal version of it, or something, where it would be GOOD to have as a best practice.

I'm open to some more suggestions on this^^
