### DISCUSSION TITLE
"argocd-server --insecure": executable file not found in $PATH: unknown

### DISCUSSION THREAD

**Discussion by yatakoi** [argoproj/argo-cd#8520] [Q&A]
I used this documentation https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ingressroute-crd to add ingressroute.

In this documentation wrote:
```
The API server should be run with TLS disabled. Edit the argocd-server deployment to add the --insecure flag to the argocd-server command.
```

Okay. I editing the argo-server deployment `$ kubectl edit deployment argocd-server` and in string #57 I added `--insecure` flag.
```
     40       affinity:
     41         podAntiAffinity:
     42           preferredDuringSchedulingIgnoredDuringExecution:
     43           - podAffinityTerm:
     44               labelSelector:
     45                 matchLabels:
     46                   app.kubernetes.io/name: argocd-server
     47               topologyKey: kubernetes.io/hostname
     48             weight: 100
     49           - podAffinityTerm:
     50               labelSelector:
     51                 matchLabels:
     52                   app.kubernetes.io/part-of: argocd
     53               topologyKey: kubernetes.io/hostname
     54             weight: 5
     55       containers:
     56       - command:
     57         - argocd-server --insecure
     58         env:
     59         - name: ARGOCD_SERVER_INSECURE
     60           valueFrom:
     61             configMapKeyRef:
     62               key: server.insecure
     63               name: argocd-cmd-params-cm
     64               optional: true
```

After editing pod argocd-server fails with error:
```
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process ca │
│ used: exec: "argocd-server --insecure": executable file not found in $PATH: unknown
```

Would you please help me? Thank you.

**Comment by chetan-rns** [comment]
Hi @yatakoi, can you please try adding the insecure flag as a separate element

```yaml
- command:
  - argocd-server
  - --insecure 
```

**Reply by yatakoi** [reply]
> 
Hi @chetan-rns. It's work! Thank you! )

**Reply by PyDataBlog** [reply]
> Hi @yatakoi, can you please try adding the insecure flag as a separate element
> 
> ```yaml
> - command:
>   - argocd-server
>   - --insecure 
> ```

Hi @chetan-rns 

I tried to patch `argocd-server` deployment with this yaml file via `kubectl patch deployments -n argocd argocd-server --patch-file no-tls.yaml`

```yaml
spec:
  template:
    spec:
      containers:
      - name: argocd-server
      - command:
        - argocd-server
        - --insecure
```

and got this error:

`Error from server: map: map[command:[argocd-server --insecure]] does not contain declared merge key: name`

Any ideas for fixing it?

**Reply by alexmt** [reply]
I think you need to remove extra `-`:

```
      - name: argocd-server
        command:
        - argocd-server
        - --insecure
```

**Reply by PyDataBlog** [reply]
> I think you need to remove extra `-`:
> 
> 
> 
> ```
> 
>       - name: argocd-server
> 
>         command:
> 
>         - argocd-server
> 
>         - --insecure
> 
> ```

So just `- -insecure`?

**Reply by alexmt** [reply]
No, another one. The is extra `-` next to `command:`  . Here is updated snippet:

```
spec:
  template:
    spec:
      containers:
      - name: argocd-server
         command:
        - argocd-server
        - --insecure
```

**Reply by PyDataBlog** [reply]
@alexmt for some reason, even after applying that, my ingress isn't working


```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: argocd.DOMAIN.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
service:
name: argocd-server
port:
name: https
  tls:
  - hosts:
    - argocd.DOMAIN.com
    secretName: argocd-secret

```

How do I enable this part from the logs? 
```bash
enable ingress in the values file `server.ingress.enabled`
```
