### DISCUSSION TITLE
What is the correct way to edit the argocd configmaps?

### DISCUSSION THREAD

**Discussion by spothound** [argoproj/argo-cd#8549] [Q&A]
If I want to add, for example, a local user [as described here](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/) to my argocd service, I have manually modified the [argocd-cm file](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#atomic-configuration) in the cluster and added the role. 

Now I want to make this change persistent even if I update the cluster, this is, made argocd manage its own confirmap. But I found the following:

1. When I go to the argocd application, it appears as synced although I have made manual changes:
![image](https://user-images.githubusercontent.com/15269938/154472184-1971baef-8f25-4b42-9f12-72da5a75df68.png)
![image](https://user-images.githubusercontent.com/15269938/154471458-b46ef060-be14-4d7e-bd22-0b2ac186a7ab.png)
Notice that the desired manifest doesn't match the living one, but argocd say that the resource is synced. 
2. If I add a new manifest in the ArgoCD repository for those configmaps, argoCD complains that the resources are defined twice (because this configmap was already defined in the default files that were automatically generated when installing argo). (The file is called `applicationset-install.yaml`)
3. If I decide to edit this `applicationset-install.yaml` file, I see `# This is an auto-generated file. DO NOT EDIT` at the top of the file, so I guess any change will be overwritten on updates.

I have been searching in the docs but I cannot find anything useful explaining what is the correct approach to update resources defined by argo during the installation without modifying the auto-generated files.

Any help? : )

**Comment by RomanBats** [comment]
In my environment, I install ArgoCD with a [Helm chart](https://github.com/argoproj/argo-helm).
It has a lot of parameters defined in values for [declarative setup](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/), mostly under "configs" property (like adding clusters, repositories etc.)
But in your case, it looks like you would need to use server.config:

```yaml
## Server
server:
  # -- Argo CD server name
  name: server
  # -- Manage ArgoCD configmap (Declarative Setup)
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  configEnabled: true
  # -- [General Argo CD configuration]
  # @default -- See [values.yaml]
  config:
    # Argo CD's externally facing base URL (optional). Required when configuring SSO
    url: https://argocd.example.com
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance


  # -- ArgoCD rbac config ([ArgoCD RBAC policy])
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
  rbacConfig:
    {}
    # policy.csv is a file containing user-defined RBAC policies and role definitions (optional).
    # Policy rules are in the form:
    #   p, subject, resource, action, object, effect
    # Role definitions and bindings are in the form:
    #   g, subject, inherited-subject
    # See https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md for additional information.
    # policy.csv: |
    #   # Grant all members of the group 'my-org:team-alpha; the ability to sync apps in 'my-project'
    #   p, my-org:team-alpha, applications, sync, my-project/*, allow
    #   # Grant all members of 'my-org:team-beta' admins
    #   g, my-org:team-beta, role:admin
    # policy.default is the name of the default role which Argo CD will falls back to, when
    # authorizing API requests (optional). If omitted or empty, users may be still be able to login,
    # but will see no apps, projects, etc...
    # policy.default: role:readonly
    # scopes controls which OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
    # If omitted, defaults to: '[groups]'. The scope value can be a string, or a list of strings.
    # scopes: '[cognito:groups, email]'

  # -- Annotations to be added to ArgoCD rbac ConfigMap
  rbacConfigAnnotations: {}

  # -- Whether or not to create the configmap. If false, it is expected the configmap will be created
  # by something else. ArgoCD will not work if there is no configMap created with the name above.
  rbacConfigCreate: true
```

[This tutorial](https://faun.pub/create-argo-cd-local-users-9e830db3763f) might help.
