### DISCUSSION TITLE
Using Global projects

### DISCUSSION THREAD

**Discussion by agaudreault** [argoproj/argo-cd#8622] [Q&A] [answered]
I am trying to use the global projects documented in https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#configuring-global-projects-v18. However, It seems like the project is not found and I cannot figure out if I have a misconfiguration.

When I call `https://localhost/api/v1/projects/proj1/globalprojects` to check that the project is inherited properly, I get `{}` and `namespaceResourceBlacklist` does not seem to be applied.

The argocd-cm
```yaml
kind: ConfigMap
data:
  globalProjects: |-
    - labelSelector:
        matchExpressions:
          - key: argocd.argoproj.io/project-inherit
            operator: In
            values:
              - global
      projectName: global
...
```

The global project
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global
spec:
  description: Global configuration
  namespaceResourceBlacklist:
    - group: ''
      kind: Pod
```

The project that shoul inherit the config
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: proj1
  labels:
    argocd.argoproj.io/project-inherit: global
...
```
