### DISCUSSION TITLE
PreSync Job didn't got deleted after completion with HookSucceeded deletion policy

### DISCUSSION THREAD

**Discussion by Issacwww** [argoproj/argo-cd#8629] [Q&A]
I have a Job for running some script in the PreSync stage, and need this job to be deleted with HookSucceeded deletion policy,
but the Job and Pod stay after job completion, which block the sync process
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/15892569/156089964-48466a2c-677a-498f-974f-7a3d2a1437a7.png">

attached the job yaml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: xxx
    app: xxx
  name: xxx
  annotations:
    argocd.argoproj.io/hook: PreSync
    helm.sh/hook: pre-upgrade
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    helm.sh/hook-weight: "5"
    argocd.argoproj.io/sync-wave: "5"
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - env: xxx
          image: xxx
          name: xxx
          args: ["xxx"]
          volumeMounts: xxx
          envFrom: xxx
          imagePullPolicy: Always
      restartPolicy: Never
      volumes: xxx
```

getting the following result of `kubectl describe job xxx`

Name:           xxx
Namespace:      xxx
Selector:       controller-uid=cdb67744-214f-4e60-892d-73e43fc710d4
Labels:       xxx
Annotations:   
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: HookSucceeded
                argocd.argoproj.io/sync-wave: 5
                helm.sh/hook: pre-upgrade
                helm.sh/hook-weight: 5
Parallelism:    1
Completions:    1
Start Time:     Mon, 28 Feb 2022 14:45:46 -1000
Completed At:   Mon, 28 Feb 2022 14:46:50 -1000
Duration:       64s
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
...
Pod Template: ...
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  50m   job-controller  Created pod: xxx-p82d9
  Normal  Completed         49m   job-controller  Job completed

why this pod still exist even the container has been killed, am I missing anything?

Thanks for any help
Issacwww
