### DISCUSSION TITLE
Project Roles with group not work

### DISCUSSION THREAD

**Discussion by tsingwang** [argoproj/argo-cd#8631] [Q&A] [answered]
Hi, all:
I use `dex` with `OKTA` oidc for auth.
Close global default policy, and want to use Project Role with group.
My need is not want set policy in global policy, because it need upgrade argocd.
But the group in `AppProject` not with the expected permission in example below.
Also the group `eng_backend` with `read` permission by global config not by `AppProject`.
Need your help, Thanks. 

Global policy:
```
  rbacConfig:
    policy.default: role:''
    policy.csv: |
      p, role:app-readonly, applications, get, */*, allow
      g, eng_backend, role:app-readonly
      g, eng_infra, role:admin
```

AppProject:
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vision
  namespace: argo-cd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: dev
    policies:
    - p, proj:vision:us-dev, applications, *, vision/srs-us-dev, allow
    groups:
    - eng_backend
```
