### DISCUSSION TITLE
ArgoCD x Keycloak

### DISCUSSION THREAD

**Discussion by adyanth** [argoproj/argo-cd#8634] [Q&A] [answered]
I have an ArgoCD installation that I wanted to integrate with Keycloak via OIDC. Setting the below config results in an error while logging in.
```yaml
data:
  oidc.config: |
    name: KeyCloak
    issuer: https://id.domain.com/auth/realms/REDACTED/.well-known/openid-configuration
    clientID: ArgoCD
    clientSecret: REDACTED
  url: https://argocd.adyanth.lan
```

Failed to query provider "https://id.domain.com/auth/realms/REDACTED/.well-known/openid-configuration": 404 Not Found: {"error":"HTTP 404 Not Found"}

Keycloak is hosted on a different environment, not on the k3s cluster where ArgoCD is. It is reachable just fine, and there are other applications using it from the same cluster. And that URL is not a 404. It contains correct JSON response for the realm.
