### DISCUSSION TITLE
Sync wave on rollout

### DISCUSSION THREAD

**Discussion by liorhasson** [argoproj/argo-cd#8678] [Q&A]
Guys,
Is it passible to sync wave **deployments** which are managed under **rollout**? It dons't seems to work!
For example:

```
apiVersion: argoproj.io/v1alpha1   
kind: Rollout
metadata:
  name: rollout-ref-deployment
spec:
  replicas: 2
  workloadRef:                            
    apiVersion: apps/v1
    kind: Deployment
    name: rollout-ref-deployment
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: rollout-canary
  name: rollout-ref-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"     #   <<---------------------
spec:
  replicas: 0 
  selector:
    matchLabels:
      app: rollout-ref-deployment
  template:
    metadata:
      labels:
        app: rollout-ref-deployment
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - containerPort: 8080
 ```           
 
 Of course I've other deployments with different sync wave values, but it looks like all of them are syncing at the same time!
 
 Cheers
