### DISCUSSION TITLE
Customize the autosync timing

### DISCUSSION THREAD

**Discussion by AbhijitPaul2006** [argoproj/argo-cd#8726] [Q&A]
Hi ArgoCD Development team, Is there any way to change the default sync timing? I understand that the default is now 3mins. Any suggestion will be much appreciated! Thank you!

**Comment by todaywasawesome** [comment]
You can change this using the `timeout.reconciliation` value in the `argocd-cm` configmap. 
 
Thanks to @kostis-codefresh for sharing this with me
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
	app.kubernetes.io/name: argocd-cm
	app.kubernetes.io/part-of: argocd
data:
  timeout.reconciliation: 240s
```

More information on this setting is in the docs on scaling https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller
