### DISCUSSION TITLE
ApplicationSet + Kustomize, how to change Ingress host in template

### DISCUSSION THREAD

**Discussion by lukonjun** [argoproj/argo-cd#9042] [Q&A]
Hi there, I am currently setting up branch deployments with argocd, gitlab action and kustomize.   
I am using the new pull request generator (really cool 😃 ). 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: lukonjun
        repo: example-nodejs
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 120
  template:
    metadata:
      name: 'example-nodejs-pr-{{number}}' # or fixed namespace for all environments?
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/lukonjun/example-nodejs-k8s-manifest
        targetRevision: HEAD
        path: env/backend-testing
        kustomize:
          images:
           - 'ghcr.io/lukonjun/example-nodejs:{{head_sha}}-test'
           # Somehow override ingress host and external DNS annotation 
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: example-nodejs-pr-{{number}}
```
In the template I would like to override the ingress host and one annotation (by somehow patching this values) in order to map traffic correctly to the environment. To give an example, if the first PR is created i would like to pass the value `pr-{{number}}-test.example.com`.

Is this somehow possible, or will I need to move to helm (would prefer kustomize because of readability) to do the templating correctly?

**Comment by rishabh625** [comment]
m not sure but may be u can combine pull request generator with https://argocd-applicationset.readthedocs.io/en/stable/Generators-Git/#git-generator-files , based on file content u can set values

**Comment by SelfhostedPro** [comment]
I found out you can. I have the following applicationset:
```yaml
  template:
    metadata:
      name: 'playground-{{branch}}-{{number}}'
    spec:
      destination:
        name: sandbox
        namespace: 'playground-{{branch}}-{{number}}'
      project: playground
      source:
        path: manifests
        plugin:
          env:
            - name: NAMESPACE
              value: 'playground-{{branch}}-{{number}}'
          name: kustomized-helm
        repoURL: 'git@github.com:org/developer-playground.git'
        targetRevision: '{{head_sha}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
 ```
Then in the kustomization.yaml for the app that I needed to be dynamic I setup a configMap generator and a file that defined a blank variable (these get replaced by environment variables) as well as a replacement to take those variables and replace targeted strings with them
ingress.properties:
```
NAMESPACE
```
kustomization.yaml:
```yaml
bases:
  - kowl-ingress.yaml
helmCharts:
- name: kowl
  releaseName: kowl
  repo: https://raw.githubusercontent.com/cloudhut/charts/master/archives
  valuesFile: values.yaml

configMapGenerator: <------
  - name: namespace-var
    env: ingress.properties

replacements: <-----
  - path: namespace-replacement.yaml

generatorOptions:
 disableNameSuffixHash: true
 labels:
   kustomize.generated.resource: "true"
```

namespace-replacement.yaml
```yaml
source:
  kind: ConfigMap
  name: namespace-var
  fieldPath: data.NAMESPACE
  version: v1
targets:
- select:
    name: kowl-ingress
    kind: Ingress
  fieldPaths:
    - spec.rules.0.host
  options:
    delimiter: '.'
    index: 1
    create: true
- select:
    name: kowl-ingress
    kind: Ingress
  fieldPaths:
    - spec.tls.0.hosts.0
  options:
    delimiter: '.'
    index: 1
    create: true
- select:
    name: kowl
    kind: ConfigMap
    version: v1
  fieldPaths:
    - data.config\.yaml
  options:
    delimiter: '.'
    index: 1
    create: true
```
It's definitely not well advertized/documented but will work well for what I'm doing.

**note:** *I'm using a custom plugin for this and passing the variables via the applicationset.*

You can test if it's working by running the following command:
```
NAMESPACE=test kustomize build /path/to/folder
```

**Comment by raebbar** [comment]
If you don't want to create an extra plugin in ArgoCD and an extra ConfigMap you can also work with the commonAnnotations of kustomize.

Add a commonAnnotation for each value you want to pass from ApplicationSet to kustomize. I use `app/param-host` in this example.

ApplicationSet based on the one from @lukonjun 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
  namespace: argocd
spec:
  generators:
  [...]
  template:
    [...]
    spec:
      [...]
      source:
        repoURL: https://github.com/lukonjun/example-nodejs-k8s-manifest
        targetRevision: HEAD
        path: env/backend-testing
        kustomize:
          commonAnnotations:
            app/param-host: pr-{{number}}-test.example.com
          images:
           - 'ghcr.io/lukonjun/example-nodejs:{{head_sha}}-test'
      project: default
      destination:
        [...]
```
We need to configure a [replacement](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) to replace all occurrences of the corresponding parameter, in this example the host.

`replacement-host.yaml`
```
source:
  kind: Ingress
  name: example
  fieldPath: metadata.annotations.app/param-host
targets:
  - select:
      kind: Ingress
      name: example
    fieldPaths:
      - spec.rules.0.host
      - spec.tls.0.hosts.0
  - select:
      kind: Certificate
      name: example-tls-certificate
    fieldPaths:
      - spec.dnsNames.0
```
And add the replacement config to the `kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

...

replacements:
- path: replacement-host.yaml

```
That's all. 

Advantages of this solution:

- no extra configuration of ArgoCD
- no extra plugins for ArgoCD
- no extra kubernetes resources in the deployment

Disadvantages of this solution:

- one annotation per parameter on all resources in the deployment

**Reply by Brad-Newton** [reply]
This is exactly what I need, however it's not working for me.
I haven't got as far as adding the replacements, the commonAnnotations are not being added to the created Application or any of the other resources. Am I missing something? or has there been a change that prevents this from working?

**Reply by raebbar** [reply]
> This is exactly what I need, however it's not working for me. I haven't got as far as adding the replacements, the commonAnnotations are not being added to the created Application or any of the other resources. Am I missing something? or has there been a change that prevents this from working?

Hard to say. Maybe as a first clue. The annotations are not added to the application resource but only to the resources created by kustomization within the source of the application.

Second thought, although unlikely. An outdated ArgoCD. The commonAnnotations for kustomize were added in [ArgoCD v1.8.0](https://github.com/argoproj/argo-cd/releases/tag/v1.8.0).

Otherwise: what does your applicationSet (or application) yaml and your kustomization.yaml (within the application source) look like?

**Reply by Brad-Newton** [reply]
Thank you for replying.

We've got ArgoCD v2.5.7.

My ApplicationSet looks similar to yours above

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ui-adhoc
  namespace: argocd
spec:
  generators:
  - git:
    [...]
  template:
    metadata:
      name: 'ui-adhoc-{{name}}'
    spec:
      project: default
      source:
        repoURL: '[...]'
        targetRevision: adhoc
        path: overlays/dev/ui-adhoc
        kustomize:
          commonAnnotations:
            host-port: '{{host.port}}'
          commonLabels:
            app: 'ui-adhoc-{{name}}'
            aadpodidbinding: 'ui-adhoc-{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: ui-adhocs
      syncPolicy:
      [...]
```
Within the 'overlays/dev/ui-adhoc' folder, there is a kustomization.yaml that only defines namespace and a list of resources (everything else has been removed for now).

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ui-adhocs

resources:
  - resources/service/
  - resources/env-cm.yaml
```
  
The resources/service folder also has a kustomization.yaml file which only lists 2 resources.
None of the deployed resources have the annotations or labels that were defined as common in the ApplicationSet,
until I get those working, I can't add the replacements and then the other resources I'll need.

**Reply by raebbar** [reply]
I see no error, everything looks correct.

**Reply by Brad-Newton** [reply]
Thanks again for trying to help me.

I think I'd had something wrong initially, then after correcting it I hadn't applied the ApplicationSet yaml.
(i.e kubectl apply -n argocd -f ui-adhoc.yaml)
After running this again it now does correctly add the annotations and labels.

**Comment by Inshaal93** [comment]
If you're on Argo `v2.9`+ they've released patches for kustomize so you can do inline patches from `Application` or `ApplicationSet`. 
Here's the docs on it - https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#patches

In your case it would be like this:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
  [...]
  template:
    [...]
      source:
        repoURL: https://github.com/lukonjun/example-nodejs-k8s-manifest
        targetRevision: HEAD
        path: env/backend-testing
        kustomize:
          images:
           - 'ghcr.io/lukonjun/example-nodejs:{{head_sha}}-test'
           # This will override
          patches:
          - target:
              kind: Ingress
              name: my-ingress # you don't need to worry about appending the name
            patch: |-
              - op: replace
                path: spec/hosts/0
                value: pr-{{number}}-test.example.com
             [...]
```
