### DISCUSSION TITLE
ApplicationSet, have the helm.values from a config file

### DISCUSSION THREAD

**Discussion by rgarrigue** [argoproj/argo-cd#9113] [Q&A]
Hi there

I've this AS

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
spec:
  generators:
    - git:
        repoURL: git@gitlab.company.cloud:infrastructure/argo-manifests.git
        revision: HEAD
        files:
          - path: "applications/services/**/config.yaml"
  template:
    metadata:
      name: "{{ name }}"
    spec:
      project: "services"
      source:
        repoURL: "{{ repository.url }}"
        targetRevision: HEAD
        path: "{{ repository.path }}"
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - "{{ repository.values }}"
      destination:
        server: "{{ cluster.url }}"
        namespace: "{{ cluster.namespace }}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
```

And here's a config.yaml

```yaml
name: product-dev-charge-service

repository:
  url: git@gitlab.company.cloud:infrastructure/argo-manifests.git
  path: charts/go-service
  values: values-product-dev-this-service.yaml

cluster:
  url: https://XXXXXXXXXXXXXXXXXXX.sk1.eu-central-1.eks.amazonaws.com
  namespace: backend

```

I wish I could replace the valueFiles by `values: | \n {{ values }}`, with a "values: \n <dict_of_values>" key in my config, so one less file to move around. Tried stuff, didn't worked since ArgoCD was unhappy, marshalling stuff etc. 

Is this possible ? How ?

Bonus question, can I add a {% if values not empty %} around AS's values: key, to avoid an issue if values in the config.yaml is empty (I guess it'll happen)

Best regards !

**Comment by todaywasawesome** [comment]
@rgarrigue Another way to solve this would be to use kustomize to reference the helm charts and the values files to use for each overlay. See this comment https://github.com/argoproj/argo-cd/issues/2789#issuecomment-960271294 and this blog on [directory structures](https://codefresh.io/about-gitops/how-to-model-your-gitops-environments-and-promote-releases-between-them/), and of course [Argo CD Autopilot](https://github.com/argoproj-labs/argocd-autopilot/) which operates this way.

**Comment by akhan23wgu** [comment]
This is what I use. In my argocd application set I configure values as:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: template
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:username/myrepo.git
      revision: HEAD
      files:
      - path: "**/config.yaml"
  template:
    metadata:
      name: '{{name}}' 
    spec:
      destination:
        name: ''
        namespace: '{{app_namespace}}'
        server: '{{address}}'
      source:
        path: ''
        repoURL: '{{helmchart_url}}'
        targetRevision: '{{version}}' 
        chart: '{{name}}'
        helm:
          values: | 
            {{app_values}}
      project: default
```

Then in my `config.yaml` file I have `app_values` listed like so:

```
app_values: |
  image:
    repository: ghcr.io/runatlantis/atlantis
    tag: v0.19.8
    pullPolicy: IfNotPresent
```

This grabs the values I specify in`app_values` and plugs it into helm so I don't need to manage an extra file. Everything I need is contained in `config.yaml`. The downside to this is that you won't be able to do any JSON as kubectl doesn't recognize any of the curly braces when applying `config.yaml`.

**Reply by joebowbeer** [reply]
You can now rewrite this example using multiple values sources, with no dependency on fasttemplate.

Note that in this example the git file generator is only providing a `{{path}}` for valueFiles.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: template
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:username/myrepo.git
      revision: HEAD
      files:
      - path: "**/config.yaml"
  template:
    metadata:
      name: '{{name}}' 
    spec:
      destination:
        name: ''
        namespace: '{{app_namespace}}'
        server: '{{address}}'
      sources:
      - ref: values
        repoURL: git@github.com:username/myrepo.git
        targetRevision: HEAD
      - path: ''
        repoURL: '{{helmchart_url}}'
        targetRevision: '{{version}}' 
        chart: '{{name}}'
        helm:
          valueFiles:
          - $values/{{path}}/config.yaml
      project: default
```
