### DISCUSSION TITLE
ArgoCD application that contains only resource with argocd hooks

### DISCUSSION THREAD

**Discussion by beatrausch** [argoproj/argo-cd#9148] [Q&A]
**Use-Case**: Deploying an ArgoCD application e.g. for ML that contains only a single K8 job with a hook _Sync_ and deletion policy _BeforeHookCreation_ does not apply the job, until any non-hooked resource appears in the application. Is this behavior intended? If yes what would be the best way to update a K8 job – e.g. a kind of job deletion policy?

**Comment by todaywasawesome** [comment]
@beatrausch I think I'm following you. I'm not sure to be honest, it sounds like because there is nothing to sync we don't reach that stage of hook. 

See this comments for tips about deleting jobs https://github.com/argoproj/argo-cd/issues/4295#issuecomment-692980119 

I would try using the replace option for syncing. This will remove and replace the resource. Kubernetes jobs can't be updated to run again, they must be deleted and recreated so I would think replace would work. The hooks are for running jobs _around_ an application update, since all you want to do is run a job I would think an app with the job and a replace option set would work. 

https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes

**Reply by beatrausch** [reply]
> @beatrausch I think I'm following you. I'm not sure to be honest, it sounds like because there is nothing to sync we don't reach that stage of hook.

I would say you got it ;-). Our current ML job uses Apache Spark/Flink which itself creates further resources based on its native controller implementation, thus we just need the job to trigger our submit call. 

> I would try using the replace option for syncing. This will remove and replace the resource. Kubernetes jobs can't be updated to run again, they must be deleted and recreated so I would think replace would work. The hooks are for running jobs _around_ an application update, since all you want to do is run a job I would think an app with the job and a replace option set would work.
> 
> https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes

Unfortunately, pure replace does not work for k8 jobs, it requires `--force` option while running `kubectl replace`, which is not supported by argocd sync options so far. Right now, force is only supported via the argocd UI. 

A workaround we are thinking about, is to deploy a second cleanup job as `PreSync Hook` that runs a` kubectl delete` on the real deployment job. The cleanup job itself uses the hooks-delete-policy `BeforeHookCreation`.

**Comment by ghost** [comment]
@beatrausch - I ran into the same issue. To get around it, I basically added a dummy Deployment that does nothing except trick ArgoCD into thinking it needs to finish the Sync.

**Comment by tomikonio** [comment]
Hi, having the same problem but with a `PreSync` hook, any updates/solutions?

**Comment by divyangjp** [comment]
I found a workaround which works for the `job` only resource type. 
 - Using helm chart with a `job` and a dummy `configmap`
 - Job with `argocd.argoproj.io/hook: PostSync` and `argocd.argoproj.io/hook-delete-policy: HookSucceeded` annotations
 - Job with `metadata` `generateName`
 - dummy configmap has a data field which populates using `job`'s docker image tag (in our case, new job is dependent on new docker image tag)
 - Application with `Replace=true`
 
With this setup, everytime new `job` docker container image is updated, the `configmap` gets updated as well which triggers `PostSync` hook. 

Example Configmap

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-tag
data:
  job_docker_tag: {{ .Values.image.tag }}
```

Partial example of Job resource template

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Chart.Name }}-
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
```

**Reply by tomoyaogura-ph** [reply]
Thanks for the workaround. This came in handy for our use case. For my configmap though, I took a checksum of my entire values object since I wanted to ensure the hook triggered if I changed any content of my values.yaml (Like my resource requests, etc). 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-values-hash
data:
    values-yaml-hash: "{{ .Values | toYaml | sha256sum }}"
```
