### DISCUSSION TITLE
Can not find working example for Argo Notifications

### DISCUSSION THREAD

**Discussion by lukonjun** [argoproj/argo-cd#9243] [Q&A]
Hi, I am currently following the guide (https://blog.argoproj.io/notifications-for-argo-bb7338231604) from @alexmt however can not make it work. I am not installing the notifications controller as it is part of the argocd helm chart (argo-cd-4.5.4 v2.3.3) I am using. I am setting up the secret 
```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  email-username: <email>
  email-password: <passowrd>
type: Opaque
```
And also the Config Map according to the guide by patching the created resource with
```
kubectl patch cm argocd-notifications-cm -n argocd --type merge -p '{"data": {"service.email.gmail": "{ username: $email-username, password: $email-password, host: smtp.gmail.com, port: 465, from: $email-username }" }}'
```
I create the argo application and expect a trigger to be triggered and an alert send
```
kubectl apply -n argocd -f - << EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: $EMAIL_USER
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc/
  project: default
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
EOF
```
However when deploying I do no get an email and even more important the logs of the applications controller do not convey any informations to me that a trigger was triggered
```
k logs argocd-notifications-controller-74f96dfd46-nxpfl -f
time="2022-04-28T13:08:18Z" level=info msg="Start processing" resource=argocd/guestbook
time="2022-04-28T13:08:18Z" level=info msg="Trigger on-sync-succeeded result: []" resource=argocd/guestbook
time="2022-04-28T13:08:18Z" level=info msg="Processing completed" resource=argocd/guestbook
time="2022-04-28T13:08:18Z" level=info msg="Start processing" resource=argocd/guestbook
time="2022-04-28T13:08:18Z" level=info msg="Trigger on-sync-succeeded result: []" resource=argocd/guestbook
time="2022-04-28T13:08:18Z" level=info msg="Processing completed" resource=argocd/guestbook
```
Any recommendation how I can further debug here, I would really like to get this going, am I missing a silly point or miss reading the logs?

Or is there any other tool I can use to make it transparent to my developers what is happening in the cluster and when an Argo Application has successfully updated?
