### DISCUSSION TITLE
Where should I put the postsync yaml?

### DISCUSSION THREAD

**Discussion by chillybug** [argoproj/argo-cd#9314] [Q&A] [answered]
Hi, I'm new here, trying to build CI/CD pipeline using GitHub actions and ArgoCD.
FYI, I have only superficial knowledge about k8s. 

I've setup below (works fine);
1. Source repository having helm chart
2. Service repository having jobs to build & push docker image to docker repository
3. `2` updates docker image's tag into `1`
4. ArgoCD App to be sync with source repository

I wanted to execute simple curl cmd when app sync is complete, so I've created PostSync job yaml like below;
```
apiVersion: batch/v1
kind: Job
metadata:
  name: api-test-trigger
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        name: api-test
    spec:
      containers:
      - name: api-test
        args:
            - /bin/sh
            - -ec
            - "curl -X POST ~~~~"
        env:
          - name: GITHUB_URL
            value: "~~~"
          - name: GITHUB_TOKEN
            value: "~~~"
        image: curlimages/curl
      restartPolicy: Never
```

**But I have no idea where should I put this file.**

1. I've tried to create batch job on Kubernetes
===> Pod api-test-~~~ had been created, run, terminated immediately, but never run again when app sync is completed.
```
$ kubectl create -f postsync.yaml -n argocd
job.batch/api-test-trigger created
```
2. Put yaml file into the `source repository` which has helm chart
===> Job never been created.
