### DISCUSSION TITLE
How to sync the helm chart dir without `Chart.yaml`

### DISCUSSION THREAD

**Discussion by yidongw** [argoproj/argo-cd#9315] [General]
`helm template` or `helmfile template` will generate directories and charts without `Chart.yaml`

for example
`helmfile template --output-dir-template $(pwd)/gitops//{{.Release.Namespace}}`
will generate the following directories structure.

```
gitops/traefik/
└── traefik
    └── templates
        ├── dashboard-hook-ingressroute.yaml
        ├── deployment.yaml
        ├── rbac
        │   ├── clusterrole.yaml
        │   ├── clusterrolebinding.yaml
        │   └── serviceaccount.yaml
        └── service.yaml

3 directories, 6 files
```
there is no `Chart.yaml`

So when I create an application chart like this
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  source:
    path: gitops/traefik/traefik/
    repoURL: git@gitlab.com:org/me/helm-charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
`traefik` will not be properly installed.

I have been googling around and trying to find the answer but I couldn't find it.

Can argocd support installing the sub-charts without `Chart.yaml`? Or do I have to manually create that one by one?
