### DISCUSSION TITLE
Replace healthy pods

### DISCUSSION THREAD

**Discussion by shyam-ks** [argoproj/argo-cd#9346] [Q&A]
Right now if an unhealthy pod gets deployed it doesn't replace the healthy ones. The new pod goes into a degraded state and the old pod will be still running. Is there any way to replace the healthy pods with new pods, even if the new pods are failing? 
We wanted this on the dev environment. 

Current sync policy
```
  syncPolicy:    
    automated:
      prune: true
      selfHeal: true
```
Thanks in advance
