### DISCUSSION TITLE
Configure CMP via sidecar: error="Manifest generation error: plugin sidecar failed. Couldn't find cmp-server plugin supporting repository .env/dev/workloads/my-app"

### DISCUSSION THREAD

**Discussion by azamora-zsc** [argoproj/argo-cd#9384] [Q&A] [answered]
Hi,
 I'm taking this other discussion as a reference: https://github.com/argoproj/argo-cd/discussions/8216

In my case, I also had my plugin working using the [ConfigMap](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#option-1-configure-plugins-via-argo-cd-configmap) option. Now I need to change this and configure my CMP via a sidecar like [this](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#option-2-configure-plugin-via-sidecar).

The plugin is in this case a tool developed by us that needs to access the code in the git repository to work properly. I have done several tests trying to make this sidecar approach work but I keep getting the following error:

`time="2022-05-12T13:06:56Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error: plugin sidecar failed. Couldn't find cmp-server plugin supporting repository .env/dev/workloads/my-app" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2022-05-12T13:07:56Z" grpc.service=repository.RepoServerService grpc.start_time="2022-05-12T13:06:56Z" grpc.time_ms=1.087 span.kind=server system=grpc `

### Details
Versions:
- ArgoCD Helm chart version: 4.5.10
- ArgoCD version: 2.3.3

Plugin configuration. As you can see, I've used the same trick of "touching" a file in */tmp* to see if the plugin is called, and returning always a non-error code as mentioned in the documentation.  
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: configurator-plugin
spec:
  version: v1.0.1
  generate:
    command: [sh, -c, 'configurator generate --all -o yaml']
  discover:
    find:
      command: ["touch", "/tmp/plugin-discover-has-run"]
  allowConcurrency: true
  lockRepo: false
```
The file in */tmp* it's created and everything looks good to me. Here some relevant log entries in the sidecar container (cmp) logs:
```
time="2022-05-12T12:39:56Z" level=info msg="touch /tmp/plugin-discover-has-run" dir=/tmp/_argocd-repo/6c8a95fe-5267-41f7-9bea-719063be6cda/env/dev/workloads/my-app execID=21591
time="2022-05-12T12:39:56Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=MatchRepository grpc.request.deadline="2022-05-12T12:40:55Z" grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2022-05-12T12:39:56Z" grpc.time_ms=0.683 span.kind=server system=grpc 
```
Here the sidecar definition added repo server deployment:
```yaml
repoServer:
  extraContainers:
    - name: cmp
      command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
      image: my-registry.url/configurator-plugin:v1.0
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /tmp
        name: tmp-dir
```
And finally an application using the plugin:
```yaml
project: config-management
source:
  repoURL: 'git@github.com:myorg/repo-config.git'
  path: env/dev/workloads/my-app
  targetRevision: HEAD
  plugin: {}
destination:
  server: 'https://XXXXXXXX.xxx.eu-central-1.eks.amazonaws.com'
  namespace: monitoring
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
```
I'm following the documentation to the letter and I can't find a solution for this situation. Something that is calling my attention is that all the examples (I couldn't find many) use an *echo* instruction to generate the manifests, so they are almost useless in real life, where the plugin binary will probably depend on the source code in the cloned repository.

Can anybody help with this issue? Maybe we can use this discussion to get a more complete example that other people can use in case of a need to use a sidecar for configuring a CMP. (I read that this could be the only option in the future).

Thanks in advance.

**Last-minute update:**
If I remove the */tmp* volume mount as I read in the documentation, then something similar to [this](https://github.com/argoproj/argo-cd/issues/9382) happens.
