### DISCUSSION TITLE
ApplicationSet PullRequest Generator ignore Dependabot

### DISCUSSION THREAD

**Discussion by lukonjun** [argoproj/argo-cd#9418] [Q&A]
Hi, I am using the PullRequest Generator for Feature Branch deployments and this works really well, for every new pull request an argo application is created. Developers in my Company use Dependabot intensively which runs on a weekly interval and creates often up to 20 PRs per Repo. Is there a way to ignore the PRs from Dependabot? 

This is my Configuration
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend-webapp-testing
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: xxxxxxxx
        repo: frontend-webapp
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 120
  template:
    metadata:
      name: 'frontend-webapp-pr-{{number}}'
      annotations:
        notifications.argoproj.io/subscribe.app-sync-status.slack: argo-notifications
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: xxxxx
        targetRevision: HEAD
        path: chart/example-web-app
        helm:
          parameters:
          - xxxxxxxxx
          valueFiles: 
          - xxxxxxxxx
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: frontend-webapp-pr-{{number}}
```
I know that there is the option to only create Applications when there is a specific label, (Docs: https://argocd-applicationset.readthedocs.io/en/stable/Generators-Pull-Request/). 
```
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - preview
```
However this is not really usable for us, as settings this labels manually over the UI would result in CI Fails as we depend on the created environment for later tests. Cool would be if I could ignore a label like `dependencies`. Any ideas how to automate this, thanks in advance!
