### DISCUSSION TITLE
OCI and wildcard version

### DISCUSSION THREAD

**Discussion by dpiraud** [argoproj/argo-cd#9447] [Q&A]
Hello,

One of my applications publish helm charts in an OCI registry with this kind of version (_appname_-_incrementalIndex_-_commitHash_-dev);
* my-api-3-xyz-dev
* my-api-2-ijk-dev
* my-api-1-abc-dev

And I use this kind of config for Argo CD:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxxx
  namespace: xxxx
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    name: ''
    namespace: xxx
    server: 'xxx'
  source:
    path: ''
    repoURL: registry.xxx/helm
    chart: my-api
    targetRevision: '>0.0.0-0'
  project: xxx
```

Let's say the current deployed app is from helm "api-2-ijk-dev" 

I'm only able to install the latest version (api-3-xyz-dev) if i hit the "Refresh Hard" button, Argo CD won't do it automatically.

Is there a way to improve this?

P.S.: I also try with '>0.0.0-0-0-0' and all sorts of target version without success

EDIT:
ArgoCD v2.3.3
