### DISCUSSION TITLE
Argo cd slack notification

### DISCUSSION THREAD

**Discussion by kaikiat** [argoproj/argo-cd#9476] [Q&A]
Hello team,

I am follow the steps in : https://argoproj.github.io/argo-rollouts/generated/notification-services/slack/.

I have created a bot and added it to my slack workspace.

However I am unsure how can I get the `$slack-token` in step 9 (ss below)
<img width="701" alt="Screenshot 2022-05-22 at 12 29 20 AM" src="https://user-images.githubusercontent.com/32543853/169660776-3b6e77ca-2e72-4f6a-aad7-ac31ba8ce095.png">

.

**Comment by aoshfan** [comment]
Hi Kaikiat,

the `$slack-token` value is the same with `OAuth-token` value.

So whatever value you put in the `OAuth-token` you put it as well in `$slack-token`.

Hope this help.

**Reply by sondrelg** [reply]
I think it's very confusing to put two different placeholder values in the two examples: 
<img width="891" alt="image" src="https://user-images.githubusercontent.com/25310870/188134489-2b52bec7-bc90-4024-ad52-0cca8375bc70.png">

Why not just have the examples say  

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  slack-token: <Oauth-access-token>
```

and 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
     token: <Oauth-access-token>
```

?

I assumed the $-notation meant it would reference the secret 🤷
