### DISCUSSION TITLE
Sync succeeded but does not actually sync the app and it stays in out of sync status

### DISCUSSION THREAD

**Discussion by ahmedasmar** [argoproj/argo-cd#9485] [Q&A]
Hello everyone,

I ran into an issue were I have an out of sync application with app diff showing a new volume and volume mount will be added but when I sync it it succeeds but the app stays in out of sync and app diff stays the same. Where can I see the logs for kubectl apply executed by sync button from UI? and if possible can I see the generated manifests that argocd would apply? I could find something there. My application looks something like this: 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  labels:
    environment: dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:xxxx.git
    targetRevision: dev
    path: kubernetes/test
  destination:
    server: https://x.x.x.x
  syncPolicy:
    automated: {}
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: myapp
      jqPathExpressions:
      - .spec.template.spec.containers[] | select(.name == "myapp") |.image
 ```
