### DISCUSSION TITLE
Allow SemVer Helm Chart Version from OCI Registry

### DISCUSSION THREAD

**Discussion by rowi1de** [argoproj/argo-cd#9509] [Q&A]
- For Git based you are able to point an Application to a branch or ref
```yaml
  source:
    repoURL:  https://github.com/rowi1de/graphql-reactive
    targetRevision:  HEAD
```
- ArgoCD will always deploy the latest commit / revision

- For Helm on OCI you need to specify a fixed Version of the Helm Chart in the Application
 ```yaml
  project: my-helm-chart
  source:
    repoURL: ghcr.io/rowi1de/graphql-reactive
    targetRevision:  0.0.17
```

- For Classic Helm Registries you can use SemVer ranges: https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/
```yaml
  project: my-helm-chart
  source:
    repoURL: ghcr.io/rowi1de/graphql-reactive
    targetRevision: 0.0.*
```
- This doesn't work for Helm on OCI, as ArgoCD expect Index.yaml which is only available for classic helm repositories. https://github.com/argoproj/argo-cd/blob/7faae31ff6454d6a443c4e2a4d935c27447c0e96/reposerver/repository/repository.go#L1663 
- OCI doesn't allow discovering versions, but it can list tags: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery
- Also for helm pull, version ranges are supported
- The error in ArgoCD is `Unable to deploy revision: rpc error: code = Unknown desc = Get "ghcr.io/rowi1de/graphql-reactive/graphql-reactive/index.yaml": unsupported protocol scheme ""`

```shell
helm pull oci://ghcr.io/rowi1de/graphql-reactive/graphql-reactive --version '0.0.*'
Pulled: ghcr.io/rowi1de/graphql-reactive/graphql-reactive:0.0.17

helm pull oci://ghcr.io/rowi1de/graphql-reactive/graphql-reactive --version '0.1.*'
Pulled: ghcr.io/rowi1de/graphql-reactive/graphql-reactive:0.1.2
```

- My workflow is as follows
  - CI with GitHub Actions
     - [Tag & Push Docker Image with commit-id](https://github.com/rowi1de/graphql-reactive/actions/workflows/gradle-build-push-image.yml)
     - [Increment Patch Version of the Helm Chart based on SemVer](https://github.com/rowi1de/graphql-reactive/runs/6562238780?check_suite_focus=true#step:9:11)
     - [Publish new Helm Chart to Github Packages as OCI Image](https://github.com/rowi1de/graphql-reactive/runs/6562238780?check_suite_focus=true#step:12:40)
     - [Point Argo CD to the OCI Image / Helm Chart](https://github.com/rowi1de/argocd/blob/main/services/graphql-reactive.yaml#L13)

- One Note: I'm currently not pushing the modified Chart.yaml from the GitHub Action Release workflow, so the committed Chart.yaml will always contain a wrong version

**Comment by fe-ax** [comment]
Not sure if this is what you mean, but Argo already supports tracking versions: https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/

**Reply by rowi1de** [reply]
> Not sure if this is what you mean, but Argo already supports tracking versions: [argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies](https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/)


how could I miss this, thank you so much!

**Reply by fe-ax** [reply]
This is what I meant with "0.0.0-{branch-name}-{unix-timestamp}-build-{commit-SHA}" with tracking "0.0.0-mydevbranch-*" on slack :)

**Reply by rowi1de** [reply]
Ok I misunderstood "You can point argo directly to your dev branch " because a helm chart in a OCI Registry is not a branch, but published SemVer :)

**Reply by rowi1de** [reply]
@fe-ax doesn't work for OCI based Helm Charts:
`ghcr.io/rowi1de/graphql-reactive/index.yaml": unsupported protocol scheme "`

**Reply by fe-ax** [reply]
Can you share your application definition?

**Reply by rowi1de** [reply]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphql-reactive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade on delete
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    repoURL: ghcr.io/rowi1de/graphql-reactive
    # https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/
    targetRevision: '>=0.0.0'
    chart: graphql-reactive
  project: services
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

I know there is no scheme, but it was hard to convince argo to use OCI, maybe something wrong there as well?
