### DISCUSSION TITLE
ApplicationSet was created but there is no application in argocd namespace

### DISCUSSION THREAD

**Discussion by losblancos113** [argoproj/argo-cd#9510] [Q&A]
Hi all,

I'm getting start with ApplicationSet and I got a problem after apply the application set manifest.
The application set was  created on namespace argocd but the applications. I'm not sure what happened because there was no error.
This is my ApplicatioSet manifest:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  # namespace: argocd-application
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://git.com/repo
        revision: feature/create-an-argocd-applicationset
        files:
        - path: "tenants/argocd-tenant/*-service-config.yaml"
  template:
    metadata:
      name: '{{application.name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/created-by: argocd
    spec:
      project: default  
      source:
        repoURL: '{{application.repoURL}}'
        targetRevision: '{{application.targetRevision}}'
        path: '{{application.path}}'
        helm:
          fileParameters:
          - name: values
            path: 'values/{{application.name}}-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basenameNormalized}}'
```
Does anyone know what is wrong here?
