### DISCUSSION TITLE
How-to mount persistent volume using HELM with terraform

### DISCUSSION THREAD

**Discussion by rmalenko** [argoproj/argo-cd#9576] [Q&A]
Hello,
I'm looking a solution to add persistent volume using terraform and helm chart. 

My aim is to have in a **pod** something like this

```yaml
spec:
  volumes:
    - name: argo-cd-nfs
      persistentVolumeClaim:
        claimName: argo-cd-nfs
  containers:
      volumeMounts:
        - name: argo-cd-nfs
          mountPath: /tmp
```

I have this error: ` error validating data: ValidationError(Deployment.spec.template.spec.volumes[0]): unknown field "containers" in io.k8s.api.core.v1.Volume`.

If I comment out  `containers = {` I have other error `ValidationError(Deployment.spec.template.spec.volumes[0]): unknown field "volumeMounts" in io.k8s.api.core.v1.Volume`
It because the volumes key should be at the same level as containers.

**My part of terraform code**
 **Variables:**
```hcl
locals {

    repoServer = {
      volumes = [
        {
          name = "${local.name_persistent_volume_claim}"
          persistentVolumeClaim = {
            claimName = "${local.name_persistent_volume_claim}"
          },
          containers = {
          volumeMounts = [
            {
              name      = "${local.name_persistent_volume_claim}"
              mountPath = "/tmp"
            }
          ]
        }
        }
      ]
    }
    
  })
}
```
```hcl
resource "helm_release" "argo-cd" {
  name             = var.argo-cd_release_name
  chart            = var.argo-cd_chart
  repository       = var.argo-cd_chart_repository_url
  version          = var.argo-cd_chart_version
  namespace        = local.namespace

  values = [yamlencode(local.argocd_values)]
```

P.S. 
If `mountPath: /tmp` it gives another error `msg="mkdir /tmp/_argocd-repo: permission denied"`
