### DISCUSSION TITLE
How do I setup ADFS Authentication in ArgoCD

### DISCUSSION THREAD

**Discussion by edtshuma** [argoproj/argo-cd#9578] [Q&A] [answered]
I am trying to enable user login via ADFS on our on-prem installation of ArgoCD.

I cannot find a clear enough guide on how to do this. I have only found an example [here](https://medium.com/dzerolabs/configuring-sso-with-azure-active-directory-on-argocd-d20be4ba753b) _**but using AzureAD.**_ 
The information in the [documentation ](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/auth0/) does not seem to be straightfoward enough (not sure if Auth0 is appropriate for my use-case).

What do I need to setup ADFS with Argo ?

**Comment by AlbertoSpain** [comment, marked as answer]
It works with OAuth & OIDC config.:

Edit argocd-cm config map

```
data:
  url: https://argocd_url
  oidc.config: |
    name: ADFS
    issuer: https://--adfs_url--/adfs
    clientID: --------
    clientSecret: --------
    insecureEnableGroups: true
    requestedScopes:
    - openid
    - profile
    - email
    - groups
```

Create an Application group into ADFS, type: server application accessing web api
You have to transform claims --> create an issuance transform rule which send ldap attributes as claims, but:
token groups unquialified names --> groups
Display Name --> email
