### DISCUSSION TITLE
Argo Notification triggered on-deployed contains terminating pod image

### DISCUSSION THREAD

**Discussion by muratakdeniz** [argoproj/argo-cd#9621] [Q&A]
When ArgoCD notification sends the "deployment is done notification", the Application has also the terminating image in `.app.status.summary.images`.

is there any way to ignore terminating pod images?

```yml    
    template.app-sync-succeeded: |
       webhook:
        argocd-webhook:
          method: POST 
          body: |
            {
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "themeColor": "5c6063",
                "summary": "App '{{.app.metadata.name}}'  has been successfully synced.",
                "sections": [{
                    "activityTitle": "{{.app.metadata.name}}",
                    "activitySubtitle": "On Team {{ .app.metadata.labels.team}}",
                    "activityImage": "./android-chrome-512x512_tcm162-26158.png",
                    "facts": [{
                        "name": "Status",
                        "value": "Application has been successfully synced. Please wait for the final deployment confirmation."
                    },    
                     ],
                    "markdown": true
                }
                ,
                { "facts":[ 
                    {{range $index, $image := .app.status.summary.images}}
                    {
                        "name": "Image {{add $index 1}}",
                        "value": " {{$image}}"
                    },    
                    {{end}}
                  ],
                }
                ],
                "potentialAction": [   {
                    "@type": "OpenUri",
                    "name": "See The App",
                    "targets": [{
                        "os": "default",
                        "uri":"{{ .context.argocdUrl }}/applications/{{.app.metadata.name}}"
                    }]
                }]
            }
```

```yml
  triggers:
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.operationState.syncResult.revision
        send:
        - app-sync-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status != 'OutOfSync'
```
