### DISCUSSION TITLE
What paths does the CLI need access to?

### DISCUSSION THREAD

**Discussion by djfinnoy** [argoproj/argo-cd#9720] [Q&A] [answered]
I'm running ArgoCD behind an oauth2-proxy auth policy with Istio.

Web UI works fine, but I'm having problems with the CLI. I allow certain endpoints of my ArgoCD URL through without going through the reverse proxy, eg. to make github webhooks work:

```
...
        - operation:
            hosts:
              - argocd.mydomain.com
            notPaths:
              # Skip oauth2-proxy for these paths
              - /api/webhook
              - /api/dex*
              - /api/v1/*
```

The CLI does not work with this setting, I get the following error:

```
$ argocd login --grpc-web argocd.mydomain.com
FATA[0003] rpc error: code = Unknown desc = unexpected EOF 
```
It works if I disable the oauth2-authentication flow entirely, so I'm guessing that the CLI is hitting the reverse proxy, and that I will need to whitelist more paths above to get it working.

Does anyone know what to do?
