### DISCUSSION TITLE
config management plugin not supported. plugin name cmp-plugin

### DISCUSSION THREAD

**Discussion by goelshubham** [argoproj/argo-cd#9726] [Q&A] [answered]
I am trying to setup a simple config management plugin using the config map approach but I am getting the error `rpc error: code = Unknown desc = config management plugin not supported. plugin name cmp-plugin`

I have referred the official [documentation](https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/config-management-plugins.md) to setup my use case.

My configmap looks like below. Here I am trying to do a simple nginx deployment.
```
apiVersion: v1
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      generate:
        command: [sh, -c, 'echo "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"name\":\"nginx-deployment\",\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"name\":\"nginx\",\"image\":\"nginx:1.14.2\",\"ports\":[{\"containerPort\":80}]}]}}}}"']
      allowConcurrency: true
      lockRepo: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2022-06-17T19:05:41Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "138522"
  uid: 23de2d90-c85f-4bd7-a628-f7fbc70ac74f
```

The Application CRD looks like below.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cmp-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goelshubham/argocd-app-config.git
    path: guestbook
    targetRevision: HEAD
    plugin:
      name: cmp-plugin
      env:
      - name: FOO
        value: bar
  destination:
    server: https://kubernetes.default.svc
    namespace: default
```

The source can he accessed here: https://github.com/goelshubham/argocd-app-config/tree/main/guestbook

When I create the project for the above Application then i get the error.

When I see argocd-repo-server pod logs, I see this message:

```
time="2022-06-21T01:00:30Z" level=info msg="manifest error cache hit: &ApplicationSource{RepoURL:https://github.com/goelshubham/argocd-app-config.git,Path:guestbook,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:&ApplicationSourcePlugin{Name:cmp-plugin,Env:[]*EnvEntry{&EnvEntry{Name:FOO,Value:bar,},},},Chart:,}/7301ef83c23b3daccba25f4da9daa8cbcd2cabb4"
time="2022-06-21T01:00:30Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): config management plugin not supported. plugin name cmp-plugin" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-06-21T01:00:30Z" grpc.time_ms=1.654 span.kind=server system=grpc
time="2022-06-21T01:00:30Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:https://github.com/goelshubham/argocd-app-config.git,Path:application/cmp,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,}/7301ef83c23b3daccba25f4da9daa8cbcd2cabb4"
time="2022-06-21T01:00:30Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2022-06-21T01:00:30Z" grpc.time_ms=0.527 span.kind=server system=grpc
```

I already went through some of the related questions such as https://github.com/argoproj/argo-cd/discussions/8216 but that's the problem with sidecar implementation.

**Comment by crenshaw-dev** [comment, marked as answer]
@goelshubham it looks like you're mixing the sidecar installation method with the argocd-cm installation method. Your `data` block in the `argocd-cm` ConfigMap should look like this:

```yaml
 data:
   configManagementPlugins: |
     - name: cmp-plugin
        generate:
          command: [sh, -c, 'echo "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"name\":\"nginx-deployment\",\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"name\":\"nginx\",\"image\":\"nginx:1.14.2\",\"ports\":[{\"containerPort\":80}]}]}}}}"']
      allowConcurrency: true
      lockRepo: true
```

argocd-cm plugins are going to be deprecated in 2.5, so I'd recommend switching to a sidecar plugin soon.
