### DISCUSSION TITLE
How to use 2.4 terminal feature when using rootpath/basehref

### DISCUSSION THREAD

**Discussion by DavidRayner** [argoproj/argo-cd#9751] [Q&A] [answered]
I am using ArgoCD `v2.4.2+c6d0c8b` (helm chart `4.9.4`) with this relevant config
```
server:
  ingress:
    enabled: true
    hosts:
      - example.com
    paths:
      - /argocd/
    annotations:
      external-dns.alpha.kubernetes.io/hostname: example.com
      ...

  extraArgs:
    - --insecure
    - --basehref
    - /argocd/
    - --rootpath
    - /argocd/

  config:
    url: https://example.com/argocd/
    exec.enabled: "true"
```

When trying to view the terminal for an application I get this console error:
`WebSocket connection to 'wss://example.com/terminal?pod=...' failed`

If I run argo on `/` instead of `/argocd/` then the terminals work as expected.

Do I need to add a rewrite annotation to the ingress to get terminals working?
Or is there a bug and terminals should use connections at `wss://example.com/<root-path>/terminal`?

Please label with `component:web-terminal `
