### DISCUSSION TITLE
Configure argocd notification dynamiclly

### DISCUSSION THREAD

**Discussion by Pazze12** [argoproj/argo-cd#9768] [Q&A]
I have multiple projects with different email-adresses, which should get informations about their specific apps
 To get the email configs dynamiclly i added something like:
 
```
subscriptions: |
    - recipients:
{{ if .project.email -}}
      - mail:{{ .project.email }}
{{ if .project.triggers -}}
      triggers:
      {{ .project.triggers }} 
{{- end }}
{{- end }}
```

But i dont know how to configure argocd notifier so project-a only get the notifications from their apps and project-b from their apps.
Do i need to configure multiple templates or could i create variable usable templates for that issue.

Some one had these problem before?

greetings pazze :)

**Comment by soudaburger** [comment]
You have `subscriptions`, `templates`, and `triggers`... 

You configure applicationsets, applications, or projects with `subscriptions`.
Those subscriptions are tied to a trigger, which defines _when_ a notification is to be sent for that subscription.
The notifications then use the `template` for sending the notification.

Does that help?

**Reply by Pazze12** [reply]
So if i have 20 project, i create 20 different `subscriptions` ?

**Reply by Pazze12** [reply]
something like:
```
subscriptions: |
    - recipients:
      - slack:test1
      triggers:
      - project1-on-sync-status-unknown
    - recipients:
      - slack:test2
      triggers:
      - projct2-on-sync-status-unknown
      - projct2-sync-failed
```
