### DISCUSSION TITLE
Does Config Management Plugin (CPM) work with ApplicationSet CRDs

### DISCUSSION THREAD

**Discussion by goelshubham** [argoproj/argo-cd#9779] [Q&A] [answered]
I know that CMP works with Application CRD and as per [this](https://argo-cd.readthedocs.io/en/release-1.8/user-guide/config-management-plugins/#environment) documentation the `init` and `generate` commands in the plugins have access to the system environment variables or Standard build environment or env values passed in Application CRD's source.

I have a usecase where I want to implement the App-of-Apps design pattern using [ApplicationSet](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/). In ApplicationSet I want to use [git generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/) but at the same time in the `template.source` of ApplicationSet, I want to pass my custom manifest and also be able to use config management plugin there. I want to inject properties specified in the git generators in my custom manifest files using the custom plugin approach.

My question is - Is it possible to use config management plugins with ApplicationSet CRD?

My ApplicationSet CRD might look like below. I have a git generator where in the files path, I will be specifying certain key-value pairs. In the `template.spec.source` I want to specify my custom template using [custom config management tool](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/) (and not use helm charts or Jsonnet or Kustomize).

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj/applicationset.git
      revision: HEAD
      files:
      - path: examples/git-generator-directory/cluster-addons/*
  template:
    metadata:
      name: xyz
    spec:
      project: default
      source:
        repoURL: git-url-of-my-custom-manifest-file
        targetRevision: HEAD
        path: path-to-manifest-files
        plugin:
          name: some-plugin-name
          env:
            - name: FOO
              value: bar
      destination:
        server: https://kubernetes.default.svc
        namespace: some-value
```
