### DISCUSSION TITLE
Argocd + env var + applicationset + kustomize

### DISCUSSION THREAD

**Discussion by soudaburger** [argoproj/argo-cd#9814] [Q&A] [answered]
We are running into an issue where we would like to simply add an environment variable `FOO` to an applicationset so that the `image.tag` (as an example) can be overwritten in the kustomize template rendering.

1. We are using a combination of kustomize with helm, but from an applicationset perspective we are NOT using the `helm:` configuration, just relying on the built in kustomize + `--enable-helm` flag.
2. We have a separate repository that contains our image versions (for a multitude of reasons) and we'd like to be able to interpolate those into kustomize for rendering so that argo will not only deploy the new version as set but also not see any deltas or diffs with the applicationset.
3. We are using argocd `2.4.2` on GKE.

We continue to see references to the CMP where we are "supposed" to just be able to use:
```yaml
        plugin:
          env:
            - name: IMAGETAG
              value: "{{version}}"
```

However, when using that we run into : 
```bash
rpc error: code = Unknown desc = plugin sidecar failed. Couldn't find cmp-server plugin supporting repository .apps/core-api/deploy/overlays/staging
```

So, how, exactly are we supposed to add an environment variable to kustomize templating from an applicationset?  I know how to retrieve it on the templating side, but setting it on the applicationset seems to either be impossible or completely undocumented?  Any pointers here or help would be fantastic! Thanks!

Documentation Sources:
1. https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/config-management-plugins.md#environment
2. https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#environment

**Comment by soudaburger** [comment, marked as answer]
Actually I solved my own problem, but this was a HUGE combination of documented pieces from around the web... ok so here are the pieces...

In my `applicationSet`:
```yaml
        plugin:
          env:
            - name: IMAGETAG
              value: "{{version}}"
          name: kustomized-helm
```

In argocd helm configuration for plugins:
```yaml
    # server.config.configManagementPlugins
    configManagementPlugins: |
      - name: kustomized-helm
        generate:
          command: ["/bin/sh", "-c"]
          args: ["IMAGETAG=${ARGOCD_ENV_IMAGETAG} kustomize build --enable-helm"]
```

Local `kustomization.yaml`:
```yaml
configMapGenerator:
  - name: image-tag-var
    env: image.tag.properties

replacements:
  - path: image-tag-replacement.yaml
```

Local `image.tag.properties`:
```bash
IMAGETAG
```

Notice the deployment name and the `containers.[name=]` sections... those are things to make it all work together.

Local `image-tag-replacement.yaml`
```yaml
source:
  kind: ConfigMap
  name: image-tag-var
  fieldPath: data.IMAGETAG
  version: v1
targets:
- select:
    name: my-deployment
    kind: Deployment
  fieldPaths:
    - spec.template.spec.containers.[name=my-container].image
  options:
    delimiter: ':'
    index: 1
    create: true

```

**Reply by raebbar** [reply]
You can set the image tag within an ApplicationSet without any extras.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo
spec:
  generators:
    [...]
  template:
    metadata:
      name: 'foo-review-{{number}}'
      [...]
    spec:
      source:
        repoURL: XXXXXX.git
        targetRevision: HEAD
        path: 'XXXX'
        kustomize:
          images:
            - example.com/foo:{{version}}
      destination:
        [...]
```

**Reply by pantmal** [reply]
@raebbar  This covers only the image tag however. If you want to change any other values, then you will have to go with soudaburger's approach.

**Reply by raebbar** [reply]
@pantmal You're right, this only works for image tags. For other values, as you said, you have to use the soudaburger's approach. 

For those interested: I described another solution without an extra Argocd plugin and ConfigMap in [discussion 9042](https://github.com/argoproj/argo-cd/discussions/9042#discussioncomment-4398836).

**Comment by pantmal** [comment]
I'm trying to use this for my setup as well but I have encountered a problem: When I want to open a new PR, a new app is created but it also updates the existing ones too. Do we have a solution and/or an explanation of why this occurs? I tried the same setup with Helm and everything works as expected.

**Comment by amine7777** [comment]
I recently had to create a custom **Config Management Plugin (CMP)** for **Carvel ytt**, and I ran into a similar challenge.  
My setup had a **single common template** but **multiple sets of data values** in different folders, and I needed a way to dynamically tell the plugin which `values.yaml` file to use when generating manifests.

Initially, I wasn’t sure how to pass those dynamic arguments from an **ApplicationSet** into the plugin.  
Thanks to this discussion, I learned that defining environment variables under the `plugin.env` section in the ApplicationSet and referencing them as `ARGOCD_ENV_*` in the plugin command works perfectly.

However, I ran into a subtle but important issue with how the command was defined in the plugin spec:

| Common Mistake | Correct Form |
|----------------|---------------|
| `command: ["/usr/local/bin/ytt"]` + `args: ["ytt -f . ${ARGOCD_ENV_YTT_EXTRA_ARGS}"]` | ❌ Runs `ytt` twice and fails with “does not accept extra arguments” |
| `command: ["/bin/sh", "-c"]` + `args: ["ytt -f . ${ARGOCD_ENV_YTT_EXTRA_ARGS}"]` | ✅ Shell expands the environment variable and runs correctly |

The issue happened because Argo CD executes the command directly (without a shell),  
so the string `ytt -f . ${ARGOCD_ENV_YTT_EXTRA_ARGS}` was passed literally as an argument to `ytt`.  
Switching to `["/bin/sh", "-c"]` lets the shell expand `${ARGOCD_ENV_YTT_EXTRA_ARGS}` before calling `ytt`.

This change finally allowed me to pass per-application arguments like:

```yaml
configManagementPlugins: |
  - name: carvel-ytt-cmp
    generate:
      command: ["/bin/sh", "-c"]
      args: ["ytt -f . ${ARGOCD_ENV_YTT_EXTRA_ARGS}"]
```

```yaml
plugin:
  name: carvel-ytt-cmp
  env:
    - name: YTT_EXTRA_ARGS
      value: "-f path/to/values.yml"
```
