### DISCUSSION TITLE
Use SSH over HTTPS for Git repositories

### DISCUSSION THREAD

**Discussion by etiennetremel** [argoproj/argo-cd#9827] [Q&A] [answered]
I'm trying to use ArgoCD repositories with SSH over HTTPS but it doesn't seem to be possible.

I mounted the following ssh config located as volume in `/home/argocd/.ssh/config` of the `argocd-repo-server`:

```
Host github.com
  Hostname ssh.github.com
  Port 443
  User git
```

When I execute `ssh -T git@github.com -v` from the argocd-repo-server container, the connection is correctly going through HTTPS.

But the `argocd-repo-server` still throw an `authentication required` error message when synchronising the repo.

This is the secret repository config that I'm using:
```
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:my-org/my-repo
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
```

Any idea if it's possible to do SSH over HTTPS with ArgoCD? For some reason, port 22 is locked on our network. We would like to stay away from setting up a GitHub App and instead use SSH with a deployment key.
