### DISCUSSION TITLE
How can i debug argocd-notifications-controller?

### DISCUSSION THREAD

**Discussion by lazychanger** [argoproj/argo-cd#9877] [Q&A]
When I use webhook notification, no message is received, So I want to debug the webhook notification by myself

```shell
argocd-notifications --help

Starts Argo CD Notifications controller

Usage:
  controller [flags]

Flags:
      --app-label-selector string       App label selector.
      --argocd-repo-server string       Argo CD repo server address (default "argocd-repo-server:8081")
      --argocd-repo-server-plaintext    Use a plaintext client (non-TLS) to connect to repository server
      --argocd-repo-server-strict-tls   Perform strict validation of TLS certificates when connecting to repo server
      --as string                       Username to impersonate for the operation
      --as-group stringArray            Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --as-uid string                   UID to impersonate for the operation
      --certificate-authority string    Path to a cert file for the certificate authority
      --client-certificate string       Path to a client certificate file for TLS
      --client-key string               Path to a client key file for TLS
      --cluster string                  The name of the kubeconfig cluster to use
      --config-map-name string          Set notifications ConfigMap name (default "argocd-notifications-cm")
      --context string                  The name of the kubeconfig context to use
  -h, --help                            help for controller
      --insecure-skip-tls-verify        If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string               Path to a kube config. Only required if out-of-cluster
      --logformat string                Set the logging format. One of: text|json (default "text")
      --loglevel string                 Set the logging level. One of: debug|info|warn|error (default "info")
      --metrics-port int                Metrics port (default 9001)
      --namespace string                Namespace which controller handles. Current namespace if empty.
      --password string                 Password for basic authentication to the API server
      --processors-count int            Processors count. (default 1)
      --request-timeout string          The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
      --secret-name string              Set notifications Secret name (default "argocd-notifications-secret")
      --server string                   The address and port of the Kubernetes API server
      --tls-server-name string          If provided, this name will be used to validate server certificate. If this is not provided, hostname used to contact the server is used.
      --token string                    Bearer token for authentication to the API server
      --user string                     The name of the kubeconfig user to use
      --username string                 Username for basic authentication to the API server
```

#### argocd-notifications-controller-cm.yaml
```yaml
service.webhook.dingtalk: |
    url: https://oapi.dingtalk.com/robot/send?access_token=$dingtalk-accesstoken
    headers:
      - name: Content-Type
        value: application/json
context: |
  argocdUrl: http://argocd.example.com
template.app-sync-change: |
  webhook:
    dingtalk:
      method: POST
      body: |
        {
              "msgtype": "markdown",
              "markdown": {
                  "title":"ArgoCD sync status",
                  "text": "### ArgoCD sync status\> - appname: {{.app.metadata.name}}\n> - app sync statuc: {{ .app.status.operationState.phase}}\n> - date:{{.app.status.operationState.startedAt}}\n> - URL: [ump ArgoCD]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true) \n"
              }
          }
trigger.on-deployed: |
  - description: Application is synced and healthy. Triggered once per commit.
    oncePer: app.status.sync.revision
    send: [app-sync-change]  # template names
    # trigger condition
    when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
trigger.on-health-degraded: |
  - description: Application has degraded
    send: [app-sync-change]
    when: app.status.health.status == 'Degraded'
trigger.on-sync-failed: |
  - description: Application syncing has failed
    send: [app-sync-change]  # template names
    when: app.status.operationState.phase in ['Error', 'Failed']
trigger.on-sync-running: |
  - description: Application is being synced
    send: [app-sync-change]  # template names
    when: app.status.operationState.phase in ['Running']
trigger.on-sync-status-unknown: |
  - description: Application status is 'Unknown'
    send: [app-sync-change]  # template names
    when: app.status.sync.status == 'Unknown'
trigger.on-sync-succeeded: |
  - description: Application syncing has succeeded
    send: [app-sync-change]  # template names
    when: app.status.operationState.phase in ['Succeeded']
subscriptions: |
  - recipients: [dingtalk] 
    triggers: [on-sync-running, on-deployed, on-sync-failed, on-sync-succeeded]
```

```txt
time="2022-07-05T09:22:50Z" level=info msg="Start processing" resource=argocd/v3-api
time="2022-07-05T09:22:50Z" level=info msg="Trigger on-sync-failed result: [{[0].H9WjsqG1dKYm6njOZ7yUQYOA1Wk  [app-sync-change] false}]" resource=argocd/v3-api
time="2022-07-05T09:22:50Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0  [app-sync-change] true}]" resource=argocd/v3-api
time="2022-07-05T09:22:50Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{dingtalk }'" resource=argocd/v3-api
time="2022-07-05T09:22:50Z" level=info msg="Trigger on-sync-running result: [{[0].xGlbhcF_taGYrI3UsrQsINn2hl0  [app-sync-change] false}]" resource=argocd/v3-api
time="2022-07-05T09:22:50Z" level=info msg="Trigger on-deployed result: [{[0].y7b5sbwa2Q329JYH755peeq-fBs 936f8edfabf78c47a015e0c047af5c28d70f7aa3 [app-sync-change] true}]" resource=argocd/v3-api
time="2022-07-05T09:22:50Z" level=info msg="Notification about condition 'on-deployed.[0].y7b5sbwa2Q329JYH755peeq-fBs' already sent to '{dingtalk }'" resource=argocd/v3-api
time="2022-07-05T09:22:50Z" level=info msg="Processing completed" resource=argocd/v3-api
```
