### DISCUSSION TITLE
Use local path instead of a repository as source

### DISCUSSION THREAD

**Discussion by SamDecrock** [argoproj/argo-cd#9912] [Ideas]
Hi,

We love ArgoCD because it syncs our application with the manifests stored on git. This makes it super easy to upgrade our software: we update the manifest, argo removes the old deployments, statefulsets, services and whatnot, adds the new ones and we're done.

However, when we install our software on a single-node Kubernetes cluster that is not connected to the internet, we have a problem. We have to manually do `kubectl apply -f manifest.yaml` and check if we need to delete some deployments, statefulsets or any other Kubernetes components. As ArgoCD's source of truth needs to be on a git repo we cannot use Argo for this.

So my question is, is there an option to use a local path as the source of truth for our manifests? This way we can drop the manifest in specific folder and we're done. Or is that a bad idea and if so, how would you solve our problem?

**Comment by crenshaw-dev** [comment]
You could run a git provider in the offline cluster, but that's a bit heavy-weight.

It might also be possible to use an init container or some other mechanism to mount the manifests into the repo-server and then load them as a `file:///` repository.

**Reply by SamDecrock** [reply]
Hmm, you mean start a local git repo and mount this to the arogcd pod(s) and access it through `file:///`. I will have to try this.

**Reply by crenshaw-dev** [reply]
Yep, something like that!

**Comment by krancour** [comment]
@SamDecrock the single node clusters you speak of that are not connected to the internet... what is the specific use case? Knowing the use case may help point to some other viable options.

**Reply by SamDecrock** [reply]
2 use cases:

- customers that don't want their machine connected to the internet.
- customers that run our application on their own cluster and we don't want them to connect to our git repo.

The company I work with has some software, running on Kubernetes. Mostly in our cloud but also on-prem at the customer. Sometimes on a machine close to the customer's production lines. 

We want them to give an easy way of updating our software.

**Reply by krancour** [reply]
While the uses cases seem perfectly valid, I'm wondering what advantages you feel Argo CD buys you in either of these cases.

For the first case, being disconnected from the internet, it would seem updates to the software will be infrequent, rather than continuous, possibly calling into question whether a CD platform buys you much, insofar as the idea behind CD and gitops is to deliver _continuously_.

In the second case (and maybe the first also?) it seems you're delivering "shrink-wrapped" software to another party, in which case, perhaps delivering the application as a Helm chart may possibly be preferable. (And fwiw, Argo CD plays nicely with those also.)

imho, Argo CD shines where/when you're continuously delivering your own first-party solution.

**Reply by SamDecrock** [reply]
I thought about using Helm but does Helm allow you to "sync" your Kubernetes state between the Helm chart and the cluster? I mean, say we drop a component during upgrade, like a Deployment or an ingress rule, can Helm help with this or does the end user/customer need to do an extra `kubectl delete` command?

**Reply by dylanpiergies** [reply]
I have a good use case for this as well: local development. It would be really useful if I could just mount a local Git repo as a `hostPath` volume on a Minikube cluster, since I could then develop and test ArgoCD workflows without the need for any external infrastructure whatsoever, including a hosted Git repository.

Can anyone point to any examples of this being achieved? I do intend to play around with the `file:///` repository approach suggested by @crenshaw-dev.

Edit: This worked beautifully.

**Reply by danijam** [reply]
@dylanpiergies did the `file:///` approach work for you? I've been scratching my head how I can easily spin up a personal instance of ArgoCD to test and play with without having a dependency on accessible Git Repos to pull in application state. I like the idea of injecting config and loading from disk maybe?

**Reply by dylanpiergies** [reply]
@danijam This did indeed work, with the directory containing the Git repository I want to track mounted into the argocd-repo-server's containers. Configuring it to track `HEAD` provided a convenient way to track the current branch in my working repo. This approach doesn't work universally, though, e.g. with Argo Workflows, since many of the images are distroless and do not contain the `git` executable, instead using go-git which has some gaps (in particular, is doesn't appear to support the `file:` URL scheme). https://github.com/argoproj/argo-workflows/pull/8292 and https://github.com/argoproj/argo-workflows/issues/10091. If you're only using ArgoCD this should still be a viable approach.

**Reply by MohammedNoureldin** [reply]
Is there any minimal example of using `file:///`?

**Reply by smp4** [reply]
Hi @dylanpiergies, would you mind sharing how you achieved mounting the local git repo? I am new to Kubernetes and am soundly in the middle of the steep initial learning curve.

My use case is also local development. At the moment I want to test ArgoCD ApplicationSets generating Apps to bootstrap cluster infrastructure. I wish to use a Git generator pulling from a git repository on my local machine, making sure everything works, before moving to a remotely hosted repo.

Using kustomize, I have so far managed to patch the default `argocd-repo-server` definition to mount a new volume for my local repo:

```yaml
# bootstrap/overlays/default/local-git-repo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: '/tmp/local-git-repo'
          name: local-git-repo
          readOnly: true
      volumes:
      - name: local-git-repo
        hostPath:
          path: '/tmp/local-git-repo'
          type: Directory
```

This seems to have worked. Result of `kubectl describe pod argocd-repo-server -n argocd`:

```bash
...
    Mounts:
...
      /tmp/local-git-repo from local-git-repo (ro)
...
Volumes:
  local-git-repo:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/local-git-repo
    HostPathType:  Directory
```

I get this far but don't seem to be able to get the AppSet to pull from this location. I currently have:

```yaml
# components/applicationsets/appset-infrastructure.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'file:///tmp/local-git-repo'
      revision: HEAD
      directories:
      - path: infrastructure/*
  template:
...
```

Any help or thoughts would be very greatly appreciated!

**Reply by dylanpiergies** [reply]
I am using Minikube with the VirtualBox driver. In this configuration, by default it will mount the host's `/home` at `/hosthome` in the Minikube VM (which is also the Node). So then I use something like:
```
volumes:
- name: host-home
  hostPath:
    path: '/hosthome'
```
Then in the container definition:
```
volumeMounts:
- mountPath: /hosthome
  name: host-home
```
So we have a chain of mounts `/home` (on the host workstation) -> `/hosthome` (in the Minikube VM) -> `/hosthome` (in the argocd-repo-server container).

Then my repo URL is `file:///hosthome/my-username/my-git-repo`.

The setup you have looks reasonable, assuming that you have the directory containing your Git repo mounted at `/tmp` on the Kubernetes node. Note that if there are other containers involved in your use case that interact directly with the Git repository, you'll need to ensure they also have the directory containing your repo mounted at the same path. What sorts of errors are you getting?

**Reply by smp4** [reply]
Hi, thanks very much for the quick reply and describing your setup!

In my case, I'm using a single node (my localhost) K3s cluster for local development, so I don't have the chain of mounts. As I understand it, provided the git repo is actually in `/tmp`, the only mounting I need to do is into the container, which seems to be working.

For now, I'll be happy to have replicated the standard ArgoCD behaviour of keeping a cluster config up to date with a GitOps repo (only, hosted locally). 

My git repo currently only configures ArgoCD to be deployed and to then manage itself via an AppSet (more or less following this [Red Hat example](https://github.com/christianh814/example-kubernetes-go-repo)). So, the only application that needs access to my local repo is ArgoCD, and my understanding is that only the `argocd-repo-server` container within ArgoCd needs access to the repo. Please correct me here if I'm wrong!

Given that you've said my config looks reasonable so far, then perhaps there's something wrong in my AppSet config, or file permissions, or... . 

I'm away from my computer for a day or two now, but next chance I get I'll dig into the logs to see if Argo reported problems parsing the AppSet config, and try a simpler minimal example, perhaps just directly ArgoCD running as an Application without the AppSet layer.

Thanks again!

**Reply by dylanpiergies** [reply]
@smp4 Yeah, the things to look out for are the obvious nonexistent file errors due to path mismatch, or permission denied errors, which are trivially fixable. But if you errors related to the absence of the `git` executable, it's likely you have a problem similar to those arising from to https://github.com/argoproj/argo-workflows/pull/8292 and/or https://github.com/argoproj/argo-workflows/issues/10091. I'm not sure if ArgoCD has taken steps towards distroless containers as Argo Workflows has.

**Reply by smp4** [reply]
Thanks @dylanpiergies. I don't see any `git` executable errors so far.

I get the following error in the `argocd-applicationset-controller` logs:

```bash
level=error msg="error generating application from params" applicationset=argocd/infrastructure-appset error="error generating params from git: error getting directories from repo: error retrieving Git Directories: rpc error: code = Internal desc = unable to resolve git revision : repository not found" generator="{nil nil &GitGenerator{RepoURL:file:///tmp/local-git-repo.....
```

The logs of `argocd-repo-server` reporting similar errors:

```bash
level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = unable to resolve git revision : repository not found" grpc.code=Internal grpc.method=GetGitDirectories grpc.
```

ArgoCD is unable to find my repository.

Using [K9s](https://k9scli.io/) to drop into a shell on the `argocd-repo-server` container, I see that `/tmp/local-git-repo` is readable (only) and owned by `UID:GID` `1000:1000` (my user), whereas other directories in `/tmp` are owned by the user `argocd`. If I can read `/tmp/local-git-repo` and its contents then ArgoCD should be able to find the repo?

Maybe I'm missing something with discoverability/ git protocol etc?

I thought `ARGOCD_APPLICATIONSET_CONTROLLER_ALLOWED_SCM_PROVIDERS` might be the ticket, but then [the docs](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Appset-Any-Namespace/) state that if you aren't configuring a custom API, (which, as a local git repo, I'm not), then this gets ignored. So, no use.

The e2e testing for ArgoCD, documented [here](https://github.com/argoproj/argo-cd/blob/1600c03abafc4a0526d6909b3eddab5071d59508/docs/developer-guide/test-e2e.md), suggests that the Argo dev team *are* using a local temp directory and referring to it via file url: `file:///tmp/argocd-e2e***`. This sent me down the rabbit hole reading through the makefile and test code to figure out how this works.

The best conclusion I have is that a custom dummy remote server listening at `http://127.0.0.1:9081/argo-e2e/testdata.git` (see eg [argoproj/argo-cd/test/remote](https://github.com/argoproj/argo-cd/tree/1600c03abafc4a0526d6909b3eddab5071d59508/test/remote).) This can't be the right solution given the hints from other comments in this issue about simply mounting volumes. It also seems a little heavy handed.

Many thanks!

---

**Edit:** Please ignore the above, I got it working (after sleep). I'll leave the post above in case the error text pulls in anyone to the solution below.

`/tmp/local-git-repo` needed to be initialised as a git repo. There were hints [here](https://github.com/argoproj/argo-cd/blob/1600c03abafc4a0526d6909b3eddab5071d59508/test/remote/Dockerfile) but I ignored them.

My "working" git repo is a properly initialised git repo in my home directory but it has a lot of cruft in it. I had been copying out the manifest directories to `/tmp/local-git-repo` prior to bootstrapping the cluster, but I had *not* been initialising that directory as a git repo. The following fixed it:

```bash
cd /tmp/local-git-repo
git init
git add .
git commit -m "initial commit"
```

Within a couple minutes Argo had re-run reconciliation and boom, I have a working AppSet from a local git repo. I'll post a cleaner working example for others to use later. Thanks again @dylanpiergies.

**Reply by smp4** [reply]
Objective:

Use a Git repository stored on your `localhost` (as opposed to stored at a remote location such as GitHub) as the source for an ArgoCD Application or ApplicationSet. This might be useful for local development purposes.

Assumptions:

* You already have a cluster running on your local machine using K3s, minikube or similar. This was tested with K3s running a single node cluster.

Steps:

1. Create local Git repo and initialise it.
2. Patch `argocd-repo-server` to include a `hostPath` volume.
3. Set Application/ ApplicationSet `repoURL` to local Git repo.
4. Deploy config to local cluster.
5. Verify.

This example uses Kustomize organised as below to deploy ArgoCD but the logic should be applicable to other methods.

```bash
my-argocd-deployment
├── base
│   ├── kustomization.yaml
│   └── ns-argocd.yaml
└── overlays
    └── dev
        ├── kustomization.yaml
        ├── local-git-repo.yaml
        └── my-appset.yaml
```

```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ns-argocd.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
```

```yaml
# /base/ns-argocd.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
spec: {}
status: {}
```

**Create local Git repo and initialise it**

On your local machine:

```bash
mkdir -p /tmp/local-git-repo
cd /tmp/local-git-repo
git init
# copy files to repo
git add .
git commit -m "initial commit"
```

**Patch `argocd-repo-server`**

```yaml
# overlays/dev/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: local-git-repo.yaml
  target:
   kind: Deployment
   name: argocd-repo-server
   namespace: argocd
```

```yaml
# overlays/dev/local-git-repo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: '/tmp/local-git-repo'
          name: local-git-repo
          readOnly: true
      volumes:
      - name: local-git-repo
        hostPath:
          path: '/tmp/local-git-repo'
          type: Directory
```

The `readOnly: true` is important for security. See [Kubernetes `hostPath` docs](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath).

**Set ApplicationSet `repoURL`**

```yaml
# overlays/dev/my-appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  generators:  # Other generator types will work too
  - git:
      repoURL: 'file:///tmp/local-git-repo'
      revision: HEAD
      directories:
      - path: apps/*  # or wherever you store your app configs in the repo
  template:
    metadata:
      name: '{{path.basename}}-app'  # not important for this example
      namespace: '{{path.basename}}'  # not important for this example
    spec:
      project: default  # not important for this example
      syncPolicy:  # not important for this example
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: 'file:///tmp/local-git-repo'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
```

**Deploy config to cluster**

```bash
kubectl apply -k /path/to/my-argocd-deployment/overlays/dev/
```

**Verify**

From CLI:

```bash
kubectl get applicationsets -A
kubectl get applications -A
```
You should see your application and/ or applicationset `Synced` and `Healthy`. 

With ArgoCD UI:

Get initial password and forward the UI port:

```bash
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
kubectl port-forward svc/argocd-server -n argocd 8080:443
```

Go to [https://localhost:8080](https://localhost:8080), log in with user `admin` and password from command above. Should see your apps deployed and healthy.

Troubleshooting:

Check for errors in logs from `argocd-repo-server` and `argocd-applicationset-controller`.

**Reply by anthonyalayo** [reply]
Thanks @smp4 , that's super helpful for myself as well. Do you have any suggestions on an easy way to toggle between `file://...` and `http://...`? Changing all repository links just for local development, then removing the changes before merge, is a bit tedious.

**Reply by smp4** [reply]
In the example above, the local repo is set in the `dev` overlay. you could have a `stage`/ `prod`/ whatever overlay as well, listing your (eg) remote repo instead. Then deploy argo with whichever overlay is applicable to your environment. 

Alternative could be use a templating tool (helm, ansible, terraform..), bash script, ...?

**Reply by odelot** [reply]
Hi @smp4 , I am new on all this, but I just could use your example when I added `- my-appset.yaml` in the list of resources of `# overlays/dev/kustomization` file

**Reply by smp4** [reply]
Hi @odelot, sorry, I don't understand your comment. Are you confirming that you could get it to work (perhaps with a simpler method? woo!), or you could _not_ get it to work?

**Reply by anthonyalayo** [reply]
@smp4 I tried this out, but it's still not working.

#### Here's my Argo CD UI, to prove my repo url is correct:
![image](https://github.com/argoproj/argo-cd/assets/17555572/810dfefe-83d7-4029-ae5e-ac6ef5d4f4a8)

#### Here's my mounts for the argocd-repo-server, to prove that its mounted:
![image](https://github.com/argoproj/argo-cd/assets/17555572/22180ecd-b2ca-4a02-8e68-48a3dfb21542)

#### With that set, I tried modifying the current version of argo-cd:
![image](https://github.com/argoproj/argo-cd/assets/17555572/24a368bf-5e05-4d0b-9662-31581612d37d)

I hit save in my IDE, as well as refresh and sync in the Argo CD UI, yet nothing changes. Is there a trick to this? I did notice that before i merged the `local-git-repo` support to main remote, it still wasn't going off of my local. It was going off of my remote.

**Reply by anthonyalayo** [reply]
I also tried changing something in the values file:
![image](https://github.com/argoproj/argo-cd/assets/17555572/49852588-3ffd-4fc1-abc2-d0cb2323b46b)

Yet even after a refresh and sync, I don't see the change on Argo CD's UI:
![image](https://github.com/argoproj/argo-cd/assets/17555572/08b4e8af-1d9a-4852-8a3d-2364b3b939c3)

I SSHed into the repo server pod to check things out:
```
argocd@argocd-repo-server-667ddfc5bc-mjhlk:/tmp/local-git-repo/argo$ cat Chart.yaml | grep 6.0.1
    version: 6.0.1
argocd@argocd-repo-server-667ddfc5bc-mjhlk:/tmp/local-git-repo/argo$ cat values.dev.yaml | grep BOOP
        targetRevision: BOOP
```

And I do see the changes in the pod's mount. So there's some sort of disconnect somewhere.

**Reply by anthonyalayo** [reply]
@smp4 am i missing anything?

**Reply by smp4** [reply]
Hi @anthonyalayo, reading through your posts i thought perhaps although you were pushing your gitops repo changes to remote, you may not have been _also_ pushing them to `/tmp/local-git-repo`on your cluster host machine, but your screenshot from your ssh session into the repo server pod seems to show it has picked up the `targetRevision` and `version` changes. 

What I also notice is that your repo URL does not end in `.git`. In my cluster, the ArgoCD App `Repo URL` is `file:///tmp/argo-gitops.git`. This should only [be a convention](https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server#_getting_git_on_a_server), but who knows. 

```bash
mkdir -p /tmp/local-git-repo.git
cd /tmp/local-git-repo.git
git init --bare
``` 

Other than that, seeing as your `argocd-repo-server` has picked up your version and targetRevision settings I'd say the problem is no longer something to do with using a local git repo, but possibly something else.

Note also that `/tmp` is volatile - it is emptied by the OS upon reboot. The choice of this location was deliberate for me (I wanted a clean system after teardown and reboot), but maybe it isn't appropriate for you. 

Hope something there helps.

**Reply by anthonyalayo** [reply]
Thanks a lot @smp4 ! I'll try fiddling with `.git`

**Reply by odelot** [reply]
Sorry for the late answer @smp4 . I followed your example, but I couldn't make it work. Just after adding the reference to the file `-my-appset.yaml` in the list of resources of the file `#overlays/dev/kustomization` I managed to get it working. Thank you for the example and I hope that sharing what I had to do can help someone who is facing the same problem that I faced.

**Comment by cloudcafetech** [comment]
seem issue is TARGET REVISION, cant put blank for file:///

- what I did

```
argopo1=`kubectl get pod -n argocd | grep argocd-server | awk '{print $1}' | head -1`
argopo2=`kubectl get pod -n argocd | grep argocd-server | awk '{print $1}' | tail -1`
kubectl wait pods/$argopo1 --for=condition=Ready --timeout=2m -n argocd
kubectl wait pods/$argopo2 --for=condition=Ready --timeout=2m -n argocd
kubectl exec -it $argopo1 -n argocd -- git clone https://github.com/myrepo/k8s-terraform
kubectl exec -it $argopo2 -n argocd -- git clone https://github.com/myrepo/k8s-terraform
kubectl create -f minio-app.yaml -n argocd
kubectl get apps -n argocd
NAME    SYNC STATUS   HEALTH STATUS
minio   Unknown       Healthy
```
- minio-app.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio-store
    server: 'https://kubernetes.default.svc'
  source:
    path: minio-store
    repoURL: 'file:///home/argocd/k8s-terraform'
    targetRevision: ''
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

![image](https://github.com/argoproj/argo-cd/assets/68260844/7f10abe1-cc08-4592-8262-4617b74184f8)

![image](https://github.com/argoproj/argo-cd/assets/68260844/12e057d8-972d-4dc2-a135-c1d67a3c7cfc)

![image](https://github.com/argoproj/argo-cd/assets/68260844/a4c546b6-545b-45ef-ba1a-41b05967ffa7)

**Reply by anthonyalayo** [reply]
just to be clear, you don't have a working solution as well?

**Reply by ricker-flow** [reply]
I see the exact same behavior. Repository not found error when using a file: url

**Comment by raoakmal55** [comment]
Hi there,

Do we have any working solution to add a local file path instead of a remote git repo in argocd for an application, any example for that would be very helpful. Thank you

**Reply by anthonyalayo** [reply]
I recently looked at this again, and I still do not have anything working. I would ideally like a set up where I'm not continually committing things just to see their effects on a dev environment.

**Comment by sarathsprakash** [comment]
A alternative I think is to override using `app sync` once after the `app create`
`argocd app sync minio --local /home/argocd/k8s-terraform/minio-store`

**Reply by anthonyalayo** [reply]
I tried this, and it only kinda sorta worked. It did a one time sync update, but nothing like a complete tracking of the state of my local filesystem without commits to a repository. It also got complicated with an app of apps pattern.

**Reply by sarathsprakash** [reply]
Yes, I think its expected I don't think `local` is intended for a production rollout anyway. its supposed to be a brute force approach to do adhoc changes while testing or developing your applications.

**Reply by anthonyalayo** [reply]
@sarathsprakash i'm plagued by the following flow. Let's say I have some current argo state, and I just want to upgrade one thing and test if it all works. I would have no problem doing this on my local cluster. However, I need to maintain branches since I'm using helm. I know that maintaining branches (ie. a dev branch) is considered an anti pattern, but I can't figure out the best integration of helm + kustomize so that I don't need to do that. 

For example, let's say I have the following boilerplate setup Chart.yaml for argo + managed apps:
```
apiVersion: v2
name: argocd-helm
description: Bootstrap a self managed argo cd via helm with app-of-apps pattern
type: application
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.34.6
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 1.6.2
    repository: https://argoproj.github.io/argo-helm
```

and I have a corresponding values.yaml for this. I would like to just run Kustomize as a final patch after helm render in order to  add this patch when testing locally:
```
argocd-apps:
  applications:
    - name: argocd
      source:
        helm:
          valueFiles:
            - values.dev.yaml
```

Do you know of a good template/format/etc to do that?

**Reply by smp4** [reply]
Hi @anthonyalayo, i made the base configuration of my homelab cluster available here: https://github.com/smp4/k3s-homelab-gitops

you can check there how i've implemented local repos. for an example of losing config from a helm chart then patching with kustomize, see infrastructure/cert-manager. there are some other examples in there too.

**Reply by sarathsprakash** [reply]
@anthonyalayo  Perhaps a matrix generator of `cluster and git` (child generator) will help you here , Refer https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#using-parameters-from-one-child-generator-in-another-child-generator

**Comment by automaticgiant** [comment]
https://cloud-native.slack.com/archives/C01TSERG0KZ/p1744037512000689?thread_ts=1692600523.577589&cid=C01TSERG0KZ

> arguably, there needs to be some solution to short-circuit the long way - make changes, commit with a message, push somewhere, change the app config to point there, sync...
> i think many of us would appreciate a tighter cli experience (potentially to be integrated into an ide, if that's one's preference) to drive down cycle time when developing a new config that will be deployed/managed with argocd.

**Comment by mdluo** [comment]
Thanks to @smp4 's comment https://github.com/argoproj/argo-cd/discussions/9912#discussioncomment-9025406, I've managed to get it working.

I'm using [tehcyx/kind terraform provider](https://search.opentofu.org/provider/tehcyx/kind/latest/docs/resources/cluster) to run local [kind](https://kind.sigs.k8s.io/) cluster:

Kind config:

```tf
resource "kind_cluster" "this" {
...
  kind_config {
    node {
      role = "control-plane"

      extra_mounts {
        host_path      = "${path.root}/../../"
        container_path = "/mnt/local-repo.git"
        read_only      = true
      }
    }
  }
}
```

Extra values when installing ArgoCD helm chart:

```yaml
repoServer:
  volumes:
    - name: local-repo
      hostPath:
        path: /mnt/local-repo.git
        type: Directory
  volumeMounts:
    - name: local-repo
      mountPath: /mnt/local-repo.git
```

Declarative repo:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: local-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  name: local-repo
  url: file:///mnt/local-repo.git
```
