### DISCUSSION TITLE
Nested groups configuration argocd-rbac-cm

### DISCUSSION THREAD

**Discussion by dsim62** [argoproj/argo-cd#9940] [Q&A]
Hi,

For a customer, we use Active Directory authentication with policy.csv defined in argocd-rbac-cm configmap, for example:

```
g, GP_TEST, role:DEV_TEST
p, role:DEV_TEST, applications, create, *toto*/*, allow
p, role:DEV_TEST, applications, update, *toto*/*, allow
```

Customer reported us that users in a subgroup of GP_TEST, for example GP_TEST_SUBGROUP don't inherit rights from GP_TEST group.

When we debug in the argocd pod as explain here https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md , we notice it :

```
argocd@argocd-server-54c8dd8bbf-8fxpv:~$ argocd admin settings rbac can GP_TEST create applications '*toto*/*' --namespace argocd
Yes
argocd@argocd-server-54c8dd8bbf-8fxpv:~$ argocd admin settings rbac can GP_TEST_SUBGROUP create applications '*toto*/*' --namespace argocd
No
```

is there a configuration in order that the subgroup GP_TEST_SUBGROUP inherit of the rights of GP_TEST group defined in the policy.csv or do we have to specify all the subgroups in the policy ? 

Thank you for your help,

**Comment by Tipsmark** [comment]
Came across similar issue today - just adjust your groups filter and you can use nested groups. So for example we have ArgoCDUsers which contains everyone that can authenticate against ArgoCD, but it provides no access rights to anything. Then we have a k8s.all-groups group which has every k8s.<project> group as member. Thus you just specify that one group in the config and work the rest in AD. ArgoCDAdmins are defined in the policy so admins can just be members of that one group.

Example config:
```
          - type: ldap
            id: active-directory
            name: AD Credentials
            config:
              host: blah.blah.tld:636
              insecureNoSSL: false
              insecureSkipVerify: true
              bindDN: $argocd-ldap-credentials:ldap-user-dn
              bindPW: $argocd-ldap-credentials:ldap-password
              usernamePrompt: Username
              userSearch:
                baseDN: "OU=Accounts,DC=blah,DC=blah,DC=tld"
                filter: "(&(objectclass=user)(objectcategory=person)(|(memberof=CN=ArgoCDUsers,OU=Groups,DC=blah,DC=blah,DC=tld)(memberof=CN=ArgoCDAdmins,OU=AdmGroups,DC=blah,DC=blah,DC=tld)))"
                username: userPrincipalName
                idAttr: distinguishedName
                emailAttr: mail
                nameAttr: displayName
              groupSearch:
                baseDN: "DC=blah,DC=blah,DC=tld"
                filter: "(&(objectClass=group))"
                userMatchers:
                - userAttr: distinguishedName
                  groupAttr: member
                nameAttr: name
              groups:
                - ArgoCDAdmins
                - k8s.all-groups
```
