### DISCUSSION TITLE
argocd setup with ingress

### DISCUSSION THREAD

**Discussion by supertwister** [argoproj/argo-cd#9993] [Q&A]
Hello. I've recently started to learn argocd. I’m trying to setup argocd in AWS using helm and terraform. I want that the argocd will be using ALB as a load balancer.  An ALB was created in AWS as expected. However, it seems that the argocd is not reachable. 

Here is my configuration:
```

---
redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

server:
  extraArgs:
    - --insecure

  autoscaling:
    enabled: true
    minReplicas: 2

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      external-dns.alpha.kubernetes.io/hostname: eks-test-alb-argocd.abc.com
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/certificate-arn: "${cert}"
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
      alb.ingress.kubernetes.io/backend-protocol-version: GRPC
  ingressGrpc:
    enabled: true
    isAWSALB: true
    awsALB:
      serviceType: NodePort
      backendProtocolVersion: HTTP2
  service:
    type: NodePort
```

Here is the ingress that was created:
```
kubectl get ing -n argocd
NAME            CLASS    HOSTS                                ADDRESS                                                                          PORTS   AGE
argocd-server   <none>   eks-test-alb-argocd.abc.com   internal-k8s-argocd-argocdse-111-222.us-east-1.elb.amazonaws.com   80      7h9m
```

What could be the issue?
