### ISSUE TITLE
Openshift Routes are "always" Progressing

### ISSUE THREAD

**Issue by amitkumar2283** [argoproj/argo-cd#10037]
# What am I trying?
We are trying to create a openshift Route using ArgoCD

````yaml
# Route Definition
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: myroute
  name: myroute
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: svc
    weight: null
  tls:
    insecureEdgeTerminationPolicy: edge
    termination: passthrough

# The below config is inspired by https://github.com/argoproj/argo-cd/issues/2370
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
````
ArgoCD Application

````yaml
# ArgoCD application 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-service-infra-cd
  namespace: development
spec:
  destination:
    server: https://kubernetes.default.svc
# trying to ignore route ingress conditions as suggested in https://github.com/argoproj/argo-cd/issues/2370#issuecomment-536270625
  ignoreDifferences:
  - group: route.openshift.io
    jsonPointers:
    - /status/ingress/conditions
    kind: Route
  project: default
  source:
    path: dev
    repoURL: ssh://<redacted>.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
````
# What is the result
Route is created and Admitted in Openshift project

````yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: myroute
  namespace: development
spec:
  host: >-
    <redacted>
  to:
    kind: Service
    name: svc
    weight: 100
  port:
    targetPort: http
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: >-
            <redacted>
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2022-07-15T09:54:54Z'
        - type: Admitted
          status: 'True'
          reason: ClaimedInInfoblox
          message: >-
                <redacted>
            successfully claimed in Infoblox
      wildcardPolicy: None
      routerCanonicalHostname:  <redacted>
````
# Problem
Despite route being created successfully, the ArgoCD application never completes the sync as the route is always in **Progressing** state with status ***Route is still getting admitted***

![image](https://user-images.githubusercontent.com/17488415/179736534-fd67389a-d64d-4104-bb30-4c4b958f6ac8.png)
