### ISSUE TITLE
PreSync hook should run only if changes are detected between git and k8s

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#10052]
The below PreSync works ok in most cases, except when i migrate my k8s workers to a new set of ASGs. In that case it fails if I have an old change jira in git repo (even though all the k8s objects defined in git are already matching what is on my k8s cluster). It continues to fail in a loop every few minutes. My expected behaviour would be that even before running the presync_check.sh it first compares the k8s manifests between git and k8s cluster, if they are same then do nothing (don't need to run presync at all since nothing to deploy), only if the manifests are different then run the presync

```
apiVersion: batch/v1
kind: Job
metadata:
  name: my-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: change-jira-validator
          image: {{ .Values.presync.image.repository }}:{{ .Values.presync.image.version }}
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/env", "bash", "presync_check.sh"]
          env:
            - name: CHANGETICKET
              value: {{.Values.presync.release.change}}
            - name: environment
              value: {{.Values.cluster_context.environment}}
      restartPolicy: Never
  backoffLimit: 0
```
