### ISSUE TITLE
App health status is Healthy even if repoURL is wrong and Application healthcheck is enabled

### ISSUE THREAD

**Issue by yellowmegaman** [argoproj/argo-cd#10088]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

App health status is `Healthy` even if repoURL is wrong and `resource.customizations.health.argoproj.io_Application` is in place.
**To Reproduce**

1. Install ArgoCD on kubernetes
2. Add healthcheck to helm chart values:
```
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        if obj.status ~= nil then
            if obj.status.conditions ~= nil then
                for i, condition in ipairs(obj.status.conditions) do
                    if condition.type == "ComparisonError" and condition.status ~= "False" then
                        hs.status = "Degraded"
                        hs.message = "can't deploy"
                        return hs
                    elseif obj.status.phase == nil then
                        hs.status = "Degraded"
                        hs.message = "phase nil"
                        return hs
                    elseif ( obj.status.phase == "Succeeded" or obj.status.phase == "Initialized" ) then
                      hs.status = "Healthy"
                    end
                end
            end
        elseif obj.status == nil then
          hs.status = "Degraded"
          hs.message = "unknown status"
          return hs
        end
        hs.status = "Healthy"
        hs.message = "Seems to be fine"
        return hs
```
3. Apply Application with wrong definition:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wrong
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/wrongurl/wrongrepo.git
    path: absolutelywrong
    targetRevision: v3.0.4
  destination:
    name: 'in-cluster'
    namespace: wrong
```
**Expected behavior**

Application health status should not be `Healthy`
**Screenshots**

<img width="988" alt="image" src="https://user-images.githubusercontent.com/3943191/180665153-fc9ef377-2d81-440d-bd80-091061557d91.png">

**Version**

```shell
argocd: v2.4.7+81630e6
  BuildDate: 2022-07-18T21:17:35Z
  GitCommit: 81630e6d5075ac53ac60457b51343c2a09a666f4
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
$ kubectl -n argocd get app wrong -o yaml
...
status:
  conditions:
  - lastTransitionTime: "2022-07-24T20:20:26Z"
    message: 'rpc error: code = Unknown desc = authentication required'
    type: ComparisonError
  health:
    status: Healthy
  reconciledAt: "2022-07-24T20:43:58Z"
  sync:
    comparedTo:
      destination:
        name: in-cluster
        namespace: wrong
      source:
        path: absolutelywrong
        repoURL: https://github.com/wrongurl/wrongrepo.git
        targetRevision: v3.0.4
    status: Unknown
```
Question: is there a way to modify health.lua to set proper health status? It is working for the app-of-apps Application (Status is Degraded, if `wrong` application is part of it), but not for the actual `wrong` app.

**Comment by aagu** [comment]
same problem here, be closed without solution

#9745

**Comment by yellowmegaman** [comment]
> same problem here, be closed without solution
> 
> #9745 

Thanks for the reply! 
The difference is that I do address ComparisonError in health.lua for kind: Application

**Comment by yellowmegaman** [comment]
If relevant, if `wrong` app is part of app-of-apps, everything is almost great. Almost because app-of-apps is degraded, `wrong` app is degraded too, but the UI is showing Health OK if I go to the `wrong` app.

App-of-apps:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/3943191/180855876-119fadf2-42d5-425d-99c4-af466b7997e9.png">
Wrong app:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/3943191/180855991-a43d1806-e328-4006-b73a-f7d81fbc31e9.png">

API status for app-of-apps:
```
...
  - group: argoproj.io
    health:
      message: can't deploy
      status: Degraded
    kind: Application
    name: wrong-sonic
    namespace: argocd
    status: Synced
    version: v1alpha1
...
```

API status for worng app as part of app-of-apps:
```
...
status:
  conditions:
  - lastTransitionTime: "2022-07-25T19:12:30Z"
    message: 'rpc error: code = Unknown desc = `helm pull --destination /tmp/8be01600-0064-48f0-be17-1d8b813041b6
      --version v3.0.4 --repo https://chartmuseum.wrong.url chart-wrong-sonic --pass-credentials`
      failed exit status 1: Error: looks like "https://chartmuseum.wrong.url" is not
      a valid chart repository or cannot be reached: Get "https://chartmuseum.wrong.url/index.yaml":
      dial tcp: lookup chartmuseum.wrong.url on 10.43.0.10:53: no such host'
    type: ComparisonError
  health:
    status: Healthy
...
```
