### ISSUE TITLE
Support resource filtering in Application controller

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1010]
There are some cases when users don't want Argo CD to touch some cluster resources:

- Temporal issues with installed extension api-server. Filter could be use to exclude problematic resource (https://github.com/argoproj/argo-cd/issues/1006 )
- Some users install Argo CD to manage only namespace resources and don't want to give cluster wide access.

It would be useful to support application controller configuration which allows excluding some resources.

I would propose to add `excludedResources` settings to `argocd-cm` with the following fields: 
* `group`, `kind` -  excluded resource group and kind ( should support wildcard matching )
* `scope` - optional field which takes on of following values: `any`, `namespaced`, `cluster-wide`
* `clusterURL` - optional field to narrow filtering to a single cluster

Example:
```
excludedResources:
  - group: istio.io
    kind: *
  - scope: cluster-wide
  - group: calico
    kind: *
    clusterURL: https://mycluster.com:443
```

**Comment by jessesuen** [comment]
> Note: if api extension server is down then discovery api does not work as well. We will have to stop using disco.ServerPreferredResources() in kube.go to avoid listing resources for filtered out groups.

Luckily the `disco.ServerPreferredResources()` method will return partially complete list of api resources, so we don't need to go that route and continue using the standard go-client interfaces.

> Some users install Argo CD to manage only namespace resources and don't want to give cluster wide access.

I actually feel this is a bit contrived use case and I don't think we need to do anything here.

> I would propose to add excludedResources settings to argocd-cm with the following fields:

Can we make the datastructure more similar to K8s RBAC rules where groups/kinds are a list? Examples:

```
excludedResources:
  # exclude all servicecatalog.k8s.io kinds
  - apiGroups:
    - servicecatalog.k8s.io
    kinds:
    - *
  # exclude NeworkPolicy
  - apiGroups:
    - extensions
    - networking.k8s.io
    kinds:
    - NetworkPolicy
  # exclude Secrets, but only from https://mycluster.com:443
  - apiGroups:
    - ""
    kinds:
    - Secret
    clusters:
    - https://mycluster.com:443
```

**Comment by alexec** [comment]
Example of RBAC "rules":

```
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
```
