### ISSUE TITLE
kubectl v1.13 fails to convert extensions/NetworkPolicy

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1012]
Encountered the following issue with an application which had extensions/NetworkPolicy. Downgrading the kubectl from v1.13.1 to v1.12.4 fixed the issue.

```
$ argocd app get APPNAME
Name:               APPNAME
Server:             <REDACTED>
Namespace:          APPNAME
URL:                https://<REDACTED>/applications/APPNAME
Repo:               <REDACTED>
Target:             HEAD
Path:               .
Environment:        qal
Sync Policy:        <none>
Sync Status:        Unknown (0ecd09d)
Health Status:      Missing

CONDITION        MESSAGE
ComparisonError  kubectl convert is DEPRECATED and will be removed in a future version.
In order to convert, kubectl apply the object to the cluster, then kubectl get at the desired version.
error: unable to decode "/dev/shm/573599277": no kind "NetworkPolicy" is registered for version "networking.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"


GROUP                         KIND              NAMESPACE    NAME                                                           STATUS     HEALTH
extensions                    NetworkPolicy     APPNAME      allow-egress-knative                                           OutOfSync  Missing
...
...
```

We should stop using `kubectl` convert

**Comment by jessesuen** [comment]
The following kustomize overlay can be used to workaround to downgrade the kubectl used in the application-controller:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - wget https://storage.googleapis.com/kubernetes-release/release/v1.12.4/bin/linux/amd64/kubectl &&
          chmod +x kubectl &&
          mv kubectl /custom-tools
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
        resources:
          requests:
            memory: 64M
            cpu: 0.02
      containers:
      - name: argocd-application-controller
        volumeMounts:
        - mountPath: /usr/local/bin/kubectl
          name: custom-tools
          subPath: kubectl
```
