### ISSUE TITLE
No dump is created when during OOM

### ISSUE THREAD

**Issue by yatakoi** [argoproj/argo-cd#10122]
Hello.

ArgoCD 2.3.3
Kubernetes 1.22.2

We have an application in Java. When OOM occurs, the application writes a memory dump to `/var/tmp/dump`. Dump argument `-XX:HeapDumpPath=/var/tmp/dump/${HOSTNAME}_dump.href`
The `/var/tmp/dump/` directory when inspecting PersistentVolume.

Before ArgoDD, we launched the application using Helm, and when we met OOM, , the dump was successfully created.

When we implemented ArgoСD, it looks like the dump does not have time to be created during OOM, because ArgoСD immediately restarts the container inside the pod.

Maybe I'm wrong, but before the introduction of ArgoСD, we created dumps. Can you tell me what I need to fix in ArgoСD so that the dump can be created?

**Our application:**
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-phd-graphql-server-02-replica
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/alias_image1.helm.image-name: rr.image.repository
    argocd-image-updater.argoproj.io/alias_image1.helm.image-tag: rr.image.tag
    argocd-image-updater.argoproj.io/alias_image1.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: alias_image1=nexus.domain.com:8444/rr/phd/phd-graphql-server/phd-graphql-server:develop

spec:
  project: default
  source:
    repoURL: 'https://gitlab.domain.com/rr/deploy.git'
    path: phd/phd-graphql-server-02-replica/dev
    targetRevision: main
    helm:
      valueFiles:
        - values-phd-graphql-server-02-replica.yaml
  destination:
    server: https://k8s.domain.com:6443
    namespace: phd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
