### ISSUE TITLE
Add health check for API Services

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1017]
API Services could be assessed as Degraded if they have this condition:
```
status:
  conditions:
  - lastTransitionTime: "2018-12-23T20:56:17Z"
    message: 'no response from https://100.68.217.200:443: Get https://100.68.217.200:443:
      dial tcp 100.68.217.200:443: getsockopt: connection refused'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```
