### ISSUE TITLE
A Merge Generator with two git generators does not work

### ISSUE THREAD

**Issue by jmccrumm** [argoproj/argo-cd#10189]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have values files for my helm application in two different external repositories that I would like to apply to my single application. I tried using a merge generator as pasted below, but it always seems to only use the first entry for git generator.

**To Reproduce**

Here is my ApplicationSet spec:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
  namespace: argocd
spec:
  generators:
    - merge:
        generators:
          - git:
              files:
                - path: path/to/first.yaml
              repoURL: 'ssh://git@mybitbucket/myproject/first-repo.git'
              revision: master
          - git:
              files:
                - path: path/to/second.yaml
              epoURL: 'ssh://git@mybitbucket/myproject/second-repo.git'
              revision: master
        mergeKeys:
          - firstValues
          - secondValues
  template:
    metadata:
      name: my-app
    spec:
      destination:
        namespace: default
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        helm:
          valueFiles:
            - some-local-values.yaml
          values: |-
            {{firstValues}}
            {{secondValues}}
        path: path/to/myapp/
        repoURL: 'ssh://git@bitbucket/myotherproject/my-app.git'
        targetRevision: master
```
My `first.yaml` values file looks like so:
```yaml
firstValues: |
  key1: value1
  ...
```
(and similarly with `second.yaml` and `secondValues`)

**Expected behavior**

The helm `values` in ArgoCD to resolve to the content under `firstValues` and `secondValues`, respectively.

**Screenshots**

Instead of resolving both items under `values`, it only ever resolves `firstValues`, while `secondValues` is always just `{{secondValues}}` unresolved, causing a yaml parsing error of course. If I swap the order of the generators and point to `second-repo` first, `secondValues` will get resolved but `firstValues` will remain unresolved. It seems only the first `git` generator entry is being applied.

**Version**

```shell
argocd: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T11:41:37Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.4+ac8b7df
```

**Logs**

```
N/A
```
