### ISSUE TITLE
Expose pull request labels in Pull Request generator template

### ISSUE THREAD

**Issue by itmustbejj** [argoproj/argo-cd#10204]
# Summary

Expose pull request labels in the template context for applicationsets using the pull request generator.

# Motivation

As a user I would like to use pull request labels to customize the templating of application sets using the pull request generator
# Proposal

How do you think this should be implemented?
Extend the[ PullRequest struct](https://github.com/argoproj/argo-cd/blob/master/applicationset/services/pull_request/interface.go#L8-L15) to include labels populated from each provider's appropriate pull request details call.

**Comment by james-callahan** [comment]
This is my #2 request to make the pull request generator usable for us: we only want to deploy pull requests with a certain github label.

**Comment by Aym3nTN** [comment]
I can work on this one, can someone assign it to me?

**Comment by ragrag** [comment]
i think this would be extremely useful and has lots of use-cases, 
would be really nice to also expose the PR body especially after was merged https://github.com/argoproj/argo-cd/pull/10026, which would open the door for lots of template customisation capabilities

**Comment by harisaisundhar** [comment]
Hey team, I'm starting to work on this case

**Comment by yuval0499** [comment]
I'm interested in working on this.
As I can see the right now, only [GithubService](https://github.com/argoproj/argo-cd/blob/6a7d79f8e0d1c583f182cf16b63142506f405923/applicationset/services/pull_request/github.go#L12) and [GitLabService](https://github.com/argoproj/argo-cd/blob/6a7d79f8e0d1c583f182cf16b63142506f405923/applicationset/services/pull_request/gitlab.go#L11) are having labels, while [BitbucketService](https://github.com/argoproj/argo-cd/blob/6a7d79f8e0d1c583f182cf16b63142506f405923/applicationset/services/pull_request/bitbucket_server.go#L12) and [GiteaService](https://github.com/argoproj/argo-cd/blob/6a7d79f8e0d1c583f182cf16b63142506f405923/applicationset/services/pull_request/gitea.go#L13)
Do not have.
Should we have first only for Gitlab and Gitlab the option to use the pull request label in the template ?
Or to add this option also to Bitbucket and Gitea.

**Comment by maheshbaliga** [comment]
Hi @itmustbejj, I am working on this issue. Will raise a PR soon. If the pull request has multiple labels - `exp1` & `exp2`, will the value of `labels` (new field) in the PullRequest struct be a comma separated string like `exp1,exp2`?

**Comment by txt-bmukum** [comment]
I'm guessing {{labels}} is a variable from the pullRequest generator. Can that variable be used inside of a git generator?
Like:
```
spec:
  generators:
      - matrix:
          generators:
            - pullRequest:
              ...
            - git:
                repoURL: https://github.com/myrepo/repo.git
                revision: main
                files:
                  - path: 'deploy/{{ labels }}/config.json'
 ```
