### ISSUE TITLE
App history in CLI doesn't contain health results

### ISSUE THREAD

**Issue by AlexDHoffer** [argoproj/argo-cd#10244]
# Summary

When you run ``argocd app get [my-app] -o yaml`` and check an Application's history, the entries don't contain Health statuses. For example, I think it would be useful if the history list looked like:

````
- deployStartedAt: "2022-05-26T22:56:28Z"
    deployedAt: "2022-05-26T22:56:29Z"
    id: 0
    revision: ...
    source:
      helm:
        releaseName: ...
        valueFiles:
        - ...
      path: .
      repoURL: ..
      targetRevision: ...
      health:
        status: Degraded
````

There may also be a case for containing the sync status from this operation, but it isn't relevant to our current situation.

# Motivation

We'd like to know the currently active deployment that is actually healthy/alive. In the event that a sync leads to a failed deployment, the old pods are still up. In theory, multiple failed syncs could occur and muddy the ability via History to know which commit is actually serving traffic.

# Proposal

How do you think this should be implemented?

I'm not sure if this information is readily available to the History list. If it is, use that. If not, there's an intermediary step requiring the collection of health data and populating it for use later.
