### ISSUE TITLE
Allow to add additional resources to an Application

### ISSUE THREAD

**Issue by gigi206** [argoproj/argo-cd#10258]
# Summary

Add the possibility to add custom resources yaml to an `Application`.

# Motivation

Some charts don't allow to add custom yaml values. In some cases, it could be great to add custom code to the original chart.

# Proposal

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/xxx/yyy/'
    path: client/config/crd
    targetRevision: v4.2.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myns
  syncPolicy:
    syncOptions:
      - PruneLast=true
  additionalResources:
    # valueFiles: []
    values: |
      apiVersion: v1
      kind: Service
      metadata:
        name: my-service
      spec:
        selector:
          app: MyApp
        ports:
          - protocol: TCP
            port: 80
            targetPort: 9376
```
