### ISSUE TITLE
Missing metrics for the grafana dashboard

### ISSUE THREAD

**Issue by gigi206** [argoproj/argo-cd#10272]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I import [examples/dashboard.json](https://github.com/argoproj/argo-cd/blob/master/examples/dashboard.json) in Grafana but metrics called by the dashboard don't exist and generate empty graphs. 

**To Reproduce**

I installed the **argocd** chart with metrics enabled. All targets generated by `serviceMonitor` are healthy in the prometheus dashboard:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: argo-cd
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: '4.10.4'
    helm:
      parameters:
        ...
        ...
        ...
        - name: applicationSet.metrics.enabled
          value: 'true'
        - name: applicationSet.metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        - name: applicationSet.metrics.serviceMonitor.enabled
          value: 'true'
        - name: controller.metrics.applicationLabels.enabled
          value: 'true'
        - name: controller.metrics.enabled
          value: 'true'
        - name: controller.metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        - name: dex.metrics.enabled
          value: 'true'
        - name: dex.metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        - name: notifications.metrics.enabled
          value: 'true'
        - name: notifications.metrics.serviceMonitor.enabled
          value: 'true'
        - name: notifications.metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        - name: redis-ha.haproxy.metrics.enabled
          value: 'true'
        - name: redis.metrics.enabled
          value: 'true'
        - name: redis.metrics.serviceMonitor.enabled
          value: 'true'
        - name: redis.metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        - name: repoServer.metrics.enabled
          value: 'true'
        - name: repoServer.metrics.serviceMonitor.enabled
          value: 'true'
        - name: repoServer.metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        - name: server.metrics.enabled
          value: 'true'
        - name: server.metrics.serviceMonitor.enabled
          value: 'true'
        - name: server.metrics.serviceMonitor.additionalLabels.release
          value: prometheus-stack
        # Prometheus rules
        - name: controller.metrics.rules.enabled
          value: 'true'
        - name: controller.metrics.rules.additionalLabels.release
          value: prometheus-stack
        - name: controller.metrics.rules.spec[0].alert
          value: ArgoAppMissing
        - name: controller.metrics.rules.spec[0].expr
          value: |-
            absent(argocd_app_info)
        - name: controller.metrics.rules.spec[0].for
          value: 15m
        - name: controller.metrics.rules.spec[0].labels.severity
          value: critical
        - name: controller.metrics.rules.spec[0].annotations.summary
          value: '[Argo CD] No reported applications'
        - name: controller.metrics.rules.spec[0].annotations.description
          value: >-
            Argo CD has not reported any applications data for the past 15 minutes which
            means that it must be down or not functioning properly.  This needs to be
            resolved for this cloud to continue to maintain state.
        - name: controller.metrics.rules.spec[1].alert
          value: ArgoAppNotSynced
        - name: controller.metrics.rules.spec[1].expr
          value: |-
            argocd_app_info{sync_status!="Synced"} == 1
        - name: controller.metrics.rules.spec[1].for
          value: 12h
        - name: controller.metrics.rules.spec[1].labels.severity
          value: warning
        - name: controller.metrics.rules.spec[1].annotations.summary
          value: '[{{`{{$labels.name}}`}}] Application not synchronized'
        - name: controller.metrics.rules.spec[1].annotations.description
          value: >-
            The application [{{`{{$labels.name}}`}} has not been synchronized for over
            12 hours which means that the state of this cloud has drifted away from the
            state inside Git.
```

**Expected behavior**

Grafana dashboard must work.

**Version**

```shell
argocd --port-forward --port-forward-namespace argo-cd --insecure version
argocd: v2.4.8+844f79e
  BuildDate: 2022-07-29T17:23:00Z
  GitCommit: 844f79eb9d8f3ab96d4ce6f8df211c6093a660ba
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.8+844f79e
```

**Metrics**

argo-cd-argocd-applicationset-controller
```
controller_runtime_active_workers{controller="applicationset"} 0
controller_runtime_max_concurrent_reconciles{controller="applicationset"} 1
controller_runtime_reconcile_errors_total{controller="applicationset"} 0
controller_runtime_reconcile_total{controller="applicationset",result="error"} 0
controller_runtime_reconcile_total{controller="applicationset",result="requeue"} 0
controller_runtime_reconcile_total{controller="applicationset",result="requeue_after"} 0
controller_runtime_reconcile_total{controller="applicationset",result="success"} 0
go_gc_duration_seconds{quantile="0"} 2.8379e-05
go_gc_duration_seconds{quantile="0.25"} 4.3264e-05
go_gc_duration_seconds{quantile="0.5"} 5.5158e-05
go_gc_duration_seconds{quantile="0.75"} 7.0617e-05
go_gc_duration_seconds{quantile="1"} 0.000997589
go_gc_duration_seconds_sum 0.001752107
go_gc_duration_seconds_count 13
go_goroutines 87
go_info{version="go1.18.4"} 1
go_memstats_alloc_bytes 1.3988168e+07
go_memstats_alloc_bytes_total 6.1498584e+07
go_memstats_buck_hash_sys_bytes 1.512272e+06
go_memstats_frees_total 286944
go_memstats_gc_cpu_fraction 7.782732791031383e-06
go_memstats_gc_sys_bytes 5.856952e+06
go_memstats_heap_alloc_bytes 1.3988168e+07
go_memstats_heap_idle_bytes 1.3811712e+07
go_memstats_heap_inuse_bytes 1.8300928e+07
go_memstats_heap_objects 59860
go_memstats_heap_released_bytes 1.339392e+07
go_memstats_heap_sys_bytes 3.211264e+07
go_memstats_last_gc_time_seconds 1.660168685899005e+09
go_memstats_lookups_total 0
go_memstats_mallocs_total 346804
go_memstats_mcache_inuse_bytes 19200
go_memstats_mcache_sys_bytes 31200
go_memstats_mspan_inuse_bytes 320552
go_memstats_mspan_sys_bytes 342720
go_memstats_next_gc_bytes 2.5797264e+07
go_memstats_other_sys_bytes 2.825568e+06
go_memstats_stack_inuse_bytes 1.441792e+06
go_memstats_stack_sys_bytes 1.441792e+06
go_memstats_sys_bytes 4.4123144e+07
go_threads 20
process_cpu_seconds_total 0.95
process_max_fds 1.048576e+06
process_open_fds 14
process_resident_memory_bytes 7.9880192e+07
process_start_time_seconds 1.66016778536e+09
process_virtual_memory_bytes 8.21932032e+08
process_virtual_memory_max_bytes 1.8446744073709552e+19
rest_client_requests_total{code="200",host="10.43.0.1:443",method="GET"} 127
rest_client_requests_total{code="404",host="10.43.0.1:443",method="GET"} 2
rest_client_requests_total{code="503",host="10.43.0.1:443",method="GET"} 4
```

argo-cd-argocd-notifications-controller
```
go_gc_duration_seconds{quantile="0"} 2.9554e-05
go_gc_duration_seconds{quantile="0.25"} 3.5857e-05
go_gc_duration_seconds{quantile="0.5"} 9.0277e-05
go_gc_duration_seconds{quantile="0.75"} 0.00035432
go_gc_duration_seconds{quantile="1"} 0.002360054
go_gc_duration_seconds_sum 0.006212601
go_gc_duration_seconds_count 14
go_goroutines 50
go_info{version="go1.18.4"} 1
go_memstats_alloc_bytes 1.517644e+07
go_memstats_alloc_bytes_total 7.69578e+07
go_memstats_buck_hash_sys_bytes 1.507576e+06
go_memstats_frees_total 600599
go_memstats_gc_cpu_fraction 1.2180401181935107e-05
go_memstats_gc_sys_bytes 5.77672e+06
go_memstats_heap_alloc_bytes 1.517644e+07
go_memstats_heap_idle_bytes 1.3049856e+07
go_memstats_heap_inuse_bytes 1.929216e+07
go_memstats_heap_objects 64685
go_memstats_heap_released_bytes 9.265152e+06
go_memstats_heap_sys_bytes 3.2342016e+07
go_memstats_last_gc_time_seconds 1.660168704109167e+09
go_memstats_lookups_total 0
go_memstats_mallocs_total 665284
go_memstats_mcache_inuse_bytes 19200
go_memstats_mcache_sys_bytes 31200
go_memstats_mspan_inuse_bytes 328984
go_memstats_mspan_sys_bytes 359040
go_memstats_next_gc_bytes 2.798384e+07
go_memstats_other_sys_bytes 3.15632e+06
go_memstats_stack_inuse_bytes 1.212416e+06
go_memstats_stack_sys_bytes 1.212416e+06
go_memstats_sys_bytes 4.4385288e+07
go_threads 18
process_cpu_seconds_total 0.66
process_max_fds 1.048576e+06
process_open_fds 11
process_resident_memory_bytes 8.050688e+07
process_start_time_seconds 1.66016778298e+09
process_virtual_memory_bytes 8.22194176e+08
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

argo-cd-argocd-redis
```
go_gc_duration_seconds{quantile="0"} 3.8391e-05
go_gc_duration_seconds{quantile="0.25"} 7.3075e-05
go_gc_duration_seconds{quantile="0.5"} 9.9513e-05
go_gc_duration_seconds{quantile="0.75"} 0.000165607
go_gc_duration_seconds{quantile="1"} 0.000435112
go_gc_duration_seconds_sum 0.001219116
go_gc_duration_seconds_count 9
go_goroutines 8
go_info{version="go1.16.7"} 1
go_memstats_alloc_bytes 3.658952e+06
go_memstats_alloc_bytes_total 2.3375488e+07
go_memstats_buck_hash_sys_bytes 1.44904e+06
go_memstats_frees_total 148015
go_memstats_gc_cpu_fraction 2.2356009831440173e-06
go_memstats_gc_sys_bytes 4.952496e+06
go_memstats_heap_alloc_bytes 3.658952e+06
go_memstats_heap_idle_bytes 6.148096e+07
go_memstats_heap_inuse_bytes 4.939776e+06
go_memstats_heap_objects 8632
go_memstats_heap_released_bytes 6.0547072e+07
go_memstats_heap_sys_bytes 6.6420736e+07
go_memstats_last_gc_time_seconds 1.6601688311884017e+09
go_memstats_lookups_total 0
go_memstats_mallocs_total 156647
go_memstats_mcache_inuse_bytes 19200
go_memstats_mcache_sys_bytes 32768
go_memstats_mspan_inuse_bytes 115328
go_memstats_mspan_sys_bytes 131072
go_memstats_next_gc_bytes 6.398224e+06
go_memstats_other_sys_bytes 1.906184e+06
go_memstats_stack_inuse_bytes 688128
go_memstats_stack_sys_bytes 688128
go_memstats_sys_bytes 7.5580424e+07
go_threads 11
process_cpu_seconds_total 0.29
process_max_fds 1.048576e+06
process_open_fds 11
process_resident_memory_bytes 1.5450112e+07
process_start_time_seconds 1.66016781178e+09
process_virtual_memory_bytes 7.31430912e+08
process_virtual_memory_max_bytes 1.8446744073709552e+19
redis_active_defrag_running 0
redis_allocator_active_bytes 4.1476096e+07
redis_allocator_allocated_bytes 4.0920648e+07
redis_allocator_frag_bytes 555448
redis_allocator_frag_ratio 1.01
redis_allocator_resident_bytes 4.6067712e+07
redis_allocator_rss_bytes 4.591616e+06
redis_allocator_rss_ratio 1.11
redis_aof_current_rewrite_duration_sec -1
redis_aof_enabled 0
redis_aof_last_bgrewrite_status 1
redis_aof_last_cow_size_bytes 0
redis_aof_last_rewrite_duration_sec -1
redis_aof_last_write_status 1
redis_aof_rewrite_in_progress 0
redis_aof_rewrite_scheduled 0
redis_blocked_clients 0
redis_client_recent_max_input_buffer_bytes 20480
redis_client_recent_max_output_buffer_bytes 0
redis_cluster_connections 0
redis_cluster_enabled 0
redis_commands_duration_seconds_total{cmd="client|setname"} 0.00012
redis_commands_duration_seconds_total{cmd="config|get"} 0.009968
redis_commands_duration_seconds_total{cmd="get"} 0.011394
redis_commands_duration_seconds_total{cmd="info"} 0.009693
redis_commands_duration_seconds_total{cmd="latency|latest"} 5e-05
redis_commands_duration_seconds_total{cmd="ping"} 0.001408
redis_commands_duration_seconds_total{cmd="publish"} 0.000244
redis_commands_duration_seconds_total{cmd="scan"} 2.1e-05
redis_commands_duration_seconds_total{cmd="set"} 0.004753
redis_commands_duration_seconds_total{cmd="slowlog|get"} 8.1e-05
redis_commands_duration_seconds_total{cmd="slowlog|len"} 3.2e-05
redis_commands_duration_seconds_total{cmd="subscribe"} 2.6e-05
redis_commands_processed_total 1070
redis_commands_total{cmd="client|setname"} 29
redis_commands_total{cmd="config|get"} 29
redis_commands_total{cmd="get"} 95
redis_commands_total{cmd="info"} 28
redis_commands_total{cmd="latency|latest"} 28
redis_commands_total{cmd="ping"} 334
redis_commands_total{cmd="publish"} 157
redis_commands_total{cmd="scan"} 4
redis_commands_total{cmd="set"} 309
redis_commands_total{cmd="slowlog|get"} 28
redis_commands_total{cmd="slowlog|len"} 28
redis_commands_total{cmd="subscribe"} 1
redis_config_maxclients 10000
redis_config_maxmemory 0
redis_connected_clients 11
redis_connected_slaves 0
redis_connections_received_total 45
redis_cpu_sys_children_seconds_total 0
redis_cpu_sys_seconds_total 0.787846
redis_cpu_user_children_seconds_total 0.000494
redis_cpu_user_seconds_total 0.964078
redis_db_avg_ttl_seconds{db="db0"} 28890.897
redis_db_keys{db="db0"} 41
redis_db_keys{db="db1"} 0
redis_db_keys{db="db10"} 0
redis_db_keys{db="db11"} 0
redis_db_keys{db="db12"} 0
redis_db_keys{db="db13"} 0
redis_db_keys{db="db14"} 0
redis_db_keys{db="db15"} 0
redis_db_keys{db="db2"} 0
redis_db_keys{db="db3"} 0
redis_db_keys{db="db4"} 0
redis_db_keys{db="db5"} 0
redis_db_keys{db="db6"} 0
redis_db_keys{db="db7"} 0
redis_db_keys{db="db8"} 0
redis_db_keys{db="db9"} 0
redis_db_keys_expiring{db="db0"} 41
redis_db_keys_expiring{db="db1"} 0
redis_db_keys_expiring{db="db10"} 0
redis_db_keys_expiring{db="db11"} 0
redis_db_keys_expiring{db="db12"} 0
redis_db_keys_expiring{db="db13"} 0
redis_db_keys_expiring{db="db14"} 0
redis_db_keys_expiring{db="db15"} 0
redis_db_keys_expiring{db="db2"} 0
redis_db_keys_expiring{db="db3"} 0
redis_db_keys_expiring{db="db4"} 0
redis_db_keys_expiring{db="db5"} 0
redis_db_keys_expiring{db="db6"} 0
redis_db_keys_expiring{db="db7"} 0
redis_db_keys_expiring{db="db8"} 0
redis_db_keys_expiring{db="db9"} 0
redis_defrag_hits 0
redis_defrag_key_hits 0
redis_defrag_key_misses 0
redis_defrag_misses 0
redis_evicted_keys_total 0
redis_expired_keys_total 4
redis_expired_stale_percentage 0
redis_expired_time_cap_reached_total 0
redis_exporter_build_info{build_date="2021-08-21-13:32:47",commit_sha="89f8140215c3f26660e9413a5d36d5dfc6228463",golang_version="go1.16.7",version="v1.26.0"} 1
redis_exporter_last_scrape_connect_time_seconds 0.000511223
redis_exporter_last_scrape_duration_seconds 0.003268559
redis_exporter_last_scrape_error{err=""} 0
redis_exporter_scrape_duration_seconds_sum 0.08240738900000001
redis_exporter_scrape_duration_seconds_count 29
redis_exporter_scrapes_total 29
redis_instance_info{maxmemory_policy="noeviction",os="Linux 5.10.0-16-amd64 x86_64",process_id="1",redis_build_id="6eab029cc2ef228b",redis_mode="standalone",redis_version="7.0.4",role="master",run_id="f02d66c8fe3214185468924f9b31addafd99051a",tcp_port="6379"} 1
redis_keyspace_hits_total 74
redis_keyspace_misses_total 21
redis_last_key_groups_scrape_duration_milliseconds 0
redis_last_slow_execution_duration_seconds 0
redis_latest_fork_seconds 0
redis_lazyfree_pending_objects 0
redis_loading_dump_file 0
redis_master_repl_offset 0
redis_mem_clients_normal 76160
redis_mem_clients_slaves 0
redis_mem_fragmentation_bytes 5.520824e+06
redis_mem_fragmentation_ratio 1.14
redis_mem_not_counted_for_eviction_bytes 0
redis_memory_max_bytes 0
redis_memory_used_bytes 4.0603344e+07
redis_memory_used_dataset_bytes 3.9660496e+07
redis_memory_used_lua_bytes 31744
redis_memory_used_overhead_bytes 942848
redis_memory_used_peak_bytes 9.0741752e+07
redis_memory_used_rss_bytes 4.6084096e+07
redis_memory_used_scripts_bytes 184
redis_memory_used_startup_bytes 862856
redis_migrate_cached_sockets_total 0
redis_module_fork_in_progress 0
redis_module_fork_last_cow_size 0
redis_net_input_bytes_total 1.02663923e+08
redis_net_output_bytes_total 2.5770494e+07
redis_process_id 1
redis_pubsub_channels 1
redis_pubsub_patterns 0
redis_rdb_bgsave_in_progress 0
redis_rdb_changes_since_last_save 309
redis_rdb_current_bgsave_duration_sec -1
redis_rdb_last_bgsave_duration_sec -1
redis_rdb_last_bgsave_status 1
redis_rdb_last_cow_size_bytes 0
redis_rdb_last_save_timestamp_seconds 1.660167812e+09
redis_rejected_connections_total 0
redis_repl_backlog_first_byte_offset 0
redis_repl_backlog_history_bytes 0
redis_repl_backlog_is_active 0
redis_replica_partial_resync_accepted 0
redis_replica_partial_resync_denied 0
redis_replica_resyncs_full 0
redis_replication_backlog_bytes 1.048576e+06
redis_second_repl_offset -1
redis_slave_expires_tracked_keys 0
redis_slowlog_last_id 0
redis_slowlog_length 0
redis_start_time_seconds 1.660167812e+09
redis_target_scrape_request_errors_total 0
redis_tracking_clients 0
redis_up 1
redis_uptime_in_seconds 1035
```

argo-cd-argocd-repo-server
```
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="0.1"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="0.25"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="0.5"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="1"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="2"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="4"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="10"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="20"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="fetch",le="+Inf"} 1
argocd_git_request_duration_seconds_sum{repo="https://github.com/gigi206/k8s",request_type="fetch"} 0.43458689
argocd_git_request_duration_seconds_count{repo="https://github.com/gigi206/k8s",request_type="fetch"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="0.1"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="0.25"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="0.5"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="1"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="2"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="4"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="10"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="20"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/gigi206/k8s",request_type="ls-remote",le="+Inf"} 3
argocd_git_request_duration_seconds_sum{repo="https://github.com/gigi206/k8s",request_type="ls-remote"} 0.817073136
argocd_git_request_duration_seconds_count{repo="https://github.com/gigi206/k8s",request_type="ls-remote"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="0.1"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="0.25"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="0.5"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="1"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="2"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="4"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="10"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="20"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch",le="+Inf"} 1
argocd_git_request_duration_seconds_sum{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch"} 0.515976639
argocd_git_request_duration_seconds_count{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch"} 1
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="0.1"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="0.25"} 0
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="0.5"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="1"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="2"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="4"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="10"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="20"} 3
argocd_git_request_duration_seconds_bucket{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote",le="+Inf"} 3
argocd_git_request_duration_seconds_sum{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote"} 1.031003722
argocd_git_request_duration_seconds_count{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote"} 3
argocd_git_request_total{repo="https://github.com/gigi206/k8s",request_type="fetch"} 1
argocd_git_request_total{repo="https://github.com/gigi206/k8s",request_type="ls-remote"} 3
argocd_git_request_total{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="fetch"} 1
argocd_git_request_total{repo="https://github.com/kubernetes-csi/external-snapshotter/",request_type="ls-remote"} 3
argocd_redis_request_duration_seconds_bucket{initiator="argocd-repo-server",le="0.1"} 128
argocd_redis_request_duration_seconds_bucket{initiator="argocd-repo-server",le="0.25"} 128
argocd_redis_request_duration_seconds_bucket{initiator="argocd-repo-server",le="0.5"} 128
argocd_redis_request_duration_seconds_bucket{initiator="argocd-repo-server",le="1"} 128
argocd_redis_request_duration_seconds_bucket{initiator="argocd-repo-server",le="2"} 128
argocd_redis_request_duration_seconds_bucket{initiator="argocd-repo-server",le="+Inf"} 128
argocd_redis_request_duration_seconds_sum{initiator="argocd-repo-server"} 0.17139503299999997
argocd_redis_request_duration_seconds_count{initiator="argocd-repo-server"} 128
argocd_redis_request_total{failed="false",initiator="argocd-repo-server"} 128
argocd_repo_pending_request_total{repo="https://argoproj.github.io/argo-helm"} 0
argocd_repo_pending_request_total{repo="https://charts.bitnami.com/bitnami"} 0
argocd_repo_pending_request_total{repo="https://charts.jetstack.io"} 0
argocd_repo_pending_request_total{repo="https://charts.longhorn.io"} 0
argocd_repo_pending_request_total{repo="https://github.com/gigi206/k8s"} 0
argocd_repo_pending_request_total{repo="https://github.com/kubernetes-csi/external-snapshotter/"} 0
argocd_repo_pending_request_total{repo="https://helm.linkerd.io/stable"} 0
argocd_repo_pending_request_total{repo="https://k8s-at-home.com/charts/"} 0
argocd_repo_pending_request_total{repo="https://kubernetes.github.io/ingress-nginx"} 0
argocd_repo_pending_request_total{repo="https://metallb.github.io/metallb"} 0
argocd_repo_pending_request_total{repo="https://prometheus-community.github.io/helm-charts"} 0
go_gc_duration_seconds{quantile="0"} 1.4245e-05
go_gc_duration_seconds{quantile="0.25"} 3.4778e-05
go_gc_duration_seconds{quantile="0.5"} 4.7542e-05
go_gc_duration_seconds{quantile="0.75"} 0.000107607
go_gc_duration_seconds{quantile="1"} 0.002189787
go_gc_duration_seconds_sum 0.009690315
go_gc_duration_seconds_count 54
go_goroutines 22
go_info{version="go1.18.4"} 1
go_memstats_alloc_bytes 2.6231392e+07
go_memstats_alloc_bytes_total 6.76162112e+08
go_memstats_buck_hash_sys_bytes 1.683056e+06
go_memstats_frees_total 2.823334e+06
go_memstats_gc_cpu_fraction 2.5703741872420532e-05
go_memstats_gc_sys_bytes 6.329024e+06
go_memstats_heap_alloc_bytes 2.6231392e+07
go_memstats_heap_idle_bytes 2.9827072e+07
go_memstats_heap_inuse_bytes 3.141632e+07
go_memstats_heap_objects 42399
go_memstats_heap_released_bytes 1.6105472e+07
go_memstats_heap_sys_bytes 6.1243392e+07
go_memstats_last_gc_time_seconds 1.6601688663514209e+09
go_memstats_lookups_total 0
go_memstats_mallocs_total 2.865733e+06
go_memstats_mcache_inuse_bytes 19200
go_memstats_mcache_sys_bytes 31200
go_memstats_mspan_inuse_bytes 302872
go_memstats_mspan_sys_bytes 571200
go_memstats_next_gc_bytes 4.1510928e+07
go_memstats_other_sys_bytes 3.658168e+06
go_memstats_stack_inuse_bytes 1.671168e+06
go_memstats_stack_sys_bytes 1.671168e+06
go_memstats_sys_bytes 7.5187208e+07
go_threads 25
process_cpu_seconds_total 2.2
process_max_fds 1.048576e+06
process_open_fds 28
process_resident_memory_bytes 1.07933696e+08
process_start_time_seconds 1.6601677929e+09
process_virtual_memory_bytes 8.23635968e+08
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

argo-cd-argocd-server-metrics
```
argocd_redis_request_duration_bucket{initiator="argocd-server",le="0.1"} 4
argocd_redis_request_duration_bucket{initiator="argocd-server",le="0.25"} 4
argocd_redis_request_duration_bucket{initiator="argocd-server",le="0.5"} 4
argocd_redis_request_duration_bucket{initiator="argocd-server",le="1"} 4
argocd_redis_request_duration_bucket{initiator="argocd-server",le="2"} 4
argocd_redis_request_duration_bucket{initiator="argocd-server",le="+Inf"} 4
argocd_redis_request_duration_sum{initiator="argocd-server"} 0.001503193
argocd_redis_request_duration_count{initiator="argocd-server"} 4
argocd_redis_request_total{failed="false",initiator="argocd-server"} 4
go_gc_duration_seconds{quantile="0"} 2.83e-05
go_gc_duration_seconds{quantile="0.25"} 3.8442e-05
go_gc_duration_seconds{quantile="0.5"} 6.1264e-05
go_gc_duration_seconds{quantile="0.75"} 0.000206853
go_gc_duration_seconds{quantile="1"} 0.005100177
go_gc_duration_seconds_sum 0.007395652
go_gc_duration_seconds_count 15
go_goroutines 82
go_info{version="go1.18.4"} 1
go_memstats_alloc_bytes 1.4427776e+07
go_memstats_alloc_bytes_total 9.7354816e+07
go_memstats_buck_hash_sys_bytes 1.519888e+06
go_memstats_frees_total 702608
go_memstats_gc_cpu_fraction 1.2257566121665835e-05
go_memstats_gc_sys_bytes 6.058448e+06
go_memstats_heap_alloc_bytes 1.4427776e+07
go_memstats_heap_idle_bytes 1.2304384e+07
go_memstats_heap_inuse_bytes 1.9709952e+07
go_memstats_heap_objects 80887
go_memstats_heap_released_bytes 6.782976e+06
go_memstats_heap_sys_bytes 3.2014336e+07
go_memstats_last_gc_time_seconds 1.660168937897543e+09
go_memstats_lookups_total 0
go_memstats_mallocs_total 783495
go_memstats_mcache_inuse_bytes 19200
go_memstats_mcache_sys_bytes 31200
go_memstats_mspan_inuse_bytes 350064
go_memstats_mspan_sys_bytes 375360
go_memstats_next_gc_bytes 2.9800224e+07
go_memstats_other_sys_bytes 2.84596e+06
go_memstats_stack_inuse_bytes 1.540096e+06
go_memstats_stack_sys_bytes 1.540096e+06
go_memstats_sys_bytes 4.4385288e+07
go_threads 21
grpc_server_handled_total{grpc_code="Aborted",grpc_method="CanI",grpc_service="account.AccountService",grpc_type="unary"} 0
...
...
...
process_cpu_seconds_total 2.23
process_max_fds 1.048576e+06
process_open_fds 16
process_resident_memory_bytes 8.8256512e+07
process_start_time_seconds 1.66016779121e+09
process_virtual_memory_bytes 8.22194176e+08
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

**Comment by todaywasawesome** [comment]
@gigi206 I was unable to replicate this issue. In general, to debug this dashboard here's what I did.

### Quick guide for debugging Argo CD dashboard with Prometheus and Grafana

1) Make sure to deploy the Argo CD `ServiceMonitor`s listed in the [documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#prometheus-operator).
2) Verify that the `ServiceMonitor`s are configured with a release label that [matches prometheus](https://managedkube.com/prometheus/operator/servicemonitor/troubleshooting/2019/11/07/prometheus-operator-servicemonitor-troubleshooting.html).
3) Verify the serviceMonitor's are showing up with active targets in Prometheus. You should have (this is for Argo CD HA, you may not have as many targets):
    - serviceMonitor/prometheus-operator/argocd-metrics/0 (1 / 1 active targets)
    - serviceMonitor/prometheus-operator/argocd-notifications-controller-metrics/0 (1 / 1 active targets)
    - serviceMonitor/prometheus-operator/argocd-repo-server-metrics/0 (2 / 2 active targets)
    - serviceMonitor/prometheus-operator/argocd-server-metrics/0 (2 / 2 active targets)
4) If you're still missing some, double check the `ServiceMonitor`s to verify they are pointing at the resources with the right names.
    - Argocd-metrics are provided by default with a matchLabel `app.kubernetes.io/name: argocd-metrics` does a service with this name exist? If you installed with helm, perhaps these names were modified slightly?
    - Check the other `ServiceMonitor` targets to make sure they exist and the ports specified. 
5) In Prometheus, start a query and you should see lots of argocd options.
![Screen Shot 2022-10-17 at 9 12 49 AM](https://user-images.githubusercontent.com/3849900/196215587-6b171a1e-cebc-42bc-836f-ed76b63f4775.png)

At this point, if all of these things are working, your dashboard should work aswell. Probably the most important service monitor is this one:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  endpoints:
  - port: metrics
```
