### ISSUE TITLE
Argocd does not honour sync waves in partial syncs

### ISSUE THREAD

**Issue by oscrx** [argoproj/argo-cd#10303]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When a namespace with resources managed by Argocd is manually deleted Argocd does not honour sync waves or the default helm generated.

**To Reproduce**

Create a simple helm chart with a namespace in it, place at least 1 object in the namespace.
When you delete the namespace manually or with a script to clean it up (with the automatic kubernetes garbage collect)
I expect argocd to re-sync the state back to what is expected in git.

The `helm template` command places namespaces at the top of the generated manifest and this works well.
If the sync gets triggered after a deletion it will get the issue.
If I wait for argocd to fail 5 times (or terminate the sync) and sync manually it also works.

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-sync-issue
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-limits
  namespace: argocd-sync-issue
spec:
  hard:
    pods: "50"
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "15"
    limits.memory: 15Gi
```

**Expected behavior**

Argocd should honour the helm order in the generated manifest
OR
Argocd should honour the sync waves
OR
Argocd should check namespaces first during syncing.

**Screenshots**

<img width="382" alt="afbeelding" src="https://user-images.githubusercontent.com/6731096/184382597-aba15748-9d27-4c2b-9554-3522a3ebb1e9.png">
<img width="998" alt="afbeelding" src="https://user-images.githubusercontent.com/6731096/184382689-f6dab4cd-67b4-45c0-951d-e81994023550.png">

**Version**

```shell
$ argocd version
argocd: v2.2.5+8f981cc
  BuildDate: 2022-02-05T01:33:25Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T11:41:37Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.10
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by oscrx** [comment]
I'm closing this issue as it is not a bug.

The feature/fix that is necessary to make this work is located here: #12904

For now I worked around the issue by splitting up my helm chart in 2 parts. 1 to dynamically generate namespace names (1 for each of our devs) and 1 to provision those namespaces with image pull secrets, limit ranges etc.

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: XXX
            taste: rbac
            url: https://cluster.url:6443
          - cluster: XXX
            taste: ns
            url: https://cluster.url:6443
            ...
  template:
    metadata:
      name: "cluster-config-{{cluster}}-{{taste}}"
    spec:
      project: "infra-{{cluster}}"
      source:
        path: argocd-managed/infra/cluster-config
        repoURL: https://git.url/infra.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - "values.yaml"
            - "values-{{cluster}}.yaml"
            - "values-{{taste}}.yaml"
      destination:
        server: "{{url}}"
        namespace: XXXX
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          backoff:
            duration: 1m0s
            factor: 2
            maxDuration: 3m0s
          limit: 100
```
