### ISSUE TITLE
revisionHistoryLimit Not Enforced

### ISSUE THREAD

**Issue by reefland** [argoproj/argo-cd#10300]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have `revisionHistoryLimit` set to 3 for all my applications but many RS expand to the default 10.

**Expected behavior**

I expect this to be set to 3 and applied to controllers within the application.

**Screenshots**

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    
spec:
  revisionHistoryLimit: 3
```

![image](https://user-images.githubusercontent.com/16230914/184356193-8addcc2d-ac2d-4871-8d39-c915f6954229.png)

![image](https://user-images.githubusercontent.com/16230914/184356350-e750929c-502d-406d-a6ac-24f81827bbc8.png)

Seems the `revisionHistoryLimit` did not get applied to controllers when it was set:

```
$ k get deployment -n argocd argocd-notifications-controller -o jsonpath='{.spec.revisionHistoryLimit}'     
10
```

**Version**

```shell
Argo CD - v2.4.9+1ba9008
```
