### ISSUE TITLE
ignoreDifferences on image effects imagePullPolicy default value

### ISSUE THREAD

**Issue by fe-ax** [argoproj/argo-cd#10308]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When using `ignoreDifferences` on the `image` field it effects the field `imagePullPolicy`. The field `imagePullPolicy` changes its default value from `Always` to `ifNotPresent`, although `image` is set to `nginx:latest`. ([link](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy))

This is not applied when sync is initiated, but the state of the application stays out of sync.

**To Reproduce**

1. Deploy application (see screenshots) with `nginx:latest` and no `imagePullPolicy` (defaults to Always for :latest)
2. Add `ignoreDifferences` to field `image` (Because an external source updates image tag to specific tag)
3. Sync application

**Expected behavior**

The field `image` should not be ignored before normalizing the object, but after.

**Screenshots**

```yaml
project: default
source:
  repoURL: 'https://github.com/fe-ax/argotest'
  path: ./
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
      - '. | .spec.template.spec.containers[].image'
```

```shell
marco@xxx:~/argo-cd$ argocd app diff my-app
===== apps/Deployment my-ns/my-app ======
183c183
<         imagePullPolicy: Always
---
>         imagePullPolicy: IfNotPresent
```

**Version**

```shell
argocd: v2.4.9+1ba9008
  BuildDate: 2022-08-11T15:43:48Z
  GitCommit: 1ba9008536b7e61414784811c431cd8da356065e
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.9+1ba9008
  BuildDate: 2022-08-11T15:22:41Z
  GitCommit: 1ba9008536b7e61414784811c431cd8da356065e
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
No relevant logs
```
