### ISSUE TITLE
Persist resource health in Redis instead of the Application CR by default

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10312]
# Summary

[As of 2.5](https://github.com/argoproj/argo-cd/pull/10191), we'll have the option to persist resource health statuses in Redis instead of in the Application CRD. In 3.0, we should default to persisting in Redis.

# Motivation

> ```yaml
>   # Specifies if resource health should be persisted in app CRD (default true)
>   # Changing this to `false` significantly reduce number of Application CRD updates and improves controller performance.
>   # However, disabling resource health by default might affect applications that communicate with Applications CRD directly
>   # so we have to defer switching this to `false` by default till v3.0 release.
>   controller.resource.health.persist: "true"
> ```

# Proposal

Flip the switch.  Maybe even remove support for CRD persistence entirely.

**Comment by csantanapr** [comment]
Minor clarification is `Application CR` not `Application CRD` 
I agree with the statement
>Flip the switch. Maybe even remove support for ArgoCD CR persistence entirely.

Saving the status in the CR/etcd has a performance impact, end user like Adobe had to switch the default to redis to improve  scalability in their recent talk at GitOpsCon NA 2024 https://youtu.be/MDXrc_cLVns?t=404
![image](https://github.com/argoproj/argo-cd/assets/1094878/9f2e25be-3e22-458e-9c7e-499ef717739f)

**Comment by rumstead** [comment]
Will this break the applicationset controller's progressive sync functionality?

**Comment by crenshaw-dev** [comment]
@rumstead good question. I think the answer is "yes." One option would be to add an option that only persists top-level health changes to the status instead of changes for individual resources. Another option would be to modify the AppSet controller to pull the current health status from Redis.

**Comment by rumstead** [comment]
took me forever to find when the resource health cache was created - https://github.com/argoproj/argo-cd/pull/1120

**Comment by MrFreezeex** [comment]
I am not entirely sure this would work out with notification/notification controllers too. AFAIU the notification controller rely on the CRD to be updated to be able to send notification in "real" time about sync event :thinking:. Sorry if that's already taken care of, just wondering how this could actually works :sweat_smile:.

**Comment by rumstead** [comment]
> I am not entirely sure this would work out with notification/notification controllers too. AFAIU the notification controller rely on the Application CR to be updated to be able to send notification in "real" time about sync event 🤔. Sorry if that's already taken care of, just wondering how this could actually works 😅.

That is a good shout but I don't believe the notification controller looks at the health status of the individual resources, just the overall application health / sync status. 

E.g., the diff in the status would look something like this:

persis = true (the default)
```yaml
status:
  health:
    status: Healthy
  resources:
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: demo-app-kust
    namespace: cluster-generator
    status: OutOfSync
    version: v1
  sync:
    status: OutOfSync
```
persist = false
```yaml
# snippet CR status
status:
  health:
    status: Healthy
  resourceHealthSource: appTree
  resources:
  - group: apps
    kind: Deployment
    name: demo-app-kust
    namespace: cluster-generator
    status: OutOfSync
    version: v1
  sync:
    status: OutOfSync
```

Where persist = false is missing `status.resources[].health`
