### ISSUE TITLE
Can not use helm chart dependency "@xxx". got "Please add them via 'helm repo add'"

### ISSUE THREAD

**Issue by lazychanger** [argoproj/argo-cd#10320]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
```yaml
# repo setting
configs.repositories:
  private-helm-chart:
    url: "http://chartmuseum.core.svc.cluster.local:8080"
    name: chartmuseum
    type: helm
    username: <username>
    password: <password>
```
```yaml
# Chart dependencies
dependencies:
  - name: <chartname>
    version: "~1.0"
    repository: "@chartmuseum"
```

**Screenshots**
<img width="378" alt="image" src="https://user-images.githubusercontent.com/20916944/184478557-66ff96d5-90c1-4381-a0af-4742966fc525.png">

**Version**

```json
{"Version":"v2.4.9+1ba9008","BuildDate":"2022-08-11T15:22:41Z","GitCommit":"1ba9008536b7e61414784811c431cd8da356065e","GitTreeState":"clean","GoVersion":"go1.18.5","Compiler":"gc","Platform":"linux/amd64","KustomizeVersion":"v4.4.1 2021-11-11T23:36:27Z","HelmVersion":"v3.8.1+g5cb9af4","KubectlVersion":"v0.23.1","JsonnetVersion":"v0.18.0"}
```

**Logs**

```
Paste any relevant application logs here.
```
