### ISSUE TITLE
ArgoCD Application Controller sets Health from Progressing to Missing which deletes app content

### ISSUE THREAD

**Issue by ericdurandsymphony** [argoproj/argo-cd#10350]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

When running on a cluster that has lots of Secrets (we had 346k Secrets when this occurred), we saw that ArgoCD switched the health status of the applications from Progressing to Missing, then began to delete their objects.
We were in that state of so many secrets because the GKE control plane began to create service account token secrets like crazy. We suspect that in that state the Secrets api was not responding.
This lead to the deletion of the ArgoCD application that controlled ArgoCD itself which lead to loss of the ArgoCD namespace, Apps etc.

k8s version: v1.22.10-gke.600

The application that hosts ArgoCD app, and its namespace is created by the following manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: apps-project
  source:
    directory:
      recurse: true
    path: $folderName
    repoURL: $repoURL
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 7 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 15m # the maximum amount of time allowed for the backoff strategy
```

**To Reproduce**

Create tons of Secrets to trigger a crash of the Secrets controller?

**Expected behavior**

ArgoCD Application Controller Should not switch from Progressing to Missing and delete the contents of the App.

**Screenshots**

**Version**

```shell
argocd version                                                                                                                                                                        [15:15:11]
argocd: v2.1.3+d855831.dirty
  BuildDate: 2021-09-30T22:11:24Z
  GitCommit: d855831540e51d8a90b1006d2eb9f49ab1b088af
  GitTreeState: dirty
  GoVersion: go1.17.1
  Compiler: gc
  Platform: darwin/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.3.1+b65c169
  BuildDate: 2022-03-10T22:51:09Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**
I only have audit logs available
```
2022-08-05 23:10:53.000 CEST 
sand-euw1-001
Updated health status: Progressing -> Missing

2022-08-05 23:10:57.627 CEST
sand-euw1-001
k8s.io
io.k8s.core.v1.namespaces.delete
core/v1/namespaces/argocd
system:serviceaccount:arg…
audit_log, method: "io.k8s.core.v1.namespaces.delete", principal_email: "system:serviceaccount:argocd:appctl"
```
