### ISSUE TITLE
ComparisonError strconv.ParseBool: parsing “\xb6\xbb\x9e”: invalid syntax

### ISSUE THREAD

**Issue by mikebryant** [argoproj/argo-cd#10373]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

A bad Secret object was mistakenly deployed to our cluster using SealedSecrets:

```
apiVersion: v1
data:
  enableOCI: "true"
  ...other bits
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  namespace: argocd
  name: foobar
type: Opaque
```

This was supposed to be the string `true` base64-encoded, but ended up being the literal string, which base64 decodes to 3 weird bytes.

Argo CD then went to status Unknown on all repositories, as it couldn't compare anything. The error message was only `ComparisonError strconv.ParseBool: parsing “\xb6\xbb\x9e”: invalid syntax`, which left us very confused

**To Reproduce**

Deploy the above secret to a cluster and all apps will break

**Expected behavior**

The error message should indicate which Secret was broken - the provided context left us scratching our heads for a while as we tried to figure out what had happened. (This secret was deployed by a different team)

**Screenshots**

**Version**

```shell
v2.4.2
```

**Logs**

```
Paste any relevant application logs here.
```
