### ISSUE TITLE
cipher: message authentication failed when logging in with okta since v2.4.9

### ISSUE THREAD

**Issue by martijnvdp** [argoproj/argo-cd#10382]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
Since upgrading to argo cd 
`v2.4.9+1ba9008` from `v2.3.4+ac8b7df` users sometime get the error when trying to access argocd using okta:
`cipher: message authentication failed`

workaround is to relogon in okta and retry to go to argo

**To Reproduce**
not sure yet, seems often to occur after an restart of argocd
**Expected behavior**
if the login session did expire i would expect to be redirected back to okta

**Screenshots**

**Version**

```shell

v2.4.9+1ba9008
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by martijnvdp** [comment]
update havent gotten this error for a few days now, i'm also unable to reproduce it

**Comment by martijnvdp** [comment]
upgraded 2 other deployments and now i've seen the error again a few times , refreshing cache seems to resolve it as wel

**Comment by martijnvdp** [comment]
restarting the argocd server deployment seems to resolve it

**Comment by ebuildy** [comment]
got it as well with v2.8.

I restart argocd server every week .......

**Comment by dmajano** [comment]
I'm in the same issue with v2.14.8.

I have configured it with SSO for keycloak with helm chart:

```
argo-cd:

  configs:
    cm:
      admin.enabled: false
      oidc.config: |
        name: sso
        issuer: XXXXXX
        clientID: $oidc.keycloak.clientID
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email"]
    params:
      server.insecure: true
    secret:
      createSecret: false
```

I don't want any initial user created. So admin user and secret  creation are disabled.

Every week I receive two types of errors:

```
cipher: message authentication failed
```

or
 
```
serverKey is missing
```

The only solutions I have found is restart argoCD. But when you start doing it weekly it is not the most optimal.

I understand the own argoCD has to be able to update those and keep the secret updated.
