### ISSUE TITLE
applicationset-controller logging not respecting `logformat` and `loglevel` flags

### ISSUE THREAD

**Issue by Laffs2k5** [argoproj/argo-cd#10399]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm not able to have applicationset-controller respect the `--logformat` and `--loglevel` flags. Logging format seems to be `text` even though I specify `json` and logging level is `info` even though I specify `warn`.

**To Reproduce**

1. Start the applicationset-controller with the flags `--logformat=json --loglevel=warn`.
2. Observe that log output is in text format and includes info level log.

**Expected behavior**

I would expect application-set controller to log in json format and only log warn level and higher as the other ArgoCD applications do.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.4.10+2ccc17a
  BuildDate: 2022-08-17T21:03:50Z
  GitCommit: 2ccc17afcbad78651cf7cd76891cdf7728cd488e
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Example output from the pod above:
```text
time="2022-08-19T08:06:48Z" level=info msg=Trace args="[git fetch origin HEAD --tags --force]" dir=/tmp/https___github.com_*** operation_name="exec git" time_ms=906.7991010000001
time="2022-08-19T08:06:49Z" level=info msg=Trace args="[git checkout --force 4824fb31972bb94fdfc72d4185131fb4f371ad1a]" dir=/tmp/https___github.com_*** operation_name="exec git" time_ms=3.373673
time="2022-08-19T08:06:49Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_*** operation_name="exec git" time_ms=3.036766
```
Note: my private github repo name was replaced with `***` in the output.

**More details**
I'm deploying applicationset-controller in Kubernetes using version `4.10.7` of the `argo-cd` helm chart from https://argoproj.github.io/argo-helm.

I have verified that the flags are picked up and evaluated in two ways:
1. Deployed with `--logFormat=json` (notice the uppercase F) and the app would not boot
3. Deployed with an invalid value for `--loglevel` and the app would not boot

Part of the resulting container spec (from `kubectl describe pod` after deploy) showing the flags:
```yaml
spec:
  containers:
    - command:
        - entrypoint.sh
        - argocd-applicationset-controller
        - --metrics-addr=:8080
        - --probe-addr=:8081
        - --namespace=argocd
        - --argocd-repo-server=argocd-repo-server:8081
        - --policy=sync
        - --debug=false
        - --dry-run=false
        - --logformat=json
        - --loglevel=warn
      image: quay.io/argoproj/argocd:v2.4.10
```
