### ISSUE TITLE
Multiple "allow" sync windows can prevent an app from syncing

### ISSUE THREAD

**Issue by jeffreyc** [argoproj/argo-cd#10425]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The [sync window documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/) states "If there are any `allow` windows matching an application then syncs will only be allowed when there is an active `allow` windows." However, the implementation appears to be that if there are multiple allow windows (e.g., allowing deploys from 9-5 on M-Th but only from 9-2 on F), then deploys will not be allowed if there are _any_ inactive windows.

When this happens, the logs will show "Sync prevented by sync window" via [`appcontroller.go`](https://github.com/argoproj/argo-cd/blob/master/controller/appcontroller.go#L1408). Looking at [`CanSync`](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L1884), it appears to be returning `false` via the `if inactiveAllows.HasWindows()` check. Looking at [`InactiveAllows`](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L1748), I do not believe this is the correct choice of function for `CanSync` to use. Per the comment, "If the current time is in an inactive allow window, syncs will be denied", the code iterates over all windows, returning any inactive windows. This does not make sense for an allow list, and will cause the presence of an inactive allow window to prevent syncing even if there is also an active allow window.

I suspect the fix is something to the effect of updating `CanSync` to compare the length of `active` to `inactiveAllows` and return `true` if they are different (i.e., there are more allow windows than there are inactive allow windows, or there is at least one active allow window). Or create an `ActiveAllows` by copying `InactiveAllows` and call that between the `hasActiveDeny` and `inactiveAllows` checks.

**To Reproduce**

Adding the following to your `AppProject` should prevent syncs:

```
  syncWindows:
    - kind: allow
      schedule: '0 0 * * *'
      duration: 12h
    syncWindows:
    - kind: allow
      schedule: '0 12 * * *'
      duration: 12h
```

**Expected behavior**

With the above manifest, apps should sync 24/7. Instead, they will refuse to sync, displaying "Sync prevented by sync window".

**Screenshots**

NA

**Version**

I've encountered this running v2.3.5+1287d24, but the underlying issue is present in master through 506bd3b2827c4502d1f468a0c52e04a86ea6b83e.

**Logs**

NA

**Comment by franznemeth** [comment]
We are facing a similar issue when I tried to add a one-time daily sync window to a project in which syncs may only happen sunday night.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: removed
  namespace: argocd
spec:
  ...
  syncWindows:
  - kind: allow
    schedule: '0 1 * * 6'
    duration: 1h
    applications:
    - '*-prod'
    manualSync: true
  - kind: allow
    schedule: '0 1 * * *'
    duration: 1h
    applications:
    - '*-prod'
    manualSync: true
```
Altough the second sync-window would allow the sync it is blocked by the first one.
