### ISSUE TITLE
Server side apply cannot sync to desired state

### ISSUE THREAD

**Issue by yeya24** [argoproj/argo-cd#10438]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After syncing the app with the server-side apply option, I got the following error indicating an out-of-sync error.

![image](https://user-images.githubusercontent.com/25150124/186265141-37db5dee-f9e6-47cd-b093-db789eccb5e7.png)

The content after sync seems identical but diff gives me the error and I am not able to sync it to the expected state.

**To Reproduce**

Initial manifest in base.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
```

Then at git repo, patch the service with customize overlay.
```yaml
resources:
- ../../base
patchesStrategicMerge:
- service.yaml
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: rtmpk
    port: 1986
    protocol: UDP
    targetPort: 1986
  - name: rtmp
    port: 1935
    protocol: TCP
    targetPort: 1935
  - name: rtmpq
    port: 1935
    protocol: UDP
    targetPort: 1935
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http3
    port: 443
    protocol: UDP
    targetPort: 443
```

application.yaml, server side apply option is not enabled at app level.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-bge-dev2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-demo
    name:  bge-dev2
  project: demo
  source:
    path: deploy/overlays/bge-dev2
    repoURL: repoURL
    targetRevision: ssa
  syncPolicy:
    automated:
      prune: true
```

Then go to ArgoCD UI and the diff shows the following. This is actually wrong because it is not considering server side apply when diffing.

![image](https://user-images.githubusercontent.com/25150124/186269463-f2341d56-2e49-4799-8a2f-36ef899dd650.png)

Then sync the application with the option `server-side apply` enabled, and finally got into the `Out of Sync` state.

![image](https://user-images.githubusercontent.com/25150124/186266666-61d1fe4d-ee23-4b5e-9715-8ac387ae2727.png)

**Expected behavior**

Sync should sync the state to `Synced` rather than `Out Of Sync`.

**Screenshots**

**Version**

latest master

**Logs**

```
Paste any relevant application logs here.
```
