### ISSUE TITLE
ApplicationSet: allow declaration of variables to be used everywhere in the CRD content

### ISSUE THREAD

**Issue by bmedici** [argoproj/argo-cd#10443]
# Summary
When using generators in a ApplicationSet, we can use the variables like `{{path}}` or `{{path[1]}}` containing parts of the path. Most of the time, directory parts have a special usage/meaning in the way we organise the file structure. to improve readability and abstraction, we could alias or name those parts explicitely.

# Motivation
When path[1] represents the app name, for example, I'd like to declare appname={{path[1]}} to be able to use {{appname}} in the declaration and only change the index for example, when the path structure evolves.

# Proposal
Such aliases could be supported at the generator level, for example:
```
spec:
   generators:

    - git:
        repoURL: https://gitlab.com/.../applications.git
        revision: develop
        files:
        - path: services/*/*.yaml
       aliases:
      - path0: contextname
      - path1: appname
      - filename: configfile 
```
