### ISSUE TITLE
prune option doesn't play nice with CiliumIdentity resource

### ISSUE THREAD

**Issue by michalschott** [argoproj/argo-cd#10456]
Hey,

I'm running on EKS with Cilium as CNI, deploying apps with kustomize with prune option enabled.

Given my kustomization looks like this:

```
kustomization.yaml:

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets-store-csi-driver
resources:
- aws-provider-installer.yaml
- namespace.yaml
- secrets-store-csi-driver.yaml

namespace.yaml:

apiVersion: v1
kind: Namespace
metadata:
  name: secrets-store-csi-driver
  labels:
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    downscaler/exclude: "true"
```

Cilium automatically creates CiliumIdentity object, which ArgoCD obviously catch up and here is where story begins:
* app (especially CiliumIdentity) is constantly marked as Out-Of-Sync
![Zrzut ekranu 2022-08-25 o 17 32 10](https://user-images.githubusercontent.com/6672421/186707809-1bbcd68c-9af4-4be1-987d-54f448fb87ae.png)
* resource is being constantly removed by Argo
* Cilium recreates the object

How can I prevent this behaviour without turning off prune option?

**Comment by ashutosh16** [comment]
@michalschott   You can add an annotation to the specific object `CiliumIdentity`, preventing it from pruning. Is this option work for you?
```
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
```
https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-prune-resources

**Comment by michalschott** [comment]
@ashutosh16 not really, as these objects are not included in kustomization and are created by cilium itself

**Comment by michalschott** [comment]
@debu99 

Apparently this fixed the issue for me:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
```

Should be included as a default IMHO.

**Comment by sathieu** [comment]
Yes. This is documented here: https://docs.cilium.io/en/stable/configuration/argocd-issues/#argo-cd-deletes-customresourcedefinitions

Still, I don't understand why ArgoCD catches those resources. Maybe they copy the labels and annotations from the pods. Could this be a bug in how ArgoCD prunes?

**Comment by lebenitza** [comment]
> Still, I don't understand why ArgoCD catches those resources. Maybe they copy the labels and annotations from the pods. Could this be a bug in how ArgoCD prunes?

```yaml
apiVersion: cilium.io/v2
kind: CiliumIdentity
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.11.0
    helm.sh/chart: cert-manager-v1.11.0
    io.cilium.k8s.policy.cluster: default
    io.cilium.k8s.policy.serviceaccount: cert-manager-webhook
    io.kubernetes.pod.namespace: ingress-system
```

I think you are right, don't think it is a bug in ArgoCD. They need to be exluded.
