### ISSUE TITLE
resourceTrackingMethod: annotation or annotation+label looses Health Status of custom resources 

### ISSUE THREAD

**Issue by dan1el-k** [argoproj/argo-cd#10463]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When enabling the new resourceTrackingMethod functionality, the status of custom resource become "Unknown". 
When just using resourceTrackingMethod: label (old behaviour), those custom resources were tracked with status "Healthy".
This is valid for all custom resources which are not part of the [resource_customizations](https://github.com/argoproj/argo-cd/tree/master/resource_customizations).

### Example: Openshift RBAC Group object

**resourceTrackingMethod: annotation+label**

![image](https://user-images.githubusercontent.com/34611072/186902853-896b4641-106f-478c-93b4-de4787005814.png)

**resourceTrackingMethod: label** 

![image](https://user-images.githubusercontent.com/34611072/186904095-229c22b2-41c1-4357-a904-1b64f1af8328.png)

This leads to further problems, as those objects are not properly tracked anymore, and thing like `auto-sync` or `self-heal` doesn't work anymore.

**To Reproduce**

1. enable resourceTrackingMethod to use (also) annotation in the Operator CR

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  finalizers:
    - argoproj.io/finalizer
  labels:
    app.kubernetes.io/instance: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  resourceTrackingMethod: annotation
  #or
  resourceTrackingMethod: annotation+label
```

2. Sync and Restart Argocd

3. In the ArgoCD UI, go to an application which includes custom resources. Click Refresh and Sync
4. Watch that custom resources went from Status "Healthy" to "Unknown"

**Expected behavior**

All resources, which are deployed by Argo, should have a correct "Status" and are tracked by Argo.
This is a standard functionality and should behave like in the past, even when enabling the new resourceTrackingMethod

**Screenshots**

**Version**

```shell
ArgoCD: 2.4.8
ArgoCD Operator: 0.4
```

**Logs**

```
Paste any relevant application logs here.
```
