### ISSUE TITLE
Labels on VPA are missing after synced

### ISSUE THREAD

**Issue by shaoxt** [argoproj/argo-cd#10489]
```
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: "this_label_will_be_missing"
  name: test-vpa
spec:
  targetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name:  test-rollout
  resourcePolicy:
    containerPolicies:
      - containerName: 'app'
        minAllowed:
          cpu: 500m
          memory: 1Gi
        maxAllowed:
          cpu: 2
          memory: 2Gi
        controlledResources: ["cpu", "memory"]
```

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
