### ISSUE TITLE
Cannot resolve git repo domain without privileges

### ISSUE THREAD

**Issue by bauerjs1** [argoproj/argo-cd#10490]
Hi there,

First of all thank you very much for this awesome piece of software! After upgrading the helm chart and thus the version of Argo CD to 2.4 we encountered an issue with the git clients in repo-server and application-controller. By default, workloads in our clusters are assigned a restricted PodSecurityPolicy that drops all the capabilities from the containers. If we run these two pods with this PSP (see below), the git client cannot resolve the repository domain. Assigning the pods a "privileged" PSP that allows everything, the problem disappears, so I suspect it has something to do with capabilities. I could not find any capability requirements documented, nor do I think they should be necessary.

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Argo CD v2.4 repo-server and applicationset-controller cannot resolve the domain of our source repository when `ALL` capabilities are dropped. Access to git fails with error `unable to access 'https://git.example.com/k8s/argocd.git/': getaddrinfo() thread failed to start`.

**To Reproduce**

Node OS: Ubuntu focal (if that makes a difference)

Run argocd repo-server (and/or applicationset-controller, if used) with this PodSecurityPolicy:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-restricted
spec:
  requiredDropCapabilities:
    - ALL
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  allowPrivilegeEscalation: false
```

**Expected behavior**

The git client in the `quay.io/argoproj/argocd:v2.4` containers should be able to resolve DNS without further privileges.

**Version**

Tested with `v2.4.0` to `v2.4.11`

**Logs**

```
time="2022-08-26T18:47:33Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: fatal: unable to access 'https://git.example.com/k8s/argocd.git/': getaddrinfo() thread failed to start" execID=7f886
time="2022-08-26T18:47:33Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/_argocd-repo/0472c56c-6a3c-4114-a9d3-d2ccb7a817eb operation_name="exec git" time_ms=9.626145
```
