### ISSUE TITLE
Web Shell - Unable to type commands into Alpine based pods

### ISSUE THREAD

**Issue by mtovmassian** [argoproj/argo-cd#10503]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

From the UI when I connect to an Alpine based pod the terminal window opens and the cursor is blinking on the first line.
But when I type any key nothing is printed.
Even if I blindly type a command and hit \<ENTER\> no output is displayed.

Tested with:
- redis:4-alpine
- python:3.9-alpine
- alpine:3.16.2

**To Reproduce**
1. Add this pod as an ArgoCD app:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: alpine-debug
  name: alpine-debug
  namespace: default
spec:
  containers:
  - image: alpine:3.16.2
    imagePullPolicy: Always
    name: alpine-debug-cntr
    command:
      - /bin/sh
      - -c
      - tail -f /dev/null
    resources:
      limits:
        cpu: "1"
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
```
2. Connect to the pod via Web Shell
3. Type anything in the terminal window

**Expected behavior**
Type command line with visual feedback, execute it and see output.

**Version**

```shell
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-11T00:01:03Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.4+fe80bdc
  BuildDate: 2022-07-07T07:11:00Z
  GitCommit: fe80bdcfdc847372f268f5d711d3112c7d1e39bf
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
time="2022-09-02T09:43:26Z" level=info msg="terminal session starting" application=alpine-debug cluster=*** container=alpine-debug-cntr namespace=default podName=alpine-debug userName=***
E0902 09:43:27.439997       1 v2.go:105] EOF
```
