### ISSUE TITLE
SSH agent requested but SSH_AUTH_SOCK not-specified\\\"\",\"type\":\"ComparisonError

### ISSUE THREAD

**Issue by tiwarisanjay** [argoproj/argo-cd#10511]
Checklist:

* [. ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ .] I've included steps to reproduce the bug.
* [ .] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to access a private repository in declarative way. For  which I have followed:
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials

After argocd installation, I have created a secret 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:tiwarisanjay
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    blabhlabl
    -----END OPENSSH PRIVATE KEY----- 
```
and trying to access it by creating application as 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sleep-pod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tiwarisanjay/pod-testing-yamls.git
    targetRevision: HEAD
    path: test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: testns
  syncPolicy:
    retry:
      limit: 2
    automated: 
        prune: true
        selfHeal: true 
        allowEmpty: false 
    syncOptions:
      - CreateNamespace=true
      - Replace=true  
```
Above setup is throwing off error as  

```
 time="2022-09-02T19:59:16Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-09-02T19:59:16Z\",\"message\":\"rpc error: code = Unknown desc = error creating SSH agent: \\\"SSH agent requested but SSH_AUTH_SOCK not-specified\\\"\",\"type\":\"ComparisonError\"}]}}" application=sleep-pod 
```

```
 time="2022-09-02T19:59:16Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-09-02T19:59:16Z\",\"message\":\"rpc error: code = Unknown desc = error creating SSH agent: \\\"SSH agent requested but SSH_AUTH_SOCK not-specified\\\"\",\"type\":\"ComparisonError\"}]}}" application=sleep-pod 
```
**To Reproduce**
- Install argocd cluster-install
- Create a secert with ssh key using above yaml
- Create a applicaiton yaml to access priavate repo

- Install argocd cluster-install
- Create a secert with ssh key using above yaml
- Create a applicaiton yaml to access priavate repo

**Expected behavior**

ArgoCD should be able to sync repo. 

ArgoCD should be able to sync repo. 

**Screenshots**
![image](https://user-images.githubusercontent.com/65133206/188229466-8b2e5ab3-afcd-4a73-afa5-ccfbfa0f2c3d.png)

**Version**

v2.4.11

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
 time="2022-09-02T19:59:16Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-09-02T19:59:16Z\",\"message\":\"rpc error: code = Unknown desc = error creating SSH agent: \\\"SSH agent requested but SSH_AUTH_SOCK not-specified\\\"\",\"type\":\"ComparisonError\"}]}}" application=sleep-pod 
```

```
Paste any relevant application logs here.
```
