### ISSUE TITLE
Allow merging Cluster Decision values key into Template params["values"] and "values.%s"

### ISSUE THREAD

**Issue by richardjennings** [argoproj/argo-cd#10536]
# Summary

The ClusterDecisionResource generator passes the 'name', 'server' and any other key/value in the duck-type resource's status list as parameters into the ApplicationSet template. For example an additional key clusterName.

Allow specifying a values key in the resources status list that is merged into the params["values"] or params["values.%s"] scopes.

# Motivation

For example when combining the Merge Generator with the Cluster Generator and ClusterDecisionResource  Generator, if values can be set as default in the Cluster Generator and can be overridden by the ClusterDecisionResource Generator, the common template variable name can be used. Currently ClusterDecisionResource values are added to params, not params["values"]. Adding a special behaviour to the CRD values parameter if a map[string]string enhances the flexibility and power of the ClusterDecisionResource Generator, for example merging with default config whilst allowing to overrides.
```
kind: MyDecisionKind
...
status:
  decisions:
    - clusterName: cluster
      values:
        targetRef: branch
...
```
```
kind: ApplicationSet
...
spec:
  generators:
    - merge:
      mergeKeys:
        - name
      generators:
        - clusters:
          values:
            targetRef: main
        - clusterDecisionResource:
          configMapRef: my-configmap
          name: my-decision-config
  template:
  ...
  spec:
    source: 
      targetRevision: '{{ values.targetRef }}'
  ...
```
With the proposal implemented, the above config allows for clusters to be optionally configured by the Decision Generator and specify via values map details like the source branch to deploy.

# Proposal

Tests to duck_type_test.go for both Go Template Enabled and default, e.g. duckTypeProdOnlyWithValues
Add code to duck_type.go line 212ish like:
```
if values, ok := cluster.(map[string]interface{})["values"]; ok {
    for key, value := range values.(map[string]interface{}) {
        if value, ok := value.(string); ok {
            appSetGenerator.ClusterDecisionResource.Values[key] = value
        } else {
            log.WithField(fmt.Sprintf("decision values %s", key), value).Warning("not a string")
        }
    }
    delete(cluster.(map[string]interface{}), "values")
}
```
If values is specified as a parameter in the CRD and it has strings as values, they are added to the appSetGenerator.ClusterDecisionResource.Values and then treated as if specified in ```clusterDecisionResource.values```.
