### ISSUE TITLE
HELM chart with dependency: no repository definition for https://charts.bitnami.com/bitnami

### ISSUE THREAD

**Issue by carslen** [argoproj/argo-cd#10541]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

When trying to deploy self hosted HELM charts (don't know if it's the correct term) with dependencies in it and using ArgoCD Vault Plugin, then application creation fails with error:

```
Unable to create application: 
application spec for backend-helm-test is invalid: 
InvalidSpecError: Unable to generate manifests in : rpc error: 
code = Unknown 
desc = `sh -c helm dependency build -n $ARGOCD_APP_NAMESPACE` failed exit status 1: 
Error: no repository definition for https://charts.bitnami.com/bitnami, https://helm.runix.net. 
Please add the missing repos via 'helm repo add'
````
When using the Git way to deploy these helm charts (details follow), then it works as expected.

**To Reproduce**

AVP plugin configuration:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |-
    - name: argocd-vault-plugin-helm-args
      init:
        command: [sh, -c]
        args: ["helm dependency build -n $ARGOCD_APP_NAMESPACE"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${helm_args} . | argocd-vault-plugin generate - -s vault-secret"]
```
ArgoCD Vault Plugin is implemented via initContainers.

ArgoCD Application (Helm):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-name1
spec:
  destination:
    name: ''
    namespace: namespace-helm
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://catenax-ng.github.io/product-portal-cd'
    targetRevision: 0.5.3
    chart: portal-backend
    plugin:
      name: argocd-vault-plugin-helm-args
      env:
        - name: helm_args
          value: '-f values.yaml -f values-int.yaml'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

After click on create in ArgoCD WebUI for app creation, the above error message is shown. If the HELM chart does not contain dependencies, it works as expected. 

**Expected behavior**

Our workaround to deploy the application is using the ArgoCD Git way, refering to git repository and the released helm chart specific GIT tag to match the released helm chart.

ArgoCD Application (GIT Way):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-name2
spec:
  destination:
    namespace: portal-test
    server: https://kubernetes.default.svc
  source:
    path: charts/portal-backend
    repoURL: https://github.com/catenax-ng/product-portal-cd
    targetRevision: portal-backend-0.5.3
    plugin:
      name: argocd-vault-plugin-helm-args
      env:
      - name: helm_args
        value: -f values.yaml -f values-int.yaml
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
```
After click on create in ArgoCD WebUI for app creation the application is created as expected. 

The expectation would be, that the plugin behave the same regardless how it's triggered.

**Version**

```shell
argocd: v2.4.11+3d9e9f2.dirty
  BuildDate: 2022-08-22T12:47:26Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: dirty
  GoVersion: go1.19
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T11:41:37Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```
