### ISSUE TITLE
multiple application sources defined: Helm,Ksonnet

### ISSUE THREAD

**Issue by bappr** [argoproj/argo-cd#1054]
Hey guys,

After upgrading to 0.11.0, I am getting the error `multiple application sources defined: Helm,Ksonnet` whenever I am trying to create a new app using my helm charts. No issue with 0.10.6.

**Comment by PaulVanStaden** [comment]
Hey 

How would I go and reproduce this error in my environment? I have not seen this error? I have also migrated from 0.10.6 to 0.11.0 without this happening.

**Comment by jessesuen** [comment]
In v0.11 we tightened the validation of the app spec to not allow two kinds of application sources defined at the same time. In v0.10, we were not strict. Basically you have both a ksonnet env defined, as well as helm values files list. e.g:

```
  source:
    ksonnet:
      env: prod
    helm:
      valueFiles:
      - values.yaml
      - values-prd.yaml
      - values-appf-prd.yaml
    path: .
    repoURL: https://github.com/myorg/myrepo.git
    targetRevision: HEAD
    # the following are legacy fields which get duplicated
    env: prod
    valuesFiles:
    - values.yaml
    - values-prd.yaml
    - values-appf-prd.yaml
```

To fix this you should unset one or the either. You can do this by either 

1. editing the app spec using kubectl:
`kubectl edit app <myapp>`

and remove `spec.source.env` and `spec.source.ksonnet`

Or using argocd cli, download [v0.11.1](https://github.com/argoproj/argo-cd/releases/tag/v0.11.1) and run:
```
argocd app set APPNAME --env ""
```
or 
```
argocd app unset APPNAME --values values1.yaml --values values2.yaml
```
You will need v0.11.1 (as opposed to v0.11.0) to do this since the CLI was fixed to allow the unsetting of these fields.
