### ISSUE TITLE
can't auth by azure

### ISSUE THREAD

**Issue by gsgs-libin** [argoproj/argo-cd#10559]
I configure it through this document: [https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/#azure-ad-saml-enterprise-app-auth-using-dex](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/#azure-ad-saml-enterprise-app-auth-using-dex)

but,I got some error in pod (argocd-dex-server):

{"level":"error","msg":"Failed to authenticate: no attribute with name \"email\": [http://schemas.microsoft.com/identity/claims/tenantid http://schemas.microsoft.com/identity/claims/objectidentifier http://schemas.microsoft.com/identity/claims/identityprovider http://schemas.microsoft.com/claims/authnmethodsreferences http://schemas.microsoft.com/ws/2008/06/identity/claims/wids Group]","time":"2022-09-09T03:34:47Z"}

Please help me！

**Comment by gsgs-libin** [comment]
there is some config in azure:
![image](https://user-images.githubusercontent.com/22513159/189266911-eea8dabb-32d7-4ca1-b530-36aebe63b06b.png)
![image](https://user-images.githubusercontent.com/22513159/189266939-764dce8e-427b-41cc-97d5-57dac52371d0.png)

**Comment by gsgs-libin** [comment]
I solved this problem by set the self account email addr in azure console.
![image](https://user-images.githubusercontent.com/22513159/189271895-16a6212e-14af-4fd9-a546-8c3ee671a4b0.png)

**Comment by galingit** [comment]
Hi there! We are getting the same error message. We also followed the same guide.
Adding email to users account does not solved the issue. We are in enterprise scenario setup that all user attributes are managed via local metaTree tool that is synced with AzureAD. All users that we added to ArgoCD Groups have email attribute in Azure AD accounts. Please, advice how to troubleshoot this issue. Thank you in advance!

**Comment by woehrl01** [comment]
@galingit @gsgs-libin 

If you don't have the `user.mail` field setup in Azure, you have to map a different field in the `Attributes & Claim` section, possible fields could be `user.userprincipalname` which often contains a mail address, too.

**Comment by galingit** [comment]
@woehrl01 Thanks for the reply! We have tried with both suggestions, but still the same result.
Here is the screenshot from our Azure SP configuration: 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/22906499/221795806-243d841e-6a94-4734-adb9-bad659b3c61b.png)

We also tried as you suggested:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/22906499/221802824-dd1becf7-28f4-438f-8b4b-b1f90778022b.png)

We always get this message when user try to login via SAML:

![Screenshot 2023-02-28 at 10 27 43](https://user-images.githubusercontent.com/22906499/221796813-46e454cc-ab07-4fb5-b118-581ec05f695c.png)

**Comment by woehrl01** [comment]
I just had a look at my config, we are not using dex, and we are using OIDC instead of SAML. Have you tried that, too?

**Comment by galingit** [comment]
@woehrl01 We would try this. Can you share your oidc.config please? Thank you in advance

**Comment by woehrl01** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"

  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/xxxxx-xxxxxx-xxxxxxx-xxxxx/v2.0
    clientID: $argo-sso-creds:clientId
    clientSecret: $argo-sso-creds:apiKey
    requestedIDTokenClaims:
        groups:
            essential: true
    requestedScopes:
        - openid
        - profile
        - email
```

Sure, this is our configuration. `admin.enabled: false` can be used to remove the login form and use SSO only.
