### ISSUE TITLE
Deploying Helm charts does not work (remote error:  upload-pack: not our ref)

### ISSUE THREAD

**Issue by brunocascio** [argoproj/argo-cd#10555]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Setting application pointing to a helm chart stored in a git repo fails.
If I include this helm-chart into a kustomization.yml, it works but I would like to avoid it in this case.

**To Reproduce**

project.yml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-bruno-test-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project that contains bruno test-helm resources
  sourceRepos:
    - 'https://bitbucket.example.com/**/*.git'
  # Allow specific namespaces to be deployed only on specific destinations (clusters)
  destinations:
    - namespace: app-bruno-test-helm
      name: management
  # Deny all cluster-scoped resources from being created, except for:
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
  # Allow all namespaced-scoped resources from being created, except for:
  namespaceResourceBlacklist:
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.istio.io'
      kind: Gateway
```

app.yml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-bruno-test-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-bruno-test-helm
  source:
    repoURL: https://bitbucket.example.com/scm/kube/helm-charts.git
    path: chart-sources/http-app
    targetRevision: HEAD
    helm:
      releaseName: http-app-test
      valueFiles:
        - values.yaml
  destination:
    name: management
    namespace: app-bruno-test-helm
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

Helm charts should be deployed without that flicky error

**Screenshots**

https://user-images.githubusercontent.com/2397875/189192523-d29f7193-9fce-43b3-a7ee-9c383f66d359.mov

**Version**

```shell
2.4.11
```

**Logs**

```

```
ComparisonError: rpc error: code = Internal desc = Failed to checkout revision 81d195992f94a1cb59f11ba336fc660b1e613657: 
`git fetch origin 81d195992f94a1cb59f11ba336fc660b1e613657 --tags --force` failed exit status 128: fatal: remote error: 
upload-pack: not our ref 81d195992f94a1cb59f11ba336fc660b1e613657. Retrying attempt #3 at 5:53PM.
```
