### ISSUE TITLE
Argocd fails to sync suspended job

### ISSUE THREAD

**Issue by antoniolucasnobar** [argoproj/argo-cd#10600]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

ArgoCD hangs and fails when I try to sync a app which has a Job in suspended state.

I have a job suspended:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "99"
  name: sigep-fotos-sincronizador-job
  labels:
    app: sigep-fotos-sincronizador
spec:
  suspend: true
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: sigep-fotos-sincronizador
    spec:
      activeDeadlineSeconds: 2147483647
```

I can see in ArgoCD the job status:

```
status:
  conditions:
    - lastProbeTime: '2022-09-15T14:23:57Z'
      lastTransitionTime: '2022-09-15T14:23:57Z'
      message: Job suspended
      reason: JobSuspended
      status: 'True'
      type: Suspended
```

But, if I try to sync this Job, it never fires a pod (expected), but keeps running (syncing) until deadline occurs. 

Why would I sync a suspended job. I do a batch sync using labels (We have lots of apps to sync). I want to sync all apps, but ignore the suspended job, but I can not do that, as it hangs in this particular Job.

**To Reproduce**

Create a Job with spec.suspend: true and try to sync it with ArgoCD.

**Expected behavior**

Sync to finish sucessfully (without firing a Job)

**Screenshots**
<img width="423" alt="image" src="https://user-images.githubusercontent.com/34720010/190437204-aa1b521e-c693-445f-a06f-b4b430289c45.png">
job is running indefinetly

job is suspended:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/34720010/190438014-09f2584f-87d9-4607-948d-becaa323e9b5.png">

**Version**

```shell
argocd: v2.4.11+3d9e9f2.dirty
  BuildDate: 2022-08-22T19:33:23Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: dirty
  GoVersion: go1.19
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.10+2ccc17a
  BuildDate: 2022-08-17T21:03:50Z
  GitCommit: 2ccc17afcbad78651cf7cd76891cdf7728cd488e
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
I do not have access to logs
```
