### ISSUE TITLE
SCM Provider Enhancement: Exclusion Labels

### ISSUE THREAD

**Issue by DaytonG** [argoproj/argo-cd#10652]
# Summary

I'm using the SCM provider to gather a list of repositories from a private gitlab enterprise server. I would like to use a label to _exclude_ repos, like `block-deploy` to instead deny certain repos from being deployed.

# Motivation

We split our gitlab groups into separate areas per company effort. Some of those projects are in the incubation phase, and should be ignored in certain environments. It would be nice to assume that all "deploy-.*" repos are available and instead exclude repos using repo tag metadata. Less repos to touch.

# Proposal

The first idea that comes to mind is to add a new "excludeLabel" filter type.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - scmProvider:
      filters:
      - repositoryMatch: ^myapp
        pathsExist: [kubernetes/kustomization.yaml]
      # a new filter that checks for the presence of a label. If found: ignore the repo
      - excludeLabel: "block-deploy"
  template:
  # ...
```

That being said, I'm not familiar with the code structure of filters.
