### ISSUE TITLE
--enable-helm flag added to argocd-cm but ArgoCD deployment fails: "must specify --enable-helm"

### ISSUE THREAD

**Issue by pmula-onbe** [argoproj/argo-cd#10651]
Checklist:

* [X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

I'm testing deploying the datadog agent with kustomize and helm and I'm getting this error:

rpc error: code = Unknown desc = `kustomize build .qa/apptest` failed exit status 1: Error: trouble configuring builtin HelmChartInflationGenerator with config: ` name: apptest namespace: test releaseName: apptestv1 repo: https://helm.datadoghq.com valuesFile: values-dd.yaml version: 3.1.3 `: must specify --enable-helm

Flag was added correctly before this but still complains about adding the flag.

**To Reproduce**

Created an argo app. Files go under qa/apptest.
|- qa
 |--apptest
  |--- kustomization.yaml
  |--- values-dd.yaml
  |--- namespace.yaml

kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: apptest
  repo: https://helm.datadoghq.com
  version: 3.1.3
  releaseName: apptestv1
  namespace: test
  valuesFile: values-dd.yaml
```

Modified my argocd config map to enable the flag:

argocd-cm.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  server.insecure: "true"
```

**Expected behavior**

App it's deployed using Kustomize and helm without any issues using the added flag: --enable-helm

**Version**

```shell
argocd: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:46:48Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: windows/amd64
time="2022-09-20T17:22:28Z" level=warning msg="Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web."
argocd-server: v2.4.12+41f54aa
  BuildDate: 2022-09-16T00:45:01Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```
