### ISSUE TITLE
Make it possible to set release name different from argcd app name. 

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1066]
Now the argocd app name is used as release name in the helm templating.  It would be great if it is possible to use a seperate app name and release name like this:

argocd create app artifactory-prd --release-name artifactory ....
This way we can create apps for production cluster and test cluster with the same release name. 

Reason we need this is that not all helm charts have the possibility to use the nameOverride parameter.

**Comment by jessesuen** [comment]
We briefly considered this, but I think there may have been issue about the combination of:

1. our decision to inject `app.kubernetes.io/instance` to be the app name
2. using app name as helm release name (i.e. `helm template --name <appname>`)
3. modern helm charts (created after helm 2.12?) also using release name in `app.kubernetes.io/instance` label.

I think the error scenario is:
1. modern Helm charts  created using `helm create` (v2.12) will auto-generate labels, including `app.kubernetes.io/instance = <release name>`
2. Argo CD overrides this label with `app.kubernetes.io/instance = <argocd app name>`
3. Since the two would be different, it may cause problems for the helm chart.

**Comment by igaskin** [comment]
This requests seems especially important when managing helm charts installed from a helm repository, instead of installing the chart from source.  As a workaround I removed all references to `{{ .Release.Name }}` in my local helm chart, and substituted it with a consistent name.  Keep in mind that if the release name is used as a label selector, it cannot be changed once set: https://github.com/kubernetes/kubernetes/issues/58597

**Comment by jessesuen** [comment]
I think it's fine to support releaseName, but we need to detect and error if the helm chart is using `app.kubernetes.io/instance: <release-name>`, and Argo CD wants to do `app.kubernetes.io/instance: <application-name>`.

For example, this the following situation:

Application Spec:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
spec:
  source:
    helm:
      releaseName: bar
```

Helm template: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-test.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-test.name" . }}
    helm.sh/chart: {{ include "helm-test.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-test.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-test.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
```
