### ISSUE TITLE
Possibility to revert app based on commit hash not revision ID

### ISSUE THREAD

**Issue by Wojciech-Chilinski** [argoproj/argo-cd#10669]
# Summary

Right now to revert the app you need to specify (or find in UI) the revision ID of the app, it is mapped to the commit hash. To expand the capabilities of this functionality it would be nice to be able to revert the app to a particular commit hash from the git repository.

# Motivation

argocd storing only the last 10 IDs of the revisions. if you want to revert the app to an older revision there is no way to do that from argocd level.

# Proposal

Introduce a special flag for this purpose ex:
```argocd app rollback APPNAME [ID] [--revision aaaaaaa] [flags]```

or make a count of history entries parametrized so we can increase this 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  revisionHistoryLimit: 20
```
[Edit] It is already possible with ```revisionHistoryLimit``` field.
