### ISSUE TITLE
Proxy support for helm repo in dependency or better description for requirements.yaml

### ISSUE THREAD

**Issue by ebini** [argoproj/argo-cd#10676]
# Summary

There is an example with this file:
[argo-cd](https://github.com/argoproj/argo-cd)/[applicationset](https://github.com/argoproj/argo-cd/tree/master/applicationset)/[examples](https://github.com/argoproj/argo-cd/tree/master/applicationset/examples)/[git-generator-directory](https://github.com/argoproj/argo-cd/tree/master/applicationset/examples/git-generator-directory)/[cluster-addons](https://github.com/argoproj/argo-cd/tree/master/applicationset/examples/git-generator-directory/cluster-addons)/[prometheus-operator](https://github.com/argoproj/argo-cd/tree/master/applicationset/examples/git-generator-directory/cluster-addons/prometheus-operator)/requirements.yaml

I haven't found a good documentation and especially is it possible to reference the repository via an https proxy.

# Motivation

We want to access from an internet helm chart to an k8s which only has access to the internet via proxy

# Proposal
If it is not possible yet, please add proxy support for repositories

for example
```
dependencies:
  - name: grafana
    version: 6.38.7
    repository: 
       - url: https://grafana.github.io/helm-charts
       - proxy: http://proxy.special:8080
```
or reference an existing/added helm repository.

or if it already exists, i'm very sorry that i opened this and a link would be great.

Thanks florian
