### ISSUE TITLE
Support Bitbucket Cloud Pull Request Generator

### ISSUE THREAD

**Issue by aprams** [argoproj/argo-cd#10695]
# Summary

ArgoCD already supports the following SCMaaS providers for pull request generators: (According to [these docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/#bitbucket-server))
- Github
- Gitea
- Bitbucket Server (not the same as BB Cloud) 

# Motivation

As Atlassian's cloud products are a large segment of their users, it would be great to also support BitBucket Cloud as a Pull Request provider.

# Proposal

This should look quite similar to the Bitbucket Server implementation, along the lines of:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - pullRequest:
      bitbucketCloud:
        organization: myOrg
        project: myproject
        repo: myrepository
        # Credentials for Basic authentication. Required for private repositories.
        basicAuth:
          # The username to authenticate with
          username: myuser
          # Reference to a Secret containing the password or app password token.
          passwordRef:
            secretName: mypassword
            key: password
      # Labels are not supported by Bitbucket Server, so filtering by label is not possible.
      # Filter PRs using the source branch name. (optional)
      filters:
      - branchMatch: ".*-argocd"
  template:
  # ...
```
