### ISSUE TITLE
Feature Request: Pre-defined filters (tabs)

### ISSUE THREAD

**Issue by vsychov** [argoproj/argo-cd#10716]
# Summary

![argo-cd](https://user-images.githubusercontent.com/2186303/192546835-b37dea4a-baad-4eb0-a2bc-75ea50bb0dfa.png)

It would be nice to have pre-defined filters (based on LABELS, PROJECTS, CLUSTERS, NAMESPACES) via config

# Motivation

if you have many applications in argo in many projects, then it is very inconvenient to switch between them every time (you need to adjust filters every time)

# Proposal

Add pre-defined filters to argocd ui

**Comment by crenshaw-dev** [comment]
Can you provide an example of how you would like these presets configured?

**Comment by vsychov** [comment]
@crenshaw-dev, something like this:
```yaml
preDefinedFilters:
  filter1: #unique filter id (for e.g. to keep in page address bar)
    # works like descibed here: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
    name: "My Super Filter" #default to "key" (filter1)
    labels: 
       match: #optional
          label1: foo
          label2: bar
       expressions: #optional
            - {key: tier, operator: In, values: [cache]}
            - {key: environment, operator: NotIn, values: [dev]}

     #projects, clusters, namespaces - are same to "labels"
```
