### ISSUE TITLE
Out of Sync on Argo CD Server Side Apply for existing resource.

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj/argo-cd#10740]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I was testing the Argo CD Server Side Apply feature by building Argo CD from master. 

I used the Argo CD SSA on an existing resource on the cluster and noticed that Argo CD was able to apply the configuration using serverside but the application stays out-of-sync. 

The same configuration is well synced without `ServerSideApply`.

**To Reproduce**
1. Build Argo CD from master or use the Argo CD Image below.
`docker.io/abhishekf5/argocd:testing-ssa:sha256:ac5d7b74e71eb6453944d564e1b5f056a4f3d8c4447141cde0e9f540a7115afc`
2. Create a simple nginx resource on your namespace WITHOUT Argo CD.
`kubectl create deploy nginx --image=nginx`
and label the resource
`kubectl label deploy nginx foo1=bar1 foo2=bar2`
3. Create an Argo CD application which points to the nginx deployment yaml. You can use the application yaml as shown below.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ssa
    repoURL: https://github.com/iam-veeramalla/demo-repo
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
```

Please refer to the screenshots section for more information.

**Expected behavior**
Application should not be out-of-sync.

**Screenshots**
![Screenshot 2022-09-29 at 6 14 54 PM](https://user-images.githubusercontent.com/43399466/193034888-afbb2263-7875-42d4-91d1-40eaead66285.png)
![Screenshot 2022-09-29 at 6 15 15 PM](https://user-images.githubusercontent.com/43399466/193034898-235fada4-ee55-456f-95f6-4735ee969cb5.png)
