### ISSUE TITLE
Ability to selectively ignore differences to support fuzzy diff comparisons

### ISSUE THREAD

**Issue by category** [argoproj/argo-cd#1075]
Thank you very much for your work on Argo CD, this project is an excellent implementation of CD in Kubernetes.

As per the [FAQs](https://github.com/argoproj/argo-cd/blob/master/docs/faq.md), mutating webhooks will cause the deployment to be shown as **OutOfSync** - what is the best method for dealing with this?

I'm thinking of a directive that tells argocd what part of the `MutatingWebhookConfiguration` to monitor - is there a better way at present?

**Comment by wreed4** [comment]
How should this work when I have multiple webhooks defined in one resource?? It currently seems like I have to do 
```yaml
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
```
which actually doesn't quite seem to be working... I don't know exactly how many webhooks may be specified and I'm trying to solve this all at once.  It seems that if any of these paths throws an error, it doesn't work. I'd really like to just be able to wildcard the number?
