### ISSUE TITLE
Previous CronJob Jobs have been deleted, but show in ArgoCD UI

### ISSUE THREAD

**Issue by deybhayden** [argoproj/argo-cd#10759]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have a CronJob resource that runs every 10 minutes and has `ttlSecondsAfterFinished` set to delete the Job resource after `100` seconds. K8s is behaving correctly, however when I view the ArgoCD UI there are several old Jobs & Pods sitting around. When I try to delete them, I receive an error saying the resource doesn't exist.

**To Reproduce**

Abstracted CronJob Manifest showing this behavior

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cdl-api-10min-ping-comp
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: monitor
              image: example.org/api-monitor:latest
              env:
                - name: API_MONITOR_URL
                  value: http://example.org
          restartPolicy: OnFailure
```

I have an Application that is using `kustomization.yaml` which includes this CronJob as a resource.

**Expected behavior**

That the deleted Jobs & Pods wouldn't show up on the UI.

**Screenshots**

<img width="977" alt="Screen Shot 2022-09-30 at 5 22 08 PM" src="https://user-images.githubusercontent.com/877908/193365856-e7048c4f-5369-4ea9-8036-b7dff617c99b.png">
<img width="1464" alt="Screen Shot 2022-09-30 at 5 22 18 PM" src="https://user-images.githubusercontent.com/877908/193365859-ebc1f7d7-a586-4699-96d9-1794f1d4ba5d.png">

**Version**

```shell
argocd: v2.4.12+41f54aa.dirty
  BuildDate: 2022-09-16T03:19:53Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: dirty
  GoVersion: go1.19.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by larstiq** [comment]
I am seeing the same problem with `v2.2.10`, 22 `job` objects in the Argo UI spawned from a single `cronjob`, but only 7 in the cluster.

**Comment by ksink7** [comment]
I am having the same issue. Not every job stays there, but over a few days, they start to add up.

**Comment by crenshaw-dev** [comment]
Maybe related to: https://github.com/argoproj/argo-cd/issues/9226

**Comment by h4tt3n** [comment]
I am seeing the exact same bug. Old jobs and pods build up over time, but cannot be deleted or found though kubectl. The only way to remove the ghost resources is to delete the parent cronjob and let ArgoCD recreate it for me.

**Comment by mmerickel** [comment]
Seeing this problem on argocd 2.7.7 - a restart of the application controller fixes the issue as well. To reiterate - the job/pod does not exist in the cluster, it is just a dangling reference that argo is hanging onto that is causing confusion in the argocd UI.

**Comment by afernandez-01** [comment]
+1

**Comment by john-gomersall** [comment]
> Use the Argo Hook Deletion Policy for cleaning up completed/failed jobs rather the K8s ttlStrategy. https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/
> 
> I'm using the annotation, and it works for me.
> 
> ```
>   annotations:
>     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
> ```

Not sure how this would work for CronJobs...

**Comment by afernandez-01** [comment]
Here is how I'm using this with a cronjob
```
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: customjob
  namespace: customjobnamespace
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - command:
...
```
