### ISSUE TITLE
ArgoCD renders Helm charts differently then local `helm template` (overriding objects with nulls)

### ISSUE THREAD

**Issue by jacek-jablonski** [argoproj/argo-cd#10779]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD renders Helm charts differently then local `helm template` command. I have specified a default value for some parameter as an object in my subchart's `values.yaml` and in the parent's chart `values.yaml` I am nullifying this parameter. As a result, in ArgoCD resource is generated with this value redendered as if it was never nullified.

**To Reproduce**

Suchart's `values.yaml`:
```
...
retryStrategy:
  limit: "5"
  backoff:
    duration: "1m"
    factor: "4"
    maxDuration: ""
...
```

Subchart's template:
```
...
    {{- if $.Values.retryStrategy }}
    retryStrategy:
      {{- include "common.tplvalues.render" (dict "value" $.Values.retryStrategy "context" $) | nindent 6 }}
    {{- end }}
...
```

Parent chart `values.yaml`:
```
...
retryStrategy: null
...
```

Local `helm template` command generates (note: no `retryStrategy`):
```
...
spec:
  schedule: "*/10 * * * *"
  timezone: "Etc/UTC"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 100
  failedJobsHistoryLimit: 100
  suspend: false
  workflowMetadata:
    labels:
      app.kubernetes.io/name: jobs
      helm.sh/chart: jobs-0.2.14
      app.kubernetes.io/instance: jobs
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/component: jobs
  workflowSpec:
    workflowTemplateRef:
      name: jobs-stats-test-client-panel
...
```

ArgoCD generates (note: `retryStrategy` is present):
```
...
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 100
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 100
  suspend: false
  timezone: Etc/UTC
  workflowMetadata:
    labels:
      app.kubernetes.io/component: jobs
      app.kubernetes.io/instance: jobs
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: jobs
      helm.sh/chart: jobs-0.2.14
  workflowSpec:
    retryStrategy:
      backoff:
        duration: 1m
        factor: '4'
        maxDuration: ''
      limit: '5'
    workflowTemplateRef:
      name: e2e-monitoring-tests-jobs-test-client-panel
...
```

**Expected behavior**

ArgoCD shouldn't render `retryStrategy` if it was nullifed in parent's chart.

**Screenshots**

![image](https://user-images.githubusercontent.com/35669512/193677427-704d3947-27bc-4f07-b085-1e3b2d750373.png)
![image](https://user-images.githubusercontent.com/35669512/193677515-8a6b9f09-573c-4cb0-848d-96fec3ecc8c5.png)

**Version**

```shell
argocd: v2.4.12+41f54aa.dirty
  BuildDate: 2022-09-16T03:19:53Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: dirty
  GoVersion: go1.19.1
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by todaywasawesome** [comment]
Can you share the app settings? The most likely is there is a misconfiguration there.

**Comment by jacek-jablonski** [comment]
Application Manifest:
```
project: e2e-tests
source:
  repoURL: 'https://github.com/xxx/infra-e2e-monitoring-tests'
  path: e2e-monitoring-tests/
  targetRevision: HEAD
destination:
  namespace: e2e-tests
  name: prod
syncPolicy:
  automated: {}
```
