### ISSUE TITLE
UI: Ultrawide support

### ISSUE THREAD

**Issue by Jellyfrog** [argoproj/argo-cd#10772]
# Summary

When using Argo CD on a ultrawide monitor, you still need to zoom out to 10-20% if you want to see all resources at the same time,

# Motivation
Currently it looks something like this when deploying argo cd itself:
![screenshot](https://user-images.githubusercontent.com/759887/193584919-a9ccc1b7-e19f-4217-955a-7563f3d9f10d.png)

# Proposal
I'd suggest we add a new mode that shows the resources horizontally, like this:
![screenshot](https://user-images.githubusercontent.com/759887/193590592-1dcd1465-275f-4d28-bfd4-91c3650b9e4c.png)
But preferentially flips the text and icons also ;)

(I simply added the `rotate` property):
```css
.application-resource-tree {
 width: 1469px;
 height: 5297.5px;
 transform: scale(0.7) rotate(90deg);
}
```
