### ISSUE TITLE
ArgoCD Application ressources being deployed in argocd namespace instead of defined namespace of destination

### ISSUE THREAD

**Issue by AlexandreODelisle** [argoproj/argo-cd#10807]
**Describe the bug**

The ArgoCD application is being deployed ( k8s ressource ) on the argocd namespace instead of the namespace defined  in the `spec.destination.namespace`

**To Reproduce**

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aqua-enforcers
  namespace: argocd
spec:
  destination:
    namespace: aqua
    server: 'https://kubernetes.default.svc'
  source:
    chart: kube-enforcer
    repoURL: https://helm.aquasec.com
    targetRevision: "2022.04.07"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

```
**Expected behavior**

The ArgoCD Application is being fully deployed in the defined destination namespace

**Version**

ArgoCD v2.4.3

I see that the version v2.5.0 will support a watcher for ArgoCD Application defined in other namespaces would that fix the issue, or should it already support it?

The helm chart looks for the `.Release.Namespace` to define the k8s ressources.
