### ISSUE TITLE
Update docs for Server-Side Apply to patch existing resources.

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj/argo-cd#10821]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [] I've pasted the output of `argocd version`.

**Describe the bug**
Server-Side Apply docs does not talk about patching of existing resources by turning off schema validation. For example, I have a deployment on the cluster that is **NOT** already managed by Argo CD. 

Now, I want to update the replicas of the deployment using `ServerSideApply`.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
```

The kubectl command to achieve this is `kubectl apply --server-side --validate=false -f xxx.yaml`. 

Please update the documentation on how to achieve this using Argo CD.

**To Reproduce**
1. Create a nginx deployment on the cluster using `kubectl`
`kubectl create deployment nginx --image=nginx`
2. Increase the replicas of the deployment using Argo CD. 
 - Upload the intended or partial nginx deployment yaml with `3` replicas in any git repo.
 ```
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-deployment
  spec:
    replicas: 3
 ```
 3. Create an Argo CD Application with ServerSideApply enabled as mentioned in the docs.

You will see an error with respect to the failing schema validation. 

**Expected behavior**

ServerSide Apply docs should provide information about patching of existing resources.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
