### ISSUE TITLE
Support Jsonnet external variables and top level arguments

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1082]
Expose top level arguments and external variables to a Jsonnet app source. Here is a spec proposal:

```yaml
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    jsonnet:

      ext:
      # equivalent to: jsonnet --ext-str foo=bar
      - name: foo
        value: bar

      # equivalent to: jsonnet --ext-code fooObj=bar
      - name: fooObj
        value: "true"
        code: true

      tla:
      # equivalent to: jsonnet --tla-str foo=bar
      - name: foo
        value: bar

      # equivalent to: jsonnet --tla-code fooObj=bar
      - name: fooObj
        value: "true"
        code: true
```

EDIT: removed request for Sjsonnet from issue
