### ISSUE TITLE
ApplicationSets not displayed in UI

### ISSUE THREAD

**Issue by Gianluca755** [argoproj/argo-cd#10837]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
ApplicationsSet is not displayed in UI (Tiles), only the Applications that are created.
This makes the Applications respawn after deletion if auto-sync is enabled.
If an Application is managing an ApplicationSet, they're correctly shown in the UI tree view.

**To Reproduce**
I used this test file.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: projects
spec:
  generators:
  - list:
      elements:
      - nameProject: test
        repoURL: https://github.com/courselabs/kubernetes.git 
        targetRevision: HEAD
        path: labs/productionizing/solution
        server: https://kubernetes.default.svc 
        namespace: default

  template:
    metadata:
      name: '{{nameProject}}-application'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        directory:
          recurse: false
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

**Version**

```shell
{
    "Version": "v2.4.14+029be59",
    "BuildDate": "2022-10-05T17:15:37Z",
    "GitCommit": "029be590bfd5003d65ddabb4d4cb8a31bff29c18",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.7",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```
