### ISSUE TITLE
ApplicationSet: cannot fork() for ssh

### ISSUE THREAD

**Issue by Veluu** [argoproj/argo-cd#10832]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using ArgoCD  `ApplicationSet`. Configured as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-name
spec:
  generators:
    - git:
        repoURL: git@bitbucket.org:my-repository-with-k8s-manifests.git
        revision: HEAD
        directories:
          - path: tenants/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: git@bitbucket.org:my-repository-with-k8s-manifests.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
```
It's been working fine. Today I just added another catalogue into `repository-with-k8s-manifests.git` and the application was not created. I checked the logs and got some `fork()` problems. I thought it might be some kind of lack of memory issue but I checked available resources - plenty left on nodes, no limits on applicationset pod etc. I deleted the ApplicationSet pod and after it was re-created my new application showed up.

I checked history of memory utilization and it's been stable for the last 30d. No spikes etc.

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:46:59Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.3+07ac038
```

**Logs**

```
time="2022-10-06T15:25:32Z" level=error msg="error generating application from params" error="Error during fetching repo: `git fetch origin HEAD --tags --force` failed exit status 128: error: cannot fork() for ssh -i /dev/shm/2931678869 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/app/config/ssh/ssh_known_hosts: Resource temporarily unavailable\nfatal: unable to fork" generator="{<nil> <nil> 0xc000aa1040 <nil> <nil> <nil> <nil> <nil>}"
1.6650699326002934e+09	ERROR	controller.applicationset	Reconciler error	{"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "app-set-name", "namespace": "argocd", "error": "Error during fetching repo: `git fetch origin HEAD --tags --force` failed exit status 128: error: cannot fork() for ssh -i /dev/shm/2931678869 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/app/config/ssh/ssh_known_hosts: Resource temporarily unavailable\nfatal: unable to fork", "errorVerbose": "`git fetch origin HEAD --tags --force` failed exit status 128: error: cannot fork() for ssh -i /dev/shm/2931678869 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/app/config/ssh/ssh_known_hosts: Resource temporarily unavailable\nfatal: unable to fork\nError during fetching repo\ngithub.com/argoproj/applicationset/pkg/services.checkoutRepo\n\t/workspace/pkg/services/repo_service.go:137\ngithub.com/argoproj/applicationset/pkg/services.(*argoCDService).GetDirectories\n\t/workspace/pkg/services/repo_service.go:87\ngithub.com/argoproj/applicationset/pkg/generators.(*GitGenerator).generateParamsForGitDirectories\n\t/workspace/pkg/generators/git.go:76\ngithub.com/argoproj/applicationset/pkg/generators.(*GitGenerator).GenerateParams\n\t/workspace/pkg/generators/git.go:60\ngithub.com/argoproj/applicationset/pkg/generators.Transform\n\t/workspace/pkg/generators/generator_spec_processor.go:52\ngithub.com/argoproj/applicationset/pkg/controllers.(*ApplicationSetReconciler).generateApplications\n\t/workspace/pkg/controllers/applicationset_controller.go:432\ngithub.com/argoproj/applicationset/pkg/controllers.(*ApplicationSetReconciler).Reconcile\n\t/workspace/pkg/controllers/applicationset_controller.go:96\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
time="2022-10-06T15:25:32Z" level=info msg="git fetch origin HEAD --tags --force" dir=/tmp/git@bitbucket.org_my-repository-with-k8s-manifests execID=65c06
time="2022-10-06T15:25:32Z" level=error msg="`git fetch origin HEAD --tags --force` failed exit status 128: error: cannot fork() for ssh -i /dev/shm/3698323688 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/app/config/ssh/ssh_known_hosts: Resource temporarily unavailable\nfatal: unable to fork" execID=65c06
time="2022-10-06T15:25:32Z" level=info msg=Trace args="[git fetch origin HEAD --tags --force]" dir=/tmp/git@bitbucket.org_my-repository-with-k8s-manifests operation_name="exec git" time_ms=12.952193000000001
time="2022-10-06T15:25:32Z" level=error msg="error generating params" error="Error during fetching repo: `git fetch origin HEAD --tags --force` failed exit status 128: error: cannot fork() for ssh -i /dev/shm/3698323688 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/app/config/ssh/ssh_known_hosts: Resource temporarily unavailable\nfatal: unable to fork" generator="&{0xc000a2c5f0}"
```
