### ISSUE TITLE
Recurse app source directories

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1083]
For directory based applications, we should provide a flag to allow the option to recurse sub directories for yaml files.

This proposal introduce a new application source field for directories, with a recurse option:

```yaml
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    directory:
      recurse: true
```

If true, the repo-server will walk sub directories for yaml files.
