### ISSUE TITLE
ArgoCD user POD interface does not hide logs tab based on RBAC

### ISSUE THREAD

**Issue by folsh** [argoproj/argo-cd#10877]
Checklist:

* [v] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [v] I've included steps to reproduce the bug.
* [v] I've pasted the output of `argocd version`.

**Describe the bug**

I created a user (visitor) with the role (noLogs). This user shouldn't have access to the pods logs after deploying rbac in my k8s but it still can see them. Did i miss something ? I have followed this documentation: https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.3-2.4/#enable-logs-rbac-enforcementversion

**To Reproduce**

argocd-cm.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:

  server.rbac.log.enforce.enable: "true"

  accounts.user3: apiKey, login
  accounts.user3.enable: "true" 
  accounts.visitor: apiKey, login
  accounts.visitor.enable: "true"
```

rbac-cm.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    ...
    p, role:noLogs, applications, get, *, allow
    p, role:noLogs, clusters, get, *, allow

    g, visitor, role:noLogs

    g, user3, role:admin

```

**Expected behavior**

I would like the "logs" tab to be removed from the pod details

**Screenshots**

![argocd_logs](https://user-images.githubusercontent.com/3035256/194865169-fee71b93-7073-4751-8cb1-5929b99f60c6.png)

**Version**

```shell
argocd: v2.4.13+19ec34e.dirty
  BuildDate: 2022-10-03T22:54:38Z
  GitCommit: 19ec34e134cac5e693ddd5f56844a946e6e1d44b
  GitTreeState: dirty
  GoVersion: go1.19.1
  Compiler: gc
  Platform: linux/amd64
```

**Comment by crenshaw-dev** [comment]
I just tested, and everything seems to work fine.

argocd-rbac-cm:

```yaml
data:
  policy.csv: |
    p, role:noLogs, applications, get, *, allow
    g, visitor, role:noLogs
```

argocd-cm:

```yaml
data:
  accounts.visitor: apiKey, login
  accounts.visitor.enable: "true"
  server.rbac.log.enforce.enable: "true"
```

`argocd version`:

```
argocd: v2.4.12+41f54aa
  BuildDate: 2022-09-16T01:05:30Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.13+19ec34e
  BuildDate: 2022-10-03T20:59:22Z
  GitCommit: 19ec34e134cac5e693ddd5f56844a946e6e1d44b
  GitTreeState: clean
  GoVersion: go1.18.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

I see that you're running 2.4.13 as the CLI. What version is the server running?
