### ISSUE TITLE
ApplicationSet probe only return 404 error codes

### ISSUE THREAD

**Issue by julien-michaud** [argoproj/argo-cd#10878]
The probe endpoint of the applicationset controller only return `404 Not Found` error codes. 

It can be problematic when you use a specific Ingress to route the traffic to the /api/webhook path on GKE.
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L2161

The correct backend config must look like this:

```
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: "argo-cd-applicationset-webhook"
spec:
  securityPolicy:
    name: allow-github-hooks-ips
  healthCheck:
    type: HTTP
    requestPath: /healthz
    port: 8081

```

But the GCP healthcheck will return 404 codes.

In the meantime, we use the metrics port to get the `200` response that the GCP healthcheck expect. 

`---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: "argo-cd-applicationset-webhook"
spec:
  securityPolicy:
    name: allow-github-hooks-ips
  healthCheck:
    type: HTTP
    requestPath: /metrics
    port: 8080
`

argocd version is `v2.4.14+029be59`
