### ISSUE TITLE
Cascade deletion with finalizer not working if destination cluster is external

### ISSUE THREAD

**Issue by bygui86** [argoproj/argo-cd#10883]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

As written in the doc at [this page](https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#about-the-deletion-finalizer):
> Argo CD's app controller watches for this (finalizer) and will then delete both the app and its resources.

This works nicely if the destination cluster is the same running ArgoCD.
If destination cluster is an external one, then deleting the app won't delete any managed resources.

**To Reproduce**

Deploy any ArgoCD Application configured as described in the following example and then delete it:

```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: # any project different than the one running argocd
  source:
    repoURL: #...
    targetRevision: #...
    path: #...
  destination:
    name: # any cluster different than the one running argocd
    namespace: #...
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
```

**Expected behavior**

After deleting an app, both the app and all managed resources must be deleted if the finalizer is specified in the app. No matter if that app is configure with internal or external cluster as destination.

**Screenshots**

No relevant screenshots.

**Version**

```shell
argocd: v2.4.14+029be59.dirty
  BuildDate: 2022-10-05T19:03:58Z
  GitCommit: 029be590bfd5003d65ddabb4d4cb8a31bff29c18
  GitTreeState: dirty
  GoVersion: go1.19.2
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.2.1+122ecef
  BuildDate: 2021-12-17T01:31:40Z
  GitCommit: 122ecefc3abfe8b691a08d9f3cecf9a170cc8c37
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Logs**

No relevant logs.
