### ISSUE TITLE
Proposal: Introduce an Optional Pull Mechanism for ApplicationSet

### ISSUE THREAD

**Issue by mikeshng** [argoproj/argo-cd#10908]
# Summary

Introduce an optional way for ApplicationSet resource deployment that uses the hub-spoke pattern / pull model. The ApplicationSet will generate Application CRs that will be pulled to the remote clusters and each remote cluster is responsible for reconciling the Application CR.

# Motivation

The current ArgoCD resource deployment is primarily pushing resources from a centralized cluster to the remote/managed clusters.
By introducing an optional pull model pattern, users will have another way to deploy resources:
The pull model offers some advantages over the existing push model:
- Scalability: well documented that hub-spoke pattern offers better scalability.
- Security: cluster credentials doesn't have to be stored in a centralized environment.
- Reduce the impact of a single point of centralized failure.

Argo Worfklow is also looking for a way to gain multicluster capability and a similar approach can be used to provide consistency between sister projects. See `https://github.com/argoproj/argo-workflows/issues/3523#issuecomment-1265407245`

This optional pull mechanism follows some similarity to the existing ArgoCD App of Apps pattern.

# Proposal

## Dependencies:
- The Open Cluster Management (OCM) multicluster environment needs to be setup. See https://open-cluster-management.io/
- In this pull model, OCM will provide the cluster inventory and ability to deliver workload to the remote/managed clusters.
- This proposal is based on the OCM API but we welcome suggestions to introduce it as a framework so that other projects can integrate with the pull model similar to OCM. Adding additional providers should not be difficult.

## Required Code Changes:
Imports the Open Cluster Management (OCM) API `https://github.com/open-cluster-management-io/api`

If there is an optional annotation `argocd.argoproj.io/pull-model: Enable=true` present in the ApplicationSet CR, the primary hub cluster with the ApplicationSet controller will:
- Evaluate the [Cluster Decision Resource Generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster-Decision-Resource/#cluster-decision-resource-generator). Other generators to be discussed.
- Validate the results of the cluster decisions using OCM API and ensure that all the managed cluster namespaces exist.
- Create a [ManifestWork](https://open-cluster-management.io/concepts/manifestwork/) CR wrapping Application CR in their own dedicated managed cluster namespace (See example at the bottom.)

## No Code Changes Requirement:
In the remote/managed cluster with the Application controller, the OCM agent will pull the Application CR from the primary hub cluster. The Application controller will reconcile and deploy resources accordingly. The results will be reported back to the primary cluster based on ManifestWork's feedback rules specifications. (See example at the bottom.)

## Diagram

```
                   Hub Cluster - ApplicationSet CR reconcile
            ApplicationSet Controller
             //                   \\
            //                     \\
      namespace cluster1       namespace cluster2
      OCM ManifestWork CR      OCM ManifestWork CR
      - Wraps Application CR   - Wraps Application CR
          /\                         /\
          || Pulls                   || Pulls
          ||                         ||
       cluster1                     cluster2
       Application CR => GitRepo <= Application CR
       - Deploy resources           - Deploy resources                           
```

##  ManifestWork wrapping Application CR example:
```
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: cluster1-guestbook-app-mw
  namespace: cluster1
spec:
  manifestConfigs:
  - feedbackRules:
    - jsonPaths:
      - name: healthStatus
        path: .status.health.status
      type: JSONPaths
    - jsonPaths:
      - name: syncStatus
        path: .status.sync.status
      type: JSONPaths
    resourceIdentifier:
      group: argoproj.io
      name: cluster1-guestbook-app
      namespace: argocd
      resource: applications
  workload:
    manifests:
    - apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        annotations:
          argocd.argoproj.io/ocm-managed-cluster: cluster1
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        name: cluster1-guestbook-app
        namespace: argocd
      spec:
        destination:
          namespace: guestbook
          server: https://kubernetes.default.svc
        project: default
        source:
          path: guestbook
          repoURL: https://github.com/argoproj/argocd-example-apps.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            prune: true
          syncOptions:
          - CreateNamespace=true
status:
...
      statusFeedback:
        values:
        - fieldValue:
            string: Healthy
            type: String
          name: healthStatus
        - fieldValue:
            string: Synced
            type: String
          name: syncStatus
...
```

## References:
- Video POC demonstration: https://youtu.be/vau-wLQOw9A
- https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#app-of-apps-pattern
- https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster-Decision-Resource/#cluster-decision-resource-generator
- https://open-cluster-management.io/
- https://github.com/open-cluster-management-io
