### ISSUE TITLE
PullRequest Generator: unknown field "appSecretName" in io.argoproj.v1alpha1.ApplicationSet.spec.generators.pullRequest.github

### ISSUE THREAD

**Issue by Fettah** [argoproj/argo-cd#10910]
I am trying to connect Argocd to our github account and the PullRequest generators. 
after created the applicationSet with all the configs, kubectl was compalaining that the appSecretname is known 

Here is my config:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-pr-testing
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: my-company
          repo: my-repository
          labels:
            - argocd-deployment
         appSecretName: github-repo-creds
          .....
```

after a `kubectl apply -f` i get the following error:
`: error validating data: ValidationError(ApplicationSet.spec.generators[0].pullRequest.github): unknown field "appSecretName" in io.argoproj.v1alpha1.ApplicationSet.spec.generators.pullRequest.github; if you choose to ignore these errors, turn validation off with --validate=false`

ArgoCD Version: v2.412
