### ISSUE TITLE
Strip whitespace from project role group names

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#10919]
# Summary

I think the API server should strip the leading/trailing whitespace from group names in project roles.

# Motivation

Intuit had a project role where a group name had a trailing whitespace. I believe this was the result of an accidental copy/paste to the UI.

```yaml
  roles:
  - description: admin
    groups:
    - 'group:Admins_99999 '
    name: admin
    policies:
    - p, proj:some-proj:admin, applications, *, some-proj/*, allow
```

# Proposal

The API server should strip leading/trailing whitespace from group names before adding them.

**Note:** I'm assuming that leading/trailing whitespace is always invalid around group names. I think that's true, but please disagree if I'm wrong!
