### ISSUE TITLE
UI Error caused by missing RBAC Permission

### ISSUE THREAD

**Issue by andredaube** [argoproj/argo-cd#10916]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Opening / showing a resource within the application view to which the Argo CD server has no access to leads to the UI error and its stack trace being shown.

**To Reproduce**

1. Create / modify the service account used for the Argo CD server so that it cannot read a certain resource kind of a resource managed by Argo CD.
1. Open / show that resource in the application view.

**Expected behavior**

This case should be handled properly by showing a warning / error message without the UI crashing.

**Screenshots**

![image](https://user-images.githubusercontent.com/5350371/195397084-8e02568b-f1dc-4996-9f26-14c463e98777.png)

**Version**

```yaml
argocd: v2.4.12+41f54aa
  BuildDate: 2022-09-16T00:45:01Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Chrome console:
```
GET https://<hidden>/api/v1/applications/azure-cli/resource?name=azure-cli-bcbbf67f8&namespace=demo-tenant-project1&resourceName=azure-cli-bcbbf67f8&version=v1&kind=ReplicaSet&group=apps 403 (Forbidden)

TypeError: Cannot read properties of null (reading 'kind')
    at p (main.d73b393b850229804000.js:2:1474214)
    at Object.children (main.d73b393b850229804000.js:2:1477768)
    at t.render (main.d73b393b850229804000.js:2:1117363)
    at Hs (main.d73b393b850229804000.js:2:805069)
    at js (main.d73b393b850229804000.js:2:804864)
    at ya (main.d73b393b850229804000.js:2:840345)
    at pl (main.d73b393b850229804000.js:2:831820)
    at dl (main.d73b393b850229804000.js:2:831745)
    at il (main.d73b393b850229804000.js:2:828775)
    at main.d73b393b850229804000.js:2:780554
```

Argo CD server error message in above 403 response:
```
error getting resource: replicasets.apps "azure-cli-bcbbf67f8" is forbidden: User "system:serviceaccount:demo-tenant-argocd:argocd-server" cannot get resource "replicasets" in API group "apps" in the namespace "demo-tenant-project1"
```

Chrome console (With UI hosted by webpack-dev-server, which proxies Argo CD API requests to the Argo CD server where the error occures):
```
GET http://localhost:4000/api/v1/applications/azure-cli/resource?name=azure-cli-bcbbf67f8&namespace=demo-tenant-project1&resourceName=azure-cli-bcbbf67f8&version=v1&kind=ReplicaSet&group=apps 403 (Forbidden)

Uncaught TypeError: Cannot read properties of null (reading 'kind')
    at getResourceTabs (resource-details.tsx?ee2e:115:83)
    at Object.eval [as children] (resource-details.tsx?ee2e:280:69)
    at DataLoader2.render (data-loader.tsx?58f1:102:31)
    at finishClassComponent (react-dom.development.js?61bb:17160:31)
    at updateClassComponent (react-dom.development.js?61bb:17110:24)
    at beginWork (react-dom.development.js?61bb:18620:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js?61bb:188:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237:16)
    at invokeGuardedCallback (react-dom.development.js?61bb:292:31)
    at beginWork$1 (react-dom.development.js?61bb:23203:7)

The above error occurred in the <DataLoader2> component:
    in DataLoader2 (created by ResourceDetails)
    in div (created by ResourceDetails)
    in ResourceDetails (created by DataLoader2)
    in div (created by RenderSlidingPanel)
    in div (created by RenderSlidingPanel)
    in div (created by RenderSlidingPanel)
    in RenderSlidingPanel (created by SlidingPanel)
    in KeybindingProvider (created by SlidingPanel)
    in SlidingPanel (created by DataLoader2)
    in div (created by Page)
    in div (created by Page)
    in Page (created by Page)
    in div (created by Page)
    in Page (created by DataLoader2)
    in div (created by DataLoader2)
    in DataLoader2 (created by ObservableQuery2)
    in ObservableQuery2 (created by ApplicationDetails2)
    in ApplicationDetails2 (created by Route2)
    in Route2 (created by ApplicationsContainer)
    in Switch2 (created by ApplicationsContainer)
    in ApplicationsContainer (created by Route2)
    in DataLoader2 (created by Banner)
    in Banner (created by Route2)
    in div (created by Layout)
    in Layout (created by Route2)
    in Route2 (created by App2)
    in Switch2 (created by App2)
    in Router2 (created by App2)
    in App2

React will try to recreate this component tree from scratch using the error boundary you provided, App2.
```

**Affected code**

https://github.com/argoproj/argo-cd/blob/v2.4.12/ui/src/app/applications/components/resource-details/resource-details.tsx#L100

**Related issues**
- #10647

**Comment by chrisob** [comment]
I'm seeing this occur when `argocd-server` doesn't have RBAC permissions for whichever resource is viewed in the UI.

Our usecase: We have multiple "restricted" Argo CD instances in a single cluster where we want to enforce multi-tenancy (ie. 5 Argo CD instances in 5 different Namespaces, each one with Roles/RoleBindings to manage resources in a few other isolated Namespaces).

Of course we could do something like add a RoleBinding to grant the `argocd-server` the `admin` Role, but it would be ideal if the UI displayed an empty "live view" when it doesn't have permissions to view a resource (I'm pretty sure I've seen this behavior before :thinking:)

**Comment by crenshaw-dev** [comment]
> it would be ideal if the UI displayed an empty "live view" when it doesn't have permissions to view a resource (I'm pretty sure I've seen this behavior before 🤔)

Yeah, I think the `{}` "live view" happens when a user has insufficient Argo CD RBAC. Seems like we could do something similar when the server has insufficient k8s RBAC.

**Comment by crenshaw-dev** [comment]
I'm unable to reproduce this in 2.4.12, running in docker-desktop with the server port-forwarded.

Here's my ClusterRole:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-server
rules: null
```

I'm getting the expected 403 from the API server, but not the UI runtime error. 

Is this issue limited to the webpack dev server.

**Comment by andredaube** [comment]
The first stack trace from the Chrome console in my issue description above occurred in the UI hosted by the argocd-server Deployment, there is no webpack-dev-server running.
I could view the resource in ArgoCD by appending the `rules` of the Role:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-tenant-argocd-server
  namespace: demo-tenant-project1
```

with:

```yaml
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
```

The Role has the following RoleBinding:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-tenant-argocd-server
  namespace: demo-tenant-project1
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: demo-tenant-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-tenant-argocd-server
```

Afterwards I got no more 403 for this resource, which contained the following message:

```
error getting resource: replicasets.apps "azure-cli-bcbbf67f8" is forbidden: User "system:serviceaccount:demo-tenant-argocd:argocd-server" cannot get resource "replicasets" in API group "apps" in the namespace "demo-tenant-project1"
```

However, the actual issue is that ***even in the case of such a 403, there should be no such UI runtime error***.

Not sure why you don't get the UI runtime error.
Do you have the ClusterRole assigned to the proper service account via a ClusterRoleBinding?
