### ISSUE TITLE
Add cluster with access to limited resource in a single namespace

### ISSUE THREAD

**Issue by sdputurn** [argoproj/argo-cd#10941]
# Summary

we have a target external k8 cluster. where we have access to only one namespace "crd-only" and in that namespace we have access to serviceAccounts and some crd's.  we want to mange apps in this external cluster using argocd. we added this cluster with below command:
argocd cluster add  local-test-sa2 --service-account test-sa --namespace crf-only  --system-namespace  crd-only --project test.

Then created one app to mange some crd's in a gitOps way. but the app failed to sync. with below error:
ComparisonError
failed to sync cluster https://external-k8s-cluster.example.com: failed to load initial state of resource Service: services is forbidden: User "**system:serviceaccount:crd-only:test-sa**" cannot list resource "services" in API group "" in the namespace "crd-only"
a few seconds ago (Fri Oct 14 2022 14:52:55 GMT+0530)

# Motivation

we want to manage apps using argocd in a very controlled cluster where we have access to only few custom resources in a single namespace.
 

# Proposal

not sure about internal of argocd. however i would propose to have argocd only look for resources which are allowed in the target cluster.

thanks,
Sandeep

**Comment by jdmaguire** [comment]
Are you aware of `resource.inclusions` and `resource.exclusions`? https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml#L185

**Comment by micgruber** [comment]
Can you provide more information because I have the same problem tried the following for a cluster where I have just namespace access:

`argocd cluster add cluster --name staging --kubeconfig ~/.kube/cluster.yaml --system-namespace ns --namespace ls`

config map: argocd-cm

```yaml
data:
  admin.enabled: 'true'
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: 'false'
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - "*"
      clusters:
      - "*"
  resource.inclusions: |
    - apiGroups:
      - "*"
      kinds:
      - Deployment
      clusters:
      - "*"
  server.rbac.log.enforce.enable: 'false'
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
```

Error:

```shell
Failed to create Role "ns/argocd-manager-role": roles.rbac.authorization.k8s.io "argocd-manager-role" is forbidden: user "u-fmvzn7wldh" ... "system:authenticated" "system:cattle:authenticated"]) is attempting to 
grant RBAC permissions not currently held:
{APIGroups:["*"], Resources:["*"], Verbs:["*"]}
```
