### ISSUE TITLE
Disks disappear when updating to strimzi 0.30.0 (ArgoCD)

### ISSUE THREAD

**Issue by swamx** [argoproj/argo-cd#10974]
**Describe the bug**
Disks disappear when updating to strimzi 0.30.0

**To Reproduce**
Deploy 0.30.0 with the same values as 0.29.0

**Expected behavior**
I expected the disks to keep existing, even when kafka transitions to strimzipodsets.

Environment (please complete the following information):

Strimzi version: 0.20.0 to 0.30.0
Installation method: Helm chart (deployed with ArgoCD)
Kubernetes cluster: 1.21
Infrastructure: AWS AKS (aka EKS)
CRD API Version: v1beta2

**TEMP Solution**
We temporarily upgraded to 0.29.0 and it worked fine. There are only minor CRD upgrades and we did not have any major change

**YAML Code**
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    argocd.argoproj.io/instance: exampledev-dev3-kafka
    chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
  name: exampledev-dev3
  namespace: kafka
spec:
  cruiseControl:
    jvmOptions:
      -Xms: 450m
      -Xmx: 450m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: cruisecontrol-metrics-config.yml
          name: kafka-metrics
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
    template:
      cruiseControlContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
      tlsSidecarContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
  entityOperator:
    template:
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
      tlsSidecarContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      topicOperatorContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      userOperatorContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    topicOperator:
      jvmOptions:
        -Xms: 450m
        -Xmx: 450m
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
    userOperator:
      jvmOptions:
        -Xms: 450m
        -Xmx: 450m
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
  kafka:
    authorization:
      superUsers:
      - akhq
      type: simple
    config:
      log.retention.hours: 168
      offsets.topic.replication.factor: 2
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 2
    jvmOptions:
      -Xms: 700m
      -Xmx: 700m
    listeners:
    - authentication:
        type: scram-sha-512
      name: plain
      port: 9092
      tls: false
      type: internal
    - authentication:
        type: scram-sha-512
      name: tlsinternal
      port: 9094
      tls: true
      type: internal
    - authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          annotations:
            mcp.infosupport.com/private.dns: enabled
          host: kafka-bootstrap.internal.dev3.example.com
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: custom-external-broker-cert
        brokers:
        - annotations:
            mcp.infosupport.com/private.dns: enabled
          broker: 0
          host: kafka-broker-0.internal.dev3.example.com
        - annotations:
            mcp.infosupport.com/private.dns: enabled
          broker: 1
          host: kafka-broker-1.internal.dev3.example.com
        class: private-nginx
      name: external
      port: 9096
      tls: true
      type: ingress
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 2
    resources:
      requests:
        cpu: 350m
        memory: 1Gi
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 20Gi
        type: persistent-claim
    template:
      kafkaContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-kafka
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-kafka
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
    version: 3.2.0
  kafkaExporter:
    groupRegex: .*
    template:
      container:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
    topicRegex: .*
  zookeeper:
    jvmOptions:
      -Xms: 450m
      -Xmx: 450m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
    storage:
      class: default
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    template:
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-zookeeper
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-zookeeper
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
      zookeeperContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
```

**Logs**

```
csi-provisioner IDATETIME     1 controller.go:1099] Final error received, removing PVC PVCID from claims in progress                  
```

**Comment by jessesuen** [comment]
@swamx Did you mean to file this against https://github.com/strimzi/strimzi-kafka-operator? Otherwise, can you explain why you feel this is an Argo CD issue if your issue is resolved by upgrading to a different strimzi version?

**Comment by swamx** [comment]
@jessesuen The issue seems to occur only when we use Strimzi on ArgoCD. If we launch the cluster using kubectl and helm without ArgoCD it turns up fine. If we create the PVC's manually then also it works fine. 
For some reason when Argo creates the PVC it regards them as orphans and deletes them. 

If there was something wrong with the CRD or Strimzi operator the cluster would not turn up normally if we do not use ArgoCD. 
There is already an issue on the Strimzi Kafka operator- https://github.com/strimzi/strimzi-kafka-operator/issues/7093
They tried it with annotations but it seems like a workaround rather than a fix.

**Comment by bauerjs1** [comment]
To give some more context, Strimzi v0.30.0 or higher by default uses their own `StrimziPodSet` CR for managing pods because it gives more flexibility (such as individual configuration of pods in one set). This means that an update to v0.30.0 replaces StatefulSets (STS) by StrimziPodSets (SPS).

I am facing the same issue. Like @swamx mentioned, ArgoCD does not seem to understand where the PVCs come from or belong to and deletes them right away after they are created by the Strimzi operator. I suspect this has something to do with the missing `ownerReferences` field in the PVCs. However, in contrast, when the PVCs belong to a StatefulSet, they do not have an `ownerReference` either, but ArgoCD somehow understands where they are coming from.

**Comment by jadhavnitind** [comment]
I am also facing similar issue. My observation is with earlier version of Strimzi it was using `StatefulSets` which was starting pods in Argocd GUI under root application > my-cluster > StatefulSets > pods and pvc's.
But now with `StrimziPodSet` the `PVC's` are getting created under root application (my-cluster) in argocd that causes app to go  OutOfSync which in return terminates volumes.
If I set `syncPolicy` as `prune: false` then doesn't delete volumes but the app goes OutOfSync.

**Comment by bauerjs1** [comment]
You can also tell Strimzi to make the `Kafka` CR the owner of the PVCs. Strimzi doesn't do that by default, so that if the `Kafka` is (accidentally) deleted, the PVCs remain intact. However, if you enable this, ArgoCD can understand the ownership and knows where the PVCs belong to.

The option for this is
```yaml
kind: Kafka
spec:
  kafka:
    storage:
      deleteClaim: true
```
I think (not tested!) you can still prevent ArgoCD from pruning child resources of the `Kakfa` in case of App deletion by annotating it with `argocd.argoproj.io/sync-options: PrunePropagationPolicy=orphan` [(source)](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#resources-prune-deletion-propagation-policy).
