### ISSUE TITLE
ApplicationSet "Git Generator" does not work with Azure devops repos

### ISSUE THREAD

**Issue by muratakdeniz** [argoproj/argo-cd#11010]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Git Generator doesn't generate applications when azure devops repos are used. However it works with  "List Generator".   

**To Reproduce**

```yaml
## values-{{ .Values.env }}.yaml
config:
  appName: csi
  namespace: kube-config
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: https://dev.azure.com/XXX/XXXX/_git/my-gitops-repo
        revision: dev
        files:
          - path: "gitops/cluster-addons/*/values-{{ .Values.env }}.yaml"
  template:
    metadata:
      name: '{{ "{{config.appName}}" }}'
      namespace: argocd
      labels:
        team: "myteam"
    spec:
      project: default
      source:
        repoURL: https://dev.azure.com/XXX/XXX/_git/my-gitops-repo
        targetRevision: dev
        path: '{{ "{{path}}" }}'
        helm:
          valueFiles:
            - values.yaml 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{config.namespace}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

**Expected behavior**

Argocd applicationset controller should create apps based on given url and path

**Screenshots**
 

**Version**

```shell
{
    "Version": "v2.4.14+029be59",
    "BuildDate": "2022-10-05T17:15:37Z",
    "GitCommit": "029be590bfd5003d65ddabb4d4cb8a31bff29c18",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.7",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
No log could be found related to error
```
