### ISSUE TITLE
Unhelpful error message from simple app-of-apps misconfiguration

### ISSUE THREAD

**Issue by DavidR91** [argoproj/argo-cd#11021]
In ArgoCD `2.4.1.4+029be59`:

**Describe the bug**
If you create an app of apps where the root application targets a server other than in-cluster (i.e. so it tries to create the sub-application definition on the clusters where their _deployed content_ should be targeting) you can receive the error

`the server could not find the requested resource` 

Although the full pod log states what is missing, this is quite a confusing behaviour and in my opinion an easy mistake to make

```
message: 'the server could not find the requested resource'" application=esss kind=Application name=guestbook namespace=argocd phase=Sync syncId=00028-kefWD
```

**To Reproduce**
Create a top level application which deploys a sub application. But set the `cluster` of the top level application to be an actual target cluster rather than in-cluster, e.g.:

**Top Level**
```yaml
project: default
source:
  repoURL: 'example-redacted.git'
  path: helm/chart
  targetRevision: HEAD
  helm:
    parameters:
      - name: spec.server
        value: 'https://redacted-ip'
destination:
  server: 'https://redacted-ip'      <---- specify an actual cluster and not in-cluster
  namespace: argocd
```

**Sub application** (in this case part of a helm chart that just receives `spec.server` as a value)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.server }}
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

Although the top level will create and sync successfully, the create of the sub-application will fail with `the server could not find the requested resource` - I _assume_ because it's looking for the Application CRD in the targeted cluster rather than inside the Argo cluster where they actually reside

**Expected behavior**
At minimum I would expect a slightly more helpful error message (possible to supplement it with `expected to find definition <X> in cluster <Y>` etc.?)

**Version**

```shell
Pending
```

**Logs**

```
time="2022-10-21T09:49:58Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:00c0270c4364b616def655ff91be5e1e19d94af7,Prune:false,DryRun:false,SyncStrategy:&SyncStrategy{Apply:nil,Hook:&SyncStrategyHook{SyncStrategyApply:SyncStrategyApply{Force:false,},},},Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[],} {redacted false} [] {0 nil}}" application=esss
time="2022-10-21T09:49:58Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2022-10-21T09:49:58Z" level=info msg="Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions"
time="2022-10-21T09:49:58Z" level=info msg="Comparing app state (cluster: https://redacted, namespace: )" application=esss
time="2022-10-21T09:49:58Z" level=info msg="getRepoObjs stats" application=esss build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=10 unmarshal_ms=9 version_ms=0
time="2022-10-21T09:49:58Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2022-10-21T09:49:58Z" level=info msg="Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions"
time="2022-10-21T09:49:58Z" level=info msg=Syncing application=esss skipHooks=false started=false syncId=00028-kefWD
time="2022-10-21T09:49:58Z" level=info msg="Adding resource result, status: 'SyncFailed', phase: '', message: 'the server could not find the requested resource'" application=esss kind=Application name=guestbook namespace=argocd phase=Sync syncId=00028-kefWD
time="2022-10-21T09:49:58Z" level=info msg="Updating operation state. phase: Running -> Failed, message: '' -> 'one or more synchronization tasks are not valid'" application=esss syncId=00028-kefWD˚
```
