### ISSUE TITLE
AppSet with helm chart not overriding values

### ISSUE THREAD

**Issue by LelvProgrammer** [argoproj/argo-cd#11049]
I have an AppSet that synchronizes a repository that has a helm chart. Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappset
spec:
  generators:
    - git:
        repoURL: https://wtvr.com/repo
        revision: HEAD
        directories:
          - path: deploy/*/*
  template:
    metadata:
      name: '{{path[2]}}'
    spec:
      project: myproject
      source:
        repoURL: https://wtvr.com/repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: '{{path[1]}}'
        namespace: '{{path[2]}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true 
```

and the repository content that looks like this

```
deploy
└───clusterA
    └─── appA
        │   Chart.yaml
        │   values.yaml
```

and the content of the files are

Chart.yaml
```yaml
apiVersion: v2
name: helm-budgie
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: budgie
  version: 0.1.1
  repository: https://charts.ectobit.com
```

and values.yaml

```yaml
replicaCount: 2
```

With this configuration and with the app running, I only get one pod instead of two
![image](https://user-images.githubusercontent.com/96209272/197543039-3bb67880-eeab-403e-b9d1-e2dad7d44204.png)

though I can see my value override on the parameters tab of the application
![image](https://user-images.githubusercontent.com/96209272/197543236-4b551654-2501-4c29-8648-33a385f2cd31.png)

Even if I try to modify the settings manually on the UI (clicking on edit, and trying to alter either the values file or the parameters), as soon as I click save, the settings are restored to what was previously there (still, even if this did work, I would expect that this manual intervention would not be required, and it would pick the values appropriately). 

If I create the application directly (instead through the appset), I am able to modify the replicaCount through the parameters and these are reflected on the deployment
![image](https://user-images.githubusercontent.com/96209272/197544805-028bdf1f-54dd-4962-a711-526636f5e4cf.png)
![image](https://user-images.githubusercontent.com/96209272/197545107-2ed9a6aa-ea6c-463c-b9fd-93d736d4b278.png)

Am I doing something wrong or is there a bug? Although the second approach works, it goes against my needs. The use-case here is to have helm charts on a repository which can have overridden value files, and these can be picked up by an appset with the git generator. I am running ArgoCD v2.4.15+05acf7a

**Comment by stephaneetje** [comment]
Hello

You are not passing value file in your App, add this:

```
    spec:
      source:
        helm:
          parameters:
          valueFiles:
          - 'values.yaml'
```
