### ISSUE TITLE
Merge generator where a generator can reference items of another one

### ISSUE THREAD

**Issue by jpcosal** [argoproj/argo-cd#11054]
# Summary

Very much like what's been added for the Matrix generator https://github.com/argoproj/argo-cd/pull/9080, it would be nice to have the same for the Merge generator.
Something like

```
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - git:
              repoURL: https://github.com/my_org/my_repo.git
              revision: my_revision
              files:
                - path: path/*.yaml
          - git:
              repoURL: https://github.com/my_org/my_repo2.git
              revision: '{{sha}}'
              files:
                - path: path2/**/file.yaml
 ```
Notice the {{sha}} reference in the second generator.

cf original issue for merge generator https://github.com/argoproj/applicationset/issues/530

# Motivation

We have the following use case:
- Repo `my_repo` contains a collection of files corresponding to a list of services to deploy. File content is basically the sha/tag of the container image to use to deploy corresponding service
- Repo `my_repo2` contains the deployment resources/manifests of the services. We want to use the version corresponding to the sha/tag defined above. We need to extract some info from the repo to create the actual ArgoCD apps.

# Proposal

Some kind of code changes as what was done in https://github.com/argoproj/argo-cd/pull/9080
