### ISSUE TITLE
Issue with Dex after upgrade

### ISSUE THREAD

**Issue by krstosavic** [argoproj/argo-cd#11071]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are using ArgoCD on our Azure AKS clusters. Azure AD App Registration Auth using Dex is configured as described in documentation:
https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/#azure-ad-app-registration-auth-using-dex

    url: https://argocd.mydomain.com/
    dex.config: |
      connectors:
      - type: microsoft
        id: microsoft
        name:  Azure AD
        config:
          clientID: xxxxxxxxxxxxxxxxxxxxxxxxxxx
          clientSecret: $oidc.azure.clientSecret
          redirectURI: http://localhost:8080/api/dex/callback
          tenant: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          groups:
            - AKS-Cluster-Admin

And everything works correctly with dex server image version 2.30.2

However, after upgrading dex-server we cannot login with SSO. Following error message appears:

**"argocd failed to query provider "https://argocd.mydomain.com/api/dex": 404 not found: 404 page not found"**

When reverting back dex-server image to 2.30.2 everything works fine, no matter of argocd-server version.

We are now on ArgoCD version 2.4.15, using dex server 2.30.2.

**To Reproduce**

Upgrade Dex-server image to version newer to 2.30.2 and SSO will stop working.

**Expected behavior**

SSO to work with newer version of dex server

**Argocd Version**
{
    "Version": "v2.4.15+05acf7a",
    "BuildDate": "2022-10-17T20:32:39Z",
    "GitCommit": "05acf7a52e377eacfee29c68e3e5e",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.7",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}

**Comment by maartengo** [comment]
I also ran into this issue. You probably use the argo-cd helm chart to deploy your Argo, right? If so, chart version 3.7.0 changed the config settings. If you've previously disabled deployment of the argo configmap (argo-cm) then you might need to do so again through `configs.cm.create`

https://github.com/argoproj/argo-helm/pull/1528

**Comment by krstosavic** [comment]
> I also ran into this issue. You probably use the argo-cd helm chart to deploy your Argo, right? If so, chart version 3.7.0 changed the config settings. If you've previously disabled deployment of the argo configmap (argo-cm) then you might need to do so again through `configs.cm.create`
> 
> [argoproj/argo-helm#1528](https://github.com/argoproj/argo-helm/pull/1528)

Actually we are using yaml manifests, not helm chart.

**Comment by crenshaw-dev** [comment]
@krstosavic 404 is a really weird error for this.... are there any logs in the API server which might be helpful?

**Comment by krstosavic** [comment]
Nothing useful in logs.

We are using this url to get manifest file:
https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.15/manifests/install.yaml

Currently we have installed this version of ArgoCD. Of course we added dex.config in ConfigMap.

We are using this install approach a year and a half and everything worked, including SSO.

When we upgraded to version 2.3.7 we noticed that SSO stopped working with 404 error. But if you change dex-server version in manifest to 2.30.2 then it works.

So I am guessing this issue has something to do with dex image, but I don't know how to fix it.

**Comment by crenshaw-dev** [comment]
> When we upgraded to version 2.3.7

I'm a bit confused... the manifests you're using are for 2.4.15. What version are you upgrading from in order to get to 2.3.7?

**Comment by krstosavic** [comment]
We were on version 2.3.3 and tried to upgrade to latest 2.4.15. When we tried to do that SSO stopped working. We then reverted the changes and started troubleshooting.

So I did a bit of investigation to figure out what is causing this. Basically I started from version 2.3.3, started to upgrading one release at the time and tested functionalities.
2.3.4 - worked, 2.3.5 - worked, 2.3.6 - worked, 2.3.7 - stopped working.
In 2.3.7 release, dex image version changed, so then I know what caused the issue.

When in release 2.3.7 I changed just dex server version to 2.30.2 everything worked, that is how I verified my suspicions that dex server is causing this issue.

Then we just upgraded ArgoCD to 2.4.15 using old dex server 2.30.2 and that also worked.
So now we are on 2.4.15 argocd release with 2.30.2 dex server.

I hope this helps :)

**Comment by holgerson97** [comment]
I am facing the same issue using Helm with version 5.8.2
This is the configuration:

configs:
  cm:

    create: true
    url: https://xxxxx
    exec.enabled: "true"
  
    dex.config: |
      connectors:
      - type: saml
        id: saml
        name: saml
        config:
          entityIssuer: https://xxxxx/api/dex/callback
          ssoURL: https://login.microsoftonline.com/xxxxx/saml2
          caData: |
            base64 encoded cert
          redirectURI: https://xxxxx/api/dex/callback
          usernameAttr: email
          emailAttr: email
          groupsAttr: Group
          
I am getting the same error:

Failed to query provider "https://xxxxx//api/dex": 404 Not Found: 404 page not found

**Comment by holgerson97** [comment]
@crenshaw-dev 
```
Defaulted container "dex-server" out of: dex-server, copyutil (init)
time="2022-10-27T09:46:32Z" level=info msg="ArgoCD Dex Server is starting" built="2022-10-25T14:40:01Z" commit=b895da457791d56f01522796a8c3cd0f583d5d91 namespace=argocd version=v2.5.0+b895da4
time="2022-10-27T09:46:32Z" level=info msg="Generating self-signed TLS certificate for this session"
time="2022-10-27T09:46:32Z" level=info msg="Starting configmap/secret informers"
time="2022-10-27T09:46:32Z" level=info msg="Configmap/secret informer synced"
time="2022-10-27T09:46:32Z" level=info msg="0xc000f88ea0 subscribed to settings updates"
time="2022-10-27T09:46:32Z" level=info msg="Dex Version: v2.35.3-dirty, Go Version: go1.19.2, Go OS/ARCH: linux amd64"
time="2022-10-27T09:46:32Z" level=info msg="config issuer: https://argocd.mgt.roclub.io/api/dex"
time="2022-10-27T09:46:32Z" level=info msg="config storage: memory"
time="2022-10-27T09:46:32Z" level=info msg="config static client: Argo CD"
time="2022-10-27T09:46:32Z" level=info msg="config static client: Argo CD CLI"
time="2022-10-27T09:46:32Z" level=info msg="config connector: saml"
time="2022-10-27T09:46:32Z" level=info msg="config skipping approval screen"
time="2022-10-27T09:46:32Z" level=info msg="config refresh tokens rotation enabled: true"
time="2022-10-27T09:46:32Z" level=info msg="keys expired, rotating"
time="2022-10-27T09:46:32Z" level=info msg="keys rotated, next rotation: 2022-10-27 15:46:32.982206911 +0000 UTC"
time="2022-10-27T09:46:32Z" level=info msg="listening (telemetry) on 0.0.0.0:5558"
time="2022-10-27T09:46:32Z" level=info msg="listening (https) on 0.0.0.0:5556"
time="2022-10-27T09:46:32Z" level=info msg="listening (grpc) on 0.0.0.0:5557"
```

**Comment by crenshaw-dev** [comment]
The lack of errors seems to indicate that the API-server traffic is never making it to Dex. Is it possible the 404 is coming from your ingress? I'm just really surprised that the API server has no interesting logs.

**Comment by holgerson97** [comment]
When I query the api/dex/callback directly than I can connect to the DEX server and get unauthorised error. The API server does not say anything weird.

Is there anyway to check my ingress?

**Comment by krstosavic** [comment]
What is changed in Dex server images after version ghcr.io/dexidp/dex:v2.30.2 ?
Because if you change nothing else, just put that image everything works.

**Comment by lacion** [comment]
i just got exactly this problem after upgrading to the latest helm chart. After updating my values to the latest and configuring it via 

```
## Argo Configs
configs:
  cm:
    create: true
    application.instanceLabelKey: argocd.argoproj.io/instance
    server.rbac.log.enforce.enable: "false"
    exec.enabled: "true"
    admin.enabled: "false"
    timeout.reconciliation: 180s
    timeout.hard.reconciliation: "0"
    url: "https://xxx"
    # Dex configuration
    dex.config: |
      staticClients:
        - id: argo-workflows-sso
          name: Argo Workflow
          redirectURIs:
            - https://xxx/oauth2/callback
          secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: xxx
            clientSecret: xxx
            redirectURI: 'https://xxx/api/dex/callback'
            orgs:
              - name: xxxx
```

when i click on github sso it just redirects me to the argocd login view

this is what i see in the server logs

```
{"error":"rpc error: code = Unauthenticated desc = no session information","grpc.code":"Unauthenticated","grpc.method":"List","grpc.service":"cluster.ClusterService","grpc.start_time":"2022-10-28T19:40:03Z","grpc.time_ms":4.919,"level":"info","msg":"finished unary call with code Unauthenticated","span.kind":"server","system":"grpc","time":"2022-10-28T19:40:03Z"}
{"error":"rpc error: code = Unauthenticated desc = no session information","grpc.code":"Unauthenticated","grpc.method":"List","grpc.service":"application.ApplicationService","grpc.start_time":"2022-10-28T19:40:03Z","grpc.time_ms":5.107,"level":"info","msg":"finished unary call with code Unauthenticated","span.kind":"server","system":"grpc","time":"2022-10-28T19:40:03Z"}
```

on dex i see

```
time="2022-10-28T19:38:31Z" level=info msg="ArgoCD Dex Server is starting" built="2022-10-25T14:40:01Z" commit=b895da457791d56f01522796a8c3cd0f583d5d91 namespace=argocd version=v2.5.0+b895da4
time="2022-10-28T19:38:31Z" level=info msg="Generating self-signed TLS certificate for this session"
time="2022-10-28T19:38:32Z" level=info msg="Starting configmap/secret informers"
time="2022-10-28T19:38:32Z" level=info msg="Configmap/secret informer synced"
time="2022-10-28T19:38:32Z" level=info msg="0xc0001546c0 subscribed to settings updates"
time="2022-10-28T19:38:32Z" level=info msg="dex is not configured"
```

the CM is definitely there with dex config, not sure why this msg shows

**Comment by niqdev** [comment]
@krstosavic thanks for reporting this, I had the same 404 issues and I'm using `helm.sh/chart: argocd-5.8.7`. After downgrading to `v2.30.2` it started working again!

**Comment by holgerson97** [comment]
@niqdev Did you downgrade Dex or ArgoCD?

**Comment by lacion** [comment]
> i just got exactly this problem after upgrading to the latest helm chart. After updating my values to the latest and configuring it via
> 
> ```
> ## Argo Configs
> configs:
>   cm:
>     create: true
>     application.instanceLabelKey: argocd.argoproj.io/instance
>     server.rbac.log.enforce.enable: "false"
>     exec.enabled: "true"
>     admin.enabled: "false"
>     timeout.reconciliation: 180s
>     timeout.hard.reconciliation: "0"
>     url: "https://xxx"
>     # Dex configuration
>     dex.config: |
>       staticClients:
>         - id: argo-workflows-sso
>           name: Argo Workflow
>           redirectURIs:
>             - https://xxx/oauth2/callback
>           secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
>       connectors:
>         - type: github
>           id: github
>           name: GitHub
>           config:
>             clientID: xxx
>             clientSecret: xxx
>             redirectURI: 'https://xxx/api/dex/callback'
>             orgs:
>               - name: xxxx
> ```
> 
> when i click on github sso it just redirects me to the argocd login view
> 
> this is what i see in the server logs
> 
> ```
> {"error":"rpc error: code = Unauthenticated desc = no session information","grpc.code":"Unauthenticated","grpc.method":"List","grpc.service":"cluster.ClusterService","grpc.start_time":"2022-10-28T19:40:03Z","grpc.time_ms":4.919,"level":"info","msg":"finished unary call with code Unauthenticated","span.kind":"server","system":"grpc","time":"2022-10-28T19:40:03Z"}
> {"error":"rpc error: code = Unauthenticated desc = no session information","grpc.code":"Unauthenticated","grpc.method":"List","grpc.service":"application.ApplicationService","grpc.start_time":"2022-10-28T19:40:03Z","grpc.time_ms":5.107,"level":"info","msg":"finished unary call with code Unauthenticated","span.kind":"server","system":"grpc","time":"2022-10-28T19:40:03Z"}
> ```
> 
> on dex i see
> 
> ```
> time="2022-10-28T19:38:31Z" level=info msg="ArgoCD Dex Server is starting" built="2022-10-25T14:40:01Z" commit=b895da457791d56f01522796a8c3cd0f583d5d91 namespace=argocd version=v2.5.0+b895da4
> time="2022-10-28T19:38:31Z" level=info msg="Generating self-signed TLS certificate for this session"
> time="2022-10-28T19:38:32Z" level=info msg="Starting configmap/secret informers"
> time="2022-10-28T19:38:32Z" level=info msg="Configmap/secret informer synced"
> time="2022-10-28T19:38:32Z" level=info msg="0xc0001546c0 subscribed to settings updates"
> time="2022-10-28T19:38:32Z" level=info msg="dex is not configured"
> ```
> 
> the CM is definitely there with dex config, not sure why this msg shows

My "fix" for this issue may not be for everyone, but basically, what i did was to add this

`dexserver.disable.tls: true` to the dex config. I'm running everything in Istio, so I'm using mutual mtls and this is not a huge change for me, but with istio i could not make it work without disabling that.

**Comment by niqdev** [comment]
> @niqdev Did you downgrade Dex or ArgoCD?

@holgerson97 only dex, but I'm using ambassador with self-signed certs as of now
```yaml
dex:
  image:
    tag: v2.30.2
```

**Comment by holgerson97** [comment]
@niqdev thank you very much!

**Comment by crenshaw-dev** [comment]
I'd strongly caution against downgrading. 2.30.2 has a [critical vulnerability](https://github.com/dexidp/dex/security/advisories/GHSA-vh7g-p26c-j2cw) which is relevant to Argo CD, given the way we use Dex.

I'm reading through release notes trying to figure out what might be the difference.

Does anyone have time to binary-search the Dex releases?

**Comment by niqdev** [comment]
As mentioned above, I was using a self-signed cert with tls enabled, and it's still not working. From what I found below, it must be a combination of argo/dex tls and self-signed certs. Setting `oidc.tls.insecure.skip.verify: true`, `--disable-tls` and `dexserver.disable.tls: true` wasn't enough for me - I'll give an update if I found a solution.

In the meantime, thanks @crenshaw-dev for mentioning the vuln. After comparing different releases I found a way to make it work with a valid certificate using `argo-helm: 5.12.1` and no dex downgrade. These are the main changes in my specific case, I hope they might help somebody else

```yaml
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
spec:
  acme:
    # PROD instead of "https://acme-staging-v02.api.letsencrypt.org/directory"
    server: "https://acme-v02.api.letsencrypt.org/directory"

---
apiVersion: cert-manager.io/v1
kind: Certificate
  dnsNames:
  - "{{ .Values.domain }}"
  - "*.{{ .Values.domain }}"
  # it used to work without before!
  # solved x509: certificate is valid for *.example.com, example.com, not argocd.example.com"
  - "argocd.{{ .Values.domain }}"

configs:
  cm:
    # make sure you are setting    
    url: "https://argocd.example.com"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-github-sso-secret:dex.github.clientID
            clientSecret: $argocd-github-sso-secret:dex.github.clientSecret
            orgs:
            - name: ORG
              teams:
              - TEAM
```

**Comment by krstosavic** [comment]
Solution @niqdev proposed does not work in our environment.
Our ClusterIssuer is configured:

`apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: k.savic@domain.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        azureDNS:
          subscriptionID: {{ .Values.azureDNS.subscriptionID }}
          resourceGroupName: {{ .Values.azureDNS.resourceGroupName }}
          hostedZoneName: "domain.com"
          environment: AzurePublicCloud`

And ingress:
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: management-nginx
  rules:
    - host: argocd.domain.com
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 443
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - argocd.domain.com
      secretName: argocd-secret`

So Lets Encrypt is issuing to us certificates with"argocd.domain.com" Common Name.
But still Dex service is not working with newest version of image.

**Comment by holgerson97** [comment]
I was just able to fix the issue for me. The fix was to provide the secret which holds my TLS certificate used for ArgoCD ingress was'nt populated with the fullchain. After adding the fullchain everything worked like a charm. @krstosavic

**Comment by miroslav-staffa** [comment]
Same issue here, downgrade of dex server helped.
Our  configuration is similar to everyone else's
`apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  
---
  
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: https://xxxxx/
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: saml
      name: saml
      config:
        entityIssuer: https://xxxxx/api/dex/callback
        ssoURL: https://yyyyy
        caData: base64Cert
        redirectURI: https://xxxxx/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: Group`

**Comment by danhawkins** [comment]
I found I had to set this in:
```
configs:
  params:
    dexserver.disable.tls: true
```

In latest helm chart, there is a separate config map that the dex chart references here

```
          - name: ARGOCD_DEX_SERVER_DISABLE_TLS
            valueFrom:
              configMapKeyRef:
                name: argocd-cmd-params-cm
                key: dexserver.disable.tls
                optional: true
```
