### ISSUE TITLE
Jsonnet Applications External Variables and/or TLA

### ISSUE THREAD

**Issue by entone** [argoproj/argo-cd#1107]
I read the great article from one of the Argo devs, https://blog.argoproj.io/the-state-of-kubernetes-configuration-management-d8b06c1205 and couldn't agree more with the power and flexibility that comes with Jsonnet.

I believe with a few small tweaks we could make Jsonnet application support within ArgoCD much more robust.

By providing namespace and cluster name to the Jsonnet compilation phase it would allow me to use pure jsonnet in place of Helm charts.

I believe setting the extVars and/or TLA for namespace and cluster name here https://github.com/argoproj/argo-cd/blob/711e271583c563eacda33a2656add848d9c3cfde/reposerver/repository/repository.go#L461 would provide enough information for me to fully replicate my current Helm charts.

In addition you can set TLACode or ExtCode, this could be an interesting place to do something similar to the values.yaml overrides that Helm provides. Or just run/provide arbitrary objects per cluster and/or namespace.

Although ExtVars don't provide as much encapsulation as TLA, I believe requiring your `main` function to accept certain TLA's may create to much reliance on Argo and perhaps unnecessary coupling, but perhaps not.

The relevant methods for the jsonnet-go VM.

https://github.com/google/go-jsonnet/blob/493c45a403d25435774370ddfa6363906a65c23c/vm.go#L67

https://jsonnet.org/learning/tutorial.html

**Comment by entone** [comment]
In addition to namespace and cluster name, some sort of convention around overriding the image.tag would be pretty awesome as well.

**Comment by jessesuen** [comment]
Related: https://github.com/argoproj/argo-cd/issues/1082

**Comment by edlee2121** [comment]
I'm thinking TLA map:
E.g. --tla-code 'env={ "cluster":"mycluster", "namespace":"mynamespace"}'

**Comment by entone** [comment]
I like that.

**Comment by PaulRudin** [comment]
people might already have jsonnet that uses std.extVar, so using this without changes is easier if there's a mechanism for setting external variables. tlas provide nicer encapsulation, but if only these are provided it's harder to using existing code bases unmodified (there's no way to set an extvar within the jsonnet code). Doing it the other way round is easier - if you've already got code that expects tlas, it's simple to write an interface that reads extvars and passes them through to your existing top level function.

If there you're going to pass things like namespace always, then maybe it's a good idea to name these in a way that's unlikely to clash with existing extvar use in people's code... something like '__argocd/namespace'. Or maybe (additionally?)  pass an exvar that's actually object with all the relevant state - e.g. __argocd_config as the name, with a value {namespace: 'foo', argocd_version: '...', git_commit_sha: '....', parameter_overrides: {...}, ...}

**Comment by jessesuen** [comment]
Here is current spec proposal, but not married to this:

```yaml
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    jsonnet:

      ext:
      # equivalent to: jsonnet --ext-str foo=bar
      - name: foo
        value: bar

      # equivalent to: jsonnet --ext-code fooObj=bar
      - name: fooObj
        value: "true"
        code: true

      tla:
      # equivalent to: jsonnet --tla-str foo=bar
      - name: foo
        value: bar

      # equivalent to: jsonnet --tla-code fooObj=bar
      - name: fooObj
        value: "true"
        code: true
```

Having some more discussions internally how the spec should look.

**Comment by alexec** [comment]
@PaulRudin and @entone  - I'm now working on this issue. Can I please ask you to take a look at @jessesuen suggestion and comment?

**Comment by entone** [comment]
So is the idea to allow for parameter setting through the CLI/UI? I wouldn't hate it if a few defaults, namespace, project etc. are passed in by default.

I also don't mind that we duplicate the vars as TLA and Ext. Seems reasonable and provides the most flexibility.

So yes, :+1:

**Comment by edlee2121** [comment]
How about:
```
ext-str:
      # equivalent to: jsonnet --ext-str foo=bar
      - name: foo
        value: bar

ext-code:
      # equivalent to: jsonnet --ext-code fooObj={p1=xxx,p2=yyy}
      - name: fooObj
        value:
          p1: xxx
          p2: yyy

tla-str:
      # equivalent to: jsonnet --tla-str foo=bar
      - name: foo
        value: bar

tla-code:
      # equivalent to: jsonnet --tla-code fooObj={p1=xxx,p2=yyy}
      - name: fooObj
        value:
          p1: xxx
          p2: yyy
```

**Comment by entone** [comment]
I believe @edlee2121 is correct, the *-code arguments are meant to pass in complex data, objects, while the *-str is meant for simple boolean/string/number values.

**Comment by alexec** [comment]
From the source code:

```
// isCode determines whether it should be evaluated as jsonnet code or
	// treated as string.
```

I'd therefore consider `-p ext-str foo` as a convenience for -p ext-code '"foo"'.

**Comment by alexec** [comment]
This is the format implemented:
```
destination:
  namespace: default
  server: https://localhost:6443
project: default
source:
  directory:
    jsonnet:
      extVars:
      - code: true
        key: foo
        val: '"true"'
      - key: name
        val: foo
      tlas:
      - key: name
        val: the name
  path: jsonnet-guestbook
  repoURL: https://github.com/alexec/argocd-example-apps/
  targetRevision: HEAD
```

**Comment by edlee2121** [comment]
Perhaps if the value field is a structure rather than a simple string, we could encode it as a json string for the user so that they can benefit from syntax checking the yaml.

**Comment by alexec** [comment]
@PaulRudin and @entone, @edlee2121 has suggested that code could be JSON object, as opposed to an evaluated string. I think this looks more elegant, but I think it might be less powerful. What do you think?

**Comment by edlee2121** [comment]
I didn't mean instead of but in addition to. I think we want users to be able to specify arbitrary jsonnet code as well.

**Comment by alexec** [comment]
@jessesuen - I believe that @edlee2121 means some equivilant to this:

```yaml
tlas:
      - key: fooObj
        val: '{"p1": "xxx", "p2": "yyy"}'
        code: true
```

This is something that works with the current implementation.

**Comment by edlee2121** [comment]
Yes, except it would be useful to type this as:
```
tlas:
      - key: fooObj
        val:  
           p1: "xxx"
           p2: "yyy"
        code: true
```
