### ISSUE TITLE
Chart.yaml: no such file or directory

### ISSUE THREAD

**Issue by kahirokunn** [argoproj/argo-cd#11072]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I got this error.

> rpc error: code = Unknown desc = Manifest generation error (cached): open /tmp/00dcd81e-152f-4a7c-aafb-a620c98592ed/infinispan-infinispan/Chart.yaml: no such file or directory

this is yaml.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infinispan
spec:
  project: default
  destination:
    name: in-cluster
    namespace: infinispan
  source:
    repoURL: https://charts.openshift.io/
    targetRevision: 0.2.2
    chart: infinispan-infinispan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

I checked the operation with the following command.

```
$ helm pull infinispan/infinispan-infinispan
$ tar -zxvf infinispan-infinispan-0.2.2.tgz
x infinispan/Chart.yaml
x infinispan/values.yaml
x infinispan/values.schema.json
x infinispan/templates/_log4j2.xml.tpl
x infinispan/templates/configmap.yaml
x infinispan/templates/helpers.tpl
x infinispan/templates/metrics-service.yaml
x infinispan/templates/ping-service.yaml
x infinispan/templates/route.yaml
x infinispan/templates/secret.yaml
x infinispan/templates/service-monitor.yaml
x infinispan/templates/service.yaml
x infinispan/templates/statefulset.yaml
x infinispan/templates/tests/test-connection.yaml
x infinispan/.helmignore
x infinispan/LICENSE
x infinispan/README.md
```

The `infinispan` directory is created instead of `infinispan-infinispan`.
However, the error message seems to indicate that ArgoCD is mistakenly thinking that it is `infinispan-infinispan`.
What should I do?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by MarcusDunn** [comment]
if anyone is running into this issue trying to run infinispan on argocd, the following configuration worked:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infinispan
  namespace: argocd
spec:
  project: default
  source:
    chart: infinispan
    repoURL: https://charts.openshift.io
    targetRevision: 0.4.1
    helm:
      valuesObject:
        deploy:
          replicas: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
```
