### ISSUE TITLE
Argocd-2.5 Can't template AppSet  because of new regexp validation on annotations

### ISSUE THREAD

**Issue by stephaneetje** [argoproj/argo-cd#11076]
since argocd 2.5, i have a problem with appset validations (that was ok before this version)
It fails on the regexp validation on all my annotations with some helm templating , for ex:

```
argocd-image-updater.argoproj.io/pr{{number}}.allow-tags': 'regexp:^pr-{{number}}.*$
```

On the ApplicationSet controller i have this error :
```
 metadata.annotations: Invalid value: "argocd-image-updater.argoproj.io/pr{{number}}.allow-tags": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]
```

Here is the part of my applicationSet.yaml :
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-app
spec:
  generators:
  - pullRequest:
      github:
        owner: Stephan
        repo: app
        labels:
        - preview
        tokenRef:
          secretName: argocd-githubtoken
          key: token
      requeueAfterSeconds: 300
  template:
    metadata:
      name: 'preview-pr{{ `{{number}}` }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .:../../helm/app
        argocd-image-updater.argoproj.io/image-list: 'pr{{`{{number}}`}}=gcr.io/infra/app'
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-repo-creds-ssh-creds
        argocd-image-updater.argoproj.io/pr{{`{{number}}`}}.update-strategy: latest
        argocd-image-updater.argoproj.io/pr{{`{{number}}`}}.allow-tags: 'regexp:^pr-{{ `{{number}}` }}.*$'
```
Then the interpreted ApplicationSet's annotation must be :
```
        argocd-image-updater.argoproj.io/pr{{number}}.update-strategy: latest
        argocd-image-updater.argoproj.io/pr{{number}}allow-tags: 'regexp:^pr-{{number}}.*$'
```
Which will create the Application with templated values in the annotation:
```
        argocd-image-updater.argoproj.io/pr1110.update-strategy: latest
        argocd-image-updater.argoproj.io/pr1110allow-tags: 'regexp:^pr-1110.*$'
```

It should not be regex validated in the AppSet as there can be helm interpretation needed.
I have the same problem on all my AppSets with dynamic annotations, with or without PR generator.

That was working on previous versions of argo-cd (i rolled back the time it gets fixed)
