### ISSUE TITLE
ArgoCD 2.5 - Redis Networkpolicy - Egress config blocks Istio communication

### ISSUE THREAD

**Issue by Starslider** [argoproj/argo-cd#11086]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have integrated ArgoCD into [Istio ](https://istio.io/)- so every pod gets an envoy proxy to communicate within the service mesh.
With the newly introduced egress configuration in #10226 argo added an egress specification that only port 53 is allowed for the redis pod. With that config, the envoy proxy cannot communicate to the istiod and will not get ready / is not able to start properbly. The redis pod will end up with an FailedPostStartHook / Crashloop error.

**To Reproduce**

- Install ArgoCD 2.5.0
- Enable Istio on your ArgoCD namespace
- Restart all ArgoCD pods
- Redis will not start
- Delete egress config in argocd-redis-network-policy
- Redis will start without egress config

I tried to fix it yesterday and added some[ istio ports](https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio) like 15012 / 15014 / 15017 / 15021 / 15001 / 15053 to the Networkpolicy egress config but I did not work out for me. In general within the service mesh we decided to get rid of all egress config in network policies. I am struggeling right now if that is ideal for ArgoCD endusers or we should provide something here. Did I add the wrong ports / or do I have to add the istio-system namespace to the selector? If we could fix that, I would like to provide a documentation if someone wants to run ArgoCD within the service mesh.

**Expected behavior**

The Redis pod can sucessfully start with an envoy proxy sidecar and can communicate to Istiod

**Version**

```shell
ArgoCD 2.5.0
```

**Logs**

```
Exec lifecycle hook ([pilot-agent wait]) for Container "istio-proxy" in Pod "argocd-redis-5494c7c4df-f88dj_helix-argocd(90df56ba-11fb-46cd-8d0b-6c8449dcf2e0)" failed - error: command 'pilot-agent wait' exited with 255: Error: timeout waiting for Envoy proxy to become ready. Last error: Get "http://localhost:15021/healthz/ready": dial tcp 127.0.0.1:15021: connect: connection refused , message: "2022-10-26T11:42:56.284795Z\tinfo\tWaiting for Envoy proxy to be ready (timeout: 60 seconds)...\n2022-10-26T11:43:56.413224Z\terror\ttimeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp 127.0.0.1:15021: connect: connection refused\nError: timeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp 127.0.0.1:15021: connect: connection refused\n"
```

**Comment by rodrigo14miguel** [comment]
Hi,
**_This is just a workaround for the issue._**
Using argocd v2.5.0 HA with istio sidecar proxy.
I bumped into this yesterday. I simply reverted redis and haproxy network policies to that is declared in argocd 2.4.15 HA manifests. As stated, this removes egress config and I think it removes some ports in the ingress section too, compared to v2.5.0.

**Comment by crenshaw-dev** [comment]
I think I'd be in favor of shipping the NetworkPolicy open enough to allow Istio traffic, since that's a very common use case. Unfortunately, I don't know Istio well enough to be any help finding the right policy. Can someone comment if you have some ideas how the NetworkPolicy should be modified?

**Comment by Starslider** [comment]
@crenshaw-dev I will work on it tomorrow, should be possible in my opinion.

**Comment by Starslider** [comment]
Ok I did some testing and it seems to be only port 15012 for istio that we need to add to the egress config to get redis running.

I am stilll wondering if should remove the egress config at all. Imho the approach from #10226 is too error prone for many users. There are other service mesh products which we should also cover like Linkerd or Consul. Another point is that something could change in Istio and we would have to rework the network policies. If we decide to add this, does it makes sense to do this only for Redis or should not every pod get a clean egress config? 

My working NetworkPolicy with Istio:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-redis-network-policy
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        - port: 15012
          protocol: TCP
      to:
        - namespaceSelector: {}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-repo-server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-application-controller
      ports:
        - port: 6379
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  policyTypes:
    - Ingress
    - Egress
```

@crenshaw-dev
