### ISSUE TITLE
Allow setting application namespace from ApplicationSet template

### ISSUE THREAD

**Issue by waaghals** [argoproj/argo-cd#11104]
# Summary

With the introduction of namespaced applications in #9755 we can have applications in different namespaces.
But the applications generated from an ApplicationSet always use the namespace from the ApplicationSet.

ApplicationSet should allow setting `.spec.template.metadata.namespace` for the generated application.

# Motivation

When deploying the same repository/directory to multiple clusters, one could use ApplicationSets to automatically generate applications for each cluster.
The names of these applications can become rather large as they might include both the application name and cluster name.

For organization purposes it might make sense to put all these argo-cd applications for the same repositry/directory into a single namespace.

Lets imagine the following directory structure:

- /cluster-1/cert-manager
- /cluster-1/external-dns
- /cluster-2/cert-manager
- /cluster-2/external-dns
- /cluster-3/cert-manager
- /cluster-3/external-dns

With the following ApplicationSet
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: ...
      revision: main
      directories:
      - path: **/*
  template:
    metadata:
      name: '{{path[0]}}'
      namespace: '{{path[1]}}' # this is currently not used, it always uses namespace of set
    spec:
      project: default
      source:
        repoURL: ...
        targetRevision: main
        path: '{{path}}'
      destination:
        name: '{{path[0]}}'
        namespace: '{{path[1]}}'
```

Which I would expect to generate applications like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-1
  namespace: cert-manager
spec:
  project: default
  source:
    repoURL: ...
    targetRevision: main
    path: ...
  destination:
    name: cluster-1
    namespace: cert-manager
```

# Proposal

When `.spec.template.metadata.namespace` is set on the ApplicationSet, use that, otherwise fallback to the ApplicationSet's namespace.
