### ISSUE TITLE
Proposal: Add support for arbitrary application tiles

### ISSUE THREAD

**Issue by carsonoid** [argoproj/argo-cd#11128]
# Summary

Add support for customized tiles in an application via a CRD

# Motivation

In may case, the Argo application is the jumping off point for a service. It would be nice to make it easy to add more context and data on the page without having to tie it to a Kubernetes resource.

# Proposal

Right now individual resources have the ability to generate links in an Application dashboard via annotations.

However, there are often links that aren't specifically related to dashboards and rather just belong to the app itself. Things like monitoring dashboards or documentation.

It would be really nice to be able to provide these kinds of links and extra data on a dashboard via CRD. The CRDs here effectively act as a simple data source for the UI.

I think it would make sense for these extra tiles to show up above or below the main "app" tile.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDInterfaceTile
metadata:
  name: my-svc-dashboard
spec:
  link:
    text: Grafana Dashboard
    url: http://my-grafana.com/pre-generated-link
    color: light-red
    text-color: black
    # image would be optional
    image:
      source:
        # emojiName is mutually exclusive with url. You should be able to give it a text
        # name for an emoji and the dashboard will attempt to render it, but render nothing if it doesn't
        # match a known emoji name
        # another option might be to use something like fontawesome to provide this kind of imaging
        emojiName: heavy_exclamation_mark

        # url is mutually exclusive with emojiName. It is the full url
        # to the the image source and will be hot-linked
        # url: http://my-image-source.com/images/dashboard.png
```

Low effort mock-up:

![Selection_734](https://user-images.githubusercontent.com/2973513/199039170-3d0084a4-5f4a-4aec-861a-4f4a9a02bbb6.png)
