### ISSUE TITLE
bug: Application's own external URLs are not shown in the UI

### ISSUE THREAD

**Issue by alexef** [argoproj/argo-cd#11123]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The `link.argocd.argoproj.io/` annotation prefix can be used on Application resources as well, in order to generate an external link button in the UI.

This works for the `link.argocd.argoproj.io/external-link` annotation (which has a special case in the UI), but doesn't work for any other annotation.

**To Reproduce**

Create an application with a link annotation, i.e.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    link.argocd.argoproj.io/drone: https://example.com
```

Observe that the link doesn't show up.

**Expected behavior**

I expect the link to show up on Application List view and on Application Details page (under the Root node), the same as it does for the `link.argocd.argoproj.io/external-link: https://another.example.com` case.

**Screenshots**

<img width="363" alt="Screenshot 2022-10-31 at 12 43 20" src="https://user-images.githubusercontent.com/346576/199000215-0ca8b8b1-2154-4876-95c3-da9a07f0630a.png">

**Version**

latest

**Logs**
