### ISSUE TITLE
Rework how Dex server is managed.

### ISSUE THREAD

**Issue by pdrastil** [argoproj/argo-cd#11132]
# Summary

Dex server is currently managed via custom made utility that overcomplicates things and locks users from more flexible setups / using HA deployments.

# Motivation

- As a cluster operator I need to have integration with LDAP but I also need to run in HA setups
- As a cluster operator I want to use Dex probes for liveness / readiness checks
- As a cluster operator I want to be able to customize Dex config via regular config maps

# Proposal

Dex uses extra init container to inject utility that replaces Dex process with it's own and just watches for changes in `argocd-cm` in `url` and `dex.config` keys. Reason for this injection of static clients with Argo CD callbacks.

- Callbacks for Argo CD and other user defined clients could be configured dynamically via Dex gRPC API - https://dexidp.io/docs/api/
- Basic configs for ports / internal dex configuration should be available via regular configmap that can be replaced / patched
- Dex is valid OIDC server with .well-known issuer address - `oidc.config` could be used to configure connection for Argo CD -> Dex component
- If extra tool is needed it should be just configmap / secret watcher that restarts Dex pod on change - this would be also helpful for managing TLS certificates issued by cert-manager and stored in `argocd-dex-tls` secret

Dex nowadays supports Go templates so functionality like http / https switch is doable with:
```yaml
{{- if getenv "DEX_WEB_HTTPS" "" }}
  https: {{ .Env.DEX_WEB_HTTPS }}
  tlsKey: {{ getenv "DEX_WEB_TLS_KEY" | required "$DEX_WEB_TLS_KEY in case of web.https is enabled" }}
  tlsCert: {{ getenv "DEX_WEB_TLS_CERT" | required "$DEX_WEB_TLS_CERT in case of web.https is enabled" }}
{{- end }}
  http: {{ getenv "DEX_WEB_HTTP" "0.0.0.0:5556" }}
```
