### ISSUE TITLE
Retrieve CRD schemas from the Server so default values can be considered during SSA diff calculation

### ISSUE THREAD

**Issue by leoluz** [argoproj/argo-cd#11139]
# Summary

When ServerSideApply is enabled, the new diff logic is currently unable to consider CRD default values. Argo CD should be able to retrieve CRD schemas from Kubernetes server and add to the controller cache so default values can be considered during SSA diff calculation.

# Motivation

Currently Argo CD is unable to consider CRD default values while calculating diffs when SSA is enabled. This makes it display the Application as out-of-sync when in fact there is no diff between the desired and live states.

# Proposal

We currently cache the GVKParser but this object doesn't have the ability to apply default values. We need to investigate and find a way to apply default values during diff calculation.

**Comment by rouke-broersma** [comment]
This feature is a must have  to consider using server side apply because most CRDs will have some default values and applying ignoreDifferences to all applications for CRD default values is an immense task.

**Comment by leoluz** [comment]
@rouke-broersma Clarifying things. The current limitation just applies for CRDs that define default values at the schema level. 

In `openAPIV3Schema` the CRD can define property's default value like in the example below:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
...
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          someProperty:
            type: string
            default: some-default-value
```

This is the case that will cause problems in the diff logic for SSA. 

However, controllers can still define and consider internal default values (only applied in runtime) and in this case there won't be any diff issues in Argo CD. Not every CRD will have default values at the schema level. Argo CD CRDs for example don't define any.
