### ISSUE TITLE
Allow advanced templating in ApplicationSet

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11164]
People want to be able to do advanced things in ApplicationSet templates.

One way to accomplish this is to provide a plain ol' string field for the template instead of an Application spec. But then you lose nice IDE support.

Another way, which I think would require fewer changes, is to allow templating _keys_ instead of just values in the Application spec.

Something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - automated: "true"
      - automated: "false"
  template:
    spec:
      syncPolicy:
        "{{ ternary "automated" "turtles" (eq .automated "true") }}": {}
```

When `automated` is not `"true"`, the key nested under `syncPolicy` evaluates to `turtles`. Since that's not part of the Application spec, it'll be dropped when the Application is unmarshaled. 

Similar strategies could be applied to toggle, for example, fields under `source`. That would allow a git files generator to generate applications both for Helm and Kustomize.

**Changes required:**

First, we'd have to change the ApplicationSet CRD to preserve unknown fields. `"{{ ternary "automated" "turtles" (eq .automated "true") }}"` would otherwise be rejected as an invalid key (or, if validation is disabled, dropped).

Second, we'd have to change the ApplicationSet controller to handle the ApplicationSpec as an unstructured until the very last moment, when _all_ templating has been applied. If we unmarshal to an Application spec before then, we'll lose the templated key.

Inspiration for this strange idea comes from fixing this bug, when I realized we can template keys: https://github.com/argoproj/argo-cd/pull/11163

**Comment by crenshaw-dev** [comment]
cc @speedfl because I think you'll find this entertaining.  :-)

**Comment by speedfl** [comment]
Hi @crenshaw-dev 

Thank you for the notification.
Not sure I will have time to work on this one :-(

But definitely a great idea.

**Comment by cjc7373** [comment]
I have read the use cases listed in https://github.com/argoproj/argo-cd/pull/12843, I was wondering if these use cases can be achieved in another way, like a [JSON6902](https://kubectl.docs.kubernetes.io/references/kustomize/glossary#patchjson6902) patch in kustomization. In this way, we would achieve the same thing by having a new generator called Patch Generator, and it works in a way like the merge generator.

To illustrate that, let's see the use cases in #12843
Use case 1:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - patch:
      matchKey: cluster  # use this key to match an item in list generator
      baseGenerator:
        list:
          elements:
          - cluster: engineering-dev
            url: https://kubernetes.default.svc
          - cluster: engineering-prod
            url: https://kubernetes.default.svc
      patch:
      - key: engineering-dev
        action:
        - op: add
          path: /spec/source
          value: |
            helm:
              parameters:
                - some-param 
      - key: engineering-prod
        action:
        - op: add
          path: /spec/source
          value: |
            kustomize:
              images:
                - some=image
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: "{{.sourceType}}"
      destination:
        server: '{{.url}}'
        namespace: guestbook
```
Use case 2 is just like the use case 1. 

In use case 3:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - patch:
      matchKey: cluster
      baseGenerator:
        list:
          elements:
          # ...
      patch:
      - key: engineering-dev
        action:
        - op: replace
          path: /spec/syncPolicy/automated/prune
          value: true
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: "{{.sourceType}}"
      destination:
        server: '{{.url}}'
        namespace: guestbook
      syncPolicy:
        automated:
          prune: false
```

What do you think of this idea? Does it look possible?

**Comment by speedfl** [comment]
This is a really good idea. Could we put patch outside generators ?

It would allow to first generate all applications, then apply patches.

Like:

```yaml
spec:
  generators:
    - list:
  patch:
    -  key: engineering-dev
       action: ...
```

**Comment by jwenz723** [comment]
It would be nice if the ApplicationSet template could be templated in a way similar to what helm allows. For example the example in the initial post in this issue could look like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - automated: "true"
      - automated: "false"
  template:
    spec:
      syncPolicy:
        {{ toYaml .automated }}
```

It would be nice to allow more advanced features like control statements like an `if` or `range`.

Allowing this advanced templating might not be easily done with the current ApplicationSet spec. It might be better to add a separate attribute like `spec.templatedTemplate` that allows this. This way the entire `spec.templatedTemplate` object could be templated. I would probably prefer the key name to be `spec.goTemplate`, but that is already being used. I think this field would have to be a string type.

For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - syncPolicy:
          automated: "true"
      - helmValues :
          one: "1"
          two: "2"
  templatedTemplate: |
    spec:
      {{- if .helmValues }}
      helm:
        values: |
          {{- range $key, $value := .helmValues }}
          {{ $key }}: {{ $value }}
          {{- end }}
      {{- end }}
      {{- if .syncPolicy }}
        {{ toYaml .syncPolicy | nindent 6}}
      {{- end }}
```
