### ISSUE TITLE
[UI] Some componentParameterOverrides don't get rendered

### ISSUE THREAD

**Issue by fabriziofortino** [argoproj/argo-cd#1116]
I have an application with some overrides that look like this

```
componentParameterOverrides:
      - name: image.tag
        value: "ecd711c"
      - name: env.SOME_ENV_VAR
        value: "some-value"
      - name: service.annotations.external-dns\.alpha\.kubernetes\.io/hostname
        value: "hostname-value"
```

When I access the application from the UI the number of overrides looks correct: `3 parameter override(s)`. When I drill down in the `PARAMETERS` section only the `image.tag` override is shown

<img width="1030" alt="screenshot 2019-02-13 at 11 21 59" src="https://user-images.githubusercontent.com/1469849/52708311-c3932d80-2f81-11e9-896c-f1f3830e9dd5.png">

I think this is just a problem in the UI since the application works fine and all the parameters overrides are correctly applied.
