### ISSUE TITLE
[helm + kustomize]Wrong evalutation of kubeVersion 

### ISSUE THREAD

**Issue by Brice187** [argoproj/argo-cd#11179]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD wrongly evaluates the kubernetes Version of the target cluster, so that helm charts with version constraints can not be deployed (see logoutput at the bottom of this issue)

Environment:
```
root@d11:~# k3s -v
k3s version v1.24.7+k3s1 (7af5b167)
go version go1.18.7
```

```
root@d11:~# kubectl get nodes
NAME   STATUS   ROLES                       AGE    VERSION
d11    Ready    control-plane,etcd,master   344d   v1.24.7+k3s1
d12    Ready    control-plane,etcd,master   327d   v1.24.7+k3s1
d13    Ready    control-plane,etcd,master   497d   v1.24.7+k3s1
```

* Using ArgoCD v2.5.1 with kustomize plugin to install longhorn 1.3.2 helmchart:

Manifest (kustomization + helm):

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: longhorn
    version: 1.3.2
    repo: https://charts.longhorn.io
    namespace: longhorn-system
    releaseName: longhorn
    valuesInline:
      persistence:
        defaultClassReplicaCount: 1
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
        ingressClassName: nginx
        host: example.com
        path: /longhorn(/|$)(.*)
        tls: true
        tlsSecret: example-com-secret
```

In the longhorn helm chart 1.3.2 an upper border for kubeVersion was introduced

Chart.yaml
```yaml
apiVersion: v1
appVersion: v1.3.2
description: Longhorn is a distributed block storage system for Kubernetes.
home: https://github.com/longhorn/longhorn
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
keywords:
- longhorn
- storage
- distributed
- block
- device
- iscsi
- nfs
kubeVersion: '>=1.18.0-0 <1.25.0-0'
maintainers:
- email: maintainers@longhorn.io
  name: Longhorn maintainers
name: longhorn
sources:
- https://github.com/longhorn/longhorn
- https://github.com/longhorn/longhorn-engine
- https://github.com/longhorn/longhorn-instance-manager
- https://github.com/longhorn/longhorn-share-manager
- https://github.com/longhorn/longhorn-manager
- https://github.com/longhorn/longhorn-ui
- https://github.com/longhorn/longhorn-tests
- https://github.com/longhorn/backing-image-manager
version: 1.3.2
```
the older helm charts only have only an bottom border:

```
...
kubeVersion: '>=1.18.0-0'
...
```

If the upper border of kubeVersion is removed, ArgoCD can deploy the chart without a flaw.

**To Reproduce**

1. Create Application in ArgoCD
2. Point the application to the above kustomization and apply

**Expected behavior**

Successful deployment of longhorn helm chart 1.3.2 with given constraint

**Version**

```shell
argocd@argocd-server-6c957cb884-b2n2c:~$ argocd version
argocd: v2.5.1+504da42
  BuildDate: 2022-11-01T21:14:30Z
  GitCommit: 504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified   
```

**Logs**

```
time="2022-11-02T11:20:31Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-11-02T11:20:31Z\",\"message\":\"rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build .dev/misc/longhorn --enable-helm --load-restrictor LoadRestrictionsNone` failed exit status 1: Error: Error: chart requires kubeVersion: \\u003e=1.18.0-0 \\u003c1.25.0-0 which is incompatible with Kubernetes v1.25.0\\n\\nUse --debug flag to render out invalid YAML\\n: unable to run: 'helm template longhorn --namespace longhorn-system .dev/misc/longhorn/charts/longhorn --values /tmp/kustomize-helm-1430322709/longhorn-kustomize-values.yaml' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-1430322709/helm HELM_CACHE_HOME=/tmp/kustomize-helm-1430322709/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-1430322709/helm/.data] (is 'helm' installed?)\",\"type\":\"ComparisonError\"}]}}" application=argocd/longhorn-dev
```

**Additional information**

Already created issues in **k3s** and **longhorn** repositories:

* https://github.com/longhorn/longhorn/issues/4811
* https://github.com/k3s-io/k3s/discussions/6407
