### ISSUE TITLE
argocd-k8s-auth aws command dont have flag for region-code

### ISSUE THREAD

**Issue by Ryu-Z** [argoproj/argo-cd#11207]
# Summary

we have six eks clusters, and we have a ops eks cluster, deploy argocd in the ops eks cluster.
use an iam role sts assume for other aws accounts role to mange eks cluster

# Motivation

my argocd serviceaccount have an iam role for sts assume to other accounts
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::[aws-account-id]:role/[ops-eks-cluster-role]
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
  namespace: argocd
```
can argocd-k8s-auth aws command have the region-code flag set?
like this
```json
{
  "tlsClientConfig": {
    "insecure": false,
    "caData": "LS0...=="
  },
  "execProviderConfig": {
    "command": "aws",
    "args": [
      "--region",
      "ap-northeast-1",
      "eks",
      "get-token",
      "--cluster-name",
      "[eks-cluster-name]",
      "--role",
      "arn:aws:iam::[aws-account-id]:role/[role-name]"
    ],
    "env": null,
    "apiVersion": "client.authentication.k8s.io/v1beta1",
    "installHint": "aws dont exist"
  }
}
```

# Proposal

https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/?nc1=h_ls
i use this docs to configure my eks clusters
i want have a region field in the awsAuthConfig configuration and a sts assume configuration,
this can use the arocd container identity role to aussme other aws role
like this:
```json
{
    ...
    "awsAuthConfig": {
        "region": "us-east-1",
        "clusterName": "[eks-cluster-name]",
        "assumeRoleARN": "arn:aws:iam::[aws-account-id]:role/[role-name]"
    },
    ....
}
```
