### ISSUE TITLE
Application wizard shows destination URL instead of name

### ISSUE THREAD

**Issue by morey-tech** [argoproj/argo-cd#11228]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating an Application from YAML that is using the `destination.name` for the cluster, after clicking save, the UI shows the empty cluster destination URL instead of the name.

**To Reproduce**

1. Start creating a new Application, edit as yaml.
2. Paste manifest that uses the `destination.name`
    ```
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
        name: my-cluster
        namespace: argocd
    spec:
        destination:
            name: in-cluster
    ```
4. Click save. 

The destination section displays the empty cluster URL instead of the populated name.

**Expected behavior**

When the Application is using the destination name, after clicking save on editing as YAML, the destination section should display the name instead of the URL.

**Screenshots**

https://user-images.githubusercontent.com/4213435/200638541-22352fbd-7dfa-4f5f-b2dc-76f3ad9e89d3.mp4

**Version**

```json
{
    "Version": "v2.5.1+504da42",
    "BuildDate": "2022-11-01T21:14:30Z",
    "GitCommit": "504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**
N/A
