### ISSUE TITLE
Unable to use Helm with any valueFiles, Application prepending period to every path

### ISSUE THREAD

**Issue by zbup** [argoproj/argo-cd#11232]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
I am having issues picking up helm values values.. I have a pretty simple application setup:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: default
    name: mycluster
  project: whatever
  syncPolicy: {}
  source:
    repoURL: git@github.com:company/repo.git
    path: manifests/helmchart
    targetRevision: helmtest
    helm:
      valueFiles:
        - ../values-abcd.yaml
```
It seems like it's prepending my values file with a `.` but I'm not sure why... It ends up with an error and says it can't find the values file. 

The helm command snippet it shows in the error in the UI
```
helm template . --name-template myapp --namespace default --kube-version 1.24 --values .manifests/values-abcd.yaml......
```

The file .manifests/values-abcd.yaml does exist, I'm not sure where the extra leading `.` is coming from.

**Version**

```
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T17:06:04Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```
