### ISSUE TITLE
[Feature Request] app of apps relative path specification

### ISSUE THREAD

**Issue by kkimdev** [argoproj/argo-cd#11253]
# Summary

When using app of apps, support relative path to the target apps directory.

# Motivation

I have a group of apps that's released together, and they are versioned in different directories in a Git repository e.g., /dev/ /staging/ /v1.1/ /v2.3/ /v3.3/ .... It's handy to use ArgoCD's app of apps to manage them, but one inconvenience is that the path of the root application yaml should be also updated as well when it's moved.

```
  source:
    path: argocd/applications/ # path to be updated
    repoURL: 'https://github.com/xxxyyy'
    targetRevision: main
```
# Proposal

Allow simple relative path specification in ArgoCD Application yaml.
