### ISSUE TITLE
Prometheus-operator sync stuck progressing

### ISSUE THREAD

**Issue by strowi** [argoproj/argo-cd#11261]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to deploy prometheus as a crd, the resource ist synced ok but stuck progressing `waiting for healthy state of monitoring.coreos.com/Prometheus/rancheer-monitoring-prometheus`.

**To Reproduce**

Deploy the rancher-monitoring-crd + rancher-monitoring via helm

Create repo with
```
helm fetch rancher-charts/rancher-monitoring-crd --version 100.1.3+up19.0.3
helm fetch rancher-charts/rancher-monitoring --version 100.1.3+up19.0.3
mkdir apps && for x in *tgz; do tar xf $x -C apps;done;
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://gitlab.com/aedifion.io/XYZ/cluster-addons.git
              revision: HEAD
              directories:
              - path: apps/*

          - clusters:
              selector:
                matchLabels:
                  monitoring: "true"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: system
      source:
        repoURL: https://gitlab.com/aedifion.io/XYZ/cluster-addons.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: "{{ server }}"
        namespace: 'cattle-monitoring-system'
      syncPolicy:
        automated: {}
```

**Expected behavior**

Rancher-Monitoring Chart should be fully synced and healthy.

**Screenshots**

![image](https://user-images.githubusercontent.com/589662/201072884-e4e9b8ef-7286-4ad3-a401-3e7a2d631fef.png)

**Version**

```shell
argocd: v2.4.6+a48bca0
  BuildDate: 2022-07-12T22:56:26Z
  GitCommit: a48bca03c79b6d63be0c34d6094831bc6916b3bc
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0

```

**Logs**

```
time="2022-11-10T10:48:07Z" level=info msg="Resuming in-progress operation. phase: Running, message: waiting for healthy state of monitoring.coreos.com/Prometheus/rancher-monitoring-prometheus" application=argocd/rancher-monitoring
# can provide more if releveant, but cant find anything useful;)
```

Might be related to https://github.com/argoproj/argo-cd/pull/10508

regards,
strowi
