### ISSUE TITLE
Pull request generator - Bitbucket cloud support

### ISSUE THREAD

**Issue by Jamess-Lucass** [argoproj/argo-cd#11273]
# Summary
Same enhancement as [#10695](https://github.com/argoproj/argo-cd/issues/10695) with a slightly different proposal following ideas from #11150 and the existing implementation for `bitbucket-server` referenced in the docs [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/#bitbucket-server)

What change you think needs making.

# Motivation

A lot of users, including myself, use the cloud version of bitbucket and would benefit from being able to utilize the pull request generator feature provided by Argo CD.

# Proposal

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
    - pullRequest:
        bitbucket:
          # Workspace name where the repoistory is stored under. Required.
          owner: myproject
          # Repository slug. Required.
          repo: myrepository
          # URL of the Bitbucket Cloud API. (optional) Will default to 'https://api.bitbucket.org/2.0'.
          api: https://api.bitbucket.org/2.0
          # Credentials for Basic authentication. Required for private repositories.
          basicAuth:
            # The username to authenticate with
            username: myuser
            # Reference to a Secret containing the password or personal access token.
            passwordRef:
              secretName: mypassword
              key: password
        # Labels are not supported by Bitbucket Cloud, so filtering by label is not possible.
        # Filter PRs using the source branch name. (optional)
        filters:
          - branchMatch: ".*-argocd"
  template:
  # ...
```

Named `bitbucket` to keep aligned to how the `scmProvider` is named in #11150

- `owner` (required) could be named several different things, possibly `workspace` to follow the naming in [Bitbucket Cloud REST API docs](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-get)

- `api` (optional) is the base url for where the pull requests are queried from - In most cases this will remain `https://api.bitbucket.org/2.0` and if the `api` is not set or left blank, it will default back to `https://api.bitbucket.org/2.0`

- `basicAuth` (optional) is to support authenticating to private bitbucket cloud repositories
