### ISSUE TITLE
Make NetworkPolicies Cilium compatible

### ISSUE THREAD

**Issue by F1ko** [argoproj/argo-cd#11321]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using Cilium as a CNI in combination with the network policies defined in this repository, DNS requests are not permitted.
This is due to Cilium not checking pod cidrs as part of `ipBlock` (see https://github.com/cilium/cilium/issues/9209).

**To Reproduce**

The issue can be reproduced on clusters using Cilium as CNI.

Prepare pods:
```shell
kubectl create deploy nginx --image nginx
kubectl expose deployment nginx --port 80
kubectl run tmp-shell --rm -i --tty --image nicolaka/netshoot -- zsh
```

Inside the netshoot container:
```shell
$ nslookup nginx | grep -i address
Address:        10.96.0.10#53
Address: 10.101.155.51
```

Apply the following network policy:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
  podSelector:
    matchLabels:
      run: tmp-shell
  policyTypes:
  - Egress
```
 
Inside the netshoot container:
```shell
$ nslookup nginx
;; communications error to 10.96.0.10#53: timed out
;; communications error to 10.96.0.10#53: timed out
;; communications error to 10.96.0.10#53: timed out
;; no servers could be reached
```

Apply the same network policy without `ipBlock`:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    # to:
    # - ipBlock:
    #     cidr: 0.0.0.0/0
  podSelector:
    matchLabels:
      run: tmp-shell
  policyTypes:
  - Egress
```

Inside netshoot container:
```shell
$ nslookup nginx | grep -i address
Address:        10.96.0.10#53
Address: 10.101.155.51
```

**Expected behavior**

The network policies in this repository should permit DNS requests despite the users CNI choice.

**Screenshots**

N/A

**Version**

```shell
Most recent version: https://github.com/argoproj/argo-cd/tree/9bd0ed0d5601f6408ef822b282841464d9784a27
```

**Logs**

```
N/A
```
