### ISSUE TITLE
Allow to sync resources even with ComparisonError

### ISSUE THREAD

**Issue by agaudreault-jive** [argoproj/argo-cd#11356]
# Summary

We have remote clusters configured in ArgoCD with restricted permissions in the argocd-manager-role. When a CRD is added to the cluster, either with ArgoCD or with something else, all ArgoCD application will start failing with ComparisionError on that cluster (until the permission is given or the resource is excluded).

```
failed to sync cluster https://my-cluster/: failed to load initial state of resource Foo.my-crd.k8s.io: foo.my-crd.k8s.io is forbidden: User “system:serviceaccount:kube-system:argocd-manager” cannot list resource “foo” in API group “my-crd.k8s.io” at the cluster scope
```

We gave permission to the argocd-manager role to elevate its permission and it can create ClusterRole to add the permissions to the CRD with an aggregate rule.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-crd-argo
  labels:
    rbac.example.com/aggregate-to-argocd-manager-cluster-role: 'true'
rules:
  - apiGroups: ['my-crd.k8s.io']
    resources: ['foo']
    verbs: ['get', 'list', 'watch']
```

Then we have an applicationSet that will sync this manifest in the desired clusters.

**The problem is that the Application cannot be sync because it fails with ComparisionError.**

# Motivation

Make sure argoCD has an automated behavior when CRDs are added and it is running with restricted permission to remote clusters.

# Proposal

I think it should be possible to have a `syncOptions` to force a sync even if there's ComparisionError. Or have an option in the UI to force the sync.

I am not aware of how the backend works and if this makes sense, but to fix the situation, applying the manifest with `kubectl apply -f clusterrole.yaml` will work.

Let me know if you have another alternative to manage new CRDs in remote cluster.
