### ISSUE TITLE
Different order helm parameters make save error

### ISSUE THREAD

**Issue by zengzhengrong** [argoproj/argo-cd#11407]
```
project: default
source:
  repoURL: 'https://zengzhengrong.github.io/helm-charts'
  targetRevision: 4.4.17
  helm:
    parameters:
      - name: persistence.storageClassName
        value: openebs-hostpath
      - name: mongoExpress.ingress.enabled
        value: 'true'
      - name: mongoExpress.enabled
        value: 'true'
  chart: mongodb
destination:
  server: 'https://kubernetes.default.svc'
  namespace: mongodb
syncPolicy:
  syncOptions:
    - CreateNamespace=true

```
![image](https://user-images.githubusercontent.com/23110784/203542611-59fadcb1-55df-4198-ab05-26a4071b315a.png)

Above  save is work but 

If I change this order ```mongoExpress.enabled```  ```mongoExpress.ingress.enabled``` and save

```
project: default
source:
  repoURL: 'https://zengzhengrong.github.io/helm-charts'
  targetRevision: 4.4.17
  helm:
    parameters:
      - name: persistence.storageClassName
        value: openebs-hostpath
      - name: mongoExpress.enabled
        value: 'true'
      - name: mongoExpress.ingress.enabled
        value: 'true'
  chart: mongodb
destination:
  server: 'https://kubernetes.default.svc'
  namespace: mongodb
syncPolicy:
  syncOptions:
    - CreateNamespace=true

```

![image](https://user-images.githubusercontent.com/23110784/203543021-02b2169a-e0bd-4504-a9c9-a8421aa64626.png)

helm 

```
{{- if .Values.mongoExpress.enabled -}}
{{- if .Values.mongoExpress.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mongodb.name" . }}-express
spec:
  ingressClassName: {{ .Values.mongoExpress.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.mongoExpress.ingress.host }}
    http:
      paths:
      - path: {{ .Values.mongoExpress.ingress.path }}
        pathType: {{ .Values.mongoExpress.ingress.pathType }}
        backend:
          service:
            name: {{ include "mongodb.name" . }}-express
            port:
              number: 80
{{- end -}}
{{- end -}}
```
