### ISSUE TITLE
Ignoring erroneously labelled resources?

### ISSUE THREAD

**Issue by larsks** [argoproj/argo-cd#11403]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In some situations, OpenShift creates copies of resources: for example, when adding a custom logo to the UI, it copies a ConfigMap from the `openshift-config` namespace to the `openshift-console` namespace. This copy inherits all the labels from the original, including the ArgoCD `app.kubernetes.io/instance` label. This causes ArgoCD to mark the copy as "requires pruning", since (a) it appears to belong to an application but (b) does not appear in the source manifests.

I would like to ignore these resources, but I haven't been able to find the appropriate procedure. After reading the [compare options](https://argo-cd.readthedocs.io/en/stable/user-guide/compare-options/) documentation, I hoped that by adding the `argocd.argoproj.io/compare-options: IgnoreExtraneous` to these resources that they would be ignored by ArgoCD, but that does not appear to be the case: the copy inherits the annotation, but still shows up as "requires pruning" in the ArgoCD UI.

ArgoCD offers the ability to ignore entire classes of resources through the [resourceExclustions](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#resource-exclusions) mechanism, but that's not appropriate in this situation: we don't want to exclude ConfigMaps or Secrets; we only want to exclude *specific* ConfigMaps or Secrets.

**To Reproduce**

Create a resource that is erroneously labelled as belonging to an existing application. E.g., if you have an application called `testapp`, then creating something like this:

```
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: test-app
  name: testconfigmap
  namespace: default
```

Without deleting the resource, how do we instruct ArgoCD to ignore it during sync?

**Expected behavior**

I expect there to be a mechanism to instruct ArgoCD to ignore *specific* resources.

**Screenshots**

![Screenshot from 2022-11-22 16-28-45](https://user-images.githubusercontent.com/82622/203424800-b6f0af3f-c811-487b-9610-e8e94504f31f.png)

**Version**

```shell
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T17:06:04Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.5+unknown
  BuildDate: 2022-07-18T20:19:53Z
  GitTreeState: clean
  GoVersion: go1.18.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 1970-01-01T00:00:00Z
  Helm Version: v3.8.1+gb630818
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by wwolfe-mend** [comment]
I have the similar situation where I have one Service Account for many APPs.
I added
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my_sa_user
  annotations:
    argocd.argoproj.io/sync-options: Validate=false, Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
```
each argo app wants to add its own instance information or is says out of sync.
```
app.kubernetes.io/instance: my_app_instance_name_here
```
All the apps thrash every 5 seconds updating the `app.kubernetes.io/instance` I have many so it goes nuts!
The difference I noticed was I have `Auto Sync` on but `self heal` off it does not thrash back and forth.  It does say all are out of sync except the last one applied. 

IF you IGNORE at the project level and edit
argocd-cm.yaml with

```
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - ServiceAccount
      clusters:
      - "*"
kind: ConfigMap
```
IT completely hides the Service Account object from all of the APPs.  So at that point it is obscured and if you have to make a change to the Service Account manifest it will never get updated by ARGO.

WHICH brings up a point.  If the suggested way to ignore the resource is to add 
```
argocd.argoproj.io/compare-options: IgnoreExtraneous
```
to the resource IT WILL Never be updated!?

I need One argo-cd APP to update k8s when the SA manifest changes but all the other apps to `IGNORE` the SA manifest and not report `Out of Sync` when it changes.  
Ideally this would be an argo app setting to reference the SA manifest but always report it as synced or DNC. It would be nice if this out resource had its own color or maybe even a grey status icon.
Then in the one argo app that is controlled by the SA manifest will show `Out of Sync` and auto update/self heal as needed.   I do not think it is IDEAL to add an argo annotation to my k8s resource like  my Service Account manifest!

on Version v2.4.17+d330967
