### ISSUE TITLE
Deprecate ComponentParameterOverrides in favor of source specific config

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1141]
Our ComponentParameterOverrides feature is getting overloaded and is attempting to normalize different concepts of "parameters" into a single datastructure, which doesn't always fit. Some examples of this:

* the concept of "component" came from ksonnet, but has no meaning in helm.
* helm has both `--set` and `--set-string`, but we only support `--set`
* kustomize 2.0 has image whereas kustomize 1.0 has imagetag
* jsonnet has `ext-str` and `tla-code`

Rather than trying to fit everything into this concept of ComponentParameterOverrides, the current thought is to deprecate this feature in favor of explicit application source config specific to the tool.

**Comment by jessesuen** [comment]
Here are examples of proposed api spec changes:

Helm:

```yaml
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    helm:
      valueFiles:
      - values-prod.yaml

      parameters:

      # equivalent to: `helm template . --set image.pullPolicy=Always`
      - name: image.pullPolicy
        value: Always

      # equivalent to: `helm template . --set-string notABool=true`
      - name: notABool    
        value: "true"
        string: true
```

Kustomize:
```yaml
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    kustomize:
      namePrefix: my-prefix-
      nameSuffix: my-suffix-
      images:

      # equivalent to: kustomize set image postgres=eu.gcr.io/my-project/postgres:latest
      - name: postgres
        value: eu.gcr.io/my-project/postgres:latest

      # equivalent to: kustomize set image node:8.15.0
      - value: node:8.15.0

      # equivalent to: kustomize set image mysql=mariadb
      - name: mysql
        value: mariadb
```

Jsonnet:
```yaml
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    jsonnet:

      ext:
      # equivalent to: jsonnet --ext-str foo=bar
      - name: foo
        value: bar

      # equivalent to: jsonnet --ext-code fooObj=bar
      - name: fooObj
        value: "true"
        code: true

      tla:
      # equivalent to: jsonnet --tla-str foo=bar
      - name: foo
        value: bar

      # equivalent to: jsonnet --tla-code fooObj=bar
      - name: fooObj
        value: "true"
        code: true

```
