### ISSUE TITLE
parameters override not ready work for  kustomize 

### ISSUE THREAD

**Issue by PengLingJun** [argoproj/argo-cd#11415]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

parameters override not ready work for  kustomize 

**To Reproduce**

**Expected behavior**

Project Yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xyd-aops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    notifications.argoproj.io/subscribe.on-deployed.xyd-deploy: ""
    notifications.argoproj.io/subscribe.on-health-degraded.xyd-deploy: ""
    notifications.argoproj.io/subscribe.on-sync-running.xyd-deploy: ""
spec:
  generators:
    - git:
        repoURL: ${repo}
        revision: HEAD
        files:
          - path: overlays/**/config.yaml
  template:
    metadata:
      name: 'xyd-{{path.basename}}'
      namespace: 'xyd-{{path.basename}}'
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.xyd-deploy: ""
        notifications.argoproj.io/subscribe.on-health-degraded.xyd-deploy: ""
        notifications.argoproj.io/subscribe.on-sync-running.xyd-deploy: ""
    spec:
      project: 'xyd'
      source:
        repoURL: ${repo}
        targetRevision: HEAD
        path: 'overlays/{{path.basename}}'
      destination:
        name: '{{cluster_name}}'
        namespace: 'xyd-{{path.basename}}'
```
then, I use that cli command to parameters override

```
argocd app set ${app_name} --kustomize-image ${image and new tag}
```
wait 30s
sync command

```
argocd app sync ${app_name} 
```

result: not any sync happen.
I checked param in UI,You will see the new parameter in the ui when it is in the app set, but after a few seconds it changes back to a placeholder symbol in the version library

**Screenshots**

**Version**

```shell
argocd: v2.5.1+504da42.dirty
  BuildDate: 2022-11-01T23:23:38Z
  GitCommit: 504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be
  GitTreeState: dirty
  GoVersion: go1.19.3
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.5.0+1ae5aff
  BuildDate: 2022-11-08T21:26:53Z
  GitCommit: 1ae5aff2f834987945951a928da414a6b5c9b726
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```
I can see in argo-application-controller Observe that parameters are overwritten after reconciliation is completed
**Logs**

```
Paste any relevant application logs here.
```
