### ISSUE TITLE
helm chart in Harbor wont deploy

### ISSUE THREAD

**Issue by gabrielfsousa** [argoproj/argo-cd#11419]
Argocd Version : v2.5.2
Harbor  Version: v2.6.0

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-weave-scope
  namespace: argocd
spec:
  project: default
  source:
    chart: weave-scope
    repoURL: https://registry.local.com/chartrepo/artifacthub.io
    targetRevision: 1.0.0
    helm:
      releaseName: weave-scope
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
```
```
apiVersion: v1
kind: Secret
metadata:
  name: repo-harbor
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "false"
  insecure: "true"
  name: "harbor"
  type: helm
  url: "https://registry.local.com/chartrepo/artifacthub.io"
  project: "default"
```
![image](https://user-images.githubusercontent.com/722744/203856728-01ea418d-1b2b-42a2-b8e8-61fc221b371c.png)
![image](https://user-images.githubusercontent.com/722744/203856842-18bd40d5-0896-47b5-9942-68a297beac67.png)

```
PS C:\WORK\argocd> kubectl -n argocd logs deployment/argocd-repo-server --all-containers=true | grep error | grep weave
Found 2 pods, using pod/argocd-repo-server-568968697d-jb6cn
time="2022-11-24T19:12:24Z" level=warning msg="manifest cache error &ApplicationSource{RepoURL:https://registry.local.com/chartrepo/artifacthub.io,Path:,TargetRevision:1.0.0,Helm:&ApplicationSourceHelm{ValueFiles:[values.yaml],Parameters:[]HelmParameter{},ReleaseName:weave-scope,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:weave-scope,}: EOF"
time="2022-11-24T19:12:24Z" level=warning msg="manifest cache set error &ApplicationSource{RepoURL:https://registry.local.com/chartrepo/artifacthub.io,Path:,TargetRevision:1.0.0,Helm:&ApplicationSourceHelm{ValueFiles:[values.yaml],Parameters:[]HelmParameter{},ReleaseName:weave-scope,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:weave-scope,}/1.0.0: write tcp 10.42.234.167:34754->10.43.109.151:6379: write: broken pipe"
```
```
PS C:\WORK\argocd> kubectl -n argocd logs deployment/argocd-server --all-containers=true | grep error
Found 2 pods, using pod/argocd-server-764ddffcc9-8gzqg
time="2022-11-24T19:12:43Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = invalid session: signature is invalid" grpc.code=Unauthenticated grpc.method=List grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:12:43Z" grpc.time_ms=10.685 span.kind=server system=grpc
time="2022-11-24T19:14:23Z" level=error msg="finished unary call with code Unknown" error="error getting cached app state: cache: key is missing" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:14:23Z" grpc.time_ms=102.353 span.kind=server system=grpc
time="2022-11-24T19:16:06Z" level=error msg="finished unary call with code Unknown" error="error getting cached app state: cache: key is missing" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:16:06Z" grpc.time_ms=79.862 span.kind=server system=grpc
time="2022-11-24T19:41:36Z" level=error msg="finished unary call with code Unknown" error="error getting cached app state: cache: key is missing" grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:41:36Z" grpc.time_ms=39.418 span.kind=server system=grpc
time="2022-11-24T19:41:48Z" level=error msg="finished streaming call with code Unknown" error="error getting app resource tree: cache: key is missing" grpc.code=Unknown grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:41:37Z" grpc.time_ms=11720.975 span.kind=server system=grpc
time="2022-11-24T19:41:48Z" level=error msg="finished unary call with code Unknown" error="error getting cached app state: cache: key is missing" grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:41:48Z" grpc.time_ms=35.795 span.kind=server system=grpc
time="2022-11-24T19:42:00Z" level=error msg="finished streaming call with code Unknown" error="error getting app resource tree: cache: key is missing" grpc.code=Unknown grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:41:49Z" grpc.time_ms=11249.236 span.kind=server system=grpc
time="2022-11-24T19:56:31Z" level=error msg="finished unary call with code Unknown" error="error getting cached app state: cache: key is missing" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2022-11-24T19:56:31Z" grpc.time_ms=37.504 span.kind=server system=grpc
```
