### ISSUE TITLE
Add discovery-endpoint to oidc.config

### ISSUE THREAD

**Issue by shukawam** [argoproj/argo-cd#11421]
# Summary

For example, I would like to be able to specify the discovery-endpoint in the `oidc.config` as follows.

```yaml
data:
  url: https://argocd.example.com/

  oidc.config: |
    name: Okta
    issuer: https://some-oidc-provider.com/
    clientID: aaaabbbbccccddddeee
    clientSecret: $oidc.okta.clientSecret
    discovery-endpoint: https://123456789.some-oidc-provider.com/.well-known/openid-configuration # NEW

   # ... omit
```

# Motivation

I think that I need to support cases that the OIDC-Discovery Endpoint configuration is not in the bellow format.

`https://<issuer-url>/.well-known/openid-configuration`

**Comment by chris-stinemetz** [comment]
I came across this enhancement request and I wanted to express my strong support for it. I'm currently facing a similar issue where the ability to specify a custom discovery endpoint in the oidc.config would be extremely beneficial.

In my use case, I'm working with an OIDC provider where the discovery endpoint does not follow the standard format of https://<issuer-url>/.well-known/openid-configuration. Instead, it has a unique URL structure.

Here's an example of how I would like to specify the discovery endpoint:

``` yaml
data:
  url: https://argocd.example.com/

  oidc.config: |
    name: Okta
    issuer: https://company-oidc-provider.com/
    clientID: aaaabbbbccccddddeee
    clientSecret: $oidc.okta.clientSecret
    discoveryEndpoint: https://company-oidc-provider.com/meta/aba/oidc/.well-known/openid-configuration 
 ```
 
Having the ability to specify a custom discovery endpoint would provide greater flexibility and compatibility with various OIDC providers. I believe this enhancement would be a valuable addition to the project and would benefit many users who are in similar situations.

Thank you for considering this enhancement.
