### ISSUE TITLE
Support for authenticating to helm OCI repositories with tools like `docker-credential-gcr`

### ISSUE THREAD

**Issue by jacek-jablonski** [argoproj/argo-cd#11492]
# Summary

Related discussion: https://github.com/argoproj/argo-cd/discussions/10644

ArgoCD should have some kind of support for authenticating to cloud-hosted OCI repositories (f.e. GCP Artifact Registry) using tools like docker-credential-gcr.

# Motivation

As the popularity of cloud-hosted repositories is increasing, the possibility of using them in ArgoCD should be easier. Currently, to be able to use the most secure solution (Workload Identity + `docker-credential-gcr` helper), you need to do a lot of workarounds.
Below is what had to be changed in `argocd-repo-server` deployment to be able to use `docker-credential-gcr` with helm (apart from the Workload Identity configuration):

```yaml
# starting command itself, for executing docker-credential-gcr
- op: replace
  path: /spec/template/spec/containers/0/command
  value:
    - "sh"
    - "-c"
    - docker-credential-gcr configure-docker -registries xxx-docker.pkg.dev
      && entrypoint.sh argocd-repo-server --redis $(ARGOCD_REDIS_SERVICE):6379

# volume containing docker-credential-gcr binary
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /usr/local/bin/docker-credential-gcr
    name: docker-credential-gcr
    subPath: docker-credential-gcr
    readOnly: true

# volume to make /home/argocd/.docker writable (needed for docker configuration, which is used by helm)
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /home/argocd/.docker
    name: docker-config

# init container for downloading docker-credential-gcr
- op: add
  path: /spec/template/spec/initContainers/-
  value:
    command:
      - sh
      - -c
      - "wget -O /tmp/docker-credential-gcr.tar.gz https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.6/docker-credential-gcr_linux_amd64-2.1.6.tar.gz
        && tar -xzf /tmp/docker-credential-gcr.tar.gz -C /tmp
        && mv /tmp/docker-credential-gcr /var/run/docker-credential-gcr/"
    image: busybox:latest
    name: copy-docker-credential-gcr
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
      - mountPath: /var/run/docker-credential-gcr
        name: docker-credential-gcr

# volume for docker-credential-gcr binary
- op: add
  path: /spec/template/spec/volumes/-
  value:
    emptyDir: {}
    name: docker-credential-gcr

# volume for docker config directory
- op: add
  path: /spec/template/spec/volumes/-
  value:
    emptyDir: {}
    name: docker-config
```

# Proposal

As docker-credential-gcr is a vendor dependent tool and its inclusion in the `argocd-repo-server` perhaps should be within the operator's task, the ability to modify files in the /home/argocd/.docker directory should be less complicated. In addition, it would also be useful to be able to run the command configuring access to repositories more elegantly (`docker-credential-gcr configure-docker -registries xxx-docker.pkg.dev` in my case) without the need to modify the main command.

Perhaps there is another - easier way to access such repositories which I have omitted. If so, please advise.
