### ISSUE TITLE
Build environment variables not always rendered in manifest

### ISSUE THREAD

**Issue by dowlingw** [argoproj/argo-cd#11496]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When updating the Target Revision from an empty string for an application, the rendered manifest is intermittently rendering without Build Environment variables being substituted.

**To Reproduce**

1. Declaratively create an ArgoCD application, passing through the `ARGOCD_APP_SOURCE_TARGET_REVISION` variable in the application configuration:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapplication
spec:
  project: myproject
  source:
    helm:
      valueFiles:
        - {{ .Values.environment }}/values.yaml
        - {{ .Values.environment }}/{{ .Values.clusterName }}.yaml
      parameters:
        - name: images.app.label
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: images.migration.label
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
    path: kubernetes/myapplication
    repoURL: https://github.com/some/repository.git
  destination:
    namespace: myapps
    server: https://kubernetes.default.svc
```

2. Using either the argo cli or web ui, set the **Target Revision** parameter to a valid value.

3. Observe that references in the rendered template to `.Values.images.migration.label` are empty.

**Expected behavior**

The rendered template to contain the target revision field.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.2.2+03b17e0.dirty
  BuildDate: 2022-01-01T16:53:02Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

N/A

**Notes**

* This appears to only occur when setting the revision away from an empty string.
* This is not reproducible 100% of the time
* As a workaround we have attempted performing a **Hard Refresh**, however this also does not fix this 100% of the time
* We are seeing this across multiple applications, argo instances and kubernetes clusters/versions

**Comment by dowlingw** [comment]
Actually, just now we've seen this present differently - same reproduction steps but in this scenario it is rendering in the diff output but failing when syncing.

![image](https://user-images.githubusercontent.com/1167455/204709437-a19e544b-5098-46e4-b131-0c0a9721df7e.png)

**Comment by chasain** [comment]
+1 on this issue, seeing this in v2.4.12+41f54aa with a parameter we feed to pod labels, they get set to a version and stay that version even after we sync to a different target revision. Hard refresh typically fixes this issue for us.

**Comment by aaronborden-rivianvw** [comment]
Also seeing this in argocd v2.14.17+fca3a7e when using the environment variables in `valuesObject` with an ApplicationSet.

```
    spec:
      source:
        repoURL: https://example.com
        path: .
        targetRevision: "{{ .head_sha }}"
        helm:
          releaseName: mr-{{ .number }}-{{ .path.basename }}
          valueFiles:
            - values/{{ .path.basename }}/values.yaml
            - values/{{ .path.basename }}/dev.values.yaml
          valuesObject:
            gitlab_runner:
              # https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/
              platform:
                fleetRevision: "0000000000000000000000000000000000000000"
                fleetVersion: 0.0.0-preview
                runnerRevision: $ARGOCD_APP_REVISION
                runnerVersion: $ARGOCD_APP_SOURCE_TARGET_REVISION
```
