### ISSUE TITLE
Can't remove the argo prefix in the application title in the UI

### ISSUE THREAD

**Issue by knjoroge** [argoproj/argo-cd#11507]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello,
I have deployed argo-cd via kubernetes using [git-generator](https://argocd-applicationset.readthedocs.io/en/stable/Generators-Git/) 

I have set the namespace to `argo` in the ApplicationSet and it has deployed my applications but I would like to get rid of the argo prefix in the title of the service. I removed the `namespace` and redeployed but still the argo prefix remains. 

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set
  namespace: 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: xxxx
      revision: main
      directories:
      - path: xxxx
  template:
    metadata:
      name: "{{`{{path.basename}}`}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: xxxx
        targetRevision: main
        path: "{{`{{path}}`}}"
        directory:
            jsonnet: {}
            exclude: .source.json
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 

```

**Expected behavior**

Expected behavior is to have the argo prefix removed in the title

**Screenshots**

![Screen Shot 2022-11-30 at 4 07 23 PM](https://user-images.githubusercontent.com/18235897/204849171-805cfdd6-aee0-40d8-821c-6013c2f9b17d.png)

By removing namespace it should remove the prefix but it does not.
