### ISSUE TITLE
RBAC blocks app sync when Application namespace is omitted

### ISSUE THREAD

**Issue by mktgbnk** [argoproj/argo-cd#11510]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When Application object doesn't specify **application.spec.destination.namespace** in non-default project appsync fails with 
`application destination {https://kubernetes.default.svc/ } is not permitted in project`, while all the resources rendered have namespace defined.

Omitted namespace is treated as an empty string and doesn't pass the glob matching

**Workaround**
Two ways to workaround this issue are:
- Recommended: Specify application.spec.destination.namespace
- Hacky: add empty namespace to project rbac configuration, like so
```
  destinations:
  - namespace: ''
    server: '*'
```

**To Reproduce**
This spec combination would fail with the above error
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-project
  namespace: argocd
spec:
  destinations:
  - namespace: 'sample-project-namespace'
    server: '*'
  sourceRepos:
  - '*'
```
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
project: sample-project
source:
  repoURL: '...'
  path: '...'
  targetRevision: HEAD
  helm:
    valueFiles:
      - ...
    ignoreMissingValueFiles: true
destination:
  server: 'https://kubernetes.default.svc/'
syncPolicy: {}
```

**Expected behavior**

RBAC should allow to create application objects with undefined destination namespace and only block the syncing on per resource level

**Version**

```shell
bash-4.2$ argocd version
argocd: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:35:38Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
```
