### ISSUE TITLE
Using Azure AD with ArgoCD DEX returns all AD groups a user belongs too

### ISSUE THREAD

**Issue by toralf-hlag** [argoproj/argo-cd#11523]
We configured ArgoCD to use DEX in the following manner:

```
  - type: microsoft
    id: microsoft
    name: Azure AD
    config:
      clientID: $argocd-azure-ad-oauth:client-id
      clientSecret: $argocd-azure-ad-oauth:client-secret-value
      redirectURI: $argocd-azure-ad-oauth:redirect-uri
      tenant: $argocd-azure-ad-oauth:tenant
      useLoginAsID: false
```

We configured MS Azure AD to return only the application specific groups. But we do get all groups (about 600) of a user.
An MS developer told us that this is not a bug but an application specific behavior (of DEX).

Therefore, please enhance DEX to not query MS Graph for all groups of a user. Instead, DEX should only return the (in Azure AD defined groups) for the application, if configured so in Azure AD.
