### ISSUE TITLE
Webhook processing failed: event not defined to be parsed (gh pull_request event)

### ISSUE THREAD

**Issue by IvanovOleg** [argoproj/argo-cd#11532]
### 

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Github pull_request webhook fails, but ping works.

**To Reproduce**
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - scmProvider:
              github:
                organization: example
                allBranches: false
                tokenRef:
                  secretName: creds-github-https
                  key: password
              filters:
                - repositoryMatch: ^pref-
                  pathsExist: [deploy/overlays/pr/kustomization.yaml]
          - pullRequest:
              github:
                owner: example
                repo: '{{.repository}}'
                tokenRef:
                  secretName: creds-github-https
                  key: password
  template:
    metadata:
      name: '{{.repository}}-pr-{{.number}}'
    spec:
      project: example
      source:
        repoURL: '{{.url}}'
        targetRevision: '{{substr 0 7 .head_sha}}'
        path: 'deploy/overlays/pr'
        plugin:
          env:
            - name: APP
              value: app-pr-{{.number}}
            - name: HOST
              value: app-pr-{{.number}}.dev.example.com
            - name: IMAGE
              value: XXXX.dkr.ecr.us-east-1.amazonaws.com/app:{{substr 0 7 .head_sha}}
      destination:
        name: dev
        namespace: '{{.repository}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

```
Request URL: https://argocd.example.com/api/webhook
Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/35a454f
X-GitHub-Delivery: e6d86030-71db-11ed-9657-9fb049f4f120
X-GitHub-Event: pull_request
X-GitHub-Hook-ID: 390781054
X-GitHub-Hook-Installation-Target-ID: 542790698
X-GitHub-Hook-Installation-Target-Type: repository
X-Hub-Signature: sha1=ddea7b5a213e9f0d3fb3b1ef2ba14df090819fdd
X-Hub-Signature-256: sha256=690247389339e86aa26da74bf8726734356f24f2ff47902c4bbdf1286b10205a
```

**Expected behavior**

Webhook is accepted

**Version**

```shell
argocd: v2.5.3+0c7de21
  BuildDate: 2022-11-28T17:22:28Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.5.3+0c7de21
  BuildDate: 2022-11-28T16:51:33Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**
pull_request.opened
```
Webhook processing failed: event not defined to be parsed
```
