### ISSUE TITLE
You may need to run `helm dependency build` to fetch missing dependencies:

### ISSUE THREAD

**Issue by AurimasNav** [argoproj/argo-cd#11564]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Helm chart via kustomize failing to deploy with `you may need to run helm dependency build` error.
`kustomize build` locally was giving the same error until I run `helm dep build` when chart.lock and .tgz files were added the `kustomize build` no longer resulted in an error locally.
I've tried to add `Chart.lock` to the repo, but that did not change the outcome.
Adding .tgz file to the repo did solve the issue, however I wonder if that is actually the intended behavior? Is it mandatory commit dependency .tgz files for it to work?

**To Reproduce**
base/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml

helmGlobals:
  chartHome: charts
helmCharts:
- name: external-secrets
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: charts/external-secrets/values.yaml
```
base/namespace.yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
```
base/charts/external-secrets/Chart.yaml
```yaml
apiVersion: v2
name: external-secrets
version: 0.6.1
dependencies:
- name: external-secrets
  version: 0.6.1
  repository: https://charts.external-secrets.io
```

base/charts/external-secrets/values.yaml
```yaml
external-secrets:
  serviceMonitor:
    enabled: true
```

Added `kustomize.buildOptions: --enable-helm` to `argocd-cm configmap`
Added external-secrets repo config to argocd helm values.yaml
```yaml
configs:
  repositories:
    external-secrets:
      url: https://charts.external-secrets.io
      name: external-secrets
      type: helm
```

**Expected behavior**
external-secrets getting deployed to k8s

**Screenshots**
![image](https://user-images.githubusercontent.com/7810047/205668229-e182b30e-0ed9-46f3-a637-3667c6804a3a.png)

**Version**

```shell
argocd: v2.5.3+0c7de21
  BuildDate: 2022-11-28T17:11:59Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.3+0c7de21
  BuildDate: 2022-11-28T16:51:33Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**
```
ComparisonError: rpc error: code = Unknown desc = `kustomize build .overlays/dev --enable-helm` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from '../../base': '.base' must resolve to a file': recursed accumulation of path '.base': Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: external-secrets : unable to run: 'helm template external-secrets --namespace external-secrets .base/charts/external-secrets --values /tmp/kustomize-helm-2338096147/external-secrets-kustomize-values.yaml' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-2338096147/helm HELM_CACHE_HOME=/tmp/kustomize-helm-2338096147/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-2338096147/helm/.data] (is 'helm' installed?)
```

**Comment by chrisduong** [comment]
I'm facing the same issue, even if purely Helm applications

**Comment by jdomag** [comment]
I'm seeing a lot of those errors in repo-server. I use halm charts that have some dependency in Chart.yaml. 
The errors seems to happen periodically no matter if our CICD sync the application or not. 
All the apps are in "sync" state anyway, but from time to time this error happens during CICD on "argocd app sync" then whole pipeline crashes. 
Argocd 2.4.18

**Comment by sebolabs** [comment]
I'm seeing that same error message for a chart that is configured with a local dependency like that:
```
apiVersion: v2
name: myApp
description: myApp
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: service
  version: 0.1.0
  repository: file://../../charts/service
```
my folder structure is:
```
project
-- apps
---- myApp
------ Chart.yaml
-- charts
---- service
------ Chart.yaml
```
I'm getting:
```
An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: service
```
ArgoCD version: `v2.5.7+e0ee345`

**Comment by AurimasNav** [comment]
Just guessing that in my case it happens because argocd is simply executing kustomize, and kustomize does not work without executing `helm dependency build` prior.

**Comment by audleman** [comment]
Does anybody know if there's a way to ask kustomize to run `helm dep build` first?

**Comment by toyamagu-2021** [comment]
@AurimasNav 
Yes, think ArgoCD simply executes `kustomize build --enable-helm` internally.
Does the following manifest not enough for your use case?
Or I'm afraid we should use ConfigMapPlugin as @audleman suggested.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: external-secrets-values.yaml
```

It seems like that `kustomize build --enable-helm` runs `helm pull --repo ${helmCharts.repo}` internally, and pulls helm charts locally, then templating it.
If we have a local chart directory, kustomize skips `helm pull`. So you got the error you mentioned.
