### ISSUE TITLE
argocd sso work in ui but not argocd cli when enable istio AuthorizationPolicy

### ISSUE THREAD

**Issue by hamdymoussa** [argoproj/argo-cd#11576]
Hello,

I'm using argocd version:

```
argocd version
argocd: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:35:38Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:35:38Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.9.0+g7ceeda6
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```
And we noticed argocd sso work in ui but not argocd cli when enable istio AuthorizationPolicy to whitelist the IPs should reach argocd instance

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: argocd-ingress-policy
  namespace: argo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argo
  action: ALLOW
  rules:
  - from:
    - source:
        remoteIpBlocks:
          - x.x.x.x/32
    to:
    - operation:
        hosts:
        - argocd.xxxxx.com

```
we got such error:

```
argocd login argocd.cp.stage.kyma.cloud.sap --sso
FATA[0002] rpc error: code = PermissionDenied desc = RBAC: access denied
```

**Comment by pre** [comment]
I can reproduce the same problem. 

With `AuthorizationPolicy` as follows there's the same error about RBAC: access denied. Without this works. Anything else than "allow all" (ie. cluster default AuthorizationPolicy in istio-system) causes the error. 

ArgoCD frontpage works, but OAuth authentication fails with 
```
Failed to query provider "https://argocd.cluster-public-domain.com/api/dex": 403 Forbidden: RBAC: access denied
```

```yaml 
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default
  namespace: argocd
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - argocd
        - istio-system # no effect 
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account # public url works, but dex doesn't
  - to:
    - operation:
        ports: # prometheus stats do work
        - "15090" # istio-proxy
        - "8082"  # argocd-metrics
        - "8083"  # argocd-server-metrics
        - "8084"  # argocd-repo-server-metrics
```

**Comment by pre** [comment]
Got it working by allowing access to the webhook and dex paths. I split the AuthorizationPolicy in two pieces:

```yaml

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - argocd
  - to:
    - operation:
        ports:
        - "15090" # istio-proxy
        - "8082"  # argocd-metrics
        - "8083"  # argocd-server-metrics
        - "8084"  # argocd-repo-server-metrics
  - to:
    - operation:
        paths:
        - /api/webhook
        - /api/dex*
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: argocd-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
        - cluster.local/ns/our-internal-argocd-client-application/sa/default
```
