### ISSUE TITLE
Directory recuse: true not making my application sync

### ISSUE THREAD

**Issue by Mayor-X** [argoproj/argo-cd#11583]
I created an application which  synced the yaml files in root folder in git. If I add 

`directory
    recuse: true`

to capture the yaml files in the subfolders, the application doesn't sync, and brings up invalid spec error: unable to generate manifests.

**Comment by nmohoric** [comment]
Would need to see your spec, are you sure you're typing it right? You've typed "recuse" here but the setting is "recurse" so maybe it's a spelling error?

Should look like
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    directory:
      recurse: true
```
