### ISSUE TITLE
App health progressing when Kubernetes Job has Suspend=true

### ISSUE THREAD

**Issue by ashutosh16** [argoproj/argo-cd#11603]
# Summary

App Health Shows progressing when the Job spec has Suspend=true.
![Screen Shot 2022-12-07 at 4 00 33 PM](https://user-images.githubusercontent.com/11219262/206323256-ea8b7f4b-3b23-4bd1-b7b0-fe19c2c622e3.png)
		}

Please give examples of your use case, e.g. when would you use this.

Job manifest
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: node-app-job
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: node-app-job
        image: alpine   #your docker image
        command: ["echo", "Welcome to my Node app"]
      restartPolicy: Never
```
With Kubernetes 1.21, a new feature was added where use can mark job as suspended
https://kubernetes.io/blog/2021/04/12/introducing-suspended-jobs/

we need to include suspend condition in the health_job.go[ gitops-engine](https://github.com/argoproj/gitops-engine/blob/1ce2acc845d230a279442eb7576203525bced9cc/pkg/health/health_job.go#L34). 

```
case batchv1.JobSuspended:
	complete = true
	message = condition.Message
	if condition.Status == corev1.ConditionTrue  {
		isSuspended = true
	}
```
