### ISSUE TITLE
Add a replicas configuration option for kustomize

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-cd#11650]
# Summary

Currently, kustomize configuration options are available only for `namePrefix`, `nameSuffix`, `images`, `commonLabels`, `commonAnnotations` according to [argocd-doc](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/).

I would like to see a replicas transformer to change a number of replicas [kustomize-doc](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replicas/).

# Motivation

I would like to change the number of replicas in `application.yaml`. Like,

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
    # kustomize specific config
    kustomize:
      replicas:
        - name: deployment-name
          count: 5
```

# Proposal

I think it is straightforward.

* Kustomize already implements `kustomize edit set replicas deployment-name=5`.
* And our code is ready to add the above command in https://github.com/argoproj/argo-cd/blob/b4c12815f0131b337404e67534eca54004ba47de/util/kustomize/kustomize.go#L87
* So, we can implement this feature by following the same way as #4613

**Comment by crenshaw-dev** [comment]
Sounds great to me. Want to open a PR?

**Comment by toyamagu-2021** [comment]
@crenshaw-dev 
I'll gladly do!

**Comment by maltewhiite** [comment]
I would love to do this with ApplicationSet as well

<details><summary>ApplicationSet Example Yaml</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: guestbook-qa
        url: https://kubernetes.default.svc
        values:
          frontend:
            replicas: 1
      - namespace: guestbook-e2e
        url: https://kubernetes.default.svc
        values:
          frontend:
            replicas: 2
      - namespace: guestbook-stage
        url: https://kubernetes.default.svc
        values:
          frontend:
            replicas: 3
      - namespace: guestbook-prod
        url: https://kubernetes.default.svc
        values:
          frontend:
            replicas: 5
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: gitops
      source:
        repoURL: https://gitlab.com/kubernetes-practice/my-k8s/kia.git
        targetRevision: HEAD
        path: gitops-and-kubernetes/guestbook
        kustomize:
          replicas:
            - name: frontend
              count: '{{values.frontend.replicas}}'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
```

</details>

**Comment by toyamagu-2021** [comment]
@maltewhiite 
Thanks for the detailed suggestions.
Yes, we can do that after #11665 is merged. I used the following manifest for the test:

<details>
<summary>applicationset.yaml</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: guestbook-qa
        url: https://kubernetes.default.svc
        values:
          replicas: "1"
      - namespace: guestbook-e2e
        url: https://kubernetes.default.svc
        values:
          replicas: "2"
      - namespace: guestbook-stage
        url: https://kubernetes.default.svc
        values:
          replicas: "3"
      - namespace: guestbook-prod
        url: https://kubernetes.default.svc
        values:
          replicas: "5"
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: kustomize-guestbook
        kustomize:
          replicas:
            - name: kustomize-guestbook-ui
              count: '{{values.replicas}}'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
```

</details>

Please let me know if there is any misunderstanding.
