### ISSUE TITLE
[ApplicationSet] Support Go Templating in `spec.generators`

### ISSUE THREAD

**Issue by llavaud** [argoproj/argo-cd#11661]
# Summary

Support Go Templating in ApplicationSet `spec.generators`

# Motivation

I would like to be able to do some Go Templating on the parameters generated by another generator like in the following example:

```yaml
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/argoproj/applicationset.git
              revision: HEAD
              files:
                - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  kubernetes.io/environment: '{{default "foo" .my_label}}'
```

# Proposal

Implemented in the same way as the support of Go Templating in `spec.template` ?

**Comment by llavaud** [comment]
after digging a little into the code, it seems that goTemplate must be supported in `spec.generators`.

with the following spec, I got a parsing error:
```yaml
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/myrepo.git
              revision: master
              files:
                - path: instances/*/argocd.yaml
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  cloud_provider: '{{default "aws" .cloud_provider}}'
```

It fails with the following error:
```
failed to get params for second generator in the matrix generator: child generator returned an error on parameter generation: failed to parse template {"clusters":{"selector":{"matchLabels":{"argocd.argoproj.io/secret-type":"cluster","cloud_provider":"{{default \"aws\" .cloud_provider}}"}},"template":{"metadata":{},"spec":{"source":{"repoURL":""},"destination":{} ,"project":""}}}}: template: :1: unexpected "\\" in operand
```

It seems to failed [here](https://github.com/argoproj/argo-cd/blob/e420666d76af5c7b5cdcf000e92952a54cc39bdb/applicationset/utils/utils.go#L213) when parsing the manifest.
