### ISSUE TITLE
ApplicationSet does not respect the namespace metadata for the application generated

### ISSUE THREAD

**Issue by IxDay** [argoproj/argo-cd#11683]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am using an ApplicationSet to generate multiple applications object in an ArgoCD setup supporting the multiple namespaces

**To Reproduce**

Set up an ArgoCD supporting multiple namespaces, i.e: pass the `ARGOCD_APPLICATION_NAMESPACES` environment variable to your application controller or use the following values on your Helm chart

```
configs:
  params:
    application.namespaces: foo,bar
```
Once this is done, create an ApplicationSet which should push applications to those namespaces:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo-bar
spec:
  generators:
    - list:
    elements:
      - namespace: foo
      - namespace: bar
  template:
    metadata:
      name: 'app-{{namespace}}'
      namespace: '{{namespace}}'
    spec:
      project: default
      source:
        path: '...'
      destination:
        namespace: kube-system
```

All the applications are created in the `argocd` namespace

**Expected behavior**

The applicationSet should respect the namespace of the application the same way as a manually created application

**Version**

```shell
argocd: v2.5.2
```
