### ISSUE TITLE
Add ComparedAt to SyncStatus

### ISSUE THREAD

**Issue by chez-shanpu** [argoproj/argo-cd#11698]
# Summary

Add `comparedAt` field, which contains the comparison time with the repository, to `SyncStatus`.
```go
type SyncStatus struct {
	Status SyncStatusCode `json:"status" protobuf:"bytes,1,opt,name=status,casttype=SyncStatusCode"`
	ComparedTo ComparedTo `json:"comparedTo,omitempty" protobuf:"bytes,2,opt,name=comparedTo"`
	Revision string `json:"revision,omitempty" protobuf:"bytes,3,opt,name=revision"`
	// new
	ComparedAt string `json:"comparedAt,omitempty" protobuf:"bytes,4,opt,name=comparedAt"`
}
```

# Motivation
To trigger notifications after a few minutes of applications status changing.

Currently, there is no fields which indicates status changing time.
Therefore make this new field and set trigger as follows.

```yaml
  trigger.on-sync-status-outofsync: |
    - description: Application status is 'OutOfSync'
      send:
      - app-sync-status-outofsync
      when: app.status.sync.status == 'OutOfSync' and time.Now().Sub(time.Parse(app.status.sync.comparedAt)).Minutes() >= 5
```

# Proposal

1. Add new struct member `ComparedAt` to `SyncStatus` struct.
2. Set timestamp in [`CompareAppState`](https://github.com/argoproj/argo-cd/blob/92abb563aff6946a325cb7cb4dd10e3329de1799/controller/state.go#L328)
