### ISSUE TITLE
Unable to create app from private repo: x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by papanito** [argoproj/argo-cd#1171]
We are using internal Bitbucket server for the git repos, which we want to add to argo-cd. Bitbucket servers the repo as https with self-signed certificates. I've added the certificates as secrets to the deployment.

I am able to configure the repo under "Settings / Repositories":

![image](https://user-images.githubusercontent.com/15034009/53335707-7c4f5a00-38fc-11e9-89cc-e3ba79b24625.png)

However when I get to create an application I get the following error
```bash
Unable to load data: Get https://scm.intra/argocd/test/info/refs?service=git-upload-pack: x509: certificate signed by unknown authority
```

**Steps to reproduce**

1. Add certificates as secrets

   ```bash
   kubectl apply -f selfsignedcert.yml
   ```

1. Download [`install.yaml`](https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml) and mount the certificates something like

   ```yml
   ...
   # add this to all containers
   volumeMounts:
   - mountPath: /etc/ssl/certs/selfsignedcert.pem
     subPath: selfsignedcert.pem
     name: selfsignedcert
   ...
   volumes:
   - name: selfsignedcert
     secret:
       defaultMode: 420
       secretName: selfsignedcert
       items:
       - key: selfsignedcert.pem
         path: selfsignedcert.pem
   ```

1. Install argo-cd

   ```bash
   kubectl create namespace argocd
   kubectl apply -n argocd -f install.yaml
   ```

The `selfsignedcert.yml` looks like

```yml
apiVersion: v1
kind: Secret
metadata:
  name: selfsignedcert
  namespace: argocd
data:
  selfsignedcert.pem: |
    xxxxxx...
```
