### ISSUE TITLE
adding a private repo declaratively shows error SSH agent requested but SSH_AUTH_SOCK not-specified

### ISSUE THREAD

**Issue by narg95** [argoproj/argo-cd#1172]
# Description

Adding a private repository, using a `ssh-key` in a secret to autenticate, by a declarative approach fails with `SSH agent requested but SSH_AUTH_SOCK not-specified`. 

```
argocd repo list
REPO                                        USER  STATUS  MESSAGE
git@bitbucket.org:MY-PROJECT/MY-REPO.git        Failed  Unable to connect to repository: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
```

## NOTE

If added by the command-line `argocd repo add git@bitbucket.org:MY-PROJECT/MY-REPO.git --ssh-private-key-path key/id_rsa_bitbucket`:
- *It works* **if** there are no previous attempts to add it  declaratively 
- it does **not** work if it was *first* added declaratively and then deleted with `argocd repo rm git@bitbucket.org:MY-PROJECT/MY-REPO.git` and then added with the command above.

## Files

kustomization.yaml
```
bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v0.11.2

configMapGenerator:
- name: argocd-cm
  behavior: merge
  files:
  - repositories=repositories.yaml

secretGenerator:
- name: bitbucket
  files:
  - sshPrivateKey=key/id_rsa_bitbucket

generatorOptions:
  disableNameSuffixHash: true
```
repositories.yaml
```
- sshPrivateKeySecret:
  key: sshPrivateKey
  name: bitbucket
  url: git@bitbucket.org:MY-PROJECT/MY-REPO
```

a valid key is set in the path `key/id_rsa_bitbucket`, this key works because as explained above, it works if added by the command line.

# Expected Behavior

```
argocd repo list
REPO                                        USER  STATUS      MESSAGE
git@bitbucket.org:MY-PROJECT/MY-REPOgit        Successful
```

# UPDATE

1. It was an identation problem in the repositories.yaml causing a wrong unmarshalling of the `sshPrivateKeySecret` was empty :). The right version is here:

```
- sshPrivateKeySecret:
    key: sshPrivateKey
    name: bitbucket
  url: git@bitbucket.org:MY-PROJECT/MY-REPO
```

2. There is a caching issue with the repo service, when it is deleted it is not removed from the cache of the connection status. This PR  #1182  fixes it

**Comment by neoakris** [comment]
(Not trying to revive a dead post)
I had the same issue and found this page via google, I'm posting on this closed thread incase it helps other future googlers. 

I think there was a change in a newer version of argocd. 
I had the exact same error message, and it didn't go away for me 

until I changed my url from 
url: git@10.10.10.10:22/home/git/bootstrap.git

to have ssh:// in the front

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
spec:
  project: default
  source:
    repoURL: 'ssh://git@10.10.10.10:22/home/git/bootstrap.git'
    ...
```
