### ISSUE TITLE
Always use CMP no matter helm or kustomize choosed

### ISSUE THREAD

**Issue by LinuxSuRen** [argoproj/argo-cd#11752]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I installed a CMP as sidecar mode. See the details from [here](https://github.com/LinuxSuRen/github-action-workflow/).

Then all applications are forced to use this CMP instead of the desired one.

The manifests is:

```yaml
project: default
source:
  repoURL: 'https://gitee.com/devops-ws/learn-pipeline-go.git'
  path: kustomize
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated: {}
```

**To Reproduce**

1. Install the above CMP
2. Create Applications on the UI

**Expected behavior**

The CMP only works when I choose it.

**Screenshots**

![image](https://user-images.githubusercontent.com/1450685/208384822-1deabc37-0e02-45e1-8b36-4b8862844baf.png)

![image](https://user-images.githubusercontent.com/1450685/208385226-5c664e59-74c0-4507-bcb5-de11b4c8cc97.png)

![image](https://user-images.githubusercontent.com/1450685/208389499-fed5ee5b-09d3-4376-b0f2-6324fbff0058.png)

**Version**

```shell
argocd: v2.5.4+86b2dde
  BuildDate: 2022-12-06T20:09:11Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.4+86b2dde
  BuildDate: 2022-12-06T20:09:11Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.9.0+g7ceeda6
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
None related
```

**Potential code lines**
* https://github.com/argoproj/argo-cd/blob/0864a0212f1746a4557abdd699a9ada3ebbc5f46/util/app/discovery/discovery.go#L134

It seems the front-end didn't offer the correct parameter when no env settings.
