### ISSUE TITLE
2.6 RC1: App summary path in multi-source app shows revision instead

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11756]
Checklist:

**Describe the bug**

If I look at an Application's summary, the `path` field is populated with the revision link instead of the path.

**To Reproduce**

Use this app: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: elastic
    repoURL: https://github.com/crenshaw-dev/values-file-repo
  - helm:
      valueFiles:
      - $elastic/values-prod.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

View the app in the UI and go to the app summary page.

**Expected behavior**

I think leaving the path field empty would be appropriate for this app. The source has no path, because it's acting only as a source for the values file, and not as sources to be rendered.

**Screenshots**

![image](https://user-images.githubusercontent.com/350466/208517985-dce2c6bb-1201-4a2b-ad8c-0f1061dd706f.png)

**Version**

2.6.0-rc1
