### ISSUE TITLE
Introduce sync windows as a CRD

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11755]
# Summary

Sync windows should be defined as CRDs which are referenceable by projects, apps, and globally.

# Motivation

At Intuit, we've encountered places where we'd like to define a sync window for an application without enforcing that sync window for _all_ apps in that project (or creating a single project per app).

[Others](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1671480462778249) have wanted to enforce a global sync window for a whole company without either using a single project for everything (terrible for security) or duplicating sync windows across a bunch of projects.

It would also be nice to allow for self-service sync windows by non-admins. The ability to update an AppProject is effectively admin access. By separating it into a CRD, admins can allow users to create and update sync windows without granting them full admin capability. 

# Proposal

The CRD:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: SyncWindow
metadata:
  name: my-sync-window
  namespace: argocd  # there's no reason this couldn't also be in other namespaces
spec:
  syncWindows:  # allow multiple for easy transition from projects
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    applications:
      - '*-prod'
    manualSync: true
  - kind: deny
    schedule: '0 22 * * *'
    duration: 1h
    namespaces:
      - default
  - kind: allow
    schedule: '0 23 * * *'
    duration: 1h
    clusters:
      - in-cluster
      - cluster1
```

Reference from project:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
spec:
  syncWindows:
  - ref:  # new field!
      name: my-sync-window
      namespace: argocd
```

Reference from application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  syncWindows:  # new field!
  - ref:
      name: my-sync-window
      namespace: argocd
```

Reference from argocd-cm (global):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  global.syncWindows:
  - ref:
      name: my-sync-window
      namespace: argocd
```

**Comment by gmartin-flexe** [comment]
I've just run into this; our organization wants all developers to limit their deployment activity at the end of the week, but has no interest in any mechanism to do so and would rather each developer go through a modified approval process or to wait until the following week. I wanted to try sync windows to ease the situation. Unfortunately almost all applications are under the same AppProject, and only a select few people have permissions, so I can't apply a sync window for my applications.

Making it possible to define a SyncWindow resource would be great!

**Comment by todaywasawesome** [comment]
I'm interested to do some work here. Tagging myself here @todaywasawesome

**Comment by todaywasawesome** [comment]
@ilia-medvedev-codefresh Check this out. Great feature.

**Comment by agaudreault** [comment]
Three things

- In the Application, Sync Windows should be referenced by using selectors with matchLabels/matchExpression instead of a plain ref by name.

- When used in an Application, a sync windows should not contain `applications`, `namespaces` or `clusters` filter. Since it is 
explicitly selected in the Application, it should always apply to it. 
 
- The sync windows that are applied in the Application are now dynamic. The application will need a view in the UI, to show all the windows that currently applies on the App.


Notes: In the global cm or on the appProject, it could also be by selector or ref. But the namespaces/projects/clusters filters will now apply to all windows of the reference. Another factor that should be evaluated to decide if a selector should be used instead of a ref in the global CM or AppProject is the dynamism aspect.

Alternative suggestion

The CRD:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: SyncWindow
metadata:
  name: my-sync-window
  namespace: argocd  # there's no reason this couldn't also be in other namespaces
  labels:
    name: my-sync-window
    env: prod
spec:
  syncWindows:  # allow multiple
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    manualSync: true
  - kind: deny
    schedule: '0 22 * * *'
    duration: 1h
  - kind: allow
    schedule: '0 23 * * *'
    duration: 1h
```

Reference from project:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
spec:
  syncWindows:
  - ref:  # new field!
      name: my-sync-window
    selectors: # Either ref or selecotrs should be used. Adding both here so it is easier to visualize
      matchLabels:
        name: my-sync-window
    # reference a sync window, but apply some restrictions.
    clusters:
      - in-cluster
      - cluster1
    namespaces:
      - default
    applications:
      - prod*
```

Reference from application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  syncWindows:  # new field!
    selectors:
      matchLabels:
        name: my-sync-window
        env: prod
```

Reference from argocd-cm (global):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  global.syncWindows: |
    - ref: 
        name: my-sync-window
      # reference a sync window, but apply some restrictions.
      clusters:
        - in-cluster
        - cluster1
      namespaces:
        - default
```

**Comment by todaywasawesome** [comment]
Related #17192

**Comment by todaywasawesome** [comment]
Tagging @nerdfacerory to work on this issue

**Comment by crenshaw-dev** [comment]
> Sync Windows should be referenced by using selectors

I'm not sure this is a good idea. This would mean that anyone with write access to any SyncWindow CR could add a label and apply their SyncWindow to some app or project.

**Comment by bkrein-vertex** [comment]
> > Sync Windows should be referenced by using selectors
> 
> I'm not sure this is a good idea. This would mean that anyone with write access to any SyncWindow CR could add a label and apply their SyncWindow to some app or project.

Wouldn't this be limited to what is whitelisted for a given AppProject (eg, namespaces, clusters, etc.)?  In other words you could only add Sync Windows to projects you're a part of.

**Comment by mra89** [comment]
I would love to see this change. Originally posted in slack, we aiming for self service where possible and need teams to be able add a sync window without being able to change anything else with how their project is configured.

https://cloud-native.slack.com/archives/C01TSERG0KZ/p1780080958183449?thread_ts=1780080958.183449&cid=C01TSERG0KZ

**Comment by Mangaal** [comment]
I would like to work on this feature.

Some of the original use cases discussed in this issue are already supported by Argo CD today. For example:

1. A sync window can already target a particular app or multiple apps.
2. Sync windows can already be applied globally through global project inheritance.
3. app, namespace, and cluster matching are already supported.

Here is my proposal inspired by the previous comments and approach

CRD

```
apiVersion: argoproj.io/v1alpha1
kind: SyncWindow
metadata:
  name: my-sync-window
  namespace: argocd
spec:
  windows:
    - kind: allow
      schedule: '10 1 * * *'
      duration: 1h
      applications:
      - '*-prod'
      manualSync: true
    - kind: deny
      schedule: '0 22 * * *'
      timeZone: "Europe/Amsterdam"
      duration: 1h
      namespaces:
      - default
    - kind: allow
      schedule: '0 23 * * *'
      duration: 1h
      clusters:
      - in-cluster
```
Reference from project:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  syncWindowRefs:
    - name: my-sync-window
```
behavior

1.  Any app using the project would be evaluated against the rules in the referenced SyncWindow.
2. When a global project references a SyncWindow, matching child projects would inherit that window through the existing global project inheritance mechanism.
3. A user with permission to manage a SyncWindow would not be able to apply it to any project or app. Attaching the window would still require permission to update the corresponding project.
4. An administrator would perform the project-level configuration once by adding the window reference. After that, a lower-privileged user could be granted permission to update the referenced SyncWindow without receiving full project update permission.

I do not think app-level syncWindowRefs are necessary. The current SyncWindow model already supports targeting a specific app through the app filter. 

I would appreciate any feedback.

**Comment by adityaraj178** [comment]
Hi, I've been working on an implementation for this feature. Here's where I've landed

CRD structure:
```
apiVersion: argoproj.io/v1alpha1
kind: SyncWindow
metadata:
  name: my-sync-window
  namespace: argocd
spec:
  windows:
    - kind: deny
      schedule: "0 22 * * *"
      duration: "8h"
      applications:
        - "*"
      manualSync: false
      timeZone: "Asia/Kolkata"
      description: "Nightly production freeze"
```

Reference from project:
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  syncWindowRefs:
    - ref:
        name: my-sync-window
      applications:
        - "prod-*"
```

Reference from application/ApplicationSet:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  syncWindowRefs:
    - name: my-sync-window
    - selector:
        matchLabels:
          env: prod
```

On the point about app-level refs not being necessary:

> I do not think app-level syncWindowRefs are necessary. The current SyncWindow model already supports targeting a specific app through the app filter.

I'd argue app-level refs are still valuable bcz
 With app-level refs, a team can opt their app into a maintenance window using only applications, update permission. Without it, someone with project-edit access must update either the project refs or the CRD's application filter every time. If 10 apps across 3 projects reference the same window,for temporary adding an app to the SW, app owner can refer to the SW cr from app'spec only and  the CRD stays clean with no growing applications list. Adding/removing an app from the window is a change to the app, not to the shared CRD which might require a separate approval process
