### ISSUE TITLE
2.6 RC1: clicking the Rollback button in a multi-source app causes UI error

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11759]
Checklist:

**Describe the bug**

If I click the History & Rollback button in the UI for a multi-source app, I get a UI error. 

**To Reproduce**

Use this app: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: elastic
    repoURL: https://github.com/crenshaw-dev/values-file-repo
  - helm:
      valueFiles:
      - $elastic/values-prod.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

View the app in the UI and click the History & Rollback button.

**Expected behavior**

Since we don't yet fully support UI actions for multi-source apps, I think the button should be disabled, and the tooltip should describe _why_ it's disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/350466/208525336-53f43e47-c346-4632-b354-b75da275c42d.png)

**Version**

2.6.0-rc1
