### ISSUE TITLE
2.6 RC1: Editing repo URL, revision, or path of a multi-source app fails silently

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11757]
**Describe the bug**

If I edit the repo URL, revision, or path field in a multi-source app's App Details page, those changes just disappear when I hit save. No error message.

**To Reproduce**

Use this app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: elastic
    repoURL: https://github.com/crenshaw-dev/values-file-repo
  - helm:
      valueFiles:
      - $elastic/values-prod.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

**Expected behavior**

Since multi-source apps don't yet have full UI support, I expect those fields to be read-only in edit mode, and I expect there to be a warning icon with a tooltip explaining why they're read-only. The tooltip should mention that the parameters can be manually edited in the Manifest tab.

**Version**

2.6.0-rc1
