### ISSUE TITLE
2.6 RC1: edits in app details Parameters tab create new `source` block

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11758]
**Describe the bug**

If I edit a parameter in a multi-source app's Parameters tab, it populates the `source` field with a directory-type source. This source is ignored because `sources` is present, but it's weird.

**To Reproduce**

Use this app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: elastic
    repoURL: https://github.com/crenshaw-dev/values-file-repo
  - helm:
      valueFiles:
      - $elastic/values-prod.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

Go to the app's Parameters tab and enable recurse for the directory parameters.

**Expected behavior**

Since multi-source apps don't yet have full UI support, I expect this tab to display a message describing why you can edit parameters in the Parameters tab. It should point users to the Manifest tab where they can manually edit parameters.

**Screenshots**

![image](https://user-images.githubusercontent.com/350466/208524450-db9493a3-3e26-4496-9301-89acfe19c828.png)

**Version**

2.6.0-rc1
