### ISSUE TITLE
2.6 RC1: sync status and sync result "More" buttons do nothing in multi-source apps

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11760]
Checklist:

**Describe the bug**

If I look at a multi-source Application's main page, "More" buttons for sync status and sync result do nothing.

**To Reproduce**

Use this app: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: elastic
    repoURL: https://github.com/crenshaw-dev/values-file-repo
  - helm:
      valueFiles:
      - $elastic/values-prod.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

View the app in the UI and go to the app summary page. Click one of the "More" buttons.

**Expected behavior**

I'm not sure what's wrong here. They should work.

**Screenshots**

![image](https://user-images.githubusercontent.com/350466/208525634-5f6ada67-79a5-40e8-899f-265725267ae9.png)

**Version**

2.6.0-rc1
