### ISSUE TITLE
2.6 RC1: source.ref cannot contain special characters even if "-" or "_"

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-cd#11768]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We cannot contain special characters, "-" or "-" in `source.ref` , although the error message suggests we can.

**To Reproduce**

Deploy following manifest.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: value-repo
    repoURL: https://github.com/toyamagu-2021/argocd-multirepo-test
  - helm:
       valueFiles:
        - $value-repo/env/dev/values.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

**Expected behavior**

We can use "-" or "_" in `source.ref` (?).

**Screenshots**

![image](https://user-images.githubusercontent.com/83329336/208654638-323b1be3-019a-4202-8f0c-8c4d43d7f891.png)

**Version**

```shell
argocd: v2.6.0-rc1+81e40d5
  BuildDate: 2022-12-19T17:10:37Z
  GitCommit: 81e40d53fe8eee50b00ab38c4b07b34b3dcd6d25
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.0-rc1+81e40d5
  BuildDate: 2022-12-19T16:48:52Z
  GitCommit: 81e40d53fe8eee50b00ab38c4b07b34b3dcd6d25
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

`argocd app sync test`

```
Events:
  Type     Reason              Age   From                           Message
  ----     ------              ----  ----                           -------
  Normal   ResourceUpdated     18s   argocd-application-controller  Updated sync status:  -> Unknown
  Normal   ResourceUpdated     18s   argocd-application-controller  Updated health status:  -> Healthy
  Normal   ResourceUpdated     18s   argocd-application-controller  Updated sync status:  -> Unknown
  Normal   ResourceUpdated     18s   argocd-application-controller  Updated health status:  -> Healthy
  Normal   OperationStarted    13s   argocd-server                  admin initiated sync to  (61e585fdb703cd2e70db3bdaa0bce353a8cd6194)
  Warning  OperationCompleted  13s   argocd-application-controller  Sync operation to  failed: ComparisonError: failed to get ref sources: source.ref value-repo cannot contain any special characters except '_' and '-'
```

**Considerations**

A Regrep does not consistent with error message.
https://github.com/argoproj/argo-cd/blob/1d885b7eea8c0e9d2bc8dc1e9e0e6a08e32d0363/util/argo/argo.go#L351
