### ISSUE TITLE
`ARGOCD_APPLICATIONSET_ENABLE_PROGRESSIVE_ROLLOUTS` missing from `v2.6.0-rc1` install.yaml

### ISSUE THREAD

**Issue by morey-tech** [argoproj/argo-cd#11761]
The docs in `v2.6.0-rc1` mention using `applicationsetcontroller.enable.progressive.rollouts` in `argocd-cmd-params-cm` to enable the feature. This doesn't seem to work when using the `manifests/install.yaml`. The `argocd-applicationset-controller` seems to be missing the `env[].valueFrom` for the `ARGOCD_APPLICATIONSET_ENABLE_PROGRESSIVE_ROLLOUTS` env var.
https://github.com/argoproj/argo-cd/blob/1ad91259bd25e0de80890c9bf913847ed3189e4e/docs/operator-manual/applicationset/Progressive-Rollouts.md?plain=1#L17

https://github.com/argoproj/argo-cd/blob/81e40d53fe8eee50b00ab38c4b07b34b3dcd6d25/manifests/install.yaml#LL15815C12-L15815C12

Does it look like this might be missing from all of the install manifests?

Would it make sense to update `ARGOCD_APPLICATIONSET_ENABLE_PROGRESSIVE_ROLLOUTS` to `ARGOCD_APPLICATIONSET_CONTROLLER_ENABLE_PROGRESSIVE_ROLLOUTS` to match current syntax (adding `_CONTROLLER`) used in the existing `ARGOCD_APPLICATIONSET_CONTROLLER_ENABLE_LEADER_ELECTION`? 

The proposal, add this block to the install manifests:
```
        - name: ARGOCD_APPLICATIONSET_ENABLE_PROGRESSIVE_ROLLOUTS
          valueFrom:
            configMapKeyRef:
              key: applicationsetcontroller.enable.progressive.rollouts
              name: argocd-cmd-params-cm
              optional: true
```

Looking for confirmation that this is the problem (and I'm not missing something), then I'll happily create the PR if correct.
