### ISSUE TITLE
Additional template values to GitGenerator.

### ISSUE THREAD

**Issue by beatrausch** [argoproj/argo-cd#11766]
# Summary

Add support for additional template values to GitGenerator. 

# Motivation

Other generators like the Cluster or List generator allow to specify additional values that can be used in the template part. E.g. with git directory generator it is only possible to use path parts as input for the template rendering. 

# Proposal

Add an additional values attribute to the Git generator:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj/argo-cd.git
      revision: HEAD
      directories:
      - path: applicationset/examples/git-generator-directory/excludes/cluster-addons/*
      values:  
        overlay: stable
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{path}}/{{values.overlay}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
```
