### ISSUE TITLE
2.6 RC1: ArgoCD shouldn't return not generating manifests as path and chart fields are empty when one of two sources do not include path or chart

### ISSUE THREAD

**Issue by lukas-unity** [argoproj/argo-cd#11770]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When application manifest is applied and later synced logs from `argocd-repo-server` return 
```
"time=\"2022-12-20T10:57:41Z\" level=warning msg=\"not generating manifests as path and chart fields are empty\" source=\"&ApplicationSource{RepoURL:git@github.com:myrepo/helm-test.git,Path:,TargetRevision:lukas-testing,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:values,}\"\n"
```

**To Reproduce**

Apply application manifest that has 2 sources

*application.yaml*
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-vulture
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc/
    namespace: lukas
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: tempo-vulture
    targetRevision: 0.2.1
    helm:
      valueFiles:
      - $values/tempo-vulture.yaml
  - repoURL: 'git@github.com:myrepo/helm-test.git'
    targetRevision: lukas-testing
    ref: values
```
*tempo-vulture.yaml*
```yaml
replicas:2
```

and perform `Sync`

**Expected behavior**

this shouldn't be happening as second source only specifies values in the git repo.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.

```sh
argocd-server: v2.6.0-rc1+81e40d5
  BuildDate: 2022-12-19T16:48:52Z
  GitCommit: 81e40d53fe8eee50b00ab38c4b07b34b3dcd6d25
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
**Logs**

```
"time=\"2022-12-20T10:57:41Z\" level=warning msg=\"not generating manifests as path and chart fields are empty\" source=\"&ApplicationSource{RepoURL:git@github.com:myrepo/helm-test.git,Path:,TargetRevision:lukas-testing,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:values,}\"\n"
```
