### ISSUE TITLE
kustomize images field is not recognized

### ISSUE THREAD

**Issue by fikriauliya** [argoproj/argo-cd#1180]
I run `v0.11.2` and got the following error:

```
CONDITION         MESSAGE
InvalidSpecError  Unable to generate manifests in frontend/overlays/production: rpc error: code = Unknown desc = Error: loadResMapFromBasesAndResources: couldn't make target for ../../base: json: unknown field "images
```

It points to the following kustomize 2.0.1 config (which is valid on my local kustomize) :
```
apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../common
resources:
  - deployment.yaml
images:
  - name: gcr.io/hijup-production/github-hijup-frontend
    newtag: latest
```

If the `images` field is deleted, ArgoCD can successfully run.

**Comment by jessesuen** [comment]
v0.11.2 does not support kustomize 2. We've added support for in this coming v0.12 release (this week)

**Comment by fikriauliya** [comment]
Understood. As of now, my workaround is adding this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
      - name: custom-tools
        emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
      - name: download-tools
        image: byrnedo/alpine-curl:0.1.7
        command: [sh, -c]
        args:
        - opsys=linux &&
          curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |
          grep browser_download |
          grep $opsys |
          cut -d '"' -f 4 |
          xargs curl -O -L &&
          mv kustomize_*_${opsys}_amd64 kustomize &&
          chmod uog+x kustomize && 
          mv kustomize /custom-tools/
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
```
