### ISSUE TITLE
Allow for multiple sources while using custom CMPs

### ISSUE THREAD

**Issue by zenitraM** [argoproj/argo-cd#11814]
# Summary

Multi-source apps supported in 2.6 currently only allow passing of configuration values in the shape of Helm chart valueFiles with the built-in Helm support, as in:
```yaml
  - repoURL: 'https://github.com/elastic/helm-charts'
    targetRevision: v8.5.1
    ref: elastic
  - repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - $elastic/charts/elasticsearch/values.yaml
```

Similar support could be implemented so that file references from other repositories can be passed as inputs to be evaluated when using a custom CMP.

# Motivation

This would apply to any plugin desiring to combine two repository inputs, but the most obvious use case is using [argocd-vault-plugin](https://github.com/argoproj-labs/argocd-vault-plugin/) with a Helm chart, while obtaining the value files from a separate repository. As the Helm evaluation in this case is done in the custom CMP and out-of-band to the built-in Helm support, the implemented interpolation as part of valueFiles will not work. 

# Proposal

A possibility I can think of could be that, using parameterized CMPs, an extra parameter type could be a path to a file or a folder in a different repo, or a reference to another repo entirely.
This path could be translated into a real path by the repo-server, with the repository local path being exposed as an environment variable to the CMP plugin to consume as desired.
