### ISSUE TITLE
SharedResourceWarning when using same helm chart

### ISSUE THREAD

**Issue by mkcc6** [argoproj/argo-cd#11838]
**Describe the bug**
I deployed 3 apps using either argocd application set or application CRD. When I point all the application CRD to the same git repository and directory, it shows `SharedResourceWarning` , `xxx is part of applications  xxx`. If I sync the app, this error is gone for this app, however, the error shows in the other apps. If I enable auto sync, some of the resources of the app will be prune and replaced by resource of other apps. I have tried to use `annotation+label` tracking method but no luck. I've also tested even my app contains only 1 configmap, this issue still happens. 

**To Reproduce**
1. Inside a git repository, create a folder
2. I used helm chart format with only 1 configmap.yaml inside
```
├── ...
├── test-app
│   ├── templates
|   |   ├── configmap.yaml 
│   ├── chart.yaml
│   └── values.yaml
└── ...
```
3. Create 3 applications/ application set and deploy it
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    appId: test-app-[ID]
    cluster: local-cluster
    env: local
  name: test-app-[ID]
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test-app
    repoURL: [git_repo]
    targetRevision: HEAD
  syncPolicy: {}
``` 
4. Once you deploy it 1 by 1, you will see the `shared resources warning` 

**Expected behavior**
No warning and will not overwrite the resource of other apps when auto sync is enabled. 

**Screenshots**
<img width="798" alt="1" src="https://user-images.githubusercontent.com/99026397/209750942-84285ee3-1190-45ee-ba32-c953f92c0f44.png">
<img width="730" alt="2" src="https://user-images.githubusercontent.com/99026397/209750960-7b3db043-513b-4fa0-8db6-0f616e28928b.png">

**Version**

```shell
argocd@argocd-server-7df4c4dd99-5d6mg:~$ argocd version
argocd: v2.5.1+504da42
  BuildDate: 2022-11-01T21:14:33Z
  GitCommit: 504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/arm64
```

**Logs**
From application controller. 
```
time="2022-12-28T02:37:24Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-12-28T02:37:24Z\",\"message\":\"ConfigMap/test-configmap is part of applications argocd/test-app-1 and test-app-2\",\"type\":\"SharedResourceWarning\"}]}}" application=argocd/test-app-1
time="2022-12-28T02:40:20Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-12-28T02:40:19Z\",\"message\":\"ConfigMap/test-configmap is part of applications argocd/test-app-3 and test-app-2\",\"type\":\"SharedResourceWarning\"}]}}" application=argocd/test-app-3
```

**Comment by blakepettersson** [comment]
If all those applications are pointing to the same namespace and server, that's expected behaviour. What do you want to achieve?

**Comment by mkcc6** [comment]
we have 2 use cases:
1. We deploy a same set of apps to multiple clusters with 1 ArgoCD. They all point to the same git repo and same k8s manifest, override by different yaml. In this case, sometimes app value of a cluster is replaced by another cluster
2. We have 1 api gateway k8s manifest, and we deploy multiple variant of api gateway by overriding different values.yaml. For example, we create 5 CRD - Applications with different values-[name].yaml. In this case, the resources of these api gateway will get replaced/overridden by each other.

**Comment by blakepettersson** [comment]
As long as these different applications are pointing to a separate cluster url, those use-cases should work.

```yaml
# per cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    appId: test-app-[ID]
    cluster: local-cluster
    env: local
  name: test-app-[ID]
  namespace: argocd
spec:
  destination:
    namespace: default
    server: # this needs to be different per app
  project: default
  source:
    path: test-app
    repoURL: [git_repo]
    targetRevision: HEAD
  syncPolicy: {}
```

Alternatively if you want to install all the apps on the same cluster, you'll need to differentiate per namespace

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    appId: test-app-[ID]
    cluster: local-cluster
    env: local
  name: test-app-[ID]
  namespace: argocd
spec:
  destination:
    namespace: # this needs to differ if you want to install multiple apps containing the same manifests to the same cluster
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test-app
    repoURL: [git_repo]
    targetRevision: HEAD
  syncPolicy: {}
```
