### ISSUE TITLE
omitted clusters field in excludedResources should match all clusters

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1183]
Current implementation of excludedResources requires `clusters` to be specified, even if it is a `*`:
```yaml
  excludedResources: |
    - apiGroups:
      - repositories.stash.appscode.com
      kinds:
      - Snapshot
      clusters:
      - '*'
```

I think this should be analogous to `resourceNames` in RBAC rules, where it is optional. If omitted, it implies all resources of that kind. Especially since restriction by clusters is not going to be a common use case.

```yaml
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["my-configmap"]
  verbs: ["update", "get"]
```

`apiGroups` and `kinds` remain as mandatory fields.
