### ISSUE TITLE
Resource argoproj.io/AppProject/argocd/myproj appeared 6 times among application resources.

### ISSUE THREAD

**Issue by wd** [argoproj/argo-cd#11843]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have a root app to manage other applications in Argo. We receive this warning from this app. 
```
Resource argoproj.io/AppProject/argocd/myproj appeared 6 times among application resources.
```

Our manifests were built through kustomize, so I believe it is impossible to have argoproj.io/AppProject/argocd/myproj in the build result multiple times because kustomize will error out. 

**To Reproduce**

**Expected behavior**

I don't know what is wrong from our setup. 

**Screenshots**

**Version**

```shell
helm chart: argo-cd-5.9.1
argocd: v2.5.0
```

**Logs**

**Comment by wd** [comment]
I also have tried to replace the manifests [here](https://github.com/argoproj/argo-cd/blob/master/controller/state_test.go#L258) with ours that were generated from the kustomize command. 
And I can't see the same issue from this test.

**Comment by wd** [comment]
I have 6 destinations for this project. 
```
spec:
  destinations:
  - namespace: staging-1
    server: https://kubernetes.default.svc
  - namespace: staging-2
    server: https://kubernetes.default.svc
  - namespace: staging-3
    server: https://kubernetes.default.svc
  - namespace: staging-4
    server: https://kubernetes.default.svc
  - namespace: staging-5
    server: https://kubernetes.default.svc
  - namespace: staging-6
    server: https://kubernetes.default.svc
```
