### ISSUE TITLE
RespectIgnoreDifferences in syncOptions not working when jqPathExpressions is defined with json array and keys of the items in the array

### ISSUE THREAD

**Issue by umi0410** [argoproj/argo-cd#11876]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I specify `ignoreDifferences` field in an ArgoCD Application with `jqPathExpressions` containing `[]`, the whole configuration in the array `[]` is ignored when it is synced.

**To Reproduce**

1. Create a namespace a namespace to reproduce the bug. (e.g. `ignore-bug`)
    ```shell
    kubectl create ns ignore-bug
    ```
3. Create an Application.
    I'll use a helm chart in [argocd-example-apps](https://github.com/argoproj/argocd-example-apps)
    And please set as the following.
      * To set ignoreDifferences with jqPathExpressions using `[]`. e.g. `spec.template.spec.containers[].image`
      * To set `RespectIgnoreDifferences=true` in syncOptions
    ```yaml
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      namespace: argocd
      name: ignore-bug
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: master
        path: helm-guestbook
        helm:
          parameters:
          - name: image.tag
            value: "0.1"
          - name: image.pullPolicy
            value: IfNotPresent
      destination:
        name: in-cluster
        namespace: ignore-bug
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jqPathExpressions:
        - .spec.template.spec.containers[].image
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
    ```
    <img width="1003" alt="image" src="https://user-images.githubusercontent.com/33250725/210555688-e80a0eef-3179-434f-9baf-75460428f8d4.png">

    You will see the application and please sync it.
    <img width="1781" alt="image" src="https://user-images.githubusercontent.com/33250725/210555616-77366274-36a2-4d08-a617-01c994b48020.png">
3. Update `image.PullPolicy` variable in the Application.
    ```yaml
    - name: image.pullPolicy
      value: Always # it was "IfPresent" before
    ```
    <img width="1701" alt="image" src="https://user-images.githubusercontent.com/33250725/210556367-5135444c-a7b0-4e0c-a3c0-55fb3e0ba2f2.png">
    The application will become out of sync because we updated the imagePullPolicy of the container.
4. Sync the application.
    This is exactly the problem. Even if you try to sync it, the change will be ignored. I guess there are some bugs in `RespectIgnoreDifferences` when `jqPathExpressions` has an array and a key inside the array

    
**Expected behavior**

**Screenshots**

**Version**

```shell
argocd: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:10:26Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

There is a fatal log but I think it doesn't matter. All components are deployed with version 2.5.5

**Logs**

I wasn't able to find any useful logs. It seemed just same as the logs of other normal synchronizations.
