### ISSUE TITLE
Declarative Secrets with Apps in Any Namespace

### ISSUE THREAD

**Issue by patrickbardo** [argoproj/argo-cd#11874]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the apps in any namespace setup, to declaratively setup private repositories using secrets, ArgoCD will not see secrets in other namespaces. 

**To Reproduce**

Apply below secret where the secret is not in the same namespace argocd is installed. Argo will not find the repository connection. Change the namespace to argocd, and reapply, and it will be found.

```
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: any-other-namespace
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:org/your-repo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
```

**Expected behavior**

ArgoCD will find secrets in other namespaces when the `argocd.argoproj.io/secret-type: repository ` label is set.

**Version**

```shell
argocd: v2.4.15+05acf7a.dirty
  BuildDate: 2022-10-17T22:52:44Z
  GitCommit: 05acf7a52e377eacfee29c68e3e5e79a172ea013
  GitTreeState: dirty
  GoVersion: go1.19.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.5.0+b895da4
```
