### ISSUE TITLE
Add support for patching Kustomize values for application/applicationset yaml to work more like helm values

### ISSUE THREAD

**Issue by ciantfv456** [argoproj/argo-cd#11906]
Why can't Kustomize values be patched like helm values
```yaml
spec:
  sources:
    - repoURL: https://github.com/helm/charts
      targetRevision: master
      path: foo/app
      kustomize:
        patch: |-
          - op: add
            path: /spec/foo
            value: bar
```
Or something like that.

Use case: 
Having an applicationset with a git generator that will change the application values by the generators values
