### ISSUE TITLE
Applicationset plugin sidecar parameters null

### ISSUE THREAD

**Issue by nbjohnson** [argoproj/argo-cd#11900]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am migrating from the old plugin configmap to the new plugin sidecar. I am getting `ARGOCD_APP_PARAMS` env var is `null` and the individual `PARAM_` env vars are also not present

**To Reproduce**
plugin config
```
parameters:
  static:
    - name: test-var1
      title: test-var1
      required: false
      itemType: "string"
    - name: test-var2
      title: test-var2
      required: false
      itemType: "string"
```
applicationset config
```
kind: ApplicationSet
spec:
  template:
    metadata:
      name: "test-app"
    spec:
      project: test
      source:
        ...
        plugin:
          name: testplugin-v1.0
          env: # this shows up fine like the legacy plugin method
            - name: TEST
              value: test
          parameters:
            - name: test-var1
              string: "testparam1"
           - name: test-var2
             string: "testparam2"
```

**Expected behavior**

 After creating the sidecar with its config defining parameters, I set the parameters in my applicationset config but the `ARGOCD_APP_PARAMS` env var is `null` when the plugin is run. The individual `PARAM_` env vars are also not present. If I set an `env` for the plugin in my applicationset config that shows up properly. Is there something I may be doing wrong in my configs? Or has anyone else experienced this null behavior, I have been trying to follow the latest plugin docs.

**Screenshots**

**Version**

```
v2.6.0-rc2
```

**Logs**

```
ARGOCD_APP_PARAMETERS: null
```
