### ISSUE TITLE
UI doesn't display helm parameters if `valuesFiles` is an empty list

### ISSUE THREAD

**Issue by dhirschfeld** [argoproj/argo-cd#11947]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When specifying an empty `valuesFiles` the UI no longer shows the parameters correctly:
```
❯ kubectl -n argocd get Application/data-clone -o yaml | rg valueFiles
      valueFiles: []
```

![image](https://user-images.githubusercontent.com/107382673/211740779-0f21c658-d06a-4cda-af19-7b641fca2b6a.png)

---

When specifying  `valueFiles: [values.yaml]` the UI displays the expected parameters:

```
❯ kubectl -n argocd get Application/data-clone -o yaml | rg valueFiles -A2
      valueFiles:
      - values.yaml
    path: build/helm/data_clone
--
          valueFiles:
          - values.yaml
        path: build/helm/data_clone
```

![image](https://user-images.githubusercontent.com/107382673/211750684-29fccb34-d9d8-409b-8a0c-e3f6050d2833.png)

----

I'm opening an issue because I'm 99% sure that `values.yaml` was previously injected automatically. 

**To Reproduce**

Specify an empty `valuesFile`

**Expected behavior**

The default values from the `values.yaml` file are used / shown in the UI

**Version**

```shell
❯ argocd version
argocd: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:34:36Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.4+86b2dde
  BuildDate: 2022-12-06T19:46:25Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```
