### ISSUE TITLE
N:1 left join for Merge generator

### ISSUE THREAD

**Issue by sergej-laufer** [argoproj/argo-cd#11952]
I was expecting the merge generator to work like a SQL left join. But it does not allow a N:1 mapping, where the base has a non unique key.

In the following example there are multiple clusters for dev, stg and prod `env` label. I would expect that all clusters would merge with the list generator, that has only one matching entry for each env. Instead I get the error `the parameters from a generator were not unique by the given mergeKeys, Merge requires all param sets to be unique.` 

```yaml
  generators:
    - merge:
        mergeKeys: [metadata.labels.env]
        generators:
          - clusters: {}
          - list: {elements: [{metadata.labels.env: dev, values.gitref: 6dba68d59f8679479ba1690336d8d8775c6057ac },
                              {metadata.labels.env: stg, values.gitref: DEVOPS-12000-argocd},
                              {metadata.labels.env: prod, values.gitref: main}]}
```

A work around is to combine a matrix and merge generator.

```yaml
  generators:
    - matrix:
        generators:
          - clusters: {}
          - merge:
              mergeKeys: [env]
              generators:
                - list: {elements: [{env: '{{ "{{metadata.labels.env}}" }}' }]}
                - list: {elements: [{env: dev, values.gitref: 4b514e8e9f9942c296e21e448da5691c5b4f4310 },
                                    {env: stg, values.gitref: DEVOPS-12000-argocd},
                                    {env: prod, values.gitref: main}]}
```

I dont see a reason to forbid non unique keys on the base generator. Allowing non unique key for the base generator would make the Merge generator more useful and would simplify the configuration for usecases like in the example.

**Comment by crenshaw-dev** [comment]
I think other merge "modes" would be really useful.

How would you feel about something like this?

```yaml
generators:
- merge:
  mode: left-join
```
