### ISSUE TITLE
URL parsing failed with OCI helm application

### ISSUE THREAD

**Issue by michalziobro** [argoproj/argo-cd#11968]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Created a sample application using helm from GHCR OCI. When I navigate to app in UI it throws `Error: URL parsing failed.`
Works ok with `v2.5.6`

**To Reproduce**

Create app with manifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: sample-project
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  source:
      repoURL: ghcr.io/energywebfoundation
      targetRevision: 0.1.1
      chart: sample-go-app-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
```

Navigate to app in UI

**Expected behavior**
App UI opens normally

**Screenshots**
![image](https://user-images.githubusercontent.com/38351902/212057961-464571f2-7ba9-4a69-9fbe-aec8478eb395.png)

![image](https://user-images.githubusercontent.com/38351902/212058694-d01644d0-582e-420a-904c-2d02683af34d.png)

**Version**

```shell
v2.6.0-rc2
```

**Logs**

```
Paste any relevant application logs here.
```
