### ISSUE TITLE
Ignore Owner References

### ISSUE THREAD

**Issue by spjmurray** [argoproj/argo-cd#11972]
# Summary

Provide a way to ignore owner references, and force ArgoCD to delete things.

# Motivation

Related to https://github.com/kubernetes-sigs/cluster-api/issues/7913.  What we are seeing here is cluster-api adding its own owner references to resources managed by Argo.  When it comes to deletion, it's not generated by the Helm template any more, but Argo thinks it's an implicitly created by cluster-api because of the owner references CAPI has added.  Basically I cannot delete things unless I do it manually.

# Proposal

One idea to handle naughty apps is to have Argo spot the tracking ID, and the fact there is no requested resource any more, and just ignore owners, it created it and has all the power here.

**Comment by spjmurray** [comment]
Another proposal now I consider it, is an explicit annotation that we can attach to a resource that says "you own this, delete it if not backed by helm template".  Probably a better solution than just considering the tracking ID implicitly as  I did see something historically about why tracking IDs came about in the first place due to inheritance.

**Comment by spjmurray** [comment]
Added a potential--and remarkably small--PoC fix for consideration.

**Comment by jannfis** [comment]
Thanks for bringing this up.

Probably we need to discuss general pruning behavior and how Argo CD handles owner references. I think the initial assumption was, that a resource would never have an owner outside of what the Argo CD application manages (think Deployment -> ReplicaSet, etc).

While it most likely contradicts with how Argo CD views things right now (e.g. that it "owns" a resource it has reconciled from Git to a cluster), I think it's perfectly fine for some other controller to claim ownership over a resource - I guess that's why there can be more than one owner references for any resource in the first place. I'd assume once CAPI puts an owner reference on the resource, Argo CD would also ignore the resource for changes originating on the cluster, and not enter an OutOfSync state when the resource change on the cluster?

Maybe a sync option on the resource, as implemented in your PoC, is a proper way to tell Argo CD to still let it handle a resource despite it having one or more owner references.

However, it sounds like it would need a little more discussion amongst contributors and maintainers on how we can support this use case. I'd like to bring this to the next contributor's meeting, happening weekly each Thursday at 4:15pm UTC, so that we'll find a good solution. You are of course invited to join, see https://github.com/argoproj/argo-cd#contribution-discussion-and-support for more details.

**Comment by spjmurray** [comment]
Yeah, my train doesn't leave London until 7, so I should be able to hop on. Thanks for having a look

**Comment by spjmurray** [comment]
Note this looks like a dupe of #4764 so linking

Did you come to any conclusions @jannfis I missed the important bit of that meeting due to Zoom (and broken library deps in dpkg!)

**Comment by jaideepr97** [comment]
There's another potential approach suggested to this problem in https://github.com/argoproj/argo-cd/issues/12210

**Comment by spjmurray** [comment]
Ah yes, I'm aware of Matt's approach, that's also good as far as I'm concerned.  While this is less dangerous, the other way does force people to write their controllers correctly (which is a win for the whole world), lest their stuff gets deleted :)

**Comment by jannfis** [comment]
@spjmurray Sorry, I forgot to update this issue eventually. So we agreed that we should support the use case when another controller sets an owner reference to a resource synced with Argo CD. I think there was also consensus that the solution you propose in your PoC looks good, and there's an item on my todo list to take it for a test drive. Obviously, I have not come around yet to do it.

**Comment by spjmurray** [comment]
Cool.  If there's anything you want me to do in the mean time just ask e.g. unit tests, technical documentation, etc.

**Comment by mkjpryor** [comment]
This is where I eventually landed as a solution: https://github.com/argoproj/gitops-engine/pull/503

I’m running this in a custom build now, and it works perfectly for my use case.

**Comment by aliok** [comment]
https://github.com/argoproj/gitops-engine/pull/771 might be the fix for this problem

**Comment by dprotaso** [comment]
The PR has now moved to https://github.com/argoproj/argo-cd/pull/24814

**Comment by dprotaso** [comment]
So I'm doing some testing with the latest argo @ HEAD - and I'm seeing without my PR changes ArgoCD is able to delete Resources with OwnerReferences(controller=true).

@spjmurray @aliok what version of ArgoCD are you using?

**Comment by dprotaso** [comment]
Hmm.. I'm not deploying stuff with Helm though

**Comment by Breee** [comment]
> So I'm doing some testing with the latest argo @ HEAD - and I'm seeing without my PR changes ArgoCD is able to delete Resources with OwnerReferences(controller=true).
> 
> [@spjmurray](https://github.com/spjmurray) [@aliok](https://github.com/aliok) what version of ArgoCD are you using?

I run 
```
{
    "Version": "v3.2.2+8d0dde1",
    "BuildDate": "2025-12-18T09:52:14Z",
    "GitCommit": "8d0dde1388a92ca4dc0daacec5707f4378b9d06a",
    "GitTreeState": "clean",
    "GoVersion": "go1.25.0",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.7.0 2025-06-28T07:00:07Z",
    "HelmVersion": "v3.18.4+gd80839c",
    "KubectlVersion": "v0.34.0",
    "JsonnetVersion": "v0.21.0"
}
``` 

We are using Helm + Cluster API resources. These kind of resources are no longer part of the referenced helmchart, but still there: 

```
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: santa
  name: santa-1.34.2-325ec064-1942-worker
  namespace: cluster-santa
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta2
      kind: Cluster
      name: santa
      uid: 7f413370-07e6-487e-ac60-bff39b12d315
```

Apps look similar to this: 

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: santa
  namespace: argocd-apps
spec:
  project: default
  destination:
    namespace: cluster-santa
    name: some-cluster
  sources:
    - ref: values
      repoURL: https://myvalues
      targetRevision: HEAD
    - helm:
        releaseName: santa
        valueFiles:
          - $values/clusters/santa/values.yaml
      chart: capi-cluster
      repoURL: https://myhelmrepo
      targetRevision: 2.0.23
    - ref: proxies
      repoURL: https://myrepo
      targetRevision: HEAD
      path: proxies
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
      limit: 1
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
```
