### ISSUE TITLE
Sql user calling every minute by ArgoCD.

### ISSUE THREAD

**Issue by rafaeltovargarrido** [argoproj/argo-cd#11975]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
We have config connector in our gke cluster to handle all the gcp resources in our infra, we use this kind **sqlusers.sql.cnrm.cloud.google.com** to create SQL user for our database. The issue is argo is calling the creation of the user every minute as you can see in the image I posted. 

**To Reproduce**
```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    environment: oat-dev
    part-of: datastore
    tier: database
  name: 9076c2ecaf2fccec3a719e88ccbb01a4
  namespace: oat-dev
spec:
  host: '%'
  instanceRef:
    external: instance-id
  password:
    valueFrom:
      secretKeyRef:
        key: password
        name: ds-gcp-cloud-sql-ds-secret

```

**Expected behavior**
Argo create the user and that is all.

**Screenshots**
![image](https://user-images.githubusercontent.com/14241603/212323436-d6afe519-1934-45b4-9de9-374b64b7befe.png)

**Version**

```shell
Paste the output from `argocd version` here.
```
argocd: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:34:36Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:34:36Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0

**Logs**

```
Paste any relevant application logs here.
```
