### ISSUE TITLE
Config Management plugin using side car approach application discovery fails - repository /tmp/_argocd-repo/7d8ad6bc-6512-4567-9712-ade75590f20b/apps/keda is not the match because error receiving stream response: rpc error: code = Unknown desc = match repository error

### ISSUE THREAD

**Issue by Akshaya-T** [argoproj/argo-cd#11978]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

<img width="848" alt="Screenshot 2023-01-13 at 7 26 21 PM" src="https://user-images.githubusercontent.com/39328208/212336552-3fb32868-5616-433f-8876-f61d41c45adb.png">

**Use case:** 
- 2 git repositories named kube and dev-repo.
- The plugin discovery has to match applications from kube repo and not from dev-repo.

**What I have done so far?** 

Migrated the Config Management Plugin (CMP) from Config maps to side car approach. Everything works fine, But I need to discover applications from a certain path and not others, so Tried using discover.find.command but it fails with the following error.

Config files:
```
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      init:
        command: [python3]
        args: ['../../render.py']
      generate:
        command: [kustomize]
        args: [build, --enable-helm, --enable-alpha-plugins]
      discover:
        find:
          command: ["bash", "-c", "pwd | grep apps"]
```
   
helm repo server - values.yaml 
```  
repoServer:
  extraContainers: 
  - name: cmp
    command: [/var/run/argocd/argocd-cmp-server]
    image: quay.io/argoproj/argocd:v2.5.5
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: plugin.yaml
        name: cmp-plugin
      - mountPath: /tmp
        name: cmp-tmp
  volumes: 
   - name: cmp-plugin
     configMap:
       name: kube-kustomize-helm-plugin
   - name: cmp-tmp
     emptyDir: {}
```

**To Reproduce**

- Deploy 2.5.5 argocd version
- Deploy applications as mentioned with the above directory structure.

**Expected behavior**

To Discover applications from kube repo and not from dev-repo. But it fails with the error.

**Screenshots**
<img width="1789" alt="Screenshot 2023-01-13 at 7 10 08 PM" src="https://user-images.githubusercontent.com/39328208/212333400-54b55d5e-ba4a-4dea-a295-f6a76cb5ed12.png">

**Version**
2.5.5

```shell
  argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:44:59Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

```
{"CWE":775,"level":"error","msg":"repository /tmp/_argocd-repo/7d8ad6bc-6512-4567-9712-ade75590f20b/apps/keda is not the match because error receiving stream response: rpc error: code = Unknown desc = match repository error: error running find command: `bash -c pwd | grep apps` failed exit status 1","security":2,"time":"2023-01-13T13:23:28Z"}

{"error":"plugin sidecar failed. Couldn't find cmp-server plugin supporting repository .apps/keda","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2023-01-13T13:23:25Z","grpc.time_ms":3197.044,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2023-01-13T13:23:28Z"}
```
