### ISSUE TITLE
2.6 RC2: ApplicationSet and Application Rollback won't work when using custom plugin

### ISSUE THREAD

**Issue by gabrielfsousa** [argoproj/argo-cd#11977]
This is my ApplicationSet manifest

```
...
spec:
      project: infrastructure
      source:
        repoURL: git@ssh.dev.azure.com:v3/ / /gitops-base
        targetRevision: HEAD
        path: "infrastructure/weave-scope"
        plugin:
          env:
            - name: CLUSTER
              value: '{{targets.path[3]}}'
            - name: ENV
              value: '{{targets.path[4]}}'
            - name: APPNS
              value: '{{targets.path[5]}}'
...
```
i pass variables to the script, when executing Rollback this variables are empty
