### ISSUE TITLE
argocd dex server has "Invalid Credentials" for login with ldap

### ISSUE THREAD

**Issue by arminbiklari** [argoproj/argo-cd#11988]
### Discussed in https://github.com/argoproj/argo-cd/discussions/11987

<div type='discussions-op-text'>

<sup>Originally posted by **arminbiklari** January 15, 2023</sup>
I need help for configuring Ldap for my argocd 

I configured dex.config in argocd-cm as follows:
```
data:
  dex.config: |
    connectors:
    - config:
        host: 172.20.20.10:1389
        insecureNoSSL: true
        insecureSkipVerify: true
        bindDN: "CN=DevOps Ldap,OU=SERVICES,OU=Units,DC=mydomain,DC=local"
        bindPW: "password"
        userSearch:
          baseDN: "OU=Units,DC=zooket,DC=local"
          filter: ""
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: name
          preferredUsernameAttr: uid
        groupSearch:
          baseDN: "OU=Units,DC=mydomain,DC=local"
          filter: "(|(objectClass=posixGroup)(objectClass=groupOfNames))"
          userMatchers:
          - userAttr: uid
            groupAttr: memberUid
          - userAttr: DN
            groupAttr: member
          nameAttr: name
      type: ldap
      id: ldap
      name: domainname
  url: https://argo.stage.snpx.dev
```

url is Argo CD server's externally base URL,

when i enter my ldap credentials in 

> https://argo.stage.snpx.dev/api/dex/auth/ldap/login?back=&state=agqkbsntrj4zkbh5sclqgwir3

th argocd-dex-server shows this error:
`time="2023-01-15T12:30:11Z" level=error msg="Failed to login user: ldap: initial bind for user \"CN=DevOps Ldap,OU=SERVICES,OU=Units,DC=mydomain,DC=local\" failed: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C090436, comment: AcceptSecurityContext error, data 52e, v4f7c\x00"`

**_the question is Where did I go wrong?_**

</div>
