### ISSUE TITLE
ApplicationSet template is missing toYaml/fromYaml functions

### ISSUE THREAD

**Issue by alexbde** [argoproj/argo-cd#11993]
We do have an use case which I would have thought is a pretty common one: we have an application Helm chart and multiple locations with application configurations. E.g., a git repository with general/common configurations (valid for all stages) & another git repository with stage-specific configurations.

Today we’re using the app-of-apps pattern with Helm charts to read & merge those configs/values.yaml files. Minimal example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: ...
spec:
  source:
    helm:
      values: |
        {{- .Values.stage | merge .Values.general | toYaml | nindent 8 }}
...
```

We tried to move to ApplicationSet instead of app-of-apps because it looks like the securer and more future-proof concept. We were very happy we can now use Go template with Argo CD >= 2.5 and the merging is working perfectly. Sadly, we noticed there is no toYaml/fromYaml function. We’re super close to the goal with the right result, but couldn’t simply print it.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: ...
spec:
  generators:
  - ... // merge or matrix with multiple (git) generators
  goTemplate: true
  template:
    metadata: ...
    spec:
      source:
        helm:
          values: |
            {{ (omit . "path") | toYaml }} // not working, missing function, so close!
...
```

Would it be possible to add this function to the upcoming 2.6 release? There is already a toJson function, which would at least make it work (because json is a subset of yaml). To make it beautiful and more native it would be great to have a toYaml/fromYaml function.
