### ISSUE TITLE
RBAC controls

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#120]
After SSO integration (https://github.com/argoproj/argo-cd/issues/70), we need a way to control access levels to apps.

**Comment by mukulikak** [comment]
Are we getting roles from Github org or Active directory.

**Comment by mukulikak** [comment]
RBAC- user belongs to a group. group has access to applications 

Roles and permissions (stretch goal) - Superuser, app admin, app readonly

Administration of mapping Github group to access

**Comment by Gangaram-Dewasi** [comment]
Team, 
I'm using SAML for login for normal users, now i want to create a local user for login and api access but post addition of the user in the argocd-cm and also in the RBAC, the login is failing with the error msg saying 

           "FATA[0010] rpc error: code = Unauthenticated desc = Bad local superuser username"

My argocd-cm:
```
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  accounts.deployer: apiKey, login
  accounts.sam: apiKey
  dex.config: 
     x.x.x.x
  repositories: |
    - name: stable
      type: helm
      url: https://kubernetes-charts.storage.googleapis.com
  url: https://argocd.apps.myorg.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-2.0.1
  name: argocd-cm
  namespace: argocd
```

My RBAC:

```
apiVersion: v1
data:
  policy.csv: |
    g, admin, role:admin
    g, deployer, role:admin
    g, sam, role:readonly
    p, role:dev-admin, projects, get, *, allow
    p, role:dev-admin, applications, get, *, allow
    g, org-admins@myorg.com, role:admin
    g, dev-admins@myorg.com, role:dev-admin
  policy.default: ""
  scopes: '[email, groups, accounts]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-2.0.1
  name: argocd-rbac-cm
  namespace: argocd
```

Would request if someone can help me on the above issue.
