### ISSUE TITLE
Helm post-install hooks are executed twice when server-side apply is enabled

### ISSUE THREAD

**Issue by svolland-csgroup** [argoproj/argo-cd#12009]
**Describe the bug**

When deploying a chart with both post-install hooks **and** server-side apply enabled, the post-install job is deployed a first time with other chart resources (e.g. deployment pods), and a second time after the deployment pods are in ready state.
When disabling server-side apply, the behavior is correct: hooks are deployed and execute only after the deployment pods are running and ready.

**To reproduce**

Simple application to reproduce is available at https://github.com/svolland-csgroup/argocd-examples/tree/main/test-hooks-app

Adjust relevant settings of the following ArgoCD [application definition](https://github.com/svolland-csgroup/argocd-examples/blob/main/test-hooks-app/test-hooks-app.yaml) : 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-hooks-app
  namespace: argocd
spec:
  destination:
    namespace: test-hooks
    server: https://my-k8s-cluster:6443
  project: default
  source:
    repoURL: https://github.com/svolland-csgroup/argocd-examples.git
    targetRevision: main
    path: test-hooks-app/simple-app
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
```
This app simply deploys a pod that takes 20 seconds to be ready and a post-install job taking 10 seconds. 

With server-side apply enabled, both are initially deployed and run. The job completes after ~10secs, but is executed a second time after the pod is ready (~20secs).

A more complex app including statefulsets and chart dependencies with additional hooks in the dependencies is also available, just point `source.path` to the [test-hooks-app/complex-app](https://github.com/svolland-csgroup/argocd-examples/tree/main/test-hooks-app/complex-app) directory.

**Expected behaviour**

Independently of server-side apply setting, the post-install hooks must execute once and only after the deployment pods are running and ready.

**Version**

Behavior was reproduced on ArgoCD release versions `2.5.5` and `2.5.6`.
Destination cluster Kubernetes 1.24
