### ISSUE TITLE
Sidecar plugin requires discover command

### ISSUE THREAD

**Issue by nbjohnson** [argoproj/argo-cd#12027]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the plugin sidecar format, even when calling the plugin by name a `discover` command is still required.

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: my-plugin
spec:
  version: v1.0
  ...
  # no discover command
```

```
apiVersion: apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testapp
spec:
  ...
  template:
    ...
    spec:
      project: test
      source:
        ...
        plugin:
          name: my-plugin-v1.0
          ...
```

Sidecar log: `invalid plugin configuration file. at least one of discover.find.name.command or discover.find.glob or discover.fineName should be non-empty`

**Expected behavior**

The appset runs through the plugin that has been specified by name, not having to put in a dummy discover command.

**Screenshots**

**Version**

```shell
v2.6.0-rc4
```

**Logs**

```
Paste any relevant application logs here.
```
