### ISSUE TITLE
Need diffing feature or configuration for unordered or empty list 

### ISSUE THREAD

**Issue by utpk** [argoproj/argo-cd#12033]
# Summary

ArgoCD always show as out-of-sync for unordered or empty list in CRD. 
For example with `RoleBinding` in `authorization.openshift.io/v1`, this will show as out-of-sync even they have the same meaning.
```yaml
# empty diff
groupNames: null
---
groupNames: []
```
or
```yaml
# unordered list diff
subjects:
- kind: Group
  name: A
- kind: User
  name: B
---
subjects:
- kind: User
  name: B
- kind: Group
  name: A
```

I've tried to use `resource.customizations.ignoreDifferences` but we really need to track changes and `resource.customizations.knownTypeFields` that we cannot find the 'array' data type in default K8s

# Proposal

I think we can just simply adding `Array/List` data type or have some flags to treat the list as unordered one.

**Comment by DaliGossrani** [comment]
I am still facing the same issue, any updates?

**Comment by jkroepke** [comment]
Still an issue. Would be great, If ArgoCD could be reorder all Manifests, before diff.

Edit: I could resolve this issue by enable server-side diff: https://argo-cd.readthedocs.io/en/stable/user-guide/diff-strategies/

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
...
```

or

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  controller.diff.server.side: "true"
...
```
