### ISSUE TITLE
helm values from secrets and configmaps

### ISSUE THREAD

**Issue by mkjpryor** [argoproj/argo-cd#12060]
# Summary

I would like to be able to specify a configmap/secret and key containing Helm values for my application.

# Motivation

I am using Argo to install Helm applications from a Helm repository, not a git repository, and am specifying values using the `spec.source.helm.values` field. However when my Helm values contain secrets, I would like to be able to keep them in a secret and reference the secret here instead.

More generally, it would be good to be able to specify multiple values sources from configmaps, secrets and inline blocks that are passed to Helm in the order they are defined.

Because of the way I am using ArgoCD as a backend for a user-facing system, it is not practical to use files in a git repository for this.

# Proposal

I propose a new field `spec.source.helm.valuesSources` that can hold references to a configmap, secret or inline block, e.g.:

```yaml
spec:
  source:
    helm:
      valuesSources:
        - configMap:
            name: my-configmap
            key: values
        - secret:
            name: my-secret
            key: values
        - inline: |
            inline:
              values: here
```

These values would be used at the same precedence as the current `spec.source.helm.values` block.
