### ISSUE TITLE
Bitbucket Server SCM provider fails to fetch repository list.

### ISSUE THREAD

**Issue by solidassassin** [argoproj/argo-cd#12079]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Bitbucket server scm provider fails to query project for repos. The error is not very descriptive: `error listing repos: EOF`. I've tried using the Bitbucket Golang library used by ArgoCD and a request using curl. In both cases  it works as expected, so I assume something is wrong on the application set controller side or my YAML configuration.

**To Reproduce**

**NOTE:** I've substituted sensitive information with placeholders

The following application set manifest was applied:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: repo-appset
spec:
  generators:
    - scmProvider:
        cloneProtocol: https
        bitbucketServer:
          project: MYPROJECT
          api: https://my.server.com/rest
          allBranches: true
          basicAuth:
            username: my-username
            passwordRef:
              secretName: bitbucket-token
              key: password
  template:
    metadata:
      name: "{{ repository }}-{{ branch }}"
    spec:
      source:
        helm:
          releaseName: "test-app-{{ branch }}"
        repoURL: "{{ url }}"
        targetRevision: "{{ branch }}"
        path: charts/test-app
      project: default
      destination:
        server: in-cluster
        namespace: "{{ branch }}"
```

**Expected behavior**

A list of repositories residing in that project should be returned with no EOF errors.

**Version**

```shell
argocd: v2.5.7+e0ee345.dirty
  BuildDate: 2023-01-18T04:28:20Z
  GitCommit: e0ee3458d0921ad636c5977d96873d18590ecf1a
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

**NOTE:** I've substituted sensitive information with placeholders

```
time="2023-01-23T11:42:17Z" level=error msg="error generating application from params" error="error listing repos: EOF" generator="{nil nil nil &SCMProviderGenerator{Github:nil,Gitlab:nil,Bitbucket:nil,BitbucketServer:&SCMProviderGeneratorBitbucketServer{Project:MYPROJECT,API:https://my.server.com/rest,BasicAuth:&BasicAuthBitbucketServer{Username:my-username,PasswordRef:&SecretRef{SecretName:bitbucket-token,Key:password,},},AllBranches:true,},Gitea:nil,AzureDevOps:nil,Filters:[]SCMProviderGeneratorFilter{},CloneProtocol:https,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:ApplicationSource{RepoURL:,Path:,TargetRevision:,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,},Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,},},} nil nil nil nil nil}"
```
