### ISSUE TITLE
CMP version field affects file unix socket path and prevents successful registration

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#12083]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The including a value for the `version` field of the plugin.yaml for argocd-cmp-server results in a socket path including the version. This doesn't match the expectations of the argocd-server container side of the pod.

**To Reproduce**

Define a plugin.yaml for use w/ the cmp-sidecar form:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin-conf
  labels:
  annotations:
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: conf
    spec:
      version: v1.0
      init:
        command: [sh, -c, 'echo "Initializing conf..."']
      generate:
        command:
        - "/usr/local/bin/conf-wrapper"
      discover:
        fileName: "./*.conf"
```

Use helm to define a sidecar for the repo-server with a `conf-cmp` and pull in the plugin definition:
```yaml
  repoServer:
    # ...
    extraContainers:
    - name: conf-cmp
      image: my-image:with-conf
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
      - mountPath: "/var/run/argocd"
        name: "var-files-conf"
      - mountPath: "/home/argocd/cmp-server/plugins"
        name: "plugins"
      - mountPath: "/home/argocd/cmp-server/config/plugin.yaml"
        subPath: "plugin.yaml"
        name: "cmp-plugin-conf"
      - mountPath: "/tmp"
        name: "cmp-tmp-conf"
      - mountPath: /usr/local/bin/conf-wrapper
        name: tools
        subPath: conf-wrapper
```

**Expected behavior**

* Things should work (how they work is an implementation detail beyond my interest -- it could be that the code enumerates and looks for conf*.sock, it could be that the version field is ignored, ...)
* Documentation should explain how to make them work
* Users shouldn't trip over suggested configuration fields that result in non working systems (I didn't invent `version: v1.0` -- I've seen other tickets which also include that)

**Screenshots**

**Version**

```shell
{
    "Version": "v2.6.0+584428e",
    "BuildDate": "2023-01-19T17:14:49Z",
    "GitCommit": "584428edaf535258924912a191a97dde8a5c5d3d",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
time="2023-01-20T19:19:12Z" level=error msg="Unable to connect to config management plugin service with address /home/argocd/cmp-server/plugins/conf.sock"
time="2023-01-20T19:19:12Z" level=error msg="error dialing to cmp-server for plugin conf.sock, dial unix /home/argocd/cmp-server/plugins/conf.sock: connect: no such file or directory" CWE=775 security=2
time="2023-01-20T19:19:12Z" level=error msg="finished unary call with code Unknown" error="plugin sidecar failed. couldn't find cmp-server plugin with name conf supporting the given repository" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2023-01-20T19:19:11Z" grpc.time_ms=1246.037 span.kind=server system=grpc
```

Note, I have:
`/home/argocd/cmp-server/plugins/conf-v1.0.sock`
but it's looking for
`/home/argocd/cmp-server/plugins/conf.sock`

**Comment by pre** [comment]
Trying to migrate to the sidecar cmp world, and I'm struggling with the exact same issues as described here:

* Example sidecar CMP has `spec.version` but the error message doesn't mention `name-version` is expected as the CMP name (docs neither..)
* `/home/argocd/cmp-server/plugins/myplugin.sock: connect: no such file or directory"`  -- `ConfigManagementPlugin` name accidentally had a `cmp-` prefix although the `plugin.name` in `Application` did not.
* Documentation does not really explain how things work - I've been running ArgoCD with the ConfigMap CMP approach for 2 years now, and I feel I'm fluent with ArgoCD ... but the Sidecar configuration is not explained well (and there's no coherent working example) even though I know the concepts around it.

**Comment by chakraborty29** [comment]
When implementing a custom Kustomize + EnvSubst Config Management Plugin for ArgoCD, we encountered socket permission errors:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = plugin sidecar failed. couldn't find cmp-server plugin with name "kustomize-envsubst" supporting the given repository
```

In the logs:

```
{
  "level":"error",
  "msg":"Unable to connect to config management plugin service with address /home/argocd/cmp-server/plugins/kustomize-envsubst.sock",
  "time":"2025-05-11T22:05:21Z"
},
{
  "CWE":775,
  "level":"error",
  "msg":"error dialing to cmp-server for plugin kustomize-envsubst.sock, dial unix /home/argocd/cmp-server/plugins/kustomize-envsubst.sock: connect: permission denied",
  "security":2,
  "time":"2025-05-11T22:05:21Z"
}
```
## Troubleshooting Steps

1. Check if the socket file exists in the plugins directory
   ```
   kubectl exec -n argocd <repo-server-pod> -c kustomize-envsubst -- ls -la /home/argocd/cmp-server/plugins/
   ```

2. Verify the socket permissions
   ```
   kubectl exec -n argocd <repo-server-pod> -c kustomize-envsubst -- stat -c '%A %a %U:%G' /home/argocd/cmp-server/plugins/kustomize-envsubst.sock
   ```

3. Check user IDs between containers
   ```
   kubectl exec -n argocd <repo-server-pod> -c argocd-repo-server -- id
   kubectl exec -n argocd <repo-server-pod> -c kustomize-envsubst -- id
   ```

4. Review logs from both containers
   ```
   kubectl logs -n argocd <repo-server-pod> -c argocd-repo-server
   kubectl logs -n argocd <repo-server-pod> -c kustomize-envsubst
   ```

## Root Cause

The issue occurs because:

1. The ArgoCD repo-server container runs as a non-root user (`argocd`, UID 999)
2. The CMP sidecar container creates socket files as the `root` user
3. The repo-server cannot access the socket files due to permission restrictions

## Solution

We implemented a solution that:

1. Uses the CMP plugin sidecar running as root (necessary for the installation of dependencies)
2. Monitors and fixes the socket permissions after creation

### Key Changes

#### 1. Sidecar Container Configuration

```yaml
# apps/argocd/manifests/overlays/cmp-kustomize-envsubst-sidecar.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: kustomize-envsubst
          image: alpine:3.20
          command: [/var/run/argocd/argocd-cmp-server]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: cmp-kustomize-envsubst
            - mountPath: /tmp
              name: cmp-tmp
          # Standard ArgoCD variables required for the plugin to function
          env:
            - name: ARGOCD_APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: ARGOCD_APP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: argocd-app-env
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    # Install dependencies
                    apk add --no-cache gettext curl jq
                    
                    # Install kustomize
                    KUSTOMIZE_VERSION=v5.1.1
                    curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz" | tar -xz -C /tmp
                    mv /tmp/kustomize /usr/local/bin/
                    chmod +x /usr/local/bin/kustomize
                    
                    # Critical component: Fix socket permissions in the background
                    (
                      # Wait for socket to be created
                      while true; do
                        if [ -S /home/argocd/cmp-server/plugins/kustomize-envsubst.sock ]; then
                          chmod 777 /home/argocd/cmp-server/plugins/kustomize-envsubst.sock
                          echo "Fixed socket permissions"
                          break
                        fi
                        echo "Waiting for socket creation..."
                        sleep 1
                      done
                    ) &
      volumes:
        - name: cmp-kustomize-envsubst
          configMap:
            name: cmp-kustomize-envsubst
        - name: cmp-tmp
          emptyDir: {}
```
