### ISSUE TITLE
Using the same repo in multi-source application feature

### ISSUE THREAD

**Issue by ShirMonDT** [argoproj/argo-cd#12159]
# Summary

In the 2.6 multiple source application feature I would like to use the same git repository with different refs but I'm getting the following error;
`rpc error: code = Unknown desc = cannot reference a different revision of the same repository`
![image](https://user-images.githubusercontent.com/89846634/214900569-08ef7a9e-bb8c-407e-befc-1fd33d23a5cd.png)

I understand that under the hood, we’re dealing with a single copy of the cloned repo. To reference one revision, we have to checkout that revision and then acquire a lock. If we try to reference another revision at the same time, we hit a potential deadlock.

# Motivation

I would like to use different refs from the same repository in the same application. This will allow usage of git tags to version certain generic configurations and referencing them in the same repository.
So for example if I have a GitOps repository with helm charts I would like to version them with git tags and reference the relevant chart version with up to date values.

# Proposal

One solution would be to make a temporary copy of the referenced repo, or at least the referenced file.

**Comment by marianheinsen** [comment]
We are also missing this functionality. Our use case is that we want to use a Helm Chart as the first source from a feature branch and the values for the Chart from the main branch of the same repository. Do you consider the implementation of this feature to be very complex? We think about contributing this if there are no plans from your side to work on this in the near future. Do you think in general this feature would be reasonable to implement and are you open to incorporate a contribution of ours? @crenshaw-dev

**Comment by crenshaw-dev** [comment]
> Do you consider the implementation of this feature to be very complex?

Not too bad, no.

> if there are no plans from your side to work on this in the near future

Unfortunately I won't be able to get to it any time soon.

> Do you think in general this feature would be reasonable to implement and are you open to incorporate a contribution of ours?

I think it's reasonable and would absolutely review it! 

The reason it's not supported now is that we lock and then check out each repo exactly once.

In the case of multiple revisions, we'd need to lock and check out one revision, copy the target values file somewhere safe (random UUID path to protect it from path traversal attacks), and then unlock the repo. Of course, you'll have to clean up the copied values file after using it.

**Comment by natalicot** [comment]
@crenshaw-dev I would be thrilled to see this feature implemented as well! Being able to manage our Helm chart versioning in this manner would be a significant improvement for our workflows. @marianheinsen  If you are considering implementing this feature, please keep us posted. I am sure many of us would be eager to offer assistance and support if needed. Looking forward to seeing your contribution!

**Comment by tkaesserfm** [comment]
We would be glad to see this too!

**Comment by amiros89** [comment]
Also looking forward seeing this feature soon. We use multiple values files in the same repo, while one of the files should always be taken of the main branch even when the chart is deployed from a feature branch. We'd love having this implemented soon in order to use ArgoCD with our use case.

**Comment by SKY-Mark-Rhoades-Brown** [comment]
We have a very similar predicament to @amiros89 - we would like valuesfiles from the main branch and a particular git ref for the applcation

**Comment by Nilushka** [comment]
I agree, it would be extremely convenient in my case. I'm waiting for implementation

**Comment by Nilushka** [comment]
My temporarty solution - is ArgoCD deception. Make a second DNS publication 

      # master config
      - path: '{{path}}'
        repoURL: 'https://gitlab-mirror.domain.com/deploy/{{project}}.git'
        targetRevision: 'master'
        ref: masterConfig

      # env config
      - path: '{{path}}'
        repoURL: 'https://gitlab.domain.com/deploy/{{project}}.git'
        targetRevision: '{{branch}}'
        ref: envConfig

**Comment by medykn-git** [comment]
Any update on this feature ?

**Comment by vuthongkms** [comment]
+1

**Comment by jakuboskera** [comment]
+1

**Comment by jakuboskera** [comment]
My temporary solution is also using different value for repoRUL so for Helm Chart I use protocol SSH for values HTTPS protocol. Not ideal but works without so much pain.

**Comment by marpears** [comment]
+1

**Comment by Shaked** [comment]
This prohibits users to use a chart with `chartVersionw` (most likely pinned to SHA or git tag) while keeping the values with `valuesVersion` (most likely HEAD/master), so in this use case, it is impossible to update `image.tag` or any other values, without promoting the chart itself.

Before trying to add a PR, it would be nice to understand why this was added in first place:

https://github.com/argoproj/argo-cd/blob/d761c94b7d9452de7f57f171b359ab44290cd414/reposerver/repository/repository.go#L764-L767

**Comment by crenshaw-dev** [comment]
> why this was added in first place

It was just easier to code at the time, and we didn't consider it to be a core feature.

The repo-server keeps a single clone of each repository. In order for two sources to safely use two (potentially different) revisions from the same source, it would have to 

1) check out the referenced source
2) make a copy of whatever file(s) are relevant to the other source
3) check out the referring source
4) run manifest generation using the path(s) of the file(s) from the referenced source

It's not a wildly complex operation. But care must be taken to avoid race conditions and path traversal.

**Comment by mhoria** [comment]
+1

**Comment by Shaked** [comment]
There are two options to solve this if you cannot control the domain and create a CNAME:

## Empty Basic Auth

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-github-app
spec:
  destination:
    namespace: mynamespace
    server: https://kubernetes.default.svc
  sources:
    - path: charts/podinfo
      repoURL: https://github.com/stefanprodan/podinfo.git
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/charts/podinfo/values.yaml
          - $values/charts/podinfo/values-prod.yaml
    - repoURL: https://@github.com/stefanprodan/podinfo.git # Notice the `@` 
      targetRevision: HEAD
      ref: values
  project: tests
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
```

Notice the `@` in the second `repoURL`

## Port

One more option to solve this if you cannot control the domain and create a CNAME, is to use an empty basic auth: 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-github-app
spec:
  destination:
    namespace: mynamespace
    server: https://kubernetes.default.svc
  sources:
    - path: charts/podinfo
      repoURL: https://github.com/stefanprodan/podinfo.git
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/charts/podinfo/values.yaml
          - $values/charts/podinfo/values-prod.yaml
    - repoURL: https://github.com:443/stefanprodan/podinfo.git # Notice the `@` 
      targetRevision: HEAD
      ref: values
  project: tests
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
```

Notice the `:443` in the second `repoURL`

**Comment by jeremyj563** [comment]
@Shaked Thanks for the slick workaround!

**Comment by mhoria** [comment]
I've managed to solve the issue by using a matrix appset (this applies to our use case, where we use one appset to create all the apps dynamically, given some parameters). 

The helm chart is hosted in its own git structure, but has the helm chart in one project, and the values in another git project. It could look like this:

├─ SomeRootPath/
│  └─ AppX/                (an example application under the AppX portfolio)
│     ├─ AppX-app/         (the actual code base + Docker build pipeline)
│     │  ├─ src/
│     │  ├─ Dockerfile
│     │  └─ .gitlab-ci.yml     (CI to build/push Docker images, etc.)
**│     └─ configurations/                 (a subgroup for all helm-related repos for "")
│        ├─ helm-chart.git     (the Helm chart repository: Chart.yaml, templates/, etc.)
│        └─ env-values.git   (the environment overlays + release-config.json)
│           ├─ nonprod/
│           │  ├─ clone/values.yaml
│           │  ├─ test/values.yaml
│           │  └─ release-config.json  (for nonprod references)
│           └─ prod/
│              ├─ prod/values.yaml
│              └─ release-config.json  (for prod references)**

Notice that under each env-values (prod and nonprod), there is the release-config.json  where you can bind which revision to be used by each environment (could be tags or a branch). ** The revision is the one from the Helm Chart Git

```
{
    "targetRevisions": {
        "test": "main",
        "uat": "1.0.0",
        "clone": "1.0.0"
    }
}
```

Then the appset glues and creates everything. 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset--nonprod     # The name of this ApplicationSet resource
  namespace: argocd               # It lives in the argocd namespace
spec:
  goTemplate: true                # Tells ArgoCD to interpret {{ ... }} as Go template expressions
  generators:
    - matrix:
        generators:
          # (1) Inner matrix: merges base config + environment overlays
          - matrix:
              generators:
                # Generator A: base config from app-configs
                - git:
                    repoURL: "https://YourGitRepor.something.com/a/Path/To/app-configs.git"
                    revision: main
                    files:
                      - path: "*/region-nonprod/*.json"
                    pathParamPrefix: base
                    requeueAfterSeconds: 20
  
                # Generator B: environment overlays from .valuesSource
                - git:
                    repoURL: "{{ .valuesSource.repoURL }}"
                    revision: "{{ .valuesSource.targetRevision }}"
                    files:
                      - path: "{{ .valuesSource.path }}*/values.yaml"
                    pathParamPrefix: env
                    requeueAfterSeconds: 20
  
          # (2) Outer generator: merges with release-config from the same (environments) repo
          - git:
              repoURL: "{{ .valuesSource.repoURL }}"
              revision: "{{ .valuesSource.targetRevision }}"
              files:
                - path: "{{ .valuesSource.path }}release-config.json"
              pathParamPrefix: release
              requeueAfterSeconds: 20
  
  template:
    metadata:
      labels:
        environment: "{{ index .env.path.segments 1 }}"
        app.kubernetes.io/name: "{{ .application_name }}-{{ index .env.path.segments 1 }}"
      name: "{{ .application_name }}-{{ index .env.path.segments 1 }}"
  
    spec:
      destination:
        namespace: "itba-{{ .domainName }}-{{ index .env.path.segments 1 }}"
        server: "https://kubernetes.default.svc/"
      project: "{{ .argocdProject }}"
  
      # We define two sources: the Helm chart, and the environment overlays
      sources:
        - helm:
            ignoreMissingValueFiles: true
            parameters:
              - name: targetRevision
                value: "{{ (index .targetRevisions (index .env.path.segments 1)) | default .helmSource.targetRevision }}"
            valueFiles:
              - values.yaml
              - "$valuesSourceRef/{{ .env.path.path }}/{{ .env.path.filename }}"
          path: "{{ .helmSource.path }}"
          repoURL: "{{ .helmSource.repoURL }}"
          targetRevision: "{{ (index .targetRevisions (index .env.path.segments 1)) | default .helmSource.targetRevision }}"
  
        - ref: valuesSourceRef
          repoURL: "{{ .valuesSource.repoURL }}"
          targetRevision: "{{ .valuesSource.targetRevision }}"
  
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

`the/base-app.json` is the parameter "store" for the appset:
```


{
  "argocdProject": "your ArgoCD Project",
  "application_name": "AppX",
  "domainName": "beta",  **our use case, can be adjusted and it s used to create the name of the applications
  "valuesSource": {
    "repoURL": "https://your.gitrepo.com/SomeRootPath/AppX/configurations/helm-chart.git",
    "path": "nonprod/",
    "targetRevision": "main"
  },
  "helmSource": {
    "repoURL": "https://your.gitrepor.com/SomeRootPath/AppX/configurations/helm-chart.git",
    "path": "./",
    "targetRevision": "main"
  }
}

```


Using this setup allows:
- having a revision strategy for the main helm chart repo (this helps to have versioning for the main helm chart)
- bind a specific revision to a specific environment (ex test using 1.2.3, prod - main etc) by only modifying release-config.json while the argocd appset takes care of applying the configuration.
