### ISSUE TITLE
Unable to pass multiline env vars to a plugin

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-cd#12152]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When passing a multi-line env var to a plugin, argocd tries to compress the env var into a single line.

**To Reproduce**

Consider an application definition of this nature:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
spec:
  destination:
    namespace: example
    server: 'https://kubernetes.default.svc'
  source:
    path: ex/ample
    repoURL: 'https://github.com/wibble/example.git'
    targetRevision: HEAD
    plugin:
      name: example-plugin
      env:                                                                                                                                                                                         
        - name: EXAMPLE_KUSTOMIZE_MERGE
          value: |
            images:
            - name: imagerepo/image1
              newTag: v0.13.24
            - name: imagerepo/image2
              newTag: v0.13.24
            - name: imagerepo/image3
              newTag: v0.13.24
            - name: imagerepo/image4
              newTag: v0.13.24
            - name: imagerepo/image5
              newTag: v0.13.24
            - name: imagerepo/image6
              newTag: v0.13.24
            - name: imagerepo/image7
              newTag: v0.13.24
            - name: imagerepo/image8
              newTag: v0.13.24
...
```

When this is passed to our plugin, the contents of the `EXAMPLE_KUSTOMIZE_MERGE` env var is mangled together onto one line and is unreadable by the plugin as a result. The Argo CD UI reflects this mangling (see screenshot below).

**Expected behavior**

If I convert the multiline yaml to a single line json, then I get the result I expect:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
spec:
  destination:
    namespace: example
    server: 'https://kubernetes.default.svc'
  source:
    path: ex/ample
    repoURL: 'https://github.com/wibble/example.git'
    targetRevision: HEAD
    plugin:
      name: example-plugin
      env:                                                                                                                                                                                         
        - name: EXAMPLE_KUSTOMIZE_MERGE
          value: '{"images":[{"name":"imagerepo/image1","newTag":"v0.13.24"},{"name":"imagerepo/image2","newTag":"v0.13.24"},{"name":"imagerepo/image3","newTag":"v0.13.24"},{"name":"imagerepo/image4","newTag":"v0.13.24"},{"name":"imagerepo/image5","newTag":"v0.13.24"},{"name":"imagerepo/image6","newTag":"v0.13.24"},{"name":"imagerepo/image7","newTag":"v0.13.24"},{"name":"imagerepo/image8","newTag":"v0.13.24"}]}'
```
Unfortunately single-line json is less human readable/maintainable than the multiline yaml.

**Screenshots**

Here's how the multiline env var looks in the argocd UI:
![image](https://user-images.githubusercontent.com/45351296/214776697-0630b36d-8e54-4330-b20b-4c703dc75096.png)

**Version**

```shell
{
    "Version": "v2.5.8+bbe870f",
    "BuildDate": "2023-01-25T16:17:49Z",
    "GitCommit": "bbe870ff5904dd1cebeba6c5dcb7129ce7c2b5e2",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```
