### ISSUE TITLE
Multiple sources: Values are not refreshed if in the same repository

### ISSUE THREAD

**Issue by Azenet** [argoproj/argo-cd#12166]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When creating an application that has values referencing the same repository the application is declared in, the values are not refreshed along with the source repository.

**To Reproduce**

Repro repository: https://github.com/Azenet/argotest

1. Create an multi-source application referencing the same repository for values, writing a value that does not pass validation:
```yaml
# apps/nginx/nginx.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - chart: nginx
      targetRevision: ^13.2
      repoURL: https://charts.bitnami.com/bitnami
      helm:
        version: v3
        releaseName: nginx
        valueFiles:
          - $values/apps/nginx/values.yaml
    - repoURL: https://github.com/Azenet/argotest.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

# apps/nginx/values.yaml
replicaCount: -1
```

2. Push the change, check that sync of the app fails (replicaCount cannot be negative)
3. Update the values.yaml file, setting replicaCount to a valid value
4. Refresh and sync the app

**Expected behavior**

The deployment is updated with the new replicaCount

**Actual behavior**

The deployment is not updated and the validation error is not cleared. The invalid replica value can be seen in the app diff on the dashboard.

**Workaround**

Restarting the ArgoCD repo server and flushing the ArgoCD redis usually makes ArgoCD realize there's something to sync, although it will sometimes not auto-sync it even if auto-sync is enabled.

**Version**

```shell
argocd: v2.6.0-rc5+unknown
  BuildDate: 2023-01-26T22:58:08Z
  GitCommit: 
  GitTreeState: 
  GitTag: 2.6.0-rc5
  GoVersion: go1.19.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.0-rc5+unknown
  BuildDate: 2023-01-26T22:58:08Z
  GitTag: 2.6.0-rc5
  GoVersion: go1.19.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: 4.5.7 2022-08-12T18:18:43Z
  Helm Version: v3.10.2+g50f003e
  Jsonnet Version: v0.19.1
```

**Logs**

No relevant logs were found.

Thank you for any help!
