### ISSUE TITLE
Notifications should only be sent for apps that have actually changed.

### ISSUE THREAD

**Issue by btxbtx** [argoproj/argo-cd#12169]
# Summary

I only want to be notified about app changes for apps that have changed, and nothing else.

Even if you implement only `deployment` notifications according to the [docs](https://argocd-notifications.readthedocs.io/en/latest/triggers/), i.e.,

```
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.sync.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

change to a single app results in the trigger firing for every app in every cluster. Supposing there is a way to modify the above implementation so that it only updates for every app in the affected cluster, my use case would not be met.

One app change, one notification.

# Motivation

I have one repo which stores cluster state for many clusters, monitored by ArgoCD.  When just one app for one cluster in this repo is merged to, I receive sync notifications for every single app in every single cluster.  This is too noisy, and doesn't show me the information I actually want -- which app in which cluster was deployed to.

Original discussion posted [here](https://github.com/argoproj/argo-cd/discussions/12127#discussioncomment-4789796)

# Proposal

Perhaps a field of `app.` which indicates that changes were found in the last sync operaiton, i.e.
`app.status.change_detected == True`

**Comment by daviderli614** [comment]
hi @btxbtx , Is this problem solved?

**Comment by btxbtx** [comment]
No @daviderli614, this has not been solved yet.

**Comment by EppO** [comment]
I ran into the same "issue" when integrating with Grafana annotations, I was expecting the annotation to get triggered only when a successful sync occurred for a specific Argo CD App that needed an actual sync but it gets triggered for any new commits in the repo of that Argo CD App, regardless if it was in a folder the App was tracking or not. So if your Git repository contains multiple Argo CD Apps (using folders structure), every single Argo CD Apps sends a notifications of "succeeded" after a Git commit. 
```
when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```
The obvious workaround is to use one Git repository per App but it's too drastic for me. 
We should have an event that gets triggered when an App is doing some actual changes (i.e. some of its tracked resources were in out-of-sync state and got synced successfully).

**Comment by daviderli614** [comment]
Hi @EppO @btxbtx, I have a great idea, my notification configurations:
```
notifiers:
    service.slack: |
      token: $slack-token
      icon: xxx

  subscriptions:
    - recipients:
        - slack:xxx
      triggers:
        - on-sync-status-unknown
        - on-sync-failed
        - on-health-degraded
        - on-deployed

  triggers:
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.sync.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() <= 3
    trigger.on-health-degraded: |
      - description: Application has degraded
        oncePer: app.status.sync.revision
        send:
        - app-health-degraded
        when: app.status.health.status == 'Degraded'
    trigger.on-sync-failed: |
      - description: Application syncing has failed
        oncePer: app.status.sync.revision
        send:
        - app-sync-failed
        when: app.status.operationState.phase in ['Error', 'Failed']
    trigger.on-sync-status-unknown: |
      - description: Application status is 'Unknown'
        oncePer: app.status.sync.revision
        send:
        - app-sync-status-unknown
        when: app.status.sync.status == 'Unknown'
    defaultTriggers: |
      - on-sync-status-unknown
```

The point is `time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() <= 3` in trigger.on-deployed.

In this way, all applications cannot have outofsync or other unhealthy states, because when updating a healthy application, the application in the non-outofsync state will be synchronized, and the outofsync application will perform a sync action and receive a notification. In this way, when the old application is updated, its startedAt distance is greater than 3 minutes, and it will not be notified.

**Comment by de-slalonde** [comment]
I'm very new to Argo, sorry if I'm way off base. To avoid on-deployed notifications from every app on every commit, what about doing this? Quick initial tests work for me, only the app(s) that have actually changed get a new `app.status.operationState.finishedAt`.

```
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.operationState.finishedAt
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

**Comment by dtotopus** [comment]
@de-slalonde , finishedAt will change on every sync even if there are no actual changes.

**Comment by Glebcher601** [comment]
@dtotopus Well, finishedAt indeed changes every time even when resource unrelated to application is changed. I still get webhook notification on every change

**Comment by dtotopus** [comment]
> 

Do you have auto heal enabled? I know it's not the best solution, but maybe disabling it won't trigger "proper" syncing.

**Comment by m00lecule** [comment]
Faced the same issue when storing multiple Apps in one repository. Imho this feature is crucial.

**Comment by freekdegreef** [comment]
We had this same issue with three environments for an app in the same repo triggering webhooks on changes regardless of which environment had actually changed. I tried the suggestion offered by @Glebcher601 but in our case the deployments we're always showing a 'configured' message. 

What we did in the end is this which works for now:
`  trigger.on-deployed-gitlab: |
    - description: Application syncing has succeeded
      oncePer: app.status.sync.revision
      send:
      - gitlab-deployment-status
      when: app.status.operationState.phase in ['Succeeded'] and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() < 2`

**Comment by gnoguchi** [comment]
Thank you @freekdegreef! We had the same problem and after implementing your solution it worked!

**Comment by eimarfandino** [comment]
Is there any progress regarding this?

**Comment by maticue** [comment]
Aren't your talking about monorepo approach? https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/triggers/#avoid-sending-same-notification-too-often

> When one repo is used to sync multiple applications, the oncePer: app.status.sync.revision field will trigger a notification for each commit. For mono repos, the better approach will be using oncePer: app.status.operationState.syncResult.revision statement. This way a notification will be sent only for a particular Application's revision.

**Comment by volkanakcora** [comment]
> We had this same issue with three environments for an app in the same repo triggering webhooks on changes regardless of which environment had actually changed. I tried the suggestion offered by @Glebcher601 but in our case the deployments we're always showing a 'configured' message.
> 
> What we did in the end is this which works for now:
> 
> ```
>   trigger.on-deployed-gitlab: |
>     - description: Application syncing has succeeded
>       oncePer: app.status.sync.revision
>       send:
>       - gitlab-deployment-status
>       when: app.status.operationState.phase in ['Succeeded'] and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() < 2
> ```

Mate, you saved me, thank you!

**Comment by smartfin** [comment]
> https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/triggers/#avoid-sending-same-notification-too-often

@maticue are there any downsides of using this method for non-monorepo apps? It looks like the condition in doc is more suitable for `on-deployed` trigger for any application.

**Comment by imorato** [comment]
> We had this same issue with three environments for an app in the same repo triggering webhooks on changes regardless of which environment had actually changed. I tried the suggestion offered by @Glebcher601 but in our case the deployments we're always showing a 'configured' message.
> 
> What we did in the end is this which works for now:
> 
> ```
>   trigger.on-deployed-gitlab: |
>     - description: Application syncing has succeeded
>       oncePer: app.status.sync.revision
>       send:
>       - gitlab-deployment-status
>       when: app.status.operationState.phase in ['Succeeded'] and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() < 2
> ```

The problem we are having is as follows:
We have the when rule with 'finishedAt < 5', and the pod deployment takes less than 5 minutes but the application remains in 'progressing' because it is creating some certificates.
As a result, it sends the commit in progress but never the success, since the evaluation of success is not met due to the < 5.

One way to solve it is to extend it to < X... But is there any other way to mitigate the problem?

Here my config:

```yaml
    trigger.on-deployed: |
      - description: Application is synced and healthy
        oncePer: app.status.sync.revision
        send: [app-deployed]
        when: app.status != nil and app.status.operationState != nil and app.status.operationState.phase in [ 'Succeeded' ] and app.status.health != nil and app.status.health.status == 'Healthy' and time.Now().Sub(time.Parse(app.status.operationState.finishedAt)).Minutes() < 30

```
