### ISSUE TITLE
Deployment of ArgoCD deleting already existing resources in k8s

### ISSUE THREAD

**Issue by knjoroge** [argoproj/argo-cd#12182]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am migrating from Flux to ArgoCD. The issue I am having is when I deploy ArgoCD it is terminating all my resources in my k8s cluster and recreating them. I am doing this in a test environment but in a production environment this would not be good. 

**To Reproduce**

- I am deploying using helm.
- Using GitGenerator so Argo watches my repository and manifests.
- kubectl apply the manifests for ArgoCD.

**Expected behavior**

What I expect is ArgoCD to start watching my repository and managing deployments but without terminating all the resources that are already present in my k8 cluster.

**Screenshots**

```
{{ range  $name, $gitRepository := .Values.gitRepositories -}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $name }}-services
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: git@github.com:sandbox/{{ $name }}
      revision: main
      directories:
      - path: {{ $gitRepository.path }}
  template:
    metadata:
      name: "{{`{{path.basename}}`}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
      source:
        repoURL: git@github.com:sandbox/{{ $name }}
        targetRevision: main
        path: "{{`{{path}}`}}"
        directory:
            exclude: .source.json
            include: '*.yaml'
            jsonnet: {}
            recurse: true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argo
{{ end -}}

```

**Version**

```shell
`v2.5.8` Chart version: `5.19.8`
```
