### ISSUE TITLE
Ability to disable userid/password login and remove from login page

### ISSUE THREAD

**Issue by RobCannon** [argoproj/argo-cd#12192]
# Summary

If SSO is enabled, the userid/password portion of the login screen is confusing at best and potentially a hacking vector.  I would like to disable user/password login and remove it from that page.

# Motivation

Some password auto-fill programs try to login in via that page since the domain is a sub-domain of our company domain.
Plus, it is confusing to people who think they should be providing their userid and password instead of hitting the "Login via SAML" button

# Proposal

Add an environment variable argo-server (and perhaps argo-dex-server) that disabled userid/password logins.

**Comment by 2022H1030042G** [comment]
I'd like to work on this issue, is it available?

**Comment by DavidConnack** [comment]
From my experience, once the default admin user is disabled and sso is enabled, the login for is removed
![image](https://user-images.githubusercontent.com/47108996/216034278-82ef8b13-29f7-4b94-940e-51718af9ff02.png)

**Comment by Ruivalim** [comment]
I would like to know if there's another way to disable de login form. 
I have disabled my admin account, but I created another login with username and password for using the API, this enabled the login form again.

Is there I way I can disabled the login form? Or is there a better way to use the API other than username and password?

**Comment by FranAguiar** [comment]
I have sso enable and my admin user is disabled, but the login form is still there... 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'false'
  url: https://argocd.domain.com
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/uuid/v2.0
    clientID: uuid
    clientSecret: $azure.clientSecret
    requestedIDTokenClaims:
       groups:
          essential: true
    requestedScopes:
       - openid
       - profile
       - email

```
I'm doing something wrong?
