### ISSUE TITLE
Allow limiting clusterResourceWhitelist to specific resource names

### ISSUE THREAD

**Issue by cspargo** [argoproj/argo-cd#12208]
# Summary

Support resource names in `clusterResourceWhitelist` to restrict to specific resource names. 

# Motivation

This was first proposed in closed issue https://github.com/argoproj/argo-cd/issues/3553, and there are a few later comments that others feel it would be useful. A specific use-case that I was thinking of was to be able to allow a project to install/update/delete specific named CRDs, without having access to update all of them.

# Proposal

I'm thinking something like RBAC's `resourceNames` list that would limit the access to only the specified resources names

```
clusterResourceWhitelist:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinitions
    resourceNames:
      - crd1.example.com
      - crd2.example.com
```

or perhaps it could be like what was suggested in the previous issue, although i'm not sure we can have multiples of the same group+kind (at least the "argocd proj allow" syntax seems to imply that it wouldn't work).

```
clusterResourceWhitelist:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinitions
    name: crd1.example.com
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinitions
    name: crd2.example.com
```

perhaps they could support a glob/wildcard for the name
