### ISSUE TITLE
Support for OpenShift

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1224]
Hi We are trying to implement argocd on top of openshift. When syncing rolebindings it appears that there are 2 groups: authorization.openshift.io and rbac.authorization.k8s.io:

How do we sync those correctly? I have one rolebinding each. and apply them as follows: 
```
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy
  namespace: {{ $namespace.name }}
roleRef:
```

Then argocd shows me outofsync with rbac group thats not correct to me

![image](https://user-images.githubusercontent.com/9946020/53803241-68cb7100-3f44-11e9-98a5-0d68aac17099.png)
