### ISSUE TITLE
Controller doesn't trust certificates set in ArgoCD when fetching external resources

### ISSUE THREAD

**Issue by yohancourbe** [argoproj/argo-cd#12256]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It seems that the controller doesn't trust the certificates of ArgoCD when it fetches external resources.

For example when using Kustomize to deploy a Helm chart coming from an custom repo, the deployment fails because of unknown authority, despite the certificate to be added in ArgoCD settings. A similar issue exists with other form of external resources in #6477.

The workaround is described in #6477 is not possible when using the ArgoCD operator as the deployment will be override by the operator and the operator doesn't support such settings.

**To Reproduce**

Deploy a helm chart via kustomize
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: some-chart
  repo: https://some-repo-with-custom-ca
  releaseName: some-release
  namespace: some-namespace
  version: 0.0.1
  valuesFile: values.yml
```

**Expected behavior**

The controller trusts the certificate set in ArgoCD when fetching external resources

**Screenshots**

n/a

**Version**

```shell
{
    "Version": "v2.5.2+148d8da",
    "BuildDate": "2022-11-07T16:42:47Z",
    "GitCommit": "148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
Get "https://[truncated]": x509: certificate signed by unknown authority : unable to run: 'helm pull --untar --untardir [truncated]/charts --repo https://[truncated]
```
