### ISSUE TITLE
Ingress link is not handled correctly if path: contains regex

### ISSUE THREAD

**Issue by ohauer** [argoproj/argo-cd#12254]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In case ingress path contains regex the links in the UI are cutted after the first '/('

Sample ingress config
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress-with-regex
spec:
  ingressClassName: nginx
  rules:
  - host: test.exemple.org
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 8080
        path: /base-path/(pattern1|pattern2|pattern3)(/.*)?
        pathType: ImplementationSpecific
```

**Expected behavior**
Since it is impossible to create a valid link matching the regex, include only the part before the first '(' in the link

**Screen Shots**

![ingress_link_path_with_regex](https://user-images.githubusercontent.com/789018/216293336-feaef44b-71cd-4b10-9a07-0cde9c499e01.png)

**Version**

```shell
argocd: v2.6.0-rc6+e6df2fc
  BuildDate: 2023-01-27T23:50:02Z
  GitCommit: e6df2fcfcaf367eb8e318790cda11a47532a72d4
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.0-rc6+e6df2fc

```
