### ISSUE TITLE
ApplicationSet/git-generator - Add generator parameter: repoURL

### ISSUE THREAD

**Issue by jaboge** [argoproj/argo-cd#12279]
# Summary

It would be useful if the git-generator would include **repoURL** in it's list of generator parameters

# Motivation

Assuming it's possible to use multiple git-generators in the first place, I'd like to be able to have them pointing at distinct git repositories. Notice how the (proposed) repoURL parameter is used to populate spec.template.spec.source.repoURL.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-stage
spec:
  generators:
     - git:
         repoURL: https://bitbucket.org/my-org/team-abc-gitops.git
         revision: HEAD
         directories:
           - path: k8s-apps/*/*/overlays/stage
     - git:
         repoURL: https://bitbucket.org/my-org/team-xyz-gitops.git
         revision: HEAD
         directories:
           - path: k8s-apps/*/*/overlays/stage
  template:
    metadata:
      name: 'stage-{{path[1]}}-{{path[2]}}'
    spec:
      project: 'my-project'
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: my-cluster
        namespace: '{{path[1]}}'
```

Even in case that my assumption regarding multiple git-generators should be wrong, the parameter would still be useful as it eliminates the need to repeat the repoURL in the template.

# Proposal

See Summary

**Comment by jaboge** [comment]
Never mind - I solved it using the matrix generator:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-stage
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - repoURL: https://bitbucket.org/my-org/team-abc-gitops.git
                - repoURL: https://bitbucket.org/my-org/team-xyz-gitops.git
          - git:
              repoURL: '{{repoURL}}'
              revision: HEAD
              directories:
                - path: k8s-apps/*/*/overlays/test/jab
  template:
    metadata:
      name: 'stage-{{path[1]}}-{{path[2]}}'
    spec:
      project: 'my-project'
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: my-cluster
        namespace: '{{path[1]}}'
```
