### ISSUE TITLE
Misspelling of ServerSideApply in the Sync Options field in UI

### ISSUE THREAD

**Issue by chipzoller** [argoproj/argo-cd#12281]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In the UI in the Summary tab for an Application, if ServerSideApply is enabled as a sync option, this is shown as "ServiceSideApply"

**To Reproduce**
Deploy a simple Application manifest with the following content:

```yaml
syncPolicy:
  automated: {}
  syncOptions:
    - ServiceSideApply=true
```

Check the UI and see the misspelling.

**Expected behavior**

Check box says "ServerSideApply"

**Screenshots**

![image](https://user-images.githubusercontent.com/29008123/216630275-d0a3d175-bd36-4387-ad4f-ec5f2cc612b7.png)

**Version**

```shell
argocd: v2.5.9+e5f1194.dirty
  BuildDate: 2023-01-28T01:33:14Z
  GitCommit: e5f1194a6de78cc1124179a4c9bb1ae3484fb77d
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jsoref** [comment]
Try doing:
```yaml
syncPolicy:
  automated: {}
  syncOptions:
    - Hello=World
```
