### ISSUE TITLE
After setting up Google w. groups, groups are present in DEX but missing in Argo

### ISSUE THREAD

**Issue by mmisztal1980** [argoproj/argo-cd#12303]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
Configure Google using OIDC & Groups by following [documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-plus-google-groups-using-dex).

```yaml
dex:
  volumes:
  - name: google-json
    secret:
      defaultMode: 420
      secretName: argocd-google-groups-json
  volumeMounts:
  - name: google-json
    readOnly: true
    mountPath: /tmp/oidc

configs:
  cm:
    url: https://argocd.dev.villy.cloud-tek.io
    admin.enabled: false
    exec.enabled: false
    dex.config: |
      connectors:
      - type: google
        id: google
        name: Google
        config:
          redirectURI: https://argocd.dev.villy.cloud-tek.io/api/dex/callback
          clientID: <clientID>.apps.googleusercontent.com
          clientSecret: <clientSecret>
          serviceAccountFilePath: /tmp/oidc/googleAuth.json
          adminEmail: <redacted>@cloud-tek.io
          groups:
          - developers@cloud-tek.io
          - devops@cloud-tek.io

```
**Expected behavior**

I'm expecting all groups I'm a member of to be visible in UserInfo view

**Screenshots**

![image](https://user-images.githubusercontent.com/1357057/217100757-b20c20ec-d2d9-4601-b2ba-4baeade66e44.png)

**Version**

```shell
argocd version --server argocd.dev.villy.cloud-tek.io --grpc-web
argocd: v2.0.3+8d2b13d.dirty
  BuildDate: 2021-05-27T19:03:20Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: dirty
  GoVersion: go1.16.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.5.9+e5f1194
```

**Logs**

Having examined dex-server's logs, I've determined that the groups are returned once logged in.
```shell
k -n argocd logs argo-argocd-dex-server-6cf9bb564-2xqs2
time="2023-02-06T21:52:21Z" level=info msg="login successful: connector \"google\", username=\"Maciej Misztal\", preferred_username=\"\", email=\"<redacted>@cloud-tek.io\", groups=[\"developers@cloud-tek.io\" \"devops@cloud-tek.io\"]"
```

**Comment by mmisztal1980** [comment]
I've found the issue. Not sure it is documented anywhere so I'm going to leave the solution for posterity.

Original HELM values contains a fragment:

```yaml
  rbac:
    scopes: '[email, group]'
    policy.default: role:readonly
```

Apparently, in case of google, plural for group needs to be used, resulting in:

```yaml
  rbac:
    scopes: '[email, groups]'
    policy.default: role:readonly
```

Once that's done, everything works as expected and group memberhips show up in the UserInfo view

**Comment by ssichynskyi** [comment]
I had the same issue with ArgoCD v2.12.4 installed using a helm chart v7.6.7. Groups were still missing although I've initially made `scopes: '[email, groups]'`.
In my case it was resolved by adding `insecureEnableGroups: true` in:
```yaml
configs:
  cm:
    dex.config: |
      connectors:
          config:
            insecureEnableGroups: true
```
