### ISSUE TITLE
 ApplicationSet/git-generator - Add generator parameter: repoURL, revision

### ISSUE THREAD

**Issue by IxDay** [argoproj/argo-cd#12322]
# Summary

It would be useful if the git-generator would include repoURL and generator in it's list of generator parameters

# Motivation

Assuming it's possible to use multiple git-generators in the first place, I'd like to be able to have them pointing at distinct git repositories and or branches. Notice how the (proposed) repoURL and revision parameters are used to populate `spec.template.spec.source.repoURL` and `spec.template.spec.source.revision`.
This can be pretty useful especially when you need to deploy a specific branch for a preproduction test and/or migration

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-stage
spec:
  generators:
     - git:
         repoURL: https://github.com/my-org/service-a.git
         revision: main
         directories:
           - path: k8s-apps/*/*/overlays/stage
     - git:
         repoURL: https://github.com/my-org/service-b.git
         revision: staging
         directories:
           - path: k8s-apps/*/*/overlays/stage
  template:
    metadata:
      name: 'stage-{{path[1]}}-{{path[2]}}'
    spec:
      project: 'my-project'
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        name: my-cluster
        namespace: '{{path[1]}}'
```

# Proposal

See Summary

**Comment by elvis-cai** [comment]
https://github.com/argoproj/argo-cd/issues/12279 similar to this?

**Comment by crenshaw-dev** [comment]
I think the matrix generator workaround in https://github.com/argoproj/argo-cd/issues/12279 is viable here. Please let me know if I'm wrong!

**Comment by IxDay** [comment]
Sadly it is not. I can give you a second example I have in to tackle where this does not work but the addition of parameters would easily solve:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset-stage
spec:
  generators:
     - git:
         repoURL: https://github.com/my-org/service-a.git
         revision: main
         directories:
           - path: k8s-apps/*
           - path: k8s-apps/test
             exclude: true
     - git:
         repoURL: https://github.com/my-org/service-a.git
         revision: test
         directories:
           - path: k8s-apps/test
  template:
    metadata:
      name: 'stage-{{path.basename}}'
    spec:
      project: 'my-project'
      source:
        repoURL: 'https://github.com/my-org/service-a.git'
        targetRevision: '{{revision}}' # <---- No way to put the proper value here without the revision
        path: '{{path}}' 
      destination:
        name: my-cluster
        namespace: '{{path.basename}}'
```
