### ISSUE TITLE
[v2.6.0] Can't preview unapplied manifests from UI 

### ISSUE THREAD

**Issue by DpoBoceka** [argoproj/argo-cd#12339]
**Describe the bug**

When I click on any unapplied resource in UI I get
> Unable to load data: ConfigMap release-name-minio not found as part of application minio

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  source:
    path: path/to/kustomize
    repoURL: https://github.com/my-org/my-repo
    targetRevision: HEAD
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: minio
    version: 5.0.5
    repo: https://charts.min.io
    includeCRDs: true
```
I have not tried it _without_ helm and same thing happened with `external-secrets`. Works fine on v2.5.10 
**Screenshots**
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/20767197/217549963-4152cb8f-5a33-4987-8767-33ad5fe4376d.png">
