### ISSUE TITLE
kustomise with helmCharts uses dummy releaseName if it was not specified explicitly 

### ISSUE THREAD

**Issue by DpoBoceka** [argoproj/argo-cd#12340]
**Describe the bug**

If `helmCharts.releaseName` is left empty in kustomise the charts get rendered with `release-name` value. Strangely enough, it does not happen with `crossplane https://charts.crossplane.io/stable`, but happened with other helm charts, like `external-secrets`
Maybe it's a bug on kustomize side, though, so https://github.com/argoproj/argo-cd/pull/12299 could fix
 
**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  source:
    path: path/to/kustomize
    repoURL: https://github.com/my-org/my-repo
    targetRevision: HEAD
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: minio
    version: 5.0.5
    repo: https://charts.min.io
    includeCRDs: true
    # releaseName: ""
```

**Screenshots**

<img width="896" alt="image" src="https://user-images.githubusercontent.com/20767197/217551579-3b5f65f1-518f-46e5-ac20-1aa6f72f26e1.png">

**Version**
v2.5.10
v.2.6.0
