### ISSUE TITLE
Add a remote API generator 

### ISSUE THREAD

**Issue by scrocquesel** [argoproj/argo-cd#12368]
# Summary

Provide a generator that request its value from a REST or gRPC server.

# Motivation

The list of generators is growing fast but having the opportunity to build new one without touching argocd codebase would be even greater. The remote server can be deployed as a sidecar or be external (requiring authent).

For example, pull request generator is good but you may want to produce a value only when the pipeline attached to the PR is sucessful or a perticular job succeed.

server would receive a map of string,any and return a list of map of string,any like the list generator.

With gRPC, I guess that the server can also stream the response and the argocd client can cache the returned values to be available when applicationset controller reconcile.

# Proposal

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - APIProvider:
      gRPC:
          serverAddr: localhost:9999
          streaming: true
      Rest:
          url: http://foo.bar/banana
          tokenRef: ...
      params:
         param1: value
         param2: value
  template:
```
