### ISSUE TITLE
2.6 - Multi-Source App (external HELM values) doesn't recognize changes in values.yaml

### ISSUE THREAD

**Issue by carslen** [argoproj/argo-cd#12366]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After initial deployment of a multi-sourced Argo App (Helm Chart with external values in GIT repo), changes in the values.yaml file aren't recognized by ArgoCD. I've tried to refresh, hard refresh and sync (tried different Sync options) the App without success.

**To Reproduce**

I've followed the example [Helm value files from external Git repository](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository). Initial deployment of the app worked like a charm, the external `values.yaml` were applied as expected.

Later the `values.yaml` file got adjusted and the changes are not recognized by the multi-source application. ArgoCD is running in a local Kind cluster for testing purpose.

**Expected behavior**

Changed sources should be applied to a multi-source ArgoCD App after initial deployment.

**App definition**
```yaml
destination:
  namespace: prom
  server: https://kubernetes.default.svc
project: default
sources:
  - chart: prometheus
    helm:
      valueFiles:
        - $values/prometheus-test/dev/values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.3.3
  - ref: values
    repoURL: https://github.com/catenax-ng/k8s-stack-config
    targetRevision: HEAD
syncPolicy:
  automated:
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
```
**external Values**

```yaml
server:
  ## Prometheus server container name
  ##
  name: server-lalaland

persistentVolume:
  ## Prometheus server data Persistent Volume labels
  ##
  labels:
    pvc: lalaLand

  ## Prometheus server data Persistent Volume size
  ##
  size: 1Gi
```
For initial deployment of Argo App only `.Values.server.name` was available in the `values.yaml` file, after deployment `.Values.persistentVolume.labels` and `.Values.persistentVolume.size` has been added to `values.yaml` file.

**Version**

```shell
$ argocd version
argocd: v2.5.6+9db2c94.dirty
  BuildDate: 2023-01-11T01:02:03Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.1+3f143c9
  BuildDate: 2023-02-08T18:51:05Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
$ kubectl version --short
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.3
```
