### ISSUE TITLE
Audience validation breaks when reading oidc clientid from secret

### ISSUE THREAD

**Issue by Sir-Jacques** [argoproj/argo-cd#12372]
Checklist:

* [V] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [V] I've included steps to reproduce the bug.
* [V] I've pasted the output of `argocd version`.

**Describe the bug**
We dynamically read-in our clientid from a secret using the syntax (as described in the docs) in the argocd-cm configmap:
(this is only the relevant part of the configmap we used)
```
data:
  oidc.config: |
    name: Azure 
    issuer: "<our hardcoded issuer>"
    clientID: $argocd-jwt:CLIENT_ID
```

This used to work before, but since audience validation was introduced this breaks. I'm assuming the dynamic secret lookup is not working for the default allowedAdience (the default value is the clientID that is provided, we suspect it read the secret-ref syntax as its value where this should be read as a reference to the value instead). 

**To Reproduce**
The config below works, but unfortunately does not lookup the clientID dynamically (requires hardcoded clientid) so is not suitable for our use-case:
```
data:
  oidc.config: |
    name: Azure 
    issuer: "<our hardcoded issuer>"
    clientID: $argocd-jwt:CLIENT_ID
    
    allowedAudiences:
    - <hardcoded clientid from secret mentioned above>
```
In addition, this does NOT work and will keep redirecting to the login page when pressing the "Log in via Azure" button:
```
data:
  oidc.config: |
    name: Azure 
    issuer: "<our hardcoded issuer>"
    clientID: $argocd-jwt:CLIENT_ID
    
    allowedAudiences:
    - $argocd-jwt:CLIENT_ID
```

**Expected behavior**
I expect the default audience validation to use the clientid found in the secret, and not use the secret-ref string as its value.

**Screenshots**

**Version**

```shell
argocd@argocd-server-dbd9f4c6f-sb7qk:~$ argocd version
argocd: v2.6.0+acc554f
  BuildDate: 2023-02-06T21:17:26Z
  GitCommit: acc554f3d99010e0353b498a595844b30090556f
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
go-oidc should log the expected audience when the check fails. 

```go
return nil, fmt.Errorf("oidc: expected audience %q got %q", v.config.ClientID, t.Audience)
```

Can you look at the argocd-server logs and confirm that the expected audience is literally `$argocd-jwt:CLIENT_ID`?

**Comment by Sir-Jacques** [comment]
I'm seeing 2 things in the logs:

Logs from argocd-server:
```
time="2023-02-09T15:13:45Z" level=warning msg="config referenced '$argocd-jwt:CLIENT_ID', but key does not exist in secret"
```

Whereas the secret + key exist:
```
jacco@pc-gg:~$ k get secret -n argocd argocd-jwt -o yaml
apiVersion: v1
data:
  CLIENT_ID: <omitted>
  ISSUER: <omitted>
kind: Secret
metadata:
  creationTimestamp: "2023-02-09T14:56:35Z"
  name: argocd-jwt
  namespace: argocd
type: Opaque
```


Then after trying to access argocd with the SSO client, these logs appear:
```
time="2023-02-09T15:13:45Z" level=warning msg="Failed to verify token: failed to verify token: oidc: expected audience \"$argocd-jwt:CLIENT_ID\" got [\"<the actual clientid>\"]"
```
