### ISSUE TITLE
API call to `/resource/links` endpoint of an application when application controller has additional binaries

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [argoproj/argo-cd#12404]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I add an init container to the argocd-application-controller  to add kubelogin (needed for connecting to AKS) and doctl (needed for connecting to Digital Ocean clusters). But after upgrading to v2.6.1, I am getting the following error when I am trying to open a resource in an Application on the web ui:
```
Unable to load data: error getting resource: Get "https://461e7e24-22c5-469f-8458-f0021f84041f.k8s.ondigitalocean.com/apis/apps/v1?timeout=32s": getting credentials: exec: executable doctl not found It looks like you are trying to use a client-go credential plugin that is not installed. To learn more about this feature, consult the documentation available at: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins install doctl
```
![image](https://user-images.githubusercontent.com/13748882/218119744-ca0cd45b-a72a-4bb1-b25e-7598ee096242.png)

Interestingly, my clusters are still showing "Successful" so the cluster access works!?

On checking the network requests, I see that the above error is getting thrown by the `https://domain/api/v1/applications/cert-manager-do-blr1-beez-dev/resource/links?name=cert-manager&appNamespace=argocd&namespace=cert-manager&resourceName=cert-manager&version=v1&kind=Service&group=` call.

**To Reproduce**

Kustomize the argocd deployment with the following kustomization

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      volumes:
      - emptyDir: {}
        name: custom-binaries
      initContainers:
        - name: download-binaries
          image: alpine:3.17.0
          command:
          - sh
          - -c
          args:
          - >
            apk add unzip &&
            wget -qO- https://github.com/Azure/kubelogin/releases/download/v0.0.11/kubelogin-linux-amd64.zip > kubelogin-linux-amd64.zip &&
            unzip -p kubelogin-linux-amd64.zip bin/linux_amd64/kubelogin > kubelogin &&
            chmod +x kubelogin &&
            mv kubelogin /custom-binaries/ &&
            wget -qO- https://github.com/digitalocean/doctl/releases/download/v1.75.0/doctl-1.75.0-linux-amd64.tar.gz > doctl-1.75.0-linux-amd64.tar.gz &&
            tar -xvf doctl-1.75.0-linux-amd64.tar.gz &&
            chmod +x doctl &&
            mv doctl /custom-binaries/
          volumeMounts:
          - mountPath: /custom-binaries
            name: custom-binaries
      containers:
      - name: argocd-application-controller
        volumeMounts:
            - mountPath: /usr/local/bin/kubelogin
              name: custom-binaries
              subPath: kubelogin
            - mountPath: /usr/local/bin/doctl
              name: custom-binaries
              subPath: doctl
```
Then deploy an application to an external cluster running on AKS or Digital Ocean. Then open the application in the web ui and try to see the details of a single resource.

**Expected behavior**

Pre 2.6, the above kustomization worked flawlessly for deploying applications in external clusters and being able to see all information of said resources.

**Screenshots**

Added above

**Version**

```shell
argocd: v2.6.1+3f143c9
  BuildDate: 2023-02-08T18:51:05Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

Related: #12403 
Creating a separate issue as this issue is probably due to a regression as discussed with @crenshaw-dev
