### ISSUE TITLE
ApplicationSet capability to combine git file generator with list generator to generate apps based on file content

### ISSUE THREAD

**Issue by lsoica** [argoproj/argo-cd#12428]
# Motivation
I have my product environment described in git as a yaml file with an array where each item defines the location of the Helm Chart, its version and the list of value files to be applied.
I want to generate the applications based on the content of this file, one Application for each entry, in a Gitops way where the applications are kept in sync with each change of this file.

# Proposal
The list generator enhanced to accept elementsYaml, so you could use a matrix generator to inject whatever elements you want:
```
generators:
- matrix:
  generators:
  - git:
      files:
      - path: your/path.yaml
  - list:
    elementsYaml: '{{ .thingsFromFile | toYaml }}'
```
