### ISSUE TITLE
ApplicationSet `plugin` generators, based on Workflows' executor plugins

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#12429]
# Summary

https://argoproj.github.io/argo-workflows/executor_plugins/

```yaml
generators:
- plugin:
    hello: {}
```

Call an API, get a set of parameters.
