### ISSUE TITLE
ApplicationSet health check as Application

### ISSUE THREAD

**Issue by Guy-Royburt** [argoproj/argo-cd#12444]
There is an argocd cm extention for apps of apps pattern that I added in resource.customizations.health.argoproj.io_Application and it orchestrating synchronization using sync waves between apps.
Can I use same pattern for ApplicationSets because this way I tried in resource.customizations.health.argoproj.io_ApplicationSet doesn't seem to work well, what is the problem or solution that you suggest with that? 

```apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://github.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
  - |
    resource.customizations.health.argoproj.io_Application=hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs
  - |
    resource.customizations.health.argoproj.io_ApplicationSet=hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs
  name: argocd-cm
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.4.8```

**Comment by thecooldrop** [comment]
I am having the same ideas. Basically I would like to specify the application wave in the config.json file and use that in combination with git file generator. That way I could have a root App with both ApplicationSets and Applications as children and I could ensure that these are all deployed in order.

Thinking about it a bit deeper, this may be problematic, given Applications produced by ApplicationSet are children of the ApplicationSet. I am unsure how the sync waving behaves across multiple levels of child-parent relationships.

**Comment by SnowBiz** [comment]
Did you ever make progress on this? 

I am trying to figure this out as well, the "App of AppSets" pattern is nice for conditional creation of applications (especially using the GitOps Bridge pattern). However, it removes the ability to use sync waves, which is problematic when trying to control deployment order.

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/gitops/multi-cluster-hub-spoke-argocd#deploy-argocd-apps-of-applicationsets-for-addons

For example, If I need the metrics server available for ArgoCD to scale via HPA, but the application controller is crashing from OOM errors due to many applications trying to sync at the same time. Ideally, I would like to ensure the metrics server is healthy before the rest of the apps try to sync.

Since the Application is the product of an ApplicationSet, the ApplicationSet is marked healthy soon as the child application is created. So while I can see the sync waves partially working, it really just leads to all the apps being spawned at the same time and choking out the Application Controller.

I investigated the progressive-sync alpha feature on the applicationSet controller, but this would only be beneficial if I were to use an "appset of apps" pattern, so I do not believe this helps the case either. 

https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/

**Comment by csantanapr** [comment]
I think adding this feature will help for use cases that you have app of applicationsets, like in the gitops-bridge when using for 1 cluster and bootstrapping a set of application set each one with 1 app, and wanting to have this apps in order

TLRD: support the following
```lua
    resource.customizations.health.argoproj.io_ApplicationSet=hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs
```

In stack recently slack thread @jannfis mentioned that it should doable to implement `obj.status.health.status` of the application set based on the health of the children apps that it generates.
If someone wants to work on this PR I think is something that community will benefit

**Comment by csantanapr** [comment]
A workaround I found was to set the sync wave number for each application set, the application controller will reconcile them in order, but it doesn't wait for the application set health status since it doesn't exist to deploy the next application set.
The default time between sync waves is 2 seconds, I increase this to 30 seconds.
```yaml
    controller:
      env:
        - name: ARGOCD_SYNC_WAVE_DELAY
          value: '30'
```
Here is repo I did an experiments, and the bootstrap it took 30 seconds between application sets in order
https://github.com/csantanapr/argocd-experiments-syncwaves/blob/main/terraform/main.tf#L134C1-L137C22

Here is how I set the sync wave
https://github.com/csantanapr/argocd-experiments-syncwaves/blob/main/gitops/bootstrap/addons/aws/addons-aws-load-balancer-controller-appset.yaml#L7

**Comment by SnowBiz** [comment]
Thank you for the workaround, it doesn't completely solve the issue so your above comment would still be a very beneficial feature. However, it does buy some time, and should help with my current issues. Thank you @csantanapr

**Comment by zbialik** [comment]
I think the issue is the CRD for ApplicationSet needs updating. But idk is there's potential code updates needed as a result.

**Comment by whitleykeith** [comment]
I have another workaround that *sorta* works. The AppSet CRD *does* spit out a `status.applicationStatus` block if you have (1) progressive sync enabled and (2) are using the `RollingSync` strategy. It looks like this: 

```yaml

  applicationStatus:                                                                                                                                                                                        
  - application: test-foo                                                                                                                                                                 
    lastTransitionTime: "2024-05-29T16:01:16Z"                                                                                                                                                              
    message: Application moved to Pending status, watching for the Application resource                                                                                                                     
      to start Progressing.                                                                                                                                                                                 
    status: Pending                                                                                                                                                                                         
    step: "1"     
```

I don't really have a need for `RollingSync` in my use-case, but it's relatively trivial to just add a hardcoded label to all the apps and then have a 1-step strategy. What I really needed was to never treat an AppSet as healthy unless *all* downstream apps were healthy, but the current healthcheck treats `ResourcesUpToDate` which effectively means synchronizing the underlying apps would still mark the AppSet as healthy in this case. 

So I modified the healthcheck to not do that, and to also look at `status.applicationStatus`. This is what that looks like:

```lua
local hs = {}

if obj.status ~= nil then
  if obj.status.applicationStatus ~= nil then
    for idx, application in pairs(obj.status.applicationStatus) do
      if application.status == "Degraded" or application.status == "Progressing" then
        hs.status = application.status
        hs.message = application.message
        return hs
      end
    end
    hs.status = "Healthy"
    hs.message = "All Applications are UpToDate and Healthy"
    return hs
  end
  if obj.status.conditions ~= nil then
    for i, condition in pairs(obj.status.conditions) do
      if condition.type == "ErrorOccurred" and condition.status == "True" then
        hs.status = "Degraded"
        hs.message = condition.message
        return hs
      end
    end
  end
end

hs.status = "Progressing"
hs.message = ""
return hs



This version mainly adds a block parsing the `status.applicationStatus` block so that the AppSet will look at the downstream app healths for it's health. 

My version also removes the Healthy condition on `ResourceUpToDate`, effectively meaning that AppSets without Progressive Sync + `RollingSync` strategy can never be healthy, but I didn't want any transient Healthy states happening. It's *probably* okay to add it back

```
