### ISSUE TITLE
ApplicationSet with spec.template.spec.sources: [...] set produces a validation error

### ISSUE THREAD

**Issue by lhriley** [argoproj/argo-cd#12446]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`ApplicationSet` with `spec.goTemplate: true` and `spec.template.spec.sources: [...]` set produces a validation error.

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-preview-app
  namespace: argocd
spec:
  goTemplate: true

  generators:
    - pullRequest:
        github:
          owner: foo
          repo: bar
          tokenRef:
            secretName: github-token
            key: token
          # Labels is used to filter the PRs that you want to target. (optional)
          # Need Preview is a Github provided label
          labels:
            - Need Preview
        requeueAfterSeconds: 120

  template:
    metadata:
      name: 'pr-{{ .number }}-{{ normalize .branch }}'
      namespace: previews

    spec:
      project: previews

      destination:
        server: https://kubernetes.default.svc
        namespace: 'pr-{{ .number }}-{{ normalize .branch }}'

      sources:
        - repoURL: git@github.com:foo/helm-values.git
          targetRevision: main
          ref: helm-values
        - repoURL: https://github.com/foo/helm-charts.git
          targetRevision: main
          path: charts/app
          helm:
            valueFiles:
              - $helm-values/helm/common/app-common-values.yaml
              - $helm-values/helm/preview/app-preview-values.yaml

            parameters:
              - name: "image.tag"
                value: '{{ regexReplaceAllLiteral "[^a-zA-Z0-9]*" .branch ""  | trunc 40 | lower }}'

      syncPolicy:
          automated:
              allowEmpty: true
              prune: true
              selfHeal: true

          syncOptions:
            - CreateNamespace=true

```

**Expected behavior**

When using `sources`, `source` should not be a required field to pass validation.

**Screenshots**

n/a

**Version**

```shell
❯ argocd version
argocd: v2.6.0+acc554f.dirty
  BuildDate: 2023-02-07T01:28:26Z
  GitCommit: acc554f3d99010e0353b498a595844b30090556f
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.1+3f143c9
  BuildDate: 2023-02-08T18:51:05Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
time="2023-02-14T00:25:53Z" level=error msg="finished unary call with code Unknown" error="error getting cached app state: InvalidSpecError: spec.source.repoURL and either spec.source.path or spec.source.chart are required" grpc.code=Unknown grpc.method=ResourceTree grpc.service=application.ApplicationService grpc.start_time="2023-02-14T00:25:53Z" grpc.time_ms=7.063 span.kind=server system=grpc
```
