### ISSUE TITLE
Enhance ApplicationSet generator

### ISSUE THREAD

**Issue by nerzhul** [argoproj/argo-cd#12454]
# Summary

Currently application set can generate various things, but it's only strings.

This doesn't permit to handle properly the arrays, like ignoreDifferences.

# Motivation

See the way we currently do to use a big appset generator permitting to ignore one object difference with max 5 fields

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-main
spec:
  generators:
  - matrix:
      generators:
      - git:
          files:
          - path: '*/config.json'
          repoURL: https://git.repo/git
          revision: 'main'
      - clusters: {}
  template:
    metadata:
      name: '{{path[0]}}-{{name}}'
    spec:
      ignoreDifferences:
      - group: '{{ignoreDifferences.0.group}}'
        kind: '{{ignoreDifferences.0.kind}}'
        name: '{{ignoreDifferences.0.name}}'
        namespace: '{{ignoreDifferences.0.namespace}}'
        jsonPointers:
          - '{{ignoreDifferences.0.jsonPointers.0}}'
          - '{{ignoreDifferences.0.jsonPointers.1}}'
          - '{{ignoreDifferences.0.jsonPointers.2}}'
          - '{{ignoreDifferences.0.jsonPointers.3}}'
          - '{{ignoreDifferences.0.jsonPointers.4}}'
```

# Proposal

I think it should be possible to put an array in config.json files and argo uses it for ignore differences. It's clearly harder for validation webhook to ensure it's always proper
