### ISSUE TITLE
ApplicationSet delete managedNamespaceMetadata when generate Application

### ISSUE THREAD

**Issue by disaster37** [argoproj/argo-cd#12464]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

ApplicationSet not set `managedNamespaceMetadata` section when generate application.

**To Reproduce**

Create applicationSet that contain on template the section  `managedNamespaceMetadata`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
      - cluster: in-cluster
  template:
    metadata:
      name: 'test'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: default
      destination:
        namespace: default
        name: '{{ cluster }}'
      source:
        repoURL: https://github.com/xxx.git
        path: 'test/'
        targetRevision: 'master'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            field.cattle.io/projectId: p-wd2xt
          annotations:
            field.cattle.io/projectId: c-57d7n:p-wd2xt
            field.cattle.io/resourceQuota: '{"limitsCpu":"8","limitsMemory":"8Gi","requestsStorage":"60Gi"}'
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
```

**Expected behavior**

It generate Application that contain section `managedNamespaceMetadata`

**Screenshots**

**Version**

```shell
ArgoCD 2.6.1
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by disaster37** [comment]
Yes I have loaded (kubectl replace) from 2.6.1 tag repository and /manifest/crds

**Comment by crenshaw-dev** [comment]
Hm. You've confirmed your ApplicationSet CRD is up to date as well?

**Comment by dmpe** [comment]
Yes, i can also confirm the same behavior on my end. Exactly as described, the generated `application` does not have `managedNamespaceMetadata` section, hence no labels/annotations are properly attached. 

My CRDs are also up to date and we are using 2.7.7 argocd version.

**Comment by blakepettersson** [comment]
I can't reproduce this.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-test
  namespace: argocd
spec:
  generators:
    - clusters: {}
      selector:
        matchExpressions:
          - key: server
            operator: In
            values:
              - https://kubernetes.default.svc
  template:
    metadata:
      name: guestbook
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        path: helm-dependency
        targetRevision: 'master'
        helm:
          valueFiles:
            - 'values.yaml'
      destination:
        namespace: guestbook
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
        syncOptions:
          - CreateNamespace=true
```

Gives this `Application` spec:

<img width="541" alt="Screenshot 2023-07-27 at 22 17 41" src="https://github.com/argoproj/argo-cd/assets/1227954/ea0aace9-4d90-4478-9c1a-204df5c9db23">

**Comment by dmpe** [comment]
I think my case is a bit different and that is likely the issue - I have following `ApplicationSet` which points to a gitlab repository.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: abc-application-set
spec:
  generators:
  - list:
      elements:
      - name: uat
        branch: branch_b
      - name: copy
        branch: branch_a
  template:
    metadata:
      name: 'abc-{{name}}-apps'
      labels:
        env: '{{name}}'
    spec:
      project: 'abc'
      source:
        repoURL: 'https://gitlab.firm.com/abc/argocd.git'
        path: 'lib/argocd/'
        targetRevision: '{{branch}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        managedNamespaceMetadata:
          annotations:
            field.cattle.io/projectId: c-m-d658bggg:p-7p8rj # Cluster ID
          labels:
            field.cattle.io/projectId: p-7p8rj
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - RespectIgnoreDifferences=true
        - CreateNamespace=true
        automated:
          prune: true
```

Inside of that repository, in branch e.g. `branch_a`, in folder `lib/argocd/` I dont have a helm chart but rather further individual `Application`s -> so it is more akin to https://github.com/argoproj/argocd-example-apps/blob/master/apps approach ("App of Apps"). The individual `Application`s do not have `managedNamespaceMetadata` section on them, only `syncOptions` which might be slightly different for each application due to variety of reasons. The default `ApplicationSet` however does contain `syncOptions` with values. 
So i guess that Application has higher priority and thus it is being used for the actual deployment. And if it does not have `managedNamespaceMetadata` it wont inherit it as well (and that would be my expectation, to maintain it only once globally).
