### ISSUE TITLE
Add helm parameter block from one file

### ISSUE THREAD

**Issue by franroa** [argoproj/argo-cd#12469]
# Summary

We have the possibility of adding helm values and helm parameters, but it would be nice to be able to get a block of values from a file instead of the whole file.

# Motivation

If you want to have all the info for your releases in a file, you will have also the values defined there. Something like:
```
name: "postgresql"
chart: "postgresql"
team: "<my-team>"
repoURL: "https://charts.bitnami.com/bitnami"
values: |
  fullnameOverride: "postgres"
  image:
    tag: 13.9.0-debian-11-r15
  metrics:
    enabled: true
    image:
      tag: 0.11.1-debian-11-r39
```

# Proposal
We could: 
- Get the values from the yaml file and insert into the as params or
- Get the values from the values and create a values file from it
 
 Then you could add it to the ApplicationSet as a third method:
 - value file
 - parameter 
 - value block
