### ISSUE TITLE
Multi-source doesn't work with CMPs

### ISSUE THREAD

**Issue by gczuczy** [argoproj/argo-cd#12476]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The new multi-source feature does not work with CMPs

**To Reproduce**

1. Define multiple sources in an application
2. Mix a plugin which is expected to work on multiple sources at once

**Expected behavior**

Multi-sources can work with CMPs

**Version**

```shell
argocd: v2.6.1-inhouse+stuff
  BuildDate: 2023-02-15T08:15:44Z
  GitCommit:
  GitTreeState: clean
  GoVersion: go1.20
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Tried multiple ways.
When trying to "chain" the avp in the sources:
```
  - ref: valuesrepo
    repoURL: https://github/valuesrepo.git
    targetRevision: master
  - chart: ourchart
    helm:
      valueFiles:
      - $valuesrepo/dev/values.yaml
    ref: chart
    repoURL: https://inhouse/helmrepo
    targetRevision: 0.42.69
  - plugin:
      name: argocd-vault-plugin
    repoURL: $chart
```
The error is:
```
spec.source.repoURL and either source.path, source.chart, or source.ref are required for source {$chart nil nil nil &ApplicationSourcePlugin{Name:argocd-vault-plugin,Env:[]*EnvEntry{},Parameters:[]ApplicationSourcePluginParameter{},} }```
```

When we're trying to handle the helm chart with a plugin, and passing the values simply through en envvar:
```
  - ref: valuesrepo
    repoURL: https://github/valuesrepo.git
    targetRevision: master
  - chart: ourchart
    repoURL: https://inhouse/helmrepo
    targetRevision: 0.42.69
    plugin:
      name: "avp-helm-values"|
      env:
        - name: VALUES
          value:  $valuesrepo/dev/values.yaml
```
The error is quite "funny". Helm template is not able to find the file, and the null values in the template's values are not getting replaced by `<placeholders>`, and the template generation is being terminated by `require` templating directive, which argocd treats as a successful run, and we're getting nothing but orphaned resources.

So, it doesn't really matter with what way, but somehow plugins are needed to do placeholder replacements for secrets management. This is kind of a blocker for us, with the cleanup work that the sources offers (separating deployment logic into charts, and environment specifics into values stored separately).
