### ISSUE TITLE
deletion prevention 

### ISSUE THREAD

**Issue by ofirshtrull** [argoproj/argo-cd#12470]
# Summary

by mistake last week I almost made a change that could have deleted a full applicationset in my  prod
(Luckey it was stoped in pr)
I think maybe we a new annotation can be added to applicationsets and applications that if there it will prevent a deletion on the argo resource 

# Motivation

such as 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
  label: 
    deletion_prevention: true
spec:
  generators:
```

or don't have two ApplicationSet/Applications with the same name and having the new one by mistake delete the old one
