### ISSUE TITLE
Multi-source apps should get an option to combine sources and render them together

### ISSUE THREAD

**Issue by lippertmarkus** [argoproj/argo-cd#12471]
# Summary

For [multi-source apps](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/) there are cases where it would make sensor to put the files of one source into the directory of another source and render them together

# Motivation

Source 1: Helm Chart which uses ` .Files.Glob  "**.json"` to put configuration files into configmaps.
Source 2: Git Repo with additional json files that should be put into the configmaps by the Helm Chat (Source 1) as well.

# Proposal

Could be implemented similarly like with the `helm.valueFiles`. Example:

```
  sources:
    - repoURL: https://github.com/example/my-json-files.git
      targetRevision: HEAD
      path: '.'
      ref: myjsonfiles
    - chart: myhelmchart
      repoURL: example.com/myhelmrepo
      targetRevision: 0.1.0
      additionalFiles
         - $myjsonfiles
```

**Comment by crenshaw-dev** [comment]
Would you just put the files in a subdirectory called “myjsonfiles”?

**Comment by lippertmarkus** [comment]
For the example outlined above, that would be enough as ` .Files.Glob  "**.json"` would find the files in any subdirectory. For others however this might should be configurable, what do you think?

**Comment by crenshaw-dev** [comment]
Fair. Maybe:

```yaml
  sources:
    - repoURL: https://github.com/example/my-json-files.git
      targetRevision: HEAD
      path: '.'
      ref: myjsonfiles
    - chart: myhelmchart
      repoURL: example.com/myhelmrepo
      targetRevision: 0.1.0
      from:
         - ref: $myjsonfiles
           destination: ./myjsonfiles
```

That would leave room for things like `exclude: **/*.tar.gz` or `renderFirst: true`.
