### ISSUE TITLE
Unhelpful "TypeError: Cannot read properties of undefined (reading 'chart')" error message when helm registry is not listed in sourceRepos

### ISSUE THREAD

**Issue by morremeyer** [argoproj/argo-cd#12487]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

I have not seen any report with this error message, so I'm opening this for two reasons so that people running into it don't need to look for the reason for… as long as I did

**Describe the bug**

When a multi source Application uses a helm repository that is not listed in its project's `sourceRepos`, the frontend only displays:

```
TypeError: Cannot read properties of undefined (reading 'chart')
```

This might also happen for single source applications, but I have not tested it.

**To Reproduce**

Create a multi source `Application` in a `Project` that does not have the referenced helm chart registry in the `allowedSources`, e.g.:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver-cluster-name
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: clusters
  sources:
    - repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
      chart: aws-ebs-csi-driver
      targetRevision: 2.17.0
      helm:
        releaseName: aws-ebs-csi-driver
        valueFiles:
          - $values/argocd-apps/clusters/aws-ebs-csi-driver/values.yaml
    - repoURL: https://github.com/org/repo
      targetRevision: main
      ref: values
  destination:
    namespace: kube-system
    name: cluster-name
```

**Expected behavior**

A clear error message saying that the helm chart repository is not listed in the `sourceRepos` for the project.

**Screenshots**

**Version**

Output is from the web frontend since the CLI is not working for me right now

```shell
v2.6.1+3f143c9
```

**Logs**

None relevant seen from any ArgoCD pods
