### ISSUE TITLE
PersistentVolumeClaims created by a CRD

### ISSUE THREAD

**Issue by KarstenSiemer** [argoproj/argo-cd#1250]
Hello,

I using am prometheus as a crd by prometheus-operator and checked my manifest into argocd.
Everything is being recognized by argocd as healthy but the persistent volume claims.
Argocd wants to remove them, since it does not fully understand the crd.
Now the pvc are constantly in terminating mode, which is extremely annoying.

I am using prometheus-operator 0.29
Kubernetes 1.13.4
and argocd v0.12.0-r3

I read in the change nodes, that this might be possible through lua scripting, yet i don't know how this could be done.
Any help would be greatly appreciated

**Comment by jessesuen** [comment]
Which set of prometheus-operator manifests are you deploying? We actually run prometheus-operator ourselves (from the helm chart), but have not encountered this.

**Comment by KarstenSiemer** [comment]
I tried to remove unnecessary information from the yamls to not bloat this thred, like ingresses and such stuff.

I am using a kustomize manifest that i created myself. This is the app:
 
```
→  argocd app get kube-prometheus -o yaml
metadata:
  creationTimestamp: "2019-03-12T11:04:56Z"
  generation: 472
  labels:
    app.kubernetes.io/instance: argocd-apps
  name: kube-prometheus
  namespace: system-cicd
spec:
  destination:
    namespace: system-monitoring
    server: https://kubernetes.default.svc
  project: system-monitoring
  source:
    path: system-monitoring/kube-prometheus
    repoURL: ssh://git@somerepo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
status:
  health:
    status: Healthy
  operationState:
    phase: Succeeded
    startedAt: "2019-03-12T15:40:19Z"
    syncResult:
      resources:
      - group: ""
        kind: PersistentVolumeClaim
        message: pruned
        name: prometheus-kube-prometheus-db-prometheus-kube-prometheus-1
        namespace: system-monitoring
        status: Pruned
        version: v1
      - group: ""
        kind: PersistentVolumeClaim
        message: pruned
        name: prometheus-kube-prometheus-db-prometheus-kube-prometheus-0
        namespace: system-monitoring
        status: Pruned
        version: v1
      - group: monitoring.coreos.com
        kind: Prometheus
        message: prometheus.monitoring.coreos.com/kube-prometheus unchanged
        name: kube-prometheus
        namespace: system-monitoring
        status: Synced
        version: v1
      revision: 271cd587d8957e4ae2e1002fcfee3b2c9bcd90c4
      source:
        path: system-monitoring/kube-prometheus
        repoURL: ssh://git@somerepo.git
        targetRevision: HEAD
  resources:
  - group: monitoring.coreos.com
    health:
      status: Healthy
    kind: Prometheus
    name: kube-prometheus
    namespace: system-monitoring
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: prometheus-kube-prometheus-db-prometheus-kube-prometheus-1
    namespace: system-monitoring
    status: OutOfSync
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: prometheus-kube-prometheus-db-prometheus-kube-prometheus-0
    namespace: system-monitoring
    status: OutOfSync
    version: v1
  sync:
    comparedTo:
      destination:
        namespace: system-monitoring
        server: https://kubernetes.default.svc
      source:
        path: system-monitoring/kube-prometheus
        repoURL: ssh://git@somerepo.git
        targetRevision: HEAD
    revision: 271cd587d8957e4ae2e1002fcfee3b2c9bcd90c4
    status: OutOfSync
```
This is the yaml from prometheus that was created by kustomize (i again removed unnecessary stuff) :
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: v2.7.2
  name: kube-prometheus
  namespace: system-monitoring
spec:
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/version: v2.7.2
      thanos-store-api: "true"
  replicas: 2
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
        storageClassName: csi-rbd
```

I could probably overcome this by adding the two pvc into the kustomize manifest, but this destroys the beauty of just upping the replicas for new instances to be created
