### ISSUE TITLE
Support git repository in bucket (aws s3, az blob storage) 

### ISSUE THREAD

**Issue by pie-r** [argoproj/argo-cd#12509]
# Summary

ArgoCD support gitRepository, and currently you need a real git backend repository.

What I propose is to use a bucket configured as a git repository.

# Motivation

I'm not asking to use a bucket instead of a git repository, but use a bucket as a git repository (with less feature and support)

# Proposal

Reference: https://github.com/argoproj/argo-cd/issues/9925 (Here the requirement is to support a bucket withouth git)

In my testing, I has been able to configure an azure blob storage as a git repository but the link between argocd is not working completely.

This is the error given by argocd repo-server:
```
repo-server | ERRO[3737] finished unary call with code Unknown         error="error testing repository connectivity: unexpected EOF" grpc.code=Unknown grpc.method=TestRepository grpc.service=repository.RepoServerService grpc.start_time="2023-02-17T11:33:40+01:00" grpc.time_ms=1250.407 span.kind=server system=grpc
```

To reproduce, first create an azure blob storage:
- configure it as public so we don't have to care of the authentication for the moment
- create a "container" in the blob storage called `repo-1`

Now from your laptop we prepare the git repository:
```
mkdir repo-1
cd repo-1
git init
git add .
git commit -m 'initial commit'
git update-server-info
```

Copy the full content of the .git folder, inside the container `repo-1` (you can use azCopy, or Azure Storage Explorer application)

![image](https://user-images.githubusercontent.com/53210578/219631231-5ae7a116-bf28-4dbb-be38-fea50dd260cf.png)

If you have not enable authentication/firewall in the blob storage account, running the git clone below from you localhost should work:
```
git clone https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/repo-1
Cloning into 'repo-1'...
Fetching objects: 18, done.
```

Great! You are cloning from a bucket. 

The next step is configure the "repository" in ArgoCD:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: repo-1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default # The project should be the project that refere to this repository, not default
  name: repo-1
  url: https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/repo-1
```

From the UI the Connection Status is `Fail` and from the logs:
```
repo-server | ERRO[3737] finished unary call with code Unknown         error="error testing repository connectivity: unexpected EOF" grpc.code=Unknown grpc.method=TestRepository grpc.service=repository.RepoServerService grpc.start_time="2023-02-17T11:33:40+01:00" grpc.time_ms=1250.407 span.kind=server system=grpc
```

From this point I had to start argocd locally and look at what is going on.
the failing code returning `Unexpected EOF` is part of the git library in use:

https://github.com/argoproj/argo-cd/blob/9476ab5e18be34a8cfc81150c94d08eefe3cee25/util/git/workaround.go#L51

I stopped my investigation at this point.
