### ISSUE TITLE
Docs: ApplicationSet git files generator: {{path}} should be {{path.path}}

### ISSUE THREAD

**Issue by mildmojo** [argoproj/argo-cd#12502]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I think the [Git Generator: Files docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#git-generator-files) need a small fix, changing `{{path}}` to `{{path.path}}`.

The docs say that when the generator finds a file, it produces a generator parameter called `path` that you can use in your Application template, which expands to the full git repo path to the file, not including the filename.

However, `path` is actually an object, not a string, and expands to some kind of object notation in the resulting Application resource. Instead, the documentation should suggest `path.path`, which is the actual string containing the path to the file.

**To Reproduce**

1. Create a git repo with a helm chart in it, say `/my-cluster/my-app/Chart.yaml` and `/my-cluster/my-app/values.yaml`.
2. Create an ApplicationSet custom resource for your ArgoCD deployment:

```yaml
# my-applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: my-namespace
spec:
  generators:
  - git:
      repoURL: https://github.com/my-user/my-repo
      revision: HEAD
      files:
      - path: /**/values.yaml
  template:
    metadata:
      name: my-app
    spec:
      project: my-project
      source:
        repoURL: https://github.com/my-user/my-repo
        targetRevision: HEAD
        path: {{ path }}
      destination:
        server: https://my-cluster-endpoint
        namespace: my-namespace
```
3. Deploy the ApplicationSet:
   `kubectl create -f my-applicationset.yaml`
5. Wait a bit and read the resulting Application resource:
   `kubectl describe -n my-namespace application my-app`

**Expected behavior**

The Application resource should have `spec.source.path` set to `my-app`.

**Actual behavior**

The resulting Application resource has `spec.source.path` set to an object representation, in which you can see the desired value under the `path` property:

```yaml
path: >-
      map[basename:my-app basenameNormalized:my-app filename:values.yaml
      filenameNormalized:values.yaml path:my-cluster/my-app segments:[my-cluster
      my-app]]
```

**Version**

ArgoCD CLI version:

```shell
argocd: v2.5.2+148d8da.dirty
  BuildDate: 2022-11-07T18:41:19Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: dirty
  GoVersion: go1.19.3
  Compiler: gc
  Platform: linux/amd64
```

ArgoCD server version:

```json
{
    "Version": "v2.5.1+504da42",
    "BuildDate": "2022-11-01T21:14:30Z",
    "GitCommit": "504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```
