### ISSUE TITLE
Merge generator with git and pull request not working

### ISSUE THREAD

**Issue by rmgpinto** [argoproj/argo-cd#12516]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I have a repo with directories for apps, ex:
```
app1
 - Chart.yaml
 - values.yaml
 - template (contains helm files)
app2
 - Chart.yaml
 - values.yaml
 - template (contains helm files)
```

I'm trying to solve the following use case:
- always deploy HEAD
- if a PR is created, override the HEAD files with the branch files

ApplicationSet.yaml:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
  name: apps
  namespace: argocd
spec:
  generators:
  - merge:
      mergeKeys: ["repo"]
      generators:
      - git:
          directories:
          - path: "*"
          repoURL: git@github.com:<ORG>/<REPO>.git
          revision: HEAD
      - pullRequest:
          github:
            owner: <ORG>
            repo: <REPO>
            tokenRef:
              key: token
              secretName: github-token
  goTemplate: true
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      name: '{{.path.basename}}'
    spec:
      destination:
        namespace: '{{.path.basename}}'
        server: https://kubernetes.default.svc
      project: apps
      source:
        helm:
          parameters:
            - name: environment
              value: staging
          valueFiles:
          - values-staging.yaml
        path: '{{.path.basename}}'
        repoURL: git@github.com:<ORG>/<REPO>.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```

**Version**

```shell
argocd: v2.6.2+6e02f8b
  BuildDate: 2023-02-16T15:05:14Z
  GitCommit: 6e02f8b23201b0620a4ff1bce5d38229ba1eb02e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/arm64
```

**Comment by rmgpinto** [comment]
Oh... it works when I open a PR, but when I delete it, it deletes the app.
Is there a way to keep the app from the git generator?

**Comment by rmgpinto** [comment]
I need a key for `mergeKeys` on both generators. Are there any that can be used?
I tried a Matrix generator, but when I close the PR, the application is deleted.

**Comment by rmgpinto** [comment]
@crenshaw-dev is this possible? Thanks

**Comment by rzala** [comment]
@rmgpinto have you found a solution to this?

**Comment by rmgpinto** [comment]
Yes, `repoURL` is the common key.

**Comment by crenshaw-dev** [comment]
@omegion can you elaborate? Are you still facing an issue?

**Comment by omegion** [comment]
@crenshaw-dev Sure, thnx for your response. I am trying to deploy a PR change to a specific cluster for a test. When I change a manifest, I would like to deploy the change to a cluster and then merge.

Since I use `AppSet` i cannot just alter a branch of an `app` because it will get overwritten. So, I am trying to work with `pullRequest` so I can achieve this but it seems the two generator does not really work together.

```yaml
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - preview
          - pullRequest:
              github:
                owner: x
                repo: x
                appSecretName: x
                labels:
                  - deploy
              requeueAfterSeconds: 60
 ...
 targetRevision: '{{ if index . "labels" }}{{ if has .name .labels }}{{ .branch }}{{ else }}example-app{{ end }}{{ else }}example-app{{ end }}'
 ...
```

This won't work because there is no common key :/
