### ISSUE TITLE
Multi-source application health and sync status not updated

### ISSUE THREAD

**Issue by lsoica** [argoproj/argo-cd#12526]
**Describe the bug**

When applying a multi source app, the application gets created, but the state is shown as status: OutOfSync & health: missing both in Argo GUI and object status.

**To Reproduce**

Apply a manifest like:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multisourceapplication
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true        
  destination:
    server: https://kubernetes.default.svc
    namespace: multisourceapp
  sources:
  - repoURL: 'https://stefanprodan.github.io/podinfo/'
    chart: podinfo
    targetRevision: "5.1.0"
    helm:
      valueFiles:
      - $environment/configuration/applicationservices/podinfo-values.yaml
  - repoURL: 'https://<redacted git server and repo name>.git'
    targetRevision: HEAD
    ref: environment
```
Then check the application object status:
```
NAMESPACE   NAME                     SYNC STATUS   HEALTH STATUS
argocd      multisourceapplication   OutOfSync     Missing
```
Check the application status in the UI:
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/1623282/219879773-221c05e8-440e-41a3-b33a-09852c9e992f.png">

Check the pods and services in the  multisourceapp namespace:
```
$ kubectl get pods,svc -n multisourceapp
NAME                                                  READY   STATUS    RESTARTS   AGE
pod/multisourceapplication-podinfo-6958f58b56-8kk5z   1/1     Running   0          12m

NAME                                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/multisourceapplication-podinfo   ClusterIP   10.43.51.56    <none>        9898/TCP,9999/TCP   12m
```

**Expected behavior**

App Health should be "Healthy" and Synced Status should be "Synced"
**Version**

```
v2.6.2+6e02f8b
```
