### ISSUE TITLE
Sync status left inconsistent after a multi source application definition update

### ISSUE THREAD

**Issue by lsoica** [argoproj/argo-cd#12528]
**Describe the bug**

Updating the definition of a multi source application leaves its sync status in OutOfSync state.

**To Reproduce**

Apply a manifest like:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multisourceapplication
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true        
  destination:
    server: https://kubernetes.default.svc
    namespace: multisourceapp
  sources:
  - repoURL: 'https://stefanprodan.github.io/podinfo/'
    chart: podinfo
    targetRevision: "5.1.0"
    helm:
      valueFiles:
      - $environment/configuration/applicationservices/podinfo-values.yaml
  - repoURL: 'https://<redacted git server and repo name>.git'
    targetRevision: HEAD
    ref: environment
```
Refresh the app in order to move to "Healthy" and "Synced".
Update targetRevision to
```
    targetRevision: "5.1.1"
```

Then check the application status: the new revision is applied, the app health is reported as "Healthy" but the Sync Status is reported as "OutOfSync"

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/1623282/219880990-abfe40cb-4396-42ca-aa3d-d8921a931d8e.png">

**Expected behavior**
Progress to the new targetRevision, report app health as "Healthy" and Sync Status as "Synced"

**Version**

```
v2.6.2+6e02f8b
```
