### ISSUE TITLE
No ApplicationSet reconciliation triggered for cluster generators in matrix and merge generators

### ISSUE THREAD

**Issue by alexandrevilain** [argoproj/argo-cd#12542]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When updating a cluster in ArgoCD a new reconciliation is triggered for all ApplicationSets with a cluster generator matching this cluster.

But when updating a cluster in ArgoCD no reconciliation is triggered for all ApplicationSets with a matrix or a merge generator with a cluster generator matching the updated cluster.

**To Reproduce**

1. Create two ApplicationSets:
- an ApplicationSet with the cluster generator as 1st level generator:
```yaml
generators:
- clusters:
    selector:
      matchLabels:
        argocd.argoproj.io/secret-type: cluster
 ```
-  an ApplicationSet with a matrix or a merge generator with a cluster generator as a child:
```yaml
generators:
# matrix 'parent' generator
- matrix:
    generators:
      # git generator, 'child' #1
      - git:
          repoURL: https://github.com/argoproj/argo-cd.git
          revision: HEAD
          directories:
            - path: applicationset/examples/matrix/cluster-addons/*
      # cluster generator, 'child' #2
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
```
3. Update a cluster. For instance, set a label.
4. You'll see in applicationset-controller logs that a reconciliation is triggered for the ApplicationSet with the cluster generator but no reconciliation is triggered for ApplicationSet with the matrix generator.

**Expected behavior**

When  a cluster is updated, any ApplicationSet matching the cluster in one of its nested generator should be reconcilied.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:30:45Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.0+acc554f
```

**Logs**

N/A, see reproducing steps.
