### ISSUE TITLE
App summary page shows error for application deployed to different namespace than "argocd"

### ISSUE THREAD

**Issue by cyvcloud** [argoproj/argo-cd#12541]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Configuring ArgoCD to allow application in [other namespaces than "argocd"](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/) and creating such an application results in an error when opening the application summary.

**To Reproduce**

- Configure ArgoCD according to [this](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/).
- Create application:
  ```yaml
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: guestbook
    namespace: test-argocd
  spec:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: casculate
    source:
      path: helm-guestbook
      repoURL: https://github.com/argoproj/argocd-example-apps.git
      targetRevision: master
  ```
- Open app details page

**Expected behavior**

The app summary page should not show any error.

**Screenshots**

![image](https://user-images.githubusercontent.com/94445975/220093072-0308e092-c111-46fd-acf2-9e29151f8204.png)

**Version**

```shell
argocd: v2.6.1+3f143c9.dirty
  BuildDate: 2023-02-08T22:29:25Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: dirty
  GoVersion: go1.19.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.6.2+6e02f8b
```

**Logs**

Failing frontend request:
```
GET /api/v1/applications/guestbook/links HTTP/1.1
Host: localhost:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
Accept: */*
Accept-Language: de
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Referer: https://localhost:9000/applications/test-argocd/guestbook?view=tree&resource=&node=argoproj.io%2FApplication%test-argocd%2Fguestbook%2F0
Cookie: argocd.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTY3Njk3ODQ4NywibmJmIjoxNjc2ODkyMDg3LCJpYXQiOjE2NzY4OTIwODcsImp0aSI6IjYxNzZkYzNkLWE4MzMtNDA3ZC1hMWQxLWNjMmM3ZjM5YTlkNSJ9.eviiqajxCocYNuyV1LhrY6q7wclq2LcvtScwgmvMLOQ
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
```
```json
{"error":"error getting application","code":2,"message":"error getting application"}
```
