### ISSUE TITLE
ArgoCD DEX Server Deployment Healthchecks in Deployment

### ISSUE THREAD

**Issue by D3vl0per** [argoproj/argo-cd#12544]
# Summary
The liveness and readiness probe are missing from the ArgoCD DEX IdP deployment manifest.

# Motivation
I wanted to release the DEX service using GCP GLB, but due to the missing health check, I keep getting an error message "Error: Server Error", because GLB cannot check if the service is running. GLB tries to perform the health check based on the liveness and readiness probes in the deployment manifest. A separate GCP backend config CRD and a service annotation can be used to get around this, but including these health check probes in the deployment would be more beneficial regardless of my use case. 

# Proposal
Add these probes to `argocd-dex-server` Deployment manifest:
```
livenessProbe:
    httpGet:
      scheme: HTTP
      path: /healthz/live
      port: 5558
readinessProbe:
    httpGet:
      scheme: HTTP
      path: /healthz/ready
      port: 5558
```
