### ISSUE TITLE
ApplicationSet : support Application.labels and Application.annotations

### ISSUE THREAD

**Issue by lchastel** [argoproj/argo-cd#12552]
# Summary
When using Application, I could specify some labels, which allows me to filter the applications more easily.
When using ApplicationSet, I would like to be able to add some labels to Application to have the same feature.

# Motivation

Allow to filter Applications with labels if they are created with Application or ApplicationSet.

# Proposal
<pre>
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-project
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true    
  generators:
  - clusters:
      selector:
       ...
  template: 
    metadata:
      name: "my-application-{{ .... }}"
      <b>labels:
        my-label-1: "value1"
        ....</b>
    spec:
      project: my-project
      source:
        ....
      destination:
        ....
</pre>

**Comment by rumstead** [comment]
You can in the applicationset.spec.template.metadata. 

```
❯ k explain applicationset.spec.template.metadata
KIND:     ApplicationSet
VERSION:  argoproj.io/v1alpha1

RESOURCE: metadata <Object>

DESCRIPTION:
     <empty>

FIELDS:
   annotations	<map[string]string>

   finalizers	<[]string>

   labels	<map[string]string>
```

```
 apiVersion: argoproj.io/v1alpha1
 kind: ApplicationSet
 metadata:
   name: my-app-appset
   namespace: not-argocd
 spec:
   generators:
       - merge ....
       - git ....
       - cluster ...
   template:
     metadata:
       name: 'my-app'
       labels:
         // using values from cluster secret labels
         environment: '{{metadata.labels.environment}}'
         region: '{{metadata.labels.cluster.region}}'
         foo: bar
     spec:
       project: not-default
       source:
           helm/git location ... 
       destination:
         namespace: some-ns
         server: '{{server}}'
       syncPolicy:
         automated:
           prune: true
```
