### ISSUE TITLE
sourceNamespace not respected (by ArgoCD GUI?)

### ISSUE THREAD

**Issue by riccardodimaria** [argoproj/argo-cd#12561]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The institute/organisation is running ArgoCD in production for in-house services (which are deployed in-cluster, and for which ArgoCD-Applications are deployed in `argocd` namespace), and for client services (which are deployed to downstream clusters through Rancher+Harvester, and for which ArgoCD-Applications are deployed in `argocd-CLIENT` namespace).

If `metadata.name` for an Application is left unchanged for deployments in `argocd` and `argocd-CLIENT`, ArgoCD GUI switches/flashes view from one deployment to another. Similar behaviour was observed before the introduction of `sourceNamespace` feature.

**To Reproduce**

Service to deploy in both in-cluster and client's cluster (`Chart.yaml` and `values.yaml`):
```
apiVersion: v2
name: istio-system
type: application
version: 1.0.0
dependencies:
  - name: base
    version: 1.13.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.13.2
    repository: https://istio-release.storage.googleapis.com/charts
```
```
base:
  name: istio-base
```

Application for in-cluster deployment:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-cluster-config
  source:
    repoURL: https://git.cscs.ch/argocd/apps/cluster-config.git
    targetRevision: HEAD
    path: istio-system
    helm:
      valueFiles:
      - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[]
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[]

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy


```

Application for downstream/external cluster deployment:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd-eck
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-eck

  source:
    repoURL: https://git.cscs.ch/argocd/apps/eck.git
    targetRevision: HEAD
    path: sole-metal/istio-system
    helm:
      valueFiles:
      - values.yaml

  destination:
    name: sole-metal
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[]
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[]


  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
    syncOptions:
      - CreateNamespace=true



```

**Expected behavior**

ArgoCD GUI should not switch/flash between one deployment to another.

**Screenshots**

https://user-images.githubusercontent.com/16279035/220402743-7c1db5a4-6759-4d9b-bd7e-28ab1613043c.mov

**Version**

```shell
NAME                     	NAMESPACE         	REVISION	UPDATED                                 	STATUS  	CHART                          	APP VERSION
argo-cd                  	argocd            	30      	2023-02-17 17:47:25.566317 +0100 CET    	deployed	argo-cd-5.19.12                	v2.5.9  
```

**Logs**

```
Paste any relevant application logs here.
```
