### ISSUE TITLE
CMP plugin is broke (2.6.2)

### ISSUE THREAD

**Issue by jympetalmd** [argoproj/argo-cd#12573]
The slack channel are only avail. to 2 domain ?
```
You can use any account with the domain:
rafay.co
huawei.com
```

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#configmap-plugin
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`. v2.6.2 Helm chart v5.22.1

**Describe the bug**

The CMP plugin that was used to work in 2.4.x doesn't seam to work in 2.6.2, as it should, since only removed from 2.7.x

**To Reproduce**
Following: https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#configmap-plugin
- Configmap
  - Creation with Helm:
  ```
    server:
      config:
        configManagementPlugins: |
          - name: gitcrypt
            init:
              command: ["git-crypt"]
              args: ["unlock", "/config/gitcrypt.gpg"]
            lockRepo: true
  ```
  - Result in cm:
  ```
    - name: gitcrypt
      init:
        command: ["git-crypt"]
        args: ["unlock", "/config/gitcrypt.gpg"]
      lockRepo: true
  ```
- Volume injection:
  - With Helm:
  ```
    repoServer:
      containerSecurityContext:
        runAsNonRoot: true
        runAsUser: 999
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
          - ALL
      volumes:
      - name: git-crypt-gpg-key
        secret:
          secretName: git-crypt-gpg-key
          items:
          - key: key
            path: gitcrypt.gpg
      volumeMounts:
      - name: git-crypt-gpg-key
        mountPath: "/config"
        readOnly: true
  ```
- Our custom image including git-crypt:
  ```
    FROM quay.io/argoproj/argocd:v2.6.2
    
    USER root
    RUN apt-get update && apt-get install git-crypt -y && rm -rf /var/lib/apt/lists/*
    
    USER argocd
  ```

**Expected behavior**

Was expected to have the same behaviour in the plugin.
