### ISSUE TITLE
Bug with multiple sources 

### ISSUE THREAD

**Issue by rnpaiva** [argoproj/argo-cd#12588]
**Describe the bug**

I cant use multiple sources as described here https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/  .

**To Reproduce**
Using the application.yaml to configure it : 

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
  labels:
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
  - repoURL: 'git@github.com:HorizonMedia/next-infrastructure.git'
    path: apps/authelia
    targetRevision: main
    ref: myRepo
  - repoURL: 'https://charts.authelia.com'
    chart: authelia
    targetRevision: 0.8.38
    helm:
      valueFiles:
        - $myRepo/values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



```

**Expected behavior**

Get the helm chart from authelia and the values-prod.yaml from my repository. 

**Screenshots**

**Version**

```shell
argocd@argocd-application-controller-0:~$ argocd version
argocd: v2.6.2+6e02f8b
  BuildDate: 2023-02-16T15:05:14Z
  GitCommit: 6e02f8b23201b0620a4ff1bce5d38229ba1eb02e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
$ kubectl apply -f application.yaml -n argocd
error: error validating "application.yaml": error validating data: ValidationError(Application.spec.source): invalid type for io.argoproj.v1alpha1.Application.spec.source: got "array", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```
