### ISSUE TITLE
Support sending updates to GitHub deployment statuses

### ISSUE THREAD

**Issue by Niksko** [argoproj/argo-cd#12598]
# Summary

ArgoCD notifications currently supports sending notifications to GitHub to update the commit status. It would be useful to be able to also update the status of a GitHub deployment from ArgoCD notifications.

# Motivation

Deployments in GitHub map to environments, and having this information in GitHub provides visual indicators and deployment information in a similar way to commit statuses.

# Proposal

Sample notifications config:

```
  template.app-deployed: |-
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version of deployments manifests.
    github:
      status: # Possibly should be commitStatus??
        state: success
        label: "argocd/{{.context.region}}/{{.context.cluster}}/{{(call .repo.FullNameByRepoURL .app.spec.source.repoURL)}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deploymentStatus:
        state: success
        environment: production
```

What I haven't figured out is how you actually create a deployment in the first place. This API is different to the commit status API in the sense that you must _create_ a deployment object and then _update_ the status of the deployment. With the commit status API, the commit already exists.

The alternative is that the notifications controller just assumes that deployments exist, and can only post statuses to existing deployments. However it still begs the question: how do you find out what the deployment ID is? Perhaps there's some matching that could happen by reading from the API and looking at what deployments are in progress and their commit SHAs, and mapping those to in progress application events?
