### ISSUE TITLE
Resource out of sync / diff issue with HPA metric sort

### ISSUE THREAD

**Issue by otherguy** [argoproj/argo-cd#12605]
It seems ArgoCD doesn't ignore the sorting of metrics in HPAs:

<img width="1367" alt="CleanShot 2023-02-24 at 17 02 37@2x" src="https://user-images.githubusercontent.com/6072721/221226805-10de8d9c-1669-4992-8b08-6e26c8416b42.png">

Unfortunately, it's being rendered by a 3rd party Helm chart (https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx), so the resource is always out of sync.

To reproduce, these are the values:

```
controller: 
  autoscaling:
    enabled: true
    minReplicas: 5
    maxReplicas: 15
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  autoscalingTemplate:
    - type: Pods
      pods:
        metric:
          name: prometheus.googleapis.com|nginx_ingress_controller_nginx_process_connections|gauge
          selector:
            matchLabels:
              metric.labels.controller_namespace: nginx
        target:
          type: AverageValue
          averageValue: 5000
```
