### ISSUE TITLE
How to add an imagepullsecret to a kustomized application

### ISSUE THREAD

**Issue by lllamnyp** [argoproj/argo-cd#12619]
I have developed an operator for kubernetes using [kubebuilder](https://book.kubebuilder.io/). It has the standard layout for manifests, which looks like this:

```
gitlab.company.com/infra/operator.git//config $ tree
.
├── crd
│   ├── bases
│   │   └── rbac.company.com_multinamespacerolebindings.yaml
│   ├── kustomization.yaml
│   ├── kustomizeconfig.yaml
│   └── patches
│       ├── cainjection_in_multinamespacerolebindings.yaml
│       └── webhook_in_multinamespacerolebindings.yaml
├── default
│   ├── kustomization.yaml
│   ├── manager_auth_proxy_patch.yaml
│   └── manager_config_patch.yaml
├── manager
│   ├── kustomization.yaml
│   └── manager.yaml
├── prometheus
│   ├── kustomization.yaml
│   └── monitor.yaml
├── rbac
│   ├── auth_proxy_client_clusterrole.yaml
│   ├── auth_proxy_role_binding.yaml
│   ├── auth_proxy_role.yaml
│   ├── auth_proxy_service.yaml
│   ├── kustomization.yaml
│   ├── leader_election_role_binding.yaml
│   ├── leader_election_role.yaml
│   ├── multinamespacerolebinding_editor_role.yaml
│   ├── multinamespacerolebinding_viewer_role.yaml
│   ├── role_binding.yaml
│   ├── role.yaml
│   └── service_account.yaml
└── samples
    └── rbac_v1_multinamespacerolebinding.yaml
```

In another repository I have my app of apps:

```
gitlab.company.com/group/app-of-apps.git// $ tree
.
└── app1.yml
```

The manifest looks like this

```yaml
# app1.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator
spec:
  destination:
    namespace: multinamespacerolebinding-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy: {}
  source:
    repoURL: 'https://gitlab.pwlnh.com/infra/operator.git'
    path: config/default
    targetRevision: HEAD
    kustomize:
      images:
      - controller=registry.company.com/infra/operator:015d3b29
```

The problem is that I'm unable to add a kustomize patch on top of this to add an imagePullSecret to the deployment that is created. IMO, this secret is part of the configuration, it may vary depending on the cluster to which the operator is deployed, so I certainly do not want to store these configuration details in the boilerplate code generated by kubebuilder next to the application code. It seems a very trivial task to apply an extra kustomization patch on top of the post-render, but I see no straightforward way to do that. Please advise?

Argo version: v2.6.2+6e02f8b
