### ISSUE TITLE
ArgoCD ignoring undescribed fields

### ISSUE THREAD

**Issue by kksudo** [argoproj/argo-cd#12639]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD ignore non described helm fields and report me, the live manifest=desired manifest. Actually it's false.

If I omit some options of the helm template in my desired manifest and add that options directly it in the k8s, then ArgoCD tell me there are no changes. But in real world there are some diffs. 

What is the main reason? 
Are there some special flag to ignore it?

**To Reproduce**

1. Describe your helm app and omit some fields, like `imagePullPolicy`.
2. Add these options directly to the k8s
3. Verify an ArgoCD sync status
4. App is synced.

**Expected behavior**

App is out of sync.

**Version**

```shell
v2.4.12+41f54aa
```

**Configs**

ArgoCD app settings:
```yaml
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - ../values.yaml
    path: /application
    repoURL: git@myrepo.git
    targetRevision: main
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
```

Live helm app manifest:
```yaml
...
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 30
...
```

Desired helm app manifest:
```yaml
...
<NONE for these fields>
...
```
