### ISSUE TITLE
Serviceaccount can't list CRDs

### ISSUE THREAD

**Issue by florianrusch** [argoproj/argo-cd#1265]
I've deployed argo-cd via the `kubectl apply` command. After I've added an application nothing happens. In the logs of the `application-controller` I'm getting this error message:
```
time="2019-03-14T13:14:42Z" level=info msg="Start watch app resources on https://kubernetes.default.svc"
time="2019-03-14T13:14:42Z" level=warning msg="Failed to watch app resources on https://kubernetes.default.svc: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:fr:argocd-application-controller\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope, retrying in 10s"
```

Here the clusterrole `argocd-application-controller`
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: argocd-application-controller
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```
