### ISSUE TITLE
ApplicationSet - Cluster Resources generator

### ISSUE THREAD

**Issue by aslafy-z** [argoproj/argo-cd#12656]
# Summary

Add an ArgoCD ApplicationSet generator that use results from downstream cluster's APIServer

# Motivation

Generate resources from other resources can help in some cases. 

# Proposal

Add the ability to generate Applications from downstream cluster resources, eg:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-addon
  namespace: argocd
spec:
  generators:
    - clusterResource:
        clusters: {}  
        resources:
          apiVersion: tenant.io/v1
          kind: Tenant
          # namespace: <optional>
          labelSelector:
            matchLabels:
              tenant.io/sync: 'true'
  template:
    metadata:
      name: '{{resource.metadata.name}}-sample-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: '{{resource.metadata.namespace}}'
```

```yaml
apiVersion: tenant.io/v1
kind: Tenant
metadata:
  name: tenant1
  labels:
    tenant.io/sync: 'true'
spec: {}
```

```yaml
apiVersion: tenant.io/v1
kind: Tenant
metadata:
  name: tenant2
  labels:
    tenant.io/sync: 'true'
spec: {}
```

ArgoCD should generate two applications from these resources.
