### ISSUE TITLE
Connection status always is failed with repository type git (private GitLab was deployed by k8s)

### ISSUE THREAD

**Issue by laiminhtrung1997** [argoproj/argo-cd#12665]
**Describe the bug**

I deployed Argocd application in cluster k8s, which connect repository type git - Gitlab application in another cluster k8s. The connection status always is failed.

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: repo-3768607578
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
_decodedData:
  enableLfs: "true"
  insecure: "true"
  password: <access token>
  project: default
  type: git
  url: https://example.com/example.git
  username: <account name>
```

**Expected behavior**

The connection status is connected.

**Version**

```shell
argocd: v2.6.2+6e02f8b
  BuildDate: 2023-02-16T15:05:14Z
  GitCommit: 6e02f8b23201b0620a4ff1bce5d38229ba1eb02e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2023-03-01T02:49:38Z" level=error msg="finished unary call with code Unknown" error="error testing repository connectivity: Get \"https://example.com/example.git/info/refs?service=git-upload-pack\": read tcp xx.xx.xx.xx:38630->xx.xx.xx.xx:443: read: connection reset by peer" grpc.code=Unknown grpc.method=TestRepository grpc.service=repository.RepoServerService grpc.start_time="2023-03-01T02:49:28Z" grpc.time_ms=10256.239 span.kind=server system=grpc
```
