### ISSUE TITLE
Application multi sources - Ignore missing

### ISSUE THREAD

**Issue by psimms-r7** [argoproj/argo-cd#12679]
# Summary

What change you think needs making.

Allow for missing sources or failed to connect multi source repo

Similar to the option ```ignoreMissingValueFiles```

# Motivation

Please give examples of your use case, e.g. when would you use this.

Allow for multi sources to be missing/fail so that sources are optional or if unable to authenticate do not fail the sync

If an app is deployed across all clusters and team x has a need to pass in additional values to app but team y is happy with the defaults multi sources along with ignoreMissingValuesFiles allows for passing in optional additional values for this app but if additional values are not defined the default deployment continues

However this source repo must exist and or be authenticated on or will fail

# Proposal

How do you think this should be implemented?

Allow for source defined under sources to be missing or unable to authenticate to not fail the sync, 

* At top level or for that particular source

```
sources:
  ignoreMissingSources: true *
  - chart: my-app
    repoURL: https://helm.my-app.com
    targetRevision: 1.0.0
    helm:
      releaseName: my-app
      ignoreMissingValueFiles: true
      valueFiles:
      - values.yaml
      - '$additionalValues/my-app/additionalValues/values.yaml'
  - repoURL: 'https://github.com/argocd-{{metadata.labels.team}}-values'
    ignoreMissingSource: true *
    targetRevision: master
    ref: additionalValues
```
