### ISSUE TITLE
Interpolated Generator can perform redundant parameter generation

### ISSUE THREAD

**Issue by KojoRising** [argoproj/argo-cd#12716]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We noticed slowdown with our Appsets when upgrading from v2.4.14 -> v2.5.10. We weren't entirely sure what the issue was, but we pinned it down to a feature introduced in [PR-9080](https://github.com/argoproj/argo-cd/pull/9080) (actually contributed by myself, smh).

*Context*
We use many appsets that have a matrix generator composed of a cluster generator + git generator. They would look something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  kubernetes.io/environment: 'dev'
          - git:
              repoURL: https://github.com/argoproj/applicationset.git
              revision: HEAD
              files:
                - path: "examples/git-generator-files-discovery/cluster-config/config.json"
```

What we noticed looking through the appset code was that the time it took the Matrix generator to generate its params was far greater in v2.5.10 versus v2.4.14. For example, here are the top 10 longest times for both versions:

*Matrix-Generator - GenerateParam Times - v2.5.10*
```yaml
 8.649865
 10.368155
 10.881855
 11.163029
 25.036734
 26.115226
 26.382355
 26.935813
 27.704323
 28.153638
 28.374578
```

*Matrix-Generator - GenerateParam Times - v2.4.14*
```yaml
 2.936658   
 2.939816   
 2.939872   
 2.944849   
 2.944878   
 2.948442   
 2.991007   
 2.991060   
 2.991501   
 3.036504   
 3.118068 
```

*TLDR/The Real Issue*
We dug further into what was causing the long reconcile times for the Matrix Generator in v2.5.10. Despite the fact we do not use any interpolated parameters at the moment, we're still noticing multiple `GenerateParam` calls being run in a single Matrix `GenerateParam` call. This is due to the 2nd param being run [within a for loop](https://github.com/argoproj/argo-cd/blob/352e51fdbd1bc729178ca5c16880dc9fcb5a5504/applicationset/generators/matrix.go#L54). 

**To Reproduce**
I created a test-case for each branch to compare the difference in calls. Please see here:

- [v2.5.10](https://github.com/KojoRising/argo-cd/blob/feat/appset_bug_v2.5.10/applicationset/generators/matrix_test.go#L839)

- [v2.4.14](https://github.com/KojoRising/argo-cd/blob/feat/appset_bug_v2.4.14/applicationset/generators/matrix_test.go#L271)

**Expected behavior**

v2.4.14 - Git's GenerateParam should only be called once
![image](https://user-images.githubusercontent.com/29113963/222833222-75ce3535-e354-4290-84ec-eae51e9fe773.png)

v2.5.10 - Git's GenerateParam should also only be called once
![image](https://user-images.githubusercontent.com/29113963/222833527-45b3fa7d-c53d-433b-a70d-088ddf4e12e0.png)

**Screenshots**

**Version**

v2.5.10

**Logs**

Please see above.
