### ISSUE TITLE
Namespace problem

### ISSUE THREAD

**Issue by jas01** [argoproj/argo-cd#12712]
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In a project with 

```yaml
projects:
  projectDescription: ************* 
  repository: **************
  allowAllNamespaces: true 

  applications: 
    okd-config: 
      disableNamespaceCreation: true
      source:
        directory:
          recurse: true

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist: {}
  namespaceResourceWhitelist: 
    - group: '*'
      kind: '*'

  # namespace
  # configuration commune des namespaces créés (si disableNamespaceCreation est à false)
  namespace:
    annotations: {}
    labels: {}
```
and inside the git repo I've got one file  who create a ClusterRoleBinding and another a 
Group, both don't have namespace because it's global. And on the argocd webui it show “Namespace : (Global)" but still I got a error with “okd-config” (the name of the app) doesn't exist. 

The weirdest thing is the resources are indeed created.

**Version**

```shell
v2.6.3+e05298b
```
