### ISSUE TITLE
Add ResourceVersion to status.resources for an Application

### ISSUE THREAD

**Issue by shraddhazpy** [argoproj/argo-cd#12727]
# Summary
At present, the status.resources array for an application contains the following details, example- 
```
  - group: argoproj.io
    health:
      message: 'RolloutAborted: Rollout aborted update to revision 2: Metric "job-analysis-new"
        assessed Failed due to failed (1) > failureLimit (0)'
      status: Degraded
    kind: Rollout
    name: rollout-demo
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: rollout-demo-active
    namespace: argocd
    status: Synced
    version: v1
```
We see that we can track via the health field, only the message and status. It would be great to also have a track on what resource version the tracked resource is currently at. That way for example if triggering a rollout from CD, there would be a key to map the 2 ends.

# Proposal

Add an additional field to the ResourceStatus or HealthStatus struct to add this information.
