### ISSUE TITLE
Allow exposing more than one external url

### ISSUE THREAD

**Issue by dhirschfeld** [argoproj/argo-cd#12725]
# Summary

There are multiple entry points (Traefik `IngressRoute` rules) to access my app. I'd like to be able to specify them as a list/array.

I naively tried:
```yaml
  annotations:
  {{- range .Values.dns_names }}
    link.argocd.argoproj.io/external-link: "https://{{ . }}"
  {{- end }}
```

...which seems to result in last-entry winning. 

# Proposal

I kind-of expected the result I got from my naïve attempt. I guess it could be made to work as a comma-separated list. I'm not sure if there are better ways?
