### ISSUE TITLE
Multiple Sources application issue with referenced path

### ISSUE THREAD

**Issue by erkerb4** [argoproj/argo-cd#12736]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello,

I am following the [Multi-Sources documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository) to create an application that points two different paths for the values files within the same git repository. It seems like the Application is not following the path provided in the reference sources field. 

Here is a better way to show the issue:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
...
spec:
    ...
  sources:
  - repoURL: ssh://git@somerepo.com/repo.git
    **path: common/tools/app** <--- This field is ignored
    ref: common-source
    targetRevision: main
  - helm:
      valueFiles:
      - $common-source/values-generic.yaml  <-- Argo says file not found
      - $common-source/values-onprem.yaml   <-- Argo says file not found
      - values-cluster1.yaml
    path: rc/tools/app
    repoURL: ssh://git@somerepo.com/repo.git
    targetRevision: main
```

This works and application Sync correctly:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
...
spec:
    ...
  sources:
  - repoURL: ssh://git@somerepo.com/repo.git
    **path: common/tools/app** <--- This field is ignored
    ref: common-source
    targetRevision: main
  - helm:
      valueFiles:
      - $common-source/common/tools/app/values-generic.yaml
      - $common-source/common/tools/app/values-onprem.yaml 
      - values-cluster1.yaml
    path: rc/tools/app
    repoURL: ssh://git@somerepo.com/repo.git
    targetRevision: main
```

**To Reproduce**

Here is an example git repository layout:

```
 ┣ 📂common
 ┃ ┣ 📂tools
 ┃ ┃ ┣ 📂app
 ┃ ┃ ┃ ┣ 📜values-generic.yaml
 ┃ ┃ ┃ ┣ 📜values-onprem.yaml
 ┃ ┃ ┃ ┗ 📜values-eks.yaml
 ┣ 📂rc
 ┃ ┣ 📂tools
 ┃ ┃ ┣ 📂app
 ┃ ┃ ┃ ┣ 📂templates
 ┃ ┃ ┃ ┃ ┣ 📜certificate.yaml
 ┃ ┃ ┃ ┃ ┗ 📜magic-beans.yaml
 ┃ ┃ ┃ ┣ 📜Chart.yaml
 ┃ ┃ ┃ ┣ 📜values-cluster1.yaml
 ┃ ┃ ┃ ┗ 📜values-cluster2.yaml

```

Create an Application with Multiple Sources. First source will be the reference entry, that points to the same git repository with a path, and second source entry will point to another directory that contains the helm chart and additional values files:

<details><summary>Example ArgoApp</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  name: tools-app
spec:
  destination:
    ...
  project: tools
  sources:
  - repoURL: ssh://git@somerepo.com/repo.git
    path: common/tools/app <--- This field is ignored
    ref: common-source
    targetRevision: main
  - helm:
      valueFiles:
      - $common-source/common/tools/app/values-generic.yaml  <-- Requires full path
      - $common-source/common/tools/app/values-onprem.yaml   <-- Requires full path
      - values-cluster1.yaml
    path: rc/tools/app
    repoURL: ssh://git@somerepo.com/repo.git
    targetRevision: main
```

</p>
</details>

If full path is not provided in valueFiles, Application complains with " Error: open .values-generic.yaml: no such file or directory"

**Expected behavior**

The valueFiles entries to respect path from referenced resource. 

**Screenshots**

N/A

**Version**

```shell
argocd: v2.6.3+e05298b
  BuildDate: 2023-02-27T14:40:19Z
  GitCommit: e05298b9c6ab8610104271fa8491f019fee3c587
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
N/A
```

**Comment by crenshaw-dev** [comment]
Using the path from the root of the repo is intentional. `$ref` is meant to provide full access to the _repo_, which is slightly different from providing access to the _source_. All `$ref` cares about is the `repoURL` and `targetRevision`.

It's certainly a bit confusing though. Perhaps some docs improvements would help?

**Comment by erkerb4** [comment]
> All $ref cares about is the repoURL and targetRevision.

Ah! Bingo. This is what I was missing. Thank you very much for pointing it out. 

> It's certainly a bit confusing though. Perhaps some docs improvements would help?

Yes, I think that is a good idea.

**Comment by erkerb4** [comment]
@crenshaw-dev, I created a PR, hopefully it's helpful.

**Comment by jessebot** [comment]
I'm running Argo CD deployed via helm chart version `5.29.1`, and having a similar issue with loki, in my monitoring app of apps. What's interesting is that this is only _not_ working with loki. It works fine with the prometheus stack defined in the same file. For the loki stack though, it applies the helm chart, however does not apply my local `values.yaml` file.

Here's the directory structure in my argo app of apps repo:

```
 📄 app_of_apps.yaml
 📁 apps
 ├── 📁 kube_prometheus_stack
 │   └── 📄 values.yml
 ├── 📁 loki
 │   └── 📄 values.yml
 └── 📄 monitoring.yaml
```


This is what I'm trying to apply in my `apps/monitoring.yaml`:

```yaml
# this is my monitoring.yaml in the apps/ directory of my private repo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-crd
  namespace: argocd
  annotations:
    # we need to have the Custom Resource Definitions for Prometheus BEFORE we
    # install the helm chart, so we put it in sync wave 1
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-45.21.0
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    # has to be synced AFTER CRDs, but BEFORE loki and promtail
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  sources:
    # prometheus-community helm repo
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: kube-prometheus-stack
      targetRevision: 45.21.0
      helm:
        skipCrds: true
        valueFiles:
        - $values/apps/kube_prometheus_stack/values.yml
    # our values.yaml file locally
    - repoURL: https://github.com/private_org/private_monitoring_repo.git
      ref: values
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    # sync loki after prometheus is available
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  sources:
    # grafana helm repo (grafana helm repo contains the loki-stack chart)
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: loki-stack
      targetRevision: 2.9.10
      helm:
        # CRDs should have installed during prometheus crd in the 1st sync wave
        skipCrds: true
        valueFiles:
        - $values/apps/loki/values.yml
    # our values.yaml file locally
    - repoURL: 'https://github.com/private_org/private_monitoring_repo.git'
      ref: values
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
```

Here's the `app_of_apps.yaml` that deploys everything above:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-app-of-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  source:
    repoURL: https://github.com/private_org/private_monitoring_repo.git
    path: apps/
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

Please let me know if this issue should be in a different repo or thread.
