### ISSUE TITLE
Support overriding image name/tag in for Kustomize 2 apps

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1275]
It should be possible to override image name/tag in Kustomize 2 apps. The `images` field should be available under application `spec.source.kustomize`. New field is an array where each element has required field `name` and optionally `newName` and `newTag`

Example:

```yaml
source:
  kustomize
    images:
    - name: argoproj/argo-cd
      newName: alexmt/argo-cd
      newTag: latest
```
