### ISSUE TITLE
[argocd-image-updater] xxx.xxxx.com:443/application.ApplicationService/List failed with status code 404

### ISSUE THREAD

**Issue by jblee-muhayu** [argoproj/argo-cd#12799]
I want to get image.tag through image updater. 

However, the image updater pod continues to generate the following error log.
The test through the argocd-image-updater test command was successful.

The argocd UI page is being routed through the AWS ALB.

Please share how to solve the error log

**Logs -  image updater pod**

```
time="2023-03-10T02:46:55Z" level=error msg="error while communicating with ArgoCD" argocd_server="argocd.XXXX.XXX:443" grpc_web=true grpc_webroot= insecure=false plaintext=false
time="2023-03-10T02:46:55Z" level=error msg="Error: rpc error: code = Unknown desc = POST https://argocd.XXXXX.XXX:443/application.ApplicationService/List failed with status code 404"

```
**ALB config**
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: argogrpc
  name: argogrpc
  namespace: argocd
spec:
  ports:
    - name: "443"
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
    alb.ingress.kubernetes.io/conditions.argogrpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}},{"field":"source-ip","sourceIpConfig":{"values":["XXX.XXX.XXX.XXX/32"]}}]
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/conditions.argocd-server: >
      [{"field":"source-ip","sourceIpConfig":{"values":["XXX.XXX.XXX.XXX/32"]}}]
  name: ingress-argocd
  namespace: argocd
spec:
  rules:
    - host: XXX.XXX.XXX
      http:
        paths:
          - path: /
            backend:
              service:
                name: argogrpc
                port:
                  number: 443
            pathType: Prefix
          - path: /
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
            pathType: Prefix
  tls:
    - hosts:
        - XXX.XXX.XXX
  
```
