### ISSUE TITLE
managedNamespaceMetadata on app removes namespace when Sync used with Force + Replace combination

### ISSUE THREAD

**Issue by lukpep** [argoproj/argo-cd#12810]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If the application using `managedNamespaceMetadata` is synced with `Force` and `Replace` method then the whole namespace created with `CreateNamespace=true` gets deleted which is not the desired outcome I believe :D 

**To Reproduce**

Create an app with sync options:
```
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    managedNamespaceMetadata:
      labels:
        some-label: yep
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

```

after the app is created and tracking metadata is put on the namespace:
```
Name:         lpe-test
Labels:       kubernetes.io/metadata.name=lpe-test
              some-label=yep
Annotations:  argocd.argoproj.io/sync-options: ServerSideApply=true
```

go to Argo UI and sync this app with Force + Replace combination:
![CleanShot 2023-03-10 at 10 56 28](https://user-images.githubusercontent.com/2960580/224285519-37661abc-ac76-45e4-b232-9db654cc116d.png)

this results in the namespace being deleted and recreated:
```
kd ns lpe-test
Name:         lpe-test
Labels:       kubernetes.io/metadata.name=lpe-test
              some-label=yep
Annotations:  argocd.argoproj.io/sync-options: ServerSideApply=true
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            False   Fri, 10 Mar 2023 10:47:34 +0100  ResourcesDiscovered     All resources successfully discovered
  NamespaceDeletionGroupVersionParsingFailure  False   Fri, 10 Mar 2023 10:47:34 +0100  ParsedGroupVersions     All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              False   Fri, 10 Mar 2023 10:47:34 +0100  ContentDeleted          All content successfully deleted, may be waiting on finalization
  NamespaceContentRemaining                    True    Fri, 10 Mar 2023 10:47:34 +0100  SomeResourcesRemain     Some resources are remaining: pods. has 1 resource instances
  NamespaceFinalizersRemaining                 False   Fri, 10 Mar 2023 10:47:40 +0100  ContentHasNoFinalizers  All content-preserving finalizers finished
```

**Expected behavior**

namespace not being deleted

**Version**

```shell
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:47:43Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.6.4+7be094f
  BuildDate: 2023-03-07T22:48:16Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
