### ISSUE TITLE
Different merge strategies for the merge generator

### ISSUE THREAD

**Issue by girstenbrei** [argoproj/argo-cd#12837]
# Summary

The merge generator currently combines child generator values in an "add and override" operation. Allowing different merge operators would enable the merge generator to filter by a subsequent generator.

# Motivation

Assume the following example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - merge:
        strategy: inner_join
        mergeKeys:
          - server
        generators:
          - clusters: {}
          - git:
            repoURL: https://my-example.repo
            revision: HEAD
            files:
              # assume 'app_version' & 'server' in here ↘
              - path: "additional-cluster-infos/**/config.json"

template:
  metadata:
    name: "{{name}}-guestbook" # 'name' field of the Secret
  spec:
    project: "my-project"
    source:
      repoURL: https://github.com/argoproj/argocd-example-apps/
      targetRevision: "{{ app_version }}"
      path: guestbook
    destination:
      server: "{{server}}" # 'server' field of the secret
      namespace: guestbook

```

Further assume, the cluster generator has more clusters configured than the git generator has matching `config.json`s. This results in some of those clusters not receiving a matching `config.json`, meaning the variable `app_version` is not set for some of those clusters. While in some environments, the resulting error might be desired, in my case I would like to set an appropriate version for some clusters, while having others just not deploy the application (without an error). The above example now specifies `strategy: inner_join`. This is intended as the 'switch' to make the merge generator produce only the intersection between the child generators.

Different words for he same context: in SQL the current setup could (loosely) be described as a LEFT OUTER JOIN (+ overriding left columns with right ones if same name). The merge generator produces every value from the left, and if a match is found on the right, it adds the values from the right. This proposes to add an INNER JOIN to find all matching values (based on the merge key) but remove all values which have not been found to match, even from the first generator.

## Pros

- Allows generators to 'filter' which values are generated by not providing a match
- Enforces equal shape of generated values (no missing fields in the generated objects)
- Keeps compatibility with the current functionality (opt-in by setting a strategy)

## Cons

- More user confusion: As there is no hard error, misconfiguration might happen more often with this 'silent' dropping of generated values

# Proposal

Adding the `strategy` field to the merge generator and defaulting it to the current strategy should be fine. Then, additional strategies can be implemented in the generator.

The main thing I'm not sure about is naming: `strategy` seems a fine field name, but how to name the different ones? I used the sql-like names above, but if they are used they should match exactly to what SQL used them for (and I'm not sure if SQL nows what it uses them for).

If we figure out the naming and we see this as a viable option, I'd be interested in setting up a PR to implement this.

**Comment by Roshick** [comment]
Would love to see this feature, we are currently working around the issue by using
```
spec:
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
            repoURL: https://my-example.repo
            revision: HEAD
            files:
              - path: "additional-cluster-infos/**/{{ name }}.json"
```
So that each Argo CD instance of ours only creates applications for clusters it actually manages, but using matrix generators that way seems to cause performance issues with a large number of clusters and cluster configs.
