### ISSUE TITLE
Error when using an HTTP_PROXY url

### ISSUE THREAD

**Issue by mikepfaffroth-okta** [argoproj/argo-cd#12841]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

We are currently attempting to upgrade to 2.6.4. When using an in-cluster proxy for connections, an error is received when installing an application:

```
message: 'rpc error: code = Unknown desc = Get "https://github.com/redactedrepo.git/info/refs?service=git-upload-pack":
      parse "http://squid.infra:3128\n": net/url: invalid control character in URL'
```

The issue is that there isn't a newline in the variable we're passing to argo (we're using the official helm chart):

```
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: proxy-config
        app.kubernetes.io/part-of: argocd
      name: proxy-config
      namespace: argocd    
    data:
      HTTP_PROXY: http://squid.infra:3128
      HTTPS_PROXY: http://squid.infra:3128
      NO_PROXY: argo-cd-argocd-repo-server,argo-cd-argocd-application-controller,argo-cd-argocd-metrics,argo-cd-argocd-server,argo-cd-argocd-server-metrics,argo-cd-argocd-redis,argo-cd-argocd-dex-server,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

controller:
  envFrom:
  - configMapRef:
      name: proxy-config
```

The same issue occurs when setting the environment on each individual application.

We've verified that by exec-ing into the pod and running `env`, as well as 'echo -e ${HTTP_PROXY}`. When editing the deploy manually with vim and running `:set list`, there are no control characters listed either. 

This is working correctly on our current version, v2.3.17.

**To Reproduce**

Launch a pod with the above-referenced config and tail the repo-server logs as it tries to checkout a git repository to install the application.

**Expected behavior**

The proxy URL should be used to make connections.

**Version**

```shell
argocd: v2.6.4+7be094f
  BuildDate: 2023-03-07T22:48:16Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2023-03-13T16:58:52Z" level=error msg="finished unary call with code Unknown" error="Get \"https://github.com/redacted.git/info/refs?service=git-upload-pack\": parse \"http://squid.infra:3128\\n\": net/url: invalid control character in URL" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2023-03-13T16:58:52Z" grpc.time_ms=1.025 span.kind=server system=grpc
```
