### ISSUE TITLE
feat(appset) git generator `repoURL` and `revision` as application template variable

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#12855]
# Summary

Purpose of this enhancement is to provide to template the list of generators and their associated fields name and value as variable

# Motivation

Multiple source application is bringing a really nice feature for ApplicationSets.

Let's take the following example: 

As a Devops I want to automatise the deployment of public charts to my cluster using my own value files
I will use an ApplicationSet and Multiple source in my template:

The repository would look like this:

```
components/public-charts/
  kubecost/
    .argocd.json
    values.dev.yaml
    values.prod.yaml
  kyverno/
    .argocd.json
    values.dev.yaml
    values.prod.yaml
```

The content of an `.argocd.json`

```
{
    "source": {
        "repoURL": "https://kubecost.github.io/cost-analyzer",
        "chart": "cost-analyzer",
    }
}
```

The applicationset: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: public-charts
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
  - git:
      repoURL: https://repo-containing-chart-definition-and-values.git
      revision: HEAD 
      files:
      - path: 'components/public-charts/**/.argocd.json'
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: system
      sources:
        - repoURL: https://repo-containing-chart-definition-and-values.git
          targetRevision: HEAD
          ref: values 
        - repoURL: '{{ .source.repoURL }}'
          targetRevision: '{{ .source.targetRevision }}'
          chart: '{{ default .path.basename .source.chart }}'
          helm:
            valueFiles:
              - $values/{{ .path.path }}/values.yaml
              - $values/{{ .path.path }}/values.dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ ternary .destination.namespace .path.basename (empty .destination) }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
```

The main problem here is related to the double place of `revision` and `repoURL` which can be misleading. 

If I want to test a feature, I will create a branch like `feature/add-new-chart` then I will have to change it in both places. 

# Proposal

The solution would be to add the `path.repoURL` and `path.revision` in the template variables.

It will imply adding them here:
- https://github.com/argoproj/argo-cd/blob/ed6e9e92aa2000059198fe71cade5ef9cbdb26b0/applicationset/generators/git.go#L75
- https://github.com/argoproj/argo-cd/blob/ed6e9e92aa2000059198fe71cade5ef9cbdb26b0/applicationset/generators/git.go#L135
