### ISSUE TITLE
Multi-sourced Application auto-sync only works for one of the sources

### ISSUE THREAD

**Issue by mulhotavares** [argoproj/argo-cd#12939]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
When using Multi-sourced Application in Argocd, changes to one of the sources is not auto-synced.

In my scenario, I have 2 sources: one source contains the helm chart, and the other a values file. If I change the values file, the application will show as OutOfSync, but auto-sync is not triggered.

**To Reproduce**
Create an application like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-helm-chart
  namespace: argocd
spec:
  project: test-project
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Validate=true
  destination:
    namespace: test-helm
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@github.com/mulho/values-repo.git
      targetRevision: main
      ref: valuesRepo
    - repoURL: git@github.com/mulho/simple-helm-chart.git
      targetRevision: main
      path: chart
      helm:
        valueFiles:
          - $valuesRepo/environments/dev/values.yaml
        values: |
          someValue: hola
```
Edit the value in the `values-repo` and wait for some time. The application will be marked as OutOfSync in the UI.
You can describe the ConfigMap and validate the configmap does not reflect the new value.

**Expected behavior**
Changes to both sources should trigger a sync given that Auto-Sync is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/103086251/226418703-e02b7723-d3e7-42bc-b3b3-1e100653aa40.png)

**Version**

```shell
argocd: v2.6.6+6d4de2e.dirty
  BuildDate: 2023-03-17T00:05:38Z
  GitCommit: 6d4de2ec5d49fa2c6823f2b7d101607a839be3fa
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.6+6d4de2e.dirty
  BuildDate: 2023-03-17T00:05:38Z
  GitCommit: 6d4de2ec5d49fa2c6823f2b7d101607a839be3fa
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:28:01Z
  Helm Version: v3.10.0+gce66412
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Paste any relevant application logs here.
```
