### ISSUE TITLE
Referenced valueFiles not recognized correctly

### ISSUE THREAD

**Issue by martin-at-home** [argoproj/argo-cd#12938]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

After following the instructions in the docs regarding [external value files for helm](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository) I was struggling a long to as the whole feature seemed not to work at all.
After a lot of trial and error I've been able to figure out that the sequence of sources matters (and does not follow the information in the documentation!), see the steps to reproduce the behaviour.

**To Reproduce**

Example application not working, i.e.
- external values file recognized
- external values not assigned
- values of Helm repo visible in Parameters page of App Details
- Revision of synched status set to 19.7.2 (i.e. the revision of the first entry of the list, now prometheus)
- Type of application is set to Helm

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 19.7.2
    helm:
      valueFiles:
      - $values/argocd/cluster-apps/prometheus/values.yaml
  - repoURL: 'https://gitlab.com/<my-id>/<my-repo>.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

Example application working, i.e.
- external values file recognized
- external values are assigned
- no values at all visible in Parameters page of App Details
- Revision of synched status set to main (i.e. the revision of the first entry of the list)
- Type of application is set to Git

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  sources:
  - repoURL: 'https://gitlab.com/<my-id>/<my-repo>.git'
    targetRevision: main
    ref: values
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 19.7.2
    helm:
      valueFiles:
      - $values/argocd/cluster-apps/prometheus/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

- Make the sequence of sources independent of the definition of the repo for the values file
- Take the (first) Helm repo as leading information for the parameters page
- Take the revision and type of the Helm repo as leading information.

**Screenshots**

First setup with Helm repo as first entry of sources:
![image](https://user-images.githubusercontent.com/43298518/226415954-d29650e6-b155-4d67-9826-bf7ead64f5b8.png)

Second setup with values repo as first entry of sources:
![image](https://user-images.githubusercontent.com/43298518/226415432-cebbd548-0063-477a-a474-aa2b187f6a99.png)

**Version**

argocd CLI: v2.6.2 (see below)
argocd Server: v2.6.6+6d4de2e (Helm Revision 5.27.1)

```shell
argocd: v2.6.2+6e02f8b
  BuildDate: 2023-02-16T15:29:20Z
  GitCommit: 6e02f8b23201b0620a4ff1bce5d38229ba1eb02e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/arm64
```

**Logs**

```
No errors in logs
```
