### ISSUE TITLE
Local diff seems to ignore diffing customization

### ISSUE THREAD

**Issue by yann-soubeyrand** [argoproj/argo-cd#1294]
Hi,

I configured Argo CD to globally ignore diff like below:
```
data:
  resource.customizations: |
    apps/DaemonSet:
      ignoreDifferences: |
        jsonPointers:
        - /spec/template/spec/securityContext/runAsGroup
    apps/Deployment:
      ignoreDifferences: |
        jsonPointers:
        - /spec/template/spec/securityContext/runAsGroup
```

Diff are effectively ignored when I visit the web UI but aren't when doing a local diff.
