### ISSUE TITLE
ignoredifferences not working for tekton EventListener CRD. App remains OutOfSync.

### ISSUE THREAD

**Issue by rodriguezc** [argoproj/argo-cd#12944]
Checklist:
* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**
We use CRD EventListener resource from tekton. This resource is immediately modified by tekton operator when argocd applies it
Original file:
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app.kubernetes.io/instance: develop-tekton
  name: gitlab-listener-interceptor
  namespace: develop-tekton
spec:
  serviceAccountName: tekton-trigger-sa
  triggers:
    - bindings:
        - ref: gitlab-trigger-binding
      interceptors:
        - gitlab:
            eventTypes:
              - Push Hook
              - Tag Push Hook
            secretRef:
              secretKey: key
              secretName: gitlab-webhook-secret
      name: gitlab-trigger
      template:
        ref: tekton-pipeline-dispatcher-template
```
Comparison after deployment by argocd:
<img width="548" alt="tektondiff" src="https://user-images.githubusercontent.com/2474044/226566323-9eff546f-350c-4bbe-96af-fbb97224b622.PNG">

I tried to define ignoredifferences in application for /spec/triggers path but it is still not working.:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jqPathExpressions:
        - '.spec.triggers[]'
      kind: CustomResourceDefinition
      name: eventlisteners.triggers.tekton.dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
   ... 
```
CRD reference is ok:
```
 kubectl get crd | grep eventlistener
 eventlisteners.triggers.tekton.dev
```
In Events tab I also have the following error:
```
Operation cannot be fulfilled on deployments.apps "el-gitlab-listener-interceptor": the object has been modified; please apply your changes to the latest version and try again
```

**To Reproduce**
1. Install tekton with ArgoCD
2. Create a Gitlab EventListener resource following tekton documentation: https://tekton.dev/vault/triggers-v0.8.1/eventlisteners/#gitlab-interceptors
3. This resource will remain OutOfSync

**Expected behavior**
Should not be OutOfSync

**Screenshots**

**Version**
v2.5.2+148d8da

**Logs**
