### ISSUE TITLE
Parameters of other child generator not being substituted in List generator when using Matrix generator

### ISSUE THREAD

**Issue by sfynx** [argoproj/argo-cd#12947]
Normally when using the Matrix generator, you are able to use parameters from the first child generator in the second child generator, as documented here: [https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#using-parameters-from-one-c[…]-in-another-child-generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#using-parameters-from-one-child-generator-in-another-child-generator)

However, when using a List generator as the second generator in a Matrix generator, it is not possible to use parameters of the first generator. Instead, the `{{ parameter }}` is not substituted, but taken as the literal value.

**To Reproduce**
You can reproduce this with this example application set:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              directories:
                - path: applications/*
              repoURL: 'https://github.com/example-org/applications.git'
              revision: HEAD
          - list:
              elements:
                - testKey: 'val-{{ path.basename }}'
  template:
    metadata:
      name: app-{{ path.basename }}
    spec:
      destination:
        name: dev
        namespace: app-{{ path.basename }}
      project: default
      source:
        helm:
          releaseName: release-{{ path.basename }}
          values: |
            testKey: {{.testKey}}
        path: test
        repoURL: 'https://github.com/example-org/manifests.git'
        targetRevision: refs/heads/release/1.2.x
      syncPolicy:
        automated:
          prune: true
```
When a Git repository contains:
```
applications/a
applications/b
```
this yields:
```
testKey: val-{{ path.basename }}
```
for both applications.

**Expected behavior**

A `{{ parameter }}` is substituted with the value from the first child generator, yielding this for the two applications in the above example:
```
testKey: val-a
testKey: val-b
```

**Version**

```shell
argocd: v2.6.6+6d4de2e.dirty
  BuildDate: 2023-03-17T00:05:38Z
  GitCommit: 6d4de2ec5d49fa2c6823f2b7d101607a839be3fa
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.6+6d4de2e
```

**Slack discussion**
https://cloud-native.slack.com/archives/C01TSERG0KZ/p1679386558427959
