### ISSUE TITLE
Proposal: ApplicationSet status condition type ErrorOccurred is confusing to new users (Change to ReconciledSuccessfully)

### ISSUE THREAD

**Issue by mikeshng** [argoproj/argo-cd#12950]
# Summary

In ApplicationSet status, there is a condition type `ErrorOccurred` that is set to `False` when the ApplicationSet has successfully been reconciled. When new users of ApplicationSet see the status and notice the `ErrorOccurred`, sometimes they assumed that there is an error with their ApplicationSets but everything is actually OK because the status is `False`. This negation means successful causes some confusion especially when coupling with the other condition type `ParametersGenerated` and `ResourcesUpToDate` which are positives to report success. Please see below:
```
status:
  conditions:
  - lastTransitionTime: "2023-03-21T11:25:06Z"
    message: Successfully generated parameters for all Applications
    reason: ApplicationSetUpToDate
    status: "False"
    type: ErrorOccurred
  - lastTransitionTime: "2023-03-21T11:25:06Z"
    message: Successfully generated parameters for all Applications
    reason: ParametersGenerated
    status: "True"
    type: ParametersGenerated
  - lastTransitionTime: "2023-03-21T11:25:06Z"
    message: ApplicationSet up to date
    reason: ApplicationSetUpToDate
    status: "True"
    type: ResourcesUpToDate
```

Is it possible to change `ErrorOccurred` to `ReconciledSuccessfully` or something similar? Or it's not worth considering because there is backward compability and API breakage concerns? If changed an example will be:
```
status:
  conditions:
  - lastTransitionTime: "2023-03-21T11:25:06Z"
    message: Successfully generated parameters for all Applications
    reason: ApplicationSetUpToDate
    status: "True"
    type: ReconciledSuccessfully
```

# Motivation

Avoid confusion for new users of ApplicationSet. `ErrorOccurred` seems like there is an error but it's actually successful because the status is False.

# Proposal

If there are no backward compability concerns then simply rename the existing `ErrorOccurred` to `ReconciledSuccessfully` or something similar. The places where it sets True or False needs to be negated after the rename.
