### ISSUE TITLE
FATA[0000] rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#12988]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
appProject/ap-syncWindows-applications.yaml

kubectl apply -f ap-syncWindows-applications.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  syncWindows:
  - applications:
    - app
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
      name: cluster2
```

appProject/ap-application.yaml

kubectl apply -f ap-application.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    server: https://192.168.229.153:6443
    namespace: demo
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1
    targetRevision: HEAD
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```
[root@localhost appProject]# argocd app sync app
FATA[0000] rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
[root@localhost appProject]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
