### ISSUE TITLE
argocd + cert-manager + ingress_nginx + acme-http-solver cannot issue standalone certificate

### ISSUE THREAD

**Issue by heroes1412** [argoproj/argo-cd#12987]
**What happened**:

The challenge show: "Waiting for HTTP-01 challenge propagation: wrong status code '404', expected '200'"

**What you expected to happen**:

The challenge was resolve, a cert will be issued.

**NGINX Ingress controller version** (exec into the pod and run nginx-ingress-controller --version.):

NGINX Ingress controller
  Release:       v1.6.4
  Build:         69e8833858fb6bda12a44990f1d5eaa7b13f4b75
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.21.6

**Kubernetes version** (use `kubectl version`):
Cert-manager: v1.11.0
k8s: v1.26.3
**Environment**:

- **Cloud provider or hardware configuration**: On-premise
- **OS** (e.g. from /etc/os-release): 20.04.6 LTS (Focal Fossa)
- **Kernel** (e.g. `uname -a`): Linux k8s 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Basic cluster related info**:
root@k8s:/tmp/2/ingress-nginx# kubectl get nodes -o wide
NAME   STATUS   ROLES           AGE    VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
k8s    Ready    control-plane   2d3h   v1.26.3   103.157.218.106   <none>        Ubuntu 20.04.6 LTS   5.4.0-144-generic   cri-o://1.26.1

- **How was the ingress-nginx-controller installed**:
helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --create-namespace \
  --debug \
  --set controller.publishService.enabled=true \
  --set controller.ingressClassResource.default=true \
  --set controller.service.externalTrafficPolicy="Cluster" \
  --set controller.service.type="NodePort" \
  --set controller.service.nodePorts.http=80 \
  --set controller.service.nodePorts.https=443

- **Current State of the controller**:
  - `kubectl describe ingressclasses`
  

> root@k8s:/tmp/2/ingress-nginx# kubectl describe ingressclasses
Name:         nginx
Labels:       app.kubernetes.io/component=controller
              app.kubernetes.io/instance=ingress-nginx
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=ingress-nginx
              app.kubernetes.io/part-of=ingress-nginx
              app.kubernetes.io/version=1.6.4
              helm.sh/chart=ingress-nginx-4.5.2
Annotations:  ingressclass.kubernetes.io/is-default-class: true
              meta.helm.sh/release-name: ingress-nginx
              meta.helm.sh/release-namespace: default
Controller:   k8s.io/ingress-nginx
Events:       <none>

**How to reproduce this issue**:
i place ingress.yaml in a config repo in gitlab:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: r1.domain.com-ingress
  labels:
    app: service1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - r1.domain.com
    secretName: r1.domain.com-secret
  rules:
  - host: "r1.domain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service1
            port:
              number: 80
```

Using argoCD to deploy app to k8s cluster, after press SYNC, i found that a ingress named "cm-acme-http-solver-XXXXX" has CLASS=NONE, and the challenge show "Waiting for HTTP-01 challenge propagation: wrong status code '404', expected '200'"
When I manually edit the solver ingress, add the "specs.ingressClassName: nginx" , the challenge succeeds immediately.

**Anything else we need to know**:

If i tried to apply the ingress rule by kubectl -f ingress.yaml, the new certificate for my domain will by issued. dont know why. how can i add "specs.ingressClassName: nginx" for every ingress rule when cert-manager request a new cert, is there any templele ingress rule for that?
