### ISSUE TITLE
Error Handling in Config Map Plugin - ArgoCD Vault Plugin

### ISSUE THREAD

**Issue by talitz** [argoproj/argo-cd#13009]
Argo CD Vault Plugin is failing in my environment (the plugin is running as a sidecar container), similar to what was describe here  - [`Error handling in a CMP`](https://github.com/argoproj/argo-cd/discussions/11191):

`time="2023-03-25T15:54:44Z" level=error msg="finished streaming call with code Unknown" error="error generating manifests: failed to unmarshal manifest: error converting YAML to JSON: yaml: line ││  8: mapping values are not allowed in this context" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-03-25T15:54:30Z" grpc.t │
│ ime_ms=13960.414 span.kind=server system=grpc`

The plugin configured in the configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-plugin
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      generate:
        command: ["sh", "-c"]
        args: ["helm dependency build --debug && helm template --debug --include-crds ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
      init:
        command: [sh, -c]
        args: ["helm repo update"]
```

The plugin runs as a sidecar container as part of the deployment:

```apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: avp
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AVP_TYPE
              value: awssecretsmanager
            - name: HELM_CACHE_HOME
              value: /helm-working-dir
            - name: HELM_CONFIG_HOME
              value: /helm-working-dir
            - name: HELM_DATA_HOME
              value: /helm-working-dir
            - name: HELM_REPOSITORY_CONFIG
              value: /helm-working-dir/repositories.yaml
            - name: HELM_REPOSITORY_CACHE
              value: /helm-working-dir/repository
            - name: HELM_REGISTRY_CONFIG
              value: /helm-working-dir/registry/config.json
            - name: REPO_USER
              valueFrom:
                configMapKeyRef:
                  name: argocd-cmp-plugin
                  key: REPO_USER
            - name: REPO_PASS
              valueFrom:
                configMapKeyRef:
                  name: argocd-cmp-plugin
                  key: REPO_PASS
          command: [ /var/run/argocd/argocd-cmp-server ]
          image: alpine/k8s:1.23.17
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: tmp
            # Register plugins into sidecar
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: avp.yaml
              name: argocd-cmp-plugin
            # Important: Mount tools into $PATH
            - name: custom-tools
              subPath: argocd-vault-plugin
              mountPath: /usr/local/bin/argocd-vault-plugin
            - name: helm-temp-dir
              mountPath: /helm-working-dir
      volumes:
        - configMap:
            name: argocd-cmp-plugin
          name: argocd-cmp-plugin
        - name: custom-tools
          emptyDir: { }
        - name: helm-temp-dir
          emptyDir: {}
      initContainers:
      - name: download-tools
        image: dopsap-docker-virtual/alpine:3.8
        command: [sh, -c]
        # Always update this to whatever the stable release version is
        # Note the lack of the `v` prefix unlike the git tag
        env:
          - name: AVP_VERSION
            value: "1.13.1"
        args:
          - >-
            wget -O argocd-vault-plugin
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/ &&
            ls -la /custom-tools &&
            echo "Successfully downloaded argocd-vault-plugin"
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      automountServiceAccountToken: true
```

I use the plugin in the following way in an ApplicationSet object:
```
        plugin:
          name: argocd-vault-plugin
          env:
            - name: helm_args
              value: -f values.yaml
```

It looks like the problem is not in the output of the plugin, it's completly valid and FINE!
The problem is what happens after, in the following lines:
https://github.com/argoproj/gitops-engine/blob/b371e3bfc5e95962096866e3d8e0205bf647f1a2/pkg/utils/kube/kube.go#L299

**Versions**
Chart version: 5.26.0
ArgoCD Vault Plugin: 1.13.1
Helm: version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```shell
argocd: v2.6.4+7be094f
  BuildDate: 2023-03-07T22:48:16Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Comment by cjc7373** [comment]
It seems that your generate command returns an incorrect YAML. Can you confirm that this generate command
```yaml
generate:
        command: ["sh", "-c"]
        args: ["helm dependency build --debug && helm template --debug --include-crds ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
```
returns a valid YAML?

**Comment by talitz** [comment]
Yes, what I did is saved the all.yaml file in order to validate it, it looks fine and not corrupted.

**Comment by todaywasawesome** [comment]
@talitz Did you take the output and try to apply it? Ideally with `dry-run=server` ?

Looks valid ≠ valid.

**Comment by talitz** [comment]
Hi guys, I have managed to solve it.
What I did is changed the following:
```
      generate:
        command: ["sh", "-c"]
        args: ["helm dependency build --debug && helm template --debug --include-crds ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
      init:
        command: [sh, -c]
        args: ["helm repo update"]
```
to
```
      generate:
        command: ["sh", "-c"]
        args: ["argocd-vault-plugin generate all.yaml"]
      init:
        command: [sh, -c]
        args: ["helm repo update && helm dependency build --debug && helm template --debug --include-crds ${helm_args} . > all.yaml"]
```
Which resolved most of the issues. Apparently the ArgoCD repo-server logic took the first command's output (helm dependency build) instead of the argocd-vault-plugin's generate output which created this issue. Hope this will help someone :)
