### ISSUE TITLE
jsonnet tlas Unknown variable 

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13005]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
application/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: mydest
    - server: https://192.168.229.156:6443
      namespace: demo
```

application/app-directory-jsonnet-tlas.yaml

kubectl apply -f app-directory-jsonnet-tlas.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    server: https://192.168.229.153:6443
    namespace: demo
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/jsonnettlas
    directory:
      jsonnet:
        tlas:
        - name: name
          value: $ARGOCD_APP_NAME
        - name: image
          value: nginx
    targetRevision: HEAD
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
jsonnet file:
```

{
  apiVersion: 'apps/v1',
  kind: 'Deployment',
  metadata: {
    name: name,
    labels: { app: name },
  },
  spec: {
    selector: { matchLabels: $.metadata.labels },
    template: {
      metadata: { labels: $.metadata.labels },
      spec: {
        containers: [{
          name: name,
          image: image,
        }],
      },
    },
  },
}
```
```
[root@localhost application]# argocd app sync app
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2023-03-25T00:37:35-07:00   apps  Deployment        demo                   app   Unknown  Healthy              

Name:               argocd/app
Project:            project
Server:             https://192.168.229.153:6443
Namespace:          demo
URL:                https://argocd-server.argocd.svc.cluster.local/applications/app
Repo:               https://gitee.com/hxpgit/argocd.git
Target:             HEAD
Path:               demo1/jsonnettlas
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Unknown
Health Status:      Healthy

Operation:          Sync
Sync Revision:      
Phase:              Error
Start:              2023-03-25 00:37:35 -0700 PDT
Finished:           2023-03-25 00:37:36 -0700 PDT
Duration:           1s
Message:            ComparisonError: rpc error: code = FailedPrecondition desc = Failed to evaluate jsonnet "nginx.jsonnet": .demo1/jsonnettlas/nginx.jsonnet:6:11-15 Unknown variable: name

    name: name,



GROUP  KIND        NAMESPACE  NAME  STATUS   HEALTH   HOOK  MESSAGE
apps   Deployment  demo       app   Unknown  Healthy        
FATA[0001] Operation has completed with phase: Error 
```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost application]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
```
time="2023-03-25T07:44:26Z" level=info msg="updated 'argocd/app' operation (phase: Running)"
time="2023-03-25T07:44:26Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:b831e1a8cfda97bd4a485284a75abea83958fa00,Prune:false,DryRun:false,SyncStrategy:&SyncStrategy{Apply:nil,Hook:&SyncStrategyHook{SyncStrategyApply:SyncStrategyApply{Force:false,},},},Resources:[]SyncOperationResource{},Source:nil,Manifests:[],SyncOptions:[],} {admin false} [] {0 nil}}" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Comparing app state (cluster: https://192.168.229.153:6443, namespace: demo)" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="updated 'argocd/app' operation (phase: Error)"
time="2023-03-25T07:44:26Z" level=info msg="Sync operation to  failed: ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to evaluate jsonnet \"nginx.jsonnet\": .demo1/jsonnettlas/nginx.jsonnet:6:11-15 Unknown variable: name\n\n    name: name,\r\n\n" application=app dest-namespace=demo dest-server="https://192.168.229.153:6443" reason=OperationCompleted type=Warning
time="2023-03-25T07:44:26Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Comparing app state (cluster: https://192.168.229.153:6443, namespace: demo)" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2023-03-25T07:44:26Z\",\"message\":\"rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to evaluate jsonnet \\\"nginx.jsonnet\\\": .demo1/jsonnettlas/nginx.jsonnet:6:11-15 Unknown variable: name\\n\\n    name: name,\\r\\n\\n\",\"type\":\"ComparisonError\"}]}}" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Skipping auto-sync: application status is Unknown" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Update successful" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Reconciliation completed" application=argocd/app dedup_ms=0 dest-name= dest-namespace=demo dest-server="https://192.168.229.153:6443" diff_ms=0 fields.level=2 git_ms=7 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=52
time="2023-03-25T07:44:26Z" level=info msg="Refreshing app status (normal refresh requested), level (3)" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Comparing app state (cluster: https://192.168.229.153:6443, namespace: demo)" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Skipping auto-sync: application status is Unknown" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Update successful" application=argocd/app
time="2023-03-25T07:44:26Z" level=info msg="Reconciliation completed" application=argocd/app dedup_ms=0 dest-name= dest-namespace=demo dest-server="https://192.168.229.153:6443" diff_ms=0 fields.level=3 git_ms=213 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=239
```
