### ISSUE TITLE
 Manifest generation error (cached): helm chart version '3' is not supported

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13011]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
application/ap-sourceRepos.yaml

kubectl apply -f ap-sourceRepos.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  sourceRepos:
    - https://charts.bitnami.com/bitnami
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: mydest
    - server: https://192.168.229.156:6443
      namespace: demo
```

application/app-source-helm-version.yaml

kubectl apply -f app-source-helm-version.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    server: https://192.168.229.153:6443
    namespace: demo
  project: project
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami 
    targetRevision: 13.2.27
    helm:
      version: "3"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```
[root@localhost application]# argocd app sync app
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2023-03-25T21:47:07-07:00            Service        demo               mynginx   Unknown  Healthy              
2023-03-25T21:47:07-07:00   apps  Deployment        demo               mynginx   Unknown  Healthy              

Name:               argocd/app
Project:            project
Server:             https://192.168.229.153:6443
Namespace:          demo
URL:                https://argocd-server.argocd.svc.cluster.local/applications/app
Repo:               https://charts.bitnami.com/bitnami
Target:             13.2.27
Path:               
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Unknown
Health Status:      Healthy

Operation:          Sync
Sync Revision:      
Phase:              Error
Start:              2023-03-25 21:47:07 -0700 PDT
Finished:           2023-03-25 21:47:07 -0700 PDT
Duration:           0s
Message:            ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): helm chart version '3' is not supported

GROUP  KIND        NAMESPACE  NAME     STATUS   HEALTH   HOOK  MESSAGE
       Service     demo       mynginx  Unknown  Healthy        
apps   Deployment  demo       mynginx  Unknown  Healthy        
FATA[0000] Operation has completed with phase: Error   
```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost application]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
