### ISSUE TITLE
ComparisonError: kustomize version v4.5.7 is not registered

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13012]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
application/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

application/app-source-kustomize-version.yaml

kubectl apply -f app-source-kustomize-version.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/kustomize
    targetRevision: HEAD
    kustomize:
      version: v4.5.7
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```
[root@localhost application]# argocd app sync app

Name:               argocd/app
Project:            project
Server:             cluster1
Namespace:          demo
URL:                https://argocd-server.argocd.svc.cluster.local/applications/app
Repo:               https://gitee.com/hxpgit/argocd.git
Target:             HEAD
Path:               demo1/kustomize
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Unknown
Health Status:      Healthy

Operation:          Sync
Sync Revision:      
Phase:              Error
Start:              2023-03-25 23:15:58 -0700 PDT
Finished:           2023-03-25 23:15:58 -0700 PDT
Duration:           0s
Message:            ComparisonError: kustomize version v4.5.7 is not registered

GROUP  KIND        NAMESPACE  NAME                         STATUS   HEALTH   HOOK  MESSAGE
       Service     demo       kustomize-guestbook-ui-mark  Unknown  Healthy        
apps   Deployment  demo       kustomize-guestbook-ui-mark  Unknown  Healthy        
FATA[0000] Operation has completed with phase: Error
```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost application]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
