### ISSUE TITLE
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): config management plugin not supported. plugin name my-plugin

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13013]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
my-plugin-config.yaml

kubectl apply -f my-plugin-config.yaml -n argocd 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: my-plugin
    spec:
      version: v1.0
      init:
        command: [sh, -c, 'echo "Initializing..."']
      generate:
        command: [sh, -c, 'echo "{\"kind\": \"ConfigMap\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"$ARGOCD_APP_NAME\", \"namespace\": \"$ARGOCD_APP_NAMESPACE\", \"annotations\": {\"Foo\": \"$ARGOCD_ENV_FOO\", \"KubeVersion\": \"$KUBE_VERSION\", \"KubeApiVersion\": \"$KUBE_API_VERSIONS\",\"Bar\": \"$ARGOCD_ENV_REV\"}}}"']
      discover:
        fileName: "./kustomization.yaml"
```

patch.yaml

kubectl patch -n argocd  deploy argocd-repo-server --patch "$(cat patch.yaml)"

```
spec:
  template:
    spec:
      containers:
        - name: my-plugin
          command: [/var/run/argocd/argocd-cmp-server] 
          image: busybox
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: my-plugin-config
            - mountPath: /tmp
              name: cmp-tmp
      volumes:
        - configMap:
            name: my-plugin-config
          name: my-plugin-config
        - emptyDir: {}
          name: cmp-tmp
```

application/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

application/app-source-plugin-env-name.yaml

kubectl apply -f app-source-plugin-env-name.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/kustomize
    targetRevision: HEAD
    plugin:
      env:
        - name: FOO
          value: bar
        - name: REV
          value: test-$ARGOCD_APP_REVISION
      name: my-plugin
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```
[root@localhost ~]# kubectl get pod -n argocd  -w
NAME                                                READY   STATUS    RESTARTS        AGE
argocd-application-controller-0                     1/1     Running   15 (3d1h ago)   30d
argocd-applicationset-controller-554d4fc79d-grwkt   1/1     Running   15 (3d1h ago)   30d
argocd-dex-server-7f644c9595-qshmv                  1/1     Running   16 (3d1h ago)   30d
argocd-notifications-controller-594584bb9-q2tsm     1/1     Running   15 (3d1h ago)   30d
argocd-redis-5c8c778664-4ks8j                       1/1     Running   16 (3d1h ago)   30d
argocd-repo-server-d88d4948-kfmrf                   1/1     Running   16 (3d1h ago)   30d
argocd-server-659b68f9fc-x8jb4                      1/1     Running   16 (3d1h ago)   30d
argocd-repo-server-5c68879b6c-wh2kw                 0/2     Pending   0               0s
argocd-repo-server-5c68879b6c-wh2kw                 0/2     Pending   0               0s
argocd-repo-server-5c68879b6c-wh2kw                 0/2     Init:0/1   0               0s
argocd-repo-server-5c68879b6c-wh2kw                 0/2     Init:0/1   0               3s
argocd-repo-server-5c68879b6c-wh2kw                 0/2     PodInitializing   0               5s
argocd-repo-server-5c68879b6c-wh2kw                 1/2     Running           0               22s
argocd-repo-server-5c68879b6c-wh2kw                 2/2     Running           0               30s
argocd-repo-server-d88d4948-kfmrf                   1/1     Terminating       16 (3d1h ago)   30d
argocd-repo-server-d88d4948-kfmrf                   0/1     Terminating       16              30d
argocd-repo-server-d88d4948-kfmrf                   0/1     Terminating       16              30d
argocd-repo-server-d88d4948-kfmrf                   0/1     Terminating       16              30d



```

```
[root@localhost application]# argocd app sync app
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME           STATUS   HEALTH        HOOK  MESSAGE
2023-03-26T00:03:17-07:00            Service        demo  kustomize-guestbook-ui-mark   Unknown  Healthy              
2023-03-26T00:03:17-07:00   apps  Deployment        demo  kustomize-guestbook-ui-mark   Unknown  Healthy              

Name:               argocd/app
Project:            project
Server:             cluster1
Namespace:          demo
URL:                https://argocd-server.argocd.svc.cluster.local/applications/app
Repo:               https://gitee.com/hxpgit/argocd.git
Target:             HEAD
Path:               demo1/kustomize
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Unknown
Health Status:      Healthy

Operation:          Sync
Sync Revision:      
Phase:              Error
Start:              2023-03-26 00:03:17 -0700 PDT
Finished:           2023-03-26 00:03:17 -0700 PDT
Duration:           0s
Message:            ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): config management plugin not supported. plugin name my-plugin

GROUP  KIND        NAMESPACE  NAME                         STATUS   HEALTH   HOOK  MESSAGE
       Service     demo       kustomize-guestbook-ui-mark  Unknown  Healthy        
apps   Deployment  demo       kustomize-guestbook-ui-mark  Unknown  Healthy        
FATA[0000] Operation has completed with phase: Error    
```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost application]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
