### ISSUE TITLE
API Sync issues

### ISSUE THREAD

**Issue by everestas** [argoproj/argo-cd#13027]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have ArgoCD and Argo Workflows set up. In Argo Workflow I have a workflor task which triggers ArgoCD to sync through API call. Sometimes ArgoCD syncs, but sometimes it doesn't with no apparent error. 

**To Reproduce**

1. In ArgoCD I have Spark Cluster which is running on AKS. It spins up when Argo Workflow task "start-deployment" pushes new manifest values to git. When ArgoCD picks up new values, spark cluster gets deployed in AKS.
2. Since ArgoCD automatically checks git repository for new values every 3 minutes by default, I use API call to sync application. 

Argo workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:  
  generateName: url-dag-
spec:
  entrypoint: init-dag
  artifactRepositoryRef: 
    configMap: workflow-controller-configmap
    key: artifactRepository
  onExit: stop-deployment
  templates:
    - name: init-dag
      dag:
        tasks:
          - name: start-dp
            template: start-deployment
          - name: sync-deployment
            template: sync-deployment
            dependencies:
              - start-dp
    - name: start-deployment
      outputs:
        artifacts:
        - name: values-output
          path: /tmp/values.yaml
      container:
        name: ''
        image: alpine/git
        command:
          - sh
          - '-c'
        args:
          - >-
            git clone --branch prod
            https://<user:password>@dev.azure.com/repo
            && cd spark-on-k8s/spark-on-spot-nodes 
            && ls
            && rm values.yaml 
            && cp start.yaml values.yaml 
            && git config --global user.email 'user@mail.com' 
            && git config --global user.name 'user' 
            && git add values.yaml 
            && git commit -m 'Deploy Data Platform at {{workflow.creationTimestamp}} for {{workflow.name}}' --allow-empty
            && git push
            && cat values.yaml > /tmp/values.yaml      
    - name: sync-deployment
      container:
        image: curlimages/curl
        command:
          - sh
          - '-c'
        args:
          - >
            curl -X POST -H "Content-Type: application/json" -d '{"appNamespace":"argo-production","revision":"prod","prune":false,"dryRun":false,"strategy":{"hook":{"force":false}},"resources":null,"syncOptions":null}' -k -i https://<ip>/api/v1/applications/spark-production/sync
            -H "Authorization: Bearer <...>" 
```

Weird thing is that sometimes it sync, sometimes it does not and there is no predictable way to determine when it is going to fail. Even if I check the argocd logs, I can see that API call was triggered with no error, but then I check UI and I see that application is not synced. If I refresh the application, it will automatically sync without me asking. If I check history, I can see that it wasn't synced before, so that curl API call doesn't appear in history.

**Expected behavior**

Application syncs everytime I call API sync function.

**Version**

```shell
argocd: v2.6.0+acc554f
  BuildDate: 2023-02-06T21:17:26Z
  GitCommit: acc554f3d99010e0353b498a595844b30090556f
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```
