### ISSUE TITLE
NamespaceBlacklist typo in the docs

### ISSUE THREAD

**Issue by cruisehall** [argoproj/argo-cd#1302]
In the file `docs/project.yaml`, the example `AppProject` spec used to populate `docs/declarative-setup.md`, we find the lines:

```
# Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
# Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  clusterResourceWhitelist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
```
The second mention of `clusterResourceWhitelist` should instead read `namespaceResourceBlacklist`:
```
# Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
# Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
```
