### ISSUE TITLE
support an on-health-healthy trigger for notifications

### ISSUE THREAD

**Issue by mmerickel** [argoproj/argo-cd#13032]
See https://github.com/argoproj-labs/argocd-notifications/issues/341.

The on-health-degraded trigger is great, but now we have in chat notifications every time the app becomes degraded and we have no trigger that tells us that things have recovered and the app is healthy again.

We see Healthy -> Degraded -> Progressing -> Healthy, and there isn't enough info in the Application.status field to use in a trigger that I have been able to find.

**Comment by trolleksii** [comment]
A situation I had is the DB went down for a few seconds which was enough for the app that was using it to crash and Argoapp sent the "degraded" notification. It would be great to have a trigger to notify the app has "recovered".

**Comment by jharris-tc** [comment]
+1 to this, currently would like a way to create a trigger for 'healthy after not healthy or progressing' in a way that doesn't flap. Perhaps the ability to assign/remove a label as part of a trigger? Then I could create a label 'unhealthy' as part of a trigger and check that label for this recovery check

**Comment by mmerickel** [comment]
I really like the idea of allowing a trigger to set/unset a set of label on the Application resource. Something like `setLabel` (naming / spec first draft) which would set a value if the trigger executes. It fits very well with `oncePer` which could also use those values in its logic.

```
trigger.on-health-degraded:
- description: Application has degraded
  send:
  - app-health-degraded
  when: app.status.health.status == 'Degraded'
  setLabel:
  - name: degraded
    value: 'true'
trigger:on-healthy-after-degraded:
- description: Application has recovered
  send:
  - app-health-recovered
  when: app.status.health.status == 'Healthy' and app.labels.degraded == "true"
  setLabel:
  - name: degraded
    value: 'false'
```
