### ISSUE TITLE
Unknown ComparisonError

### ISSUE THREAD

**Issue by Orabig** [argoproj/argo-cd#13066]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

My application can't be deployed, and the error message doesn't help. I've set log levels to "debug" for all ArgoCD components, but I don't get any more detail.

From ArgoCD UI, the application sync status is "Unknown", and there is 1 error :
**ComparisonError    rpc error: code = Unknown desc = unknown error: remote:**

The application is a multiple-source helm, and has exactly the same syntax and structure than another application which works fine on the same cluster

**To Reproduce**

The application manifest is : 

```
project: pk
destination:
  namespace: training
  name: my-cluster
sources:
  - repoURL: >-
      ssh://git@gitlab.xxxxxx.net/yyyyy/zzzzz/my-repo-name.git
    targetRevision: HEAD
    ref: values
  - repoURL: harbor.xxxxxx.net/yyyy/training
    targetRevision: 0.5.5
    helm:
      valueFiles:
        - $values/helm/values/values.yaml
    chart: my-chart
```

**Expected behavior**

The application should be deployed, or the error message should explain what's wrong ("Unknown" is not helpful).

**Screenshots**

![image](https://user-images.githubusercontent.com/2180151/229035564-59b19838-c0b4-40fb-bb9d-57b0af7e82d0.png)

![image](https://user-images.githubusercontent.com/2180151/229035603-aff452d9-553a-4069-9291-9d182dc157f0.png)

**Version**

```shell
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:45:12Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.6.7+5bcd846
```

**Logs**

```
argocd-repo-server :: level=error msg="finished unary call with code Unknown" error="unknown error: remote: " grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2023-03-31T05:49:06Z" grpc.time_ms=317.258 span.kind=server system=grpc
```
