### ISSUE TITLE
Application status is "OutOfSync" when deploy configmap with git tag

### ISSUE THREAD

**Issue by lnvn** [argoproj/argo-cd#13065]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I created a Helm repository in Gitlab, inside this repository contains a config-map.yaml file in helm chart, in the config-map.yaml file contains date(1) functions.

Then I create a new tag in Helm repository and create an application to deploy that tag.

After I deploy, the application always have status "OutOfSync"

(1) https://helm.sh/docs/chart_template_guide/function_list/#date-functions
**To Reproduce**

**Step 1**: Create helm chart with config-map.yaml file in template. The helm chart is located in Helm repository
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  config.json: |-
    {
      "version": {
        "time": "{{ now | date "2006-01-02T15:04:05+0000" }}"
      }
    }
```

**Step 2**: Create a git tag in Helm repository
Example: v2.2.2

**Step 3**: Create an Argocd application to deploy app with tag
- test-application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test-project
  source:
    repoURL: "https://<gitlab-url>/test/helm.git"
    targetRevision: v2.2.2
    path: my-app

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
```

After I deployed, the "CURRENT SYNC STATUS" is always "OutOfSync" event it's already sync.
![image](https://user-images.githubusercontent.com/29085915/229017654-6c99b59e-aa6f-45dd-acf4-c32066b9b4bb.png)

_**It will not happend if I use feature branch instead of tag in targetRevision.**_

**Expected behavior**

Usage of tag in targetRevision will not get OutOfSync

**Version**

```shell
I'm using:
- Argocd v2.5.2
- Gitlab
```
