### ISSUE TITLE
too many redirect on AWS EKS

### ISSUE THREAD

**Issue by tesla59** [argoproj/argo-cd#13092]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD is deployed on EKS (version: 1.25). Service type for argocd-server has been changed to LoadBalancer (as mentioned in the installation guide). External IP (of type loadbalancer-53783971.ap-south-1.elb.amazonaws.com
) is generated, and works as expected when used. When a CNAME record is made in, say, Cloudflare, to point to the external IP, the site doesnt work with error too_many_redirects

Another Case, ArgoCD is deployed on EKS (version: 1.25), Service type for argocd-server is kept as ClusterIP. Ingress setup has been done as mentioned in the guide [AWS Application Load Balancers (ALBs) And Classic ELB (HTTP Mode)](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode) .
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 #This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC specific features
  labels:
    app: argogrpc
  name: argogrpc
  namespace: argocd
spec:
  ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
      alb.ingress.kubernetes.io/conditions.argogrpc: |
        [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    name: argocd
    namespace: argocd
  spec:
    rules:
    - host: argocd.xxx.io
      http:
        paths:
        - path: /
          backend:
            service:
              name: argogrpc
              port:
                number: 443
          pathType: Prefix
        - path: /
          backend:
            service:
              name: argocd-server
              port:
                number: 443
          pathType: Prefix
    tls:
    - hosts:
      - argocd.xxx.io
```
After the Ingress is created, the external IP doesn't work as expected and health check for target group in AWS fails with Status Code 307 (Temporary Redirect). When the Host argocd.xxx.io is accessed, it returns error too_many_redirects

**To Reproduce**

1. Deploy ArgoCD on EKS
2. Change argocd-server type to LoadBalancer
3. Create a CNAME record to point to the External IP of LoadBalancer

**Expected behavior**

Accessing the app through External IP (in first case) should be same as accessing the app through generated CNAME
There is some kind of unexpected redirects happening

**Screenshots**

![image](https://user-images.githubusercontent.com/39598220/229580997-27825b64-a816-4545-8295-6e33a3fbf5ae.png)

**Version**

```shell
argocd: v2.6.7+unknown
  BuildDate: 2023-03-24T01:08:09Z
  GitCommit:
  GitTreeState:
  GitTag: 2.6.7
  GoVersion: go1.20.2
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
