### ISSUE TITLE
Does ClusterRole `argocd-application-controller` need such priviledges?

### ISSUE THREAD

**Issue by humbledude** [argoproj/argo-cd#1311]
I got Forbidden error while install argo-cd.
I am using customized cluster by DevOps team in company,
so I think it is forbidden by the DevOps team.

```
Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml": clusterroles.rbac.authorization.k8s.io "argocd-application-controller" is forbidden: attempt to grant extra privileges: ....
```

I edited `install.yaml` to change `argocd-application-controller` `ClusterRoleBinding` to reference `cluster-admin` and it seems working.
(I saw `DO NOT EDIT` on first line..)
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  #  name: argocd-application-controller
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
```

So, my question is, does `argo-application-controller` `ClusterRole` need such privileges?
If so, why not using `cluster-admin`?
I saw helm Tiller using `cluster-admin`.
