### ISSUE TITLE
Support merging ApplicationGenerator parameters using different keys

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#13118]
# Summary

Support merging ApplicationGenerator parameters using different keys:

```yaml
- merge:
    mergeKeys:
      - metadata.labels.env=path[0]
```

# Motivation

ApplicationSet `merge` generator allows merging result of two other generators using one or several keys. E.g.

```yaml
- merge:
    mergeKeys:
      - server
    generators:
      - clusters:
          values:
            kafka: 'true'
            redis: 'false'
      - clusters:
          selector:
            matchLabels:
              use-kafka: 'false'
          values:
            kafka: 'false'
```

The problem is generators might output keys with different names. Real-life use case: override application path in cluster labels with `env` label if directory generator finds `envs/<env-name>/<app-name>` directory. So in this case we need to merge using `metadata.labels.env` and `path[1]` which is not possible currently

# Proposal

Improve [merge](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/merge.go) generator to handle `=` in merge key definition.
