### ISSUE TITLE
tempalte function 'Helm.GetParameterValueByName()' doesn't return image.tag value expressed in '.argocd-source-myapp.yaml'

### ISSUE THREAD

**Issue by jeffreymlewis** [argoproj/argo-cd#13132]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Method `Helm.GetParameterValueByName()` inside a notification template is returning incorrect values. The default value in `values.yaml` is getting returned, rather then the override value specified in `.argocd-source-myapp.yaml`.

```
{{(call .repo.GetAppDetails).Helm.GetParameterValueByName "subchart.image.tag"}}
```

**To Reproduce**

* Deploy ArgoCD `v2.6.7` with a notification template like the following
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
  template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      *Tag:* {{(call .repo.GetAppDetails).Helm.GetParameterValueByName "subchart.image.tag"}}
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
```

* Deploy a "helm" app using ArgoCD
(Chart.yaml)
```yaml
apiVersion: v2
name: myapp
description: A Helm chart
type: application
version: 2.6.11

dependencies:
- name: subchart
  version: 2.6.11
  repository: https://raw.githubusercontent.com/myorg/subchart/main
```

(values.yaml)
```yaml
subchart:
  image:
    tag: notspecified
    repository: nginx
```

* Add an `.argocd-source-myapp.yaml` override file

(.argocd-source-myapp.yaml)
```yaml
helm:
  parameters:
  - name: subchart.image.repository
    value: nginx
    forcestring: true
  - name: subchart.image.tag
    value: stable-alpine
    forcestring: true
```

* Observe ArgoCD correctly deploying tag `stable-alpine`
* Observe the notification template saying the deployed tag is `notspecified`

**Expected behavior**

I expected the notification to show tag `stable-alpine`

**Screenshots**

N/A

**Version**

```shell
argocd@argo-cd-argocd-server-5fd8775f84-lzxm2:~$ argocd version
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

**Logs**

N/A
