### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13139]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
```
[root@localhost applicationSet]# kubectl logs -n argocd argocd-applicationset-controller-554d4fc79d-grwkt  --tail 100
time="2023-04-06T06:46:10Z" level=info msg="ArgoCD ApplicationSet Controller is starting" built="2023-01-10T19:30:17Z" commit=9db2c9471f6ff599c3f630b446e940d3a065620b namespace=argocd version=v2.5.6+9db2c94
I0406 06:46:11.984780       7 request.go:601] Waited for 1.030510818s due to client-side throttling, not priority and fairness, request: GET:https://10.68.0.1:443/apis/argoproj.io/v1alpha1?timeout=32s
time="2023-04-06T06:46:15Z" level=info msg="Starting configmap/secret informers"
time="2023-04-06T06:46:15Z" level=info msg="Configmap/secret informer synced"
time="2023-04-06T06:46:15Z" level=info msg="Starting manager"
time="2023-04-06T06:46:15Z" level=info msg="Starting webhook server"
time="2023-04-06T06:46:15Z" level=info msg="processing event for cluster secret" name=cluster-192.168.229.153-2643868442 namespace=argocd type=createSecretEventHandler
time="2023-04-06T06:46:15Z" level=info msg="listed ApplicationSets" count=1 type=createSecretEventHandler
time="2023-04-06T06:46:15Z" level=info msg="processing event for cluster secret" name=cluster-karmada-apiserver.karmada-system.svc.cluster.local-3895443601 namespace=argocd type=createSecretEventHandler
time="2023-04-06T06:46:15Z" level=info msg="listed ApplicationSets" count=1 type=createSecretEventHandler
time="2023-04-06T06:46:15Z" level=info msg="processing event for cluster secret" name=cluster-192.168.229.156-3815208859 namespace=argocd type=createSecretEventHandler
time="2023-04-06T06:46:15Z" level=info msg="listed ApplicationSets" count=1 type=createSecretEventHandler
time="2023-04-06T06:46:15Z" level=info msg="Kind.Group/Version Reference" kind.apiVersion=placementrules.apps.open-cluster-management.io/v1
time="2023-04-06T06:46:15Z" level=info msg="selection type" listOptions.FieldSelector="metadata.name=test-placement"
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 506 [running]:
github.com/argoproj/argo-cd/v2/applicationset/generators.(*DuckTypeGenerator).GenerateParams(0xc00124cc30, 0xc000b063c0, 0xc000a87600)
        /go/src/github.com/argoproj/argo-cd/applicationset/generators/duck_type.go:169 +0x1d0d
github.com/argoproj/argo-cd/v2/applicationset/generators.Transform({_, _, _, _, _, _, _, _, _}, 0xc00126e7b0, ...)
        /go/src/github.com/argoproj/argo-cd/applicationset/generators/generator_spec_processor.go:63 +0x8b0
github.com/argoproj/argo-cd/v2/applicationset/controllers.(*ApplicationSetReconciler).generateApplications(_, {{{0x2c0a1ef, 0xe}, {0xc000c754e8, 0x14}}, {{0xc000644b86, 0x6}, {0x0, 0x0}, {0xc000644ba0, ...}, ...}, ...})
        /go/src/github.com/argoproj/argo-cd/applicationset/controllers/applicationset_controller.go:434 +0x27e
github.com/argoproj/argo-cd/v2/applicationset/controllers.(*ApplicationSetReconciler).Reconcile(0xc000648a00, {0x4510748, 0xc000adb650}, {{{0xc000644ba0, 0x6}, {0xc000644b86, 0x6}}})
        /go/src/github.com/argoproj/argo-cd/applicationset/controllers/applicationset_controller.go:98 +0x185
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000a54bb0, {0x4510748, 0xc000adb620}, {{{0xc000644ba0?, 0x32dc0e0?}, {0xc000644b86?, 0x4041f4?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x27e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000a54bb0, {0x45106a0, 0xc00124ea00}, {0x307c580?, 0xc000d2f880?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x349
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000a54bb0, {0x45106a0, 0xc00124ea00})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x31c
```

**To Reproduce**
部署ocm

```
chmod +x clusteradm
mv clusteradm /usr/local/bin/

hub:
clusteradm init --context context-cluster1


cluster1:
clusteradm join --hub-token eyJhbGciOiJSUzI1NiIsImtpZCI6IjRFcVRRVE9ONnJSX3lIN0lqb2dpOWZ5TWhXcEtWWlJZeFVheGZXRGFocFkifQ.eyJhdWQiOlsiYXBpIiwiaXN0aW8tY2EiXSwiZXhwIjoxNjgwNzYyOTE5LCJpYXQiOjE2ODA3NTkzMTksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2YyIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoib3Blbi1jbHVzdGVyLW1hbmFnZW1lbnQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiY2x1c3Rlci1ib290c3RyYXAiLCJ1aWQiOiIzZTYxODU1NS01NGRjLTQzNTktYjllNC04OWUyYjU3MGQ5MzMifX0sIm5iZiI6MTY4MDc1OTMxOSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50OmNsdXN0ZXItYm9vdHN0cmFwIn0.M48s4nf7OFwHpH9bzpEankkgoi1fihGoxrX5q0F8kUZIpFrMYLB-_FOpSOONGA1j5LiYwZWlUlqF9bY0bEZbKhdvrPWgFJgqbA6FzqVWtJK1YylVOEePdl8o3hf99tkdHu18SEcWgrVSHTZD8cK21vXhIs1pe5GV1dzjMC8A23caNsJLZCRpJw8nFScY9cVlmCGnRpYjniAz-OLgVsyhUWjC0_hygUwx-spJB8H5PbG975WscaRNuirOSTqVqW57zgquqFt2Dokck_6YavBoLQTgRpuTIrNovJzBRnuN-pbSAC7lmzDVrfwCpIF4KJJZa1lfmJl4GOHWZkz4C-pxjg --hub-apiserver https://192.168.229.148:6443 --cluster-name cluster1

hub:
 clusteradm accept --clusters cluster1

cluster2:
clusteradm join --hub-token eyJhbGciOiJSUzI1NiIsImtpZCI6IjRFcVRRVE9ONnJSX3lIN0lqb2dpOWZ5TWhXcEtWWlJZeFVheGZXRGFocFkifQ.eyJhdWQiOlsiYXBpIiwiaXN0aW8tY2EiXSwiZXhwIjoxNjgwNzYyOTE5LCJpYXQiOjE2ODA3NTkzMTksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2YyIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoib3Blbi1jbHVzdGVyLW1hbmFnZW1lbnQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiY2x1c3Rlci1ib290c3RyYXAiLCJ1aWQiOiIzZTYxODU1NS01NGRjLTQzNTktYjllNC04OWUyYjU3MGQ5MzMifX0sIm5iZiI6MTY4MDc1OTMxOSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50OmNsdXN0ZXItYm9vdHN0cmFwIn0.M48s4nf7OFwHpH9bzpEankkgoi1fihGoxrX5q0F8kUZIpFrMYLB-_FOpSOONGA1j5LiYwZWlUlqF9bY0bEZbKhdvrPWgFJgqbA6FzqVWtJK1YylVOEePdl8o3hf99tkdHu18SEcWgrVSHTZD8cK21vXhIs1pe5GV1dzjMC8A23caNsJLZCRpJw8nFScY9cVlmCGnRpYjniAz-OLgVsyhUWjC0_hygUwx-spJB8H5PbG975WscaRNuirOSTqVqW57zgquqFt2Dokck_6YavBoLQTgRpuTIrNovJzBRnuN-pbSAC7lmzDVrfwCpIF4KJJZa1lfmJl4GOHWZkz4C-pxjg --hub-apiserver https://192.168.229.148:6443 --cluster-name cluster2

hub:
 clusteradm accept --clusters cluster2
```

```
hub:
clusteradm install hub-addon --names application-manager
clusteradm addon enable --names application-manager --clusters cluster1
clusteradm addon enable --names application-manager --clusters cluster2
clusteradm install hub-addon --names governance-policy-framework
clusteradm addon enable --names governance-policy-framework --clusters hub --annotate addon.open-cluster-management.io/on-multicluster-hub=true 
clusteradm addon enable --names governance-policy-framework --clusters cluster1
clusteradm addon enable --names governance-policy-framework --clusters cluster2
clusteradm addon enable addon --names config-policy-controller --clusters cluster1
clusteradm addon enable addon --names config-policy-controller --clusters cluster2
```

### clusterDecisionResource

```
git clone https://github.com/stolostron/multicloud-operators-placementrule
cd multicloud-operators-placementrule/
kubectl apply -f deploy/crd
kubectl create ns open-cluster-management
kubectl apply -f deploy/ -n open-cluster-management
```

#### configMapRef

applicationSet/ap-destinations-name.yaml

kubectl apply -f ap-destinations-name.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  description: this is my demo project
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
      name: cluster2
```

applicationSet/placementDecistion.yaml 

kubectl apply -f placementDecistion.yaml  -n argocd

```
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: test-placement
spec:
  clusterReplicas: 2
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
```

applicationSet/configmap.yaml

kubectl apply -f configmap.yaml -n argocd

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocm-placement
data:
  apiVersion: apps.open-cluster-management.io/v1
  kind: placementrules
  statusListKey: Decisions
  matchKey: "Cluster Name"
```

applicationSet/appset-generators-clusterDecisionResource-configMapRef.yaml

kubectl apply -f appset-generators-clusterDecisionResource-configMapRef.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement
        name: test-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{clusterName}}-mark'
    spec:
      project: project
      source:
        repoURL: https://gitee.com/hxpgit/argocd.git
        targetRevision: HEAD
        path: demo1/{{clusterName}}
      destination:
        server: '{{clusterName}}'
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true        
```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost applicationSet]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
