### ISSUE TITLE
error: error validating "appset-generators-cluster-filters.yaml": error validating data: ValidationError(ApplicationSet.spec.generators[0].clusters): unknown field "filters" in io.argoproj.v1alpha1.ApplicationSet.spec.generators.clusters; if you choose to ignore these errors, turn validation off with --validate=false

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13149]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
error: error validating "appset-generators-cluster-filters.yaml": error validating data: ValidationError(ApplicationSet.spec.generators[0].clusters): unknown field "filters" in io.argoproj.v1alpha1.ApplicationSet.spec.generators.clusters; if you choose to ignore these errors, turn validation off with --validate=false

**To Reproduce**
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          stage: dev
      filters:
      - expr: '{{name}} matches "cluster1.*"'
      - expr: '{{metadata.labels.stage}} in [dev]'
  template:
    metadata:
      name: '{{name}}-mark'
    spec:
      project: project
      source:
        repoURL: https://gitee.com/hxpgit/argocd.git
        targetRevision: HEAD
        path: demo1/{{name}}
      destination:
        server: '{{server}}'
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true        
```

https://github.com/argoproj/applicationset/blob/master/examples/design-doc/proposal/filters.yaml
this demo shows we can use filter,but I can not use it?

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost applicationSet]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
