### ISSUE TITLE
error generating params" error="error parsing values map" generator="&{}

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13153]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**
applicationSet/ap-sourceRepos.yaml

kubectl apply -f ap-sourceRepos.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  sourceRepos:
    - https://charts.bitnami.com/bitnami
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: mydest
    - server: https://192.168.229.156:6443
      namespace: demo
```

applicationSet/appset-generators-list-template-metadata.yaml

kubectl apply -f appset-generators-list-template-metadata.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
  - list:
      elements:
        - url: https://192.168.229.153:6443
          targetNamespace: demo
          appName: nginx
          repoUrl: https://charts.bitnami.com/bitnami
          chart: nginx
          version: 13.2.27
          values: |
            
        - url: https://192.168.229.156:6443
          targetNamespace: demo
          appName: redis
          repoUrl: https://charts.bitnami.com/bitnami
          chart: redis
          version: 17.8.0
          values: |
            master:
              persistence:
                enabled: false
            replica:
              persistence:
                enabled: false
      template:
        metadata:
          labels:
            app: '{{appName}}'
        spec:
          project: project
          source:
            chart: '{{chart}}'
            repoURL: '{{repoUrl}}' 
            targetRevision: '{{version}}'
            helm:
              values: |
                '{{values}}'
          destination:
            server: '{{url}}'
            namespace: '{{targetNamespace}}'          
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: project
      source:
        repoURL: https://gitee.com/hxpgit/argocd.git
        targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```

```

```

```
time="2023-04-07T10:20:53Z" level=error msg="error generating params" error="error parsing values map" generator="&{}"
time="2023-04-07T10:20:53Z" level=error msg="error generating application from params" error="error parsing values map" generator="{&ListGenerator{Elements:[]JSON{{[123 34 97 112 112 78 97 109 101 34 58 34 110 103 105 110 120 34 44 34 99 104 97 114 116 34 58 34 110 103 105 110 120 34 44 34 114 101 112 111 85 114 108 34 58 34 104 116 116 112 115 58 47 47 99 104 97 114 116 115 46 98 105 116 110 97 109 105 46 99 111 109 47 98 105 116 110 97 109 105 34 44 34 116 97 114 103 101 116 78 97 109 101 115 112 97 99 101 34 58 34 100 101 109 111 34 44 34 117 114 108 34 58 34 104 116 116 112 115 58 47 47 49 57 50 46 49 54 56 46 50 50 57 46 49 53 51 58 54 52 52 51 34 44 34 118 97 108 117 101 115 34 58 34 34 44 34 118 101 114 115 105 111 110 34 58 34 49 51 46 50 46 50 55 34 125]},{[123 34 97 112 112 78 97 109 101 34 58 34 114 101 100 105 115 34 44 34 99 104 97 114 116 34 58 34 114 101 100 105 115 34 44 34 114 101 112 111 85 114 108 34 58 34 104 116 116 112 115 58 47 47 99 104 97 114 116 115 46 98 105 116 110 97 109 105 46 99 111 109 47 98 105 116 110 97 109 105 34 44 34 116 97 114 103 101 116 78 97 109 101 115 112 97 99 101 34 58 34 100 101 109 111 34 44 34 117 114 108 34 58 34 104 116 116 112 115 58 47 47 49 57 50 46 49 54 56 46 50 50 57 46 49 53 54 58 54 52 52 51 34 44 34 118 97 108 117 101 115 34 58 34 109 97 115 116 101 114 58 92 110 32 32 112 101 114 115 105 115 116 101 110 99 101 58 92 110 32 32 32 32 101 110 97 98 108 101 100 58 32 102 97 108 115 101 92 110 114 101 112 108 105 99 97 58 92 110 32 32 112 101 114 115 105 115 116 101 110 99 101 58 92 110 32 32 32 32 101 110 97 98 108 101 100 58 32 102 97 108 115 101 92 110 34 44 34 118 101 114 115 105 111 110 34 58 34 49 55 46 56 46 48 34 125]},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{app: {{appName}},},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:ApplicationSource{RepoURL:{{repoUrl}},Path:,TargetRevision:{{version}},Helm:&ApplicationSourceHelm{ValueFiles:[],Parameters:[]HelmParameter{},ReleaseName:,Values:'{{values}}'\n,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:{{chart}},},Destination:ApplicationDestination{Server:{{url}},Namespace:{{targetNamespace}},Name:,},Project:project,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,},},} nil nil nil nil nil nil nil nil}"
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost applicationSet]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
