### ISSUE TITLE
git type applicationset generator ignoreDifferences not effective

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13150]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

git type applicationset generator ignoreDifferences not effective
**To Reproduce**
applicationSet/ap-destinations-name.yaml

kubectl apply -f ap-destinations-name.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  description: this is my demo project
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
      name: cluster2
```

applicationSet/appset-generators-git-template-ignoreDifferences.yaml

kubectl apply -f appset-generators-git-template-ignoreDifferences.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
  - git:
      repoURL: https://gitee.com/hxpgit/argocd.git
      revision: HEAD
      directories:
      - path: demo1/git-generator-directory/excludes/cluster-addons/*
      template:
        metadata:
          labels:
            app: '{{path.basename}}'
        spec:
          project: project
          source:
            repoURL: https://gitee.com/hxpgit/argocd.git
            targetRevision: HEAD
            path: '{{path}}'
          destination:
            server: https://192.168.229.153:6443
            namespace: demo
          ignoreDifferences:
          - group: apps
            kind: Deployment
            jsonPointers:
            - /spec/template/metadata/annotations
            - /spec/replicas
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: xxx
      source:
        repoURL: https://gitee.com/hxpgit/xxx.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: xxx
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true 
```

```
[root@localhost applicationSet]# argocd app list
NAME            CLUSTER                       NAMESPACE  PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                 PATH                                                           TARGET
argocd/busybox  https://192.168.229.153:6443  demo       project  Synced  Healthy  Auto-Prune  <none>      https://gitee.com/hxpgit/argocd.git  demo1/git-generator-directory/excludes/cluster-addons/busybox  HEAD
argocd/nginx    https://192.168.229.153:6443  demo       project  Synced  Healthy  Auto-Prune  <none>      https://gitee.com/hxpgit/argocd.git  demo1/git-generator-directory/excludes/cluster-addons/nginx    HEAD
argocd/redis    https://192.168.229.153:6443  demo       project  Synced  Healthy  Auto-Prune  <none>      https://gitee.com/hxpgit/argocd.git  demo1/git-generator-directory/excludes/cluster-addons/redis    HEAD

[root@member1-153 ~]# kubectl get pod -n demo
NAME                       READY   STATUS    RESTARTS   AGE
busybox-7f44ff447f-l45c7   1/1     Running   0          22s
nginx-787f54657b-nj8v4     1/1     Running   0          32s
redis-7b76576cd4-slnbb     1/1     Running   0          32s

[root@member1-153 ~]# kubectl scale deploy nginx --replicas=3 -n demo
deployment.apps/nginx scaled
[root@member1-153 ~]# kubectl get pod -n demo
NAME                       READY   STATUS              RESTARTS   AGE
busybox-7f44ff447f-l45c7   1/1     Running             0          52s
nginx-787f54657b-n2tft     0/1     ContainerCreating   0          2s
nginx-787f54657b-nj8v4     1/1     Running             0          62s
nginx-787f54657b-t82t6     0/1     ContainerCreating   0          2s
redis-7b76576cd4-slnbb     1/1     Running             0          62s

[root@localhost applicationSet]# argocd app sync nginx
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2023-04-07T00:37:25-07:00   apps  Deployment        demo                 nginx    Synced  Healthy              
2023-04-07T00:37:26-07:00   apps  Deployment        demo                 nginx    Synced  Healthy              deployment.apps/nginx configured
2023-04-07T00:37:26-07:00   apps  Deployment        demo                 nginx    Synced  Progressing              deployment.apps/nginx configured
2023-04-07T00:37:26-07:00   apps  Deployment        demo                 nginx    Synced  Healthy              deployment.apps/nginx configured

Name:               argocd/nginx
Project:            project
Server:             https://192.168.229.153:6443
Namespace:          demo
URL:                https://argocd-server.argocd.svc.cluster.local/applications/nginx
Repo:               https://gitee.com/hxpgit/argocd.git
Target:             HEAD
Path:               demo1/git-generator-directory/excludes/cluster-addons/nginx
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Synced to HEAD (a78475a)
Health Status:      Healthy

Operation:          Sync
Sync Revision:      a78475aa92eedc51e9b2fe13c886950471c1b441
Phase:              Succeeded
Start:              2023-04-07 00:37:25 -0700 PDT
Finished:           2023-04-07 00:37:26 -0700 PDT
Duration:           1s
Message:            successfully synced (all tasks run)

GROUP  KIND        NAMESPACE  NAME   STATUS  HEALTH   HOOK  MESSAGE
apps   Deployment  demo       nginx  Synced  Healthy        deployment.apps/nginx configured


[root@member1-153 ~]# kubectl get pod -n demo
NAME                       READY   STATUS    RESTARTS   AGE
busybox-7f44ff447f-l45c7   1/1     Running   0          2m29s
nginx-787f54657b-nj8v4     1/1     Running   0          2m39s
redis-7b76576cd4-slnbb     1/1     Running   0          2m39s
```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@localhost applicationSet]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
**Logs**

```
Paste any relevant application logs here.
```
