### ISSUE TITLE
Frontend crashing when re-editing previous YAML template

### ISSUE THREAD

**Issue by agilob** [argoproj/argo-cd#13155]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

I'm trying to add values.yaml for a helm chart I'm deploying, so I fill the necessary values in web UI when I edit in YAML, the webui doesn't offer a way to include custom values.yaml so I go do yaml and edit:
![image](https://user-images.githubusercontent.com/2544251/230635831-763a9227-98ba-4e6a-a156-4939a96a26f3.png)

I edit sources to include my custom values and click SAVE

then I go back and click Edit YAML again

![image](https://user-images.githubusercontent.com/2544251/230635623-4b492559-3035-41e7-96c9-8c95f8872a87.png)

**Version**

```shell
❯ argocd version
argocd: v2.6.7+unknown
  BuildDate: 2023-03-24T01:08:09Z
  GitCommit:
  GitTreeState:
  GitTag: 2.6.7
  GoVersion: go1.20.2
  Compiler: gc
  Platform: linux/amd64
```

**Comment by agilob** [comment]
I eventually found out what I need  can be done with:
```
argocd app create pyroscope --repo https://pyroscope-io.github.io/helm-chart --helm-chart pyroscope --revision 0.2.92 --dest-namespace monitoring --dest-server https://kubernetes.default.svc --values-literal-file pyroscope.yaml
```

which results in:
```
destination:
  namespace: monitoring
  server: https://kubernetes.default.svc
project: pyroscope
sources:
- chart: pyroscope
  helm:
    valueFiles:
    - $values/pyroscope/pyroscope.yaml
  repoURL: https://pyroscope-io.github.io/helm-chart
  targetRevision: 0.2.92
- ref: values
  repoURL: totally_my_repo
  targetRevision: HEAD
syncPolicy:
  syncOptions:
  - ApplyOutOfSyncOnly=true
```

but that wasn't easy nor documented anywhere I looked
