### ISSUE TITLE
applicationset pullrequest gitea ignoreDifference is not effective

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13164]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**
applicationSet/appProject-gitea.yaml

kubectl apply -f appProject-gitea.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - http://192.168.229.148:3000/mark/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
    - server: https://192.168.229.156:6443
      namespace: demo
```

```
settings->applications->generate tokens

kubectl create secret generic gitea-auth --from-literal token=327b4bce27495f226856a56aff39c69da3ea1977 -n argocd
```

applicationSet/appset-generators-pullRequest-template-ignoreDifferences.yaml

kubectl apply -f appset-generators-pullRequest-template-ignoreDifferences.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
  - pullRequest:
      gitea:
        api: http://192.168.229.148:3000
        owner: mark
        insecure: true
        repo: argocd
        tokenRef:
          secretName: gitea-auth
          key: token
      template:
        metadata:
          labels:
            app: nginx
        spec:
          source:
            repoURL: 'http://192.168.229.148:3000/mark/argocd.git'
            targetRevision: '{{ head_sha }}'
            path: demo1
          project: project
          destination:
            server: https://192.168.229.153:6443
            namespace: demo
          ignoreDifferences:
          - group: apps
            kind: Deployment
            jsonPointers:
            - /spec/template/metadata/annotations
            - /spec/replica
      requeueAfterSeconds: 30
  template:
    metadata:
      name: 'myapp-{{ branch }}-{{ number }}'
    spec:
      source:
        repoURL: 'xxx'
        targetRevision: 'xxx'
        path: demo1
      project: project
      destination:
        server: https://192.168.229.153:6443
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
```

```
[root@localhost applicationSet]# argocd app list
NAME                 CLUSTER                       NAMESPACE  PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                         PATH   TARGET
argocd/myapp-main-1  https://192.168.229.153:6443  demo       project  Synced  Healthy  Auto-Prune  <none>      http://192.168.229.148:3000/mark/argocd.git  demo1  596bba2e25ab48243c92485c7d81e7160f107785

[root@member1-153 ~]# kubectl get pod -n demo
NAME                           READY   STATUS    RESTARTS   AGE
nginx-gitea-787f54657b-cmhvk   1/1     Running   0          4s
[root@member1-153 ~]# kubectl scale deploy nginx-gitea --replicas=3 -n demo
deployment.apps/nginx-gitea scaled
[root@member1-153 ~]# kubectl get pod -n demo
NAME                           READY   STATUS        RESTARTS   AGE
nginx-gitea-787f54657b-2lw26   0/1     Terminating   0          1s
nginx-gitea-787f54657b-cmhvk   1/1     Running       0          7s
nginx-gitea-787f54657b-mlwj2   0/1     Terminating   0          1s

无效
```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
