### ISSUE TITLE
time="2023-04-08T08:28:20Z" level=error msg="error generating params" error="error listing repos: error listing pull requests for argocd/argocd: Get \"/account/signin/?next=%2F195446040%2Frest%2Fapi%2F1.0%2Fprojects%2Fargocd%2Frepos%2Fargocd%2Fpull-requests%3Flimit%3D100\": stopped after 10 redirects" generator="&{0xc0010cdc70 0x2420860 {0xc00082e1b0}}"

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13161]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**
bitbucketserver can not list pullrequest

```
time="2023-04-08T08:28:20Z" level=error msg="error generating params" error="error listing repos: error listing pull requests for argocd/argocd: Get \"/account/signin/?next=%2F195446040%2Frest%2Fapi%2F1.0%2Fprojects%2Fargocd%2Frepos%2Fargocd%2Fpull-requests%3Flimit%3D100\": stopped after 10 redirects" generator="&{0xc0010cdc70 0x2420860 {0xc00082e1b0}}"
time="2023-04-08T08:28:20Z" level=error msg="error generating application from params" error="error listing repos: error listing pull requests for argocd/argocd: Get \"/account/signin/?next=%2F195446040%2Frest%2Fapi%2F1.0%2Fprojects%2Fargocd%2Frepos%2Fargocd%2Fpull-requests%3Flimit%3D100\": stopped after 10 redirects" generator="{nil nil nil nil nil &PullRequestGenerator{Github:nil,GitLab:nil,Gitea:nil,BitbucketServer:&PullRequestGeneratorBitbucketServer{Project:argocd,Repo:argocd,API:https://bitbucket.org/195446040,BasicAuth:&BasicAuthBitbucketServer{Username:hxpwangyi,PasswordRef:&SecretRef{SecretName:bucket-password,Key:password,},},},Filters:[]PullRequestGeneratorFilter{},RequeueAfterSeconds:*30,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:ApplicationSource{RepoURL:,Path:,TargetRevision:,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,},Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,},},} nil nil nil}"
```
**To Reproduce**
applicationSet/appProject-bitbucket.yaml

kubectl apply -f appProject-bitbucket.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://hxpwangyi@bitbucket.org/195446040/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
    - server: https://192.168.229.156:6443
      namespace: demo
```

applicationSet/appset-generators-pullRequest-bitbucketServer-project.yaml

kubectl apply -f appset-generators-pullRequest-bitbucketServer-project.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
  - pullRequest:
      bitbucketServer:
        api: https://bitbucket.org/195446040
        basicAuth:
          username: hxpwangyi
          passwordRef:
            secretName: bucket-password
            key: password
        project: argocd     
        repo: argocd
      requeueAfterSeconds: 30
  template:
    metadata:
      name: 'myapp-{{ branch }}-{{ number }}'
    spec:
      source:
        repoURL: 'https://hxpwangyi@bitbucket.org/195446040/argocd.git'
        targetRevision: '{{ head_sha }}'
        path: .
      project: project
      destination:
        server: https://192.168.229.153:6443
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```

```

```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
