### ISSUE TITLE
applicationset scmProvider gitea error listing repos: 404 Not Found

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13176]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

```
time="2023-04-10T07:17:52Z" level=error msg="error generating params" error="error listing repos: 404 Not Found" generator="&{0xc00126c9b0 <nil> {0xc001272d50}}"
time="2023-04-10T07:17:52Z" level=error msg="error generating application from params" error="error listing repos: 404 Not Found" generator="{nil nil nil &SCMProviderGenerator{Github:nil,Gitlab:nil,Bitbucket:nil,BitbucketServer:nil,Gitea:&SCMProviderGeneratorGitea{Owner:mark,API:http://192.168.229.148:3000,TokenRef:&SecretRef{SecretName:gitea-auth,Key:token,},AllBranches:true,Insecure:true,},AzureDevOps:nil,Filters:[]SCMProviderGeneratorFilter{},CloneProtocol:http,RequeueAfterSeconds:*30,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{sha: {{sha}},},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:ApplicationSource{RepoURL:{{url}},Path:demo1,TargetRevision:{{ sha }},Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,},Destination:ApplicationDestination{Server:https://192.168.229.153:6443,Namespace:demo,Name:,},Project:project,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,},},} nil nil nil nil nil}"
[root@mycompany applicationSet]# 
```
**To Reproduce**
applicationSet/appProject-gitea-scm-http.yaml

kubectl apply -f appProject-gitea-scm-http.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - http://192.168.229.148:3000/mark/argocd-2.git
    - http://192.168.229.148:3000/mark/argocd-3.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
    - server: https://192.168.229.156:6443
      namespace: demo
```

```
settings->applications->generate tokens

kubectl create secret generic gitea-auth --from-literal token=6d2d30b3f4f623897ce91814e51c4baf35beff0a -n argocd 
```

applicationSet/appset-generators-scmProvider-gitea-allBranches.yaml

kubectl apply -f appset-generators-scmProvider-gitea-allBranches.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
spec:
  generators:
  - scmProvider:
      gitea:
        api: http://192.168.229.148:3000
        allBranches: true
        owner: mark
        insecure: true
        tokenRef:
          secretName: gitea-auth
          key: token
      requeueAfterSeconds: 30
      cloneProtocol: http
      template:
        metadata:
          labels:
            sha: '{{sha}}'
        spec:
          source:
            repoURL: '{{url}}'
            targetRevision: '{{ sha }}'
            path: demo1
          project: project
          destination:
            server: https://192.168.229.153:6443
            namespace: demo        
  template:
    metadata:
      name: 'myapp-{{ repository }}'
    spec:
      source:
        repoURL: 'http://192.168.229.148:3000/mark/argocd.git'
        targetRevision: '{{ head_sha }}'
        path: demo1
      project: project
      destination:
        server: https://192.168.229.153:6443
        namespace: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```

```

```

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
[root@mycompany applicationSet]# argocd version
argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.6+9db2c94
**Logs**

```
Paste any relevant application logs here.
```
