### ISSUE TITLE
repo.GetAppDetails doesn't return all paramters, values etc. of the specific app

### ISSUE THREAD

**Issue by PG2000** [argoproj/argo-cd#13171]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If i use the Helper function

`{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "simple" }}`

 from a notification template **no value** is returned even when i can see the expected value in `.app.spec.source.helm.parameters` from the template.

After trying to return all Helm specific variables with a call to:
`{{ (call .repo.GetAppDetails).Helm}}` i can see that only the Parameters from the `values-dev.yaml` are available.

In the UI all expected paramters are visible so that i think something is wrong in the function.

**To Reproduce**

I have created this app from an application set and a notifcation cm.

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: dev-apps-helm
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - git:
              files:
                - path: apps/**/dev-test/config.json
              repoURL: https://gitlab.com/<test-repo>
              requeueAfterSeconds: 20
              revision: HEAD
              template:
                metadata: {}
                spec:
                  destination: {}
                  project: ""
                  source:
                    repoURL: ""
          - pullRequest:
              gitlab:
                project: some-repo/test
                api: https://gitlab.com/api/v4
                tokenRef:
                  secretName: gitlab-automation-token
                  key: token
                labels:
                  - "update/patch"
                pullRequestState: opened
              requeueAfterSeconds: 300
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.gitlab: ""
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ .appName }}'
        foo: bar
      name: 'dev-{{ .userGivenName }}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{ .destNamespace }}'
        name: '{{ .destServer }}'
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: dev-test
      source:
        path: '{{ .srcPath }}/dev-test/'
        repoURL: '{{ .srcRepoURL }}'
        targetRevision: '{{ default "HEAD" .head_sha }}'
        helm:
          parameters:
            - name: "simple"
              value: "easy"
          valueFiles:
            - 'values-dev.yaml'
          values: |
            my-number: 2
      syncPolicy:
        automated:
          allowEmpty: true
          prune: false
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
status: {}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://localhost:8080

  service.webhook.gitlab: |
    url: https://gitlab.com/
    headers:
    - name: Authorization
      value: Bearer $token
    subscriptions: |
      - recipients
        - gitlab
        triggers:
        - on-sync-succeeded
  template.app-sync-succeeded: |
    webhook:
      gitlab:
        method: POST
        path: api/v4/projects/7229/merge_requests/{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "simple" }}/pipelines
        body: |
          {
            "body": "app sync {{.app.metadata.name}}"
          }
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
---
```

**Expected behavior**

From my example i would expect to see the value `easy` when i call `{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "simple" }}` from the notification template

**Screenshots**

**Version**

```shell
v2.6.7+5bcd846
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by evheniyt** [comment]
Looks like `Parameters` contains data from `helm.valueFiles` and not from `helm.parameters`. It looks incorrectly, as `FileParameters` should contain such values

**Comment by lucasoares** [comment]
For me is even worse. For my application `GetAppDetails` is returning null for Helm. It is a multi-source argo application where helm is the second source:

```
        - repoURL: 'https://github.com/foo/bar.git'
          targetRevision: HEAD
          ref: values
        - repoURL: 'foobar.azurecr.io/helm'
          chart: 'foo-bar'
          targetRevision: '0.1.44'
          helm:
            valueFiles:
              - '$values/applications/{{.values.appName}}/shared.yaml'
```

How to fetch the helm details when using multi-source?
