### ISSUE TITLE
Application parameters string not preserving newlines or indentation

### ISSUE THREAD

**Issue by manzamor-cs** [argoproj/argo-cd#13180]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to create and utilize a helm-kustomization plugin to deploy a kustomized version of jsPolicy onto a cluster. When I try to pass a couple of block string parameters to the plugin, the newlines and indentations are not preserved in the resulting environment variables, causing a failure to generate the manifests and sync.

**To Reproduce**

Here's the plugin config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-kustomization-plugin-config
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-kustomization-plugin
    spec:
      init:
        # Using this for testing
        command: [sh]
        args: 
          - '-c'
          - >
            echo "Initializing...";
            echo $PARAM_VALUES > /tmp/values_test.yaml;
            echo $PARAM_PATCH > /tmp/patch_test.yaml;
            echo $ARGOCD_APP_PARAMETERS > /tmp/params_test.yaml;
      generate:
        command: [sh, -c]
        args:
          - >
            echo $PARAM_VALUES |
            helm template -f - $ARGOCD_APP_NAME . > all.yaml &&
            echo $PARAM_PATCH > patch.yaml &&
            cp /kustomization.yaml . &&
            kustomize build .
      parameters:
        static:
          - name: values
            title: Values
            itemType: string
            collectionType: string
          - name: patch
            title: Patch
            itemType: string
            collectionType: string
  # Being mounted in the root folder
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources: [all.yaml]
    patches: [patch.yaml]
```

Here's the Application manifest:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jspolicy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.loft.sh/
    chart: jspolicy
    targetRevision: v0.2.2
    plugin:
      name: helm-kustomization-plugin
      parameters:
        - name: values
          string: |
            image: loftsh/jspolicy:0.2.2
            priorityClassName: system-cluster-critical
            replicaCount: 2
            podDisruptionBudget:
              create: true
              minAvailable: 1
        - name: patch
          string: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: jspolicy
              namespace: jspolicy
            spec:
              template:
                spec:
                  hostNetwork: true
                  securityContext:
                    fsGroup: 1000
                    supplementalGroups: [ 1000 ]
                  containers:
                    - name: jspolicy
                      ports:
                        - containerPort: 8080
                          hostPort: 8080
                          name: metrics-server
                          protocol: TCP
  destination:
    name: in-cluster
    namespace: jspolicy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

Dockerfile used to build the image of the container:

```Dockerfile
FROM alpine:3.17
RUN apk update && \
    apk add helm && \
    apk add kustomize -X https://dl-cdn.alpinelinux.org/alpine/edge/community
```

The changes I made to the repo-server deployment:

```yaml
spec:
  template:
    spec:
      volumes:
        - name: helm-kustomization-plugin-config
          configMap:
            name: helm-kustomization-plugin-config
            defaultMode: 420
        - name: cmp-tmp
          emptyDir: {}
      containers:
        - name: helm-kustomization-plugin
          image: <PRIVATE_REGISTRY>/helm-kustomize-ubuntu
          command:
            - /var/run/argocd/argocd-cmp-server
          resources: {}
          volumeMounts:
            - name: var-files
              mountPath: /var/run/argocd
            - name: plugins
              mountPath: /home/argocd/cmp-server/plugins
            - name: helm-kustomization-plugin-config
              mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
            - name: helm-kustomization-plugin-config
              mountPath: /kustomization.yaml
              subPath: kustomization.yaml
            - name: cmp-tmp
              mountPath: /tmp
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            runAsUser: 999
            runAsNonRoot: true
```

These are the environment variables I'm receiving in the plugin container (after being piped into persistent files using the plugin's init command):

```sh
I have no name!@argo-cd-argocd-repo-server-d647876d5-j5ffk:/$ cd tmp/
I have no name!@argo-cd-argocd-repo-server-d647876d5-j5ffk:/tmp$ ls
_cmp_server  params_test.yaml  patch_test.yaml  values_test.yaml
I have no name!@argo-cd-argocd-repo-server-d647876d5-j5ffk:/tmp$ cat values_test.yaml 
image: loftsh/jspolicy:0.2.2 replicaCount: 3 podDisruptionBudget: create: true minAvailable: 1
I have no name!@argo-cd-argocd-repo-server-d647876d5-j5ffk:/tmp$ cat patch_test.yaml 
apiVersion: apps/v1 kind: Deployment metadata: name: jspolicy namespace: jspolicy spec: template: spec: hostNetwork: true securityContext: fsGroup: 1000 supplementalGroups: [ 1000 ] containers: - name: jspolicy ports: - containerPort: 8080 hostPort: 8080 name: metrics-server protocol: TCP
I have no name!@argo-cd-argocd-repo-server-d647876d5-j5ffk:/tmp$ cat params_test.yaml 
[{"name":"values","string":"image: loftsh/jspolicy:0.2.2
replicaCount: 3
podDisruptionBudget:
 create: true
 minAvailable: 1
"},{"name":"patch","string":"apiVersion: apps/v1
kind: Deployment
metadata:
 name: jspolicy
 namespace: jspolicy
spec:
 template:
 spec:
 hostNetwork: true
 securityContext:
 fsGroup: 1000
 supplementalGroups: [ 1000 ]
 containers:
 - name: jspolicy
 ports:
 - containerPort: 8080
 hostPort: 8080
 name: metrics-server
 protocol: TCP
"}]
```

The error I get in the UI:
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/124194098/230947296-df537eec-b01a-42d7-8fde-4918d77d54a9.png">

**Expected behavior**

I expect the parameter strings to be passed into the environment variables (both ARGOCD_APP_PAREMETERS and PARAM_<name>) with newlines and indentations preserved. 

**Version**

```shell
argocd: v2.6.5+60104ac.dirty
  BuildDate: 2023-03-14T17:59:42Z
  GitCommit: 60104aca6faec73d10d57cb38245d47f4fb3146b
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.7+5bcd846
```

**Logs**

```sh
time="2023-04-10T16:23:19Z" level=info msg="Generating manifests with no request-level timeout"
time="2023-04-10T16:23:19Z" level=info msg="sh -c \"echo \\\"Initializing...\\\"; echo $PARAM_VALUES > /tmp/values_test.yaml; echo $PARAM_PATCH > /tmp/patch_test.yaml; echo $ARGOCD_APP_PARAMETERS > /tmp/params_test.yaml;\\n\"" dir=/tmp/_cmp_server/1f926c89-8208-40ab-aea5-5f00612da73c execID=2abe9
time="2023-04-10T16:23:19Z" level=info msg="sh -c \"echo $PARAM_VALUES | helm template -f - $ARGOCD_APP_NAME . > all.yaml && echo $PARAM_PATCH > patch.yaml && cp /kustomization.yaml . && kustomize build .\\n\"" dir=/tmp/_cmp_server/1f926c89-8208-40ab-aea5-5f00612da73c execID=13be6
time="2023-04-10T16:23:19Z" level=error msg="`sh -c \"echo $PARAM_VALUES | helm template -f - $ARGOCD_APP_NAME . > all.yaml && echo $PARAM_PATCH > patch.yaml && cp /kustomization.yaml . && kustomize build .\\n\"` failed exit status 1: Error: failed to parse -: error converting YAML to JSON: yaml: mapping values are not allowed in this context" execID=13be6
time="2023-04-10T16:23:19Z" level=error msg="finished streaming call with code Unknown" error="error generating manifests: `sh -c \"echo $PARAM_VALUES | helm template -f - $ARGOCD_APP_NAME . > all.yaml && echo $PARAM_PATCH > patch.yaml && cp /kustomization.yaml . && kustomize build .\\n\"` failed exit status 1: Error: failed to parse -: error converting YAML to JSON: yaml: mapping values are not allowed in this context" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-04-10T16:23:19Z" grpc.time_ms=28.796 span.kind=server system=grpc
```
