### ISSUE TITLE
Application manifest and state changes while a sync is running 

### ISSUE THREAD

**Issue by zmotu** [argoproj/argo-cd#13187]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

An Application manifest and state changes while a sync is running causing differences between resources applied during different phases of the Sync. 

For example. 

1. ArgoCD Image Updater sets the `spec.source.helm.parameters.0` to `image.tag: A`
2. The PreSync runs with `image.tag: A` helm parameter. The job takes minutes to complete. 
3. Image Updater changes the `spec.source.helm.parameters.0` to `image.tag: B` before the PreSync job completes. 
4. The Sync phase runs with `image.tag: B`. 

This has considerable implications for PreSync jobs such as database migrations where the deployed application version may start without a db migration for that version being run. 

**To Reproduce**
1. helm create new
2. Add a presync job that sleeps 2 minutes
```
---
# Source: new/templates/PreSync.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    spec:
      containers:
        - name: web-pre-sync-upload-assets
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - 
              |
                sleep 120
          image: "{{ image.name }}:{{ image.tag }}"

```
4. Create an Argo Application deploying the new chart
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    helm:
      parameters:
        - forceString: true
          name: image.tag
          value: 1.22     
    path: new
```
5. Sync the application in the UI
6. Update the `spec.source.helm.parameters.0.value` to `1.23`
7. Check the container image pulled by kubernetes deployment on Sync
8. Check the applications `status.history.0.source.helm.parameters.0.value`. This should be `1.23` instead of `1.22`. 

**Expected behavior**

1. Sync completes using container image tag `1.22` 
2. Applications `status.history.0.source.helm.parameters.0.value` is `1.22`. 
3. Application is OutOfSync immediately after Sync completed successfully.

**Screenshots**
N/A

**Version**

```shell
{
    "Version": "v2.5.3+0c7de21",
    "BuildDate": "2022-11-28T16:51:33Z",
    "GitCommit": "0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
Nil sharable
```

**Notes**
It is suspected that this may be a pass by reference opposed to pass by value issue where the lookup of application spec and manifest changes between Sync phases or Syncing of resources. 

There are inline comments noting that a revisions commit sha should not change while a sync is in progress but no protections against the spec changing from what i can see in 
https://github.com/argoproj/argo-cd/blob/master/controller/sync.go#L60-L64
