### ISSUE TITLE
AppType Discovery unreliably distinguishes between Kustomize and Helm

### ISSUE THREAD

**Issue by howardjohn** [argoproj/argo-cd#13210]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Discover https://github.com/argoproj/argo-cd/blob/9aa1351e5645ab7477a4d2725187228a58f22797/util/app/discovery/discovery.go#L59-L64 is meant to determine if an app is Helm or Kustomize.

The result is deterministic due to the fact file.Walk sorts things, and `kustomization.yaml` comes after `Chart.yaml` in that sorting, so Kustomize will always "win".

However, I would argue its not quite right. For example:

```yaml
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: ~1.17.2
```

In this chart, there is both a kustomization.yaml and Chart.yaml. This leads to Argo-CD picking kustomize, leading to unexpected behavior (https://github.com/istio/istio/issues/44237). This is _also_ largely a bug in the Istio chart, which we (I am an Istio maintainer) will address on our end.

Per the API spec:
```
   chart        <string>
     Chart is a Helm chart name, and must be specified for applications sourced
     from a Helm repo.
```

So it seems a bit misleading to have a user explicitly convey intent to use Helm (via `chart` attribute) but then using Kustomize.

Explicitly setting some Helm attribute works around this:

```yaml
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: ~1.17.2
    helm:
      values: |
        fake: bar
```

**To Reproduce**

```
kubectl create namespace istio-system
cat <<EOF | kubectl apply -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: ~1.17.2
    helm:
      values: |
        fake: bar
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
EOF
```

The istiod Deployment will have gcr.io/istio-testing/pilot:latest (from kustomize); it should be docker.io/istio/pilot:1.17.2 (from helm)

**Expected behavior**

Helm should probably be used here? Or maybe some indication that both are present, etc

**Version**

```shell
docker.io/istio/pilot:1.17.2
```
