### ISSUE TITLE
Helm Local sub-chart with sub-charts

### ISSUE THREAD

**Issue by DoomAndLove** [argoproj/argo-cd#13224]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When ArgoCD is deploying a Helm chart which has a sub chart via file path ("file://") and that sub chart has a sub chart (file or hosted), the bottom most chart is ignored by argo

**To Reproduce**

https://github.com/DoomAndLove/helm-subcharts-subchart
top-chart
->middle-chart via file path
--->bottom-chart is ignore by argo

Create an Application against "top-chart"

One Created Service Account

```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: middle-chart
    app.kubernetes.io/version: 1.16.0
    argocd.argoproj.io/instance: release-name
    helm.sh/chart: middle-chart-0.1.0
  name: release-name-middle-chart
  namespace: default
```

**Expected behavior**

Two ServiceAcount Created, output from helm template

```
---
# Source: top-chart/charts/middle-chart/charts/bottom-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-bottom-chart
  labels:
    helm.sh/chart: bottom-chart-0.1.0
    app.kubernetes.io/name: bottom-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: top-chart/charts/middle-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-middle-chart
  labels:
    helm.sh/chart: middle-chart-0.1.0
    app.kubernetes.io/name: middle-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
```

**Screenshots**

**Version**

```shell
argocd-server: v2.6.1+3f143c9
  BuildDate: 2023-02-08T18:51:05Z
  GitCommit: 3f143c9307f99a61bf7049a2b1c7194699a7c21b
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1

```

**Logs**

```
Paste any relevant application logs here.
```
