### ISSUE TITLE
Multiple ingress hosts not shown

### ISSUE THREAD

**Issue by yingtho** [argoproj/argo-cd#13233]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When there is an ingress with multiple hosts the UI in argocd app will only show the first ingress host.

**To Reproduce**

Create an ingress with multiple host like:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: example
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: example
    app.kubernetes.io/version: 1.16.0
    argocd.argoproj.io/instance: example
    helm.sh/chart: invoice-backend-1.2.1
  name: invoice
  namespace: invoice-example
spec:
  ingressClassName: nginx
  rules:
    - host: sub1.example.com
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: sub2.example.com
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
```

**Expected behavior**

I expected there will be links to all ingress hosts.

**Screenshots**
![image](https://user-images.githubusercontent.com/4170913/232004451-a9d4c09b-56cc-4f47-a65b-211d0311292f.png)
Here it only shows one link for ingress but it should show two links when there is two ingress hosts.

**Version**

```shell
v2.6.2+6e02f8b.
```

**Logs**

```
Paste any relevant application logs here.
```
