### ISSUE TITLE
ConfigManagementPlugin env can not get from application

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13291]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ]x I've pasted the output of `argocd version`.

**Describe the bug**

ARGOCD_ENV_HELM_OPTS  ARGOCD_ENV_RELEASE_NAME can not get，makes
```
      resources:
      - group: ""
        kind: Secret
        message: namespace default is not permitted in project 'project'
        name: release-name-postgresql
        namespace: default
        status: SyncFailed
        syncPhase: Sync
        version: v1
      - group: ""
        kind: Service
        message: namespace default is not permitted in project 'project'
        name: release-name-postgresql-hl
        namespace: default
        status: SyncFailed
        syncPhase: Sync
        version: v1
      - group: ""
        kind: Service
        message: namespace default is not permitted in project 'project'
        name: release-name-postgresql
        namespace: default
        status: SyncFailed
        syncPhase: Sync
        version: v1
      - group: apps
        kind: StatefulSet
        message: namespace default is not permitted in project 'project'
        name: release-name-postgresql
        namespace: default
        status: SyncFailed
        syncPhase: Sync
``` 

the name space is demo I set in the env.

**To Reproduce**
secret/helm-secrets/my-plugin-config.yaml

kubectl apply -f my-plugin-config.yaml -n argocd 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-secrets
    spec:
      version: v1.0
      init:   
        command: ["/bin/sh", "-c"] 
        args: ["gpg --import /home/argocd/gpg/key.asc"] # is mounted as a kube secret
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helm secrets template ${ARGOCD_ENV_HELM_OPTS} ${ARGOCD_ENV_RELEASE_NAME} ."]
      discover:
        fileName: "./helm-secrets"
```

```
kubectl create cm -n argocd gpg-pub-key --from-file=key.asc=key.asc
```

patch.yaml

kubectl patch -n argocd  deploy argocd-repo-server --patch "$(cat patch.yaml)"

```
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /home/argocd/.gnupg
              name: gnu
            - mountPath: /home/argocd/gpg/key.asc
              subPath: key.asc
              name: gpg-pub-key
        - name: my-plugin
          command: [/var/run/argocd/argocd-cmp-server] 
          image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: my-plugin-config
            - mountPath: /home/argocd/gpg/key.asc
              subPath: key.asc
              name: gpg-pub-key
            - mountPath: /home/argocd/.gnupg
              name: gnu
            - mountPath: /tmp
              name: cmp-tmp
      volumes:
        - configMap:
            name: my-plugin-config
          name: my-plugin-config
        - configMap:
            name: gpg-pub-key
          name: gpg-pub-key
        - emptyDir: {}
          name: cmp-tmp
        - emptyDir: {}
          name: gnu
```

```
kubectl set image -n argocd deploy argocd-repo-server copyutil=registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7  argocd-repo-server=registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7

```

secret/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

secret/app-helm-secrets.yaml

kubectl apply -f app-helm-secrets.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/secretManager/helm-screts/postgresql
    targetRevision: HEAD 
    plugin:
      #name: helm-secrets
      env:
        - name: HELM_OPTS
          value: "-f secret.yaml -n demo"
        - name: RELEASE_NAME
          value: "postgresql"
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```

```

[h](https://faun.pub/handling-kubernetes-secrets-with-argocd-and-sops-650df91de173)

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
