### ISSUE TITLE
ArgoCD 2.6.7 MultiSource: Auto-Sync not updating Helm hooks after upgrade from 2.5.*

### ISSUE THREAD

**Issue by OpsMaya** [argoproj/argo-cd#13295]
Checklist:

* [V] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [V] I've included steps to reproduce the bug.
* [V] I've pasted the output of `argocd version`.

**Describe the bug**

I recently upgraded ArgoCD from version 2.5.* to 2.6.6 and encountered an issue with the Auto-Sync feature. I am using the app-of-apps pattern with 75 applications using multi-source feature, and everything is working great except for one problem.

When a Helm chart has resources with hooks (e.g., jobs, external secrets) and the hooks are changed (e.g., updating the image tag of the job), the hooks are not updated during the Auto-Sync phase. However, the hooks are updated when the Sync button is manually pressed in the UI.

I have tested this issue multiple times, and it appears that only the Deployment resource is updated during the Auto-Sync phase, but not the hooks. The image tag of the main application (Deployment) is the same as the image for the migrationJob, and while the Deployment is updated, the migrationJob is not.

I am not sure if this issue is related to Helm or ArgoCD. Is anyone else experiencing this problem?

**To Reproduce**

1.  Upgrade ArgoCD from 2.5.* to 2.6.6.
2. Use app-of-apps pattern with Helm charts containing resources with hooks (e.g., jobs, external secrets).
3. Change the hooks (e.g., update the image tag of a job).
4. Observe that the hooks are not updated during the Auto-Sync phase but are updated when pressing Sync manually in the UI.

**Expected behavior**

The hooks should be updated during the Auto-Sync phase, just like they are when the Sync button is manually pressed in the UI.

**Version**

```shell
argocd: v2.6.7+5bcd846.dirty
  BuildDate: 2023-03-23T17:23:10Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.7+5bcd846.dirty
  BuildDate: 2023-03-23T17:23:10Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.9.4+gdbc6d8e
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Cant find any specific logs about that.
```

**Comment by OpsMaya** [comment]
Just tested
https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.0-rc1/manifests/install.yaml
And still when we have multisource of

OCI Registry + vlauesFiles with ref from source2
Git Repository
ArgoCD application manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migration-test
  namespace: argocd
spec:
  project: company
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'ghcr.io/companyio/charts'
      targetRevision: 0.1.1-migration-chart
      chart: migration-test
      helm:
        valueFiles:
          - $ops/gitops/envs/local1/core/migration-test/values.yaml
    - repoURL: https://github.com/companyio/ops.git
      targetRevision: master
      ref: ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
```

The application has
<img width="342" alt="image" src="https://user-images.githubusercontent.com/110965062/233396476-428f2621-f054-4d7f-a189-83dde964a2e2.png">

The job.yaml has PreSync hooks
And the job.yaml using the same tag as the deployment.yaml (Same key in values.yaml)

Meaning when we change the deployment image to except that the job and the deployment will be deployed and the job should go first.
It's not happening unfortunately
And I think its happening only when using an OCI registry, so if I'm using a Repository-based Helm chart instead of a registry its seems to work as excepted
