### ISSUE TITLE
Ability to configure git credentials at a domain level

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1332]
Currently, each git repository in Argo CD needs to be configured with individual credentials. In other words, if I have both `https://github.com/my-org/repo-aaa` and `https://github.com/my-org/repo-bbb`, then there needs to be two entries in the Argo CD config and reference credentials for both. Often times, this configuration is too granular since most of the time, it is the same credentials to access multiple repos in the same domain.

The proposal is to have git authentication be done more like how it is done on a laptop, where credentials are configured per an entire domain name. For example instead of having credentials for: `https://github.com/my-org/repo-aaa`, we would support supplying credentials for: `https://github.com/my-org`, or `https://github.com`.

We still need to support granular, repo-specific credentials, but often-times, single credentials for an entire domain is good enough. To support both cases, when attempting to locate credentials for a repo, we would iterate the repo list and match the deepest match for the repo.

For example, consider the following repo configuration:
```
data:
  repositories: |
    - url: https://github.com
      passwordSecret:
        name: my-github-secret
        key: password
      usernameSecret:
        name: my-github-secret
        key: username

    - url: https://github.com/my-org/repo-aaa
      passwordSecret:
        name: aaa-secret
        key: password
      usernameSecret:
        name: bbb-secret
        key: username
 ```

An application which is retrieving manifests for `https://github.com/my-org/repo-aaa`, would use credentials contained in `aaa-secret`. But an application which is retrieving manifests for `https://github.com/my-org/repo-bbb` would use the credentials in `my-github-secret`.
