### ISSUE TITLE
Wrong data type in `ExecProviderConfig`

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [argoproj/argo-cd#13346]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `ExecProviderConfig` type used to parse the `execProviderConfig` object in a cluster secret has the wrong data type for `Env`. In https://github.com/argoproj/argo-cd/blob/3de96ca51c85c27fb2f1ef5b0b7f9c7124d26f7c/pkg/apis/application/v1alpha1/types.go#L1367-L1384 `Env` has the data type `map[string]string` but the correct data type is `[{name: string, value: string}]`, as is evident going to the link above the function. This causes the `kubeconfig` which works in my local system to have parse failures in Argo CD.

**To Reproduce**

Create a secret as below with the below:

```yaml
apiVersion: v1
stringData:
    config: |-
    {
        "execProviderConfig": {
            "command": "aws",
            "args": [
                "eks",
                "get-token",
                "--cluster-name",
                "NAME",
                "--region",
                "REGION",
                "--output",
                "json",
                "--role",
                "ROLE"
            ],
            "env": [
                {
                    "name": "AWS_ACCESS_KEY_ID",
                    "value": "KEY"
                },
                {
                    "name": "AWS_SECRET_ACCESS_KEY",
                    "value": "SECRET"
                }
            ],
            "apiVersion": "client.authentication.k8s.io/v1beta1",
            "installHint": "install AWS CLI"
        },
        "tlsClientConfig": {
            "insecure": true
        }
    }
    name: NAME
    server: SERVER
kind: Secret
metadata:
    labels:
        argocd.argoproj.io/secret-type: cluster
    name: cluster-name
    namespace: argocd
type: Opaque
```

Most of the values in CAPITALS shouldn't matter as the parse will fail with `could not unmarshal cluster secret` error.

**Expected behavior**

The structure of env is

```json
env: [
  {
    "name": "NAME",
    "value": "VALUE"
  }
]
```
and not 
```json
env:  {
   "NAME": "VALUE"
}
```

**Version**

```shell
argocd: v2.5.16+84fbc93
  BuildDate: 2023-03-23T15:29:04Z
  GitCommit: 84fbc930161f29ebe45a7da3b2e81ee256d119c2
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.5.16+84fbc93
  BuildDate: 2023-03-23T14:57:24Z
  GitCommit: 84fbc930161f29ebe45a7da3b2e81ee256d119c2
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```
