### ISSUE TITLE
rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed timeout after 1m30s

### ISSUE THREAD

**Issue by lknite** [argoproj/argo-cd#13356]
Checklist:
* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
To deploy prometheus-operator I've always deployed the operator helm chart without crds, and then with a second chart install the crds using a directory recurse pointing to the right path / git repo.  This has always worked in the past but with a new cluster and new installation of argocd getting an error.

**To Reproduce**
```
$ cat applicationset.yaml 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-prometheus-crds
  namespace: argocd
spec:
  generators:
  - clusters: # Automatically use all clusters defined within Argo CD
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          addons-prometheus: "true"

  template:
    metadata:
      name: '{{name}}-prometheus-crds'
    spec:
      project: addons
      source:
        repoURL: https://github.com/bitnami/charts.git
        path: bitnami/kube-prometheus/crds
        targetRevision: HEAD
        #targetRevision: 6.8.5

        directory:
          recurse: true

      destination:
        server: '{{server}}'
        namespace: prometheus

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - Replace=true

        automated:
          selfHeal: true
          prune: true
```

**Expected behavior**
All crds at the specified location applied.

**Version**
kubernetes v1.25.8
argocd v2.6.7+5bcd846

```shell
$ argocd version
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T15:24:49Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Comment by lknite** [comment]
Switched to using:
```
      syncPolicy:
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
        - Replace=true

        automated:
          selfHeal: true
          prune: true

      ignoreDifferences:
      - group: monitoring.coreos.com
        kind: ServiceMonitor
        jqPathExpressions:
        - .metadata.annotations
```
