### ISSUE TITLE
through cmd testuser have permission,but in ui it is rejected

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-cd#13379]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**
## 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  accounts.testuser: apiKey,login
  policy.default: role:readonly
  policy.csv: |
    p, role:org-test, applications, *, */*, allow
    p, role:org-test, projects, *, *, allow

    g, testuser, role:org-test
```

```
[root@mycompany ~]# argocd account list
NAME      ENABLED  CAPABILITIES
admin     true     login
testuser  true     apiKey, login

[root@mycompany ~]# argocd account update-password --account testuser --new-password 12345678 --current-password qu2-5RQk0qIOBSAW
Password updated
```

用testuser登入ui

![image-20230430124954152](https://user-images.githubusercontent.com/31508490/235336544-57bb1112-c7c6-4bac-87ec-729613477229.png)

```
[root@mycompany configuration]# argocd admin settings rbac can testuser create project  --policy-file policy.csv 
Yes

[root@mycompany configuration]# cat policy.csv 
    p, role:org-test, applications, *, */*, allow
    p, role:org-test, projects, *, *, allow
    g, testuser, role:org-test
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
