### ISSUE TITLE
Manifest generation error: multiple application sources defined: Helm,Plugin

### ISSUE THREAD

**Issue by talitz** [argoproj/argo-cd#13413]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Hi, when using Helm for declaring values files along Plugin for secrets integration on an Application object, I receive the following error:
rpc error: code = Unknown desc = Manifest generation error (cached): multiple application sources defined: Helm,Plugin

**To Reproduce**

```
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      project: "argo-rollouts"
      source:
        repoURL: https://git.info/scm/devops/argo-projects.git
        targetRevision: HEAD
        path: 'argocd-repos/argo-rollouts/development'
        plugin:
          name: argocd-vault-plugin
          env:
            - name: helm_args
              value: -f values.yaml -n saas-argo-rollouts
        helm:
          valueFiles: []
```
It makes sense to use both if I need the plugin for secrets integration...

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
