### ISSUE TITLE
No instructions for private repositry

### ISSUE THREAD

**Issue by garganubhav** [argoproj/argo-cd#1342]
Hi, I am trying to setup argocd for my private repo, but it gives me this error - InvalidSpecError: No credentials available for source repository and repository is not publicly accessible: authentication required 
I tried using https://github.com/argoproj/argo-cd/blob/master/docs/declarative-setup.md#repositories, but with no sucess.
Is there a way to give argocd github oauth token for access? Or any other method?
Thank you!

**Comment by mjasion** [comment]
I have similar issue with selfhosted Gitlab with private repository :(

My config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - insecureIgnoreHostKey: true
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: repo-argocd-get-started-1347344391
      url: ssh://git@gitlab.example.com/marcin.jasion/argocd-get-started.git
      usernameSecret:
        key: username
        name: repo-argocd-get-started-1347344391
```

And Log from `argocd-server` pod:
```time="2019-04-02T15:38:22Z" level=info msg="received unary call /application.ApplicationService/Create" grpc.method=Create grpc.request.claims="{\"iat\":1554217511,\"iss\":\"argocd\",\"nbf\":1554217511,\"sub\":\"admin\"}" grpc.request.content="application:<TypeMeta:<kind:\"\" apiVersion:\"\" > metadata:<name:\"argo-get-started\" generateName:\"\" namespace:\"\" selfLink:\"\" uid:\"\" resourceVersion:\"\" generation:0 creationTimestamp:<0001-01-01T00:00:00Z> clusterName:\"\" > spec:<source:<repoURL:\"git@gitlab.example.com:marcin.jasion/argocd-get-started.git\" path:\"/\" targetRevision:\"master\" directory:<recurse:false jsonnet:<> > > destination:<server:\"https://kubernetes.default.svc\" namespace:\"default\" > project:\"default\" syncPolicy:<automated:<prune:true > > > status:<sync:<status:\"\" comparedTo:<source:<repoURL:\"\" path:\"\" targetRevision:\"\" > destination:<server:\"\" namespace:\"\" > > revision:\"\" > health:<status:\"\" message:\"\" > reconciledAt:<0001-01-01T00:00:00Z> observedAt:<0001-01-01T00:00:00Z> sourceType:\"\" > > " grpc.service=application.ApplicationService grpc.start_time="2019-04-02T15:38:22Z" span.kind=server system=grpc
time="2019-04-02T15:38:22Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: No credentials available for source repository and repository is not publicly accessible: error creating SSH agent: \"SSH agent requested but SSH_AUTH_SOCK not-specified\"" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2019-04-02T15:38:22Z" grpc.time_ms=10.44 span.kind=server system=grpc
```

I am using minikube with kubernetes 1.14.0

**Comment by alexec** [comment]
Can you please tell me if you're using Github? Gitlab?

**Comment by twalla** [comment]
Assuming you're trying to access a private GitHub repository, the following worked for me to authenticate over HTTPS:

Generate a personal access token, ensure it has the proper repository scopes and the user generating the token has access to the repo you want to use. [You can generate a new token here.](https://github.com/settings/tokens/new)

Use the newly generated token and your username to authenticate via HTTPS when configuring a new repo - a declarative configuration would look like this:

secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-credentials
type: Opaque
data:
  username: YOUR_GITHUB_USERNAME
  password: YOUR_GENERATED_TOKEN
```
configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-repo-config
data:
  repositories: |
    - url: https://github.com/YOUR_GITHUB_ORG/YOUR_PRIVATE_REPO
      passwordSecret:
        name: argocd-repo-credentials
        key: password
      usernameSecret:
        name: argocd-repo-credentials
        key: username
```
