### ISSUE TITLE
change helm value extraContainers from array to map

### ISSUE THREAD

**Issue by zswanson** [argoproj/argo-cd#13433]
# Summary
`extraContainers` is difficult to manage across multiple values.yaml files for helm users because the array prevents merging, so that specific values files can override a setting. For example being able to override the resource requests for production vs dev clusters. With the array we have to specify the entire container definition again to make the change (or just accept defining them individually in every values file). With a map we can directly override particular settings. 

This pattern is useful for users that 'layer' multiple values files based on things like stage, region, individual cluster, etc. In a helmfile deploy pattern a user might be selecting values files based on these conditions like so, where the values are applied in order of Default --> global --> env --> cluster :
```
/app1
  helmfile.yaml
  global-values.yaml
  env-prod-values.yaml
  env-dev-values.yaml
  cluster-c1-prod-region1.yaml
  cluster-c2-prod-region2.yaml
``` 

# Motivation

Example: overriding settings for a CMP sidecar container in the reposerver.

```yaml
reposerver:
  extraContainers:
    - name: cmp
      command: [/var/run/argocd/argocd-cmp-server]
      image: mycustomer-cmp-sidecar:latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 256Mi
```

Because this is an array I cannot add an overriding definition of the sidecar unless I completely redefine it. The overriding snippet would squash in the list and be incomplete/invalid. For example the following would break the container definition.

```yaml
reposerver:
  extraContainers:
    - name: cmp
      resources:
        limits:
          cpu: 2
```

However with a map this is possible.

```yaml
reposerver:
  extraContainers:
   cmpSidecar:
      name: cmp
      command: [/var/run/argocd/argocd-cmp-server]
      image: mycustomer-cmp-sidecar:latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 250m
```

Now with the map I can directly update individual fields in an overlaying values.yaml

# Proposal

Redefine the helm values for extraContainers to a map `{}` rather than an array, and adjust the iteration method in the templating as required.
