### ISSUE TITLE
argocd-server pod stuck in CrashLoopBackOff during 2.6.7 - 2.7.1 update

### ISSUE THREAD

**Issue by fdzuJ** [argoproj/argo-cd#13430]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I've got self managed argo cd installed with kustomize. During update from 2.6.7 to 2.7.1 argocd-server pod stuck in CrashLoopBackOff.

**To Reproduce**

kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.1/manifests/ha/install.yaml

## changes to config maps
patchesStrategicMerge:
  - ./overlays/production/argocd-cmd-params-cm.yaml
  - ./overlays/production/argocd-cm.yaml

namespace: argocd
```

./overlays/production/argocd-cmd-params-cm.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
```

./overlays/production/argocd-cm.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
```

**Expected behavior**

argocd-server started

**Version**

healthy pod:
```shell
argocd-server: v2.6.7+5bcd846
```

**Logs**

```
Error: unknown command "/usr/local/bin/argocd-server" for "argocd-server"
Run 'argocd-server --help' for usage.
```

Resulting pod manifest contains following (which i guess is the source of error):
```yaml
spec:
  containers:
    - args:
        - /usr/local/bin/argocd-server
      command:
        - argocd-server
        - '--redis'
        - 'argocd-redis-ha-haproxy:6379'
```

**Comment by drewboswell** [comment]
I had the same issue, it's related to this commit: https://github.com/argoproj/argo-cd/commit/c2e0026de16c2622ddf4c95d0311c321ebd51f3a 

They have changed the default entrypoint method, and now you need to supply this information as args. You block above should look like this now:

```yaml
spec:
  containers:
    - args:
        - /usr/local/bin/argocd-server
        - '--redis'
        - 'argocd-redis-ha-haproxy:6379'
```
