### ISSUE TITLE
git fetch origin --tags --force' failed: fatal: unable to access 'xxxx': Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by papanito** [argoproj/argo-cd#1344]
We are using internal Bitbucket server for the git repos, which we want to add to argo-cd. Bitbucket servers the repo as https with self-signed certificates. I've added the certificates as secrets to the deployment. I can successfully add the repo to argocd.

However when I get to create an application I get the following error
```bash
rpc error: 
code = Internal 
desc = Failed to fetch git repo: 'git fetch origin --tags --force' failed: fatal: unable to access 'https://bitbucket.intra/scm/test/kube/': Problem with the SSL CA cert (path? access rights?)" grpc.code=Internal grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2019-04-01T06:17:11Z" grpc.time_ms=162.943 span.kind=server system=grpc
```

`argocd-repo-server` log:

```go
time="2019-04-01T09:19:37Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = Failed to fetch git repo: 'git fetch origin --tags --force' failed: fatal: unable to access 'https://bitbucket.intra/scm/test/kube/': Problem with the SSL CA cert (path? access rights?)" grpc.code=Internal grpc.method=GetAppDetails grpc.service=repository.RepoServerService grpc.start_time="2019-04-01T09:19:37Z" grpc.time_ms=140.751 span.kind=server system=grpc
```

**Steps to reproduce**

1. Add certificates as secrets

   ```bash
   kubectl apply -f selfsignedcert.yml
   ```

1. Download [`install.yaml`](https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml) and mount the certificates something like

   ```yml
   ...
   # add this to all containers
   volumeMounts:
   - mountPath: /etc/ssl/certs/selfsignedcert.pem
     name: selfsignedcerts
   ...
   volumes:
   - name: selfsignedcert
     secret:
       defaultMode: 420
       secretName: selfsignedcerts
   ```

1. Install argo-cd

   ```bash
   kubectl create namespace argocd
   kubectl apply -n argocd -f install.yaml
   ```

The `selfsignedcert.yml` looks like

```yml
apiVersion: v1
kind: Secret
metadata:
  name: selfsignedcerts
  namespace: argocd
data:
  RootCAG3.crt: |
    ...
  SubordinateCA3.crt: |
    ...
  NOPRootCAG3.crt: |
    ....
  NOPSubordinateCAG3.crt: |
    ....
  RootCAG2.crt: |
    ....
  SubordinateCA2.crt: |
```

The repo I have added is "publicly" available i.e. credentials should not be required.

**Comment by papanito** [comment]
My secret contains various certificates and thus mapping it the way described above ensures that only my certificates are available - thus all default certs are "removed". On the other hand when mapping with `subpath` I have all defaults certs plus mine available. With this the issue described above does not occur.
   ```yml
   ...
   # add this to all containers
   volumeMounts:
	- mountPath: /etc/ssl/certs/RootCAG3.crt
	  subPath: RootCAG3.crt
	  name: selfsignedcerts
	- mountPath: /etc/ssl/certs/SubordinateCA3.crt
	  subPath: SubordinateCA3.crt
	  name: selfsignedcerts	
	- mountPath: /etc/ssl/certs/NOPRootCAG3.crt
	  subPath: NOPRootCAG3.crt
	  name: selfsignedcerts
	- mountPath: /etc/ssl/certs/NOPSubordinateCAG3.crt
	  subPath: NOPSubordinateCAG3.crt
	  name: selfsignedcerts	
	- mountPath: /etc/ssl/certs/RootCAG2.crt
	  subPath: RootCAG2.crt
	  name: selfsignedcerts
	- mountPath: /etc/ssl/certs/SubordinateCA2.crt
	  subPath: SubordinateCA2.crt
	  name: selfsignedcerts
   ...
   volumes:
   - name: selfsignedcerts
     secret:
       defaultMode: 420
       secretName: selfsignedcerts
   ```
