### ISSUE TITLE
Argo-cd sync wave overrides cronjobs run time

### ISSUE THREAD

**Issue by angewcy** [argoproj/argo-cd#13444]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**
When new and the existing completed cronjobs were updated with new values, the cronjobs were triggered to run immediately instead of running according to the cronjobs' schedules. The cronjob resources were annotated with sync-wave: 1, service account sync-wave: 0, vpa sync-options: SkipDryRunOnMissingResource=true

**To Reproduce**

The first time when the cronjob was deployed and synced, the triggered run time was correct. Then when more cronjobs were added (Same sync wave number), all the cronjobs triggered to run immediately.
**Expected behavior**
Expect the cronjobs running time should be according to the jobs' crontabs without the need to delete and recreate the resources.

**Version**

```shell
v2.0.5+4c94d88
```

**Settings**

```
---
# Source: dbcopy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: dbcopy-serviceaccount
  labels:
    helm.sh/chart: dbcopy-1.0.0
    app.kubernetes.io/name: dbcopy
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: dbcopy-stream-stg-1
  namespace: vn-data
spec:
  suspend: true
  schedule: "0 15 * *  MON-SAT"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: dbcopy-1.0.0
            app.kubernetes.io/release_name: "test"
            app.kubernetes.io/version: "1.16.0"
            app.kubernetes.io/managed-by: "Helm"
          annotations:
            {}
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 2000
          containers:
          - name: dbcopy
            image: db-copy
            imagePullPolicy: "Always"
            env:
              - name: ENV
                value: "STG"
              - name: AWS_REGION
                value: "ap-southeast-1"
              - name: TZ
                value: "UTC"
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
              requests:
                cpu: "1"
                memory: "2Gi"
            command:
              - /bin/sh
              - -c 
              -     date;./scripts-STG/stream-01.sh; sleep 86400
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: dbcopy-stream-stg-2
  namespace: vn-data
spec:
  suspend: true
  schedule: "0 15 * *  MON-SAT"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: dbcopy-1.0.0
            app.kubernetes.io/release_name: "test"
            app.kubernetes.io/version: "1.16.0"
            app.kubernetes.io/managed-by: "Helm"
          annotations:
            {}
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 2000
          containers:
          - name: dbcopy
            image: db-copy
            imagePullPolicy: "Always"
            env:
              - name: ENV
                value: "STG"
              - name: AWS_REGION
                value: "ap-southeast-1"
              - name: TZ
                value: "UTC"
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
              requests:
                cpu: "1"
                memory: "2Gi"
            command:
              - /bin/sh
              - -c 
              -     date;./scripts-STG/stream-02.sh; sleep 86400
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: dbcopy-stream-stg-3
  namespace: vn-data
spec:
  suspend: true
  schedule: "0 15 * *  MON-SAT"
  # startingDeadlineSeconds: 32400
  # argocd.argoproj.io/hook: PostSync
  # argocd.argoproj.io/hook-delete-policy: HookSucceeded
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: dbcopy-1.0.0
            app.kubernetes.io/release_name: "test"
            app.kubernetes.io/version: "1.16.0"
            app.kubernetes.io/managed-by: "Helm"
          annotations:
            {}
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 2000
          containers:
          - name: dbcopy
            image: db-copy
            imagePullPolicy: "Always"
            env:
              - name: ENV
                value: "STG"
              - name: AWS_REGION
                value: "ap-southeast-1"
              - name: TZ
                value: "UTC"
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
              requests:
                cpu: "1"
                memory: "2Gi"
            command:
              - /bin/sh
              - -c 
              -     date;./scripts-STG/stream-03.sh; sleep 86400
          restartPolicy: Never
---
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: dbcopy-stream-stg-1-vpa
  namespace: vn-data
spec:
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: "batch/v1beta1"
    kind: CronJob
    name: dbcopy-stream-stg-1
---
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: dbcopy-stream-stg-2-vpa
  namespace: vn-data
spec:
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: "batch/v1beta1"
    kind: CronJob
    name: dbcopy-stream-stg-2
---
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: dbcopy-stream-stg-3-vpa
  namespace: vn-data
spec:
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: "batch/v1beta1"
    kind: CronJob
    name: dbcopy-stream-stg-3
```
