### ISSUE TITLE
Support for Projected Volume with a `serviceAccountToken`

### ISSUE THREAD

**Issue by dee-kryvenko** [argoproj/argo-cd#13477]
# Summary

There doesn't seem to be support included for the most basic of things - [Projected Volume with a `serviceAccountToken`](https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken).

# Motivation

OIDC is really awesome and secure, and it allows direct cluster-to-cluster authentication without an intermediary like AWS IAM role or GCP authentication. Tokens issued by the issuer in the cluster A can be directly verified with that issuer in the cluster B.

# Proposal

Implementation is very simple - it is essentially the same as regular in-cluster authentication, except that certificate authority data and endpoint are different, also it may be non-standard path instead of `/var/run/secrets/kubernetes.io/serviceaccount/token` in case my other cluster wants different `aud` claim.

**Comment by Shegox** [comment]
As of today you can use this `execProviderConfig` config to construct a argocd cluster secret, which reads the OIDC token from a file. 

Make sure to update the following values: 
- `server: https://mycluster.example.com` with the URL of your Kubernetes API server
- `/var/run/secrets/tokens/argocd` with the path where your projected service account token is mounted in the `argocd-application-controller` and `argocd-server`
- `"caData": "<base64 caData>"` with the base64 encoded CA certificate of your Kubernetes API server

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: target-cluster
  server: https://mycluster.example.com
  config: |
    {
      "execProviderConfig": {
        "command": "bash",
        "args": [
          "-c",
          "echo -n '{\"apiVersion\":\"client.authentication.k8s.io/v1\",\"kind\":\"ExecCredential\",\"status\":{\"token\":\"'; cat /var/run/secrets/tokens/argocd; echo -n '\"}}'"
          ],
        "apiVersion": "client.authentication.k8s.io/v1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 caData>"
      }
    }
```
