### ISSUE TITLE
ApplicationSet ignores `.spec.source.kustomize.namespace`

### ISSUE THREAD

**Issue by dee-kryvenko** [argoproj/argo-cd#13488]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have a simple base:

```
# standard-user-namespace/kustomization.yaml:
resources:
- namespace.yaml

# standard-user-namespace/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: default
```

Then I have ApplicationSet:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-project
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          # This will skip in-cluster
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-demo-project'
    spec:
      project: demo-project
      source:
        repoURL: https://github.com/foo/bar
        targetRevision: main
        path: standard-user-namespace
        kustomize:
          namespace: demo-project
      destination:
        name: '{{name}}'
        namespace: demo-project
```

ArgoCD keeps namespace name as `default` and the ApplicationSet itself is always Out of Sync - it says that the live manifest does not have `namespace: demo-project`.

On top of that, this project had this:

```
  destinations:
  - namespace: 'demo-project'
    name: '*'
```

So I am not sure why RBAC even allows that.

**To Reproduce**

Just install this simple example from above.

**Expected behavior**

ApplicationSet should create `demo-project` namespace per each cluster that match the selector.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T19:24:14Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.20.3
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Paste any relevant application logs here.
```
