### ISSUE TITLE
ApplicationSet Progressive Sync using multiple NotIn operators selects unintended Applications

### ISSUE THREAD

**Issue by wmgroot** [argoproj/argo-cd#13501]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Using NotIn operators is a common patterns to avoid including the same set of Applications in the same Progressive Sync step in a concise way. Currently, using multiple NotIn operators within the same matchExpression does not behave as it should, leaving extra conflicted Applications in the step with multiple NotIn operators.

https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/
> All matchExpressions must be true for an Application to be selected (multiple expressions match with AND behavior).

**To Reproduce**
```
  - matchExpressions:
    - key: app
      operator: In
      values:
        - app1
    - key: cluster
      operator: In
      values:
        - cluster1
  - matchExpressions:
    - key: app
      operator: In
      values:
        - app1
    - key: cluster
      operator: NotIn
      values:
        - cluster1

  - matchExpressions:
    - key: app
      operator: In
      values:
        - app2
    - key: cluster
      operator: In
      values:
        - cluster1
  - matchExpressions:
    - key: app
      operator: In
      values:
        - app2
    - key: cluster
      operator: NotIn
      values:
        - cluster1

  - matchExpressions:
    - key: app
      operator: NotIn
      values:
        - app1
        - app2
    - key: cluster
      operator: In
      values:
        - cluster1
  - matchExpressions:
    - key: app
      operator: NotIn
      values:
        - app1
        - app2
    - key: cluster
      operator: NotIn
      values:
        - cluster1
```

```
AppSet 'prod-auto-sync-apps' has a invalid matchExpression that selects Application 'app3-cluster1' label twice, in steps 5 and 6
AppSet 'prod-auto-sync-apps' has a invalid matchExpression that selects Application 'app4-cluster1' label twice, in steps 5 and 6
```

**Expected behavior**
`app3-cluster1` and `app4-cluster` should not be included in step 6, because step 6 contains a NotIn expression excluding `cluster1`.
`(NOT IN app1 OR app2) AND (NOT IN cluster1)` should not select an Application labeled as `cluster1`
