### ISSUE TITLE
Delete=false not working for StatefulSets with volumeClaimTemplates

### ISSUE THREAD

**Issue by ddevaal** [argoproj/argo-cd#13503]
I have added the `Delete=false` sync-option but  the PVC's are still being deleted when I remove the ArgoCD application via the webUI.  How do I prevent this from happening?

```
volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/instance: rabbitmq
      annotations:
        argocd.argoproj.io/sync-options: Prune=false,Delete=false
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "8Gi"
```

ArgoCD: v2.7.1

**Comment by ddevaal** [comment]
It's because the PVC is not defined in git but there is an app.kubernetes.io/instance: rabbitmq label on the resource so ArgoCD decides to prune the resource.

**Comment by ddevaal** [comment]
It seems I was mistaken. I'm already using: `application.instanceLabelKey: argocd.argoproj.io/instance`. I've tried adding `argocd.argoproj.io/sync-options: Prune=false,Delete=false` to various places like: `StatefulSet.spec.template.metadata.annotations` or `StatefulSet.spec.volumeClaimTemplates.metadata.annotations` but the PVC's always get deleted. What am I missing here?

**Comment by chary1112004** [comment]
@ddevaal I have tested by add annotation for all objects of mongodb then it works (beside pvc is not deleted, statefulset and other kubernetes objects are not deleted too)

- We use bitnami mongodb helm chart. Adding value then it works
```
mongodb:
  ## @param commonAnnotations Common annotations to add to all Mongo resources (sub-charts are not considered). Evaluated as a template
  ##
  commonAnnotations:
    argocd.argoproj.io/sync-options: Delete=false 
```

- Kubernetes object with annotation
![image](https://github.com/argoproj/argo-cd/assets/76929085/57cbe69d-4a31-47e8-ab92-adfadb56e6e5)

- I test with argocd v2.7.3

Regards
