### ISSUE TITLE
Application fails to synchronize - error: plugin sidecar failed. error generating manifests in cmp

### ISSUE THREAD

**Issue by jgagnon44** [argoproj/argo-cd#13539]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

We have a Kubernetes cluster where we use ArgoCD to manage and synchronize updates. We recently upgraded ArgoCD to version v2.5.15 and also did the work to switch from using plugins to sidecars. Everything appears to be in good condition, with one exception. An application fails to synchronize with the message:

```
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c "helm dependency build\n"` failed exit status 1: Error: no cached repository for helm-manager-ad0ea17f2a357d9a8e390ad4d1a7baf91c56ff6891dd88e9dd273134a29256c1 found. (try 'helm repo update'): open /home/argocd/.cache/helm/repository/helm-manager-ad0ea17f2a357d9a8e390ad4d1a7baf91c56ff6891dd88e9dd273134a29256c1-index.yaml: no such file or directory
```

The application is deployed via a Helm chart. The chart does not have any external dependencies.

**To Reproduce**

Not sure what to tell you here. As mentioned above, it is an internal application that is failing to synchronize with ArgoCD. This is happening within our company internal network.

**Expected behavior**

For the application to be successfully synchronized when updates are committed to our GitLab repository being monitored by ArgoCD.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.

argocd: v2.5.15+64a7bb8
  BuildDate: 2023-03-16T22:34:19Z
  GitCommit: 64a7bb8f02238777ec45752d7655dba505eed889
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

I do not know if it would be helpful, but I am including what I think are relevant files.

The main Chart.yaml:

```
apiVersion: v2
type: application
name: prometheus-metrics-ref
description: Provides an HTML page listing all Prometheus metrics and rules.
version: 1.0.1
```

and the associated values.yaml:

```
application:
  image:
    repository: harbor.hulk.beast-code.com/phactory-images/prometheus-metrics-and-rules
    tag: latest
  env:
    port: 8080
    prometheusApiUrl: ""
  ingress:
    domain: hulk.beast-code.com
    subdomain: ""
  resources:
    requests:
      cpu: 125m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
```

A K8s cluster-specific Chart.yaml to deploy the app to the cluster:

```
apiVersion: v2
name: prometheus-metrics-ref-argocd
description: Prometheus metrics and rules reference app.
type: application
version: 1.0.0

dependencies:
  - name: prometheus-metrics-ref
    version: 1.0.1
    repository: https://harbor.hulk.beast-code.com/chartrepo/library
```

and its values.yaml:

```
prometheus-metrics-ref:
  nameOverride: arc-prometheus-metrics-ref
  application:
    env:
      prometheusApiUrl: https://prometheus.nnpi.beast-code.com/api/v1
    ingress:
      domain: nnpi.beast-code.com
      subdomain: ""
```

Our cmp-plugin:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      init:
        command:
          - sh
          - "-c"
          - |
            helm dependency build
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_helm_args} . |
            argocd-vault-plugin generate -
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
```
