### ISSUE TITLE
HTTP 500 when attempting to fetch links

### ISSUE THREAD

**Issue by tobiasbrodersen** [argoproj/argo-cd#13545]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Problem did no occur until we upgraded our ArgoCD deployment from 2.6.7 to 2.7.1

When opening app details or editing a resource directly from the UI, a HTTP 500 is returned when my browser tries to visit https://argocd.com/api/v1/applications/myapp/links - this error also spawns pop-ups in the bottom right corner (see screenshots)

**To Reproduce**

1. Deploy ArgoCD v2.7.1 without any Deep Links
2. Add a Cluster by defying a secret (we use GKE and server: https://1.2.3.4)
3. Create AppProject
```yaml
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: ops
    server: '*'
  - namespace: service
    server: '*'
```
4. Deploy App in above Project
5. Visit app details of app in UI

**Expected behavior**

If intended behaviour, a non 500 status message and brief explanation

**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/31192146/f4e85437-b524-48f8-9a46-eb103424292b)
![image](https://github.com/argoproj/argo-cd/assets/31192146/e3b23564-6d1d-441f-8682-9f67bb1bbf49)

**Version**

```shell
argocd-server: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T16:35:40Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1.
```

**Logs**
```
[argocd-server-544f8c9564-bgfhz] time="2023-05-11T10:18:13Z" level=error msg="finished unary call with code Unknown" error="error getting destination cluster" grpc.code=Unknown grpc.method=ListLinks grpc.service=application.ApplicationService grpc.start_time="2023-05-11T10:18:13Z" grpc.time_ms=20.904 span.kind=server system=grpc
```

**Comment by tobiasbrodersen** [comment]
Adding a name field to all AppProject destinations with asterisk value seems to have fixed the issue, I'm not 100% sure why yet. I'll try dig a bit through the code.
```
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: ops
    server: '*'
  - name: '*'
    namespace: service
    server: '*'
```
