### ISSUE TITLE
307 Redirect Loop via server.insecure, but not via --insecure

### ISSUE THREAD

**Issue by SlothCroissant** [argoproj/argo-cd#13578]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Doc ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22

> The API server should be run with TLS disabled. Edit the argocd-server deployment to add the --insecure flag to the argocd-server command or set server.insecure: "true" in the argocd-cmd-params-cm ConfigMap [as described here](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/additional-configuration-method/).

When using `server.insecure: "true"` in `argocd-cmd-params-cm` via ConfigMap patch, `argocd-server` will throw a HTTP 307 redirect if you access via HTTP/80 via reverse proxy, as it unexpectedly HTTP > HTTPS redirects you. 

When you exec into the `argocd-server` Deployment/Pod, the Env var `ARGOCD_SERVER_INSECURE`, which is supposed to be populated via the [v2.7.1 install.yml](https://github.com/argoproj/argo-cd/blob/v2.7.1/manifests/install.yaml#LL17636C1-L17642C29):

``` yaml
# https://github.com/argoproj/argo-cd/blob/5e543518dbdb5384fa61c938ce3e045b4c5be325/manifests/install.yaml#LL17636C1-L17642C29
        - name: ARGOCD_SERVER_INSECURE
          valueFrom:
            configMapKeyRef:
              key: server.insecure
              name: argocd-cmd-params-cm
              optional: true
```      

If you access via kubectl port-forward or similar, you'll notice an HTTP>HTTPS redirect, further indicating that the server isn't running in insecure mode.

**To Reproduce**

1. Deploy `argocd` via yml manifest:

``` bash
kubectl create ns argocd || true
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.1/manifests/install.yaml
```

2. Setup your repo/secrets, etc to be able to deploy apps from declarative.
3. Deploy "app of apps" via:

``` yml
# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.1/manifests/install.yaml
- secrets.yml # used for repo secret - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories

patches:
  - path: patch-argocd-cm.yml
  - path: patch-argocd-rbac-cm.yml
  - path: patch-argocd-cmd-params-cm.yml
#  - path: patch-argocd-insecure.yml
#     target:
#       kind: Deployment
```

``` yml
# patch-argocd-cm.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.url.com
  kustomize.buildOptions: --enable-helm
  dex.config: |
      connectors:
      - config:
          issuer: https://sso.url.com/application/o/argocd/
          clientID: redacted
          clientSecret: redacted
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
            - groups
        name: authentik
        type: oidc
        id: authentik
```

``` yml
# patch-argocd-rbac-cm.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, authentik Admins, role:admin
```

``` yml
# patch-argocd-cmd-params-cm.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
```

``` yml
# patch-argocd-insecure.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        args:
        - /usr/local/bin/argocd-server
        - --insecure
```

And my IngressRoute (via Traefik CRDs), for ref. Nothing special, pretty much ripped straight out of the docs:

``` yml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.url.com`)
      kind: Rule
      priority: 10
      services:
        - name: argocd-server
          port: http
    - match: Host(`argocd.url.com`) && Headers(`Content-Type`, `application/grpc`)
      kind: Rule
      priority: 11
      services:
        - name: argocd-server
          port: http
          scheme: h2c
  tls: {}
```

**Expected behavior**

When using `server.insecure: "true"`, argocd should serve itself on HTTP, and *not* redirect you to HTTPS (leading to a 307 redirect loop when accessing via an ingress)

**Workaround**

If you deploy the kustomization.yml as follows (same ymls as above), it works a charm:

``` yml
# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.1/manifests/install.yaml
- secrets.yml # used for repo secret - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories

patches:
  - path: patch-argocd-cm.yml
  - path: patch-argocd-rbac-cm.yml
#  - path: patch-argocd-cmd-params-cm.yml
  - path: patch-argocd-insecure.yml
     target:
       kind: Deployment
```

**Version**

```shell
argocd: v2.6.7+5bcd846.dirty
  BuildDate: 2023-03-23T17:23:10Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.7+5bcd846.dirty
  BuildDate: 2023-03-23T17:23:10Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.11.3+g66a969e
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

Not sure what is relevant here, please advise what I could provide to assist!
