### ISSUE TITLE
Container logs in UI do not always match the displayed container name

### ISSUE THREAD

**Issue by shawntoffel** [argoproj/argo-cd#13572]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When there are multiple containers the displayed container logs do not always match the container name. It seems as if the container name defaults to the first in the list while the displayed logs persist between viewings. 

Note that the dropdown does work, so this seems to be different from #13410. 

**To Reproduce**

1. Create a new app which has a pod manifest with multiple containers:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
    - name: '1'
      image: alpine:latest
      command:
        - /bin/sh
      args:
        - '-c'
        - 'while :; do echo "I am container 1"; sleep 5; done'
    - name: '2'
      image: alpine:latest
      command:
        - /bin/sh
      args:
        - '-c'
        - 'while :; do echo "I am container 2"; sleep 5; done'
```

2. In the Argo UI, click on the Pod to view the logs. Sometimes they are already mismatched here. 
3. Select container 2 from the name dropdown and see container 2's logs. 
4. Click the `X` or click out of the pod view.
5. Click on the pod to view the logs again. See container 1's name and container 2's logs.

**Expected behavior**

The container logs should match the container name by default. 

**Screenshots**
![Screenshot 2023-05-12 101239](https://github.com/argoproj/argo-cd/assets/2343437/0d9429a1-21a1-434e-bc31-3b677fd6ada0)

**Version**

```shell
{
    "Version": "v2.7.2+cbee7e6.dirty",
    "BuildDate": "2023-05-12T13:43:26Z",
    "GitCommit": "cbee7e6011407ed2d1066c482db74e97e0cc6bdb",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```
