### ISSUE TITLE
GKE 1.27: ComparisonError for CSIDriver .spec.seLinuxMount: field not declared in schema

### ISSUE THREAD

**Issue by kaiburjack** [argoproj/argo-cd#13585]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to Kubernetes/GKE 1.27, we get a sync error from Argo CD v2.7.2+cbee7e6 that a field ([which became alpha in Kubernetes 1.25](https://kubernetes-csi.github.io/docs/csi-driver-object.html#what-fields-does-the-csidriver-object-have) but apparently now is stable/graduated in Kubernetes 1.27 and being set by the API server after applying a manifest which _did not_ have this field in it) is not recognized:
```
ComparisonError: error calculating structured merge diff: error building typed value from live resource: .spec.seLinuxMount: field not declared in schema.
```

An `ignoreDifferences` on the respective Argo CD Application *does* solve this issue:
```yaml
ignoreDifferences:
- group: storage.k8s.io
  jsonPointers:
  - /spec/seLinuxMount
  kind: CSIDriver
  name: nfs.csi.k8s.io
```
However it would be great if that wasn't needed.

**To Reproduce**

Apply the following CSIDriver manifest to a 1.27 cluster:
```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    argocd.argoproj.io/instance: csi-driver-nfs
  name: nfs.csi.k8s.io
spec:
  attachRequired: false
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Persistent
```

the live state of this resource would be:
```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  creationTimestamp: '2023-03-30T16:20:58Z'
  labels:
    argocd.argoproj.io/instance: csi-driver-nfs
  name: nfs.csi.k8s.io
  resourceVersion: '19449537'
  uid: 8038c804-bb65-41ec-aa4f-9437847f7682
spec:
  attachRequired: false
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
```

**Expected behavior**

The structured YAML diff of Argo CD to work out that there is no difference between the live state and the desired state.

**Version**

v2.7.2+cbee7e6

**Comment by JoseAlvarezSonos** [comment]
Seeing the same issue with ArgoCD `2.7.3+e7891b8` on EKS 1.27.

**Comment by dels78** [comment]
Seeing the same with `v2.7.3+e7891b8` on k3s `v1.27.2+k3s1`

**Comment by davhdavh** [comment]
same issue with kubernetes 1.28.2 and v2.8.2+dbdfc71

**Comment by noroutine** [comment]
same on vanilla 1.28.2 and v2.8.4+c279299

this can be mitigated by disabling feature gate `SELinuxMountReadWriteOncePod` (enabled by default in 1.28)

**Comment by dfroberg** [comment]
Same for EKS v1.28.1-eks

**Comment by monester** [comment]
Also have the same problem on v1.28.2+k3s1 with synology-csi.

**Comment by jtcressy** [comment]
Still experiencing this issue on argocd `v2.9.3+6eba5be`.
K8S version `v1.28.2`, talos linux `v1.5.5`, running bare metal.
Attempted to use `ignoreDifferences` on the application but the diff still fails and the application remains in `Unknown` state.

**Comment by adberger** [comment]
> Still experiencing this issue on argocd `v2.9.3+6eba5be`. K8S version `v1.28.2`, talos linux `v1.5.5`, running bare metal. Attempted to use `ignoreDifferences` on the application but the diff still fails and the application remains in `Unknown` state.
> 
> Edit: It seems the only way to make this go away was to disable the feature gate on my apiserver via `SELinuxMountReadWriteOncePod=false` and remove the seLinuxMount field from my CSIDriver object. **Most managed k8s distributions won't be able to customize apiserver feature gates like this, so YMMV**

Does anyone know, why the following doesn't work?

Argo Application
```
  ...
  ignoreDifferences:
  - group: storage.k8s.io
    jsonPointers:
    - /spec/seLinuxMount
    kind: CSIDriver
```

CSIDriver
```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: testing_nutanix-csi-storage:storage.k8s.io/CSIDriver:nutanix-system/csi.nutanix.com
  creationTimestamp: "2023-12-28T08:35:36Z"
  labels:
    argocd.argoproj.io/instance: testing_nutanix-csi-storage
  name: csi.nutanix.com
  resourceVersion: "83290342"
  uid: a26eab8c-7373-4625-ab53-90d02b0e104a
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
```

Problem occurs on ArgoCD v2.8.4 & v2.9.3

**Comment by algo7** [comment]
Confirmed on ArgoCD v2.9.3+6eba5be with the official kube [csi-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs)

**Comment by kaiburjack** [comment]
@myoung34 [The `ignoreDifferences` spec field of the ArgoCD Application](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L212) is not meant to contain a YAML multiline *string* literal, but a structured YAML array/list.
The workaround still works for me with latest Argo CD.

**Comment by myoung34** [comment]
@kaiburjack I configure it [this way](https://github.com/myoung34/homelab/blob/4b5054436001812e925acb92bf4af443947b863f/k8s/argo/configmap.yaml#L26-L64)

**Comment by myoung34** [comment]
For those coming here:

It _seems_ as though `jsonPointers` depends on the schema and errors, while `jqPathExpressions` does not

I tried 

```
      storage.k8s.io/CSIDriver:
          ignoreDifferences: |
             jsonPointers :
              - /spec/seLinuxMount
```

but it did not work, while 

```
      storage.k8s.io/CSIDriver:
          ignoreDifferences: |
             jqPathExpressions:
              - .spec.seLinuxMount
```

did in fact work and its now green and healthy

**Comment by woehrl01** [comment]
If you still encounter that issue, try to remove "managedFieldsManagers" in any of the matching "ignoreDiff" rules. It looks like that this happens if you have `managedFieldsManagers` set.

**Comment by wpi86** [comment]
> If you still encounter that issue, try to remove "managedFieldsManagers" in any of the matching "ignoreDiff" rules. It looks like that this happens if you have `managedFieldsManagers` set and the crd of the core resources in argocd does not match with the target cluster version.

Confirm, had similar issue, but with Jobs (error building typed results: error creating typedLive: errors: .spec.podReplacementPolicy: field not declared in schema). managedFieldsManagers was set on global level, after removing it ignoredifference start working.
JobPodReplacementPolicy featuregate become beta.
eks 1.29  +  argo v2.10.0+2175939

**Comment by Typositoire** [comment]
I'm also currently hitting this with Kyverno latest chart and multiple fields, the only way to make the chart compute without having `Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: XYZ: field not declared in schema` is to ignore them like so.

```
ignoreDifferences:
  - group: kyverno.io
    kind: ClusterPolicy
    jqPathExpressions:
      - .status.validatingadmissionpolicy
      - .status.autogen
      - '.spec.rules[].skipBackgroundRequests'
      - .spec.admission
```
