### ISSUE TITLE
ArgoCD Extensions as an alternative for Custom Health Check

### ISSUE THREAD

**Issue by rahul-mourya** [argoproj/argo-cd#13589]
# Summary
Currently argocd provides two ways to customize health checks as mentioned here
https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks
1. Updating `argocd-cm` ConfigMap with the lua script for an custom resource under resource.customizations.
2. To contribute adding custom resources logic in the main argocd github repository under resource_customizations.

This proposal/contribution is to utilize argocd-extensions https://github.com/argoproj-labs/argocd-extensions for the same.

This enhancement covers the proposal and the code changes that are required in the code base for argocd-extensions and also on the argocd code base.

# Motivation

Considering a large organization with multiple teams making use of a common argocd environment as a gitops based CD pipeline. Now each of these teams has a huge list of custom resources which they want to modify as per their needs. This list keeps on growing. It becomes a bit tricky and difficult to manage/updates all these custom resources health check under a single `argocd-cm` configmap.

Currently, argocd-extension doesn't seems to have the completeness for utilizing the same as an alternative for custom health check requirements. We were able to add/update codebase for argocd-extensions and argocd to be able to utilize the same for custom health check. We have been using this in out production for a while and would also want to contribute the same back to the community.  

# Proposal

This has been already implemented by us and here is the example with the detailed steps for the same. Once you have the proposed codebase changes in the argod-extensions and argocd repository, the below steps could be followed to utilize the argocd-extensions for custom health check.

1. Create a base directory for all your custom health check e.g. `resource_customizations` directory in your CD repository. The repo where you have all the configuration defines for gitops delivery.
2. For private repo, make sure you have configured a secret with either ssh or github token.
3. Create the structure as follows, with health checks included under resource_customizations/<group-name>/<resource-name>/health.lua.
4. Create an ArgoCDExtension manifest named <service>-extension.yaml, following the format below. 
Note: For private repo, the github ID must have access to the repository in order for ArgoCD to access it!

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: <service-name>
spec:
  baseDirectory: resource_customizations # You can change the base directory here!
  sources:
    - git:
        url: ssh://git@github.com/<org-name>/<repo-name>.git # private/public github repo
        revision: HEAD
        secret:
          name: argocd-extensions-github
          namespace: argocd # argocd namespace
```
The above need to be deployed under the same namespace where argocd is running. Once it is deployed, argocd should be able to retrieve all the custom health check from the configured repo. It support both github public/private repo over SSH or HTTP provided with the authentication with the secret e.g. `argocd-extensions-github`.
Example for the secret, providing repo authentication here:
```
apiVersion: v1
data:
  git_token: <github_token if accessing repo over http>
  git_user: <github userid if accessing repo over http>
  insecure: <true/false> #it is equivalent to skip server verification
  sshkey: <ssh key for accessing github repo>
  type: git
kind: Secret
metadata:
  name: argocd-extensions-github
  namespace: argocd
type: Opaque
```

This provides the individual service lines to maintain and manage all the custom health checks on their own. The only thing which required on the argocd side is the deployment of the above CR pointing to the location of those custom health checks.
All the required changes are already implemented and we have been utilizing the same for our custom health check requirements for over an year now. I will also update this proposal with the link to the required PRs for both argocd-extensions and argocd for you to review the same.
