### ISSUE TITLE
Applications are failing which have more than 53 characters in name

### ISSUE THREAD

**Issue by AnubhavSabarwal** [argoproj/argo-cd#13645]
Checklist:

* [ Yes] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ Yes] I've included steps to reproduce the bug.
* [ Yes] I've pasted the output of `argocd version`.

**Describe the bug**

I have upgraded Argo from **v2.4.7** to **v2.7.2**, all applications got sync except whose name length was more than **53** characters. 
On version 2.4.7, the applications are getting created more than 63 characters.

**To Reproduce**

**Go to Argo -> Create new application -> Edit as yaml -> Paste the below yaml**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testingargocdwithnewhelmchart-clusternamefortestingpurpose
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: testing
    name: testcluster
  project: testProject
  source:
    plugin:
      env:
      - name: HELM_VALUES_FILE
        value: testingargocdwithnewhelmchart-clusternamefortestingpurpose.yaml
      - name: K8S_CLUSTER_NAME
        value: testcluster
      - name: APPLICATION_NAME
        value: testingargocdwithnewhelmchart
    path: usdata/test
    repoURL: https://github.com/helm-deployments.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

ArgoCD config map have
apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance

**Expected behavior**

The application should be created if characters are more than 53 on metadata.name.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.

argocd: v2.7.2+cbee7e6.dirty
  BuildDate: 2023-05-12T13:43:26Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Unable to create application: application spec for testingargocdwithnewhelmchart-clusternamefortestingpurpose is invalid: 
InvalidSpecError: Unable to generate manifests in : 
rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: 
`sh -c "helm template ${ARGOCD_APP_NAME} . -n ${ARGOCD_APP_NAMESPACE} --set ${ARGOCD_ENV_APPLICATION_NAME}-${ARGOCD_APP_NAMESPACE}.k8s_cluster_name=${ARGOCD_ENV_K8S_CLUSTER_NAME} 
--include-crds -f ${ARGOCD_ENV_HELM_VALUES_FILE}"` failed exit status 1: Error: release name "testingargocdwithnewhelmchart-clusternamefortestingpurpose": 
invalid release name, 
must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53
```
