### ISSUE TITLE
ArgoCD Application Render Not Matching Helm template

### ISSUE THREAD

**Issue by anthonyalayo** [argoproj/argo-cd#13643]
## Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

## Describe the bug

I have a basic `kube-prometheus-stack` umbrella helm chart setup, deploying with ArgoCD.

```
kube-prometheus-stack ❯ tree
.
├── Chart.lock
├── Chart.yaml
├── charts
│   └── kube-prometheus-stack-45.26.0.tgz
├── secret-values.yaml
├── templates
├── values.dev.yaml
└── values.yaml

3 directories, 6 files
```

When I check what the result of a helm template is:
```
❯ helm template . -f values.dev.yaml -f values.yaml | grep serviceMonitorSelector
  serviceMonitorSelector: {}

❯ helm template . -f values.dev.yaml -f values.yaml | grep retention
  retention: "30d"
```

It is what I expect, according to the values I setup. However when I deploy this chart via ArgoCD:
```
❯ k get prometheus -o yaml | grep serviceMonitorSelector -A 3
    serviceMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack

❯ k get prometheus -o yaml | grep retention
    retention: 10d
```

It seemingly doesn't apply what I've setup inside the `values.yaml`:
```
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 30d
      serviceMonitorSelectorNilUsesHelmValues: false
```

## To Reproduce

Setup an umbrella chart with `kube-prometheus-stack`:
```
apiVersion: v2
name: kube-prom-stack
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 45.26.0
    repository: https://prometheus-community.github.io/helm-charts
```

Add the following to `values.yaml`:
```
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 30d
      serviceMonitorSelectorNilUsesHelmValues: false
```

Install the chart as an ArgoCD application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: {{ .Values.spec.project }}
  source:
    path: kube-prometheus-stack
    repoURL: https://github.com/anthonyalayo/argo-test
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?secret-values.yaml
        - values.dev.yaml
        - values.yaml
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # required
```

Confirm it's installed:
```
❯ k get apps -n argo | grep prom
kube-prometheus-stack   Synced        Healthy
```

## Expected behavior

I expect the output of `helm template` to match the installed helm chart via ArgoCD.

## Screenshots

![image](https://github.com/argoproj/argo-cd/assets/17555572/9076a6a6-b7a2-429f-b71d-88c1d62fb9ac)

## Version

```shell
❯ argocd version
  argocd: v2.6.4+7be094f.dirty
  BuildDate: 2023-03-07T23:43:59Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
```
