### ISSUE TITLE
Add the ability to call hook for partial synchronization

### ISSUE THREAD

**Issue by vyacheslav25** [argoproj/argo-cd#13652]
# Summary
Add the ability to call hook(BeforeHookCreation, HookSuccess, HookFailed) for partial synchronization

# Motivation
I need to update the image version via values(tag.yaml) , which is in a separate git repository. When I change the application version, argocd automatically changes the version for deployment, after which it has to call a job that runs autotests. But job is not created/recreated . I noticed that the hook works only when there is a full synchronization. Now I am replacing this in a very strange way, which I would like to replace with argo hooks. I spent many hours trying to solve this problem, but I could not find the cause. Therefore, I think that hooks do not work with partial synchronization.

My typical yaml for apps

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  labels:
    app: myapp
spec:
 project: myapp
 sources:
  - repoURL: 'mychart.com/charts'
    chart: myapp
    targetRevision: 1.1.1
    helm:
      releaseName: myapp
      valueFiles:
      - $values/helm-values/myapp/values.yaml  #All parametrs
      - $values/helm-values/myapp/tag.yaml #only tag
  - repoURL: 'git@myrepo.git'
    targetRevision: master
    ref: values
 destination:
    server: https://kubernetes.default.svc
    namespace: myapp
 syncPolicy:
  automated:
    selfHeal: true
  syncOptions:
  - CreateNamespace=true
  - PruneLast=true
  - ApplyOutOfSyncOnly=true
```

# Proposal

Add something like this for application
```
syncOptions:
- ParticalSyncCallHook=true
```
