### ISSUE TITLE
Using the wildcard "*" in "Git Generator: Files" path parameter shouldn't be recursive

### ISSUE THREAD

**Issue by DjoleLepi** [argoproj/argo-cd#13686]
# Summary

I am using the ArgoCD `Git Generator: Files` with a wildcard (`*` or `**`) in the `path` parameter. With any of the wildcards the Generator looks for files recursively.

In my opinion, the `*` wildcard should represent a single directory.

# Motivation

If someone is using the `Git Generator: Files` with any of the following `path` parameter:
- `path: examples/**/config.json`
- `path: examples/*/config.json`

In both cases these will also find `config.json` files located at `examples/test/dir/another/config.json`.

I don't think it is expected to have ArgoCD recurse through the directories when `*` is used

# Proposal

- Using `path: examples/**/config.json` should find `examples/test/config.json` and `examples/test/dir/another/config.json`
- Using `path: examples/*/config.json` should find `examples/test/config.json` **BUT NOT** `examples/test/dir/another/config.json`

**Comment by christianh814** [comment]
Concurrently, it would be nice to be able to have the `exclude` option as well for the `Git Generator: Files`

**Comment by alexmt** [comment]
If I’m not mistaken this PR fixes the issue https://github.com/argoproj/argo-cd/pull/13314

**Comment by DjoleLepi** [comment]
> If I’m not mistaken this PR fixes the issue #13314

Yes, thank you for the info!


Regarding @christianh814 comment. There was an issue on the old repo https://github.com/argoproj/applicationset/issues/468. Maybe you could create a new issue

**Comment by christianh814** [comment]
New issue created #13690

**Comment by maffka123** [comment]
Hello,

I think this issue is not fixed yet. We have ArgoCD v3.1.8+becb020 and when I create appset like this
```yaml
                generators:
                - matrix:
                    generators:
                      - git:
                          repoURL: "{{.url}}"
                          revision: HEAD
                          files:
                            - path: "*.yaml"
                      - list:
                          elements: []
                          elementsYaml: "{{`{{ .appComponents | toJson }}`}}"
                goTemplate: true
                goTemplateOptions: ["missingkey=error"]
                template:
...
```
Argo searches for yamls in root, but also in subfolders recursively, what is not expected.
