### ISSUE TITLE
Add support for multiple sources in argocd cli diff|manifests

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [argoproj/argo-cd#13682]
# Summary

ArgoCD 2.6+ introduced multi source apps. Argocd CLI is not able to render manifests or show diffs, when multiple application have a different revision. 

# Motivation

Sample multiple source app:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  labels:
    type: deployment
    application: argo-rollouts
    timestamp: lol
spec:
  project: default
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 2.22.3
      chart: argo-rollouts
      helm:
        valueFiles:
        - $values/argocd/applications/values/argo-rollouts/values-common.yaml
    - repoURL: https://github.com/my-repo/argo-iac.git
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-rollouts
```

In the above example, we have 2 different targetRevisions:
- One for public helm chart
- One for the values of this helm chart, which are stored in another github repo

When running argocd cli, the revision parameter refers to the targetRevision, and only one value can be provided:
```
 argocd app diff argocd/rollouts --grpc-web --revision=xxx
```

# Proposal

I think that 2 approaches could be possible to handle this:
- Be able to define target revision per source. (Not ideal)
- Render the whole application manifest based on the github branch content of the application. This means that if we have a new branch where this application is defined with same changes, use the target revision and values defined in this branch.

**Comment by cmontemuino** [comment]
I also notice the same issue without using helm.

For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-admin
  sources:
    - repoURL: git@gitlab.example.com:k8s/gitops.git
      targetRevision: main
      path: infra/gitops/overlays/cluster-a
    - repoURL: git@gitlab.example.com:k8s/gitops.git
      targetRevision: main
      path: infra/auth/overlays/cluster-a
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

It seems like the desired state config is taken form the first source only. It does not matter if I use `argocd app diff <app-name> --revision <rev> --refresh` or `argocd app diff <app-name> --local /path-to-cloned-repo-at-specific-revision --server-side-generate`
