### ISSUE TITLE
Kustomize commonAnnotations on ApplicationSet sometimes sets wrong annotation value

### ISSUE THREAD

**Issue by yilmazo** [argoproj/argo-cd#13696]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Kustomize commonAnnotations on ApplicationSet sometimes sets wrong annotation value. I think this can be fixed by checking if there are any commonAnnotations in [this method](https://github.com/argoproj/argo-cd/blob/b44c805e9d690686988e8cd81231b27093dc5a9a/pkg/apis/application/v1alpha1/types.go#L500).

**To Reproduce**
Since this is caused by a race condition, there isn't a convenient way to reproduce it. In my case, I have an ApplicationSet similar to the following example and I have almost 100 Kubernetes clusters to deploy it. I'm trying to add a commonAnnotation with cluster name as its value.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: prod
  template:
    metadata:
      name: "{{name}}-foo"
      labels:
        app: foo
    spec:
      project: foo
      source:
        repoURL: <my-repo>/manifests.git
        targetRevision: HEAD
        path: ".appsets/foo"
        kustomize:
          commonAnnotations:
            clustername: "{{ name }}"
      destination:
        name: "{{name}}"
        namespace: foo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true

```

**Expected behavior**
`clustername` annotation is added to each Application with respective cluster's name.

**Version**

```shell
v2.5.5
```
