### ISSUE TITLE
ArgoCD applicationset controller storage grows indefinitely

### ISSUE THREAD

**Issue by moleskin-smile** [argoproj/argo-cd#13691]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD ApplicationSet Controller pods' `/tmp` volume grows indefinitely if one of GitOps state repositories is frequently updated. `argocd-applicationset-controller` pods are frequently being evicted because of disk pressure. 

If I `kubectl exec` to a `argocd-applicationset-controller` pod and execute `git gc` in `/tmp/https___github.com_*/` directory, a lot of disk space is reclaimed.

(Repo server use the same GitOps state repositories, but `/tmp` doesn't grow there indefinitely, but remains at constant, low level).

To work around the issue, first we added an EBS ephemeral volume of 100G. It didn't help – ApplicationSet controller ate that storage quickly. Then we added a container that executes `git gc` on this volume periodically. We also had to add an init container to set 1777 on /tmp.

Source of the workaround that works for us (kustomize patches):

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      volumes:
        - name: tmp
          emptyDir: null
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: std-ebs-gp3
                resources:
                  requests:
                    storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-applicationset-controller-git-gc
          image: quay.io/argoproj/argocd:v2.6.4
          command:
            - sh
            - "-c"
            - |-
              set -eEu
              while true; do
                sleep 600
                for git_dir in /tmp/*/.git/; do
                  echo "Running git gc of ${git_dir}..."
                  rm -f ${git_dir}objects/pack/*.keep || true
                  git --git-dir="${git_dir}" gc
                done
              done
          resources:
            limits:
              cpu: 100m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      initContainers:
        - name: argocd-applicationset-controller-tmp-chmod
          image: busybox:1.36.0-musl
          command:
            - sh
            - "-c"
            - "chmod 1777 /tmp"
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            runAsUser: 0
```

**To Reproduce**

Configure applicationset controller to watch a repo that is frequently updated.

ApplicationSet resource:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    # (...)
  name: staging-01-envs
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: envs/**/env-generator-config.yaml
        repoURL: https://github.com/<redacted>
        revision: HEAD
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""
  template:
    metadata:
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        # (...)
      name: staging-01-env-{{ path.basename }}
      namespace: argocd
    spec:
      destination:
        name: in-cluster
        namespace: argocd
      project: deployments-staging-seed
      revisionHistoryLimit: 10
      source:
        helm:
          ignoreMissingValueFiles: true
          releaseName: staging-01-env-{{ path.basename }}
          valueFiles:
            - values.yaml
            - user-values.yaml
          values: '{}'
        path: '{{ path }}'
        repoURL: https://github.com/<redacted>
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
```

**Expected behavior**

Disk usage doesn't grow indefinitely.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/20775179/82cc271d-3c10-4175-b485-b61fdae6ebd3)

**Version**

```shell
argocd: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T18:57:22Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.20.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T18:57:22Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.20.3
  Compiler: gc
  Platform: darwin/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:20:22Z
  Helm Version: v3.9.3+g414ff28
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

We only see errors like this:

```
{
  (...)
  "error": "Error during fetching repo: `git fetch origin HEAD --tags --force --prune` failed timeout after 1m30s"
}
```

```
`git fetch origin HEAD --tags --force --prune` failed timeout after 1m30s
```

If this is our problem – is there a way to increase this timeout?
