### ISSUE TITLE
 Add the ability to exclude files when using the git file generator #468 

### ISSUE THREAD

**Issue by christianh814** [argoproj/argo-cd#13690]
**NOTE: Original Issue found [here](https://github.com/argoproj/applicationset/issues/468)**

When using the git directory generator it is possible to exclude specific paths like this

```
  - git:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      revision: HEAD
      directories:
      - path: examples/git-generator-directory/excludes/cluster-addons/*
      - path: examples/git-generator-directory/excludes/cluster-addons/exclude-helm-guestbook
        exclude: true
```

When using the git file generator I would like to be able to add files using a wildcard and then exclude specific files like this

```
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      revision: HEAD
      files:
      - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
      - path  "examples/git-generator-files-discovery/cluster-config/staging/config.json"
        exclude: true
```

Of course if there is another way to do this that I am not aware of then I would be happy to use that. If not I am also happy to implement this change if it is agreed.

**Comment by MattiDeGrauwe** [comment]
@christianh814 did you find a workaround for this? also in need for this feature

**Comment by krisdock** [comment]
we have a pressing need for this as well. thanks for working on it.

**Comment by vl-kp** [comment]
any workaround?

**Comment by hubmat00** [comment]
anyone knows if the proposed [PR from old applicationset repo](https://github.com/argoproj/applicationset/issues/468) got ever moved to argoproj/argo-cd?

if not, would you mind if I take over this issue and move/migrate this proposed [PR](https://github.com/argoproj/applicationset/issues/468) by @adamjohnson01 ?!

FYI @crenshaw-dev @adamjohnson01 as you were mainly involved in the [original issue](https://github.com/argoproj/applicationset/issues/468).

**Comment by andrey-parkhomets** [comment]
Hi there, 
my current workaround: **wrap `Git-Files-Generator` with `matrix`** where second child can be anything, one of : `list` of `cluster` generator with necessary logic to select single or few target clusters. 

example:
```yaml
  applyNestedSelectors: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          pathParamPrefix: conf
          repoURL: https://github.com/my-dot-com/my-argo-repo.git
          revision: HEAD
          files:                                # <namespace>/<application>.yaml
            - path: argocd-cluster/_app-catalog/**/*.yaml # from here we need only two files argocd.yaml and sealed-secrets.yaml
          values:
            applName: '{{ splitList "." .conf.path.filename |first }}'. # need to add values  like this or simple, i.e.  ".conf.path.filename" , so it become a  label

      - clusters:
          selector:
            matchExpressions:
            - {key: type, operator: In, values: [hub]}

# here it is, should allow you to implement "In" or "NotIn" logic
  selector:
    matchExpressions:
      - key: applName
        operator: In
        values: 
          - 'argocd'
          - 'sealed-secrets'
```

```bash
-> % argocd version
argocd: v2.14.4+3d901f2
  BuildDate: 2025-03-04T22:56:08Z
  GitCommit: 3d901f2037888af302a85f518bea70b33ee8e1c7
  GitTreeState: clean
  GoVersion: go1.24.0
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.14.4+3d901f2
  BuildDate: 2025-03-04T20:39:46Z
  GitCommit: 3d901f2037888af302a85f518bea70b33ee8e1c7
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```
