### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by zibuyule** [argoproj/argo-cd#13726]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I deployed a self built private Harbor and have configured a self signed TLS certificate for it.

I configured a repo for argocd using the parameter " **--insecure-skip-server-verification**", and it appears to be successfully connected.

The command is as follows:

> argocd repo add harbor.sredevops.me --type helm --name will-harbor-helm --enable-oci --username admin --insecure-skip-server-verification

![connect-harbor](https://github.com/argoproj/argo-cd/assets/5792519/62205536-2e6c-4934-a175-0fdb7ac73834)

The chart in my Harbor is as follows:
![helm-harbor-nginx](https://github.com/argoproj/argo-cd/assets/5792519/ac65bd36-90af-4c34-a437-5762d6260058)
![helm-harbor-nginx2](https://github.com/argoproj/argo-cd/assets/5792519/c00db971-41b0-4796-a8d9-1c42bb1cffd7)
![helm-harbor-nginx3](https://github.com/argoproj/argo-cd/assets/5792519/e93f3e7e-4094-4d58-92e8-d53bdfa4415a)

I have created an application as follows:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx-harbor
  namespace: argocd
spec:
  project: default
  source:
    chart: helm/nginx
    repoURL: harbor.sredevops.me
    targetRevision: "0.24"
    helm:
      releaseName: my-nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helm-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

![application-1](https://github.com/argoproj/argo-cd/assets/5792519/f045ba7c-2bc4-43d6-9b10-511ad31a329b)

![application-2](https://github.com/argoproj/argo-cd/assets/5792519/6673d98c-a170-488b-a1f2-206bf230d0d9)

The Configmap also looks normal.
![configmap1](https://github.com/argoproj/argo-cd/assets/5792519/4f3762c7-396f-463e-9679-46f16a616081)

![pod-argocd-server](https://github.com/argoproj/argo-cd/assets/5792519/0b137d11-edef-49f5-a202-16fbbb7a1787)

![pod-argocd-repo-server](https://github.com/argoproj/argo-cd/assets/5792519/20638536-f908-4290-b3f9-a77004f58dc1)

I always thought that if the repo connection was successful, the application should not show 'x509: certificate signed by unknown authority'.

**To Reproduce**

**Expected behavior**

The expected behavior is that the application can proceed smoothly. Ultimately, a chart named nginx will be installed.

**Screenshots**

**Version**
argocd： 2.72

![argocd](https://github.com/argoproj/argo-cd/assets/5792519/d7426a82-b80f-411b-983e-5755d55d0395)

![argocd2](https://github.com/argoproj/argo-cd/assets/5792519/9e97ce54-251f-4520-be5f-28e92334217c)

```shell

**Logs**

```
Paste any relevant application logs here.
```

**Comment by dan-m8t** [comment]
https://github.com/argoproj/argo-cd/issues/12371

**Comment by augeivv** [comment]
We have the problem as well and cannot continue without the feature.
We use the current version 2.8.4.

Is there a solution for this?

**Comment by dromie** [comment]
@augeivv 
This issue is "fixed" and your v2.8.4 should contain the fix, BUT.......

when you update your argocd-tls-certs-cm configmap with the TLS certificate, this configmap is mounted into argocd-server pod.
And it can take up two minutes from you updating your configmap update till that update gets mounted into the argocd-server pod.  [k8s-doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically)
And argo-cd won't refresh your application automatically, you need to hit the refresh button.

Option B: update your argocd-tls-certs-cm configmap, wait 2 minutes, and deploy your application. 

Feel free to test this, you can use my testenv (https://gist.github.com/dromie/0199dada8f1d080c83c292e2e3e30f85)

**Comment by dromie** [comment]
@FrancescoAzzariti 
In the argocd-server pod's container you should be able to find the "openssl" command,  in my testsetup the following command shows "Verification: OK", what does your's say?

`openssl s_client -debug -showcerts -CAfile /app/config/tls/myregistry  -connect myregistry:443`

**Comment by FrancescoAzzariti** [comment]
I just checked - mine says:
`Verify return code: 2 (unable to get issuer certificate)`

i'll try adding the cert of the issuer / the whole chain

**Comment by ElouanLD** [comment]
Hi, we are facing the exact same problem on argocd v2.9.0. Helm version in pods is v3.12.1.

We have one Harbor instance signed with a private CA in our network. 

We are trying to setup argocd to pull charts from an application but we always face the "x509: certificate signed by unknown authority". 

Local charts calling for the main metallb chart stored on Harbor :
```yaml
apiVersion: v2
name: metallb
description: A network load-balancer implementation for Kubernetes using standard routing protocols
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: helm/metallb
  repository: oci://registry.harbor.ats-sre.ngxp.domaintests.loc
  version: 0.13.9 

```

I have performed the following tasks :

- Setup the registry in argocd (argocd repo add registry.harbor.ats-sre.ngxp.domaintests.loc --type helm --name harbor --username test --enable-oci --insecure-skip-server-verification)
- Add the harbor certificate to argocd "Repository certificates and known hosts"
- Wait 2 minutes
- Checked that the configmap correclty contains the harbor certificate
- Checked that the harbor certificate is correctly mounted in the /app/config/tls/ folder of both "reposerver" and "server" pods
- Checked that openssl correctly responds "Verification: OK" to previous openssl command (openssl s_client -debug -showcerts -CAfile /app/config/tls/myregistry  -connect myregistry:443)

@FrancescoAzzariti you seemed to have found a way to make it work. Can you explain how did you perform the resolving task ? I don't quite understand what you mean by "I mounted the configmap which includes the cert+chain provided by trustmanager into the "reposerver" and "server" pod to /etc/ssl/certs/pkichain.pem". Can you provide more details ? (commands or created confimaps ?) Thank you !

Ps : To expand on this bug, we found that by creating an application from the UI did correctly pull the helm chart. From the "Repositories" settings panel, you can create an application from a specific registry by clicking on the 3 dots and Create application. If we do that, there is no issue, the helm chart is correctly retrieved from Harbor. It seems that the "--insecure-skip-verify" of helm is correctly passed and used here but not if we point to the repository in a chart or application.

**Comment by augeivv** [comment]
Hello,
First of all, thank you very much for the information.
I have done some more research as I am still having these problems.

I assume we are currently talking about different possibilities. ArgoCD and Helm Charts.

Roughly speaking, I have the same setup as @ElouanLD 
And can agree that it doesn't work with version 2.8.4 or newer either.

If I link directly to the Helm Chart repository in my ArgoCD application, the deployment works. However, if I link to a Git repository in the ArgoCD application, which contains a local chart, I still get the x509 error.

I have also tried @FrancescoAzzariti solution. But without success.

**Comment by FrancescoAzzariti** [comment]
The ConfigMap ist created by Trustmanager ( https://github.com/cert-manager/trust-manager ) and placed inside the argo-cd namespace. 

Afterwards I updated the values.yaml of the helmchart by which ArgoCD is installed:
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L2197-L2206

This looks something like this for me:
```
  # -- Additional volumeMounts to the Repo Server main container
  volumeMounts:
    - mountPath: /etc/ssl/certs/pkichain.pem
      name: pkibw-ca-certs
      subPath: root-certs.crt

  # -- Additional volumes to the Repo Server pod
  volumes:
    - name: pki-ca-certs
      configMap:
        name: pki-ca-certs
``` 

I hope this helps :)
@ElouanLD @augeivv

**Comment by augeivv** [comment]
@FrancescoAzzariti 

Thank you for your help. It works. 
I had bound the certificates to the server pod. But not to the repo server.

**Comment by benjsc** [comment]
Facing the same issue  We have a application with a source being a gitrepo, referencing a helmchart, with a dependancy on another helmchart which in an oci registry. 

```
This causes argocd to need to run _[helm dependency build](https://github.com/argoproj/argo-cd/blob/6eba5be864b7e031871ed7698f5233336dfe75c7/util/helm/cmd.go#L247)_ but that doesn't pick up the certs or honour the tls ignore and argocd-server reports the error:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: could not download oci://<registryhere>: failed to do request: Head "https://<registryhere>/v2/<chartnamehere>/manifests/<chartversionhere>": tls: failed to verify certificate: x509: certificate signed by unknown authority
``` 

For anyone following if you get the error due to `helm dependency build` failing, your after this bug #6477

**Comment by BigKAA** [comment]
Hello
It doesn't work for me either.

argocd:v2.10.0

```json
{"execID":"092dc","level":"error","msg":"`helm pull oci://registry.kryukov.local/charts/devcontainer --version 0.1.0 --destination /tmp/0a234fff-856f-4fbe-af0d-6e6cc2404793` failed exit status 1: Error: failed to do request: Head \"https://registry.kryukov.local/v2/charts/devcontainer/manifests/0.1.0\": tls: failed to verify certificate: x509: certificate signed by unknown authority","time":"2024-02-28T10:21:14Z"}
```

in containers. The file `registry.kryukov.local` contains the CA certificate

```shell
argocd@argo-cd-argocd-server-5f8bcf7999-kt2pj:~$ ls /app/config/tls
registry.kryukov.local
```

```shell
argocd@argo-cd-argocd-repo-server-7bdbfcc9b4-qsxh5:/etc/ssl/certs$ ls /app/config/tls
registry.kryukov.local
```

**Comment by lknite** [comment]
I'm seeing this as well when I try to pull an image from harbor.  I've seen it before and was able to just click 'hard refresh' and it started working but looks like it really is struggling this time and haven't been able to pull the image.  For me the logs are showing:
```time="2024-05-17T00:06:54Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:07:04Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:07:14Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:07:24Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:07:34Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:07:40Z" level=info msg="invalidated cache for resource in namespace: argocd with the name: argocd-notifications-cm"
time="2024-05-17T00:07:40Z" level=info msg="invalidated cache for resource in namespace: argocd with the name: argocd-notifications-secret"
time="2024-05-17T00:07:44Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:07:54Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:08:04Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:08:14Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:08:24Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:08:34Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:08:40Z" level=info msg="Alloc=18006 TotalAlloc=335991 Sys=57701 NumGC=25 Goroutines=106"
time="2024-05-17T00:08:44Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:08:54Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:09:04Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:09:14Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:09:24Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:09:34Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:09:44Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:09:54Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:10:04Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:10:14Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:10:24Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
time="2024-05-17T00:10:34Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
```

**Comment by lknite** [comment]
```
$ openssl s_client -debug -showcerts -CAfile /app/config/tls/k.home.net -connect harbor.vc-prod.k.home.net:443 | grep Veri
depth=1 CN = k.home.net
verify return:1
depth=0 
verify return:1
Verification: OK
Verify return code: 0 (ok)
```

**Comment by lucatr** [comment]
Facing the same issue, pretty much same setup as @FrancescoAzzariti. Might very well be a chain issue as well, and I'll try to fix that accordingly. When trying to verify with openssl from the repo-server pod, I'm getting `unable to get issuer certificate`. This shouldn't pop up if using `--insecure-skip-server-verification` (respectively setting insecure to true), right?  Otherwise I don't understand what the flag is there for.

**Comment by svghadi** [comment]
I think this has been fixed with #16656. Self-signed certs + helm oci registry worked for me with Argo CD v2.10.11. Try latest version of 2.10.x or 2.11.x. However, there is a bug (#19138) that affects certain scenarios, but it should work in most cases.

**Comment by kromooooo** [comment]
I have faced the same issue
`ArgoCD v2.14.2 ` installed via `helm chart 7.8.2`

My case is close to @FrancescoAzzariti 
I have Artifactory for store helm charts, and I have internal CA which is used to issue other TLS certs in the company.
I tried to add a bundle with fullchain certs under configmap `argocd-tls-certs-cm` and I even see it in the GUi in Settings -> Repository certificates and known hosts. But I still got an error `x509: certificate signed by unknown authority`

so, I decided to ignore it, and created a new secret for the repo with the flag ` insecure: "true" `

```
apiVersion: v1 
kind: Secret 
metadata: 
  name: artifactory-repo-insecure 
  namespace: argocd 
  labels: 
    argocd.argoproj.io/secret-type: repository 
stringData: 
  enableOCI: "false" 
  insecure: "true" 
  name: "artifactory"  ##remember this name
  type: helm 
  url: "https://artifactory.example.com:443/artifactory/helm/"
```

in the GUI I saw that the repo was added successfully, there is no error. But, when I tried to create application through yaml again, I still got the error `x509: certificate signed by unknown authority`

After some research, and attempts to use approaches defined in this thread, I found an interesting note from @ElouanLD where he mentioned that if add an application from the "Repository" settings panel it works.. and yes. So I compared why and looks like I found the reason:

If you have not defined the name of the repository in the application, looks like ArgoCD uses it as a "new" repo, and not the repo already added with the ` insecure: "true" ` flag!

After I had added the name for Helm repo in the app and reapplied it, it started syncing successfully. Here is a simple app as an example:
```
apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  name: goldpinger 
  namespace: argocd 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io 
spec: 
  destination: 
    namespace: goldpinger 
    server: https://kubernetes.default.svc 
  project: dev-infra 
  sources: 
    - repoURL: https://git.example.com/somerepo-dev/argocd.git 
      targetRevision: master 
      ref: gitlabRepo 
    - name: artifactory ##despite this filed is not mandatory, this should be the same name as defined in the already created repo, if it is not the same or not defined - you will get an mentioned error
      repoURL: https://artifactory.example.com:443/artifactory/helm/ 
      targetRevision: 1.0.1 
      chart: goldpinger 
      helm: 
        releaseName: goldpinger 
        valueFiles: 
        - $gitlabRepo/apps/goldpinger/values.yaml 
  syncPolicy: 
    syncOptions: 
    - CreateNamespace=true ` 
```

If it is expected behavior, it would be great to mention it in documentation.

Thanks @FrancescoAzzariti @ElouanLD you save a lot of time for me!)
