### ISSUE TITLE
Go templates are not expanded in list generator values block

### ISSUE THREAD

**Issue by raxod502-plaid** [argoproj/argo-cd#13732]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In the ArgoCD matrix generator [you can use parameters from one generator in the definition of the second](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#using-parameters-from-one-child-generator-in-another-child-generator). There are [a few documented restrictions](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#restrictions).

However, there is an additional restriction that I don't think is documented - some fields in the second generator don't expand templates. One example is the `elements` list in the list generator. In the following code, `{{ .values.dnsWeight }}` will not be expanded, the value will be used as is, curly braces and all:

```yaml
  - matrix:
      generators:
      - clusters:
          values:
            dnsWeight: "0"
      - list:
          elements:
          - dnsWeight: "{{ .values.dnsWeight }}"
```

This is because of a limitation in the `deeplyReplace` function that is used to perform the template expansion in applicationsets. Specifically, it replaces strings:

https://github.com/argoproj/argo-cd/blob/5e543518dbdb5384fa61c938ce3e045b4c5be325/applicationset/utils/utils.go#L149-L150

But not bytes:

https://github.com/argoproj/argo-cd/blob/5e543518dbdb5384fa61c938ce3e045b4c5be325/applicationset/utils/utils.go#L164

This seems correct, but it has unintended side effects. Take a look at the way the `ListGenerator` configuration is defined:

https://github.com/argoproj/argo-cd/blob/5e543518dbdb5384fa61c938ce3e045b4c5be325/pkg/apis/application/v1alpha1/applicationset_types.go#L183-L188

And `apiextensionsv1.JSON` [is just unparsed bytes](https://github.com/kubernetes/apiextensions-apiserver/blob/501bf5ec6db2f5e9171a8ed822380f71911b1b8f/pkg/apis/apiextensions/v1/types_jsonschema.go#L252-L256):

```go
// JSON represents any valid JSON value.
// These types are supported: bool, int64, float64, string, []interface{}, map[string]interface{} and nil.
type JSON struct {
	Raw []byte `json:"-" protobuf:"bytes,1,opt,name=raw"`
}
```

So all sub-fields specified in the list generator configuration get skipped during template application, even if they are valid strings that appear the same as others in the applicationset. This may be surprising to the user.

**To Reproduce**

Here's some example YAML:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              something: value
          values:
            dnsWeight: "0"
      - list:
          elements:
          - something: value
            app:
              name: example
              subkey: value
            dnsWeight: "{{ .values.dnsWeight }}"
            setIdentifier: my-record
  template:
    metadata:
      name: '{{ .app.name }}-{{ .name }}'
    spec:
      project: 'my-project'
      sources:
      - repoURL: https://example.com.git
        path: path/to/chart
        targetRevision: master
        helm:
          releaseName: '{{ .app.name }}-foobar'
          values: |
            ingress:
              annotations:
                external-dns.alpha.kubernetes.io/alias: "true"
                external-dns.alpha.kubernetes.io/aws-weight: {{ .dnsWeight | quote }}
                external-dns.alpha.kubernetes.io/set-identifier: {{ .setIdentifier }}/{{ .name }}
      destination:
        server: '{{ .server }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
```

Note that we define `values.dnsWeight` in the cluster generator, then reference it as `{{ .values.dnsWeight }}` from the list generator to copy it to the top level, so we can use it as `{{ .dnsWeight }}` in the Helm values template. This doesn't work because `{{ .values.dnsWeight }}` is taken literally by the list generator instead of being templated.

**Expected behavior**

All strings in the provided appset yaml are expanded, not just the ones that happen to be defined explicitly as strings in the internal structs inside ArgoCD.

**Screenshots**

Example manifest templated without Go templates being expanded:

![image](https://github.com/argoproj/argo-cd/assets/69264599/5b7656c1-99ad-4da1-b86e-df14b52ea3e3)

Internal notes on the appset in question:

![image](https://github.com/argoproj/argo-cd/assets/69264599/1611e736-2acd-41c8-992d-a675eac37808)

**Version**

```shell
argocd: v2.6.7+unknown
  BuildDate: 2023-04-03T15:48:13Z
  GitCommit:
  GitTreeState: clean
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/amd64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.7.1+5e54351.dirty
```

**Logs**

n/a
