### ISSUE TITLE
wrong replacement of variable .Release.Namespace value while rendering the helm chart

### ISSUE THREAD

**Issue by vaashu99** [argoproj/argo-cd#13735]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I was trying to use a helm chart with kustomize, I added the flag `--enable-helm` in argo cm as suggested [here](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomizing-helm-charts). but I noticed one of the deployments was failing because the appended value of `.Release.Namespace` is wrong in ConfigMap.

I tried to render the chart locally with Kustomize build and helm template and values are correct everywhere. pasting output for your reference.

**helm chart:**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  {{- if .Values.global.prometheus.enabled }}
  {{- if .Values.global.zone }}
    prometheus-alertmanager-endpoint: http://{{ template "cost-analyzer.prometheus.alertmanager.name" . }}.{{ .Release.Namespace  }}.svc.{{ .Values.global.zone }}
  {{ else }}
    prometheus-alertmanager-endpoint: http://{{ template "cost-analyzer.prometheus.alertmanager.name" . }}.{{ .Release.Namespace  }}
  {{- end -}}
  {{ else }}
    prometheus-alertmanager-endpoint: {{ .Values.global.notifications.alertmanager.fqdn }}
  {{- end -}}
  {{ if .Values.global.gmp.enabled }}
    prometheus-server-endpoint: {{ .Values.global.gmp.prometheusServerEndpoint }}
  {{- else if .Values.global.amp.enabled }}
    prometheus-server-endpoint: {{ .Values.global.amp.prometheusServerEndpoint }}
  {{- else if .Values.global.prometheus.enabled }}
  {{- if .Values.global.zone }}
    prometheus-server-endpoint: http://{{ template "cost-analyzer.prometheus.server.name" . }}.{{ .Release.Namespace  }}.svc.{{ .Values.global.zone }}
  {{ else }}
    prometheus-server-endpoint: http://{{ template "cost-analyzer.prometheus.server.name" . }}.{{ .Release.Namespace  }}
  {{- end -}}
  {{ else }}
    prometheus-server-endpoint: {{ .Values.global.prometheus.fqdn }}
  {{- end -}}
  {{- if .Values.kubecostToken }}
    kubecost-token: {{ .Values.kubecostToken }}
  {{ else }}
    kubecost-token: not-applied
  {{- end -}}
```
**Kustomization.yaml:**

```
namespace: kubecost
 helmGlobals:
   chartHome: charts
 helmCharts:
 - name: cost-analyzer
   includeCRDs: true
   releaseName: kubecost
   version: 1.103.2
```

**output of kustomize build command:**

```
# Source: cost-analyzer/templates/cost-analyzer-config-map-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: validation-test-cost-analyzer
  namespace: kubecost
  labels:
    
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.103.3
    app.kubernetes.io/instance: validation-test
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
data:
    prometheus-alertmanager-endpoint: http://validation-test-prometheus-alertmanager.kubecost
    prometheus-server-endpoint: http://validation-test-prometheus-server.kubecost
    kubecost-token: not-applied
```

**output of helm template command:**
```
---
# Source: cost-analyzer/templates/cost-analyzer-config-map-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: validation-test-cost-analyzer
  namespace: kubecost
  labels:

    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.103.3
    app.kubernetes.io/instance: validation-test
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
data:
    prometheus-alertmanager-endpoint: http://validation-test-prometheus-alertmanager.kubecost
    prometheus-server-endpoint: http://validation-test-prometheus-server.kubecost
    kubecost-token: not-applied
```

**Live menifest in argoCD:**

```
apiVersion: v1
data:
  kubecost-token: not-applied
  prometheus-alertmanager-endpoint: 'http://kubecost-prometheus-alertmanager.default'
  prometheus-server-endpoint: 'http://kubecost-prometheus-server.default'
kind: ConfigMap
metadata:
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: dev-backend-kubecost-install
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.103.3
  name: kubecost-cost-analyzer
  namespace: kubecost
```

**To Reproduce**

deploy the kubecost helm-chart with argocd kustomise 

**Expected behavior**

Namespace value should be replaced by kubecost

**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/36596644/e2637b70-bb43-4a20-890d-048fac5fc551)
![image](https://github.com/argoproj/argo-cd/assets/36596644/aff66d50-5803-4c61-ad57-2054eb323c64)

**Version**

```
 argocd version     
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:30:45Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.0+acc554f
```

**Logs**

```
Paste any relevant application logs here.
```
