### ISSUE TITLE
Automated preview environments at Pull Request

### ISSUE THREAD

**Issue by dakar91** [argoproj/argo-cd#13741]
# Summary

Bunnyshell is providing free Kubernetes infrastructure to open source projects.

Would you be interested in having preview environments on future pull requests?

Our team @bunnyshell and @bunnyshellosi are ready to help implement the initial pipeline to get you started!

# Motivation

We really think some of the issues and PRs can benefit from preview environments, like the 244 open issues which are UI related: https://github.com/argoproj/argo-cd/labels/component%3Aui

# Proposal

Example PR-preview workflow - https://github.com/aris-bunnyshell/demo-books-php/tree/main/.github/workflows
Example configuration - https://github.com/aris-bunnyshell/demo-books-php/blob/main/.bunnyshell/templates/docker-compose/bunnyshell.yaml

**Comment by dakar91** [comment]
Hey @jannfis or @crenshaw-dev I saw you've done some work with gitpod in the argocd project, maybe you can see if this initiative is interesting move forward with?

**Comment by BunnyCrlu** [comment]
Hey @crenshaw-dev,

Regarding generating preview environments in specific scenarios, Github Actions can definitely help here.

A simple approach would be to guard the jobs under a specific label (similar to an opt-in):

```yaml
name: Preview Environment

on:
  pull_request:
      types: [opened, reopened, synchronize, labeled]

jobs:
  preview:
    if: contains(github.event.pull_request.labels.*.name, 'bns:preview')
    runs-on: ubuntu-latest

    steps:
    - name: Demo
      run: echo "Hello from PRs containing bns:preview"
```

Other solutions might include community driven actions such as [trstringer/manual-approval](https://github.com/trstringer/manual-approval) which has a couple more features you might be interested in.

What are the next steps here in your opinion?
