### ISSUE TITLE
New user, Same Cluster?

### ISSUE THREAD

**Issue by alifiroozi80** [argoproj/argo-cd#13810]
Hello everyone

We already have an ArgoCD deployment in the cluster with the default `admin` user.

Everything is fine, but we wanted to create another user, so we did like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  accounts.bot: apiKey, login
  policy.csv: |
    p, role:admin-group, applications, *, */*, allow
    p, role:admin-group, clusters, get, *, allow
    p, role:admin-group, repositories, get, *, allow
    p, role:admin-group, repositories, create, *, allow
    p, role:admin-group, repositories, update, *, allow
    p, role:admin-group, repositories, delete, *, allow
    g, bot, role:admin-group
```

and then we applied it with the `kubectl` CLI.

In the Argo Pod, we checked it, and it's there!

```shell
$ argocd account list
NAME   ENABLED  CAPABILITIES
admin  true     login
bot    true     apiKey, login
```

and even defined a password for it:

```shell
$ argocd account update-password --account "bot" --new-password "Superstrong-Password"
```

---

We did everything right, but we saw nothing when we logged in with this new user!

It is like a fresh installation!

We had a lot of projects there, defined repositories and clusters, and none were there!

---

I searched and found nothing!
Read the docs and also found nothing!

How can we define a user, for instance, this new `bot` user and this new user have access to all the previously configured resources just like the `admin` user?
