### ISSUE TITLE
ApplicationSet: Provide repoURL and revision in GitGenerator

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#13828]
# Summary

When using ApplicationSet with GitGenerator to generate an Application from a mono-repo, it is pretty annoying to repeat the revision and repoURL. And moreover if you want to test a feature.

# Motivation

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: public-charts
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
  - git:
      repoURL: https://gitlab.org/entity/department/team/infra.git # When testing a feature from fork I need to switch this
      revision: HEAD  # When testing feature from revision I need to switch this
      files:
      - path: 'components/charts/**/values.yaml'
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: team
      source:
        repoURL: https://gitlab.org/entity/department/team/infra.git # When testing a feature from fork I need to switch this
        targetRevision: HEAD # When testing a new feature from revision I need to switch this
        path: '{{ .path.path }}'
        helm:
          valueFiles:
            - values.yaml
            - values.dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'team-namespace'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
```

# Proposal

It could be nice to add `revision` and `repoURL` fields from GitGenerator such as

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: public-charts
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
  - git:
      repoURL: https://gitlab.org/entity/department/team/infra.git
      revision: HEAD  
      files:
      - path: 'components/charts/**/values.yaml'
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: team
      source:
        repoURL: '{{ .path.repoURL }}' # use same as git generator
        targetRevision: '{{ .path.revision }}' # use same as git generator
        path: '{{ .path.path }}'
        helm:
          valueFiles:
            - values.yaml
            - values.dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'team-namespace'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
```

We just need to pass to `generators/git.generateParamsFromGitFile` and  `generators/git.generateParamsFromApps` the revision and repoURL and do:

```golang
paramPath["repoURL"] = revision
paramPath["revision"] = revision
```

If you are ok I can work on this one ;)
