### ISSUE TITLE
LDAP auth don't register in v2.6.8

### ISSUE THREAD

**Issue by HugoRh** [argoproj/argo-cd#13865]
After a clean install with latest v2.6 version using
`kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.8/manifests/install.yaml`
and creation of an ingress for traefik as described in the [argocd documentation](https://argo-cd.readthedocs.io/en/release-2.6/operator-manual/ingress/#ingressroute-crd) 

All is working well except for authentication with Dex

My Dex setup does not seems to register, and ldap auth does not appear on the webui login screen.

I can still login with the built in admin account

**To Reproduce**
Here's the only customization I apply to the V2.6.8 deploy manifest

argocd-cm configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dexConfig: |-
    logger:
      level: debug
    connectors:
    - type: ldap
      name: ActiveDirectory
      id: ad
      config:
        host: "dc.org:636"
        insecureNoSSL: true
        insecureSkipVerify: true
        #bindDN: "$dex.ldap.bindDN"
        bindDN: CN=user,OU=System Accounts,OU=Accounts,DC=something,DC=else
        #bindPW: "$dex.ldap.bindPW"
        bindPW: Some_PWWD
        usernamePrompt: Username
        userSearch:
          baseDN: DC=something,DC=else
          filter: "(objectClass=user)"
          username: sAMAccountName
          idAttr: distinguishedName
          emailAttr: mail
          nameAttr: displayName
        groupSearch:
          baseDN: DC=something,DC=else
          filter: "(objectClass=group)"
          userMatchers:
          - userAttr: DN
            groupAttr: member
          nameAttr: cn
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  url: https://argocd.url.in.my.org
````

 argocd-cmd-params-cm configmap

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  applicationsetcontroller.log.format: json
  controller.log.format: json
  dexserver.disable.tls: "true"
  reposerver.log.format: json
  server.insecure: "true"
  server.log.format: json
```

argocd-rbac-cm

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, Admins, role:admin
    g, Users, role:read-only
    p, role:none, *, *, */*, deny
  policy.default: role:none
```

**Expected behavior**

Well, just the LDAP auth to work

**Version**

```shell
argocd-server: v2.6.8+674cf8d
  BuildDate: 2023-05-25T15:55:50Z
  GitCommit: 674cf8d6e2a8f06683fcc6d8ec0f880ec9c2779c
  GitTreeState: clean
  GoVersion: go1.19.7
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

Dex server logs
```
klog argocd-dex-server-75b9ff99d6-cc4zt                                 
Defaulted container "dex" out of: dex, copyutil (init)
time="2023-06-01T06:30:30Z" level=info msg="ArgoCD Dex Server is starting" built="2023-05-25T15:55:50Z" commit=674cf8d6e2a8f06683fcc6d8ec0f880ec9c2779c namespace=argocd version=v2.6.8+674cf8d
time="2023-06-01T06:30:30Z" level=info msg="Starting configmap/secret informers"
time="2023-06-01T06:30:30Z" level=info msg="Configmap/secret informer synced"
time="2023-06-01T06:30:30Z" level=info msg="0xc000367860 subscribed to settings updates"
time="2023-06-01T06:30:30Z" level=info msg="dex is not configured"
```

argocd server logs
```
klog argocd-server-79b787b9b5-8jkk4                                 
{"built":"2023-05-25T15:55:50Z","commit":"674cf8d6e2a8f06683fcc6d8ec0f880ec9c2779c","level":"info","msg":"ArgoCD API Server is starting","namespace":"argocd","port":8080,"time":"2023-06-01T06:30:28Z","version":"v2.6.8+674cf8d"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"Initialized admin mtime","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"configmap informer cancelled","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"secrets informer cancelled","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"argocd v2.6.8+674cf8d serving on port 8080 (url: https://argocd.url.in.my.org, tls: false, namespace: argocd, sso: false)","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"Enabled application namespace patterns: argocd","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"0xc0012f6b40 subscribed to settings updates","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"Starting rbac config informer","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"RBAC ConfigMap 'argocd-rbac-cm' added","time":"2023-06-01T06:30:28Z"}
{"level":"info","msg":"Notifying 1 settings subscribers: [0xc0012f6b40]","time":"2023-06-01T06:30:28Z"}
```

**Comment by HugoRh** [comment]
Well well well, not much more love for me , but it's a tribute to good READING :D 

So, if you guys land up here trying to understand why you have that "dex is not configured" message, here's two things you could check : 

- that the ```url``` parameter is defined ```argocd-cm``` configmap ( it's mentionned in the official doc )
- if you come from a blog that is a few month/ year  old on how to setup dex, pay attention to the name of the parameter , my mistake was that I used ```dexConfig``` instead of the ```dex.config``` ... here's to good doc reading :) 

I'll post below what worked for me ( if you need example of a working config, check below example) :

argocd-cm : 

- I changed the name of the config key that holds the dex config ( which I mention above )
- the ldap host port ( 636 didn't work, 389 is fine )
- I now use the secret ```dex.ldap.bindDN``` and ```dex.ldap.bindPW``` from the ```argocd-secret```

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |-
    connectors:
    - type: ldap
      name: ActiveDirectory
      id: ad
      config:
        host: "dc.org:389"
        insecureNoSSL: true
        insecureSkipVerify: true
        #bindDN: CN=user,OU=System Accounts,OU=Accounts,DC=something,DC=else
        #bindPW: Some_PWWD
        bindDN: "$dex.ldap.bindDN"
        bindPW: "$dex.ldap.bindPW"
        usernamePrompt: Username
        userSearch:
          baseDN: DC=something,DC=else
          filter: "(objectClass=user)"
          username: sAMAccountName
          idAttr: distinguishedName
          emailAttr: mail
          nameAttr: displayName
        groupSearch:
          baseDN: DC=something,DC=else
          filter: "(objectClass=group)"
          userMatchers:
          - userAttr: DN
            groupAttr: member
          nameAttr: cn
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  url: https://argocd.url.in.my.org
```

argocd-cmd-params-cm ( I ditched ```dexserver.disable.tls``` , for the rest only ```server.insecure: "true"``` is needed)
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  applicationsetcontroller.log.format: json
  controller.log.format: json
  reposerver.log.format: json
  server.insecure: "true"
  server.log.format: json
```

argocd-rbac-cm ( I had the name of the read only profile wrong replaced ```read-only``` with ```readonly```

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, Admins, role:admin
    g, Users, role:readonly
    p, role:none, *, *, */*, deny
  policy.default: role:none
```

There, it might help a little !

Cheers!!!
