### ISSUE TITLE
Unable to retrieve Chart.yaml dependencies from custom helm repository

### ISSUE THREAD

**Issue by avishayil** [argoproj/argo-cd#13867]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
````
rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template my-app --namespace  my-app --kube-version 1.25 --values secrets+age-import:///helm-secrets-private-keys/key.asc?custom-values.enc.yaml

Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: my-app
````
**To Reproduce**
````
app.yaml (argocd application)

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.asc?custom-values.enc.yaml
    path: environments/test/applications/my-app
    repoURL: git@github.mycorp.com:myorg/myrepo.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
````
````
environments/test/applications/my-app/Chart.yaml contents:

---
apiVersion: v2
name: my-app
version: 0.1.0
appVersion: 0.1.0
description: my-app
dependencies:
  - name: my-app
    version: 0.1.0
    repository: https://raw.github.mycorp.com/myorg/helm-charts/gh-pages
````

`https://raw.github.mycorp.com/myorg/helm-charts/gh-pages` is a connected helm repository from ArgoCD `Repositories`

**Expected behavior**

Argo should fetch the helm dependency as usual, according to the example at `https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency`

**Version**

```shell
{
    "Version": "v2.7.3+e7891b8.dirty",
    "BuildDate": "2023-05-24T15:05:34Z",
    "GitCommit": "e7891b899a35dca06ae94965ea5ae2a86b344848",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```
