### ISSUE TITLE
ServerSideApply breaks CreateNamespace

### ISSUE THREAD

**Issue by morey-tech** [argoproj/argo-cd#13874]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When `ServerSideApply` is enabled on a resource (e.g., a `ConfigMap` or `Deployment`) and the Application is using `CreateNamespace`, the sync will fail with `namespaces "<namespace>" not found`.

Based on [this thread](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1685621879077619) in the `#argo-cd` channel.

**To Reproduce**

Create new application using this spec:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'kustomize-guestbook'
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/argocd-example-apps/'
    path: general/kustomize-guestbook
    targetRevision: ssa-createnamespace-test
    kustomize:
      namespace: kustomize-guestbook
  destination:
    namespace: kustomize-guestbook
    name: kind
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

![Xnapper-2023-06-01-11 22 32](https://github.com/argoproj/argo-cd/assets/4213435/3fd28bfb-3a08-4427-a580-76e5407e71df)

**Expected behavior**

Without `ServerSideApply` on a resource, the sync creates the namespace and the resources without issue. I would expect the same here. Here's a working example (the [only difference is no SSA](https://github.com/morey-tech/argocd-example-apps/compare/main...ssa-createnamespace-test) on the deployment):

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'kustomize-guestbook'
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/argocd-example-apps/'
    path: general/kustomize-guestbook
    targetRevision: HEAD
  destination:
    namespace: kustomize-guestbook
    name: kind
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

![Xnapper-2023-06-01-11 38 40](https://github.com/argoproj/argo-cd/assets/4213435/edc3b242-90aa-423c-8515-bcaa7ae2a7b5)

**Version**

```shell
{
    "Version": "v2.7.2+cbee7e6.dirty",
    "BuildDate": "2023-05-12T13:43:26Z",
    "GitCommit": "cbee7e6011407ed2d1066c482db74e97e0cc6bdb",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by morey-tech** [comment]
@leoluz, is this expected behaviour with the implementation of https://github.com/argoproj/argo-cd/pull/9711?

**Comment by blakepettersson** [comment]
Does this work when adding `managedNamespaceMetadata`, like 

```yaml
  syncPolicy:
    automated:
      selfHeal: true
    managedNamespaceMetadata:
      labels: {}
      annotations: {}
    syncOptions:
      - CreateNamespace=true
```
