### ISSUE TITLE
ServiceAccount not updated if a namespace other than argocd is used

### ISSUE THREAD

**Issue by jba31** [argoproj/argo-cd#13873]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When we installed argocd on other namespace then clusterrolebinding for argocd-application-controller and clusterrolebinding for argocd-server not updated with it.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
   .... 
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
....
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd   <----------------
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      ....
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-server
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: argocd    <----------------
```

**To Reproduce**

```
kubectl apply -n <NEW_NS> -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.1/manifests/ha/install.yaml
```
or
```
kubectl apply -n <NEW_NS> -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.3/manifests/ha/install.yaml
```

**Expected behavior**

The ServiceAccounts namespace is set with the correct namespace.

**Version**

```shell
argocd: v2.7.1+5e54351
  BuildDate: 2023-05-02T16:54:25Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: clean
  GoVersion: go1.19.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.3+e7891b8.dirty
```
