### ISSUE TITLE
Sending notifications to multiple instances of the same service. #13866

### ISSUE THREAD

**Issue by ernestre** [argoproj/argo-cd#13906]
# Summary

Send notifications to multiple instances of the same service. For example multiple instances of grafana.

# Motivation

We have a case where we have multiple grafana instances deployed and we want to send argocd notifications to all of them. However, I can't anything in the docs on how to achieve this.

For example instead of this:
```yaml
//...
    service.grafana: |
      apiUrl: ${argocd_grafana_url}
      apiKey: ${argocd_grafana_key}
```
I want something similar to this:

```yaml
  notifiers:
    service.grafana-one: |
      apiUrl: ${argocd_grafana_url_one}
      apiKey: ${argocd_grafana_key_one}
    service.grafana-two: |
      apiUrl: ${argocd_grafana_url_two}
      apiKey: ${argocd_grafana_key_two}
    service.grafana-...: |
      apiUrl: ${argocd_grafana_url_...}
      apiKey: ${argocd_grafana_key_...}
```
