### ISSUE TITLE
ArgoCD 2.7.4 bug: ArgoCD not retreiving secret value referred to in argocd-cm

### ISSUE THREAD

**Issue by mbonica1990** [argoproj/argo-cd#13928]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

According to this documentation:
https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#alternative
I should be able to use the syntax `$<k8s_secret_name>:<a_key_in_that_k8s_secret>` to get a key from another secret in the cluster within `argocd-cm` (for example, when getting the OIDC creds for my identity provider).

This works fine in ArgoCD 2.7.3, and worked fine in 2.6.8, but it does not work in 2.7.4.

**To Reproduce**

Create a secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: another-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  ...
  oidc.auth0.ClientID: <client-secret-base64-encoded>
  oidc.auth0.clientSecret: <client-secret-base64-encoded>
  ...
  ```
  
 and refer to it in argocd-cm:
 
 ```
 apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  ...
  oidc.config: |
    name: Auth0
    clientID: $another-secret:oidc.auth0.ClientID
    clientSecret: $another-secret:oidc.auth0.clientSecret  
  ...
  ```

**Expected behavior**

ArgoCD sends the value of ` another-secret.oidc.auth0.ClientID` to the auth provider.

(Instead, it's just sending the string "another-secret.oidc.auth0.ClientID" as the client ID to the auth provider.

**Screenshots**

N/A

**Version**

argocd@argocd-application-controller-0:~$ argocd version
argocd: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T19:00:34Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64

**Logs**
N/A

**Comment by cjc7373** [comment]
This case is covered by a unit test and I don't see anything wrong. Does `argocd-server` emits any log saying `config referenced xxx, but key does not exist in secret`?

**Comment by jstewart612** [comment]
@cjc7373 yes it does for me as of this comment under an identical scenario

**Comment by jstewart612** [comment]
If I hit the "login with XXX" button, I get this:
 
 Failed to query provider "$argocd-oidc:issuer": parse "$argocd-oidc:issuer/.well-known/openid-configuration": first path segment in URL cannot contain colon

**Comment by jstewart612** [comment]
Looks the same as https://github.com/argoproj/argo-cd/issues/7786 ?

**Comment by jgwest** [comment]
Apparent dupe of #7786

**Comment by dfsdevops** [comment]
Anyone coming here thinking they did everything right and it is not working, try restarting the services. Thats what ultimately fixed this for me.

**Comment by hawkesn** [comment]
Anyone coming here thinking they did everything right and it is not working, also be sure to put the label on the secret:
```
app.kubernetes.io/part-of: argocd
```
And restarting the service worked for me

**Comment by MasterExecuson** [comment]
Anyone comming here with the `app.kubernetes.io/part-of: argocd` on the secret and still having issues, make sure the secret name used on the configMap is referenced on the secret label: 

```
app.kubernetes.io/name: <k8s_secret_name>
```

**Comment by aaaaahaaaaa** [comment]
I'm facing a similar issue with a secret provisioned via External Secrets. All the labels mentioned above are present and the notification controller restarted. But ArgoCD doesn't want to pick the secret...

```
config referenced '$slack-app:token', but key does not exist in secret
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-app:token
```

```yaml
apiVersion: v1
data:
  token: ...
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: ...
  creationTimestamp: "2025-07-14T10:57:55Z"
  labels:
    app.kubernetes.io/name: slack-app
    app.kubernetes.io/part-of: argocd
    reconcile.external-secrets.io/created-by: ed68a8410469770f20ebd85d097501ff62dd913c5e388b52947e2b91
    reconcile.external-secrets.io/managed: "true"
  name: slack-app
  namespace: argocd
  ownerReferences:
  - apiVersion: external-secrets.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: slack-app
    uid: 87d7a42a-c506-4cea-a2fa-b8163432a3fb
  resourceVersion: "1752490675753631024"
  uid: ad943292-88c3-409e-ad3e-0550aeba28e3
type: Opaque

```

**Comment by sohel-m** [comment]
Hi @aaaaahaaaaa 
I have the same issue, were you able to find the fix?
If yes please share the steps.
On my side I already had the needed labels "app.kubernetes.io/part-of: argocd" and I tried restarting the notification controller; without any luck :(

**Comment by aaaaahaaaaa** [comment]
@sohel-m Nope, I didn't find a fix...

**Comment by aaaaahaaaaa** [comment]
FYI, as I mentioned in the other issue [here](https://github.com/argoproj/argo-cd/issues/9958#issuecomment-3069615490) which is basically addressing the same problem, I'm pretty sure this used to work in the past and a regression was introduced at some point.

**Comment by Ajay-Chidambaram** [comment]
Hi everyone, just wondering if anyone is able to resolve this ? or is there any other open issue to track this 

I'm also facing the same issue, labels and rbac are updated still seeing the `key does not exist in secret` warning

**Comment by iborysiuk** [comment]
Hi everyone, I have the same issue when fetching secret via External Secrets. ArgoCD v3.1.0.

**Comment by o10s** [comment]
Same issue here with latest helm available at date

**Comment by Dwayne75** [comment]
adding app.kubernetes.io/part-of: argocd to the external secret I was using fixed it for me when getting
msg="config referenced '$argocd-external-oidc-secret:client-id', but key does not exist in secret"

**Comment by bmassemin** [comment]
I ran into the issue with the secrets related to the notifications service. Only the secrets loaded into the default notifications secret work, you can’t reference an external secret.
For the other services, I didn’t have any problem referencing an external secret using the `${secret_name}:{secret_key}` syntax.

**Comment by Thijmen** [comment]
Same still happening with 3.3.0. Strange thing is (I use it for authentication) that it 100% works, otherwise the auth process wont be able to send client id/secret to my SSO provider.

**Comment by meldaravaniel** [comment]
I've been playing with this all day and the only way I can get things to work is if I only use the secret for the clientSecret, not the clientID.  I think we're all expecting the secret inject to work everywhere...and for the life of me I can't get it to.  

For context, I'm using dex and google oidc, external secrets manager to make the secret.  I'm using some kustomize, so these are my patches on top of the default configs.  Here's what works for me:

argocd-cm:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  url: https://my-argocd.mydomain.com
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: <my-client-id-numbers>.apps.googleusercontent.com
        clientSecret: $dex-google-oidc:google-client-secret
      type: oidc
      id: google
      name: Google
```

externalsecret:

```
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-oidc-externalsecret
  labels: 
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/name: dex-google-oidc
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-clustersecretstore
  target:
    name: dex-google-oidc
    creationPolicy: Owner
  data:
  - secretKey: google-client-secret
    remoteRef:
      key: <secretstore-key>
      property: password
```

The secret that gets generated:

```
apiVersion: v1
data:
  google-client-secret: ...
kind: Secret
metadata:
  annotations:
    ...
  labels:
    app.kubernetes.io/name: dex-google-oidc
    app.kubernetes.io/part-of: argocd
    reconcile.external-secrets.io/created-by: ...
    reconcile.external-secrets.io/managed: "true"
  name: dex-google-oidc
  namespace: argocd
  ownerReferences:
  - apiVersion: external-secrets.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: google-oidc-externalsecret
    uid: ...
type: Opaque
```

Maybe it's only coded to look for a secret if the field is, itself a secret?  I dunno, man, but maybe this will help someone.
