### ISSUE TITLE
App in any namespace resourceActions Permission Denied

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#13922]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using app in any namespace and try to restart a deployment `Permission Denied` is raised

**To Reproduce**

- start e2e setup: `make start-e2e-local`
- Update argocd configmap to enable a user

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd-e2e
data:
  accounts.alice: apiKey,login
  application.resourceTrackingMethod: annotation
```
- Set alice password

```
./argocd account update-password --account alice --new-password password
```

- Create project and application:

```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: teamone
spec:
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: '*'
  sourceRepos:
    - '*'
  roles:
    - name: edit
      policies:
        - p, proj:teamone:edit, applications, get, teamone/*, allow
        - p, proj:teamone:edit, applications, list, teamone/*, allow
        - p, proj:teamone:edit, applications, create, teamone/*, allow
        - p, proj:teamone:edit, applications, action/*, teamone/*, allow
        - p, proj:teamone:edit, applications, sync, teamone/*, allow
      groups:
        - alice
  sourceNamespaces:
    - argocd-e2e-external
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-namespaced-restart
  namespace: argocd-e2e-external
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: teamone
  source:
    path: guestbook
    repoURL: https://github.com/speedfl/argocd-example-apps.git
    targetRevision: HEAD 
```

- Try to restart guetbook deployment

**Expected behavior**

Restart must be possible

**Screenshots**

N/A

**Version**

```shell
{
    "Version": "v2.7.4+a33baa3.dirty",
    "BuildDate": "2023-06-05T19:00:34Z",
    "GitCommit": "a33baa301fe61b899dc8bbad9e554efbc77e0991",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
time="2023-06-06T15:29:59Z" level=warning msg="user tried to action/apps/Deployment/restart application which they do not have access to: rpc error: code = PermissionDenied desc = permission denied: applications, action/apps/Deployment/restart, projectone/spark-history-server, sub: 000, iat: 2023-06-06T14:45:26Z" application=spark-history-server namespace=argocd project=projectone security=2
time="2023-06-06T15:29:59Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied" grpc.code=PermissionDenied grpc.method=RunResourceAction grpc.service=application.ApplicationService grpc.start_time="2023-06-06T15:29:59Z" grpc.time_ms=3.202 span.kind=server system=grpc
```

AppProject projectone

```
        - p, proj:projectone:admins, applications, actions/*, projectone/*, allow
```
