### ISSUE TITLE
v2.7.4 CMP regression: the plugin isn't called

### ISSUE THREAD

**Issue by farcaller** [argoproj/argo-cd#13940]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Starting v2.7.4 my CMP plugin is no longer being called.

**To Reproduce**

I have the following config configuration:

```yaml
apiVersion: v1
data:
  nix.conf: |
    build-users-group = nixbld
    sandbox = false
    experimental-features = nix-command flakes
    substituters = https://cache.nixos.org https://nixhelm.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixhelm.cachix.org-1:esqauAsR4opRF0UsGrA6H3gD21OrzMnBBYvJXeddjtY=
  passwd: |
    nix:x:999:30000:Nix build user 1:/home/nix:/bin/false
    root:x:0:0::/root:/bin/bash
  plugin.yaml: '{"apiVersion":"argoproj.io/v1alpha1","kind":"ConfigManagementPlugin","metadata":{"name":"nix-cmp-plugin"},"spec":{"discover":{"fileName":"flake.nix"},"generate":{"command":["sh","-c","cat
    result"]},"init":{"command":["sh","-c","export OUTPUT=\"${ARGOCD_ENV_NIX_OUTPUT:-kubernetesConfiguration}\"\necho
    -ne \"Building for $OUTPUT\\n\\n\"\nif [ \"$PARAM_VALUES\" != \"\" ]; then\n  echo
    \"$PARAM_VALUES\" > values.json\n  nix-shell -p git --run ''git add values.json''\nfi\nnix
    build \".#${OUTPUT}\"\n"]},"name":"nix-cmp-plugin","version":"v1.0"}}'
kind: ConfigMap
metadata:
  labels:
    argocd.argoproj.io/instance: cloudops-argocd
  name: nix-cmp-config
  namespace: argocd
```

(pretty-printed that is:)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: nix-cmp-plugin
spec:
  discover:
    fileName: flake.nix
  generate:
    command:
      - sh
      - '-c'
      - cat result
  init:
    command:
      - sh
      - '-c'
      - |
        export OUTPUT="${ARGOCD_ENV_NIX_OUTPUT:-kubernetesConfiguration}"
        echo -ne "Building for $OUTPUT\n\n"
        if [ "$PARAM_VALUES" != "" ]; then
          echo "$PARAM_VALUES" > values.json
          nix-shell -p git --run ''git add values.json''
        fi
        nix build ".#${OUTPUT}"
  name: nix-cmp-plugin
  version: v1.0
```

Starting from 2.7.4 the plugin doesn't seem to be called at all (I tried to add some verbose logging into `init.command` to no avail, also it hard refreshes too fast). The pipeline runs without errors but suggests all the resources should be removed.

**Expected behavior**

Expected the CMP work just as it was working in 2.7.3. Reverting argo to 2.7.3 makes it operational again.

**Version**

2.7.4 installed via helm.

**Logs**

No useful logs in repo server.

**Comment by farcaller** [comment]
Heh, I'm actually trying to build that one reverted right now 😄

**Comment by farcaller** [comment]
Yes, I can confirm that reverting #13360 (specifically the b3f0979e71b59a19dcad4a222cfec08f2ccb377b commit) fixes 2.7.4 for me.

**Comment by crenshaw-dev** [comment]
I wonder if we can avoid throwing out the bugfix-baby with the bug-bathwater. We should have fixed the docs instead of changing behavior.

**Comment by crenshaw-dev** [comment]
Reverting is safer, but I hate to lose the bugfix if it's an easy tweak to get it working again.

**Comment by farcaller** [comment]
is $ARGOCD_APP_SOURCE_PATH supposed to trickle down into the `discover.find.command`? It doesn't really make sense to me that a per-app plugin check will only test files on a repo level if you have a monorepo setup. I'm trying to refactor the abovementioned check into

```yaml
discover:
  find:
    command:
    - sh
    - -c
    - test -f "./$ARGOCD_APP_SOURCE_PATH/flake.nix" && echo OK
```
