### ISSUE TITLE
[helm chart] deploy online helm chart with local values.yaml

### ISSUE THREAD

**Issue by ozbillwang** [argoproj/argo-cd#13966]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

I'd like to deploy an online helm chart with local `values.yaml`
```
helm upgrade --install -n keycloak-bitnami  my-keycloak oci://registry-1.docker.io/bitnamicharts/keycloak -f values-dev.yaml
```
I have added repo in ArgoCD successfully
```
argocd repo add registry-1.docker.io --type helm --name registry-1.docker.io --enable-oci
```

But when create an application in ArgoCD, **I found there is no option to set the path, branch name and local values.yaml file** , it always reference the default `values.yaml` from the online helm chart.

```
project: default
source:
  repoURL: registry-1.docker.io
  targetRevision: 15.1.3
  chart: bitnamicharts/keycloak
destination:
  server: 'https://kubernetes.default.svc'
  namespace: keycloak-bitnami
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

If I try to add part of `helm` in source, it always failed

```
    helm:
      valueFiles:
        - values-dev.yaml
```
**To Reproduce**

```
project: default
source:
  repoURL: registry-1.docker.io
  targetRevision: 15.1.3
  chart: bitnamicharts/keycloak
  helm:
      valueFiles:
        - values-dev.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: keycloak-bitnami
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```
when create with above application in argocd, I got this error
>Unable to save changes: application spec for keycloak-bitnami is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = `helm template . --name-template keycloak-bitnami --namespace keycloak-bitnami --kube-version 1.25 --values /tmp/9d87d3ea-882b-4ed0-8500-466c4cac6feb/keycloak/values-dev.yaml --api-versions acme.cert-manager.io/v1 ... --include-crds` failed exit status 1: Error: open /tmp/9d87d3ea-882b-4ed0-8500-466c4cac6feb/keycloak/values-dev.yaml: **no such file or directory**

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd version
argocd: v2.2.0+6da92a8
  BuildDate: 2021-12-14T18:11:55Z
  GitCommit: 6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.12+41f54aa
  BuildDate: 2022-09-16T00:45:01Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```
