### ISSUE TITLE
Ignore Job annotation for batch.kubernetes.io/job-tracking

### ISSUE THREAD

**Issue by reinvantveer** [argoproj/argo-cd#14015]
**Describe the bug**

I'm deploying a Kong API Gateway as an Application from their official helm chart and I'm running into a Job diff I cannot seem to get rid of. I have a test running that requires all applications to be completely synced and the init Job for Kong keeps getting an annotation:

```
metadata:
  annotations:
        batch.kubernetes.io/job-tracking: ''
```
I've tried a couple of `ignoreDifferences` settings, both `jqPathExpressions` and `jsonPointers` but either my syntax is off or something isn't listening for this particular diff. I'm not sure.

Can anyone help me out with this one?

**To Reproduce**

The (truncated) Application spec:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: operators
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - kind: Job
      jqPathExpressions:
        - .metadata.annotations
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: "2.23.0"
```
I ignored the helm override settings here, because there's a boatload of 'em and I'm convinced they are irrelevant for the question.

**Version**

```
argocd: v2.7.2+cbee7e6
  BuildDate: 2023-05-12T14:06:49Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: clean
  GoVersion: go1.19.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.2+cbee7e6
  BuildDate: 2023-05-12T14:06:49Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: clean
  GoVersion: go1.19.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.12.0+gc9f554d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

Thanks!

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/9550733/af8d7e3d-c595-464d-822d-b47c671057c2)

**Logs**

Doesn't appear anything unusual from the logs, all messages from the controller are `info` level

```
time="2023-06-13T10:31:56Z" level=info msg="updated 'operators/kong' operation (phase: Running)"
time="2023-06-13T10:31:56Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:2.23.0,Prune:true,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{SyncOperationResource{Group:batch,Kind:Job,Name:kong-kong-init-migrations,Namespace:,},SyncOperationResource{Group:batch,Kind:Job,Name:kong-kong-pre-upgrade-migrations,Namespace:,},SyncOperationResource{Group:batch,Kind:Job,Name:kong-kong-post-upgrade-migrations,Namespace:,},},Source:nil,Manifests:[],SyncOptions:[CreateNamespace=true ServerSideApply=true RespectIgnoreDifferences=true],} { true} [] {5 nil}}" application=operators/kong```
