### ISSUE TITLE
Creating ApplicationSet with Argo CD cli gives error

### ISSUE THREAD

**Issue by christianh814** [argoproj/argo-cd#14026]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have an ApplicationSet that is giving me weird errors when I try and create it with the `argocd` CLI.

AppSet
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-go
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - overlay: eks
        appBranch: main
      - overlay: gke
        appBranch: main
  template:
    metadata:
      name: 'simple-go-{{overlay}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/christianh814/simple-go
        targetRevision: '{{appBranch}}'
        path: 'deploy/overlays/{{overlay}}'
      destination:
        name: '{{overlay}}-cluster'
        namespace: 'simple-go-{{overlay}}'
```

Command
```shell
$ argocd appset  create appset-simple-go.yaml
ApplicationSet 'simple-go' created
```

Error

```shell
$ argocd appset list
NAME       NAMESPACE  PROJECT  SYNCPOLICY  CONDITIONS                                                                                                                                                                                                REPO                                        PATH                         TARGET
simple-go  argocd     default  nil         [{ErrorOccurred error unmarshling decoded ElementsYaml error converting YAML to JSON: yaml: control characters are not allowed 2023-06-13 15:49:41 -0700 PDT True ApplicationGenerationFromParamsError}]  https://github.com/christianh814/simple-go  deploy/overlays/{{overlay}}  {{appBranch}}
```

This same YAML works when deploying via `kubectl create -f appset-simple-go.yaml`

**To Reproduce**

1. Login to your cluster with `argocd login`
2. Try and deploy the applicationset

**Expected behavior**

ApplicationSet gets created

**Version**

```shell
$ argocd version 
argocd: v2.7.2+cbee7e6
  BuildDate: 2023-05-12T14:06:49Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: clean
  GoVersion: go1.19.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.3+e7891b8.dirty
  BuildDate: 2023-05-24T15:05:34Z
  GitCommit: e7891b899a35dca06ae94965ea5ae2a86b344848
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```shell
$ argocd appset get simple-go
Name:               simple-go
Project:            default
Server:             {{overlay}}-cluster
Namespace:          simple-go-{{overlay}}
Repo:               https://github.com/christianh814/simple-go
Target:             {{appBranch}}
Path:               deploy/overlays/{{overlay}}
SyncPolicy:         Automated (Prune)

CONDITION            STATUS  MESSAGE                                                                                                         LAST TRANSITION
ErrorOccurred        True    error unmarshling decoded ElementsYaml error converting YAML to JSON: yaml: control characters are not allowed  2023-06-13 16:12:46 -0700 PDT
ParametersGenerated  False   error unmarshling decoded ElementsYaml error converting YAML to JSON: yaml: control characters are not allowed  2023-06-13 16:12:46 -0700 PDT
ResourcesUpToDate    False   error unmarshling decoded ElementsYaml error converting YAML to JSON: yaml: control characters are not allowed  2023-06-13 16:12:46 -0700 PDT
```
