### ISSUE TITLE
preservedFields doesn't work as expected in applicationSet

### ISSUE THREAD

**Issue by vl-kp** [argoproj/argo-cd#14027]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
preservedFields is expected to keep annotation as described in https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/

i want to use argocd application annotation to temporarily stop sync for some application for debugging/testing
After manually add annotations
```
argocd.argoproj.io/skip-reconcile: "true"
argocd.argoproj.io/sync-options: Prune=false
```
The auto-sync/selfHeal should be stopped and ignored by argocd, but actually it doesn't work, still revert by argocd

**To Reproduce**
use below applicationset
```
kind: ApplicationSet
metadata:
  name: infra-applications
spec:
  preservedFields:
    annotations: ["argocd.argoproj.io/sync-options", "argocd.argoproj.io/compare-options", "argocd.argoproj.io/skip-reconcile"]
  metadata:
    spec:
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
```
After the application has been generator, manually added below annotation to application in argocd UI and change replicas for the deployment, the argocd should ignore the changes
```
argocd.argoproj.io/skip-reconcile: "true"
argocd.argoproj.io/sync-options: Prune=false
```

**Expected behavior**
Argocd should ignore the changes on the application(deployment)

**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/128127889/e85a4172-f1af-4e44-a5c4-ac8eec76306c)

**Version**
v2.7.2+cbee7e6.
```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
