### ISSUE TITLE
Login not working after switching sso from dex to keycloak

### ISSUE THREAD

**Issue by svghadi** [argoproj/argo-cd#14038]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Whenever I switch sso from `dex` to `keycloak`, I am unable to login unless I restart the **argocd-server** deployment. 

**To Reproduce**

1. [Setup keycloak](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/)
2. Switch sso to keycloak by updating `argocd-cm` configmap
   ```yaml
   data:
     url: https://127.0.0.1:8080
     dex.config: ''
     oidc.config: |
       name: Keycloak
       issuer: http://127.0.0.1:30005/realms/master
       clientID: argocd
       clientSecret: $oidc.keycloak.clientSecret
       requestedScopes: ["openid", "profile", "email", "groups"]
   ```
3. Perform a login via UI

**Expected behavior**

Login should work without having to restart argocd-server deployment.

**Actual behavior**
Argocd is trying to query dex endpoint even though we have changed sso to keycloak. Upon restart this error message is not seen and login works as expected.

Error message in UI. 
```
Failed to query provider "https://127.0.0.1:8080/api/dex": Get "https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration": dial tcp: lookup argocd-dex-server: no such host
```

**Version**

```shell
latest/master
```

**Comment by svghadi** [comment]
I found similar issues related to sso config changes not reflecting in argocd unless we restart the deployments.
#13526
#12815

According to https://github.com/argoproj/argo-cd/issues/12221#issuecomment-1423453659, hot-reload of configmap is broken. This might be the reason changes are not updated in argocd.

**Comment by svghadi** [comment]
I did some digging and found that hot reload code for sso config changes is broken at 2 places

1. https://github.com/argoproj/argo-cd/blob/99d8024a2f8c2f786c774ec7bcc3b4d63e007860/server/server.go#L1049-L1050 On hot-reload, above section runs to re-register the routes with updated sso configurations however for some reason when the api calls are made, older value of ArgoCDServer object `a` is used to handle the incoming request resulting in failure to authenticate. 

2. The `a.sessionMgr` object of ArgoCDServer is never updated with new configurations during [hot reload](https://github.com/argoproj/argo-cd/blob/99d8024a2f8c2f786c774ec7bcc3b4d63e007860/server/server.go#L421-L508). sessionMgr object is used to [verify token](https://github.com/argoproj/argo-cd/blob/99d8024a2f8c2f786c774ec7bcc3b4d63e007860/util/session/sessionmanager.go#L507-L509) but since it is never updated, the token verification fails after a successful hot-reload.

**Comment by Nello-Angelo** [comment]
i have the same problem

**Comment by crenshaw-dev** [comment]
If it's a problem with hot-reloading, I'm guessing that a restart of the API server should resolve this.

**Comment by Nello-Angelo** [comment]
not resolve

**Comment by Nello-Angelo** [comment]
update docs for the latest version of keycloak with scrense

**Comment by svghadi** [comment]
Restarting the API server works for me.

@crenshaw-dev - I am try to come up with a fix for this issue. While debugging, I found that during hot-reload, after the new server object is created, we do not shutdown the older server object, causing the incoming HTTP traffic to be distributed amongst these server objects in an indeterministic way, which leads to such behaviours. Shouldn't the older server be shutdown/cleaned once new server is up?

**Comment by omar-khaled-mahmoud** [comment]
I have the same issue

**Comment by mycodeself** [comment]
We're facing the same issue trying to switch from dex server to internal OIDC for GitHub.

Basically we turn off dex server and configure OIDC in the CM

```yaml
oidc.config: |
  name: GitHub
  issuer: https://github.com
  clientID: $github-oauth2-creds:clientID
  cliClientID: $github-oauth2-creds:clientID
  clientSecret: $github-oauth2-creds:clientSecret
  requestedScopes: ["openid", "profile", "email", "read:org"]
```

The result, is a GET request to the issuer URL and the error `failed to query provider "https://github.com": 404 Not Found:` in the top of the page...

Tried restarting everything, using different issuer URL like https://github.com/login/oauth/authorize with no success...

any hint to get rid of dex in favor of internal OIDC?

---

Edit: After some research I think the issue is that for GitHub the issuer and the jwks url are different:

`issuer` must be `https://github.com` but the jwks url is https://github.com/login/oauth/.well-known/jwks.json, in the current implementation using coreos/go-oidc it assumes the jwks url is `$issuer/.well-known/jwks.json` and changing the issuer to `https://github.com/login/oauth/` also fails, as there is a validation that the issuer returned is equal to the issuer defined.

I believe, there should be a parameter in the `oidc.config` to allow setting different JWKs URL. wdyt?


Edit2: Related to https://github.com/argoproj/argo-cd/issues/11421
