### ISSUE TITLE
HPA Object metrics average type always out of sync

### ISSUE THREAD

**Issue by WFA-hhsieh** [argoproj/argo-cd#14035]
Checklist:

* [v ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [v ] I've included steps to reproduce the bug.
* [v ] I've pasted the output of `argocd version`.

**Describe the bug**
When manage HPA resource(Object metrics AverageValue type) in ArgoCD, ArgoCD always diffs with additional 'value' filed and always shows out of sync.

**To Reproduce**
Create autoscaling/v2 HPA resource with Object metrics
```
- type: Object
      object:
        describedObject:
          apiVersion: v1
          kind: Service
          name: rabbitmq
        metric:
          name: rabbitmq_celery_queue_unprocessed_messages
        target:
          type: AverageValue
          averageValue: 10
```

ArgoCD Diff
![image](https://github.com/argoproj/argo-cd/assets/91172474/73e57404-7f07-49e4-a27e-ee5ee1a4e762)

**Expected behavior**
ArgoCD should not diff the value filed when HPA metrics value type is average.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T15:24:49Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+5bcd846
```

**Logs**

```
Paste any relevant application logs here.
```
