### ISSUE TITLE
Only admin can see helm parameters

### ISSUE THREAD

**Issue by mick1627** [argoproj/argo-cd#14047]
**Describe the bug**

User does not see helm parameters of their applications even if they have all actions allow for their application

**To Reproduce**

I have a simple helm application => 

```yaml
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: NS
    name: cluster
  project: myproject
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: ./
    repoURL: >-
      https://XXXXXXXXXXXXXXXXXX.git
    targetRevision: HEAD
```

I have the following rbac rules : 

```yaml
    p, role:myrole, applications, *, myproject/*, allow
    p, role:myrole, clusters, get, *, allow
```

The users in role myrole can do all action on the application but the user does not see the helm parameters : 

![image](https://user-images.githubusercontent.com/36628449/234028137-86387e54-391a-4aa0-8220-ce072746df34.png)

Admin user of argocd can see the helm parameter :

![image](https://user-images.githubusercontent.com/36628449/234028485-0ac8ec29-93c1-4ae0-a121-8e64c8b33ee6.png)

**Expected behavior**

User should be able to see change helm parameter

![image](https://user-images.githubusercontent.com/36628449/234028485-0ac8ec29-93c1-4ae0-a121-8e64c8b33ee6.png)

**Version**

```shell
argocd-server: v2.6.9+3f1e7d4
  BuildDate: 2023-06-05T19:03:22Z
  GitCommit: 3f1e7d401e4a23bc2060b88aaef33e034bf9ec3e
  GitTreeState: clean
  GoVersion: go1.19.7
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1

```
