### ISSUE TITLE
Can't provide multi-line environment variable to plugin

### ISSUE THREAD

**Issue by AidanHilt** [argoproj/argo-cd#14091]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to pass helm values to a custom plugin, using an environment variable. When I check the environment variables, however, only the first line of the environment variable seems to be captured. 

**To Reproduce**
Apply the following files
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command: [sh, -c, find . -name Chart.yaml]
      init:
       command:
          - bash
          - "-c"
          - |
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo add prometheus https://prometheus-community.github.io/helm-charts
            helm repo add grafana https://grafana.github.io/helm-charts
            helm dependency build
      lockRepo: false
      generate:
        command:
          - bash
          - "-c"
          - |
            env > /home/argocd/vars.env && helm template $ARGOCD_ENV_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") . 
#| argocd-vault-plugin generate -s argocd:argocd-vault-plugin-credentials -
```
https://github.com/AidanHilt/PersonalMonorepo/blob/master/kubernetes/setup/configmap.yaml

```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-03-23T02:47:48Z"
  labels:
    kubernetes.io/metadata.name: monitoring
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts.git'
    path: charts/kube-prometheus-stack
    targetRevision: e58a02bf1f7bc99b0c155c1b301b94534ed49b90
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: APP_NAME
          value: kube-prometheus-stack
        - name: APP_NAMESPACE
          value: $ARGOCD_APP_NAMESPACE
        - name: HELM_VALUES
          value: |
            grafana:
              env:
                GF_SERVER_ROOT_URL: %(protocol)s://%(domain)s:%(http_port)s/grafana/
                GF_SERVE_FROM_SUB_PATH: <path:kv-v2/test/prometheus#subPath>
            prometheus:
              prometheusSpec:
                serviceMonitorSelectorNilUsesHelmValues: false
          #value: "grafana:\n  env:\n    GF_SERVER_ROOT_URL: %(protocol)s://%(domain)s:%(http_port)s/grafana/\n    GF_SERVE_FROM_SUB_PATH: <path:kv-v2/test/prometheus#subPath>\n prometheus:\n   prometheusSpec:\n     serviceMonitorSelectorNilUsesHelmValues: false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
https://github.com/AidanHilt/PersonalMonorepo/blob/master/kubernetes/argocd/applications/prometheus.yaml

```
extraContainers: 
    - name: avp-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v2.4.8
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      env:
        - name: HELM_CONFIG_HOME
          value: /home/argocd/helm-working-dir
        - name: HELM_CACHE_HOME
          value: /home/argocd/helm-working-dir
        - name: HELM_DATA_HOME
          value: /home/argocd/helm-working-dir
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: cmp-plugin
          subPath: plugin.yaml
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
  
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
    - name: tmp-dir
      emptyDir: {}
```
This is how I'm configuring the extra container in the values.yaml for ArgoCD. It's not currently checked into source control.

Once that's done, if you check the prometheus application, it will fail to sync. If you exec into the avp-helm container in the argocd-repo-server pod, in /home/argocd/vars.env, the value of ARGOCD_ENV_HELM_VALUES will be "grafana:"
**Expected behavior**

The value of the ARGOCD_ENV_HELM_VALUES variable is equal to its value in the prometheus application, and the template operation can successfully complete.

**Screenshots**
<img width="1343" alt="Screenshot 2023-06-15 at 11 18 53 PM" src="https://github.com/argoproj/argo-cd/assets/11202897/7b42861b-3dd5-406c-9c88-492c714c7319">

<img width="555" alt="Screenshot 2023-06-15 at 11 19 35 PM" src="https://github.com/argoproj/argo-cd/assets/11202897/5a71f934-b249-41c3-bfb9-ec8ec43a0f0c">

**Version**
```
argocd: v2.4.8+844f79e
  BuildDate: 2022-07-29T17:01:39Z
  GitCommit: 844f79eb9d8f3ab96d4ce6f8df211c6093a660ba
  GitTreeState: clean
  GoVersion: go1.18.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T19:00:34Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
