### ISSUE TITLE
Notification trigger to know when app went from `degraded` into `healthy` (and not from `progressing` into `healthy`)

### ISSUE THREAD

**Issue by luciano-buono** [argoproj/argo-cd#14106]
# Summary
Notification trigger know when app went from `degraded` into `healthy` (and not from `progressing` into `healthy`)

# Motivation

An application is deployed succesfully and is on-sync and healthy.
Then, for X reason, a pod enters into a CrashLoopBackoff and the Application health goes into Progressing for 10mins.
As the error persist, the health state goes into degraded.

There should be a way to be informed when this issue is resolved and health goes back to `healthy`

# Proposal

Create a new `notWhen` similar to `oncePer` that allows to filter a workflow of `PROGRESSING `-> `HEALTHY` as this would happen all the time an image tag is changed:

trigger.on-health-healthy: |
  - description: Application is back to healthy
    send:
    - app-health-healthy
    when: app.status.health.status == 'Healthy'
    notWhen: app.status.health.prev.status == 'Progressing'

**Comment by oterno** [comment]
I agree with this, but I think having the previous status available would be enough as the trigger could then be configured like this:
```yaml
trigger.on-health-healthy: |
  - description: Application is back to healthy
    send:
    - app-health-healthy
    when: app.status.health.status == 'Healthy' and app.status.health.prev.status != 'Progressing'
```
