### ISSUE TITLE
Race condition on Endpoints resulting to FailedToUpdateEndpoint events  

### ISSUE THREAD

**Issue by kmaounis** [argoproj/argo-cd#14102]
I am on version 2.7.3, I just noticed that i am  floaded with FailedToUpdateEndpoint errors. 
80% of my k8s event logs are now from these type of error.:

```
(x796 over 4d7h)       Warning   FailedToUpdateEndpoint    Endpoints/service-maintenance  Failed to update endpoint nl/service-maintenance: Operation cannot be fulfilled on endpoints "service-maintenance": the object has been modified; please apply your changes to the latest version and try again
```

We control this service via argocd and the following yaml

```
kind: Service
apiVersion: v1
metadata:
  name: service-maintenance
spec:
  type: ExternalName
  externalName: service-maintenance.global.svc.cluster.local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
```

Endpoints are generated by k8s (if not mistaken) and we do not control them via argocd:

```
Name:         service-maintenance
Namespace:    nl
Labels:       app.kubernetes.io/instance=namespace-nl
              environment=test
              service.kubernetes.io/headless=
Annotations:  <none>
Subsets:
  Addresses:          10.5.15.199,10.5.15.32, <....lots of IPS here>....10.5.9.20
  NotReadyAddresses:  <none>
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    <unset>  80    TCP

Events:
  Type     Reason                  Age                     From                 Message
  ----     ------                  ----                    ----                 -------
  Warning  FailedToUpdateEndpoint  3m40s (x804 over 4d8h)  endpoint-controller  Failed to update endpoint nl/service-maintenance: Operation cannot be fulfilled on endpoints "service-maintenance": the object has been modified; please apply your changes to the latest version and try again
````

Any idea on why this is happening? is this a race condition between k8s and argocd?
