### ISSUE TITLE
Mix up of targetRevisions in multi source app starting in 2.7.5

### ISSUE THREAD

**Issue by woehrl01** [argoproj/argo-cd#14108]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We experience that in multi source apps starting in 2.7.5, the targetRevision is mixed up across the sources:

Example multisource: 

```
sources:
  - repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.17.2
    helm:
      releaseName: istio-base
    chart: base
  - repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.17.2
    helm:
      releaseName: istio-istiod
      values: |
        pilot:
          autoscaleMin: 2
    chart: istiod
  - repoURL: 'https://cert-manager.github.io/aws-privateca-issuer'
    targetRevision: v1.2.4
```

we see the following error in the UI:    

```

rpc error: code = Unknown desc = `helm pull --destination /tmp/3bbb499c-1875-4dc6-b36d-10c6465141ce --version v1.2.4 --repo https://istio-release.storage.googleapis.com/charts istiod` failed exit status 1: Error: chart "istiod" version "v1.2.4" not found in https://istio-release.storage.googleapis.com/charts repository
```
    
 out of completeness and for further searches an alternative error looks like that   
    
 ```
 rpc error: code = Unknown desc = invalid revision 'ff2ca7291c435c934782189b18d775697ec9f148': improper constraint: ff2ca7291c435c934782189b18d775697ec9f148
 ```

This also results in endless loops of apps in the "Unknown" state.

**To Reproduce**

**Expected behavior**

Should not mix up the targetRevisions across the sources

**Screenshots**

<img width="849" alt="Bildschirmfoto 2023-06-17 um 18 11 41" src="https://github.com/argoproj/argo-cd/assets/2535856/0c9738ad-e61a-46c6-8b68-9cb641af06e7">

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

We didn't experience that error in 2.7.4. Downgrading fixed the issue.
