### ISSUE TITLE
Unable to retrieve Google groups

### ISSUE THREAD

**Issue by Guent4** [argoproj/argo-cd#14137]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to set up ArgoCD with Google auth, following the instructions [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-plus-google-groups-using-dex).  I encountered no issues setting up OIDC using Dex as I am able to log in using Google.  However, I cannot figure out why the extra steps to enable Google Groups support doesn’t seem to work.

**To Reproduce**

Followed the [instructions in the docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-plus-google-groups-using-dex).  Some specific config to note:
* Dex config in the `argocd-cm`:
    ```
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          redirectURI: https://*******/api/dex/callback
          clientID: ***************.apps.googleusercontent.com
          clientSecret: *****************
          serviceAccountFilePath: /tmp/oidc/googleAuth.json
          adminEmail: ***********
        type: oidc
        id: google
        name: Google
    ```

**Expected behavior**

When I go to the "User Info" tab on the ArgoCD UI, I should be able to see the Google Groups I am part of

**Screenshots**

N/A

**Version**
- v2.7.4 of ArgoCD container
- v2.36.0 of Dex container
- Note: CLI wasn't actually used as part of the setup so version shouldn't matter
    ```
    > argocd version
    argocd: v2.7.5+a2430af
      BuildDate: 2023-06-16T15:00:03Z
      GitCommit: a2430af1c356b283e5e3fc5bde1f5e2b5199f258
      GitTreeState: clean
      GoVersion: go1.19.10
      Compiler: gc
      Platform: linux/amd64
    ```

**Logs + other relevant notes**

* When I log in, I see the following log line:
    ```
    time="2023-06-20T16:01:10Z" level=info msg="login successful: connector \"google\", username=\"******\", preferred_username=\"\", email=\"********\", groups=[]"
    ```
* Even with the extra configuration, I am still able to log in using Google, I just don’t see the Google groups I’m a part of when I go to the “User Info” tab
* I have verified that the mounting of the serviceaccount key is correct and verified that the contents match what I expect.
* There are no errors in the pod logs that indicate something is incorrect.  To validate, I tried changing a different field to an invalid value and I did see errors.
* I tried pointing the `serviceAccountFilePath` to an invalid path, but didn’t see any errors because of the change.  This is what has me really confused because I would expect an error message.  Based on this, it makes me think that ArgoCD+Dex isn’t picking actually picking up on the `serviceAccountFilePath` field.

**Comment by Guent4** [comment]
Resolved the issue!

When following the instructions on https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/, I first started with [OpenID Connect using Dex](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-using-dex) section.  In that section, it has the code snippet:
```
data:
  url: https://argocd.example.com
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: XXXXXXXXXXXXX.apps.googleusercontent.com
        clientSecret: XXXXXXXXXXXXX
      type: oidc
      id: google
      name: Google
```
and then when I went to [OpenID Connect plus Google Groups using Dex](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-plus-google-groups-using-dex) section to add support for GSuite groups, there's a code snippet:
```
dex.config: |
  connectors:
  - config:
      redirectURI: https://argocd.example.com/api/dex/callback
      clientID: XXXXXXXXXXXXX.apps.googleusercontent.com
      clientSecret: XXXXXXXXXXXXX
      serviceAccountFilePath: /tmp/oidc/googleAuth.json
      adminEmail: admin-email@example.com
    type: google
    id: google
    name: Google
```
there's a change that's not clearly called out which is that the `type` field changed from `oidc` to `google`
