### ISSUE TITLE
ComparisonError while try to deploy k8s resource kind: APIService

### ISSUE THREAD

**Issue by 1337andre** [argoproj/argo-cd#1414]
testet with vesion v0.12.0

**Describe the bug**
CompareError while try to deploy k8s resource kind: APIService

**To Reproduce**
Deploy Application with source directory. 

in this directory i have this file:
```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app: metrics-server
    chart: metrics-server
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```

when argo try to deploy this resource
i go the following error from UI
```
ComparisonError
error: unable to decode "/dev/shm/063309308": no kind "APIService" is registered for version "apiregistration.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"
```

in my repo-server-log i find this
```
time="2019-04-09T12:04:55Z" level=warning msg="Failed to remarshal oject: no kind \"APIService\" is registered for version \"apiregistration.k8s.io/v1beta1\" in sch
eme \"k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28\""
```

**Expected behavior**
This kind should be able to deploy
