### ISSUE TITLE
couldn't find key applicationsetcontroller.policy in ConfigMap argocd/argocd-cmd-params-cm

### ISSUE THREAD

**Issue by SrDayne** [argoproj/argo-cd#14158]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When trying to install argocd from HA manifest(https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml) get error `couldn't find key applicationsetcontroller.policy in ConfigMap argocd/argocd-cmd-params-cm`

In  `argocd-applicationset-controller` Deployment there is no optional field regarding key `applicationsetcontroller.policy`:

```
- name: ARGOCD_APPLICATIONSET_CONTROLLER_POLICY
  valueFrom:
    configMapKeyRef:
      key: applicationsetcontroller.policy
      name: argocd-cmd-params-cm
```

And there is no such key in `argocd-cmd-params-cm` ConfigMap too:

```
apiVersion: v1
data:
  redis.server: argocd-redis-ha-haproxy:6379
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
```

That is the reason of the error.

**To Reproduce**

Try to deploy Argocd in HA mode from manifest https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

**Expected behavior**

Argocd deployed.

**Version**

```
  argocd: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:55:00Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  argocd-server: v2.8.0+8840929.dirty

```

**Logs**
There are no logs, only error event during deploy.
```
couldn't find key applicationsetcontroller.policy in ConfigMap argocd/argocd-cmd-params-cm
```
