### ISSUE TITLE
Helm Umbrella Chart does not work with recurse:true

### ISSUE THREAD

**Issue by CloudoguSiebels** [argoproj/argo-cd#14159]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a Helm Umbrella Chart and enabling `recurse`, Argo CD does not deploy any kubernetes resources.

**To Reproduce**

```
.
├── apps
│   └── nginx-helm-dependency
│       ├── Chart.yaml
│       └── values.yaml
└── argocd
    └── nginx-helm-dependency.yaml

3 directories, 3 files
```

```yaml
# argocd/nginx-helm-dependency.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-dependency
  namespace: argocd-production
spec:
  destination:
    namespace: argocd-production
    server: https://kubernetes.default.svc
  project: example-apps
  source:
    path: apps/nginx-helm-dependency
    repoURL: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/example-apps # same repo
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

```

```yaml
# apps/nginx-helm-dependency/Chart.yaml 
apiVersion: v2
version: 13.2.21
name: nginx
dependencies:
  - name: nginx
    version: 13.2.21
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami⏎  
```

```yaml
# apps/nginx-helm-dependency/values.yaml 
---
nginx:
  service:
    ports:
      http: 80
    nodePorts:
      http: 30026
service:
  type: "NodePort"
```

When using `recurse:true`, Argo CD does not create resources.
When removing the `recurse` option, Argo CD creates the resources as expected.

**Expected behavior**

ArgoCD deploys helm chart.

**Screenshots**

![Screenshot at 2023-06-21 14-52-53](https://github.com/argoproj/argo-cd/assets/135615817/fd112b41-55a9-40bf-a4db-65af8695351b)

**Version**

```shell
argocd: v2.7.6+00c914a
  BuildDate: 2023-06-20T21:18:20Z
  GitCommit: 00c914a948d9e8ad99be8bd82a368fbdeba12f88
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1

```

**Logs**

```
Paste any relevant application logs here.
```
none
