### ISSUE TITLE
Setting array values in spec.source.helm.parameters results in error

### ISSUE THREAD

**Issue by corkupine** [argoproj/argo-cd#14171]
**Describe the bug**

Configuring the `spec.source.helm.parameters` section in the application manifest like below results in `error: applications.argoproj.io "my-app" is invalid`:

```yaml
spec:
  destination:
    name: cluster
    namespace: my-app
  project: project
  source:
    helm:
      parameters:
      - name: first.second.third.events[0]
        value: firstevent
      - name: first.second.third.events[1]
        value: secondevent
      - name: first.second.third.events[2]
        value: thirdevent
      - name: first.second.third.events[3]
        value: fourthevent
```

**To Reproduce**

You can edit the application directly using kubectl to try this out

**Expected behavior**

The parameters are used in the application

**Version**

```shell
v2.5.0+b895da4
```
