### ISSUE TITLE
Matrix generator should accept more than two child generators

### ISSUE THREAD

**Issue by huynhsontung** [argoproj/argo-cd#14182]
# Summary

When working with ApplicationSet, I encountered a situation where I wish the matrix generator had supported more than two child generators. Like the current matrix generator, it should generate all possible parameter combinations for all child generators. This would allow the matrix generator to handle more complex combinations without having to use nested matrix generators.

# Motivation

For example, consider we have two clusters:
- cluster1
- cluster2

Given this Git folder structure:
- `argocd/app1/config.yaml`
- `argocd/app2/config.yaml`

The content of each `config.yaml` is:

```yaml
configs:
  - configName: config1
     custom: value1
  - configName: config2
     custom: value2
```

Now we want to combine all the above parameters using Git generator, List generator, and Cluster generator:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  goTemplate: true
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: <<URL>>
              revision: HEAD
              files:
                - path: argocd/*/config.yaml
          # list generator, 'child' #2
          - list:
              elements: []
              elementsYaml: "{{ .configs | toJson }}"
          # cluster generator, 'child' #3
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
```

The Matrix generator should output:

```yaml
# Some params are omitted for brevity
- name: cluster1
  path: argocd/app1/config.yaml
  configName: config1
  custom: value1
- name: cluster2
  path: argocd/app1/config.yaml
  configName: config1
  custom: value1
- name: cluster1
  path: argocd/app1/config.yaml
  configName: config2
  custom: value2
- name: cluster2
  path: argocd/app1/config.yaml
  configName: config2
  custom: value2
- name: cluster1
  path: argocd/app2/config.yaml
  configName: config1
  custom: value1
- name: cluster2
  path: argocd/app2/config.yaml
  configName: config1
  custom: value1
- name: cluster1
  path: argocd/app2/config.yaml
  configName: config2
  custom: value2
- name: cluster2
  path: argocd/app2/config.yaml
  configName: config2
  custom: value2
```

# Proposal

For template handling, when going through the child generators, the current generator should have access to the combined params of all the generators before it. Using the above example, List generator should have access to all Git params (like the current implementation), and the Cluster generator should have access to both Git and List params.
