### ISSUE TITLE
Referencing Manifests from Dockerhub Fails (Requires RepoURL)

### ISSUE THREAD

**Issue by Interaze** [argoproj/argo-cd#14195]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Argocd's Application logic is requiring me to fill out a repoURL, in addition to the chart. While this works for most registries, unfortunately, this doesn't work for DockerHub's helm registry. Dockerhub expects the pull command to have the entire url within the chart description.

i.e 
What I (Dockerhub) want (resolved via the application):
```helm pull oci://registry-1.docker.io/<username>/<chart> --version <version>```

Argo instead requires the repoURL to be inputted, which results in some variation where:
```helm pull --repo='oci://registry-1.docker.io' <username>/<chart> --version <version>```

I've attempted permutations of this to no success. If repoURL is allowed to be empty, I believe this would be an easy fix. If there's another way to solve this I'd sincerely appreciate it. Thanks!

**To Reproduce**

Try deploying an application that points to dockerhub's helm chart repository.

**Expected behavior**

When attempting to pull a dockerhub manifest, argocd requires the repoURL for the manifest. This is not (to my knowledge) supported by Dockerhub. 

**Screenshots**
N/A

**Version**

```shell
v2.7.6+00c914a.dirty

{
    "Version": "v2.7.6+00c914a.dirty",
    "BuildDate": "2023-06-20T20:51:13Z",
    "GitCommit": "00c914a948d9e8ad99be8bd82a368fbdeba12f88",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by blakepettersson** [comment]
Can you provide an `Application` manifest with the Helm chart you're trying to apply?

**Comment by Interaze** [comment]
Hi Blake. I appreciate the response. I moved over to GitLab's registry, so it isn't an issue for my anymore. The thing that baffles me is why I couldn't get it working for Dockerhub (maybe wasn't lucky enough). In reality it was probably my ArgoCD helm registry configuration. Unfortunately, I kinda lobotomized my example application reference into a helm dependency, so what I can do is share what made gitlab work and close the issue:

ArgoCD Helm Config
```
gitlab-oci-creds:
      url: 'registry.url' <--- no oci://prepend
      enableOCI: 'true'
      username: <user>
      password: <pass>
      
vcluster-repo:
      url: 'registry.<url>/path/without/chartname' <--- no oci:// prepend
      name: Registry
      type: helm
      enableOCI: 'true'
```

Helm Chart Reference Chart.yaml:
```
dependencies:
- name: <name>
  version: <version>
  repository: "oci://registry.<url>/path/<name>"
```
