### ISSUE TITLE
ArgoCD Range Processing Incorrect

### ISSUE THREAD

**Issue by SteveJ-IT** [argoproj/argo-cd#14221]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD does not process range correctly. When using the following Helm snippet (or range with a list):

```
{{- range $k, $v := .Values.NetworkPolicies }}
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: {{ $k }}
  namespace: {{ $k | default "default" }}
spec:
  selector: {{ $v.selector | default "all() "}}
...
```

With the following values:
```
"NetworkPolicies":
  "example":
    "selector": "global()"
  "example2":
    "selector": "global()"
```

Argo outputs the following:

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'calico-policies:projectcalico.org/NetworkPolicy:default/'
  labels:
    argocd.argoproj.io/instance: calico-policies
  name: null
  namespace: default
spec:
  selector: global()
```

This is because it does not get a value for $k. However, it does receive values for $v which is visible in the selector key. It also only outputs the last object in the range, when it should output two objects here due to range. Moreover, if you deploy this via Helm directly it works absolutely fine as expected.

**To Reproduce**

1. Deploy Helm Chart with the above snippet example. Any using a range works.
2. Provide a key and value type input.
3. Observe output.

**Expected behavior**

Range is processed correctly same as directly via Helm. In this case, the $k value is rendered correctly and two NetworkPolicies objects are applied.

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'calico-policies:projectcalico.org/NetworkPolicy:default/'
  labels:
    argocd.argoproj.io/instance: calico-policies
  name: example
  namespace: example
spec:
  selector: global()
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'calico-policies:projectcalico.org/NetworkPolicy:default/'
  labels:
    argocd.argoproj.io/instance: calico-policies
  name: example2
  namespace: example2
spec:
  selector: global()
```

**Screenshots**

**Version**

```shell
argocd: v2.7.6+00c914a.dirty
BuildDate: 2023-06-20T20:51:13Z
GitCommit: 00c914a948d9e8ad99be8bd82a368fbdeba12f88
GitTreeState: dirty
GoVersion: go1.19.10
Compiler: gc
Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
