### ISSUE TITLE
An application with child components may display healthy despite some error components.

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#14223]
**Describe the bug**

An application with child components may display healthy despite some error components.

**To Reproduce**

See screenshots.

Job is not part of desired manifests but created by the operator.

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: create-default-database
    app.kubernetes.io/instance: temporal-ec2-eks-dev
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.20.0
```

Parent instance

```
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  labels:
    app.kubernetes.io/instance: temporal-ec2-eks-dev
  name: temporal
  namespace: temporal
```

**Expected behavior**

The application should display unhealthy status.

**Screenshots**

<img width="1196" alt="Screenshot 2023-06-27 at 20 45 46" src="https://github.com/argoproj/argo-cd/assets/6813397/c3253f08-6445-46bb-8ffe-cca8a49d3566">

**Version**

```shell
argocd version
argocd: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T18:57:22Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.20.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T16:35:40Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.4 2022-03-28T23:12:45Z
  Helm Version: v3.8.2+g6e3701e
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

N/A
