### ISSUE TITLE
Create Job (2.8.0-rc1) deep copy bug when creating Job from Cronjob

### ISSUE THREAD

**Issue by otherguy** [argoproj/argo-cd#14232]
**Describe the bug**

Unfortunately, I found a small bug 🐞 with the new Create Job feature introduced in #12925.

When creating a `Job` from a `CronJob` with the new, built in `create-job` action, `metadata` from the `jobTemplate` is ignored.

The created job has only the `spec` copied, but not the `metadata`. See https://github.com/argoproj/argo-cd/blob/97906bb9302ae9e557947927df34dd1fe674fbd0/resource_customizations/batch/CronJob/actions/create-job/action.lua#L50

Already mentioned in the [original issue #4116](https://github.com/argoproj/argo-cd/issues/4116#issuecomment-1609724748).

**To Reproduce**

We rely on an annotation `pod.kubernetes.io/sidecars` on our jobs for correct termination (provided by [otherguy/k8s-controller-sidecars](https://github.com/otherguy/k8s-controller-sidecars)). This is applied to jobs via `jobTemplate` like so:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: testjob
  namespace: test
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            pod.kubernetes.io/sidecars: cloud-sql-proxy
        spec:
          containers:
            ...
```

**Expected behavior**

Metadata should also be copied to the created `Job`. [Kubernetes generated metadata](https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values) such as `creationTimestamp`, `deletionTimestamp`, `uid` and `resourceVersion` should of course be exempted from copying.

A safer option would probably be to only copy `.metadata.annotations` (except `.metadata.labels.argocd.argoproj.io/tracking-id`) and `.metadata.labels`.

![CleanShot 2023-06-27 at 18 04 51@2x](https://github.com/argoproj/argo-cd/assets/6072721/f0f99619-d373-47dc-822b-9b6e49678c79)

**Version**

* [v2.8.0-rc1](https://github.com/argoproj/argo-cd/releases/tag/v2.8.0-rc1)
