### ISSUE TITLE
Error with field managedNamespaceMetadata 

### ISSUE THREAD

**Issue by birnazarova2** [argoproj/argo-cd#14239]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Following this documentation:

https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#namespace-metadata

I tried to configure a managedNamespaceMetadata section for the ApplicationSet:

```
managedNamespaceMetadata:
  labels:
    istio-injection: enabled
```

but got an error:

```
error validating data: ValidationError(ApplicationSet.spec.template.spec.syncPolicy): unknown field "managedNamespaceMetadata" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.syncPolicy
```

I know that this feature was released in v2.6 and we already upgraded our ArgoCD to v2.6.1.

**To Reproduce**

1. In our application-set.yaml we have this configuration:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
spec:
  generators:
    - git:
        repoURL: https://github.com/XXX/argocd.git
        revision: main
        files:
          - path: "clusters/dev/**/app.yaml"
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: dev
      source:
        repoURL: 'https://github.com/XXX/argocd'
        path: 'clusters/dev/{{cluster.namespace}}'
        targetRevision: 'main'
        helm:
          valueFiles:
            - 'values.yaml'
      destination:
        namespace: '{{cluster.namespace}}'
        name: 'dev'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
        syncOptions:
          - CreateNamespace=true
```

2. The sync in ArgoCD fails with the error:  
```
error validating data: ValidationError(ApplicationSet.spec.template.spec.syncPolicy): unknown field "managedNamespaceMetadata" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.syncPolicy
```

**Expected behavior**

The sync is successful and the namespace is labeled with `istio-injection: enabled`. 

**Version**

`v2.6.1+3f143c9`

![Screenshot 2023-06-27 at 1 51 34 PM](https://github.com/argoproj/argo-cd/assets/95429884/3cb0c2c5-b41c-4073-a24c-b77bdc1a6382)

**Logs**

Only this error showed up:

```
error validating data: ValidationError(ApplicationSet.spec.template.spec.syncPolicy): unknown field "managedNamespaceMetadata" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.syncPolicy
```
