### ISSUE TITLE
What is the difference between `Prune` and `Prune Last`?

### ISSUE THREAD

**Issue by jeremyj563** [argoproj/argo-cd#14240]
Having some further clarification on this would be helpful. I'm specifically wondering what is the expected result when `syncPolicy.automated.prune=false` and `PruneLast=true`? For example:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - PruneLast=true
```

Additionally, what would be the advantage of specifying `true` for both settings?

_Similar question posted by @sunyeongchoi in https://github.com/argoproj/argo-cd/discussions/14037_
