### ISSUE TITLE
Multi source app can't combine helm and path

### ISSUE THREAD

**Issue by soostdijck** [argoproj/argo-cd#14254]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I combine a helm chart and another source with custom resources I get the error:
> `rpc error: code = Unknown desc = Manifest generation error (cached): multiple application sources defined: Helm,Directory`

**To Reproduce**

* Create a cluster in argocd with a label `environment=dev`
* Create a applicationset with something like this:

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trident
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  generators:
  - clusters:  
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster # select only "remote" clusters
        matchExpressions:
          - { key: disableplumbing, operator: NotIn, values: [ trident ] }
  #         - {key: environment, operator: In, values: [dev,prod]}

  goTemplate: true

  template:
    metadata:
      name: 'trident-{{ .name }}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"

    spec:
      project: plumbing
      destination:
        server: '{{ .server }}'
        namespace: trident
      info:
        - name: "Description"
          value: "Netapp Trident is a CSI storage driver for netapp volumes"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
          #- RespectIgnoreDifferences=true
          - CreateNamespace=true

      sources:
        # This repo is where the value files for the helm chart are
        - repoURL: https://gitlab.example.net/IaC/argo/eksa/argocd.git
          targetRevision: main
          ref: values

        # Install the helm chart with the approritate value files from the repo above
        - chart: trident-operator
          repoURL: https://netapp.github.io/trident-helm-chart
          targetRevision: 23.4.0
        
          directory:
            recurse: false

          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/plumbing-apps/trident/values-default.yaml
              - $values/plumbing-apps/trident/values-{{ .metadata.labels.environment }}.yaml

        # Repo with custom resources for each cluster and/or environment
        - repoURL: https://gitlab.example.net/IaC/argo/eksa/argocd.git
          targetRevision: main # for branch based CR's use {{ .metadata.labels.environment }}
          path: /plumbing-apps/trident/{{ .metadata.labels.environment }}
          ref: customresources
```
 
**Expected behavior**

I expect to install a helm chart with value files from `ref: values` as well as resources from `ref: customresources`
There is even a [example in the official documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/) that suggests that this should work

**Version**

```shell
argocd: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T23:26:55Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T23:26:55Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/amd64
  Kustomize Version: v5.0.3 2023-05-09T20:05:13Z
  Helm Version: v3.11.1+g293b50c
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
