### ISSUE TITLE
Applicationset controller produces unclear messages when templating applications with no spec.destination.namespace definition in namespace scoped appprojects

### ISSUE THREAD

**Issue by michaelkotelnikov** [argoproj/argo-cd#14284]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Applicationset controller produces unclear messages when templating applications with no spec.destination.namespace definition in namespace scoped appprojects.

The log generated in the applicationset controller looks like - 

```
time="2023-06-30T11:41:31Z" level=error msg="validation error found during application validation: application spec is invalid: InvalidSpecError: application destination {https://kubernetes.default.svc } is not permitted in project 'default'" applicationset=ebutz/mariadb-appset
```

There is no indication that the application creation failure was caused because of the missing namespace name in spec.template.spec.destination.namespace. The log only states the application can not be created on \<server\>. At first this message caused some confusion since the created appproject allows application creation on any cluster.

I figured the message looks like this because `spec.Destination.Namespace` is not populated in the next snippet -

```go
application destination {%s %s} is not permitted in project '%s'", spec.Destination.Server, spec.Destination.Namespace, spec.Project
```

Finding this snippet helped my troubleshoot the issue and resolve it. But I think the message can be more specific when `spec.Destination.Namespace` is missing to avoid the confusion at the first place.

**To Reproduce**

1. Create the next AppProject (Argocd is deployed in the `ebutz` namespace) -

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ebutz
  namespace: ebutz
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: ""
  destinations:
  - name: '*'
    namespace: ebutz
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
```

2. Create an applicationset with no spec.template.spec.destination.namespace defined, e.g -

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mariadb-appset
  namespace: ebutz
spec:
  generators:
  - git:
      repoURL: https://github.com/michaelkotelnikov/argocd-playground
      revision: master
      directories:
      - path: mariadb-resources/*
  template:
    metadata:
      name: 'mariadb-{{path.basename}}'
      namespace: ebutz
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelkotelnikov/argocd-playground.git
        targetRevision: master
        path: 'mariadb-resources/{{path.basename}}'
      destination:
        name: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
```

3. View the status of the applicationset -

```
$ kubectl get applicationset/mariadb-appset -o yaml -n ebutz
...
status:
  conditions:
  - lastTransitionTime: "2023-06-30T12:38:39Z"
    message: 'application spec is invalid: InvalidSpecError: application destination
      {https://kubernetes.default.svc } is not permitted in project
      ''ebutz'' (and 1 more)'
    reason: ApplicationValidationError
    status: "True"
    type: ErrorOccurred
...
```

4. View the applicationset controller log

```
time="2023-06-30T11:41:31Z" level=error msg="validation error found during application validation: application spec is invalid: InvalidSpecError: application destination {https://kubernetes.default.svc } is not permitted in project 'ebutz'" applicationset=ebutz/mariadb-appset
```

**Expected behavior**

A descriptive message that states a `namespace` is missing in the generated application definition. e.g -

```
time="2023-06-30T11:41:31Z" level=error msg="validation error found during application validation: application spec is invalid: InvalidSpecError: application destination is missing a namespace declaration in project 'ebutz'" applicationset=ebutz/mariadb-appset
```

**Version**

```shell
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T15:24:49Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+unknown
  BuildDate: 2023-04-03T17:35:00Z
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 1970-01-01T00:00:00Z
  Helm Version: v3.10.0+ge534a5d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
