### ISSUE TITLE
Parameter overrides not honored in multi-source helm/git setup

### ISSUE THREAD

**Issue by sgrissom-rxss** [argoproj/argo-cd#14296]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Parameter overrides do not appear to work when using multi-source setup with a Helm repo as one source and a git repo as the second source for value files.

I know multi-source is beta so this may just be a corner case not covered yet?

In the UI, the `Application` manifest contains the parameter override. Snippet:

```yaml
project: default
source:
  repoURL: registry-1.docker.io/bitnamicharts
  targetRevision: 15.0.2
  helm:
    valueFiles:
      - $values/path/to/my/values.yaml
    parameters:
      - name: replicaCount
        value: '3'
  chart: nginx
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
...
```

**To Reproduce**

- Create an `Application` with two sources:
  - Source 1 is a Helm chart. By default it has a `replicaCount=1`.
  - Source 2 is a git repo with `values.yaml` containing `replicaCount=2`.
- Issue command ` argocd app set <project> -p replicaCount=3`
- Verify `Application` manifest contains parameter override for `helm`.
- Note that parameter override is not reflected in number of deployed pods. 

**Expected behavior**

Expected: The deployed app has 3 replicas.
Actual: The deployed app has 2 replicas.

**Version**

```shell
argocd: v2.7.6+00c914a                                                                                                                                          │Handling connection for 8080
  BuildDate: 2023-06-20T21:18:20Z                                                                                                                               │Handling connection for 8080
  GitCommit: 00c914a948d9e8ad99be8bd82a368fbdeba12f88                                                                                                           │Handling connection for 8080
  GitTreeState: clean                                                                                                                                           │Handling connection for 8080
  GoVersion: go1.19.10                                                                                                                                          │Handling connection for 8080
  Compiler: gc                                                                                                                                                  │Handling connection for 8080
  Platform: darwin/arm64                                                                                                                                        │Handling connection for 8080
argocd-server: v2.7.6+00c914a.dirty                                                                                                                             │Handling connection for 8080
  BuildDate: 2023-06-20T20:51:13Z                                                                                                                               │Handling connection for 8080
  GitCommit: 00c914a948d9e8ad99be8bd82a368fbdeba12f88                                                                                                           │Handling connection for 8080
  GitTreeState: dirty                                                                                                                                           │Handling connection for 8080
  GoVersion: go1.19.10                                                                                                                                          │Handling connection for 8080
  Compiler: gc                                                                                                                                                  │Handling connection for 8080
  Platform: linux/arm64                                                                                                                                         │Handling connection for 8080
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z                                                                                                                │Handling connection for 8080
  Helm Version: v3.11.2+g912ebc1                                                                                                                                │Handling connection for 8080
  Kubectl Version: v0.24.2                                                                                                                                      │Handling connection for 8080
  Jsonnet Version: v0.19.1
```

**Logs**

The only relevant thing I could find was in the repo-server, which seems to indicate the HelmParameter is not honored.

```
time="2023-06-30T22:09:54Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:registry-1.docker.io/bitnamicharts,Path:,TargetRevision:15.0.2,Helm:&ApplicationSourceHelm{ValueFiles:[$values/path/to/my/values.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:nginx,Ref:,}/15.0.2"
```

**Comment by Keramblock** [comment]
You using source instead of sources? Also I do not see second repo with values

**Comment by sgrissom-rxss** [comment]
@Keramblock Good eye. I inadvertently chopped off some import pieces of that yaml, which may point to the underlying issue.

After deploying the multi-source app, this is the manifest rendered in the UI appears like this:

```yaml
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.0.2
    helm:
      valueFiles:
        - $values/path/to/my/values.yaml
    chart: nginx
  - repoURL: 'https://git.example.com/my/project.git'
    targetRevision: poc
    ref: values
```

Through the command line, a parameter is added to the app:
```bash
argocd app set argocd/my-app -p replicaCount=3
``` 

The resulting manifest in the UI:
```yaml
project: default
source:
  repoURL: registry-1.docker.io/bitnamicharts
  targetRevision: 15.0.2
  helm:
    valueFiles:
      - $values/appconfig/team-kirk/nginx/dev/values.yaml
    parameters:
      - name: replicaCount
        value: '3'
  chart: nginx
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.0.2
    helm:
      valueFiles:
        - $values/path/to/my/values.yaml
    chart: nginx
  - repoURL: 'https://git.example.com/my/project.git'
    targetRevision: poc
    ref: values
```

The result of adding a parameter to the application via the command line `argocd` is the generation of a `source` field utilizing values from existing `sources[0]`.
