### ISSUE TITLE
Failure to execute `helm template` when using `spec.source.helm.valuesObject`

### ISSUE THREAD

**Issue by asaf400** [argoproj/argo-cd#14334]
I have attempted to use the newly merged feature #11538,

I have an application that has used `spec.source.helm.values: |` as a string,
Upon redeploying argocd using the latest rc image which includes the merged PR [v2.8.0-rc1](https://github.com/argoproj/argo-cd/releases/tag/v2.8.0-rc1) (quay.io/argoproj/argocd:v2.8.0-rc1)
I have attempted to modify the application in-place using argocd ui, but changing `values: |` to `valuesObject` I have encountered an unexpected error:

```
Unable to save changes: application spec for openshift-console is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = Manifest generation error (cached): 
`helm template . --name-template openshift-console --namespace openshift-console --kube-version 1.23 --api-versions all.of.k8s/v0/apis.here --include-crds` failed exit status 1: 
Error: execution error at (openshift-console/templates/deployment.yaml:1:70): .Values.bridgeEnvironmentVariables.BRIDGE_BASE_ADDRESS is required. Use --debug flag to render out invalid YAML
```

The chart I've used is my own [helm for okd|openshift console deployment](https://github.com/asaf400/openshift-console-chart)
Within the chart's app deployment template I use this templating rule to enforce a required value:
```
{{- $name := .Values.bridgeEnvironmentVariables.BRIDGE_BASE_ADDRESS | required ".Values.bridgeEnvironmentVariables.BRIDGE_BASE_ADDRESS is required." -}}
```
https://github.com/asaf400/openshift-console-chart/blob/main/charts/console/templates/deployment.yaml#L1

It works fine with `values` as a a string, but failed on that line when using `valuesObject`
I tried digging into this PR to see what would cause this, but I can't see where potentially the issue would be..

For completeness, this is a sample of the values (already into the .values key):
```
        bridgeEnvironmentVariables:
          BRIDGE_BASE_ADDRESS: https://console.somedomain.here.dom
          BRIDGE_USER_AUTH_OIDC_CLIENT_ID: deface33-defa-cede-face-defacedeface
          BRIDGE_USER_AUTH_OIDC_ISSUER_URL: https://oauth.id.authproviderdomain.com/
        extraEnv:
          - name: BRIDGE_INACTIVITY_TIMEOUT
            value: "3600"
          - name: BRIDGE_CUSTOM_PRODUCT_NAME
            value: "Tab Title here"
        ingress:
          hosts:
            - host: console.somedomain.here.dom # value will be replaced by a patch
              paths:
                - path: /*
                  pathType: ImplementationSpecific
          sslRedirect: true
```

**Comment by blakepettersson** [comment]
I cannot repro this. When I apply the manifest below

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-asaf
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  project: default
  sources:
  - repoURL: https://github.com/asaf400/openshift-console-chart
    targetRevision: main
    path: charts/console
    helm:
      valuesObject:
        bridgeEnvironmentVariables:
          BRIDGE_BASE_ADDRESS: https://console.somedomain.here.dom
          BRIDGE_USER_AUTH_OIDC_CLIENT_ID: deface33-defa-cede-face-defacedeface
          BRIDGE_USER_AUTH_OIDC_ISSUER_URL: https://oauth.id.authproviderdomain.com/
        extraEnv:
          - name: BRIDGE_INACTIVITY_TIMEOUT
            value: "3600"
          - name: BRIDGE_CUSTOM_PRODUCT_NAME
            value: "Tab Title here"
        ingress:
          hosts:
            - host: console.somedomain.here.dom # value will be replaced by a patch
              paths:
                - path: /*
                  pathType: ImplementationSpecific
          sslRedirect: true
```

I get this 

<img width="1244" alt="Screenshot 2023-07-18 at 15 31 44" src="https://github.com/argoproj/argo-cd/assets/1227954/33eee42f-cef5-49cb-b6c9-7dabf325c77c">

I'll give it a shot when converting from `values` -> `valuesObject` to see if I get any different results.

**Comment by blakepettersson** [comment]
Nope, same result there.

**Comment by asaf400** [comment]
I actually revisited this Yesterday, I ran locally using updated master branch,
And I also couldn't reproduce it locally, but I copied the 100% same manifest from local, to running Argo CD instance on EKS cluster, and it happened again, using 2.8.0-rc4, and Today, I'm going to retry in EKS using current master branch docker image.

Something very odd is going on, since I tried it multiple different ways, copying the entire app k8s object,
copying just the values, in any test cast, the deployed version (2.8.0-rc4) is production an UNMARSH JSON error

**Comment by asaf400** [comment]
in my original message, I missed the ingress resource key:
```
      valuesObject:
        ingress:
          annotations:
            alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect",
              "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode":
              "HTTP_301"}}'
            alb.ingress.kubernetes.io/group.name: internal
            alb.ingress.kubernetes.io/healthcheck-path: /api/health
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
            alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
          className: alb
          enabled: true
          hosts:
          - host: console.i.unit.sh
            paths:
            - path: /*
              pathType: ImplementationSpecific
          sslRedirect: true
        oidcIdentityProvider: jumpcloud
        secret:
          create: false
        verbosity: 10
        ```
