### ISSUE TITLE
Multi Source: can't mix multiple remote helm charts

### ISSUE THREAD

**Issue by snakebyte85** [argoproj/argo-cd#14330]
I am trying the new multi source feature with ArgoCD v2.7.4

I am using an application like this:

```
sources:
  - repoURL: <remote-helm-repo-url>
    targetRevision: 1.14.0
    chart: chart1
 - repoURL: <remote-helm-repo-url>
    targetRevision: 1.17.0
    chart: chart2
```

The expected results would be having the resources of both `chart1` and `chart2`, but this is not happening. Only the resources of `chart2` (the last remote chart defined in the application) are rendered.

The documentation https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/ explicitly says that the manifests generated by multiples sources should be merged.

Maybe this is not supported if using multiple REMOTE helm charts?
