### ISSUE TITLE
Pod logs are displayed as line numbers

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-cd#14402]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have a pod that just prints out 1-160 but they are displayed as line numbers in the log viewer.

**To Reproduce**

The following is the pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: intentional-fail
spec:
  containers:
  - name: fail
    image: bash:4.4
    command: ["bash", "-c"]
    args:
    - |
      set -eu
      for i in {1..160}; do echo $i; done;
      exit 1

```

**Expected behavior**

The actual numbers printed out should also be in the log viewer.

**Screenshots**

![Screen Shot 2023-07-03 at 2 55 10 PM](https://github.com/argoproj/argo-cd/assets/4269898/727aae92-02b5-4846-91e1-9bde9ac4514d)
