### ISSUE TITLE
ArgoCD keeps trying to update unchanged DNSRecordSets

### ISSUE THREAD

**Issue by peter-tar** [argoproj/argo-cd#14426]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD tries updating DNSRecordSet (config-connector) resources (and keeps failing) even though there are no changes to the resource. 

The fact that it fails to sync in case of a genuine change is not unexpected. Similar problems have been discussed here: https://github.com/argoproj/argo-cd/issues/5882 and I think this PR will be useful as a workaround https://github.com/argoproj/gitops-engine/pull/526 .

However the real problem is that these DNSRecordSets aren't being changed. We don't change them. Argocd sees them as synced and green. There is nothing in the diff. If I force replace the resource (it makes the problem go away for a few days), there are no differences between the old and new resource except for a few computed fields (metadata.creationTimestamp, metadata.resourceVersion, metadata.uid).
We've been experiencing this problem for at least a couple of years.

**To Reproduce**

1. Create a DNSRecordSet resource using the following format:
```
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true # This has been added as a potential workaround/remedy, but it's not helping. We had the same problem without
  labels:
    app.kubernetes.io/instance: <omitted>
    app.kubernetes.io/name: <omitted>
    app.kubernetes.io/part-of: <omitted>
  name: dns-record-1
  namespace: development
spec:
  managedZoneRef:
    external: <omitted>
  name: <omitted>
  rrdatas:
    - <omitted>
  ttl: 300
  type: A
```
2. Let Argo apply it
3. Wait for a few days
4. Find your Argo Application failing to sync with the following error message
```
error when replacing "/dev/shm/3513087848": admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: annotation cnrm.cloud.google.com/state-into-spec is immutable (retried 5 times).
```
5. Force replace the resource and watch the problem go away
6. Wait for a few days
7. The sync fails again

**Expected behavior**

I would expect ArgoCD to not attempt updating an unchanged resource.

**Screenshots**

**Version**

```shell
argocd-server: v2.7.3+e7891b8.dirty
  BuildDate: 2023-05-24T15:52:17Z
  GitCommit: e7891b899a35dca06ae94965ea5ae2a86b344848
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v5.0.3 2023-05-09T20:05:13Z
  Helm Version: v3.12.0+gc9f554d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
error when replacing "/dev/shm/3513087848": admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: annotation cnrm.cloud.google.com/state-into-spec is immutable (retried 5 times).
```
