### ISSUE TITLE
diff for k8s secrets using CLI

### ISSUE THREAD

**Issue by marcb1** [argoproj/argo-cd#1442]
using argocd `v0.12.0+cd4bb25`, we have some kubernetes secrets in git in the form of a yaml files, for example a webhook secret:
```
apiVersion: v1
data:
  WEBHOOK_SECRET: test
kind: Secret
metadata:
  creationTimestamp: null
  name: mrmeeseeks-production
```

The web UI does not show any diffs on this, however running `argocd app [app name] diff --local=.`, shows a diff like so:
```
<   WEBHOOK_SECRET: '*********'
>   CERTIFICATE: test
```
Is there better way of doing this, either have the CLI tool ignore `****` secrets, or if there's a better way of managing secrets let me know. I realize having them in git is not ideal, but there are some secrets that are not private keys but just random strings.
