### ISSUE TITLE
CMP Sidecar plugin missing Chart.yaml on Helm pulled from OCI on multi source app

### ISSUE THREAD

**Issue by zs-ko** [argoproj/argo-cd#14459]
Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**
when using a multi source app with CMP and OCI repository i would expect the rendered helm output would be equal to a regular helm repo. 

Currently I have an application that uses multiple sources and a regular helm successfully integrated with AVP trough CMP, only difference is that this do not refrence a values file trough
ref and valuesfile

When i now need to pull a bitnami/mariadb chart trough OCI it seems that the output do not contain Chart.yaml or any other file.

**To Reproduce**
create a multi source application, refrence a value file from a git repo and use a OCI helm repository
create an CMP that triggers on Chart.yaml and values.yaml 
notice CMP is not able to find Chart.yaml on generate step

**Expected behavior**
CMP is able to render out Chart.yaml as it would on a regular helm repo

**Screenshots**
<img width="269" alt="image" src="https://github.com/argoproj/argo-cd/assets/123738040/b03f8a80-7ac5-46f3-9dfe-1a28853df6ea">

**Version**

```shell
2.7.7
```

**Logs**

```
time="2023-07-11T16:02:35Z" level=info msg="sh -c \"find . -name 'Chart.yaml' && find . -name 'values.yaml'\"" dir=/tmp/_cmp_server/5f0e587d-3cd9-4299-9259-89abfeb91c61/phpipam execID=24ffb
time="2023-07-11T16:02:35Z" level=info msg="sh -c \"find . -name 'Chart.yaml' && find . -name 'values.yaml'\"" dir=/tmp/_cmp_server/75059f66-4bfb-4476-8ab7-a45455bdf3b7/phpipam execID=2fcd4
time="2023-07-11T16:02:35Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=MatchRepository grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-07-11T16:02:35Z" grpc.time_ms=34.588 span.kind=server system=grpc
time="2023-07-11T16:02:35Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=MatchRepository grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-07-11T16:02:35Z" grpc.time_ms=41.618 span.kind=server system=grpc
time="2023-07-11T16:02:35Z" level=info msg="sh -c \"find . -name 'Chart.yaml' && find . -name 'values.yaml'\"" dir=/tmp/_cmp_server/7f5c687e-7039-47f4-bbaa-b40ff521e76a/phpipam execID=28e10
time="2023-07-11T16:02:35Z" level=info msg="sh -c \"find . -name 'Chart.yaml' && find . -name 'values.yaml'\"" dir=/tmp/_cmp_server/653b0870-5a43-4464-85d8-d8837af1cef2/phpipam execID=22acc
time="2023-07-11T16:02:35Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=MatchRepository grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-07-11T16:02:35Z" grpc.time_ms=39.83 span.kind=server system=grpc
time="2023-07-11T16:02:35Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=MatchRepository grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-07-11T16:02:35Z" grpc.time_ms=42.422 span.kind=server system=grpc
time="2023-07-11T16:02:35Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=GetParametersAnnouncement grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-07-11T16:02:35Z" grpc.time_ms=35.044 span.kind=server system=grpc
time="2023-07-11T16:02:35Z" level=info msg="Generating manifests with no request-level timeout"
time="2023-07-11T16:02:35Z" level=info msg="bash -c \"helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo \\\"$ARGOCD_ENV_HELM_VALUES\\\") --include-crds . |\\nargocd-vault-plugin generate -s vault-configuration -\\n\"" dir=/tmp/_cmp_server/b90804df-9ee2-432c-a185-69f72b42aa58/phpipam execID=7bba2
time="2023-07-11T16:02:35Z" level=warning msg="Plugin command returned zero output" command="{[bash -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo \"$ARGOCD_ENV_HELM_VALUES\") --include-crds . |\nargocd-vault-plugin generate -s vault-configuration -\n] []}" stderr="Error: Chart.yaml file is missing\n"
```

**Comment by crenshaw-dev** [comment]
As well as your CMP config

**Comment by zs-ko** [comment]
app.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpipam
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/privaterepo/coreservices.git
    targetRevision: HEAD
    path: phpipam
    ref: values
  - chart: bitnamicharts/mariadb
    repoURL: registry-1.docker.io
    targetRevision: 12.2.7
    helm:
      releaseName: mariadb
      valueFiles:
      - $values/phpipam/mariadb/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: phpipam
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

```

```
---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin-helm
spec:
  allowConcurrency: true
  discover:
    find:
      command:
        - sh
        - "-c"
        - find . -name 'Chart.yaml' && find . -name 'values.yaml'
  generate:
    command:
      - bash
      - "-c"
      - |
        helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") --include-crds . |
        argocd-vault-plugin generate -s vault-configuration -
  lockRepo: false
```
