### ISSUE TITLE
RollingSync strategy for multiple ApplicationSets

### ISSUE THREAD

**Issue by alexymantha** [argoproj/argo-cd#14458]
# Summary

Add a way to define a RollingSync strategy in one place and refer to it in different ApplicationSets

# Motivation

The RollingSync strategy for Progressive Sync requires the steps to be defined in the ApplicationSet. This leads to a lot of duplication because there are often common patterns for strategy, especially across a team's ApplicationSets. It would be a good QoL improvement if we could define the strategy in one place and refer to it in other ApplicationSets.

# Proposal

A CRD to define the strategy:
```
apiVersion: argoproj.io/v1alpha1
kind: RollingSyncStrategy
metadata:
  name: region-strategy
spec:
  steps:
    - matchExpressions:
      - key: region 
        operator: In
        values:
          - apac
    - matchExpressions:
      - key: region
        operator: In
        values:
          - emea
        maxUpdate: 10%
    - matchExpressions:
      - key: region
        operator: In
        values:
          - na-west
        maxUpdate: 100%

```

In the ApplicationSet, refer to the resource instead:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        region: apac
      - cluster: cluster2
        region: emea
      - cluster: cluster3 
        region: na-west
  strategy:
    type: RollingSync
    name: region-sync
```
