### ISSUE TITLE
Discrepancy in Helm repo server and CMP sidecar

### ISSUE THREAD

**Issue by hnajib-sym** [argoproj/argo-cd#14451]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

While using Config Management Plugin as a sidecar to repo server , there seems to be a discrepancy in helm registry command 

In the RepoServer the output of  ``` helm registry --help ```  is below  
```bash
kubectl exec -it argocd-repo-server-58796ddb9f-qdztx -n argocd  -- /bin/bash
Defaulted container "repo-server" out of: repo-server, cmp, copyutil (init)
argocd@argocd-repo-server-58796ddb9f-qdztx:~$ helm registry --help

This command consists of multiple subcommands to interact with registries.

Usage:
  helm registry [command]

Available Commands:
  login       login to a registry
  logout      logout from a registry

Flags:
  -h, --help   help for registry

Global Flags:
      --burst-limit int                 client-side default throttling limit (default 100)
      --debug                           enable verbose output
      --kube-apiserver string           the address and the port for the Kubernetes API server
      --kube-as-group stringArray       group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --kube-as-user string             username to impersonate for the operation
      --kube-ca-file string             the certificate authority file for the Kubernetes API server connection
      --kube-context string             name of the kubeconfig context to use
      --kube-insecure-skip-tls-verify   if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kube-tls-server-name string     server name to use for Kubernetes API server certificate validation. If it is not provided, the hostname used to contact the server is used
      --kube-token string               bearer token used for authentication
      --kubeconfig string               path to the kubeconfig file
  -n, --namespace string                namespace scope for this request
      --registry-config string          path to the registry config file (default "/helm-working-dir/registry/config.json")
      --repository-cache string         path to the file containing cached repository indexes (default "/helm-working-dir/repository")
      --repository-config string        path to the file containing repository names and URLs (default "/helm-working-dir/repositories.yaml")
```

while within the CMP side car , the output is different
```bash
kubectl exec -it argocd-repo-server-58796ddb9f-qdztx -n argocd -c cmp -- /bin/bash
argocd@argocd-repo-server-58796ddb9f-qdztx:~$ helm registry --help

This command consists of multiple subcommands to interact with registries.

Usage:
  helm registry [command]

Available Commands:
  login       login to a registry
  logout      logout from a registry

Flags:
  -h, --help   help for registry

Global Flags:
      --burst-limit int                 client-side default throttling limit (default 100)
      --debug                           enable verbose output
      --kube-apiserver string           the address and the port for the Kubernetes API server
      --kube-as-group stringArray       group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --kube-as-user string             username to impersonate for the operation
      --kube-ca-file string             the certificate authority file for the Kubernetes API server connection
      --kube-context string             name of the kubeconfig context to use
      --kube-insecure-skip-tls-verify   if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kube-tls-server-name string     server name to use for Kubernetes API server certificate validation. If it is not provided, the hostname used to contact the server is used
      --kube-token string               bearer token used for authentication
      --kubeconfig string               path to the kubeconfig file
  -n, --namespace string                namespace scope for this request
      --registry-config string          path to the registry config file (default "/home/argocd/.config/helm/registry/config.json")
      --repository-cache string         path to the file containing cached repository indexes (default "/home/argocd/.cache/helm/repository")
      --repository-config string        path to the file containing repository names and URLs (default "/home/argocd/.config/helm/repositories.yaml")
``` 

In reposerver helm is using  ```/helm-working-dir/registry/config.json``` to store credentials by default while in other hand cmp is using ```/home/argocd/.config/helm/registry/config.json```  despite using the very same helm verified using  sha1sum  

```bash
argocd@argocd-repo-server-58796ddb9f-qdztx:~$ sha1sum /usr/local/bin/helm
8eca0062947e6815deeaad2e551621b8337022bb  /usr/local/bin/helm
```

**To Reproduce**

Replace reposerver by the below yaml 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: argocd-repo-server
  namespace: argocd
  containers:
  - args:
    - /usr/local/bin/argocd-repo-server
    - --port=8081
    - --metrics-port=8084
    env:
    - name: ARGOCD_RECONCILIATION_TIMEOUT
      valueFrom:
        configMapKeyRef:
          key: timeout.reconciliation
          name: argocd-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_LOGFORMAT
      valueFrom:
        configMapKeyRef:
          key: reposerver.log.format
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_LOGLEVEL
      valueFrom:
        configMapKeyRef:
          key: reposerver.log.level
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_PARALLELISM_LIMIT
      valueFrom:
        configMapKeyRef:
          key: reposerver.parallelism.limit
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_DISABLE_TLS
      valueFrom:
        configMapKeyRef:
          key: reposerver.disable.tls
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_TLS_MIN_VERSION
      valueFrom:
        configMapKeyRef:
          key: reposerver.tls.minversion
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_TLS_MAX_VERSION
      valueFrom:
        configMapKeyRef:
          key: reposerver.tls.maxversion
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_TLS_CIPHERS
      valueFrom:
        configMapKeyRef:
          key: reposerver.tls.ciphers
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_CACHE_EXPIRATION
      valueFrom:
        configMapKeyRef:
          key: reposerver.repo.cache.expiration
          name: argocd-cmd-params-cm
          optional: true
    - name: REDIS_SERVER
      valueFrom:
        configMapKeyRef:
          key: redis.server
          name: argocd-cmd-params-cm
          optional: true
    - name: REDIS_COMPRESSION
      valueFrom:
        configMapKeyRef:
          key: redis.compression
          name: argocd-cmd-params-cm
          optional: true
    - name: REDISDB
      valueFrom:
        configMapKeyRef:
          key: redis.db
          name: argocd-cmd-params-cm
          optional: true
    - name: REDIS_USERNAME
      valueFrom:
        secretKeyRef:
          key: redis-username
          name: argocd-redis
          optional: true
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: redis-password
          name: argocd-redis
          optional: true
    - name: ARGOCD_DEFAULT_CACHE_EXPIRATION
      valueFrom:
        configMapKeyRef:
          key: reposerver.default.cache.expiration
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_OTLP_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: otlp.address
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_MAX_COMBINED_DIRECTORY_MANIFESTS_SIZE
      valueFrom:
        configMapKeyRef:
          key: reposerver.max.combined.directory.manifests.size
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_PLUGIN_TAR_EXCLUSIONS
      valueFrom:
        configMapKeyRef:
          key: reposerver.plugin.tar.exclusions
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_ALLOW_OUT_OF_BOUNDS_SYMLINKS
      valueFrom:
        configMapKeyRef:
          key: reposerver.allow.oob.symlinks
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_STREAMED_MANIFEST_MAX_TAR_SIZE
      valueFrom:
        configMapKeyRef:
          key: reposerver.streamed.manifest.max.tar.size
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_REPO_SERVER_STREAMED_MANIFEST_MAX_EXTRACTED_SIZE
      valueFrom:
        configMapKeyRef:
          key: reposerver.streamed.manifest.max.extracted.size
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_GIT_MODULES_ENABLED
      valueFrom:
        configMapKeyRef:
          key: reposerver.enable.git.submodule
          name: argocd-cmd-params-cm
          optional: true
    - name: HELM_CACHE_HOME
      value: /helm-working-dir
    - name: HELM_CONFIG_HOME
      value: /helm-working-dir
    - name: HELM_DATA_HOME
      value: /helm-working-dir
    image: quay.io/argoproj/argocd:v2.7.6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz?full=true
        port: metrics
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: repo-server
    ports:
    - containerPort: 8081
      name: repo-server
      protocol: TCP
    - containerPort: 8084
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: metrics
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - mountPath: /home/argocd/.config
      name: config
    - mountPath: /home/argocd/cmp-server/config/plugin.yaml
      name: argocd-cm
      subPath: plugin.yaml
    - mountPath: /app/config/ssh
      name: ssh-known-hosts
    - mountPath: /app/config/tls
      name: tls-certs
    - mountPath: /app/config/gpg/source
      name: gpg-keys
    - mountPath: /app/config/gpg/keys
      name: gpg-keyring
    - mountPath: /app/config/reposerver/tls
      name: argocd-repo-server-tls
    - mountPath: /helm-working-dir
      name: helm-working-dir
    - mountPath: /home/argocd/cmp-server/plugins
      name: plugins
    - mountPath: /tmp
      name: tmp
  - command:
    - /var/run/argocd/argocd-cmp-server
    image: quay.io/argoproj/argocd:v2.7.6
    imagePullPolicy: IfNotPresent
    name: cmp
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 999
    volumeMounts:
    - mountPath: /var/run/argocd
      name: var-files
    - mountPath: /home/argocd/cmp-server/plugins
      name: plugins
    - mountPath: /tmp
      name: cmp-tmp
    - mountPath: /home/argocd/cmp-server/config/plugin.yaml
      name: argocd-cm
      subPath: plugin.yaml
  initContainers:
  - command:
    - /bin/cp
    - -n
    - /usr/local/bin/argocd
    - /var/run/argocd/argocd-cmp-server
    image: quay.io/argoproj/argocd:v2.7.6
    imagePullPolicy: IfNotPresent
    name: copyutil
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - mountPath: /var/run/argocd
      name: var-files
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: argocd-repo-server
  serviceAccountName: argocd-repo-server
  volumes:
  - emptyDir: {}
    name: config
  - emptyDir: {}
    name: cmp-tmp
  - configMap:
      defaultMode: 420
      items:
      - key: plugin.yaml
        path: plugin.yaml
      name: argocd-cm
    name: argocd-cm
  - emptyDir: {}
    name: helm-working-dir
  - emptyDir: {}
    name: plugins
  - emptyDir: {}
    name: var-files
  - emptyDir: {}
    name: tmp
  - configMap:
      defaultMode: 420
      name: argocd-ssh-known-hosts-cm
    name: ssh-known-hosts
  - configMap:
      defaultMode: 420
      name: argocd-tls-certs-cm
    name: tls-certs
  - configMap:
      defaultMode: 420
      name: argocd-gpg-keys-cm
    name: gpg-keys
  - emptyDir: {}
    name: gpg-keyring
  - name: argocd-repo-server-tls
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
      - key: ca.crt
        path: ca.crt
      optional: true
      secretName: argocd-repo-server-tls
```

**Expected behavior**

Both the reposerver and the CMP sidecar should use the default helm registry credentials location ```/home/argocd/.config/helm/registry/config.json``` 

**Screenshots**

**Version**

```shell
argocd: v2.7.6+00c914a.dirty
  BuildDate: 2023-06-20T20:51:13Z
  GitCommit: 00c914a948d9e8ad99be8bd82a368fbdeba12f88
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
