### ISSUE TITLE
AppSet Matrix Generator Override not Working for Booleans

### ISSUE THREAD

**Issue by alexbde** [argoproj/argo-cd#14498]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using a matrix generator combining two git generators with go template activated, we experienced strange behavior regarding booleans. If you define a boolean and set it to `true` in one repository and like to override it with `false` in another repository, it is simply not working and the boolean stays `true`.

We're using this pattern as a standard way to define a default value in one repository and override it with stage-specific values in another repository. So this bug is pretty critical for us, especially because it produces unexpected behavior which is hard to indentify.

**To Reproduce**

Although we experienced the issue with the git generator, I was able to narrow it down to the following minimal example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements: # these values (should) take precedence over the values in the second generator
                - expectBooleanFalse: false
                  expectBooleanTrue: true
                  expectStringFalse: "false"
                  expectStringTrue: "true"
          - list:
              elements:
                - expectBooleanFalse: true
                  expectBooleanTrue: false
                  expectStringFalse: "true"
                  expectStringTrue: "false"
  goTemplate: true
  template:
    ...
    spec:
      source:
        ...
        helm:
          values: |
            {{ `{{ . | mustToPrettyJson }}` }}
        ...
```

Which generates the following application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  source:
    helm:
      values: |
        {
          "expectBooleanFalse": true, # <= unexpected behavior
          "expectBooleanTrue": true,
          "expectStringFalse": "false",
          "expectStringTrue": "true"
        }
    ...
```

As you can see, the string-typed value is overridden with `"false"` correctly. Inspite of this, the boolean-typed value states `false` unexpectedly.

**Expected behavior**

An application is generated with the Helm value `expectBooleanFalse` set to `false`, thus:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  source:
    helm:
      values: |
        {
          "expectBooleanFalse": false,
          "expectBooleanTrue": true,
          "expectStringFalse": "false",
          "expectStringTrue": "true"
        }
    ...
```

**Screenshots**

n/a

**Version**

```json
{
    "Version": "v2.7.7+4650bb2.dirty",
    "BuildDate": "2023-07-05T19:42:32Z",
    "GitCommit": "4650bb2817c3c81405f40cf77e93ef2b5fb275fb",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

n/a

**Possible Solution**

We noticed the same behavior in Helm templates using the `merge` function. Our solution in Helm is to use the `mergeOverwrite` function instead.

Diving into the implementation of the matrix generator, you can see the `mergo.Merge(&dst, src)` function is used: [applicationset/generators/matrix.go#L62-L67](https://github.com/argoproj/argo-cd/blob/v2.7.7/applicationset/generators/matrix.go#L62-L67). Luckily, [mergo provides a flag](https://github.com/imdario/mergo#usage), to enable override functionality. Using `mergo.Merge(&dst, src, mergo.WithOverride)` instead of the implementation above, should fix the issue.
