### ISSUE TITLE
ArgoCD progressive sync to allow removal of the application in specific order

### ISSUE THREAD

**Issue by rrachev** [argoproj/argo-cd#14505]
# Summary
Currently argocd progressive sync deploy generated applications based on the order that you specified in the applicationset configuration, but when you need to remove all the generated/deployed application it does not follow this order. It keep the argocd application (if it is also generated by the applicationset) and removes all other applications in parallel.

What change you think needs making.
It will be better to have possibility to overwrite/configure this behavior via argocd configuration and to provide specific order or to instruct argocd to follow the deployment order but in reverse order.
 
# Motivation
I noticed this behavior when some clusters need to be decommissioned. There are some dependencies between the kubernetes core services which were deployed on the clusters for example in following order:
- argocd and alb controller first
- then crossplane with its provider and provider configuration
- some CSI driver which use resources that crossplane
- application which use above mentioned services
When I tried to remove them via just removing the applicationset which generated them removal process stuck first on crossplane. Because argocd progressive sync remove them in parallel it removed the crossplane deployment before the actual  crossplane provider configuration and in this way it leave a resources which are with finalizers that wait the crossplane operator to remove them. When I remove all the resources next stuck was related to the argocd ingress resources which need alb controller but it was again removed before that.

Please give examples of your use case, e.g. when would you use this.
This improvement will be helpful in above mentioned situations and will make for example the decommission process much easier and smooth.

# Proposal
It will be good to allow the users to specify if they want all the apps to be removed in parallel (current approach), to specify their own order which could be different from the deployment order or to use the deployment order but in reverse.
 
How do you think this should be implemented?

**Comment by rrachev** [comment]
Hello

Are there any update, movement on the current issue?

**Comment by crenshaw-dev** [comment]
@rrachev I think I'd be in favor of this feature. Do you want to sketch out how the spec might look? Are you up for writing a PR?

**Comment by rrachev** [comment]
As I mentioned in the description of the issue it will be to have possibility to overwrite/configure this behavior via argocd configuration and to provide specific order or to instruct argocd to follow the deployment order but in reverse order

Here is example if we want to use current deletion strategy to remove everything in parallel and to keep the argocd at the end:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pricelist
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - srv: config
        path: applicationsets/rollingsync/apps/pricelist-config
      - srv: db
        path: applicationsets/rollingsync/apps/pricelist-db
      - srv: frontend
        path: applicationsets/rollingsync/apps/pricelist-frontend
  strategy:
    type: RollingSync
### Deletion configuration ###
    deletionSyncStrategy: "default"  # available options to be default/reverse/custom
### Deletion configuration ###
    rollingSync:
      steps:
        - matchExpressions:
            - key: pricelist-component # the "key" is based on the label (below as "pricelist-component: {{srv}}")
              operator: In
              values:
                - config
          #maxUpdate: 100%  # if undefined, all applications matched are updated together (default is 100%)
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - db
          #maxUpdate: 0      # if 0, no matched applications will be updated
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - frontend
          #maxUpdate: 10%    # all application matched are rollout no more than the percentage indicates
  template:
    metadata:
      name: 'pricelist-{{srv}}'
      labels:
        pricelist-component: '{{srv}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: pricelist
```

Example if we want to use same deletion strategy as we have for the deployment but in reverse order:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pricelist
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - srv: config
        path: applicationsets/rollingsync/apps/pricelist-config
      - srv: db
        path: applicationsets/rollingsync/apps/pricelist-db
      - srv: frontend
        path: applicationsets/rollingsync/apps/pricelist-frontend
  strategy:
    type: RollingSync
### Deletion configuration ###
    deletionSyncStrategy: "reverse"  # available options to be default/reverse/custom
### Deletion configuration ###
    rollingSync:
      steps:
        - matchExpressions:
            - key: pricelist-component # the "key" is based on the label (below as "pricelist-component: {{srv}}")
              operator: In
              values:
                - config
          #maxUpdate: 100%  # if undefined, all applications matched are updated together (default is 100%)
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - db
          #maxUpdate: 0      # if 0, no matched applications will be updated
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - frontend
          #maxUpdate: 10%    # all application matched are rollout no more than the percentage indicates
  template:
    metadata:
      name: 'pricelist-{{srv}}'
      labels:
        pricelist-component: '{{srv}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: pricelist
```

And example if we want to use custom/different deletion strategy:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pricelist
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - srv: config
        path: applicationsets/rollingsync/apps/pricelist-config
      - srv: db
        path: applicationsets/rollingsync/apps/pricelist-db
      - srv: frontend
        path: applicationsets/rollingsync/apps/pricelist-frontend
  strategy:
    type: RollingSync
### Deletion configuration ###
    deletionSyncStrategy: "custom"  # available options to be default/reverse/custom
    deletionSync:
      steps:
        - matchExpressions:
            - key: pricelist-component # the "key" is based on the label (below as "pricelist-component: {{srv}}")
              operator: In
              values:
                - config
          #maxUpdate: 100%  # if undefined, all applications matched are updated together (default is 100%)
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - frontend
          #maxUpdate: 10%    # all application matched are rollout no more than the percentage indicates
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - db
          #maxUpdate: 0      # if 0, no matched applications will be updated
### Deletion configuration ###
    rollingSync:
      steps:
        - matchExpressions:
            - key: pricelist-component # the "key" is based on the label (below as "pricelist-component: {{srv}}")
              operator: In
              values:
                - config
          #maxUpdate: 100%  # if undefined, all applications matched are updated together (default is 100%)
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - db
          #maxUpdate: 0      # if 0, no matched applications will be updated
        - matchExpressions:
            - key: pricelist-component
              operator: In
              values:
                - frontend
          #maxUpdate: 10%    # all application matched are rollout no more than the percentage indicates
  template:
    metadata:
      name: 'pricelist-{{srv}}'
      labels:
        pricelist-component: '{{srv}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: pricelist
```
