### ISSUE TITLE
Conflict for "branch" parameter when using ApplicationSet SCM+PR generators

### ISSUE THREAD

**Issue by joshuabaird** [argoproj/argo-cd#14556]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When using the SCM and PR _ApplicationSet_ generators, you are unable to use the `{{ branch }}` parameter in a template since this key exists in both the SCM and PR generators -- and the merge fails:

```
error="failed to combine string maps with merging params for the matrix generator: found duplicate key branch with different value"
```

**To Reproduce**

Create an _ApplicationSet_ that uses both the SCM and PR generators, and then tries to access `branch` in the template spec:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sandbox-applications-preview
spec:
  generators:
    - matrix:
        generators:
        - matrix:
            generators:
            - scmProvider:
                pathParamPrefix: scm
                cloneProtocol: https
                github:
                  organization: my-inc
                  allBranches: false
                  tokenRef:
                    secretName: my-inc
                    key: password
                filters:
                  - labelMatch: kubernetes-sandbox
                  - pathsExist: [.platform/manifests]
            - clusters:
                selector:
                  matchLabels:
                    argocd.argoproj.io/secret-type: cluster
                    my.io/environment: sandbox
        - pullRequest:
            github:
              owner: my-inc
              repo: '{{ .repository }}'
              tokenRef:
                secretName: my-inc
                key: password
              labels:
              - preview
            requeueAfterSeconds: 60

  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: '{{ repository }}-preview-{{ number }}-{{ name }}'
    spec:
      source:
        repoURL: '{{ url }}' 
        targetRevision: '{{ .branch }}' # from scmProvider AND PR generator
        path: '.platform/manifests/overlays/preview'
        kustomize:
          namespace: '{{ repository }}-preview-{{ number }}'
          commonAnnotations:
            app/hostname: '{{ repository }}-{{ number }}.preview.dev.my.io'
      project: default
      destination:
        server: '{{ server }}' 
      syncPolicy:
        automated: 
          prune: false 
          allowEmpty: false
          selfHeal: false 
        syncOptions:
          - ServerSideApply=false
          - FailOnSharedResource=false
          - CreateNamespace=false
```

Experience this error:

```
error="failed to combine string maps with merging params for the matrix generator: found duplicate key branch with different value"
```

If you enable Go Templates, you don't get the above error, but `{{ branch }}` always returns the value from the SCM provider (not the PR generator -- which is desired in this scenario).  This is because the logic for merging is different when using Go Templates.

**Expected behavior**

I would expect to be able to state from which Generator I want to source the parameter from (eg, `pr.Branch`).  After discussing with @crenshaw-dev, here are a few viable options:

* per-appset order option (works for all N=2 matrices) [[link](https://github.com/argoproj/argo-cd/blob/a57786657bc26f66e55fb30b66463fe18625459d/applicationset/generators/matrix.go#L62)]
* per-matrix order option (more verbose, but works for all matrices)
* per-child-generator prefix (works for all matrices, a bit more clear/explicit maybe)

**Version**

2.7.7
