### ISSUE TITLE
path not supported when using ref with multiple sources

### ISSUE THREAD

**Issue by axel7083** [argoproj/argo-cd#14567]
**Describe the bug**

- considering git repository with a file located at `content/hello/helm-values.yaml`

When using `path`, with a ref defined, the ref is not pointing to the path. It is still reference to the root of the source.
The following would give an error. 

```yaml
      - repoURL: <helm-repo>
        targetRevision: <rev>
        chart: <chart>
        helm:
          valueFiles:
            - $values/helm-values.yaml
      - repoURL: <git>
        targetRevision: HEAD
        ref: values
        path: content/hello
```

To fix it, we would have to use `$values/content/hello/helm-values.yaml`.

**Version**

```shell
argocd: v2.7.6+00c914a.dirty
  BuildDate: 2023-06-20T20:51:13Z
  GitCommit: 00c914a948d9e8ad99be8bd82a368fbdeba12f88
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```
