### ISSUE TITLE
App of apps drifts out of sync immediately after syncing, losing ignoreMissingValueFiles and selfHeal parameters

### ISSUE THREAD

**Issue by jessebye** [argoproj/argo-cd#14591]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We use an app-of-apps approach with a helm chart that creates multiple Argo applications. After syncing the application for the helm chart, we have observed that it immediately goes out of sync. When it goes out of sync, two particular parameters are missing from most (but not always all) of the child apps.

The parameters in question are `helm.ignoreMissingValueFiles` and `automated.selfHeal`.

If we re-sync the parent app, it will momentarily show "Synced", but a few moments later shows "Out of Sync" again. Showing the diff reveals one of the parameters missing, or both.

See logs below, where the app is synced one minute and goes out of sync the next minute with no human input. For some reason, the changes applied to the helm and automated parameters don't "stick" and get reverted by ArgoCD after it syncs.

**To Reproduce**

Use an app-of-apps pattern with a parent helm chart app. The parent chart should template one or more ArgoCD applications that use the `helm.ignoreMissingValueFiles` and `automated.selfHeal` parameters. Here's an excerpt from the chart we use:

```
{{- range .Values.services }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $namespace }}-{{ .name }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'app={{ $registryUrl }}/app/{{ .name }}:{{ .tag }},dev={{ $registryUrl }}/dev/{{ .name }}:{{ .tag }}'
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/dev.update-strategy: digest
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: applications
  source:
    repoURL: https://github.com/{{ $githubOrg }}/{{ .name }}.git
    targetRevision: {{ .ref }}
    path: infra/helm/{{ .name }}
    helm:
      valueFiles:
      - values.{{ $environment }}.yaml
      ignoreMissingValueFiles: true
      values: |
        cluster: {{ $cluster }}
        environment: {{ $environment }}
        global:
          cluster: {{ $cluster }}
          environment: {{ $environment }}
        image:
          tag: {{ .tag }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - PrunePropagationPolicy=background
{{- end }}
```

After syncing, observe that the parent app becomes out of sync and stops correctly applying the parameters.

**Expected behavior**

The parameters are applied correctly and the parent app stays in sync (since nothing should be changing).

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/8467862/2d8d30f7-a112-40d1-984e-3ddccdfa7dd6)
![image](https://github.com/argoproj/argo-cd/assets/8467862/7a60d128-9206-4cdb-87fa-d15d4a3e2989)

**Version**

```shell
argocd: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T19:42:32Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64

```

**Logs**

```
time="2023-07-18T23:55:10Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd/weary-slug
time="2023-07-18T23:55:10Z" level=info msg="Updated sync status: OutOfSync -> Synced" application=weary-slug dest-namespace=weary-slug dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2023-07-18T23:55:10Z" level=info msg="Update successful" application=argocd/weary-slug
time="2023-07-18T23:55:10Z" level=info msg="Reconciliation completed" application=argocd/weary-slug dedup_ms=0 dest-name= dest-namespace=weary-slug dest-server="https://kubernetes.default.svc" diff_ms=145 fields.level=2 git_ms=14 health_ms=0 live_ms=12 settings_ms=0 sync_ms=0 time_ms=312
time="2023-07-18T23:56:49Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=argocd/weary-slug
time="2023-07-18T23:56:49Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: weary-slug)" application=argocd/weary-slug
time="2023-07-18T23:56:49Z" level=info msg="getRepoObjs stats" application=argocd/weary-slug build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=13 unmarshal_ms=12 version_ms=0
time="2023-07-18T23:56:50Z" level=info msg="Skipping auto-sync: most recent sync already to 102b3a58fb9274cd4b0c7b40990b7dc8fe4e61a6" application=argocd/weary-slug
time="2023-07-18T23:56:50Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=weary-slug dest-namespace=weary-slug dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2023-07-18T23:56:50Z" level=info msg="Update successful" application=argocd/weary-slug
time="2023-07-18T23:56:50Z" level=info msg="Reconciliation completed" application=argocd/weary-slug dedup_ms=0 dest-name= dest-namespace=weary-slug dest-server="https://kubernetes.default.svc" diff_ms=188 fields.level=1 git_ms=13 health_ms=0 live_ms=11 settings_ms=0 sync_ms=0 time_ms=350
```
