### ISSUE TITLE
ArangoDeployment pods are stuck in Progressing

### ISSUE THREAD

**Issue by bo0ts** [argoproj/argo-cd#14594]
**Describe the bug**

We are deploying the custom resource `ArangoDeployment` with ArgoCD. The `ArangoDeployment` directly owns the pods that make up the Arango database instead of producing a deployment/sts/etc. Unfortunately those pods are never marked as healthy in ArgoCD but always stay in `Progressing` even though all status fields are `green`.

**To Reproduce**

Install the ArangoDB Operator and deploy a minimal `ArangoDeployment` with ArgoCD.

**Expected behavior**

The pods are ready, the arangodeployment is ready. ArgoCD should recognize this.

**Version**

`v2.7.3+e7891b8.dirty`

**Screenshots**
<img width="705" alt="image" src="https://github.com/argoproj/argo-cd/assets/76102/ccf94a3e-f21a-46c7-9750-9b4d5febb913">

**Logs**

A heavily truncated overview of the involved objects and their `status.conditions`:
```
apiVersion: v1
kind: Pod
metadata:
  name: arangodb-cluster-sngl-amktj5ia-4c8580
  namespace: default
  ownerReferences:
    - apiVersion: database.arangodb.com/v1
      controller: true
      kind: ArangoDeployment
      name: arangodb-cluster
spec:
  ...
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2023-07-19T08:44:05Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2023-07-19T08:44:07Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2023-07-19T08:44:07Z'
      status: 'True'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2023-07-19T08:42:58Z'
      status: 'True'
      type: PodScheduled
```
The arangodeployment:
```
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  finalizers:
    - database.arangodb.com/remove-child-finalizers
  name: arangodb-cluster
  namespace: default
spec:
  ...
status:
  ...
  conditions:
    - hash: 1e4ec7079346017bae39ed76f34b2b26101efbc4e7eeeb6ecf82956a1bd6adab
      lastTransitionTime: '2023-07-19T09:19:00Z'
      lastUpdateTime: '2023-07-19T09:19:00Z'
      message: Spec Object accepted
      reason: Spec Accepted
      status: 'True'
      type: SpecAccepted
    - lastTransitionTime: '2023-07-19T08:44:14Z'
      lastUpdateTime: '2023-07-19T08:44:14Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2023-07-19T08:44:15Z'
      lastUpdateTime: '2023-07-19T08:44:15Z'
      reason: ArangoDB is reachable
      status: 'True'
      type: Reachable
    - lastTransitionTime: '2023-07-19T07:47:19Z'
      lastUpdateTime: '2023-07-19T07:47:19Z'
      message: The bootstrap process has been completed successfully
      reason: Bootstrap successful
      status: 'True'
      type: BootstrapCompleted
    - lastTransitionTime: '2023-07-19T07:47:19Z'
      lastUpdateTime: '2023-07-19T07:47:19Z'
      message: The bootstrap process has been completed successfully
      reason: Bootstrap successful
      status: 'True'
      type: BootstrapSucceded
    - hash: 1e4ec7079346017bae39ed76f34b2b26101efbc4e7eeeb6ecf82956a1bd6adab
      lastTransitionTime: '2023-07-19T08:44:16Z'
      lastUpdateTime: '2023-07-19T08:44:16Z'
      message: Spec is Up To Date
      reason: Spec is Up To Date
      status: 'True'
      type: UpToDate
    - lastTransitionTime: '2023-07-19T07:47:20Z'
      lastUpdateTime: '2023-07-19T07:47:20Z'
      message: Spec is Propagated
      reason: Spec is Propagated
      status: 'True'
      type: SpecPropagated
```
