### ISSUE TITLE
Applicationset not recognized Private-Token issue. 

### ISSUE THREAD

**Issue by Qasim-Aziz** [argoproj/argo-cd#14597]
### i am following tutorial [https://about.gitlab.com/blog/2022/08/02/how-to-provision-reviewops/] 
(url) to learn preview environment with argo applicationset , all things seems fine but facing issue when i deploy applicationset,

`error listing repos: error listing merge requests for project '6': Get "https://git.tripon.io/api/v4/projects/6/merge_requests?labels=deploy&per_page=100&state=opened": net/http: invalid header field value for "Private-Token"

i am using gitlab configrations and create group token to perform preview , here is my applicationset

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: review-the-application
  namespace: argocd
spec:
  generators:
  - pullRequest:
      gitlab:
        project: "6"
        api: https://git.tripon.io/
        tokenRef:
          secretName: git-token
          key: token
        labels:
        - deploy
        pullRequestState: opened
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'review-the-application-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: https://git.tripon.io/reviewer-argocd/helm-charts.git
        path: tripon-hasura/
        targetRevision: 'main'
        helm:
          parameters:
          - name: "image.repository"
            value: "docker.io/bazihassan/tripon-hasura-dev"
          - name: "image.tag"
            value: "{{head_sha}}"
          - name: "service.url"
            value: "the-application-{{number}}.159.65.213.81.nip.io"
      project: default
      destination:
        server: https://kubernetes.default.svc/
        namespace: dynamic-environments-with-argo-cd
```
