### ISSUE TITLE
Add sprig library support to DeepLink

### ISSUE THREAD

**Issue by daftping** [argoproj/argo-cd#14625]
# Summary

Add sprig library support to DeepLink

# Motivation
Getting the last `canaryExecutionId` from the list is impossible with the standard library.

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
...
status:
  dryRunSummary: {}
  message: foo
  metricResults:
    - count: 4
      measurements:
        - finishedAt: '2023-07-19T19:58:56Z'
          metadata:
            canaryExecutionId: 01H5QVPH45Y5ACYY74MNR8FZT4
          phase: Successful
          resumeAt: '2023-07-19T19:58:56Z'
          startedAt: '2023-07-19T19:58:11Z'
          value: '100'
        - finishedAt: '2023-07-19T20:04:56Z'
          metadata:
            canaryExecutionId: 01H5QW121CWYTARZSNXJT7ZANV
          phase: Successful
          resumeAt: '2023-07-19T20:04:56Z'
          startedAt: '2023-07-19T20:03:56Z'
          value: '100'
        - finishedAt: '2023-07-19T20:10:56Z'
          metadata:
            canaryExecutionId: 01H5QWC1KV9S1WMZ5C6A81304T
          phase: Successful
          resumeAt: '2023-07-19T20:10:56Z'
          startedAt: '2023-07-19T20:09:56Z'
          value: '100'
        - finishedAt: '2023-07-19T20:16:56Z'
          metadata:
            canaryExecutionId: 01H5QWQ15BG28GFDAB14CWSD5W
          phase: Successful
          resumeAt: '2023-07-19T20:16:56Z'
          startedAt: '2023-07-19T20:15:56Z'
          value: '100'
      message: foo
      name: bar
      phase: Successful
      successful: 4
  phase: Successful
  runSummary:
    count: 4
    successful: 4
  startedAt: '2023-07-19T19:53:11Z'

```

# Proposal

Add sprig library support to DeepLink code to support more advanced scenarious.
