### ISSUE TITLE
2.7.8: OCI dependency url can't contain part of repository

### ISSUE THREAD

**Issue by maartengo** [argoproj/argo-cd#14636]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The OCI repository URL in Helm dependencies get parsed differently than before, causing a breaking change. A repository with URL `oci://acrweu.azurecr.io/helm` used to work if the repository was named `helm/my-chart`, but no longer works since Argo 2.7.8 (probably caused by [PR 14528](https://github.com/argoproj/argo-cd/pull/14528/files)).

**To Reproduce**

Only tested with an Azure Container Registry, but likely affects other registries too.

* Create an ACR (`acrweu.azurecr.io`)
* Publish an empty Helm chart with name `my-chart` into a repository with name `helm/my-chart`
  * e.g. `helm push $(helm package "${chartDir}" | grep -o '/.*.tgz') oci://acrweu.azurecr.io/helm`
  * This is inline with Microsoft documentation; https://learn.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos#push-chart-to-registry-as-oci-artifact
* Create an application that references a Helm chart within a Git repository
* Add the following dependency to that Helm chart:
```yaml
dependencies:
- name: 'my-chart'
  version: '1.0.0'
  repository: 'oci://acrweu.azurecr.io/helm'
```
* Refresh the argo application
* Get the following error:
> ComparisonError: rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: could not download oci://acrweu.azurecr.io/helm/my-chart: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized

Repository secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: acr-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  enableOCI: true
  name: acr-helm
  password: supersecret
  type: helm
  url: acrweu.azurecr.io
  username: someuser
type: Opaque
```

Git Helm chart:
```yaml
apiVersion: 'v2'
name: 'some-chart'
type: 'application'
version: '0.0.1'
appVersion: '0.0.1'
dependencies:
- name: 'my-chart'
  version: '1.0.0'
  repository: 'oci://acrweu.azurecr.io/helm'

```

**Expected behavior**

Same as on 2.7.7; the chart gets pulled and deployed as usual.

**Screenshots**

**Version**

```json
{
    "Version": "v2.7.8+92949f6.dirty",
    "BuildDate": "2023-07-19T15:18:54Z",
    "GitCommit": "92949f6033080f2fba9a9654f46592fb71982770",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Additional info**

What does work is moving the `/helm` from the repository URL to the chart name:

```yaml
apiVersion: 'v2'
name: 'some-chart'
type: 'application'
version: '0.0.1'
appVersion: '0.0.1'
dependencies:
- name: 'helm/my-chart'
  version: '1.0.0'
  repository: 'oci://acrweu.azurecr.io'
```
