### ISSUE TITLE
Image set in an Application has no effect when using Kustomize image transformers

### ISSUE THREAD

**Issue by BillyMorgan** [argoproj/argo-cd#14631]
My Argo application has the following image set:
```yaml
Source:
    Kustomize:
      Images:
        busybox:1.24.0
```

Kustomization:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: container-image
    newName: busybox
    newTag: ubuntu
resources:
  - base-deployment.yaml
 ```

base-deployment.yaml looks like:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      role: deployment
  template:
    metadata:
      labels:
        role: deployment
    spec:
      containers:
        - name: test-pod
          image: container-image
          command: ["tail", "-f", "/dev/null"]
```

As a result I get the `busybox:ubuntu` image, where I would expect to get the `busybox:1.24.0` image from the Argo application.

```shell
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T15:24:49Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Comment by David3310273** [comment]
Hi @BillyMorgan, I wonder what's your output yaml script of `kustomize build` command, would you like to show me that?

**Comment by BillyMorgan** [comment]
@David3310273 Sure thing, here you go, it's as you'd expect tho:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      role: deployment
  template:
    metadata:
      labels:
        role: deployment
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: busybox:ubuntu
        imagePullPolicy: Always
        name: test-pod
```
