### ISSUE TITLE
Random 500 error with SSO : Failed to query provider

### ISSUE THREAD

**Issue by rpg600** [argoproj/argo-cd#14669]
Hello, I have implemented a gitlab sso with this dex configuration :
```
connectors:
- type: gitlab
  id: gitlab
  name: GitLab
  config:
    baseURL: "https://my-gitlab.com/"
    clientID: my_client_id
    clientSecret: my_client_secret
    redirectURI: "https://argo-url/api/dex/callback"
    orgs:
    - MyOrg
    groups:
    - myGroup
  useLoginAsID: false
```
It's working well on my first attempt but I randomly get this error when I logout and login again : 
`"http://argo-url/api/dex": oidc: issuer did not match the issuer returned by provider, expected "http://argo-url/api/dex" got "https://argo-url/api/dex"`

If I reload the page after a few minutes It may log in again.
I'm using argocd v2.7.6.

**Comment by jayachristina** [comment]
did you get around fixing this by any chance please :)

**Comment by vadym-arch** [comment]
We see intermittent SSO login failures with Dex + Google in EKS.

Symptoms:
- UI error: `failed to query provider "": Get "/.well-known/openid-configuration": unsupported protocol scheme ""`
- In argocd-server logs sometimes: `Initializing OIDC provider (issuer: )` (empty issuer)
- Behind LB this can be pod-specific: one pod works (303), another returns 500.
- Refresh/retry may succeed; pod restart also helps.

Environment:
- EKS, Argo CD via Helm chart (tested 9.4.4, 9.4.3, 9.3.0)
- Dex configured via `dex.config` in argocd-cm

Could you confirm if this matches known Dex/OIDC race conditions and recommend a stable fix path?

**Comment by illrill** [comment]
Also hitting this while testing Helm chart upgrade 9.3.7 → 9.4.5. My config:
```
      oidc.config: |
        name: Azure
        issuer: https://login.microsoftonline.com/**REDACTED**/v2.0
        clientID: **REDACTED**
        clientSecret: $oidc.azure.clientSecret
        requestedIDTokenClaims:
          groups:
            essential: true
        requestedScopes:
          - openid
          - profile
          - email
```
