### ISSUE TITLE
helm values.yaml can't change parameter

### ISSUE THREAD

**Issue by vvatlin** [argoproj/argo-cd#14667]
argocd 2.7.8 
I'm using argocd with helm 
Part of my Application is 
```
source:
    chart: ras
    repoURL: myrepo
    targetRevision: 0.0.2
    helm:
      skipCrds: true
      valueFiles:
        - values.yaml
```
Accidentally I set wrong Certificate name in two Applications to  the same name, and now argocd is trying to sync it twice and it's always out of sync. 

Then I tried  to change certificate name in the app2 to the correct value. Pushed to the repo, but nothing is changed. 
I tried everything, delete argocd pods, hard refresh, delete app, sync with prune, with recreate. Still my app in argocd use old values parameters.
