### ISSUE TITLE
An App Of Apps is in "OutOfSync" state and Applications for which I override helm parameters like this `helm: {}` are also in "OutOfSync" state

### ISSUE THREAD

**Issue by ArtemShevelyukhin** [argoproj/argo-cd#14668]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

An App Of Apps is in "OutOfSync" state and Applications for which I override helm parameters like this `helm: {}` are also in "OutOfSync" state

**To Reproduce**

To reproduce just apply [app-of-apps.yaml](https://github.com/ArtemShevelyukhin/argocd-demo/blob/main/AppOfAppsAndOutOfSync/app-of-apps.yaml)

https://github.com/ArtemShevelyukhin/argocd-demo/tree/main/AppOfAppsAndOutOfSync

There is an AppOfApps which contains 4 applications. These applications use ["simple-microservice-2" chart](https://github.com/ArtemShevelyukhin/argocd-demo/tree/main/simple-microservice-2) which is in the root of the repository
Also I tried different overrides for helm section in these apps - [example](https://github.com/ArtemShevelyukhin/argocd-demo/blob/main/AppOfAppsAndOutOfSync/apps/templates/application-1.yaml#L26)

**Expected behavior**

"app-of-apps" argocd application has Synced state on both overall "Applications" and specific application views

**Actual behavior**

On the "Applications" view we see that "app-of-apps" application is in OutOfSync state and all other applications are in Synced state

![image](https://github.com/argoproj/argo-cd/assets/33910251/1d097c87-59f2-4032-aef5-b7bbbdba76bf)

And if we go to the "app-of-apps" application we will see that "app-of-apps" application is in  OutOfSync state and "application-1" and "application-4" are also in OutOfSync  state

![image](https://github.com/argoproj/argo-cd/assets/33910251/32f20529-9b12-418c-b18a-ebe98921b8b9)

And if we check sync status here 

![image](https://github.com/argoproj/argo-cd/assets/33910251/f0f68a9c-ef6b-477f-b699-4623a47e72c5)

we will see that all application are in Synced state 

![image](https://github.com/argoproj/argo-cd/assets/33910251/bb662e62-9cc9-4465-bbaa-c17d4837dabc)

**Version**

```shell
argocd-server: v2.7.7+4650bb2.dirty
BuildDate: 2023-07-05T19:42:32Z
GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
GitTreeState: dirty
GoVersion: go1.19.10
Compiler: gc
Platform: linux/amd64
Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
Helm Version: v3.11.2+g912ebc1
Kubectl Version: v0.24.2
Jsonnet Version: v0.19.1
```

**Comment by pgier** [comment]
This looks similar to #13004

**Comment by ArtemShevelyukhin** [comment]
Diff before manual Sync
![image](https://github.com/argoproj/argo-cd/assets/33910251/229a1969-8095-4347-a174-8990851f4271)

After manual Sync
![image](https://github.com/argoproj/argo-cd/assets/33910251/e71b1589-0dd0-4569-b8fe-5301e76dad5b)

**Comment by pgier** [comment]
Seems like this is a bug in the sync code.  Looks like when the Application object is serialized it's using `omitempty` in one place, but not in the other.

**Comment by crenshaw-dev** [comment]
I'm not sure about the `retry` block, but the Argo CD controller automatically "normalizes" the app spec: https://github.com/argoproj/argo-cd/blob/0ae5882d5ae9fe88efc51f65ca8543fb8c3a0aa1/util/argo/argo.go#L873

I'm not sure why. I don't feel like it's a good thing to do. Seems like Argo CD should just have one canonical interpretation of whatever input the user chooses to specify.

**Comment by crenshaw-dev** [comment]
https://github.com/argoproj/argo-cd/pull/848

> This change normalizes an application spec as part of controller reconciliation. This allows us to migrate specs into preferred states, and eventually drop legacy fields.

We haven't done this kind of field migration in a long time. I'm not sure it's necessary anymore.

**Comment by evs-ops** [comment]
> I'm not sure about the `retry` block, but the Argo CD controller automatically "normalizes" the app spec:
> 
> https://github.com/argoproj/argo-cd/blob/0ae5882d5ae9fe88efc51f65ca8543fb8c3a0aa1/util/argo/argo.go#L873
> 
> I'm not sure why. I don't feel like it's a good thing to do. Seems like Argo CD should just have one canonical interpretation of whatever input the user chooses to specify.

Currently same error, If can help somehow please tell me. I can test changes if you need

**Comment by pgier** [comment]
> I'm not sure about the `retry` block, but the Argo CD controller automatically "normalizes" the app spec:
> 
> https://github.com/argoproj/argo-cd/blob/0ae5882d5ae9fe88efc51f65ca8543fb8c3a0aa1/util/argo/argo.go#L873
> 
> I'm not sure why. I don't feel like it's a good thing to do. Seems like Argo CD should just have one canonical interpretation of whatever input the user chooses to specify.

@crenshaw-dev  I agree this seems wrong, since a null value means don't use Helm, while an empty/Zero value should mean use Helm with the default values.  Seems like that if block should be removed.  Do you think that will break something else?

**Comment by crenshaw-dev** [comment]
> a null value means don't use Helm

I think it's more like, "a null value means detect what to use based on repo contents."

> Seems like that if block should be removed. Do you think that will break something else?

I don't think it will break anything.

**Comment by crenshaw-dev** [comment]
I think I'd want to do it in 2.9, just so we have more time to make sure it doesn't break anything. But yep, I'm in favor of removing at least the Helm normalization. Maybe all source normalization.

**Comment by crenshaw-dev** [comment]
@evs-ops sounds like your request is to do something like this:

```yaml
kind: ApplicationSet
template:
  spec:
    template:
      source:
        helm: '{{config}}'
```

Unfortunately, ApplicationSet's templating isn't quite that powerful yet. What you could do is this:

```yaml
kind: ApplicationSet
template:
  spec:
    template:
      source:
        helm:
          values: '{{config.values}}'
```

But I think that discussion is a bit out of scope of this issue.

**Comment by alex-souslik-hs** [comment]
I have the same issue when setting parameters to `null`.
Argo thinks the value needs to be an empty string in the rendered manifest and get stuck on a sync loop.

**Comment by andrii-korotkov-verkada** [comment]
You can ignore some differences using something like this
```
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "*"
      kind: "Application"
      namespace: argocd
      jsonPointers:
        - /spec/source/helm
        - /spec/source/retry
        # To allow manually turn off auto sync for apps and preserve that setting
        - /spec/syncPolicy/automated
        # These were found to also introduce desyncs
        - /metadata/annotations/argocd.argoproj.io~1refresh
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
```
