### ISSUE TITLE
Managing Argo CD with Argo CD inevitably causes diff from Kustomization template

### ISSUE THREAD

**Issue by lindhe** [argoproj/argo-cd#14665]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

This is very much in the gray area between being a bug report and and a feature request, so please excuse me if I'm posting the wrong type here.

As far as I can tell, the recommended way of deploying Argo CD is using Kustomize. At least that's what all examples in your repos are using, so that's what I'm using. And since it says in [the documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd) that it's fine to let Argo CD manage itself, I do that too!

> "Argo CD is able to manage itself since all settings are represented by Kubernetes manifests. The suggested way is to create [Kustomize](https://github.com/kubernetes-sigs/kustomize) based application which uses base Argo CD manifests from [https://github.com/argoproj/argo-cd](https://github.com/argoproj/argo-cd/tree/stable/manifests) and apply required changes on top.

But here's where I'm running into a slight snag. Argo CD automatically adds the `app.kubernetes.io/instance: <appname>` annotation for [resource tracking](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/) purposes. This causes a diff compared to my Kustomization template, which is annoying. This makes it a lot harder to keep track of new changes before they are committed, pushed and eventually applied by Argo CD.

So, I thought, let's just add that annotation to the application manually. That's not such a big deal, and I'll get rid of the diff. But, alas, it seems like Argo CD does not set the `app.kubernetes.io/instance` label for CRDs that are part of an application. So now I'm caught in a catch 22 where I either get a diff on the CRD resources (if I explicitly set the `app.kubernetes.io/instance` annotation) or a diff on _all other resources_ (if I do not explicitly set the `app.kubernetes.io/instance` annotation). **Is this a bug or a feature?** I cannot tell.

If this is a bug, I guess my Issue should be renamed to "Resource tracking label `app.kubernetes.io/instance` is not set for CRD objects".

If I'm wrong and it is possible to have a diff free setup, please inform me! :)

**To Reproduce**

I cannot share the exact details of my full setup, but I believe something like this should be sufficient to replicate the behavior:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.8/manifests/ha/install.yaml
- ./repo.yaml
- ./argocd.yaml
```

```yaml
# repo.yaml
apiVersion: v1
kind: Secret
metadata:
  name: repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/lindhe/argocd-kustomization-diff.git
```

```yaml
# argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /
    repoURL: https://github.com/lindhe/argocd-kustomization-diff.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```shell
kubectl create ns argocd
kustomize build . | kubectl apply -f -

# Wait until everything settles

kustomize build . | kubectl diff -f -
```

**Expected behavior**

I want to be able to have a clean Kustomize setup for Argo CD that has no `kubectl diff` unless something has actually changed in my code.

**Screenshots**

This is the diff output before explicitly setting `app.kubernetes.io/instance: argocd`:

![Diff with unmodified code](https://github.com/argoproj/argo-cd/assets/7773090/06e94f13-e79e-44e6-9003-abfef7ac30e4)

Then we try adding this to the `kustomization.yaml`:

```yaml
labels:
- pairs:
    app.kubernetes.io/instance: argocd
```

Now this is the diff output, after explicitly setting `app.kubernetes.io/instance: argocd`:

![Diff with unmodified code](https://github.com/argoproj/argo-cd/assets/7773090/802531bb-a1d8-4d1e-80ce-d509b7f4ac88)

Note how there's other resources diffing now.

**Version**

```console
$ argocd version
argocd: v2.7.8+92949f6
  BuildDate: 2023-07-19T15:34:15Z
  GitCommit: 92949f6033080f2fba9a9654f46592fb71982770
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.8+92949f6.dirty
  BuildDate: 2023-07-19T15:18:54Z
  GitCommit: 92949f6033080f2fba9a9654f46592fb71982770
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

```console
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:56:58Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
```

```console
$ kustomize version
v5.1.0
```
