### ISSUE TITLE
Multi-source support for .argocd-source-<appName>.yaml

### ISSUE THREAD

**Issue by filipprosovsky** [argoproj/argo-cd#14672]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using multiple sources with helm, ArgoCD is unable to fetch the .argocd-source-<appNAME>.yaml file from the location as it expects the file to exists in helm repository instead of git repository. 
I am using modified argocd-image-updater, but that is not the problem as the file is being created based on path I supply to first source (helm source in my case). This path attribute is ignored as written in documentation when using helm.

**To Reproduce**

1. Create an Application manifest like:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $chartName }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: image={{ $repo }}/{{ $chartName }}
    argocd-image-updater.argoproj.io/image.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/image.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/image.force-update: "true"
    argocd-image-updater.argoproj.io/image.update-strategy: latest
    argocd-image-updater.argoproj.io/image.allow-tags: regexp:^main.*$
spec:
  destination:
    name: {{ $cluster }}
    namespace: {{ $namespace }}
  project: apps
  sources:
    - repoURL: {{ $helmRepo }}
      chart: {{ $chartName }}
      targetRevision: 1.0.0
      path: {{ $imageUpdaterPath }} # this is for image updater to know where to store the .argocd-source-appName.yaml file
      helm:
        passCredentials: true
        valueFiles:
          - $values/{{ $pathToValues }}
    - repoURL: {{ $gitRepo }}
      targetRevision: main
      ref: values
  
  syncPolicy:
    retry:
      limit: 3
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```
2. Create .argocd-source-<appName>.yaml file in any location (should be **path:** location as thats where my modified argocd-image-updater creates it)

**Expected behavior**

Either some annotation or attribute, when using helm, should be possible to specify to select repo other then repoURL from which to get .argocd-source-<appName>.yaml file

**Version**

```shell
v2.7.6+00c914a.dirty
```

**Logs**

```
No relevant logs found
```

**Comment by ishitasequeira** [comment]
@filipprosovsky , are you using `.argocd-source-appName.yaml` as the values file? If that is the case, assuming `.argocd-source-appName.yaml` is present in `gitRepo`, you can provide the file using below format..

```
spec:
  destination:
    name: {{ $cluster }}
    namespace: {{ $namespace }}
  project: apps
  sources:
    - repoURL: {{ $helmRepo }}
      chart: {{ $chartName }}
      targetRevision: 1.0.0
      helm:
        passCredentials: true
        valueFiles:
          - $values/{{ $path }}/.argocd-source-appName.yaml      # path to .argocd-source-appName.yaml file
    - repoURL: {{ $gitRepo }}
      targetRevision: main
      ref: values
```

You can pass multiple valueFiles as well using the `$values` referenced repository.

**Comment by filipprosovsky** [comment]
@ishitasequeira Yes that is the workaround I do. But I can imagine there should be **native** support in ArgoCD? 
Also, passing that as values file (with the structure helm.parameters[N]) is not usable, so what we did was code the argocd-image-updater to support dynamic structure of image.repository | image.tag + combining few PRs present in argocd-image-updater repo to support multi-sources and specifying git repo instead of helmRepo. 
[Repository](https://github.com/filipprosovsky/argocd-image-updater-multiple-sources) if anybody finds it usable as well :) In README.md, there is description as what is included on top of 0.12.2 version

**Comment by LS80** [comment]
This could be very useful now that we have https://github.com/argoproj-labs/argocd-image-updater/pull/424.

**Comment by wofr** [comment]
Unfortuantly the workarround didn't work for me.   I agree it would be greate if it would be possible to tell ArgoCD where the  [Git Overides](https://argo-cd.readthedocs.io/en/stable/user-guide/parameters/#store-overrides-in-git) could be found.    

I would like to avoid to store them within my private helm-repository I use for the deployment.  The ArgoCd should be stored some where else but considered for the deployment.

**Comment by kobin23** [comment]
Hi folks! I wanted to check if there are any plans or timelines to address this issue? I really appreciate any update or guidance on possible workarounds🙏

**Comment by unmacaque** [comment]
I have managed to get it working with a few workarounds. It is based on https://github.com/argoproj/argo-cd/issues/14672#issuecomment-1652887719 which had to be adapted a bit as ArgoCD seems to get confused where to apply `.argocd-source-appName.yaml` when using multiple sources.

This is the complete Application manifest using mailpit as an example:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailpit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd-image-updater.argoproj.io/image-list: mailpit=axllent/mailpit
    argocd-image-updater.argoproj.io/mailpit.force-update: "true"
    argocd-image-updater.argoproj.io/mailpit.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/mailpit.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/mailpit.update-strategy: semver
    argocd-image-updater.argoproj.io/git-repository: {{ .Values.spec.sources.repos.overrides }}
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-method: {{ .Values.updater.git.writeBack.method }}
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/mailpit/values.yaml
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: mailpit
  project: {{ .Values.spec.project }}
  sources:
    - repoURL: https://jouve.github.io/charts/
      chart: mailpit
      targetRevision: 0.*
      helm:
        releaseName: mailpit
        valueFiles:
          - $values/mailpit/values.yaml
          - $overrides/mailpit/values.yaml
        ignoreMissingValueFiles: true
    - repoURL: {{ .Values.spec.sources.repos.values }}
      ref: values
    - repoURL: {{ .Values.spec.sources.repos.overrides }}
      ref: overrides
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

The workaround is actually pretty simple. argocd-image-updater supports writing files in `helmvalues` format, which can be referenced as another source for `valueFiles` in the Helm section. In my case, ``{{ .Values.spec.sources.repos.overrides }}`` is a Git repository that only stores the overrides files generated by image updater. A seperate repo is not strictly necessary, but I did not like the image updater messing with the formatting of my existing values files. I set `ignoreMissingValueFiles: true` so the deployment will not fail, if no previous override file exists. Otherwise, it would require manual creation, if the flag is undesired.

Still hoping for support of multi-source apps though, that will make all or at least some workarounds obsolete.
