### ISSUE TITLE
SSO with AWS' Identity Center does not work.

### ISSUE THREAD

**Issue by nicl-dev** [argoproj/argo-cd#14703]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are trying to setup SSO with AWS' IAM Identity Center and are facing the following error:

```
time="2023-07-25T12:56:02Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2023-07-25T12:56:02Z" grpc.time_ms=0.247 span.kind=server system=grpc
```

Unfortunately, there does not exist any documentation of successful attempts to use IAM Identity Center for SSO with ArgoCD. The Slack channel couldn't help us either, so we rely on help here now. A similar issue (using OneLogin instead of IAM Identity Center) has been reported here: https://github.com/argoproj/argo-cd/issues/5450

**To Reproduce**

Current dex.config and rbac:

```
configs:
  cm:
    dex.config: |
      logger:
        level: debug
        format: json
      connectors:
      - type: saml
        id: saml
        name: saml
        config:
          ssoURL: https://portal.sso.eu-central-1.amazonaws.com/saml/assertion/xxx
          entityIssuer: https://xxx.amazonaws.com/api/dex/callback
          caData: |
            xxx
          usernameAttr: subject
          emailAttr: email
```

```
rbac:
    policy.csv: |
      g, myusername, role:admin,
    scopes: "[name]"
    policy.default: role:readonly
```

**Expected behavior**

Login via SAML is succesful.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/75254846/9134c683-6fd8-4ca1-a175-593e58e80dc4)

**Version**

```shell
argocd: v2.7.9+0ee33e5.dirty
  BuildDate: 2023-07-24T18:26:31Z
  GitCommit: 0ee33e52dd1f1bb944488584fc6f854b929f1180
  GitTreeState: dirty
  GoVersion: go1.20.6
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.9+0ee33e5.dirty
  BuildDate: 2023-07-24T18:26:31Z
  GitCommit: 0ee33e52dd1f1bb944488584fc6f854b929f1180
  GitTreeState: dirty
  GoVersion: go1.20.6
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v5.1.0 2023-06-19T16:53:36Z
  Helm Version: v3.12.2+g1e210a2
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
time="2023-07-25T12:56:02Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2023-07-25T12:56:02Z" grpc.time_ms=0.247 span.kind=server system=grpc
```

**Comment by walkingerica** [comment]
Hi nicl-dev, do you have any solutions for this? Thank you!

**Comment by nicl-dev** [comment]
@walkingerica Unfortunately we couldn't make it work yet. Still looking for help.

**Comment by smeckert** [comment]
@nicl-dev we've make it work!   

In AWS Identity Center configuration should be have the following attributes configured:  

**Application start URL - (optional):** https://<ARGO_CD_DOMAIN>/auth/login?return_url=https%3A%2F%2F<ARGO_CD_DOMAIN>%2Fapplications

**Application ACS URL:** https://<ARGO_CD_DOMAIN>/api/dex/callback

**Application SAML audience:** https://<ARGO_CD_DOMAIN>/api/dex/callback


Our dex.config looks like:

```    
dex.config: |
      logger:
        level: debug
        format: json
      connectors:
      - type: saml
        id: aws
        name: "AWS IAM Identity Center"
        config:
          ssoURL: https://portal.sso.eu-central-1.amazonaws.com/saml/assertion/<ID>
          caData: <BASE64_DECODED_CA_CERT>
          entityIssuer: https://<ARGO_CD_DOMAIN>/api/dex/callback
          redirectURI: https://<ARGO_CD_DOMAIN>/api/dex/callback
          usernameAttr: email
          emailAttr: email
          groupsAttr: groups
```

I hope it helps to make tthis work.

**Comment by patr00n** [comment]
In addition to @smeckert reply. You need to have proper attribute mapping in AWS Application:
![image](https://github.com/argoproj/argo-cd/assets/14932399/c5f33374-7217-4c65-bf50-1164a0bb9bc4)

**Comment by zeusal** [comment]
Hi, 

I am trying to configure ArgoCD with AWS SSO and I am having problems.

Following the instructions for @patr00n  and @smeckert  I have a question, the caData is the string <ds:X509Certificate> of the SAML Metadata  File or is the IAM Identity Center Certificate of the application AWS SSO converted to base64.

caData of SAML Metadata file or Cert PEM convert to base64 (-----BEGIN CERTIFICATE----- and -----END CERTIFICATE----- certificate)?

**Comment by patr00n** [comment]
@zeusal 
We have even stricter policies, but in general, it looks similar. Unless we have only groups in scopes

**Comment by madclement** [comment]
Hi @zeusal , even after adding the policies that you mentioned, i am not able to sync an application in the default project.
My argocd-rbac-cm.yaml : 

<img width="573" alt="image" src="https://github.com/argoproj/argo-cd/assets/93644717/22f2f886-50fc-45f6-bbcf-2802545c8901">

**Comment by zeusal** [comment]
> Hi @zeusal , even after adding the policies that you mentioned, i am not able to sync an application in the default project. My argocd-rbac-cm.yaml :
> 
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/93644717/281395379-22f2f886-50fc-45f6-bbcf-2802545c8901.png">
Are all other settings correct?

You need:
- AWS Identity Center (AWS SSO) Saml application with correct attribute mappings
![image](https://github.com/argoproj/argo-cd/assets/33123154/71141283-1198-4c44-a82b-2bedbd3d186f)
- Assign group(s) to AWS Identity Center (AWS SSO) Saml application
![image](https://github.com/argoproj/argo-cd/assets/33123154/88571337-9d2f-478f-b4f6-47da566557fe)
- Get Group ID of AWS Identity Center from this console.
- Configure ArgoCD Dex with the AWS Identity Center SAML application.
- And finally,  configure RBAC with previously Group ID and the permissions you want to have for the group(s).


You can help yourself with this document: https://argo-cd.readthedocs.io/en/latest/operator-manual/user-management/identity-center/

**Comment by madclement** [comment]
Yes I followed the same instructions
Sharing here the settings used

<img width="970" alt="image" src="https://github.com/argoproj/argo-cd/assets/93644717/8f5ace12-3831-4516-bc55-62ff6b81a982">

<img width="1074" alt="image" src="https://github.com/argoproj/argo-cd/assets/93644717/21b9f754-0c6c-46af-bbe7-be6239558bcc">

argocd-cm:

<img width="721" alt="image" src="https://github.com/argoproj/argo-cd/assets/93644717/b9befd65-177b-4335-84ea-216e55c4f223">

**Comment by zeusal** [comment]
> Yes @zeusal I followed the same instructions Sharing here the settings used
> 
> <img alt="image" width="970" src="https://user-images.githubusercontent.com/93644717/281416567-8f5ace12-3831-4516-bc55-62ff6b81a982.png"> <img alt="image" width="1074" src="https://user-images.githubusercontent.com/93644717/281416731-21b9f754-0c6c-46af-bbe7-be6239558bcc.png">
> argocd-cm:
> 
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/93644717/281417081-b9befd65-177b-4335-84ea-216e55c4f223.png">

I understand, that you get access to ArgoCD, so the connection/configuration of ArgoCD <-> AWS Identity Center SAML APP is correct.

After accessing and attempting a "sync" operation, what error/message is displayed?

Does the group shown in "User Information" of the ArgoCD console match the one in the AWS Identity Center (in this case Infra-L4 and Infra-L5)?

And finally, I understand that the user with which you are trying to access is within any of these two groups (Infra-L4 and Infra-L5), is that correct?

You can send us the logs after the login, to see if argocd is showing any error when retrieving the groups.

Also test this policy by entering a single group.
```  yaml
  policy.csv: |
    g, <GROUP ID>, role:admin
  scopes: '[groups, email]'
```

**Comment by madclement** [comment]
Hey @zeusal , the following error message is displayed after sync operation

`Unable to deploy revision: permission denied: applications, sync, default/karpenter-test, sub: ChhjbGVtZW50QG1hZHN0cmVldGRlbi5jb20SA2F3cw, iat: 2023-11-08T13:02:08Z`

There are random multiple groups shown in User Info page in argocd, but none of them corresponds to the group id in AWS Identity Center 

Yes, my access is within Infra-L3 group

The logs i am getting after entering the policy you provided, after replacing my groupid there

<img width="1321" alt="image" src="https://github.com/argoproj/argo-cd/assets/93644717/c7b7e0da-15cc-48bd-8026-163a2a42749d">

**Comment by zeusal** [comment]
> Hey @zeusal , the following error message is displayed after sync operation
> 
> `Unable to deploy revision: permission denied: applications, sync, default/karpenter-test, sub: ChhjbGVtZW50QG1hZHN0cmVldGRlbi5jb20SA2F3cw, iat: 2023-11-08T13:02:08Z`
> 
> There are random multiple groups shown in User Info page in argocd, but none of them corresponds to the group id in AWS Identity Center
> 
> Yes, my access is within Infra-L3 group
> 
> The logs i am getting after entering the policy you provided, after replacing my groupid there
> 
> <img alt="image" width="1321" src="https://user-images.githubusercontent.com/93644717/281438204-c7b7e0da-15cc-48bd-8026-163a2a42749d.png">

Hi @madclement

The permissions are not applied correctly because they do not match the groups with the Identity Center, ArgoCD and RBAC.

In my case, the AWS Identity Center Group ID match with "User Info" Argo CD.

If you need help, I can help you through Slack.

**Comment by zeusal** [comment]
Hi again @madclement 

I have tested from my local with AWS Identity Center SAML APP in my personal AWS account and it works.

If in rbac cm I have role:admin I can create and sync application, if change this value to role:readonly, I can only see objects.

With role:readonly:
```  yaml
  policy.csv: |
    g, 64d84438-b0c1-708c-f431-91ece2abb39a, role:readonly
  scopes: '[groups, email]'
```
![image](https://github.com/argoproj/argo-cd/assets/33123154/927d179d-c43a-476f-adcd-8cc2a2ed6dbf)
![image](https://github.com/argoproj/argo-cd/assets/33123154/3d166c72-bcb5-4b6b-b36c-47aacbf6fd3e)

With role:readonly:
```  yaml
  policy.csv: |
    g, 64d84438-b0c1-708c-f431-91ece2abb39a, role:admin
  scopes: '[groups, email]'
```
I can sync:
![image](https://github.com/argoproj/argo-cd/assets/33123154/de2a1553-1615-47d4-bfaf-7b2722b28775)


This is my argocd-cm:
```  yaml
apiVersion: v1
data:
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: aws
      name: "AWS IAM Identity Center"
      config:
        ssoURL: https://portal.sso.us-east-1.amazonaws.com/saml/assertion/<ID>
        caData: <CERT IN BASE64>
        entityIssuer: https://localhost:8080/api/dex/callback
        redirectURI: https://localhost:8080/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: groups
  url: https://localhost:8080
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd

```

This my group: 
![image](https://github.com/argoproj/argo-cd/assets/33123154/fcea432b-ac73-48e4-9a2b-ef802603e6ac)
Mappings:
![image](https://github.com/argoproj/argo-cd/assets/33123154/f845488b-cff4-4d8a-9706-d4db7988878d)
SAML APP config:
![image](https://github.com/argoproj/argo-cd/assets/33123154/379a567e-22c9-48fb-88ec-00fa1944fc77)
Group Assignment
![image](https://github.com/argoproj/argo-cd/assets/33123154/02e34535-2a52-4d62-be59-de3eb850be18)

I don't understand why it doesn't work, following the steps I have managed to make it work locally.
