### ISSUE TITLE
OpenShift Route in combination with cert-utils-operator expose certificate keys

### ISSUE THREAD

**Issue by renat1sakenov** [argoproj/argo-cd#14702]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

We're running Argo CD (v2.6.4) on OpenShift (4.11).
OpenShift Routes do not support secrets directly, so we're utilizing partially the cert-util-operator in order to implement tls.
When adding a route to an application, with the annotation `cert-utils-operator.redhat-cop.io/certs-from-secret: "<secret-name>"`, cert-util-operator will inject the certificate, from a secret, into the fields `.spec.tls.certficate` and `.spec.tls.key` into the route.
The private key will be visible in the Argo CD web UI for anyone who has access to view the corresponding application.

In contrast, the sensitive content of live manifests of secrets is hidden on the web UI.

I'm aware that this report goes in similar direction as some of the previous issues, such as:
#5201 - This was never resolved / the reporter found a workaround)
#4736 - In contrast to this issue, I'm not referring to values but to the live manifest.

but I'd like to discuss this particular case - OpenShift Routes, which was not addressed directly.

**To Reproduce**

With the prerequisites fulfilled (access to OpenShift and cert-utils-operator, minimal Argo CD application to manage a route):

Create OpenShift Route with annotation to be managed by Argo CD:
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: "test-cert"
  name: test-route
spec:
  host: <hostname>
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: test
```
Argo CD will expose the certificate and private key in the live manifest view.

**Expected behavior**

My expectation would be that the private key would be consealed in the same way as a secret (`++++++++`).

**Screenshots**

![argocd_cert_issue](https://github.com/argoproj/argo-cd/assets/9828084/424e4adb-678c-42cc-b005-62602c66987d)

**Version**

```shell
argocd@argocd-application-controller-0:~$ argocd version
argocd: v2.6.4+7be094f
  BuildDate: 2023-03-07T22:48:16Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```
