### ISSUE TITLE
Set parameters are not passed in case of PLUGIN

### ISSUE THREAD

**Issue by AnubhavSabarwal** [argoproj/argo-cd#14719]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When we use helm whatever parameters we were passing was getting set in helm template command however, when same thing injected through plugin is not working.

**To Reproduce**

**argocd-cmp-cm**
```
apiVersion: v1
data:
  ssm-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: ssm-helm
    spec:
      discover:
        fileName: ./*.yaml
      generate:
        args:
        - helm template ${ARGOCD_APP_NAME} . -n ${ARGOCD_APP_NAMESPACE} --include-crds -f ${PARAM_VALUEFILES}
        command:
        - sh
        - -c
      init:
        args:
        - helm ssm -f Chart.yaml &&  if grep -Fq 'ssm ' ${PARAM_VALUEFILES}; then helm ssm -f ${PARAM_VALUEFILES}; else echo 'helm ssm skipped'; fi  && helm dependency build
        command:
        - sh
        - -c
```

**Application Manifest Yaml:**
```
project: testingargo
source:
  repoURL: 'https://git/testingargo.git'
  path: >-
    testing/argo/path
  targetRevision: main
  plugin:
    parameters:
      - name: testingargo.k8s_cluster_name
        string: testingargocluster
      - name: valueFiles
         string: testing.yaml
destination:
  namespace: testingargo
  name: testingargocluster
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: true
  ``` 
    
  **Application Values.yaml**
  ```
 testingargo:
      VaultInitContainer:
      enabled: true
      image:
        repository: dockerhub.com
        pullPolicy: Always
        tag: v1
      vault_url: https://vault.com
      vault_k8s_mount_path: '{{ "{{" }} .Values.k8s_cluster_name {{ "}}" }}'
```

here vault_k8s_mount_path is coming blank

**Expected behavior**

vault_k8s_mount_path should have the value eg **testingargocluster**

**Screenshots**

**Version**

argocd: v2.7.9+0ee33e5.dirty
  BuildDate: 2023-07-24T17:42:11Z
  GitCommit: 0ee33e52dd1f1bb944488584fc6f854b929f1180
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64

**Logs**

```
Paste any relevant application logs here.
```
