### ISSUE TITLE
OpenID Connect using AWS Cognito cannot map Groups

### ISSUE THREAD

**Issue by JBartlett86** [argoproj/argo-cd#1471]
**Describe the bug**

Argo's OpenID Connect setup sends an unsupported scope during authorisation called **_groups_** scope, when used with AWS Cognito this causes a failure.

For AWS Cognito an additional scope is not required and in fact groups is not a supported scope at all and when included causes it to fail.

**To Reproduce**
1. Create AWS Cognito User Pool
1. Create Client App within User Pool (store client id and secret)
    1. Set callback url to https://argo.test.com:30443/auth/callback
1. Configure oidc configuration in Argo
```
data:
  url: https://argo.test.com:30443

  oidc.config: |
    name: company
    issuer: "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_xxxxxxx"
    clientID: xxxxxxxxxxxxxx
    clientSecret: xxxxxxxxxxx
   
```
1. Navigate to Argo and attempt to login using new SSO button
1. This then directs to the following url: _https://<pool_domain>.auth.eu-west-1.amazoncognito.com/oauth2/authorize?client_id=xxxxxxxxx&redirect_uri=https://argo.test.com:30443/auth/callback&response_type=code&scope=openid+profile+email+groups&state=xxxxxxxx_
1. Which produces the error: **_invalid_request: invalid_scope_**

**Expected behavior**
Using AWS Cognito should not include the groups scope and it should be possible to get the groups from the **_cognito:groups_** claim

**Additional context**
AWS Cognito returns groups as part of the idToken payload with the name cognito:groups and doesn't seem to require an additional scope.
https://stackoverflow.com/questions/52878146/aws-cognito-how-to-get-users-group-from-token-object

From a review of the code that processes the claims it is also expecting the claim for the groups to be called  **_groups_** which also will not work as the claim is actually called **_cognito:groups_**
