### ISSUE TITLE
Application+Ingress links are HTTP instead of HTTPS

### ISSUE THREAD

**Issue by TeamDman** [argoproj/argo-cd#14711]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Link for Application and Ingress shows HTTP not HTTPS.

**To Reproduce**

1. Create an Application
2. Add an ingress with tls field
3. Link is not presented as HTTPS

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ing
  namespace: demo-hello
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" # removing this had no effect
spec:
  tls:
    - hosts:
        - aksdemo-hello.acc.myhost.ca
  rules:
  - host: aksdemo-hello.acc.myhost.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-svc
            port:
              number: 80
  ingressClassName: nginx
```

**Expected behavior**

Link should be HTTPS on the web interface

**Screenshots**

Application object

<img width="278" alt="image" src="https://github.com/argoproj/argo-cd/assets/9356891/ac582e2a-224c-4feb-96f5-1099752e69f3">

Ingress object

<img width="254" alt="image" src="https://github.com/argoproj/argo-cd/assets/9356891/d567d9df-05c4-4afe-bbd7-f020da532d52">

**Version**

```shell
{
    "Version": "v2.7.9+0ee33e5.dirty",
    "BuildDate": "2023-07-24T17:42:11Z",
    "GitCommit": "0ee33e52dd1f1bb944488584fc6f854b929f1180",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```

```

**Related**

- https://github.com/argoproj/argo-cd/blob/0ae5882d5ae9fe88efc51f65ca8543fb8c3a0aa1/controller/cache/info.go#L170-L194
- https://github.com/argoproj/argo-cd/issues/6884
- https://github.com/argoproj/argo-cd/issues/2199
