### ISSUE TITLE
Multi-source doesn't work with repo target revision

### ISSUE THREAD

**Issue by PengLingJun** [argoproj/argo-cd#14715]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

my config is:
```
      - repoURL: https://git.xxx.cn/api/v4/projects/87/packages/helm/stable
        targetRevision: 0.7.6
        chart: argocd-project-apps
        helm:
          valueFiles:
            - "$values/argocd-staging.yaml"
           
      - repoURL: 'git@git.xxxx.cn:cloud/point/deploy.git'
        targetRevision: staging
        ref: values
```

**To Reproduce**

**Expected behavior**
vaules ref from staging，but if I commit new version in master,argocd autosync

**Screenshots**

**Version**

```shell
argocd: v2.7.5+a2430af.dirty
  BuildDate: 2023-06-16T14:55:17Z
  GitCommit: a2430af1c356b283e5e3fc5bde1f5e2b5199f258
  GitTreeState: dirty
  GoVersion: go1.20.5
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.7.3+e7891b8.dirty
  BuildDate: 2023-05-24T15:05:34Z
  GitCommit: e7891b899a35dca06ae94965ea5ae2a86b344848
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Paste any relevant application logs here.
```
