### ISSUE TITLE
appset progressive sync should support globs/regex or templating

### ISSUE THREAD

**Issue by zswanson** [argoproj/argo-cd#14724]
# Summary

Based on testing, AppSet progressive sync steps appear to support only fully qualified app names. This doesn't fit well with the idea of 'generating' apps, where part of the benefit is not having to specify everything inclusively. There also seems to be no way to indicate "and now sync all the other apps" at the end of the steps.

# Motivation

We want to be able to define a progressive step with either a template from the Generator, or using wildcard globs or regex. 
Example:

``` yaml
 strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: helmfileBaseName
          operator: In
          values:
          - argocd
      - matchExpressions:
        - key: helmfileBaseName
          operator: In
          values:
          - "demo-*"
       - matchExpressions:
        - key: helmfileBaseName
          operator: In
          values:
          - "*"     
```

# Proposal

Implement glob/regex matching in the progress sync of the applicationset controller.

**Comment by wmgroot** [comment]
Progressive sync doesn't leverage Application names at all, it utilizes label selectors on the generated Application to determine which Applications belong to which step for syncing. You can freely template labels on your generated Applications to have a wide degree of freedom in how you order your Applications. 

https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#rollingsync

I don't believe there's a need to implement any kind of Application name regex matching, but let us know here if you think you have a use case that warrants it.

**Comment by DesmondH0** [comment]
> Progressive sync doesn't leverage Application names at all, it utilizes label selectors on the generated Application to determine which Applications belong to which step for syncing. You can freely template labels on your generated Applications to have a wide degree of freedom in how you order your Applications.
> 
> https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#rollingsync
> 
> I don't believe there's a need to implement any kind of Application name regex matching, but let us know here if you think you have a use case that warrants it.

yes, but current progressive-syncs are needed to be exact match in steps for triggering the sync.
which is annoying when we wanted to have the last steps for sync all the apps, we cannot do things like:
```
      - matchExpressions:
        - key: app
          operator: In
          values:
          - priority-app
       # Deploy rest of the apps
       - matchExpressions:
        - key: app
          operator: In
          values:
          - "*"
```

I know we could leverage `notIn` key for excluding apps from previous steps, but it would be much more flexible if supporting regex / globs
