### ISSUE TITLE
Excessive requests to git repository on commit to monorepo w/ multi-source apps

### ISSUE THREAD

**Issue by de-slalonde** [argoproj/argo-cd#14725]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

With 71 multi-source applications in a monorepo (in Bitbucket), a single commit triggers 271 requests to the git repository (11 fetch, 260 ls-remote). Logs show 333 "getting manifest cache" entries, with 15 cache hits and 318 cache misses. Example application sources:

```shell
sources:
  - path: manifests/my-app/
    repoURL: git@bitbucket.org:my-company/argo.git
    targetRevision: HEAD
  - chart: my-chart
    helm:
      releaseName: my-release
      valueFiles:
      - $values/values/my-app-values.yaml
    repoURL: my-helm-repo/charts
    targetRevision: 0.1.0
  - ref: values
    repoURL: git@bitbucket.org:my-company/argo.git
    targetRevision: HEAD
``` 

**To Reproduce**

Make any commit to the repository.

**Expected behavior**

Far fewer requests to the git repository and more cache hits.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T19:42:32Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```shell
msg="getting manifests cache" appName=tenant-1 appSrc="{\"appSrc\":{\"repoURL\":\"\",\"ref\":\"values\"},\"srcRefs\":{\"$values\":{\"repoURL\":\"git@bitbucket.org:my-company/argo-dev.git\",\"project\":\"\",\"targetRevision\":\"HEAD\",\"chart\":\"\"}}}
```

In depth discussion with @crenshaw-dev on Slack with more detail. https://cloud-native.slack.com/archives/C01TSERG0KZ/p1690317861587929

Discussed at Argo SIG Scalability meeting on July and @ishitasequeira volunteered to take a look.

**Comment by de-slalonde** [comment]
@ishitasequeira in terms of an example repo, I'm not sure if you just want a detailed description of what the applications look like, where files are, etc, or if you need an actual functioning repository that you can point ArgoCD at? The latter may be difficult as we're running many private internal applications, secrets, etc.

Applications typically look like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    fast-lane-wave: nowave
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: tenants
  name: qa1
  namespace: argocd
spec:
  destination:
    namespace: tnnt-qa1
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: clusters/cluster1/manifests/tenants/qa1
    repoURL: git@bitbucket.org:mycompany/argo-dev.git
    targetRevision: HEAD
  - chart: tenant-chart
    helm:
      releaseName: qa1
      valueFiles:
      - $values/clusters/cluster1/values/tenants/qa1-values.yaml
    repoURL: myhelmrepo/charts
    targetRevision: 0.13.2
  - ref: values
    repoURL: git@bitbucket.org:mycompany/argo-dev.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

With the following repository structure:

```
├── clusters
│   └── cluster1
│       ├── applications
│       │   ├── external
│       │   │   ├── cert-mgr-argo.yaml
│       │   │   ├── ext-dns-argo.yaml
│       │   │   └── ingress-argo.yaml
│       │   ├── internal
│       │   │   ├── internal-app-1-argo.yaml
│       │   │   ├── internal-app-2-argo.yaml
│       │   │   └── internal-app-3-argo.yaml
│       │   ├── mmts
│       │   │   ├── mmt-1-argo.yaml
│       │   │   ├── mmt-2-argo.yaml
│       │   │   └── mmt-3-argo.yaml
│       │   └── tenants
│       │       ├── qa1-argo.yaml
│       │       ├── qa2-argo.yaml
│       │       └── qa3-argo.yaml
│       ├── manifests
│       │   ├── external
│       │   │   ├── cert-mgr
│       │   │   │   ├── cert-mgr-clusterissuer-prod.yaml
│       │   │   │   └── cert-mgr-clusterissuer-staging.yaml
│       │   │   ├──  ext-dns
│       │   │   │   └── ext-dns-svc-acc-ss.yaml
│       │   │   └── ingress
│       │   │       └── ingress-lua-plugin-cm.yaml
│       │   ├── internal
│       │   │   ├── internal-app-1
│       │   │   │   └── internal-app-1-ss.yaml
│       │   │   ├── internal-app-2
│       │   │   │   └── internal-app-2-ss.yaml
│       │   │   └── internal-app-3
│       │   │       └── internal-app-3-ss.yaml
│       │   ├── mmts
│       │   │   ├── mmt-1
│       │   │   │   └── mmt-1-ss.yaml
│       │   │   ├── mmt-2-main
│       │   │   │   └── mmt-2-ss.yaml
│       │   │   └── mmt-3-main
│       │   │       └── mmt-3-ss.yaml
│       │   └── tenants
│       │       ├── qa1
│       │       │   └── qa1-secrets-ss.yaml
│       │       ├── qa2
│       │       │   └── qa2-secrets-ss.yaml
│       │       └── qa3
│       │           └── qa3-secrets-ss.yaml
│       └── values
│           ├── external
│           │   ├── cert-mgr-values.yaml
│           │   ├── ext-dns-values.yaml
│           │   └── ingress-values.yaml
│           ├── internal
│           │   ├── internal-app-1-values.yaml
│           │   ├── internal-app-2-values.yaml
│           │   └──internal-app-3-values.yaml
│           ├── mmts
│           │   ├── mmt-1-values.yaml
│           │   ├── mmt-2-values.yaml
│           │   └── mmt-3-values.yaml
│           └── tenants
│               ├── qa1-values.yaml
│               ├── qa2-values.yaml
│               ├── qa3-values.yaml
└── yamllint_config
```

**Comment by de-slalonde** [comment]
I've created a public repo that also exhibits this issue: https://bitbucket.org/sam-lalonde/argocd-14725. I created the app of apps defined in `app-of-apps.yaml` at the root of the repo. I have 10 nginx apps configured, with a custom values.yaml in the same repo, and a directory with extra manifests (just a configmap) also in the same repo. Once everything is settled down, if I change a value for a single app, for example, change `revisionHistoryLimit` in one of the values.yaml and commit, the webhook informs argo and in the logs I get:

getting manifests cache: 83
cache hit: 23
cache miss: 60

From my monitoring I can see:
git fetch: 6
git ls-remote: 52

That's quite a few git requests for just 10 apps, I'm hoping to run 500+ apps.

**Comment by ishitasequeira** [comment]
Thanks @de-slalonde for the detailed explanation and an example. 

One thing I noticed is that we are using the same repository with same TargetRevision (`HEAD`) in every app within app-of-apps. The repo is being used as a source for app-of-apps, as one of the sources and as a `ref` source within each app. So, whenever there is a new commit, it tries updating the app-of-apps, each app inside app-of-apps, and each source inside each app. 

The point to consider here - argocd should have used the cache, once updated by any app, because the Repo and the Revision(`HEAD`) used in every app and source are same. 

Still investigating 🤔 🔍 🔬

**Comment by de-slalonde** [comment]
In the logs I can see dozens of cache misses in the first 500ms after the change is detected. They couldn't possibly get an updated cache when it's all happening so fast. (This is just a small part of the logs).

<img width="598" alt="image" src="https://github.com/argoproj/argo-cd/assets/50598818/931aba55-6f08-437a-805e-8468c694d3e8">

Is the app of apps pattern making this issue even worse for me? Our plan was to have ALL our apps in a single app-of-apps, but we could consider breaking things up into groups of apps-of-apps, or I suppose (not ideal) move away from app-of-apps altogether and make API calls to create and delete apps instead of just dropping them into the repo.

**Comment by crenshaw-dev** [comment]
I'd be very surprised if the issue were the app-of-apps. I think our investigation showed that most of the attempts to hit the cache are from the `ref: values` source of each app. I suspect that we're not effectively de-duping those requests, maybe because we're not holding a lock on the repo at the target revision like (I believe) we do for non-ref sources.

**Comment by de-slalonde** [comment]
@crenshaw-dev  Once the repo has been pulled, and the cache has been updated, does Argo then have the information that wasn't available in the Bitbucket webhook paylook to help it know what has actually changed so that unaffected applications can be just "nudged to the next revision" (or whatever that was you mentioned in the meeting).

**Comment by s7an-it** [comment]
Are you using webhooks by he way and path based computation to decide if cache should be used or not as ast time (2 months I tested in Bitbucket it wasn't working at all).
Outside of that I had a talk with BB team regarding IP request from Argo and I am on quite low number, I wonder if that changed in past few weeks and I am in the app of app of app of app of app of app patterns with thounds of apps. I run still 2.6.9 but wll switch in to 2.8.1 probably.

**Comment by phanama** [comment]
@de-slalonde @ishitasequeira @crenshaw-dev 

I recently encountered a similar issue, using a monorepo w/multi-source apps generated by AppSet. The repo-server logs showed mostly cache miss, something like:

```text
level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://REPO_URL.git,Path:,TargetRevision:master,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:values,}/SHA1_VALUE"
```

Looking at the cache miss logs, most have `Ref:values`, making me suspect the helm values ref source as the cause. I somehow fixed the cache miss issue by adding specific directory to the ref source:

```yaml
sources:
  - directory:
      exclude: *
    path: my-app/
    repoURL: https://REPO_URL
    targetRevision: HEAD
    ref: values
  - chart: CHART_NAME
    repoURL: CHART_URL
    targetRevision: v0.0.1
    helm:
      version: v3
      releaseName: RELEASE_NAME
      valueFiles:
      - $values/my-app/values.yaml
```

After doing this, our repo-server now shows 100% cache hit:

```text
level=info msg="manifest cache hit: &ApplicationSource{RepoURL:https://REPO_URL.git,Path:my-app,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:&ApplicationSourceDirectory{Recurse:false,Jsonnet:ApplicationSourceJsonnet{ExtVars:[]JsonnetVar{},TLAs:[]JsonnetVar{},Libs:[],},Exclude:*,Include:,},Plugin:nil,Chart:,Ref:values,}/SHA1"`
...
```

Our repo-server then shows an almost-total decrease of the `git fetch` metrics; though the `git ls-remote` number stays the same.

git fetch:

<img width="1755" alt="image" src="https://github.com/argoproj/argo-cd/assets/11147376/e28cd122-ffef-4771-a448-7951753b1a7a">

git ls-remote:

<img width="1724" alt="image" src="https://github.com/argoproj/argo-cd/assets/11147376/8bd1ed75-b6c2-473a-beb7-4a0e363cd2ef">

**Comment by crenshaw-dev** [comment]
I'm sitting at my desk chuckling at this workaround. That's an incredible find. Makes me think there must be something wrong with how we populate the cache when the source is a values-only source (i.e. doesn't contribute any manifests to the Application). Adding a no-manifests manifest source must force it to be cached properly.

**Comment by ryan-dyer-sp** [comment]
We also have encountered this issue and the workaround provided [here](https://github.com/argoproj/argo-cd/issues/14725#issuecomment-1693495437) worked for us.

**Comment by tribu** [comment]
+1 to this issue. In my case we have a mono git repo and multi apps/charts with a dependency chart. The above work around didnot fix the issue for us. We are still facing ~12k git requests per minute.  also in our case the requests were"Cache Hit" and still causing rate limit  details are [here](https://github.com/argoproj/argo-cd/issues/14725#issuecomment-1693495437)

**Comment by phanama** [comment]
@tribu Are you still seeing both `git ls-remote` and `git fetch` requests or just `git ls-remote` requests?

**Comment by de-slalonde** [comment]
In my case I was able to use the concepts from that workaround to cut down on my `git fetch`, but my `git ls-remote` are still through the roof.

**Comment by ryan-dyer-sp** [comment]
I feel there is something similar in regards to the behavior of ls-remote.  I have effectively 5 mono repos.  Looking at the ls-remote metrics for each repo we see (per hour)
```
repo1 - 75
repo2 - 480
repo3 - 600
repo4 - 5300
repo5 - 4500
```

all of these mono repos, except repo4 have the same number of applications defined to pull values files from these repos.  repo4 has 4x the amount of apps defined.

in the case of repo1 the file is a singular static file. eg.
```
valueFiles:
- $values/file.yaml
```

In the case of repo2 and repo3, they use a variable.  eg.
```
valueFiles:
- $values/{{ .Values.clusterName}}.yaml
```

In the case of repo4, they use a variable like repo2/3, but on 4 of the clusters, there is an additional variable
```
valueFiles:
- $values/{{ .Values.clusterName}}.yaml
{{- if special cluster }}
- $values/{{ .Values.environment }}.yaml
- $values/file.yaml
{{- end }}
```

and finally in the case of repo5, each of the 4 apps (per cluster) references a different static file.  This one I find the most interesting as I would simply expect this to produce 4x the volume of ls-remotes as repo1, not 60x.  eg
app1
```
- $values/app1.yaml
```
app2
```
- $values/app2.yaml
```

**Comment by andrleite** [comment]
@phanama 
+1 We tried the suggested workaround by adding the path to the ref source. We got the same result. Reduce the git fetch API calls but ls-remote is still the same. Similar behavior we mentioned #12878

**Comment by laurentiusoica** [comment]
Same here. Multi source apps with an OCI registry as a source for helm charts and a single Git repository as a source for configuration values. In my case Argo is short polling every 3 minutes; no webhooks configured. I can see excessive number of git requests not just on a new commit, but for every 3 minutes. applying the work around fetch does not grow anymore. ls-remote still growing. Although there is a single git repository serving config files, the repo server runs several ls-remote for each new reconciliation cycle.

**Comment by LiamMccafferty-bud** [comment]
Can confirm we are also experiencing the same behaviour deploying from a mono-repo hosting lots of values files separate from the git repo we deploy the helm chart from. 

We added all the files we care about to a section like below and can confirm we are still getting dozens of cache misses a second. 

  ```
directory:
    includes: "{file1.yaml, file2.yaml}"
    excludes: "*"
```

**Comment by kncesarini** [comment]
Is this issue still being worked on or supposed to be resolved? We're experiencing the same issue in 2025. Argo version v2.14.11+8283115. This is ~ the applicationset we use for ~30 services, which seems to be generating ~30gb of github traffic per day (repos are small).

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: company-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'git@github.com:Company-Org/company-cluster.git'
        revision: main
        directories:
          - path: clusters/dev/company-services/*
  template:
    metadata:
      name: '{{path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: company
      sources:
        - repoURL: 'git@github.com:Company-Org/charts.git'
          targetRevision: v2.2.2
          path: company-service
          helm:
            valueFiles:
              - '$valuesRef/clusters/dev/company-services/common-values.yaml'
              - '$valuesRef/common-values/company-services/{{path.basename}}/values.yaml'
              - '$valuesRef/clusters/dev/company-services/{{path.basename}}/app.yaml'
        - repoURL: 'git@github.com:Company-Org/company-cluster.git'
          targetRevision: main
          ref: valuesRef
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: services
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
          - PrunePropagationPolicy=orphan
        automated:
          prune: false
          selfHeal: true
```
