### ISSUE TITLE
scmProvider for gitlab should export a Normalized version of the organization value

### ISSUE THREAD

**Issue by prune998** [argoproj/argo-cd#14768]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In Gitlab it is possible to use sub-folders for organizations, like /orgA/teamB/projectC.

In that cas you would git clone git@gitlab.server/orgA/teamB/projectC.git

When using An AppSet searching for all matching repos under the orgA, the returned organization contains / like orgA/teamB.

**To Reproduce**

Here's an appset that will fail if there is a matching project in a subgroup like `orgA/teamB/projectC`:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
  labels:
  name: org-a
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
              environment: qa
          values:
            environment: qa
      - scmProvider:
          cloneProtocol: https
          filters:
          - branchMatch: deployment
            pathsExist:
            - deployments/argocd/qa.yaml
          gitlab:
            allBranches: false
            api: https://gitlab.server.net/
            group: "orga"
            includeSubgroups: true
            tokenRef:
              key: token
              secretName: my-gitlab-token
  template:
    metadata:
      name: '{{ organization }}-{{ repository }}-{{ nameNormalized }}'
    spec:
      destination:
        namespace: orga
        server: '{{server}}'
...
```

Here the template name will be orgaA/teamB-projectC-cluster_name, which is not a valid name.

Appset Controler does log an error:

```
applicationset-controller 
time="2023-07-27T20:15:35Z" 
level=error 
msg="failed to unchanged Application" 
action=unchanged 
app=orgaA/teamB-projectC-cluster_name 
appSet=orga 
error="Application.argoproj.io \"orgaA/teamB-projectC-cluster_name\" is invalid: 
  metadata.name: Invalid 
  value: \"orgaA/teamB-projectC-cluster_name\": 
      a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
```

For example, the cluster name provided by the clusters generator does provide a normalized version of the name as nameNormalized. This would solve the issue.

**Expected behavior**

The appset should discover all the subprojects and we should be able to use the resulting `organization` value in a template.

**Version**

```shell
argocd: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T22:48:59Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.9+0ee33e5.dirty
```
