### ISSUE TITLE
GPG signature validation doesn't work on multi-source values

### ISSUE THREAD

**Issue by shmargum** [argoproj/argo-cd#14773]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

An application with helm chart from source A and values from source B says target revision in source B is not signed when it is indeed signed.

**To Reproduce**

```yaml
sources:
  - repoURL: 'git@github.com:my-org/my-repo-1.git'
    path: charts/test
    targetRevision: master
    helm:
      valueFiles:
        - values/test.yaml
          $values1/charts/test/values/test.yaml
  - repoURL: 'git@github.com:my-org/my-repo-2.git'
    targetRevision: master
    ref: values1
```

**Expected behavior**

Expecting ArgoCD to recognize the commit is signed.

**Screenshots**

<img width="931" alt="Screenshot 2023-07-28 at 2 15 46 PM" src="https://github.com/argoproj/argo-cd/assets/895880/20fa4672-b0a9-4166-8802-781e6fea7dd6">
<img width="245" alt="Screenshot 2023-07-28 at 2 17 48 PM" src="https://github.com/argoproj/argo-cd/assets/895880/f31de7a1-5dc4-4840-a9d3-b0fa36a5d005">

**Version**

```shell
v2.7.7+4650bb2.dirty
```

**Logs**

```
Paste any relevant application logs here.
```
