### ISSUE TITLE
[2.8-rc6] "History and Rollback" and "more" pages crash for app with Helm Chart from chart repo

### ISSUE THREAD

**Issue by morey-tech** [argoproj/argo-cd#14854]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

"History and Rollback" and the "more" of the sync status or last sync box pages crash for an app with Helm Chart from a chart repo.

Likely related to https://github.com/argoproj/argo-cd/pull/11575

**To Reproduce**

1. Deploy 2.8-rc6
```shell
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0-rc6/manifests/install.yaml
```
2. Create this example application pulling a Helm chart from a chart repo.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    name: kind
  project: default
  source:
    chart: hello-world
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    helm:
      values: |
        replicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
3. Click on History and Rollback or the three dots in the top right of the sync status or last sync box.

The result is the "Something went wrong!" page shown in the screenshot below.
```
Stacktrace:

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.children (https://localhost:8080/main.157f2067183bd10ecda3.js:2:1973159)
    at Fr.render (https://localhost:8080/main.157f2067183bd10ecda3.js:2:1565823)
    at zi (https://localhost:8080/main.157f2067183bd10ecda3.js:2:820282)
    at Hi (https://localhost:8080/main.157f2067183bd10ecda3.js:2:820077)
    at Es (https://localhost:8080/main.157f2067183bd10ecda3.js:2:855701)
    at Sl (https://localhost:8080/main.157f2067183bd10ecda3.js:2:847160)
    at xl (https://localhost:8080/main.157f2067183bd10ecda3.js:2:847085)
    at hl (https://localhost:8080/main.157f2067183bd10ecda3.js:2:844108)
    at https://localhost:8080/main.157f2067183bd10ecda3.js:2:795769
    at t.unstable_runWithPriority (https://localhost:8080/main.157f2067183bd10ecda3.js:2:870971)
```

**Expected behavior**

The Helm Chart metadata should be displayed as it does for a Helm chart from a repo.

For example, the page does not crash for this app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    namespace: default
    name: kind
```

**Screenshots**

<img width="904" alt="Xnapper-2023-08-02-11 07 05" src="https://github.com/argoproj/argo-cd/assets/4213435/fcd8bdea-978d-4d6e-8313-3196aade7f11">

**Version**

```json
{
    "Version": "v2.8.0-rc6+40fda39",
    "BuildDate": "2023-07-28T13:48:04Z",
    "GitCommit": "40fda394eb3883d62112fc73b17fc201392ce0b3",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/arm64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

argocd-server
```
time="2023-08-02T15:19:01Z" level=info msg="received unary call /repository.RepositoryService/GetAppDetails" grpc.method=GetAppDetails grpc.request.content="source:<repoURL:\"https://helm.github.io/examples\" path:\"\" targetRevision:\"0.1.0\" helm:<releaseName:\"\" values:\"replicaCount: 1\\n\" version:\"\" passCredentials:false ignoreMissingValueFiles:false skipCrds:false > chart:\"hello-world\" ref:\"\" > appName:\"hello-world-dev\" appProject:\"default\" " grpc.service=repository.RepositoryService grpc.start_time="2023-08-02T15:19:01Z" span.kind=server system=grpc
time="2023-08-02T15:19:01Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2023-08-02T15:19:01Z" grpc.time_ms=9.326 span.kind=server system=grpc
time="2023-08-02T15:19:01Z" level=info msg="received unary call /application.ApplicationService/RevisionChartDetails" grpc.method=RevisionChartDetails grpc.request.content="name:\"hello-world-dev\" revision:\"0.1.0\" appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2023-08-02T15:19:01Z" span.kind=server system=grpc
time="2023-08-02T15:19:01Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=RevisionChartDetails grpc.service=application.ApplicationService grpc.start_time="2023-08-02T15:19:01Z" grpc.time_ms=4.826 span.kind=server system=grpc
time="2023-08-02T15:19:02Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2023-08-02T15:18:37Z" grpc.time_ms=24884.512 span.kind=server system=grpc
time="2023-08-02T15:19:02Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2023-08-02T15:18:37Z" grpc.time_ms=24892.64 span.kind=server system=grpc
```

argocd-repo-server
```
time="2023-08-02T15:20:10Z" level=info msg="revision chart details cache hit: https://helm.github.io/examples/hello-world/0.1.0"
time="2023-08-02T15:20:10Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetRevisionChartDetails grpc.service=repository.RepoServerService grpc.start_time="2023-08-02T15:20:10Z" grpc.time_ms=0.3 span.kind=server system=grpc
time="2023-08-02T15:20:10Z" level=info msg="app details cache hit: 0.1.0/"
time="2023-08-02T15:20:10Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetAppDetails grpc.service=repository.RepoServerService grpc.start_time="2023-08-02T15:20:10Z" grpc.time_ms=0.497 span.kind=server system=grpc
```
