### ISSUE TITLE
multi-line plugin parameter strings are corrupted if edited in ui

### ISSUE THREAD

**Issue by thesuperzapper** [argoproj/argo-cd#14876]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Right now, `Applications` which set multi-line parameter strings can not be safely edited in the Web UI as the data will become corrupted (newlines stripped out) after saving.

Additionally, the Web UI does not display the newlines, or provide any method to add a newline.

This issue is very problematic as it makes it impossible to pass YAML a plugin parameter (at least, from the UI).

__Here is an example of an `Application` with a multi-line string parameter:__

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "XXXX"
    path: "XXXX"
    plugin:
      name: "my-plugin"
      parameters:
        - name: "multiline-string"
          string: |
            my:
              yaml:
                values:
                  are: "here"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
```

__Here is a screenshot of a multi-line string (named "VALUES") which is not displayed properly in the UI:__

![Screenshot 2023-08-02 at 22 17 00](https://github.com/argoproj/argo-cd/assets/5735406/60f734a8-6a4f-44dc-b426-ab8f31f19fdd)

**Version**

```shell
2.7.10
```
