### ISSUE TITLE
Problem with MutatingAdmissionWebhookConfiguration object used by Istio

### ISSUE THREAD

**Issue by mjasion** [argoproj/argo-cd#1487]
**Describe the bug**
`Istio-sidecar-injector` POD is changing webhooks `clientConfig.caBundle` field in object `istio-sidecar-injector` (kind `MutatingWebhookConfiguration`) on startup

On installation this field is empty, but POD is setting own certificate. After this ArgoCD recognizes `MutatingWebhookConfiguration` object as out of sync.

After creating again `MutatingWebhookConfiguration` object(deleting and syncing) Argo says it is in sync.

But after restarting POD, the field is overridden again. And ArgoCD will say this object is out of sync. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5058132/56361963-f6a7a680-61e8-11e9-986b-a9ea203432f8.png)

**Additional context**
We are installing istio helm chart from our private fork:
```yaml 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-dev.yaml
    path: istio
    repoURL: git@example.com:helm-charts/istio.git
    targetRevision: master
  syncPolicy:
    automated: {}
```
And we are using sidecar injector mode
