### ISSUE TITLE
Enhancement Proposal: pull OIDC `clientID` and `issuer` from existing secret

### ISSUE THREAD

**Issue by jessebot** [argoproj/argo-cd#14899]
# Summary
Pull OIDC `clientID` and `issuer` from an existing Kubernetes Secret.

# Motivation

Right now we have to specify the OIDC `issuer` and `clientID` directly in plain text via the `values.yaml` when applying the argo-cd helm chart. It's possible to specify a `clientSecret` in another secret, but not the `clientID` or `issuer`. This information is still considered private, so it'd be good to have this obscured.

# Proposal

I'd like to see the issuer and clientID also optionally called from an existing secret, in the same way that we can specify a clientSecret in another secret, example currently:
```yaml
    # clientSecret comes from the k8s secret, argocd-provider, with the key oidc.provider.clientSecret
    oidc.config: |
      name: provider
      issuer: https://my.domain/realms/coolrealm
      clientID: argocd
      clientSecret: $argocd-provider:oidc.provider.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
```

Proposed update:

```yaml
    # clientSecret comes from the k8s secret, argocd-provider, with the key oidc.provider.clientSecret
    # clientID comes from the k8s secret, argocd-provider, with the key oidc.provider.clientID
    # issuer comes from the k8s secret, argocd-provider, with the key oidc.provider.issuer
    oidc.config: |
      name: provider
      issuer: $argocd-provider:oidc.provider.issuer
      clientID: $argocd-provider:oidc.provider.clientID
      clientSecret: $argocd-provider:oidc.provider.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
```

### Additional context

This would make everything a bit more secure and allow for more open sourcing of Argo CD configurations without exposing any useful information for attackers.

Originally opened this in https://github.com/argoproj/argo-helm/issues/2199 by accident. Sorry about that. 🙏 

I haven't looked at the code yet to see how difficult this would be, but I will as soon as I can. The farthest I got was checking [utils/settings/settings.go](https://github.com/argoproj/argo-cd/blob/master/util/settings/settings.go), but couldn't figure out why issuer/clientID don't work the same way as clientSecret. I did check for similar feature requests in this repo and the argo-helm repo, but couldn't find any. If there's already an enhancement proposal that I've missed, please let me know and I'll close this one.
