### ISSUE TITLE
Authentication required when creating an application with GitLab deploy tokens

### ISSUE THREAD

**Issue by Oduig** [argoproj/argo-cd#1491]
**Describe the bug**

With the help of https://github.com/argoproj/argo-cd/issues/901, I succeeded in adding a GitLab repository to ArgoCD with a deployment token. This is a way for us not to have to use my private account to gain access to the repository.

The git repository link with a deploy token looks like this, with a redacted password that only uses characters from [a-z] [A-Z] [0-9]:

`https://gitlab%2Bdeploy-token-1:<...password...>@gitlab8.company.nl/guidoj/myproject-deployment.git`

When adding the repository, this results in a "Successful" state. I can also clone the repository with the above URL. However, when I try to create an application with it, I see the following error in the argocd-server logs.

`time="2019-04-19T11:28:16Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = authentication required" grpc.code=Unknown grpc.method=ListApps grpc.service=repository.RepositoryService grpc.start_time="2019-04-19T11:28:16Z" grpc.time_ms=228.818 span.kind=server system=grpc`

**To Reproduce**
1. Add a private GitLab repository via a deploy token (see https://github.com/argoproj/argo-cd/issues/901)
2. Create an application
3. Select the created repository, click next
4. See "Authentication required" error

**Expected behavior**
Repository is read and the contents are shown in the ArgoCD UI

**Screenshots**
![image](https://user-images.githubusercontent.com/3661031/56422546-48fbcc80-62a8-11e9-9d10-a0bf56dd8871.png)

**Additional context**
Same problem with the argo CLI.

**Comment by alexec** [comment]
Have you read this guide:

https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#repositories

I don't think you should username and password into the repo URL. Instead, use Kubernetes secrets for this.

**Comment by Oduig** [comment]
Thank you, I wasn't aware this would work with deploy tokens as a regular username/password combination. Turns out it does!

**Comment by vjtm** [comment]
Hi there,

I am having issues using the declarative setup for the repositories. I am using argo-cd (v1.7.8) on k8s v1.18.8 (kind 0.9.0). ArgoCD is up and running fine.

This is the content of my ```argocd-cm``` from the ```argocd``` namespace (This is a test repo from a private project in Azure DevOps):

```argocd-cm.yaml```:
```
apiVersion: v1
data:
  repositories: |
    - url: https://dev.azure.com/vicenstomas/Test/_git/azure-pipelines-canary-k8s-manifests
      type: git
      passwordSecret:
        key: password
        name: repo-secret
      usernameSecret:
        key: username
        name: repo-secret
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
```
This is the ```repo-secret.yaml``` that references the ```argocd-cm``` ConfigMap:
```
apiVersion: v1
data:
  password: <base64_password>
  username: <base64_username>
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
type: Opaque
```
Then I run
```
$ kubectl apply -f argocd-cm.yaml
```
The argocd web UI show the repo but in a ```Failed``` state. The logs from the ```argocd-repo-server-xxx``` pod show it is a ```error="authentication required"```

But, If I create the repo via the web UI using exactly the same URL and credentials it works perfectly fine.
I see the argocd manages the creation of the k8s secret for the credentials ```repo-dddddddd``` (d for digits) and uses that name in the ```argocd-cm``` as well.

For testing purposes I tried to add a public repo from github without any credentials (via yaml) and it worked fine as well.

What am I missing here? Maybe a bug?

Thanks!
