### ISSUE TITLE
Helm chart application local `diff` fails with open Chart.yaml: no such file or directory

### ISSUE THREAD

**Issue by cyrus-mc** [argoproj/argo-cd#14948]
**Describe the bug**

I am attempting to do a local app diff (or app manifests) for the following application

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /vault/operator
  labels:
    app.kubernetes.io/name: vault-operator
  name: vault-operator
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/charts/vault-operator
    repoURL: https://github.com/bank-vaults/vault-operator.git
    helm:
      values: |-
        image:
          repository: ghcr.io/bank-vaults/vault-operator
          tag: v1.21.2

        # the namespace the operator watches for Vault CR objects
        watchNamespace: vaultj
    targetRevision: v1.21.1
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - preserveResourcesOnDeletion=true
    - CreateNamespace=true
```

Doing so results in the following fatal error:

```
FATA[0002] open Chart.yaml: no such file or directory
```

**To Reproduce**

Using the above application.yaml, locally run

`argocd app diff vault-operator --server argo.xxxx --auth-token xxx' --local .`

**Expected behavior**

Expected behavior is that the local CLI would download the referenced `helm` chart and render it locally with the values specified in the `application.yaml` and then diff that with the current state in ArgoCD.

But it appears like it is expecting to find `Chart.yaml` locally rather than cloning the chart source repo. 

**Version**

```shell
argocd: v2.7.10+469f257.dirty
  BuildDate: 2023-07-31T23:19:45Z
  GitCommit: 469f25753b2be7ef0905a11632a6382060bcae99
  GitTreeState: dirty
  GoVersion: go1.20.6
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.11+697fd7c
```
