### ISSUE TITLE
ProgressiveSync syncs all apps concurrently following an initial progressiveSync deployment

### ISSUE THREAD

**Issue by charlrvd** [argoproj/argo-cd#14946]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the applicationSet ProgressiveSync feature, an initial deployment will as expected, create all applications and sync in order as defined in the applicationSet `spec.strategy.rollingSync.steps` list.
The issue happens when more than one of the generated application gets a diff on the next argocd refresh, the expected progressive sync steps are not respected and any application that gets diffed will start syncing immediately.

**To Reproduce**

I've been using an applicationSet similar to 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: progressive-sync-test
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
        - appName: main1
          priority: stage1
          repo: 'https://github.com/org/repo'
          path: 'app/development/foo'
          revision: tmp-test-progressive-syncs
        - appName: main2
          priority: stage1
          repo: 'https://github.com/org/repo'
          path: 'app/development/foo'
          revision: tmp-test-progressive-syncs
        - appName: stage-last
          priority: stage-last
          repo: 'https://github.com/org/repo'
          path: 'app/development/bar'
          revision: tmp-test-progressive-syncs
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: syncPriority
              operator: In
              values:
                - stage1
        - matchExpressions:
            - key: syncPriority
              operator: In
              values:
                - stage-last
  template:
    metadata:
      name: '{{.appName}}'
      labels:
        syncPriority: '{{.priority}}'
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        path: '{{.path}}'
        targetRevision: '{{.revision}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: test-sync
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
```

The foo apps are just deploying a pod with an init container having a sleep in it just to make it seem like it's taking time to deploy an app and the last app was a single k8s job.

**Expected behavior**

The progressive sync keeps a sync order on subsequent updates if multiple apps are updated during a same refresh window. For example if foo and bar gets updated I would expect foo to be sync'd first and finally bar.

**Screenshots**

NA

**Version**

2.7.10

**Logs**

NA
