### ISSUE TITLE
Error when creating Workflow from CronWorkflow using 2.8's new feature

### ISSUE THREAD

**Issue by mcanevet** [argoproj/argo-cd#14962]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The "create job from Cronjob" feature from 2.8 is working fine, but I get this weird error message for the "create Workflow from CronWorkflow":

```
Unable to execute resource action: error executing Lua resource action: <string>:53: attempt to index a non-table object(nil) with key 'workflows.argoproj.io/controller-instanceid' stack traceback: <string>:53: in main chunk [G]: ?
```

**To Reproduce**

Here is my `CronWorkflow` object:

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  concurrencyPolicy: Replace
  schedule: '* * * * *'
  startingDeadlineSeconds: 0
  suspend: false
  workflowSpec:
    entrypoint: hello-hello-hello
    templates:
      - name: hello-hello-hello
        steps:
          - - arguments:
                parameters:
                  - name: message
                    value: hello1
              name: hello1
              template: whalesay
          - - arguments:
                parameters:
                  - name: message
                    value: hello2a
              name: hello2a
              template: whalesay
            - arguments:
                parameters:
                  - name: message
                    value: hello2b
              name: hello2b
              template: whalesay
      - container:
          args:
            - '{{inputs.parameters.message}}'
          command:
            - cowsay
          image: docker/whalesay
        inputs:
          parameters:
            - name: message
        name: whalesay
```

**Version**

```shell
2.8.0
```
