### ISSUE TITLE
Document additional permissions for ApplicationSets in any namespace

### ISSUE THREAD

**Issue by jocelynthode** [argoproj/argo-cd#15001]
# Summary

A new feature was introduced in `2.8.0` which allows us to use ApplicationSets in any namespace. However, in the documentation there are no mentions of additional permissions that should be added. 

# Motivation

This was specified in the `Applications in any namespace` documentation as well as example ClusterRoles and ClusterRoleBindings embedded in the argocd repository. And I think this would be worth it for ApplicationSets as well

See: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#adapt-kubernetes-rbac

# Proposal

I would propose to add a similar sectin here: https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Appset-Any-Namespace/ as well as example YAML in the repository.

I can do the PR for these changes if this is something we'd like to have.

I'm currently using this lifted from the namespaced role for the applicationset-controller SA:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-server-cluster-appsets
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server-cluster-appsets
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - applicationsets/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applicationsets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: argocd-server-cluster-appsets
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server-cluster-appsets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-server-cluster-appsets
subjects:
- kind: ServiceAccount
  name: argocd-applicationset-controller
  namespace: argocd
```
