### ISSUE TITLE
Support for scheduled ignore difference 

### ISSUE THREAD

**Issue by nduyphuong** [argoproj/argo-cd#15011]
# Summary

What change you think needs making.

# Motivation

We have use case where we use another tool like [kube-downscaler](https://codeberg.org/hjacobs/kube-downscaler) do scheduled down scaling actions. It would be beneficial to have support for ignore sync action during specified time interval.

# Proposal
Something using syntax like what [Event Bridge](https://docs.aws.amazon.com/scheduler/latest/UserGuide/schedule-types.html#cron-based) does here

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  syncPolicy:
    syncOptions:
    - IgnoreInterval="cron(minutes hours day-of-month month day-of-week year)"
```

How do you think this should be implemented?
