### ISSUE TITLE
Argo .metadata.labels accessor error in 2.8.0

### ISSUE THREAD

**Issue by omarkalloush** [argoproj/argo-cd#15025]
Checklist:

* [ ✅ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ✅ ] I've included steps to reproduce the bug.
* [ ✅ ] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to ArgoCD version 2.8.0, Some of the secrets went to Unknown state with the following error
```
ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): .metadata.labels accessor error: contains non-string key in the map: <nil> is of the type <nil>, expected string (retried 5 times).
```

**To Reproduce**

The helm-chart that contains the secret looks like this
```
apiVersion: v1
kind: Secret
metadata:
  name: newrelic
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "vault/secret/path"
data:
  license: <newrelic-license>
```
_helper.tpl
```
{{/*
Common labels
*/}}

{{- define "common.labels" -}}
metaLabel: {{ .Values.app }}-{{ .Release.Name }}
app.kubernetes.io/name: {{ .Values.app }}
helm.sh/chart: {{ .Values.app }}-{{ .Values.chartVersion }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/instance: {{ .Release.Name }}
team: {{ .Values.team }}
provider: {{ .Values.provider }}
environment: {{ .Values.environment }}
{{- end -}}
```

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/100078273/3a8b9a0b-1d26-4774-b1fc-929148b60e1f)

**Version**

```shell
2.8.0
```

**Comment by agaudreault-jive** [comment]
Can you provide the generated Secret from a local `helm template` command? 

The data/stringData is not necessary.

**Comment by omarkalloush** [comment]
```
apiVersion: v1
kind: Secret
metadata:
  name: newrelic
  namespace: profile-api
  labels:
    metaLabel: app-name-here-release-name
    app.kubernetes.io/name: app-name-here
    helm.sh/chart: app-name-here-0.0.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    team: team-name-here
    provider: gcp
    environment: 
  annotations:
    avp.kubernetes.io/path: "vault/secret/path"
data:
  license: <newrelic-license>
```
