### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'kustomize')

### ISSUE THREAD

**Issue by martijnvdp** [argoproj/argo-cd#15038]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When using an application using the new multiple sources feature we often get an error when we try to view the parameters tab of the application in the GUI

`TypeError: Cannot read properties of undefined (reading 'kustomize'`

**To Reproduce**

create an application

```
project: myproject
destination:
  namespace: alb-ingress
  name: in-cluster
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - PrunePropagationPolicy='backgound'
    - CreateNamespace=false
  retry:
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
sources:
  - repoURL: 'https://github.com/my-org/test'
    path: deployments/alb-ingress/overlay/test/cluster-1
    targetRevision: master
    ref: test
  - repoURL: 'https://aws.github.io/eks-charts'
    targetRevision: 1.4.7
    helm:
      valueFiles:
        - $test/deployments/alb-ingress/overlay/test/cluster-1/values.yaml
    chart: aws-load-balancer-controller
```
1. after deployment go to the argocd gui 
2. click on application details 
3. click on parameters

**Expected behavior**

expected to see the application parameters

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/73637849/41679c3a-7b2a-4290-b310-ae4a52e5f5b0)

**Version**

```shell
{
    "Version": "v2.8.0+804d4b8",
    "BuildDate": "2023-08-07T14:25:33Z",
    "GitCommit": "804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by martijnvdp** [comment]
closed issue that looks a bit like this https://github.com/argoproj/argo-cd/issues/12487

**Comment by hackinteach** [comment]
I also got the same problem by having both Kustomize and Helm chart as sources.

My argo-cd version:
```json
{
    "Version": "v2.9.3+6eba5be",
    "BuildDate": "2023-12-01T23:05:50Z",
    "GitCommit": "6eba5be864b7e031871ed7698f5233336dfe75c7",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

My applicationset yaml:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traccar
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: sample
            url: https://<REDACTED>
            branch: main
  template:
    metadata:
      name: "traccar-{{cluster}}"
      labels:
        environment: "{{cluster}}"
        app: traccar
    spec:
      project: default
      sources:
        - path: "apps/traccar/overlays/{{cluster}}"
          repoURL: <REDACTED>
          targetRevision: "{{ branch }}"
        - chart: traccar
          repoURL: https://traccar.github.io/traccar-helm/
          targetRevision: 1.8.0
          helm:
            releaseName: traccar
            valueFiles:
              - $valuesRepo/apps/traccar/helm/values-master.yaml
              - $valuesRepo/apps/traccar/helm/values-{{cluster}}.yaml
        - ref: valuesRepo
          repoURL: <REDACTED>
          targetRevision: "{{ branch }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      destination:
        server: "{{url}}"
        namespace: "traccar"
```

Result when trying to view the parameters on the UI:
<img width="956" alt="Screenshot 2567-01-17 at 11 43 35" src="https://github.com/argoproj/argo-cd/assets/2115896/055b4f11-7c4d-4eed-b102-98260aeafc1b">
