### ISSUE TITLE
Annotated Tag's Commit SHA Not Resolved Properly

### ISSUE THREAD

**Issue by ozlevka-work** [argoproj/argo-cd#15037]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Bug description**

When an application revision is defined by an annotated tag in a multisource application, and one or more of the referenced sources are fetched from the same repository as the main source, the repository validation fails. See the following YAML exampl:  
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    app.of.apps/managed-by: argo-cd
  labels:
    argocd.argoproj.io/instance: cluster-startup
  name: eck-orchestration-app
  namespace: argocd
spec:
  destination:
    namespace: eck-operator
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - helm:
        releaseName: eck-orchestration-app
        valueFiles:
          - $global/values/global-values.yaml
          - $overlay/internal-feeds-dev/argocd/kibana-overlay-values.yaml
          - $overlay/internal-feeds-dev/argocd/elasticsearch-overlay-values.yaml
      path: elasticsearch
      repoURL: 'https://github.com/REDACTED/argocd-apps.git'
      targetRevision: v1.6.0
    - ref: overlay
      repoURL: 'https://github.com/REDACTED/conf.git'
      targetRevision: internal-feeds-dev-cluster
    - ref: global
      repoURL: 'https://github.com/REDACTED/argocd-apps.git'
      targetRevision: v1.6.0
```
The repository validation fails with an error defined in [repository.go file](https://github.com/argoproj/argo-cd/blob/f7bfb3f15b7d3e7524c705e6cf3d18659d14186e/reposerver/repository/repository.go#L730-L733).

The main reason for this failure is: [this line](https://github.com/argoproj/argo-cd/blob/f7bfb3f15b7d3e7524c705e6cf3d18659d14186e/reposerver/repository/repository.go#L402).

**Explanation**
The function on line 402 fetches the HEAD revision of the git repo, and this revision is different from the SHA of the [annotated tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging), However, the validation on line 730 uses the referencedCommit revision, which equals the SHA of the annotated tag. Since the committedSHA and referencedCommitSHA are different, the validation fails.

**Suggestion to Fix**
Avoid using HEAD fetching for multisource applications in line 402.
Suggested code below:
```go
var commitSHA string
if !hasMultipleSources {
	commit, err := gitClient.CommitSHA()
	if err != nil {
		return err
	}
	commitSHA = commit
} else {
	commitSHA = revision
}
```

I'll be happy to discuss this fix, and if the community agrees, I will open a PR for this fix.
