### ISSUE TITLE
kustomization fields are all mandatory

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1504]
**Describe the bug**

You cannot use the `source.kustomization` without all fields.

**To Reproduce**
Create a Kustomize app and go to the UI and edit the "SPEC MANIFEST".
```yaml
source:
  repoURL: 'https://github.com/alexec/argocd-example-apps.git'
  path: kustomize-guestbook
  targetRevision: HEAD
  kustomize:
    images:
    - test
destination:
  server: 'https://35.224.150.196'
  namespace: default
project: default
```

**Expected behavior**

No error.
