### ISSUE TITLE
Google SSO with Dex not working when serving multiple replicas

### ISSUE THREAD

**Issue by gratus-acuitymd** [argoproj/argo-cd#15079]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

We've set up Google SSO with Dex by adding the following to the configmap:
```
  dex.config: |
    connectors:
    - config:
        redirectURI: https://applicationurl/api/dex/callback
        clientID: client id
        clientSecret: secret
        serviceAccountFilePath: /tmp/oidc/googleAuth.json        
        adminEmail: admin@our_actual_domain.com
      type: google
      id: google
      name: Google
```
After login, we just keep ending up at the login screen.

I found [this StackOverflow question](https://stackoverflow.com/questions/74278590/argocd-login-redirect-loop-for-sso) and followed the advice and scaled down to 1 replica. The login started working. As a test I scaled back up to 3 replicas, and it stopped working again.

**To Reproduce**

- Set up google sso using a config similar to the above
- Set up HA with more than 1 replica
- Attempt to login using SSO
- Notice how you are always redirected back to the login

- Scale down to 1 replica
- And notice how it starts working again
- 

**Expected behavior**

We should be able to have SSO and HA.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
