### ISSUE TITLE
SkipDryRunOnMissingResource does not work on Application Level

### ISSUE THREAD

**Issue by jan-di** [argoproj/argo-cd#15095]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [] I've pasted the output of `argocd version`.

**Describe the bug**

We have a Helm Chart that contains multiple resources that are using CRDs, that are not managed by this helm chart. When trying to sync this application, it fails if at least one CRD is not installed in the cluster. This is expected.

To work around this problem, we tried to use `SkipDryRunOnMissingResource` on the ArgoCD Application as SyncOption (not as Annotation!)

```yaml
project: default
source:
  repoURL: (redacted, git url)
  path: .
  targetRevision: main
  helm:
    releaseName: (redacted)
    values: (redacted)
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true # <-- This was added
  retry:
    limit: -1
    backoff:
      maxDuration: 20m
```

ArgoCD still errors while doing the DryRun and complains about the resources where the CRDs are missing. It does not sync any resource, even those which could be synced (CRDs are in place)

If we instead add the Annotation `argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true`to each of the resources in the helm chart, ArgoCD does indeed a partially sync and create all resources where their CRDs are in place. But this requires that you control the helm chart and the annotations.

**To Reproduce**

1. Create a Helm chart that uses resources that require CRDs that are not installed as well as resources that could be synced right away.
2. Create an Application that uses this Helm chart.

**Expected behavior**

ArgoCD just syncs all resources that could be synced, skipping dry run for all other resources where CRDs are missing.

![grafik](https://github.com/argoproj/argo-cd/assets/23323185/587d0527-c761-4a6d-84cd-f1b30d84f087)
(This result is currently only possible by using the annotation method inside the chart)

**Version**

Kubernetes 1.26.2
Argocd 2.7.7
(we don't use the CLI, everything is declaratively described as k8s resources)
