### ISSUE TITLE
secrets not created correctly

### ISSUE THREAD

**Issue by asraroraaman** [argoproj/argo-cd#15117]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

While deploying datadog helm chart through argo we noticed, the value of secret is missing,  although on argo ui, the paramters value is shown correctly, tested deploying with helm instead of argo with the exact configuration works correctly, just with argo the secrets are not populated correctly.

**To Reproduce**

We are deploying helm chart and values stored in git repo:

Chart.yaml
```yaml
apiVersion: v2
name: datadog-agent
description: A Helm chart for datadog agent
type: application
version: 3.33.10

dependencies:
- name: datadog
  version: 3.33.10
  repository: https://helm.datadoghq.com
```

values.yaml
```yaml
datadog:
  apiKey: abcdefghsomerandomkey
```

https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/secret-api-key.yaml

**Expected behavior**

The value in secret data for api-key should be 'abcdefghsomerandomkey'.

**Version**

```shell
argocd-server: v2.6.6+6d4de2e
```
