### ISSUE TITLE
After enable the plugin via the sidecar way, the out of box templating tool Helm not working anymore

### ISSUE THREAD

**Issue by lauralhm** [argoproj/argo-cd#15125]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Hello, I am trying to migrate the argocd plugin from configManagementPlugins to sidecar plugin way as guidance https://argo-cd.readthedocs.io/en/release-2.8/operator-manual/config-management-plugins/.
But after migration, the out of box plugin **Helm** not working anymore. even when I create application from the GUI and set the templating tool to Helm, after saving the application, then check application's parameter found it will be forced change to Plugin:
![image](https://github.com/argoproj/argo-cd/assets/26691514/f1804baa-6bef-4b29-8f70-0683034b7877)
after saving above application, check the application detail, it change to the custom Plugin:
![image](https://github.com/argoproj/argo-cd/assets/26691514/963dfdf6-f3a4-4593-a185-33856f07b361)
**Btw, my custom defined plugins working well.**

two thing wired:
1. My **Helm** view not showing the **Parameters** block
![image](https://github.com/argoproj/argo-cd/assets/26691514/cb6ccc32-6bde-4dc9-83e6-5910e1fff54b)

2. after saving the application, **Manifest** block has no `source.helm` , it's something like:
```
project: default
source:
  repoURL: 'https://github.tools/.***/***/chart-istio.git'
  path: ./grafana
  targetRevision: HEAD
destination:
  server: 'https://api/.***'
  namespace: default
```

after manually add the **helm.valueFiles** back, the application back to normal
```
project: default
source:
  repoURL: 'https://github.tools/.***/***/chart-istio.git'
  path: ./grafana
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://api/.***'
  namespace: default
```
![image](https://github.com/argoproj/argo-cd/assets/26691514/de54ba67-13ac-43ae-aef4-f52688d8a63d)

**To Reproduce**
**argocd version: 2.8.0**
1. my cmp config snippet:
```
  cmp:
    # -- Create the argocd-cmp-cm configmap
    create: true

    # -- Annotations to be added to argocd-cmp-cm configmap
    annotations: {}

    # -- Plugin yaml files to be added to argocd-cmp-cm
    plugins:
      default:
        generate:
          command: [ bash, -c ]
          args: ["helm dependency update > /dev/null && helm template $ARGOCD_ENV_RELEASE_NAME . $ARGOCD_ENV_HELM_FLAGS > all.yaml && [[ $(grep avp_path all.yaml) ]] && argocd-vault-plugin generate all.yaml || cat all.yaml"]
        discover:
          find:
            glob: "**/Chart.yaml"
            command: [bash, -c, grep -q -r 'avp_path' .]
      defaultPlugin:
        init:
          command: [ bash, -c ]
          args: ["/var/run/argocd/custom-plugins/init_default.sh"]
        generate:
          command: [ bash, -c ]
          args: ["/var/run/argocd/custom-plugins/generate_default.sh"]
        discover:
          find:
            glob: "**/Chart.yaml"
            command: [bash, -c, grep -q -r 'avp_path' .]
```
2.   extraContainer config for plugin

```
  # -- Additional containers to be added to the repo server pod
  extraContainers:
    # sidecar for custom plugin default
    - name: custom-plugin-default
      command: [ /var/run/argocd/argocd-cmp-server ]
      envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
        - secretRef:
            name: aws-upscale-vault-audit-user
        - secretRef:
            name: aws-upscale-argo-vault-user
      image: <my-custom-image-repo>
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: default.yaml
          name: argocd-custom-plugins
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin_v1.2.0
          subPath: argocd-vault-plugin_v1.2.0
        - name: helm
          mountPath: /helm-working-dir/repositories.lock
          subPath: repositories.lock
        - name: helm
          mountPath: /helm-working-dir/repositories.yaml
          subPath: repositories.yaml

    # sidecar for custom plugin defaultPlugin
    - name: custom-plugin-defaultplugin
      command: [ /var/run/argocd/argocd-cmp-server ]
      envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
        - secretRef:
            name: aws-upscale-vault-audit-user
        - secretRef:
            name: aws-upscale-argo-vault-user
      image: <my-custom-image-repo>
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: defaultPlugin.yaml
          name: argocd-custom-plugins
        - mountPath: /var/run/argocd/custom-plugins/generate_default.sh
          subPath: generate_default.sh
          name: plugins-dir
        - mountPath: /var/run/argocd/custom-plugins/init_default.sh
          subPath: init_default.sh
          name: plugins-dir
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin_v1.2.0
          subPath: argocd-vault-plugin_v1.2.0
        - name: helm
          mountPath: /helm-working-dir/repositories.lock
          subPath: repositories.lock
        - name: helm
          mountPath: /helm-working-dir/repositories.yaml
          subPath: repositories.yaml

```
3. after enable the sidecar plugin, try to create application with `Helm`, and specify the values.yaml
Then check the application detail--> parameters

**Expected behavior**

When creating application with the Helm templating tool which is come out of box with argocd, application can be redenering correct and not forced to use the custom plugin.

**Screenshots**

**Version**
```
{
    "Version": "v2.8.0+804d4b8",
    "BuildDate": "2023-08-07T14:25:33Z",
    "GitCommit": "804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```
**Logs**
```
time="2023-08-21T09:09:56Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:[https://github.tools.sap/Upscale/chart-istio.git,Path:./grafana,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:,}/6df5621e57512862eedb3f975ab08c959eb8ba3e](https://github.tools.sap/Upscale/chart-istio.git,Path:./grafana,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:,%7D/6df5621e57512862eedb3f975ab08c959eb8ba3e)"
```
Helm shows as nil from the repo server log. but I do feed it with value files
