### ISSUE TITLE
helm.valuesFileSchemes not working with cli and --local

### ISSUE THREAD

**Issue by OnekO** [argoproj/argo-cd#15142]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I run the following command: "argocd app sync myapp --local . --local-repo-root ." always return the same error message: 
```
FATA[0000] the URL scheme 'secrets+gpg-import' is not allowed 
```

In my values.yaml I have the needed values:

```
helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes,
      secrets+age-import, secrets+age-import-kubernetes,
      secrets,
      https
```
Also I have checked my argocd-cm, and there is the valuesFileSchemes data.

**To Reproduce**
- Deploy this app to Argo:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - cluster: default
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'myapp'
      labels:
        app: myapp
    spec:
      project: data
      destination:
        server: '{{url}}'
        namespace: data
      source:
        helm:
          valueFiles:
            - values.yaml
            - secrets+gpg-import:///helm-secrets-private-keys/key.asc?secrets.enc.yaml
        repoURL: ssh://git@mygit/mycorp.git
        targetRevision: main
        path: ./projects/data/apps/myapp
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```
- Try to sync with a local directory: 
```
argocd app sync argo/myapp --local . --local-repo-root .
```

**Expected behavior**

The app would be synced with the local directory
**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.8.0+unknown
  BuildDate: 2023-08-09T03:34:39Z
  GitCommit: 
  GitTreeState: 
  GitTag: 2.8.0
  GoVersion: go1.21.0
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.0+804d4b8
  BuildDate: 2023-08-07T14:25:33Z
  GitCommit: 804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
Kernel version: 6.4.11-arch2-1
Kubelet version: v1.27.4
Container runtime: containerd://1.7.3
```
