### ISSUE TITLE
Support for git targetRevision ranges

### ISSUE THREAD

**Issue by flyingsaucerer** [argoproj/argo-cd#15141]
# Summary
Revision tag ranges are not supported for git. Just for helm.

What change you think needs making.
Allow the use of targetRevision ranges even for git.

# Motivation
I use skaffold to render my helm templates into plain k8s manifests and push them to a separate git repo which only contain configs. This is a proper gitops approach to separate code from configuration. The repo to which the manifests get pushed then deploy to dev and staging k8s clusters automatically from the main branch, but not to prod, until a git version tag that follows semver is created. I don't want devs to have to constantly update the applicationsets with a single tag everytime they are ready to upgrade their apps in prod. Hence allowing to specify targetRevision ranges for git is a valuable gitops approach which allows ArgoCD to pick up new versions between 0.0.0 and 9.0.0 for example.

Sample proposed applicationset for reference, if it helps.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka-snowflake-connector
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - target_cluster: gke-prod-i3er
        target_revision:  0.0.1 - 0.0.9
        env: prod
      - target_cluster: gke-prod-cm5i
        target_revision: 0.0.1 - 0.0.9
        env: prod
      - target_cluster: gke-prod-lnbf
        target_revision:  0.0.1 - 0.0.9
        env: prod
      - target_cluster: gke-stage-jeh6
        target_revision: main
        env: staging
  template:
    metadata:
      name: 'kafka-snowflake-connector-{{target_cluster}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: dataeng
      destination:
        name: '{{target_cluster}}'
        namespace: dataeng
      source:
        repoURL: ssh://git@gitlab.xxx.net/science/kafka-snowflake-connector-manifests.git
        targetRevision: "{{target_revision}}"
        path: '{{target_cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
```

# Proposal
I propose supporting git targetRevision ranges just like they are supported for helm

How do you think this should be implemented?
I'm just an end user so I leave the implementation details to you. But the same way as its supported for helm should just work.
