### ISSUE TITLE
no matches for kind "ConfigManagementPlugin" in ArgoCD 2.8.0

### ISSUE THREAD

**Issue by ledroide** [argoproj/argo-cd#15152]
Installation method : manifest from https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0/manifests/install.yaml 
Context : "Support dropped for argocd-cm plugins" - in [upgrade notes for ArgoCD 2.7 to 2.8](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.7-2.8/)
Doc/guide followed : [Migrating from argocd-cm plugins](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#migrating-from-argocd-cm-plugins)

I have converted this configMapGenerator file for configMap/argocd-cm : 
```yaml
- name: kustomized-helm
  init:
    command: ["/bin/sh", "-c"]
    args: ["helm dependency build"]
  generate:
    command: [sh, -c]
    args: ["helm template --release-name release-name . > all.yaml && kustomize build"]
```
... to this argoproj resource :  
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomized-helm
spec:
  init:
    command: ["/bin/sh", "-c"]
    args: ["helm dependency build"]
  generate:
    command: [sh, -c]
    args: ["helm template --release-name release-name . > all.yaml && kustomize build"]
``` 
But when applying manifests : 
```
error: resource mapping not found for name: "kustomized-helm" namespace: "argocd" from "./tools/argocd/env/poc": no matches for kind "ConfigManagementPlugin" in version "argoproj.io/v1alpha1"
ensure CRDs are installed first
```
So I have commented this resource in order to make sure that ArgoCD 2.8.0 is fully installed, including CRDs from the manifest. Then I retried. Same error.

When checking argoproj CRDs, there is no configmanagementplugin.argoproj.io resource :  
```bash
$ kubectl api-resources --api-group=argoproj.io
NAME              SHORTNAMES         APIVERSION             NAMESPACED   KIND
applications      app,apps           argoproj.io/v1alpha1   true         Application
applicationsets   appset,appsets     argoproj.io/v1alpha1   true         ApplicationSet
appprojects       appproj,appprojs   argoproj.io/v1alpha1   true         AppProject
```
It is because there is no configmanagementplugin.argoproj.io CRD in manifests/install.yaml - but only applications.argoproj.io, applicationsets.argoproj.io, and appprojects.argoproj.io : 
```bash
$ curl -s https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.0/manifests/install.yaml | grep -i customresourcedefinition -A5 
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: applications.argoproj.io
    app.kubernetes.io/part-of: argocd
  name: applications.argoproj.io
--
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: applicationsets.argoproj.io
    app.kubernetes.io/part-of: argocd
  name: applicationsets.argoproj.io
--
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: appprojects.argoproj.io
    app.kubernetes.io/part-of: argocd
  name: appprojects.argoproj.io
```
I did not find the configmanagementplugin.argoproj.io CRD in this repository - I have searched in both branches v2.8.0 and master.
Where is it ?

**Comment by crenshaw-dev** [comment]
ConfigManagementPlugin is not an actual CRD. It's a config file that's formatted to look like a CRD. You're meant to embed it in a ConfigMap and mount it into your plugin's sidecar. 

I want to remove the CRD-like fields from that file, because it is confusing: https://github.com/argoproj/argo-cd/pull/14440

**Comment by gajus** [comment]
^same question

**Comment by prein** [comment]
Do I read it right then that the [migration guide](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#migrating-from-argocd-cm-plugins) is misleading and the configManagementPlugins entries stay where they were?

**Comment by ledroide** [comment]
@prein : From what I understood from documentation, this : 
```yaml
data: 
  configManagementPlugins: |
    - name: kustomized-helm
      init:
[...]
```
...should be converted into this : 
```yaml
data: 
  configManagementPlugins: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomized-helm
    spec:
      init:
[...]
```
But I could not find a way to check this configuration is correct and taken in account by argocd application controller.
