### ISSUE TITLE
Error: topologySpreadConstraints .matchLabelKeys: field not declared in schema

### ISSUE THREAD

**Issue by mdfaizsiddiqui** [argoproj/argo-cd#15176]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am seeing this error in k8s 1.27 cluster when synching a deployment manifest with argocd -

```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: errors:
  .spec.template.spec.topologySpreadConstraints[topologyKey="kubernetes.io/hostname",whenUnsatisfiable="DoNotSchedule"].matchLabelKeys: field not declared in schema
  .spec.template.spec.topologySpreadConstraints[topologyKey="topology.kubernetes.io/zone",whenUnsatisfiable="DoNotSchedule"].matchLabelKeys: field not declared in schema
```

Example manifest -

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: warpstream
          matchLabelKeys:
          - pod-template-hash
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: warpstream
          matchLabelKeys:
            - pod-template-hash
```

**To Reproduce**

Try apply above resource via argocd

**Expected behavior**

No error, it should just sync without any schema error.

**Screenshots**

**Version**

```shell
v2.8.0+804d4b8
```

**Logs**

```
Paste any relevant application logs here.
```
