### ISSUE TITLE
Any namespace permission denied

### ISSUE THREAD

**Issue by SledgeHammer01** [argoproj/argo-cd#15216]
I am installing Argo with:

```
kubectl create namespace argocd
kubectl apply -k .

```

I have a kustomization.yml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
patches:
  - path: argocd-cmd-params-cm-patch.yml
namespace: argocd

```

argocd-cmd-params-cm-patch.yml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  application.namespaces: "*"

```

Project template created with kubectl apply -f localstack-project.yml -n argocd:

```
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: localstack
  namespace: argocd
spec:
  description: localstack
  sourceNamespaces:
  - localstack
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: localstack
    server: https://kubernetes.default.svc
  sourceRepos:
  - 'https://helm.localstack.cloud'
```

When I try to create the application in localstack/localstack, I get:

Unable to create application: error creating application: applications.argoproj.io is forbidden: User "system:serviceaccount:argocd:argocd-server" cannot create resource "applications" in API group "argoproj.io" in the namespace "localstack"

What am I missing here?
