### ISSUE TITLE
resource.exclusions for CiliumIdentity causes some weird argocd state

### ISSUE THREAD

**Issue by dusatvoj** [argoproj/argo-cd#15256]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I've created K8s cluster via RKE2 with Cilium as CNI. After creating I did a bootstrap of argocd with autopilot. Now I want to deploy monitoring so I decided to use standalone `kube-state-metrics` via [this helmchart](https://artifacthub.io/packages/helm/prometheus-community/kube-state-metrics).
After deploying I'm still seeing OutOfSync 
![image](https://github.com/argoproj/argo-cd/assets/11560794/f7a19e57-5cca-4b40-baed-a22b7e99b770)
After a while of searching I tried to apply [fix / workaround from Cilium docs](https://docs.cilium.io/en/latest/configuration/argocd-issues/).

There's a part of my `kustomization.yml`:
 ```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
configMapGenerator:
  - behavior: merge
    name: argocd-cm
    literals:
      # Cilium identity out-of-sync fix
      - |
        resource.exclusions=- apiGroups:
            - cilium.io
            kinds:
            - CiliumIdentity
            clusters:
            - "*"
```

When I apply this I'm stuck in weird state of argocd - everything unknown, etc.
![image](https://github.com/argoproj/argo-cd/assets/11560794/cc5a593e-1701-44d2-bf1f-5ea83a929e23)

**To Reproduce**

Apply fix from https://docs.cilium.io/en/latest/configuration/argocd-issues/

**Expected behavior**

Working argo with exclusion of `CiliumIdentity` kind

**Screenshots**

Added above

**Version**

```json
{
    "Version": "v2.8.2+dbdfc71",
    "BuildDate": "2023-08-24T20:05:39Z",
    "GitCommit": "dbdfc712702ce2f781910a795d2e5385a4f5a0f9",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
N/A?
```
