### ISSUE TITLE
Ability to generate Account token for SSO logged user

### ISSUE THREAD

**Issue by seb-835** [argoproj/argo-cd#15277]
# Summary
it is impossible to generate an account token for a SSO  authenticated user  using  argocd CLI or through the GUI.
 
```
$ argocd login argo.*** --sso --grpc-web
Opening browser for authentication
Performing authorization_code flow login: [....]
Authentication successful
'seb835@noname.com' logged in successfully
Context 'argo.***' updated

$ argocd account generate-token --grpc-web 
FATA[0000] rpc error: code = NotFound desc = account 'seb835@noname.com' does not exist
```

# Motivation
Be able to use token for SSO authenticated User like we can do with gitlab, harbor, .... in a way to automate tasks.

# Proposal
Add the ability thorugh GUI or through the argocd cli.

**Comment by fkaksa** [comment]
Any status about this?

**Comment by robp94** [comment]
Would need this too.

**Comment by zimmertr** [comment]
Without this, it is not possible to interact with the API through an SSO user. Do I have that right?

**Comment by dee-kryvenko** [comment]
This is not a solution to this problem as SSO-federated users still need to be able to issue tokens to themselves, but since it was not self-evident to me I thought to mention it here: even if SSO is enabled, you can still create normal accounts via a ConfigMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # This is a test account used for development
  accounts.test: apiKey
  accounts.test.enabled: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.test.csv: |
    p, test, applications, get, */*, allow
```

Now, `test` account does exists and you can issue tokens for it.

The problem with this approach is that the process of provisioning accounts like that is tightly coupled with ArgoCD deployment itself (i.e. you need to modify these config maps to issue new accounts). If you are practicing multi-tenant ArgoCD instances like me, this is not practical as you will want users to be able to get themselves service accounts with access to their respective projects, and with this approach it is not possible to self-service this process.

I was thinking about creating a controller which would watch projects and mutate configmaps to add service accounts per project, issue tokens to them and store the token as secret in the user namespace (in my setup, I have 1:1 relation for project<->namespace). Somehow it feels like this should be a native functionality.
