### ISSUE TITLE
ArgoCD notifications logs credentials in DEBUG loglevel

### ISSUE THREAD

**Issue by jnogol** [argoproj/argo-cd#15290]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When `debug` log level is set for ArgoCD notifications, all headers are logged in (and potentially parsed and sent to the log management tool of the choosing).

I was trying to find out why my webhook wasn't able to trigger a GitHub Workflow

```yaml
  service.webhook.github: |
    url: https://api.github.com
    headers:
    - name: Authorization
      value: Bearer $githubToken
    - name: Accept
      value: application/vnd.github+json
    - name: X-GitHub-Api-Version
      value: 2022-11-28
template.github-actions: |
    webhook:
      github:
        method: POST
        path: /repos/{{call .repo.FullNameByRepoURL .app.spec.source.repoURL}}/actions/workflows/<myWorkflowID>/dispatches
        body: |
          {
            "ref":"main",
            "inputs":{"message":"hello from argo notifications"}
          }
```

Set [ArgoCD notifications log level](https://github.com/argoproj/argo-helm/blob/argo-cd-5.35.0/charts/argo-cd/values.yaml#L2720) to `debug`

And to my surprise, along with the response code and all the information, I saw that along with all the needed information, the headers were logged in clear text, showing my GitHub token:

```json
Sending request: POST /repos/ovotech/kmi-gitops/actions/workflows/<MYWORKFLOWID>/dispatches HTTP/1.1
Host: api.github.com
Accept: application/vnd.github+json
Authorization: Bearer <REDACTED>
X-Github-Api-Version: 2022-11-28

{
  "ref":"main",
  "inputs":{"message":"hello from argo notifications"}
}
```

Same happened with a webhook that sends info to a Datadog API:

```yaml
service.webhook.datadog: |
    url: https://api.datadoghq.com
    headers:
      - name: DD-API-KEY
        value: $datadog-token
```

```json
Sending request: POST /api/v1/events HTTP/1.1
Host: api.datadoghq.com
Dd-Api-Key: <REDACTED>

{...}
```

Is there a way the headers can be masked like in [here](https://github.com/open-policy-agent/opa/pull/4496/files)?

**To Reproduce**

- Add this to `argocd-notifications-cm`

```yaml
  service.webhook.github: |
    url: https://api.github.com
    headers:
    - name: Authorization
      value: Bearer MY-SUPER-SECURE-TOKEN
    - name: Accept
      value: application/vnd.github+json
    - name: X-GitHub-Api-Version
      value: 2022-11-28
  template.github-actions: |
    webhook:
      github:
        method: POST
        path: /repos/{{call .repo.FullNameByRepoURL .app.spec.source.repoURL}}/actions/workflows/workflowID1234/dispatches
        body: |
          {
            "ref":"main",
            "inputs":{"message":"hello from argo notifications"}
          }
  trigger.github-actions: |
    - description: Application syncing has succeeded
      send:
      - github-actions
      when: app.status.operationState.phase in ['Running', 'Succeeded']
```

Set [ArgoCD notifications log level](https://github.com/argoproj/argo-helm/blob/argo-cd-5.35.0/charts/argo-cd/values.yaml#L2720) to `debug`

Then suscribe any argocd app to it by adding the annotation `notifications.argoproj.io/subscribe.github-actions.github: ""` to it.

Check the logs, grep for `MY-SUPER-SECURE-TOKEN`

**Expected behavior**

My auth related aren't logged or are masked.

**Version**

```shell
argocd: v2.6.7+5bcd846
  BuildDate: 2023-03-23T14:57:27Z
  GitCommit: 5bcd846fa16e4b19d8f477de7da50ec0aef320e5
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64

```

**Logs**

```
Paste any relevant application logs here.
```
