### ISSUE TITLE
support redis sharing between multiple argocd instances

### ISSUE THREAD

**Issue by gaurav517** [argoproj/argo-cd#15305]
As discussed in https://github.com/argoproj/argo-cd/discussions/15260:

I did a test and it looks like sharing same redis instance would create conflicts between argocd instances.
I had following `Certificate` definition in three isolated clusters sharing same redis instance.
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: istio
    name: cert-1
```
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: istio
    name: cert-2
```
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: istio
    name: cert-3
```
And in `argocd` UI, `istio` application was flickering between `cert-1`, `cert-2` and `cert-3`. So either sharing same redis is not supported or this is a bug.
