### ISSUE TITLE
App health stuck at "Progressing" forever when pod has `restartPolicy: Never`

### ISSUE THREAD

**Issue by lindhe** [argoproj/argo-cd#15317]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an Application deploys a pod that has `restartPolicy: Never`, the Application gets stuck with health "Progressing" seemingly forever.

**To Reproduce**

Apply this manifest:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: debug
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: manifests
    repoURL: https://github.com/lindhe/debug-argocd-15317.git
```

That app installs just this seemingly innocuous pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - image: busybox
      command: ['sh', '-c', 'sleep 3600']
      name: bar
  restartPolicy: Never
```

**Expected behavior**

The application health should soon become "Healthy".

**Screenshots**

<img width="1080" alt="Screenshot 2023-09-01 083537" src="https://github.com/argoproj/argo-cd/assets/7773090/24d80128-05a6-4b06-8498-ccefa687ca7a">

**Version**

```shell
argocd: v2.7.9+0ee33e5
  BuildDate: 2023-07-24T18:26:12Z
  GitCommit: 0ee33e52dd1f1bb944488584fc6f854b929f1180
  GitTreeState: clean
  GoVersion: go1.19.11
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.8.0+804d4b8
```

**Logs**

No relevant logs that I've found.

**Other information**

Similar to #5620 and some other issues found by searching for "health progressing".

I'm running an RKE2 cluster with version `v1.26.6+rke2r1` and Cilium `1.13.2` installed.
