### ISSUE TITLE
Controller should retry kubectl apply during syncing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1532]
**Describe the bug**
The kubectl apply might fail due to intermittent errors. Especially if it is trying to apply changes to CRD backed by third party api server. Right now application sync fails even if single `kubectl apply` fails. It was observed that application which includes multiple `calico/GlobalNetworkPolicy` resources never synced successfully because at least one resource fails during syncing.

As a solution, we can introduce retries during syncing. This is not a common issue and it is difficult to differentiate the retriable error from non-retriable. So by default reties should be disabled and can be enabled per-application using `spec.syncPolicy.retryCount` field. E.g.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  syncPolicy:
    retryCount: 3
```
