### ISSUE TITLE
Can't create project token for policies using applications in namespaces

### ISSUE THREAD

**Issue by iandelahorne** [argoproj/argo-cd#15333]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

This is related to [Applications in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/). 
When creating a project that leverages `spec.sourceNamespaces`, an operator might want to create an API token that is scoped to a single namespace inside the project, or even further to a specific application prefix inside a project. 

For example, in this project definition, we are allowing applications to be created in `my-namespace` and `my-other-namespace`. We want to create a role, `my-role` that can only create applications in the namespace `my-namespace` that start with `app-prefix`:

```yaml

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  sourceNamespaces:
    - my-namespace
    - my-other-namespace
  roles:
    - name: my-role
      policies:
        - p, proj:my-project:my-role, applications, create, my-project/my-namespace/app-prefix-*, allow
```

When attempting to create a token with `argocd proj role create-token my-project my-role`, this will fail with:
```
FATA[0000] rpc error: code = InvalidArgument desc = invalid policy rule 'p, proj:my-project:my-role, applications, create, my-project/my-namespace/app-prefix-*, allow': object must be of form 'my-project/*' or 'my-project/<APPNAME>', not 'my-project/my-namespace/app-prefix-*' 
```

This can be worked around by removing the policy definition, creating the token, and adding the policy back to the project again.

**To Reproduce**
1. Apply manifest above.
2. Run  `argocd proj role create-token my-project my-role`

**Expected behavior**

The expectation is that the token can be created.

**Version**

```shell
$ argocd version
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.12.3+g3a31588
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```
