### ISSUE TITLE
Pulling helm charts from GCP Artifact Registry fails after upgrading Argo to v2.8.2

### ISSUE THREAD

**Issue by Hoferl** [argoproj/argo-cd#15344]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I am using Google Artifact Registry to store helm charts as OCI images and use them as dependencies in other helm charts. After upgrading ArgoCD to v2.8.2 from v2.7.4 the generation of the manifest started failing. It worked before with version 2.7.4.

The UI displays this error message:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download oci://europe-west1-docker.pkg.dev/.....: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://europe-west1-docker.pkg.dev/v2/token?scope=repository%3.....%3Apull&service=europe-west1-docker.pkg.dev: 403 Forbidden
```

**To Reproduce**

I have this K8s secret for the OCI repository. This solution was recommended in various issues regarding Artifact Registry and OCI. It also follow GCP´s [docs](https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key) on how to authenticate with AR.

```yaml
apiVersion: v1
data:
  enableOCI: <"true" | base64>
  name: <"my-repository-ar" | base64>
  password: <service account key file in JSON format and base64 encoded>
  type: <"helm" | base64 >
  url: <"europe-west1-docker.pkg.dev/my-project-id/my-repository" | base64>
  username: <"_json_key" | base64>
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: my-repository-ar
  namespace: argocd
type: Opaque
```

I also added the url as source for my ArgoCD Project.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - 'git@github.com:test/my-repo.git'
    - 'europe-west1-docker.pkg.dev/my-project-id/my-repository'
  destinations:
    - namespace: default
      name: in-cluster
```

And i use the helm chart as a dependency.

```yaml
dependencies:
  - name: test-application
    version: 0.4.0
    repository: oci://europe-west1-docker.pkg.dev/my-project-id/my-repository/my-charts
    alias: my-test-application
```

**Expected behavior**

ArgoCD authenticates with Artifact Registry, pulls the image and generates the manifest.

**Version**

I am using this manifest to deploy ArgoCD
`https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.2/manifests/ha/install.yaml
`

**Comment by lhaussknecht** [comment]
Seems related or same as #11717

**Comment by AndreasWeichselbaum** [comment]
Hi, I'm a colleague of @Hoferl and we managed to fix tihs issue, although it seems to have nothing to do with authorisation per se:

The names of our Helm Charts in Artifact Registry look something like this: `europe-west1-docker.pkg.dev/my-project-id/my-repository/my-charts/chart-name`.
The `europe-west1-docker.pkg.dev/my-project-id/my-repository` part being the Artifact Registry repository and the `/my-charts/chart-name` being the Chart name.

Before upgrade to version `2.8.x`, the `Repository` definition looked like this:
```yaml
apiVersion: v1
data:
  ...
  url: <"europe-west1-docker.pkg.dev/my-project-id/my-repository" | base64>
  ...
kind: Secret
...
```

while the dependency helm charts looked like this:
```yaml
dependencies:
  - name: test-application
    version: 0.4.0
    repository: oci://europe-west1-docker.pkg.dev/my-project-id/my-repository/my-charts
    alias: my-test-application
```

We fixed the error by adding the `/my-charts` part to the `Repository` definition like this:
```yaml
apiVersion: v1
data:
  ...
  url: <"europe-west1-docker.pkg.dev/my-project-id/my-repository/my-charts" | base64>
  ...
kind: Secret
...
```

Hope this helps anyone experiencing the same issue
