### ISSUE TITLE
Badges not working with "Applications in any namespace"

### ISSUE THREAD

**Issue by villisco** [argoproj/argo-cd#15351]
**Describe the bug**

When ArgoCD "Application" resource is deployed under namespace other than "argocd" the badge url is not working.
Shows "Not found" or "Unknown".

Badges currently seem to only work when Application resources are deployed to argocd namespace (default way).

**To Reproduce**

Deploy application to namespace other than argocd.

Example: __testnamespace/app1__
```
kind: Application
metadata:
    name: app1
    namespace: testnamespace
```

Generated badge url under the application "app1" (UI):
```
https://<argocd_base_url>/api/badge?name=app1&revision=true <!--- "Badge: Not Found"
```

Try to check status with badge url:
```
<argocd_base_url>/api/badge?name=app1&revision=true <!--- "Badge: Not Found"
<argocd_base_url>/api/badge?name=testnamespace_app1&revision=true <!--- "Badge: Not Found"
```

**Version**
v2.8.2

**Comment by sushank3** [comment]
The feature is disabled by default because badge image is available to any user without authentication. The feature can be enabled using statusbadge.enabled key of argocd-cm ConfigMap.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  // Enables application status badge feature
  statusbadge.enabled: "true"
  
```
