### ISSUE TITLE
Failed to deploy helm app with value file with vault CMP 

### ISSUE THREAD

**Issue by harshchauhan1988** [argoproj/argo-cd#15355]
Checklist:

* [ v] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ v] I've included steps to reproduce the bug.
* [ v ] I've pasted the output of `argocd version`.

**Describe the bug**

Unable to Deploy App and getting below Error:
`Unable to create application: application spec for sumologic is invalid: InvalidSpecError: Unable to generate manifests in sumologic: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -c "helm template \"$ARGOCD_APP_NAME\" -n \"$ARGOCD_APP_NAMESPACE\" ${ARGOCD_ENV_HELM_ARGS} . --include-crds | argocd-vault-plugin generate -"` failed exit status 1: Error: No manifests `

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sumologic
spec:
  destination:
    name: ''
    namespace: sumologic-test-harsh
    server: 'https://1.1.1.1:6443'
  source:
    path: sumologic
    repoURL: 'https://github.com/harshchauhan1988/argo-cd.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm-with-args
      env:
        - name: HELM_ARGS
          value: '-f sumologic-sjc2-eng.yaml -n sumologic-test-harsh'
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true

```

**Expected behavior**

It should be able to deploy helm app with vault plug-in

**Version**

```shell
v2.8.2+dbdfc71
```
