### ISSUE TITLE
ArgoCD connect to Google Cloud Source Repo from GKE Using WorkloadIdentity credentials

### ISSUE THREAD

**Issue by Vavinash-github** [argoproj/argo-cd#15361]
Currently ArgoCD supports connecting to Google Cloud Source Repo only using Google Service Account (GSA) Private key Json file 
mentioned in -->  https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#google-cloud-source

Storing the GSA in kubernetes cluster is not secure and is not approved in many organizations.

Since WorkloadIdentity can be used in GKE clusters Argocd Deployments should be able to use the KSA (Kubernetes Service account) and run as GSA user using WorkloadIdentity and connect to Google Cloud Source Repo. 

Using WorkloadIdentity improves the security because there are no private key files stored in GKE cluster and the credentials are short lived and will be auto rotated.

I would like to know when this feature can be made available or any alternate approaches using WorkloadIdentity to connect to Google Cloud Source Repo.

Thanks..

**Comment by torfjor** [comment]
This is already supported, using [External Account Credentials](https://google.aip.dev/auth/4117) (albeit not very well documented).

Patch your `argocd-repo-server` to mount the KSA token with the cluster pool as audience:
```yaml
  - patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: gcp-ksa
          projected:
            defaultMode: 420
            sources:
            - serviceAccountToken:
                path: token
                audience: YOUR_PROJECT_ID.svc.id.goog
                expirationSeconds: 172800
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: gcp-ksa
          mountPath: /var/run/secrets/tokens/gcp-ksa
          readOnly: true
    target:
      kind: Deployment
      name: argocd-repo-server
```

Use the following JSON contents for the service account key:
```json
{
  "type": "external_account",
  "audience": "identitynamespace:YOUR_PROJECT_ID.svc.id.goog:https://container.googleapis.com/v1/projects/PROJECT_ID/locations/CLUSTER_REGION/clusters/CLUSTER_NAME",
  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/TARGET_SERVICE_ACCOUNT_NAME@YOUR_PROJECT_ID.iam.gserviceaccount.com:generateAccessToken",
  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
  "token_url": "https://sts.googleapis.com/v1/token",
  "credential_source": {
    "file": "/var/run/secrets/tokens/gcp-ksa/token"
  }
}
```

`TARGET_SERVICE_ACCOUNT_NAME` will need to have the required IAM bindings to the `roles/iam.workloadIdentityUser` role with `serviceAccount:YOUR_PROJECT_ID.svc.id.goog[argocd/argocd-repo-server]` as member.
