### ISSUE TITLE
StatefulSet with initContainers gives syntax error in 0.12.1 and up

### ISSUE THREAD

**Issue by oskar** [argoproj/argo-cd#1540]
**Describe the bug**
In 0.12.0 the following configuration works fine. However, since 0.12.1 and up (tested in 0.12.1, 0.12.3 and 1.0.0-rc1) it fails with "index out of range" error during config validation.

When commenting out the initContainers block it works again.

The configuration is a vanilla example taken from [Kubernetes docs](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components)

**To Reproduce**

1. Apply this config:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: say-hello
        image: busybox
        command: ["echo", "hello"]
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```

2. Get validation error in Argo (`rpc error: code = Internal desc = runtime error: index out of range`)

**Expected behavior**
No validation error since the configuration is valid for Kubernetes.
