### ISSUE TITLE
[ApplicationSet] Gitlab scm_provider ignores proxy settings

### ISSUE THREAD

**Issue by an-toine** [argoproj/argo-cd#15424]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Since ArgoCD `2.8.0`, the Gitlab `scm_provider` seems to ignore proxy settings of pod `argocd-applicationset-controller`.

When deployed to an environment where a proxy is mandatory to connect to the remote Gitlab server, the provider will fail to list group repositories.

**To Reproduce**

We use the following `ApplicationSet` object : 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: XXXXXX
  name: XXXX-applicationset
  namespace: openshift-gitops
spec:
  generators:
  - matrix:
      generators:
      - git:
          files:
          - path: XXXXX/gitops/config.yaml
          repoURL: https://XXXXXXXX-setup.git
          revision: master
      - scmProvider:
          cloneProtocol: https
          gitlab:
            allBranches: false
            api: https://gitlab.XXXXX.com
            group: XXXXX/helm/charts
            includeSubgroups: false
            tokenRef:
              key: token
              secretName: XXXXXXXX
  goTemplate: true
  template:
    metadata:
      labels:
        app: '{{ .repository }}'
      name: '{{ .cluster.name }}-{{ .repository }}'
    spec:
      destination:
        name: '{{ .cluster.name }}'
      project: default
      sources:
      - helm:
          valueFiles:
          - $values/XXXXX/XX.yaml
          values: '{{ .values }}'
        path: .
        repoURL: '{{ .url }}'
        targetRevision: develop
      - ref: values
        repoURL: https://gitlab.XXXXXXX.com/XXXXX/XXXXXX.git
        targetRevision: master
```

**Expected behavior**

We expect the Gitlab `scm_provider` to work in environments mandating proxy use, as it used to in earlier versions

**Version**

```shell
./argocd-linux-amd64 version --server argocd-XXXXX.net:443 --grpc-web
argocd: v2.8.0+804d4b8
  BuildDate: 2023-08-07T19:41:16Z
  GitCommit: 804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.0+804d4b8
```

**Logs**

Error logs found in pod `argocd-applicationset-controller` :

```
time="2023-09-08T12:23:26Z" level=error msg="error generating application from params" error="failed to get params for second generator in the matrix generator: child generator returned an error on parameter generation: error listing repos: error listing projects for paas/helm/charts: Get \"https://gitlab.XXXXXX.com/api/v4/groups/XXXXX%2Fhelm%2Fcharts/projects?include_subgroups=false&per_page=100\": dial tcp XXXXX:443: connect: connection timed out" generator="{nil nil nil nil nil nil &MatrixGenerator{Generators:[]ApplicationSetNestedGenerator{ApplicationSetNestedGenerator{List:nil,Clusters:nil,Git:&GitGenerator{RepoURL:https://gitlab.XXXXXX.com/XXXXX/XXXXXXXX.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:XXXXXXXX/gitops/config.yaml,},},Revision:master,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},},SCMProvider:nil,ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},ApplicationSetNestedGenerator{List:nil,Clusters:nil,Git:nil,SCMProvider:&SCMProviderGenerator{Github:nil,Gitlab:&SCMProviderGeneratorGitlab{Group:XXXXX/helm/charts,IncludeSubgroups:false,API:https://gitlab.XXXXXX.com,TokenRef:&SecretRef{SecretName:aXXXXXXX,Key:token,},AllBranches:false,Insecure:false,},Bitbucket:nil,BitbucketServer:nil,Gitea:nil,AzureDevOps:nil,Filters:[]SCMProviderGeneratorFilter{SCMProviderGeneratorFilter{RepositoryMatch:nil,PathsExist:[],PathsDoNotExist:[],LabelMatch:nil,BranchMatch:nil,},},CloneProtocol:https,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},Values:map[string]string{},AWSCodeCommit:nil,},ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},} nil nil nil}"
time="2023-09-08T12:25:49Z" level=error msg="error generating params" error="error listing repos: error listing projects for XXXXX/helm/charts: Get \"https://gitlab.XXXXXX.com/api/v4/groups/XXXXX%2Fhelm%2Fcharts/projects?include_subgroups=false&per_page=100\": dial tcp XXXXX:443: connect: connection timed out" generator="&{0xc000fd92c0 <nil> {0xc0012791f0}  []}"
time="2023-09-08T12:25:49Z" level=error msg="error generating params" error="failed to get params for second generator in the matrix generator: child generator returned an error on parameter generation: error listing repos: error listing projects for XXXXX/helm/charts: Get \"https://gitlab.XXXXXX.com/api/v4/groups/XXXXX%2Fhelm%2Fcharts/projects?include_subgroups=false&per_page=100\": dial tcp XXXXX:443: connect: connection timed out" generator="&{map[ClusterDecisionResource:0xc000fd9770 Clusters:0xc000fd9720 Git:0xc001279200 List:0x6db6b88 Matrix:0xc000597ff0 Merge:0xc000597ff8 Plugin:0xc001281280 PullRequest:0xc000fd97c0 SCMProvider:0xc000ff9140]}"
time="2023-09-08T12:25:49Z" level=error msg="error generating application from params" error="failed to get params for second generator in the matrix generator: child generator returned an error on parameter generation: error listing repos: error listing projects for XXXXX/helm/charts: Get \"https://gitlab.XXXXXX.com/api/v4/groups/XXXXX%2Fhelm%2Fcharts/projects?include_subgroups=false&per_page=100\": dial tcp XXXXX:443: connect: connection timed out" generator="{nil nil nil nil nil nil &MatrixGenerator{Generators:[]ApplicationSetNestedGenerator{ApplicationSetNestedGenerator{List:nil,Clusters:nil,Git:&GitGenerator{RepoURL:https://gitlab.XXXXXX.com/XXXXX/XXXXXXXX.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:XXXXXXXX/gitops/config.yaml,},},Revision:master,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},},SCMProvider:nil,ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},ApplicationSetNestedGenerator{List:nil,Clusters:nil,Git:nil,SCMProvider:&SCMProviderGenerator{Github:nil,Gitlab:&SCMProviderGeneratorGitlab{Group:XXXXX/helm/charts,IncludeSubgroups:false,API:https://gitlab.XXXXXX.com,TokenRef:&SecretRef{SecretName:aXXXXXXX,Key:token,},AllBranches:false,Insecure:false,},Bitbucket:nil,BitbucketServer:nil,Gitea:nil,AzureDevOps:nil,Filters:[]SCMProviderGeneratorFilter{SCMProviderGeneratorFilter{RepositoryMatch:nil,PathsExist:[],PathsDoNotExist:[],LabelMatch:nil,BranchMatch:nil,},},CloneProtocol:https,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},Values:map[string]string{},AWSCodeCommit:nil,},ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},} nil nil nil}"
```

I managed to reproduce the issue in a go test program, and I believe this bug is caused by the creation from scratch of an `http.Transport`, causing all proxy settings to be lost : https://github.com/argoproj/argo-cd/blob/v2.8.0/applicationset/services/scm_provider/gitlab.go#L31

Regards,
Antoine
