### ISSUE TITLE
Failed to query provider "https://argocd-url/api/dex": 502 Bad Gateway

### ISSUE THREAD

**Issue by farouqy** [argoproj/argo-cd#15485]
Checklist:

* [v] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [v] I've included steps to reproduce the bug.
* [v] I've pasted the output of `argocd version`.

**Describe the bug**
I'm using **argo-cd-5.46.0** helm chart
SSO not working using dex.

![image](https://github.com/argoproj/argo-helm/assets/57801581/5a9f12ad-7aa5-4c6d-adf0-ea597be356f4)

But logs from dex server shows that the authentication was successful :

`{"level":"info","msg":"login successful: connector \"saml\", username=\"my_email\", preferred_username=\"\", email=\"my_email\"..............}`

**To Reproduce**

```
configs:
    url: https://my-argo-cd-url
   dex.config: |
       logger:
         level: debug
         format: json
       connectors:
       - type: saml
         id: saml
         name: saml
         config:
           entityIssuer: https://my-argo-cd-url/api/dex/callback
           ssoURL: https://my-login-url (e.g. https://login.microsoftonline.com/xxxxx/a/saml2)
           caData: |
              MY-BASE64-ENCODED-CERTIFICATE-DATA
           redirectURI: https://my-argo-cd-url/api/dex/callback
           usernameAttr: email
           emailAttr: email
           groupsAttr: Group
```

RBAC : 
```
policy.default: role:readonly
policy.csv: |
   p, role:org-admin, applications, *, */*, allow
   p, role:org-admin, clusters, get, *, allow
   p, role:org-admin, repositories, get, *, allow
   p, role:org-admin, repositories, create, *, allow
   p, role:org-admin, repositories, update, *, allow
   p, role:org-admin, repositories, delete, *, allow
   g, "84ce98d1-e359-4f3b-85af-985b458de3c6", role:org-admin # (azure group assigned to role)
```

Ingress setup : 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
    host: argocd.example.com
  tls:
  - hosts:
    - argocd.example.com
    secretName: argocd-ingress-http
```

**Expected behavior**

Login to argocd dashboard using sso

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/57801581/332f176c-b498-4d28-b117-27da7d58b821)

**Version**

```shell
v2.8.3
```

**Logs**
`{"level":"info","msg":"login successful: connector \"saml\", username=\"my_email\", preferred_username=\"\", email=\"my_email\"..............}`
```
Paste any relevant application logs here.
```
