### ISSUE TITLE
Argo Application defining multiple sources for Helm Chart and Values will ignore path attribute for Values sources

### ISSUE THREAD

**Issue by rodoherty-ppb** [argoproj/argo-cd#15528]
Asked in #argo-cd Slack channel and agreed to post a bug for further review.

Checklist:
* [Yes] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [Yes] I've included steps to reproduce the bug.
* [Yes] I've pasted the output of `argocd version`.

**Describe the bug**

My Argo application is defined as follows:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application-staging
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.promote: ""
  labels:
    env: 'staging'
    nextenv: 'prd'
    name: my-application
spec:
  project: my-project
  sources:
    - repoURL: https://raw.githubusercontent.com/my-private-org/my-private-repo/some-branch
      chart: my-chart
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $environments/values.yaml
          - $variants/values.yaml
    - repoURL: https://github.com/my-private-org/my-private-repo
      targetRevision: some-branch
      path: environments/staging/values
      ref: environments
    - repoURL: https://github.com/my-private-org/my-private-repo
      targetRevision: some-branch
      path: variants/staging/values
      ref: variants
  destination:
    name: staging
    namespace: my-appliction-staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
```

ArgoCD (v2.8.4) cannot find the corresponding `values.yaml` file.  It is as if ArgoCD is ignoring the `path` attributes in the 2nd and 3rd sources reference.

The [ArgoCD Docs](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository) state the following:
> If the `path` field is set in the `$values` source, Argo CD will attempt to generate resources from the git repository at that URL. If the `path` field is not set, Argo CD will use the repository solely as a source of value files.

This suggests that I should be able to provide a `path` attribute for my `values.yaml` files.

Have I encountered a bug?

**To Reproduce**
The above Argo Application definition should be enough for you to reproduce this issue.
The inclusion of the `path` attribute in Helm Values sources will be ignored and this is the bug.

**Expected behavior**
I expect that ArgoCD is able to locate the Helm chart and the two `values.yaml` files and attempt to deploy the application to a Kubernetes cluster.

**Screenshots**
The attached stacktrace is the error that the ArgoUI displays when the Application fails to synchronise.
[stacktrace.txt](https://github.com/argoproj/argo-cd/files/12621731/stacktrace.txt)
<img width="1687" alt="Screenshot 2023-09-15 at 17 21 25" src="https://github.com/argoproj/argo-cd/assets/62054139/b97123aa-8636-4356-bd35-0c679fa1aa36">

**Version**
```json
{
    "Version": "v2.8.4+c279299",
    "BuildDate": "2023-09-13T19:12:09Z",
    "GitCommit": "c27929928104dc37b937764baf65f38b78930e59",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

[argo-repo-server.log](https://github.com/argoproj/argo-cd/files/12621721/argo-repo-server.log)

**Comment by ishitasequeira** [comment]
@rodoherty-ppb , The `ref` variable points to the root of the repository and not to the path within the repository specified.

If the `path` is specified for a source along with `ref` field, then ArgoCD will generate manifests for the source while also using the source as a referenced source. 

So, to use the value files from the referenced source, you need to mention the path of the values file like below:

```
spec:
  project: my-project
  sources:
    - repoURL: https://raw.githubusercontent.com/my-private-org/my-private-repo/some-branch
      chart: my-chart
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $environments/staging/values/values.yaml                           <--------- see the change in path
          - $variants/staging/values/values.yaml                               <--------- see the change in path
    - repoURL: https://github.com/my-private-org/my-private-repo
      targetRevision: some-branch
      path: environments/staging/values
      ref: environments
    - repoURL: https://github.com/my-private-org/my-private-repo
      targetRevision: some-branch
      path: variants/staging/values
      ref: variants
```

**Comment by rodoherty-ppb** [comment]
@ishitasequeira Hi Ishita - thank you for the pointer.  Your suggestion does indeed work.  I still have an outstanding question which I will raise in the CNCF Argo-cd Slack channel.
Happy to close this bug!  Thanks again!

**Comment by AndreCbrera** [comment]
@ishitasequeira when I try to pass a harbor chart repository I got this error:


``Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = helm pull --destination /tmp/eb66c1b7-9ae2-4112-997f-3bd2021c5673 --version 0.1.0 --repo https://harbor.contv2-k8s.mapa.es/devops/nginx-mapa nginx-mapa --ca-file /app/config/tls/harbor.contv2-k8s.mapa.es failed exit status 1: Error: looks like  https://harbor.contv2-k8s.mapa.es/devops/nginx-mapa  is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile``

this is my application yaml  file

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webbackend-app
  namespace: argocd
spec:
  project: default
  sources:
  - chart: 'nginx-nama'
    repoURL: "https://harbor.contv2-k8s.mapa.es/devops/chart"
    targetRevision: '0.1.0'
    helm:
      valueFiles:
      - $values/chartsvalues/dev/values.yaml
  - repoURL: 'https://repo.git/application-controller-chart.git'
    targetRevision: "feat/test-app"
    path: chartsvalues/desa/
    ref: values
  destination:
    namespace: nginx-a
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
```
