### ISSUE TITLE
Add section about traefik v3 to ingress docs

### ISSUE THREAD

**Issue by mxcd** [argoproj/argo-cd#15534]
# Summary

The documentation concerning the `IngressRouteCRD` configuration (https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ingressroute-crd) will be invalid when using traefik version 3

# Motivation

With the upcoming traefik v3 release, there is a breaking change to the `IngressRouteCRD` matchers (see https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/#matchers) causing the following to be an invalid configuration:

```yaml
# ...
- kind: Rule
      match: Host(`argocd.example.com`) && Headers(`Content-Type`, `application/grpc`)
# ...
```

The new configuration using `apiVersion: traefik.io/v1alpha1` requires to replace `Headers` with `Header`

# Proposal

Add a dedicated section concerning traefik v3 to the docs, warning the reader about the breaking changes introduced with traefik v3
