### ISSUE TITLE
Argo CD not picking values.yaml from multiple sources

### ISSUE THREAD

**Issue by areebemumba** [argoproj/argo-cd#15542]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to deploy bitnami/redis helm chart via argo CD. The values.yaml file is in my personal repository. I am following this [documentation]( https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#:~:text=a%20Git%20repo.-,Helm%20value%20files%20from%20external%20Git%20repository,%C2%B6,-Helm%20sources%20can):

**To Reproduce**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-test
  namespace: argocd
spec:
  destination:
    namespace: redis-test
    server: https://kubernetes.default.svc/
  project: default
  sources:
    - chart: redis
      helm:
        valueFiles:
          - $values/deployments/redis/values.yaml
      repoURL: https://raw.githubusercontent.com/bitnami/charts/index/bitnami
      targetRevision: 18.0.4
    - ref: values
      repoURL: https://github.com/orgnization-name/repo-name.git
      targetRevision: branch-name
 ```

**Expected behavior**

I need my values.yaml files to be picked from my personal repo and not the default values coming from the official repository.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
2.7.8
**Logs**

```
Paste any relevant application logs here.
```
