### ISSUE TITLE
Alias: not working in repository reference in Chart.yaml

### ISSUE THREAD

**Issue by ffppmm** [argoproj/argo-cd#15563]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

https://helm.sh/docs/chart_best_practices/dependencies/#repository-urls

> If the repository has been added to the repository index file, the repository name can be used as an alias of URL. Use **alias: or @** followed by repository names.

But in ArgoCD Code only @ ist considered, see the if.
https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L1020

**To Reproduce**

Create a Chart.yaml with dependency repository: "alias:my-repo"
```yaml
apiVersion: v2
name: my-app
version: 0.1
description: my-app
dependencies:
- name: some-dep
  version: 0.2.17
  repository: 'alias:my-repo'
```
**Expected behavior**

Repository works with helm dependency build

**Version**
v2.8.4
v2.7.14
**Logs**
```
Unable to save changes: application spec for my-app is invalid: InvalidSpecError: Unable to generate manifests in my-app: rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: could not find protocol handler for: alias
```

As mentioned here:
https://github.com/argoproj/argo-cd/issues/7436#issuecomment-1681884991

Looking forward to a fix,
Regards Philipp
