### ISSUE TITLE
400 (Bad Request) - http: named cookie not present and data length is less than nonce size - ArgoCD

### ISSUE THREAD

**Issue by rakesh-vishwabrahmana** [argoproj/argo-cd#15565]
Unable to login to ArgoCD UI which is embedded inside my python flask application. I have changed the configuration of argocd ConfigMap,

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  server.x.frame.options: allow-from "https://my-app.com/"
  server.content.security.policy: frame-ancestors *
```

So that, I'm able to access the page but unable sign in using admin credentials or using SSO with Microsoft.

But generally I'm able to sign in to the argocd UI using SSO and admin credentials from https://argocd.my-app.com/ without any issues. But I'm unable to sign in from my application which is embedded.

Error message: `400 (Bad Request), http: named cookie not present` and `data length is less than nonce size`

Any advise?

Thanks
