### ISSUE TITLE
ArgoCD AVP not working as expected

### ISSUE THREAD

**Issue by MarcoPereira7** [argoproj/argo-cd#15570]
Hey guys, i am having some problems while using ArgoCD vault plugin.
I have followed the instalation documentation provided [here](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/#initcontainer-and-configuration-via-sidecar). I managed to install the plugin and to use it to fetch a secret from Vault and create it on k8s as a secret, but i found a major problem when using the plugin. Every time i launch it as a sidecar container to argocd-repo-server, and if i do a hard refresh on some applications, they get out-of-sync and with the status missing. All those application are referencing a git repo with manifests.
Everytime i remove the sidecar and consequently the plugin this issue disapears and if i do a hard-refresh again, every application goes to normal (synced).
Why could be happening? I have tried to increase the log level, from both avp sidecar container and repo-server but they dont show me anything usefull.

**Describe the bug**

Installing argocd vault plugin makes applications out-of-sync and missing. This should not happen since the repo is untouched.

**To Reproduce**

Since iam using **kustomize** to deploy all my k8s objets i configured the ConfigMap cmp-plugin with the following:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -s argocd-vault-approle -"
```

Also i have added the following sidecar container:

```
      - name: avp-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        args:
          - --loglevel=debug
        image: XXXXXXX
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-kustomize.yaml
            name: cmp-plugin
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
```

and the init container that downloads the plugin binary:

```
      - name: download-tools
        image: XXXXXXX
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
```

**Expected behavior**

If an untouched application is synced, the instalation of argocd plugin should not change the state to out-of-sync (missing), since all the files are in git and were not changed.

**Version**

```shell
argocd: v2.6.8+674cf8d
  BuildDate: 2023-05-25T15:55:50Z
  GitCommit: 674cf8d6e2a8f06683fcc6d8ec0f880ec9c2779c
  GitTreeState: clean
  GoVersion: go1.19.7
  Compiler: gc
  Platform: linux/amd64
```
