### ISSUE TITLE
Clusters cannot be added in namespaces other than argocd

### ISSUE THREAD

**Issue by liam-j-bennett** [argoproj/argo-cd#15601]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We currently have ArgoCD setup in cluster-wide mode and teams use their own namespace to both deploy onto the ‘in-cluster’ cluster and their own clusters. I’m trying to enable teams to create their own cluster resources through a declarative setup through project scoped clusters. The secrets themselves are synced into the namespaces of each team, but it seems that cluster objects are not synced into ArgoCD server itself (through `argocd.argoproj.io/secret-type: cluster`) unless they are in the ArgoCD namespace. I can’t see a config option for this in particular, but looking at the code it seems the secret watcher is only looking at 1 namespace. The only way around this is to allow teams access to the `argocd` namespace, which is something we would like to avoid.

Not sure if a bug, misconfig, or by design, but I couldn't find any reference to this limitation in the docs. In particular, [this doc](https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-scoped-repositories-and-clusters) would seem to indicate the sort of self-service cluster creation that is for the cluster-wide setup. If it is by design, I'm happy to look at contributing this feature (if a valid use-case here)

**To Reproduce**

Apply the following in an ArgoCD in cluster-wide mode:

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: argocd-in-cluster
  server: https://kubernetes.default.svc?namespace=argocd
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: foo-in-cluster
  namespace: foo-ns
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: foo-in-cluster
  server: https://kubernetes.default.svc?namespace=foo-ns
```

Only the cluster in the ArgoCD namespace is added to the cluster list:

<img width="1118" alt="Screenshot 2023-09-20 at 16 09 17" src="https://github.com/argoproj/argo-cd/assets/36160948/2f3bb317-5b12-4fbe-8811-398ddf5e1ff4">

**Expected behavior**

I expect both clusters to be added to the ArgoCD server.

**Version**

```shell
argocd version
argocd: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T22:18:46Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.20.5
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T22:18:46Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.20.5
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
