### ISSUE TITLE
Application refresh is triggered by untracked resources

### ISSUE THREAD

**Issue by duizabojul** [argoproj/argo-cd#15612]
**Describe the bug**

For a while, Argo CD feels slow to reconcile (refreshing syncing) and i activated debug logs. I noticed a lot of application refresh where caused by untracked resources. We run argocd with tracking with annotation, so we expect all app controller refresh should be triggered only by changes in resources with `argocd.argoproj.io/tracking-id` annotation, and not by every resources watched by the controller.

**Version**

```shell
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:05:39Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

One example among others

```
time="2023-09-21T08:39:37Z" level=debug msg="Requesting app refresh caused by object update"
api-version=kubernetes.crossplane.io/v1alpha1 application=argocd/admin-infra-it-central cluster-name=it-admin 
fields.level=0 kind=Object name=central-postgres-engine-configuration 
namespace="(cluster-scoped)" server="https://kubernetes.default.svc"
```

This update is caused by untracked child resource owned by tracked resource

```
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: postgres-engine-configuration
    crossplane.io/external-create-pending: '2023-07-22T17:30:40Z'
    crossplane.io/external-create-succeeded: '2023-07-22T17:30:40Z'
    crossplane.io/external-name: central-postgres-engine-configuration
    crossplane.io/paused: 'false'
  name: central-postgres-engine-configuration
  ownerReferences:
    - apiVersion: storage.crossplane.airnity.net/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: XDatabaseEngine
      name: central
      uid: 1c6697d2-6212-4d26-997f-47ea02aacba0
```

```
apiVersion: storage.crossplane.airnity.net/v1alpha1
kind: XDatabaseEngine
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/tracking-id: >-
      admin-infra-it-central:storage.crossplane.airnity.net/XDatabaseEngine:crossplane-infra-it-central/central
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"storage.crossplane.airnity.net/v1alpha1","kind":"XDatabaseEngine","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true","argocd.argoproj.io/tracking-id":"admin-infra-it-central:storage.crossplane.airnity.net/XDatabaseEngine:crossplane-infra-it-central/central","xfn.crossplane.airnity.net/backup":"true"},"name":"central"},"spec":{"compositionRevisionSelector":{"matchLabels":{"channel":"stable"}},"compositionSelector":{"matchLabels":{"engine":"postgres","provider":"aws"}},"params":{"clusterRef":{"name":"central"},"deletionProtection":false,"instanceType":"small","masterUserSecretRef":{"name":"postgres-central-credentials","namespace":"crossplane-infra-it-central"}},"writeConnectionSecretToRef":{"name":"postgres-central-connection","namespace":"crossplane-infra-it-central"}}}
    xfn.crossplane.airnity.net/backup: 'true'
  name: central
```
