### ISSUE TITLE
RepoURL in git generator fails to template from cluster generator

### ISSUE THREAD

**Issue by aperullo** [argoproj/argo-cd#15625]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

A git generator's `repoURL` is failing to be templated properly from the result of a cluster generator.

I have a situation where the same repo is exposed under two different urls. There are two clusters, internal and external. Internal can only access the git repo at `https://myrepo.internal/gitops.git` and the other can only access it at  `https://myrepo.external/gitops.git`. In order to use the same repo in each cluster I need to change the repoURL in the git generator, but it doesn't.

**To Reproduce**

Use an ApplicationSet similar to the following:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-maker
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: internal
          values:
            repoURL: https://myrepo.internal/gitops.git
    - clusters:
        selector:
          matchLabels:
            cluster: external
          values:
            repoURL: https://myrepo.external/gitops.git
    - git:
        repoURL: '{{values.repoURL}}'
        revision: main
        files:
          - path: '*/application.yaml'

  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: '{{values.repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
```

**Expected behavior**

The ApplicationSet should result in one application per path in the git repo, with the url matching whether it was internal or external.

Instead it results in 
```
rpc error: code = Internal desc = unable to resolve git revision : repository not found
```

**Screenshots**

**Version**
`argocd: v2.8.0+804d4b8`

**Comment by crenshaw-dev** [comment]
The `spec.generators` list produces the output of each generator, one by one, and concatenates the output. No generator is aware of any other generators.

I think you're attempting to do something that the `matrix` generator does. I'd try something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-maker
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters:
              values:
                repoURL: '{{ (eq .metadata.labels.cluster "internal") | ternary "https://myrepo.internal/gitops.git" "https://myrepo.external/gitops.git" }}'
          - git:
              repoURL: '{{.values.repoURL}}'
              revision: main
              files:
                - path: '*/application.yaml'
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: '{{.values.repoURL}}'
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
```
