### ISSUE TITLE
Possible combine between helm values and valueFiles

### ISSUE THREAD

**Issue by chary1112004** [argoproj/argo-cd#15687]
# Summary

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-app

  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete.
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: bootstrap

  # Source of the application manifests
  sources:
    - repoURL: <repo>
      targetRevision: <branch>
      ref: values
    - repoURL: <repo>
      targetRevision: <branch>
      path: monitoring
      helm:
        valueFiles:
          - $values/common-values.yaml
          - $values/dev-values.yaml
        values: |-
          common:
             <value of file $values/common-values.yaml>
          monitoring:
              <value of file $values/dev-values.yaml>
```

# Proposal

We would like to combine between helm **values** and **valueFiles** (or another option that allow generate value into **values**  because most of value of file $values/dev-values.yaml that is from default value of helm chart and each time we upgrade for specific component then we need to add the tab. And it is not kind of convinence for all components.

Any suggestion or information to resolve this would be very much appreciated.

Thank you!

# Version

argocd: 2.7.3
