### ISSUE TITLE
Helm value files from external Git repository does not work with argocd-vault-plugin

### ISSUE THREAD

**Issue by ToonTijtgat2** [argoproj/argo-cd#15691]
Hi

We'd like to deploy helm charts from our azure container registry but use the value files from devops git repo.
The solution provided in https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository is the perfect solution for this.

The second requirement is using a key vault which is possible with argocd-vault-plugin.

If you use the sidecar for the plugin, passing the files in the directory with the multiple sources solutions does not work anymore it leaves the variable empty and sais it does not find the /.../.../values.yaml file.

Is there a way to solve this issue? options could be:
 1. add the argocd-vault-plugin as default in argocd so that we can use the default helm functionality instead of the sidecar
```
  sources:
  - repoURL: xxx.azurecr.io
    chart: tempo-distributed
    targetRevision: 1.6.4
    helm:
      valueFiles:
      - $values/tempo/base/values.yaml
      - $values/tempo/overlays/man-dev/values.yaml
  - repoURL: https://xxx.visualstudio.com/xxx/_git/argocd-applications
    targetRevision: feature/temp
    ref: values
```

 2. make it possible to pass the $values variable to the sidecar so that it recognize the path.
```
  sources:
  - repoURL: xxx.azurecr.io
    chart: tempo-distributed
    targetRevision: 1.6.4
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: "-f $values/tempo/base/values.yaml -f $values/tempo/overlays/man-dev/values.yaml"
  - repoURL: https://xxx.visualstudio.com/xxx/_git/argocd-applications
    targetRevision: feature/temp
    ref: values
```

Thanks in advance.
