### ISSUE TITLE
Helm + values + valueFiles not working as expected

### ISSUE THREAD

**Issue by phyzical** [argoproj/argo-cd#15706]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Hey, we currently use kustomize and are giving the helm approach a go

application manifest
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}-${environment}
  namespace: argocd
spec:
  project: ${environment}
  source:
    repoURL: https://github.com/xxx
    targetRevision: feature/helm-app
    path: helm/app
    helm:
      values: |-
        nameOverride:   I_AM_MIDDLE_OVERRIDE
      valueFiles:
        # TODO: this doesn't take precedence over ^
        - ../../manifests/${environment}/values.yaml
```    
../../manifests/${environment}/values.yaml
```
nameOverride: I_AM_FINAL_OVERRIDE
```

helm/app/values.yaml
```
nameOverride: I_AM_DEFAULT
```

i expected the following to result in a result similar to running 
```
kubectl get Applications  ${name}-${environment}-o jsonpath="{.spec.source.helm.values}" -n argocd > ./argocd-values.yml
helm template --debug ./helm/app -f  ./argocd-values.yml -f ../../manifests/${environment}/values.yaml
```

as in the merge order  i want to be used is
* /helm/app/values.yaml 
* ./argocd-values.yml
* ../../manifests/${environment}/values.yaml

But what i see is `./argocd-values.yml ` takes precedence over `../../manifests/${environment}/values.yaml`
or rather `helm.values` takes precedence over `valueFiles`
or rather `nameOverride:  I_AM_MIDDLE_OVERRIDE` is used for resources

But then in the ui the parameters section instead shows  `I_AM_FINAL_OVERRIDE`, But it isnt used.

 if i set an override value to anything it is then used and reflected on resources

What is the correct way this should be working?
should the parameter section reflect what should be getting used? 

or am i miss understanding something

**Version**

```shell
v2.8.4
```

Thanks!
