### ISSUE TITLE
Mutliple sources not working when sourcing helm chart from git

### ISSUE THREAD

**Issue by StoffelCPR** [argoproj/argo-cd#15745]
### Discussed in https://github.com/argoproj/argo-cd/discussions/15744

After continuing to debug myself I figured out that it works with charts directly from  a chart repo with the given sources in my app. Which leaves the question: Why doesn't it work with an umbrella chart from git? Is it not supposed to and if so why not?

<div type='discussions-op-text'>

<sup>Originally posted by **StoffelCPR** September 30, 2023</sup>
Heyo,

I can't seem to make it work correctly. I've seen your youtube video and thought about asking here.

My goal would be to have an umbrella chart repository in git in which I can write a values file for general configurations.

umbrella-chart-repo/
|-- Chart.yaml
|-- values.yaml

and then Cluster/Stage specific repository containing congifurations specific to those. For ease of use I'd like to use values files here as to not need complex patching in kustomizations to do this:

argocd-repository/
|-- application/
|--|-- argocd-application.yaml
|--|-- values-stage.yaml

I'm trying to accomplish this by using multiple sources:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ssh://git@gitaddress.example/argocd-repository.git
      targetRevision: HEAD
      ref: values
      
    - repoURL: ssh://git@gitaddress.example/umbrella-chart-repo.git
      path: ./
      targetRevision: HEAD
      helm:
        valueFiles:
        - values.yaml
        - $values/application/values-stage.yaml
    
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
```

As I said.. Nothing happens.. The umbrella charts' values file is sourced and shown in argocd. The remote values file is not used.

I've checked -> It works when I use a chart ref..

My question would be why it isn't working with the umbrella chart directly from git?</div>
