### ISSUE TITLE
rootPath & baseHref not working with Nginx ingress.

### ISSUE THREAD

**Issue by Yothgewalt** [argoproj/argo-cd#15750]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I finished setting up everything needed to make a custom path like baseHref, rootPath, and did Nginx ingress, my ArgoCD WebUI was blank.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2566-10-01 at 05 43 35](https://github.com/argoproj/argo-cd/assets/77398391/22df7b0c-10df-4dc6-b5b8-ba70b19a3df1)

**Version**
v2.8.4

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**My config argocd-cmd-params-cm.yaml**
```yaml
# Run server without TLS
  server.insecure: "true"
  # Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from / (default "/")
  server.basehref: "/_argocd/"
  # Used if Argo CD is running behind reverse proxy under subpath different from /
  server.rootpath: "/_argocd/"
```

**My ingress**
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: "nginx"
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /_argocd/
        backend:
          service:
            name: argocd-server
            port:
              name: https
    host: yoth.dev
  tls:
  - hosts:
    - yoth.dev
    secretName: argocd-secret
```

**Comment by Yothgewalt** [comment]
I forgot to added rootPath into manifests

**Comment by EF-NMR** [comment]
hi, If you can share the changes you made . I'm stuck configuring the argocd on a different rootpath, but failing

**Comment by AlexVCaron** [comment]
Please do ! Any hints would be good at that point

**Comment by zeitler** [comment]
hi

Looking for the same.

I was adding server.rootpath and server.basehref with /argocd as values to argocd-cm configmap - didn't work

Added  --rootpath /argocd --basehref  with same values to manifest. I believe if it installed through helm it would be extraArgs - it worked

Later I've found out that adding 
```
server.rootpath: /argocd
server.basehref: /argocd 
```
to argocd-cmd-params-cm configmap was enough. Anything else is needed. 


Taking the chance to clarify for the ones that are using SSO, that you must provide the full path in argocd-cm configmap. 

Conclusion:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.basehref: /argocd
  server.rootpath: /argocd
...
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"
  oidc.config: |-
    name: MyProvider
    issuer: https://<provider_url>
    clientID: <client id>
    clientSecret: $oidc.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    requestedIDTokenClaims:
      groups:
        essential: true
  url: https://<my hostname>/argocd
...
```

And finally, the ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: argocd-server-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: <my hostname>
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              name: https
        path: /argo
        pathType: Prefix
  tls:
  - hosts:
    - <my hostname>
    secretName: <my tls secret>
```

Hope it help
