### ISSUE TITLE
Scheme support for value files from external repositories

### ISSUE THREAD

**Issue by micwiel** [argoproj/argo-cd#15764]
# Summary

In the documentation I can see that `$values` variable need to be the first part of the path.
https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/multiple_sources.md?plain=1#L65-L66

# Motivation

In my case I need to use _helm secrets_ to store values securely in the git. It requires either use of wrapper command for example `helm secrets template` or to provide `secrets://` scheme in front of the values file path in the command.
https://github.com/jkroepke/helm-secrets/wiki/Usage#helm-wrapper
https://github.com/jkroepke/helm-secrets/wiki/Usage#alternative-decrypt-via-downloader-plugin

Helm secrets is one of the method which is mentioned here https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/ and seems to be a good choice for my use case.

# Proposal

It would be really helpful to have a possibility to define scheme in the path, for example: `secrets://$values/charts/prometheus/secrets.yaml`

**Comment by meysam81** [comment]
+1 for this one

**Comment by meysam81** [comment]
On the same token, the following also doesn't work when specifying the `path` in the second `source`.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hydra
  namespace: gitops
spec:
  project: ory
  sources:
    - repoURL: https://k8s.ory.sh/helm/charts
      chart: hydra
      targetRevision: 0.36.x
      helm:
        valueFiles:
          - $values/path/to/values/hydra-config.yml
          - $values/path/to/values/hydra-secret.enc.yml
    - repoURL: "git@github.com:myorg/myrepo.git"
      ref: values
      targetRevision: v1.0.0
      # path: path/to/values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ory
```
