### ISSUE TITLE
Compare Options is not working, resulting in Out of sync.

### ISSUE THREAD

**Issue by iyongmin01** [argoproj/argo-cd#15840]
Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**

Ignoring Resources That Are Extraneous setting for externalAccess.service.annotations in mongodb helm chart (bitnami) does not work.

Please help me.

https://argo-cd.readthedocs.io/en/release-2.8/user-guide/compare-options/#ignoring-resources-that-are-extraneous

**To Reproduce**

Install an application inside the cluster

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 14.0.4
    chart: mongodb
    helm:
      values: |
        replicaCount: 3
        architecture: replicaset
        rbac:
          create: true
        auth:
          enabled: true
          rootUser: root
          rootPassword: {{ .Values.rootPassword }}
        externalAccess:
          enabled: true
          autoDiscovery:
            enabled: true
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
              argocd.argoproj.io/compare-options: IgnoreExtraneous
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m0s"
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
```

**Expected behavior**

Service should have SYNC STATUS out-of-sync and
App should have SYNC STATUS in-sync.

![image](https://github.com/argoproj/argo-cd/assets/14326737/c41f1eb6-cc87-42c3-9ed2-51801d7ba09b)

**Offical User Guide**
![image](https://github.com/argoproj/argo-cd/assets/14326737/f185965e-6e6b-400c-99fa-e1b69494925f)

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/14326737/61d22bff-40e2-440d-ba02-69d81907ae84)

![image](https://github.com/argoproj/argo-cd/assets/14326737/baf793ae-aeb0-4413-bbf7-58afce8357ba)

**Version**

```shell
ArgoCD Version: argocd: v2.8.4+c279299
Helm Chart Version: 5.46.7
```
