### ISSUE TITLE
Can't ignore a non-existent pointer anymore

### ISSUE THREAD

**Issue by coderanger** [argoproj/argo-cd#1586]
**Describe the bug**

The code does [try to ignore errors](https://github.com/argoproj/argo-cd/blob/fc6df01b8e19bd7a764e3ee50e1564d876b00210/util/argo/diff_normalizer.go#L103) during normalization, but I think I found a new one:

```
time="2019-05-08T15:23:53Z" level=warning msg="Failed to normalize apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition//podvolumebackups.velero.io: jsonpatch remove operation does not apply: doc is missing path: \"/spec/additionalPrinterColumns/0/priority\""
```

(related: this is also a default field and should be getting ignored I think)

**To Reproduce**

```
  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
        - /spec/additionalPrinterColumns/0/priority
```

**Expected behavior**

Non-existent pointer targets should be ignored since they don't need to be removed.
