### ISSUE TITLE
Bad external URL link https://%!s(<nil>)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1590]
UI links to: https://%!s(<nil>) 

![image](https://user-images.githubusercontent.com/12677113/57432024-7d004880-71e9-11e9-99dd-88dcf8df7997.png)

application payload was generated incorrectly

![image](https://user-images.githubusercontent.com/12677113/57432141-df594900-71e9-11e9-832d-733ed4ae62d6.png)

here is the relevant ingress 

```yaml
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: cg-rtb-050719-deleteme-appd-service
              servicePort: 443
            path: /*
status:
  loadBalancer:
    ingress:
      - hostname: XXXXXX.us-west-2.elb.amazonaws.com
```
