### ISSUE TITLE
Resource hooks not running job when it's the only CRD

### ISSUE THREAD

**Issue by panbanda** [argoproj/argo-cd#15915]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I have a job that basically runs some kafka stuff.  It's the only resource in the helm chart.  

**To Reproduce**

Use a job in a helm chart:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-sync
  labels:
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    argocd.argoproj.io/hook: Sync
```

Deploy that with an argo application.

You'll notice that it gets deployed, synced, but the resources are missing.

**NOTE**: this annotation works elsewhere in our cluster where we have web / worker resources defined.  It seems to be happening only when it's the only resource in a chart.

**Expected behavior**

It should show up with the expected hook and run successfully.

**Screenshots**

<img width="557" alt="Screenshot 2023-10-11 at 4 41 30 PM" src="https://github.com/argoproj/argo-cd/assets/150944/d335947d-e2d0-49fc-a378-cdcb6f122983">

**Version**

```shell
{
    "Version": "v2.7.9+0ee33e5.dirty",
    "BuildDate": "2023-07-24T17:42:11Z",
    "GitCommit": "0ee33e52dd1f1bb944488584fc6f854b929f1180",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```
