### ISSUE TITLE
UI crashes when viewing app with no target state

### ISSUE THREAD

**Issue by duboisf** [argoproj/argo-cd#1592]
**Describe the bug**
I just upgraded to 1.0.0-rc2. I added an application that points to an empty folder. I was going to add the target state later but wanted to open the app in the UI first. Viewing the app without any target state crashes the UI with:

```
react-dom.production.min.js:198 TypeError: Cannot read property 'map' of undefined
    at Object.children (application-details.tsx:95)
    at t.render (data-loader.tsx:69)
    at Oi (react-dom.production.min.js:173)
    at Ai (react-dom.production.min.js:172)
    at Yi (react-dom.production.min.js:180)
    at Ga (react-dom.production.min.js:232)
    at Xa (react-dom.production.min.js:233)
    at Os (react-dom.production.min.js:249)
    at Cs (react-dom.production.min.js:248)
    at Es (react-dom.production.min.js:245)
```

**To Reproduce**

I use an `applications` application to manage my apps declaratively. I added a new app:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: someapp
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: falco/crashburn.infra.use1
    repoURL: git@github.com:someorg/deployments
    targetRevision: master
```

which I committed and pushed to github. Argocd proceeded to auto sync this new app and everything is fine, `someapp` appears in the UI. If I click it though, I get the above error and the UI becomes blank.

**Expected behavior**
To be able to see `someapp` even if it contains nothing.

**Screenshots**

**Additional context**
Noticed that if you try to do the same from the UI, it refuses since the target state path is empty... but still I feel the case of an app without any target state should handled gracefully by the UI.
