### ISSUE TITLE
helm.parameters.values can't expanded as a list parameter

### ISSUE THREAD

**Issue by kkk777-7** [argoproj/argo-cd#15930]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When setting the "**{a,b,c}**" format in the Helm parameters of Applicationset,  the parameters are not expanded as a list in the `helm template`.
I know that I can pass list parameters in array format (val[0], val[1]), it is inconvenient because the number of value in the variables is different for each Application.

**To Reproduce**

#### manifests
- Applicationset manifest (Display only related settings.)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  template:
    spec:
      source:
        helm:
          parameters:
          - name: listValue
            value: '{a,b,c}'
```
- Helm values.yaml
```yaml
listValue:
  - a
  - b
```
- Helm templates (pod.yaml)
```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: example
     args:
       {{- range .Values.listValue }}
       - --value={{ . }}
       {{- end }}
```

#### created resource
```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: example
     args:
       - --value=a,b,c
```
**Expected behavior**

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: example
     args:
       - --value=a
       - --value=b
       - --value=c
```

Referring to the [documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-parameters), `helm.parameters` is expanded as `helm template . --set`.

When executed locally, it is correctly expanded as a list parameter.
`helm template --set listValue={a,b,c}`

**Screenshots**

https://helm.sh/ja/docs/intro/using_helm/
<img width="1286" alt="スクリーンショット 2023-10-13 午前2 53 17" src="https://github.com/argoproj/argo-cd/assets/86363983/ea139df8-4613-481c-829e-f017ff7db0e2">

**Version**

```shell
argocd: v2.7.2+cbee7e6.dirty
  BuildDate: 2023-05-12T15:42:57Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.2+cbee7e6.dirty
  BuildDate: 2023-05-12T13:43:26Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**
