### ISSUE TITLE
ArgoCD sync doesn't wait until Helm/ArgoCD PreSync/Sync hooks completion

### ISSUE THREAD

**Issue by TemKaa1337** [argoproj/argo-cd#15968]
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to add migration mechanism to my application but here is the problem: i've tried argocd hooks and helm hooks (which are mapped to argo hooks), i expect this migration mechanism to apply migrations, wait until this process is ended and only then deploy my new application, but it doesn't work like this - migration hook starts, application deploys, migration ends.  So the problem is:
1) ArgoCD doesn't wait until PreSync hook completes and deploys other application parts
2) same as above but with Sync hook and sync waves (when sync hook has the lowest sync wave number).

Actually after two days investigation i found this  (https://github.com/argoproj/argo-cd/issues/9891) issue and just tried to do as one of commentators described, but it doesn't work.

Helm template output:
```
Source: REDACTED/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: REDACTED
    app.kubernetes.io/component: service
    app.kubernetes.io/name: REDACTED
    environment: dev
  annotations:
    eks.amazonaws.com/role-arn: REDACTED
    eks.amazonaws.com/sts-regional-endpoints: 'true'
    argocd.argoproj.io/sync-wave: "-2"
```
```
Source: REDACTED/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: REDACTED
    app.kubernetes.io/component: service
    app.kubernetes.io/name: demo
    environment:
  annotations:
      argocd.argoproj.io/sync-wave: "10"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/part-of: REDACTED
    app.kubernetes.io/component: service
    app.kubernetes.io/name: demo
```
```
Source: REDACTED/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: REDACTED
    app.kubernetes.io/component: service
    app.kubernetes.io/name: demo
    environment:
  annotations:
      argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: REDACTED
      app.kubernetes.io/component: service
      app.kubernetes.io/name: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: REDACTED
        app.kubernetes.io/component: service
        app.kubernetes.io/name: demo
        environment:
    spec:
      serviceAccountName: demo
      containers:
        - name: demo
          image: REDACTED
          securityContext:
            runAsNonRoot: true
            runAsUser: 82
            allowPrivilegeEscalation: false
          env:
            - ..here are some of envs
          ports:
            - here are some of ports
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
```
```
Source: REDACTED/templates/hooks/sync-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
    generateName: demo--0.0.1-sleep-hook
    labels:
        app.kubernetes.io/part-of: REDACTED
        app.kubernetes.io/component: service
        app.kubernetes.io/name: demo
        environment:
    annotations:
        argocd.argoproj.io/hook: Sync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
    backoffLimit: 0
    ttlSecondsAfterFinished: 1200
    template:
        metadata:
            name: sleep-hook
            labels:
                app.kubernetes.io/part-of: REDACTED
                app.kubernetes.io/component: service
                app.kubernetes.io/name: demo
                environment:
        spec:
            serviceAccountName: demo
            restartPolicy: Never
            containers:
                - name: sleep-hook
                  image: REDACTED
                  command: ["sleep", "120"]
                  securityContext:
                      runAsNonRoot: true
                      runAsUser: 82
                      allowPrivilegeEscalation: false
                  env:
                      - env vars...
                  ports:
                      - ports....
```

**Expected behavior**

ArgoCD must wait for every hook completion before going to next deployment/sync step.

Versions:
```
{
    "Version": "v2.8.3+77556d9",
    "BuildDate": "2023-09-07T16:05:43Z",
    "GitCommit": "77556d9e64304c27c718bb0794676713628e435e",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```
