### ISSUE TITLE
Rename source `ref` to `name` and make it a merge key

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#15975]
# Summary

```yaml
kind: Application
spec:
  sources:
  - name: my-chart # make "name" a required field 
    repoUrl: <helm chart>
    valueFiles:
    - $values/values-prod.yaml
  - name: values # call it "name" instead of "ref"
    repoUrl: <git repo>
```

# Motivation

Patching lists is difficult. It's easier with strategic merge patching when you define a merge key for the list items.

Adding this merge key would let users patch Applications using Kustomize or kubectl in a more precise and intuitive way.

It would also allow `ignoreApplicationDifferences` in ApplicationSets to avoid [strange behavior](https://github.com/argoproj/argo-cd/pull/15965) when trying to ignore individual fields in list items.

# Proposal

1. Rename `ref` to `name`. Why reuse `ref`? It already serves the similar purpose of uniquely identifying a source. Why call it `name`? Because that's more standard/expected for merge keys on lists.
2. Make the field required, because that's how merge keys work.

We shouldn't do this until Argo 3.0, because 1) renaming a field is a breaking API change, and 2) requiring the previously-optional field is another breaking API change.

Argo 3.0 should provide a mechanism to automatically rename the field on conversion, but it'll still have to throw an error and ask the user to name unnamed sources.
