### ISSUE TITLE
Using .repo.GetAppDetails).Helm.Name returns empty string

### ISSUE THREAD

**Issue by Evilong** [argoproj/argo-cd#15998]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using {{(call .repo.GetAppDetails).Helm.Name }} return a empty string

**To Reproduce**

Creating a notification template like the presented bellow, on a sync success the message will only have "---" as title instead of "RELEASE-NAME ---"

```yaml
template.app-sync-succeeded: |
        message: |
          Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
          Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
        slack:
          attachments: |-
            [{
              "title": "{{ (call .repo.GetAppDetails).Helm.Name }} ---",
              "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#18be52",
              "fields": [
              {
                "title": "Sync Status",
                "value": "{{.app.status.sync.status}}",
                "short": true
              }
              ]
            }]

```
**Expected behavior**

Using {{(call .repo.GetAppDetails).Helm.Name }} should return a string with Helm Release Name

**Version**

```shell
  argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
```
