### ISSUE TITLE
Example use of Build Environment variables in kustomization.yaml

### ISSUE THREAD

**Issue by appiepollo14** [argoproj/argo-cd#16010]
# Summary

Expand the documentation on this page: https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/ . There are only two lines related to the use of Build Environment variables in the kustomization.yaml files. However, there is no example. Please add an example to this page. 

# Motivation

I would love to use this feature in production, but am not able to without a sample.

# Proposal

Give a code example of the use of build environment in a kustomization.yaml file

**Comment by christianh814** [comment]
Hi @appiepollo14 , you're right. The docs aren't clear on this.

The use of Env Subs can be used in your Application Spec like this (for example):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    kustomize:
      commonAnnotationsEnvsubst: true
      commonAnnotations:
        app-source: ${ARGOCD_APP_NAME}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

Note that oyu have to enable this by setting `commonAnnotationsEnvsubst` to `true`. 

You can also use the build env vars with any CMP plugins you're using with Kustomize.
