### ISSUE TITLE
Add a doc for the meanings of 'p' and 'g' in the ArgoCD policy.csv file on RBAC Configuration page

### ISSUE THREAD

**Issue by able8** [argoproj/argo-cd#16029]
Some users are confused about what the `p` and `g` stand for?
Can we provide an explanation for what the "p" and "g" stand for to help clarify confusion among users?

On the RBAC Configuration page: https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/

I guess, p means permission or policy, and g means group or grant? 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, logs, get, *, allow
    p, role:org-admin, exec, create, */*, allow

    g, your-github-org:your-team, role:org-admin

```
