### ISSUE TITLE
upgrade 2.8.4 -> 2.9.0-rc2 sync error namespace creation

### ISSUE THREAD

**Issue by ohauer** [argoproj/argo-cd#16036]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

after upgrade from 2.8.4 to 2.9.0-rc2 argocd sync task failed to sync namespace, downgrade to 2.8.4 and issue is not present

Error msg, (relevant part):

```json
{
  "group": "",
  "hookPhase": "Running",
  "kind": "Namespace",
  "message": "namespace/cert-manager configured. Warning: resource namespaces/cert-manager is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically.",
  "name": "cert-manager",
  "namespace": "",
  "status": "Synced",
  "syncPhase": "Sync",
  "version": "v1"
}
```
**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: cluster-resources
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/cluster-resources/*.json
      repoURL: git@gitlab.example.org:devops/argocd/bootstrap-cluster.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-resources-{{name}}
      name: cluster-resources-{{name}}
      namespace: argocd
    spec:
      destination:
        server: '{{server}}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: default
      source:
        path: apps/cluster-resources/{{name}}
        repoURL: git@gitlab.example.org:devops/argocd/bootstrap-cluster.git
      syncPolicy:
        automated:
          allowEmpty: true
          selfHeal: true
```

file apps/cluster-resources/in-cluster.json

```json
{
  "name": "in-cluster",
  "server": "https://kubernetes.default.svc"
}
```

file apps/cluster-resources/in-cluster/ns-cert-manager.yaml

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  creationTimestamp: null
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
  name: cert-manager
```

**Expected behavior**

Sync will not fail
After downgrade to v2.8.4 issue is also gone

**Version**

Only for 2.8.4 since downgrade already happened

```shell
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.4+c279299
```

**Logs**
```
Message:   "" is invalid: patch: Invalid value: "{\"metadata\":{\"generation\":52164,\"labels\":{\"app.kubernetes.io/name\":\"cluster-resources-in-cluster\"},\"managedFields\":[{\"apiVersion\":\"argoproj.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:labels\":{\".\":{},\"f:app.kubernetes.io/name\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"498f2fa3-95b2-45e0-9458-2efee4a95741\\\"}\":{}}},\"f:spec\":{\".\":{},\"f:destination\":{\".\":{},\"f:server\":{}},\"f:ignoreDifferences\":{},\"f:project\":{},\"f:source\":{\".\":{},\"f:path\":{},\"f:repoURL\":{}},\"f:syncPolicy\":{\".\":{},\"f:automated\":{\".\":{},\"f:allowEmpty\":{},\"f:selfHeal\":{}}}},\"f:status\":{\".\":{},\"f:health\":{},\"f:summary\":{},\"f:sync\":{\".\":{},\"f:comparedTo\":{\".\":{},\"f:destination\":{},\"f:source\":{}}}}},\"manager\":\"argocd-applicationset-controller\",\"operation\":\"Update\",\"time\":\"2023-07-15T12:23:52Z\"},{\"apiVersion\":\"argoproj.io/v1alpha1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:status\":{\"f:controllerNamespace\":{},\"f:health\":{\"f:status\":{}},\"f:history\":{},\"f:operationState\":{\".\":{},\"f:finishedAt\":{},\"f:message\":{},\"f:operation\":{\".\":{},\"f:initiatedBy\":{\".\":{},\"f:automated\":{}},\"f:retry\":{\".\":{},\"f:limit\":{}},\"f:sync\":{\".\":{},\"f:revision\":{}}},\"f:phase\":{},\"f:startedAt\":{},\"f:syncResult\":{\".\":{},\"f:resources\":{},\"f:revision\":{},\"f:source\":{\".\":{},\"f:path\":{},\"f:repoURL\":{}}}},\"f:reconciledAt\":{},\"f:resources\":{},\"f:sourceType\":{},\"f:sync\":{\"f:comparedTo\":{\"f:destination\":{\"f:server\":{}},\"f:ignoreDifferences\":{},\"f:source\":{\"f:path\":{},\"f:repoURL\":{}}},\"f:revision\":{},\"f:status\":{}}}},\"manager\":\"argocd-application-controller\",\"operation\":\"Update\",\"time\":\"2023-10-19T11:43:26Z\"}],\"name\":\"cluster-resources-in-cluster\",\"namespace\":\"argocd\",\"ownerReferences\":[{\"apiVersion\":\"argoproj.io/v1alpha1\",\"blockOwnerDeletion\":true,\"controller\":true,\"kind\":\"ApplicationSet\",\"name\":\"cluster-resources\",\"uid\":\"498f2fa3-95b2-45e0-9458-2efee4a95741\"}],\"resourceVersion\":\"378287483\",\"uid\":\"d43e0fc1-be74-4cc7-98b6-b66d206dbbc8\"},\"spec\":{\"destination\":{\"server\":\"https://kubernetes.default.svc\"},\"ignoreDifferences\":[{\"group\":\"argoproj.io\",\"jsonPointers\":[\"/status\"],\"kind\":\"Application\"}],\"project\":\"default\",\"source\":{\"path\":\"apps/cluster-resources/in-cluster\",\"repoURL\":\"git@gitlab.example.org:devops/argocd/bootstrap-cluster.git\"},\"syncPolicy\":{\"automated\":{\"allowEmpty\":true,\"selfHeal\":true}}},\"status\":{\"controllerNamespace\":\"argocd\",\"health\":{\"status\":\"Healthy\"},\"history\":[{\"deployStartedAt\":\"2023-07-15T12:59:09Z\",\"deployedAt\":\"2023-07-15T12:59:10Z\",\"id\":0,\"revision\":\"4836df62692c12a66376b8f16d1bd16ded740633\",\"source\":{\"path\":\"apps/cluster-resources/in-cluster\",\"repoURL\":\"git@gitlab.example.org:devops/argocd/bootstrap-cluster.git\"}},{\"deployStartedAt\":\"2023-07-25T14:45:22Z\",\"deployedAt\":\"2023-07-25T14:45:24Z\",\"id\":1,\"revision\":\"7103270bfb55ec3a0e47b545f5f838b94c73dce0\",\"source\":{\"path\":\"apps/cluster-resources/in-cluster\",\"repoURL\":\"git@gitlab.example.org:devops/argocd/bootstrap-cluster.git\"}}],\"operationState\":{\"finishedAt\":\"2023-07-25T14:45:24Z\",\"message\":\"successfully synced (all tasks run)\",\"operation\":{\"initiatedBy\":{\"automated\":true},\"retry\":{\"limit\":5},\"sync\":{\"revision\":\"7103270bfb55ec3a0e47b545f5f838b94c73dce0\"}},\"phase\":\"Succeeded\",\"startedAt\":\"2023-07-25T14:45:22Z\",\"syncResult\":{\"resources\":[{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/logging configured\",\"name\":\"logging\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/argocd configured\",\"name\":\"argocd\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/kubecost configured\",\"name\":\"kubecost\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/kyverno configured\",\"name\":\"kyverno\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/nfs-system configured\",\"name\":\"nfs-system\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/external-secrets configured\",\"name\":\"external-secrets\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/external-dns configured\",\"name\":\"external-dns\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/monitoring configured\",\"name\":\"monitoring\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/metallb-system configured\",\"name\":\"metallb-system\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"\",\"hookPhase\":\"Running\",\"kind\":\"Namespace\",\"message\":\"namespace/cert-manager configured. Warning: resource namespaces/cert-manager is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically.\",\"name\":\"cert-manager\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"},{\"group\":\"networking.k8s.io\",\"hookPhase\":\"Running\",\"kind\":\"IngressClass\",\"message\":\"ingressclass.networking.k8s.io/nginx unchanged\",\"name\":\"nginx\",\"namespace\":\"\",\"status\":\"Synced\",\"syncPhase\":\"Sync\",\"version\":\"v1\"}],\"revision\":\"7103270bfb55ec3a0e47b545f5f838b94c73dce0\",\"source\":{\"path\":\"apps/cluster-resources/in-cluster\",\"repoURL\":\"git@gitlab.example.org:devops/argocd/bootstrap-cluster.git\"}}},\"reconciledAt\":\"2023-10-19T11:43:25Z\",\"resources\":[{\"kind\":\"Namespace\",\"name\":\"argocd\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"cert-manager\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"external-dns\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"external-secrets\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"kubecost\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"kyverno\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"logging\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"metallb-system\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"monitoring\",\"status\":\"Synced\",\"version\":\"v1\"},{\"kind\":\"Namespace\",\"name\":\"nfs-system\",\"status\":\"Synced\",\"version\":\"v1\"},{\"group\":\"networking.k8s.io\",\"kind\":\"IngressClass\",\"name\":\"nginx\",\"status\":\"Synced\",\"version\":\"v1\"}],\"sourceType\":\"Directory\",\"summary\":{},\"sync\":{\"comparedTo\":{\"destination\":{\"server\":\"https://kubernetes.default.svc\"},\"ignoreDifferences\":[{\"group\":\"argoproj.io\",\"jsonPointers\":[\"/status\"],\"kind\":\"Application\"}],\"source\":{\"path\":\"apps/cluster-resources/in-cluster\",\"repoURL\":\"\"}},\"revision\":\"7bccba9b48fe9499479f3aa7780732b1739d3067\",\"status\":\"\"}}}": Object 'Kind' is missing in '{"metadata":{"generation":52164,"labels":{"app.kubernetes.io/name":"cluster-resources-in-cluster"},"managedFields":[{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:app.kubernetes.io/name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"498f2fa3-95b2-45e0-9458-2efee4a95741\"}":{}}},"f:spec":{".":{},"f:destination":{".":{},"f:server":{}},"f:ignoreDifferences":{},"f:project":{},"f:source":{".":{},"f:path":{},"f:repoURL":{}},"f:syncPolicy":{".":{},"f:automated":{".":{},"f:allowEmpty":{},"f:selfHeal":{}}}},"f:status":{".":{},"f:health":{},"f:summary":{},"f:sync":{".":{},"f:comparedTo":{".":{},"f:destination":{},"f:source":{}}}}},"manager":"argocd-applicationset-controller","operation":"Update","time":"2023-07-15T12:23:52Z"},{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:controllerNamespace":{},"f:health":{"f:status":{}},"f:history":{},"f:operationState":{".":{},"f:finishedAt":{},"f:message":{},"f:operation":{".":{},"f:initiatedBy":{".":{},"f:automated":{}},"f:retry":{".":{},"f:limit":{}},"f:sync":{".":{},"f:revision":{}}},"f:phase":{},"f:startedAt":{},"f:syncResult":{".":{},"f:resources":{},"f:revision":{},"f:source":{".":{},"f:path":{},"f:repoURL":{}}}},"f:reconciledAt":{},"f:resources":{},"f:sourceType":{},"f:sync":{"f:comparedTo":{"f:destination":{"f:server":{}},"f:ignoreDifferences":{},"f:source":{"f:path":{},"f:repoURL":{}}},"f:revision":{},"f:status":{}}}},"manager":"argocd-application-controller","operation":"Update","time":"2023-10-19T11:43:26Z"}],"name":"cluster-resources-in-cluster","namespace":"argocd","ownerReferences":[{"apiVersion":"argoproj.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"ApplicationSet","name":"cluster-resources","uid":"498f2fa3-95b2-45e0-9458-2efee4a95741"}],"resourceVersion":"378287483","uid":"d43e0fc1-be74-4cc7-98b6-b66d206dbbc8"},"spec":{"destination":{"server":"https://kubernetes.default.sv
```
