### ISSUE TITLE
Validation for HPA and Deployment/replicas

### ISSUE THREAD

**Issue by shaoxt** [argoproj/argo-cd#1603]
**Is your feature request related to a problem? Please describe.**
The suggested way to apply HPA on Deployment is to get rid of "replicas" in DeploymentSpec.
But it scales down to 1 pod when deleting the replicas on existing Deployment.
Here is the issue
https://github.com/kubernetes/kubernetes/issues/25238

**Describe the solution you'd like**

## argocd app **hpa** sample-namespace

1.  Check whether there is any HorizontalPodAutoscaler
    - If YES, check whether the target is a **Deployment**
        - If YES, goto step 2
        - If NO, return
    - If NO,  return
2. Check whether the Deployment has **replicas**
    - If YES, show error, suggest to delete the replicas
    - If NO, goto step 3
3. Sync HorizontalPodAutoscaler **ONLY** to make sure it get synced.
    - If SUCCESS, goto step 4
    - If NO, show error
4. Check whether the old Deployment has **replicas**
   - If YES, run "kubectl apply set-last-applied -f deployment.yaml -n ${THE_NAMESPACE}", deployment.yaml  is the **OLD** Deployment Spec
   - If NO, return

## argocd app sync  sample-namespace

HPA Sample:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  labels:
    app: hpa-samples
  name: hpa-samples
spec:
  minReplicas: 3
  maxReplicas: 30
  metrics:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: hpa-samples
```

**Describe alternatives you've considered**

**Additional context**
