### ISSUE TITLE
oauth2: "invalid_client" "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."

### ISSUE THREAD

**Issue by mconigliaro** [argoproj/argo-cd#16043]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

SSO authentication doesn't work in the CLI, but it works just fine in the web UI. Our identity provider is Jumpcloud.

**To Reproduce**

```
oidc.config:
  name: JumpCloud
  issuer: https://oauth.id.jumpcloud.com/
  clientID: REDACTED
  clientSecret: REDACTED
dex:
  enabled: false
```

```
$ argocd login REDACTED --grpc-web --sso
Opening browser for authentication
Performing authorization_code flow login: https://oauth.id.jumpcloud.com/oauth2/auth?access_type=offline&client_id=REDACTED&code_challenge=Pn8Qe1URVDoBNW9g6hQVttT_cIaDRNl09aVsYwVk8ek&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=dhgljZvoVBWnyXEluhWMySFX
FATA[0003] oauth2: "invalid_client" "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."
```

**Version**

```shell
argocd: v2.8.4+c279299.dirty
  BuildDate: 2023-09-13T22:00:14Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: dirty
  GoVersion: go1.21.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Comment by patrickshan** [comment]
we are having similar issues with argocd cli sso login using Okta:
```
oauth2: &#34;invalid_client&#34; &#34;Client authentication failed. Either the client or the client credentials are invalid.&#34;
```
argocd cli version: 2.8.5
argocd server version: 2.8.5

**Comment by b8kings0ga** [comment]
having the same issue right now

**Comment by alexlokshin-czi** [comment]
Same problem here!

**Comment by patrickshan** [comment]
Just tested with latest v2.9.5 release and same issues still exists

**Comment by llavaud** [comment]
same problem here with latest v2.10.1 version

**Comment by fcrespofastly** [comment]
Same problem with latest

**Comment by TheDevMinerTV** [comment]
Same issue here happening when using Authentik as our IdP.

**Comment by dothinh316** [comment]
same issue here with okta

**Comment by zentavr** [comment]
Had it been resolved for 9 month so far??

**Comment by zentavr** [comment]
Someone had it working here: https://github.com/argoproj/argo-cd/issues/12124#issuecomment-1717865942

**Comment by zentavr** [comment]
The solution for Keykloak is here: https://github.com/argoproj/argo-cd/issues/12124#issuecomment-2204914627

**Comment by dothinh316** [comment]
> Someone had it working here: [#12124 (comment)](https://github.com/argoproj/argo-cd/issues/12124#issuecomment-1717865942)

Thank you! this was helpful and worked!

**Comment by zentavr** [comment]
@alexmt probably this should be added to the docs and the case could be closed

**Comment by llavaud** [comment]
I have the same problem with Jumpcloud IdP, I am not sure about the config I need to set with Jumpcloud

**Comment by santiagon610** [comment]
> I have the same problem with Jumpcloud IdP, I am not sure about the config I need to set with Jumpcloud

@llavaud - This is what I'm using in my values file with Jumpcloud as an IdP, hopefully it works for you with appropriate tweaking:

```yaml
  configs:
    cm:
      create: true
      oidc.config: |
          name: "Jumpcloud"
          issuer: "https://oauth.id.jumpcloud.com/"
          clientID: "MY_JUMPCLOUD_CLIENT_ID"
          clientSecret: "MY_JUMPCLOUD_CLIENT_SECRET"
          requestedScopes:
            - openid
            - email
            - profile
            - groups
    rbac:
      create: true
      scopes: "[groups]"
      policy.csv: |
        p, role:clusterAdmin, *, *, *, allow
        p, role:noPerms, *, *, *, deny
        g, MY_JUMPCLOUD_ADMIN_GROUP, role:clusterAdmin
        g, MY_JUMPCLOUD_READONLY_GROUP, role:readonly
```

In Jumpcloud, I have the following as an authorized redirect URI: `https://MY-ARGOCD-FQDN/auth/callback`, and am including the group attribute of `groups`.

Hope this helps!

**Comment by llavaud** [comment]
> > I have the same problem with Jumpcloud IdP, I am not sure about the config I need to set with Jumpcloud
> 
> @llavaud - This is what I'm using in my values file with Jumpcloud as an IdP, hopefully it works for you with appropriate tweaking:
> 
> ```yaml
>   configs:
>     cm:
>       create: true
>       oidc.config: |
>           name: "Jumpcloud"
>           issuer: "https://oauth.id.jumpcloud.com/"
>           clientID: "MY_JUMPCLOUD_CLIENT_ID"
>           clientSecret: "MY_JUMPCLOUD_CLIENT_SECRET"
>           requestedScopes:
>             - openid
>             - email
>             - profile
>             - groups
>     rbac:
>       create: true
>       scopes: "[groups]"
>       policy.csv: |
>         p, role:clusterAdmin, *, *, *, allow
>         p, role:noPerms, *, *, *, deny
>         g, MY_JUMPCLOUD_ADMIN_GROUP, role:clusterAdmin
>         g, MY_JUMPCLOUD_READONLY_GROUP, role:readonly
> ```
> 
> In Jumpcloud, I have the following as an authorized redirect URI: `https://MY-ARGOCD-FQDN/auth/callback`, and am including the group attribute of `groups`.
> 
> Hope this helps!

And the CLI auth works ?

**Comment by santiagon610** [comment]
@llavaud - Just tested it again, and it looks like I'm now having the same issue as you are.

```
❯ argocd login ${ARGOCD_FQDN}" --sso
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
Opening browser for authentication
Performing authorization_code flow login: https://oauth.id.jumpcloud.com/oauth2/auth?access_type=offline&client_id=e0e1e1b9-8f9d-4971-a244-58836ae5c27c&code_challenge=fB21uzObiaSM_viiplE80ADRXRyJuw3QNFyGZOZ2MaY&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+email+profile+groups+offline_access&state=LKqYUudIniScERlgiCWthnDk
FATA[0014] oauth2: "invalid_client" "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)." 
```

**Comment by zentavr** [comment]
@santiagon610 @llavaud - don't have JumpCloud on hands, the pic is taken from the [docs](https://jumpcloud.com/support/sso-with-oidc):
![image](https://github.com/argoproj/argo-cd/assets/595334/e6bdb818-e3d9-40f0-8959-df08687f892e)

Just try to set up:
- Client authentication type: Public (None PKCE)

Also there should be at least 2 URLs:
1. The one with ${ARGOCD_FQDN}
2. http://localhost:8085/auth/callback

**Comment by santiagon610** [comment]
> Just try to set up:
> 
> * Client authentication type: Public (None PKCE)
> 

That did it, thanks @zentavr -

```
❯ argocd login "${MY_ARGOCD_FQDN}" --sso
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
Opening browser for authentication
Performing authorization_code flow login: https://oauth.id.jumpcloud.com/oauth2/auth?access_type=offline&client_id=${MY_JUMPCLOUD_APP_CLIENT_ID}&code_challenge=W2FYbei4X8p32Uqvjw-v6xqkrA-7LnaUsRyvLqd9Zag&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+email+profile+groups+offline_access&state=acCEpNAHCyznaKDqBZQKNNsH
Authentication successful
'${MY_SSO_ID}' logged in successfully
Context '${MY_ARGOCD_FQDN}' updated

❯ argocd proj list | grep default
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
default                               *,*                       *        */*                         <none>                        <none>          disabled
```

My current values are as follow:
```yaml
configs:
  cm:
    create: true
    oidc.config: |
      name: "Jumpcloud"
      issuer: "https://oauth.id.jumpcloud.com"
      clientID: "${MY_JUMPCLOUD_APP_CLIENT_ID}"
      enablePKCEAuthentication: true
      requestedScopes:
        - openid
        - email
        - profile
        - groups
  rbac:
    create: true
    scopes: "[groups]"
    policy.csv: |
      p, role:clusterAdmin, *, *, *, allow
      p, role:noPerms, *, *, *, deny
      g, ${MY_JUMPCLOUD_ADMIN_GROUP}, role:clusterAdmin
      g, ${MY_JUMPCLOUD_RO_GROUP}, role:readonly
```

@llavaud - it might be worth trying on your end, if you're able to.
