### ISSUE TITLE
ArgoCD should support attributes that can explicitly disable application deletion and syncing

### ISSUE THREAD

**Issue by shapirus** [argoproj/argo-cd#16063]
# Summary
There should be a way to explicitly block application deletion and syncing, regardless of what sequence of actions leads to them, using attributes in the Application object spec.

# Motivation
There are many types of applications whose accidental deletion may result in a disaster: mission-critical applications, the "applications" application, applications that contain persistent volumes, application that manages ArgoCD itself etc.

Human errors happen.

There are multiple possibilities to trigger an unwanted deletion: from deleting a wrong application via the web UI (and even confirming it by typing the app name in the input field, which is a mistake easily made after a long day) to a poorly carried out migration of ArgoCD from cluster to cluster when one of the instances begins removing everything that it manages.

There are also situations when an unwanted sync may lead to a disaster, e.g., manifest path errouneously set to a wrong location and either auto-sync being enabled or the operator not checking the manifest diff before clicking Sync manually.

Application manifests often include namespace objects. If such an object is deleted following an accidental application deletion or syncing to a wrong set of manifests, then it can also be a disaster, such as losing data on persistent volumes that will be deleted following the deletion of the namespace, as well as losing state kept in CRD-managed objects.

The possibility to explicitly disable app deletion and sync would be similar in its purpose to, for example, the instance termination protection or the RDS deletion protection attributes supported by AWS which serve as additional protection against accidental resource termination by both humans and automated resource management tools.

# Proposal
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mission-critical-app
spec:
  deletionPolicy:
    automated:
      disable-condition: always
    cli:
      disable-condition: always
    web-ui:
      disable-condition: always
  syncPolicy:
    automated:
      disable-condition: always
    cli:
      disable-condition: always
    web-ui:
      disable-condition: require-extra-confirmation
```

The `automated` section is for the decisions made by ArgoCD itself. The rest are for externally triggered actions. The reason why I am proposing to make separate declarations for `cli` and `web-ui` is because the former is often used for external CI/CD workflows which are non-interactive with regards to human presence, and the latter is more likely to be used by humans, so they will serve different use cases.

This would create a unified and consistent method of specifying a set of human-readable unambiguous attributes as part of the application spec (as opposed to annotations which are generally harder to understand and track) to protect mission-critical resources regardless of whether the applications are standalone or managed by appsets.
