### ISSUE TITLE
No-diff Sync Fails

### ISSUE THREAD

**Issue by antwacky** [argoproj/argo-cd#16070]
Checklist:

* [ /] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ /] I've included steps to reproduce the bug.
* [ /] I've pasted the output of `argocd version`.

**Describe the bug**

I restored a PVC, which added dataSource and dataSourceRef spec fields to the PVC (referring to the source VolumeSnapShot).

This rightly caused ArgoCD to report the application as out of sync, as it is unaware of these dataSource fields.

To work around this, I added the below configuration to the ArgoCD configmap:

```
  resource.customizations.ignoreDifferences.all: |
    jsonPointers:
      - /spec/dataSource
      - /spec/dataSourceRef
      - /spec/storageClassName
```

This worked, and now the PVC and application shows as 'Synced'.

However, despite the fact that ArgoCD shows now there is no diff, and the application is in sync, when I click sync, I get sync failed.

**To Reproduce**

- Deploy an application with a PVC
- Once synced, delete the PVC and restore from a VolumeSnapshot using the dataSource field
- Configure ArgoCD configmap to ignore the relevant fields
- Observe that the application is now 'Synced'
- Attempt to sync
- Observe that the sync fails

**Expected behavior**

I expect the application to be in sync, and syncing to be successful.

**Version**

```shell
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
one or more objects failed to apply, reason: PersistentVolumeClaim "jenkins" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims   core.PersistentVolumeClaimSpec{    ... // 2 identical fields    Resources: {Requests: {s"storage": {i: {...}, s: "150Gi", Format: "BinarySI"}}},    VolumeName: "pvc-6cc09d41-7fd1-40b5-b79f-bfb624aa2f5d", -  StorageClassName: &"vsphere-csi", +  StorageClassName: nil,    VolumeMode: &"Filesystem",    DataSource: &{APIGroup: &"snapshot.storage.k8s.io", Kind: "VolumeSnapshot", Name: "jenkins-20-10-2023-15-19-48"},    DataSourceRef: &{APIGroup: &"snapshot.storage.k8s.io", Kind: "VolumeSnapshot", Name: "jenkins-20-10-2023-15-19-48"},   }
```

**Comment by rumstead** [comment]
Have you enabled the [respect ignore diff sync option](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs)?

**Comment by antwacky** [comment]
Sure, here you go:

```
project: default
source:
  repoURL: 'https://gitlab.com/argocd.git'
  path: ./apps/jenkins
  targetRevision: master
destination:
  server: 'https://kubernetes.default.svc'
  namespace: jenkins
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - kind: Secret
    jsonPointers:
      - /data/jenkins
```

**Comment by rumstead** [comment]
https://github.com/argoproj/argo-cd/issues/12569 looks to be the same issue.

Nasty, but I wonder if you can ignore the entire `spec`.

**Comment by antwacky** [comment]
I've tried that an it's still failing to sync...

It's slightly strange because as I've said, ArgoCD reports that there is no differences, and the app is in sync.

So theoretically, clicking sync shouldn't actually do anything.

```
project: default
source:
  repoURL: 'https://gitlab.com/argocd.git'
  path: ./apps/jenkins
  targetRevision: master
destination:
  server: 'https://kubernetes.default.svc'
  namespace: jenkins
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - kind: Secret
    jsonPointers:
      - /data/jenkins
  - kind: PersistentVolumeClaim
    jsonPointers:
      - /spec
```
