### ISSUE TITLE
Undetected diffs when adding a key in the live manifest from the UI

### ISSUE THREAD

**Issue by PonchonB** [argoproj/argo-cd#16092]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello, and first of all thanks for your hard work on ArgoCD. It has been of great use for us to manage several applications. In particular it allows our dev teams to conveniently modify live manifests for some Kubernetes resources without leaving the ArgoCD web interface. 

Usually when modifying the live manifest on an application resource within ArgoCD UI, the sync status of the application changes to "out of sync" and the APP DIFF shows the difference between the new live manifest and the desired manifest.

However when the edit to the live manifest involves adding a new key to a manifest (for instance the `args` key to a cronjob/deployment pod template spec or a new data key in a configmap), this edit seems undetected: the app still appears as synced with the target manifest and syncing the app/resource does not revert the key addition to the manifest.

Is it an expected behavior? Am I missing something?
 
**To Reproduce**

Minimal set-up to reproduce this issue:

1. ArgoCD basic setup. 
 
- Leave all application controller parameters to their default value.
 
- one EKS cluster, a `reproduce-bug-argocd-missing-diff` namespace and proper IAM + Kubernetes RBAC configuration for the argocd user

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: argocd
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd
  namespace: reproduce-bug-argocd-missing-diff
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - rbac.authorization.k8s.io
      - extensions
      - keda.sh
      - policy
      - batch
      - networking.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd
  namespace: reproduce-bug-argocd-missing-diff
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: argocd
    namespace: default

```

- a source repository

- a simple ArgoCD application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-argocd-bug-reproduction
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: <source repository URL>
    targetRevision: <source branch>
    path: <path-to-Helm-chart-parent-directory>/test-app
  destination:
    name: <cluster name>
    namespace: "reproduce-bug-argocd-missing-diff"
```

2. Create a simple Helm chart with a configmap as only resource. Commit it and push it to a branch of your source repository:

test-app/Chart.yaml:

```yaml
apiVersion: v2
name: test-app
description: Test application to reproduce ArgoCD missing diff bug in container args
kubeVersion: ">= v1.20-0"
type: application
version: 0.0.1
appVersion: "0.0.1"
```

test-app/templates/test-configmap.yaml:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  namespace: reproduce-bug-argocd-missing-diff
data:
  TEST_KEY: "test-value"
```

3. In ArgoCD web interface, edit the live manifest of the application test-configmap resource to add a another data key:

<img width="1303" alt="image" src="https://github.com/argoproj/argo-cd/assets/12891660/5d8397ac-1088-4927-b731-0e20e6d0ba52">

**Expected behavior**

- The application sync status should be `OUT OF SYNC`

- In the DIFF tab of the configmap resource or in the APP DIFF panel of the application, we should see the diff with the desired manifest (that does not possess this other key). It's the case when altering any key present in the live manifest: 

<img width="1311" alt="image" src="https://github.com/argoproj/argo-cd/assets/12891660/84ac867d-d5a2-47f8-9ff8-2fc0633815fe">

- When syncing the app, the added data key of the configmap should be removed.

**Actual Behavior**

- The application sync status is `SYNCED``

- No diff is detected between the live manifest and the desired manifest

- If syncing the application, nothing changes

Live Manifest:
<img width="1311" alt="image" src="https://github.com/argoproj/argo-cd/assets/12891660/f5c501f7-3b6d-4ce6-9460-14c8541551b8">

Desired Manifest:
<img width="1311" alt="image" src="https://github.com/argoproj/argo-cd/assets/12891660/7f60440e-9c39-4c85-958d-5e33f5863277">

Diff:
<img width="1311" alt="image" src="https://github.com/argoproj/argo-cd/assets/12891660/741a84b2-1c73-4c51-adbb-18426ba265c4">

**Version**

```shell
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:05:39Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64```
