### ISSUE TITLE
We want argo to ignore "Degraded" status for synced object with problematic event

### ISSUE THREAD

**Issue by tommeramber** [argoproj/argo-cd#16102]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
We are trying to sync SecretStore object (Hashicorp Vault object) using Argo to our Openshift 4.12 cluster.

The status of the object is "Synced" but the Health is "Degraded".
We see that the object presents the following event:
```
Reason: InvalidProviderConfig
Message: unable ...
```
And in the object yaml:
```
oc get secretstore -o yaml 
```
```
Output:
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
   name: vault-secretstore
   namespace: test
spec:
...
status:
  conditions:
  - lastTransitionTime: ..
    message: unable to ...
    reason: InvalidProviderConfig
    status: 'False'
    type: Ready
```

The details of the event is irrelevant, we just want argo to sync the object into the cluster, and ignore the `.status.conditions` section entirly (like it does for basicly every other object in the cluster)
1. We dont understand why for this particular object argocd looks at the status section
2. We cant figure how to configure argocd to ignore it. We've tried multiple options from the documentation and nothing worked.

We know that the right solution should be to "fix" the object so no problematic events will alert, but we would like are to ignore them for this specific object

**To Reproduce**

**Expected behavior**

Ignore 'failed' conditions for this object

**Screenshots**

due to sensitivity of the environment we cannot add screenshots

**Version**

ArgoCD version: 2.7.2

**Logs**

Querying for resource events with field selector: involvedObject.name=clustersecretstores.external-secret.io...
