### ISSUE TITLE
ApplicationSet: Allow skipping files with Git Generator based on file content

### ISSUE THREAD

**Issue by Vince-Chenal** [argoproj/argo-cd#16138]
# Summary

The Git Generator currently fetches all matching files from a Git repository, parses them to extract params and generate an ArgoCD application for each file.
It would be great if we could skip a file based on a configuration field within the file itself.

# Motivation

Let's take this example where each file corresponds to different environments of the same project:
```
root
├── production
│   └── myproject.yaml
└── staging
    └── myproject.yaml
```

If I only want to create staging Application, I need to push only staging file.
It would be great if we could push both but disable production one by setting a defined configuration field in the file directly.

# Proposal

We could define a `skipKey` setting that would allow to define a specific param to search within the parsed file.
If the param equals true then we skip file evaluation and skip Application creation.

```
generators:
  - git:
      repoURL: https://github.com/somerepo
      revision: main
      files:
        - "root/*/*.yaml"
      skipKey: skip
```

And the file for production could be skipped by setting the `skip` key within the file:
```
---
skip: true

# production related stuffs....
```

**Comment by christianh814** [comment]
Which Git generator are you using? Using the Git Dir Generator or Git File Generator?

**Comment by rumstead** [comment]
Why not make the files glob more restrictive to avoid the git files you want to be skipped? There is a relatively [new globbing feature](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git-File-Globbing/#enabling-the-new-globbing) that may help. 

Or as @christianh814 is most likely alluding to, use the [git directory generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#exclude-directories) and skip.

**Comment by crenshaw-dev** [comment]
Every generator also supports the ability to filter on arbitrary parameters: https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators-Post-Selector/

So you could do this:

```yaml
generators:
  - git:
      repoURL: https://github.com/somerepo
      revision: main
      files:
        - "root/*/*.yaml"
    selector:
      matchExpressions:
        - key: skip
          operator: NotIn
          values:
            - "true"
```

The value might need to be quoted to avoid running afoul of `matchExpressions` expectations.

```yaml
skip: "true"
```

**Comment by Vince-Chenal** [comment]
Wow I completely missed the updates on this issue, my bad :grimacing: 
@crenshaw-dev post selectors are exactly what I need, thank you :ok_hand:

**Comment by rajatgupta828** [comment]
@crenshaw-dev @Vince-Chenal  Were you able to achieve it from the files ?

I am using a matrix generator : 

`
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
              revision: HEAD
              directories:
                - path: "application-sets/appsets-dir/addons/*"
            selector:
              matchExpressions:
                - key: skip
                  operator: NotIn
                  values:
                    - "true"
          - list:
              elements:
              - cluster: kind
                url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.path.basename}}-{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - base-values.yaml
            - '{{.cluster}}-values.yaml'
      destination:
        namespace: "nginx"
        server: '{{.url}}'
`


At git@github.com:rajatgupta828-stem/federated-argocd-test.git repo ,  I have a directory : 

application-sets/appsets-dir/addons/*

`
├── README.md
├── application-sets
│   ├── appsets-dir
│   │   ├── addons
│   │   │   └── nginx
│   │   │       ├── Chart.yaml
│   │   │       ├── base-values.yaml
│   │   │       └── kind-values.yaml
│   │   └── cluster-addons.yaml
│   └── argocd-addons
│       └── argocd-addons-application.yaml
├── archived
│   ├── application-of-applicationsets.yaml
│   └── infra-apps
│       └── applicationset-nginx.yaml
├── kind-local-k8s-2.kubeconfig
└── projects
    └── add-on-project.yaml
`

In the list generator 

`
          - list:
              elements:
              - cluster: kind
                url: https://kubernetes.default.svc
`

I could define all clusters under my project
Is there a way I can skip nginx installation for any 1 of clusters ?

I tried solution mentioned by @crenshaw-dev  

And at kind-values.yaml i have defined as below : 

`
skip: "true"

global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  ## Security parameters
  ##
......
`

But this application gets rendered regardless.

![Image](https://github.com/user-attachments/assets/14a1d7da-0da8-4c5e-a4f5-8656236b7364)

**Comment by Vince-Chenal** [comment]
I just tested again and I was able to filter out generators outputs. I only tested on `list` and `matrix` generators though:

filtering `list` generator output:
```yaml
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
            - foo: bar
        - list:
            elements:
              - bar: foo
          selector:
            matchExpressions:
              - key: bar
                operator: In
                values:
                  - notfoo
```
--> matrix returns nothing

filtering `matrix` generator output:
```yaml
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
            - foo: bar
        - list:
            elements:
              - bar: foo
    selector:
      matchExpressions:
        - key: bar
          operator: In
          values:
            - foo
```
--> matrix returns only one app

If not doing it already, I encourage you to test rendering using `argocd appset generate appset.yml` command


```shell
> argocd version
argocd: v2.13.2+dc43124
  BuildDate: 2024-12-11T19:01:33Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.22.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.2+dc43124
  BuildDate: 2024-12-11T18:37:15Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Comment by rajatgupta828** [comment]
@Vince-Chenal  - It works fine with list generators, but the point where I am getting confused here is : 

In git generators, if we want to skip a application in a certain cluster(which is being generated by list generator), where should I specify around the directory to be skipped for a certain cluster.

To be specific, I have multiple clusters in list generator : 

```
           - list:
              elements:
              - cluster: kind
                url: https://kubernetes.default.svc
              - cluster: kind2
                url: https://10.1.1.100
```

and I have a git generator : 

```
            - git:
              repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
              revision: HEAD
              directories:
                - path: "application-sets/appsets-dir/addons/*"
            selector:
              matchExpressions:
                - key: skip
                  operator: NotIn
                  values:
                    - "true"
```

under application-sets/appsets-dir/addons/addons/* directory I may have multiple applications , such as nginx, fluent-bit etc 
I want to skip nginx only for kind cluster , not kind2 cluster.

Is there a way , I can specify this in a file (or any other way) where I can tell do not install nginx in kind2 cluster ?

**Comment by Vince-Chenal** [comment]
In fact you are using the [Git directories generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#git-generator-directories) and not [Git files generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#git-generator-files). I don't think the directories one is parsing any files.

So you would need to use the Git files generator with something like: 

```
- git:
    repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
    revision: HEAD
    files:
      - path: "application-sets/appsets-dir/addons/*/values.yaml"
```

But even with that you would get something like this for nginx:

```
- cluster: kind
  url: https://kubernetes.default.svc
  path: application-sets/appsets-dir/addons/nginx/values.yaml
  skip: true
- cluster: kind2
  url: https://10.1.1.100
  path: application-sets/appsets-dir/addons/nginx/values.yaml
  skip: true
```
Each nginx instantiation gets the `skip: true` and I'm not sure you can add more expressions in `matchExpressions` field to match the behavior you want.

Instead, you could create an arborescence like:
```
application-sets/appsets-dir/addons/nginx/kind1/values.yaml
application-sets/appsets-dir/addons/nginx/kind2/values.yaml
application-sets/appsets-dir/addons/.../.../values.yaml
```

This way you would be able to:
- discover all apps that need to be created by using a git file generator with path: `application-sets/appsets-dir/addons/*/*/values.yaml`
-  skip from within the `values.yaml` by setting `skip : "true"` (+ appropriate post selector expression on top matrix generator)

**Comment by rajatgupta828** [comment]
This although works : 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
              revision: HEAD
              directories:
                - path: "application-sets/appsets-dir/addons/*"
          - list:
              elements:
              - cluster: kind
                url: https://kubernetes.default.svc
                allowedAddons: "nginx"
      selector:
        matchLabels:
          allowedAddons: "nginx"
  template:
    metadata:
      name: '{{.path.basename}}-{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - base-values.yaml
            - '{{.cluster}}-values.yaml'
      destination:
        namespace: "{{.path.basename}}"
        server: '{{.url}}'
```

But now I am looking to match multiple allowedAddons , but it doesn't work - 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
              revision: HEAD
              directories:
                - path: "application-sets/appsets-dir/addons/*"
          - list:
              elements:
              - cluster: kind
                url: https://kubernetes.default.svc
                allowedAddons: ["nginx"]
      selector:
        matchExpressions:
          key: "allowedAddons"
          operator: In
          values: ["{{ .path.basename }}"]
  template:
    metadata:
      name: '{{.path.basename}}-{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:rajatgupta828-stem/federated-argocd-test.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - base-values.yaml
            - '{{.cluster}}-values.yaml'
      destination:
        namespace: "{{.path.basename}}"
        server: '{{.url}}'
```

Any idea if it is due to passing varaibles between generators / templates ?
