### ISSUE TITLE
ArgoCD UI - Team Members not able to view the repository 

### ISSUE THREAD

**Issue by tppalani** [argoproj/argo-cd#16141]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

1. I'm part of admin - managing and maintain the argocd as platform engineer. 
2. I have created two projects project-application-initializer-devteam-a and application-initializer-devteam-b via yaml files
3. Note Yaml file are applied inside the EKS cluster.
4.  Once the yaml file applied successfully i can able to see the application projects from argocd home page with healthy status.
5. Argocd - settings - i can able to see the repository details its based on my yaml file without any issue, please find the attached screenshots.
![image](https://github.com/argoproj/argo-cd/assets/6921037/02f7d809-bf3c-49fe-9aff-cffa11a5452c)

6. As a admin i can able to view all the projects from argocd UI page.
7. But when we are talking about development team they are not suppose view all the application right, so i have configured argocd rbac, so that they can able to view only their application project, just consider i'm from team-a i can able to see only team-a project, refer the screenshot  
![image](https://github.com/argoproj/argo-cd/assets/6921037/15195780-9793-4596-8c19-59918b8327a8)
8. As a devteam-a when they're checking arogcd - setting - repository - they are not able to view repository connection details, refer the screenshot 
![image](https://github.com/argoproj/argo-cd/assets/6921037/432a7dd1-f671-460c-b83e-2cc3320c8d92)

**To Reproduce**

**Expected behavior**

Respective team should able to view their repository details under the argocd UI Page.

**Screenshots**

**v2.6.2+6e02f8b**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
Repository read access is controlled by RBAC rules: https://argo-cd.readthedocs.io/en/latest/operator-manual/rbac/

You can either explicitly grant your dev teams repository read access via argocd-rbac-cm or by using project-scoped repositories: https://argo-cd.readthedocs.io/en/latest/user-guide/projects/#project-scoped-repositories-and-clusters

**Comment by tppalani** [comment]
Hi @crenshaw-dev 

Can you pls help how to add repo read access, here is the my config map

`apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, ARGOCD-USER-TEAM-B, role:devteam-b
    p, role:devteam-b, applications, get, devteam-b/*, allow
    p, role:devteam-b, applications, sync, devteam-b/*, allow
    p, role:devteam-b, projects, get, devteam-b, allow

    g, ARGOCD-USER-TEAM-A, role:devteam-a
    p, role:devteam-a, applications, get, devteam-a/*, allow
    p, role:devteam-a, applications, sync, devteam-a/*, allow
    p, role:devteam-a, projects, get, devteam-a, allow

    g, ARGOCD-ADMIN, role:admin
    g, ARGOCD-RO, role:readonly
  scopes: '[email, profile, filteredgroups]'
`

**Comment by crenshaw-dev** [comment]
```diff
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, ARGOCD-USER-TEAM-B, role:devteam-b
+   # To grant access to project-scoped repositories
+   p, role:devteam-b, applications, get, devteam-b/*, allow
+   # To grant access to all repositories
+   p, role:devteam-b, applications, get, *, allow
    p, role:devteam-b, applications, get, devteam-b/*, allow
    p, role:devteam-b, applications, sync, devteam-b/*, allow
    p, role:devteam-b, projects, get, devteam-b, allow

    g, ARGOCD-USER-TEAM-A, role:devteam-a
    p, role:devteam-a, applications, get, devteam-a/*, allow
    p, role:devteam-a, applications, sync, devteam-a/*, allow
    p, role:devteam-a, projects, get, devteam-a, allow

    g, ARGOCD-ADMIN, role:admin
    g, ARGOCD-RO, role:readonly
  scopes: '[email, profile, filteredgroups]'
```

**Comment by tppalani** [comment]
Thanks lot for your help, please close the ticket.

**Comment by tppalani** [comment]
When i add below code, team-b can able to view all the repository which is belongs to other team as well.

```
p, role:devteam-b, repositories, get, *, allow
```

but when i add below code, nothing to to view it.

```
p, role:devteam-b, repositories, get, devteam-b/*, allow
```

**Comment by crenshaw-dev** [comment]
The repositories will only appear if they are scoped to the devteam-b project. Are the repos project-scoped?

**Comment by tppalani** [comment]
Hi @crenshaw-dev  Can you pls help me how to check repos are scoped to devteam-b or not ? do i need to changes any config map ?

**Comment by tppalani** [comment]
Hi @crenshaw-dev  can you pls guide me ?

**Comment by christianh814** [comment]
> When i add below code, team-b can able to view all the repository which is belongs to other team as well.
> 
> ```
> p, role:devteam-b, repositories, get, *, allow
> ```
> 
> but when i add below code, nothing to to view it.
> 
> ```
> p, role:devteam-b, repositories, get, devteam-b/*, allow
> ```

You'll need to set up an AppProject with the appropriate repo configuration 

see: https://argo-cd.readthedocs.io/en/stable/operator-manual/project-specification/

**Comment by tppalani** [comment]
HI @christianh814 

i have configured AppProject 

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devteam-a1
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Enable DevTeam-A1 Project to install new applications

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    # Any other repo are restricted
    - "*"

  destinations:
    - namespace: "devteam-a1"
      server: https://kubernetes.default.svc

  # Restrict Namespace cluster-scoped resources from being created
  clusterResourceBlacklist:
    - group: ""
      kind: "Namespace"

  # Restrict namespaced-scoped resources from being created
  namespaceResourceBlacklist:
    - group: "argoproj.io"
      kind: "AppProject"
    - group: "argoproj.io"
      kind: "Application"
    - group: ""
      kind: "ResourceQuota"
    - group: "networking.k8s.io"
      kind: "NetworkPolicy"

```

**Comment by crenshaw-dev** [comment]
@tppalani project-scoping a repository requires setting the `project` field in the repo secret. Instructions are here: https://argo-cd.readthedocs.io/en/latest/user-guide/projects/#project-scoped-repositories-and-clusters

**Comment by tppalani** [comment]
Hi @crenshaw-dev  Thanks for the help.

I have created below code changes, do i need change anything inside the argocd config map ?

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-devteam-b-projects
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  project: devteam-b
  name: argocd-devteam-b-projects
  url: https://github.com/tppalani/devteam-b.git
```
