### ISSUE TITLE
ServerSideApply fails to install kube-prometheus-stack

### ISSUE THREAD

**Issue by ninja-** [argoproj/argo-cd#16158]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Latest argocd version fails to install kube-prometheus-stack CRDs which used to work fine some time ago...

**To Reproduce**

Install manifest

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        prometheus-node-exporter:
           hostRootFsMount:
             enabled: false
        prometheusOperator:
           admissionWebhooks:
             failurePolicy: Ignore
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 52.1.0
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
#    - CreateNamespace=true
    - Validate=false
 ```
   

**Expected behavior**

**Screenshots**

**Version**

```shell
➜  ~ argocd version
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: could not get helm version: exec: "helm": executable file not found in $PATH
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0```

**Logs**


```
status:
  health:
    status: Missing
  operationState:
    finishedAt: "2023-10-30T18:57:26Z"
    message: 'one or more objects failed to apply, reason: unable to recognize "/dev/shm/3033025924":
      no matches for kind "Prometheus" in version "monitoring.coreos.com/v1",CustomResourceDefinition.apiextensions.k8s.io
      "prometheusagents.monitoring.coreos.com" is invalid: metadata.annotations: Too
      long: must have at most 262144 bytes,CustomResourceDefinition.apiextensions.k8s.io
      "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long:
      must have at most 262144 bytes'
    operation:
      initiatedBy: {}
      retry: {}
      sync:
        revision: 52.1.0
        syncOptions:
        - ServerSideApply=true
        - Validate=false
        syncStrategy:
          hook: {}
    phase: Failed
    startedAt: "2023-10-30T18:57:15Z"```
