### ISSUE TITLE
Helm chart with empty string as path does not work

### ISSUE THREAD

**Issue by gergaly** [argoproj/argo-cd#16179]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to deploy an application via a helm chart (https://github.com/twuni/docker-registry.helm). But the helm chart is located at the root of a repository. And seems like ArgoCD does not  accept `""` as a `path`. I've tried the source without `path` and with the following values:
```yaml
...
path: ""
path: ''
path:
path: "/"
path: nil
```
When I try to use `""`, the `path` is missing from the manifest (taken from the UI):
```yaml
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: registry
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
sources:
  - repoURL: 'https://github.com/twuni/docker-registry.helm'
    targetRevision: v2.2.2
    helm:
      releaseName: registry
```
**To Reproduce**
Use this application.yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/twuni/docker-registry.helm'
      path: ""
      targetRevision: v2.2.2
      helm:
        releaseName: registry
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: registry
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
```

**Expected behavior**

I'm expecting the chart located in the root of a repository to work. Or I expect the documentation to specify accepted values for `path`.

**Screenshots**

**Version**
Well I don't have the argocd executable, I didn't need it yet. I clicked the version string in the UI, I hope it is enough.
```json
{
    "Version": "v2.8.4+c279299",
    "BuildDate": "2023-09-13T19:12:09Z",
    "GitCommit": "c27929928104dc37b937764baf65f38b78930e59",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**
Error message from UI:
```
time="2023-10-31T13:33:12Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec for registry is invalid: InvalidSpecError: spec.source.repoURL and either source.path, source.chart, or source.ref are required for source {https://github.com/twuni/docker-registry.helm  v2.2.2 &ApplicationSourceHelm{ValueFiles:[$values-bertok/values/registry-values-bertok.yaml],Parameters:[]HelmParameter{},ReleaseName:registry,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,} nil nil nil  }" grpc.code=InvalidArgument grpc.method=UpdateSpec grpc.service=application.ApplicationService grpc.start_time="2023-10-31T13:33:07Z" grpc.time_ms=4966.616 span.kind=server system=grpc
```
