### ISSUE TITLE
Notification service '' is not supported

### ISSUE THREAD

**Issue by crhuber** [argoproj/argo-cd#16195]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have an argocd application with the following annotations for notifications

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.slack: some-channel
    notifications.argoproj.io/subscribe.on-sync-failed.slack: some-channel
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: some-channel
```

In the notification service configmap `argocd-notifications-cm` I have the slack notification service setup

```
k get cm argocd-notifications-cm -o yaml
apiVersion: v1
data:
  service.slack: |
    token: $slack-token
   ... 
```

* The slack account is already joined in the `some-channel` slack channel. 

* Also we have many applications with the same annotation and they are working fine. 

* However for 1 or 2 application we occasionally get this error message multiple times.

`Failed to notify recipient { some-channel} defined in resource argocd/some-app-prod: notification service '' is not supported`

**To Reproduce**

Configure app and notifications as shown above

**Expected behavior**

No error message

**Screenshots**

NA

**Version**

```shell
v2.8.4+c279299
```

**Logs**

```
Failed to notify recipient { some-channel} defined in resource argocd/some-app-prod: notification service '' is not supported
```

**Comment by guitarrapc** [comment]
I've met same issue on v2.9.3.

**Error message:**

```Failed to notify recipient { channel_name} defined in resource argocd/master: notification service '' is not supported
```

**Workaround:**

Investigated my settings and seems like it happen when `defaultTriggers` are exists. Issue disappears by following.

**BEFORE**

defaultTrigger is enabled when issue happens, and issue disappers by remove defaultTrigger related.
 
```yaml
# application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
-    notifications.argoproj.io/subscribe.slack: channel_name
+    notifications.argoproj.io/subscribe.on-deployed.slack: channel_name
+    notifications.argoproj.io/subscribe.on-health-degraded.slack: channel_name
+    notifications.argoproj.io/subscribe.on-sync-failed.slack: channel_name
---
# argocd-notification-cm
apiVersion: v1
kind: ConfigMap
data:
-  defaultTriggers: |
-    - on-deployed
-    - on-health-degraded
-    - on-sync-failed
-    - on-sync-running
```

**Comment by aokomorowski** [comment]
My wild guess (I did not investigate this, but it would make sense) is `defaultTriggers` requires defaultSubscription to be configured as well (see [this piece of documentation](https://argocd-notifications.readthedocs.io/en/stable/subscriptions/#default-subscriptions))

**Comment by crhuber** [comment]
Just following up here  but we already had default triggers setup. Here is the CM

```yaml
apiVersion: v1
data:
  defaultTriggers: |
    - on-sync-status-unknown
  service.slack: |
    token: $slack-token
  subscriptions: |
    - recipients:
      - slack:argocd-notifications
      triggers:
      - on-sync-status-unknown
      - on-health-degraded
      - on-sync-failed
      - on-sync-status-unknown
```


> My wild guess (I did not investigate this, but it would make sense) is `defaultTriggers` requires defaultSubscription to be configured as well (see [this piece of documentation](https://argocd-notifications.readthedocs.io/en/stable/subscriptions/#default-subscriptions))

**Comment by toini** [comment]
@crhuber did you figure out this one? We have default triggers configured and see the same errors in logs. Adding default subscriptions like in your example above doesn't seem to help.

**Comment by crhuber** [comment]
Removing defaultTriggers fixed it for me: 
So , something like this:
```
apiVersion: v1
data:
  service.slack: |
    token: $slack-token
  subscriptions: |
    - recipients:
      - slack:argocd-notifications
      triggers:
      - on-sync-status-unknown
      - on-health-degraded
      - on-sync-failed
      - on-sync-status-unknown
```
