### ISSUE TITLE
resource.exclusion with namespace as criteria

### ISSUE THREAD

**Issue by vstoppe** [argoproj/argo-cd#16196]
# Summary

ArgoCD can not be configured differentiated enough, to ignore certain resource types in one namespace but generate them in an other namespace. I want to be able to ignore a resource type in one namespace but process it in another namespace, to be able to deploy all software in ArgoCD I need, by just one ArgoCD.

# Motivation

I can configure a resource exclusion in the argo-cm in the following way:

```yaml
resource.exclusions
- apiGroups:
  - "rbac.authorization.k8s.io"
  kinds:
  - "ClusterRoleBinding"        
  clusters:
  - https://my-cluster-address
```

I have to do this to avoid out-of-sync warnings for a clusterRoleBinding which is generated by the strimzi-operaotr when creating a strimzi-kafka-cluster. When I want to deploy another application (here stakater/releader) which generates a clusterRoleBinding I stuck with the message:

```
ExcludedResourceWarning Resource rbac.authorization.k8s.io/ClusterRoleBinding reloader-role-binding is excluded in the settings
```

# Proposal

## Add namespaces for resource.exclusion like

```yaml
resource.exclusions
- apiGroups:
  - "rbac.authorization.k8s.io"
  kinds:
  - "ClusterRoleBinding"        
  clusters:
  - https://my-cluster-address
  namespaces:
  - my-strimzi-namespace
```

## or make it configureable in an ArgoCD application

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  resourceExclusion:
  - apiGroups:
    - "rbac.authorization.k8s.io"
    kinds:
    - "ClusterRoleBinding"        
```

**Comment by thikade** [comment]
A very useful suggestion! 
We also need this and would prefer to make it configurable on application and/or project level!

**Comment by clement94310** [comment]
yes i need this too

**Comment by tjouffroy** [comment]
A workaround can be to filter namespace view on the project side

**Comment by SayakMukhopadhyay** [comment]
In #8662 , the devs have already ruled out on an application level "inclusion" of excluded resources. I still think that it would be a nice thing to have and the worst that could happen is the secret(s) of that particular application leaking via git and I don't think it would affect other applications.

**Comment by crenshaw-dev** [comment]
Can folks comment with details about their use cases? Sounds like OP's use case might be solveable with ignoreDifferences instead of resource exclusions.

The implementation of `resource.exclusions` is currently super simple. If we added namespaces, it would get complicated. Instead of skipping lists/watches on entire kinds, we'd have to either set up a global list/watch and then filter or set up namespaced watches. They have different tradeoffs. If the use cases could be satisfied by other existing mechanisms, we may be able to avoid that complexity.

**Comment by SayakMukhopadhyay** [comment]
I have 2 use cases, 1 mentioned in #8662 . The other use case involves `external-secrets`. It's Helm chart [provides an empty secret](https://github.com/external-secrets/external-secrets/blob/25f760633306b2316eeae5e046e9391330af11ea/deploy/charts/external-secrets/templates/webhook-secret.yaml) which gets populated by TLS certs by the operator itself.

Since I have all secrets excluded, this secret is not deployed using the Helm chart, rather I use an External Secret resource to generare an "empty" secret. I would have preferred to deploy only this empty secret using Argo itself since the contents of that secret is not managed in GitOps.

**Comment by oivindoh** [comment]
I have an application that uses Endpoints to provide a service and ingress for an external service with no dns entries associated.

In v3 Argo excludes endpoints by default:

```
  resource.exclusions: |
    ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
    - apiGroups:
      - ''
      - discovery.k8s.io
      kinds:
      - Endpoints
      - EndpointSlice
```

And I agree this is a good change in general, but sometimes you still want to create endpoints manually, so the ability to selectively re-enable this (or any other resource) would be useful.
