### ISSUE TITLE
LogoutURL in oidc.config supports the `$secret.key` syntax only partially

### ISSUE THREAD

**Issue by pre** [argoproj/argo-cd#16204]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `oidc.config` in `argocd-cm` allows authenticating with OIDC without Dex. The configuration syntax involves placeholders such as the following:

```yaml 
oidc.config: |
    name: IAS
    # Reads "url" from Secret/my-secret
    issuer: $my-secret:url
    clientID: $my-secret:clientid
    clientSecret: $my-secret:clientsecret
   
    # Replacement works here: 
    logoutURL: $my-secret:url     # this works 

    # Replacement does not work here: 
    # logoutURL: $mysecret:url/anything
```

For `logoutURL` the `$mysecret.key` syntax works only partially. 

The placeholder is replaced when it's only the placeholder:  `logoutURL: $my-secret:url` 

But the logout url will also need a path so that the full URL would be 

`$my-secret:url/something?token={{token}}&post_logout_redirect_url={{logoutRedirectURL}}/login` 

If the `$my-secret:url` is appended with any value, the substitution no longer works. 

There should be a way to tell ArgoCD that `$my-secret:url ends here` and `/something?token.. starts here`. 

I didn't find such a mechanism from the code  [
](https://github.com/argoproj/argo-cd/blob/26264b87d063720e1665e5caaf2f0a6b09cb3532/server/logout/logout.go#L123) and trying out variations of `{{$my-secret:url}}/something` and such did not produce results. 

**Expected behavior**

The URL part of the logout url should be retrievable from the Secret in the same way as `issuer` and `clientID`.

Motivation: We have multiple clusters and the URL is different in each cluster. We already generate the `Secret` dynamically, and it has the correct URL for the logout end point. We just can't use dynamically provide ArgoCD with this URL.

**Version**

ArgoCD 2.8.3
