### ISSUE TITLE
Cluster generator parameters not substituted

### ISSUE THREAD

**Issue by antwacky** [argoproj/argo-cd#16206]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using the below ArgoCD ApplicationSet manifest does not substitute the cluster `metadata.labels.environment` (which definitely exists in the secret for the local cluster).

I created a secret for the local cluster so I could add a label to be used in the application template:

```
apiVersion: v1
data:
  config: blahblahblah==
  name: blahblah==
  server: blahblahblah
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-11-01T11:56:52Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/secret-type: cluster
    environment: local
  name: cluster-local
  namespace: argocd
  resourceVersion: "156256"
  uid: 458f2ec1-fdfe-47a3-8e82-c55328080eca
type: Opaque
```

I've also tried `name` which again does not get substituted.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
  namespace: default
spec:
  generators:
    - clusters: {}
    - list:
        elements:
          - appName: example
            namespace: default
            repoURL: https://gitlab.com/example.git
            path: helm/charts
            targetRevision: main
  template:
    metadata:
      name: "{{ appName }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      sources:
        - repoURL: "{{ repoURL }}"
          targetRevision: "{{ targetRevision }}"
          path: "{{ path }}"
          helm:
            releaseName: "{{ appName }}"
            # values in order of precendence
            valueFiles:
              - "$values/argocd/values/global.yml" # global values
              - "$values/argocd/values/{{ metadata.labels.environment }}.yml" # per environment, cross application values
              - "$values/argocd/apps/{{ appName }}/values.yml" # per app, cross environment values
              - "$values/argocd/apps/{{ appName }}/{{ metadata.labels.environment }}-values.yml" # per app, per environment values
        - repoURL: https://gitlab.example.com/example.git
          targetRevision: "{{ targetRevision }}"
          ref: values
      destination:
        name: in-cluster
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
```

**To Reproduce**

Apply the given manifest.

**Expected behavior**

I expected the `manifest.labels.environment` parameter to be substituted.

**Version**

```shell
argocd: v2.8.6+113b538
  BuildDate: 2023-10-31T14:18:21Z
  GitCommit: 113b53859dbf01cee7f1abac255cb112ad30bd8b
  GitTreeState: clean
  GoVersion: go1.20.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

This error is from the UI when you click on the app `Error`, it shows that `{{ metadata.labels.environment }}` has not been substituted.

```
Error: open <path to cached source>/argocd/values/{{ metadata.labels.environment }}.yml: no such file or directory
```

**Comment by crenshaw-dev** [comment]
You've specified two generators (cluster and list), but only the first one produces the `metadata.labels.environment` parameter.

**Comment by antwacky** [comment]
Thanks for the reply!

Excuse my ignorance, how should I proceed?

**Comment by antwacky** [comment]
Matrix generator such as the below works. 

```
spec:
  generators:
    matrix:
      generators:
        - clusters: {}
        - list:
```
