### ISSUE TITLE
[Proposal] Custom AppSet generator - Schedules generator 

### ISSUE THREAD

**Issue by Aym3nTN** [argoproj/argo-cd#16215]
# Summary

I'm suggesting to create an AppSet generator to un-apply/delete an Application using Cron expressions.

# Motivation

My motivation is about cost savings, in my case, I have multiple applications that each uses an Ingress that is responsible for creating an AWS ALB (using AWS ALB Controller plugin) and alb costs money; therefore I'd like to automate shutting down my dev/stg environment when not needed like weekends or after work hours. 

What do you think about that? The idea is similar to KubeGreen but acts on Argo Application resource level rather than Deployments resources.

**Comment by crenshaw-dev** [comment]
I think it's a cool idea. What would be the syntax?

You could probably do it today with a plugin. Pass the plugin some unique key (app name maybe) and a cron schedule, have the plugin pass back the unique key and a `shutdown: true/false`. Merge the plugin output with your other generators', and filter on the `shutdown` param.

**Comment by Aym3nTN** [comment]
Won't that require having my plugin's code deployed somewhere? I believe that would fit better in the applicationset_controller code base.

It can look something like that, we can adjust afterward:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - schedules:
      weekdays: ["weekends", "Saturday', ...]
      workdays: "18:00-08:00"
      timezone: "UTC+1"
```
