### ISSUE TITLE
Add option to ignore pull requests in draft state to ApplicationSet

### ISSUE THREAD

**Issue by ymktmk** [argoproj/argo-cd#16219]
# Summary
Add ignoreDraft option to ApplicationSet and pull request in draft state I want to ignore

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - pullRequest:
      filters:
      - branchMatch: ".*-argocd"
      - ignoreDraft: true
  template:
  # ...
```

# Motivation
Argo CD Pull Request Generator automatically discovers open pull requests in your repository. This also includes Draft pull requests, so some people may end up creating unnecessary Argo CD Applications. Therefore, I would like to create an ignoreDraft option to be able to exclude it arbitrarily.

**Comment by mrharpo** [comment]
👍 Yes, this would be helpful for our workflows as well!

**Comment by mgerhardy** [comment]
https://github.com/mgerhardy/argo-cd/tree/pr/16219 - not yet an MR - as this is not discusses anywhere yet (afaik)

**Comment by HarnageaGabriel** [comment]
I'd like to pick this up. Proposed approach:

Add an `IgnoreDraft` boolean field on the Pull Request generator's filter spec (`PullRequestGeneratorFilter` in `pkg/apis/applicationset/v1alpha1/applicationsetgenerator_types.go`), mirroring how `branchMatch`/`labelMatch` are already exposed there:

```yaml
generators:
- pullRequest:
    filters:
    - branchMatch: ".*-argocd"
    ignoreDraft: true
```

Implementation-wise:
- Extend the `PullRequestGeneratorFilter` struct with `IgnoreDraft *bool`.
- Plumb a `Draft` field onto the generic `PullRequestSCM.PullRequest` struct returned by each SCM provider (`applicationset/services/scm_provider/`), so `applicationset/generators/pull_request.go` can filter on it generically instead of per-provider.
- Populate `Draft` in the GitHub and GitLab provider implementations (both APIs expose draft/WIP status natively); other providers (Gitea, Bitbucket, Azure DevOps) can leave it `false`/unsupported for now unless their APIs support it too.
- Add unit tests per provider plus a generator-level filter test, and doc updates in `docs/operator-manual/applicationset/Generators-Pull-Request.md`.

Will open a PR referencing this issue once implemented. Flagging here first since @mgerhardy mentioned an unpublished branch and this hasn't been discussed with maintainers yet — happy to defer or collaborate if you're actively working on it too.
