### ISSUE TITLE
Argocd CMP plugin is not designed to work nicely with other tools (such as helm)

### ISSUE THREAD

**Issue by borisovano** [argoproj/argo-cd#16252]
# Summary
Allow CMP plugin to Plug-In to the flow together with other tools, instead of trying augment them with complicated CLI commands.

| Argocd checkout repo | ----> | Argocd helm tool | ----> | Argocd CMP plugin | -----> | Diff | ----> | Sync | 

# Motivation

Currently CMP plugin is not designed to Plug-In to the flow together with other tools, instead it tries to augment them.

I'll bring vault plugin as example.

I'd like to use vault-plugin - meaning to dynamically fetch the secrets on Sync.
Instead of chaining the plugin to the output of helm tool which is minimal and elegant. The user is required to implement all the helm heavy lifting by himself.

So instead of using the output of helm tool we need to use on of the following:
Default: https://argocd-vault-plugin.readthedocs.io/en/stable/installation/#initcontainer-and-configuration-via-sidecar
Helm Simple: https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-additional-helm-arguments
Helm with arguments: https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-additional-helm-arguments
Helm with inline values: https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-an-inline-values-file

(PS - it's not clear from the docs where to use which direction)

Some of the directions above have security risks, others prone to errors and none allows me to keep my application as is. 
So instead of current implementation, the application is as follows:

```
project: myproj
source:
  repoURL: 'https://gitlab.com/myrepo'
  path: local-charts/mychart
  targetRevision: HEAD
  helm:
    valueFiles:
      - ../../services/myservice/myapp/values.yaml
      - >-
        ../../services/myservice/myapp/env/myenv/values.yaml
```
The user required to use something like this:
```
  source:
    path: your-app
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            # non-vault helm values are specified normally
            someValue: lasldkfjlksa
            moreStuff:
              - a
              - b
              - c

```
# Proposal
CMP plugin should get the **helm tool output** and return valid manifests
```
project: myproj
source:
  repoURL: 'https://gitlab.com/myrepo'
  path: local-charts/mychart
  targetRevision: HEAD
  helm:
    valueFiles:
      - ../../services/myservice/myapp/values.yaml
      - >-
        ../../services/myservice/myapp/env/myenv/values.yaml
   plugin: 
      name: argo-vault-plugin
      after: helm
 ```

**Comment by borisovano** [comment]
Looks like someone picked up the gauntlet: https://github.com/crumbhole/argocd-lovely-plugin 💪

**Comment by reggie-k** [comment]
Can https://github.com/crumbhole/argocd-lovely-plugin help?

**Comment by Roysav** [comment]
We are dealing with similar problems with CMP and would also like a cleaner way to integrate plugins into the rendering flow without re-implementing Helm.

I'd like to propose a slightly different model that uses a **middleware pipeline**, allowing us to chain any number of plugins after the initial rendering step (via Helm in this example), instead of the proposed `plugin.after` syntax.
```yaml
source:
  repoURL: https://github.com/myrepo.git
  path: local-charts/mychart
  targetRevision: HEAD
  helm:
    valueFiles:
      - ../../services/myservice/myapp/values.yaml
      - >-
        ../../services/myservice/myapp/env/myenv/values.yaml
  middleware: 
    - plugin:
         name: argocd-vault-plugin
    - plugin:
         name: another-plugin
```
