### ISSUE TITLE
project restrictions monitoring  - api restriction

### ISSUE THREAD

**Issue by anwoolterton** [argoproj/argo-cd#16259]
# Summary

When there are failures due to restrictions on api projects

example project which blocks everything

Project
```
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: foo
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: foo
  sourceRepos:
    - '*'
```

Application Sync Status
```
    syncResult:
      resources:
        - group: ''
          kind: Secret
          message: resource :Secret is not permitted in project foo
          name: test-secret
          namespace: test-namespace
          status: SyncFailed
          syncPhase: Sync
          version: v1
```

# Motivation

When there are failures metrics or logs should be created. looking at stdout and metrics server for argocd pod this is not logged or a metric is not created other than a generic failure not specific to api restrictions.

# Proposal

This information would be useful for troubleshooting / alerting on when using monitoring platforms such as splunk / datadog / etc .
