### ISSUE TITLE
External secrets values are not replaced in webhook settings

### ISSUE THREAD

**Issue by MrFreezeex** [argoproj/argo-cd#16261]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

You can't reference other secrets in all the webhook settings with the the syntax $<secretName>:<key>.

**To Reproduce**

Have something like that:
```
apiVersion: v1
kind: Secret
stringData:
  webhook.github.secret: "mysecrethere"
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-helm-values
  namespace: argocd
type: Opaque
```

And set "webhook.github.secret" in "argocd-secret" to "$argocd-helm-values:webhook.github.secret". The value will not be replaced and you can check that by configuring the webhook with litterally "$argocd-helm-values:webhook.github.secret" (while any other value will not work meaning that the secret is not correctly replaced).

**Expected behavior**

The secret to be replaced

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
