### ISSUE TITLE
argocd applicationset-controller 2.9.0 toYaml function not defined

### ISSUE THREAD

**Issue by sdomula** [argoproj/argo-cd#16280]
**Describe the bug**

When using the new `toYaml` function with argocd 2.9.0 in an applicationset to include the values for a helm chart argocd-applicationset-controller logs an error that `toYaml` is not defined.

**To Reproduce**

I applied the following argocd appliationset (I removed sensitive information):
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
    ...
  template:
    metadata:
      name: 'myset.{{ index .path.segments 1 }}'
    spec:
      project:  'myproject'
      source:
       ....
        helm:
          releaseName: 'myrelease'
          values: |
            {{ toYaml | .values }}
```

I am using the git generator and have, e.g., the following config file for the application set:

```
metadata:
  argoCDProject: infra
  repoURL:  https://github.com/lovoo/operators
  branch: develop
  chartPath: cert-manager/deploy/charts/cert-manager
values:
  key: value
  nested:
    anotherKey: value
```

**Expected behavior**

It should create an appliation where it sets the values in the following way:
```yaml
...
helm:
  releaseName: 'myrelease'
  values: |
    key: value
    nested:
      anotherKey: value
```

**Version**

```shell
argocd: v2.9.0+9cf0c69.dirty
  BuildDate: 2023-11-06T15:13:36Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: dirty
  GoVersion: go1.21.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.9.0+9cf0c69
  BuildDate: 2023-11-06T04:43:50Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
{"error":"failed to parse template {{ .values | toYaml }}\n: template: :1: function 
\"toYaml\" not defined", ...}
```
