### ISSUE TITLE
Application/ApplicationSet: add support for templated helm value files

### ISSUE THREAD

**Issue by theblop** [argoproj/argo-cd#16302]
# Summary

# Motivation

One annoying thing with helm values in values files is that they can't refer to other helm values.

With ApplicationSets it's possible to template them if defined inline in spec.template.helm.values, but that implies all applications use the same values template.

I suggest adding the possibility to use go-templated values files in Application definition (e.g. `spec.template.helm.valueFilesTemplates`) that would support this.

# Proposal

Possible implementation with a `valueFilesTemplates`  helm option in the Application definition:

*ApplicationSet (partial):*
```
kind: ApplicationSet
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://example.com
          files:
            - path: "apps/*.yaml"
      - list:
          elements:
            - domainname: example1.com
            - domainname: example2.com

  goTemplate: true
  template:
    metadata:
      name: {{ .appname }}
    spec:
      project: myproject
      sources:
        - repoURL: https://example.com
          path: app/{{ .appname }}
          helm:
            valueFilesTemplates:
              - app/{{ .appname }}/values.yaml.gotmpl
```

*Files in git repo:*

apps/app01.yaml:
```
appname: myapp
hostname: foo
```
app/app01/values.yaml.gotmpl:
```
ingress:
  tls:
    - hosts:
      - '{{ .hostname }}.{{ .domainname }}'
  hosts:
    - '{{ .hostname }}.{{ .domainname }}'
```

**Comment by crenshaw-dev** [comment]
Isn't it possible in Helm for one values file to template values from another values file?

**Comment by theblop** [comment]
> Isn't it possible in Helm for one values file to template values from another values file?

Sadly not and yaml anchor/reference tricks can't replace a value mid-text. Only `helmfile` supports templating values (https://helmfile.readthedocs.io/en/latest/#values-files-templates) and this is what I currently use as an Argo plugin, but it has a lot of limitations compared to what the native argo `helm` source supports (plugins don't support multi-sources values for a start, I would have to re-implement that inside the plugin).

It would be nice to have that functionality in argo (getting the template from a generator)

**Comment by diversario** [comment]
```
          helm:
            valueFilesTemplates:
              - app/{{ .appname }}/values.yaml.gotmpl
```

would be fantastic. Sometimes values files are huge blobs of text that contain one dynamic string (e.g. the cluster name), and currently it's just impossible to avoid massive amounts of copypaste because the entire values file has to be duplicated for every cluster.

```
            values: |
              {{ .values_string_from_generator | tpl | nindent 14 }}
```

is also nice.

**Comment by theblop** [comment]
@crenshaw-dev as a quick and hopefully not too complex implementation, do you think it would be relatively easy to just add the same `tpl` function as in helm in the Argo gotemplate syntax used in ApplicationSets?

That would allow me to get rid of the `helmfile` plugin I'm currently using to implement templating of helm values :)

**Comment by chary1112004** [comment]
Currently, to work around we need call nested application and then start using tpl. We expect no need calling to nested application to generate value

first application call to nested application and nested application is as below:
```
apiVersion: argoproj.io/v1alpha1
kind: Application

spec:
  # The project the application belongs to.
  project: bootstrap

  # Source of the application manifests
  source:
    repoURL: <repo>
    targetRevision: <tag>
    path: test
    helm:
      values: |-
        common:
        {{ tpl (.Values.common | toYaml) . | nindent 10 }}
```

**Comment by luhahn** [comment]
This really would be a great feature for argocd

**Comment by bingkunyangvungle** [comment]
Any updates on this one? It can provide so much flexibility for rendering.

**Comment by dudo** [comment]
This is exactly what I'm looking for to help manage addons in my clusters. I can currently have individual ApplicationSets for each addon, since I often need to reference the cluster name within the values file, and can only achieve that via the inline helm block.

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-kyverno
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'kyverno-{{.name}}'
      labels:
        argocd.argoproj.io/type: helm
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: kyverno
          targetRevision: 3.3.3
          repoURL: https://kyverno.github.io/kyverno/
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/app-of-apps/addons/helm-charts/kyverno/values.yaml'
              - '$values/app-of-apps/addons/helm-charts/kyverno/{{ index .metadata.labels "kubernetes.io/environment" }}.values.yaml'
            valuesObject: {}
        - repoURL: https://github.com/gitops-ci-cd/argo-config
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{.name}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
```

It'd be simply lovely to be able to have a single ApplicationSet with a matrix generator. Feels like a perfect fit!

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-helm
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - repository: https://charts.crossplane.io/stable
                  chart: crossplane
                  version: 1.18.1
                - repository: https://kyverno.github.io/kyverno/
                  chart: kyverno
                  version: 3.3.3
          - clusters: {}
  template:
    metadata:
      name: '{{ .chart }}-{{ .name }}'
      labels:
        argocd.argoproj.io/type: helm
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: '{{ .chart }}'
          targetRevision: '{{ .version }}'
          repoURL: '{{ .repository }}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:  # treating these as templates, per OP's suggestion
              - '$values/app-of-apps/addons/helm-charts/{{ .chart }}/values.yaml'
              - '$values/app-of-apps/addons/helm-charts/{{ .chart }}/{{ index .metadata.labels "kubernetes.io/environment" }}.values.yaml'
            valuesObject: {}
        - repoURL: https://github.com/gitops-ci-cd/argo-config
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{ .name }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
```

**Comment by kheraud** [comment]
We are facing the exact same use case than @dudo . It would be great to be able to use go templating in `valueFiles`.
Right now we need to add more complexity in the target `$values` repository to have a prerendering done before `ApplicationSet` can pull the values.
One drawback that I see is that some argo stacks out there may use `{{` in their existing values. Introducing templating feature would mess with it. An additional `enableValueFileTemplating` parameter could turn the feature one.

**Comment by YvesEarnix** [comment]
A possible workaround solution can be to use git generator as describe [here](https://github.com/argoproj/argo-cd/discussions/23903) ?

**Comment by dmosesson** [comment]
I seem to have the exact opposite project as in this ticket. All templates that I am passing in my helm values file  (or even in the chart) are getting evaluated, even when they are strings. Are people still having this issue, or did I somehow mess up my argo-cd config in the exact way that poeple are looking for (and I do not want)

**Comment by twobiers** [comment]
We have a similar use-case with kustomize where we want to create preview environments based on pull requests using ApplicationSets. On a Pull request we want to template the `kustomize` spec of the Application so we can inject e.g. the pull request number. That works quite good unless the template should be located in the source repository and used with a matrix generator (git / pull-request). 

As far as I'm concened, it would be enough to add an additional `tpl` templating function like helm has.
Our current workaround requires manual variable substitution with `regexReplaceAll`.

Assuming we would have a `guestbook/preview_configuration.yaml` file containing something like:
```yaml
kustomize:
  nameSuffix: -pr-{{ .number }}
```

It could be used like so:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-ephemeral-deployment
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/example/guestbook # The application repository
              revision: main
              files:
                - path: "guestbook/preview_configuration.yaml"
          - pullRequest:
              requeueAfterSeconds: 60
              github:
                owner: example
                repo: guestbook
                appSecretName: github-secret
                labels:
                  - preview
  template:
    metadata:
      name: "guestbook-ephemeral-deployment"
    spec:
      source:
        repoURL: https://github.com/example/gitops-example-repository
        targetRevision: "main"
        path: "apps/guestbook/base"
        kustomize:
          namespace: "guestbook"
      destination:
        name: "my-cluster"
        namespace: "guestbook"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      source:
        kustomize:
          {{- tpl .kustomize . | nindent 6 -}}
```
