### ISSUE TITLE
invaild error when deploying ConfigMap to helm chart with "argocd create" command

### ISSUE THREAD

**Issue by changhyuni** [argoproj/argo-cd#16319]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When running with argocd 2.4.0 version, it is normal, but when using 2.8.0 version, an error occurs.

**To Reproduce**
See the chart below


**Expected behavior**
```shell
 argocd app create tes --helm-chart cofigmap    
```
```yaml
overwrite:
  data:
     LIST_A: >-
       ["sss", "ddd", "ccc", "ddd"]
     LIST_B: >-
       host, host-test
```

this is template:
```yaml
{{- if (index .Values "test" "enabled") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml (index .Values "overwrite" "data") | indent 2 }}
{{- end }}
```

**Logs**

```
is invalid: patch: Invalid value: "map[data: metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"v1\",\"data\":\"\",\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"argocd.argoproj.io/instance\":\"test\"},\"name\":\"cm\",\"namespace\":\"kube-system\"}}\n]]]": cannot restore map from string
```
