### ISSUE TITLE
Unable to pass null as Helm value

### ISSUE THREAD

**Issue by bodgit** [argoproj/argo-cd#16312]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to pass a `null` as a Helm value to knock out a default chart value and ArgoCD seems to be stripping the value from the Application manifest.

The only bug I could find that seemed vaguely similar was #15566.

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
spec:
  project: cluster
  source:
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: 3.0.2
    chart: vpa
    helm:
      valuesObject:
        recommender:
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: null
              memory: 64Mi
```
Without setting the `recommender.resources.limits.cpu` value, it inherits the 200m value from the chart defaults, I don't want a CPU limit at all.

In the ArgoCD UI, there's no `recommender.resources.limits.cpu` key or value visible in the manifest. If I edit the manifest in the UI and add the key and `null` value in, it disappears from the manifest.

The desired manifest then shows the 200m value.

**Expected behavior**

`null` should be passed through to the underlying Helm chart.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/559268/edea241c-8e2e-451c-8219-6cd210b5a886)

**Version**

```shell
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
```

**Comment by Pionerd** [comment]
I think there has been a helm upgrade in one of the later versions of ArgoCD. There have been some recent changes around overriding values like this in helm. This may be a shot. I can override with `null` as you desire (v2.9.3), but then I run into https://github.com/argoproj/argo-cd/issues/15566.

**Comment by AnhQKatalon** [comment]
There is a PR https://github.com/helm/helm/pull/12879 to fix this bug on the Helm side, but it seems no one reviewed it. This bug is super annoying, and we cannot downgrade to the lower version above `2.9.1` to workaround

**Comment by ghostsquad** [comment]
ah helm... can't wait for the community to move to something like Jsonnet. Also, if you want you _can_ wrap helm in Jsonnet using Tanka. https://tanka.dev/helm/ then you can explicitly change whatever you want that helm doesn't support, or that a specific chart (via the values file) doesn't support.

**Comment by joshhklee** [comment]
@bodgit thank you for the thorough documentation and replication of the issue. I'm seeing this issue too and it seems like we'll have to ask for this bug fix on all of our Christmas lists and New Year's resolutions

**Comment by martijnvdp** [comment]
isnt this issue an argo issue as ArgoCD seems to be stripping the value from the Application manifest when providing inline values 
the helm issue mentioned is also specific for sub charts

**Comment by jennerm** [comment]
I've just hit this issue too.  It feels very similar to a problem I had with some other Helm templating I was doing, where I needed to merge maps and keep the null values.  In that scenario I had to start using the sprig `mergeOverwrite` function instead of the vanilla `merge`.
e.g:
```
{{ mergeOverwrite dict $defaults .Values.overwrites | toYaml }}
```
Where a key with a null value in the overwrites should be kept and should clobber a default value.

I imagine there is a lot of yaml manipulation going on in Argo, I wonder if one of their merges needs to use the same semantics as `mergeOverwrite` and ensure that nulls are kept.

**Comment by andrii-korotkov-verkada** [comment]
What are your argocd versions?

**Comment by jennerm** [comment]
I am using `argo-helm` chart version `7.6.5` which installs image `quay.io/argoproj/argocd:v2.12.4`

**Comment by de-mkolovic** [comment]
This behaviour also occurs when using `parameters` instead of `valuesObject`. Trying to use the value `null` results in the entire line being deleted.

It seems the only way to use the helm feature `null` to unset default values, is to use an external values file. However this forces you to use a multi-source app.

**Comment by thomas-biesmans** [comment]
FYI, per [link](https://github.com/argoproj/argo-cd/issues/19781), you can also use `values` with a block scalar instead of `valuesObject`, this also preserves the `null`. Like so:
```
values: |
  foo: bar
  footwo: null
```

**Comment by alekc** [comment]
Even if I am using values it still doesn't clear a nested single value, i.e. 
```
source:
    chart: cost-analyzer
    helm:
      values: |
        global:
          securityContext:
            fsGroup: null
```

Related Helm discussion about unsetting values https://github.com/helm/helm/pull/12162
