### ISSUE TITLE
enabling `applicationsSync: create-update` creates a permanent OutOfSync

### ISSUE THREAD

**Issue by FernandoMiguel** [argoproj/argo-cd#16324]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

we enabled `applicationsSync: create-update` in one applicationset, and then argo cd ui shows a permanent OutOfSync.
We tried to delete the applications and AppSet to let it recreate, but still same

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-deployments
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: "https://github.com/ORG/test.deployments.git"
                    revision: HEAD
                    directories:
                      - path: "*/*/*"
                      - path: "application-sets/*"
                        exclude: true
                - git:
                    repoURL: "https://github.com/ORG/test.deployments.git"
                    revision: HEAD
                    files:
                      - path: "{{ .path.path }}/values.yaml"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                matchExpressions:
                  - key: clustersgroup
                    operator: In
                    values:
                      - "{{if lt 0 (len .argo.clustersgroup)}}{{index .argo.clustersgroup 0}}{{else}}na{{end}}"
                      - "{{if lt 1 (len .argo.clustersgroup)}}{{index .argo.clustersgroup 1}}{{else}}na{{end}}"
  template:
    metadata:
      name: '{{ .nameNormalized }}-{{ index (splitList "/" .path.path) 0 }}-{{ index (splitList "/" .path.path) 1 }}-{{ .path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: deployments
      source:
        repoURL: "https://github.com/ORG/test.deployments.git"
        path: "{{ .path.path }}"
        targetRevision: HEAD
        helm:
          ignoreMissingValueFiles: true
          passCredentials: true
          valueFiles:
            - "./values.yaml"
      destination:
        name: "{{ .nameNormalized }}"
        namespace: '{{ index (splitList "/" .path.path) 0 }}-{{ index (splitList "/" .path.path) 1 }}-{{ .path.basename }}'
      syncPolicy:
        applicationsSync: create-update
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

**Expected behavior**

for argo to modify the appset and prevent the apps from being destroyed

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/168366/9b9ee67c-983b-416f-82c4-190f5deaa603)

**Version**

```json
{
    "Version": "v2.8.5+85025e1",
    "BuildDate": "2023-10-27T23:36:30Z",
    "GitCommit": "85025e1dcb683b192ea3599de0b0a196d64c94a7",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```
