### ISSUE TITLE
Enhancement proposal: Add velocity algorithms (linear, exponential, etc.) for canary rollout

### ISSUE THREAD

**Issue by Bennett-Lynch** [argoproj/argo-cd#16338]
# Summary

Add support for velocity algorithms (linear, exponential, etc.) for canary rollout, rather than requiring users to manually define steps.

# Motivation

Today if you want to simulate something like an exponential rollout with your canary, you must manually define the steps and weights yourself.

E.g., here is an exponential velocity based on `weight = 1.5849^step`

```
steps:
  - setWeight: 2
  - pause: { duration: 1m }
  - setWeight: 3
  - pause: { duration: 1m }
  - setWeight: 4
  - pause: { duration: 1m }
  - setWeight: 6
  - pause: { duration: 1m }
  - setWeight: 10
  - pause: { duration: 1m }
  - setWeight: 16
  - pause: { duration: 1m }
  - setWeight: 25
  - pause: { duration: 1m }
  - setWeight: 40
  - pause: { duration: 1m }
  - setWeight: 63
  - pause: { duration: 1m }
  - setWeight: 100
```

Or a simple linear velocity:

```
steps:
  - setWeight: 25
  - pause: { duration: 1m }
  - setWeight: 50
  - pause: { duration: 1m }
  - setWeight: 75
  - pause: { duration: 1m }
  - setWeight: 100
```

In both cases, you must define a number of manual steps, where the weights are simply derived from an algorithm. This is tedious and forces you to define more steps for the more granular you wish your increments to be. Furthermore, if you want to scale the overall rollout time, you need to reason about how many times you're pausing and update all of the pause parameters.

# Proposal

Offer support for various rollout velocities natively in the rollout spec.

E.g. the above exponential rollout simplified:

```
steps:
  - exponentialRampUp:
    totalDuration: 9m
```
_(the base of `1.5849` can be inferred from the desired total duration, with a default coefficient of `1`)_

And the linear rollout simplified:

```
steps:
  - linearRampUp:
    totalDuration: 3m
```

Other algorithms could also be supported, such as Fibonacci, etc.
