### ISSUE TITLE
ArgoCD with Okta (saml) having intermittent issues

### ISSUE THREAD

**Issue by SamVimes124** [argoproj/argo-cd#16332]
ArgoCD has been integrated with Okta via SAML and works _most_ of the time. The Okta login always works when opening a fresh browser or incognito. It fails ~25% of the time in testing when trying to log out and back in a normal browser. This can affect someone who's been logged out/timed out and needs to get back in. When it fails, it appears to pick another route for authentication using a bad path. 

**Describe the bug**

This is the error the end user sees ( replacing info with {WEBSITE_URL} )

`Failed to query provider "http://{WEBSITE_URL}//api/dex": 404 Not Found: 404 page not found`

The argocd logs show this. The double slash after the url is likely causing a problem, but I don't know where it's picking it up from.

`time="2023-11-13T23:05:49Z" level=info msg="Initializing OIDC provider (issuer: http://{WEBSITE_URL}//api/dex)"`

**To Reproduce**

The issue is caused when a user is logged out and tries to log back in using the same session. When it starts failing, without making any changes I can keep clicking the Okta login button until it eventually works. Here's what the logs look like for that.

**Logs**

```
time="2023-11-13T23:39:54Z" level=info msg="Initializing OIDC provider (issuer: {WEBSITE_URL}//api/dex)" 
time="2023-11-13T23:52:17Z" level=info msg="Performing authorization_code flow login: {WEBSITE_URL}/api/dex/auth?client_id=argo-cd&redirect_uri={WEBSITE_URL}%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=... {snip}"
time="2023-11-13T23:52:21Z" level=info msg="Web login successful. Claims:... {snip}
```

The error with "Initializing OIDC provider" can happen anywhere from 1 to 20 times before going back to successful login. Generally if the browser is closed and re-opened then that fixes the problem. However it has happened a few times that the issue is seen again when using the same browser, and using a different browser lets them log in.

This is the ArgoCD configuration:

```
  dex.config: |-
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: {OKTA_URL}/sso/saml 
        caData: |
          {CERT}
        redirectURI: {WEBSITE_URL}/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: group
  url: >-
    {WEBSITE_URL}
```

**Expected behavior**

The user should be able to log out and back in without issue. 

**Version**

```shell
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: windows/amd64
```
Using dex server version - dex:v2.37.0

The dex server logs don't show anything other than successful logins, and the same goes for the Okta logs. As a result I didn't post any of those (and since it's mostly personal info). So I'd like to understand what's happening here, at least to find a workaround when a user gets caught in this loop. Right now there isn't one that works consistently.
