### ISSUE TITLE
Source path must contain a `kustomization.yaml` when using `kustomize.patches`

### ISSUE THREAD

**Issue by morey-tech** [argoproj/argo-cd#16352]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
The [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#patches) state that:
> Patches are a way to kustomize resources using inline configurations in Argo CD applications. This allows for kustomizing **without** [a] kustomization file. 

However, when using the `kustomize.patches` field, the Application expects the `path` to contain a `kustomization.yaml` file. Without one, the sync will fail with the error `open <path to cached source>/<path>/kustomization.yaml: no such file or directory`.

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): failed to load kustomization.yaml: open <path to cached source>/guestbook/kustomization.yaml: no such file or directory
```

**To Reproduce**
Deploy the Application from the example in the docs:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-inline-guestbook
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD

## In-line Kustomize on plain Kubernetes manifests.
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: guestbook-ui
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/ports/0/containerPort
              value: 443
```

**Expected behavior**

The Application should ignore a missing `kustomization.yaml` file in the `path` when `kustomize.patches` is used. Or some equivalent (e.g. a toggle to allow missing).

**Screenshots**

![Xnapper-2023-11-15-14 19 54](https://github.com/argoproj/argo-cd/assets/4213435/335ff493-13b7-4553-8f5e-f91bd36c4ad1)

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
I think this is actually an enhancement request, i.e. automatically create kustomization.yaml for the user if `spec.source.kustomize` is populated and the file doesn't already exist.

**Comment by morey-tech** [comment]
Good point. The bug is the wording and example in the docs. The feature request is the expected behaviour. I'll put in a PR for the former.

**Comment by alexmt** [comment]
@morey-tech as I understand the use case is to allow users to apply last mile customization to **any** application (plain yaml, helm, plugin etc), correct? In this case Argo CD cannot just auto-create kustomization.yaml. E.g. app is helm-based then auto-creating kustomization.yaml would switch app to kustomize rendering and just break manifest generation. I think it is an entirely different feature. Argo CD would need to generate manifests first, then store result in e.g. `all.yaml` and leverage kustomize to apply patches on top. This would require a new field in the application spec:


```yaml
spec:
...
## The field definitely should not be kustomize, because kustomize holds "inputs" for kustomize based apps.
    overrides:
      patches:
        - target:
            kind: Deployment
            name: guestbook-ui
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/ports/0/containerPort
              value: 443
```
