### ISSUE TITLE
Sync option to GC old ConfigMaps & Secrets

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1636]
Spawned from: https://github.com/argoproj/argo-cd/issues/1629

It may be desirable for Argo CD to have GC controls on ConfigMaps/Secrets which are no longer referenced, to complement the feature in https://github.com/argoproj/argo-cd/issues/1629, which ignores "extra" resources in a namespace.

One proposal is to introduce a new sync option: --prune-unreferenced-config at the API and spec level:

The CLI to enable this command might be something like:
```
argocd app sync --prune-unreferenced-config
```

For declarative app specs which desire to have this happen automatically as part of auto-sync, the spec addition would be:
```yaml
spec:
  syncPolicy:
    automated:
      pruneUnreferencedConfig: true
```

The way pruneUnreferencedConfig would work is, when set to true:
1. Before performing sync, iterate all live configmaps/secrets which are part of the application which are candidates for pruning (i.e. no longer defined in git)
2. For each configmap/secret which is a pruning candidate, iterate all pods of the corresponding namespace. 
3. If any pod is referencing the configmap or secret, do not prune, otherwise proceed to perform pruning.

**Comment by jessesuen** [comment]
Need syntax to support all of the following cases during `argocd app sync`:

1. don't prune anything
2. don't prune anything except for **unreferenced** configs
3. prune everything except **referenced** configs
4. but prune everything no longer defined in git

**Comment by jessesuen** [comment]
Here is the proposed syntax. We would introduce a `syncOptions` feature to support this. The first option would be `ConfigGC=true|false`

1. don't prune any extra resources

CLI:
```
argocd app sync
```
Spec:
```yaml
spec:
  syncPolicy:
    automated: {}
```

2. don't prune any extra resources except for unreferenced configs

CLI:
```
argocd app sync -o ConfigGC=true
```
Spec:
```yaml
spec:
  syncPolicy:
    automated:
      syncOptions:
      - ConfigGC=true
```

3. prune all extra resources except for referenced configs

CLI:
```
argocd app sync --prune -o ConfigGC=false
```
Spec:
```yaml
spec:
  syncPolicy:
    automated:
      prune: true
      syncOptions:
      - ConfigGC=false
```

4. prune all extra resources

CLI:
```
argocd app sync --prune
```
Spec:
```yaml
spec:
  syncPolicy:
    automated:
      prune: true
```
