### ISSUE TITLE
Allow adding repo with public key from the GUI

### ISSUE THREAD

**Issue by reegnz** [argoproj/argo-cd#1638]
**Is your feature request related to a problem? Please describe.**
Currently I am deploying applications from a private git repository and I want to use ssh private keys for argocd to access the repo.
To configure the public key I have to:
* create a secret with the ssh private key for the repo access
* edit the argocd-cm configmap and add the repository by hand, referencing the configmap, like this:
```yaml
repositories:
- url: git@github.com:username/reponame.git
  sshPrivateKeySecret: username-reponame-gitkey
```

**Describe the solution you'd like**
I would like it to be an option on the GUI to configure a git repository that is accessed through ssh with a private key.

eg. a way of configuring a repo with ssh url and private key file instead of url and username/password.

**Describe alternatives you've considered**

Alternative is that I keep using kubectl to set up the secret and argocd config map.
