### ISSUE TITLE
OutOfSync when deployment has topologySpreadConstraints and resource limits 

### ISSUE THREAD

**Issue by imeliran** [argoproj/argo-cd#16400]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
We noticed that deployments that are a part of the Application become OutOfSync if they have topologySpreadConstraints as part of specs . when looking at the diff pane it shows unrelated diff regarding the resource limits:
![image](https://github.com/argoproj/argo-cd/assets/36511676/566a258b-e593-45bc-9284-9dca93f9fe9d)

**To Reproduce**
Create argo application that deploy the below manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: petclinic-demo-app-1
  labels:
    app: petclinic-demo-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-demo-app-1
  template:
    metadata:
      labels:
        app: petclinic-demo-app-1
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app: petclinic-demo-app-1
          matchLabelKeys:
            - pod-template-hash
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Ignore
      containers:
        - name: app
          image: jbrisbin/spring-petclinic
          env:
          - name: "_JAVA_OPTIONS"
            value: "-Xmx1G -Xms1G -XX:MaxDirectMemorySize=64m"
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
```
And you should see app outofsync with a diff of limits.
2) Remove the topologySpreadConstraints from deployment :
```yaml
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app: petclinic-demo-app-1
          matchLabelKeys:
            - pod-template-hash
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Ignore
```
And you should see that outofsync is no longer seen.

**Expected behavior**
App should be synced properly in terms of resource limits regardless the existence of topologySpreadConstraints

**Screenshots**

**Version**

```shell
v2.9.1+58b04e5
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ashutosh16** [comment]
I have seen a similar issue in one environment where resource limits diffing, however, in another environment with an identical configuration there is no difference. The spec doesn't contain any extra fields like  `topologySpreadConstraints`
```
resources:
            limits:
              cpu: '4'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
```
![Screenshot 2024-01-08 at 2 34 45 PM](https://github.com/argoproj/argo-cd/assets/11219262/c94e80b6-c679-4194-b773-20b475b989b0)
