### ISSUE TITLE
Context deadline exceeded when having more than 30 apps

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1641]
**Describe the bug**
with version 1.0.0
When using more than 20 apps it appears a lot of the time that argo cannot refresh or sync and gives context deadline exceeded errors. 

**To Reproduce**
Use more applications and the problem appears 

**Expected behavior**
Quick response without errors 

**Screenshots**

![image](https://user-images.githubusercontent.com/9946020/58230193-ed53b180-7d33-11e9-9655-e0cb60dfab6b.png)

**Version**

```shell
1.0.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Additional context**

**Comment by alexmt** [comment]
I'm almost sure this is because of this change https://github.com/argoproj/argo-cd/pull/1528

 @peterbosalliandercom , do you store all applications in a single repo? In this case repo server responses might be slow because it hold lock per repo during manifest generation.


As a quick fix you can increase timeout using '--repo-server-timeout-seconds' flag in argocd-application-controller deployment. By default it is 60 seconds

**Comment by alexmt** [comment]
You can also increase number of repo servers to improve performance.

Meanwhile we should optimize template generation in case when repo has a lots of applications.

**Comment by peterbosalliandercom** [comment]
We will test thism thanks for quick response

**Comment by alexmt** [comment]
@peterbosalliandercom did you have a chance to check if '--repo-server-timeout-seconds' helps?

**Comment by sahil87** [comment]
We were facing the same issue. This helped instantly. 
For reference, we used the following overlay for deploying argocd:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-application-controller
        command:
        - argocd-application-controller
        - --status-processors
        - "20"
        - --operation-processors
        - "10"
        - --repo-server-timeout-seconds
        - "180"
```
