### ISSUE TITLE
[ApplicationSet controller] reflect.Value.SetMapIndex: value of type interface {} is not assignable to type string

### ISSUE THREAD

**Issue by cilindrox** [argoproj/argo-cd#16417]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to argocd v2.9.x, the ApplicationSet controller is failing to start with the following error `panic: reflect.Value.SetMapIndex: value of type interface {} is not assignable to type string`.

**To Reproduce**

From the output, it seems this is related to a string being casted as `{}`, but I've taken a closer look at all the ApplicationSet definitions and I see no such values being passed into the template.

I've also attempted removing the ApplicationSet that is mentioned in the logs during the crash, but then the panic is raised on the following (alphabetically) application, which suggests it's a controller issue and not an appset definition issue.

**Expected behavior**

With v2.8.6, the ApplicationSet controller starts cleanly without panicking and the controllers progresses through the appset reconcile cycle

**Version**

```json
{
    "Version": "v2.9.2+c5ea5c4",
    "BuildDate": "2023-11-20T17:18:26Z",
    "GitCommit": "c5ea5c4df52943a6fff6c0be181fde5358970304",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

Tested all versions ranging from `2.9.0`, `2.9.1` and `2.9.2`, all with the same result. Rolling back to ArgoCD `v2.8.6` starts the ApplicationSet controller without any issues.

**Logs**

I've tried increasing the log level by setting `applicationsetcontroller.log.level: 'debug'` in the `argocd-cmd-params-cm` configMap, but the trace/logs don't yield anything more useful.

```
time="2023-11-21T17:56:17Z" level=info msg="matched cluster secret" cluster=cluster-my-cluster-foo-bar

panic: reflect.Value.SetMapIndex: value of type interface {} is not assignable to type string

goroutine 438 [running]:

reflect.Value.assignTo({0x3356620?, 0xc0007af000?, 0x4fc19b?}, {0x3ae7354, 0x19}, 0x3223420, 0x0)

	/usr/local/go/src/reflect/value.go:3307 +0x289

reflect.Value.SetMapIndex({0x33c9940?, 0xc001acda40?, 0xc0007ab4a0?}, {0x3223420, 0xc0007aefd0, 0x98}, {0x3356620, 0xc0007af000, 0x94})

	/usr/local/go/src/reflect/value.go:2395 +0x1b2

github.com/imdario/mergo.deepMerge({0x33c9940?, 0xc001acda40?, 0x0?}, {0x33c9be0?, 0xc0013fcd20?, 0x98?}, 0x0?, 0x2, 0xc0006c0408)

	/go/pkg/mod/github.com/imdario/mergo@v0.3.16/merge.go:212 +0x2645

github.com/imdario/mergo.deepMerge({0x33c9be0?, 0xc001acdce0?, 0xcc0121f1630?}, {0x33c9be0?, 0xc0013fccf0?, 0x98?}, 0x3356620?, 0x1, 0xc0006c0408)

	/go/pkg/mod/github.com/imdario/mergo@v0.3.16/merge.go:153 +0x1b69

github.com/imdario/mergo.deepMerge({0x33c9be0?, 0xc00110e330?, 0x33c9be0?}, {0x33c9be0?, 0xc0013fcde0?, 0x0?}, 0x0?, 0x0, 0xc0006c0408)

	/go/pkg/mod/github.com/imdario/mergo@v0.3.16/merge.go:153 +0x1b69

github.com/imdario/mergo.merge({0x31bf560, 0xc00110e330}, {0x33c9be0, 0xc0013fcde0}, {0xc0010a8f60, 0x1, 0x0?})

	/go/pkg/mod/github.com/imdario/mergo@v0.3.16/merge.go:395 +0x2cb

github.com/imdario/mergo.Merge(...)

	/go/pkg/mod/github.com/imdario/mergo@v0.3.16/merge.go:319

github.com/argoproj/argo-cd/v2/applicationset/generators.(*MatrixGenerator).GenerateParams(0xc001142fc0?, 0xc00087e280, 0xc001086580)

	/go/src/github.com/argoproj/argo-cd/applicationset/generators/matrix.go:67 +0x45d

github.com/argoproj/argo-cd/v2/applicationset/generators.Transform({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc001084240, 0x0, 0x0, 0x0}, ...)

	/go/src/github.com/argoproj/argo-cd/applicationset/generators/generator_spec_processor.go:67 +0x7ec

github.com/argoproj/argo-cd/v2/applicationset/controllers.(*ApplicationSetReconciler).generateApplications(_, {{{0x3074774, 0xe}, {0xc0010a0000, 0x14}}, {{0xc0012f8b46, 0x7}, {0x0, 0x0}, {0xc0012f8b50, ...}, ...}, ...})

	/go/src/github.com/argoproj/argo-cd/applicationset/controllers/applicationset_controller.go:499 +0x205

github.com/argoproj/argo-cd/v2/applicationset/controllers.(*ApplicationSetReconciler).Reconcile(0xc00055d680, {0x4d4fd38, 0xc000f380f0}, {{{0xc0012f8b50, 0x6}, {0xc0012f8b46, 0x7}}})

	/go/src/github.com/argoproj/argo-cd/applicationset/controllers/applicationset_controller.go:117 +0x185

sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000cd6580, {0x4d4fd38, 0xc000f38090}, {{{0xc0012f8b50?, 0x38c2ae0?}, {0xc0012f8b46?, 0xc001035620?}}})

	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x27e

sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000cd6580, {0x4d4fd70, 0xc0007ab310}, {0x35ad940?, 0xc00081e320?})

	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x325

sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000cd6580, {0x4d4fd70, 0xc0007ab310})

	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x1c9

sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()

	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x79

created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 172

	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x52b
```

Here's a the cluster definition from the cluster mentioned in the logs above

```yaml
apiVersion: v1
kind: Secret
type: Opaque
data:
  config: sometoken
  name: my-cluster
  server: https://my-cluster.my-region.eks.amazonaws.com
metadata:
  annotations:
    argocd.argoproj.io/refresh: "2023-06-02T13:26:39Z"
    managed-by: argocd.argoproj.io
  generateName: cluster-my-cluster-
  labels:
    app.kubernetes.io/name: my-cluster
    argocd.argoproj.io/secret-type: cluster
    environment: my-env
    name: my-cluster
    region: my-region
  name: cluster-my-cluster-foo-bar
  namespace: argocd
```

I've gone through the commits for v2.9.0 and couldn't find anything relevant to this, so any help is appreciated.

Thanks in advance,

**Comment by crenshaw-dev** [comment]
Can you share the (properly redacted) appset definition for one of the apps which is causing the error?

**Comment by cilindrox** [comment]
here it goes @crenshaw-dev 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
spec:
  generators:
  - merge:
      mergeKeys:
      - server
      generators:
      - clusters:
          values:
            project: in-cluster
            roleARN: 'arn:aws:iam::ACCCOUNT:role/irsa/foo/external-dns_role'
            domainFilters: '{my.domain}'
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
          values:
            project: remote-clusters
            roleARN: '{{`{{metadata.annotations.external-dns}}`}}'
            domainFilters: '{my.domain,domain.example}'
      - clusters:
          selector:
            matchExpressions:
            - key: environment
              operator: In
              values: [ dev ]
          values:
            project: remote-clusters
            roleARN: '{{`{{metadata.annotations.external-dns}}`}}'
            domainFilters: '{my.domain}'
  template:
    metadata:
      name: 'external-dns-{{`{{name}}`}}'
    spec:
      project: '{{`{{values.project}}`}}'
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        path: charts/external-dns  # a copy of https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/
        helm:
          releaseName: external-dns
          valueFiles:
          - values-foo.yaml
          parameters:
          - name: 'external-dns.domainFilters'
            value: '{{`{{values.domainFilters}}`}}'
          - name: 'external-dns.serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
            value: '{{`{{values.roleARN}}`}}'
      destination:
        namespace: kube-system
        server: '{{`{{server}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ServerSideApply=true
```

I picked this one because it's got the most-likely offender, the "helm list as string" notation (`domainFilters: '{this,is,a,list}'`)

This is rendered correctly on v2.8.6, ie: the chart value is

```yaml
domainFilters: ["my.domain"]
```
and
 
```yaml
domainFilters: ["my.domain", "domain.example"]
```

I've also double checked, and all non `in-cluster`/local cluster definitions are properly annotated (no empty properties, and the expected property is being read from the cluster definition and passed to the chart)

That said, I've tried refactoring the appset definition (removed the suspected `domainFilters`) and the error was still present. From the logs I'm unable to determine which appset(s) are the culprits, so take this with a pinch of salt
