### ISSUE TITLE
(appset) Filtering by title on Pull Request generator

### ISSUE THREAD

**Issue by jjsiv** [argoproj/argo-cd#16447]
# Summary

Currently it is only possible to filter pull requests with the PR generator by target and source branches (also labels in case of Github and Gitlab). I think it would be nice to be able to do some filtering based on the PR title - especially for Git providers such as Bitbucket Server which do not support labels.

# Motivation

We use Bitbucket Server and currently we can only filter pull requests based on the source/target branch. Sometimes we would like to perform other actions on the PR before it is picked up by ArgoCD, but as source/target branches are immutable and Bitbucket doesn't support labels, we have no option to do that. Filtering based on the title would allow us to configure ArgoCD to only pick PRs with particular keywords.

# Proposal

I can have a look into this

**Comment by crenshaw-dev** [comment]
Rather than adding a new filter, I think we can take advantage of the existing post-selector.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - pullRequest:
      github:
        owner: myorg
        repo: myrepository
    values:
      titleMatches: '{{ regexMatch "some-regex" .title }}'
    selector:
      matchLabels:
        values.titleMatches: "true"
```

I haven't tested this, but seems like it should work. We'd still need to add the `title` parameter, but we'd avoid the new filter field.

**Comment by jjsiv** [comment]
Indeed, that could be a solution as well. I will try it out locally later and see how it goes

**Comment by llavaud** [comment]
> Rather than adding a new filter, I think we can take advantage of the existing post-selector.
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: ApplicationSet
> metadata:
>   name: guestbook
> spec:
>   goTemplate: true
>   generators:
>   - pullRequest:
>       github:
>         owner: myorg
>         repo: myrepository
>     values:
>       titleMatches: '{{ regexMatch "some-regex" .title }}'
>     selector:
>       matchLabels:
>         values.titleMatches: "true"
> ```
> 
> I haven't tested this, but seems like it should work. We'd still need to add the `title` parameter, but we'd avoid the new filter field.

I don't see the `values` bloc in the doc neither in the ApplicationSet spec...

**Comment by crenshaw-dev** [comment]
Ah, we need to add that `values` field to all generators. Try this.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - pullRequest:
          github:
            owner: myorg
            repo: myrepository
      - list:
          elements:
            titleMatches: '{{ regexMatch "some-regex" .title }}'
    selector:
      matchLabels:
       titleMatches: "true"
```

**Comment by crenshaw-dev** [comment]
Just tested, and that actually works.

**Comment by ggjulio** [comment]
Unfortunately, it seem that the `title` key is not available on bitbucket.
![image](https://github.com/argoproj/argo-cd/assets/13398285/45ffb658-4935-432d-8be8-4252360306f4)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - pullRequest:
            bitbucketServer:
              project: project-name
              repo: repo-name
              api: https://bitbucket.example.com
              basicAuth:
                username: argo-user
                passwordRef:
                  secretName: secret-ref
                  key: token-key
        - list:
            elements:
              - titleMatches: '{{ regexMatch "some-regex" .title }}'
    selector:
      matchLabels:
       titleMatches: "true"
template:
  // ...
```

**Comment by ggjulio** [comment]
> Rather than adding a new filter, I think we can take advantage of the existing post-selector.
> 
> I haven't tested this, but seems like it should work. We'd still need to add the `title` parameter, but we'd avoid the new filter field.

A PR adding the `title` parameter is ready for review #17907

**Comment by ggjulio** [comment]
Btw it works fine as long as we careful with the matcher...
First tried `"[PREVIEW]"` and somehow it matched all PRs... quickly triggering hundreds & hundreds of PR deployments... 
Indeed brackets are special chars and should be properly escaped `"\\[PREVIEW\\]"` .

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-previews
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - pullRequest:
          requeueAfterSeconds: 30
          bitbucketServer:
            project: name
            repo: name
            api: https://bitbucket.example.com
            basicAuth:
              // ...
      - list:
          elements:
          - titleMatches: '{{ regexMatch "\\[PREVIEW\\]" .title }}'
    selector:
      matchLabels:
        titleMatches: "true"
  template:
    // ...
```
