### ISSUE TITLE
Make CMP able to expose its grpc via network

### ISSUE THREAD

**Issue by ptimofee** [argoproj/argo-cd#16472]
# Summary

Make CMP able to expose its grpc via network.
Now it's available only via unix socket.

# Motivation

There is basic grpc [health check implemented](https://github.com/argoproj/argo-cd/blob/v2.9.2/cmpserver/server.go#L117-L118) for CMP server.
This allows users to create readiness and liveness probes for argocd-repo-server's sidecard plugin containers, like
```
      readinessProbe:
        exec:
          command:
          - grpcurl
          - --plaintext
          - --unix
          - /home/argocd/cmp-server/plugins/avp-helm.sock
          - grpc.health.v1.Health/Check
        initialDelaySeconds: 10
```
Such probes are crucial for plugin containers if you have auto-sync enabled as I believe there a race condition with discovery when argocd-repo-server being restarted.

# Proposal

Make CMP able to expose its grpc via network. This would allow using standard k8s [grpc probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) without installing additional binaries into sidecar (grpcurl).
