### ISSUE TITLE
An ApplicationSet Generator that allows overlay off of selectors.

### ISSUE THREAD

**Issue by tomelliot16** [argoproj/argo-cd#16474]
# Summary

First of all if a current generator supports this I would love to learn how to configure. (I tried mergeGenerator but the negative case gets very complicated very quickly)

The idea would be a generator base that supports a baseGenerator then similar to ClusterGenerator it is able to select based on labels.

# Motivation

The problem we are try to solve is the ability to select all clusters and given a type of cluster be able deploy override setting to the application without having to alway worry about the negative case and merge that back in.

Example use case
| Cluster Name | Cluster Labels |
|--------|--------|
| cluster-1 | region=us-east-1, type=internal, environment=dev |
| cluster-2| region=us-west-1, type=internal, environment=dev |
| cluster-3 | region=eu-west-1, type=internal, environment=dev |
| cluster-4 | region=us-east-1, type=product, environment=dev |
| cluster-5 | region=us-west-1, type=product, environment=dev |
| cluster-6 | region=eu-west-1, type=product, environment=dev |
| cluster-7 | region=us-east-1, type=build, environment=dev |
| cluster-8 | region=us-west-1, type=build, environment=dev |
| cluster-9 | region=eu-west-1, type=build, environment=dev |
| cluster-10 | region=us-east-1, type=internal, environment=staging |
| cluster-11 | region=us-west-1, type=internal, environment=staging |
| cluster-12 | region=eu-west-1, type=internal, environment=staging |
| cluster-13 | region=us-east-1, type=product, environment=staging |
| cluster-14 | region=us-west-1, type=product, environment=staging |
| cluster-15 | region=eu-west-1, type=product, environment=staging |
| cluster-16 | region=us-east-1, type=build, environment=staging |
| cluster-17 | region=us-west-1, type=build, environment=staging |
| cluster-18 | region=eu-west-1, type=build, environment=staging |
| cluster-19 | region=us-east-1, type=internal, environment=prod |
| cluster-20 | region=us-west-1, type=internal, environment=prod |
| cluster-21 | region=eu-west-1, type=internal, environment=prod |
| cluster-22 | region=us-east-1, type=product, environment=prod |
| cluster-23 | region=us-west-1, type=product, environment=prod |
| cluster-24 | region=eu-west-1, type=product, environment=prod |
| cluster-25 | region=us-east-1, type=build, environment=prod |
| cluster-26 | region=us-west-1, type=build, environment=prod |
| cluster-27 | region=eu-west-1, type=build, environment=prod |

Now lets say you have 3 applicationSets called myfoobar-dev, myfoobar-staging, myfoobar-prod
myfoobar-dev would select environment=dev
myfoobar-staging would select environment=staging
myfoobar-prod would select environment=prod

Now lets say for only us-east-1 region internal you want to use a special values file called special-internal.yaml for each of the application sets. this would select only one cluster per applicationSet to have different values. cluster-1, cluster-10, and cluster-19.

Now in addition you want all clusters labeled type=product to use product.yaml values file. this would be 3 per application set cluster-5, cluster-6, cluster-7, then cluster-13, cluster-14, cluster-15, then cluster-22, cluster-23, cluster-24.

Okay so Yes currently using a series of generators you can select the proper cluster but for example focusing on myfoobar-prod.

If I had
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myfoobar-prod
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            type: internal
            environment: prod
            region: us-east-1
        template:
          metadata: {}
          spec:
            source:
              helm:
                valueFiles:
                  - values-prod.yaml
                  - special-internal.yaml
              path: charts/myfoobar
              repoURL: 'https://github.com/company/myfoobar'
              targetRevision: v1.2.3
    - clusters:
        selector:
          matchLabels:
            type: product
            environment: prod
        template:
          metadata: {}
          spec:
            destination: {}
            project: ''
            source:
              helm:
                valueFiles:
                  - values-prod.yaml
                  - product.yaml
              path: charts/myfoobar
              repoURL: 'https://github.com/company/myfoobar'
              targetRevision: v1.2.3
  template:
    metadata:
      labels:
        cluster: '{{name}}'
        parent: myfoobar-prod
      name: '{{name}}-myfoobar-prod'
    spec:
      destination:
        name: '{{name}}'
        namespace: myfoobar-system
      project: myfoobar-proj
      source:
        helm:
          valueFiles:
            - values-prod.yaml
        path: charts/myfoobar
        repoURL: 'https://github.com/company/myfoobar'
        targetRevision: v1.2.3

```

that would find cluster-20, custer-21, cluster-25, cluster-26, and cluster-27. Okay so yes we could systematically do the inverse
using some sort of but as we add more labels to cluster and have more then one label selector for 1 or more it becomes a form of [DeMorgan's Law](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) and now because the clusterGenerators are basically ors of ands we quickly are for to break it down to that form. In addition these are key value pairs so its not quite a perfect DeMorgan's law problem. We attempts with minor success to write an overly complicated helm chart chart that tried to solve the negative as a template very much pushing the limit on the abilities of the helm as a programming language. Anyways this all seems way too complicated and I much rather have something that is clear concise and hard to mess up.

# Proposal
Now a yaml is worth a 1000 words so I'm going to start there. (I'm not the best namer but lets call this generator for now clusterOverlayGenerator)
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myfoobar-prod
spec:
  generators:
    - clustersOverlay:
        selector:
          matchLabels:
            environment: prod
        overlays:
          - selector:
              matchLabels:
                type: internal
                region: us-east-1
            template:
              spec:
                source:
                  helm:
                    valueFiles:
                      - special-internal.yaml
          - selector:
              matchLabels:
                type: product
              template:
                spec:
                  source:
                    helm:
                      valueFiles:
                        - values-prod.yaml
                        - product.yaml
  template:
    metadata:
      labels:
        cluster: "{{name}}"
        parent: myfoobar-prod
      name: "{{name}}-myfoobar-prod"
    spec:
      destination:
        name: "{{name}}"
        namespace: myfoobar-system
      project: myfoobar-proj
      source:
        helm:
          valueFiles:
            - values-prod.yaml
        path: charts/myfoobar
        repoURL: https://github.com/company/myfoobar
        targetRevision: v1.2.3
```

The idea here would this would select all cluster labeled with prod and then override the values for those who match the labels
