### ISSUE TITLE
Auto Sync override

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#16489]
# Summary

An ability to override "stuck" auto-sync operation. It is known that sync might stuck due to various reasons: sync job could not be complete due to "image pull backoff"; deployment cannot reach a healthy state due to failing readiness probe, etc. Ideally, it should be enough to fix the root cause and let Argo CD deploy new changes. However, currently, Argo CD is not going to give up on a first sync if new changes are detected. 

# Motivation

Preview environments. Argo CD application generated by Appset for a pull request might fail, because code in the PR might have issue. Engineer should be able to just fix bug in the code, push new change to the PR and see updated synced applciation.

# Proposal

Introduce a `syncPolicy.terminate` setting that allows configuring automatic operation termination when based on the state of configured "problematic" resources. 

Example below cancels automatic sync :

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: guestbook

  syncPolicy:
    terminate:
         timeout: 10m # global timeout (see https://github.com/argoproj/argo-cd/issues/6055 )
         resource:
             - group: batch
                kind: Job
                name: upgrade-database-*
                status: Progressing
                timeout: 1m # sync should be terminated if `upgrade-database` sync hook stuck for longer than 1 minute
```
