### ISSUE TITLE
Multi source application doesn't accept releaseName field to override application name for Helm

### ISSUE THREAD

**Issue by AaveshK** [argoproj/argo-cd#16498]
# Summary

Single source applications have a source.helm.releaseName field which can override the release name of the application resources from the default application name. Multi-source applications even when supplied with a sources.helm.releaseName for either/both the sources do not use it and it takes the application name by default.

# Motivation

I am trying to deploy multiple applications that point to a single helm repo and a git repo containing the values file for each. The release name for each application is supposed to be the same and hence cannot match the application name. Each application can possibly run with different chart versions hence multi-source application seems the right way for ease of upgrade/rollback.

# Proposal

A field similar to the source.helm.releaseName could be supported to allow overriding application name as the release name

**Comment by crenshaw-dev** [comment]
Multi-source does support `releaseName`.


```yaml
project: another
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
sources:
  - repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      releaseName: one
  - repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      releaseName: two
```

![image](https://github.com/argoproj/argo-cd/assets/350466/bf32af9d-7945-420a-8ae1-a031f5ddb2ad)
