### ISSUE TITLE
Application sets Matrix : SCM + GIT - never refresh 

### ISSUE THREAD

**Issue by mysiki** [argoproj/argo-cd#16518]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using matrix generator with GIT and SCM work for first manifest upload. But it never refresh and discover the new branch (withSCM generator). 

The goal is to create 1 application by git branch. 

Generator : 

```yaml
  generators:
    - matrix:
        generators:
          - scmProvider:
              cloneProtocol: https
              gitlab:
                group: "95"
                api: https://mygitlab.com
                allBranches: true
                includeSubgroups: false
                includeSharedProjects: false
                tokenRef:
                  secretName: secret-git
                  key: token
              filters:
                - repositoryMatch: ^argo-inventory$
          - git:
              repoURL: '{{ url }}'
              revision: '{{ branch }}'
              files:
                - path: '{{ branch }}-wrapper-values.yaml'
```

So I use the SCM Generator to discover the branch of a project and the Git generator in order to get config file specific to the branch. 

When I create the applicationset (first upload) it work correctly. But if I create new branch in project watch by SCM, it does nothing. 

Does I miss some parameter or it's a bug ? :) 

**To Reproduce**

Create applicationset with the previous generator, add new branch. 

**Expected behavior**

AppSet detect new branch with SCM provider and generate new application. 

**Version**

```shell
v2.9.3+6eba5be
```
