### ISSUE TITLE
ArgoCD does not update Helm dependencies when version wildcard is used

### ISSUE THREAD

**Issue by florentvaldelievre** [argoproj/argo-cd#16533]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We would like to automatically upgrade our Helm charts to the latest patch version when available. It works only if I hit 'Hard Refresh' in the UI. 

Example:
```
apiVersion: v2
name: external-dns
description: A Helm chart for deploying external-dns from Bitnami
type: application
version: 1.0.0
dependencies:
- name: external-dns
  version: "6.28.x"
  repository: https://charts.bitnami.com/bitnami/
```

I have also tried to change the following settings in argocd-cm, but changing timeout.hard.reconciliation does not seems to have an effect.

```
  # -- Timeout to discover if a new manifests version got published to the repository
  timeout.reconciliation: 10s

  # -- Timeout to refresh application data as well as target manifests cache
  timeout.hard.reconciliation: 30s
```

1. Is there a way to achieve this without any manual action? Am I missing something?
2. Even if timeout.hard.reconciliation was working, it would be good to be able to specify per Application (argocd.argoproj.io/refresh: hard in the Application manifest could potentially work but its temporary since it's removed right after the first time)
3. Ideally, an helm option in the Application manifest to force checking every X seconds would be nice

```
argocd-server: v2.9.1+58b04e5
  BuildDate: 2023-11-14T15:08:20Z
  GitCommit: 58b04e5e11d007b0518853029ff7612c24a2eb35
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0`
```
