### ISSUE TITLE
Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune`

### ISSUE THREAD

**Issue by thoefkens** [argoproj/argo-cd#16532]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I have tried connecting a new repository from our gitlab instance containing kustomize overlays to ArgoCD in our K8S cluster. This has worked fine, both using SSH and HTTPS the repo shows as "Connected". However, when setting up an application that uses that repo, the application fails to refresh its state with this error:

`stream read failed: rpc error: code = Unknown desc = error getting app resource tree: error getting cached app resource tree: ComparisonError: rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed timeout after 1m30s`

The application looks like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proj-dev-new-app
  namespace: argocd
spec:
  project: proj-dev
  source:
    repoURL: https://git.xxxcom/pimcore/backend-code.git --> this is the repo configured with the same URL under "Repositories"
    targetRevision: feature/test_new_deployment
    path: backend-code-kustomize/overlay/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: proj-dev-new
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
```

I have been unable to find out why this happens. We have another repo connected from the same gitlab instance and those applications sync fine.

**To Reproduce**

1. Create a repo. (SSH or HTTPS)
2. Add an application for that Repo URL.

**Expected behavior**

Applications based on repo URL will work fine if the repo is connected and the target revision/path exist.

**Version**

argocd-server: v2.7.14+a40c95a.dirty
  BuildDate: 2023-09-07T16:50:42Z
  GitCommit: a40c95a6383baa0d9f670586a5c295021f59337c
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
**Logs**

**Comment by Puvendhan** [comment]
Any fix on this?

**Comment by Puvendhan** [comment]
Any fix for this?, can anyone look into this?

**Comment by deer-wmde** [comment]
I'm also experiencing  this with argo-cd 6.7.15.

This is a full `Application` manifest that I'm encountering this with, hopefully someone can reproduce it:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bitnami/charts.git
    path: bitnami/redis
    targetRevision: HEAD

  syncPolicy:
    automated:
      selfHeal: false
      prune: true
```
