### ISSUE TITLE
ApplicationSet pull request generator path filter

### ISSUE THREAD

**Issue by jan-mrm** [argoproj/argo-cd#16574]
# Summary

I'd be interested in having a path filter in the pull request generator of an ApplicationSet.
That would enable the possibility to set up pull request deployments using the ApplicationSet and the pull request generator in a **mono repo** setup.

# Motivation

As far as I can tell: 
Currently mono repos are not supported for pull request deployments since you cannot filter on specific paths. Without a path filter all pull requests (that match the branch name filter or label filter, when setup) are observed and trigger the generator.
I guess it would be possible to setup a variant using the existing filters (branch name or label) but i feel like a path filter would be very convenient since the developer would not need to use the correct branch name or label on the pull request.

# Proposal

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-pr
spec:
  generators:
    - pullRequest:
        azuredevops:
          organization: my-org
          project: my-project
          repo: my-repo
          tokenRef:
            secretName: my-token
            key: token
          pathFilters: 
            - /apps/app1
  template:
    ...
```

How do you think this should be implemented?

Actually I'm not sure about if its feasible. I'd guess argo would need to use the api of the platform and check if there is at least one file changed for the path filter. That might go too far?

**Comment by crenshaw-dev** [comment]
> That might go too far?

No, I think this is a good idea. I suspect that all our favorite SCM providers probably provide access to the list of modified files.

I do wonder if we should think about how this would work in a one-shot monorepo appset. So imagine I want a single AppSet to create both my apps and my preview apps. What would that look like? Maybe in this realm?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-monorepo
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/my-org/my-project
        revision: HEAD
        directories:
          - path: apps/*
        values:
          appName: '{{ index (split "/" .path.path) 1 }}'
          pr: "false"
    - matrix:
        generators:
        - pullRequest:
            github:
              owner: my-org
              repo: my-project
        - list:
            # Use regex to get the 2nd segment of each path in the modifiedPaths list. Loop over that list and create a
            # new YAML list of objects where the key is "appName" and the value is the 2nd segment of the path. Add an
            # field to each object called "pr" with the value `true`.
            elementsYaml: |
              {{- range $path := .modifiedPaths }}
              {{- if reMatch "apps/([^/]+)/" $path }}
              - appName: {{ index (split "/" $path) 1 }}
                values:
                  pr: "true"
              {{- end }}
              {{- end }}
  template:
    metadata:
      # If the app is a PR, suffix the app name with `-pr-{PR_NUMBER}`.
      name: '{{ if eq .values.pr "true" }}{{ .values.appName }}-pr-{{ .values.prNumber }}{{ else }}{{ .values.appName }}{{ end }}'
      annotations:
        # Add the path annotation to avoid unnecessary manifest rendering.
        argocd.argoproj.io/manifest-generate-paths: "apps/{{.values.appName}}"
```

The above also handles the case where a single PR modifies more than one app.

The only change needed to make the above work is to expose the `modifiedPaths` parameter.
