### ISSUE TITLE
Notification - GitHub PR Comment not rendered

### ISSUE THREAD

**Issue by clementblaise** [argoproj/argo-cd#16577]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Configuration of notification template using GitHub PR Comment don't template correctly.

**To Reproduce**

Add template using `github.pullRequestComment`
```yaml
template.app-deployed: |
    message: Deployed
    github:
      repoURLPath: "{{.app.metadata.annotations.repo}}"
      revisionPath: "{{.app.metadata.annotations.sha}}"
      pullRequestComment:
       content: "Deployed"
```

Retrieve template:
```bash
argocd admin notifications template get app-deployed -o yaml
app-deployed:
  github:
    repoURLPath: '{{.app.metadata.annotations.repo}}'
    revisionPath: '{{.app.metadata.annotations.sha}}'
  message: Deployed
```

**Expected behavior**

The template is not rendered with `github.pullRequestComment`.

When `github.status` or `github.deployment` are used, it gets correctly rendered and notifications are successful. Both are well [documented](https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/github/#templates) however  found `github.pullRequestComment` [here](https://github.com/argoproj/notifications-engine/blob/8ba938ed24a03a6da53dc5bb295fdc7ecc7ee91d/pkg/services/github.go#L39)

**Screenshots**

**Version**

```shell
argocd: v2.9.3+6eba5be.dirty
  BuildDate: 2023-12-02T00:37:14Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.9.1+58b04e5
```

**Logs**

```
```
