### ISSUE TITLE
ApplicationSet - failed to pull request service provider: Get ... : net/http: invalid header field value for "Authorization"

### ISSUE THREAD

**Issue by johan974** [argoproj/argo-cd#16585]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After adding the ApplicationSet (controller), I get this message: 
```
status:
  conditions:
    - lastTransitionTime: '2023-12-09T18:51:01Z'
      message: >-
        failed to select pull request service provider: Get
        "http://gitea-gitea-http.default.svc.cluster.local/api/v1/version":
        net/http: invalid header field value for "Authorization"
      reason: ApplicationGenerationFromParamsError
      status: 'True'
      type: ErrorOccurred
```

I tried also to work sith https. Or with port 3000. 

**To Reproduce**

This is the Generator part of the ApplicationSet: 

```
spec:
  generators:
    - pullRequest:
        gitea:
          api: http://gitea-gitea-http.default.svc.cluster.local
          insecure: true
          owner: gituser
          repo: quotes
          tokenRef:
            key: token
            secretName: gitea-token
        requeueAfterSeconds: 90

```
Or https or the port number. 

May be some extra information. When I perform a pull request, I see in a webhook the following header info: 

```
Request URL: http://el-github-pr.default.svc.cluster.local:8080
Request method: POST
Content-Type: application/json
X-GitHub-Delivery: f8d91e7c-something
X-GitHub-Event: pull_request
X-Gitea-Delivery: f8d91e7c-something
X-Gitea-Event: pull_request
X-Gitea-Signature: a3b712c6096063fdf8d91e7c-something
X-Gogs-Delivery: f8d91e7c-something
X-Gogs-Event: pull_request
X-Gogs-Signature: a3b712c6096063fdef8d91e7c-something
```

**Expected behavior**

Get a trigger to create an Application.

**Version**

```shell
I use ArgoCD (UI) version: v2.9.0+9cf0c69
```

**Logs**

```
See above.
```
