### ISSUE TITLE
Application setauthentication handshake failed: EOF in logs

### ISSUE THREAD

**Issue by DucretJe** [argoproj/argo-cd#16593]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

We upgraded Argo to 2.9.2 and then our logs are flooded by errors:

```plain
{"error":"error generating params from git: error retrieving Git files: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: EOF\"","generator":{},"level":"error","msg":"error generating params","time":"2023-12-12T11:02:35Z"}
{"error":"error generating params from git: error retrieving Git files: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: EOF\"","generator":{"git":{"repoURL":"git@github.com:xxxx/yyyy.git","files":[{"path":"zzzz/**/argocd.yaml"}],"revision":"main","template":{"metadata":{},"spec":{"destination":{},"project":""}}}},"level":"error","msg":"error generating application from params","time":"2023-12-12T11:02:35Z"}
```

We didn't managed to manually trigger it, it's just repeating periodically.
Argo is still capable to sync our apps, (all is synced and healthy, and still detects the changes), beside the logs, we haven't noticed anything.

**To Reproduce**

Deploy Argo using 5.51.4 Helm chart
Create definition of an ApplicationSet

```yaml
applicationsets:
  myapp:
    autoSync: false
    generator:
      repoURL: git@github.com:xxxx/yyyy.git
      path: zzzz/**/argocd.yaml
      revision: main
    template:
      name: "app-{{ product.name }}"
      repoURL: git@github.com:xxxx/yyyy.git
      revision: main
      path: "apps/{{ product.name }}"
      valueFiles:
        - product.yaml
        - values.yaml
      destinationNamespace: "{{ product.name }}"
```
Create Argo apps to point to repo xxxx/yyyy and deploy the apps from application set

**Expected behavior**

The apps to be deployed without errors in logs

**Version**

```json
{
    "Version": "v2.9.2+c5ea5c4",
    "BuildDate": "2023-11-20T17:18:26Z",
    "GitCommit": "c5ea5c4df52943a6fff6c0be181fde5358970304",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```
