### ISSUE TITLE
ApplicationSet drops field specified in ignoreApplicationDifferences when applying patch

### ISSUE THREAD

**Issue by shydefoo** [argoproj/argo-cd#16605]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When ignoreApplicationDifferences is set on an element in a list, eg `helm.parameters[]`, the ApplicationSet drops the ignored field's value after applying update to Application manifest when another field in the Application is modified. For example:
```
source:
  repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
  path: helm-guestbook
  targetRevision: HEAD
  helm:
    parameters:
      - name: service.port # <-- this is empty
      - name: image.tag
        value: '0.1'
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
  name: in-cluster
```

**To Reproduce**

1. Apply an Appset with `ignoreApplicationDifferences` specified, eg:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.helm.parameters[] | select(.name=="service.port").value
  generators:
  - list:
      elements:
      - name: "a"
      - name: "b"
  template:
    metadata:
      name: 'guestbook-{{name}}'
    spec:
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
          parameters:
            - name: service.port
              value: "80"
            - name: image.tag
              value: "0.1"
      destination:
        namespace: argocd
        name: "in-cluster"

```
2. Modify any other field in parameters in `guestbook-a` **Application** except the ignored field, for example the `image.tag` field
3. Check actual manifest (the UI indicates that the value is set, but in the actual manifest, the value field is empty) See screenshots below:
<img width="1354" alt="image" src="https://github.com/argoproj/argo-cd/assets/20089568/7b1b02b7-219b-42b2-ae9a-e6a0146fa30a">

vs

![image](https://github.com/argoproj/argo-cd/assets/20089568/30624bc7-3475-4de5-9398-722937defb2f)

For this example, the patch results in Service resource having port set to 0
![image](https://github.com/argoproj/argo-cd/assets/20089568/99b3d873-fd3b-4ca6-9011-a44af4280cfb)

**Expected behavior**
The expected behaviour should be what's described in the [docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#limitations-of-ignoreapplicationdifferences), where the list gets overwritten with what was defined the ApplicationSet template, so for the example above, `service.port` should be set to 80.

**Screenshots**

See above

**Version**

```shell
➜ argocd version --grpc-web
argocd: v2.8.6+6f7af53.dirty
  BuildDate: 2023-11-01T18:24:23Z
  GitCommit: 6f7af53bea9ebc9e9eadd47fc43b671ef91c0586
  GitTreeState: dirty
  GoVersion: go1.21.3
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```
