### ISSUE TITLE
ApplicationSet pull request gernator fails because it failed to checkout revision somekindofhash: `git fetch origin somekindofhash--tags --force --prune` failed exit status 128: error: Server does not allow request for unadvertised object somekindofhash

### ISSUE THREAD

**Issue by johan974** [argoproj/argo-cd#16619]
In my Kubernetes cluster on Windows Docker Desktop runs both **Gitea** and **ArgoCD**. Using the ApplicationSet I am trying to get a pull request generator work. 

**Describe the bug**

I have an ApplicationSet pull request generator. When opening a pull request I get this error message: 

```
Application conditions
ComparisonError
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to initialize repository resources: rpc error: code = Internal desc = Failed to checkout revision somekindofhash: `git fetch origin somekindofhash--tags --force --prune` failed exit status 128: error: Server does not allow request for unadvertised object somekindofhash
```
I know the token is right because otherwise the id was not found. 

**To Reproduce**

This is the ApplicationSet I use: 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-quotes-app
  namespace: argocd
spec:
  generators:
    - pullRequest:
        gitea:
          owner: gituser
          repo: quotes
          api: http://gitea-gitea-http.default.svc.cluster.local:3000
          tokenRef:
            secretName: gitea-token
            key: token
          insecure: true
        requeueAfterSeconds: 90
  template:
    metadata:
      name: "webapp-{{branch}}-{{number}}"
      namespace: default
    spec:
      source:
        repoURL: "http://gitea-gitea-http.default.svc.cluster.local:3000/gituser/argocd-demo.git"
        targetRevision: "{{head_sha}}"
        path: helmconfig
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

**Expected behavior**

No error message. The git hash is used for starting a new Application. 
The git has is existing. 

**Screenshots**

The exact message is shown above. 

**Version**

argocd ui: 2.9.0

**Logs**

The manifest is: 
```
project: default
source:
  repoURL: >-
    http://gitea-gitea-http.default.svc.cluster.local:3000/gituser/argocd-demo.git
  path: helmconfig
  targetRevision: somehash
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  syncOptions:
    - CreateNamespace=true```
