### ISSUE TITLE
KEDA - SharedResourceWarning in AKS

### ISSUE THREAD

**Issue by joudaon** [argoproj/argo-cd#16635]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

```
When installing KEDA with ArgoCD in a new cluster, I get SharedResourceWarning warning.

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-keda
  namespace: argocd
  labels:
    app_type: applicationset
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              values:
                addonChart: keda
                # anything not staging or prod use this version
                addonChartVersion: 2.11.2
                addonChartRepository: https://kedacore.github.io/charts
              selector:
                matchExpressions:
                  - key: enable_keda
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: pre
              values:
                addonChartVersion: 2.11.2
          - clusters:
              selector:
                matchLabels:
                  environment: pro
              values:
                addonChartVersion: 2.11.2
  template:
    metadata:
      name: "addon-{{.name}}-{{.values.addonChart}}-{{.values.addonChartVersion}}"
      labels:
        app_type: addon
        addon_name: keda
    spec:
      project: default
      sources:
        - repoURL: '{{ .values.addonChartRepository}}'
          targetRevision: '{{ .values.addonChartVersion}}'
          chart: '{{ .values.addonChart}}'
          helm:
            releaseName: keda
            parameters:
              - name: cluster_name
                value: '{{ .name }}'
            values: |-
              webhooks:
                enabled: false              
      destination:
        name: '{{ .name }}'
        namespace: keda
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
```
**To Reproduce**

Install this applicationset in AKS

**Expected behavior**

I should not get any SharedResourceWarning

**Screenshots**

**Version**

Kubernetes version: 1.26.6

```shell
Server: 2.9.2
Client:
  argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
CustomResourceDefinition/clustertriggerauthentications.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
CustomResourceDefinition/scaledjobs.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
CustomResourceDefinition/scaledobjects.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
CustomResourceDefinition/triggerauthentications.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
```
