### ISSUE TITLE
Azure not supported for WebUI PKCE Auth Code Flow

### ISSUE THREAD

**Issue by Kerwood** [argoproj/argo-cd#16649]
## Describe the bug

In the upcoming `v2.10.0-rc1` release, @Marvin9 added support for using authorization code flow with PKCE in the webUI, which is lovely. :heart: 
 - https://github.com/argoproj/argo-cd/pull/15889

Unfortunately Azure is non-compliant with RFC8414 standard because the `/.well-known/openid-configuration` endpoint is missing the `code_challenge_methods_supported` property. 
The ArgoCD login flow is stopped checking for that specific property here.
https://github.com/argoproj/argo-cd/blob/3224102664b747e88e7330e59b3b44bc9c28cd66/ui/src/app/login/components/utils.ts#L76-L80

Other projects seem to have the same issue, like kubelogin.
 - https://github.com/int128/kubelogin/issues/858

This was brought to the attention of Microsoft in January 2021 and I do not think that they intend to do anything about it.
 - https://learn.microsoft.com/en-us/answers/questions/218113/openid-connect-authorization-code-flow-with-proof

## Proposal
 Maybe have a setting something like, `forcePKCECodeChallengeMethod: S256` that would skip the `code_challenge_methods_supported` property check ?

**Comment by Kerwood** [comment]
@michael-basil

**Comment by michael-basil** [comment]
I have verified the same issue and agree with the suggestion of a flag to mindfully force the flow.

🙏

**Comment by Marvin9** [comment]
What if we know in the frontend itself if IdP is Azure then we by default skip the error assuming that PKCE still works even if `/.well-known/openid-configuration` omit `code_challenge_methods_supported`. I don't see benefit of additional flag for exception like this. Any thoughts on it?

**Comment by michael-basil** [comment]
It would seem this was debated a fair amount with the kubelogin project (dropping the link again):

* https://github.com/int128/kubelogin/issues/858

That project chose to go with: "--oidc-use-pkce"

To follow this convention that others in the industry may be conditioned for the following flag (or similar) would seem to follow suit:

* skipPKCECodeChallengeMethodVerification

**Comment by Kerwood** [comment]
> What if we know in the frontend itself if IdP is Azure then we by default skip the error assuming that PKCE still works even if `/.well-known/openid-configuration` omit `code_challenge_methods_supported`. I don't see benefit of additional flag for exception like this. Any thoughts on it?

Personally I think that creating a snowflake solution for a specific provider is a bad idea. This could end up with all sorts of snowflake code for different IDP's. I think it would be better to create a generic setting.

@michael-basil are you proposing that the setting shoud be `skipPKCECodeChallengeMethodVerification` ?

**Comment by michael-basil** [comment]
I am suggesting the same and with the name to skip verification or would be simpler in configuration management over time.

For example, we test before we introduce new Argo versions, but the typical engineer wouldn't know the details of PKCE.

They would know that it doesn't work though and then we really are in the weeds at that point anyway.

So I am partial to the basic approach of kubelogin though not fixed on the name, just what came naturally.

**Comment by michael-basil** [comment]
Implementation of both flags as optional.

One flag to skip verification and one flag to force a method ...

This is the most robust and durable after thinking it through further.

**Comment by Kerwood** [comment]
"Skip code challenge verification" sounds good to me.

**Comment by michael-basil** [comment]
Wouldn't the proof of key code exchange be the challenge?

This is skipping the method verification.

Perhaps I am understanding this differently?

**Comment by Kerwood** [comment]
tl;dr
I think either
 - there should not be a frontend check for `code_challenge_methods_supported` property
 - or there should be a setting to skip the check
 - or there should be a setting to set the challenge method manually and therefore the check is skipped.

**Comment by michael-basil** [comment]
In a local build of ArgoCD I have been attempting to see if the PKCE flow will actually work when this method verification check is skipped.

Essentially I have commented out the following in utils.ts

``` ts
    // TODO - https://github.com/argoproj/argo-cd/issues/16649 - this check fails for Azure AD
    //if (!authorizationServer?.code_challenge_methods_supported?.includes('S256')) {
    //    throw new PKCELoginError('Authorization Server does not support S256 code challenge method');
    //}
```

I have configured argocd-cm as:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: "false"
  url: http://localhost:4000
  oidc.config: |
    name: Azure Identity
    enablePKCEAuthentication: true
    issuer: https://login.microsoftonline.com/<tenant-id>/v2.0
    clientID: <client-id>
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - email
```

And argocd-rbac-cm as:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, group-of-admins, role:admin
    g, user@company.com, role:admin
  policy.default: ""
  scopes: '[roles, email]'
```

The PKCE flow seems to work fine and a JWT token is on the client called `argocd.token` as I would expect.

However, the _User Info_ screen shows that the user is not logged in and the _Log In_ button keeps re-appearing.

So, it seems that the RBAC configuration is not applied correctly, but I don't see how to debug it (yet).

I have tested the RBAC configuration prior with a non-PKCE OIDC flow without issues, so I am a bit puzzled.

Curious if others have gotten further or would see anything obviously wrong from their Azure configurations.
