### ISSUE TITLE
Sync of managed PersistentVolumes fail on kubernetes 1.29

### ISSUE THREAD

**Issue by weikinhuang** [argoproj/argo-cd#16640]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading cluster to v1.29.0, argo-cd fails to sync applications that manage PersistentVolumes resources with the error `error building typed value from live resource: .status.lastPhaseTransitionTime`.

**To Reproduce**

Using a cluster of kubernetes v1.29.0, and a generic helm chart with just a pv resource:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: example
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: SOME_NFS_SERVER
    path: /example
```

Then have a PVC bind to that pvc with a running pod behind it.

**Expected behavior**

**Screenshots**

**Version**

```shell
Chart version: 5.51.6
Image: quay.io/argoproj/argocd:v2.9.3
```

**Logs**

```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .status.lastPhaseTransitionTime: field not declared in schema
```

**Comment by clearlybaffled** [comment]
As a workaround, you can add a [diff customization](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/) to the Application manifest:
```yaml
spec:
  ignoreDifferences:
  - kind: PersistentVolume
    jsonPointers:
    - /spec/claimRef/resourceVersion
    - /spec/claimRef/uid
    - /status/lastPhaseTransitionTime
```
