### ISSUE TITLE
ArgoCD PostSync job cannot find pipeline in namespace, although it is existing

### ISSUE THREAD

**Issue by johan974** [argoproj/argo-cd#16658]
An ArgoCD PostSync job complains that a pipeline is not existing in a namespace. How come? All resources are existing in the right namespace. 

**To Reproduce**

Try 1: The ArgoCD postsync Job: 

```
    apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: trigger-functional-test-
      annotations:
        argocd.argoproj.io/hook: PostSync
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
            - name: functional-test
              image: quay.io/rhcanada/tkn-cli
              command:
                - tkn
              args:
                - -n
                - test
                - pipeline
                - start
                - postsync-pipeline
                - --param
                - pause-duration="2"
          restartPolicy: Never
      backoffLimit: 0
```

The error message: 

> Error: Pipeline name postsync-pipeline does not exist in namespace test. 

I created my own Docker image with the official 'tkn' image using : [this Dockerfile](https://github.com/tektoncd/plumbing/blob/main/tekton/images/tkn/Dockerfile). Same result!

The Job, Pipeline and the Task are in the 'test' namespace: 

```
$ k get job -n test
NAME                                                  COMPLETIONS   DURATION   AGE
trigger-functional-test-aff65fc-postsync-1703065986   0/1           6m38s      6m38s

$ k get pipeline -n test
NAME                AGE
postsync-pipeline   24m

$ k get task -n test
NAME            AGE
postsync-task   12m
```

I also tried to isolate the issue by making a simple Deployment: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkncli
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tkncli
  template:
    metadata:
      labels:
        app: tkncli
    spec:
      containers:
        - name: tkncli
          image: quay.io/rhcanada/tkn-cli
          imagePullPolicy: IfNotPresent
          command:
            - tkn
          args:
            - -n
            - test
            - pipeline
            - start
            - postsync-pipeline
            - --param
            - pause-duration="2"
```

I can start the pipeline from the commandline: 

   $ tkn -n test pipeline start postsync-pipeline --param pause-duration="2" --showlog

This results in: 

```
PipelineRun started: postsync-pipeline-run-jzfvf
Waiting for logs to be available...
[first-task : say-it] Text one
[second-task : say-it] Text two
```

The result was identical: 

> Error: Pipeline name postsync-pipeline does not exist in namespace test

**Expected behavior**

Just start the pipeline, like the CLI start at the command line. 

**Version**
v2.9.0 (UI)

```shell
Paste the output from `argocd version` here.
```

**Logs**
Additional ... after some time. This is not the root cause. 
```
 container "functional-test" failed with exit code 1
```
