### ISSUE TITLE
[BUG]: The cli command line creates an application that automatically pulls submodules

### ISSUE THREAD

**Issue by freemankevin** [argoproj/argo-cd#16655]
```shell
$ cat .gitmodules

 [submodule "src/projects/onemap"]
    path = src/projects/onemap
    url = http://192.168.1.120/rdcenter/apply/product/productivity/onemapV2.0/geoscene/DataSource/onemap.git
    branch = vue3
[submodule "src/projects/system"]
    path = src/projects/system
    url = http://gitlab+deploy-token-8:DsPyfwgePdv6gA_gcrxz@192.168.1.120/rdcenter/apply/product/productivity/operation/source/system.git
    branch = master
[submodule "src/projects/bpmmng"]
    path = src/projects/bpmmng
    url = http://192.168.1.120/rdcenter/apply/product/resource/zwyth/source/webvue3/system/bpmmng.git
    branch = master
```

argocd create logs:
```bash
$ echo "Syncing application with ArgoCD"
Syncing application with ArgoCD
$ if argocd app list | grep -q $APP_NAME; then # collapsed multi-line command
Application frame-ui does not exist. Creating...
time="2023-12-19T03:24:03Z" level=fatal msg="rpc error: code = InvalidArgument desc = application spec for frame-ui is invalid: \
InvalidSpecError: Unable to generate manifests in k8s/overlays/prod: rpc error: \
code = Unknown desc = failed to initialize repository resources: rpc error: code = Internal desc = Failed to checkout FETCH_HEAD: \
`git submodule update --init --recursive` failed exit status 1: Cloning into '<path to cached source>/src/projects/bpmmng'...\nfatal: \
could not read Username for 'http://192.168.1.120': terminal prompts disabled\nfatal: \
clone of 'http://192.168.1.120/rdcenter/apply/product/resource/zwyth/source/webvue3/system/bpmmng.git' into submodule path\
 '<path to cached source>/src/projects/bpmmng' failed\nFailed to clone 'src/projects/bpmmng'. Retry scheduled\nCloning into \
 '<path to cached source>/src/projects/onemap'...\nfatal: could not read Username for 'http://192.168.1.120': \
 terminal prompts disabled\nfatal: clone of 'http://192.168.1.120/rdcenter/apply/product/productivity/onemapV2.0/geoscene/DataSource/onemap.git' \
 into submodule path '<path to cached source>/src/projects/onemap' failed\nFailed to clone 'src/projects/onemap'. \
 Retry scheduled\nCloning into '<path to cached source>/src/projects/bpmmng'...\nfatal: could not read Username for \
 'http://192.168.1.120': terminal prompts disabled\nfatal: clone of \
 'http://192.168.1.120/rdcenter/apply/product/resource/zwyth/source/webvue3/system/bpmmng.git' \
 into submodule path '<path to cached source>/src/projects/bpmmng' failed\nFailed to clone 'src/projects/bpmmng' a second time, aborting"

```
ci.yaml step: 
```yaml
sync_application:
  image:
    name: $HARBOR_HOST/kubernetes/argocli-git:v2.7.14
  stage: deploy
  variables:
    CI_PROJECT_NAME: 'frame-ui'
  script:
    - echo "Logging in to ArgoCD"
    - >-
      export APP_NAME="$CI_PROJECT_NAME" &&
      echo y | argocd login $ARGOCD_SERVER --password $ARGOCD_PASSWORD --username $ARGOCD_USERNAME
    - echo "Syncing application with ArgoCD"
    - echo "The branch being used is $CI_COMMIT_REF_NAME "
    - export ARGOCD_GIT_MODULES_ENABLED=false
    - >-
      if argocd app list | grep -q $APP_NAME; then
        echo "Application $APP_NAME exists. Syncing..."
        argocd app sync $APP_NAME --prune
      else
        echo "Application $APP_NAME does not exist. Creating..."
        argocd app create $APP_NAME \
        --repo $REPO_URL \
        --revision $CI_COMMIT_REF_NAME \
        --path k8s/overlays/$DEST_ENVIRONMENT \
        --dest-server https://kubernetes.default.svc \
        --sync-policy automated \
        --loglevel debug 
      fi
  needs: ['update_config']
  environment:
    name: prod
    url: https://$ARGOCD_SERVER/kubernetes/cluster/namespaces/$NAMESPACE_NAME
  tags:
    - kubernetes
  # when: manual
  allow_failure: false
```
Positional relationship：
```bash
$ ls -lh .gitmodules 
-rw-r--r-- 1 PC 197121 587 Dec 18 17:07 .gitmodules

$ ls -lh k8s/overlays/prod/
total 5.0K
-rw-r--r-- 1 PC 197121 635 Dec 20 11:12 kustomization.yaml
-rw-r--r-- 1 PC 197121 647 Dec 18 18:39 kustomization.yaml.template
-rw-r--r-- 1 PC 197121  92 Dec 18 18:21 namespace.yaml
-rw-r--r-- 1 PC 197121  86 Dec 20 10:17 replica_count.yaml
-rw-r--r-- 1 PC 197121 312 Dec 18 18:41 resource_requirements.yaml
```
argocd version:
```bash
root@master1:~# argocd version 
argocd: v2.9.2+c5ea5c4
  BuildDate: 2023-11-20T17:37:53Z
  GitCommit: c5ea5c4df52943a6fff6c0be181fde5358970304
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.2+c5ea5c4
  BuildDate: 2023-11-20T17:18:26Z
  GitCommit: c5ea5c4df52943a6fff6c0be181fde5358970304
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

I'm not sure if this is a bug. I couldn't find this documentation resource very well. There is only one disabled parameter: `export ARGOCD_GIT_MODULES_ENABLED=false`, but it doesn't seem to work because my k8s resources have been updated, argocd You only need to know the k8s-related code, and there is no need to pull the code of the business sub-module. How can we avoid this problem?
