### ISSUE TITLE
ArgoCD tries to `helm repo add` OCI repos when getting Helm dependencies

### ISSUE THREAD

**Issue by efbicief** [argoproj/argo-cd#16674]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have an application which deploys a Helm chart defined in git. This chart has a dependency which needs to be pulled from an OCI Helm repository, which I have configured with a repository secret.
Syncing the application fails with: `Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): 'helm repo add helm-oci-repo' failed exit status 1: Error: could not find protocol handler for:`

**To Reproduce**

- Define repository
```yaml
apiVersion: v1
stringData:
  name: helm-oci-repo
  project: default
  type: helm
  url: helm-oci-repo.mydomain.com
  enableOCI: "true"
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io        
  labels:
    argocd.argoproj.io/secret-type: repository
  name: helm-oci-repo
  namespace: argocd
type: Opaque
```
In ArgoCD I can see that it can successfully connect to the repo.

- Define helm chart
  `Chart.yaml`:
```yaml
apiVersion: v2
name: my-chart
description: A Helm wrapper chart for deploying crunchydata postgres operator
type: application
version: 0.1.0
appVersion: "5.5.0"

dependencies:
- name: my-dependency-chart
  version: 1.2.3
  repository: "@helm-oci-repo"
```

- Deploy with applicationset with:
```yaml
    ...
    spec:
      source:
        repoURL: "https://link-to-repo-containing-my-chart"
        targetRevision: HEAD
        path: path/to/my-chart
        helm:
          ...
```
- We see a sync error in argocd:
`Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add docker-virtual ` failed exit status 1: Error: could not find protocol handler for:`

OCI repos are not supported by `helm repo add`, but Argo CD tries to add them.

**Expected behavior**
ArgoCD should not attempt to `helm repo add` any repos with `enableOCI: "true"` set, instead it should just try to pull using the url (prepended with `oci://`)

**Version**

```json
{
    "Version": "v2.9.2+c5ea5c4",
    "BuildDate": "2023-11-20T17:18:26Z",
    "GitCommit": "c5ea5c4df52943a6fff6c0be181fde5358970304",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
Paste any relevant application logs here.
```
