### ISSUE TITLE
Application using Helm valueFiles attribute won't sync

### ISSUE THREAD

**Issue by rwbennett** [argoproj/argo-cd#16693]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

When using .spec.source.helm.valueFiles for an ArgoCD Application, the Application resource never syncs and always shows a diff in which the helm section is not applied.

**To Reproduce**

1. Reference any Helm chart, such as a default 'nginx' one create by `helm create <name>` in an Application, such as this:

argo-cd-apps\apps\nginx.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rwbennett/k8s-deploy.git
    targetRevision: develop
    path: argo-cd-apps/nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
    
```

2. Add an additional values file to the Helm chart e.g. values-env2.yaml. Values don't actually have to differ from the other values.yaml.
3. Create an additional Application that uses the .spec.source.helm.valueFiles attribute to reference the 2nd values file:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rwbennett/k8s-deploy.git
    targetRevision: develop
    path: argo-cd-apps/nginx
  helm:
    # Helm values files for overriding values in the helm chart
    # The path is relative to the spec.source.path directory defined above
    valueFiles:
    - values-env2.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx2
---
apiVersion: v1
kind: Namespace
metadata:
  name:  nginx2
  labels:
    name: nginx2
```

**Expected behavior**

The Application should sync and values-env2.yaml should be used for template values in the 2nd Application's Helm chart.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/4762629/4dccb498-1fdf-46f1-b398-c5257173ee20)

![image](https://github.com/argoproj/argo-cd/assets/4762629/f6757500-cfd9-408d-90cb-b7347dae98e2)

**Version**

```shell
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.9.3+6eba5be
```

**Logs**

```

```
