### ISSUE TITLE
ignoreDifferences with jqExperssions is not able to filter resources by label

### ISSUE THREAD

**Issue by idogada-akamai** [argoproj/argo-cd#16723]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

I am trying to use the jqPathExpressions in an ArgoCD application to ignore .spec.suspend on all cronjobs that have a specific label.
I have tried the following:
```yaml
- group: batch 
  jqPathExpressions: 
    - select(.metadata.labels.controlledByLeader == "true").spec.suspend 
  kind: CronJob
```
Unfortunately that ignores the .spec.suspend field for all the cronjobs that are generated by the application.

**To Reproduce**

1. Install an application that generate cronjobs
2. label some of the cronjobs with `controlledByLeader : "true"`
3. Add the following `ignoreDifferences`
```yaml
ignoreDifferences:
- group: batch 
  jqPathExpressions: 
    - select(.metadata.labels.controlledByLeader == "true").spec.suspend 
  kind: CronJob
```
4. Manually change .spec.suspend for cronjobs that does not have the `controlledByLeader : "true"` label.
Notice how the application is still marked as in sync

**Expected behavior**

Whenever a Cronjobs without the `controlledByLeader : "true"` label is modified in the cluster, that the application will be out of sync.

**Version**
`2.9.3`

```shell
argocd-server: v2.9.3+6eba5be
```

**Comment by idogada-akamai** [comment]
Any news about this?

**Comment by sunsided** [comment]
Just stumbled over the same issue. My use case is replicating secrets into multiple namespaces using Reflector. The mirror target's `data` object gets updated, resulting in a sync loop.

I tried to use the following but it didn't work:

```yaml
- group: ""
      kind: Secret
      jqPathExpressions:
        - select(.metadata.annotations."reflector.v1.k8s.emberstack.com/reflects" != null).data
```

**Comment by idogada-akamai** [comment]
Any update here?

**Comment by crenshaw-dev** [comment]
Also, please try with the most recent stable Argo CD version. There have been recent improvements to `ignoreDifferences`.

**Comment by Goose29** [comment]
I stumbled across the same issue, when trying to make a "dynamic" ignore to avoid bloated Application due to a large `ignoreDifferences` list.

> I am using ApplicationSets, and I don't want to set global ignores for all secrets, or use TemplatePatch / ignoreapplicationdifferences. It should be handled in each scenario to make sure nothing extra is ignored.

> Ultimately something like this: https://github.com/argoproj/argo-cd/issues/12686 would be the holy grail solution.

I have tried something like this which is similarly to the other approaches in this issue:

```yaml
ignoreDifferences:
  - kind: Secret
    jqPathExpressions:
      - . | select(.metadata.annotations.ignore) | .data
```

Which results in the following:
![image](https://github.com/user-attachments/assets/554529a1-078d-4cf7-bb8a-d3c2f76d5ee9)

I would have expected it to outright ignore the difference, instead it thinks it the .data.X doesn't exist then wants to add them, even though they are already present. This makes it hard to perform secret injection in ApplicationSets without using global ignores, or TemplatePatches.

**Comment by AvihaiSam** [comment]
i have the same issue. I'm trying to ignore HPA changes if scaleops is configured .

what argo does is as @Goose29 mentioned. it can't find the actual data and wants to set the original data

```yaml
ignoreDifferences:
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jqPathExpressions:
      - >-
        select(.metadata.annotations["analysis.scaleops.io/original-metrics"] !=
        null) | .spec.metrics[].resource.target
```
