### ISSUE TITLE
K8s resources are deleted when being moved from one ApplicationSet to another (prune is set to false)

### ISSUE THREAD

**Issue by algo7** [argoproj/argo-cd#16721]
### Discussed in https://github.com/argoproj/argo-cd/discussions/6676

<div type='discussions-op-text'>

<sup>Originally posted by **weichuliu** July  9, 2021</sup>
Hi,

In our deployment, we have an ArgoCD applicationset. It is used to deploy Consul via Helm.
We were working on splitting it into 3 applicationsets per staging level (inf, qa, prod).

During this splitting, we expected the old resources to be taken over by the new applicationsets without recreation. However, the resources were actually deleted then recreated in ArgoCD, even though the `prune` are all set to `false`. And it caused downtime.

Can you help to take a look about what did we do wrong? Is there a way we can move resources between applications without deleting it?

Thanks very much.

Here is how the manifest looks like:

1. We have this `meta` app at the path `argocd/consul.yaml` that applies YAMLs under `argocd/consul/`.

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-consul-k8s-meta
spec:
  project: argo-projects
  destination:
    name: ...
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  source:
    repoURL: [same-repo]
    targetRevision: master
    path: argocd/consul
```

2. At the path `argocd/consul/consul-app.yaml`, we used to have a single monolithic ApplicationSets:

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consul
spec:
  generators:
    - list:
        elements:
        - cluster: prod1
          url: ...
        - cluster: prod2
          url: ...
        - cluster: testing1
          url: ...
        - cluster: testing2
          url: ...
  template:
    metadata:
      name: consul-{{cluster}}
    spec:
      project: consul
      source:
        helm:
          releaseName: cv-consul
          valueFiles:
            - values-{{cluster}}.yaml
        path: manifests/consul/transitional
        repoURL: [same-repo]
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: consul
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

3. After splitting, it looks like this:

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consul
spec:
  generators:
    - list:
        elements:
        - cluster: prod1
          url: ...
        - cluster: prod2
          url: ...
        # - cluster: testing1
        #   url: ...
        # - cluster: testing2
        #   url: ...
  template:
    metadata:
      name: consul-{{cluster}}
    spec:
      project: consul
      source:
        helm:
          releaseName: cv-consul
          valueFiles:
            - values-{{cluster}}.yaml
        path: manifests/consul/transitional
        repoURL: [same-repo]
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: consul
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consul-testing
spec:
  generators:
    - list:
        elements:
        - cluster: testing1
          url: ...
        - cluster: testing2
          url: ...
  template:
    metadata:
      name: consul-{{cluster}}
    spec:
      project: consul
      source:
        helm:
          releaseName: cv-consul
          valueFiles:
            - values-{{cluster}}.yaml
        path: manifests/consul/transitional-testing
        repoURL: [same-repo]
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: consul
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```</div>

**Comment by algo7** [comment]
Simply changing the directory/path in the application set will also cause resource recreation.

If one has some kube manifest in directory `root/a/b/*`, one moves all the manifests to `root/a/c*`, and  edit the application set manifest like below will cause all the defined resources to be recreated even though nothing has changed in reality apart from the directory structure.

```yml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: git@github.com:someone/someproject.git
        revision: HEAD
        directories:
          - path: root/a/b/* # If changed to root/a/c the resources will be recreated
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: myproject
      source:
        repoURL: git@github.com:someone/someproject.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: my-namespace
        namespace: my-cluster
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
```

**Comment by rumstead** [comment]
By removing the elements in the list generator, I would expect the ApplicationSet to delete the child Applications. By default, Applications have [finalizers set on them that will delete all deployed resources](https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#about-the-deletion-finalizer) (besides CRDs). You can control this behavior by [removing the finalizer ](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Application-Deletion/) or at the [individual resource level](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-resource-deletion). 

Similar to the list generator, in the path example, it looks like your Application names are changes which results in them being deleted and recreated, which in turn happens to all the underlying resources.
```
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
```

Prune will only prevent resources from deleting that were removed from Git, more or less.
