### ISSUE TITLE
Mulitsource not working with private git repo

### ISSUE THREAD

**Issue by karthik1710** [argoproj/argo-cd#16747]
### Discussed in https://github.com/argoproj/argo-cd/discussions/16746

<div type='discussions-op-text'>

<sup>Originally posted by **karthik1710** January  4, 2024</sup>
Hi All,

I'm trying deploy a helm chart with custom values ref: from private git repo. Both helm chart and git repo are private and repositories are already added in argocd.

Below is my argocd setup,

```shell
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```
My application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fr-eb-mongodb-dev
spec:
  destination:
    name: ''
    namespace: fr-mongodb-dev
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://gitlab.com/api/v4/projects/xxxx/packages/helm/stable'
    chart: mongodb
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - $values/custom-value/values-fr.yaml
  - repoURL: 'https://gitlab.com/xxxx/eb-xxxx/exxx.git'
    targetRevision: custom-values
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```
In the application.yaml, I trying to deploy private helm chart with custom values from git repository. But after deployment I could see Argocd is not getting custom values from the referred repo.

Thanks in advance. :raised_hands:</div>

**Comment by karthik1710** [comment]
@ishitasequeira Can you help me in this? Thanks

**Comment by stepa-ict** [comment]
I can confirm the issue. Just happening for a multi-sources app, and on different argocd versions: v2.9.3 and v2.8.5.
Also happens with the repository and credentials template.
How should we proceed with this issue?

**Comment by stepa-ict** [comment]
Also, we've tried to downgrade argocd to v2.7.8 and use ssh auth method, but no luck.
Still getting the same issue. 
<img width="967" alt="image" src="https://github.com/argoproj/argo-cd/assets/12424728/7fb9f75d-8ed5-437f-a7b2-db9d504e2c72">

**Comment by ishitasequeira** [comment]
Thanks @karthik1710 and @stepa-ict for raising the issue. I will try reproducing the issue on my end.

**Comment by stepa-ict** [comment]
@ishitasequeira Do you have any info regarding this issue? It becomes very important. We've switched completely to multi-source apps, so this is a huge problem. Thanks for understanding.
If we can help anyhow, please let us know.

**Comment by ishitasequeira** [comment]
Apologies for a delayed response. I tried reproducing the issue, and was able to see an error when used `chart` field. Try using `path` field instead. Below example worked for me and should resolve the issue you are seeing.

```yaml
sources:
  - repoURL: 'git@github.com:ishitasequeira/multi-source-test.git'
    path: helm-guestbook
    targetRevision: main
    helm:
      valueFiles:
        - $values/values-guestbook.yaml
  - repoURL: 'git@github.com:ishitasequeira/multi-source-values.git'
    targetRevision: main
    ref: values
```
