### ISSUE TITLE
Error when declaratively adding a new AKS cluster (using MSI)

### ISSUE THREAD

**Issue by 1aziz** [argoproj/argo-cd#16759]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to add a new AKS cluster [declaratively](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#aks) using kubelogin, but I'm getting the following error:
```
level=error msg="could not unmarshal cluster secret aks-workload-dev-secret-manual"
```

This is how my cluster Secret looks like:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: aks-workload-dev-secret-manual
  namespace: argocd
stringData:
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "env": {
          "AZURE_CLIENT_ID": REDACTED,
          "AAD_LOGIN_METHOD": "msi"
        },
        "args": ["azure"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": true,
        "caData": REDACTED
      }
    }
  name: aks-workload-dev
  server: REDACTED
type: Opaque
```
I have already added the required configs to the deployment templates (for both the server and app controller) to use kubelogin: 

![Screenshot 2024-01-05 at 15 55 04](https://github.com/argoproj/argo-cd/assets/62608112/da083441-398b-4ca4-be5a-cff493fe3bf6)

![Screenshot 2024-01-05 at 16 00 40](https://github.com/argoproj/argo-cd/assets/62608112/6de1ee9b-2805-4e9e-9e8c-c8aef79f726f)

The error could be caused by  a formatting issue (maybe with my JSON in the Secret manifest), or I might have misconfigured something. I'd appreciate if someone could help, please.

**To Reproduce**

- Run the secret above with own values (replaced by REDACTED).

**Expected behavior**

- The cluster is added in Argo CD

**Version**

```shell
v2.9.3+6eba5be
```

**Logs**
```
level=error msg="could not unmarshal cluster secret aks-workload-dev-secret"
```

**Comment by 1aziz** [comment]
So, it seems I should use the `kubelogin` command directly. 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aks-workload-dev-secret
  namespace: argocd
data:
  config: {
  "execProviderConfig": {
    "command": "kubelogin",
    "args": [
      "get-token",
      "--login=msi",
      "--server-id=REDACTED",
      "--client-id= REDACTED"
    ],
    "apiVersion": "client.authentication.k8s.io/v1beta1"
  },
  "tlsClientConfig": {
    "insecure": false,
      "caData": REDACTED
  }
}  name: aks-workload-dev
  server: REDACTED
type: Opaque
```
