### ISSUE TITLE
Argo CD reformats own ConfigMap which make it is difficult to manage Argo CD declaratively

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1676]
**Describe the bug**
Argo CD reformats own ConfigMap while updating settings. This makes it is difficult to manage it argocd deployment declaratively.

**To Reproduce**
If we cannot reproduce, we cannot fix! Steps to reproduce the behavior:
1. Deploy self-managed argocd and include repos into config map
2. Try to update settings imperatively (e.g. reset admin password)
3. See the config map reformatted

**Screenshots**
![image](https://user-images.githubusercontent.com/426437/58825849-2b828800-85f4-11e9-8e9f-b84d0c3b2a17.png)

**Version** v1.0.1

**Comment by kwladyka** [comment]
```
configMapGenerator:
- name: argocd-cm
  behavior: replace
  files:
  - argocd-cm/repositories
  - argocd-cm/helm.repositories
```

exact code in kustomize which generate what is on screenshoot.
