### ISSUE TITLE
ApplicationSet Generator combine values into single context

### ISSUE THREAD

**Issue by MoonChel** [argoproj/argo-cd#16760]
# Summary

It would be nice to have some generator that can combine multiple git files into single context. 

# Motivation

We have matrix generator, merge generator based on key and we might be missing simple merge-everything-without-any-rules-into single context generator.

Here is an example:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "app-set-1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:<org>/dev-values.git
        revision: master
        combine: true
        files:
          - path: "project-1/version.yaml"
          - path: "project-2/version.yaml"
  template:
    spec:
      sources:
        - repoURL: git@github.com:<org>/project-1.git
          targetRevision: master
          path: project-1/helm
          helm:
            values: |
              version: {{ .project1.version }}      

        - repoURL: git@github.com:pmedianetwork/project-2.git
          targetRevision: master
          path: project-2/helm
          helm:
            values: |
              version: {{ .project2.version }}

        - repoURL: git@github.com:<org>/project-3.git
          targetRevision: master
          path: project-3/helm
          helm:
            values: |
              project2:
                version: {{ .project2.version }}                                          
              project1:
                version: {{ .project1.version }}                                                          
```

Currently this will be possible through an Application with values injected on a ArgoCD level, so those will be available in all managed apps. 

# Proposal

I think it's easier to take a shortcut and extend git generator or add new generator based on git generator that will combine provided files.
