### ISSUE TITLE
ArgoCD doesnt see service as Out of Sync after manually adding another port

### ISSUE THREAD

**Issue by ginokok1996** [argoproj/argo-cd#16771]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have a service that we manage with ArgoCD that has 1 port (8080) defined in the manifest file.
If we edit the manifest file by hand to add another port entry, ArgoCD doesn't see this difference and stays in sync.
We would expect that the diff on the live and desired manifest would show the newly added port.

**To Reproduce**

1. Create the service with one port defined.
``` yaml
kind: Service
apiVersion: v1
metadata:
  name: component-dummy
  labels:
    app: component-dummy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: component-dummy
  type: ClusterIP
```

2. After argoCD manages the service manually edit the service to add another port.
``` yaml
kind: Service
apiVersion: v1
metadata:
  name: component-dummy
  labels:
    app: component-dummy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: sidecar
      protocol: TCP
      port: 15020
      targetPort: 15020
  selector:
    app: component-dummy
  type: ClusterIP
```

3. Check the argocd UI or via CLI to see that the service is still in sync

**Expected behavior**

Argocd notices the difference between the desired and live manifest of the service and goes out of sync because the ports are different

**Version**

```shell
argocd: v2.6.7+unknown
  BuildDate: 2023-05-10T05:05:38Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.13+unknown
  BuildDate: 2023-07-24T20:29:56Z
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 1970-01-01T00:00:00Z
  Helm Version: v3.10.0+ge534a5d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```
