### ISSUE TITLE
ApplicationSet Controller with git Generator not updating Application on webhook

### ISSUE THREAD

**Issue by rivera-bl** [argoproj/argo-cd#16787]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ApplicationSet Controller webhook doesn't update Application when using git Generator with directories. Despite the ApplicationSet Controller receiving the Webhook, logs read "unchanged Application"

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-test
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: REDACTED
      revision: HEAD
      directories:
      - path: platform/gha-controller/*
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.path.basename}}'
      labels:
        name: '{{index .path.segments 1}}-{{.path.basename}}'
    spec:
      project: '{{index .path.segments 0}}'
      source:
        repoURL: REDACTED
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: '{{.path.basename}}'
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - ServerSideApply=true
```

**To Reproduce**

1. Configure Github Webhook for ApplicationSet Controller
2. Create ApplicationSet with gitGenerator
3. Make changes on the manifests that reference the Application
4. Push your changes to remote repository

**Expected behavior**

1. The Application should be created
2. The Application should be updated everytime a new push event happens on the git repo

**Screenshots**

**Version**

```shell
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

ApplicationSet Controller logs

```
time="2024-01-09T01:40:20Z" level=info msg="Received push event repo: REDACTED, revision: main, touchedHead: true"
time="2024-01-09T01:40:20Z" level=info msg="refresh ApplicationSet argocd/argocd-test from webhook"
time="2024-01-09T01:40:22Z" level=info msg="applications result from the repo service" allPaths="[... platform/gha-controller platform/gha-controller/melchior ...]" pathParamPrefix= repoURL="REDACTED" revision=HEAD total=38
time="2024-01-09T01:40:22Z" level=info msg="generated 1 applications" generator="REDACTED"
time="2024-01-09T01:40:22Z" level=info msg="unchanged Application" app=gha-controller-melchior appSet=argocd-test
time="2024-01-09T01:40:22Z" level=info msg="end reconcile" applicationset=argocd/argocd-test requeueAfter=3m0s
```
