### ISSUE TITLE
Multiple sources with Kustomize

### ISSUE THREAD

**Issue by mihaigalos** [argoproj/argo-cd#16790]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Multiple sources for kustomize seem to not work using `v2.9.3`.

**To Reproduce**

I'm using a generator with the following file hierarchy:
```
.
├── all
│   ├── README.md
│   └── accounts
│       └── proj1.yaml
├── bootstrap.yaml
└── core
    ├── proj-externaldns
    │   ├── component_kustomize.yaml
    │   ├── kustomization.yaml
    │   └── stages
    │       └── proj1-dev
    │           ├── deploymentPatch.yaml
    │           └── kustomization.yaml
    └── dev-applicationSet.yaml
```

`core/dev-applicationSet.yaml` (simplified):
```yaml
- git:
      requeueAfterSeconds: 300
      repoURL: 'https://do.main/company/proj-mono.git'
      revision: HEAD
      files:
      - path: 'core/*/component_kustomize.yaml'
      template:
        metadata: {}
        spec:
          project: proj
          sources:
          - repoURL: '{{.repoURL}}'
            targetRevision: '{{.targetRevision}}'
            path: deployment
          - repoURL: 'https://do.main/company/proj-mono.git'
            targetRevision: HEAD
            path: 'core/{{.name}}/stages/proj1-dev'
          destination: {}
```

This does generate the `proj-externaldns` app, but does not add the overlays in `core/{{.name}}/stages/proj1-dev`.

**Expected behavior**

Overlays get added using multiple sources.

**Screenshots**

**Version**

```shell
v2.9.3
```

**Logs**
-
