### ISSUE TITLE
Sequencially evaluate and templetize files in git generator files

### ISSUE THREAD

**Issue by mihaigalos** [argoproj/argo-cd#16814]
# Summary

Sequencially evaluate and templetize files in git generator files.

# Motivation
I would like to use a git generator to specify a `files` list and that list to be sequencially evaluated and values defined in previous files to be templateable in the current file list element

# Proposal

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "dev-appset"
  namespace: proj-argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      requeueAfterSeconds: 300
      repoURL: 'https://do.main/orga/proj-mono.git'
      revision: HEAD
      files:
      - path: 'config.yaml'
      - path: '{{.clusterName}}/*/component_kustomize.yaml' # clusterName defined in config.yaml
```
