### ISSUE TITLE
Can not access the ArgoCD when change the ingress path to /argo

### ISSUE THREAD

**Issue by songleo** [argoproj/argo-cd#16811]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have deployed the ArgoCD v2.9.3 in my local kind cluster. I can access ArgoCD ( https://www.private-cloud.com/ ) via the following ingress config:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  rules:
  - host: www.private-cloud.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argocd-server
            port:
              number: 443

```
<img width="1055" alt="image" src="https://github.com/argoproj/argo-cd/assets/6408381/1096ef29-e271-4136-b2a3-7234ecc9eea0">

But if I want to change the ingress `path` to `/argocd`. I can not access the ArgoCD via https://www.private-cloud.com/argocd.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: / # change here
spec:
  ingressClassName: nginx
  rules:
  - host: www.private-cloud.com
    http:
      paths:
      - pathType: Prefix
        path: /argocd # change here
        backend:
          service:
            name: argocd-server
            port:
              number: 443

```
<img width="1181" alt="image" src="https://github.com/argoproj/argo-cd/assets/6408381/82b02ee1-5269-4570-bb5e-20e201122c9c">

Does anyone know how to configure it? thank you.

**Expected behavior**
I should have access to ArgoCD from https://www.private-cloud.com/argocd

**Comment by FredrikAugust** [comment]
I think this is because it by default tries to fetch resources from `/` at the host. That's why it works to serve it from `argocd.private-cloud.com` by default, and not `private-cloud.com/argocd`. You can change this with the `--basehref` and `--rootpath` options: https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-server/#options.

**Comment by songleo** [comment]
Thank you so much @FredrikAugust Now I can access this page, but I found another issue. seems I can not login to the console. the console always auto-logout. see the record from here: http://g.recordit.co/j1xExbe1de.gif  

error log:

```
time="2024-01-10T10:40:39Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Create grpc.service=session.SessionService grpc.start_time="2024-01-10T10:40:39Z" grpc.time_ms=789.488 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2024-01-10T10:40:41Z" span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=0.936 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=2.406 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=application.ApplicationService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=0.466 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=0.617 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.content= grpc.service=session.SessionService grpc.start_time="2024-01-10T10:40:41Z" span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=1.497 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.content= grpc.service=session.SessionService grpc.start_time="2024-01-10T10:40:41Z" span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=1.168 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=3.293 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=3.309 span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" span.kind=server system=grpc
time="2024-01-10T10:40:41Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2024-01-10T10:40:41Z" grpc.time_ms=2.716 span.kind=server system=grpc
```

**Comment by FredrikAugust** [comment]
@songleo Great! The second problem I don't have any experience with sadly.

**Comment by songleo** [comment]
@FredrikAugust Thank you, now I have fixed this issue. need to add the follow lines to ingress:

```
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
```
