### ISSUE TITLE
ApplicationSet Git Generator documentation is incorrect

### ISSUE THREAD

**Issue by soggycactus** [argoproj/argo-cd#16819]
ArgoCD version: v2.9.3

Following the instructions in https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/applicationset/Generators-Git.md yields a broken `ApplicationSet` spec. Specifically, all of the parameters cannot be accessed using `.path`, they must use `path`. For example, I applied the below `ApplicationSet` spec:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster-type: foo
          - git:
              repoURL: https://github.com/foo/bar
              revision: HEAD
              directories:
                - path: apps/*
  template:
    metadata:
      name: "{{nameNormalized}}-{{.path.basenameNormalized}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/foo/bar
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: '{{server}}'
```
which resulted in the error condition:

```
{ErrorOccurred Application.argoproj.io "dev-cluster-{{.path.basenameNormalized}}" is invalid: metadata.name: Invalid value: "dev-cluster-{{.path.basenameNormalized}}": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 2024-01-10 17:57:54 -0600 CST True UpdateApplicationError}
```

After a bit of guess & check, the following manifest works as intended:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster-type: foo
          - git:
              repoURL: https://github.com/foo/bar
              revision: HEAD
              directories:
                - path: apps/*
  template:
    metadata:
      name: "{{nameNormalized}}-{{path.basenameNormalized}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/foo/bar
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: '{{server}}'
```

`.path.path` cannot be accessed, and instead just `path` must be used. 

This same issue is also prevalent when using `pathParamPrefix` - if I set this to `app` for example, I cannot access parameters using `.app`, it must be `app`
