### ISSUE TITLE
Failing to pull charts from GCP Artifact Registry

### ISSUE THREAD

**Issue by romanvogman** [argoproj/argo-cd#16836]
**Describe the bug**

* Created a project `foo` in argocd that points to a github repo
* Creating an app from `foo/chart` that contains dependency charts from gcp artifact registry in Chart.yaml
* Argocd uses a service account with access to the artifact registry - has artifact registry admin permissions 
* App creation fails on 403 forbidden when running `helm dependency build` 

Argocd uses the same service account to connect to other clusters (argocd-fleet-admin) which works fine (managed to install app when only pointing it to a chart in github repo without oci dependencies)

service account annotations in the helm chart:
```
    controller:
      serviceAccount:
        annotations:
          "iam.gke.io/gcp-service-account": "argocd-fleet-admin@project.iam.gserviceaccount.com"
    server:
      serviceAccount:
        annotations:
          "iam.gke.io/gcp-service-account": "argocd-fleet-admin@project.iam.gserviceaccount.com"
```

no clue what's missing since the SA seems to be in use to access other clusters, and also has the needed permissions to artifact registry

**Version**

```shell
used v2.9 and also tried v2.7.7
```

**Logs**
```
Unable to generate manifests in argocd/dev: rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download oci://us-central1-docker.pkg.dev/repo/chart_dir/chart: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

**Comment by dev-whoan** [comment]
Any Updates?

**Comment by dev-whoan** [comment]
@romanvogman I just solved this issue adding username and password with created Google Service Account.

You can follow [this docs](https://cloud.google.com/artifact-registry/docs/helm/authentication?hl=ko#macos).

here is one example that how I solved;

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gar-config-chart
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
stringData:
  enableOCI: "true"
  name: config-chart
  type: helm
  url: asia-northeast3-docker.pkg.dev/my-project/my-repo/config-chart
  username: _json_key         # < From here to the EOF is what I did.
data:
  password: BASE64_FROM_SERVICE_ACCOUNT_KEY_JSON
```
