### ISSUE TITLE
Job not created with Sync hook

### ISSUE THREAD

**Issue by emedvesApk** [argoproj/argo-cd#16835]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using the [HAProxy ingress controller helm chart](https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress) deployed with ArgoCD, in an App-of-Apps pattern. We installed ArgoCD with the chart version 5.51.6, repo https://argoproj.github.io/argo-helm

The HAProxy chart declares a Job annotated with a sync hook and delete policy. When upgrading or downgrading the chart version, sometimes the job is not recreated by ArgoCD. When it happens, Even deleting and recreating the child Application does not make the job reappear.
I tried to pinpoint a reproducible scenario, but I was unable to. Restarting the argocd-server deployment seems to fix the issue.

**To Reproduce**

Install HAproxy Helm chart with an Argo Application managed by another Application in an App-of-Apps pattern.
This is an extract of our child App:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-haproxy
  namespace: argocd
spec:
  destination:
    namespace: ingress-haproxy
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /operation
      kind: Application
  project: default
  source:
    chart: kubernetes-ingress
    repoURL: 'https://haproxytech.github.io/helm-charts'
    targetRevision: 1.35.5
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
      - Validate=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=false
      - ServerSideApply=true
      - FailOnSharedResource=false
      - RespectIgnoreDifferences=true
      - CreateNamespace=false
```

**Expected behavior**

The job resource is created again every time we change/recreate the application.

**Screenshots**

**Version**

```shell
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
