### ISSUE TITLE
Additional values not working with git generator templates

### ISSUE THREAD

**Issue by mihaigalos** [argoproj/argo-cd#16830]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using a generator in a monorepo containing the appset and custom overlays.

`component_helm.yaml`:

```yaml
clusters:
  dev:
    name: proj-dex
    namespace: proj-dex
    targetRevision: 2023.51.1
    repoURL: https://do.main/orga/proj-dex-manifest.git
```

`applicationSet.yaml`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "dev-appset"
  namespace: proj-argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
   - git:
      requeueAfterSeconds: 300
      repoURL: 'https://do.main/orga/proj-mono.git'
      revision: HEAD
      files:
      - path: 'core/*/component_helm.yaml'
      values: # <--------------- This does not get applied in [1]
        stage: 'dev1'
        name: '{{.clusters.dev.name}}'
        namespace: '{{.clusters.dev.namespace}}'
      template:
        metadata: {}
        spec:
          project: proj
          sources:
          - repoURL: '{{.clusters.dev.repoURL}}'
            targetRevision: '{{.clusters.dev.targetRevision}}'
            path: deployment
            helm:
              ignoreMissingValueFiles: true
              valueFiles:
              - $values/all/accounts/account1.yaml
              - $values/{{index .path.segments 0}}/{{index .path.segments 1}}/values.yaml
              - $values/{{index .path.segments 0}}/{{index .path.segments 1}}/clusters/dev.yaml
              - $values/{{index .path.segments 0}}/{{index .path.segments 1}}/stages/dev-dev1.yaml
          - repoURL: 'https://do.main/orga/proj-mono.git'
            targetRevision: HEAD
            ref: values
          destination: {}
template:
    metadata:
      name: '{{.values.name}}' # <----------------- [1] Not getting applied here. 
    spec:
      project: 'proj'
      source:
        targetRevision: '{{.clusters.dev.targetRevision}}'
        repoURL: '{{.clusters.dev.repoURL}}'
        path: 'deployment'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.values.stage}}-{{.values.namespace}}' # <----------------- [1] Also not getting applied here.
```

**To Reproduce**
See above appset.

**Expected behavior**

Additional values as specified [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#pass-additional-key-value-pairs-via-values-field_1) are consumed by the top-level template.
**Screenshots**

**Version**

```shell
v2.9.3
```

**Logs**

**Comment by rojspencer-e3** [comment]
Ran in to this myself sort of.

I can set values but none of the data in the file that was found is available.  

For example, only way I could see what was going on was to use `.` and use the value in a helm paramter to see what showed up.
```
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: https://github.com/mycompany/argocd-infra
              revision: HEAD
              files:
                # find all argocd.json files
                - path: 'components/**/argocd.json'
              values:
                # enabled: '{{ or (dig "clusters" .name "enabled" false .) (dig "clusters" "all" "enabled" false .) }}'
                enabled: '{{ . }}'
# ...snip
        - repoURL: '{{ .source.repoURL }}'
          targetRevision: '{{ dig "clusters" .name "chartRevision" .source.targetRevision . }}'
          chart: '{{ dig "source" "chart" "" . }}'
          path: '{{ dig "source" "path" "" . }}'
          helm:
            version: v3
            releaseName: '{{ dig "source" "chart" "" . }}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{ .path.path }}/values.yaml
              - $values/{{ .path.path }}/values.{{ .name }}.yaml
            parameters:
              - name: "global.additionalLabels.argocd-enabled"
                value: '{{ .values.enabled }}'
```

This is what got set for `.values.enabled`:
```
            map[metadata:map[annotations:map[managed-by:argocd.argoproj.io]
            labels:map[argocd.argoproj.io/secret-type:cluster]]
            name:deployment-prod nameNormalized:deployment-prod
            server:https://kubernetes.default.svc]
```
In other words, it only saw values from the cluster generator, nothing from the `argocd.json` file

**Comment by askulkarni2** [comment]
@ixxeL2097 using yaml instead of json worked for me. I am not too familiar with argocd source but looking at the code [here](https://github.com/argoproj/argo-cd/blob/6ca29a3c0b9a4baa089bbe3bb83104461d558be8/applicationset/generators/git.go#L140) I am not even sure if json is supported.

**Comment by mogopz** [comment]
I seem to be hitting the same issue on v2.10.3.

This is my ApplicationSet:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters: {}
            selector:
              matchExpressions:
                - key: server
                  operator: NotIn
                  values:
                    - https://kubernetes.default.svc
          - git:
              repoURL: https://github.com/org/repo
              revision: HEAD
              files:
                - path: 'charts/**/config.yaml'
              values:
                enabled: '{{ dig "clusters" .name "enabled" false . }}'
      # This doesn't work because the values from config.yaml are not available
      selector:
        matchLabels:
          enabled: "true"
  template:
    metadata:
      name: '{{ .name }}-promtail'
    spec:
      project: cluster-services
      sources:
        - repoURL: https://github.com/org/repo
          targetRevision: '{{ dig "clusters" .name "valuesRevision" "HEAD" . }}'
          ref: values
        - repoURL: '{{ .source.repoURL }}'
          targetRevision: '{{ dig "clusters" .name "chartRevision" .source.targetRevision . }}'
          chart: '{{ default "" .source.chart }}'
          path: '{{ default "" .source.path }}'
          helm:
            valueFiles:
              - $values/{{ .path.path }}/values/values.yaml
              - $values/{{ .path.path }}/values/{{ .metadata.labels.environment }}/{{ .name }}.yaml
      destination:
        server: '{{ .server }}'
        namespace: '{{ .destination.namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - FailOnSharedResource=true
```

And this is my config.yaml:
```yaml
source:
  repoURL: https://grafana.github.io/helm-charts
  chart: promtail
  targetRevision: 6.15.5
destination:
  namespace: monitoring
clusters:
  my-cluster:
    chartRevision: 6.15.0
    enabled: true
```

I did the same trick @rojspencer-e3 shared and can confirm it only seems to have the values from the cluster generator.

I was following an article with the same setup that was posted Nov 7th 2023 so it must be a very recently introduced bug ([link](https://medium.com/@geoffrey.muselli/argocd-multi-cluster-helm-charts-installation-in-mono-repo-0a406ff7c578))

**Comment by kaos** [comment]
I've found the templating logic broken when using nested generators in combination with gotTemplate syntax, in that the templates are evaluated multiple times (once for each generator, twice for the `.values` block, if any) so you'd need to add extra levels of escaping.

I've gone through iterations running with a custom argo unit test to find out how many levels of nested I need to escape for our use case, and came up with this, for your reference:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ...
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              values:
                deployment_area: "{{.nameNormalized}}"
          - matrix:
              generators:
                - scmProvider:
                    cloneProtocol: https
                    github:
                      organization: acme
                      api: https://api.github.com/
                      appSecretName: some-credentials
                    filters:
                      - repositoryMatch: "-config$"
                        labelMatch: gitops-deploy-repo
                        pathsExist: [apps]
                    values:
                      project: |-
                        {{`{{ .repository | replace "-config" "" }}`}}
                - git:
                    repoURL: "{{`{{ .url }}`}}"
                    revision: "{{`{{ .branch }}`}}"
                    files:
                      - path: "apps/*/envs/*/{{ .values.deployment_area }}/values.yaml"
                    values:
                      app: |-
                        {{"{{`{{ index .path.segments 1 }}`}}"}}
                      deployment_environment: |-
                        {{"{{`{{ index .path.segments 3 }}`}}"}}
                      # name: `<app>-<deployment_environment>`
                      name: |-
                        {{"{{`{{ index .path.segments 1 }}-{{ index .path.segments 3 }}`}}"}}
                      # default namespace_suffix: `-<deployment_environment>`
                      namespace_suffix: |-
                        {{"{{`{{ if ne ($x := (dig \"namespace_suffix\" nil .)) nil }}{{ $x }}{{ else }}-{{ index .path.segments 3 }}{{ end }}`}}"}}
                      variant: |-
                        {{"{{`{{ dig \"variant\" \"other\" . }}`}}"}}
  template:
    metadata:
      name: "{{ .values.name }}"
      labels:
        app: "{{ .values.app }}"
# ...
```

I put as much as possible into the `.values` block to make it easier to reference in the template, and also to reduce churn if we need to change stuff.

**Comment by blade5502** [comment]
Running into exact the same issue with argo v2.10.4, values from config.json git generator files are not accessible within the generator, accessing the variables in template works fine though.

Have exactly the same use case of a post generator selector to enable/disable an application for a particular cluster

`spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              files:
                - path: cluster-testing/**/.argocd.json
              repoURL: git@github.com:user/my_repo.git
              revision: HEAD
              values:
                enabled: '{{ dig "cluster" .name "enabled" false . }}'
      selector:
        matchLabel:
          enabled: "true"
`

**Comment by carlcauchi** [comment]
@blade5502 @mogopz I have the same issue and same use case as yours - did you manage to resolve this by any chance?

**Comment by memelet** [comment]
@blade5502 is my use case as well. Trying to conditionally enable based on a value in the git discovered file. I can of course use the values in the template, but the selector never matches.

**Comment by mogopz** [comment]
> Have exactly the same use case of a post generator selector to enable/disable an application for a particular cluster



> @blade5502 @mogopz I have the same issue and same use case as yours - did you manage to resolve this by any chance?

For now I'm just filtering clusters in the Cluster Generator until this gets fixed.

**Comment by h4ckroot** [comment]
Hey, any update on this? I am having the same issue: values does not show any values from the passed in config file!

**Comment by pydolan** [comment]
One hacky workaround for the "enabled" filtering is to use nested matrix-generators with a final list-generator for defining the "enabled" parameter. 

Here's an example using cluster configs. I'm using an "env" annotation on the cluster-config, but using the cluster-config name (e.g., ".name") should work as well.

```yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
  annotations:
    my-org.com/cluster-env: dev
type: Opaque
stringData:
  name: dev-cluster
  server: https://dev-cluster.my-org.com

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - clusters: {}
                - git:
                    repoURL: https://github.com/my-org/gitops-repo.git
                    revision: main
                    files:
                      - path: 'apps/*/.argocd.yaml'
          - list:
              elements:
                - clusterEnv: '{{ index .metadata.annotations "my-org.com/cluster-env" }}'
                  appEnabled: '{{ dig "clusters" (index .metadata.annotations "my-org.com/cluster-env") "enabled" false . }}'
      selector:
        matchLabels:
          appEnabled: "true"
  template:
    metadata:
    ...
```

(Also, +1 for `.argocd.yaml` instead of `.argocd.json`)

**Comment by cgarcia-l** [comment]
Same case and same issue... I can't find a way to solve it

**Comment by ArieLevs** [comment]
> Ran in to this myself sort of.

@rojspencer-e3 I have exactly same use case like you described, trying to use cluster + git generators, when the values from git should override all others. with no success, it just does not work.

were you able to find a workaround?

**Comment by irizzant** [comment]
See also https://github.com/argoproj/argo-cd/issues/17610, it's not possible to use templating in selectors either.
Don't know if it may be related to this.

**Comment by reedjosh** [comment]
https://github.com/argoproj/argo-cd/issues/14152

I think setting `applyNestedSelectors: true` may solve some of these issue.

**Comment by irizzant** [comment]
I think `applyNestedSelectors` works in the nested matrix generator, not in the external 
```
- matrix:
    generators:
      - matrix:
          generators:
            - list
                elements:
                  - # (...)
              selector: { } # Only applied when applyNestedSelectors is true

```

**Comment by blade5502** [comment]
Could only get it to work with the workaround described above by @pydolan using an extra list generator:

```yaml
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - clusters: {}
                - git:
                    files:
                      - path: cluster-apps/**/.argocd.json
                    repoURL: git@github.com:example/repo.git
                    revision: HEAD
                    values:
                      enabled: '{{ .source.repoURL }}'
          - list:
              elements:
                - appEnabled: '{{ dig "clusters" .name "enabled" false . }}'
      selector:
        matchLabels:
          appEnabled: 'true'
  ```

**Comment by blade5502** [comment]
> > Could only get it to work with the workaround described above by @pydolan using an extra list generator:
> > ```yaml
> > spec:
> >   goTemplate: true
> >   generators:
> >     - matrix:
> >         generators:
> >           - matrix:
> >               generators:
> >                 - clusters: {}
> >                 - git:
> >                     files:
> >                       - path: cluster-apps/**/.argocd.json
> >                     repoURL: git@github.com:example/repo.git
> >                     revision: HEAD
> >                     values:
> >                       enabled: '{{ .source.repoURL }}'
> >           - list:
> >               elements:
> >                 - appEnabled: '{{ dig "clusters" .name "enabled" false . }}'
> >       selector:
> >         matchLabels:
> >           appEnabled: 'true'
> > ```
> 
> Thank you @blade5502 but unless I'm missing something I think this won't work for my case as I need scm+clusters+git. So I don't know how to add this workaround with list to the nested matrix example that I've shared.

Try that:

```yaml
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
             - scmProvider: {}
             - matrix:
                 generators: 
                     - clusters: {}
                     - git:
                         repoURL: '{{ .url }}'
                         revision: '{{ .branch }}'
                         files:
                           - path: '.deployment/argocd.yaml'
             - list:
                 elements:
                   - appEnabled: '{{ dig "clusters" .name "enabled" false . }}'
       selector:
         matchLabel:
           appEnabled: 'true'
  template: {}
  templatePatch: {}
```

**Comment by jacek-jablonski** [comment]
Still present in ArgoCD 3.0.5, have to do with additional escapings:

```yaml
  generators:
    - matrix:
        generators:
          - clusters:
              values:
                cluster: '{{ .name }}'
          - git:
              directories:
                - path: '*/clusters/{{ .name }}'
              repoURL: https://github.com/xxx/argocd-k8s-base.git
              revision: main
              values:
                app: '{{"{{ index .path.segments 0 }}"}}'  # !!!HERE
                external-gateway-namespace: default
                external-secrets-namespace: external-secrets
```
