### ISSUE TITLE
Applicationset controller silently not creating apps when facing 1 or more errors

### ISSUE THREAD

**Issue by similark** [argoproj/argo-cd#16832]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an appset is configured and only 1 set of params is causing a templating error (example below), the applicationset controller logs the error, followed by a "`generated x applications`" but actually does not create any.

**To Reproduce**

Create the following modified version of `git-generator-files-discovery`:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/similark/argo-cd.git
        revision: fix/applicationset_errors_no_apps
        files:
        - path: "applicationset/examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{.cluster.name}}-guestbook'
      labels:
        env: '{{ index .path.segments 5}}'
    spec:
      project: pe-dev-project
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: "applicationset/examples/git-generator-files-discovery/apps/guestbook"
      destination:
        server: https://kubernetes.default.svc
        #server: '{{.cluster.address}}'
        namespace: guestbook
```
This appset utilizes the `path.segments` array argument for templating a label, for simplicity.
Note that the generator discovers 3 `config.json` files, from which one has only 4 segments to its `path`. This can be caused by mistake or unaware user, and causes the templating to fail as stated in the logs of the controller:
`error="failed to execute go template {{ index .path.segments 5}}: template: :1:3: executing \"\" at <index .path.segments 5>: error calling index: reflect: slice index out of range"`
The repo still holds 2 correct `config.json` files, even the the following log line says:
`"generated 2 applications" generator`
But the actual behavior is that NOTHING gets created.

**Expected behavior**
I would expect the controller to create the desired applications that are correctly configured according to the appset spec, and ignore the ones that can't be created.

**Version**

```shell
                                                                                                                                                                                 
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.0+gc9f554d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0

```
