### ISSUE TITLE
A sudden permission error when triggering deployment restart

### ISSUE THREAD

**Issue by kyleli666** [argoproj/argo-cd#16845]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
We are using ArgoCD's API to restart deployment when needed.
It always works well, until today it fails just one time with a strange permission error, and then it still works later...
So it looks like a bug.

**To Reproduce**
It rarely happens, not sure how to reproduce.

**Expected behavior**
my deployment restarts without error

**Screenshots**

**Version**

```yaml
argocd: v2.8.6+6f7af53
  BuildDate: 2023-11-01T15:05:10Z
  GitCommit: 6f7af53bea9ebc9e9eadd47fc43b671ef91c0586
  GitTreeState: clean
  GoVersion: go1.20.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.6+6f7af53
  BuildDate: 2023-11-01T15:05:10Z
  GitCommit: 6f7af53bea9ebc9e9eadd47fc43b671ef91c0586
  GitTreeState: clean
  GoVersion: go1.20.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0

```

**Logs**
logs of argocd-server on this error
```ini
time="2024-01-12T08:10:00Z" level=info msg="received unary call /notification.NotificationService/ListServices" grpc.method=ListServices grpc.request.content= grpc.service=notification.NotificationService grpc.start_time="2024-01-12T08:10:00Z" span.kind=server system=grpc
time="2024-01-12T08:10:00Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListServices grpc.service=notification.NotificationService grpc.start_time="2024-01-12T08:10:00Z" grpc.time_ms=0.242 span.kind=server system=grpc
time="2024-01-12T08:10:00Z" level=info msg="received unary call /application.ApplicationService/RunResourceAction" grpc.method=RunResourceAction grpc.request.content="name:\"mdc-connection-deribit\" namespace:\"mkt\" resourceName:\"mkt-connection-deribit\" version:\"v1\" group:\"apps\" kind:\"Deployment\" action:\"restart\" appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2024-01-12T08:10:00Z" span.kind=server system=grpc
time="2024-01-12T08:10:00Z" level=info msg="Requested app 'mdc-connection-deribit' refresh"
time="2024-01-12T08:10:02Z" level=error msg="finished unary call with code Unknown" error="application default/mdc-connection-deribit is not permitted to manage apps/Deployment/mkt-connection-deribit in mkt" grpc.code=Unknown grpc.method=RunResourceAction grpc.service=application.ApplicationService grpc.start_time="2024-01-12T08:10:00Z" grpc.time_ms=1627.455 span.kind=server system=grpc
```
We get this error feedback from our own application.
![image](https://github.com/argoproj/argo-cd/assets/93997542/5309a536-89b4-4b14-aded-09c43bf9d444)
