### ISSUE TITLE
(Sealed)Secrets are not synced if in sub-directory and directory is not explicitly named

### ISSUE THREAD

**Issue by aydinseven7** [argoproj/argo-cd#16849]
**Setup**

Argo CD installed via Helm, using App of Apps pattern:
one application.yaml in an app of apps repo, other files in infra repo.

**Bug**

There is a dummy SealedSecret in the "root" directory (/argo) and a dummy SealedSecret 2 in the /roles directory (/argo/roles). Recurse is set to true, so it should go into each directory and sync the sealed secrets. However Argo CD actually only syncs the secrets in the root directory, but not the ones in the /roles folder. Every other kind (here: RoleBinding, Role, SA, etc) are synced normally.

**To Reproduce**

As an example for Argo-Workflows:
Secrets are synced separately from the Helm Chart and values.yaml, in an app called "argo-workflows-events-secrets":
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    repoURL: 'https://gitlab.corp-domain.com/example-group/infrastructure.git'
    targetRevision: HEAD
    path: argo
    directory:
      recurse: true
      include: '{sealed-*.yaml, *-role.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  project: example-group
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
metadata:
  name: argo-workflows-events-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
```

The secrets get synced if you set `include: '{sealed-*.yaml, *-role.yaml, roles/*}'`
folder structure of /argo:
```
.
├── README.md
├── argo-events-values.yaml
├── argo-workflows-values.yaml
├── roles
│   ├── README.md
│   ├── admin-role.yaml
│   ├── argo-workflow-role.yaml
│   ├── default-read-only-role.yaml
│   └── sealed-dummy-secret.yaml
├── sealed-argo-workflows-oidc-creds.yaml
├── sealed-dummy-secret.yaml
```

**Expected behavior**

SealedSecrets get synced normally, even without specifying the directory.

**Version**

```shell
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: windows/amd64
```
