### ISSUE TITLE
v2.9.3 generators - pathParam bug - only reads/use the first pathParam in generators

### ISSUE THREAD

**Issue by gabrielfsousa** [argoproj/argo-cd#16848]
Generators only use the first pathParam.

### **WONT WORK** 
Generators:
```
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - merge
        generators:
        - git:
            repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-cpm
            revision: HEAD
            files:
            - path: "weave-scope/base/conf.yaml"
        - matrix:
            generators:
            - git:
                repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-cpm
                revision: HEAD
                files:
                - path: "weave-scope/targets/**/conf.yaml"
                pathParamPrefix: targets
            - git:
                repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-k8s-clusters
                revision: HEAD
                files:
                - path: "targets/{{index .targets.path.segments 2}}/{{index .targets.path.segments 3}}/*.yaml"
                pathParamPrefix: clusters
```
Log:
![image](https://github.com/argoproj/argo-cd/assets/722744/b5db34dd-c5aa-41b7-9f84-4001f3c94528)

### **WORKS**
Generators:
this works, but i cant use because i need "_../targets/**/conf.yaml_" to override "_base/conf.yaml_"
```
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - merge
        generators:
        - matrix:
            generators:
            - git:
                repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-cpm
                revision: HEAD
                files:
                - path: "weave-scope/targets/**/conf.yaml"
                pathParamPrefix: targets
            - git:
                repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-k8s-clusters
                revision: HEAD
                files:
                - path: "targets/{{index .targets.path.segments 2}}/{{index .targets.path.segments 3}}/*.yaml"
                pathParamPrefix: clusters
        - git:
            repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-cpm
            revision: HEAD
            files:
            - path: "weave-scope/base/conf.yaml"
```
also work with only matrix
```
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-cpm
          revision: 'master'
          files:
          - path: "k8spacket/targets/**/conf.yaml"
          pathParamPrefix: targets
      - git:
          repoURL: git@ssh.dev.azure.com:v3/NAME/GitOps/dr-k8s-clusters
          revision: 'master'
          files:
          - path: "targets/{{index .targets.path.segments 2}}/{{index .targets.path.segments 3}}/*.yaml"
          pathParamPrefix: clusters
```
