### ISSUE TITLE
ApplicationSet RollingSync: the maxUpdate value might not be respected

### ISSUE THREAD

**Issue by rootmout** [argoproj/argo-cd#16881]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I wanted to give a try to the RollingSync feature of the ApplicationSet by creating a very basic setup having for RollingSync the follow:
```yaml
strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: env
              operator: In
              values:
                - prod
          maxUpdate: 1
```
By having a step matching all apps (2 in total) and with `maxUpdate` set to 1, I was expecting the controller to sync one app at the time when a rollout had to be performed. Instead, it happened **sometimes** that all apps went synced at the same time.

**To Reproduce**

In a fresh cluster, with ArgoCD (`argo-cd-5.52.1`) installed and with `RollingSync` enabled, deploy multiple time an app like the following one:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wave-server
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-update
  generators:
  - list:
      elements:
      - lang: en
        title: "Hello"
      - lang: fr
        title: "Bonjour"
  template:
    metadata:
      name: '{{lang}}-wave-server'
      labels:
        env: prod
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      project: default
      sources:
        - repoURL: 'registry-1.docker.io/rootmout'
          chart: wave-server
          targetRevision: 0.1.1
          helm:
            parameters:
              - name: "server.title"
                value: '{{title}}'
              - name: "service.type"
                value: "ClusterIP"
              - name: "service.nodePort"
                value: '~'

  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: env
              operator: In
              values:
                - prod
          maxUpdate: 1
```

The repeated creation-deletion of the above manifest didn't behave always the same way.

On my machine, by having a second open term I've been able to log the state of two ApplicationSet creation that didn't behave the same way: [app-sync-progress.log](https://github.com/argoproj/argo-cd/files/13955864/app-sync-progress.log)

**Note**: the "wave-server" is a nginx server taking intentionally 30s to start for simulating a fake workload.

**Expected behavior**

A RollingSync consistent between that will sync one app at time if `maxUpdate` is set to 1.

**Version**

```shell
$> kind --version
kind version 0.20.0
$> helm list -n argocd       
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
argocd  argocd          1               2024-01-16 00:06:38.790208732 +0100 CET deployed        argo-cd-5.52.1  v2.9.3     
```

**Logs**

Logs of the appset controller: [argocd-applicationset-controller.log](https://github.com/argoproj/argo-cd/files/13955901/argocd-applicationset-controller.log)
