### ISSUE TITLE
Cluster Generator delete Applications using same name unexpectedly

### ISSUE THREAD

**Issue by MasayaAoyama** [argoproj/argo-cd#16882]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Generated application is conflict unexpectedly using Cluster Generator of ApplicationSet.

In Argo CD, `server` is used as unique ID, and `name` is used as metadata (please see Additional notes in following).
But Cluster Generator use `name` as entry in generation loop, so we cannot use same `name` with Cluster Generator.

We provide Kubernetes as a Service, so some tenants create same name cluster. After that, ArgoCD sync and delete manifests to the cluster randomly, and then cluster is broken.

**To Reproduce**

+ Create same `name` cluster with different `server`.
+ Create ApplicationSet with Cluster Generator, using label for Application name
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - clusters: {} 
  template:
    metadata:
      name: '{{ metadata.labels.tenant-name }}-{{name}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: default
```
+ ApplicationSet Controller create Application for `cluster-1`
    * e.g. tenantA-mycluster-guestbook
+ And then, create new cluster `cluster-2`, and ApplicationSet Controller create Application for `cluster-2`.
    * e.g. tenantB-mycluster-guestbook
    * but currently, Cluster Generator only generate for `cluster-2`. because [GenerateParams](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/cluster.go#L88) generate Applications by `name`.
+ Unexpectedly, delete Application for `cluster-1` at `deleteInCluster()`

**Expected behavior**

Cluster generator should not delete existing Application with same name.
So I think Cluster generator shoud use `server` as entry in generation loop. I think this changes are not affected to others.

**Version**

```
argocd: v2.7.2+cbee7e6.dirty
  BuildDate: 2023-05-12T13:43:26Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
none
```

**Additional notes**

* can add different `server` with same `name`.

```shell
# argocd cluster add context1 --name argocluster1
Cluster 'https://10.0.0.1:443' added

# argocd cluster add context2 --name argocluster1
Cluster 'https://10.0.0.2:443' added
```

* cannot add same `server` with different `name`.

```shell
# argocd cluster add context2 --name argocluster1
Cluster 'https://10.0.0.2:443' added

# argocd cluster add context3 --name argocluster2
FATA[0001] rpc error: code = InvalidArgument desc = existing cluster spec is different; use upsert flag to force update; difference in keys "ID,Name"
```

* example kubeconfig

```yaml
apiVersion: v1
kind: Config
users:
- name: myuser

clusters:
- cluster:
    server: https://10.0.0.1:443
  name: cluster1
- cluster:
    server: https://10.0.0.2:443 # same cluster
  name: cluster2
- cluster:
    server: https://10.0.0.2:443 # same cluster
  name: cluster3

contexts:
- context:
    cluster: cluster1
    user: myuser
  name: context1
- context:
    cluster: cluster2
    user: myuser
  name: context2
- context:
    cluster: cluster3
    user: myuser
  name: context3
```

**Screenshots**
