### ISSUE TITLE
Notification Controller 

### ISSUE THREAD

**Issue by Arsen-Zhakypbek-Uulu** [argoproj/argo-cd#16904]
# Summary
When using ArgoCD notifications, we can only configure it per app using Application CRD
I wonder if we could configure notifications per resource? e.g, 

```
kind: Deployment, DaemonSet, StatefullSet, etc....
metadata:
     annotations:
          notifications.argoproj.io/subscribe.on-deployed.slack: <slack.channel>
          notifications.argoproj.io/subscribe.on-health-degraded.slack: <slack.channel>
          notifications.argoproj.io/subscribe.on-sync-failed.slack: <slack.channel>
```

# What change you think needs making.
Options:
       1. Notification controller should allow subscription from Kubernetes RDs, not just from Application RD.
# Motivation
There are could be many resources with a single Argo App, and when using argo notifications we only get Alerts with an app name, and no visibility what exactly got deployed. (service-A or service-B), we just get alerts that App has been deployed.

Please give examples of your use case, e.g. when would you use this.
Argo App: App-A(has multiple resources, e.g Deployment-A, Deployment-B, Deployment-C), and when we receive the notification in slack, I wanna be able to see which Deployment from A,B,C got deployed, instead just getting App-A Deployment message. 

# Proposal

How do you think this should be implemented?
I'll leave the implementation up to you
