### ISSUE TITLE
Can not disable https prort in argo-cd-server deployment

### ISSUE THREAD

**Issue by qodirovshohijahon** [argoproj/argo-cd#16909]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am anaylzing using `istioctl analyze -A`

I am facing
Warning [IST0137] (Deployment sample-petclinic/sample-petclinic-argocd-server) This deployment sample-petclinic-argocd-server is associated with multiple services [sample-petclinic/sample-petclinic-argocd-server sample-petclinic/sample-petclinic-argocd-server] using targetPort "8080" but different ports: [80 443].
This waring is caused by the ports on the argocd server

It is possible to remove this warning according to the doc, but argo-cd is installed via Helm and deployment/service (argo-cd server deployment and service) cannot be controlled.

These warnings disappear in version 1.20.0, but I want to fix it without waiting for the upgrade.

I can not disable https port from here, If I remove manually this port this warning will be removed so I need to disable this port using helm values or with another way

**Screenshots**

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      sample-bookinfo-argocd:/Service:sample-bookinfo/sample-bookinfo-argocd-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.8.2
    helm.sh/chart: argo-cd-5.45.0
  name: sample-bookinfo-argocd-server
  namespace: sample-bookinfo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  type: ClusterIP
```
**Version**

```shell
istioctl version: 1.20.0
control/data plane version: 1.18.5
argocd chart version: 5.45.0`
imageTag: v2.8.2
```
**Logs**
```
Warning [IST0137] (Deployment sample-bookinfo/sample-bookinfo-argocd-server) This deployment sample-bookinfo-argocd-server is associated with multiple services [sample-bookinfo/sample-bookinfo-argocd-server sample-bookinfo/sample-bookinfo-argocd-server] using targetPort "8080" but different ports: [80 443].
```
