### ISSUE TITLE
multi-source apps break application parameters UI

### ISSUE THREAD

**Issue by nneram** [argoproj/argo-cd#16910]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using the [beta feature](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/) multi sources for an app with a CMP plugin. It's working all fine, my plugin take a config source with values and app source with helm charts. 

```
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: app
syncPolicy:
  automated:
    prune: true
    selfHeal: true
sources:
  - repoURL: 'ssh://gitolite@forge.com/my-config.git'
    path: ./addons/cert-manager
    targetRevision: cluster115
    plugin:
      name: plugin-v1.0.0
  - repoURL: 'ssh://gitolite@forge.com/dome-apps.git'
    path: ./security/cert-manager
    targetRevision:  cluster115
    plugin:
      name: plugin-v1.0.0
      env:
        - name: OVERLAY
          value: internal
        - name: HELM_RELEASE_NAME
          value: certm
        - name: APP_VERSION
          value: latest
```

However, in the UI, If I try to reach the parameters from an app, I got an error:
https://apps.cluster115.sts.lan/applications/app/cert-manager?view=tree&node=argoproj.io%2FApplication%2Fapp%2Fcert-manager%2F0&tab=parameters&resource=

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).

Stacktrace:

Mh@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1725680
Za@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:808354
Es@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:854400
Sl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:847162
xl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:847085
hl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:844108
82002/Xo/<@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795769
90362/t.unstable_runWithPriority@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:870971
qo@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795478
Xo@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795716
Jo@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:795649
cl@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:840878
enqueueSetState@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:799432
17952/y.prototype.setState@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1024313
t@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1566791
o@https://apps.cluster115.sts.lan/main.dacc55dcbd944c5e45d8.js:2:1566912
```

**Screenshots**

![argo_bug](https://github.com/argoproj/argo-cd/assets/58568330/898713e6-b891-41c8-9f95-483069a36068)

**Version**

```shell
argocd version --grpc-web
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:24:09Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
  ```
  
  **Logs**

logs with `server.log.level: "debug"` when I click:

```
time="2024-01-18T15:14:39Z" level=info msg="received unary call /repository.RepositoryService/GetAppDetails" grpc.method=GetAppDetails grpc.request.claims="{\"acr\":\"0\",\"at_hash\":\"N_pM01J5F0Kd5Bc4abPQBg\",\"aud\":\"argo-cd\",\"auth_time\":1705572021,\"azp\":\"argo-cd\",\"email\":\"admin@replaced_name.exemple.bar.eu\",\"email_verified\":true,\"exp\":1705591173,\"family_name\":\"Administrator\",\"given_name\":\"replaced_name\",\"groups\":[\"/admin\"],\"iat\":1705590873,\"iss\":\"https://auth.cluster115.sts.lan/realms/replaced_name\",\"jti\":\"a7d5dab4-aff8-4f19-bf3c-b8e0faeddc20\",\"name\":\"replaced_name Administrator\",\"preferred_username\":\"replaced_name_admin\",\"realm_access\":{\"roles\":[\"view-dashboards\",\"edit-dashboards\",\"edit-subscribers\",\"view-subscribers\",\"admin\",\"manage-dashboards\",\"manage-apps\",\"view-alerts\",\"view-metrics\",\"view-apps\",\"view-logs\"]},\"session_state\":\"389cce28-3a15-4f2c-be94-c3a317ec7be2\",\"sid\":\"389cce28-3a15-4f2c-be94-c3a317ec7be2\",\"sub\":\"f08abe40-829c-412e-8d3a-15283a3b8ddb\",\"typ\":\"ID\"}" grpc.request.content="source:<repoURL:\"ssh://gitolite@forge.b-com.com/dop-css/nnerambour/my-replaced_name-config.git\" path:\"./replaced_name-addons/cert-manager\" targetRevision:\"cluster115\" plugin:<name:\"replaced_name-plugin-v1.0.0\" > chart:\"\" ref:\"\" > appName:\"cert-manager\" appProject:\"default\" " grpc.service=repository.RepositoryService grpc.start_time="2024-01-18T15:14:39Z" span.kind=server system=grpc
time="2024-01-18T15:14:39Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2024-01-18T15:14:39Z" grpc.time_ms=4.833 span.kind=server system=grpc
time="2024-01-18T15:14:39Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2024-01-18T15:14:33Z" grpc.time_ms=5581.443 span.kind=server system=grpc
time="2024-01-18T15:14:39Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2024-01-18T15:14:33Z" grpc.time_ms=5485.515 span.kind=server system=grpc
```

**Comment by ishitasequeira** [comment]
Thanks @nneram for raising the issue. Currently, the UI support is not yet added for multiple sources feature. But if the UI is crashing, I can take a look at fixing it. Can you please provide a working example of the configuration you are using? This would help me test the changes locally and try to fix the issue. Thanks!!

**Comment by nneram** [comment]
Thank you for supporting it during the beta ! We are using it cautiously.

If you refer to the `Application` specification from the [documentation example](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: my_ns
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - chart: elasticsearch
      repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      path: guestbook
      targetRevision: HEAD
```

It works fine. However, when I tried something else, more like my example but without my custom plugin (I still have the sidecar, but not using it); here, I encountered the same bug. So, I guess it's not because of my CMP sidecar:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: my_ns
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      path: sock-shop
      targetRevision: HEAD
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      path: guestbook
      targetRevision: HEAD
```

I hope you can replicate the bug with this configuration. Please let me know if you need any additional information.
