### ISSUE TITLE
Can't exec on pods using Keycloack user with role:admin 

### ISSUE THREAD

**Issue by gabrieloandco** [argoproj/argo-cd#16928]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
I can exec pods using argocd admin, however I can't when using my Keycloack user with admin role. 

**To Reproduce**
I already added the `exec.enabled` flag, argocd cluster role already has permissions to exec pods and already gave my role permissions to exec pods. 

argocd-rbac-cm .yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, my-group, role:admin
    p, role:admin, exec, create, */* , allow
  policy.default: role:readonly
  scopes: '[groups]'
```

**Expected behavior**

I expect to be able to use the terminal if I'm part of  ole:admin

**Screenshots**
using admin user:

Using my keycloack user on group "my-group" with role:admin:
![Screenshot from 2024-01-19 14-25-51](https://github.com/argoproj/argo-cd/assets/22502671/a8e16cc0-77bb-4424-9d7e-b88f744cd351)

**Version**
argocd: v2.5.2+148d8da
  BuildDate: 2022-11-07T17:06:04Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.7
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.8.0+804d4b8
  BuildDate: 2023-08-07T14:25:33Z
  GitCommit: 804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0

**Logs**
