### ISSUE TITLE
ExternalSecret Resource not getting deleted due to foregroundDeletion finalizer 

### ISSUE THREAD

**Issue by manali14** [argoproj/argo-cd#16925]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have an external secret associated with an application. As soon as we click on sync, the secret gets deleted and externalSecret goes to a pendingDeletion state.

We are able to successfully sync the App by force deleting the external secret.

Also, though foreground deletion through argocd is stuck in PendingDeletion state, if we delete it manually using kubectl command through jumphost, it gets deleted without adding --force.

**To Reproduce**

Create an application with below manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: <>
  namespace: argocd
spec:
  destination:
    name: '<>'
    namespace: dev
  project: <>
  source:
    helm:
      passCredentials: true
      releaseName: <>
      valueFiles:
        - values.yaml
        - values_dev.yaml
    path: <>
    repoURL: '<>'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

The application contains below k8s resources:

1. configMap
2. svc
3. pods
4. hpa
5. deployment
6. job
7. externalSecret (reading secrets from AWS Secrets Manager)
8. ingress
9. role
10. rolebinding

Post auto-sync/manually syncing the app, the secret deletes while the corresponding secret goes to a pendingDeletion state. It has to be manually deleted through jumphost/force deleted through argocd to get the deployment done.

**Expected behavior**

The application should recreate the external secret and sync successfully.

**Screenshots**

<img width="1226" alt="Screenshot 2024-01-19 at 3 25 15 PM" src="https://github.com/argoproj/argo-cd/assets/6524146/96ae07d9-d2b5-4f49-a59a-c3a38ef19c71">
<img width="1136" alt="Screenshot 2024-01-19 at 3 25 25 PM" src="https://github.com/argoproj/argo-cd/assets/6524146/af3acd4d-092f-47bd-b684-7730e0f3bad3">

**Version**

```shell
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.3+6eba5be
```
