### ISSUE TITLE
Deployment Restart via ArgoCD not working. 

### ISSUE THREAD

**Issue by agido-heppe** [argoproj/argo-cd#16923]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hey, since I upgraded to ArgoCD to 2.9.4 via Helmchart version 5.53.1, I cannot restart deployments via the UI. First, I tried to restart a deployment via the regular UI on the deployment object. During this attempt an error message popped up: `Unable to execute resource action: Invalid content type`. To rule out errors with permissions i tried the same as admin and got the same error.
<img width="161" alt="image" src="https://github.com/argoproj/argo-cd/assets/102145035/e14479a1-281b-4280-b8c0-f15030964c8e">

I also tried this on multiple apps/deployments.

**To Reproduce**

Restart an app via ArgoUI on Version 2.9.4 (deployed by the helm chart version 5.53.1)

**Expected behavior**

The deployment should restart like usual.

**Screenshots**

<img width="348" alt="image" src="https://github.com/argoproj/argo-cd/assets/102145035/23fa4fef-0c96-44a5-96c7-16708fc2b546">

**Version**

Unfortunately, I already perfomed a rollback before opening this issue.
Details:
ArgoCD 2.9.4
HelmChart: 5.53.1

If you need detailed build details, I could deploy the newer version later this day. 

**Logs**

I didn't find any related logs, if you could provide me with a hint on what to grep for, I could provide some logs later.

Edit:
- Might be related to https://github.com/argoproj/argo-cd/pull/16860.
I guess, I have to allow `application/grpc` and/or others?

**Comment by baileydoestech** [comment]
We are also seeing this issue upgrading to 2.9.4 - seems to be blocking all post actions in the UI with a 415 unsupported media error

**Comment by nobbs** [comment]
Running the ArgoCD server with the cli argument

```
--api-content-types application/json;application/x-www-form-urlencoded
```

does fix that, as the POST requests are using `application/x-www-form-urlencoded` and as of v2.9.4 only `application/json` is allowed for non-GET requests. This does fix the "invalid content type" issue for triggering actions from the UI, _**but I'm not sure whether this does not fully disable the protection for the vulnerability that was fixed in v2.9.4 - that's something someone from the ArgoCD team will need to clarify**_.

**Comment by rubensheik** [comment]
Hello! I'm getting this same issue with the version v2.9.0+c7bf064 always that a try to perform any exclusion by UI,  

> Running the ArgoCD server with the cli argument
> 
> ```
> --api-content-types application/json;application/x-www-form-urlencoded
> ```
> 
> does fix that, as the POST requests are using `application/x-www-form-urlencoded` and as of v2.9.4 only `application/json` is allowed for non-GET requests. This does fix the "invalid content type" issue for triggering actions from the UI, _**but I'm not sure whether this does not fully disable the protection for the vulnerability that was fixed in v2.9.4 - that's something someone from the ArgoCD team will need to clarify**_.

Hello! I'm getting this same issue with the version v2.9.0+c7bf064 always that a try to perform any exclusion by UI, how can i fixing this, i'm using eks HA deploy.

**Comment by nobbs** [comment]
@rubensheik Depends on what you used to deploy ArgoCD. Their community-maintained helm chart from <https://github.com/argoproj/argo-helm>? Then the following values will work:

```yaml
server:
  # FIX: this is a workaround for https://github.com/argoproj/argo-cd/issues/16923
  extraArgs:
    - "--api-content-types"
    - "application/json;application/x-www-form-urlencoded"
```

If it's another way of deployment, you'll need to check how to best modify the args of the container to look like this:

```yaml
...
    spec:
...
      containers:
        - args:
            - /usr/local/bin/argocd-server
            - '--api-content-types'
            - application/json;application/x-www-form-urlencoded
            - ...
...
```
