### ISSUE TITLE
Multi-source helm app w/ targetRevision specified via semver not updating

### ISSUE THREAD

**Issue by proever** [argoproj/argo-cd#16957]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

I've got an app for MLflow deployed via Argo CD. It's a multi-source app, with a helm chart from Bitnami and some custom values in our private git repo. Here's the manifest: 

```yaml
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: mlflow
syncPolicy:
  automated:
    prune: true
    selfHeal: true
sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '0.5'
    helm:
      valueFiles:
        - $values/helm/mlflow/values.yaml
    chart: mlflow
  - repoURL: '<repo>/infra'
    targetRevision: main
    ref: values
```

I specified `targetRevision: '0.5'`, so I'd expect any release matching `0.5` to be synced and applied, but it seems I'm stuck on `0.5.0` (although this is hard to verify from the UI, given the multi-source nature of the app), even though `0.5.1` is [available](https://github.com/bitnami/charts/commit/1452875bc661cff6f5685f9deaf2b1416067ea84). 

The way I noticed was that that release says that `tag: 11-debian-11-r94` should be applied for the `os-shell` container, but in the UI at least I can see `docker.io/bitnami/os-shell:11-debian-11-r93` still specified. 

**Expected behavior**

From my understanding, `argo-cd` should have updated from `0.5.0` to `0.5.1` at some point, given that `targetRevision: '0.5'` was specified. But I could be wrong about that expectation!

**Version**

```bash
argocd: v2.9.3+6eba5be.dirty
  BuildDate: 2023-12-02T00:37:11Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.9.3+6eba5be
```
