### ISSUE TITLE
Deep link from resource annotations

### ISSUE THREAD

**Issue by buker** [argoproj/argo-cd#16969]
<!-- If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack). -->

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I want get link or its part from resource object for which i want create deep link but i can't read from annotations.
Could you add in documentation if how i can do that if it possibile at all? I am adding few examples i tried

**To Reproduce**
argocd-cm.yaml
```yaml
    resource.links: |
      - url: {{ .resource.metadata.annotations.grafana }}
        title: Grafana
        if: resource.kind == "Deployment"
      - url: {{ .resource.metadata.annotations \"grafana\"}}
        title: Grafana
        if: resource.kind == "Deployment"
      - url: {{ .resource.metadata.annotations.[grafana]}}
        title: Grafana
        if: resource.kind == "Deployment"
```
**Expected behavior**

<!-- A clear and concise description of what you expected to happen. -->

**Screenshots**

<!-- If applicable, add screenshots to help explain your problem. -->

**Version**

```shell
{
    "Version": "v2.9.3+6eba5be",
    "BuildDate": "2023-12-01T23:05:50Z",
    "GitCommit": "6eba5be864b7e031871ed7698f5233336dfe75c7",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
 server {"error":"failed to read application deep links from configmap: error unmarshalling deep links error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{\".resource.metadata.labels.annotations.grafana\":interface {}(nil)}","grpc.code":"Unknown","grpc.method":"ListResourceLinks","grpc.service":"application.ApplicationService","grpc.start_time":"2024-01-24T08:44:26Z","grpc.time_ms":30.062,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2024-01- │
│ 24T08:44:26Z"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
```

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by crenshaw-dev** [comment]
I think you need to use the `index` function of go text templates. Example:

```yaml
    # sample checking a tag exists that contains - or / and how to alternatively access it
    - url: https://mycompany.splunk.com?tag={{ index .resource.metadata.labels "some.specific.kubernetes.like/tag" }}
      title: Tag Service
      if: resource.metadata.labels["some.specific.kubernetes.like/tag"] != nil && resource.metadata.labels["some.specific.kubernetes.like/tag"] != ""
```

Closing since I'm 99% sure this is it. :-)
