### ISSUE TITLE
argocd diff shows no diff when secret key deleted

### ISSUE THREAD

**Issue by lcc3108** [argoproj/argo-cd#16986]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We manage the secret of the application as egocd.

When I deleted the secret, the diff didn't come up, so I found a problem with the previous version of manifest being applied as it was.

**To Reproduce**
1. Update github code to show yaml file below

```
apiVersion: v1
data:
  CACHE_REDIS_PASSWORD: ++++++++
  STATISTIC_POSTGRES_DB: ++++++++
  STATISTIC_POSTGRES_PASSWORD: ++++++++
  STATISTIC_POSTGRES_USER: ++++++++
kind: Secret
metadata:
  name: statistic-consumer
type: Opaque
```
2. Synchronize to Argosidi

3.Update the contents of CACHE_REDIS_PASSWORD key

**Expected behavior**
argocd detect diff and remove secret key CACHE_REDIS_PASSWORD 
**Screenshots**
live
![image](https://github.com/argoproj/argo-cd/assets/38449269/93408a38-737b-4e96-b178-3e23f8e7e032)
desired
![image](https://github.com/argoproj/argo-cd/assets/38449269/00351d3b-132f-406a-bffd-fd29c93d77f5)
but no diff
![image](https://github.com/argoproj/argo-cd/assets/38449269/9bc2edbc-2c53-4de6-8e16-d69f8e230a3e)

**Version**

{
    "Version": "v2.8.4+c279299",
    "BuildDate": "2023-09-13T19:12:09Z",
    "GitCommit": "c27929928104dc37b937764baf65f38b78930e59",
    "GitTreeState": "clean",
    "GoVersion": "go1.20.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.1.0 2023-06-19T16:58:18Z",
    "HelmVersion": "v3.12.1+gf32a527",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}

**Logs**

```
Paste any relevant application logs here.
```
