### ISSUE TITLE
Default values in templates can't be explicitly set

### ISSUE THREAD

**Issue by max06** [argoproj/argo-cd#16990]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Helm-charts might contain dictionaries in templates with default values, where overriding one value might make another value unavailable.

**To Reproduce**

Assume helm chart default values (simplified):

```yaml
ingress:
  enabled: true
  hosts:
    - host: chart-example.local
      paths:
        - path: /
```

together with following template:

```yaml
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
```

ArgoCD will offer parameters for `ingress.hosts[0].host` and `ingress.hosts[0].paths[0].path`. Overriding the first one will make the second one disappear, and there's no possibility to set the second parameter to `/` because argo doesn't recognize it as "modified".

From the helm pov:

Default render:

```yaml
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            backend:
              service:
                name: something
                port:
                  number: 3000
```

Render with one parameter changed: (`helm template something apps/something/ -s templates/ingress.yaml --set ingress.hosts[0].host=some.domain.net`

```yaml
spec:
  rules:
    - host: "some.domain.net"
      http:
        paths:
```

Render with proper override: (`helm template something apps/something/ -s templates/ingress.yaml --set ingress.hosts[0].host=some.domain.net,ingress.hosts[0].paths[0].path=/`)

```yaml
spec:
  rules:
    - host: "some.domain.net"
      http:
        paths:
          - path: /
            backend:
              service:
                name: something-homepage
                port:
                  number: 3000
```

**Version**

```json
{
    "Version": "v2.9.3+6eba5be",
    "BuildDate": "2023-12-01T23:05:50Z",
    "GitCommit": "6eba5be864b7e031871ed7698f5233336dfe75c7",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.13.2+g2a2fb3b",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```
