### ISSUE TITLE
UI will crash when create application without destination namespace

### ISSUE THREAD

**Issue by eric4545** [argoproj/argo-cd#1701]
**Describe the bug**
Showing blank page / UI crash after login.

**To Reproduce**
If we cannot reproduce, we cannot fix! Steps to reproduce the behavior:
1. Create `guestbook.yaml` with below content
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    # namespace: guestbook
```
2. kubectl -n argocd apply -k guestbook
3. kubectl -n argocd port-forward svc/argocd-server 8000:443
4. login https://localhost:8000, Blank page will occur 

**Expected behavior**
Expected applications page working properly 
 
**Screenshots**
![image](https://user-images.githubusercontent.com/6886275/58998158-f5cae280-8831-11e9-875b-60d9390a1c03.png)

**Version**

```shell
argocd: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:28:05Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:27:38Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```
