### ISSUE TITLE
[ApplicationSet] 

### ISSUE THREAD

**Issue by yogeek** [argoproj/argo-cd#17026]
I have a gitlab group with 12 repositories.
If someone opens a PR on 1 (or more) repository  in this group from a branch named "b1", I would like to generate only 1 argocd application that will take the PR branch name ("b1") as parameter.
I don't want to create 1 appset per repo, so I am using a matrix generator :  SCMProvider (to discover all repos in the group) + PullRequest (to discover the PRs)

If I open a PR on 1 repo, it works well => 1 app is generated
But if I open a PR on 2 repos, it generates 2 apps... how can I do to only have 1 app please ? Is there a way to do like a "uniq" on the branch name ?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-virtualenv
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - scmProvider:
          cloneProtocol: ssh
          gitlab:
            api: https://mygitlab
            group: mygroup
      - pullRequest:
          gitlab:
            project: 'mygroup/{{ .repository }}'
            api: https://mygitlab
            pullRequestState: opened
  template:
    metadata:
      name: '{{ .repository }}-{{ .branch_slug }}-{{ .number }}'
      labels:
        generated: pr
    spec:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: git@mygitlab:mycharts/chart.git
        helm:
          parameters:
          - name: name
            value: '{{ .branch_slug }}-{{ .number }}'
```
        
I tried to play with matrix and merge but no valid results for now...
I also thought about making a plugin generator but that would imply to store a kind of "state" (first time the branch "b1" is present, set a boolean to true to not generating outputs for the other "b1" branches...) and I doubt it is a good idea to manage state for this.
