### ISSUE TITLE
ApplicationSet: Nested GitGenerator params not available for templating in the `values` object using GoTemplate.

### ISSUE THREAD

**Issue by kaos** [argoproj/argo-cd#17034]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

As described in the docs for [GitGenerator `values` field](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#pass-additional-key-value-pairs-via-values-field) you can provide additional params to the template via the `values` field object on the generator. The example in the documentation uses the legacy fasttemplate syntax, which works in all cases, but when using the new `goTemplate: true` syntax it breaks when the generator is nested in a Matrix generator.

The reason it breaks is because the params of the git generator is not provided when evaluating the template strings for the matrix generator, so any references to git parameters or values read from a file in case of a git file generator will result in `<no value>` or error.

The generator values are provided (too late, is my point) when doing a final template evaluation for the top level result (the matrix generator output).

The reason this works for the legacy template engine, is because any failed template expressions are left as-is so for the inner evaluations they remain unchanged and once evaluated again with the params properly provided they resolve to their corresponding correct values. The go template engine does not have any option to reflect this behavior, so will result in either a failed coercion or "<no value>"'s in the output.

There is a work-around available by providing an additional layer of wrapping of the template values, as shown in the reproduction below.

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - list:
            elements:
            - filename: kustomization.yaml
        - git:
            repoURL: https://github.com/argoproj/argo-cd.git
            revision: HEAD
            files:
            - path: "applicationset/examples/git-generator-directory/cluster-addons/*/{{.filename}}"
            values:
              name: "{{index .path.segments 4}}"
              workaround: "{{`{{.kind}}`}}"
  template:
    metadata:
      name: '{{.values.name}}'
      labels:
        kind: "{{.values.workaround}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
```

**Expected behavior**

I expect the git generator to behave the same as a root level generator as well as when nested in a matrix generator.

**Version**

Verified by unit test on latest `master` `4e084ace8c815f225252fe7b8c770a5a1629461a`.

**Unit test**

Failing unit test show-casing this error:

```go
// applicationset/generators/matrix_test.go

func TestMatrixGenerator_GenerateParams_list_x_git_matrix_generator(t *testing.T) {
	// Given a matrix generator over a list generator and a git files generator, the nested git files generator should
	// be able to use `path` in the `values` object using GoTemplate.

	listGeneratorMock := &generatorMock{}
	listGeneratorMock.On("GenerateParams", mock.AnythingOfType("*v1alpha1.ApplicationSetGenerator"), mock.AnythingOfType("*v1alpha1.ApplicationSet")).Return([]map[string]interface{}{
		{"some": "value"},
	}, nil)
	listGeneratorMock.On("GetTemplate", mock.AnythingOfType("*v1alpha1.ApplicationSetGenerator")).Return(&argoprojiov1alpha1.ApplicationSetTemplate{})

	gitGeneratorSpec := &argoprojiov1alpha1.GitGenerator{
		RepoURL: "https://git.example.com",
		Files: []argoprojiov1alpha1.GitFileGeneratorItem{
			{Path: "some/path.json"},
		},
		Values: map[string]string{
			"key1": "val1-{{.path.path}}",
			"key2": "some:{{.some}}",
			"key3": "file:{{.test}}",
                        // Test PASS with the following:
			// "key1": "val1-{{`{{.path.path}}`}}",
			// "key2": "some:{{.some}}",
			// "key3": "file:{{`{{.test}}`}}",
		},
	}

	repoServiceMock := &mocks.Repos{}
	repoServiceMock.On("GetFiles", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Return(map[string][]byte{
		"some/path.json": []byte("test: content"),
	}, nil)
	gitGenerator := NewGitGenerator(repoServiceMock)

	matrixGenerator := NewMatrixGenerator(map[string]Generator{
		"List": listGeneratorMock,
		"Git":  gitGenerator,
	})

	matrixGeneratorSpec := &argoprojiov1alpha1.MatrixGenerator{
		Generators: []argoprojiov1alpha1.ApplicationSetNestedGenerator{
			{
				List: &argoprojiov1alpha1.ListGenerator{
					Elements: []apiextensionsv1.JSON{
						{
							Raw: []byte(`{"some": "value"}`),
						},
					},
				},
			},
			{
				Git: gitGeneratorSpec,
			},
		},
	}
	params, err := matrixGenerator.GenerateParams(&argoprojiov1alpha1.ApplicationSetGenerator{
		Matrix: matrixGeneratorSpec,
	}, &argoprojiov1alpha1.ApplicationSet{
		Spec: argoprojiov1alpha1.ApplicationSetSpec{
			GoTemplate: true,
		},
	})
	require.NoError(t, err)
	assert.Equal(t, []map[string]interface{}{{
		"path": map[string]interface{}{
			"path":               "some",
			"basename":           "some",
			"basenameNormalized": "some",
			"filename":           "path.json",
			"filenameNormalized": "path.json",
			"segments": []string{
				"some",
			},
		},
		"some": "value",
		"test": "content",
		"values": map[string]string{
			"key1": "val1-some",
			"key2": "some:value",
			"key3": "file:content",
		},
	}}, params)
}
```

```
    matrix_test.go:1214:
        	Error Trace:	/Users/aadt/proj/gh/argoproj/argo-cd/applicationset/generators/matrix_test.go:1214
        	Error:      	Not equal:
        	            	expected: []map[string]interface {}{map[string]interface {}{"path":map[string]interface {}{"basename":"some", "basenameNormalized":"some", "filename":"path.json", "filenameNormalized":"path.json", "path":"some", "segments":[]string{"some"}}, "some":"value", "test":"content", "values":map[string]string{"key1":"val1-some", "key2":"some:value", "key3":"file:content"}}}
        	            	actual  : []map[string]interface {}{map[string]interface {}{"path":map[string]interface {}{"basename":"some", "basenameNormalized":"some", "filename":"path.json", "filenameNormalized":"path.json", "path":"some", "segments":[]string{"some"}}, "some":"value", "test":"content", "values":map[string]string{"key1":"val1-<no value>", "key2":"some:value", "key3":"file:<no value>"}}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -15,5 +15,5 @@
        	            	   (string) (len=6) "values": (map[string]string) (len=3) {
        	            	-   (string) (len=4) "key1": (string) (len=9) "val1-some",
        	            	+   (string) (len=4) "key1": (string) (len=15) "val1-<no value>",
        	            	    (string) (len=4) "key2": (string) (len=10) "some:value",
        	            	-   (string) (len=4) "key3": (string) (len=12) "file:content"
        	            	+   (string) (len=4) "key3": (string) (len=15) "file:<no value>"
        	            	   }
        	Test:       	TestMatrixGenerator_GenerateParams_list_x_git_matrix_generator
```
