### ISSUE TITLE
Applications in any namespace documentation omits necessary application-controller privileges

### ISSUE THREAD

**Issue by cdemarco-drw** [argoproj/argo-cd#17073]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Neither [the documentation of K8s RBAC necessary for Applications in any Namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#adapt-kubernetes-rbac), nor [the examples linked](https://github.com/argoproj/argo-cd/tree/master/examples/k8s-rbac/argocd-server-applications) declare what privs application-controller will need in the various Namespaces where Application resources will be processed.

Through trial and error, reading the logs and clicking the GUI, I've arrived at this priv scope as the minimum necessary for a ClusterRole:

```
      - apiGroups:
          - ""
        resources:
          - events
        verbs:
          - create
      - apiGroups:
          - argoproj.io
        resources:
          - applications
        verbs:
          - get
          - list
          - watch
          - patch
```

**To Reproduce**

Configure apps-in-any-namespace without this K8s RBAC, observe errors in the logs and GUI non-functioning.
Add this K8s RBAC and observe normal functioning.

**Expected behavior**

The docs should disclose what's needed to use the feature.

**Version**

```shell
v2.9.5+f943664
```
