### ISSUE TITLE
Better `manifest-generate-paths` annotation support for multi source apps

### ISSUE THREAD

**Issue by jackevans43** [argoproj/argo-cd#17085]
# Summary

Currently a single `manifest-generate-paths` annotation applies to all sources.

# Motivation

Users may want to apply different values of  `manifest-generate-paths` per source/repo as they'll have different directory structures.

# Proposal

#17071 could solve the issue, but can something be done as non-breaking change before ArgoCD 3.0?

**Comment by shapirus** [comment]
I would say that the time has come that the annotation has matured enough and is ready to be made a per-source field, be it a single `source` or the multiple `sources` array.

**Comment by agaudreault** [comment]
This is hacky, but few possibilities could be 

1. Use the source ref name in ther annotation so you have `manifest-generate-paths: /root/folder;./relative/all/source;also/relative;$ref/relative/to/ref/source/only`. But I am not sure if ref can be specified on any sources. 
2. Use order `#0/ref/relative/to/first/source`

Example app:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $ref/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: ref
```
