### ISSUE TITLE
When --disable-auth is enabled, exec no longer works without a log in

### ISSUE THREAD

**Issue by ashwinath** [argoproj/argo-cd#17114]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When `argocd-server` is started with `--disable-auth --insecure`, pod exec will not work without a login. It was working on v2.5.8 but not on v2.10.0/v2.8.3. After logging in as an admin user, it works.

I understand this fix for expiring sessions for some CVE here: https://github.com/argoproj/argo-cd/commit/e047efa8f9518c54d00d2e4493b64bc4dba98478, so it should not be working since v2.6.0

From what I checked, without logging in as an admin user, it does not send any cookie with the key `argocd.token`, causing the session to produce an `Internal server error`. There are no logs that are relevant other than this:

```
time="2024-02-07T07:55:59Z" level=info msg="terminal session starting" appNamespace=argo application=argo-cd container=argocd-server namespace=argo podName=argocd-server-645954b5ff-kxjf9 project=default userName=
```

When logged in as an admin user, the `argocd.token` appears in the cookie and it works. 

**To Reproduce**

Main manifest is here: https://github.com/argoproj/argo-cd/blob/v2.10.0/manifests/install.yaml, with these edits:

```yaml
# argocd-cm
data:
  exec.enabled: "true"

# argocd-rbac-cm
data:
  policy.default: role:admin

# argocd-server Role
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create

# argocd-server ClusterRole
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
```

Exec into a known pod with a shell without logging in.

**Expected behavior**

A non logged in user should be able to exec into pods with `--disable-auth` and `policy.default: role:admin` set.

**Screenshots**

![Screenshot 2024-02-07 at 4 42 37 PM](https://github.com/argoproj/argo-cd/assets/13537118/1c3eb644-6902-4c83-b574-8b33782d6a8b)

**Version**

```shell
argocd@argocd-server-645954b5ff-kxjf9:~$ argocd version
argocd: v2.10.0+2175939
  BuildDate: 2024-02-06T14:28:43Z
  GitCommit: 2175939ed6156ddd743e60f427f7f48118c971bf
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Largely irrelevant but this was the only log that was attached.

```
time="2024-02-07T07:55:59Z" level=info msg="terminal session starting" appNamespace=argo application=argo-cd container=argocd-server namespace=argo podName=argocd-server-645954b5ff-kxjf9 project=default userName=
```
