### ISSUE TITLE
Support more ways to scope custom health checks than just GVK globs

### ISSUE THREAD

**Issue by mbbush** [argoproj/argo-cd#17169]
# Summary

Currently argocd supports applying custom health checks to resources by matching their GVK with a glob pattern. This is simple, easy to use, and of limited power to define more complex patterns.

I'd like to allow the patterns to be specified in multiple ways: 
* A Group/Kind glob (for backwards compatibility)
* A Group/Kind regex
* Separate regexes/globs for Group, Kind and Version
* A check against membership in a particular category in the `spec.names.categories` on the resource's CRD

This would also allow bundled health checks to support wildcards, or other more flexible means of targeting. I would want to combine this with a fix for https://github.com/argoproj/argo-cd/issues/16905 which applied some intelligent ordering to which health checks to apply.

# Motivation

For example, I could define a health check for all resources in categories `crossplane` and `managed`, which uses generic crossplane provider conditions, and another for resources with gvk matching `*.customprovider.myorg.com` and categories `crossplane` and `managed`, which uses specific conditions added by one particular crossplane provider. This would allow me to exclude or provide separate healthchecks for e.g. `customprovider.myorg.com/ProviderConfig`, which is _not_ a crossplane managed resource, and uses different conditions, but is in the same api group.

Similarly, I could apply a health check for all resources in categories `crossplane` and `claim`, or `crossplane` and `composite`, using generic crossplane claim/composite conditions. This is quite difficult to implement in the current version of argo, because in general claims and composite resources have user-defined GVKs (the user writes a CompositeResourceDefinition which generates a CustomResourceDefinitions for the composite, and conditionally another CRD for the claim.)

I think this would apply outside of the crossplane ecosystem as well, I'm just not as familiar with commonly used patterns there. 

# Proposal

In the configmap for resource customizations, we could continue to support globs and explicit patterns in the key name, for backwards compatibility, while conditionally ignoring the key name and instead looking for matchers in other fields, based on the presence of a not-null `matchers` key:

```
resource.customizations: |
  external-secrets.io/PushSecret: # existing check, still works unchanged
    health.lua: |
      ...
  crossplane-managed: | # arbitrary name, which must not contain a /
    matchers:
      categories:
        include:
          - literal: crossplane
          - literal: managed
      group:
        include:
          - type: glob
            glob: *.upbound.io
        exclude:
          - type: literal
            literal: some.exception.upbound.io
      version: 
        min: v1beta1
        max: v1
      kind: 
        exclude:
          - ProviderConfig
    health.lua: |
      ...    
```

For the health checks committed to the repository, we could drop support for the `group/Kind` directory structure, and instead have arbitrarily-named directories, each of which would contain a `matchers.yaml` file with the same schema as above, alongside the existing `health.lua`, `health_test.yaml`, and `testdata` files/directories. If maintaining compatibility with custom forks is important, we could also keep the group/Kind directory structure, and use either the depth of directories, or the presence of a `matchers.yaml` file to determine whether to use the directory structure as a matcher or not.

This may require adding caching to https://github.com/argoproj/argo-cd/blob/d5e119c251738afcb5c51296d00cc48e6459b6c8/util/lua/lua.go#L128 to avoid performance regressions.
