### ISSUE TITLE
ArgoCD application with Airflow helm chart 1.12 version fails to get deployed

### ISSUE THREAD

**Issue by alex-slynko** [argoproj/argo-cd#17182]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I can't deploy latest release of Airflow helm chart.

**To Reproduce**

1. Create a new application with the following config
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'airflow-test'
spec:
  project: default
  source:
    repoURL: 'https://airflow.apache.org'
    targetRevision: 1.12.0
    helm:
      releaseName: airflow-test
      version: v3
    chart: airflow
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
2. See the error in UI
```
Unable to create application: application spec for airflow-test is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = illegal filepath in archive: /tmp/d629b287-bcfd-4ca1-b827-33aa871dae80
```

Same output with `targetRevision: 1.11.0` works fine.

**Expected behavior**

Application is created and started to roll out.

**Version**

We have deployed ArgoCD using Helm chart 5.55.x

```shell
argocd: v2.9.5+f943664.dirty
  BuildDate: 2024-01-19T22:59:02Z
  GitCommit: f9436641a616d277ab1f98694e5ce4c986d4ea05
  GitTreeState: dirty
  GoVersion: go1.21.6
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.10.0+2175939
  BuildDate: 2024-02-06T14:28:43Z
  GitCommit: 2175939ed6156ddd743e60f427f7f48118c971bf
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.0+g3fc9f4b
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

The log output using `kubectl logs -n argocd -l app.kubernetes.io/instance=argocd --max-log-requests=12 -f`

```
time="2024-02-12T15:32:13Z" level=info msg="received unary call /application.ApplicationService/UpdateSpec" grpc.method=UpdateSpec grpc.request.claims="{\"exp\":1707824358,\"iat\":1707737958,\"iss\":\"argocd\",\"jti\":\"a96e8382-54c9-4ae2-8789-3638046c4be0\",\"nbf\":1707737958,\"sub\":\"admin\"}" grpc.request.content="%!v(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)" grpc.service=application.ApplicationService grpc.start_time="2024-02-12T15:32:13Z" span.kind=server system=grpc
time="2024-02-12T15:32:13Z" level=info msg="took to get index" seconds=0.155747188
time="2024-02-12T15:32:13Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=TestRepository grpc.service=repository.RepoServerService grpc.start_time="2024-02-12T15:32:13Z" grpc.time_ms=158.056 span.kind=server system=grpc
time="2024-02-12T15:32:13Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://airflow.apache.org,Path:,TargetRevision:1.12.0,Helm:&ApplicationSourceHelm{ValueFiles:[],Parameters:[]HelmParameter{},ReleaseName:airflow-test,Values:,FileParameters:[]HelmFileParameter{},Version:v3,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:airflow,Ref:,}/1.12.0"
time="2024-02-12T15:32:13Z" level=error msg="finished unary call with code Unknown" error="illegal filepath in archive: /tmp/4e9c1acc-ef45-4531-ade7-bf14ef2ba3d5" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-02-12T15:32:13Z" grpc.time_ms=1.479 span.kind=server system=grpc
time="2024-02-12T15:32:13Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec for airflow-test is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = illegal filepath in archive: /tmp/4e9c1acc-ef45-4531-ade7-bf14ef2ba3d5" grpc.code=InvalidArgument grpc.method=UpdateSpec grpc.service=application.ApplicationService grpc.start_time="2024-02-12T15:32:13Z" grpc.time_ms=246.604 span.kind=server system=grpc
time="2024-02-12T15:32:14Z" level=info msg="Alloc=244655 TotalAlloc=76202347 Sys=608803 NumGC=606 Goroutines=938"
```
