### ISSUE TITLE
`argocd.argoproj.io/sync-options: Prune=false` not respected in Application CRD (and thus CLI and UI)

### ISSUE THREAD

**Issue by thesuperzapper** [argoproj/argo-cd#17188]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

## Describe the bug

The [`argocd.argoproj.io/sync-options: Prune=false`](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-prune-resources) annotations for resources are not respected by the Application controller.

The application controller lists these resources as `requiresPruning: true` in the CRD `status.resources[]` field.
This is a problem in two significant places:

1. __The ArgoCD CLI:__
      - When a user runs a `argocd app get -o json` command.
3. __The ArgoCD UI:__
      - The UI will always show these resources in the diff, even if they would not be removed during an actual sync. 
      - NOTE: this is also true if `argocd.argoproj.io/compare-options: IgnoreExtraneous` is set on the resource.

## To Reproduce

1. __Create an ArgoCD application called `my-app` (it doesn't matter what is in it):__

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
```

2. __Create a ConfigMap that shares the `app.kubernetes.io/instance` label with the ArgoCD app and `argocd.argoproj.io/sync-options: Prune=false` annotation:__

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/instance: guestbook
data:
  SOME_KEY: "SOME_VALUE"
```

3. __Observe that the `argocd app get` command shows the ConfigMap as `requiresPruning: true`:__

```shell
ARGOCD_NAMESPACE="argocd"
ARGOCD_USERNAME="admin"
ARGOCD_PASSWORD=$(kubectl -n "argocd" get secret "argocd-initial-admin-secret" -o jsonpath="{.data.password}" | base64 -d)

# log in to argocd
export ARGOCD_OPTS="--port-forward --port-forward-namespace '${ARGOCD_NAMESPACE}'"
argocd login --username "${ARGOCD_USERNAME}" --password "${ARGOCD_PASSWORD}"

# get the application as JSON
_app_json=$(argocd app get "guestbook" -o json --refresh)

# extract the `status.resources` array from the JSON
_app_resources=$(echo "$_app_json" | jq -c '.status.resources[]?')

# print the resources
echo "$_app_resources"

# OUTPUT:
# {"version":"v1","kind":"ConfigMap","namespace":"default","name":"my-configmap","status":"OutOfSync","requiresPruning":true}
# {"version":"v1","kind":"Service","namespace":"default","name":"guestbook-ui","status":"Synced","health":{"status":"Healthy"}}
# {"group":"apps","version":"v1","kind":"Deployment","namespace":"default","name":"guestbook-ui","status":"Synced","health":{"status":"Healthy"}}
```

4. __Observe that the UI shows the resource as requiring pruning:__

![Screenshot 2024-02-12 at 12 34 18](https://github.com/argoproj/argo-cd/assets/5735406/80b4a339-db4e-4b63-a8c8-0f3672a70f3a)

## Expected behavior

Both the CRD itself (and therefore ArgoCD CLI and UI) correctly reflect the presence of `argocd.argoproj.io/sync-options: Prune=false`.

For example, in the above situation, I would expect to see the `status.resources` like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  ...
status:
  ...
  resources:
    - version: v1
      kind: ConfigMap
      name: my-configmap
      namespace: default

      ## \/ this part should show as `false`, not `true`  \/ 
      requiresPruning: false

      ## NOTE: this will probably still need to be OutOfSync, until we can create a new "ignored" status:
      ##       https://github.com/argoproj/argo-cd/issues/14338
      status: OutOfSync
```

## Version

```shell
argocd: v2.10.0+2175939.dirty
  BuildDate: 2024-02-06T15:31:09Z
  GitCommit: 2175939ed6156ddd743e60f427f7f48118c971bf
  GitTreeState: dirty
  GoVersion: go1.21.6
  Compiler: gc
  Platform: darwin/arm64
```

## Other Notes

There is a similar issue with `argocd.argoproj.io/compare-options: IgnoreExtraneous` (see https://github.com/argoproj/argo-cd/issues/14338), but that will be more complex to fix, because it probably requires a new "resource status" of "ignored" as it is not correct to say that an ignored resource is "Synced".
