### ISSUE TITLE
store-overrrides does not work with .argocd-source and sourceType plugin

### ISSUE THREAD

**Issue by 1337andre** [argoproj/argo-cd#17195]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

according docs https://argo-cd.readthedocs.io/en/stable/user-guide/parameters/#store-overrides-in-git plugins could/should work with argocd-source file, isn't it?
> The .argocd-source.yaml file is used during manifest generation and overrides application source fields, such as kustomize, helm etc.

When i try to deploy a app with plugin stuff it does not work

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    name: myserver
    namespace: mynamespace
  project: myproject
  source:
    path: manifests
    repoURL: git@git.blub.de:argo/myrepo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
```

the corresponding argocd-source file looks like this
$cat .argocd-source-myapp.yaml
```
plugin:
  name: lovely-vault
  env:
  - name: LOVELY_HELM_VALUES
    value: 'values.yaml integration.yaml'
```

But the app was not generated with plugin stuff.

<img width="854" alt="Screenshot 2024-02-13 at 12 44 39" src="https://github.com/argoproj/argo-cd/assets/32708635/2ea6557d-aa7a-43e4-9cf6-b190acbd6824">

When try to deploy the app with plugin stuff it works fine.

given the same app, with with plugin config

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    name: myserver
    namespace: mynamespace
  project: myproject
  source:
    path: manifests
    repoURL: git@git.blub.de:argo/myrepo.git
    targetRevision: HEAD
    plugin:
      name: lovely-vault
      env:
      - name: LOVELY_HELM_VALUES
        value: 'values.yaml integration.yaml'
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
```

<img width="853" alt="Screenshot 2024-02-13 at 12 47 47" src="https://github.com/argoproj/argo-cd/assets/32708635/f99d2d2e-3dd2-4470-8bcc-838fd5903061">

**Expected behavior**

app generation should work with store-overrides

**Version**

```shell
argocd: v2.10.0+2175939
  BuildDate: 2024-02-06T14:28:43Z
  GitCommit: 2175939ed6156ddd743e60f427f7f48118c971bf
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
