### ISSUE TITLE
PostDelete Hook with other resources than pod/job (like SA)

### ISSUE THREAD

**Issue by dtrouillet** [argoproj/argo-cd#17191]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I create a PostDelete hook with other resources like ServiceAccount, Role, RoleBinding, even if the hook succeed, the Application stay in Deleted state.

**To Reproduce**

Create resources like ServiceAccount, Role, RoleBinding and Pod/Job that use this ServiceAccount to works.

You can view this repo : https://github.com/dtrouillet/postdelete-hook-issue2 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2-damien
  namespace: argocd
spec:
  destination:
    namespace: test2-damien
    server: https://XXXXX
  project: default
  revisionHistoryLimit: 10
  sources:
    - path: .
      repoURL: https://github.com/dtrouillet/postdelete-hook-issue2.git
      targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

Application is deleted after hook execution

**Screenshots**

**Version**

argocd: v2.10.0+2175939
BuildDate: 2024-02-06T14:28:43Z
GitCommit: https://github.com/argoproj/argo-cd/commit/2175939ed6156ddd743e60f427f7f48118c971bf
GitTreeState: clean
GoVersion: go1.21.3
Compiler: gc
Platform: linux/amd64

**Logs**

No logs
