### ISSUE TITLE
Upgrading to Argo CD 2.10.1 drop reconciliation/sync to nearly a zero. 

### ISSUE THREAD

**Issue by daftping** [argoproj/argo-cd#17257]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
After upgrading Argo CD from 2.9.2 to 2.10.1 it is unable to reconcile almost anything. Most of the Applications are stuck in the `Progressing` or `OutOfSync` state, metrics drop close to zero.

Sharding is **not** used. (1 replica in StatefulSet with default configuration)

**To Reproduce**
~~We are unable to reproduce in a similar dev environment with a handful of apps and only a few clusters connected.~~
see below https://github.com/argoproj/argo-cd/issues/17257#issuecomment-1961865002

**Expected behavior**
Argo CD should operate as usual after the upgrade.

**Screenshots**
~9:40 Argo CD was upgraded to 2.10.1. ~10:45 it was rolled back to 2.9.2
Application Controller
![image](https://github.com/argoproj/argo-cd/assets/21245083/14272ee8-23a9-4ca5-a491-85de448ed08b)
![image](https://github.com/argoproj/argo-cd/assets/21245083/13604fa8-b46e-4daf-83a5-2ff1a435caa1)
![Screenshot from 2024-02-20 14-11-48](https://github.com/argoproj/argo-cd/assets/21245083/13498db6-9a7f-4d91-a795-a6908822c277)

Repo Server
![image](https://github.com/argoproj/argo-cd/assets/21245083/ce946dfc-80ee-488b-bc5c-2e5cd1066de4)

Redis
![image](https://github.com/argoproj/argo-cd/assets/21245083/cc69413e-91f6-42b8-9b93-8aac80775058)

**Config**
```json
kubectl get cm argocd-cmd-params-cm -o json | jq .data
{
  "application.namespaces": "",
  "applicationsetcontroller.enable.leader.election": "true",
  "applicationsetcontroller.enable.new.git.file.globbing": "true",
  "applicationsetcontroller.enable.progressive.syncs": "true",
  "applicationsetcontroller.log.format": "text",
  "applicationsetcontroller.log.level": "debug",
  "applicationsetcontroller.policy": "sync",
  "controller.log.format": "text",
  "controller.log.level": "debug",
  "controller.operation.processors": "10",
  "controller.repo.server.timeout.seconds": "60",
  "controller.self.heal.timeout.seconds": "5",
  "controller.status.processors": "20",
  "otlp.address": "",
  "redis.server": "redis-ha-haproxy:6379",
  "repo.server": "argo-cd-argocd-repo-server:8081",
  "reposerver.log.format": "text",
  "reposerver.log.level": "debug",
  "reposerver.parallelism.limit": "0",
  "server.basehref": "/",
  "server.dex.server": "https://argo-cd-argocd-dex-server:5556",
  "server.dex.server.strict.tls": "false",
  "server.disable.auth": "false",
  "server.enable.gzip": "true",
  "server.insecure": "false",
  "server.log.format": "text",
  "server.log.level": "debug",
  "server.repo.server.strict.tls": "false",
  "server.rootpath": "",
  "server.staticassets": "/shared/app",
  "server.x.frame.options": "sameorigin"
}

kubectl get cm argocd-cm -o json | jq .data
{
  "admin.enabled": "false",
  "application.instanceLabelKey": "argocd.argoproj.io/instance",
  "dex.config": "<redacted>",
  "exec.enabled": "false",
  "help.chatText": "<redacted>",
  "help.chatUrl": "<redacted>",
  "resource.customizations": "<redacted>",
  "resource.links": "<redacted>",
  "server.rbac.log.enforce.enable": "false",
  "statusbadge.enabled": "true",
  "timeout.hard.reconciliation": "0s",
  "timeout.reconciliation": "180s",
  "ui.bannercontent": "<redacted>",
  "ui.bannerpermanent": "true",
  "url": "<redacted>"
}

```

**Version**

```shell
argocd: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:56:39Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:37:43Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.0+g3fc9f4b
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0

```

**Logs**

Lots of messages
![Screenshot from 2024-02-20 13-24-50](https://github.com/argoproj/argo-cd/assets/21245083/7ca5367e-5154-4473-a4d5-d51c9a1f69d6)

From **20000** to **40000** messages below per cluster per 5 min
```
"Checking if cluster <cluster> with clusterShard 0 should be processed by shard 0"
```

**Comment by selfuryon** [comment]
Yeah, the same thing

**Comment by crenshaw-dev** [comment]
This was meant to fix it: https://github.com/argoproj/argo-cd/pull/17204

Can you try 2.10.0 and see if you hit the same issue?

**Comment by prune998** [comment]
I'm on 2.10.1 and everything is fine for me... but I only have few clusters and few Apps

**Comment by Hariharasuthan99** [comment]
We are facing a similar issue but when we enable dynamic cluster sharding and run application-controller as a **deployment** with 2 replicas(We need more than 1). I made application-controller **'statefulset'** replica 0 and tried deleting the statefulset itself to ensure the deployment runs properly. But syncs stopped working with below error

![image](https://github.com/argoproj/argo-cd/assets/24827116/71a91220-9eed-443e-b4f4-7a41961fbf01)

Attaching application-controller **deployment** pod logs 
[argocd-application-controller-6bdfc8586c-5vpcp-argocd-application-controller.log](https://github.com/argoproj/argo-cd/files/14383378/argocd-application-controller-6bdfc8586c-5vpcp-argocd-application-controller.log)

However when we run application-controller as **statefulest** everything works as expected. But we are interested in the dynamic cluster sharding feature hence tried running it as deployment.

**Comment by daftping** [comment]
> This was meant to fix it: #17167
> 
> Can you try 2.10.0 and see if you hit the same issue?

Same behaviour on 2.10.0
I am highly suspicious of the newly introduced rate-limiting feature
https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#rate-limiting-application-reconciliations

When I create 100 Applications reconciliation drops to zero and recovers after a while
![image](https://github.com/argoproj/argo-cd/assets/21245083/8bcd251c-fa75-46dc-9f05-8f04045fb044)

Any mass operations cause this, in bigger environments it is a permanent state.

I am trying to reproduce it on a vanilla Argo CD deployed on Kind so we can have steps to reproduce.

**Comment by daftping** [comment]
I forgot to mention restarting application-controller helps for a short period, it processes a bunch of operations and stuck again.

**Comment by daftping** [comment]
I have repro steps:

Create cluster and install Argo CD
```bash
kind create cluster -n argocd
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

Create AppProject with `orphanedResources` enabled.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-orphaned-resources
  # namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  orphanedResources:
    warn: false
```

Create 225 Apps

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-loadtest
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - prefix: a
                - prefix: b
                - prefix: c
                - prefix: d
                - prefix: e
                - prefix: f
                - prefix: g
                - prefix: h
                - prefix: i
                - prefix: j
                - prefix: k
                - prefix: l
                - prefix: m
                - prefix: n
                - prefix: o
          - list:
              elements:
                - number: 10
                - number: 11
                - number: 12
                - number: 13
                - number: 14
                - number: 15
                - number: 16
                - number: 17
                - number: 18
                - number: 19
                - number: 20
                - number: 21
                - number: 22
                - number: 23
                - number: 24

  template:
    metadata:
      name: "argocd-loadtest-{{.prefix}}-{{.number}}"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default-orphaned-resources
      sources:
      - repoURL: "https://github.com/argoproj/argocd-example-apps.git"
        path: helm-guestbook
        helm:
          valuesObject:
            replicaCount: 0
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

```

Go to UI
`kubectl port-forward svc/argocd-server -n argocd 8080:443`

Argo CD is stuck at around 80 apps and really slowly processing them afterwards
![image](https://github.com/argoproj/argo-cd/assets/21245083/3db1d0c4-f6a7-418c-9746-d68c68d6472c)

reconcile_count barely changing
`kubectl port-forward pod/argocd-application-controller-0 8082:8082`
```
while true
do 
    sleep 1; 
    curl -s http://localhost:8082/metrics | grep argocd_app_reconcile_count | cut -d' ' -f2
done
```
```
25905
25905
25906
25906
25906
25906
25906
25906
25906
25907
25907
25907
25907
25908
25909
25909
25909
25909
25909
25909
25909
25909
25909
25909
25909
25909
25909
25910
25911
25912
```

`orphanedResources` probably is not related, it just helps to generate the load.

@crenshaw-dev could you please advise what else can I check to help find the root cause?

**Comment by crenshaw-dev** [comment]
Thanks for the analysis, @daftping! @gdsoumya can you take a look at the rate limiting code and see if it's a viable explanation for this issue?

**Comment by jessesuen** [comment]
Whenever reconcilliation drops to zero, controller deadlocks may be culpable. @daftping - when this happens, can we get a dump of stacktrace of the controller to see if this might be the case?

> the workqueue dedups the items so it shouldn't be putting in the same item multiple times

This is correct. Workqueues will dedup `Add()` calls by name.

**Comment by gdsoumya** [comment]
That is possible we had some deadlock issues before causing the controller to freeze

**Comment by daftping** [comment]
> Just reading the issue, I am not sure if the behavior is expected due to the rate limiter. We added 2 rate limiters 1 - global Bucket limiter and 2 - per item ExponentialBackoff limiter. By default the exp. limiter is disabled and I don't see the it being turned on so the only possible limiter being on is the Bucket limiter and the defaults for that are as follows :
> 
> ```
> WORKQUEUE_BUCKET_SIZE - The number of items that can be queued in a single burst. Defaults to 500.
> WORKQUEUE_BUCKET_QPS - The number of items that can be queued per second. Defaults to 50.
> ```
> 
> So it should at least let 500 items in the queue in the burst and then 50 items per second if queue get's full. In that case 225 apps should easily be handled in the burst as it has enough capacity. @crenshaw-dev correct me if I am wrong but I believe that the workqueue dedups the items so it shouldn't be putting in the same item multiple times until it's processed so I am not sure if the issue is due to the rate limiter. But I will dig more and get back in case I find anything suspicious with the limiter.

@gdsoumya setting bigger values got Global limiter improves reconciliation performance for the report above. It is somehow related.
```yaml
 - name: WORKQUEUE_BUCKET_SIZE
   value: 5000 
 - name: WORKQUEUE_BUCKET_QPS
   value: 500
```
Is it possible to disable all rate limiters alltogether to validate this assumption?

**Comment by daftping** [comment]
> Whenever reconcilliation drops to zero, controller deadlocks may be culpable. @daftping - when this happens, can we get a dump of stacktrace of the controller to see if this might be the case?
> 
> > the workqueue dedups the items so it shouldn't be putting in the same item multiple times
> 
> This is correct. Workqueues will dedup `Add()` calls by name.
@jessesuen 
I have limited Go lang knowledge. How can I do that?

**Comment by gdsoumya** [comment]
> Is it possible to disable all rate limiters altogether to validate this assumption?

Currently it's not possible to completely disable the limiter, the simplest way to simulate a disabled bucket limiter would be to set a very large value for both QPS and bucket size like you have done. I would set a even higher limit something like 10000000000 for both

**Comment by daftping** [comment]
> > Is it possible to disable all rate limiters altogether to validate this assumption?
> 
> @daftping Currently it's not possible to completely disable the limiter, the simplest way to simulate a disabled bucket limiter would be to set a very large value for both QPS and bucket size like you have done. I would set a even higher limit something like 10000000000 for both

I've set it to

**Comment by daftping** [comment]
> > Is it possible to disable all rate limiters altogether to validate this assumption?
> 
> @daftping Currently it's not possible to completely disable the limiter, the simplest way to simulate a disabled bucket limiter would be to set a very large value for both QPS and bucket size like you have done. I would set a even higher limit something like 10000000000 for both

I've set them both to 10000000000 as you suggested and all 225 apps were created and fully in sync in about 50 seconds. No issues or halts whatsoever.

```yaml
- name: WORKQUEUE_BUCKET_SIZE
  value: "10000000000"
- name: WORKQUEUE_BUCKET_QPS
  value: "10000000000"
```

value of `argocd_app_reconcile_count` every second
```
20
20
42
79
84
110
152
165
193
206
227
246
265
295
321
342
359
378
445
591
721
831
918
1052
1139
1248
1357
1466
1557
1692
1772
1896
1978
2041
2135
2236
2300
2391
2486
2590
2758
2817
2836
2857
2876
2896
2897
2897
```

Thank you suggestion @gdsoumya , at least we have a workaround now.
