### ISSUE TITLE
Allows `templatePatch` to load YAML config values

### ISSUE THREAD

**Issue by datlife** [argoproj/argo-cd#17255]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Related to https://github.com/argoproj/argo-cd/pull/14893

`templatePatch` doesn't reconstruct YAML config properly. Apparently it converts to JSON object first and then converts back to YAML.

**To Reproduce**

I have  argocd config YAML files for different environments to allow ApplicationSet generate applications. This is a sample of the config.yaml
```yaml
# apps/chatbot/overlays/on-prem-cluster/argocd-config.yaml 
appName: chatbot
env: staging
cluster: 
  name: on-prem-cluster
  namespace: chatbot
autoSync: true
syncPolicy:
  automated:
    prune: true 
    selfHeal: false
    allowEmpty: false
```

Here is my applicationSet definition:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chatbot-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: redacted
      revision: redacted
      files:
        - path: apps/chatbot/overlays/*/argocd-config.yaml 
  template:
    metadata:
      name: '{{ .env }}-{{ .appName }}'
    spec:
      project: "chatbot"
      source:
        directory:
          recurse: false
        repoURL:  redacted
        targetRevision:  redacted
        path: '{{.path.path}}'
      destination:
        name: '{{ .cluster.name }}'
        namespace: '{{ .cluster.namespace }}'
  templatePatch: |
    {{- if .autoSync }}
    spec:
      syncPolicy: 
      {{ .syncPolicy | toYaml}}
    {{- end }}
```
**Expected behavior**

I expect the `templatePatch` being able to generate nested YAML objects. In the above example, an application manifest should be as the following:
```
project: chatbot
source:
  repoURL: redacted
  path: apps/chatbot/overlays/on-prem-cluster
  targetRevision: redacted
destination:
  namespace: chatbot
  name: on-prem-cluster
syncPolicy:
  automated:
    prune: true
    selfHeal: false
    allowEmpty: false
```

However, in reality, `syncPolicy` was ignored and empty. However, if I change the `templatePatch` to this format, it works:
```
  templatePatch: |
    {{- if .autoSync }}
    spec:
      syncPolicy: 
        automated: 
          prune: {{ .syncPolicy.automated.prune}}
          selfHeal: {{ .syncPolicy.automated.selfHeal}}
          allowEmpty: {{ .syncPolicy.automated.allowEmpty}}
    {{- end }}

```

**Version**

```shell
$ argocd version     
argocd: v2.10.1+a79e0ea.dirty
  BuildDate: 2024-02-14T22:07:13Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: dirty
  GoVersion: go1.21.7
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.10.1+a79e0ea.dirty
  BuildDate: 2024-02-14T22:07:13Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: dirty
  GoVersion: go1.21.7
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v4.5.4 2022-03-28T23:06:20Z
  Helm Version: v3.13.3+gc8b9489
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Comment by datlife** [comment]
If I updated the string value of `templatePatch` to JSON, it works.

```
  templatePatch: |- 
  {
    {{- if .autoSync }}
    "spec": {
      "syncPolicy": {{ .syncPolicy | toJson}}
    }
    {{- end }}
  }'
```

**Comment by crenshaw-dev** [comment]
I'd bet quite a bit of money that the problem is indentation. Helm templates make heavy use of an `indent` function.

JSON is YAML, so I'd recommend doing this:

```yaml
  templatePatch: |
    {{- if .autoSync }}
    spec:
      syncPolicy: {{ .syncPolicy | toJson }}
    {{- end }}
```

As a matter of fact, I'd recommend _always_ piping variables to `toJson` so that things like strings get properly escaped.

**Comment by datlife** [comment]
Thanks! In the documentation, it said it accepts YAML object as templatePatch so I thought it would be trivial to use YAML object. I'll stick to JSON format for now

**Comment by crenshaw-dev** [comment]
YAML is never trivial. 😆 But it was a fair expectation. If you can think of a good docs update that will help others, I'd be happy to review.

**Comment by jurgenweber** [comment]
How do you get the variables from the repo's yaml file to work in the templatePatch? For me, it says the key doesn't exist;

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: snap
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators: # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  bpcyber.com/environment-color: mauve   # TODO remove when ready
                  bpcyber.com/environment-stage: staging # TODO remove when ready
                  bpcyber.com/environment-type: snap
              # from the server k8s secrets, .name and .server are exposed
              values:
                color: '{{ index .metadata.labels "bpcyber.com/environment-color" }}'
                stage: '{{ index .metadata.labels "bpcyber.com/environment-stage" }}'
                type:  '{{ index .metadata.labels "bpcyber.com/environment-type" }}'
          # this is cool, but it assumes a 1 to 1 relationship repo to service, but we have one repo, many services
          # - scmProvider: # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/
          #     cloneProtocol: ssh
          #     filters:
          #       - labelMatch: argodeploy
          #     github:
          #       # The GitHub organization to scan.
          #       organization: engineering
          #       # For GitHub Enterprise: the api/v3 is important, needed this to make it authenticate
          #       api: https://github.bpcyber.com/api/v3/
          #       # If true, scan every branch of every repository. If false, scan only the default branch. Defaults to false.
          #       allBranches: false
          #       appSecretName: argocd-github-app-private-key
          - git:
              repoURL: "git@github.xxx.com:engineering/helm-values.git"
              revision: master
              files:
                - path: "services/**.yaml"
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  # This looks cool; See documentation for "Progressive Syncs"
  strategy: {}
  # This sync policy pertains to the ApplicationSet, not to the Applications it creates.
  syncPolicy: {}
  # These fields are identical to the Application spec.
  # The generator's template field takes precedence over the spec's template fields
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
  template:
    metadata:
      name: '{{ .name }}-{{ .fullnameOverride }}'
      # scmProvider name: '{{ .name }}-{{ .repository }}'
    spec:
      project: '{{ .name }}-services'
      destination:
        name: '{{ .name }}'
        namespace: snap
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: []
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#template-patch
  templatePatch: |
    spec:
      sources:
        - repoURL: "https://raw.github.bpcyber.com/engineering/helm-charts/gh-pages/"
          chart: services
          # https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/#helm
          targetRevision: '{{ .servicesChartVersion | toJson }}'
          helm: # https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
            releaseName: '{{ .fullnameOverride }}'
            valueFiles:
              - $values/product/snap.yaml
              - $values/services/{{ .fullnameOverride }}.yaml
              - $values/stage/{{ .values.stage }}.yaml
              - $values/environments/{{ .name }}.yaml
              {{- if ne .parentService "iamtheparent" }}
              - $values/environments/{{ .name }}/{{ .parentService }}.yaml
              {{- end }}
              - $values/environments/{{ .name }}/{{ .fullnameOverride }}.yaml
        - repoURL: "git@github.xxx.com:engineering/helm-values.git"
          targetRevision: master
          ref: values
```

**Comment by jurgenweber** [comment]
How do you get the variables from the repo's yaml file to work in the templatePatch? For me, it says the key doesn't exist;

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: snap
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators: # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  xxx.com/environment-color: mauve   # TODO remove when ready
                  xxx.com/environment-stage: staging # TODO remove when ready
                  xxx.com/environment-type: snap
              # from the server k8s secrets, .name and .server are exposed
              values:
                color: '{{ index .metadata.labels "xxx.com/environment-color" }}'
                stage: '{{ index .metadata.labels "xxx.com/environment-stage" }}'
                type:  '{{ index .metadata.labels "xxx.com/environment-type" }}'
          # this is cool, but it assumes a 1 to 1 relationship repo to service, but we have one repo, many services
          # - scmProvider: # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/
          #     cloneProtocol: ssh
          #     filters:
          #       - labelMatch: argodeploy
          #     github:
          #       # The GitHub organization to scan.
          #       organization: engineering
          #       # For GitHub Enterprise: the api/v3 is important, needed this to make it authenticate
          #       api: https://github.xxx.com/api/v3/
          #       # If true, scan every branch of every repository. If false, scan only the default branch. Defaults to false.
          #       allBranches: false
          #       appSecretName: argocd-github-app-private-key
          - git:
              repoURL: "git@github.xxx.com:engineering/helm-values.git"
              revision: master
              files:
                - path: "services/**.yaml"
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  # This looks cool; See documentation for "Progressive Syncs"
  strategy: {}
  # This sync policy pertains to the ApplicationSet, not to the Applications it creates.
  syncPolicy: {}
  # These fields are identical to the Application spec.
  # The generator's template field takes precedence over the spec's template fields
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
  template:
    metadata:
      name: '{{ .name }}-{{ .fullnameOverride }}'
      # scmProvider name: '{{ .name }}-{{ .repository }}'
    spec:
      project: '{{ .name }}-services'
      destination:
        name: '{{ .name }}'
        namespace: snap
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: []
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#template-patch
  templatePatch: |
    spec:
      sources:
        - repoURL: "https://raw.github.xxx.com/engineering/helm-charts/gh-pages/"
          chart: services
          # https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/#helm
          targetRevision: '{{ .servicesChartVersion | toJson }}'
          helm: # https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/
            releaseName: '{{ .fullnameOverride }}'
            valueFiles:
              - $values/product/snap.yaml
              - $values/services/{{ .fullnameOverride }}.yaml
              - $values/stage/{{ .values.stage }}.yaml
              - $values/environments/{{ .name }}.yaml
              {{- if ne .parentService "iamtheparent" }}
              - $values/environments/{{ .name }}/{{ .parentService }}.yaml
              {{- end }}
              - $values/environments/{{ .name }}/{{ .fullnameOverride }}.yaml
        - repoURL: "git@github.xxx.com:engineering/helm-values.git"
          targetRevision: master
          ref: values
```
