### ISSUE TITLE
Parameter substitution does not work correctly with nested matrix generators in the second child (only when goTemplate=true)

### ISSUE THREAD

**Issue by ricoapon** [argoproj/argo-cd#17261]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a matrix generator, the parameters from the first child should be substituted in the second child. When using two matrix generators (one nested in the other), you have two options for applying them:

1. matrix(child1, matrix(child2, child3))
2. matrix(matrix(child1, child2), child3)

Assuming you have parameter outputs from child1 AND child2 that are used in child3, it should not matter (in theory) which of the options you use. I found out that using the first option does not work when using goTemplate=true, but it does when using goTemplate=false.

**To Reproduce**

I created a very simple example with only lists that shows the issue.

```
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - key1: value1
          - matrix:
              generators:
                - list:
                    elements:
                      - key2: value2
                - list:
                    elements:
                      - substitute1: '{{ .key1 }}'
                        substitute2: '{{ .key2 }}'
```
This is the same as option 1 I mentioned above. And this gives an error:
```
failed to get params for second generator in the matrix generator: child generator returned an error on parameter generation: failed to replace parameters in generator: failed to deeply replace JSON field contents: failed to execute go template {{ .key2 }}: template: :1:3: executing "" at <.key2>: map has no entry for key "key2"
```

Now when you turn off goTemplate, it works just fine:
```
spec:
  generators:
    - matrix:
        generators:
         - matrix:
              generators:
                - list:
                    elements:
                      - key1: value1
                - list:
                    elements:
                      - key2: value2
         - list:
             elements:
               - substitute1: '{{ key1 }}'
                 substitute2: '{{ key2 }}'
```

And if you use option 2, it also works just fine.
```
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
         - matrix:
              generators:
                - list:
                    elements:
                      - key1: value1
                - list:
                    elements:
                      - key2: value2
         - list:
             elements:
               - substitute1: '{{ .key1 }}'
                 substitute2: '{{ .key2 }}'
```

**Expected behavior**

Substitution of parameters for the matrix generator works the same, independent of applied order.

**Version**

```shell
argocd: v2.9.2+c5ea5c4
  BuildDate: 2023-11-20T18:17:07Z
  GitCommit: c5ea5c4df52943a6fff6c0be181fde5358970304
  GitTreeState: clean
  GoVersion: go1.20.11
  Compiler: gc
  Platform: linux/amd64
```

**Comment by rarexixi** [comment]
This example will also report an error：`failed to get params for second generator in the matrix generator: child generator returned an error on parameter generation: failed to replace parameters in generator: failed to execute go template {{index .metadata.labels "chj.cloud/env"}}`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-cm-test-matrix
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://gitee.com/rarexixi/argocd-appset-generator.git
          revision: HEAD
          directories:
          - path: config-map/*
          - path: "config-map/logs"
            exclude: true
          values:
            basename: '{{.path.basename}}'
      - clusters:
          selector:
            matchLabels:
              chj.cloud/group: dip
          values:
            basename: '{{index .metadata.labels "rarexixi/env"}}' # report an error
  template:
    metadata:
      name: 'cm-test-matrix-{{.values.basename}}-{{index .metadata.labels "rarexixi/env"}}' # work well 
      labels:
        appset-name: appset-cm-test-matrix
    spec:
      project: default
      source:
        repoURL: https://gitee.com/rarexixi/argocd-appset-generator.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
        namespace: dip-system
```

**Comment by llavaud** [comment]
I had similar issue and found a workaround by adding an additional layer of Helm templating:

```yaml
      - clusters:
          selector:
            matchLabels:
              rarexixi/group: dip
          values:
            basename: 
'{{- printf "{{- `{{ index .metadata.labels "rarexixi/env" }}` -}}" -}}'
```

It seems the matrix generator do another round of Helm templating when adding values on the second generator, welcome Helmception... 😵

**Comment by rarexixi** [comment]
@llavaud Thanks，It works like this:
```
      - clusters:
          selector:
            matchLabels:
              chj.cloud/group: dip
          values:
            env: '{{- printf `{{ index .metadata.labels "chj.cloud/env" }}` -}}'
```

**Comment by llavaud** [comment]
> @llavaud Thanks，It works like this:
> 
> ```
>       - clusters:
>           selector:
>             matchLabels:
>               chj.cloud/group: dip
>           values:
>             env: '{{- printf `{{ index .metadata.labels "chj.cloud/env" }}` -}}'
> ```

yes I just updated, I paste my code that live in an Helm Chart, so I have another Helm level ;)

**Comment by andrii-korotkov-verkada** [comment]
Can this be considered resolved?

**Comment by ricoapon** [comment]
@andrii-korotkov-verkada I don't think so. Workarounds have been given, that is nice. However, I still consider it a bug that should be solved in ArgoCD. And as far as I know, the bug is still not fixed.

But that is only my opinion. I am not aware of conventions used for the ArgoCD project. If bugs get closed because there is a workaround, then that is how it shall go. That is not my call to make.

**Comment by OpenGuidou** [comment]
I confirm that the issue is still present, and I would complement with an interesting case:

When using matrix of matrix, then it works for the params from the first matrix, not for the params in the same matrix:

```
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - list:
                    elements:
                      - key1: value1
                - list:
                    elements:
                      - key2: value2
          - matrix:
              generators:
                - list:
                    elements:
                      - key3: value3
                - list:
                    elements:
                      - substitute1: '{{ .key1 }}'
                        substitute2: '{{ .key2 }}'
                        substitute3: '{{ .key3 }}'
```

key1 and key2 are resolved, not key3

**Comment by OpenGuidou** [comment]
After a bit of debugging, I understood why:

In a matrix case, you should be able to use values from your first generator as a variable inside your second generator.
This is thanks to the `InterpolateGenerator`
For example:

```yaml
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - key1: value1
          - list:
              elements:
                - key2: "{{ .key1 }}
```
"key2" will have value "value1".


Now, in a matrix of matrix, the second level of matrix is considered first as a raw string by the code.

The InterpolationGenerator is handling the second matrix as a string and trying to replace the variables inside.

```yaml
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix (1):
        generators:
          - matrix (2):
              generators:
                - list (1):
                    elements:
                      - key1: value1
                - list (2):
                    elements:
                      - key2: value2
          - matrix (3):
              generators:
                - list (3):
                    elements:
                      - key3: value3
                - list (4):
                    elements:
                      - substitute1: '{{ .key1 }}'
                        substitute2: '{{ .key2 }}'
                        substitute3: '{{ .key3 }}'
```

List (2) can use values from list (1), thanks to the behavior explained earlier.
Then matrix (3) is handled as the second element of a matrix, so templatized as a whole.

All keys defined in matrix (2) are replaced, and all the variables not found are replaced by the string value `<no value>`.

When running the Interpolation between list (3) and list (4), the variables having been replaced by `<no value>`, they are not handled as variables anymore, so not replaced.

We can also note that thanks to that behavior, it is possible to use variables inside selectors, something that is not coded for directly.

Example:
```yaml
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix (1):
        generators:
          - matrix (2):
              generators:
                - list (1):
                    elements:
                      - key1: value1
                - list (2):
                    elements:
                      - key2: value2
          - matrix (3):
              generators:
                - list (3):
                    elements:
                      - key3: value3
                - list (4):
                    elements:
                      - substitute1: '{{ .key1 }}'
                        substitute2: '{{ .key2 }}'
                        substitute3: '{{ .key3 }}'
                  selector:
                    matchLabels:
                       substitute1:  '{{ .key1 }}'
```

This is only possible (and I found existing cases where it is !) in a matrix of matrix use case, but not for the regular usages.

I think we should align all that so that it works in all cases.
