### ISSUE TITLE
ArgoCD and Gcloud Workload Identity Improvements

### ISSUE THREAD

**Issue by withnale** [argoproj/argo-cd#17279]
We make extensive use of ArgoCD to bootstrap our Kubernetes clusters and we have many clusters we are constantly deploying so our bootstrap code is exercised daily. Below are the steps required to enable ArgoCD throughout our estate.

Our main goals are:

- to avoid generating and storing explicit credentials for git repositories
- to avoid generating and storing explicit credentials for OCI registries

NB: I have deliberately tried to consolidate all of the work to get Workload Identity working in the current ArgoCD release below, since this is not well documented at present and I had to piece together information deep within the comments of multiple issues as well as the source code to get this working.

I am aware of the discussion in the issue https://github.com/argoproj/argo-cd/issues/10218 and the preference not to "reinvent the wheel" and delegate the responsibility for this to a separate deployment of the External Secrets Operator. However, this doesn't provide for a very clean solution when you wish for the ArgoCD to be the first thing to be bootstrapped onto a cluster.

The work to support Workload Identity for Source Repositories introduced a `gcpServiceAccountKey`field to the `Secret` manifest. Although this is still very verbose, it would be great if this approach would also work for OCI registries since it is 
possible to login to OCI registries using this token, and it is already available for git registries. However, after looking through the code it's clear that this is only useable for git repos. 

**Would you accept a PR to allow this to be used for OCI repos?** This would alleviate the need for an initContainer in the approaches outlined below.

In the longer term it would be great if this setup could be made much cleaner. There is a lot of complexity here and it would be very easy to mess up with so many moving parts. In particular the use of a gcpServiceAccount key seems very complex with a great deal of substitution required just to consume a token that is already mounted within the container.

## Current Implementation

We use helm to install ArgoCD and fortunately the chart is pretty flexible allowing for `initContainers` and additional `volumes` to be defined from the `values.yaml` and so these instructions below work without chart modification.

### Helm OCI Support to Google Artifact Registry using Workload Identity

The approach to enable this is broadly outlined in the following issue: https://github.com/argoproj/argo-cd/issues/11492

This generates a initContainer to configure the repoServer with gcloud docker credentials, and shares the necessary volumes with the main container.

```yaml
# values.yaml
repoServer:
  volumes:
    - name: docker-credential-gcr
      emptyDir: {}
    - name: docker-config
      emptyDir: {}
  volumeMounts:
    - mountPath: /home/argocd/.docker
      name: docker-config
    - name: docker-credential-gcr
      mountPath: /usr/local/bin/docker-credential-gcr
      subPath: docker-credential-gcr
      readOnly: true
  initContainers:
    - command:
        - sh
        - -c
        - >
          cp -rp /tmp/docker-credential-gcr /usr/local/bin/ && 
          docker-credential-gcr configure-docker 
          --registries=europe-west1-docker.pkg.dev && 
          chmod +r /root/.docker/config.json
      image: mypersonalrepo/docker-credential-gcr:latest
      name: copy-docker-credential-gcr
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: docker-credential-gcr
          mountPath: /usr/local/bin
        - mountPath: /root/.docker
          name: docker-config
```

This is slightly different from the original issue since it is referencing a custom image for the initContainer that from the following Dockerfile instead of dynamically pulling the tarball down at runtime (and having an associated runtime dependency that might fail).

```
# Dockerfile
FROM alpine:latest

RUN wget -O /tmp/docker-credential-gcr.tar.gz https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.22/docker-credential-gcr_linux_amd64-2.1.22.tar.gz
RUN tar -xzf /tmp/docker-credential-gcr.tar.gz -C /tmp
```

NB: I have deliberately used `docker-credential-gcr` rather than `gcloud-cli` since installing `gcloud-cli` generates an image over 2GB in size. We only need the credential helper and so this is a much smaller image and `docker-credential-gcr` is still maintained by Google. 

After that, if you copy the stefanprodan `podinfo` chart into your repo you should be able to run the following `Application` manifest:

```bash
oras cp -r ghcr.io/stefanprodan/charts/podinfo:6.5.4 europe-west1-docker.
pkg.
dev/registry-project/registry/stefanprodan/charts/podinfo:6.5.4
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: podinfo
    helm:
      passCredentials: false
    repoURL: europe-west1-docker.pkg.
    dev/registry-project/registry/stefanprodan/charts
    targetRevision: 6.5.4
```

### Git support to Google Cloud Source Repos using Workload Identity

The approach to enable this is broadly outlined in the following issue: https://github.com/argoproj/argo-cd/issues/15361

This requires creating mounting a projected volume of the workload identity kubernetes service account token into the `argocd-repo-server` pod and then defining a repository secret which references a gcpServiceAccount of type `external_account` using the mounted token as the credential source.

```yaml
# values.yaml
repoServer:
  volumes:
    - name: gcp-ksa
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              path: token
              audience: __CLUSTER_PROJECT_ID__.svc.id.goog
              expirationSeconds: 172800
  volumeMounts:
    - name: gcp-ksa
      mountPath: /var/run/secrets/tokens/gcp-ksa
      readOnly: true
```

Then you need to create an ArgoCD external account secret that references the 
token (replacing the placeholders with your own values).

```
apiVersion: v1
kind: Secret
metadata:
  name: repo-gcloud-source
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://source.developers.google.
  com/p/__REGISTRY_PROJECT_ID__/r/__GIT_REPO_NAME__
  gcpServiceAccountKey: |
    {
      "type": "external_account",
      "audience": "identitynamespace:__CLUSTER_PROJECT_ID__.svc.id.goog:https://container.googleapis.
      com/v1/projects/__CLUSTER_PROJECT_ID__/locations/europe-west1/clusters/__CLUSTER_NAME__",
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/__CLUSTER_GCLOUD_SERVICE_ACCOUNT__:generateAccessToken",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "client_email": "must.be.non.empty@localhost.localdomain",
      "credential_source": {
        "file": "/var/run/secrets/tokens/gcp-ksa/token"
      }
    }

```

Once this is created you can then create an `Application` manifest that uses this source.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-git
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://source.developers.google.com/p/registry-project/r/git-repo-name
    path: components/podinfo
    targetRevision: main
```

### Comparison to Flux Helm OCI Support

The flux support is native as befits a system that is typically the first thing to be bootstrapped onto a cluster. It is also very concise with the OCI support being enabled by the single `provider: gcp` directive in the `HelmRelease` manifest.

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: charts-dev
  namespace: flux-system
spec:
  provider: gcp
  type: oci
  url: oci://europe-docker.pkg.dev/registry-project/registry
```
