### ISSUE TITLE
Multi repo pull request generators

### ISSUE THREAD

**Issue by alifemove** [argoproj/argo-cd#17271]
# Summary

Discussion https://github.com/argoproj/argo-cd/discussions/15803

# Motivation

Its quite easy to have a list generator for multiple different repos main branches, but much more difficult or impossible to use a pull request generator in a similar way. Highly reduces boilerplate when you have to create new files for every repo and every repo the only change is the name of the repo and url...

# Proposal

```yaml
spec:
  generators:
    - pullRequest:
        github:
          repo: repo-a
    - pullRequest:
        github:
          repo: repo-b
  template:
    metadata:
      name: '{{pullReuqest.repo}}-{{branch}}-{{number}}'
```
Just pass along the pullRequest object to the template maybe? Or `generator.pullRequest.repo`? Something along those lines...
