### ISSUE TITLE
An applicationSet cannot be synchronized when certain helm values are enabled: Failed to unmarshal "xxxxx.yaml": <nil>

### ISSUE THREAD

**Issue by papanito** [argoproj/argo-cd#17288]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

An applicationSet cannot be synchronized when certain helm values are enabled

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = FailedPrecondition desc = Failed to unmarshal "kured.yaml": <nil>
```

**To Reproduce**

Setup the following applicationSet

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kured
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: cluster1
        project: p-n6fht
        rebootDays: [mon,tue,wed,thu,fri]
        notifyUrl: teams://<redacted>
      - cluster: cluster2
        project: p-tbck6
        rebootDays: [mon,tue,wed,thu]
        notifyUrl: teams://<redacted>
    metadata:
      name: kured-{{.cluster}}
      namespace: argocd
      labels:
        swisscard.ch/ea-app-id: "424"
    spec:
      destination:
        namespace: kured
        name: "{{.cluster}}"
      project: container-platform-tooling
      source:
        repoURL: https://helm.intra
        targetRevision: 4.4.1
        chart: kured
        helm:
          valuesObject:
            updateStrategy: RollingUpdate 
            image:
              repository: docker.intra/kubereboot/kured
              tag: 1.12.2 # should match the recommended version at https://github.com/weaveworks/kured
            configuration:
              period: 5m # reboot check period (default 1h0m0s)
              startTime: 6am
              endTime: 6pm
              timeZone: Europe/Zurich
              #rebootDays: {{.rebootDays}}
              blockingPodSelector: ["app=artifactory"]
              #notifyUrl: {{.notifyUrl}}
            tolerations:
              - effect: NoSchedule
                operator: Exists
              - key: CriticalAddonsOnly
                operator: Exists
              - effect: NoExecute
                operator: Exists
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            field.cattle.io/projectId: "{{.project}}"
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
 ```

So far, this synchronizes fine, but then if you comment either of these lines

```
#rebootDays: {{.rebootDays}}
#notifyUrl: {{.notifyUrl}}
```

I also tried without

```
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
```

**Expected behavior**

Synchronisation is ok

**Screenshots**

**Version**

```shell
v2.10.1+a79e0ea
```

**Logs**

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = FailedPrecondition desc = Failed to unmarshal "kured.yaml": <nil>
```

**Comment by blakepettersson** [comment]
Is the issue that if any key within `valuesObject` is commented out, an unmarshaling error occurs? (i.e does this issue happen with any other key than the ones you mentioned)?

**Comment by papanito** [comment]
Yes any key which contains a "templating" value (`{{xxxx}}`) and is un-commented, will cause the error. I added for instance `startTime: 6am` as template (`startTime: {{.startTime}}` and deployed it, which resulted in the error.

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by JustScreaMy** [comment]
I’m not sure if this is the same issue, but I ran into something similar using the git generator. The problem seemed to be related to unquoted templated values. I managed to fix it by quoting every value that had a template in it.

For example, changing from:
```yaml
metadata:
  name: example-project-{{ .path.basename }}
spec:
  destination:
    namespace: example-project-{{ .path.basename }}
    name: in-cluster
  source:
    path: {{ .path.path }}
```
to
```yaml
metadata:
  name: 'example-project-{{ .path.basename }}'
spec:
  destination:
    namespace: 'example-project-{{ .path.basename }}'
    name: in-cluster
  source:
    path: '{{ .path.path }}'
```
After quoting the template expressions, the ApplicationSet synced successfully. It looks like valuesObject with unquoted templates can cause similar Failed to unmarshal errors.
