### ISSUE TITLE
StatefulSet's volumeClaimTemplates is displayed as PersistentVolumeClaim which status is OutOfSync

### ISSUE THREAD

**Issue by seroron** [argoproj/argo-cd#1729]
**Describe the bug**

When 'app name' and 'app.kubernetes.io/instance' are the same, StatefulSet's volumeClaimTemplates is displayed as PersistentVolumeClaim which status is OutOfSync.

**To Reproduce**

* yaml

```
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: testapp
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: testapp-api
  name: testapp-api-mongo
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: testapp
      app.kubernetes.io/name: mongo
      app.kubernetes.io/part-of: testapp-api
  serviceName: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: testapp
        app.kubernetes.io/name: mongo
        app.kubernetes.io/part-of: testapp-api
      name: mongo
    spec:
      containers:
      - image: mongo:4.0.5
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27017
          name: service
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data-volume
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/instance: testapp
        app.kubernetes.io/part-of: testapp-api
      name: mongo-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

```

* NG ('app name' and 'app.kubernetes.io/instance' are same)

```
argocd app create testapp \
  --repo <omission> \
  --path "." \
  --dest-server <omission> \
  --dest-namespace sandbox \
  --project sandbox
```

```
# argocd app get testapp
Name:               testapp
Project:            sandbox
Server:             <omission>
Namespace:          sandbox
URL:                <omission>
Repo:               <omission>
Target:
Path:               .
Sync Policy:        <none>
Sync Status:        OutOfSync from  (e04dd96)
Health Status:      Healthy

GROUP  KIND                   NAMESPACE    NAME                                   STATUS     HEALTH
apps   StatefulSet            sandbox      testapp-api-mongo                      Synced     Healthy
       PersistentVolumeClaim  sandbox      mongo-data-volume-testapp-api-mongo-0  OutOfSync  Healthy
```

* OK ('app name' and 'app.kubernetes.io/instance' are not same)

```
argocd app create testapp2 \
  --repo <omission> \
  --path "." \
  --dest-server <omission> \
  --dest-namespace sandbox \
  --project sandbox
```

```
# argocd app get testapp2
Name:               testapp2
Project:            sandbox
Server:             <omission>
Namespace:          sandbox
URL:                <omission>
Repo:               <omission>
Target:
Path:               .
Sync Policy:        <none>
Sync Status:        Synced to  (e04dd96)
Health Status:      Healthy

GROUP  KIND         NAMESPACE    NAME               STATUS  HEALTH
apps   StatefulSet  sandbox      testapp-api-mongo  Synced  Healthy
```

**Expected behavior**

StatefulSet's volumeClaimTemplates is not displayed as resource.

**Version**

v1.0.1
