### ISSUE TITLE
Document how to add Gitlab RBAC policies

### ISSUE THREAD

**Issue by warmfusion** [argoproj/argo-cd#1731]
**Is your feature request related to a problem? Please describe.**

We operate an on-prem gitlab installation and have configured it for authentication but cannot work out how to associate groups in rbac.

**Describe the solution you'd like**
Documentation that highlights 

1. how the rbac policies associate `my-org` with an on-prem installation.
1. how we might view or debug groups for a given user when they've logged in (ie 'my groups')

**Have you thought about contributing yourself?**

Yes, but don't know the answer to this question.

**Comment by alexec** [comment]
does https://argoproj.github.io/argo-cd/operator-manual/rbac/ help?

**Comment by jessesuen** [comment]
See dex's gitlab docs:
https://github.com/dexidp/dex/blob/master/Documentation/connectors/gitlab.md

To debug, you can:
* tail dex's logs
* examine the JWT in your cookie after logging in

**Comment by alexec** [comment]
Please re-open if you have more questions.

**Comment by sunnoy** [comment]
when i use gitlab , how i config user group 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow

    g, your-github-org:your-team, role:org-admin
```

how about group  "your-github-org:your-team" in gitlab

**Comment by alwaysastudent** [comment]
@warmfusion @sunnoy - what did you finally end up with? Can you please share any references/example settings?

**Comment by damian-keska** [comment]
@sunnoy I have the same issue - I cannot get the group name when pairing with gitlab.

**Comment by kirt13** [comment]
@sunnoy @alwaysastudent i got gitlab integration working with the following cofigmap settings: 

argocd-cm:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - <removed>
  dex.config: |
    connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://gitlab.com
        clientID: "<removed>"
        clientSecret: "<removed>"
        groups:
        - <myorg>/<mygroup>
        useLoginAsID: false
```
argocd-rbac-cm
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:dev-app-update, applications, update, dev/*, allow
    p, role:dev-app-update, applications, update, staging/*, allow
    p, role:testers, applications, sync, *, allow
    g, <myorg>/<group-1>, role:admin
    g, <myorg>/<group-2>, role:testers, role:dev-app-update, role:readonly
    g, <myorg>, role:dev-app-update, role:readonly 

```
in argocd-cm, under dex.config, if you remove gitlab groups and login, you can see all the groups you are part of in the dex-server logs.
