### ISSUE TITLE
bug: manually deleting an app from an appset does not trigger a recreate

### ISSUE THREAD

**Issue by DButter** [argoproj/argo-cd#17312]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Manually deleting a resource from an applicationset leads to a 

applications.argoproj.io
        "XXX not
        found

Error, afterwhich the appset will not reconcile the state anymore

**To Reproduce**

create appset:

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - git:
        repoURL: 'ssh://git@git.git'
        revision: test
        directories:
          - path: resources/*
  template:
    metadata:
      name: 'test--{{path.basename}}-test'
    spec:
      project: test
      source:
        repoURL: 'ssh://git@git.git'
        targetRevision: test
        path: '{{path}}'
      destination:
        name: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true

target-app:

any app yml

**Expected behavior**

Recreation of the app

**Version**

```shell
v2.10.1+a79e0ea
```

**Logs**

```
status:
  conditions:
    - lastTransitionTime: '2024-02-26T12:23:21Z'
      message: >-
        applications.argoproj.io
        "test" not
        found
      reason: UpdateApplicationError
      status: 'True'
      type: ErrorOccurred
    - lastTransitionTime: '2024-02-26T09:47:28Z'
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: 'True'
      type: ParametersGenerated
    - lastTransitionTime: '2024-02-26T12:23:21Z'
      message: >-
        applications.argoproj.io
        "test" not
        found
      reason: UpdateApplicationError
      status: 'False'
      type: ResourcesUpToDateype: ResourcesUpToDate
```

**Comment by bruno561** [comment]
In my case, after I rolled out HAProxy from Redis and (re)created the Application manually (kubectl apply -f), I had no more problems. Furthermore, this problem has already happened to me in versions prior to 2.10 and intermittently, that is, it already excludes Applications that were automatically recreated (as expected) and Applications that were not.

**Comment by DButter** [comment]
I'd rather know were the appset keeps its state so i can also delete the application there tbh

**Comment by JorTurFer** [comment]
We are facing too with this issue, and the workaround is restarting the appset-controller. It looks like if the controller stores a cached version that is tried to be validated on each loop. When we restart the controller that cached entry is gone and it works again

**Comment by blakepettersson** [comment]
I've seen this in some environments, but have not been able to repro this locally. Any ideas? Which k8s versions are you all using? Which k8s flavor (EKS, AKS, GKE)?

**Comment by donovanrost** [comment]
I'm just now running into this on EKS

**Comment by liad5h** [comment]
Happened to me with this applicationset spec

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-events
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  SomeLabel: "true"
          - git:
              repoURL: https://<REPO_URL>/argo-events.git
              revision: HEAD
              files:
                - path: "values/kafka/{{.name}}*"
  template:
    metadata:
      name: '{{.name}}-{{trimSuffix ".yaml" .path.filename}}-argo-events'
    spec:
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            team: team_value
        #        automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - FailOnSharedResource=true
          - PrunePropagationPolicy=orphan
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          - ServerSideApply=true
      project: infra
      sources:
        - chart: argo-events
          repoURL: https://argoproj.github.io/argo-helm
          targetRevision: 2.4.8
          helm:
            valuesObject:
              global:
                podAnnotations:
                  argocd.argoproj.io/hook: Sync
                  argocd.argoproj.io/syncwave: "10"
              controller:
                serviceAccount:
                  annotations:
                    argocd.argoproj.io/hook: Sync
                    argocd.argoproj.io/syncwave: "10"
            releaseName: argo-events
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/values.yaml
              - $values/{{.name}}.yaml
        - path: charts/kafka
          repoURL: https://<REPO_URL>/kafka-k8s.git
          targetRevision: HEAD
          helm:
            valuesObject:
              kafka:
                annotations:
                  argocd.argoproj.io/hook: Sync
                  argocd.argoproj.io/syncwave: "5"
            releaseName: kafka-eventbus
            valueFiles:
              - $values/values/kafka/{{.name}}/{{.path.filename}}
        - path: charts/events-infra
          repoURL: https://<REPO_URL>/argo-events.git
          targetRevision: HEAD
          helm:
            valuesObject:
              global:
                annotations:
                  argocd.argoproj.io/hook: Sync
                  argocd.argoproj.io/syncwave: "15"
            ignoreMissingValueFiles: true
            releaseName: events-infra
            valueFiles:
              - $values/values/events-infra/values.yaml
              - $values/values/events-infra/{{.name}}.yaml
        - repoURL: https://<REPO_URL>/argo-events.git
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{.server}}'
        namespace: argo-events

```

AWS EKS 1.29
argocd v2.11.4
