### ISSUE TITLE
Failed to sync external cluster due to permission denied on  some local crd

### ISSUE THREAD

**Issue by alekc** [argoproj/argo-cd#17336]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.
* [ ] 

**Describe the bug**

I have an external cluster (where I have a limited access to one specific namespace) where I would like to deploy some helm charts via ArgoCD. 

The cluster is added via secret like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: xxx-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  clusterResources: false
  config: |
      {
      "bearerToken":"xxx",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "xxx"
      }
    }

  name: xxx
  namespaces: tenant-xx
  server: xxx
type: Opaque

```

When I deploy a simple application (deployment, serviceaccount, etc, all resources for which I do have access), the deployment fails due to `cluster 'coreweave' has not been configured`

The cluster status reports:
```
 failed to sync cluster https://k8s.ord1.coreweave.com: failed to load initial state of resource WorkloadSpread.apps.kruise.io: workloadspreads.apps.kruise.io is forbidden: User "token-xxx" cannot list resource "workloadspreads" in API group "apps.kruise.io" in the namespace "tenant-7efe6c-myta" 
```

My understanding is that ArgoCD tries to list all non cluster crds in the namespace, and chokes as soon as it gets permission denied on some of them. Ideally it would simply ignore those resources for which it doesn't have access to (and return an error in case we actually try to deploy it). Less ideally, there should be a mechanism which would allow to explicitly ignore certain resources / or whitelist specific ones for which we do have access. 

**Expected behavior**
Being able to deploy objects for which Argo CD does have access

**Version**

```shell
argocd: v2.9.6+ba62a0a
  BuildDate: 2024-02-02T19:17:57Z
  GitCommit: ba62a0a86d19f71a65ec2b510a39ea55497e1580
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```
