### ISSUE TITLE
Weird / Not Working notifications behavior

### ISSUE THREAD

**Issue by dusatvoj** [argoproj/argo-cd#17369]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
I have deployed ArgoCD in my cluster via official helm chart https://artifacthub.io/packages/helm/argo/argo-cd @ version 6.3.1 -> ArgoCD version `v2.10.1+a79e0ea`.

In my values,yaml I have this basic config:
```yaml
  notifications:
    enabled: true
    metrics:
      enabled: true
    context:
      cluster: "clustername"
    secret:
      create: true
      items:
        rocketchat-email: "argocd@example.com"
        rocketchat-password: "XXX"
    notifiers:
      service.rocketchat: |
        email: $rocketchat-email
        password: $rocketchat-password
        alias: "ArgoCD"
        icon: ":argocd:"
        serverUrl: "https://im.example.com"
    cm:
      create: true
    subscriptions:
      - recipients:
          - rocketchat:#it-argocd-notifications
        triggers:
          - on-created
          - on-deleted
          - on-health-degraded
          - on-sync-failed
          - on-sync-status-unknown

    templates:
     ... # Truncated
    triggers:
    ... # Trucnated
      defaultTriggers: |
        - on-deployed
        - on-health-degraded
        - on-sync-failed
        - on-sync-status-unknown
        - on-sync-succeeded
``` 
It work's correctly and it triggers what I need to. But when I want to explicit notification settings at ArgoCD ApplicationSet
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'some-project'
spec:
  generators: {{ index .Values.projects "some-project" "app-sets" "some-appset" "generators" | toYaml | nindent 4 }}
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-sync-failed.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-sync-status-unknown.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-health-degraded.rocketchat: '#specific-infra-alerting'
....
```
... it doesn't work. ArgoCD gives me an error:
```
time="2024-03-01T16:43:36Z" level=error msg="Failed to notify recipient { #specific-infra-alerting} defined in resource argocd/some-project-1: notification service '' is not supported using the configuration in namespace argocd" resource=argocd/some-project-1
```

I've found issue https://github.com/argoproj/argo-cd/issues/16195 which tells me that I have to disable default triggers, so I've changed annotations to:
```yaml
        notifications.argoproj.io/subscribe.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-created.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-deleted.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-deployed.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-health-degraded.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-sync-failed.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-sync-status-unknown.rocketchat: '#specific-infra-alerting'
        notifications.argoproj.io/subscribe.on-sync-succeeded.rocketchat: '#specific-infra-alerting'
```
Then I can see error:
```
time="2024-03-01T17:14:22Z" level=error msg="Failed to notify recipient {rocketchat #specific-infra-alerting} defined in resource argocd/some-project-1: Unauthorized using the configuration in namespace argocd" resource=argocd/specific-project-1
```

This error appears again when I move annotations to `AppProject` of this `ApplicationSet`

When I disable default triggers to have jus "unauthorized" config, I can't use tham anymore (probably can override by setting `triggers` for `notifications.subscriptions.[]...` / defining triggers at every application).

As I can read [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/subscriptions/#default-subscriptions), changing `notifications.subscriptions` is used just for defining default subscriptions so I'm not adding any new subscription into `notifications.subscriptions.[]` ???

I'm confused of trying to use notifications the way like:
- Default triggers into generic operations channel
- Specific notifications to specific channels

**To Reproduce**

Described above

**Expected behavior**

- I can define default, global subscription
- I can define specific subscriptions for apps / projects / app-sets 

**Screenshots**

N/A

**Version**

```json
{
    "Version": "v2.10.1+a79e0ea",
    "BuildDate": "2024-02-14T17:37:43Z",
    "GitCommit": "a79e0eaca415461dc36615470cecc25d6d38cefb",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.0+g3fc9f4b",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**
... pasted above
