### ISSUE TITLE
resource with a postsync hook in a multi-sources application gets re-created on every synchronization

### ISSUE THREAD

**Issue by martijnvdp** [argoproj/argo-cd#17387]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Additional resources in a mult-sources argocd application with a postsync hook annotation are getting re-created on every sync
```
annotations:
  argocd.argoproj.io/hook: PostSync
```

**To Reproduce**

create a multi-source application with a helm chart and an additional resource with a postsync hook annotation
```
annotations:
  argocd.argoproj.io/hook: PostSync
```
**test application:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-2048-app
  namespace: argo-cd
spec:
  destination:
    name: in-cluster
    namespace: test-2048-app
  project: myproject
  sources:
  - repoURL: http://daocloud.github.io/dao-2048/
    targetRevision: v1.4.1
    helm:
      releaseName: game-2048
      valuesObject:
        fullnameOverride: game-2048
    chart: dao-2048
  - repoURL: 'https://github.com/MyOrg/repo'
    path: deployments/test-2048-app
    targetRevision: HEAD  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ```
  contents of https://github.com/MyOrg/repo/deployments/test-2048-app
  **additional-resource-cnp.yaml**
  ```yaml
  apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test
  annotations:
    argocd.argoproj.io/hook: PostSync
specs:
  - description: "Egress to kube-api-server"
    endpointSelector:
      matchLabels:
        app.kubernetes.io/name: game-2048
    egress:
      - toEntities:
        - kube-apiserver
        toPorts:
          - ports:
            - port: "443"
              protocol: TCP
  ```
  
  after the app is deployed trigger a sync in argocd and the additonal resource with the hook annotation gets deleted and recreated

**Expected behavior**

Expected the resource not to be recreated on a sync without changes to the manifest

removing the posthook "fixes" it
**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/73637849/c40d2fdf-9302-4566-a1f3-3b7ca76ea7b0)

**Version**

```shell
{
    "Version": "v2.10.1+a79e0ea",
    "BuildDate": "2024-02-14T17:37:43Z",
    "GitCommit": "a79e0eaca415461dc36615470cecc25d6d38cefb",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.0+g3fc9f4b",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
Paste any relevant application logs here.
```
