### ISSUE TITLE
Rename and change of YAML file leads to Sync failure (without kustomize)

### ISSUE THREAD

**Issue by NiroDeveloper** [argoproj/argo-cd#17392]
Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**

Rename and change a YAML file in the same commit leads to a sync failure.
In this example ArgoCD tries to add the new YAML variables without removing the old ones, that leads to two multiple probe handlers. (Remove exec liveness probe and add http probe)
Problem only occures **_WITHOUT_** kustomize.

**To Reproduce**

1. Create an pod without kustomize and let it deploy via argocd
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-test
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
```
2. In the same commit rename the file and change the livenessProbe
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-test
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 5
      periodSeconds: 5
```
3. See ArgoCD OutOfSync Error (Not from this example, but same behavior)
```
one or more objects failed to apply, reason: error when patching "/dev/shm/2076440606": Deployment.apps "pod-name" is invalid: [spec.template.spec.containers[2].livenessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type, spec.template.spec.containers[2].startupProbe.tcpSocket: Forbidden: may not specify more than 1 handler type]. Retrying attempt #4 at 2:27PM.
```
4. Fix this by Sync-Button and enable prune, so it will build a completely fresh instance

**Expected behavior**

ArgoCD should remove the attributes removed from the manifest, so the Sync runs without failure.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/23154768/7fbc13b6-1133-4d42-a2a0-a76b06d958db)

ArgoCD only adds the new attributes and does not remove the old probe.
![image](https://github.com/argoproj/argo-cd/assets/23154768/2464e44f-82cb-47bc-9f71-af14822b6858)

**Version**

```shell
{
    "Version": "v2.10.1+a79e0ea",
    "BuildDate": "2024-02-14T17:37:43Z",
    "GitCommit": "a79e0eaca415461dc36615470cecc25d6d38cefb",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.0+g3fc9f4b",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```
