### ISSUE TITLE
Server-Side Diff Reports out of sync on "status" key (among other noisy diffs)

### ISSUE THREAD

**Issue by sthomson-wyn** [argoproj/argo-cd#17394]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Applications using server-side diff report incorrect diffs. Especially notable with app-of-apps, daemonsets.

**To Reproduce**

Enable server-side diff

**Expected behavior**

Don't report diffs on fields that shouldn't be synced

**Screenshots**

Example: an argoCD Application in an app-of-apps setup changes its status when the application syncs
![image](https://github.com/argoproj/argo-cd/assets/108886656/04e7761a-9047-4d8d-9325-afcdd5af0e02)

Daemonsets reporting out of sync when a new node is being added / a pod isn't ready yet
![image](https://github.com/argoproj/argo-cd/assets/108886656/75994d1c-3620-4962-9ca0-10628620e2df)

Reporting missing labels, even after syncing
![image](https://github.com/argoproj/argo-cd/assets/108886656/237d125d-6d89-4057-af72-4b7258006a62)

**Version**

```shell
argocd: v2.9.3+6eba5be.dirty
  BuildDate: 2023-12-02T00:36:55Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.2+fcf5d8c

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by llavaud** [comment]
also experience these problems with latest version 2.10.2

**Comment by zswanson** [comment]
2.10.4 just installed from 2.9.x, after enabling server side diff and waiting for a bit I had a couple of Apps report OutOfSync status due to a missing `app` label - which they all had on the resources.

**Comment by rouke-broersma** [comment]
I'm having the same issue. I'm deploying emqx (mqtt broker) which for some reason likes to use the status field to keep track of the uptime of the nodes, this causes a sync to be triggered every loop.

```yaml
status:
  conditions:
    - lastTransitionTime: '2024-04-14T12:45:31Z'
      message: Cluster is ready
      reason: Ready
      status: 'True'
      type: Ready
    - lastTransitionTime: '2024-04-14T12:45:30Z'
      message: Cluster is available
      reason: Available
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-04-14T12:45:30Z'
      message: Core nodes is ready
      reason: CoreNodesReady
      status: 'True'
      type: CoreNodesReady
    - lastTransitionTime: '2024-04-14T12:43:38Z'
      message: Core nodes progressing
      reason: CoreNodesProgressing
      status: 'True'
      type: CoreNodesProgressing
  coreNodes:
    - connections: 1
      uptime: 65596542
      version: 5.6.0
    - connections: 1
      uptime: 65719858
      version: 5.6.0
```

**Comment by zswanson** [comment]
2.11 with server-side-diff enabled and we randomly today have HPAs reporting their status fields as out of sync.

![image](https://github.com/user-attachments/assets/0c996ae1-cfb4-4da9-adf2-04da1d5907fc)

**Comment by llavaud** [comment]
personally we now completely ignore `status` fields with the following 2 parameters:
```
resource.customizations.ignoreResourceUpdates.all: |
  jsonPointers:
    - /status
resource.compareoptions: |
  ignoreResourceStatusField: all
```
