### ISSUE TITLE
blockOwnerDeletion and controller missing from job spec when using create-job

### ISSUE THREAD

**Issue by tallmanbrew** [argoproj/argo-cd#17391]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the create-job, either from the UI or the CLI the job.metadata.ownerReferences is missing both:
* blockOwnerDeletion
* controller
Both of these are set to be true in the create-job/action.lua file.
https://github.com/argoproj/argo-cd/blob/release-2.9/resource_customizations/batch/CronJob/actions/create-job/action.lua#L51
https://github.com/argoproj/argo-cd/blob/release-2.9/resource_customizations/batch/CronJob/actions/create-job/action.lua#L52
However the output yaml does not include either of these settings.
```
ownerReferences:
    - apiVersion: batch/v1
      kind: CronJob
      name: <cron-job-name>
      uid: <valid-uuid>
```
With controller missing from the yaml definition the job is not cleaned up or included in the `successfulJobsHistoryLimit` count, leaving jobs created this way remaining in the cluster until manually deleted.

**To Reproduce**

In the UI select a cronJob and select Create Job
In the CLI the following cmd
```
argocd app actions run <APPNAME> create-job --kind CronJob --resource-name <CRONJOBNAME>
```
Inspect the yaml produced.

**Expected behavior**

Both the `job.metadata.ownerReference.blockOwnerDeletion` and `job.metadata.ownerReference.controller` values should be set true as intended, indicated by the code from the create-job/action.lua file.  Is it possible that the boolean `true` in lua file is not properly being translated to a yaml true and then being nulled or ignored when the yaml is created?
Yaml should look like this:
```
ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: CronJob
      name: <cron-job-name>
      uid: <valid-uuid>
```

**Screenshots**

No screen shots, links to code and description define the issue.

**Version**

```
argocd: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```
