### ISSUE TITLE
PostSync hook runs while Deployment pods from previous ReplicaSet still exist

### ISSUE THREAD

**Issue by glasser** [argoproj/argo-cd#17408]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have some ArgoCD apps which contain (among other things) a Deployment, a Service, and a Job that is a PostSync hook. The Job uses `curl` to connect to the Deployment via the Service URL to get some information from it (a GraphQL schema) and send it somewhere.

Our intention is that the Job should *only* talk to the newly-deployed pods, *not* pods from the previous ReplicaSet, so that the information it gets is about the current deploy, not the previous one.

However, we are seeing that in practice the Job occasionally gets responses from the previous ReplicaSet. We can tell because we log the headers received by `curl` and the `Kubernetes-Pod-Name` in the response is from the previous ReplicaSet.

This is surprising. My understanding is that PostSync hooks only run after all the resources in the app are Healthy, and [the health code for Deployments](https://github.com/argoproj/gitops-engine/blob/5fd9f449e75774f6b2b7b1ff137c7759e075e385/pkg/health/health_deployment.go#L47-L51) specifically wait for previous replicas to terminate before becoming Healthy (with code borrowed from `kubectl rollout status`).  And yet this definitely happens.

**To Reproduce**

I will try to put together a more self-contained version of this as a reproduction. Here is a slightly redacted version of the three resources in question.

```
---
apiVersion: v1
kind: Service
metadata:
  name: engine-proposals
  namespace: staging
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: engine-proposals
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-proposals
  namespace: staging
spec:
  replicas: 2
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      name: engine-proposals
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: engine-proposals
    spec:
      containers:
        - image: REPOSITORY:TAG
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: .well-known/healthcheck.json
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          name: engine-proposals
          ports:
            - containerPort: 9998
              name: jmx
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: .well-known/healthcheck.json
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proposals-subgraph-publish-staging
  namespace: argo-subgraph-publish
data:
  publish.sh: >
    #!/bin/bash

    set -e

    if ! curl --fail-with-body --silent --show-error "$SCHEMA_URL" -o
    schema.graphql --dump-header header.txt; then
      cat schema.graphql
      exit 1
    fi


    echo "Downloaded schema from $SCHEMA_URL; headers:"

    cat header.txt

    # more elided
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: proposals-subgraph-publish-staging
  namespace: argo-subgraph-publish
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - command:
            - /bin/bash
            - '-c'
            - scripts/publish.sh
          env:
            - name: SCHEMA_URL
              value: >-
                http://engine-proposals.staging.svc.cluster.local/api/graphql/schema-for-publish
          image: ANOTHERREPO:ANOTHERTAG
          name: rover
          volumeMounts:
            - mountPath: /scripts
              name: scripts-volume
      restartPolicy: Never
      volumes:
        - configMap:
            name: proposals-subgraph-publish-staging
          name: scripts-volume
```

**Expected behavior**

After the PostSync hook runs, the headers displayed in the pod logs should never have a `Kubernetes-Pod-Name` from the previous replicaset.

**Version**

We don't use the `argocd` CLI but our server is running `v2.10.1+a79e0ea`.

**Workaround**

- We can add a long sleep to the beginning of our PostSync hook.
- If we ever detect that the problem happened, clicking Sync on the app will rerun the hook which will properly fetch and publish the correct data.
