### ISSUE TITLE
Argo CD CLI prevents appset from being created when using list generator with empty array

### ISSUE THREAD

**Issue by blakepettersson** [argoproj/argo-cd#17450]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

An Akuity customer reported that they are having difficulties creating an ApplicationSet with the Argo CD CLI. The ApplicationSet consists of a matrix generator that uses both the git (file) generator, and a list generator. When they try to apply the ApplicationSet with the command `argocd appset create <file>` they get the following error:

```
time="2024-02-29T12:16:12+05:30" level=fatal msg="rpc error: code = InvalidArgument desc = error creating ApplicationSet: [ApplicationSet.argoproj.io](http://applicationset.argoproj.io/) \"foobar\" is invalid: spec.generators[0].matrix.generators[1].list.elements: Required value
```

This seems to be a bug that occurs only with the CLI. When applying the ApplicationSet using the app-of-apps pattern, the ApplicationSet deploys and generates the expected Application resources.

**To Reproduce**

Here's an ApplicationSet yaml that I tested with works with app-of-apps, but not using the CLI.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: some-random-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements: []

  syncPolicy: {}
  template:
    metadata:
      name: "some-random-app"
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        path: helm-dependency
        targetRevision: main
      destination:
        name: '{{.name}}'
        namespace: 'some-random-app'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
```

This also applies for a bare list generator (that's not a part of a matrix generator)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: some-random-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements: []
  syncPolicy: {}
  template:
    metadata:
      name: "some-random-app"
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        path: helm-dependency
        targetRevision: main
      destination:
        name: '{{.name}}'
        namespace: 'some-random-app'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
```

If you apply the first one with `argocd appset create <file>` you'll get

```
rpc error: code = InvalidArgument desc = error creating ApplicationSet: ApplicationSet.argoproj.io "some-random-app" is invalid: spec.generators[0].matrix.generators[0].list.elements: Required value 
```

If you apply the second one with `argocd appset create <file>` you'll get

```
rpc error: code = InvalidArgument desc = error creating ApplicationSet: ApplicationSet.argoproj.io "some-random-app" is invalid: spec.generators[0].list.elements: Required value 
```

**Expected behavior**

No errors.

**Version**

```shell
argocd: v2.9.3+6eba5be.dirty
  BuildDate: 2023-12-02T00:46:25Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.9.0+a93f05d.dirty
  BuildDate: 2024-03-08T13:04:27Z
  GitCommit: a93f05d0f0c7583f9a62187b5bf97cc1227adfa4
  GitTreeState: dirty
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.2+gc309b6f
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```
