### ISSUE TITLE
Allow to use helm.valuesObject and kustomize at the same time. Error: Manifest generation error (cached): multiple application sources defined: Kustomize, Helm

### ISSUE THREAD

**Issue by gomin1d** [argoproj/argo-cd#17461]
# Summary

It is now not possible to use helm.valuesObject and kustomize at the same time. If I try to do this, I get an error:
```
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = Manifest generation error (cached): multiple application sources defined: Kustomize,Helm
```

# Motivation

Here is my living example. I install helm chart mailu. I configured it via valuesObject. And also I want to configure tolerations and nodeSelector via kustomize.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://mailu.github.io/helm-charts/
      targetRevision: 1.5.0
      chart: mailu
      kustomize:
        patches:
          - target:
              kind: Deployment
              name: guestbook-ui
            patch: |-
              - op: add
                path: /spec/template/spec
                value: 
                  tolerations:
                   - key: "host"
                     operator: "Equal"
                     value: "critical"
                     effect: "NoSchedule"
                  nodeSelector:
                   'kubernetes.io/hostname': 'dev.mineland.local'
      helm:
        valuesObject:
          oletools:
            enabled: false
          subnet: 10.233.64.0/18
          front:
            hostPort:
              enabled: false
          domain: mail.gomin1d.top
          hostnames:
            - mail.gomin1d.top
          timezone: Europe/Kyiv
          ingress:
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
          webmail:
            enabled: false
          logLevel: INFO
          limits:
            authRatelimit:
              ip: 100/minute;3600/hour
              user: 100/day
            messageSizeLimitInMegabytes: 200
          persistence:
            existingClaim: mailu-pvc
          clamav:
            enabled: false
          redis:
            enabled: false
    - repoURL: git@gitlab.com:gomin1ds/gomin1ds-argocd.git
      path: 'mailu'
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gomin1ds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

# Proposal

Support simultaneous use of helm.valuesObject and kustomize at the same time.

**Comment by MartinLoeper** [comment]
Is there currently a workaround to this?

**Comment by crenshaw-dev** [comment]
I think my preference would be that we add support for kustomization.yaml's `helmCharts` field by adding it to `spec.source.kustomize`. Then users can take advantage of the `spec.source.kustomize.helmCharts[].valuesInline` field.

**Comment by gomin1d** [comment]
> Is there currently a workaround to this?

@MartinLoeper yes, my solution: https://github.com/Mailu/helm-charts/issues/341#issuecomment-2089030963

**Comment by yannick-roeder** [comment]
Could  an implementation for this work, that uses multiple sources similar to the way you can [reference Helm value files across sources via the ref field](https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository). Imagine a configuration like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    valuesObject: 
       prometheus:
         enabled: true
    ref: helm
  - repoURL: https://github.com/my-org/my-repo.git
    path: 'my-app'
    targetRevision: HEAD
    kustomize:
      resources:
        - $helm.output
```

This has the advantage that it does not matter if the Kustomize patches are part of the Application or somewhere separate inside the repository. Additionally Helm could still make use of ArgoCDs build in Helm repository authentication (which is not supported for `helmCharts` in Kustomize as far as I'm aware).
