### ISSUE TITLE
403 when attempting to apply or update an Argo Application through api that contains the text 'http://localhost'

### ISSUE THREAD

**Issue by Justin-DynamicD** [argoproj/argo-cd#17483]
Scenario: client wants to add an environment variable to their helm chart that contains a simple string `http://localhost` (appended characters, such as for port, do not matter).  Argo blocks this update with a 403 (access denied) error:

via argoCD UI:
![image](https://github.com/argoproj/argo-cd/assets/8795183/ce39b74b-f9ca-4abd-ba82-d31f73d66d5d)

via Terraform modules/provider:
![image](https://github.com/argoproj/argo-cd/assets/8795183/7f0d9de4-6776-437f-9ec8-d80eeda64da4)

Similarly, it also appears to block `http://127.0.0.1`, but is ok with a simple `localhost` or `127.0.0.1`; it's the literal combination of http:// and local loop url.

using `kubectl apply -f somefile.yml` and manually updating the Argo Application manifest directly will work, and the environment variable will propagate to all pods in the final deployment.

Sample failing argo app manifest (as seen from the gui):

```Yaml
project: justintest
source:
  repoURL: 'https:/blah'
  path: charts/my-template
  targetRevision: 0.1.0
  helm:
    values: >
      "envVar":
        "SAMPLE": "http://localhost:8080"
      "image": "myimage:0.1.0"
destination:
  namespace: awesome
  name: mycluster
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: true
  retry:
    limit: 3
    backoff:
      duration: 30s
      factor: 2
      maxDuration: 2m
revisionHistoryLimit: 10
```

The Helm chart is being passed via the values block, but it doesn't seem to care with anything except this specific combination of http://localhost

## Version info

argocd: v2.7.17+13d723d
  BuildDate: 2024-02-02T18:47:02Z
  GitCommit: 13d723df9cd59b3a49ee54ab7c38f759dbc56179
  GitTreeState: clean
  GoVersion: go1.20.13
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.7.17+13d723d.dirty
  BuildDate: 2024-02-02T18:38:10Z
  GitCommit: 13d723df9cd59b3a49ee54ab7c38f759dbc56179
  GitTreeState: dirty
  GoVersion: go1.20.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.
