### ISSUE TITLE
Kubernetes v1.29 Can't compare schema for Service (due to new IPMode field)

### ISSUE THREAD

**Issue by sthomson-wyn** [argoproj/argo-cd#17548]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a cluster with 1.29, Services that have IPMode in their status (https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-ip-mode)

Results in 

```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .status.loadBalancer.ingress[0].ipMode: field not declared in schema
```

**To Reproduce**

Install a service onto a Kubernetes cluster that has IPMode enabled 

**Expected behavior**

Able to diff/sync

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/108886656/780d9db5-acfc-4ecb-bc78-e4d1ac2a6263)
![image](https://github.com/argoproj/argo-cd/assets/108886656/8933a93f-65ee-4c80-9634-3a001cabfbd0)

**Version**

```shell
argocd: v2.9.3+6eba5be.dirty
  BuildDate: 2023-12-02T00:36:55Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.2+fcf5d8c

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jgwest** [comment]
FWIW v1.29 is not one of the versions that Argo CD v2.9 is tested against, as perhttps://argo-cd.readthedocs.io/en/stable/operator-manual/tested-kubernetes-versions/

**Comment by jdmcmahan** [comment]
Incidentally, this will be a much more important issue [now that the `ipMode` feature is out of alpha in Kubernetes v1.30](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/#make-kubernetes-aware-of-the-loadbalancer-behaviour-sig-network-https-github-com-kubernetes-community-tree-master-sig-network).

I was able to work around the problem by setting the following in my `ApplicationSet`:
```yaml
  template:
    spec:
      ignoreDifferences:
        - group: ""
          kind: Service
          jqPathExpressions:
            - .status.loadBalancer.ingress[].ipMode
```

Keep in mind this only works if you aren't actually changing anything with `ipMode`.

**Comment by andre161292** [comment]
We're still running into this issue in v2.11.4+e1284e1 using Kubernetes v1.30. I know this version is not in the list of tested versions, but the ipMode field should be supported  nevertheless, am i right? Even with ignoreDifferences, the issue still occurs.

The manifest used is the following:

```yaml
project: default
source:
  repoURL: 'https://kubernetes.github.io/ingress-nginx'
  targetRevision: 4.11.0
  helm:
    releaseName: ingress-nginx
    valuesObject:
      controller:
        allowSnippetAnnotations: true
        ingressClassResource:
          controllerValue: k8s.io/ingress-nginx
          default: true
          enabled: true
          name: nginx
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        name: controller
        service:
          enabled: true
          ipFamilies:
            - IPv4
          ipFamilyPolicy: SingleStack
          type: LoadBalancer
  chart: ingress-nginx
destination:
  server: 'https://kubernetes.default.svc'
  namespace: ingress-nginx
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: true
```
