### ISSUE TITLE
Provide possibility for deep links encode some parameters in base64

### ISSUE THREAD

**Issue by Hronom** [argoproj/argo-cd#17552]
# Summary

Possibility to encode some text in base64 for deep links.

# Motivation

We using `ApplicationSet` and we would like to add deep links for our applications for Kubecost savings feature.
So developers can quickly jump from Argo CD application details page to recommended savings for the application.

# Proposal

## Option 1
Right now Kubecost form link like this:
```
https://kubecost.example.com/request-sizing?filter=W3sia2V5IjoibmFtZXNwYWNlIiwib3BlcmF0b3IiOiI6IiwidmFsdWUiOiJ4eHgifV0=&profile=production&CPUTargetUtilization=0.65&RAMTargetUtilization=0.65
```
As you can see for `filter` parameter we have base64. If we decode it - we see that there json with filters:
```
[
  {
    "key": "namespace",
    "operator": ":",
    "value": "xxx"
  }
]
```
The `Application` generated by `ApplicationSet` contain namespace, so in order to automatically generate such links we need to have possibility to encode some pieces of text by base64.

So we can put something like this:
```
  application.links: |
    - url: https://kubecost.example.com/request-sizing?filter={{ base64start }}[{"key":"namespace","operator":":","value":"{{.app.spec.destination.namespace}}"}]{{ base64end }}&profile=production&CPUTargetUtilization=0.65&RAMTargetUtilization=0.65
      title: Kubecost Right-Sizing Recommendations
```

## Option 2
Create new CRD where each application can put all what will be displayed on Application details page.
So when application synced by helm chart, there will be added in Kubernetes new resource `ApplicationMetadata`
```
apiVersion: v1
kind: ApplicationMetadata
metadata:
  name: example
spec:
  application:
    links:
      - title: http
        {{- $templatedString := tpl .Files.Get "templates/kubecost_filter.tpl" . }}
        url: {{ $templatedString | b64enc | quote }}
```
And Argo CD can pull dynamic metadata from it.
Trick here is this enables to use full power of helm templating.
