### ISSUE TITLE
Apply styling changes depending on Dex connector used to log in

### ISSUE THREAD

**Issue by erhudy** [argoproj/argo-cd#17562]
# Summary

I would like to make it possible to apply styling changes to the Argo CD UI based on the Dex connector the user came in through.

# Motivation

We provide a consolidated Argo CD instance that is used to manage deployments to various environments. For access to applications in more sensitive environments, users must log in through a different Okta instance from the usual one. I would like to be able to apply certain styling changes to the Argo UI (e.g., add a colored frame around the viewport, change colors of UI items, etc.) in order to make it visually distinctive and clear that they are accessing Argo as some sort of privileged user account.

# Proposal

Probably the simplest way to implement it would be to work out a list of permissible styling changes (colored viewport frame, background color, maybe a warning banner) and then link that to regexes against the username format or groups; if the specified regex matched the username or a group, then the specified styling changes would be applied. If multiple possible styling changes would be valid, the order of items in the configuration would determine display priority.

```
privilegedUIIndicators:
  - userRegex: "@prod-okta.company.com"
    styling:
      viewportBorder: "#FF0000"
      messageBanner: "You are logged in as an account with access to production resources."
  - groupRegex: "^SSO_ARGO_Superadmin$"
    styling:
      viewportBorder: "#123456"
      messageBanner: "You are logged in as an account with full administrative privileges to all resources."
```
