### ISSUE TITLE
User tokens are missing from the UI after ArgoCD gets restarted

### ISSUE THREAD

**Issue by knowacki23** [argoproj/argo-cd#17584]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello! :)
We have noticed that after our ArgoCD instance is being restarted all the User Tokens created via ArgoCD UI are missing.
Tokens were created by going to `Settings` -> `Accounts` -> `account_name` -> `Generate New` in `Tokens` section.
When we try to use previously created tokens after ArgoCD restart with an API call we get following error:
`"error": "invalid session: account account_name does not have token with id test", "code": 16, "message": "invalid session: account account_name does not have token with id test"`

We have to generate new tokens every time we restart our ArgoCD instance but weird thing is that the old tokens values still exist somewhere because if we generate new token with the same `Token ID` as the previous one we are able to authenticate using old Token value.

It seems that the token authentication is based on the contents of the UI but the old tokens that are "missing" from the ArgoCD UI are stored somewhere.

**To Reproduce**

1. Generate new token via UI - go to `Settings` -> `Accounts` -> `account_name` -> `Generate New` in `Tokens` section.
2. Use newly generated token
After restart of ArgoCD instance account token should be missing from the UI and using it should result in getting auth error.
3. Add token again with the same `Token ID`
4. Authentication should work with both old Token value and newly generated Token value

**Expected behavior**

We would expect that ArgoCD would be able to load the tokens to the UI after it is being restarted
**Screenshots**

**Version**

```shell
{
    "Version": "v2.10.4+f5d63a5",
    "BuildDate": "2024-03-18T08:09:23Z",
    "GitCommit": "f5d63a5c77d2e804e51ef94bee3db441e0789d00",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jpmaas** [comment]
I am not sure this is related to restarts directly. I am facing the same  with tokens being gone randomly, however I could not reproduce this on 2.10.7 and 2.11.7.

Somehow it looks like the secret `argocd-secret` in which the tokens are stored is regenerated somewhere down the line. I am currently fiddling around and trying to understand where this is coming from.

Out of curiosity, did you try tokens with a custom name or where all tokens the UUID that is generated if no name is set. I am asking since I have a token that exists since ages and that is having a UUID instead of a custom name 🤔

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?

**Comment by minhnpham-cnb** [comment]
I can confirm this is still happening in ArgoCD version: v2.12.0+ec30a48

We ran into this issue with a bot account we created, then generated a token with it. Restarted our ArgoCD instances a few times, and the tokens on this bot account is wiped.

If it helps, we use a combination of SSO and local bot user accounts, with Github as our main SSO "user" authentication.
This bot account is created as a local user.

**Comment by QuadmanSWE** [comment]
ArgoCD stores the tokens in the secret aptly named `argocd-secret`

I thought I had the issue described here until I realized that this secret got recreated when my helm chart for argocd ran an update. (thanks @jpmaas )

My solution was to add the tokens I wanted to my sealed secrets file for my argocd deployment.

Could part of the issue that OP describe have to do with how the apikey / tokens actually work? Not saying this solves your problem but it would remove a potential dead end from consideration.

> but weird thing is that the old tokens values still exist somewhere because if we generate new token with the same Token ID as the previous one we are able to authenticate using old Token value.

@knowacki23  ArgoCD doesn't actually store the token, it stores the token "id". The token that is given out is a payload, [encoded so that it can be expressed easilty as a string](https://en.wikipedia.org/wiki/JSON_Web_Token). Part of the payload contains the id (which explains why if you create a new token with the same ID the old token will still work).

For example this token I generated just now to try it out: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJiYWNrc3RhZ2U6YXBpS2V5IiwibmJmIjoxNzQ2MDA5MDI3LCJpYXQiOjE3NDYwMDkwMjcsImp0aSI6Ik1ZIFVOSVFVRSBUT0tFTiBJRCJ9.hib4vvJeI18-9_j6XwO-tofdHk3sTXfIq_eGcSJcV6s`

This is an encoded value for this payload:

`{
  "iss": "argocd",
  "sub": "backstage:apiKey",
  "nbf": 1746009027,
  "iat": 1746009027,
  "jti": "MY UNIQUE TOKEN ID"
}`

This is what argocd actually stores in the secret in kubernetes: `accounts.backstage.tokens: '{"id":"MY UNIQUE TOKEN ID","iat":1746009027}]'`

Which means that anyone who can provide a token with the matching payload (which again is not stored in argocd) that encodes the jti, will be allowed to become the account "backstage" - but only if that token is actually represented in the secret, which it was happens when you generate a new token with the same Token ID.

Next time, before you regenerate the token. Take a look if it has dissapeared like it did for me.

`kubectl get secret -n argocd argocd-secret -o yaml `

**Comment by chr0n1x** [comment]
EDIT: Im on argocd `v3.1.9+8665140`

@QuadmanSWE thanks for typing this up, it helped me figure out wth was happening.

In my particular case, I use vault-secrets-operator (VSO). With it, I seed my `argocd-secret` with OIDC secrets stored in vault.

So everytime I generated a new token for a utility/api account generated via the helm `cm.accounts...` value, the token would disappear after the VSO sync/poll. At first I was looking at the UI and seeing the token vanish, having no idea that the token was actually stored/patched in `argocd-secret`.

My SOP to get around this:
1. generate the token in the web UI (don't have access to the CLI for now)
2. leave the web page open so the token stays copy-paste-able for later
3. `kubectl -n argocd get secret argocd-secret -o=yaml | yq r - 'data['accounts.k8s_automation_user.tokens']' | base64 -d`
4. take the value that shows up above, store it into my vault path for `argocd-secret` - key is `accounts.k8s_automation_user.tokens`
5. validate that VSO syncs everything over time and that the key does not disappear
6. use the token from step 1, store it, whatever

example of what my VSO secret looks like:

```yaml
{{- with .Values.argocdSecret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-secret-vso-ref
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .mountType | default "kv-v2" }}
  mount: {{ .mount }}
  # this path must at the minimum have the following keys in order for this
  # chart to w/ .Values.secret.createSecret = false to work:
  #   admin.password
  #   admin.passwordMtime
  #   server.secretkey
  #   accounts.k8s_automation_user.tokens <--- also goes here
  # if these do not exist, set configs.secret.createSecret to true first while
  # you're configuring vault
  path: {{ .path }}
  destination:
    name: argocd-secret
    create: true
    overwrite: true
  refreshAfter: 30s
  vaultAuthRef: {{ $.Release.Namespace -}}/argocd-vso-connection-auth # separate resource/manifest, omitting here
{{- end }}
```

my particular approach might be dumb, I guess.

although I would've expected argocd to generate/source account secrets via something like repositories via a label

```yaml
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-creds-{{ .name -}}-vso-ref
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .mountType | default "kv-v2" }}
  mount: {{ .mount }}
  path: {{ .path }}
  destination:
    name: {{ .name }}
    create: true
    overwrite: true
    labels:
      argocd.argoproj.io/secret-type: repository # THIS - maybe something like "local-user"?
  refreshAfter: 30s
  vaultAuthRef: {{ $.Release.Namespace -}}/argocd-vso-connection-auth
```
