### ISSUE TITLE
Helm-hooks/Wrong behavior of argocd to deploy helm chart with hooks

### ISSUE THREAD

**Issue by galsasi1989** [argoproj/argo-cd#17604]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to deploy helm chart which contains a job with helm hook annotation: "helm.sh/hook: post-install,post-upgrade" 
When helm is used, the job is deployed successfully with the rest of chart's resources.
But when the chart is deployed by argocd, the job is ignored. 
According to argocd documentation(https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks) is seems like this helm annotation is translated into argocd hook annotation: "argocd.argoproj.io/hook: PostSync". 
According to the documentation about argocd PostSync hook(https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/) it seems like a different behavior: "Using a PostSync hook to run integration and health checks after a deployment.". So the behavior when the chart is deployed by argocd is different from the behavior when it's deployed by helm. The only solution I found is the use argo hook annotations instead those of helm but it's less preferred. 

**To Reproduce**

**Expected behavior**

The job hook will be triggered by argo with the application workloads as done by helm when using the post-install,post-upgrade annotation. 

**Screenshots**

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: app-db-migration
  name: app-db-migration
  namespace: staging
spec:
  template:
    metadata:
      labels:
        app: app-db-migration
        cdk8s.io/metadata.addr: appChart-dbMigrationJob-job-c88dfdff
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - app
      automountServiceAccountToken: true
      containers:
        - command:
            - python
            - manage.py
            - migrate
          env:
           // list of env vars
          image: <docker image path>
          imagePullPolicy: Always
          name: app
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "2"
              memory: 2048Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /mnt/secrets-store
              name: app-secret
              readOnly: true
          workingDir: /app
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Never
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      serviceAccountName: app-sa
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: app-secret-spc
          name: app-secret
  ttlSecondsAfterFinished: 7200
```

**Version**

```shell
argocd: v2.8.4+c279299.dirty
  BuildDate: 2023-09-13T22:00:14Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: dirty
  GoVersion: go1.21.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.9.5+f943664
  BuildDate: 2024-01-19T17:57:57Z
  GitCommit: f9436641a616d277ab1f98694e5ce4c986d4ea05
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.17
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by cardoe** [comment]
Agreed here. The `post-install,post-upgrade` Helm hook should really map to the `Sync` ArgoCD hook. In Helm the `post-install,post-upgrade` happens after all the resources have been applied but not before they're up and healthy. This maps to the ArgoCD `Sync` hook instead of the ArgoCD `PostSync` hook which happens after the resources are applied and healthy.

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?

**Comment by pawgajda-drs** [comment]
@andrii-korotkov-verkada I am facing similar issue with the newest release of ArgoCD. I am trying to install Airflow from Bitnami's Helm Chart and the Batch Job is not being executed:

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: airflow
    app.kubernetes.io/version: 2.10.4
    helm.sh/chart: airflow-22.4.7
  name: airflow-setup-db
  namespace: airflow
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: airflow
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: airflow
        app.kubernetes.io/version: 2.10.4
        helm.sh/chart: airflow-22.4.7
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - -ec
        - |
          . /opt/bitnami/scripts/airflow-env.sh
          . /opt/bitnami/scripts/libairflow.sh

          info "Trying to connect to the database server"
          airflow_wait_for_db_connection

          if ! airflow_execute db check-migrations; then
              info "Populating database"
              airflow_execute db init

              airflow_create_admin_user
          else
              info "Upgrading database schema"
              airflow_execute db upgrade
              true
          fi
        command:
        - /bin/bash
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: AIRFLOW_USERNAME
          value: metoptima-airflow
        - name: AIRFLOW_PASSWORD
          valueFrom:
            secretKeyRef:
              key: airflow-password
              name: airflow-secret
        image: docker.io/bitnami/airflow:2.10.4-debian-12-r4
        imagePullPolicy: IfNotPresent
        name: setup-db
        resources:
          limits:
            cpu: 375m
            ephemeral-storage: 2Gi
            memory: 384Mi
          requests:
            cpu: 250m
            ephemeral-storage: 50Mi
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
          subPath: tmp-dir
        - mountPath: /opt/bitnami/airflow/logs
          name: empty-dir
          subPath: app-logs-dir
        - mountPath: /opt/bitnami/airflow/airflow.db
          name: empty-dir
          subPath: app-base-dir/airflow.db
        - mountPath: /opt/bitnami/airflow/airflow.cfg
          name: empty-dir
          subPath: app-base-dir/airflow.cfg
        - mountPath: /opt/bitnami/airflow/config/airflow_local_settings.py
          name: empty-dir
          subPath: app-conf-dir/airflow_local_settings.py
      initContainers:
      - args:
        - -ec
        - |
          . /opt/bitnami/scripts/libairflow.sh

          mkdir -p /emptydir/app-base-dir /emptydir/app-conf-dir

          # Copy the configuration files to the writable directory
          cp /opt/bitnami/airflow/airflow.cfg /emptydir/app-base-dir/airflow.cfg

          # Apply changes affecting credentials
          export AIRFLOW_CONF_FILE="/emptydir/app-base-dir/airflow.cfg"
          db_user="$(airflow_encode_url "$AIRFLOW_DATABASE_USERNAME")"
          db_password="$(airflow_encode_url "$AIRFLOW_DATABASE_PASSWORD")"
          airflow_conf_set "database" "sql_alchemy_conn" "postgresql+psycopg2://${db_user}:${db_password}@${AIRFLOW_DATABASE_HOST}:${AIRFLOW_DATABASE_PORT_NUMBER}/${AIRFLOW_DATABASE_NAME}"
          info "Airflow configuration ready"

          if [[ -f "/opt/bitnami/airflow/config/airflow_local_settings.py" ]]; then
              cp /opt/bitnami/airflow/config/airflow_local_settings.py /emptydir/app-conf-dir/airflow_local_settings.py
          else
              touch /emptydir/app-conf-dir/airflow_local_settings.py
          fi

          # HACK: When testing the db connection it creates an empty airflow.db file at the
          # application root
          touch /emptydir/app-base-dir/airflow.db
        command:
        - /bin/bash
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: AIRFLOW_DATABASE_NAME
          value: bitnami_airflow
        - name: AIRFLOW_DATABASE_USERNAME
          value: bn_airflow
        - name: AIRFLOW_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: airflow-postgresql
        - name: AIRFLOW_DATABASE_HOST
          value: airflow-postgresql
        - name: AIRFLOW_DATABASE_PORT_NUMBER
          value: "5432"
        image: docker.io/bitnami/airflow:2.10.4-debian-12-r4
        imagePullPolicy: IfNotPresent
        name: prepare-config
        resources:
          limits:
            cpu: 150m
            ephemeral-storage: 2Gi
            memory: 192Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /emptydir
          name: empty-dir
        - mountPath: /opt/bitnami/airflow/airflow.cfg
          name: configuration
          subPath: airflow.cfg
        - mountPath: /opt/bitnami/airflow/config/airflow_local_settings.py
          name: configuration
          subPath: airflow_local_settings.py
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      serviceAccountName: airflow
      volumes:
      - emptyDir: {}
        name: empty-dir
      - configMap:
          name: airflow
          optional: true
        name: configuration
```

**Comment by galsasi1989** [comment]
@pawgajda-drs 
You can use Argo Sync phases and waves annotations. 
For example: 
argocd.argoproj.io/hook: PreSync

You can find more details in Argo [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/)

**Comment by pawgajda-drs** [comment]
> [@pawgajda-drs](https://github.com/pawgajda-drs) You can use Argo Sync phases and waves annotations. For example: argocd.argoproj.io/hook: PreSync
> 
> You can find more details in Argo [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/)

Thanks. As a workaround I did this in my kustomization of Airflow's Helm Chart:

```patches:
  - path: job-patch.yaml
    target:
      kind: Job
      name: airflow-setup-db
```
and the patch:
```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
  name: airflow-setup-db
```
It is not a way that I prefer to do things but for now it works and that's what matters. I'd be nice if Helm Chart hooks were executed properly without modifications, I use this Chart to not to patch every single thing myself after all...

**Comment by raweber42** [comment]
This issue still persists on Argo 2.13.3. I am trying to deploy the [wundergraph](https://github.com/wundergraph/cosmo/tree/main/helm/cosmo) chart. When applying via helm everything works fine. When trying via Argo, I cannot see the jobs and they are appearantly getting ignored.

I am happy to contribute in order to resolve this.

**Comment by v-cimburek** [comment]
I want to report that I am having the same issue as well. I am deploying our inhouse application which has a job with annotations post-install and post-upgrade. The job is ignored. If I run the job without the annotations, it will run.

**Comment by Alex2357** [comment]
I'm also having a problem I can not deploy chart while using helm CLI works fine.
Would be nice if there was ability to request chart to be deployed using helm cli like Flux CD does. That would solve many problems. The ArgoCD mountainers would not need to bother with full feature parity with Helm CLI. To be honest I really would not want to use a GitOps tool which makes an attempt to reimplement Helm CLI functionality. It is kinda extra efforts for nothing with low success rate as there will be constantly something not working like it works in Helm CLI. 
I also do not have time to reimplement the chart and replace helm hooks with argo hooks. Moreover with new versions repeating the same operation is not the best option.

When I run, all got deployed successfully. But when I deploy corresponding ArgoCD applications deploying same charts with same values it fails.

```bash
helm upgrade --install -n spire-mgmt spire-crds spire-crds --repo https://spiffe.github.io/helm-charts-hardened/ --create-namespace
helm upgrade --install -n spire-mgmt spire spire --repo https://spiffe.github.io/helm-charts-hardened/ -f values/spire.yaml
```

spire.yaml
```yaml
        global:
          spire:
            recommendations:
              enabled: true
            namespaces:
              create: true
            ingressControllerType: "" # If not openshift, and want to expose services, set to a supported option [ingress-nginx]
            # Update these
            clusterName: minikube
            trustDomain: example2.org
            caSubject:
              country: AU
              organization: Mx
              commonName: example2.org
```

Please make possibility to deploy using Helm CLI. This is really needed. We can't use both ArgoCD and FluxCD to solve this problem. We have to chose one GitOps tooling.
