### ISSUE TITLE
Support helm repo alias in repoUrl

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argo-cd#17621]
# Summary

Helm repo alias is supported in chart dependency, but we can't reuse it when using a chart as source in an Application.

# Motivation

It would be useful to reuse the alias and not have to reuse the URL if already added in the repo list.

# Proposal

Support the same patterns in repoURL (when Helm is the source type) as in the helm dependencies:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: "@sealed-secrets" or "alias:sealed-secrets"
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
```

Do you think it would make sense ?

If so I can propose a PR.
