### ISSUE TITLE
ArgoCD tries to guess SSH password even though passwordless ssh private key is added for github template

### ISSUE THREAD

**Issue by jbiskur** [argoproj/argo-cd#17625]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

I have added a ssh private key as a github repository template, I get access to the repositories just fine, but my network firewall keeps getting repeated attempts at "guessing" the ssh password. I don't see any failure in the logs and the configuration is a standard helm install, no special configuration. 

**To Reproduce**

1. Create a k3s cluster on an Ubuntu 22.04 server
2. Install helm chart: https://artifacthub.io/packages/helm/argo/argo-cd with out of the box configuration
3. create repository secret with ssh key
```
apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  sshPrivateKey: >-
    SSH PRIVATE KEY
  url: GITHUB ORG SLUG
type: Opaque
```
4. add repository, watch as it works
5. screenshot is a snippet from the firewall logs

**Expected behavior**

It should not try to connect with password when an SSH key is present, especially when no password is supplied at all.

**Screenshots**

![CleanShot 2024-03-26 at 10 42 43@2x](https://github.com/argoproj/argo-cd/assets/7002421/0ceedc87-7002-4bc0-b5cc-772866cc3cc2)

**Version**

```shell
argocd: v2.10.4+f5d63a5
  BuildDate: 2024-03-18T08:09:23Z
  GitCommit: f5d63a5c77d2e804e51ef94bee3db441e0789d00
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Nothing in the logs indicates this behaviour
