### ISSUE TITLE
ArgoCD does not honouring  sync-wave in argo applications

### ISSUE THREAD

**Issue by Emmerson-Miranda** [argoproj/argo-cd#17639]
Hi all,

I am deploying applications using applicationSet, the application set install applications using source helm.

I have a use case were one helm chart depends on another helm chart finish its installation, **to simplify** lets assume for instance I have a helm chart installing RabbitMQ and another installing some microservice that depends on RMQ, both of them are installed by the same applicationSet.

So rabbit-mq application have a wave "-1"
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-mq
  namespace: argocd
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
```

my-microservice application have a wave "1"
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-microservice
  namespace: argocd
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
```

The expectation is ArgoCD will deploy first rabbit-mq and when is ready start to deploy my-microservice. The truth is both are deployed at same time ignoring the wave configuration.

Am I doing something wrong ? is this feature supported by Argo at Application level ?

Kind regards,
Emmerson
