### ISSUE TITLE
One unhealthy application belonging to an applicationset can prevent argocd from syncing the other healthy ones

### ISSUE THREAD

**Issue by lyesbit** [argoproj/argo-cd#17646]
Checklist:

* [ /] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ /] I've included steps to reproduce the bug.
* [ /] I've pasted the output of `argocd version`.

**Describe the bug**

We're experiencing some annoying bug/feature of argocd. It can be broken down like this:

We have an **applicationset**, lets call it **customer-network-policies** (definition below in the screenshot part)

So basicaly argocd makes use of the generator to loop through a directory called dev-cluster/network-policies and generate one Network Policy per file.

Let's imagine for instance that the so called folder dev-cluster/networkpolicies/ contains 3 network policies files, and, for the sake of the example, let's also imagine that each netpol is created within its own namespace. When everything works fine the Argo CD UI renders something like this:

```
customer-network-policies(ApplicationSet) ----> customer-network-policies(Application)

                                          ----> network-policy-1 (NetworkPolicy)
                                          |
customer-network-policies(Application) ---|----> network-policy-2 (NetworkPolicy)
                                          |
					  ----> network-policy-3 (NetworkPolicy)

```
So far so good.

Problem occurs here:

**To Reproduce**

* Delete network-policy-1 from dev-cluster/networkpolicies
* Delete namespace of network-policy-1 (let's say NS1)
* Commit again the exact same file network-policy-1 (which is supposed to be created in NS1)
* Update the file of network-policy-2 (or network-policiy-3, doesn't matter)
--> now argocd will be unable to synchronize ANY of the network policies.

It very much looks like that one unhealthy network policy which cannot be created for whatever reason (in this case because the namespace does not exist) causes argocd to go bunkers and it cannot even sync/refresh the other network policies belonging to the same application/application set which are absolutely fine.

We've tested this at length and this behaviour is very much reproducible, but it feels wrong.

**Expected behavior**

One "unhealthy" resource failing to be created/updated/synced  should not have any consequences on the other "healthy" resources. ArgoCD should be able to move forward with the healthy one and only display an error message for the unhealthy one.

**Screenshots**

Definition of the ApplicationSet

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-network-policies
spec:
  generators:
    - git:
        directories:
          - path: dev-cluster/networkpolicies
        repoURL: >-
          ssh://git@<bitbucket>/customer-instances.git
        revision: master
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: customer-network-polices
    spec:
      destination:
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: dev-cluster/networkpolicies
        repoURL: >-
          ssh://git@<bitbucket>/customer-instances.git
        targetRevision: master
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: `true`
```

**Version**
2.8.4

```shell
Paste the output from `argocd version` here.
```
