### ISSUE TITLE
ArgoCD does not respect ApplyOutOfSyncOnly for admission webhooks

### ISSUE THREAD

**Issue by ilevinupgrade** [argoproj/argo-cd#17643]
I have a `MutatingWebhookConfiguration` resource with a default value added in the live manifest. This default value does not exist in the configuration (desired manifest), and even though ArgoCD does not show out of sync, when syncing with ApplyOutOfSyncOnly set to true, it will reapply the change, i.e. sync state will show "Configured".
ApplyOutOfSyncOnly does work as expected on other type of resources.

To reproduce consider the following manifest : 

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate.example.com
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: example
      path: /
  name: mutate.example.com
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - UPDATE
    resources:
    - '*'
```

After sync a default field is added in the live manifest (`scope`): 

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate.example.com
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: example
      path: /
  name: mutate.example.com
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - UPDATE
    resources:
    - '*'
    scope: '*'
```
Syncing this resource (again) with `ApplyOutOfSyncOnly=true` will result in a "Configured" sync state with the change applied (desired manifest does not have the scope field)

Expected behaviour
With ApplyOutOfSyncOnly set, and given that the resource is not out of sync, a sync should skip this resource.

System
1. ArgoCD `v2.10.3`
2. Kube `1.28`
