### ISSUE TITLE
Application auto-discovery

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1766]
**Is your feature request related to a problem? Please describe.**

A number of users would like something a bit more that app-of-apps. This would probably be served by auto-discovery of apps within a repo.

**Describe the solution you'd like**

Point Argo CD at a repo and let it fly.

**Comment by alexmt** [comment]
Related issue: https://github.com/argoproj/argo-cd/issues/1431

```
argoproj.io/AppsSource - implements application auto-discovery. Instead of forcing user to create an application for each directory the argoproj.io/AppsSource should scan repo and create (delete obsolete apps) automatically.
```

**Comment by wmedlar** [comment]
How would an AppsSource determine the corresponding AppProject for autodiscovered apps? A user might want to be able to specify that certain directories belong to a permissive project that allows certain cluster-scoped resources, while other directories belong to a far more restrictive project.

**Comment by joshuasimon-taulia** [comment]
Here is my current workaround for auto-generating apps-in-app from a kubernetes manifest monorepo. `./components` is symlinked to `openshift/templates/components`. The general idea here is that the helm template for the parent app loops through `components/*` and creates an argo app for each folder on the fly. 
```
{{ range $path, $bytes := .Files.Glob "components/*/configuration.json" }}
  {{- $app := base (dir $path) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $.Values.namespace }}
    server: {{ $.Values.server | default "https://kubernetes.default.svc" }}
  project: {{ $.Values.project | default "default" }}
  source:
    path: openshift/templates/components/{{ $app }}/argotest
    repoURL: git@github.com:ops-stuff/kube-templates
    targetRevision: argocd
  syncPolicy:
{{ end }}
```
I would imagine some folks keep their argo app yaml/k8s manifests in the same repo as their application code. Auto discovery of a configurable filename pattern under a certain Github org would probably work well (like the Jenkins github organization folder plugin).
