### ISSUE TITLE
Helm hooks aren't respected in multi helm chart ArgoCD Applications

### ISSUE THREAD

**Issue by Guent4** [argoproj/argo-cd#17677]
I am trying to deploy out the [`rancher-monitoring-crds`](https://github.com/rancher/charts/tree/release-v2.8/charts/rancher-monitoring-crd/103.0.4%2Bup45.31.1) and [`rancher-monitoring`](https://github.com/rancher/charts/tree/release-v2.8/charts/rancher-monitoring/103.0.4%2Bup45.31.1) Helm charts in one ArgoCD application.  The former relies on Helm PostSync hook to create CRDs from a ConfigMap.  The CRDs are needed for the other Helm chart to sync.  However, unfortunately, the Helm PostSync hook never runs so the CRDs never get created.

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

See above description

**To Reproduce**

Here's a simplified version of the ArgoCD Application I'm applying:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cattle-monitoring-system
  namespace: argocd
spec:
  destination:
    server: ***********
    namespace: cattle-monitoring-system
  sources:
  - chart: rancher-monitoring-crd
    repoURL: https://charts.rancher.io
    targetRevision: 103.0.4+up45.31.1
    helm:
      releaseName: rancher-monitoring-crd
  - chart: rancher-monitoring
    repoURL: https://charts.rancher.io
    targetRevision: 103.0.4+up45.31.1
    helm:
      releaseName: rancher-monitoring
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          prometheusSpec:
            externalLabels:
              cluster: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true # This is needed because the annotations on rancher-monitoring-crd-manifest ConfigMap is too long
```
The syncing will fail saying that certain resources can't be applied because there's no CRD for it.

**Expected behavior**

`rancher-monitoring-crds` will be synced, including running the PostSync Helm hook and then the `rancher-monitoring` will be synced.  There's also no event under the "Sync Status" tab indicating that PostSync hooks were even attempted (note that if the Application only had the `rancher-monitoring-crds` Helm chart, then there's an event for PostSync.

**Screenshots**

N/A

**Version**

CLI version doesn't matter in this case.  Here's is the server version:
```
Argo CD       v2.9.3+6eba5be
Build Date    2023-12-01T23:05:50Z
Go Version    go1.21.3
Go Compiler   gc
Platform      linux/amd64
jsonnet       v0.20.0
kustomize     v5.2.1 2023-10-19T20:13:51Z
Helm          v3.13.2+g2a2fb3b
kubectl       v0.24.2
```

**Logs**

No relevant logs, but happy to grab logs if someone can point me to what logs could be helpful to debug this issue.
