### ISSUE TITLE
ignoreDifferences and RespectIgnoreDifferences=true does allow ignoring differences in selected array elements

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#17694]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Once https://github.com/argoproj/argo-cd/pull/17693 is merged Argo CD will be able to "ignore" arrays. However it is still not possible to ignore individual array elements. In order to fix it Argo CD would need to use strategic merge patch (using built-in k8s schema and dynamic CRD schema)

**To Reproduce**

Unit tests from https://github.com/argoproj/argo-cd/pull/14602 are reproducing behavior.

**Expected behavior**

It should be possible to ignore different individual array elements.

**Version**

```shell
v2.10.4
```

**Comment by alexmt** [comment]
Related to https://github.com/argoproj/argo-cd/issues/9678

**Comment by alexmt** [comment]
If someone attempts to fix it before me. We need to use strategic merge patch here: https://github.com/argoproj/argo-cd/pull/17693/files#diff-627c32a4f31d0f97e6ddc1f19ab3add7fb7791e0d1b0503d78c6c049e8cb4865R438

**Comment by saumeya** [comment]
This is issue is partially fixed by PR - https://github.com/argoproj/argo-cd/pull/17693#issuecomment-2035676032 , fix is only needed for custom resources now.

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?

**Comment by SleepyDeb** [comment]
> ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?

Hello @andrii-korotkov-verkada I can confirm that as today on version v2.13.0+347f221 we still have the same issue.

LMK if you need guidance on how to replicate the issue...

**Comment by ashexpertVersion2** [comment]
Hello we have this issue with ArgoCD v2.11.7+e4a0246.

**Comment by nitishfy** [comment]
I'd like to take this up!

**Comment by BeyondEvil** [comment]
Anything I can do to help here @nitishfy ? I don't think you need to ask permission. Ping @alexmt 

jqPathExpression not working is a major pain, especially for the very prevalent `/webhooks/0/clientConfig/caBundle` use-case.

**Comment by crenshaw-dev** [comment]
Fix was reverted in https://github.com/argoproj/argo-cd/pull/25294, so need to reopen this.

**Comment by webertrlz** [comment]
~+1 this facing this issue, cannot Sync with Ignore Differences enabled.~
Worked for me after upgrading to 3.2.1.

**Comment by rivolity** [comment]
Hello, @crenshaw-dev 

I have tested with `3.2.2` but the behavior is still not as expected.

Scenario:
I want to create an application and ignore all env variables on my Rollout resources because they are patched in another way (via a workflow). I want Argo CD to ignore these environment variables while still keeping the rest of the template (like image, resources, etc.) in sync.

Configuration I used:

```
ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jqPathExpressions:
      # Ignore the entire env array of all app containers
      - .spec.template.spec.containers[].env
      # Ignore the entire env array of all init containers
      - .spec.template.spec.initContainers[].env
```

When I update the container image via GitOps (Helm value), Argo CD shows the Rollout as out-of-sync and does not trigger the update, even though only the image changed. The ignored env variables are correctly skipped, but the image change is not applied.

It seems RespectIgnoreDifferences=true causes Argo CD to pre-patch the desired state, preventing the image change from being applied.

here is screen capture on argoCD

<img width="344" height="91" alt="Image" src="https://github.com/user-attachments/assets/1710753b-e709-48cc-9857-b74e6a30aab4" />

<img width="670" height="196" alt="Image" src="https://github.com/user-attachments/assets/da9f5562-3ceb-4215-8b82-1564883070c4" />

**Comment by blakepettersson** [comment]
Since this was reverted with 3.2.1 I wouldn't expect this to work.

I think #25294 can be unreverted once we upgrade to client-go/apimachinery 0.35 (see kubernetes/kubernetes@5af28702540ddf0a4c16a1c2d9586748ad1b6892).

**Comment by Hunter-Thompson** [comment]
Same issue here in v3.3.2 any updates?

**Comment by makoh1ra33** [comment]
Hi, cloud you please check bellow?

---
Still reproducible on Argo CD **v3.4.2** (helm chart `argo-cd-9.5.14`), confirming this bug persists after the revert of #24197.

This adds a slightly different reproduction shape than the existing reports: `ignoreDifferences` is targeted at **a single field inside a specific element of a multi-source array, selected by `jq` filter**.

### Intent

In this multi-source setup the two `targetRevision`s are intentionally driven by different controllers:

- `sources[1].targetRevision` (values.git) — **managed out-of-band** (e.g. by a separate pipeline) and therefore **should be ignored by Argo CD**. This is what the `jq` expression in `ignoreDifferences` targets.
- `sources[0].targetRevision` (chart.git) — **GitOps-controlled**. Changes here are the user's intent and **must NOT be ignored**; Argo CD should reconcile them as normal.

The bug is that changing `sources[0].targetRevision` — a field **outside** the `jq` expression — is silently reverted to the live value during apply, leaving the root Application stuck OutOfSync.

### Reproduction

Root Application managing a multi-source child Application:

```yaml
# helm-root
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-root
  namespace: argocd
spec:
  source:
    repoURL: <repo holding helm-child manifest>
    targetRevision: v1
    path: .
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jqPathExpressions:
        - .spec.sources[] | select(.repoURL == "https://github.com/<...>/python-app-helm-values.git").targetRevision
```

```yaml
# helm-child (multi-source)
spec:
  sources:
    - repoURL: https://github.com/<...>/python-app-helm-chart.git
      targetRevision: chart_v1     # <-- changed to chart_v2 in git
      path: .
      helm:
        releaseName: python-app
        valueFiles:
          - $values-path/values.yaml
    - repoURL: https://github.com/<...>/python-app-helm-values.git
      targetRevision: values_v1    # <-- this one is the ignored field
      ref: values-path
```

Change `sources[0].targetRevision` in git (`chart_v1` → `chart_v2`), not the ignored path (`sources[1].targetRevision`).

### Observed

- `helm-root` becomes `OutOfSync` and stays there.
- Diff panel correctly shows `chart_v1` → `chart_v2`.
- Auto sync runs ("Sync OK" timestamp updates) but the live `helm-child.spec.sources[0].targetRevision` keeps showing `chart_v1`.
  - The managed `helm-child` Application even reports `Synced` (because its own live spec still says `chart_v1`, which matches what's deployed), while `helm-root` loops on the same diff forever.
- Removing `RespectIgnoreDifferences=true` from `helm-root.syncPolicy.syncOptions` reconciles cleanly on the very next sync.

### Why this is the same bug (for cross-reference)

In `controller/sync.go normalizeTargetResources()`, when the target is a CRD (`Application`), `scheme.Scheme.New()` fails so `lookupPatchMeta` stays `nil`. That sends both `getMergePatch` and `applyMergePatch` down the RFC 7396 JSON Merge Patch path (`jsonpatch.CreateMergePatch` / `jsonpatch.MergePatch`). RFC 7396 replaces arrays wholesale, so the `livePatch` derived from `live - normalized.Lives` carries the entire live `spec.sources` array (with the ignored field re-injected), and overwrites the desired `sources[0].targetRevision` back to the live value during the apply.

This is exactly the regime PR #24197 tried to fix by routing CRDs through `strategicpatch.NewPatchMetaFromOpenAPI`, and which PR #25294 reverted because of #25199. Posting in case it helps when unreverting after the `apimachinery 0.35` bump that @blakepettersson mentioned.

### Version

```
argocd-server: v3.4.2 (helm chart argo-cd-9.5.14)
```
