### ISSUE TITLE
Make it possible for ArgoCD to generate a physical `helm-values.yaml` file that could be referenced when using `kustomize build --enable-helm`

### ISSUE THREAD

**Issue by spkane** [argoproj/argo-cd#17739]
# Summary

While using `kustomize build --enable-helm` with ArgoCD can be very helpful, you lose a straightforward way to pass dynamic values into the Helm chart.

If it was possible to get ArgoCD to take any `helm` parameters that were defined in the application and  create a temporary file with a well-known filename and location (_maybe `argo-generated-value.yaml` right in the repo path_), then it might be possible to use Kustomize's `valuesFile` or `additionalValuesFiles` fields to point to it and then pull in those dynamic values.

# Motivation

There are a lot of folks who like to use upstream helm charts but need to add additional manifests or tweaks to them. Some recommend forking the charts, but this is often a maintenance nightmare. Instead combining `kustomize` and `helm` together can provide a very maintainable middle ground. However, with ArgoCD one loses the capability to easily pass in dynamic values that are defined in the Application YAML.

ArgoCD plugins can be created to do this, but it feels like an integrated solution should be achievable here.

# Proposal

Off the top of my head, generating a temporary file with a well-known name and location during the rending process seems like a method that would allow folks to set Kustomize to pull that values file in when it is doing the rendering work. 

The file name and location could be set by an argument in the Application definition, as well.

It would also mean that values should either be definable under the `kustomize:` header in the application, or via the normal `helm:` header, even when using `kustomize` to do the rendering.

There might be a better approach, but the primary goal here is to discuss and find the right approach for Argo.

**Comment by crenshaw-dev** [comment]
iirc, the Kustomize Helm feature provides the ability to set inline Helm values in kustomization.yaml.

The Application `spec.source.kustomize` field is meant to be basically a 1:1 map to kustomization.yaml (or, more specifically, the `kustomize edit` commands).

Could we just add a field to `spec.source.kustomize` to thread through arbitrary values to the kustomization.yaml inline Helm values field?

**Comment by spkane** [comment]
> The Application spec.source.kustomize field is meant to be basically a 1:1 map to kustomization.yaml (or, more specifically, the kustomize edit commands).

@crenshaw-dev Hmmm, I didn't realize that. that is good to know.

Indeed there are fields in the `kustomization.yaml` that can be used:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    releaseName: karpenter
    namespace: kube-system
    version: 0.35.2
    valuesFile: helm-values.yaml
   valuesInline:
     settings:
       clusterName: myAwesomeCluster 
```

I think the one issue with this approach might be that this will only edit the `kustomization.yaml` that ArgoCD is pointing directly at, which in this case would work since we are pointing at a `kustomization.yaml` in an overlay (`overlays/staging`) that has the helm chart defined in it, BUT if the helm chart was defined in the `kustomization.yaml`  that is in the `../../base` directory that this file points at then, I don't believe that this approach would work. That being said, even getting this far might provide enough elbow room to make this work in most cases.

- This is a link to the subkeys that the `helmCharts` key supports: 
  - https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_

**Comment by joebowbeer** [comment]
One easy way ArgoCD can support value patching is to add `helmCharts` to the kustomize "configuration options" that can appear in an Application source. Then an ApplicationSet can apply template patching to the valuesInline as well as other parts:

```yaml
helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    releaseName: karpenter
    namespace: kube-system
    version: 0.35.2
    valuesFile: helm-values.yaml
    valuesInline:
      settings:
        clusterName: '{{.values.clusterName}}'
```
