### ISSUE TITLE
Add optional `name` reference to Source object

### ISSUE THREAD

**Issue by agaudreault** [argoproj/argo-cd#17731]
# Summary

With the support of multi-source, it is only possible to reference a source by it's position in the list. If people build automation around sources and the order change, it could break the users workflow.

Adding an optional `name` parameter to the `source` object would allow to build safer automation and facilita the identification of sources in the UI.

# Motivation

When using the CLI with multi-source application.

Before
```
argocd app manifests test --revisions d7927a27b4533926b7d86b5f249cd9ebe7625e90 --revisions 53e28ff20cc530b9ada2173fbbd64d48338583ba --source-positions 1 --source-positions 2
```

After
```
argocd app manifests test --revisions d7927a27b4533926b7d86b5f249cd9ebe7625e90 --revisions 53e28ff20cc530b9ada2173fbbd64d48338583ba --source-names gitops-test --source-names base
```

# Proposal

- Add `name` parameter to source
- Add `--source-name` parameter to the CLI. Do not allow to specify both named and position parameters.
- If ref is set for a source and name is not set, evaluate if the name could default the the ref value. (similar to how releaseName has a default of the applicationName if not specified)
- Add in the multi-source UI

```yaml Application CR example
spec:
  destination:
    name: dev
    namespace: dev
  project: tests
  sources:
  - name: base            # <--- can be referenced as "base", or position 1
    chart: hello-world
    helm:
      valueFiles:
      - $gitops-test/services/multi-source-ref/values.yaml
    path: whatever
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
  - path: services/multi-source-with-ref
    ref: gitops-test       # <--- can be referenced as "gitops-test", or position 2
    repoURL: https://github.com/agaudreault/gitops-tests
    targetRevision: test-sync
```

### Related work

https://github.com/argoproj/argo-cd/pull/17425
https://github.com/argoproj/argo-cd/pull/17650
https://github.com/argoproj/argo-cd/pull/17589
https://github.com/argoproj/argo-cd/pull/17275
