### ISSUE TITLE
Pull Request Generator: Allow Posting a Comment with URLs after App is Deployed

### ISSUE THREAD

**Issue by hofq** [argoproj/argo-cd#17730]
# Summary
If I use the ArgoCD Pull Request Generator, I want a Comment to be posted, letting the user know that the Deployment is ready to be tested.

# Motivation
If inexperienced or new devs want to find out where the Deployment can be found, a comment would be useful. For more experienced Devs, it would improve the time needed for accessing it.

# Proposal
There should either be a field for a comment in the CRD, where I can enter the message manually and template the URL, or the URL should be directly commented using available ingresses in the App.

**Comment by mubarak-j** [comment]
This can be achieved using `pullRequestComment` from GitHub notifications service: https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/github/#templates

**Comment by kmadel** [comment]
> This can be achieved using `pullRequestComment` from GitHub notifications service: https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/github/#templates

Is there a better example of this? I feel like I have configured everything correctly but the commit doesn't get updated with a status and no comment is added to the PR. 

Here is the notification-cm:
```
data:
  context: |
    argocdUrl: "{{.context.argocdUrl}}"
  service.github: |
    appID: xxxxxx 
    installationID: xxxxxxx
    privateKey: $github-privateKey
  template.app-deployed: |
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests.
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.spec.source.targetRevision}}"
      status:
        state: success
        label: "continuous-delivery/{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deployment:
        state: success
        environment: dev
        environmentURL: "https://{{.app.metadata.name}}.example.com"
        logURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        requiredContexts: []
        autoMerge: true
      pullRequestComment:
        content: |
          Application {{.app.metadata.name}} is now running new version of deployments manifests.
          See more here: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.operationState?.syncResult?.revision
      send:
      - app-deployed
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
        and app.status.health.status == 'Healthy'
---
```

Here are the logs from the notifications generator:
```
time="2024-04-17T15:28:12Z" level=info msg="Trigger app-deployed result: []" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
time="2024-04-17T15:28:12Z" level=info msg="Trigger on-deployed result: [{[0].Yv81TUs0gmPTEyk-v8Lb6ZKEo0g aa70cd1166fc10844ed918d9ca3023e3089f83ac [app-deployed] true}]" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
time="2024-04-17T15:28:12Z" level=info msg="Notification about condition 'on-deployed.[0].Yv81TUs0gmPTEyk-v8Lb6ZKEo0g' already sent to '{github }' using the configuration in namespace argocd" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
time="2024-04-17T15:28:12Z" level=info msg="Processing completed" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
```

And annotations on Application (generated via ApplicationSet):
```
  annotations:
    notifications.argoproj.io/subscribe.app-deployed.github: ''
    notifications.argoproj.io/subscribe.github: ''
    notifications.argoproj.io/subscribe.on-deployed.github: ''
    notified.notifications.argoproj.io: >-
      {"aa70cd1166fc10844ed918d9ca3023e3089f83ac:on-deployed:[0].Yv81TUs0gmPTEyk-v8Lb6ZKEo0g:github:":1713367089}
```

The last one seems to have been injected by Argo CD.

**Comment by GabSnow24** [comment]
On annotions you need to point out to your GithubApp

`  annotations:
    notifications.argoproj.io/subscribe.app-deployed.github: argocd-githubapp-bot`

**Comment by GabSnow24** [comment]
> > This can be achieved using `pullRequestComment` from GitHub notifications service: https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/github/#templates
> 
> Is there a better example of this? I feel like I have configured everything correctly but the commit doesn't get updated with a status and no comment is added to the PR.
> 
> Here is the notification-cm:
> 
> ```
> data:
>   context: |
>     argocdUrl: "{{.context.argocdUrl}}"
>   service.github: |
>     appID: xxxxxx 
>     installationID: xxxxxxx
>     privateKey: $github-privateKey
>   template.app-deployed: |
>     message: |
>       Application {{.app.metadata.name}} is now running new version of deployments manifests.
>     github:
>       repoURLPath: "{{.app.spec.source.repoURL}}"
>       revisionPath: "{{.app.spec.source.targetRevision}}"
>       status:
>         state: success
>         label: "continuous-delivery/{{.app.metadata.name}}"
>         targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
>       deployment:
>         state: success
>         environment: dev
>         environmentURL: "https://{{.app.metadata.name}}.example.com"
>         logURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
>         requiredContexts: []
>         autoMerge: true
>       pullRequestComment:
>         content: |
>           Application {{.app.metadata.name}} is now running new version of deployments manifests.
>           See more here: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
>   trigger.on-deployed: |
>     - description: Application is synced and healthy. Triggered once per commit.
>       oncePer: app.status.operationState?.syncResult?.revision
>       send:
>       - app-deployed
>       when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
>         and app.status.health.status == 'Healthy'
> ---
> ```
> 
> Here are the logs from the notifications generator:
> 
> ```
> time="2024-04-17T15:28:12Z" level=info msg="Trigger app-deployed result: []" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
> time="2024-04-17T15:28:12Z" level=info msg="Trigger on-deployed result: [{[0].Yv81TUs0gmPTEyk-v8Lb6ZKEo0g aa70cd1166fc10844ed918d9ca3023e3089f83ac [app-deployed] true}]" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
> time="2024-04-17T15:28:12Z" level=info msg="Notification about condition 'on-deployed.[0].Yv81TUs0gmPTEyk-v8Lb6ZKEo0g' already sent to '{github }' using the configuration in namespace argocd" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
> time="2024-04-17T15:28:12Z" level=info msg="Processing completed" resource=argocd/hello-app-vcluster-pro-feature-z-pr10
> ```
> 
> And annotations on Application (generated via ApplicationSet):
> 
> ```
>   annotations:
>     notifications.argoproj.io/subscribe.app-deployed.github: ''
>     notifications.argoproj.io/subscribe.github: ''
>     notifications.argoproj.io/subscribe.on-deployed.github: ''
>     notified.notifications.argoproj.io: >-
>       {"aa70cd1166fc10844ed918d9ca3023e3089f83ac:on-deployed:[0].Yv81TUs0gmPTEyk-v8Lb6ZKEo0g:github:":1713367089}
> ```
> 
> The last one seems to have been injected by Argo CD.

@kmadel On annotions you need to point out to your GithubApp

`  annotations:
    notifications.argoproj.io/subscribe.app-deployed.github: argocd-githubapp-bot`

**Comment by GabSnow24** [comment]
@kmadel also you need to setup the deployment environment on the workflow you are running, and configure notifications to deploy to this environment

**Comment by jalvarezit** [comment]
I have a similar issue, did you manage to solve it @kmadel ? /cc @GabSnow24 

I will briefly describe the issue and what ive done so far so it may help either fix it or find others in the same situation.

* Installed ArgoCD templates, following the [docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/):

```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/notifications_catalog/install.yaml
```

* Already have a Github App so do not need to create one

* Updated *argocd-notifications-secret* to include both slack and github secrets:

![Image](https://github.com/user-attachments/assets/e65d4d77-8cb1-4e38-8f9a-489661546ac6)

* Configured*argocd-cm* ConfigMap:

```yaml
apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  service.github: |
    appID: APP_ID
    installationID: INSTALLATION_ID
    privateKey: $github-privateKey
  statusbadge.enabled: "false"
  template.app-deployed: |
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests!!!.
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: success
        label: "continuous-delivery/{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://github.bs.prefapp.es
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd

```

> I would like both PR comments and commit status but none were working so decided to debug simply trying to get  commit status working.

* Add the ArgoCD applications notification subscriptions:

```yaml
    notifications.argoproj.io/subscribe.on-deployed.github: fs-bs-firestarter-dev-test # This is the Github App name
    notifications.argoproj.io/subscribe.on-deployed.slack: dev
```

> Note that *fs-bs-firestarter-dev-test* is the Github App name installed 

![Image](https://github.com/user-attachments/assets/429d2c76-f329-45c9-95a2-58975012243b)

* At this point slack notificatinos work, however Github does not. Inspecting *argocd-notifications-controller* logs I can see the following:

`Notification about condition 'on-deployed.[0].y7b5sbwa2Q329JYH755peeq-fBs' already sent to '{github fs-bs-firestarter-dev-test}' using the configuration in namespace argocd" resource=argocd/state-infra`

However checking calmly the logs i saw this one error:

`Failed to notify recipient {github fs-bs-firestarter-dev-test} defined in resource argocd/state-infra: notification service 'github'  is not supported using the configuration in namespace argocd" resource=argocd/state-infra`

But does not show a detailed reason why it failed. It should not be a permissions issue since we use this Github App in other places as well to comment PRs, added the permissions required (deployments, commit statuses and pull request comment creation)
