### ISSUE TITLE
Jsonnet arguments from a separate source

### ISSUE THREAD

**Issue by joey-squid** [argoproj/argo-cd#17743]
# Summary

Add the ability to load Jsonnet arguments from a separate source, similar to the support that already exists for Helm values

# Motivation

We currently use Helm charts where values are loaded from a secondary source:
```
      sources:
      - helm:
          valueFiles:
          - $values/some/path/values.yaml
      - ref: values
        repoURL: https://github.com/whatever
        targetRevision: main
```

This allows us to specify Docker labels in a separate repository from the bulk of our ArgoCD configuration, so we can grant our CD permissions on just that repo. I don't think there's currently a similar solution for Jsonnet applications.

# Proposal

```
      sources:
      - directory:
          jsonnet:
            tlas:
              name: foo
              file: true
              value: $values/some/path/values.yaml
```

This builds upon the syntax of #7404. In this case the file would be imported as a string, but I think that PR supports `code: true` as well as `file: true` which would import it as Jsonnet code.
