### ISSUE TITLE
notification - trigger is not configured using the configuration in namespace

### ISSUE THREAD

**Issue by andronux** [argoproj/argo-cd#17773]
Hello everyone,

I keep getting the following error:

`argocd-notifications-controller-65664f4d96-zvxgm notifications-controller time="2024-04-08T08:56:18Z" level=debug msg="Failed to execute condition of trigger on-health-degraded: trigger 'on-health-degraded' is not configured using the configuration in namespace argocd" resource=argocd/kube-prometheus-stack
`

Although I have my service/triggers/templates configured in the configmap argocd-notifications-cm.

Am I missing something here?
Thanks

**Comment by andronux** [comment]
Any help from anyone please?

**Comment by andronux** [comment]
@jannfis any chance you could help me with this?

**Comment by ericjmooney** [comment]
@andronux -- not sure if you have made any progress but i ran into this same issue today.  after a lot of screwing around and trial and error, i have come to believe that it is now necessary to have a `trigger` defined for this thing to work.

this example file was very helpful for me to try to figure out how this should work https://github.com/argoproj-labs/argocd-notifications/blob/master/docs/argocd-notifications-cm.yaml

Ultimately I ended up w/ a configmap like this:

```
apiVersion: v1
data:
  context: |
    argocdUrl: https://my-argocd.ericexample.com

  service.email.smtp: |
    host: mail.ericexample.com
    port: 587
    from: argocd@ericexample.com

  template.eric-app-sync-running: |
    message: |
      The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationState.startedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
    email:
      subject: Start syncing application {{.app.metadata.name}}.

  trigger.app-sync-running: |
    - when: true
      send: [eric-app-sync-running]
``` 

and the annotation on my application like:
    `notifications.argoproj.io/subscribe.app-sync-running.smtp=eric@ericexample.com`

Hope this helps!
