### ISSUE TITLE
Project destination removal does not consider wildcards

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1780]
We had a project which had some project destinations, e.g.

```yaml
- server: https://server1.com
  namespace: my-service-qa
- server: https://server2.com
  namespace: my-service-prod
```

Using the API, we tried to simplify the project by collapsing this using wildcards:
```yaml
- server: *
  namespace: my-service-*
```

However, the API server validation failed with error `Unable to edit project: following destinations are used by one or more application and cannot be removed`.

The bug is that the API server check does not consider wildcards when checking if a project destination removal is already covered by some wildcard destination.

The workaround was to manually edit the project (e.g. using kubectl) to remove the undesired destinations.
