### ISSUE TITLE
Breaking Change in `ApplicationSet`s git generator in `v2.10.6` after upgrading from `v2.10.5`

### ISSUE THREAD

**Issue by ForbiddenEra** [argoproj/argo-cd#17801]
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.
* [x] I've made a thread on Slack asking about my issue
* [x] I've tried reverting to `2.10.5` and then everything worked fine/as expected/as it did previously.
---

Hi,

I just ran into a huge issue (breaking change?) after going from `2.10.5` to `2.10.6`.

I've created a thread on Slack: https://cloud-native.slack.com/archives/C01U45M2SVB/p1712772465106739 but was also recommended to create an issue here.

I use an `ApplicationSet` to deploy many core services in my cluster (including ArgoCD) with the git generator.

My git repo contains git submodules for each service and this has worked great.

The issue I'm having now is that I have two `ingress-nginx` services, and they're in a sub-directory of this repo that contains both of them as sub-directories (git submodules).

My `ApplicationSet` is like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: <redacted>
      revision: HEAD
      directories:
      - path: '*'
      - path: 'ingress-controllers'
        exclude: true
      - path: 'ingress-controllers/*'
  templatePatch: |
    {{- if eq .path.basename "argocd"  }}
      spec:
        destination:
          namespace: '{{.path.basename}}'
        syncPolicy:
          automated: {}
    {{- else }}
      spec:
        destination:
          namespace: ''
    {{- end }}
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      syncPolicy:
        automated: {}
      project: 'core-services'
      source:
        repoURL: <redacated>
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: core
```

This was like this because the `path: '*'` alone didn't pick up 2nd level sub-directories and if I didn't use `exclude: true` on the `ingress-controllers` parent directory, it would create an app called `ingress-controllers` with no resources and ignored the sub-directories (`ingress-controllers/ingress-nginx-internal` and `ingress-controllers/ngress-nginx-external`)

After updating to 2.10.6, my ingress controllers vanished. I tried with:
```yaml
      - path: 'ingress-controllers/ingress-nginx-internal'
      - path: 'ingress-controllers/ingress-nginx-external'
```

But it still just deploys the empty `ingress-controllers` application and doesn't deploy the other two paths. I should note that the `ingress-controllers` sub-directory doesn't contain any manifests or anything else, just the sub-directories ([`ingress-nginx-internal`, `ingress-nginx-external`]).

When adding the exclude back, even with the direct paths listed as above (instead of the wildcard) also results in nothing being deployed.

I'm not sure how to handle this as the docs aren't super clear on handling nested sub-directories for the git generator; there is definitely a breaking change in this minor version bump though - I've confirmed by reverting to `2.10.5` with no changes to the `ApplicationSet` and the ingresses were re-deployed as expected.

(I should note that this also basically locked me out of my Argo as well, at least without giving it a separate loadbalancer in the meantime; fortunately through the magic of Argo, I can simply update the repo to test changes/revert)

**To Reproduce**

I can't provide repo access as this is internal, but you can use the above `ApplicationSet` (feel free to remove the `templatePatch` for `argo`, I just left it for semi-completeness), perhaps like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: <redacted>
      revision: HEAD
      directories:
      - path: '*'
      - path: 'ingress-controllers'
        exclude: true
      - path: 'ingress-controllers/*'
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      syncPolicy:
        automated: {}
      project: 'core-services'
      source:
        repoURL: <redacated>
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: core
        namespace: '{{.path.basename}}'
```

Tree:
```
.
├── CoreServices-ApplicationSet.yaml
├── argocd
├── ingress-controllers
│   ├── ingress-nginx-external
│   │   ├── base
│   │   ├── kustomization.yaml
│   │   └── values.yaml
│   └── ingress-nginx-internal
│       ├── base
│       ├── kustomization.yaml
│       └── values.yaml
```

`kustomization.yaml` for `ingress-nginx-internal`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  namespace: ingress-nginx-internal
  includeCRDs: true
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx-internal
  version: 4.10.0
  valuesFile: values.yaml

resources:
- base/ingress-nginx-internal-ns.yaml
```

`base/ingress-nginx-internal-ns.yaml`:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-internal
```

Unfortunately I can't as it's private but it shouldn't be hard to re-create from the information I've given.

- create a `core-services` git repo
- add `CoreServices-ApplicationSet.yaml` with the above `ApplicationSet` yaml
- create a `ingress-controllers` git repo
- create `ingress-nginx-internal` and `ingress-nginx-external` git repos
- add the `kustomization.yaml` as above in each repo (adjusting the name for internal/external of course)
- add namespace files in `base/ingress-nginx-internal.yaml` (and the same for external, also adjusting name again)
- add `ingress-nginx-internal` and `ingress-nginx-external` as git submodules inside the `ingress-controllers` repo
- add the `ingress-controllers` repo as a submodule inside the `core-services` repo
- add an `Application` in `ArgoCD` that points to the `core-services` repo

The `values.yaml` for `ingress-nginx-*` doesn't really matter, defaults for the helm chart would be fine; heck, you could probably deploy any helm chart or even just a simple `kustomization.yaml` with a simple test pod or something.

I should note that I would expect this same behavior to happen whether or not the sub-directories are actually git submodules or simply plain sub-directories, but I'm being exact for completeness (especially as I've had issues with sub-modules and branches with Argo before, there's still an outstanding issue where apps break when overrides are applied when using sub-modules or deploying an app with multiple branches, in fact it might even affect apps not using either, essentially `git` complains that changes have been made to the repo when argo tries to re-clone, update submodules or switch branches - but this is another problem altogether, which I have created an [issue](https://github.com/argoproj/argo-cd/issues/17207) for, over a month ago, no replies :().

If there's a better way to setup the `ApplicationSet` generator for this case, I'm all ears but this is still something that worked perfectly <`2.10.5` (and also on `2.9.x`) and broke on `2.10.6`. I did briefly review the changes for `2.10.6` and didn't see anything striking that should cause this, but after reverting with no changes to the `ApplicationSet`, it sync'd fine and re-deployed the ingress `Application`s.
