### ISSUE TITLE
`restartPolicy: field not declared in schema` for native sidecars in Kubernetes 1.29

### ISSUE THREAD

**Issue by kaiburjack** [argoproj/argo-cd#17811]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When making use of the Kubernetes Native Sidecars (beta) feature in Kubernetes 1.29 (in GKE) and declaring an `initContainer` with `restartPolicy: Always`, we get the following error message in Argo CD:
```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .spec.jobTemplate.spec.template.spec.initContainers[name="cloud-sql-proxy"].restartPolicy: field not declared in schema
```

This can be mitigated by ignoring the field `restartPolicy` in `initContainers` like so:
```yaml
ignoreDifferences:
  - group: batch
    kind: CronJob
    jqPathExpressions:
      - '.spec.jobTemplate.spec.template.spec.initContainers[].restartPolicy'
```
But it's not my preferred solution.

**To Reproduce**

- Create a Kubernetes cluster with at least version 1.29 with the native sidecar feature enabled (like it is by default for GKE 1.29 clusters)
- create an Argo CD application that wants to create a CronJob with an initContainer having `restartPolicy: Always`

**Expected behavior**

Argo CD should support restartPolicy on initContainers (for the Kubernetes native sidecar feature).

**Version**

- Argo CD Version: v2.10.6+d504d2b

**Comment by matthewhughes-uw** [comment]
I just ran into an issue with the same cause, although I didn't see an error like above, instead I was presented with a confusing diff like:

```diff
-             cpu: '0'
+             cpu: 0m
              memory: 1Gi
            requests:
-              cpu: '0'
+              cpu: 0m
```

This was on a deployment with a `.spec.template.spec.containers[0].resources':

```yaml
limits:
  cpu: 0m
  memory: 1Gi
requests:
  cpu: 0m
  memory: 100Mi
```

and an `initContainer` with `restartPolicy` set. In my case that diff was generated because `github.com/argoproj/gitops-engine` is using [` v0.26.4` of `k8s.io/apimachinery`](https://github.com/argoproj/gitops-engine/blob/fbecbb86e41254a75a59943b5eb43ed55d21cdb9/go.mod#L17) so when it creates a `k8s.io/apimachinery/pkg/runtime.Object(*k8s.io/api/apps/v1.Deployment)` it isn't aware of the `restartPolicy` field.

I'm not sure why I didn't see the same error message as you (I believe the underlying issue is the same) my debugging was rather slower (see that makes logging related to this a bit nicer https://github.com/argoproj/argo-cd/pull/17871)

**Comment by crenshaw-dev** [comment]
Reproduced this in 8ca96a9d0e9f26821e72a163c5630a25f34ee1ce with k8s 1.29.6.

Confirmed that this fixes it: https://github.com/argoproj/gitops-engine/pull/588

I used this spec:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: nginx-sidecar
          image: nginx:1.14.2
          restartPolicy: Always
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```
