### ISSUE TITLE
Add a layer of overrides

### ISSUE THREAD

**Issue by evrardjp** [argoproj/argo-cd#1784]
**Is your feature request related to a problem? Please describe.**

Currently, argo-cd relies on a chart repository to deploy a manifest, whatever the method is (helm, directory, ksonnet, kustomize).

There is only one way to currently override the application behaviour: using live parameters ("set") within argo CLI [1].

This is an anti-pattern of the gitops behaviour, as expressed in the documentation.

I think another layer should be added (defaulting to an empty directory) of overrides, by adding another source to the deployed application.

[1]: https://argoproj.github.io/argo-cd/user-guide/parameters/

**Describe the solution you'd like**
I would like to have an extra thing next to "set", like "application overrides". This "application overrides" layer would be like any othe repository, (url, commit sha, branch, ...).

What would actually happen is that in the preparation phase, files would be copied into a temporary directory, containing both the "upstream" application source (copied first) and the "application layer" (copied second).

That would allow flexibility in terms of overriding. You could override a whole file by shadowing a file in the "application layer".
Alternatively, you could completely modify the behaviour of the deploy:
Let's say the "upstream" application is a series of manifests, you could add a kustomize file and completely alter the deployment.

The only problem I see is the added complexity (optional though), the lack of 
versioning of the resulting state (but do we need that? Should there be a git repo for the "stored" state then?), and we would probably have to disable the ability to guess what's deployed from the "upstream" repository location (as it could be completely modified).

**Have you thought about contributing yourself?**

Yes, I am fine driving that change, but I need to know if that sounds realistic, and I would require some guidance. I am not available on Slack, sadly.

**Comment by evrardjp** [comment]
I realise this is achievable by having a series of forked repositories who would be rebased regularily. I consider there are some cases where this should be avoided.

**Comment by spencergilbert** [comment]
I believe currently (at least for helm) you can pass source.helm.parameters in the application crd to do this in a more gitops friendly way: 

```
spec:
  destination:
    namespace: polaris
    server: https://kubernetes.default.svc
  project: dev-polaris
  source:
    helm:
      parameters:
      - name: templateOnly
        value: "true"
      - name: fullnameOverride
        value: polaris
    path: stable/polaris
    repoURL: https://github.com/reactiveops/charts.git
    targetRevision: HEAD
```

https://argoproj.slack.com/archives/CASHNF6MS/p1560901159047500?thread_ts=1560899817.040500&cid=CASHNF6MS
