### ISSUE TITLE
ArgoCD landed AVP Secrets with placeholder values due to application-controller crash loop

### ISSUE THREAD

**Issue by paterczm** [argoproj/argo-cd#17855]
Hello!

We're using ArgoCD to manage cluster configurations. Recently, the application-controller pod entered a crashloop due to OOM errors. It happens. The concerning part is that it caused a service degradation on the clusters it manages by replacing values in argocd-vault-plugin managed Secrets with placeholder values, as if the plugin sidecar didn't run at all. For example, this is what it did to the apiserver crt:

```yaml
apiVersion: v1
data:
  tls.crt: PHRscy5wZW0+
  tls.key: PHRscy5rZXk+
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: apps/data/../cluster/apiserver
  labels:
    app.kubernetes.io/instance: cluster
  name: apiserver-tls
  namespace: openshift-config
type: kubernetes.io/tls
```

```
❯ echo PHRscy5wZW0+ | base64 -d
<tls.pem>

❯ echo PHRscy5rZXk+ | base64 -d
<tls.key>
```

Multiple Secrets were affected (not all) and some services did not take it well, resulting in cluster degradation.

I experimented with this later and was able to reproduce with following steps:
1. Install ArgoCD from gitops-operator 1.12.1 (v2.6.15+unknown)
2. Setup AVP plugin as a sidecar.
3. Create ArgoCD application(s) managing Secrets using AVP.
4. Set memory limit so that application-controller gets OOMKilled. 

Expected results:
Sync does not work at all or works partially, but when and where it works, it delivers correct resources, with Secrets correctly populated from Hashicorp Vault using argocd-vault-plugin (AVP).

Actual results:
A number of Secrets got synced with placeholder values instead of actual tokens/certs/passwords from Hashicorp Vault.

When application-controller is stable, ArgoCD works as expected. The issues observed with Secret resolution or otherwise.

```
$ argocd version
argocd: v2.10.3+0fd6344
  BuildDate: 2024-03-13T19:37:04Z
  GitCommit: 0fd6344537eb948cff602824a1d060421ceff40e
  GitTreeState: clean
  GoVersion: go1.21.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.15+unknown
  BuildDate: 2023-11-02T14:22:54Z
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 1970-01-01T00:00:00Z
  Helm Version: v3.10.0+ge534a5d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

```
  avp-kustomize.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - bash
          - "-c"
          - "set -o pipefail; kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
```
