### ISSUE TITLE
ArgoCD AVP plugin update not detected

### ISSUE THREAD

**Issue by raweber42** [argoproj/argo-cd#17856]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

I had a issue where I updated my argocd-vault-plugin version and I couldn't make ArgoCD see it. Hard refreshing, scaling up and down, removing the redis pod, nothing worked. The version was updated by bumping the version in the initContainer downloading the plugin:
```
      initContainers:
        - name: download-tools
          image: alpine:3.8
          command: [sh, -c]
          env:
            - name: AVP_VERSION
              value: "1.17.0" <---- UPDATED FROM 1.11.0
          args:
            - >-
              wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 && chmod +x argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
```
For debugging I finally added an echo command ` && echo "Downloaded argocd-vault-plugin version: ${AVP_VERSION}"` at the end of the download command and all of the sudden it worked and the version got updated in the `argocd-repo-server`. This seems very odd to me. It seemed to me like the plugin version was cached somehow, but I couldn't verify that. Maybe it's also related to me running older versions (ArgoCD: `v2.4.27` and AVP plugin: `1.11.0`). Any ideas?
BTW: The plugin is not installed via Sidecontainer, but with ArgoCD-cm. And the plugin is the `helm` version of the AVP plugin.

**To Reproduce**

- Use above configuration for adding an initContainer to your repo-server and install the plugin.
- Verify the installation by logging in to the `repo-server` pod and running `argocd-vault-plugin version`
- Update the version in the config file
- Apply the new configuration
- Run the `argocd-vault-plugin version` again and see that the version didn't get updated.

**Expected behavior**

Best would be, that the changes get detected, the pod restarts and the new plugin is installed instantly. Having to restart the pod manually would be acceptable too.

**Screenshots**

**Version**

```v2.4.27```

**Logs**

```
Paste any relevant application logs here.
```
