### ISSUE TITLE
labels not syncing, v2.10.7+b060053

### ISSUE THREAD

**Issue by lknite** [argoproj/argo-cd#17862]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.

**Describe the bug**

I have a [LIVE MANIFEST] showing some labels & [DESIRED MANIFEST] showing the same labels minus one... but the [DIFF] isn't showing the labels and its not removing the one label as I would expect.  All things showing Synced and green.  Why isn't it removing the label?

I have never manually modified the labels using the argocd gui, or kubectl, the labels are only managed by argocd & the git repo being used.

**To Reproduce**

Working on this, but going ahead and submitting the issue in case there is already a known issue or easy fix.  I swear this was working just fine before ...

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters-prod
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: target
        server: https://...:6443

  template:
    metadata:
      name: '{{name}}-clusters-prod'
    spec:
      project: default
      source:
        repoURL: ...
        targetRevision: HEAD
        path: clusters

        directory:
          recurse: true

      destination:
        server: '{{server}}'

      syncPolicy:
        automated:
          selfHeal: true
          prune: false
```

**Expected behavior**

I would expect argocd to show the label in the [DIFF] tab, and eventually remove the label from the live manifest.

**Screenshots**
desired manifest:
![image](https://github.com/argoproj/argo-cd/assets/92187614/9a4e88ea-f145-47f6-968d-9f5b3d781f78)
live manifest:
![image](https://github.com/argoproj/argo-cd/assets/92187614/4c3ab096-b1f1-415e-8c09-a287f0b9f4d3)
diff not showing any differences:
![image](https://github.com/argoproj/argo-cd/assets/92187614/da68a944-1b60-4a17-82b4-89b517f3ed29)
