### ISSUE TITLE
Argo CD should detect unknown fields in invalid specs as OutOfSync

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1787]
If a user has the following in their git repo, we will not detect it as OutOfSync.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: invalid-cm
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
invalidKey: asdf
```

This is because we drop `invalidKey` as part of remarshalling/normalization when we do comparisons.
