### ISSUE TITLE
Support  same repository address but different projects

### ISSUE THREAD

**Issue by yyzxw** [argoproj/argo-cd#17897]
# Summary

similar to https://github.com/argoproj/argo-cd/issues/9581 ,  support same repository address in different projects.

# Motivation

we used ArgoCD as the backend engine for GitOps, and in a multi-tenant scenario, we isolated different projects as tenants. So we want different projects to save the same url, because even with the same url, their credentials may be different.  or just distinguish by project. 

# Proposal

1. repo store
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: repo-83006512331
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  name: repoName
  project: projectID
  type: git
  url: gitURL
```
why don't we use `project` and `url` as the key to create and query.

2. repo connection state

as mentioned above, the same URL may use different credentials, so also need to get the connection status of the repository for each `project` and `url` as the cache key.

3. repo credentials 
``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: argoproj-https-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/argoproj
  type: helm
  password: my-password
  username: my-username
  project: projectID     # add field
```
add `project` field. but there seems to be too much duplication with the repo definition. maybe it can be removed.

4. how implement?
 
- create
   use `default` project as default project if user not select project, is also for compatibility. 
- query
   query repo list need add `project` as query param
- repo state
  repo cache key format: 
  ```
  repo|repoURl|project|connection-state
  ```
  the cache needs to be rebuilt.

Or if there's any way to do that, please let me know. Thank you!

If this proposal is acceptable, I will submit a PR for it.
