### ISSUE TITLE
`no repository definition` in Plugins but declared in argocd-cm already

### ISSUE THREAD

**Issue by eric4545** [argoproj/argo-cd#1797]
**Describe the bug**
Following example [kustomized-helm](https://github.com/argoproj/argocd-example-apps/tree/master/plugins/kustomized-helm)

Helm repo did not added with using plugin, causing error `Error: no repository definition for alias:istio. Please add them via 'helm repo add'\n"`

**To Reproduce**
1. Create `argocd-cm`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  helm.repositories: |
    - url: https://storage.googleapis.com/istio-release/releases/1.2.0/charts
      name: istio
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm init --client-only && helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template . > all.yaml && kustomize build"]
```
2. Create application
```yaml
# istio-init/Chart.yaml
name: istio-init
---
# istio-init/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - all.yaml
---
# istio-init/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
# istio-init/requirements.yaml
dependencies:
- name: istio-init
  version: 1.2.0
  repository: alias:istio
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-init
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: addons
  source:
    repoURL: git@github.com:eric4545/deployments.git
    targetRevision: HEAD
    path: istio-init
    plugin:
      name: kustomized-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated: {}
```

**Expected behavior**
Application should deployed with no error

**Version**

```shell
argocd: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:28:05Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.0.2+e0bd546.dirty
  BuildDate: 2019-06-14T17:15:03Z
  GitCommit: e0bd546a07818ec06a27c2b3033454e3eb1c4152
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
time="2019-06-21T08:48:36Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.request.deadline="2019-06-21T08:49:34Z" grpc.service=repository.RepoServerService grpc.start_time="2019-06-21T08:48:34Z" grpc.time_ms=2125.161 span.kind=server system=grpc
time="2019-06-21T08:48:38Z" level=info msg="/bin/sh -c helm init --client-only && helm dependency build"
time="2019-06-21T08:48:39Z" level=error msg="`/bin/sh -c helm init --client-only && helm dependency build` failed: Error: no repository definition for alias:istio. Please add them via 'helm repo add'\n"
time="2019-06-21T08:48:39Z" level=error msg="finished unary call with code Unknown" error="Error: no repository definition for alias:istio. Please add them via 'helm repo add'" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2019-06-21T08:49:34Z" grpc.service=repository.RepoServerService grpc.start_time="2019-06-21T08:48:34Z" grpc.time_ms=4588.803 span.kind=server system=grpc
```
