### ISSUE TITLE
No diff detected in maps with ServerSideDiff enabled

### ISSUE THREAD

**Issue by jrcast** [argoproj/argo-cd#18038]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Drift in maps part of resources monitored by ArgoCD applications is not detected when server-side diff is enabled (`controller.diff.server.side: true` in `argocd-cmd-params-cm`), This is happening with multiple resource types. So far, I have reproduced this using (k8s services, workflowtemplates.argoproj.io, CRDs)

**To Reproduce**
1. Enable server-side diff + restart argocd components.
2. Using ArgoCD UI or `kubectl`, edit a K8s service that is monitored by an ArgoCD application. i.e. Add an extra port to the list.
3. In the ArgoCD UI, press refresh/hard-refresh and Sync. 
4. Verify ArgoCD live manifest shows the change applied, desired manifest doesn't. The diff tab is blank (no diff detected)

Desired manifests:
```yaml
apiVersion: v1
kind: Service
metadata:
  {...}
spec:
  ports:
    - name: service-port
      port: 80
      protocol: TCP
      targetPort: service-port
  selector:
  {...}
  type: ClusterIP
```
  
Live Manifest: (Note the extra port. This was added manually)
```yaml
apiVersion: v1
kind: Service
metadata:
  {...}
spec:
  ports:
    - name: service-port
      port: 80
      protocol: TCP
      targetPort: service-port
    - name: shouldntbehere    # <<<< THIS 
      port: 8080
      protocol: TCP
      targetPort: service-port
  selector:
  {...}
  type: ClusterIP
```

The same can be observed in other resource types.

**Expected behavior**
ArgoCD detects the drift, marks the application "Out Of Sync", and (if Self-Heal is enabled) fixes the drift.

**Screenshots**
Live Manifests
![image](https://github.com/argoproj/argo-cd/assets/22987396/db1550fc-ef95-4573-9d21-08ff5c800bc0)

Desired Manifest
![image](https://github.com/argoproj/argo-cd/assets/22987396/e049dee6-5696-45c1-ab67-ea9bf89362be)

Diff
![image](https://github.com/argoproj/argo-cd/assets/22987396/e56df649-e93f-4ed1-891c-a89b33beca73)

**Version**

```shell
argocd-server: v2.10.7+b060053
  BuildDate: 2024-04-15T09:05:25Z
  GitCommit: b060053b099b4c81c1e635839a309c9c8c1863e9
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: 5.1.1 unknown
  Helm Version: v3.13.1+gv3.13.1
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**
Nothing out of the ordinary here. 
```
time="2024-04-30T22:23:27Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" appl
ication=argocd/example-app

time="2024-04-30T22:23:27Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespa
ce: myns)" application=argocd/example-app

time="2024-04-30T22:23:27Z" level=info msg="GetRepoObjs stats" application=argocd/example-app build_options_ms=0 
helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=10 unmarshal_ms=10 version_ms=0

time="2024-04-30T22:23:27Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd/
example-app

time="2024-04-30T22:23:27Z" level=info msg="Update successful" application=argocd/example-app

time="2024-04-30T22:23:27Z" level=info msg="Reconciliation completed" application=argocd/example-app dedup_ms=0 d
est-name= dest-namespace=myns dest-server="https://kubernetes.default.svc" diff_ms=2 fields.level=2 git_m
s=11 health_ms=1 live_ms=3 patch_ms=15 setop_ms=0 settings_ms=0 sync_ms=0 time_ms=106

```
