### ISSUE TITLE
OIDC: PKCE Incorrectly Uses Base Redirect URL for ArgoCD Hosted Under Custom Path

### ISSUE THREAD

**Issue by ptr1120** [argoproj/argo-cd#18045]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

I'm hosting ArgoCD at a custom base path (`mycompany.org/infra/argocd`) and using Keycloak as an external IdP. The configuration functions as expected until I enable PKCE (Proof Key for Code Exchange). Specifically, when enablePKCEAuthentication is set to true in the `argocd-cm` config map, the ArgoCD frontend incorrectly uses `window.location.origin` as the redirect URL, as demonstrated in the `getPKCERedirectURI` function located in [utils.ts](https://github.com/argoproj/argo-cd/blob/50027733db96e793c057fa64690cbbc38b76fda4/ui/src/app/login/components/utils.ts#L26C36-L26C57). 

**To Reproduce**

* Host Argocd under a sub-path, e.g. https://mycompany.org/infra/argocd/
* Configure an Idp Provider

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://mycompany.org/infra/argocd/
  enablePKCEAuthentication: true
  oidc.config: >-
    name: Keycloak
    issuer: https://<redacted>
    clientID: <redacted>
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes:
    - openid
    - profile
    - email
    - roles
    logoutURL: https://<redacted>/protocol/openid-connect/logout?redirect_uri={{logoutRedirectURL}}&id_token_hint={{token}}
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  - server.rootpath=/infra/argocd
  - server.basehref=/infra/argocd
```

* Click on `Login via Keycloak` button

**Expected behavior**

ArgoCD should respect one of the configured parameters (`server.rootpath`, `server.basehref`, or `url` from the `argocd-cm` or `argocd-cmd-params-cm` config map) to determine the correct base URL for redirects.

**Version**

```shell
v2.11.0-rc3+20fd621
```
