### ISSUE TITLE
helm values files wildcard in multi source

### ISSUE THREAD

**Issue by mysiki** [argoproj/argo-cd#18078]
# Summary

Add the availability to inject helm values files with wildcard in Application and ApplicationSet.

# Motivation

As generator cannot merge all the files (matrix / merge are limitated to 2 levels) it can be good to use * in valuesFile for helm. 

Specially because argo have this really good capacity to load files from external git repo ! This allow to manage external values files woth auto loading and avoid to change the application to inject new data. As the files are merge, it will be really simple to split data files. 

Currently : 

```yaml
      sources:
        - helm:
            valueFiles:
              - $externalNames/prd/subnets.yaml
              - $externalNames/prd/vpcs.yaml
              - $externalNames/prd/instancesByAccount.yaml
              - $externalNames/prd/route53HostedZones.yaml
              - $globalconfig/configuration.yaml
          path: Chart
          repoURL: >-
            https://gitlab.XXX/YYYY
          targetRevision: develop
        - ref: globalconfig
          repoURL: >-
            https://gitlab.XXX/BBB
          targetRevision: 1.1.0
        - ref: externalNames
          repoURL: >-
            https://gitlab.XXX/CCC
          targetRevision: master
```

# Proposal

Just with glob patern inside valuesFiles (for application AND applicationSet) 

```yaml
      sources:
        - helm:
            valueFiles:
              - $externalNames/prd/*.yaml
              - $globalconfig/configuration.yaml
          path: Chart
          repoURL: >-
            https://gitlab.XXX/YYYY
          targetRevision: develop
        - ref: globalconfig
          repoURL: >-
            https://gitlab.XXX/BBB
          targetRevision: 1.1.0
        - ref: externalNames
          repoURL: >-
            https://gitlab.XXX/CCC
          targetRevision: master
```

**Comment by gioppoluca** [comment]
this could be useful

**Comment by AnubhavSabharwa** [comment]
Please consider this

**Comment by shearn89** [comment]
This would be very beneficial - we use different files to break up large sets of values for apps to make them easier to read/manage/diff, but also to separate out permissions for secrets. Given these files can vary per app, I'd rather be able to do this:

```
          helm:
            ignoreMissingValueFiles: true
            passCredentials: true
            valueFiles:
              - "$values/{{ values.sharedPath }}/*.yaml"
              - "$values/clusters/{{ clusterName }}/system/{{ values.appName }}/*.yaml"
```

than this:

```
          helm:
            ignoreMissingValueFiles: true
            passCredentials: true
            valueFiles:
              - "$values/{{ values.sharedPath }}/image-tag-value.yaml"
              - "$values/clusters/{{ clusterName }}/system/{{ values.appName }}/image-tag-value.yaml"
              - "$values/{{ values.sharedPath }}/values.yaml"
              - "$values/clusters/{{ clusterName }}/system/{{ values.appName }}/values.yaml"
              - "$values/{{ values.sharedPath }}/values.encrypted.yaml"
              - "$values/clusters/{{ clusterName }}/system/{{ values.appName }}/values.encrypted.yaml"
              - ... some more files that I have to list individually for every app ...
```
