### ISSUE TITLE
Multiple source values ref in "app details"-"parameters" do not show targetRevision

### ISSUE THREAD

**Issue by gioppoluca** [argoproj/argo-cd#18088]
# Summary

In the UI there is no reference on the targetRevision of the values

# Motivation

We use che changing of the values to map the change of a release from the same helm version (there can be a simple change of values that needs to be tracked) and this is not shown anywhere

# Proposal

Add the information on the targetRevision in the "app details"-"parameters"

**Comment by keithchong** [comment]
The "app details"-"parameters" panel does not currently support multiple source apps.  It actually only shows the parameters from the first source.  

Could you please attach your application manifest or if that's not possible, reduce it to show only the pertinent elements, including the _sources_ field/element ?

**Comment by gioppoluca** [comment]
Here is an example:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-01-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    recipients.argocd-notifications.argoproj.io: email:mail@dummy.com
spec:
  destination:
    namespace: app-01-prod
    name: mycluster-prod01-argo-cluster
  project: appproj
  sources:
    - chart: app
      helm:
        releaseName: app-release-01
        valueFiles:
          - $values/gitops/customer-01/prod/values-prod.yaml
      repoURL: http://myrepo/artifactory/helm-projects
      targetRevision: 0.0.1
    - ref: values
      repoURL: https://mygit/products/app/app-envs.git
      targetRevision: 0.0.2
```
**application.yaml** and **values-prod.yaml** are placed both in the /gitops/customer-01/prod folder of the https://mygit/products/app/app-envs.git - there are different folder for other envs/customers
Since the targetRevision of the values.yaml is the one that defines the changes my interest is to be able to see that revision number not the one of the chart that being the generic infrastructure of the product stay the same
