### ISSUE TITLE
Document best practices for preview apps

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1811]
Enough users want to create preview apps that we should document this.

A *preview app* is a version of an app that has things tweaked, and are typically ephemeral. For example:

* Ingress hostname change to include PR number.
* Replicas (fewer).
* Service name, so that the deployment routes to the correct ingress.
* Prefix the namespace (e.g with PR number).

Approaches currently in play:

1. Create a branch of the repository and patch the files (onerous, requires write permissions)
2. Use commands such as `app patch` and `app patch-resource`.

We should document current approaches.

See also #1157, #1481.

**Comment by anarcher** [comment]
Current approach (using argocd commands) is a good approach. But I would like to have a more declarative approach. Such as Using Application CRD as Application Template.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: branch-apps
  annotations:
     argoproj.io/argocd/branches/*: Disallow  // disallow to make apps 
     argoproj.io/argocd/branches/test: SyncPolicy=auto // default sync policy is manual?
     argoproj.io/argocd/branches/staging: SyncPolicy=manual
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: ${branch}
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-${branch}
opertation:
   patches:
      - '[{"op": "replace", "path": "/spec/destination/namespace", "value": "gurstbook-${branch}"}]' 
```

This Application CRD makes other Application CRD with branches. This `branch-apps` makes applications with current branches. If a branch is deleted, this application deletes a app related to the branch when this application is syncing. But I'm not sure this approach is more declarative or better than working with CI pipelines. Just small idea.^^;
