### ISSUE TITLE
Diffing Customization is not applied as expected

### ISSUE THREAD

**Issue by santasub** [argoproj/argo-cd#1815]
**Describe the bug**
We have deployed heapster form a helm chart. Within the starting process of this deployment a nanny pod resizes the CPU and memory limits of the heaspter container. This resolves in a "out-of-sync" state in argocd.

We then have tried to configure fuzzy diffing based on the documentation found here:
[Diffing Customization](https://argoproj.github.io/argo-cd/user-guide/diffing/)

The first thing we have noticed is that there is no information on where to put that config. In case of the application level Configuration.

After some digging around we found a hint here:
[docs/operator-manual](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml)

**To Reproduce**
So we now know that it has to be configured in a custum definion called Application wihtin the argocd namespace.

We then tried to edit this resource by simply add the snippet to the yaml. For a start just the cpu limit.

`kubectl edit Application/heapster -n argocd`

```yaml
ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/spec/containers[0]/resources/limits/cpu
```

But unfortunally this does not work and the deployment ist still "out-of-sync"
We also tried to losen up the config by ignoring more than just the limits. So we moved the ignore up to the resource pointer. `/spec/template/spec/containers[0]/resources/` also with no luck.

**Screenshots**
![image](https://user-images.githubusercontent.com/27772872/60091856-d2ff6000-9745-11e9-9275-99c894b4e4fe.png)

**Expected behavior**
The deployment shoud be ignoreing the diff. I would prefer that the specific value is marked as ignored.

**Version**
```shell
argocd: v1.0.2+e0bd546.dirty
  BuildDate: 2019-06-14T17:13:49Z
  GitCommit: e0bd546a07818ec06a27c2b3033454e3eb1c4152
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.0.2+e0bd546.dirty
  BuildDate: 2019-06-14T17:15:03Z
  GitCommit: e0bd546a07818ec06a27c2b3033454e3eb1c4152
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by alexec** [comment]
Related to #1615.

**Comment by alexec** [comment]
We know about this problem with limits (we want to fix it). Have you read this please?

https://argoproj.github.io/argo-cd/user-guide/diffing/

**Comment by alexec** [comment]
Please also try using `argocd app edit`

**Comment by santasub** [comment]
> We know about this problem with limits (we want to fix it). Have you read this please?
> 
> https://argoproj.github.io/argo-cd/user-guide/diffing/

Im sure it is some how related, but we figured out more.

We made some more testing and found out some things. Our fist test was to ignore diff on a other parameter. We took '/spec/replicas' and it was not working too. We tested it on a other deplyment and it was successfull.

So we started to diff the to Application configs and found out that we had the wrong "group:" parameter. it was not "apps" it had to be "extentions" in case of our heapster deployment.

So we did the replicas test on heaspter and voila it workt. But when we wiched back to the limits config, it was not working at all. As a next step we moved up in the ignore list as folows:

- /spec/template/spec/containers[0]/resources/limits/cpu  (not working)
- /spec/template/spec/containers[0]/resources/limits/        (not working)
- /spec/template/spec/containers[0]/resources/                  (not working)
- /spec/template/spec/containers[0]                                    (not working)
- /spec/template/spec                                                          (working)

So if we ignore the whole spec it actualy ignores the limits, but unfortunally much more than that.
It seems that the jsonPointer is not able to get over the "containers[0]" part.

**Comment by alexec** [comment]
Can you try this:

`/spec/template/spec/containers/0/resources/limits/cpu`

i.e "0" rather than "[0]" which is invalid.

**Comment by santasub** [comment]
Yes this actually works. Thank you.
This would be our final config on this.
```
ignoreDifferences:
  - group: extensions
    kind: Deployment
    name: heapster-heapster
    jsonPointers:
      - /spec/template/spec/containers/0/resources/limits/cpu
      - /spec/template/spec/containers/0/resources/limits/memory
      - /spec/template/spec/containers/0/resources/requests/cpu
      - /spec/template/spec/containers/0/resources/requests/memory
```
 As i said befor it would be nice if the UI would mark the ignored fields some how.
Thanks for you help.
