### ISSUE TITLE
Diff on Endpoint confused by IP sorting

### ISSUE THREAD

**Issue by warmfusion** [argoproj/argo-cd#1816]
**Describe the bug**
When using an Endpoint object with a set of IP addresses explicitally declared, when comparing the state against the intention the diff appears to sort the IP addresses Alphanumerically whilst Kubernetes sorts by octet resulting in a mistaken diff output.

**To Reproduce**
Provide a configuration as shown;

``` yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    description: A workaround to support a set of backend IPs for solr
    linkerd.io/inject: disabled
  name: solrcloud
  namespace: engineering-fcsis-vanilla-quantum
subsets:
- addresses:
  - ip: 172.20.10.97
  - ip: 172.20.10.98
  - ip: 172.20.10.99
  - ip: 172.20.10.100
  - ip: 172.20.10.101
  ports:
  - name: solr-http
    port: 8080
```

**Expected behavior**

State in kubernetes is applied and no diff errors are shown.

** Actual Behaviour **

The diff triggers an out-of-sync warning as the IP list gets changed by some part of the system.

**Screenshots**

![Screen Shot 2019-06-25 at 14 09 42](https://user-images.githubusercontent.com/2294568/60101477-bd913280-9753-11e9-8d20-359c88964852.png)

**Version**

```shell
argocd: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:28:05Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.0.1+5fe1447.dirty
  BuildDate: 2019-05-28T17:27:38Z
  GitCommit: 5fe1447b722716649143c63f9fc054886d5b111c
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by alexec** [comment]
Interesting. Can you work around by making sure the Git repo has the ASCII ordered list, rather than the (and admittedly nicer) dictionary order.

**Comment by jessesuen** [comment]
This is the same problem that [HPA has](https://github.com/kubernetes/kubernetes/issues/74099). The only real workaround is to order the list in the same way that Kubernetes orders this list.

It's unlikely that Argo CD can do anything about this because we have no way to understand if list order is significant or not for all types of objects.

**Comment by warmfusion** [comment]
The workaround works as a solution, albeit one that needs a little twiddling if changes are made.

Could there perhaps be a whitelist of known sortable elements for both HPA and endpoints for instance?

**Comment by abhishekjiitr** [comment]
+1, really annoying for endpoint resources with lots of addresses

**Comment by abhishekjiitr** [comment]
> Interesting. Can you work around by making sure the Git repo has the ASCII ordered list, rather than the (and admittedly nicer) dictionary order.

This doesn't seem to work for ascii ordered list. Kubernetes seems to sort the list like this, which is not ascii ordered:
```
apiVersion: v1
kind: Endpoints
metadata:
  name: qa
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.2.4.5
    ports:
      - name: bindexporter
        port: 9119
        protocol: TCP
      - name: nodeexporter
        port: 9100
        protocol: TCP
      - name: postgresexporter
        port: 9187
        protocol: TCP
      - name: apacheexporter
        port: 9117
        protocol: TCP
      - name: jmxexporter
        port: 7090
        protocol: TCP
```
