### ISSUE TITLE
Unable to load data: Request has been terminated Possible causes: the network is offline Origin is not allowed by Access-Control-Allow-Origin the page is being unloaded, etc.

### ISSUE THREAD

**Issue by csyyy106** [argoproj/argo-cd#18170]
I deployed argocd in the k8s cluster, but I kept having this problem. I use： https://github.com/argoproj/argo-cd/blob/master/manifests/namespace-install.yaml    deployed argocd

![image](https://github.com/argoproj/argo-cd/assets/112543052/07447ae3-b5af-446d-af87-89297cfc2ec0)
![image](https://github.com/argoproj/argo-cd/assets/112543052/e8b8bfdb-65d5-4a7a-83aa-200d83f7b973)
![image](https://github.com/argoproj/argo-cd/assets/112543052/b6c6900f-d005-49ea-9d59-13e84f5fc5d3)

Does anyone know why? Install several times, this situation has occurred, feel the network connection is very unstable

**Comment by csyyy106** [comment]
help ME

**Comment by rouke-broersma** [comment]
Usually happens when the UI can't reach the backend api, like when argocd-server is restarting or if your port-forward bugs out or something like that.

**Comment by UriZafrir** [comment]
Hi, I think I have the same issue.
redirect goes from settings to version many times and finally fails
![image](https://github.com/argoproj/argo-cd/assets/35652384/1c0e676e-f1a7-4230-aaab-7edb07d684df)

**Comment by csyyy106** [comment]
> Hi, I think I have the same issue. redirect goes from settings to version many times and finally fails ![image](https://private-user-images.githubusercontent.com/35652384/331420786-1c0e676e-f1a7-4230-aaab-7edb07d684df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDk0MDksIm5iZiI6MTcxNTkwOTEwOSwicGF0aCI6Ii8zNTY1MjM4NC8zMzE0MjA3ODYtMWMwZTY3NmUtZjFhNy00MjMwLWFhYWItN2VkYjA3ZDY4NGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAxMjUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODA0YTVkYjZhMTlkOWMzODcwZDg2ZjJkOTVjNTcxZWJiN2IxYjcxNmUwY2E4ZGVkYmY2ZDc0ZGVjZWI5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y0_lrRFuNJAyZNcbh4_b-Oxed6tuiffV30N8TgiE5Vk)

Have you found a solution yet？

**Comment by UriZafrir** [comment]
Actually yes.
You need to add an annotation to the ingress-nginx:
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

Its actually documented here
https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/
Look for "redirect loop"
I found the solution looking in the issues here i just dont remember what i looked for

**Comment by powellchristoph** [comment]
> Actually yes. You need to add an annotation to the ingress-nginx: nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
> 
> Its actually documented here https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/ Look for "redirect loop" This is the thread i found that talks about it [#2953 (comment)](https://github.com/argoproj/argo-cd/issues/2953#issuecomment-1754074089)

For the record, I have the following Nginx annotations and I still get the error.
```
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/cors-expose-headers: "*, X-CustomResponseHeader"
```

**Comment by andrii-korotkov-verkada** [comment]
What argocd version do you have?

**Comment by manojtalluri12** [comment]
same issue ..........help me plz

**Comment by PatTheSilent** [comment]
@andrii-korotkov-verkada v2.12, seeing this often, my setup does not include a nginx-ingress though.

**Comment by Vinaum8** [comment]
I'm using version 2.13.3 and I'm having this problem in Google Chrome and Edge.

It doesn't happen in Firefox.

When I clear the cache, it works, but it soon happens again.

**Comment by nathanielkeeler** [comment]
Same issue here. Using Chrome and Argo Helm Chart with App Version 2.13.3

**Comment by amirsh98** [comment]
Same issue here.

**Comment by vndr** [comment]
> > Had same issue. I am running helm version 7.8.2 and added this annotations to my values.yaml:
> > ```
> > annotations:
> >       nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
> >       nginx.ingress.kubernetes.io/ssl-passthrough: "true"
> >       nginx.ingress.kubernetes.io/rewrite-target: /
> >       nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > do not getting error again
> 
> I have the configurations you mentioned, following the documentation: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#kubernetesingress-nginx
> 
> I don't have the annotation nginx.ingress.kubernetes.io/rewrite-target: /, my question is:
> 
> Is it necessary to add nginx.ingress.kubernetes.io/rewrite-target: /?

yep, you are right it is not needed, as with `nginx.ingress.kubernetes.io/ssl-passthrough: "true", NGINX Ingress Controller is not teminating SSL; instead it's passing the request directly to ArgoCD. So no rewriting is needed. but you know that moments when something you do not expect to work, just works. 

This is my ingress, I am using. Using common self-sign certificate:
````yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx-homelab
  rules:
  - host: argocd.home.network  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https  # This should be the name of the port, not the number
  tls:
    - hosts:
      - argocd.home.network  # Replace with your domain
      secretName: home-network-tls  # The TLS secret created earlier
````

since path is already `/`, there is nothing to rewrite, but as I sad, that annotation fixed that some way. Was working for ages without, so not sure what changed. it is running on my homelab, did not pay any more attention to it as did not experience any issues since I added.
