### ISSUE TITLE
BUG: UI Error - Helm Chart with values.yaml from private Repo

### ISSUE THREAD

**Issue by Raskosk** [argoproj/argo-cd#18188]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I'm trying to use "Multiple Sources for an Application" as described in the [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/). In my case, I'm trying to install traefik by helm with a custom values.yaml from my on-premise hosted gitlab instance.

**To Reproduce**
1. Create Namespaces "argocd" and "traefik" via kubectl
2. Install ArgoCD via helm CLI with the official [Helm Chart](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd) Version 6.9.0
3. Added "SSH known hosts data" for my on-premise GitLab via UI ( Settings -> Repository certificates and known hosts -> add SSH known hosts) 
4. Add Gitlab-project "traefik-values" (Settings -> Repositories -> Connect Repo -> "via ssh", "git@...", etc ) to validate if connection is successful 
5. Add Traefik-HelmChart as Repository ( Settings -> Repositories -> Connect Repo -> "via https", "helm" ...) to validate if connection is successful 
6. Create an Application with Multiple Sources as described in the [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/), via UI, see the following definition as a reference
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  sources:
    - repoURL: 'git@<internal-gitlab-url>:templates/values-repo.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://traefik.github.io/charts'
       targetRevision: 28.0.0
       helm:
	 valueFiles:
           - $values/<path-to-values>/traefik.yaml
       chart: traefik
```
7. Error Orrcurs, see Screenshot1
8. After reloading the Page, the application is saved (Screenshot2) but needs to be synced twice to succeed

On the other hand, if I deploy the MultisourceApp.yaml by kubectl CLI, no Error occurs.
I checked the Pod Logs for argocd-server and argocd-repo-server and nothing unusual.

**Expected behavior**

Same behavior between 
No Error Message since it seems to work anyway.
And/or some more useful error message since I couldn't find anything in the Pod Logs.

**Screenshots**
![Screenshot1](https://github.com/argoproj/argo-cd/assets/75483160/fe42733e-18f2-4f02-9ed6-34b392dab643)
![Screenshot2](https://github.com/argoproj/argo-cd/assets/75483160/8f81b0bc-e7a3-40fa-9865-0c7e58a4f3f1)

**Version**

```shell
argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
argocd-server:
```
time="2024-05-13T08:25:07Z" level=info msg="received unary call /application.ApplicationService/UpdateSpec" grpc.method=UpdateSpec grpc.request.claims="{\"exp\":1715667448,\"iat\":1715581048,\"iss\":\"argocd\",\"jti\":\"dc0a3088-8722-4570-b8c7-af394c113cd5\",\"nbf\":1715581048,\"sub\":\"admin\"}" grpc.request.content="%!v(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)" grpc.service=application.ApplicationService grpc.start_time="2024-05-13T08:25:07Z" span.kind=server system=grpc
time="2024-05-13T08:25:08Z" level=info msg="admin updated application spec" application=traefik dest-namespace=traefik dest-server="https://kubernetes.default.svc" reason=ResourceUpdated spec="{nil {https://kubernetes.default.svc traefik  false} default nil [] [] <nil> [{git@<internal-gitlab-url>:templates/values-repo.git  main nil nil nil nil  values} {https://traefik.github.io/charts  28.0.0 &ApplicationSourceHelm{ValueFiles:[$values/003.traefik/helm/values.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,} nil nil nil traefik }]}" type=Normal user=admin
time="2024-05-13T08:25:08Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=UpdateSpec grpc.service=application.ApplicationService grpc.start_time="2024-05-13T08:25:07Z" grpc.time_ms=954.052 span.kind=server system=grpc
time="2024-05-13T08:25:08Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2024-05-13T08:24:44Z" grpc.time_ms=23539.604 span.kind=server system=grpc
time="2024-05-13T08:25:08Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2024-05-13T08:24:45Z" grpc.time_ms=23398.465 span.kind=server system=grpc
```
