### ISSUE TITLE
sync is broken with v6.8.0

### ISSUE THREAD

**Issue by jascsch** [argoproj/argo-cd#18190]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

You cannot manually sync any apps anymore with helm chart version 6.8.0.

the error message is:
`Unable to sync: error resolving repo revision: rpc error: code = Unknown desc = repository not found`

**To Reproduce**

try to manual sync an argo app

**Expected behavior**

manual sync worked with before 6.8.0

**Screenshots**

**Version**

```shell
v2.11.0
```

**Logs**

```
Unable to sync: error resolving repo revision: rpc error: code = Unknown desc = repository not found
```

**Comment by jascsch** [comment]
example manifest of redis cache:

```
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: prod
sources:
  - repoURL: >-
      https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    targetRevision: '*'
    helm:
      valueFiles:
        - $valuesRepo/prod-cluster/tools/redis/values.yaml
      releaseName: redis
    chart: redis
  - repoURL: 'https://git.xxx.com/LES/argo.git'
    targetRevision: HEAD
    ref: valuesRepo
```
values.yaml
```
global:
  imageRegistry: registry-xxx.net/dockerhub
image:
  repository: bitnami/redis

architecture: standalone

auth:
  enabled: true
  existingSecret: "redis-secret"

master:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: "100Mi"
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: "50Mi"
```
