### ISSUE TITLE
Enabling preserveResourcesOnDeletion

### ISSUE THREAD

**Issue by austinflowspace** [argoproj/argo-cd#18201]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Context: I use argocd to deploy our Nginx ingress controllers. When deploying I made a small error and called another appSet the same name as the nginx ingress controller which nuked the nginx ingress controllers for production 🫤. After writing up a doc about how to avoid the error I found this [argo doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#prevent-an-applications-child-resources-from-being-deleted-when-the-parent-application-is-deleted). 

It tells you to enable `preserveResourcesOnDeletion: true` under syncpolicy (I also switched to PrunePropagationPolicy=orphan).

Whenever I enable the flag the app sits in out of sync and doesn't register the value preserveResourcesOnDeletion. (ref screenshot)

**To Reproduce**

Steps) Take any example app or appset and under syncPolicy enabled preserveResourcesOnDeletion to true via code. I don't see anything in the UI that references the preserveResourcesOnDeletion.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  # (...)
  syncPolicy:
    preserveResourcesOnDeletion: true

```

**Expected behavior**

Sync Policy to register preserveResourcesOnDeletion that way if Nginx or other critical components are accidentally nuked that they are not completely deleted.

**Screenshots**

<img width="1383" alt="Screenshot 2024-05-13 at 1 02 29 PM" src="https://github.com/argoproj/argo-cd/assets/119883519/fed5c679-f4b6-4ec1-a08b-49fb8a38625a">
**Version**

```shell
argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
application=flowspace-argocd/argo-bootstrap kind=ApplicationSet name=internal-nginx-appset namespace=flowspace-argocd phase=Sync syncId=43375-bjBts
time="2024-05-13T20:01:18Z" level=info msg="Updating operation state. phase: Running -> Succeeded, message: 'one or more tasks are running' -> 'successfully synced (all tasks run)'" application=flowspace-argocd/argo-bootstrap syncId=43375-bjBts
time="2024-05-13T20:01:18Z" level=info msg="sync/terminate complete" application=flowspace-argocd/argo-bootstrap duration=1.000861304s syncId=43375-bjBts
time="2024-05-13T20:01:18Z" level=info msg="updated 'flowspace-argocd/argo-bootstrap' operation (phase: Succeeded)" appNamespace=flowspace-argocd application=argo-bootstrap project=infrastructure
time="2024-05-13T20:01:18Z" level=info msg="Partial sync operation to cea2f2e3d482446031bcf934213c42cc2f639b64 succeeded" application=argo-bootstrap dest-namespace=flowspace-argocd dest-server="https://kubernetes.default.svc" reason=OperationCompleted spec="{&ApplicationSource{RepoURL:ssh://git@github.com/Flowspace-Team/flowspace-manifest,Path:argo,TargetRevision:main,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,Ref:,} {https://kubernetes.default.svc flowspace-argocd  false} infrastructure &SyncPolicy{Automated:&SyncPolicyAutomated{Prune:true,SelfHeal:true,AllowEmpty:false,},SyncOptions:[Validate=false CreateNamespace=true PrunePropagationPolicy=foreground PruneLast=true],Retry:&RetryStrategy{Limit:0,Backoff:&Backoff{Duration:5s,Factor:*2,MaxDuration:3m,},},ManagedNamespaceMetadata:nil,} [] [] <nil> []}" type=Normal
time="2024-05-13T20:01:18Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=flowspace-argocd/argo-bootstrap
time="2024-05-13T20:01:18Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: flowspace-argocd)" application=flowspace-argocd/argo-bootstrap
```

**Comment by austinflowspace** [comment]
Hello! Wanted to make a quick comment as I've continued to test this deployment out and how appsets react to migrating/deleting, etc. 

Context: I'm changing how I do app of apps in my current git repo. While doing this I'm setting the flag PrunePropagationPolicy under syncOptions to orphan. This does work as intended and when I delete the generator for say staging (sole instance arogcd across env) it orphans the resources and they stay alive.

HOWEVER! When I delete the appset even though I have it set to orphan it will delete the resources. I think if we were able to enable preserveResourcesOnDeletion on the appset we would not run into this type of scenario of accidentally deleting resources when creating/deleting/migrating

**Comment by lwabish** [comment]
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: velero
  namespace: argocd
spec:
  syncPolicy:
   # seems not working at all?  
    preserveResourcesOnDeletion: true   

when I delete this applicationset or delete some cluster from the generator, app along with the resources are all deleted.

**Comment by apex-oevans** [comment]
I'm also experiencing the same issue. When I attempt to use `preserveResourcesOnDeletion: true`, it does nothing. It actually rejects it. I'm running the below version:

```
argocd-server: v2.12.2+560953c
  BuildDate: 2024-08-23T03:30:19Z
  GitCommit: 560953c37b343c956f3a18f3db7d006e694c0dc4
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Comment by sshafiullah** [comment]
Still not working. ArgoCD version: v2.11.2
apiVersion: argoproj.io/v1alpha1 kind: ApplicationSet metadata: name: test-appset namespace: argo-cd spec: syncPolicy: preserveResourcesOnDeletion: true

**Comment by kastriotdobratiqi** [comment]
not working on v2.11.8, I still see the finalizer on the application after changing the `preserveResourcesOnDeletion` to `true`. Based on these [docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Application-Deletion/), it shouldn't add that or I'd expect to remove it once applying the policy change.
> An Argo CD resources-finalizer.argocd.argoproj.io finalizer in .metadata.finalizers of the Application if .syncPolicy.preserveResourcesOnDeletion is set to false.

As long as that annotation exists, based on these [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#about-the-deletion-finalizer) it will perform a cascading deletion meaning all the child resources will be deleted.

**Comment by Laakso** [comment]
Yeah I can confirm, this feature does not work anymore. It used to though.

**Comment by abdelraouf-bl** [comment]
same here, version: 2.8.13

**Comment by Ravi-hnr** [comment]
I have an ApplicationSet (ArgoCD v2.12.4) configured with preserveResourcesOnDeletion: true. However, when I delete an application through the ArgoCD UI, all associated resources are still being deleted. According to the ArgoCD documentation(https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Application-Deletion/), resources should not be deleted when an application is removed.

**Comment by reggie-k** [comment]
@Ravi-hnr could you attach logs + AppSet manifest + generated App manifest?

**Comment by austinflowspace** [comment]
@reggie-k, update the GH_TEAM, GH_REPO and IMAGE_PATH. You could just delete that last snippet if you don't want to create argo-image

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: ssh://git@github.com/GH_TEAM/GH_REPO
      revision: main
      files:
        - path: apps/**/**/app.json
  template:
    metadata:
      name: '{{.path.basename}}-{{index .path.segments 1}}'
      labels:
        app: '{{.chart.labels.app}}'
        system: '{{.chart.labels.system}}'
    spec:
      project: '{{.argo.project}}'
      sources: 
        - path: '{{.chart.path}}'
          repoURL: 'ssh://git@github.com/GH_TEAM/helm-charts'
          targetRevision: 'main'
          helm:
            valueFiles:
              - $values/{{.path.path}}/values.yaml
        - repoURL: ssh://git@github.com/GH_TEAM/GH_REPO
          targetRevision: main
          ref: values
      destination:
        name: '{{.path.basename}}'
        namespace: '{{.chart.namespace}}'
  templatePatch: |
    spec:
      syncPolicy:
        {{- if .argo.autosync }}
        automated:
          selfHeal: true
          prune: true
        {{- end }}
        {{- if .argo.preserveResourcesOnDeletion }}
        preserveResourcesOnDeletion: true
        {{- end }}
        syncOptions:
        {{- if .argo.Validate }}
        - Validate=true
        {{- end }}
        {{- if eq .argo.PrunePropagationPolicy "orphan" }}
        - PrunePropagationPolicy="orphan"
        {{- end }}
        {{- if eq .argo.PrunePropagationPolicy "background" }}
        - PrunePropagationPolicy="background"
        {{- end }}
        {{- if .argo.ServerSideApply }}
        - ServerSideApply=true
        {{- end }}
        {{- if eq .argo.PrunePropagationPolicy "foreground" }}
        - PrunePropagationPolicy="foreground"
        {{- end }}
        - PruneLast=true
        {{- if .argo.creatNamespace }}
        - CreateNamespace=true
        {{- end }}
        retry:
          limit: 0
          backoff:
            duration: 5s 
            factor: 2 
            maxDuration: 3m
    {{- if .argo.syncWave.enabled }}
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "{{.argo.syncWave.phase}}"
    {{- end }}
    {{- if .argo.imgUpdater.enabled }}
    metadata:
      annotations: 
        argocd-image-updater.argoproj.io/image-list: 'app=us-docker.pkg.dev/IMAGE_PATH/{{.argo.imgUpdater.image}}'
        argocd-image-updater.argoproj.io/app.update-strategy: latest
        argocd-image-updater.argoproj.io/app.ignore-tags: latest
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: '{{.argo.imgUpdater.branch}}'
    {{- end }}
```

Here is an app.json file

```json
{
  "chart": {
    "namespace": "observability",
    "path": "charts/grafana",
    "labels": {
      "app": "monitoring",
      "system": "observability"
    }
  },
  "argo": {
    "autosync": true,
    "project": "infrastructure",
    "creatNamespace": true,
    "PrunePropagationPolicy": "foreground",
    "preserveResourcesOnDeletion": true,
    "syncWave": {
      "enabled": true,
      "phase": "-90"
    },
    "imgUpdater": {
      "enabled": false,
      "image": "flowspace-",
      "branch": "main"
    }
  }
}
```

then for the values override file:
```yaml
# it can be blank 
grafana:
  assertNoLeakedSecrets: true
```

**Comment by austinflowspace** [comment]
*** the above might be a bad example *** It is currently not even generating in the appset section. Let me grab one of the tutorial apps and deploy it real quick

**Comment by austinflowspace** [comment]
@reggie-k Here is what I did to replicate it:

```
argocd login URL --sso
argocd app create guestbook --repo https://github.com/argoproj/argocd-example-apps.git --path guestbook --dest-server https://kubernetes.default.svc --dest-namespace default
```

I then manually went into the guestbook app and slapped this snippet into the manifest here:
<img width="684" alt="Screenshot 2024-11-30 at 5 58 32 PM" src="https://github.com/user-attachments/assets/a4a036f3-be62-454c-a457-56b131fc2ad1">

As you can see the pod:
<img width="509" alt="Screenshot 2024-11-30 at 5 59 19 PM" src="https://github.com/user-attachments/assets/b83c18c2-e054-4dd6-9929-5419f7a0a2c8">

Lets delete the application in argo. Validate the pod stays
<img width="608" alt="Screenshot 2024-11-30 at 6 00 52 PM" src="https://github.com/user-attachments/assets/1ab9076e-4b62-4438-baf9-ae913cf2d681">

After deleting the application in argo the pod deleted with the rest of the resources.

Note: After slapping the syncPolicy into the guestbook it wasn't even trying to recognize it. It simply ignored it and synced the rest of the manifest.

**Comment by reggie-k** [comment]
The `preserveResourcesOnDeletion` is a field of the AppSet and not of the App, it instructs the AppSet to generate an App without finalizer annotation (finalizer annotation is what causes App resources to be deleted when an App is deleted). Configuring this field on the App has no effect.
More info about the field:
https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Controlling-Resource-Modification/#prevent-an-applications-child-resources-from-being-deleted-when-the-parent-application-is-deleted
More about resources deletion:
https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Application-Deletion/#application-pruning-resource-deletion

**Comment by Laakso** [comment]
@blakepettersson Which version of Argo CD are you using? We are experiencing this issue with version v2.12.4. Our ApplicationSet configuration looks something like this:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappset
spec:
  generators:
  - git:
      files:
      - path: dev/apps/**/*.json
      repoURL: git@github.com:repourl.git
      revision: HEAD
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      name: '{{.app.name}}'
    spec:
      destination:
        namespace: '{{.app.namespace}}'
        server: https://kubernetes.default.svc
      project: '{{.app.argocd_project}}'
      sources:
      - chart: '{{.app.helm.chart_name}}'
        helm:
          parameters:
          - name: image.repository
            value: '{{.app.image.repository}}'
          - name: image.tag
            value: '{{.app.image.tag}}'
          valueFiles:
          - $values/dev/apps/{{- if hasKey .app "current_dir" -}}{{ .app.current_dir
            }}{{- else -}}{{ .app.name }}{{- end -}}/{{- if hasKey .app.helm "values_override"
            -}}{{ .app.helm.values_override }}{{- else -}}values.yaml{{- end -}}
        repoURL: http://chartmuseum.chartmuseum.svc.cluster.local:8080
        targetRevision: '{{.app.helm.chart_version}}'
      - ref: values
        repoURL: git@github.com:repourl.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 5
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
```

**Comment by reggie-k** [comment]
@Laakso I see that you are using both `preserveResourcesOnDeletion` on the AppSet and then `finalizers` in the metadata section of the App.
The two are contradicting, could you verify that your App was created with the finalizer? If so, this is the reason for the deletion of the resources, and this section should be removed from the template.

**Comment by Laakso** [comment]
> The two are contradicting, could you verify that your App was created with the finalizer? If so, this is the reason for the deletion of the resources, and this section should be removed from the template on the AppSet.

Argh, that was it! Thank you so much! I removed the finalizer and the resources were preserved after deleting the ApplicationSet.

**Comment by reggie-k** [comment]
Can this issue be closed?

**Comment by jon-nfc** [comment]
> Given the reported misconfigurations have been resolved, can this issue be closed?

no as i dont have the finalizer set. I use the following for my appsets


``` yaml

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: earth
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: --truncated--
        revision: HEAD
        directories:

          - path: --truncated--
  template:
    metadata:
      name: '{{index .path.segments 2}}'
    spec:
      project: earth

      source:
        repoURL: --truncated--
        targetRevision: HEAD
        path: '{{.path.path}}'
      
      destination:
        name: --truncated--
        namespace: argocd

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 2
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
  syncPolicy:
    applicationsSync: create-update

```

reading the docs at https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/applicationset-specification/ show having `spec.syncPolicy.applicationsSync: create-update` should also prevent deletion, however I've just lost an entire cluster as everything was deleted when a sync decided to fail, which subsequently deleted my entire cluster.

if `preserveResourcesOnDeletion` is also required to prevent delete this should have been made clear as setting `spec.syncPolicy.applicationsSync: create-update` also alludes to appset controller wont delete applications

**Comment by jharlow1** [comment]
I'm also seeing this in 2.13.2


```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vapp-static-resources
  namespace: argocd
spec:
  generators:
... removed for brevity
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true

```

We are not setting a finalizer in the template manually, and when an app is generated, it still has the finalizer on it:


```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2025-03-03T18:32:59Z'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  generation: 30
  name: svc-static-resources-per-usw2-jh01-blue
  namespace: argocd
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ApplicationSet
      name: vapp-static-resources
      uid: 195bd7e1-34c2-46e9-8f7f-e6a9dd069356
```

And, if i remove the cluster from the generator, it deletes all child resources.
