### ISSUE TITLE
argocd-notifications-controller on-delete trigger result is always empty and doesn't send notification

### ISSUE THREAD

**Issue by akennealy** [argoproj/argo-cd#18203]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The `argocd-notifications-controller` controller [on-delete](https://github.com/argoproj/argo-cd/blob/master/notifications_catalog/triggers/on-deleted.yaml) trigger logs an empty result and never triggers the webhook templated. However, I can see a successful `true` result if manually triggered via argcd cli. 

**To Reproduce**

1) Create/apply the on-delete trigger and template (I'm using webhook). Refer to [notifications_catalog](https://github.com/argoproj/argo-cd/blob/master/notifications_catalog) examples.

Trigger:
```yaml
- when: app.metadata.deletionTimestamp != nil
  description: Application is deleted.
  send: [app-deleted]
  oncePer: app.metadata.name
```

Template:
```yaml
  template.app-deleted: |
    webhook:
      mywebhook:
        method: POST
        path: /argo-hooks
        body: |
          {
            "description": "Application is deleted.",
            "klipenvId": "{{.app.metadata.name}}",
            "event": "app_deleted",
            "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "context": "continuous-delivery/{{.app.metadata.name}}"
```
2) Create/apply an Application that subscribes to the `on-delete` trigger
3) Use argocd cli to manually verify that the trigger returns `false`, as expected:
```
argocd admin notifications trigger run on-deleted <app-name>

CONDITION                                RESULT
app.metadata.deletionTimestamp != nil    false
```
4) Delete the app (add the `metadata.deletionTimestamp` field)
5) Use argocd cli to again manually run the trigger and see the result is now `true`
```
argocd admin notifications trigger run on-deleted <app-name>
CONDITION                                RESULT
app.metadata.deletionTimestamp != nil    true
```
6) Bug: Tail the `argocd-notifications-controller` logs, you'll see the `on-delete` trigger always has an empty result:
```
msg="Trigger on-delete result: []" resource=argocd/myapp
msg="Trigger on-delete result: []" resource=argocd/myapp
...
```

**Expected behavior**
The on-delete trigger should fire with a successful result and trigger the webhook template. Also, the info level logs should show the results of the `app.metadata.deletionTimestamp != nil` 

**Version**

```shell
  argocd: v2.10.5+335875d.dirty
  BuildDate: 2024-03-28T18:33:38Z
  GitCommit: 335875d13e018bed6e03873f4742582582964745
  GitTreeState: dirty
  GoVersion: go1.22.1
  Compiler: gc
  Platform: darwin/arm64
```
