### ISSUE TITLE
Invalidated cache for resource in namespace: argocd with the name: argocd-notifications-cm

### ISSUE THREAD

**Issue by win5923** [argoproj/argo-cd#18210]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I'm trying to add TEAMS to ArgoCD Notifications, but it isn't sending notification.

I followed the step from: https://argocd-notifications.readthedocs.io/en/stable/services/teams/

Here is my config: 
argocd-notifications-cm:
```yaml
data:
  service.teams: |
    recipientUrls: 
      channelName: $channel-teams-url
  template.app-deployed: |
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{.app.status.sync.status}}"
        },
        {
          "name": "Repository",
          "value": "{{.app.spec.source.repoURL}}"
        },
        {
          "name": "Revision",
          "value": "{{.app.status.sync.revision}}"
        }
        {{range $index, $c := .app.status.conditions}}
          ,
          {
            "name": "{{$c.type}}",
            "value": "{{$c.message}}"
          }
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Application",
          "targets":[{
            "os":"default",
            "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default",
            "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
          }]
        }]
      themeColor: '#000080'
      title: New version of an application {{.app.metadata.name}} is up and running.
```
argocd-notifications-secret:
```yaml
data:
  channel-teams-url: <base64 encoded webhook>
```

application:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.teams: channelName
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelName
```

**To Reproduce**

1. Open Teams and goto Apps
2. Find Incoming Webhook microsoft app and click on it
3. Press Add to a team -> select team and channel -> press Set up a connector
4. Enter webhook name and upload image (optional)
5. Press Create then copy webhook url and store it in argocd_notifications-secret in argocd-notifications-cm
6. in argocd-notifications-cm ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.teams: |
    recipientUrls: 
      channelName: $channel-teams-url
```
7. Create subscription for your Teams integration:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelName
```
**Expected behavior**

The Incoming Webhook microsoft app can send notifications.

**Screenshots**

**Version**

```shell
argocd: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:56:39Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.9+c071af8
  BuildDate: 2024-04-30T15:53:28Z
  GitCommit: c071af808170bfc39cbdf6b9be4d0212dd66db0c
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

argocd-notifications-controller log:
```
time="2024-05-14T10:00:24Z" level=info msg="invalidated cache for resource in namespace: argocd with the name: argocd-notifications-cm"
time="2024-05-14T10:00:24Z" level=info msg="invalidated cache for resource in namespace: argocd with the name: argocd-notifications-secret"
...
time="2024-05-14T09:53:24Z" level=info msg="Start processing" resource=argocd/mosquitto-test
time="2024-05-14T09:53:24Z" level=info msg="Trigger on-sync-succeeded result: []" resource=argocd/mosquitto-test
time="2024-05-14T09:53:24Z" level=info msg="Trigger on-deployed result: []" resource=argocd/mosquitto-test
time="2024-05-14T09:53:24Z" level=info msg="Processing completed" resource=argocd/mosquitto-test
```
