### ISSUE TITLE
Persistent YAML to JSON Conversion Error with KCL Plugin

### ISSUE THREAD

**Issue by oliver-hofmann-cistec-com** [argoproj/argo-cd#18211]
**Describe the bug**
When attempting to generate manifests using the KCL plugin, I encounter the following error: "failed to unmarshal manifest: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context." This error persists until I perform a hard refresh, despite making no changes to the codebase.

**To Reproduce**
1. Deploy an application using ArgoCD with the KCL plugin.
2. Observe the error in the ArgoCD UI or through CLI output.
3. Note that the error appears consistently until a hard refresh is performed.

**Expected behavior**
Manifest generation should occur without errors, without the need for hard refreshes to correct YAML to JSON conversion issues.

**Version**
- ArgoCD Version: 6.9.1

**Logs**
generating manifests: failed to unmarshal manifest: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context

**Additional context**
The issue occurs consistently under the current setup, using the KCL plugin, and without any recent changes to the YAML files or configurations that might explain this behavior.

**Comment by andrii-korotkov-verkada** [comment]
Can you clarify argocd version, please? 6.9.1 looks like a version of something else.

**Comment by oliver-hofmann-cistec-com** [comment]
thanks for the reply. I forgot to close this issue. The problem was that the repo server component was for some reason not able to finish rendering the manifest and thus argocd recieved a non valid yaml.

**Comment by raweber42** [comment]
For me it was an issue with race conditions due to too many kcl runs in parallel. Supposedly before the fix hundreds of processes were stepping on each other’s cache/temp files.

What fixed it was switching from

```
kind: ConfigMap
apiVersion: v1
data:
  v2.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kusion
    spec:
      version: v2
      generate:
        command: ["sh", "-c"]
        args:
          - |
            kcl run -D ARGOCD_APP_PARAMETERS=${ARGOCD_APP_PARAMETERS} # No caching/dedicated tmpfile
```

to

```
kind: ConfigMap
apiVersion: v1
data:
  v2.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kusion
    spec:
      version: v2
      generate:
        command: ["sh", "-c"]
        args:
          - |
            export KCL_CACHE_PATH=/tmp
            export KCL_PKG_PATH=/tmp
            tempfile=$(mktemp)
            kcl run -D ARGOCD_APP_PARAMETERS=${ARGOCD_APP_PARAMETERS} -o $tempfile > /dev/null 2>&1
            error=$?
            if [ $error -eq 0 ]; then
              cat $tempfile
              rm $tempfile
            fi
            exit $error
```


like [recommended here by the KCL guys](https://github.com/kcl-lang/kcl-lang.io/blob/main/examples/gitops/install/kcl-cmp.yaml).

Maybe putting this here helps someone for debugging in the future.
