### ISSUE TITLE
Annotation not working argocd.argoproj.io/sync-options: Force=true,Replace=true

### ISSUE THREAD

**Issue by ybucci** [argoproj/argo-cd#18245]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I Using the latest version ArgoCD 2.11, but the annotation not working

**error when replacing "/dev/shm/2809239019": EC2NodeClass.karpenter.k8s.aws "aws-node-template" is invalid: spec.role: Invalid value: "string": immutable field changed**

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  name: aws-node-template
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 120Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: XXXXXXXX
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: XXXXXXXX
  subnetSelectorTerms:
  - tags:
      Name: '*private*'
  tags:
    karpenter.sh/discovery: XXXXXXXX
```

```yaml
{{- if and .Values.karpenterTemplates .Values.karpenterTemplates.enable -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-templates
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.karpenterTemplates.syncWave | default '0' }}"
  labels:
    app: "karpenter-templates"
    env: "{{ .Values.environment }}"
    clusterName: "{{ .Values.clusterName }}"
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: 05-helm/karpenter-templates
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |-
{{- toYaml .Values.karpenterTemplates | nindent 8 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.karpenterTemplates.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
#      - Replace=true
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
      # - ServerSideApply=true
      # - Force=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ChristianCiach** [comment]
The commit https://github.com/argoproj/argo-cd/commit/dd4ee8344204ea46edc0ebecbcfda946fda21e85 didn't make it into v2.11.0. You will have to wait for v2.11.1

**Comment by wpbeckwith** [comment]
We are using `quay.io/argoproj/argocd:v2.11.2` and have a job manifest of
```
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
    argocd.argoproj.io/sync-wave: "-1000"
  labels:
    app.kubernetes.io/managed-by: Helm
    framework: unknown
    helm.sh/chart: oz-canary-java-1.0.0
  name: db-migration-oz-canary-java
  namespace: oz-canary-java-prod
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        log-group: oz-canary-java
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -Duser.timezone=America/Los_Angeles -Xms256M -Xmx256M
            - name: PROFILE_NAME
              value: primary
            - name: SCHEMA_NAME
              value: oz_canary_gitops_db
          image: repo/flyway-migration:0.1018.0-1242-1-8bc390f531c3fcc69127cec59c40797b84e8e031
          name: oz-canary-java
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
```
During the dry-sync we see 
```
Dry-run sync failed with message: ComparisonError: Failed to compare desired state to live state: failed to calculate diff: error calculating server side diff: serverSideDiff error: error running server side apply in dryrun mode for resource Job/db-migration-oz-canary-java: Job.batch "db-migration-oz-canary-java" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>
...
 Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil), OS:(*core.PodOS)(nil), SchedulingGates:[]core.PodSchedulingGate(nil), ResourceClaims:[]core.PodResourceClaim(nil)}}: field is immutable
```
Are the annotations not available during a dry-sync with server-side apply?
