### ISSUE TITLE
Options include and exclude not available for Directory type applications when using ApplicationSet

### ISSUE THREAD

**Issue by otherguy** [argoproj/argo-cd#18266]
When using `ApplicationSet`, the `include` or `exclude` options for directory type applications are not available.

Sample manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            phase: demo
  template:
    metadata:
      name: my-app
    spec:
      project: demo
      source:
        repoURL: https://github.com/demo/demo
        path: foo/bar
        include: file.yaml
        targetRevision: HEAD
```

Error:
```
ApplicationSet in version "v1alpha1" cannot be handled as a ApplicationSet: strict decoding error: unknown field "spec.template.spec.source.include"
```
