### ISSUE TITLE
Support sync waves for applicationset

### ISSUE THREAD

**Issue by Emmerson-Miranda** [argoproj/argo-cd#18268]
# Summary

ApplicationSets generate argo applications, sometimes we have dependencies in the order to deploy the applications, for instance istio need cert-manager to be up and running first.

# Motivation

Sometimes we have dependencies in the order to deploy the applications, for instance istio needs cert-manager to be up and running first. I another cases we depends in CRDs deployed by other apps.

I created a bug ticket and I was suggested to open an enhancement proposal here https://github.com/argoproj/argo-cd/issues/17639

# Proposal

We need to be able to generate argo applications with applicationset, inside each application we should be able to use the sync wave annotation.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "-10"

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "-9"
```
