### ISSUE TITLE
manifest-generate-paths annotation and Multiple Sources 

### ISSUE THREAD

**Issue by Emmerson-Miranda** [argoproj/argo-cd#18267]
Hello, 

Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Context**

I have argo applications with two sources:
- The first source is avp-helm plugin. Pull a helm chart and resolve secrets from hashicorp vault ([see docs](https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-additional-helm-arguments)).
- The second source pull helm values from an external git repo ([see docs](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository))

The external git repo has a webhook that notifies argo when we push changes.

In my applications I am trying to use 'argocd.argoproj.io/manifest-generate-paths' as described [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/) because I have a mono repo, the value I am using is a relative path inside the external git repo .

```
argocd.argoproj.io/manifest-generate-paths: ./common-config.yaml;./my-cluster/my-app-override-values.yaml
```

**Describe the bug**
Looks like 'argocd.argoproj.io/manifest-generate-paths' does not work when I am using multiple sources, because I am getting a warning and application does not get updated.

**To Reproduce**
- Create some secrets in hashicorp vault.
- Integrate ArgoCD with Hashicorp vault using argocd-vault-plugin-helm as described in your documentation.
- Create a helm chart that use secrets in vault.
- Create an external git repo to store values files for the application.
- Configure your annotation to something similar to `argocd.argoproj.io/manifest-generate-paths: ./common-config.yaml;./my-cluster/my-app-override-values.yaml`
- Configure webhook in your git repo to notify argo when you push to HEAD
- Push changes to your external git repo

**Expected behavior**
The applications that uses argocd-vault-plugin-helm, external git repos and  'argocd.argoproj.io/manifest-generate-paths'  annotation should refresh when a change is happening in one specific file or files inside the external git repo.

**Version**

I am using argo v2.10.5+335875d

**Logs**

```
time="2024-05-16T11:44:36Z" level=warning msg="Failed to store cached manifests of previous revision for app my-app: cache: key is missing"
```

**Comment by blakepettersson** [comment]
I think the issue you're having is with `argocd-vault-plugin`, not with `manifest-generate-paths`. From taking a quick glance, I cannot see that there's any reason why multi-sources wouldn't work with `manifest-generate-paths`. IIRC `argocd-vault-plugin` doesn't support multi-sources at all.

**Comment by jorgelon** [comment]
i get  several "Failed to store cached manifests of previous revision for app XXXX cache: key is missing" errors too.
In my case I use 2 manifest-generate-paths and only  1 application source.

`argocd.argoproj.io/manifest-generate-paths: apps/system/kustomize/folder/folder/;apps/system/folder/folder/folder/../../releases/`

i will check if the ../../ is the reason

**Comment by jorgelon** [comment]
nah, the cause is not the ../../ thing. I disable manifest-generate-paths for now

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?

**Comment by knechtionscoding** [comment]
I can confirm that multi source and manifest generate path work together

**Comment by todaywasawesome** [comment]
Closing as this seems to be an issue with the vault plugin rather than with manifest generate paths or multi source apps.

**Comment by pkazi** [comment]
How to use annotation in case when i want my ArgoCD app to refresh only when there are files changed in the Values path `values/abc-argo-cd/values-staging.yaml`

Currently it refreshes on every push on repo abcd/abc-k8s-configs.
```
project: argocd
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  syncOptions:
    - CreateNamespace=true
sources:
  - repoURL: 1234567890.dkr.ecr.us-east-1.amazonaws.com
    targetRevision: 1.4.0
    helm:
      valueFiles:
        - values.yaml
        - $values/values/abc-argo-cd/values-staging.yaml
      releaseName: argocd
    chart: abc-argo-cd
  - repoURL: https://github.com/abcd/abc-k8s-configs
    targetRevision: main
    ref: values
```
