### ISSUE TITLE
The order of sources (git/helm) in multi-source application matters in case of app diff & manifests features

### ISSUE THREAD

**Issue by filip-kolodziej-synerise** [argoproj/argo-cd#18359]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using multi-source applications where Helm values are fetched from git repository and the Helm chart from another OCI repository.

The application manifest has following structure.

```yaml
project: default
destination:
  server: >-
    https://mock:443
  namespace: default
sources:
  - repoURL: 'https://helm-repository/helm-charts'
    targetRevision: 1.0.0
    helm:
      valueFiles:
        - $values/git/values1.yaml
        - $values/git/values2.yaml
        - $values/git/values3.yaml
    chart: test-chart
  - repoURL: 'https://git-repository/mock.git'
    targetRevision: master
    ref: values
```

When it came to testing new `argocd manifests/diff` feature for multi-source apps, it gave me a headache. Both functionalities were not able to compile k8s manifests successfully:
- `argocd app manifests test-app --revisions 1.0.0 --source-positions 1 --revisions master --source-positions 2 --grpc-web` - produced no output (with exit code 0)
- `argocd app diff test-app --revisions 1.0.0 --source-positions 1 --revisions master --source-positions 2 --grpc-web` - as no manifests have been compiled, the output displayed all manifests present on the K8s cluster

**To Reproduce**

When I changed the order of sources in application manifest from:

```yaml
project: default
destination:
  server: >-
    https://mock:443
  namespace: default
sources:
  - repoURL: 'https://helm-repository/helm-charts'
    targetRevision: 1.0.0
    helm:
      valueFiles:
        - $values/git/values1.yaml
        - $values/git/values2.yaml
        - $values/git/values3.yaml
    chart: test-chart
  - repoURL: 'https://git-repository/mock.git'
    targetRevision: master
    ref: values
```

to:

```yaml
project: default
destination:
  server: >-
    https://mock:443
  namespace: default
sources:
  - repoURL: 'https://git-repository/mock.git'
    targetRevision: master
    ref: values
  - repoURL: 'https://helm-repository/helm-charts'
    targetRevision: 1.0.0
    helm:
      valueFiles:
        - $values/git/values1.yaml
        - $values/git/values2.yaml
        - $values/git/values3.yaml
    chart: test-chart
```

the features work as expected. I can only assume that the manifests could not be compiled because the values from Git were not present in the cache in the first case.

**Expected behavior**

Source order in application manifests should not matter, or there should be a mention of this in the documentation.

**Version**

```shell
argocd: v2.11.1+9f40df0
  BuildDate: 2024-05-21T14:47:51Z
  GitCommit: 9f40df0c29eca7e45a73f802f033dfd1ed0068e3
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.1+9f40df0
```

**Logs**

When executing `argocd app manifests/diff` with wrong sources order neither output nor pods' logs did not provide useful information.
