### ISSUE TITLE
Unable to override json value when using multiple sources to build argocd application

### ISSUE THREAD

**Issue by ghataSaxena** [argoproj/argo-cd#18379]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have packaged helm chart and pushed to our internal org repository. I am using that helm chart as base for deploying it in different environment overriding the values.yaml using multiple sources in argocd application.yaml but it is merging the json value for key specified in the packaged chart+ the overriding values.yaml instead of overriding it completely.

**To Reproduce**

Create helm chart with configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  asset-hierarchy.conf: |
    {
      
      "baseHierarchyAsset" : {{ .Values.baseHierarchyAsset | toJson }},
      "pinApp": "xyz"
    }
```
    
values.yaml

 `baseHierarchyAsset: {"name" : "Corp", id: "test", "show": true, "isIAPM": false}`
 
 Package the helm chart and use it to deploy app of apps with following config:

application.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: apm-rel-abc
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/replicas
  destination:
    name: ''
    namespace: app-apm-rel
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  - repoURL: 'https://github.com/bh-iam-helm-charts.git'
    targetRevision: helm-release-umbrella-chart
    ref: values
  - chart: abc
    repoURL: ghcr.io/git_repo_hosting_helm_charts
    targetRevision: 24.2.436 
    helm:
      valueFiles:
      - $values/charts/abc/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

values.yaml
` baseHierarchyAsset: {"show": false, "isIAPM": false}`

**Expected behavior**

Deployed configmap should have the overridden value:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  asset-hierarchy.conf: |
    {
      
      "baseHierarchyAsset" : {"show": false, "isIAPM": false},
      "pinApp": "xyz"
    }
```

**Real Output**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  asset-hierarchy.conf: |
    {
      
      "baseHierarchyAsset" : {"name" : "Corp", id: "test", "show": false, "isIAPM": false},
      "pinApp": "xyz"
    }
```
I don't want the extra parameters name and id it is picking up from values.yaml of the packaged helm chart.

**Argo CD Version**

```shell
v2.10.7+b060053
```
