### ISSUE TITLE
ArgoCD webhook refresh causes apps to go into Unknown state

### ISSUE THREAD

**Issue by LarryGF** [argoproj/argo-cd#18404]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When you have an app-of-apps that gets refreshed by a push to the "app-of-apps repo", it refreshes successfully and updates the child apps. But sometimes when the change involves changing the targetRef the child app Sync Status goes into Unknown and there's an error saying that it can't find the Ref's SHA: `Failed to load target state: failed to compare revisions for source 1 of 1: rpc error: code = Internal desc = unable to resolve git revision`. It can get fixed by manually refreshing the child app but it doesn't happen automatically.
It's worth noting that in our scenario these updates to the Refs of the child apps happen automatically when a new version is released, so the tag definitely exists

**To Reproduce**

- Install Argo using the helm chart
- Create an app-of-apps where each child application is sourced  from external repositories
- Enable a webhook in Github for your app-of-apps repository and finish the configuration in the argocd-cm
- Make a push to the app-of-apps repo changing the Git Ref for one or more apps

**Expected behavior**

After the app-of-app refreshes, the child app should automatically refresh every time

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/26148349/59142de5-965a-4af2-a43a-4b6ec93792a9)

**Version**

```shell
argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
Not a log, but this is the manifest for an application where this error happened:

```
project: system
source:
  repoURL: {repo}
  path: ./
  targetRevision: v1.1.5
  helm:
    valueFiles:
      - values.yaml
    values: |
      global:
          applicationFolder: gemstash
          applicationName: gemstash-management
          applicationNamespace: system
destination:
  namespace: system
  name: in-cluster
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - Validate=false
    - ServerSideApply=false
    - Replace=false
    - CreateNamespace=true
```
