### ISSUE TITLE
Make the health check for APIService a built in 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1841]
**Is your feature request related to a problem? Please describe.**

We should make the health check for APIService a built in (native golang) one so everyone will benefit from this.

**Describe the solution you'd like**

See 

* #1826
* https://github.com/cybozu-go/neco-apps/blob/4e87a73010a4e7fa7c92ab7c6317c4d329b7d819/argocd/base/configmap.yaml#L56-L77.
* https://github.com/argoproj/argo-cd/pull/1699

**Comment by alexec** [comment]
@ishii-masayuki/@jessesun - FYI - it'd be great to get community contributions for this one.

**Comment by alexmt** [comment]
There is also a failed condition (https://github.com/argoproj/argo-cd/issues/1017#issue-399259602):

```
status:
  conditions:
  - lastTransitionTime: "2018-12-23T20:56:17Z"
    message: 'no response from https://100.68.217.200:443: Get https://100.68.217.200:443:
      dial tcp 100.68.217.200:443: getsockopt: connection refused'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```
