### ISSUE TITLE
Cannot template first child of matrix generator inside first child of mergegenerator

### ISSUE THREAD

**Issue by wanddynosios** [argoproj/argo-cd#18430]
Checklist:

* [tx] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by steve-todorov** [comment]
We are experiencing a similar problem with the `git` generator. In our case we want to be able to load additional properties stored in a separate repository. Here's an example:

```yaml
        generators:
          - matrix:
              generators:
                - scmProvider:
                    cloneProtocol: ssh
                    github:
                      organization: xyz
                      allBranches: true
                      tokenRef:
                        secretName: github-token
                        key: token
                    filters:
                      - repositoryMatch: ^.*$
                        branchMatch: ^scm/([0-9]+).*$
                        pathsExist: [deployment/kubernetes/kustomization.yaml]

                - plugin:
                    configMapRef:
                      name: applicationset-branch-generator-plugin
                    input:
                      parameters:
                        branch: "{{.branch}}"
                    requeueAfterSeconds: 15

          - git:
              repoURL: "git@github.com:{{.organization}}/{{.repository}}.git"
              revision: "{{.branch}}"
              files:
                - path: "deployment/kubernetes/properties/{{.case_number}}.yml"

```

We've also tried various combinations:

1. `merge` generator = `[ scmProvider, matrix = [plugin, git] ]`
2. `matrix` generator = `[ scmProvider, git]` (just to be sure the custom plugin generator we have isn't the problem)
3. `matrix` generator = `[ scmProvider, merge = [plugin, git]  ]`

None of these combos work and it's a big blocker. Any ideas on how to fix this?
