### ISSUE TITLE
UI - Add Link From Application to its Parent ApplicationSet  

### ISSUE THREAD

**Issue by neevnuv** [argoproj/argo-cd#18446]
# Summary

In the UI of the application add a link to go from the Application to the Applicationset that deployed it. 

# Motivation

We have a large amount of Applicationsets deployed on our environment, espesialy on our dev and prep environments. 
When navigating between Applications in the ArgoCD UI, you cannot know which Applicationset deployed which Application, unless you go into the correct Applicationset and check the Applications it owns.

# Proposal

How do you think this should be implemented?

Inside the Application's screen, you will have link that will allow you to go to the parent ApplicationSet that deployed it. It can be done by checking the managedFields of the Application resource or by adding a new lable, next to the manageBY=Appset.

**Comment by christianh814** [comment]
This probably belongs in the https://github.com/argoproj/argo-helm repo cc @jmeridth

**Comment by jmeridth** [comment]
@christianh814 is this existing functionality and we'd need to expose in argo-cd helm chart's values.yaml?  Asking our argo-cd helm chart folks while asking here.

**Comment by christianh814** [comment]
@jmeridth I had my tabs confused and this is actually for another issue. Sorry about the noise!  Will tag you there

**Comment by agaudreault** [comment]
@neevnuv I think this can be configured already with https://argo-cd.readthedocs.io/en/latest/operator-manual/deep_links/. You should have access to the `metadata.ownerReferences` field. Can you try building one and if it is successful, we could add it in the documentation examples?

**Comment by neevnuv** [comment]
Hi, thank you for the suggestions, it was the thing we looked for. 
In our environment we have applications that deploys an applicationset that deploys other applications. This way we deploy all our applications from a single application. 

When trying add a link to an application to the applicationset that created it, we could not link it properly because the name of the ApplicationSet inside the `metadata.ownerReferences` is different then the application that deploys it.

we could only get this far:
```
application.links:
  - url: https://<argo-route>/applications/{{ (index .app.metadata.ownerReferences 0).name }}
    title: Parent ApplicationSet
    if: application.metadata.ownerReferences != nil
```

**Comment by agaudreault** [comment]
@neevnuv Can you share the content of the `.metadata.ownerReferences` and the expected url ? Go template has a couple of [functions](https://masterminds.github.io/sprig/) available that should allow you to parse the data to get the correct value.

**Comment by neevnuv** [comment]
@agaudreault my `.metadata.ownerReferences` looks like this:
```
ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ApplicationSet
    name: my-application-set
    uid: <long-uid>
```

The issue with this OwnerReferences is that you cannot assume the appliction the appset is deployed from.
I think an option here is to create a link based on an annotation on the Appset/Application.
