### ISSUE TITLE
Define resource kind in syncWindow

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-cd#18497]
# Summary

Define which resource kind (deployment, config map, ...) is affected by the sync window.

# Motivation

We have got several apps which should be updated only during certain time frames. That's where we use the sync windows for. But some of the apps support e.g. hot reloading for config maps. So it would be nice to define which resource kind is affected by the sync window. This way the deployment could be updated (and therefor restarted) during night and the config map can still be updated and auto synced during the day.

# Proposal

Extend `syncWindow` with `resource`.

```
...
  syncWindows:
  - kind: allow
    schedule: '0 3 * * *'
    duration: 1h
    applications:
    - '*nightly-sync*'
    resource:
    - deployment
    manualSync: true
```
