### ISSUE TITLE
argocd-secret is synced every 24 hour ignoring ignoreDifferences setting

### ISSUE THREAD

**Issue by ktzsolt** [argoproj/argo-cd#18530]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have created an `Application` for Argo CD to manage itself.
I disabled default admin and enabled oidc sso.
I also added this `ignoreDifferences` section to the argocd `Application` to ignore the password and other automatic changes in argocd-secret:

```yaml
  ignoreDifferences:
  - kind: Secret
    name: argocd-secret
    namespace: argocd
    jsonPointers:
      - /spec/data
      - /metadata/annotations
      - /metadata/selfLink
      - /metadata/uid
      - /metadata/resourceVersion 
```

This successfully ignores the updates meaning Argo CD will not try to sync back the values however I get a sync notification every 24 hour that this argocd-secret resource is synced when really it is not synced.

![kép](https://github.com/argoproj/argo-cd/assets/57558440/bac4c30b-55f0-48df-b790-b2a24a0dafdf)

Also when I modify the secret in the cluster with `kubectl edit argocd-secret` and I click on the `hard refresh` on Argo CD UI the sync will also trigger. Somewhere I read that hard refresh happens every 24 hours too maybe that is the culprit:
![kép](https://github.com/argoproj/argo-cd/assets/57558440/d2ab7e06-0181-4bbc-afb7-34f798d08e17)

**UPDATE:**  the argocd-secret sync (that does not sync anything) happens when I click `hard refresh` regardless if I modified the secret by hand in the cluster or not, so most probably the automatic `hard refresh` that happens every 24 hours is causing this.

This is annoying because every 24 hour we also get a notification on teams about this sync that did nothing, that is just noise.

**Expected behavior**

when a resource or part of a resource is updated and it is specified in `ignoreDiffrences` it should not report that it was synced not even in case of a manual or 24h automatic `hard refresh`

**Version**

```shell
v2.11.2+25f7504
```

**Comment by agaudreault** [comment]
@ktzsolt, do you have your application configured with https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs ?

**Comment by ktzsolt** [comment]
@agaudreault yes, it is set. 

Please note that everything works as expected, only in case of manual or the automated 24H `hard refresh` triggers a sync on this secret object but nothing is effectively synced and modified that is set in the `ignoreDifferences` as it is expected.

You can reproduce this with setting up ignoreDifferences for a resource, modify it manually in the cluster and click refresh and/or sync and you will see that there will be no sync triggered and your manual changes will be preserved. However if you click `hard refresh` a sync will trigger but your manual changes will still be preserved.

**Comment by Kifok** [comment]
Hello, i have the same issue with ignoreDifferences for secret

**Comment by ktzsolt** [comment]
@Kifok what is your argocd version? Looks like for me one of the updates solved this problem, I am on v2.14.1

**Comment by Kifok** [comment]
@ktzsolt I have autoupdate so now it's 2.14.5, but last time I had this issue on 2.14.4

**Comment by ktzsolt** [comment]
@Kifok 
I checked the `Application` spec for argocd and I modified the `ignoreDifferences` from the one In the original post to this in december. Instead of /spec/data I set up /data. Makes sense because K8s secrets doesn't have `spec.data` field but `data` field.
```
  ignoreDifferences:
  - kind: Secret
    name: argocd-secret
    namespace: argocd
    jsonPointers:
      - /data
      - /metadata/annotations
      - /metadata/selfLink
      - /metadata/uid
      - /metadata/resourceVersion
```

Could you try out like this? If this helps for you too then it was a user error from our part from the beginning and we can close this.
