### ISSUE TITLE
Provide way for sidecar plugin to persist git repository for debugging purposes

### ISSUE THREAD

**Issue by paololazzari** [argoproj/argo-cd#18547]
# Summary

Add option to persist git repository on filesystem on sidecar plugin execution. 

# Motivation

I am seeing diffs for a bunch of secrets in the argo UI, which I do not see locally when running kustomize locally and then diffing against the cluster. To debug this, it would be helpful if I could run the same commands the plugin is running in the plugin container itself. 

Currently this is awkward to do because the plugin does not persist the git repository in `/tmp/_cmp_server`. I've been able to `cp` the repository during the plugin execution from `/tmp/_cmp_server` during the execution but this is not ideal.

# Proposal

Add option to plugin configuration, e.g.:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: pluginName
spec:
  init:
    command: ["sample command"]
    args: ["sample args"]
  generate:
    command: ["sample command"]
    args: ["sample args"]
  preserveRepository: true
```
