### ISSUE TITLE
resource customization  still out of sync

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1857]
**Describe the bug**

When using this resource customization the image still is out of sync

```
  resource.customizations: |
    apps.openshift.io/DeploymentConfig:
      ignoreDifferences: |
        jsonPointers:
        - /spec/template/spec/containers/image



```

![image](https://user-images.githubusercontent.com/9946020/60515448-e8dbca80-9cdb-11e9-9708-3f38744cb5e4.png)

Is perhaps the documentation I found not sufficient enough?

**Comment by peterbosalliandercom** [comment]
Ah containers is an array so this is correct:

````
apps.openshift.io/DeploymentConfig:
  ignoreDifferences: |
    jsonPointers:
    - /spec/template/spec/containers/0/image
````
