### ISSUE TITLE
Multi-source: Helm values from values file specified by `ref` field are not resolved

### ISSUE THREAD

**Issue by keithchong** [argoproj/argo-cd#18580]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
This issue is related to the ref field in the enhancement to support multiple sources in applications.  When the `ref` field is specified for a values file, the values are not resolved and not correctly returned by the appdetails API ((/api/v1/repositories/{source.repoURL}/appdetails).  However, if no `ref` is specified, and the values file is in the default location in the repo, the API correctly returns the values, even if the application is a multi-source app.  For a single source app, the values are correctly returned as well.  So this only affects ref-referenced values files, which is an important part and reason for providing the multiple-source support.

**To Reproduce**

Create the following app:
```
project: default
destination:
  server: https://kubernetes.default.svc
  namespace: default
sources:
  - repoURL: https://github.com/ishitasequeira/argocd-example-apps.git
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - $values_test/values.yaml
  - repoURL: https://github.com/ishitasequeira/values-test.git
    targetRevision: HEAD
    ref: values_test
```
Go to the Details page and view the Sources tab and look at the values for the first source
The values under the Parameters section do not match the values provided by the values file

The UI is calling the appdetails endpoint of the repos. service, and it's not returning the correct values.

**Expected behavior**

The UI should be showing the correct values

**Version**
Latest version (latest from repo)

**Logs**
N/A
