### ISSUE TITLE
"&" string in valuesObject mess up PARAMETERS tab on argocd's web ui

### ISSUE THREAD

**Issue by nattawitr** [argoproj/argo-cd#18632]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating an application through a yaml files with helm and valuesObject. If we include a string that contain `&`, The parameters tab in applicaiton detail on argocd's ui became directory type instead.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.9.0
    helm:
      releaseName: test
      valuesObject:
        test: "test&"
  destination:
    name: in-cluster
    namespace: default
```

**Expected behavior**

Parameters tab show helm configuration that allow us to change values and parameters.

**Screenshots**

<img width="1174" alt="image" src="https://github.com/argoproj/argo-cd/assets/168150489/d075b30f-892c-4e19-b8d3-bdc773e1bcff">
<img width="1184" alt="image" src="https://github.com/argoproj/argo-cd/assets/168150489/07631c38-c77c-45d0-bf38-53b7e90e0b95">

**Version**

```shell
argocd: v2.7.4+a33baa3.dirty
  BuildDate: 2023-06-05T22:48:59Z
  GitCommit: a33baa301fe61b899dc8bbad9e554efbc77e0991
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.0+d3f33c0
```

**Logs**

```
Paste any relevant application logs here.
```
