### ISSUE TITLE
Helm dependency conditions/tags are not respected with multisource

### ISSUE THREAD

**Issue by ep4sh** [argoproj/argo-cd#18667]
Checklist: 

* [ ✅ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ✅] I've included steps to reproduce the bug.
* [ ✅] I've pasted the output of `argocd version`.

**Describe the bug**
Helm dependency conditions/tags are not respected with multiple Sources for an Application

**To Reproduce**

1. Checkout dependencies disable: https://github.com/ep4sh/bla-values/blob/main/values.yaml

2. create app and deploy
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ep4sh-bla
  namespace: argocd
spec:
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: 15.7.1
      helm:
        valueFiles:
        - $values/values.yaml
    - repoURL: 'https://github.com/ep4sh/bla-values.git'
      targetRevision: HEAD
      ref: values
  project: system
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m


```

**Expected behavior**
Since `kube-state-metrics` / `prometheus-node-exporter` and others are disabled, no one of them should NOT be deployed.

**Screenshots**
![image](https://github.com/argoproj/argo-cd/assets/19505042/13335ce8-60b0-4b51-81d1-c2d7393bfb09)

**Version**

```shell
version v2.11.3+3f344d5
build date 2024-06-06T08:42:00Z
helm v3.14.4+g81c902a
```
