### ISSUE TITLE
[docs] define clusterRole for appset-controller (watching many namespaces)

### ISSUE THREAD

**Issue by TheRealNoob** [argoproj/argo-cd#18693]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.

**Describe the bug**

[This section](https://argo-cd.readthedocs.io/en/latest/operator-manual/app-any-namespace/#adapt-kubernetes-rbac) of the `app-in-any-namespace` documentation details the [additional RBAC manifests](https://github.com/argoproj/argo-cd/tree/master/examples/k8s-rbac/argocd-server-applications) that must manually be made when configuring argo to deploy apps from many namespaces.  These are super helpful and I was very appreciative to have them.

When I went to configure the same behavior for appplicationSets I found that there wasn't equivilant docs on the permissions required for that serviceAccount.  From my small tinkering so far (before giving up and doing allow all on argoproj.io resources) I found it that it requires the below permissions.  It would be really helpful to get a concrete list of the required permissions from the people more informed than I.  I'd be happy to open all the relevant PRs if so.  Thank you!

```yaml
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - "applications"
      - "applicationsets"
    verbs:
      - create
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
```
