### ISSUE TITLE
After upgrading from `2.10.12` to `2.11` all applications sourced from github stopped working due to `failed to get git client for repo https://github.com/cxxx.git`

### ISSUE THREAD

**Issue by grzesuav** [argoproj/argo-cd#18759]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have set of applications using private github repository, like 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set
  namespace: argocd
...
spec:
  project: compute
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.9.2
      helm:
        valueFiles:
          - $values/provisioning/actions-runner-controller/helm/gha-runner-scale-set/values.yaml
    - repoURL: https://github.com/internal.git
      targetRevision: master
      ref: values
```

or 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-companion-azure
  namespace: argocd
...
spec:
  project: compute
  source:
    repoURL: https://github.com/internal.git
    targetRevision: master
    path: provisioning/cluster-api-companion-azure/helm/cluster-api-companion-azure/
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
```

which worked fine with `2.9` and `2.10`.

Immediately after updating to `2.11` (I tried `2.11.0` and `2.11.3`) all the apps have `Unknown` sync status in ui with error 
```
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = failed to get git client for repo https://github.com/internal.git
```

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = EOF
```

In logs of `argocd-repo-server` I see a lot of entries like 
```json
{"level":"error","msg":"Failed to get git client for repo https://github.com/xxx.git: EOF","time":"2024-06-21T10:49:12Z"}
{"error":"failed to get git client for repo https://github.com/xxx.git","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2024-06-21T10:44:58Z","grpc.time_ms":253691.66,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2024-06-21T10:49:12Z"}
```

After rolling back to `2.10` it start to work again.

In all versions in `Settings/repositories` -  `Connection status: successful` in UI

**To Reproduce**

Unsure if it is reproducible on some other repo, in my case it just update to `2.11` and see the issue.

**Expected behavior**

All apps are synced correctly, no issues when accessing github

**Screenshots**

<img width="2181" alt="image" src="https://github.com/argoproj/argo-cd/assets/9568421/2739c45f-1afc-46d5-b85c-8bc024e0258c">

<img width="1951" alt="image" src="https://github.com/argoproj/argo-cd/assets/9568421/a6870503-beac-4d89-ad89-fc6a8e8cc946">

**Version**
`v2.11.0` and `v2.11.3`
```shell
argocd@argocd-application-controller-0:~$ argocd version
argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
```json
{"level":"error","msg":"Failed to get git client for repo https://github.com/xxx.git: EOF","time":"2024-06-21T10:49:12Z"}
{"error":"failed to get git client for repo https://github.com/xxx.git","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2024-06-21T10:44:58Z","grpc.time_ms":253691.66,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2024-06-21T10:49:12Z"}
```

**Comment by jonggulee** [comment]
Hello, I am currently using ArgoCD version 2.12.0 and I've encountered the same issue as reported in #18759. 
Is this issue still being addressed? I am experiencing the same problem and would appreciate any updates.

**Comment by axinorm** [comment]
Hi,

I ran into the same problem as you after upgrading. I checked the logs of the ``argocd-repo-server`` and I saw, for a specific AppProject, Argo CD was not able to pull the source code.

After a quick check of my repository credentials, it was only configured for a specific AppProject, so I have to duplicate the authentication method and select the AppProject involved.

To conclude, I think secrets like repository credentials are now binded to a specific project, I mean AppProject are no longer global.

```sh
kubectl -n argocd get secrets | grep repo

kubectl -n argocd get secrets repo-[repo_id] -o yaml
```

```yaml
apiVersion: v1
data:
  name: ***
  password: ***
  project: ***
  type: ***
  url: ***
  username: ***
```

As you can see, inside the secret, you have a ``project`` field, which is your AppProject name, duplicate it for another project to grant repository access.

Have a nice day!
