### ISSUE TITLE
not able to connect with public github repo 

### ISSUE THREAD

**Issue by shreyanshZevo** [argoproj/argo-cd#18769]
Unable to create application: application spec for dev-appsetting is invalid: InvalidSpecError: repository not accessible: repositories not accessible: &Repository{Repo: "https://github.com/jaiswaladi246/Repo-2.git", Type: "", Name: "", Project: ""}: repo client error while testing repository: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup argocd-repo-server: i/o timeout"

Reproduce the Bug
GO to the Argocd UI 
Create a application and give the public repo in github url 
and then create application 
then you will get this message afet 10 - 15 second of loading .

**Comment by thecooldrop** [comment]
Does your cluster have access to public internet? Could you give more details about your cluster setup?

**Comment by shreyanshrathore** [comment]
Yes, my cluster have access to internet.

**Comment by shreyanshZevo** [comment]
Hey, you can close this issue, I have some other network config, which prevented me from connecting to the internet.

**Comment by hasirciogli** [comment]
What error man. im in same situation

**Comment by shreyanshZevo** [comment]
Tell me more about it

**Comment by tbernacchi** [comment]
[UPDATE] - In my case (I'm using `v2.14.10+5feb8c2`version) I had the same issue...but it was because a network policy was missing, by default ARGO created these:

```
k get netpol -n argocd
NAME                                              POD-SELECTOR                                              AGE
allow-foobar-to-repo-server                       app.kubernetes.io/name=argocd-repo-server                 39m
argocd-application-controller-network-policy      app.kubernetes.io/name=argocd-application-controller      62d
argocd-applicationset-controller-network-policy   app.kubernetes.io/name=argocd-applicationset-controller   62d
argocd-dex-server-network-policy                  app.kubernetes.io/name=argocd-dex-server                  62d
argocd-notifications-controller-network-policy    app.kubernetes.io/name=argocd-notifications-controller    62d
argocd-redis-network-policy                       app.kubernetes.io/name=argocd-redis                       62d
argocd-repo-server-network-policy                 app.kubernetes.io/name=argocd-repo-server                 62d
argocd-server-network-policy                      app.kubernetes.io/name=argocd-server                      62d
```

So I've created this policy to alllow `foobar` namespace reach argocd-repo-server:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-foobar-to-repo-server
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: foobar
  policyTypes:
  - Ingress
```
After that all good =)
