### ISSUE TITLE
Error syncing `Job` due to `spec.podReplacementPolicy: field not declared in schema`

### ISSUE THREAD

**Issue by ptr1120** [argoproj/argo-cd#18778]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Having an argocd application that contains a `Job` (`batch/v1`) breaks syncing the application with the error message:

```
Failed to compare desired state to live state: failed to calculate diff:
        error calculating structured merge diff: error building typed value from  live resource: errors:
          .spec.podReplacementPolicy: field not declared in schema
          .status.terminating: field not declared in schema
      type: ComparisonError
```

**To Reproduce**

It is easily reproducible using k8s version `1.29.4` .
I have tested it with argocd versions  `v2.11.3`  and `v2.12.0-rc1`. 
Interestingly using k8s 1.30.0 (`kindest/node:v1.30.0`) the error does not happen.

1. Install argocd using kustomize
```
kubectl create namespace argocd	  
kustomize build github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.12.0-rc1 | kubectl apply --server-side --namespace "argocd" -f -
```

2. Add the following application definition  (which contains a `Job`) to argocd:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-test
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: pre-post-sync/
    targetRevision: master
    kustomize:
      namespace: job-test
      patches:
        - patch: |
            - path: /metadata/annotations
              op: remove
          target:
            kind: Job
  destination:
    name: in-cluster
    namespace: job-test
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
```

**Expected behavior**

I can manage applications with argocd that contain a `Job`.

**Version**

```shell
argocd: v2.11.3+3f344d5
BuildDate: 2024-06-06T09:27:36Z
GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
GitTreeState: clean
GoVersion: go1.21.10
Compiler: gc
```

**Logs**

```
Failed to compare desired state to live state: failed to calculate diff:
        error calculating structured merge diff: error building typed value from
        live resource: errors:
          .spec.podReplacementPolicy: field not declared in schema
          .status.terminating: field not declared in schema
      type: ComparisonError
```

**Investigations**

I already tried different combinations of 

* ignoreDifferences definitions to exclude the fields
* enable/disable server-side-diff
* enable/disable server-side-apply

but nothing helped.
Only installing k8s version 1.30.0 helped.

Any idea how to overcome this situation, so getting the application with a `Job` synced successfully?
