### ISSUE TITLE
Add hash validation support for the clusterResourceWhitelist

### ISSUE THREAD

**Issue by saltbo** [argoproj/argo-cd#18821]
# Summary
Add hash validation support for the clusterResourceWhitelist

# Motivation

As a platform manager, we hope that all cluster-level resources deployed to a cluster will be reviewed by the platform. We found that argocd provides clusterResourceWhitelist for basic verification. But we want to support checkings based on names #12208 and hashes.

# Proposal

```yaml
clusterResourceWhitelist:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinitions
    resourceNames:
      - crd1.example.com
      - crd2.example.com
    resourceHashes:
      - 0a4d55a8d778e5022fab701977c5d840bbc486d0
      - cd1144e1b687f6d586c215f09ddd1a67a8f1c0f3
```
