### ISSUE TITLE
Some resources' live manifests can't be viewed in the UI since repo server cluster role lacks list permission

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#18853]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Some resources' live manifests would show that resource not found, despite it's there in the cluster. For example
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
```
I've validated that adding list permission to the repo server via
```
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - get
  - list
  - patch
```
works, whereas existing one looks like
```
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - get
  - patch
```
So apparently get is not enough.

**To Reproduce**

Create resources
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
```
and try to view their live manifest in the UI

**Expected behavior**

Live manifest is viewable in the UI

**Screenshots**

![Screenshot 2024-06-29 at 8 59 23 AM](https://github.com/argoproj/argo-cd/assets/137232734/b0eef007-804d-4fb5-b4d7-2e28280d909d)
After the update
![Screenshot 2024-06-29 at 8 59 37 AM](https://github.com/argoproj/argo-cd/assets/137232734/acabcfbf-b0df-40e8-b837-a456aa41c663)

**Version**

A custom build from master + https://github.com/argoproj/argo-cd/pull/18694 around the time of v2.12.0-rc1 release.

**Logs**
