### ISSUE TITLE
Error: topologySpreadConstraints[...].nodeTaintsPolicy: field not declared in schema when ignoring differences

### ISSUE THREAD

**Issue by snuggie12** [argoproj/argo-cd#18879]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Similar to #15176, when refreshing an app which contains a `Deployment` with `nodeTaintsPolicy` set and when setting 
```
resource.customizations.ignoreDifferences.apps_Deployment: |
    managedFieldsManagers:
    - foo
```

or the `all` variant we get an error:
```
Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: .spec.template.spec.topologySpreadConstraints[topologyKey="kubernetes.io/hostname",whenUnsatisfiable="DoNotSchedule"].nodeTaintsPolicy: field not declared in schema
```

**To Reproduce**

In the `argocd-cm` add the following field:
```
data:
  resource.customizations.ignoreDifferences.apps_Deployment: |
    managedFieldsManagers:
    - istio-pilot # This was for scaleops and I presume any manager can go here
```
Then create a `Deployment` which contains:
```
spec:
  template:
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              foo: bar
          maxSkew: 2
          nodeTaintsPolicy: Honor # field that breaks things
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
```

**Expected behavior**

App can be refreshed/synced

**Screenshots**

**Version**

```shell
argocd-server: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**
