### ISSUE TITLE
Interpolation does not work in git generator

### ISSUE THREAD

**Issue by steve-todorov** [argoproj/argo-cd#18877]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We are using a `matrix` generator together with a `merge` generator and a `git file` generator.
The interpolation inside the `repoURL` and `revision` parameters of the `git file` generator are not wodking. 
When you try to reference the `{{.branch}}` parameter you will get the literal `{{.branch}}` instead of the actual value.

I went back to v2.4.0 where this was introduced and it looks like the `interpolation` is supposed to work only for `values` which seems to be very odd?

https://github.com/argoproj/argo-cd/compare/v2.3.0...v2.4.0#diff-e18bda08876f1471ded096f197d58778d250cd942ca66539391b067d5f069f79

Here's the slack thread where I discussed this with @crenshaw-dev:
https://cloud-native.slack.com/archives/C01TSERG0KZ/p1719585649594259

**To Reproduce**

```yaml
  - matrix:
      generators:
        - scmProvider:
            cloneProtocol: ssh
            github:
              organization: my-organization
              allBranches: true
              tokenRef:
                secretName: github-token
                key: token
            filters:
              - repositoryMatch: ^my-repository$
                branchMatch: ^feature-.*$
                pathsExist: [deployment/kubernetes/kustomization.yaml]
        - git:
            # None of the SCM variables work here.
            repoURL: "https://github.com/{{.organization}}/{{.repository}}"
            revision: "{{.branch}}"
            files:
              - path: "deployment/kubernetes/overrides.yaml"

```

**Expected behavior**

Interpolation should work in the `git file` generator parameters.

**Version**

```shell
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T09:27:36Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0

```

**Logs**

Different variations of this error (depending on the version I tried)
```
ERRO[0048] error generating params                       error="Error during fetching repo: `git fetch origin {{.branch}} --tags --force --prune` failed exit status 128: fatal: couldn't find remote ref {{.branch}}" generator="&{0xc00186e270}" 
INFO[0208] Trace                                         args="[git fetch origin {{.branch}} --tags --force]" dir=/tmp/git@github.com_xyz_repo operation_name="exec git" time_ms=1366.6199119999999
```

**Comment by steve-todorov** [comment]
@christianh814 yes I have it:

```
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
```

**Comment by christianh814** [comment]
@steve-todorov It shouldn't "matter" but have you tried using `''` instead? Like `'{{.branch}}'` and `'https://github.com/{{.organization}}/{{.repository}}'`

**Comment by cardoe** [comment]
Likely related to #22051. I believe you'll be able to do something like:

```yaml
    - git:
        repoURL: 'git@github.com:{{ "{{.organization}}" }}/{{ "{{.repository}}" }}.git'
        revision: '{{ "{{.branch}}" }}'
        files:
          - path: 'deployment/kubernetes/properties/{{ "{{.case_number}}" }}.yml'
```

This should be fixed with #22267
