### ISSUE TITLE
appset: Git generator do not tolerate templating in `spec.template.spec.project`

### ISSUE THREAD

**Issue by dacofr** [argoproj/argo-cd#18906]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I think that since #18545 we are not able to use templating in `project` attribute of application we are generating.
Git generator raise this `error getting project : AppProject.argoproj.io \"{{ path.basename }}\" not found` and applications are not generated (`path.basename` is coming from my test suite).

cf. [GenerateParams](https://github.com/argoproj/argo-cd/blob/b96be4c5e4b44d684182444bc403936ff8505470/applicationset/generators/git.go#L51)
```
	var project string
	if strings.Contains(appSet.Spec.Template.Spec.Project, "{{") {
		project = appSetGenerator.Git.Template.Spec.Project
	} else {
		project = appSet.Spec.Template.Spec.Project
	}

	appProject := &argoprojiov1alpha1.AppProject{}
	if err := client.Get(context.TODO(), types.NamespacedName{Name: appSet.Spec.Template.Spec.Project, Namespace: appSet.Namespace}, appProject); err != nil {
		return nil, fmt.Errorf("error getting project %s: %w", project, err)
	}
```
Even if we have a variable `project` we do not use it when we request k8s API.

**To Reproduce**

- Create an AppSet, example https://github.com/dacofr/hello-appset/blob/main/git-appset.yaml
- Watch logs

**Expected behavior**

No error, applications are generated, and we can use a template in project field.

**Version**

Running locally based on this commit : b96be4c5e4b44d684182444bc403936ff8505470

**Logs**

```
ERRO[2348] error generating application from params      applicationset=argocd/hello-git-appset error="error getting project : AppProject.argoproj.io \"{{ path.basename }}\" not found" generator="{nil nil &GitGenerator{RepoURL:https://github.com/dacofr/hello-appset.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:envs/**/config.json,},},Revision:main,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
ERRO[2358] error generating params                       error="error getting project : AppProject.argoproj.io \"{{ path.basename }}\" not found" generator="&{0xc00014ff00}"
```

**Comment by christianh814** [comment]
I wonder what's happening is that since the `config.json` file is empty, that it's erroring the whole thing out.

I agree, in this specific use case, I'd expect it to work (even with an empty `config.json` file).

Does it still not work if you add dummy data?

like in the `config.json` you put...

```json
{
    "argo": "iscool"
}
```

...and see if it still errors out?

**Comment by dacofr** [comment]
Yes, even with dummy values in config.json, we still have errors.

**Comment by TimLinsenmayer** [comment]
Observing the same issue. I operate two clusters, each with the same applications.
On version v2.11.2+25f7504, this behaviour is not observable while in version v2.12.0+f8e2ca7 it is. 

In my case, I use a Matrix Generator with a Git and List Generator.
```
spec:
  generators:
    - matrix:
        generators:
          - git:
              directories:
                - path: infrastructure/applications/*
              repoURL: (removed)
              revision: (removed)
          - list:
              elements:
                - server: https://kubernetes.default.svc
                  stage: dev
                - server: https://kubernetes.default.svc
                  stage: test
                - server: https://kubernetes.default.svc
                  stage: prod
  template:
    metadata:
      name: '{{stage}}-{{path.basename}}'
    spec:
      destination:
        namespace: '{{stage}}-managed'
        server: '{{server}}'
      project: '{{stage}}-stage'
      source:
        path: '{{path}}/env/{{stage}}'
        repoURL: (removed)
        targetRevision: (removed)
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
When setting project to dev-managed for example, it creates all applications correctly (even with the name as stage-servicename). Would highly appreciate a fix as we can't deploy our infra with the new version.
