### ISSUE TITLE
Unable to use sleep preStop hook

### ISSUE THREAD

**Issue by mogopz** [argoproj/argo-cd#18992]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to use the new sleep preStop hook ([link](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3960-pod-lifecycle-sleep-action/README.md)) but am getting a `field not declared in schema` error. After looking at the [FAQ](https://github.com/argoproj/argo-cd/blob/master/docs/faq.md?plain=1#L327-L346) the reason is that the Kubernetes library hasn't been updated to 1.30.

**To Reproduce**

Try to sync a deployment with the following preStop hook in a 1.30 cluster.

```yaml
lifecycle:
  preStop:
    sleep:
      seconds: 20
```

**Comment by christianh814** [comment]
@mogopz Just for testing (workaround), does annotating the resource with:

```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
```

Work at all?  https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#disable-kubectl-validation

**Comment by jlgeering** [comment]
That did not seem to help

**Comment by jlgeering** [comment]
this worked for us (we have no mutation webhook):

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  # and https://argo-cd.readthedocs.io/en/stable/user-guide/diff-strategies/
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
```
