### ISSUE TITLE
Helm OCI repo won't work if proxy is needed and insecure or cafile is specified

### ISSUE THREAD

**Issue by Wellyas** [argoproj/argo-cd#19019]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a OCI helm private repository with self-signed certificate behind a proxy, if you add `--insecure-skip-tls-verify` or `--ca-file` the proxy setting will not be use.

it is due to an issue in helm : https://github.com/helm/helm/issues/13116

**To Reproduce**

Add the proxy env variable to the server and repo server pod

when installing argocd with helm charts add this 

```yaml
server:
      envFrom:
        - configMapRef:
            name: proxy-conf
    repoServer:
      envFrom:
        - configMapRef:
            name: proxy-conf
extraObjects:
- apiVersion: v1
        kind: ConfigMap
        metadata:
          name: proxy-conf
        data:
          http_proxy: "http://proxy:3128"
          https_proxy: "http://proxy:3128"
          HTTP_PROXY: "http://proxy:3128"
          HTTPS_PROXY: "http://proxy:3128"
          no_proxy: .svc,.cluster.svc,svc.cluster.local,10.96.0.0/12,10.244.0.0/16,172.30.0.1,argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,argocd-dex-server
          NO_PROXY: .svc,.cluster.svc,svc.cluster.local,10.96.0.0/12,10.244.0.0/16,172.30.0.1,argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,argocd-dex-server
```

Then try the helm pull command in the repo server pod : 

Without TLS setting ( no certificate configure for the repository )
```shell
argocd@argocd-repo-server-75497f44bc-cfggw:~$ helm pull oci://ghcr.io/netbox-community/netbox-chart/netbox --version 5.0.0-beta.48 --destination /tmp/
Error: failed to do request: Head "https://ghcr.io/v2/netbox-community/netbox-chart/netbox/manifests/5.0.0-beta.48": Proxy Authentication Required
```

With TLS setting ( insecure add to the repository )
```shell
argocd@argocd-repo-server-75497f44bc-cfggw:~$ helm pull oci://ghcr.io/netbox-community/netbox-chart/netbox --version 5.0.0-beta.48 --destination /tmp/ --insecure-skip-tls-verify
Error: failed to do request: Head "https://ghcr.io/v2/netbox-community/netbox-chart/netbox/manifests/5.0.0-beta.48": dial tcp 140.82.121.33:443: connect: connection timed out
```

version helm : 
```shell
argocd@argocd-repo-server-75497f44bc-cfggw:~$ helm version
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}
```

**Expected behavior**

the chart can be pull when configuring insecure or a dedicated cert

**Screenshots**

**Version**

```shell
argocd: v2.11.4+e1284e1
  BuildDate: 2024-07-02T19:17:02Z
  GitCommit: e1284e19e03c9abab2ea55314b14b1e0381c4045
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

**FIX**
The issue seem to be fix in helm version 3.15.3
