### ISSUE TITLE
The redis-ha-server pods are blocked by the NetworkPolicy when attempting to make requests to the redis-ha-haproxy pods

### ISSUE THREAD

**Issue by KeerthiSap** [argoproj/argo-cd#19023]
**Describe the bug**

The redis-ha-server pods are attempting to make requests to the redis-ha-haproxy pods, but are blocked by the NetworkPolicy

**To Reproduce**

The issue arises when redis-ha-server pods try to connect to the redis-ha-haproxy pods.

**Expected behavior**

argocd-redis-ha-server should have an egress connection to argocd-redis-ha-haproxy
argocd-redis-ha-haproxy should have an ingress connection to argocd-redis-ha-server

**Version**

Argo CD v2.7.14

**Logs**

Please find the below GCP log which indicates the request is denied by the network policy: 

```
jsonPayload: {
connection: {
dest_ip: "172.xx.xx.xxx"
dest_port: 42330
direction: "ingress"
protocol: "tcp"
src_ip: "172.xx.xx.xxx"
src_port: 6379
}
count: 1
dest: {
namespace: "argocd"
pod_name: "argocd-redis-ha-haproxy-xxx"
pod_namespace: "argocd"
workload_kind: "Deployment"
workload_name: "argocd-redis-ha-haproxy"
}
disposition: "deny"
node_name: "gke-build-default-xxxxx"
src: {
namespace: "argocd"
pod_name: "argocd-redis-ha-server"
pod_namespace: "argocd"
}}
```

We can find that the argocd-redis-ha-server is NOT added in the latest release as well. The relevant network policy from https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.0-rc3/manifests/ha/install.yaml, does not include labels or ports to allow this connection:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-redis-ha-proxy-network-policy
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-repo-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-application-controller
    ports:
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha-haproxy
  policyTypes:
  - Ingress
  ```

The destination ports seem to not even be part of the base manifest (for example, trying to connect from argocd-redis-ha-server port 6379 to argocd-redis-ha-haproxy port 42330 which does not exist).
