### ISSUE TITLE
ArgoCD does not see changes 

### ISSUE THREAD

**Issue by buker** [argoproj/argo-cd#19032]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Argo does not see changes when the environment variable in deployment is removed. When I add a new one or edit an existing it will find that one of the variables should be removed. Helm template properly changes.

**To Reproduce**

1. Deploy a helm chart that has some environmental variable (more than one)
2. comment out or remove one of the environmental variables

**Expected behavior**

ArgoCD catch change in the diff and syncs it

**Screenshots**

**Version**

```shell
v2.12.0-rc3+81d4542
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by christianh814** [comment]
@buker Are you saying you made a change in Git and it isn't reflected when you sync? Or are you making an "out of band" change (like `kubectl edit` or `kubectl apply` and then trying to sync?

**Comment by christianh814** [comment]
If it's an edit, then this is a Kubernetes behavior not an Argo CD issue.

Example:

I have the following in Git

```yaml
    spec:
      containers:
        - env:
            - name: DEMO_GREETING
              value: Hello from the environment
            - name: DEMO_FAREWELL
              value: Such a sweet sorrow
```

Then I do `kubectl edit` and change the following

```yaml
    spec:
      containers:
        - env:
            - name: DEMO_GREETING
              value: Hello from the environment
            - name: DEMO_FAREWELL2
              value: Such a sweet sorrow
```

When you click "sync" on Argo CD the end result will be...

```yaml
    spec:
      containers:
        - env:
            - name: DEMO_GREETING
              value: Hello from the environment
            - name: DEMO_FAREWELL
              value: Such a sweet sorrow
            - name: DEMO_FAREWELL2
              value: Such a sweet sorrow
```

This is because of the 3-way-diff Kubernetes uses.

So more information is needed to see if this is a bug or expected behavior
