### ISSUE TITLE
ArgoCD CLI refresh-token does not regenerate new access token when it expire.

### ISSUE THREAD

**Issue by GeorgiDimv** [argoproj/argo-cd#19051]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD cli returns following error after access token expire, and refresh token does not regenerate new one:

FATA[0001] oauth2: "invalid_client" "Invalid client authentication for this refresh token."

**To Reproduce**

Configure OIDC for ArgoCD

create ArgoCD config file or use the default, default is in "~/.argocd/config". It should look like:

```
contexts:
- name: <ARGOCD_SERVER_URL>
  server: <ARGOCD_SERVER_URL>
  user: <ARGOCD_SERVER_URL>
current-context: <ARGOCD_SERVER_URL>
servers:
- grpc-web-root-path: ""
  server: <ARGOCD_SERVER_URL>
users:
- auth-token: <ID_TOKEN_FROM_CURL>
  name: <ARGOCD_SERVER_URL>
  refresh-token: <REFRESH_TOKEN_FROM_CURL>
```

`argocd --config ~/PATH/TO/CONFIG app list`

**Expected behavior**

To list apps

**Version**
v2.10.11
