### ISSUE TITLE
Helm chart values not rendered as expected

### ISSUE THREAD

**Issue by taneli-kantomaa** [argoproj/argo-cd#19080]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Helm chart values don’t get rendered correctly with multiple value files.

**To Reproduce**

We deploy our helm charts in a Kubernetes cluster using argocd (we use an applicationset which creates an application per helm chart). We have a folder structure where we have two sets of values.yaml's for these helm charts; one values.yaml is environment specific and the other one is generic (for more info about the folder structure see “Screenshots” section). The intention is that 
•	The default values of a helm installation are used by default
•	If a value has been defined in the generic values-file then that value should overwrite the default value
    o	There is one single values-file which is used for all environments
•	If a value has been set in the environment specific values-file then that value should overwrite a value in the generic values-file
    o	There is an environment specific values-file for each environment

![image](https://github.com/user-attachments/assets/647197fa-5ace-45a4-8573-18a5ecd4c8d2)
                               Figure 1 screenshot of git-generator-helm-charts.yaml

_In figure 1 the “values.yaml” refers to the generic values-file and the “.../.../values.yaml” in the second line refers to the environment specific values-file._

This approach works for the vast majority of the parameters we define. Still, we have observed few problems with some helm charts with this approach. Here we give 3 such scenarios scenarios:

1.	[Datadog](https://github.com/DataDog/helm-charts/tree/main/charts/datadog)
Helm chart version: 3.57.3
values file parameter: datadog.site
Intention: We would like to define this value only in the generic values-file (as “datadoghq.eu”).
Problem: If we do so the value doesn’t get propagated (and a default value of “datadoghq.com” is used). Currently, to work around this problem, we have to set this value in all of the environment specific values-files.

2.	[Kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)
Helm chart version: 57.0.1
values file parameter: prometheus.agentMode
Intention: We would like to define this value only in the generic values-file (as “true”).
Problem: If we do so the value doesn’t get propagated. Currently, to work around this problem, we have had to set this value in all of the environment specific values-files.

3.	[Kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)
Helm chart version: 57.0.1
values file parameter: prometheus.prometheusSpec.remoteWrite
Note! The value for this parameter is given as a list of objects and we have received the following statement from argocd Slack people:
“Helm can merge maps but not lists (deep merge). Is it what you're experiencing?”

Based on that we understood that this parameter (with list value) can’t be handled properly; still we don’t see this mentioned anywhere in the argocd documentation. Should it be included in the documentation?

**Expected behavior**

If a value is defined in the "generic" values.yaml then that should suffice and we don't need to specify those values in the environment specific values file.

**Screenshots**

![image](https://github.com/user-attachments/assets/0b0e0e1f-845f-4d53-838e-4b14d9bbcb8a)
Figure 2 Folder structure

**Version**

argo-cd helm-chart-version: 6.2.0
argo-cd server version: 2.10.1
argo-cd client side version:v2.9.18+151ee6a
kubernetes version: AKS 1.28

**Comment by bhavinkotak** [comment]
We have been able to use multiple values files for kube-prometheus-stack helm chart that is getting deployed using ArgoCD. This precedence document should provide on how the setup should be done - https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-value-precedence

The first values file is always the common one which will get applied to all the clusters listed in your app-set. Next should be environment-specific values.yaml and so on...

**Comment by MaryamTvk** [comment]
Thank you @bhavinkotak for your response. 
We are also using this method generally and it works. However, as specified in the description, there are only specific values that are not overridden by environment specific value file by surprise. 

For kube-prometheus-stack, these specific cases includes 
- prometheus.agentMode
- prometheus.prometheusSpec.remoteWrite

Are you able to pass these exact values using this structure? (passing these in general values.yaml does not work and is overridden by empty values.yaml in the environment specific values.yaml, but if is passed in the env values, then it works)

**Comment by MaryamTvk** [comment]
To be more clear, I can add that this is not a case that a key is defined in two different values files, because in that case, as is stated in the docs, it is expected that the second value file (the env values in our case) will override the other one.

But if a key is only defined in one of the files, then the two files should be merged. This is what is not happening in our case. When a key such as `prometheus.agentMode` is defined in the common values.yaml, it is not passed and instead the empty env values.yaml takes precedence. But if this value is passed in env values.yaml, then it works.

**Comment by reggie-k** [comment]
Thanks for the detailed description of the problem, @taneli-kantomaa and @MaryamTvk.
I see in the screenshot that you also use Kustomize, is this a case of Kustomize used together with Helm?
Or is Kustomize used just to render ArgoCD manifests and ArgoCD apps just watch Helm charts + values, meaning pure Helm?

**Comment by MaryamTvk** [comment]
Hi @reggie-k,

Kustomization is used to render ArgoCD manifests. ArgoCD helm chart and all other Argo applications and projects (located in the base folder) are deployed by Kustomize. Here is the content in `Kustomization.yaml`: 

```
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 6.2.0 # Installs app version 2.10.1
  releaseName: argocd
  namespace: argocd
  valuesFile: base/values.yaml # ValueFile name HAS TO be changed according to the env/cluster

resources:
- base/application-argocd-dev-prod.yaml
- base/git-generator-helm-charts.yaml
- base/git-generator-charts-resources.yaml
- base/platform-dev-argo-cp-cluster-registeration.yaml
- base/namespaces.yaml
- base/projects.yaml
- base/optional-helm-charts/git-generator-mysql-exporter-helm-chart.yaml
- base/optional-helm-charts/git-generator-oauth-helm-chart.yaml
- base/optional-helm-charts/git-generator-velero-helm-chart.yaml
```

We use the below command to initially install ArgoCD helm chart and after that everything is managed by Argo: 
`kubectl kustomize --enable-helm | kubectl apply -f -`

The applicationset (`git-generator-helm-charts.yaml`) only watches the helm charts folder, and for the helm charts, we are using the umbrella charts, and for instance, in the `cert-manager` folder under helm-charts folder, we have the following:

`Chart.yaml`:
```
apiVersion: v2
name: cert-manager
type: application
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.12.1
    repository: https://charts.jetstack.io
```

and `values.yaml` only has those values that we want to re-write for the upstream chart. Then, some of these general vaules, still are required to be re-written by different enviornments, which are defined in such path under each env folder:  `argocd-demo/argocd-main/platform-dev-argo-cp/environments/dev-argo-cp/cert-manager/values.yaml`
