### ISSUE TITLE
Argocd out of sync at part of spec.kustomize

### ISSUE THREAD

**Issue by namirinz** [argoproj/argo-cd#19122]
Checklist:

* [/] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [/] I've included steps to reproduce the bug.
* [/] I've pasted the output of `argocd version`.

**Describe the bug**
Every argoCD app out of sync at the part of **spec.source.kustomize** even though the source repo has kustomization.yaml file and I try sync, force sync in the argocd ui.

**To Reproduce**
Use this argocd app manifest.
```yaml

# Source: kubeflow-chart/charts/kubeflow-core/templates/010-developer-gateway/010-istio-resources.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 010-istio-resources
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://api.kafra.arkcube.com:6443
  project: default
  source:
    kustomize:
      patches:
      - patch: |-
          - op: replace
            path: /spec/servers/0
            value:
              hosts:
              - "kubeflow.arkcube.com""
              port:
                name: https
                number: 443
                protocol: HTTPS
              tls:
                credentialName: gateway-cert
                mode: SIMPLE
        target:
          kind: Gateway
          name: kubeflow-gateway
    path: common/istio-1-17/kubeflow-istio-resources/base
    repoURL: https://github.com/kubeflow/manifests
    targetRevision: 776d4f4
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - ServerSideApply=true
```

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/ba640505-f820-4cae-ad84-dec2c115146f)
![image](https://github.com/user-attachments/assets/733661fa-d580-47a7-b3e4-6c9713aa3e95)

**Version**

```json
{
    "Version": "v2.7.4+a33baa3.dirty",
    "BuildDate": "2023-06-05T19:00:34Z",
    "GitCommit": "a33baa301fe61b899dc8bbad9e554efbc77e0991",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**
