### ISSUE TITLE
changing destination from server to name causes constant app refresh

### ISSUE THREAD

**Issue by wrdls** [argoproj/argo-cd#19194]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

We have one ArgoCD instance managing a few Kubernetes clusters (A, B, C). ArgoCD itself is deployed on cluster A.

Apps targeting cluster A originally used this destination.

```yaml
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
```

For consistency reasons with apps targeting B and C, we decided to update it to the following:

```yaml
spec:
  destination:
    namespace: default
    name: cluster-a
```

This seemed to work fine initially. However our controller cpu usage has exploded and we constantly see app refreshes happening with `Refreshing app status (spec.destination differs), level (2)`.

Inspecting the app yaml shows that ArgoCD is comparing the app to a state which includes both the name and server in the destination.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-app
  namespace: argocd
spec:
  destination:
    name: cluster-a
    namespace: default
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  sync:
    comparedTo:
      destination:
        name: cluster-a
        namespace: default
        server: https://kubernetes.default.svc
    status: Synced
```

I've tried a hard refresh, restarting the controller, invalidating the cache in Settings->Clusters but none of these seem to help.

We plan to recreate the apps (after removing the finalizer) as a fix but hopefully there's a less drastic solution.

**To Reproduce**

Change destination from `server` to `name` in an app. Both should deploy to `https://kubernetes.default.svc`.

Example cluster config:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster-a
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster-a
  server: https://kubernetes.default.svc
  config: |-
    {
      "tlsClientConfig":{
        "insecure":false
      }
    }
```

**Expected behavior**

`status.comparedTo.destination` only contains `name` and not `server`.

Refreshes because of `Refreshing app status (spec.destination differs), level (2)` don't occur.

**Screenshots**

**Version**

```shell
v2.12.0-rc4
```

**Logs**

```
{"app-namespace":"argocd","app-qualified-name":"argocd/some-app","application":"some-app","level":"info","msg":"Refreshing app status (spec.destination differs), level (2)","project":"default","time":"2024-07-24T15:44:27Z"}
```

Let me know if you'd like any other logs.
