### ISSUE TITLE
Application controller can run out of disk space on '/dev/shm', when deploying concurrently to a large number of clusters, or with many large manifests

### ISSUE THREAD

**Issue by jgwest** [argoproj/argo-cd#19201]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

At present, Argo CD (via gitops-engine) uses `/dev/shm` to store temporary files that are passed to kubectl code, such as manifests and cluster credentials. The temp directory logic can be found within `pkg/utils/io/io.go` of gitops-engine. 

However, since `/dev/shm` is backed by RAM, it has limited size (but has the security advantage of avoiding writes of sensitive info to disk). For many use cases this is not an issue, but, when deploying to a large number of kubernetes clusters, or deploying large k8s manifests, `/dev/shm` can run out of disk space. 

We can/should allow Argo CD users to customize the target output path for application-controller/gitops-engine generated manifests, to allow them to avoid this issue.

I propose we add a new configuration parameter to `argocd-cmd-params-cm` (and connected to Application Controller Deployment/StatefulSet YAML), that allow users to specify a custom application controller manifest destination path, which will allow application controller to writing to a different path with the container, such as '/tmp'.

See the linked issue in gitops-engine for further details.

This issue has a corresponding issue on gitops-engine: https://github.com/argoproj/gitops-engine/pull/614
And PR: https://github.com/argoproj/gitops-engine/pull/613

**To Reproduce**

Concurrently deploy to a large number of clusters, or deploy a large number of large manifests: if the concurrent KiB of generated resources exceed `/dev/shm` size, an error occurs.

**Expected behavior**

Users should be able to specify custom Argo CD path/volume to store generated manifests, allowing them to avoid running out of disk space in `/dev/shm`. 

**Version**

All

**Comment by andrii-korotkov-verkada** [comment]
What's your argocd version? How many clusters/apps do you have?

**Comment by thudi** [comment]
@andrii-korotkov-verkada I have a similar setup with ~10K manifest files as an Application which ended up ~130MB size. Is there any direction or way to increase the tmpfs /dev/shm size ?

**Comment by PhipBlitch-Arcadia** [comment]
@andrii-korotkov-verkada I also hit this about once a month with ArgoCD 2.14.2 managing one very large cluster using app-of-apps, 4900 total.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          20G  4.7G   16G  24% /
tmpfs            64M     0   64M   0% /dev
/dev/nvme0n1p1   20G  4.7G   16G  24% /tmp
shm              64M   64M   56K 100% /dev/shm
```

**Comment by leszekbulawa** [comment]
Just hapened to me at v2.14.8.
Mounting bigger emptydir to /dev/shm fixed the issue

**Comment by mvillla** [comment]
> Just hapened to me at v2.14.8. Mounting bigger emptydir to /dev/shm fixed the issue

how did you mount a bigger emptyDir to /dev/shm exactly? mind sharing the snippet/steps you used?

**Comment by larsks** [comment]
@andrii-korotkov-verkada We just hit this with argocd v2.14.20 with a single cluster and only 10 apps. The largest app has about 100 manifests; the others are much smaller. There were just under 15,000 files in `/dev/shm`.

Restarting the application controller pod (`openshift-gitops-application-controller-0`) seems to have things working again.

**Comment by 7Upers** [comment]
> > Just hapened to me at v2.14.8. Mounting bigger emptydir to /dev/shm fixed the issue
> 
> how did you mount a bigger emptyDir to /dev/shm exactly? mind sharing the snippet/steps you used?

```yaml
    spec:
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi # Increase as needed
      containers:
      - name: argocd-application-controller
        volumeMounts:
        - mountPath: /dev/shm
          name: shm
```

**Comment by kkworden** [comment]
I just ran into this on v2.15.3. The solution from @7Upers worked like a charm.

We also had to update our application controller memory request/limits, as the `emptyDir` volume mount with `medium: Memory` incurs additional memory usage:

```
  resources:
    requests:
      cpu: 2000m
      memory: 6G # Increase as needed to account for additional volume mount
    limits:
      memory: 6G # Increase as needed to account for additional volume mount
  metrics:
    enabled: true
```

So make sure to rightsize your application controller's memory too.
