### ISSUE TITLE
ArgoCD does not set OutOfSync status after editing a deployed resource

### ISSUE THREAD

**Issue by BoyFromDubai** [argoproj/argo-cd#19215]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After editing a resource using web interface or kubectl edit, argo does not set OutOfSync status
Application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-test-infra
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks/0/failurePolicy
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
    - group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks/0/failurePolicy
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
  project: infra
  sources:
    - chart: base
      helm:
        releaseName: base
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.22.1
    - chart: gateway
      helm:
        releaseName: gateway
        valuesObject:
          defaults:
            service:
              loadBalancerIP: 10.10.99.31
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.22.1
    - helm:
        releaseName: istio
      path: .
      repoURL: 'some-istio-repo'
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

**To Reproduce**

kubectl edit smth that is under argocd control

**Expected behavior**

It has to set OutOfSyncStatus

**Screenshots**
![image](https://github.com/user-attachments/assets/1a6ba01e-670b-4a23-b420-d760648872c6)
![image](https://github.com/user-attachments/assets/cdb6d5e7-8cc3-4ace-b58f-23465dc7a5e6)

**Version**

v2.11.2+25f7504

**Logs**

```
Paste any relevant application logs here.
```
