### ISSUE TITLE
Add Kubectl Option support like disable-compression

### ISSUE THREAD

**Issue by darkradish** [argoproj/argo-cd#19259]
# Summary

For my needs, i want to add option --disable-compression to my cluster configuration ( https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#Cluster) i see no option to doing that on my cluster contfiguration

# Motivation

Support all of kubectl feature

# Proposal

in cluster secret (or cli) add 
```yaml
server: xxx
bearerToken: xxx
context_option : {
 "disable-compression": true
}
```
and pass it to kubectl context
