### ISSUE TITLE
applicationSet syncPolicy docs vs CRD mismatch

### ISSUE THREAD

**Issue by drdkmkkr** [argoproj/argo-cd#19253]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ApplicaitonSet docs does list `spec.syncPolicy.syncOptions` and `spec.syncPolicy.ignoreApplicationDifferences` as a possible value:
https://github.com/argoproj/argo-cd/blob/25c2f2fbc66ef3554f45786249af0ff4afafeaf2/docs/operator-manual/applicationset.yaml#L166-L187

But this is not reflected in the CRD:
https://github.com/argoproj/argo-cd/blob/ff3e36c3ceb8c82c60349d2ce797c60fca87b3e9/manifests/crds/applicationset-crd.yaml#L14936-L14947

**To Reproduce**

Supply applicationSet with a `spec.syncPolicy.syncOptions` value.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: ...
spec:
  generators: ...
  template: ...
  syncPolicy:
    applicationsSync: create-only
    syncOptions: # Will fail if provided
    - PrunePropagationPolicy=background
```
**Expected behavior**

Docs and CRD should be in sync.
Not sure if the fields are missing in the CRD or mistakenly documented.

**Version**

```shell
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T14:02:54Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.22.5
  Compiler: gc
  Platform: darwin/arm64
```

**Logs**

```
strict decoding error: unknown field "spec.syncPolicy.syncOptions"

strict decoding error: unknown field "spec.syncPolicy.ignoreApplicationDifferences"
```
