### ISSUE TITLE
Commas and dollar signs improperly passed to Helm

### ISSUE THREAD

**Issue by benjaminxie** [argoproj/argo-cd#19269]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Values with consecutive commas or dollar signs are improperly escaped and passed to Helm (despite [PR 1720](https://github.com/argoproj/argo-cd/pull/1720).)
**To Reproduce**

Create a new app from a helm chart. Set one of the parameters to `,,,,,,,,$$$$$` (or just any string with consecutive commas and consecutive dollar signs). Click create. To simplify things, I've attached an Application yaml that creates the helm-guestbook example and has an overridden parameter:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    helm:
      parameters:
        - name: containerPort
          value: ',,,,,,,,$$$$'
  sources: []
  project: default
  syncPolicy:
    automated: null

```
Attempting to create this app, we will see a popup with the error message:
Unable to create application: application spec for guestbook is invalid: InvalidSpecError: Unable to generate manifests in helm-guestbook: rpc error: code = Unknown desc = `helm template . --name-template guestbook --namespace default --kube-version 1.28 --set containerPort=,\,,\,,\,,\,$$ <api versions removed> --include-crds` failed exit status 1: Error: failed parsing --set data: key "," has no value (cannot end with ,)

Note that flag `--set containerPort=,\,,\,,\,,\,$$`. Only about half the commas are escaped and we end up with half the $'s we wanted.
**Expected behavior**

I should be able to create my app.

Helm's set flag should be receive my value but with all the commas properly escaped as well as my dollar signs (I'm guessing whatever shell Argo CD is using, $$ is how you get a literal dollar sign).

Additionally, using `forceString: true` on the parameter does not help.

**Version**

```
$ argocd version
argocd: v2.10.3+0fd6344.dirty
  BuildDate: 2024-03-13T21:01:52Z
  GitCommit: 0fd6344537eb948cff602824a1d060421ceff40e
  GitTreeState: dirty
  GoVersion: go1.22.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.9.14+d3955f4
```

Helm has a `--set-literal` flag that allows us to avoid all this escaping. I understand that Argo CD might not be able to take advantage due to using an older version of Helm or some other technical reason but I thought I'd throw it out there.
