### ISSUE TITLE
Support for in-line block from helm chart values

### ISSUE THREAD

**Issue by pluqueTheLuxe** [argoproj/argo-cd#1930]
> This feature is a split of [1903](https://github.com/argoproj/argo-cd/issues/1903) which suggest implementation of ConfigMap to store helm chart values.

**Is your feature request related to a problem? Please describe.**
ArgoCD uses value files from it's `valueFiles` property from the source git as values to be used in the templating. Unfortunatly, this does not covers the situation were source git contains public helm charts and value files located outside of the source git.

**Describe the solution you'd like**
Having the ability add as inline block the value files.

Here is the suggested implementation(improved by @jessesuen in [1903](https://github.com/argoproj/argo-cd/issues/1903#issuecomment-510705793))  of in-line block to configure the helm chart values. 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    helm:
      valueFiles:
      - override.yaml   
      - staging.yaml   
      valuesLiteral:
      - name: override.yaml
        value: |
           param1: value1
           param2: value2
           param3: value3
```
