### ISSUE TITLE
Add `spec.source.helm` fields for `--kube-version`, `--api-versions`, and `--namespace`

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#19325]
# Summary

We should add fields in `spec.source.helm` for the Helm CLI's `--kube-version`, `--api-versions`, and `--namespace` flags.

Today, all three of those parameters are inferred from the `spec.destination`. The Kube version and API versions are pulled from the destination cluster. And the `--namespace` field is set to the `spec.destination.namespace` field (if present).

# Motivation

Users should have a way to make these dynamic values static so that manifest hydration is predictable/deterministic.

Most users likely will be fine with the default values dynamically loaded at manifest hydration time. Some may want the additional control.

Adding these fields will help provide a full feature set to the [manifest hydrator](https://github.com/argoproj/argo-cd/pull/17755/files) which is meant to generate manifests deterministically and should avoid accepting runtime-generated variables.

# Proposal

We should add these fields to the Application CRD:

```yaml
spec:
  source:
    helm:
      # You can specify the Kubernetes API version to pass to Helm when templating manifests. By default, Argo CD uses
      # the Kubernetes version of the target cluster.
      kubeVersion: v1.30

      # You can specify the Kubernetes resource API versions to pass to Helm when templating manifests. By default, Argo
      # CD uses the API versions of the target cluster. The format is [group/]version/kind.
      apiVersions:
        - traefik.io/v1alpha1/TLSOption
        - v1/Service

      # Optional namespace to template with. If left empty, defaults to the app's destination namespace.
      namespace: custom-namespace
```

When one is specified, the corresponding dynamically-loaded value should be ignored in favor of the hard-coded value.

We should provide a CLI interface to set these values.

We should not provide a UI interface to set these values. This is more of a power-user feature set, and it would likely be more confusing than helpful to UI users.
