### ISSUE TITLE
argocd proj role shows information for all roles instead of specified role

### ISSUE THREAD

**Issue by gnunn1** [argoproj/argo-cd#19341]
Checklist:

* [* ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ *] I've included steps to reproduce the bug.
* [ *] I've pasted the output of `argocd version`.

**Describe the bug**

When using the `argocd proj role` command to view a specific role it outputs information for all roles instead of just the specified role.

**To Reproduce**

Given the following Project definition with two roles, admin and pipeline:
```
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: shared-gitops:argoproj.io/AppProject:gitops/user1
  labels:
    argocd.argoproj.io/project-inherit: global
  name: user1
  namespace: gitops
spec:
  description: user1 project
  destinations:
  - name: in-cluster
    namespace: user1-argocd
  - name: in-cluster
    namespace: user1-dev
  - name: in-cluster
    namespace: user1-stage
  - name: in-cluster
    namespace: user1-prod
  - name: in-cluster
    namespace: user1-cicd
  roles:
  - description: Team1 admins
    groups:
    - team1
    - user1-cli
    name: admin
    policies:
    - p, proj:user1:admin, applications, *, user1/*, allow
    - p, proj:user1:admin, exec, create, user1/*, allow
  - description: Pipeline accounts
    groups:
    - user1-pipeline
    name: pipeline
    policies:
    - p, proj:user1:pipeline, applications, get, user1/*, allow
    - p, proj:user1:pipeline, applications, sync, user1/*, allow
  sourceNamespaces:
  - user1-argocd
  sourceRepos:
  - '*'
```
Run the `argocd proj role` command for the admin role and note that all policies are output not just the ones for the admin role:
```
$ argocd proj role get user1 admin
Role Name:     admin
Description:   Team1 admins
Policies:
p, proj:user1:admin, projects, get, user1, allow
p, proj:user1:admin, applications, *, user1/*, allow
p, proj:user1:admin, exec, create, user1/*, allow
g, team1, proj:user1:admin
g, user1-cli, proj:user1:admin
p, proj:user1:pipeline, projects, get, user1, allow
p, proj:user1:pipeline, applications, get, user1/*, allow
p, proj:user1:pipeline, applications, sync, user1/*, allow
g, user1-pipeline, proj:user1:pipeline
JWT Tokens:
ID  ISSUED-AT  EXPIRES-AT
```
**Expected behavior**

The command should only return the information for the `admin` role:

````
$ argocd proj role get user1 admin
Role Name:     admin
Description:   Team1 admins
Policies:
p, proj:user1:admin, projects, get, user1, allow
p, proj:user1:admin, applications, *, user1/*, allow
p, proj:user1:admin, exec, create, user1/*, allow
g, team1, proj:user1:admin
g, user1-cli, proj:user1:admin
JWT Tokens:
ID  ISSUED-AT  EXPIRES-AT
````

**Version**

```shell
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T10:10:59Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.16+3bf801f
  BuildDate: 2024-07-29T10:40:39Z
  GitCommit: 3bf801f2dfe666bccdb0b40fa6e24e8d4b0087d6
  GitTreeState: clean
  GoVersion: go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+21986+2112108a)
  Compiler: gc
  Platform: linux/amd64
  ExtraBuildInfo: {Vendor Information: Red Hat OpenShift GitOps version: v1.12.5}
  Kustomize Version: v5.2.1 unknown
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```
