### ISSUE TITLE
"argocd proj get" should show sourceNamespaces information

### ISSUE THREAD

**Issue by gnunn1** [argoproj/argo-cd#19344]
Checklist:

* [ *] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ *] I've included steps to reproduce the bug.
* [ *] I've pasted the output of `argocd version`.

**Describe the bug**

When using `argocd proj role get` on an AppProject no information is displayed about configured sourceNamespaces. There also doesn't seem to be any way to display this information from the CLI.

**To Reproduce**

With an AppProject where sourceNamespaces are defined as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: shared-gitops:argoproj.io/AppProject:gitops/user1
  labels:
    argocd.argoproj.io/project-inherit: global
  name: user1
  namespace: gitops
spec:
  description: user1 project
  destinations:
  - name: in-cluster
    namespace: user1-argocd
  - name: in-cluster
    namespace: user1-dev
  - name: in-cluster
    namespace: user1-stage
  - name: in-cluster
    namespace: user1-prod
  - name: in-cluster
    namespace: user1-cicd
  roles:
  - description: Team1 admins
    groups:
    - team1
    - user1-cli
    name: admin
    policies:
    - p, proj:user1:admin, applications, *, user1/*, allow
    - p, proj:user1:admin, exec, create, user1/*, allow
  - description: Pipeline accounts
    groups:
    - user1-pipeline
    name: pipeline
    policies:
    - p, proj:user1:pipeline, applications, get, user1/*, allow
    - p, proj:user1:pipeline, applications, sync, user1/*, allow
  sourceNamespaces:
  - user1-argocd
  sourceRepos:
  - '*'
 ```
Viewing the project in the argocd CLI does not show the sourceNamespace information:

```
$ argocd proj get user1
Name:                        user1
Description:                 user1 project
Destinations:                ,user1-argocd
                             ,user1-dev
                             ,user1-stage
                             ,user1-prod
                             ,user1-cicd
Repositories:                *
Scoped Repositories:         <none>
Allowed Cluster Resources:   <none>
Scoped Clusters:             <none>
Denied Namespaced Resources: /Namespace
                             /ResourceQuota
                             /LimitRange
                             operators.coreos.com/*
                             operator.openshift.io/*
                             storage.k8s.io/*
                             machine.openshift.io/*
                             machineconfiguration.openshift.io/*
                             compliance.openshift.io/*
Signature keys:              <none>
Orphaned Resources:          disabled
```
**Expected behavior**

sourceNamespaces should be dsplayed.

**Screenshots**

**Version**

```shell
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T10:10:59Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.16+3bf801f
  BuildDate: 2024-07-29T10:40:39Z
  GitCommit: 3bf801f2dfe666bccdb0b40fa6e24e8d4b0087d6
  GitTreeState: clean
  GoVersion: go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+21986+2112108a)
  Compiler: gc
  Platform: linux/amd64
  ExtraBuildInfo: {Vendor Information: Red Hat OpenShift GitOps version: v1.12.5}
  Kustomize Version: v5.2.1 unknown
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```
