### ISSUE TITLE
Argo does not automatically sync an application when using multi-repo configuration

### ISSUE THREAD

**Issue by daviddvir14** [argoproj/argo-cd#19382]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Argo does not automatically sync an application after changes are made to a source repository (Git) when using a multi-repo configuration. 
However, manual sync works as expected.

**To Reproduce**
1. Create a new application 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc/
  project: default
  sources:
    - repoURL: "ghcr.io/a-repo"
      targetRevision: 0.35.5
      chart: karpenter
      helm:
        passCredentials: true
        valueFiles:
          - $values/infra/staging/kube-system/karpenter/values.yaml
    - repoURL: "https://github.com/a-repo/argo-config.git"
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
2. Change a value in the **ref** repo

**Expected behavior**

Argo should automatically sync the application when there is a change in the source repository.

**Screenshots**

**Version**

```shell
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T14:02:54Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.22.5
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.3+3f344d5
```

**Logs**

application-controller:
```
time="2024-08-05T11:11:02Z" level=debug msg="https://github.com/a-repo/argo-config.git has credentials"
time="2024-08-05T11:11:02Z" level=debug msg="Generating Manifest for source {https://github.com/a-repo/argo-config.git  HEAD nil nil nil nil  values} revision HEAD"
time="2024-08-05T11:11:03Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd/karpenter
```
repo-service:
```
time="2024-08-05T11:11:02Z" level=debug msg="getting manifests cache" appName=karpenter appSrc="{\"appSrc\":{\"repoURL\":\"ghcr.io/a-repo\",\"targetRevision\":\"0.35.5\",\"helm\":{\"valueFiles\":[\"$values/infra/staging/kube-system/karpenter/values.yaml\"],\"passCredentials\":true},\"chart\":\"karpenter\"},\"srcRefs\":{\"$values\":
time="2024-08-05T11:11:02Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:ghcr.io/a-repo,Path:,TargetRevision:0.35.5,Helm:&ApplicationSourceHelm{ValueFiles:[$values/infra/staging/kube-system/karpenter/values.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:true,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:karpenter,Ref:,}/0.35.5"
time="2024-08-05T11:11:02Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-08-05T11:11:02Z" grpc.time_ms=16.011 span.kind=server system=grpc
time="2024-08-05T11:11:02Z" level=debug msg="Skipping manifest generation for ref only source for application: karpenter and ref values"
time="2024-08-05T11:11:02Z" level=debug msg="symbolic reference 'HEAD' (refs/heads/master) resolved to '9cc8e001f39a9a0bbb8c1dac28fc7cfa9c33722a'"
time="2024-08-05T11:11:02Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-08-05T11:11:02Z" grpc.time_ms=0.581 span.kind=server system=grpc
```
