### ISSUE TITLE
Node view should show resources (memory/cpu) for the hover details of a pod (or parent/top level resource)

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#19457]
# Summary

If you go to the [node view](https://cd.apps.argoproj.io/applications/argo-cd?resource=kind%3APod&view=pods) and look at a node, you'll see two bars:
1. cpu
2. mem

If you hover over a bar, it'll show you requests for pods in that app on that node and for all other pods on that node.

<img width="261" alt="image" src="https://github.com/user-attachments/assets/c640df6f-5c4e-4c0f-93d6-813cbd5272f1">

If you hover over a **pod** in the node, you won't see requests for cpu/mem

<img width="262" alt="image" src="https://github.com/user-attachments/assets/a558de8b-0459-46c0-b51b-0a6aaa05b1fd">

# Motivation

I'd like to be able to see the resource costs per pod (this would be the sum of all running containers -- it would exclude completed init containers), or if i switch to parent resource/top level resource (this would be the sum of all running containers for all running pods for the given resource).

It's true that I could open a pod's info view, but if the pod has multiple containers, getting the information out of the yaml is absolutely impractical

# Proposal

How do you think this should be implemented?

1. Add two rows to the pod hover one for cpu and one for ram showing requests
2. consider adding a hover to parent/top resources -- this should only count live pods (i.e. things that are currently requesting resources as opposed to terminated pods which are still in kubernetes but no longer running and thus aren't reserving resources)

**Comment by surajyadav1108** [comment]
Hey, @jsoref, I might like to try to implement this, but I would need a few suggestions first as I am not familiar with backend code yet. 💭 

So, is the resource cost per pod supposed to be the declared resources in the manifests for a pod (like requests and limits)? Or is it something like real-time usage that we get with the 
`kubectl top command `for a pod? I am asking because the bars are showing allocated resources for the pods as groups.
```
     containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
```
we need  to implement something similar, like showing allocated resources (requests for CPU and memory) for every pod (if declared in manifest) or live resource usage ?
