### ISSUE TITLE
SelfHeal with AppSet and Multi-Source is not respected when SyncResult Revisions do not match ComparedTo Revisions

### ISSUE THREAD

**Issue by Ezzahhh** [argoproj/argo-cd#19452]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have an ApplicationSet using Multi-Source like this:
```
sources:
  - repoURL: git@github.com:example/argo-deploy.git
    targetRevision: HEAD
    ref: values
  - chart: "{{.values.csChart}}"
    repoURL: "{{.values.csChartRepository}}"
    targetRevision: "{{.values.csChartVersion}}"
    helm:
      releaseName: promrules
      ignoreMissingValueFiles: true
      valueFiles:
        - $values/{{index .metadata.annotations "gitops_workload_basepath"}}environments/default/workloads/{{.values.csChart}}/values.yaml
        - $values/{{index .metadata.annotations "gitops_workload_basepath"}}environments/{{index .metadata.labels "environment"}}/workloads/{{.values.csChart}}/values.yaml
        - $values/{{index .metadata.annotations "gitops_workload_basepath"}}clusters/{{.name}}/workloads/{{.values.csChart}}/values.yaml
```

with this sync policy:

```
syncPolicy:
  automated:
    prune: true
    selfHeal: false
    allowEmpty: false
```

If the last revision for the last sync to the App does not match the HEAD revision in Git and the object is updated in the cluster, Argo will sync even if selfHeal is set to `false`.

When I test the same helm chart in an Application with no Multi-Source, the selfHeal is respected.

If the SyncResult Revision hash is the same as the HEAD commit hash, then `selfHeal: false` will be respected.

**To Reproduce**

1. Set `selfHeal: false` and sync the AppSet
2. Make a random commit that is unrelated so that `HEAD` points to another revision
3. Make a change on the cluster to force a resource change on the App
4. App will initiate an automated sync and selfHeal the change
5. Make the same change on the cluster again to force change on App
6. App will stay OutOfSync and no longer selfHeal

Operating theory is that the OperationState.SyncResult.Revisions (last sync Revision) are being DeepEquals with comparedTo Revision (HEAD in Git). When these differ (unrelated commit made to Git), Argo incorrectly syncs even when selfHeal is set to `false`. This means `selfHeal` only works when these revisions line up which is not correct or expected behaviour. We cannot rely on comparing Revisions from HEAD and last Revision SyncResult to determine whether the App should sync since changes made on cluster could compare with unrelated Revisions in Git.

**Expected behavior**

selfHeal should be respected regardless of any combination of AppSet/App with or without Multi-Source.
Argo should not sync the Multi-Source App simply because the HEAD revision in Git has differed with the last SyncResult Revision hash. It should check the source of what is triggering the sync (from resource/object change on cluster) before determining whether it should sync/selfHeal. In other words, if an object change is from the cluster and `selfHeal: false` then we should skip the sync.

**Screenshots**

**Version**

```shell
{
    "Version": "v2.10.9+c071af8",
    "BuildDate": "2024-04-30T15:53:28Z",
    "GitCommit": "c071af808170bfc39cbdf6b9be4d0212dd66db0c",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```
