### ISSUE TITLE
Support envsubst in Kustomize patches

### ISSUE THREAD

**Issue by sethryder** [argoproj/argo-cd#19459]
# Summary

It would be helpful if we could use envsubst (specifically Build Environment variables) in patches for Kustomize like we can for commonLabels and commonAnnotations. This is specifically for the `Application` kind as we can get this to work with go templates for `ApplicationSets`.

# Motivation

There are times were we have specific labels we want to set on just Deployments and not on every object, for example the short hash of the git commit for the Datadog version label.

```yaml
patches:
  - target:
      kind: Deployment
      name: ecommerce
    patch: |-
      - op: replace
        path: /metadata/labels/tags.datadoghq.com~1version
        value: ${ARGOCD_APP_REVISION_SHORT}
      - op: replace
        path: /spec/template/metadata/labels/tags.datadoghq.com~1version
        value: ${ARGOCD_APP_REVISION_SHORT}
```

# Proposal

I believe it should work the same way as it does for commonLabels/commonAnnotations. But maybe a flag like `commonAnnotationsEnvsubst` for turning in on for patches would be best/required.

**Comment by christianh814** [comment]
Unless I'm misunderstanding the ask, but I think this is available now

https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L118

**Comment by sethryder** [comment]
> Unless I'm misunderstanding the ask, but I think this is available now
> 
> https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L118

I believe currently envsubst only works on Labels/Annotations. What I am looking for is being able to use them in the actual patch definitions. I mentioned `commonAnnotationsEnvsubst` as an example if Argo wanted to use something like `patchEnvsubst` to be able to turn it on/off.

**Comment by isarns** [comment]
This can also be a huge help when using ArgoCD + kustomize with helm chart inflection with helm private repo. A PAT could be passed to the repo URL. 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://token:${PAT}@raw.githubusercontent.com/my-org/helm-repository/master/
    version: 0.0.1
    name: package-name
    namespace: test
    releaseName: test
    valuesFile: "values.yaml"
```

currently this behavior (quite popular pattern) is impossible with private helm repo with out hardcoding the PAT.
