### ISSUE TITLE
Can't login to helm registy when "return" character is missing in the password (external-secrets)

### ISSUE THREAD

**Issue by northys** [argoproj/argo-cd#19451]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When I create the repository using external secrets like this
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-helms
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: ssm
    kind: ClusterSecretStore
  target:
    name: gitlab-helms
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        project: default
        name: gitlab-helms
        type: helm
        url: https://gitlab.com/api/v4/projects/projectID/packages/helm/stable
        username: gitlabUser
        password: |
                { .password }}" }}
  data:
    - secretKey: password
      remoteRef:
        key: /argocd/gitlab-token
```

It creates a secret which shows as failed in Argo with 401 Unauthorized.

When I try to manually create the same the same repository connection it works.

The only reason I found in the secrets (created by external-secrets.io and argocd UI) is that when I base64 decode the password the one from external-secret is missing the `return` character at the end of it (displayed as ⏎ in windows terminal console).

This one works:
```
glpat-secretToken⏎
```
This one doesn't work:
```
glpat-secretToken
```

**To Reproduce**

**Expected behavior**

As the stings are the same I would expect that argo correctly logs in to the helm repository. It works with the SSH key (which is also missing the return character when I decode the secret value) to clone the git repository.

**Screenshots**

**Version**

```shell
argocd: v2.12.0+ec30a48
  BuildDate: 2024-08-05T13:25:54Z
  GitCommit: ec30a48bce7a60046836e481cd2160e28c59231d
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
