### ISSUE TITLE
The Argo CD Application resource cannot retrieve the server address information of the deployment cluster.

### ISSUE THREAD

**Issue by CCH0124** [argoproj/argo-cd#19481]
Checklist:

* [v] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [v] I've included steps to reproduce the bug.
* [v] I've pasted the output of `argocd version`.

**Describe the bug**

Error message:
```bash
InvalidSpecError
application destination server 'https://172.18.0.4:6443' and namespace 'team-a' do not match any of the allowed destinations in project 'team-a-project'
```
**To Reproduce**

I am declaring a new ApplicationSet resource with the following specifications:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-generator-app
  namespace: argo
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - clusters: 
          selector:
            matchExpressions:
              - key: env
                operator: In
                values:
                  - dev
                  - stage
                  - prd
          values:
            env: '{{index .metadata.annotations "env"}}' 
      - git:
          repoURL: https://github.com/CCH0124/helm-charts.git
          revision: argo-appset
          directories:
          - path: charts/*
  template:
    metadata:
      name: '{{.path.basename}}-{{.values.env}}'
    spec:
      project: team-a-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=false
      source:
        repoURL: https://github.com/CCH0124/helm-charts.git
        targetRevision: 'argo-appset'
        path: 'charts/{{.path.basename}}'
        helm:
          valueFiles:
            - 'values-{{.values.env}}.yaml'
          ignoreMissingValueFiles: true
          releaseName: '{{.path.basename}}-{{.values.env}}'
      destination:
        # name: '{{.name}}'
        server: '{{.server}}'
        namespace: 'team-a'
```

I am declaring a new AppProject resource with the following specifications:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a-project
  namespace: argo
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for team-a
  sourceRepos:
  - https://github.com/CCH0124/K8s-with-quarkus.git
  - https://github.com/CCH0124/helm-charts.git
  destinations:
  - namespace: team-a
    name: stage-cluster
  - namespace: team-a
    name: k3d-dev-cluster
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: ReplicaSet
  - group: '*'
    kind: ServiceAccount
  - group: '*'
    kind: Service
  - group: '*'
    kind: Pod
  - group: 'batch'
    kind: Job
  permitOnlyProjectScopedClusters: false
```

The image below presents the configuration details of the AppProject resource.

![image](https://github.com/user-attachments/assets/1bd8b10a-95e4-4ac8-9d77-b595d4b258d2)

The git-generator-app ApplicationSet has generated the Application resources shown below. The Server endpoint is resolved correctly, however, the deployment is failing. The root cause of this deployment failure is yet to be determined.

```yaml
project: team-a-project
source:
  repoURL: 'https://github.com/CCH0124/helm-charts.git'
  path: charts/project-b
  targetRevision: argo-appset
  helm:
    valueFiles:
      - values-dev.yaml
    releaseName: project-b-dev
    ignoreMissingValueFiles: true
destination:
  server: 'https://172.18.0.4:6443'
  namespace: team-a
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: true
  syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=false
```

**Expected behavior**

By modifying the value to `name: {{.name}}`, I can successfully execute the process.  I expect `server: {{.server}}` to work successfully, just like the nginx-ingress-appset resource below.

While the previous case failed, the following one succeeded in deployment.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress-appset
  namespace: argo
spec:
  generators:
  - clusters: 
      selector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - dev
              - stage
              - prd
  template:
    metadata:
      name: '{{name}}-ingress-controller'
    spec:
      project: sre-project
      sources:
      - repoURL: 'https://kubernetes.github.io/ingress-nginx'
        chart: ingress-nginx
        targetRevision: 4.10.1
        helm:
          releaseName: ingress-nginx
          version: v3
          valueFiles:
          - $values/third-party/ingress/values.yaml
      - repoURL: 'https://github.com/CCH0124/argocd-sandbox.git'
        targetRevision: HEAD
        ref: values
      destination:
        server: '{{server}}'
        namespace: 'ingress'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```
Despite both examples specifying the same server variable, server: '{{server}}', there is a discrepancy in their execution behavior. One example deploys successfully, while the other fails.

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.11.5+c4b283c
  BuildDate: 2024-07-15T18:15:32Z
  GitCommit: c4b283ce0c092aeda00c78ae7b3b2d3b28e7feec
  GitTreeState: clean
  GoVersion: go1.21.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

```

application destination server 'https://172.18.0.4:6443' and namespace 'team-a' do not match any of the allowed destinations in project 'team-a-project'
```
