### ISSUE TITLE
"the server is currently unable to handle the request" - after AKS upgrade

### ISSUE THREAD

**Issue by kubebn** [argoproj/argo-cd#19490]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

We have upgraded the AKS cluster to the latest version, 1.30.3. After the upgrade, ArgoCD stopped being able to sync applications within the cluster. When looking at the settings of ArgoCD, we can clearly see that the cluster is green and successfully connected.

**To Reproduce**

The following steps are used to connect external AKS cluster to ArgoCD:

```
kubectl create serviceaccount argocd-manager -n kube-system

kubectl -n kube-system apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: argocd-manager-token
  annotations:
    kubernetes.io/service-account.name: argocd-manager
type: kubernetes.io/service-account-token
EOF

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-role
rules:
- apiGroups:
    - '*'
  resources:
    -  '*'
  verbs:
    - '*'
- nonResourceURLs:
    - '*'
  verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-role
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: kube-system
---

and then secret is created in argocd namespace with SA token -


  labels:
    argocd.argoproj.io/secret-type: cluster
{

   "bearerToken":"{cluster_token}",

   "tlsClientConfig":{

      "insecure":true

   }

}

```

**Expected behavior**

In ArgoCD UI we could clearly see that cluster (in settings/clusters tab) is green. It was working just fine. After AKS cluster upgrade, cluster is still shown as green/successful in UI, however, whenever we try to sync something in this cluster, we are getting "the server is currently unable to handle the request" error.

Worth to mention that if I run Sync with Replace/Prune-force, it works

**Screenshots**

<img width="339" alt="image" src="https://github.com/user-attachments/assets/6d84c1e3-0427-4885-9be7-f566bdaa926f">
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/81134c17-a715-40c3-9ed5-dabb39485d26">
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/e938dc5c-d074-4627-8afb-b56829b5769c">
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/39ffb745-f7e2-4f12-af08-53fbfaf1b082">

**Version**

```shell
argocd version
argocd: v2.11.4+e1284e1
  BuildDate: 2024-07-02T19:17:02Z
  GitCommit: e1284e19e03c9abab2ea55314b14b1e0381c4045
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

**Logs**

In the logs I could find this. If there is anything else worth to check on, please share.

```
argo-cd-dev-argocd-application-controller-3 application-controller {"eventType":"MODIFIED","groupKind":"CustomResourceDefinition.apiextensions.k8s.io","level":"info","msg":"Updating Kubernetes APIs, watches, and Open API schemas due to CRD event","server":"https:/cluster-name/","time":"2024-08-09T09:53:22Z"}
argo-cd-dev-argocd-application-controller-3 application-controller {"error":"failed to load open api schema while handling CRD change: error getting openapi resources: the server is currently unable to handle the request","level":"error","msg":"Failed to reload open api schema","server":"https://cluster-name/","time":"2024-08-09T09:53:22Z"}
argo-cd-dev-argocd-application-controller-3 application-controller {"eventType":"MODIFIED","groupKind":"CustomResourceDefinition.apiextensions.k8s.io","level":"info","msg":"Updating Kubernetes APIs, watches, and Open API schemas due to CRD event","server":"https://cluster-name/","time":"2024-08-09T09:53:22Z"}
```
