### ISSUE TITLE
hydrator: enable pushing for SSH creds

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#19499]
I've tested the hydrator so far only with GitHub App credentials. Trying to do the same with SSH creds currently fails.

Here's the credential format I'm using.

I've enabled the key as a deploy key in my test repo.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-example-apps-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository-write
stringData:
  url: https://github.com/crenshaw-dev/argocd-example-apps
  sshPrivateKey: |
```

Here's the error I get:

```
Failed to hydrated revision 6950caf8881481f20017156b3ac0528343d0da4f: failed to hydrate apps: failed to commit hydrated manifests: rpc error: code = Unknown desc = failed to commit and push: failed to push: `git push origin whatever` failed exit status 128: fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

I've confirmed via logs that the commit-server is using the SSH credential.
