### ISSUE TITLE
Argo CD hooks are ignored when helm hooks present

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1952]
Tried to add argo-cd hooks into an existing helm hook

```yaml
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
```

However the hook was ignored because of the presence of the helm hook. Needed to remove the helm hook before it worked. We should never ignore argocd hooks.
