### ISSUE TITLE
OpenKruise Daemonset sync blocked by healthy check

### ISSUE THREAD

**Issue by alswl** [argoproj/argo-cd#19545]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying ArgoCD to manage OpenKruise Daemonset, and when I want to sync the kruise ds, the sync will failed and give the message:

```
ComparisonError: error setting app health: failed to get resource health for "DaemonSet" with name "rdma-device-plugin" in namespace "nvidia-gpu": <string>:12: cannot perform sub operation between number and nil stack traceback: <string>:12: in main chunk [G]: ?
```

**To Reproduce**

- Install ArgoCD
- apply a openkruise daemonset, like

```
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: rdma-device-plugin
spec:
  burstReplicas: 250
  revisionHistoryLimit: 10
  selector:
        app-name: rdma-device-plugin-pod
  template:
    metadata:
      labels:
        app-name: rdma-device-plugin-pod
    spec:
      containers:
          image: 'test.com/k8s-rdma-sriov-dev-plugin'
          imagePullPolicy: IfNotPresent
          name: k8s-rdma-device-plugin
      hostNetwork: true
      restartPolicy: Always
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50
      rollingUpdateType: Standard
    type: RollingUpdate

```

**Expected behavior**

Sync will works.

**Screenshots**

![image](https://github.com/user-attachments/assets/137f993c-57ee-41d3-aa58-e702b7452065)

**Version**

```shell
argocd: v2.11.2+25f7504
  BuildDate: 2024-05-23T13:32:13Z
  GitCommit: 25f7504ecc198e7d7fdc055fdb83ae50eee5edd0
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
ComparisonError: error setting app health: failed to get resource health for "DaemonSet" with name "rdma-device-plugin" in namespace "nvidia-gpu": <string>:12: cannot perform sub operation between number and nil stack traceback: <string>:12: in main chunk [G]: ?
```
