### ISSUE TITLE
2.12.x throws could not read Username for 'https://gitlab.com' from the UI

### ISSUE THREAD

**Issue by c-buisson** [argoproj/argo-cd#19585]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Since 2.12.x, the UI throws this error message:
```
Unable to load data: error acquiring repo lock: failed to initialize repository resources: rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed exit status 128: fatal: could not read Username for 'https://gitlab.com/': terminal prompts disabled
```

**To Reproduce**

Upgrade to `2.12.x` from `2.11.x` with connectivity to Gitlab repositories.
Using Helm chart version `7.4.4`

**Expected behavior**

UI able to refresh Applications from Gitlab.

**Screenshots**

<img width="315" alt="Screenshot 2024-08-19 at 11 55 02" src="https://github.com/user-attachments/assets/ab3ff146-e01a-4f1b-8150-5c5208c9d697">

```shell
argocd: v2.11.2+25f7504
  BuildDate: 2024-05-23T13:58:43Z
  GitCommit: 25f7504ecc198e7d7fdc055fdb83ae50eee5edd0
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.12.1+26b2039
  BuildDate: 2024-08-16T16:42:13Z
  GitCommit: 26b2039a55b9bdf807a70d344af8ade5171d3d39
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Logs**

```
`git fetch origin --tags --force --prune` failed exit status 128: fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled
```

**Comment by argo1984** [comment]
Hi together,

i have the same issue with 2.12.X and it seems that the login to the repository works (it is green) but the Projects and Applications are not able to access the credentials.

**Comment by crenshaw-dev** [comment]
For the failing repo, was the `project` field set in the credential Secret?

**Comment by crenshaw-dev** [comment]
+1 to Blake's question, but to anyone who's experiencing this issue. :-)

**Comment by blakepettersson** [comment]
I suspect it's the same thing actually :( An applicationset doesn't have a project; it's admin-scoped. I believe the resolution is exactly the same as for #19587 - having a repo-cred that doesn't have a `project` set.

**Comment by blakepettersson** [comment]
>The downside now is, that the repo creds can now be used by all projects.

Yes, that is true; that was however the same behavior in < 2.12. A workaround for _that_ would be to disallow that source to be used in your `AppProject`s:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: < project-1 >
spec:
  sourceRepos:
    - '!https://gitlab.xxxxx/project-1/deployment.git'
```

**Comment by ChristianCiach** [comment]
I am confused. I am seeing this error after upgrading from `v2.11.7` to `v.2.12.2`, but after reading this and the linked issue, I don't think I should be affected, because my Secret doesn't have a `project` set:

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repocred-gitoops
  namespace: argocd
type: Opaque
data:
  password: base64(somePassword)
  url: base64(https://internal-url/some-group/gitoops.git)
  username: base64(gitlab+deploy-token-62)

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: bootstrap:argoproj.io/AppProject:argocd/egs-external
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/instance: bootstrap
  name: egs-external
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: EGS External Cluster
  destinations:
  - name: egs-external
    namespace: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/tracking-id: bootstrap:argoproj.io/Application:argocd/netshoot
  labels:
    argocd.argoproj.io/instance: bootstrap
  name: netshoot
  namespace: argocd
spec:
  destination:
    name: egs-external
    namespace: default
  project: egs-external
  source:
    path: netshoot
    repoURL: https://internal-url/some-group/gitoops.git
    targetRevision: HEAD
```

I've tried to debug this for hours, but I am none the wiser.

**Comment by blakepettersson** [comment]
@ChristianCiach from what I can see you should indeed be unaffected - does rolling back to 2.11.x solve your issue?

**Comment by ChristianCiach** [comment]
@blakepettersson Yes, downgrading immediately fixes all apps, and upgrading immediately triggers the issue again. Weird..

**Comment by blakepettersson** [comment]
@ChristianCiach are you sure that there are no other repo-creds making use of the same repo url?

**Comment by ChristianCiach** [comment]
@blakepettersson This is a small test cluster. There is a *single* other repo-cred (not technically, they are both `argocd.argoproj.io/secret-type: repository`, not `repocreds`), but it is referencing another project on the same gitlab server.

**Comment by blakepettersson** [comment]
That other `argocd.argoproj.io/secret-type: repository` secret - is it referring to the same repo url?

**Comment by ChristianCiach** [comment]
It is not. It is use for my `bootstrap` application to set up the other AppProjects and Applications. 

Unsurprisingly, deleting this other secret breaks the `bootstrap` app, but doesn't fix all the other apps.

**Comment by blakepettersson** [comment]
@ChristianCiach are you around on the CNCF slack?

**Comment by ChristianCiach** [comment]
@blakepettersson Not yet, but I could change that :) I was just about to leave for vacation for the next three weeks, but this is too interesting to let go. Give me a few minutes to figure out how to join the slack channel.

Btw, the crazy thing is that I can sync the applications just fine! Argo CD picks up the changes from the repo without issues. It's just the UI that shows this error message all the time...

**Comment by ChristianCiach** [comment]
Weird... The error message disappears from the UI as soon as I sync the application, even if there are no changes. I need to do this once for each application, even though they are all synced from the same git repository. But the error message is gone for good after syncing each application once.

**Comment by ChristianCiach** [comment]
This may or may not have something to do with the fact that we moved the gitlab project from one group to another group (on the same server) last week. But we did this way before upgrading Argo CD to v2.12, including updating all `Applications` and `Secrets` to the new repo url. But maybe the old project path was still cached somewhere inside the browser cache...?

Anyway, I seem to be the only one affected by this, so this probably has something to do with dirty caches and the recently moved git repo, so we probably shouldn't think too hard about this. I probably should have started with this information, so I'm sorry about that!

**Comment by moonkaktus** [comment]
So private (project-scoped) repositories now can not be used in other projects, similar to clusters. It seems right, but for clusters we have `permitOnlyProjectScopedClusters` in appProject, so one can disable or enable such behavior per project. Shouldn't such setting exist for repos now too? Take my case:

- I want to set `permitOnlyProjectScopedClusters: true` for user projects and forbid deployments in ArgoCD cluster
- I want users to use applicationSets and applications defined in their repos with yaml

Apps and appsets can only reside in ArgoCD cluster (can be in separate namespace, but still) so I do:
- project for user with `permitOnlyProjectScopedClusters: true`, appset/app repo bound to this project (by user)
-  another supplementary project with `permitOnlyProjectScopedClusters: false`, which has above repo in `sourceRepos` and where master app for this repo is created. This project can not be used by user, only by admin (automated)

With 2.11 this workflow is possible, but with 2.12 master app will throw error, because supplementary project no longer can access repo (it is bound to another project). I think it still possible, because now we have ability to add duplicate repo to supplementary project with same credentials. But it adds another burden of duplicating user-provided credentials, not to mention it looks awful.

Some project setting like `permitOnlyProjectScopedRepositories` will solve such problems at project level, so we don't have to use duplicate repo hacks or permit to use them globally.

**Comment by yevon** [comment]
Same here, I had to downgrade as I having random issues with this message. I use the matrix generator with git files and clusters. I specified the project in the cluster secret as stated in the upgrade instructions, but getting this anyway. The git credentials do also must have the project set in?

**Comment by blakepettersson** [comment]
@yevon in the case of applicationsets you would need to have the `project` parameter _unset_.

**Comment by blakepettersson** [comment]
@moonkaktus having a `permitOnlyProjectScopedRepositories` field for the project is not a bad idea, it has been previously proposed but hasn't been implemented.  

In that case it would mean that for a given project it would not be allowed to use globally scoped repositories?

**Comment by moonkaktus** [comment]
@blakepettersson I think global repositories should be allowed to every project, as now. But restriction to use only project-scoped repositories of one project should be switchable for that project (like `permitOnlyProjectScopedClusters`). 
This way we can have restricted projects where users can add their repos, and not allowed to use repos of other projects, but still have ability to create technical projects without such restriction.

**Comment by yevon** [comment]
I do use ApplicationSet, but I specify the project for the Application spec itself, not for the ApplicationSet spec. Do I must unset the Application project? I just have this but it was not working:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
  labels:
    name: test-appset-label
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git:
              repoURL: 'https://testurl.com'
              revision: "{{metadata.annotations.targetRevision}}"
              files:
              - path: "example/path"
            selector:
                  matchExpressions:
                    - key: client.nodeBackend
                      operator: In
                      values:
                        - "true"                  
  template:
    metadata:
      name: "application-name"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=false
        argocd-image-updater.argoproj.io/image-list: app=registry.gitlab.yevon.es/nasia-projects/{{client.backendProject}}-node
        argocd-image-updater.argoproj.io/app.force-update: "true"
        argocd-image-updater.argoproj.io/write-back-method: "git"
        argocd-image-updater.argoproj.io/git-branch: "git-source:git-destination"
        argocd-image-updater.argoproj.io/app.ignore-tags: "latest"
      labels:
        name: test-app-label
    spec:
      project: my-project
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "namespace"
```
