### ISSUE TITLE
ApplicationSet does not generate any apps if there are 2 or more git generators and there is no credentials for one of them

### ISSUE THREAD

**Issue by BoyFromDubai** [argoproj/argo-cd#19586]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

ApplicationSet cannot create applications, if there are multiple git generators and no credentials for one of private repos

**To Reproduce**

Create an appset with 2 git generators for 2 repos and without providing any credentials for one of them.

**Expected behavior**
AppSet controller has to create apps at least for accessible repos, but still displaying an unhealthy status, saying that it cannot auth in one of given repos (It would be great to provide repo url for which it has not credentials)

**Screenshots**

**Version**

```shell
v2.12.1
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by christianh814** [comment]
Do you have an example YAML that is known to fail?

**Comment by BoyFromDubai** [comment]
Found a bit interesting bug when I was trying to create an appset with the bug described above
Created this appset:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ccc
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - smth: bbb
        source:
          repoURL: https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: 18.1.9
          helm:
            releaseName: bbb
      - smth: aaa
        sources:
          repoURL: https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: 18.1.9
          helm:
            releaseName: aaa
  template:
    metadata:
      name: '{{.smth}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 18.1.9
        helm:
          releaseName: aaa
      destination:
        name: in-cluster
        namespace: default
  templatePatch: |
      spec:
      {{- if (hasKey . "sources") }}
      sources:
        {{ .sources | toYaml | nindent 4 }}
      {{- else if (hasKey . "source") }}
      source:
        {{ .source | toYaml | nindent 4 }}
      {{- else }}
      source: {}
      {{- end }}
```
And when got into the web interface, got what's in the picture
![image](https://github.com/user-attachments/assets/61ac4eba-1189-4d61-aa03-91b5985cc4a6)

Talking about the main bug it's a bit difficult to reproduce with default examples of using appset the described bug
But we have and app of apps pattern, where appset generates all applications according to a git repository like this:
An AppSet:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-generator
spec:
  generators:
    - git:
        files:
          - path: apps/**.yaml
        repoURL: https://somerepo.git
        requeueAfterSeconds: 5
        revision: HEAD
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy/automated
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: >-
        {{ printf "%s-%s" ((.path.filename | split ".")._0 | replace "_" "-")
        (.path.segments | rest | join "-") | lower }}-infra
    spec:
      destination: {}
      project: infra
  templatePatch: |
    metadata:
      annotations:
        {{ dig "annotations" nil . | toYaml | nindent 4 }}

      labels:
        {{ dig "labels" nil . | toYaml | nindent 4 }}
        
    spec:
      {{- if (hasKey . "sources") }}
      sources:
        {{ .sources | toYaml | nindent 4 }}
      {{- else if (hasKey . "source") }}
      source:
        {{ .source | toYaml | nindent 4 }}
      {{- else }}
      source: {}
      {{- end }}

      destination:
        {{ .destination | toYaml | nindent 4 }}

      info:
        {{ dig "info" nil . | toYaml | nindent 4 }}

      syncPolicy:
        automated:
        {{ dig "syncPolicy" "automated" nil . | toYaml | nindent 6 }}
        syncOptions:
        {{ dig "syncPolicy" "syncOptions" nil . | toYaml | nindent 6 }}
        managedNamespaceMetadata:
          labels:
            {{- if (dig "syncPolicy" "managedNamespaceMetadata" "labels" nil .) }}
            {{ .syncPolicy.managedNamespaceMetadata.labels | toYaml | nindent 8 }}
            {{- end }}
            project: some-project

          annotations:
            {{ dig "syncPolicy" "managedNamespaceMetadata" "annotations" nil . | toYaml | nindent 8 }}

      ignoreDifferences:
        {{ dig "ignoreDifferences" nil . | toYaml | nindent 4 }}
```

And in repo https://somerepo.git smth like this:
apps/smth/app1.yaml

```
source:
  repoURL: https://charts.bitnami.com/bitnami
  chart: nginx
  targetRevision: 18.1.9
  helm:
    releaseName: nginx

syncPolicy:
  preserveResourcesOnDeletion: true
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
destination:
  namespace: argo-testing
  name: in-cluster
```

And if you'll create multiple apps like apps/smth/app2.yaml with smth like this:
```
sources:
  repoURL: https://charts.bitnami.com/bitnami
  chart: nginx
  targetRevision: 18.1.9
  helm:
    releaseName: nginx

syncPolicy:
  preserveResourcesOnDeletion: true
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
destination:
  namespace: argo-testing
  name: in-cluster
```
AppSet will fail and all other changes in the repo with all applications will be ignored
Tested in argo v2.12.2, but I think it doesn't matter
