### ISSUE TITLE
Sync issue with argo-cd helm chart 7.4.x

### ISSUE THREAD

**Issue by jascsch** [argoproj/argo-cd#19582]
Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `argocd version`.

**Describe the bug**

There is a sync issue with argocd version v2.12.1 so that apps are stuck in "OutOfSync" status.

**To Reproduce**

use the following manifest and try to sync the dapr app.

```
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dapr
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - kind: Secret
    name: dapr-trust-bundle
    namespace: dapr
    jsonPointers:
      - /data
sources:
  - repoURL: 'https://dapr.github.io/helm-charts/'
    targetRevision: 1.11.1
    helm:
      valueFiles:
        - $values/tools/dapr/values.yaml
      releaseName: dapr
      skipCrds: true
    chart: dapr
  - repoURL: 'https://git.xxx.com/org/gitops-cluster-dev.git'
    targetRevision: HEAD
    ref: values
```

**Expected behavior**

The sync status should be "Synced" instead of "OutOfSync"
The sync works perfectly fine with helm chart version 7.3.x

**Screenshots**

![image](https://github.com/user-attachments/assets/a720e524-dbdd-4890-a770-23fcd7ef0f87)

**Version**

```
argocd v2.12.1
helm chart argo-cd-7.4.4
```

**Logs**

```
no relevant application logs available.
```
