### ISSUE TITLE
couldn't find cmp-server plugin with name "helmchart-ytt" supporting the given repository

### ISSUE THREAD

**Issue by mdavid01** [argoproj/argo-cd#19614]
Checklist:

* [X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.  
* [X] I've included steps to reproduce the bug.  
* [X] I've pasted the output of `argocd version`.  

**Describe the bug**

Without adequate documentation and end-to-end examples, we are unable to resolve the error message below:
THE ERROR MESSAGE (apparently from application chart)
time="2024-08-20T19:16:33Z" level=error msg="finished unary call with code **Unknown**" dt.entity.host=HOST-D099CC1C537BFD52 dt.entity.host_group=HOST_GROUP-E15501BCEE3919CB dt.entity.process_group=PROCESS_GROUP-BDC473FD376E7E12 dt.entity.process_group_instance=PROCESS_GROUP_INSTANCE-A1F3853A19F3E80E dt.host_group.id=ez-container-registry-dev dt.span_id=664a429a231c6727 dt.trace_id=35ebe2a8e0dc8f3761348ab3dad9676a dt.trace_sampled=true error="Manifest generation error (cached): plugin sidecar failed. couldn't find cmp-server plugin with name \"helmchart-ytt\" supporting the given repository" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-08-20T19:16:33Z" grpc.time_ms=802.08 span.kind=server system=grpc

**To Reproduce**

Using the source code below as a model for the configmap, configmapplugin, repo server sidecar and application, create an end-to-end git repo example of an application using YTT plugins and HELM. (YTT may not be a specific factor in the error message so any plugin may reproduce the result.)

Please address questions below and show relevant ArgoCD 2.10.0 and Kubernetes outputs.  

**Expected behavior**

Expecting to get no error messages about locating the cmp-server plugin.

**Version**
2.10.1

```shell
see below
```

**Logs**
```
see below
```
**Details of outputs and source code:  **
```
We're struggling with plugin sidecar for multiple weeks with Argocd 2.10.  We cannot tell if there's a bug or missing critical documentation. If the documentation clearly answers the questions below, pls direct us to the documented answers.  Error message below implies the application plugin cannot locate it's corresponding plugin or container (helmchart-ytt-plugin) 
-----------------------------------------------------
THE ERROR MESSAGE (apparently from application chart)
time="2024-08-20T19:16:33Z" level=error msg="finished unary call with code Unknown" dt.entity.host=HOST-D099CC1C537BFD52 dt.entity.host_group=HOST_GROUP-E15501BCEE3919CB dt.entity.process_group=PROCESS_GROUP-BDC473FD376E7E12 dt.entity.process_group_instance=PROCESS_GROUP_INSTANCE-A1F3853A19F3E80E dt.host_group.id=ez-container-registry-dev dt.span_id=664a429a231c6727 dt.trace_id=35ebe2a8e0dc8f3761348ab3dad9676a dt.trace_sampled=true error="Manifest generation error (cached): plugin sidecar failed. couldn't find cmp-server plugin with name \"helmchart-ytt\" supporting the given repository" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2024-08-20T19:16:33Z" grpc.time_ms=802.08 span.kind=server system=grpc
-----------------------------------------------------
QUESTIONS:
1. Exactly what from our source code (below) provides the input to the plugin search and what object, file or file text is the source code input  expected to match?
2. In the REPO-SERVER pod's description (see below), in the plugin section for 'helmchart-ytt'
  a. What is the 'Environment' parameter?
  b. Where does its value come from? 
  c. Is it involved in locating the cmp-server plugin?
3. What is the 'given repository' and where does that value come from (and why is it not presented in the error message)?
4. If the error is produced by the application searching for matching plugin, what's the purpose/role of the configmapplugin discover statement?
5. In our setup (see source code below), the application source path is ./apps/harbor.  The actual git repo path containing Application plugin info is a template in path: gitops\shared\harbor\templates\harbor.yaml.  Values for the template are provided from git folder gitops\tkg-pub-east-dev\harbor.yaml.  What path should be used for the configmapplugin discover statement? 
-----------------------------------------------------
CONTAINER helmchart-ytt-plugin /home/argocd/cmp-server/config/plugin.yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: helmchart-ytt
spec:
  kustomize.buildOptions: --enable-helm
  init:
    command: ["/bin/sh", "-c"]
    args:
    - >-
      export PATH=$PATH:/custom-binaries &&
      ["helm dependency build || true"]
  generate:
    command: ["/bin/sh", "-c"]
    args:
    - echo "$ARGOCD_ENV_HELM_VALUES" | helm template --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE --repo $ARGOCD_ENV_HELM_REPO --version $ARGOCD_ENV_HELM_CHART_VERSION $ARGOCD_ENV_HELM_CHARTNAME $ARGOCD_ENV_HELM_ARGS -f - --include-crds > ./qltz-deployment.yaml && echo "$ARGOCD_ENV_YTT_VALUES" | /custom-binaries/ytt --ignore-unknown-comments -f ./qltz-deployment.yaml -f - $ARGOCD_ENV_YTT_OPTIONS
  discover:
    filename: "./gitops/shared/harbor/templates/harbor.yaml"
-----------------------------------------------------
POD argocd-argo-cd-repo-server-.... DESCRIBE PLUGIN SECTION
  helmchart-ytt-plugin:
    Container ID:  containerd://dd4a22bcf6f651a89e87f429364897b9aeade55ac609b6b3d6ebd21a055c6d72
    Image:         quay.io/argoproj/argocd:v2.10.0
    Image ID:      quay.io/argoproj/argocd@sha256:13cdc24e2218bb74fe6ec988c8045c7afc3043f24601e33b20ee78b787440baa
    Port:          <none>
    Host Port:     <none>
    Command:
      /var/run/argocd/argocd-cmp-server
    State:          Running
      Started:      Wed, 21 Aug 2024 04:20:18 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>  #  WHERE DOES THIS VALUE COME FROM? IS IT PART OF THE APPLICATION MATCH PARAMETERS?
    Mounts:
      /custom-binaries from custom-binaries (rw)
      /home/argocd/cmp-server/config/plugin.yaml from helmchart-ytt (rw,path="plugin.yaml")
      /home/argocd/cmp-server/plugins from plugins (rw)
      /tmp from helmchart-yttp-tmp (rw)
      /var/run/argocd from var-files (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lppbm (ro)
-----------------------------------------------------
CONTAINER helmchart-ytt-plugin /var/run/argocd
-rwxr-xr-x 1 argocd argocd 160203923 Aug 21 08:20 argocd-cmp-server
-----------------------------------------------------
CONTAINER helmchart-ytt-plugin /home/argocd/cmp-server/plugins
srwxr-xr-x 1 argocd argocd 0 Aug 21 08:20 harbor-applicationset.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 08:20 helm-kustomize.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 08:20 helm-ytt.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 08:20 helmchart-kustomize.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 08:20 helmchart-ytt.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 08:20 output-environmentvariables.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 08:20 ytt.sock
-----------------------------------------------------
POD LIST
NAME                                                       READY   STATUS    RESTARTS   AGE
argocd-argo-cd-repo-server-785c4c578c-67vgc                8/8     Running   0          11h
argocd-argo-cd-repo-server-785c4c578c-94m9d                8/8     Running   0          11h
argocd-argo-cd-repo-server-785c4c578c-kq75x                8/8     Running   0          11h
argocd-argo-cd-repo-server-785c4c578c-nc6s2                8/8     Running   0          11h
argocd-argo-cd-repo-server-785c4c578c-tr44v                8/8     Running   0          11h
-----------------------------------------------------
CONTAINER LIST IN EACH OF THE ABOVE PODS
helm-kustomize-plugin 
helmchart-kustomize-plugin 
helm-ytt-plugin 
helmchart-ytt-plugin 
ytt-plugin 
harbor-applicationset-plugin 
output-environmentvariables-plugin 
repo-server
-----------------------------------------------------
CONTAINER REPO-SERVER FOLDERS
app  bin  boot  dev  etc  helm-working-dir  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
-----------------------------------------------------
CONTAINER REPO-SERVER helm-working-dir
empty
-----------------------------------------------------
CONTAINER REPO-SERVER /home/argocd/cmp-server/plugins
srwxr-xr-x 1 argocd argocd 0 Aug 21 07:42 harbor-applicationset.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 07:42 helm-kustomize.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 07:42 helm-ytt.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 07:42 helmchart-kustomize.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 07:42 helmchart-ytt.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 07:42 output-environmentvariables.sock
srwxr-xr-x 1 argocd argocd 0 Aug 21 07:42 ytt.sock
-----------------------------------------------------
CONTAINER  helmchart-ytt-plugin folders
app  bin  boot  custom-binaries  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
-----------------------------------------------------
CONTAINER  helmchart-ytt-plugin /custom-binaries folder
ytt (the executable)
-----------------------------------------------------
CONTAINER  helmchart-ytt-plugin /usr/local/bin folder
-rwxr-xr-x 1 root root 160203923 Feb  6  2024 argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-application-controller -> /usr/local/bin/argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-applicationset-controller -> /usr/local/bin/argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-cmp-server -> /usr/local/bin/argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-dex -> /usr/local/bin/argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-k8s-auth -> /usr/local/bin/argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-notifications -> /usr/local/bin/argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-repo-server -> /usr/local/bin/argocd
lrwxrwxrwx 1 root root        21 Feb  6  2024 argocd-server -> /usr/local/bin/argocd
-rwxr-xr-x 1 root root       203 Feb  6  2024 entrypoint.sh
-rwxr-xr-x 1 root root       934 Feb  6  2024 git-verify-wrapper.sh
-rwxr-xr-x 1 root root       215 Feb  6  2024 gpg-wrapper.sh
-rwxr-xr-x 1 root root  50655232 Feb  6  2024 helm
-rwxr-xr-x 1 root root  15015936 Feb  6  2024 kustomize
lrwxrwxrwx 1 root root        28 Feb  6  2024 uid_entrypoint.sh -> /usr/local/bin/entrypoint.sh
-----------------------------------------------------
```
Gitlab REPO SOURCE CODE AS VIEWED IN ARGOCD: 
From Application generated from Git as viewed in Argocd

```
project: .....
source:
  repoURL: 'https://gitlab..../deployment.git'
  path: apps/harbor/
  targetRevision: develop
  plugin:
    name: helmchart-ytt
    env:
      - name: HELM_REPO
        value: helm.goharbor.io
      - name: HELM_CHART_VERSION
        value: 1.14.1
      - name: HELM_CHARTNAME
        value: harbor
      - name: YTT_VALUES
        value: |
          #@data/values
          ---
          url: harbor-dev...
          lmregistryURL: 
          appName: harbor-dev
          istioGateway: harbor-dev
          docsUrl: docs.harbor-dev...
          aquaUrl: https://harbor...
          asapUserId: 321
          fjordFqdn: fjord-dev...
          s3Bucket: ...
          smoketestsImages: ext.hub.docker.com/library/busybox:latest
      - name: YTT_OPTIONS
        value: '-f ./overlays -f ./tkg-pub-east-dev'
      - name: HELM_VALUES
        value: |
-----------  HARBOR REGISTRY SUBSTITUTE VALUES --------------------        
destination:
  server: 'https://kubernetes.default.svc'
  namespace: harbor-dev
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
  retry:
    limit: 1
ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
      - .spec.template.metadata.annotations
      - .spec.replicas

```
======================================  
**Plugin ConfigMap for 'helmchart-ytt' generated from Git as viewed in Argocd**
======================================  
```
apiVersion: v1
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helmchart-ytt
    spec:
      kustomize.buildOptions: --enable-helm      
      init:
        command: ["/bin/sh", "-c"]
        args:
        - >-
          export PATH=$PATH:/custom-binaries &&
          ["helm dependency build || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args:
        - echo "$ARGOCD_ENV_HELM_VALUES" | helm template --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE --repo $ARGOCD_ENV_HELM_REPO --version $ARGOCD_ENV_HELM_CHART_VERSION $ARGOCD_ENV_HELM_CHARTNAME $ARGOCD_ENV_HELM_ARGS -f - --include-crds > ./qltz-deployment.yaml && echo "$ARGOCD_ENV_YTT_VALUES" | /custom-binaries/ytt --ignore-unknown-comments -f ./qltz-deployment.yaml -f - $ARGOCD_ENV_YTT_OPTIONS
      discover:
        filename: "./gitops/shared/harbor/templates/harbor.yaml"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: helmchart-ytt
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: argocd-customizations
  name: helmchart-ytt
  namespace: argocd
```
======================================  
**Repo-Server (Sidecar) generated from Git as viewed in Argocd** 
    this includes several other plugins with similar command, mounts, and volume construct
======================================  
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-customizations
  name: argocd-argo-cd-repo-server
  namespace: argocd
spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd-argo-cd
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: argocd-argo-cd
        app.kubernetes.io/name: argocd-repo-server
    spec:
      automountServiceAccountToken: true
      containers:
--------------------- OTHER YTT PLUGINS --------------
        - command:
            - /var/run/argocd/argocd-cmp-server
          image: 'quay.io/argoproj/argocd:v2.10.0'
          imagePullPolicy: IfNotPresent
          name: helmchart-ytt-plugin
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /custom-binaries
              name: custom-binaries
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              name: helmchart-ytt
              subPath: plugin.yaml
            - mountPath: /tmp
              name: helmchart-yttp-tmp
......
Volumes:
      volumes:
        - configMap:
            name: helm-kustomize
          name: helm-kustomize
        - configMap:
            name: helmchart-kustomize
          name: helmchart-kustomize
        - configMap:
            name: helm-ytt
          name: helm-ytt
        - configMap:
            name: helmchart-ytt
          name: helmchart-ytt
        - configMap:
            name: ytt
          name: ytt
        - configMap:
            name: harbor-applicationset
          name: harbor-applicationset
        - configMap:
            name: output-environmentvariables
          name: output-environmentvariables
```
