### ISSUE TITLE
Add more information for enabling the Terminal in Argo CD

### ISSUE THREAD

**Issue by nitishfy** [argoproj/argo-cd#19616]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
While going through the [Web based Terminal docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/#web-based-terminal) I found it a little difficult and time consuming trying to [enable the Terminal](https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/#enabling-the-terminal). The docs are great and simple, however, it is better to add the manifest examples for the users that shows them how will the fields set look like, how the RBAC rules is going  to look like in the configmap manifest once added.  Eg. Add these manifests in the docs

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: <namespace>  # Replace <namespace> with your actual namespace
data:
  exec.enabled: "true"
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-server-role
  namespace: <namespace>  # Replace <namespace> with your actual namespace
rules:
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
```

**Version**

```shell
argocd: v2.11.7+e4a0246
  BuildDate: 2024-07-24T10:10:59Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.12
  Compiler: gc
  Platform: linux/amd64
```
