### ISSUE TITLE
Can not sync application with some securityContext

### ISSUE THREAD

**Issue by artemus717** [argoproj/argo-cd#19638]
Checklist:

* [ √ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ √ ] I've included steps to reproduce the bug.
* [ √ ] I've pasted the output of `argocd version`.

**Describe the bug**

Can not sync application with some securityContext, eg allowPrivilegeEscalation  capabilities  privileged  readOnlyRootFilesystem

**To Reproduce**

Sync applications with these config

securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
      - ALL
  privileged: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0

allowPrivilegeEscalation capabilities  privileged  readOnlyRootFilesystem are not synced.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/61161da8-20c3-4d7e-82c2-e9f87e4e4754)

**Version**
2.8.20

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by nitishfy** [comment]
Hi @artemus717 , thanks for raising this issue. I tried to reproduce this and my application gets in sync state inspite of using a security context. Here is the deployment manifest that I used:

```
\apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - ALL
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          ports:
            - containerPort: 80
```
![image](https://github.com/user-attachments/assets/708872ca-ea7e-410b-8111-fd418454caff)
