### ISSUE TITLE
unclear warning about deprecated plugins "spec.plugin.name is set"

### ISSUE THREAD

**Issue by Sven1410** [argoproj/argo-cd#19643]
we use argocd v2.10.9, we migrated all our plugins to sidecar-plugins (some versions ago).
 
 We still get this warning:
 
 `time="2024-08-21T13:35:05Z" level=warning msg="spec.plugin.name is set, which means this Application uses a plugin installed in the argocd-cm ConfigMap. Installing plugins via that ConfigMap is deprecated in Argo CD v2.5. Starting in Argo CD v2.6, this Application will fail to sync. Contact your Argo CD admin to make sure an upgrade plan is in place. More info: https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.4-2.5/"
time="2024-08-21T13:35:05Z" level=warning msg="The following Applications use deprecated plugins:  ...`

this warning looks not correct:
It was introduced here:
https://github.com/argoproj/argo-cd/pull/10341/files
and it just checks if a plugin is named - which is still allowed

```
if app.Spec.Source.Plugin != nil && app.Spec.Source.Plugin.Name != "" {
	log.Warnf(argocommon.ConfigMapPluginCLIDeprecationWarning)
}
```

the plugins are detected and work as expected.
also the comment here:
https://github.com/argoproj/argo-cd/pull/11341/files#diff-16370636772309512011fc9134f70595151d74e71ce3aa6eb71048fd088dc73eR337
says we can specify the name.

our apps look like:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   ...
spec:
  ...
  source:
    path: .
    plugin:
      env:
        - name: RELEASE_NAME
          value: something
      name: kube_apply
	  ...

```
