### ISSUE TITLE
ArgoCD: Issue with Adding Repo-Creds for Azure DevOps Collection Projects

### ISSUE THREAD

**Issue by Umair-Dehlvi** [argoproj/argo-cd#19645]
I'm encountering an issue with ArgoCD when trying to add repository credentials for Azure DevOps collection projects. The repo-creds configuration is not working as expected for repositories within different collection projects.

### Steps to Reproduce

1. Add repo-creds for the Azure DevOps collection project CollectionA:

        apiVersion: v1
        kind: Secret
        metadata:
          name: azure-collection-a-repos-creds
          namespace: argocd
          labels:
            argocd.argoproj.io/secret-type: repo-creds
        stringData:
          url: https://dev.azure.com/yourorganization/CollectionA
          username: <username>
          password: <password>

2. Add repo-creds for the Azure DevOps collection project CollectionB:

        apiVersion: v1
        kind: Secret
        metadata:
          name: azure-collection-b-repos-creds
          namespace: argocd
          labels:
            argocd.argoproj.io/secret-type: repo-creds
        stringData:
          url: https://dev.azure.com/yourorganization/CollectionB
          username: <username>
          password: <password>

3. Attempt to sync repositories from CollectionA or CollectionB in ArgoCD.

### Expected Behavior

ArgoCD should authenticate successfully with the provided credentials and be able to sync the repositories from CollectionA and CollectionB.

### Actual Behavior
ArgoCD fails to authenticate or sync the repositories from the Azure DevOps collection projects specified in repo-creds.

Example URLs:

    Collection Project A: https://dev.azure.com/yourorganization/CollectionA/_git/RepositoryA
    Collection Project B: https://dev.azure.com/yourorganization/CollectionB/_git/RepositoryB

### Environment:

    ArgoCD Version: v2.8.21
    Kubernetes Version: v1.29.0

**Comment by TimLinsenmayer** [comment]
Hi there,
I recently added our repo credentials for Azure DevOps Git-Repositories of my org. Not sure if its identical or comparable to Azure DevOps collection projects in your case (but it seems like it , given the url).
I managed to do it using this template (in production we pull the values in using a CSI plugin, but it shouldn't matter here):
```yaml
 apiVersion: v1
 kind: Secret
 metadata:
   name: argocd-git-credentials
   namespace: argocd
   labels:
     argocd.argoproj.io/secret-type: repo-creds
 stringData:
   type: git
   url: https://dev.azure.com/yourorganization/CollectionB/_git
   username: <username>
   password: <password>
```
I just tested it on ArgoCD v2.12.2 & Kubernetes v1.29.7 and it works without any issues. My guess is that you are missing the `type: git` as per [the docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials).
