### ISSUE TITLE
labels in managedNamespaceMetadata not being added to namespace

### ISSUE THREAD

**Issue by lknite** [argoproj/argo-cd#19674]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

**Describe the bug**

labels normally applied to the created namespace which are specified in managedNamespaceMetadata are not being applied to the namespace

**To Reproduce**

```
project: addons
source:
  repoURL: https://github.com/cockroachdb/cockroach-operator.git
  path: install
  targetRevision: 2.13.0
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://10.1.2.3:6443
  namespace: cockroach-operator-system
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/audit: restricted
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/warn: baseline
```

**Expected behavior**

labels specified to be applied to the namespace

**Version**
argocd version:  v2.12.1+26b2039

**Screenshot**
![image](https://github.com/user-attachments/assets/be9c2284-ae7c-42eb-b646-85299031f5ce)
![image](https://github.com/user-attachments/assets/a1e76b8b-647b-4c1f-9a82-f74112592eaa)
