### ISSUE TITLE
ignoreDifference not works with app in app pattern

### ISSUE THREAD

**Issue by keyolk** [argoproj/argo-cd#19680]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to ignore the `TargetRevision` field if the `Application` has a label `ignoreTargetRevision: "true"`.
But from the Argocd UI, it always catches the diff.

**To Reproduce**

From the parent application

```yaml
spec:
  ignoreDifferences:
  - group: argoproj.io/v1alpha1
    jqPathExpressions:
    - . | select(.metadata.labels.ignoreTargetRevision == "true") | .spec.source.targetRevision
    kind: Application
```

And the child
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    ignoreTargetRevision: "true"
```

Make it sure that if the child app has proper states.

```bash
$ cat child.yaml | yaml2json | jq ' . | select(.metadata.labels.ignoreTargetRevision == "true").spec.source.targetRevision'
"CPLAT-3112"
```

**Expected behavior**

The diff from `targetRevision` should be ignored from the parent application.

**Screenshots**

![image](https://github.com/user-attachments/assets/6288c7c6-36df-4f78-80fe-16f79d61d5e2)

**Version**

```shell
argocd: v2.11.1+9f40df0
  BuildDate: 2024-05-21T22:43:41Z
  GitCommit: 9f40df0c29eca7e45a73f802f033dfd1ed0068e3
  GitTreeState: clean
  GoVersion: go1.22.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.11.5+c4b283c
  BuildDate: 2024-07-15T17:39:54Z
  GitCommit: c4b283ce0c092aeda00c78ae7b3b2d3b28e7feec
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

No suspected logs I can see
