### ISSUE TITLE
[ApplicationSet] scmProvider generator: webhook support for topic/label updates

### ISSUE THREAD

**Issue by ejhayes** [argoproj/argo-cd#19689]
# Summary

Add webhook support for GitHub topic updates. This can be specified in the `scmProvider` generator but cannot receive updates via webhook notifications.

# Motivation

Being able to add/remove apps based on topic is very useful but updates are often slow. Sure we could increase polling frequency but it'd be even more lightweight to add support for `repository` events!

# Proposal
Here's an example `ApplicationSet` that uses a [`labelMatch`](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/#filters) filter.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
spec:
  generators:
  - scmProvider:
      filters:
        - labelMatch: someLabel # corresponds to repository topic
      github:
        organization: myOrg
        allBranches: false
        appSecretName: my-github-repo-secret
  template:
    metadata:
      name: '{{ repository }}-{{ branch }}'
    spec:
      destination:
        name: in-cluster
        namespace: default
      source:
        path: '.'
        repoURL: '{{ url }}'
        targetRevision: '{{ sha }}'
      project: default
```

The associated github app sends `repository` events (specific `created` and `updated` actions) when repository topics change (I'm using `label` and `topic` interchangeably here). In the github app configuration the event is called `repository`:

<img width="388" alt="image" src="https://github.com/user-attachments/assets/2c861f6a-1e2f-49a4-aa45-08aa127c320b">

Here's a sample event when I add or remove a topic from a repo (shortened for brevity):

```
{
  "event": "repository",
  "payload": {
    "action": "created|edited",
    "changes": {
      "topics": {
        "from": []
      }
    },
    "repository": {
      "topics": [] /* this is what we care about */
    },
    "organization": {},
    "sender": {},
    "installation": {}
  }
}
```

And the logs from the applicationset controller show that the event is unsupported:

```
argocd-applicationset-controller-*** time="2024-08-26T23:27:08Z" level=info msg="Webhook processing failed: event not defined to be parsed"
```

Adding support for this event looks like it could go here:
https://github.com/argoproj/argo-cd/blob/master/applicationset/webhook/webhook.go#L164C3-L164C10

More info about the `repository` object (we only care about `edited` and `created` actions):
- Created: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=created#repository
- Edited: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=edited#repository
- Repository object: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository
