### ISSUE TITLE
Extensions don't immediately get updated after upgrading the version

### ISSUE THREAD

**Issue by daniddelrio** [argoproj/argo-cd#19696]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

See: https://argo-cd.readthedocs.io/en/stable/developer-guide/extensions/ui-extensions/

We use the `argocd-extension-installer` image to install an extension. I upgraded the version of my tar file in the `EXTENSION_URL` env var, and upon checking the logs I verified that the correct and updated tar file was fetched. However, after checking `my-argo-domain.com/extensions.js`, the extension.js file is outdated.

Based on the logic of this [code block here](https://github.com/argoproj/argo-cd/blob/9af0ff5233ab4eb5cd87c24d5ea05bf92b1b4294/server/server.go#L1088-L1107) to serve the extensions and the logic of the [installer image](https://github.com/argoproj-labs/argocd-extension-installer/blob/main/install.sh), I know that extensions.js is derived from the `/tmp/extensions/resources/` directory which the installer populates during the instantiation phase. I checked that directory and that directory for sure has the updated assets, but extensions.js doesn't, so my guess is that there's something wrong with the logic of serving extensions. Maybe something to do with caching? 

Note that we have the `EnableGZip` option enabled.

**To Reproduce**

Let's say you have this configured:
```
initContainers:
  - name: my-extension
    image: quay/argoprojlabs/argocd-extension-installer:v0.0.1
    env:
      - name: EXTENSION_URL
        value: https://my-link-to-my-cdn.com/v1.0/extension.tar
    volumeMounts:
      - name: extensions
        mountPath: /tmp/extensions/
```

1. Make changes to your extension
2. Update the version in EXTENSION_URL in your server deployment resource
3. Rollout the new deployment
4. Check if your changes were reflected immediately

**Expected behavior**

Changes should immediately be reflected after the new deployment is rolled out. Instead, the server seems to use an older version of the extensions.js file (presumably from a cache). Not sure where the cache comes from, but it would be nice to disable this so that changes are immediately reflected, making it easier for testing purposes.

**Version**

v2.11.5
