### ISSUE TITLE
ignoreApplicationDifferences in ApplicationSet does not work with two identical repos

### ISSUE THREAD

**Issue by snirmusayof** [argoproj/argo-cd#19692]
**Describe the bug**
 
 I have ApplicationSet with ignoreApplicationDifferences  
 
 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: moon
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            moon: "true"
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.sources[] | select(.repoURL == "https://bitbucket.org/controlup-code/moon.git").targetRevision
        - .spec.sources[] | select(.repoURL == "https://charts.aerokube.com").targetRevision
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{name}}-moon'
    spec:
      syncPolicy:
        # automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - FailOnSharedResource=true
          - PrunePropagationPolicy=orphan
          - CreateNamespace=true
      project: devops-infra
      sources:
        - chart: moon2
          repoURL: https://charts.aerokube.com
          targetRevision: 2.7.1
          helm:
            releaseName: moon
            valueFiles:
              - $values/values.yaml
              - $values/{{name}}.yaml
        - repoURL: https://repo-x.git
          targetRevision: HEAD
          ref: values
        - repoURL: https://repo-x.git
          targetRevision: HEAD
          path: "service-monitor"
      destination:
        server: '{{server}}'
        namespace: moon

``` 
when I add to the spec more sections of the same repo

   ```
         - repoURL:  https://repo-x.git
           targetRevision: HEAD
           path: "service-monitor"
 ```

 I get an error in Argo,
 
![image](https://github.com/user-attachments/assets/13678fe7-48d7-407f-b367-71a35582e975)

if I comment ignoreApplicationDifferences the problem is resolved.

it happens when there are ignoreApplicationDifferences and 2 repo with the same URL.
 
**To Reproduce**

Create an ApplicationSet with ignoreApplicationDifferences of targetRevision and  2 repos with the same URL (like in the example).

**Expected behavior**

I expected that the ignoreApplicationDifferences support in 2 repo with the same URL

**Version**

```shell
v2.11.1
```

**Logs**

```
spec.source.targetRevision is required if the manifest source is a helm chart 
```

**Comment by andrey-parkhomets** [comment]
Using latest argocd (stable 2.14.8) installed via helm chart.

Could be related to that issue other observation:
I'm unable re-define `targetRevision` for single source application if it parent appset (with rollingSync) has next:
```
    ignoreApplicationDifferences:

      - name: my-argocd-application
        jqPathExpressions:
          - .spec.syncPolicy
          - .spec.sources[]|.targetRevision
          - .spec.sources.targetRevision
      - jqPathExpressions:
          - .spec.syncPolicy
          - .spec.sources[]|.targetRevision
          - .spec.sources.targetRevision
```
only works `jsonPointers`
```
    ignoreApplicationDifferences:

      # for single source application only jsonPointers works
      - jsonPointers:
          - /spec/source/targetRevision
```
if convert single sourced application to multisource above works.

i.e. 
```
  sources:
    - chart: ....
```
