### ISSUE TITLE
SyncPolicy in ApplicationSet template not propagated properly in Application

### ISSUE THREAD

**Issue by ypereirareis** [argoproj/argo-cd#19726]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

## Hello ! And thanks for this awesome tool ArgoCD.

**Describe the bug**

SyncPolicy in ApplicationSet template not propagated properly in Application

**To Reproduce**

* ApplicationSet template part

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{$namespace}}"
spec:
  template:
    metadata:
      ...
    spec:
      destination:
        ...
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      project: "{{$namespace}}"
      sources:
        - helm:
            ...
```

* **Generated**  Application

```yaml
project: argocd
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated: {}
sources:
  - ...
```

So the application is always in autoSync mode and so always auto sync :smile_cat: 

**Expected behavior**

* **Generated**  Application

```yaml
project: argocd
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
sources:
  - ...
```

**Version**

```shell
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```
