### ISSUE TITLE
ArgoCD v2.12 introduces newer git which enforces directory ownership but ArgoCD has no way to declare safe.directories 

### ISSUE THREAD

**Issue by pre** [argoproj/argo-cd#19727]
**Describe the bug**

ArgoCD v2.12 updates git to 2.43.0 which enforces the directory ownership match with the effective user id. In the command line environment declaring a git `safe.directory` tells git to accept a directory, but Git executed by ArgoCD does not respect /home/argocd/.gitconfig

```bash
argocd@argocd-repo-server-8dfb95f45-rm2vk:~$ cat ~/.gitconfig
[safe]
	directory = /usr/local/*
argocd@argocd-repo-server-8dfb95f45-rm2vk:~$ git --version
git version 2.43.0
```

## Context

In one of our environments, we include a certain version of manifests into the argocd-repo-server pod. The overall purpose is to serve a fixed set of manifests from the argocd-repo-server filesystem without a dependency to any external version control system. (The business purpose is somewhat more complex but it's not relevant here.)

Using an init container, files are copied from this manifest container image to a shared volume, which is then mounted by argoocd-repo-server. The Application manifests then defines `repoURL: /usr/local/example-manifests`. 

## Situation 

With ArgoCD v2.10 everything works. 

In ArgoCD v2.12 (didn't try v2.11) git in argocd-repo-server fails with 
```
error="error testing repository connectivity: unknown error: fatal: detected dubious ownership in repository at '/usr/local/example-manifests'"
```

Locally this issue would be fixed with `git --add safe.directory /usr/local/example-manifests` (.gitconfig shown above). But argocd-repo-server does respect /home/argocd/.gitconfig. 

This is demonstrated by git clone being successful in argocd-repo-server command line (it fails without this .gitconfig):

```
argocd@argocd-repo-server-8dfb95f45-rm2vk:~$ git clone /usr/local/example-manifests/ /tmp/lol
Cloning into '/tmp/lol'...
done.
```

But running in ArgoCD fails because of the permission mismatch. 

```
argocd@argocd-repo-server-8dfb95f45-rm2vk:~$ ls -ld /usr/local/cloud-runtime-manifests/
drwxr-xr-x 7 root root 4096 Aug 29 09:52 /usr/local/cloud-runtime-manifests/
```

## Workaround

Our intention was to have these manifests read-only, which was achieved by having the directory owned by root:root. 

Since .gitconfig is not respected, and the problem is caused by mismatching owner:group (root != argocd), we loosened the security approach by changing the ownership of /usr/local/example-manifests to `argocd:argocd` .

The downside is that now the manifest directory is writable by the non-root argocd user. Even though the argocd-repo-server root file system is mounted read only, the volume shared by the init container and argocd-repo-server is writable (otherwise the init container wouldn't be able to write there).

Ironically this means that this enhanced security setting made the overall security worse. 

**Expected behavior**

The argocd-repo-server would either respect ~/.gitconfig or have a way to define a list of `safe.directory` paths. 

**Version**

```shell
v1.12.2
```

**Logs**

```
time="2024-08-29T09:18:17Z" level=error msg="finished unary call with code Unknown" error="error testing repository connectivity: unknown error: fatal: detected dubious ownership in repository at '/usr/local/example-manifests'" grpc.code=Unknown grpc.method=TestRepository grpc.service=repository.RepoServerService grpc.start_time="2024-08-29T09:18:17Z" grpc.time_ms=1.054 span.kind=server system=grpc
```

**Comment by larssb** [comment]
Is this still an issue?

**Comment by theblop** [comment]
same problem here with single-node cluster and a local git repo specified with `repoURL: file:///local-git-repo`

The local volume is mounted with the specified argocd helm values and `/opt/argo.git` belongs to root:root (755) on the host:
```
    repoServer:      
      volumes:
        - name: local-git-repo
          hostPath:
            path: /opt/argo.git
            type: Directory
      volumeMounts:
        - name: local-git-repo
          mountPath: /local-git-repo
          readOnly: true
```

**Comment by csun-cpointe** [comment]
I am running into the same issue as well. Looking into the workaround but dunno how to changing the ownership of the directory? Can anyone give an example? Thanks

**Comment by pre** [comment]
> changing the ownership of the directory

You can run any commands as root in an initContainer which starts before the argocd app container.

**Comment by neildeng** [comment]
> You can run any commands as root in an initContainer which starts before the argocd app container

I configured it based on the reference settings, but the problem persists.
Any suggestions on what I could try next?

```
repoServer: 
  initContainers:
    - name: git-ownership-fix
      image: alpine/git
      command:
        - sh
        - -c
        - |
          git config --global --add safe.directory "/tmp/_argocd-repo/*" 
  existingVolumes:
    tmp:
      persistentVolumeClaim:
        claimName: pvc-argocd-repo-server-tmp
```

**Comment by csun-cpointe** [comment]
> You can run any commands as root in an initContainer which starts before the argocd app container.

@pre can you give an example? thanks

**Comment by rembik** [comment]
> > You can run any commands as root in an initContainer which starts before the argocd app container.
> 
> [@pre](https://github.com/pre) can you give an example? thanks

You could run a sidecar container constantly syncing the local git repository into another mounted volume with the expected ownership `argocd:argocd`. Assuming you are using the argocd helm chart the `values.yaml` could look like this:
```yaml
...
## Repo Server
repoServer:
  # -- Additional containers to be added to the repo server pod
  extraContainers:
    # Workaround for https://github.com/argoproj/argo-cd/issues/19727
    - name: local-git-repo-sync
      image: alpine
      command: [sh, -c]
      args:
        - apk add --no-cache inotify-tools rsync;
          rsync -avz --chown=999:999 /opt/local-git-repo/ /opt/local-git-repo-sync;
          while inotifywait -r -e modify,create,delete,move /opt/local-git-repo; do
            rsync -avz --chown=999:999 /opt/local-git-repo/ /opt/local-git-repo-sync;
          done
      volumeMounts:
        - mountPath: /opt/local-git-repo
          name: local-git-repo
          readOnly: true
        - mountPath: /opt/local-git-repo-sync
          name: local-git-repo-sync

  # -- Init containers to add to the repo server pods
  initContainers: []

  # -- Additional volumeMounts to the repo server main container
  volumeMounts:
    # Add synced local repository directory
    - mountPath: /opt/local-git-repo
      name: local-git-repo-sync
      readOnly: true

  # -- Additional volumes to the repo server pod
  volumes:
    # Add local repository directory
    - name: local-git-repo
      hostPath:
        path: /opt/local-git-repo
        type: Directory
    - name: local-git-repo-sync
      emptyDir: {}
...
```
