### ISSUE TITLE
Allow OCI helm repositories to reuse the GCPServiceAccountKey 

### ISSUE THREAD

**Issue by withnale** [argoproj/argo-cd#19731]
# Summary

In https://github.com/argoproj/argo-cd/issues/17279 I outlined the work required to get argocd to work reliably with gcloud workload identity.

There are two different possible integrations that both require different approaches to work.

For integrating with Google Cloud Source repos, it's possible to create a projected serviceAccount token and create an argocd repository secret which consumes the token. An example of which can be seen below (mocked helm values):

```yaml
repoServer:
  volumes:
    - name: gcp-ksa
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              path: token
              audience: __CLUSTER_PROJECT_ID__.svc.id.goog
              expirationSeconds: 172800
  volumeMounts:
    - name: gcp-ksa
      mountPath: /var/run/secrets/tokens/gcp-ksa
      readOnly: true
```

For the Helm OCI support, the current best approach is to wire in an initContainer which registers docker credentials and shares this with the repo-server. This is a lot of additional work and it requires a bespoke initContainer image and basically a lot of additional complexity. As things stand it also does not allow for `GetTags` to work since that is only wired for hard-coded credentials.

It would be great to align on the repo-server so that it is capable of consuming the token from the first use case to align implementations making things much more predictable.

# Motivation

This would simplify the use case for integrating argocd with gcloud hosted resources making the integration the same for both cases. It would also make floating definitions  (i.e. `targetRevision: 1.2.*`) available to these OCI helm charts.

# Proposal

This would require:

- making sure that `GCPServiceAccountKey` is available in `helm.Creds` as well as in git.Creds
- updating `util/helm/client.go` so that `getAccessToken()` is called during `RegistryLogin` and `GetTags`

I have implemented a "Work in Progress" branch which has this working, but it probably requires some modifications. The naming of the existing resources implies that they are only used for git repositories and if this becomes generic this should be reflected in the naming scheme.
