### ISSUE TITLE
Absence of source and sources in Application cause an unavailability of web interface, which shows stacktrace

### ISSUE THREAD

**Issue by BoyFromDubai** [argoproj/argo-cd#19765]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
When you create an application without source and sources the Web UI is not accessible, showing the stacktrace

**To Reproduce**
Deploy smth like this
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smth
  namespace: argocd
spec:
  destination:
    namespace: xxx
    name: in-cluster
  project: default
```

**Expected behavior**

An existence of sources or source must be validated or just give to an app an unknown status in the WebUI

**Screenshots**
![image](https://github.com/user-attachments/assets/fe3220cd-9578-4080-bbf8-28908a79e282)

**Version**

```shell
v2.11.2
```
But tested in v2.12.x also, and if I'm not mistaken, the same issue exists
