### ISSUE TITLE
Slack notification app-sync-succeeded fails when using sources in Application

### ISSUE THREAD

**Issue by m3talstorm** [argoproj/argo-cd#19766]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If an Application has `sources` (array) rather than `source`, when the Slack notification tries to get the source URL, it will fail because that field does not exist. I expect this happens for other types of notifications but haven't checked.

This is the offending template section:
```
          {
            "title": "Repository",
            "value": "{{.app.spec.source.repoURL}}",
            "short": true
          }
```
**To Reproduce**

Deploy the notification templates from: https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.3/notifications_catalog/install.yaml

Create an application like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: <slack channel>
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/somerepo
      path: some/dir
      targetRevision: HEAD
... etc ...
```

Sync the application

**Expected behavior**

To get a notification containing the list of source repo URLs, or as a minimum, the first?

**Version**

```shell
{
    "Version": "v2.10.3+0fd6344",
    "BuildDate": "2024-03-13T19:03:00Z",
    "GitCommit": "0fd6344537eb948cff602824a1d060421ceff40e",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.2+gc309b6f",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
Failed to notify recipient {slack <channel>} defined in resource argocd/argocd: template: app-sync-succeeded:14:40: executing \"app-sync-succeeded\" at <call .repo.RepoURLToHTTPS>: error calling call: arg 0: value is nil; should be of type string using the configuration in namespace argocd" resource=argocd/argocd
```
