### ISSUE TITLE
Different behavior between helm `values` and `valuesObject`

### ISSUE THREAD

**Issue by fad3t** [argoproj/argo-cd#19781]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

In one of my applications, I'm overriding some values with the null (`~`) value. 
I noticed I'm getting a different behavior when using `values` vs `valuesObject` in my Helm application. ArgoCD correctly understands it when using `values`, however it looks totally ignored when I'm switching to `valuesObject`.

Note I'm not using any subchart here.

**To Reproduce**

This one works as expected:
```yaml
<..snipped..>
source:
  repoURL: "https://example.com"
  chart: "my-chart"
  targetRevision: "1.0.0"
  helm:
    values: |
      quota: ~
      limitRange: ~
```

This one does not:
```yaml
<..snipped..>
source:
  repoURL: "https://example.com"
  chart: "my-chart"
  targetRevision: "1.0.0"
  helm:
    valuesObject:
      quota: ~
      limitRange: ~
```

And this is the template used for the limit range for example:
```yaml
{{- with .Values.limitRange }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "my-chart.namespace" $ }}-limits
  labels:
    {{- include "my-chart.labels" $ | nindent 4 }}
spec:
  limits:
  <..snipped..>
{{- end }}
```

**Expected behavior**

I'm expecting both options to provide identical results, i.e. override the value with null.

**Version**

```
{
    "Version": "v2.11.7+e4a0246",
    "BuildDate": "2024-07-24T09:33:49Z",
    "GitCommit": "e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.4+g81c902a",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```
