### ISSUE TITLE
Invalid redirect uri when using argo-cd dex with workflows 

### ISSUE THREAD

**Issue by kush-work** [argoproj/argo-cd#19787]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have had a working argocd instance until today when we integrated argo-workflows with it's dex. Apparently the argo-workflows sso works now but argocd dex always gives us the error of unregistered redirect_uri.
Below is our dex.config block which is configured by argo-cd helm chart.

```yaml
      dex.config: |
        logger:
          level: debug
          format: json
        connectors:
        - type: saml
          id: okta
          name: Okta
          config:
            ssoURL: <redacted>
            caData: <redacted>
            redirectURI: https://argocd.management.<redacted>.net/api/dex/callback
            usernameAttr: email
            emailAttr: email
            groupsAttr: group
        staticClients:
        - id: argo-cd
          name: Argo Workflow Management
          redirectURIs:
          - https://argo-workflows.management.<redacted>.net/oauth2/callback
          secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      url: https://argocd.management.<redacted>.net
      users.anonymous.enabled: 'false'
```

**To Reproduce**

- Set up argocd with dex
- Integrate the dex with argo-workflows
- See argocd erroring out with invalid redirect uri

**Expected behavior**

ArgoCD should have worked correctly with dex redirectly to our oauth provider.

<img width="1488" alt="Screenshot 2024-09-04 at 11 29 16 PM" src="https://github.com/user-attachments/assets/fb87dd59-b875-45f0-868c-7cbb0695fa39">

**Version**

```shell
v2.11.7+e4a0246
```

**Logs**

```
Paste any relevant application logs here.
```
