### ISSUE TITLE
RequestedScopes must be set for SSO with PKCE 

### ISSUE THREAD

**Issue by mheuser** [argoproj/argo-cd#19825]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using SSO with PKCE the `requestedScopes` MUST be set and are not optional as stated in the documentation.

**To Reproduce**

Enable SSO with PKCE in the argocd-config cm and do not set `requestedScopes`:

```
...
data:
  url: https://argocd.example.com

  oidc.config: |
    name: dex
    issuer: https://dex.example.com
    clientID: argocd-pkce
    enablePKCEAuthentication: true
    # Optional set of OIDC scopes to request. If omitted, defaults to: ["openid", "profile", "email", "groups"]
    #requestedScopes: ["openid", "profile", "email", "groups"]
...
```
Try to login via UI. You will get a error that a join is call on undefined. This one: https://github.com/argoproj/argo-cd/blob/master/ui/src/app/login/components/utils.ts#L88

In the `api/v1/settings` endpoint are no `oidcConfig.scopes` set.

**Expected behavior**

Login works as described in the docs. That the scopes "openid", "profile", "email", "groups" are set by default.

When setting `requestedScopes` to `["openid", "profile", "email", "groups"]` scopes will be set in `api/v1/settings`. So uncommenting the last line in the example config fixes this.

So adding a hint on the docs that `requestedScopes` must be set with PKCE would fix this.

**Version**

```shell
v2.12.3+6b9cd82
```
