### ISSUE TITLE
Not reflecting Helm quote function to label values

### ISSUE THREAD

**Issue by zip-chanko** [argoproj/argo-cd#19835]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD not reflecting Helm `quote` function.

**To Reproduce**

1. Create an app with [example](https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook).
2. Add `repo` label in `helm-guestbook/templates/service.yaml`. (e.g. `repo: {{ .Values.repo | quote }}`)
3. Update the value `repo` to `https://gitlab.com/test/sample-service.git`.

**Expected behavior**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    chart: guestbook-0.1.3
    release: guestbook
    heritage: Helm
    team: test
    repo: "https://gitlab.com/test/sample-service.git"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: guestbook
    release: guestbook
```

**Screenshots**

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/7fccebd0-cf18-4b68-ab45-87a402e08c90">
<img width="1316" alt="image" src="https://github.com/user-attachments/assets/0a536dc7-1ba8-43ba-8bed-015b8869231d">

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T15:33:41Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.23.0
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.12.2+560953c
  BuildDate: 2024-08-23T03:30:19Z
  GitCommit: 560953c37b343c956f3a18f3db7d006e694c0dc4
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Logs**

```
one or more objects failed to apply, reason: Service "ping" is invalid: metadata.labels: Invalid value: "https://gitlab.com/test/sample-service.git": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'). Retrying attempt #2 at 1:52PM.
```
