### ISSUE TITLE
targetBranchMatch filter does not work with pullRequest generator for Azure DevOps

### ISSUE THREAD

**Issue by bonddim** [argoproj/argo-cd#19869]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Adding `targetBranchMatch` filter on generator for Azure DevOps pull request produces zero apps output

**To Reproduce**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        requeueAfterSeconds: 120
        azuredevops:
          api: https://dev.azure.com
          organization: org
          project: project
          repo: repo
          tokenRef:
            secretName: creds-azdo
            key: password
        filters:
          - targetBranchMatch: "develop"
```

**Expected behavior**

ApplicationSet generates apps for pull requests with matched target branch

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T12:18:06Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T12:18:06Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.15.1+ge211f2a
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```
