### ISSUE TITLE
ApplicationSet believes it should make two of every appset

### ISSUE THREAD

**Issue by nwinstel-insight** [argoproj/argo-cd#19912]
Checklist:

* [ X I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
I have a directory structure like so:

└── appsets
    ├── argocd
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── test
    │       └── prod
    ├── cert-manager
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── dev
    │       └── tst
    ├── datadog
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── tst
    │       └── prod
    ├── external-dns
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   └── dev
    │       │       └── config.yaml
    │       └── prod
    ├── gateway-api
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   └── dev
    │       └── prod
    │           └── config.yaml
    ├── istio
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── tst
    │       └── prod
    ├── istio-gateway
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       └── prod
    ├── istio-ztunnel
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── tst
    │       └── prod
    ├── istiod
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── tst
    │       └── prod
    ├── opa-gatekeeper
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── tst
    │       └── prod
    ├── opa-gatekeeper-policies
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── tst
    │       └── prod
    ├── spacelift-workerpool-controller
    │   ├── appset.yaml
    │   └── config
    │       ├── config.yaml
    │       ├── nonprod
    │       │   ├── config.yaml
    │       │   ├── dev
    │       │   └── tst
    │       └── prod
    └── wiz
        ├── appset.yaml
        └── config
            ├── config.yaml
            ├── dev
            └── tst

Here's an example of the appset in the gateway-api appset.yaml:
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-appset
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: 'git@my-repo.com:my-org/aks-infra-appsets.git'
              revision: HEAD
              files:
                - path: 'appsets/gateway-api/config/config.yaml'
                - path: 'appsets/gateway-api/config/{{ .metadata.labels.realm }}/config.yaml'
                - path: 'appsets/gateway-api/config/{{ .metadata.labels.realm }}/{{ .metadata.labels.environment }}/config.yaml'
  template:
    metadata:
      name: '{{ .name }}-{{ .metadata.labels.location }}-gateway-api'  # Use .cluster.name directly
    spec:
      project: "default"
      source:
        repoURL: 'git@smy-repo.com:my-org/aks-gateway-api.git'
        targetRevision: '{{ .chartRevision }}'
        path: '.'
      destination:
        server: '{{ .server }}'  # Use .cluster.server directly
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
```

and I'm attempting to load everything in that repo's folder structure with an appset such as:

```

 

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@my-repo:my-org/aks-infra-appsets.git
        revision: main
        files:
          - path: appsets/**/appset.yaml
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: default
      source:
        path: 'appsets/{{.path.basename}}'
        repoURL: git@my-repo:my-org/aks-infra-appsets.git
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

The actual appsets themselves load correctly, however the appsets generated by this that do not have the cluster name error due to them saying 2 of the same application must be made (so two of {{.name}}-gateway-api

**To Reproduce**

Install ArgoCD create a repository with a directory structure as above. Create an applicationset for gateway-api, then applyu the infra appset.

**Expected behavior**

All appsets are created and evaluated based on their health on the system. I'm somewhat new to how to set up ArgoCD from nothing so I imagine there's already a great way to do this that I've missed.

**Screenshots**

**Version**
```
v2.12.3+6b9cd82
```

**Logs**

```
time="2024-09-12T12:32:06Z" level=info msg="end reconcile" applicationset=argocd/infra-appset requeueAfter=3m0s
time="2024-09-12T12:32:07Z" level=info msg="generated 2 applications" applicationset=argocd/gateway-api-appset generator="{nil nil nil nil nil nil &MatrixGenerator{Generators:[]ApplicationSetNestedGenerator{ApplicationSetNestedGenerator{List:nil,Clusters:&ClusterGenerator{Selector:{map[] []},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},Values:map[string]string{},},Git:nil,SCMProvider:nil,ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},ApplicationSetNestedGenerator{List:nil,Clusters:nil,Git:&GitGenerator{RepoURL:git@myrepo.com:my-org/aks-infra-appsets.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:appsets/gateway-api/config/config.yaml,},GitFileGeneratorItem{Path:appsets/gateway-api/config/{{ .metadata.labels.realm }}/config.yaml,},GitFileGeneratorItem{Path:appsets/gateway-api/config/{{ .metadata.labels.realm }}/{{ .metadata.labels.environment }}/config.yaml,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},},SCMProvider:nil,ClusterDecisionResource:nil,PullRequest:nil,Matrix:nil,Merge:nil,Selector:nil,Plugin:nil,},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},} nil nil nil}"
time="2024-09-12T12:32:07Z" level=error msg="validation error found during application validation: ApplicationSet gateway-api-appset contains applications with duplicate name: cluster-location-gateway-api" applicationset=argocd/gateway-api-appset
time="2024-09-12T12:32:07Z" level=info msg="end reconcile" applicationset=argocd/gateway-api-appset requeueAfter=3m0s

```
