### ISSUE TITLE
ArgoCD ResourceTree issue: Multiple OwnerReferences causing duplicate nodes

### ISSUE THREAD

**Issue by yafeiaa** [argoproj/argo-cd#19910]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I use argocd, I encounter some resources with multiple OWnerreferences. When argocd's resourcetree is generated, two identical nodes will be added to the nodes. The result returned by my resource definition and resourcetree is as follows:
1、my resource：
```
apiVersion: networking.tke.cloud.tencent.com/v1
kind: VpcIPClaim
metadata:
  name: actsvr-grrjk
  namespace: develop-lobby
  ownerReferences:
    - apiVersion: tkex.tencent.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: GameDeployment
      name: actsvr
      uid: 513fcac4-48cd-4839-a616-636db421451d
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: false
      kind: Pod
      name: actsvr-grrjk
      uid: 58575c2d-6b7e-454a-a561-b971c11af025
```

2、resource-tree result.nodes：
```
            {
                "createdAt": "2024-09-02T01:41:26Z",
                "group": "networking.tke.cloud.tencent.com",
                "kind": "VpcIPClaim",
                "name": "actsvr-grrjk",
                "namespace": "develop-lobby",
                "parentRefs": [
                    {
                        "group": "tkex.tencent.com",
                        "kind": "GameDeployment",
                        "name": "actsvr",
                        "namespace": "develop-lobby",
                        "uid": "513fcac4-48cd-4839-a616-636db421451d"
                    },
                    {
                        "kind": "Pod",
                        "name": "actsvr-grrjk",
                        "namespace": "develop-lobby",
                        "uid": "58575c2d-6b7e-454a-a561-b971c11af025"
                    }
                ],
                "resourceVersion": "31288285932",
                "uid": "35c8b9ba-b6c9-4e78-a0ef-95789e6f10c1",
                "version": "v1"
            },
            {
                "createdAt": "2024-09-02T01:41:26Z",
                "group": "networking.tke.cloud.tencent.com",
                "kind": "VpcIPClaim",
                "name": "actsvr-grrjk",
                "namespace": "develop-lobby",
                "parentRefs": [
                    {
                        "group": "tkex.tencent.com",
                        "kind": "GameDeployment",
                        "name": "actsvr",
                        "namespace": "develop-lobby",
                        "uid": "513fcac4-48cd-4839-a616-636db421451d"
                    },
                    {
                        "kind": "Pod",
                        "name": "actsvr-grrjk",
                        "namespace": "develop-lobby",
                        "uid": "58575c2d-6b7e-454a-a561-b971c11af025"
                    }
                ],
                "resourceVersion": "31288285932",
                "uid": "35c8b9ba-b6c9-4e78-a0ef-95789e6f10c1",
                "version": "v1"
            },
```

**To Reproduce**

**Expected behavior**
Normally there should be only one node for the same resource

**Screenshots**

<img width="807" alt="image" src="https://github.com/user-attachments/assets/3e2c86ac-bdc6-4645-9e33-8621a2eb6da5">
**Version**

```shell
v2.9.0
```

**Logs**

```
Paste any relevant application logs here.
```
