### ISSUE TITLE
Name-less repositories will be skipped when authenticating OCI dependencies

### ISSUE THREAD

**Issue by nbarrientos** [argoproj/argo-cd#19930]
**Describe the bug**

The registries of  OCI authenticated dependencies are not logged into if the available and valid Argo CD repository definition does not have a name.

**To Reproduce**

Create an app pointing to a chart umbrella, containing one dependency declared in `Chart.yaml`, ex:

```yaml
...
dependencies:
- name: kubernetes-ingress
  version: 1.39.4
  repository: "oci://registry.cern.ch/foo/bar"
  alias: ingress
...
```
requiring authentication (in other words, `helm registry login...`)

Then, configure ArgoCD with an app using the chart above and a repository like (values base64-decoded on purpose):

```yaml
apiVersion: v1
data:
  enableOCI: true
  password: foo
  type: helm
  url: registry.cern.ch/foo/bar
  username: bar
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.12.3
    argocd.argoproj.io/instance: foo
    argocd.argoproj.io/secret-type: repository
    helm.sh/chart: argo-cd-7.4.7
  name: argocd-repo-dir-harbor-charts
  namespace: argocd
type: Opaque
```
ArgoCD fails to render Helm templates with error:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: could not download oci://registry.cern.ch/foo/bar/kubernetes-ingress: pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials
```

**Expected behavior**

Helm should be able to build all dependencies as there's a valid repository with URL matching 1:1 the URL defined in the dependency itself (`registry.cern.ch/foo/bar`).

If I add a `name` to the ArgoCD repository above, in other words:

```yaml
apiVersion: v1
data:
  enableOCI: true
  password: foo
  type: helm
  url: registry.cern.ch/foo/bar
  username: bar
  name: dir-harbor-charts
kind: Secret
...
```

everything works. My guess is that for some reason the name is somehow expected when creating `HelmRepository` definitions for each dependency. This should not be the case as here I'm doing a 100% URL matching which should just work without having to give it any name, I think.

**Version**

v2.12.3+6b9cd82

**Logs**

See message above.
