### ISSUE TITLE
https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml contains argocd:v2.13.0-rc1

### ISSUE THREAD

**Issue by murand78** [argoproj/argo-cd#19949]
Stable channel manifest contains v2.13.0-rc1 version.

Currently installations done with autopilot points at this repo and automatically sync.
( https://github.com/argoproj-labs/argocd-autopilot/blob/main/manifests/base/kustomization.yaml ) .

( and in my case argocd-notifications-controller is in CrashLoopBackOff :-( )

**Comment by liron-telemessage** [comment]
my case here as well, anyone knows how to resolve this issue?

**Comment by murand78** [comment]
Replace the resources in the base kustomization used by autopilot in YOUR git repo where autopilot is installed at 
/bootstrap/argocd/kustomization.yaml, for example from 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.4.17
```
to 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ./autopilot-manifests/base
```

Create a directory under bootstrap/argocd/autopilot-manifests/base with the following kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - "timeout.reconciliation=15s"

patches:
  # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default

```

This will override the default manifest. Note that argocd version will be will locked to v2.12.3 and not updated automatically.
