### ISSUE TITLE
Add a maintenance window for Applications with automated syncing

### ISSUE THREAD

**Issue by jutley** [argoproj/argo-cd#1995]
It is common for us to need to deploy projects at specific times of the day. For example, sometimes we may need to deploy during contractual maintenance hours. Or we may want to deploy off-peak, which in a multi-region deployment isn't at one specific time.

When I specify an Application with an automated sync-policy, I'd like to be able to provide a window when automated syncing is allowed. Then, when I commit to git, the application delays making any changes to Kubernetes until it is within the designated window. 

It would be nice if the windows allowed for fairly arbitrary scheduling rules, such as "between 2:00am and 4:00am PST every Tuesday", or "Any time UTC on the first of every even-numbered month". 

We should also probably be able to override the maintenance window by manually clicking the "sync" button.

**Comment by jutley** [comment]
An idea for an interface is to use a cron schedule and a window length to specify the complete window. A sync policy may look like this:
```
syncPolicy:
  automated:
    prune: true
    maintenanceWindows:

    # Tuesdays at 2am-4am
    - schedule: "0 2 * * 2" 
      duration: 2h

    # Any time on the first of every even-numbered month
    - schedule: "0 0 1 2 *"
      duration: 24h
    - schedule: "0 0 1 4 *"
      duration: 24h
    - schedule: "0 0 1 6 *"
      duration: 24h
    - schedule: "0 0 1 8 *"
      duration: 24h
    - schedule: "0 0 1 10 *"
      duration: 24h
    - schedule: "0 0 1 12 *"
      duration: 24h
```
