### ISSUE TITLE
out of sync applications ignore manifest-paths annotation

### ISSUE THREAD

**Issue by bobzoller** [argoproj/argo-cd#19967]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an application is a) out of sync and b) uses the `manifest-paths` annotation, it will attempt a sync for _every_ new repo revision, not only those whose content matches its `manifest-paths`.

**To Reproduce**

1. create an Application that uses `manifest-paths`:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  name: infra-development-tester-development
spec:
  destination:
    name: development
    namespace: infra-development-tester
  project: default
  source:
    directory:
      recurse: true
    path: development/infra-development-tester
    repoURL: git@github.com:example/deployments.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    retry: {}
```

2. create a commit that adds a manifest at `development/infra-development-tester/manifest.yaml` that succeeds but does not match, thereby leaving the application Out of Sync (Not sure how to give you a reproducible test case for Out of Sync... in our case a custom operator was swallowing a particular field of the resource definition.  Make sure the Application uses the `manifest-paths` annotation.)

3. create another commit in a different directory of the deployments repo.

4. watch the app attempt a sync.

**Expected behavior**

That the application only attempts a sync when there's a new revision _and_ it matches its `manifest-paths` annotation.

**Screenshots**

none

**Version**

```shell
{
    "Version": "v2.11.7+e4a0246",
    "BuildDate": "2024-07-24T09:33:49Z",
    "GitCommit": "e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.4+g81c902a",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```
