### ISSUE TITLE
Enable ignoreResourceUpdate by default with known high churn resources

### ISSUE THREAD

**Issue by agaudreault** [argoproj/argo-cd#19992]
### Summary

The feature is behind a flag. We should enable `resource.ignoreResourceUpdatesEnabled: true` by default the argocd-cm ConfigMap.

### Motivation

No undesired effect has been reported since it has been implemented. Argo operators will likely experience problems until they find that flag and turn it on. If it is on by default, argo performance will be sustainable with default configurations for longer. CPU will be less and new/existing users are less likely to deploy Argo on instances with a lot of CPU request/limits, saving cost.

### Proposal

- Set it to true by default
- For widely used Kubernetes resources that are known to have high churn, we should configure the ignore by default.

**Comment by andrii-korotkov-verkada** [comment]
Can we enable ignore updates and differences for the status field for all resources? Or is it for v3?

**Comment by nebojsa-prodana** [comment]
```
          resource.customizations.ignoreResourceUpdates.all: |
            jsonPointers:
              - /status
              - /metadata/generation
              - /metadata/resourceVersion
              # ignoring managedFields to prevent churn when argocd competes with argo-rollouts for ownership of vs and dr
              - /metadata/managedFields

          # pods are not directly managed by argocd - skipping churn on larger service (200 or more pods) helps significantly
          resource.customizations.ignoreResourceUpdates.v1_Pod: |
            jsonPointers:
              - /metadata
              - /spec

          # HPA is in control of this, no need to reconcile
          resource.customizations.ignoreResourceUpdates.argoproj.io_Rollout: |
            jsonPointers:
              - /spec/replicas

          # controlled by rollout, no need to reconcile
          resource.customizations.ignoreResourceUpdates.apps_ReplicaSet: |
            jsonPointers:
              - /metadata
              - /spec/replicas

          # controlled by discovery API, no need to reconcile - helps reduce churn with larger services
          resource.customizations.ignoreResourceUpdates.discovery.k8s.io_EndpointSlice:
            |
            jsonPointers:
              - /metadata
              - /endpoints
              - /ports
```

**Comment by agaudreault** [comment]
- https://github.com/argoproj/argo-cd/issues/9819#issuecomment-1705318287 (ReplicaSet annotations)
- Documented configs in operator-manual https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml#L114-L134
- Some usage of leases
```
  resource.customizations.ignoreResourceUpdates._ConfigMap: |
    jqPathExpressions:
    - '.metadata.annotations."control-plane.alpha.kubernetes.io/leader"'
    - .metadata.resourceVersion
```

**Comment by andrii-korotkov-verkada** [comment]
Here's the config we've been using at Verkada and I'm pretty happy with it
```
  # The combo of `ignoreResourceStatusField: all` and `ignoreDifferencesOnResourceUpdates: true`
  # makes /status field updates ignored during both diffing and reconciliation.
  resource.compareoptions: |
    ignoreDifferencesOnResourceUpdates: true
    ignoreResourceStatusField: all
  # The Node-related resources are not shown in UI anyways for some reason.
  resource.exclusions: |
    - kinds:
      - Node
      - NodeClaim
      - CSINode
      - CNINode
  # These mean to exclude EndpointSlice nearly completely.
  resource.customizations.ignoreResourceUpdates.discovery.k8s.io_EndpointSlice: |
    jsonPointers:
    - /endpoints
    - /metadata
  # There are a number of annotations generated and also annotations field itself can be
  # added/deleted
  resource.customizations.ignoreResourceUpdates._Pod: |
    jsonPointers:
    - /metadata/annotations
  # ReplicaSet ones don't work now, since health also changes when replicas change.
  resource.customizations.ignoreResourceUpdates.apps_ReplicaSet: |
    jsonPointers:
    - /metadata/annotations/deployment.kubernetes.io~1desired-replicas
    - /metadata/annotations/deployment.kubernetes.io~1max-replicas
    - /metadata/annotations/rollout.argoproj.io~1desired-replicas
    - /metadata/annotations/rollout.argoproj.io~1ephemeral-metadata
    - /spec/replicas
  # Some Application fields are auto-generated and not related to the application updates itself
  # when needed by app of apps.
  resource.customizations.ignoreDifferences.argoproj.io_Application: |
    jsonPointers:
    - /metadata/annotations/argocd.argoproj.io~1refresh
    - /metadata/annotations/notified.notifications.argoproj.io
    - /operation
```

Need some way to tackle ReplicaSets though.

**Comment by crenshaw-dev** [comment]
Copying from Avo Sepp's message on Slack:

```yaml
  resource.ignoreResourceUpdatesEnabled: "true"
    #   resource.compareoptions: |
    #     ignoreDifferencesOnResourceUpdates: true
  resource.customizations.ignoreDifferences.autoscaling_HorizontalPodAutoscaler: |
    jsonPointers:
    - /status/currentMetrics
  resource.customizations.ignoreDifferences.external-secrets.io_ExternalSecret: |
    jsonPointers:
    - /status/refreshTime
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  resource.customizations.ignoreDifferences.Service: |
    jqPathExpressions:
    - '.spec.selector."rollouts-pod-template-hash"'
  resource.customizations.ignoreDifferences.PodDisruptionBudget: |
    jqPathExpressions:
    - '.status.currentHealthy'
    - '.status.disruptionsAllowed'
    - '.status.observedGeneration'
  resource.customizations.ignoreDifferences.all: |
    jsonPointers:
    - /metadata/generation
    - /metadata/resourceVersion
```

**Comment by daftping** [comment]
https://github.com/argoproj/argo-cd/issues/3150
```yaml
    resource.customizations.ignoreDifferences.apps_Deployment: |
      jqPathExpressions:
        - .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"
        - if (.spec.template.metadata.annotations | length) == 0 then .spec.template.metadata.annotations else empty end
    resource.customizations.ignoreDifferences.apps_StatefulSet: |
      jqPathExpressions:
        - .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"
        - if (.spec.template.metadata.annotations | length) == 0 then .spec.template.metadata.annotations else empty end
```

**Comment by daftping** [comment]
I believe Argo Cd 3.0 can be a good opportunity to disable diffing for all resource by default
```yaml
    resource.compareoptions: |
      # disables status field diffing in specified resource types
      # 'crd' - CustomResourceDefinitions (default)
      # 'all' - all resources
      # 'none' - disabled
      ignoreResourceStatusField: all
```

**Comment by jsolana** [comment]
```yaml
                resource.compareoptions: |
                  ignoreAggregatedRoles: true
                  ignoreResourceStatusField: all
                resource.ignoreResourceUpdatesEnabled: "true"
                resource.customizations.ignoreDifferences.all: |
                  managedFieldsManagers:
                  - kube-controller-manager
                  jsonPointers:
                  - /spec/replicas
                resource.customizations.ignoreDifferences.Secret: |
                  jsonPointers:
                  - /data
                  - /stringData
                resource.customizations.ignoreDifferences.batch_Job: |
                  jsonPointers:
                  - /metadata/annotations
                resource.customizations.ignoreDifferences.Service: |
                  jsonPointers:
                  - /spec/selector/rollouts-pod-template-hash
                resource.customizations.ignoreDifferences.apps_StatefulSet: |
                  jqPathExpressions:
                  - .spec.volumeClaimTemplates[]?.kind
                  - .spec.volumeClaimTemplates[]?.apiVersion
                resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
                  jsonPointers:
                  - "/spec/preserveUnknownFields"
                resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
                  jqPathExpressions:
                  - '.webhooks[]?.clientConfig.caBundle'
                resource.customizations.ignoreResourceUpdates.all: |
                  jsonPointers:
                  - /status
                  - /spec/replicas
                  managedFieldsManagers:
                  - kube-controller-manager
                  - redis-operator
                  - consuela-controller
                resource.exclusions: |
                  - apiGroups:
                    - "discovery.k8s.io"
                    kinds:
                    - "EndpointSlice"
                  - kinds:
                    - "Pod"
                  - apiGroups:
                    - "wgpolicyk8s.io"
                    kinds:
                    - "PolicyReport"
```
