### ISSUE TITLE
api/webhook not triggering refresh of Azure DevOps Repos

### ISSUE THREAD

**Issue by avo-sepp** [argoproj/argo-cd#20039]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD is set to receive webhooks from Azure Devops. These are arriving and I can see in the logs:

```shell
Received push event repo: ...
```

However, the refresh of the app is not triggered after the push event is received. 

**Expected behavior**

After the received push event, the applications under that repo and ref should trigger a refresh. 

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T15:33:41Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.23.0
  Compiler: gc
  Platform: darwin/arm64
```

**Logs**

```
time="2024-09-20T15:47:45Z" level=info msg="Received push event repo: <redacted>, revision: main, touchedHead: true"
```

**Comment by avo-sepp** [comment]
#15427 seems related, so I made sure to include the fix from that issue before creating this one. It seems like there is a separate issue for Azure DevOps webhooks that is still causing an issue.

**Comment by avo-sepp** [comment]
@rumstead I noticed you fixed 15427, so I'm wondering if you have some insight here. It might be a related or similar problem.

**Comment by rumstead** [comment]
The webhook in #15427 was for the applicationset controller. Based on your description it sounds like this is for the argocd server + application controller as described [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/). Is that correct?

Assuming the above is correct, I would set the application controller log level to debug and see if you see anything interesting like the applications not matching the repo URL.

**Comment by avo-sepp** [comment]
Yeah, that seems correct. It's a little confusing, we have individual applications and application sets. None of them seem to be responding. I set the log level to debug, it's a lot here. I'm not sure I'm seeing what I'm supposed to look for.

**Comment by rumstead** [comment]
Seeing either of these?
https://github.com/argoproj/argo-cd/blob/9ac1670c91c8829543725f9387535e201bd6e05e/util/webhook/webhook.go#L394

**Comment by avo-sepp** [comment]
I see nothing about "does not match" in the logs... I do see something about the repo vs webhook url that might be relevant. 

The repos in ArgoCD are configured as https://org@dev.azure.com/org/department/repo but the webhook is sending https://dev.azure.com/org/department/repo

Could that be enough that they don't match?

**Comment by avo-sepp** [comment]
That's it... that's the problem. I need to remove the org@ in all of our applications. 

Is there a way to have that part of this URL be ignored sever-side? Azure Devops provides the url with the org@ when copying a link. It's not expected for most folks to remove that value from the URL.

**Comment by rumstead** [comment]
Interesting I am an Azure DevOps user as well but don't use webhooks. 

We use a repo template with `https://<Org>@dev.azure.com/<Org>/` that allows all our applications to connect without having to do anything on a per-repo basis. 

It doesn't look like based on the regex used to find the applications https://github.com/argoproj/argo-cd/blob/9ac1670c91c8829543725f9387535e201bd6e05e/util/webhook/webhook.go#L328

**Comment by avo-sepp** [comment]
So I was able to do the per-repo templating with https://dev.azure.com as the base and dropped the <Org>@. This still lets us access Repos without a per-repo config, but all of the webhook API calls work now. That is definitely the issue. Night and day difference here.

**Comment by rumstead** [comment]
Can you share the configuration? It would be helpful if this was on the docs

**Comment by avo-sepp** [comment]
Help me narrow down which parts are most useful to share. There's a few components here. Do you want a rundown of removing the <org>@ section?

**Comment by rumstead** [comment]
Yea a rundown would be awesome and if you could share a repo url you are using in your application and the repo cred template url that would be great. Thanks!

**Comment by avo-sepp** [comment]
Azure DevOps Repo Credential

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: azdo-http-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  password: <PAT of READ ALL USER>
  type: git
  # If you want to include all projects in your org, end the url at /<org>
  url: https://dev.azure.com/<org>/<project>
  # You must put a username but any value works, we use not-required
  username: not-required
type: Opaque
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://dev.azure.com/<org>/<project>/_git/argocd
    targetRevision: HEAD
```

Then configure Azure Webhooks per the docs. I did not do anything unique there.
