### ISSUE TITLE
`targetRevision` value inheritance for App of Apps

### ISSUE THREAD

**Issue by nrogerarkhn** [argoproj/argo-cd#20072]
# Summary

Child apps in an ArgoCD app could "inherit" the `targetRevision` value from the root app.

# Motivation

When 
- the codebase is large and split into multiple applications (because, for example, not all applications need to be deployed everywhere),
- the apps should follow an unusual branch (not main or a release branch) on a specific deployment,
- the apps are maintained as code,

we would like to propagate the value of `targetRevision` from the root App into the child apps.

# Proposal

What would be super nice would be the possibility to set `targetRevision: inherit` telling the App to retrieve the `targetRevision` from the root App.
I don't know how hard it is for an App to "know" it's a child app though.

**Comment by nrogerarkhn** [comment]
Nevermind, I managed to do what I wanted by using helm parameters in ArgoCD app definition and passing the `ARGOCD_APP_SOURCE_TARGET_REVISION` value in the root App:
```yaml
    helm:
      parameters:
        - name: charts_version
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
```
Sorry for the trouble!

**Comment by niallwalsh** [comment]
> Nevermind, I managed to do what I wanted by using helm parameters in ArgoCD app definition and passing the `ARGOCD_APP_SOURCE_TARGET_REVISION` value in the root App:
> 
>     helm:
>       parameters:
>         - name: charts_version
>           value: $ARGOCD_APP_SOURCE_TARGET_REVISION
> Sorry for the trouble!

Hey, I'm trying to get this to work too; could you expand on what you added to the root-app.yaml, and then what you set the targetRevision to in the child app to inherit? Thanks!

**Comment by nrogerarkhn** [comment]
I forgot to mention, I'm using Helm as well, so this might not be the solution for your use case, sorry :(
But in the root app I added 
```yaml
spec:
  source:
    helm:
      parameters:
        - name: global.charts_version
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
```
and in the definition of my child app it is
```yaml
spec:
  source:
    targetRevision: {{ .Values.global.charts_version }}
```
