### ISSUE TITLE
Pull request 19209 broke vanilla instalation using kustomization

### ISSUE THREAD

**Issue by ignotas** [argoproj/argo-cd#20114]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Get error:
```shell
strict decoding error: unknown field "spec.template.spec.containers[0].env[21].configMapKeyRef"
```
**To Reproduce**

To reproduce install using kustomization
```yaml
"apiVersion": "kustomize.config.k8s.io/v1beta1"
"kind": "Kustomization"
"namespace": "argocd"
"resources":
- "https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml"
```
**Expected behavior**

Clean installation
**Screenshots**

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T15:33:41Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.23.0
  Compiler: gc
  Platform: darwin/arm64
  ```

**Logs**

```
strict decoding error: unknown field "spec.template.spec.containers[0].env[21].configMapKeyRef"
```
