### ISSUE TITLE
Add Node Selector for Linux Nodes in Deployment YAML for Hybrid Cluster Support

### ISSUE THREAD

**Issue by andorrafields** [argoproj/argo-cd#20141]
I propose adding a `nodeSelector` to the ArgoCD deployment YAML file to ensure that ArgoCD components are scheduled on Linux nodes in hybrid clusters (containing both Linux and Windows nodes). Without this `nodeSelector`, ArgoCD may be deployed on incompatible Windows nodes, resulting in deployment failures.

In hybrid Kubernetes clusters that include both Windows and Linux nodes, certain workloads like ArgoCD require Linux-based nodes for proper operation. Currently, the ArgoCD deployment YAML lacks any node selection mechanism, which may cause the Kubernetes scheduler to assign pods to Windows nodes in these environments. As a result, deployments fail because ArgoCD cannot run on Windows nodes.

To address this issue, I propose modifying the ArgoCD deployment YAML to include a `nodeSelector` that ensures ArgoCD pods are scheduled on Linux nodes only. The following `nodeSelector` should be added to the `spec.template.spec` section of the ArgoCD deployment YAML file:

```
nodeSelector:
   kubernetes.io/os: linux
```
or
```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
 ```

This configuration ensures that only nodes labeled with beta.kubernetes.io/os: linux will be selected for scheduling ArgoCD pods. This would make ArgoCD more robust in hybrid cluster environments and prevent deployment issues related to incompatible node scheduling.

The proposed change will not affect users running clusters with Linux nodes exclusively. For users running hybrid clusters, this ensures correct deployment behavior.
