### ISSUE TITLE
Argocd appset generate with cluster generator is not working

### ISSUE THREAD

**Issue by pradithya** [argoproj/argo-cd#20161]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Calling `argocd appset generate` on applicationSet that use cluster generator cause the command to fail with missing clusterrole

```
> argocd appset generate appset.yaml
FATA[0000] rpc error: code = PermissionDenied desc = unable to generate Applications of ApplicationSet: error generating applications: error getting param sets from generators: error getting params from generator 1 of 4: child generator returned an error on parameter generation: error getting cluster secrets: secrets is forbidden: User "system:serviceaccount:argocd:argocd-server" cannot list resource "secrets" in API group "" at the cluster scope
```

**To Reproduce**

Create appset that use cluster generator. e.g.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name:my-appset
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - merge:
      mergeKeys:
      - server
      generators:
      - clusters:
          values:
            environment: '{{ index .metadata.labels "environment" }}'
            cluster: '{{ .name }}'
  template:
    ... 

```

**Expected behavior**

`argocd appset generate` should be successful

**Version**

```shell
argocd: v2.13.0-rc1+74a367d
  BuildDate: 2024-09-16T08:51:02Z
  GitCommit: 74a367d10e7110209610ba3ec225539ebe5f7522
  GitTreeState: clean
  GoVersion: go1.22.7
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.13.0-rc2+0f083c9
  BuildDate: 2024-09-20T11:37:53Z
  GitCommit: 0f083c9e58638fc292cf064e294a1aa53caa5630
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```
