### ISSUE TITLE
SSO Configuration using argocd-secret not working

### ISSUE THREAD

**Issue by MihaiAnei** [argoproj/argo-cd#2017]
**Describe the bug**
As per documentation ( https://argoproj.github.io/argo-cd/operator-manual/sso/ ) I tried hiding the secret value clientSecret in the argocd-secret resource. The authentication fails because additional characters are added to the clientSecret value when using `$dex.google.clientSecret ` notation.

**To Reproduce**
1. Configure the argocd-cm configmap:
```
data:
  url: https://argocd.example.com
  dex.config: |
    connectors:
      - type: oidc
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
          clientID: redacted-string.apps.googleusercontent.com
          clientSecret: $dex.google.clientSecret
```
2. Encrypt in base64 a value to be set in argocd-secret
3. Edit the secret and add `dex.google.clientSecret: base64-string-from-above`
4. Go into the dex logs and see that the actual clientSecret used by it is: 
`clientSecret: |\n        string-from-above`

**Expected behavior**
The value should be ` clientSecret: string-from-above`

If the value is set directly in argocd-cm the dex server works as expected!

**Version**
Both: 0.12.2 and 1.1.1

Not familiar with golang but I can try debugging this myself if you want.
