### ISSUE TITLE
ManagedFieldsManagers ignoreDifferences setting is not honored with server-side diff enabled

### ISSUE THREAD

**Issue by an-toine** [argoproj/argo-cd#20178]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The MetalLB controller is mutating the `spec.conversion.webhook.clientConfig.caBundle` field in MetalLB CRDs : https://github.com/metallb/metallb/issues/1681

To prevent these resources from being flagged as `OutOfSync`, I've been using this configuration with Argocd 2.11.7 to globally ignore all fields managed by MetalLB : 

```yaml
data:
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
      - MetalLB
```

I've recently upgraded to ArgoCD `2.12.4` and this configuration is no longer working, ArgoCD is flagging the ressource as `OutOfSync ` : 

![image](https://github.com/user-attachments/assets/16465446-711e-43e1-8d6c-530e5529a559)

As soon as I set a matching `jsonPointers` to ignore, ArgoCD won't report any diff for the resource : 

```yaml
data:
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
      - MetalLB
    jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
```

![image](https://github.com/user-attachments/assets/04d724f9-8c3f-4b18-a3d2-b7a8a8ff8899)

**To Reproduce**

Deploy MetalLB with ArgoCD from this chart : https://github.com/metallb/metallb/tree/v0.14/charts/metallb

Check that the deployed CRD contains a field managed by MetalLB : 

```
➜  ~ k get crd bgppeers.metallb.io --show-managed-fields -o yaml | grep -b10 "manager: MetalLB"
12891-    subresource: status
12915-    time: "2024-09-26T11:55:10Z"
12948-  - apiVersion: apiextensions.k8s.io/v1
12988-    fieldsType: FieldsV1
13013-    fieldsV1:
13027-      f:spec:
13041-        f:conversion:
13063-          f:webhook:
13084-            f:clientConfig:
13112-              f:caBundle: {}
13141:    manager: MetalLB
13162-    operation: Update
13184-    time: "2024-09-26T11:55:58Z"
13217-  - apiVersion: apiextensions.k8s.io/v1
13257-    fieldsType: FieldsV1
13282-    fieldsV1:
13296-      f:metadata:
13314-        f:annotations:
13337-          .: {}
13353-          f:controller-gen.kubebuilder.io/version: {}
13407-          f:kubectl.kubernetes.io/last-applied-configuration: {}
```

Update the ArgoCD cm to ignore MetalLB managed fields : 

```yaml
data:
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
      - MetalLB
```

**Expected behavior**

I expect ArgoCD to not report a diff on the CRD as the configuration states that MetalLB fields should be ignored.

**Version**

```shell
➜  ~ k exec -ti argo-cd-argocd-repo-server-7b6b7f68-kjrdw -- argocd version
Defaulted container "repo-server" out of: repo-server, avp, copyutil (init), download-tools (init)
argocd: v2.12.4+27d1e64
  BuildDate: 2024-09-26T06:36:13Z
  GitCommit: 27d1e641b6ea99d9f4bf788c032aeaeefd782910
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
command terminated with exit code 1
```

Feel free to request any additional technical details about my setup.

Antoine
