### ISSUE TITLE
Make sha of source repository available for templating

### ISSUE THREAD

**Issue by manuschillerdev** [argoproj/argo-cd#20185]
# Summary

It would be helpful, if i could access the sha of the `targetRevision` of a source repo for templating.

# Motivation

I use a list generator to deploy `main` and `develop`. `develop` does not create releases/tags, but it creates a docker image on every merge, that is tagged with the branchname, and the latest commit sha (short).
Right now the reference to the `branchname` is stable - so I can not make ArgoCD refresh the app, whithout also referencing the sha.

# Proposal
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - branch: main
          - branch: develop
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: '{{ .branch }}'
    spec:
      project: my-project
      sources:
        - repoURL: 'https://myinstance.tld/org/repo.git'
          targetRevision: '{{ .branch }}'
          path: /helm
          helm:
            parameters:
              - name: image.tag
                # this is the actual proposal: .source.targetRevisionSha
                # would need to be provided after checking out the revision
                value: '{{ .source.targetRevisionSha }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ .branch }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
```

**Comment by manuschillerdev** [comment]
I found the solution via the build environment.

```yaml
sources:
        - repoURL: 'https://myinstance.tld/org/repo.git'
          targetRevision: '{{ .branch }}'
          path: /helm
          helm:
            parameters:
              - name: image.tag
                # docs: https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/
                value: $ARGOCD_APP_REVISION_SHORT
```

this works fine for me and lets me update image tags to the short sha automatically
