### ISSUE TITLE
Add connection-specific socks5 proxy configuration to argocd cli configuration

### ISSUE THREAD

**Issue by fhaftmann** [argoproj/argo-cd#20199]
# Summary

There is already support to connect to the argocd service over a socks5 proxy using the environment variable `ALL_PROXY`, e.g.:

```sh
ALL_PROXY=socks5://localhost:8081 argocd app list
```

I propose to make this configurable on a per-connection base. I.e. in `~/.config/argocd/config` it should be possible to specify something like:

```yaml
servers:
- server: 10.42.0.199
  insecure: True
  proxy-url: socks5://localhost:8081
```

This is inspired by `kubectl` which in `kubeconfig` supports this already:

```yaml
- name: example
  cluster:
    server: https://10.42.0.51:6443
    proxy-url: socks5://localhost:8081
```

# Motivation

It is not uncommon that a k8s API is only reachable by using a SSH server as jump host. A possible solution is to establish a socks5 proxy by SSH using `-D`:

```sh
ssh -NTfv -o ExitOnForwardFailure=yes -D 8081 myuser@myhost
```

As written above `kubectl` can make use of that out-of-the-box.

While the approach `ALL_PROXY=socks5://localhost:8081 argocd app list` works, this is tedious to use in practice:
* Having `ALL_PROXY` permanently in the environment of the interactive shell is havoc – tools like `curl` won’t work as they used to be any longer.
* Passing `ALL_PROXY` on demand does not offer command line completion; typing `ALL_PROXY=socks5://localhost:8081 argocd app get` and then pressing TAB does not give you anything.

Hence the idea to follow the `kubectl` approach and have a connections-specific proxy setting.

# Proposal

I think `argocd login …` should accept an optional argument specifying a proxy.

This should then be stored in the connection configuration and applied accordingly.
