### ISSUE TITLE
[v2.13.0-rc2] ArgoCD is not working when plugin without discovery is configured

### ISSUE THREAD

**Issue by pradithya** [argoproj/argo-cd#20195]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Many (if not all) applications registered in ArgoCD is incorrectly recognized as plugin application when a [plugin](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) without discovery  functionality is configured.
The bug seems introduced by this PR https://github.com/argoproj/argo-cd/pull/18053 . Specifically, [this line of code](https://github.com/argoproj/argo-cd/blob/48551b3746510123285b3ce4aae324b41fd37652/util/app/discovery/discovery.go#L177) in cmpSupports function.

**To Reproduce**
1. Install ArgoCD version v2.13.0-rc1 / rc-2
2. Create kustomize application, for example
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: git@github.com:pradithya/argocd-hack.git
    targetRevision: main
    path: bootstrap
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
```
3. Create CM plugin without discovery functionality configured
4. Check that the application above is somehow recognized as plugin app instead of kustomize app

Full repository to reproduce https://github.com/pradithya/argocd-hack/commit/4ab374e180ffc94d19270652ef70906610fc2927 

**Expected behavior**

application should be rendered properly and recognized as kustomize application instead of plugin application.

**Screenshots**
<img width="841" alt="Screenshot 2024-10-02 at 5 41 14 PM" src="https://github.com/user-attachments/assets/7b8d7268-9e89-46b2-9105-b4ab32b7d021">

<img width="1311" alt="Screenshot 2024-10-02 at 5 38 28 PM" src="https://github.com/user-attachments/assets/739228f6-34fe-450d-9ccb-f16490b5e965">

**Version**

```shell

2024/10/02 17:32:56 maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined
argocd: v2.13.0-rc1+74a367d
  BuildDate: 2024-09-16T08:51:02Z
  GitCommit: 74a367d10e7110209610ba3ec225539ebe5f7522
  GitTreeState: clean
  GoVersion: go1.22.7
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.13.0-rc2+0f083c9
  BuildDate: 2024-09-20T11:37:53Z
  GitCommit: 0f083c9e58638fc292cf064e294a1aa53caa5630
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0

```

**Logs**

```
Paste any relevant application logs here.
```
