### ISSUE TITLE
Support values.yaml outside of chart folder

### ISSUE THREAD

**Issue by drewwells** [argoproj/argo-cd#2020]
**Is your feature request related to a problem? Please describe.**
It is not typical to house all of your values files from the chart folder, helm does not have this requirement. There should be a way to reference values.yaml from other folders, even other repositories.  For example,

charts/application
env/dev/values.yaml
env/qa/values.yaml
env/prod/values.yaml

**Describe the solution you'd like**
I should be able to write something like for dev

```
project: default
source:
  repoURL: 'https://github.com/myorg/myapp/
  path: charts/application
  targetRevision: master
  helm:
    valueFiles:
      - /env/dev/values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dwells
syncPolicy:
  automated:
    prune: true
```

**Have you thought about contributing yourself?**

I have thought about it, but I'm not sure if this is a bug or a feature request. I tried several different strings in valueFiles, but none of them successfully loaded the file.

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

**Comment by alexec** [comment]
We pass the path to values files verbatim to Helm, see:

https://github.com/argoproj/argo-cd/blob/master/util/helm/helm.go#L75

Have you tried relative paths for example?

**Comment by tolko** [comment]
Hi @alexec,
I have tried the following:
Have a chart in a repository and additional values file in the same repository but one level up

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: test
 namespace: argocd
spec:
 destination:
   namespace: default
   server: https://kubernetes.default.svc
 project: default
 source:
  helm:
   valueFiles:
      - ../conf1.yaml
  path: wordpress
  repoURL:  https://github.com/[path_to_repo].git
``` 
and this is working I can use passed conf1.yaml as a values file.

What is concerning me here is this type of behavior can be used as a directory traversal attack?
