### ISSUE TITLE
Response 401 randomly when viewing resource 

### ISSUE THREAD

**Issue by ram4444** [argoproj/argo-cd#20255]
The issue is likely occur (9 out of 10) but not every time 
when I click to view an item in a project the screen redirect to login screen
the browser shows it is a 401 response I have 

![Screenshot From 2024-10-06 19-54-05](https://github.com/user-attachments/assets/b8f9fab0-8353-4bc3-8fc3-b74377430ffb)

Background:
argocd installed from Helm Chart with config in values.yaml:
```
setarg_argocd="\
redis.image.tag=7.4.0,\
server.config.url=argocd.dionys.xyz,\
server.ingress.enabled=true,\
server.ingress.hostname=argocd.$hostname,\
server.ingress.tls=true,\
server.ingress.path=/,\
server.ingress.pathType=Prefix,\
server.ingress.annotations."nginx\.ingress\.kubernetes\.io/force-ssl-redirect"="true" \
server.ingress.annotations."nginx\.ingress\.kubernetes\.io/ssl-passthrough"="true" \
global.domain=dionys.xyz \
server.ingress.ingressClassName=nginx"
```

NGINX  ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.dionys.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 443
  tls:
  - hosts:
    - argocd.dionys.xyz
    secretName: argocd-server-tls # as expected by argocd-server
```
