### ISSUE TITLE
Add a SyncOption to enable / disable helm schema validation

### ISSUE THREAD

**Issue by hawksight** [argoproj/argo-cd#20287]
# Summary

Add a new `application.spec.syncPolicy.syncOptions` for `HelmSchemaValidation`.

This would be to toggle the following helm CLI flag:

```
--skip-schema-validation                     if set, disables JSON schema validation
```

# Motivation

As mentioned [in slack](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1728383914722909), cert-manager chart is used widely in various wrappers. Since introducing a JSON schema to provider better error handling for users, we have seen that some user have different use cases where this breaks.

We are already working on adding some additional change to allow non cert-manager values for common use cases:

- https://github.com/cert-manager/cert-manager/pull/7350
- https://github.com/cert-manager/helm-tool/pull/43

However we believe there will still be more complex edge cases and in those instances it would be appropriate to disable schema validation on the `Application` level.

This would be equivalent to Flux's: `.disableSchemaValidation`
[Reference](https://fluxcd.io/flux/components/helm/helmreleases/#install-configuration).

# Proposal

1. Upgrade helm binary in ArgoCD base image to v3.16.1 (latest, which also includes `--skip-schema-validation`
2. Enable a new `syncOption` to toggle this flag per application.

Maybe something like:

```yaml
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - FailOnSharedResource=true
    - HelmSchemaValidation=false # Defaults to true
```

Not fussy on working, just thought including `Helm` in the option name was a good signal this applied only to Helm as applications cover many installation methods.

**Comment by crenshaw-dev** [comment]
I think instead of a sync option, this should live in spec.source.helm. We render manifests and sync manifests separately. The render operation invokes Helm, and its options live in spec.source.helm.

Would you be up for opening separate PRs for the version bump and the new field? That'll help us diagnose any issues that may pop up.

**Comment by hawksight** [comment]
> I think instead of a sync option, this should live in spec.source.helm.

Thanks @crenshaw-dev that makes sense, I was thinking similar after raising the issue.
So perhaps something like:

```yaml
spec:
  source:
    chart: cert-manager
    repoURL: charts.jetstack.io
    helm:
      releaseName: cert-manager
      releaseName: cert-manager
      skipCrds: false
      disableSchemaValidation: true # or false <--- new field
      version: 3
```

> Would you be up for opening separate PRs for the version bump and the new field?

Absolutely, updating base image CLI version is maybe something I can contribute if I go find where.
As for a new field in the `Application` CRD, I might need a fair bit of guidance :)
