### ISSUE TITLE
Wildcard Support for Namespace Selection in Linked Clusters

### ISSUE THREAD

**Issue by ykoer** [argoproj/argo-cd#20307]
# Proposal
In my organization, we have many team-based ArgoCD instances. Each instance should only have access to namespaces that start with the corresponding team name. Keeping the list of namespaces up to date in the cluster secrets field is quite a challenge. This proposal aims to introduce wildcard support for specifying namespaces in the cluster secret, as shown in the example below. Have you included this feature in your roadmap?

```
kind: Secret
apiVersion: v1
metadata:
  name: argocd-prod-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: ...
  name: prod-cluster
  namespaces: team1--*
  server: ...
```
