### ISSUE TITLE
Add support for route object in Openshift

### ISSUE THREAD

**Issue by tomerle03** [argoproj/argo-cd#20305]
# Summary
In openshift when you deploy a route without a host, the Openshift will generate a host for the route

But currently when you deploy a route object in argocd without ```.spec.host``` argocd will mark it as OutOfSync because in the live manifest the ```.spec.host``` is auto generated by the cluster. Right now the only way to solve this issue is to implement the ignoreDifferences:
```yaml 
ignoreDiffreneces:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
      - /spec/host```
```

# Proposal

I think that part of the route health check should include a check that the ```.spec.host``` in the live manifest is not empty
