### ISSUE TITLE
namespace annotations change not detected

### ISSUE THREAD

**Issue by rgcosma** [argoproj/argo-cd#20328]
**Describe the bug**

Argocd deploys a chart onto multiple clusters, with a manifest that includes a namespace annotation:
```
monitoring-crd:
  chart:
    name: rancher-monitoring-crd
    version: 103.1.1+up45.31.1
  release:
    name: monitoring-crd
    namespace: cattle-monitoring-system
  namespace:
    annotations:
    downscaler/uptime: "Mon-Fri 7-19"
```
The annotation is used by `kube-downscaler` which works fine, scales all deployments to 0 replicas at the time.
Argocd also has a Sync Window defined as `allow:* 8-18` so that it won't try to scale deployments back up conflicting with the downscaler. 
The problem is: in the morning, the annotation is gone.
Adding to the confusion, if the exact same annotation is set via `kubectl annotate namespace --overwrite`, Argo will not try to replace it nor delete next day.

**To Reproduce**

- Set a namespace annotation in Argo
- On a different cluster, set the same annotation via `kubectl`
- Set a Sync Window to run only during the day
- Wait 1 day
- in the morning, the Argo annotation will be gone, the `kubectl` one will still be there

**Expected behavior**

Annotation is left alone.

**Version**

```
argocd: v2.11.4+e1284e1
```

**Comment by rgcosma** [comment]
Edit after looking/logging more carefully: Argo does not wipe the namespace annotation, kube-downscaler does.
It happens in the evening not in the morning: at 7pm when downscaler changes all deployments in the namespace to 0 replicas, it also deletes the annotation. No idea why, this is probably an issue to be discussed in their tracker.
The Argo problem then is - it doesn't detect that the annotation is gone. When running "Sync" the next day, the annotation is put back, but this was supposed to happen automatically.
Also, the confusing difference remains: if the annotation is set manually, it won't be deleted. Only if set by Argo.

**Comment by agaudreault** [comment]
@rgcosma If the annotation is set in your helm chart, then it is part of the desired state. Argo will try to apply that state whenever it syncs, depending on multiple configurations such as ignoreDifferences, syncWindows, respect ignore differences, etc.

Also in your example, it looks like you may have an error with your helm formatting
```yaml
  namespace:
    annotations:
    downscaler/uptime: "Mon-Fri 7-19"

// should be
  namespace:
    annotations:
      downscaler/uptime: "Mon-Fri 7-19"
```

So if your annotation is part of you desired state, it will always be added when argo syncs. If the annotations is NOT in your desired state, and is added by any other mean, then argo will ignore it (will neither add nor remove it)
