### ISSUE TITLE
Extra single quotes in Go templater's output

### ISSUE THREAD

**Issue by 2b** [argoproj/argo-cd#20331]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Go templater in ApplicationSet adds additional single quotes to the output fields, while the Spring library functions output them correctly.

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  template:
    spec:
      project: default
      sources:
      - repoURL: https://gitlab.com/*****
        targetRevision: master
        path: charts/{{ index (splitList "." .path.filenameNormalized) 0 }}
        helm:
          valuesObject:
            vpa:
              enabled: '{{ default true .vpa.enabled }}'
              updateMode: '{{ default "\"Off\"" .vpa.updateMode }}'
              minAllowed:
                memory: '{{ default "\"64Mi\"" .vpa.minAllowed.memory }}'
              maxAllowed:
                memory: '{{ default "\"2Gi\"" .vpa.maxAllowed.memory }}'
```
outputs:

```
vpa:
  enabled: "true"
  maxAllowed:
    memory: '"2Gi"'
  minAllowed:
    memory: '"64Mi"'
  updateMode: '"Off"'
```

**Expected behavior**

```
vpa:
  enabled: true
  updateMode: "Off"
  minAllowed:
    memory: "64Mi"
  maxAllowed:
    memory: "2Gi"
```

which is the output of Spring library - https://go.dev/play/p/I615QD0WbKR

**Screenshots**

**Version**

```shell
{
    "Version": "v2.12.4+27d1e64",
    "BuildDate": "2024-09-26T06:36:13Z",
    "GitCommit": "27d1e641b6ea99d9f4bf788c032aeaeefd782910",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by 2b** [comment]
Please ignore the boolean field - I'm well aware of its usage [limitations](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/#limitations).

**Comment by crenshaw-dev** [comment]
Does this work?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  template:
    spec:
      project: default
      sources:
      - repoURL: https://gitlab.com/*****
        targetRevision: master
        path: charts/{{ index (splitList "." .path.filenameNormalized) 0 }}
        helm:
          valuesObject:
            vpa:
              enabled: '{{ default true .vpa.enabled }}'
              updateMode: '{{ default "Off" .vpa.updateMode }}'
              minAllowed:
                memory: '{{ default "64Mi" .vpa.minAllowed.memory }}'
              maxAllowed:
                memory: '{{ default "2Gi" .vpa.maxAllowed.memory }}'
```

I don't think it's necessary to add escaped quotes. The output of the template is inherently a string.

**Comment by 2b** [comment]
Hi Michael,

It produces the following output:

```yaml
vpa:
  enabled: "true"
  maxAllowed:
    memory: 2Gi
  minAllowed:
    memory: 64Mi
  updateMode: Off
```

which breaks the manifest, because `Off` evaluates as the boolean `False`:

> failed to create typed patch object (microservices/account; [autoscaling.k8s.io/v1](http://autoscaling.k8s.io/v1), Kind=VerticalPodAutoscaler): .spec.updatePolicy.updateMode: expected string, got &value.valueUnstructured{Value:false}

**Comment by crenshaw-dev** [comment]
I think that's a bug with the Helm chart, not with the ApplicationSet. From the AppSet's perspective, I think `vpa.updateMode` is a string. But maybe once it's rendered by the Helm chart into the final manifest, it gets coerced back to a boolean.

**Comment by 2b** [comment]
I can actually provide the Helm chart itself:

template:

```yaml
{{- if .Values.vpa.enabled }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        minAllowed:
          memory: {{ .Values.vpa.minAllowed.memory }}
        maxAllowed:
          memory: {{ .Values.vpa.maxAllowed.memory }}
        controlledResources: ["memory"]
{{- end }}
```

values.yaml:

```yaml
vpa:
  enabled: false
  updateMode: "Initial"
  minAllowed:
    memory: "64Mi"
  maxAllowed:
    memory: "2Gi"
```

**Comment by 2b** [comment]
Even if I add `quote` function to the template, ArgoCD produces output with single quotes around the double quotes:

```yaml
{{- if .Values.vpa.enabled }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        minAllowed:
          memory: {{ .Values.vpa.minAllowed.memory | quote }}
        maxAllowed:
          memory: {{ .Values.vpa.maxAllowed.memory | quote }}
        controlledResources: ["memory"]
{{- end }}
```


output:

```yaml
vpa:
  enabled: "true"
  maxAllowed:
    memory: '"2Gi"'
  minAllowed:
    memory: '"64Mi"'
  updateMode: '"Off"'
```

**Comment by ChristianCiach** [comment]
Maybe try this as a workaround (but I didn't test it):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  template:
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/*****
        targetRevision: master
        path: charts/{{ index (splitList "." .path.filenameNormalized) 0 }}
        helm:
          valuesObject:
            vpa:
              enabled: '{{ default true .vpa.enabled }}'
              minAllowed:
                memory: '{{ default "64Mi" .vpa.minAllowed.memory }}'
              maxAllowed:
                memory: '{{ default "2Gi" .vpa.maxAllowed.memory }}'
  templatePatch: |
    spec:
      source:
        helm:
          valuesObject:
            vpa:
              updateMode: '{{ default "Off" .vpa.updateMode }}'
```

I think I understand why this happens: The YAML marshaller just sees `Off` as a regular string and it doesn't know that it needs quotes to preserve the type when marshalling it to YAML. But  "fixing" this seems dangerous, because there may be people who rely on the current behavior

By using `templatePatch` you should be able to generate a properly quoted patch.
