### ISSUE TITLE
unknown field "metadata.$setElementOrder/finalizers" warning in Application controller

### ISSUE THREAD

**Issue by didlawowo** [argoproj/argo-cd#20351]
i'm using application set config with go template like, thoses are working fine
but two things not work (the feature enabled true for cluster)

and i have a warn message like

 unknown field "metadata.$setElementOrder/finalizers"

i don't know what i'm doing wrong ? 

the two configs file are 

```
{
    "source": {
        "repoURL": "https://argoproj.github.io/argo-helm",
        "targetRevision": "0.42.5",
        "chart": "argo-workflows"
    },
    "project": "testing-apps",
    "destination": {
        "namespace": "argo-workflows"
    },
    "syncPolicy": {
        "syncOptions": {
            "CreateNamespace": true
        }
    },
    "clusters": {
        "in-cluster": {
            "enabled": true,
            "valuesRevision": "main"
        }
    }
}
```
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: discovery-all-clusters
  namespace: kube-infra
spec:
  goTemplate: true
  generators:
  # Create a matrix generator that will install all chart in all clusters
  - matrix:
      generators:
      # Get all clusters
      - clusters: {}
      - git:
          repoURL: git@github.com:xxx/continuous-delivery.git
          #revision: main
          revision: main
          files:
          # Find all .argocd.json  in cc folder
          - path: 'deployed-charts/**/.argocd.json'
          values:
            # Add enabled field if clusters.${name}.enabled = true
            # name comes from the cluster generator
            enabled: '{{ dig "clusters" .name "enabled" false . }}'
            # selector:
            #   matchLabel:
            #     enabled: "true"
  template:
    metadata:
      name: '{{ .name }}-{{ .path.basename }}'
    spec:
      ignoreDifferences: ## for vault
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
      # project: '{{ .project }}'
      project: raspberry-apps
      sources:
      # First source is for value files
      # Default revision is HEAD but can be overriden with clusters.${name}.valuesRevision
      - repoURL: git@github.com:xxxx/continuous-delivery.git
        targetRevision: '{{ dig "clusters" .name "valuesRevision" "main" . }}'
        ref: values
      # Second source is for chart
      # Default revision is .source.targetRevision but can be overriden with clusters.${name}.chartRevision
      - repoURL: '{{ .source.repoURL }}'
        targetRevision: '{{ dig "clusters" .name "chartRevision" .source.targetRevision . }}'
        chart: '{{  default "" .source.chart }}'
        path: '{{  default "" .source.path }}'
        helm:
          #releaseName: '{{ .path.basename }}'
          valueFiles:
          - $values/{{ .path.path }}/values.yaml
          - $values/{{ .path.path }}/values.{{ .name }}.yaml
      destination:
        name: '{{ .name }}' ## from cluster generator
        namespace: '{{ .destination.namespace }}' ## from file json
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace={{ dig "syncPolicy" "syncOptions" "CreateNamespace" "true" . }}
        - ServerSideApply={{ dig "syncPolicy" "syncOptions" "ServerSideApply" "false" . }}
        retry:
          limit: 3 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 20m

```

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

 unknown field "metadata.$setElementOrder/finalizers"

**To Reproduce**

just add config

**Expected behavior**

not warning 

 

**Version**

 Image:           quay.io/argoproj/argocd:v2.12.4   
 

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ChristianCiach** [comment]
Did you recently enable "server-side doff" for your Argo-CD instance? The error message probably comes from kubectl when validating the generated `Application` resources.

Is your ApplicationSet generating Applications that you previously created manually?

Do you mind sharing your Argo-CD configuration?

Where exactly do you see this warning?

**Comment by ChristianCiach** [comment]
You can *maybe* workaround this issue by adding this to your ApplicationSet `template`:

```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
```

But even if this works, I would not really recommend that.
