### ISSUE TITLE
Errors being logged: "Error persisting normalized application spec: applications.argoproj.io "pr-256-my-application" not found"

### ISSUE THREAD

**Issue by yekta-flink** [argoproj/argo-cd#20403]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have recently started using an ApplicationSet that creates and removes ArgoCD applications depending on their PR labels. Basically, if a PR on Github is labeled `preview`, we create a `pr-123-my-application` Application, where the `123` is the number of the PR. If the label is removed, the ArgoCD Application is also removed. The configuration of it is pretty simple, and I have attached it here in this bug report below.

While this seems to work perfectly fine, we have noticed some errors being logged, many hours after the label and the ArgoCD application is already removed: 

```
│ argocd-application-controller-0 {"application":"argocd/pr-256-my-application","level":"error","msg":"Error persisting normalized application spec: applications.argoproj.io \"pr-256-my-application\" not found","time":"2024-10-16T15:14:16Z"}                                                 │
│ argocd-application-controller-0 {"application":"argocd/pr-256-my-application","level":"warning","msg":"Error updating application: applications.argoproj.io \"pr-256-my-application\" not found","time":"2024-10-16T15:14:17Z"}     
```

These same lines are logged every 2-5 minutes. This specific application's `preview` label was removed at 8pm yesterday, which is makes the ApplicationSet remove the application in a few seconds. We can verify from the ArgoCD UI that the this Application doesn't exist anymore. First line was logged at Oct 15 20:00:09.484, around nine seconds after the label was removed, and since then it has been almost 24 hours and these errors are still being logged.

While this is one example, we have other Applications that have the same issue. Common theme among them is that they are created by an ApplicationSet and not directly by us, and their names are sometimes reused. (For example we may re-add the label, and that would lead to another ArgoCD application being created sometime after it was deleted, with the same name again)

As far as I understand ApplicationSets are not interacting with ArgoCD internals but they simply create Applications, so this seems to be an issue with ArgoCD proper, though I may be wrong.

ApplicationSet configuration:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    argocd.argoproj.io/instance: init
  name: preview-my-application
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        labels:
        - preview
        owner: mycompany
        repo: my-application
        tokenRef:
          key: GITHUB_TOKEN
          secretName: some-token
      requeueAfterSeconds: 300
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.slack: some-channel
        notifications.argoproj.io/subscribe.on-sync-failed.slack: some-channel
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: some-channel
        mycompany.com/preview-pr-number: '{{number}}'
        mycompany.com/preview-repo: my-application
        mycompany.com/preview-sha: '{{head_sha}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        mycompany.com/env: staging
        mycompany.com/preview: "true"
      name: pr-{{number}}-my-application
      namespace: argocd
    spec:
      destination:
        namespace: my-app-namespace
        server: https://123.123.12.12
      project: default
      source:
        helm:
          parameters:
          - name: image.tag
            value: '{{head_short_sha_7}}'
          - name: preview.enabled
            value: "true"
          - name: preview.pr_number
            value: '{{number}}'
          valueFiles:
          - values.yaml
        path: staging/some-path
        repoURL: https://github.com/mycompany/my-application.git
        targetRevision: preview/pr-{{number}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```

**To Reproduce**

We haven't yet confirmed if this can be reproduced on any clean ArgoCD setup, yet the steps would be:

* Create a similar ApplicationSet using the configuration above.
* Tag a PR with `preview` label and have it create an Application.
* Wait for some time, remove the label.
* Wait for some time, re-label it.
* Check logs.

**Expected behavior**

No errors are logged as Apps are being created and removed.

**Screenshots**

**Version**

```shell
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T12:31:55Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.7+e4a0246
  BuildDate: 2024-07-24T09:33:49Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0

```

**Logs**

```
│ argocd-application-controller-0 {"application":"argocd/pr-256-my-application","level":"error","msg":"Error persisting normalized application spec: applications.argoproj.io \"pr-256-my-application\" not found","time":"2024-10-16T15:14:16Z"}                                                 │
│ argocd-application-controller-0 {"application":"argocd/pr-256-my-application","level":"warning","msg":"Error updating application: applications.argoproj.io \"pr-256-my-application\" not found","time":"2024-10-16T15:14:17Z"}     
```
