### ISSUE TITLE
Nested gotemplate values don't work

### ISSUE THREAD

**Issue by yehlo** [argoproj/argo-cd#20426]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There seems to be a bug with applicationset using nested gotemplate values in functions like `dig`. When using nested values like `.values.environment` the function didn't return the expected / tested result.

In this case I tried to set the targetRevision of a helm chart depending on the cluster environment. After some testing I found out, that the issue only appears when a nested value is used. If something like `.name` is used it works as expected.

The bug seems to be reproducable generally when using nested variables in sprig functions.

Feel free to ask me for any further details. 

**To Reproduce**

Using a directory structure like this:
```
├── applicationset.yaml
├── apps
│   ├── app1
│   │   ├── argo-config.json
│   │   └── values
│   │       ├── clusters
│   │       │   └── clustername.yaml
│   │       ├── environments
│   │       │   ├── dev.yaml
│   │       │   ├── prod.yaml
│   │       │   └── test.yaml
│   │       └── globals.yaml
│   └── app2/...
└── README.md
```

Applicationset.yaml for reference:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bedag-observability-stack
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  enabled: "true"
              values:
                cluster: '̣{{ index .metadata.labels "app.kubernetes.io/name" }}'
                environment: '̣{{ index .metadata.labels "environment"}}'
          - git:
              repoURL: 'https://git.com/repo.git'
              revision: HEAD
              files:
                - path: 'apps/*/argo-config.json'
              
  template:
    metadata:
      # because of mysterios reasons i couldnt use .values.cluster whether I set values.cluster=name or nameNormalized
      # both result in the same error of the name not being in RFC 1123 format
      # thus we'll have to use the nameNormalized value hardcoded here (╯°□°)╯︵ ┻━┻
      name: "{{.nameNormalized}}-{{.app}}" #"{{ .values.cluster }}-{{ .app }}"
    spec:
      project: default 
      sources:
        # by default all values are within the values directory
        - repoURL: 'https://git.com/repo.git'
          targetRevision: HEAD
          ref: helmValues
        # template the helm charts using the given values
        # these gotpl methods basically check if overrides on the environment level are given and defaults to the root level
        - repoURL: '{{ .helmRepo }}'
          chart: '{{ .helmChart }}'
          # shuld be working according to https://medium.com/@geoffrey.muselli/argocd-multi-cluster-helm-charts-installation-in-mono-repo-0a406ff7c578
          # only issue is that why the fuck ever the value is not allowed to be nested -> .values.env does not work (╯°□°)╯︵ ┻━┻ 
          targetRevision: '{{ dig "overrides" .values.environment "helmChartVersion" .helmChartVersion . }}'
          helm:
            valueFiles:
              - '$helmValues/apps/{{.app}}/values/globals.yaml'
              - '$helmValues/apps/{{.app}}/values/environments/{{.values.environment}}.yaml'
              - '$helmValues/apps/{{.app}}/values/clusters/{{.values.cluster}}.yaml' 
            ignoreMissingValueFiles: true
      destination:
        server: '{{.server}}'
        namespace: my-namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

And finally the argo-config.json file
```json
{
  "app": "app",
  "helmRepo": "https://chart-repo.io",
  "helmChart": "chart",
  "helmChartVersion": "1.2.0",
  "overrides": {
    "dev": {
      "helmChartVersion": "1.4.0"
    },
    "test": {
      "helmChartVersion": "1.3.0"
    },
    "prod": {},
    "in-cluster": {
      "helmChartVersion": "1.1.0"
    }
  }
}
```

_some details_
This applicationset uses the cluster generator and reads the `values.environment` from the labels. Using the matrix generator we want to create all the apps within the app/ directory on each enabled cluster.

When the applicationset is running as is it always defaults to the root `.helmChartVersion` . Meaning it's set to `1.2.0` on all of the clusters.

The same `.values.environment` gotemplate works for the helmfile where the corresponding `test.yaml`, `dev.yaml`, etc. is chosen. Thus I know that the value is working.

_workaraound_
After some testing I found out that the issue only appeared when I used a nested value like `values.environment`. 

The `dig` worked when set statically like this:
`targetRevision: '{{ dig "overrides" "test" "helmChartVersion" .helmChartVersion . }}'`

Meaning I know that the method call should be working. 

Then I added the `in-cluster` to the `overrides` and tested it using only `.name` like this:
`targetRevision: '{{ dig "overrides" .name "helmChartVersion" .helmChartVersion . }}'`

Which also worked for the corresponding cluster.

This lead me to believe that there's a bug with nested values in functions like `dig`.

_additional infos_

But this should be applicable to any nested values thus you could recreate it using the list generator. On a previous iteration I tried something similar using this more complex gotemplate: 

`{{ if (index .overrides.envs (printf .values.environment)).helmChartVersion }}{{ (index .overrides.envs (printf .values.environment)).helmChartVersion }}{{ else }}{{ .helmChartVersion }}{{ end }}`

I'm guessing this didn't work due to the same bug though I didn't verify. Though I replaced this using the dig, thinking it was due to the larger call.

**Expected behavior**

Both the easier `dig` example aswell as the `dig` work when placed in a gotemplate playground like: https://repeatit.io/. 

I would expect argocd to work the same as these playgrounds.

**Screenshots**

n/e

**Version**

```json
{
    "Version": "v2.12.4+27d1e64",
    "BuildDate": "2024-09-26T06:36:13Z",
    "GitCommit": "27d1e641b6ea99d9f4bf788c032aeaeefd782910",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**
I can just see the apps being created by the appset controller, no errors in the logs.
