### ISSUE TITLE
Application shows differences in Deployment's annotations when syncPolicy.managedNamespaceMetadata is set

### ISSUE THREAD

**Issue by mtougeron** [argoproj/argo-cd#20477]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an Application or ApplicationSet is using the `syncPolicy.managedNamespaceMetadata` field with the `RespectIgnoreDifferences=true` flag is set and the `resource.customizations.ignoreDifferences.apps_Deployment` (and StatefulSet) is set in the `argocd-cm` ConfigMap, Argo CD will incorrectly calculate the differences in the `.spec.template.metadata.annotations` field. It will show that the live manifest has

```yaml
  template:
    metadata:
      annotations: {}
```

instead of not being set at all when the only annotation set is the one being ignored in the `resource.customizations.ignoreDifferences` settings.

**To Reproduce**

Update the `argocd-cm` ConfigMap to contain

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.ignoreDifferences.apps_Deployment: |
    jqPathExpressions:
      - .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"
      - .spec.template.metadata.annotations."shredder.ethos.adobe.net/restartedAt"
  resource.customizations.ignoreDifferences.apps_StatefulSet: |
    jqPathExpressions:
      - .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"
      - .spec.template.metadata.annotations."shredder.ethos.adobe.net/restartedAt"
```

Restart Argo CD pods

Create an Application using the guestbook example app.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
  syncPolicy:
#    managedNamespaceMetadata:
#      labels:
#        some-custom-label: somevalue
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Prune=false
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
```

Apply the Application to the Argo CD instance.

Once the Deployment exists, do a `kubectl rollout restart deploy/guestbook-helm-guestbook -n guestbook` to add the `kubectl.kubernetes.io/restartedAt` annotation. 

Verify that the Application in Argo CD shows no differences.

Edit the Application to set a label on the Namespace using the `syncPolicy.managedNamespaceMetadata` field and apply it

The Application will show that there is a difference because the Namespace label has not been applied.

Click sync to sync the Application and have the Namespace label applied.

After this, the Application will _always_ show that there is a difference in the `guestbook-helm-guestbook` Deployment's annotations.
 
**Expected behavior**

The Application should not show that there are any differences in the Application.

**Screenshots**

![image](https://github.com/user-attachments/assets/64701cde-3598-492f-b7d9-518ced8086b3)

![image](https://github.com/user-attachments/assets/1988d3dd-bafb-43b7-86b6-a602d28498da)

**Version**

```shell
v2.12.6+4dab5bd
```

I also tested this with the latest `v2.13.0-rc5` release as well and was able to reproduce it.

Tested reproduction steps with Kubernetes `Server Version: v1.29.4` and `Server Version: v1.31.1` using kind.

**Comment by mtougeron** [comment]
btw, I don't know if this is the same issue or not (in this case it might be the way we wrote the ignoreDifferences) but I thought I'd mention it anyway since it's so similar but a more complex data structure.

The Argo CD config has a global configuration to ignore the AKS mutations to the `ValidatingWebhookConfiguration`

```yaml
      resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
        jqPathExpressions:
          # Ignore AKS injections.
          - '.webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "control-plane")'
          - '.webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")'
```

but as you can see in this screenshot, the live vs desired don't quite match up right.
![image](https://github.com/user-attachments/assets/25bead82-1956-48a1-a14c-075059964297)

**Comment by andrii-korotkov-verkada** [comment]
The annotations field itself is not configured in ignore differences.

> Edit the Application to set a label on the Namespace using the syncPolicy.managedNamespaceMetadata field and apply it

Does it mean a manual edit, not through Git or similar?
There is some counter-intuitive handling of some edge cases by kubectl when there were manual edits and they won't be deleted automatically.

**Comment by andrii-korotkov-verkada** [comment]
You have managedNamespaceMetadata commented out in the example manifest
```
```

**Comment by andrii-korotkov-verkada** [comment]
My hunch is that `managedNamespaceMetadata` is a red herring and any update with these configs and rollout restart may trigger this issue. Can you try upgrading to v2.13.1 and try to reproduce, please? I think there's been some PRs working on the diffing, that might have helped here.

**Comment by mtougeron** [comment]
> The annotations field itself is not configured in ignore differences.
> 
> > Edit the Application to set a label on the Namespace using the syncPolicy.managedNamespaceMetadata field and apply it
> 
> Does it mean a manual edit, not through Git or similar? There is some counter-intuitive handling of some edge cases by kubectl when there were manual edits and they won't be deleted automatically.

For this reproduction example I did it via `kubectl edit`. However I've seen it happen in the real-world when the Application was updated via Argo CD.

**Comment by mtougeron** [comment]
> My hunch is that `managedNamespaceMetadata` is a red herring and any update with these configs and rollout restart may trigger this issue. Can you try upgrading to v2.13.1 and try to reproduce, please? I think there's been some PRs working on the diffing, that might have helped here.

I'll try this today or tomorrow

**Comment by adriananeci** [comment]
This issue is still present on 2.13.2

**Comment by adriananeci** [comment]
FYI this issue is still present on 2.14.2

**Comment by blakepettersson** [comment]
Still present on `HEAD` (`>=3.0`)

**Comment by danielgines** [comment]
Confirming this bug is still present in **ArgoCD v3.3.2** (Helm chart v9.x).

**Reproduction:** When `syncPolicy.managedNamespaceMetadata` includes annotations with dynamic values (e.g., a build timestamp), `resource.customizations.ignoreDifferences.all` in `argocd-cm` does NOT prevent the Application from showing OutOfSync.

In our case, we have ~30 Applications managed by a parent App-of-Apps (platform-root). Each Application uses `managedNamespaceMetadata` to set provenance annotations on its target namespace:

```yaml
syncPolicy:
  managedNamespaceMetadata:
    annotations:
      estabilis.io/built-at: "2026-04-10T17:03:24Z"  # changes on every promote
      estabilis.io/git-revision: "9db1012..."           # changes on every commit
```

We have `ignoreDifferences.all` configured in `argocd-cm`:

```yaml
resource.customizations.ignoreDifferences.all: |
  jqPathExpressions:
    - .metadata.annotations."estabilis.io/built-at"
    - .metadata.annotations."estabilis.io/git-revision"
    - .metadata.annotations."estabilis.io/build-id"
    - .metadata.annotations."estabilis.io/git-source"
```

**Expected:** Applications stay Synced because the annotation diff is ignored.
**Actual:** Every promote causes ALL 30+ Applications to show OutOfSync because the namespace annotations changed. The `ignoreDifferences` configuration has no effect on `managedNamespaceMetadata`.

**Impact:** In a multi-cluster platform with frequent promotes, this creates a permanent OutOfSync storm across all Applications. The only workaround is to remove dynamic annotations from `managedNamespaceMetadata` entirely.
