### ISSUE TITLE
ServerSide diff is not working

### ISSUE THREAD

**Issue by kotyara85** [argoproj/argo-cd#20473]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

I set annotation argocd.argoproj.io/compare-options=ServerSideDiff=true

Here's helm template sample:
```
{{- define "k8sServiceHost" }}
  {{- if lookup "v1" "ConfigMap" "kube-public" "cluster-info" }}
    {{- $configmap := (lookup "v1" "ConfigMap" "kube-public" "cluster-info") }}
    {{- $kubeconfig := get $configmap.data "kubeconfig" }}
    {{- $k8sServer := get ($kubeconfig | fromYaml) "clusters" | mustFirst | dig "cluster" "server" "" }}
    {{- $uri := (split "https://" $k8sServer)._1 | trim }}
    {{- (split ":" $uri)._0 | quote }}
  {{- end }}
{{- end }}
```

which does work correctly with --dry-run=server using helm command

Template:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
    host: {{ include "k8sServiceHost" . }}
```

results into:
```
apiVersion: v1
data:
  host: ''
kind: ConfigMap
metadata:
  labels:
    argocd.argoproj.io/instance: test
  name: test
  namespace: test
```

**Version**
1.12.6
