### ISSUE TITLE
Apps of apps remote cluster unpredictable sync

### ISSUE THREAD

**Issue by kotyara85** [argoproj/argo-cd#20487]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using app of apps and want to use one mgmt cluster to manage a swarm of clusters.
The idea is simple, you can push charts from a single mgmt cluster.
What's weird, let's say I created an app of apps and pointed to a destination cluster, argocd rendered it - 
```
argoproj.io/Application/cluster-example-com/auth

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels:
    argocd.argoproj.io/instance: cluster-example-com_apps
  name: auth
  namespace: cluster-example-com
spec:
  destination:
    namespace: kube-system
    server: 'https://100.100.100.100:443'
  project: default
  source:
    chart: auth
    repoURL: 'https://artifactory.example.com/artifactory/helm-virtual'
    targetRevision: 0.1.*
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
```

If I create it manually, it works as expected, argocd on the other hand is trying to create this app in the destination cluster and errors out with - namespace `cluster-example-com` doesn't exist.

Am I missing something here? I just want these apps to get created in the mgmt cluster under ns cluster-example-com

Thanks
