### ISSUE TITLE
ApplicationSet webhooks should use stricter comparison of repository URL

### ISSUE THREAD

**Issue by dacofr** [argoproj/argo-cd#20485]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

ApplicationSet webhook can trigger refresh of unwanted ApplicationSet, due to regexp that is not enough strict at the end, in my opinion, it is missing a `$` at end of this regexp :

https://github.com/argoproj/argo-cd/blob/ac69f5223cd0fc42fcc638b340a3703addda3812/applicationset/webhook/webhook.go#L225

**To Reproduce**

Create two ApplicationSet where URL are close : 
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
....
spec:
  generators:
  - git:
      files:
      - path: envs/**/config.json
      repoURL: https://github.com/dacofr/hello-appset.git
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
....
spec:
  generators:
  - git:
      files:
      - path: envs/**/config.json
      repoURL: https://github.com/dacofr/hello-appset-copy.git
```

Trigger a webhook (included minimal payload from GitHub)
```
curl --request POST \
  --url http://localhost:7000/api/webhook \
  --header 'Content-Type: application/json' \
  --header 'X-GitHub-Event: push' \
  --data '{
    "ref": "refs/heads/main",
    "repository": {
      "html_url": "https://github.com/dacofr/hello-appset",
      "default_branch": "main"
    }
}'
```

**Logs**

```
INFO[0431] Received push event repo: https://github.com/dacofr/hello-appset, revision: main, touchedHead: true 
DEBU[0431] https://github.com/dacofr/hello-appset-copy.git uses repoURL main 
INFO[0431] refresh ApplicationSet argocd/hello-git-appset-copy from webhook 
DEBU[0431] https://github.com/dacofr/hello-appset.git uses repoURL main 
INFO[0431] refresh ApplicationSet argocd/hello-git-appset from webhook 
```

**Expected behavior**

Only one of ApplicationSet should be refreshed.
