### ISSUE TITLE
ArgoCD Multiple Source Issues

### ISSUE THREAD

**Issue by hjoneswh** [argoproj/argo-cd#20499]
ArgoCD version - v2.12.4+27d1e64

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have been attempting to implement ArgoCD multiple source (https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/) values.yaml and been running into some issues with the functionality which I'd thought id raise here.

I can confirm that ArgoCD can successfully see code in both my locations and both sources are being shown in my application. When I attempt to make a change in the values.yaml in the git repository `git-repo-1` ArgoCD cannot see any changes in my state until I perform a manual 'force refresh' in the UI. 

Furthermore, If I make a change in the values.yaml in the git repository `git-repo-2`, ArgoCD also cannot see any changes in the state (even on force refresh), however if I am to delete the resource that is being created by ArgoCD the new values will be brought in. 

In my case I have a very simple cron job and I'm simply just changing the schedule as a test i'd assume this will be the same with a any k8s resource. 

**To Reproduce**

I have configured the following application resource. Essentially I have two locations I want my values to be pulled from both located in separate git repositories. 

```
  sources:
    - repoURL: 'https://gitlab.com/my-redacted-path/hjones/git-repo-2'
      targetRevision: main
      ref: valuesRepo
    - repoURL: 'https://gitlab.com/my-redacted-path/git-repo-1'
      path: transient-1161/eks-addons/envs/default/scalertron
      targetRevision: main
      helm:
        releaseName: scalertron
        valueFiles:
          - $valuesRepo/values.yaml
          - ../../dev/eu-west-1/transient-1161/scalertron/values.yaml
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
```

1. Deploy an application with multiple source locations, you will need to create any secrets include api tokens for your git repositories
2. Create a simple helm chart with some resource e.g. a pod which a label is controlled by values.yaml 
3. Adjust the label in both locations in your sources
4. Monitor ArgoCD to review whether your changes are identified by ArgoCD
5. Check if a force refresh in UI brings changes in
6. Check if deleting pod resources brings changes in

**Expected behavior**

I would expect ArgoCD to be monitoring the two source locations and to be able to understand that there is a diff between expected and desired state. 

This should be done without any manual interaction, I shouldn't have to force refresh or delete resource to bring changes through.

**Version**

```shell
❯ argocd version
argocd: v2.12.6+4dab5bd
  BuildDate: 2024-10-18T18:51:56Z
  GitCommit: 4dab5bd6a60adea12e084ad23519e35b710060a2
  GitTreeState: clean
  GoVersion: go1.22.8
  Compiler: gc
  Platform: darwin/amd64
```
