### ISSUE TITLE
ApplicationSet Proposal: Add templateable field for whether Application should be generated

### ISSUE THREAD

**Issue by Baegi** [argoproj/argo-cd#20504]
# Summary

For ApplicationSets, there should be a fully templateable field (e.g. `.spec.template.generate: true|false`). 

This field should specify whether the application should be created, similar to the Post Selector, but fully templateable.

# Motivation

In our case, we use the git files generator to template applications. In certain cases based on suffixes of fields in these files, no application should be generated. `matchLabels` and `matchExpressions` from the Post Selector isn't sufficient for these cases, as they only provide few functions (does key exist, is value in set, etc. instead of e.g. does value have suffix?)

# Proposal

Add a field to the ApplicationSet CRD, e.g. `.spec.template.generate`, which can be templated to a boolean to specify whether the application should be created. The default value of this field should be `true`.

Our current workaround is to template the undesired applications to a hidden project to which no one has access, to hide it from users. Is there a better workaround?

**Comment by crenshaw-dev** [comment]
I'd use the `values` field of your git generator to template out a true/false condition and then use a post selector to filter on it.

```yaml
generators:
- git:
    values:
      generate: '{{ my | complex | logic }}'
```

**Comment by Baegi** [comment]
Hi @crenshaw-dev

Thanks for the response. I'm not sure this is possible, even with a straight-forward

```yaml
spec:
  generators:
    - git:
        files:
          - path: apps/**.yaml
        repoURL: '[...]'
        revision: HEAD
        values:
          generate: abc
      selector:
        matchLabels:
          generate: abc
```

All applications get filtered out. The passed `.spec.generators.git.values` doesn't seem to be considered by the post selector.

**Comment by crenshaw-dev** [comment]
I believe the correct selector would be `values.generate`. But there may be a limitation in the selector preventing it from accessing nested fields. I think that's a bug we could fix.

**Comment by Baegi** [comment]
This also doesn't template any applications:

```yaml
spec:
  generators:
    - git:
        files:
          - path: apps/**.yaml
        repoURL: '[...]'
        revision: HEAD
        values:
          generate: abc
      selector:
        matchLabels:
          values.generate: abc
```

Should this be tracked here, or should I create a seperate bug-issue for this?
/
