### ISSUE TITLE
Applications keep changing between Degraded and Healthy every 3 minutes

### ISSUE THREAD

**Issue by kachi-app** [argoproj/argo-cd#20517]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.
* [x] I've found that 3 minutes is **timeout.reconciliation** config.

**Describe the bug**
I have a private OCI helm chart that push to Artifact Registry. To add the Helm Repository Credentials, I am using Kubernetes CronJob to renew the access tokens every 15 minutes and it works well as I can deploy the applications. Here is the CronJob Config:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-access-token-generator
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: helm-access-token-generator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-access-token-generator
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "patch", "list" ]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gcar-access-token-generator
spec:
  schedule: "15 * * * *" # Run every 15 minutes
  timeZone: Asia/Jakarta
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: argocd-server
          tolerations:
            - effect: NoSchedule
              key: role
              operator: Equal
              value: infra
          containers:
            - name: generate-access-token
              image: google/cloud-sdk:498.0.0-slim
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  ACCESS_TOKEN=$(gcloud auth print-access-token)
                  SECRET_FILE_NAME="github-chi-infra-argocd-secret.yaml"
                  
                  export TZ="Asia/Jakarta"
                  apt-get install -y tzdata kubectl
                  RUNNING_DATE=$(date +"%Y-%m-%d-%H-%M-%S")
                  RENEWAL_DATE=$(date -d "+30 minutes" +"%Y-%m-%d-%H-%M-%S")
                  echo "Running Date: $RUNNING_DATE"
                  echo "Renewal Date: $RENEWAL_DATE"
                  cat << EOF > $SECRET_FILE_NAME
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: gcar-auth
                    namespace: argocd
                    labels:
                      argocd.argoproj.io/secret-type: repository
                      argocd/helm-repo-last-renewed: "$(echo $RUNNING_DATE)"
                      argocd/helm-repo-renew-at: "$(echo $RENEWAL_DATE)"
                  type: Opaque
                  stringData:
                    name: "helm-chart"
                    password: "$(echo $ACCESS_TOKEN)"
                    project: "chi"
                    type: "helm"
                    enableOCI: "true"
                    url: "europe-west4-docker.pkg.dev/xxxxx"
                    username: "oauth2accesstoken"
                  EOF
                  kubectl apply -f $SECRET_FILE_NAME
          restartPolicy: OnFailure
```
I also have a **Application** config that refer to **Application** other deployment repository, so the flow is
```
Application ( Root Deployment Repo - app-of-apps ) -> Application ( Each folder in the Repo, refer to path ai/app-of-apps ) -> ApplicationSet ( Generator, ai/app-of-apps ) -> Application ( Smallest unit of Deployment, ai/xxx )

├── ai
│   ├── app-of-apps
│   │   └── applicationsets.yaml
├── app-of-apps
│   ├── ai.yaml
│   └── backend.yaml
└── backend
    ├── app-of-apps
    │   └── applicationsets.yaml


```
In the deployment repository have a Chart with dependencies to the OCI Helm Chart above.
```
apiVersion: v2
name: xxx
description: A Helm deployment for Kubernetes Service
type: application
version: 0.1.0-staging
appVersion: "xxx"
dependencies:
  - name: xxx
    version: 0.1.0-staging
    repository: oci://europe-west4-docker.pkg.dev/xxx/xxx-chart
    alias: xxx
```
However the applicationSet that deploying the application keep changing between Degraded and Healthy every 3 minutes 

**To Reproduce**

**Expected behavior**
ArgoCD ApplicationSet Status should not keep changing between Healthy and Degraded every 3 minutes.

**Screenshots**
![image](https://github.com/user-attachments/assets/ac539631-e6f9-42f6-88bd-ce265bb56db0)

![image](https://github.com/user-attachments/assets/48380f88-2062-4b7e-87d4-28de34df2ae3)
![image](https://github.com/user-attachments/assets/59df8937-6b54-4ae8-882f-635ef73c5b7f)

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T15:33:41Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.23.0
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.12.6+4dab5bd
  BuildDate: 2024-10-18T17:39:26Z
  GitCommit: 4dab5bd6a60adea12e084ad23519e35b710060a2
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Logs**

```
ApplicationSet: error generating params from git: error getting directories from repo: error retrieving Git Directories: rpc error: code = Internal desc = unable to resolve git revision : authentication required

```

Thank you
