### ISSUE TITLE
Allow access to argocd-notifications-secret in notification service webhook configuration

### ISSUE THREAD

**Issue by dmarquez-splunk** [argoproj/argo-cd#20538]
# Summary

Secrets should be able to be used in webhook notification service for requests that require an access token to be a part of the HTTP header field.

# Motivation

Gitlab API requires the PRIVATE-TOKEN header field to be present with a valid access token in order to authenticate to its API. If we wish to use this then we would need to hardcode an access token inside of the configmap which is not ideal. We should be able to use the argocd-notifications-secret similar to the way it is able to be used in the template as demonstrated in the [docs](https://argo-cd.readthedocs.io/en/latest/operator-manual/notifications/templates/#defining-and-using-secrets-within-notification-templates)

When I try to leverage it in the service config like this:

```
    "service.webhook.gitlab": |||
      url: <gitlab_url>
      headers:
        - name: PRIVATE-TOKEN
          value: {{.secrets.gitlab-token}}
```

I see the following error:

`
time="2024-10-25T18:39:57Z" level=error msg="error getting api from namespace: argocd error: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{\".secrets.gitlab-token\":\"\"}"
`

# Proposal

Make this such that we can use the argocd-notifications-secret fields in the webhook configuration similar to the templates configuration.

**Comment by andrii-korotkov-verkada** [comment]
Why do you have `|||` in the config?

**Comment by jekader** [comment]
I ran some tests using this documentation and looks like everything works as expected not just for emails but for webhooks as well:
https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/

1) edit/create the `argocd-notifications-secret` secret and set the sensitive token value (don't forget to base64 encode it first)

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
data:
  my-apikey: BASE64_OF_VALUE
```

2) now use `my-apikey` in the `argocd-notifications-cm` configmap to define the webhook:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.test: |
    url: https://demo.local/myendpoint
    headers: #optional headers
    - name: auth
      value: $my-apikey
```
