### ISSUE TITLE
kube-prometheus-stack stuck in OutOfSync/Syncing

### ISSUE THREAD

**Issue by pablo-balboa-team** [argoproj/argo-cd#20537]
Checklist:

- [x]  I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x]  I've pasted the output of argocd version.

**Describe the bug**

Hi,
I am deploying the kube-prometheus-stack helm chart using ArgoCD:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  goTemplate: true  
  generators:
    - list:
        elements:
          - cluster: my-cluster
            gitBranch: my-namespace
  template:
    metadata:
      name: '{{ .cluster }}-{{ .name | default "kube-prometheus-stack" }}'
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "test"
      project: test
      source:
        path: prometheus
        repoURL: git@github.com:repo/infrastructure.git
        targetRevision: '{{ .gitBranch }}'
        helm:
          valueFiles:
            - "values.yaml"
            - "values-{{ .cluster }}.yaml"
      syncPolicy:
        syncOptions:
        # - ServerSideApply=true
        - ApplyOutOfSyncOnly=true
        - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: "external-secrets.io"
          kind: ExternalSecret
          jsonPointers:
            - /spec/dataFrom/0/extract/decodingStrategy
            - /spec/dataFrom/0/extract/metadataPolicy
        - group: "apps"
          kind: DaemonSet
          jsonPointers:
            - /spec/template/spec/containers/0/resources
        - group: "admissionregistration.k8s.io"
          kind: MutatingWebhookConfiguration
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
        - group: "admissionregistration.k8s.io"
          kind: ValidatingWebhookConfiguration
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
```

I'm using this configuration with ApplicationSets cause I want to later apply it to other clusters. It create all the resources but it stays changing between Syncing and OutOfSync due to the Clusterrole "my-cluster-kube-p-operator". The issue is in the definition of the ClusterRole manifest file found in **_kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml_**, at the end of the definition there is condition in order to add the **_discovery.k8s.io apiGroup_**

```
{{- if .Capabilities.APIVersions.Has "discovery.k8s.io/v1/EndpointSlice" }}
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - create
  - list
  - watch
  - update
  - delete
{{- end }}
```
this provoques the following output seen in ArgoCD in the CusterRole I mentioned before
![Screenshot 2024-10-25 at 8 55 01 a m](https://github.com/user-attachments/assets/2498605c-a192-47a5-bc3c-c63e5b866c5f)

**Expected behavior**

Current sync status: Sync

ArgoCD version 

```
argocd-server: v2.6.3+e05298b
  BuildDate: 2023-02-27T14:40:19Z
  GitCommit: e05298b9c6ab8610104271fa8491f019fee3c587
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Comment by pablo-balboa-team** [comment]
Already fixed the issue using ignoreDifferences and jqPathExpressions, if someone finds this helpful, here is the solution:
```
- group: "rbac.authorization.k8s.io"
        kind: ClusterRole
        jqPathExpressions:
          - .rules[] | select (.apiGroups == ["discovery.k8s.io"])
```
this will tell ArgoCD to ignore the apiGroup "discovery.k8s.io" when creating the ClusterRole in kube-prometheus.stack
