### ISSUE TITLE
ApplicationSets' Progressive Sync stuck after upgrade to v2.12

### ISSUE THREAD

**Issue by offzale** [argoproj/argo-cd#20576]
**Describe the bug**

After upgrading ArgoCD to **v2.12.6** from v2.11.7, all applicationsets have gotten stuck.  The sync does not get triggered, although changes are detected.  See below the logs the applicationset-controller is writting for all applicationsets in the cluster.

I also tried to upgrade to **v2.12.3**, as v2.12.4 was introducing relevant changes to applicationsets. However, I got the same result.
Last I tried upgrading to **v2.12.0**, just in case this was necessary for to upgrade. But I faced the same issue. Therefore, this is happening since v2.12.0.

It seems like it requires a field to be set under `applicationStatus`.  However, that field should not be managed by the user but by the controller, right?

Please let me know if any further information would become handy to debug.

**Version**

```shell
v2.12.0
v2.12.3
v2.12.6
```

**Logs**

```
applicationset-controller {"applicationset":{"Namespace":"argocd","Name":"istio"},"level":"error","msg":"unable to set application set status: ApplicationSet.argoproj.io \"istio\" is invalid: [applicationStatus[0].targetRevisions: Required value, applicationStatus[1].targetRevisions: Required value, applicationStatus[2].targetRevisions: Required value, applicationStatus[3].targetRevisions: Required value]","time":"2024-10-28T08:43:25Z"} 
```

**Comment by andrii-korotkov-verkada** [comment]
Can you share your application set yaml, please?

**Comment by offzale** [comment]
@andrii-korotkov-verkada here you go

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argo
spec:
  generators:
  - list:
      elements:
      - name: base
        component: base
      - name: cni
        component: cni
      - name: discovery
        component: istiod
      - name: ingressgateway-internetfacing
        component: gateway
  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: istioComponent
          operator: In
          values:
          - base
      - matchExpressions:
        - key: istioComponent
          operator: In
          values:
          - cni
      - matchExpressions:
        - key: istioComponent
          operator: In
          values:
          - discovery
      - matchExpressions:
        - key: istioComponent
          operator: In
          values:
          - gateway
  goTemplate: true
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.slack: platform-staging-alerts
      labels:
        istioComponent: '{{.component}}'
      name: istio-{{.name}}
      namespace: argo
    spec:
      destination:
        namespace: istio-system
        server: https://kubernetes.default.svc
      project: cluster
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: "ValidatingWebhookConfiguration"
          jsonPointers:
          - /webhooks/0/failurePolicy
      sources:
      - repoURL: https://istio-release.storage.googleapis.com/charts
        chart: '{{.component}}'
        targetRevision: 1.23.3
        helm:
          ignoreMissingValueFiles: true
          parameters:
          - name: global.hub
            value: gcr.io/istio-release
          - name: podAnnotations.istioVersion
            value: 1.23.3
          valueFiles:
          - $values/applications/istio/{{.name}}/values.yaml
          - $values/applications/istio/{{.name}}/staging/values.yaml
          - $values/applications/istio/{{.name}}/secrets.yaml
          - $values/applications/istio/{{.name}}/staging/secrets.yaml
      - repoURL: https://github.com/arexio/aws-kubernetes-tf.git
        targetRevision: HEAD
        path: applications/istio/{{.name}}
        directory:
          exclude: '{application.yaml,kustomization.yaml,secrets.yaml,values.yaml}'
          include: '*.yaml'
        ref: values
      - repoURL: https://github.com/arexio/aws-kubernetes-tf.git
        targetRevision: HEAD
        path: applications/istio/{{.name}}
        directory:
          exclude: '{*/secrets.yaml,*/values.yaml}'
          include: 'staging/*.yaml'
          recurse: true
      revisionHistoryLimit: 5
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - FailOnSharedResource=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
```
