### ISSUE TITLE
ApplicationSet "goTemplateOptions" = ["missingkey=error"] should not error when an undefined value is handled with the default function

### ISSUE THREAD

**Issue by pre** [argoproj/argo-cd#20594]
# Summary

ApplicationSet provides `"goTemplateOptions" = ["missingkey=error"]` which will fail when a template key does not exist in the source manifest. This is what I would want: fail instead of defaulting to an empty value.

However, when I intentionally leave a key out and cover it's absence with `default`, argocd-applicationset-controller spits out an error:

```
"error":"failed to execute go template acme-service/bs-cluster/{{.acmeService.name}}/{{ .acmeService.subPath | default \"landscapes/default\" }}: template: :1:70: executing \"\" at \u003c.acmeService.subPath\u003e: map has no entry for key \"subPath\""
```

ApplicationSet: example `spec.template.spec.source.path`

```
spec:
  generators:
  - git:
      files:
      - path: cloud-release/bs-cluster/*.yaml
[..]
  template:
    spec:
      source:
        path: acme-service/bs-cluster/{{.acmeService.name}}/{{ .acmeService.subPath | default "landscapes/default" }}
[..]
```

Git generator example source yaml:

```
acmeService:
  name: reloader
  namespace: reloader
  # subPath: xyz <-- By default undefined (covered by `| default`), but allows an exception when needed 
release:
  targetRevision: env/dev
```

# Motivation 

Flexible configuration for the Git generator by allowing a value be defined only when it is needed.

# Proposal

Fail with an error when there is an unhandled blank value.

Allow an undefined value if it are handled with eg. `| default`.
