### ISSUE TITLE
Enhance git generator with value files

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argo-cd#20593]
# Summary

I would propose to enhance the git generator to be able to fetch values from a file, in addition to the values directly provided as key/values

# Motivation

Let's say I have two sources to templatize my Applications: a list of tenants with their configurations and a file containing the version of the application to deploy, and technical information not related to the tenants.

Today, if we want to provide values from different files to templatize an Application using an ApplicationSet, we need to create a matrix like so:

```yaml

spec:
  generators:
    - matrix:
        generators:
          - git:
            repoUrl: http://myGitRepo
            revision: HEAD
            files:
              - path/to/tenants/*.yaml
            pathParamPrefix: "tenant"
          - git:
            repoUrl: http;//myGitRepo
            revision: HEAD
            files:
            - path/to/appConfig/{{.tenant.version}}/appconfig.yaml
```

This complexify the lisibility, especially if we multiply the number of file sources (ending up with matrix of matrix of...)

# Proposal

I would propose to be able to provide values as files inside a git generator, to be applied on top of the value provided by the `files`.
This would avoid Cartesian product across generators.

```yaml

spec:
  generators:
    - matrix:
        generators:
          - git:
            repoUrl: http://myGitRepo
            revision: HEAD
            files:
              - path/to/tenants/*.yaml
            pathParamPrefix: "tenant"
            valueFiles:
            - path/to/another/someBaseConfig.yaml
            - path/to/appConfig/{{.tenant.version}}/appconfig.yaml
```

The `valueFiles` would be merged from bottom to top, like the helm values at Application level.
