### ISSUE TITLE
ApplicationSet not allowing environment-specific values.yaml files outside the chart directory

### ISSUE THREAD

**Issue by tomlnd** [argoproj/argo-cd#20604]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to create an ApplicationSet that would deploy 2 apps (a frontend & a backend in separated charts) from inside `apps/` folder in git, and choose the `values.yaml` for them from `tenants/` folder, which is in the git repo's root instead of under the charts' folder.

This results in this error:

```shell
Failed to load target state:
failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached):
`helm template . --name-template frontend-application --namespace env-xxx --kube-version 1.27 --values <path to cached source>/tenants/*.yaml <api versions removed> --include-crds` failed
exit status 1: Error: open <path to cached source>/tenants/*.yaml: no such file or directory
```

The repo structure would look like this:

```shell
.
├── apps
│   ├── frontend
│   │   ├── Chart.lock
│   │   ├── charts
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   └── values.yaml
│   └── backend
│       ├── Chart.lock
│       ├── charts
│       ├── Chart.yaml
│       ├── templates
│       └── values.yaml
└── tenants
    ├── dev-values.yaml
    └── prod-values.yaml
```

And the ApplicationSet like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'https://gitlab.com/example/gitops-repo.git'
        revision: master
        directories:
          - path: apps/frontend
          - path: apps/backend
  template:
    metadata:
      name: '{{ .path.basename }}-application'
    spec:
      project: default
      sources:
        - repoURL: 'https://gitlab.com/example/gitops-repo.git'
          targetRevision: master
          path: '{{ .path.path }}'
          helm:
            valueFiles:
              - /tenants/*.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'env-{{ .path.basename }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
```

Is it prohibited by design to access `values.yaml` files outside the chart folder itself? This way we could add new envs / tenants just by adding a new `values.yaml` file under the `/tenants/` folder with edited parameters, compared to the charts' default `values.yaml` in `apps/frontend/values.yaml` and `apps/backend/values.yaml`. Or would there be a better way of managing these, that would also work with ArgoCD?

**Version**

```shell
v2.12.6
```

**Comment by aali309** [comment]
@andrii-korotkov-verkada can you please assign me this issue as well. Thnx.

**Comment by carlosrodfern** [comment]
@tomlnd, yes,  by design, the values must be inside the chart; including your environment specific ones.

**Comment by tomlnd** [comment]
I got this working the way I originally wanted (keeping everything in one repo, and have tenant-specific values.yaml files outside the charts' folders) by playing around with the generators.

I switched the `generators[].git.directories[].path` value to point to the tenants' folder at repo root, instead to the /apps folder, like previously. And added a list-generator for the apps I wanted to include in this applicationset under the /apps folder.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://gitlab.com/example/gitops-repo.git'
              revision: master
              directories:
                - path: 'tenants/*'
          - list:
              elements:
                - app: backend
                - app: frontend
  template:
    metadata:
      name: 'tenant-{{path.basename}}-{{app}}'
    spec:
      project: production
      source:
        repoURL: 'https://gitlab.com/example/gitops-repo.git'
        targetRevision: master
        path: 'apps/{{app}}'
        helm:
          valueFiles:
            - '/tenants/{{path.basename}}/values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'tenant-{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
```

The repo structure is now the following:

```
.
├── applicationset.yaml
├── apps
│   ├── backend
│   │   ├── Chart.yaml
│   │   └── values.yaml
│   └── frontend
│       ├── Chart.yaml
│       └── values.yaml
└── tenants
    ├── alice
    │   └── values.yaml
    └── bob
        └── values.yaml
```

This successfully creates 2 namespaces (tenant-alice & tenant-bob), and creates 2 applications per tenant (tenant-alice-frontend, tenant-alice-backend & tenant-bob-frontend, tenant-bob-backend), while keeping everything in one repo and having the tenants' values.yamls separated.

```
NAMESPACE   NAME                          SYNC STATUS   HEALTH STATUS
argocd      tenant-alice-backend          Synced        Healthy
argocd      tenant-alice-frontend         Synced        Healthy
argocd      tenant-bob-backend            Synced        Healthy
argocd      tenant-bob-frontend           Synced        Healthy
```
