### ISSUE TITLE
UI Support for Custom CRD Resource Icons

### ISSUE THREAD

**Issue by ap0phi5** [argoproj/argo-cd#20636]
# Summary

It would be great if we were able to add custom icons for custom resources that are created off the back of CRD installations. Currently only a subset of the core Kubernetes resources are supported in ArgoCD. These were added about 5 years ago and haven't been updated since: https://github.com/argoproj/argo-cd/tree/master/ui/src/assets/images/resources

# Motivation

To give two examples of this:

## 1) Google Cloud - Config Connector CRD

Config Connector CRD allows external cloud resources to be created within Kubernetes. Here, a Cloud SQL Postgres Database resource has been created: 
![image](https://github.com/user-attachments/assets/fb13c510-f579-4705-9e12-29a7889b8dcc)

It would be great to be able to see this, instead of a grey blob:
![image](https://github.com/user-attachments/assets/d57d37ad-f45a-4575-9657-8d5aedff2cd9)

SVGs of all the Google Cloud icons are available here: https://cloud.google.com/icons

## 2) Strimzi Kafka CRD

Another example would be https://strimzi.io/ - resources could include zookeeper instances, brokers etc

# Proposal

_How do you think this should be implemented?_

I recon this could be done in several ways;

a) Adding the SVG files (with an index) as a volume to ArgoCD server
b) Update the config map with key-values - the values referencing URIs where to source the remote SVG/image from.

Example of b)

```
apiVersion: v1
kind: ConfigMap
metadata:
  ...
  name: argocd-cm
data:
  ui.cssurl: "https://www.example.com/my-styles.css"
  ui.customresourceicons:
    sqlinstance: "https://raw.githubusercontent.com/GoogleCloudPlatform/devrel-demos/refs/heads/main/app-dev/party-game/public/google-cloud-icons/cloud_sql.svg"
    someresource: "https://anotherURI.com/someotherresource.svg"
```
