### ISSUE TITLE
Significant Latency in ArgoCD Notification Generation (~10 Minutes) for Synchronization Events

### ISSUE THREAD

**Issue by jwalant527** [argoproj/argo-cd#20659]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
We’ve recently implemented Argo CD notifications to track synchronization and deployment status events, specifically sending these notifications to a Webhook. The webhook in turn sends these notifications to a Kafka topic. However, we’re experiencing significant latency, where there’s an approximate 10-minute+ delay between an actual synchronization event (such as a deployment) and the notification being generated and sent to the Webhook.

**To Reproduce**
https://gitlab.be-md.ncbi.nlm.nih.gov/pd/do/p2/cd/agents/be-clusters/deployment-notifier/-/tree/feat/CD-6874-test?ref_type=heads

**Expected behavior**

Notifications should be generated and sent in near real-time (or as close as possible) after a synchronization event is triggered.

**Actual Behavior**

There is an approximate 10-minute delay between a synchronization event occurring and the Argo CD notification being generated and sent.

**Screenshots**:
Here is a screenshot of my argocd-notifications-cm.yml:

![image](https://github.com/user-attachments/assets/9abb20d3-2e33-4a18-a93d-cd1d4a15fd1b)

To be clear, the notifications are coming through, but with a significant delay.

**Comment by andrii-korotkov-verkada** [comment]
Can you share the following, please?
* ArgoCD version
* Notification controller logs for a given application
* Application controller logs for a given application
There are some structured fields you can filter on, like `application`, which may or may not be preceded by a namespace.

**Comment by gallolp** [comment]
I am observing the same 10 minute delay for triggers with the same configuration as the OP. That is, check for all possible values of `operationState.phase` (except Terminating) and all possible values of `health.status`.

ArgoCD version: `v2.11.5+c4b283c`
No log output on the notifications-controller.

**Comment by gallolp** [comment]
As a workaround, moving the checks to individual items on the same trigger seems to have solved the issue for me.
Maybe there's a debounce on each item??

For example going from:

```yaml
trigger.trgSyncPhase: |
  - description: Application sync phase changed
    send: [tplSyncPhase]
    when: app.status.operationState != nil and app.status.operationState.phase in ['Running', 'Error', 'Failed', 'Succeeded']
```

To:

```yaml
trigger.trgSyncPhase: |
  - description: Application sync phase changed
    send: [tplSyncPhase]
    when: app.status.operationState != nil and app.status.operationState.phase == "Running"
  - description: Application sync phase changed
    send: [tplSyncPhase]
    when: app.status.operationState != nil and app.status.operationState.phase == "Error"
  - description: Application sync phase changed
    send: [tplSyncPhase]
    when: app.status.operationState != nil and app.status.operationState.phase == "Failed"
  - description: Application sync phase changed
    send: [tplSyncPhase]
    when: app.status.operationState != nil and app.status.operationState.phase == "Succeeded"
```

Sends consecutive events immediately so far for me.

The nil check is for the problem described in #15541 see this [comment](https://github.com/argoproj/argo-cd/issues/15541#issuecomment-1795339338)

Hope it helps.
