### ISSUE TITLE
argocd appset generate doesn't work when login with --core

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argo-cd#20692]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The appset generate from the argocd CLI doesn't work when being logged with the `--core` option.

**To Reproduce**

- argocd login --core
- argocd appset generate anyappset.yaml

**Expected behavior**

Should generate the appset

**Screenshots**

**Version**
2.13.0

**Logs**
```
error generating params error="error getting project default: no kind is registered for the type v1alpha1.AppProject in scheme \"pkg/runtime/scheme.go:100\""
```

**Comment by druchoo** [comment]
@OpenGuidou, are you experiencing this issue with the Git Generators or others as well?

I have a similar issue where I receive the same error but only for ApplicationSets using the GitGenerator. Cluster, List and Matrix all seem to work without issue.


```
❯ argocd appset create --dry-run appset.yaml
2024/11/14 16:56:56 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
ERRO[0003] error generating params                       error="error getting project default: no kind is registered for the type v1alpha1.AppProject in scheme \"pkg/runtime/scheme.go:100\"" generator="&{0x14001bb5cc0 argocd}"
ERRO[0003] error generating application from params      applicationset=cluster-addons error="error getting project default: no kind is registered for the type v1alpha1.AppProject in scheme \"pkg/runtime/scheme.go:100\"" generator="{nil nil &GitGenerator{RepoURL:https://github.com/argoproj/argo-cd.git,Directories:[]GitDirectoryGeneratorItem{GitDirectoryGeneratorItem{Path:applicationset/examples/git-generator-directory/cluster-addons/*,Exclude:false,},},Files:[]GitFileGeneratorItem{},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
ERRO[0003] finished unary call with code Unknown         error="unable to generate Applications of ApplicationSet: error generating applications: error getting project default: no kind is registered for the type v1alpha1.AppProject in scheme \"pkg/runtime/scheme.go:100\"" grpc.code=Unknown grpc.method=Create grpc.service=applicationset.ApplicationSetService grpc.start_time="2024-11-14T16:57:00-05:00" grpc.time_ms=350.664 span.kind=server system=grpc
FATA[0003] rpc error: code = Unknown desc = unable to generate Applications of ApplicationSet: error generating applications: error getting project default: no kind is registered for the type v1alpha1.AppProject in scheme "pkg/runtime/scheme.go:100"
```


<details>
  <summary>Git Generator ApplicationSet</summary>
  
  ```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/argoproj/argo-cd.git
      revision: HEAD
      directories:
      - path: applicationset/examples/git-generator-directory/cluster-addons/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  ```
</details>
