### ISSUE TITLE
Sync windows free text

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#20723]
# Summary

When navigating in sync windows it is complex to understand why they are here. Are they still applicable... It is even more complicated when they have been created manually

# Motivation

Adding a sync windows free text zone could help referencing an incident number for example or JIRA issue. 

# Proposal

Add a non mandatory free text field such as `description`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  syncWindows:
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    applications:
    - '*-prod'
    manualSync: true
    description: |
      INC123456789, contact group@organization.com
```

# Additional

To consider as well here: https://github.com/argoproj/argo-cd/issues/11755
