### ISSUE TITLE
RBAC not active with direct SSO

### ISSUE THREAD

**Issue by andreas-p** [argoproj/argo-cd#20748]
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

I've installed `argocd: v2.13.0+347f221` from Helm chart argo/argo-cd 7.7.0, and configured my local OIDC provider using minimal configuration according to https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#existing-oidc-provider:
```
 admin.enabled: false
 url: argocd.my-site.com
 oidc.config: |
    name: My OIDC
    issuer: https://oidc.my-site.com
    clientID: TheId
    clientSecret: TheSecret
```
This works fine, I can login, and the User Info shows my email address and all groups I'm in, but I have all privileges, although RBAC is configured like this:

```
apiVersion: v1
kind: ConfigMap
  name: argocd-rbac-cm
  namespace: argocd
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: ""
  policy.default: role:readonly
  policy.matchMode: glob
  scopes: '[groups]'
```

Updating the configmap with policy.default="" (argocd-server logs "RBAC ConfigMap 'argocd-rbac-cm' updated"), there should be no privileges at all, but I'm still admin-privileged, so apparently argocd-server thinks it hasn't any valid user configuration.

There's one anomaly that might be relevant: some group names provided by SSO include spaces. Still, all groups are listed correctly under User Info.

**Comment by romanpanov993** [comment]
I faced the same issue. And I don't have any groups with spaces.
Did you find any workaround?

**Comment by romanpanov993** [comment]
I tried to connect via DEX and got the same behaviour. I can get groups list, I can login via DEX, but RBAC doesn't apply group's permissions.

I tried to login with the following policy:
`
policy.csv: |
      g, my-group, role:readonly
`
without default.policy. And I have full access in Argo.

**Comment by romanpanov993** [comment]
@andreas-p check if you have policies on application's projects. It was my root cause. I deleted policies from projects and it started to work

**Comment by andreas-p** [comment]
My projects are very minimal:

```yaml

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: System Apps
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
 ```
