### ISSUE TITLE
Pull Request generator not working for Bitbucket Cloud

### ISSUE THREAD

**Issue by mpitt** [argoproj/argo-cd#20769]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using the Pull Request generator with Bitbucket Cloud results in the error

```
error listing repos: error unmarshalling json to type '[]BitbucketCloudPullRequest': json: cannot unmarshal object into Go struct field BitbucketCloudPullRequest.author of type string
```

It looks like the error can be traced to adding the `author` field with the wrong type in [[1]](https://github.com/argoproj/argo-cd/pull/18974/files#diff-8523234aa497230c1a958d497fd318024e3659df83f15163537f2a4f98a43e77): it was added as a _string_ but in the Bitbucket Cloud API it's an _object_ [[2]](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-get)

**To Reproduce**

Create an ApplicationSet with the Pull Request generator:

```yaml
spec:
  generators:
    - pullRequest:
        bitbucket:
          basicAuth:
            passwordRef:
              key: password
              secretName: argocd-controller-secret
            username: Srv-CICD-Robot
          owner: REDACTED
          repo: REDACTED
        filters:
          - branchMatch: .*/.*REDACTED.*/.*
        requeueAfterSeconds: 60
```

**Expected behavior**

The PR generator can parse the Bitbucket API response, where the `author` field is an object and not a string.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.0+347f221
```

**Logs**

```
error listing repos: error unmarshalling json to type '[]BitbucketCloudPullRequest': json: cannot unmarshal object into Go struct field BitbucketCloudPullRequest.author of type string
```
