### ISSUE TITLE
Change from server is not considered as a diff

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argo-cd#20765]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When a change is done on a resource directly on the target, it is not detected as a diff by Argo CD, and so not self-healed.

**To Reproduce**

1. Create a simple Application deploying a ConfigMap (for example pointing to https://github.com/OpenGuidou/simple-configmap.git) 
2. Add a new field in the configmap on the server
3. It is not seen as a change

**Expected behavior**

It should be flagged as a diff and self-healed if the option is set

**Screenshots**

Desired manifest:
![image](https://github.com/user-attachments/assets/f51623c4-00e2-429a-beb9-279a2c7e1d2d)

Live manifest:
![image](https://github.com/user-attachments/assets/2303ad84-d1bd-4554-9866-070da48cba2e)

Diff:
![image](https://github.com/user-attachments/assets/bcf626c8-2cdd-4a91-8f3b-383644909dff)

Application:

```yaml
project: default
source:
  repoURL: https://github.com/OpenGuidou/simple-configmap.git
  path: .
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    selfHeal: true

```

**Version**

```shell
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T15:31:20Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T15:31:20Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.1 2024-04-04T17:11:54Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0

```
