### ISSUE TITLE
Can't terminate sync outside of sync window

### ISSUE THREAD

**Issue by hanikesn** [argoproj/argo-cd#20799]
**Describe the bug**

Can't terminate outstanding sync outside of sync window.

**To Reproduce**

1. Configure a sync window for an application and enable auto sync
2. Apply an update to the Application using kubectl with the following options:
    ```yaml
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      # ...
    operation: null
    spec:
      # ...
      source:
        # ...
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - FailOnSharedResource=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
    ``` 
3. The sync will get started, but is blocked `Sync operation blocked by sync window`
4. Try terminating the sync in the web interface

**Expected behavior**

Even outside a sync window I'm able to terminate an outstanding sync.

**Screenshots**

![image](https://github.com/user-attachments/assets/ad29df8a-dc01-46c9-a343-b52b202377b8)

**Version**

```shell
v2.12.6+4dab5bd
```
