### ISSUE TITLE
Kustomize 5.4.0+ regression: null values set in HelmChartInflationGenerator are ignored

### ISSUE THREAD

**Issue by erwanval** [argoproj/argo-cd#20808]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Kustomize's HelmChartInflationGenerator ignore null values, which prevent removal of default values set in source chart's values.yaml.  
This seems to be a regression from Kustomize 5.4.0 (see [kustomize issue](https://github.com/kubernetes-sigs/kustomize/issues/5803)).  
It worked properly with ArgoCD v2.11.0 (bundled with kustomize 5.2.1).

**To Reproduce**

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helmchartinflation-crowdsec.yaml
```

```yaml
# helmchartinflation-crowdsec.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: crowdsec
releaseName: crowdsec
namespace: crowdsec
name: crowdsec
repo: https://crowdsecurity.github.io/helm-charts
version: 0.13.0
includeCRDs: true
valuesInline:
  lapi:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: null # We want to remove the default from values.yaml
        memory: 100Mi
    persistentVolume:
      config:
        enabled: false
      data:
        enabled: false
  agent:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: null # We want to remove the default from values.yaml
        memory: 100Mi
    acquisition:
      - namespace: ingress-nginx
        podName: ingress-nginx-controller-*
        program: nginx
```

**Expected behavior**

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: crowdsec-agent
spec:
  [...]
  template:
    [...]
    spec:
      [...]
      containers:
        [...]
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
```
**Actual Output**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: crowdsec-agent
spec:
  [...]
  template:
    [...]
    spec:
      [...]
      containers:
        [...]
          resources:
            limits:
              cpu: 500m # default from values.yaml still set
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
```

**Screenshots**

**Version**
```shell
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
