### ISSUE TITLE
[BUG] Can not pull helm from private repository in AWS ECR with 403 forbidden.

### ISSUE THREAD

**Issue by laiminhtrung1997** [argoproj/argo-cd#20810]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Can not create an application with a helm chart as OCI in AWS ECR. The status is always 403 forbidden.

**To Reproduce**

Create credential as secret
```
kind: Secret
apiVersion: v1
metadata:
  name: argocd-aws-ecr-credential
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  enableOCI: "true"
  password: $(aws ecr get-login-password --region $region)
  type: helm
  url: $aws_id.dkr.ecr.$region.amazonaws.com
  username: AWS
```

Create repository as secret
```
kind: Secret
apiVersion: v1
metadata:
  name: argocd-aws-ecr-redis-chart
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  enableLfs: "true"
  enableOCI: "true"
  forceHttpBasicAuth: "true"
  insecure: "true"
  name: $some_path/redis
  project: default
  type: helm
  url: $aws_id.dkr.ecr.$region.amazonaws.com
```

Create application
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: ''
    repoURL: $aws_id.dkr.ecr.$region.amazonaws.com
    targetRevision: 18.17.1
    chart: $some_path/redis
  sources: []
  project: default
```

**Expected behavior**

Create the application successfully.

**Screenshots**

![image](https://github.com/user-attachments/assets/157dac16-19c0-4647-ad69-158d07de2049)

**Version**

```shell
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T12:29:51Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.22.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**

```
time="2024-11-16T05:29:21Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = error pulling OCI chart: failed to pull OCI chart: failed to get command args to log: `helm pull oci://$aws_id.dkr.ecr.$region.amazonaws.com/$some_path/redis --version 18.17.1 --destination /tmp/833c8113-9a86-4474-b89e-7106e2f627b0 --insecure-skip-tls-verify` failed exit status 1: Error: unexpected status from HEAD request to https://$aws_id.dkr.ecr.$region.amazonaws.com/v2/$some_path/redis/manifests/18.17.1: 403 Forbidden" grpc.code=Unknown grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2024-11-16T05:29:21Z" grpc.time_ms=305.181 span.kind=server system=grpc
```

**Comment by laiminhtrung1997** [comment]
Dear @andrii-korotkov-verkada @andrii-korotkov @andrii-codefresh 
Could you please check the issue? Thank you.

**Comment by andrii-korotkov-verkada** [comment]
I haven't seen something like this before in the manifests.
```
password: $(aws ecr get-login-password --region $region)
```
Does it work, do you put an actual password there, or does it literally uses this string as a password?

**Comment by laiminhtrung1997** [comment]
@andrii-korotkov-verkada 
Oh, just a how-to tell you where the password I got from. It is just an actual string as a password, not a command line.

**Comment by andrii-korotkov-verkada** [comment]
> repoURL: $aws_id.dkr.ecr.$region.amazonaws.com

This looks wrong

**Comment by laiminhtrung1997** [comment]
Hmmmmm. What is wrong with that? The $aws_id and $region are my private values so I have to write like that.

**Comment by andrii-korotkov-verkada** [comment]
No, I mean the URL is ECR url. To my understanding, ECR is used for storing images, wheres manifests usually live somewhere like Github. Correct me if you actually store the manifests in the ECR.

**Comment by laiminhtrung1997** [comment]
I store the manifests of helm charts in the ECR. Do they not support it yet?

**Comment by andrii-korotkov-verkada** [comment]
I don't know. Can you try removing insecure flag?

**Comment by laiminhtrung1997** [comment]
I tried it in the first place but still not working.

**Comment by laiminhtrung1997** [comment]
All the secrets are used for credentials to pull manifests from the repository in AWS ECR. That's all. Is this what you ask for?

**Comment by andrii-korotkov-verkada** [comment]
I guess I'm asking what consumes `argocd-aws-ecr-redis-chart` and `argocd-aws-ecr-credential`, since the names look pretty custom. Sorry for asking a lot of questions. I've never worked with charts stored in ECR.

**Comment by macmiranda** [comment]
@laiminhtrung1997 keep in mind tokens generated with `aws ecr get-login-password` are only valid for 12h.

I'd recommend as a first step for you to create a Helm OCI repository via the UI. Go to Settings -> Repositories -> Connect repo.

Make sure you:
- generate a fresh token
- connect via HTTPS
- type Helm (OCI will be auto-detected)
- for the repository URL, use the registry URL (without the repo path)
- username: AWS
- password: <your recently generated token>

Check for a successful connection status. If so, you can find the corresponding secret that you would need to create in the argo cd namespace.

Now, you will need to find a way to refresh that token every 12h, Argo won't do it for you.

**Comment by laiminhtrung1997** [comment]
@macmiranda 

I created a repo via UI with connect successfully. However, when I created an application from it, an error occurred, so I don't know what I am missing.

**Comment by macmiranda** [comment]
What's the output of `helm pull oci://$aws_id.dkr.ecr.$region.amazonaws.com/$some_path/redis --version 18.17.1` if you run it yourself on the command line after running
```
aws ecr get-login-password \
     --region $region | helm registry login \
     --username AWS \
     --password-stdin $aws_id.dkr.ecr.$region.amazonaws.com
```
I'm assuming that you've set these variables in your shell as well.

**Comment by laiminhtrung1997** [comment]
![image](https://github.com/user-attachments/assets/181ce40b-7257-48fc-afe2-a61635fe9acd)

Of course, I can pull it.

**Comment by laiminhtrung1997** [comment]
>Try in the shell with --insecure-skip-tls-verify as being run by Argo.
Pull successfully.

>Try removing the path field from the source - IIUC it's not needed for helm charts.
There are many images in ECR, including charts and docker images, so I must use the path to distinguish them.

>Check the logs to see if helm registry login or something similar pops up. May need to enable debug level.
Ok, I will reproduce it and collect the full log at the debug level.

**Comment by macmiranda** [comment]
I think @andrii-korotkov-verkada means:

![image](https://github.com/user-attachments/assets/4273b726-3297-4dd4-88ab-ef45e45e4bba)

**Comment by laiminhtrung1997** [comment]
Wait a minute, when I create an Application via UI, the path field is required.

**Comment by laiminhtrung1997** [comment]
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-11-20T02:48:27Z"
  generation: 5
  name: redis
  namespace: argocd
  resourceVersion: "4819069"
  uid: 9b3a9d4d-2d0a-4be8-b3c7-7c3a58272bcf
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    chart: $some_path/redis
    repoURL: $aws_id.dkr.ecr.$region.amazonaws.com
    targetRevision: 18.17.1
status:
  conditions:
  - lastTransitionTime: "2024-11-20T02:55:34Z"
    message: "Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = error pulling OCI chart: failed to pull OCI chart: failed to get command args to log: `helm pull oci://$aws_id.dkr.ecr.$region.amazonaws.com/$some_path/redis --version 18.17.1 --destination /tmp/9454b56f-f884-4056-9d1a-aab0859a9694` failed exit status 1: Error: unexpected status from HEAD request to https://$aws_id.dkr.ecr.$region.amazonaws.com/v2/$some_path/redis/manifests/18.17.1: 403 Forbidden"
    type: ComparisonError
  controllerNamespace: argocd
  health:
    status: Healthy
  reconciledAt: "2024-11-20T02:55:34Z"
  sync:
    comparedTo:
      destination:
        name: in-cluster
        namespace: argocd
      source:
        chart: $some_path/redis
        repoURL: $aws_id.dkr.ecr.$region.amazonaws.com
        targetRevision: 18.17.1
    status: Unknown
```

@andrii-korotkov-verkada  @macmiranda 
It is still failed.

**Comment by standrewd** [comment]
@laiminhtrung1997 What are the permissions on your private ecr repository that you're trying to pull from? I had a similar issue that was related to my repo permissions when trying to pull the helm chart in a cluster.

**Comment by macmiranda** [comment]
> @laiminhtrung1997 What are the permissions on your private ecr repository that you're trying to pull from? I had a similar issue that was related to my repo permissions when trying to pull the helm chart in a cluster.

This should be a non-issue since he's using the same token on the CLI and on Argo CD (supposedly).

Just to be clear, @laiminhtrung1997, when you created the repo via the UI, did you remove the secrets that you had created before?

**Comment by laiminhtrung1997** [comment]
@macmiranda 

>This should be a non-issue since he's using the same token on the CLI and on Argo CD (supposedly).

Why is it a non-issue since I was using the same token? If the token on the CLI is successful, so does ArgoCD.

>when you created the repo via the UI, did you remove the secrets that you had created before?

The secret as repo created via UI is a different name than mine created. So I did not.

**Comment by macmiranda** [comment]
> The secret as repo created via UI is a different name than mine created. So I did not.

Because of the way [repo-creds](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-repo-creds-yaml/) work, if they match the url, Argo CD will attempt to use them

Please delete the manually created secret and make sure that you update the secret with a new token on the UI

**Comment by macmiranda** [comment]
> Why is it a non-issue since I was using the same token?

I meant ECR permissions should be a non-issue since the token has been confirmed to be working.

**Comment by laiminhtrung1997** [comment]
@macmiranda 

![image](https://github.com/user-attachments/assets/19967603-b61c-456f-88d6-8862d6dbe3f3)
<img width="955" alt="image" src="https://github.com/user-attachments/assets/f466bace-6f48-4f04-ae01-041120f85ee7">
![image](https://github.com/user-attachments/assets/6c99a024-1640-401c-bca5-a7d411288e61)

The application still fails with 403, even though the repository connects successfully.

**Comment by yurifrl** [comment]
I seem to be experiencing the same issue. Locally, I can successfully pull the chart, but when deployed, it fails.

![CleanShot 2024-12-04 at 19 59 32](https://github.com/user-attachments/assets/bb05bc3b-db52-4c66-930d-2a758d6e6f67)
![CleanShot 2024-12-04 at 19 54 30](https://github.com/user-attachments/assets/57f7dc06-3e1b-424d-aa7f-8f75e39e22e9)
### Setup Details:

Initially, I created the repo using the following configuration:  
```yaml
# Based on: https://medium.com/@prassonmishra330/helm-chart-deployment-with-argocd-and-ecr-f8f95f625a56
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-gen-helm
  namespace: argocd
spec:
  region: us-east-1
  auth:
    jwt:
      serviceAccountRef:
        name: ecr-infra-argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-infra-argocd
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXX:role/EcrArgocd
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-helm
  namespace: argocd
spec:
  refreshInterval: "1h"
  target:
    name: ecr-helm
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        url: XXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com
        type: "helm"
        name: "ecr-helm"
        enableOCI: "true"
        username: "{{ .username }}"
        password: "{{ .password }}"
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: "ecr-gen-helm"
```

Additionally, I tried other approaches, such as creating the repo via the CLI or AWS Management Console. For authentication, I tested both the service account and direct token usage.
![CleanShot 2024-12-04 at 19 54 52](https://github.com/user-attachments/assets/64baf1eb-d12c-4b30-8176-cc00cb7bb7d4)


### Observations:

1. **Local Success:** When I run the `helm pull` command directly from my terminal, everything works perfectly.
2. **Pod Success:** Executing into the pod and manually logging in with credentials also allows the pull to succeed.
3. **Repo URL Issue:** It seems the format of `repoURL` affects the generation of the correct `helm pull` command. For instance:
   - **Incorrect:** Using the `oci://` prefix in `repoURL` results in failure.
   - **Correct:** Removing the `oci://` prefix generates the correct `helm pull` command.

Here’s the relevant application spec I used:  
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
    - repoURL: 492684252576.dkr.ecr.us-east-1.amazonaws.com/charts
      targetRevision: 1.0.0
      chart: support
```

Despite these efforts, the issue persists, and I still encounter authentication or pulling errors when deploying through ArgoCD. Any insights would be appreciated!

**Comment by macmiranda** [comment]
@yurifrl in your case, the failure is probably due to the `repoURL` containing a path. Try without `/charts` and specify the path in the `chart` attribute, e.g. `charts/support`

**Comment by yurifrl** [comment]
You are correct, I moved the chart one / back and it worked, I thought I have tried everything, thank you.

![CleanShot 2024-12-05 at 09 33 11](https://github.com/user-attachments/assets/2250f396-f448-4e57-b62b-a8947c157ebe)

**Comment by beatrizdemiguelperez** [comment]
I struggled a lot with the same thing, finally, at least for me, it is working by adding the ecr repository path to the argocd repository.  Instead of using `$aws_id.dkr.ecr.$region.amazonaws.com` use `$aws_id.dkr.ecr.$region.amazonaws.com/$some_path`

For your case would be 

```
apiVersion: v1
kind: Secret
metadata:                                                                                                                                                                                                                                                                      
  labels:                                                                                                                                                      
    argocd.argoproj.io/instance: sentiment-analysis.yaml                                                                                                       
    argocd.argoproj.io/secret-type: repository                                                                                                                 
    project: sentiment-ecr-helm-charts                                                                                                                         
  name: <my-repo-name>
  namespace: argocd                                                                                                                                            
data:                                                                                                                                                          
  enableOCI: true
  name: <my-repo-name>
  project: default
  type: helm
  url: $aws_id.dkr.ecr.$region.amazonaws.com/$some_path
```
