### ISSUE TITLE
Support ignoreDifferences within string

### ISSUE THREAD

**Issue by DerekTBrown** [argoproj/argo-cd#20873]
# Summary
- A common pattern is to define application-specific options as YAML inside a `ConfigMap`.
- For the same reason as `ignoreDifferences` are supported within Kubernetes manifests, users may need to ignore differences inside a ConfigMap.

# Motivation
For example- there are certain fields within our Kiali `ConfigMap` that show diffs on every update. We would like to suppress those changes in the ArgoCD UI.

# Proposal
```diff
type ResourceIgnoreDifferences struct {
     ...
     JSONPointers           []string `json:"jsonPointers,omitempty" protobuf:"bytes,5,opt,name=jsonPointers"`
     JQPathExpressions      []string `json:"jqPathExpressions,omitempty" protobuf:"bytes,6,opt,name=jqPathExpressions"`
+   YAMLStringIgnoreJQPaths []string `json:"yamlStringIgnoreJQPaths,omitempty" protobuf:"bytes,6,opt,name=yamlStringIgnoreJQPaths"`
```

The behavior would be:
- If `YAMLStringIgnoreJQPaths` is non-empty, all values referred to by `JSONPointers` and `JQPathExpressions` will be parsed as YAML.
- Within those YAMLs, differences in keys referred to within `YAMLStringIgnoreJQPaths` will be ignored.

**Comment by andrii-korotkov-verkada** [comment]
Hm, this seems like it would be inconsistent with how JSONPointers and JQPathExpressions behave currently.

**Comment by andrii-korotkov-verkada** [comment]
I don't fully understand the motivation yet. Wouldn't setting ignoreDifferences on individual keys in the data section work?

**Comment by DerekTBrown** [comment]
> I don't fully understand the motivation yet. Wouldn't setting `ignoreDifferences` on individual keys in the data section work?

Not to my knowledge. Perhaps an example would clarify my proposal. 

Suppose I had a K8s manifest like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-example
data:
   my-file.yaml: | 
       ...
       my_dynamic_key: xxx
```

I want to prevent ArgoCD from detecting changes to `my_dynamic_key` _inside_ the `data."my-file.yaml".my_dynamic_key` string, so I:

```
spec:
  ignoreDifferences:
  - group: core
    kind: ConfigMap
    data:
    - /data/my-file.yaml
    YAMLStringIgnoreJQPaths:
    - my_dynamic_key
```
