### ISSUE TITLE
successfull sync doesn't sync 

### ISSUE THREAD

**Issue by stephaneetje** [argoproj/argo-cd#20875]
I'm using kargo to update the image tag. When argocd syncs from kargo, i can see it uses the right commit sha with my image tag update.
Sync ends successfully, but deployment hasn't been updated and app is still out of sync untill i sync manually.

Argocd version: 2.13

<img width="674" alt="Capture d’écran 2024-11-20 à 23 18 59" src="https://github.com/user-attachments/assets/4a61a59f-6127-4164-a3e8-cfdcd7097dd2">

<img width="773" alt="Capture d’écran 2024-11-20 à 23 19 30" src="https://github.com/user-attachments/assets/17e79aa8-ebf4-49cc-875d-304d8ed007b3">

<img width="527" alt="Capture d’écran 2024-11-20 à 23 21 43" src="https://github.com/user-attachments/assets/be63ecff-f14c-4cc8-acec-662c31d2c5cf">

**Comment by andrii-korotkov-verkada** [comment]
Does it show as out of sync? I saw a similar issue recently. It shows out of sync and not applying all changes in a previous sync, but manual sync can get it to a good state.

**Comment by andrii-korotkov-verkada** [comment]
Can you try to get logs with debug enabled, please?

Try setting this
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  applicationsetcontroller.log.level: debug
  applicationsetcontroller.log.format: json
  controller.log.level: debug
  controller.log.format: json
  notificationscontroller.log.level: debug
  notificationscontroller.log.format: json
  reposerver.log.level: debug
  reposerver.log.format: json
  server.log.level: debug
  server.log.format: json
  ...
```
