### ISSUE TITLE
Split arrays in yaml so that the first line is blank to avoid messy collapse behavior

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#20905]
# Summary

Currently the collapse behavior of something like this is bad:

```yaml
      containers:
        - command:
            - /shared/argocd-dex
            - rundex
          env:
            - name: ARGOCD_DEX_SERVER_LOGFORMAT
              valueFrom:
                configMapKeyRef:
                  key: dexserver.log.format
                  name: argocd-cmd-params-cm
                  optional: true
```

There's a collapse widget to the left of `- command:` but it's ambiguous as to what it should collapse, it could collapse the array element, or it could collapse the `command` key.

If the yaml was automatically presented like this, then one could independently and unambiguously collapse the `-` or `command:`: 
```yaml
      containers:
        -
          command:
            - /shared/argocd-dex
            - rundex
          env:
            - name: ARGOCD_DEX_SERVER_LOGFORMAT
              valueFrom:
                configMapKeyRef:
                  key: dexserver.log.format
                  name: argocd-cmd-params-cm
                  optional: true
```

# Motivation

Typically the first item in `containers:` is something that would itself be collapsible, and it's incredibly frustrating to end up collapsing the **entire container** instead of just the first property for the `container`.

If the yaml was automatically presented like this, then one could easily collapse the various keys of the container without collapsing the entire container

https://cd.apps.argoproj.io/applications/argo-cd?resource=kind%3APod&node=apps%2FDeployment%2Fargocd%2Fargocd-dex-server%2F0
before:
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/b93e468f-bf96-4b25-9c27-edc54d4cfed0">
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/b306e348-a6f7-4c2b-8983-459a0852dc62">

after:
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/fff554f3-a743-4bde-b561-bd5e651bfc1e">
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/8ec29961-cab1-43de-9eeb-3f7d72f9380e">

# Proposal

When encountering an array where the first item in the array is itself collapsible, put the first item on its own line.
