### ISSUE TITLE
Trying to delete a repo I added by mistake and getting "permission denied"

### ISSUE THREAD

**Issue by davidt-gh** [argoproj/argo-cd#20921]
Checklist:

* [ V ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ V ] I've included steps to reproduce the bug.
* [ V ] I've pasted the output of `argocd version`.

**Describe the bug**
I've copy paste git url from bitbucket, not sure why, they provide it with `git clone` command in prefix, and by mistake I've try to add the repo like that.
After I saw the connection status fail and I added it in right way, but now I'm not able to delete the wrong typo, not from CLI and not from UI.

**To Reproduce**
Instead put git http url, add `git clone https://bitbucket.org/workspace/repo.git`

**Expected behavior**
Just allow to delete

**Screenshots**
![image](https://github.com/user-attachments/assets/fa71615c-e89a-45a6-a795-53393c8b8302)

**Version**

```shell
➜  ~ argocd version
argocd: v2.12.6+4dab5bd
  BuildDate: 2024-10-18T21:32:12Z
  GitCommit: 4dab5bd6a60adea12e084ad23519e35b710060a2
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: darwin/arm64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**
This is me trying to delete the repo from CLI
```
➜  ~ argocd repo rm "git clone https://bitbucket.org/workspace/repo.git"
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
FATA[0001] rpc error: code = PermissionDenied desc = permission denied 
```

I did not saw any related logs in ArgoCD NS after trying to run the command or delete from UI, here is the last logs I saw:
![image](https://github.com/user-attachments/assets/6fbdacb8-bfdd-4e3e-82d2-a591a5475350)

**Comment by andrii-korotkov-verkada** [comment]
What's your RBAC configuration? It looks like it has permissions to create, but not delete.

**Comment by davidt-gh** [comment]
> What's your RBAC configuration? It looks like it has permissions to create, but not delete.
But if it's a valid repo it been deleted without any error - only this case.
I did not configured anything related to RBAC, here is my vaulues:

```
global:
  domain: argocd.domain.net

configs:
  params:
    server.insecure: true

dex:
  enabled: false

server:
  ingress:
    hostname: "argocd.domain.net"
    enabled: true
    ingressClassName: nginx
    tls: false
    extraTls:
      - secretName: compamny-net-tls-certificate
        hosts:
          - argocd.domain.net
```

I've found a workaround - which is to delete the secret created by ArgoCD, and it vanished.

**Comment by andrii-korotkov-verkada** [comment]
Sorry, I've meant `argocd-rbac-cm`.

**Comment by davidt-gh** [comment]
> Sorry, I've meant `argocd-rbac-cm`.

Here:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.13.0
    helm.sh/chart: argo-cd-7.7.3
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
data:
  policy.csv: ''
  policy.default: ''
  policy.matchMode: glob
  scopes: '[groups]'
```
