### ISSUE TITLE
Support a list of values as string in the generators selectors

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argo-cd#20943]
# Summary

With the current state of applicationset templating, it's not possible to provide values as a list in a selector `matchExpressions` values, coming from another generator.

# Motivation

Let's take the example of this applicationset:
```yaml
spec:
  generators:
  - list:
      elements:
        - cluster: engineering-dev
          url: https://kubernetes.default.svc
          envs:
            - staging
            - prod
      selector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - {{ .envs }}
```

It's not possible to provide the `envs` variable in the selector `values`.

# Proposal

I would propose to add a field in the matchExpression, to support a list of values as string:
```yaml
spec:
  generators:
  - list:
      elements:
        - cluster: engineering-dev
          url: https://kubernetes.default.svc
          envs:
            - staging
            - prod
      selector:
        matchExpressions:
          - key: env
            operator: In
            valuesString: "staging,prod"
```

This would be a comma-separated list, as a string, that could be filled using templating functions:

```yaml
spec:
  goTemplate: true
  generators:
  - list:
      elements:
        - cluster: engineering-dev
          url: https://kubernetes.default.svc
          envs:
            - staging
            - prod
      selector:
        matchExpressions:
          - key: env
            operator: In
            valuesString: `{{- join "," .envs }}`
```

**Comment by damsien** [comment]
Hello, can I take this issue? 🙂
@OpenGuidou can you confirm that we should have either values or valuesString (both can't be used at the same time).

**Comment by OpenGuidou** [comment]
Sure, go ahead !

It's Indeed a good idea to check only one is provided

**Comment by damsien** [comment]
Thanks!
/assign

**Comment by damsien** [comment]
I took a look at the issue. I am not sure that it is a good idea to add the `valuesString` field since it is redundant. Why not using in this way?
```yaml
spec:
  goTemplate: true
  generators:
  - list:
      elements:
        - cluster: engineering-dev
          url: https://kubernetes.default.svc
          envs:
            - staging
            - prod
      selector:
        matchExpressions:
          - key: env
            operator: In
            values: [`{{- range $index, $env := .envs }}{{ if $index }}, {{ end }}"{{ $env }}"{{- end }}`]
```
The thing is we want to be as much close to the native Kubernetes API as possible. The struct for the [`matchExpressions`](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-references-in-api-objects) does not include the `valuesString` field.
