### ISSUE TITLE
use the "project" field in cluster credentials

### ISSUE THREAD

**Issue by SergeiCherevko** [argoproj/argo-cd#20958]
I use an ApplicationSet to deploy vault-webhook to each cluster using matchLabels.

```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-webhook
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'vault-webhook-{{name}}'
      namespace: argocd
    spec:
      project: devops
      source:
        repoURL: ghcr.io/bank-vaults/helm-charts
        targetRevision: "1.21.2"
        chart: vault-secrets-webhook
        helm:
          releaseName: vswh
          values: |
            ---
            replicaCount: 2
            certificate:
              generate: false
              useCertManager: true
            rbac:
              authDelegatorRole:
                enabled: true
            serviceAccount:
              annotations:
                iam.gke.io/gcp-service-account: vault-webhook@{{project}}.iam.gserviceaccount.com
            env:
              VAULT_ADDR: https://xxx.example.com
              VAULT_PATH: '{{name}}'
            
      destination:
        name: '{{name}}'
        namespace: vault
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

Each cluster retrieves its data from a Secret, for example:
```
apiVersion: v1
kind: Secret
metadata:
  name: global-us-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
data:
  name: xxx
  server: yyy
  ```

Everything works fine, but now I need to add an additional field, like project, to each cluster so I can use it in the service account annotation:
```
            serviceAccount:
              annotations:
                iam.gke.io/gcp-service-account: vault-webhook@{{project}}.iam.gserviceaccount.com
```

I tried to manually update the cluster Secrets by adding a "project" field:
```
apiVersion: v1
kind: Secret
metadata:
  name: global-us-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
data:
  name: xxx
  server: yyy
  project: zzz <---------------------------------------------------------
  ```

However, when I deploy to my clusters, I don't see the variable expanding as expected.
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/68315c07-1a22-45e9-9780-8e1a4844b2e1">

ArgoCD version v2.9.1+58b04e5
