### ISSUE TITLE
OutOfSync due to pod spec with multiple env vars with the same key

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#20979]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Create a pod spec of sorts (we used a cronjob, but presumably a sts, deploy, rs, or pod would also work) that has:
    ```yaml
    ...
            spec:
              containers:
                - env:
                    - name: REPEATED
                      value: 5
                    - name: REPEATED
                      value: 6
    ...
    ```
2. Wait for argocd to try to sync this object.
3. It temporarily says it's Synced and then goes back to Out Of Sync

**Expected behavior**

1. Until ArgoCD's behavior changes, consider including a note about this case in the faq -- "if your application contains an object that contains a bag with multiple conflicting fields but which isn't actually rejected by kubernetes, you may get an out of sync, a simple example of this is two env vars with the same name for the same container"
2. Ideally ArgoCD would identify that providing two env vars with the same name is problematic

**Screenshots**

**Version**

```shell
{
    "Version": "v2.12.4+27d1e64",
    "BuildDate": "2024-09-26T06:36:13Z",
    "GitCommit": "27d1e641b6ea99d9f4bf788c032aeaeefd782910",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```
