### ISSUE TITLE
[Feature request] Ignore resources

### ISSUE THREAD

**Issue by gitgudguy** [argoproj/argo-cd#20988]
# Summary

I need a way to tell argocd to completely ignore a resource with a group and a kind.

# Motivation

on my eks cluster, when upgrading calico from 3.27.4 to 3.28 there is a documented breaking change:
the uid of crd.projectcalico.org/v1 (networkpolicies.crd.projectcalico.org) and projectcalico.org/v3 
(networkpolicies.projectcalico.org) is not the same anymore.
official doc, search "breaking change"
https://docs.tigera.io/calico/3.28/release-notes/
the commit that implemented it (maybe not useful)
https://github.com/projectcalico/calico/pull/9191/commits/1f11a76c4d8665be50a53301642ed2ac42806ce3

This causes argocd to try to upgrade the projectcalico.org/v3 resources and the errore is "not found".
```
Failed sync attempt to redacted-id: 
            one or more synchronization tasks completed unsuccessfully, 
reason: networkpolicies.projectcalico.org "nameoftheresouce" not found,
... not found (retried 5 times).
```

with tigera/calico 3.27.4, argocd does not even track the projectcalico.org/v3 resources, infact when I upgrade tigera/calico to 3.28 I see the network policies number being doubled in argocd UI.

Note: in my charts I'm only creating a crd.projectcalico.org/v1 resource, the projectcalico.org/v3 is created automatically by tigera/calico

By reading the argocd documentation I've already tried those solutions, but nothing worked:
- adding to argocd-cm
```
  resource.customizations.ignoreResourceUpdates.all: |
    jsonPointers:
    - /metadata
```
(the uid field is under metadata, I've tried `/metadata/uid` too, but still didn't work)

- adding to the network policy
```
annotations:
    argocd.argoproj.io/apply-resources-updates: "false"
    argocd.argoproj.io/hook: Skip
    argocd.argoproj.io/compare-options: IgnoreExtraneous
```
- adding in the application resource
```
  ignoreDifferences:
      - group: projectcalico.org
        kind: NetworkPolicy
        jsonPointers:
          - /metadata/uid
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
```
argocd chart version 7.6.12
argocd version 2.12.6

# Proposal
A simple way of telling argocd to ignore a certain resource by group and kind

# How do you think this should be implemented?
Through annotation, or application file, or globally in argocd-cm. Any working solution would be good for my use case.
