### ISSUE TITLE
Application objects are unsetting values when they match the default

### ISSUE THREAD

**Issue by nwsparks** [argoproj/argo-cd#21002]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

we are creating `applications` via terraform - basically the same thing as doing it via a yaml file with kubectl apply.

something is unsetting values when they match the default value. this is causing a perpetual diff in terraform since our manifest no longer matches what is in the cluster. the removal of the fields only seems to occur once the app has successfully deployed and seems possibly linked to this https://github.com/argoproj/argo-cd/blob/02d6866f8a8276c455986672f2e8709232292e76/cmd/util/app.go#L386

example:

```
2024-11-25T11:35:08.548-0500 [INFO]  provider.terraform-provider-kubectl_v2.1.3: 2024/11/25 11:35:08 [TRACE] yaml drift detected in /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/test2-app for spec.source.helm.ignoreMissingValueFiles, was false now blank: timestamp=2024-11-25T11:35:08.548-0500
```

this is problematic for a number of reasons.

1. we have create complex configurations to leave things unset if they match the default
2. it becomes less clear what the actual settings are if you can't see them explicitly when viewing the application definition
3. its dangerous in the event that the defaults ever change
4. it is not very declarative to go back and adjust what the end user is defining.

**To Reproduce**

Install this. once it succeeds (it must complete), `kubectl get application test -n kube-system -o yaml | yq .spec` and view that the fields for `ignoreMissingValueFiles` and ` selfHeal` have disappeared.

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: bitnami
stringData:
  name: bitnami
  type: helm
  url: https://github.com/bitnami/charts/
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: kube-system
spec:
  destination:
    name: <cluster name>
    namespace: kube-system
  project: default
  revisionHistoryLimit: 5
  source:
    helm:
      ignoreMissingValueFiles: false
      releaseName: nginx
      version: v3
      parameters:
        - name: image.repository
          value: nginx
        - name: image.tag
          value: alpine
    path: bitnami/nginx
    repoURL: https://github.com/bitnami/charts/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
```

**Expected behavior**

All declared settings should be present in the cluster application definition

**Version**

```shell
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```
