### ISSUE TITLE
Intermittent Issue with Refresh Not Detecting Deleted Files in Repository

### ISSUE THREAD

**Issue by ermakov-oleg** [argoproj/argo-cd#21043]
## Describe the bug  
Sometimes, the refresh process in ArgoCD does not detect changes made in the repository, particularly when files are deleted. This leads to resources not being removed from the cluster. A hard refresh is required to resolve the issue.  

---

## To Reproduce  
Reproducing the issue consistently is not possible as it works correctly in test cases.  
- **Cluster size:** ~2,500 applications.  
- **Frequency:** 5–7 cases per day.  
- **Commits:** Approximately 500 commits per day.  

### Example Application Spec:  
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: some-name
  namespace: argocd
spec:
  destination:
    name: app-1
    namespace: microservices
  project: microservices
  source:
    directory:
      include: '*'
    path: microservices/some-name/app-1-specs/
    repoURL: <repo-url>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
```
Example Repository Files:

microservices/some-name/app-1-specs/install.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: some-name
  namespace: microservices
```
microservices/some-name/app-1-specs/install-v1.yaml
```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: some-name-v1
  namespace: microservices
```
microservices/some-name/app-1-specs/install-v2.yaml
```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: some-name-v2
  namespace: microservices
```

**CI Process**:
	1.	New files (e.g., install-v1.yaml, install-v2.yaml, install-v3.yaml) are created, and outdated versions are deleted.
	2.	Changes are committed to the repository.
	3.	A webhook is triggered to notify ArgoCD.

**Observed Behavior**:

After a file is deleted, ArgoCD sometimes fails to detect the change and does not remove the corresponding resources from the cluster.
	•	Frequency: 5–7 cases per day.
	•	Daily Commits: ~500 commits.

**Expected Behavior**

When a file is deleted from the repository, ArgoCD should detect the change and remove the corresponding resources from the cluster without requiring a hard refresh.

**Environment Info**
```bash
❯ argocd version
argocd: v2.13.1+af54ef8
  BuildDate: 2024-11-20T18:32:21Z
  GitCommit: af54ef8db5adfa77a08d4d05b1318a2198084c22
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```
