### ISSUE TITLE
Parameters of the ArgoCD Application are momentarily unset during Sync.

### ISSUE THREAD

**Issue by younghoon-klleon** [argoproj/argo-cd#21074]
Checklist:

* [O] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [O] I've included steps to reproduce the bug.
* [O] I've pasted the output of `argocd version`.

**Describe the bug**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-server
spec:
  project: example
  source:
    repoURL: 'git@github.com:test/test_k8s_deploy.git'
    targetRevision: main
    path: 'example-server/example-server'
    helm:
      valueFiles:
      - values.yaml
      - deploy-vendor/eks-values.yaml
      parameters:
      - name: scaledObject.cron.enabled
        value: 'true'
  destination:
    server: "https://kubernetes.default.svc"
    namespace:  example
  revisionHistoryLimit: 5
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true

```

I am deploying a service with a file like the one above. When the ArgoCD Application is synced, there is a momentary issue where the parameters are not recognized. Why does this happen? Is there a workaround? Also, it seems like ArgoCD detects new commits in the repository even if there are no changes to the source path of the Application. When it detects this, the same issue of momentarily not recognizing the parameters occurs. Why does this happen?

**To Reproduce**
With AutoSync enabled, make a new commit to the GitHub repo referenced by the Application.

**Expected behavior**
The parameter values must be preserved.

**Screenshots**

**Version**
{
    "Version": "v2.11.5+c4b283c",
    "BuildDate": "2024-07-15T17:39:54Z",
    "GitCommit": "c4b283ce0c092aeda00c78ae7b3b2d3b28e7feec",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.4+g81c902a",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}

**Logs**

```
Paste any relevant application logs here.
```
