### ISSUE TITLE
JWT invalid => Password for superuser has changed since token issued 

### ISSUE THREAD

**Issue by HugoRh** [argoproj/argo-cd#2108]
Hi,

I'm trying to use argocd CLI with JWT as an authentication method
So, I login in the GUI using dex, then I go to my project, then role , from here I generate a JWT with no expiry date.
Yet, after a while, I have below error:
```
# /usr/local/bin/argocd --insecure --grpc-web app list
FATA[0000] rpc error: code = Unauthenticated desc = invalid session: Password for superuser has changed since token issued 
```

I didn't update the admin ( superuser) password ( still same password...)

```
# argocd version
argocd: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:45:54Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:47:02Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

I manage argocd from argocd but autoupdate is off.

I don't get what is this issue... could it be because this JWT is signed & issued by the IDP ( as I log on with dex)???

Thanks for any hints !!

**Comment by alexec** [comment]
@jessesuen ?

**Comment by jessesuen** [comment]
"Password for superuser has changed since token issued" indicates it is using admin user and not SSO. I think `argocd login --sso` needs to be run.

**Comment by HugoRh** [comment]
Hi,

Another parameter I failed to mention , I'm using argocd CLI from a remote server ( which not connected to the AD and can't really be used for sso)
So when I run your suggested command it doesn't work

```
# argocd login some-server.dom --sso
Opening browser for authentication
Performing authorization_code flow login: https://some-server.dom/api/dex/auth?access_type=offline&client_id=argo-cd-cli&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=jvEgzXaSUV
FATA[0004] exit status 3                  
```

The JWT has been issued with my user ( I use dex to authenticate) which is part of the admin group, yet I do not use the local admin at all.

I'm using JWT to execute script around argocd so I can avoid storing passwords.

Maybe I missed something and I don't use the correct way to obtain or create an everlasting token allowing me to do my thing, in which case, could you please indicate what would be the recommended way ( frustating part is that it's working just fine for some time before failing :) )?

Thanks !!

**Comment by HugoRh** [comment]
Hi,

Any suggestion?

Thanks!

**Comment by alexec** [comment]
@jessesuen did you have any more thoughts on this? @HugoRh have you examined the JWT using https://jwt.io for expiry?

**Comment by HugoRh** [comment]
@alexec  JWT.io shows that generated token has no exp defined :
```
{
  "iat": 1564378977,
  "iss": "argocd",
  "nbf": 1564378977,
  "sub": "proj:caas-admin:admin"
}
```

**Comment by HugoRh** [comment]
In the mean time, I resorted to use a cheap trick which solve my issue :
```
kubectl -n argocd patch secret argocd-secret  -p='{"data":{"admin.passwordMtime": "MjAxNi0wMS0wMVQxMDowMDowMFo="}}' -v=1
```
So it shows that indeed my ldap user is considered as the built-in admin user although my user is only part of the admin group:
```
kubectl -n argocd get cm argocd-rbac-cm -oyaml
apiVersion: v1
data:
  policy.csv: |
    g, MY-GROUP, role:admin
  policy.default: none
kind: ConfigMap
```
Is there a way to suspend the key rotation mechanism?

Thanks !

**Comment by HugoRh** [comment]
@jessesuen and @alexec , any thoughts?

Thanks !!

**Comment by alexmt** [comment]
Better later than never. Should be fixed by https://github.com/argoproj/argo-cd/pull/3215

**Comment by Gangaram-Dewasi** [comment]
Team, 
I'm using SAML for login for normal users, now i want to create a local user for login and api access but post addition of the user in the argocd-cm and also in the RBAC, the login is failing with the error msg saying 

           "FATA[0010] rpc error: code = Unauthenticated desc = Bad local superuser username"

My argocd-cm:
```
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  accounts.deployer: apiKey, login
  accounts.sam: apiKey
  dex.config: 
     x.x.x.x
  repositories: |
    - name: stable
      type: helm
      url: https://kubernetes-charts.storage.googleapis.com
  url: https://argocd.apps.myorg.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-2.0.1
  name: argocd-cm
  namespace: argocd
```

My RBAC:

```
apiVersion: v1
data:
  policy.csv: |
    g, admin, role:admin
    g, deployer, role:admin
    g, sam, role:readonly
    p, role:dev-admin, projects, get, *, allow
    p, role:dev-admin, applications, get, *, allow
    g, org-admins@myorg.com, role:admin
    g, dev-admins@myorg.com, role:dev-admin
  policy.default: ""
  scopes: '[email, groups, accounts]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-2.0.1
  name: argocd-rbac-cm
  namespace: argocd
```

Would request if someone can help me on the above issue.
