### ISSUE TITLE
ArgoCD behind an auth proxy

### ISSUE THREAD

**Issue by hyec** [argoproj/argo-cd#21089]
### Discussed in https://github.com/argoproj/argo-cd/discussions/10321

<div type='discussions-op-text'>

<sup>Originally posted by **bennesp** August 13, 2022</sup>
I was wondering if ArgoCD supports a setup where it is put behind an auth proxy, maybe similar to what [Grafana allows to do](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/).

In this setup, ArgoCD should not ask the user for credentials, while instead it should look somewhere else (e.g.: an HTTP header) to get the username and, optionally, the role.

I tried to search this, but I only found ways of integrating existing SSO in ArgoCD. Unfortunately, that would mean having two different setups for the same purpose: the existing one with a centralized auth proxy and all the apps behind it, and the other one with ArgoCD exposed without the auth proxy, but configured to use the same configuration the auth proxy is using. Of course, I would like to avoid the latter.

Do you think this is possible?</div>

I found dex support the [authproxy connector](https://dexidp.io/docs/connectors/authproxy/), but this config doesn't work.
I have no idea what's wrong and how to debug it.

```
dex.config: |
  connectors:
    - type: authproxy
      id: oauth2-proxy
      name: OAuth2-Proxy
      config:
        userHeader: X-Forwarded-User
        groupHeader: X-Forwarded-Group
        staticGroups:
          - default
```
