### ISSUE TITLE
Bad Gateway at the end of OIDC flow with Microsoft Entra and no Dex

### ISSUE THREAD

**Issue by calogajac** [argoproj/argo-cd#21139]
### Discussed in https://github.com/argoproj/argo-cd/discussions/21025

<div type='discussions-op-text'>

<sup>Originally posted by **NiklasRosenstein** December  2, 2024</sup>
I'm trying to enable Microsoft Entra as SSO for our ArgoCD instance installed from the Helm chart (`v7.7.6`) using OIDC (not SAML). I've followed the guide here: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/#entra-id-app-registration-auth-using-oidc

The relevant Helm values I use are:

```yaml
    dex:
      enabled: false
    configs:
      cm:
        url: https://{{ .Values.ingress.host }}/
        oidc.config: |
          name: AzureAD
          issuer: '{{ required ".oidc.issuer missing" .Values.oidc.issuer }}'
          clientID: '{{ required ".oidc.clientID missing" .Values.oidc.clientID }}'
          clientSecret: $oidc.azure.clientSecret
          requestedIDTokenClaims:
            groups:
              essential: true
              value: "SecurityGroup"
          requestedScopes:
          - openid
          - profile
          - email
      secret:
        extra:
          oidc.azure.clientSecret: '{{ required ".oidc.clientSecret missing" .Values.oidc.clientSecret }}'
```

When I log in via SSO in ArgoCD, I get directed through Entra and back to ArgoCD, but then the Ingress returns a 502 😕 We're using ingress-nginx

![image](https://github.com/user-attachments/assets/fddff44c-7193-4dc0-84e6-5893eb6c89f4)

![image](https://github.com/user-attachments/assets/99d79903-2b47-4ece-bf33-d50befd905cd)

From the `argocd-server` logs, it seems the login succeeds:

![image](https://github.com/user-attachments/assets/16e792b1-0c22-4dbb-8168-b785314c3ea8)

The ingress-nginx logs are not much more helpful:

![image](https://github.com/user-attachments/assets/666d096e-9ef9-421d-93b7-917e8339b6a0)

Any idea what's going on? Thank you!

Edit: I get the same behavior on ArgoCD 2.12.4 (Helm Chart 7.6.10).</div>
