### ISSUE TITLE
ignoreDifferences feature does not work as expected

### ISSUE THREAD

**Issue by jascsch** [argoproj/argo-cd#21152]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

I would like to exclude a CRDs from the argocd app which belongs to the group gateway.networking.k8s.io

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: '*'
    helm:
      releaseName: traefik
      valueFiles:
        - $valuesRepo/tools/traefik/values.yaml
  - ref: valuesRepo
    repoURL: https://github.com/orga/argo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: CustomResourceDefinition
      group: gateway.networking.k8s.io
```

**Expected behavior**

the gateway CRDs should not be synced anymore.

**Screenshots**

N/A

**Version**

v2.13.2+dc43124

**Logs**

N/A
