### ISSUE TITLE
Application referencing project xyz which does not exist

### ISSUE THREAD

**Issue by cmoulliard** [argoproj/argo-cd#21150]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When an Application is installed on a cluster within a user's namespace and where its AppProject is also installed within a user's namespace, then we got as error within the Application resource status:
```
Application referencing project xyz which does not exist
```
even if the AppProject is well created under the user's namespace.

This issue has been discussed here: https://github.com/argoproj/argo-cd/discussions/8402#discussioncomment-11533578

**To Reproduce**

- Create a cluster (kind, etc)
- Install Argocd
- Create a user's namespace: `test`
- Update the Argocd config map - argocd-cmd-params-cm to include as parameter: `application.namespaces: test`
- Rollout argocd server and application controller
```
kubectl rollout restart -n argocd deployment argocd-server
kubectl rollout restart -n argocd statefulset argocd-application-controller
```
- Deploy the following yaml definition
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: cmoullia
  name: test
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: test
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-app
  namespace: test
spec:
  destination:
    name: in-cluster
    namespace: test
  project: guestbook
  source:
    path: apps
    repoURL: https://github.com/ch007m/my-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=false
```

**Expected behavior**

The Argocd Applications: bootstrap-app and guestbook should be installed and status been: sync and health

**Screenshots**

![Screenshot 2024-12-12 at 09 18 35](https://github.com/user-attachments/assets/588ca44f-e0bb-4f67-bb84-c107e0e7bd90)
![Screenshot 2024-12-12 at 09 18 44](https://github.com/user-attachments/assets/0e9f00ea-1dab-41fb-aacc-476e05d51fe6)
![Screenshot 2024-12-12 at 09 21 26](https://github.com/user-attachments/assets/c7293180-9bbd-4d48-8645-149e23ced3ce)
![Screenshot 2024-12-12 at 09 21 17](https://github.com/user-attachments/assets/e5875ad7-f9a8-48e5-a2b2-c6a3a0ea4752)

**Version**

```shell
v2.10.7
```

**Logs**

```
Status:
  Conditions:
    Last Transition Time:  2024-12-12T08:18:11Z
    Message:               Application referencing project guestbook which does not exist
    Type:                  InvalidSpecError
  Health:
    Status:  Unknown
  Sync:
    Status:  Unknown
Events:
  Type    Reason           Age   From                           Message
  ----    ------           ----  ----                           -------
  Normal  ResourceUpdated  25s   argocd-application-controller  Updated sync status:  -> Unknown
  Normal  ResourceUpdated  25s   argocd-application-controller  Updated health status:  -> Unknown
```

**Remark**

There is a workaround which is to create 2 AppProjects: one under argocd namespace and the other under the user's namespace. 

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: test
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
```

**Comment by cmoulliard** [comment]
Another workaround is to create the `AppProject` under the namespace of the argocd control plane `argocd, openshift-gitops` but where we restrict the sourceNamespace to `test` namespace. 

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - 'test'
 ```

**Remark**: The issue that we have we this approach is that many users will not been able to create/delete an `AppProject` under the namespace of the control plane due to RBAC permission !!

**Comment by NoOverflow** [comment]
Hi, can confirm this issue also occurs on ArgoCD version `v2.13.1+af54ef8` installed through the Red Hat `openshift-gitops` operator. 

I'm running a setup with two ArgoCD instances for separation of concerns between infrastructure and applicative teams, each running in their own namespace (`openshift-gitops`, `openshift-gitops-applicative`). 

The second instance (applicative) is configured for multitenancy with Application(+Set) in any namespace. Creating an AppProject in the `openshift-gitops-applicative` namespace in a declarative way works fine and I can see it show up in the UI.

However, when an Application is scoped to this AppProject, it fails while syncing:
```
Application referencing project app-test-sea-appproj which does not exist
```

Creating the same AppProj in the "default" ArgoCD namespace (in my case `openshift-gitops`) fixes the issue and syncing goes through.

It's as-if one of the ArgoCD API request does not take in account the control-plane namespace for its current ArgoCD instance when querying AppProjects, and instead defaults to the default one (`argocd` or `openshift-gitops`).

Reading the code I deduced this call stack:
```
[Controller]
AppController.go::newApplicationInformerAndLister ? https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/controller/appcontroller.go#L2232
  AppController.go::getAppProj (errors out)         https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/controller/appcontroller.go#L381
    AppController.go::projCache::GetAppProject      https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/controller/appcontroller.go#L366
      Argo.go::GetAppProjectByName                  https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/util/argo/argo.go#L661
        Lister::AppProject.go::Get (errors out)     https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/pkg/client/listers/application/v1alpha1/appproject.go#L75
  projectErrorToCondition                           https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/controller/appcontroller.go#L2349
```

I believe the issue comes from an incorrect namespace given to the AppProjectLister::Get method:
https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/pkg/client/listers/application/v1alpha1/appproject.go#L74-L77

But I don't see how this could be the case since the `ns` variable should be equals to `Server.ns` which seems to be the control-plane namespace, so `openshift-gitops-applicative` in my case:
https://github.com/argoproj/argo-cd/blob/af54ef8db5adfa77a08d4d05b1318a2198084c22/server/application/application.go#L1045

I will create a debug environment when I get the time and figure out what is going on.

@cmoulliard Can you tell me where in the documentation is mentioned the fact that you can create AppProjects objects outside of the ArgoCD namespace ? Because reading the code I don't see how this could work ...

**Comment by NoOverflow** [comment]
Well this is embarrassing, I found out why my setup wasn't working. Both ArgoCD instances had the same applicative namespace configured for the Application-in-any-namespace feature and were fighting for control over it. 

Removing the namespace from the `openshift-gitops` instance fixed the issue... Ignore my previous comment 😄

**Comment by cmoulliard** [comment]
> Can you tell me where in the documentation is mentioned the fact that you can create AppProjects objects outside of the ArgoCD namespace ?

The existing documentation don't mention at all that we should use an `AppProject` [created](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#overview) under the Argocd control plane namespace (= gitops, openshift-gitops nalmespaces)

**Comment by cmoulliard** [comment]
> What's your use-case for self-service AppProjects (i-e, outside of argocd control plane namespace) ?

My use is pretty simple. We would like to offer the possibility that users creates their applications within their own namespaces and that argocd reconcile them (= synced) without the need to touch a `AppProject` of the argocd control plane as users don't have access to such a namespace

**Comment by NoOverflow** [comment]
> The existing documentation don't mention at all that we should use an AppProject [created](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#overview) under the Argocd control plane namespace (= gitops, openshift-gitops nalmespaces)

True, I guess it is self-implied because if you allow users to create AppProjects, they effectively become ArgoCD administrators which doesn't make sense for most use-cases.

> My use is pretty simple. We would like to offer the possibility that users creates their applications within their own namespaces and that argocd reconcile them (= synced) without the need to touch a AppProject of the argocd control plane as users don't have access to such a namespace

What you could do is use a Kyverno generate policy, that, on AppProject creation:
- Validate that the AppProject is restrained to the user's namespace(s) by checking /spec/destinations
- If valid, "mirror" this AppProject in ArgoCD's control-plane namespace 

(See: https://kyverno.io/docs/writing-policies/generate/)

This obviously comes with some issues and edge cases but you seem to have a really specific use-case and that would be my approach with it. 

But ideally you would have a process that automates the creation of an AppProject when creating the project for a user

**Comment by cmoulliard** [comment]
> But ideally you would have a process that automates the creation of an AppProject when creating the project for a user

We have a project able to generate such an `AppProject` - https://github.com/quarkiverse/quarkus-argocd/blob/main/deployment/src/main/java/io/quarkiverse/argocd/deployment/ArgoCDProcessor.java#L80 so that should not be an issue for us until to create by default the AppProject under the namespace of Argocd control plane (if of course we have the RBAC rights) ;-)

**Comment by cmoulliard** [comment]
> True, I guess it is self-implied because if you allow users to create AppProjects, they effectively become ArgoCD administrators which doesn't make sense for most use-cases.

Documentation should be improved to clearly warn the user that the `AppProject` should always been created or updated under the Argocd control plane namespace

**Comment by NoOverflow** [comment]
> Documentation should be improved to clearly warn the user that the AppProject should always been created or updated under the Argocd control plane namespace

Agreed 😄

**Comment by agaudreault** [comment]
> However this confirms that AppProjects can only be located in the control-plane namespace, as the ApplicationController instance looks for them in the same namespace where he is running in itself. This makes sense since AppProjects are not meant for self-service and are restricted to ArgoCD administrators.

That is correct. All resources should be created in the argo control-plane namespace, unless specified otherwise. AppProject is the Security and tenancy control, allowing users to create them without validation would not make sense.

**Comment by agaudreault** [comment]
@cmoulliard Please open a PR on what you think the wording in the documentation should be to avoid confusion, or close the issue.

**Comment by mboutet** [comment]
Hello, we are experiencing this issue with `v2.10.0+2175939`. Everything (Application, AppProject) are created in the argocd namespace. We use the following app of apps (more like app of apps of apps 😛) pattern:

```
Application
+- Application for app projects
   +- AppProject-app1
   +- AppProject-app2
   +- ...
+- Application for the "applications"
   +- Application-app1
   +- Application-app2
   +- ...
```

When adding a new application, the `AppProject-app1` and `Application-app1` are added to git in the same commit. However, we've observed that the AppProject is systematically not being created first despite using sync waves on `Application for app projects` (`-1000`) and `Application for the "applications"` (`-900`). The only way to unblock it is to trigger a refresh of `Application for app projects` and then the `Application for the "applications"`. On top of this, we're also using git webhooks to avoid polling too often our github enterprise instance, so it results in the Application getting stuck forever unless manual intervention is taken.

**Comment by saptadip** [comment]
Today I upgraded our `argocd` server(running in HA mode) from `2.14.11` to `3.0.5`. After that I started receiving the error: `Application referencing project default which does not exist`. On investigation I found that ONE out of THREE `application-controller` pods was frequently terminated due to OOM error. After increasing the resource limits the error was gone.

**Comment by Blarc** [comment]
AI suggested the following and it worked for me:

The error `InvalidSpecError: Application referencing project argo-cd which does not exist` occurs because Argo CD is trying to create the `Application` before the `AppProject` has been fully processed and "seen" by the Argo CD controller.

Even though they are in the same file, Argo CD often processes resources in a way that can lead to race conditions if the `AppProject` isn't ready when the is validated. `Application`

To fix this, you should add a **Sync Wave** annotation to ensure the Project is created first.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Ensure project is created first
spec:
# ... existing code ...
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: argo-cd
# ... existing code ...
```
