### ISSUE TITLE
Notifications subscription selector matchExpressions

### ISSUE THREAD

**Issue by JerkyTreats** [argoproj/argo-cd#21162]
# Summary

Currently the notification selector is limited to a string type. It would be more useful if it could use matchExpressions: 
```
  notifications:
    subscriptions:
      - recipients:
        - foohook
        triggers:
        - foohook-trigger
        selector:
          matchExpressions:
            - key: exclude-foohook-trigger
              operator: NotIn
              values:
                - "true"
```

# Motivation

Given several applications/appsets, it would be easier to exclude the apps I don't want vs. selecting for the apps I do want. My expectation was to do a matchExpression. 

`selector` is only a string though. This might work `selector: exclude-foohook-trigger!=true`? 

# Proposal

Convert selector from string type to.... something that can consume matchExpression?
