### ISSUE TITLE
Warning: Conflict when getting shard from shard mapping configMap

### ISSUE THREAD

**Issue by fmunteanu** [argoproj/argo-cd#21181]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm deploying ArgoCD with the Helm chart, running on 2 application controllers with `dynamicClusterDistribution` enabled and `controller.sharding.algorithm` set to `round-robin`. I always see the following warnings (see logs below):

- `conflict when getting shard from shard mapping configMap. Retrying`
- `The cluster https://kubernetes.default.svc has no assigned shard`

I'm not sure what the root cause of these warnings, I was wondering if anyone can provide some guidance if this is considered a bug or a configuration issue.

**CM Details**

```
$ kubectl get cm argocd-app-controller-shard-cm -n kube-system -o json | jq .data
{
  "shardControllerMapping": "[{\"ShardNumber\":0,\"ControllerName\":\"argo-cd-argocd-application-controller-6c5b5d5d66-dh2pt\",\"HeartbeatTime\":\"2024-12-15T01:13:04Z\"},{\"ShardNumber\":1,\"ControllerName\":\"argo-cd-argocd-application-controller-6c5b5d5d66-g4dzj\",\"HeartbeatTime\":\"2024-12-15T01:13:03Z\"}]"

$ kubectl get cm argocd-cmd-params-cm -n kube-system -o json | jq .data
{
  "application.namespaces": "kube-system",
  "applicationsetcontroller.enable.leader.election": "true",
  "applicationsetcontroller.enable.new.git.file.globbing": "true",
  "applicationsetcontroller.enable.progressive.syncs": "true",
  "applicationsetcontroller.log.format": "text",
  "applicationsetcontroller.log.level": "warn",
  "applicationsetcontroller.namespaces": "",
  "applicationsetcontroller.policy": "sync",
  "controller.ignore.normalizer.jq.timeout": "1s",
  "controller.log.format": "text",
  "controller.log.level": "warn",
  "controller.operation.processors": "10",
  "controller.repo.server.timeout.seconds": "60",
  "controller.self.heal.timeout.seconds": "5",
  "controller.sharding.algorithm": "round-robin",
  "controller.status.processors": "20",
  "otlp.address": "",
  "redis.server": "argo-cd-argocd-redis:6379",
  "repo.server": "argo-cd-argocd-repo-server:8081",
  "reposerver.log.format": "text",
  "reposerver.log.level": "warn",
  "reposerver.parallelism.limit": "0",
  "server.basehref": "/",
  "server.dex.server": "https://argo-cd-argocd-dex-server:5556",
  "server.dex.server.strict.tls": "false",
  "server.disable.auth": "false",
  "server.enable.gzip": "true",
  "server.enable.proxy.extension": "false",
  "server.insecure": "true",
  "server.log.format": "text",
  "server.log.level": "warn",
  "server.repo.server.strict.tls": "false",
  "server.rootpath": "",
  "server.staticassets": "/shared/app",
  "server.x.frame.options": "sameorigin"
}

$ kubectl get cm argocd-cm -n kube-system -o json | jq .data
{
  "application.instanceLabelKey": "argocd.argoproj.io/instance",
  "exec.enabled": "true",
  "server.rbac.log.enforce.enable": "false",
  "statusbadge.enabled": "false",
  "timeout.hard.reconciliation": "0s",
  "timeout.reconciliation": "180s",
  "url": "https://argocd.noty.cc"
}
```

**Helm Chart Custom Values**

```yaml
applicationSet:
  pdb:
    enabled: true
    minAvailable: 1
  replicas: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
configs:
  cm:
    exec.enabled: true
    statusbadge.enabled: false
  params:
    application.namespaces: kube-system
    applicationsetcontroller.enable.leader.election: true
    applicationsetcontroller.enable.new.git.file.globbing: true
    applicationsetcontroller.enable.progressive.syncs: true
    controller.sharding.algorithm: round-robin
    server.insecure: true
  rbac:
    policy.default: role:readonly
  secret:
    argocdServerAdminPassword: redacted
controller:
  dynamicClusterDistribution: true
  pdb:
    enabled: true
    minAvailable: 1
  replicas: 2
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
dex:
  pdb:
    enabled: true
    minAvailable: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
global:
  domain: argocd.noty.cc
  logging:
    level: warn
notifications:
  pdb:
    enabled: true
    minAvailable: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
redis:
  pdb:
    enabled: true
    minAvailable: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
repoServer:
  autoscaling:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetMemoryUtilizationPercentage: 80
  pdb:
    enabled: true
    minAvailable: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
server:
  autoscaling:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetMemoryUtilizationPercentage: 80
  pdb:
    enabled: true
    minAvailable: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
```

**Version**

```shell
argocd: v2.13.2+dc43124
  BuildDate: 2024-12-11T19:01:33Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.22.9
  Compiler: gc
  Platform: linux/arm64
```

**Logs**

```
time="2024-12-15T00:49:55Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (0/3)"
time="2024-12-15T00:49:55Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (1/3)"
time="2024-12-15T00:49:56Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (2/3)"
time="2024-12-15T00:49:56Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (3/3)"
time="2024-12-15T00:49:58Z" level=warning msg="The cluster https://kubernetes.default.svc has no assigned shard."
```

**Comment by andrii-korotkov-verkada** [comment]
How is argocd-app-controller-shard-cm updated? Is it a dynamic process?

**Comment by fmunteanu** [comment]
I'm deploying everything with the official Helm chart.

**Comment by andrii-korotkov-verkada** [comment]
I just see specific names like `argo-cd-argocd-application-controller-6c5b5d5d66-dh2pt`, so guess it's dynamically specified.
Can you share your application controller manifest, please?

**Comment by fmunteanu** [comment]
When I set:

```
controller:
  dynamicClusterDistribution: true
```

I see the two pod names changing from `argo-cd-argocd-application-controller-0/1` to the above listed format. For now I disabled the `dynamicClusterDistribution` option, it order to address the warnings.

**Comment by fmunteanu** [comment]
Happy holidays @andrii-korotkov-verkada. I enabled the `controller. dynamicClusterDistribution` option when I look at the logs I see these warnings:

```
time="2024-12-27T23:58:43Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (0/3)"
time="2024-12-27T23:58:43Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (1/3)"
time="2024-12-27T23:58:43Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (2/3)"
time="2024-12-27T23:58:43Z" level=warning msg="conflict when getting shard from shard mapping configMap. Retrying (3/3)"
time="2024-12-27T23:58:50Z" level=warning msg="The cluster https://kubernetes.default.svc has no assigned shard."
```

Please let me know what additional information I should provide.

**Comment by andrii-korotkov-verkada** [comment]
Try enabling debug level for logs instead of warn, that might help a lot.

**Comment by fmunteanu** [comment]
@andrii-korotkov-verkada I think the issue is related to this [condition](https://github.com/argoproj/argo-helm/blob/argo-cd-7.7.11/charts/argo-cd/templates/argocd-application-controller/role.yaml#L46):

```
{{- if and (not .Values.createClusterRoles) .Values.controller.dynamicClusterDistribution }}
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - argocd-app-controller-shard-cm
  verbs:
  - get
  - list
  - watch
  - create
  - update
{{- end }}
```

By default, the helm chart sets `createClusterRoles` to `true`. If I understand correctly, the condition is read as:

```
IF .Values.createClusterRole IS False AND .Values.controller.dynamicClusterDistribution IS True
```

**Comment by fmunteanu** [comment]
I agree, I believe the condition above evaluates always False.

**Comment by agray-ctm** [comment]
```
# FOR DYNAMIC CLUSTER SCALING (alpha)
# it's a big fragile, but we want the shard CM to reset whenever argo is updated
# This prevents weirdness where the shard CM becomes inaccessable because the pod GUIDs have changed
resource "terraform_data" "reset_argo_shards" {
  triggers_replace = [
    helm_release.argo.manifest
  ]

  provisioner "local-exec" {
    on_failure = continue

    command = <<-EOF
aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME;

# Kill the application controller
kubectl patch deployment -n argo argo-cd-argocd-application-controller -p "{\"spec\":{\"replicas\":0}}";
kubectl rollout restart deployment -n argo argo-cd-argocd-application-controller;
kubectl patch deployment -n argo argo-cd-argocd-application-controller -p "{\"spec\":{\"replicas\":0}}";
sleep 30;

# Grant 'create' for unscoped configmaps within the argo namespace
# The helm chart grants 'get, list, watch, create, update' for the shard configmap
# But scoping 'create' means it can't create the shard CM
# This is a bug in the helm chart
kubectl patch role -n argo argo-cd-argocd-application-controller --type='json' \
  -p='[{"op": "add", "path": "/rules/-", "value": {"apiGroups": [""], "resources": ["configmaps"], "verbs": ["create"]}}]';

# Delete the shard CM
kubectl delete configmap -n argo argocd-app-controller-shard-cm;
# Restart the application controller
kubectl patch deployment -n argo argo-cd-argocd-application-controller -p "{\"spec\":{\"replicas\":$REPLICAS}}";
    EOF

    environment = {
      REGION       = var.AWS_REGION
      CLUSTER_NAME = var.EKS_CLUSTER_NAME
      REPLICAS     = local.replicas
    }
  }

  # Forces waiting for cluster to be available
  depends_on = [
    helm_release.argo
  ]
}
```

This is what it took for me to get it somewhat stable. Note that in my patch I'm adding:
```
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
```
To the role. For some reason the shard CM is not tolerant to reboots.
