### ISSUE TITLE
Application multiple sources (helm, git) with directory recurse does not work. v2.13.2+dc43124

### ISSUE THREAD

**Issue by HakimHC** [argoproj/argo-cd#21228]
**Describe the bug**

Hello, I've encountered an issue with creating an Application with multiple sources: a source for a public Helm chart (grafana) and a source for my private GitHub repository, containing a values files for the helm chart and various other related manifests (Ingress etc). For this reason, I must specify directory.recurse = true.
When deploying without directory.recurse, the values file gets detected correctly, and the chart gets deployed. However, when directory.recurse is specified, I get the following error:
```shell
Failed to load target state: failed to generate manifest for source 2 of 2: rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal "values.yaml": <nil>
```

I could not find anything related to this behaviour in the documentation, thus I open this issue.

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: grafana
      targetRevision: 8.8.2
      helm:
        valueFiles:
          - $values/kubernetes/grafana/values/values.yaml
    - repoURL: 'git@github.com:xxx/yyy.git'
      targetRevision: HEAD
      path: kubernetes/grafana
      ref: values
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: grafana
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

**Expected behavior**

The expected behaviour is to detect the values file and all of the manifests declared in the specified 'path' directory (kubernetes/grafana in this case) with all of its subdirectories.

**Screenshots**

**Version**

```shell
argocd-server: v2.13.2+dc43124
```
<img width="360" alt="image" src="https://github.com/user-attachments/assets/090f0bd4-8cfd-47f2-ad93-d59c43454456" />

**Logs**
![image](https://github.com/user-attachments/assets/ca5de7e9-ed09-4941-99e2-9d710ea70929)
