### ISSUE TITLE
Bug: Clusters Generator isn't accessing metadata values from cluster secret

### ISSUE THREAD

**Issue by magic-madrigal** [argoproj/argo-cd#21293]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Currently trying to create an ApplicationSet with nested Matrix Generators, but the final Cluster generator can't access the `metadata.labels` from the Cluster Secret. The system continues to complain that 

Argocd Server Details:
```
{
    "Version": "v2.13.2+dc43124",
    "BuildDate": "2024-12-11T18:37:15Z",
    "GitCommit": "dc43124058130db9a747d141d86d7c2f4aac7bf9",
    "GitTreeState": "clean",
    "GoVersion": "go1.23.1",
    "Compiler": "gc",
    "Platform": "linux/arm64",
    "KustomizeVersion": "v5.4.3 2024-07-19T16:40:33Z",
    "HelmVersion": "v3.15.4+gfa9efb0",
    "KubectlVersion": "v0.31.0",
    "JsonnetVersion": "v0.20.0"
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by andrii-korotkov-verkada** [comment]
From what I've heard, matrix of matrix isn't fully supported. Are there other ways to restructure this to avoid having nested matrix? Is there something that can be added to ArgoCD to allow for that to happen?

**Comment by magic-madrigal** [comment]
@andrii-korotkov-verkada - I ended up hardcoding the values, which is unfortunate, but I couldn't find a better way to do this.

**Comment by jkleinlercher** [comment]
I have the same issue. And in my case I do not have a matrix of matrix generators, but just a matrix of list and clusters. 

```
  generators:
  - matrix:
      generators:
        - list:
            elements:
            - stage: test
              targetClusterStage: testing
            - stage: qa
              targetClusterStage: testing
            - stage: prod
              targetClusterStage: testing
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                spoke.kubrix.io/stage: '{{.targetClusterStage}}'
            values:
              ingressDomain: '{{index .metadata.annotations "spoke.kubrix.io/ingress-domain"}}'
```

error message:

```
    message: 'failed to get params for second generator in the matrix generator: child
      generator returned an error on parameter generation: failed to replace parameters
      in generator: failed to execute go template {{index .metadata.annotations "spoke.kubrix.io/ingress-domain"}}:
      template: :1:17: executing "" at <.metadata.annotations>: map has no entry for
      key "metadata"'
    reason: ApplicationGenerationFromParamsError
    status: "True"
    type: ErrorOccurred
```

cluster secret:

```
apiVersion: v1
data:
  config: <redacted>
  name: <redacted>
  server: <redacted>
kind: Secret
metadata:
  annotations:
    spoke.kubrix.io/ingress-domain: cluster000.xxx.cloud.xxx.at
    spoke.kubrix.io/stage: testing
  creationTimestamp: "2024-12-17T20:52:43Z"
  labels:
    argocd.argoproj.io/secret-type: cluster
    spoke.kubrix.io/stage: testing
  name: xxxx
  namespace: argocd
type: Opaque
```


Getting the annotation works fine when I just use a clusters generator without a matrix

**Comment by jkleinlercher** [comment]
what worked in my environment is this, however, I do not know why this works instead of https://github.com/argoproj/argo-cd/issues/21293#issuecomment-2603951046 .

Also, as I read in other issues, nested matrixes are not really supported.


```
  generators:
  - matrix:
      generators:
        - matrix:
            generators:
              - list:
                  elements:
                  - stage: test
                    targetClusterStage: testing
                  - stage: qa
                    targetClusterStage: testing
                  - stage: prod
                    targetClusterStage: testing
              - clusters:
                  selector:
                    matchLabels:
                      argocd.argoproj.io/secret-type: cluster
                      spoke.kubrix.io/stage: '{{.targetClusterStage}}'
        -  list:
              elements:
                - ingressDomain: '{{index .metadata.annotations "spoke.kubrix.io/ingress-domain"}}'
```

**Comment by jkleinlercher** [comment]
thanks to https://github.com/argoproj/argo-cd/issues/16830#issuecomment-1997578627 I tried to escape the values and now it works like this:

```
  generators:
  - matrix:
      generators:
        - list:
            elements:
            - stage: test
              targetClusterStage: testingbla
            - stage: qa
              targetClusterStage: testing
            - stage: prod
              targetClusterStage: testing
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                spoke.kubrix.io/stage: '{{.targetClusterStage}}'
            values:
              ingressDomain: |-
                {{"{{ index .metadata.annotations \"spoke.kubrix.io/ingress-domain\" }}"}}
```

@magic-madrigal maybe this approach also helps you
