### ISSUE TITLE
ignoreDifferences for CustomerResource does not have any effect

### ISSUE THREAD

**Issue by dirkvdplas** [argoproj/argo-cd#21308]
Checklist:

* [V ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [V] I've included steps to reproduce the bug.
* [V] I've pasted the output of `argocd version`.

IgnoreDifferences for CustomResource objects is not working.  What have I done:

1. tested if I understood IgnoreDifferences syntax. I tested with standard builtin objects like replicas and this was working as expected
2. tested  with multiple helmcharts which use custom resource object, and always encountered same issue. I will provide an example based on a small project external-dns, which will make it easy to reproduce 

ArgoCD reports outofsync condition despite the fact that the changed objects are defined under IgnoreDifferences

**To Reproduce**
It is assumed that ArGoCD server v2.13.2  is installed 
1. Create App in ArgoCD, with following settings (also provided in file: argocd-app.yaml). This will create namespace external-dns  with external-dns application and the CRD dnsendpoints.externaldns.k8s.io

```
project: default
destination:
  server: https://kubernetes.default.svc
  namespace: external-dns
syncPolicy:
  syncOptions:
    - CreateNamespace=true
ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
sources:
  - repoURL: https://github.com/dirkvdplas/argocd-externaldns-ignoredifferences.git
    path: manifests
    targetRevision: main
  - repoURL: registry-1.docker.io/bitnamicharts
    path: external-dns
    targetRevision: 8.7.1
    chart: external-dns
```

 2. Introduce a change in the external-dns custom resource. Change
    recordTTL to another value
 `kubectl -n external-dns edit DNSEndpoint ns-record`
 3. ArgoCD will now report outofSync, appearantly the "ignoreDifferences" did not have any effect

**Expected behavior**
I expect that ArgoCD does not report outofsync for objects which are defined under IgnoreDifferences

I expected Sync Status to be "Synced" because ArgoCD should have ignored any changes on the DNSendpoint
**Screenshots**

A screenshot has been added which shows the detected diff: 
![dnsendpoint-diff](https://github.com/user-attachments/assets/61f2fe86-b6fb-4411-91d4-0d5bcd221fe2)

**Version**

```shell
argocd: v2.13.1+af54ef8
  BuildDate: 2024-11-20T16:54:29Z
  GitCommit: af54ef8db5adfa77a08d4d05b1318a2198084c22
  GitTreeState: clean
  GoVersion: go1.22.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.2+dc43124
  BuildDate: 2024-12-11T18:37:15Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**
Attached are the logs which appeared after changing the dnsendpoint
The following command was used to gather the logs:
kubectl -n argocd logs -f argocd-application-controller-0 -c argocd-application-controller

```
time="2024-12-24T14:19:47Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" app-namespace=argocd app-qualified-name=argocd/external-dns application=external-dns project=default
time="2024-12-24T14:19:47Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: external-dns)" application=argocd/external-dns
time="2024-12-24T14:19:47Z" level=info msg="GetRepoObjs stats" application=argocd/external-dns build_options_ms=0 manifests_ms=11 plugins_ms=0 repo_ms=0 time_ms=11
time="2024-12-24T14:19:47Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=external-dns dest-namespace=external-dns dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2024-12-24T14:19:47Z" level=info msg="Update successful" app-namespace=argocd app-qualified-name=argocd/external-dns application=external-dns project=default
time="2024-12-24T14:19:47Z" level=info msg="Reconciliation completed" app-namespace=argocd app-qualified-name=argocd/external-dns app_status_update_ms=0 application=external-dns auto_sync_ms=0 compare_app_state_ms=14 comparison-level=1 comparison_with_nothing_ms=0 dedup_ms=0 dest-name= dest-namespace=external-dns dest-server="https://kubernetes.default.svc" diff_ms=0 git_ms=11 health_ms=0 live_ms=0 normalize_application_ms=0 patch_ms=18 persist_app_status_ms=26 process_finalizers_ms=0 project=default refresh_app_conditions_ms=0 set_app_managed_resources_ms=8 setop_ms=0 settings_ms=0 sync_ms=0 time_ms=49
```

**Comment by andrii-korotkov-verkada** [comment]
For ignore differences you have to specify paths as well (keep in mind that just / doesn't work for some reason).
```
ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
```
is not sufficient.
Please, try with paths and let me know if the issue is still there.

**Comment by enneitex** [comment]
Hey,

Based on the screenshot, I think the ignoreDifferences should target the custom resource instead of the CRD 

something like:
```yaml
ignoreDifferences:
  - group: externaldns.k8s.io
    kind: DNSEndpoint
```

and a jsonPointers with the path to `recordTTL`

**Comment by dirkvdplas** [comment]
I was able to get the desired results by a combination of the above mentioned suggestions:

```
ignoreDifferences:
  - group: externaldns.k8s.io
    kind: DNSEndpoint
    jqPathExpressions:
      - .spec.endpoints[]?.recordTTL
```
     
Thanks. This issue can be closed
