### ISSUE TITLE
Show full app-of-apps/ApplicationSet tree in UI

### ISSUE THREAD

**Issue by Hobbit44** [argoproj/argo-cd#21325]
# Summary

I would like to see a full tree of my repo when looking at the top level app. I have a repo structure like the below:

```
services
├─ ci
│   └─ argocd.yaml
├─ data
│   ├─ postgres.yaml
│   └─ redis.yaml   
├─ monitoring
│   └─ prometheus.yaml
└─ system
     └─ metallb.yaml
```

I have each of the services in a namespace that corresponds with the namespace (e.g. redis and postgres are in data ns (i know its not best practice but its only a home cluster)). Each of the yaml files are argocd Apps as they are all helm charts and as i have pretty simple values setups I'm happy to store all the details in the applications files.

My ideal would be to see a layout like the below under the services app, as it clearly shows the resources in my tree. I can then look at the apps to see the resources created by the charts.

![Screenshot 2024-12-29 140037](https://github.com/user-attachments/assets/3641ef41-72b2-4bd0-9908-aa80cf854d02)

I have tried various different things to try and attain that kind of view:

<details><summary>ApplicationSet</summary>
<p>

<ul>
<details><summary>UI Tree</summary>
<p>

![image](https://github.com/user-attachments/assets/60a2e4f5-6c10-4dd7-87d1-b446f6a3d9af)
![image](https://github.com/user-attachments/assets/3b3c504e-2af6-4941-9695-5c1732a1ec65)

</p>
</details>
<details><summary>services.yaml</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: ci
spec:
  project: default
  source:
    repoURL: https://github.com/Hobbit44/services
    targetRevision: refs/heads/main
    path: '.'
    directory:
      include: 'appset.yaml'
  destination:
    name: home-k8s
    namespace: ci
  syncPolicy:
    automated: {}
```

</p>
</details>
<details><summary>appset.yaml</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: ci
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Hobbit44/services
      revision: refs/heads/main
      directories:
      - path: '*'
  template:
    metadata:
      name: '{{ .path.basenameNormalized }}'
      namespace: ci
    spec:
      project: default
      source:
        repoURL: https://github.com/Hobbit44/services
        targetRevision: refs/heads/main
        path: '{{ .path.path }}'
      destination:
        name: home-k8s
        namespace: '{{ .path.basenameNormalized }}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
```

</p>
</details>
</ul>

</p>
</details> 

<details><summary>App of Apps</summary>
<p>

<ul>
<details><summary>UI Tree</summary>
<p>

![image](https://github.com/user-attachments/assets/700c3750-3f1b-4c55-82cf-a54076a62a55)

</p>
</details>
<details><summary>services.yaml</summary>
<p>

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: ci
spec:
  project: default
  source:
    repoURL: https://github.com/Hobbit44/services
    targetRevision: refs/heads/main
    path: '.'
    directory:
      recurse: true
      include: '**/*.yaml'
  destination:
    name: home-k8s
    namespace: ci
  syncPolicy:
    automated: {}
```

</p>
</details>
</ul>

</p>
</details> 

<details><summary>Config Management Plugin</summary>
<p>

<ul>
<details><summary>UI Tree</summary>
<p>

![image](https://github.com/user-attachments/assets/04a5f923-09bb-4060-84fa-870ec69fa729)

</p>
</details> 
<details><summary>ArgoCD Helm Values</summary>
<p>

```yaml
configs:
  cm: 
    application.resourceTrackingMethod: annotation+label
  cmp:
    create: true
    plugins:
      ns-plugin:
        sync-hook: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: ns-plugin-sync
            annotations:
              argocd.argoproj.io/hook: PostSync
              argocd.argoproj.io/hook-delete-policy: HookSucceeded
          spec:
            template:
              spec:
                serviceAccountName: argocd-application-controller
                containers:
                - name: hook
                  image: bitnami/kubectl:latest
                  command: [bash, -c]
                  args:
                  - |-
                    while read -r name; do 
                      namespace=$(kubectl get apps -n ci $name -o yaml | yq '.spec.destination.namespace')
                      if [[ ! -e /tmp/${namespace}.yaml ]]; then
                        kubectl get ns $namespace -o yaml | yq '{"metadata": {"ownerReferences": [{"apiVersion": .apiVersion, "kind": .kind, "name": .metadata.name, "uid": .metadata.uid}]}}' > /tmp/${namespace}.yaml
                      fi
                      kubectl patch app -n ci $name --type=merge --patch-file=/tmp/${namespace}.yaml
                    done <<< $(kubectl get apps -n ci services -o yaml | yq '.status.resources[] | select(.kind == "Application").name')
                  volumeMounts:
                  - mountPath: /tmp
                    name: tmp
                volumes:
                - name: tmp
                  emptyDir: {}
                restartPolicy: Never
            backoffLimit: 2
        init:
          command: [bash, -c]
          args:
          - |-
            set -o pipefail
            mkdir .generated
            while read -r namespace; do 
              export namespace
              [[ "$namespace" == "null" ]] && continue
              [[ -z "$namespace" ]] && continue
              kubectl create ns --dry-run=client $namespace -o yaml > .generated/${namespace}.yaml
              yq -i '.metadata.labels["app.kubernetes.io/instance"] |= env(ARGOCD_APP_NAME)' .generated/${namespace}.yaml
              yq -i '.metadata.annotations["argocd.argoproj.io/tracking-id"] |= env(ARGOCD_APP_NAME)+":/Namespace:"+env(namespace)+"/"+env(namespace)' .generated/${namespace}.yaml
            done <<< $(find . -mindepth 2 -maxdepth 2 -type f -name "*.yaml" -exec yq '.spec.destination.namespace' {} ';' | sort | uniq)
            yq '.spec.sync-hook' /home/argocd/cmp-server/config/plugin.yaml > .generated/sync-hook.yaml
        generate:
          command: [bash, -c]
          args:
          - find . -mindepth 2 -maxdepth 2 -type f -name "*.yaml" | xargs yq eval-all
repoServer:
  plugin:
    tar:
      exclusions: ".git/*"
  extraContainers:
  - name: ns-plugin
    command: [/var/run/argocd/argocd-cmp-server]
    args: [--loglevel, debug]
    image: bitnami/kubectl
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: plugin.yaml
        name: argocd-cmp-cm
  volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
        items:
          - key: "ns-plugin.yaml"
            path: "plugin.yaml"
```

</p>
</details> 
<details><summary>services.yaml</summary>
<p>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: ci
spec:
  project: default
  source:
    repoURL: https://github.com/Hobbit44/services
    targetRevision: refs/heads/main
    path: '.'
    plugin:
      name: ns-plugin
  destination:
    name: home-k8s
    namespace: ci
  syncPolicy:
    automated: {}
```

</p>
</details> 
</ul>

</p>
</details> 

# Proposal

My thinking is that if an application only contains other applications, the tree could extend to show the child apps.

I think there a few related issues that are related that i think could contribute to this end.

https://github.com/argoproj/argo-cd/issues/11196 Would add visibility of the NSs to the UI but might not nessesarily add the dependency element.
https://github.com/argoproj/argo-cd/issues/7437 Could add the ability to set exlicit dependencies via a dependsOn key.
