### ISSUE TITLE
Matrix list generator with elementsYaml not working with git repos

### ISSUE THREAD

**Issue by tomlnd** [argoproj/argo-cd#21336]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD's applicationsets allows fetching deployable charts from a file in a gitops repository, as seen [in the docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-List/#dynamically-generated-elements). This feature works fine with helm charts (by using `template.spec.sources.chart`), but seems to fail when trying to deploy pure manifests from a git repository (by using `template.spec.sources.path`).

Here's a working **Application** CRD:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: 'https://github.com/kubernetes/ingress-nginx.git'
      path: "deploy/static/provider/cloud"
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

But when converting it to an ApplicationSet like below where the first source's values are being feeded from the yaml-file, while the second source allows me to supply additional custom manifests to the applications:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - git:
            repoURL: 'https://gitlab.com/xxx/example-repo.git'
            revision: master
            files:
              - path: 'appsets/configs/infrastructure-config.yaml'
        - list:
            elementsYaml: '{{ .app.charts | toJson }}'
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      sources:
        - repoURL: '{{.repoUrl}}'
          path: '{{.path}}' # see this
          chart: '{{.chart}}'
          targetRevision: '{{.version}}'
        - repoURL: 'https://gitlab.com/xxx/example-repo.git'
          targetRevision: master
          path: 'apps/infrastructure/{{.name}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
```

And using the following example `appsets/configs/infrastructure-config.yaml` file to deploy 2 applications:

```yaml
app:
  charts:
    - name: ingress-nginx
      path: "deploy/static/provider/cloud" # the path in the repoUrl repository
      chart: "" # empty since it's a git repo
      version: "main"
      repoUrl: "https://github.com/kubernetes/ingress-nginx.git"
      namespace: ingress-nginx
    - name: cert-manager
      chart: cert-manager
      path: ""
      version: "v1.16.1"
      repoUrl: "https://charts.jetstack.io"
      namespace: cert-manager
```

The cert-manager application will deploy successfully, but the ingress-nginx application will fail with the following error:

```
ComparisonError
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = map[basename:configs basenameNormalized:configs filename:infrastructure-config.yaml filenameNormalized:infrastructure-config.yaml path:appsets/configs segments:[appsets configs]]: app path does not exist
```

**Version**

```shell
argocd: v2.12.6+4dab5bd
```
