### ISSUE TITLE
403 Forbidden when editing application details after enabling Dex

### ISSUE THREAD

**Issue by bzurkowski** [argoproj/argo-cd#21421]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

My team is using [Argo CD with Dex](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-plus-google-groups-using-dex) to delegate user authentication to Google as the IDP.

Before enabling Dex, everything was working fine. However, after enabling Dex, we encountered a `403 Forbidden` error when attempting to edit application details, such as labels or sync policies, through the Argo CD dashboard. These actions are also disallowed even when I log in as an admin user.

Despite this issue, I am still able to perform other actions, such as deleting Pods, via the dashboard. Additionally, editing application details works without any issues when using kubectl.

The applied RBAC policy is as follows:

```yaml
cm:
  users.anonymous.enabled: "false"
rbac:
  policy.default: "role:authenticated"
  policy.csv: |
    p, role:authenticated, *, *, *, deny
    g, sg-argo-demo-accessor@mydomain.com, role:readonly
    g, sg-argo-demo-admin@mydomain.com, role:admin
```

Got similar results with the following policy:

```yaml
cm:
  users.anonymous.enabled: "false"
rbac:
  policy.default: "role:readonly"
  policy.csv: |
    g, sg-argo-dev-accessor@mydomain.com, role:readonly
    g, sg-argo-dev-admin@mydomain.com, role:admin
```

**To Reproduce**

1. Ensure Dex is enabled with the IDP connector.
2. Attempt to edit application details (e.g., labels or sync policies) through the Argo CD dashboard.

**Expected behavior**

Editing application details through the Argo CD dashboard should work without encountering a `403 Forbidden` error.

**Screenshots**

![image](https://github.com/user-attachments/assets/8ff43c2a-18c0-4cc8-9a55-4423865c573a)

**Version**

```shell
v2.12.4
```

**Logs**

No relevant information found in logs.
