### ISSUE TITLE
login `return_url` doesn't work with custom server paths

### ISSUE THREAD

**Issue by oleksandr-codefresh** [argoproj/argo-cd#21432]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

values.yaml
```
configs:
      params:
        server.basehref: /argocd 
        server.rootpath: /argocd 
```

**Expected behavior**

redirect should open `{url}/argocd/applications` , not `{url}/argocd/argocd/applications`

**Screenshots**

https://github.com/user-attachments/assets/fb0b6177-2ed8-4df9-9847-153d65beab0e

**Version**

```shell
Paste the output from `argocd version` here.
```
2.13.3

**Logs**

```
Paste any relevant application logs here.
```
