### ISSUE TITLE
Multiple sources (one helm repo, one local path) throws "failed to initialize repository resources" error

### ISSUE THREAD

**Issue by esn89** [argoproj/argo-cd#21456]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

Using ArgoCD's multi-source Application, one helm rpeo, one local path, things sync and get created fine, but throws an error on the bottom right saying:

```
Unable to load data: error acquiring repo lock: failed to initialize repository resources: rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed exit status 128: fatal: repository 'https://victoriametrics.github.io/helm-charts/' not found
```

**To Reproduce**

`application.yaml`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-single
  namespace: argocd
spec:
  project: management
  destination:
    namespace: vm
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://mycompanyrepo.com/bootstrap.git
    path: victoriametrics-assets
    targetRevision: master
  - repoURL: 'https://victoriametrics.github.io/helm-charts'
    chart: victoria-metrics-single
    targetRevision: 0.13.4
    helm:
      parameters:
      - name: server.persistentVolume.size
        value: "500Gi"
      - name: server.persistentVolume.storageClassName
        value: "premium-rwo"
      - name: server.retentionPeriod
        value: "3"
      - name: server.scrape.enabled
        value: "true"
  syncPolicy:
    syncOptions:
```

The `victoriametrics-assets/` path simply is a helm repo local to *this* `application.yaml`:

```bash
.
├── Chart.yaml
├── cluster-bootstrap-apps/templates/application.yaml
├── README.md
├── values.yaml
└── victoriametrics-assets
    ├── Chart.yaml
    ├── templates
     │   └── vs.yaml
    └── values.yaml
```

Inside of it I just create a VirtualService.

**Expected behavior**

A clean sync without errors. 

**Screenshots**

![image](https://imgur.com/a/dz467lU)

**Version**

```shell
{
    "Version": "v2.12.6+4dab5bd",
    "BuildDate": "2024-10-18T17:39:26Z",
    "GitCommit": "4dab5bd6a60adea12e084ad23519e35b710060a2",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
}

```

**Logs**

```
Unable to load data: error acquiring repo lock: failed to initialize repository resources: rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed exit status 128: fatal: repository 'https://victoriametrics.github.io/helm-charts/' not found
```

**Comment by crenshaw-dev** [comment]
@esn89 do you have a spec that reproduces the issue using all public repos? I tried this and was able to sync with no problems:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-single
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/argoproj/argocd-example-apps
      path: guestbook
      targetRevision: master
    - repoURL: 'https://victoriametrics.github.io/helm-charts'
      chart: victoria-metrics-single
      targetRevision: 0.13.4
      helm:
        parameters:
          - name: server.persistentVolume.size
            value: "500Gi"
          - name: server.persistentVolume.storageClassName
            value: "premium-rwo"
          - name: server.retentionPeriod
            value: "3"
          - name: server.scrape.enabled
            value: "true"
```

**Comment by esn89** [comment]
Confirming with you that, with your manifest, both public.  All is good, no errors.

**Comment by esn89** [comment]
If it helps, I have a manifest where I only deploy 2 local repos.  That also has no errors.

**Comment by esn89** [comment]
THis one syncs , but throws errors:

```yaml
  - path: argocd-assets
    repoURL: https://mycompany.com/bootstrap.git
    targetRevision: master
  - chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.6.12
```

[image](https://imgur.com/a/fX2sgTL)
