### ISSUE TITLE
helm umbrella chart - dependencies with authentication

### ISSUE THREAD

**Issue by jonahbohlmann** [argoproj/argo-cd#21463]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I configured an application containing a Git source with an umbrella Helm chart that has an OCI dependency from DockerHub. Despite adding the credentials for our DockerHub Pro account to the ArgoCD repository configuration, ArgoCD does not use them, leading to pull rate limit errors.

**To Reproduce**

1. Create a simple ArgoCD Application containing a git source
2. Create an umbrella chart with a docker oci helm chart dependency. In my case:
   ```
      - name: mongodb
        version: "16.4.0"
        repository: "oci://registry-1.docker.io/bitnamicharts"
   ```
3. Add the docker OCI repository to ArgoCD
4. Start a lot of syncs

**Expected behavior**
The repository from ArgoCD should also be used in helm dependencies.

**My code**

Repository
```
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-bitnamicharts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: dockerhub-bitnamicharts
  type: helm
  url: registry-1.docker.io/bitnamicharts
  username: xxx
  password: xxx
  enableOCI: "true"
```

Application
```
{{- $service := .Values.services.mongodb }}
{{- if $service.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: services
  destination:
    server: "https://kubernetes.default.svc"
    namespace: services
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  sources:
    - repoURL: https://git.xxx.de/xxx/portal/argocd-deployment.git
      path: charts/services/mongodb/
      targetRevision: {{ include "xxx.appTargetRevision" . }}
      helm:
        releaseName: mongodb
        passCredentials: true
        valueFiles:
          - /vars/base/services/mongodb.yaml
          - /vars/{{ .Values.bootstrapEnvironment }}/services/mongodb.yaml
{{ end }}
```

Chart.yaml
```
[...]
dependencies:
- name: mongodb
  version: "16.4.0"
  repository: "oci://registry-1.docker.io/bitnamicharts"
```

**Version**

```shell
argocd: v2.13.2+dc43124
  BuildDate: 2024-12-11T18:37:15Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

N/A

**Comment by NoelAussurin** [comment]
Hello ! I'm encountering the same problem with ArgoCD : 

<img width="1509" height="264" alt="Image" src="https://github.com/user-attachments/assets/34f8250e-4a0e-412e-86f3-d709410899e2" />
I have this secret written like it was told in [23469](https://github.com/argoproj/argo-cd/issues/23469) :

```
kind: Secret
apiVersion: v1
metadata:
  name: registry-1.docker.io
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  name: registry-1.docker.io/bitnamicharts
  password: my_password
  type: helm
  url: registry-1.docker.io/bitnamicharts
  username: my_username
type: Opaque
```

I can see it in ArgoCD :

<img width="1065" height="75" alt="Image" src="https://github.com/user-attachments/assets/eba7e36b-e71e-4075-b909-fb763e1c9da5" />

But it seems the credentials are not used and ArgoCD is still unregistered to docker.io when pulling charts.
