### ISSUE TITLE
Multi-source application using private OCI registry on Google Cloud: not a valid chart repository

### ISSUE THREAD

**Issue by medykn-git** [argoproj/argo-cd#21466]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to deploy a multi-source application using a private OCI Google Artifact Registry and a private Gitlab repository. ArgoCD is deployed on GKE, it acccesses the Artifact registry using workload identity. I've already tried several suggestions on other Github issues such as splitting differently the repoURL and chart fields, but I could not get it work. 

**To Reproduce**

Deploy an application with a similar setup.  

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <app>
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc/
  sources:
  - chart: <chart>
    repoURL: oci://<region>-docker.pkg.dev/<project>/<registry>
    targetRevision: v1.15.0
    helm:
      valueFiles:
      - $values/<app>/values.yaml
  - repoURL: https://gitlab.<domain>/<path>.git
    ref: values
    targetRevision: main
  syncPolicy: {}
```

**Expected behavior**

The app should be successfully deployed, containing the Helm chart of the first source configured with the values of the second source.

**Screenshots**

**Version**
```shell
argocd: v2.13.3+a25c8a0
  BuildDate: 2025-01-03T18:44:26Z
  GitCommit: a25c8a0eef7830be0c2c9074c92dbea8ff23a962
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.3+a25c8a0
```

**Logs**
```
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = error fetching chart: failed to fetch chart: failed to get command args to log: `helm pull --destination /tmp/88d30b00-556a-4bc1-bc5c-5eea321e73bd --version v1.15.0 --repo oci://<region>-docker.pkg.dev/<project>/<registry> <app>` failed exit status 1: Error: looks like "oci://<region>-docker.pkg.dev/<project>/<registry>" is not a valid chart repository or cannot be reached: object required
```
