### ISSUE TITLE
v1.2.0-rc1 nil pointer dereference when syncing

### ISSUE THREAD

**Issue by ijl** [argoproj/argo-cd#2146]
The initial sync of a repository using kustomize configuration fails with every application having the below output:

```
time="2019-08-14T11:06:29Z" level=info msg="Refreshing app status (spec.source differs), level (2)" application=example
W0814 11:06:29.461731       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
time="2019-08-14T11:06:29Z" level=info msg="Reconciliation completed" application=example fields.level=2 time_ms=0.074851
time="2019-08-14T11:06:29Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 95 [running]:
runtime/debug.Stack(0xc000a33818, 0x18332c0, 0x2cc1810)
\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem.func1(0xc00044d8c0, 0x17a4ee0, 0xc00054f370)
\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:620 +0x85
panic(0x18332c0, 0x2cc1810)
\t/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/argoproj/argo-cd/controller.(*ApplicationController).managedResources(0xc00044d8c0, 0x0, 0x2d04bf8, 0x0, 0xc0001f7c20, 0x17, 0x1)
\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:228 +0x3a
github.com/argoproj/argo-cd/controller.(*ApplicationController).setAppManagedResources(0xc00044d8c0, 0xc000937180, 0x0, 0x0, 0x1, 0xc0001f7c20)
\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:173 +0x3c
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppRefreshQueueItem(0xc00044d8c0, 0x1)
\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:700 +0x74b
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func3()
\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:298 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005bf4c0)
\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005bf4c0, 0x3b9aca00, 0x0, 0x5648646852336301, 0xc000540120)
\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005bf4c0, 0x3b9aca00, 0xc000540120)
\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
\t/go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:297 +0x2a9
"
```

The applications look like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
  labels:
    kind: server
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: path/to/example/environment
    repoURL: 'https://repo.git'
    targetRevision: HEAD
  project: example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
````

I can build the kustomize configuration using v3.1.0.

Argo was configured using `manifests/install.yaml`.

Argo v1.1.1 does not show this problem.
