### ISSUE TITLE
Multi Cluster Deploy of App of Apps: Permission Denied in GUI

### ISSUE THREAD

**Issue by abunet** [argoproj/argo-cd#21496]
HI,

I have two cluster:
corp-cluster-dev 
satellite1-cluster-dev

the two clusters are connected with rancher

ArgoCD is installed on both clusters. Every ArgoCD are configured.

I need to deploy, from ArgoCD in corp-cluster-dev an app to satellite1-cluster-dev. satellite1-cluster-dev is defined in ArgoCD corp-cluster-dev
The RBAC permissions seem to be created correctly between clusters

![Image](https://github.com/user-attachments/assets/c080f632-2fe4-4dc9-b90a-a5d297729971)

i have an app of app deployment the manifest has satellite1-cluster-dev as destination

```
project: mdw-dev
source:
  repoURL: https://scm-eng-fts.mydomain.com/rmq/mdw-argocd.git
  path: satellite1/layer-01/broker-01/dev/apps
  targetRevision: HEAD
  directory:
    recurse: true
    jsonnet: {}
destination:
  namespace: argocd
  name: satellite1-cluster-dev

```
the manifest loads this application
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: apps.itsw.layer-01.broker-01
    mdw.io/argocd: Application
  name: itsw.layer-01.broker-01
  namespace: argocd
spec:
  destination:
    name: satellite1-cluster-dev
    namespace: mdw-satellite1-dev
  project: mdw-dev
  sources:
    - chart: cf-core-broker
      helm:
        valueFiles:
          - $values/satellite1/layer-01/broker-01/dev/apps/cf-core-broker/values.yaml
      path: cf-core-broker
      repoURL: dre-eng-fts.mydomain.com/k8s-charts
      targetRevision: 0.1.0
    - ref: values
      repoURL: https://scm-eng-fts.mydomain.com/rmq/mdw-argocd.git
      targetRevision: HEAD
```

When i sync the Application is created on **corp-cluster-dev**:

![Image](https://github.com/user-attachments/assets/885d723f-ad26-4e65-bb09-b50b6d89905f)

if i switch on ArgoCD on the "child" cluster **satellite1-cluster-dev**, i can see the application deployment:

![Image](https://github.com/user-attachments/assets/234ca3c4-4f3e-418e-9c09-7402c912be39)

The problem is: when i click on open Application link on corp-cluster-dev (the main cluster) I receive an error:

![Image](https://github.com/user-attachments/assets/2596c01e-9825-4198-849b-b94960d2e6c2)

i cannot see in logs any specific error.

![Image](https://github.com/user-attachments/assets/eb8992b5-0f49-4029-b32c-afa28eda8342)
