### ISSUE TITLE
App `OutOfSync` if untracked resource with same name as `PostDelete` hook exists in app namespace

### ISSUE THREAD

**Issue by svghadi** [argoproj/argo-cd#21579]
**Describe the bug**

Application stays always `OutOfSync` when a `PostDelete` hook and an untracked resource have the same name. I have a `PostDelete` hook on a secret resource named _“post-delete-secret"_ which resets the data to empty, and I also have a cert-manager created secret resource with the same name, _“post-delete-secret”_ in the application namespace. This setup ensures the secret is cleaned up after removing the app.

Argo CD recognizes the extra secret as part of the application. However, since it’s a `PostDelete` hook, it expects the secret not to be present. As a result, the application is always in an `OutOfSync` state.

Is this expected behavior? The same behavior is observed with Helm hooks in Argo CD as well.

**To Reproduce**

1. Create app
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ./
    repoURL: https://github.com/svghadi/argocd-reproducer.git
    targetRevision: hook
  sources: []
  project: default
```
2. Perform Sync
3. Create a secret in destination namespace with same name as PostDelete hook  **(UPDATE: Missing steps)**
```bash
kubectl create secret generic post-delete-secret --from-literal=username=admin -n default
```
5. Observe `OutOfSync` in UI/CLI

**Expected behavior**

Argo CD should not track and display the extra resource with same name as postDelete hook and App should not be OutOfSync state.

**Screenshots**

<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/774e38b9-2133-4135-bcad-644ad10b6f6e" />

**Version**

```shell
v2.13.3
```
