### ISSUE TITLE
resources marked with resource hooks not participating in drift detection?

### ISSUE THREAD

**Issue by hsmade** [argoproj/argo-cd#21573]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
When a resource has helm hooks set to post-install/post-upgrade, and weight:2, the tagged resource does not seem to participate in drift detection.

I'm managing capi-operator in an argo enabled cluster. When I set the `core` value in the manifest, it renders the `CoreProvider` resource
through [this](https://github.com/kubernetes-sigs/cluster-api-operator/blob/release-0.14/hack/charts/cluster-api-operator/templates/core.yaml) template.
The resource gets from that template:
```yaml
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '2'
```

This seems to translate to sync-wave:2 and `PostSync`.
The resource indeed has the anchor icon:

![Image](https://github.com/user-attachments/assets/43f63897-166e-4804-85a2-3895c91ab286)

Now when I change the version for the core provider, by setting in the manifest the value for `core` to (for example) `cluster-api:v1.8.7`,
and argo does its refresh, the manifest in the `Application` gets updated, but the `CoreProvider` resource does not get changed.
In fact, it's not marked as drifted.

Only when I manually trigger a sync in argo, it recreates the resource with the right version.

**To Reproduce**
Application:
```yaml
project: default
source:
  repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
  targetRevision: 0.14.0
  helm:
    valuesObject:
      cert-manager:
        crds:
          enabled: false
        enabled: false
      configSecret:
        name: capi-manager
        namespace: capi-manager
      controlPlane: kubeadm:v1.8.7
      core: cluster-api:v1.8.7
      infrastructure: aws:v2.7.0
      manager:
        featureGates:
          aws:
            EKS: true
            EKSAllowAddRoles: true
            EKSEnableIAM: true
            MachinePool: true
  chart: cluster-api-operator
destination:
  server: https://kubernetes.default.svc
  namespace: capi-operator
syncPolicy:
  automated:
    prune: true
  syncOptions:
    - CreateNamespace=true
```

**Expected behavior**

I would expect that upon refresh, argo would show the yellow 'drift' icon. 
Or at least that it would trigger a sync because of pending changes.

**Screenshots**

**Version**

We're running `v2.13.3+a25c8a0`

**Logs**

There's no logs about this.
