### ISSUE TITLE
Helm template command fails on ArgoCD but works locally.

### ISSUE THREAD

**Issue by phvel01** [argoproj/argo-cd#21571]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When trying to install istio cni component I am met with error due to helm template command failing. When running the same command locally through the terminal no errors are shown and a manifest is generated.

**To Reproduce**

1. Pull istio cni chart using helm pull command.
2. Checkout feature branch with the chart and files included.
3. Create ArgoCD application through interface by pressing "New App"
4. Configure application to point to the branch and navigate to the directory with the chart.
5. Press Create.

**Expected behavior**

Application is created and configured based on the supplied values.yaml file etc.

**Version**

```shell
v2.13.0+347f221
```

**Logs**

```
Unable to create application: application spec for istio-cni is invalid: InvalidSpecError: Unable to generate manifests in management-system/managed-operators/helmcharts/istio/cni: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template istio-cni --namespace istio-system --kube-version 1.30 <api versions removed> --include-crds` failed exit status 1: Error: template: cni/templates/clusterrole.yaml:17:8: executing "cni/templates/clusterrole.yaml" at <eq (coalesce .Values.platform .Values.global.platform) "openshift">: error calling eq: incompatible types for comparison Use --debug flag to render out invalid YAML Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name>
```

**Comment by reggie-k** [comment]
I see in the error that you are using Vault Plugin, could you paste your plugin configuration + manifest of the application you are trying to create?

**Comment by phvel01** [comment]
The manifest of the application is quite extensive and split between multiple files this is the default setup when pulling the helm chart using the helm pull command. Would you like me to copy all of it and paste it?

But here is the configuration for the vault plugin, among other things:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: helm-wrapper
          configMap:
            defaultMode: 509
            name: helm-wrapper
        - name: gcloud
          emptyDir: {}
      initContainers:
        - name: install-gcloud
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying Gcloud SDK"
              cp -R /google-cloud-sdk/* /gcloud
          volumeMounts:
            - mountPath: /gcloud
              name: gcloud
        - name: copy-helm
          image: argoproj/argocd:v2.1.0 # contains helm 3.6.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying Helm..."
              cp /usr/local/bin/helm /custom-tools/helm
              echo "Done."
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
        - name: install-argocd-vault-plugin
          image: alpine:3.8
          command: [sh, -c]

          # Don't forget to update this to whatever the stable release version is
          # Note the lack of the `v` prefix unlike the git tag
          env:
            - name: AVP_VERSION
              value: "1.7.0"
          args:
            - >-
              wget -O argocd-vault-plugin
              https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
              chmod +x argocd-vault-plugin &&
              mv argocd-vault-plugin /custom-tools/argocd-vault-plugin
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      serviceAccountName: gke-argocd
      containers:
        - name: argocd-repo-server
          env:
          - name: AVP_TYPE
            value: gcpsecretmanager
          volumeMounts:
          - mountPath: /google-cloud-sdk
            name: gcloud
          - mountPath: /usr/local/bin/_helm
            name: custom-tools
            subPath: helm
          - mountPath: /usr/local/bin/helm
            name: helm-wrapper
            subPath: helm
          - mountPath: /usr/local/bin/argocd-vault-plugin
            name: custom-tools
            subPath: argocd-vault-plugin

```
