### ISSUE TITLE
SelfHealAttemptsCount not resetting if application syncs successfully/on new revision

### ISSUE THREAD

**Issue by Aaron-9900** [argoproj/argo-cd#21599]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

[This PR](https://github.com/argoproj/argo-cd/pull/20275) introduced the possibility to add _Exponential Backoff_ to ArgoCD self-heal attempts. I've noticed however that `SelfHealAttemptsCount` is never reset if the application self heals correctly/a new revision comes by, so even if the self-heal succeeds, a future deployment will wait the 300s (or the maximum set by the user) if it needs to self heal.

**To Reproduce**

Create an ArgoCD application that causes self-heal to trigger indefinetly:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.1
        randomField: "randomValue" # This will cause ArgoCD to keep trying to self heal
```

Also, enable selfHeal and autoSync for the application.

After letting the application attempt to self heal multiple times, create a commit removing randomField and wait for it to sync **do not manually sync, that makes the issue not occur**. Check the state of the application, and you will see that autoHealAttemptsCount is not reset to 0.

If you later add again the problematic field, it will wait for 300s

**Expected behavior**

After a successful sync that doesn't leave the app in an out of sync state, it should update autoHealAttemptsCount to 0. Also, a new revision should cause the autoHealAttemptsCount to be 0 as well, since the attempts refer now to a new version of the application

**Screenshots**

**Version**

```shell
> argocd version

argocd: v2.13.3+a25c8a0
  BuildDate: 2025-01-03T19:56:17Z
  GitCommit: a25c8a0eef7830be0c2c9074c92dbea8ff23a962
  GitTreeState: clean
  GoVersion: go1.23.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.0.0+3a29a74
```
