### ISSUE TITLE
Improve argocd app sync --dry-run Behavior for Non-Existent Applications

### ISSUE THREAD

**Issue by jsolana** [argoproj/argo-cd#21659]
# Summary

The `argocd app sync --dry-run` command does not work when the specified application does not exist. Instead of providing a clear and descriptive error message, it returns a vague **Permission Denied" error**.

# Motivation

A more robust `--dry-run` utility would allow users to verify actions without making changes, even in scenarios where the specified application does not exist. This would make the tool more consistent and helpful, especially when verifying user actions or debugging potential modifications.

How to reproduce it:

```console
kind create cluster
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
kubectl port-forward svc/argocd-server -n argocd 8080:443
argocd login localhost:8080 --username admin --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) --insecure

# test with a non existent app
argocd app sync busybox-echo --dry-run --timeout 60 --retry-limit 1

<img width="498" alt="Image" src="https://github.com/user-attachments/assets/8a280b2a-3b0a-44fd-bf43-71835b2fa4c0" />

```

The app yaml:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox-echo
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  destination:
    namespace: busybox-echo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/busybox
    repoURL: https://github.com/jsolana/argocd-applications
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
      limit: 2
    syncOptions:
    - CreateNamespace=true
```

# Proposal

If feasible, the `argocd app sync --dry-run` command should behave consistently for both existing and non-existent applications. It should simulate the sync process as closely as possible, providing valuable feedback about the intended actions, even if the application does not currently exist. This would allow users to validate their changes effectively and detect potential issues during pull request reviews.

If there are technical limitations preventing this, the behavior should be adjusted to provide clear and actionable feedback:

- Detect whether the application exists before proceeding with the dry-run.
- If the application does not exist, return a descriptive error message, e.g.: "Error: Application '<app-name>' does not exist."
- Ensure the message is informative and helps users understand the issue and how to address it.
