### ISSUE TITLE
Show container version for each argocd Application

### ISSUE THREAD

**Issue by perpective2410** [argoproj/argo-cd#21662]
Hello,

We would like to be able to display in the ArgoCD UI the image.tag located in values-app.yaml
We are deploying our stack with an applicationSet based on a git generator and a folder structure.
We could maybe display this image tag as a label? Any idea how we could achieve this? I know we could use the CLI, but its an information that we want for non-tech people in our company.

`values-app.yaml`

```
  image:
    tag: "0.1.27"
```

`ApplicationSet`
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nonprod-uks-xxx
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: environments/pol-sandpit/nonprod-uks/*/*/*
      repoURL: git@ssh.dev.azure.com:v3/xxx
      revision: main
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
  goTemplate: true
  template:
    metadata:
      labels:
        application: '{{ .path.basename }}'
        environment: '{{ index .path.segments 2 }}'
        type: '{{ index .path.segments 4 }}'
      name: '{{ .path.basename }}-{{ index .path.segments 3 }}-{{ index .path.segments 2 }}'
    spec:
      destination:
        name: '{{ index .path.segments 2 }}'
        namespace: '{{ index .path.segments 3 }}'
      project: xxx
      revisionHistoryLimit: 10
      source:
        helm:
          ignoreMissingValueFiles: true
          releaseName: '{{ .path.basename }}-{{ index .path.segments 3 }}-{{ index.path.segments 2 }}'
          valueFiles:
          - values-app.yaml
        path: environments/pol-sandpit/nonprod-uks/{{ index .path.segments 3 }}/{{index .path.segments 4 }}/{{ .path.basename }}
        repoURL: git@ssh.dev.azure.com:v3/xxx
        targetRevision: main
```
