### ISSUE TITLE
Auto-sync not triggering after deny rule becomes inactive in syncWindow

### ISSUE THREAD

**Issue by matthew-parry-cc** [argoproj/argo-cd#21692]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When pushing a change while a deny syncWindow rule is in place, auto-sync does not trigger a sync once the rule is lifted and the window is open a allow sync. 
For example: we have a deny window active, except from allowing 16:00-17:00. Pushing a change at 15:30 results in the application being out-of-sync. Once the window is lifted at 16:00, the sync-window can be seen as disabled in the UI, however the application is still out-of-sync and auto-sync does not kick in. Manual sync works during this period and if a new change is pushed while the window is lifted, auto-sync will trigger for that subsequent change. 

**To Reproduce**

- Sync window set in application project:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample
  namespace: argocd
spec:
...
  syncWindows:
  - kind: deny
    schedule: '0 0-15,17-23 * * *'
    duration: 1h
    applications:
      - myservice
```

- Application configured with auto-sync:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myservice
...
spec:
  project: sample
...
  syncPolicy:
    automated: {}
```

- Change made to application version prior to 16:00, while deny window is active and blocking sync.
- Application shows as out-of-sync in UI with desired changes, but blocked by syncWindow rules.
- Sync-window lifted at 16:00 and shows as disabled in UI.
- Auto-sync does not trigger a sync action despite being indicated as enabled in UI.
- A sync is triggered when a new, subsequent change is pushed to the application within the allowed window. 

**Expected behavior**

Expected auto-sync to kick in once the sync window deny rule was lifted at 16:00, without having to push an additional change. 

**Version**

```shell
argocd: v2.13.3+a25c8a0
BuildDate: 2025-01-03T18:44:26Z
GitCommit: a25c8a0eef7830be0c2c9074c92dbea8ff23a962
GitTreeState: clean
GoVersion: go1.23.1
Compiler: gc
Platform: linux/amd64
```
