### ISSUE TITLE
SSO Double Slash in URL Causes 404 Not Found Error When Querying Dex Provider

### ISSUE THREAD

**Issue by aomaryoussef** [argoproj/argo-cd#21766]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am encountering a 404 Not Found error when Argo CD attempts to query the Dex provider. The issue appears to be caused by a malformed URL with an extra slash (//), resulting in a URL like https:/*******.com//api/dex. This causes the request to fail with a 404 response.
```
apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: saml
      name: Microsoft
      config:
        entityIssuer: "https://********.com/api/dex/callback"
        ssoURL: https://login.microsoftonline.com/****************/saml2
        caData: |
          ****************
        redirectURI: "https://******.com//api/dex/callback"
        usernameAttr: email/email
        emailAttr: email/email
        groupsAttr: Group
  exec.enabled: "true"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://******.com
```

**Expected behavior**

Argo CD should correctly construct the URL without an extra slash, e.g., https://**********.com/api/dex, and successfully query the Dex provider.

**Actual Behavior**

Argo CD constructs the URL with an extra slash (//), resulting in https://******.com//api/dex, which causes a 404 Not Found error.

*But when I try to refresh the page multiple times, I can suddenly access my ArgoCD Home Page.*
*NOTE*: I tried to downgrade the Dex Server image version to  v2.30.2 and I am facing the same issue

**Version**

```shell
Chart Version: argo-cd-5.27.3
App Version: v2.7.2
Dex Image Version: v2.35.3
```
