### ISSUE TITLE
Argo CD displays two images in Application summary (one outdated and one correct)

### ISSUE THREAD

**Issue by Rmaabari** [argoproj/argo-cd#21785]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When deploying our application with Argo CD, the Application summary shows two images:

registry.example.com/sample-app:0.0.1 (unexpected/outdated)
registry.example.com/sample-app:0.0.1-c56fcf54 (the correct, updated image)

We expect only the correct image to be shown. It appears that either a stale default image tag from the Helm chart or an intermediate rollout state is being detected by Argo CD.

**To Reproduce**
1. Helm Values File (env/dev.yaml):
```
namespace: default

image:
  registry: registry.example.com
  repository: sample-app
  pullPolicy: IfNotPresent
  tag: ""

env:
  - name: LOGGING
    value: ""

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8888
  
readinessProbe: 
  httpGet:
    path: /readiness
    port: http

livenessProbe: 
  httpGet:
    path: /liveness
    port: http

resources:
  limits:
    cpu: 500m
    memory: 4096Mi
  requests:
    cpu: 100m
    memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80s

replicaCount: 1

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
```

2. Deployment Template (templates/deployment.yml):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "generic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if gt (len .Values.livenessProbe) 0 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
      {{- end }}
      {{- if gt (len .Values.readinessProbe) 0 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

```
3. Argo CD Application (app.yaml):
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/myproject/sample-app.git'
    targetRevision: argo-test
    path: helm/sample-app
    helm:
      valueFiles:
        - env/dev.yaml
  destination:
    server: 'https://10.1.1.1:6443'
    namespace: argo-test
  syncPolicy:
    automated: {}
```

4. Deploy the application via Argo CD.

5. Once synced, inspect the Application summary. Under the summary: images section, observe that two images are listed:

registry.example.com/sample-app:0.0.1
registry.example.com/sample-app:0.0.1-c56fcf54 (correct commit from gitlab)

**Expected behavior**

Only the correct image (registry.example.com/sample-app:0.0.1-c56fcf54) should be displayed in the Application summary. The outdated tag (0.0.1) should not appear if the deployment is fully updated.

**Screenshots**

<img width="1529" alt="Image" src="https://github.com/user-attachments/assets/a1069b51-237a-4ef3-98d0-921de58e2096" />

**Version**

![Image](https://github.com/user-attachments/assets/90687f97-5fce-4131-97f4-0d02d2e761b8)

**Logs**
```
time="2025-02-05T09:41:26Z" level=info msg="helm template . --name-template sample-app --namespace argo-test --kube-version 1.26 --values /tmp/_argocd-repo/67e9c6ad-1dc9-4f59-adb0-fb4106716fd8/helm/sample-app/env/dev.yaml --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1/Challenge --api-versions acme.cert-manager.io/v1/Order --api-versions admissionregistration.k8s.io/v1 
```
Additional Context:

Our Helm chart defaults the image tag to an empty string, which then falls back to .Chart.AppVersion.
Our CI/CD pipeline overrides the image tag during deployment, leading to the correct tag 0.0.1-c56fcf54 on some pods.
It appears that during a rolling update (or due to a reconciliation issue), Argo CD detects both the default and overridden image tags.
This might be related to how Argo CD compares the desired state (from Git/Helm) with the live state in the cluster.
Any insights or suggestions on how to address this discrepancy would be appreciated.
