### ISSUE TITLE
sso login with cli doesn't work

### ISSUE THREAD

**Issue by jaxxstorm** [argoproj/argo-cd#2179]
**Describe the bug**
Similar to #1266 - i can login via the web interface, but the cli fails. I have the same callback URL set for the web and cli interface, using an external dex. Here's the configuration from that:

```
staticClients:
- id: "argocd"
  name: "argocd"
  redirectURIs: [ "https://argocd.example.com/auth/callback", "http://localhost:8085/auth/callback" ]
  secret: "supersecret"
```

When I run the cli login flow, I get this
```
DEBU[0000] OIDC Configuration:
DEBU[0000]   supported_scopes: [openid email groups profile offline_access]
DEBU[0000]   response_types_supported: [code]
Opening browser for authentication
Performing authorization_code flow login: https://dex.example.com/auth?access_type=offline&client_id=argocd&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=<state>
DEBU[0004] Callback: /auth/callback?code=<code>&state=VrAEaiNlmd
FATA[0004] oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}
```

I can see in the dex logs that the dex implementation returns the relevant groups etc. My argocd config map looks like this

```
apiVersion: v1
data:
  oidc.config: |
    name: dex
    issuer: https://dex.example.com
    clientID: argocd
    clientSecret: $dex.clientSecret
  url: https://argo.example.com
```
Any ideas what this might be?
