### ISSUE TITLE
Support gotemplating in Appset generator selectors

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argo-cd#21803]
# Summary

It could be useful to support gotemplating in the Appset generators selectors, as it's already supported in other parts of the generators.

# Motivation

It can be needed for example when we use a matrix of "something" + cluster generators, to allow dynamic labels to be used as matchers.
Let's say we want to deploy to different environment (staging, production) and that target environment is defined in the git generator files.
We could select the related clusters using that value, in the selector:

Example:

```
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/argoproj/argo-cd.git
              revision: HEAD
              directories:
                - path: applicationset/examples/matrix/cluster-addons/*
          - clusters:
              selector:
                matchLabels:
                  environment: "{{ .environment }}"
```

# Proposal

I would propose to support gotemplating in the selectors, such as:

matchLabels:
- key: gotemplate support
- value: gotemplate support

matchExpression:
- key: gotemplate support
- operator: static, no gotemplating
- values: gotemplate support
