### ISSUE TITLE
Application property kustomize.patches not erroring and not applying patch

### ISSUE THREAD

**Issue by NelsonG6** [argoproj/argo-cd#21812]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Patches under application or applicationset, source, kustomize, patches, are not being applied, and no error is being thrown either.

**To Reproduce**
Following docs here on kuztomize/patches:
https://argo-cd.readthedocs.io/en/latest/user-guide/kustomize/#patches

Manifests:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-test
spec:
  project: external-secrets
  source:
    path: other/external-secrets
    repoURL: redacted
    kustomize:
      patches:
        - target:
            kind: ClusterSecretStore
            name: default-kv
          patch: |-
            - op: replace
              path: /spec/provider/azurekv/vaultUrl
              value: https://test.vault.azure.net
        - target:
            kind: ServiceAccount
            name: workload-identity-sa
          patch: |-
            - op: replace
              path: "/metadata/annotations/azure.workload.identity~1client-id"
              value: test
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
```

I am required to have a kustomization.yaml file at the path:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - external-secrets.yaml
patches:
```
I have tried this with the patches property being empty, containing an arbitrary patch I don't want, and having no patches property at all, all with the same result of the patches in the application manifest not being applied. If I copy the patch from the application to the kustomization.yaml file, the patch works, leading me to believe the syntax of the patch is correct.

I have tried this by using an application and an applicationset with no luck. This ideally will work for an applicaitonset.

I have tried this by using bases and resources in kustomize to point to the external-secrets.yaml file with no luck.

**Expected behavior**

When a diff is generated, the patch appears at the intended properties. It does this if the patch is placed in the kustomization.yaml file, but not in the application spec. Wondering if I could sync and the patch might get caught at that phase, the resources are not patched there either, which is expected since the patch doesn't show up for the diff.

**Version**

argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:21:23Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.14.2+ad27246
  BuildDate: 2025-02-05T23:44:17Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0

**Logs**

Logs for the application controller do not seem to mention this issue.

**Comment by crenshaw-dev** [comment]
Confirm that your Application CRD is up to date. Do a `kubectl get app -oyaml` and confirm that the patches field is populated on the cluster.

**Comment by crenshaw-dev** [comment]
I wasn't able to reproduce this issue. I used this to test:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      patches:
        - patch: |-
            - op: replace
              path: /spec/template/spec/terminationGracePeriodSeconds
              value: 60
          target:
            kind: Deployment
            name: guestbook-ui
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD

```

<img width="1310" alt="Image" src="https://github.com/user-attachments/assets/c29be1bb-77b4-4864-ac76-fddd9555948d" />

Can you put together a spec that reproduces the issue on a public repo?

**Comment by NelsonG6** [comment]
Thanks for looking into it, Dan. Can you share what your kustomization.yaml file looks like? That's one part that is missing in the docs. I will work on putting my config together in a public repo as well.

**Comment by NelsonG6** [comment]
https://github.com/NelsonG6/argo-issue/tree/main/other/external-secrets/overlays

Here's a public repo with the manifests.

**Comment by crenshaw-dev** [comment]
The first patch works fine for me:

```yaml
      - patch: |-
          - op: replace
            path: /spec/provider/azurekv/vaultUrl
            value: crenshaw
        target:
          kind: ClusterSecretStore
          name: default-kv
```


<img width="625" alt="Image" src="https://github.com/user-attachments/assets/15f76e93-84be-42ad-a895-2223ec051588" />

The second patch didn't work at first, but I think it's because the ServiceAccount name was wrong. I updated the name, and it worked:

```yaml
      - patch: |-
          - op: replace
            path: "/metadata/annotations/azure.workload.identity~1client-id"
            value: crenshaw
        target:
          kind: ServiceAccount
          name: cluster-secret-store-sa
```

<img width="620" alt="Image" src="https://github.com/user-attachments/assets/5732881d-a752-4e81-9efd-c1ae79cd9536" />
