### ISSUE TITLE
The ArgoCD v2.14.0 doesn't correctly identify  the targetRevision.

### ISSUE THREAD

**Issue by jackalbsd** [argoproj/argo-cd#21818]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

Moving from v 2.13.1 to v.2.14.2 we found that the tag tracking doesn't work again. 

Deployed version of ArgoCD

<img width="873" alt="Image" src="https://github.com/user-attachments/assets/ce884059-87c8-4211-81ad-247c7b72e6f2" />

These configurations are not working anymore:
```shell
     - repoURL: xxx.yyy/charts
      chart: thechart
      # targetRevision should be changed to a released version of topstack
      targetRevision: "2024.03-LTS-RC19"
```
or
```shell
     - repoURL: xxx.yyy/charts
      chart: thechart
      # targetRevision should be changed to a released version of topstack
      targetRevision: "2024.06-RC19"
```

<img width="1109" alt="Image" src="https://github.com/user-attachments/assets/d1efb962-2c97-44d8-938e-73e3ebda38ca" />

<img width="1422" alt="Image" src="https://github.com/user-attachments/assets/1c8e402e-88df-4c28-8f36-85713faf6352" />

<img width="1349" alt="Image" src="https://github.com/user-attachments/assets/c7c446a5-9bf8-496f-9a7c-b62f508670b4" />

However, this targetRevision works as expected
```shell
     - repoURL: xxx.yyy/charts
      chart: thechart
      # targetRevision should be changed to a released version of topstack
      targetRevision: "2024.10.3"
```

<img width="1146" alt="Image" src="https://github.com/user-attachments/assets/af537860-9270-40f6-beaf-1fa58868850e" />

**Version**

```shell
{
    "Version": "v2.14.2+ad27246",
    "BuildDate": "2025-02-05T23:44:17Z",
    "GitCommit": "ad2724661b66ede607db9b5bd4c3c26491f5be67",
    "GitTreeState": "clean",
    "GoVersion": "go1.23.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.3 2024-07-19T16:40:33Z",
    "HelmVersion": "v3.16.3+gcfd0749",
    "KubectlVersion": "v0.31.0",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Unable to sync: error resolving repo revision: rpc error: code = Unknown desc = invalid revision '2024.03-LTS-retail': constraint Parser Error

Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = invalid revision '2024.06-RC30': constraint Parser Error

{"error":"rpc error: code = FailedPrecondition desc = error resolving repo revision: rpc error: code = Unknown desc = invalid revision '2024.06': constraint Parser Error","grpc.code":"FailedPrecondition","grpc.method":"Sync","grpc.service":"application.ApplicationService","grpc.start_time":"2025-02-06T09:59:26Z","grpc.time_ms":44.899,"level":"warning","msg":"finished unary call with code FailedPrecondition","span.kind":"server","system":"grpc","time":"2025-02-06T09:59:26Z"}

```

Taking into the account that there are very interesting features included into v2.14.0 we would like to use it as much as we coold.
However, this issue prevents us from the v2.14.2 usage 

Thank you for the help

**Comment by andrii-korotkov-verkada** [comment]
Might be related to semver work. My hunch is it may be complaining about not following the format with 3 numbers, i.e. `<major>.<minor>.<patch>[-<suffix>]`. Can you try adding a patch version and see if it fixes the issue, please?

**Comment by jackalbsd** [comment]
Yes, you are right.

<img width="1044" alt="Image" src="https://github.com/user-attachments/assets/b123fd46-a2f5-4c8d-b46d-d70c1a2a56c9" />

The only issue is that our devs don't use this format quite much :( 
May I ask, was this check introduced in 2.14.x?
Because with v2.13.x everything is fine

Thank you

**Comment by jackalbsd** [comment]
So far I found this PR https://github.com/argoproj/argo-cd/pull/20096/files which could potentially cause it
I can check on Monday if my assumption is correct

**Comment by jackalbsd** [comment]
This is strange.
I just did several test with different targetrevision variants and suddenly previous one stopped woking.

The only working for now is `<major>.<minor>.<patch>`
The error is the same

<img width="1055" alt="Image" src="https://github.com/user-attachments/assets/ba803b5a-fbc4-40e6-aa4d-a56284bda471" />
<img width="1057" alt="Image" src="https://github.com/user-attachments/assets/77743b4c-2e30-4de2-bfbe-0824ee390e80" />
<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/d90bdfcd-b3d5-4dbf-9bed-edb8ca18a1a7" />

**Comment by andrii-korotkov-verkada** [comment]
Can you try prefix it with `v`, e.g. `v2024.06.1-retail`?

**Comment by andrii-korotkov-verkada** [comment]
@jackalbsd, @pierreyves-lebrun, based on your work on https://github.com/argoproj/argo-cd/pull/19644, can you check this issue and see if it can be related to the topic from that issue, please?

**Comment by blakepettersson** [comment]
I think this might stem from #20096, @PaulSonOfLars

**Comment by PaulSonOfLars** [comment]
@blakepettersson I believe #20096 was released as part of 2.13. It was also aimed at git clients, whereas this appears to be a helm issue - the two don't share the same core logic, which is one of the issues that was going to be addressed in a followup PR.
The PR which unifies the version resolution logic is #20216, but that hasn't been merged yet.

Regarding the issue itself - `2024.03-LTS-RC19` is not a valid semver version, and so I don't think it should undergo semver resolution (which I believe to be the issue here). 
In fact, the semver unification PR removes the [line throwing the current error](https://github.com/argoproj/argo-cd/pull/20216/files#diff-66db997cf6001ce63d5c5803380962f4b474aae67abacc9e86192673080d2c59L2426), in favour for doing resolution separately. So merging that might actually fix this issue.

**Comment by PaulSonOfLars** [comment]
I'm happy to update #20216 with some tests that cover this case, if that could help?

**Comment by jackalbsd** [comment]
It would be great if you could do this.
Thank you.

**Comment by PaulSonOfLars** [comment]
After further investigation, it seems like this may be a breaking change introduced by the upgrade to semver 3.3.1, which changed the regex for version parsing: https://github.com/Masterminds/semver/releases/tag/v3.3.1

**Comment by PaulSonOfLars** [comment]
I've just checked the timestamps for the [commit regarding the upgrade of semver](https://github.com/argoproj/argo-cd/commit/29ac23827a0722c96a09a9e1cd52f597679210f2) to `v3.3.1`; it was merged 5 minutes **after** the [release of argocd `2.13.1`](https://github.com/argoproj/argo-cd/commit/af54ef8db5adfa77a08d4d05b1318a2198084c22), meaning `2.13.1` is the last know "good" version.

I've also managed to verify that this error no longer happens when downgrading semver back to 3.3.0.

I've now updated #20216 to handle this new behaviour (see [this commit](https://github.com/argoproj/argo-cd/pull/20216/commits/4468b90f07dfda4c6b4451193a1ef6301173fee2)), with a test to specifically handle this case.

**Comment by blakepettersson** [comment]
Those are great finds, thank you @PaulSonOfLars!

**Comment by jackalbsd** [comment]
Hi guys.
I hope everyone is ok.
Could you please share any info regarding the issue?
When it could be fixed?
Thank you

**Comment by crenshaw-dev** [comment]
@PaulSonOfLars just so you know, the "Bump" commit time isn't a reliable marker for what made it into a release. Look at the version tag instead.

**Comment by josecsotomorales** [comment]
This is the same issue I'm facing, documented here: https://github.com/argoproj/argo-cd/issues/22404

**Comment by josecsotomorales** [comment]
Here's an example of my Helm repo with some versions, this shouldn't cause any issue with SemVer in theory as it follows `<major>.<minor>.<patch>`:

```yaml
apiVersion: v1
entries:
  develop-app:
  - apiVersion: v2
    created: 2025-03-19T02:47:55.681136998Z
    description: A Helm chart for Kubernetes
    digest: 2338e17a697c234028d33912614124a8e31bf23ebd7521d89069339293498cfc
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0319.0247.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0319.0247"
  - apiVersion: v2
    created: 2025-03-18T18:15:30.561236891Z
    description: A Helm chart for Kubernetes
    digest: 9a3bf73a12d5c2342e67989bde125c4a13df3b6a9023456fa8920c314d0fd87b
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0318.1815.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0318.1815"
  - apiVersion: v2
    created: 2025-03-17T10:30:45.121893572Z
    description: A Helm chart for Kubernetes
    digest: a8e3bf23ebd7521d89069339293498cfc2338e17a697c234028d33912614124a
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0317.1030.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0317.1030"
  - apiVersion: v2
    created: 2025-03-16T08:05:22.987654321Z
    description: A Helm chart for Kubernetes
    digest: 4e17a697c234028d33912614124a8e31bf23ebd7521d89069339293498cfc23
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0316.0805.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0316.0805"
generated: 2025-03-19T02:49:04.121378572Z
```
