### ISSUE TITLE
Autosync in multi source application doesn't work

### ISSUE THREAD

**Issue by MrFreezeex** [argoproj/argo-cd#21869]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

On a multi source apps ArgoCD, autosync doesn't always function properly. ArgoCD does detect that there is some change to sync but never sync them even though auto sync is enabled (see to reproduce section).

Prior relevant bug reports: #12939 / #12366

As noted by some people in the above bug report, adding self heal fix the issue.

**To Reproduce**
Here is a small reproducer with two sources, one is the nginx bitnami chart:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autosynctest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: nginx
      targetRevision: "19.0.0"
      helm:
        valuesObject:
          commonLabels:
            test1: test1
  destination:
    name: in-cluster
    namespace: test-autosync-multi-source
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```

Now if you update the application and add another labels under `spec.sources[0].helm.valuesObject.commonLabels` you will see that argocd will detect changes but never autosync unless you sync it manually. If you now use `source` instead of `sources` the autosync will function properly.

Note that in production we noticed that while updating the content of the `valueFiles` inside the application spec (which is the reason why this specific app is a multi source app). Now if we update the file directly that are referenced by some `valueFiles` auto sync does work properly.

**Expected behavior**

Updating `valueObjects`/`valueFiles` (and probably `values`) in an autosync app should actually trigger a sync

**Screenshots**

Not entirely sure if it's relevant but here is a screenshot of the app not synced above:

![Image](https://github.com/user-attachments/assets/77c3a7ed-5df4-4902-9f94-5d6a99e41de6)

**Version**

2.14.2

**Logs**

N/A
