### ISSUE TITLE
How to give a specific user access to a specific cluster

### ISSUE THREAD

**Issue by kyungminchoi** [argoproj/argo-cd#21908]
Hello, I am using argocd in conjunction with keycloak.
I want to separate a project from argocd and provide it to a specific keycloak user group.
For example, I want to create a project called 'athos' in argocd, and users belonging to the keycloak group called argocd_athos_group can only use this project.
At this time, I want to prevent athos users from viewing other projects, clusters, repositories, etc.

After testing with my v2.13.4 argocd, it seems that there is no way to allow argocd_athos_group users to view only the 'athos' cluster with the current argocd policy.

p, role: Athos, applications, *, athos/*, allow
p, role: Athos, projects, *, athos, allow
p, role: Athos, clusters, create, *, allow
p, role: Athos, clusters, get, *, allow
p, role: Athos, repositories, create, *, allow
p, role: Athos, repositories, get, *, allow
g, argocd_athos_group, role: Athos

My argocd policy is as above.
In this case, the argocd_athos_group user can view all clusters.

However,

p, role: Athos, clusters, get, athos-dev, allow

or

p, role: Athos, clusters, get, clusters/athos-dev, allow

or

p, role: Athos, clusters, get, athos*, allow

etc., I tried to make the argocd_athos_group user see only the 'athos-dev' cluster, but nothing was shown.

So my question is
1. Is there no feature in the current latest version of ArgoCD to allow a specific user to see only a specific cluster?
2. If it doesn't exist now, is there a possibility that it will be provided in the future?
3. If it does exist now, how do I do it?

If anyone knows, please answer.

**Comment by rumstead** [comment]
https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#creating-projects

Have you tried scoping the project to specific clusters?

Eg something like this (below is untested):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: athos
  namespace: argocd
spec:
  description: Project for athos applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      name: 'anthos-*'
  roles:
    - name: athos-role
      description: Role for users in argocd_athos_group
      policies:
        - p, proj:athos:athos-role, applications, get, athos-*, allow
      groups:
        - argocd_athos_group
```

**Comment by kyungminchoi** [comment]
@rumstead 

The same thing happens if you set it up like this:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: athos
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: 클라우드엔지니어링2팀 프로젝트
  destinations:
  - name: athos-dev
    namespace: '*'
    server: https://10.150.231.144:6443
  roles:
  - description: Role for users in argocd_athos_group
    groups:
    - argocd_athos_group
    name: athos-role
    policies:
    - p, proj:athos:athos-role, applications, get, athos/*, allow
    - p, proj:athos:athos-role, clusters, get, athos-dev, allow
  sourceRepos:
  -  '*'
```

**Comment by rumstead** [comment]
My last suggestion would be to also scope the clusters to the same project and see if that works - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters

**Comment by kyungminchoi** [comment]
@rumstead THANK YOU !! 
As you said, I added the project value under the data of the cluster Secret, and now only the athos-dev cluster is visible to the athos user.
```
apiVersion: v1
type: Opaque
kind: Secret
data:
  config:
  name: YXRob3MtZGV2
  project: YXRob3M=     ### I just added this part ### 
  server: aHR0cHM6Ly8xMC4xNTAuMjMxLjE0NDo2NDQz
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-10.150.231.144-3541595423
  namespace: argocd
```

Lastly, can I ask one more question? 
Can a **repository** also be scoped to belong to a specific **project**, like a cluster?
