### ISSUE TITLE
Expand the `ref` parameter and `$values` variable available with Helm multiple sources.

### ISSUE THREAD

**Issue by chauncey-garrett** [argoproj/argo-cd#21923]
# Summary

Expand the `ref` parameter and `$values` variable available with Helm multiple sources to include the `ref` source's build environment.

# Motivation

Expanding the `ref` parameter to include additional meta such as the ref's source build environment could be useful. For example, having `ARGOCD_APP_REVISION` could be useful to pass into an upstream helm chart if  a custom docker image were generated in the ref'd private repo so it could be referenced by commit hash.

```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valuesObject:
        server:
          image:
            # custom docker image built in https://git.example.com/org/value-files.git
            repository: https://path/to/custom/image/repo 
            tag: $values.ARGOCD_APP_REVISION
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: values
```

# Proposal

Add the build environment meta for a source to the `$values` object. https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/

```
$values.ARGOCD_APP_NAME
$values.ARGOCD_APP_NAMESPACE
$values.ARGOCD_APP_REVISION
...
```
