### ISSUE TITLE
Failed to unmarshal "config.yaml": <nil>

### ISSUE THREAD

**Issue by obervinov** [argoproj/argo-cd#21934]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Through the helm chart, argo-cd should deploy the following manifests to kubernetes
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-1
spec:
  limits:
    memory: 192Gi
  template:
    metadata:
      labels:
        node-group: nodepool-1
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: generic
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - r6a
        - key: karpenter.k8s.aws/instance-memory
          operator: In
          values:
            - '4096'
      startupTaints:
        - effect: NoExecute
          key: node.cilium.io/agent-not-ready
          value: 'true'
      taints:
        - effect: NoSchedule
          key: node-group
          value: nodepool-1
```
We also use this helm template in our helm chart
```yaml
{{- if .Values.karpenterNodePools }}
{{-   range .Values.karpenterNodePools }}
{{-     $namespace := $.Release.Namespace }}
{{-     $apiVersion := .apiVersion }}
{{-     if not $apiVersion }}
{{-         $apiVersion = "karpenter.sh/v1beta1" }}
{{-     end }}
{{-     $name := .name }}
{{-     $spec := .spec }}
---
apiVersion: {{ $apiVersion }}
kind: NodePool
metadata:
  name: {{ $namespace }}-{{ $name }}
spec:
{{-      if $spec }}
  {{- toYaml .spec | nindent 2 }}
{{-      end }}
...
{{-   end }}
{{- end }}
```
and this `config.yaml`
```yaml
karpenterNodePools:
  - name: nodepool-1
    apiVersion: karpenter.sh/v1
    spec:
      template:
        metadata:
          labels:
            node-group: nodepool-1
        spec:
          nodeClassRef:
            name: generic
            kind: EC2NodeClass
            group: karpenter.k8s.aws
          startupTaints:
            - key: node.cilium.io/agent-not-ready
              value: "true"
              effect: NoExecute
          taints:
            - key: node-group
              effect: NoSchedule
              value: nodepool-1
          requirements:
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["on-demand"]
            - key: karpenter.k8s.aws/instance-family
              operator: In
              values: ["r6a"]
            - key: karpenter.k8s.aws/instance-memory
              operator: In
              values: ["4096"]
      limits:
        memory: 192Gi
```
As soon as we try to start synchronization, the application freezes with an error
```bash
ComparisonError: Failed to load target state: failed to generate manifest for source 2 of 2: rpc error: code = FailedPrecondition desc = Failed to unmarshal "config.yaml": <nil>
```
Experimentally, we found out that reading `config.yml` starts to break as soon as we add these two parameters.
```yaml
            kind: EC2NodeClass
            group: karpenter.k8s.aws
```
If we remove them, the application starts to work correctly.
We also tried to reproduce the problem directly by running the `helm template` with this `config.yaml` and our diagram for argo-cd, but we were unable to reproduce this problem.

**To Reproduce**

1. Make helm chart with the following template
```yaml
{{- if .Values.karpenterNodePools }}
{{-   range .Values.karpenterNodePools }}
{{-     $namespace := $.Release.Namespace }}
{{-     $apiVersion := .apiVersion }}
{{-     if not $apiVersion }}
{{-         $apiVersion = "karpenter.sh/v1beta1" }}
{{-     end }}
{{-     $name := .name }}
{{-     $spec := .spec }}
---
apiVersion: {{ $apiVersion }}
kind: NodePool
metadata:
  name: {{ $namespace }}-{{ $name }}
spec:
{{-      if $spec }}
  {{- toYaml .spec | nindent 2 }}
{{-      end }}
...
{{-   end }}
{{- end }}
```
2. Make config.yaml with the following content
```yaml
karpenterNodePools:
  - name: nodepool-1
    apiVersion: karpenter.sh/v1
    spec:
      template:
        metadata:
          labels:
            node-group: nodepool-1
        spec:
          nodeClassRef:
            name: generic
            kind: EC2NodeClass
            group: karpenter.k8s.aws
          startupTaints:
            - key: node.cilium.io/agent-not-ready
              value: "true"
              effect: NoExecute
          taints:
            - key: node-group
              effect: NoSchedule
              value: nodepool-1
          requirements:
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["on-demand"]
            - key: karpenter.k8s.aws/instance-family
              operator: In
              values: ["r6a"]
            - key: karpenter.k8s.aws/instance-memory
              operator: In
              values: ["4096"]
      limits:
        memory: 192Gi
```
3. Add the application to argo-cd
4. Start synchronization

**Expected behavior**
Argo-CD should correctly process the following `config.yaml` file
```yaml
karpenterNodePools:
  - name: nodepool-1
    apiVersion: karpenter.sh/v1
    spec:
      template:
        metadata:
          labels:
            node-group: nodepool-1
        spec:
          nodeClassRef:
            name: generic
            kind: EC2NodeClass
            group: karpenter.k8s.aws
          startupTaints:
            - key: node.cilium.io/agent-not-ready
              value: "true"
              effect: NoExecute
          taints:
            - key: node-group
              effect: NoSchedule
              value: nodepool-1
          requirements:
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["on-demand"]
            - key: karpenter.k8s.aws/instance-family
              operator: In
              values: ["r6a"]
            - key: karpenter.k8s.aws/instance-memory
              operator: In
              values: ["4096"]
      limits:
        memory: 192Gi
```

**Screenshots**
<img width="1424" alt="Image" src="https://github.com/user-attachments/assets/12ede72d-e297-4a52-9b4e-7561572a1b0c" />
<img width="1547" alt="Image" src="https://github.com/user-attachments/assets/b85deab7-a19e-4141-8c99-058026e58d52" />

**Version**

```shell
argocd: v2.14.1+3345d05
  BuildDate: 2025-02-03T21:23:31Z
  GitCommit: 3345d05a43d8edd7ec42ec71ffe8b5f95bc68dbe
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2025-02-21T13:44:42Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal \"config.yaml\": <nil>" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2025-02-21T13:44:42Z" grpc.time_ms=13.638 span.kind=server system=grpc
```

**Comment by crenshaw-dev** [comment]
Can you post your Application manifest?

**Comment by rumstead** [comment]
This feels semi-similar to https://github.com/argoproj/argo-cd/issues/11001. 

IIRC, the code tries to be smart and looks to see if the yaml/json contains "apiVersion,kind,metadata" and if it does, it treats the yaml as a Kubernetes resource.

**Comment by obervinov** [comment]
@rumstead hello! Thanks for the reply.
Could you tell me more about IIRC? What is it and for what purpose?
We have a case again where we can't use `config.yaml` is a little more complicated than a simple structure
```yaml
global:
   parameter: value
```
We can easily install the helm chart with this `config.yml` manually, but as soon as it comes to adding this `config.yaml` ArgoCD breaks down again.  This makes the system unsuitable for global use in our case.

Additional example config.yaml
```yaml
limits:
  main:
    Container:
      defaultRequest:
        memory: 128Mi
      default:
        memory: 256Mi
    PersistentVolumeClaim:
      min:
        storage: 1Gi
      max:
        storage: 100Gi

quotas:
  main:
    hard:
      limits.memory: 384Gi
      requests.memory: 384Gi
    scopeSelector:
      matchExpressions:
        - operator : In
          scopeName: PriorityClass
          values: ["compute"]

resourceQuota:
  storageResources:
    ebs-gp3-delete: 100Gi

allowedServiceTypes:
  - ClusterIP

allowedHostnames:
  - example.com

karpenterNodePools:
  ec2NodeClassDefault:
    tags:
      "bg:owner": "obervinov@example.com"
      "bg:environment": "dev"
      "bg:application": "app1"
      "bg:project-id": "APP123"
      "bg:jira-ref": "APP-123"
    kubelet:
      maxPods: 1000
    amiFamily: AL2023
    amiSelectorTerms:
      - alias: al2023@latest
    subnetSelectorTerms:
      - tags:
          Name: us-east-1a
      - tags:
          Name: us-east-1a
    securityGroupSelectorTerms:
      - tags:
          Name: eks-node
    role: eks-karpenter-node
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 50Gi
          volumeType: gp3
          encrypted: true
          deleteOnTermination: true
    userData: |
      MIME-Version: 1.0
      Content-Type: multipart/mixed; boundary="//"

      --//
      Content-Type: application/node.eks.aws

      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        kubelet:
          flags:
            - --max-pods=1000
          config:
            kind: KubeletConfiguration
            apiVersion: kubelet.config.k8s.io/v1
            shutdownGracePeriod: 30s
            shutdownGracePeriodCriticalPods: 15s
        containerd:
          config: |
            [plugins."io.containerd.grpc.v1.cri"]
            max_concurrent_downloads = 250

            [plugins."io.containerd.grpc.v1.cri".registry]
            config_path = "/etc/containerd/certs.d"

            [stream_processors."io.containerd.processor.v1.pigz"]
            accepts = ["application/vnd.docker.image.rootfs.diff.tar.gzip"]
            returns = "application/vnd.oci.image.layer.v1.tar"
            path = "unpigz"
            args = ["-d", "-c"]


      --//
      Content-Type: text/cloud-config

      ca_certs:
        trusted:
          - |
            -----BEGIN CERTIFICATE-----
            ***
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            ***
            -----END CERTIFICATE-----
            
      write_files:
        - path: /etc/containerd/certs.d/docker.io/hosts.toml
          content: |
            [host."https://mirror.example.com:443"]
              capabilities = ["pull", "resolve"]

      --//

  nodePools:
    - app1:
        template:
          metadata:
            labels:
              node-group: app1
          spec:
            startupTaints:
              - effect: NoExecute
                key: node.cilium.io/agent-not-ready
                value: 'true'
            taints:
              - effect: NoSchedule
                key: node-group
                value: app1
            requirements:
              - key: karpenter.sh/capacity-type
                operator: In
                values: ["on-demand"]
              - key: karpenter.k8s.aws/instance-family
                operator: In
                values: ["r6a"]
              - key: karpenter.k8s.aws/instance-size
                operator: In
                values: ["large"]
        limits:
          memory: 384Gi
        disruption:
          consolidationPolicy: WhenEmpty
          consolidateAfter: 10s
```
