### ISSUE TITLE
Progressive Sync: Allow temporarly disabling sync for specific applications

### ISSUE THREAD

**Issue by purkhusid** [argoproj/argo-cd#22001]
# Summary

When using Auto Sync it is possible to disable the Auto Sync using `ignoreApplicationDifferences` property on the `ApplicationSet`

When using Progressive Syncs there is no way to disable the sync of apps since there is no property on the `Application` that controls whether to sync the app.

I tried using a label so that all `Application` with the label `sync=false` would be excluded from the Progressive Sync but that does not work since Progressive Sync ignores any manual changes to the labels and instead uses the desired state of the Application as the baseline for if the application should be included in the sync.

Example `ApplicationSet` snippet:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployments
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
  # Ignore the sync label so that the label can be manually added to the application to disable Progressive Sync
  ignoreApplicationDifferences:
    - jsonPointers:
        - /metadata/labels/sync
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: env
              operator: In
              values:
                - dev
            - key: sync
              operator: NotIn
              values:
                - "false"
          maxUpdate: 100%
        - matchExpressions:
            - key: env
              operator: In
              values:
                - prod
            - key: sync
              operator: NotIn
              values:
                - "false"
          maxUpdate: 100%
.....

```

# Motivation
Being able to manually update deployments if needed

# Proposal

Either respect the `ignoreApplicationDifferences` when evaluating if an `Application` should be included in the sync or add a property to `Application` that allows disabling Progressive Sync

**Comment by crenshaw-dev** [comment]
I can't remember whether progressive syncs respects sync windows. If not, it probably should, and that would be one way to accomplish this.

**Comment by purkhusid** [comment]
> I can't remember whether progressive syncs respects sync windows. If not, it probably should, and that would be one way to accomplish this.

Wouldn't sync windows block the progressive sync from progressing? I guess I'm asking for a way to temporarily remove an application from the progressive rollout

**Comment by andrey-parkhomets** [comment]
In my setup I relay on application config (yaml/json) which has attribute: `syncOrder` - that I made responsible on subject control. I.e. my applicationSet doesn't keep hardcoded application names and sync orders, instead has list of necessary steps 5..10 - should be enough in most cases . The value "0" or other outside of my range - imply: "do not sync it".
```
  strategy:
    rollingSync:
      steps:
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '1'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '2'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '3'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '4'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '5'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '6'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '7'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: In
              values:
                - '8'
          maxUpdate: 100%
        - matchExpressions:
            - key: syncOrder
              operator: NotIn
              values:
                - '1'
                - '2'
                - '3'
                - '4'
                - '5'
                - '6'
                - '7'
                - '8'
          maxUpdate: 0%
    type: RollingSync
```
