### ISSUE TITLE
targetBranchMatch filter does not work with pullRequest generator for Bitbucket Cloud

### ISSUE THREAD

**Issue by hartmanfrost** [argoproj/argo-cd#22005]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Adding `targetBranchMatch` filter on generator for Azure DevOps pull request produces zero apps output

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: feature
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        requeueAfterSeconds: 60
        bitbucket:
          owner: owner
          repo: repo
          api: https://api.bitbucket.org/2.0
          bearerToken:
            tokenRef:
              secretName: bitbucket-bearer-token
              key: token
        filters:
          - targetBranchMatch: "develop"
```

**Expected behavior**

ApplicationSet generates apps for pull requests with matched target branch

**Version**

```shell
argocd: v2.14.2+ad27246
  BuildDate: 2025-02-06T02:19:55Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.6
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.14.2+ad27246
  BuildDate: 2025-02-05T23:44:17Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```
