### ISSUE TITLE
InitContainers from Templates Not Listed in ArgoCD Front-End Menu

### ISSUE THREAD

**Issue by MaxClercEricsson** [argoproj/argo-cd#22027]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In ArgoCD's front-end interface, initContainers originating from a template are not listed in the menu. However, users can still access their logs by using the search field near the log fields button. By manually entering the initContainer name, logs appear as expected.

That bug did not appear if the iniContainers is directly in the step (without template)

**To Reproduce**

Deploy an application using ArgoCD with initContainer definitions sourced from a template.

Navigate to the application's details in the ArgoCD UI.

Open the initContainer menu and check the listed initContainers.

Observe that initContainers originating from a template are missing from the menu.

Use the search field near the log fields button and enter the initContainer name manually.

Observe that logs for the missing initContainer are retrievable.

**Expected behavior**

All initContainers, including those originating from templates, should be listed in the front-end initContainer menu for easy access.

**Screenshots**
A container name "setup" should be parts of the list
![Image](https://github.com/user-attachments/assets/46565edd-1a49-49e4-b0cb-a2056e2bae79)

**Version**

```shell
v3.6.0-rc4
```

**Logs**

Pipline and template use to reproduce the bug : 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: init-template
spec:
  templates:
    - name: test-init
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: "alpine"
        command:
          - sh
          - -xc
        args:
          - |
            echo "Hello world! from the template"
            ls # Listing all files in the mounted workspace
        workingDir: /mountdir/
        resources: {}
        volumeMounts:
          - name: workdir
            mountPath: /mountdir
      initContainers:
        - name: setup
          image: "alpine"
          command:
            - sh
            - -c
          args:
            - |
              echo "Here is output from InitContainer in the template"
          workingDir: /mountdir/
          resources: {}
          mirrorVolumeMounts: true
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-using-template
spec:
  entrypoint: call-template
  templates:
    - name: call-template
      steps:
        - - name: use-init-template
            templateRef:
              name: init-template
              template: test-init
```
