### ISSUE TITLE
Git files generator does not populate parameters from the file inside nested matrix generator

### ISSUE THREAD

**Issue by dedri-github** [argoproj/argo-cd#22051]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When creating an ApplicationSet with a matrix generator that has a some generators inside, the parameters which are populated from within the first generator are not accessible in the second generator within the matrix generator if those generators reside in a nested matrix generator. If the matrix generator is not nested, the parameters of the first generator are available for use by the second generator as documented.

**To Reproduce**
The following does not work:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: not-working
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:  # this one is not relevant for the bug showcase - it's only here because a matrix generator must have exactly two children.
              elements:
                - dummy: a
          - matrix:
              generators:
              - git:
                    repoURL: 'https://some-git-server/some-repo.git'
                    revision: "some-revision"
                    gitParamPrefix: test
                    files:
                      - path: "deployments/config.yaml"
              - list:
                  elementsYaml: "{{ .apps.myapp | toJson }}"
  template:
    metadata:
      name: "myapp-{{ .namespace }}"
    spec:
      project: "infra"
      sources:
        - repoURL: "https://some-git-server/some-other-repo.git"
          targetRevision: 'some-tag'
          ref: values
      destination:
        server: 'some-server'
        namespace: '{{.namespace}}'
```
Assuming the following configuration file `deployments/config.yaml` in `some-repo` within the `some-revision` branch:
```
apps:
  myapp:
  - chartVersion: 1.2.4
    namespace: ns1
  - chartVersion: 1.2.7
    namespace: ns2
```

With the following error:
```
$  argocd --grpc-web appset create --dry-run notworking-applicationset.yaml -o yaml
FATA[0000] rpc error: code = Unknown desc = unable to generate Applications of ApplicationSet: error generating applications: failed to get params for second generator in the matrix generator: child generator returned an error on parameter generation: failed to replace parameters in generator: failed to execute go template {{ .apps.myapp | toJson }}: template: :1:8: executing "" at <.apps.myapp>: map has no entry for key "apps"
```

However, when using the same applicationset however with one level of nesting on the matrix generator, is works as expected:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: working
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
            repoURL: 'https://some-git-server/some-repo.git'
            revision: "some-revision"
            gitParamPrefix: test
            files:
              - path: "deployments/config.yaml"
      - list:
          elementsYaml: "{{ .apps.myapp | toJson }}"
  template:
    metadata:
      name: "myapp-{{ .namespace }}"
    spec:
      project: "infra"
      sources:
        - repoURL: "https://some-git-server/some-other-repo.git"
          targetRevision: 'some-tag'
          ref: values
      destination:
        server: 'some-server'
        namespace: '{{.namespace}}'
```

Output:
```
...
status:
  resources:
  - health: {}
    name: myapp-ns1
    namespace: argocd
  - health: {}
    name: myapp-ns2
    namespace: argocd
```

**Further debugging**
To show what happens, please note the following simplified example that doesn't use the git generator, however has a modified ApplicationSet that "prints" all the parameters that the second generator can see. "Printing" is done by writing the contents in the Application name so it would be visible for debugging purposes:
First, with the **non-working** applicationset (nested):
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acs-test
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - dummy: a
          - matrix:
              generators:
              - list:
                  elements:
                  - my-key: my-value
              - list:
                  elements:
                  - a: "{{ . }}"

  template:
    metadata:
      name: "{{.a | toJson }}"
    spec:
      project: "infra"
      sources:
        - repoURL: "https://repo.git"
          targetRevision: 'revision'
          ref: values
      destination:
        server: 'some-server'
        namespace: 'some-namespace'
```
This gives the following output (please note that we cannot see the `my-key` parameter but only the dummy one from outside):
```
...
status:
  resources:
  - health: {}
    name: '"map[dummy:a]"'
    namespace: argocd
```

Second, with the working debugging example (with a non-nested applicationset):
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acs-test
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - my-key: my-value
      - list:
          elements:
          - a: "{{ . }}"

  template:
    metadata:
      name: "{{.a | toJson }}"
    spec:
      project: "infra"
      sources:
        - repoURL: "https://repo.git"
          targetRevision: 'revision'
          ref: values
      destination:
        server: 'some-server'
        namespace: 'some-namespace'
```

This gives the following output (and here we can see my-key):
```
...
status:
  resources:
  - health: {}
    name: '"map[my-key:my-value]"'
    namespace: argocd
```

**Expected behavior**

Both cases (nested and non-nested) should find the parameters of the first generator when querying for them in the second generator.

**Screenshots**
N/A

**Version**

```shell
argocd: v2.14.2+ad27246
  BuildDate: 2025-02-06T02:20:43Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.6
  Compiler: gc
  Platform: darwin/arm64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.13.2+dc43124
  BuildDate: 2024-12-11T18:37:15Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**
N/A

**Comment by andrii-korotkov-verkada** [comment]
I think matrixes of matrixes is not a supported pattern.

**Comment by dedri-github** [comment]
> I think matrixes of matrixes is not a supported pattern.

The 4th restriction in [the documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/#restrictions) states that nesting once is supported.

**Comment by Sturgelose** [comment]
I've been investigating this a bit as it also bit me.

Given the examples you wrote, (and simplifying it a bit into names)
```yaml
Matrix:
- List 1
- Matrix2:
  - List 2
  - List 3 (reference to Previous step)
```

The current logic in the code is:

1. Process List1
   1. Update State with List 1
2. Process Matrix 2
   1. Interpolate List2 and List3 with current state -> Issue, it replaces reference in list 3 with list 1
   2. Generate List2 and List3 into state

**As a workaround I have found that using `{{ \"{{ . }}\" }}` instead of `{{ . }}` allows to interpolate in 2.1 but still be able to interpolate again.**

I tried to do a fix in the argocd code, which would be more elegant and improve the UX, but the code is kinda hardcoded to enforce a map of data when templating with gotemplate.

The solution I see is to set the `params map[string]any` to `params any`, so we can override `InterpolateGenerator` with something like...

```golang
	if requestedGenerator.Matrix != nil {
		// If there is a second child of matrix type, first replace `{{ . }}` with `{{ {{ . }} }}` so it doesn't replace with parent matrix's state

		p := "{{ . }}"

		interpolatedGenerator, err := render.RenderNestedGeneratorParams(&requestedGenerator.Matrix.Generators[1], p, useGoTemplate, goTemplateOptions)
		if err != nil {
			log.WithError(err).WithField("interpolatedGenerator", interpolatedGenerator).Error("error interpolating generator with other generator's parameter")
			return argoprojiov1alpha1.ApplicationSetGenerator{}, err
		}
	}
```

... So this way we can pass a simple string "{{.}}" to the templating. But this could be breaking if there is anything else to replace or trying to access an attribute...

Mostly we want a logic such as "if the second nested generator is a matrix, template everything but the `{{ . }}` of the second child....
