### ISSUE TITLE
Intermittent rollback failure from UI in v2.14.2 where specifying destination.server with  "Unable to rollback application: application destination spec for x is invalid"

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#22077]
### Discussed in https://github.com/argoproj/argo-cd/discussions/22050

<div type='discussions-op-text'>

<sup>Originally posted by **TazUk** February 27, 2025</sup>
This seems to be an intermittent problem so I've not been able to determine steps to consistently reproduce (and therefore haven't raised it as an issue at this point).

**Configuration:**
cluster is configured as:
name: in-cluster
url: https://kubernetes.default.svc

Standard application manifest example:
```
project: my-project
source:
  repoURL: >-
    https://gitlab.com/my-group/my-project/foo.git
  path: deployment/helm/
  targetRevision: master
  helm:
    parameters:
      - name: foo.image.tag
        value: 1.3.0
destination:
  server: 'https://kubernetes.default.svc'
  namespace: my-namespace
syncPolicy:
  automated: {}
```

**Observed behaviour when issue occurs:**
1. In UI user opens the history & rollback pane, selects the desired version and "rollback"
2. Warning message to disable AutoSync
3. User confirms
4. Error displayed: 
```Unable to rollback application: application destination spec for foo is invalid: application destination can't have both name and server defined: in-cluster https://kubernetes.default.svc```

Opening the application manifest in the UI after receiving this message reveals that the destination.name has been added to the existing manifest, i.e. manifest shows :
```
<snip>
destination:
  server: 'https://kubernetes.default.svc'
  namespace: my-namespace
  name: in-cluster
<snip>
```
Observing the manifest for a few minutes one can see the `name: in-cluster` get removed.
Once this has occurred, repeating steps 1 to 3 above allows rollback to continue without issue.

</div>
