### ISSUE TITLE
Argocd argocd-repo-server Failed to initialize git repo: stat /tmp/_argocd-repo/xxx : permission denied

### ISSUE THREAD

**Issue by cdtzabra** [argoproj/argo-cd#22088]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

Recurring error with argocd-repo-server: permission denied.

We have an applicationset that hinders apps.
Dev apps are in auto sync.

However, for some time now, we've been getting the `failed to initialize repository resources: rpc error: code = Internal desc = Failed to initialize git repo: stat /tmp/_argocd-repo/0b441887-c8fd-4515-9cfd-dd46178c5f3e: permission denied` on applications at sync time` in popup and this one `Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Failed to initialize repository resources: rpc error: code = Internal desc = Failed to initialize git repo: stat <path to cached source> permission denied` 

In rare cases, the sync is done despite the error and in all other cases a manual intervention “invalid cluster cache” or even restart compelment pods `argocd-repo-server` and it becomes very painful.

**Expected behavior**

refresh/sync is successful every time without intermittent denied permission errors

**Screenshots**

![Image](https://github.com/user-attachments/assets/6d744332-2b43-4ae7-a871-f70d9525c6d2)

![Image](https://github.com/user-attachments/assets/5acd882b-4ad0-4f0a-940d-2ce51765b6bc)

**Version**

```shell
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T09:27:36Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.11.7+e4a0246
  BuildDate: 2024-07-24T09:33:49Z
  GitCommit: e4a0246c4d920bc1e5ee5f9048a99eca7e1d53cb
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

```
Unable to load data: error acquiring repo lock: failed to initialize repository resources: rpc error: code = Internal desc = Failed to initialize git repo: stat /tmp/_argocd-repo/0b441887-c8fd-4515-9cfd-dd46178c5f3e: permission denied
```
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to initialize repository resources: rpc error: code = Internal desc = Failed to initialize git repo: stat <path to cached source> permission denied
```

```
time="2025-02-28T15:16:40Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://gitlab/xxx/xxx/nginx,TargetRevision:dev,Helm:nil,Kustomize:nil,Directory:nil,Plugin:&ApplicationSourcePlugin{Name:avp-helm,Env:[]*EnvEntry{&EnvEntry{Name:HELM_ARGS,Value:-f ../app-values.yaml -f ../infra-values.yaml,},&EnvEntry{Name:RELEASE_NAME,Value:yzx-xx0,},},Parameters:[]ApplicationSourcePluginParameter{},},Chart:,Ref:,}/18c3ca5aa82ce8fa187f2a689cdd25930b1399ba"
time="2025-02-28T15:16:40Z" level=error msg="finished unary call with code Unknown" error="failed to initialize repository resources: rpc error: code = Internal desc = Failed to initialize git repo: stat <path to cached source> permission denied" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2025-02-28T15:16:40Z" grpc.time_ms=8.678 span.kind=server system=grpc
```

**Comment by cdtzabra** [comment]
I have avp-plugin configured

App manifest example

```yaml
project: xxx-dev
source:
  repoURL: 'https://gitlab/xxx/xxx/app.git'
  path: xxx/nginx
  targetRevision: dev
  plugin:
    name: avp-helm
    env:
      - name: HELM_ARGS
        value: '-f ../app-values.yaml -f ../infra-values.yaml'
      - name: RELEASE_NAME
        value: yxz-xxx
destination:
  server: 'https://kubernetes.default.svc'
  namespace: a1323-dev
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
```
