### ISSUE TITLE
App -> Details -> Parameters UI page crashed on app with hydration enabled.

### ISSUE THREAD

**Issue by daftping** [argoproj/argo-cd#22097]
**Describe the bug**
App -> Details -> Parameters UI page crashed on app with hydration enabled.

**To Reproduce**

Create an App

```yaml
project: default
destination:
  server: https://api.company.net
  namespace: dev-foo
sourceHydrator:
  drySource:
    repoURL: https://github.com/user/repo.git
    targetRevision: master
    path: helm-guestbook
  syncSource:
    targetBranch: environments/dev
    path: helm-guestbook
  hydrateTo:
    targetBranch: environments/dev-next
```

Click on the App -> "Details" -> "Parameters"
```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

TypeError: Cannot read properties of null (reading 'type')
    at M_ (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:1521320)
    at Object.children (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:1519562)
    at Ir.render (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:1290002)
    at Bi (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:581369)
    at zi (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:581165)
    at Es (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:616701)
    at Sl (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:608184)
    at xl (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:608109)
    at hl (https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:605142)
    at https://argocd.company.com/main.67d3d35d60308e91d5f4.js:2:556862
```

**Version**
v2.14.3+71fd4e5

**Comment by crenshaw-dev** [comment]
The parameters tab is odd for the hydrator... there's not a whole lot to parameterize right now. But probably just needs a null check, I'll look into it. 

Out of curiosity, what's your use case for the hydrator? Just tinkering or using it for something more?

**Comment by daftping** [comment]
> The parameters tab is odd for the hydrator... there's not a whole lot to parameterize right now. But probably just needs a null check, I'll look into it.
> 
> Out of curiosity, what's your use case for the hydrator? Just tinkering or using it for something more?

We use a rendered manifests pattern for all our Kubernetes deployments. We’ve built an opinionated standalone CLI to hydrate Helm charts, and Argo CD points to the directory with the hydrated manifests instead of deploying the Helm chart directly.

The native Argo CD hydration looks amazing, and eliminating the manual step of rendering manifests would significantly enhance the developer experience.

I’m evaluating the feasibility of replacing our internal tooling with Argo CD’s native capabilities.

Most of our applications follow this structure:
```
  sources:
    - repoURL: https://artifactory.company.com/artifactory/helm
      targetRevision: 1.1.1
      helm:
        valueFiles:
          - $values/values.yaml
      chart: app
    - repoURL: git@github.com:user/repo.git
      targetRevision: HEAD
      ref: values
```

The central team publishes Helm charts to Artifactory, while individual teams maintain their values files along with hydrated manifests in their own repositories.

@crenshaw-dev  Is this scenario planned to be supported in the future?
