### ISSUE TITLE
UI editor for manifests shows extra new lines for list items

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#22099]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There are extra newlines after each -
```
      volumeMounts:
        -
          mountPath: /app/config
          name: config
        -
          mountPath: /app/common-config
          name: common-config
        -
          mountPath: /app/data
          name: data
        -
          mountPath: /tmp
          name: tmp-tmpfs
```
This makes it not look like regular Yaml and might be breaking live editing in the UI, since newlines still show up after entering the edit mode.

**To Reproduce**

Just open the live manifest of some pod

**Expected behavior**

The - and test are on the same line

**Screenshots**

![Image](https://github.com/user-attachments/assets/1da23fdb-f6da-4dbf-844e-9db8970c8529)

**Version**

Master build from 2025/02/28

**Logs**

**Comment by andrii-korotkov-verkada** [comment]
@aali309, seems related to https://github.com/argoproj/argo-cd/commit/55f8a434d06ee335b195783a0a83c6a7c8dd3078. 
The issue is I can't properly live edit anymore I think, since the format is preserved and I'm afraid saving the object can save this layout.

**Comment by andrii-korotkov-verkada** [comment]
cc @jsoref, @keithchong

**Comment by jsoref** [comment]
Does it actually fall to save?

**Comment by andrii-korotkov-verkada** [comment]
I disagree, the experience has been quite non-intuitive. I was scared to save and also there are edge cases like what if new-line gets deleted.

**Comment by andrii-korotkov-verkada** [comment]
I'll discuss on the contributors meeting to see what consensus would be.

**Comment by andrii-korotkov-verkada** [comment]
I just think that everybody who's new to this feature would have similar questions to me, e.g. "Would it save a properly formatted object?", "Why is it not like Yaml format?", which I think is a sign we should make it better.

**Comment by jsoref** [comment]
Have you tried saving yet? Does it actually work?

I'm not opposed to improving the experience.

**Comment by andrii-korotkov-verkada** [comment]
![Image](https://github.com/user-attachments/assets/a0ca1cd2-9594-4167-a307-28ea219ff655)

**Comment by andrii-korotkov-verkada** [comment]
(the config was used for testing, so don't pick on rate limit values pls)

**Comment by andrii-korotkov-verkada** [comment]
We probably have to revert the change for now. What do you think?

**Comment by jsoref** [comment]
Looking unusual is *not* the same as actually *being* malformed.

**Comment by andrii-korotkov-verkada** [comment]
I mean, look at results from kubectl get
```
          for_callers:
          -
            any_caller: 1000001/min
            key: ip_address
            overrides:
              127.0.0.1: 500000/min
          -
            any_caller: 500000/min
            key: service_identity
            overrides:
              vprovision: 700000/min
```
Is it a correct yaml?

**Comment by andrii-korotkov-verkada** [comment]
That's not from Argo CD UI, where I'd expect this with this feature.

**Comment by keithchong** [comment]
I merged the revert change for now.  

I looked at parsing YAML to JSON to verify the validity

```
Employees:
  - name: Joe
    date: 11/27/2001
  - name: John
    date: 11/26/2005
```

The above in JSON is:

```
{
  "Employees": [
    {
      "date": "11/27/2001", 
      "name": "Joe"
    }, 
    {
      "date": "11/26/2005", 
      "name": "John"
    }
  ]
}
```

The following YAML, with the hyphen on its own line, has the same JSON equivalent:

```
Employees:
  - 
    name: Joe
    date: 11/27/2001
  - 
    name: John
    date: 11/26/2005
```

Similarly, for this too:

```
Employees:
- 
  name: Joe
  date: 11/27/2001
- 
  name: John
  date: 11/26/2005
```

I was discussing with @aali309 that perhaps there's another way to implement the collapse capability, without changing the original format of the YAML.  Perhaps we need to look at the YAML editor itself.  There's a tradeoff here between changing the YAML format from what the user has or what the user is used to, and having the expand/collapse capability.

**Comment by andrii-korotkov-verkada** [comment]
TIL that
```
Employees:
  - 
    name: Joe
    date: 11/27/2001
  - 
    name: John
    date: 11/26/2005
```
is actually a valid Yaml.

Thanks for your help overall.
