### ISSUE TITLE
Installing envoy gateway via helm chart using ArgoCD: Error 401 when pulling image

### ISSUE THREAD

**Issue by GeroL** [argoproj/argo-cd#22100]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello,

i could not figure out how to install the envoy-gateway application when using ArgoCD.
Does anybody successfully used this combination? 
I keep all my helm charts in a git repository. ArgoCD always keeps telling me error 401.
I tried using as a helm chart dependency and directly as an application source

I have the following resources:

```
apiVersion: argoproj.io/v1alpha1
metadata: 
  name: envoy-gateway-app
  namespace: argocd-apps
kind: Application
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway
  source:
    repoURL: registry-1.docker.io/envoyproxy/gateway-helm
    targetRevision: ">=1.3.0"
    chart: envoy-gateway 
    # helm: 
    #   passCredentials: true

  syncPolicy:
    # automated:
    #   selfHeal: true
    #   prune: true
    #   allowEmpty: true
    syncOptions:
      - CreateNamespace=true
```
```
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: envoy-gateway-repo
  namespace: argocd
stringData:
  url:  registry-1.docker.io/envoyproxy/gateway-helm #registry-1.docker.io/bitnamicharts
  name: envoy-gateway
  type: helm
  enableOCI: "true"
```
```
apiVersion: v2
name: envoy-gateway
type: application
version: 1.0.1
appVersion: "1.0.1"
dependencies:
  - name: eg
    version: "=1.3.0"
    repository: oci://registry-1.docker.io/envoyproxy/gateway-helm
```

**Expected behavior**

Like normal helm chart

**Version**

```shell
v2.14.3+71fd4e5
```

**Logs**

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = unable to get tags: failed to get tags: GET "https://registry-1.docker.io/v2/envoyproxy/gateway-helm/envoy-gateway/tags/list": response status code 401: unauthorized: authentication required: [map[Action:pull Class: Name:envoyproxy/gateway-helm/envoy-gateway Type:repository]]
```
