### ISSUE TITLE
argocd gitlab pullRequest generator: unable to render envs

### ISSUE THREAD

**Issue by maaaax92** [argoproj/argo-cd#22103]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

applicationset gitlab pullrequest generator unable to parse any envs like {{.numbers}} or {{.branch}}
looked this article https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/
for example if I switch .spec.template.metadata.name to base string without envs like `myapp-feature-1234` - it works fine but if I use this construction `name: 'myapp-feature-{{.number}}` - the applicationset goes to **OutOfSync** state

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-feature
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        gitlab:
          project: "1111"
          api: https://gitlab.corp.local
          tokenRef:
            secretName: gitlab-token
            key: token
          pullRequestState: opened
        requeueAfterSeconds: 600
  template:
    metadata:
      name: 'myapp-feature-{{.number}}'
```

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd version 2.4.13
```

**Logs**

```
Paste any relevant application logs here.
```
