### ISSUE TITLE
AKS Workload Identity not working in v2.14.3

### ISSUE THREAD

**Issue by andersro93** [argoproj/argo-cd#22122]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
It seems that when Argo CD was upgraded to v2.14.3 it was no longer able to sign in with Workload Identity on AKS. argocd-k8s-auth failed with exit code 20 was the message that was received. This worked on the previous versions of Argo CD with the exact same config on v2.14.2.

**To Reproduce**
Deploy a kubernetes cluster on AKS with Argo CD v2.14.3 and another kubernetes cluster where the identity used in Argo CD have permissions to manage the cluster.

Cluster Secret:
```yaml
"apiVersion": "v1"
"kind": "Secret"
"metadata":
  "labels":
    "argocd.argoproj.io/secret-type": "cluster"
  "name": "weu-test-kubernetes-primary-aks-cluster-secret"
"stringData":
  "config": "{\"execProviderConfig\":{\"apiVersion\":\"client.authentication.k8s.io/v1beta1\",\"args\":[\"azure\"],\"command\":\"argocd-k8s-auth\",\"env\":{\"AAD_ENVIRONMENT_NAME\":\"AzurePublicCloud\",\"AAD_LOGIN_METHOD\":\"workloadidentity\",\"AZURE_CLIENT_ID\":\"00000000-0000-0000-0000-000000000000\"}},\"tlsClientConfig\":{\"caData\":\"XXXXX\",\"insecure\":false}}"
  "name": "weu-test-kubernetes-primary-aks"
  "server": "https://azure-westeurope-primary-test-XXXXXXX.privatelink.westeurope.azmk8s.io"
"type": "Opaque"
```

**Expected behavior**
Argo CD to be able to connect to the cluster and sync/compare the manifests as usual

**Screenshots**
A screenshot showing the errors on one of the applications that targets a remote cluster managed by Argo CD. This was on Argo CD v2.14.3.
![Image](https://github.com/user-attachments/assets/ae5c057b-7e67-447f-bd89-366182d9f922)

This screenshot shows the clusters as working in v2.14.2:
![Image](https://github.com/user-attachments/assets/b8ed52c5-a410-4260-b68b-9f348caab1f8)

**Version**
v2.14.3

**Logs**
```
executable argocd-k8s-auth failed with exit code 20
```
