### ISSUE TITLE
SSO redirect url is incorrect if configured Argo CD URL has trailing slash

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2212]
**Describe the bug**
Argo CD generates SSO URL on the fly using configured external URL (`url` field in `argocd-cm`  config map).

**To Reproduce**
1. Configure SSO and using Google oauth and add trailing slash to `url` field:

example
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: http://localhost:4000/
  dex.config: |
    connectors:
    - config:
        clientID: <myclientid>
        clientSecret: <mysecret>
        issuer: https://accounts.google.com
      id: google
      name: Google
      type: oidc
```
2. Try to login
3. Login fails. 

**Expected behavior**
Login should be successful

**Logs**
Dex:
```
time="2019-08-23T16:46:36Z" level=error msg="Connector \"google\" returned error when creating callback: expected callback URL \"http://localhost:4000/api/dex/callback\" did not match the URL in the config \"http://localhost:4000//api/dex/callback\"
```
