### ISSUE TITLE
`App.status.health.LastTransitionTime` missing from Application Status

### ISSUE THREAD

**Issue by liranZiv27** [argoproj/argo-cd#22192]
`Checklist:`

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Missing field in Application status, causing the suggested trigger for [on-deployed template example](https://github.com/argoproj/argo-cd/blob/master/notifications_catalog/triggers/on-deployed.yaml) to fail to send.

Noticed this log warn message by Application-controller 
```
W0305 13:12:24.248939       7 warnings.go:70] unknown field "status.health.lastTransitionTime"
```

**To Reproduce**
1. Running ArgoCD instance with notifications-controller enabled.
2. on-deployed template + on-deployed trigger - [from here](https://github.com/argoproj/argo-cd/blob/master/notifications_catalog/triggers/on-deployed.yaml)
3. Application installed and set with on-deployed annotation `notifications.argoproj.io/subscribe.on-deployed.slack: "slack-channel"`
4. notifications-controller logs next message - 
```
level=error msg="failed to execute when condition: reflect: Call using interface {} as type string (1:139)\n | app.status.operationState != nil and app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and !time.Parse(app.status.health.lastTransitionTime).Add(1 * time.Minute).Before(time.Parse(app.status.operationState.finishedAt))
```

**Expected behavior**
Notification sent for an application deployment successfully.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
argocd: v2.14.4+3d901f2
  BuildDate: 2025-03-04T22:56:08Z
  GitCommit: 3d901f2037888af302a85f518bea70b33ee8e1c7
  GitTreeState: clean
  GoVersion: go1.24.0
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.14.2+ad27246
```

**Comment by liranZiv27** [comment]
Issue was created per @andrii-korotkov-verkada request.

**Comment by andrii-korotkov-verkada** [comment]
Did you recently upgrade from an earlier version? The last transition time was added in 2.14, so older apps may not have it. But once you deploy an app, it should get it.

**Comment by liranZiv27** [comment]
> Did you recently upgrade from an earlier version? The last transition time was added in 2.14, so older apps may not have it. But once you deploy an app, it should get it.

I have tried deploying after upgrading the version, no `lastTransitionTime` field in the Application status spec.

**Comment by andrii-korotkov-verkada** [comment]
Ah, when upgrading the app, did you upgrade the install manifest as well including the CRD with types definitions?

**Comment by liranZiv27** [comment]
Using a helm release - 7.8.8
https://artifacthub.io/packages/helm/argo/argo-cd

**Comment by svghadi** [comment]
Seems like Argo CD CRDs are not updated to latest during upgrade. Can you confirm if CRDs are updated on cluster?
```bash
$ kubectl get crd applications.argoproj.io -o yaml|grep LastTransitionTime
.......
                      description: LastTransitionTime is the time the condition was
                    description: LastTransitionTime is the time the HealthStatus was
                          description: LastTransitionTime is the time the HealthStatus
```


I created a Argo CD Application with 2.14.4 and could see the `LastTransitionTime` field in status.
```yaml
status:
....
  health:
    lastTransitionTime: "2025-03-06T11:37:53Z"
    status: Healthy
```

**Comment by liranZiv27** [comment]
```
          status:
            description: ApplicationStatus contains status information for the application
            properties:
              conditions:
                description: Conditions is a list of currently observed application
                  conditions
                items:
                  description: ApplicationCondition contains details about an application
                    condition, which is usually an error or warning
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the time the condition was
                        last observed
                      format: date-time
                      type: string
```

**Comment by svghadi** [comment]
There are multiple `lastTransitionTime` fields in the Application CRD. The one you shared is under `conditions`. There should be another under `health`. Can you confirm?

```
status:
            description: ApplicationStatus contains status information for the application
            properties:
              conditions:
                description: Conditions is a list of currently observed application
                  conditions
                items:
                  description: ApplicationCondition contains details about an application
                    condition, which is usually an error or warning
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the time the condition was
                        last observed
                      format: date-time
                      type: string
              .......
              .......
              health:
                description: Health contains information about the application's current
                  health status
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the time the HealthStatus was
                      set or updated
                    format: date-time
                    type: string
               ......
```
