### ISSUE TITLE
UI yaml editor leads to stacktrace

### ISSUE THREAD

**Issue by Clausinho** [argoproj/argo-cd#22199]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

the UI crashes into
```
Something went wrong!

Consider submitting an issue here.

Stacktrace:

M_@https://xxx/main.67d3d35d60308e91d5f4.js:2:1523149
k_@https://xxx/main.67d3d35d60308e91d5f4.js:2:1519247
Qa@https://xxx/main.67d3d35d60308e91d5f4.js:2:569442
Es@https://xxx/main.67d3d35d60308e91d5f4.js:2:615400
Sl@https://xxx/main.67d3d35d60308e91d5f4.js:2:608186
xl@https://xxx/main.67d3d35d60308e91d5f4.js:2:608109
hl@https://xxx/main.67d3d35d60308e91d5f4.js:2:605142
90495/Zo/<@https://xxx/main.67d3d35d60308e91d5f4.js:2:556862
14099/t.unstable_runWithPriority@https://xxx/main.67d3d35d60308e91d5f4.js:2:631967
qo@https://xxx/main.67d3d35d60308e91d5f4.js:2:556571
Zo@https://xxx/main.67d3d35d60308e91d5f4.js:2:556809
Jo@https://xxx/main.67d3d35d60308e91d5f4.js:2:556742
cl@https://xxx/main.67d3d35d60308e91d5f4.js:2:601912
enqueueSetState@https://xxx/main.67d3d35d60308e91d5f4.js:2:560525
42431/v.prototype.setState@https://xxx/main.67d3d35d60308e91d5f4.js:2:732154
t@https://xxx/main.67d3d35d60308e91d5f4.js:2:1290965
o@https://xxx/main.67d3d35d60308e91d5f4.js:2:1291086

```
**To Reproduce**

When you try to create an application and paste (replace xxx with environment specific values)
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxx
spec:
  destination:
    namespace: 'xxx'
    server: https://xxx:443
  source:
    path: helm/
    repoURL: https://git.xxx.xxx/xxx.git
    targetRevision: main
    helm:
      valueFiles: xxx/xxx/xxx/values.yaml
  project: xxx
```

**Expected behavior**

The UI errors out a human readable error. I assume it can't enumerate the valueFiles and expects:
```
    helm:
      valueFiles:
        - xxx/xxx/xxx/values.yaml
```

**Version**

I will try `argocd version` when I manage to login via `--sso`, I get the error from keycloak `Invalid parameter: redirect_uri` but I assume this is on keycloaks side.

This might suffice though, from the web ui:

```
{
    "Version": "v2.14.2+ad27246",
    "BuildDate": "2025-02-05T23:44:17Z",
    "GitCommit": "ad2724661b66ede607db9b5bd4c3c26491f5be67",
    "GitTreeState": "clean",
    "GoVersion": "go1.23.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.3 2024-07-19T16:40:33Z",
    "HelmVersion": "v3.16.3+gcfd0749",
    "KubectlVersion": "v0.31.0",
    "JsonnetVersion": "v0.20.0"
}
```
