### ISSUE TITLE
helm valuesObject does not work

### ISSUE THREAD

**Issue by babelfish** [argoproj/argo-cd#22234]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I was trying to add some values overrides to the [keda](https://github.com/kedacore/charts/tree/main/keda) helm chart. I tried to use `source.helm.valuesObject` which, according to the docs, seemed to be exactly what I needed, but after syncing the `Application` definition, the app still showed as fully in sync. It was not using the values I provided when rendering the chart's templates. I could see the values I provided shown in the Parameters tab of the app details, however it was still rendering the templates with the default values from the chart's values.yml.

When I switch it to use `source.helm.values` instead, it immediately worked.

**To Reproduce**

Create an `Application` that uses `source.helm.valuesObject` to try to pass values to a helm chart.

This does not work:

```yaml
source:
  repoURL: https://github.com/kedacore/charts
  path: keda
  targetRevision: v2.15.1
  helm:
    valuesObject:
      podIdentity:
        gcp:
          enabled: true
          gcpIAMServiceAccount: [redacted].iam.gserviceaccount.com
destination:
  server: https://kubernetes.default.svc
  namespace: keda
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

This does work:

```yaml
source:
  repoURL: https://github.com/kedacore/charts
  path: keda
  targetRevision: v2.15.1
  helm:
    values: |
      podIdentity:
        gcp:
          enabled: true
          gcpIAMServiceAccount: [redacted].iam.gserviceaccount.com
destination:
  server: https://kubernetes.default.svc
  namespace: keda
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

**Expected behavior**

Values provided via `source.helm.valuesObject` should work the same as via `source.helm.values`.

**Screenshots**

![Image](https://github.com/user-attachments/assets/ea38440a-19eb-44cd-bc8c-ae21027a758c)

![Image](https://github.com/user-attachments/assets/054ce7ec-d4ca-4833-8c93-6cd655afe3b1)

**Version**

```shell
argocd: v2.13.1+af54ef8
  BuildDate: 2024-11-20T15:58:16Z
  GitCommit: af54ef8db5adfa77a08d4d05b1318a2198084c22
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
```

Upgrading argo is outside of the scope of what I'm currently working on, so I can't test with the latest version, but I did look through the changelogs of more recent releases and didn't see any reference to this.

**Logs**

n/a

**Comment by nitishfy** [comment]
For me it worked, 

![Image](https://github.com/user-attachments/assets/13ec8506-a254-41cc-940b-6b8a91686a97)

```
> argocd version                                     
argocd: v2.14.1+3345d05
  BuildDate: 2025-02-03T21:45:26Z
  GitCommit: 3345d05a43d8edd7ec42ec71ffe8b5f95bc68dbe
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.14.2+ad27246
  BuildDate: 2025-02-05T23:44:17Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
               
> k get cm -n helm -o yaml | grep CUSTOM_HEADER
    CUSTOM_HEADER: This is on the DEV environment created by nitish!
        {"apiVersion":"v1","data":{"BG_COLOR":"#12181b","CUSTOM_HEADER":"This is on the DEV environment created by nitish!","FONT_COLOR":"#FFFFFF"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"helm-webapp"},"name":"myhelmapp-configmap-v1","namespace":"helm"}}
```

**Comment by nitishfy** [comment]
Looking at the manifest that didn't work:

```
source:
  repoURL: https://github.com/kedacore/charts
  path: keda
  targetRevision: v2.15.1
  helm:
    valuesObject:
      podIdentity:
        gcp:
          enabled: true
          gcpIAMServiceAccount: [redacted].iam.gserviceaccount.com
destination:
  server: https://kubernetes.default.svc
  namespace: keda
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

I think this is happening because the `gcp` field should be of an array , something like: 

```
gcp:
   - enabled: true
     gcpIAMServiceAccount: ...
```

Please read this: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values
