### ISSUE TITLE
latest version broke applicatonset generation

### ISSUE THREAD

**Issue by morgoved** [argoproj/argo-cd#22268]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
After upadate from v2.13.1 то v2.14.4

I have this approach for generation

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-all
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - name
          - appName
        generators:
          - matrix:
              generators:
                - clusters:
                    selector:
                      matchLabels:
                        argocd.argoproj.io/secret-type: cluster
                        owner: mxdr
                        env: dev
                - git:
                    repoURL: https://xxxxxxx/infrastructure/argocd.git
                    revision: HEAD
                    files:
                      - path: "defaults-dev/all/**/*.yaml"
                      - path: "defaults-dev/all/*.yaml"
          - git:
              repoURL: https://xxxxxxx/infrastructure/argocd.git
              revision: HEAD
              files:
                - path: "clusters/dev/*.yaml"
                - path: "clusters/dev/**/*.yaml"
                - path: "clusters/dev/**/**/*.yaml"
      selector:
        matchLabels:
          enabled: "true"
  template:
    metadata:
      name: >
        {{- if eq .name "in-cluster" -}}
          argocd-dev-{{ .appName }}
        {{- else -}}
          {{ .name }}-{{ .appName }}
        {{- end -}}
      annotations:
        debug-data: "{{ toJson . }}"
      namespace: argocd
    spec:
      project: "{{ .project }}"
      source:
        repoURL: "{{.source.repoURL}}"
        chart: "{{.source.chart}}"
        targetRevision: "{{.source.targetRevision}}"
        helm:
          values: |
            {{ toYaml .values | nindent 2 }}
      destination:
        name: "{{ .name }}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - prune=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
  templatePatch: |
    {{- if or .syncPolicy .ignoreDifferences }}
    spec:
      {{- if .syncPolicy }}
      syncPolicy:
        {{- if .syncPolicy.automated }}
        automated:
          {{- toYaml .syncPolicy.automated | nindent 10 }}
        {{- end }}
        {{- if .syncPolicy.syncOptions }}
        syncOptions:
          {{- toYaml .syncPolicy.syncOptions | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .ignoreDifferences }}
      ignoreDifferences:
      {{ toYaml .ignoreDifferences | nindent 4 }}
        - group: rbac.authorization.k8s.io
          kind: ClusterRole
          jsonPointers:
            - /rules
      {{- end }}
    {{- end }}

```
and somethig like this in defaults-dev

```
appName: istio-argo
namespace: argocd
project: argocd-base-dev
enabled: false
source:
  repoURL: xxxxxx.dkr.ecr.eu-central-1.amazonaws.com
  chart: cr-chart
  targetRevision: 0.1.0
```

and something like this in clusters folder

```
- appName: istio-argo
  name: in-cluster
  enabled: true
  values:
    cr:
      - apiVersion: networking.istio.io/v1alpha3
        kind: Gateway
        metadata:
          name: istio-argo-gw
        spec:
          selector:
            istio: ingressgateway
          servers:
            - port:
                number: 443
                name: https
                protocol: HTTPS
              hosts:
                - "argocd.xxxxxxxx.com"
              tls:
                mode: PASSTHROUGH

```

after update i see in logs for appl applications

`validation error found during application validation: application references project which does not exist
`

**Comment by rumstead** [comment]
That error message should contain the project that the application is referencing. Does it exist in the same namespace as Argo CD?

**Comment by morgoved** [comment]
Yes project present, i rolled back to v2.13.1 and all working well. Some changes between v2.13.1 and latest version do this bag.

**Comment by sarfarazgit** [comment]
@morgoved  - If we miss some mandatory  fields/parameters configuration in the applicationSet then validation errors are increased.

Example:

**Comment by morgoved** [comment]
i have all that you provided - did you check my request? all worked well in version v2.13.1 - i have errors if i start to try use v2.14.4 i have a bug. On version v2.13.1 all working well!

**Comment by nichcuta** [comment]
I can confirm that we encountered this bug after upgrading to 2.14.11 from 2.13.3. From my testing it turns out that when templating the project field with .project the error occurs.

Working Workaround, change the below:
```
...
    spec:
      project: "{{ .project }}"
...
```
With:
```
...
    spec:
      project: "{{ .projectName }}"
...
```
Effectivley as long as the variable is not named project it worked in my use case. Note that the value needs to also change in the generator section or in your case in _defaults-dev_. From `project: argocd-base-dev` to `projectName: argocd-base-dev`

Still think this is a bug, and there were no mentions in release notes of such a change but in the meantime hope this helps users with the issue

Thanks,
Nic

**Comment by rljohnsn** [comment]
We had to implement the exact same workaround for our ApplicationSets used by @nichcuta 

Here is the generator portion of our ApplicationSet (org and repo details obfuscated)

```
 generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: 'git@github.com:org/repo.git'
              revision: 'branch'
              files:
                - path: 'resources/*.yml'
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  env: alpha
                  type: workload
```
In essence the application metadata provided by the git generator contained the attribute `project` which conflicted with the new cluster object attribute that defaults to blank. We are rendering the application metadata so it was an easy fix to just rename `project` to something else. Not sure everyone will be in that boat though.

Here is the error message on the ApplicationSet status:

```
failed to combine string maps with merging params for the matrix generator: found duplicate key project with different value, a: data-encryption ,b:
```
`a` represents the git generator
`b` represents the cluster generator

For me its confusing to consider an entire cluster scoped into a single project. We have hundreds of projects within a workload cluster. 

UPDATE: Looks related to [this feature](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.11-2.12/) where projects help scope which clusters are allowed/available to Argo objects
