### ISSUE TITLE
Support helmCharts kustomize configuration option

### ISSUE THREAD

**Issue by joncolby** [argoproj/argo-cd#22300]
# Summary

When using kustomize, helm charts can be managed using the [helmCharts](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/) configuration option.

This feature requests to add `helmCharts` as a Kustomize application manifest configuration option, in addition to [the currently supported set of options](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#declarative).

# Motivation

We often use ApplicationSets to keep our code DRY across many target clusters.   Also, we usually leverage cluster labels as variables with the cluster-generator feature. 

Some kustomize apps use the `helmCharts` feature of kustomize to render helm charts.   Allowing the `helmCharts` config in the Application manifest would allow us to keep code DRY, without the need to create multiple overlays and values files when a unique configuration is required.
 

# Proposal

The declarative Application configuration should support the following syntax example:

```yaml
project: some-project
source:
 ...
  targetRevision: HEAD
  kustomize:
    commonLabels:
      environment: dev
    labelWithoutSelector: true
    helmCharts:
      - name: aws-vpc-cni
         releaseName: aws-node
         namespace: kube-system
         version: 1.19.2
         repo: https://aws.github.io/eks-charts
         valuesFile: ../../values.yaml
         additionalValuesFiles:
           - values.yaml
destination:
  namespace: kube-system
  name: some-cluster
```
