### ISSUE TITLE
Applicationset error git generator failed to list refs

### ISSUE THREAD

**Issue by gabriel-suela** [argoproj/argo-cd#22319]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hi, im getting an error when generating an applicationset with git generator, it says that `error generating params from git: error retrieving git files: rpc error: code = Internal desc = unable to resolve git revision: failed to list refs: read: connection reset by peer`. I've already successfully set up an ssh key for the repo, idk what to do.

**To Reproduce**

![Image](https://github.com/user-attachments/assets/ab61b6bb-15c8-4cfd-8436-08094bbea10c)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development-apps
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: git@github.com:-<org>/<org>-gitops.git
        revision: main
        files:
          - path: k8s/**/k8s-development.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:-<org>/<org>-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://vcluster/.**.**
        namespace: icv
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

**Expected behavior**

Apply the applicationset 

**Screenshots**

![Image](https://github.com/user-attachments/assets/735c7705-7675-4e70-99c6-843b9b447039)

**Version**

```shell
v2.14.5
```

**Logs**

![Image](https://github.com/user-attachments/assets/a7a3cd30-6606-4503-bdd2-4618c32403b0)

## logs from repo-server

![Image](https://github.com/user-attachments/assets/f62d1f78-e9a9-4418-add3-5a5b4e1cd5bd)
