### ISSUE TITLE
[BUG] Azure: 2.14.* breaks cross-tenant SPN auth

### ISSUE THREAD

**Issue by CCOLLOT** [argoproj/argo-cd#22318]
We have a central argocd deploying to several AKS clusters. Some of them are in the same azure tenant, in which case we use a workload identity while some others are in another azure tenant, in which case we use an Azure Service Principal with a client-id/client-secret as in the below config:

```yaml
config: |
  {
    "execProviderConfig": {
      "command": "argocd-k8s-auth",
      "env": {
        "AAD_ENVIRONMENT_NAME": "AzurePublicCloud",
        "AAD_SERVICE_PRINCIPAL_CLIENT_SECRET": "xxx",
        "AAD_SERVICE_PRINCIPAL_CLIENT_ID": "xxx",
        "AZURE_TENANT_ID": "xxx",
        "AAD_LOGIN_METHOD": "spn"
      },
      "args": ["azure"],
      "apiVersion": "client.authentication.k8s.io/v1beta1"
    },
    "tlsClientConfig": {
      "insecure": false,
      "caData": "xxx"
    }
  }
name: cluster-name
server: https://cluster-url.hcp.westeurope.azmk8s.io:443
```

After upgrading to 2.14.5, the central argocd can still connect to clusters using the `workloadidentity` login method but all connections using the `spn` login method towards other tenants fail (I don't know if it would fail within the same tenant).

I believe recent changes have been made to this part of the codebase.
