### ISSUE TITLE
ApplicationSet makes a lot of requests to the API server when using a flatList cluster generator

### ISSUE THREAD

**Issue by lsibilla** [argoproj/argo-cd#22314]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using an ApplicationSet with cluster generator and `flatList: true`, a large amount of apiserver requests is generated, eventually triggering apiserver rate limitation (Observed with 6 clusters).

**To Reproduce**

Connect 6 clusters to ArgoCD and add an ApplicationSet with:
```
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        flatList: true
  template:
    spec:
      source:
        helm:
          values: |
            [...]
            clusters:
              {{- .clusters | toYaml | nindent 2 }}
```

At this point, argoCD starts failing because of slow responses from the API server due to rate limitation.

You can observe the number of API server requests using LogInsights:
```
fields @timestamp, @message
| filter @logStream like "kube-apiserver-audit"
| filter ispresent(requestURI)
| filter verb = "list"
| filter userAgent like "argocd-applicationset"
| stats count(*) as CountTime by bin(3m), requestURI
| sort `bin(3m)` desc, CountTime desc
```

In my case, I can observe around 100 requests/minutes to `/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster`.

**Expected behavior**

I expect the applicationset controller to honor the defined polling interval.

**Mitigation**

I have successfully mitigated the issue by setting `ARGOCD_K8S_CLIENT_QPS=3` in my helm values:
```
applicationSet:
  extraEnv:
  - name: ARGOCD_K8S_CLIENT_QPS
    value: "3"
```

**Screenshots**

<img width="994" alt="Image" src="https://github.com/user-attachments/assets/4a93550d-7322-44fc-bbf8-ec641a35184e" />

**Version**

```shell
argocd: v2.13.1+af54ef8
  BuildDate: 2024-11-20T18:32:21Z
  GitCommit: af54ef8db5adfa77a08d4d05b1318a2198084c22
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: darwin/arm64
WARN[0001] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.14.5+f463a94
```

**Logs**

With the limitation mentioned above, I can observe the following log:
```
I0312 10:15:07.827836       6 request.go:700] Waited for 1.253535487s due to client-side throttling, not priority and fairness, request: GET:https://172.16.0.1:443/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster
```

**Comment by rumstead** [comment]
How often is your applicationset being requeued?

**Comment by lsibilla** [comment]
Hi @rumstead , how can I check that?

To be honest, I'm not sure what "requeued" mean, but to give more context, that particular application set and the generated data are changed on rare occasion. It serves to bootstrap clusters. Also, I can observe continuous high API rate even during off-hours and week-ends.

**Comment by rumstead** [comment]
> Hi [@rumstead](https://github.com/rumstead) , how can I check that?
> 
> To be honest, I'm not sure what "requeued" mean, but to give more context, that particular application set and the generated data are changed on rare occasion. It serves to bootstrap clusters. Also, I can observe continuous high API rate even during off-hours and week-ends.

The application and the applicationset controller can be triggered to work by a cluster event or at a fixed interval. When using the cluster generator, work is only triggered when an applicationset changes or a cluster secret with the label `argocd.argoproj.io/secret-type: cluster` changes. Meaning, it doesn't matter if it's off hours. 

You can see how often your applicationset is being requeue by counting the log line "end reconcile in" or by looking at the `controller_runtime_reconcile_total{controller="applicationset"}` metric. If you see a lot of reconciles, you can set the applicationset controller's log level to debug and watch for log lines "received update event" or "received generic event"

You can see how often the secrets change by checking for the log line "processing event for cluster secret".

**Comment by rumstead** [comment]
Each cluster generator will do 2 "cluster lists" and each reconciliation for any applicationset will do 1 cluster list. 

Can you provide the raw numbers of our queries when you rerun them?

**Comment by lsibilla** [comment]
Hi @rumstead 

I have re-run the query for the same 7 days period and binned them day-per-day:
**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: [redacted]
start-time: 2025-03-10T00:00:00.000Z    
end-time: 2025-03-17T23:59:59.000Z    
query-string:
  ```
  fields @timestamp, @message
| filter @logStream like "kube-apiserver-audit"
| filter ispresent(requestURI)
| filter verb = "list"
| filter userAgent like "argocd-applicationset"
| stats count(*) as CountTime by bin(1d), requestURI
| sort `bin(1d)` desc, CountTime desc
  ```
---
| bin(1d) | requestURI | CountTime |
| --- | --- | --- |
| 2025-03-17 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 119785 |
| 2025-03-16 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 119548 |
| 2025-03-15 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 128702 |
| 2025-03-14 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 119376 |
| 2025-03-14 00:00:00.000 | /api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0 | 2 |
| 2025-03-14 00:00:00.000 | /apis/argoproj.io/v1alpha1/namespaces/argocd/applicationsets?limit=500&resourceVersion=0 | 1 |
| 2025-03-14 00:00:00.000 | /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects?limit=500&resourceVersion=0 | 1 |
| 2025-03-14 00:00:00.000 | /apis/argoproj.io/v1alpha1/namespaces/argocd/applications?limit=500&resourceVersion=0 | 1 |
| 2025-03-14 00:00:00.000 | /api/v1/namespaces/argocd/configmaps?labelSelector=app.kubernetes.io%2Fpart-of%3Dargocd&limit=500&resourceVersion=0 | 1 |
| 2025-03-13 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 119526 |
| 2025-03-12 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 126651 |
| 2025-03-11 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 132313 |
| 2025-03-11 00:00:00.000 | /api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0 | 2 |
| 2025-03-11 00:00:00.000 | /apis/argoproj.io/v1alpha1/namespaces/argocd/applicationsets?limit=500&resourceVersion=0 | 1 |
| 2025-03-11 00:00:00.000 | /apis/argoproj.io/v1alpha1/namespaces/argocd/applications?limit=500&resourceVersion=0 | 1 |
| 2025-03-11 00:00:00.000 | /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects?limit=500&resourceVersion=0 | 1 |
| 2025-03-11 00:00:00.000 | /api/v1/namespaces/argocd/configmaps?labelSelector=app.kubernetes.io%2Fpart-of%3Dargocd&limit=500&resourceVersion=0 | 1 |
| 2025-03-10 00:00:00.000 | /api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster | 132643 |
---

**Comment by rumstead** [comment]
and for those time ranges, how many reconciles and secret changes happened?

**Comment by lsibilla** [comment]
@rumstead , as stated above, there has been 273 reconciliation and 16 secret changes.

**Comment by agaudreault** [comment]
Take a look at the options from https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/cluster_constants.go to improve the communication with the api-server

**Comment by rumstead** [comment]
I agree that an informer can help, but I cannot come near the volume of secret lists being reported. 

Something else must be changing that is causing more reconciles. Eg, errors in the applicationset, changing child applications, something else. I haven't touched the cluster secrets or the applicationset for over an hour, and no additional requests have been sent. 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: argocd
spec:
  generators:
  - clusters:
      flatList: true
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      labels:
        app-type: cluster
      name: cluster-generator
    spec:
      destination:
        name: dev
        namespace: cluster-generator
      project: default
      source:
        path: manifests/kustomize/
        repoURL: https://github.com/rumstead/argocd-playground.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
```

```
❯ jq '[inputs | select(.user.username | contains("argocd-applicationset") and . != {})] | [.[].requestURI] | length' audit.log
22

❯ jq '[inputs | select(.user.username | contains("argocd-applicationset") and . != {})] | .[].requestURI' audit.log 
"/api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0"
"/api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0"
"/api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0"
"/api/v1/namespaces/argocd/secrets?limit=500&resourceVersion=0"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
"/api/v1/namespaces/argocd/secrets?labelSelector=argocd.argoproj.io%2Fsecret-type%3Dcluster"
```
