### ISSUE TITLE
Multi source applicationset with templated value as targetRevision erroring

### ISSUE THREAD

**Issue by 4l3xNA** [argoproj/argo-cd#22324]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

 I have a multisource appset with a templated value as targetRevision. If I do exactly the same with a hardcoded value on the targetRevision it works fine. I double checked that the templated value of the label is corrected and exists. Any idea why this could be happening? This same approach works for appsets with 2 sources. But this one with 3 have some type of issue.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-proportional-autoscaler
  namespace: argocd
  labels:
    cluster-components: "true"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster-name: qd01-us-1
            nodegroup-label: general
            coresPerReplica: "4"
            cpu-requests: "0.4"
  template:
    metadata:
      name: '{{cluster-name}}-proportional-scaler-{{nodegroup-label}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;..
      namespace: argocd
      labels:
          cluster-name: "{{cluster-name}}"
    spec:
      project: sre-common
      sources:
      - chart: cluster-proportional-autoscaler
        repoURL: 'https://kubernetes-sigs.github.io/cluster-proportional-autoscaler'
        targetRevision: 1.1.0
        helm:
          valueFiles:
          - $values/argocd/cluster_components/base/values-files/cluster-proportional-autoscaler.yaml
          values: |
            config:
              linear:
                coresPerReplica: {{coresPerReplica}}
            options:
              nodeLabels:
                {{nodegroup-label}}: "true"
              target: deployment/overprovisioning-{{nodegroup-label}}
      - repoURL: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sre'
        targetRevision: '{{metadata.labels.base-components-target-revision}}'
        ref: values
      - repoURL: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sre'
        targetRevision: '{{metadata.labels.base-components-target-revision}}'
        path: argocd/cluster_components/base/cluster-proportional-autoscaler
        helm:
          values: |
            nodegroupLabel: {{nodegroup-label}}
            overprovisioning:
                cpuRequest: {{cpu-requests}}
      destination:
        name: "{{cluster-name}}"
        namespace: 'kube-system'
``` 
This is error I get:
```
rpc error: code = Unknown desc = failed to get git client for repo https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sre
``` 

**To Reproduce**

Recreate the applicationset above

**Expected behavior**

It is expected for the application to recognize the value of the cluster label. But it does not. 

**Version**

```shell
{
    "Version": "v2.7.8+92949f6.dirty",
    "BuildDate": "2023-07-19T15:18:54Z",
    "GitCommit": "92949f6033080f2fba9a9654f46592fb71982770",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```
