### ISSUE TITLE
A resource tracked through ownerReference is not filtered out by resourceExclusions

### ISSUE THREAD

**Issue by amit-o** [argoproj/argo-cd#22334]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Setting resourceExclusions for a kind not directly managed by argo (ie one that is tracked due to ownerReference) doesn't affect the UI.
This is important for services such as karpenter where we can have thousands of NodeClaim objects, causing the UI to freeze.

**To Reproduce**
Create a deployment managed by argo, set
```yaml
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - "ReplicaSet"
      clusters:
      - "*"
```
And see how the replicaSet still shows in the UI. Filtering out deployment works

**Expected behavior**
We expect to not see the excluded resource no matter where in the hierarchy they are

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
argocd-server: v2.14.1+3345d05
```

**Logs**

```
Paste any relevant application logs here.
```
