### ISSUE TITLE
Unable to add OCI Helm Repository on Harbor

### ISSUE THREAD

**Issue by aydinseven7** [argoproj/argo-cd#22349]
Hello everybody,

I am unable to add a privately hosted OCI registry as a Helm repository source through the UI and declaratively.
My Secret:
```
apiVersion: v1
stringData:
  project: poc
  type: helm
  url: https://harbor.domain.com/demo
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-demo-harbor
  namespace: argocd
type: Opaque
```
With there being a different secret for credentials:
```
apiVersion: v1
stringData:
  password: SECRET
  url: https://harbor.domain.com/demo
  type: helm
  username: 'robot$demo+k8s'
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: creds-harbor-demo
  namespace: argocd
type: Opaque
```

I have also tried to use `oci://` instead of `https://`, the first resulting in "unsupported protocol" and the latter producing this error:
`finished unary call with code Unknown" error="error testing repository connectivity: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `<!DOCTY...` into helm.Index" grpc.code=Unknown grpc.method=TestRepository grpc.service=repository.RepoServerService grpc.start_time="2025-03-14T10:53:45Z" grpc.time_ms=21.005 span.kind=server system=grpc`.

Can anybody help?

My ArgoCD version:
```
{
    "Version": "v2.12.6+4dab5bd",
    "BuildDate": "2024-10-18T17:39:26Z",
    "GitCommit": "4dab5bd6a60adea12e084ad23519e35b710060a2",
    "GitTreeState": "clean",
    "GoVersion": "go1.22.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.2 2024-05-22T15:19:38Z",
    "HelmVersion": "v3.15.2+g1a500d5",
    "KubectlVersion": "v0.29.6",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by aydinseven7** [comment]
The fix, which isn't shown in any documentation (or not easily available):
```
apiVersion: v1
stringData:
  project: "poc"
  type: "helm"
 enableOCI: "true"
  url: "harbor.domain.com/demo"
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-demo-harbor
  namespace: argocd
type: Opaque
```
The "enableOCI" field fixed it, with the protocol and specific repo being omitted, only using the base domain and project in Harbor

Can you update the documentation on that?
