### ISSUE TITLE
Page crashes when setting the 'valuesObject' value in the UI YML

### ISSUE THREAD

**Issue by Ruby-rc** [argoproj/argo-cd#22367]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Steps to Reproduce:

  1. Generate an application using Helm's [valuesObject](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values
) defined in a YAML:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxx
spec:
  destination:
    namespace: xx
    server: xx
  source:
    helm:
      valuesObject:
        ingress:
          enabled: true
          path: /
          hosts:
            - mydomain.example.com
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          labels: {}
          tls:
            - secretName: mydomain-tls
              hosts:
                - mydomain.example.com
```
2. Save the YAML
3. Observe that the UI unexpectedly crashes 

**Screenshots**

![Image](https://github.com/user-attachments/assets/abd3a97d-9b6c-4b16-a1cb-7b6086487426)

![Image](https://github.com/user-attachments/assets/bd8136e1-60c0-48d5-ba66-85c58522edb3)

**Comment by Ruby-rc** [comment]
I suspect the issue might the result of the this: 

https://github.com/argoproj/argo-cd/pull/14257/files#diff-5aa688c8363519e0872e7dc3c5fec9b665f7b3ee2cc6db59d14e6ac2eeef1907R226

**Comment by Ruby-rc** [comment]
I'll try to fix this

**Comment by nitishfy** [comment]
Nvm, you can raise a different PR to fix [this](https://github.com/argoproj/argo-cd/issues/22234).

**Comment by Ruby-rc** [comment]
> Nvm, you can raise a different PR to fix [this](https://github.com/argoproj/argo-cd/issues/22234).nvm，你可以提出不同的 PR 来[解决这个问题](https://github.com/argoproj/argo-cd/issues/22234)。




Yes, I think these are two separate issues.

One issue is the crash caused by setting ValuesObject in YAML. I raised this PR to confirm whether it is reasonable to modify the ValuesObject value to values when editing YAML (since modifying values in this way would be more convenient after switching from YAML to a form).

The other [issue](https://github.com/argoproj/argo-cd/issues/6086) is the display error in parameters, which involves several values' precedence problems (Order of precedence is parameters > valuesObject > values > valueFiles > helm repository values.yaml). As shown in the figure, when editing, if the Helm parameters are as follows, what should the behavior of "Remove override" and "keepoverride" be? (Is it reasonable to directly clear the values of `values`, `valuesObject`, and `parameters`?)

![Image](https://github.com/user-attachments/assets/fd487092-eb40-4c9e-ac43-eda6580cfe16)

```
helm:
    values: |
      replicaCount: 1
    valuesObject:
      replicaCount: 2
    parameters:
      - name: replicaCount
        value: '3'
```

If these two issues are confirmed, I will fix them together in this PR.
