### ISSUE TITLE
Expose Application Parameter Overrides as Metrics

### ISSUE THREAD

**Issue by LaikaN57** [argoproj/argo-cd#22386]
# Summary

We would like to see new metrics and/or metric labels exposed that would show which ArgoCD applications currently have parameter overrides set.

The current workaround is to use [`kube-state-metrics`](https://github.com/kubernetes/kube-state-metrics?tab=readme-ov-file#readme) and define [custom resource state metrics](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md) like this:

```yaml
customResourceState:
  enabled: true
  config:
    spec:
      resources:
        - groupVersionKind:
            group: argoproj.io
            kind: Application
            version: v1alpha1
          labelsFromPath:
            name: [metadata, name]
            namespace: [metadata, namespace]
            project: [spec, project]
            dest_server: [spec, destination, server]
            dest_namespace: [spec, destination, namespace]
          metrics:
            - name: argocd_app_param_override
              help: >-
                A metric series will be emmited for each ArgoCD application
                parameter that is overriden. Note that the value will always
                be 1. If a parameter is not overriden, no metric series will
                exist for it.
              each:
                type: Info
                info:
                  path: [spec, source, helm, parameters]
                  labelsFromPath:
                    parameter_name: [name]
```

# Motivation

Like `argocd_app_info`, a future "`argocd_app_params_info`" would be helpful in monitoring parameter overrides which have not yet been codified. We currently use the KSM workaround to find when engineers have temporarily increased memory requests or limits for troubleshooting purposes and send nags after a few days to remind them to either codify their overrides or revert them.

# Proposal

This could be implemented as a new metric or possibly as an extension of the current `argocd_app_info` metric. Currently the KSM workaround metric looks like this:

```json
{
  __name__="kube_customresource_argocd_app_param_override"
  cluster="dev1"
  dest_namespace="my-app-namespace"
  dest_server="https://kubernetes.default.svc"
  name="my-app"
  parameter_name="my-app.somerandomoverride"
  project="default"
}
```

In KSM, we use an "Info" type metric which is essentially just a "Gauge" that always reads `1`. This works well for dashboard/alerting and is what `argocd_app_info` currently does.

One small implementation detail here to consider is that I am not sure if `.spec.source.helm.parameters[*]` only exists for "overrides" as denoted in the ArgoCD web UI (gavel icon). There may be some extra state tracking that needs to take place internally that the ArgoCD application k8s resource does not maintain.
