### ISSUE TITLE
cert-manager crd are always unsynced

### ISSUE THREAD

**Issue by mckjhd** [argoproj/argo-cd#2239]
I've merged cert-manager crds to cert-manager v0.9.1 helm chart, and the state of cert-manager deployment is always out of sync, supposedly due to the following. I'm using ArgoCD helm chart v0.3.0 (argocd 1.1.2).

```sh
time="2019-09-01T19:45:18Z" level=info msg="kubectl --kubeconfig /dev/shm/355031746 -f - apply -n cert-manager --dry-run" dir= execID=z02p1
time="2019-09-01T19:45:18Z" level=error msg="`kubectl convert --output-version apiregistration.k8s.io/v1beta1 -o json --local=true -f /dev/shm/168359342` failed exit status 1: kubectl convert is DEPRECATED and will be removed in a future version.\nIn order to convert, kubectl apply the object to the cluster, then kubectl get at the desired version.\nerror: unable to decode \"/dev/shm/168359342\": no kind \"APIService\" is registered for version \"apiregistration.k8s.io/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29\"" execID=SzlEq
time="2019-09-01T19:45:18Z" level=warning msg="Failed to convert resource: kubectl failed exit status 1: kubectl convert is DEPRECATED and will be removed in a future version.\nIn order to convert, kubectl apply the object to the cluster, then kubectl get at the desired version.\nerror: unable to decode \"/dev/shm/168359342\": no kind \"APIService\" is registered for version \"apiregistration.k8s.io/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29\"
```

**Comment by alexec** [comment]
can you please provide the version of Kubernetes you are using?

**Comment by mckjhd** [comment]
@alexec 1.14.6

**Comment by greenstatic** [comment]
I experienced a similar issue (manual installation of cert-manager opposed to installation via helm).

I managed to come up with a configuration hotfix. In my application manifest I added the following:

```
  # This solves a bug where argo-cd will mark the application as healthy but OutOfSync
  # this occurs because cert-manager updates the status field in the CRD. This field 
  # makes argo-cd diff's think it is out of sync.
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificaterequests.certmanager.k8s.io
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificates.certmanager.k8s.io
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: challenges.certmanager.k8s.io
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterissuers.certmanager.k8s.io
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: issuers.certmanager.k8s.io
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: orders.certmanager.k8s.io
      jsonPointers:
      - /status
```

**Comment by alexec** [comment]
See #2684 #2629

**Comment by alexec** [comment]
I'm in the process of trying to repo this on Argo CD v1.3. 

Following: https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html

```
kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml
kubectl create namespace cert-manager
argocd repo add https://charts.jetstack.io --type helm --name jetpack
argocd app create cert-manager --repo https://charts.jetstack.io --helm-chart cert-manager --revision v0.11.0 --dest-namespace cert-manager --dest-server https://kubernetes.default.svc
argocd app sync cert-manager
```

**Comment by alexec** [comment]
@greenstatic I see you found that if you ignore the status of all the custom resources, then they go in-sync. @mckjhd did you try this workaround please?

**Comment by mckjhd** [comment]
@alexec, so the workaround is to deploy crds before the rest of the app?

**Comment by greenstatic** [comment]
@mckjhd I doubt that will work since the `status` field will change after the app (cert-manager) is deployed. Also you need to deploy the app (at least the custom resource definitions) so you can even deploy the CRD.

**Comment by samvdb** [comment]
Updated ignoreDifferences for 0.11.0 ( new namespace cert-manager.io )

```yaml
  # This solves a bug where argo-cd will mark the application as healthy but OutOfSync
  # this occurs because cert-manager updates the status field in the CRD. This field
  # makes argo-cd diff's think it is out of sync.
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificaterequests.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: challenges.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: challenges.acme.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: orders.acme.cert-manager.io
      jsonPointers:
        - /status
```

**Comment by binoue** [comment]
We encountered the same problem. 
To solve this, we patched the upstream CRDs [here](https://github.com/cybozu-go/neco-apps/blob/master/cert-manager/base/kustomization.yaml).

cert-manager is now v0.12.0 and its CRDs do not contain the status filed.

**Comment by olivierlemasle** [comment]
I have the same problem with prometheus-operator's CRDs.
When I initially deployed prometheus-operator using Argo CD, everything was fine. However, since I tried to upgrade it, with new versions of CRDs, CRDs always appear unsynced due to differences in status.
I suppose I can ignore these differences with `ignoreDifferences`. However, is it normal to compare CRD's statuses (not only specs)?

**Comment by nhuray** [comment]
@samvdb 

I'm running the last version of ArgoCD (v1.4.2). 

I tried to setup the `ignoreDifferences` on the `Application` but the cert-manager crds are still OutOfSync.

I tried to define a System-Level Configuration in the configmap `argocd-cm`:

```
apiextensions.k8s.io/CustomResourceDefinition:
    ignoreDifferences: |
      jsonPointers:
      - /status
```
but it's still not working.

Can you share your configuration or tell me if I'm missing something ?

Thanks

Note: It might be a good idea in the future to have an annotation to disable health check

**Comment by alexmt** [comment]
Hello @nhuray,
I think it does not work because group and kind fields are missing. Please check this example: https://github.com/argoproj/argoproj-deployments/blob/master/argoproj/base/cert-manager.yaml

**Comment by nhuray** [comment]
@alexmt 

Actually I did the same thing on `Application` defining it like that:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/cert-manager
    repoURL: git@bitbucket.org:xxx/deployments.git
    targetRevision: "HEAD"
    helm:
      releaseName: cert-manager
      valueFiles:
        - env/ops.yaml
  # Cert-manager hack: See: https://github.com/argoproj/argo-cd/issues/2239
  ignoreDifferences:
    - group:  apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: certificaterequests.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: challenges.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: challenges.acme.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: orders.acme.cert-manager.io
      jsonPointers:
        - /status
```

Then I tried to configure globally in the config map as explained in the documentation: https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration

ArgoCD remains OutOfSync in any case.

Thanks for your help.

**Comment by mojtabacazi** [comment]
`x-kubernetes-preserve-unknown-fields` seems to be the difference causing sync issues for CRDs .

**Comment by drzero42** [comment]
@mojtabacazi The issue with `x-kubernetes-preserve-unknown-fields` is well known for cert-manager. It is a field that will cause a validation error on Kubernetes versions before 1.15, as mentioned in the cert-manager docs: https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests
If you were to apply it manually yourself with kubectl, you would need to add `--validate=false` to get it to apply. I just had this issue on a GKE cluster running v1.14.8-gke.33. After upgrading to v1.15.9-gke.8 the issue goes away.
I don't know enough about ArgoCD yet to know if it is possible to add `--validate=false` to the apply step for clusters that you can not upgrade. Perhaps somebody else can fill in that information?

**Comment by mojtabacazi** [comment]
@drzero42 

> @mojtabacazi The issue with `x-kubernetes-preserve-unknown-fields` is well known for cert-manager. It is a field that will cause a validation error on Kubernetes versions before 1.15, as mentioned in the cert-manager docs: https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests
> If you were to apply it manually yourself with kubectl, you would need to add `--validate=false` to get it to apply. I just had this issue on a GKE cluster running v1.14.8-gke.33. After upgrading to v1.15.9-gke.8 the issue goes away.
> I don't know enough about ArgoCD yet to know if it is possible to add `--validate=false` to the apply step for clusters that you can not upgrade. Perhaps somebody else can fill in that information?

Yes you can pass `--validate=false` in ArgoCD, but I haven't found a way to ignore those differences.

**Comment by dmitrievav** [comment]
Cert manager v0.13.0 with kubernetes v1.15.6 do not have this issue

**Comment by chriskolenko** [comment]
@mojtabacazi Here is the workaround I used to ignore status and x-kubernetes-preserve-unknown-fields

```
    resource.customizations: |
      apiextensions.k8s.io/CustomResourceDefinition:
          ignoreDifferences: |
            jsonPointers:
            - /status
            - /spec/validation/openAPIV3Schema/properties/spec/properties/solver/properties/dns01/properties/webhook/properties/config/x-kubernetes-preserve-unknown-fields
            - /spec/validation/openAPIV3Schema/properties/spec/properties/acme/properties/solvers/items/properties/dns01/properties/webhook/properties/config/x-kubernetes-preserve-unknown-fields
```
