### ISSUE TITLE
Enable support for kustomize edit add configmap and secret to the application manifest

### ISSUE THREAD

**Issue by cweeks72** [argoproj/argo-cd#22407]
# Summary

Kustomize edit - the mechanism you use to create kustomize manifests, supports the "configmap" and "secret" actions to add "configMapGenerator" and "secretGenerator" statements to the in-flight kustomization file, similarly to the existing "patches" and "components" actions. (There is also a generic resource action as well to add an arbitrary resource to the kustomize).

Exposing these to the application layer of argo would allow injection of configmaps and secrets from the argo context into the kustomize build setup, enabling DRY on a significant scale, since the kustomization file could then use those extensively for configuration of the application.

# Motivation

I have a bunch of cloud resources built by external means. They need to be referenced within kubernetes applications. Some are secret, some are not, but all require injection into the kubernetes manifest somehow. Storing the resource references and loading them into a configmap or secret would allow me to use kustomize replacements to populate the application. Currently, I have to hard code URLs to a specific external location, but ideally, the location of the resources would be provided in the argo cluster secret (by means of annotations on the cluster secret), that could then be read and populated using an applicationset templatePatch.

Example:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - "management"
        values:
          resources: '{{index .metadata.annotations "resourcedata"}}'
  template:
    metadata:
      name: 'test-app'
    spec:
      project: default
      source:
        repoURL: <nope>
        targetRevision: main
        path: test
        kustomize:
          namespace: test
      destination:
        server: '{{.server}}'
        namespace: test
      syncPolicy:	
        automated:
          selfHeal: true	
          prune: true	
        syncOptions:
        - CreateNamespace=true
        - FailOnSharedResource=true
  templatePatch: |
    {{- $env := index .metadata.labels "env" }}
    {{- $path := .values.resources }}
    spec:
      source:
        kustomize:
          configmap:
            - name: myresourceparameters
              envFile: {{$path}}/testparams/
```

# Proposal

How do you think this should be implemented?

I believe that adding additional kustomize map keys "configmap" and "secret" with a name and various file options would work nicely. There seems to be several options for adding files of various types using the kustomize edit add configmap/secret command:

```
$ kustomize edit add configmap
Error: failed to validate flags: name must be specified once
Usage:
  kustomize edit add configmap NAME [--namespace=namespace-name] [--behavior={create|merge|replace}] [--from-file=[key=]source] [--from-literal=key1=value1] [flags]

Examples:

	# Adds a configmap to the kustomization file (with a specified key)
	kustomize edit add configmap my-configmap --from-file=my-key=file/path --from-literal=my-literal=12345

	# Adds a configmap to the kustomization file (key is the filename)
	kustomize edit add configmap my-configmap --from-file=file/path

	# Adds a configmap from env-file
	kustomize edit add configmap my-configmap --from-env-file=env/path.env

	# Adds a configmap from env-file with behavior merge
	kustomize edit add configmap my-configmap --behavior=merge --from-env-file=env/path.env

	# Adds a configmap to the kustomization file with a specific namespace
	kustomize edit add configmap my-configmap --namespace test-ns --from-literal=my-key=my-value


Flags:
      --behavior string            Specify the behavior for config map generation, i.e whether to create a new configmap (the default),  to merge with a previously defined one, or to replace an existing one. Merge and replace should be used only  when overriding an existing configmap defined in a base
      --disableNameSuffixHash      Disable the name suffix for the configmap
      --from-env-file string       Specify the path to a file to read lines of key=val pairs to create a configmap (i.e. a Docker .env file).
      --from-file strings          Key file can be specified using its file path, in which case file basename will be used as configmap key, or optionally with a key and file path, in which case the given key will be used.  Specifying a directory will iterate each named file in the directory whose basename is a valid configmap key.
      --from-literal stringArray   Specify a key and literal value to insert in configmap (i.e. mykey=somevalue)
  -h, --help                       help for configmap
      --namespace string           Specify the namespace of the ConfigMap

Global Flags:
      --stack-trace   print a stack-trace on error
```

To implement this, it seems like the primary changes would be to extend the build function here: 
https://github.com/argoproj/argo-cd/blob/9f37d436726256a3182ba3623fd927de66f315c8/util/kustomize/kustomize.go#L128

and amend schemas to suit.

I don't know when kustomize added this functionality, so I'm not sure what version bounds you'd need to add to support this capability, sorry.
