### ISSUE TITLE
Upgrade from 2.14.5 to 2.14.6 breaks Argo Rollouts promote action

### ISSUE THREAD

**Issue by kaiburjack** [argoproj/argo-cd#22408]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading from ArgoCD 2.14.5 to 2.14.6, I cannot click on "Promote-Fully" on an Argo Rollouts "Rollout" object via the ArgoCD UI anymore.

The HTTP call that the ArgoCD UI sends:
```
https://argo.my.domain/api/v1/applications/myapp/resource/actions?appNamespace=argocd&namespace=default&resourceName=myapp&version=v1alpha1&kind=Rollout&group=argoproj.io
```
fails with the ArgoCD server responding with:
```
{
    "error": "application appproject/myapp is not permitted to manage argoproj.io/Rollout/myapp in default",
    "code": 2,
    "message": "application appproject/myapp is not permitted to manage argoproj.io/Rollout/myapp in default"
}
```

**To Reproduce**

- deploy ArgoCD 2.14.6
- deploy Argo Rollouts 1.8.0
- create an ArgoCD application and assign it a ArgoCD project other than "default"
- make a Rollout manifest with a canary strategy and a "pause" step part of that ArgoCD application which wants to deploy to the default namespace
- make a change in the Rollout (e.g. pod template label changes)
- wait until the Rollout hits the "pause" step
- try to do a promotion via the ArgoCD context menu on the Rollout object via "Promote-Full"

**Expected behavior**

The promotion should work just like in ArgoCD 2.14.5 (with Argo Rollouts 1.8.0).

**Version**

2.14.6

**Comment by kaiburjack** [comment]
In addition, one can also not trigger CronJobs via the ArgoCD UI anymore.

**Comment by kaiburjack** [comment]
Seemingly, the only relevant commit here between 2.14.5 and 2.14.6 is: https://github.com/argoproj/argo-cd/commit/38c03769af1d62ae07c0ffcf8f74d7a8cb283570
So, something in the authorization logic for ArgoCD REST/API calls (emitted by the ArgoCD UI) got broken due to this.

**Comment by PatrickSpies** [comment]
Restart-action for deployments seems to be affected too:

> Unable to execute resource action: application my-appproject/my-namespace/my-app is not permitted to manage apps/Deployment/my-deployment in my-namespace

Downgrading to v2.14.5 fixes this issue..

**Comment by crenshaw-dev** [comment]
Taking a look. That's a really weird bug to be caused by that change, but I agree, the other change doesn't seem relevant. @rumstead have time to take a look?

**Comment by rumstead** [comment]
yea, i dont use argo rollouts is there a semi-simple way to reproduce?

**Comment by kaiburjack** [comment]
> yea, i dont use argo rollouts is there a semi-simple way to reproduce?

https://github.com/argoproj/argo-cd/issues/22408#issuecomment-2737137809 also mentions that Restarting a simple Deployment does also not work.

**Comment by rumstead** [comment]
What configuration do you think I am missing? 

https://github.com/user-attachments/assets/d1fffe7d-36f1-4cad-9040-dae2539bb36b

**Comment by kaiburjack** [comment]
@rumstead sure. Here are a bit more details:
1. We install ArgoCD via the Helm Chart: https://artifacthub.io/packages/helm/argo/argo-cd
2. For authorization we use Google Federated Logins via DEX (via the Dex deployment provided by the ArgoCD Helm chart)
3. We use the following effective configuration:
```yaml
global:
  logging:
    format: json
    level: warn
  additionalLabels: &helmLabels
    app.kubernetes.io/managed-by: Helm
crds:
  annotations: &helmAnnotations
    meta.helm.sh/release-namespace: argocd
    meta.helm.sh/release-name: argocd
  labels: *helmLabels
redis:
  service:
    annotations: *helmAnnotations
  metrics:
    enabled: true
    service:
      annotations: *helmAnnotations
    serviceMonitor:
      enabled: true
      namespace: argocd
      interval: null
  exporter:
    enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
controller:
  replicas: 1
  serviceAccount:
    annotations: *helmAnnotations
  metrics:
    enabled: true
    service:
      annotations: *helmAnnotations
    serviceMonitor:
      enabled: true
      namespace: argocd
      interval: null
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
applicationSet:
  pdb:
    enabled: true
    minAvailable: 1
    annotations: *helmAnnotations
    labels: *helmLabels
  replicas: 3
  service:
    annotations: *helmAnnotations
  serviceAccount:
    annotations: *helmAnnotations
  metrics:
    enabled: true
    service:
      annotations: *helmAnnotations
    serviceMonitor:
      enabled: true
      namespace: argocd
      interval: null
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  webhook:
    enabled: true
notifications:
  secret:
    create: false
  serviceAccount:
    annotations: *helmAnnotations
  metrics:
    enabled: true
    service:
      annotations: *helmAnnotations
    serviceMonitor:
      enabled: true
      namespace: argocd
      interval: null
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
repoServer:
  pdb:
    enabled: true
    minAvailable: 1
    annotations: *helmAnnotations
    labels: *helmLabels
  replicas: 3
  service:
    annotations: *helmAnnotations
  serviceAccount:
    annotations: *helmAnnotations
  metrics:
    enabled: true
    service:
      annotations: *helmAnnotations
    serviceMonitor:
      enabled: true
      namespace: argocd
      interval: null
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: ARGOCD_GIT_ATTEMPTS_COUNT
      value: "5"
server:
  pdb:
    enabled: true
    minAvailable: 1
    annotations: *helmAnnotations
    labels: *helmLabels
  replicas: 3
  serviceAccount:
    annotations: *helmAnnotations
  metrics:
    enabled: true
    service:
      annotations: *helmAnnotations
    serviceMonitor:
      enabled: true
      namespace: argocd
      interval: null
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  service:
    service:
      annotations: *helmAnnotations
    type: ClusterIP

configs:
  notifications:
    secret:
      # DO NOT let the Helm chart create the secret! We create it in another deployment manually!
      create: false
  secret:
    # DO NOT let the Helm chart create the secret!
    # We create this Secret via an ExternalSecret in the argocd-before chart.
    createSecret: false
  gpg:
    annotations: *helmAnnotations
  params:
    annotations: *helmAnnotations
    server.insecure: true
    reposerver.parallelism.limit: "20"
    controller.status.processors: "25"
    controller.operation.processors: "20"
  cm:
    annotations: *helmAnnotations
    exec.enabled: true
    timeout.reconciliation: 1800s # <-- 30m
    timeout.reconciliation.jitter: 600s # <-- 10m
  ssh:
    annotations: *helmAnnotations
  tls:
    annotations: *helmAnnotations
  rbac:
    annotations: *helmAnnotations
    policy.default: "role:readonly"
    policy.csv: |
      g, user.a@example.com, role:admin
    scopes: "[groups, email]"

dex:
  serviceAccount:
    annotations: *helmAnnotations
  metrics:
    service:
      annotations: *helmAnnotations
  extraArgs:
    - --logformat
    - json
    - --loglevel
    - warn
  enabled: true
  # WORKAROUND: to enable Google Authorization
  # In Istio, HTTP traffic is routed to a cluster based on Host header.
  # Dex reverse proxy does not rewrite Host header, so traffic does not get routed to argocd-dex-server cluster
  # Reference: https://github.com/argoproj/argo-cd/issues/3975
  servicePortHttpName: tcp
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
```

**Comment by rumstead** [comment]
sorry, specifically the `appproject/myapp` configuration like the destintation, resource allowlists, etc.

**Comment by kaiburjack** [comment]
Sure, if you mean the Application manifest spec, then:
```yaml
spec:
  destination:
    name: in-cluster
    namespace: oauth2-proxy
  project: default
  revisionHistoryLimit: 2
  source:
    helm:
      releaseName: oauth2-proxy
      valueFiles:
      - values.yaml
    path: services/oauth2-proxy
    repoURL: https://my.gitlab/myrepo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
```

**Comment by kaiburjack** [comment]
And here is a screenshot of the ArgoCD "default" project settings (where this Application is deployed in):

![Image](https://github.com/user-attachments/assets/cca35732-2f07-4dcd-87b5-b437f2c8c907)

**Comment by kaiburjack** [comment]
But, like said above: Everything is totally fine in ArgoCD 2.14.5. It starts failing with 2.14.6. And the *only* change I do is to upgrade to the argocd Helm chart version 7.8.12 from 7.8.11.

**Comment by rumstead** [comment]
When you rolled back did you roll back both the chart and the image version?

**Comment by PatrickSpies** [comment]
I tried both variants with the same result, what to expect, as the chart-versions 7.8.12 contains only the bumped argo-version.

**Comment by crenshaw-dev** [comment]
I'm not able to reproduce this bug in 2.14.6. The request to this URL succeeded:

```
https://localhost:8443/api/v1/applications/cronjob/resource/actions?appNamespace=argocd&namespace=default&resourceName=hello&version=v1&kind=CronJob&group=batch
```

My app config:

```yaml
project: default # configured as out-of-the-box
source:
  repoURL: https://github.com/crenshaw-dev/argocd-example-apps
  path: cronjob
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: default
```

**Comment by crenshaw-dev** [comment]
@kaiburjack the screenshot from your original post is weird:

![](https://private-user-images.githubusercontent.com/72760888/424636090-1c70a135-f62c-4d72-8b83-240d743f5d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI0ODAyMDIsIm5iZiI6MTc0MjQ3OTkwMiwicGF0aCI6Ii83Mjc2MDg4OC80MjQ2MzYwOTAtMWM3MGExMzUtZjYyYy00ZDcyLThiODMtMjQwZDc0M2Y1ZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzIwVDE0MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNDA3OWY0YTZkMmQyZDE0Y2VlMjMyOTQ1ZThmODI2MDg5ZDhlYmYzNWE5ODhmOGMzNTkzNGRjNzE2MGQ1NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dSEdv45u2t_Iv0mUnClByoYe9tnpolXD2SSGghtc4bk)

The `default/oauth2-proxy` part tells me that Argo CD thinks the _Application_ is in the default namespace, not the _resource_. That's weird.

**Comment by rumstead** [comment]
https://github.com/user-attachments/assets/615ba99c-d927-46bd-8893-6e8d6d0bd5aa

this is working for me using default too 😕

**Comment by crenshaw-dev** [comment]
@kaiburjack can you do `kubectl get app -n default`?

I think the only way we get this error is if 1) the API request has `appNamespace=default` and 2) there's an Application CR in the `default` namespace called `oauth2-proxy`.

**Comment by kaiburjack** [comment]
> can you do kubectl get app -n default?

Of course: Output:
```
➜  ~ kubectl get app -n default
No resources found in default namespace.
➜  ~ 
```
We do not deploy any apps in any namespace other than "argocd".

**Comment by kaiburjack** [comment]
Another thing, maybe, that could be relevant: We disable deploying the argocd-secret secret via:
```
configs:
  secret:
    createSecret: false
```
because we don't want each rollout to generate a new server private key (which will invalidate the signature of all issued JWT tokens for project roles - which we use for pipelines to allow them to make ArgoCD API calls).

**Comment by kaiburjack** [comment]
Maybe someone wants to have a _direct_ chat/call with me? (dunno whether that is appropriate to ask here?)

**Comment by kush-work** [comment]
We are also having the same trouble and we had downgraded to 2.14.5 to fix the issue.

**Comment by crenshaw-dev** [comment]
@kaiburjack are you on CNCF Slack? Hit me up there, and we can hop on a call to take a look.

**Comment by kaiburjack** [comment]
> are you on CNCF Slack? Hit me up there, and we can hop on a call to take a look.

No. I am not currently. How do I get there? What do I need to do?

**Comment by crenshaw-dev** [comment]
I read the code wrong, `default` in `default/oauth2-proxy` is the project, not the app namespace.

**Comment by rumstead** [comment]
I was able to reproduce it locally. The cluster needs to be anything but the "in-cluster". 

https://github.com/user-attachments/assets/1d4c3425-3b2b-469b-a8d7-6059876b770e

**Comment by PatrickSpies** [comment]
We´re using `in-cluster (https://kubernetes.default.svc)` but also experiencing this issue. But we´re using apps in any namespace, maybe this produces the issue too?!

**Comment by crenshaw-dev** [comment]
Do y'all have `permitOnlyProjectScopedClusters` enabled in the relevant AppProjects?

**Comment by kaiburjack** [comment]
> Do y'all have permitOnlyProjectScopedClusters enabled in the relevant AppProjects?

I sure don't.

**Comment by kush-work** [comment]
I don’t have that too.

**Comment by crenshaw-dev** [comment]
Thanks. Was a long shot, I know the function that's returning `false`, I just haven't yet figured out why.

**Comment by crenshaw-dev** [comment]
I can reproduce it if I specify `in-cluster` in the app destination by name instead of URL.

The AppProject has a `*` for destination Server but not for destination Name.

I think the old informer was running inference logic to populate the destination Server field with a URL, but the new informer isn't doing so.

(I removed all that inference logic for 3.0, because it causes weird bugs like this one.)

**Comment by crenshaw-dev** [comment]
You'll only encounter this bug when your Application's `spec.destination` specifies something different from your AppProject. i.e. your app specifies a URL while your AppProject specifies a cluster name, or your app specifies a cluster name while your AppProject specifies a cluster URL. This explains why Ryan and I weren't able to reproduce it initially: our app destinations precisely matched our AppProject configs.

**Comment by tutman96** [comment]
I have an AppProject (default) that references
```yaml
  destinations:
    - namespace: '*'
      server: '*'
```
whereas my Application references
```yaml
destination:
  namespace: iot
  name: in-cluster
```
If you need another test case to validate, this seems to hit the same issue.

**Comment by tutman96** [comment]
Yup, perfect!

**Comment by andrey-parkhomets** [comment]
> That ^ PR should fix it. But I think we'll want e2e tests and potentially fixes for other features like extensions ([issue reported on Slack](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1742486896580459)) and deep links.
> 
> 3.0 shouldn't have this issue.

Hi there!
 once project changed to:
```yaml
  destinations:
    - name: in-cluster
      namespace: '*'
```
both errors: reported by this issue and with metrics reported in slack are gone.
