### ISSUE TITLE
ArgoCD > 2.13.0 Fails to Resolve `targetRevision: x` in some Helm Charts

### ISSUE THREAD

**Issue by josecsotomorales** [argoproj/argo-cd#22404]
## Checklist
* [x] I've searched in the docs and FAQ for my answer: [ArgoCD FAQ](https://bit.ly/argocd-faq).
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

---

## **Describe the Bug**
After upgrading from **ArgoCD 2.13.0** to **2.14.6**, my Helm-based application fails to resolve `targetRevision: x`, resulting in the error:

```
error="constraint not found in index"
```

This issue **did not occur in 2.13.0**.

When running:
```sh
argocd app manifests develop-app
```
ArgoCD **returns `null` instead of valid manifests**, indicating a failure in Helm version resolution.

---

## **To Reproduce**
1. Upgrade ArgoCD from **2.13.0** to **2.14.6**.
2. Apply the following **Helm-based Application**:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://develop.artifactory.io/artifactory/helm
    targetRevision: x  # ArgoCD fails to resolve this
    helm:
      valueFiles:
        - client.values.yaml
    chart: develop-stack
  destination:
    server: https://localhost
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

3. Run:
   ```sh
   argocd app sync develop-app
   ```

4. Observe the error in ArgoCD UI or CLI:
   ```sh
   error="constraint not found in index"
   ```

5. Run:
   ```sh
   argocd app manifests develop-app
   ```
   **Expected:** Rendered manifests  
   **Actual:** Returns `null`  

6. Manually setting a specific version **works**, but `targetRevision: x` fails:
   ```sh
   argocd app set develop-app --revision 2025.3.191440
   argocd app sync develop-app
   ```

---

## **Expected Behavior**
- `targetRevision: x` should resolve to the latest available Helm chart version.
- `argocd app manifests develop-app` should **return valid manifests**, not `null`.
- This behavior worked fine in **ArgoCD 2.13.0** but is broken in **2.14.6**.

---

## **Screenshots**

<img width="1506" alt="Image" src="https://github.com/user-attachments/assets/47c64a57-76df-4906-913a-a27ad9292bd8" />

<img width="2334" alt="Image" src="https://github.com/user-attachments/assets/931199ad-2058-4355-b477-2c01d4114bff" />

### **ArgoCD Repo Server Logs**
```shell
kubectl logs -n argocd -l app.kubernetes.io/name=argocd-repo-server
```
```log
error="constraint not found in index"
time="2025-03-19T01:58:06Z" level=error msg="finished unary call with code Unknown"
grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService
```

---

## **Additional Information**
- The Helm repository **contains the expected versions** and is accessible.
- Manually setting a specific version **works**, but `targetRevision: x` fails.

---

### 🚀 **Request for Guidance**
Is this an **intended change** in ArgoCD 2.14.6 or a **regression**?  
I would appreciate any insights on restoring wildcard resolution for `targetRevision: x`.

**Comment by josecsotomorales** [comment]
Here's an example of the repo's index.yaml` file:

```yaml
apiVersion: v1
entries:
  develop-app:
  - apiVersion: v2
    created: 2025-03-19T02:47:55.681136998Z
    description: A Helm chart for Kubernetes
    digest: 2338e17a697c234028d33912614124a8e31bf23ebd7521d89069339293498cfc
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0319.0247.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0319.0247"
  - apiVersion: v2
    created: 2025-03-18T18:15:30.561236891Z
    description: A Helm chart for Kubernetes
    digest: 9a3bf73a12d5c2342e67989bde125c4a13df3b6a9023456fa8920c314d0fd87b
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0318.1815.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0318.1815"
  - apiVersion: v2
    created: 2025-03-17T10:30:45.121893572Z
    description: A Helm chart for Kubernetes
    digest: a8e3bf23ebd7521d89069339293498cfc2338e17a697c234028d33912614124a
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0317.1030.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0317.1030"
  - apiVersion: v2
    created: 2025-03-16T08:05:22.987654321Z
    description: A Helm chart for Kubernetes
    digest: 4e17a697c234028d33912614124a8e31bf23ebd7521d89069339293498cfc23
    name: develop-app
    urls:
    - https://develop.artifactory.io/artifactory/helm/develop-app-2025.0316.0805.tgz
    type: application
    appVersion: "1.16.0"
    version: "2025.0316.0805"
generated: 2025-03-19T02:49:04.121378572Z
```
