### ISSUE TITLE
Can't add https-based HELM Repos due to upstream bug in HELM

### ISSUE THREAD

**Issue by dersimn** [argoproj/argo-cd#22445]
Specifying HELM repos in ArgoCD like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  destination:
    namespace: nginx-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 19.0.2
```

Is resulting in an Error like this:

![Image](https://github.com/user-attachments/assets/99aa9970-a243-4a4b-91bc-52bb8ed8b4d1)

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = error fetching chart: failed to fetch chart: failed to get command args to log: `helm pull --destination /tmp/eeed361a-372a-4c98-a3b0-a1f5502840a2 --version 19.0.2 --repo https://charts.bitnami.com/bitnami nginx` failed exit status 1: Error: invalid_reference: invalid tag
```

Trying to replicate the error locally I found that HELM versions `3.16.3`, `3.16.4` are both having the same issue locally:

```
b47c07527470:/# tar xfz helm-v3.16.4-linux-arm64.tar.gz 
b47c07527470:/# cd linux-arm64/
b47c07527470:/linux-arm64# ./helm pull --version 19.0.2 --repo https://charts.bitnami.com/bitnami nginx
Error: invalid_reference: invalid tag
```

It was fixed in `3.17.0`:

```
b47c07527470:/# tar xfz helm-v3.17.0-linux-arm64.tar.gz 
b47c07527470:/# cd linux-arm64/
b47c07527470:/linux-arm64# ./helm pull --version 19.0.2 --repo https://charts.bitnami.com/bitnami nginx
b47c07527470:/linux-arm64# ls -l
total 55432
-rw-r--r-- 1 1001  128    11373 Jan 15 21:27 LICENSE
-rw-r--r-- 1 1001  128     3699 Jan 15 21:27 README.md
-rwxr-xr-x 1 1001  128 56688792 Jan 15 21:26 helm
-rw-r--r-- 1 root root    49764 Mar 22 10:41 nginx-19.0.2.tgz
```

Recent ArgoCD Chart version `3.35.4` (deploys app version `2.14.7`) are using an older version of HELM. You'd need to upgrade HELM cli to fix this issue I guess.

Version details:

```
Argo CD v2.14.7+d107d4e
Build Date 2025-03-19T17:07:48Z
Go Version go1.23.3
Go Compiler gc
Platform linux/arm64
jsonnet v0.20.0
kustomize v5.4.3 2024-07-19T16:40:33Z
Helm v3.16.3+gcfd0749
kubectl v0.31.0
```
