### ISSUE TITLE
`argocd app diff --revision` ignores hard refresh

### ISSUE THREAD

**Issue by thejoeejoee** [argoproj/argo-cd#22463]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using `argocd app diff` with custom `--revision` and `--hard-refresh`, manifests are taken from cache and not refreshed.

**To Reproduce**

With following application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    name: not-relevant
    namespace: default
  project: default
  source:
    repoURL: repository.org
    chart: my-app
    helm: {}
    targetRevision: 0.0.42
```

and following CLI is called:

```
argocd app diff my-app --revision 0.0.42 --hard-refresh
```

The repo server is returning the diff with `targetRevision` and previously cached state of `0.0.42` -- e.g. even if the `0.0.42` revision has changed, the cached version is used for diff (with no respect to `--hard-refresh`). 

**Expected behavior**

No cached response is returned.

**Screenshots**

**Version**

```shell
❯ argocd version
argocd: v2.14.7+d107d4e
  BuildDate: 2025-03-19T19:56:45Z
  GitCommit: d107d4e41a9b8fa792ed6955beca43d2642bad26
  GitTreeState: clean
  GoVersion: go1.24.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.14.2+ad27246
```

**Logs**

```
time="2025-03-24T14:54:33Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:repository.org,Path:,TargetRevision:0.0.42,Helm:&ApplicationSourceHelm{ValueFiles:[],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,Namespace:,KubeVersion:,APIVersions:[],SkipTests:false,SkipSchemaValidation:false,},Kustomize:nil,Directory:nil,Plugin:nil,Chart:my-app,Ref:,Name:,}/0.0.42"
```
