### ISSUE TITLE
resourceIgnoreDifferences - expressions are ignored

### ISSUE THREAD

**Issue by hiimheregit** [argoproj/argo-cd#22491]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When setting `resourceIgnoreDifferences` in the argocd-cm with specific expressions and pointers, ArgoCD ignores every resource of the kind `[kind]`.

In our case, we wanted ArgoCD to ignore ConfigMaps with a specific name and a specific pointer.

Also, we tried multiple other things :  ServerSideDiff, overriding the ignoreDifferences just for that app. None of it worked.

Syncing the resource did work, the only thing is ArgoCD didn't put the resource in "out of sync" state.

**To Reproduce**

We are running ArgoCD v2.13.1 through the openshift gitops operator.

The config block we added :

```
  resourceIgnoreDifferences:
    resourceIdentifiers:
      - customization:
          jqPathExpressions:
            - .metadata | select(.name == "abcdef")
          jsonPointers:
            - /data
        kind: ConfigMap
```

**Expected behavior**

We would expect ArgoCD to ignore differences only for the selected ConfigMap (e.g. the configMap named `abcdef` only for the `data` part) resource (did we make a mistake in the config?). What we noticed is that ArgoCD "ignored" diffs in any of the configmaps (although we didn't notice immediately because we mostly use Kustomize and in rarer cases we use Helm, as in this one).

**Version**

```shell
argocd: v2.13.1+af54ef8
  BuildDate: 2024-12-11T18:55:26Z
  GitCommit: af54ef8db5adfa77a08d4d05b1318a2198084c22
  GitTreeState: clean
  GoVersion: go1.22.9 (Red Hat 1.22.9-1.module+el8.10.0+22500+aee717ef)
  Compiler: gc
  Platform: linux/amd64
  ExtraBuildInfo: {Vendor Information: Red Hat OpenShift GitOps version: v1.15.0}
```
