### ISSUE TITLE
ArgoCD UI not updating in real time

### ISSUE THREAD

**Issue by sammy-sandhu** [argoproj/argo-cd#22492]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Anytime I want to sync/refresh an app or restart/delete a resource from the ArgoCD UI, nothing happens in the UI until I do a hard refresh of the browser. I also can't view any logs. Things were working fine until I upgraded the version to the latest and threw it behind an application loadbalancer. I followed the AWS ingress documentation from the website. I've tried to search stack overflow and the other issues to see how I can fix this problem but have had no luck. Any assistance would be greatly appreciated. I have a video of the problem but it won't upload. 

**Expected behavior**

The UI should update anytime changes are made or an event is triggered from the UI.

**Screenshots**

**Version**

```
argocd: v2.14.7+d107d4e
  BuildDate: 2025-03-19T17:32:13Z
  GitCommit: d107d4e41a9b8fa792ed6955beca43d2642bad26
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.14.6+fe2a6e9
  BuildDate: 2025-03-18T13:26:42Z
  GitCommit: fe2a6e91b61299a476cc25948cbb53eb1ca1cc14
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0

```

**Logs**

```
Paste any relevant application logs here.
```

**ingress service**
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC # This tells AWS to send traffic from the ALB using GRPC. Plain HTTP2 can be used, but the health checks wont be available because argo currently downgrade non-grpc calls to HTTP1
  labels:
    app: argogrpc
  name: argogrpc
  namespace: argocd
spec:
  ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
```

***ingress***
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/backend-protocol: HTTPS  # ALB to ArgoCD uses HTTP
    alb.ingress.kubernetes.io/subnets: <my subnets>
    alb.ingress.kubernetes.io/certificate-arn: <my aws cert>
    # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
    alb.ingress.kubernetes.io/conditions.argogrpc: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  name: argocd
  namespace: argocd
spec:
  ingressClassName: alb
  rules:
  - host: argocd.mydomain.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: argogrpc # The grpc service must be placed before the argocd-server for the listening rules to be created in the correct order
            port:
              number: 443
        pathType: Prefix
      - path: /
        backend:
          service:
            name: argocd-server
            port:
              number: 443
        pathType: Prefix
  tls:
  - hosts:
    - argocd.mydomain.com
```
