### ISSUE TITLE
Source Hydrator hydrateTo triggers hydrates every few second

### ISSUE THREAD

**Issue by procinger** [argoproj/argo-cd#22506]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
ArgoCD 2.14.8+a7178be
Helm Chart 7.8.14

I am currently testing the new feature of the source hydrator in a playground repository. So far this application manifest works without any problems
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: source-hydrator
  namespace: argo-cd
spec:
  destination:
    server: https://foo.svc
    namespace: source-hydrator
  project: default
  sourceHydrator:
    drySource:
      path: kustomize
      repoURL: git@company-stuff.com/foo
      targetRevision: HEAD
    syncSource:
      path: .
      targetBranch: environment/dev
```

As soon as i add the `hydrateTo` to the manifest, argocd tries to hydrate the branch every  ~5 second and i get everytime an error message in the bottom right corner.

![Image](https://github.com/user-attachments/assets/9c97bfb2-1644-4021-8b33-4b9e17a6f872)

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: source-hydrator
  namespace: argo-cd
spec:
  destination:
    server: https://foo.svc
    namespace: source-hydrator
  project: default
  sourceHydrator:
    drySource:
      path: kustomize
      repoURL: git@company-stuff.com/foo
      targetRevision: HEAD
    syncSource:
      path: .
      targetBranch: environment/dev
    hydrateTo:
      targetBranch: environment/dev-next
```

I followed the steps from this [guide](https://argo-cd.readthedocs.io/en/stable/user-guide/source-hydrator/) and activated the commit server in an existing argocd installation.

**Expected behavior**

It should only hydrate if changes are really present and without an error message

**Version**
```
argocd-server: v2.14.8+a7178be
  BuildDate: 2025-03-24T20:54:41Z
  GitCommit: a7178be1c1ebe08a61e326037173d2ef979cb3f8
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```
