### ISSUE TITLE
Clarify docs about Helm valueFiles from the same Git repository

### ISSUE THREAD

**Issue by dersimn** [argoproj/argo-cd#22522]
There is a docs section about [Helm value files from external Git repository](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository) explaining best-practice to include a `values.yaml` that's hosted in some *external* Git repository (other than the one where the ArgoCD Application is specified).

Please also add an example for a best practice to use a local `values.yaml` file *within* the directory structure of the ArgoCD Application:

```
|-- argocd
|   `-- nginx-app.yaml
`-- nginx
    `-- values.yaml
```

File `argocd/nginx-app.yaml` (in Git repo `http://git.example.com/argocd/main-repo`):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: nginx
      targetRevision: 19.0.1
      helm:
        valueFiles:
          - $argo-main-repo/nginx/values.yaml
    - repoURL: http://git.example.com/argocd/main-repo  # this is the same we're reading this yaml from
      ref: argo-main-repo
```

Is this really the best practice to include a `values.yaml` from a sibling directory of the ArgoCD App itself or is there a better way without having to specify our own Git repo url again?  
In case of migration etc. it's quite an easy fix to search&replace all the urls, but idk - sounds like a clear "don't repeat yourself" violation to me.
