### ISSUE TITLE
Native helm support

### ISSUE THREAD

**Issue by parisnakitakejser** [argoproj/argo-cd#22535]
When using ArgoCD with Helm charts, you might expect it to work like `helm upgrade -i`. However, ArgoCD actually runs `helm template` before applying the chart, which can lead to confusion.

This behavior can cause unexpected issues, often requiring an additional tool in your GitOps stack. The key missing feature before fully transitioning to ArgoCD as your primary deployment tool is native Helm chart support.

To see this in action, try installing GitLab CE using Helm first, then attempt the same installation with ArgoCD. You'll notice that it gets stuck. Just remember to clean up the Helm installation beforehand—otherwise, ArgoCD won’t get stuck as expected.

```shell
helm repo add gitlab http://charts.gitlab.io/
helm install my-gitlab gitlab/gitlab --version 8.10.1
```

Now do the ArgoCD way

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: flux-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  source:
    chart: gitlab
    repoURL: http://charts.gitlab.io/
    targetRevision: 8.10.1
    helm:
      releaseName: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

I propose fixing this by allowing ArgoCD to recognize when it's handling a Helm chart and automatically compare it against the updated version, similar to how GitHub manages changes.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: flux-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  source:
    chart: gitlab
    repoURL: http://charts.gitlab.io/
    targetRevision: 8.10.1
    helm:
      releaseName: gitlab
      native: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

So if `native=true`, ArgoCD should behave like a real Helm chart, allowing additional features like rollback, timeouts, and more. This is a crucial missing feature in ArgoCD—I have no idea how people work without it! 😊
