### ISSUE TITLE
Document the search order of `jsonnet.libs`

### ISSUE THREAD

**Issue by VannTen** [argoproj/argo-cd#22532]
# Summary

Directory application with *.jsonnet files can use `libs` to add path when using `import` in jsonnet.
This is an array, however, the resolution order is not documented.

# Motivation

I'm currently working on an applicationset with applications sourced from helm, raw manifests, kustomize Kustomization and jsonnet application, targeting multiple cluster (deploying mostly "infra" like metrics, logs collection, etc)
The expectation is to allow the source repo to override at several level (currently I have `global def < zone < prod level < single cluster`) 

To implement this for jsonnet apps, I'm going with an application template looking roughly like this:

```
        template:
          metadata: {}
          spec:
            destination: {}
            project: default
            source:
              repoURL: "https://REDACTED/gitops/clusters-infra.git"
              path: "{{ values.application }}"
              targetRevision: main
            directory:
              recurse: false
              include: "*.jsonnet"
              jsonnet:
                libs:
# values is sourced from a merge/matrix generator with git files generator and cluster generator as input
                - jsonnet/vendor # for vendored dependencies
                - jsonnet/lib # for common code
                - "{{ values.application }}/zones/{{ values.zone }}"
                - "{{ values.application }}/prlvl/{{ values.prlvl }}"
                - "{{ values.application }}/clusters/{{ values.cluster }}"
                # Should allow to selectively update versions
                # Should not be abused to have different versions of dependency in each vendor/ directory
                tlas:
                - name: prlvl
                  value: "{{ values.prlvl }}"
                - name: zone
                  value: "{{ values.zone }}"
                - name: cluster
                  value: "{{ values.cluster }}"
                - name: "{{ values.version }}"
```

`jsonnet/lib` will hold placeholders for the overrides, (`cluster/zone/prlvl.libsonnet` with content = ` { } `.

Application source will be expected to be define with something like that:

```jsonnet
local cluster = import 'cluster.libsonnet';
local zone = import 'zone.libsonnet';
local prlvl = import 'prlvl.libsonnet';

// whatever imports and definition are needed

final_object + zone + prlvl + zone // the way to combine the override should not be hardcoded, I'll leave that in the app definition.
```

The idea is that the overrides are optional, so an application does not have to define them, and in that case the `jsonnet/lib` provide a "no-op" overrides.

But this depends on the search path for jsonnet import, (actual overrides should win over jsonnet/lib).

I'm going to test and report back, but since the jsonnet cli for instance has 2 way to indicate libs dirs (`-J` or `JSONNET_PATH` ) with inverse precedence order, it would be a good thing to document it for argocd.
