### ISSUE TITLE
ArgoCD failing to template complex variable map of lists in get function

### ISSUE THREAD

**Issue by igoratencompass** [argoproj/argo-cd#22538]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

I have the following variable:
```
myOptions:
  option-1:
    - mypath/some-hash-1
    - mypath/some-hash-2
  option-2:
    - mypath/some-hash-3
    - mypath/some-hash-4
```
that I'm getting an error in ArgoCD for the following get function:
```
{{- $options := get .Values.myOptions .Values.option }}
```
in one of the manifests:
```
failed exit status 1: Error: template: at <.Values.myOptions>: wrong type for value; expected map[string]interface {}; got interface {} Use --debug flag to render out invalid YAML
```
I can't reproduce this locally, `helm template . --debug --set option=option-1` executes just fine. Any idea what might be the problem?

**To Reproduce**

The get function call is given above.

**Expected behavior**

ArgoCD helm template should not fail parsing the var.

**Version**

```shell
v2.13.4+102853d
```

**Logs**

```
Paste any relevant application logs here.
```
