### ISSUE TITLE
Applicationset with source.plugin templatepatch breaks applications frontend page

### ISSUE THREAD

**Issue by Dutchy-** [argoproj/argo-cd#22545]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using an applicationset with a `templatePatch` to override `source.plugin`, the applications page in the frontend breaks with this error:

```
Stacktrace:

TypeError: Cannot read properties of undefined (reading 'targetRevision')
    at cP (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:1834665)
    at Qa (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:569442)
    at Es (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:615400)
    at Sl (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:608184)
    at xl (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:608109)
    at hl (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:605142)
    at https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:556862
    at o.14099.t.unstable_runWithPriority (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:631967)
    at qo (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:556571)
    at Zo (https://<redacted>/argocd/main.67d3d35d60308e91d5f4.js:2:556807)
```

The applicationset works properly, it is just the frontend that breaks. Deleting the applicationset will restore functionality.

**To Reproduce**

Deploy this applicationset:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-test
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: nonexistent-1
            deploy: helm
          - app: nonexistent-2
  template:
    metadata:
      name: "applicationset-test-{{.app}}"
    spec:
      project: "default"
      source:
        repoURL: "https://redacted/redacted.git"
        path: "apps/{{.app}}/overlays/test"
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
      source:
        {{- if (eq (or .deploy "kustomize") "helm") }}
        plugin:
          name: kustomize-build-with-helm
        {{- end }}
```

Then go to the applications page (`/applications`) in the frontend. You will see the stacktrace.
The elements do not even have to exist in the git repo for the problem to occur, it just breaks immediately. The problem is the same wether or not they exist.

**Expected behavior**

The `/applications` page is able to handle these applications normally.

**Version**

```shell
argocd@argocd-server-6755cf496d-vw6fl:~$ argocd version
argocd: v2.14.7+d107d4e
  BuildDate: 2025-03-19T17:07:48Z
  GitCommit: d107d4e41a9b8fa792ed6955beca43d2642bad26
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified           
```
