### ISSUE TITLE
Setting allowEmpty: false explicitly results in OutOfSync loop

### ISSUE THREAD

**Issue by mike-code** [argoproj/argo-cd#22546]
```
argocd: v2.14.8+a7178be
  BuildDate: 2025-03-24T20:54:41Z
```

I have following root application definition (ie. yaml file in a git repository)

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: TheApp
  namespace: argocd
spec:
  syncPolicy:
    automated:
        allowEmpty: false
        prune: true
        selfHeal: true
  sources:
    ...
```

which has both self-healing, but also one of the resources of this (ie. TheApp) application is the application (ie. TheApp) itself. 

However, the **live manifest** of this app looks like so
```
[...]
syncPolicy:
  automated:
    prune: true
    selfHeal: true
```

as you can see, the `allowEmpty: false` line is not there. I assume that's because `false` is the default setting and hence I don't _have to_ set it explicitly, however for the sake of clarity in the application definition file, I _prefer_ to have it explicitly set to `false`.

Now, the issue is that since live manifest doesn't have this line while the manifest file does, it'll put application in `OutOfSync` state. This will repeat over and over which is undesirable.

**Comment by rumstead** [comment]
while imperfect, have you tried ignoring the difference? https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration

**Comment by u-kai** [comment]
@mike-code @rumstead 
I’m also facing the same issue. While using `ignoreDifferences` helps avoid the `OutOfSync` status, it also means I can no longer detect changes to that specific field.

I believe the root cause of this behavior is that fields marked with `omitempty` don't appear in the API server response when they are set to their default values. As a result, Argo CD sees a difference between the live and desired state.

To address this, I’d like to propose a new feature like the following:

```yaml
ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/template/spec/containers/0/securityContext/allowPrivilegeEscalation
    defaultValueOnly: true
```
This would allow us to ignore fields that are missing due to defaulting, without fully disabling diffs for that field.
