### ISSUE TITLE
Ignore Second Generator Matrix Failures

### ISSUE THREAD

**Issue by CamiloValderruten** [argoproj/argo-cd#22550]
# Summary

When working with Matrix Generators, the first Generator will be generating params that will be used to generate the params in the second generator. We noticed that while the first generator creates X number of params, one of more of them might cause the second one to fail. 

# Motivation

In our case, we have a Git generator that gets all the Directories under the `/apps` directory in a repo. This produces a list of 100 directories. The second generator is a Pull Request generator which uses the results from the first as the repositories to get Pull Requests from. It is possible that one of the 100 directory names (repository names on the second generator) returns a 404 because the repo doesn't exists. 

One solution would be to just remove the directory from the `/apps` directory, but keeping this dynamic list up-to-date gets more difficult as the number of directories increases and the number of Git repos get created or deleted. 

# Proposal

Given that the Generator fails completely if one of the 100 params provided is incorrect, we propose a flag on the Matrix generator to continue when the second generator fails.

```yaml
spec:
  goTemplate: true
  generators:
    - matrix:
        ignoreSecondGeneratorFailure: true
        generators:
          - git:
              directories:
                - path: apps/*/stage
              repoURL: https://github.com/my-org/monorepo.git
              revision: HEAD
          - pullRequest:
              github:
                owner: my-org
                repo: '{{index .path.segments 1 }}'
```
