### ISSUE TITLE
Reference in argocd-secret Secret get replaced by secret value when a argocd-server pod gets deleted

### ISSUE THREAD

**Issue by rtomadpg** [argoproj/argo-cd#22588]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Via an ExternalSecret I have a k8s Secret which contains the github webhook secret. This secret looks like:
```
apiVersion: v1
data:
  secret: REDACTED
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-github-webhook-secret-ext
  namespace: argocd
type: Opaque
```

I reference this secret from Secret `argocd-secret` with `webhook.github.secret: $argocd-github-webhook-secret-ext:secret`. And this works.

BUT ... when I delete a "argocd-server" pod the reference in Secret `argocd-secret` is replaced by the secret value. In other words, the reference gets removed, causing drift and breaks future secret rotations (the ref is gone, so ArgoCD will never read fresh value).

In more details, I started this oneliner before the pod delete:
```
$ while :; do date;k -n argocd get secret/argocd-secret -ojson|jq -r '.data["webhook.github.secret"]|@base64d';sleep 3;done
```
... which prints the "webhook.github.secret" value from the `argocd-secret` Secret, every 3 seconds.

Here is a short log. It's pretty clear when the "argocd-server" pod gets killed as the value gets replaced:
```
Mon  7 Apr 2025 15:48:14 CEST
$argocd-github-webhook-secret-ext:secret
Mon  7 Apr 2025 15:48:17 CEST
$argocd-github-webhook-secret-ext:secret
Mon  7 Apr 2025 15:48:21 CEST
$argocd-github-webhook-secret-ext:secret
Mon  7 Apr 2025 15:48:25 CEST
some-secret-not-really
Mon  7 Apr 2025 15:48:28 CEST
some-secret-not-really
Mon  7 Apr 2025 15:48:32 CEST
some-secret-not-really
Mon  7 Apr 2025 15:48:36 CEST
some-secret-not-really
...
```

**To Reproduce**

- Create this k8s Secret:
```
apiVersion: v1
stringData:
  secret: some-secret-not-really
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-github-webhook-secret-ext
  namespace: argocd
type: Opaque
```
- Ensure k8s Secret `argocd-secret` has:
```
stringData:
  webhook.github.secret: $argocd-github-webhook-secret-ext:secret
```
- Check the secret value with command below. The output should be "$argocd-github-webhook-secret-ext:secret".
```
kubectl -n argocd get secret/argocd-secret -ojson|jq -r '.data["webhook.github.secret"]|@base64d'
```
- Delete a "argocd-server" pod
- Check the secret value with aforementioned command. You'll see the output is changed to "some-secret-not-really"

**Expected behavior**

"argocd-server" should NOT update secret references.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.14.5+f463a94
  BuildDate: 2025-03-11T03:15:56Z
  GitCommit: f463a945d57267e9691cede37021d9ddc5994f36
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

I've checked the "argocd-server" logs before/after pod kill and there is nothing mentioned.
