### ISSUE TITLE
Diff fails with Object 'Kind' is missing in '{} when manually applying a resource then creating an application to track it

### ISSUE THREAD

**Issue by pjiang-dev** [argoproj/argo-cd#22595]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I am noticing this error Object 'Kind' is missing in '{} when manually applying a resource, then creating an app in argocd to track the same resource.

 I tested using the public example app

**To Reproduce**

1. Apply a resource manually
```
   kubectl create -f https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-deployment.yaml --save-config
deployment.apps/guestbook-ui created
```
Deploy the app that tracks the same resource we created:
```
kubectl apply -f - <<EOF
   apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: guestbook
     namespace: argocd
   spec:
     project: default
     source:
       repoURL: https://github.com/argoproj/argocd-example-apps.git
       targetRevision: master
       path: guestbook
     destination:
       server: https://kubernetes.default.svc
       namespace: default
EOF
application.argoproj.io/guestbook created
```
Run any argocd app diff - they all fail with Object Kind is missing
```
argocd app diff guestbook 
FATA[0000] Object 'Kind' is missing in '{}'         
argocd app diff guestbook --server-side-generate
FATA[0000] Object 'Kind' is missing in '{}'     
argocd app diff guestbook --revision master
FATA[0000] Object 'Kind' is missing in '{}'         
```

**Expected behavior**

Diff shows a valid response

**Screenshots**

**Version**

```shell
argocd: v2.14.9+38985bd.dirty
  BuildDate: 2025-04-02T23:02:54Z
  GitCommit: 38985bdcd6c3b031fb83757a1fb0c39a55bf6a24
  GitTreeState: dirty
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
