### ISSUE TITLE
Progressive Sync: Retry limit configuration not respected

### ISSUE THREAD

**Issue by lalastraszy** [argoproj/argo-cd#22639]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When using Progressive Sync to deploy applications sequentially across multiple clusters with `syncPolicy.retry.limit`: 0, the system ignores the retry limit setting during deployment errors. Instead of stopping after reaching the limit, it continues retrying indefinitely. In our current setup, we have two applications—the first deployment includes a pre-sync job, while the pre-sync job in the second application is skipped. When we intentionally introduce an error to the deployment manifest, we observe the following behavior:
- The pre-sync job runs and completes successfully for the first application
- The first application enters a sync error state due to deployment configuration issues
- ArgoCD ignores the retry limit and keeps attempting to resync
- This creates an endless loop of pre-sync job executions for the first application
Meanwhile, the sync of the second application remains suspended as expected.

Note: We have set up GH webhooks. 

**To Reproduce**

1. Create a sample app containing a pre-sync job and a deployment
```
apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: print-message
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo 'This is a preSync job'; exit 0"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop: [ "ALL" ]
          seccompProfile:
            type: "RuntimeDefault"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-c
  labels:
    app.kubernetes.io/name: sample-c
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: sample-c
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-c
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-c
    spec:
      containers:
      - name: sample-c
        image: sample-c
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: "RuntimeDefault"
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 3
          failureThreshold: 3

```
2. Set up applicationSet with Progressive Sync (configure `syncPolicy.retry.limit: 0`):
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-c-application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      - cluster: bravo
        env: sandbox
      - cluster: delta
        env: sandbox
  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: cluster
          operator: In
          values:
          - bravo
      - matchExpressions:
        - key: cluster
          operator: In
          values:
          - delta
  template:
    metadata:
      name: '{{.cluster}}-{{.env}}-sample-c'
      labels:
        cluster: '{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/....
        targetRevision: main
        path: 'services/sample-c/clusters/{{.cluster}}/sandbox'
      destination:
        name: '{{.cluster}}'
        namespace: '{{.env}}-sample-c'
      syncPolicy:
        retry:
          limit: 0
```
3. Introduce a deployment error (for example, set resource requests higher than limits)⁠

**Expected behavior**

When `syncPolicy.retry.limit: 0` is set, ArgoCD should:
- Stop retrying after the initial sync failure
- Not re-run the pre-sync job
- Maintain failed sync state until manual intervention

**Screenshots**

**Version**

```shell
argocd: v2.14.3+71fd4e5
  BuildDate: 2025-02-28T18:56:13Z
  GitCommit: 71fd4e501d0d688ab0d70cd649fbf5f909cff12b
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/arm64
```

**Logs**

```
Paste any relevant application logs here.
```
[applications-logs.txt](https://github.com/user-attachments/files/19699866/applications-logs.txt)
