### ISSUE TITLE
`helm dependency build` fails if subchart is from private repository

### ISSUE THREAD

**Issue by waxb** [argoproj/argo-cd#22663]
**Describe the bug**

Our applications' source is git where we are checking out charts with dependency charts not included in the repository hence `helm dependency build` running. Since we are hitting the rate limit for Docker Hub we need to go authenticated but the dependency charts are unreachable because it seems like credentials aren't passed down.

If I create an application which is directly consuming the Helm OCI repo as source it works, therefore the credentials aren't passed (correctly) for the dependency build step.

**To Reproduce**

non-working application:
```yaml
project: test-project
source:
  repoURL: local.repo.git
  path: charts/waxb
  targetRevision: main
  helm:
    passCredentials: true
    ....
....
```
corresponding chart (`charts/waxb`):
```yaml
apiVersion: v2
name: waxb
description: test chart from repo waxb0
type: application
version: 1.0.0

dependencies:
  - name: minimal-test-chart
    version: 0.1.0
    repository: oci://registry-1.docker.io/waxb0
```

working application (direct source):
```yaml
project: test-project
source:
  repoURL: registry-1.docker.io
  targetRevision: 0.1.0
  helm:
    passCredentials: true
  chart: waxb0/minimal-test-chart
```

Also if I commit the dependency chart to my repository it works.

**Expected behavior**

Have an authenticated `helm dependency build` if my application's source is git and it has a dependency chart in a private repository.

**Version**

```json
{
    "Version": "v2.14.8+a7178be",
    "BuildDate": "2025-03-24T20:54:41Z",
    "GitCommit": "a7178be1c1ebe08a61e326037173d2ef979cb3f8",
    "GitTreeState": "clean",
    "GoVersion": "go1.23.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.4.3 2024-07-19T16:40:33Z",
    "HelmVersion": "v3.16.3+gcfd0749",
    "KubectlVersion": "v0.31.0",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): failed to build helm dependencies: failed to build dependencies: failed to get command args to log: `helm dependency build` failed exit status 1: Error: could not download oci://registry-1.docker.io/waxb0/minimal-test-chart: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
