### ISSUE TITLE
Unable to deploy a Helm chart that contains only resources with Helm hooks

### ISSUE THREAD

**Issue by lucaspouzac** [argoproj/argo-cd#22694]
**Describe the bug**

When deploying via ArgoCD a Helm chart containing two resources (one Job and one ServiceAccount), each with Helm hook annotations, ArgoCD does not perform any deployment (as seen in the screenshot). However, if I add a third resource without a Helm hook, the deployment works.

![Image](https://github.com/user-attachments/assets/9523ca4d-290f-493a-bc21-635cacf9bffe)

**To Reproduce**

Try to deploy with helm these 2 resources.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "charts.fullname" . }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: {{ template "charts.fullname" . }}
    appType: {{ template "charts.name" . }}
    chart: {{ template "charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
```

```
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "charts.fullname" . }}"
  labels:
    app: {{ template "charts.fullname" . }}
    appType: {{ template "charts.name" . }}
    chart: {{ template "charts.chart" . }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: {{ template "charts.fullname" . }}
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
```

If we add these resource without helm hook, the deployement is OK

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "charts.fullname" . }}-test
  labels:
    app: {{ template "charts.fullname" . }}
    appType: {{ template "charts.name" . }}
    chart: {{ template "charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
```

**Expected behavior**

To be able to deploy a Helm chart that contains only resources with Helm hooks.

**Version**

```shell
2.14.10
```
