### ISSUE TITLE
hydrator: hydrateTo and syncSource as a different repository

### ISSUE THREAD

**Issue by newtondev** [argoproj/argo-cd#22719]
# Summary

When using the source hydrator and it does the hydration to the verbose manifests, it would be great to have it able to do this to a separate repository not under the control of the user (and not just a branch on the same project).

# Motivation

We have Argo CD installed in various clusters watching specific GitOps specific repositories of hydrated manifests. Currently the hydration is done by custom scripting. It would be great to have this built into Argo CD to make the custom scripting redundant.

# Proposal

Add the ability to hydrate manifests to a separate repository and path specified. Similar to drySource where you could specify:

```
properties:
  path:
    description: Path is a directory path within the Git repository
      where the manifests are located
    type: string
  repoURL:
    description: RepoURL is the URL to the git repository that
      contains the application manifests
    type: string
  targetRevision:
    description: TargetRevision defines the revision of the source
      to hydrate
    type: string
```

This way hydrateTo the new repository and path, then syncSource is configured to read out of this remote repository instead.

The original repository is then not polluted with any of the rendered manifests in separate branches and only had the dry kustomize/helm manifests.
