### ISSUE TITLE
CRDs are reporting an incorrect diff when `ServerSideDiff` + annotation tracking is used

### ISSUE THREAD

**Issue by blakepettersson** [argoproj/argo-cd#22721]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* ~[ ] I've pasted the output of `argocd version`~. (this is happening on `master` and at least since 2.14)

**Describe the bug**

When `ServerSideDiff` is used in conjunction with annotation resource tracking, the live CRDs incorrectly get a diff of a tracking annotation that should be removed. The tracking annotation is not there nor should it be there in the first place.

**To Reproduce**

Apply this application

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.1.4
    chart: kyverno
    helm:
      releaseName: kyverno
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
```

**Expected behavior**

No diffs should appear on the CRDs; they should be `Synced`.

**Screenshots**

<img width="878" alt="Image" src="https://github.com/user-attachments/assets/1e04ae61-705b-4824-92f2-d0e640986f91" />

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/c6c8a1c4-1c52-4cb6-8ee4-c5be0dbacb6f" />

**Logs**

N/A
