### ISSUE TITLE
Strange Failed sync attempt to <guid>: successfully synced (all tasks run) messaged

### ISSUE THREAD

**Issue by MartijnZuijderduijn** [argoproj/argo-cd#22764]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Ever so often I get successfully synced (all tasks run) messages as a Failed Sync message. The application indeed syncs fine but the message indicates as a failure and ArgoCD marks it as such.

**To Reproduce**

1. Create repo for openbao. Due to some legacy on our part it is a kustomize installing an helm chart, as we had this before using argo, we are migrating away from this by removing kustomize as the middle man. (this issue still occurs in other purely helm components)

cluster specific config in `clusters/infra/openbao`
```
resources:
- ../../../openbao
- <some other loose manifests>

generatorOptions:
  disableNameSuffixHash: true

namespace: openbao

helmCharts:
- name: openbao
  repo: https://openbao.github.io/openbao-helm
  version: 0.10.1
  releaseName: openbao
  namespace: openbao
  valuesFile: ../../../openbao/values.yml
  additionalValuesFiles:
  - environment-specific-values.yml
  skipHooks: true
  includeCRDs: true
```

the common kustomize contains just some more loose manifests.
the value files just contain inout for the openbao helm chart.

2. Add application:
```yml
project: infra-managed-components
source:
  repoURL: <git repo path>/openbao
  path: clusters/infra/openbao
  targetRevision: '>=1.0.0-0'
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - PrunePropagationPolicy=foreground
    - PreserveResourcesOnDeletion=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 1m
ignoreDifferences:
  - kind: Secret
    name: openbao-vault-token
    namespace: openbao
    jsonPointers:
      - /data/VAULT_TOKEN
```

3. Make some changes, let it sync automatically. Sometimes but not always this message occurs.

**Expected behavior**

Argo to sync the application and mark it as successful not as an error with a convoluted error message

**Screenshots**

<img width="1296" alt="Image" src="https://github.com/user-attachments/assets/16381a4d-9e8a-490e-8e9b-bea2b6de52af" />

**Version**

```shell
argocd: v2.14.4+3d901f2
  BuildDate: 2025-03-04T20:39:46Z
  GitCommit: 3d901f2037888af302a85f518bea70b33ee8e1c7
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
