### ISSUE TITLE
[AppSet + ignoreApplicationDifferences + templatePatch] puts generated Application in "Unknown" state

### ISSUE THREAD

**Issue by andrey-parkhomets** [argoproj/argo-cd#22803]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The `Applicationset` with extensively usage of `templatePatch` used to patch `spec.sources[].helm.valuesObject` where last set via `config.yaml` sourced by "Git Files Generator" and in that `Applicationset`  the `ignoreApplicationDifferences`  used `.spec.sources[]?|.targetRevision` to allow version changes via UI -  puts  generated`Application` in **Unknown** state if `config.yaml` got changed which lead to change of`spec.sources[].helm.valuesObject`.

**To Reproduce**

1. create simplyfied `Applicationset` with next structure:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  applyNestedSelectors: true
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: argocd-cluster/_app-catalog/trivy/trivy-test.yaml # i.e. argocd-cluster/_app-catalog/<namespace>/<Application>.yaml
              pathParamPrefix: conf
              repoURL: https://github.com/my-org/my-repo.git
              revision: HEAD
          - clusters:
              selector:
                matchExpressions:
                  - key: clusterAlias
                    operator: In
                    values:
                      - dev0-csi4-app

  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.sources[]?|.targetRevision
        - .spec.source?|.targetRevision

  template:
    metadata:
      name: 'trivy-{{ .metadata.labels.clusterAlias }}'
    spec:
      destination:
        name: '{{ .name }}'
      project: project-clusters
  templatePatch: |
    {{- $k8sNamespace := index .conf.path.segments 2 }}
    {{- $source := dict }}
    {{- $source = index . "sources" }}

    spec:
      destination:
        name: '{{ .name }}'
        namespace: '{{ $k8sNamespace }}'

      sources: {{ $source  |toJson }}

    {{- if (hasKey . "syncPolicy"  )  }}
      syncPolicy: {{ (index . "syncPolicy") |toJson }}
    {{- end }}

```
2. Create `config` , for example `trivy-test.yaml` i.e. argocd-cluster/_app-catalog/trivy/trivy-test.yaml with next body:
```yaml

sources:

- name: trivy-operator
  repoURL: https://aquasecurity.github.io/helm-charts/
  targetRevision: 0.27.0
  chart: trivy-operator
  ref: trivy-operator
  helm:
    valuesObject:
      targetWorkloads: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob"

syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: false
  syncOptions:
    - Retry=true
    - ApplyOutOfSyncOnly=true
    - FailOnSharedResource=true
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true

```
above successfully creates child `Application`, but when something get changed within above config wihin git repo , i.e. `sources[].helm.valuesObject.*`
```yaml
targetWorkloads: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"
```
the `Application` got an **Unknown** state  with error: `InvalidSpecError
spec.source.targetRevision is required if the manifest source is a helm chart`

**Expected behavior**

Application should be generated successfully 

**Screenshots**

<img width="1177" alt="Image" src="https://github.com/user-attachments/assets/4b7ee1d7-db0c-44e9-bdb2-c48d7eeeb39b" />

<img width="1367" alt="Image" src="https://github.com/user-attachments/assets/a5d04058-20bf-47a0-997f-fe42fad7c776" />

<img width="908" alt="Image" src="https://github.com/user-attachments/assets/7758706f-a85b-43f5-94c1-976c8b41d274" />
as shown on last screen, the `targetRevision` not present !

**Version**

```shell
argocd: v2.14.11+8283115.dirty
  BuildDate: 2025-04-22T17:03:17Z
  GitCommit: 82831155c2c1873b3b5d19449bfa3970dab9ce24
  GitTreeState: dirty
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.14.11+8283115.dirty
  BuildDate: 2025-04-22T17:03:17Z
  GitCommit: 82831155c2c1873b3b5d19449bfa3970dab9ce24
  GitTreeState: dirty
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v5.6.0 2025-01-14T15:12:17Z
  Helm Version: v3.17.3+ge4da497
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**

```bash
 Events:                                                                                                                                                  │
│   Type    Reason              Age    From                           Message                                                                              │
│   ----    ------              ----   ----                           -------                                                                              │
│   Normal  OperationStarted    16m    argocd-application-controller  Initiated automated sync to '0.27.0'                                                 │
│   Normal  ResourceUpdated     16m    argocd-application-controller  Updated sync status:  -> OutOfSync                                                   │
│   Normal  ResourceUpdated     16m    argocd-application-controller  Updated health status:  -> Missing                                                   │
│   Normal  OperationCompleted  15m    argocd-application-controller  Sync operation to  succeeded                                                         │
│   Normal  ResourceUpdated     15m    argocd-application-controller  Updated sync status: OutOfSync -> Synced                                             │
│   Normal  ResourceUpdated     15m    argocd-application-controller  Updated health status: Missing -> Progressing                                        │
│   Normal  ResourceUpdated     5m58s  argocd-application-controller  Updated health status: Progressing -> Degraded                                       │
│   Normal  ResourceUpdated     4m38s  argocd-application-controller  Updated sync status: Synced -> Unknown                                               │
│   Normal  ResourceUpdated     4m38s  argocd-application-controller  Updated health status: Degraded -> Unknown                                           │
│
```

**Comment by andrey-parkhomets** [comment]
Also reproduced for current version `argocd-server: v3.0.0+e98f483`.
workarounds:
1) apply annotation to appset:  i.e. `k annotate applicationset/my-appset argocd.argoproj.io/application-set-refresh="true"` - doesn't help
2) use shell snippet `argocd appset generate |  kubectl apply `- works !
```
#!/usr/bin/env bash
argocd login --core
# set -x
declare -a app_arr=($(kubectl get applications.argoproj.io -o yaml|yq '.items[]|select(.status.health.status == "Unknown" or .status.sync.status == "Unknown" )|.metadata.name'))

for app in "${app_arr[@]}";
do
    echo "...found that Application: $app in Unknown state";
    _parent_appset=$(kubectl get "applications.argoproj.io/$app" -o yaml |yq '.metadata.ownerReferences[]|select(.kind == "ApplicationSet")|.name')
    if [[ -n ${_parent_appset} ]]; then
        echo "...it's generated by $_parent_appset";

        echo "...start force re-generating..."
        tmpfile=$(mktemp /tmp/"$_parent_appset.XXXXXX")

        kubectl get "applicationsets.argoproj.io/$_parent_appset" -o yaml|kubectl neat > "$tmpfile"
        echo "...created temp file with appset: $tmpfile"
        _cmd="argocd appset generate $tmpfile -o json \\
            | jq -r 'if type == \"object\" then [.] else . end' | yq -P \\
            |  _app=$app yq '.[]| split_doc|select(.metadata.name == env(_app))' -o yaml \\
            | kubectl apply  --force-conflicts --server-side -f - "
        echo "$_cmd"
        eval " $_cmd"
    fi
    rm -f "$tmpfile"
done;
```

**Comment by andrey-parkhomets** [comment]
The issue not reproducible if :

1. above code for `appset.yaml` converted to single sourced i.e.:

```
  templatePatch: |
    {{- $k8sNamespace := index .conf.path.segments 2 }}
    {{- $source := dict }}
    {{- $source = index . "source" }}

    spec:
      destination:
        name: '{{ .name }}'
        namespace: '{{ $k8sNamespace }}'

      source: {{ $source  |toJson }}

    {{- if (hasKey . "syncPolicy"  )  }}
      syncPolicy: {{ (index . "syncPolicy") |toJson }}
    {{- end }}
```
2.  application `config.yaml` in my example `argocd-cluster/_app-catalog/trivy/trivy-test.yaml` 
```
source:
  name: trivy-operator
  repoURL: https://aquasecurity.github.io/helm-charts/
  targetRevision: 0.27.0
  chart: trivy-operator
  ref: trivy-operator
  helm:
    valuesObject:
      targetWorkloads: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,jobssssss"
```

3. the `ignoreApplicationDifferences` changed to `jsonPointers` like this:
```
  ignoreApplicationDifferences:
  - jsonPointers:
      - /spec/source/targetRevision
```
