### ISSUE TITLE
Respect the definition of namespace in DestinationServiceAccount as described in the docs

### ISSUE THREAD

**Issue by yehlo** [argoproj/argo-cd#22829]
# Summary

Currently the sync controller checks `spec.destination.namespace` and `metadata.namespace` of an application for the serviceAccount to use.

https://github.com/argoproj/argo-cd/blob/master/controller/sync.go#L598 

# Motivation

In some cases the projects are predetermined by an administrator with given `destinationServiceAccounts`.

As an administrator I could create the projects for the developers and use an already created serviceAccount to use.

With the current implementation the project creator needs their app creators to create a serviceAccount with a specific name in the app namespace.

In an implementation like this only rolebindings are left to create which can be automated through other means by the administrator. 

Meaning the developer does not have to think about Kubernetes resources and can just create apps.

# Proposal

We could add an additional optional field to the object to specify the serviceAccount namespace.

It would look something like this:
```yaml
kind: AppProject
metadata:
  name: myproj
  namespace: argocd
spec:
  destinationServiceAccounts:
    - server: "in-cluster"
      namespace: <customer-prefix>-*
      defaultServiceAccount: customer-sync
      defaultServiceAccountNamespace: argocd
```

The biggest drawback will be the evaluation of the namespace foreach `project.Spec.DestinationServiceAccounts` instead of just once per func call. 

Could maybe put it in another helper method
```go
func deriveServiceAccountNamespace(sa *v1alpha1.ApplicationDestinationServiceAccount, application *v1alpha1.Application) string {
	// if the namespace is specified in the ApplicationDestinationServiceAccount 
	// use that namespace for the service account.
	if sa.defaultServiceAccountNamespace != "" {
		return sa.defaultServiceAccountNamespace
	}

	// spec.Destination.Namespace is optional. If not specified, use the Application's
	// namespace
	serviceAccountNamespace := application.Spec.Destination.Namespace
	if serviceAccountNamespace == "" {
		serviceAccountNamespace = application.Namespace
	}
	if sa.Namespace != "" {
		return sa.Namespace
	}
	return serviceAccountNamespace
}
```
