### ISSUE TITLE
argocd login failed on 2.14

### ISSUE THREAD

**Issue by hzw649** [argoproj/argo-cd#22823]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

argocd cli login failed on new version

it works for `v2.13.0+347f221`, but failed for `v2.14.0+4745e08`, I can do more test if needed

**To Reproduce**

We use emissary-ingress for tls, and argocd-server is started with `--insecure`

here is the Service and Mapping manifests
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: argocd
  name: argocd-server
  namespace: argocd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: argocd
  name: argocd-server-grpc
  namespace: argocd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    argocd.argoproj.io/instance: argocd
  name: argocd-server-api
  namespace: argocd
spec:
  bypass_auth: true
  grpc: true
  host: argocd-server.xxx
  prefix: /
  service: http://argocd-server-grpc.argocd
  timeout_ms: 180000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    argocd.argoproj.io/instance: argocd
  name: argocd-server-ui
  namespace: argocd
spec:
  allow_upgrade:
    - websocket
  bypass_auth: true
  host: argocd.xxx
  prefix: /
  resolver: endpoint
  service: http://argocd-server.argocd
  timeout_ms: 180000
```
here is the `argocd-cmd-params-cm`
```
apiVersion: v1
data:
  dexserver.disable.tls: 'true'
  redis.server: argocd-redis-ha-haproxy:6379
  server.dex.server.plaintext: 'true'
  server.insecure: 'true'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: argocd--shlab-prod
  name: argocd-cmd-params-cm
  namespace: argocd
```

```
❯ argocd login argocd-server.xxx --sso
WARNING: server is not configured with TLS. Proceed (y/n)? y
FATA[0003] rpc error: code = Unknown desc =
```

It works if add option `--skip-test-tls`, but it is not needed in old version
```
❯ argocd login argocd-server.xxx --sso   --skip-test-tls
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
Performing authorization_code flow login: https://argocd.xxx/api/dex/auth?access_type=offline&client_id=argo-cd-cli&code_challenge=pnamjatEW1GXu9pDfiaelguNvhXWmiLNIRo5k2JjKz8&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=VeMNAjWQmRHfmQTXrNZWzxXt
Opening system default browser for authentication
Authentication successful
'xxx@com' logged in successfully
Context 'argocd-server.xxx' updated
```

**Expected behavior**

```
❯ argocd login argocd-server.xxx --sso
Opening browser for authentication
Performing authorization_code flow login: https://argocd.xxx/api/dex/auth?access_type=offline&client_id=argo-cd-cli&code_challenge=SGBj1taEvnFMHDeDVIiTnjCwXY72oSh5A5xkVcaKyGs&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=ZgfszXsiuWYhdNaLjfugNKAa
Authentication successful
'xx@com' logged in successfully
Context 'argocd-server.xxx' updated
```

**Screenshots**

**Version**

```
❯ argocd version
argocd: v2.14.11+8283115.dirty
  BuildDate: 2025-04-22T17:02:45Z
  GitCommit: 82831155c2c1873b3b5d19449bfa3970dab9ce24
  GitTreeState: dirty
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.13.1+8ec6889.dirty
  BuildDate: 2025-04-18T06:05:01Z
  GitCommit: 8ec68898b9e6ed80e2c2d60e5eac7cd7cea1f00b
  GitTreeState: dirty
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```
