### ISSUE TITLE
Allow to set authorEmail and authorName used in Commit Server

### ISSUE THREAD

**Issue by reneeckstein** [argoproj/argo-cd#22847]
# Summary

It should be possible to set the Git commit author name and email used in the Commit Server if enabling Source Hydrator. Currently, it only supports getting it automatically for GitHub users, otherwise it's using a default value for both.

[authorName](https://github.com/argoproj/argo-cd/blob/7d81d1a59eeda6d7f24afcaba91b89341acc2864/commitserver/commit/commit.go#L191C3-L191C25) = "Argo CD"
[authorEmail](https://github.com/argoproj/argo-cd/blob/7d81d1a59eeda6d7f24afcaba91b89341acc2864/commitserver/commit/commit.go#L195C3-L195C38) = "argo-cd@example.com"

# Motivation

We want to use the Source Hydrator on a self-hosted GitLab instance and certain push rules are enabled which prohibit commits with these defaults.

- Reject unverified users
   _Users can only push commits to this repository if the committer email is one of their own verified emails._

- Check whether the commit author is a GitLab user
   _Restrict commits to existing GitLab users._

# Proposal

Allow to set authorName and authorEmail similar to like Kargo supports it [here](https://docs.kargo.io/operator-guide/advanced-installation/common-configurations/#default-commit-author)
maybe as part of `commitserver.xxx` in argocd-cmd-params-cm configmap https://argo-cd.readthedocs.io/en/latest/operator-manual/argocd-cmd-params-cm-yaml/

**Comment by crenshaw-dev** [comment]
Makes sense! Would you be up for raising a PR?

**Comment by adityaraj178** [comment]
Hi @crenshaw-dev, I’d like to take this up.

My approach: add support for configuring authorName and authorEmail in the commit server via `env vars` and` argocd-cmd-params-cm`. 

```
# Via environment variables
export ARGOCD_COMMIT_SERVER_AUTHOR_NAME="DevOps"
export ARGOCD_COMMIT_SERVER_AUTHOR_EMAIL="devops@company.com"


# Via ConfigMap (argocd-cmd-params-cm)
data:
  commitserver.author.name: "DevOps"
  commitserver.author.email: "devops@company.com"
```
This would let users override the current hardcoded defaults .
let me know if this approach looks good? and also should i make it configurable through flags like` argocd-commit-server --author-name "DevOps" --author-email "devops@company.com"` ?
