### ISSUE TITLE
Cannot patch valuesObject using patchTemplate

### ISSUE THREAD

**Issue by jan-di** [argoproj/argo-cd#22850]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using a templatePatch to patch the valuesObject inside the static template using a gotemplate, the following error is thrown:

```
error while applying templatePatch template to json "{\"spec\":{\"source\":{\"helm\":{\"valuesObject\":{\"prometheus\":{\"kube-state-metrics\":{\"namespaces\":\"\"}}}}}}}": unable to find api field in struct RawExtension for the json field "prometheus"
```

It seems, that you can only patch values known to Argocd (e.g. all the application spec, but not unstructured data in valuesObject.

**To Reproduce**

1. Create the following applicationset

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            project.example/application-set: enabled

  goTemplate: true
  template:
    metadata:
      name: "myappset-{{ .name }}"
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/compare-options: ServerSideDiff=true
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      source:
        repoURL: mychartrepo
        chart: mychartname
        targetRevision: 1.2.3
        helm:
          releaseName: myappsetrelease
          valuesObject:

            prometheus:
              kube-state-metrics:
                namespaces: "kube-system"

      destination:
        name: "{{ .name }}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1 # unlimited
          backoff:
            maxDuration: 20m

  templatePatch: |
    {{- if eq (index .metadata.annotations "do-not-filter") "yes" }}
    spec:
      source:
        helm:
          valuesObject:
            prometheus:
              kube-state-metrics:
                # Do not filter namespaces
                namespaces: ""
    {{- end }}
```

**Expected behavior**

The templatePatch get applied and overwrites the specific bit inside valuesObject with no error

**Version**

```shell
argocd-server: v2.14.2+ad27246
  BuildDate: 2025-02-05T23:44:17Z
  GitCommit: ad2724661b66ede607db9b5bd4c3c26491f5be67
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Comment by nitishfy** [comment]
Hi, I spent some time figuring out this thing and this is what I've come up with:

What you're describing as a bug is the intended behaviour of Argo CD due to how Argo CD handles patching on unstructured fields like `valuesObject`. Internally, `valuesObject` is [defined](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L506) as a `runtime.RawExtension` which means it's treated as opaque unstructured data. Since it's not a normal Go struct with defined fields, Argo CD and Kubernetes do not know the structure inside it - it could contain anything. Because of this, the templatePatch mechanism in ApplicationSet cannot apply partial patches to nested fields inside `valuesObject` (like `prometheus.kube-state-metrics.namespaces`). When it tries, it fails because it cannot resolve the internal keys of a `RawExtension`, which results in the error you're seeing.

I'd not consider this as a bug. Please try this instead and let me know if it worked for you
```
templatePatch: |
  spec:
    source:
      helm:
        valuesObject: {{ if eq (index .metadata.annotations "do-not-filter") "yes" }}{{ `{"prometheus":{"kube-state-metrics":{"namespaces":""}}}` }}{{ else }}{{ `{"prometheus":{"kube-state-metrics":{"namespaces":"kube-system"}}}` }}{{ end }}
```

**Comment by nitishfy** [comment]
Closing this...feel free to reopen!

**Comment by tonyay163** [comment]
@nitishfy can you explain what the difference is in your example? Is it supposed to work because the patch is json, or because you're adding the applying the same node on both sides? I'm running into the exact same problem using the following example:

```
  templatePatch: |
    spec:
      source:
        helm:
          valuesObject:
            {{- if (dig "arm64" "" .) }}
            replica:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: kubernetes.io/arch
                            operator: In
                            values:
                              - arm64
            {{- else }}
            replica:
              affinity: {}
            {{- end }}
```
