### ISSUE TITLE
Restrict namespace permission for application

### ISSUE THREAD

**Issue by WinterNis** [argoproj/argo-cd#22869]
# Summary

We would like to let argoCD create the destination namespaces for applications, but forbid the application to mess with other namespaces.

# Motivation

To create the namespace where the resources of an application will be deployed in, there are multiple options:

- Use the `CreateNamespace` sync option
- Declare the namespace in the resources manifests directly
- Create the namespace before creating the application (by other means)

The first two options requires the `AppProject` to allow `Namespaces` resources to be created by the application (with `clusterResourceWhitelist` for example).
**This is a really powerful permission as it basically allows the application not only to create the namespace, but also to update and delete any namespace in the cluster (`kube-system` excluded, there is a specific protection for this namespace).**

We are running _multi-tenant_ clusters with _apps-of apps_, and we would like to allow tenants to create the destination namespace automatically alongside their argocd apps. But we do not want them to be able to mess with other already existing namespaces in the cluster.

In order to achieve this, we tried to reduce the permissions of the application in multiple ways:

- Use argocd RBAC and [fine grained permissions](https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#fine-grained-permissions-for-updatedelete-action). This works well to limit permission of users that have access of the application via the UI/CLI, but does not restrict resources created by the application itself during syncs.
- Use the `namespace` field of the `destination` field of the `AppProject`: This only applies to namespaced resources. AFAIK it does not allow to restrict which namespace objects can be managed by the application or not.
- Use [service account impersonation](https://argo-cd.readthedocs.io/en/latest/operator-manual/app-sync-using-impersonation/) to restrict what the application can do on namespaces. This works well to block namespace deletion. It also works to block namespace updates, but it requires to know the name of the namespace beforehand, as the patch permission is necessary, and we need to scope it on this namespace only (using `ResourcesName` in the clusterRole associated with the service account). It’s not possible to only give the create permission on namespaces as patch is required, else the application sync will fail on the namespace management.

So the last option using impersonation kind of works but sometimes you can not know the namespace name beforehand (ex: ephemeral/dynamic applications), and/or do not want to handle the complexity of creating the namespace dynamically.

What we would like is argoCD being able to create the namespace automatically. But it should only handle the creation of the namespace if it does not exist, without trying to update it afterhands.

Maybe we are missing something and there is a better approach to solve this issue ?

Thanks !

**Comment by anandf** [comment]
@WinterNis Thanks for bringing it up. I have worked on the [service account impersonation](https://argo-cd.readthedocs.io/en/latest/operator-manual/app-sync-using-impersonation/) and am interested in the specific use case you have.

When `CreateNamespace` sync option is enabled and if the destination namespace is allowed in the project, can the namespace be created by app controller's SA and  further sync can be done using the impersonated SA. Would such a solution work for you ?

**Comment by WinterNis** [comment]
Hi, thanks for your interest on this issue.

> When CreateNamespace sync option is enabled and if the destination namespace is allowed in the project, can the namespace be created by app controller's SA and further sync can be done using the impersonated SA.

AFAIK, today the allowed `destinations` namespaces in the AppProject are never considered when deploying cluster wide resources (which makes sense).
If somehow, the argocd controller could check these to allow the `namespace` creation without having to allow `Namespace` resources in `ClusterResourceWhitelist`, that could work I suppose yes (even without service account impersonation)

With service account impersonation, it’s already possible to correctly restrict the management of specific namespaces without using `CreateNamespace` (as explained in the issue).
But that only works for "static" namespaces, you have to know the namespace name before hand because it’s not possible to use wildcard in the resourcesName attributes of roles in k8s rbac.



Another solution to this issue would be to be able to configure resourcesNames (with wildcards) in argocd rbac directly. Ex:

```
  clusterResourceWhitelist:
    - group: "*"
      kind: Namespace
      resourceNames: 
       - foo
       - bar-*
```

This would actually solves other issues people have with argocd rbac (not only with namespaces).

The "downside" is that argocd rbac would become more "powerful" than k8s one, and service account impersonation would not be able to match the same capabilities (as wildcard is not allowed in resourcesName in k8s rbac)

**Comment by ChristianCiach** [comment]
We just encountered the same issue. I think the sync option should (optionally) work even without a matching `clusterResourceWhitelist` permission, because (usually) only cluster-admins can set the sync-option and the destination namespace of an application. 

Adding `kind: Namespace` to the `clusterResourceWhitelist` is just not feasible, as this allows users to easily hijack existing namespaces.

Dear maintainers: Would a PR be considered that adds a global setting to allow ArgoCD to create namespaces even without a `clusterResourceWhitelist` via sync-options?

**Comment by agaudreault** [comment]
@WinterNis What is the issue with https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#create-namespace ? As far as I know, it does not require to be allowed as a cluster resource in the AppProject. The destination will need to be valid for the AppProject.

**Comment by WinterNis** [comment]
@agaudreault 

AFAIK, it does require to be allowed in the AppProject.

Here is simple example to reproduce:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name:  foo
  namespace: argocd
spec:
  destinations:
    - name: in-cluster
      namespace: 'test-foo'
      server: '*'
  sourceRepos:
    - https://github.com/argoproj/*
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd
spec:
  project: foo
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: test-foo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
```

Since `Namespace` is not allowed in the `clusterResourceWhitelist`, the sync will fail with the following error:

`resource :Namespace is not permitted in project foo`


![Image](https://github.com/user-attachments/assets/cbc3ca44-ba42-4126-a073-dc55a30a373e)
