### ISSUE TITLE
Add health checks for `karpenter.sh`: `NodePool` and `NodeClass`

### ISSUE THREAD

**Issue by nvatuan** [argoproj/argo-cd#22885]
# Summary

With the v1 upgrade of Karpenter come with the introduction of status conditions for `NodePool` and `NodeClasses`:

https://karpenter.sh/v1.0/concepts/nodepools/#statusconditions
https://karpenter.sh/v1.0/concepts/nodeclasses/#statusconditions

I wonder if it's appropriate to add health check for these resources based on their `status.conditions` value.

# Motivation

During an upgrade to `Karpenter v1`, I found out (pretty late) that my `NodePool` was having error events like so:

<img width="482" alt="Image" src="https://github.com/user-attachments/assets/297b24ae-9800-4791-8b32-5e9a84691d10" />

```yaml
status:
  conditions:
    - lastTransitionTime: '2025-04-25T06:16:54Z'
      message: NodeClass not found on cluster
      reason: NodeClassNotFound
      status: 'False'
      type: NodeClassReady
    - lastTransitionTime: '2025-04-25T06:16:54Z'
      message: NodeClassReady=False
      reason: UnhealthyDependents
      status: 'False'
      type: Ready
    - lastTransitionTime: '2025-04-25T01:09:46Z'
      message: ''
      reason: ValidationSucceeded
      status: 'True'
      type: ValidationSucceeded
```

Apparently I forgot to add the new `NodeClass`. I wonder if it's appropriate to do ArgoCD health check for NodePool and NodeClass

# Proposal

In general for both `NodePool` and `NodeClass`, there is this field available:

> status.conditions 
> [Conditions](https://github.com/kubernetes/apimachinery/blob/f14778da5523847e4c07346e3161a4b4f6c9186e/pkg/apis/meta/v1/types.go#L1523) objects add observability features to Karpenter.

> The status.conditions.type object reflects node status, such as Initialized or Available.
> The status of the condition, status.conditions.status, indicates if the condition is True or False.

We can check for `status.conditions[i].type == Ready && status.conditions[i].status == True`  to have Healthy status.
Although I'm not sure when should it be `In Progress` or `Degraded`.
* Maybe we can have use `now() - lastTransitionTime`:
  * `type==Ready && status == False && now() - lastTransitionTime < 10m` = `Progressing`
  * `type==Ready && status == False && now() - lastTransitionTime >= 10m` = `Degraded`
