### ISSUE TITLE
Allow config management plugins to output a directory

### ISSUE THREAD

**Issue by taharah** [argoproj/argo-cd#2294]
**Is your feature request related to a problem? Please describe.**

Currently, the generate command for config management plugins must output all manifests to STDOUT. In order to operate better with tools like Kapitan, plugins should be able to output and/or just modify a directory of manifests that Argo CD can utilize for deployment.

**Describe the solution you'd like**

Allow the generate command for configuration management plugins to be configured in such a way Argo CD knows it will output a directory of manifests rather than only allowing them to send the manifests to STDOUT.

**Have you thought about contributing yourself?**

Yes, I am more than happy to take a look at making the necessary changes myself.

**Comment by alexec** [comment]
Could you have a script that runs your plugin, and then does `find . -type f -name '*.yaml' | xargs cat`?

**Comment by taharah** [comment]
Yeah, I was going to do something like that for the time being, but it would be nice if it was available as a first-class feature to read in a set of files and/or directories.

**Comment by alexec** [comment]
ok, nice idea

**Comment by augustfengd** [comment]
Holy moly. For those who are trying the `find` method like me, it takes a special level of parsing and escaping:

```yaml
---
generate:
  command:
  - find
  args:
  - "${REPLACEME}"
  - "-type" # predicates need to be by themselves.
  - "f"
  - "-exec"
  - "cat"
  - "{}"    # gfind: In ‘-exec ... {} +’ the ‘{}’ must appear by itself, but you specified ‘cat {}’ (gfind / 'foobar' -exec 'cat {}' +)
  - ";"     # "\;" wouldn't work. see alternatives: https://stackoverflow.com/a/26439638
  - "-exec"
  - "echo"
  - "---"
  - ";"
```
