### ISSUE TITLE
`argocd appset generate` does not support Any Namespaces feature

### ISSUE THREAD

**Issue by cdemarco-drw** [argoproj/argo-cd#22942]
**Describe the bug**

`argocd appset generate` does not work when the AppSet is to be loaded into a Namespace other than the "global" Argo-CD Namespace, even when this Namespace is permitted by AppSets in Any Namespace:

`FATA[0000] rpc error: code = Unknown desc = unable to generate Applications of ApplicationSet: error generating applications: error getting project tenant: namespace tenant-argo-cd provided for the object  does not match the namespace argo-cd on the client`

Argo-CD is in fact configured correctly for this feature, because directly loading the same AppSet manifest works as expected.

**To Reproduce**

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: uppi-6077-test-001
  namespace: tenant-argo-cd
spec:
  generators:
    - git:
        repoURL: some-repo
        revision: HEAD
        files:
          - path: ':(glob)k8s/uppi-6077-appset-test/*/kustomization.yaml'
  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'
        app: '{{path[1]}}'
      namespace: tenant-argo-cd
    spec:
      project: some-tenant
      destination:
        name: some-cluster
        namespace: '{{path[2]}}'
      source:
        repoURL: some-repo
        path: '{{path}}'
        targetRevision: HEAD
      syncPolicy: {}
```

**Expected behavior**

- The appset should render locally just as if `.metadata.namespace` was changed to the global `argo-cd` (in our case) Namespace.

- The `generate` sub-command should accept the `[-n | --namespace]` option.

**Version**

```shell
argocd: v2.14.10
  BuildDate: unknown
  GitCommit: v2.14.10
  GitTreeState: clean
  GitTag: v2.14.10
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.14.11+8283115
  BuildDate: 2025-04-22T15:31:47Z
  GitCommit: 82831155c2c1873b3b5d19449bfa3970dab9ce24
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.16.3+gcfd0749
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by nitishfy** [comment]
I'll take this up.

**Comment by cdemarco-drw** [comment]
It would be lovely to have this fix available in the 2.x series, as we (and I suspect many others) aren't ready to jump to 3.0 yet.

**Comment by nitishfy** [comment]
After some debugging, I found out that the root cause of the problem is that the Argo CD ApplicationSet controller uses a namespaced client that is restricted to operate only within the namespace where the controller is deployed (usually `argocd`).

When your ApplicationSet is defined in a different namespace (e.g., `dev`), and it references an AppProject in that same namespace (`dev`), the controller tries to fetch the AppProject using the namespace from the ApplicationSet (`dev`).

However, the namespaced client checks if the namespace in the request matches its own configured namespace (argocd), and if it doesn't match, it returns an error. This means the client refuses to fetch resources from any namespace other than `argocd`, causing the lookup for AppProject in dev to fail and blocking ApplicationSet generation.

Before working on this, I'm interested to hear other maintainers thought on how to implement this. I think changing the client namespace to other than the default namespace may lead to problems.

**Comment by agaudreault** [comment]
@nitishfy thanks for the investigation. 

Based on my knowledge of appset/apps in any namespaces, the AppProject will always be defined in the **argo controller namespace**. We do not have a concept of "AppProject in any namespace". 

So the assumption that the appProject namespace is in the same namespace as the AppSet is wrong. It should default to the controller namespace. 

Maybe related to https://github.com/argoproj/argo-cd/pull/19553, but the documentation of the appset-in-any-namespace needs to be improved.

https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/
> Creating following ApplicationSet generates two Applications infra-escalation and team-two-escalation. Both will be rejected as they are outside argocd namespace, therefore sourceNamespaces will be checked

**Comment by cdemarco-drw** [comment]
Hi, any progress on this? It's pretty important functionality for AppSet adoption, to be able to preview generator output.

**Comment by nitishfy** [comment]
@ishitasequeira ^^ :)

**Comment by ishitasequeira** [comment]
@agaudreault, You're right that the AppProject always resides in the controller's (typically argocd) namespace. Even when the ApplicationSet itself is in another namespace (like dev), the controller should still resolve the AppProject from the controller namespace.

To clarify the generator's namespace field, yes, that is meant to indicate the namespace in which the controller is running, and where it should resolve controller-scoped resources like AppProject. This aligns with the expected behavior described in the [AppSet Any Namespace docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/#overview), where AppProjects remain centralized in the controller's namespace.

We should ensure that the controller uses the correct namespace (controller namespace) when resolving AppProjects, regardless of where the ApplicationSet is defined. Also, can we ensure that the `--applicationset-namespaces` are configured on the applicationset controller pod? Happy to help further debug or review any implementation changes around this.

**Comment by nitishfy** [comment]
@cdemarco-drw can you please verify that the source namespace is correctly configured for appset controller and AppProj?

**Comment by cdemarco-drw** [comment]
This is actually very strange; the bug appears to be tickled only for Git generators:

```
❯ cat working-appset.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: working-appset
  namespace: tenant-argo-cd
spec:
  generators:
    - list:
        elements:
          - app: foo
            overlay: path/to/foo
  template:
    metadata:
      name: some-name
      namespace: tenant-argo-cd
    spec:
      destination:
        namespace: tenant-dev
      project: tenant
      source:
        path: some-path
        repoURL: some-repo
        targetRevision: HEAD

❯ argocd --grpc-web appset generate working-appset.yaml
NAME                     CLUSTER  NAMESPACE     PROJECT  STATUS  HEALTH  SYNCPOLICY  CONDITIONS  REPO       PATH       TARGET
tenant-argo-cd/some-name           tenant-dev  tenant                    Manual      <none>      some-repo  some-path  HEAD


❯ cat broken-appset.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: broken-appset
  namespace: tenant-argo-cd
spec:
  generators:
    - git:
        repoURL: some-repo
        files:
          - path: some-path
  template:
    metadata:
      name: some-name
      namespace: tenant-argo-cd
    spec:
      destination:
        namespace: tenant-dev
      project: tenant
      source:
        path: some-path
        repoURL: some-repo
        targetRevision: HEAD

❯ argocd --grpc-web appset generate broken-appset.yaml
FATA[0000] rpc error: code = Unknown desc = unable to generate Applications of ApplicationSet: error generating applications: error getting project tenant: namespace tenant-argo-cd provided for the object  does not match the namespace argo-cd on the client%0Atime="2025-07-08T17:21:27Z" level=error msg="error generating application from params" applicationset=broken-appset error="error getting project tenant: namespace tenant-argo-cd provided for the object  does not match the namespace argo-cd on the client" generator="{nil nil &GitGenerator{RepoURL:some-repo,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:some-path,},},Revision:,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},SourceHydrator:nil,},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"%0A


❯ diff -u {working,broken}-appset.yaml
--- working-appset.yaml 2025-07-08 13:31:31
+++ broken-appset.yaml  2025-07-08 13:31:55
@@ -2,14 +2,14 @@
 apiVersion: argoproj.io/v1alpha1
 kind: ApplicationSet
 metadata:
-  name: working-appset
+  name: broken-appset
   namespace: tenant-argo-cd
 spec:
   generators:
-    - list:
-        elements:
-          - app: foo
-            overlay: path/to/foo
+    - git:
+        repoURL: some-repo
+        files:
+          - path: some-path
   template:
     metadata:
       name: some-name


 ❯ k get appproject tenant -o yaml | yq '.metadata.namespace,.spec.destinations[],.spec.sourceNamespaces'
argo-cd
name: '*'
namespace: tenant-*
name: cluster1
namespace: tenant-prod
name: cluster2
namespace: tenant-dev
name: cluster3
namespace: tenant-dev
- tenant-argo-cd

❯ k get cm argocd-cmd-params-cm -o yaml | yq .data
application.namespaces: '*-argo-cd'
applicationsetcontroller.allowed.scm.providers: https://git.drwholdings.com/,https://git.drwholdings.com,https://git.drwholdings.com/api/v3
applicationsetcontroller.enable.leader.election: "true"
applicationsetcontroller.enable.new.git.file.globbing: "true"
applicationsetcontroller.enable.progressive.syncs: "false"
applicationsetcontroller.log.format: json
applicationsetcontroller.log.level: info
applicationsetcontroller.namespaces: '*-argo-cd'
applicationsetcontroller.policy: sync
applicationsetcontroller.tokenref.strict.mode: "true"
controller.ignore.normalizer.jq.timeout: 1s
controller.log.format: json
controller.log.level: info
controller.operation.processors: "25"
controller.repo.server.timeout.seconds: "60"
controller.self.heal.timeout.seconds: "5"
controller.status.processors: "50"
controller.sync.timeout.seconds: "0"
dexserver.log.format: json
dexserver.log.level: info
notificationscontroller.log.format: json
notificationscontroller.log.level: info
otlp.address: ""
redis.server: argo-cd-redis-ha-haproxy:6379
repo.server: argo-cd-argocd-repo-server:8081
reposerver.log.format: json
reposerver.log.level: info
reposerver.parallelism.limit: "0"
reposerver.plugin.tar.exclusions: .git/*
server.basehref: /
server.disable.auth: "false"
server.enable.gzip: "true"
server.enable.proxy.extension: "false"
server.insecure: "true"
server.log.format: json
server.log.level: info
server.repo.server.strict.tls: "false"
server.rootpath: ""
server.staticassets: /shared/app
server.x.frame.options: sameorigin
```

The only thing that stands out to me is the extra space in the error message, as if `object` is null:
```
unable to generate Applications of ApplicationSet: error generating applications: error getting project tenant: namespace tenant-argo-cd provided for the object  does not match the
 namespace argo-cd on the client
```
