### ISSUE TITLE
k8s job should re-run only if its specification has changed when using sync options with the replace annotation

### ISSUE THREAD

**Issue by devopsmash** [argoproj/argo-cd#22952]
# Summary

Following the comment from [here](https://github.com/argoproj/argo-cd/discussions/7984#discussioncomment-12492308), I would like to suggest to re-run k8s jobs only if its specification has changed when using sync options with the replace annotation.

# Motivation

In my case, I would like to use this feature for my db migration scripts (Liquibase) with the following flow:

1. when I create the job for the **first time** (new namespace) --> ArgoCD will detect the change and it will create the job accordingly.
2. when I **update** the job container image tag version --> ArgoCD will detect the change in the job spec and it will recreate the job with the new image tag version accordingly.
3. When there are **no changes** to the job specification and I perform a manual/auto sync to my application (that includes other k8s resources) --> ArgoCD **should not** recreate the job.

Example for a k8s Job resource:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-job
  labels:
    app.kubernetes.io/name: "myjobname"
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/sync-wave: "-1"    
spec:
  ttlSecondsAfterFinished: 259200 
  backoffLimit: 0 
  parallelism: 1
  activeDeadlineSeconds: 18000
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "myjobname"
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 300
      containers:
      - name: liquibase
        image: liquibase:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: mysecret
        args:
          - "liquibase"
          - "update"
      restartPolicy: Never
```

notes:
* I would like to use the annotation: `argocd.argoproj.io/sync-wave: "-1"` to ensure this job runs before syncing my other k8s resources.
* I would prefer not to decouple this job from my Argo CD application as suggested [here](https://stackoverflow.com/questions/78153617/argocd-doesnt-trigger-kubernetes-job-on-image-tag-update-using-hooks/78155523#78155523).
* It seems that it's not allowed to use Resource Hooks to target syncs of specific resources as mentioned [here](https://github.com/argoproj/argo-cd/issues/7691), so I can't find a solution with ArgoCD Resource Hooks.

In order to avoid regressions in the current job sync behavior,  it's possible to present a new sync-options annotation, something like: `argocd.argoproj.io/sync-options: Force=true,Replace=true,**replaceOnlyOnChange=true**` .
