### ISSUE TITLE
Progressive Sync (RollingSync) does not auto-sync next app in ArgoCD v3

### ISSUE THREAD

**Issue by gojanpaolo** [argoproj/argo-cd#22976]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Progressive Sync (RollingSync) does not auto-sync next app in ArgoCD v3.
The first app gets automatically synced.
The issue does not happen in ArgoCD v2

**To Reproduce**

I have the following `ApplicationSet`
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: foo
      - name: bar
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: nameLabel
              operator: In
              values:
                - foo
        - matchExpressions:
            - key: nameLabel
              operator: In
              values:
                - bar
  template:
    metadata:
      name: '{{.name}}'
      labels:
        nameLabel: '{{.name}}'
    spec:
      project: default
      source:
        path: 'helm/{{.name}}'
        repoURL: https://bitbucket.org/REDACTED.git
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default
```

The state of the apps/appset gets into this eventually

```
$ argocd app list
NAME        CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO                                            PATH      TARGET
argocd/bar  https://kubernetes.default.svc  default    default  OutOfSync  Missing  Manual      <none>      https://bitbucket.org/REDACTED.git  helm/bar  HEAD
argocd/foo  https://kubernetes.default.svc  default    default  Synced     Healthy  Manual      <none>      https://bitbucket.org/REDACTED.git  helm/foo  HEAD
```

**Expected behavior**

All apps should sync progressively. In the example above, bar should sync automatically after foo is healthy.

**Version**

```shell
$ argocd version
argocd: v3.0.0+e98f483
  BuildDate: 2025-05-06T11:50:03Z
  GitCommit: e98f483bfd5781df2592fef1aeed1148f150d9c9
  GitTreeState: clean
  GoVersion: go1.24.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v3.0.0+e98f483
  BuildDate: 2025-05-06T11:50:03Z
  GitCommit: e98f483bfd5781df2592fef1aeed1148f150d9c9
  GitTreeState: clean
  GoVersion: go1.24.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.0.5 2021-03-08T20:53:03Z
  Helm Version: v3.16.1+g5a5449d
  Kubectl Version: v0.32.2
  Jsonnet Version: v0.20.0
```
