### ISSUE TITLE
Introduce a globbing field for the git file generator

### ISSUE THREAD

**Issue by nitishfy** [argoproj/argo-cd#22991]
# Summary

The [Git Dir generator](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators-Git/#git-generator-directories) and [Git file generator](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators-Git/#git-generator-files) currently supports excluding directories and files based on the globbing library defined by the user. The new globbing pattern matching library for git file generator was required because the old globbing pattern matching had some issues that have been [described here](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git-File-Globbing/).

I'm proposing four thing as a part of this enhancement:

1. Remove the `exclude` field from the git generator entirely and prefer negation instead i.e any exclusion would be prefixed with an `!`.
2. Introduce a new field in the git file generator CRD spec such as `newGlobbingEnabled` which when set to true will use the new globbing library else the old globbing library. We are not conerned about the git directory generator for this because it is always using the another globbing library without any issues. Please look at the following pieces of code:
- https://github.com/argoproj/argo-cd/blob/master/applicationset/services/repo_service.go#L42 ( function that is used to fetch directories)
- https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/git.go#L307 (the function that is used to perform inclusion/exclusion using the [`path` libnrary](https://pkg.go.dev/path).)
3.  All of this inclusion/exclusion logic for git dir generator is happening on the generator side. This should be done on the repo server side which means we should get all required directires from [here](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/git.go#L117) without [filtering later](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/git.go#L130). In other words, remove the filtering function from the generato and perform the filtering when trying to fetch directories.
4. Perform the inclusion/exclusion logic on the repo server side for git file generator. It is currently[ happening on the generator side](https://github.com/argoproj/argo-cd/blob/master/applicationset/generators/git.go#L149-L197) and similar to git directory generator, it should be happening on the repo server side. Please read [this](https://github.com/argoproj/argo-cd/pull/22734#discussion_r2066115405) for better understanding.

# Motivation

The current inclusion/exclusion logic for both the Git directory and file generators in Argo CD's ApplicationSet controller introduces inconsistencies and limitations:

1. **Inconsistency in Filtering Location:** Filtering for included or excluded directories and files is currently performed on the generator side, while it would be more appropriate and efficient to delegate this to the repo server, which is already responsible for accessing and processing the Git repository content. Keeping the filtering logic in the generator can lead to duplication of logic and drift between how data is retrieved vs how it is filtered.
2. **Unreliable Globbing Behavior in Git File Generator:** The old globbing logic used in the Git file generator has known issues (see [docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git-File-Globbing/)). Introducing a newGlobbingEnabled flag allows users to opt into a more predictable and accurate globbing implementation while maintaining backward compatibility.
3. **Use Case – Large Monorepos with Complex Structure:** Many organizations using Argo CD manage applications in monorepos with hundreds of directories and files. They rely on flexible glob patterns to include or exclude specific parts of the repo. Moving filtering to the repo server ensures that only relevant data is processed and reduces the amount of work on the ApplicationSet controller, leading to better performance and maintainability.

# Proposal

Already mentioned in the summary section....From an operator perspective, this would look like this:

```
 generators:
    - git:
        files:
          - path: "apps/**/config.json"
          -  path: "!apps/**/test/**"       # exclude test directories
        newGlobbingEnabled: true # use new globbing library only for git file generator
```

If we still want to prefer `exclude` over negation, this would look like:

```
generators:
    - git:
        files:
          - path: "applicationset/examples/git-generator-files-discovery/cluster-config/**/config.json"
          - path: "applicationset/examples/git-generator-files-discovery/cluster-config/*/dev/config.json"
            exclude: true
        newGlobbingEnabled: true # use new globbing library only for git file generator
```
