### ISSUE TITLE
Applicationset only randomly detects changes via git generator (but with webhooks it works)

### ISSUE THREAD

**Issue by raweber42** [argoproj/argo-cd#23009]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The issue is with an ApplicationSet that uses a Git generator. Typically, the Git generator should trigger a refresh of the ApplicationSet when it detects changes. The refresh interval is supposed to be [three minutes](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/#webhook-configuration) by default, and I configured it to 30 secondsv via the `requeueAfterSeconds` property. However, neither interval triggers the refresh as expected. Sometimes, changes take up to a day to reflect. This leads me to suspect some kind of caching issue.

Interestingly, once I installed webhooks, the refresh worked as expected. I'm happy to contribute to resolving this issue if needed! Please feel free to reach out for any further details.

**To Reproduce**

1. Create a helm chart under `https://mydomain.io/test-repo.git`. _Don't_ define the `datacenter` property in the values file under `/dev/values/<FILENAME>.yaml` in order to get the applicationset to error. The structure of the repo should look like this

```
test-repo/
└── dev/
    ├── templates/
    ├── values/
    ├── Chart.yaml
    └── values.yaml
```

3. Create an applicationset with a git generator pointing to the previously created repository. Should look something like this:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-application-set
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      requeueAfterSeconds: 30 # Even this does not work
      repoURL: https://mydomain.io/test-repo.git
      revision: main
      files:
      - path: "dev/values/*.yaml"
      values:
        path: 'dev'
  template:
    metadata:
      name: 'my-application-{{.client}}-{{.values.path}}'
      labels:
        environment: '{{.values.path}}'
    spec:
      project: my-project
      source:
        repoURL: https://mydomain.io/deployment-repo.git
        targetRevision: main
        path: '{{.values.path}}'
        helm:
          releaseName: 'my-application-{{.client}}-{{.values.path}}'
          valueFiles:
            - 'values/{{.cluster}}.yaml'
      destination:
        name: '{{.datacenter}}'
        namespace: my-namespace
```
2. Update `https://mydomain.io/deployment-repo.git`
3. See that even after 30 seconds (as configured in the `requeueAfterSeconds` option) the applicationset is not updated.
4. in my experience it sometimes does not update even for _a day_ 😅 

**Expected behavior**

The applicationset should realize changes in the git repo referenced by the git generator after 30 seconds.

**Screenshots**

**Version**

```shell
v3.0.0+e98f483
```

**Logs**

```
Paste any relevant application logs here.
```
