### ISSUE TITLE
Git generator  in a  merge generator does not support values

### ISSUE THREAD

**Issue by EricPE69** [argoproj/argo-cd#23014]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

When you try to set values in a git generator included in a merge generator you get the error:
```shell
FATA[0000] rpc error: code = Internal desc = reflect.Value.SetMapIndex: value of type interface {} is not assignable to type string
```

**To Reproduce**
Here is the application
```shell
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-nginx-referentiel
  labels:
    service: securite

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
  - merge:
      mergeKeys:
       - name
      generators:
        - git:
            repoURL: ssh://git@xxxxxxxxxxxxxxxxxxxxx:2222/plateforme/k8s/base/argocd/simple-deployment.git
            revision: master
            files:
            - path: "referentiel/**/configuration-cluster.yaml"
            values:        # BUG: does not work
              tag: "v1"   # BUG: does not work
        - list:
            elements:
              - name: a1-sandbox
                values:
                  tag: "v3"
              - name: a2-sandbox
                values:
                  tag: "v2"


  template:
    metadata:
      # name: "nginx-referentiel-{{ .name }}"
      name: "nginx-referentiel-{{ .path.basename }}-{{ .fondation }}"
      labels:
        service: toto
        type: '{{ .type }}'
        tag: '{{ .values.tag }}'

    spec:
      project: plateforme

      source:
              repoURL: ssh://git@xxxxxxxxxxxxxxxxxxx:2222/plateforme/k8s/base/argocd/simple-deployment.git
              targetRevision: master
              path: helm-nginx-referentiel

      destination:
        name: "{{ .name }}"

      syncPolicy:
        automated:
          #   prune: true
          allowEmpty: false
        #   selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=background
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=false
          # - CreateNamespace=true

  syncPolicy:
    applicationsSync: sync

```

**Expected behavior**

I expect no error.

**Version**

```shell
argocd: v3.0.1+2bcef48
  BuildDate: 2025-05-14T15:31:59Z
  GitCommit: 2bcef4877285db808e47b862567b278c3793d056
  GitTreeState: clean
  GoVersion: go1.24.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by kingbj940429** [comment]
@EricPE69 

I tried to reproduce this issue but I couldn't

It worked well ...

so can you give me more information for reproducing this issue :)

**Comment by EricPE69** [comment]
@kingbj940429 

What information can i give you ? Do you test with argocd 2.13 (not 3) ?

**Comment by kingbj940429** [comment]
@EricPE69 
I'm test in argocd v3 

could you give me other example yaml occurs an error?

**Comment by agaudreault** [comment]
I did experience this in the past too (2.13). The error was trying to merge the "values" of both generators. I haven't had time to reproduce on newer versions.

@kingbj940429 if you are not able to reproduce trying different combination of values, I think we can close the issue.

@EricPE69 Can you validate with the master branch as well?

**Comment by kingbj940429** [comment]
@agaudreault 
I will re-try this on 2.13 version and inform you again :)

**Comment by EricPE69** [comment]
@kingbj940429 In the short term we do not plan to update to v3
FYI here is another test case with the same error : matrix with clusters generator + list generator:
````yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-nginx-referentiel
  labels:
    service: securite

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
  - merge:
      mergeKeys:
       - name
      generators:
        - clusters:
            selector:
              matchExpressions:
                - {key: env, operator: In, values: [sandbox, dev]}
            values:
              tag: v1
        - list:
            elements:
              - name: z1469-sandbox
                values:
                  tag: "v3"
              - name: z2358-sandbox
                values:
                  tag: "v2"


  template:
    metadata:
      # name: "nginx-referentiel-{{ .name }}"
      name: "nginx-referentiel-{{ .path.basename }}-{{ .name }}"
      labels:
        service: toto

    spec:
      project: plateforme

      source:
              repoURL: `ssh://git@xxxxxxxxxxxxxxxxxx:2222/plateforme/k8s/base/argocd/simple-deployment.git`
              targetRevision: master
              path: helm-nginx-referentiel-bug

      destination:
        name: "{{ .name }}"

      syncPolicy:
        automated:
          #   prune: true
          allowEmpty: false
        #   selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=background
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=false
          # - CreateNamespace=true

  syncPolicy:
    applicationsSync: sync
```

**Comment by cgartner** [comment]
Wanted to note that I've seen the same error on v2.11 when attempting to get the merge generator working with the cluster and list generators to allow us to override a value on just one of our clusters. I ended up trying this as the [documented example ](https://argo-cd.readthedocs.io/en/release-2.11/operator-manual/applicationset/Generators-Merge/#example-base-cluster-generator-override-cluster-generator-list-generator)for overriding values with a list wasn't working  (`values.targetRevision: 20250702.1285.1`).
```
  generators:
  - merge:
      mergeKeys:
        - name
      generators:
        - clusters:
            selector:
              matchLabels:
                environment: dev
            values:
              targetRevision: 20250702.1280.0
        - list:
            elements:
              - name: cluster-dev-us-east-1
                values:
                  targetRevision: 20250702.1285.1
```
We're planning to update to v3 soon so hopefully that will resolve it 👍
