### ISSUE TITLE
resources not getting deleted after upgrading to argo 3.0.1

### ISSUE THREAD

**Issue by pdeva** [argoproj/argo-cd#23048]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
all our ApplicationSets have this:

```
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
```

but upon deleting one, it shows deleted from argo, but doesnt remove the underlyign resource.
this was not an issue in 2.xx versions.

**To Reproduce**

delete yaml resource

**Expected behavior**
the underlying pod of that resource should be deleted from cluster

**Screenshots**

**Version**

argo 3.0.1
k8s 1.32

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
