### ISSUE TITLE
Surface ControllerRevision revisions in UI

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#2306]
A Kubernetes Controller revision looks like:
```
kind: ControllerRevision
metadata:
  labels:
    app: nginx
    controller.kubernetes.io/hash: c7cd8d57f
  name: web-c7cd8d57f
  namespace: statefulset
revision: 2
```

The `revision: 2` should be surfaced to the UI as an InfoItem, just like how revisions are surfaced for Deployments
