### ISSUE TITLE
Sync error while everything is working

### ISSUE THREAD

**Issue by LeeMonZ** [argoproj/argo-cd#23069]
I have a template for my services that looks like this

```
{{- range $key, $app := $.Values.application_dev }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  namespace: {{ $app.namespace }}
  labels:
    app: {{ $key }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      imagePullSecrets:
      - name: {{ $.Values.nexusSecret }}
      containers:
      - name: {{ $key }}
        image: "{{ $app.image }}:{{ $app.tag }}"
        imagePullPolicy: Always
        envFrom:
        {{- if ($.Files.Glob $app.configmap) }}
        - configMapRef:
            name: {{ $key }}
        {{ end }}
{{ end }}
```
And values file:
```  
check:
    tag: dev
    configmap: "configmaps/check.conf"
```
File configmaps/check.conf exists

If i use helm template I have a correct yaml. In argocd I can see respective configmap, which is correct.
```
apiVersion: v1
data:
  check.conf: |-
    server_port: 8080
    server_max_http_header_size: 10KB
    management_server_port: 9090
    springdoc_enabled: true
    springdoc_application_path: /check
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"check.conf":"server_port:
      8080\nserver_max_http_header_size: 10KB\nmanagement_server_port:
      9090\nspringdoc_enabled: true\nspringdoc_application_path:
      /check"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"o2o-dev-app"},"name":"check","namespace":"o2o-dev"}}
  creationTimestamp: '2025-05-20T18:52:17Z'
  labels:
    app.kubernetes.io/instance: o2o-dev-app
  name: check
  namespace: o2o-dev
```
But in sync status I have an error
```
failed exit status 1: Error: template: application_dev/templates/template.yaml:35:33: executing "application_dev/templates/template.yaml" at <$app.configmap>: wrong type for value; expected string; got interface {} Use --debug flag to render out invalid YAML
```
If I use new clean installation of argocd I have no errors but It appears later for some reason. How can I fix this?
I am also using argocd-image-updater if it is relevant.
