### ISSUE TITLE
Surface tooling versions in `/api/version`

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#2311]
Just like ksonnetVersion, we should surface the versions of:
* kustomize
* helm
* kubectl

```yaml
{
"Version": "v1.2.1+a6a394b.dirty",
"BuildDate": "2019-09-12T23:09:35Z",
"GitCommit": "a6a394ba93a2a56981a45b9395e245e5210eaa35",
"GitTreeState": "dirty",
"GoVersion": "go1.12.6",
"Compiler": "gc",
"Platform": "linux/amd64",
"KsonnetVersion": "0.13.1"
}
```
