### ISSUE TITLE
ServerSideDiff not detecting changes.

### ISSUE THREAD

**Issue by klaudworks** [argoproj/argo-cd#23126]
**Describe the bug**

If server side diff is enabled, Argo sometimes does not detect diffs when fields are added to a resource or removed from a resource. 

**To Reproduce**

*Note: To really replicate the issue, you would have to install the [Strimzi Kafka Operator](https://strimzi.io/quickstarts/).*

1. Enable server side diff via Annotation: `argocd.argoproj.io/compare-options=ServerSideDiff=true,IncludeMutationWebhook=true`.

2. Apply `KafkaConnector` Resource via ArgoCD:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: backup-connect-cluster
  name: s3-sink-consumer-offsets
  namespace: kimi
spec:
  autoRestart:
    enabled: true
  class: io.lenses.streamreactor.connect.aws.s3.sink.S3ConsumerGroupsSinkConnector
  config:
    config.providers: env
    config.providers.env.class: io.lenses.connect.secrets.providers.ENVSecretProvider
    connect.s3.aws.access.key: ${env::AWS_ACCESS_KEY_ID}
    connect.s3.aws.auth.mode: Credentials
    connect.s3.aws.region: de
    connect.s3.aws.secret.key: ${env::AWS_SECRET_ACCESS_KEY}
    connect.s3.custom.endpoint: https://s3.eu-central-1.ionoscloud.com
    connect.s3.location: kimi-nico-test-backup-6716d3:kafka/consumer-offsets
    connect.s3.vhost.bucket: true
    key.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    topics: __consumer_offsets
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
  tasksMax: 1
```

3. Remove the field `autoRestart` via git.  Then, Argo shows the live manifest correctly with autoRestart.enabled=true and it shows the desired manifest correctly with autoRestart field missing. However, there is no Diff shown. Turning off server side diff fixes the issue.

**Expected behavior**

Argo detecting diffs properly with server side diff.

**Version**

Argo CD Version: v3.0.0+e98f483
Kubernetes Versions: 1.32.0 and 1.32.2
