### ISSUE TITLE
.app.status.resources[*].health.status is not available in notification templates (shows <no value>), while .kind and .name are accessible

### ISSUE THREAD

**Issue by tkgeng** [argoproj/argo-cd#23135]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I’m using the App of Apps pattern in Argo CD, and I want to send webhook notifications when any Deployment inside an application is not healthy.

To do this, I tried accessing `.app.status.resources[*].health.status` in my notification template. However, this field is always evaluated as `<no value>`, even though `.kind` and `.name` are accessible without issues.

When I run argocd app get  my-app  -o yaml, I can see that `.status.resources[*].health.status` is indeed present and contains values like Degraded or Healthy, so the data exists in the Application object.

It seems that the .health.status field from app.status.resources is not available in the notification template context at render time, even though other fields like .kind and .name are.
**To Reproduce**

_argocd-notifications-cm_
```
apiVersion: v1
data:
  context: |
    argocdUrl: http://my-cicd
  service.webhook.my-hook: |
    url: https://my-hook-url
    headers:
      - name: Content-Type
        value: application/json
  subscriptions: |
    - recipients:
        - my-hook
      triggers:
        - deployment-pod-failed
  template.deployment-pod-failed: |
    webhook:
      my-hook:
        method: POST
        path: /hook-url
        body: |
          all app get .health.status test
          {{- range .app.status.resources}}
            {{- if (eq .kind "Deployment") -}}
               {{.name}}
               {{.health.status}}
            {{- end -}}
          {{- end}}
  trigger.deployment-pod-failed: |
    - when: app.status.health.status == 'Degraded'
      send: [deployment-pod-failed]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-cm
  namespace: argocd
```
`argocd admin notifications template notify deployment-pod-failed my-app --recipient my-hook`  output like this
```
request to {all app get .health.status test my-app1
     <no value>my-app2
     <no value>
```
`argocd app get my-app  -o yaml` output like this
```
argocd app get my-app  -o yaml

metadata:
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/overlays/dev
    repoURL: https://mygit.com/app.git
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-05-20T03:31:32Z"
    status: Degraded
  history:
  - deployStartedAt: "2025-05-17T11:02:08Z"
    deployedAt: "2025-05-17T11:02:09Z"
    id: 3
    initiatedBy:
      username: admin
    revision: 565cbd8ba0224935417bb7891525999571a4a324
    source:
      path: app/overlays/dev
      repoURL: https://mygit.com/app.git
  operationState:
    finishedAt: "2025-05-23T05:42:14Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 2ffc26a8e3beb169a08b1b308d14d4ba92febb19
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2025-05-23T05:42:13Z"
    syncResult:
      resources:
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/my-app1 unchanged
        name: my-app1
        namespace: dev
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/my-app2 unchanged
        name: my-app2
        namespace: dev
        status: Synced
        syncPhase: Sync
        version: v1        
      revision: 2ffc26a8e3beb169a08b1b308d14d4ba92febb19
      source:
        path: app/overlays/dev
        repoURL: https://mygit.com/app.git
  reconciledAt: "2025-05-24T05:55:58Z"
  resourceHealthSource: appTree
  resources:
  - group: apps
    health:
      message: Deployment "my-app1" exceeded its progress deadline
      status: Degraded
    kind: Deployment
    name: my-app1
    namespace: app
    status: Synced
    version: v1
  - group: apps
    health:
      message: Deployment "my-app2" exceeded its progress deadline
      status: Degraded
    kind: Deployment
    name: my-app2
    namespace: app
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Kustomize
  summary:
    images:
    - ghcr.io/xx/app:2.22
  sync:
    comparedTo:
      destination:
        server: https://kubernetes.default.svc
      source:
        path: app/overlays/dev
        repoURL: https://mygit.com/app.git
    status: Synced

```
**Expected behavior**

`argocd admin notifications template notify deployment-pod-failed my-app --recipient my-hook`  output like this
```
request to {all app get .health.status test my-app1
     Degraded my-app2
     Degraded
```

**Version**

`argocd version`

```
argocd: v3.0.0+e98f483
  BuildDate: 2025-05-06T14:00:37Z
  GitCommit: e98f483bfd5781df2592fef1aeed1148f150d9c9
  GitTreeState: clean
  GoVersion: go1.24.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.0.0+e98f483
  BuildDate: 2025-05-06T11:25:45Z
  GitCommit: e98f483bfd5781df2592fef1aeed1148f150d9c9
  GitTreeState: clean
  GoVersion: go1.24.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.6.0 2025-01-14T15:12:17Z
  Helm Version: v3.17.1+g980d8ac
  Kubectl Version: v0.32.2
  Jsonnet Version: v0.20.0
```

**Comment by thiagowfx** [comment]
I can reproduce this as well.

**Comment by ggiacobazzi** [comment]
Thumbs up for this, when trying to setup templates I cannot access `".app.status.resources[*].health"`, thus blocking custom notifications based on status and/or message

```  
- group: redacted
  health:
    message: All customer deployments are ready.
    status: Healthy
  kind: CustomCrd
  name: test1
  namespace: test1
  status: Synced
  version: v1alpha1
```

Template:
```
[...]
{{range $res := .app.status.resources}}
{
  "title": "Resource Details",
  "value": "*{{$res.kind}}/{{$res.name}}* ({{$res.health}})",
  "short": false
}
{{end}}
```
Slack:

```
Resource Details
CustomCrd/test1 (<no value>)
```
