### ISSUE TITLE
New Globbing issues with doublestar supported pattern

### ISSUE THREAD

**Issue by hieulw** [argoproj/argo-cd#23158]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Git file generator in Argo CD v2.11.3 does not recognize files when using a glob pattern with brace expansion, such as */{cronjob,deployment}/*/values-ppd.yaml, even after enabling the new globbing mechanism by setting applicationsetcontroller.enable.new.git.file.globbing: "true" in the argocd-cmd-params-cm ConfigMap. The pattern */*/*/values-ppd.yaml works as expected, correctly matching files, but the brace expansion pattern fails to match any files. Local testing with the doublestar package's FilepathGlob function confirms that the brace expansion pattern works correctly outside of Argo CD, suggesting an issue with Argo CD's implementation of the new globbing mechanism.

**To Reproduce**

Configure the argocd-cmd-params-cm ConfigMap to enable the new globbing mechanism:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  applicationsetcontroller.enable.new.git.file.globbing: "true"
```
Create an ApplicationSet with the following Git file generator configuration:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://<your-repo-URL>
      revision: HEAD
      files:
      - path: "*/{cronjob,deployment}/*/values-ppd.yaml"
      values:
        name: "{{index .path.segments 2}}"
        namespace: "{{index .path.segments 0}}"
        type: "{{index .path.segments 1}}"
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: https://<your-repo-URL>
        targetRevision: HEAD
        path: "{{index .path.segments 0}}/{{index .path.segments 1}}/{{index .path.segments 2}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
```
The repository contains a structure like:
```
├── billing-system
│   └── cloud-run
│       └── national-address-log-forwarder
│           ├── values-dev.yaml
│           └── values-prod.yaml
├── national-address
    ├── cronjob
    │   └── payment-sync
    │       ├── values-dev.yaml
    │       ├── values-obd.yaml
    │       ├── values-ppd.yaml
    │       ├── values-prod.yaml
    │       └── values-uat.yaml
    └── deployment
        ├── frontend
            ├── values-dev.yaml
            ├── values-obd.yaml
            ├── values-ppd.yaml
            ├── values-prod.yaml
            └── values-uat.yaml
...
```

**Expected behavior**

The Git file generator should recognize files matching the pattern */{cronjob,deployment}/*/values-ppd.yaml when applicationsetcontroller.enable.new.git.file.globbing: "true" is set, as the doublestar package supports brace expansion (e.g., {cronjob,deployment}) according to its documentation. The ApplicationSet should generate applications for files like namespace1/cronjob/app1/values-ppd.yaml and namespace1/deployment/app2/values-ppd.yaml, with the name, namespace, and type values correctly extracted from the path segments.

**Screenshots**

**Version**

```shell
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2025-05-26T21:24:01Z" level=info msg="generated 0 applications" applicationset=argocd/ppd generator="{nil nil &GitGenerator{RepoURL:https://@dev.azure.com/***,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:*/{cronjob,deployment}/*/values-ppd.yaml,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{name: {{index .path.segments 2}},namespace: {{index .path.segments 0}},type: {{index .path.segments 1}},},} nil nil nil nil nil nil nil}"
time="2025-05-26T21:30:03Z" level=info msg="generated 7 applications" applicationset=argocd/obd generator="{nil nil &GitGenerator{RepoURL:https://@dev.azure.com/***,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:*/*/*/values-obd.yaml,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{name: {{index .path.segments 2}},namespace: {{index .path.segments 0}},type: {{index .path.segments 1}},},} nil nil nil nil nil nil nil}"
```
