### ISSUE TITLE
argocd app diff not working for Service .spec.ports field with server side apply diff

### ISSUE THREAD

**Issue by Vince-Chenal** [argoproj/argo-cd#23171]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd app diff` does not see diffs for certain fields while using ServerSide apply/diff.
Here I had the problem with `.spec.ports` field of a `Service` object. I imagine other resources are impacted but I did not test.

**To Reproduce**

Application example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  name: svc-diff
  namespace: argo-cd
spec:
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
  destination:
    name: somecluster
    namespace: svc-diff
  project: someproject
  source:
    path: manifests
    repoURL: https://github.com/somerepo
    targetRevision: main
```

With `https://github.com/somerepo/manifests` containing:

service.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
    targetPort: 53
  - name: tcp-53
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    some: selector
```

and in another branch named `diff`:

service.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    some: selector
    another: selector
```

Then, execute `argocd app diff argo-cd/svc-diff --revision <diff branch HEAD commit sha>`:
```diff

===== /Service svc-diff/svc ======
24a25
>     someother: selector
```

The change on Service `.spec.ports` field is not reported.

With `kubectl diff -f manifests/service.yaml --server-side=true --field-manager=argocd-controller` the change is reported:

```diff
diff -u -N /var/folders/v6/tn58v7b91vz8zqg8s65gglbm0000gp/T/LIVE-2244811294/v1.Service.svc-diff.svc /var/folders/v6/tn58v7b91vz8zqg8s65gglbm0000gp/T/MERGED-697597641/v1.Service.svc-diff.svc
--- /var/folders/v6/tn58v7b91vz8zqg8s65gglbm0000gp/T/LIVE-2244811294/v1.Service.svc-diff.svc    2025-05-27 17:41:26
+++ /var/folders/v6/tn58v7b91vz8zqg8s65gglbm0000gp/T/MERGED-697597641/v1.Service.svc-diff.svc   2025-05-27 17:41:26
@@ -1,8 +1,6 @@
 apiVersion: v1
 kind: Service
 metadata:
-  annotations:
-    argocd.argoproj.io/tracking-id: svc-diff:/Service:svc-diff/svc
   creationTimestamp: "2025-05-27T15:11:37Z"
   name: svc
   namespace: svc-diff
@@ -21,8 +19,13 @@
     port: 53
     protocol: UDP
     targetPort: 53
+  - name: tcp-53
+    port: 53
+    protocol: TCP
+    targetPort: 53
   selector:
     some: selector
+    someother: selector
   sessionAffinity: None
   type: ClusterIP
 status:
```

**Expected behavior**

The change should be reported by `argocd app diff`

**Screenshots**

N/A

**Version**

```shell
> argocd version
argocd: v3.0.3+a14b012
  BuildDate: 2025-05-21T19:57:07Z
  GitCommit: a14b0125fe02ff953caffc59e55016e5872d45bf
  GitTreeState: clean
  GoVersion: go1.24.3
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.0.3+a14b012
  BuildDate: 2025-05-21T18:19:53Z
  GitCommit: a14b0125fe02ff953caffc59e55016e5872d45bf
  GitTreeState: clean
  GoVersion: go1.24.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.6.0 2025-01-14T15:12:17Z
  Helm Version: v3.17.1+g980d8ac
  Kubectl Version: v0.32.2
  Jsonnet Version: v0.20.0
```

**Logs**

N/A
