### ISSUE TITLE
application external url falsely uses backend servicePort

### ISSUE THREAD

**Issue by tschonnie** [argoproj/argo-cd#2318]
**Describe the bug**

I think it is wrong that the external url for an application is built with the backend servicePort. This port is just the port of the internal service, but not the external ingress port.

**To Reproduce**
when you use this ingress, the external application url in argocd is http://v-k8s-liberty-demo.banking-k8s-i.k8s.m086:9080/  . which is wrong, because accoring to the ingress rule, the ingress port is http (80).
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: v-k8s-liberty-demo-server
  namespace: v-k8s-liberty-demo
spec:
  rules:
    - host: v-k8s-liberty-demo.banking-k8s-i.k8s.m086
      http:
        paths:
          - backend:
              serviceName: v-k8s-liberty-demo-server
              servicePort: 9080
```

**Expected behavior**

Use the port of the ingress rule, not the internal backend servicePort. as described in https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

**Version**
1.2.0
