### ISSUE TITLE
ignoreDifferences not effective for Secret

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#2322]
**Describe the bug**

ignoreDifferences configured for Secret but it still remains `OutOfSync`.

**To Reproduce**

Apply the example configuration

**Example**

With ignoreDifferences configured as below

```
  ignoreDifferences:
  - group: core
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
    kind: Secret
    name: kubedb-operator-apiserver-cert
    namespace: kubedb
  - group: apiregistration.k8s.io
    jsonPointers:
    - /spec/caBundle
    kind: APIService
```

The secret is still `OutOfSync`, showing differences on

```
data:
  tls.crt: ++++
  tls.key: +++
```

caBundle is NOT displayed `OutOfSync` though.

**Expected behavior**

Secret differences are ignored

**Screenshots**

N/A

**Version**

Custom build from master branch

```shell
argocd: v1.2.0+674978c
  BuildDate: 2019-09-04T21:27:44Z
  GitCommit: 674978cd587701b39e81fce6d5c960b6d76d5882
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.1.2+67d8f43
  BuildDate: 2019-09-17T05:53:35Z
  GitCommit: 67d8f430ef3f6b7046c94f3e783289a99d4ea97e
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

N/A

**Have you thought about contributing a fix yourself?**

It could be related to #2298
