### ISSUE TITLE
Add support for labels and selectors in AppProject destination name

### ISSUE THREAD

**Issue by nea1** [argoproj/argo-cd#23279]
# Summary

Currently the `spec.destinations[].name` field supports limited matching of the target cluster _name_ using the `!`, `*` syntax. This is only useful if the cluster name contains all the metadata that you want to base permissions on, and the name is structured in a manner that can be matched on. It would be more flexible and powerful if we could base destination cluster permissions on the cluster secret's _labels_.

# Motivation

Suppose you have a number of clusters labelled similarly to this:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: payments-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    example.com/cloud-provider: aws
    example.com/environment: prod
    example.com/purpose: payments
    example.com/pci-scope: pci
    example.com/region: us-west-2
```

Currently if you want to allow an application to deploy to say clusters with  `example.com/purpose: payments` then as this _happens to be reflected in the cluster name_ you can do this:

```yaml
spec:
    destinations:
    - name: payments*
```

However if we want to permit an application to deploy to just the pci clusters, or to say just us-west-2 clusters in aws, then this is not possible

# Proposal

Add support for label selectors and expressions in app projects to match on cluster secret labels

e.g. allow list an application to deploy to non-pci, aws, us-west-2 clusters

```yaml
spec:
    destinations:
    - clusterSelector:
          matchLabels:
          - example.com/region: us-west-2
          - example.com/cloud-provider: aws
          matchExpressions:
          - { key: example.com/pci-scope, operator: NotIn, values: [pci] }
```
