### ISSUE TITLE
Argocd overly conservative with RespectIgnoreDifferences for Rollouts

### ISSUE THREAD

**Issue by santi1s** [argoproj/argo-cd#23283]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD handling of  RespectIgnoreDifferences  is being overly conservative in the case of Rollouts and not updating any fields in the containers, even though only image and imagePullPolicy should be ignored. This does not happen with deployments

**To Reproduce**

1. Configured ignoreDifferences for spec.template.spec.initContainers[].imagePullPolicy and .spec.template.spec.initContainers[].image for rolouts and deployments
```k get cm -n argocd argocd-cm -ojson | jq .data | grep ignoreDifferences
  "resource.customizations.ignoreDifferences.apps_Deployment": "jqPathExpressions:\n- .spec.template.spec.containers[].image\n- .spec.template.spec.containers[].imagePullPolicy\n- .spec.template.spec.initContainers[].image\n- .spec.template.spec.initContainers[].imagePullPolicy\n",
  "resource.customizations.ignoreDifferences.argoproj.io_Rollout": "jqPathExpressions:\n- .spec.template.spec.containers[].image\n- .spec.template.spec.containers[].imagePullPolicy\n- .spec.template.spec.initContainers[].image\n- .spec.template.spec.initContainers[].imagePullPolicy
```
2. Configure the following apps 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx_rollout
    repoURL: https://github.com/xxxx/kube
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx_deployment
    repoURL: https://github.com/xxxx/kube
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
```
whith the following deployment and rollout manifests

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "25m"
            memory: "70Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "28m"
            memory: "70Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
  revisionHistoryLimit: 2
  strategy:
    canary: {}
```
3. Push an update of any of the cpu or memory resources to GitHub
4. Both deployment and rollout will show OutOfSync

5. Sync the deployment and rollout apps ( RespectIgnoreDifferences=true) 
```shell
argocd app sync nginx-deployment-app --sync-option RespectIgnoreDifferences=true
argocd app sync kube-test --sync-option RespectIgnoreDifferences=true
```
The Sync operation shows as  successfull for boths apps but the Rollout app stays out of sync

6. Sync the rollout app ( RespectIgnoreDifferences=false) 
```shell
argocd app sync kube-test --sync-option RespectIgnoreDifferences=fale
```
The Sync operation shows as  successfull and the rollout app changes to Synced Status
**Expected behavior**

The sync operation for the rollout with RespectIgnoreDifferences=true should have updated the spec.template.spec.containers[0].resources

**Version**

```shell
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T15:31:13Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v3.0.5+af9ebac
  BuildDate: 2025-05-29T17:30:53Z
  GitCommit: af9ebac0bb35dc16eb034c1cefaf7c92d1029927
  GitTreeState: clean
  GoVersion: go1.24.1
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.6.0 2025-01-14T15:12:17Z
  Helm Version: v3.17.1+g980d8ac
```

**Logs**

Below result of parsing the request body of the rquests made from argocd-application-controlle to API server 
The "CHANGES DETECTED" section in the parser shows the differences between:
  - oldObject: What was in the cluster before the API request
  - object: What the API request is trying to set

  An empty "CHANGES DETECTED" section means the parser found no differences between the old and new objects in the fields it's checking (image, imagePullPolicy, and resources)

**Deployment App Sync RespectIgnoreDifferences=true**
```
================================================================================
REQUEST #17
================================================================================
Operation: UPDATE
User: system:serviceaccount:argocd:argocd-application-controller
UID: 3a4422a7-4b14-472d-bc0a-9589d1862a59
Resource: apps/v1/deployments
Name: nginx-deployment
Namespace: default

Object Kind: Deployment
Object Name: nginx-deployment

Container 1: nginx
  Image: nginx:1.24
  ImagePullPolicy: IfNotPresent
  Resources:
    Requests: CPU=25m, Memory=70Mi
    Limits: CPU=500m, Memory=256Mi

--- CHANGES DETECTED ---

Container 'nginx' changes:
  - CPU request: 28m -> 25m
  - Memory request: 60Mi -> 70Mi

--- REQUEST SOURCE ---
Username: system:serviceaccount:argocd:argocd-application-controller
Groups: system:serviceaccounts, system:serviceaccounts:argocd, system:authenticated
```

**Rollout App Sync RespectIgnoreDifferences=true**
```
================================================================================
REQUEST #18
================================================================================
Operation: UPDATE
User: system:serviceaccount:argocd:argocd-application-controller
UID: faad7fba-b44c-4ba3-b0c7-854b516cc555
Resource: argoproj.io/v1alpha1/rollouts
Name: nginx-rollout
Namespace: default

Object Kind: Rollout
Object Name: nginx-rollout

Container 1: nginx
  Image: nginx:1.23
  ImagePullPolicy: Always
  Resources:
    Requests: CPU=25m, Memory=60Mi
    Limits: CPU=500m, Memory=256Mi

--- CHANGES DETECTED ---

--- REQUEST SOURCE ---
Username: system:serviceaccount:argocd:argocd-application-controller
Groups: system:serviceaccounts, system:serviceaccounts:argocd, system:authenticated
```

**Rollout App Sync RespectIgnoreDifferences=false**
```
================================================================================
REQUEST #19
================================================================================
Operation: UPDATE
User: system:serviceaccount:argocd:argocd-application-controller
UID: 6bfc88bc-a6ec-4176-9f43-561275609610
Resource: argoproj.io/v1alpha1/rollouts
Name: nginx-rollout
Namespace: default

Object Kind: Rollout
Object Name: nginx-rollout

Container 1: nginx
  Image: nginx:latest
  ImagePullPolicy: Always
  Resources:
    Requests: CPU=28m, Memory=70Mi
    Limits: CPU=500m, Memory=256Mi

--- CHANGES DETECTED ---

Container 'nginx' changes:
  - Image: nginx:1.23 -> nginx:latest
  - CPU request: 25m -> 28m
  - Memory request: 60Mi -> 70Mi

--- REQUEST SOURCE ---
Username: system:serviceaccount:argocd:argocd-application-controller
Groups: system:serviceaccounts, system:serviceaccounts:argocd, system:authenticated
```

**Comment by santi1s** [comment]
After opening this issued discovered issue https://github.com/argoproj/argo-cd/issues/17694
Seems the same issue . Is my assumption correct ? If so, any ETA for a fix or potential workaround ?

**Comment by cshintov** [comment]
Yup, facing similar issue! Seems like we still can't do this:

```
Expected behavior

It should be possible to ignore different individual array elements.
```

**Comment by crenshaw-dev** [comment]
The fix for https://github.com/argoproj/argo-cd/issues/17694 is in 3.2.0-rc1. Can you please test and confirm whether that version fixes the issue?

**Comment by santi1s** [comment]
@crenshaw-dev  tested for v3.2.0-rc4 and still not working

**Comment by santi1s** [comment]
@crenshaw-dev  Tested on v3.6.0-rc1 — still reproducing.

Setup: fresh kind cluster, ArgoCD v3.6.0-rc1 (non-HA install manifest), Argo Rollouts CRD only (no controller needed for this).

```yaml
argocd-cm patch:
data:
  resource.customizations.ignoreDifferences.apps_Deployment: |
    jqPathExpressions:
    - .spec.template.spec.containers[].image
    - .spec.template.spec.containers[].imagePullPolicy
    - .spec.template.spec.initContainers[].image
    - .spec.template.spec.initContainers[].imagePullPolicy
  resource.customizations.ignoreDifferences.argoproj.io_Rollout: |
    jqPathExpressions:
    - .spec.template.spec.containers[].image
    - .spec.template.spec.containers[].imagePullPolicy
    - .spec.template.spec.initContainers[].image
    - .spec.template.spec.initContainers[].imagePullPolicy

Applications:
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx_deployment
    repoURL: <git repo>
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rollout-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx_rollout
    repoURL: <git repo>
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
```

Manifests in git (final state, after the resources bump described below — originally cpu: "25m" / memory: "70Mi", bumped to cpu: "28m" / memory: "80Mi"):

```yaml
nginx_deployment/deployment.yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "28m"
            memory: "80Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
```

nginx_rollout/rollout.yaml:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "28m"
            memory: "80Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
  revisionHistoryLimit: 2
  strategy:
    canary: {}
```

Repro steps:
1. Sync both apps initially (both in-sync with git).
2. Drift the live image on both Deployment and Rollout out-of-band (simulating an external image update — e.g. kubectl patch ... image=nginx:1.24 / nginx:1.23).
3. Bump resources.requests in git to the values above (cpu: 25m→28m, memory: 70Mi→80Mi) and commit.
4. Refresh + argocd app sync <app> --sync-option RespectIgnoreDifferences=true for both.

Result:
- Deployment: image stays drifted (correctly ignored), resources.requests updates to 28m/80Mi from git. Synced.
- Rollout: image stays drifted (correctly ignored), but resources.requests stays at 25m/70Mi — does not pick up the git change. The sync operation reports succeeded (rollout.argoproj.io/nginx-rollout configured), yet the app remains OutOfSync, and the object's kubectl.kubernetes.io/last-applied-configuration confirms the patch ArgoCD actually computed still carries the old resources values.

PR #28220 ("respect ignore differences for individual array elements in CRDs") is in this release's changelog and looks related, but I believe it addresses a different code path — ignoring a specific array element by key — rather than this case, where a whole-array jqPathExpressions ignore on a CRD appears to cause an unrelated sibling field (resources) in the same array element to also get dropped from the computed sync patch. Deployment (built-in resource) doesn't hit this; Rollout (CRD) does.
