### ISSUE TITLE
Failed edit application with plugin type requiring environment

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#2330]
**Describe the bug**

Edit application from either UI/CLI will fail if the content management plugin requires environment variable.

Create and sync application works though.

**To Reproduce**

1. `argocd edit app ...`
2. Make some modification
3. Save and exit
4. See errors

**Example**

```
- name: helmfile
  generate:                      # Command to generate manifests YAML
    command: ["/bin/sh", "-c"]
    args: ["helmfile --selector name=${HELMFILE_SELECTOR_NAME:-${ARGOCD_APP_NAME}} template --skip-deps"]
```

```
metadata:
  name: kubedb-catalog
  namespace: argocd
spec:
  destination:
    namespace: kubedb
    server: https://kubernetes.default.svc
  project: helmfile
  source:
    path: helmfile
    plugin:
      name: helmfile
    repoURL: ssh://argocd@gitrepo
    targetRevision: master
```

**Expected behavior**

Spec updated without error

**Screenshots**

N/A

**Version**

Custom build based on master branch

```shell
argocd: v1.2.0+674978c
  BuildDate: 2019-09-04T21:27:44Z
  GitCommit: 674978cd587701b39e81fce6d5c960b6d76d5882
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.1.2+67d8f43
  BuildDate: 2019-09-17T05:53:35Z
  GitCommit: 67d8f430ef3f6b7046c94f3e783289a99d4ea97e
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
# Failed to update application spec:
# rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in helmfile: rpc error: code = Unknown desc = `/bin/sh -c helmfile --selector name=${HELMFILE_SELECTOR_NAME:-${ARGOCD_APP_NAME}} template --skip-deps` failed exit status 1: in ./helmfile.yaml: Malformed label: name=. Expected label in form k=v or k!=v
```

**Have you thought about contributing a fix yourself?**

YES
