### ISSUE TITLE
Child app not installed when using same private repo for parent and child, in app-of-apps pattern

### ISSUE THREAD

**Issue by syst0m** [argoproj/argo-cd#2333]
**Describe the bug**

Using the app-of-apps pattern to bootstrap the cluster with `system-y` helm charts.
Both the parent and the child helm templates are in the same repo.
The parent app is installed successfully.
However, the child app shows up as synced, but the chart is not installed in the cluster.

**To Reproduce**
1. Bootstrap Argo CD with the following manifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: XXXX
    targetRevision: staging
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  helm:
    valueFiles:
    - values.yaml

  syncPolicy:
    automated:
      prune: true # Should resources be pruned during auto-syncing?
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
```
2. Used the following helm template for child app:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}

  project: default

  source:
    path: system/cluster-autoscaler
    repoURL: xxx
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated:
      selfHeal: true
```
3. Wait for Sync to install the Argo as parent app
4. Child app (helm cluster-autoscaler chart) shows up as synced, but is not installed in the cluster

**Example**

Override of helm cluster-autoscaler chart:
https://github.com/syst0m/argocd-example-apps/tree/master/cluster-autoscaler

**Expected Behaviour**

Expected the child app (cluster-autoscaler helm chart) to be installed in the kube-system namespace.

**Screenshots**
![1](https://user-images.githubusercontent.com/15815107/65260660-9f429500-dafe-11e9-9849-f072625ca990.png)

**Version**

Non-HA v1.2.1

**Logs**

```
W0919 15:36:59.885925       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist

```

**Have you thought about contributing a fix yourself?**

Yes.
