### ISSUE TITLE
Provide an option to exclude all resources of an API group and include only the ones that needs to be included

### ISSUE THREAD

**Issue by anandf** [argoproj/argo-cd#23344]
# Summary

`resource.inclusions` and `resource.exclusions` (in `argocd-cm` configmap) are useful settings to control the resources that Argo CD watches for. In order to reduce the number of watches, I want to exclude all resources of an API group by default and want to include only those resources I am interested in managing it via Argo CD. But, with the current implementation (v3), if a resource is matching both `resources.inclusions` and `resource.exclusions`, then the resource gets excluded. i.e `resource.exclusions` setting gets priority over the `resource.inclusions` setting.

The proposal is to inverse this priority order so that I can exclude multiple resources using a glob pattern `*` and include only resources that needs to be managed via Argo CD.

# Motivation

Let's say I am deploying the `guestbook` [guestbook](https://github.com/argoproj/argocd-example-apps/tree/master/guestbook) example app. The resources that guestbook Argo CD `Application` manages are `Deployment`, `Service` and its children/related resources. So I can include a `resource.inclusions` settings in `argocd-cm` configmap as below.
```
data:
  resource.inclusions: |
    - apiGroups:
        - ""
      clusters:
        - '*'
      kinds:
        - Endpoints
        - ServiceAccount
        - ConfigMap
        - Pod
        - Service
    - apiGroups:
        - apps
      clusters:
        - '*'
      kinds:
        - ReplicaSet
        - Deployment

```
and exclude all other resources in `argocd-cm` config map via `resource.exclusions` as below
```
data:
  resource.exclusions: |
    - apiGroups:
        - ""
      clusters:
        - '*'
      kinds:
        - '*'
    - apiGroups:
        - apps
      clusters:
        - '*'
      kinds:
        - '*'
```

Currently with the above settings, the app sync fails as both `Deployment` and `Service` remains in the exclusion list.

![Image](https://github.com/user-attachments/assets/9fd88b2d-985b-4324-9339-d6c617b05bdd)

![Image](https://github.com/user-attachments/assets/7f3cc01a-ff8d-4ce8-b491-d6f599ff8b9d)

# Proposal

How do you think this should be implemented?

Change the logic in this method `func (rf *ResourcesFilter) IsExcludedResource(apiGroup, kind, cluster string) bool` 
https://github.com/argoproj/argo-cd/blob/7ee59d02b6c0fee81e79b6e995cdc2e933e09912/util/settings/resources_filter.go#L64
as below
```
        // if excluded, and not included, then do not allow
	if rf.isExcludedResource(apiGroup, kind, cluster) && !rf.isIncludedResource(apiGroup, kind, cluster) {
		return true
	}
```
