### ISSUE TITLE
ArgoCD not detecting changes in aggregation labels despite ignoreAggregatedRoles only applying to rules

### ISSUE THREAD

**Issue by rgarcia89** [argoproj/argo-cd#23352]
## Description

ArgoCD is not detecting changes in the `rbac.authorization.k8s.io/aggregate-to-admin` label of a ClusterRole, despite the documentation stating that `ignoreAggregatedRoles: true` should only ignore changes to the rules that are automatically added via aggregation, not the aggregation labels themselves.

## Current Behavior

When a ClusterRole has a change in its aggregation labels (e.g., `rbac.authorization.k8s.io/aggregate-to-admin: 'true'` is removed), ArgoCD does not detect this as a difference requiring sync.

## Expected Behavior

ArgoCD should detect changes to aggregation labels as differences requiring sync, as the `ignoreAggregatedRoles: true` setting should only ignore changes to the rules that are automatically added via aggregation.

## Steps to Reproduce

1. Configure ArgoCD with `resource.compareoptions.ignoreAggregatedRoles: true`
2. Deploy a ClusterRole with the label `rbac.authorization.k8s.io/aggregate-to-admin: 'true'`
3. Update the manifest to remove this label
4. Observe that ArgoCD does not detect this change

### Live Manifest
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      kyverno:rbac.authorization.k8s.io/ClusterRole:kyverno/kyverno:rbac:admin:policies
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.2
    helm.sh/chart: kyverno-3.4.2
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
  name: kyverno:rbac:admin:policies
rules:
  - apiGroups:
      - kyverno.io
    resources:
      - cleanuppolicies
      - clustercleanuppolicies
      - policies
      - clusterpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
```

### Desired Manifest
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      kyverno:rbac.authorization.k8s.io/ClusterRole:kyverno/kyverno:rbac:admin:policies
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.2
    helm.sh/chart: kyverno-3.4.2
  name: kyverno:rbac:admin:policies
rules:
  - apiGroups:
      - kyverno.io
    resources:
      - cleanuppolicies
      - clustercleanuppolicies
      - policies
      - clusterpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
```

## ArgoCD Configuration
```yaml
configs:
  cm:
    resource.compareoptions: |
      ignoreAggregatedRoles: true
```

## Environment

- ArgoCD version: 3.0.5
- Kubernetes version: 1.32.3
- Deployment method: Helm

## Documentation Reference

According to the [ArgoCD documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#ignoring-rbac-changes-made-by-aggregateroles):

> If you are using Aggregated ClusterRoles and don't want Argo CD to detect the rules changes as drift, you can set resource.compareoptions.ignoreAggregatedRoles: true. Then Argo CD will no longer detect these changes as an event that requires syncing.

This clearly states that the setting should only ignore changes to the rules, not to the aggregation labels themselves.
