### ISSUE TITLE
Add deletion confirmation as an application level sync option

### ISSUE THREAD

**Issue by MrFreezeex** [argoproj/argo-cd#23380]
# Summary

Delete/Prune=confirm was "recently" added as a sync option in annotation of resources deployed. Those options essentially acts on the whole application and I feel like it could be easier (for us it is!) in some situation to add those directly on the Application itself rather than the resources deployed.

# Motivation

Do things like that:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-delete-confirm
spec:
  project: default
  source:
    repoURL: ...
    targetRevision: "main"
    path: ...
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    syncOptions:
      - Delete=confirm # <---
```

To add additional deletion confirmation on the application directly.

# Proposal

Add Delete/Prune=confirm support as application level sync option in addition to the existing deployed resource annotation.

As Delete/Prune option has also another option "false" I think that for consistency it would makes sense to also do the same for those. It would probably be weird UX wise if there was some option (confirm in this case) that would be added as a sync option on the application and not some other (false in this case).
