### ISSUE TITLE
Add helm releaseName option to source hydrator

### ISSUE THREAD

**Issue by akselleirv** [argoproj/argo-cd#23396]
# Summary

I was testing the source hydrator and I to rename the helm release name to something else than the Application name, but it seems that the `drySource` field currently does not support it. Adding it to `.spec.source.helm.releaseName` was also ignored by the source hydrator.

# Motivation

I'm running a central management cluster which controls several worker clusters. The Application name must be prefixed with the target worker cluster name to avoid name collision but the actual helm release name can omit the cluster name to avoid having too long names which makes reading resources difficult.

# Proposal

It would be helpful if the `drySource` supported all current fields under the `source` field.

**Comment by crenshaw-dev** [comment]
I've been trying to resist adding all the `source` fields to `drySource`, because it'll make hydration nondeterministic. I'll probably have to cave on that eventually though.

Until then you can add the release name to a `.argocd-source.yaml` file in the repo with these contents:

```yaml
helm:
  releaseName: <your release name>
```

The hydrator will pick up that value.

**Comment by akselleirv** [comment]
Yes, that would work if I used an Application resource directly. However, I use an AppSet, so I still need to define the configurations directly in the Application. Could the user be warned in the documentation, which could list the non-deterministic fields that cannot be used? 

One of the appeals for me with the source hydrator is that it builds on ArgoCD, but when you restrict what it can do, then takes away one of its strength. In my use-case I also require to use multi sources, but I assume that functionality is also removed when using the source hydrator?

**Comment by BenHesketh21** [comment]
> I've been trying to resist adding all the `source` fields to `drySource`, because it'll make hydration nondeterministic. I'll probably have to cave on that eventually though.
> 
> Until then you can add the release name to a `.argocd-source.yaml` file in the repo with these contents:
> 
> helm:
>   releaseName: <your release name>
> The hydrator will pick up that value.

@crenshaw-dev I know you said you'll probably cave on this but I'm wondering if you didn't, did you have a vision for how you would handle environment specific changes? Say you want to increase resources in prod but not in lower environments.

**Comment by crenshaw-dev** [comment]
Without adding parameters to `spec.sourceHydrator`, I'd envision per-environment config being always applied via git. For Kustomize applications, it's easy to set `spec.sourceHydrator.drySource.path` to a directory holding an environment-specific overlay. For Helm, one could use a `.argocd-source-<env app name>.yaml` file to specify a `helm.valuesFile` block pointing to a values-prod.yaml.

There are obvious downsides to doing everything in git, especially when you're trying to separate dev concerns (which should be in git) from platform concerns (which is ideally held elsewhere). But per-environment config is at least _possible_ using only git today.

**Comment by Supporterino** [comment]
Hi @crenshaw-dev ,

I have a quick question regarding the implementation of Helm options within the hydrator. Specifically, I’d like to discuss our current ApplicationSet setup and seek your recommendations on utilizing the sourceHydrator feature for diff detection in merge requests across different stages.

Currently, we are leveraging the SCM provider to load all repositories from a specific GitLab group based on a designated topic. This serves as the entry point for our ApplicationSets. Here’s a brief overview of our ApplicationSet process:

It loads a charts.yaml file from the root of the repository, which lists all the Helm charts to be deployed.
It traverses the env folder to locate a config.yaml file that specifies deployable environments.
It combines the Helm charts with the detected environments, creating an application for each combination. The Helm values are merged at each folder depth to minimize duplication, while also incorporating a default set of values from the common folder.
Please note that any all-caps names within the templates have been redacted for confidentiality.

I appreciate your insights on whether it’s feasible to use the sourceHydrator with this setup. Thank you!

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: APPNAME-applicationset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - matrix:
            generators:
              - git:
                  repoURL: https://gitlab.com/GROUP/argocd/REPO.git
                  revision: HEAD
                  pathParamPrefix: "app"
                  files:
                  - path: "charts.yaml"
              - list:
                  elementsYaml: "{{ .charts | toJson }}"
        - git:
            repoURL: https://gitlab.com/GROUP/argocd/REPO.git
            revision: HEAD
            pathParamPrefix: "appValues"
            files:
            - path: "env/**/**/config.yaml"
  template:
    metadata:
      name: 'argocd-{{ .chartName }}-{{ index .appValues.path.segments 1 }}-{{ index .appValues.path.segments 2 }}'
    spec:
      project: PROJECT
      sources:
      - repoURL: "{{ .repoURL }}"
        targetRevision: '{{ dig "chartVersionOverride" .chartName "targetRevision" .targetRevision . }}'
        chart: "{{ .chartName }}"
        helm:
          ignoreMissingValueFiles: true 
          passCredentials: true
          valueFiles:
          - $values/common/{{ .values }}
          - $values/{{ index .appValues.path.segments 0 }}/{{ index .appValues.path.segments 1 }}/{{ .values }}
          - $values/{{ index .appValues.path.segments 0 }}/{{ index .appValues.path.segments 1 }}/{{ index .appValues.path.segments 2 }}/{{ .values }}
      - repoURL: https://gitlab.com/GROUP/argocd/REPO.git
        targetRevision: HEAD
        ref: values
      destination:
        name: '{{ .cluster.name }}'
        namespace: '{{ .cluster.namespace }}'
  templatePatch: |
    spec:
      {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
      {{- else }}
      syncPolicy:
        syncOptions:
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
      {{- end }}
```

`charts.yaml`
```
charts:
- repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-cd
  targetRevision: 8.2.5
  values: argocd.yaml
```

`config.yaml`
```
cluster:
  name: CLUSTERNAME
  namespace: NAMESPACE

autoSync: true
```
