### ISSUE TITLE
Github SSO fails with 'connection refused' from argocd-dex-server

### ISSUE THREAD

**Issue by shazinahmed** [argoproj/argo-cd#23415]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have Github SSO setup with ArgoCD. When trying to sign in with Github, we get the below error

Failed to query provider "https://argocd2.company.io/api/dex": Get "https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused

**To Reproduce**
1. Setup ArgoCD with helm chart version 7.9.1 and dex image (ghcr.io/dexidp/dex:v2.42.1 or ghcr.io/dexidp/dex:v2.423.1)
2. Configure Github SSO

```
apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  application.sync.impersonation.enabled: "false"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: xxx
          clientSecret: +xxx
          orgs:
            - name: company-io
  exec.enabled: "true"
  server.rbac.log.enforce.enable: "true"
  statusbadge.enabled: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://argocd2.company.io
kind: ConfigMap
```

Here is the argocd-cmp-params-cm

```
apiVersion: v1
data:
  application.namespaces: ""
  applicationsetcontroller.enable.leader.election: "true"
  applicationsetcontroller.enable.progressive.syncs: "false"
  applicationsetcontroller.log.format: json
  applicationsetcontroller.log.level: warn
  applicationsetcontroller.namespaces: ""
  applicationsetcontroller.policy: sync
  controller.ignore.normalizer.jq.timeout: 1s
  controller.log.format: json
  controller.log.level: warn
  controller.operation.processors: "10"
  controller.repo.server.timeout.seconds: "60"
  controller.self.heal.timeout.seconds: "5"
  controller.status.processors: "20"
  controller.sync.timeout.seconds: "0"
  dexserver.log.format: json
  dexserver.log.level: warn
  notificationscontroller.log.format: json
  notificationscontroller.log.level: warn
  otlp.address: ""
  redis.server: argocd-redis-ha-haproxy:6379
  repo.server: argocd-repo-server:8081
  reposerver.git.request.timeout: 60s
  reposerver.log.format: json
  reposerver.log.level: warn
  reposerver.parallelism.limit: "0"
  server.basehref: /
  server.dex.server: https://argocd-dex-server:5556
  server.dex.server.strict.tls: "false"
  server.disable.auth: "false"
  server.enable.gzip: "true"
  server.enable.proxy.extension: "false"
  server.insecure: "true"
  server.log.format: json
  server.log.level: warn
  server.repo.server.strict.tls: "false"
  server.rootpath: ""
  server.staticassets: /shared/app
  server.x.frame.options: sameorigin
kind: ConfigMap
```
Login using Github SSO

**Expected behavior**

Login should work with the right roles

**Screenshots**

**Version**

```shell
argocd@argocd-server-6cd4c9bc64-2wsx8:~$ argocd version
argocd: v2.14.11+8283115
  BuildDate: 2025-04-22T15:31:47Z
  GitCommit: 82831155c2c1873b3b5d19449bfa3970dab9ce24
  GitTreeState: clean
  GoVersion: go1.23.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
argocd-server logs

```
time="2025-06-16T13:15:26Z" level=info msg="maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined"
{"level":"warning","msg":"Failed to verify token: failed to verify token: token verification failed for all audiences: error for aud \"argo-cd\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused, error for aud \"argo-cd-cli\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused","time":"2025-06-16T13:44:03Z"}
{"level":"warning","msg":"Failed to verify token: failed to verify token: token verification failed for all audiences: error for aud \"argo-cd\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused, error for aud \"argo-cd-cli\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused","time":"2025-06-16T13:44:03Z"}
{"level":"warning","msg":"Failed to verify token: failed to verify token: token verification failed for all audiences: error for aud \"argo-cd-cli\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused, error for aud \"argo-cd\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused","time":"2025-06-16T13:44:03Z"}
{"level":"warning","msg":"Failed to verify token: failed to verify token: token verification failed for all audiences: error for aud \"argo-cd\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused, error for aud \"argo-cd-cli\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused","time":"2025-06-16T13:44:04Z"}
{"level":"warning","msg":"Failed to verify token: failed to verify token: token verification failed for all audiences: error for aud \"argo-cd\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused, error for aud \"argo-cd-cli\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused","time":"2025-06-16T13:44:04Z"}
{"level":"warning","msg":"Failed to verify token: failed to verify token: token verification failed for all audiences: error for aud \"argo-cd\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused, error for aud \"argo-cd-cli\": Failed to query provider \"https://argocd2.company.io/api/dex\": Get \"https://argocd-dex-server:5556/api/dex/.well-known/openid-configuration\": dial tcp [2600:2d00:0:4:4075:fd79:3ba:c894]:5556: connect: connection refused","time":"2025-06-16T13:44:04Z"}

```

Thank you!
