### ISSUE TITLE
feat(app): Extract External links from custom resources

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#23533]
# Summary

Currently it is possible to add links using annotation `link.argocd.argoproj.io/external-link` (source: https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/)

However this it is limited to a link that is known in advance

# Motivation

Some links cannot be know in advance as they come from:
- templating 
- custom resource reconciliation

# Proposal

The proposal would be to allow link extraction from custom resources using: `link.argocd.argoproj.io/external-link-path` and use simple jsonpointer (that is already used in argoproj).

```yaml
apiVersion: foo.bar/v1alpha1
kind: Baz
metadata:
  name: my-svc
  annotations:
    link.argocd.argoproj.io/external-link-path: /status/url
spec:
  some: "field"
status:
  url: https://123456.some.generated.url.io
```

Don't hesitate if you have remarks
