### ISSUE TITLE
accept ingress: null in OpenShift routes

### ISSUE THREAD

**Issue by cooktheryan** [argoproj/argo-cd#2353]
**Describe the bug**

If a route object has been created outside of Argo CD and a user wants to load the route into a YAML file to be stored in the git repository to be managed by Argo the default value of ingress: null. The value of ingress: [] can be used in the YAML file but that would require the person to make a modification to the deployed YAML.

**To Reproduce**

If we cannot reproduce, we cannot fix! Steps to reproduce the behavior:

1. Deploy a route in OpenShift. 
oc expose svc/httpd
Here is the default YAML.
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app: httpd
  name: httpd
  selfLink: /apis/route.openshift.io/v1/namespaces/simple-app/routes/httpd
spec:
  host: REMOVED
  port:
    targetPort: 8080
  subdomain: ""
  to:
    kind: Service
    name: httpd
    weight: 100
  wildcardPolicy: None
status:
  ingress: null

```

2. Attempt to sync or dry run the Application in Argo CD this error will pop up

```
GROUP               KIND        NAMESPACE   NAME        STATUS     HEALTH   HOOK  MESSAGE
route.openshift.io  Route       simple-app  httpd       OutOfSync  Unknown        kubectl failed exit status 1: error validating data: ValidationError(Route.status): missing required field "ingress" in com.github.openshift.api.route.v1.RouteStatus
```

3. The user has to modify the value of ingress to be ingress: [] rather than ingress: null

4. Sync and error goes away

**Example**

Take a look at https://github.com/cooktheryan/blogpost/compare/argo-friends master branch works argo-friends contains the default value

**Expected behavior**

Argo can differentiate between null and []
**Version**

```shell
argocd: v1.2.0-rc2+5571cf1
  BuildDate: 2019-08-21T15:47:33Z
  GitCommit: 5571cf133323f1c864472480c56e03e9ff3da0b3
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.0-rc2+5571cf1
  BuildDate: 2019-08-21T15:48:43Z
  GitCommit: 5571cf133323f1c864472480c56e03e9ff3da0b3
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
Above
```
