### ISSUE TITLE
Helm values not set on child apps

### ISSUE THREAD

**Issue by syst0m** [argoproj/argo-cd#2359]
**Describe the bug**

Using the app-of-apps pattern to bootstrap the cluster.
The child apps parameters from values.yaml appear on the UI,
but they are not used by the resources (i.e. pods), deployed by the chart.

**To Reproduce**

The child apps path has a kustomization.yaml which points to the directory of each child app:
```
resources:
- ../system/cluster-autoscaler/argocd-app
- ../system/kubernetes-dashboard/argocd-app
- ../system/heapster/argocd-app
- ../system/rbac-setup/argocd-app
```

Each child app has a kustomization.yaml in their `argocd-app` directory, which points to the manifest for the child app:
```
resources:
- heapster.yaml
```

The manifest of the child app points to the values.yaml file, in each child app directory.
For example, the heapster manifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heapster
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

  project: default

  source:
    path: system/heapster
    repoURL: XXX
    targetRevision: HEAD

    helm:
      valueFiles:
      - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Example**

https://github.com/syst0m/argocd-example-apps/tree/master/system

**Expected behavior**

The child apps resources are deployed using the parameters from their respective values.yaml.

**Screenshots**

![heapster](https://user-images.githubusercontent.com/15815107/65601485-11e9bf80-df9a-11e9-87e3-d06623ee0ece.png)

**Version**

```
Non-HA v1.2.1
```

**Logs**

Using kubectl to describe, i.e. the heapster pod, I can see that the command does not equal the one in the values.yaml:
```
    Command:
      /heapster
      --source=kubernetes.summary_api:''
```

The heapster values.yaml has the command:
```
command:
- "/heapster"
- "--source=kubernetes:kubernetes:https://kubernetes.default?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true"
```

Using kubectl to describe, the kubernetes dashboard, I can see that the arguments are:
```
    Args:
      --auto-generate-certificates
```

Where, the kuberentes-dashboard values.yaml has `enableSkipLogin: true` set,
which adds another argument:
```
    Args:
      --enable-skip-login
      --auto-generate-certificates
```

**Have you thought about contributing a fix yourself?**
Yes, not sure where to start.

**Comment by syst0m** [comment]
Adding the application name in the header of the values.yaml resolved the issue.
Maybe it would make sense to document this?

**Comment by mkue** [comment]
I'm facing the exact same problem. What exactly do you mean by "adding the application name in the header of the values.yaml" @syst0m?

**Comment by mkue** [comment]
Ok, I figured it out in the meantime :)

The root of the values.yaml file has to be the name of the application, e.g.:
```
prometheus-operator:
  prometheus:
    ingress:
      enabled: true
...
```

and not:
```
prometheus:
  ingress:
    enabled: true
```
