### ISSUE TITLE
Missing argocd-redis service in HA setup

### ISSUE THREAD

**Issue by tomaszkiewicz** [argoproj/argo-cd#2366]
**Describe the bug**

After deployment of argocd 1.2.1 (and 1.2.2) with HA manifest provided argocd-server cannot connect to redis as it tries to connect to service `argocd-redis` which doesn't exist.

Adding the following service (from argocd non-ha) to k8s solves problem:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: argocd-redis-ha
    app.kubernetes.io/part-of: argocd
  name: argocd-redis
spec:
  clusterIP: None
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    app.kubernetes.io/name: argocd-redis-ha
  type: ClusterIP
```

**To Reproduce**

Install argocd ha 1.2.1 and try to use it.

**Expected behavior**

Argocd HA working like non-ha.

**Version**

1.2.1 and 1.2.2
