### ISSUE TITLE
Support for aggregated ClusterRoles

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#2382]
**Is your feature request related to a problem? Please describe.**

I recently installed an application from a Helm chart (rook-operator), which makes extensive use of a K8s feature called aggregated ClusterRoles (https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles). This feature populates a ClusterRole resource with RBAC rules defined in other ClusterRole resources with a special annotation, and obviously ArgoCD marks the resulting ClusterRole resources as out-of-sync.

As an example, consider the following resource definitions:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-clusterrole
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.com/aggregate-to-test: "true"
rules: [] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-clusterrole-aggr1
  labels:
    rbac.example.com/aggregate-to-test: "true"
rules:
 - apiGroups: [""]
   resources: ["services", "endpoints"]
   verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-clusterrole-aggr2
  labels:
    rbac.example.com/aggregate-to-test: "true"
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list"]

```
This would create three ClusterRole resources, but `test-clusterrole` would be populated in the cluster as follows and therefore deviate from the definition stored in Git:

```
$ kubectl get clusterrole test-clusterrole -o yaml
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.com/aggregate-to-test: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: test-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list

```

**Describe the solution you'd like**
ArgoCD should either

- ignore the role's RBAC rules for the state comparison and only consider resource spec and meta-data for sync state (the "simple" solution) or
- resolve the aggregation rule and compare the resource's RBAC rules against the aggregated rules from other ClusterRole object that a matching label

However, since I'm unsure if (and if yes, how) K8s deterministically decides on the order of aggregation so that we end up with reproducable target objects and I'm also not sure about its value, I'd say option 1 (ignoring rules) would be sufficient. Any RBAC rules defined manually in the ClusterRole acting as the aggregator will be overriden by the aggregation anyway, and K8s takes care about the aggregations if resources with matching aggregation labels are added or deleted to/from the cluster.

**Have you thought about contributing yourself?**

Sure, I'd go for implementing this change if we decide it's something we want to have in ArgoCD.

**Comment by jannfis** [comment]
This could maybe be very easily accomplished by adding a new selector to the `ignoreDifferences` configuration, e.g. `aggregated`:
```
  ignoreDifferences:
  - kind: ClusterRole
    aggregated: true
    jsonPointers:
    - /rules
```
Would make ArgoCD ignore the RBAC rules if an `aggregationRule` is defined in the resource configuration.

**Comment by jannfis** [comment]
While I was thinking more about it, maybe something like "conditional" ignore would be even better. 

So introducing a "conditions" field to the ignoreDifferences which applies a list of expressions to the spec that must be matched so that the ignore rule matches, i.e.

```
  ignoreDifferences:
  - kind: ClusterRole
    conditions:
     - /aggregationRule is defined
    jsonPointers:
    - /rules
```

We could start with simple expressions (`is defined` and `not defined`) and extend it to `matches <regexp>`, `not matches <regexp>` and logical operators `==`, `!=`, `>`, `<` later on.

**Comment by jan-di** [comment]
For everyone who get here by a search engine:

In addition to @zvlb's [solution on application basis](https://github.com/argoproj/argo-cd/issues/2382#issuecomment-1179040437), you could apply it globally via the argocd configmap (see #3076 for details):

```yaml
resource.compareoptions: |
    ignoreAggregatedRoles: true
```

**Comment by m1schka-bdr** [comment]
> If use `aggregated` in `ignoreDifferences` I have error: `# * <nil>: Invalid value: "The edited file failed validation": ValidationError(Application.spec.ignoreDifferences[1]): unknown field "aggregated" in io.argoproj.v1alpha1.Application.spec.ignoreDifferences`
> 
> For this case for me work:
> 
> ```
>   - kind: ClusterRole
>     managedFieldsManagers:
>       - clusterrole-aggregation-controller
>     jsonPointers:
>     - /rules
> ```

not sure why but this doesn't work for me.

it should not need the /rules jsonPointer as it should detect this from the managedFields. also, for me this needs a group: "*". however, then it doesn't detect changes from regular clusterroles in the same application.

if I remove the jsonPointers, it detects both changes on aggregated (which it should not) and regular clusterroles

maybe related to #25110

**Comment by a7i** [comment]
Confirming @m1schka-bdr's observation: an explicit `group` is required for `ignoreDifferences` to match a ClusterRole, otherwise the entry silently does nothing and the resource stays `OutOfSync` regardless of `jsonPointers` or `managedFieldsManagers`.

The twist: the working value is `group: rbac.authorization.k8s.io` (not `*` or omitted). I verified this on argocd v3.2.6 with the cluster-wide `controller.diff.server.side: "true"` and `ServerSideApply=true` on the Application. Patching the live `Application` and toggling just the `group` field flipped the status from `OutOfSync` to `Synced` immediately. Scoping by `name` also avoids the "matches non-aggregated ClusterRoles too" issue you ran into with `group: "*"`:

```yaml
spec:
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: oncall
      jsonPointers:
        - /rules
```

Also required when auto-sync is on (otherwise sync keeps reverting `/rules` and the resource flaps, even though the diff is hidden):

```yaml
spec:
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
```

For `managedFieldsManagers: [clusterrole-aggregation-controller]` specifically: under ServerSideDiff it's effectively a no-op for me, because the diff is computed from a kube API dry-run apply response rather than from the live resource's `metadata.managedFields`. Falling back to `jsonPointers` is needed in that setup.
