### ISSUE TITLE
patch level updates helm charts are not synced

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#2391]
**Describe the bug**

We use helm dependency charts based on a patch-level version match:
version: ~1.2.3
Argocd does not detect a new version.

**To Reproduce**

1. create helm chart version x 
2. create argoapp with helm chart with a subchart, requirements.yaml:
```
dependencies:
- name: openshift-generic-valuestream
  version: ~0.1.57 (important bit is ~)
  repository: xxxxxx
```
**Example**
same as helm-dependency on https://github.com/argoproj/argocd-example-apps
but then with ~5.0.2
**Expected behavior**

When a new version of the subchart is created (5.0.3) in this case argocd should get out of sync
automatically

**Version**
1.2.2
