### ISSUE TITLE
UI bug when targetRevision is ommited

### ISSUE THREAD

**Issue by olivierlemasle** [argoproj/argo-cd#2407]
**Describe the bug**

When an application in a declarative way (using YAML), it is possible to omit `targetRevision`.
This parameter is documented _"If omitted, will sync to HEAD"_.

However, it causes an issue in UI:  under "Synced" status, revision metadata fails to load (cf screenshots). At the same time, a warning popup is displayed with message "Unable to load data: NotFound" (cf screenshots). Clicking on "Try again" generates the same error.

The request failing is `/api/v1/applications/{appName}/revisions//metadata`, that redirects to  `/api/v1/applications/{appName}/revisions/metadata`, that fails with a 404 error. The issue is therefore that the URL does not include any revision.

**To Reproduce**

Create an application with no `targetRevision`. For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-2407-guestbook
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
  syncPolicy:
    automated: {}
```

Display the application in UI.

**Expected behavior**

The revision metadata is expected to be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/628140/66137987-34b14f00-e5fe-11e9-992b-fd64c8af99b1.png)

![image](https://user-images.githubusercontent.com/628140/66138099-5f9ba300-e5fe-11e9-96a6-aca09febe637.png)

**Version**

```shell
argocd: v1.3.0+399a022
  BuildDate: 2019-10-03T00:10:12Z
  GitCommit: 399a02209974d040b1f79a162d56712debf29201
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```
