### ISSUE TITLE
Add support for adding individual users via rbac

### ISSUE THREAD

**Issue by jl431** [argoproj/argo-cd#2424]
**Is your feature request related to a problem? Please describe.**
I have argo-cd setup to authenticate my users. They are able to login but are unable to see any admin created applications.

I have attempted to add the rbac policy as documented but no access is granted and users still have zero visibility.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    g, company.com:user@company.com, role:admin
```

**Describe the solution you'd like**
I would like examples adding to the documentation on how to add individual users to admin groups.

**Comment by servo1x** [comment]
Assuming you're using oidc, we update the rbac scope to include email.

Example (values for helm chart):

```
  rbac:
    create: true

    policyCsv:
      - g, user01@mycompany.com, role:admin

    scopes: "[email, group]"

    policyDefault: ""
```

**Comment by jl431** [comment]
I am using oicdConfig.
My argocd-rbac-cm contains the following:
```
apiVersion: v1
data:
  policy.csv: |
    g, user@company.com, role:admin
  scopes: '[email, group]'
kind: ConfigMap
metadata:...
```
But the user still has no visibility once logged in.
argocd v1.2.3

**Comment by jl431** [comment]
When templating your exact values above, I get a malformed config map.
```
  rbac:
    create: true
    policyCsv:
      - g, user01@mycompany.com, role:admin
    scopes: "[email, group]"
    policyDefault: ""
```
helm template ./mycharts/argocd --name argocd --namespace mynamespace > test.yaml
---
```
# Source: argocd/charts/argo-cd/templates/argocd-rbac-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argo-cd
    helm.sh/chart: argo-cd-0.5.4
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/part-of: argocd
data:
  policy.csv:    - g, user01@mycompany.com, role:admin
    
  scopes: [email, group]
```
Note the list attempt in the csv. Maybe this is a bug?

**Comment by servo1x** [comment]
@jl431, we use a custom helm chart, for the one provided by argo-cd - the policy.csv should be a string.

```
policy.csv: |
  g, user01@mycompany.com, role:admin
```

**Comment by stgarf** [comment]
Changes #2503 for the RBAC docs might help you here once they're merged.

**Comment by Beer786** [comment]
@jl431 It is working when we add single email, how to add multiple email id as a group in it.
I tried like this but didn't work
```
policy.csv: |
    g, [user1@example.com, user2@example.com], role:admin
  policy.default: role:readonly
  scopes: '[email]'

**Comment by jl431** [comment]
@Beer786 I also couldn't get it working via groups. My users are added individually, which isn't ideal.

**Comment by nhuray** [comment]
I'm also trying to configure SSO and RBAC using Okta as IDP, but I could not get it working using Okta group :(

The documentation is not clear enough regarding the RBAC configuration with certain IDP providers (Google, Okta...)

**Comment by stgarf** [comment]
@jl431 @nhuray @saranicole 
I went through the same trials and tribulations as you all seem to have (only it was about 8 months ago) and so I wrote some documentation for it... (long and short, try to use SAML if possible -- unless you're paying Okta extra $$ you can't get OIDC).

I'm curious if you guys found the documentation lacking in setting up [Okta with Argo CD](https://argoproj.github.io/argo-cd/operator-manual/user-management/okta/#saml-with-dex).

If there's some gotchas or missed spots in the docs please submit a PR, it'd be greatly appreciated :)

**Comment by saranicole** [comment]
@stgarf  thanks for the doc and the inspiration!  I opened issue https://github.com/argoproj/argo-cd/issues/3352 and PR https://github.com/argoproj/argo-cd/pull/3351

**Comment by renperez** [comment]
@saranicole so glad i found this post. i was pulling my hair out why my cert isnt working when i enabled okta integration. i didnt know you have to base64 encode the cert from okta :)

**Comment by wojtek-viirtue** [comment]
For anyone using NOT using SSO and is using local user accounts the argocd-rbac-cm should be as follows:

```
data:
  policy.default: role:readonly
  policy.csv: |
    p, alice, applications, *, */*, allow
  scopes: '[accounts]'
```

The mention of scopes in this thread helped!  I could not find it documented in the RBAC configuration docs for local users.  
Thank you!

**Comment by johnkost** [comment]
I ran into an issue with the the above where specifying `policy.default: role:readonly` took precedence over what I had defined in `policy.csv` (note - I didn't apply scopes).

**Comment by abdennour** [comment]
@johnkost  then what's the fix ?

**Comment by johnkost** [comment]
I removed `policy.default`. I wasn't able to find any other workarounds

**Comment by Chabane** [comment]
@wojtek-viirtue did you find a solution since August ?

**Comment by cp1408** [comment]
Hi team, how to find the org name in okta ..i am unable to find the org name in okta also the group is not working for me ..i have setup the OKTA with SAML and groups defined in rbac-cm

APP-ArgoCD-DEV-Admin is the group, user is able to login via okta sso. pls check the below rbac-cm yaml

##############################################################################
apiVersion: v1
data:
  policy.csv: |
    p, role:dish-org-admin, applications, *, */*, allow
    p, role:dish-org-admin, project, *, */*, allow
    p, role:dish-org-admin, clusters, get, *, allow
    p, role:dish-org-admin, clusters, delete, *, allow
    p, role:dish-org-admin, clusters, update, *, allow
    p, role:dish-org-admin, clusters, create, *, allow
    p, role:dish-org-admin, repositories, get, *, allow
    p, role:dish-org-admin, repositories, create, *, allow
    p, role:dish-org-admin, repositories, update, *, allow
    p, role:dish-org-admin, repositories, delete, *, allow
    g, APP-ArgoCD-DEV-Admin, role:dish-org-admin
  policy.default: role:readonly
  scopes: '[groups]'
##############################################################################

**Comment by ngoduykhanh** [comment]
Hi,

How about granting access to an individual user? In my case, it was a Github account authenticated via dex config. The following config map doesn't work.

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:owner, applications, create, */*, allow
    p, role:owner, applications, update, */*, allow
    p, role:owner, applications, delete, */*, allow
    p, role:owner, applications, sync, */*, allow
    p, role:owner, applications, override, */*, allow
    p, role:owner, applications, action/*, */*, allow
    p, role:owner, certificates, create, *, allow
    p, role:owner, certificates, update, *, allow
    p, role:owner, certificates, delete, *, allow
    p, role:owner, clusters, create, *, allow
    p, role:owner, clusters, update, *, allow
    p, role:owner, clusters, delete, *, allow
    p, role:owner, repositories, create, *, allow
    p, role:owner, repositories, update, *, allow
    p, role:owner, repositories, delete, *, allow
    p, role:owner, projects, create, *, allow
    p, role:owner, projects, update, *, allow
    p, role:owner, projects, delete, *, allow
    p, role:owner, accounts, update, *, allow
    p, role:owner, gpgkeys, create, *, allow
    p, role:owner, gpgkeys, delete, *, allow

    g, user@email.com, role:owner
  scopes: '[email]'
```

**Comment by cp1408** [comment]
Hello ,
individual user using mail-id in argocd-rbac-cm.ymal is working as per below definition, i want to assign a group of AD where user are added. i have 4 different groups for which i need to define custom policies and attach to each group.

Also how to find the "org name in okta" for which @saranicole  mentioned in one of the above comment, he got it working with SAML & OKTA with groups.

There is no official documentation for this parameter and no mention about this parameter in the document SAML with OKTA config.

  policy.csv: |
    g, cp1408@xxxxxx.com, role:admin
  scopes: '[email,groups]'

**Comment by ismailyenigul** [comment]
The following values work for local users.


values in helm.

```
config:

    accounts.user1: apiKey, login
    accounts:user2: apiKey, login
    accounts.user3: apiKey, login

```

values in argocd-rbac-cm
```
apiVersion: v1
data:
  policy.csv: |
    p, user1, applications, *, *, allow
    p, user2, applications, *, *, allow
    p, user3, applications, *, *, allow
  policy.default: role:readonly
kind: ConfigMap
```

If you set  `policy.default: role:admin`, then the settings in `policy.csv` never works!
And all users will be admin regardless of values in policy.csv

**Comment by xlanor** [comment]
Does anybody have a solution for saml/okta with groups instead of explicitly specifying permissions for each username>

**Comment by johnkost** [comment]
We use Okta and were able to use groups here. We use Ansible to drive creation of the Helm values

Generic users with access to only their apps
```
        p, role:{{ team.name }}, applications, get, atlas/namespace-{{ team.name }}*, allow
        p, role:{{ team.name }}, applications, create, {{ team.name }}/*, allow
        p, role:{{ team.name }}, applications, delete, {{ team.name }}/*, allow
        p, role:{{ team.name }}, applications, get, {{ team.name }}/*, allow
        p, role:{{ team.name }}, applications, override, {{ team.name }}/*, allow
        p, role:{{ team.name }}, applications, sync, {{ team.name }}/*, allow
        p, role:{{ team.name }}, applications, update, {{ team.name }}/*, allow
        p, role:{{ team.name }}, projects, get, {{ team.name }}, allow
        p, role:{{ team.name }}, clusters, get, *, allow
        p, role:{{ team.name }}, repositories, get, *, allow
```

Admin teams
```
        g, "{{ ad_group_name }}", role:{{ team.name }}
        g, "{{ team.name }}-user", role:{{ team.name }}
```

**Comment by KeerthigaKrishnan** [comment]
Can we provide access to users for specifc components in applications like logs. user will have get acces to applications, and canonly view logs. Is it possible. ?

**Comment by AbhinayGupta741** [comment]
This works for us. We are trying to give default admin permission to the specific user and some particular permission to the group of people in Github Teams
SSO: Github



   
    # Grant all members of 'my-org:team-beta' admins

    p, role:role-name, applications, create, */*, allow
    p, role:role-name, applications, update, */*, allow
    p, role:role-name, applications, sync, */*, allow
    p, role:role-name, applications, override, */*, allow
    p, role:role-name, applications, action/*, */*, allow

    g, my_org_name:team_name, role:role-name
    g, user@company.com, role:admin

    policy.default: role:readonly
    scopes: '[groups, email]'


Hope it helps to someone

**Comment by zmx** [comment]
The solution provide @AbhinayGupta741 works for me on Dex Google Connector

Another trap: `scopes: [email]` won't works

**Comment by anhdle14** [comment]
Testing it on Dex GitHub without Org as well. Nothing from the discussion above can solve this.

The log coming from `argocd-dex`:

```
time="2022-01-05T17:08:11Z" level=info msg="login successful: connector \"github\", username=\"Le Anh Duc\", preferred_username=\"anhdle14\", email=\"anhdle14@icloud.com\", groups=[]"
```

The RBAC configmap:

```yaml
apiVersion: v1                                                                                                                                                                              
kind: ConfigMap                                                                                                                                                                             
metadata:                                                                                                                                                                                   
  name: argocd-rbac-cm                                                                                                                                                                      
data:                                                                                                                                                                                       
  # policy.default: role:readonly                                                                                                                                                           
  policy.csv: |                                                                                                                                                                             
    g, Le Anh Duc, role:admin
    g, anhdle14@icloud.com, role:admin                                                                                                                                                           
    g, anhdle14, role:admin    
```

None of these work. Normally this solution is likely to handle very few users or only 1 user, so it is not the end of the world with `policy.default: role:admin`.
