### ISSUE TITLE
Let Argo CD manage itself when using a private repo

### ISSUE THREAD

**Issue by mkue** [argoproj/argo-cd#2438]
I've created a private repository with all my Kubernetes cluster config files. It has the same structure like this dummy [project](https://github.com/mkue/argocd-example).
The `argocd/` directory holds the kustomize configuration files that I used to install Argo CD (`kubectl apply -k argocd`). In the frontend, I added a private repository and a single application that follows the app in app principle. This works great to deploy all kind of applications.

What I would like to do though, is to add the `argocd/` directory as an application as well, so Argo CD would manage itself. This would make sure that changes in the `argocd/` folder would be applied automatically. At the moment, I need to run the `kubectl apply -k argocd` command manually if I make changes in the `argocd/` directory.

Adding the `argocd/` directory as an application doesn't work though. I get the error `SSH agent requested but SSH_AUTH_SOCK not-specified` when the app starts synchronizing. I believe what happens is that the `argocd-cm` ConfigMap is deleted (it disappears) in the synchronization process and that Argo CD basically locks itself out of the private repository.

When I run `kubectl apply -k argocd` thereafter, everything works fine again. This shows in my eyes that the problem is not the sealed secret.

Is there a way how I can avoid this from happening? The documentation only shows an example with a public repository...

**Comment by jannfis** [comment]
Do you have a repository configuration for the repo specified with repoURL? The error message usually happens when you try to access a repository using SSH without having a private key specified as credential for the repository.

To workaround use either https (works unauthenticated) or define a repository with a private key.

@alexmt is this something we should consider a bug, i.e. allow SSH repository access without specifying credentials?

**Comment by jannfis** [comment]
OK, now after I have read your issue carefully (doh), I tried to reproduce your scenario on my local test cluster - but without the repository's credentials stored in a sealed-secret (bad practice, I know).

- installed ArgoCD from the Kustomize manifests into namespace `argocd`
- created a connection to a private repository containing the ArgoCD manifests (using HTTPS and a token, tho)
- created an application from that repo in the UI, to be synced into namespace `argocd`
- synced from repo
- success

So I suspect it might indeed by a race between sealed-secret and ArgoCD. This could maybe be solved using sync-waves (https://argoproj.github.io/argo-cd/user-guide/sync-waves/), giving the SealedSecret a lower wave ID so it will be synced before anything else. I'm unsure how ArgoCD currently determines the health state of a `SealedSecret` resource, but if it goes healthy when the actual `Secret` is created in the cluster, then the rest of the app would sync only afterwards and you might be save.

Worth a try?

**Comment by mkue** [comment]
Thanks :) I'll give it a try and let you know if it worked!

**Comment by lfloeer** [comment]
Hi @mkue , I really like your approach of managing Argo CD with itself.  Did you have success with using sync-waves for your applications?

**Comment by jakirpatel** [comment]
Hello is there any update on this ?

**Comment by mkue** [comment]
I recently came across this again. I managed to set this up by installing Argo CD with `kubectl` as described in the documentation and then creating a new Argo CD application that points to a Helm chart that represents the Argo CD installation.

This seems to work. At least, it's possible to configure the installation by setting parameters in the `values.yaml` file. I can't say how this behaves with Argo CD version upgrades.

----
### Example files

Argo CD application file
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:mkue/argocd-example.git
    path: namespaces/argocd
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
```

**Chart.yaml** in `namespaces/argocd` directory:
```yaml
apiVersion: v2
name: argocd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 3.29.4
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
```

**values.yaml** in `namespaces/argocd` directory (as examle on how to configure installation):
```yaml
argocd:
  server:
    replicas: 2
    env:
      - name: ARGOCD_API_SERVER_REPLICAS
        value: "2"

  repoServer:
    replicas: 2
```
