### ISSUE TITLE
Missing `Kind` when editing new application as YAML 

### ISSUE THREAD

**Issue by Dimss** [argoproj/argo-cd#2471]
**Describe the bug**
When creating a new application from the UI, there is an option to edit the application as YAML file, in that YAML `Kind` directive is missing  
**To Reproduce**

1. Create a new Application
2. Click on `Edit as Yaml`
3. kind: Application` is missing 

**Example of missing Kind directive** 
```
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ''
spec:
  destination:
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  project: ''

```

**Version**

```
argocd: v1.2.3+de7003f
  BuildDate: 2019-10-01T20:05:41Z
  GitCommit: de7003f530dbe0a8d49e2572b575a333ac7d803c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.3+de7003f
  BuildDate: 2019-10-01T20:05:11Z
  GitCommit: de7003f530dbe0a8d49e2572b575a333ac7d803c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```
