### ISSUE TITLE
Documentation: add info on webhook headers that need to pass reverse proxy

### ISSUE THREAD

**Issue by reegnz** [argoproj/argo-cd#2507]
# Summary

When running behind a reverse proxy, custom headers need to be let through by the proxy to the argocd upstream for the hook to work.

# Motivation

I was just setting up GitHub WebHooks (with secrets) for our ArgoCD instance behind nginx-ingress. I noticed that the documentation was lacking about custom headers having to be allowed to pass into argocd, and that made me scratch my head before diving into the ArgoCD code again to see why it's not working.

Turned out ArgoCD is using 'X-*' custom headers coming from the caller to determine the kind of SCM where it is coming from.

I set up a custom ingress for argocd for just the /api/webhook path and instructed nginx per configuration-snippet to let custom request headers be passed on to the backend:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-webhook
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_pass_request_headers on;

spec:
  rules:
  - host: argocd.example.com
    http:
    paths:
    - path: /api/webhook
      backend:
        serviceName: argocd-server
        servicePort: 8080
```

# Proposal

Operations documentation should mention that the webhook mechanism relies on these headers and that they need to be passed on to the client when the /api/webhook path is called.

**Comment by jetersen** [comment]
Here is my updated example with argocd container using tls and service as loadbalancer that is private:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-webhook
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_pass_request_headers on;
      # verify the argocd internal server through SNI
      proxy_ssl_name "argocd.company.io";
      proxy_ssl_server_name on;
spec:
  rules:
  - host: argocd.webhook.company.io
    http:
      paths:
      - path: /api/webhook
        backend:
          serviceName: argocd-server
          servicePort: https
  tls:
  - hosts:
    - argocd.webhook.company.io
    secretName: argocd.webhook.company.io-tls

```
