### ISSUE TITLE
Helm Application source values

### ISSUE THREAD

**Issue by bencompton** [argoproj/argo-cd#2531]
Does the Helm Application source in v1.3 support values at this point? The UI doesn't appear to have an option to specify Helm values. I took a guess as to the correct syntax (docs are still a WIP it appears), and this doesn't seem to work:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    path: ''
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 5.0.2
    chart: wordpress
    values:
      ...
```

**Comment by simster7** [comment]
The correct syntax is this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    path: ''
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 5.0.2
    chart: wordpress
    helm:
      values: |
        replicaCount: 1
```

Also, you can specify values in the UI under "Application Details" > "Parameters":
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/614838/67226306-79ecc380-f3e9-11e9-80c9-845db35dc52c.png">

You can also specify value files. You can do so with the [CLI](https://argoproj.github.io/argo-cd/user-guide/helm/#values-files), with the UI (just like above), and the YAML directly.

**Comment by bencompton** [comment]
@simster7 - thanks for the example!

I was able to successfully get an Application with a public Helm source working. For example, this is working perfectly:

```
project: default
source:
  repoURL: 'https://kubernetes-charts.storage.googleapis.com'
  targetRevision: 1.5.9
  helm:
    values: |-
	  ...
	  ...
  chart: jenkins
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated:
    prune: true
```

However, when I attempt to use a Helm source from a private Helm repository, I get this error:

```
InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = open /tmp/878873593/my-app: no such file or directory
```

Helm charts from this private repo are working fine when installed via a requirements.yaml file instead of an Application CRD. I have a private repo declared like this:

```
  ...
  helm.repositories: |
    - url: https://my-private-repo.net:443/helm-charts/
      name: myprivaterepo
  ...
```

My Application manifest looks like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-ns
  syncPolicy:
    automated:
      prune: true
  source:
    path: ''
    repoURL: https://myprivaterepo.net:443/helm-charts/
    targetRevision: 1.4.2
    chart: my-app
    helm:
      values: |
		...
		...
```

I'm still investigating, but if anyone has any ideas to try, it would be greatly appreciated.
