### ISSUE TITLE
Ignore some entries in OpenShift router YAMLs

### ISSUE THREAD

**Issue by cooktheryan** [argoproj/argo-cd#2548]
# Summary

What change you think needs making.
To make it so that you do not need to modify ArgoCD or predefine the following values in a route YAML file. Conditions and status should be ignored. If the values below are not predefined then the object stays in a perpetual out of sync.

```
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
```

# Motivation
To successfully use ArgoCD with routes you need the following under *status*. We should just ignore everything underneath of status. Some entries under status are already ignored by default.
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pacman
  namespace: pacman
spec:
  host: pacmanhosthere
  port:
    targetPort: 8080
  to:
    kind: Service
    name: pacman
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
```

# Proposal

How do you think this should be implemented? I don't know the coding but it would be ignoring the items similar to other items under status
