### ISSUE TITLE
Timestamp in Helm package file name causes error in Application with Helm source

### ISSUE THREAD

**Issue by bencompton** [argoproj/argo-cd#2549]
**Describe the bug**

In Argo CD v1.3, Applications with a Helm source fail when the Helm package name contains an ISO-8601 timestamp. The following error occurs: 

```
Unknown desc = open /tmp/055825409/my-app/values-559404908.yaml: no such file or directory
````

This error does not occur when using a `requirements.yaml` instead of an Application with a Helm source.

**To Reproduce**

1. Publish a Helm package with a timestamp in the filename (e.g., `my-app-1.0.0-20190927T222651Z.tgz`)

2. Consume the Helm package in an Application with a Helm source, e.g.:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
  source:
    path: ''
    repoURL: https://my-repo.net:443/helm/
    targetRevision: 1.0.0
    chart: my-app
```

**Expected behavior**

The Helm package will be deployed successfully.

**Version**

1.3

**Comment by alexec** [comment]
@bencompton I don't suppose you know of a Helm app in the public repos that has the timestamp please?

**Comment by alexec** [comment]
Also, are you able to provide logs? I'm wondering if this is actually related to the `spec/helm/values` configuration.

**Comment by bencompton** [comment]
> @bencompton I don't suppose you know of a Helm app in the public repos that has the timestamp please?

I'm not aware of any public repos with timestamps (it's just an internal practice my org uses). However, AFAIK, there is nothing preventing Helm servers from using any valid HTTP URL for Helm package resources, so Argo CD enforcing a particular naming convention could be problematic for some users (can't speak to how many users deviate from the typical `name-semver.tgz` convention). If Argo CD is going to expect the `name-semver.tgz` naming convention, it would probably be worth at least validating the package URL and providing a more useful error message.

> I'm wondering if this is actually related to the spec/helm/values configuration.

The same issue occurs when no Helm values were specified in the Application. The error message changes to `Unknown desc = open /tmp/878873593/my-app: no such file or directory`. I can consistently reproduce these errors when a helm package has a timestamp, and removing the timestamp fixes the error. I didn't test any other package names to see if it is just the timestamp that is the problem (i.e., there may be other file names that produce this error).

> Also, are you able to provide logs?

Sure, I'll see if I can get some logs for you.

**Comment by bencompton** [comment]
> @bencompton I don't suppose you know of a Helm app in the public repos that has the timestamp please?

I think I misunderstood what you were asking. If you're looking for a quick way to reproduce the issue, this is a public repo I created with helm-guestbook with a timestamp in the filename:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-broken
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  source:
    path: ''
    repoURL: https://jdh3.blob.core.windows.net/helm/
    targetRevision: 0.2.0
    chart: helm-guestbook
```

This one from the same public repo doesn't have the timestamp in the filename and works:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-working
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  source:
    path: ''
    repoURL: https://jdh3.blob.core.windows.net/helm/
    targetRevision: 0.1.0
    chart: helm-guestbook
```
