### ISSUE TITLE
Not all values from custom values files are applied

### ISSUE THREAD

**Issue by tolko** [argoproj/argo-cd#2562]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

when custom values files are used with a chart, not all values are applied

**To Reproduce**

clone stable/wordpress to your git repo in folder wordpress
create the following values yaml files in wordpress folder:
```yaml
# masterVal.yaml
wordpressBlogName: 111111111
wordpressFirstName: 1name
```
```yaml
# masterVal1.yaml
wordpressBlogName: 2222222
wordpressEmail: 2222@mail.org
```
```yaml
# masterVal2.yaml
wordpressBlogName: 3333
wordpressFirstName: 33333name
```
create application with following yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: wordpress
 namespace: argocd
spec:
 destination:
   namespace: default
 
   server: https://kubernetes.default.svc
 project: default
 
 source:
  helm:
   valueFiles:
   - masterVal.yaml
   - masterVal1.yaml
   - masterVal2.yaml
   
  path: wordpress/
  repoURL: [YOUR REPO].git
```
this application will not have the values stored in masterVal1.yaml
**Expected behavior**

when more than one values file is used for the application everything from those values files should be used:
```yaml
wordpressBlogName: 3333
wordpressEmail: 2222@mail.org
wordpressFirstName: 33333name
```

**Screenshots**

**Version**

```shell
argocd: v1.0.0+c74ca22
  BuildDate: 2019-05-16T20:03:24Z
  GitCommit: c74ca22023cbee245cb83fb23224978fbe23703c
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.1.2+567fcc3.dirty
  BuildDate: 2019-07-30T17:47:02Z
  GitCommit: 567fcc33140ec93051fdf8d0af7ea404deb64f20
  GitTreeState: dirty
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Logs**

```
Paste any relevant application logs here.
```
