### ISSUE TITLE
diff customization for cert-manager doesn't work

### ISSUE THREAD

**Issue by dontreboot** [argoproj/argo-cd#2586]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
```
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/acme/email
    kind: ClusterIssuer
``` 
The diff customization doesn't help for ignoring the diff for the cert-manager manifest I have in the screenshot

**To Reproduce**

n/a

**Expected behavior**

I follow the example provided here: https://argoproj.github.io/argo-cd/user-guide/diffing/; however, I am not sure if the the `group` definition is correct or not
**Screenshots**
<img width="1290" alt="Screen Shot 2019-10-29 at 1 41 30 PM" src="https://user-images.githubusercontent.com/1145737/67808256-932de980-fa53-11e9-80f0-8c11c7c42a89.png">

**Version**

```
argocd: v1.2.1+a6a394b
  BuildDate: 2019-09-12T17:16:32Z
  GitCommit: a6a394ba93a2a56981a45b9395e245e5210eaa35
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.4+ad7a69a
  BuildDate: 2019-10-23T20:06:50Z
  GitCommit: ad7a69a79883b7767cbeb88ca9a36d28277bd4ab
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```
