### ISSUE TITLE
shared resource warning for using same namespace for multiple microservices

### ISSUE THREAD

**Issue by chiragthaker** [argoproj/argo-cd#2600]
We really wants application to deploy to same namespace but argo doesnt sync and error in all microservices complaining about shared resource warning

how to either fix or silence this alarm ?

**Comment by alexec** [comment]
Hi @chiragthaker,

Thank you for your bug report.

This warning is intentional. You have two apps that are creating a resource with the same kind, name, and namespace. It is possible the two apps have different manifests for the same resource, so ignoring this warning could introduce bugs into your system as each resource gets overwritten.

The recommendation for this is to move your shared resources into a another single app.

Alex

**Comment by edernucci** [comment]
It's really great to have such warnings, thank you!

**Comment by zfrhv** [comment]
hello, is there any way to still use shared resources?

we have RHSSO and LDAP (as a backup) in our openshift environment.
so we want in each application to add a block of its own configuration into the `OAuth/cluster` instance under `spec.identityProviders[]`, for example:
```yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
      ...
  - openID:
      ...
```

we prefer not to have a separate application only for the OAuth instance.

also is there any way to tell agrocd to append / merge the yamls instead of overriding and fighting for it?

**Comment by zfrhv** [comment]
why not to enable shared resources, merge the fields, and only if there are 2 applications that use the same field inside the same resources then make the warning? : >

**Comment by brunocascio** [comment]
I'm facing the same problem, installing kyverno (through argocd + kustomize + helm) and seems the applicationset get wrong, because I don't have 2 apps writing the same CRDs

**Comment by brunocascio** [comment]
I solved it removing `app.kubernetes.io/instance` labels from CRDs

```yaml
resources:
  - namespace.yml

helmCharts:
- name: kyverno
  repo: https://kyverno.github.io/kyverno/
  version: 2.3.4 
  releaseName: kyverno
  namespace: kyverno
  valuesInline:
    replicaCount: 3

# Here's the warning fix
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |- 
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
```
