### ISSUE TITLE
Add support to ignore certain files in Git source

### ISSUE THREAD

**Issue by chris-vest** [argoproj/argo-cd#2638]
# Summary

Add support to ignore certain files in Git source.

# Motivation

I have a private Git repository which contains both Kubernetes objects in yaml files and Kafka Connect objects in json files defining Kafka Connect connectors and tasks. Currently when I set up an ArgoCD application pointing at this repo, it will fail to sync because it cannot apply the Kafka Connect objects to the Kubernetes API.

# Proposal

A solution for this could be to allow an extra configuration option in the application `source` configuration to optionally define files, file extensions and / or directories to ignore.

## Comments

I am going to pull down the codebase and see if I can add support for this myself, but I wanted to make you aware of my intention to do this by creating this issue.

**Comment by chris-vest** [comment]
It looks like this would be a relatively simple addition, if accepted: 

1. Add `ignore` section to `Application` CRD, e.g. `spec.source.directory.ignore` - can be either file extensions, file names (regex support?) or a directory. Not sure how the CRD definition is managed in the argo-cd codebase, will take me some time to familiarise myself with it
2. Add `Ignore` to `pkg/apis/application/v1alpha1/types.go:330` - 
```go
type ApplicationSourceDirectory struct {
	Recurse bool                     `json:"recurse,omitempty" protobuf:"bytes,1,opt,name=recurse"`
	Ignore []string				 `json:"ignore,omitempty" protobuf:"bytes,2,opt,name=ignore"`
	Jsonnet ApplicationSourceJsonnet `json:"jsonnet,omitempty" protobuf:"bytes,3,opt,name=jsonnet"`
}
```
3. `reposerver/repository/repository.go:456` - in `func findManifests`, add some logic (separate function?) to ignore the files / extensions / regex in the `Ignore` configuration []string

**Comment by alexec** [comment]
Seems like a useful feature. Directory based syncs don't have many options. I think there's a few ways to support this. What about having a `.argocdignore` file in the directory? Or an `argo-cd.yaml` file?

**Comment by ghostsquad** [comment]
It might be interesting to have an ArgoCD file the repo which describes how to sync files and what to sync. Instead of having that configuration outside of the repo.

**Comment by peimanja** [comment]
Any Update on this one

**Comment by mayzhang2000** [comment]
This is fixed by https://github.com/argoproj/argo-cd/issues/4432.

**Comment by korncola** [comment]
Price Quesdtion: **And how do i use it?** didnt found anything in Docs or Github Issues how to use the commit https://github.com/argoproj/argo-cd/pull/4686/files/a47ccaa8a8fd017c13ce8fdf5281a030b19e3bbf

**Comment by korncola** [comment]
never mind i found out with reading the source code, CLI options and some trial and error:

`spec.source.directory.exclude`, but also `spec.source.directory.recurse` has to be set to `true`

BTW i really love argocd! Would be nice if you update documentation and the example `application.yml`

example in `application.yml`:
```
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: myrepo
    targetRevision: HEAD
    path: myapp1

    directory:
      recurse: true
      exclude: '.drone.yml'
```

**Comment by JohnMops** [comment]
still trying to find a way to exclude specific folders

**Comment by pashcan** [comment]
@JohnMops I was able to exclude all files inside helm templates folder using
```yaml
spec:
  source:
...
    directory:
      recurse: true
      exclude: 'somedir/templates/*'
```

**Comment by ewassef** [comment]
how can i exclude several files names?

**Comment by hbrewster-splunk** [comment]
Were you able to achieve this with just the CLI too?

**Comment by arbianqx** [comment]
BUMP! The exclude option isn't working!!

**Comment by sadshwat** [comment]
The exclude function is not working, either with files or directories. Any update on this?

**Comment by doug62** [comment]
Bump: I wish to ignore directories, and perhaps files.  I feel that this feature should be triggered by something in the GIT repo rather than argo/crd because that way it could be source controlled.   Suggested resolutions:
1) .argoIgnore - file in each nested directory using a .gitIgnore pattern
2) .argoManifest.yaml - that would apply Kustomize like patch pattern to that directory and desendants.

**Comment by crenshaw-dev** [comment]
I created a test repo with this structure:

```
cm1.yaml
cm2.yaml
cm3.yaml
a-directory/
  cm1.yaml
  cm2.yaml
  cm3.yaml
```

To exclude two root-level configmaps as well as everything in the `a-directory` directory, I used this manifest:

```yaml
project: default
source:
  repoURL: 'https://github.com/crenshaw-dev/directory-app'
  path: .
  targetRevision: HEAD
  directory:
    recurse: true
    jsonnet: {}
    exclude: '{cm1.yaml,cm2.yaml,a-directory/*}'
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
```

The `exclude` field is a glob which, if you wrap it in `{}` supports a comma-delimited list of patterns.

This isn't well-documented. I'm going to create some tickets/PRs.  :-)

**Comment by crenshaw-dev** [comment]
Closing unless someone has a specific use case that isn't working. Feel free to continue to discuss here though!

**Comment by doug62** [comment]
@crenshaw-dev This was a feature request to add the ability to ignore files not by using an argo manifiest but to use a file in the repo to signal to argo to ignore files, so the 'font'/source of truth would remain in the repo rather than spread across concerns, so:  .argoIgnore { <file patterns similar to .gitIgnore>} would be ignored.

**Comment by crenshaw-dev** [comment]
Gotcha. I think the OP's request has been satisfied:

> A solution for this could be to allow an extra configuration option in the application source configuration to optionally define files, file extensions and / or directories to ignore.

Would you be willing to open another issue to track `.argoignore`?

**Comment by bremme** [comment]
Not sure if this is a bug or if I'm just doing something wrong. But whatever I try, my files/directories don't get ignored. My `spec.source.path` is set to `.` and I have a couple .json files in `documentation/examples`. I've tried to set `spec.source.directory.exclude` to the following values:

* `documentation`
* `documentation/*`
* `documentation/**`
* `documentation/examples/*.json`
* `./documentation/examples/*.json`
* `*.json`

I all cases I get a `ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal "my-example.json"`

**Comment by husira** [comment]
@bremme could you solve this issue? I have the same behaviour right now using ArgoCD Version 2.6.12. Always getting the error `ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): rpc error: code = FailedPrecondition desc = Failed to unmarshal "my-example.json"`

**Comment by raghu-manne** [comment]
> I created a test repo with this structure:
> 
> ```
> cm1.yaml
> cm2.yaml
> cm3.yaml
> a-directory/
>   cm1.yaml
>   cm2.yaml
>   cm3.yaml
> ```
> 
> To exclude two root-level configmaps as well as everything in the `a-directory` directory, I used this manifest:
> 
>  ```
> project: default
> source:
>   repoURL: 'https://github.com/crenshaw-dev/directory-app'
>   path: .
>   targetRevision: HEAD
>   directory:
>     recurse: true
>     jsonnet: {}
>     exclude: '{cm1.yaml,cm2.yaml,a-directory/*}'
> destination:
>   server: 'https://kubernetes.default.svc'
>   namespace: default
> ```
> The `exclude` field is a glob which, if you wrap it in `{}` supports a comma-delimited list of patterns.
> 
> This isn't well-documented. I'm going to create some tickets/PRs. :-)


This isn't working for me with multiple sources, is there any catch here I am missing?

My config:

```
sources:
  - repoURL: 'https://github.com/source1.git'
    path: applications/dev/
    targetRevision: main
    ref: muleRepo
  - repoURL: ''https://github.com/source2.git'
    targetRevision: XXX
    helm:
      valueFiles:
        - $muleRepo/path/to/values.yaml
    chart: sample-chart
    directory:
      recurse: true
      exclude: '{file-to-be-excluded.yaml}'
```
