### ISSUE TITLE
Old ReplicaSets are not deleted when sync completes

### ISSUE THREAD

**Issue by ovk** [argoproj/argo-cd#2639]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Old `ReplicaSet` not deleted after rollout to new `ReplicaSet` (even when doing sync with prune enabled).

**To Reproduce**

1. Create a simple Helm chart:

`Chart.yaml:`
```yaml
apiVersion: v1
name: test
description: A test app
type: application
version: 0.1.0
```

`values.yaml:`
```yaml
replicaCount: 2
```

`templates/deployment.yaml:`
```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: nginx:alpine          
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
```

`templates/service.yaml:`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
```

2. Create and sync ArgoCD application from this chart.

3. Edit `templates/deployment.yaml:` and replace container image to `nginx:latest`. Sync with prune and wait till sync completes.

4. Observe the current state of the application: notice **two** replica sets instead of **one**.

**Expected behavior**

Old replica set is deleted after rollout complete.

**Screenshots**

Notice two replica sets, one is without any pods:

![Untitled](https://user-images.githubusercontent.com/693072/68216820-89563a00-ffaf-11e9-9d10-6a807ef0c5e6.png)

**Version**

```shell
argocd: v1.2.5+85f62df
  BuildDate: 2019-10-29T00:05:49Z
  GitCommit: 85f62dff9e3de5a2ee80e9350c897923f59b7e85
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.4+ad7a69a
  BuildDate: 2019-10-23T20:06:50Z
  GitCommit: ad7a69a79883b7767cbeb88ca9a36d28277bd4ab
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

**Comment by OmerKahani** [comment]
You should add [revisionHistoryLimit](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy) to the deployment

**Comment by sualehasif** [comment]
How do you set a revisonHistoryLimit on an Argocd application:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-server
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-system
  project: default
  source:
    chart: kiali-server
    repoURL: https://kiali.org/helm-charts
    targetRevision: "v1.65"
    helm:
      values: |
        auth:
          strategy: anonymous
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    ```
    
    
    this is the file that I would like to set a revision history limit on^
