### ISSUE TITLE
Helm cannot use build environment variables

### ISSUE THREAD

**Issue by whitlekx** [argoproj/argo-cd#2651]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The feature described [here](https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/helm.md#build-environment) does not work. I'm on the latest version of argocd (1.2.5) and using the same image in our Kubernetes Cluster.

**To Reproduce**

Use this Application YAML:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REDACTED
    path: path/to/chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
      - name: image.tag
        value: $ARGOCD_APP_REVISION
      - name: test.image.tag
        value: $ARGOCD_APP_REVISION
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-test-deployment
```
or remove the parameters blob and override it on the CLI via:

```shell
argocd app create test-api -f test-argo-app.yaml --helm-set-string 'image.tag=${ARGOCD_APP_REVISION}'
```
**Expected behavior**

I expect to see the ARGOCD_APP_REVISION param be replaced by the revision Argo. However, I get the entire token injected as a string (i.e. the image tag is "TESTIMAGE:$ARGOCD_APP_REVISION"

Trying to use the CLI gives an unknown flag error

**Version**

```shell
argocd: v1.2.5+85f62df
  BuildDate: 2019-10-29T00:07:08Z
  GitCommit: 85f62dff9e3de5a2ee80e9350c897923f59b7e85
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.5+85f62df
  BuildDate: 2019-10-29T00:06:43Z
  GitCommit: 85f62dff9e3de5a2ee80e9350c897923f59b7e85
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```
