### ISSUE TITLE
Support Jsonnet Jpaths 

### ISSUE THREAD

**Issue by anarcher** [argoproj/argo-cd#2679]
# Summary

Support jsonnet jpaths(`jsonnet -J`) for  argocd apps

# Motivation

jsonnet supports jpaths . It can be useful with jsonnet based app. specially if we use it with jsonnet-bundler (https://github.com/jsonnet-bundler/jsonnet-bundler)
 

# Proposal

```
spec:
  source:
    directory:
      jsonnet:
        jpaths:
        - ../../vendor
        - ../../lib
    path: baseapp/environments/default
    repoURL: https://github.com/anarcher/hello-tk.git
    targetRevision: HEAD
```
