### ISSUE TITLE
1.3.0-rc4 Unable to provide helm valuesFiles from a git repo?

### ISSUE THREAD

**Issue by jon-walton** [argoproj/argo-cd#2682]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm starting to migrate our applications from helm charts within a git repo, to a helm repository. If I supply the `repoURL` to be the helm repository, it's not clear how to provide a values file from a git repo.

Anything supplied to `valuesFiles: []` results in a file not found error during application deployment.

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-ea-atlantis
spec:
  project: azure-ci-east-asia
  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: atlantis
    targetRevision: 3.8.4
    helm:
      valuesFiles:
        - clusters/azure/ci-ea/values/atlantis.yaml
```

The values file ` clusters/azure/ci-ea/values/atlantis.yaml` is in the same git repo as the application manifest, the above config results in an error.

If I `helm fetch ... --untar` a chart and store it in a git repo, the following application works

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-ea-nginx-ingress-internal
spec:
  project: azure-ci-east-asia
  source:
    repoURL: git@github.com:example/repo.git
    targetRevision: HEAD
    path: infrastructure/nginx-ingress
    helm:
      valueFiles:
        - values/default.yaml
        - values/internal.yaml
        - values/argocd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

The values files are applied relative to the chart folder `{git-root}/infrastructure/nginx-ingress/values/default.yaml`

**Expected behavior**

Be able to use a helm chart from a helm repository and apply a values file from a git repository. This will allow me to have multiple environments declared, targeting different helm chart versions

**Version**

```shell
argocd: v1.3.0-rc3+e0de330
  BuildDate: 2019-10-29T19:43:40Z
  GitCommit: e0de3300d23d559ae1248749e1c351bda684c013
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.0-rc4+5937150
  BuildDate: 2019-11-04T06:27:50Z
  GitCommit: 593715038c35506c80edc01a6f684c6cbe12f385
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.1.0
  Helm Version: v2.12.1
  Kubectl Version: v1.14.0
```

**Comment by alexec** [comment]
You're getting the app from the Helm repository - not Git. Therefore your values files must be in that repo. There appears to be a `values.yaml` and ` test-values.yaml` for Atlantis. 

Instead of using `valuesFiles`. you . can use `values` - a block of YAML.

**Comment by jon-walton** [comment]
Hi Alex,

I understand, so i suppose this is more of an enhancement request.

I have multiple environments managed by the same argocd - ci, dev, qa1, qa2, qa3, staging, production. If we take nginx ingress as an example, it is deployed to all environments as 2 appplications, an internal load balancer and a public load balancer. Therefore, the nginx ingress chart is deployed 14 times

I have 4 values files

- default.yaml
- internal.yaml
- public.yaml
- argocd.yaml (ci cluster)

`default.yaml` is used in every deployment, it's 80 lines of general configuration for the chart, `internal.yaml` and `public.yaml` are another 20-30 lines.

Duplicating the config and supplying it as a `values` block to each application is a blocker in being able to use the new helm chart features.

my request:

have the ability to supply a git source for the values files

**Comment by alexec** [comment]
Have you considered using Helm dependencies for this instead?

**Comment by jon-walton** [comment]
Actually, I had not considered doing that. It should also work quite well for my use case

thanks

**Comment by markmclaren** [comment]
Um.  Could it be in the first example you used "valuesFiles" and in the working one you used "valueFiles" (value singular)?

**Comment by yaphetsglhf** [comment]
> Checklist:
> 
> * [x]  I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
> * [x]  I've included steps to reproduce the bug.
> * [x]  I've pasted the output of `argocd version`.
> 
> **Describe the bug**
> 
> I'm starting to migrate our applications from helm charts within a git repo, to a helm repository. If I supply the `repoURL` to be the helm repository, it's not clear how to provide a values file from a git repo.
> 
> Anything supplied to `valuesFiles: []` results in a file not found error during application deployment.
> 
> **To Reproduce**
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   name: ci-ea-atlantis
> spec:
>   project: azure-ci-east-asia
>   destination:
>     server: https://kubernetes.default.svc
>     namespace: atlantis
>   syncPolicy:
>     automated:
>       prune: true
>       selfHeal: true
>   source:
>     repoURL: https://kubernetes-charts.storage.googleapis.com
>     chart: atlantis
>     targetRevision: 3.8.4
>     helm:
>       valuesFiles:
>         - clusters/azure/ci-ea/values/atlantis.yaml
> ```
> 
> The values file ` clusters/azure/ci-ea/values/atlantis.yaml` is in the same git repo as the application manifest, the above config results in an error.
> 
> If I `helm fetch ... --untar` a chart and store it in a git repo, the following application works
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   name: ci-ea-nginx-ingress-internal
> spec:
>   project: azure-ci-east-asia
>   source:
>     repoURL: git@github.com:example/repo.git
>     targetRevision: HEAD
>     path: infrastructure/nginx-ingress
>     helm:
>       valueFiles:
>         - values/default.yaml
>         - values/internal.yaml
>         - values/argocd.yaml
>   destination:
>     server: https://kubernetes.default.svc
>     namespace: ingress
>   syncPolicy:
>     automated:
>       prune: true
>       selfHeal: true
> ```
> 
> The values files are applied relative to the chart folder `{git-root}/infrastructure/nginx-ingress/values/default.yaml`
> 
> **Expected behavior**
> 
> Be able to use a helm chart from a helm repository and apply a values file from a git repository. This will allow me to have multiple environments declared, targeting different helm chart versions
> 
> **Version**
> 
> ```shell
> argocd: v1.3.0-rc3+e0de330
>   BuildDate: 2019-10-29T19:43:40Z
>   GitCommit: e0de3300d23d559ae1248749e1c351bda684c013
>   GitTreeState: clean
>   GoVersion: go1.12.6
>   Compiler: gc
>   Platform: linux/amd64
> argocd-server: v1.3.0-rc4+5937150
>   BuildDate: 2019-11-04T06:27:50Z
>   GitCommit: 593715038c35506c80edc01a6f684c6cbe12f385
>   GitTreeState: clean
>   GoVersion: go1.12.6
>   Compiler: gc
>   Platform: linux/amd64
>   Ksonnet Version: v0.13.1
>   Kustomize Version: v3.1.0
>   Helm Version: v2.12.1
>   Kubectl Version: v1.14.0
> ```

as you mentioned above，this is what i set
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biz
spec:
  project: default
  destination:
    namespace: qa001
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/biz
    repoURL: 'git@git.example.com:tiny/iac.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/biz-qa001/app.values.yaml
        - values/biz-qa001/gateway.values.yaml
        - values/biz-qa001/infra.values.yaml
```
but it could work. it only templates the default `values.yaml`.
