### ISSUE TITLE
argocd app create fails with status.sync.comparedTo.source.path in body is required

### ISSUE THREAD

**Issue by nouseforaname** [argoproj/argo-cd#2712]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
run:
trying to set app of apps via argocd cli:
```argocd app create env-apps --server argo.TLD.dev:443 --dest-namespace argocd --dest-server https://kubernetes.default.svc --directory-recurse --repo https://PRIVATE.git --path env-apps  --upsert --revision BRANCH --insecure```
containting:
```
apiVersion: argoproj.io/v1alpha1
metadata:
  name: 'env-apps'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    repoURL: 'PRIVATE.git'
    path: ./apps
    targetRevision: BRANCH
    directory:
      recurse: true
      jsonnet: {}
  project: default
```
errors with `status.sync.comparedTo.source.path in body is required`

kubectl apply -f with the app of apps.yml works 

after removing "path" from the list found in:
`kubectl get customresourcedefinition applications.argoproj.io \
--template={{.spec.validation.openAPIV3Schema.properties.status.properties.sync.properties.comparedTo.properties.source.required}}`
it worked.

* [x] I've pasted the output of `argocd version`

```argocd: v1.3.0+9f8608c
  BuildDate: 2019-11-13T01:49:01Z
  GitCommit: 9f8608c9fcb2a1d8dcc06eeadd57e5c0334c5800
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.0+9f8608c
  BuildDate: 2019-11-13T01:51:00Z
  GitCommit: 9f8608c9fcb2a1d8dcc06eeadd57e5c0334c5800
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Expected behavior**

I'm not getting a status validation error on a fresh create

**Version**
1.3.0
