### ISSUE TITLE
Allow passing adding a source repo for Helm values

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#2719]
# Summary

Follow up on #2682, having the ability to have a git source for values.

# Motivation

We have a git monorepo which currently hosts applications that will reference different versions of the same chart. It's really annoying to have to create a local chart every time we want to update a application to reference a different version.

We also follow the application of applications pattern, and if you are using helm 1st class with chart where there are lot of values (100+ lines), it becomes really painful (our app of apps helm chart does not define each app individually, instead - we pass in an array of helm charts and value paths and loop over that to create argocd applications).

# Proposal

```yaml
...
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: my-chart
    targetRevision: 1.0.0
    helm:
      valuesRepo: git@github.com:example/repo.git
      valuesFiles:
        - values/some/value.yaml
```
