### ISSUE TITLE
Rollout resource customization

### ISSUE THREAD

**Issue by vanhtuan0409** [argoproj/argo-cd#2742]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When Argo Rollout is `paused` by `spec.strategy.canary.steps` as the following example, Argo CD health status will show as `Progressing` instead of `Suspended`

```
strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0,
      steps:
      - setWeight: 10
      - pause:
          duration: 3600 # 1 hour
      - setWeight: 20
      - pause: {}

```

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.
- Create an application with Rollout resources (Canary strategy). Rollout strategy is as the above example
- Update Rollout and waiting for `paused` step

**Expected behavior**

ArgoCD should display Health Status as `Suspended`

**Version**

```shell
argocd: v1.3.0+9f8608c
  BuildDate: 2019-11-13T01:49:01Z
  GitCommit: 9f8608c9fcb2a1d8dcc06eeadd57e5c0334c5800
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.0+9f8608c
  BuildDate: 2019-11-13T01:51:00Z
  GitCommit: 9f8608c9fcb2a1d8dcc06eeadd57e5c0334c5800
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

Argo Rollout version: `v0.6.0`

**Diagnosis**

As Rollout 0.6.0 use both `spec.paused` and `status.pauseCondition`, we should update ArgoCD to check with both fields.
https://github.com/argoproj/argo-rollouts/releases
https://github.com/argoproj/argo-cd/blob/master/resource_customizations/argoproj.io/Rollout/health.lua#L35

Please correct me if my diagnosis is not correct
