### ISSUE TITLE
Build environment variables not working in helm

### ISSUE THREAD

**Issue by jonasdkhansen** [argoproj/argo-cd#2749]
When using any of the build environment variables in helm, the only thing getting passed is the name of the variable.

My manifest looks like this:
```
source:
  repoURL: 'https://github.com/bla/bla.git'
  path: svc
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: image.tag
        value: $ARGOCD_APP_REVISION
```
Pod event error message:
`
Failed to apply default image tag "eu.gcr.io/image:$ARGOCD_APP_REVISION"
`
So it seems like the variable is not set. I have also tried with APP_NAME, and it is also not working.

Argo CD version: 1.3.0
