### ISSUE TITLE
Regression: Can not supply value files as URLs

### ISSUE THREAD

**Issue by davideagle** [argoproj/argo-cd#2762]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Can not supply value files as URLs, they seem to be mistaken as file paths.

 helm template . --name oauth2-proxy --namespace ingress-nginx --kube-version 1.13 --values /tmp/https:__github.com_org_charts/bases/ingress-nginx/oauth2-proxy/

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

```yaml
applications:
  - name: oauth2-proxy
    project: ingress-nginx
    destination:
      server: https://kubernetes.default.svc
      namespace: ingress-nginx
    helm:
      chart: oauth2-proxy
      targetRevision: 2.0.0
      valueFiles:
        - https://raw.githubusercontent.com/org/Chart-values/master/oauth2-proxy/values-dev.yaml
    value_files:
      - values.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
```

**Expected behavior**

Values should be loaded from URL

**Version**

```shell
argocd:v1.3.0-rc5
```

**Logs**

```
ComparisonError: rpc error: code = Unknown desc = `helm template . --name oauth2-proxy --namespace ingress-nginx --kube-version 1.13 --values /tmp/https:__github.com_org_charts/bases/ingress-nginx/oauth2-proxy/https:/raw.githubusercontent.com/Icelandair/Chart-values/master/oauth2-proxy/values-dev.yaml?` failed exit status 1: Error: open /tmp/https:__github.com_org_charts/bases/ingress-nginx/oauth2-proxy/https:/raw.githubusercontent.com/Icelandair/Chart-values/master/oauth2-proxy/values-dev.yaml no such file or directory
```
