### ISSUE TITLE
Docs metrics wrong selector for API Server Metrics

### ISSUE THREAD

**Issue by greenstatic** [argoproj/argo-cd#2774]
The documentation on metrics contains a configuration mistake.

The `ServiceMonitor` CRD for `argocd-server-metrics` (API server metrics) should match the label `app.kubernetes.io/name: argocd-server-metrics` and not `app.kubernetes.io/name: argocd-server`.

This can be verified by looking the the service definition:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server-metrics
    app.kubernetes.io/part-of: argocd
  name: argocd-server-metrics
spec:
  ports:
  - name: metrics
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
```
