### ISSUE TITLE
Webhook Documentation

### ISSUE THREAD

**Issue by nouseforaname** [argoproj/argo-cd#2776]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

https://argoproj.github.io/argo-cd/operator-manual/webhook/ 
states:
```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
...
stringData:
  # github webhook secret
  webhook.github.secret: shhhh! it's a github secret
  # gitlab webhook secret
  webhook.gitlab.secret: shhhh! it's a gitlab secret
  # bitbucket webhook secret
  webhook.bitbucket.uuid: your-bitbucket-uuid
  # bitbucket server webhook secret
  webhook.bitbucketserver.secret: shhhh! it's a bitbucket server secret
  # gogs server webhook secret
  webhook.gogs.secret: shhhh! it's a gogs server secret
```
all the keys are under **webhook**

https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-secret.yaml#L27-L29

contains

```
  github.webhook.secret:
  gitlab.webhook.secret:
  bitbucket.webhook.uuid:
```

**To Reproduce**
none required, docs issue

**Expected behavior**
docs be truthful

**Version**
Current Master
