### ISSUE TITLE
Adding cluster with limited privileges

### ISSUE THREAD

**Issue by marian-margeta** [argoproj/argo-cd#2783]
# Summary

I want to add cluster, where I have only limited privileges - I only have access to one namespace, thus I have no cluster scope privileges that is currently needed for argocd. I added resource.inclusions to argocd-cm for *kinds* I want to synchronize:
```yaml
resource.inclusions: |
    - apiGroups:
      - "*"
      kinds:
        - "Deployment"
        - "ConfigMap"
        - "Service"
        - "Ingress"
```

However, argo tries to list those *kinds* at cluster scope level
```
ingresses.extensions is forbidden: User "***" cannot list resource "ingresses" in API group "extensions" at the cluster scope
```

# Motivation

We wanted to deploy applications to our customer, that is not willing to extend needed privileges at cluster scope. It is quite common if there are more different applications running on the cluster.

# Proposal

It would be nice to have an option to configure argocd to use just namespace scope privileges for custom k8s *kinds*.
