### ISSUE TITLE
argo-cd does not respect app sync policy

### ISSUE THREAD

**Issue by pydo** [argoproj/argo-cd#2787]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Argo-cd sets an automated `syncPolicy` on apps that have manual sync set.

**To Reproduce**

1. Create an Application with an automated sync policy
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-python-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: testapp-python-deployment
    server: https://kubernetes.default.svc
  project: kumo
  source:
    path: apps/testapp-python-deployment
    repoURL: https://github.com/myorg/myapp
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
```
2. Push manifest to a git argo-cd state repo.
3. Create an app of apps
```shell
argocd app create master-app \
            --dest-namespace argocd \
            --dest-server https://kubernetes.default.svc \
            --repo https://github.com/myorg/argo-cd-state-repo \
            --path global \
            --directory-recurse
```
4. Sync master-app `argocd app sync master-app --grpc-web`
5. Update app with 
```yaml
syncPolicy:
  manual:
    prune: true
```
6. Sync the child app `argocd app sync testapp-python-deployment --grpc-web --prune`
7. Sync is successful 

**Expected behavior**

The `testapp-python-deployment` app should no longer have `auto-sync` enabled.

**Actual behavior**

The `testapp-python-deployment` app still has `auto-sync` enabled even though it still has successfully synced to a commit that has the `syncPolicy` set to manual.

**Screenshots**

![Auto-sync enabled on app](https://user-images.githubusercontent.com/10181884/69882022-d8387c00-129c-11ea-8cc3-cbc260f2cd10.png)

![Active commit](https://user-images.githubusercontent.com/10181884/69882088-0a49de00-129d-11ea-95f0-2b40b3473735.png)

Proof that the app has manual sync set in the active commit:
```shell
git show 528af0d767825beab28afa7a1f07b0ae2b084a71:global/testapp-python-deployment.yaml | ag sync -A 2
  syncPolicy:
    manual:
      prune: true
```

**Version**

```shell
argocd: v1.2.3+de7003f
  BuildDate: 2019-10-01T20:05:41Z
  GitCommit: de7003f530dbe0a8d49e2572b575a333ac7d803c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.3+de7003f
  BuildDate: 2019-10-01T20:05:11Z
  GitCommit: de7003f530dbe0a8d49e2572b575a333ac7d803c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1```
