### ISSUE TITLE
Diffing with slash in field name

### ISSUE THREAD

**Issue by mg03** [argoproj/argo-cd#2795]
Hi

I want to use ignoreDifferences for a annotation field in all services.  
In order to set it up as a system level configuration, I am modifying the argo-cm configmap.

Qs 1) What would be the resource name that I need to use for services?

Qs 2) In the ignoreDifferences section, can I provide a fieldname with a slash in it? suppose field name is "string1/string2"

data:
  resource.customizations: |
    <what is this for services????>:
      ignoreDifferences: |
        jsonPointers:
        - /metadata/annotations/string1/string2

**Comment by alexec** [comment]
These are JSON pointers. I believe you can use tilde character.

https://tools.ietf.org/html/rfc6901

**Comment by mg03** [comment]
ok thanx @alexec and the resource name under resource customizations does it follow a format. Is the format:  APIGROUP/KIND?

**Comment by Lirt** [comment]
So for example if I want to reference annotation `checksum/certs` from yaml like this:

```yaml
metadata:
  annotations:
    checksum/certs: "CHECKSUM"
```

RFC says that `/` is encoded as `~1`, so appropriate json pointer is this `/metadata/annotations/checksum~1certs`?

**Comment by maximmold** [comment]
Did this work for you? I've been struggling even with the ~1.

**Comment by maximmold** [comment]
I'm having issues ignoring a label in a CRD. It appears that K8S is automatically removing it for some reason and I'd like to just ignore it if the label is there in source control, but not showing up in K8S.

The CRD looks like this
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: velero
```

Here is my application spec...
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: tools
  source:
    repoURL: 'https://github.com/../...'
    plugin:
      
  ignoreDifferences:
    - group: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      namespace: velero
      jsonPointers:
        - /metadata/labels/app.kubernetes.io~1name
```

Does this not work with the custom plugin?

**Comment by younsl** [comment]
You can escape it by replacing the slash `/` with `~1` in the argocd application's jsonPointers.

Example of slash escaping an annotation named `checksum/clusteragent_token`:

```yaml
# argocd application resource yaml
spec:
  ignoreDifferences:
    - kind: Secret
      name: datadog-cluster-agent
      jsonPointers:
        - /data/token
    - group: apps
      kind: Deployment
      name: datadog-cluster-agent
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1clusteragent_token
    - group: apps
      kind: Deployment
      name: datadog-clusterchecks
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1clusteragent_token
```

Other slash escape example in [argocd docs](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration):

If you have a slash `/` in your pointer path, you need to replace it with the `~1` character.
For example:

```yaml
spec:
  ignoreDifferences:
  - kind: Node
    jsonPointers: /metadata/labels/node-role.kubernetes.io~1worker
```

## References

- [jsonPointer official docs](https://jsonpatch.com/#json-pointer)
- https://github.com/argoproj/argo-cd/issues/2918#issuecomment-1410883890
