### ISSUE TITLE
Upgrading to 1.3.2 broke an self-managed ArgoCD Application: revision HEAD must be resolved

### ISSUE THREAD

**Issue by jutley** [argoproj/argo-cd#2802]
After upgrading from v1.2.5 to v1.3.2, one of our Applications (which manages our ArgoCD itself) stopped working. When we look at it via the web UI, we see this warning in the bottom-right:
![image](https://user-images.githubusercontent.com/5660346/70097956-7e5aed80-15df-11ea-96e3-97139361e4eb.png)

Additionally, this is the current sync status:
![image](https://user-images.githubusercontent.com/5660346/70097993-97639e80-15df-11ea-8943-a4fcc22b7fb0.png)

And here are the sync details:
![image](https://user-images.githubusercontent.com/5660346/70098015-a5b1ba80-15df-11ea-80e5-923b29bf0fb4.png)

We are on Kubernetes v1.13.12. 

The application simply points to the upstream kustomize resources for ArgoCD, with some overlays that don't add anything particularly fancy. Just configuration within the scope of what ArgoCD documents. Also, we have other Applications that are using this repository successfully. What may be relevant is that this is our only Application that uses Kustomize.

Here is the spec of our application:
```
project: argocd
source:
  repoURL: 'git@github.com:myorg/myrepo'
  path: argocd-global
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd-global
syncPolicy: {}
```

This is the only relevant log I can find coming from the repo-server
```
time="2019-12-04T00:07:41Z" level=error msg="finished unary call with code Unknown" error="revision HEAD must be resolved" grpc.code=Unknown grpc.method=GetRevisionMetadata grpc.request.deadline="2019-12-04T00:08:41Z" grpc.service=repository.RepoServerService grpc.start_time="2019-12-04T00:07:41Z" grpc.time_ms=0.038 span.kind=server system=grpc
```

Update: I can also see that the repo-server is correctly resolving `HEAD`. After updating the application, I see the repo-server log this:
```
time="2019-12-04T00:13:19Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:git@github.com:myorg/myrepo,Path:argocd-global,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:,}/93ff092784cc2460da74fdcd9a88f394c4ef5b95"
```

**Comment by jutley** [comment]
It seems the error I'm seeing is coming from here, and was introduced in 1.3.1:
https://github.com/argoproj/argo-cd/blob/v1.3.2/reposerver/repository/repository.go#L715

**Comment by jutley** [comment]
I'm seeing that as I update my repo, ArgoCD is able to pull the changes and show me the diff. So many things still seem to work. I'm not sure what exactly is broken.

**Comment by alexec** [comment]
That error is from the UI and should be benign. Can you please share the app yaml?

**Comment by jutley** [comment]
This is the full file:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-argocd-global
spec:
  destination:
    namespace: argocd-global
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: argocd-global
    repoURL: <redacted>
  syncPolicy: {}
```

It's pretty basic. It seems to be mostly a UI issue, but this error message in the Application status seems interesting:
```
ComparisonError: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 0 for field Username
```
