### ISSUE TITLE
Rollback or sync to an older version does not delete resources in UI

### ISSUE THREAD

**Issue by jomeier** [argoproj/argo-cd#2840]
Hi,

I stumbled on an effect today on OpenShift (OKD) v3.11 where I rolled back from the current version in GIT to the previous version and resources still were visible in the UI but not in the cluster.

In my repository I have this deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app: hello-openshift
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: hello-openshift
          image: openshift/hello-openshift
          ports:
            - containerPort: 8080
```

I created a new version where only the name of the deployment changed from **example** to **example666**.

I wrote down both commit IDs (from the current version and the version before in GIT).

If I sync to the current version in GIT with
```
argocd app sync sepptest5 --prune --revision <current commit id, name=example666>
```
the current version is synced properly **both** in the cluster **and** the UI:
https://pasteboard.co/IKtY4qL.png

If I sync to an older version with
```
argocd app sync sepptest5 --prune --revision <commit id with old deployment name=example>
```
the current version is properly synced in the cluster **but not** in the UI:
https://pasteboard.co/IKtZaVD.png

If I sync to the current version in GIT again, everything looks good again.

Greetings,

Josef

### Version
```
argocd: v1.3.4+6f38cf3
  BuildDate: 2019-12-05T23:27:38Z
  GitCommit: 6f38cf313315a645492c2be6452a4e846c684b1c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.4+6f38cf3
  BuildDate: 2019-12-05T23:28:15Z
  GitCommit: 6f38cf313315a645492c2be6452a4e846c684b1c
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```
