### ISSUE TITLE
Application is incorrectly reporting a diff

### ISSUE THREAD

**Issue by jutley** [argoproj/argo-cd#2865]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

From the ArgoCD web console, some of our Applications (same service, many clusters) are reporting being out of sync. The diff in the details shows that a couple values for container env vars need to be added, but the live state shows that they are already there.

When I uncheck "Hide default fields", the full diff disappears, even without selecting the compact view.

When I use the argo cli, it doesn't show any diff, even though the exit code indicates there is one. I'm removing specifics about our deployment in this example.

```
➜  argocd --grpc-web --server <server> app diff <app>
===== extensions/Deployment <namespace>/<deployment> ======

➜  echo $?
1
```

**To Reproduce**

Create an application that points to a path containing this manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: VAR1
          value: var1
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      restartPolicy: Always
```

Make sure the application is synced. Then, manually edit the deployment using kubectl, adding this as the _first_ environment variable:
```
        - name: VAR2
          value: var2
```

The Application should now show to be out of sync.

From what I can tell, there _must_ be an environment variable that uses `valueFrom`. I've done this with both the downward api and a configmap. Additionally, the new environment variable _must_ be the first variable. 

**Expected behavior**

There should be no diff, and the app should report as synced.

**Version**

```shell
➜  argocd --grpc-web --server <server> version
argocd: v1.3.5+3e150df
  BuildDate: 2019-12-09T21:14:37Z
  GitCommit: 3e150df0ede862c476d2ad0b90717ae00a890551
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.5+3e150df
  BuildDate: 2019-12-09T21:14:05Z
  GitCommit: 3e150df0ede862c476d2ad0b90717ae00a890551
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```
