### ISSUE TITLE
IgnoreDifferences doesn't work on docker registry secrets

### ISSUE THREAD

**Issue by cabrinha** [argoproj/argo-cd#2875]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm using [kubernetes-replicator](https://github.com/mittwald/kubernetes-replicator) to copy docker registry credentials into different namespaces.

In order to do this, I create an "empty" secret in my Application's helm chart:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  annotations:
    replicator.v1.mittwald.de/replicate-from: default/regcred
  labels:
    env: {{ .Values.environment }}
    region: {{ .Values.region }}
data:
  .dockerconfigjson: e30K
type: kubernetes.io/dockerconfigjson
```

`e30K` is a base64 encoded `{}`. Once the empty secret is created, the replicator service overwrites the value of the `.dockerconfigjson` key, which ArgoCD immediately notices is now out of sync.

I've tried adding this to my Application manifest:

```yaml
ignoreDifferences:
  - group: apps
    kind: Secret
    jsonPointers:
      - /data/.dockerconfigjson # and /data/\.dockerconfigjson
```

But it doesn't seem to work.

**To Reproduce**

Use [kubernetes-replicator](https://github.com/mittwald/kubernetes-replicator) to alter an empty docker registry secret, try to apply an `ignoreDifferences` section to your Application spec and see that ArgoCD will see the resource as out-of-sync.

**Expected behavior**

I expect ArgoCD to ignore the differences in my secret object.

**Screenshots**

![Screen Shot 2019-12-13 at 9 14 53 AM](https://user-images.githubusercontent.com/775203/70819184-69721d00-1d8a-11ea-9755-8c9573fd07ae.png)

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.2+a5a65cd
  BuildDate: 2019-12-03T21:32:18Z
  GitCommit: a5a65cdfe7c43fd1e3beada202d80c19bc50bd40
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

As an aside, it'd be nice to also document how to ignore other common resources like image tag when using with rollouts.

**Comment by alexmt** [comment]
Finally got time to reproduce it and realized that secrets are no in `apps` group. So settings should be 

```
ignoreDifferences:
  - group: 
     kind: Secret
     jsonPointers:
       - /data/.dockerconfigjson # and /data/\.dockerconfigjson
```

**Comment by taintedkernel** [comment]
Just putting this in here in case someone else hits it, for my version & deployment of docker-registry I had to use the following:

```
ignoreDifferences:
  - kind: Secret
    name: docker-registry-secret
    jsonPointers:
      - /data/haSharedSecret
```

**Comment by sfitzgerald96** [comment]
I had still had trouble with the above solutions. Argo doesn't have the Out of Sync errors with these solutions, but when another sync comes after it it reverts the secret back to e30K.

What ended up working for me on Argo v2.3.4 was using kube-replicator's [push-based replication](https://github.com/mittwald/kubernetes-replicator#push-based-replication).

**Comment by mdrakiburrahman** [comment]
This did the trick for me - was using SealedSecrets with Kustomize - here's the App of Apps:
```yaml
ignoreDifferences:
    - kind: Secret
      jsonPointers:
      - /data
```
