### ISSUE TITLE
Dex client secret not masked in logs for Microsoft

### ISSUE THREAD

**Issue by cehoffman** [argoproj/argo-cd#2904]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When setting the client secret for the microsoft dex connector, the client secret is output in logs

**To Reproduce**

Configure Dex to use the microsoft connector.

**Expected behavior**

The logs have the client secret masked.

**Screenshots**

<img width="1663" alt="Screen Shot 2019-12-18 at 8 17 45 PM" src="https://user-images.githubusercontent.com/27545/71139401-ac415400-21d3-11ea-8265-8ad33df0093c.png">
**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0

```

**Logs**

```
Paste any relevant application logs here.
```

I think what is happening is that the secret is line wrapped in the YAML output because of its length. There is nothing I can do about this though, because Azure does not let me set my own passwords for application client secrets.

**Comment by cehoffman** [comment]
The source of this error is the YAML generated for dex uses the YAML multiline string literal

```yaml
  dex.config: |
    connectors:
    - type: microsoft
      id: microsoft
      name: Azure
      config:
        clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        clientSecret: $dex.oidc.microsoft.clientSecret
        redirectURI: https://10.207.15.215/api/dex/callback
        tenant: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        onlySecurityGroups: true                
```

The generated dex config is

```yaml

connectors:
- config:
    clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    clientSecret: |
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    onlySecurityGroups: true
    redirectURI: https://10.207.15.215/api/dex/callback
    tenant: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  id: microsoft
  name: Azure
  type: microsoft
```

This is what is breaking the secret masking in logs, but this is also breaking other connectors like GitLab for dex.

It appears what I had used to create the base64 value included a newline at the end of the secret. This is what forced the YAML deserialize to output using `|`.
