### ISSUE TITLE
Maintain difference in cluster and git values for specific fields

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-cd#2913]
# Summary
If another controller modifies a field in a resource and that field is required by the resource to be created, then that resource cannot be compatible with GitOps. The manifest stored in Git requires that field in order to be created, but another controller will modify that field once created making it out of sync. Argo CD should have an annotation called `argocd.argoproj.io/respect-existing-fields` that accepts JSON paths to fields that are managed by other controllers. That annotation should use stored in the Kubernetes instead of applying what is in Git when Argo CD does a diff or apply. This is a step further than https://argoproj.github.io/argo-cd/user-guide/diffing/#application-level-configuration

# Motivation
Istio Virtual Services require a weight when two destinations are listed in a route. If a user creates the Virtual Service using GitOps and another controller modifies those weights to shape traffic, the Virtual Service will be out of sync with what is stored in Git. If there is a Sync, the Virtual Service will be revert to the Git state and then the other controller should revert it back.

# Proposal

How do you think this should be implemented?

The application controller should look for this annotation on all objects within the repo while executing a diff or sync. If found, the diffing logic should not figure this information into Diff status, and the apply logic should not change this value in the cluster.

Questions/Concerns that should be addressed during the implementation:
- How should the annotation be applied if the annotation itself is modified in Git?
- The `argocd app get manifest` command should return the actual Git contents instead of the modified Git contents.
- The annotation should be able to index an entire array (i.e. `spec.http.[*].route[*].weight` means check each entry of http and the entries within each route.)
- Allow multiple fields to ignore

**Comment by akhy** [comment]
Shouldn't it be already addressed by this custom diffing feature? 

https://argoproj.github.io/argo-cd/user-guide/diffing/

**Comment by shibataka000** [comment]
Custom diffing feature can ignore difference in specific fields. But it can't prevent ArgoCD from change resources when other fields are changed which are not specified in custom diffing feature.

Following example show details.

1. Configure ArgoCD to ignore difference at `spec.replicas` fields in `Deployment` resource.

```yaml
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
```

2. Create `Deployment` resource by ArgoCD.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 64Mi
            cpu: 100m
```

3. Change `spec.replicas` of `Deployment` . As we expected, ArgoCD ignore difference.

```bash
kubectl patch deployments.apps nginx -p '{"spec":{"replicas":2}}'
```

4. Change `metadata.labels.app` of `Deployment` . ArgoCD notice difference between manifests in git repository and actual resources in kubernetes cluster.

```bash
kubectl patch deployments.apps nginx -p '{"metadata":{"labels":{"app":"nginx-updated"}}}'
```

5. Sync ArgoCD `Application` resources by ArgoCD.
6. You can find that value of `spec.replicas` is reverted to `1`.

```bash
kubectl get deployments.apps nginx -o jsonpath='{.spec.replicas}'
```

So custom diffing feature doesn't satisfy following statement in proposal.

> and the apply logic should not change this value in the cluster.

**Comment by dulltz** [comment]
It seems intuitive to me to prevent fields specified in `ignoreDifferences` from being overwritten by static values stored in git, 
so I think we should solve this issue in a way that extends `ignoreDifferences`.

How about adding `respectExistingValue` field to skip updating the field ?
We can also keep the existing behavior by setting the default to `false`.

```yaml
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    respectExistingValue: true
```

**Comment by ironashram** [comment]
@dulltz solution would solve a similar issue i am facing

**Comment by alexmt** [comment]
wow, it has a lot of thumbs-ups. Adding to proposal discussion queue to make sure it is prioritized appropriately.

**Comment by leoluz** [comment]
After further discussion with @alexmt and @jessesuen we came up with the following proposal. Basically we agreed that there are two different new features related to this issue:

## 1. Leveraging `managedFields` 
Using the `managedFields` structure to define which managers should have their fields preserved and never overwritten by the desired state (git) values. This provides a better user experience as users can define how to ignore diffs based on `managers` instead of doing it field-by-field.
The example bellow show how users would be able to configure ArgoCD to ignore differences made by the `kube-controller-manager`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - kube-controller-manager
```

Note that `ignoreDifferences` structure remains with its current responsibility of guiding how ArgoCD compute diffs currently used to display in ArgoCD UI. This configuration has no impact during the sync process.

## 2. Respect differences during sync
The ability to instruct ArgoCD to respect the `ignoreDifferences` configurations during the sync process.

The example bellow shows how users would enable this feature:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
```

The two features above could be used in isolation as well as combined allowing users to decide how they want to apply the desired state in their clusters and how to react upon conflicts.

The current idea is providing two separate PR's for each of the features.
