### ISSUE TITLE
Ignoring Dynamic Volume Claims

### ISSUE THREAD

**Issue by Silvenga** [argoproj/argo-cd#2924]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Argo-cd should support ignoring dynamically provisioned volume claims using the `ignoreDifferences` syntax.

**To Reproduce**

Given the following project definition:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-galera
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mariadb-galera
    targetRevision: 0.5.6
    helm:
      valueFiles:
        - values-production.yaml
      values: |
        rootUser:
          password: password
        db:
          database: dummy
          user: dummy
          password: password
        galera:
          mariabackup:
            password: password

        persistence:
          enabled: true
          subPath: mariadb-galera
          storageClass: csi-cephfs (any dynamic pv)
          accessModes:
            - ReadWriteMany
          size: 100Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: default
```

Multiple volume claims are created by Kubernetes.

e.g. `data-mariadb-galera-0`, `data-mariadb-galera-1`, `data-mariadb-galera-2`

This leads to an expected out-of-sync state within argo-cd. Attempting to ignore these dynamic claims, like so, fails:

```yaml
  ignoreDifferences:
    - group: ''
      kind: PersistentVolumeClaim
      jsonPointers:
      - "/"
      - ""
      - "."
      - "/spec"
      - "/status"
      - "/metadata"
    - kind: PersistentVolumeClaim
      jsonPointers:
      - "/"
      - ""
      - "."
      - "/spec"
      - "/status"
      - "/metadata"
```

(just trying everything I can think of).

**Expected behavior**

I would expect that ignoring the json root (either with `/` or `<zero-length string>`) would ignore the entire resource.

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:46:45Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```
