### ISSUE TITLE
Add QBEC support

### ISSUE THREAD

**Issue by kvaps** [argoproj/argo-cd#2930]
# Summary

Please add support for QBEC (https://qbec.io/) as alternative to ksonnet.

# Motivation

Ksonnet is [deprecated](https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/) almost year ago. [Qbec](https://github.com/splunk/qbec) is closest and enhanced alternative to it.

It supports the similar logic with components and environments, can render helm charts and do another amazing stuff.

Here is an [example app](https://github.com/splunk/qbec/tree/master/examples/test-app) described for the qbec

# Proposal

Argo CD [should detect](https://argoproj.github.io/argo-cd/user-guide/tool_detection/) [`qbec.yaml`](https://github.com/splunk/qbec/blob/master/examples/test-app/qbec.yaml) file in repository, and associate it with qbec application.

Example apply for incluster call:
```
qbec apply dev --root examples/test-app --force:k8s-context __incluster__ --wait --yes
```

where:
- `dev` -  name of environment to apply
- `--root examples/test-app` - path to application
- `--force:k8s-context __incluster__` forces to override context for incluster run
- `--wait` - wait until resources be ready
- `--yes` - just disables `Are you sure?` during apply

**Comment by kvaps** [comment]
OK I have some time to configure the plugin for qbec:

```yaml
# cm.yaml
data:
  configManagementPlugins: |
    - name: qbec
      generate:
        command: [sh, -xc]
        args: ['qbec show "$ENVIRONMENT" -S --force:k8s-namespace "$ARGOCD_APP_NAMESPACE"']
```

```yaml
# deploy.yaml
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
      - name: custom-tools
        emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
      - name: download-tools
        image: alpine:3.12
        command: [sh, -c]
        args:
        - wget -qO- https://github.com/splunk/qbec/releases/download/v0.12.2/qbec-linux-amd64.tar.gz | tar -xvzf - -C /custom-tools/
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/qbec
          name: custom-tools
          subPath: qbec
        - mountPath: /usr/local/bin/jsonnet-qbec
          name: custom-tools
          subPath: jsonnet-qbec
```

```bash
kubectl patch deploy/argocd-repo-server -p "$(cat deploy.yaml)"
kubectl patch cm/argocd-cm -p "$(cat cm.yaml)"
```

And example application:
```bash
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbec-app
  namespace: argocd
spec:
  destination: 
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: qbec-app
    plugin: 
      env: 
        - name: ENVIRONMENT
          value: default
      name: qbec
    repoURL: https://github.com/kvaps/argocd-play
  syncPolicy: 
    automated: 
      prune: true
```
