### ISSUE TITLE
Undocumented surprise requirement of the argocd-cm configmap

### ISSUE THREAD

**Issue by thefirstofthe300** [argoproj/argo-cd#2931]
As far as I can tell, this particular requirement is not documented anywhere but in the source code: https://github.com/argoproj/argo-cd/blob/91b0cd0a4745f288e78a8cff2dfdf942281e5e1d/util/settings/settings.go#L288

I just spent about three hours trying to figure out why Argo was not seeing a CM that was clearly there. Just wanting to help save other people some hassle.

For posterity and to make this issue more searchable, the error I saw was 

```
configmap \"argocd-cm\" not found
```

**Comment by asaushkin** [comment]
I had been trying to use argocd-util and also found this bug. But my ConfigMap is annotated with this label.

```
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
```

Trying to run export:

```
$ argocd-util export 
FATA[0000] configmaps "argocd-cm" not found
```
