### ISSUE TITLE
Make Helm values field templatable using Kustomize

### ISSUE THREAD

**Issue by carlosjgp** [argoproj/argo-cd#2936]
# Summary

Use a YAML structure for `argoproj.io/v1alpha1/Application.spec.source.helm.values` instead of `string` to allow Kustomize to change properties per environment

# Motivation

Helm allows to template charts using YAML files typically called `values.yaml` files

I found myself repeating code across environments for charts that include their configuration on these `values.yaml` files, like Prometheus chart. 
It happens that loads of apps are using YAML files themselves to be configured

ArgoCD currently supports Kustomize which is a great tool to template YAML files and could solve this problem easily but since `argoproj.io/v1alpha1/Application.spec.source.helm.values` is a string Kustomize can't change few properties.

In this particular case, it could be even better since Prometheus configuration itself is expressed on YAML format so I could tweak tiny bits thanks to Kustomize

```
- prometheus-kustomize
  |- base
  |  |- kustomization.yaml
  |  |- prometheus.yaml
  |- ci
  |  |- kustomization.yaml
  |  |- patch.yaml
...
```

`prometheus.yaml` would contain all the common configuration
- chart repo
- chart version
- release name
- Alertmanager global webhook shared across all environments but without receivers
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    chart: prometheus
    helm:
      releaseName: prometheus
      values:
        alertmanagerFiles:
          alertmanager.yml:
            global:
              slack_api_url: https://hooks.slack.com/services/xxxxxxx
  ```

`patch.yaml` little changes like which channel on Slack will receive the notifications

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    helm:
      values:
        alertmanagerFiles:
          alertmanager.yml:
            receivers:
              - name: prometheus-alert
                slack_configs:
                  - channel: '#ci-alerts'
```

# Proposal

Change the field [`spec.source.helm.values`](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L182) to be a generic YAML structure (`map`?) to allow Kustomize to template these values

**Comment by lienerieksta** [comment]
I second this request. The benefits of having yaml values (just as flux does them) are more than just ability to  kustomize them.

Yaml syntax highlighting would be preserved - Less errors and easier to debug.

Easier to manage by various CI tools - One could just edit the application definition directly, commit it back to the repository and be done with it. As it is now it's a hassle to get the values variable first and then parse it again and then write the variable and then write it back to Application.

The values are not even parsed and merged with chart defaults in the UI. This leads to incorrect app parameters shown in the UI and it's just asking for erroneous troubleshooting decisions. 

Forcing user to split the values and define some as parameters, just to have an accurate depiction in UI and cleaner CI code, complicates the manifest and makes it harder to read. In a gitops situation I see that as a workaround to get the same results that could be achieved by values alone.  


Tbh, I'm surprised that this issue has so little support. Though I account it to poor documentation - it does not even hint in the docs that you can define values in a variable. It's just shows in the example Application yaml. This and the huge amount of issues that beg for ability to fetch a values file from a separate location indicates that a good part of them either have not found the feature even exists or are not happy with the implementation. I'm sure that changing the values string to a yaml format and documenting it properly would appease most of those requests.

**Comment by jacobscunn07** [comment]
I am currently working on a POC for Argo CD and this is something that I've run into. I'd love to be able to define the base values for a helm chart, but then override them in a kustomize overlay. As mentioned, I'm doing a POC over ArgoCD and Flux v2 and a couple of core features I am looking for is to declaratively define helm chart releases and support for kustomize. Ideally, the two would work together as well.

**Comment by carlosjgp** [comment]
As a workaround my previous company did develop a custom plugin using Kustomize to render the expected ArgoCD `Application` of type `helm`

I hope they open source it soon but it's not crazy complicated to bake your own... they did use Python but any programming language could be used for this purpose

It'd be a winning hand for Argo having this when it's time to compare with other GitOps solutions

**Comment by mcanevet** [comment]
Would it be possible to use an array of maps instead of a map so that we can pass multiple values as the `helm` binary supports it?

```shell
helm template --help
...
  -f, --values strings               specify values in a YAML file or a URL (can specify multiple)
...
```
i.e.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    chart: prometheus
    helm:
      releaseName: prometheus
      values:
        - alertmanagerFiles:
            alertmanager.yml:
              global:
                slack_api_url: https://hooks.slack.com/services/xxxxxxx
        - alertmanagerFiles:
            alertmanager.yml:
              receivers:
                - name: prometheus-alert
                  slack_configs:
                    - channel: '#ci-alerts'
```
