### ISSUE TITLE
Dex version 2.14.0 cause login without respecting gitlab groups policy

### ISSUE THREAD

**Issue by CDimonaco** [argoproj/argo-cd#2958]
Checklist:

* [ X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X ] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

On the latest `argocd` version, with the dex server on the image `quay.io/dexidp/dex:v2.14.0`, a bug caused by `dex` itself, cannot create a correct oauth policy on authentication.

When you specify in the `groups` on the `dex` config, with the `gitlab` plugin, the groups will be not whitelisted, so any gitlab user can access the `argocd` console using the dex authentication method.

I solved this issue upgrading the dex image in the dex server deployment to `quay.io/dexidp/dex:v2.21.0`

**To Reproduce**

You can simply configure a dex connector, of type `gitlab` and restrict the users with some group, you will notice that when you can login with every gitlab user.

You can notice the successfully login procedure on the dex server pod.

**Example configuration**

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: YOUR REDIRECT URL
  dex.config: |
    connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        config:
          clientID: $client_id
          clientSecret: $sso_secret
          groups:
          - your group
```

**Expected behavior**

The users should be restricted to specified groups.

**Screenshots**

N/A

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:46:45Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
N/A
```
