### ISSUE TITLE
ArgoCD isn't templating helm loops properly

### ISSUE THREAD

**Issue by De1taE1even** [argoproj/argo-cd#2973]
**Describe the bug**

I'm creating an "app-of-apps" within ArgoCD.  All of our applications are very similar, so rather than create a separate template for each app within the chart, I created a single template with a range loop around it.  Instead of creating all of the apps, argocd is only creating the last one in the loop.

**To Reproduce**

Here's my template:
```yaml
{{- range $application, $parameters := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application }}
  namespace: {{ $.Values.core.argocdNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.core.argocdProjectName }}
{{- if eq $parameters.autoSync true }}
  syncPolicy:
    automated:
{{- if hasKey $parameters "prune" }}
      prune: {{ $parameters.prune }}
{{- else }}
      prune: true
{{- end }}
{{- if hasKey $parameters "selfHeal" }}
      selfHeal: {{ $parameters.selfHeal }}
{{- end }}
{{- end }}
  destination:
    namespace: {{ $.Values.core.kasewareNamespace }}
    server: {{ $.Values.core.kubernetesServer | quote }}
  source:
    path: {{ $.Values.core.helmPath }}/{{ $application }}
    repoURL: {{ $.Values.core.repoUrl | quote }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - {{ $.Values.core.valuesFileName }}
      parameters:
        - name: core.dockerTag
          value: {{ $parameters.dockerTag }}
{{- end }}
```
Here's a snippet of my values file:
```yaml
apps:
  browserless:
    dockerTag: 1.0.0
    autoSync: false
  clamav:
    dockerTag: 1.0.0
    autoSync: false
  video:
    dockerTag: 1.0.0
    autoSync: false
```

**Expected behavior**

Since a helm template command on that chart shows me all the applications correctly, I would expect argocd to see the same, and create all applications appropriately.  Instead, only our 'video' application was created.

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Comment by De1taE1even** [comment]
Oops, sorry I figured out the issue.  I had forgotten to add the `---` app separator at the bottom of my loop.  ArgoCD is handling the loop just fine now.

**Comment by rivetmichael** [comment]
@De1taE1even could you give an example of how to use the `---` ?

**Comment by De1taE1even** [comment]
@rivetmichael The loop i have above, creates multiple ArgoCD applications in a single yaml file once helm templates it.  To contain multiple kubernetes objects in a single yaml file, you have to separate them using `---`.  So if you're using a loop, you need to put `---` at the bottom of the loop.
This won't work:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  <stuff>

apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  <stuff>
```
This works fine:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  <stuff>

---

apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  <stuff>
```

**Comment by kaustubhsharma-009** [comment]
I am facing the same issue but with cron job template. I have configured the template in a similar fashion cron job resource is not getting deployed at all
```
{{- if .Values.jobsEnabled }}
{{- range $key, $value := .Values.jobnamecron }}    # range present in values.yml for applying template iteratively
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $key | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    jobname: {{ $key | quote }}
    schedule: {{ $value | quote }}
spec:
  schedule: {{ $value | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: "{{ $.Values.image }}"
            imagePullPolicy: Always
            
            command: ["/bin/sh", "-c"]
            args:
              - cd ~;
                file="/parameter.json";
                echo "{"'"jobname"'":"'"'${JOBNAMECRON}'"'"}" > $file;
                chmod +x /parameter.json;
                cd /usr/src/app;
                npm --prefix packages/jobs start;
            env:
              - name: JOB_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobname']
              - name: JOBNAMECRON
                value: {{ $key | quote }}
              - name: JOB_SCHEDULE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['schedule']
          terminationGracePeriodSeconds: 60
          restartPolicy: "OnFailure"

      parallelism: 3
      completions: 2
  concurrencyPolicy: "Allow"
---
{{- end }}
{{- end }}
```

The values.yml snippet for this is: 
```
jobsEnabled: true
jobnamecron:
  job1: "* * * * *"
  job2: "*/2 * * * *"
  job3: "*/3 * * * *"
```
@De1taE1even 

Thanks
