### ISSUE TITLE
ArgoCD doesn't deal with changing a multiple entry sequence to a single entry sequence spanning multiple lines

### ISSUE THREAD

**Issue by thardie** [argoproj/argo-cd#2980]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Changing a deployments args from an array of items that fits onto 1 line into a single string that goes onto multiple lines results in ArgoCD wanting to keep just the last array entry from the original entry

**To Reproduce**

- Create a deployment or pod with a container with args with 2 or more entries and deploy it, e.g.:

```
command:
  - /usr/local/bin/somecommand
args:
  - averylongparameter1
  - averylongparameter2
  - averylongparameter3
  - averylongparameter4
```

- Change the args entry to be a single entry that wraps onto multiple lines:

```
command:
  - /bin/sh
  - -c
args:
  - /usr/local/bin/somecommand averlongparameter1 averylongparameter2
    averlongparameter3 averylongparameter4
```

ArgoCD will apply the command section change correctly, but not the args. Change will be:
```
command:
  - /usr/local/bin/somecommand
args:
  - averylongparameter4
```

**Expected behavior**

Apply the change to command and args correctly.

**Version**

```argocd: v1.2.4+ad7a69a
  BuildDate: 2019-10-23T20:06:03Z
  GitCommit: ad7a69a79883b7767cbeb88ca9a36d28277bd4ab
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
```

**Comment by dontreboot** [comment]
@jannfis @alexmt could you guys help here?

**Comment by jannfis** [comment]
Hm, cannot reproduce this behaviour. Given the following manifests:

First manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
      - image: argoproj/argocd:latest
        name: argocd-server
        ports:
        - containerPort: 80
        command:  
        - argocd-server
        args:
        - --staticassets                                                          
        - /shared/app                                                             
```
modified then to
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
      - image: argoproj/argocd:latest
        name: argocd-server
        ports:
        - containerPort: 80
        command:  
        - /bin/sh
        - -c
        args:
        - argocd-server 
          --staticassets
          /shared/app     
```
will result in a desired manifest in ArgoCD after refresh of:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: test
  name: argocd-test
  namespace: test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
        - args:
            - argocd-server --staticassets /shared/app
          command:
            - /bin/sh
            - '-c'
          image: 'argoproj/argocd:latest'
          name: argocd-server
          ports:
            - containerPort: 80
```
and sync/apply correctly.

Have I reproduced the use-case correctly? What version of ArgoCD are you using (your version paste is missing some info).
