### ISSUE TITLE
Replace aws-iam-authenticator with aws cli to fix EKS service account roles

### ISSUE THREAD

**Issue by jdmulloy** [argoproj/argo-cd#2996]
# Summary

Connections to eks clusters should use the aws cli to get the connection token instead of aws-iam-authenticator. aws-iam-authenticator hasn't released in over 6 months and thus still does not support OIDC based IAM role assumption as described here https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

# Motivation

We're setting up an argocd instance in a tools EKS cluster and we want it to connect to other EKS clusters via IAM. The aws-iam-authenticator doesn't pick up the AWS_WEB_IDENTITY_TOKEN_FILE environment variable. Master of aws-iam-authenticator pulls in an updated SDK version that should work, but it's not released yet and it doesn't seem like they will release any time soon. The AWS cli seems to be better supported and more frequently updated.

# Proposal

Replace aws-iam-authenticator with aws cli.

**Comment by alexmt** [comment]
Done, thanks to @jdmulloy !

**Comment by janwillies** [comment]
FWIW, I had to add this kustomize patch to make it read the token:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      securityContext:
        fsGroup: 999
```
