### ISSUE TITLE
make input box for ENV vars be a text area instead of simple input

### ISSUE THREAD

**Issue by travisghansen** [argoproj/argo-cd#2998]
# Summary

The input box (during creation and edit of an app using a custom config plugin) for `ENV` vars is a simple input. When multi-line values are input the rendering is bad visually (non-edit mode) and during edit it's very cumbersome.

# Motivation

Writing a custom configuration plugin which will have `ENV` vars that could potentially be quite large blocks yaml etc.

# Proposal

Change inputs to textareas.

Example snippet to illustrate the issue:

```
...
  plugin:
    name: helmfile
    env:
      - name: KUBE_VERSION
        value: '1.16'
      - name: HELMFILE_HELMFILE
        value: |-
          repositories:
          - name: stable
            url: https://kubernetes-charts.storage.googleapis.com
          - name: elastic
            url: https://helm.elastic.co
          - name: influx
            url: http://influx-charts.storage.googleapis.com
          - name: kiwigrid
            url: https://kiwigrid.github.io
          releases:
          - name: grafanatwo
            namespace: monitoring
            chart: stable/grafana
            set:
            - name: adminPassword
              value: admin
            - name: persistence.enabled
              value: true
            - name: ingress.enabled
              value: true
            - name: ingress.hosts[0]
              value: grafana.example.com
            - name: ingress.annotations.kubernetes\.io/ingress\.class
              value: traefik-internal
            - name: grafana\.ini.auth.disable_login_form
              value: true
            - name: grafana\.ini.auth\.anonymous.enabled
              value: true
            - name: grafana\.ini.auth\.anonymous.org_role
              value: Admin
...
```
