### ISSUE TITLE
Argo-CD not detecting/linking generated objects

### ISSUE THREAD

**Issue by tylerauerbeck** [argoproj/argo-cd#2999]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
When using Argo-CD to create subscriptions to operators from operator-hub, Argo only tracks the objects used for the subscription (i.e. a subscription, operatorgroup and then tracks these objects (and the installPlan that the subscription creates). However it doesn't detect any of the other objects that are also generated (clusterserviceversion, deployments, pods, etc.). What logic determines what objects are picked up? Are there labels that can be applied to these generated objects via a hook to have them included?

I would like to see all objects that are generated by my application so that I have a full picture of my deployment

**To Reproduce**

Apply the following configuration in a cluster running Operator Lifecycle Manager:

**operator-group**:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: my-operatorgroup
  namespace: my-namespace
spec:
  targetNamespaces:
  - my-namespace
```

**subscription**:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: opendatahub
  namespace: my-namespace
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: opendatahub-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
```

Once this has been applied, you'll notice that the operatorgroup and subscription are tracked, as well as a generated installPlan. However no other objects (i.e. the operator deployment or pods) are detected/tracked.

**Expected behavior**

I would like to see all objects that are generated by my application.

**Screenshots**
N/A

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**
N/A
