### ISSUE TITLE
GKE Authentication on Remote Cluster

### ISSUE THREAD

**Issue by brunodomenici** [argoproj/argo-cd#3027]
Hi,

Any recommendation to connect ArgoCD to a remote GKE cluster without client cert enabled?
Bearer Tokens seems not to be a good option since it will expire.

Is there anything configlike kubectl does with gcloud to refresh token?

Thanks a lot!

**Comment by alexmt** [comment]
We would have to make a code change to support it.

Argo CD already supports [IAM AWS authentication](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/declarative-setup.md#clusters):

```
# IAM authentication configuration
awsAuthConfig:
    clusterName: string
    roleARN: string
```

To support GKE we would have to bundle `gcloud` binary and use `gcloud auth --no-launch-browser`. https://cloud.google.com/sdk/gcloud/reference/auth/login

**Comment by FelixRodriguezJara** [comment]
Hello,

We are in a similar situation where we have to register an external cluster in a production implementation with ArgoCD and GKE. Are there any updates on this topic?

On this line, ¿what is the recommendation to securely connect a remote cluster in a productive environment?

Thank you very much.

Kind regards.

**Comment by FelixRodriguezJara** [comment]
Hi! We are in the middle of the Production Deployment and we would need to add remote clusters soon. Do you have any recommendations on how to secure remote GKE clusters when registering in ArgoCD?

Thank you very much.

Kind regards.

**Comment by test-account-0** [comment]
I'm using bearer token to add additional clusters. I don't think the tokens expire in gke.

What I do is:
  * create service account and clusterrolebinding on the destination cluster like this:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: argocd
  namespace: kube-system
```
  * get `server` from `kubectl cluster-info`
  * get certificate and the token
```sh
secret_name=$(kubectl -n kube-system get sa argocd \
    -o go-template='{{range .secrets}}{{.name}}{{"\n"}}{{end}}')
kubectl -n kube-system get secrets ${secret_name} -o go-template='{{index .data "ca.crt"}}'
kubectl -n kube-system get secrets ${secret_name} -o go-template='{{.data.token}}' | base64 -d
```
* put them in the `config` and create secret in argocd deployment as specified here https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "bearerToken": "<authentication token>", # this is the token, it cannot be base64
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>" # this is the ca.crt, it has to be base64
      }
    }
```
