### ISSUE TITLE
Helm "values: |" are ignored

### ISSUE THREAD

**Issue by ruzickap** [argoproj/argo-cd#3032]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When I create new application + specify the helm values as a block file (`values: |`) all these parameters are ignored.

**To Reproduce**

Here is the example of my application with helm values:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 2
        ingress:
          enabled: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
```

The important parts are where I would like to change the `replicaCount` and `ingress`:

```yaml
    helm:
      values: |
        replicaCount: 2
        ingress:
          enabled: true
```

Unfortunately both helm parameters are ignored.
(this is real example you you test it in your environment) 

**Expected behavior**

Helm chart values are going to be used...

**Screenshots**

![image](https://user-images.githubusercontent.com/1434387/73117177-ff7c9400-3f41-11ea-9a3c-922f75b62a84.png)

**Version**

```shell
v1.4.1+f8721a7
```

**Logs**

no logs collected

-> Maybe this issue is related to #2967
