### ISSUE TITLE
PVC created by volumeClaimTemplates always pruned

### ISSUE THREAD

**Issue by benjamin-bergia** [argoproj/argo-cd#3050]
**Describe the bug**

I have pruning enabled. When creating a statefulset with a volumeClaimTemplates, the pvc is created and immediately pruned by argocd.

**To Reproduce**
Create a statefulset with a volumeClaimTemplate, something like:
```
  volumeClaimTemplates:
  - metadata:
      labels:
        argocd.argoproj.io/instance: hep
      name: data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 50G
```
My current workaround is to add `argocd.argoproj.io/sync-options: Prune=false` to my volumeClaimTemplate. It avoid deleting the pvc, but it stays in out of sync.

**Expected behavior**

I would expect the PVC to show up in argocd as being in Sync

**Version**

```shell
argocd: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:53:00Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.4.0+2d02948
  BuildDate: 2020-01-18T05:55:02Z
  GitCommit: 2d029488aba6e5ad48b2a756bfcf43d5cb7abcee
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```
