### ISSUE TITLE
new Openshift project: not all resources are being applied

### ISSUE THREAD

**Issue by CurryWurry** [argoproj/argo-cd#3052]
**Describe the bug**

We try to create a new Openshift (4.2) project, called "my-test" and its containing resources using ArgoCD, version 1.4.2. The project is being created just fine, just like the DeploymentConfig and ImageStream. However, the config map, rolebinding, pull secret, and service are not being synced. 

Error in ArgoCD is "SyncFailed: namespaces my-test not found". **When manually re-syncing, the resources are created just fine.** 

Maybe a coinsidence, but only the Openshift CRD's (like IS, DeploymentConfig,...) are created at the first run, not the K8 resources. 
The resources are provided in one yaml file to ArgoCD. 

**To Reproduce**

The project CRD:

`apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: my-test
    openshift.io/display-name: my-test
    openshift.io/requester: argocd
  labels:
    app: my-test
    app.kubernetes.io/instance: my-test
  name: my-test
spec:
  finalizers:
    - kubernetes
status:
  phase: Active`

**Expected behavior**

All resources must be created. 

**Version**

argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0

**Comment by dgoodwin** [comment]
Could you include sample yaml to demonstrate the problem?

It's not overly surprising that there might be a delay between project creation and the namespace being available for use, but it is puzzling that the OpenShift types don't experience the problem despite being namespaced. An example would help here as I'm curious if they were perhaps later in the application and thus it might have been ready at that point?

I'm curious if anyone has seen similar problems with Namespace + resources in that namespace in one yaml file, delivered via kubectl apply or similar. I can't recall seeing this myself.

Is your expectation that this should work in one try? Or that ArgoCD should handle the error and retry more quickly? How long does it take to sort out with auto-sync on?

We've seen similar if you try to deliver a CRD and then a resource for that CRD in one yaml blob, sometimes the apiserver will reject because the CRD is not fully available just yet and a retry is needed.

**Comment by dgoodwin** [comment]
I've attempted to replicate with a test branch in this repo, and using Argo 1.4.1.

```
$ argocd app create project-test --repo https://github.com/dgoodwin/openshift4-gitops.git --path=project-test --dest-server=https://kubernetes.default.svc --revision project-testing --dest-namespace=project-test
```

This file just contains a project, a configmap, and a deploymentconfig. My result:

```yaml
    syncResult:                            
      resources:                              
      - group: ""     
        hookPhase: Failed  
        kind: ConfigMap                                                                                   
        message: namespaces "project-test" not found                                                      
        name: test-cm                                                                                     
        namespace: project-test
        status: SyncFailed                                                                                                                                                                                          
        syncPhase: Sync                                                                                   
        version: v1                                                                                                                                                                                                 
      - group: apps.openshift.io                                                                          
        hookPhase: Failed         
        kind: DeploymentConfig                                                                                                                                                                                      
        message: namespaces "project-test" not found                                                      
        name: memsql-master           
        namespace: project-test                                                                                                                                                                                     
        status: SyncFailed                                                                                
        syncPhase: Sync                    
        version: v1                                       
```

So I'm not seeing any difference between an OpenShift type and a core v1 type. (which is what I would expect)

Re-syncing and everything is successful.

If I switch my application to create a kube Namespace, instead of a OpenShift Project, everything applies fine.

I think the delay between creation of a Project and the OpenShift controllers creating the Namespace for it is throwing everything off here, Project creation is successful, but there's a very small delay before the Namespace is ready, whereas if you create a Namespace directly, it is immediately available in the apiserver.

I tried with --sync-policy=automated, but this doesn't seem to help, Argo does not appear to immediately re-try an operation on failure. @alexmt would you consider that a bug or expected behavior? I'm not sure of the history there. Often controllers will try failures with backoff, does Argo only kick back in if there's a git change or a change in the cluster resources?

Suspect there's nothing Argo can do here, and your best option is just to use Namespace directly, but will wait to hear back if anyone feels there should be some kind of retry on a sync failure.
