### ISSUE TITLE
Can't create new App

### ISSUE THREAD

**Issue by Leletir** [argoproj/argo-cd#3077]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I cannot create an application, I have this error:
```
time="2020-02-03T12:27:43Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to initialize git repo: mkdir /tmp/https:__mygitrepo_myproject: read-only file system" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2020-02-03T12:27:33Z" grpc.time_ms=10245.296 span.kind=server system=grpc
W0203 12:28:26.481346       1 reflector.go:299] github.com/argoproj/argo-cd/util/settings/settings.go:556: watch of *v1.ConfigMap ended with: too old resource version: 264126707 (264127732)
error: unexpected EOF
```

**To Reproduce**

First of all, I had to patch the argocd manifests in order to deploy Argo inside my company cluster:
Here is the manifest of argocd-server:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - command:
        - argocd-server
        - --staticassets
        - /shared/app
        image: argoproj/argocd:v1.4.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        name: argocd-server
        ports:
        - containerPort: 8080
        - containerPort: 8083
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 240m
            memory: 256Mi
        volumeMounts:
        - mountPath: /app/config/ssh
          name: ssh-known-hosts
        - mountPath: /app/config/tls
          name: tls-certs
        - mountPath: /tmp
          name: tmp-dir
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
      serviceAccountName: argocd-server
      volumes:
      - emptyDir: {}
        name: tmp-dir
      - emptyDir: {}
        name: static-files
      - configMap:
          name: argocd-ssh-known-hosts-cm
        name: ssh-known-hosts
      - configMap:
          name: argocd-tls-certs-cm
        name: tls-certs
```

I have the error when i execute:
```bash
argocd app create score-fraude \
  --repo https://mygitrepo/myproject.git \
  --path "." \
  --dest-server https://kubernetes.default.svc \
  --dest-namespace my-namespace
```

I had to add a security context in order to be able to start the container, as you can see here:
```yaml
securityContext:
   fsGroup: 999
   runAsGroup: 999
   runAsUser: 999
```

When I look the rights on /tmp, I have:
```
drwxrwsrwx   2 root argocd 4096 Feb  1 14:22 tmp
```

and the user can create a file to /tmp, that's why I don't understand the error in the logs.

**Version**

```shell
argocd: v1.4.2+48cced9
argocd-server: v1.4.0+2d02948
```

Thank you for your help.

**Comment by jannfis** [comment]
Hi @Leletir - I believe that this error message is proxied through from `argocd-repo-server`. 

Have you adapted that container's spec as well, especially with the empty dir `/tmp` mount? Can you execute for example `touch /tmp/foobar` on the `argocd-repo-server` pod?

**Comment by Leletir** [comment]
Hi @jannfis,

Thank you very much ! I was thinking the problem was on the `argocd-server` side. 

I add to `argocd-repo-server` deployment:
```yaml
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /app/config/ssh
          name: ssh-known-hosts
        - mountPath: /app/config/tls
          name: tls-certs
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
      volumes:
      - emptyDir: {}
        name: tmp-dir
      - configMap:
          name: argocd-ssh-known-hosts-cm
        name: ssh-known-hosts
      - configMap:
          name: argocd-tls-certs-cm
        name: tls-certs
```
