### ISSUE TITLE
Support private GitHub repo authentication using GitHub app

### ISSUE THREAD

**Issue by omerlh** [argoproj/argo-cd#3086]
# Summary

Support private repositories authentication using [GitHub app authentication](
https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation).
# Motivation

We want to use argocd with multiple private repositories. The current options are:

1. Create a deploy key for each repository and upload them to argocd (hard to manage)
2. Create a user for argocd (expensive, as you need to pay for a seat in the organization).

# Proposal

Add support for GitHub app authentication. Allow the user to define the credentials using something like: 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/argoproj/private-repo
    - url: https://github.com/argoproj/other-private-repo
  repository.credentials: |
    - url: https://github.com/argoproj
      githubAppPrivateKey:
        name: my-secret
        key: privateKey
      githubInstallationId: <>
```

**Comment by KarstenSiemer** [comment]
Additionally I'd like to add that apps provide a far greater rate limit, have fine grained access control and as a huge plus, you don't even need to manage users for it.
Overall a pretty damn fine feature if you ask me.
But would mean quite some work with the ttl of the tokens and would only benefit users of github.

**Comment by hendrikmaus** [comment]
I have started to work on the feature last week, but after reading through https://github.com/argoproj/argo-cd/issues/4348 I am not confident that github-specific code might make it into argo-cd at all. Could someone from the maintainer team shed some light if it is worth to continue on the feature?

**Comment by joebowbeer** [comment]
@jetersen @omerlh close this one as well?

**Comment by joebowbeer** [comment]
This does not appear to be working yet for private repos in an organization.

If I try to connect to a private repo then the repo is added to the Repositories list, but the Connection Status shows as Failed. (With a public repo, the connection status is Successful.)

GitHub Apps have read access to metadata (mandatory) so I assume they can see the private repos? I tried one GitHub App with read access to repo content and another with read/write access, but neither could connect successfully.

**Comment by diranged** [comment]
> This does not appear to be working yet for private repos. Irregardless of whether they are personal repos or organization repos.
> 
> If I try to connect to a private repo then the repo is added to the Repositories list, but the Connection Status shows as Failed. (With a public repo, the connection status is Successful.)
> 
> I tried a few different GitHub Apps in personal and organization contexts. In all cases they have read access to metadata (mandatory) so I assume they can see the private repos? I tried one GitHub App with read access to repo content and another with read/write access, but neither could connect successfully.

We are using the Github App feature and absolutely cloning dozens of private Github.com-managed repositories in a private business organization. Can you elaborate on what problems you are seeing?

**Comment by joebowbeer** [comment]
@diranged If I try to connect to a private repo (either org or user) then the repo is added to the Repositories list, but the Connection Status shows **Failed**.

With a public repo (either org or user), the connection status is Successful, so I conclude that what I'm trying to do is more or less correct.

Can you elaborate more on what you are doing in order to make this work? I can't find any demos or tests for this feature, so I'm flying blind. However, the fact that what I'm doing works for public repos in GitHub.com organizations (or user owned) leads me to believe that the problem is related to private repos.

OTOH, perhaps the `Connection Status: Failed` is a false negative?

**Comment by diranged** [comment]
> @diranged If I try to connect to a private repo (either org or user) then the repo is added to the Repositories list, but the Connection Status shows **Failed**.
> 
> With a public repo (either org or user), the connection status is Successful, so I conclude that what I'm trying to do is more or less correct.
> 
> Can you elaborate more on what you are doing in order to make this work? I can't find any demos or tests for this feature, so I'm flying blind. However, the fact that what I'm doing works for public repos in GitHub.com organizations (or user owned) leads me to believe that the problem is related to private repos.
> 
> OTOH, perhaps the `Connection Status: Failed` is a false negative?

Make sure you are using the "Repository Template", not a particular "Repository"... you are setting up, for example, "gitub.com/MyOrg" as a template, and then any Application object can refer to "https://github.com/MyOrg/<insert repo>.git" and it will automatically handle authenticating for you.

**Comment by joebowbeer** [comment]
@diranged How do you apply the template? Do you have a command-line sequence that works?

See #6093 

Are you suggesting that I add a repository template and then add an Application rather than add a Repository?

**Comment by diranged** [comment]
> @diranged How do you apply the template? Do you have a command-line sequence that works?
> 
> See #6093
> 
> Are you suggesting that I add a Repository Template and then add an Application rather than add a Repository?

We do everything via the declarative setup model.. but yes.. you create a repository template, then just add Applications that use repositories that match the template.

**Comment by diranged** [comment]
> > @diranged How do you apply the template? Do you have a command-line sequence that works?
> > See #6093
> > Are you suggesting that I add a Repository Template and then add an Application rather than add a Repository?
> 
> We do everything via the declarative setup model.. but yes.. you create a repository template, then just add Applications that use repositories that match the template.

Sorry it was late last night and I was too tired to find the code.. but we use the `argocd` helm chart. In that chart, here's our config:

```
      repository.credentials: |
        # https://github.com/organizations/xyz/settings/installations/123344
        - type: git
          url: https://github.com/xyz
          githubAppID: xxx
          githubAppInstallationID: xxx
          githubAppPrivateKey:
            key: privateKey
            name: gitops-app-credentials  # templates/github-repo-key.yaml
```

So we have no specific `Repository` configurations, just the Repository Template configuration above.. because if you think about it, there's no real point to using a Github App that specifically is tied to only one repository, you'd just use an SSH Deploy Key.

**Comment by joebowbeer** [comment]
@diranged thanks for details. I see what you mean about repo being unnecessary in the presence of repocreds, though this works with non-GitHub-App connections in both command line and UI, so I think there are some issues.

However, back to the chase, I'll try the declarative setup:

https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#repository-credentials

**Comment by joebowbeer** [comment]
@diranged I checked out your helm chart configuration and compared it to what is created by the UI and CLI.

Our configs differ in one key:
* `githubAppPrivateKey` (yours)
* `githubAppPrivateKeySecret` (mine)

From my argocd-cm ConfigMap:

```
  repository.credentials: |
    - githubAppID: 123
      githubAppInstallationID: 456
      githubAppPrivateKeySecret:
        key: githubAppPrivateKey
        name: repo-xxx
      url: https://github.com/MyOrg/
```

My config, created by CLI and/or UI, seems to agree with the docs, however, looking at the code, I see many more occurrences of `githubAppPrivateKey` than of `githubAppPrivateKeySecret`, which may be related to why your config is working and mine is not?
