### ISSUE TITLE
Improved OTS helm chart support #2183

### ISSUE THREAD

**Issue by omerlh** [argoproj/argo-cd#3101]
# Summary

Today, support for OTS helm charts is not ideal - you have to define 3 files for each chart:
 - requirements.yaml
 - Chart.yaml
 - values.yaml (optional)

This makes the process a bit cumbersome to use.

# Motivation

We have a lot of OTS charts we're using and creating those files for each chart is a very tedious process. 

# Proposal

Something similar to Flux's helm operator [CRD](https://github.com/fluxcd/helm-operator/blob/master/docs/references/helmrelease-custom-resource.md) - the ability to define the repo and chart name as part of the CRD. This would eliminate the need for the 2 additional files (Chart.yaml and requirements.yaml).
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexmt** [comment]
Argo CD has first-class helm support https://blog.argoproj.io/argo-cd-v1-3-generally-available-6a7d80595bf4.  You might point Argo CD application to the helm repository directly and specify values in the application spec:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: default

  source:
    repoURL: 'https://kubernetes-charts-incubator.storage.googleapis.com/'
    targetRevision: 0.1.*
    chart: grafana

    helm:
      valueFiles:
      - values-prod.yaml
      
      values: |
        ingress:
          enabled: true
```

@omerlh can you please confirm this is what you are looking for?
