### ISSUE TITLE
Auto update helm chart to the latest version

### ISSUE THREAD

**Issue by danilorsilva** [argoproj/argo-cd#3146]
Hello all,

     I have create a new application using my private helm repository. So i choose the chart and the version 1.0 and apply.
     When i release a new version of my chart (2.0 or 1.5), is there a way to argocd automatic update my application to the latest version available of the chart?

Thanks!

**Comment by alexmt** [comment]
Hello @danilorsilva ,

This is supported. You might specify version [range](https://helm.sh/docs/topics/chart_best_practices/dependencies/#scrollpane) instead of exact version. E.g. 4.0.* instead of 4.0.0.

**Comment by andrejpetras** [comment]
Hi @alexmt ,

I tried but it doesn't work for me.
This is my application yaml file
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ping-qaurkus
  namespace: {{ .Values.spec.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: ping-quarkus
    repoURL: https://my.helm.repository/
    targetRevision: 0.1.*
    helm:
      parameters:
        - name: "image.pullSecret"
          value: {{ .Values.spec.imagePullSecrets }}    
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
```
![image](https://user-images.githubusercontent.com/828045/76243947-72fc0b80-6239-11ea-891b-a104cb29995d.png)

In ArgoCD I have this error:
```
ComparisonError
rpc error: code = Unknown desc = constraint not found in index
3 hours ago (Mon Mar 09 2020 16:06:21 GMT+0100)
```
