### ISSUE TITLE
Ability to deploy multiple components and application using one file and argocd cli 

### ISSUE THREAD

**Issue by y4roslav** [argoproj/argo-cd#3155]
# Summary

For massive deployment it is nice to have option to deploy multiple applications/components using one file 

# Motivation

In case if I have many components of the same big solution and I need to cherry-pick components for specific installation. It is nice to have something like `deployment` file that I can execute.  

# Proposal

Is there possibility to create file like this: 

```
---
project: kubeflow
source:
  repoURL: 'git@github.com:project/some-manifests.git'
  path: istio/istio-install/base
  targetRevision: a235b98
destination:
  server: 'https://kubernetes.default.svc'
  namespace: istio-system
syncPolicy:
  automated:
    selfHeal: true
--- 
project: kubeflow
source:
  repoURL: 'git@github.com:project/some-manifests.git'
  path: istio/istio-crd/base
destination:
  server: 'https://kubernetes.default.svc'
  namespace: istio-system
syncPolicy:
  automated:
    selfHeal: true
--- 
```

And execute it as: 

` argocd app create --some-flag path/to/manifest`

Please advise 

PS
There can be such option for one manifest that I'm not seeing.
