### ISSUE TITLE
cannot access helm repositories via proxy

### ISSUE THREAD

**Issue by astrajohn** [argoproj/argo-cd#3158]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

I am deploying argocd on a private network and need to use a proxy server to access the internet. By adding proxy env variables to the argocd server, argo repo server and argo application controller I can pull from git repos but not helm repos, where I receive connection refused.

**To Reproduce**

1. Deploy argocd with env variables to set proxy as follows for argocd server
```
env:
  - name: NO_PROXY
   value: argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,10.0.0.0/8
  - name: HTTP_PROXY
   value: {{ proxy }}
  - name: HTTPS_PROXY
   value: {{ proxy }}
```
2. Attempt to connect to helm repository

**Expected behavior**

receive the following error:
Unable to connect HTTPS repository: Get https://jexample/index.yaml: dial tcp xxx.xxx.xx.xx:443: connect: connection refused

**Screenshots**

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
time="2020-02-25T19:50:03Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2020-02-25T19:50:03Z" grpc.time_ms=0.112 span.kind=server system=grpc
time="2020-02-25T19:53:13Z" level=error msg="finished unary call with code Unknown" error="Get https://jupyterhub.github.io/helm-chart/index.yaml: dial tcp 185.199.109.153:443: connect: connection refused" grpc.code=Unknown grpc.method=Create 
```
