### ISSUE TITLE
WebhookConfiguration objects are ignored

### ISSUE THREAD

**Issue by jeanlucmongrain** [argoproj/argo-cd#3171]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

I'm using the web UI installed with [official helm chart](https://github.com/argoproj/argo-helm/) Which is 1.4.2.

I'm trying to install this:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproj
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: MyApp
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - https://kubernetes-charts.storage.googleapis.com/
  - https://charts.appscode.com/stable
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
  project: myproj
  source:
    chart: stash
    repoURL: https://charts.appscode.com/stable
    targetRevision: v0.9.0-rc.6
    helm: ""
```

It works if I install with helm 2 or 3. But with ArgoCD there is 2 k8s objects ignored, both are `*WebhookConfiguration`. One of the 2 is [admission.stash.appscode.com](https://github.com/stashed/installer/blob/57f829a57567cec3b890d22a8940908e6557277c/charts/stash/templates/validating-webhook.yaml#L6)

When I click `sync` it's never created, it's not showing up in the web UI and it's not in the `APP DIFF` view.

I `kubectl exec` into the repository-server pod and I copied the `/tmp/values-*.yaml` while it was running and ran it manually:

```console
argocd@cluster-argocd-repo-server-64866bc448-2n8xm:/tmp/
helm template . --name stash --namespace kube-system --kube-version 1.17 --values /tmp/z/values-651977800.yaml
```

and eventually those 2 webooks show up:

```yaml
---
# Source: stash/templates/validating-webhook.yaml
# GKE returns Major:"1", Minor:"10+"
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.stash.appscode.com
```

Followed by the rest of the YAML.

So, Helm 2 is really generating the YAML from those templates, it's just it's being ignored by ArgoCD.
