### ISSUE TITLE
bug: deleting project and application at the same time using autosync&prune

### ISSUE THREAD

**Issue by wecger** [argoproj/argo-cd#3175]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In an environment with the following conditions: 
- ArgoCD is using declarative setup in an apps of apps style
- all apps are set to auto-sync including auto-prune

I wanted to delete one of the projects and the applications using the project. So I deleted the files defining the approject and the application in a single commit. 

ArgoCD picked up the diff and started the sync and successfully deleted the project. For the deletion of the application, ArgoCD wants to prune all objects now, but the project is deleted already, Therefore ArgoCD stopped to delete the objects, because there is no project matching the application.

**To Reproduce**

- create a project and an application using this project with autosync and prune enabled
- create an app maintaining this project and application using autosync and autoprune
- commit and push to repo
- wait for the sync to create all objects
- delete the new project and application from repo
- commit and push
-> project gets deleted, application is in unknown state trying to delete its objects

**Expected behavior**

ArgoCD waits for the deletion of the application (including its maintained objects) before the project gets deleted.

**Screenshots**

**Version**

```shell
argocd-server: v1.4.2+unknown
  BuildDate: 2020-02-03T11:45:44Z
  GitCommit:
  GitTreeState: clean
  GoVersion: go1.13.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.3 GitCommit:f8412aa3d39f32151525aff97a351288f5a7470b BuildDate:2019-10-08T23:30:25Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
ComparisonError     appproject.argoproj.io "deletebug-test" not found
DeletionError       appproject.argoproj.io "deletebug-test" not found
InvalidSpecError    Application referencing project deletebug-test which does not exist
```

**Comment by wecger** [comment]
as a workaround I recreated the project and then deletion of the application took place. Afterwards I deleted the project again.

So to avoid this bug:
- one commit/sync to delete the applications
- then another commit/sync to delete the projects

**Comment by jessebye** [comment]
We're seeing this too. We delete all the manifests from Git at the same time. The resources get stuck in "Progressing" / "Unknown" / "Deleting":
![image](https://user-images.githubusercontent.com/8467862/80245473-97f8e200-861f-11ea-8e4e-ab3cf6983543.png)

The error logged:
```
ComparisonError 
rpc error: code = Unknown desc = xxxxxx/deployments/cloakroom-ovens: app path does not exist
```

**Comment by alexmt** [comment]
Two changes have been implemented so far: 

* Application deletion removes resources in reverse order: https://github.com/argoproj/argo-cd/pull/3959. So if projects are assigned for the first wave then projects would be created first and deleted after all applications are deleted.
* Projects can be protected by `resources-finalizer.argocd.argoproj.io` finalizer. If finalizer is added then project won't be deleted until it is referenced by applications.

**Comment by mcanevet** [comment]
Somehow this does not work for me. Maybe because I'm using [Application in any Namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/)?
Here is an example of what I have:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: internal-developer-platform
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  description: AppProject for internal-developer-platform Applications
  destinations:
    - namespace: internal-developer-platform*
      server: 'https://kubernetes.default.svc'
  sourceNamespaces:
    - internal-developer-platform
  sourceRepos:
    - '*'
```
and
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: app-of-apps
  namespace: internal-developer-platform
spec:
  destination:
    namespace: internal-developer-platform
    server: 'https://kubernetes.default.svc'
  project: internal-developer-platform
  source:
    directory:
      recurse: true
    path: <mypath>
    repoURL: <myrepourl>
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
Both resources are declared in the same Application (my app-of-app-of-apps), and when I delete it, the `AppProject` is destroy before the `Application`, while I have the sync-wave annotation and the finalizer...
