### ISSUE TITLE
Cannot create roles using argocd-rbac-cm configmap policy

### ISSUE THREAD

**Issue by pydo** [argoproj/argo-cd#3177]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I've tried multiple permutations of this example policy
https://argoproj.github.io/argo-cd/operator-manual/rbac/#tying-it-all-together ,
but none of them resulted in a role being implicitly created.

**To Reproduce**

Policies used:

policy_1
```
p, role:read-only-bot, applications, *, kumo/*, allow
p, role:read-only-bot, clusters, *, kumo/*, allow
g, myorg:dev-ops, role:admin
```
policy_2
```
p, role:read-only-bot, applications, *, */*, allow
p, role:read-only-bot, clusters, *, */*, allow
g, mygithuborg:dev-ops, role:admin
```

1. Grab the 1.4.2 argocd manifest https://github.com/argoproj/argo-cd/blob/v1.4.2/manifests/install.yaml
2. Add this rbac configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    policy_$N
```
3. Install argocd
4. Login to the argocd UI using either the admin credentials or the SSO integration.
5. Head to the projects page
6. Neither the `kumo` nor the `default` project have any roles.

**Expected behavior**

6. `policy_1`
There should be a role called `read-only-bot` under the `kumo` project.

6. `policy_2`
There should be a role called `read-only-bot` under the `default` project.

**Screenshots**

![Screen Shot 2020-03-02 at 12 40 23 PM](https://user-images.githubusercontent.com/10181884/75702206-086c2e00-5c83-11ea-8550-2f0218a55b05.png)

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```
