### ISSUE TITLE
App of Apps not working when using kustomize applications

### ISSUE THREAD

**Issue by ageekymonk** [argoproj/argo-cd#3181]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating an Apps of Apps, where each app is a kustomize app, apps donot get created. They throw the following error.  ```one or more synchronization tasks are not valid```. If i apply manually the app alone it works. 

**To Reproduce**
Create a kustomize app which points to another kustomize app. 

**Expected behavior**

Apps of Apps should be created. 

**Screenshots**

![Screen Shot 2020-03-03 at 10 47 27 am](https://user-images.githubusercontent.com/271647/75728664-7bf05880-5ce0-11ea-8660-9452bbc29964.png)

**Version**
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0

**Comment by shabbir-taulia** [comment]
Sorry for commenting on this issue, but I seem to be running into the same using helm app of apps too. Running a sync results in the following 
```
argoproj.io  Application  argocd     test-app                      OutOfSync  Missing        the server could not find the requested resource
```
And looking at the the `application` object i see
```
status:
  health:
    status: Missing
  observedAt: "2020-05-05T00:55:28Z"
  operationState:
    finishedAt: "2020-05-05T00:55:28Z"
    message: one or more synchronization tasks are not valid
    operation:
      initiatedBy:
        username: admin
```

Whereas adding the applications individually via the UI seems to work without any issues.

**Comment by Woland2k** [comment]
Same error as above with argo 1.5.4 and kustomize templates.

**Comment by AustinSmart** [comment]
I have the same error w/ a Helm App of Apps. All application manifests specify `namespace: argocd`.

**Comment by FearTheBadger** [comment]
This is still a problem in 1.6.1

```
argocd version --client
  argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server version
  argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
Kustomize version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
Kubectl Version:
  Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", 
  GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-10-31T21:06:55Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

The error from the application controller:
```
level=info msg="adding resource result, status: 'SyncFailed', phase: '', message: 'the server could not find the requested resource'" application=test kind=Kustomization name= namespace=test phase=Sync syncId=00008-PFwkm
level=info msg="Updating operation state. phase: Running -> Failed, message: '' -> 'one or more synchronization tasks are not valid'" application=test syncId=00009-cRIAm
level=info msg="sync/terminate complete" application=test duration=7.003573ms syncId=00009-cRIAm
level=info msg="updated 'test' operation (phase: Failed)"
level=info msg="Sync operation to 056d4f65824e28726b07ca417ed9452cdbd30db5 failed: one or more synchronization tasks are not valid" application=test dest-namespace=test dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning
```

**Comment by flickerfly** [comment]
One thing I've discovered in my research is the API endpoint `yourargocd.com/api/v1/repositories/{repo}/apps`. It appears that if if hit, with the problematic {repo} name, it would result in some context for where the issue manifests. It is document on your ArgoCD UI at the path `yourargocd.com/swagger-ui#operation/ListApps`. 

I'm wondering, is it that ArgoCD isn't recognizing Kustomize is involved so trying to actually add the Kustomization type to the cluster rather than processing it? If so, how does ArgoCD get triggered on this?

In the interest of discovering that information, but not being a Golang guy, I found these hopefully relevant bits. There is apparently two ways this is supposed to be triggered. There is some documentation in the [Tool Detection Doc](https://argoproj.github.io/argo-cd/user-guide/tool_detection/), but it left me with some questions and clearly it isn't working exactly as documented.

 _First,_ auto-detection based on the contents of the repo.

So what does the code use to determine if a directory of code should be handled as a Kustomize appType? 
The answer appears to be on [line 168 of kustomize.go](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/util/kustomize/kustomize.go#L168). 

    var KustomizationNames = []string{"kustomization.yaml", "kustomization.yml", "Kustomization"}

This is then used on [line 181](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/util/kustomize/kustomize.go#L181) in the isKustomization function. It appears very consistent with [the docs](https://argoproj.github.io/argo-cd/user-guide/tool_detection/).

This info is used by `reposerver/repository/repository.go` on [line 100](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/reposerver/repository/repository.go#L100) in the ListApps function. There is also a ListApps function in `server/repository/repository.go` on [line 155](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/server/repository/repository.go#L155), but this one doesn't use the `discovery.Discover` function, but instead calling the API ListApps endpoint. 

_Second_, explicit identification in the `Application` resource as `spec.source.kustomize`. I'm not clear on what this should be if I just want to explicitly say this should use kustomize, but not change other characteristics. Maybe `spec.source.kustomize: []`? `pkg/apis/application/v1alpha1/types.go` [line 2260](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/pkg/apis/application/v1alpha1/types.go#L2260) seems to be involved and best I can tell anything non-nil would be acceptable.

The two methods of detection appear to come together in `reposerver/repository/repository.go` function [GetAppSourceType](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/reposerver/repository/repository.go#L451) where it first checks ExplicitType, then if that comes back blank, uses [discovery.AppType](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/util/app/discovery/discovery.go#L39) to tell [GenerateManifests](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/reposerver/repository/repository.go#L353) which type of application to output manifests for and hopefully hits [line 378](https://github.com/argoproj/argo-cd/blob/3d4d64e1b7ec1f7d1fa59d02d82960512dead84c/reposerver/repository/repository.go#L378) where it gets processed by Kustomize. 

My suspicion is that we aren't making it this far, but I don't know how to watch the code at work.

**Comment by FearTheBadger** [comment]
I think I have finally found the trigger point.

All `kustomization.yaml` files will be ignored, or `kind: Kustomization` configs will throw the error above, if the application source directory `recurse: true` is set. `recurse: false` or omitting recurse works without issue. 

Failing scenario:
``` yaml
kind: Application
spec:
  source:
    directory:
      recurse: true
```

Successful scenario:
``` yaml
kind: Application
spec:
  source:
    directory:
      recurse: false
```

**Comment by dpennell** [comment]
> edit: for anyone who found themselves here while trying out the App of App patterns. If your child apps are deploying to a different cluster, make sure your _parent_ app has destination `server: https://kubernetes.default.svc` as that is where the child ArgoCD Application resources are created and tracked.

This works for app of apps where all of the children are apps.  If any of the children are simple resources (e.g. Secret), the end up being created in the local cluster and not the external one.

**Comment by bitva77** [comment]
is this really still an issue?  I'm POC'ing ArgoCD now but this bug makes it seem like App of Apps configuration is broken and so what's the point

**Comment by bobbywatson3** [comment]
I'm in the same boat as @bitva77 . Our app of apps is a mixture of applications (off the shelf helm charts) and template files in the app of apps chart. Is that not supported?

**Comment by flickerfly** [comment]
It does seem to work, but there are some gotchas along the way. The one that had us really twisted is that you can NOT set up the app to be recursive or it doesn't properly detect what is going on and ArgoCD gets terribly confused.

**Comment by bobbywatson3** [comment]
If you have to deploy the app of apps to the cluster

> I think I have finally found the trigger point.
> 
> All `kustomization.yaml` files will be ignored, or `kind: Kustomization` configs will throw the error above, if the application source directory `recurse: true` is set. `recurse: false` or omitting recurse works without issue.
> 
> Failing scenario:
> 
> ```yaml
> kind: Application
> spec:
>   source:
>     directory:
>       recurse: true
> ```
> 
> Successful scenario:
> 
> ```yaml
> kind: Application
> spec:
>   source:
>     directory:
>       recurse: false
> ```

I tried this, and the app stayed out of sync. It could never sync the directory recurse section. [Apparently recurse: false is the default behavior.](https://github.com/argoproj/argo-cd/issues/4501#issuecomment-705208165)

I ended up not using this tiny kustomize file, instead copying in the entire 26,000 line cert-manager kube file. Bummer, but it works.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
```

**Comment by riweston** [comment]
> I think I have finally found the trigger point.
> 
> All `kustomization.yaml` files will be ignored, or `kind: Kustomization` configs will throw the error above, if the application source directory `recurse: true` is set. `recurse: false` or omitting recurse works without issue.
> 
> Failing scenario:
> 
> ```yaml
> kind: Application
> spec:
>   source:
>     directory:
>       recurse: true
> ```
> 
> Successful scenario:
> 
> ```yaml
> kind: Application
> spec:
>   source:
>     directory:
>       recurse: false
> ```

Is there any way around this? I'm specifically trying to use a number of kustomize.yml configs in my repo and rely on all applications being recursively deployed from a kustomize file but I'm seeing the same sync issues unless I disable recursion

In my case I'm trying to run a bootstrap that then adds an app-of-apps to argocd where I expect my source of truth for everything to be.

```shell
.
├── argocd
│  ├── argocd
│  │  └── kustomization.yml
│  └── sealed-secrets
│     └── kustomization.yml
├── bootstrap
│  └── kustomization.yml
├── juju
│  ├── deployment.yml
│  └── README.md
├── kustomize
│  ├── argocd
│  │  ├── app.yml
│  │  ├── cm.rbac.yml
│  │  ├── cm.repos.yml
│  │  ├── cm.sso.yml
│  │  ├── kustomization.yml
│  │  ├── overlay.argocd.yml
│  │  ├── overlay.secrets.yml
│  │  ├── resource.ingress.yml
│  │  ├── resource.namespace.yml
│  │  ├── resource.project.yml
│  │  └── resource.secrets.yml
│  └── sealed-secrets
│     ├── app.yml
│     └── kustomization.yml
└── README.md
```

```yaml
# argocd/argocd/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomize/argocd/
```

```yaml
# kustomize/argocd/app.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    path: argocd
    directory:
      recurse: true
...
```

**Comment by bygui86** [comment]
Hi guys, any news about this issue?

**Comment by selcuk-cofe** [comment]
That issue still exist I m using 2.0.5 and in the middle of the POC with kustomization app of apps repo. I already tried @Woland2k and @FearTheBadger recommendation but still have no luck child apps stuck at OutOfSync

argocd: v2.0.5+4c94d88.dirty
  BuildDate: 2021-07-23T05:12:02Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: dirty
  GoVersion: go1.16.6
  Compiler: gc
  Platform: darwin/amd64

**Comment by Janikio** [comment]
I am also facing this issue with the subchart pattern of helm.

**Comment by trajakovic** [comment]
I can confirm. This issue still exists to this date:
`{
    "Version": "v2.1.6+a346cf9",
    "BuildDate": "2021-10-28T19:59:40Z",
    "GitCommit": "a346cf933e10d872eae26bff8e58c5e7ac40db25",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}`

**Comment by jordan-seemplicity** [comment]
I suppose it makes sense that this wouldn't work, since there is ambiguity in how to handle a directory containing both an `Application` manifest as well as a Kustomize entrypoint in some sub-directory with recursion enabled - do we deploy the Kustomize manifest as part of the base app or as part of the dependent app?

It would be nice if Argo was "smarter" about how to deploy the app of apps when using Kustomize, i.e., allow recursive directories, but only for `Application` manifests. Maybe implementing some kind of globbing filter would help:

```yaml
spec:
  directory:
    recurse: true
    pattern: **/app.yaml
```

For the time being, my seed app is set to `directory.recurse: false` and pointing to a flat directory of app manifests (`clusters/cluster-1`). Each app manifest points to its own sub-directory (`clusters/cluster-1/my-app`), containing Kustomize manifests or Helm charts. Recursion can be independently configured for each app as needed.

**Comment by marcofranssen** [comment]
Thanks to @crenshaw-dev I was able to resolve the issue.

**Solution**

All applications have to be installed in the argocd namespace.

So like

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  …
```

Following is not yet supported and will probably land in the next `2.5.x` release.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: my-other-namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  …
```

So `namespace: argocd` is a hard requirement with current release of ArgoCD.

**Comment by winston0410** [comment]
> > I think I have finally found the trigger point.
> > All `kustomization.yaml` files will be ignored, or `kind: Kustomization` configs will throw the error above, if the application source directory `recurse: true` is set. `recurse: false` or omitting recurse works without issue.
> > Failing scenario:
> > ```yaml
> > kind: Application
> > spec:
> >   source:
> >     directory:
> >       recurse: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Successful scenario:
> > ```yaml
> > kind: Application
> > spec:
> >   source:
> >     directory:
> >       recurse: false
> > ```
> 
> I tried this, and the app stayed out of sync. It could never sync the directory recurse section. [Apparently recurse: false is the default behavior.](https://github.com/argoproj/argo-cd/issues/4501#issuecomment-705208165)
> 
> I ended up not using this tiny kustomize file, instead copying in the entire 26,000 line cert-manager kube file. Bummer, but it works.
> 
> ```
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> namespace: cert-manager
> resources:
> - github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
> ```

I am getting an error mentioned by [this ticket](https://github.com/kubernetes-sigs/kustomize/issues/738), when I tried to use a yaml with `kind: Kustomization`. How did you workaround and apply that yaml with argocd at the end?

The error that I got:

```
2022-09-26T23:36:30+01:00  kustomize.config.k8s.io  Kustomization     default                        OutOfSync  Missing              the server could not find the requested resource
```

**Comment by jhodnett2** [comment]
I think Argo-CD is getting confused about the apiVersion and kind as was mentioned before:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
```

The problem is that it tries to apply that file but there is no controller/api service to handle that kind.  

I've just removed those 2 lines and all is fine. 

I'm researching if I should have a controller/custom resource def for that type (for completeness).  kubectl works fine without those lines.  And so does Argo-CD.  Hope this works for others.

**Comment by Xtigyro** [comment]
+1

**Comment by rafael-adorna-incode** [comment]
+1

**Comment by sjonpaulbrown-cc** [comment]
This should be supported since `v0.2.5`. The [following documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/) outlines how to configure argo to deploy to any namespace. After initially configuring argo, I have configured it to self-manage itself, and using the below configuration, I have updated it to support deployments to any namespace.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cd
  sources:
    - repoURL: https://github.com/argoproj/argo-cd.git
      targetRevision: v2.10.6
      path: examples/k8s-rbac/argocd-server-applications

    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.7.11
      helm:
        valuesObject:
          configs:
            application.namespaces: "*"
          redis-ha:
            enabled: false
          controller:
            replicas: 1
          server:
            autoscaling:
              enabled: true
              minReplicas: 2
          repoServer:
            autoscaling:
              enabled: true
              minReplicas: 2
          applicationSet:
            replicas: 2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

The key points here are that the  `configs` section of the `values` needs to have `application.namespaces: "*"` set to your namespaces or any namespace. It would likely be best to isolate these to only the namespaces that you want to control with argo rather than leaving it open with a wildcard.

```
          configs:
            application.namespaces: "*"
```

Along with that, the additional RBAC resources must be created to grant argo the access it needs. This is handled in the other source that I had outlined.

```
    - repoURL: https://github.com/argoproj/argo-cd.git
      targetRevision: v2.10.6
      path: examples/k8s-rbac/argocd-server-applications
```
After updating the config & RBAC, you can now create argo Applications in new namespaces. When creating the `Application`, you need to make sure that your project supports the source namespace. This can be added to your project using the following. Once again, it would be best practice to limit the namespaces to only those that you want to support rather than leaving it wide open. To be fully clear, the `sourceNamespace` is specific to the Argo Applications that are deploying resources to a specific destination namespace.

```
spec:
  sourceNamespaces:
    - "*"
```

After adding this, I can deploy the argo application to a separate namespace, and I have been able to successfully deploy a combination of helm resources & manifests to the the same destination namespace from a single app of apps.
