### ISSUE TITLE
argocd-server-role is too privileged

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#319]
I see the following rule in `argocd-server-role`:
```
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
```

I don't see why the API server needs to do anything with pods in the cluster it's installed in. I think this whole section can be removed.
