### ISSUE TITLE
unable to use namespace isolation

### ISSUE THREAD

**Issue by ryandawsonuk** [argoproj/argo-cd#3191]
Restricting permissions to just using per-namespace RBAC was [recently added and the v1.4.0 release notes cover adding a cluster](https://github.com/argoproj/argo-cd/issues/2176#issuecomment-584746217). I'm trying to use this (with v1.4.2) and I'm able to add a cluster and a project. But any permutation I've tried of creating an app then fails.

Am working with an existing setup that has cluster-wide permissions and that all works fine. I'm trying to port it to using the per-namespace RBAC but can't create an app. If I set the dest-server as a URL (the one returned as SERVER in `argocd cluster list`) then I get this error
```
InvalidSpecError: application destination {https://xx.xx.xx.xx default} is not permitted in project 'project'
```
I've also tried using the name and then I get this error:
```
InvalidSpecError: Unable to get cluster: rpc error: code = NotFound desc = cluster "<NAME>" not found
```
I can use the same command when I've got cluster-wide permissions and it works fine so the problem must be permission-related.

I should say I've taken the un-namespaced ClusterRoles from the argocd install yaml and modified them so that instead they're named to argocd and then created them again for the namespace I'm using.

**Comment by ryandawsonuk** [comment]
Related - https://github.com/argoproj/argo-cd/issues/3197

**Comment by jannfis** [comment]
Hi @ryandawsonuk, can you please post your project definition and also the application definition? The error message suggests that you want to create an app in namespace `default`, but this seems to be not allowed by your project `project`. Newly created projects by default do not allow any destinations, and they must be allowed explicitly.

**Comment by ryandawsonuk** [comment]
I'll check and get back to you

**Comment by ryandawsonuk** [comment]
You're right, this was a slip on my part. Apologies.

**Comment by ryandawsonuk** [comment]
What I did to get this working was change the `argocd-application-controller` clusterrole to only use read verbs:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - list
      - get
      - watch
  - nonResourceURLs:
      - '*'
    verbs:
      - list
      - get
      - watch
```
Then each time I add a namespace I need to create a Role and bind it to the serviceAccount:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
  namespace: ${namespace}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-application-controller
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
```
I also did the same with any write roles for the `argocd-server` serviceAccount. Read roles do seem to need to be cluster-wide.
