### ISSUE TITLE
syncPolicy validate being deleted upon failed sync

### ISSUE THREAD

**Issue by shaikatz** [argoproj/argo-cd#3208]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Creating an application with 
```
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  validate: false
```

Then trying to sync the application with validation error, yields failed sync.
Observing the app manifest after the sync and finding that `validate: false` was deleted from the app definition.
I see 2 problems here:
- Why does it validate the sync?
- Why does it remove the `validate: false` after the failed sync.

**To Reproduce**
Create app with
```
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  validate: false
```
Put some invalid manifests and try to sync. Observe the results.

**Expected behavior**
The app should not validate the sync and shouldn't remove the `validate: false` from the app manifest.

**Screenshots**

**Version**
`1.4.2`
