### ISSUE TITLE
Unable to connect to repository parse <repo_name> first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by lr-carmichael** [argoproj/argo-cd#3210]
Checklist:

* [X ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When trying to setup a repo declaratively, I get an error in the GUI:

Unable to connect to repository parse git@github.com:carmichael/sandbox.git first path segment in URL cannot contain colon.

**To Reproduce**

Add a resource to your kustomization.yaml that sets up repos for an ArgoCD deployment.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: "git@github.com:carmichael/sandbox.git"
      sshPrivateKeySecret:
        name: repo-ssh-keypair
        key: sshPrivateKey
```

Look at the GUI > repos and you'll notice the error specified above.

Setting this same repo up in the GUI or with `argocd repo add` works great.  Example:

```bash
# add private repo to Argo
argocd repo add git@github.com:carmichael/sandbox.git --ssh-private-key-path ~/.ssh/id_rsa

```

**Expected behavior**

I expect the repo to connect like it does using the other installation methods.  Our goal is to let ArgoCD manage the ArgoCD installation, as outlined in your declarative page.

**Version**

```shell
argocd version
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.0+a00798b
  BuildDate: 2020-03-08T04:20:36Z
  GitCommit: a00798bc5ea1193337173be22d4ba41b05f7b239
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0

```

I've tried pointing to the `v1.4.2` tag as well as master.  Bug exists in both versions.

**Logs**

Could not find any relevant logs.

**Comment by jannfis** [comment]
Hi @lr-carmichael - can you please try to explicitly set repository type to "git" in your spec and see if that works, i.e.
```yaml
  repositories: |
    - url: "git@github.com:carmichael/sandbox.git"
      sshPrivateKeySecret:
        name: repo-ssh-keypair
        key: sshPrivateKey
      type: git
```
