### ISSUE TITLE
Named JWT tokens

### ISSUE THREAD

**Issue by chancez** [argoproj/argo-cd#3213]
# Summary

JWTs should be named, so we can define `AppProject`'s that have roles referencing tokens with names, rather than `iat` to make it simpler to automate configuration of `AppProject`s.

# Motivation

I'd like to define an AppProject for use in multiple K8s clusters, which contains a role for CI and other tools to use. 

Doing this is difficult because I cannot associate the role with tokens until after I have created the tokens and get their `iat` value. This also means the AppProject is different per environment which makes it more difficult to automate configuration and setup for new environments.

Currently, I have a multi-step process which involves CI installing argocd using kustomize, along with the bootstrap `Application`,  and `AppProject`. It also creates an initial role and token using the argocd CLI. However, the initial `kustomization.yaml` used to install the `AppProject` doesn't set the `jwtTokens`, and that must be set using a patch, _after_ the initial install, as the token is not known until after install time, since we must create tokens post-install, and then go back an update the file to include the JWT token created. However, even this doesn't really work well because the `create-token` sub command updates our AppRole to add the new token's `iat` to the `jwtTokens` list, but  if our CI/CD pipeline runs again it'll overwrite the token added and there's no way to get the token IDs from the argocd CLI that I can see.

# Proposal

I think tokens should be namable. You create them with an optional name, and then reference the token by name in your `AppProject`.

If you reference a token by name that doesn't exist, nothing can use a non-existent token, so there are no permissions issues. Since you can already reference a token that doesn't exist via `iat`, there should be no issues.

Example:

```
argocd --port-forward --port-forward-namespace argocd proj role create-token my-proj ci-role --name ci-token
```

Once created, you could then reference the token like so:

```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-proj
spec:
  description: My project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: ci-role
      description: Sync privileges for test-app
      policies:
        - p, proj:my-proj:ci-role, applications, sync, my-proj/test-app, allow
      jwtTokens:
        - name: ci-token # references the token by name
```

**Comment by alexmt** [comment]
I think this is a great idea. I've just sent a PR that introduces service accounts/users with tokens: https://github.com/argoproj/argo-cd/pull/3215/files

Instead of using issuedAt user tokens are using auto-generated ID. I think user should be able to specify unique token name for both service account token as well as project token. 

@jessesuen do you have any objections?

**Comment by jannfis** [comment]
I also like this idea. Maybe we could even support wildcards for matching token names, and have kind of a revocation list too.

**Comment by chancez** [comment]
> I think this is a great idea. I've just sent a PR that introduces service accounts/users with tokens: https://github.com/argoproj/argo-cd/pull/3215/files
> 
> Instead of using issuedAt user tokens are using auto-generated ID. I think user should be able to specify unique token name for both service account token as well as project token.
> 
> @jessesuen do you have any objections?

Would these UUIDS be the names your thinking of, or would names be in addition to the UUID?

**Comment by chancez** [comment]
Oh I see, you added accounts, so we would reference the account by name in a role, and any of the tokens it's issued would be valid or?

**Comment by alexmt** [comment]
@chancez  sorry, missed your comment on the issue.

Right, now both accounts and projects might have tokens. I agree with your proposal. User should be able to specify name manually and if name is not specified then some unique name should be generated ( accounts use uuid and projects use issuedAt )

**Comment by alexmt** [comment]
@rachelwang20 , this might be good next ticket

**Comment by sdputurn** [comment]
can someone please give some example of AppProject definition? 
how do i get the token for this id/name? seems create-token sub command still has no option with named token.

for example - i have a project definition
```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: analytics
  namespace: argocd
spec:
  description: Use this project for all analytics apps
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  roles:
  - description: analytics role decription
    name: analytics-role
    policies:
    - p, proj:analytics:analytics-role, applications, *, analytics/test-app, allow
    jwtTokens:
    - name: abcd12
       iat: 1591729523 
  sourceRepos:
  - '*'
```
now how can i generate a jwt for abcd12?
