### ISSUE TITLE
Unexpected (and Constant) Application Updates

### ISSUE THREAD

**Issue by DaytonG** [argoproj/argo-cd#3262]
Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**

When using helm, found that our Application object's "generation" field was constantly updating. After some help, we discovered it was because of a few empty fields: `source.path` (was set to empty string), `source.helm.parameters` (empty list), and `source.helm.valuesFiles` (empty list). I removed all three fields from our Application objects, and things stopped refreshing.

Some other things to note:
- sync policy is set to automated
- we are using the app-of-apps pattern. The issue was present in the sub-apps. Didn't notice it in the parent app objects.
- the UI showed no diffs.
- Once I removed the empty fields, I had to manually trigger a sync. Argo did not roll out the change itself.
- the only reason I noticed was because the YAML manifests in the UI would not scroll because the text was constantly changing. There was no other indication a problem was occurring.

**To Reproduce**

Deploy an Application like so, using app-of-apps:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: opining-molly-redis
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - jsonPointers:
    - "/spec/clusterIP"
    kind: Service
  project: default
  source:
    chart: redis
    helm:
      releaseName: opining-molly
      valuesFiles: []
      parameters: []
      path: '' 
      values: |-
        "master":
          "persistence":
            "enabled": false
        "metrics":
          "enabled": true
        "password": "redacted"
        "rbac":
          "create": true
        "sentinel":
          "enabled": false
        "serviceAccount":
          "create": true
        "slave":
          "persistence":
            "enabled": false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.4.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

```

**Expected behavior**

Application allows for empty fields to be present without causing behind-the-scenes refreshes. 

**Version**

```shell
# Took this from within the container, as we haven't hooked up the client from outside kubernetes yet
argocd@mothy-horse-argocd-repo-server-7bf9d9f6dc-m52td:~$ argocd version --client
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64

```

**Logs**

From the application-controller pod:
```
time="2020-03-20T19:35:43Z" level=info msg="Update successful" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:43Z" level=info msg="Reconciliation completed" application=zany-antelope-dds-tls-secret dest-namespace=argocd dest-server="https://kubernetes.default.svc" fields.level=2 time_ms=807.498233
time="2020-03-20T19:35:43Z" level=info msg="Refreshing app status (spec.source differs), level (2)" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:43Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:43Z" level=info msg="Skipping auto-sync: application status is Synced" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:44Z" level=info msg="Update successful" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:44Z" level=info msg="Reconciliation completed" application=zany-antelope-dds-tls-secret dest-namespace=argocd dest-server="https://kubernetes.default.svc" fields.level=2 time_ms=802.009486
time="2020-03-20T19:35:44Z" level=info msg="Refreshing app status (spec.source differs), level (2)" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:44Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:44Z" level=info msg="Skipping auto-sync: application status is Synced" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:45Z" level=info msg="Update successful" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:45Z" level=info msg="Reconciliation completed" application=zany-antelope-dds-tls-secret dest-namespace=argocd dest-server="https://kubernetes.default.svc" fields.level=2 time_ms=801.774317
time="2020-03-20T19:35:46Z" level=info msg="Refreshing app status (spec.source differs), level (2)" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:46Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=zany-antelope-dds-tls-secret
time="2020-03-20T19:35:46Z" level=info msg="Skipping auto-sync: application status is Synced" application=zany-antelope-dds-tls-secret
```
