### ISSUE TITLE
308 infinite redirect

### ISSUE THREAD

**Issue by kotyara85** [argoproj/argo-cd#3274]
**Describe the bug**
argocd is in infinite 308 recdirect

**To Reproduce**
AWS setup - 
ELB (ssl) -> service port 80 argo-server -> loop redirect

```
spec:
  rules:
  - host: argocd
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 80
        path: /
  tls:
  - hosts:
    - argocd
```

Is there a way to disable redirect on argo side?

```
$ curl https://argocd
<a href="https://argocd/">Temporary Redirect</a>.
```

Thanks
