### ISSUE TITLE
Application destination without specifying namespace

### ISSUE THREAD

**Issue by neilharris123** [argoproj/argo-cd#3285]
Let me briefly describe what I'm doing. 

I am using argocd to create several namespaces on a cluster managed by argocd. I have an app called namespaces-app which these namespacess resources belong to. The only purpose of this argocd app is to create these namespaces, and nothing more. 

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-namespaces
  labels:
    project: k8s
    role: namespaces
spec:
  project: k8s
  source:
    repoURL: 'git@github.com:/k8s-base.git'
    path: 'namespaces/overlays/prod'
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: prod-k8s-namespaces
```

As the point of this application is to create namespaces, none of the resources it creates end up in the namespace of the App destination (prod-k8s-namespaces). So on the cluster where the namespaces are created, there are zero resources in namespaces prod-k8s-namespaces. 

However, I still need to create this namespace manually on the cluster in order for the argocd Application to be created. 

Is there anyway around doing this?
