### ISSUE TITLE
Cannot sync same resource to multiple clusters

### ISSUE THREAD

**Issue by MohamedTalhaoui** [argoproj/argo-cd#3328]
**Describe the bug**
I have on cluster per stage (devl, test, prod) and have a set of common resources I need to deploy to all the clusters (eg: nginx controller, psp, storage classes, clusterroles, ...)
I have one helm template containing my common resources and one argocd application per cluster.
This work but I hit a SharedResourceWarning during synchronisation.
This is because argocd uses (Kind,Name,Namespace) as a resource key regardless of the destination cluster.
So, if I have a psp resource called "privileged" and want argocd to deploy it in many clusters, that won't work.

**To Reproduce**
- Create a simple cluster level resource (psp, clusterrole, ...) with name "my-resource"
- Create at least 2 argocd applications to deploy the resource in at least 2 destination clusters

**Expected behavior**
I expect argocd be able to deploy the same resources in different clusters.
Maybe the destination cluster can be added to the key used by argocd to identify resources.

**Workaround**
A workaround would be to name the resource differently for each cluster, for example including the cluster name in the resource name.
This is not very nice solution and makes multi-clusters management more complex.

**Screenshots**
![Screen Shot 2020-04-01 at 14 06 36](https://user-images.githubusercontent.com/26436887/78135475-4004fc00-7422-11ea-9d53-788212a332bb.png)

![Screen Shot 2020-04-01 at 14 06 51](https://user-images.githubusercontent.com/26436887/78135510-4bf0be00-7422-11ea-8603-6216a7deda75.png)

**Version**
```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by alexmt** [comment]
Hello @MohamedTalhaoui ,

Argo CD does not use resource key to check if it belongs to another application. Every resource deployed by Argo CD has label `app.kubernetes.io/instance=<appName>`. The `SharedResourceWarning` is set if Argo CD detects that resource has `app.kubernetes.io/instance` with the name of another application. Can you please double-check that you are not trying to deploy application with another name into the same cluster/namespace?

**Comment by MohamedTalhaoui** [comment]
Hi @alexmt ,
thanks for your answer and you are completely right.
I was having a duplicate application name and it is now fixed.
Thing is that I have same set of applications to deploy in multiple clusters with ArgoCD and then I have to create one application for each destination cluster with a different name (like prefixing the cluster name) to make it work.
Is that the recommended way to deal with multiple clusters or do you have some best practices or lessons learned to share ?

**Comment by alexmt** [comment]
I don't think we have better approach than separate application per cluster. This is not perfect and we are planning to have the better answer in 1.7. Please follow https://github.com/argoproj/argo-cd/issues/3403 . It should get more updates soon

**Comment by cheddarwhizzy** [comment]
This issue still persists with Kustomize configuration in ArgoCD v2.0.1+33eaf11. The Application names are both different and being deployed to different clusters (same namespace name). This is not an issue with Helm charts. Using namePrefix isn't an option

`development`
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: <redacted>
  project: development
  source:
    path: development/default
    repoURL: <redacted>
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

`test/staging`
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: <redacted>
  project: test
  source:
    path: test/default
    repoURL: <redacted>
    targetRevision: HEAD
  syncPolicy:
    automated: {}
      # prune: true
      # selfHeal: true
```
