### ISSUE TITLE
ArgoCD v1.5.0 Ignores kustomize field when creating application programmatically 

### ISSUE THREAD

**Issue by jdfalk** [argoproj/argo-cd#3355]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating an application via kubectl apply, ArgoCD ignores the kustomize field. We created a bootstrap app to contain our other apps. In our bootstrap app we set the `spec.kustomize.nameSuffix` field. When you do a `kubectl get application/booostrap-apps-test` it shows the field is set, but when you look in the web ui, and the applications that get created ignore the field.

**To Reproduce**

1. Create app of apps that contains kustomize field with namePrefix/nameSuffix programmatically using `kubectl apply -f ` 
2. ArgoCD ignores field.

**Expected behavior**

ArgoCD adds the prefix/suffix. If you set the parameter through the UI then it respects it. 

**Screenshots**

![Screen Shot 2020-04-03 at 3 36 45 PM](https://user-images.githubusercontent.com/1310106/78398461-1e8e4680-75c1-11ea-8afa-e9387ab2f231.png)

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.0+bdda410
  BuildDate: 2020-04-02T16:38:24Z
  GitCommit: bdda41046378a855e289b5f1602d5c923a3f914a
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Manifests**

***Manifest as generated by kustomize***

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-apps-test
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  kustomize:
    nameSuffix: -test
  project: default
  source:
    path: application-home
    repoURL: REDACTED
    targetRevision: HEAD
```

***Manifest as Applied in the Cluster***

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-apps-test
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  kustomize:
    nameSuffix: -test
  project: default
  source:
    path: application-home
    repoURL: REDACTED
    targetRevision: HEAD
status:
  health:
    status: Missing
  observedAt: "2020-04-03T19:27:51Z"
  reconciledAt: "2020-04-03T19:27:51Z"
  resources:
  - group: argoproj.io
    health:
      status: Missing
    kind: Application
    name: apps-aws-cluster-autoscaler
    namespace: argocd
    status: OutOfSync
    version: v1alpha1
  sourceType: Kustomize
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: application-home
        repoURL: REDACTED
        targetRevision: HEAD
    revision: REDACTED
    status: OutOfSync
```
