### ISSUE TITLE
Support User Impersonation

### ISSUE THREAD

**Issue by zoetrope** [argoproj/argo-cd#3376]
# Summary

Application-controller impersonates a user when synchronizing applications.

By impersonating a user, we can restrict resource operations using Kubernetes RBAC.
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation

# Motivation

ArgoCD already has a feature to restrict resource operations such as ClusterResourceWhitelist, NamespacedResourceBlacklist.
However, most of Kubernetes users already have Kubernetes RBAC configurations.
Therefore, we need to manage similar information doubly.

With support for user impersonation, a restriction will be based on a single source of truth.

# Proposal

Add the following fields `impersonateUser`  and `impersonateGroups`  to AppProject resource.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: impersonation-sample
spec:
  impersonateUser: "system:serviceaccount:myns:mysa"
  impersonateGroups:
  - "system:authenticated"
```
Application-controller impersonates user and group using the above settings to deploy applications.

See PR in detail.
