### ISSUE TITLE
Proposal & Proof of Concept: Dynamically Generate Applications for Clusters Based On Label Selectors

### ISSUE THREAD

**Issue by dgoodwin** [argoproj/argo-cd#3403]
# Summary

Add a new CRD ApplicationGenerator to support dynamically generating Applications for Clusters via a label selector.

# Motivation

Argo models Applications via a 1-1 relationship with a Cluster. This works great in environments where the number of clusters is fixed and known.

In many use cases however clusters are increasingly being treated as cattle, they come and go often, likely via programmatic APIs. This scenario can be found in organizations providing developers short lived clusters, distributing clusters to different regions or projects, and CI systems.

In cases such as this, it is still equally important to deliver consistent configuration to clusters and leverage gitops, if not more so, to keep the fleet in it's expected state.

When working with dynamic clusters, it is reasonable to expect that an integrating application or API would register those clusters with ArgoCD. (by creating an appropriate secret) It is however less reasonable to also generate the expected Applications, and keep them in sync. This solution below allows the ApplicationGenerator to itself be stored in git and configured via Argo. Clusters can come and go, and just need to be labelled appropriately to pickup the desired configuration.

# Proposal

I have written up a small proof of concept operator for an ApplicationGenerator CRD and controller in this repository: https://github.com/dgoodwin/argocd-appgenerator

The CRD itself as proposed (happy to discuss changes if this idea is popular):

```yaml
apiVersion: appgenerator.rm-rf.ca/v1
kind: ApplicationGenerator
metadata:
  name: default-configmap
  namespace: argocd
spec:
  matchLabels:
    argocd.argoproj.io/secret-type: cluster
  applicationSpec:
    destination:
      namespace: default
      # server will be overwritten for every cluster that matches this generator.
      server: https://kubernetes.default.svc
    project: default
    source:
      path: config/samples/argocd-application
      repoURL: https://github.com/dgoodwin/argocd-appgenerator.git
    syncPolicy:
      automated:
        prune: true
```

Any Cluster which matches the given label gets an Application generated for it with the given spec. If the label or ApplicationGenerator were to be removed, the Application is cleaned up.

There is however another change that would be required, it looks like today there is no way to specify labels to attach to a Cluster, the CLI would likely need to be expanded to allow for this, perhaps something like:

```
$ argocd cluster add kind-kind --insecure --in-cluster -l foo=bar -l x=y
```

Request is somewhat related to #1673 but rather than making Application multi-destination, this solution layers on top and leaves the core Application mechanics alone.

This solution can easily be provided by a separate operator, but having worked on an API for provisioning/deprovisioning clusters dynamically for several years, it feels like a great fit for the core of Argo itself, so I first wanted to propose for inclusion there.
