### ISSUE TITLE
Inconsistent resource overrides key parsing

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#3406]
**Describe the bug**

Resource custom actions/health assessment and resource diffing differently handle kinds from noname group (e.g. ConfigMap) . The actions and health assessment expect only Kind in this case but custom diffing expects `/<Kind>`. As a result it is impossible to configure resource action/health and custom diffing for same resource group/kind.

**To Reproduce**

Following customization introduce only custom health check:

```yaml
  resource.customizations: |
    ConfigMap:
      ignoreDifferences: |
        jsonPointers:
        - /data
      health.lua: |
        return { status = "Progressing" }
```

Following customization introduce only custom diffing:

```yaml
  resource.customizations: |
    /ConfigMap:
      ignoreDifferences: |
        jsonPointers:
        - /data
      health.lua: |
        return { status = "Progressing" }
```

**Expected behavior**

We probably have some users who use `<kind>` and some who use `/<kind>`. So at this point I think we should support both. User should be able to use `<kind>` or `/<kind>` or even both simultaneously.

**Version**

```shell
v1.5.1
```

**Logs**

```
Paste any relevant application logs here.
```
