### ISSUE TITLE
Add more detailed parameters to resource.exclusions

### ISSUE THREAD

**Issue by h3poteto** [argoproj/argo-cd#3415]
# Summary

Add `name`, `annotations` or `labels` parameter to `resource.exclusions` argument.

# Motivation
I want to exclude some `Job` resources, so I tried to set `resource.exclusions`:

```yaml
apiVersion: v1
data:
  resource.exclusions: |
    - apiGroups:
      - "batch"
      kinds:
      - "Job"
      clusters:
      - "*"
kind: ConfigMap
```
But this parameter can only specify `apiGroup`, `kinds` and `clusters`, so it ignores all Job resources. I don't ignore all Job resources, I want to exclude only specific Jobs.

Next, I tried to specify `argocd.argoproj.io/hook: Skip` to the Jobs. This is the desired behavior, but the application status is `missing` and `OutOfSync`. 

# Proposal

Add `name`, `annotations` or `labels` to `FilteredResource`, and implement match functions.
https://github.com/argoproj/argo-cd/blob/476b09cbbf/util/settings/filtered_resource.go
