### ISSUE TITLE
Application dependency

### ISSUE THREAD

**Issue by ruzickap** [argoproj/argo-cd#3454]
# Summary

I have a helm chart which contains multiple application definitions like it's described here: https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/

```text
├── Chart.yaml
├── templates
│   ├── app1_with_crds.yaml
│   └── app2_requires_crds_from_app1.yaml
└── values.yaml
```

When I install such helm chart the ArgoCD will immediately start creating child applications (`app1`, `app2`) in paralel.

There is no definition of priority which will ensure, that `app1` will be installed before `app2` (which depends on CRDs created by `app1`) - race condition.

-> This situation may break the deployment process.

# Motivation

There should be a way how to solve dependencies between applications.

# Proposal

Maybe something like this may solve this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  depends_on:    # Optional parameter
    - app1
```

-> The `app2` will be installed only after successful installation of `app1`
-> The `app1` can not be deleted before `app2`

**Comment by sfynx** [comment]
I have a similar issue where I get a "Sync failed" because one app tries to create something in a namespace that another app is supposed to create. For me it would already be fine if we have some way of retry syncing for a certain period/interval, because that would complete everything eventually. However it looks like a sync error is an instant error which is not waited for /retried by the CLI.

**Comment by sfynx** [comment]
This use case is actually supported: https://argoproj.github.io/argo-cd/user-guide/sync-waves/
Annotate the applications that need to go first with lower wave number, and the other apps will only start syncing after the lower ones are done.

I just tested it with an app that defines a namespace that needs to exist before another app may create things in it, and the second only appears after the first has become healthy.

**Comment by ruzickap** [comment]
Thanks for pointing me the right way...

Closing...

**Comment by vikas027** [comment]
> This use case is actually supported: https://argoproj.github.io/argo-cd/user-guide/sync-waves/
> Annotate the applications that need to go first with lower wave number, and the other apps will only start syncing after the lower ones are done.
> 
> I just tested it with an app that defines a namespace that needs to exist before another app may create things in it, and the second only appears after the first has become healthy.

Hello @sfynx ,
It works fine on a resource but the wave annotation `argocd.argoproj.io/sync-wave: '-1'` has no effect on the argo application.

Is there a way to make an application dependent on the other?

**Comment by IbraheemAlSaady** [comment]
Why is this issue closed?
 
I've tested this with the following and it didn't work

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    helm:
      releaseName: cert-manager
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.5.3
    chart: cert-manager
  destination:
    name: 'in-cluster'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    helm:
      releaseName: redis
      parameters:
        - name: architecture
          value: standalone
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "15.3.2"
    chart: redis
  destination:
    name: 'in-cluster'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Shouldn't `Redis` app run after the `cert-manager` app is in a healthy state?

I also enabled the health assesment mentioned [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessement-of-argoprojioapplication-crd-has-been-removed)


*Versions:*

```
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
argo    default         2               2021-09-09 16:03:48.239841 +0300 EEST   deployed        argo-cd-3.17.6  2.1.2      
```
