### ISSUE TITLE
Add support for arbitrary links in app dashboard

### ISSUE THREAD

**Issue by carsonoid** [argoproj/argo-cd#3487]
# Summary

Add the ability to enrich the dashboard with extra links. Links to things like monitoring pages or documentation instead of just ingress hosts or other apps.

# Motivation

I love the way that I can jump between apps or directly to an ingress host from the app dashboard.  In fact, I love it so much that I wish I could put more, arbitrary links to things in that dashboard so that it can be a single view for all the relevant details for an app. 

# Proposal

Argo-CD could support a per-resource annotation that would cause the app dashboard to generate clickable links to outside pages on that resource.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-svc
  annotations:
    argocd.argoproj.io/external-link: http://my-grafana.com/pre-generated-link
```

Then, whenever any resource as that annotation, it generates an additional link button to the given url on that resource.

There could also be a sort of **"Phase 2"** implementation of this concept with a new CRD. Maybe somthing like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDInterfaceTile
metadata:
  name: my-svc-dashboard
spec:
  link:
    text: Grafana Dashboard
    url: http://my-grafana.com/pre-generated-link
    color: light-red
    text-color: black
    # image would be optional
    image:
      source:
        # emojiName is mutually exclusive with url. You should be able to give it a text
        # name for an emoji and the dashboard will attempt to render it, but render nothing if it doesn't
        # match a known emoji name
        emojiName: heavy_exclamation_mark

        # url is mutually exclusive with emojiName. It is the full url
        # to the the image source and will be hot-linked
        # url: http://my-image-source.com/images/dashboard.png
```

Putting that into an app would cause an extra tile to show up with the given information. This might be overkill, but I really think that Argo-CD's interface is one of it's best features so it would be awesome to be able to do just a bit more with it.

Since the resource is defined as a CRD, end-users would still have all the normal mechanisms for resource generation (helm, kustomize, etc).
