### ISSUE TITLE
how can create namespace

### ISSUE THREAD

**Issue by w-huaqiang** [argoproj/argo-cd#3490]
I have to set namespace when I create APP. how can I create namespace resource use argo cd

**Comment by alexmt** [comment]
Hello @w-huaqiang ,

You can add namespace resource definition into git repo along with your application resources. We are considering adding namespace auto-creation feature: https://github.com/argoproj/argo-cd/issues/3502#issuecomment-620820658

**Comment by w-huaqiang** [comment]
@alexmt ok, thinks

**Comment by miletskyi** [comment]
The one should use
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'create-target-namespace'
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```
Or Tick the Box 'AUTO-CREATE NAMESPACE' under 'SYNC OPTIONS'
