### ISSUE TITLE
Declarative helm repositories with missing secret causes all repositories in ArgoCD to lock

### ISSUE THREAD

**Issue by Cyanopus** [argoproj/argo-cd#3492]
**Describe the bug**

When adding a private helm reposistory in argocd-cm using declarative git way like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: management
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # v1.3 or later use `repositories` with `type: helm`
  repositories: |
    - type: git
      url: https://example1
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: example1
    - type: helm
      url: https://example2
      name: example2
      usernameSecret:
        name: example2
        key: username
      passwordSecret:
        name: example2
        key: password
```
Secret example 2 is missing in the cluster. This leads to ArgoCD totally block the rest of the configured repositories( in this case examples) and not able to load them. Its giving exception for missing secret and from this point no other correctly configured repository can be synced so apps stay in Unknown state immediately after this happens.

**To Reproduce**

Take the definition in the Description and modify it to have one private helm repo and one public plain. Configure non-existing secret parameters. Sync ArgoCD and check the result. It was tested with 1.4.2 and 1.5.2

**Expected behavior**

When a secret is not correctly setup, Argo should not bother for the rest of the correct setup repositories. It should continue to function as expected.

**Screenshots**

**Version**

1.4.2 , 1.5.2
