### ISSUE TITLE
can't create resource of helm hook

### ISSUE THREAD

**Issue by w-huaqiang** [argoproj/argo-cd#3504]
1. check app is :
```
[root@node1 ~]# argocd app get gitlab
Name:               gitlab
Project:            default
Server:             https://kubernetes.default.svc
Namespace:          gitlab
URL:                https://10.233.52.204/applications/gitlab
Repo:               git@github.com:w-huaqiang/kubedui.git
Target:             HEAD
Path:               gitlab
Helm Values:        hq-values.yaml
SyncWindow:         Sync Allowed
Sync Policy:        <none>
Sync Status:        OutOfSync from HEAD (003f8fc)
Health Status:      Missing

GROUP                      KIND                     NAMESPACE  NAME                                     STATUS     HEALTH   HOOK     MESSAGE
                           ServiceAccount           gitlab     gitlab-shared-secrets                    Succeeded           PreSync  gitlab-shared-secrets created
rbac.authorization.k8s.io  Role                     gitlab     gitlab-shared-secrets                    Succeeded           PreSync  gitlab-shared-secrets created
rbac.authorization.k8s.io  RoleBinding              gitlab     gitlab-shared-secrets                    Succeeded           PreSync  gitlab-shared-secrets created
                           ConfigMap                gitlab     gitlab-shared-secrets                    Succeeded           PreSync  gitlab-shared-secrets created
batch                      Job                      gitlab     gitlab-shared-secrets.0-yn7              Running             PreSync  job.batch/gitlab-shared-secrets.0-yn7 created
batch                      Job                      gitlab     gitlab-shared-secrets.0-hg5-selfsign     Running             PreSync  job.batch/gitlab-shared-secrets.0-hg5-se
```

2. the status is succeded,but can't found the resource of k8s:
```
[root@node1 ~]# kubectl get ServiceAccount -n gitlab
NAME      SECRETS   AGE
default   1         12h
```
3. the presync yaml is:
```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shared-secrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
{{- if and .Values.enabled (not .Values.global.operator.enabled) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
{{- end }}

```

4. I add ` "argoproj.io/hook-weight": "-5"` to this resource,but is the same error.

5. I run `helm template` output this resource is:
```
# Source: gitlab/charts/shared-secrets/templates/rbac-config.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-shared-secrets
  namespace: default
  labels:
    app: shared-secrets
    chart: shared-secrets-0.1.0
    release: RELEASE-NAME
    heritage: Helm
    
  annotations:
    "argoproj.io/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation

```
