### ISSUE TITLE
Please display in UI when sync is blocked by earlier SyncWave

### ISSUE THREAD

**Issue by AceHack** [argoproj/argo-cd#3516]
# Summary

Right now if I do a check-in in that affects two different syncwaves and it takes say 5 minutes for the first syncwave to finish it is very hard to know without a lot of knowledge about the different syncwaves that the later syncwave is actually blocked waiting on the first syncwave to complete.  It would be nice in the UI if it would show for the later 2nd syncwave that it's not actually syncing, it's waiting for 1st earlier sync wave to finish.

# Motivation
Below are our syncwaves, so given this huge list it's very difficult to understand that say an update to our search.services.api deployment could be blocked by knative.kafka.zookeeper deployment if it's unhealthy.  We would just like to see something in the UI that can help in this type of troubleshooting.
```
  syncWaves:
    clusterBootstrap:
      namespaces:
        platformTopology: 0
        playgroundTopology: 0
      priorityClasses: 0
      storageClasses: 0
      sealedSecretsController: 10
      sealedSecrets: 20
      spotTerminationHandler: 10
    istio:
      controlPlane: 1000
      kiali: 1010
    infra:
      jaeger: 2000
      prometheus:
        operator: 2000
        alertRules: 2010
        grafanaDashboard: 2010
        thanos: 2010
      certManager: 2000
      argoCd: 2100
    operators:
      spark: 3000
      zookeeper: 3000
    knative:
      operator: 3000
      serving: 4000
      eventing: 4000
      source:
        config: 3000
        sqs: 4000
      kafka:
        zookeeper: 4000
    search:
      core:
        zookeeper: 5000
        solr: 5010
      services:
        api: 6000
    content:
      cassandra: 7000
      spark: 7000
```
