### ISSUE TITLE
Please allow for defining dependency DAG (Directed Acyclic Graph)

### ISSUE THREAD

**Issue by AceHack** [argoproj/argo-cd#3517]
# Summary

When defining Application please allow a new field that is very similar to SyncWaves but allows for more fine-grained control of dependencies, thus allowing more parallelism.  For any Application, I should be able to define a DependsOn array that lists other applications that must be synced and correct before I am allowed to sync.  This is very similar to SyncWaves but would allow for a much finer-grained parallelism.

# Motivation

Below is our SyncWaves and they are very complex and we are unable to parallels everything to it's the fullest extent because of inherent limitation in the sync wave design.  We would like to be able to completely express our fine-grained dependencies in a DAG so maximum parallelism can be reached.
```
  syncWaves:
    clusterBootstrap:
      namespaces:
        platformTopology: 0
        playgroundTopology: 0
      priorityClasses: 0
      storageClasses: 0
      sealedSecretsController: 10
      sealedSecrets: 20
      spotTerminationHandler: 10
    istio:
      controlPlane: 1000
      kiali: 1010
    infra:
      jaeger: 2000
      prometheus:
        operator: 2000
        alertRules: 2010
        grafanaDashboard: 2010
        thanos: 2010
      certManager: 2000
      argoCd: 2100
    operators:
      spark: 3000
      zookeeper: 3000
    knative:
      operator: 3000
      serving: 4000
      eventing: 4000
      source:
        config: 3000
        sqs: 4000
      kafka:
        zookeeper: 4000
    search:
      core:
        zookeeper: 5000
        solr: 5010
      services:
        api: 6000
    content:
      cassandra: 7000
      spark: 7000
```

# Proposal

Please add a DependsOn array to the application so it can list out what other applications it depends on.
