### ISSUE TITLE
Issue with decorative setup and SSH auth

### ISSUE THREAD

**Issue by Kampe** [argoproj/argo-cd#3568]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When attempting to use declarative setup with Argo after any changes from 1.5 on we're running into many issues with attempting to use our private git repo. We do see via the UI when you mouse over the "X" on why repo sync failed: 

```
Unable to connect to repository: parse "git@github.com:org/manifests_repo": first path segment in URL cannot contain colon
```

The docs clearly show using the git ssh URI as valid:
https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/

Here's my configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:org/manifest_repo
      sshPrivateKeySecret:
        name: ssh-deploy-keys
        key: key.pem
```

Rolling back to 1.4.3 allows for argo to sync properly.  What's changed here about the setup of SSH Private keys repo keys?

**To Reproduce**

Setup argo with declarative setup and attempt to give it a private git repo with SSH key credentials to authenticate with.

**Expected behavior**

Should deploy the Argo configured application as expected without regression. 

**Version**
1.5.x and onward

**Comment by jannfis** [comment]
Hi @Kampe, can you please try to set `type: git` property explicitly for the repository configuration, i.e.

```
  repositories: |
    - url: git@github.com:org/manifests_repo
      sshPrivateKeySecret:
        name: ssh-deploy-keys
        key: key.pem
      type: git
```

**Comment by jannfis** [comment]
I could reproduce the issue, and also validated that explicitly setting `type` should be the workaround. 

However, I think we should assume `git` as the default repository type when testing for repository access, as to support legacy configurations.

**Comment by jannfis** [comment]
After some more research, I came to another conclusion. I have tested the following configuration with v1.5.3:

```
    - url: git@github.com:jannfis/argocd-example-apps
      sshPrivateKeySecret:
        name: ssh-deploy-keys
        key: key.pem
```

and it works out of the box - as long as the connection to the repository is successful, i.e. the referenced secret exists and contains a key which can be used to connect the repository.

If either the secret does not exist, or the key is not good, the error message can be observed when the type of the repository is not explicitly set. This is because of a check in https://github.com/argoproj/argo-cd/blob/e42102a67e1d82c33351f95d3a758784f1e1c7ef/util/argo/argo.go#L136 - when the type of the repo is not explicitly set, it checks both, `git` and `helm` repos. The git check returns an error, therefore, the helm check is executed and that does not accept an scp-style URL.

This could be considered a bug, but I am lowering severity and priority.
