### ISSUE TITLE
Only show manifests rendered from the given helm templates

### ISSUE THREAD

**Issue by h0tbird** [argoproj/argo-cd#3606]
# Summary

When using `helm template` as a source, I would like to specify:
```
-s, --show-only stringArray        only show manifests rendered from the given templates
```

# Motivation

This is useful when we are interested in a subset of the chart templates.

# Proposal

```yaml
spec:
    source:
      helm:
        templates:
        - templates/deployment.yaml
        - templates/service.yaml
```
