### ISSUE TITLE
getting error when enabling okta integration 

### ISSUE THREAD

**Issue by renperez** [argoproj/argo-cd#3628]
i'm getting this error when i edit argocd-cm configmap to add dex.config. 
error: error: error validating "deployment.yaml": error validating data: ValidationError(ConfigMap.data.connectors): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by renperez** [comment]
`apiVersion: v1
data:
  dex.config: |
    logger:
      level: debug
      format: json
  connectors:
  - type: saml
    id: okta
    name: Okta
    config:
      ssoURL: https://oktaurl/sso/saml
      caData: |
        -----BEGIN CERTIFICATE-----
        my cert
        -----END CERTIFICATE-----
      redirectURI: https://myargocdurl/api/dex/callback
      usernameAttr: email
      emailAttr: email
      groupsAttr: group
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm`

**Comment by alexmt** [comment]
Hello @renperez ,

Looks like it is an incorrect indentation in config map manifest. Try changing config map as following:

```yaml
data:
  dex.config: |
    logger:
      level: debug
      format: json
    connectors: # indentation changed here
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: https://oktaurl/sso/saml
        caData: |
          -----BEGIN CERTIFICATE-----
          my cert
          -----END CERTIFICATE-----
        redirectURI: https://myargocdurl/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: group
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
```
