### ISSUE TITLE
Cert-manager resources are out of sync

### ISSUE THREAD

**Issue by bappr** [argoproj/argo-cd#3658]
**Describe the bug**

I am using cert-manager v0.15.0 and I have `Issuer` and `Certificate` resources in my Helm chart that are managed by argocd. The resources have been correctly applied by argocd and they are ready. However, argocd mark them as `Out Of Sync`

Notes: Out of topic - I noticed cert-manager labels all its deployment and CRDs with `app.kubernetes.io/instance`. Meaning it's conflicting with argocd. Had to comment them on the crds resources to be able to create an argocd app for crds.

**To Reproduce**

Those resources are out of sync.

```
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: kintohub-issuer
  namespace: kintohub
spec:
  acme:
    email: devaccounts@kintohub.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: kintohub-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: devaccounts@kintohub.com
          apiTokenSecretRef:
            name: cert-manager-cloudflare-secret
            key: api-token
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kintohub-wildcard-cert
  namespace: kintohub
spec:
  secretName: kintohub-wildcard-cert
  issuerRef:
    name: kintohub-issuer
    kind: Issuer
  dnsNames: {{ .Values.certManager.kintohubWildcardHost | toJson }}
```

**Expected behavior**

All resources should be sync and green.

**Screenshots**

<img width="777" alt="Screen Shot 2020-05-27 at 12 10 25 PM" src="https://user-images.githubusercontent.com/8669741/82976968-0fe96c00-a013-11ea-8da0-d34aed53756a.png">

**Version**

```shell
argocd: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:22:34Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.3+095c5d6
  BuildDate: 2020-05-02T04:21:47Z
  GitCommit: 095c5d616b1cb39f87e8f7a54cabea2643e1c99a
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```
