### ISSUE TITLE
cannot remove last application from a directory

### ISSUE THREAD

**Issue by test-account-0** [argoproj/argo-cd#3686]
**Describe the bug**

It's not posible to remove last application from directory with applications.

**To Reproduce**

Create application that points to directory with at least 2 argoproj applications in yaml format.
Like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testngx1
  namespace: ops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: some-url-to-repo
    targetRevision: HEAD
    path: testngx1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: testngx1
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
```
Delete one of them - it should be deleted from the cluster with all the objects inside.
Delete the second one - You'll see the error:
```
rpc error: code = Unknown desc = applications: app path does not exist
```
You can add to the repo this or the first one and the deleted one will be deleted.

**Expected behavior**

Last application is being deleted.

**Version**

It's docker image - `argoproj/argocd:v1.5.5`

**Logs**

```
argocd-repo-server-67bb7fb56-2wmq5 repo-server time="2020-06-01T14:36:27Z" level=error msg="finished unary call with code Unknown" error="applications: app path does not exist" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2020-06-01T14:37:26Z" grpc.service=repository.RepoServerService grpc.start_time="2020-06-01T14:36:26Z" grpc.time_ms=1616.006 span.kind=server system=grpc
```
