### ISSUE TITLE
Support for jsonnet-bundler & jsonnet flags (like `-J` to include library paths)

### ISSUE THREAD

**Issue by wmcnamee-tunein** [argoproj/argo-cd#3688]
# Summary

This is a request to support jsonnet-bundler and jsonnet flags like `-J` which adds libraries to the "paths" for where `import` looks for files.

# Motivation

My jsonnet files have external library dependencies that I don't want to check into my git repo. I use `jsonnet-bundler` in order to pull down those dependencies locally before calling jsonnet with`-J vendor` to automatically look for relevant libraries within the vendor directory.

In order to use ArgoCD I would need the same functionality.

# Proposal

In an abstract way, it might be nice to support some sort of custom "post-clone"/"pre-sync" job/command.

Such that it might look like:

```
git clone...
<something here to generate files>
sync...
```

**Comment by gaurav517** [comment]
Did you find a workaround for this @wmcnamee-tunein ? We have a similar issue where our base jsonnet libraries are in different repo (shared by many other repos).
One idea is to keep all app manifest files in one repo only.. but we don't prefer that.

Also I got confused by `prefixed by repoRoot` in `--jsonnet-libs stringArray           Additional jsonnet libs (prefixed by repoRoot)`. Which `repoRoot`? library-repo-root? or app-repo-root?
Thanks.

**Comment by kgaurav2** [comment]
we changed our strategy and we are going to keep all app manifest files in same repo as library.

**Comment by jessebye** [comment]
@wmcnamee-tunein @gaurav517 I have this working using a [plugin](https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/). In addition to the plugin I had to add `jb` to a custom docker image for argo. 

In our case, we're using jb and tanka, and got it to work like this:
```
    configManagementPlugins: |
      - name: tanka
        init:
          command: ["/bin/sh", "-c"]
          args: ["jb update"]
        generate:
          command: ["/bin/sh", "-c"]
          args: ['tk show environments/"$ENVIRONMENT" --dangerous-allow-redirect']
```

Then you can create an Argo app like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:<org>/<repo>.git
    targetRevision: dev
    path: test
    plugin:
      name: tanka
      env:
        - name: ENVIRONMENT
          value: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
```

The only issue I'm still trying to solve is how to use a private git repo that has some jsonnet libraries in it. Apparently the `init` step doesn't use the same repositories we have configured for Argo CD. If anyone has insight on that, it would be very helpful!

**Comment by ghostsquad** [comment]
where does `ENVIRONMENT` var get set from?

**Comment by jessebye** [comment]
@ghostsquad it's set in the Argo `Application` (I gave an example in my previous comment):

```
...
spec:
  source:
    plugin:
      name: tanka
      env:
        - name: ENVIRONMENT
          value: default
```

**Comment by ghostsquad** [comment]
@jessebye thanks, ya I totally missed that! :)

**Comment by ghostsquad** [comment]
any idea why `--dangerous-allow-redirect` exists?

**Comment by jessebye** [comment]
@ghostsquad "Redirection of the output of tk show is discouraged and disabled by default. Run tk show --dangerous-allow-redirect to enable." The idea is that tanka users should use its built-in kubernetes context management, and using `tk show` bypasses that. Piping the output (as Argo CD does when it runs a generate) is disabled and you have to pass the `--dangerous-allow-redirect` flag to enable output. This is fine since Argo is handling the kubernetes context anyway.

See also https://github.com/grafana/tanka/issues/3

**Comment by ghostsquad** [comment]
thank you. This makes sense.

**Comment by Geethree** [comment]
> @wmcnamee-tunein @gaurav517 I have this working using a [plugin](https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/). In addition to the plugin I had to add `jb` to a custom docker image for argo.
> 
> In our case, we're using jb and tanka, and got it to work like this:
> 
> Dockerfile:
> 
> ```
> FROM argoproj/argocd:v1.7.6
> 
> USER root
> ADD https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v0.4.0/jb-linux-amd64 /usr/bin/jb
> ADD https://github.com/grafana/tanka/releases/download/v0.12.0/tk-linux-amd64 /usr/bin/tk
> RUN chmod +x /usr/bin/jb /usr/bin/tk
> 
> USER argocd
> ```
> 
> Argo config:
> 
> ```
>     configManagementPlugins: |
>       - name: tanka
>         init:
>           command: ["/bin/sh", "-c"]
>           args: ["jb update"]
>         generate:
>           command: ["/bin/sh", "-c"]
>           args: ['tk show environments/"$ENVIRONMENT" --dangerous-allow-redirect']
> ```
> 
> Then you can create an Argo app like this:
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   name: test
>   namespace: argocd
>   finalizers:
>     - resources-finalizer.argocd.argoproj.io
> spec:
>   project: infrastructure
>   source:
>     repoURL: git@github.com:<org>/<repo>.git
>     targetRevision: dev
>     path: test
>     plugin:
>       name: tanka
>       env:
>         - name: ENVIRONMENT
>           value: default
>   destination:
>     server: https://kubernetes.default.svc
>     namespace: default
> ```
> 
> I also got this working for private git repos by using HTTPS instead of SSH to authenticate and providing a PAT that had permission to reach both the GitOps repo as well as our jsonnet library repo.

FWIW: Since @deleted and I had a simple app without pulling in other jsonnet libraries - i.e. no jsonnet lock file. The jb update was failing with

```
geethree@footop:~/blah/tanka-hello-world$ ../jb update
jb: error: failed to load lockfile: open /home/blah/jsonnetfile.lock.json: no such file or directory
```

So we just return the appropriate exit code in jb update - i.e. 

```
    - name: tanka
      init:
        command: ["/bin/sh", "-c"]
        args: ["jb update || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ['tk show environments/"$ENVIRONMENT" --dangerous-allow-redirect']
```

**Comment by moustafab** [comment]
> Argo config:
> 
> ```
>     configManagementPlugins: |
>       - name: tanka
>         init:
>           command: ["/bin/sh", "-c"]
>           args: ["jb install"]
>         generate:
>           command: ["/bin/sh", "-c"]
>           args: ['tk show environments/"$ENVIRONMENT" --dangerous-allow-redirect']
> ```

FWIW, `jb update` will update your dependencies, so to use the pinned versions from your lock file you should probably use `jb install` when setting up the repo

**Comment by pmorch** [comment]
@jessebye writes:

> I also got this working for private git repos by using HTTPS instead of SSH to authenticate and providing a PAT that had permission to reach both the GitOps repo as well as our jsonnet library repo

One thing with jsonnet-bundler/`jb` that tends to get overlooked is when a dependency inside `jsonnetfile.json` refers to a private git repo. Then a simple `jb update` is not going to suffice.

Is that one of the situations you got working? How?

If PAT is a "personal access token", then one way I've got it working with `bash` is:

```bash
mkdir /tmp/home
set +H # to avoid exclamation point triggering history expansion...
HOME=/tmp/home git config --global credential.helper "!f() { echo \"username=gitlab-ci-token\\npassword=${GITLAB_TOKEN}\"; }; f"
HOME=/tmp/home jb update
rm -rf /tmp/home
```

My vote would be that if jsonnet-bundler should be supported, it needs to support both SSH and HTTPS credentials for dependencies stored as secrets somehow elegantly too.

**Comment by Lukas-solar** [comment]
Does anyone have an idea how to pass `--tla-code` to `tk show` in a meaningful way in this setup?
I was thinking something like this
`jq -r ".[] | \"--tla-code \(.name)='\(.value | tojson)'\"" <<< "$ARGOCD_APP_PARAMETERS" | paste -sd' ' -`

See https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#using-environment-variables-in-your-plugin

But i don't have `jq` installed in my docker image yet.

I think that an official solution such as for jsonnet https://argo-cd.readthedocs.io/en/stable/user-guide/jsonnet/ with corresponding input parameters would be practical here.

**Comment by VannTen** [comment]
@Lukas-solar I'm doing it this way:

```yaml
# plugin.yaml
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: jsonnet-bundler
spec:
  version: v0.1.0
  init:
    command:
      - /usr/bin/jb
      - install
  generate:
    command:
      - /usr/bin/jsonnet
      - --ext-code
      - ARGOCD_APP_PARAMETERS
      - --tla-code-file
      - argocd_params=/params.libsonnet
      - -J
      - vendor
      - --yaml-stream
      - app.jsonnet
  discover:
    fileName: jsonnetfile.lock.json
```

```jsonnet
# params.libsonnet (bundled in the docker image)
{
  [p.name]: std.filter(function(k) k.key != 'name', std.objectKeysValues(p))[0].value
  for p in std.extVar('ARGOCD_APP_PARAMETERS')
}
```

```yaml
kustomization.yaml (Applied to the argocd Deployment)
kind: Component
apiVersion: kustomize.config.k8s.io/v1alpha1

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
      spec:
        template:
          spec:
            containers:
            - name: jsonnet-bundler
              command:
              - /var/run/argocd/argocd-cmp-server
              securityContext:
                runAsUser: 999
                runAsNonRoot: true
              image: ghcr.io/VannTen/argocd-cmp-jsonnet-bundler # i don't actually use that image name as I ended up only putting this on our internal gitlab.
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /var/run/argocd
                  name: var-files
                - mountPath: /home/argocd/cmp-server/plugins
                  name: plugins
                - mountPath: /tmp # used by jsonnet-bundler when downloading deps
                  name: cmp-tmp
            volumes:
            - emptyDir:
                sizeLimit: 1Gi
              name: cmp-tmp
```

Example app:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://example.com/example/example-app.git
    targetRevision: HEAD
    path: example-app
    plugin:
      parameters:
        - name: cluster
          string: qtk8s
        - name: prlvl
          string: q
        - name: zone
          string: zoneA
        - name: structured
          map:
            foo: bar
            bar: foo
```

And then your app.jsonnet just takes a TLA argocd_params containers for instance your params in a map with name:key
