### ISSUE TITLE
Kustomize commonLabels in the argocd cli

### ISSUE THREAD

**Issue by wreed4** [argoproj/argo-cd#3703]
# Summary

The commonLabels field of Applications should be exposed to the `argocd app create` command.  

# Motivation

I have a kustomization that I want to use as a template for cluster bootstrapping.  I want to install this on every cluster I have.  I also want to be able to filter and sync just one cluster at a time.  My approach to solve this would be to specify a specific label on each app I make (and have that propagate down to every App inside the top-level App).  My only other option seems to be to use helm for all of this instead, but kustomize seems to be a better tool for this use-case. 

# Proposal

Mentioned above, expose this option to the cli.

**Comment by rosscdh** [comment]
+1 same requirement here

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "app-sandbox"
spec:
  destination:
    namespace: sandbox-app
    server: https://kubernetes.default.svc
  project: sandbox
  source:
    repoURL: git@.../my-app.git
    targetRevision: "feat/VN-1234/argo-sandbox"
    path: kustomize/overlays-eks/sandbox
    kustomize:
      version: v3.5.5
      commonLabels:
        app: "feat-vn-1234-argo-sandbox"
      namePrefix: "feat-vn-1234-argo-sandbox-"
      images:
        - "web-foundation-webapp-image=docker.io/my-app:1234"
        - "web-foundation-nginx-image=docker.io/my-app:1234"
```
