### ISSUE TITLE
Convert the `Application`s List into a ConfigMap

### ISSUE THREAD

**Issue by alpozcan** [argoproj/argo-cd#3708]
# Summary

Convert the `Application`s List into a ConfigMap.

# Motivation

If instead this data was in ConfigMap format, it would provide more flexibility.

# Proposal

Currently, the Application configuration is passed as a List:
```
apiVersion: v1
kind: List
items:
# If you put apps inside apps, the universe will be lost forever
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    ...
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    ...
```

If we could instead have these definitions in a kube `ConfigMap`, it would facilitate better  manipulation. For example, this would allow us to use Kustomize's `ConfigMapGenerator` to generate this largely repetitive data on the fly.
