### ISSUE TITLE
Support argocd app diff --local and argocd app sync --local with custom plugins

### ISSUE THREAD

**Issue by chancez** [argoproj/argo-cd#3731]
# Summary

The commands `argocd app diff` and `argocd app sync` both support a `--local` flag to run the sync or diff against local manifests. It would be desirable for this to work when using custom tools configured in the `argocd-cm` `data.configManagementPlugins` option. 

Currently trying to use these commands results in an error like:

```
FATA[0002] Config management plugin with name 'kustomize-with-local-plugins' is not supported.
```

# Motivation

I use custom plugins to call wrapper scripts on `kustomize` so that I can set additional environment variables and flags to pass to kustomize:

Eg:  `scripts/kustomize-with-local-plugins.sh`:
```
#!/bin/bash

set -e

DIR="$( cd "$(dirname "$0")" ; pwd -P )"
export KUSTOMIZE_PLUGIN_HOME="${KUSTOMIZE_PLUGIN_HOME:-"$DIR/../kustomize/plugins"}"
kustomize build --enable_alpha_plugins "$@"
```

With the following application:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  project: infrastructure
  source:
    path: kustomize/overlays/monitoring
    repoURL: git@gitlab.com/example/kubernetes-gitops.git
    targetRevision: master
    plugin:
      name: kustomize-with-local-plugins
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true

```

This allows me to use the chartInflator plugin with kustomize (https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/execPluginGuidedExample.md). I have similar use-cases with other tools, and custom tools in general.

# Proposal

Make it work similar to how `argocd app sync --local` and `argocd app diff --local` already works, except execute the plugin locally. Or even make it execute in the `argocd-repo-server` pod and pass the computed back. (I'm not entirely sure I know how this works with built in plugins).
