### ISSUE TITLE
Support additional metadata in Application sync operation

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#3736]
# Summary

Third-party integrations with Argo CD requires storing additional metadata in sync operation. 

# Proposal

Allow user to specify a list of key-value pairs during sync process so that information can be accessed later using Argo CD API/UI.

### CRD changes

Add info field to the application operation [struct](https://github.com/argoproj/argo-cd/blob/0a815be07a18a132e4a89eb26a25d722722fa9c3/pkg/apis/application/v1alpha1/types.go#L432):

```yaml
    operation:
      info:
        - name: name1
           value: value1
        - name: name2
           value: value2
      sync:
        prune: true
        revision: 6bed858de32a0e876ec49dad1a2e3c5840d3fb07
        syncStrategy:
          hook: {}
```

## CLI Changes

Add `--info` flag which value includes name and value separated with `=`:

```bash
argocd app sync <my-app> --info name1=value1 --info name2=value2
```
