### ISSUE TITLE
Can't sync with ignoreDifferences for configmap data

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#3750]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Create an application with ignore differences for a config map, ignoring some keys under data. When trying to sync, the following error is returned:

```go
FATA[0001] rpc error: code = InvalidArgument desc = Application.argoproj.io "test" is invalid: spec.ignoreDifferences.group: Required value
```

**To Reproduce**

```yaml
# application.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
labels:
  app.kubernetes.io/instance: test
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  generation: 73310
  labels:
    argocd.argoproj.io/instance: test
  name: test
  namespace: argocd
spec:
  destination:
    namespace: test
    server: 'https://my-external-cluster:6443'
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data/TEST_NAME
  project: test
  source:
    helm:
      releaseName: test
      valueFiles:
        - values.yaml
    path: chart/test
    repoURL: 'ssh://git/manifests.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
```

**Expected behavior**

Should be able to sync.

**Version**

```yaml
argocd: v1.5.6+f46333e
  BuildDate: 2020-06-02T18:40:52Z
  GitCommit: f46333ea82ad2157baffc5a8cf02a86720d4bad4
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.0-rc2+f5bcc1d
  BuildDate: 2020-06-09T22:23:19Z
  GitCommit: f5bcc1dbcc11c6aa00e6fbcd4dc34a0fd752e917
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
  Kubectl Version: v1.14.0
```
