### ISSUE TITLE
No redirect_uri when using GitHub dex connector

### ISSUE THREAD

**Issue by mhamann** [argoproj/argo-cd#3761]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to configure Argo CD to SSO authenticate with GitHub (specifically, Enterprise in my case). My configmap looks like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.development-4.<company_app_domain>
  dex.config: |
    connectors:
      - type: github
        id: github-enterprise
        name: GitHub
        config:
          hostName: github.<company>.com
          clientID: $dex.github.clientId
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: my-github-org
            teams:
            - argo-cd-master
```

When I click the `Login via GitHub` button on the Argo CD login page, no `redirect_uri` is present in the URL query string, so GitHub doesn't know exactly where to return during the callback phase of the auth handshake.

**To Reproduce**

- Configure Argo CD configmap with GitHub Dex config (see above).
- Restart Argo CD server pods
- Open the Argo CD login page and click "Login with GitHub"
- Go through OAuth flow / redirects
- Arrive back at `<argocd domain>`

**Expected behavior**

Argo CD should include a `redirect_uri` query param so GitHub knows exactly where to return the browser to upon authorization success.

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:58:54Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```
