### ISSUE TITLE
Unable to configure SSO, Dex server doesn't appear to be running

### ISSUE THREAD

**Issue by cyrus-mc** [argoproj/argo-cd#3787]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am attempting to configure Okta SAML SSO integration and have followed the documentation as outlined here (https://argoproj.github.io/argo-cd/operator-manual/user-management/okta/).

After making the necessary configuration changes, I click the Login with Okta button and it quickly shows the main login page and then redirects back to the login page. 

**To Reproduce**

I updated `argocd-cm` with the following contents as shown in the documentation (obviously replacing with values for my deployment. 

```
dex.config: |
  logger:
    level: debug
    format: json
  connectors:
  - type: saml
    id: okta
    name: Okta
    config:
      ssoURL: https://yourorganization.oktapreview.com/app/yourorganizationsandbox_appnamesaml_2/rghdr9s6hg98s9dse/sso/saml
      # You need `caData` _OR_ `ca`, but not both.
      caData: |
        <CA cert passed through base64 encoding>
      # You need `caData` _OR_ `ca`, but not both.
      ca: /path/to/ca.pem
      redirectURI: https://ui.argocd.yourorganization.net/api/dex/callback
      usernameAttr: email
      emailAttr: email
      groupsAttr: group
```

After doing so I am unable to login. 

**Expected behavior**

I am sure I am probably missing something really simple and stupid here. However I note that the dex server itself outputs no logs what so ever (even on start-up). Dex should be accessible via port 5556, but if I port forward that I get connection refused. Execing into the POD and running netstat does not show any listening ports. From what I can tell it appears that dex itself isn't starting as there should at least be some log output on start-up. 

In addition the configuration calls for the redirectURI to be https://ui.argocd.yourorganization.net/api/dex/callback. The Ingress setup routes all traffic to the argocd-server (as per the documentation) meaning /api/dex/callback would route through that component. Hitting that URI on the server returns 404. 

**Version**

Running version 1.5.8 of the server and CLI (just upgraded from 1.5.7 which exhibited the same issue).

**Logs**

No logs are generated by the dex server.
