### ISSUE TITLE
insecure flag is nor working with repository.credentials

### ISSUE THREAD

**Issue by MohamedTalhaoui** [argoproj/argo-cd#3798]
**Describe the bug**

I have setup repository.credentials to configure credential templates to acces multiple repositories in a private gitlab using self-signed certificates.
I am using declarative setup and the insecure flag is set to true.
Synchronization is failing due to invalid certificate

**To Reproduce**
My configuration looks like this:

```
  repository.credentials: |
    - url: https://my-gitlab-private-repo.com/my-group
      insecure: true
      usernameSecret:
        key: username
        name: gitlab-secret
      passwordSecret:
        key: password
        name: gitlab-secret
```

**Expected behavior**

Synchronization should work

**Version**

```shell
argocd: v1.5.4+36bade7
  BuildDate: 2020-05-05T19:02:56Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.4+36bade7
  BuildDate: 2020-05-05T19:01:57Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```
