### ISSUE TITLE
Disable the submodule feature in a declarative way.

### ISSUE THREAD

**Issue by zioalex** [argoproj/argo-cd#3799]
# Summary

It would be great to have the possibility to disable the sub-modules feature in a declarative way.
Today it is only possible globally as documented here https://argoproj.github.io/argo-cd/user-guide/private-repositories/#git-submodules
Even it is disconnected from the Declarative Setup as defined here https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/ 

# Motivation

We have a project that doesn't need to fetch all the sub-modules in all the stages. 
So it would be great if we can control such config in a declarative way.

# Proposal

The idea is to have a feature toggle directly n the repo declaration like:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    fetch_submodules: false
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
```

**Comment by wreed4** [comment]
Is there a possibility of getting this in?  I need to disable submodules for a single app, but don't want to disable globally and this is currently preventing me from using ArgoCD for this app.

**Comment by dohnto** [comment]
We would like to utilize this feature as well.

**Comment by redno2** [comment]
Especially useful if you have repo pointing to github.com, and your argocd is in offline mode, because of security constraints. The deployment fail like;
```
 ComparisonError
rpc error: code = Internal desc = Failed to checkout 7a34387fdf439e8a8f9f126703b1f3da709aa0d6: `git submodule update --init --recursive` failed exit status 1: Cloning into '/tmp/https:__github.*******_cicd_*******'... fatal: unable to access 'https://github.com/.......
```

**Comment by MaxWinterstein** [comment]
For everyone like me, who had no idea how to disable it globally,

```bash
kubectl set env deployment/argocd-repo-server ARGOCD_GIT_MODULES_ENABLED=false
```

**Comment by mattsfrey** [comment]
Another voice of support here, pulling submodules is causing a lot of issues for me.

**Comment by soudaburger** [comment]
For the helm chart:
```yaml
repoServer:
  env:
    - name: ARGOCD_GIT_MODULES_ENABLED
      value: "false"
```
