### ISSUE TITLE
Support for verification of GPG signed Helm packages

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#3833]
# Summary

Following up the verification of GPG signatures on Git commits (#3242), we should also support the verification of signatures on charts in Helm repositories, as described in https://helm.sh/docs/topics/provenance/

# Motivation

Many people use Helm charts with ArgoCD and could benefit from this feature, when they require that only signed packages are allowed to be installed on their clusters.

This is most likely less relevant for many OTS charts. However, organisations building and hosting their own charts might have those requirements.

# Proposal

We should leverage the key management and many of the mechanisms introduced with #3242 for validating GPG signatures on Helm charts, too.

**Comment by aelbarkani** [comment]
I agree, it's an important security feature.

**Comment by aelbarkani** [comment]
Any plans to make this feature available ?

**Comment by moosh3** [comment]
+1, and updates here?

**Comment by btrepp** [comment]
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dash
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dash 
  project: core
  source:
    chart: kubernetes-dashboard
    repoURL: https://kubernetes.github.io/dashboard/
    targetRevision: 5.3.1
    helm:
      releaseName: kubernetes-dashboard
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argocd
    server: 'https://kubernetes.default.svc'
  - namespace: authentik
    server: 'https://kubernetes.default.svc'
  - namespace: registry
    server: 'https://kubernetes.default.svc'
  - namespace: tunnel
    server: 'https://kubernetes.default.svc'
  - namespace: dash
    server: 'https://kubernetes.default.svc'
  - namespace: traefik
    server: 'https://kubernetes.default.svc'
  signatureKeys:
  - keyID: 906F464D532BA3E1
  sourceRepos:
  - "https://git.sr.ht/~btrepp/infrastructure"
  - "https://kubernetes.github.io/dashboard/"
  - "https://helm.traefik.io/traefik"
  - "https://charts.goauthentik.io/"
```

```
status:
  conditions:
  - lastTransitionTime: "2022-04-02T08:08:09Z"
    message: Target revision 5.3.1 in Git is not signed, but a signature is required
    type: ComparisonError
  - lastTransitionTime: "2022-04-02T08:13:20Z"
    message: 'Failed sync attempt to 5.3.1: ComparisonError: Target revision 5.3.1
      in Git is not signed, but a
```

Did this sneak in somehow?. Documentation says this won't be checked, but it's throwing an error that it's not signed.

Either I have found a bug, or this feature is implemented :).
