### ISSUE TITLE
Allow setting custom staticClients for dex configuration

### ISSUE THREAD

**Issue by gordonbondon** [argoproj/argo-cd#3834]
# Summary

Currently, ArgoCD generates its own static clients for dex installation and provides no way to add custom ones. 

# Motivation

We're running ArgoCD together with Argo Workflow, which has recently added SSO support. It would be great if we can use only one Dex to provide access to both. This will reduce setup complexity - no need to maintain two integrations in Github, Okta etc.

# Proposal
PR #3835

**Comment by hobbsh** [comment]
@gordonbondon @jannfis do either of you mind elaborating on what the sso config looks like on the workflows side? Should the `issuer` be the external URL of the argo-cd server, for example `https://my-argo-cd.mydomain.com/api/dex`? I think there's a bit of documentation missing (or I can't seem to find it). Happy to PR with the details if someone can give a brief explanation. thanks!

**Comment by gordonbondon** [comment]
@hobbsh I use external argo-cd url as you've mentioned. 

Snippet from argo workflow config map:
```yaml
sso:
  clientId:
    key: argoWorkflowDexClientID
    name: argocd-secret
  clientSecret:
    key: argoWorkflowDexClientSecret
    name: argocd-secret
  issuer: https://argo-cd.example.com/api/dex
  redirectUrl: https://argo-workflow.example.com/oauth2/callback
```

and config for argo-cd is like this:
```yaml
dex.config: |
  staticClients:
    - id: argo-workflow
      name: Argo Workflow
      redirectURIs:
        - https://argo-workflow.example.com/oauth2/callback
      secret: $argoWorkflowDexClientSecret
```

`argoWorkflowDexClientID` in secret is equal to `argo-workflow`, and `argoWorkflowDexClientSecret` is just some randomly generated secret.
