### ISSUE TITLE
PreSync hook resources are recreated on sync

### ISSUE THREAD

**Issue by michaelgeorgeattard** [argoproj/argo-cd#3837]
Resources marked with `argocd.argoproj.io/hook: PreSync` annotation are deleted and recreated on sync.

Is this intentional?

**Comment by anarcher** [comment]
IMHO,I'm not entirely sure but the 'hook-delete-policy' will have 'nothing' policy. 
Currently Default policy is 'BeforeHookCreation'. So resources in presync are recreated.

**Comment by runzexia** [comment]
We have also encountered such a problem.

Our deployment process is divided into the following steps.
1. create db
2. run db migrate job
3. deploy serverless workload

Because our workload is serverless, we need to complete the initialization of the database at deployment time and cannot use init container

**Comment by runzexia** [comment]
cc @alexmt @jannfis

**Comment by yalosev** [comment]
It's a bit weird becaues documentation clearly says:"This means that if the hook is named and already exists, it will not change unless you have annotated it with before-hook-creation"

**Comment by ronengloat** [comment]
I had this same issue. I have a pvc created with `argocd.argoproj.io/hook: PreSync`. When I re-synced the app, the pvc was recreated. It was unsuccessfull since it was still attached to a pod so the sync broke. 

For my case I solved it by adding the annotation `argocd.argoproj.io/hook-delete-policy: "HookFailed"`. Im not sure if this is appropriate to your case however, but this ensures my pvc isnt recreated on each sync.

**Comment by vl-kp** [comment]
I have the same issue on v2.6.7+5bcd846

**Comment by Wouter0100** [comment]
I think this is wrongly tagged as a bug, instead: it is a feature. A "Nothing" `hook-delete-policy` is currently not yet implemented, it seems.

**Comment by vitalii-dubovoy** [comment]
I think it's a bug. Currently, I use the v2.10.0 ArgoCD version and have a helm chart, here is a template output
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: init-migration
        image: "ghcr.io/team/migration:2.0.7"
        envFrom:
        - secretRef:
            name: cluster-example-superuser
      containers:
      - name: nginx
        image: "ghcr.io/team/app:2.0.3"
        envFrom:
        - secretRef:
            name: cluster-example-superuser
      imagePullSecrets:
      - name: github-registry-pull-secret
---
# Source: app-test/templates/cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  annotations:
    argocd.argoproj.io/hook: "PreSync"
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  instances: 1
  enableSuperuserAccess: true
  storage:
    size: 1Gi
```

Add app
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: app-test
  namespace: argo
spec:
  destination:
    namespace: cnpgtest
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: valuesRepo
    repoURL: git@github.com:team/ArgoCD.git
    targetRevision: main
  - chart: helm/app-test
    helm:
      releaseName: app-test
      valueFiles:
      - $valuesRepo/deployment/team/development/app-test/values.yaml
    repoURL: team.azurecr.io
    targetRevision: 3.0.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
```

And every Sync I get `kind: Cluster` is being deleted event it has such annotations
<img width="631" alt="image" src="https://github.com/argoproj/argo-cd/assets/103578109/658edfc5-564f-42b6-935c-2369ec4e2f52">
