### ISSUE TITLE
PVC with Pre-Sync or Helm's Pre-Install annotation getting terminated by argo during every sync process

### ISSUE THREAD

**Issue by pkrishnath** [argoproj/argo-cd#3846]
When I deploy PVC which has  argo's Pre-Sync / Helm Pre-Install annotation  via helm chart , Argo is terminating  the PVC & getting stuck during every sync process

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: '-5'
  labels:
    argocd.argoproj.io/instance: test
  name: test-node-pvc
  namespace: uat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
status:
  accessModes:
    - ReadWriteOnce
```

**Expected behavior**

Argo Should not terminate the PVC which is annotated  with helm\argo hooks

**Screenshots**

<img width="565" alt="Screenshot 2020-06-23 at 17 05 58" src="https://user-images.githubusercontent.com/8318142/85706612-4aa9f700-b6da-11ea-9b78-99f8b43c69b9.png">

**Version: v.1.6.1**

**Comment by werne2j** [comment]
Wanted to bring some attention back to this issue as my team is seeing the same thing

**Comment by cloudlady911** [comment]
This was first pointed out 4 1/2 years ago.  I am encountering it now in version 2.13.2.  It seems to be a blocker for me.  I have over 400 apps to deploy and maintain with argocd.  

I have a job that run in the PreSync phase which downloads files onto the PVC.  This PVC is then later used by the Deployment.

The problem is, if any part of the deploy fails ArgoCD tries to remove the pvc.  However the remove gets stuck because the PVC is in use by the deployment.

If the bug can't be fixed, then what is the work-around?

**Comment by crenshaw-dev** [comment]
Maybe you could try setting the hook deletion policy to `HookFailed`. That should keep it from being deleted when the next sync starts. https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies

But since a persistent Deployment uses this PVC, maybe you should abandon sync hooks and instead use sync waves. Sync waves enforce ordering but do not cleanup resources after they're applied.

**Comment by cloudlady911** [comment]
These are my settings:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.appName }}-efs-claim"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "{{ .Values.appRegion }}-efs-sc"
  resources:
    requests:
      storage: "5Gi"
```
I have a job that runs in PreSync. I also have a job that runs in PostSync.  **If EITHER job fails**, then Argo tries to delete the PVC.  But it can't because the PVC in use by the deployment. It might work as expected when a new app is created but if I am modifying an app and the EITHER job fails then it gets stuck.  And the only thing I can do is manually remove the deployment from Kubernetes.  Then Argo can delete the pvc and the process continues.  

But it should not try to delete the pvc if a PostSync job fails.
