### ISSUE TITLE
Unable to force tool type as helm without adding dummy values

### ISSUE THREAD

**Issue by james-callahan** [argoproj/argo-cd#3868]
Creating an application with source:
```
  destination:
    namespace: mynamespace
    server: https://mycluster.com
  source:
    repoURL: repo@example.com:example
    path: some-path
    targetRevision: HEAD
    helm: {}
```
(to force the tool type as helm), results in the `helm: {}` disappearing.
Likewise
```
    helm:
      values: ''
```
and 
```
    helm:
      namespace: mynamespace
```
gets removed (if the namespace is the one already set in the destination).

To trick argo into *not* removing the `helm` key, I've had to use:
```
    helm:
      values: 'dummy: dummy'
```
