### ISSUE TITLE
argo login returning "The handle is invalid"

### ISSUE THREAD

**Issue by bcaton85** [argoproj/argo-cd#3871]
**What happened**:

CLI version: 

Fresh install of argo cli and server into GKE cluster. Attempting to login with argocd login <server> always returns with ` time="2020-06-29T14:46:26Z" level=fatal msg="The handle is invalid."`

Example:
```
$ argo login $SERVER_IP
WARNING: server certificate had error: x509: certificate signed by unknown authority. Proceed insecurely (y/n)? y
Username: admin
Password: time="2020-06-29T14:46:26Z" level=fatal msg="The handle is invalid."
```

**What you expected to happen**:
To successfully login.

**How to reproduce it (as minimally and precisely as possible)**:
Fresh install, run argocd login.

**Anything else we need to know?**:

**Environment**:
locally: windows 10
Kubernetes: GKE cluster

- Argo version:
```
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:43:39Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: windows/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-04-21T04:45:58Z"
  compiler: gc
  gitCommit: f2a77f678d6baccda27740d700f6cba2754dfacf
  gitTreeState: clean
  gitVersion: v1.15.11-dispatcher
  goVersion: go1.12.17
  major: "1"
  minor: 15+
  platform: windows/amd64
serverVersion:
  buildDate: "2020-04-06T16:33:17Z"
  compiler: gc
  gitCommit: 34a615f32e9a0c9e97cdb9f749adb392758349a6
  gitTreeState: clean
  gitVersion: v1.14.10-gke.36
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
