### ISSUE TITLE
Unable to disable auto-sync

### ISSUE THREAD

**Issue by sadovnikov** [argoproj/argo-cd#3895]
Argo CD version: 

**Describe the bug**

With app-of-apps pattern, when syncPolicy of a child application changes from "automated" to empty, Argo does not spot the difference. The child application remains in auto-sync mode, although it's desired manifest in the parent app changes 

**To Reproduce**

* Create an application, which creates another application with auto-sync policy

```
  syncPolicy:
    automated: {}
```

* After everything is synchronized change policy to

```
  syncPolicy: {}
```

**Expected behavior**

Synchronization policy of the child application changes.
However, it remains auto-sync. No Diff is spotted in spite of different live and desired manifests

**Screenshots**

With these live and desired manifests, the Diff tab is empty

![image](https://user-images.githubusercontent.com/4749332/86452027-fcb97280-bd1b-11ea-9de0-f5d6561deebe.png)

![image](https://user-images.githubusercontent.com/4749332/86452092-1c509b00-bd1c-11ea-8f93-810f359315b9.png)

**Version**

Taken from UI
```
v1.6.1+159674e
```

Note: we also spotted #3815. Seems treating of default or boolean values of `syncPolicy` has changed in v1.6

**Comment by jannfis** [comment]
Hi @sadovnikov, I couldn't reproduce this issue, but maybe I did the wrong steps to reproduce it. I did the following:

* I created a repo containing a single `application.yaml` with the following contents:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/jannfis/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated: {}
```

* I then created an application `parent` using ArgoCD UI, and specifying above mentioned repo as its source. This creates the app-of-apps pattern, with `parent` as parent and `test-app` as child. `parent` has no automatic sync policy.
* Once I sync `parent`, `test-app` resource is created and immediately syncs due to automatic sync policy
* I changed sync policy of `test-app` to `syncPolicy: {}` and commited to repository
* After a refresh, `parent` becomes out of sync
* Once I sync `parent`, it reconciles the updated manifest for `test-app` and I can see that automatic sync policy for `test-app` is disabled

Did I miss something?

**Comment by sadovnikov** [comment]
Hi @jannfis, I created https://github.com/sadovnikov/argocd-tests/tree/master/github-3895 to reproduce the bug, but it's not reproducible anymore. Neither I can reproduce it with the original repositories ;( I'll re-open the issue if I find a way to reproduce it. Thank you!

**Comment by dorroddorrod** [comment]
Hi everyone,
I'm facing the same issue,
It start when i tried to run a rollback from the UI and got the following error :
<img width="1426" alt="Screen Shot 2021-08-19 at 14 17 16" src="https://user-images.githubusercontent.com/31075689/130060054-ec69c73f-ef5e-43e5-93ad-e3d842ed3781.png">
Then, i chose one of the old deployment to rollback, got prompt if i want to disable the auto-sync, clicked yes and got the following error :
<img width="1398" alt="Screen Shot 2021-08-19 at 14 18 36" src="https://user-images.githubusercontent.com/31075689/130060239-b6c91364-af05-4f70-909b-97868e58a84d.png">

When trying to disable the auto-sync from the UI OR from the cli, nothing really happen.

https://user-images.githubusercontent.com/31075689/130060627-c765c598-a04c-477a-bbda-af10c4c87659.mov

{
    "Version": "v2.0.3+8d2b13d",
    "BuildDate": "2021-05-27T17:38:37Z",
    "GitCommit": "8d2b13d733e1dff7d1ad2c110ed31be4804406e2",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}

**Comment by dorroddorrod** [comment]
@sadovnikov Would you mind to re-open this issue ?

**Comment by cheddarwhizzy** [comment]
```
kubectl -n <namespace> patch --type='merge' application <app-name> -p "{\"spec\":{\"syncPolicy\":null}}"
```

**Comment by ThoughtHopper** [comment]
I'm having this problem too. 

I'm trying it from the UI (buttons), modifying the manifest, the kubectl patch does not work either.

I'm under the impression that this is something intermittent. I think it was working a day or two ago, but now it's not.

Here is my server version 

{
    "Version": "v2.0.4+0842d44",
    "BuildDate": "2021-06-23T01:27:53Z",
    "GitCommit": "0842d448107eb1397b251e63ec4d4bc1b4efdd6e",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}

**Comment by alexmt** [comment]
Created ticket to improve auto-sync button behavior: https://github.com/argoproj/argo-cd/issues/7197

**Comment by converge** [comment]
is there any update about this bug?

**Comment by altosys** [comment]
We are also experiencing this issue, what is the current status on this?

**Comment by jannfis** [comment]
Re-opening this as people reporting issue again.

**Comment by thiagolsfortunato** [comment]
Any news?

I'm experiencing the same issue.

To disable the sync in the YAML manifest I set `syncPolicy: {}` but I would like to keep the `syncOption`, and today is impossible to have both.

https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#fail-the-sync-if-a-shared-resource-is-found

```
syncPolicy:
    syncOptions:
      - FailOnSharedResource=true
```

**Comment by adrian-sturm** [comment]
I'm facing the similar problem that I cannot disable auto-snyc (nor pruning and self heal) of an application resource via the UI.
It seems to me that argoCD is overwriting these changes immediately as it tries to sync and auto-heal again - which Im trying to disable!
So the UI buttons must get around the self-healing and auto-syncing process to be able to work...

**Comment by adrian-sturm** [comment]
Update: For my problem (and i figure it might resolve the OPs problem as well) the issue was that in my app-of-apps pattern, the root-application was configured with `self-heal=true`, causing changes to the child-apps to be "healed" even though the child apps had a different (or no) sync-policy configured. 
So now my setup is: root-app: `syncPolicy: automated # so new apps are auto-detected and deployed` `prune: true # so removed apps get deleted` and `selfHeal: false # so changes to child-apps (e.g. via the UI) do not trigger an auto sync`

I hope this helps someone out there as well!

**Comment by olastefaniak** [comment]
I want to override sync policy from CLI and I also fail miserably.
I tried the approach proposed by @adrian-sturm, but with no result. I tried disabling syncing at all, also with no result. From UI the situation is the same. Additionally, I don't get any error messages, argo just keeps bringing back the original configuration.

1. Parent application yaml and original status:

     ```                                                                          
     destination:                                                                 
       namespace: krowa                                                           
       server: https://kubernetes.default.svc                                     
     project: default                                                             
     source:                                                                      
       helm:                                                                      
         valueFiles:                                                              
         - environments/dev.yaml                                                  
       path: argocd/krowa-apps                                                    
       repoURL: <redacted>                                                        
       targetRevision: HEAD                                                       
     syncPolicy:                                                                  
       automated:                                                                 
         prune: true                                                              
         selfHeal: true                                                           
     ```  

    ```
    $ argocd app get krowa-parent
    Name:               argo/krowa-parent
    Project:            default
    Server:             https://kubernetes.default.svc
    Namespace:          krowa
    URL:                <redacted>
    Repo:               <redacted>
    Target:             HEAD
    Path:               argocd/krowa-apps
    Helm Values:        environments/dev.yaml
    SyncWindow:         Sync Allowed
    Sync Policy:        Automated (Prune)
    Sync Status:        Synced to HEAD (5519559)
    Health Status:      Healthy

    GROUP        KIND         NAMESPACE     NAME             STATUS     HEALTH  HOOK  MESSAGE
                 Namespace    krowa         krowa            Succeeded  Synced        namespace/krowa unchanged
    argoproj.io  Application  argo          child-app        Synced                   application.argoproj.io/child-app configured
                 Namespace                  krowa            Synced
    ```

3. I edited parent app and I commented out whole `syncPolicy` section:

    ```
    $ argocd app edit krowa-parent

     # Please edit the object below. Lines beginning with a '#' will be ignored,
     # and an empty file will abort the edit. If an error occurs while saving this file will be
     # reopened with the relevant failures."

     destination:
       namespace: krowa
       server: https://kubernetes.default.svc
     project: default
     source:
       helm:
         valueFiles:
         - environments/dev.yaml
       path: argocd/krowa-apps
       repoURL: <redacted>
       targetRevision: HEAD
    # syncPolicy:
    #   automated:
    #     prune: true
    #     selfHeal: true
    ```

4. Check app once again

    ```
    $ argocd app get krowa-parent
    Name:               argo/krowa-parent
    Project:            default
    Server:             https://kubernetes.default.svc
    Namespace:          krowa
    URL:                <redacted>
    Repo:               <redacted>
    Target:             HEAD
    Path:               argocd/krowa-apps
    Helm Values:        environments/dev.yaml
    SyncWindow:         Sync Allowed
    Sync Policy:        Automated (Prune)
    Sync Status:        Synced to HEAD (5519559)
    Health Status:      Healthy

    GROUP        KIND         NAMESPACE     NAME             STATUS     HEALTH  HOOK  MESSAGE
                 Namespace    krowa         krowa            Succeeded  Synced        namespace/krowa unchanged
    argoproj.io  Application  argo          child-app        Synced                   application.argoproj.io/child-app configured
                 Namespace                  krowa            Synced

    ```

5. Running `argocd app set krowa-parent --sync-policy="none"` has no effect.
6. Changes in UI are also immediately brought back to the original settings.

**Comment by adrian-sturm** [comment]
@olastefaniak I assume you are using the app-of-apps pattern as well and "krowa-parent" is the root application resource?
Commenting out the sync policy likely results in argocd using the default sync policy, which I could not find in the docs but by the behavior you describe it might be "automated" anyways. As long as "self-heal" is activated in the deployed resource (aka the yaml found in your k8s cluster), argocd will continue to overwrite any changes with the status described in your repository.

Have you tried disabling "self-heal" in your repository (target-manifest in argocd-terms)?
And if so, did you check that this change is actually deployed in the cluster?

If that does not fix the situation, there has to be some other resource (e.g. application or applicationset) that references your "krowa-parent" app and has self-heal enabled.

**Comment by v-avdeev** [comment]
Also check if you have an `ApplicatoinSet` that manages your `Applications`. In this case all changes to `Application` will be instantly undone, no matter what they were made with (UI/argocd cli/CRD)

**Comment by illegalnumbers** [comment]
Is there any movement on this?

**Comment by crenshaw-dev** [comment]
@illegalnumbers yes, this will allow folks to exclude fields from ApplicationSet's regular updates: https://github.com/argoproj/argo-cd/pull/14743

**Comment by ghostsquad** [comment]
I'm running into the same problem. Not using app of apps, literally just `kubectl apply -f app.yaml`

originally, I had `automated` filled in. But then I changed it to `automated: {}` and auto-sync is still reported as being enabled. Both from the CLI and UI.

```
Sync Policy:        Automated
```

I feel like the solution here is a simple one. Add an `enabled` field, then this becomes just a boolean value. It's easier to reason about for both the user and the code behind the scenes.

**Comment by ghostsquad** [comment]
I actually found out that setting this field to the `null` equivalent disables auto sync

```
  # Sync policy
  syncPolicy:
    automated:
```

<img width="199" alt="image" src="https://github.com/argoproj/argo-cd/assets/903488/891319aa-a750-465a-aa1c-cf7ed225e9b9">

**Comment by b8kings0ga** [comment]
seems like it'll sync back to "enable" using all method

**Comment by VesperDev** [comment]
syncPolicy: null

**Comment by younsl** [comment]
In my case, I found a solution.

## Environment

- Amazon EKS v1.26
- ArgoCD v2.9.5 (Installed by `helm install` command)

## Solutions

Disable autosync in application spec:

```yaml
# application resource spec
syncPolicy: {}
```

Enable autosync in application spec:

```yaml
# application resource spec
syncPolicy:
  automated:
    prune: false
    selfHeal: false
```

or also valid spec:

```yaml
# application resource spec
syncPolicy:
  automated: {}
```

> **Warning**:
> You must definitely set `syncPolicy` value to null `{}` in order to disable auto-sync.

```diff
# application resource spec
- syncPolicy:
-   automated: {}
+ syncPolicy: {}
```

## Reference

[Automated sync policy](https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/)

**Comment by hawkesn** [comment]
We did this:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
```
From: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync

And that worked!
