### ISSUE TITLE
argocd always detects diffs in tekton TaskRuns

### ISSUE THREAD

**Issue by ls-devon-hakel-kinko** [argoproj/argo-cd#3897]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

argocd always detects a diff on `TaskRun` custom resources. We've been experiencing this bug since version `v1.2.3` of argocd and still have it in `v1.4.2`. All of our apps are constantly `OutOfSync` because of the `TaskRun`s.
Performing a 2nd selective sync on the taskrun when it's outofsync somehow fixes the issue and argocd stops detecting non-existent diffs.

**To Reproduce**

1. Create an argocd application with a tekton `TaskRun`:
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: dx-dashboard-app-namespace-run-292333
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  taskRef:
    name: init-namespace
  inputs:
    params:
      - name: app-name
        value: dx-dashboard-app
  serviceAccount: tools-cluster-admin
```

2. Sync the app
3. Confirm that the desired manifest of the taskrun matches the live manifest.

**Expected behavior**

The `TaskRun` appears fully synced in the argocd dashboard.

**Actual behavior**

argocd will always detect a diff in the TaskRun and therefore is always outofsync.

Different fields: 
- `metadata.annotations`
- `metada.labels`
- `spec.inputs.params`
- `spec.serviceAccount`
- `spec.taskRef`

**Screenshots**

<img width="827" alt="Screen Shot 2020-07-03 at 7 13 28 PM" src="https://user-images.githubusercontent.com/54455959/86500749-53956b00-bd61-11ea-9fbd-0dc66782d8bd.png">

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Additional Notes**

I'm not convinced that this diffing issue is related to https://github.com/argoproj/argo-cd/issues/2865 since it doesn't only concern environment variables.
