### ISSUE TITLE
UI only links to the last OwnerReference in the list

### ISSUE THREAD

**Issue by alexvanboxel** [argoproj/argo-cd#3910]
**Describe the bug**

The UI only shows a link to the last OwnerReference of a resource in the OwnerReferences list. You would expect that it links to all of the parents.

**To Reproduce**

Apply the following file: `kubectl apply -f owner-a.yaml`

```yaml
apiVersion: v1
data:
  foo: "bar"
kind: ConfigMap
metadata:
  name: owner-a
```

Apply the following file: `kubectl apply -f owner-b.yaml`

```yaml
apiVersion: v1
data:
  foo: "bar"
kind: ConfigMap
metadata:
  name: owner-a
```

Now get the UID's of the applied files by using 

```shell
kubectl get cm owner-a -o=yaml
kubectl get cm owner-b -o=yaml
```

Fill the UID in the following file, so the UID is correct for each resource (AAAAA for owner-a, BBBBB for owner-b):

```yaml
apiVersion: v1
data:
  foo: "bar"
kind: ConfigMap
metadata:
  name: child
  ownerReferences:
    - apiVersion: v1
      kind: owner-a
      name: privacy
      uid: AAAAA
    - apiVersion: v1
      kind: ConfigMap
      name: owner-b
      uid: BBBBB
```

If you now go to the UI you will see that only the last owner is linked too.

<img width="645" alt="Screen Shot 2020-07-07 at 11 25 47 AM" src="https://user-images.githubusercontent.com/639539/86762279-d4e14c00-c046-11ea-9fe9-50109751d0f0.png">

If you flip owner-a and -b the UI will flip to the other parent (the last one)

<img width="641" alt="Screen Shot 2020-07-07 at 11 26 41 AM" src="https://user-images.githubusercontent.com/639539/86762540-022dfa00-c047-11ea-87e4-7ecb257e28ce.png">

**Expected behavior**

You would expect the UI links to both OwnerReferences.

<img width="736" alt="Screen Shot 2020-07-07 at 11 40 59 AM" src="https://user-images.githubusercontent.com/639539/86762201-c6933000-c046-11ea-8f05-c29e78bd8c71.png">

**Version**

```shell
v1.5.8+47f43f9
```
