### ISSUE TITLE
x509: certificate signed by unknown authority when adding cluster

### ISSUE THREAD

**Issue by rayanebel** [argoproj/argo-cd#3945]
**Describe the bug**

Hi,

For our own purpose we need to define all our kubernetes cluster in argocd with a list of allowed namespaces. By default argocd import it's local cluster but with a cluster scope watch which is not possible in our kubernetes cluster (because we are not admin). So, I want to replace the default cluster by creating a new secret **in-cluster** with the address **kubernetes.default.svc** and with it's own service account (token and CAdata) to not use the SA of application-controller.

Here you can find an example of my secret for the cluster:

```yaml
apiVersion: v1
stringData:
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLWFyZ29jZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjaWNkLXRva2VuLXRkOTJwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImNpY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhMGRkZWM3Yi1iNmMzLTExZWEtODJhNC03MjVlZDk5NTljNTciLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1hcmdvY2Q6Y2ljZCJ9.BPkagMUSEyE7ysIVEq9G4LXiscU9CbsB9S6-pEp2Q7bScCx4i3myhMJiVs8FNFQ_dN_jKTfyJoju-60RwQWXKQHP_SnaHtKsMN-_COO6aqbFF1y0FHnmBPpVZ05uhWuqchfRuYoMVkENupSpZoicCP-SoT6X7wsASkfqcDPHGZR5YC0TETPZOWGM07BDZlMEfHV-YBpFepKio8Vtlh0E3N3QH8WrytoM9UPc3rvlmE01sN1nGTou7IRnzC7KIreTrIplhkPn2ax-q3isbCLjBxguuIjfhyomOMmoiNRt-cGc_GMkT2WvGSkt-5yjH3jyJbfHDeGYhHa04dI6JAHezxG-CKfUQ5wLFyw36R4JiKMOkVhbhLuRKwVANmG5O8iLKkbhqn_u79jnBOT3PrfjQRLTFoQZdjwjdx-x5ap7uNfWEwMdEzc49i57OrlgrNJOXMQiZqZrEF0G98uIyKQaUoUAI9VujplRKB3vMEdp974Ot7TcI_roo4ZzbB-yn-Sg2vG0EvuufaGwqldFg7YAY8yKZA23vBYNzy6h7PD-zehoBqChO6icwDOPuH4LIIMh_xSILNgMwcAVfG8Cg-9ph8A3ep6lYVKaIsvmGJ8LsdtPaoCajWk0SewPgnnTQjraMmh5TBf2hLL6I4IXSJyc3sEEiwTCNCfW0clGDpghfVg",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5RENDQXJDZ0F3SUJBZ0lSQUxLM3h0T2pidWdjSkNrNWwrWW0wL2N3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTVRreE1URTFNVEl5TnpRMldoY05ORGt4TVRBM01USXpOelEyV2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTlFKCmw0YmZSQ3JETVpGaHRhd0NkZnVJSlFKNDRnbi9aemY5Tzl6YlhHVk9YZFpTbEJQMlMzbHRKK2VJK2FwVi9OZzkKQmh3eCtEOEc2SEVnSGlOZkpHTHpuMkVXYjF6VGVlcW05R0VrSU4rMEN0ZWtXOHY5cld2Q3REZFlTUC83VVo0QQpHS3psa0hmbU1tUUw4Tm8rdjNsRWN1aUMvTENidXpBSWxMdkxFdW5WYXlNdGUyTEdRQ0JTWWdXanJyUmNRVDM1Cmladlg0cWVtMHhqR01JMnZhWnhFVDZvdU43RXgvSzRuOThGR1FTRUdpTENkcFdadWErY3N3dGxweFViYUJLNWUKRWlQVVhUS3VRMURLNjdjeW50bGRsUVpPdnh2ZDJzc2tDazdOa0RGdTEwSDNjazdMNUlSTjRKc3VGNHZIS0VhSApPVDh0VFIvTW4xYUFHSUtadFNxWjdJcElsK3V2KzNIN2dHNzNPZTlpTWVQckVqRE1hcFRyUUpmb3JEc0dpbGJmCnpJbjk3WVN1bE5oekZZTSt1RVhWSm5QOWliZkxoMXU3elZxZ3FzS2JtOWxVV0lqNFhLOHVocDFCWUxUbVRNcTEKTENjTUo5cDQvaVBoVU82UFFwTE85S2dBeXJKai82aGNabEpaSTlYVEZ4dG9uM1RDbnl6bHpFVG81YmJOSitMVQpvUk1iTk9rYVlIbC9CbXo5TlpCRUdHRWNPY3lNaDRHMGVWZXZhQ0U1eUxsR3hNRVlxc29tYkxuQW9tZHVPMTYzCk8wY2h4TFMrMC9TTU9jR051b3RjQ2RRSm54aFdTaElDOWhnbURlZmpLRmJUdFpwS3hVQ2JZa3lmRVBiSnlIREoKQWp6dXFJZmE1b1NzVHp1L2cydGZLY1BHdm14MTQwbk1veEs0UmFnVEFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQnRGWUZEClF6UEtBMzQzZGxHMFVVaWQzNVp0Y2lBM2tDVFR6c0hYUTlzL3ZjYlVKY0c5M1RLRmJFeWtYaFpPOXg1TUFDYkEKMWNZdmk3N25BZEU0d1FYLzlpMW01TWNqMUxKMFAwcHdVbm5NeDBnV3RRSlBQME90S3R5akFpTTFWbWYvdVo2ZgpNNE5oZUtvZFRpbWFZbU4vR2MyeFFnalh6eFFrQUJVWDd4NEZDRXExeEhLbnYxMEM1Q0lHZkZsUVBhY01ISUFhCm9nTWozV1dtQ2JjM1JzcVpYV2hWaUR5TUJuUlFYSDB3V0lNcFdoVTFQZEE3STdoRVBtN080eE1iOUMrZzFCVjQKTFJqOHplbWdZc3dBQm1OUlE3bk1JWDhBekdOWkg2Rml0UWxPd25kNjRibXlrQTVFQzFLTjZ3SkZvS04xTEJWbgp0NUlIWkJSRjQrLzZ1bHdyQ2YvYk1ncC9qUzRNbEkwVVBoellUUWs1RlFJU1BxeHVUMEFrUFdFNTBrT0tDTHBxCkZZSzlXTEFhODQ5bk9iajltUHYyUXdZNkNSbTdrS3NaeERaUWhDbTVQUEdxR1M0TUZBMlNnU0ErTzBORi9XMjQKK1ZCQnhCclM0Z0dKY0h1VnZjRE55Unl1T2cxbWtMRXZyMDhKbk9SdU1Xemt0NTBwS2dySDVLalZmNjRicVNIZAp2U3pJN2I2L2VUWTh5YkZybVBEbzBMYVZ3YzU1bElBUWxQK1RNOUJZMXhIKzF5aGl3ZWhCK2JDK3RJOVh3VTVECk9WQS8vUE5YOE9YZEhDRlVrWnpaRTRpQnROQ0R1REFuSThpUTRwVmlwWk5xQzhYS0dOa0VHejZsektwVDRhYzkKYTIxQmRaQ3VaTzFkRnhLN2kvcWU0RDV4WFlyZWZxSXpBZlUyOHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
      }
    }
  name: incluster
  namespaces: demo-argocd
  server: https://kubernetes.default.svc
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: incluster
type: Opaque
```

When I applied this secret I have the followig error: 

```
Failed  Unable to connect to cluster: Get "https://kubernetes.default.svc/version?timeout=1s": x509: certificate signed by unknown authority
```

For the Root CA I copy/past the value in the secret of my service account and I kept it in a base64 encoded format. I've already replace the default cluster in the past but now it's not working and I don't know why and if something has changed.

I also tried to create a kubeconfig using the CAdata and the bearer token of my service account and it's working.

Can you help me about this issue ?

**Version**

```shell
v1.6.1
```
