### ISSUE TITLE
Unable to use external Helm chart with provided values

### ISSUE THREAD

**Issue by parkee** [argoproj/argo-cd#3961]
I'm not able to deploy an external helm chart with my own values.yaml override.

**To Reproduce**

Application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: linkerd
  destination:
    namespace: "linkerd"
    server: {{ .Values.spec.destination.server }}
  source:
    path: deployments/linkerd2
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: "identity.issuer.crtExpiry"
          value: "2021-07-19T02:13:43Z"
      valueFiles:
        - values-ha-prod.yaml
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
      - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')
```
Chart.yaml
```
apiVersion: v2
name: linkerd2
version: 2.8.1
dependencies:
  - name: linkerd2
    repository: https://helm.linkerd.io/stable
    version: 2.8.1
```
values-ha-prod.yaml
```
identity:
  issuer:
    tls:
      crtPEM: issuer.crt
      keyPEM: issuer.key
    crtExpiry: "2021-07-19T02:13:43Z"

enablePodAntiAffinity: true

global:
  identityTrustAnchorsPEM: ca.crt
...
...
...
```

**Expected behavior**

Values from valueFiles and parameters should be applied.

**Actual result**

```
ComparisonError
rpc error: code = Unknown desc = `helm template . --name-template linkerd --namespace linkerd --set identity.issuer.crtExpiry=2021-07-19T02:13:43Z --values values-ha-prod.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions cloud.google.com/v1 --api-versions cloud.google.com/v1beta1 --api-versions crd.projectcalico.org/v1 --api-versions getambassador.io/v2 --api-versions getambassador.io/v1 --api-versions getambassador.io/v1beta2 --api-versions getambassador.io/v1beta1 --api-versions kubernetes-client.io/v1 --api-versions serving.knative.dev/v1 --api-versions serving.knative.dev/v1beta1 --api-versions serving.knative.dev/v1alpha1 --api-versions argoproj.io/v1alpha1 --api-versions authentication.istio.io/v1alpha1 --api-versions autoscaling.internal.knative.dev/v1alpha1 --api-versions caching.internal.knative.dev/v1alpha1 --api-versions certmanager.k8s.io/v1alpha1 --api-versions domains.cloudrun.com/v1alpha1 --api-versions internal.autoscaling.k8s.io/v1alpha1 --api-versions networking.internal.knative.dev/v1alpha1 --api-versions nodemanagement.gke.io/v1alpha1 --api-versions scalingpolicy.kope.io/v1alpha1 --api-versions tls.cloudrun.com/v1alpha1 --api-versions config.istio.io/v1alpha2 --api-versions networking.istio.io/v1alpha3 --api-versions networking.gke.io/v1beta2 --api-versions networking.gke.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds` failed exit status 1: Error: execution error at (linkerd2/charts/linkerd2/templates/identity.yaml:19:55): Please provide the identity issuer certificate expiry date Use --debug flag to render out invalid YAML

```

**Notes**
I added helm.parameters just for testing and see that it's correctly applied to the command:
```helm template . --name-template linkerd --namespace linkerd --set identity.issuer.crtExpiry=2021-07-19T02:13:43Z```
Also, I tried to intentionally set invalid values file name - in this case, it correctly fails with kind of file not found issue, so it definitely can see my file and the path is correct.
Tried to copy-paste the command and run it locally - it works as expected (without any errors and renders the correct output)

If I just copy-paste the entire chart, not just a reference to an external chart and use my own values in values.yaml it also works as expected.

**Version**
1.6.1+1
