### ISSUE TITLE
ArgoCD HookSucceeded deletion policy doesn't work on Sync hooks with a negative sync-wave value

### ISSUE THREAD

**Issue by encigem** [argoproj/argo-cd#3980]
Checklist:

* [Y] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [Y] I've included steps to reproduce the bug.
* [Y] I've pasted the output of `argocd version`.

**Describe the bug**

I've used the HookSucceeded policy without issue on PostSync hooks and Sync hooks with a wave value of 0 and up.
However, I'm noticing that one of my deployment's Job resources fails to delete after succeeded execution/completion, which is set as default 'Sync' hook type, but with a sync-wave value of '-1'.

This is a snippet of the job in question, which doesn't auto-delete after completion:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-wait-for-fs-ready"
  labels:
    ...
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ...
```

Here's a snippet from the same deployment, of a job that _does_ auto-delete on completion:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-proj-ps-pv-setup"
  namespace: {{ .Values.projPS.pvc.namespace }}
  labels:
    ...
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ...
```

**To Reproduce**

Create a job with default hook type "Sync" and with a sync-wave value of "-1", check to see if the job deletes after completion

**Expected behavior**

The resource with the "HookSucceeded" annotation should delete itself once it reaches it's successful state

**Version**

ArgoCD v1.5.1
```shell
ubuntu@dev-env-3-master:~$ argocd version
argocd: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:53:49Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:58:54Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```
Kubernetes v1.14:
```shell
ubuntu@dev-env-3-master:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Logs**
On the cluster where my charts are deployed:
```
ubuntu@dev-env-3-master:~$  kubectl get po,job -n proj | grep workspace
pod/workspacemanager-7fdfd54c5c-gd8c2          1/1     Running     0          41m
pod/workspacemanager-wait-for-fs-ready-m4vbl   0/1     Completed   0          36m

job.batch/workspacemanager-wait-for-fs-ready   1/1 

ubuntu@dev-env-3-master:~$ kubectl describe -n proj jobs.batch workspacemanager-wait-for-fs-ready | grep Annot -A 2
Annotations:    argocd.argoproj.io/hook-delete-policy: HookSucceeded
                argocd.argoproj.io/sync-wave: -1
                kubectl.kubernetes.io/last-applied-configuration:

```
