### ISSUE TITLE
Support for helm chart and values.yaml located in separated repos

### ISSUE THREAD

**Issue by likaiwen123** [argoproj/argo-cd#3988]
# Summary

Currently, we have to put chart.yaml and values.yaml together in a repo, as [doc](https://argoproj.github.io/argo-cd/user-guide/helm/#values-files) says. 

However, we want support for tracking two repos, one for helm chart (maybe a helm repo) and the other for values.yaml (a git repo).

# Motivation

We have established our only helm repo and saved our charts there. Currently, we are considering to use argo-cd to automatically deploy the charts to multiple clusters, and there are one values.yaml for each cluster. We don't want to move out the chart from our chart repo and store with the multiple values.yaml files.

We have tried the `--values-literal-file` option, but argo-cd seems to just insert the file into the application configuration, and therefore the changes of the values.yaml will not be tracked.

Besides, we are switching to the [helm registry](https://helm.sh/docs/topics/registries/), and the charts will be saved as OCI storage. According to [issue 3349](https://github.com/argoproj/argo-cd/issues/3349), this feature may be supported in version 1.7. At that time, the values.yaml will not be able to be stored with helm charts. So tracking two repos is requied.

# Proposal

Currently for the helm repo (not helm registry) and git repo, just add an option to track the chart repo (the original feature) and the values git repo. And users have to specify the location of the values.yaml for the app. 

When the chart repo or the values repo changed, mark the app as unsynced. And when re-deploy the app, the values.yaml should be re-downloaded.

**Comment by myspotontheweb** [comment]
Could I suggest an alternative that would require no ArgoCD modifications? In a nutshell, use an Argo CD "Application" object to record the helm settings for each deployment. 

Here's what we do:

**Helm Charts** 

Our Helm charts are stored alongside the source code. So, the release of each helm chart is managed in lock-step with the code it deploys.  This idea is not mandatory, could just as easily use a separate repo to manage the helm charts. 

**ArgoCD deployment**

Deployment configuration is managed in a separate repository, which leverages to the ArgoCD "Application" custom resource to record the helm settings:

 ```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-project1
  destination:
    namespace: demo-project1-namespace 
    server: https://kubernetes.default.svc
  source:
    path: chart
    repoURL: git@github.com:myorg/demo-app1.git
    targetRevision: master
    helm:
      values: |
        env:
           ONE: "1"
           TWO: "1"
           THREE: "1"
```

**Cluster bootstrapping**

All the application declarations, stored in our gitops repository can be deployed on a target cluster using the ["App of Apps" pattern](https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/). We have a directory of applications, for each region (could alternatively use branches).

```
REGION=US

argocd app create apps --repo git@github.com:myorg/gitops-repo.git \
                       --path apps/$REGION \
                       --dest-server https://kubernetes.default.svc \
                       --dest-namespace default \
                       --sync-policy automated \
                       --self-heal \
                       --auto-prune
```

**Comment by kenske** [comment]
| Could I suggest an alternative?

This seems like a workaround. Embedding configuration that could get pretty complicated inside another yaml file feels like a very fragile approach.

**Comment by sfatgc** [comment]
Hey all!

Is there any progress on this issue?

We wish to use third party helm charts from third party git repos, providing them with our value files, in the way like this: 
```
source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.1.3
    helm:
      version: 1.1.3
      valueFiles:
        - helm-values.yaml
```

So requirement to put value files to the same repo as chart looks like a huge functionality restriction.

And yes - I give +1 for the point, about embedding complicated values structure into application manifest file. It looks like really ugly workaround in that case.
