### ISSUE TITLE
Caching Application k8s resource drops fields

### ISSUE THREAD

**Issue by xvzf** [argoproj/argo-cd#3991]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`k8s.io/client-go/tools/cache` drops `spec.source.directory.jsonnet.libs` field when no other field in `spec.source.directory.jsonnet` is provided. Can be fixed by additionally setting e.g. `spec.source.directory.jsonnet.tlas`

**To Reproduce**

Non-working manifest:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: <some/path/to/app>
    repoURL: git@<any-repo>
    targetRevision: HEAD
    directory:
      jsonnet:
        libs:
        - 'vendor'
```

Working manifest:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: <some/path/to/app>
    repoURL: git@<any-repo>
    targetRevision: HEAD
    directory:
      jsonnet:
        libs:
        - 'vendor'
        tlas:
        - name: name
          value: test123
```

**Expected behavior**

Both manifests work

**Version**
(not latest master but no changes involved)
```shell
argocd: v1.5.4+36bade7
  BuildDate: 2020-05-05T19:02:56Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.0+561f308
  BuildDate: 2020-07-15T07:13:35Z
  GitCommit: 561f30815c628e562bb80b1d4beaaa39c8575e16
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

After configuring additional logging here, the dropping of the field can be observed: https://github.com/argoproj/argo-cd/blob/1a36fd178abf63b54b33e1ef47a25b8c9381a0e1/controller/appcontroller.go#L1355

```go
oldApp, oldOK := old.(*appv1.Application)
newApp, newOK := new.(*appv1.Application)
if oldOK && newOK && automatedSyncEnabled(oldApp, newApp) {
	log.WithField("application", newApp.Name).Info("Enabled automated sync")
	compareWith = CompareWithLatest.Pointer()
}
if oldOK && newOK {
	log.Infof("Cache Update: Old App %s", oldApp.String())
	log.Infof("Cache Update: New App %s", newApp.String())
}
```
