### ISSUE TITLE
Nightly scaledown

### ISSUE THREAD

**Issue by totemcaf** [argoproj/argo-cd#4038]
# Summary

We want a mechanism to scale down deployments (and perhaps StatefulSets) at night and to restore them at morning. Also weekends can a period to scale down.

Example:
   Monday through Friday, 8PM to 8PM -> 100% capacity
   Rest 0% (Monday to Friday 8PM to 8AM, Friday and Sunday all day).

# Motivation

We have clusters used for development and or testing. Those resources are used for 10 hours on working days so, they are no used at night or on weekends.

If we could turn off those resources at non working hours, we expect to reduce costs.

# Proposal

Add an entry to the Application object to describe the timetable of reduced resources.

Another is to add this information in new annotations for Deployment/StatefulSet that ArgoCD will read and execute.

**Comment by jessesuen** [comment]
This is out of scope of the goals of Argo CD. I believe I've heard of other projects already doing similar feature.

**Comment by jessesuen** [comment]
https://github.com/hjacobs/kube-downscaler

**Comment by asafhm** [comment]
> https://github.com/hjacobs/kube-downscaler

kube-downscaler is great, though if ArgoCD isn't tweaked to tolerate it, its changes will get overridden.
The following additions to ArgoCD's configmap (`argocd-cm`) will make sure ArgoCD won't override them:
```
resource.customizations.ignoreDifferences.all: |
  managedFieldsManagers:
    - pykube-ng # kube-downscaler's manager
  jsonPointers:
    - /spec/replicas
```
