### ISSUE TITLE
ArgoCD stuck on "Refresh"

### ISSUE THREAD

**Issue by razvanonet** [argoproj/argo-cd#4044]
hi! we are using ArgoCD v1.5.4+36bade7 to orchestrate our applications in our EKS k8s cluster, we've tried editing the argocd-server ConfigMap to make it ignore differences on deployments replicas, we've using documentation (https://argoproj.github.io/argo-cd/user-guide/diffing/). We changed the ConfigMap using:
```
data:
  resource.customizations: |
    apps/Deployment:
      ignoreDifferences: |
        jsonPointers:
        - /spec/replicas
```
after I redeployed the deployment using `kubectl rollout restart deployment argocd-server -n argocd` it worked, but it wasn't what we were expecting, and we removed the resource.customizations from the configmap and redeployed the argocd-server again. Now, after redeployment, every application is stuck on refresh, and I cannot see pods (in photo) but they are present in the cluster, as I can see them with kubectl get pods command... is this something that has to do with restarting the deployment? I can see the github repositories where we keep the charts but maybe we lost the connection with the cluster?
<img width="1253" alt="Screenshot 2020-08-04 at 13 33 58" src="https://user-images.githubusercontent.com/53819454/89298347-df0a6080-d66d-11ea-952d-965a130ba18a.png">
