### ISSUE TITLE
ComparisonError when creating an app with version range

### ISSUE THREAD

**Issue by jbapu** [argoproj/argo-cd#4047]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Creating an argocd application with the source as a Helm repository and the chart version as a valid semver range throws a ComparisonError (`Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = invalid revision '>=1.0.0 <2.0.0': improper constraint: >=1.0.0 <2.0.0`)

**To Reproduce**

Create an application for the postgresql Helm chart from bitnami using this manifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '>9.0.0 <9.1.2'
    chart: postgresql
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Expected behavior**

The application should be created without any errors even with version ranges for the Helm chart. The version range should resolve to 9.1.1. Interestingly, just having `>9.0.0` works. It seems like having a verbose semver range has an issue.
According to the [docs](https://argoproj.github.io/argo-cd/user-guide/tracking_strategies/#helm), version ranges are supported for an argocd application.

**Screenshots**

![image](https://user-images.githubusercontent.com/8113335/89316274-e0c22d00-d649-11ea-8acd-9b886effddb6.png)

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:43:39Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: windows/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```
