### ISSUE TITLE
Missing documentation about using helm repository as repo URL

### ISSUE THREAD

**Issue by yoshz** [argoproj/argo-cd#4059]
I just found out that it is also possible to use a Helm repository url instead of a Git repository url and add a `chart` config to let ArgoCD directly manage a public chart, for example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    chart: nginx-ingress
    targetRevision: 1.40.3
```

I only know this is possible by reading a blog of @AlexsJones because I can't find anything related in the documentation website.
Is this intended or got the documentation somewhere lost in the process?
I can imagine that first time users will struggle with this as well.

Is it also possible to add a reference list of all declarative configuration options to the documentation?
Right now I have to open the CRD's yaml files to list all configuration options.
