### ISSUE TITLE
Application source parameters in Git repository

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4083]
# Summary

Argo CD application CRD has a way to specify manifests management tool-specific parameters, such as images for kustomize, values for the helm, or parameters for Jsonnet. These "parameters" are currently stored in Application CRD. Argo CD should support specifying parameters in the Git repository in `.argocd-app.yaml` file along with resource manifests.

# Motivation

* With parameters overrides stored in CRD the Git repository no longer a single source of truth. That is why parameter overrides are recommended only for "dev" or "ephemeral" environments only. Storing the parameter overrides in the repository solves that problem and overrides can be used in all kinds of environments.

* This enables "write back" feature for https://github.com/argoproj-labs/argocd-image-updater . The updater can generate `.argocd-app.yaml` file and push it/create PR to the repository.

* The [git-files-discovery](https://github.com/argoproj-labs/applicationset/blob/master/examples/git-files-discovery.yaml) generator can use `.argocd-app.yaml` and auto-create applications.

# Proposal

Argo CD should check for `.argocd-app.yaml` in the specified application target path. If `.argocd-app.yaml` present then use parameters specified in the file. The `.argocd-app.yaml` is a YAML serialized application source (excluding `repo`, `url` and `targetRevision` fields) https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L20:
```yaml
    # kustomize specific config
    kustomize:
      # Optional kustomize version. Note: version must be configured in argocd-cm ConfigMap
      version: v3.5.4
      # Optional image name prefix
      namePrefix: prod-
      # Optional images passed to "kustomize edit set image".
      images:
      - gcr.io/heptio-images/ks-guestbook-demo:0.2
```
