### ISSUE TITLE
Helm ArgoCD does not take into account values cert-manager

### ISSUE THREAD

**Issue by isantospardo** [argoproj/argo-cd#4091]
**Describe the bug**:
Helm ArgoCD does not install cert-manager CRDs when specifying installCRDs: true

I have tried the following setup 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-cert-manager
    server: https://kubernetes.default.svc
  project: default
  # tried workaround https://github.com/argoproj/argo-cd/issues/2239
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: challenges.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: challenges.acme.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: issuers.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: orders.acme.cert-manager.io
  source:
    repoURL: {{ .Values.repoURL }}
    path: deploy/charts/cert-manager
    targetRevision: {{ .Values.targetRevision | quote }}
    helm:
      values: |
        ##
        ## Default values for openshift-cert-manager.
        ## This is a YAML-formatted file.
        ## Declare variables to be passed into your templates.
        ##
        global:
          leaderElection:
            # Override the namespace used to store the ConfigMap for leader election
            namespace: "openshift-cert-manager"
        installCRDs: true
        image:
          repository: "{{ .Values.controller.image }}"
          tag: "{{ .Values.controller.tag }}"
          pullPolicy: IfNotPresent

        # Override the namespace used to store DNS provider credentials etc. for ClusterIssuer
        # resources. This namespace will not be automatically created by the Helm chart.
        clusterResourceNamespace: "openshift-cert-manager"

        webhook:
          image:
            repository: "{{ .Values.webhook.image }}"
            tag: "{{ .Values.webhook.tag }}"
            pullPolicy: IfNotPresent

        cainjector:
          image:
            repository: "{{ .Values.cainjector.image }}"
            tag: "{{ .Values.cainjector.tag }}"
            pullPolicy: IfNotPresent
        ##
        ## End of additional cert-manager resource settings.
        ##
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
Also I have tried without `ignoreDifferences` but it seems the CRDs are never installed. I also see the following error in the cainjector pod
```
cert-manager/controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"Certificate\" in version \"cert-manager.io/v1alpha2\""  "kind"={"Group":"cert-manager.io","Kind":"Certificate"}
```

In any case, a workaround is to install the CRDs manually by executing:
```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.crds.yaml
```

Also, installing the helm chart manually it success and install all the CRDs corrently
```
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.16.1 \
  --set installCRDs=true
```

**Expected behaviour**:
The CRDs should be automatically installed when adding `installCRDs: true` in the values file

**Environment details:**:
- cert-manager version: v.0.16.1
- ArgoCD version: v1.6.1+1
- Install method: ArgoCD + helm

I am not sure it is a bug in ArgoCD, but as far as I can see the helm install command works as expected, so I guess specifying the values in an ArgoCD application should make it work also. Any help is appreciated.

/kind bug
