### ISSUE TITLE
Improve error message when excluding https:// from the URL in configmap 

### ISSUE THREAD

**Issue by mekstrem** [argoproj/argo-cd#4098]
# Summary
URL validation for argocd-server configmap and print a error message that the URL does not contain any protocol prefix.

# Motivation

When configuring Dex config for SSO in the configmap argocd-cm is it required to provide a URL to the ArgoCD instance. 

If this URL does not contain explicitly the HTTPS protocol every SSO login attempt will generate a `Failed to query provider "argocd-server.io/api/dex": 400 Bad Request: 400 Bad Request` message and in the argocd-server log `time="2020-08-14T12:19:03Z" level=info msg="Initializing OIDC provider (issuer: argocd-server.io/api/dex)"`. 

These two log entries are not good enough for debugging what is wrong when in fact it is required that the URL must be formatted like this:

Example 

BAD configmap 
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: argocd-server.io
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      name: SAML
      id: saml
      config:
        ssoURL: https://identity-provider/idp/profile/SAML2/POST/SSO
        entityIssuer: https://argocd-server.io/api/dex
        ca: /opt/cert/ca.pem
        usernameAttr: name
        emailAttr: email
        groupsAttr: groups
```

GOOD configmap 
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd-server.io
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      name: SAML
      id: saml
      config:
        ssoURL: https://identity-provider/idp/profile/SAML2/POST/SSO
        entityIssuer: https://argocd-server.io/api/dex
        ca: /opt/cert/ca.pem
        usernameAttr: name
        emailAttr: email
        groupsAttr: groups
```

# Proposal

When argocd-server loads the configmap `argocd-cm` do a validation of the URL (data.url) provided and check if it has a protocol prefixed or not and log accordingly.
