### ISSUE TITLE
Creating an application through the web UI and setting auto sync causes an erroneous config

### ISSUE THREAD

**Issue by jdfalk** [argoproj/argo-cd#4099]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Create an issue through the WebUI and select autosync, auto heal, prune. When you look at the yaml it has this:
```yaml
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
```

**To Reproduce**

Does not require repository.
1. Login to the argocd WebUI
1. Select new app 
1. Change sync policy to automatic
1. Select Prune Resources
1. Select Self Heal
1. Select Edit as yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ''
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  project: ''
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
```

**Expected behavior**

Normal yaml is generated without duplicate fields, it should look like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ''
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  project: ''
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Version**

```shell
argocd-server: v1.7.0+c387a27
  BuildDate: 2020-08-13T21:40:24Z
  GitCommit: c387a27f73d1e4beb6607257b630868c9b1b2441
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```
