### ISSUE TITLE
Document minimum and suggested system requirements

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj/argo-cd#4110]
It would be beneficial for operators if the documentation had some overview on minimum/suggested requirements in order to run ArgoCD

The following pages are good candidates for including this information 
https://argoproj.github.io/argo-cd/getting_started/
https://argoproj.github.io/argo-cd/operator-manual/

**Comment by trv-smaksym3** [comment]
@jessesuen @alexmt Our current OpenShift environment requires that we set limits and requests for memory and cpu.  Have these been documented anywhere?  Also, if not can you suggest requests and limits for cpu and memory as a starting point?  Thanks.

**Comment by tomaszdudek7** [comment]
So, could anybody (basing on previous experiences) join the discussion and at least specify them here on GitHub?

**Comment by jannfis** [comment]
It is not easy to come with a one-size-fits-all recommendation (and that's why we don't deliver resource limits by default), because the requirements vary on a lot of factors.

For the application controller, you need to consider at least the following variables:

* How many applications are being managed?
* How many clusters are being managed?
* How many APIs and resources are there in any of the managed clusters, and how big are those resources?
* What is the tuning configuration regarding status- and operation-processors, kube parallelism limits, etc?

For the repository server, there are also quite a few variables to consider:

* How big are your application manifests?
* What tooling do you use (e.g. Helm, Kustomize, custom plugins, ...)
* Did you scale out the repository server?
* Do you allow concurrent processing of manifests?

The list goes on. The most simple one to size would most likely be the API server.

I see the demand in the community for guidance here, maybe some kind of documentation with a starting point would indeed be a good idea.

For example, consider the application controller in my vanilla K8s test cluster with ~115 apps managed on a single cluster:

![image](https://user-images.githubusercontent.com/3942683/128820591-28462624-28ed-43ef-bd8e-d84531d5564d.png)

As you can see, the controller consumes not that much memory resources at all, and probably you could easily set the limit to 500Mi or 1Gi. But I've seen installations (e.g. on OCP) that manage far less applications, but have a memory spike at startup of up to 2Gi.

So I hope that gives a hint about how difficult it is to come up with a recommendation that work for some but is not falling on the feet of many people.

**Comment by u2m4c6** [comment]
Has there been any progress on this? It is hard to estimate the cost of running Argo CD without knowing minimum resources

**Comment by HariSekhon** [comment]
@kostis-codefresh thanks for the link

@u2m4c6 @chronicc @tomaszdudek7 I've sized and tuned my ArgoCD resources based on my Goldilocks recommendations - you can find my resource settings for my production ArgoCD with a dozen+ apps at my git repo below as well as Goldilocks deployment too, which is a handy thing to run for all your k8s resource sizing:

https://github.com/harisekhon/kubernetes-configs

**Comment by megabreit** [comment]
I was sent here from Slack because I was asking the question about the minimum kubernetes version for particular argocd versions. In particular I have Openshift 3.11 here and try to find out what argo cd version will work.
Any hints?

**Comment by CCOLLOT** [comment]
In case it helps, here are my ArgoCD installation CPU and Memory consumption graphs (~100 Apps, 4 clusters): 
![image](https://user-images.githubusercontent.com/52134228/158155869-5d0c0b82-9dbb-4bea-8ded-22aa7dcb180f.png)
![image](https://user-images.githubusercontent.com/52134228/158156074-25b6a39c-0685-4d0b-8aec-edea138a703c.png)

**Comment by ghostsquad** [comment]
I'd very much like to see a couple of tests run with more information so that some accurate estimates can be made:

- of applications, with each application containing XYZ resources
- does anything change if ArgoCD is running in 1 cluster (and hitting the API of others), or if you do other distributed architectures, such as `applicationSet` on 1 cluster, deploying applications to other clusters
- startup time vs letting it idle
- what happens if you have polling/syncing enabled (and at what frequency)
- what does the usage look like with users hitting the UI?

Planning on rolling this out soon, so if someone beats me this, that's great! Otherwise I can post numbers in the coming months when we have this rolled out.

**Comment by chris922** [comment]
I would also love to have reasonable defaults that should be enough for a smaller setup. I tried the commeted-out values from the values.yaml (https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml), but it seems that e. g. the repoServer requests/limits are far too low, even for a smaller setup with just ~15 apps in one cluster, no large Git repo to fetch etc.

**Comment by adamency** [comment]
@chris922 would you mind sharing your average CPU & memory consumption of the whole argocd namespace ? I believe your usecase is the most appropriate for a basic "minimal requirements" suggestion for the hardware requirements of running argocd, i.e. a single cluster serving about 10 apps via argo.

**Comment by chris922** [comment]
> @chris922 would you mind sharing your average CPU & memory consumption of the whole argocd namespace ? I believe your usecase is the most appropriate for a basic "minimal requirements" suggestion for the hardware requirements of running argocd, i.e. a single cluster serving about 10 apps via argo.

I can't really share the real consumption here, anyhow my setup grew a bit and now I am managing a bit more than 30 apps with the following config. If someone has any recommendations what can be improved here or is unsuitable, feel free :)

```yaml
controller:
  resources:
    limits:
      cpu: 1000m
      memory: 1536Mi
    requests:
      cpu: 500m
      memory: 1536Mi

dex:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 64Mi

server:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

repoServer:
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 1024Mi

applicationSet:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

notifications:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```
