### ISSUE TITLE
Add TargetRevision to argocd_app_info metric

### ISSUE THREAD

**Issue by simonc-613** [argoproj/argo-cd#4115]
# Summary

Currently the Prometheus `argocd_app_info` metric exports many fields of information about the applications, namespace, project, destination namespace/server, repo, health and sync status. The metric does not expose the `targetRevision`, this is a similar field to the other exported fields and could be added.

# Motivation

We have dashboards (mainly Grafana) powered by Prometheus metrics and as well as health and sync status it would be good to be able to display the targetRevision, which in our use-case it is usually the version of the container being deployed, without needing to add additional logic and datasources to the dashboard.

# Proposal

`argocd_app_info` should include a `target_revision` field which maps to the `targetRevision` field of the application.
This does of course increase the number of fields in the `argocd_app_info` metric and also with revision changes increases the number of metrics exported.
It may be worth considering #3549 as part of any works as this addresses missing/expiring metrics this proposal would only exacerbate.

**Comment by Cytram** [comment]
@simonc-613 don't know if this PR would be an idea for your proposal?
https://github.com/argoproj/argo-cd/pull/3869

**Comment by simonc-613** [comment]
Almost, I think for us `app.Status.Sync.ComparedTo.Source.TargetRevision` is the desired output as that would typically be a human readable version (although in production it may be a SHA anyway)

**Comment by jessesuen** [comment]
> This does of course increase the number of fields in the argocd_app_info metric and also with revision changes increases the number of metrics exported.

My main concern with this is that including targetRevision by default may increase the cardinality of the prometheus metrics a great deal. At the very least there needs to be a way to disable this, or opt-in on this.

**Comment by simonc-613** [comment]
I'll be the first to admit I'm only really an end user of Prometheus (and it's friends) so please do correct me if I'm wrong, but having a quick read up on cardinality, if the metrics for a previous revisions were to expire (see #3549 ) then does the cardinality increase cause only one (or two) revisions exist at a single time?

Opt-in isn't a bad shout though

**Comment by davidriskified** [comment]
Hi, I wonder if someone can review my change #5157 
We really have hard time dealing when target revision is changed and some how forgotten (when working a feature for application we set the target revision to side branch and when finishing usually move it to the main branch)
I'm sure many users face that issue.

Adding target revision as label to metrics (in that case its value can be unknown or any tag/branches) will have a low effect on Prometheus cardinality (since the nature of branch/tag name) and bring visibility.

**Comment by migueleliasweb** [comment]
This is being going for a while now. I've read the other PRs and the feedback seems to be that the cardinality is going to be impacted thus making Prometheus have a bad time.

I understand the issue. I really do. But at the same time it's just too easy to discard a change that can bring A LOT of visibility to how Applications are running on the cluster.

My proposal is to make this not enabled by default. So whoever wants to have this feature, can do so.

Any objections?

**Comment by migueleliasweb** [comment]
If this idea is accepted, I'm happy to contribute with a PR.

**Comment by migueleliasweb** [comment]
Hi @jessesuen , any thoughts on my idea?

**Comment by ebuildy** [comment]
@migueleliasweb I have done some works for this https://github.com/argoproj/argo-cd/pull/15143, labels cardinality can be controller via a command option 

```
command.Flags().StringSliceVar(&metricsAplicationRevisions, "metrics-application-revisions", env.StringsFromEnv("ARGOCD_METRICS_APP_REVISIONS", []string{"main", "master", "develop"}, ","), "List of Application revisions that will be added to the argocd_app_info metric")
```

**Comment by migueleliasweb** [comment]
@ebuildy Uh, I like that. Can't wait! :clap:

**Comment by migueleliasweb** [comment]
Any news?

**Comment by ebuildy** [comment]
> Any news?

PR is under review !

**Comment by mikejoh** [comment]
Shameless plug! ⚠️ 

I created [this project](https://github.com/mikejoh/argocd-extra-app-info-exporter) meanwhile we wait for the PR to merge. Tested in a proof-of-concept environment, can't say it's the _best_ way of approaching this but it _works_.

**Comment by trexx** [comment]
You can also do this by adding a custom resource metric to kube-state-metrics and then any fields in an application CR would be available as a metrics.
This likely provides the greatest flexibility at the cost of a little more configuration.

**Comment by scoplin** [comment]
Should we consider also the revision information currently in `Application` k8s status information?  In the case of a git source specifying `main` as the `targetRevision`, this would then be the commit.

It could also differ when sourcing a helm chart from an OCI repository if a flexible range is specified.

**Comment by crabique** [comment]
> If someone has a working `CustomResourceStateMetrics` configuration. The it is likely something that can be added to the codebase and/or helm chart.

@agaudreault here is a minimal KSM Helm values setup that works to provide an info source for the target revision that can be used to enrich `argocd_app_info`:
```yaml
kube-state-metrics:
  customResourceState:
    enabled: true
    config:
      spec:
        resources:
        - groupVersionKind:
            group: argoproj.io
            version: "*"
            kind: Application
          metricNamePrefix: ""
          metrics:
          - name: argocd_app_target_revision_info
            help: ArgoCD application target revision git ref
            each:
              type: Info
              info:
                labelsFromPath:
                  name: [metadata, name]
                  namespace: [metadata, namespace]
                  target_revision: [spec, source, targetRevision]
  rbac:
    extraRules:
    - apiGroups: [argoproj.io]
      resources: [applications]
      verbs: [list, watch]
```

As you can see, it's not a CR that KSM could discover dynamically, but rather an install-time parameter that ArgoCD can't really affect from the chart/code level. 

Although it's definitely better than nothing, it's rather a documentation recipe at best.
