### ISSUE TITLE
Manifests shown in UI don't match (apparently) with what is trying to be applied to the cluster

### ISSUE THREAD

**Issue by cyrus-mc** [argoproj/argo-cd#4120]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to sync deployment and receiving error

`error validating data: ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "enable" in io.k8s.api.core.v1.Probe`

Argo UI shows the following generated manifest (some data redacted): https://gist.github.com/cyrus-mc/021961e789bc3afabee6104ff95f991c

Which from a syntax perspective is correct. In fact I can take the manifest and apply it myself without issue. The error it is complaining about (unknown field "enable") isn't actually present in the generated manifest.

**To Reproduce**

Trying to sync a deployment manifest (paste above) results in the error shown. 

**Expected behavior**

If what Argo shows in the UI is what is actually synced to the cluster then it should apply without issue as from a syntax standpoint it is a valid k8s manifest.

**Version**

```shell
 Release v1.6.2
```

**Comment by jessesuen** [comment]
Could you share the manifest in git, and how it differs from the one presented in UI?

**Comment by cyrus-mc** [comment]
@jessesuen I think I have at least figured out what is going on. The manifests are actually generated via helm

I was able to SSH into the repo-server and manually call helm template and see that it is in-fact generating

```

 livenessProbe:
          enable: false                                                                                         
          failureThreshold: 3          
          httpGet:                                                                                                
            path: /healthcheck                                                                                    
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

```

Which is why the error is being thrown. The issue is that the UI, what it shows as the generated manifest does not list that field. Which is what threw me off because I was under the impression that what the UI is showing is the complete manifest. But it looks like maybe the UI is dropping invalid fields.
