### ISSUE TITLE
Allow specifying helm values as an object instead of string

### ISSUE THREAD

**Issue by FrederikNS** [argoproj/argo-cd#4121]
# Summary

I would like to be able to specify helm values in an ArgoCD Application by specifying a yaml object instead of a string. For example:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: some-helm-chart
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 0.0.1
    helm:
      releaseName: some-helm-chart
      values:                                # <- Notice there's no vertical bar on this line here!
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
          enabled: true
          hosts:
          - host: some-helm-chart.stage.example.org
            paths:
            - /
  destination:
    server: https://kubernetes.default.svc
    namespace: some-helm-chart
```

# Motivation

The reason I'm requesting this is that I'm trying to manage many helm charts distributed across many clusters and environments. Therefore I'm often deploying the same application but with some slight difference, often only differing on a DNS record or an annotation.

I would like to use Kustomize with overlays to manage these subtle differences. Currently when `values` is specified as a string, I have no choice but to repeat ALL the helm values again for a subtly different other application. Even the values that doesn't change between each app. If the values were specified as an object, the merge semantics in Kustomize would allow me to make slight changes, such as this Kustomize patch:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-helm-chart
  namespace: argocd
spec:
  source:
    helm:
      values:
        ingress:
          hosts:
          - host: some-helm-chart.prod.example.org
            paths:
            - /
  destination:
    server: https://kubernetes.default.svc
```

My current workaround is to build all these slightly differing apps into a helm chart with the helm templating to capture the differences, but this is quickly growing unwieldy and unreadable, with if-else statements strewn about everywhere.

# Proposal

I would like to propose that the `spec.source.helm.values` key can be specified as both a string and as an object.

If it is not possible to have multiple types for a given key, an alternative could be to implement a new key such as `spec.source.helm.valuesObject`. This would also clearly distinguish between using a string or an object. The original `spec.source.helm.values` could be kept for backwards compatibility, and new `spec.source.helm.valuesString` could also be introduced to make the distinction even clearer.
