### ISSUE TITLE
Since v1.7.0-rc1 volumeClaimTemplates are out of sync

### ISSUE THREAD

**Issue by niiku** [argoproj/argo-cd#4126]
**Describe the bug**

Since v1.7.0-rc1 `volumeClaimTemplates` in `StatefulSets` are out-of-sync.

**To Reproduce**

Deploy a `StatefulSet` using `volumeClaimTemplates`:

```
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
```
The k8s adds 
```
    - apiVersion: v1
      kind: PersistentVolumeClaim
```
which is detected as diff. 

**Expected behavior**
Argo CD ignores `apiVersion` and `kind` in `volumeClaimTemplates`

**Screenshots**

![image](https://user-images.githubusercontent.com/1416186/90683863-80e19e00-e267-11ea-94d9-65af2a14f51b.png)

**Version**
ArgoCD Version: v1.7.0-rc1
Kubernetes Version: v1.18.3
OKD Version: 4.5.0-0.okd-2020-07-14-153706-ga 

```shell
v1.7.0-rc1+4728412
```

**Logs**

```
time="2020-08-19T21:48:28Z" level=info msg="Refreshing app status (hard refresh requested), level (2)" application=harbor
time="2020-08-19T21:48:28Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2020-08-19T21:48:28Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: harbor)" application=harbor
```
(no other relevant log)

Edit:

It seems like other fields are affected with new diffing issues as well, like when `creationTimestamp: null` is in Git (seen at a `ServiceAccount` - ignored in v1.6.2), or when `app.conf: \|+` (diff says ` app.conf: |`) is used in a e.g. a `ConfigMap`

**Comment by niiku** [comment]
@alexmt There are other diff issues with v1.7.0 which were not present in v1.6.2:
![image](https://user-images.githubusercontent.com/1416186/91217955-9d268480-e718-11ea-8c05-5800cfe16a42.png)
![image](https://user-images.githubusercontent.com/1416186/91218160-f8587700-e718-11ea-959d-df7368760311.png)

**Comment by alexmt** [comment]
Thank you, @niiku ! 

Can you please provide more details about resources that have issues? The first one looks like ConfigMap, right? 
What are the group/kind of the second resource?

**Comment by niiku** [comment]
Sorry for the bad screenshots, @alexmt:
here's the yaml:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iptables-config
  creationTimestamp: null
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-core
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-6.0.8

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: core
data:
  app.conf: |+
    appname = Harbor
    runmode = dev
    enablegzip = true

    [dev]
    httpport = 8080
```
And if you want to have a look yourself:
https://argocd.baloise.dev/applications/iptables-config?node=%2FServiceAccount%2Fiptables-config%2Fiptables-config%2F0
https://argocd.baloise.dev/applications/harbor?node=%2FConfigMap%2Fharbor%2Fharbor-core%2F0
