### ISSUE TITLE
Allow use of GIT for values.yaml file definitions

### ISSUE THREAD

**Issue by dirtycajunrice** [argoproj/argo-cd#4129]
# Summary

Helm allows the use of external URLs for values.yaml files. The helm repository feature of argocd is really only good for authentication of private helm repositories and, if you like pain, manually defining each and every value in a line by line fashion in the UI/CLI

# Motivation

Currently, if we want to use a helm chart with a maintained values.yaml override file we currently have to create a "fake" umbrella chart in a git repo with completely irrelevant information outside of the dependancy that is the chart we actually care about. Then we can choose a/many values.yaml files. 

If git + helm were allowed, we would be able to keep version controlled values.yaml files without obfuscating them behind a fake umbrella chart.
### Fake umbrella chart (Chart.yaml)
```yaml
name: grafana       # Irrelevant
apiVersion: v2      # Irrelevant once we can choose helm version in 7.0
version: 1.0.0      # Irrelevant
dependencies:       # Irrelevant
  - name: grafana
    version: 5.5.5
    repository: https://kubernetes-charts.storage.googleapis.com
```
### values.yaml (version controlled in git)
```yaml
grafana:   # This is now indenting everything so that this values file is not useful outside of this umbrella
  fullnameOverride: grafana
  testFramework:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      external-dns.alpha.kubernetes.io/hostname: ""
    path: /grafana
  plugins:
    - grafana-piechart-panel
    - neocat-cal-heatmap-panel
    - natel-discrete-panel
    - vonage-status-panel
    - flant-statusmap-panel
  grafana.ini:
    server:
      serve_from_sub_path: true
    metrics:
      enabled: true
```
### App
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://some.k8s.url.com:6443
  project: default
  source:
    path: grafana
    repoURL: https://gitlab.domain.example/organization/apprepo.git
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}
```
## Proposal
Helm+GIT mix that allows specifying the helm chart and version in the application definition, and then using a git repository that can query for values files.
### New App
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://some.k8s.url.com:6443
  project: default
  source:
    path: grafana
    repoURL: https://gitlab.domain.example/organization/apprepo.git
    targetRevision: HEAD
    helm:
      chart: grafana
      repoURL: https://kubernetes-charts.storage.googleapis.com
      targetRevision: 5.5.5
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}
```
