### ISSUE TITLE
Still display OutOfSync in the UI when the changes are applied in argocd

### ISSUE THREAD

**Issue by anggao** [argoproj/argo-cd#4166]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ *] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ *] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

We upgraded to argo-cd v1.7 yesterday, I added a new entry to a configmap and committed the changes to a branch.
Then I switched argo-cd app to use that branch. I saw configmap got updated. but the status of the app still in OutOfSync.

**To Reproduce**
1. Add a new entry to an existing configmap
2. Commit changes to a branch
3. Change argo-cd app to use the branch
4. Check live manifest confirm changes are applied.
5. But still have OutOfSync in the UI.

**Expected behavior**
After changes applied, the app should be in sync status.

**Version**
v1.7

**Comment by alexmt** [comment]
Hello @anggao , Can you please provide more information to help to reproduce it? If you attach the diff it would help.

**Comment by anggao** [comment]
@alexmt  The change is really simple, like the following, I just added a new entry in the configmap for one of our existing app.

```
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization

  bases:
    - ../../base

  generatorOptions:
    disableNameSuffixHash: true
  configMapGenerator:
    - name: default-config
      literals:
+     - egress.endpoint="http://v-seservice.XXX.XXX.com"
      - model.log.prediction.percent="0.0"
      - model.log.feature.percent="0.0"
```
