### ISSUE TITLE
Feature request: Latest discovered version in Application resource

### ISSUE THREAD

**Issue by cubic3d** [argoproj/argo-cd#4167]
# Summary

It would be great if Argo CD could attach the latest version discovered of an application to the `Application` custom resource itself. This would allow to to monitor possible application updates without using wildcard semver version definitions in the application and notify on available updates in repositories like Helm.

# Motivation

Using applications with a specific `targetRevision`:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: metallb
    targetRevision: 0.1.21
    helm:
      values: |-
        ...
```
does not allow to easily track new versions on upstream. Even with a `targetRevision` like `0.1.*` one would miss the minor releases and have to track the repositories manually.

# Proposal

Having a latest discovered version field in the `Application` custom resource would allow to check if it differs from the current synced or targeted with something like kubewatch and notify about possible updates. Or probably integrate with Prometheus / Alertmanager / Grafana.
