### ISSUE TITLE
Documentation: RBAC Documentation should be clearer about deny actions

### ISSUE THREAD

**Issue by jdfalk** [argoproj/argo-cd#4192]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.
^ NA as this is a documentation bug

**Describe the bug**

The current RBAC documentation does not clearly state if a deny rule overrides a allow rule. For instance, if I have this RBAC policy, does the allow or the deny take precedence? 
```
        p, role:qa, projects, get, *, allow
        p, role:qa, projects, get, production, deny
```

In addition, does order matter? 
```
        p, role:qa, projects, get, production, deny
        p, role:qa, projects, get, *, allow
```

None of that is well documented in the RBAC documentation. Something I think would be a critical area for several organizations.

**To Reproduce**
Read https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md

**Expected behavior**

A clear and concise description of what should happen in these situations, and additional examples.

**Comment by pavanfhw** [comment]
Can someone with knowledge or a successful experience comment on this? In my case for example I can't deny get access to apps/projects in a role. The user with the role can see all apps and projects.

**Comment by doctornkz** [comment]
We are having the same issue and even worse - our SSO applies too many groups to user automatically, so it's very impossible to implement `deny` mechanic there - default access will be leaked again with every new group. Could someone fix that IRL ?

**Comment by iamcryptoki** [comment]
@pavanfhw We had the same issue but figured it out.
You have to disable default policy by setting `policy.default` with the role `role: ''`.

The configuration below does not work:
```yml
policy.default: role:readonly
policy.csv: |
  p, role:developers, applications, *, */*, allow
  p, role:developers, applications, *, production/*, deny
```
Users with the role `developers` can still view applications in the `production` project.

The configuration below works:
```yml
policy.default: role:''
policy.csv: |
  p, role:developers, applications, *, */*, allow
  p, role:developers, applications, *, production/*, deny
```
Users with the role `developers` can no longer see applications in the `production` project.
