### ISSUE TITLE
System-level resource customization pattern matching

### ISSUE THREAD

**Issue by albertrdixon** [argoproj/argo-cd#4194]
# Summary

I would like to be able to specify arbitrary fields expressed as json pointers to be ignored across all resource types at the system level.

# Motivation

The specific field I have in mind right now is `/metadata/creationTimestamp`. In fact most of the use cases I can think of are in the `/metadata` block.

This seems to have been solved in the past by adding a `ignore...` option to `resource.compareoptions`. I don't think that's sustainable as there's no way to fit all use cases.

I have not found any issues or documentation around this type of use case, so I assume it does not exist. Do not hesitate to let me know I just missed it!

# Proposal

Allow simple glob pattern matching - or a special keyword like `all` - in `resource.customizations` so I could do something like below:

```yaml
resource.customizations: |
  "*":
    ignoreDifferences: |
      jsonPointers: [/metadata/creationTimestamp]
```

**Comment by jessesuen** [comment]
I agree this might be useful, but there may be some difficulty implementing this when there are multiple matches and the config needs to be merged somehow.

**Comment by darshanime** [comment]
This can be done now too with `resource.customizations` using glob matching implemented in https://github.com/argoproj/argo-cd/pull/3754. 

Use `"*/*"` to match all groups and kinds. 

```
  resource.customizations: |
    "*/*":
      ignoreDifferences: |
        jsonPointers:
        - /metadata/creationTimestamp
```
