### ISSUE TITLE
Error: Repo-Server GPG keys already initialized, can't initialize again.

### ISSUE THREAD

**Issue by hamza-tumturk** [argoproj/argo-cd#4214]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading ArgoCD from version `1.6.0` to `1.7.2` the `argocd-repo-server` failed with the message that the GPG keys were already initialized, and can't initialize again.

**To Reproduce**

Let ArgoCD upgrade itself from version `1.6.0` to `1.7.2` sourcing from https://raw.githubusercontent.com/argoproj/argo-cd/v1.7.2/manifests/install.yaml

**Expected behavior**

Reuse already initialized GPG key from the previous deployment.

**Version**

```shell
v1.7.2+c342d3f
```

**Logs**

```
ARGOCD-REPO-SERVER
level=info msg="Initializing GnuPG keyring at /app/config/gpg/keys"
level=fatal msg="ARGOCD_GNUPGHOME at /app/config/gpg/keys already initialized, can't initialize again."
```

**Comment by jannfis** [comment]
Hm, this is probably due to the change #4136, which introduced `emptyDir` mount for `/app/config/gpg/keys`. 

If `argocd-repo-server` container within the pod crashes and gets restarted, the path will not be emptied and the repo server will choke on it.

**Comment by jannfis** [comment]
This should happen rarely (only when the repo server crashes inside the pod and the container is restarted), but I will think about a proper fix and submit a PR soon. I need to think about the implications of when the key ring is re-used vs. clean up of the directory in the initialization sequence.

As a workaround, the pod itself can be restarted, i.e. by either deleting it and having K8s recreate it or by issuing a `kubectl rollout restart argocd-repo-server`.

**Comment by hamza-tumturk** [comment]
@jannfis thanks for the workaround suggestion. After restarting the deployment for the repo-server, it initialised the GPG key successfully but kept failed on the liveness probe. For now, I rolled it back to v1.6.0 which sorted itself. I'm going to try upgrading to version 1.7.3 again.

**Comment by hamza-tumturk** [comment]
I had added a liveness probe patch to the `argocd-repo-server` deployment on `v1.7.3`. It seems that caused the liveness probe to fail. Does that even make sense to add it this way?
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
```
