### ISSUE TITLE
redirectURI for OpenShift Dex connectors is not correctly set by argocd-util

### ISSUE THREAD

**Issue by chrisob** [argoproj/argo-cd#4221]
**Describe the bug**

When configuring OpenShift as a Dex connector for SSO, if the `redirectURI` is left out of the base Dex config, `argocd-util` will not add the `redirectURI` based on the URL found in `argocd-cm`. This results in failed SSO logins.

I believe the culprit lies here: https://github.com/argoproj/argo-cd/blob/v1.7.2/util/dex/config.go#L137

**To Reproduce**

1. Configure an OAuth client in OpenShift as described here: https://github.com/dexidp/dex/blob/master/Documentation/connectors/openshift.md
1. Configure Argo CD to use OpenShift as an OAuth provider, leaving out the `redirectURI`:
    ```yaml
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: argocd-cm
      namespace: argocd
    data:
      dex.config: |
        connectors:
        - config:
            clientID: system:serviceaccount:argocd:argocd-dex-server
            clientSecret: $dex.openshift.clientSecret
            insecureCA: true
            issuer: https://kubernetes.default.svc
            # If this line is uncommented, logins will work:
            # redirectURI: https://argocd-server-argocd.apps.my-cluster-dns.com/api/dex/callback
          id: openshift
          name: OpenShift
          type: openshift
    ```
1. Attempt to login using SSO, which fails

**Expected behavior**

I would expect `argocd-util` to set the `redirectURI` value to argo-cm's `.data.url + /api/dex/callback`, resulting in successful SSO logins using OpenShift as an OAuth provider.

**Version**
From inside a dex pod:
```shell
$ /shared/argocd-util version
argocd-util: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:35:20Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Example of a failed SSO login due to Dex's misconfigured OpenShift connector:
```
argocd/argocd-dex-server-658788d579-bbkwv[dex]: time="2020-09-01T14:37:17Z" level=error msg="Connector \"openshift\" returned error when creating callback: expected callback URL \"https://argocd-server-argocd.apps.my-cluster-dns.com/api/dex/callback\" did not match the URL in the config \"\""
```
