### ISSUE TITLE
ignoreDifferences in namespaceSelector in Webhook

### ISSUE THREAD

**Issue by ramanNarasimhan77** [argoproj/argo-cd#4276]
Hello,
I am trying to use `argoCD` to deploy `seldon-core-operator`

`seldon-core-operator` installs a `mutatingwebhookconfiguration` and a `validatingwebhookconfiguration` 

After installation, the live manifest has an additional namespace selector as shown below

<img width="1229" alt="Screenshot 2020-09-07 at 12 16 59 PM" src="https://user-images.githubusercontent.com/52691361/92356692-228c3a80-f104-11ea-821e-75b19f53e25b.png">

The path to the `namespaceSelector` as validated in the live `mutatingwebhookconfiguration` using `yq` is

```shell
$ cat liveMutatingWebhookConfiguration.yaml | yq r - "webhooks[0].namespaceSelector.matchExpressions[1]"
key: control-plane
operator: DoesNotExist
```

So I tried adding the following `ignoreDifferences` spec

```yaml
- group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: seldon-mutating-webhook-configuration-{{ .Values.global.spec.destination.namespace }}
    namespace: {{ .Values.global.spec.destination.namespace }}
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/0/namespaceSelector/matchExpressions/1
```

However, this does not seem to resolve the difference and `argoCD` still reports the `namespaceSelector` as different and shows the `webhookconfigurations` as OutOfSync

<img width="315" alt="Screenshot 2020-09-07 at 12 21 49 PM" src="https://user-images.githubusercontent.com/52691361/92357015-bcec7e00-f104-11ea-842e-c4de23654503.png">

How can I fix this?

**Comment by jessesuen** [comment]
Suggestions:
1. Can you run the troubleshooting steps under "Diffing Customization" in https://argoproj.github.io/argo-cd/operator-manual/troubleshooting/ and paste the output?

2.  Does removing the `1` under `/webhooks/0/namespaceSelector/matchExpressions` work?

**Comment by ramanNarasimhan77** [comment]
@jessesuen 
I tried Suggestion#2, it did not work.
I will try Suggestion#1 and let you know.

I am doing this installation on `azure aks` and looks like the extra namespace selector is added by `aks`

**Comment by ramanNarasimhan77** [comment]
@jessesuen  is there a way to debug `diffing customizations` defined in an application.

Currently I have written the ignoreDifferences spec as part of my `application spec`
Looks like to use the steps from the `troubleshooting guide` I have to move them to the `argocd-cm configmap`

I will try this out and let you know

**Comment by FarnazZ** [comment]
I have a same issue, I tested both of the ways you mentioned, with `/webhooks/0/clientConfig/caBundle`, but when I just add `/webhooks` it starts working. Do you have any solution to prevent ignoring all of the webhooks instead of caBundle?

**Comment by BobClaerhout** [comment]
We are experiencing the same issue. Adding `/webhooks` doesn't work either.
We are configuring the ignore differences via the [Application Level Configuration](https://argoproj.github.io/argo-cd/user-guide/diffing/#application-level-configuration). 
Any updates on this?

**Comment by vortarian** [comment]
I used:
`    - kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/.../clientConfig/caBundle`

**Comment by marcgascon** [comment]
In my case I have an app of apps deployment in ArgoCD.

The System Level Diffing configuration that is documented in the ArgoCD docs worked fine for the parent application that is not out-of-sync anymore. But unfortunately this is not the case for the application that the MutatingWebhookConfiguration belongs to.

Does this mean that I have to put this ignoreDifferences on every application that has the Mutating/ValidatingWebhookConfiguration ?

**Comment by FarnazZ** [comment]
> - /webhooks/1/clientConfig/caBundle
>         - /webhooks/2/clientConfig/caBundle
>         - /webhooks/3/clientConfig/caBundle
>         - /webhooks/4/clientConfig/caBundle
>         - /webhooks/5/clientConfig/caBundle
>         - /webhooks/6/clientConfig/caBundle
>         - /webhooks/7/clientConfig/caBundle

Thanks @vortarian, it works for me.

**Comment by FarnazZ** [comment]
> In my case I have an app of apps deployment in ArgoCD.
> 
> The System Level Diffing configuration that is documented in the ArgoCD docs worked fine for the parent application that is not out-of-sync anymore. But unfortunately this is not the case for the application that the MutatingWebhookConfiguration belongs to.
> 
> Does this mean that I have to put this ignoreDifferences on every application that has the Mutating/ValidatingWebhookConfiguration ?

I think because you should put a line for each of the caBundle you have in your webhooks, different apps may have different number of caBundles and it won't work for all of your apps.

But you can test this, for example you have 3 apps with different number of cabundle but the biggest number of cabundle you have is 8 and you can put 8 lines (0-7) in your `jsonPointers` to ignore all of them in your parent application.

**Comment by fdebuire** [comment]
Got into the same issue with `cert-manager` on AKS (https://github.com/Azure/AKS/issues/1771) and this is what worked for me:
```
ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
    jsonPointers:
      - /webhooks/0/namespaceSelector/matchExpressions/2
```
However when I tried to narrow to the specific resource by adding the optional namespace filter it doesn't work anymore.

**Comment by jschnurr** [comment]
I had the same problem with `cert-manager` on `AKS`, and tweaked @fdebuire 's suggestion to use `jqPathExpressions`, which also worked:

```yaml
 ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
 ```

**Comment by ams0** [comment]
@mateustanaka True, `jqPathExpressions` is not available on `v1alpha`, I solved the `cert-manager` on AKS constant out-of-sync problem with this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jsonPointers:
        - /webhooks/0/namespaceSelector/matchExpressions/2
```

I'm on v2.1.0+d0b2d55 deployed with the Helm chart of version argo-cd-3.13.2

**Comment by jschnurr** [comment]
I'm on `Argo v2.1.1`  deployed with `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.1/manifests/install.yaml`, and the following manifest works for me using the `argoproj.io/v1alpha1` apiVersion.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.5.3
    helm:
      values: |
        installCRDs: true
        ingressShim:
          defaultIssuerName: letsencrypt
          defaultIssuerKind: ClusterIssuer
        nodeSelector:
          kubernetes.io/os: linux
  # https://github.com/argoproj/argo-cd/issues/4276
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ```

**Comment by rdgacarvalho** [comment]
I trying to apply the above example on **argo-cd-3.10.0** and I am getting the following error.

```
error: error validating "argocd/application.yaml": error validating data: [ValidationError(Application.spec.ignoreDifferences[0]): unknown field "jqPathExpressions" in io.argoproj.v1alpha1.Application.spec.ignoreDifferences, ValidationError(Application.spec.ignoreDifferences[0]): missing required field "jsonPointers" in io.argoproj.v1alpha1.Application.spec.ignoreDifferences]; if you choose to ignore these errors, turn validation off with --validate=false
```

Kubernetes-1.20.0

**Comment by punkerpunker** [comment]
> I used:
> 
> ```
>     - kind: ValidatingWebhookConfiguration
>       group: admissionregistration.k8s.io
>       jsonPointers:
>         - /webhooks/0/clientConfig/caBundle
>         - /webhooks/1/clientConfig/caBundle
>         - /webhooks/2/clientConfig/caBundle
>         - /webhooks/3/clientConfig/caBundle
>         - /webhooks/4/clientConfig/caBundle
>         - /webhooks/5/clientConfig/caBundle
>         - /webhooks/6/clientConfig/caBundle
>         - /webhooks/7/clientConfig/caBundle
> ```

Seems like could be solved with one-liner here: 
```
-  kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
```

**Comment by SafeEval** [comment]
If you find your way here while trying to use ArgoCD to configure Istio, and are getting an `OutOfSync` error on `istiod-default-validator`, the following configuration in an ArgoCD app that installs the `istio/base` Helm chart will help:

```
spec:
  ...
  ignoreDifferences:     
  - group: admissionregistration.k8s.io                                                              
    kind: ValidatingWebhookConfiguration
    jsonPointers:                                                                                    
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/0/failurePolicy
```

**Comment by ramanNarasimhan77** [comment]
Closing this issue as jqPathExpressions seems to work well.

**Comment by jimangel** [comment]
I ran into this issue again playing with Argo v2.9 (v2.9.0-rc2) that started [failing on this solution](https://github.com/argoproj/argo-cd/issues/4276#issuecomment-1279858247) due to an "invalid patch."I couldn't find a format that would make ArgoCD happy, but ultimately moving it to the declarative config map (https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/) did the trick. For reference:

```
# apply a similar configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/0/failurePolicy
    jqPathExpressions:
    - .webhooks[0].clientConfig.caBundle
    - .webhooks[0].failurePolicy

# restart argocd
kubectl -n argocd rollout restart deployment argocd-applicationset-controller argocd-notifications-controller argocd-redis argocd-repo-server argocd-server
```

Inspiration: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#system-level-configuration

**Comment by Vinaum8** [comment]
I used these values in argocd's ignore differences.

```
- group: admissionregistration.k8s.io
     kind: ValidatingWebhookConfiguration
       jqPathExpressions:
         - .webhooks[]?.clientConfig.caBundle
         - .webhooks[]?.failurePolicy
         - .webhooks[]?.namespaceSelector
```
