### ISSUE TITLE
Deep-links to logging facility etc

### ISSUE THREAD

**Issue by boniek83** [argoproj/argo-cd#4281]
# Summary

Argo Workflow has ability to add custom links to pods or workflow with templated variables. It is really useful to dynamically generate links to logging system (eg. Granafa Loki instance) and massively eases debugging.

# Motivation

Integrate with external tools in company such as logging or opsec. Links right in the ArgoCD lessen operational burden - no additional documentation where to find such tools is necessary. Introducing new tools globally in company is really easy.

# Proposal

Argo Workflows already implements this. At least pods and whole project should have custom links.

**Comment by jessesuen** [comment]
There's an undocumented feature to add "info items" to an application. It's spec looks like:

```yaml
project: argo-rollouts
source:
  repoURL: 'https://REDACTED'
  path: argo-rollouts
destination:
  server: https://REDACTED
  namespace: argo-rollouts
info:
  - name: splunk-logs
    value: >-
      https://REDACTED
```

In the UI it then shows up in the details page:

![image](https://user-images.githubusercontent.com/12677113/92527246-95b4b000-f1db-11ea-86d1-84bb58f43b81.png)
