### ISSUE TITLE
App destination displayed as "in-cluster" when destination cluster defined by name

### ISSUE THREAD

**Issue by savealive** [argoproj/argo-cd#4291]
**Describe the bug**

When ArgoCD app defined with destination cluster by NAME then it's displayed in UI with destination "in-cluster"
Applicable only for compact display mode. In "tiles" mode destination is shown correctly. 

Example with two identical apps deployed into the same cluster. Nginx-prod destination defined by "name", nginx app defined by "server", Nginx-prod app displayed as "in-cluster".
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/12967071/92671459-f4f9e980-f2db-11ea-83b2-031f518327a9.png">

In tiles mode it's better, however it'd rather see server alias instead server URL for app "nginx" as it's displayed in compact mode. Nginx-prod app destination displayed correctly.
<img width="840" alt="image" src="https://user-images.githubusercontent.com/12967071/92671572-3e4a3900-f2dc-11ea-91d0-d367a880f8fc.png">

**To Reproduce**

Deploy an app with CRD like following (with `.spec.destination.name`)
```
# Source: umbrella-app/charts/nginx-prod/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: rhythm-useast1-cluster1
    namespace: test123-prod
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.2.1
    chart: nginx
    helm:
      valueFiles:
        - values.yaml
      values: |-
        service:
          type: ClusterIP
  project: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
try to deploy the same app but with `.spec.destination.server` instead of `.spec.destination.name` and see the difference in UI.

**Expected behavior**
Application destination cluster name displayed correctly.

**Version**

```shell
argocd-server: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:45:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```
