### ISSUE TITLE
Not delete previous `Job` with `BeforeHookCreation` delete policy

### ISSUE THREAD

**Issue by posquit0** [argoproj/argo-cd#4295]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD doesn't delete previous jobs after succeeding Sync operation, although there is an annotation `argocd.argoproj.io/hook-delete-policy: BeforeHookCreation`.

**To Reproduce**

```yaml
# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-test
  generateName: app-job-test-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: docker/whalesay
        command: [cowsay]
        args: ["Hello, World!"]
      restartPolicy: Never
  backoffLimit: 2
```

```yaml
# deployment.yaml
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
```

```yaml
# patches/job-generate-name.yaml
- op: remove
  path: /metadata/name
```

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kasa-exchange-dev
commonLabels:
  stage: dev
resources:
- deployment.yaml
- job.yaml
patchesJson6902:
- path: patches/job-generate-name.yaml
  target:
    group: batch
    version: v1
    kind: Job
    name: app-job-test
```

```yaml
# app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-test
  # Add a this finalizer ONLY if you want these to cascade delete.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: xxxxxxx

  source:
    repoURL: https://github.com/xxxxx/xxxxxx
    targetRevision: job-test
    path: xxxxx/test

    kustomize:
      version: v2.0.3
      # Optional image name prefix
      # namePrefix: prod-
      # Optional images passed to "kustomize edit set image".
      # images:
      # - gcr.io/heptio-images/ks-guestbook-demo:0.2

  destination:
    server: https://kubernetes.default.svc
    namespace: xxxxxx

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    # Disables resource validation (equivalent to 'kubectl apply --validate=true')
    - Validate=false
    # Ensures that namespace specified as the application destination exists in the destination cluster.
    - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences at the specified json pointers
  # ignoreDifferences:
  # - group: apps
  #   kind: Deployment
  #   jsonPointers:
  #   - /spec/replicas
```

**Expected behavior**

ArgoCD should delete previous jobs after succeeding Sync

**Screenshots**

![image](https://user-images.githubusercontent.com/1484002/92690795-8de04180-f37c-11ea-96f6-af36073d3950.png)

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:46:53Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:45:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
Paste any relevant application logs here.
```
