### ISSUE TITLE
Access denied when AppProject name is not equal to Application name

### ISSUE THREAD

**Issue by JaveriaK** [argoproj/argo-cd#4302]
**Describe the bug**

Group users cannot access thier applications when the Argo Application name is not the same as the AppProject it references.

**To Reproduce**

We bind an okta group a to Role:

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: infra-foundation-user-access
  namespace: infra-foundation
subjects:
  - kind: Group
    name: teleport-k8s-infrafoundation
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-foundation-user-access
```

Application manifest:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-configs
  namespace: argocd
spec:
  project: infra-foundation
  source:
...
...
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-foundation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

and in the argo rbac settings:

```yaml
    p, role:infrafoundation, applications, get, infra-configs/*, allow
    p, role:infrafoundation, applications, sync, infra-configs/*, allow

    g, teleport-k8s-infrafoundation, role:infrafoundation
```

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
The argo server logs generate the following errors only:

```shell
time="2020-09-10T01:33:34Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: applications, get, infra-foundation/infra-configs" grpc.code=PermissionDenied grpc.method=Get grpc.service=application.ApplicationService grpc.start_time="2020-09-10T01:33:34Z" grpc.time_ms=13.929 span.kind=server system=grpc
time="2020-09-10T01:33:35Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: applications, get, infra-foundation/infra-configs" grpc.code=PermissionDenied grpc.method=Get grpc.service=application.ApplicationService grpc.start_time="2020-09-10T01:33:35Z" grpc.time_ms=14.132 span.kind=server system=grpc
time="2020-09-10T01:34:25Z" level=info msg="client watch grpc context closed" application=infra-configs
```
