### ISSUE TITLE
UI shows resource for pruning even when app is healthy and synced

### ISSUE THREAD

**Issue by xsreality** [argoproj/argo-cd#4309]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

**Describe the bug**
When a resource created by another tool (like Strimzi) is annotated with below annotations, the application is healthy and synced but the UI shows marks the resource for pruning.

```
argocd.argoproj.io/compare-options: IgnoreExtraneous
argocd.argoproj.io/sync-options: Prune=false
```

**To Reproduce**

1. Deploy a resource managed by some other tool (like Strimzi Kafka cluster)
2. Add above annotations on the resource.
3. Modify some parameter that forces other tool (Strimzi) to modify the resource.
4. UI would mark the resource for pruning.

**Expected behavior**

UI should show it as green and synced.

**Screenshots**

![image](https://user-images.githubusercontent.com/4991449/92941334-87bb9500-f450-11ea-94ae-979085caffea.png)

**Version**

```shell
❯ argocd version
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:46:53Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

The issue https://github.com/argoproj/argo-cd/issues/2427 is similar to what is described here.

**Comment by jessesuen** [comment]
This is actually the intended behavior. We will still mark the resource OutOfSync, but do not allow that condition to contribute to the overall Sync status of the application. See docs:

https://argoproj.github.io/argo-cd/user-guide/compare-options/

**Comment by jessesuen** [comment]
One fix we should make is to *not* mark the resource as "required pruning"

**Comment by xsreality** [comment]
@jessesuen Yes that was the intention with this issue to not display the resource as "required pruning" in UI. 

Would it make sense to somehow display the resource as "Extraneous" instead of just OutOfSync to distinguish from other resources that are _actually_ OutOfSync? That way these resources can be ignored at a glance instead of checking why they are OutOfSync.

**Comment by jessesuen** [comment]
I don't think we should introduce a new status, but I do think it would be nice to distinguish somehow in the UI extraneous resources differently than OutOfSync. I think this can be a UI feature.

**Comment by schmidtjohannes** [comment]
Hi, I am working with version 2.3.3 and it looks like the annotations are not working anymore.
```
argocd.argoproj.io/compare-options: IgnoreExtraneous
argocd.argoproj.io/sync-options: Prune=false
```
I added them to a configmap:

```
apiVersion: v1
data:
  my.conf: |
    # some comment
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    argocd.argoproj.io/instance: app-dev
    name: my-config
  name: my-config
  namespace: my-namespace
```

When I change the configmap , the app shows that it is out of sync immediately

I also added the following to my app manifest through the UI but it is not even saving it (without error)
```
          ignoreDifferences:
            - group: ""
              kind: ConfigMap
              name: my-config
              namespace: my-namespace
              jsonPointers:
                - /data
```
I saw this here as a workaround, but I am not sure if this is still valid


Can somebody confirm, that this should work on 2.3.3? Or perhaps I miss something in my config?

**Comment by schmidtjohannes** [comment]
the fix is:
```
          ignoreDifferences:
            enabled: true
            config:
              - group: ""
                kind: ConfigMap
                name: my-config
                namespace: my-namespace
                jsonPointers:
                  - /data
```
