### ISSUE TITLE
Persistent GPG Server Key

### ISSUE THREAD

**Issue by kvaps** [argoproj/argo-cd#4316]
# Summary

Currently Argo CD generating new gpg key pair each start:

https://github.com/argoproj/argo-cd/blob/ea9b0b35d0a2f996066b2d41315ff575d38eadc9/util/gpg/gpg.go#L256-L267

Right now this key is not much useful because changing each restart.
But if it would be persistent, it would allow to use it to simple decrypt the repository using [git-crypt](https://github.com/AGWA/git-crypt) or [sops](https://github.com/mozilla/sops).

# Motivation

Simple and native Git-based encryption for the Argo CD.

Example use case:

- Initial ArgoCD installation generates gpg-server key.
- User is logging in to ArgoCD interface and able to download public key for this server
- User encrypting his Git repository using for this gpg-key.
- During the deployment ArgoCD able to decrypt the repository using it's gpg key.

eg. simple command `git-crypt unlock` is enough after fetching

# Proposal

-   Initial ArgoCD installation should generate persistent gpg-server key if another one is not existing yet and write it to `argocd-gpg-keys-secret` secret.

-   This key should be stored in specific secreand mounted to argocd-repo-server container for automatic loading during the startup (this is already implemented):
     ```yaml
      volumes:
      - name: gpg-keys
        projected:
          sources:
          - secret:
            name: argocd-gpg-keys-secret
          - configMap:
            name: argocd-gpg-keys-cm
      ```

-   Additionally an opportunity for adding additional persistent gpg keys in Argo CD interface might be implemented.
