### ISSUE TITLE
Implementing JsonPath for diffing customization

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [argoproj/argo-cd#4320]
# Summary

Right now Diffing Customization uses `jsonPointers` to indicate the patch to be ignored. This is sufficient when the tree contains non array objects. But, if an array is present, then it becomes infeasible to query the element to be ignored by array index. As such, support for `jsonPath`, which has the capability of making deeper queries, would go a long way.

# Motivation

Cert Manager creates a validatingwebhookconfiguration which when deployed on AKS (maybe for other cloud providers too) gets modified.

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  ...
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    ...
  failurePolicy: Fail
  matchPolicy: Exact
  name: webhook.cert-manager.io
  namespaceSelector:
    matchExpressions:
    - key: cert-manager.io/disable-validation
      operator: NotIn
      values:
      - "true"
    - key: name
      operator: NotIn
      values:
      - cert-manager
    - key: control-plane
      operator: DoesNotExist
...
```
In the above yaml, the array element with `key: control-plane` was added by AKS and as such I want ArgoCD to ignore that specific element. Having JsonPath support, I could do something like `$.webhooks[?(@.name == webhook.cert-manager.io)].namespaceSelector.matchExpressions[?(@.key == control-plane)]`. I believe this is not currently possible in jsonPointers.

# Proposal

Implementing the jsonPath spec in addition to jsonPointer should fix this.

**Comment by jessesuen** [comment]
I think this is a good idea. There's room in the spec to allow for jsonPath as an alternative.

**Comment by chetan-rns** [comment]
Hi @jessesuen , is this applicable to [system-level configuratio](https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration)n as well? I'm happy to work on it

**Comment by SayakMukhopadhyay** [comment]
In my opinion, it should also apply there.

**Comment by buehlmann** [comment]
This would be a **great** improvement to use JSONPath! :heart_eyes: I ran into this one several times when trying to ignore differences inside an element of an array. For example `containers` inside Deployments or sts is quite common.. Accessing the array by index is not an option because it's non-deterministic.

**Comment by fuesec** [comment]
would love to see this feature

**Comment by jutley** [comment]
I would really love to have this feature. Like many others, I just ran into a scenario where I would like to ignore a certain value that gets added to a list via a mutation webhook.

I tried to look for a jsonpatch library for golang, but struggled to find anything that would make this easy to implement.

Perhaps it makes sense to fork the Kubernetes implementation to add support for returning matching paths (as opposed to just the values). Then ArgoCD can create a JSON patch to remove those paths before diffing.

**Comment by jutley** [comment]
After a bit of digging, I think that both JSONPath and JMESPath are poorly suited for this task. They both aim to get query values from a JSON objects, but not mutate them or return paths.

Alternatively, there may be a sensible way forward leveraging `jq`. It's `del` function should do exactly what we need to prepare the JSON objects for the diff, and the end user can provide a "path expression" that gets wrapped in the `del` function.

For example, lets assume that my mutating webhook is adding an environment variable called `POD_NAME` to every pod, and I want to remove it. This is easily possible with `jq`:

```
➜  jq '.' pod.json
{
  "apiVersion": "v1",
  "kind": "Pod",
  "spec": {
    "containers": [
      {
        "image": "image1",
        "name": "container1"
      },
      {
        "env": [
          {
            "name": "POD_NAME",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.name"
              }
            }
          },
          {
            "name": "ENVVAR",
            "value": "foo"
          }
        ],
        "image": "image2",
        "name": "container2"
      }
    ]
  }
}

➜  jq 'del(.spec.containers[]?.env[]? | select(.name == "POD_NAME"))' pod.json
{
  "apiVersion": "v1",
  "kind": "Pod",
  "spec": {
    "containers": [
      {
        "image": "image1",
        "name": "container1"
      },
      {
        "env": [
          {
            "name": "ENVVAR",
            "value": "foo"
          }
        ],
        "image": "image2",
        "name": "container2"
      }
    ]
  }
}
```

The argocd `resource.customizations` field may look like this:

```yaml
Pod:
  ignoreDifferences: |
    jqPathExpressions:
    - .spec.containers[]?.env[]? | select(.name == "POD_NAME")
```

There are some implementations of jq in golang that allow it to be used as a library. I did a proof of concept with [github.com/itchyny/gojq](https://github.com/itchyny/gojq) and it seemed to do the trick. I'm not sure what kind of validation or mutation should be done on the path expressions to make UX pleasant. I can imagine people running into issues where they use the `[]` syntax without a `?`, and getting an error when the field is not defined (such as the first container's `env` in my example.
