### ISSUE TITLE
Mutatingwebhook drifting at application level not working

### ISSUE THREAD

**Issue by kotlak** [argoproj/argo-cd#4326]
**Describe the bug**

Deploying vault secrets agent through argo and observed  vault-agent-injector-cfg keep out of sync

added this to ignore the differences but its still not working

  ignoreDifferences: 
    - group: ""
      kind: MutatingWebhookConfiguration
      name: webhookignore
      namespace: "default"
      jsonPointers: 
      - /webhooks

tried with 

  ignoreDifferences: 
    - group: ""
      kind: MutatingWebhookConfiguration
      name: webhookignore
      namespace: ""    # even removed this name space entry
      jsonPointers: 
      - /webhooks

Note: added /* in end of this and added individual entries like -  /webhooks/0/clientConfig/caBundle \n -/webhooks/0/clientConfig/caBundle

No change in out put, saw a cluster level change in argocd-cm but I need a change at the application level

**To Reproduce**
Deploy vault agent through helm

https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault

login to argo and can see webhook out of sync

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

no out of sync any time 

**Screenshots**

![image](https://user-images.githubusercontent.com/62711872/93116728-ab1e5400-f68b-11ea-9d65-0fa46a93b823.png)

**Version**

v1.6.1+1
**Logs**
![image](https://user-images.githubusercontent.com/62711872/93117074-3f88b680-f68c-11ea-9ca7-305bf5d8f472.png)

![image](https://user-images.githubusercontent.com/62711872/93116883-eb7dd200-f68b-11ea-913b-56a6b695d512.png)

**Comment by jessesuen** [comment]
You need to specify group as `admissionregistration.k8s.io`

**Comment by kotlak** [comment]
ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: webhookignore
    jsonPointers:
      - /webhooks
![image](https://user-images.githubusercontent.com/62711872/93157679-aaf87580-f6d8-11ea-8b15-76e53dde3ebe.png)


No change, still getting same issue

**Comment by kotlak** [comment]
tried with single tab or space at group too to cross verify yaml format issues, no change

**Comment by Rahulsharma0810** [comment]
Facing same issue

**Comment by St4NNi** [comment]
There is an example in: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/
I could only solve this issue by adding:
```yaml
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
```
to my argo-cm configmap.

**Comment by Rahulsharma0810** [comment]
@St4NNi can you share snippet, not working 

```
ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/replicas
  - group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    jsonPointers:
      - /webhooks
data:
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
    - ```

**Comment by St4NNi** [comment]
@Rahulsharma0810 This looks like an application spec. I used the global configmap (argocd-cm) to change this. My kustomize overlay looks like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
```

**Comment by Rahulsharma0810** [comment]
Doesn't been resolved yet

![image](https://user-images.githubusercontent.com/9934859/148933090-887f780d-69f0-492d-bccb-211d699fa664.png)

```
╰─❯ k describe cm argocd-cm
Name:         argocd-cm
Namespace:    vault
Labels:       <none>
Annotations:  <none>

Data
====
resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration:
----
jqPathExpressions:
- '.webhooks[]?.clientConfig.caBundle'


BinaryData
====

Events:  <none>

```

**Comment by Mais316** [comment]
Having the same issue was there any fix, tried the above didnt work.

**Comment by mhjacks** [comment]
I had the same issue, but was able to resolve it by specifying the group as noted above in https://github.com/argoproj/argo-cd/issues/4326#issuecomment-692308968

**Comment by jozefs** [comment]
This worked for me:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.19.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
```

**Comment by kometen** [comment]
New to argo-cd so bear with me. I spent hours trying to add the settings suggested. Then I clicked on DETAILS in upper left corner, MANIFEST, EDIT, and added `ignoreDifferences`. All good now. For others that may struggle how to modify the settings.

**Comment by iamhritik** [comment]
I'm still facing this issue even after adding this in the Application level 

```
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
```

any other suggestions guys ?

**Comment by mardonner** [comment]
> any other suggestions guys ?

@iamhritik  Did you also set this on the app?

```yaml
syncPolicy:
  syncOptions:
    - RespectIgnoreDifferences=true
```
