### ISSUE TITLE
webhook.go: Limit application refresh according to application spec.source.path

### ISSUE THREAD

**Issue by jetersen** [argoproj/argo-cd#4349]
# Summary

Improve `webhook.go:HandleEvent` to parse paths from the events.
https://github.com/argoproj/argo-cd/blob/ba71ad934c79a5148eb171d6760c0553eecdb5c6/util/webhook/webhook.go#L145-L195

# Motivation

To speed up refreshing of a mono repository with apps of apps setup.

# Proposal

All the possible event sources usually gives us a set of paths that was changed.
Here is a snippet from a github webhook.

```jsonc
{  
  // ...
  "commits": [
    {
      "id": "9b61182f0dce5b250bfffc50225fdab9743d2bc9",
      "tree_id": "35980cb790d7d2008a0f3598e9f3004ffd44b6f7",
      "distinct": true,
      "message": "add argocd app",
      "timestamp": "2020-09-16T14:44:57+02:00",
      "url": "https://github.com/org/repo/commit/9b61182f0dce5b250bfffc50225fdab9743d2bc9",
      "author": {
        "name": "Joseph Petersen",
        "email": "snip",
        "username": "jetersen"
      },
      "committer": {
        "name": "Joseph Petersen",
        "email": "snip",
        "username": "jetersen"
      },
      "added": [
        "apps/argocd.yaml"
      ],
      "removed": [

      ],
      "modified": [
        "apps/kustomization.yaml"
      ]
    }
  ],
  // ...
}
```

First application with `path: apps` will be triggered

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    path: apps
    repoURL: git@github.com:org/repo
    targetRevision: master
  destination:
    name: k8s
    namespace: argocd
  syncPolicy:
    automated: {}
```

Second app with `path: apps/myapp` will not be triggered since there are no changes to the folder `apps/myapp`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    path: apps/myapp
    repoURL: git@github.com:org/repo
    targetRevision: master
  destination:
    name: k8s
    namespace: argocd
  syncPolicy:
    automated: {}
```
