### ISSUE TITLE
Unable to get application when namespace is not argocd

### ISSUE THREAD

**Issue by MeNsaaH** [argoproj/argo-cd#4387]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
We are running a dev and test environment on a single cluster. Apps have similar names and are isolated by namespaces. To also isolate argocd applications, I tried to deploy the argocd Application resource to dev or test namespace.
But When Application resource is deployed to a different namespace, argocd cannot find the created resource from web UI. But running `kubectl get applications -n namespace` shows the deployed application. The resources are not even created by the applications

**To Reproduce**

Create an argocd application with namespace not set to argocd
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  # You'll usually want to add your resources to the argocd namespace.
  namespace: ns
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  # Destination cluster and namespace to deploy the application

  destination:
    server: https://kubernetes.default.svc
    namespace: ns

  # Source of the application manifests
  source:
    repoURL: repoLink
    targetRevision: HEAD
    path: k8s

```

**Expected behavior**

ArgoCD Web UI should show deploed application.

**Screenshots**

**Version**
2.7.2 deployed on server from helm

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
