### ISSUE TITLE
Inaccurate sync error message when template value is passed as boolean instead of string

### ISSUE THREAD

**Issue by lucinvitae** [argoproj/argo-cd#4391]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When a boolean value is used in the environment variables section of a deployment template in a Helm chart (which `helm template` validates successfully as can be seen below), our ArgoCD instance fails to sync the deployment (SyncFailed for deployment `apps/v1/...`) with the following difficult-to-read and inaccurate error message:
```
"" is invalid: patch: Invalid value: "map[metadata:map[annotations:map[
<snip lots and lots of annotations, see log output at bottom of this bug report>
\n]]
spec:map[template:map[spec:map[volumes:<nil>]]]]": unrecognized type: string
```

This error message displayed in our ArgoCD version has the following issue:

1. It seems to suggest that there is an empty string in the values somewhere (there is not).
2. It seems to suggest that there is a string value at fault causing the issue (incorrect, it's a boolean).
3. The error message dumps the entire mapping of YAML values (scroll down to see example full output) instead of the particular value causing the error.

Note that I know how to fix (and have fixed) the error, but that the goal of this ticket is to improve the error handling of ArgoCD's sync to make it easier for future developers who found the same issue.

**To Reproduce**

To reproduce the issue, create a Helm chart setup with the following `values.yaml` and `templates/deployment.yaml` files:

`values.yaml` file:
```yaml
boolString: "False"
```

`templates/deployment.yaml` file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-bug-report
spec:
  template:
    spec:
      containers:
        - name: test-bug-report-container
          image: python:3.7-alpine
          env:
            - name: MY_VAR
              value: {{ .Values.boolString }}
```

Running `helm template` shows that it's a valid template:
```
helm template . -x ./templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-bug-report
spec:
  template:
    spec:
      containers:
        - name: test-bug-report-container
          image: python:3.7-alpine
          env:
            - name: MY_VAR
              value: False
```

Notice that helm does not care that the `MY_VAR` value wasn't encapsulated in double quotes. Only ArgoCD appears to care, throwing the abovementioned error during application sync: `"" is invalid: patch: Invalid value: "map[metadata:map[annotations:map[ ....... \n]] spec:map[template:map[spec:map[volumes:<nil>]]]]": unrecognized type: string`

The fix is to edit the following lines in the `templates/deployment.yaml` file to ensure string encapsulation:
```
              value: "{{ .Values.boolString }}"
```

But Argo's error message requires that the developer does quite a bit of unnecessary debugging, especially if there are many variables in the `values.yaml` file and a much more complicated deployment template.

**Expected behavior**

What would be ideal: The current error message, which seems to imply that the value at fault is a string instead of a boolean, could be improved by highlighting that the value at fault is actually a boolean and not a string. For example, it would be really helpful for debugging if the error message was simply `patch failed due to the following issue: the value for key "MY_VAR" in the nested mapping was type <boolean>, but type <string> was expected. Value: "{\"name\":\"MY_VAR\",\"value\":false}"`

What is perhaps more feasible: If it's not possible to drill down to the value that is causing the issue within the nested mapping, at least the following should be implemented if possible:

1. The error message should not state that there is an empty string in the values somewhere.
2. The error message should indicate that there is a boolean value causing the issue.

The above 2 fixes would be a significant improvement, since the error message would only be difficult to parse in that case, rather than difficult to parse and misleading.

**Screenshots**

N/A

**Version**

argocd version:
```shell
v1.6.2+3d1f37b
```

**Logs**

```
"" is invalid: patch: Invalid value: "map[metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"iam.amazonaws.com/role\":\"<redacted>\"},\"labels\":{\"app.kubernetes.io/instance\":\"gfb-docs-inference-service-dev-inference-service\",\"app.kubernetes.io/managed-by\":\"Tiller\",\"app.kubernetes.io/name\":\"gfb-docs-inference-service\",\"argocd.argoproj.io/instance\":\"gfb-docs-inference-service-dev\",\"helm.sh/chart\":\"gfb-docs-inference-service-0.1.0\"},\"name\":\"doc-scanner-inference-service\",\"namespace\":\"doc-scanner\"},\"spec\":{\"replicas\":2,\"selector\":{\"matchLabels\":{\"app.kubernetes.io/instance\":\"gfb-docs-inference-service-dev-inference-service\",\"app.kubernetes.io/name\":\"gfb-docs-inference-service\"}},\"template\":{\"metadata\":{\"annotations\":{\"iam.amazonaws.com/role\":\"<redacted>\"},\"labels\":{\"app.kubernetes.io/instance\":\"gfb-docs-inference-service-dev-inference-service\",\"app.kubernetes.io/name\":\"gfb-docs-inference-service\"}},\"spec\":{\"containers\":[{\"args\":[\"-c\",\"<redacted>\"],\"command\":[\"/bin/sh\"],\"env\":[{\"name\":\"MY_VAR\",\"value\":false},{\"name\":\"HTTP_PORT\",\"value\":\"8080\"},{\"name\":\"WORKERS\",\"value\":\"17\"},{\"name\":\"MLFLOW_TRACKING_URI\",\"value\":\"<redacted>\"},{\"name\":\"MLFLOW_EXPERIMENT_NAME\",\"value\":\"doc_classifier_v2\"},{\"name\":\"MODEL_NAME\",\"value\":\"prodigy-text-multiclass\"},{\"name\":\"MODEL_LABELS\",\"value\":\"TRF_any_page,family_history,genetic_counseling_report,insurance_card,insurance_card_info,invitae_report_coversheet,invitae_report_other_page,letter_of_medical_necessity,medical_records,pedigree,prior_auth_form\"},{\"name\":\"SUGGESTED_LABELS_CONFIDENCES\",\"value\":\"0.5,0.45,0.4,0.9,0.35,0.5,0.5,0.95,0.6,0.8,0.5\"},{\"name\":\"SUGGESTED_LABELS_BBOXES\",\"value\":\"False,False,False,False,False,False,False,False,False,False,False\"}],\"image\":\"<redacted>\",\"imagePullPolicy\":\"Always\",\"livenessProbe\":{\"failureThreshold\":20,\"httpGet\":{\"path\":\"/v1/models\",\"port\":\"http\"},\"initialDelaySeconds\":180,\"periodSeconds\":30},\"name\":\"gfb-docs-inference-service\",\"ports\":[{\"containerPort\":8080,\"name\":\"http\",\"protocol\":\"TCP\"}],\"readinessProbe\":{\"failureThreshold\":20,\"httpGet\":{\"path\":\"/v1/models\",\"port\":\"http\"},\"initialDelaySeconds\":60,\"periodSeconds\":20},\"resources\":{\"limits\":{\"cpu\":\"2\",\"memory\":\"7Gi\"},\"requests\":{\"cpu\":\"500m\",\"memory\":\"4Gi\"}}}],\"nodeSelector\":{\"group-name\":\"worker-group-1\"},\"volumes\":null}}}}\n]] spec:map[template:map[spec:map[volumes:<nil>]]]]": unrecognized type: string
```

**Comment by jessesuen** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-bug-report
spec:
  template:
    spec:
      containers:
        - name: test-bug-report-container
          image: python:3.7-alpine
          env:
            - name: MY_VAR
              value: False
```

According to the YAML linter I tried, `False` (even if capitalized), is considered a bool value and not a string. So this would be expected behavior.
