### ISSUE TITLE
[docs] Helm user guide incorrectly claims that values files needs to be in the same or subdirectory of chart

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [argoproj/argo-cd#4406]
The note attached to the [helm user guide](https://argoproj.github.io/argo-cd/user-guide/helm/#values-files) claims the following

> Values files must be on the same directory or a subdirectory of the Helm application

I have tried keeping the `values.yaml` file outside the chart directory and I can still access it using relative path. Here' an example `Application` that works

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-stuff
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: stuff
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/my-stuff
    repoURL: git@github.com:my-repo/my-charts.git
    targetRevision: HEAD
    helm:
      releaseName: my-stuff
      valueFiles:
        - ../../valuesFiles/my-stuff/values.yaml

```

As you can see that the `values.yaml` file is in a seperate root directory of the repo and using a relative path works. Maybe the note should be updated with this information.

I can create a PR for the same if its fine.
