### ISSUE TITLE
Cannot login with Bitbucket Cloud 

### ISSUE THREAD

**Issue by abdennour** [argoproj/argo-cd#4408]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Cannot login with Bitbucket cloud and always getting this message: "Failed to authenticate: invalid_scope: These requested scopes are beyond the OAuth client's own scopes: team"

**To Reproduce**

Using the helm-chart argo/argo-cd, set values as following
```yaml
    server:
      config:
        url: https://cd.dev.mycompany.com
        dex.config: |
          connectors:
          - type: bitbucket-cloud
            # Required field for connector id.
            id: bitbucket-cloud
            # Required field for connector name.
            name: Bitbucket Cloud
            config:
              # Credentials can be string literals or pulled from the environment.
              clientID: $BITBUCKET_CLIENT_ID
              clientSecret: $BITBUCKET_CLIENT_SECRET
              redirectURI: https://cd.dev.mycompany.com/api/dex/callback
              # https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/
              scopes:
              - email
    configs:
      secret:
        extra:
          BITBUCKET_CLIENT_ID:  XYZxcxc
          BITBUCKET_CLIENT_SECRET: XYZcxcxcx
```

**Expected behavior**

I expect to be able to login with Bitbucket Cloud Provider.

**Screenshots**

![image](https://user-images.githubusercontent.com/1788384/94018483-55e3f000-fdb9-11ea-87da-78bb006e9b37.png)

**Version**

```sh
> argocd version
argocd: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:53:13Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
```

```sh
> helm -n argocd ls

NAME  	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
argocd	argocd   	14      	2020-09-23 15:53:57.307614 +0300 +03	deployed	argo-cd-2.7.4	1.7.6 
```

**More**

After updating the helm release, i tried also to manual restart dex server : 

```sh
k -n argocd rollout restart deployment/argocd-dex-server
```

Also ... before each configuration attempt, I clear browser cache.
