### ISSUE TITLE
Global (inherited) project settings

### ISSUE THREAD

**Issue by mayzhang2000** [argoproj/argo-cd#4416]
# Summary
Need support of global namespace allow list. Each project still has its own allow list. The final allow list is the concatenation of these two.

What change you think needs making.

# Motivation
Global namespace allow list eliminates the duplication of allow list for each project if they are the same.

Please give examples of your use case, e.g. when would you use this.

# Proposal
Configure global namespace allow list

How do you think this should be implemented?
1. In argocd-cm, add the following to specify global namespace allow list.
```
data: 
  projectSpec: |
    allowedResources:
     - apps/daemonsets
     - apps/replicasets
```

Or

```
data: 
  project.namespaceResourceWhitelist: |
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
```
2. When checking permission `IsGroupKindPermitted`, use the concatenation of allow list in project and and in argocd-cm.

**Comment by jessesuen** [comment]
Proposal is to:

1. Utilize existing AppProject for configuration to define a "global" project. e.g. create a AppProject whose settings would like to be applied to other projects.

2. Reference the project created in step 1 in the argocd-cm ConfigMap, and use Kubernetes `matchExpressions` syntax to map to other projects. For example, syntax might look like:

```yaml
data:
  globalProjects:
  - projectName: my-global-project
    matchExpressions:
    - {key: "opt-out", operator: "DoesNotExist"}
```

The above syntax would apply the settings in `my-global-project` to all existing Argo CD projects, **unless** they have an "opt-out" label.

3. When multiple projects need to be merged, we synthesize a "virtual" project on the fly, which merges all fields of the project into a synthesized one, and then apply normal project enforcement.
