### ISSUE TITLE
Can app helm get gitlab ci variables???

### ISSUE THREAD

**Issue by D-wenhao** [argoproj/argo-cd#4418]
- How can app helm get gitlab ci variabels
![image](https://user-images.githubusercontent.com/56722758/94147671-311a7600-fea8-11ea-8af5-59ee099d160c.png)
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@gitlab.xxx.com:xxx/xxx.git
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: argocd
      valueFiles:
      - values-dev.yaml
      version: v2
```
