### ISSUE TITLE
SSO login via cli without WebBrowser

### ISSUE THREAD

**Issue by mcouliba** [argoproj/argo-cd#4424]
Hello,

I would like to using argocd cli as a Tekton Task (running argocd inside a container).
ArgoCD is using OpenShift OAuth. When logging in I got the following error message

```
argocd login argocd-server.argocd.svc --sso --plaintext
Opening browser for authentication
Performing authorization_code flow login: https://argocd-server-argocd.apps.cluster-afe0.afe0.example.opentlc.com/api/dex/auth?access_type=offline&client_id=argo-cd-cli&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=lGaGXCEHVi
FATA[0001] exec: "xdg-open": executable file not found in $PATH 
```

I could install xdg-open but inside my container, I do not have any browser

Is there a way to SSO login without webrowser redirection?

Thanks

**Comment by jannfis** [comment]
I'm afraid the OAuth with ArgoCD is only possible using a browser. However, you can create a [local (technical) user](https://argoproj.github.io/argo-cd/operator-manual/user-management/#local-usersaccounts-v15) and use it for automation purposes. Be sure to configure appropriate RBAC rules in Argo CD for the user, so that the user will be authorized to do what you need it to do.

**Comment by mcouliba** [comment]
Thanks @jannfis. 
I will do that

**Comment by seanwalker909** [comment]
Bumping this post to see if there are any plans of adding SSO login support via the REST API

**Comment by ramanNarasimhan77** [comment]
My team also is facing this issue and we are using this workaround

We use `keycloak` for SSO and it is possible to directly obtain a TOKEN from Keycloak using REST API

```
export ACCESS_TOKEN=$(curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' -d "username=${USER}" -d "password=${PASSWORD}" -d 'grant_type=password' -d "client_id=${ARGOCD_CLIENT}" -d 'scope=offline_access' -d "client_secret=${CLIENT_SECRET}" ${KEYCLOAK_REALM}/protocol/openid-connect/token | jq -r .access_token)
```

Once we have a token, we can use it in the cli

```
argocd app list --auth-token $ACCESS_TOKEN --server argocd.example.com
```

One caveat of this approach is that ACCESS_TOKEN has to be retrieved before running each command and both TOKEN and SERVER options have to be passed to each and every command.

**Comment by xlanor** [comment]
Has anyone figured out a way to do this for google SSO?

It seems like creating a user seems to require an admin user being enabled in the first place. we could script this via terraform, but would prefer a cleaner approach.

**Comment by kevanslumin** [comment]
I'd like to automate the argocd login with headless chrome via chromedp or puppeteer.  Could you possibly add a flag like 
`--browser=none` to just print out the SSO URL without popping up the browser?

**Comment by cpmoore** [comment]
I had the same issue with using argocd with openshift oauth.  
I was able to emulate the oauth flow in python pretty easily.  It should be possible to translate this to curl.

```python
def argocd_login(host, username, password):
    # temporarily disable ssl verification warnings
    with warnings.catch_warnings():
        urllib3.disable_warnings()
        # create session to keep cookies
        session = requests.session()
        # call initial login endpoint, will redirect to openshift oauth
        response = session.get("https://" + host + "/auth/login", allow_redirects=True, verify=False)
        # parse response to get openshift host
        parsed = urlparse(response.url)
        openshift_url = parsed.scheme + '://' + parsed.netloc
        # setup oauth and idp urls
        authorize_endpoint = '/oauth/authorize?' + parsed.query
        idp_url = openshift_url + "/login/ldapidp"
        # do an initial get to the idp endpoint to get the csrf value
        csrf = session.get(idp_url, allow_redirects=False, verify=False, params={
            'then': authorize_endpoint
        }).cookies['csrf']
        # post csrf,username, and password to idp endpoint
        oauth_result = session.post(idp_url, data={
            'username': username,
            'password': password,
            'csrf': csrf,
            'then': authorize_endpoint
        }, allow_redirects=True, verify=False)
        # the final location will be the argo cd cluster, so we need to get the last redirect instead
        return oauth_result.history[-1].cookies['argocd.token']

```

**Comment by warroyo** [comment]
@jannfis can this be reopened? for some users creating a local account is not acceptable for the company's auth policies. we need a way to login without a browser using . Dex supports the `resource owner password credentials grant` type which should support this. 

https://github.com/dexidp/dex/pull/1621

**Comment by Mohjive** [comment]
The [PKCE flow](https://auth0.com/docs/authorization/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce) should be possible to support as well.

**Comment by tarfeef101** [comment]
Commenting to indicate my support for:
- printing the browser URL (best option)
- something i've seen before in other apps, the ability to spin up a local server on a given port and simply wait for the user to visit it. in at least some cases, you can set the container and/or VM to forward that port back to your host machine and complete the auth flow that way

**Comment by antonio-te** [comment]
I'm having this issue on WSL, but it's because of https://github.com/skratchdot/open-golang/issues/29.

**Comment by Tronix117** [comment]
Same here, it should be possible to disable the web-browser opening and just show the URL, or just display a warning instead. It would be great to not be blocking.
On tools using `xdg-open`, there is usualy the possibility to disable it.

On my hand, I'm using the cli on a remote session, and there is no desktop environment.

**Comment by antoniordz96** [comment]
Can this be reopened? We are using devspaces which are like gitpods and the docker argocd container doesn't support opening a web browser. I'm happy to help implement something similar as suggested in https://github.com/argoproj/argo-cd/issues/4424#issuecomment-1266055758 where it just prints the link to generate a token. Similar to what the Openshift CLI does.

**Comment by blairdrummond** [comment]
FYI [I have done this with AzureAD](https://github.com/argoproj/argo-cd/issues/11632), and if you use Dex then this [recent feature](https://github.com/dexidp/dex/pull/2806) will allow you to solve this via federation. (That feature might not be cut into a release yet, but you can find the edge images published which work).

This effectively makes this possible with any OIDC provider via Dex. The flow is, take your github-action/gitlab-ci job/kubernetes service account token, yada yada, configure the OIDC backend for that as a connector for Dex, and do a token exchange to get a dex token. You can then pass that token with the argocd cli. I even have the ArgoCD terraform provider working with OIDC.

**Comment by achdmbp** [comment]
in the case of running argocd cli in a remote container (such as in devspaces / gitpods). if argocd cli expose a flag to override redirect_uri, this should work, since one can configure a redirect_uri to point to an ingress/route that points to server argocd cli spins up locally in the container

**Comment by achdmbp** [comment]
> in the case of running argocd cli in a remote container (such as in devspaces / gitpods). if argocd cli expose a flag to override redirect_uri, this should work, since one can configure a redirect_uri to point to an ingress/route that points to server argocd cli spins up locally in the container

just an update, this solution won't work. we cannot use arbitrary redirect url. the redirect url has be registered in oauth.

is there a proposed solution at this point that is ready to be implemented? I'd be happy to help implement it.

**Comment by ArieLevs** [comment]
> I even have the ArgoCD terraform provider working with OIDC.

Hi @blairdrummond, could you please elaborate on the token exchange you did with Terraform?
i'm trying to implement a token exchange for the argocd terraform provider, using Okta SSO, but the process seems to be not that documented except for github use case.

Thanks

**Comment by blairdrummond** [comment]
You can't exactly do this with Okta, instead what you do is:

1. Set up ArgoCD to [use the built-in Dex](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#oidc-configuration-with-dex). You need to use [the most recent dex image](https://github.com/dexidp/dex/releases/tag/v2.38.0) because token exchange was just released 3 weeks ago.
2. In the `dex.config`, hook up Okta to dex (looks like you need either a SAML or oidc connector)?
3. IN ADDITION to Okta, hook up github-actions to dex. Sample config below.


```yaml
issuer: https://argocd.example.com/api/dex
expiry:
  idTokens: 8h
  signingKeys: 24h

staticClients:
  - id: argocd
    name: ArgoCD
    redirectURIs:
      - https://argocd.example.com/api/dex/callback
    secretEnv: ARGOCD_CLIENT_SECRET

connectors:
  # This is my Github auth config, but switch this out for SAML or OIDC for Okta
  - config:
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      loadAllGroups: true
      orgs:
        - name: liatrio
      redirectURI: https://argocd.example.com/api/dex/callback
    id: github
    name: GitHub
    type: github

  - config:
      issuer: https://token.actions.githubusercontent.com
      scopes:
        - openid
        - groups
      userNameKey: sub
    id: github-actions
    name: github-actions
    type: oidc

oauth2:
  skipApprovalScreen: true

storage:
  config:
    inCluster: true
  type: kubernetes
telemetry:
  http: 0.0.0.0:5558
web:
  http: 0.0.0.0:5556
```

Users will see a screen like below, and your github actions will need a token to auth that doesn't involve Okta at all

<img width="552" alt="Screen Shot 2024-02-18 at 11 30 36 AM" src="https://github.com/argoproj/argo-cd/assets/10801138/bd82e0c4-7109-4611-998a-688807e5bf77">

You can find sample code for the token exchange from a github action [here](https://github.com/dexidp/dex/pull/2806#issuecomment-1542704781). [I am trying to get a PR going for Kubelogin so that kubelogin can do this](https://github.com/int128/kubelogin/pull/1052) instead of `curl`. Once you have that token, you can fire that off to ArgoCD as a bearer token and it'll work. Sample TF below

```tf
terraform {
  required_providers {
    argocd = {
      source = "oboukili/argocd"
      version = "6.0.3"
    }
  }
}

# I used this with interactive auth-code login locally,
# but switch it out with curl, OR just use a TF_VAR
data "external" "token" {
  program = [
    "sh", "-c", <<-HEREDOC
    kubelogin \
      get-token \
      --oidc-issuer-url ${var.sso_issuer} \
      --oidc-client-id ${var.client_id} \
      --grant-type authcode \
      --oidc-extra-scope openid | jq '{"token": .status.token}'
HEREDOC
  ]
}

provider "argocd" {
  auth_token  = data.external.token.result.token
  server_addr = var.argocd_host
}
```

# Why Dex?

Dex happens to now support token-exchange, last I checked Okta *does not* support that yet (PingFederate does. If you use Ping you can do all this natively there and skip Dex). Once/if Okta natively supports token exchange, basically you just register Github Actions to be able to auth to Okta to get an Okta token, then fire that to your service.

# IMPORTANT NOTE: Github-Actions security

The github-actions OIDC issuer there is github.com wide. Literally anyone could use that. I have a personal fork of Dex were I added lua support to do some extra authz there, I think something like rego or CEL would be better. You might just need to vet the security there to make sure that this system doesn't open up unintended access. Keeping your dex/argocd service in a private network will obviously help here

**Comment by blairdrummond** [comment]
@achdmbp you can definitely use device-code login to access argocd if you use an extra tool like [kubelogin](https://github.com/int128/kubelogin). You do a device-code login there, get the token, then plug it into whatever system.

**Comment by haiwu** [comment]
@blairdrummond : per this okta doc https://developer.okta.com/docs/guides/set-up-token-exchange/main/, does it mean that okta does support token-exchange?

**Comment by blairdrummond** [comment]
Oh snap @haiwu yes it does! Looks like you can use that for token-exchange.

In that case, you can hook ArgoCD -> Okta, then Okta humans use sso as normal, and you use that flow to get machine identities to get an Okta ID token, then send that token to ArgoCD

**Comment by alexjball** [comment]
For sessions over ssh or codespaces, where you can forward your terminal's port to your local host, you can stub out xdg-open on the remote side to avoid the error. You can then open the link in your local browser to finish the flow.

```bash
echo "#!/bin/sh" > ~/.local/bin/xdg-open
chmod +x ~/.local/bin/xdg-open

argocd login ... --sso
```

**Comment by ryanhashemi-tmx** [comment]
For those interested to achieve this with dex, here are the details:


```bash
export ACCESS_TOKEN=$(curl -X POST ${DEX}/token \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "${CLIENT_ID}:${CLIENT_SECRET}" \
  -d "grant_type=password&username=${USER}&password=${PASSWORD}&scope=openid email groups" | jq -r '.access_token')
```

```bash
argocd app list --auth-token $ACCESS_TOKEN --server $ARGOCD_SERVER
```

Please note, I had to set `passwordConnector: ldap`  in my dex deployment helm value file

```yaml
        config:
          logger:
            level: "debug"
          connectors:
            - type: ldap
              id: ldap
              name: LDAP
              ...
          oauth2:
            skipApprovalScreen: true
            passwordConnector: ldap
```

This is based on what [ramanNarasimhan77](https://github.com/ramanNarasimhan77) shared here.

**Comment by joshuajetomo** [comment]
@ryanhashemi-tmx what's the value of this ${DEX}/token. I am trying to test your solution. I am using the argocd helm chart https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml 

here's my value file 

    configs:
      cm:
        dex.config: |
          connectors:
          - type: ldap
            name: ..
            id: ad
            config:
              host: ..
              insecureNoSSL: true
              insecureSkipVerify: true
              startTLS: false
              # Variable name stores ldap bindDN in argocd-secret
              bindDN: "$dex.ldap.bindDN"
              # Variable name stores ldap bind password in argocd-secret
              bindPW: "$dex.ldap.bindPW"
                # Ldap user serch attributes
              userSearch:
                baseDN: ..
                filter: "(objectClass=person)"
                username: sAMAccountName
                idAttr: distinguishedName
                emailAttr: mail
                nameAttr: displayName
              # Ldap group serch attributes
              groupSearch:
                baseDN: ..
                filter: "(objectClass=group)"
                userAttr: distinguishedName
                groupAttr: member
                nameAttr: `name

**Comment by xi4n** [comment]
I must unlike the OP of this issue. For anyone who comes here: DO NOT install `xdg-open`!! Not only it won't solve your problem for argocd authentication, but it'll break other tools such as Azure CLI.. Now I'll need to spend hours to fix another problem.

It's definitely an ArgoCD's problem: I have a browser in my Ubuntu but it just doesn't work. And Azure CLI for example doesn't need `xdg-open` to open a browser for authentication so why can they but ArgoCD CLI can't?

**Comment by p1utoze** [comment]
Even I have same issue. Like @blairdrummond, I am trying to use Github-actions OIDC to exchange github action ID token for argocd auth token using dex config with OIDC instead of using [ Dex Github connector](https://dexidp.io/docs/connectors/github/). Something like this in `argocd-cm` configmap:
```
dex.config: |-
    connectors:
    -   type: oidc
        id: github-actions
        name: GitHub Actions
        config:
            issuer: https://token.actions.githubusercontent.com
            clientID: argocd-dev-server
            clientSecret: ''
            redirectURI: https://$ARGOCD_SERVER/api/dex/callback
            requestedScopes:
            - openid
            - email
            - groups
            claimMapping:
                preferred_username: sub
                groups: sub
```
And defined RBAC policy as well:
```
apiVersion: v1
kind: ConfigMap
name: argocd-rbac-cm
data:
  policy.csv: |
    p, role:github-ci, applications, *, *, allow
    p, role:github-ci, projects, *, *, allow
    p, role:github-ci, repositories, *, *, allow
    p, role:github-ci, applicationsets, *, *, allow
    p, role:github-ci, certificates, *, *, allow
    p, role:github-ci, logs, *, *, allow
    p, role:github-ci, clusters, *, *, allow
    g, repo:$GITHUB_REPOSITORY:environment:$ENVIRONMENT, role:github-ci
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
```

This is the workflow job steps that I am using:
```
 steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get GitHub OIDC Token
        uses: actions/github-script@v6
        id: oidc
        with:
          script: |
            const token = await core.getIDToken("${{ env.ARGOCD_CLIENT_ID }}");
            core.setOutput("token", token);

      - name: Exchange GitHub OIDC Token for ArgoCD Session Token
        id: argo_token
        run: |
          echo "Exchanging GitHub OIDC token for ArgoCD session token..."
   
          ARGOCD_SESSION_TOKEN=$(
            curl -sSL -X POST "https://${{ env.ARGOCD_URL }}/api/v1/session" \
              -H "Content-Type: application/json" \
              -d '{"idToken":'"${{ steps.oidc.outputs.token }}"'}' \
            | jq -r .token
          )
            
          if [ "$ARGOCD_SESSION_TOKEN" == "null" ] || [ -z "$ARGOCD_SESSION_TOKEN" ]; then
            echo "Failed to get ArgoCD token"
            exit 1
          fi
          echo "::add-mask::$ARGOCD_SESSION_TOKEN"
          echo "ARGOCD_SESSION_TOKEN=$ARGOCD_SESSION_TOKEN" >> $GITHUB_ENV

      - name: ArgoCD get stable version number
        id: argocd-version
        shell: bash
        run: |
          echo "version=$(curl -L -s https://raw.githubusercontent.com/argoproj/argo-cd/stable/VERSION)" >> $GITHUB_OUTPUT
        
      - name: Install ArgoCD CLI
        env:
          VERSION: ${{ inputs.version != '' && inputs.version || steps.argocd-version.outputs.version }}
        shell: bash
        run: |
          echo "Installing ArgoCD CLI version ${{ env.VERSION }}"
          url="https://github.com/argoproj/argo-cd/releases/download/v${{ env.VERSION }}/argocd-linux-amd64"
          curl --fail -sSL -o argocd $url
          echo "Installation Complete!"
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
          echo "Permission set complete"
          argocd version --client

      - name: Argo CD Login Test
        run: |
          echo "Logging into ArgoCD at $ARGOCD_URL with OIDC token…"
          # this should return “context switched to …” or similar success message
          argocd login $ARGOCD_URL \
            --insecure \
            --auth-token "${{ steps.oidc.outputs.token }}" \
```

I am stuck at the error: 
```
{"error":"no credentials supplied","code":16,"message":"no credentials supplied"}
```

**Comment by andrii-korotkov-verkada** [comment]
One can use an option `--sso-launch-browser false` now, but there's still a problem that redirect url is for a localhost.

**Comment by janosmiko** [comment]
I'm using ArgoCD+Dex and Authentik as the OIDC source and this solution works for me.

ArgoCD ConfigMap `dex.conf`:
```yaml
connectors:
  -
    config:
      issuer: https://auth.example.com/application/o/argocd/
      clientID: my-client-id
      clientSecret: my-client-secret
      insecureEnableGroups: true
      getUserInfo: true
      userIDKey: preferred_username
      scopes:
        - openid
        - profile
        - email
    name: authentik
    type: oidc
    id: authentik

oauth2:
  grantTypes:
    - "authorization_code"
    - "urn:ietf:params:oauth:grant-type:token-exchange"
```

script:
```bash
docker run --rm -it alpine sh

apk add --no-cache argocd --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
apk add -u --no-cache curl jq

export AUTH_SERVER_URL="https://authentik.example.com/application/o/token/"
export ARGOCD_SERVER=argocd.example.com
export CLIENT_ID=my-client-id
export AUTH_USER=test-user
export AUTH_PASSWORD=password

# fetch token from auth source
export AUTH_ACCESS_TOKEN=$(curl -sSL \
  -d "client_id=$CLIENT_ID" \
  -d "username=$AUTH_USER" \
  -d "password=$AUTH_PASSWORD" \
  -d "grant_type=password" \
  -d "scope=openid profile email groups" \
  "${AUTH_SERVER_URL}" | jq -r '.access_token')

# fetch token from dex
export ARGOCD_AUTH_TOKEN=$(curl -sSL "https://${ARGOCD_SERVER}/api/dex/token" \
  --user "argo-cd-cli:" \
  --data-urlencode "connector_id=authentik" \
  --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
  --data-urlencode "scope=openid profile email groups" \
  --data-urlencode "requested_token_type=urn:ietf:params:oauth:token-type:access_token" \
  --data-urlencode "subject_token=$AUTH_ACCESS_TOKEN" \
  --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:access_token" \
  --data-urlencode "audience=argo-cd-cli" \
  | jq -r '.access_token')

# test access
argocd account get-user-info
Logged In: true
Username: ICB0ZXN0LXVzZXIJYXV0aGVudGlr
Issuer: https://argocd.example.com/api/dex
Groups: test-group

```
