### ISSUE TITLE
helm repo values in git!!!

### ISSUE THREAD

**Issue by herozabbix** [argoproj/argo-cd#4425]
### application config
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: 'https://xxx/chartrepo/library'
    targetRevision: 0.1.1
    helm:
      valueFiles:
        - values.dev.yaml
      parameters:
        - name: image.version
          value: 55v23ee4
    chart: demo
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
```

* I want to update the app's helm Image.version to git Commit number when gitLAB commits. What should I do
