### ISSUE TITLE
Parameters passed declaratively needs to be quoted

### ISSUE THREAD

**Issue by MeNsaaH** [argoproj/argo-cd#4428]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Parameters passed to helm's chart declaratively needs to be quoted

**To Reproduce**
This works
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.4
    chart: redis
    helm:
      releaseName: redis
      parameters:
        - name: "usePassword"
          value: "false"
        - name: "cluster.slaveCount"
          value: "1"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
But when I use the manifests below it fails
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.4
    chart: redis
    helm:
      releaseName: redis
      parameters:
        - name: "usePassword"
          value: false
        - name: "cluster.slaveCount"
          value: 1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Expected behavior**

Passing variables without quotes should infer the type of the variables

**Error**

```
The Application "redis" is invalid: 
* spec.source.helm.parameters.value: Invalid value: "boolean": spec.source.helm.parameters.value in body must be of type string: "boolean"
* spec.source.helm.parameters.value: Invalid value: "integer": spec.source.helm.parameters.value in body must be of type string: "integer"

```

**Version**
 1.7.6 Installed from Helm's Chart version 2.7.4

**Comment by alexmt** [comment]
The helm parameters eventually translated to `helm template --set` so all parameters either way must be formatted as strings. There is an opposite issue: values like '1' or 'true' will be converted to integer or boolean. To force string type you can use `forceString`:

```yaml
      parameters:
        - name: "usePassword"
          value: "false"
          forceString: true
```

Add example to documentation: https://github.com/argoproj/argo-cd/pull/4431/files

**Comment by MeNsaaH** [comment]
Also the error should be more clear. It should state the values been affected if possible.

**Comment by MeNsaaH** [comment]
I'll like to work on the error string. Can you please help point me to any useful resource @alexmt in the code I can start from

**Comment by Keralin** [comment]
I'm using ArgoCD 1.7.7 version and this behaviour it's happenning.
```yaml
- name: "HTTProxy.create"
  value: "false"
  forceString: true
```

And the answer from ArgoCD stills like @MeNsaaH 
```bash
spec.source.helm.parameters.value: Invalid value: "boolean": spec.source.helm.parameters.value in body must be of type string: "boolean"

I'm doing something wrong? Looks like this is the way to solve this problem but looks like it isn't working.
