### ISSUE TITLE
How to use the CreateNamespace option in syncOptions?

### ISSUE THREAD

**Issue by jamesla** [argoproj/argo-cd#4438]
I have an application with the following syncoptions:

```
syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
```

When it syncs it throws the following error:

```
namespaces "myNamespace" not found
```

I can't understand why it is not creating this namespace even though I have CreateNamespace=true set. 

Is there something else that needs to be set in order for argo to create namespaces automatically?

**Comment by mayzhang2000** [comment]
Is "mayNamespace" what you defined in your application spec as below:
```
spec:
  destination:
    namespace: mayNamespace
```?

**Comment by jamesla** [comment]
@mayzhang2000 Yep namespace is being set and if I create the namespace manually it deploys it all properly into the correct namespace.

I use helm so don't mind the templating but here is the entire argo application:


```
{{- range .Values.packages}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.name}}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{.repository}}
    targetRevision: {{.version}}
    path: {{.path}}
    helm:
      values: |
      {{- range $key, $value := .values }}
        {{ $key }}: {{ $value }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{.namespace}}
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
{{- end }}
```

**Comment by jannfis** [comment]
What version of Argo CD are you using, @jamesla? The `CreateNamespace` option was introduced with v1.7.

**Comment by jamesla** [comment]
Ah yes that was it - thanks - will manually create the namespaces for now and wait for 1.7 of the operator - cheers 👍

**Comment by vanniszsu** [comment]
can this issue re-opened?  using Helm application in operator 1.7.8,  still unable to auto create namespace

**Comment by druyang** [comment]
> can this issue re-opened? using Helm application in operator 1.7.8, still unable to auto create namespace

I am on 1.7.9 and it is also not auto-creating namespace. When I manually make the namespace everything runs fine.

**Comment by jgericke** [comment]
We found that it was necessary to deploy applications to the same namespace argocd is running in (running on version 1.7.6), and then append the syncOptions stanza below with the CreateNamespace=true item.

```
  additionalApplications:
    - name: app.name
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      project: eth2-test
      source:
        repoURL: src.url
        targetRevision: branch
        path: path.to.manifests
        directory:
          recurse: true
      destination:
          server: https://kube.uri
          namespace: target.namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        **syncOptions:
        - CreateNamespace=true**
```
