### ISSUE TITLE
bad URL endpoint link

### ISSUE THREAD

**Issue by stsang-intuit** [argoproj/argo-cd#4454]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**
Create an ingress with multiple hosts with paths defined.
After syncing in argocd, When you click on the endpoint link, it will include the path `/*`

**To Reproduce**

Create an ingress with 2 services
```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:xxxxxxxx:certificate/xxxxxxxxxxx
    alb.ingress.kubernetes.io/security-groups: cidr-ingress
    external-dns.alpha.kubernetes.io/hostname: sandbox-qal-usw2-eks-mesh-demo-e.somedomain.com,sandbox-qal-usw2-eks-mesh-demo-e-jacoco.somedomain.com
  name: ingress
spec:
  rules:
    - host: sandbox-qal-usw2-eks-mesh-demo-e-jacoco.somedomain.com
      http:
        paths:
          - backend:
              serviceName: jacoco-server-service
              servicePort: 443
            path: /*
    - host: sandbox-qal-usw2-eks-mesh-demo-e.somedomain.com
      http:
        paths:
          - backend:
              serviceName: mesh-demo-e-appd-service
              servicePort: 443
            path: /*

```

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**
The URL endpoint should not append the path, if it is '/*'

**Screenshots**

<img width="403" alt="Screen Shot 2020-09-29 at 11 58 10 AM" src="https://user-images.githubusercontent.com/26099223/94619123-2cb3db80-0261-11eb-9bd1-f0e623467ad0.png">

**Version**

```shell
v1.7.6+f5c72fa.dirty
```

**Logs**
