### ISSUE TITLE
Question: How to ignore config differences in a serviceaccount code

### ISSUE THREAD

**Issue by wouter2397** [argoproj/argo-cd#4467]
Hello,

We sync a serviceaccount through ArgoCD.
OpenShift is linking several secrets and imagepullsecrets to this serviceaccount which makes the actual config different.

I follow this documentation [Diffing Customization](https://argoproj.github.io/argo-cd/user-guide/diffing/#diffing-customization) to let ArgoCD ignore these configuration differences.

The only problem I have now is that the kind 'serviceaccount does not have a api group.
Can someone please help me and tell me what I need to configure in the code below:
``` yaml
spec:
  ignoreDifferences:
  - group: ...
    kind: Serviceaccount
    jsonPointers:
    - /imagePullSecrets
    - /secrets
```

Note:  The documentation itself is quite unclear on where the config needs to be placed. Later I found another reference where it stated that it needs to be in the application config of ArgoCD.
