### ISSUE TITLE
Unable to install jfrog helm charts as helm dependency

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [argoproj/argo-cd#4480]
**Describe the bug**

Unable to install jfrog helm charts as helm dependency from a git repo source

**To Reproduce**

1. create files in a git repo.

### Chart.yaml

`name: artifactory-oss`

### requirements.yaml

```
dependencies:
  - name: jfrog/artifactory-oss
    version: 3.1.0
    repository: https://repo.chartcenter.io
```

### values.yaml

```
# Default values for artifactory-jcr.
# This is a YAML-formatted file.

# Beware when changing values here. You should know what you are doing!
# Access the values with {{ .Values.key.subkey }}

# This chart is based on the main artifactory chart with some customizations.
# See all supported configuration keys in https://github.com/jfrog/charts/tree/master/stable/artifactory

## All values are under the 'artifactory' sub chart.
artifactory:

  ## Artifactory
  ## See full list of supported Artifactory options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  artifactory:
    ## Default tag is from the artifactory sub-chart in the requirements.yaml
    image:
      registry: docker.bintray.io
      repository: jfrog/artifactory-oss
      # tag:
    ## Uncomment the following resources definitions or pass them from command line
    ## to control the cpu and memory resources allocated by the Kubernetes cluster
    resources: { }
    #  requests:
    #    memory: "1Gi"
    #    cpu: "500m"
    #  limits:
    #    memory: "4Gi"
    #    cpu: "1"
    ## The following Java options are passed to the java process running Artifactory.
    ## You should set them according to the resources set above.
    ## IMPORTANT: Make sure resources.limits.memory is at least 1G more than Xmx.
    javaOpts: { }
      # xms: "1g"
      # xmx: "3g"
    # other: ""

  installer:
    platform: art-oss-helm

  installerInfo: '{"productId": "Helm_artifactory-oss/{{ .Chart.Version }}", "features": [ { "featureId": "Platform/{{ default "kubernetes" .Values.installer.platform }}"}]}'

  ## Nginx
  ## See full list of supported Nginx options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  nginx:
    enabled: true
    tlsSecretName: ""
    service:
      type: LoadBalancer

  ## Ingress
  ## See full list of supported Ingress options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  ingress:
    enabled: false
    tls:

  ## PostgreSQL
  ## See list of supported postgresql options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  ## Configuration values for the PostgreSQL dependency sub-chart
  ## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md
  postgresql:
    enabled: true

  ## This key is required for upgrades to protect old PostgreSQL chart's breaking changes.
  databaseUpgradeReady: "yes"

  ## If NOT using the PostgreSQL in this chart (artifactory.postgresql.enabled=false),
  ## specify custom database details here or leave empty and Artifactory will use embedded derby.
  ## See full list of database options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
  # database:


## Enable the PostgreSQL sub chart
postgresql:
  enabled: true
  postgresqlPassword: password
```

**Expected behavior**

artifactory helm chart should be deployed

**Screenshots**

**Version**

```shell
v1.7.6+b04c25e
```

**Logs**

```
time="2020-10-04T13:03:02Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in btita-artifactory: rpc error: code = Unknown desc = `helm2 template . --name btita-artifactory --namespace default --kube-version 1.17 --values values.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions argoproj.io/v1alpha1 --api-versions crd.k8s.amazonaws.com/v1alpha1 --api-versions vpcresources.k8s.aws/v1beta1` failed exit status 1: Error: found in requirements.yaml, but missing in charts/ directory: jfrog/artifactory-oss" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2020-10-04T13:02:49Z" grpc.time_ms=13194.867 span.kind=server system=grpc
```

Similar issue #3981 
I tried to follow above bug and deploy it from helm repo source and it works.

**Comment by jessesuen** [comment]
Error is: `exit status 1: Error: found in requirements.yaml, but missing in charts/ directory: jfrog/artifactory-oss" `

I feel like there was another recent issue with a similar message. It implies we don't run `helm dep build` correctly.

**Comment by mayzhang2000** [comment]
This is what I observed from the log.
```
INFO[0188] helm2 dependency build                        dir="/var/folders/qy/lt9q1y9j6cz5lhf8d_7qjdf8ztg96w/T/https:__github.com_mayzhang2000_argocd-example-apps/helm-jfrog" execID=uJ5FK
DEBU[0257] Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get "http://127.0.0.1:8879/charts/index.yaml": dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "center" chart repository
Update Complete.
```

**Comment by mayzhang2000** [comment]
I tried the following without using ArgoCD and seeing the same error
```
helm2 dependency build
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading jfrog/artifactory-oss from repo https://repo.chartcenter.io
Deleting outdated charts

helm2 template .
Error: found in requirements.yaml, but missing in charts/ directory: jfrog/artifactory-oss
```

**Comment by jessesuen** [comment]
@abhinavkhanna-sf this seems to just be the behavior of helm, are you able to get this to work without argo-cd?

**Comment by abhinavkhanna-sf** [comment]
@jessesuen 
yes, I tried with helm3 and it works. 
It even works in argo-cd if I do a straight install from helm source.  Below is the application.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://repo.chartcenter.io'
    targetRevision: 3.1.0
    chart: jfrog/artifactory-oss
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
