### ISSUE TITLE
sync not happening when remote repos are referred in ArgoCD using Kustomize

### ISSUE THREAD

**Issue by s-u-b-h-a-k-a-r** [argoproj/argo-cd#4508]
Created base repo:
https://github.com/SubhakarKotta/hello-world-kustomize

Created child repo which uses base:
https://github.com/SubhakarKotta/hello-world-kustomize-preprod

Child repo kustomization.yaml referring the base repo.
 
```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - github.com/SubhakarKotta/hello-world-kustomize/base
patchesStrategicMerge:
    - deployment.yaml
```
Argocd:
Create Repository:-
https://github.com/SubhakarKotta/hello-world-kustomize-preprod
Create Application:-

```yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes
spec:
  destination:
    name: ''
    namespace: hello-kubernetes
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/SubhakarKotta/hello-world-kustomize-preprod.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
Now when any changes happens to 'https://github.com/SubhakarKotta/hello-world-kustomize-preprod.git' autosync happens properly.

Issue:
When the changes are done to base repository the argocd is not able to sync the changes made in base repository.
