### ISSUE TITLE
UI Input form for helm parameters should be redesigned 

### ISSUE THREAD

**Issue by jaideepr97** [argoproj/argo-cd#4513]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

The Argo-CD UI form for creation of a new helm application with a helm component could use a re-design to make it more intuitive for users to populate helm parameters. Currently, the form just consists of 1 input field titled "values" and it is not an intuitive approach for users to input helm parameters, which are a set of key-value pairs. Additionally, the parameters block is wrongly labeled as "values" instead of parameters in the resulting manifest leading to failure to create the application with the right parameters (screenshots included)
the manifest created looks like this:
``` 
. . .
source:
    path: helm-guestbook
    repoURL: 'https://github.com/jaideepr97/ARGOCD-EXPERIMENT'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      values: 'image.tag: $ARGOCD_APP_REVISION'
  project: ''
```
as opposed to the required format
```
. . .
 source:
    path: helm-guestbook
    repoURL: 'https://github.com/jaideepr97/ARGOCD-EXPERIMENT'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
         - name: image.tag
           value: $ARGOCD_APP_REVISION
  project: ''
```
**To Reproduce**

Try to create a helm application through the UI and input parameters in the helm section of the form, and look at the resulting yaml view 

**Expected behavior**

That particular form section should be renamed to "parameters" and should contain 2 input fields (name, value) and have an "add" and "delete" button to add/delete new key-value pair input fields if a user wishes to work with multiple parameters

Example for proposed behaviour: https://jsfiddle.net/wh75s4u0/1/ 

**Screenshots**

![argo-helm-issue1](https://user-images.githubusercontent.com/21956986/95485365-9a49c100-095f-11eb-9ede-fa4b5a47117d.png)
![argo-helm-issue2](https://user-images.githubusercontent.com/21956986/95485367-9ae25780-095f-11eb-9bcc-0ad357983e4a.png)

cc @tetchel
