### ISSUE TITLE
Resource hooks and sync loop bug

### ISSUE THREAD

**Issue by imranismail** [argoproj/argo-cd#4614]
https://youtu.be/uWuKi32SGeY

Whenever a resource hook fails, it somehow doesn't stop the app from resyncing and somehow goes into a sync loop.

The resources gets created but deleted as soon as it is recreated. This goes on an on until the sync is terminated and reattempted.

**Comment by lindsaygrace** [comment]
We're getting this too. If a database migration hook fails, it never stops syncing. You can see that the earlier hooks get created / destroyed every few seconds.

ArgoCD version v1.7.6
Kubernetes 1.16

I believe this started happening for us after upgrading to 1.7.x

We're using the following annotations on a Kubernetes job thats having the issue.

```
helm.sh/hook: 'pre-install,pre-upgrade'
helm.sh/hook-delete-policy: before-hook-creation
helm.sh/hook-weight: '-1'
```

![image](https://user-images.githubusercontent.com/36291262/98490221-f49eb000-2284-11eb-8180-9d35724c2225.png)

The job itself
![image](https://user-images.githubusercontent.com/36291262/98490601-1187b300-2286-11eb-9922-4b58ddbd5a20.png)

**Comment by snowping** [comment]
We have the same issue after we have upgrade to version 1.7.x. We also tried the argocd annotations instead of the helm but same effect. It looks like it's related to the delete policy in our case "before-hook-creation".

**Comment by zeagur** [comment]
We also having this issue with `1.7.9` on `pre-sync` hook that run flyway migration jobs before deploy an applications with kustomize, if flyway failed, argocd will start to loop sync and delete/re-create the flyway jobs until manually terminate the sync multiple times.

annotation used:
`argocd.argoproj.io/hook: PreSync`

argocd version: `1.7.9`
kubernetes version : `1.19.3`

**Comment by amartin-isp** [comment]
Responding to this issue in case someone (like me) stumbles upon this issue. As of argocd `v1.7`, it is possible to configure the retry behavior of an application configured for auto sync. 
https://github.com/argoproj/argo-cd/blob/a695aa866529f4499cc017325a6068f6b1b15566/docs/operator-manual/application.yaml#L181-L187

**Comment by loganmzz** [comment]
Encountering same issue, but my job pod is terminating in success:

```yaml
apiVersion: v1
kind: Pod
metadata:
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: xxxxx
status:
  containerStatuses:
  - containerID: ...
    lastState: {}
    name: xxxx
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: ...
        exitCode: 0
        finishedAt: "2024-06-12T10:52:03Z"
        reason: Completed
        startedAt: "2024-06-12T10:52:01Z"
```
