### ISSUE TITLE
Unable to schedule all pods on nodes with specific role

### ISSUE THREAD

**Issue by GerbenWelter** [argoproj/argo-cd#4615]
Checklist:

* [✓] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [✓ ] I've included steps to reproduce the bug.
* [✓ ] I've pasted the output of `argocd version`.

**Describe the bug**
We wish to run all ArgoCD pods on a set of designated nodes. We can only partially achieve this.

When we set the default annotations for node selection and tolerations on the namespace where ArgoCD is deployed, most pods inherit those settings except the following:

- argocd-operator-\<random string\>
- argocd-redis-ha-haproxy-\<random string\>
- argocd-redis-ha-server-0
- argocd-redis-ha-server-1
- argocd-redis-ha-server-2

**To Reproduce**

Before installing the ArgoCD operator we create its namespace the following way:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ArgoCD project for gitops
    openshift.io/display-name: ArgoCD
    openshift.io/node-selector: node-role.kubernetes.io/infra=
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Equal","key":"infra","value":"reserved"}]'
  name: infra-argocd
```

**Expected behavior**

It's expected to have all the argocd pods running on the nodes we have designated with the infra role. Also the ArgoCD pods will have inherited the same nodeSelector and tolerations keys. Manually adding these keys to the Deployment will have no effect because the operator actively removes at least the nodeSelector key.

**Version**

ArgoCD operator version 0.0.14

```shell
$ argocd version
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```
