### ISSUE TITLE
argocd do not support `env` in `Kustomization`

### ISSUE THREAD

**Issue by AlphaWong** [argoproj/argo-cd#4617]
if the Kustomization comes with `env` inside the `configMapGenerator`
```yaml
configMapGenerator:
  - name: dev.env
     env: "environment/dev.env"
```

it cannot be recognized and fail to deploy. 

# reference
https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#configmapgenerator
