### ISSUE TITLE
can't create namespace with CreateNamespace=true

### ISSUE THREAD

**Issue by suppix** [argoproj/argo-cd#4618]
Hello. 

What I do wrong ? 

Here is my app.yaml for argocd, I also use 1.7.8 argocd release. 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/system/ingress-nginx/overlays/production
    repoURL: ssh://git@git.mycompany.com:2222/deploy/repo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
```

But I get `namespaces "ingress-nginx" not found`
