### ISSUE TITLE
Declarative approach and plugins support

### ISSUE THREAD

**Issue by dmitry-semenov-rtl** [argoproj/argo-cd#4631]
We can define our own plugins and then create an app like this `argocd app create MyApp --config-management-plugin <pluginName>` and it works, the plugin is called for `MyApp`.
But when `MyApp` is an app-of-apps (MyApp --> App1) then the plugin isn't called, my App1 definition is this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://gitlab.com/myrepo
    targetRevision: HEAD
    path: app

    directory:
      recurse: true

  # plugin specific config
  plugin:
    name: replaceSecrets

  destination:
    server: https://kubernetes.default.svc
    namespace: default
```

I want the same plugin to be called on all apps.
Is it even supported? Is "plugin" section in this file a directive to use the plugin or a configuration for a plugin **if** it's going to be used?
