### ISSUE TITLE
Argocd

### ISSUE THREAD

**Issue by varshabhijeet** [argoproj/argo-cd#4648]
I want to create application in argocd only using my custom values.yaml which present in local machine or cluster how to configure application.yaml??

**Comment by alexmt** [comment]
Hello @varshabhijeet ,

I think you have two possible options:

Embed value into `values` field on application CRD:

```
  # Source of the application manifests
  source:
    helm:
      # Values file as block file
      values: |
        ingress:
          enabled: true
          path: /
```

or move values into git

https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L35
