### ISSUE TITLE
Possible to read jsonnet tla(s) from a file?

### ISSUE THREAD

**Issue by kgaurav2** [argoproj/argo-cd#4656]
jsonnet gives a way to read tla(s) from a file.
```
--ext-str-file <var>=<file> Read the string from the file
```
Also kubecfg gives this option:
```
 --ext-str-file stringArray       Read external variables with string values from files
```

Is this possible to do with argo-cd? 
It would handy:
- CI commits/pushes a change of docker-tag to a properties file
- before syncing, argo-cd reads the properties file and updates its tla(s)
- sync app.

I am new to argoCD and not sure how this can be achieved with argo-CD? 

Thanks,

**Comment by darshanime** [comment]
how about using the [`--file`](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/app.go#L201) argument?

**Comment by jessesuen** [comment]
I think the proposal seems reasonable. We need to update the spec to introduce a new field, which is a relative path to a json tla file

https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L71-L84

**Comment by jessesuen** [comment]
> how about using the --file argument?

This is for an application CR file, and unrelated to the jsonnet.

**Comment by darshanime** [comment]
ah, gotcha thanks @jessesuen. I'll look into this 👍

**Comment by irizzant** [comment]
This would be great, having to manually manage files injection in jsonnet is really something you don't want to do.

**Comment by maxbrunet** [comment]
I have created PR #7404 which would add support for files.

If you want to use files right now, this should work too in the `spec.source.directory` of your Application manifest:

```yaml
jsonnet:
  extVars:
  - name: myExtVarStringFile
    value: importstr @'my-ext-var.txt'
    code: true
  - name: myExtVarCodeFile
    value: import @'my-ext-var.libsonnet'
    code: true
  tlas:
  - name: myTlaStringFile
    value: importstr @'my-tla.txt'
    code: true
  - name: myTlaCodeFile
    value: import @'my-tla.libsonnet'
    code: true
```

The support for files is only a shorthand for the above.
