### ISSUE TITLE
unable to sync deployment with pod topologySpreadConstraints configured

### ISSUE THREAD

**Issue by sergkkaltura** [argoproj/argo-cd#4657]
**Describe the bug**

On a k8s v1.17 cluster, Pod Topology Spread Constraints won't sync once applied to a deployment. Deployment does not get the update and stays in 'OutOfSync' state.

**To Reproduce**

1) Add topologySpreadConstraints object to a pod spec under a deployment manifest, for example:
```
      topologySpreadConstraints:
      - topologyKey: zone
        maxSkew: 1
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            run: overprovisioning    
```

2) Sync the deployment in ArgoCD UI.

**Expected behavior**

Application should sync properly and topologySpreadConstraints added to the deployment.

**Screenshots**
![image](https://user-images.githubusercontent.com/57398476/97108310-61d31280-16d5-11eb-9444-1d236b1ec2c5.png)

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:34:12Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```
