### ISSUE TITLE
Unable to use multiple GitHub orgs/team for argo-rbac-cm

### ISSUE THREAD

**Issue by vrodomista** [argoproj/argo-cd#4682]
Hey all - we are trying to setup RBAC with OAuth to GitHub with Dex - and so far it has worked fabulously with a single role/group binding. We recently updated the `policy.csv` to contain the following:

```
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    g, redacted-org-1:redacted-team-1, role:org-admin
    g, redacted-org-1:redacted-team-2, role:org-admin
    p, role:developer, applications, get, redacted-project-dev/*, allow
    p, role:developer, applications, get, redacted-project-prod/*, allow
    p, role:developer, projects, get, redacted-project-dev, allow
    p, role:developer, projects, get, redacted-project-prod, allow
    g, redacted-org-2:redacted-team-3, role:developer
```

After making these changes - not only were users in `redacted-org-2:redacted-team-3` unable to login to argoCD via GitHub - but my test account who is part of both team-1 and team-2 is only showing a single group on the `user` page

```
groups:
    redacted-org-1:redacted-team-1
```

do I need to restart the argoCD server for RBAC changes to take place?

**Comment by vrodomista** [comment]
Issue was because I did not list teams and orgs in argocd-cm dex config

**Comment by rosscdh** [comment]
@vrodomista having the same issue; listed org and teams but still no result can you post more info?

**Comment by shermanericts** [comment]
I was able to set up multiple teams just fine 
```
dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-github-client-secret:dex.acme.clientID
            clientSecret: $argocd-github-client-secret:dex.acme.clientSecret
            redirectURI: $argocd-github-client-secret:dex.acme.redirectURI
            orgs:
              - name: redacted
                teams:
                  - SRE
                  - Backend_Root
```

The issue I had was my second team was a **child** github team.  Once I re-created it as a parent team and added people, it seems to work just fine.
