### ISSUE TITLE
Cluster name should be supported on AppProjects

### ISSUE THREAD

**Issue by paveq** [argoproj/argo-cd#4691]
# Summary

Cluster name feature introduced in v1.7 should be supported in AppProjects as well.

# Motivation

Should be able to give easy to remember name, instead of URL for the destination clusters in AppProject CRD.

**Comment by msonnleitner** [comment]
Also, using `server` instead `name`, URLs and IPs leak into the `AppProject`, so it they change, they would have to be changed in multiple locations

**Comment by llienard** [comment]
Hi,

It would be great to allow to use the server name in all declaratives resources (AppProject and Application).

For my case, all of my kubernetes clusters are provided by a rancher server and I need to access to the k8s cluster via the RancherAPI and so with its clusterID.

**Comment by ragarcia26** [comment]
I thought this was supported as you are able to specify a name when creating destinations in appProject, but it doesn't actually do anything. On the other hand, specifying name when creating an app seems to translate it to server before comparing against the appProject. I thought this was a bug, what is the intent behind this design?

**Comment by tgdfool2** [comment]
Same here. We are currently dynamically provisioning AKS clusters, so their URL will change every time:
![image](https://user-images.githubusercontent.com/66017789/116508820-7382b600-a8c2-11eb-98f9-8c6aa3e542d8.png)

Would be really nice to be able to configure the cluster name in the AppProject.

**Comment by jacek-jablonski** [comment]
So at the moment despite the fact that `AppProject` CRD allows specifying target cluster as name, it doesn't work, unfortunately. You need to specify cluster in `AppProject` by IP:
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
...
spec:
  destinations:
  - namespace: mynamespace
    server: https://35.35.35.35
```

and you can specify Application by cluster or IP:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  destination:
    namespace: mynamespace
    name: prod
```
