### ISSUE TITLE
Declarative setup: Unable to connect to repository: authentication required

### ISSUE THREAD

**Issue by vjtm** [argoproj/argo-cd#4726]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hi there,

I am having issues using the [declarative setup](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/) for the repositories. I am using argo-cd (v1.7.8) on k8s v1.18.8 (kind 0.9.0). ArgoCD is up and running fine.

This is the content of my ```argocd-cm``` from the ```argocd``` namespace (This is a test repo from a private project in Azure DevOps):

```argocd-cm.yaml```:
```
apiVersion: v1
data:
  repositories: |
    - url: https://dev.azure.com/vicenstomas/Test/_git/azure-pipelines-canary-k8s-manifests
      type: git
      passwordSecret:
        key: password
        name: argocd-secret
      usernameSecret:
        key: username
        name: argocd-secret
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
```
This is the ```argocd-secret.yaml``` that references the ```argocd-cm``` ConfigMap:
```
apiVersion: v1
data:
  password: <base64_password>
  username: <base64_username>
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
```
Then I run
```
$ kubectl apply -f argocd-secret.yaml
$ kubectl apply -f argocd-cm.yaml
```
The argocd web UI show the repo but in a ```Failed``` state. The logs from the ```argocd-repo-server-xxx``` pod show it is a ```error="authentication required"```

But, If I create the repo via the web UI using exactly the same URL and credentials it works perfectly fine.
I see the argocd manages the creation of the k8s secret for the credentials ```repo-dddddddd``` (d stands for digits) and uses that name in the ```argocd-cm``` as well.

For testing purposes I tried to add a public repo from github without any credentials (via yaml) and it worked fine as well.

What am I missing here? Maybe a bug?

Thanks!

**To Reproduce**

See above.

**Expected behavior**

I expect the repository to be successfully added with auth working properly. Addingit via the web ui it works fine.

**Screenshots**

**Version**

```shell
argocd: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:33:00Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:34:12Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
Web UI -> Settings -> Repositories
CONNECTION STATUS column
Failed (Unable to connect to repository: authentication required)
```
