### ISSUE TITLE
PreSync hooks failing due to missing namespace even though CreateNamespace=true is set

### ISSUE THREAD

**Issue by elemental-lf** [argoproj/argo-cd#4753]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I've observed that `PreSync` hooks are failing if the namespace doesn't exist even though `CreateNamespace=true` is set. In the case described below synchronization of the application fails in a `PreSync` hook with an error message of `namespaces "beta" not found`.

 If I create the namespace in question the execution of the hooks proceeds.

This bug is actually in https://github.com/argoproj/gitops-engine/ but I wasn't sure if I should open the issue here or there.

**To Reproduce**

I'm trying to install a Helm chart which includes some resources with the `helm.sh/hook: pre-install,pre-upgrade` annotation set:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: beta-api
  labels:
    {{ include "beta.labels" . | nindent 4 }}
    tier: backend
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
[...]
```

The namespace doesn't exist but the application has `CreateNamespace=true` set and some other synchronization options set:

```yaml
  destination:
    namespace: beta
    name: <redacted>
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 60s
        limit: 1000000
    syncOptions:
      - "CreateNamespace=true"
```

**Expected behavior**

ArgoCD should create the namespace before running `PreSync` hooks.

**Version**

```shell
argocd: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:54:55Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:56:23Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
time="2020-11-04T16:38:21Z" level=info msg="apply failed" application=<redacted> dryRun=false message="namespaces \"beta\" not found" syncId=00075-abUEC task="PreSync/-10 hook /Secret:beta/beta-api nil->obj (,,)"
time="2020-11-04T16:38:21Z" level=info msg="adding resource result, status: 'SyncFailed', phase: 'Failed', message: 'namespaces \"beta\" not found'" application=<redacted> kind=Secret name=beta-api namespace=beta phase=PreSync syncId=00075-abUEC
```

**Comment by mayzhang2000** [comment]
I tried the following steps and could not reproduce it.

1. Create an app
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mayhook
  namespace: argocd-e2e
spec:
  destination:
    namespace: bug1104
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bug
    repoURL: https://github.com/mayzhang2000/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
```
2. Source contains PreSync hook: https://github.com/mayzhang2000/argocd-example-apps/blob/master/bug/presynchook.yaml
3. Sync and verified namespace `bug1104` is created.

![image](https://user-images.githubusercontent.com/7737306/98161069-01419380-1e94-11eb-9396-9133713839b5.png)
