### ISSUE TITLE
Applications list should dynamically update available filters

### ISSUE THREAD

**Issue by josecv** [argoproj/argo-cd#4784]
# Summary

Imagine I go into the applications list and filter the apps based on some label. If I then want to apply a second filter based on a different label, argo-cd will offer me all possible label values, regardless of whether any applications will match both the second and the first label.

Similarly, the checkboxes will show how many applications are Healthy/Degraded/etc, and allow us to filter based on application state. However, the numbers next to these checkboxes don't update on the basis of any currently applied filters.

# Motivation

Suppose I have three apps, `app-a`, `app-b`, `app-c`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: dev
    my-custom-label: foo
  name: app-a
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: staging
    my-custom-label: bar
  name: app-b
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: dev
    my-custom-label: baz
  name: app-c
```

If I go into the applications list, and filter by `app.kubernetes.io/instance=dev`, argocd will then offer me to filter by `my-custom-label=bar`, even though `app-b` -- the only app that would match that filter -- has already been filtered out by `app.kubernetes.io/instance=dev`.

This adds lots of noise and makes it difficult to use the applications list, especially when the argo-cd instance is shared by multiple different teams that are each creating their own label filters.

# Proposal

If applying a filter would result in 0 apps being visible, that filter should not be offered to the user.
