### ISSUE TITLE
Provide a way to pause syncing an application

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4808]
# Summary

Provide a way to pause syncing an application

# Motivation

I have an application which is broken. I can delete the application in argocd and then argocd will recreate it. Currently that just recreates it in its broken state. I'd like to be able to tell argocd to "pause" its syncs for this application, let me delete the application, and then after I fix the underlying state (possibly by deleting some PVCs), I would then "unpause" it and let argocd recreate the application properly.

# Proposal

An option in app details?

**Comment by jannfis** [comment]
Isn't this basically achievable by just turning off auto sync?

**Comment by jsoref** [comment]
I think that autosync in my case is controlled by the parent application which means that if i try to turn it off, when the parent syncs, it's overridden, although i could be wrong.

Certainly, if I try to change the branch of a child application then when the parent application syncs it overwrites the branch.

**Comment by jsoref** [comment]
Note:
1. If the behavior of these two things is different (i.e. that one can safely change one but not the other), then the UI should make that clear.
1. The UI should really make it clear that fields (e.g. branch on a child application) will be overwritten on the next sync of their parent.

**Comment by jessesuen** [comment]
I agree with @jannfis that this just sounds like auto-sync enabled/disabled.

> I think that autosync in my case is controlled by the parent application which means that if i try to turn it off, when the parent syncs, it's overridden, although i could be wrong.

Wouldn't you just have the same problem with a new pause field?

**Comment by jsoref** [comment]
It would have to not be something which is controlled by the versioned content -- a strict local overlay.

**Comment by vikas027** [comment]
> Isn't this basically achievable by just turning off auto sync?

Yes, it is but it is still useful to have a _maintenance_ mode which just stops all syncing across the cluster.

**Comment by renaudguerin** [comment]
> > Isn't this basically achievable by just turning off auto sync?
> Yes, it is but it is still useful to have a _maintenance_ mode which just stops all syncing across the cluster.

Exactly. Very interested in this feature too, as we have ArgoCD managed by itself and we have to go back to the root manifests and commit things to git whenever we need to temporarily disable `selfHeal` in an `Application` several levels below.

**Comment by agaudreault-jive** [comment]
I have the same use case, I also tried to configure diffing on the parent application, with the code below, however, if the parent application detect that the app is OutOfSync for any other reason or if a manual sync is done on the parent application, then it will re-apply what is configured in the source control.

The only way to turn off automated sync when the app is managed as code, is to do a PR and update the source code. 

We would need another way because disabling it in the UI would be crucial for urgent operations, such as someone on-call in the middle of the night that cannot update the source control due to branch protection in place.

I agree that the title of this question is misleading 😅 

Config on parent app:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-sync-parent
spec:
  # ...
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Automated sync enabled by default on child app:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example2-diffed
spec:
  # ...
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Comment by leoluz** [comment]
@agaudreault-jive wrote:
> I have the same use case, I also tried to configure diffing on the parent application, with the code below, however, if the parent application detect that the app is OutOfSync for any other reason or if a manual sync is done on the parent application, then it will re-apply what is configured in the source control.

This will be addressed by https://blog.argoproj.io/new-sync-and-diff-strategies-in-argocd-44195d3f8b8c

**Comment by agaudreault-jive** [comment]
@leoluz I havent, It seemed too hack-ish to use the sync windows as a process to disable the sync during emergencies.
I will try to add the following configuration when I have the time to test master locally or when 2.3 is released.

```yaml
# Allow the Application sync behavior to be overwritten in ArgoCD UI
resource.customizations.ignoreDifferences.argoproj.io_Application: |
      managedFieldsManagers:
        - argocd-server
      jsonPointers:
        - /spec/syncPolicy/automated
```
This seems like it could work, and it will be applied only for the automated fields

**Comment by rishabh625** [comment]
@agaudreault-jive : You mean to say pause syncing an application feature or presence of ignoreDifferences field is not implemented in appplicationset?

and yaml mentioned in [#542](https://github.com/argoproj/applicationset/discussions/542) quite works

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'example.{{name}}'
    spec:
      destination:
        namespace: argocd-e2e
        name: '{{name}}'
      project: default
      source:
        path: apps/example
        repoURL: https://github.com/user/repo
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
         - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          managedFieldsManagers:
            - argocd-server
          jsonPointers:
            - /spec/syncPolicy/automated
```

**Comment by agaudreault-jive** [comment]
> @agaudreault-jive : You mean to say pause syncing an application feature or presence of ignoreDifferences field is not implemented in appplicationset?

pause syncing an application created/managed by an ApplicationSet.

It actually does not and it is listed in the current [limitations](https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#limitation-no-support-for-manual-edits-to-individual-applications ).
Since last time I checked the documentation, an issue has been opened https://github.com/argoproj/applicationset/issues/186 

The presence of the ignore difference in ApplicationSet is [another limitation](https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#limitation-applicationset-controller-will-not-selectively-ignore-changes-to-individual-fields), but the implementation would be one way to fix this issues

**Comment by rishabh625** [comment]
ohk got it sorry I overlooked actual issue and thought it as yaml deployment issue, looks like a must feature, although links mentions a limitation arises by design but I too feel it would be a good feature

**Comment by thiagolsfortunato** [comment]
Any news?

I'm experiencing the same issue.

To disable in the YAML manifest I set `syncPolicy: {}` but I would like to keep the `syncOption`, and today is impossible to have both.

```
syncPolicy:
    syncOptions:
      - FailOnSharedResource=true
```

**Comment by sondrelg** [comment]
I have a use-case that I don't see mentioned yet.

We have an automated build pipeline that will build, tag, and push docker images to a registry when code is merged into the main branch of our project. We also have an argocd image watcher process monitoring our registry for new image versions. When it finds one, it updates our deployment manifest image tag. This works well, and for our biggest project we'll manually sync changes a few times per day.

Every now and then we'll have an issue flagged in staging, so we know that syncing the same image to production will introduce an issue. Suddenly it can be critical that no one manually syncs prod.

The easiest way to resolve the problem is to push a fix and wait for a new image to build, but that can take upwards of 30 minutes.

Today we're relying on communicating issues like these using slack, but that's not a great solution. It would be much more useful for us to be able to instead temporarily disable, or lock syncing for a project until the issue is resolved.

**Comment by jannfis** [comment]
@sondrelg I think that could be easily accomplished by configuring a blocking [sync window](https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/) in these cases.

**Comment by sondrelg** [comment]
Ok I'll take a look! Thanks a lot 🙂 

Do you know if there's a way to set windows in the ArgoCD UI? The docs seem to suggest not, but we're not really using the CLI 🙈 If not, I guess this might be a good reason to adopt it.

**Comment by sondrelg** [comment]
Am I correct in my interpretation here?

It looks like using windows would mean we would first take a guess at how long it will take us to resolve the issue. We might say "let's free syncs for 30 minutes" and create a window with ~: 

````
  - kind: deny
    schedule: '37 13 * * *'  # outage started 13:37
    duration: 30m  # we think it will be resolved in 30 minutes
    applications:
    - '<our app>'
 ```

But then if our fix is delayed, we would need to "top up" the window, right? And If we *do* resolve it in the 30 minutes and someone decides to just let the window expire and not clean up the window, then tomorrow at 13:37 syncs will be blocked again for 30 minutes?

I see how we might be able to use this, but seem like a tool with pretty serious flaws for our use-case tbh. Maybe I'm misunderstanding something? 🙇
