### ISSUE TITLE
Support IAM Authentication from ArgoCD clients

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#481]
As an alternative to JWT tokens, there is an upcoming need to authenticate to ArgoCD at an AWS account level, using IAM roles. After discussion with @wanghong230, @edlee2121, and @gaganapplatix we could use the techniques employed by [AWS IAM Authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) (previously known as Heptio authenticator).

The client will make a call to sts:GetCallerIdentity API to generate a pre-signed URL which would be supplied in lieu of the JWT token. Upon receipt, the API server will submits the request to the real https://sts.amazonaws.com server, which validates the client's HMAC signature and returns information about the user.

This type of authentication would be used by automation pipelines from external AWS accounts, and would negate the need to store and/or rotate any tokens stored in CI systems.

Here is an example config snippet which IAM authenticator uses:

```
    data:
      config.yaml: |
        # a unique-per-cluster identifier to prevent replay attacks
        # (good choices are a random token or a domain name that will be unique to your cluster)
        clusterID: some-cluster-name.cluster.k8s.local
        server:
          mapRoles:
          - roleARN: arn:aws:iam::111222333444:role/some_role_name
            username: acme-{{SessionName}}
            groups:
            - somek8s:groupname
```

We would need to store a similar mapping of roleARN to our own ArgoCD RBAC privileges. I think for ease of use, we can only support this mode for project tokens.
