### ISSUE TITLE
Authentication required with declarative setup

### ISSUE THREAD

**Issue by MrJinggles** [argoproj/argo-cd#4818]
Hi there,

I am having issues using the declarative setup for the repositories. I am using argo-cd (v1.7.8) on k8s v1.18.8 (kind 0.9.0). ArgoCD is up and running fine.

This is the content of my ```argocd-cm``` from the ```argocd``` namespace (This is a test repo from a private project in Azure DevOps):

```argocd-cm.yaml```:
```
apiVersion: v1
data:
  repositories: |
    - url: https://dev.azure.com/vicenstomas/Test/_git/azure-pipelines-canary-k8s-manifests
      type: git
      passwordSecret:
        key: password
        name: repo-secret
      usernameSecret:
        key: username
        name: repo-secret
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
```
This is the ```repo-secret.yaml``` that references the ```argocd-cm``` ConfigMap:
```
apiVersion: v1
data:
  password: <base64_password>
  username: <base64_username>
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
type: Opaque
```
Then I run
```
$ kubectl apply -f argocd-cm.yaml
```
The argocd web UI show the repo but in a ```Failed``` state. The logs from the ```argocd-repo-server-xxx``` pod show it is a ```error="authentication required"```

But, If I create the repo via the web UI using exactly the same URL and credentials it works perfectly fine.
I see the argocd manages the creation of the k8s secret for the credentials ```repo-dddddddd``` (d for digits) and uses that name in the ```argocd-cm``` as well.

For testing purposes I tried to add a public repo from github without any credentials (via yaml) and it worked fine as well.

What am I missing here? Maybe a bug?

Thanks!

_Originally posted by @vjtm in https://github.com/argoproj/argo-cd/issues/1491#issuecomment-717846308_

Hi, I just can say, that I have the exact same problem!

Versions are:
- ArgoCD v1.7.8+ef5010c
- K8s 1.19.3

On an "older" server everything works fine including the declarative setup!
The versions on the older ones:
- ArgoCD v1.7.6+b04c25e
- K8s 1.17.4
