### ISSUE TITLE
Custom config management plugin commands are executed at application path, not repository root

### ISSUE THREAD

**Issue by megakoresh** [argoproj/argo-cd#4831]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Custom plugins execute `init` and `generate` commands at specified application path, not root of the repository.

**To Reproduce**

Patch `argocd-cm`:

```yaml
    configManagementPlugins: |
      - name: vault-secrets-kustomize
        init:
          command: ["sh", "-c"]
          args: ["make generate-secrets ENV=$ENV SERVICE=$SERVICE_NAME"]
        generate:
          command: ["sh", "-c"]
          args: ["kustomize build $ARGOCD_APP_SOURCE_PATH"]
```

Application:

```yaml
spec:
  source:
    repoURL: https://my-github.com/companyuser/the-repo
    targetRevision: master
    path: path/to/kustomize/overlay
    plugin:
      name: vault-secrets-kustomize
      env: []
```

Have a makefile with target `generate-secrets` in the repo root, as usual.

**Expected behavior**

Application is created successfully

**Version**

```shell
argocd: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:54:55Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:34:12Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
time="2020-11-14T20:20:45Z" level=info msg="make generate-secrets ENV=$ENV SERVICE=$SERVICE_NAME" dir="/tmp/https:my-github.com_companyuser_the-repo/path/to/kustomize/overlays" execID=vGWzi
time="2020-11-14T20:20:45Z" level=error msg="`make generate-secrets ENV=$ENV SERVICE=$SERVICE_NAME` failed exit status 2: make: *** No rule to make target 'generate-secrets'.  Stop." execID=vGWzi
```

This is caused by https://github.com/argoproj/argo-cd/blob/ccb7371047ff0756f2b4617685d22d40e9d2e360/reposerver/repository/repository.go#L991

It seems unlikely that it would be intentional, as I see no use-case where such behavior would be desired, given the path is already available at `$ARGOCD_APP_SOURCE_PATH` specifically to reference it for such purpose, so I am filing this as a bug report. Please reclassify if this behavior is intended for some reason.

UPD: Same is for `generate` commands.
