### ISSUE TITLE
Problem with jsonnet lib

### ISSUE THREAD

**Issue by antonionappi88** [argoproj/argo-cd#4839]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hello,
I'm trying to deploy a Jsonnet application using ArgoCD but I'm getting strange behaviour.
This is the structure of my directory.

```bash
prometheus-operator-v3
├── application.yaml
├── jsonnetfile.json
├── jsonnetfile.lock.json
├── pushgateway.jsonnet
└── vendor
    ├── github.com
    │   ├── ksonnet
    │   │   └── ksonnet-lib
    │   │       ├── ksonnet.beta.3
    │   │       │   ├── k8s.libsonnet
    │   │       │   └── k.libsonnet
    │   └── latchmihay
    │       └── kube-prometheus-pushgateway
    │           └── prometheus-pushgateway
    │               ├── jsonnetfile.json
    │               └── pushgateway.libsonnet
    ├── ksonnet -> github.com/ksonnet/ksonnet-lib
    └── prometheus-pushgateway -> github.com/latchmihay/kube-prometheus-pushgateway/prometheus-pushgateway
```

I have a .gitignore like this:
```bash
jsonnetfile.json
jsonnetfile.lock.json
#*.jsonnet
#!pushgateway.jsonnet
application.yaml
```

And my `application.yaml`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway-v3
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    path: prometheus-operator-v3
    repoURL: https://github.com/whatever/argo-test.git

    # directory
    directory:
      recurse: false
      jsonnet:
        # A list of Jsonnet External Variables
        extVars:
        - name: PUSHGATEWAY_PRODUCER
          value: jeedy-internal
          # You can use "code to determine if the value is either string (false, the default) or Jsonnet code (if code is true).
        - name: PUSHGATEWAY_EXTERNAL_URL
          value: argo-test.com
        - name: PUSHGATEWAY_MONIT_PROMETHEUS_ENABLED
          value: "true"
        - name: NAMESPACE
          value: test-vendor
        libs:
        - vendor
        
  destination:
    server: https://kubernetes.default.svc
    namespace: test-vendor

  # Sync policy
  syncPolicy:
    automated: 
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')
    - CreateNamespace=true
```
**To Reproduce**
I push to my repository the following pushgateway.jsonnet file:

```jsonnet
// Ingress section 
// https://github.com/coreos/kube-prometheus/blob/master/docs/exposing-prometheus-alertmanager-grafana-ingress.md
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local label_release = "prometheus-operator-jeedy";
local secret = k.core.v1.secret;
local ingress = k.extensions.v1beta1.ingress;
// Not used
local ingressTls = ingress.mixin.spec.tlsType;
local ingressRule = ingress.mixin.spec.rulesType;
local httpIngressPath = ingressRule.mixin.http.pathsType;
// End ingress section 
local pushgatewayExternalUrl = std.extVar("PUSHGATEWAY_EXTERNAL_URL");
local monitPrometheusEnabled = std.extVar("PUSHGATEWAY_MONIT_PROMETHEUS_ENABLED");
local producer = std.extVar("PUSHGATEWAY_PRODUCER");
local namespace = std.extVar("NAMESPACE");
local add_relabeling_to_endpoints() = (
  {
      relabelings+: [
                  {
                    targetLabel: 'monit_forward',
                    replacement: monitPrometheusEnabled,
                  },
                  {
                    targetLabel: 'producer',
                    replacement: producer,
                  },
                ],
  }
 );


local kp =
  (import "prometheus-pushgateway/pushgateway.libsonnet") +
  {
    _config+:: {
      namespace: namespace,
    },
   pushgateway+::{
      serviceMonitor+:{
        metadata+:{
            labels+: {
              release: label_release,
            },
        },
        spec+:{
            endpoints: std.map(function(v) v + add_relabeling_to_endpoints(), super.endpoints)
        },
      },
    },
    ingress+::{
      'pushgateway':
        ingress.new() +
        ingress.mixin.metadata.withName('pushgateway') +
        ingress.mixin.metadata.withNamespace($._config.namespace) +
        ingress.mixin.spec.withRules(
          ingressRule.new() +
          ingressRule.withHost(pushgatewayExternalUrl) +
          ingressRule.mixin.http.withPaths(
            httpIngressPath.new() +
            httpIngressPath.mixin.backend.withServiceName($.pushgateway.service.metadata.name) +
            httpIngressPath.mixin.backend.withServicePort('http')
          ),
        ),
    },
  };

[kp.pushgateway[i] for i in std.objectFields(kp.pushgateway)]
```
This produce an array of deployment,service and servicemonitor objects.

But ArgoCD complains with:

```bash
rpc error: code = FailedPrecondition desc = Failed to evaluate jsonnet "pushgateway.jsonnet": RUNTIME ERROR: couldn't open import "prometheus-pushgateway/pushgateway.libsonnet": no match locally or in the Jsonnet library paths /tmp/https:__gitlab.cern.ch_anappi_argo-test/prometheus-operator-v3/pushgateway.jsonnet:37:4-57 thunk <kp> from <$> /tmp/https:__gitlab.cern.ch_anappi_argo-test/prometheus-operator-v3/pushgateway.jsonnet:71:46-48 <std>:1293:24-25 thunk from <function <anonymous>> <std>:1293:5-33 function <anonymous> /tmp/https:__gitlab.cern.ch_anappi_argo-test/prometheus-operator-v3/pushgateway.jsonnet:71:29-61 $ During evaluation
```
To fix i have to add the `vendor` in front of the import directives. Shouldn't the libs section in the application.yaml take care of it ?

Than even if I fix the import adding the vendor in front of the paths(in the pushgateway.jsonnet), I get this error:
```bash
rpc error: code = FailedPrecondition desc = Failed to evaluate jsonnet "pushgateway.jsonnet": RUNTIME ERROR: couldn't open import "ksonnet/ksonnet.beta.4/k.libsonnet": no match locally or in the Jsonnet library paths /tmp/my-repo/prometheus-operator-v3/vendor/prometheus-pushgateway/pushgateway.libsonnet:1:11-54 thunk <k> from <$> /tmp/my-repo/prometheus-operator-v3/vendor/prometheus-pushgateway/pushgateway.libsonnet:26:26-27 /tmp/my-repo/prometheus-operator-v3/vendor/prometheus-pushgateway/pushgateway.libsonnet:45:7-17 /tmp/my-repo/prometheus-operator-v3/pushgateway.jsonnet:71:2-19 thunk from <$> During manifestation
```
This because the pushgateway libsonnet import also the ksonnet one.

In general if I run jsonnet by myself on my local machine it works without problems. (jsonnet -J vendor pushgateway.jsonnet)

The only way to make it working it was to create a directory and put all the libsonnet at the same level or add the vendor in front of all import paths.

**Expected behavior** 

In general I have impression that the libs fields is ignored. And ArgoCD/jsonnet should be able to resolve import path.

**Version**

```shell
argocd: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:33:00Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:34:12Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```
