### ISSUE TITLE
RBAC policy to apps from other groups

### ISSUE THREAD

**Issue by tiagocborg** [argoproj/argo-cd#4887]
I want to show each group only apps that belong to their project.

The project policy is working fine, only people from `myproject:guest` can sync, other people can´t sync, but still can see the apps on the dashboard. I want other groups to not be able to see at all.

Policy on the project manifest:
```
- name: myproject-guest
  description: Previlegies for myprojectguests
  policies:
   - p, proj:myproject:myproject-guest, applications, get, insiderlog/*, allow
   - p, proj:myproject:myproject-guest, applications, sync, insiderlog/*, allow
   groups:
   - myproject:guest
```

I tried to add this to the RBAC config file, but no dice:
```policy.default: role:readonly
  policy.csv: |
  p, role:cluster-admin, *, *, */*, allow
  g, admin, role:cluster-admin
  p, role:guest, *, *, *, deny   p, role:guest, *, *, */*, deny
  g, otherproject:guest, role:guest```
