### ISSUE TITLE
helm url values.yaml not refreshing

### ISSUE THREAD

**Issue by krisdevopsbot** [argoproj/argo-cd#4889]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Created application with one of the values files coming from a url. A refresh of the application does not pull new values from the url if they are updated if there is no associated git commit. 

In my use case, the external url is rendered by a templating engine fed by our config management tool data

URL support was added in https://github.com/argoproj/argo-cd/issues/624

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      - "https:/example.com/values.yaml"
    path: app
    repoURL: https:/....../helm-chart.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Expected behavior**

Refresh should pick up the new value from the url hosted values.yaml..

If I push a dummy commit to git, it will notice the outofsync and pull the new url values in that case... is this intentional? or should refresh always check both git and any possible diff in url values.

**Screenshots**

**Version**

```shell
argocd: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:33:00Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
