### ISSUE TITLE
multiple application sources defined: Helm,Plugin

### ISSUE THREAD

**Issue by renexu** [argoproj/argo-cd#4910]
I have an Application Spec look like this
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: myapp-ns
spec:
  destination:
    namespace: myapp-ns
    server: https://kubernetes.default.svc
  project: my-project
  source:
    chart: my-helm-chart
    repoURL: ...
    targetRevision: 0.0.1
    plugin:
      env:
      - name: MYAPP_ENV
        value: myapp
      name: myapp_plugin
    helm:
      values: |
        name: myapp
```

And I got an error while creating this app using `argocd app create -f myapp.yaml`

```
FATA[0000] rpc error: code = Unknown desc = multiple application sources defined: Helm,Plugin
```

argocd version
```
argocd: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:43:46Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:45:07Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jessesuen** [comment]
Argo CD is pointing out the fact that we do not allow this:

```yaml
    plugin:
      env:
      - name: MYAPP_ENV
        value: myapp
      name: myapp_plugin
    helm:
      values: |
        name: myapp
```
