### ISSUE TITLE
Enable wildcard for *ResourceWhitelist/Blacklist

### ISSUE THREAD

**Issue by NissesSenap** [argoproj/argo-cd#4914]
# Summary

Enable wildcard for *ResourceWhitelist/Blacklist

# Motivation

Today I let my different application teams sync on specific AppProjects where i define namespaceResourceWhitelist & Blacklist.

But it's kind of a pain to manage. For example I use tekton in my cluster and as you can see bellow it have a few crd:s and thus a rather big number of groups.

```
kubectl get crd |grep tekto
clustertasks.tekton.dev                                     2020-11-18T14:14:23Z
clustertriggerbindings.triggers.tekton.dev                  2020-11-18T14:14:57Z
conditions.tekton.dev                                       2020-11-18T14:14:23Z
config.operator.tekton.dev                                  2020-11-18T14:13:54Z
eventlisteners.triggers.tekton.dev                          2020-11-18T14:14:57Z
pipelineresources.tekton.dev                                2020-11-18T14:14:24Z
pipelineruns.tekton.dev                                     2020-11-18T14:14:24Z
pipelines.tekton.dev                                        2020-11-18T14:14:24Z
runs.tekton.dev                                             2020-11-18T14:14:24Z
taskruns.tekton.dev                                         2020-11-18T14:14:24Z
tasks.tekton.dev                                            2020-11-18T14:14:24Z
triggerbindings.triggers.tekton.dev                         2020-11-18T14:14:57Z
triggers.triggers.tekton.dev                                2020-11-18T14:14:57Z
triggertemplates.triggers.tekton.dev                        2020-11-18T14:14:57Z
````

I would have to do something like:
````
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  namespaceResourceWhitelist:
  - group: 'tekton.dev'
    kind: '*'
  - group: 'triggers.tekton.dev'
    kind: '*'
... etc
````

# Proposal

Enable wildcards on groups.
So i can do something like:
````
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  namespaceResourceWhitelist:
  - group: '*.tekton.dev'
    kind: '*'
````
**Notice * in-front of .tekton.dev**

I know this will potentially issues since we are not being as specific but I think the bad parts/risks will be outweighs by the administrative work being saved.

**Comment by jessesuen** [comment]
This is a bug, we are using the wrong globber to match on resources.

https://github.com/argoproj/argo-cd/blob/6ef89e3c096dc43532abf0ba80f3f319f1293fa1/pkg/apis/application/v1alpha1/types.go#L2421

**Comment by chetan-rns** [comment]
There's already `globMatch()` function in the same file. Happy to raise a PR with a test

**Comment by jessesuen** [comment]
@chetan-rns - @alexmt actually thinks this feature should be working for the example in the description:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  namespaceResourceWhitelist:
  - group: '*.tekton.dev'
    kind: '*'
```

Have we verified something else (aside from the glob function) is preventing this from working?
