### ISSUE TITLE
multiple application sources defined: Ksonnet,Plugin

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#4922]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Unable to set env for plugin source app. Similar error as #1054 but in this case there is no ksonnet source in the app spec.

**To Reproduce**

Create an app with plugin source

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: my-apps
  source:
    path: my-app
    plugin:
      name: my-plugin
    repoURL: my-repo
```

Try set env from CLI

```
❯ argocd app set my-app --env FOO='bar'
FATA[0005] rpc error: code = Unknown desc = multiple application sources defined: Ksonnet,Plugin
```

**Expected behavior**

Set env in as

```
spec:
  source:
    plugin:
      env:
        - name: FOO
          value: bar
```

**Screenshots**

**Version**

```shell
argocd: v1.7.10+bcb05b0.dirty
  BuildDate: 2020-11-21T00:34:29Z
  GitCommit: bcb05b0c2e0f8006aa2d2abaf780e73c9e73c945
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.0+a0c4b66
  BuildDate: 2020-11-26T07:34:15Z
  GitCommit: a0c4b663a2f36be1a4f5064e4cbd2ef15018b778
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.0+g7090a89
  Kubectl Version: v1.17.8
```

**Logs**

```
 time="2020-11-27T09:02:02Z" level=error msg="finished unary call with code Unknown" error="multiple application sour
 ces defined: Ksonnet,Plugin" grpc.code=Unknown grpc.method=UpdateSpec grpc.service=application.ApplicationService gr
 pc.start_time="2020-11-27T09:02:00Z" grpc.time_ms=2981.155 span.kind=server system=grpc
```
