### ISSUE TITLE
Argocd cannot create cluster resources even though my project has permission to do it

### ISSUE THREAD

**Issue by rodrigo-loza-mojix** [argoproj/argo-cd#4932]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

My application is not able to create **cluster resources** even though my linked project has permission to do it.

**To Reproduce**

1. Create a project with permission to create **cluster resources**.

![Screen Shot 2020-11-30 at 10 43 04 AM](https://user-images.githubusercontent.com/49159808/100623810-09f18200-32f9-11eb-8038-a11add3d6ee8.png)

2. Create an application with the configured project.

3. In the git repository add a template yaml for a persistent volume or cluster role. Example with persistent volume. 

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  creationTimestamp: null
spec:
  storageClassName: manual
  volumeName: test-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
```

**Expected behavior**

Persistent volume should be created. Instead I get a **"Comparison error. ... can not be managed when in namespaceb mode"**

<img width="1020" alt="Screen Shot 2020-11-30 at 10 46 23 AM" src="https://user-images.githubusercontent.com/49159808/100624116-6785ce80-32f9-11eb-9ae1-3682e0013a5d.png">

**Version**

```shell
argocd: v1.7.8+ef5010c.dirty
  BuildDate: 2020-10-16T02:25:17Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: dirty
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:34:12Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```
