### ISSUE TITLE
Helm v3 app changing between Synced/OutOfSync (with "version: v3" diff)

### ISSUE THREAD

**Issue by MPV** [argoproj/argo-cd#4950]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Why am I getting constant diffs like this?

```diff
$ argocd app diff apps-build
===== argoproj.io/Application argocd/cluster-cert-manager-build ======
--- /var/folders/wy/snw8djrd0ml_4d9gbb9dlqzw0000gn/T/argocd-diff909742697/cluster-cert-manager-build-live.yaml	2020-12-02 13:46:44.000000000 +0100
+++ /var/folders/wy/snw8djrd0ml_4d9gbb9dlqzw0000gn/T/argocd-diff909742697/cluster-cert-manager-build	2020-12-02 13:46:44.000000000 +0100
@@ -25,6 +25,7 @@
       - values.yaml
+      version: v3
     path: umbrellas/cluster-cert-manager
     repoURL: git@obfuscated
   syncPolicy:
```

My app keeps being synced/out-of-sync:

```shell
$ argocd app get apps-build
Name:               apps-build
Project:            default
Server:
Namespace:          argocd
URL:                https://127.0.0.1:61711/applications/apps-build
Repo:               git@obfuscated
Target:
Path:               argocd-apps/build
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        OutOfSync from  (7e4fc49)
Health Status:      Healthy

GROUP        KIND         NAMESPACE  NAME                         STATUS     HEALTH   HOOK  MESSAGE
argoproj.io  Application  argocd     cluster-cert-manager-build   OutOfSync  Healthy
```

Note how they fluctuate back/forth as shown in the Grafana dashboard for ArgoCD:

<img width="1668" alt="Skärmavbild 2020-12-02 kl  13 55 32" src="https://user-images.githubusercontent.com/62675/100875346-2e3e9180-34a6-11eb-8d24-c9b8f2b08534.png">

**To Reproduce**

My app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels:
  name: cluster-cert-manager-build
  namespace: argocd
spec:
  destination:
    name: build
    namespace: cluster-cert-manager
  project: default
  source:
    helm:
      releaseName: cluster-cert-manager
      valueFiles:
        - values.yaml
      version: v3
    path: umbrellas/cluster-cert-manager
    repoURL: 'git@obfuscated
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

App being `Synced`, no diff and not `OutOfSync`.

**Version**

```shell
$ argocd version
argocd: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:35:17Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:34:12Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```
