### ISSUE TITLE
 How could a plugin generate multiple yamls as output?

### ISSUE THREAD

**Issue by hongchaodeng** [argoproj/argo-cd#4958]
ref https://github.com/oam-dev/kubevela/issues/674

Currently, the argo plugin is expected to generate **a valid yaml stream**. But in KubeVela, an appfile like the following could generate multiple yamls:

Appfile input:
```yaml
name: demo
services:
  testsvc:
    type: webservice
    image: crccheck/hello-world
    port: 8000
    route:
      domain: testsvc.example.com
```

Manifest outputs:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
...
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
...
---
apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
...
```

This would fail with error:
```
failed to unmarshal manifest: error converting YAML to JSON: yaml:
```

How could a plugin generate multiple yamls as output?
