### ISSUE TITLE
Add local account maintenance functionality to argocd-util

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#4967]
# Summary

argocd-util should provide functions to manage and maintain local user accounts for people with K8s access and permissions to manipulate resources in ArgoCD's namespace.

# Motivation

Currently, local account management is not a good user experience. Changing the password of the built-in admin account is complex and requires shell scripts and kubectl, and creating and maintaining local users is complex as well.

# Proposal

I think it would be good to introduce a new set of commands to `argocd-util`, e.g. `argocd-util accounts`, that will in the first throw

* allow creation/deletion of local accounts (`account create`/`account delete`)
* setting password for built-in admin user as well as local accounts (`account password`)
* disable admin user (`account disable`)
* change capabilities for local accounts (`account change`)

The commands should be able to either directly manipulate the resources (i.e. `argocd-cm` and `argocd-secret`) in the cluster (in case of non-declaratively managed Argo CD), or merge result with the live resources and output resource as YAML to stdout, for feeding into Git (for declaratively managed Git).

**Comment by sbose78** [comment]
Example: 

`account create` would populate
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.alice: apiKey, login
```
