### ISSUE TITLE
kustomize build failed timeout after 1m30s

### ISSUE THREAD

**Issue by windsource** [argoproj/argo-cd#5010]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When syncing an app (here argocd app managed by ArgoCD) I get the error message in the UI:

ComparisonError: rpc error: code = Unknown desc = `kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd` failed timeout after 1m30s.

When I manually call `kubectl kustomize .` in the argocd folder it takes around 53 seconds to more than a minute. Can that timeout of 1m30s be adjusted? I have already increased `--repo-server-timeout-seconds` to `180`.

**To Reproduce**

`kustomization.yaml` contains:

```yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=v1.7.10
- github.com/argoproj/argo-cd/manifests/crds?ref=v1.7.10
- github.com/argoproj/argo-cd/manifests/base/application-controller?ref=v1.7.10
- github.com/argoproj/argo-cd/manifests/base/dex?ref=v1.7.10
- github.com/argoproj/argo-cd/manifests/base/repo-server?ref=v1.7.10
- github.com/argoproj/argo-cd/manifests/base/server?ref=v1.7.10
- github.com/argoproj/argo-cd/manifests/base/redis?ref=v1.7.10

images:
- name: argoproj/argocd
  newName: argoproj/argocd
  newTag: v1.7.10

# Here we have a subset of secrets and config maps. Others might be added later on.
# Later on other ConfigMaps for roles etc. and Secrets might be added here as well
resources:
- argocd-cm.yaml
- argocd-rbac-cm.yaml
- argocd-secret.yaml
- argocd-ingress-route.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server
  path: overlays/argocd-server-deploy-command.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-application-controller
  path: overlays/argocd-application-controller-deploy-command.yaml
```

The argocd app is referenced from an app-of-apps with 10 apps in total.

**Expected behavior**

The sync succeeds even if `kustomize build` takes longer than 1m30s.

**Screenshots**

![image](https://user-images.githubusercontent.com/13716595/101643147-1af66d80-3a34-11eb-93b6-9854ccf9dd8e.png)

**Version**

```shell
argocd: v1.7.8+unknown
  BuildDate: 2020-11-14T23:34:50Z
  GitCommit: 
  GitTreeState: 
  GitTag: 1.7.8
  GoVersion: go1.15.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.10+bcb05b0
  BuildDate: 2020-11-20T19:51:39Z
  GitCommit: bcb05b0c2e0f8006aa2d2abaf780e73c9e73c945
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

The logs of argocd-repo-server:

```
time="2020-12-09T13:54:30Z" level=info msg="git fetch origin --tags --force" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=1U5u6
time="2020-12-09T13:54:31Z" level=info msg="git checkout --force 42835b2774136b35d97bd9ecb04837f484be9e40" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=znCBG
time="2020-12-09T13:54:31Z" level=info msg="git clean -fdx" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=D8psX
time="2020-12-09T13:54:31Z" level=info msg="git rev-parse HEAD" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=qwqGA
time="2020-12-09T13:54:31Z" level=info msg="kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd" dir= execID=izuMg
time="2020-12-09T13:56:01Z" level=error msg="`kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd` failed timeout after 1m30s" execID=izuMg
time="2020-12-09T13:56:01Z" level=error msg="finished unary call with code Unknown" error="`kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd` failed timeout after 1m30s" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2020-12-09T13:56:26Z" grpc.service=repository.RepoServerService grpc.start_time="2020-12-09T13:53:27Z" grpc.time_ms=154101.64 span.kind=server system=grpc
time="2020-12-09T13:56:01Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://github.com/windsource/hcloud-k3s-setup.git,Path:argocd,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:,}/42835b2774136b35d97bd9ecb04837f484be9e40"
time="2020-12-09T13:56:01Z" level=info msg="git fetch origin --tags --force" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=wrDFq
time="2020-12-09T13:56:02Z" level=info msg="git checkout --force 42835b2774136b35d97bd9ecb04837f484be9e40" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=h2X43
time="2020-12-09T13:56:02Z" level=info msg="git clean -fdx" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=3GR5W
time="2020-12-09T13:56:02Z" level=info msg="git rev-parse HEAD" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=0tVGC
time="2020-12-09T13:56:02Z" level=info msg="kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd" dir= execID=wFMhm
time="2020-12-09T13:56:02Z" level=info msg="Alloc=4995 TotalAlloc=200250 Sys=71568 NumGC=34 Goroutines=44"
time="2020-12-09T13:56:48Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://github.com/windsource/hcloud-k3s-setup.git,Path:argocd,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:,}/42835b2774136b35d97bd9ecb04837f484be9e40"
time="2020-12-09T13:57:32Z" level=error msg="`kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd` failed timeout after 1m30s" execID=wFMhm
time="2020-12-09T13:57:32Z" level=error msg="finished unary call with code Unknown" error="`kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd` failed timeout after 1m30s" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2020-12-09T13:56:47Z" grpc.service=repository.RepoServerService grpc.start_time="2020-12-09T13:53:48Z" grpc.time_ms=223697.45 span.kind=server system=grpc
time="2020-12-09T13:57:32Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://github.com/windsource/hcloud-k3s-setup.git,Path:argocd,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:,}/42835b2774136b35d97bd9ecb04837f484be9e40"
time="2020-12-09T13:57:32Z" level=info msg="git fetch origin --tags --force" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=VKkFZ
time="2020-12-09T13:57:33Z" level=info msg="git checkout --force 42835b2774136b35d97bd9ecb04837f484be9e40" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=p7sjC
time="2020-12-09T13:57:33Z" level=info msg="git clean -fdx" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=fv16O
time="2020-12-09T13:57:33Z" level=info msg="git rev-parse HEAD" dir="/tmp/https:__github.com_windsource_hcloud-k3s-setup" execID=cNmSN
time="2020-12-09T13:57:33Z" level=info msg="kustomize build /tmp/https:__github.com_windsource_hcloud-k3s-setup/argocd" dir= execID=KugaF
```
