### ISSUE TITLE
Default metrics service doesn't get metrics from all shards when using sharded controllers

### ISSUE THREAD

**Issue by jemisonf** [argoproj/argo-cd#5016]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When querying argocd metrics that include the `hostname` label, I can only see metrics from one cluster shard.

**To Reproduce**

We're using the New Relic Prometheus integration, but I don't _think_ that's required to reproduce the issue. We currently have the following controller configuration:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 2
  template:
    spec:
      ...
      containers:
        - name: argocd-application-controller
          ...
          env:
            - name: ARGOCD_CONTROLLER_REPLICAS
              value: "2
```

I'm running the following query after syncing 10 applications synchronously:

NRQL: 
```nrql
SELECT latest(argocd_kubectl_exec_total) FROM Metric SINCE 30 minutes AGO WHERE clusterName = *** FACET hostname TIMESERIES 
```

PromQL: 
```promql
sum(argocd_kubectl_exec_total) by (hostname)
```

**Expected behavior**

I'd expect to see a value for each controller, since I've confirmed from logs that both controllers are running syncs. This is what I'm seeing instead:

![6b6eef90-7b1a-47ca-8547-720cb1fb232c](https://user-images.githubusercontent.com/28904930/101702325-7bd27580-3a35-11eb-99e7-f47504092e37.png)

**Screenshots**

**Version**

```shell
➜  ~ argocd version
argocd: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:05:28Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.0+3034841
  BuildDate: 2020-12-09T18:29:09Z
  GitCommit: 30348417a9603ec1c0e40b335cdf0fd83192bad0
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

**Logs**

```
Paste any relevant application logs here.
```
