### ISSUE TITLE
application level ignore differences does not work

### ISSUE THREAD

**Issue by jetersen** [argoproj/argo-cd#5020]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Reading the docs https://argoproj.github.io/argo-cd/user-guide/diffing/#application-level-configuration seems to suggest that I can add `ignoreDifferences` to the application `spec` yet this does not seem to work nor shown in the manifest when looking under app details in the UI.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    path: apps/harbor
    repoURL: SNIP
    targetRevision: master
  destination:
    name: k8s-euc1
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data/CSRF_KEY
    - /data/secret
    - /data/JOBSERVICE_SECRET
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key
    - /data/REGISTRY_HTTP_SECRET
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1secret
    - /spec/template/metadata/annotations/checksum~1secret-core
    - /spec/template/metadata/annotations/checksum~1secret-jobservice
```

**To Reproduce**

spin up goharbor helm chart

**Expected behavior**

This should ignore diffing on generated values.

**Screenshots**

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

**Logs**
