### ISSUE TITLE
v1.8.0 External oidc login broken

### ISSUE THREAD

**Issue by drewboswell** [argoproj/argo-cd#5021]
# Describe the bug

After upgrading to v1.8.0 from v1.7.10 oidc external login doesn't work anymore.

It appears that the redirect url defaults to self, rather than use the config that is supposed to be copied to the dex container. This may be a regression in the argo copy utils.

# To Reproduce
**configure an external oidc source**
(as per https://argoproj.github.io/argo-cd/operator-manual/user-management/#existing-oidc-provider)
<details>
  <summary>argocd-cm.yaml ...</summary>

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  ...
data:
  ...
  oidc.config: |
    name: external.dex.local
    issuer: https://external.dex.local/dex
    clientID: xxxxxx
    clientSecret: xxxxxxxxxx
    scopes:
      - groups
      - openid
      - profile
      - email
      - offline_access
  ...
```
</details>

**attempt to login to argocd via oidc login**
<details>
  <summary>argocd login screenshot ...</summary>

![image](https://user-images.githubusercontent.com/6523434/101755442-28176900-3ad5-11eb-8201-16f8e47ac7a0.png)
</details>

**ArgoCD redirects you to itself instead of the remote oidc url**
<details>
  <summary>redirection result on click ...</summary>

127.0.0.1:8081 is my local argo test instance
url in navbar: http://127.0.0.1:8081/auth/login?return_url=http%3A%2F%2F127.0.0.1%3A8081%2Fapplications%2Fargocd-repositories
![image](https://user-images.githubusercontent.com/6523434/101755039-b50df280-3ad4-11eb-80a4-a88183a3e987.png)
</details>

**Expected behavior**

Redirect to url configured in the argocd-cm configmap

**Version**

```shell
argocd: v1.8.0+3034841
  BuildDate: 2020-12-09T18:27:49Z
  GitCommit: 30348417a9603ec1c0e40b335cdf0fd83192bad0
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```
