### ISSUE TITLE
large helm chart are very slow at refreshing

### ISSUE THREAD

**Issue by jetersen** [argoproj/argo-cd#5063]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

kube-prometheus-stack is extremely slow at refreshing and often getting stuck, requiring a reboot of argocd-server and application controller.

Using a subchart
```
apiVersion: v2
appVersion: "1.0"
description: Proxy-chart for kube-prometheus-stack
name: kube-prometheus-stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 12.8.0
    repository: https://prometheus-community.github.io/helm-charts
```
With the following values:
```
kube-prometheus-stack:
  defaultRules:
    rules:
      kubeApiserverAvailability: false
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false
    createCustomResource: false
  prometheus:
    prometheusSpec:
      retentionSize: 45GB
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
      - prometheus.company.io
      tls:
      - hosts:
        - prometheus.company.io
        secretName: prometheus.company.io-tls
  grafana:
    deploymentStrategy:
      type: Recreate
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
      - grafana.company.io
      tls:
      - hosts:
        - grafana.company.io
        secretName: grafana.company.io-tls
    persistence:
      type: pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      finalizers:
        - kubernetes.io/pvc-protection
    rbac:
      pspEnabled: false
    grafana.ini:
      users:
        viewers_can_edit: true
      server:
        root_url: https://grafana.company.io
      security:
        cookie_secure: "true"
      auth.generic_oauth:
        enabled: "true"
        client_id: "grafana"
        client_secret: SNIP
        scopes: openid profile email groups offline_access
        auth_url: https://dex.company.io/auth
        token_url: https://dex.company.io/token
        api_url: https://dex.company.io/userinfo
        allow_sign_up: "true"
    plugins:
    - grafana-worldmap-panel
    additionalDataSources:
    - name: loki
      access: proxy
      orgId: 1
      type: loki
      url: http://loki.loki:3100/
      jsonData:
        maxLines: 1000
      version: 1
  alertmanager:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
      - alertmanager.company.io
      tls:
      - hosts:
        - alertmanager.company.io
        secretName: alertmanager.company.io-tls
    config:
      route:
        group_by: ['alertname', 'service']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'null'
      receivers: # yet to be configured
      - name: "null"
```

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    path: apps/kube-prometheus-stack
    repoURL: SNIP
    targetRevision: master
  destination:
    name: k8s-euc1
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

Would be nice without needing to restart the containers.

**Version**

```shell
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```
