### ISSUE TITLE
Allow specifying parent/child relationships in config

### ISSUE THREAD

**Issue by pbecotte** [argoproj/argo-cd#5082]
# Summary

Argo detects parent child relationships for the UI display in most cases. It appears to use OwnerReferences to do so. However, not all CRDs use OwnerReferences for this task. We should have an api similar to the "custom health check" system that allows us to specify some other method (such as a specific label to look at)

# Motivation

We are using Argocd with the Istio Operator. With a recent upgrade, Argo stopped showing the resources created by the istio operator.  From some troubleshooting, we discovered that Istio is no longer creating OwnerReferences on child objects (our older deployment still had them from the older version, we were very confused). This ticket https://github.com/istio/istio/issues/29430 got a response saying they switched to using labels for tracking these relationships.

Turning to argo, I had hoped to find a way to specify to track all resources keyed on that label as a child of IstioOperator resources. I read this ticket https://github.com/argoproj/argo-cd/issues/2999, which makes it look like any change like this would actually involve adding code to argo itself that adds the OwnerReferences. However, looking at https://github.com/argoproj/argo-cd/tree/master/resource_customizations/install.istio.io/IstioOperator, there is already work in tree to allow customizing health checks for a CRD.

# Proposal

I would be interested in an API change that allows you to specify this behavior. A couple possibilities are-
1. A lua or yaml file dumped in a CRD specific directory in the argocd container, the same way the health checks are.
2. A field in the argocd configmap
3. A field in the application spec.

In all three cases I would expect the format to be something like

```
relationshipTracking:
    install.istio.io/IstioOperator:
        ownerLabels: install.operator.istio.io/owning-resource
        ownerNamespaceLabel:  install.operator.istio.io/owning-namespace
```

**Comment by jessesuen** [comment]
If the only thing which is desired is to view the resources in the Argo CD UI, then a workaround can be to create a dummy application that targets the `istio-sytem` namespace, but enable orphaned resource monitoring feature to view all of the resources in that namespace.

@pbecotte would that solve your use case?

**Comment by pbecotte** [comment]
It sorta works. It wouldn't show the relationship between the CRD object and its children, and depends on both there being nothing else in the namespace AND all the resources being in the SAME namespace (neither of which are true in my setup).

**Comment by yfried** [comment]
+1
We have the exact same use case: ArgoCD + Istio Operator

**Comment by alexisbel1** [comment]
We have the same problem here using [Kubevela](https://github.com/oam-dev/kubevela) as mentionned in #8047. Since v1.1.x, Kubevela does not use `ResourceOwner` to track generated resources. It uses a `ResourceTracker` cluster scope CRD.

Kubevela applies Open Application Model (OAM), which eases Kubernetes resources creation for Application Engineers less familiar with Kubernetes, using components and traits defined by Operation Engineers (who know kubernetes).

The big issue is that `Deployments` (and other workload resources) are generated using Kubevela, and so even pods, do not appear in the UI. Therefore, ArgoCD `Application` is not able to retrieve container images running in pods which is a bit problematic when using the [ArgoCD Image Updater](https://github.com/argoproj-labs/argocd-image-updater) which uses these images as reference.

Any plan to add more ways to specify parent/child relationship?

Cc: @pasha-codefresh

**Comment by natereid72** [comment]
I'll throw another 'we too' in the ring with Crossplane. Crossplane has a namespace scoped resource called Composite Resource Claim that create cluster scoped resources called Composite Resource. The Composite Resource creates potentially many child resources. A namespace scoped resource cannot be the owner of a global scoped resource. So the app shows as out of sync or when configured to ignore Composite Resources, only shows the tip of the iceberg of related resources.

If I understand #3390 correctly, that aims to fix a similar issue described in #2999, that solution was to edit the managed fields of an existing resource to manually show ownership. In my opinion, that is not a feasible solution to this issue.

While the use of owner ref is a mostly convenient solution in Argo CD, as owner ref is intended for garbage collection, it seems to be misaligned. There are going to be cases where resources are related but are not intended to be part of a cascading delete pattern. And then there are related resources that can't show owner ref because they are in separate namespaces or flow up from namespace to cluster scope.

A label or annotation solution will probably not solve all cases immediately, but should likely solve the majority, with the remainders needing to add functionality to pass labels to related downstream resources.

**Comment by negz** [comment]
Throwing in my two cents regarding Crossplane - while a label based relationship mapping would be better than nothing, I'd prefer if it was possible to teach ArgoCD about the relationships we already use in the 'XRM' (i.e. the Crossplane superset of the Kubernetes Resource Model).

As @natereid72 mentions, we have concepts known as Composite Resource Claims (XRCs), Composite Resources (XRs), and Managed Resources (MRs). Note that these are classes of custom resource kinds, not kinds themselves. So any of them may have an arbitrary `kind: Foo` despite being considered "an XRC". There's typically a fan-out relationship between these three classes of resource. When someone creates an XRC, Crossplane creates a corresponding XR, which in turn creates one or more corresponding MRs. So `XRC -> XR -> MRs`.

XRCs are the only namespaced resource in this DAG, so we have no `ownerRef` between XRCs and XRs, though there is an `ownerRef` between an XR and its MRs. We model all of the relationships using Kubernetes references:

* An XRC uses `spec.resourceRef` to reference its bound XR.
* An XR uses `spec.claimRef` to reference its bound XRC.
* An XR uses `spec.resourceRefs` (an array of references) to reference its MRs.

In an ideal world it would be possible to configure ArgoCD to be aware of these types of relationships. Unfortunately because the custom resources are of arbitrary kinds this would have to rely on duck typing - i.e. if a resource has an `ObjectReference` under `spec.resourceRef` it is assumed to be an XRC.

**Comment by vfarcic** [comment]
+1

**Comment by natereid72** [comment]
The more I delve into this issue, the more I tend to believe it's a larger issue than just how dependency relationships are resolved by Argo CD. I really don't see owner reference chain as good, because it's for garbage collection and has rules that are not aligned with many relationships that fall outside of garbage collection models. And because I'm starting to believe that any 'best-effort' logic for a GitOps platform to rationalize downstream relationships from the upstream resource coming from a repo and then acted on by an operator is just that. best-effort  It's prone to not working over and over again. 

I currently believe the better path to resolution is one of two options (or both). Option 1: Argo CD should automatically ignore any downstream operator created resources and only track 1:1 resources in repo and cluster. Option 2: implement an operator interface in Argo CD in conjunction with Option 1, and then allow the operator to inform Argo CD of what it has created and expects in the cluster based on the upstream resource.

**Comment by jessesuen** [comment]
Related: https://github.com/argoproj/argo-cd/issues/8683 and potentially we can duplicate to taht.

**Comment by ofirshtrull** [comment]
HI all, 
any update on this?

**Comment by tm-nadavsh** [comment]
+1

**Comment by fhopfensperger** [comment]
+1
I would very much in favour of being able to define user-defined parent relationships.

**Comment by petar-cvit** [comment]
+1

**Comment by aleoli** [comment]
+1 for this

**Comment by andrii-korotkov-verkada** [comment]
Labels can introduce an issue with people potentially making application resources to not be a tree, but rather a graph, maybe even with loops. Also, using owner references is ingrained in how gitops engine works to construct the tree, so this would be a bit involved. Another issue is that seems like there's no standard way of tracking and we may need to add support for all of those. Can you give more context on how people argument not using owner references, please?

**Comment by lorelei-rupp-imprivata** [comment]
We see something similar here with the GPU Operator. It does use OwnerReferences though. It spawns a ton of Daemonsets that are not tracked by Argo, and we really want them to be. The Daemonsets Do have OwnerReference on it, back to a ClusterPolicy though.

  ownerReferences:
  - apiVersion: nvidia.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterPolicy
    name: cluster-policy

Even with this set, the children owned by this cluster-policy do not show up in ArgoCD UI

**Comment by andrii-korotkov-verkada** [comment]
By chance, do you have exclusions configured for Daemonsets in the ArgoCD configmap?

**Comment by lorelei-rupp-imprivata** [comment]
> By chance, do you have exclusions configured for Daemonsets in the ArgoCD configmap?
@andrii-korotkov-verkada  

so we do set the resource.inclusions in the argocd-cm, I tried adding DaemonSet but that did not seem to matter

This is what that looks like
```
resource.inclusions:
----
- apiGroups:
  - ""
  kinds:
  - ConfigMap
  - Endpoints
  - LimitRange
  - Ingress
  - IngressRoute
  - Job
  - Namespace
  - OpenTelemetryCollector 
  - PersistentVolumeClaim
  - PersistentVolume
  - Pod
  - PodTemplate
  - ReplicationController
  - ResourceQuota
  - ServiceAccount
  - Secret
  - Service
  - Workflow
  - PodDisruptionBudget
  - ClusterPolicy
  - HorizontalPodAutoscaler
  - DynaKube
  - PriorityClass
  - CSIDriver
  - MutatingWebhookConfiguration
  - ValidatingWebhookConfiguration
  - DaemonSet
  clusters:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  - "rbac.authorization.k8s.io"
  - "extensions"
  - "discovery.k8s.io"
  - "batch"
  - "argoproj.io"
  - "apps"
  - "policy"
  - "apiextensions.k8s.io"
  - "apiregistration.k8s.io"
  - "opentelemetry.io"
  - "kubernetes-client.io"
  - "nvidia.com"
  - "autoscaling"
  - "scheduling.k8s.io"
  - "storage.k8s.io"
  - "admissionregistration.k8s.io"
  kinds:
  - "*"
  clusters:
  - "*"
```
