### ISSUE TITLE
Are PreSync hook behaviors not suitable for DB migration?

### ISSUE THREAD

**Issue by ebkn** [argoproj/argo-cd#5086]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I'm using PreSync hook (https://argoproj.github.io/argo-cd/user-guide/resource_hooks/) to perform db schema migration job.
I encountered following problems.
- Sync phase is started even if job is still running. (not completed)
- Sync phase is started even if job is failed.

Are these expected behaviors?

**To Reproduce**

<details><summary>job and deployment manifests</summary>
<p>

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: db-apply
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2" # after sealed-secrets
spec:
  activeDeadlineSeconds: 120
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: xxx:v1.0.0
        imagePullPolicy: Always
        name: db-schema
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: xxx:v1.0.0
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
          name: api
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cd
resources:
  - api-deployment.yaml
  - db-apply-job.yaml
```

</p>
</details>

**Expected behavior**

Resources should wait for completion of jobs with PreSync hook. If db migration jobs takes long time, new version of the apps might be broken for a while.
Resources should not be applied after jobs with PreSync hook failed. When new version of the app deployed even if db migration is failed, apps might be broken.

**Screenshots**

**Version**

```shell
argocd: v1.7.10+bcb05b0.dirty
  BuildDate: 2020-11-20T23:40:45Z
  GitCommit: bcb05b0c2e0f8006aa2d2abaf780e73c9e73c945
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8

```

**Logs**

```
```

**Comment by dpinchukov-ueni** [comment]
While this doesn't answer the original question, try this workaround that works fine for me:

```
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
```

**Comment by jessesuen** [comment]
> I encountered following problems.
> * Sync phase is started even if job is still running. (not completed)
> * Sync phase is started even if job is failed.

This would definitely be a bug. However, we had tried this internally using your manifests and was unable to reproduce. We also have an e2e test for this.

Can you share the portion of controller logs relevant to the sync?

Do you happen to have a datapoint if the second+ sync are the ones that are continuing prematurely? It could be a bug where we proceed prematurely by considering the *previous* jobs success as a signal to continue to the Sync phase, caused by this annotation

```
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
```

If true, a workaround could be to switch from `BeforeHookCreation` to `HookSucceeded`, or use a hook that uses `generateName` and not an explicit name.

**Comment by shapirus** [comment]
In my case, the annotations that I posted above, work this way: the job (with explicit name) is run before the sync of other resources begin, and, after its completion, stays in either completed or failed state until the next sync, which gives plenty of time to analyze its pod logs.

I forgot, however, to note one important detail. We have the following in the Deployment and other resources that depend on the successful completion of the migration:

```
 annotations:
   argocd.argoproj.io/sync-wave: "1"
```

Whereas the db-migration Job has the default value which I believe is zero. This way it starts before other resources begin to sync.

Together it works just fine.

**Comment by ebkn** [comment]
I changed `sync-wave`, it finally works! (Thanks @shapirus !)
- deployment waited for completion of job
- if job failed(ImagePullBackoff, active deadline exceeded, exited with code 1, ContainerCannotRun), deployment was not applied

`sync-wave` at deployment should be specified and not be 0.

|sync-wave(job)|sync-wave(deployment)|result|
|:-:|:-:|:-:|
|2|not specified|NG|
|-1|not specified|NG|
|2|-1|OK|
|2|0|NG|
|2|1|OK|

<details><summary>our manifests (works)</summary>
<p>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
  annotations:
    argocd.argoproj.io/sync-wave: "1" # should be specified and not be 0
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: xxx
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-apply
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2" # after sealed secrets
spec:
  activeDeadlineSeconds: 120
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: xxxx
        imagePullPolicy: Always
        name: api
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hook-test
resources:
- api.yaml
- job.yaml
```

</p>
</details>

I think this is a kinds of `sync-wave`'s bug, right?

---

I tried these changes, but nothing changed.
Sync at the first time works(deployment waited for completion of job), but *second+ syncs* are always broken.

- use `HookSucceeded` delete policy for job
- use `generatorName` for job

<details><summary>HookSucceeded delete policy (not working)</summary>
<p>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: xxx
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-apply
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  activeDeadlineSeconds: 120
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: xxxx
        imagePullPolicy: Always
        name: api
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hook-test
resources:
- namespace.yaml
- api.yaml
- job.yaml
```

</p>
</details>

<details><summary>generatorName (not working)</summary>
<p>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: xxx
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-apply-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  activeDeadlineSeconds: 120
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: xxxx
        imagePullPolicy: Always
        name: api
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hook-test
resources:
- namespace.yaml
- api.yaml
- job.yaml
patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: db-apply-
    patch: |-
      - op: move
        from: /metadata/name
        path: /metadata/generateName
```

</p>
</details>
