### ISSUE TITLE
Combination of `replicas` definition and HPA keeps scaling pods between same nums.

### ISSUE THREAD

**Issue by nakkoh** [argoproj/argo-cd#5105]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I push the following manifest files into Git repository.

* Deployment with the following definition 

    ```yaml
    spec:
      replicas: 1
    ```

* HPA with the following definition 

    ```yaml
    spec:
      minReplicas: 2
      maxReplicas: 10
    ```

I created the Application to create the above manifest.
After that, pods deployed, and kept beeing scaled to 1 or 2 again and agian.

This time the target of HPA was unknown.

```
$ k -n test-hpa get hpa nginx 
NAME    REFERENCE          TARGETS       MINPODS   MAXPODS   REPLICAS   AGE
nginx   Deployment/nginx   <unknown>/1   2         10        1          17h
```

But HPA can get target metrics if the app was disabled auto-sync of Argo CD.

[How to work around]

Set the following definition into Application definition.

```yaml
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: nginx
    namespace: test-hpa
    jsonPointers:
    - /spec/replicas
```

**To Reproduce**

Create the Application by the following manifests.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-hpa
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: 1
```

**Expected behavior**

The replicas defined in Deployment manifest is ignored and the pod num is decided by HPA.

**Screenshots**

**Version**

```shell
argocd: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:43:46Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

**Logs**
