### ISSUE TITLE
ArgoCD authentication handshake failed

### ISSUE THREAD

**Issue by storm1kk** [argoproj/argo-cd#5110]
**Describe the bug**

Hello ArgoCD Team!

We have upgraded our ArgoCD instances recently and facing bothering issue now. Time to time ArgoCD starts sync process and looks like it hanging somewhere. Then it works normally and then hit again.

We also noticed that restart of ```argocd-repo-server``` can help for a short moment.

We have one replica of ```argocd-repo-server``` and two replicas of ```argocd-server```.

**To Reproduce**

N/A.

**Expected behavior**

ArgoCD is not hanging during app sync

**Screenshots**

![Screenshot 2020-12-22 at 16 03 04](https://user-images.githubusercontent.com/8113941/102893827-3cfbe100-4473-11eb-9aee-557d11d3d7bf.png)

**Version**

```shell
argocd: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:57:57Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2020-12-22T12:43:44Z" level=info msg="Sync operation to  failed: ComparisonError: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: remote error: tls: internal error\"" application=graph-db-graphdb-api-instances dest-namespace=graph-db dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning
```

**Comment by jannfis** [comment]
@alexmt Probably similar issue as the one we recently talked about.

**Comment by jessesuen** [comment]
Yes we are facing this internally as well. We suspect the upgrade in gRPC libraries may have caused this but haven't confirmed. In an internal build, we put in place a gRPC health check which kills the repo-server when this happened and that allowed us to recover, but doesn't address the root cause.

**Comment by jannfis** [comment]
As discussed on Slack already, it would be really valuable if someone could inspect the argocd-repo-server listener when its failing. with another TLS capable client that gives some more information about handshake.

For example, full output of `openssl s_client -host <host_of_failing_reposerver_pod> -port <port_on_pod>` (or service instead of pod, if there's only one replica of repo-server), which might give us some more indications of what happens on TLS handshake level.

I have also taken a look at our gRPC stack, it looks terrible :) We have updated some of the components, but others not, and its not easy to get this straight due to many legacy constructs in the code. I'm working on it, tho.

I'm still trying to reproduce the issue locally, but without much luck.

**Comment by storm1kk** [comment]
> As discussed on Slack already, it would be really valuable if someone could inspect the argocd-repo-server listener when its failing. with another TLS capable client that gives some more information about handshake.
> 
> For example, full output of `openssl s_client -host <host_of_failing_reposerver_pod> -port <port_on_pod>` (or service instead of pod, if there's only one replica of repo-server), which might give us some more indications of what happens on TLS handshake level.
> 

We will try to catch it next time ArgoCD hangs.

**Comment by Issif** [comment]
Hi,

We're currently facing the issue, here the result of the command (run internally of a repo-server):

```bash

argocd@argocd-repo-server-c4d8c7f6b-cwhjj:~$ openssl s_client -host localhost -port 8081

CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 O = Argo CD
verify error:num=18:self signed certificate
verify return:1
depth=0 O = Argo CD
verify return:1
140146647491712:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1544:SSL alert number 80
---
Certificate chain
 0 s:O = Argo CD
   i:O = Argo CD
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDETCCAfmgAwIBAgIRAKGoOTg9C6uM6wu2GonmFT4wDQYJKoZIhvcNAQELBQAw
EjEQMA4GA1UEChMHQXJnbyBDRDAeFw0yMDEyMjIxNjMyMjRaFw0yMTEyMjIxNjMy
MjRaMBIxEDAOBgNVBAoTB0FyZ28gQ0QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQCsshiDMHQ61J55+0AOApeCY4xgmbQ+/+YqWKQDbRpBbHdDEgf4Bux8
Ij1XUBgC4iTlI6LNu1rXgt3wIr3peeiNsrjcHR73C0A5WVAPsbD+ueyAj9mdA1RM
Iq70WwvdJv7ITGSCfJ2di4gV3AeMVO2qBH5A5GOtIaVt4dbskvG4i7cvvr+Rvnrq
4xX1jMbjh1pkhCnXrNhnyxPrwHgYV0Lz4+eeirMsJD603OJgekYDHGT/v9AtnW/8
KN/6VGHy4qvjjlms7wXaeANK1wu9h0dfublFuC8jvr/BUdHdMqZ71vn/FluRVdqa
smAHQWO2DxdbR2CHXuTuLaKdZYTwOso3AgMBAAGjYjBgMA4GA1UdDwEB/wQEAwIC
pDATBgNVHSUEDDAKBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCgGA1UdEQQh
MB+CCWxvY2FsaG9zdIISYXJnb2NkLXJlcG8tc2VydmVyMA0GCSqGSIb3DQEBCwUA
A4IBAQCargXh/niqJcbKZGkhDp7SY72Fmy9wSjnfSALOJtiomHeAt2kuOmmcu8v6
B62xIHYHMIU/bVecV4CgdyoVOeNmA9Hs3UUuIMBWWuCPFnUJUIpijY34/xdYceXB
AHX8OGmjY/VdLQgRM5fQg+ufZiqNRRPnB9uxxzpqy1VxGKetoXdCzfATmIsNh32N
0otUE2PGEufM01ggJWD3sUoKewlBHPmyAocEzDDLFVsQdKfFFB4PsYPCDZvlH2mq
CoDvRcSQ2Y2D7U6DlzQOrDBhqVMmpC9GHp8wHtH+rMgo1ZJyAfZgIvYJTgdfn2HC
LqFFE09tUWyK8ZZSIhLtSE53QZsZ
-----END CERTIFICATE-----
subject=O = Argo CD

issuer=O = Argo CD

---
No client certificate CA names sent
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1009 bytes and written 283 bytes
Verification error: self signed certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 18 (self signed certificate)
---
```

Hope I will help.

**Comment by jannfis** [comment]
OK, this one is interesting

> `140146647491712:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1544:SSL alert number 80`

Apparently, for `openssl` client, this error is transient while for our golang/gRPC client, it is not.

Will investigate further.

Thank you for this additional information, @Issif

**Comment by eroji** [comment]
Having the same issue here.

@Issif when you said you deleted the repo-server can you clarify what exactly you did? Did you delete the pods for `argocd-repo-server` deployment?

**Comment by Issif** [comment]
> Having the same issue here.
> 
> @Issif when you said you deleted the repo-server can you clarify what exactly you did? Did you delete the pods for `argocd-repo-server` deployment?

Exactly. I just deleted the pod and let the deployment recreate it.

**Comment by eroji** [comment]
Got it. I guess I'll use that as a workaround until this is fixed.

**Comment by alexmt** [comment]
We've added livenessProbe that restart repo server as a workaround. Here is merge patch that introduce the probe:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          exec:
            command: [ "/usr/local/bin/grpc-health-probe", "-addr=:8081", "-tls", "-tls-no-verify" ]
        volumeMounts:
        - mountPath: /usr/local/bin/grpc-health-probe
          name: custom-tools
          subPath: grpc-health-probe
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-grpc-health-probe
        image: docker.intuit.com/oicp/alpine3.8:latest
        command: [sh, -c]
        args:
          - wget --no-check-certificate https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.3.5/grpc_health_probe-linux-amd64 &&
            mv grpc_health_probe-linux-amd64 /custom-tools/grpc-health-probe &&
            chmod ugo+x /custom-tools/grpc-health-probe
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
```

@jannfis , @jessesuen do you think we should add it by default until issue is resolved?
