### ISSUE TITLE
Argo tree visualization doesn't handle daily certificates well

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5115]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Set up cert-manager to generate certificates daily...
View the tree for the resource

**To Reproduce**

1. Set up cert-manager
2. Add a certificate:

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-tap-k8s-tls
  namespace: linkerd
spec:
  secretName: linkerd-tap-k8s-tls
  duration: 48h0m0s
  renewBefore: 24h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-tap.linkerd.svc
  dnsNames:
  - linkerd-tap.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
```

Go to argocd tree view after a few months.

**Expected behavior**

I don't have a great suggestion. This is just a problem statement :-(

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/103032384-e9020280-452d-11eb-9722-64611bbfc45d.png)

**Version**

```shell
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```
