### ISSUE TITLE
OutOfSync should provide better help for elided fields

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5116]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Fields that are equivalent to being omitted result in end user confusion.

**To Reproduce**

1. Create a cert w/ `isCA: true`
2. Update the cert to have `isCA: false`
3. Check argo status
4. See hint: `Whether or not the version of your app is up to date with your repo. You may wish to sync your app if it is out-of-sync.`

`isCA: true`:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-tap-k8s-tls
  namespace: linkerd
spec:
  secretName: linkerd-tap-k8s-tls
  duration: 48h0m0s
  renewBefore: 24h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  dnsNames:
  - linkerd-tap.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
```
`isCA: false`:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-tap-k8s-tls
  namespace: linkerd
spec:
  secretName: linkerd-tap-k8s-tls
  duration: 48h0m0s
  renewBefore: 24h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  dnsNames:
  - linkerd-tap.linkerd.svc
  isCA: false
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
```

**Expected behavior**

It'd be nice if the hint for out of sync indicated that it's possible that the desired configuration includes fields that are equivalent to omitted values and thus the desired config should be adjusted instead.

I don't have precise wording -- happy to word-smith with someone on this.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/103035250-ebb42600-4534-11eb-922a-1daa304d7c21.png)
Hovered, it says:
`Whether or not the version of your app is up to date with your repo. You may wish to sync your app if it is out-of-sync.`
![image](https://user-images.githubusercontent.com/2119212/103035283-fe2e5f80-4534-11eb-92b4-aefce0547ded.png)

**Version**

```shell
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
```
