### ISSUE TITLE
CRD-configured clusters

### ISSUE THREAD

**Issue by dpkirchner** [argoproj/argo-cd#5139]
# Summary

Add a CRD that allows users to specify a cluster's configuration, including the name of whatever service account will be used, the endpoint, CA, etc.

# Motivation

Adding clusters to argocd requires several manual commands as well as permission to create service accounts. Removing clusters also requires manual work (although you can do it from the web UI). It would be more gitopsy and k8sy if there was a way to specify a cluster's configuration using a CRD-backed resource. Additionally, this would increase security somewhat by allowing the administrator to create the necessary ServiceAccounts, RoleBindings, etc instead of granting that ability to argocd's SA.

# Proposal

I am not familiar with how to create CRDs but I think the resulting resources would look something like:

```yaml
apiVersion: xx/yy
kind: Cluster
metadata:
  name: cluster-a
spec:
  endpoint: https://1.2.3.4
  caBase64: <base64 encoded certificate>
  serviceAccount:
    name: name-of-sa-on-cluster-a
    secretRef: name-of-secret
```

There would need to be some way for an administrator to specify credentials used to access the cluster's endpoint, perhaps using another secretRef.

Additionally, it would be useful to be able to refer to this cluster by reference in `Application` resources in place of the URL.
