### ISSUE TITLE
"include filter" for spec.source.directory settings as with "exclude filter"

### ISSUE THREAD

**Issue by MasayaAoyama** [argoproj/argo-cd#5165]
# Summary

Implement include filter for directory settings as with exclude filter (https://github.com/argoproj/argo-cd/pull/4686).

# Motivation

A directory has several microservice manifests.
For example,

```
somedir
|-- microservice-a.yaml
|-- microservice-b.yaml
`-- microservice-c.yaml
```

In this situation, we cannot create an Application resource for only a single microservice by exclude filter.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-a
spec:
  source:
    repoURL: https://github.com/xxx
    targetRevision: master
    path: somedir/
    directory:
      # we cannot use negative regular expression 
      # exclude: "(!microservice-a.yaml)"
```

# Proposal

I want to also implement include filter like exclude filter. 0f course, we can use a regular expression like "microservice-*.yaml".

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-a
spec:
  source:
    repoURL: https://github.com/xxx
    targetRevision: master
    path: somedir/
    directory:
      include: "microservice-a.yaml"
      # we cannot use negative regular expression 
      # exclude: "(!microservice-a.yaml)"
```
