### ISSUE TITLE
Can not sync cluster role in external cluster if that cluster does not have namespace the application is deployed to

### ISSUE THREAD

**Issue by werne2j** [argoproj/argo-cd#5169]
I have an external cluster that I am trying to deploy a cluster role and cluster role binding to. The argocd application is deployed in the argocd namespace of the cluster where argocd is deployed but when trying to sync the cluster role and cluster role binding it takes the namespace from the app and so I get an error that says “namespace argocd not found”. Is there a way to deploy resources that don’t have a namespace to an external cluster without it taking the namespace of the argocd application?

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

**To Reproduce**

Connect an external cluster and then attempt to sync a cluster resource such as cluster role or cluster role binding with the argocd application being deployed in a namespace that the external cluster does not have

**Expected behavior**

The resource should be able to sync without taking the namespace from the argocd application

**Comment by jkayani** [comment]
To add additional information we have tried hardcoding `namespace: default` in the cluster resources since that namespace is guaranteed to exist on all of our external target clusters (even though namespaces shouldn't matter for cluster resources). Unf, that didn't work and instead the error message remained the same: "namespace argocd doesn't exist".

**Comment by jannfis** [comment]
What is the value of your Application's `.spec.destination.namespace`?

**Comment by jkayani** [comment]
It's `default`. This is the latest attempt's ArgoCD app:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dmt-eu-de-test-infra
  namespace: argocd
spec:
  destination:
    namespace: default
    name: dmt-eu-de-test
  source:
    path: infrastructure/dmt-eu-de-test-infra
    repoURL: some-repo
    targetRevision: HEAD
    directory:
      recurse: true
  project: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
```

and the resource is:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: some-name
  namespace: default
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
 - some-data
```

**Comment by jannfis** [comment]
And the only resources in `infrastructure/dmt-eu-de-test-infra` (and below directories, due to `recurse: true`) in `some-repo` are your `ClusterRole` and `ClusterRoleBinding` ones? No other namespaced resource in some stray YAML within the path in that repo?

How is your external cluster configured? Does it have any namespace constraints on it?

**Comment by jkayani** [comment]
> How is your external cluster configured? Does it have any namespace constraints on it?

No special configuration comes to mind re: namespaces. 

>  No other namespaced resource in some stray YAML within the path in that repo?

There are other resources, and they are all namespace-specific ones, with hardcoded, non-default values. Those are applied via ArgoCD just fine. An example from `infrastructure/dmt-eu-de-test-infra/customresources/thing.yaml`

```
apiVersion: cio-sets.ibm.com/v1alpha1
kind: SyncSecret
metadata:
  name: sync-ingress-tls
  namespace: openshift-ingress
spec:
  some-data
```

**Comment by werne2j** [comment]
@jannfis Any idea on how we can get around this?

**Comment by jessesuen** [comment]
Something doesn't seem to add up. The error `namespace argocd not found` would indicate that `argocd` is the `spec.destination.namespace` which makes sense to error because `argocd` is typically not a namespace in a managed cluster (it is in the control plane). but according to your spec, you use `default` as the destination namespace.

**Comment by werne2j** [comment]
@jessesuen yes, can confirm ` SyncFailed  namespaces "argocd" not found`. I believe what is happening is because the resources we are trying to sync do not typically have a namespace, it is being stripped away. So then the argocd application uses its namespace which is `argocd`.

**Comment by werne2j** [comment]
All of our resources that have a namespace in them work just fine but something like a cluster role does not work
This is the live manifest:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - delete
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - list
```
and this is what is in git
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-role
  namespace: default
rules:
  - apiGroups:
    - ''
    resources:
    - pods
    verbs:
    - delete
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - list
```

**Comment by jkayani** [comment]
Hi, everyone - sorry about the confusion, I re-tested the problematic scenario:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dmt-eu-de-test-infra
  namespace: argocd
spec:
  destination:
    namespace: default
    name: dmt-eu-de-test
  source:
    path: infrastructure/dmt-eu-de-test-infra
    repoURL: some-repo
    targetRevision: HEAD
    directory:
      recurse: true
  project: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
```

and in `infrastructure/dmt-eu-de-test-infra/rbac`:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: some-name
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
 - some-data
```

And it sync'd fine without a problem. I suspect I didn't press the Sync button at the right time or something else happened to not cause Argo to sync the change. 

The moral of the story here is that for the child app in the app of apps, the destination for the resources in that app must be a namespace that exists in the destination cluster. And that's perfectly logical and exactly what was explained here: https://github.com/argoproj/argo-cd/issues/5169#issuecomment-755737433. Maybe I just glossed over this problem because this was a cluster resource, which had no namespace, and it wasn't obvious that in that scenario Argo CD would use the `spec.destination.namespace` of it's containing app.

Thanks a lot for your help, sorry about this.
