### ISSUE TITLE
Kubernetes secret create from vault  is Always OutOfSync

### ISSUE THREAD

**Issue by yan-zhao-unity** [argoproj/argo-cd#5178]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
Create secret from vault causes secret OutOfSync.
```
apiVersion: v1
data:
  REFLECTPROJECT_ConnectionStrings__ProjectServiceDatabase: 
  REFLECTPROJECT_Security__LicenseValidationStartDate: "${vault:secret/data/argocd/password1#key1}"
  REFLECTPROJECT_Sentry__Dsn: "${vault:secret/data/argocd/password2#key2}"

kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/inline-mutation: 'true'
    vault.security.banzaicloud.io/vault-addr: 'https://vault.xx.com'
    vault.security.banzaicloud.io/vault-path: default
    vault.security.banzaicloud.io/vault-role: default
    vault.security.banzaicloud.io/vault-skip-verify: 'true'
  labels:
    argocd.argoproj.io/instance: reflect-project-staging
  name: project-master-secrets
  namespace: project
type: Opaque
```

```
apiVersion: v1
data:
  REFLECTPROJECT_ConnectionStrings__ProjectServiceDatabase: 
  REFLECTPROJECT_Security__LicenseValidationStartDate: "test password1"
  REFLECTPROJECT_Sentry__Dsn: "test password2"

kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/inline-mutation: 'true'
    vault.security.banzaicloud.io/vault-addr: 'https://vault.xx.com'
    vault.security.banzaicloud.io/vault-path: default
    vault.security.banzaicloud.io/vault-role: default
    vault.security.banzaicloud.io/vault-skip-verify: 'true'
  labels:
    argocd.argoproj.io/instance: reflect-project-staging
  name: project-master-secrets
  namespace: project
type: Opaque
```
**To Reproduce**

use vault webhook to get secret content.

**Expected behavior**

**Screenshots**

**Version**

```shell
1.81
```
**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
As I understand the behavior (please correct me if I'm wrong), a vault webhook is behind-the-scenes mutating the secret from it's desired state in git. If so, Argo CD is correctly reporting the diff and I would not consider this a bug.

You can always configure ignoreDifferences to ignore the mutations performed by vault.

**Comment by Elyytscha** [comment]
if you just ignore the secrets it will be not possible to change the secret reference from e.g. 
`REFLECTPROJECT_Sentry__Dsn: "${vault:secret/data/argocd/password2#key2}"`
to
`REFLECTPROJECT_Sentry__Dsn: "${vault:secret/data/argocd/sentry#dsn}"`

which is not cool

**Comment by victorgetz** [comment]
Hi we experienced the same problem and we found a good workaround (if you use helm).

In the global argocd server config you need to add this:

```
# Ignores .data changes of all secrets with a vaultInjectionChecksum annotation
resource.customizations.ignoreDifferences.Secret: |
  jqPathExpressions:
    - '. | select(.metadata.annotations.vaultInjectionChecksum) | .data'
```

Inside the secret of your helm chart you add the annotation like this:

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-ak-sk-gitlab-runner
  annotations:
    # The checksum is changed if accessKey and secretKey are changed
    vaultInjectionChecksum: {{ printf "%s%s" .Values.accessKey .Values.secretKey | sha256sum }}
data:
  accesskey: {{ .Values.accessKey | b64enc }}
  secretkey: {{ .Values.secretKey | b64enc }}
```

The magic is argocd will now look only at vaultInjectionChecksum. If this changes there is diff.
Works like a charm.
