### ISSUE TITLE
/settings/repos page is crashed with Javascript error message Error: Invalid url.

### ISSUE THREAD

**Issue by abdennour** [argoproj/argo-cd#5182]
**Describe the bug**

While navigating to ArgoCD website, and specially /settings/repos, i got this error: 

```
Something went wrong!

Consider submitting an issue here.


Stacktrace:

Error: Invalid url.
    at e.exports (https://cd.devops.example.com/main.2e65a524d04617fac156.js:393:1221)
    at e.exports (https://cd.devops.example.com/main.2e65a524d04617fac156.js:393:349)
    at o (https://cd.devops.example.com/main.2e65a524d04617fac156.js:383:172291)
    at https://cd.devops.example.com/main.2e65a524d04617fac156.js:33:175825
    at wi (https://cd.devops.example.com/main.2e65a524d04617fac156.js:33:175904)
    at Zo (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:53276)
    at Yi (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:65519)
    at Ka (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:90782)
    at Xa (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:91166)
    at Ps (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:98191)
```

At the begining, i was able to see that it renders the git repository.. for other repos (which are helm repos),it keeps loading ( loading icon), then after 1 or 2 seconds, the whole page crashes.

**To Reproduce**

ArgoCD is installed from a Helm chart :

```
repositories:
# To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
- name: argo
  url: https://argoproj.github.io/argo-helm
# ...
releases:
- name: argocd
  namespace: argocd
  chart: argo/argo-cd
  version: 2.11.0
```
And values.yaml includes the following config: 

```yaml
      config:
        repository.credentials: |
          - url: http://git.bitbucket
            passwordSecret:
              name: bitbucket-secret
              key: password
            usernameSecret:
              name:  bitbucket-secret
              key: username
        repositories: |
          - type: git
            url: http://git.bitbucket/scm/project/app-sample.git
          - type: helm
            url: http://nexus.nexus/repository/helm-stable/
            name: stable
          - type: helm
            url: http://nexus.nexus/repository/helm-charts-atlassian/
            name: atlassian
          - type: helm
            url: http://nexus.nexus/repository/helm-charts-incubator/
            name: incubator
          - type: helm
            url: http://nexus.nexus/repository/helm-charts-banzaicloud-stable/
            name: banzaicloud-stable
          - type: helm
            url: http://nexus.nexus/repository/helm-charts-tn/
            name: tn
          - type: helm
            url: http://nexus.nexus/repository/helm-charts-hashicorp/
            name: hashicorp
          - type: helm
            url: http://nexus.nexus/repository/helm-charts-bitnami/
            name: bitnami
          - type: helm
```

**Expected behavior**

I expect that ArgoCD shows the list of configured repos under **/settings/repos** without errors

**Screenshots**

- as webpage: 

![image](https://user-images.githubusercontent.com/1788384/103628128-9b36c280-4f4f-11eb-806d-1cb8e4ed9e6c.png)

- as api response, there is no issue ( screeshot from JS Console of the browser) : 

![image](https://user-images.githubusercontent.com/1788384/103627460-b35a1200-4f4e-11eb-866a-1240028b2ac2.png)

**Version**

```shell
argocd: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:57:57Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:52:04Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:l
inux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersi
on:"go1.13.10"}
  Kubectl Version: v1.17.8
  Jsonnet Version:```

**Logs**

- From HTML webpage: 

```
Something went wrong!

Consider submitting an issue here.

Stacktrace:

Error: Invalid url.
    at e.exports (https://cd.devops.example.com/main.2e65a524d04617fac156.js:393:1221)
    at e.exports (https://cd.devops.example.com/main.2e65a524d04617fac156.js:393:349)
    at o (https://cd.devops.example.com/main.2e65a524d04617fac156.js:383:172291)
    at https://cd.devops.example.com/main.2e65a524d04617fac156.js:33:175825
    at wi (https://cd.devops.example.com/main.2e65a524d04617fac156.js:33:175904)
    at Zo (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:53276)
    at Yi (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:65519)
    at Ka (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:90782)
    at Xa (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:91166)
    at Ps (https://cd.devops.example.com/main.2e65a524d04617fac156.js:354:98191)
```

- Response of /api/v1/repositories 

```json
{"metadata":{},"items":[{"repo":"http://git.bitbucket/scm/jd/nodejs-sample.git","username":"builder","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"git"},{"repo":"http://nexus.nexus/repository/helm-stable/","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"helm","name":"stable"},{"repo":"http://nexus.nexus/repository/helm-charts-atlassian/","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"helm","name":"atlassian"},{"repo":"http://nexus.nexus/repository/helm-charts-incubator/","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"helm","name":"incubator"},{"repo":"http://nexus.nexus/repository/helm-charts-banzaicloud-stable/","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"helm","name":"banzaicloud-stable"},{"repo":"http://nexus.nexus/repository/helm-charts-tn/","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"helm","name":"tn"},{"repo":"http://nexus.nexus/repository/helm-charts-hashicorp/","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"helm","name":"hashicorp"},{"repo":"http://nexus.nexus/repository/helm-charts-bitnami/","connectionState":{"status":"Successful","message":"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"helm","name":"bitnami"},{"repo":"","connectionState":{"status":"Failed","message":"Unable to connect to repository: Get \"index.yaml\": unsupported protocol scheme \"\"","attemptedAt":"2021-01-05T08:49:30Z"},"type":"git"}]}
```
