### ISSUE TITLE
Option to hide sesetive data in specific fields

### ISSUE THREAD

**Issue by kvaps** [argoproj/argo-cd#5201]
# Summary

We need an opportunity mask or hide specific fields for all resources.

# Motivation

We're using qbec to generate and render kubernetes manifests from jsonnet files.
Just like ksonnet it also can add its own last-applied annotation with gziped secret encoded in base64.

while secret data is hidden, the last-applied annotation doesn't:

![image](https://user-images.githubusercontent.com/7556217/103831436-5ceaf180-507c-11eb-8466-b79d2edf457e.png)

# Proposal

Add configuration option into argocd configmap:

```yaml
data:
  resource.customizations: |
    "*":
      maskFields:
      - field: "metadata.annotations.\"qbec.io/last-applied\""
```
