### ISSUE TITLE
Unable to fetch metadata with truncated SHA targetRevision

### ISSUE THREAD

**Issue by mveitas** [argoproj/argo-cd#5264]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using truncated SHA revisions throws errors in the UI. The request from the UI to fetch the metadata with a revision such as `e15e282` is failing with the following response:
`{"error":"revision e15e282 must be resolved","code":2,"message":"revision e15e282 must be resolved"}`

Request is to the following via `kubectl port-forward`: https://localhost:9999/api/v1/applications/gatekeeper/revisions/e15e282/metadata

![Screen Shot 2021-01-17 at 2 55 07 PM](https://user-images.githubusercontent.com/439521/104854330-07141600-58d4-11eb-8dd1-5089caf008c8.png)

**To Reproduce**

We see this issue when declaring the Argo Application as follows with a targetRevision of `e15e282`
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: {{ .Values.argo_namespace }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Values.argo_namespace }}
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: gatekeeper

  # Source of the application manifests
  source:
    repoURL: git@xxxxxxxxxxxx:Development/core-services.git
    targetRevision: e15e282
    path: services/gatekeeper/env/{{ .Values.env }}/
    helm:
      valueFiles:
      - values.yaml
```

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

ArgoCD should be able to resolve both full and truncated SHA values to use for the targetRevision

**Version**
```
argocd: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:35:17Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:52:04Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```
