### ISSUE TITLE
Sync is not running when only SealedSecret resources changed

### ISSUE THREAD

**Issue by ebkn** [argoproj/argo-cd#5267]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Sync does not run when only SealedSecret resources changed.

I'm ArgoCD with AutoSync, GitHub webhooks. And I'm using [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) for secret management for target cluster.
When PR like following that have only SealedSecrets diff merged to develop(AutoSync enabled), ArgoCD AutoSync was triggerd but sync operation not started.

```
// diffs on Git
spec:
  encryptedData:
-   xxxxxxxxxxxxxxxxxxxxxxxxx
+   yyyyyyyyyyyyyyyyyyyyyyyy
```

AutoSync (triggered by GitHub webhook) works, but no diffs(= `APP DIFF` button on ArgoCD UI is disabled) found on ArgoCD. So secrets was not updated.

`kustomize build | kc apply -f` works as expected(secrets was updated).

Is this a ArgoCD's bug?

**To Reproduce**

- AutoSync, GitHub webhook enabled on ArgoCD
- Create PR that have only diffs of SealedSecrets resource file
- merge PR
- AutoSync started, but no diffs found on ArgoCD

**Expected behavior**

Sync operation started when diffs found in SealedSecrets resource

**Screenshots**

**Version**

```shell
argocd version
argocd: v1.8.2+94017f2.dirty
  BuildDate: 2021-01-10T06:49:46Z
  GitCommit: 94017f2c8d97588d4aa2213713a71d51005ed62d
  GitTreeState: dirty
  GoVersion: go1.15.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Does `kubectl diff` report a diff? We should be consistent with `kubectl diff`.

**Comment by ebkn** [comment]
Sorry. I think this is not ArgoCD's bug.

> kustomize build | kc apply -f works as expected(secrets was updated).
I misunderstood. This command didn't work.

When I updated only SealedSecret, SealedSecret and Secret was successfully updated. And Deployment had no diffs and didn't restarted (i think this is correct behavior).
In my case deployment like app server loaded secrets when it started, so server didn't changed when SealedSecrets changed.

I want to do rollout deployments when secrets updated.

**Comment by jannfis** [comment]
Hi @ebkn, you might want to take a look at [Reloader](https://github.com/stakater/Reloader), which can trigger a rolling update of `Deployment`, `StatefulSet` and the like on change of `ConfigMap` and `Secret` resources.

As a more sophistic alternative, you could also have a look at Argo Events to set up an event pipeline for accomplishing the same.

**Comment by ebkn** [comment]
Thanks. But I think [Reloader](https://github.com/stakater/Reloader) isn't compatible with ArgoCD's hook.
Reloader restarts deployments immediately even if deployments have ArgoCD hooks annotation. Because Reloader ignores ArgoCD's hook (e.g. `argocd.argoproj.io/hook` annotations).

**Comment by ebkn** [comment]
I'm trying to use Kustomize's `configMapGenerator` to restart deployments when only sealed secrets updated.
This is a hucky way. I want to migrate if I find out better solution.

<details><summary>sample manifests</summary><div>

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: watch-sealed-secrets-secret-json
  files:
    - sealed-secrets-secret-json
resources:
- api-deployment.yaml
- sealed-secrets-secret-json
...
```

api-deployment.yaml
```yaml
volumeMounts:
- name: secret-json
  mountPath: /var/config/secret.json
  subPath: secret.json
...
volumes:
- name: secret-json
  secret:
    secretName: secret-json
- name: watch-sealed-secrets-secret-json
  configMap:
    name: watch-sealed-secrets-secret-json
...
```

</div></details>

other solutions -> https://github.com/bitnami-labs/sealed-secrets/issues/167
