### ISSUE TITLE
Add oci protocol to resolve Helm dependencies

### ISSUE THREAD

**Issue by eirisdg** [argoproj/argo-cd#5270]
# Summary

According to the new Helm version 3.5.0, OCI protocol in dependencies with `oci://` url format is now supported.
It's allow to download dependencies from a OCI repo.

# Motivation

```yaml
- name: common
  version: 0.0.1
  repository: oci://url-repo/chart
```

# Proposal

Upgrade to Helm 3.5 would be great.
