### ISSUE TITLE
Allow wildcard for IgnoreDifferences.jsonPointers

### ISSUE THREAD

**Issue by dpolicastro** [argoproj/argo-cd#5276]
# Summary
IDK about other resources, but for Secrets, I felt lack of support to allow the use of wildcards on `jsonPointers`, and that would make secrets management using external tools easier, e.g., SOPS.

# Motivation
I use SOPS to encrypt some of my secrets, so I can push manifest files to the source repository, and for that reason I deploy the secret manually. Basically I have a Chart to create multiple `Application` CRDs, and I want to have the option to always ignore changes on Secrets, to avoid syncing something by mistake, an encrypted secret for example.

Now I have to pass all the data fields I want to ignore:
```yaml
  ignoreDifferences:
  - group: ""
    kind: Secret
    jsonPointers:
    - /data/something
    - /data/password
```
It would be good to have something like this:
```yaml
  ignoreDifferences:
  - group: ""
    kind: Secret
    jsonPointers:
    - /data/*
    or
    - '*'
```

# Proposal
The wildcard should be enough
