### ISSUE TITLE
Config management plugins enhancement

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5293]
# Summary

Currently, Argo CD provides first-class support for Helm, Kustomize, Jsonnet/YAML, and Ksonnet (to be removed). The first-class support includes:

* Bundled binaries (maintainers periodically upgrade binaries)
* An ability to override parameters using UI/CLI
* The applications are discovered in Git repository and auto-suggested during application creation in UI
* Performance optimizations. Argo CD "knows" when it is safe to generate manifests concurrently and takes advantage of it.

There are many more great config management tools. However, it is impossible to provide first-class support: additional tool binaries increase image size and it is hard to keep track of breaking changes in each tool. The [config management plugins] allow using any CLI command to generate manifest but currently provide the only bare minimum and user experience is not so good. 

# Motivation

The [config management plugin](https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/) functionality should be improved to provide the same level of user experience as first-class support ( including Argo CD operators as well as end-user experience )

# Proposal

The proposal includes summaries of config management plugin enhancements that we are aware of already. More enhancements might be added based on feedback from the community and details should be discussed in sub-issues.

**Installation Experience**

Config Management plugin typically requires a new entry in [configManagementPlugins](https://github.com/argoproj/argo-cd/blob/eaf9887d174d23791831f641cc411bc148ebaef3/docs/operator-manual/argocd-cm.yaml#L215) and [init container with a volume mount](https://argoproj.github.io/argo-cd/operator-manual/custom_tools/#adding-tools-via-volume-mounts) that add new binary into Argo CD repo server pod. The problem is that the whole process is 100% manual and requires learning from each and every Argo CD administrator. 

To improve it we might create a community-maintained catalog of config management tools similar to https://github.com/argoproj-labs/argo-workflows-catalog or https://github.com/tektoncd/catalog.

* The catalog should include a list of merge patches register a new tool in `argocd-cm` ConfigMap and introduce an init container in `argocd-repo-server` Deployment.
* Catalog should enforce predefined directory structure that allows to easily discover required config management tool
* The installation process should be as easy as  `kubectl patch --type merge -f <URL>`

This way config management tool maintainers can make tools easily accessible for Argo CD operators.

**Application discovery**

Argo CD detects paths of Helm/Kustomize/Ksonnet applications in the Git repository. The config management plugins should allow configuring shell script that is executed by `argocd-repo-server` in the Git repository and return the list of detected application paths.

Additionally, Argo CD automatically detects which config management tool should be used for manifest generation. The same should be done for config management plugins

 **Parameters support in UI/CLI**

This is probably the most challenging enhancement. Config management plugins allow specifying only a list of environment variables while config management with first-class support has custom made UI/CLI code. We would have to brainstorm more. Here list of advantages that first-class tools have:

* Argo CD provides list of available parameters, does not require user to guess which parameters are supported. For example it executes `helm values` and shows list of supported values in the UI
* Argo CD shows default values of each parameter. For example it detects list of images used in Kustomize based app and show image tags as default values
* User friendly UI: parameters are group logically, no rendered as just flat list ( for example Kustomize images are rendered separately from other parameters )

As a summary config management plugin settings should allow configuring a shell script that returns declarative definition of application parameters. The definition should be used to dynamically render UI and control CLI behavior.

**Comment by alexmt** [comment]
Related issues
* Tanka https://github.com/argoproj/argo-cd/issues/3124 
* QBEC https://github.com/argoproj/argo-cd/issues/2930
* Dhall https://github.com/argoproj/argo-cd/issues/4961
* Kustomize + Helm https://github.com/argoproj/argo-cd/issues/4738
* kpt https://github.com/argoproj/argo-cd/issues/3360
* jk https://github.com/argoproj/argo-cd/issues/3322

**Comment by alexec** [comment]
I think this is a great idea - I wrote a PoC about 1 year ago ;) 

I think Danny mentioned that Golang plugins were not great at the time. Maybe improved now. Did you see how Kustomize does plugins?

Also, it would be good to be able to run concurrent Kustomize and Helm versions

**Comment by alexmt** [comment]
Found PoC PR . Here it is https://github.com/argoproj/argo-cd/pull/3338 , may be we can use part of it :)

**Comment by alexec** [comment]
If I recall, there are only so many inputs to a plugin (which is just a binary at the end of the day), which are arguments to `exec.Command`:

* PWD
* Environment
* Arguments

So you just need to generalize those into configuration/API.

**Comment by dcherman** [comment]
As an alternative, what about something like the following:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDPlugin
metadata:
  name: tanka
spec:
  binaries:
    tk: https://github.com/grafana/tanka/releases/download/v0.13.0/tk-linux-amd64
    jb: https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v0.4.0/jb-linux-amd64

  # How should the user specify the param name / types / validation?  OpenAPI / Swagger?
  # The UI could be present this options to the user which solves the problem of passing custom params
  # to plugins
  params:
    my-plugin-argument:
      type: string
      default: "foobar"

  # A command that can be executed to detect whether or not this plugin should automatically be executed maybe?
  detect:
    command: ''

  # Corresponds to the existing init command in the plugin api
  init:
    command: ''
    args: []

  # Corresponds to the existing generate command in the plugin api
  generate:
    command: ''
    args: [] 
```

By extracting all of this out of the primary configmap and into individual CRDs, it becomes much easier to create and share plugins in the community.  Many of the built-in generators like helm, kustomize, jsonnet, etc. could potentially be refactored to use this API and be bundled with the default installer so that it's a non-breaking change, however they'd remain easy to replace.

Interestingly enough, this could even support multiple versions of the same plugin.  If we were to install the plugins at a path like `/var/argocd/plugins/{{ pluginName }}` and then add the correct folder to the PATH in the repo server when generating manifests, you could even have multiple versions of a given plugin/tool installed at the same time.

**Comment by snuggie12** [comment]
It's not documented, but the helm chart inflator became a built in plugin in kustomize in at least version 3.9.2 so perhaps kustomize-helm can be removed from the list.

Also in some recent version of kustomize (at least 3.8.4) the ability to run krm functions (I believe the name is getting changed to "image plugins" in kustomize soon?) works, but it requires docker to pull and execute the image. Not sure how that would work on the repo-server. I think a lot of kpt also relies on docker to do krm functions though.

**Comment by yann-soubeyrand** [comment]
> If I recall, there are only so many inputs to a plugin (which is just a binary at the end of the day), which are arguments to `exec.Command`:
> 
>     * PWD

I guess the working directory should be set to the path defined in the application, isn’t it?

> 
>     * Environment
> 
>     * Arguments
> 
> 
> So you just need to generalize those into configuration/API.

What about using the same API which is used in a Pod spec https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#container-v1-core (fields args and env)?

**Comment by meiblorn** [comment]
Is it possible to add an ability to specify what repositories to preload when using custom management plugins? Or you can give an ability (or provide an example how) to call `argo template` from the custom management plugins to reuse existing default Argo's behaviour in these plugins.

As for example, lets assume I use popular `kustomized-helm` plugin. When I use it and declare private helm OCI repo dependency in Charts.yaml, that does't work on Argo's side because helm repositories are not loaded and authenticated, hence I get 401 error.

So it would be good to have smth like:
```
configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: 
          - "argo auth helm" // or smth like that ...
          - "helm dependency build"
      generate:
        command: [sh, -c]
        args: ["helm template --release-name release-name . > all.yaml && kustomize build"]
```
