### ISSUE TITLE
Error creating aerospike application

### ISSUE THREAD

**Issue by saidelmark** [argoproj/argo-cd#5334]
**Describe the bug**

I try to deploy aerospike using it's [public helm chart](https://github.com/aerospike/aerospike-kubernetes/tree/master/helm).  
And I get an error "`groupVersion shouldn't be empty`".

**To Reproduce**

1. Start minikube
2. Deploy argocd (I installed with helm and also tried with `kubectl apply -f <argo-cd-manifest>`)
3. Create a minimal manifest for aerospike application:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aerospike
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: aerospike
  source:
    repoURL: 'https://aerospike.github.io/aerospike-kubernetes'
    targetRevision: '*'
    chart: aerospike
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
4. Run `kubectl apply -f aerospike.yaml` (assuming the manifest above is called `aerospike.yaml`)

**Expected behavior**

I expect to have aerospike installed. And when I explicitly use helm to install aerospike (the same chart), then everything is fine. 

**Version**

Reproduces on versions `1.5.4`, `1.7.5`, `1.7.6`, `1.8.3`:
```shell
argocd: v1.8.0+unknown
  BuildDate: 2020-12-10T01:50:14Z
  GitCommit:
  GitTreeState:
  GitTag: 1.8.0
  GoVersion: go1.15.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.4+36bade7
  BuildDate: 2020-05-05T19:01:57Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
  Jsonnet Version:
```
```shell
argocd-server: v1.7.5+90cc56c
  BuildDate: 2020-09-15T23:03:57Z
  GitCommit: 90cc56c3a99127f6ed6bcb777abf92e357c1eb00
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
  Jsonnet Version:
```
```shell
argocd-server: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:52:04Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
  Jsonnet Version:
```
```shell
argocd-server: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:20:39Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9284083/105970620-a090b400-609a-11eb-887d-bb0b9e974b09.png)
