### ISSUE TITLE
failure with invalid label value

### ISSUE THREAD

**Issue by strantalis** [argoproj/argo-cd#5364]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When adding an invalid unquoted numeric label value argocd removes all other labels from the namespace.

**To Reproduce**

#### Initial Namespace
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: label-test
  labels:
    label-1: "12345"
```

#### Now add a label-2 unquoted. Argocd will show label-1 being removed.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: label-test
  labels:
    label-1: "12345"
    label-2: 12345
```

**Expected behavior**

With this being an invalid label value I would expect argocd to produce an error.

**Version**

```shell
$ argocd version
argocd: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:50:44Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Comment by jessesuen** [comment]
This is not Argo CD doing this, it is kubernetes. Kubernetes drops the entire labels/annotations if there is one invalid value applied.

**Comment by strantalis** [comment]
@jessesuen So I probably don't understand everything fully but I thought argocd validates all manifest before being applied?

When do I `kubectl apply --dry-run` the namespace comes back invalid.

```sh
❯ kubectl apply --server-side=true --dry-run=server -f namespace.yaml
error: unable to decode "namespace.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found 1, error found in #10 byte of ...|label-2":12345},"nam|..., bigger context ...|metadata":{"labels":{"label-1":"12345","label-2":12345},"name":"label-test"}}|...
```

```h
❯ kubectl apply --dry-run=client -f namespace.yaml
error: unable to decode "namespace.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found 1, error found in #10 byte of ...|label-2":12345},"nam|..., bigger context ...|metadata":{"labels":{"label-1":"12345","label-2":12345},"name":"label-test"}}|...
```

**Comment by alexmt** [comment]
The 1.8 has an improvement https://github.com/argoproj/argo-cd/issues/1787 .  Argo CD used to drop unknown fields - now such fields stay untouched. @strantalis  can you please check if upgrade resolves issue?

**Comment by strantalis** [comment]
I tried upgrading to 1.8.3 but it still didn't seem to change anything. This is the namespace definition in git below and some screenshots of live, diff and desired.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: label-test
  labels:
    label-1: "12345"
    label-2: 12345
````
#### Live
<img src="https://user-images.githubusercontent.com/18211470/106701512-c9420d80-65b4-11eb-8689-a1c44ea73c59.png" width="400" />

#### Diff
<img src="https://user-images.githubusercontent.com/18211470/106701630-f4c4f800-65b4-11eb-902e-9c32dbf3354e.png" width="400" />

#### Desired
<img src="https://user-images.githubusercontent.com/18211470/106701640-fb536f80-65b4-11eb-8871-08d78fdf0662.png" width="400" />

**Comment by strantalis** [comment]
@alexmt One thing I noticed is argocd/kube does block a bad label with spaces on sync so not sure whats going on with the integer label value. Seems to be something happening before the sync phase. Maybe when it does the diff? 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/instance: label-test
    label-1: '12345'
    spaces: This is invalid
  name: label-test
```

```
Namespace "label-test" is invalid: metadata.labels: Invalid value: "This is invalid": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

<img src="https://user-images.githubusercontent.com/18211470/107053774-39ab8300-679d-11eb-8e19-84a00c65ddc4.png" width="800" />
