### ISSUE TITLE
Enable --disable-openapi-validation sync option when using Helm

### ISSUE THREAD

**Issue by esys** [argoproj/argo-cd#5366]
# Summary

When using helm as a templating tool, charts requiring the `--disable-openapi-validation` cannot be installed using ArgoCD

# Motivation

For example, the privatebin chart is failing to deploy because the `StatefulSet` object is missing the `spec.serviceName` field. So we have a chart that is deployable through Helm using the `--disable-openapi-validation` option but not with ArgoCD

# Proposal

Support additional Helm flags when defining application CRD. For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: privatebin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@repo.git'
    path: helm/charts/pio-privatebin
    targetRevision: master
    helm:
      valueFiles:
        - values-custom.yaml
      releaseName: privatebin
      flags:
        # will translate to helm template ... --disable-openapi-validation=true
        disable-openapi-validation: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: privatebin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```
