### ISSUE TITLE
Application health assessment failed with "ComparisonError: json: cannot unmarshal array into Go value of type"

### ISSUE THREAD

**Issue by ymmt2005** [argoproj/argo-cd#5423]
**Describe the bug**

When I added a Lua script to restore Application health assessment behavior in v1.7 for v1.8.3 server
according to the [this](https://argoproj.github.io/argo-cd/operator-manual/upgrading/1.7-1.8/#health-assessement-of-argoprojioapplication-crd-has-been-removed), `argocd-application-controller` stop syncing Applications.

An Application had a status like this:

```yaml
status:
    health:
      status: Missing
    operationState:
      finishedAt: "2021-02-02T08:39:12Z"
      message: 'ComparisonError: json: cannot unmarshal array into Go value of type
        health.HealthStatus'
```

`argocd-application-controller` outputted logs like this:

```
time="2021-02-02T10:19:40Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2021-02-02T10:19:40Z\",\"message\":\"json: cannot unmarshal array into Go value of type health.HealthStatus\",\"type\":\"ComparisonError\"}]}}" application=argocd-config
```

**To Reproduce**

We cannot create a minimal case.
Our app-of-apps repository is github.com/cybozu-go/neco-apps

When we added the Lua script in https://argoproj.github.io/argo-cd/operator-manual/upgrading/1.7-1.8/#health-assessement-of-argoprojioapplication-crd-has-been-removed to `argocd-cm`, it stops Application synchronization.

**Expected behavior**

The Lua script should work without errors.

**Version**

```shell
argocd: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:19:20Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.3+unknown
  BuildDate: 2021-02-02T03:51:06Z
  GitCommit:
  GitTreeState: clean
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: v3.7.0 2020-07-04T19:15:46Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v1.19.7
  Jsonnet Version: v0.17.0
```
