### ISSUE TITLE
Deprecate `repositories` and `repository.credentials` keys of `argocd-cm` ConfigMap key

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5436]
# Summary

The `repositories` and `repository.credentials` keys of `argocd-cm` ConfigMap contain yaml serialized list of repositories credentials. Both keys should be deprecated and replaced with just only list of secrets.

# Motivation

These two keys make it difficult to manage repositories declaratively and imperatively at the same time (see https://github.com/argoproj/argo-cd/issues/3218). In case when repositories are managed declaratively the one key forces users to put everything into a single YAML file. It is impossible to leverage e.g. Kustomize and merge patch files.

# Proposal

Deprecate both `repositories` and `repository.credentials` keys. Infer list of repositories and repo credentials from list of secrets with label `argocd.argoproj.io/secret-type=repository`  (same as we already manage cluster credentials)

**Comment by jangraefen** [comment]
I proposed something similar in #5398. I think one of them could be closed.

I am also very interessted to contribute this functionality. Would that be an option?

**Comment by alexmt** [comment]
Hello @jangraefen, Looks like #5398 proposes using CRDs. Is it a critical requirement or you agree that Secrets are good enough for repository credentials? 

After had several discussions we've concluded that at least repository credentials don't need CRDs and could be stored just as Secrets. The reason is that sensitive information must be stored as a secret, either way, so CRDs looks like overkill in this case. Instead of strongly typed CRDs it is better to just use convention: Secret must have a label `argocd.argoproj.io/secret-type=repository` and predefined key names ( such as `username`, `password`, `sshPrivateKey` )

**Comment by alexmt** [comment]
Thank you for offering help! If you have time your contribution is very welcome. This feature is not on the critical path for 1.9 release and we have enough time to work on design and implementation.

Please let me know what you think about using Secrets vs ConfigMaps.

**Comment by jannfis** [comment]
To chip my 2 cents into this, both types of configuration (CRDs vs Secrets) would be a major breaking change for about all of our users and both would require equally much work on the user side to migrate existing repository configuration. Taking this into account, I guess `v2.0` would be the proper release to target for either of both changes.

I have not been part of the mentioned discussions, so I don't know all arguments that were brought up already. However, implementing this as CRD instead of Secret will not only give us the already mentioned validation abilities, but also would allow us to manage repositories more in a truly Kubernetes-native way, enabling proper status retrieval using Kubernetes API. Also, viewing & making changes to Secrets is quite a pita, due to the base64 encoding requirements. 'argocd-util` enhancement of course will remediate some of this pain, however the basic pita will remain.

But if there is consensus already on implementing as Secret, that'll be fine for me too.

**Comment by jangraefen** [comment]
Thank you for your reply @alexmt.

I tried to formulate #5398 in a way that it allows for secrets as a solution as well and discuss the pros and cons of using secrets vs. CRDs.

I fully agree that the actual credentials should always be stored within a secret and nowhere else. CRDs add a "strongly typed" API, validation and [better compatibility](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/). As someone who is responsible for operating several ArgoCD instances in a declarative way, these properties can be a huge qualitity of life improvment.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Repository
metadata:
  name: argocd-example-apps
spec:
  url: https://github.com/argoproj/argocd-example-apps.git
  type: git
  usernameSecret:
    name: my-secret
    key: username
  passwordSecret:
    name: my-secret
    key: password
  privateKeySecret:
    name: my-secret
    key: privateKey
```

Personally, I am a big fan of explict APIs over conventions, but thats my personal taste. Secrets solve the problem at hand with way less complexity. Secrets are well supported by all Kubernetes tools, where as CRD support is not always perfect or even present.

In the end, @jannfis said it much better then I did. I fully agree with what he said.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-example-apps
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: argocd-example-apps
  url: https://github.com/argoproj/argocd-example-apps.git
  username: ****
  passowrd: ****
  privateKey: ****
```

I closed #5398 in favor of this issue, since the discussion of CRDs vs. Secrets has seemingly already happend and secrets come out on top 👍.

---

Using ConfigMaps is something that did not cross my mind so far. I would be interessted in knowing what possible motivations for ConfigMaps would be?
One of the advantages of secrets is that all information is provided by a single resource. ConfigMaps would require storing the credentials externally within a Secret while also provide little to no advantage over Secrets, in my opinion.
Looking at #5439, where no sensitive information is stored, ConfigMaps could be a good option though.

Once a design is settled, I will gladly start working on this. 

--- 

 Could this be implemented in a downward-compatible way though? A first implementation could be done in two ways, without breaking compatibilty with existing installations:
1. The secrets are used to provision the `argocd-cm` config map. The `argocd-cm` config map is still the source of truth.
2. The secrets are used as additional inputs when building the list of all repositories.

Meanwhile the  `argocd-cm` repository configuration is deprecated and marked for removal in `v2`. Personally, if this path would be chosen, I would do it with option 2.
