### ISSUE TITLE
Delete CRD should give an indication of the number and list of items to be deleted

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5445]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I tried upgrading an experimental instance's sealed-secret deployment and received a spec discrepancy in the sealed-secret CRD. I decided to delete the resource.

The end result is that all of my sealed-secrets (and the secrets they owned) were deleted. 

**To Reproduce**

1. Install sealed-secrets (1.10.3) using helm (via argo)
    ```yaml
    dependencies:
    - name: sealed-secrets
      version: 1.10.3
      repository: https://charts.helm.sh/stable/
    ```
2. Properly seal and install some secrets
3. Upgrade sealed-secrets (1.14.1-r1) using helm (via argo)
    ```yaml
    dependencies:
    - name: sealed-secrets
      version: 1.14.1-r1
      repository: https://bitnami-labs.github.io/sealed-secrets/
    ```
4. See a warning about the CRD not matching
5. Decide to delete the CRD
6. Get the generic type the name item to delete the CRD
7. Enter the name of the resource and delete it
 
**Expected behavior**

While ArgoCD may not know about all objects in the cluster, as it will know about many of them, it should be able to tell the user how many objects of the type managed by the CRD will be destroyed. And ideally have a way to show them.

**Screenshots**

**Version**

```shell
{
    "Version": "v1.9.0+bb15a49",
    "BuildDate": "2021-02-06T01:06:52Z",
    "GitCommit": "bb15a4996e327fb27ad91f3f6fa24f831f7754e0",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```
