### ISSUE TITLE
SSO setup with Github doesn't work with RBAC

### ISSUE THREAD

**Issue by IamGabrielWu** [argoproj/argo-cd#5448]
Hi 
Is it a bug ? or something i missed ? 
I followed the link https://argoproj.github.io/argo-cd/operator-manual/rbac/ to set up rbac but turns out people within team-sre still don't have proper access. 
I placed sensitive information with xxx_

my argo-cm.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://cd.xxx_org.org
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: xxx_clientid
          clientSecret:xxx_clientsecret
          orgs:
          - name: xxx_org
  admin.enabled: "true"
```
my rbac
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, projects, *, *, allow
    g, xxx_org:team-sre, role:org-admin
```
My goal is to allow people within Github team "team-sre" to be admin. 
And the argocd page gives me error like below picture.
![image](https://user-images.githubusercontent.com/11718739/107178014-310db380-6a0e-11eb-8290-72a6a9b25a20.png)
