### ISSUE TITLE
Presync hooks stop working after namespace resource is added in a Helm chart

### ISSUE THREAD

**Issue by raulsh** [argoproj/argo-cd#5522]
**Describe the bug**

I added namespace as a resource in a Helm chart (to add some annotations). When I did it presync hooks stop working. All sync actions works normally, just presync hooks stop working.

I simply added:

```yml
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
{{- if .Values.rancherProjectId }}
  annotations: 
    field.cattle.io/projectId: {{ .Values.rancherProjectId }}
{{- end }}
```
