### ISSUE TITLE
AppProjects allow cluster resources to be applied by default and when clusterResourceWhitelist is "[]"

### ISSUE THREAD

**Issue by wmgroot** [argoproj/argo-cd#5540]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**

After some extensive testing and confusion, we discovered that in the AppProject resource, the default behavior with no included whitelist or blacklist allows Applications that belong to the AppProject to apply cluster resources.

Additionally, setting `clusterResourceWhitelist: []` in the AppProject does not restrict Applications from applying any cluster resource.

The default AppProject documented implies that removal of the clusterResourceWhitelist entry will revoke access to deploy cluster resources.
https://argoproj.github.io/argo-cd/user-guide/projects/#the-default-project
```
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
```

The declarative setup docs also imply that an empty list should prevent any cluster resource from being applied.
https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#projects
```
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
```

**To Reproduce**

Apply the following resources.
```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: perm-test1
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perm-test1
spec:
  project: perm-test1

  source:
    repoURL: <>
    targetRevision: master
    path: manifests/test

  destination:
    name: <my-cluster>
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: perm-test2
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perm-test2
spec:
  project: perm-test2

  source:
    repoURL: <>
    targetRevision: master
    path: manifests/test

  destination:
    name: <my-cluster>
    namespace: default
```
Create a cluster resource manifest in the `manifests/test` directory to verify this.
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: oidc:test
```

Notice that ArgoCD successfully applies the cluster resource using either AppProject.

**Expected behavior**

I expect ArgoCD to deny all cluster resources by default, based on the available documentation.
I expect a `clusterResourceWhitelist` of `[]` to also deny all cluster resources, based on the available documentation.

**Code**

I believe this line is where this logic occurs. A length of zero (default) is treated as an allow.
https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L2523

This is also likely an issue for namespaced resources, though I personally do not mind that these are allowed by default.

**Version**

```shell
v1.7.3+b4c79cc
```

**Logs**

```
Paste any relevant application logs here.
```
