### ISSUE TITLE
google SSO doco is poor

### ISSUE THREAD

**Issue by dodwmd** [argoproj/argo-cd#5579]
I'm trying to get SSO working with google and the documentation for how to configure dex seems wrong. In the google documentation it says it edit the configmap 'argo-cm' but that config map doesn't exist, in the other documentation for other endpoints it says to edit configmap 'argocd-cm' which does exist. However, when i do edit argocd-cm i get the following and a crashloop on the dex server:

time="2021-02-22T23:32:31Z" level=fatal msg="invalid configuration: default cluster has no server defined"

```
apiVersion: v1
data:
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: oidc
      id: google
      name: google
      config:
        issuer: https://accounts.google.com
        clientID: <REMOVED>
        clientSecret: <REMOVED>
  url: https://argocd.<REMOVED>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
```

I can't see in the deployment where dex mounts the configmap but i assume the cp of argocd and rundex is what unmarshals the config into place.

Any assistance would be greatly appreciated.
