### ISSUE TITLE
apps of apps - dependency (sync-wave) between apps not working

### ISSUE THREAD

**Issue by vikas027** [argoproj/argo-cd#5585]
**Describe the bug**

I am trying to make an app dependent on other apps. Just for sake of an example, I have taken two off the shelf charts - [kubernetes-external-secrets](https://external-secrets.github.io/kubernetes-external-secrets) and [prometheus](https://prometheus-community.github.io/helm-charts)

**NOTE**: I have just taken these charts as an example, we have different charts (stored in a git repository) in my organization along with a few `kustomized_helm` charts (like [kustomize-guestbook](https://github.com/argoproj/argocd-example-apps/tree/master/kustomize-guestbook)) which uses [kustomize-helm](https://github.com/argoproj/argocd-example-apps/blob/master/plugins/kustomized-helm/README.md) plugin

**To Reproduce**
I have tried to use [sync-waves](https://argoproj.github.io/argo-cd/user-guide/sync-waves/#how-do-i-configure-waves) in vain, it does not look like it is coming into effect at all. 
```bash
$ kubectl apply -f nonprod-apps.yaml
```
##### File `nonprod-apps.yaml` for calling other apps
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-nonprod-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: <my git repo>
    targetRevision: HEAD
    path: bootstrap/envs/nonprod
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

##### App files in the git repository
_File 1_ `prometheus.yaml`
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 13.3.2
    helm:
      releaseName: prometheus
      version: v3
      parameters:
      - name: 'alertmanager.enabled'
        value: 'false'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

_File 2_ `secrets-manager.yaml`
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets
    chart: kubernetes-external-secrets
    targetRevision: 6.2.0
    helm:
      releaseName: secrets-manager
      version: v3
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

**Expected behavior**

I want the status of the `prometheus` application to be healthy before argocd moves to `secrets-manager` application.

**Screenshots**

![2021-02-24_07-00-58](https://user-images.githubusercontent.com/6998650/108903883-ef1d7800-7671-11eb-90a9-91f60e2c960c.png)

**Version**

```shell
❯ argocd version
argocd: v1.8.5+d0f8edf.dirty
  BuildDate: 2021-02-20T11:49:52Z
  GitCommit: d0f8edfec804c013d4fc535e8b9022eb47602617
  GitTreeState: dirty
  GoVersion: go1.15.8
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:56:06Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
❯
```

**Related** Issues / Questions
- https://github.com/argoproj/argo-cd/issues/3454
- https://github.com/argoproj/argo-cd/discussions/5316
