### ISSUE TITLE
Helm installation order is not followed

### ISSUE THREAD

**Issue by 617m4rc** [argoproj/argo-cd#5606]
**Bug description**

Argo CD does not install the resources in the same order when deploying an application as they would be installed when directly using Helm. Deployments get stuck due to dependencies on not-yet available resources.

**Expected behavior**

Argo CD should respect the installation order defined by Helm: 

Namespace -> ResourceQuota -> LimitRange -> PodSecurityPolicy -> Secret -> ConfigMap -> StorageClass -> PersistentVolume -> PersistentVolumeClaim -> ServiceAccount -> CustomResourceDefinition -> ClusterRole -> ClusterRoleBinding -> Role -> RoleBinding -> Service -> DaemonSet -> Pod -> ReplicationController -> ReplicaSet -> Deployment -> StatefulSet -> Job -> CronJob -> Ingress -> APIService

(see https://github.com/helm/helm/blob/master/pkg/releaseutil/kind_sorter.go)

**Steps to reproduce**

Deploy [Spark operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/charts/spark-operator-chart) using Argo CD. The job resource is installed first and thus installation never completes.

![image](https://user-images.githubusercontent.com/1398799/109133205-0c774280-7755-11eb-819e-91f45e5410f5.png)
![image](https://user-images.githubusercontent.com/1398799/109133260-1ac55e80-7755-11eb-8ba2-607fe00eefaa.png)

**Comment by mayzhang2000** [comment]
Which version of ArgoCD are you using?

I just tried with the latest code and below is the sync order
![image](https://user-images.githubusercontent.com/7737306/109206739-1ac95c80-775d-11eb-8782-3699237b8081.png)

**Comment by brunokoeferli** [comment]
I have a similar issue with ArgoCD (v2.0.1+33eaf11) and a wrong resources order. In my case I'm using a `ServiceAccount` and a `Secret` referrencing this `ServiceAccount`. If I am using `kubectl apply -f secret.yaml` all works fine/as expected. Even with helm the installation order is correct: first the `ServiceAccount` and then the `Secret`.
When applying the `secret.yaml` via ArgoCD the result is "Sync OK", but the sync status is "OutOfSync". This is due to the fact that ArgoCD is applying the resources in the wrong order: first the `Secret` and then the `ServiceAccount`.
ArgoCD App Overview:
![image](https://user-images.githubusercontent.com/7573326/125947200-ab42042a-3ba3-484f-9c18-7621945a4574.png)

ArgoCD Sync Log:
![image](https://user-images.githubusercontent.com/7573326/125947631-9d4bc7f9-2934-49d1-b98d-dc5624964d82.png)

The Kubernetes API response with an "OK", but the `Secret` referrencing a none existing `ServiceAccount` is not available after the first sync. With a "resync" the `Secret` will be created due to the fact that the `ServiceAccount` is existing now. This behavior can be tested with `kubectl` as well, you have to just switch the resource order in the `secret.yaml` file.

I would expect the same installation order for ArgoCD as for helm.

secret.yaml:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bkotest-sa
  labels:
    helm.sh/chart: bkotest-sa-1.0.0
    app.kubernetes.io/name: bkotest-sa
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: bkotest-service-account-token
  labels:
    helm.sh/chart: bkotest-sa-1.0.0
    app.kubernetes.io/name: bkotest-sa
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/service-account.name: bkotest-sa
type: kubernetes.io/service-account-token
```

Issue https://github.com/argoproj/argo-cd/issues/6727 might be similar.
