### ISSUE TITLE
Versioned Git Tag Tracking - similar to ArgoCD Image Updater

### ISSUE THREAD

**Issue by diranged** [argoproj/argo-cd#5609]
# Summary

When using private Github repositories to manage all of your Application objects, you run into the question of how you are going to manage updating ArgoCD to point to the right version of the repository. There is currently Tag, Branch, and Commit pinning, but they are limited in their function set.

I propose updating the Tag tracking to be able to follow all new tags being created in the repository, and to be able to select the tags using patterns that have been developed in the ArgoCD Image Updater repository (see https://github.com/argoproj-labs/argocd-image-updater/blob/master/docs/configuration/images.md#update-strategies, https://github.com/argoproj-labs/argocd-image-updater/blob/master/docs/configuration/images.md#filtering-tags and https://github.com/argoproj-labs/argocd-image-updater/blob/master/docs/configuration/images.md#ignoring-certain-tags).

# Motivation

Mutating tags is something that we consider "bad" internally. That is - we don't want to have a `production` tag and simply move that around because it makes it very hard to track how and why something happened. There is no real history associated with where a tag was yesterday vs today for example. It also makes leveraging the Github "Release" feature pretty much useless.

We have always used Git tags to manage our deploys.. the tagging strategies vary by team, but being able to quickly see that a new deploy was released because there is a _new_ tag in the repo, and then being able to diff that tag to the previous release is pretty critical.

# Proposal

The ArgoCD Image Updater project has done much of the leg work from a "logic" perspective I think, and ideally that logic could be packaged up into a shared library or something between these projects. In addition to `targetRevision`, I'd like to see a new parameter added in named `targetTracking` and make that an object. For example:

```yaml
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: projects
    repoURL: git@github.com:OurOrg/MyApp.git
    targetTracking:
      updateStrategy: [ semver, latest, name ]
      allowTags: [ <any>, <regex pattern>, ... ]
      ignoreTags: [ <glob pattern>, <regex pattern>, ... ]
```

# In-Practice Examples

Follow Semver-packaging but only in the 1.2.x branch. Include any additional string added to the end of a semvar: `1.2.0`, `1.2.10`, `1.2.30.alpha.1`:
```yaml
targetTracking:
  updateStrategy: semver
  allowTags: [ '1\.2\.[0-9]+.* ']
```

Follow a simple numeric pattern: `0001`, `0002`, `0003`, `0020`, etc:
```yaml
targetTracking:
  updateStrategy: latest
  allowTags: [ '[0-9]{4}' ]
```

**Comment by pnowy** [comment]
I have to say that would be great to have this feature. 

We have the similar problems that branching strategy is super complex for human tracking when there is a lot merges between branches and additionally when you store a couple of configs in one repo that you have to merge all or nothing.

Also with quite popular app of apps patter if you want use parent app pinned to specified tag on the CI you have to first sync that specific app in parent app (to start pointing argo application into different pinned commit) and in second step you are able to sync real manifest. With this feature and possibility to add that kind of tracking strategy it will be much easier to manage in single repo multiple config (per tag prefix for example) and just sync in one step (then argo app-of-apps define only correct strategies).

Yes - above would extend a lot of possibilities with complex distributed systems.

**Comment by edude03** [comment]
Would love to see this as well

**Comment by erkerb4** [comment]
> We have the similar problems that branching strategy is super complex for human tracking when there is a lot merges between branches and additionally when you store a couple of configs in one repo that you have to merge all or nothing.

I found this enhancement to share this same point.. I am a bit late to the party, but I also support this  enhancement idea.

**Comment by Mais316** [comment]
Could we please consider this enhancement request as we are sort of blocked when we have to create a new app tag then its not auto picked.

**Comment by diranged** [comment]
While I still want this to be built - we did work around this internally. Every time we create a release (via github), we have a github action that automatically moves the `production` tag to that release. So we can point Argo at `production` while still using github releases. It's stupid simple... just annoying though that we can't have Argo understand the actual release version/tag-name.

```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update the Production Tag
      run: git tag production --force && git push origin production --force
```
