### ISSUE TITLE
Ability to pin version of Kustomize along side a plugin

### ISSUE THREAD

**Issue by vikas027** [argoproj/argo-cd#5630]
# Summary

I am looking to utilize both a kustomize plugin and also pin down the version of kustomize

# Motivation

It is always good to pin down versions wherever possible to avoid drifts between different environments.
```yaml
  source:
    path: kustomized_helm/overlays/prod
    repoURL: <my_repo>
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
    # Error rpc error: code = Unknown desc = multiple application sources defined: Kustomize,Plugin
    # kustomize:
    #   version: v4.0.1
```

# Proposal

Not quite sure about this, maybe we can specify the version and the specified version gets downloaded automatically in the pod (only if it does not exists).

# Related Issue/Discussion
- https://github.com/argoproj/argo-cd/discussions/5572
