### ISSUE TITLE
Show security information about each application

### ISSUE THREAD

**Issue by omerlh** [argoproj/argo-cd#5640]
# Summary

Provide extendable mechanism for adding relevant security information about the application, like number of vulnerabilities from Snyk (container / OSS / IaC / SAST) or other security issues.

# Motivation

Bring security closed to developers by making this information more approachable and visible in the tools they are already using. Making it easier to spot vulnerable apps in the cluster.

# Proposal

A very rough UI example:
![Screen Shot 2021-03-01 at 14 06 18](https://user-images.githubusercontent.com/6730584/109495088-749c9000-7a97-11eb-8662-61dae9826e2e.png)

Maybe introduce a new CRD?
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSecurityStatus
spec:
  selector:
     app: a
  vulnerabilities:
     sast:
        high: 5
        details: <url>
```

An alternative is allowing to load plugins to the UI, I am not sure how easy it is - but this will be more generic and allows different security companies to offer their own plugins
