### ISSUE TITLE
Cluster cache requires manual refresh

### ISSUE THREAD

**Issue by risinger** [argoproj/argo-cd#5643]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I synced a helm App that installed CRDs to the local cluster. Helm Apps that rely on helm's built-in `.Capabilities` object did not render those custom resources. I waited ~20 hours and the resources still did not render. I manually invalidated the cluster cache via the UI. Then I hard refreshed the helm Apps. Helm then properly rendered the custom resources. 

This is an issue for us because we regularly spin up new clusters and want to use ArgoCD to bootstrap them. AFAICT, there is no way to invalidate the cluster state cache via the CLI, so we're stuck with an extra manual step on cluster bootstrap. 

**To Reproduce**

I'm not certain all of these steps are required. I can say these steps reliably reproduce the issue in my environment. 
I'll try to pare down the steps later. 

* Start with a clean EKS cluster. We run k8s 1.18 latest. 
* Install ArgoCD via the helm chart. 
* Install a cluster autoscaler App and sync it. Here's the App used to reproduce: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler-sandbox-1
  namespace: argocd
  finalizers: # will cascade deletion of this Application to its resources
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://kubernetes.github.io/autoscaler"
    chart: cluster-autoscaler-chart
    targetRevision: 1.0.0
    helm:
      version: v3
      releaseName: cluster-autoscaler
      values: |
        autoDiscovery:
          clusterName: sandbox-1
          enabled: true
        awsRegion: us-west-2
        cloudProvider: aws
        fullnameOverride: cluster-autoscaler
        replicaCount: 1
        serviceMonitor:
          enabled: true
          namespace: kube-system
```
* Install a kube-prometheus-stack App and sync it. Here's the one used to reproduce:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-sandbox-1
  namespace: argocd
  finalizers: # will cascade deletion of this Application to its resources
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: 10.1.0
    helm:
      version: v3
      releaseName: kube-prometheus-stack
      values: |
        prometheus:
          prometheusSpec:
            image:
              tag: v2.21.0
        prometheusOperator:
          enabled: true
          tlsProxy:
            enabled: true
            image:
              tag: v1.5.2
          image:
            tag: v0.42.1
          configmapReloadImage:
            tag: v0.4.0
          prometheusConfigReloaderImage:
            tag: v0.42.1
```
* Refresh the cluster autoscaler App. 

**Expected behavior**

I expected an App hard refresh would refresh all caches involved in rendering the App, including cluster state. 

**Version**

```shell
argocd: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:19:20Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:20:39Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```
