### ISSUE TITLE
Support helm values also via Secret and ConfigMap

### ISSUE THREAD

**Issue by mkilchhofer** [argoproj/argo-cd#5664]
# Summary

Add the ability to use existing Kubernetes Resources (i.e. ConfigMaps and Secrets) as a source for helm values.

# Motivation

As I also use flux (currently the "new" v2/toolkit, but also used v1) I miss the feature to use a Kubernetes Secret or ConfigMap as a source for the `values.yaml`.

Look at the flux example here:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "2.14.7"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  values:
    installCRDs: false

    controller:
      enableStatefulSet: true

    server:
      extraArgs:
        - --insecure
  # (..)
  valuesFrom:
  - kind: Secret
    name: "argocd-values"
    optional: false
```

What you can see here is a resource that looks very similar to the `appprojects.argoproj.io` object, except the `valuesFrom` array. This `valuesFrom` feature enables me to separate the sensitive values from the non-sensitive ones.

# Proposal

1. Extend the CRD `appprojects.argoproj.io`
2. Before the `helm template` command is executed, the controller needs to "download" the ConfigMap/Secret containing the `values.yaml`.
3. Extend the "utility" that calls `helm template -f` with the downloaded file(s). Helm supports multiple values files:
```console
$ helm template -h
  (..)
  -f, --values strings               specify values in a YAML file or a URL (can specify multiple)
```
