### ISSUE TITLE
Changing the cluster name leaves an orphaned instance of the application in the previous cluster

### ISSUE THREAD

**Issue by SamDecrock** [argoproj/argo-cd#5668]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

I change the destination `name` of the cluster. The application is recreated in the new cluster, but in the old cluster, the application is still there.

**To Reproduce**

Create a new Argo Application using yaml. For example

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sam
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: <redacted>
  source:
    repoURL: <redacted>
    targetRevision: HEAD
    path: applications/sam
  destination:
    name: cluster1
    namespace: sam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

Change 
```yaml
  destination:
    name: cluster1
    namespace: sam
```
to
```yaml
  destination:
    name: cluster2
    namespace: sam
```

The application with namespace `sam` is now created at `cluster2` but the application with namespace `sam` also still exists in `cluster1`.

**Expected behavior**

I would expect the application to be removed from the old cluster.

**Version**

```shell
argocd: v1.8.4+28aea3d.dirty
  BuildDate: 2021-02-05T18:42:27Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: dirty
  GoVersion: go1.15.7
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:20:39Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```
