### ISSUE TITLE
Provide build environment as env file while kustomization strategy is used.

### ISSUE THREAD

**Issue by jkroepke** [argoproj/argo-cd#5673]
# Summary

The [ArgoCD build environment](https://argoproj.github.io/argo-cd/user-guide/build-environment/) is currently exposed as system environment variables. kustomize doesn't have a interface to read env variables, but in combination with an [`configMapGenerator`](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md), kustomize could read env files `key=value pair per line`.

# Motivation

I would like to report the sync status back to gitlab. Thats is possible with Post Sync Hooks in combination with Gitlab Commit Status API. The API requires a full commit sha.
Example kustomization.yaml

```yaml
configMapGenerator:
  - name: gitlab-commit-sha
    envs:
      - argocd.env

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: GIT_COMMIT_SHA
    objref:
      kind: ConfigMap
      name: gitlab-commit-sha
      apiVersion: v1
    fieldref:
      fieldpath: data.ARGOCD_APP_REVISION
```

status.yaml

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: devops-api-service-gitlab-status-failed
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: slack-notification
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "--header"
            - "PRIVATE-TOKEN: $(GITLAB_TOKEN)"
            - "https://gitlab.example.com/api/v4/projects/2108/statuses/$(GIT_COMMIT_SHA)?state=failed&name=ArgoCD"
      restartPolicy: Never
  backoffLimit: 2
```

# Proposal

ArgoCD could expose the build environment as env file inside the work directly where the kustomize.yaml lives.
