### ISSUE TITLE
Application Caching old repository after changing to different repository type

### ISSUE THREAD

**Issue by Lemmons** [argoproj/argo-cd#5706]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When a helm chart repository which was storing a chart previously used for an application goes down, the application will fail to refresh or sync, even if it is currently using a different chart.  Deleting the application makes things worse, as once this is done, the application cannot be recreated, due to this issue.

In our specific case, the application was previously pointing to a harbor helm chart repository, but had been updated to use git directly.  When trying to do a `argocd app create` it would fail with the following error: 
```
InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in {path to chart}/: rpc error: code = Unknown desc = `helm repo add --username ****** --password ****** harbor https://{harbor-url}}` failed exit status 1: Error: looks like \"https://{harbor-url}}" is not a valid chart repository or cannot be reached: failed to fetch https://{harbor-url}}/index.yaml : 503 Service Unavailable"
```
Once the helm chart repo became healthy again, the application was able to be created and synced without issues.

Here is the application resource we were trying to apply:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: my-app
    server: '{some-kube-cluster}'
  source:
    repoURL: 'ssh://my.git.repo/repo.git'
    path: argocd/templates/my-app/
    targetRevision: HEAD
    helm:
      parameters:
      - name: 'hostname'
        value: 'my-host'
  syncPolicy:
    syncOptions:
      - createNamespace=True
```
and a previous version was:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: my-app
    server: '{some-kube-cluster}'
  source:
    repoURL: 'https://my.harbor.repo/chartrepo/library'
    chart: my-app
    targetRevision: 1.0.*
    helm:
      parameters:
      - name: 'hostname'
        value: 'my-host'
  syncPolicy:
    syncOptions:
      - createNamespace=True
```

**To Reproduce**

1. Create an app with helm repo as a source
2. Move update the app to use git for the source
3. Remove argocd's access to the chart repository somehow (running your own chart repo would be the simplest way to control this)

**Expected behavior**

When an application is changed to use a different repository type, it should not require the previous repository to still be accessible.

**Version**

```shell
> argocd version
argocd: v1.5.4+36bade7
  BuildDate: 2020-05-05T18:59:08Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
```

**Logs**

```
InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in {path to chart}/: rpc error: code = Unknown desc = `helm repo add --username ****** --password ****** harbor https://{harbor-url}}` failed exit status 1: Error: looks like \"https://{harbor-url}}" is not a valid chart repository or cannot be reached: failed to fetch https://{harbor-url}}/index.yaml : 503 Service Unavailable"
```
