### ISSUE TITLE
Strongly-typed API for ArgoCD Configuration

### ISSUE THREAD

**Issue by sbose78** [argoproj/argo-cd#5721]
# Summary

Introduce a strongly-typed `Config` API/CRD to manage ArgoCD configuration as an alternative to [argocd-cm.yaml](https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml)

# Motivation

## Why

- Maintaining a large ArgoCD configuration configmap such as https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml is error-prone in the absence of native validation/feedback.
- There is no way to find out which config options are supported without referring to version-specific docs.
- There is no good way to provide feedback to the admin/operator on the correctness of the  config in argocd-cm.

## How

- Have a Kubernetes-native way of defining structured configuration information
- De-couple areas of configuration which may grow overtime ( repos, health-checks ).
- Encourage client tooling to make use of native OpenAPI Validation before letting in configuration information.

# Proposal

How do you think this should be implemented?

* Introduce a CRD with an OpenAPI validation schema `ArgoCDConfig`. The OpenAPI validation schema would drive generation of UI forms and IDE code completion. 
* Deprecate specification of repository configuration in the "main" config and instead use the `GitRepositoryConfig` CRD as proposed in https://github.com/argoproj/argo-cd/issues/5720
*  Deprecate specification of health checks in the "main" config and instead use the `HealthCheck` CRD as proposed in < yet to add proposal >
* **Backward compatibility** : Honor argocd-cm.yaml if the `ArgoCDConfig` CR is absent.

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDConfig
metadata:
  name: hello-world
spec:
  url: https://github.com/argoproj/my-private-repository
  statusBadge: 
    enabled: hello-world-secret
  users:
    anonymous:
      enabled: true
    session:
      duration: "24h"
  ga:
    trackingID: UA-12345-1
    anonymizeusers: "false"
  help:
    chatUrl: "https://mycorp.slack.com/argo-cd"
    chatText: "Chat now!"
    
    
  authConfig:
    dex:
      connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: aabbccddeeff00112233
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: your-github-org
            teams:
            - red-team
```
