### ISSUE TITLE
Can't deploy application if OLM Subscription has never been applied in cluster

### ISSUE THREAD

**Issue by aceeric** [argoproj/argo-cd#5738]
I have one Argo CD Application deploying an app with many manifests generated by `kustomize`. The three manifests causing this issue are:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: my-operator-group
  namespace: test-ns
spec:
  targetNamespaces:
  - test-ns
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: runtime-component-operator
  namespace: test-ns
spec:
  channel: runtime-component-operator-0.7.0
  installPlanApproval: Automatic
  name: runtime-component-operator
  source: my-disconnected-operators-registry
  sourceNamespace: olm
---
apiVersion: app.stacks/v1beta1
kind: RuntimeComponent
metadata:
  name: my-app
  namespace: test-ns
spec:
  ...
```
if I hand-deploy this application: `kustomize build | kubectl apply -f -` The following will happen in a cluster _in which the operator has never been subscribed_: The `OperatorGroup` and `Subscription` will deploy and `kubectl` will fail on the `RuntimeComponent` resource because the subscription has not fulfilled and therefore the cluster does not contain that CRD. So - wait until the subscription completes (CSV is showing `Succeeded`) and redo the `kubectl apply` and the second time it succeeds. Thereafter in that cluster, every kube apply will work fine.

When deployed using Argo CD v1.8.3 the same behavior occurs in a cluster in which the operator has never been subscribed. If I hand-sync the` OperatorGroup` and `Subscription` in the UI, then hand sync everything else, the sync succeeds. But if I let Argo sync it - it fails with "app.stacks/v1beta1/RuntimeComponent the server could not find the requested resource". Once successfully sync'd, all successive syncs succeed.

I tried annotating both the `OperatorGroup` and `Subscription` with `argocd.argoproj.io/hook: PreSync` hoping that these would be handled in the pre-sync. But no luck there - and when I look at the application in the UI, those two resources are excluded from the resource network diagram in this case. And again if I try to hand sync the `Application` it fails with the same message. (The UI doesn't show me the  `OperatorGroup` and `Subscription` to hand-sync.)

It seems Argo CD  should cleanly handle this OLM _first operator subscription in cluster_ use case. Otherwise some work-around would need to be devised.
