### ISSUE TITLE
Hot reload of dex/oidc config hangs argocd-server: Unable to load data: grpc: the client connection is closing

### ISSUE THREAD

**Issue by ryota-sakamoto** [argoproj/argo-cd#5742]
**Describe the bug**

application list is not correct display after editing `dex.config` in `argocd-cm`.
`Unable to load data: grpc: the client connection is closing` error happened.

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/~~~
    targetRevision: HEAD
    path: argocd/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

1. open https://argocd.example.com/applications
2. edit `dex.config` in `argocd-cm`
3. reopen https://argocd.example.com/applications

For example, in the case of `/api/v1/session/userinfo`.
the error happened at line 231, this code is generated by grpc-gateway.
I guess that if I will change grpc dial option, I can avoid this error.
Because maybe the client has old connections before grpc server restarts.
https://github.com/argoproj/argo-cd/blob/1c15e1845b0151eac9fba8321fde4a61c78eca37/pkg/apiclient/session/session.pb.gw.go#L231-L236

**Expected behavior**

It will get better over time occasionally.(it  is unstable)
but we need to get back to normal quickly.

**Screenshots**

![image](https://user-images.githubusercontent.com/18019529/110838702-203eaf00-82e6-11eb-9e86-3edfddbd346c.png)

**Version**

```shell
⟩ argocd version
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T20:25:24Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.7+eb3d1fb
  BuildDate: 2021-03-03T07:13:34Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Comment by alexmt** [comment]
Can you help to reproduce it? e.g. share dex config change

**Comment by ryota-sakamoto** [comment]
@alexmt 

I share ConfigMap.
I changed dex config that it is removing `config.org` line.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 7471222a3fd8d3974850
          clientSecret: $dex.github.clientSecret
          org: parvae
```
