### ISSUE TITLE
[Enhancement] git+ssh for helm applications

### ISSUE THREAD

**Issue by JuanSeBestia** [argoproj/argo-cd#5752]
# Summary

Using helm packages with git repositories has bugged behaviors.

First, you can't create helm type repositories with ssh keys, when it tries to recognize the url, it imposes an error that the URL is malformed.

`level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = parse \"git@gitlab.com:company/repo-app.git\": first path segment in URL cannot contain colon" grpc.code=Unknown grpc.method=GetHelmCharts grpc.service=repository.RepositoryService grpc.start_time="2021-03-12T14:41:39Z" grpc.time_ms=13.276 span.kind=server system=grpc`

You can hack this by telling argocd that this repository is a git repository. it incredible works!

Second, when you want to perform the umbrella helm pattern or Apps in Apps pattern described in the guide, either using an App-helm or App-kustomize. This won't work, because the version only supports samver as a version and I can't include the branch/tag as a version. 

It is very strange because it is only the behavior of the helm version, it only happens when it is a child of another App.

![image](https://user-images.githubusercontent.com/7362688/110988912-23b25480-833f-11eb-85e0-026a7ba82863.png)

Take this example:

Has two Application, invoice that is a helm app and sales that it would contain an array of applications (for this example only contain invoice)

```bash
sales-apps
├── sales-chart
│   ├── Chart.yaml
│   ├── charts
│   ├── templates
│   │   ├── _helpers.tpl
│   │   └── invoice-aplication.yaml
│   └── values.yaml
└── sales-aplication.yaml
```

sales-application.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sales
spec:
  project: default
  source:
    repoURL: git@gitlab.com:company/sales-repo.git
    targetRevision: feature/argocd-poc
    path: sales-apps/sales-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
```

invoice-application.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invoice
spec:
  project: default
  source:
    repoURL: git@gitlab.com:company/invoice-repo.git
    targetRevision: feature/argocd-poc
    path: invoice/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: sales-namespace
```
# Motivation 

The charts are first in git repositories before being published and many clients prefer **DO NOT** publish these charts, they are already protected by git security.

Similarly, we are using 2FA for git and it cannot support basic auth at all within them.

It's clear that this behavior is GitOps 

# Proposal

* Support helm-repository with ssh
* Support helm-app whit git
