### ISSUE TITLE
Upgrade ArgoCD 1.8.1 -> 1.8.7 - now web UI is a blinkin

### ISSUE THREAD

**Issue by mabushey** [argoproj/argo-cd#5754]
This appears to be just a display issue, but now about every 2 seconds 1 to 5 of the 7 applications go from green to yellow and stay yellow for up to 3 seconds. Kind of looks like flashing Christmas lights.

The repo is in GitHub. The only difference from stock config is I add `kustomize.buildOptions: --enable_alpha_plugins`  in `argocd-cm` and use the awesome SopsSecretGenerator plugin to decrypt the secrets (gcp-kms).

**Comment by mabushey** [comment]
Here are screenshots, it changes like this every couple of seconds.
![2021-03-12_argocd1](https://user-images.githubusercontent.com/7863135/111002142-219dc500-8342-11eb-9f8c-6dd9328ce160.png)
![2021-03-12_argocd2](https://user-images.githubusercontent.com/7863135/111002145-22cef200-8342-11eb-948e-cfad946be7df.png)
![2021-03-12_argocd3](https://user-images.githubusercontent.com/7863135/111002146-22cef200-8342-11eb-836d-d49f38768471.png)

By the way, ArgoCD is absolutely amazing. :)

**Comment by mabushey** [comment]
If I go into an app, It's the Namespace block that's having issues, every 6 seconds the green checkmark is replaced with a grayed out pacman ghost with a grayed out circle to the right which lasts for 1 second, and then back to 6 seconds of green. My namespace has two things going on different from typical: 1. istio injection enabled, 2.  A transformer adding the `app.kubernetes.io/instance` label. I'm adding this label as ArgoCD adds it, so I want CLI vs ArgoCD to have the exact same result.

base/ns.yaml
```
kind: Namespace
apiVersion: v1
metadata:
  name: httpbin
  labels:
    istio-injection: enabled
```

dev/global-labels.yaml
```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  app.kubernetes.io/instance: dev-httpbin
fieldSpecs:
  - path: metadata/labels
    create: true
    ```
