### ISSUE TITLE
Speed up SSH by reusing connections in reposerver

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#5765]
# Summary

Speed up SSH by reuse connections in reposerver

# Motivation

We have hit ssh connection limit with just two reposerver from time to time

```
rpc error: code = Unknown desc = ssh: handshake failed: ssh: disconnect, reason 12: Too many concurrent connections (64) - max. allowed: 64
```

It seems argocd establishes a new SSH connection for each operation. This not only consumes lots of resources but also slows down actions like set and refresh.

# Proposal

Adopt the configuration recommended in https://puppet.com/blog/speed-up-ssh-by-reusing-connections/

**Comment by yujunz** [comment]
Current work around is mount ssh config in repo server.

e.g.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: ssh-config-d
          mountPath: /etc/ssh/ssh_config.d
      volumes:
        - name: ssh-config-d
          configMap:
            name: argocd-ssh-config-d-cm
```
