### ISSUE TITLE
Support prometheus operator rbac defaults

### ISSUE THREAD

**Issue by conorfennell** [argoproj/argo-cd#577]
The [default](https://github.com/coreos/prometheus-operator/blob/f70c3e32032e2aada8273328260e446e5b99f05e/example/rbac/prometheus/prometheus-cluster-role.yaml#L17) prometheus operator configuration requires access to a `nonResourceURLs` resource `/metrics` .
```YAML
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

The `argocd-manager-role` policy does not provide permissions for `nonResourceURls`.
Therefore any rbac role being created by Argo cannot create roles with these permissions.

I think it would be resonable to add the `metrics` endpoint with the `get` verb as a default configuration.

```YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - /metrics
  verbs:
  - get
```
