### ISSUE TITLE
ArgoCD: Proxy/NoProxy not regarded with dex sso configuration

### ISSUE THREAD

**Issue by oliverbaehler** [argoproj/argo-cd#5781]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Set Noproxy/Proxy environment variables are not regarded when calling sso endpoint. Noone was able to help me in the slack channel. I will try to see if I can find the bug myself and do a pr.

**To Reproduce**

Does someone have a Setup with ArgoCD SAML over Dex in a Proxy environment? My ArgoCD Config looks something like this:

```
url: https://argo.company.com/api/dex/callback
dex.config: | 
         logger:
            level: debug
            format: json
          connectors:
          - type: saml
            id: saml
            name: Bedag
            config:
              ssoURL: https://adfs.company.com
              entityIssuer: https://argo.company.com/api/dex/callback
              caData: |
                 ....
              redirectURI: https://argo.company.com/api/dex/callback
              usernameAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
              emailAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
              groupsAttr: http://schemas.xmlsoap.org/claims/Group
```

This works as expected when not having a Proxy/NoProxy defined. Since our Setups have to use Proxy to have internet access, i tried to add Proxy variables:

```
env:
  - name: "HTTP_PROXY"
    value: "http://proxy.company.com"
  - name: "HTTPS_PROXY"
    value: "http://proxy.company.com"
  - name: "NO_PROXY"
    value: "localhost,127.0.0.1,10.0.0.0/8,*.company.com"
```    
    
Everything seems to be fine after applying the changes, but once i try to login via saml, i get a 503 Response from the Proxy:
Failed to query provider "https://argo.company.com/api/dex": 503 Service Unavailable
So the question is, why does the Proxy respond me? I defined that domain as No Proxy in the environment. Note, that this request is made for the config.url from the argocd config, so if I change that to another url it's going to request that. Is it possible that this specific request does not regard proxy environment variables? Or Am I missing out on something...

**Expected behavior**

NoProxy and Proxy environment variables should be regarded when using a sso configuration.

**Screenshots**

![image](https://user-images.githubusercontent.com/26610571/111234842-b9740b00-85ef-11eb-9dda-cffbffbbc69f.png)

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
