### ISSUE TITLE
multiple application sources defined: Helm,Plugin

### ISSUE THREAD

**Issue by clcchai** [argoproj/argo-cd#5791]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

app spec looks like
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: cpaas-argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    helm:
      valueFiles:
      - values.yaml
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```

issue:
rpc error: code = Unknown desc = multiple application sources defined: Helm,Plugin

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by clcchai** [comment]
error: rpc error: code = Unknown desc = multiple application sources defined: Helm,Plugin

**Comment by jannfis** [comment]
This is not a bug imho, since `plugin` defines just another application type. You can't mix it with other types.

**Comment by clcchai** [comment]
@jannfis  hi how would you get this to work? if you want to declare helm as source and use the custom plugin?

**Comment by WillooWisp** [comment]
This seems like a bad decision, since there are good use cases where both helm and plugin are needed. I my case I utilize the application set and generate apps from a template with a dynamically specified helm values file based on environment and use plugin for kustomized-helm. Not being able to do this seems like a flaw.

```
helm:
  releaseName: '{{path.basename}}'
  valueFiles:            
    - '../../../{{path.basename}}/globals.yaml'
    - 'values.yaml'
plugin:
  name: kustomized-helm
```
