### ISSUE TITLE
Support for application name alias

### ISSUE THREAD

**Issue by musabmasood** [argoproj/argo-cd#5807]
# Issue

Because ArgoCD stores applications as manifests in the same namespace (argocd), application names need to be unique. For a centralized multi-tenant ArgoCD setup, this leads to long application names often prefixed with `<project>` for instance:

```
mycompany-myproject1-myapp1
mycompany-myproject2-myapp1
mycompany-myproject1-myapp2
mycompany-myproject2-myapp2

```

This makes it them harder to search on the UI and the experience is just not as great.

# Proposal

Support application alias (e.g. Jenkins - Staging) which, if set, will be displayed in the UI instead of the actual application name. The `Application` declaration could then be:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mycompany-staging-guestbook
  namespace: argocd
  alias: Guestbook - Staging # optional
  finalizers:
    - resources-finalizer.argocd.argoproj.io
```
