### ISSUE TITLE
Unable to connect HTTPS repository: permission denied: repositories, create

### ISSUE THREAD

**Issue by suhas316380** [argoproj/argo-cd#5824]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `argocd version`.

**Describe the bug**

When attempting to add a Bitbucket repository via the UI, i see and error: "Unable to connect HTTPS repository: permission denied: repositories, create,https://myrepo.com/test.git, sub: xxxx, iat: 2021-03-19T18:31:49Z. 

**To Reproduce**

Following the steps outlined in: 
- ArgoCD setup: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- Steps followed to setup argoCD authentication with Azure on EKS: https://argoproj.github.io/argo-cd/operator-manual/user-management/microsoft/#azure-ad-app-registration-auth-using-oidc

References:
- https://github.com/argoproj/argo-cd/blob/master/assets/builtin-policy.csv

Trying to use argoCD authentication with Azure on EKS.

My configMaps:
```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
data:
    oidc.azure.clientSecret: <redacted>
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
    url: https://argocd.mydomain.com
    oidc.config: |
        name: Azure
        issuer: https://login.microsoftonline.com/<redacted>/v2.0
        clientID: <redacted>
        clientSecret: <redacted>
        requestedIDTokenClaims:
            groups:
                essential: true
        requestedScopes:
            - openid
            - profile
            - email  
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:  
    policy.default: role:readonly
    policy.csv: |
        p, role:org-admin, applications, *, */*, allow
        p, role:org-admin, clusters, get, *, allow
        p, role:org-admin, repositories, get, *, allow
        p, role:org-admin, repositories, create, *, allow
        p, role:org-admin, repositories, update, *, allow
        p, role:org-admin, repositories, delete, *, allow
        g, "<redacted>", role:org-admin  
```
If I change "policy.default: role:readonly" to "policy.default: role:admin", it works fine but this isn't what I want. As an admin, I would have admin access to the UI and everyone else would have readonly access.

**Expected behaviour**

Be able to add a respository in the argoCD UI

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v1.8.6+6dbbb18
  BuildDate: 2021-02-26T21:21:11Z
  GitCommit: 6dbbb18aa963a0c9e608fcfeab4065c6fb46f8cb
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Logs from argocd-server pod
```
time="2021-03-19T18:36:54Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListRepositoryCredentials grpc.service=repocreds.RepoCredsService grpc.start_time="2021-03-19T18:36:54Z" grpc.time_ms=0.727 span.kind=server system=grpc
time="2021-03-19T18:37:02Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: repositories, create, https://myrepo.com/test#, sub: gredacted, iat: 2021-03-19T18:31:49Z" grpc.code=PermissionDenied grpc.method=Create grpc.service=repository.RepositoryService grpc.start_time="2021-03-19T18:37:02Z" grpc.time_ms=0.596 span.kind=server system=grpc
time="2021-03-19T18:44:25Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: repositories, create, https://myrepo.com/test.git, sub: gredacted, iat: 2021-03-19T18:31:49Z" grpc.code=PermissionDenied grpc.method=Create grpc.service=repository.RepositoryService grpc.start_time="2021-03-19T18:44:25Z" grpc.time_ms=0.653 span.kind=server system=grpc
```
