### ISSUE TITLE
independent version controlled helm values file

### ISSUE THREAD

**Issue by perezjasonr** [argoproj/argo-cd#5826]
# Summary

followup on #2719 reopening this proposal. The author closed it but I disagree with the conclusion and believe this should still be pursued.

# Motivation

To not allow the values file to be independently version controlled and checked into git in my opinion goes against the spirit of gitOps and forces design that is not ideal. In abandoning this proposal you closely couple the snowflake values/desired results of a single install to the chart itself.

This means either

a) for every given set of values files for an install the entire helm chart has to be replicated just for the values file.
or
b) the helm chart itself requires every possible desired values file preexisting within it.

so if I have three environments managed by 3 teams, but all three of those teams can reference a chart I designed, this means either all 3 of these teams must replicate the entire chart and modify it uniquely for their scenario even though I've given read/pull access to the chart and their argocd instance can reference it directly. Why do that when they can reference the chart and check in just the values?

or the reverse:
for each of these 3 teams I have to preload their values files in my chart. so they can update it, I now have to give them push/write access to my repo, or they have to tell me what they want if thats not their role and I have to add it.

Furthermore this seems to be intentional with helm. With helm, we can reference a chart, designed by someone else and version control our values file. Not allowing this takes away an option we have with helm itself although I admit having the inline values in the app object helps bridge that gap...but an independent values file route can be used both by someone just using regular helm AND someone using argocd.

In my mind decoupling the two is superior in many ways...maybe not every way, but many.
Indeed, this is a design choice and I think you should do w/e works best for your situation but I think version controlling the values file independently should at least be an option, alongside having the inline values of the argo app object, or cloning the entire chart and putting your own values file in it. Right now we don't have that option.

# Proposal

same as 2719 something like this:

Proposal
```
...
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: my-chart
    targetRevision: 1.0.0
    helm:
      valuesRepo: https://gitlab.com/someproject/path.git
      valuesFiles:
        - values/some/value.yaml
```

**Comment by blacksd** [comment]
We're in the middle of a software selection process, and this, coupled with the lack of an efficient solution for the secrets management (or robust integration with a project like SOPS or Vault that can supply it) is one of the major show stoppers. 

From my perspective, asking to version the values together with the charts is not just an antipattern, it's a plain wrong choice: I have to be able to version my configuration and my charts following two independent paths.

**Comment by eytanhanig** [comment]
Not being able to separate them is also a security risk. We want developers to be able to self-manage environment variables and CI/CD to update and auto-commit image tags when new images are built **without giving either write-access to more sensitive parts of our charts and values files**.

**Comment by JulienBreux** [comment]
Hi !

I agree with that!

I've the same problem, but I've discover that:

https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/project.yaml#L14-L15

It's not a way for a project to link a specific Git repository for configuration files?
(I have not tested)

**Comment by andrei-dascalu** [comment]
+1 for this.

I was actually just looking around today a bit dumbfounded that if I need to pick a chart from a Helm repo to deploy it, I can't provide my own versioned values file(s) and instead I need to manually override values in the Application (either UI or in Git).

This is actually pretty bad in that even with sops integration, we should still be able to provide separately versioned files otherwise we need to encrypt by default the entire Application spec (or not) rather than just values that are secrets.

**Comment by awiesner4** [comment]
Adding to the requests for this functionality.  In my opinion, requiring a separate values.yaml file to have to exist alongside the chart is a Helm anti-pattern.

It would definitely be extremely beneficial to support simply supplying a values path to inject into the application that is separate from the actual Chart location.

That being said, for others, there is a current workaround that, while hacky, does work with minimal extra overhead (though having this workaround should not suggest that the functionality being requested is not needed).

In your `values.yaml` directory in repo A, per App you want to deploy, create a corresponding `Chart.yaml`.  In the `Chart.yaml` declare a dependency section that points to the actual remote Helm chart repo.  Inside your `values.yaml` next to the `Chart.yaml`, just make sure to add a top-level key matching the sub-chart name so it can pick up your parent `values.yaml` values. Then, in your `Application` CR for your app in ArgoCD, point that to your values.yaml location.  

Here is an example config i'm using successfully for `cert-manager`:

**repoA/charts/cert-manager/Chart.yaml:**
````
apiVersion: v2
name: cert-manager
version: 1.1.0
type: application
dependencies:
  - name: cert-manager
    version: v1.1.0
    repository: "https://charts.jetstack.io"
````

**repoA/charts/cert-manager/values.yaml**
````
cert-manager:
  installCRDs: true
  global:
    imagePullSecrets:
      - name: dockercredentials
 ````

repoB/apps/templates/cert-manager.yaml
````
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    path: charts/cert-manager
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/repoA/helm-values.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
````

As I said, it's a bit hacky to create an empty parent chart to just point to the chart you want, but it basically results in the desired outcome, with only one extra file next to your values.yaml.

**Comment by arramos84** [comment]
No idea why this has been debated for so long. It's a no brainer that being able to override a chart's values from a helm repo without having to use a "proxy chart" should be standard. I was really surprised to see this when I started my migration from flux to argo. Put it on pause for now.

**Comment by andrei-dascalu** [comment]
@awiesner4 hardly a workaround. You need to create a proxy chart. Basically you wrap a chart into another that's in a git repo instead of a helm repo for the benefit of being in VC.

That said, you might want this if the "app chart" brings together several different charts.

I wonder though if it wouldn't work to version the ArgoCD Application. An override values yaml is part of the definition of Helm Applications so that could be versioned.

**Comment by KaiReichart** [comment]
I will have a look at solving this, this is a major pain point for us currently too. 
Do you guys have any preferences about notation in the template? I was thinking of something like this:
```yaml
spec:
  source:
    helm:
      extraValueFiles:
        - repo: https://github.com/repoA/helm-values.git
          valueFiles:
             - values1.yaml
             - values2.yaml
        - repo: https://github.com/repoB/helm-values.git
          valueFiles:
             - values1.yaml
             - values2.yaml
```
