### ISSUE TITLE
Network view does not map Ingress with networking.k8s.io/v1 apiVersion to targeted services.

### ISSUE THREAD

**Issue by dhnukem** [argoproj/argo-cd#5839]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I recently updated my ingresses to use `apiVersion: networking.k8s.io/v1` due to the warnings that the `extensions/v1beta1` ingresses are deprecated.    However, now when I view my project's network view, the ingresses that I have updated do not show any relationship to the services.

**To Reproduce**

Create Ingress using the `networking.k8s.io/v1` apiversion to connect to a service (I used statefulset, but I think any deployment will show this issue).

**Expected behavior**

I would expect that the new ingress would show a mapping to a targetted service.

**Screenshots**

This is a screenshot of two ingresses using the new API version, and one using the old apiVersion.   Only the old apiVersion is showing a mapping to its targeted services.

![Selection_065](https://user-images.githubusercontent.com/12902525/112066705-71437400-8b2c-11eb-8e3d-e4a19baaf681.png)

**Version**

```shell
argocd: v2.0.0-rc1+0ca643f
  BuildDate: 2021-03-19T21:27:59Z
  GitCommit: 0ca643f027b99e8a5b931bb8ee9df42c3e4b64bf
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Volkmire** [comment]
@backjo, @jessesuen Are you sure this issue is fixed?

Using v2.1.6+a346cf9.
I'm playing around with ArgoCD atm, trying to figure out the ropes. I have an ingress `guestbook` map to the service `guestbook`. 
Cluster-side ingress is working (I'm receiving reply from the service), but on network view it looks like this:
![image](https://user-images.githubusercontent.com/48139665/141323116-19575f0c-a2a3-4410-b9ee-f74f9fbe6318.png)

Ingress:
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    argocd.argoproj.io/instance: guestbook
  name: guestbook
  namespace: guestbook
spec:
  rules:
    - host: guestbook.fu
      http:
        paths:
          - backend:
              service:
                name: guestbook
                port:
                  number: 3000
            path: /
            pathType: Prefix
```

Service:
``` yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: guestbook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: guestbook
    argocd.argoproj.io/instance: guestbook
    helm.sh/chart: guestbook-0.2.0
  name: guestbook
  namespace: guestbook
spec:
  ports:
    - port: 3000
      targetPort: http-server
  selector:
    app.kubernetes.io/instance: guestbook
    app.kubernetes.io/name: guestbook
  type: ClusterIP
```
