### ISSUE TITLE
[SPIKE] check compatibility with ArgoCD and nginx-ingress

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#585]
User reported that ELB (passthrough) to nginx-ingress to argocd was not working properly.

**Comment by empath** [comment]
To add some more details:
going through nginx, and a tcp elb listener, i get rpc error: code = Unavailable desc = transport is closing
The only way i can get it to work is with a tcp elb listener and a node port service.

**Comment by empath** [comment]
if someone has an example of an nginx ingress config that works, that would be great.

**Comment by jessesuen** [comment]
I determined out how to get nginx-ingress to work with ArgoCD:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: argocd-server-ingress
  namespace: argocd
spec:
  rules:
  - host: argocd.example.com
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https```
```

Note that this requires nginx-controller to be run with the `--enable-ssl-passthrough` option, and a passthrough ELB.
