### ISSUE TITLE
Cannot apply CustomResourceDefinitions from namespaced install eventhough RBAC allows it

### ISSUE THREAD

**Issue by wilmardo** [argoproj/argo-cd#5886]
**Describe the bug**

We are using ArgoCD in a managed cluster where we have rights within our namespaces. So we use the namespaced ArgoCD install with a cluster with namespaces defined:
```yaml
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cluster-kubernetes.default.svc
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: '{"tlsClientConfig":{"insecure":false}}'
  name: iks-cluster
  namespaces: argocd,playground,tools
  server: https://kubernetes.default.svc
```
We also have the right to create CRDs in the clusterscope, but just CRDs nothing else. This gives us the ability to install applications within our namespaces that define CRDs, like ArgoCD or Gloo.
This gives us an issue with Argo, in the namespaced setup it errors when applying CRDs:
```
Cluster level ClusterIssuer "letsencrypt-production" can not be managed when in namespaced mode
```

When I set `namespaces: *` Argo cannot connect to the cluster anymore since RBAC doesn't allow clusterresources other then the CRDs:
```
failed to sync cluster https://10.43.0.1:443: failed to load initial state of resource Deployment.apps: deployments.apps is forbidden: User "system:serviceaccount:argocd:argocd-application-controller" cannot list resource "deployments" in API group "apps" in the namespace "*
```
I traced the change back to this PR:
https://github.com/argoproj/gitops-engine/pull/143

It shipped with ArgoCD 1.7.7, we are now pinned to 1.7.6. In that version it applies the CRDs fine, it just has no diff and is permanently `OutOfSync`

**To Reproduce**

* Setup ArgoCD as a namespaced install with a namespace set for the cluster.
* Create the RBAC underneath to give ArgoCD permission to apply CRDs at the clusterscope.
* Apply an CRD, I included a `ClusterIssuer` as an example.
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: argocd:admin
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: info@example.org
    privateKeySecretRef:
      name: le-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
            class: nginx
```

**Expected behavior**

ArgoCD to apply the CRD and have a `Healthy` status.

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:45:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by alexmt** [comment]
As of v2.1 it is possible to enable cluster level resources in a namespaced mode using:

```
argocd cluster add <context> --cluster-resources=true --namespace my-namespace
```

**Comment by nnachefski** [comment]
I'm getting the same issue....  

ComparisonError: Cluster level Namespace "elastic-test" can not be managed when in namespaced mode

ServiceAccount has cluster-wide policy.  this whole thing worked fine until the auto-update on my argocd cluster/operator that occurred today.

**Comment by nnachefski** [comment]
Ugh, i just checked on my other "prod" clusters for a different customer... same issue.  broke everything.

**Comment by magf** [comment]
> Ugh, i just checked on my other "prod" clusters for a different customer... same issue. broke everything.

are you done that?

> Add a label to the namespace your application is deployed in so that the Argo CD instance in the openshift-gitops namespace can manage it:

```bash
$ oc label namespace spring-petclinic argocd.argoproj.io/managed-by=openshift-gitops
```
it was described [here](https://docs.openshift.com/container-platform/4.7/cicd/gitops/configuring_argo_cd_to_recursively_sync_a_git_repository_with_your_application/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html#creating-an-application-by-using-the-oc-tool_configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations)

**Comment by Cuball0** [comment]
> ServiceAccount has cluster-wide policy. this whole thing worked fine until the auto-update on my argocd cluster/operator that occurred today.

We are experiencing the sames issues, after the auto-update of ArgoCd everything is messed up, apparently ArgoCD cannot manage the namespaces anymore.

Namespace "yyyy" for ConfigMap "jenkins-rrrrr" is not managed

Did you find a solution for this?  We are running ArgoCD v2.1.6 in Openshift 4.6

**Comment by jaipalkomakula** [comment]
Hello, Any solution for this issue:  Namespace "yyyy" for "resources" "jenkins-rrrrr" is not managed

**Comment by gkmahendran09** [comment]
We are able to fix this issue by adding the below key/value in the `argocd-default-cluster-config` secret.

```
clusterResources: true
```

![image](https://user-images.githubusercontent.com/3875338/144000902-850e8115-489f-4101-939c-324fd737a65f.png)

We are running ArgoCD v2.1.6 in Openshift 4.7.30

**Comment by Cuball0** [comment]
We are you are using the ArgoCD Operator (in Openshift).  I'm not sure, but it could be that the operator reconciles the default secret.

We solved it by adding 
```
config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: argocd
```
the following env variable to the Subscription of the Operator  (where the value is the namespace of the argocd installation)
