### ISSUE TITLE
argocd unable to manage Node resource - Resource /Node worker-4 is excluded in the settings

### ISSUE THREAD

**Issue by clcchai** [argoproj/argo-cd#5891]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

```
apiVersion: v1
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: worker-4
    kubernetes.io/os: linux
    node: worker
    node-role.kubernetes.io/app: ""
    node-role.kubernetes.io/worker: ""
    node.openshift.io/os_id: rhcos
  name: worker-4
spec:
  ignoreDifferences:
  - group: apps
    kind: Node
    jsonPointers:
    - /metadata/annotations
```

**Expected behavior**

Node resource is synced in argo but not the case.

received warning - 
ExcludedResourceWarning
Resource /Node worker-4 is excluded in the settings

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```
