### ISSUE TITLE
GitLab Groups are not fetched from userinfo endpoint

### ISSUE THREAD

**Issue by MatteoJoliveau** [argoproj/argo-cd#5944]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using [GitLab](https://docs.gitlab.com/ee/integration/openid_connect_provider.html) as an OIDC provider, groups are not mapped to Argo and are therefore not usable in RBAC policies. GitLab does not return group membership info in the ID token, only in the `/userinfo` endpoint. I suspect ArgoCD is not calling that endpoint for user information but only reading the ID token.

**To Reproduce**

- Configure GitLab as an OIDC provider with the following configuration:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: |
    name: GitLab
    issuer: https://gitlab.example.com
    clientID: REDACTED
    clientSecret: $oidc.gitlab.clientSecret
    # the groups scope is not supported by GitLab. Groups are returned as part of the openid scope
    requestedScopes: [openid profile email]
```
- check `https://argocd.example.com/user-info` for the list of groups
- confirm that the GitLab groups are NOT showing in the `Groups` section

**Expected behavior**

ArgoCD calls the `/userinfo` endpoint of the GitLab instance to retrieve group membership info.

**Screenshots**

![image](https://user-images.githubusercontent.com/9077612/113294645-8e7bfd80-92f7-11eb-8343-97014871823c.png)

**Version**

```shell
> argocd version
argocd: v1.4.2+48cced9
  BuildDate: unknown
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.15.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0-rc1+0ca643f
  BuildDate: 2021-03-19T21:27:59Z
  GitCommit: 0ca643f027b99e8a5b931bb8ee9df42c3e4b64bf
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
```

**Logs**

Notice the lack of `groups` claim in the field `grpc.request.claims`.
```
time="2021-04-01T12:21:44Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims="{\"aud\":\"353ab692234207c659960bcbc31696753ee13f6502e3f32c03d49b682ab00221\",\"auth_time\":1617275574,\"email\":\"matteo.joliveau@mikamai.com\",\"email_verified\":true,\"exp\":1617279821,\"iat\":1617279701,\"iss\":\"https://gitlab.example.com\",\"sub\":\"87\",\"sub_legacy\":\"718eb3690efda2cdebed7e194436a5405b2a1e55854aa4403a7437acd0c6d158\"}" grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-04-01T12:21:44Z" span.kind=server system=grpc
```
