### ISSUE TITLE
fix docu of Ingress configuration for kubernetes v1.19+

### ISSUE THREAD

**Issue by rsoika** [argoproj/argo-cd#5962]
# Summary

Fix Ingress documentation

# Motivation

current example is not according to Kuberenetes 1.19+

# Proposal

I suggest to replace the Ingress Example  using SSL-Passthrough with cert-manager and Let's Encrypt as followed:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # If you encounter a redirect loop or are getting a 307 response code 
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: argocd.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server
            port:
              name: https
  tls:
  - hosts:
    - argocd.example.com
    secretName: argocd-secret # do not change, this is provided by Argo CD
```

I also created a Pullrequest which was rejected for policy reasons 

https://github.com/argoproj/argo-cd/pull/5961
