### ISSUE TITLE
Disagreement in three way diff calculation

### ISSUE THREAD

**Issue by fabriziofortino** [argoproj/argo-cd#597]
I am trying to use argocd with this elasticsearch helm chart https://github.com/helm/charts/tree/master/incubator/elasticsearch

Here is how my `Application` looks like

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-observe
spec:
  project: observe
  source:
    repoURL: git@github.com:helm/charts.git
    path: charts/incubator/elasticsearch
    componentParameterOverrides:
    - name: cluster.name
      value: elasticsearch-observe
    - name: master.persistence.storageClass
      value: ebs-gp2
    - name: data.persistence.storageClass
      value: ebs-gp2

  destination:
    server: https://kubernetes.default.svc
    namespace: observe
```

The application remains in `OutOfSync`. Here is the output of the `app diff`:

```
argocd app diff elasticsearch-observe
WARN[0001] Disagreement in three way diff calculation: {"spec":{"volumeClaimTemplates":[{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"30Gi"}},"storageClassName":"ebs-gp2"}}]}}
WARN[0001] Disagreement in three way diff calculation: {"spec":{"volumeClaimTemplates":[{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"4Gi"}},"storageClassName":"ebs-gp2"}}]}}
===== ConfigMap elasticsearch-observe ======
===== Service elasticsearch-observe-client ======
===== Service elasticsearch-observe-discovery ======
===== Deployment elasticsearch-observe-client ======
===== StatefulSet elasticsearch-observe-data ======

===== StatefulSet elasticsearch-observe-master ======

```
