### ISSUE TITLE
node view isn't showing pod that can't get into node

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5981]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Nodes for which pods want to get into, but can't get in, aren't shown in the nodes view

**To Reproduce**

1. Have a node with insufficient capacity for a pod 
    e.g.
    ```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchFields:
                  - key: metadata.name
                    operator: In
                    values:
                      - gke-default-cluster-default-pool-cd475819-7c1f
    ```
2. Switch to pods view by parent resource
3. See pod unhappy
4. Switch to node view
5. Look for pod

**Expected behavior**

If a pod is asking explicitly for a node, show the node the pod is trying to get into even if it isn't there.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/113843531-a6250d00-9761-11eb-9dbe-e1c130824047.png)
![image](https://user-images.githubusercontent.com/2119212/113843941-0320c300-9762-11eb-955a-c59022473d88.png)

**Version**

```shell
{
    "Version": "v2.0.0+d085636",
    "BuildDate": "2021-03-30T19:10:08Z",
    "GitCommit": "d085636fd72c170d0553a2db1f0de8e6ea0df398",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

Reason | Message | Count | First Occurred | Last Occurred
-|-|-|-|-
NotTriggerScaleUp | pod didn't trigger scale-up: 9 node(s) didn't match node selector | ... | ... | ...
FailedScheduling | 0/26 nodes are available: 1 Insufficient cpu, 25 node(s) didn't match node selector. | ... | ... | ...

```
Paste any relevant application logs here.
```
