### ISSUE TITLE
ArgoCD cli login does not work neither for Ingress or LoadBalancer

### ISSUE THREAD

**Issue by Born2Bake** [argoproj/argo-cd#5983]
I can login and use ArgoCD UI via both Ingress and LoadBalancerIP. However, if I try to login via cli it's not working either way:

```
argocd login --insecure --grpc-web --username admin --password xxxxxxxxxxxx 10.25.0.12
WARNING: server is not configured with TLS. Proceed (y/n)? y
FATA[0031] rpc error: code = Unknown desc = Post "https://10.25.0.12:443/session.SessionService/Create": net/http: TLS handshake timeout
---
argocd login --insecure --grpc-web --username admin --password xxxxxxxxxxx my.domain.com
WARNING: server is not configured with TLS. Proceed (y/n)? y
FATA[0020] rpc error: code = Unknown desc = POST http://my.domain.com:443/session.SessionService/Create failed with status code 400
```

Ingress:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: my.domain.com
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https
        path: /
  tls:
  - hosts:
    - my.domain.com
    secretName: argocd-secret
```

P.S. ssl-passthrough is set to nginx-ingress-controller in helm via

```
extraArgs:
  enable-ssl-passthrough: 'true'
```

LB config:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  clusterIP: 10.99.251.76
  clusterIPs:
  - 10.99.251.76
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30872
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31691
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.25.0.12
```

**Comment by seangallavan** [comment]
I'm having the same problem with port forwarding

**Comment by andrei-dascalu** [comment]
@Born2Bake is your argocd server running with --insecure flag? I'm not sure if what you're doing make sense .... asking for an insecure connection  on an ingress that works on HTTP with HTTPS passthrough to an https backend ?

**Comment by Born2Bake** [comment]
> @Born2Bake is your argocd server running with --insecure flag? I'm not sure if what you're doing make sense .... asking for an insecure connection on an ingress that works on HTTP with HTTPS passthrough to an https backend ?

Hi, ArgoCD was deployed via 
```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.1/manifests/ha/install.yaml

 k get po -n argocd
NAME                                       READY   STATUS    RESTARTS   AGE
argocd-application-controller-0            1/1     Running   1          46h
argocd-dex-server-5dd657bd9-2ldnf          1/1     Running   1          46h
argocd-redis-ha-haproxy-5886787f8b-9bdhs   1/1     Running   1          46h
argocd-redis-ha-haproxy-5886787f8b-9qvlh   1/1     Running   1          47h
argocd-redis-ha-haproxy-5886787f8b-swgsp   1/1     Running   1          47h
argocd-redis-ha-server-0                   2/2     Running   2          46h
argocd-redis-ha-server-1                   2/2     Running   2          47h
argocd-redis-ha-server-2                   2/2     Running   2          47h
argocd-repo-server-f6ccdd667-ddqtz         1/1     Running   1          46h
argocd-repo-server-f6ccdd667-vlkls         1/1     Running   1          47h
argocd-server-56659b9dd8-qvfgc             1/1     Running   1          47h
argocd-server-56659b9dd8-vbt82             1/1     Running   1          46h
```
As I shared configuration for both LB and Ingress objects, I am not sure what exactly I did wrong with both cause I followed official docs. I tried the same thing without --insecure flag and got the same results:

```
bn@DESKTOP-IQ0K33P:~$ argocd login --grpc-web --username admin --password kTCXvPVbWFxzEUDW 10.25.0.12
WARNING: server is not configured with TLS. Proceed (y/n)? y
FATA[0032] rpc error: code = Unknown desc = Post "https://10.25.0.12:443/session.SessionService/Create": net/http: TLS handshake timeout
bn@DESKTOP-IQ0K33P:~$ k get ingress -n argocd
NAME                    CLASS    HOSTS                ADDRESS                                  PORTS     AGE
argocd-server-ingress   <none>   deploy.domain.com  172.16.1.135,172.16.1.143,172.16.1.150   80, 443   11d
bn@DESKTOP-IQ0K33P:~$ argocd login --grpc-web --username admin --password kTCXvPVbWFxzEUDW deploy.domain.com 
WARNING: server is not configured with TLS. Proceed (y/n)? y
FATA[0023] rpc error: code = Unknown desc = POST http://deploydomain.com:443/session.SessionService/Create failed with status code 400
```

**Comment by andrei-dascalu** [comment]
@Born2Bake Yeah, I'm also not an expert, just brainstorming against what I've experimented with.

Are you running your ingress with passthrough enabled ? (for nginx ingress "--enable-ssl-passthrough" in the args list)?

**Comment by Born2Bake** [comment]
> @Born2Bake Yeah, I'm also not an expert, just brainstorming against what I've experimented with.
> 
> Are you running your ingress with passthrough enabled ? (for nginx ingress "--enable-ssl-passthrough" in the args list)?

Yup

```
image:
  registry: docker.io
  repository: bitnami/nginx-ingress-controller
  tag: 0.44.0-debian-10-r28
extraArgs:
  enable-ssl-passthrough: 'true'
```
