### ISSUE TITLE
Cannot create repository declaratively (error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified")

### ISSUE THREAD

**Issue by pr-mu-deploy** [argoproj/argo-cd#6000]
**Describe the bug**

- Using the declarative configuration to create a repository doesn't work:
![image](https://user-images.githubusercontent.com/35437420/113982137-bf29dd00-988b-11eb-8bca-fa1d116390ce.png)
- Using the ArgocdUi to create the repository works:
![image](https://user-images.githubusercontent.com/35437420/113982446-1cbe2980-988c-11eb-9929-c33bb0e2dc57.png)

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bootstrap-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: cluster-charts
    repoURL: git@github.com:xxx/xxx-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:xxx/xxx-infrastructure.git
      name: test
      sshPrivateKeySecret:
        name: github-xxx-infrastructure-private
        key: sshPrivateKey
```

**Version**

```json
{
    "Version": "v1.8.7+eb3d1fb",
    "BuildDate": "2021-03-03T07:13:34Z",
    "GitCommit": "eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

`error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"`

```sh
time="2021-04-07T08:06:12Z"
level=error
msg="finished unary call with code Unknown"
error="error creating SSH agent: \"SSH agent requested but SSH_AUTH_SOCK not-specified\""
grpc.code=Unknown
grpc.method=GenerateManifest
grpc.request.deadline="2021-04-07T08:07:12Z"
grpc.service=repository.RepoServerService
grpc.start_time="2021-04-07T08:06:12Z"
grpc.time_ms=0.174
span.kind=server
system=grpc
```
