### ISSUE TITLE
Identical time values shouldn't be treated as different or the FAQ should suggest using `knownTypeFields`

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#6008]
**Workaround**
See https://github.com/argoproj/argo-cd/issues/6008#issuecomment-1346433001

**Not a general suport forum**
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

**Checklist**

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The prometheus-community helm chart is using a short time format, and cert-manager is using golang's Duration.string() function which writes out long time format (including hours and minutes).

duration: 8760h0m0s and duration: 8760h are treated as different.

This triggers annoying sync behaviors

https://github.com/prometheus-community/helm-charts/pull/750

**To Reproduce**

install cert-manager using:
```yaml
name: cert-manager
apiVersion: v2
appVersion: "1.0"
description: Cert Manager
version: 1.0.4
dependencies:
  - name: cert-manager
    version: 1.0.4
    repository: https://charts.jetstack.io
```

install prometheus operator using:
```yaml
name: prometheus-operator
apiVersion: v2
appVersion: "1.0"
description: Prometheus operator
version: 14.4.0
dependencies:
  - name: kube-prometheus-stack
    version: 14.4.0
    repository: https://prometheus-community.github.io/helm-charts
```

Possibly add some values to ensure the certificate is created:

values.yaml:
```yaml
kube-prometheus-stack:
  prometheusOperator:
    tlsProxy:
      enabled: false
    admissionWebhooks:
      certManager:
        enabled: true
      enabled: false
```

https://github.com/prometheus-community/helm-charts/pull/750

**Expected behavior**

ideally `duration` fields would be understood as times and compared as times.

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/114216154-88f46800-9934-11eb-8d99-211196969d73.png)

\# | Live | # | Desired
-- | -- | -- | --
56 |  prometheus-kube-prometheus-operator.metrics | 56 |  prometheus-kube-prometheus-operator.metrics
57 |  prometheus-kube-prometheus-operator.metrics.svc | 57 |  prometheus-kube-prometheus-operator.metrics.svc
58 | duration: 8760h0m0s | 58 | duration: 8760h
59 | issuerRef: | 59 | issuerRef:
60 | name: prometheus-kube-prometheus-root-issuer | 60 | name: prometheus-kube-prometheus-root-issuer

**Version**

```shell
{
    "Version": "v2.0.0+d085636",
    "BuildDate": "2021-03-30T19:10:08Z",
    "GitCommit": "d085636fd72c170d0553a2db1f0de8e6ea0df398",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by andrein** [comment]
I'm hitting the same issue with https://github.com/ns1/cert-manager-webhook-ns1

![image](https://user-images.githubusercontent.com/52871/135857180-d82d1c41-2844-43b4-aaea-991cbf6362e1.png)

**Comment by leotomas837** [comment]
Any news on this ? I am hitting the same issue too by installing Istio-csr (from cert-manager). The certificate is included in the chart so I have no control over the duration (on my own certificates I set the full duration for ex `1h0m0s` to prevent the OutOfSync).

**Comment by leotomas837** [comment]
Any news on this ? I am hitting the same issue too by installing Istio-csr (from cert-manager). The certificate is included in the chart so I have no control over the duration (on my own certificates I set the full duration for ex 1h0m0s to prevent the OutOfSync).

**Comment by micahmo** [comment]
We have added an `ignoreDifferences` to our `Application` to handle this case. The downside is that if the duration really does change, Argo won't detect that it's out of sync. But since that's rare, this is preferable to having an app that's forever out of sync.

``` yaml
ignoreDifferences:
- group: cert-manager.io
  kind: Certificate
  jsonPointers:
  - /spec/duration
  - /spec/renewBefore
```

This is definitely still a bug, though, when the values are functionally identical.

**Comment by leotomas837** [comment]
@micahmo Thanks for the tip, well found 👍🏻 but indeed that is not entirely ideal (I guess you need to force sync to apply changes ? Or change manually)

**Comment by mstarostik** [comment]
Same for the timeout fields in ClusterAPI's MachineHealthCheck resources:

```
[...]
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 300s
  - type: Ready
    status: "False"
    timeout: 300s
```

Becomes:
```
[...]
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 5m0s
  - type: Ready
    status: "False"
    timeout: 5m0s
```

and is treated as out of sync by Argo CD, correctly so given it's a string field. However, some heuristics would be nice to compare the usual time values. As doing that in general might cause underdetection of real differences, one suggestion would be to expand on `ignoreDifferences` to declare fields as elligible for semantical time value comparison instead of treating them as an opaque string. Or automatically apply such a logic when field names include substrings like `time`, `interval` etc.

**Comment by theelderbeever** [comment]
Having this problem with a Redpanda helm chart as well with the additional issue that Argo wants to add `isCA: false`.


<img width="1143" alt="image" src="https://user-images.githubusercontent.com/29295582/232359603-7647df01-1567-4910-8068-b23843727968.png">

**Comment by Kavinraja-G** [comment]
Haha, I came here after facing the same issue with Redpanda and few others. Is there any progress on this issue ?

**Comment by dntosas** [comment]
are you using `ServerSideApply=true` people ?

**Comment by matthewhughes934** [comment]
There's a solution for this in `v2.10.0` via a7d0da941cc9d92f3aef19acc0c898a43fee3b16 which adds support for `meta/v1/duration` as a known diffing type (docs: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#known-kubernetes-types-in-crds-resource-limits-volume-mounts-etc) so it's just a matter of letting Argo know about the type of the field:

```yaml
apiVersion: v1
kind: configMap
metadata:
  name: argocd-cm
data:
  resource.customizations.knownTypeFields.cert-manager.io_Certificate |
    - field: spec.duration
      type: meta/v1/Duration
```
