### ISSUE TITLE
Redis container fails to start

### ISSUE THREAD

**Issue by hrpatel** [argoproj/argo-cd#6040]
Hello,

The Redis container fails to start while deploying ArgoCD on k3s using the `install.yaml` manifest. 

**To Reproduce**

```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

**k3s version**

```shell
k3s --version
k3s version v1.20.5+k3s1 (355fff30)
go version go1.15.10
```

**Event Log**

```
Error: container has runAsNonRoot and image will run as root (pod: "argocd-redis-869ccb7478-lrxxp_argocd(9cd55b49-6e04-4da1-8d9d-cdd33b39fbef)", container: redis)
```

The [image](https://github.com/docker-library/redis/blob/master/6.2/Dockerfile) from Docker hub does not specify `USER`

**Workaround**

```diff
diff --git a/argoproj/argo-cd/install.yaml b/argoproj/argo-cd/install.yaml
index d691207..d36b0ec 100644
+++ b/argoproj/argo-cd/install.yaml
@@ -2599,7 +2599,7 @@ spec:
         - containerPort: 6379
       securityContext:
         runAsNonRoot: true
+        runAsUser: 999
       serviceAccountName: argocd-redis
 ---
 apiVersion: apps/v1
```

**Comment by jannfis** [comment]
@sbose78 can you please take a look, since I believe this is due to https://github.com/argoproj/argo-cd/pull/5863

**Comment by alexmt** [comment]
Strange, https://github.com/argoproj/argo-cd/pull/5863 did not get into v2.0.  The `stable` tag has `runAsUser: 1000`

https://github.com/argoproj/argo-cd/blob/f5119c06686399134b3f296d44445bcdbc778d42/manifests/base/redis/argocd-redis-deployment.yaml#L19

Also, I'm able to reproduce the using master but not stable tag.

**Comment by sbose78** [comment]
Good it didn't get into the stable tag :D 

Alex, does this break on non k3s clusters too? Very curious :( 

Sorry for breaking this, I will revisit my change.

**Comment by alexmt** [comment]
No problem @sbose78 :) I've reproduced it on EKS cluster. I won't be surprised if minikube/k3s ignore `runAsNonRoot `

**Comment by alexmt** [comment]
Also, it affects only non-HA manifests. All our test environments use HA versions. That is why we did not notice the issue immidiatelly

**Comment by jannfis** [comment]
We could also think about migrating the Redis image used to `bitnami/redis`, which is built with non-root in mind. This would work using `runAsNonRoot: true` without having to specify a `runAsUser`.

I just tested this on a local setup, using K3s. The manifests (command arguments) would need a slight adoption as well, e.g.

```yaml
      containers:                                   
      - args:                                    
        - --save                                    
        - ""                                        
        - --appendonly                              
        - "no"                                      
```

would need to become, due to changes in the container's startup.

```yaml
      containers:                                   
      - command:                                    
        - /opt/bitnami/scripts/redis/run.sh         
        - --save                                    
        - ""                                        
        - --appendonly                              
        - "no"                                      
```
