### ISSUE TITLE
Allow administrator enable lua standard library for health checks.

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#6050]
# Summary

For security reasons standard library is disabled lua based health check. However, this is blocking the implementation of complex health checks that requires functions like `string.find` or `string.match`. (https://github.com/argoproj/argo-cd/issues/6039) . 

# Motivation

The argocd administrator should be able to enable the standard library after reviewing the script.

# Proposal

* Enable standard library for built-in health checks
* Introduce `health.lua.useOpenLibs: true` setting that could be set be Argo CD admin and enable standard library  support for a specific health check:
```yaml
apiVersion: v1
data:
  resource.customizations: |
    kubernetes-client.io/ExternalSecret:
      health.lua.useOpenLibs: true
      health.lua: | ....
```
