### ISSUE TITLE
SSH user form config is not used

### ISSUE THREAD

**Issue by kuburoman** [argoproj/argo-cd#6053]
We have 1000+ apps so we would like to use ssh config but user is not used from .ssh/config.

# How to replicate

We have config: 
```
apiVersion: v1
data:
  config: |-
    Host my.git.cz
        User argo_cd
        Port 2222
        HostName mine.git.cz
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argo-ssh-config
 ```

Mount it to argocd-repo-server and argocd-server.
 ```
volumeMounts:
  - mountPath: /home/argocd/.ssh/config
     name: argo-ssh-config
     subPath: config 
 ```
 
 Add repository:
 ```
   repositories: |
    - url: ssh://my.git.cz/ci/kubernetes-descriptors
      sshPrivateKeySecret:
        name: repository
        key: argocd_key
 ```
 
 But sync fails because user from .ssh config is not used.
