### ISSUE TITLE
OCI chart as dependency

### ISSUE THREAD

**Issue by mballoni** [argoproj/argo-cd#6062]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Just upgraded out argocd from 1.8.x to v2.0.1+33eaf11 so we are trying to use OCI hosted helm charts.
The OCI helm itself works like a charm (as oposed to the 1.8.x version).
However when we have a helm chart in a git repository that has this OCI helm as a dependency it fails. More details below. 

**To Reproduce**
Our application Chart.yaml in the git repository looks like:

```
apiVersion: v2
name: sample-app
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: chart-name
    repository: "oci://registry.gitlab.com"
    version: 0.2.0
```
This repo happens to be previously added to argocd using the cli:

```shell
argocd repo add registry.gitlab.com --type helm --name repo-name --enable-oci --username [user] --password [password]`
```
There is also a values.yaml with the non-default values I wanna override from the inherited chart.

**Expected behavior**
The git repository should allow an application to be created with this OCI chart dependency.

What we get instead is that this chart (the OCI dependency) could not be found in the charts directory (see the logs)

**Version**

```shell
 v2.0.1+33eaf11
```

**Logs**

Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in prometheus-contract-first-sample/dev: rpc error: code = Unknown desc = `helm template . --name-template sample-app --namespace apps --values values.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions crd.k8s.amazonaws.com/v1alpha1 --api-versions vpcresources.k8s.aws/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds` failed exit status **1: Error: found in Chart.yaml, but missing in charts/ directory: chart-name**

**Comment by mballoni** [comment]
Additional info:

Tried to change the Chart.yaml from

```yaml
apiVersion: v2
name: sample-app
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: chart-name
    repository: "oci://registry.gitlab.com"
    version: 0.2.0
```

to 

```yaml
apiVersion: v2
name: sample-app
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: chart-name
    repository: "oci://repo-name"
    version: 0.2.0
```

**repo-name** is the OCI repository from the repo add command described above.

**Log:**

Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in [app repo path here]: rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: could not download oci://repo-name/chart-name: failed to do request: Head "https://repo-name/v2/chart-name/manifests/0.2.0": dial tcp: lookup repo-name on 10.205.0.10:53: no such host

Also tried without "oci://" given the repo is already added as OCI:

```yaml
apiVersion: v2
name: sample-app
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: chart-name
    repository: "repo-name"
    version: 0.2.0
```
**Log:**
rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: no repository definition for repo-name. Please add them via 'helm repo add' Note that repositories must be URLs or aliases. For example, to refer to the "example" repository, use "https://charts.example.com/" or "@example" instead of "example". Don't forget to add the repo, too ('helm repo add').

**Comment by jannfis** [comment]
This might be fixed by #6027

**Comment by mayzhang2000** [comment]
There is a test case of storing helm chart in git repository and this helm chart has OCI dependencies:https://github.com/argoproj/argo-cd/blob/master/test/e2e/testdata/helm-oci-with-dependencies/Chart.yaml

**Comment by mballoni** [comment]
@mayzhang2000 is it for the 2.1 release? I see the reference file was created 8 days ago.

If that is the case I'll wait for this next release. 

Thank you, I appreciate your help.

**Comment by mballoni** [comment]
@mayzhang2000 thank you for the clarification.

I supose we will still need to export HELM_EXPERIMENTAL_OCI=1, right?

In this case, should it happen in the argocd agent/node instances? Can we use some sort of configuration for it?

**Comment by mayzhang2000** [comment]
@mballoni, for the current v2.0.1 release, you need to do `argocd repo add <your helm oci repository> --type helm --name repo-name --enable-oci` after this, argocd would export HELM_EXPERIMENTAL_OCI=1.

In the future release, this dependency repo add is taken care of by argocd.

**Comment by mballoni** [comment]
@mayzhang2000 got it, that is already done then.
Thank you, I appreciate your patience.

Can we consider this issue as a duplicate of #6027 ?

**Comment by mayzhang2000** [comment]
@mballoni I don't think this is a duplicate of #6027. This `argocd repo add` for your helm oci repository is needed.

**Comment by mballoni** [comment]
@mayzhang2000 but we did the `argocd repo add` , as far as I understood I still need to wait for the 2.1 release, right?

**Comment by mayzhang2000** [comment]
@mballoni, I see you did 'argocd repo add registry.gitlab.com`, wonder if you have done 'argocd repo add' for your helm OCI repository?

**Comment by mballoni** [comment]
Oh got it!
registry.gitlab.com is my OCI helm repository.

In my scenario I have another chart in a git repository (not a helm or oci helm repository) that includes a chart as a dependency from a private registry.gitlab.com oci helm repository, hence that configuration.

**Comment by stijnbrouwers** [comment]
I just tried this with v2.0.1 of the application when using an AWS ECR OCI repo.
I created the repo in argocd
```
argocd repo add <account_id>.dkr.ecr.<region>.amazonaws.com --type helm --name <a name for the repo> --username AWS --password $PASSWORD --enable-oci
```
I also explicitly added set HELM_EXPERIMENTAL_OCI=1 (just to be sure).
But still get the error mentioned above
```
helm template ... failed exit status 1: Error: found in Chart.yaml, but missing in charts/ directory: chart-name
```
Am I doing something wrong here?

**Comment by mballoni** [comment]
@stijnbrouwers From what I understood this will be fixed in the 2.1 release. That is exactly the same behaviour I'm getting.

**Comment by stijnbrouwers** [comment]
@mballoni 
Thanks for the reply!
I was confused since @mayzhang2000 mentioned the following comment
> Hi @mballoni, yes it is for 2.0.1 release. The test cases were added recently.
I'll wait for the 2.1.0 release then! 👍

**Comment by mballoni** [comment]
@stijnbrouwers didn't see that, thank you for pointing it out.
@mayzhang2000 Is it still expected to 2.0.1 or was it supposed to be 2.1?

**Comment by KlavsKlavsen** [comment]
Since we're having issues with argocd and many helm chart repos.. (and these chart repos are down more and more often - causing EVERYTHING to fail in argocd - even those using repos that aren't down - because argocd tries to add ALL repos before doing anything) - we were REALLY hoping to use OCI repo-cache feature - to fetch charts from our own OCI cache of charts - avoiding the issue altogether :)

**Comment by mayzhang2000** [comment]
@mballoni Sorry for the late reply. I have code 2.0.1 on my local and I am able to create an app which is stored in git repo and have dependency with OCI chart. Here is the [steps and example](https://github.com/mayzhang2000/argocd-example-apps/tree/master/helm-oci-with-dependencies) that I followed.

**Comment by mballoni** [comment]
@mayzhang2000 thank you for your example , it is very helpfull.

 I've managed to find one thing I was doing wrong about the chart name in the dependency listing, however even after fixing it (and triple checking everything else) I still get that error from the first post.
 Can it be related to the fact that I'm using an authenticated OCI repo and/or creating the app with the UI?
 
 Thank you

**Comment by mballoni** [comment]
@mayzhang2000 my apologies, today I found out my issue.
I was assuming the right name for the OCI repository would be the generic one for gitlab saas: registry.gitlab.com and my chart name the full name (without the registry).

 For anyone who ever finds this issue here is the solution.
 
 argocd repo add registry.gitlab.com/ORGANIZATION/GROUP/SUB_GROUP/ --type helm --name repo_name --enable-oci --username USERNAME --password PASSWORD
 
 And the Chart.yaml
 
 ```yaml
 apiVersion: v2
name: my-app
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: chart-name
    repository: "oci://registry.gitlab.com/ORGANIZATION/GROUP/SUB_GROUP/"
    version: 0.3.0
 ```
 
 
 What I was doing wrong was the repository with only registry.gitlab.com and the chart name as /ORGANIZATION/GROUP/SUB_GROUP/chart-name.
 
 
 Thank you folks

**Comment by stijnbrouwers** [comment]
I can confirm that it also works for AWS ECR!
I added following dependency to my chart
```
dependencies:
- name: my-chart-name
  version: 0.1.0
  repository: "oci://<aws-account-id>.dkr.ecr.<aws-account-region>.amazonaws.com/"
```
**note**: My ECR repo name and helm chart name are the same, this means that when the name of my helm chart is "my-chart-name", I made sure that's also the name of my ECR repo. I don't know if it might give issues if this should not be the case...

In ArgoCD CLI, I added the ECR helm repo as follows
```
PASSWORD=$(aws ecr get-login-password)
argocd repo add <aws-account-id>.dkr.ecr.<aws-account-region>.amazonaws.com --type helm --name my-chart-name --username AWS --password $PASSWORD --enable-oci
```
**note**: The password retrieved with "aws ecr get-login-password" is only valid for 12 hours. If you want to keep this repo active, I propose creating a cron-job that performs these commands everytime before the password expires.

**Comment by dorroddorrod** [comment]
I was able to add an ECR repo to ArgoCD but as @stijnbrouwers mentioned, the password is valid for 12hours only.
I tried adding the ArgoCD service account AWS assume role with ECR permissions but i'm not able to add a repository without user and password.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::********:role/******-ecr_role'
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: kube-infra
```

Any idea if there is any workaround ?

**Comment by stijnbrouwers** [comment]
@dorroddorrod 
I assume adding the AWS role doesn't work because ArgoCD won't try to use the AWS CLI to retrieve a token to pass along the docker login.

From the top of my head (haven't tried it) I would create a Kubernetes Cronjob that runs every 12 hours (or 11 hours to be sure there won't be any gaps between expiring tokens).
The cronjob can use the service account you created, runs an image with AWS CLI and ArgoCD CLI and runs the command I provided in my previous comment
```
PASSWORD=$(aws ecr get-login-password)
argocd repo add <aws-account-id>.dkr.ecr.<aws-account-region>.amazonaws.com --type helm --name my-chart-name --username AWS --password $PASSWORD --enable-oci
```
note that this will argocd command will create a helm repo, if it's not helm you are after you need to edit this accordingly.

**Comment by dorroddorrod** [comment]
Ok, i created this cronjob.
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-login
spec:
  schedule: "* 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: argocd-server
          containers:
            - name: ecr-login
              image: python:3.7.4-alpine3.10
              envFrom:
                - secretRef:
                    name: argocd-initial-admin-secret
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                [
                  "apk add bash openssl curl && pip3 install awscli && curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.0.3/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd && argocd login argocd-server:80 --username admin --password $password  --plaintext && ECR_PASSWORD=$(aws ecr get-login-password --region eu-central-1) && argocd repo add ********.dkr.ecr.eu-central-1.amazonaws.com --type helm --name dr-common-chart --enable-oci --upsert --username AWS --password $ECR_PASSWORD ",
                ]
          restartPolicy: OnFailure

```

Service account:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::********:role/******-ecr_role'
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: kube-infra
```

**Comment by stijnbrouwers** [comment]
@dorroddorrod 
And is it working?

**Comment by dorroddorrod** [comment]
@stijnbrouwers Yep :)

**Comment by jdfalk** [comment]
Would it be possible to get a argocd native way to do this through the AWS SDK in argocd? Or is that not possible? I'm not super excited by a cron job that if/when it fails my entire argocd installation comes to a halt. It's a great work around for now, but was just hoping a flag could be added --ecr or something like that which enables it automatically refreshing the token.

**Comment by sidewinder12s** [comment]
Can the --enable-oci flag/config be set if you are declaratively configuring your repositories through the argocd configmap?

**Comment by KlavsKlavsen** [comment]
Yes - I use Helm - and we put this in values values file:
```
         - name: helm-repo-cache
           type: helm
           url: ghcr.io/Obmondo
           enableOci: true
           usernameSecret:
           ...
```
Which is exactly what is put in configmap.

**Comment by m-yosefpor** [comment]
I've tested this with argocd v1.2-rc3, and there is still an issue with supporting OCI charts as dependency.


I've created a `git` application with some dependency to an OCI helm chart:

```
---
apiVersion: v2
name: myapp
type: application
version: 0.1.0
dependencies:
  - name: mydep
    version: 0.1.0
    repository: oci://registry.private.snappcloud.io/myrepo
```

Then I added this private OCI repository to argocd with the following command:

```
argocd repo add oci://registry.private.snappcloud.io/mydep  --type helm --name myrepo --enable-oci --username sth --password sth
```

Then I faced this issue:


```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add registry.private.snappcloud.io oci://registry.private.snappcloud.io/myrepo` failed exit status 1: Error: looks like "oci://registry.private.snappcloud.io/myrepo" is not a valid chart repository or cannot be reached: tag explicitly required
```


This is a clear bug as it is trying to run `helm repo add` with an OCI chart (which is not supported)


The issue is somewhat related to what is explained here https://github.com/argoproj/argo-cd/issues/5856. In the aforementioned issue, if there were any configured OCI repositories, it would result in argocd Helm chart dependencies update failure. The issue is addressed in https://github.com/argoproj/argo-cd/pull/5887, to avoid running `helm repo add` when a repository has `enableOCI: true`. However it only checks this in [getHelmRepo func](https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L461). To be able to use OCI dependencies, it is required to check a similar condition in [getHelmDependencyRepos](https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L477)

I'll fix this in a following PR.


argocd version:

```
argocd-server: v2.1.0-rc3+5700faf
  BuildDate: 2021-08-11T19:44:44Z
  GitCommit: 5700faf0d17dacad93c5fe96edd42fb6dd1ae7b1
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
  ```
