### ISSUE TITLE
ArgoCD always showing diff even after successful sync

### ISSUE THREAD

**Issue by musabmasood** [argoproj/argo-cd#6063]
ArgoCD `2.0.1` continuously showing diff for the following two fields even after a successful sync:

```
spec.
  syncPolicy:
    automated:
      selfHeal: false
      allowEmpty: false
```

![image](https://user-images.githubusercontent.com/8170066/115312926-4acf2380-a140-11eb-9792-ed93ef5369e2.png)
