### ISSUE TITLE
Overridden values from an Application CRD values block are not visualized under Parameters

### ISSUE THREAD

**Issue by Fresa** [argoproj/argo-cd#6086]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

Values from an Application CRD values block that overrides values from value files are not visualized under the App Details -> Parameters -> Parameters section.

**To Reproduce**

Application CRD:

```
project: default
source:
  repoURL: 'https://github.com/some-repo.git'
  path: helm/charts/bootstrap
  targetRevision: master
  helm:
    valueFiles:
      - values.yaml
      - values.dev.yaml
    values: |
      test:
        foo: "hello-from-values-block"
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated: {}

```
values.yaml:
```
test:
  foo: "hello"
```
values.dev.yaml:
```
test:
  foo: "hello-dev"
```

helm/charts/bootstrap/templates/foo.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: bar
  labels:
    test: {{ .Values.test.foo }}
spec:
  project: default
  source:
    chart: bar
    repoURL: https://foo.bar.io
    targetRevision: 1.2.3
  destination:
    namespace: foo
    server: https://kubernetes.default.svc
```

**Expected behavior**

Parameters 'test.foo' should read 'hello-from-values-block' not 'hello-dev'

**Screenshots**
Bootstrap app: App Details -> Parameters:
![image](https://user-images.githubusercontent.com/1190300/115706397-e396b680-a36d-11eb-93fe-67c2d964c67a.png)

foo app: App Details -> Summary:
![image](https://user-images.githubusercontent.com/1190300/115706821-57d15a00-a36e-11eb-8733-53e87138d492.png)

**Version**

```shell
v1.8.7+eb3d1fb
```

**Logs**

```
N/A
```

**Comment by jessesuen** [comment]
This is a valid bug. The application details API needs to use the same logic that the rendering does, in order to calculate projected parameters.

**Comment by Rishabhraghwendra18** [comment]
Hi @jessesuen . First timer this side . I will like to give it a try

**Comment by OliverLeighC** [comment]
any word on this?

**Comment by bmedici** [comment]
Hi, same behavior here while trying to specify 2 values-files. Sometimes the first one is taken into account, sometimes none of them.
Any news ?

**Comment by mnacharov** [comment]
Hi!
It looks like a mess...

According to the api of [argocd app set](https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_set/ ) we have 5 options to set values which will be used to render a helm chart:

- --values
- --values-literal-file
- --helm-set
- --helm-set-string
- --helm-set-file

The first two of them are passed to the `--values` parameter of [helm template](https://helm.sh/docs/helm/helm_template/) command. `--values` has a priority on `--values-literal-file` - [source code](https://github.com/argoproj/argo-cd/blob/dfeacd3e9e0e691ba324f57abf52b19efb432380/reposerver/repository/repository.go#L734-L767)

The last three are passed to the 
- --set
- --set-string
- --set-file

respectively. And according to the [helm logic](https://helm.sh/docs/chart_best_practices/values/#consider-how-users-will-use-your-values) overrides values

So, "Parameters" section of Argocd Application shuld describe `--set` and ` --set-string` option or in yaml - [helm.parameters section](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#build-environment):
```
spec:
  source:
    helm:
      parameters:
      - name: app
        value: $ARGOCD_APP_NAME
```

But for a some reason it [populates from `--values-literal-file` option](https://github.com/argoproj/argo-cd/blob/dfeacd3e9e0e691ba324f57abf52b19efb432380/reposerver/repository/repository.go#L1453) and `--helm-set` and `--helm-set-string` are simply ignored.

A fix of this bug is on the way..

**Comment by brat002** [comment]
It's only UX bug. Just tap Enter after fill in values field.

**Comment by chiragbhatia8** [comment]
This is actually a pain, when trying to use the appset with individual apps ability to define the parameters, I am unable to cast parameters from string to a array when using it with argocd for below template


`{{-  $projectName := printf "%s" $.Values.argocd.project.name -}}
{{- $disableAutoSync := .Values.argocd.applicationSet.disableAutoSync | default false }}
{{- $env := .Values.argocd.environment }}
{{- $identifier := "" }}
{{- if .Values.argocd.applicationSet.identifier }}
{{- $identifier = printf "-%s" $.Values.argocd.applicationSet.identifier}}
{{- end }}
{{- if .Values.argocd.applicationSet.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "%s-%s%s-appset" .Values.argocd.project.name .Values.argocd.environment $identifier }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  generators:
    - list:
        elements:
        {{- range .Values.argocd.apps }}
          - appName: {{ printf "%s-%s%s" $.Values.argocd.environment .name $identifier }}
            namespace: {{ $.Values.argocd.environment }}
            path: {{ .path }}
            parameters:
              {{- if .parameters }}
              {{- range .parameters }}
            - name: {{ .name }}
              value: {{ .value }}
              {{- end }}
              {{- end }}
        {{- end }}
  template:
    metadata:
      name: '{{ "{{appName}}" }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: {{$projectName}}-project
      source:
        repoURL: {{ $.Values.argocd.applicationSet.repo }}
        targetRevision: main
        path: '{{ "{{path}}" }}'
        helm:
          passCredentials: true
          releaseName: '{{ "{{appName}}" }}'
          valueFiles:
            {{- toYaml $.Values.argocd.valueFiles | nindent 12 }}
          parameters:
           '{{ "{{parameters}}" }}'
      destination:
        name: {{ $.Values.argocd.applicationSet.destinationName }}
        namespace: {{ $.Values.argocd.environment }}
      syncPolicy:
      {{- if eq  $disableAutoSync false }}
        automated:
          prune: true
          selfHeal: true
      {{- end }}
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=background

{{- end }}`

`Invalid value: "string": spec.template.spec.source.helm.parameters in body must be of type array: "string" (retried 2 times).
 `

**Comment by Ruby-rc** [comment]
@nitishfy If no one is assigned to this issue，Could I continue handling this issue?

Also, I noticed that when setting the value of 'valuesObject' while editing the UI YAML, the page crashes. Should we create a new issue to follow up on this?"


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
 ...

 source:
    path: app-test
    repoURL:  ''
    targetRevision: HEAD
    path: ''
    helm:
      releaseName: test
      valuesObject:
        custom: "custom"
```

![Image](https://github.com/user-attachments/assets/2be29442-84ba-4b5f-b72b-c2d2d4833e64)
