### ISSUE TITLE
[Potential Bug?] ArgoCD can't filter resources on the cluster it's installed on

### ISSUE THREAD

**Issue by edude03** [argoproj/argo-cd#6096]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Excluding a resource doesn't work when specifying the cluster name. 

When I deploy argocd to my GKE Autopilot cluster I want to prevent argo from attempting to apply MutatingWebhooks to the cluster it's installed on. 

(See #5813) for more context

**To Reproduce**

- Create a Google GKE Autopilot cluster 
- Deploy Argo 2.0.0rc1 - 2.0.1 (the versions I've tested at least) 
- edit the argocd configmap with the following:

```
 resource.exclusions: |
      - apiGroups:
        - "admissionregistration.k8s.io"
        kinds:
        - "MutatingWebhookConfiguration"
        clusters:
          - "*"
```

When clusters is "*" it works - it warns that it won't apply webhooks. 
When the cluster is 

"in-cluster" (the default name) it doesn't work - it gives an error about not being able to apply the webhooks 
"management" (I changed the cluster name) - same behaviour
"https://kubernetes.default.svc.cluster.local" - same behaviour 
"https://10.8.2.1" (the IP address that the error message reports it can't sync with) - same behaviour. 

**Expected behavior**

Expected behaviour is that Argo should not attempt to sync Mutatingwebhooks on the cluster its installed onto, but should sync them for other clusters it manages. 

**Screenshots**

(See #5813) for more context

**Comment by edude03** [comment]
I managed to solve my issue, https://10.8.2.1 is the correct value, but it expects the port as well :/ I guess this is "solved" but I think at least as far as UX goes it would be great if any of the more "stable" values could be used instead of the IP address, that way it could be setup easily in a kustomize patch

**Comment by KeisukeYamashita** [comment]
@edude03  I still have problem... Am i missing something?


```
failed to sync cluster https://10.59.10.10:443: failed to load initial state of resource MutatingWebhookConfiguration.admissionregistration.k8s.io: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:argocd:argocd-application-controller" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope: GKEAutopilot authz: cluster scoped resource "mutatingwebhookconfigurations/" is managed and access is denied
```

My configmap configurations are below

```yaml
...

  resource.exclusions: |
    - apiGroups:
        - admissionregistration.k8s.io
      kinds:
        - MutatingWebhookConfiguration
      clusters:
        - "https://10.59.10.10"
````
