### ISSUE TITLE
Argocd repo server error  "rpc error: code = Canceled desc = context canceled"

### ISSUE THREAD

**Issue by ssharma2089** [argoproj/argo-cd#6106]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

*  I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* I've included steps to reproduce the bug.
* I've pasted the output of `argocd version`.

**Describe the bug**

While upgrading from v1.8.1 to v2.0.0, argocd repo server error is showing context cancelled error.

**To Reproduce**

1. Deploy argocd v1.8.7
2. Upgrade argocd v2.0.0

**Expected behavior**

It should not show any error like this after upgrading

**Version**

argocd: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:43:46Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64

**Logs**

time="2021-04-26T07:56:52Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Check grpc.request.deadline="2021-04-26T07:57:52Z" grpc.service=grpc.health.v1.Health grpc.start_time="2021-04-26T07:56:52Z" grpc.time_ms=0.039 span.kind=server system=grpc

time="2021-04-26T07:56:59Z" level=error msg="&{0xc000c8cfa0 0xc000138b00 {} 0x529560 true false false true 0 {0 0} 0xc000d5a1c0 {0xc0004bf260 map[] false false} map[] false 0 -1 503 false false [] 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0] [0 0 0] 0xc000cab030 1} rpc error: code = Canceled desc = context canceled"

time="2021-04-26T07:57:02Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Check grpc.request.deadline="2021-04-26T07:58:02Z" grpc.service=grpc.health.v1.Health grpc.start_time="2021-04-26T07:57:02Z" grpc.time_ms=0.053 span.kind=server system=grpc

**Comment by dpinchukov-ueni** [comment]
seeing the same thing here with argocd v2.0.1+33eaf11:

```
time="2021-05-12T10:33:57Z" level=error msg="&{0xc0003203c0 0xc000d70f00 {} 0x529560 true false false true 0 {0 0} 0xc000c86600 {0xc0006f2a80 map[] false false} map[] false 0 -1 503 false false [] 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0] [0 0 0] 0xc000b750a0 1} rpc error: code = Canceled desc = context canceled"
```

with no apparent reason and nothing suggested by the surrounding log lines. This appears to be leading to crashes of argocd-repo-server and subsequent CrashLoopBackOffs.

**Comment by ssharma2089** [comment]
After upgrading to v2.0.2, I am getting below events

17m         Warning   Unhealthy                pod/argocd-redis-ha-haproxy-54654c699-zqcnk   Readiness probe failed: Get "http://10.42.1.206:8888/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
11m         Warning   Unhealthy                pod/argocd-redis-ha-haproxy-54654c699-zqcnk   Liveness probe failed: Get "http://10.42.1.206:8888/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
11m         Warning   Unhealthy                pod/argocd-repo-server-6dfd577445-qpwp7       Liveness probe failed: Get "http://10.42.1.220:8084/healthz?full=true": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Could you please tell, what is the root cause of this.

**Comment by HariSekhon** [comment]
I'm also seeing this on ArgoCD 2.0.3

**Comment by Paragon1970** [comment]
Seeing the same `context deadline exceeded'` errors. (v2.0.0).

**Comment by sshota0809** [comment]
I'm facing the same issue with v2.1.2.
Any clue?

**Comment by ddevaal** [comment]
This also happens in 2.2.0-rc1.

**Comment by ddevaal** [comment]
These crashes stopped happening when we switched from Standard_B2s to Standard_D2s_v3 VM's on AKS (Azure). I initially used a B series VM for development. I think ArgoCD crashes easily when the hardware is insufficient.

**Comment by HariSekhon** [comment]
@ddevaal thanks for the feedback, I had tuned ArgoCD resources as per this ticket below because it didn't come with resource requests which would alleviate this resource issue, I haven't had this issue in a while:

https://github.com/argoproj/argo-cd/issues/7772

This issue links to my resources settings and configs I've provided on github too.

**Comment by wangyi198682** [comment]
facing the same issue with argocd v2.2.5, and I can even clone repo from github inside the argocd-repo-server pod.

**Comment by karlkovaciny** [comment]
> You can see my ArgoCD resources settings that solved this for me in my Kubernetes repo:
> https://github.com/HariSekhon/kubernetes-configs

@HariSekhon That's a huge repo, do you remember where the resources settings went?

**Comment by HariSekhon** [comment]
@karlkovaciny well it's all prefixed with `<name>-*.yaml` so `argocd-*.yaml` would narrow it down, but here are the direct links to the `argocd-resources.*.yaml` files:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd-resources.argocd-application-controller.jsonpatch.yaml

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd-resources.argocd-dex-server.jsonpatch.yaml

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd-resources.argocd-redis-ha-haproxy.jsonpatch.yaml

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd-resources.argocd-redis.jsonpatch.yaml

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd-resources.argocd-repo-server.jsonpatch.yaml

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd-resources.argocd-server.jsonpatch.yaml

Obviously, tweak the resources to meet your environment's needs for how many apps your ArgoCD is managing... but this should get you close.

I also recommend running Goldilocks which will give you live recommendations using VPAs, which can be deployed like this:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/goldilocks-kustomization.yaml

and then just enable for the ArgoCD namespace with this label:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd-namespace.yaml

**Comment by karlkovaciny** [comment]
@HariSekhon Thank you, bookmarkable answer.

**Comment by ppferrari** [comment]
We're facing a similar issue trying to use a custom plugin to build manifests with `kustomize` and a private helm registry. 

ArgoCD version: `v2.11.3+3f344d5`

**Comment by SuperYangSong** [comment]
Maybe sometimes just restart server can fix it,  worth to try :)

**Comment by hongbo-miao** [comment]
Thanks for @HariSekhon hint! ☺️
In my case, after I add resource limitation, my Argo CD repo server keeps crashing.
It turns out Argo CD especially Argo CD repo server needs a lot of resources. Goldilocks helps me know it actually how much it needs. Here is my custom values.yaml which can give some ideas:

```yaml
controller:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
server:
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi
repoServer:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
applicationSet:
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi
dex:
  enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi
  initImage:
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
      limits:
        cpu: 50m
        memory: 256Mi
redisSecretInit:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
redis:
  enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi
notifications:
  enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi

```
