### ISSUE TITLE
Support JsonPath for diffing customization

### ISSUE THREAD

**Issue by gaurav517** [argoproj/argo-cd#6107]
# Summary

We currently use jsonPointers for diffing customization: https://argo-cd.readthedocs.io/en/latest/user-guide/diffing/. 
Because JsonPointers are quite limiting, proposal is to use JsonPath in addition to that.

# Use Cases

With JsonPointers we are limited to using index which can be error prone to specify and maintain, specially for arrays.. e.g. currently we need to use `/spec/http/0` in following example to refer to first rule defined in a virtual service:
```
ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    jsonPointers:
    - /spec/http/0
```
This depends on order of rules in virtual service.. which can be error prone and hard to maintain. Using JsonPath:  something like `.spec.http[?(@.name == "argo-managed-route")` takes away the order dependence. Another example using regex could be `jsonPath: .spec.http[?(@.name  =~ /^.*argo-managed.*/ )`.

So, both could co-exists

```
ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    jsonPointers:
    - /spec/http/0
    jsonPath: .spec.http[?(@.name  =~ /^.*argo-managed.*/ )
```
So diff rules can be applied to a combination of paths.
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
