### ISSUE TITLE
Suggest adding an ignore if there's a discrepancy and an ignore for other versions

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#6122]
# Summary

Diff Customization should identify near misses due to CRD version bumps and warn about them (not fix them, a CRD change can legitimately mean that the diff needs to be reworked)

# Motivation

Argo CD supports [Diffing Customization](https://argoproj.github.io/argo-cd/user-guide/diffing/), but eventually an app will upgrade its CRD from `alpha1` to `alpha2` or `alpha3` to `beta1` and suddenly the diffs will stop working.

This will surprise people, and debugging it isn't fun because it isn't obvious.

Yet, computers can fairly efficiently catch this and provide assistance

# Proposal

How do you think this should be implemented?

* If there's an object that's out of sync, and
* if no diff customizations apply,
* check to see if diff customizations would match the objects if not for the version
* apply a note to the object indicating this

---

Sample input:

<details><summary>Argo Diff Customization</summary>

```yaml
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - jsonPointers:
    - /spec/http
    kind: VirtualService
    name: test-deployment-app-intra-cluster
    namespace: test
  source:
    path: apps/test-deployment-app
    repoURL: https://github.com/repo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
```
</details>

<details><summary>Argo Diff Customization</summary>

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: test-deployment-app
  name: test-deployment-app-intra-cluster
  namespace: test
spec:
  gateways:
  - mesh
  hosts:
  - test-deployment-app.test.svc.cluster.local
  http:
  - match:
    - port: 8080
    name: main
    route:
    - destination:
        host: test-deployment-app-canary
        port:
          number: 8080
      weight: 1
    - destination:
        host: test-deployment-app
        port:
          number: 8080
      weight: 99
```
</details>

---

Debugging yielded:

> I realized that in client side rendered yaml, apiVersion was `v1alpha3` but when checking server side object after applying, apiVersion was `v1beta1` for networking.istio.io. Apparently k8s was converting from `v1alpha3` to `v1beta1`.
I changed to `v1beta1` on client side as well (in rendered yaml).. And that did the trick. Thanks a lot.
