### ISSUE TITLE
Knative health checks incorrectly reports degraded during install

### ISSUE THREAD

**Issue by strangiato** [argoproj/argo-cd#6130]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Health checks for operator.knative.dev/KnativeEventing and operator.knative.dev/KnativeServing incorrectly report a depreciated health status during the install process which causes the sync to get stuck.

During the install process the Ready condition has the following progression with the health status:

Ready = "Unknown" => "Progressing"
Ready = "False" => "Degraded"
Ready = "True" => "Healthy"

When using this resource with Sync-Waves this causes the sync to become stuck on this resource and it will not progress past the knative resource to deploy resources in additional sync waves without manual intervention.

**To Reproduce**

Install the knative or openshift-serverless operator onto a cluster.

Deploy the following manifest using argo:

```yaml
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  name: knative-eventing
  namespace: knative-eventing
---
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: example
  namespace: knative-eventing
data:
  example.property.1: hello
  example.property.2: world
  example.property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3
```

**Expected behavior**

The health check should have the following health reporting:

Ready = "Unknown" => "Progressing"
Ready = "False" => "Progressing"
Ready = "True" => "Healthy"

With the manifest above, the knative-eventing object should deploy successfully and the configmap should deploy after that.

**Version**

```shell
argocd: v1.8.3+0f9c684
  BuildDate: 2021-01-21T22:19:20Z
  GitCommit: 0f9c68427882bf4633d395cbfcd7c9271795fd9b
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:56:23Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
  Jsonnet Version: 
```

Additional Note:

I'm happy to submit a PR to fix the issue!
