### ISSUE TITLE
yaml type errors with kustomize and patches

### ISSUE THREAD

**Issue by snuggie12** [argoproj/argo-cd#6158]
Checklist:

* [/] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [/] I've included steps to reproduce the bug.
* [/] I've pasted the output of `argocd version`.

**Describe the bug**

We recently upgraded from 1.7.12 to 1.8.2 and noticed a weird kustomize error. In `base` a `Deployment` has `.spec.replicas` set to `OVERLAY`. In `dev` we pull in `base` and have a patch setting the replicas to `2`.

When running kustomize we see the following:
```
# base
$ kustomize-3.6.1 build | yq e -j '.spec.replicas' - | jq 'type'
"string"

# dev
$ kustomize-3.6.1 build | yq e -j '.spec.replicas' - | jq 'type'
"number"
```

However, when adding to argo the desired manifest becomes `replicas: '2'` which is a string and not the right type. We get the error:

```
error validating data: ValidationError(Deployment.spec.replicas): invalid type for io.k8s.api.apps.v1.DeploymentSpec.replicas: got "string", expected "integer"
```

This can be fixed by changing `base` to have an integer and can break again by switching back to a string.

This somehow seems like argo breaks up the overlay with a base and since the base is a string the patch must also be a string?

**To Reproduce**

base/deploy.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-test-echo
  namespace: demo
spec:
  replicas: OVERLAY
  template:
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.0
        imagePullPolicy: Always
        name: echo
        ports:
        - containerPort: 8080
          name: main
          protocol: TCP
        resources:
          limits:
            cpu: 20m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 10Mi
```

dev/deploy.patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-test-echo
  namespace: demo
spec:
  replicas: 2
```

Point the argo app at the `dev` directory

**Expected behavior**

Should render with `replicas: 2` instead of `replicas: '2'`

**Version**

```shell
argocd-server: v1.8.2+94017f2
  BuildDate: 2021-01-10T05:40:54Z
  GitCommit: 94017f2c8d97588d4aa2213713a71d51005ed62d
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```
