### ISSUE TITLE
Plugin argocd for git-crypt

### ISSUE THREAD

**Issue by gevraud** [argoproj/argo-cd#6174]
Version : 
- Argocd 1.8.7
- Argocd 2.0.1

Hello,

In our argocd config repo, we are using git-crypt with gpg keys to crypt our secrets. That means that we are using argocd plugin to unlock the repo , so argocd can read the crypted files. We have one gpg key for argocd.

Here is the config in configmap :

```
  configManagementPlugins: |    
    - name: encrypted-yaml    
      init:    
        command: ["sh", "-c"]    
        args: ["export GNUPGHOME=/home/argocd/.gnupg; export HOME=/home/argocd; eval $(gpg-agent --daemon); gpg --import /home/argo/argo.key; git crypt unlock"]                                                                               
      generate:    
        command: ["sh", "-c"]    
        args: ["find . -name '*.yaml' -exec cat {} \\;"]    
    - name: bootstrap-argo-projects    
      generate:    
        command: ["sh", "-c"]    
        args: ["find operation -name '*.yaml' -exec cat {} \\+ && find application -name 'argo.yaml' -exec cat {} \\+"]    
    - name: recursive-argo-bootstrap    
      generate:    
        command: ["sh", "-c"]    
        args: ["find . -name 'argo.yaml' -exec cat {} \\+"]    
    - name: recursive-project-deploy    
      generate:    
        command: ["sh", "-c"]    
        args: ["find . -name '*.yaml' -a ! -name 'argo.yaml' -exec cat {} \\+"]    
    - name: recursive-encrypted-project-deploy    
      init:    
        command: ["sh", "-c"]    
        args: ["export GNUPGHOME=/home/argocd/.gnupg; export HOME=/home/argocd; eval $(gpg-agent --daemon); gpg --import /home/argo/argo.key; git crypt unlock"]    
      generate:    
        command: ["sh", "-c"]    
````

It worked well when we were in version 1.7.X and below.

Now we have that kind of error

```
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): `sh -c export GNUPGHOME=/home/argocd/.gnupg; export HOME=/home/argocd; eval $(gpg-agent --daemon); gpg --import /home/argo/argo.key; git crypt unlock` failed exit status 1: gpg-agent: a gpg-agent is already running - not starting a new one gpg: key xxxx: "ArgoCD xxx<team@xxx.com>" not changed gpg: key xxx : secret key imported gpg: Total number processed: 1 gpg: unchanged: 1 gpg: secret keys read: 1 gpg: secret keys unchanged: 1 fatal: Unable to create '/tmp/http:__myrepo_url_scm_oc_projects/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue. Error: 'git checkout' failed git-crypt has been set up but existing encrypted files have not been decrypted
```

Do you have any idea why this is happening in version > 1.8.7 & 2.0.1 ?

Any workaround ?

Thx
Regards
