### ISSUE TITLE
ClusterRoleBinding defaults not detected

### ISSUE THREAD

**Issue by fabriziofortino** [argoproj/argo-cd#620]
I am using argo with the `fluentd-elasticsearch` helm chart https://github.com/helm/charts/tree/master/stable/fluentd-elasticsearch

The app remains OutOfSync because of some not detected default values for `ClusterRoleBinding`.

This is the result of the diff

```
===== ConfigMap fluentd-es-fluentd-elasticsearch ======
===== ServiceAccount fluentd-es-fluentd-elasticsearch ======
===== ClusterRole fluentd-es-fluentd-elasticsearch ======
===== ClusterRoleBinding fluentd-es-fluentd-elasticsearch ======
 {
   "apiVersion": "rbac.authorization.k8s.io/v1",
   "kind": "ClusterRoleBinding",
   "metadata": {
     "labels": {
       "addonmanager.kubernetes.io/mode": "Reconcile",
       "app": "fluentd-elasticsearch",
       "applications.argoproj.io/app-name": "fluentd-es",
       "chart": "fluentd-elasticsearch-1.0.2",
       "heritage": "Tiller",
       "kubernetes.io/cluster-service": "true",
       "release": "fluentd-es"
     },
     "name": "fluentd-es-fluentd-elasticsearch"
   },
   "roleRef": {
-    "apiGroup": "",
+    "apiGroup": "rbac.authorization.k8s.io",
     "kind": "ClusterRole",
     "name": "fluentd-es-fluentd-elasticsearch"
   },
   "subjects": [
     {
-      "apiGroup": "",
       "kind": "ServiceAccount",
       "name": "fluentd-es-fluentd-elasticsearch",
       "namespace": "observe"
     }
   ]
 }

===== DaemonSet fluentd-es-fluentd-elasticsearch ======
```

**Comment by jessesuen** [comment]
@fabriziofortino - this is actually a problem with the Helm chart. The Helm chart renders the ClusterRoleBinding as follows. Notice that apiGroup is explicitly set to empty string:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: fluentd-elasticsearch
    applications.argoproj.io/app-name: fluentd-elasticsearch
    chart: fluentd-elasticsearch-0.7.2
    heritage: Tiller
    kubernetes.io/cluster-service: "true"
    release: fluentd-elasticsearch
  name: fluentd-elasticsearch-fluentd-elasticsearch
roleRef:
  apiGroup: ""   # <<<< this really shouldn't be empty
  kind: ClusterRole
  name: fluentd-elasticsearch-fluentd-elasticsearch
subjects:
- kind: ServiceAccount
  name: fluentd-elasticsearch-fluentd-elasticsearch
  namespace: fluentd-elasticsearch
```

If you look at how the actual manifest is defined:
https://github.com/helm/charts/blob/36f368b2a68a318fb298fd1027c39cb38430f6dc/stable/fluentd-elasticsearch/templates/clusterrolebinding.yaml#L21

You will see that the `apiGroup` is set to empty string in the actual template:
```
{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fluentd-elasticsearch.fullname" . }}
  labels:
    app: {{ template "fluentd-elasticsearch.name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd-elasticsearch.fullname" . }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "fluentd-elasticsearch.fullname" . }}
  apiGroup: ""
{{- end -}}
```

Setting it to be empty string is actually worse than omitting it entirely, because the semantics of GitOps is essentially stating that the desired state for apiGroup is "", as opposed to I don't care what gets defaulted by K8s for apiGroup.

For many resource fields, Kubernetes is lenient about leaving things empty, because they will default the values with something. apiGroup is one of those cases. However in this case, it manifests itself as a OutOfSync condition because what's defined in git, is being detected as a mutated value in live. In other words, argocd is stating the user *wants* apiGroup to be empty string, but someone went ahead and changed it and populated it with a value.

The fix really needs to be made on the helm chart. One of two things should be done:
* omit `apiGroup` completely from the manifest
* set the the correct value as `rbac.authorization.k8s.io`

It's not really feasible to expect that ArgoCD understand all of the API types, and understand that apiGroup (or any other fields for that matter) are things that will get defaulted, and intelligently decide *not* to render the diff because of the understanding that it's a specially treated field that K8s will default if empty.
