### ISSUE TITLE
Argocd namespace install contains namespace in the manifests

### ISSUE THREAD

**Issue by dimitarKiryakov** [argoproj/argo-cd#6227]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD namespace install contains
```yaml
kind: ConfigMap
metadata:
  labels:
    app: argocd-redis-ha
    chart: redis-ha-4.12.9
    heritage: Helm
    release: argocd
  name: argocd-redis-ha-health-configmap
  namespace: argocd
```
which breaks the possibility to install ArgoCD in different namespaces:
https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.1/manifests/ha/namespace-install.yaml

**To Reproduce**

Deploy argocd namespace install manifest in namespace different than argocd

**Expected behavior**

To be able to deploy ArgoCD in all namespaces

**Version**
v2.0.1

**Comment by jessesuen** [comment]
We ran into this problem too. It makes it hard to use kustomize with the vended manifests. 

workaround for kustomize users is:

```
# workaround where upstream manifests are hard-wiring namespace in argocd-redis-ha-health-configmap
patches:
- patch: |-
    - op: remove
      path: /metadata/namespace
  target:
    kind: ConfigMap
    name: argocd-redis-ha-health-configmap
```
