### ISSUE TITLE
URL cannot contain colon

### ISSUE THREAD

**Issue by xiaoweihong** [argoproj/argo-cd#6236]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have add repo with yaml,but not use,log 
Unable to connect to repository: parse \"git@gitlab.xxxx.com:www/argowolf.git\": first path segment in URL cannot contain colon

**To Reproduce**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: "git@gitlab.xxx.com:xxx/argowolf.git"
      sshPrivateKeySecret:
        name: ssh-key-secret
        key: sshPrivateKey

```

**Expected behavior**

**Screenshots**

**Version**

```shell
ocker images|grep argocd
quay.io/argoproj/argocd                                  v2.0.0              8075dbad12c1        5 weeks ago         1.02GB

```

**Logs**

```
Unable to connect to repository: parse \"git@gitlab.xxxx.com:www/argowolf.git\": first path segment in URL cannot contain colon
```
