### ISSUE TITLE
Add ability to disable installation of v3 helm chart CRDs

### ISSUE THREAD

**Issue by jwenz723** [argoproj/argo-cd#6252]
# Summary

Currently with Argo CD when you define an Application declaratively to sync a V3 helm chart there is no way to disable the installation of CRDs.

For example, in the aws-load-balancer-controller helm chart the CRDs are defined in the [crds](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller/crds) directory and there is no way using a helm value to template this directory. The following application will force the user to sync the CRDs:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: someproject
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.1.4
```

# Possible Workaround

Currently to get around this limitation I am able to set the `.spec.source.helm.version` property to `v2` to cause ArgoCD to not sync the contents of the `crds` directory, like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: someproject
  source:
    helm:
      version: v2 # This causes v2 templating to be used with ArgoCD
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.1.4
```

## Update

Setting `version: v2` will only work on helm charts which have `apiVersion: v1` in Chart.yaml. So this isn't really a work around because CRDs would be managed as basic templates with `apiVersion: v1`.

# Motivation

In the kubernetes clusters which I manage I have a single ArgoCD Application which manages the installation of all CRDs since they are cluster-wide resources. We do not allow individual applications to install CRDs on their own because they could potentially conflict with other application CRDs. 

# Proposal

Add `.spec.source.helm.installCRDs` parameter to the Application CRD to allow individual applications to specify whether or not their CRDs should be synced.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: someproject
  source:
    helm:
      installCRDs: false # add this property
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.1.4
```
