### ISSUE TITLE
argocd ignores destination.namespace and deploys into default namespace

### ISSUE THREAD

**Issue by philipp1992** [argoproj/argo-cd#6274]
Hi,

im using the following application yaml with argocd 2:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
spec:
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: mongodb
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mongodb/mongodb-kubernetes-operator.git
    targetRevision: v0.6.0
    path: config/default
```

The application gets deployed into the default kubernetes namespace instead of the mongodb namespace.
The manifests under "config/default" have no metadata.namespace field.

Is there any way to force argocd to deploy them into the namespace specified under destination.namespace?

thanks
