### ISSUE TITLE
HorizontalPodAutoscaler causes degraded status

### ISSUE THREAD

**Issue by lindlof** [argoproj/argo-cd#6287]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

To scale up `HorizontalPodAutoscaler` increases the `replicas` of a `Deployment`. That seems to cause ArgoCD to consider that the service is degraded as the number of replicas running immediately after the increase will be less than what is specified in `Deployment`. The status recovers back to healthy once the `Deployment` has managed to start the desired number of replicas.

The status shouldn't be considered degraded because it's working exactly as intended and scaling up, using standard Kubernetes practices.

We are receiving notifications when the status is degraded. We're constantly getting notifications when the deployment is scaled up.

**To Reproduce**

1. Add a Deployment and a HorizontalPodAutoscaler
2. Send traffic to scale up the deployment
3. After autoscaling status of the application gets degraded

**Expected behavior**

The status shouldn't be considered degraded. Instead, it could stay healthy or be something less severe than degraded.

We expect to get notified when the status truly degrades and not during normal `HorizontalPodAutoscaler` operations.

**Version**

`v1.9.0+98bec61`

**Comment by zezaeoh** [comment]
After upgrading the version from 1.x to 2.0, I had the same issue. 👀

**Comment by pvlltvk** [comment]
We have the same issue (after upgrading to 2.0.x), but during the deployment's rollout. It seems like `maxSurge: 2` in `rollingUpdate` also causes the degraded status.

**Comment by juris** [comment]
Having the same issue with degraded HPA. Looks like it happens because HPA does not have enough metrics during a rollout. Potentially, it can be mitigated by increasing HPA cpu initialisation period `--horizontal-pod-autoscaler-cpu-initialization-period`
In my case it is not an option, as EKS does not support it [yet](https://github.com/aws/containers-roadmap/issues/159).

**Comment by mmckane** [comment]
Seeing this as well. This is causing our pipelines to fail as we validate application health as a step using `argocd app wait --health`, but there is about a 30second to 1min period where argocd marks the HPA as degraded and causes the argocd app wait --health to exit with an error code failing our pipeline.

Because we are using cloud clusters we can't change the flag --horizontal-pod-autoscaler-cpu-initialization-period on the kube controller. Would be nice if there was a way around this from an argocd standpoint other than writing a custom health check that always marks HPA's as healthy.

FYI for anyone looking for a workaround to stop the degraded status from appearing at all here is the health check we are using.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations: | 
    autoscaling/HorizontalPodAutoscaler:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Ignoring HPA Health Check"
        return hs
```

**Comment by pentago** [comment]
While approach above works, it's rather a workaround than a solution. We should solve this on an argocd-notifications side of things somehow..

**Comment by noam-allcloud** [comment]
Any new suggestions here?

**Comment by mubarak-j** [comment]
The new format as shown in [argocd docs examples](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/)  was introduced in ArgoCD v1.2.0 and explained  in the [blog release here](https://blog.argoproj.io/argo-cd-v2-1-first-release-candidate-is-ready-c1aab7795638)

So unless you're running an older version of argocd, you will need to use the new format.

**Comment by prein** [comment]
@mubarak-j thanks for answering! 
Looking into the blog post, I'm not sure what "In the upcoming release, the resource.customizations key has been deprecated in favor of a separate ConfigMap key per resource" means.

I think I found a different issue in my setup. I'm managing argocd with the helm chart, and what I came up in my values.yaml based on outdated documentation was
```
argo-cd:
  server:
    config:
      resourceCustomizations: |
        health.autoscaling_HorizontalPodAutoscaler: |
          hs = {}
          [...]
```
which was ignored.
BTW It would be great if there was a way to list/show resource customizations

**Comment by mubarak-j** [comment]
You can find argocd built-in resource customizations here: https://github.com/argoproj/argo-cd/tree/master/resource_customizations

**Comment by chris-ng-scmp** [comment]
This is a comprehensive custom health check for HPA 

I also added a condition to make sure apiVersion is not v1, as v1 only contains status in the annotation 

```
    resource.customizations.useOpenLibs.autoscaling_HorizontalPodAutoscaler: "true"
    resource.customizations.health.autoscaling_HorizontalPodAutoscaler: |
      hs = {}
      hsScalingActive = {}
      if obj.apiVersion == 'autoscaling/v1' then
          hs.status = "Degraded"
          hs.message = "Please upgrade the apiVersion to the latest."
          return hs
      end
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do
            if condition.status == "False" and condition.type ~= 'ScalingActive' then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
            end
            if condition.type == "ScalingActive" and condition.reason == "FailedGetResourceMetric" and condition.status then
                if string.find(condition.message, "missing request for") then
                  hs.status = "Degraded"
                  hs.message = condition.message
                  return hs
                end
                hsScalingActive.status = "Progressing"
                hsScalingActive.message = condition.message
            end
          end
          if hs.status ~= nil then
            return hs
          end
          if hsScalingActive.status ~= nil then
            return hsScalingActive
          end
          hs.status = "Healthy"
          return hs
        end
      end
      hs.status = "Progressing"
      return hs
```

**Comment by zdraganov** [comment]
Anyone having idea for a workaround in the Koncrete (https://www.koncrete.dev/) hosted ArgoCD?

**Comment by andrii-korotkov-verkada** [comment]
Is this still an issue? I haven't seen HPA degraded during normal operations in a while.

**Comment by younsl** [comment]
In an EKS 1.32 cluster with ArgoCD 2.13.4 installed, some Applications with HPA attached are running normally, but occasionally false degraded status alarms are being sent. This is still a valid issue, and the solution appears to be setting up [custom health checks](https://argo-cd.readthedocs.io/en/release-2.13/operator-manual/health/#custom-health-checks) for HPA. (https://github.com/argoproj/argo-cd/discussions/7936, https://github.com/argoproj/argo-cd/issues/6287)

**Comment by younsl** [comment]
In an EKS 1.32 cluster with ArgoCD 2.13.4 installed, some Applications with HPA attached are running normally, but occasionally false degraded status alarms are being sent. This is still a valid issue, and the solution appears to be setting up [custom health checks](https://argo-cd.readthedocs.io/en/release-2.13/operator-manual/health/#custom-health-checks) for HPA. (https://github.com/argoproj/argo-cd/discussions/7936, https://github.com/argoproj/argo-cd/issues/6287)

<details>
<summary>Custom health check values HPA</summary>

## Not working for me

This ArgoCD Custom Health Check configuration prevents HPA (Horizontal Pod Autoscaler) from being incorrectly marked as degraded during metric collection delays and initial startup.

This uses ArgoCD's standard naming pattern for custom health checks: `resource.customizations.health.<API_GROUP>_<RESOURCE_NAME>`

```yaml
# charts/argocd/values_my.yaml (appVersion v2.13.4)
configs:
  cm:
    resource.customizations.useOpenLibs.autoscaling_HorizontalPodAutoscaler: "true"
    resource.customizations.health.autoscaling_HorizontalPodAutoscaler: |
      hs = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "ScalingActive" and condition.reason == "FailedGetResourceMetric" then
                hs.status = "Progressing"
                hs.message = condition.message
                return hs
            end
            if condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
            end
          end
        end
        hs.status = "Healthy"
        return hs
      end
      hs.status = "Progressing"
      return hs
```

⚠️ **Not working for me**: Still getting false alerts. [Custom health checks](https://argo-cd.readthedocs.io/en/release-2.13/operator-manual/health/#custom-health-checks) not properly applied due to health keyword in the middle. It is also discussed here https://github.com/argoproj/argo-cd/issues/6175.

## Working soltuions

Custom health check for HPA:

```yaml
# charts/argocd/values_my.yaml (appVersion v2.13.4)
configs:
  cm:
    resource.customizations.useOpenLibs.autoscaling_HorizontalPodAutoscaler: "true"
    resource.customizations.useOpenLibs.keda.sh_ScaledObject: "true"
    resource.customizations: |
      autoscaling/HorizontalPodAutoscaler:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          hs.message = "Force ignoring HPA health check to prevent abnormal false alerts."
          return hs
      
      keda.sh/ScaledObject:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          hs.message = "Force ignoring KEDA ScaledObject health check to prevent abnormal false alerts."
          return hs
```

I removed health keyword from configuration path. Used nested `|` structure instead of inline configuration and force HPA status to "Healthy" to eliminate false positives.

To verify the custom health check is working:

1. Open ArgoCD UI and navigate to your application
2. Click on the HPA resource
3. Check the HEALTH field displays your custom message: "Force ignoring HPA health check to prevent abnormal false alerts."
4. If you see this message, the configuration is applied correctly

As a additional safeguard, I added a 2-minute delay before sending degraded alerts. This is mentioned in https://github.com/argoproj-labs/argocd-notifications/issues/341#issuecomment-927169471. This condition helps reduce false alerts by waiting a bit to see if the issue fixes itself before sending notifications.

argocd-notifications-cm configMap:

```yaml
data:
  trigger.on-health-degraded: |
    - description: Application status is degraded and unhealthy
      send:
      - app-health-issue
      when: app.status.health.status in ['Degraded'] and app.spec.project != 'infra' and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Minutes() >= 2
```
