### ISSUE TITLE
Update Rollout health check for Argo Rollouts v1.0

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#6321]
# Summary

Argo Rollouts v1.0 has been improved to record a phase/message in status, which Argo CD can blindly surface. e.g.

```yaml
status:
  phase: Progressing
  message: waiting for all steps to complete
```

Argo CD health lua should be improved to surface this value (after the existing check for status.observedGeneration). The equivalent go code which can be used as the base for the lua code is:

https://github.com/argoproj/argo-rollouts/blob/master/utils/rollout/rolloututil.go#L15-L25

# Motivation

This should be the last health check we ever need to make for rollouts.
