### ISSUE TITLE
ArgoCD ignores specified helm values in Argo App

### ISSUE THREAD

**Issue by shibumi** [argoproj/argo-cd#6323]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When specifying helm values via `application.spec.source.helm.values` ArgoCD ignores them and just deploys the app
with default helm values.

**To Reproduce**

1. Add the cockroachdb helm repository
2. Add the following Argo App:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb-21-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cockroachdb-21-1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    chart: cockroachdb
    repoURL: https://charts.cockroachdb.com/
    targetRevision: 6.0.1
    helm:
      releaseName: cockroachdb-21-1
      values: |
        conf.single-node: true
        statefulset.replicas: 1
        statefulset.resources.limits.cpu: 100m
        statefulset.resources.limits.memory: 512Mi
        statefulset.resources.requests.cpu: 100m
        statefulset.resources.requests.memory: 512Mi
        storage.persistentVolume.size: 1Gi
        init.resources.requests.cpu: 10m
        init.resources.requests.memory: 128Mi
        init.resources.limits.cpu: 10m
        init.resources.limits.memory: 128Mi
```

**Expected behavior**

Argo should deploy cockroachdb with the chosen values: 1 replica.
Instead, Argo deploys cockroachdb with 3 replicas.

**Screenshots**

![https://kurisu.shibumi.dev/share/img-2021-05-25-17-28-58.png](https://kurisu.shibumi.dev/share/img-2021-05-25-17-28-58.png)

**Version**

```shell
argocd: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit:
  GitTreeState:
  GoVersion: go1.16.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.2+9a7b0bc
  BuildDate: 2021-05-20T19:30:25Z
  GitCommit: 9a7b0bc35048835516fc5f5f31a93d4c1bd61242
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Comment by shibumi** [comment]
The `argoproj.io/v1alpha1/Application` clearly states that specifying values this way should be possible:

```
KIND:     Application
VERSION:  argoproj.io/v1alpha1

RESOURCE: helm <Object>

DESCRIPTION:
     Helm holds helm specific options

FIELDS:
   fileParameters	<[]Object>
     FileParameters are file parameters to the helm template

   parameters	<[]Object>
     Parameters is a list of Helm parameters which are passed to the helm
     template command upon manifest generation

   releaseName	<string>
     ReleaseName is the Helm release name to use. If omitted it will use the
     application name

   valueFiles	<[]string>
     ValuesFiles is a list of Helm value files to use when generating a template

   values	<string>
     Values specifies Helm values to be passed to helm template, typically
     defined as a block

   version	<string>
     Version is the Helm version to use for templating (either "2" or "3")
```

Do I misunderstand the use of the values block? I know that override parameters would be a solution, but if you have more than 1 value it's very toilsome to add values. With parameters the above YAML would look like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb-21-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cockroachdb-21-1
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    chart: cockroachdb
    repoURL: https://charts.cockroachdb.com/
    targetRevision: 6.0.1
    helm:
      releaseName: cockroachdb-21-1
      parameters:
        - name: "conf.single-node"
	  value: true
	- name: "statefulset.replicas"
	  value: 1
	- name: "statefulset.resources.limits.cpu"
	  value: 100m
	- name: ....
```

As you can see.. I gave up after the third.. it's just too toilsome to specify a name + value set this way instead of directly pasting the YAML paths.

**Comment by cyberbliss** [comment]
Have you tried the following:
```
values: |
        conf:
            single-node: true
        statefulset:
            replicas: 1
...
```
