### ISSUE TITLE
argo-rollouts fail on sync: the server could not find the requested resource

### ISSUE THREAD

**Issue by templarfelix** [argoproj/argo-cd#6373]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

on sync argo-rollouts error ocurre

**To Reproduce**
apply this application:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-prod-sa-east-1
  namespace: argocd
spec:
  project: argo-rollouts-prod
  destination:
    namespace: argo-rollouts
    name: cluster-prod-sa-east-1
  source:
    repoURL: https://github.com/argoproj/argo-rollouts
    path: manifests/cluster-install
    targetRevision: v1.0.1
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
```

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/3375629/120389950-7fb7c400-c303-11eb-95a1-90257dcef984.png)

**Version**
latest of argo-rollouts
latest of argoCD

**ArgoCD Version**
```
argocd: v1.7.12+602df42
  BuildDate: 2021-02-05T20:23:06Z
  GitCommit: 602df423e0d1be0e71eb204293d91969dfb77c8a
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+e44fa43
  BuildDate: 2021-05-28T23:38:29Z
  GitCommit: e44fa434abcfd622f13cf8a0107bc84752184f36
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.1.2 2021-04-15T20:38:06Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.21.0
```

**Comment by jessesuen** [comment]
```yaml
  source:
    repoURL: https://github.com/argoproj/argo-rollouts
    path: manifests/cluster-install
    targetRevision: v1.0.1
```

Argo Rollouts stopped releasing manifests as git commits. See upgrade notes in https://github.com/argoproj/argo-rollouts/releases/tag/v1.0.0. We now attach release manifests as artifacts to the release.

The manifests at the location above at manifests/cluster-install, targetRevision v1.0.1 will not be the ones in the release artifacts here:
https://github.com/argoproj/argo-rollouts/releases/download/v1.0.1/install.yaml

Can you try using the ones attached as artifacts?
