### ISSUE TITLE
Feature request: Create local users based on data from some kubernetes secret

### ISSUE THREAD

**Issue by djfinnoy** [argoproj/argo-cd#6400]
# Summary
We manage users via a third party SSO integration. Sometimes this integration breaks during dev work, and we rely on local user profiles to access ArgoCD until the problem is resolved.

We therefore need at least one local user in case of emergency, but we would like to avoid relying on manual CLI procedures to create and maintain these users.

# Motivation
Assume you are maintaining multiple clusters and multiple ArgoCD installations, all of them deployed via an Infrastructure as Code approach.
Assume there are no local users, all authentication is handled via dex.
Now imagine that we upgrade our service mesh, and something goes wrong, leaving ArgoCD unable to communicate with the third party oauth2 service.
We are now unable to access ArgoCD without a local user.

In order to do set up these local users in a secure way, my understanding is that I would need to perform manual CLI procedures on each ArgoCD installation. I would prefer to handle this in a declarative fashion.

# Proposal
Include the possibility to create local users (username and password) by referencing some kubernetes secret in the ArgoCD configuration.
This would give us the ability to inject user credentials for ArgoCD through our secret management solution (eg. Hashicorp Vault); and we could create unique passwords for each user/cluster combination through our Infrastructure as Code tool.

**Comment by alexmt** [comment]
Hello @djfinnoy , this is technically already possible but admittedly not 100% documented. 

Please check [local users](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/user-management/index.md#local-usersaccounts-v15) documentation. You can define new user by adding `account.<user-name>` in Argo CD configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.alice: apiKey, login
```

Account's password hash is stored in `argocd-secret` Secret in `accounts.<accountName>.password` key.
