### ISSUE TITLE
Orphaned RoleBindings can't be ignored

### ISSUE THREAD

**Issue by jimmyjones2** [argoproj/argo-cd#6414]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

In an OpenShift cluster, there are a number of additional RoleBindings in each namespace - eg. admin, edit, system:deployers, system:image-builders, system:image-pullers. I've also manually added a RoleBinding to grant ArgoCD admin access. I'd like to enabled detection of orphaned resourced, but ignore them.

I've added them to the default AppProject to ignore, and while other resources are ignored, the RoleBinding I list are not.

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  orphanedResources:
    ignore:
      - kind: RoleBinding
        name: admin
      - kind: RoleBinding
        name: let-argocd-deploy-here
```

Either do this on an OpenShift cluster (where the admin RoleBinding will exist) or manually create a `let-argocd-deploy-here` RoleBinding.

**Expected behavior**

OpenShift's automatically created admin RoleBinding and the manually created let-argocd-deploy-here RoleBinding are ignored

**Version**

```shell
v2.0.0+f5119c0
```
