### ISSUE TITLE
node-role labels get removed from node objects

### ISSUE THREAD

**Issue by langemar** [argoproj/argo-cd#6417]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD removes the node-role.kubernetes.io/xxx Labels from node objects even if they are present in the git manifest. Other custom labels get removed too, but this seems not that critical to me.

**To Reproduce**

Register a node with a manifest like this:

```yaml
apiVersion: v1
kind: Node
metadata:
  labels:
    dedicated: DDB
    node-role.kubernetes.io/infra: ""
    node-role.kubernetes.io/worker: null
  name: infra-ddb-1
spec:
  taints:
  - effect: NoSchedule
    key: infra
    value: reserved
  - effect: NoExecute
    key: infra
    value: reserved
  - effect: NoExecute
    key: dedicated
    value: DDB
```

And add this manifest to your git base of through

**Expected behavior**

node-role label node-role.kubernetes.io/infra: "" is **not** removed

**Version**

```shell
sh-4.4$ argocd version
argocd: v2.0.0+unknown
  BuildDate: 2021-05-14T21:41:18Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd6
```
OpenShift GitOps Operator 1.1.1 on OpenShift 4.7.12

**Logs**

```
Paste any relevant application logs here.
```
