### ISSUE TITLE
Not possible to use a plugin together with helm valueFiles configuration!

### ISSUE THREAD

**Issue by WillooWisp** [argoproj/argo-cd#6450]
I report this again, since it does not get any attention here, https://github.com/argoproj/argo-cd/issues/5791. If there is a workaround, please let me know.

Not allowing plugins together with helm source seems like a very bad decision, since there are very good use cases where both helm and plugin are needed. I my case I utilize the ApplicationSet to generate apps from a template with a dynamically specified helm values file based on environment and use plugin for kustomized-helm. Not being able to do this seems like a big flaw in the design. How can I override this limitation?

```
helm:
  releaseName: '{{path.basename}}'
  valueFiles:            
    - '../../../{{path.basename}}/globals.yaml'
    - 'values.yaml'
plugin:
  name: kustomized-helm
```
