### ISSUE TITLE
Bearer token missing in secrets when adding external cluster (AliCloud K8S)

### ISSUE THREAD

**Issue by vbem** [argoproj/argo-cd#6461]
> If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug** & **To Reproduce**

> A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

In AliCloud K8S, each "IAM" user got a fixed `kubeconfig` which only contains personal `client-certificate-data` and `client-key-data` for authentication:

```shell
# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.229.255.60:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: "218683520989850935"
  name: 218683520989850935-ccb3fb0b5b40345dcbc6450a0bae78007
current-context: 218683520989850935-ccb3fb0b5b40345dcbc6450a0bae78007
kind: Config
preferences: {}
users:
- name: "218683520989850935"
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
``` 

And `argocd cluster add` create ServiceAccount `argocd-manager` successfully on that external cluster:
```shell
# argocd cluster add 218683520989850935-ccb3fb0b5b40345dcbc6450a0bae78007
INFO[0000] ServiceAccount "argocd-manager" already exists in namespace "kube-system"
INFO[0000] ClusterRole "argocd-manager-role" updated
INFO[0000] ClusterRoleBinding "argocd-manager-role-binding" updated
Cluster 'https://10.229.255.60:6443' added

# kubectl get -n kube-system sa/argocd-manager
NAME             SECRETS   AGE
argocd-manager   1         58m

# kubectl get ClusterRole/argocd-manager-role
NAME                  CREATED AT
argocd-manager-role   2021-06-11T14:30:42Z

# kubectl get ClusterRoleBinding/argocd-manager-role-binding
NAME                          ROLE                              AGE
argocd-manager-role-binding   ClusterRole/argocd-manager-role   59m
```

Howerer, the [cluster secret](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters) created in our ArgoCD server, does NOT contains any `bearerToken` key in the JSON of `.data.config`, which looks like:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cluster-10.229.255.60-100615209
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: 218683520989850935-ccb3fb0b5b40345dcbc6450a0bae78007
  server: https://10.229.255.60:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "certData": "identical to client-certificate-data of my personal kubeconfig",
        "keyData": "identical to client-key-data of my personal kubeconfig",
        "caData": "identical to certificate-authority-data of my personal kubeconfig"
      }
    }

```

This makes ArgoCD manipulate external K8S using my personal authentication, not the created service account `argocd-manager `.

**Expected behavior**

Even `kubeconfig` only use personal `client-certificate-data` and `client-key-data` for authentication, `bearerToken` of `argocd-manager` should be use in *cluster secret*, not personal `client-certificate-data` and `client-key-data` appeared in `kubeconfig`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "bearerToken": "<authentication token> of `argocd-manager `",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate> of `argocd-manager `"
      }
    }
```

**Version**

```shell
argocd: v2.0.3+8d2b13d
  BuildDate: 2021-05-27T17:38:37Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.2+9a7b0bc
  BuildDate: 2021-05-20T19:30:25Z
  GitCommit: 9a7b0bc35048835516fc5f5f31a93d4c1bd61242
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```
