### ISSUE TITLE
Unit tests do not cover resource_customizations

### ISSUE THREAD

**Issue by romachalm** [argoproj/argo-cd#6498]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I work to add a custom health check. Adding on purpose an error in my `health_test.yaml` file, I found that `make test` does not cover any of the customizations. 

The test `TestLuaHealthScript` from `github.com/argoproj/argo-cd/util/lua/health_test.go` tries to find recursively `health.lua` from the module path, and there is none. 

**To Reproduce**

In `resource_customizations/cert-manager.io/Certificate/health_test.yaml`, change the yaml from 
```yaml 
- healthStatus:
    status: Progressing
    message: Waiting for certificate
  inputPath: testdata/progressing_noStatus.yaml
```
to 
```yaml 
- healthStatus:
    status: Whatever
    message: Waiting for certificate
  inputPath: testdata/progressing_noStatus.yaml
```

Run 
```shell
TEST_MODULE=github.com/argoproj/argo-cd/v2/util/lua make test
```

The tests pass

**Expected behavior**

The test should fail indicating that the values are not equal

**Screenshots**

N/A

**Version**

2.0.0

**Logs**

N/A
