### ISSUE TITLE
Can't add repository via cli (or UI) - getting "Forbidden" response

### ISSUE THREAD

**Issue by joseftw** [argoproj/argo-cd#6510]
**Describe the bug**
Getting the following error when trying to add a repository using **argocd repo add**
```
FATA[0000] rpc error: code = Unknown desc = Get "https://github.com/argoproj/argocd-example-apps.git/info/refs?service=git-upload-pack": Forbidden
```

I've also tried using ```--grpc-web``` to no avail.

Im running ArgoCD in OpenShift using the ArgoCD operator. I've used the following YAML when creating it:

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata: 
  name: argocd
  namespace: demo
spec: 
  dex: 
    image: quay.io/ablock/dex
    openShiftOAuth: true
    version: openshift-connector
  rbac: 
    defaultPolicy: "role:admin"
    policy: "g, system:cluster-admins, role:admin"
  server: 
    route: 
      enabled: true

```

**To Reproduce**

```
argocd repo add https://github.com/argoproj/argocd-example-apps.git --server myserver.com --insecure --auth-token MyToken 
```

**Expected behavior**
Repository gets added

**Version**

```shell
argocd: v2.0.3+8d2b13d
  BuildDate: 2021-05-27T17:38:37Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```
time="2021-06-21T07:07:10Z" level=error msg="finished unary call with code Unknown" error="Get \"https://github.com/argoproj/argocd-example-apps.git/info/refs?service=git-upload-pack\": Forbidden" grpc.code=Unknown grpc.method=Create grpc.service=repository.RepositoryService grpc .start_time="2021-06-21T07:07:10Z" grpc.time_ms=13.088 span.kind=server system=grpc
```
