### ISSUE TITLE
Inconsistent behaviour with the ignoreDifferences function

### ISSUE THREAD

**Issue by Lapeyus** [argoproj/argo-cd#6520]
while declaring an argocd application the ignoreDifferences function behaves unexpectedly, it only works if the deployment manifest has no replica declaration in the deployment definition file

I take this block directly from the documentation
```
ignoreDifferences:
 - group: apps
   kind: Deployment
   jsonPointers:
      - /spec/replicas

```

if the deployment.yaml specifies the desired replicas the ignoreDifferences section fails
```

spec:
   replicas: {{ .Values.replicaCount }}

```
but this one works
```

spec:
   #replicas: {{ .Values.replicaCount }}

```
