### ISSUE TITLE
Modification to existing keys in configmaps are rolled back regardless of the ignoreDifferences block in the app definition

### ISSUE THREAD

**Issue by Lapeyus** [argoproj/argo-cd#6521]
this ignore request has no effect in the configMap resource

```
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    jsonPointers:
    - /data
   
```
after this is applied and if a new key value is added to the configmap Argo retains the new values, but after the sync operation any modification to existing keys in the configmap are rolled back regardless of the ignoreDifferences block in the app definition.

```
    - /data
    - /data/key
```
both have no effect
