### ISSUE TITLE
Show content of a secret

### ISSUE THREAD

**Issue by fhopfensperger** [argoproj/argo-cd#6640]
# Summary

Currently it's not possible to view the data of a `Secret` in the ArgoCD Web UI, instead of the real base64 encoded values only `++++++++` is displayed. To make the values visible, annotate the secret with `argocd.argoproj.io/show-secret-value: "true"`.

# Motivation

If the secret is created by a Kubernetes controller such as a Crossplane provider and the user does not have access to the Kubernetes API, it is impossible for the user to obtain the value of the secret.

# Proposal

I've already developed the functionality and it's working fine on my system. For a secret, where we want to view the data inside the WebUI & API, we need to annotate the secret with `argocd.argoproj.io/show-secret-value: "true"`.

Example in git: 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  annotations:
    argocd.argoproj.io/show-secret-value: "true" # `TRUE, t, 1, True` is also possible
type: connection.crossplane.io/v1alpha1
```

Example in Argo Web-UI:
```yaml
apiVersion: v1
data:
  mySecretKey: ZjE2NmUwNmUtMWU3OS00ZjE0LWI3ZWQtNDUxMzZiM2NhYjYz
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/show-secret-value: 'TRUE'
...
  name: my-secret
...
type: connection.crossplane.io/v1alpha1

```

Changed code in `server/application/application.go`
```go
func replaceSecretValues(obj *unstructured.Unstructured) (*unstructured.Unstructured, error) {
        // start new lines
	if val, ok := obj.GetAnnotations()[v1alpha1.AnnotationShowSecretValue]; ok {
		if b, err := strconv.ParseBool(val); err == nil && b {
			return obj, nil
		}
	}
        // end new

	if obj.GetKind() == kube.SecretKind && obj.GroupVersionKind().Group == "" {
		_, obj, err := diff.HideSecretData(nil, obj)
		if err != nil {
			return nil, err
		}
		return obj, err
	}
	return obj, nil
}
```

If this functionality is desired, I would like to create a pull request that includes code & tests.
