### ISSUE TITLE
RBAC based on groups from GitLab doesn't work. 

### ISSUE THREAD

**Issue by PigNatovsky** [argoproj/argo-cd#6645]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**

After integrating Dex with our GitLab, I cann't set proper permissions to my users. I was trying with base group, with separated subgroup, with boths. 

**To Reproduce**

1. Integrate Dex with GitLab:
```
data:
  dex.config: |
    connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        config:
          baseURL: https://<our_GitLab_address>
          clientID: <redacted>
          clientSecret: <redacted>
          groups:
          - tooling-cluster
          - tooling-cluster/argo-admins
```
2. Configure permissions in argocd-rbac-cm (this is example with broad permissions) :
```
data:
  admin.enabled: "false"
  policy.csv: |
    g, tooling-cluster/argo-admins, role: admin
    g, tooling-cluster, role: admin
  policy.default: ""
  scopes: '[groups]'
```
3. Verify my groups in my account info screen:
```
Groups:

    tooling-cluster
    tooling-cluster/argo-admins
```
4. Try to create a new project: permission denied
5. Try to add repo: permission denied
6. Try to add cluster: permission denied

**Expected behavior**

I can manage all ArgoCD objects.

**Version**

```shell
argocd: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.4+0842d44
```

**Logs**

```
time="2021-07-06T10:48:14Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims="{\"at_hash\":\"<redacted>\",\"aud\":\"argo-cd\",\"email\":\"<redacted>\",\"email_verified\":true,\"exp\":1625654894,\"groups\":[\"tooling-cluster\",\"tooling-cluster/argo-admins\"],\"iat\":1625568494,\"iss\":\"https://<redacted>/api/dex\",\"name\":\"<redacted>\",\"preferred_username\":\"<redacted>\",\"sub\":\"<redacted>\"}" grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-07-06T10:48:14Z" span.kind=server system=grpc

time="2021-07-06T10:50:16Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied: projects, create, github-issue-example, sub: <redacted>, iat: 2021-07-06T10:48:14Z" grpc.code=PermissionDenied grpc.method=Create grpc.service=project.ProjectService grpc.start_time="2021-07-06T10:50:16Z" grpc.time_ms=0.863 span.kind=server system=grpc

```
