### ISSUE TITLE
RBAC not enforced with Google OIDC

### ISSUE THREAD

**Issue by akath19** [argoproj/argo-cd#6647]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Creating RBAC policies backed by Google OIDC SSO doesn't work, all users get assigned the `policy.default` permission regardless of what `argocd-rbac-cm` says even though Dex is passing the groups claim correctly.

We're trying to use Google OIDC instead of SAML to have correctly mapped groups instead of having to manage permissions manually per user

**To Reproduce**

1. Follow the [steps](https://dexidp.io/docs/connectors/google/) to use Dex with Google OIDC instead of SAML
2. Enable Google OIDC SSO with the following config in `argocd-cm`:

```
dex.config: |
    connectors:
    - type: google
      id: google
      name: Google
      config:
        clientID: {REDACTED}
        clientSecret: {REDACTED}
        issuer: https://accounts.google.com
        redirectURI: https://argo-cd.example.com/api/dex/callback
        serviceAccountFilePath: /creds/sa.json
        adminEmail: {REDACTED}
```

3. Configure RBAC in the following way:
```
policies.csv: |
    g, group@example.com, role:admin
policy.default: role:readonly
scopes: '[email, groups]'
```
4. Login to ArgoCD via Google
5. Try to create a new resource (I've been testing trying to create a repo)
6. All create actions get denied

**Expected behavior**
Users/Groups mapped by Dex in the `groups` claim should have the correct RBAC permissions based on the `policies.csv` contents in `argocd-rbac-cm`

**Screenshots*
Screenshot of permission denied even though my user is in the `group@example.com` group in Google Groups
![Captura de pantalla 2021-07-06 150024](https://user-images.githubusercontent.com/3260715/124659884-12033880-de6b-11eb-8747-3eeb2c2b5cb8.png)

**Version**
```shell
{
    "Version": "v2.0.4+0842d44",
    "BuildDate": "2021-06-23T01:27:53Z",
    "GitCommit": "0842d448107eb1397b251e63ec4d4bc1b4efdd6e",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```

All ArgoCD configuration is managed via Kustomize and synchronized by ArgoCD itself

**Logs**
Log snippet of `argocd-dex-server` showing that Dex correctly maps the groups a user is in in the groups claim (my own login)
```
time="2021-07-06T19:40:49Z" level=info msg="login successful: connector \"google\", username=\"Julian Cuevas\", preferred_username=\"\", email=\"jcuevas@example.com\", groups=[\"group@example.com\" \"staff@example.com\"]"
```
Log snippet of `argocd-server` showing the correct claims in grpc requests:
```
{"grpc.method":"Watch","grpc.request.claims":"{\"at_hash\":\"ec_uiox4fNrIrIIug6QvWA\",\"aud\":\"argo-cd\",\"email\":\"jcuevas@example.com\",\"email_verified\":true,\"exp\":1625686849,\"groups\":[\"group@example.com\",\"staff@example.com\"],\"iat\":1625600449,\"iss\":\"https://cd.example.com/api/dex\",\"name\":\"Julian Cuevas\",\"sub\":\"{REDACTED}\"}","grpc.request.content":{"resourceVersion":"5354726"},"grpc.service":"application.ApplicationService","grpc.start_time":"2021-07-06T19:41:30Z","level":"info","msg":"received streaming call /application.ApplicationService/Watch","span.kind":"server","system":"grpc","time":"2021-07-06T19:41:30Z"}
```

**Comment by jannfis** [comment]
I'm unsure whether that's a typo in your c&p, but

```yaml
policies.csv: |
    g, group@example.com, role:admin
  policy.default: role:readonly
  scopes: '[email, groups]'
```
should be
```yaml
policy.csv: |
    g, group@example.com, role:admin
policy.default: role:readonly
scopes: '[email, groups]'
```

(note indentation and `policy.csv` vs `policies.csv`)
