### ISSUE TITLE
Helm parameters defined in Application CRD are overriden by .argocd-source-<app>.yml

### ISSUE THREAD

**Issue by Alan-pad** [argoproj/argo-cd#6665]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Helm parameters defined in Application CRD are overriden by .argocd-source-<app>.yml

**To Reproduce**

Create an Application with Helm parameters and valueFiles defined (I didn't test without valueFiles defined so this might also be linked) :

```yaml
 project: XXX
source:
  repoURL: 'XXX'
  path: XXX
  targetRevision: master
  helm:
    valueFiles:
      - ../../../values/XXX.common.yaml
      - values.yaml
    parameters:
      - name: 'www.ingress.hosts[0].host'
        value: host
        forceString: true
destination:
  server: 'https://kubernetes.default.svc'
  namespace: XXX
syncPolicy:
  automated:
    prune: true
    selfHeal: true
```

Add an .argocd-source-<app>.yml in the same path as Application.spec.path with other Helm parameters :

```yaml
helm:
  parameters:
  - name: xxx.image.name
    value: xxx
    forcestring: true
  - name: xxx.image.tag
    value: xxx
    forcestring: true
```

- ArgoCD UI will detect the helm parameters in Application CRD and show them as overriden
- The helm template command won't have any `--set` option defined for those helm parameters 

**Expected behavior**

I expect helm parameters from Application CRD and helm parameters from .argocd-source-<app>.yml to be somewhat merge using `--set` option of Helm.

**Version**

```shell
argocd: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64```
```

Tell me if you need any more information or context
