### ISSUE TITLE
ArgoCD does not update PVC managed by StatefulSet

### ISSUE THREAD

**Issue by diodel-agr** [argoproj/argo-cd#6666]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have encountered an issue with ArgoCD while updating the size of a Persistent Volume Claim managed by a StatefulSet.
In the StatefulSet manifest, the volumeClaimTemplates storage size gets updated, the pods are restarted, however, the PVC remains to the previous size. ArgoCD does not report any sync failures.

The workaround to this issue is to manually update the PVC storage information, then kubernetes will start updating the actual storage volume to the requested size.

**To Reproduce**

The issue was encountered on an EKS cluster version 1.18.9, ArgoCD version 1.7.11, on a prometheus-stack application version 16.10.0 ([chart link](https://prometheus-community.github.io/helm-charts)). The storage class is an AWS EBS, dynamically provisioned, type gp2, filesystem type ext4.

1. Launch ArgoCD and the prometheus application. In values.yaml the configuration is something like this: 
```
storageSpec: 
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 150Gi
```
2. Then update the storage to other value. The StatefulSet gets updated, however the PVC remains at the initial size.

The structure of the StatefulSet is shown here:
![image](https://user-images.githubusercontent.com/56575851/124921967-abfce980-e001-11eb-987d-6aecf3214d9f.png)

**Expected behavior**

I expect that ArgoCD will update the volume size automatically.

**Version**

```shell
argocd: v1.7.11+97401f9
  BuildDate: 2020-12-10T02:39:33Z
  GitCommit: 97401f9bb9ec9db350d2c8bf6563f5a43b71b2c6
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
No relevant logs were found
