### ISSUE TITLE
external-links not shown in Application if it is part of AppsOfApps

### ISSUE THREAD

**Issue by tgruenert** [argoproj/argo-cd#6667]
**Describe the bug**

Normaly a link given by annotation `link.argocd.argoproj.io/external-link` should shown in app rectangle in application overview. If application is part of AppsOfApps, link is shown at umbrella application level.

**To Reproduce**

Given app 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: https://mon.wolke8.it/
spec:
  project: infrastructure-common
...
```

and AppOfApp within startup config for argocd
```
    additionalApplications:
        - name: infrastructure-common
          # namespace: istio-operator
          project: infrastructure-common
          source:
            repoURL: https://github.com/XXX/common-deployments.git
            targetRevision: dev
            path: cluster/pathToAppFiles
            directory:
                recurse: true
          destination:
            server: https://kubernetes.default.svc
          syncPolicy:
            automated:
                prune: false
                selfHeal: true
```

**Expected behavior**

If annotation is for an application the link should shown for this application also at applications overview level.

**Screenshots**

**Version**

v2.0.4+0842d44
