### ISSUE TITLE
OCI Helm Chart Application with Version Range  is Not Working

### ISSUE THREAD

**Issue by suresh-sivanantham-irm** [argoproj/argo-cd#6686]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to deploy a Helm Chart with version range as "*" and automated sync policy. It works fine if the chart is HTTPS hosted but does not work if the chart is OCI registry hosted

**To Reproduce**

* Create a kind Cluster
* Deploy Argo CD 
* Add OCI Helm Repository with command `argocd repo add <oci helm repo> --type helm --name repo_name --enable-oci --username ${GITLAB_USERNAME=} --password ${GITLAB_ACCESS_TOKEN}`
* Deploy Helm Application (with below manifest)
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tva
spec:
  destination:
    name: ''
    namespace: tva
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: <Helm repo added above>
    targetRevision: "*"
    chart: tva-helm-chart
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

The latest version of the chart must be deployed instead error is seen in Argo CD UI 

**Screenshots**

![image](https://user-images.githubusercontent.com/73496952/125119060-8a156c80-e0be-11eb-8985-5a56db769209.png)

**Version**

```shell
argocd@argocd-server-744cbfb89-rn5b4:~$ argocd version
argocd: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```
