### ISSUE TITLE
OCI chart version cannot begin with "v" 

### ISSUE THREAD

**Issue by Ailsa-Wu** [argoproj/argo-cd#6711]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to create an application with OCI-based chart repo(ACR), and my chart version is match `vYYYY.MM.DD-r*`, e.g. `v2021.07.13-r2`.  It would failed because of pull error version `2021.7.13-r3`.  I'm wondering that if Argocd do some format 
 on the version.

```
rpc error: code = Unknown desc = `helm chart pull myregistry.azurecr.io/1/ede/helm/test-longlonglonnameailsa:2021.7.13-r3` failed exit status 1: Error: myregistry.azurecr.io/1/ede/helm/test-longlonglonnameailsa:2021.7.13-r3: not found
```

**To Reproduce**

Add OCI Helm Repository with command `argocd repo add myregistry.azurecr.io --type helm --name myregistry.azurecr.io --enable-oci --username myuser --password mypasswd`

Deploy Helm Application (with below manifest)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    deployID: ""
    deployName: ""
    svcName: test-longlonglonnameailsa
  name: test-longlonglonnameailsa-12345678
  namespace: argocd
spec:
  destination:
    name: uat
    namespace: testns
  ignoreDifferences:
  - group: s4.sap.com
    jsonPointers:
    - /metadata
    kind: Postgres
  - group: s4.sap.com
    jsonPointers:
    - /metadata
    kind: Kafka
  project: eurekauat--1
  revisionHistoryLimit: 30
  source:
    chart: 1/ede/helm/test-longlonglonnameailsa
    helm:
      parameters:
      - name: project
        value: eurekauat
      - name: eureka.envs.ORG_ALIAS
        value: eurekauat
      - name: clusterName
        value: uat
      - name: domain
        value: uat.eurekacloud.io
      - name: nsDomain
        value: uat.eurekacloud.io
      valueFiles:
      - values.production.yaml
      - values.testns.uat.yaml
    repoURL: myregistry.azurecr.io
    targetRevision: v2021.07.13-r3
  syncPolicy:
    automated:
      prune: true
```

**Expected behavior**

The chart can be deployed successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/66725688/125627102-aa7a12dc-254b-4f73-b59b-7a569113d9a9.png)

**Version**

```shell
argocd: v1.8.1+c2547dc.dirty
  BuildDate: 2020-12-10T05:00:12Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.4+28aea3d
  BuildDate: 
  GitCommit: 
  GitTreeState: 
  GoVersion: 
  Compiler: 
  Platform: 
  Ksonnet Version: 
  Kustomize Version: 
  Helm Version: 
  Kubectl Version: 
  Jsonnet Version: 
```

**Logs**

![image](https://user-images.githubusercontent.com/66725688/125628761-d1220407-80bc-41cd-9806-bff0958196ec.png)
