### ISSUE TITLE
Metrics endpoint not reachable through the metrics kubernetes service

### ISSUE THREAD

**Issue by conorfennell** [argoproj/argo-cd#672]
I am using the prometheus operator and scraping is failing against the new `argocd-metrics` service.

This is the configuration for the metrics Kubernetes service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app: argocd-server
```

Notes:
 * Using v0.9.2

* I can successfuly GET the `/metrics` in the argocd-server pod if I do a port-forward:  
`kubectl port-forward argocd-server-789654c5df-2r9hr 8082:8082  --namespace argocd`

* The argocd-metrics kubernetes service has discovered the pod

Here you can see the argocd-metrics endpoint has an entry
```yaml
Name:              argocd-metrics
Namespace:         argocd
Selector:          app=argocd-server
Type:              ClusterIP
IP:                172.20.74.161
Port:              http  8082/TCP
TargetPort:        8082/TCP
Endpoints:         10.137.58.37:8082
Session Affinity:  None
Events:            <none>
```

* When I try this curl within the cluster, I get connection refused . 
`curl argocd-metrics.argocd.svc.cluster.local:8082/metrics`

I am not 100% on how dex works, but could it cause any interferance here? everything else is working great since the upgrade. 
Last step was to export these useful metrics in.
