### ISSUE TITLE
coredns application sync looping

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#6754]
I'm using app of apps to create coredns via helm chart and it is on a sync loop, deleting the deployment and syncing over and over. Any suggestions?

Application yaml after helm template completed
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations.coredns.staging
  namespace: argocd
  labels:
    metaLabel: coredns
    app: coredns
    team: operations
    provider: gcp
    project: development
    cluster: playground-west
    region: us-west1
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      releaseName: staging
      valueFiles:
      - values.yaml
    repoURL: https://xxxx.com/Operations-argocd-applications.git
    targetRevision: HEAD
    path: applications/operations/coredns/staging
  destination:
    name: playground-west
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - PrunePropagationPolicy=foreground
    - ApplyOutOfSyncOnly=true
```

coredns chart.yaml
```
apiVersion: v2
name: coredns
version: 0.0.1
dependencies:
- name: coredns
  version: 1.16.0
  repository: https://coredns.github.io/helm
```

coredns values.yaml
```
coredns:
  autoscaler:
    enabled: true
```

**Comment by rbreeze** [comment]
Could you take a look at the FAQ? If you're still having trouble afterward, feel free to comment again:

https://argoproj.github.io/argo-cd/faq/#why-is-my-application-still-outofsync-immediately-after-a-successful-sync

**Comment by rwong2888** [comment]
I have tried that with replicas, as well as removing my values.yaml to remove autoscaler, as well as putting the health configmap described in
https://argoproj.github.io/argo-cd/operator-manual/health/#argocd-app
The problem is, I am not able to figure out what to put in the ignore differences.
I've determined it is a combination of the configmap, service, and deployment which are going out of sync. I tested by copying the coredns helm chart and removing and adding resources individually.
I also tried modifying helper to add targetport: 53 to the service.

**Comment by rwong2888** [comment]
Any idea @rbreeze ?

**Comment by rbreeze** [comment]
Are you saying you have `ignoreDifferences` configured already, but it's not working? If so, could you paste your `ignoreDifferences` field? It sounds like if the ConfigMap, Service and Deployment are going out of sync you could add those to the `ignoreDifferences` field of your App Spec and it would fix your problem.

Here's a sample for ignoring a deployment with a container called "injected-init-container" (from https://argoproj.github.io/argo-cd/user-guide/diffing/):

```
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .spec.template.spec.initContainers[] | select(.name == "injected-init-container")
```

**Comment by rwong2888** [comment]
I added below to my application, however the out of sync is triggered by configmap, service, and deployment. Nor did below resolve the issue for deployment. I am unable to determine what paths if any that need ignoring.

```
  ignoreDifferences:
  - kind: Deployment
    name: staging-coredns
    namespace: kube-system
    jsonPointers:
    - /spec/replicas
```

**Comment by rwong2888** [comment]
@rbreeze , trying to focus on one manifest to isolate. Ignoring metadata and spec is still failing. Any ideas?

```
ignoreDifferences:
  - kind: Service
    jsonPointers:
      - /metadata
      - /spec
```
