### ISSUE TITLE
ArgoCD UI not showing repository

### ISSUE THREAD

**Issue by sitilge** [argoproj/argo-cd#6795]
**Describe the bug**

I created a new repository

apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@gitlab.com:user/project.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----

The public key of the PKI has been uploaded to Gitlab, and is working. I also tried using url: ssh://git@gitlab.com:user/project.git but it didn't change anything. The UI is completely empty, nothing under Settings/Repositories, so what am I missing here?

**To Reproduce**

Do `kubectl apply -f file.yaml -n argocd`. Then go to Settings/Repositories and notice nothing is there.

**Expected behavior**

The repository is showed in the Web UI.

**Screenshots**

![image](https://user-images.githubusercontent.com/3306642/126764548-640b1cd7-8dca-45cc-abf7-b4cb886c566b.png)

**Comment by igorGevaerd** [comment]
I'm facing the same issue.

The argocd version being used is:
```
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/crds?ref=v2.0.4
- github.com/argoproj/argo-cd/manifests/base?ref=v2.0.4
- github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=v2.0.4
- ingress.yaml

patchesStrategicMerge:
- server.yaml

namespace: argocd
```
```
# server.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        command: [argocd-server, --staticassets, /shared/app, --insecure]

```

The repository manifests is defined like follows:
```
# repository.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-app-test
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
    app.kubernetes.io/part-of: argocd
stringData:
  url: git@git.internal.net:applications/app-test.git
  sshPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    xyz
    ...
    ...
    ...
    -----END RSA PRIVATE KEY-----
---
```

I didn't change anything inside the configmap `argocd-cm`, since after 2.0 the [references to repositories were completely removed](https://argoproj.github.io/argo-cd/operator-manual/argocd-cm.yaml) because it is now deployed as a Secret.
