### ISSUE TITLE
OIDC with http-Keycloak

### ISSUE THREAD

**Issue by Raskosk** [argoproj/argo-cd#6824]
I want to integrate Keycloak as IdentityProvider.
Therefore, I followed the instructions of the official [documentation](https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/). 

Unfortunately, I'm ending up with the response of "invalid return_url"

1. Install Keycloak via kubectl to default-namespace
Keycloak-Deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:14.0.0
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080`
```

Keycloak-Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
```

For ingress, I'm using Consul so keycloak is accessible from `http://keycloak.k8s.example.com`

2. Install ArgoCD via Kubectl according to [Documentation](https://argo-cd.readthedocs.io/en/stable/getting_started/)
For ingress, I'm using Consul so keycloak is accessible from `http://argocd-server.k8s.example.com`

3. Configure ArgoCD following the instructions of the official [documentation](https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/)

4. Ending up with the following:
![image](https://user-images.githubusercontent.com/75483160/127310248-d837baa4-5b04-4536-94b1-8fd3677136fe.png)

5. Try to fix with some less secure keycloak configuration
![image](https://user-images.githubusercontent.com/75483160/127310721-3c2eca4f-9e47-4faa-a307-e1db20dfcaa9.png)

6. Still the same 
![image](https://user-images.githubusercontent.com/75483160/127310248-d837baa4-5b04-4536-94b1-8fd3677136fe.png)

7. ArgoCD Server Logs 
```
time="2021-07-28T10:46:11Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.claims=null grpc.request.content= grpc.service=version.VersionService grpc.start_time="2021-07-28T10:46:11Z" span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.768 span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:11Z" span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.812 span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:11Z" span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.375 span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:11Z" span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.344 span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims=null grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-07-28T10:46:11Z" span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.127 span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.064 span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=application.ApplicationService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.055 span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims=null grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-07-28T10:46:11Z" span.kind=server system=grpc
time="2021-07-28T10:46:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2021-07-28T10:46:11Z" grpc.time_ms=0.27 span.kind=server system=grpc
time="2021-07-28T10:46:12Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims=null grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-07-28T10:46:12Z" span.kind=server system=grpc
time="2021-07-28T10:46:12Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2021-07-28T10:46:12Z" grpc.time_ms=0.149 span.kind=server system=grpc
time="2021-07-28T10:46:12Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:12Z" span.kind=server system=grpc
time="2021-07-28T10:46:12Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-07-28T10:46:12Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-07-28T10:46:12Z" grpc.time_ms=0.452 span.kind=server system=grpc
time="2021-07-28T10:48:13Z" level=info msg="Alloc=10441 TotalAlloc=332622 Sys=73553 NumGC=381 Goroutines=151"
```

8. Logs from keycloak
```
22:04:52,780 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 64) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RealmsResource from Application class org.keycloak.services.resources.KeycloakApplication
22:04:52,781 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 64) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.WelcomeResource from Application class org.keycloak.services.resources.KeycloakApplication
22:04:52,926 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 64) WFLYUT0021: Registered web context: '/auth' for server 'default-server'
22:04:53,084 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 46) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
22:04:53,152 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
22:04:53,155 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) started in 25106ms - Started 692 of 977 services (686 services are lazy, passive or on-demand)
22:04:53,157 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
22:04:53,158 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
```

Due to no activity in the Keycloak-Logs, I assume it's an argocd problem.
Can anybody help?

**Comment by Raskosk** [comment]
Mistake found:

At the official docs, right at 'Configuring ArgoCD OIDC' is the given url pointing to argocd-server.
In my configuration I've given the keycloak url.

My (wrong) configuration:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://keycloak.k8s.example.com
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.k8s.example.com/auth/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
```

Correct configuration:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd-server.k8s.example.com
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.k8s.example.com/auth/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
```
