### ISSUE TITLE
Multiple globalProjects do not work

### ISSUE THREAD

**Issue by dornimaug** [argoproj/argo-cd#6844]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If multiple globalProjects are configured in the argocd-cm ConfigMap as documented here: https://argoproj.github.io/argo-cd/user-guide/projects/#configuring-global-projects-v18 and the first globalProject's labelSelector does not match, no further globalProjects are matched.

**To Reproduce**

Set globalProjects in argocd-cm:
```
data:
  globalProjects: |-
   - projectName: default-x
     labelSelector:
       matchExpressions:
        - key: is-x
          operator: Exists
   - projectName: default-non-x
     labelSelector:
       matchExpressions:
        - key: is-x
          operator: DoesNotExist
```

Create a project "is-x" with label "is-x" set to any value.
Create a project "is-no-x" without the label "is-x".

**Expected behavior**

Project "is-x" should have global project "default-x" AND project "is-no-x" should have global project "default-non-x".

BUT "is-no-x" does *not* have any global projects.

**Version**

```shell
argocd: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:52:31Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:52:31Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0

```

**Logs**

```

```

The fix is trivial: the "break" statement in https://github.com/argoproj/argo-cd/blob/c7738a0cae17ec1175d9e61e6729cc2185a6d7aa/util/argo/argo.go#L589 needs to be a "continue" statement.

I would like to provide a PR including a unit test, but according to https://argo-cd.readthedocs.io/en/stable/developer-guide/contributing/#contributor-license-agreement I need to sign a CLA, but following the link to https://cla-assistant.io/argoproj/argo-cd always results in an error: "There is no CLA to sign for argoproj/argo-cd"

See: https://github.com/dornimaug/argo-cd/tree/fix-multiple-globalprojects
