### ISSUE TITLE
SSO issue with existing OIDC Provider

### ISSUE THREAD

**Issue by cnukwas** [argoproj/argo-cd#6857]
Configured Argo with following OIDC configuration to work with our internal provider. Postman tool returns correct scopes but fails with Argo due to the way /authorize call is made as mentioned below.

OIDC configuration is below per Argo [docs](https://argo-cd-docs.readthedocs.io/en/latest/operator-manual/sso/#existing-oidc-provider)

```
oidcConfig: |
    name: SAFE
    issuer: https://myoidc.provider.com/
    clientID: abc123456sfsfsdfsdf
    clientSecret: sfsfsdffffffffff
    requestedScopes: ["openid", "argo-admin", "GroupA", "GroupB", "GroupC", "GroupCD1"]
    requestedIDTokenClaims:
      sub:
        essential: true
      email:
        essential: true
```
RBAC enforcement YAML with following configuration as per [argocd-rbac.yaml](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-rbac-cm.yaml)

argocd-rbac-cm.yaml scopes data:

`scopes: '[argo-admin, GroupA, GroupB, GroupC, GroupCD1]'`

I see that Argo is making following call with correct scopes but is sending a + sign for delimiting requested scopes string. I believe it's supposed to encode space character as %20 not as a plus sign. Due to this, the APM tokens don't have correct scopes, leading to permission errors for any Argo functions after logging into web UI.

`https://my.oidcprovider.com/authorize?claims=%7B%22id_token%22%3A%7B%22email%22%3A%7B%22essential%22%3Atrue%7D%2C%22sub%22%3A%7B%22essential%22%3Atrue%7D%7D%7D&client_id=asddddddddddddddddddd&redirect_uri=https%3A%2F%2Fopenshift-gitops-server-openshift-gitops.apps.os-dev-test.com%2Fauth%2Fcallback&response_type=code&scope=openid+argo-admin+GroupA+GroupB+GroupC+GroupCD1&state=vexgRhBLqJ`
 

**To Reproduce**

Configure Argo CD to use an existing OIDC provider as per the documentation and notice /authorize call made to the OIDC provider when requesting configured scopes. The call is sending plus signs instead of encoding space characters as %20. This is causing an issue on the provider end and not returning requested scopes.

**Expected behavior**

Return requested scopes, in this case GroupA, GroupB, GroupC and GroupCD1 in the scope.

**Screenshots**

N/A

**Version**

```shell
v2.0.5
```

**Logs**

```
Argo logs and argocd.token cookie token doesn't have requested scopes.
```
