### ISSUE TITLE
Documentation does not state how to escape $ substitution in helm Applications

### ISSUE THREAD

**Issue by andrewm-aero** [argoproj/argo-cd#6878]
**Describe the bug**

In the official docs, the page for Helm notes that variables can be substituted using the $ character, but do not specify how to escape them. The user should not have to dig through the source code for this information. If this is not a supported feature, then the docs should state this very clearly.

**To Reproduce**

See https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#build-environment

**Expected behavior**

Docs should describe how to escape $ characters, or that it isn't possible, it should clearly state so.

**Comment by Jonas18175** [comment]
It's currently a bug in helm-applications, because the go cmd exec interprets it as bash variables and when its undefined it erase the $ and the following text - because it try to set it to var content.
I thought I had created a issue about this in the past, but I don't find this one. I tried to create a fix with a escape lib, but it doesn't work for me. 
A other problem is in Helm Applications to specify annotations without result in a double string.

**Comment by andrewm-aero** [comment]
If that is the case, don't you agree that the docs should have a big red warning somewhere explaining this, and that if such behavior is undesirable, to use 1.8 for the time being?

**Comment by Jonas18175** [comment]
**Yes, because it can be a security risk or results in unexpected behaviour.** But better is to fix that bug.
I work very much with helm application argocd charts, because it is practical, but i think it need more attraction or a rework.
For example supporting types or helm's --set-string - for example for prometheus annotations - I have no chance to set it because it results in "'true'" in yaml. the escaping is in generally very bad. And I hate the flatten yaml structure - why no support for normal helm yaml in helm argocd application like a helm operator do.

**Comment by andrewm-aero** [comment]
I definitely agree that the bug should be fixed, however, the question is how long that will take, and if its more than a few days (And given that your issue has been untouched for months, I suspect it will be quite a bit longer than that), the best thing would be to document it immediately.

As for how to fix it, if I were doing it, I would make a breaking change where there are two fields, 'value' and 'valueExpr', where the first is interpreted literally, and the second does replacement, meaning its opt-in, rather than opt-out.

**Comment by andrewm-aero** [comment]
Actually, something that just occurred to me, if parameters are just interpreted, as-is, by bash, could this be used for shell injection? If so, that seems CVE-worthy.

**Comment by Jonas18175** [comment]
No, its not a CVE - i tested it with a $(data) inside a string and it results in $(data) and not in a date - but its not sure if that is executed or not.

**Comment by mohitsaxenaknoldus** [comment]
I can mention it in the docs. Can I be assigned to this?

**Comment by RomanBats** [comment]
Quite a frustrating issue :)
I tried to use Fluent Bit with Splunk output. It uses "record accessors pattern" to access values in the JSON.
This [record accessors pattern](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/record-accessor) starts with a dollar sign.

**Comment by dmitry-mightydevops** [comment]
Same issue with prometheus-community/prometheus chart.
If you embed alert rules in the values, argocd fails 

```
serverFiles:
          alerting_rules.yml:             
            groups:              
              # ┌──────────────────────────────────────────────────────────────────────────────┐
              # │ ALERT: NODES                                                                 │
              # │                                                                              │
              # └──────────────────────────────────────────────────────────────────────────────┘
              - name: Instances
                rules:                  
                  - alert: InstanceHighCPULoad
                    expr: node_load1 > 3
                    for: 1m
                    labels:
                      severity: warning
                      
                    annotations:
                      description: Docker host is under high load, the avg load 1m is at {{ $value}}.
                        Reported by instance {{ $labels.instance }} of job {{ $labels.job }}.
                      summary: Server under high load
                      type: Server

                  - alert: InstanceOutOfMemory
                    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
                    for: 2m
                    labels:
                      severity: warning
                      
                    annotations:
                      summary: Host out of memory (instance {{ $labels.instance }})
                      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

**Comment by benreynolds-drizly** [comment]
Inability to escape the $ is a pretty significant issue. It's currently blocking us from having ArgoCD manage itself via Helm with SSO due to the way [ArgoCD references secrets containing client ID and secret](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#alternative). 

```yaml
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "3.26.12"
    chart: argo-cd

    helm:
      values: |
        server:

          config:
            admin.enabled: "false"
            url: "https://argocd.ben.dev-dvx.drizly.com"
            dex.config: |
              connectors:
                - type: github
                  id: github
                  name: GitHub
                  config:
                    clientID: $argocd-github-sso:clientID # THIS BREAKS
                    clientSecret: $argocd-github-sso:clientSecret # THIS BREAKS
```
