### ISSUE TITLE
2.1-rc2: controller.repo.server.timeout.seconds not being accepted by engine

### ISSUE THREAD

**Issue by schoki040** [argoproj/argo-cd#6907]
**Describe the bug**
When setting `controller.repo.server.timeout.seconds: "180"` the app-controller will not accept the value

**To Reproduce**
Set the following option in your params-cm and restart your controller pods
```yaml 
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  controller.repo.server.timeout.seconds: "180"
```

**Expected behavior**

It ups the timeout to 180 seconds

**Screenshots**
 no

**Version**
```shell
argocd: v2.1.0-rc2+b067879
  BuildDate: 2021-08-03T17:08:07Z
  GitCommit: b067879892d3586bb2392dfc2f0932e9bde231dd
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
From inside the container
```shell
argocd@argocd-application-controller-0:~$ printenv | grep -i seconds
ARGOCD_APPLICATION_CONTROLLER_REPO_SERVER_TIMEOUT_SECONDS=180
```
Container level
```log
time="2021-08-04T14:53:22Z" level=warning msg="Could not parse '180' as a number from environment ARGOCD_APPLICATION_CONTROLLER_REPO_SERVER_TIMEOUT_SECONDS"
```
