### ISSUE TITLE
Health check doesn't work when using `resource.customizations.health.*`

### ISSUE THREAD

**Issue by batthebee** [argoproj/argo-cd#6909]
Version 2.0.4

I am implementing a health check for the pulumi-operator.

My first try was the following config map: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations.health.pulumi.com_Stack: |
    hs = {}
    hs.status = "Progressing"
    hs.message = "Waiting for update stack."
    return hs
```

This does not work, the deployment is marked as "Healthy".

After that I tried the following:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations: |
    pulumi.com/Stack:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = "Waiting for update stack."
          return hs
```

Now, as expected, the deployment is marked as "Progressing".
