### ISSUE TITLE
basehref not set correctly on v2.1.0-rc2

### ISSUE THREAD

**Issue by Brice187** [argoproj/argo-cd#6919]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In ArgoCD 2.0.1 it was possible to reach the GUI on https://my-corp-url.org/argocd/, if you run

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
...
      containers:
        - image: argoproj/argocd:v2.0.1
        - command:
            - argocd-server
            - --staticassets
            - /shared/app
            - --insecure
            - --basehref
            - /argocd/
```

In ArgoCD v2.1.0-rc2 the basehref is ignored, even if set in the new ConfigMap

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  ## Server properties
  # Run server without TLS
  server.insecure: "true"
  # Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from / (default "/")
  server.basehref: "/argocd/"
```

The resulting html of the above settings:

```html
lars@pinki:~$ curl https://my-corp-url.org/argocd/
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Argo CD</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='icon' type='image/png' href='assets/favicon/favicon-32x32.png' sizes='32x32'/>
    <link rel='icon' type='image/png' href='assets/favicon/favicon-16x16.png' sizes='16x16'/>
<link href="fonts.css" rel="stylesheet"></head>

<body>
    <noscript>
        <p>
        Your browser does not support JavaScript. Please enable JavaScript to view the site. 
        Alternatively, Argo CD can be used with the <a href="https://argoproj.github.io/argo-cd/cli_installation/">Argo CD CLI</a>.
        </p>
    </noscript>
    <div id="app"></div>
<script type="text/javascript" src="main.bb1d24b8bcb8413f4ef7.js"></script></body>

</html>
```
in the `<head>`-section the base href is still set to `/`

**To Reproduce**

Try to use a subpath with vanilla installation instruction and the ingress mentioned above

**Expected behavior**

Set basehref to desired value 

**Screenshots**

![argocd](https://user-images.githubusercontent.com/2021699/128514737-1204469c-59f3-4777-8dae-a73af4351e10.png)
**Version**

```shell
Paste the output from `argocd version` here.
```
> Bug is not about argocd cli tool

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
@mayzhang2000 can you take a look please?

**Comment by mayzhang2000** [comment]
@Brice187 wonder if you could please post your deployment manifest that you used with ArgoCD v2.1.0-rc2?

**Comment by Brice187** [comment]
@alexmt: 

Today i tried out `argoproj/argocd:v2.1.0`

Now basehref is basically working, but I still get a blank screen an following error in Chrome DevTools

```
Uncaught SyntaxError: Unexpected token l in JSON at position 0
    at JSON.parse (<anonymous>)
    at Module.<anonymous> (main.e889df4a8fc69d005b54.js:54)
    at o (main.e889df4a8fc69d005b54.js:1)
    at Module.<anonymous> (main.e889df4a8fc69d005b54.js:359)
    at Module.<anonymous> (main.e889df4a8fc69d005b54.js:359)
    at o (main.e889df4a8fc69d005b54.js:1)
    at main.e889df4a8fc69d005b54.js:1
    at main.e889df4a8fc69d005b54.js:1Uncaught SyntaxError: Unexpected token l in JSON at position 0
    at JSON.parse (<anonymous>)
    at Module.<anonymous> (main.e889df4a8fc69d005b54.js:54)
    at o (main.e889df4a8fc69d005b54.js:1)
    at Module.<anonymous> (main.e889df4a8fc69d005b54.js:359)
    at Module.<anonymous> (main.e889df4a8fc69d005b54.js:359)
    at o (main.e889df4a8fc69d005b54.js:1)
    at main.e889df4a8fc69d005b54.js:1
    at main.e889df4a8fc69d005b54.js:1
```

Could you pls have a look again?

**Comment by alexmt** [comment]
Hello @Brice187 ,

I've tried to reproduce the issue with the following steps. Run argocd server  v2.1.0 with ` --basehref /argocd/` and nginx reverse proxy that drops `/argocd/` path:

argocd-server:

```yaml
      containers:
      - args:
        - --insecure
        - --basehref
        - /argocd/
        command:
        - argocd-server
```

nginx
```
events {
  worker_connections  1024;
}

http {
    server {
        listen       9000;
        location /argocd/ {
            rewrite /argocd/(.*) /$1  break;
            proxy_pass http://localhost:8080;
            proxy_no_cache 1;
            proxy_cache_bypass 1;
        }

        # buffering should be disabled for api/v1/stream/applications to support chunked response
        proxy_buffering off;
    }
}

```

Cannot reproduce the error. Can you confirm that you have a proxy in front of Argo CD that overrides `/argocd/` ?

**Comment by Brice187** [comment]
Sorry for wasting your time, the fault was on my side :)

**Comment by alexmt** [comment]
No problem :) thanks for confirming!

**Comment by danmx** [comment]
it seems I have the same issue with v2.1.6 both while proxying using Traefik 2.4.8 and while using port forwarding.
![Screenshot from 2021-10-31 15-30-37](https://user-images.githubusercontent.com/11769367/139588519-93b21826-069a-4ebe-a280-6b3006fa241d.png)

Kustomize ConfigMap generator:

```yaml
configMapGenerator:
  - name: argocd-cmd-params-cm
    namespace: argocd
    behavior: merge
    literals:
      - server.insecure=true
      - server.basehref=/argocd/
```
