### ISSUE TITLE
It is impossible to override an ingress annotation with helm.

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-cd#6940]
We try to override a chart helm by modifying an ingress annotation.

```yaml
helm:
   parameters:
     - name: ingress.annotations.cert-manager.io/cluster-issuer
        value: "dummy"
```

When we try with the above syntax we have an error since helm can not template.

For this to work with a helm template, we need to escape the point of the last block of our annotation.

```bash
helm template . --set ingress.annotations.cert-manager\\.io/cluster-issuer=dummy
```

But when we add the double escape directly in our yaml, argocd interprets it as a new annotation which is not the desired behavior

```yaml
helm:
   parameters:
     - name: "ingress.annotations.cert-manager\\.io/cluster-issuer"
        value: "dummy"
```

![Screenshot 2021-08-10 at 14 15 44](https://user-images.githubusercontent.com/76174192/128865292-8f5e014d-c73e-435f-9805-dfdf5877e861.png)

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Version**

```shell
quay.io/argoproj/argocd:v2.0.3
```

**Comment by iusergii** [comment]
Also looking for a proper workaround for this.

**Comment by iusergii** [comment]
Escaping dot helps:
```yml
helm:
   parameters:
     - name: ingress.annotations.cert-manager\.io/cluster-issuer
       value: "dummy"
```
