### ISSUE TITLE
label causing sync loop

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#6958]
tried deploying an application with the helm chart and it sync loops
https://github.com/coredns/helm/tree/master/stable/coredns

the label `kubernetes.io/cluster-service: "true"` in configmap, deployment, and service is causing the application to go out of sync.

when I remove it manually it works.

I tried adding ignore to the application spec, but it did not work.
```
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: staging-coredns
    namespace: kube-system
    jsonPointers:
    - /metadata/labels
  - group: apps
    kind: ConfigMap
    name: staging-coredns
    namespace: kube-system
    jsonPointers:
    - /metadata/labels
  - group: apps
    kind: Service
    name: staging-coredns
    namespace: kube-system
    jsonPointers:
    - /metadata/labels
```

**Comment by rwong2888** [comment]
@alexmt below is still failing

```
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: staging-coredns
    namespace: kube-system
    jsonPointers:
    - /metadata/labels
  - group: ""
    kind: ConfigMap
    name: staging-coredns
    namespace: kube-system
    jsonPointers:
    - /metadata/labels
  - group: ""
    kind: Service
    name: staging-coredns
    namespace: kube-system
    jsonPointers:
    - /metadata/labels
```


syncing

![image](https://user-images.githubusercontent.com/61470342/129100985-efaa45df-8fc1-47a7-b1b3-94050b8ec2f1.png)


out of sync

![image](https://user-images.githubusercontent.com/61470342/129100812-4e30b71b-b3bd-4a55-8612-878557afac14.png)

**Comment by rwong2888** [comment]
Found a workaround with kustomized-helm

argocd-cm
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |-
    - name: kustomized-helm
      init:
        command: ["sh", "-c"]
        args: ["helm repo add ${helm_dependency_name} ${helm_dependency_repo} && helm dependency update ${helm_base}"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${helm_dependency_name} ${helm_base} ${helm_args} > ${helm_base}/all.yaml && kustomize build"]
```

application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: main
    path: applications/coredns
    plugin:
      name: kustomized-helm
      env:
      - name: helm_args
        value: -f base/values.yaml
      - name: helm_dependency_name
        value: coredns
      - name: helm_dependency_repo
        value: https://coredns.github.io/helm
      - name: helm_base
        value: base
  destination:
    name: {{ .Values.destinationName }}
    namespace: kube-system
```

applications/coredns/base/Chart.yaml
```
apiVersion: v2
name: coredns
version: 0.0.1
dependencies:
- name: coredns
  version: 1.16.3
  repository: https://coredns.github.io/helm
```

applications/coredns/overlays/remove-label.yaml
```
- op: remove
  path: "/metadata/labels/kubernetes.io~1cluster-service"
```

applications/coredns/kustomization.yaml
```
kind: Kustomization

bases:
- base/all.yaml

patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: coredns-coredns
  path: overlays/remove-label.yaml
- target:
    version: v1
    kind: Deployment
    name: coredns-coredns
  path: overlays/remove-label.yaml
- target:
    version: v1
    kind: Service
    name: coredns-coredns
  path: overlays/remove-label.yaml

namespace: kube-system
```
