### ISSUE TITLE
IgnoreExtraneous not working with mutated secrets

### ISSUE THREAD

**Issue by sedadas** [argoproj/argo-cd#7011]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When deploying applications that use the [Vault mutating webhook from banzai cloud](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/) for secrets mutation, we get the issue that the application secrets are always listed as out-of-sync even though IgnoreExtraneous and Prune=false are specified in the annotations of the secret [as per the documentation](https://argoproj.github.io/argo-cd/user-guide/compare-options/). 

The webhook works using references to secrets in Hashicorp Vault. It resolves the path to a secret and injects it in a Kubernetes resource. For example, the following manifest is present in the repo of the application:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-path: "kubernetes"
stringData:
  .very_secure: vault:secret/test#example_secret 
```

The mutating webhook will get the secret with key `example_secret` at the path `secret/test` from Vault and inject it in the Kubernetes resource.

Argo CD detects this and marks the application as out-of-sync, as the resource differs from the manifest in the repo. This is expected as a behaviour. However, if we add the `IgnoreExtraneous` annotation to the secret from above, the secret and the application are still getting listed as out-of-sync, which was not expected. We were able to reproduce this on both vanilla Kubernetes with an upstream Argo CD install and OpenShift with the GitOps Operator from RedHat.

We also considered the solution, suggested in #5178, but thus, as the first comment says, the references will not be synced by Argo CD, producing inconsistencies between the is- and should-be state.
 
**To Reproduce**

1. Have a running Argo CD
2. Have a running Hashicorp Vault instance
3. Have a mutating webhook installed and configured in Kubernetes
4. Create an application containing a secret with a manifest, similar to the one from above
5. Make Argo CD sync the application
6. Observe the behaviour
7. Add the `IgnoreExtraneous` and `Prune=false` annotations
8. Observe the behaviour

**Expected behavior**

The secret is listed as out-of-sync but does not affect the overall application sync status.

**Screenshots**
N/A

**Version**

```shell
argocd: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
N/A

**Comment by Elyytscha** [comment]
yep i can reproduce with

```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.apps.clustername.domain.com"
    vault.security.banzaicloud.io/vault-role: "ocp-int"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
stringData:
  password: vault:devops/data/int/awx#admin_password
```
and application is still shown as out of sync in the argo cd webui and is constantly syncing
