### ISSUE TITLE
delete application without cascade using kubectl

### ISSUE THREAD

**Issue by vijay-dcrust** [argoproj/argo-cd#7033]
I am following this document to delete application using kubectl without cascading effect on underlying resources.

https://argoproj.github.io/argo-cd/user-guide/app_deletion/#deletion-using-kubectl

But it is deleting my resources also which are created by argocd application.

I tried removing finalizer also before deleting the application without any luck.

**Comment by chetan-rns** [comment]
@vijay-dcrust It is working as expected for me. How was the finalizer added? AFAIK Argo CD doesn't add the finalizer when the app is created. It gets added when the app is deleted either from CLI or UI with cascade enabled.

**Comment by iam-veeramalla** [comment]
Hi @vijay-dcrust , How did you remove the finalizer ? Can you please mask the secrets(if any) and paste the application file here ?

**Comment by vijay-dcrust** [comment]
Hi @chetan-rns I am adding finalizer in application manifest. So when i create it is automatically added. Are you saying that i should create application without adding finalizer. Is that the default way.

Below is my app definition.

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela-ops-resources-argo-events-HOSTNAME
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-01
  source:
    repoURL: git@gitlab.net:my-project/git-repo-name.git
    targetRevision: master
    path: deployments/clusters/kubevela/resources/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    automated:
      selfHeal: true


@iam-veeramalla  I am removing finalizer using below command

kubectl patch app kubevela-ops-resources-argo-events -p="[{'op': 'remove', 'path': '/metadata/finalizers'}]" --type=json  -n argocd

**Comment by wtam2018** [comment]
@vijay-dcrust Please report back if non-cacade deletion is achieved when no finalizer `resources-finalizer.argocd.argoproj.io` is  added which is what the doc is suggesting.

**Comment by vijay-dcrust** [comment]
Hi @wtam2018  the finalizer resources-finalizer.argocd.argoproj.io is added automatically by application controller even if i am not specifying it in the manifest. Is there a way to stop it. I am using applicationset to create application.

**Comment by vutkin** [comment]
@vijay-dcrust same behaviour on 2.1.2.

**Comment by nneram** [comment]
Hi @vijay-dcrust, I got the same problem with this example with no `finalizer`: 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stacks
  namespace: argocd
spec:
  destination:
    namespace: capm3-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: repoURL
    targetRevision: HEAD
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
```

When I remove a file in the Git (custom resource) which deploys other resources **they are also deleted by argocd**. I expected that it didn't because the resources deleted are handle by an operator and argocd make conflict with it. 
_Notice_ that the expected behavior happen when I used to delete the CR with the dashboard: `delete --> Non-cascading (Orphan) Delete`

At present, I have to use basic `kubectl create -f cr` for this resource because of this bug. I would really appreciate a correction of it or a walkaround. So far I have found nothing
