### ISSUE TITLE
Install manifests RBAC are missing event list permissions

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#704]
argocd-server-clusterrole needs:
```
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
```
