### ISSUE TITLE
ArgoCD upgrade v2.0.5 to v2.1.0 cause argocd-repo-server CrashLoopBackOff

### ISSUE THREAD

**Issue by angelosanramon** [argoproj/argo-cd#7044]
I am trying to upgrade argocd from v2.0.5 to v2.10. The argo-repo-server is showing CrashLoopBackOff error. I am getting the following status when running `kubectl get pod -n argo-cd argocd-repo-server-5b8db4f6d-svx5k -o yaml`

```
  containerStatuses:
  - containerID: docker://190aa1c55678a910aa2d33456c09d624693324c8a388bdc3ebf19d4e7362f26f
    image: quay.io/argoproj/argocd:v2.1.0
    imageID: docker-pullable://quay.io/argoproj/argocd@sha256:544f0cd334c7418526e56497308c5d10b4f942237929004c3ac2360bb2a337a1
    lastState:
      terminated:
        containerID: docker://190aa1c55678a910aa2d33456c09d624693324c8a388bdc3ebf19d4e7362f26f
        exitCode: 127
        finishedAt: "2021-08-21T00:38:07Z"
        message: 'OCI runtime create failed: container_linux.go:380: starting container
          process caused: exec: "uid_entrypoint.sh": executable file not found in
          $PATH: unknown'
        reason: ContainerCannotRun
        startedAt: "2021-08-21T00:38:07Z"
```
