### ISSUE TITLE
Can't seem to use a plugin to extend argocd when using Helm

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-cd#7048]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have a plugin that takes the output of `helm template` and performs string interpolation based on set values. My plugin setup is this:
```
    - name: helm-argocd-vault-replacer
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE $ARGOCD_APP_NAME . | argocd-vault-replacer"]
```

Until Argocd 2.1, this worked most of the time as it seems that whatever magic background Helm work that argocd did also ran on the repo server where my plugin resides. Since argocd 2.1, this fails 100% of the time with the error:
```
rpc error: code = Unknown desc = `/bin/sh -c helm dependency build` failed exit status 1: Error: no cached repository for helm-manager-a3d71d79da3a7e97fc44127f373aa765c1b71499cb48cdf46a0c10608bd437bc found. (try 'helm repo update'): open /home/argocd/.cache/helm/repository/helm-manager-a3d71d79da3a7e97fc44127f373aa765c1b71499cb48cdf46a0c10608bd437bc-index.yaml: no such file or directory
```

The issue seems to be that `helm repo add` is skipped by argocd on the repo server nodes, so the cache cannot be found and therefore no helm plugin will ever work?

**To Reproduce**

You can reproduce this without a plugin binary.

Create a plugin config like so:
```
    - name: helm-example
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE $ARGOCD_APP_NAME . | cut -d' ' -f2"]
```
Apply this plugin to a helm-based argocd application.

**Expected behavior**

I should be able to push helm template commands to stdout so that plugins can interact with them

**Version**

```shell
argocd: v2.1.0+d0b2d55
  BuildDate: 2021-08-20T05:30:54Z
  GitCommit: d0b2d55e3fb7fe8b17385d6687886de41651f31b
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
```shell
argocd-repo-server time="2021-08-23T06:15:25Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): `/bin/sh -c helm dependency build` failed exit status 1: Error: no cached repository for helm-manager-a3d71d79da3a7e97fc44127f373aa765c1b71499cb48cdf46a0c10608bd437bc found. (try 'helm repo update'): open /home/argoc
d/.cache/helm/repository/helm-manager-a3d71d79da3a7e97fc44127f373aa765c1b71499cb48cdf46a0c10608bd437bc-index.yaml: no such file or directory" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2021-08-23T06:16:25Z" grpc.service=repository.RepoServerService grpc.start_time="2021-08-23T06:15:25Z" grpc.time_ms=143.545 span.kind=server system=gr
pc
```
