### ISSUE TITLE
Doc: Missing `type: helm` in repo-creds example

### ISSUE THREAD

**Issue by romachalm** [argoproj/argo-cd#7074]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have used the new `repo-creds` secret to manage helm and dependencies deployment. Authentication to main helm chart repo is managed with `repository` secret, and authentication to dependencies repositories is managed with `repo-creds` secret. 

The examples https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-repositories.yaml show how to configure private helm repo, but not https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-repo-creds.yaml

It appears from the code, the `repo-creds` for helm charts repo need the `type`
https://github.com/argoproj/argo-cd/blob/57abbf95ed160c88b2634ec4d37df9555cc74fb3/util/db/repository_legacy.go#L244

So the secret should something like : 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-xxx-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  password: xxx=
  username: xxx==
stringData:
  url: https://registry.xxx.io
  type: helm
```

**To Reproduce**

n/a
Related to doc

**Expected behavior**

The specific helm configuration, ie the required `helm` type, should be documented 

**Screenshots**

n/a

**Version**

Doc from 
```
Commit a80656d345ca7e83d20900a04cd59c52b84f2566
```

argocd
```json
{
    "Version": "v2.1.0+d0b2d55",
    "BuildDate": "2021-08-20T05:30:54Z",
    "GitCommit": "d0b2d55e3fb7fe8b17385d6687886de41651f31b",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

n/a
