### ISSUE TITLE
helm dependency build failed exit status 1: Error: no cached repository for helm-manager

### ISSUE THREAD

**Issue by tuananh** [argoproj/argo-cd#7076]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: no cached repository for helm-manager-dfdd58bd596a1776c810feb868ee24fb6b533feaebc50ca3e1ea41966786a0b9 found. (try 'helm repo update'): open /tmp/helm938911747/cache/helm/repository/helm-manager-dfdd58bd596a1776c810feb868ee24fb6b533feaebc50ca3e1ea41966786a0b9-index.yaml: no such file or directory
```

**To Reproduce**

it's the same as helm-dependency example but i use private helm repo
I added the helm repo and it shows as successful in the webui 

the app manifest

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=username/hello-nodejs:1.x
    argocd-image-updater.argoproj.io/myimage.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitlab-creds
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/myimage.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'gitlab path'
    path: app-nodejs
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-demo
  syncPolicy:
    automated: {}
  
```

**Expected behavior**

the app to be build as normal

**Screenshots**

**Version**

```shell
argocd version
argocd: v2.1.0+d0b2d55
  BuildDate: 2021-08-20T05:33:25Z
  GitCommit: d0b2d55e3fb7fe8b17385d6687886de41651f31b
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.5+unknown
  BuildDate: 2021-07-28T02:44:47Z
  GitTreeState: clean
  GoVersion: go1.16.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: unknown 1970-01-01T00:00:00Z
  Helm Version: v3.5.0+6.el8+g77fb4bd
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```
Paste any relevant application logs here.
```
