### ISSUE TITLE
Environment variables substitution in spec.source.helm.parameters

### ISSUE THREAD

**Issue by guillaume-roland-cd** [argoproj/argo-cd#7106]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Parameters (_spec.source.helm.parameters_) that look like environment variables are replaced by an empty string
Might be related to https://github.com/argoproj/argo-cd/pull/6097

**To Reproduce**
Create the following application:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: daemonset.filebeatConfig.filebeat\.yml
        value: |
          filebeat.inputs:
          - type: container
            paths:
              - /var/log/containers/*.log
            processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"

          output.elasticsearch:
            host: '${NODE_NAME}'
            hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'

    repoURL: https://helm.elastic.co
    targetRevision: 7.14.0
    chart: filebeat
```
source from: https://github.com/elastic/helm-charts/blob/master/filebeat/values.yaml#L27

filebeat.yml is showing as:
```yaml
apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: 
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
 
    output.elasticsearch:
      host: ''
      hosts: ''
kind: ConfigMap
metadata:
  labels:
    app: filebeat-filebeat
    app.kubernetes.io/instance: filebeat
    chart: filebeat-7.14.0
    heritage: Helm
    release: filebeat
  name: filebeat-filebeat-daemonset-config
  namespace: default
```

**Expected behavior**
The filebeat.yml file should stay as declared (that was the behavior before argocd version 2).

```yaml
apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
 
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
kind: ConfigMap
metadata:
  labels:
    app: filebeat-filebeat
    app.kubernetes.io/instance: filebeat
    chart: filebeat-7.14.0
    heritage: Helm
    release: filebeat
  name: filebeat-filebeat-daemonset-config
  namespace: default
```

**Screenshots**
![image](https://user-images.githubusercontent.com/52173256/131172262-4100e936-9706-4911-8880-ff5b7c39634d.png)

**Version**

```shell
argocd: v2.0.5+4c94d88.dirty
  BuildDate: 2021-07-23T05:09:14Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: dirty
  GoVersion: go1.16.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.0+d0b2d55
```

**Comment by joke** [comment]
I'm having the same problem with version 2.1.1

**Comment by guillaume-roland-cd** [comment]
When I escape the string that are interpreted as env. variable, it make ArgoCD work the same way than before.

Application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: daemonset.filebeatConfig.filebeat\.yml
        value: |
          filebeat.inputs:
          - type: container
            paths:
              - /var/log/containers/*.log
            processors:
            - add_kubernetes_metadata:
                host: $\{NODE_NAME}
                matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"

          output.elasticsearch:
            host: '$\{NODE_NAME}'
            hosts: '$\{ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'

    repoURL: https://helm.elastic.co
    targetRevision: 7.14.0
    chart: filebeat
```

Desired manifest:
```
apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
kind: ConfigMap
metadata:
  labels:
    app: filebeat-filebeat
    app.kubernetes.io/instance: filebeat
    chart: filebeat-7.14.0
    heritage: Helm
    release: filebeat
  name: filebeat-filebeat-daemonset-config
  namespace: default
```
