### ISSUE TITLE
argocd-redis role is missing in install.yaml since ArgoCD 2.0 (non-HA)

### ISSUE THREAD

**Issue by zwilling79** [argoproj/argo-cd#7107]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Since ArgoCD 2.1.0 the `argocd-redis` role is missing in `manifests/install.yaml` but is still referenced in the corresponding role binding. The role exists in `manifests/ha/install.yaml` but differs from the `argocd-redis` role in `manifests/install.yaml` from earlier ArgoCD releases (pre 2.1.0).

**To Reproduce**

* Open <https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml>
* Search for the `argocd-redis` role

**Expected behavior**

`argocd-redis` role is included. In ArgoCD 2.0.5 the role was defined as follows:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
  name: argocd-redis
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
```

In ArgoCD 2.1.x the role in the `manifest/ha/install.yaml` is defined as follows:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: argocd-redis-ha
    app.kubernetes.io/part-of: argocd
  name: argocd-redis-ha
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
```

**Comment by jannfis** [comment]
This change was done as part of cleanup in https://github.com/argoproj/argo-cd/pull/5863

Can you please elaborate on the error you are seeing without this role?

**Comment by zwilling79** [comment]
I wanted to update my ArgoCD instance from 2.0.5 to 2.1.1 and have seen this as a diff. Furthermore, I was confused why the `argocd-redis` role is still referenced in the `argocd-redis` RoleBinding resource. The update had no issues (the role still exists in the cluster/namespace). Also an installation into an empty namespace didn't show any errors. So it seems that Kubernetes can handle this situation.

I guess that in this case the `argocd-redis` RoleBinding could also be removed and in addition to that even the `argocd-redis` service account?

**Comment by zwilling79** [comment]
What also confuses me, why is the `argocd-redis-ha` role still included in `manifest/ha/install.yaml`?

**Comment by Reamer** [comment]
> Also an installation into an empty namespace didn't show any errors. So it seems that Kubernetes can handle this situation.

If I delete the `argocd-redis` role, the redis pod does not start in OKD/Openshift 4.7
```
pods "argocd-redis-9c7c8f86-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.runAsUser: Invalid value: 999: must be in the ranges: [1000690000, 1000699999]]
```

I use this workaround in my `kustomization.yml`
```
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: argocd-redis
  patch: |
    - op: "remove"
      path: /spec/template/spec/securityContext/runAsUser
```
