### ISSUE TITLE
How to add an OCI helm repository in declarative mode

### ISSUE THREAD

**Issue by raphink** [argoproj/argo-cd#7121]
**Describe the bug**

It doesn't seem possible to add an OCI helm repository using a repo cred secret.

**To Reproduce**

I've created a secret like this:

```yaml
apiVersion: v1
data:
  enableOCI: true
  name: myrepo.example.com
  password: somepassword
  type: helm
  url: myrepo.example.com
  username: someuser
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: argocd-repo-test-helm
  namespace: argocd
type: Opaque
```

When trying to deploy a helm chart using the `myrepo.example.com` OCI repository, it fails with:

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add myrepo.example.com https://myrepo.example.com` failed exit status 1: Error: looks like "https://myrepo.example.com" is not a valid chart repository or cannot be reached: failed to fetch https://myrepo.example.com/index.yaml : 404 Not Found
```

which seems to hint that the `enableOCI` parameter is not understood. I couldn't find anything in the docs on how to set this up with Kubernetes objects.

**Expected behavior**

The repo should be added with `helm registry login` instead of `helm repo add`.

**Version**

v2.1.1+aab9542

**Comment by rgeraskin** [comment]
Maybe it is related to #6062 See #6994 also

Btw the manifest you provided is not correct: the data section should be base64 encoded. Or use stringData instead

**Comment by AustinSmart** [comment]
@raphink is `myrepo.example.com` the full _repository_ url?

The error message you are receiving indicates you are missing the repository subpath, as `index.yaml` is generally never aviable at the root of a _registry_. Generally an OCI repository will have a subpath.

EX: `myrepo.example.com/my-oci-charts`

I'm able to add an OCI repository declaratively on v2.1.2

```
apiVersion: v1
stringData:
  enableOCI: true
  name: my-oci-charts
  password: password
  type: helm
  url: myrepo.example.com/my-oci-charts
  username: username
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
```

`enableOCI` is picked up from the secret [here](https://github.com/argoproj/argo-cd/blob/36ab4dadda53a1778f16931b1e30ca741239798a/util/db/repository_secrets.go#L299-L303)

**Comment by rogfut** [comment]
In my experience, this error that you got happens when argocd tries to connect to a non-OCI Helm repo.  

`rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add myrepo.example.com https://myrepo.example.com` failed exit status 1: Error: looks like "https://myrepo.example.com" is not a valid chart repository or cannot be reached: failed to fetch https://myrepo.example.com/index.yaml : 404 Not Found`

I came to the same solution as Austin posted above, it works for me in 2.1.2.

**Comment by raphink** [comment]
Thanks, it works with the full path. Maybe there should be some doc about this?

**Comment by rgeraskin** [comment]
I still have the same troubles with my private OCI helm repo in argocd 2.1.2. 

I'm using this config. Just like @AustinSmart one
```
apiVersion: v1
stringData:
  enableOCI: "true"
  name: my-oci-charts
  password: token-password
  type: helm
  url: registry.gitlab.com/asdasd/charts
  username: token-name
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: my-oci-charts
```

Notice quoted `true` because without quotes it fails on validation. And extended metadata sections. But it makes no big difference anyway.

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm repo add oci://registry.gitlab.com/asdasd/charts oci://registry.gitlab.com/asdasd/charts` failed exit status 1: Error: looks like "oci://registry.gitlab.com/asdasd/charts" is not a valid chart repository or cannot be reached: tag explicitly required
```


I can't login inside argocd-repo-server container also (see #7144 and #7162):
```
argocd@argocd-repo-server-84f4b95796-ndpt2:~$ export HELM_EXPERIMENTAL_OCI=1
argocd@argocd-repo-server-84f4b95796-ndpt2:~$ helm registry login -u token-name -p token-password registry.gitlab.com/asdasd/charts
WARNING: Using --password via the CLI is insecure. Use --password-stdin.
Error: mkdir /home/argocd/.config/helm: read-only file system
```

Using Argocd v2.2.0+183d729 I have no `read-only file system` error, but `is not a valid chart repository` error still persists.

How can you get it working?)

**Comment by raphink** [comment]
I don't know if it makes a difference, but in my case, the URL had a final `/`, both in the Secret and in the Application source.

**Comment by AustinSmart** [comment]
@rgeraskin are you using the OCI repo directly, or as a subchart dependency? The latter is currently broken in 2.1.2.

**Comment by rgeraskin** [comment]
@AustinSmart oh you are right, it is because I use helm OCI subchart. Using OCI repo directly works fine, thanks!

@raphink it's funny but in my case, it works only without trailing `/` in the Secret =)

**Comment by artemkozlenkov** [comment]
```
$: argocd repo add -h| grep oci
  argocd repo add helm-oci-registry.cn-zhangjiakou.cr.aliyuncs.com --type helm --name stable --enable-oci --username test --password test
      --enable-oci                              enable helm-oci (Helm OCI-Based Repository)
```

**Comment by prein** [comment]
Getting 401 as well with the yaml as in previous comments. Similar error in logs:
```
"error testing repository connectivity: `helm registry login <REDACTED>.dkr.ecr.us-east-1.amazonaws.com/helm-charts --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin.\nError: login attempt to https://<REDACTED>.dkr.ecr.us-east-1.amazonaws.com/v2/ failed with status: 401 Unauthorized"
```

Did anyone try, if possible, using some form of short lived token auth or assumed role?

**Comment by tuananh** [comment]
It works so this issue should close now.

Here's how you do it with ECR for example.

```yaml
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  enableOCI: "true"
  user: "xxx"
  password: "xxx"
  url: xxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/charts # need full path here, not just base domain
  type: helm
```
