### ISSUE TITLE
Selective prune

### ISSUE THREAD

**Issue by magmax** [argoproj/argo-cd#7141]
# Summary

"Prune" option might be dangerous, but maybe it can be harmless if it can be selective.

# Motivation

I'm scary of enabling "Prune" option for everything, but if I could use a jq query to select what can be pruned it will be enabled safely. This way a very important resource will remain untouch but a less important one (such a grafana dashboard configmap) can be pruned.

# Proposal

Adding a new field to the Application CRD to match `spec.syncPolicy.syncOptions.pruneRequirements`, with an array of objects like `ignoreDifferences` object:
```
                    group:
                      type: string
                    jqPathExpressions:
                      items:
                        type: string
                      type: array
                    jsonPointers:
                      items:
                        type: string
                      type: array
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
```

Maybe even the `ignoreDifferences` functions can be reused.
