### ISSUE TITLE
helm dependency build is failing with subchart

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#7144]
Error
```
rpc error: code = Unknown desc = `sh -c helm dependency build` failed exit status 1: Error: no cached repository for helm-manager-ebe10bb4e257360e3453a37c457759ba554bc3a2fd86e79d6f93e4d119b0e1e2 found. (try 'helm repo update'): open /home/argocd/.cache/helm/repository/helm-manager-ebe10bb4e257360e3453a37c457759ba554bc3a2fd86e79d6f93e4d119b0e1e2-index.yaml: no such file or directory
```

Chart.yaml
```
apiVersion: v2
name: cert-manager
version: 0.0.1
dependencies:
- name: cert-manager
  version: v1.4.0
  repository: https://charts.jetstack.io
```

Plugin
```
  configManagementPlugins: |-
    - name: argocd-vault-plugin-helm
      init:
        command: ["sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
```

Versions
```
argocd@argocd-server-7d859b554f-kl9m4:~$ helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
argocd@argocd-server-7d859b554f-kl9m4:~$ argocd version
argocd: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

https://www.gitmemory.com/issue/unbroken-dome/gradle-helm-plugin/102/850499759

**Comment by rwong2888** [comment]
Had to remove .gitignore which contained below. Seems repo server will take the gitignore into account
```
charts
Chart.lock
```

Getting new error
```
rpc error: code = Unknown desc = `sh -c helm dependency build` failed exit status 1: Error: no repository definition for https://charts.jetstack.io. Please add the missing repos via 'helm repo add'
```

Related to:
https://github.com/argoproj/argo-cd/issues/3280
https://github.com/IBM/argocd-vault-plugin/issues/190
https://github.com/IBM/argocd-vault-plugin/issues/175

Changing ```helm dependency build``` to ```helm dependency update``` did not work

**Comment by rwong2888** [comment]
https://github.com/IBM/argocd-vault-plugin/issues/175#issuecomment-892888255

>Seems like this may be a workaround.. Instead, you can add those repos in your init script.. Something like helm repo add https://charts.omegion.dev && helm dependency build. You could also vendor the helm dependencies.

**Comment by rwong2888** [comment]
plugin
```
  configManagementPlugins: |-
    - name: argocd-vault-plugin-helm
      init:
        command: ["sh", "-c"]
        args: ["helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
```

Application
```
spec:
  source:
    plugin:
      name: argocd-vault-plugin-helm
      env:
      - name: AVP_K8S_ROLE
        value: xxx
      - name: AVP_TYPE
        value: vault
      - name: AVP_AUTH_TYPE
        value: k8s
      - name: AVP_K8S_MOUNT_PATH
        value: xxx
      - name: VAULT_ADDR
        value: 'xxx'
      - name: helm_args
        value: -f values.yaml
      - name: helm_dependency_name
        value: jetstack
      - name: helm_dependency_repo
        value: 'https://charts.jetstack.io'
```

Getting below error now:
```
rpc error: code = Unknown desc = `sh -c helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build` failed exit status 1: Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system helm.go:81: [debug] open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached main.(*repoAddOptions).run helm.sh/helm/v3/cmd/helm/repo_add.go:184 main.newRepoAddCmd.func1 helm.sh/helm/v3/cmd/helm/repo_add.go:80 github.com/spf13/cobra.(*Command).execute github.com/spf13/cobra@v1.1.3/command.go:852 github.com/spf13/cobra.(*Command).ExecuteC github.com/spf13/cobra@v1.1.3/command.go:960 github.com/spf13/cobra.(*Command).Execute github.com/spf13/cobra@v1.1.3/command.go:897 main.main helm.sh/helm/v3/cmd/helm/helm.go:80 runtime.main runtime/proc.go:225 runtime.goexit runtime/asm_amd64.s:1371
```

**Comment by mayzhang2000** [comment]
When using plugins, `helm repo add` of the dependent repository needs be be part of the script.

**Comment by rwong2888** [comment]
@mayzhang2000 I have `helm repo add`
```
args: ["helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build"]
```

**Comment by mayzhang2000** [comment]
@rwong2888 I just followed your steps and created application using [app](https://github.com/mayzhang2000/argocd-example-apps/blob/master/plugins/application-for-dependencies.yaml). I can see the application has dependencies resolved. 
![image](https://user-images.githubusercontent.com/7737306/131921949-70eb4142-4102-42d3-9ebd-494744edc9fe.png)

Maybe I have missed something?

**Comment by rwong2888** [comment]
I'm unable to get it working @mayzhang2000 ...

I'm on below argocd and vault plugin versions...

```
argocd@argocd-server-64757879d8-s8fjq:~$ argocd version
argocd: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
argocd@argocd-server-64757879d8-s8fjq:~$ argocd-vault-plugin version
argocd-vault-plugin v1.3.0 (733d62dd23ceb01a183d995799ba9e5566b08eeb) BuildDate: 2021-08-31T19:57:23Z
```

```
rpc error: code = Unknown desc = `sh -c helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build` failed exit status 1: Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system helm.go:81: [debug] open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached main.(*repoAddOptions).run helm.sh/helm/v3/cmd/helm/repo_add.go:184 main.newRepoAddCmd.func1 helm.sh/helm/v3/cmd/helm/repo_add.go:80 github.com/spf13/cobra.(*Command).execute github.com/spf13/cobra@v1.1.3/command.go:852 github.com/spf13/cobra.(*Command).ExecuteC github.com/spf13/cobra@v1.1.3/command.go:960 github.com/spf13/cobra.(*Command).Execute github.com/spf13/cobra@v1.1.3/command.go:897 main.main helm.sh/helm/v3/cmd/helm/helm.go:80 runtime.main runtime/proc.go:225 runtime.goexit runtime/asm_amd64.s:1371
```

**Comment by mayzhang2000** [comment]
@rwong2888 I did not use argocd-vault-plugin. In my plugin, I used below to test if plugin can resolve dependencies.
```
command: ["sh", "-c"]
        args: ["helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build"]
```

**Comment by rwong2888** [comment]
@mayzhang2000 I think the problem is it's a read only filesystem for repo-server... Any ideas where that may be configured?


Test
```
argocd@argocd-repo-server-784b7f6cc8-5vz64:~/.cache/helm/repository$ ls -la
total 20
drwxr-xr-x 2 argocd argocd 4096 Sep  1 22:20 .
drwxr-xr-x 1 argocd argocd 4096 Sep  1 22:20 ..
-rw-r--r-- 1 argocd argocd   39 Sep  1 22:20 argo-helm-charts-charts.txt
-rw-r--r-- 1 argocd argocd 5260 Sep  1 22:20 argo-helm-charts-index.yaml
argocd@argocd-repo-server-784b7f6cc8-5vz64:~/.cache/helm/repository$ touch y.yaml
touch: cannot touch 'y.yaml': Read-only file system
argocd@argocd-repo-server-784b7f6cc8-5vz64:~/.cache/helm/repository$ ls -la
total 20
drwxr-xr-x 2 argocd argocd 4096 Sep  1 22:20 .
drwxr-xr-x 1 argocd argocd 4096 Sep  1 22:20 ..
-rw-r--r-- 1 argocd argocd   39 Sep  1 22:20 argo-helm-charts-charts.txt
-rw-r--r-- 1 argocd argocd 5260 Sep  1 22:20 argo-helm-charts-index.yaml
argocd@argocd-repo-server-784b7f6cc8-5vz64:~/.cache/helm/repository$
```

Logs
```
 ❯ kubectl logs argocd-repo-server-784b7f6cc8-5vz64 | grep -i jetstack                                                                                                                                                                     [22:06:22]
time="2021-09-03T02:00:50Z" level=info msg="helm repo add jetstack https://charts.jetstack.io" dir=/tmp/https___github.com_forbes-media_operations-argocd-applications/applications/data-products/hello-secret-world/app execID=a2Evq
time="2021-09-03T02:00:50Z" level=info msg=Trace args="[helm repo add jetstack https://charts.jetstack.io]" dir=/tmp/https___github.com_forbes-media_operations-argocd-applications/applications/data-products/hello-secret-world/app operation_name="exec helm" time_ms=242.99659000000003
time="2021-09-03T02:00:53Z" level=info msg="helm repo add jetstack https://charts.jetstack.io" dir=/tmp/https___github.com_forbes-media_operations-argocd-applications/applications/data-products/hello-secret-world/vault execID=HIDyf
time="2021-09-03T02:00:54Z" level=info msg=Trace args="[helm repo add jetstack https://charts.jetstack.io]" dir=/tmp/https___github.com_forbes-media_operations-argocd-applications/applications/data-products/hello-secret-world/vault operation_name="exec helm" time_ms=202.90823699999999
time="2021-09-03T02:01:34Z" level=info msg="manifest error cache miss: &ApplicationSource{RepoURL:https://github.com/Forbes-Media/Operations-argocd-applications.git,Path:applications/operations/cert-manager,TargetRevision:main,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:&ApplicationSourcePlugin{Name:argocd-vault-plugin-helm,Env:[]*EnvEntry{&EnvEntry{Name:AVP_K8S_ROLE,Value:operations-argocd-vault-plugin,},&EnvEntry{Name:AVP_TYPE,Value:vault,},&EnvEntry{Name:AVP_AUTH_TYPE,Value:k8s,},&EnvEntry{Name:AVP_K8S_MOUNT_PATH,Value:auth/development-playground,},&EnvEntry{Name:VAULT_ADDR,Value:https://vault.forbes.com,},&EnvEntry{Name:helm_args,Value:-f values.yaml,},&EnvEntry{Name:helm_dependency_name,Value:jetstack,},&EnvEntry{Name:helm_dependency_repo,Value:https://charts.jetstack.io,},},},Chart:,}/d0ce0c72c56e8a695a14b374bc0f1b6e05925ecc"
time="2021-09-03T02:01:35Z" level=info msg="manifest error cache miss: &ApplicationSource{RepoURL:https://github.com/Forbes-Media/Operations-argocd-applications.git,Path:applications/operations/cert-manager,TargetRevision:main,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:&ApplicationSourcePlugin{Name:argocd-vault-plugin-helm,Env:[]*EnvEntry{&EnvEntry{Name:AVP_K8S_ROLE,Value:operations-argocd-vault-plugin,},&EnvEntry{Name:AVP_TYPE,Value:vault,},&EnvEntry{Name:AVP_AUTH_TYPE,Value:k8s,},&EnvEntry{Name:AVP_K8S_MOUNT_PATH,Value:auth/development-playground,},&EnvEntry{Name:VAULT_ADDR,Value:https://vault.forbes.com,},&EnvEntry{Name:helm_args,Value:-f values.yaml,},&EnvEntry{Name:helm_dependency_name,Value:jetstack,},&EnvEntry{Name:helm_dependency_repo,Value:https://charts.jetstack.io,},},},Chart:,}/d0ce0c72c56e8a695a14b374bc0f1b6e05925ecc"
time="2021-09-03T02:01:35Z" level=error msg="`sh -c helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build` failed exit status 1: Error: looks like \"https://charts.jetstack.io\" is not a valid chart repository or cannot be reached: open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system\nhelm.go:81: [debug] open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system\nlooks like \"https://charts.jetstack.io\" is not a valid chart repository or cannot be reached\nmain.(*repoAddOptions).run\n\thelm.sh/helm/v3/cmd/helm/repo_add.go:184\nmain.newRepoAddCmd.func1\n\thelm.sh/helm/v3/cmd/helm/repo_add.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.1.3/command.go:852\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.1.3/command.go:897\nmain.main\n\thelm.sh/helm/v3/cmd/helm/helm.go:80\nruntime.main\n\truntime/proc.go:225\nruntime.goexit\n\truntime/asm_amd64.s:1371" execID=UbONS
time="2021-09-03T02:01:35Z" level=error msg="finished unary call with code Unknown" error="`sh -c helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build` failed exit status 1: Error: looks like \"https://charts.jetstack.io\" is not a valid chart repository or cannot be reached: open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system\nhelm.go:81: [debug] open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system\nlooks like \"https://charts.jetstack.io\" is not a valid chart repository or cannot be reached\nmain.(*repoAddOptions).run\n\thelm.sh/helm/v3/cmd/helm/repo_add.go:184\nmain.newRepoAddCmd.func1\n\thelm.sh/helm/v3/cmd/helm/repo_add.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.1.3/command.go:852\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.1.3/command.go:897\nmain.main\n\thelm.sh/helm/v3/cmd/helm/helm.go:80\nruntime.main\n\truntime/proc.go:225\nruntime.goexit\n\truntime/asm_amd64.s:1371" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2021-09-03T02:02:34Z" grpc.service=repository.RepoServerService grpc.start_time="2021-09-03T02:01:34Z" grpc.time_ms=696.584 span.kind=server system=grpc
```

**Comment by rwong2888** [comment]
I see read only filesystem got introduced in argo 2.1, are you using a version below that @mayzhang2000 ?

**Comment by rwong2888** [comment]
Confirmed read only filesystem is the culprit. Downgraded to 2.0.5 to test

I see jetstack yaml in repo-server now and manifests attempting to sync now with the error
```
Failed sync attempt to 6e6fefeef677226ad62e344918a0d2280d0b44d5: one or more objects failed to apply (retried 5 times).
```

```
argocd@argocd-repo-server-767d4f5846-fz5gx:~/.cache/helm/repository$ ls -la
total 96
drwxr-xr-x 1 argocd argocd  4096 Sep  3 11:40 .
drwxr-xr-x 1 argocd argocd  4096 Jul 26 18:56 ..
-rw-r--r-- 1 argocd argocd    39 Sep  3 11:40 argo-helm-charts-charts.txt
-rw-r--r-- 1 argocd argocd  5260 Sep  3 11:40 argo-helm-charts-index.yaml
-rw-r--r-- 1 argocd argocd    36 Sep  3 11:40 jetstack-charts.txt
-rw-r--r-- 1 argocd argocd 63528 Sep  3 11:40 jetstack-index.yaml
argocd@argocd-repo-server-767d4f5846-fz5gx:~/.cache/helm/repository$
```

![image](https://user-images.githubusercontent.com/61470342/132000087-70c2bc9e-a118-40b0-940d-db90ea687908.png)


Reference:
https://github.com/argoproj/argo-cd/issues/3648


@mayzhang2000 , @alexmt can we have repo-server home dir or helm dir be an emptydir similar to how plugin home is on argo-server?
https://github.com/argoproj/argo-cd/blob/master/manifests/base/server/argocd-server-deployment.yaml#L203
https://github.com/argoproj/argo-cd/blob/master/manifests/base/server/argocd-server-deployment.yaml#L176
https://github.com/argoproj/argo-cd/blob/master/manifests/base/repo-server/argocd-repo-server-deployment.yaml#L124

**Comment by rwong2888** [comment]
Upgraded to 2.1.2 and added this overlay

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /home/argocd
          name: plugins-home
      volumes:
      - emptyDir: {}
        name: plugins-home
```

Getting past the previous errors now

**Comment by rwong2888** [comment]
@mayzhang2000 , @alexmt can you review the [PR](https://github.com/argoproj/argo-cd/pull/7152)?

**Comment by rwong2888** [comment]
Emptydir is wiping out the cached helm repos specified in configmap...

**Comment by rwong2888** [comment]
Any suggestions on how to overcome this issue @mayzhang2000 , @alexmt ?

New overlay to remove read only filesystem....

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        securityContext:
          readOnlyRootFilesystem: false
```

**Comment by mayzhang2000** [comment]
@rwong2888 Have you tried [custom tooling](https://argo-cd.readthedocs.io/en/latest/operator-manual/custom_tools/#adding-tools-via-volume-mounts)?

**Comment by irizzant** [comment]
Please review https://github.com/argoproj/argo-cd/pull/7162

To me this works like a charm.

Waiting for the approval, you can also use the following kustomize patch:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
      - name: custom-tools
        emptyDir: {}
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
        env:
        - name: HELM_CACHE_HOME
          value: /custom-tools
        - name: HELM_CONFIG_HOME
          value: /custom-tools
        - name: HELM_DATA_HOME
          value: /custom-tools
```

**Comment by rwong2888** [comment]
Thanks @irizzant , I was looking into exporting `HELM_CACHE_HOME` in the plugin, but this is cleaner and works!

Any thoughts on adding `HELM_PLUGINS`? I tried to do that, but it did not move my plugin from `HELM_PLUGINS=/home/argocd/.local/share/helm/plugins/` to `/helm-working-dir`. Additional configuration must be needed.

**Comment by irizzant** [comment]
@rwong2888  you're welcome.

It's weird it doesn't work. Indeed, just with the above config, helm should be already able to use `helm-working-dir`.
I tried myself using the kustomize patch reported above, and when I run `helm plugin install` I get no error and I see the plugin data listed in `helm-working-dir/plugins`.

E.g
```
argocd@argocd-repo-server-998b74559-7jhf4:~$ helm plugin install https://github.com/jkroepke/helm-secrets

Installed plugin: secrets

argocd@argocd-repo-server-998b74559-7jhf4:~$ ls -al /helm-working-dir/plugins/
total 12
drwxr-xr-x 10 argocd argocd  267 Sep  8 09:39 .
drwxrwxrwx  3 root   root     21 Sep  8 09:37 ..
drwxr-xr-x  3 argocd argocd  103 Sep  8 09:39 helm-env
drwxr-xr-x 11 argocd argocd  292 Sep  8 09:37 helm-push.git
drwxr-xr-x 12 argocd argocd 4096 Sep  8 09:38 helm-s3.git
drwxr-xr-x  8 argocd argocd 4096 Sep  8 09:38 helm-secrets
drwxr-xr-x  3 argocd argocd  103 Sep  8 09:39 https-github.com-adamreese-helm-env
drwxr-xr-x  9 argocd argocd  265 Sep  8 09:37 https-github.com-chartmuseum-helm-push.git
drwxr-xr-x 10 argocd argocd  330 Sep  8 09:38 https-github.com-hypnoglow-helm-s3.git
drwxr-xr-x  8 argocd argocd 4096 Sep  8 09:38 https-github.com-jkroepke-helm-secrets

```

Which plugin are you trying to install?

**Comment by rwong2888** [comment]
Ah, I figured it out @irizzant , it is an artifact from Build Your Own Image...
However, If I were to point it to the helm dir, then the above overlay would wipe it out.
Should I be installing it after the fact somehow?

```
FROM quay.io/argoproj/argocd:v2.1.2

ARG GCS_PLUGIN_VERSION="0.3.13"
ARG GCS_PLUGIN_REPO="https://github.com/hayorov/helm-gcs.git"

RUN helm plugin install ${GCS_PLUGIN_REPO} --version ${GCS_PLUGIN_VERSION}
```

**Comment by irizzant** [comment]
@rwong2888 in this case I think you could specify a Kubernetes initContainer doing exactly the same.

**Comment by rwong2888** [comment]
@irizzant it looks like it installs the plugin as I see the directory, however it does not show up in `helm plugin list` nor does it recognize a handler for `gs`. Am I missing an env variable?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
      - name: helm-working-dir
        emptyDir: {}
      initContainers:
      - name: helm-install
        image: quay.io/argoproj/argocd:v2.1.2
        command: ["sh", "-c", "-x"]
        args:
          - |-
              GCS_PLUGIN_VERSION="0.3.13"
              GCS_PLUGIN_REPO="https://github.com/hayorov/helm-gcs.git"
              helm plugin install ${GCS_PLUGIN_REPO} --version ${GCS_PLUGIN_VERSION}
              # helm repo add argo-helm-charts gs://argo-helm-charts
        env:
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
        - name: HELM_PLUGINS
          value: /helm-working-dir
        volumeMounts:
        - mountPath: /helm-working-dir
          name: helm-working-dir
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /helm-working-dir
          name: helm-working-dir
        env:
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
        - name: HELM_PLUGINS
          value: /helm-working-dir
```

```
helm-install + GCS_PLUGIN_VERSION=0.3.13
helm-install + GCS_PLUGIN_REPO=https://github.com/hayorov/helm-gcs.git
helm-install + helm plugin install https://github.com/hayorov/helm-gcs.git --version 0.3.13
helm-install Installing helm-gcs 0.3.13 ...
helm-install helm-gcs 0.3.13 is correctly installed.
helm-install Init a new repository:
helm-install   helm gcs init gs://bucket/path
helm-install Add your repository to Helm:
helm-install   helm repo add repo-name gs://bucket/path
helm-install Push a chart to your repository:
helm-install   helm gcs push chart.tar.gz repo-name
helm-install Update Helm cache:
helm-install   helm repo update
helm-install Get your chart:
helm-install   helm fetch repo-name/chart
helm-install Installed plugin: gcs
```

```
argocd@argocd-repo-server-6d9f6b969b-p789b:~$ cd /helm-working-dir/plugins/
argocd@argocd-repo-server-6d9f6b969b-p789b:/helm-working-dir/plugins$ ls -la
total 16
drwxr-xr-x 4 argocd argocd 4096 Sep  8 16:33 .
drwxrwxrwx 3 root   root   4096 Sep  8 16:33 ..
drwxr-xr-x 9 argocd argocd 4096 Sep  8 16:33 helm-gcs.git
drwxr-xr-x 8 argocd argocd 4096 Sep  8 16:33 https-github.com-hayorov-helm-gcs.git
argocd@argocd-repo-server-6d9f6b969b-p789b:/helm-working-dir/plugins$ helm plugin list
NAME	VERSION	DESCRIPTION
argocd@argocd-repo-server-6d9f6b969b-p789b:/helm-working-dir/plugins$ helm repo add argo-helm-charts gs://argo-helm-charts
Error: could not find protocol handler for: gs
argocd@argocd-repo-server-6d9f6b969b-p789b:/helm-working-dir/plugins$ env | grep -i helm
PWD=/helm-working-dir/plugins
HELM_CONFIG_HOME=/helm-working-dir
HELM_PLUGINS=/helm-working-dir
HELM_CACHE_HOME=/helm-working-dir
HELM_DATA_HOME=/helm-working-dir
argocd@argocd-repo-server-6d9f6b969b-p789b:/helm-working-dir/plugins$
```

**Comment by irizzant** [comment]
@rwong2888 I think this is more an Helm issue.

I bumped into https://github.com/helm/helm/issues/7528 and tried to also set `XDG_DATA_HOME=/helm-working-dir`.
At this point `helm plugin list` starts complaining about double plugin names:
```
Error: two plugins claim the name "secrets" at "/helm-working-dir/plugins/helm-secrets" and "/helm-working-dir/plugins/https-github.com-jkroepke-helm-secrets"
```
but this seems to me more related to helm than to the Kubernetes volume.

**Comment by rwong2888** [comment]
I am okay keeping `HELM_PLUGINS` unset as it is working for me and revisiting later @irizzant . Do you or @alexmt foresee any issues with that?

**Comment by om3171991** [comment]
@mayzhang2000 @rwong2888 - We reverted back to v2.0.5 but still seeing the same error. any leads?  as It blocked all our deployment with sub-charts.

**Comment by om3171991** [comment]
@rwong2888 - but that also not working. It was working earlier before the upgrade.

**Comment by rwong2888** [comment]
@om3171991 read the change logs and see what changed between your working version and the first version that breaks.

**Comment by headyj** [comment]
I still have @mayzhang2000 issue (dependency are resolved but are empty, ArgoCD status is "Missing") with v2.2.1:
plugin:
`- name: kustomized-helm
  init:
    command: ["/bin/sh", "-c"]
    args: ["helm dependency build"]
  generate:
    command: ["/bin/sh", "-c"]
    args: ["helm template .  --values inject-values.yml --values values.yaml"]
`
Chart.yml:
`
---
apiVersion: v2
name: my-project
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: my-helm
  version: 0.7.13
  repository: http://chartmuseum.chartmuseum.svc.cluster.local:8080/my-helm`
`
Any idea?

**Comment by headyj** [comment]
still have @mayzhang2000 issue (dependency are resolved but are empty, ArgoCD status is "Missing") with v2.2.1:
plugin:
```
- name: kustomized-helm
  init:
    command: ["/bin/sh", "-c"]
    args: ["helm dependency build"]
  generate:
    command: ["/bin/sh", "-c"]
    args: ["helm template .  --values inject-values.yml --values values.yaml"]
```

Chart.yml:
```
---
apiVersion: v2
name: my-project
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: my-helm
  version: 0.7.13
  repository: http://chartmuseum.chartmuseum.svc.cluster.local:8080/my-helm
```
Any idea?
