### ISSUE TITLE
GlusterFS PersistentVolume does not contain a namespace

### ISSUE THREAD

**Issue by doyelese** [argoproj/argo-cd#7159]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Gluster PV do not get namespaces. This causes problems when syncing as the PV will go 'missing' under certain sync conditions (moving application to a project, for example).

**To Reproduce**

Deploy an app that contains a gluster PV. Deploy via reference to a git repository

Argo config file
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-emails
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.helcim.net/helcim/technology/infrastructure/core/emails.git
    targetRevision: HEAD
    path: kubernetes/qa/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```

Part of the referenced config file that contains PV definition:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: qa-emails
  name: qa-emails-volume
  annotations:
    pv.beta.kubernetes.io/gid: "0"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: /qa-emails
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  ```

In ArgoCD namespace section is missing 

![Screen Shot 2021-09-03 at 4 07 11 PM](https://user-images.githubusercontent.com/65038083/132069687-98089532-82e2-49f4-a6a2-8c48fd51e2a9.png)

in `Live Manifest`
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.beta.kubernetes.io/gid":"0"},"labels":{"app.kubernetes.io/instance":"qa-emails"},"name":"qa-emails-volume"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"50Gi"},"glusterfs":{"endpoints":"glusterfs-cluster","path":"/qa-emails","readOnly":false},"persistentVolumeReclaimPolicy":"Retain"}}
    pv.beta.kubernetes.io/gid: '0'
```

and also missing in `Desired Manifest`
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.beta.kubernetes.io/gid: '0'
  labels:
    app.kubernetes.io/instance: qa-emails
  name: qa-emails-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  glusterfs:
    endpoints: glusterfs-cluster
    path: /qa-emails
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
```

**Expected behavior**

The desired manifest and PV would contain the `namespace` section as it appears in the original config file.

**Screenshots**

PV appears missing on sync with certain conditions:

![Screen Shot 2021-09-03 at 4 11 58 PM](https://user-images.githubusercontent.com/65038083/132069790-a62fa54f-b601-41bb-81b7-ec87990e2b21.png)

**Version**

```shell
argocd: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.1+aab9542
```
