### ISSUE TITLE
Ability to read additional environment variables within the argocd-repo-server

### ISSUE THREAD

**Issue by shanproofpoint** [argoproj/argo-cd#7189]
# Summary

When specifying an Application yaml, we would like the build envirionment to include all os level environment variables or can be restricted to any custom os environment variable prefixed with ARGOCD_

# Motivation

we are setting up many clusters that poll a single git repo for their entire list of applications and their configuration.  however, each cluster has an identity that is used in parameterizing some deployments and custom resources either through additional annotations, environment variables or other resources like disks.  we store this as a configmap of values inside the argocd namespace which then can me mounted in the argocd-repo-server as environment variables.

# Proposal

just read additional os level environment variables into the argocd build environment so we can do the following:

```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-sops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://isindir.github.io/sops-secrets-operator/
    chart: sops-secrets-operator
    targetRevision: 0.9.2
    helm:
      parameters:
        - name: "gcp.enabled"
          value: "true"
        - name: "gcp.existingSecretName"
          value: "sops-decrypter-access"
        - name: "podAnnotations.i-was-here/ok"
          value: $ARGOCD_MY_CUSTOM_ENV_VAR
        - name: "podAnnotations.i-was-here2/ok"
          value: $ARGOCD_APP_NAME```


where ARGOCD_MY_CUSTOM_ENV_VAR would be read from a configmap into the argocd-repo-server container

**Comment by Jmainguy** [comment]
We are currently using a plugin to get these vars, but that stops us from using the helm: block. So this would be a great feature to add.

**Comment by crenshaw-dev** [comment]
I think this makes sense. Rather than prefixing with `ARGOCD_` (there may be collisions with Argo CD env vars added in the future), maybe there could be an allow-list configurable via repo-server ConfigMap or env var?

**Comment by mstrYoda** [comment]
Hi, I would like to work on this issue. Can you assign it to me @crenshaw-dev ? Thanks.

**Comment by jselleck-sans** [comment]
I'd like this too!  In my case I want to override application placeholders with global (or config map) env vars.   Our use case is gitops - we want to use the same manifests but pull from different branches depending on a cluster name variable (changing branch Revision).  I also see us setting parameters in apps for helm charts - dependent on global params..

**Comment by jselleck-sans** [comment]
`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: $MY_CUSTOM_ENV_VAR
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook`

+ maybe add an annotation to the Application manifest to point to a CM for variables.

**Comment by Stolr** [comment]
+1 Would be so good !

Trying to achieve the same goal. Having multiple cluster and 1 applicationSet. So , for ingress route, it would be pretty handfull.

**Comment by shanproofpoint** [comment]
Thank you!


Shan Tang

Staff Engineer

Proofpoint Isolation


________________________________

**Comment by revaspeho** [comment]
Hi I am the head DevOps Engineer for the federal government. We need to be able to pass in our gitlab auth token into the url string for helm.valueFiles -https://<code>$AUTH_TOKEN. This would be great!

**Comment by danhawkins** [comment]
👍  for this, I am trying to have a dynamic targetRevision also 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt
  namespace: argocd
spec:
  project: core-services
  source:
    path: services/letsencrypt/manifests
    repoURL: <repo>
    targetRevision: $TARGET_REVISION
```

**Comment by krzwiatrzyk** [comment]
@revaspeho theoretically you can achieve it with `helm-secrets` plugin - https://github.com/argoproj/argo-cd/issues/7819
practically, environment substation doesn't work for me (but still trying to make it work)

**Comment by danhawkins** [comment]
@mstrYoda are you actively working on this?

**Comment by danhawkins** [comment]
I was able to get something to work here, I built my own docker image, removing [this line](https://github.com/argoproj/argo-cd/blob/master/applicationset/utils/utils.go#L27) from applicationset utils to allow access to the env function. Then using and applicationset with a go template 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: letsencrypt
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{.name}}-letsencrypt'
    spec:
      project: core-services
      source:
        path: services/letsencrypt/manifests
        repoURL: https://github.com/xxxxxxxxxxxx/argolab.git
        targetRevision: '{{ env "TARGET_REVISION" }}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
```

This works, but obviously there is some security concern. But I think if we are able to set an allowlist of vars somewhere like suggested earlier on, we can perhaps just filter out env values not on the list? Something like that. I mean I am sure there could be more elegant ways to solve this. But I am happy with this so far.
