### ISSUE TITLE
Scoped repositories may not work as intended 

### ISSUE THREAD

**Issue by patchon** [argoproj/argo-cd#7191]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Hi, 

I think this could be a bug, but it could also be a missunderstanding, or a feature that is not yet complete. 
We are very exciting about the idea about scoped repositories, since it seems to fulfill our needs. Proposal is available at https://github.com/argoproj/argo-cd/blob/master/docs/proposals/project-repos-and-clusters.md and from what I understand it's being merged from #6065 , #6943 , #7008 and possible others that I've missed. 

So the basic understanding to us were that we had two users, 
* **user-1**,  
* **user-2** 

Each user has their own project, 
* project-1,
* project-2

And within their own project they would be able to create a so called "scoped repository" (if rbac allowed). 
This is really neat, and exactly what we needed, so we pulled latest master (as of today), and got working, *partially*. 

So it seems like **user-2** is able to add the scoped repository from **user-1** in his project and application. 

This to me, feels wrong, and kind of defeats atleast one of the purposes we were hoping for, namely that **each user** could add private scoped repositories and that those repositories **only should be available for them selves** (ie. only for the user **that actually has** "upstream" access (with pw/sshkey)).  

**To Reproduce**

* Pull latest master (as of 2021-09-09, docker image id:      docker.io/argoproj/argocd@sha256:69041056f24e6bc22c0005d4481ec4020240fce92df5b8957da948cb9012a80a)
* Have two test-users, **user-1** and **user-2**  
* Set up an rbac as follows, 
```
  policy.csv: |
    p, role:user-1-admin, applications, create,     user-1-project/*, allow
    p, role:user-1-admin, applications, delete,     user-1-project/*, allow
    p, role:user-1-admin, applications, get,        user-1-project/*, allow
    p, role:user-1-admin, applications, override,   user-1-project/*, allow
    p, role:user-1-admin, applications, sync,       user-1-project/*, allow
    p, role:user-1-admin, applications, update,     user-1-project/*, allow
    p, role:user-1-admin, projects,     get,        user-1-project,   allow
    g, user-1, role:user-1-admin

    p, role:user-2-admin, applications, create,     user-2-project/*, allow
    p, role:user-2-admin, applications, delete,     user-2-project/*, allow
    p, role:user-2-admin, applications, get,        user-2-project/*, allow
    p, role:user-2-admin, applications, override,   user-2-project/*, allow
    p, role:user-2-admin, applications, sync,       user-2-project/*, allow
    p, role:user-2-admin, applications, update,     user-2-project/*, allow
    p, role:user-2-admin, projects,     get,        user-2-project,   allow
    g, user-2, role:user-2-admin
  policy.default: ""
```

This to me says, that 
1. by default you have no rights at all, 
2. if you are **user-1** you have "admin" rights for **user-1-project**, and vice versa for user-2. 

* Create the two projects (replace 1 with 2 for the other project), 
```
kind: AppProject
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: user-1-project
  spec:
    description: This appproject belongs to the user-1
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    destinations:
      - namespace: user-1
        server: 'https://kubernetes.default.svc'
    sourceRepos:
      - ssh://git@internal-git-server:9999/**
```

* Now, **user-1** creates a scoped repository, 
```
apiVersion: v1
kind: Secret
metadata:
  name: repo-user-1
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  project: user-1-project
  name: user-1-private-repo
  url: ssh://git@internal-git-server:9999/user-1-secret-project/user-1-secret-project.git
  sshPrivateKey: |
  < ssh key >
```

* So this is all fine and dandy, and works as expected for **user-1**. That user get's his scoped repository and can use it within his application (this we tried, and **user-1** successfully can create an application with the scoped repository as source url). 

* However, **user-2** can also use the same repository, within his application (in his project, ie. **user-2**-project), like this, 
```
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: user-2-app-test
    namespace: argo-lab
  spec:
    destination:
      namespace: user-2
      server: https://kubernetes.default.svc
    project: user-2-project
    source:
      path: ./
      repoURL: ssh://git@internal-git-server:9999/user-1-secret-project/user-1-secret-project.git
      targetRevision: HEAD
```

The **only** thing needed here by **user-2** is to know the repourl, ie. the git-url to pull from. It doesn't need to know any secrets or anything, **user-2** hasn't even defined any scoped repositories. 

This feels like an issue, or I'm missing something vital.    

**Expected behavior**

I would expect that scoped repositories are **only usuable by the projects from within they are defined**. 
Ie. my **user-2** shouldn't be able to reference **user-1's** scoped repository from his **user-2-project**. 

**Version**

```shell
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:02:21Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.2.0+be884d2
  BuildDate: 2021-09-06T16:12:14Z
  GitCommit: be884d217284aaf96f0389e1ae34fd03075a8038
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**
This is easy to reproduce, but if not, I can provide logs of course, I just don't have them atm. 

**Summary**
Hope I made sense, and that I'm not missing anything. 
It's possible that this has not yet been implemented, or that I'm doing something wrong, or that as stated above, I missunderstand something. 

Thanks for a great product and your hard work ❤️ 🎉
