### ISSUE TITLE
Project destination using cluster name does not work

### ISSUE THREAD

**Issue by francilioaraujo** [argoproj/argo-cd#7198]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

AppProject.spec.destinations has the type []ApplicationDestination (https://github.dev/argoproj/argo-cd/blob/49378a95c400a9e535a7178a2a77ba2022a5e084/pkg/apis/application/v1alpha1/types.go#L1639). Aside from declarative configuration there is no other way to use the cluster's name to define an allowed destination in a project. Using the name of the cluster creates a destination with an empty URL, thus not allowing an application to be deployed.

**To Reproduce**

1. Have an external cluster;
2. Add an AppProject manifest with the cluster's name in destinations;
3. Add an Application manifest in this project with the cluster's name in destination .

**Expected behavior**

The application should be deployed.

**Version**

argocd: v2.1.0+d0b2d55
  BuildDate: 2021-08-20T05:30:54Z
  GitCommit: d0b2d55e3fb7fe8b17385d6687886de41651f31b
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0

**Comment by francilioaraujo** [comment]
The same thing happens on v2.1.2


argocd: v2.1.0+d0b2d55
  BuildDate: 2021-08-20T05:30:54Z
  GitCommit: d0b2d55e3fb7fe8b17385d6687886de41651f31b
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0

**Comment by alexmt** [comment]
I think it is not a bug but valid feature request. We need to update application controller to use [ValidateDestination](https://github.com/argoproj/argo-cd/blob/49378a95c400a9e535a7178a2a77ba2022a5e084/util/argo/argo.go#L301) function to fetch cluster server URL if only cluster `name` is specified. This should be enough to support validation using cluster name. Also projects cluster name should be mentioned in projects documentation.

**Comment by jaideepr97** [comment]
Hey @alexmt, I'd be interested in looking into this

**Comment by alexmt** [comment]
Thank you @jaideepr97 !

**Comment by jaideepr97** [comment]
Hi @francilioaraujo @alexmt 
I'm trying to reproduce this issue, but I'm not sure how to
Could you elaborate on how I should create the application?

I tried applying this application manifest through the terminal but didn't encounter the described issue:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: myproject
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    name: k3d-local-cluster-2
    namespace: default
 ```
 
 I also tried creating this app through the UI and failed to reproduce the issue

**Comment by alexmt** [comment]
Hello @jaideepr97 ,

I think to reproduce it you need to create a project that whitelist cluster by name but not URL. UI does not allow it so you would have to use Kubectl. Here is sample project YAML:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject
spec:
  description: Example Project

  sourceRepos:
  - '*'

  destinations:
  - namespace: guestbook
     name: k3d-local-cluster-2
```
