### ISSUE TITLE
`argocd admin settings resource-overrides ignore-differences` doesn't work with `jqPathExpressions`

### ISSUE THREAD

**Issue by mikebryant** [argoproj/argo-cd#7223]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

With a configmap setting like:

```yaml
  resource.customizations.ignoreDifferences.argoproj.io_Application: |
    jqPathExpressions:
      - '.spec.syncPolicy.automated.allowEmpty'
```

The CLI tool doesn't recognise the config:
```
mikebryant@BULB-MB-0246 /tmp % docker run --rm -it -w /src -v $(pwd):/src quay.io/argoproj/argocd:v2.1.0 argocd admin settings resource-overrides ignore-differences --argocd-cm-path argocd-cm.yaml ci-cluster-base.yaml
INFO[0000] Starting configmap/secret informers
INFO[0000] Configmap/secret informer synced
INFO[0000] Ignore status for CustomResourceDefinitions
INFO[0000] Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions
Ignore differences are not configured for 'argoproj.io/Application'
```

**To Reproduce**

Use config as above that doesn't use the `jsonPointers` section

**Expected behavior**

It should continue and use the config

**Version**

```shell
mikebryant@BULB-MB-0246 /tmp % docker run --rm -it -w /src -v $(pwd):/src quay.io/argoproj/argocd:v2.1.0 argocd version
argocd: v2.1.0+d0b2d55
  BuildDate: 2021-08-20T05:30:54Z
  GitCommit: d0b2d55e3fb7fe8b17385d6687886de41651f31b
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

**Investigation**

The issue appears to be [here](https://github.com/argoproj/argo-cd/blob/25db5038c7dd80fab7445ba1ea3f17cc0bc4539d/cmd/argocd/commands/admin/settings.go#L405). The CLI tool is explicitly checking for jsonPointers, but ignores the new way that was just added

**Comment by ReeSilva** [comment]
It also happens on UI and when trying to apply a application with ignoreDifferences for a jqPath. The yaml below could be used to reproduce:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fake-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://fake.com/repo/manifests.git'
    path: fake-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: fake-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fake-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - kind: Deployment
    jqPathExpressions:
    - .metadata.annotations | select( .["replicator.v1.mittwald.de/replicated-at"] != null )
```
