### ISSUE TITLE
ArgoCD doesn't deploy hook resources when there are no other resources in the Argo application

### ISSUE THREAD

**Issue by SansDK** [argoproj/argo-cd#7237]
**Describe the bug**

ArgoCD doesn't seem to deploy a Job with the following annotations when it is the only resource in the Argo application.
```
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
```

**To Reproduce**

1. Create an Argo application
2. Add a Job to it with above annotations
3. Try to sync the application

**Expected behavior**

We would expect that the Job itself would run once, then be deleted once an update is detected in the image tag of the Job template.

**Version**

```shell
v2.1.2+7af9dfb
```

**Comment by creosonic** [comment]
Same issue with helm hooks - Job is not listed (and not available for sync) when there are no any other resources but Job with hooks itself.
```
annotations:
  helm.sh/hook: post-install
  helm.sh/hook-delete-policy: before-hook-creation
  helm.sh/hook-weight: '-5'
```

Version:
```
v2.1.7+a408e29
```
