### ISSUE TITLE
Cannot reference local values file when using Remote Helm chart

### ISSUE THREAD

**Issue by MeNsaaH** [argoproj/argo-cd#7257]
**Describe the bug**

When using remote helm charts, I realized that all my values files I specify in the repository don't work. I don't know if this is by design. I'm trying to use it alongside the helm secrets plugin, hence the need to pass the values files externally via the schemed-path format (`secrets://secrets.yaml`)

Here's my app file
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.1
    chart: ingress-nginx

    helm:
      releaseName: ingress-nginx
      valueFiles:
        - secrets://.yaml
        - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Brice187** [comment]
Maybe this gets fixed with https://github.com/argoproj/argo-cd/pull/6280

**Comment by ericmeadows** [comment]
From what I can tell, he (and I, now) are asking to support a remote Helm chart using a git-backed values file.  The way around this is that you have to create your own Helm chart locally and add said `values.yaml` file, making the external chart a dependency of an empty chart.  I feel like there's a lot of entangled logic that [Plumbr.ai](https://www.plumbr.ai/) would surface here...

**Comment by romulus-ai** [comment]
Would be nice to find a solution for that, no Idea how this could look like. However, to create an empty helmchart in a git repo for each external helmchart we are using is a bit overkill... However in my opinion it would be much easier if argocd would provide a mechanism for secrets..

**Comment by YperXristis** [comment]
@kostis-codefresh @romulus-ai 
Here is the solution I came up with which works for me, please share it.
```

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: ska
  source:
    chart: kube-prometheus-stack
    helm:
      version: v3
      values: |
{{ .Files.Get "prometheus-stack-vaules.yaml" | indent 8 }}
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 34.9.0
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
    - CreateNamespace=true
    ```
    Now you can put the values file in your repo and reference a remote helm repo.
    one directory up I have the ```prometheus-stack-vaules.yaml``` file with all the values
