### ISSUE TITLE
argocd admin export error on applicationsets.argoproj.io

### ISSUE THREAD

**Issue by timox** [argoproj/argo-cd#7276]
**Describe the bug**

after upgrading from 2.0.5 to 2.1.1, `argocd admin export` produce an error while we do not use applicationset CRDs :

```
 argocd@argocd-server-6f7dd485cc-sc59x:~$ argocd admin export > /tmp/test211.yaml
FATA[0000] applicationsets.argoproj.io is forbidden: User "system:serviceaccount:argocd:argocd-server" cannot list resource "applicationsets" in API group "argoproj.io" in the namespace "argocd"
```
Do I really need applicationsets CRDs ?
Is the export correct and this is just an informative message ?

The Roles argocd-server :
```
...
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
  - verbs:
      - create
      - list
```

In CRD argoproj.io i only have "Application" and "AppProject" defined

**To Reproduce**

 - connect to the argocd-server pod
 - execute `argocd admin export > export.yaml`

**Expected behavior**

should just get the export in a yamlfile without the reference to applicationsets.argoproj.io.
In argocd 2.0.5  We used `argocd-util export`, it worked without error.

**Version**

```shell
argocd@argocd-server-6f7dd485cc-sc59x:~$ argocd version
argocd: v2.1.1+aab9542
  BuildDate: 2021-08-25T15:12:04Z
  GitCommit: aab9542f8b3354f0940945c4295b67622f0af296
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```
