### ISSUE TITLE
ignore deployments generation increase number

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [argoproj/argo-cd#7285]
# Summary

I am using kyverno to apply some policies in our k8s. kyverno is deployed using argocd.
Everytime that kyverno is used to mutate a resource, a new annotation is patched to the kyverno deployment:
 annotations:  
    kyverno.io/last-request-time: "2021-09-23T13:49:17.475532085Z"

This causes an increase of the deployment generation number, and argo sets healthy a progressing

HEALTH DETAILS
Waiting for rollout to finish: observed deployment generation less then desired generation

# Proposal

I would like to avoid this behaviour, because I receive constant notifications about application is progressing.

Is there any way to ignore this health behaviour, or totally ignore the health check for a specific deployment?

**Comment by tobiaswi** [comment]
We ran into the exact issue this week and spend some time pulling our hair to figure out the source of the bahaviour.

**Comment by ccremer** [comment]
We're also affected by this using Kyverno.
We tried using the [ignoreDifferences](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration) spec but that _doesn't_ help unfortunately:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  ignoreDifferences:
    - group: 'apps'
      kind: 'Deployment'
      jsonPointers:
        - '/metadata/annotations/kyverno.io~1last-request-time'
    - group: 'apps'
      kind: 'ReplicaSet'
      jsonPointers:
        - '/metadata/annotations/kyverno.io~1last-request-time'
```
(also see http://jsonpatch.com/)

**Comment by salineselin** [comment]
We're also running into this issue in our environment. I thought it might have been the webhookactive bit repeatedly updating, but I don't believe that is the case.

**Comment by PDQDakota** [comment]
This issue on the Kyverno side might add some context to this issue. https://github.com/kyverno/kyverno/issues/2269

I still think having the option to work around this on the ArgoCD side would be very helpful for not just this issue but others that may manifest on other deployments as well.

**Comment by tuananh** [comment]
this seems to be on argocd side because it does the comparison here when get health status https://github.com/argoproj/gitops-engine/blob/master/pkg/health/health_deployment.go#L77

**Comment by nmorey-ratehub** [comment]
For anyone who had a similar thought to me, adding an `ignoreDifferences` entry for the `observedGeneration` does not address the issue.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  ignoreDifferences:
    - group: 'apps'
      kind: 'Deployment'
      name: 'kyverno'
      jsonPointers:
        - '/status/observedGeneration'
```
I am assuming this is because AgroCD `getAppsv1DeploymentHealth` function does not take into account the `ignoreDifferences`.
