### ISSUE TITLE
Poor error reporting for missing namespace

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#7294]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Loading an app in the argocd view which targets a nonexistent namespace yields an unhelpful error message

**To Reproduce**

1. Add a `apps/charts/rabbitmq/Chart.yaml`:
```yaml
name: rabbitmq
apiVersion: v2
appVersion: "1.0"
description: Open source message broker software that implements the Advanced Message Queuing Protocol (AMQP)
version: 8.22.3
dependencies:
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.22.3
```

2. Add a `apps/applications/rabbitmq.yaml` (do *not* create the `rabbitmq` namesapce):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  destination:
    namespace: rabbitmq
    server: {{ .Values.spec.destination.server }}
  source:
    path: apps/charts/rabbitmq
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: rabbitmq
      valueFiles:
        - values.yaml
```
(Do create an `apps/applications/values.yaml` file)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/134741327-5fa9b7fd-2304-4b80-b331-414c85a780b5.png)
> Application conditions
SyncError
Failed sync attempt to fbfb7cca97fdc55456637ac2f3cc9e57a17960c9: one or more objects failed to apply (retried 5 times).
12 minutes ago (Fri Sep 24 2021 17:13:20 GMT-0400)

**Version**

```shell
{
    "Version": "v2.1.0+50b0010",
    "BuildDate": "2021-08-04T00:28:17Z",
    "GitCommit": "50b00104704f28780b320ae043ecbda64214f132",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

I couldn't figure out where to find useful logs, after a few moments of reviewing the ArgoCD interface, I had a eureka moment. But I shouldn't have needed to, the app should have clearly reported this user error.

For my reference, `receiveTimestamp: "2021-09-24T20:32:54.611061798Z"`  in the `repo-server` logs shows `helm template . --name-template rabbitmq --namespace rabbitmq ...`

Afaict, the error message from that command isn't present

When I locally run:
```sh
helm dependency build
helm template . --name-template rabbitmq --namespace notrabbitmq --kube-version 1.20 --values values/0-base.yaml --values values/glaypen.yaml --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1alpha2 --api-versions acme.cert-manager.io/v1alpha3 --api-versions acme.cert-manager.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions argoproj.io/v1alpha1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions bitnami.com/v1alpha1 --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1alpha2 --api-versions cert-manager.io/v1alpha3 --api-versions cert-manager.io/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions cloud.google.com/v1 --api-versions cloud.google.com/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions events.k8s.io/v1 --api-versions extensions/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions internal.autoscaling.k8s.io/v1alpha1 --api-versions metrics.k8s.io/v1beta1 --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1alpha1 --api-versions networking.gke.io/v1 --api-versions networking.gke.io/v1beta1 --api-versions networking.gke.io/v1beta2 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1beta1 --api-versions nodemanagement.gke.io/v1alpha1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions scalingpolicy.kope.io/v1alpha1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1 --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions v1 --include-crds > foo.yaml
kubectl apply -f foo.yaml
```
I get:
```
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
Error from server (NotFound): error when creating "foo.yaml": namespaces "notrabbitmq" not found
```

I can't find an equivalent item in the k8s logs.
