### ISSUE TITLE
Applicationset stuck in deletion 

### ISSUE THREAD

**Issue by runderwoodcr14** [argoproj/argo-cd#7330]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

While doing some deployments, I removed one of my applicationsets as per needed to be changed and needed a clean deployment, currently I have an app of app setup with a parent application which at the same time contain a set of applicationsets for different infra related deployments, the applications got removed but the applicationset is stuck in pending deletion, I've waited for a couple of hours and is still in pending deletion

**To Reproduce**

I've basically just removed the yaml file from the repository to force argocd to remove the application, argocd detects that the applicationset is not in the repository anymore and starts a sync and deletes the applications that are part of the applicationset but not the applicationset itself, I tried to prune it from the UI as well with no luck

**Expected behavior**

The applicationset to be removed without any problems nor causing delays

**Screenshots**
<img width="1033" alt="Screen Shot 2021-09-30 at 18 15 29" src="https://user-images.githubusercontent.com/58430460/135494751-7249cd36-c945-4cf9-be25-9612175ddaeb.png">
<img width="1142" alt="Screen Shot 2021-09-30 at 18 52 51" src="https://user-images.githubusercontent.com/58430460/135498187-76e310a4-e229-4377-a3d4-980d5381e7f0.png">

Here is the code of the yaml file:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: common
        url: https://10.0.0.X
      - cluster: development
        url: https://10.0.0.X
      # - cluster: staging
      #   url: https://10.0.0.X
      # - cluster: production
      #   url: https://10.0.0.X
  template:
    metadata:
      name: '{{cluster}}-traefik-ingress'
    spec:
      project: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: git@github.com:xxxx/gke-addons.git
        targetRevision: HEAD
        path: applications/traefik/overlays/{{cluster}}
        plugin:
          name: argocd-vault-plugin-kustomize
      destination:
        server: '{{url}}'
        namespace: traefik-system

```

**Version**

```shell
argocd: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.2+7af9dfb
  BuildDate: 2021-09-02T18:05:23Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**

```
Release server logs:

time="2021-09-30T16:12:58Z" level=info msg="received unary call /application.ApplicationService/DeleteResource" grpc.method=DeleteResource grpc.request.claims="{\"at_hash\":\ "tDcaze0WrFvrOo_bL9pWcw\",\"aud\":\"argo-cd\",\"c_hash\":\"3ap6fnJPdKiw0mCzs_MMHw\",\"email\":\",\"email_verified\":true,\"exp\":1633033761,\"iat\":1632947361,\"iss\":\"https://argocd/api/dex\",\"name\":\"Ricardo Underwood\",\"sub\":"}" grpc.request.content="name:\"infrastructure\" namespace:\"argocd\" resourceName:\"traefik-ingress\" version:\"v1alpha1\" group:\"argoproj.io\" kind:\"ApplicationSet\" force:true orphan:false " grpc.service=application.ApplicationService grpc.start_time="2021-09-30T16:12:58Z" span.kind=server system=grpc
time="2021-09-30T16:12:58Z" level=info msg="ricardo.underwood deleted resource argoproj.io/ApplicationSet 'traefik-ingress'" application=infrastructure dest-namespace=default dest-server="https://kubernetes.default.svc" reason=ResourceDeleted type=Normal time="2021-09-30T16:26:02Z" level=info msg="received unary call /application.ApplicationService/ManagedResources" grpc.method=ManagedResources grpc.request.claims="{\"at_hash\":\"tDcaze0WrFvrOo_bL9pWcw\",\"aud\":\"argo-cd\",\"c_hash\":\"3ap6fnJPdKiw0mCzs_MMHw\",\"email\":\\",\"email_verified\":true,\"exp\":1633033761,\"iat\":1632947361,\"iss\":\"https://argocd/api/dex\",\"name\":\"Ricardo Underwood\",\"sub\":\\"}" grpc.request.content="applicationName:\"infrastructure\" namespace:\"argocd\" name:\"traefik-ingress\" version:\"\" group:\"argoproj.io\" kind:\"ApplicationSet\" " grpc.service=application.ApplicationService grpc.start_time="2021-09-30T16:26:02Z" span.kind=server system=grpc

From Application Controller:

time="2021-09-30T16:39:51Z" level=info msg="Failed to watch TraefikService.traefik.containo.us on https://10.0.0.18: Resyncing TraefikService.traefik.containo.us on https://10.0.0.18 during to timeout, retrying in 1s" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch IngressRouteTCP.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch TLSStore.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"time="2021-09-30T16:39:52Z" level=info msg="Start watch MiddlewareTCP.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch ServersTransport.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch IngressRouteUDP.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch Middleware.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch IngressRoute.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch TLSOption.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:52Z" level=info msg="Start watch TraefikService.traefik.containo.us on https://10.0.0.18" server="https://10.0.0.18"
time="2021-09-30T16:39:51Z" level=info msg="Failed to watch TraefikService.traefik.containo.us on https://10.0.0.18: Resyncing TraefikService.traefik.containo.us on https://10.0.0.18 during to timeout, retrying in 1s" server="https://10.0.0.18"
```
