### ISSUE TITLE
.argocd-source-<app-name>.yaml does not get synced by argocd

### ISSUE THREAD

**Issue by albertyfwu** [argoproj/argo-cd#7333]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

tl;dr: ArgoCD is seemingly not respecting image overrides in `.argocd-source-<app-name>.yaml`. The UI shows the app as synced even though the image digest is different in the git K8s manifest vs. the running version.

Longer version:

We use `kustomization.yaml` files with image overrides to indicate following `branch-master`:
```
images:
- name: my-thing-image
  newName: account.dkr.ecr.us-west-2.amazonaws.com/my-thing
  newTag: branch-master
```

We also use `argocd-image-updater` in order to monitor ECR and `branch-master` in order to make new commits onto `master` to keep our manifests updated:
```
    argocd-image-updater.argoproj.io/image-list: backend-image=account.dkr.ecr.us-west-2.amazonaws.com/my-thing:branch-master
    argocd-image-updater.argoproj.io/backend-image.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/my-repo
```

As an example, consistently, the following file is generated correctly:

```
kustomize:
  images:
  - account.dkr.ecr.us-west-2.amazonaws.com/my-thing@sha256:asdf676768726f876d9v869w863fdfd

```

In the ArgoCD UI, the app shows as synced, but the old pod does not get deleted to create a new pod pointing to the new image.

I am using an App-of-Apps pattern.

**To Reproduce**

- Create a root Application, say, `root-app`.
- Create a child Application, say, `child-app`. Have your child Application refer to a directory (like `my-thing/overlays/staging`) that has a kustomization.yaml file with a `Deployment` with an image with tag `branch-master`.
- `kubectl apply` the root Application to your cluster.
- Commit a file `.argocd-source-child-app.yaml` inside `my-thing/overlays/staging` with the following contents:
```
kustomize:
  images:
  - account.dkr.ecr.us-west-2.amazonaws.com/my-thing@sha256:asdf676768726f876d9v869w863fdfd

```
- Wait for ArgoCD sync and see that the image is not updated.

**Expected behavior**

ArgoCD should update the pod to the new image version.

**Screenshots**

**Version**

v2.1.2

**Logs**

```
Paste any relevant application logs here.
```

**Comment by zmx** [comment]
We have also hit this. And may be related to https://github.com/argoproj/argo-cd/issues/6129

**Comment by sachinbachhav** [comment]
We are also facing same issue.

**Comment by fchiacchiaretta** [comment]
I'm also hitting this bug.

@albertyfwu In my case, inspecting via ArgoCD web interface -> App Details -> Parameters I see that ArgoCD properly import the overrides, but application shows as Synced and pod are not updated.

If I click on 'Edit' in Parameters tab, I see a 'Digest?' flag that is currently disabled for imported images overrides, and I can't enable it, do you confirm the same behaviour?

**Comment by rminderhoud** [comment]
Okay, I've discovered the root issue of the problem here and it's not an ArgoCD issue but a peculiarity of kustomize.


## Problem

Firstly, the issue stems from a setup kind of like this where the image is defined in a base as an alias and the overlay renames it:

```yaml
# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: my-app
      - image: my-app-image
```

```yaml
# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: my-app-image
  newName: mycontainer.registry.com/my-app-image
  newTag: dev
```

What happens here is that ArgoCD uses `kustomize edit set image` to set the new image and so after the kustomize overrides are applied the final kustomization will look like this:

```yaml
# merged kustomization.yaml
images:
- digest: sha256:a6fa396b885772736d53bc44089e5b03d4c12915883ecad8d2e2d1df527822a9
  name: mycontainer.registry.com/my-app-image
  newTag: dev
- name: my-app-image
  newName: mycontainer.registry.com/my-app-image
  newTag: dev
```

Notice the order, the digest appears at the start of the image list.

When running `kustomize build` on this kustomization you will see that the digest image is ignored. If you manually sort the images so digest comes after the alias rename then it works.

## Solution
Unfortunately there currently doesn't appear to be a way to make `kustomize set image` to append the image. The easiest fix is to change the deployment to use the full URL and not use an alias, e.g.

```yaml
# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - image: mycontainer.registry.com/my-app-image
```

```yaml
# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mycontainer.registry.com/my-app-image
  newTag: dev
```

This way `kubectl apply -k` will still use the desired tag but argocd can still apply the digest.

There might be another way to fix this within argocd image updater but I'm not certain.

Regards,
