### ISSUE TITLE
Self service group access to project applications

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#742]
A use case is that a user creates a project, and wants to be able to self service access to applications within the project, based on OAuth2 group claims.

Currently, the issue is that all rbac is centralized into the argocd-rbac-cm configmap, and these users would not have the permissions to edit the central rbac config.

Since it's already possible for a project admin to generate tokens for a project, it probably makes sense to also give them the ability to map user groups to the project so that they can self service access to its apps.

**Comment by jessesuen** [comment]
A new `groups` field has been added under a role, to map OIDC groups to the project role:

```
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  roles:
  - description: asdf
    groups:
    - argoproj:rbac-test
    name: my-role
    policies:
    - p, proj:default:my-role, applications, *, default/kustomize-guestbook, allow
  sourceRepos:
  - '*'
```
