### ISSUE TITLE
Canary Deployment is causing downtime

### ISSUE THREAD

**Issue by om3171991** [argoproj/argo-cd#7421]
Hi Team,

We are experience downtime for an application while deployment gets into a suspended state (Deployments for someone to do promote full).

Deployment Strategy - Canary without any traffic management.

Usecase - We have a simple nodejs deployment with 4 replica and whenever we do deployment and it gets to a suspended state, ingress associated with the application shows a blank page. As soon as, we progress and deployment is completed - everything starts working.

RolloutManifest:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: Demo
  labels:
spec:
 strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      steps:
        - setWeight: 50
        - pause: {}
        - setWeight: 50
        - pause:
            duration: 40s
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: Demo
      app.kubernetes.io/instance: Demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: Demo
        app.kubernetes.io/instance: Demo
    spec:
      containers:
        - name: demo
          image: "demo:master-890d3f1-4.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
```
Is there anyone experiencing the same or am I doing something wrong?

_Originally posted by @om3171991 in https://github.com/argoproj/argo-cd/discussions/7317_
