### ISSUE TITLE
create internal ingress controller with manifest file using argocd 

### ISSUE THREAD

**Issue by calvinShan** [argoproj/argo-cd#7428]
Hello,

I want to deploy ingress controller with argocd on aks based on this article : https://docs.microsoft.com/en-au/azure/aks/ingress-internal-ip

I need to create an application argocd like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  destination:
    name: ''
    namespace: 'common-ingress '
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx/'
    targetRevision: 4.0.6
    chart: ingress-nginx
    helm:
      valueFiles: []
  project: default
```

But I don't know how to pass the manifest file, the command line should be like this:
helm install nginx-ingress ingress-nginx/ingress-nginx -f internal-ingress.yaml

How to define the '-f internal-ingress.yaml' in argocd pls?

Thanks

**Comment by calvinShan** [comment]
@buker  thanks for your response, so how to pass this in argo pls? could you show us an example?

```
controller:
  service:
    loadBalancerIP: 10.240.0.42
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```
to install chart helm install nginx-ingress ingress-nginx/ingress-nginx -f internal-ingress.yaml
