### ISSUE TITLE
helm dependency build with repository alias fails with "no repository definition for @myhelmrepo"

### ISSUE THREAD

**Issue by srouil** [argoproj/argo-cd#7436]
**Describe the bug**

I am creating an application whose helm Chart.yaml uses a helm library chart from a repository defined using a repository alias. 
 
**To Reproduce**

1. You need to have a helm repository containing a library chart. 
2. Configure it as helm repository in Argo CD and give it a name, e.g. myhelmrepo
3. Configure an application from a git Repo whose Chart.yaml uses the helm library chart using an alias:

Chart.yaml
```
apiVersion: v2
name: dependency-test-helm
description: Helm chart
type: application
version: 1.1.0
appVersion: 0.1.0
dependencies:
- name: my-helm-library-chart
  repository: "@myhelmrepo"
  version: 0.0.1
```

**Expected behavior**

Argo CD can create the application, or if application has already been created, Argo CD displays correct sync status. 

This works correctly with Argo CD 2.0.5 but I observe the error with 2.1.3

**Screenshots**

See Logs

**Version**

argocd: v2.1.3+d855831
  BuildDate: 2021-09-29T21:51:21Z
  GitCommit: d855831540e51d8a90b1006d2eb9f49ab1b088af
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.3+d855831
  BuildDate: 2021-09-29T21:51:21Z
  GitCommit: d855831540e51d8a90b1006d2eb9f49ab1b088af
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0

**Logs**

time="2021-10-14T06:54:52Z" level=info msg="manifest error cache hit: &ApplicationSource{RepoURL:https://xxx.xxx.xx/stash/scm/example-paas/example-paas-kube.git,Path:helm,TargetRevision:deploy/lab,Helm:&ApplicationSourceHelm{ValueFiles:[values-lab-fe-01.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,},Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:,}/952aa32f62745fc9557344d528b88d0a530cb202"
71
time="2021-10-14T06:54:52Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: no repository definition for @myhelmrepo. Please add them via 'helm repo add'" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2021-10-14T06:55:52Z" grpc.service=repository.RepoServerService grpc.start_time="2021-10-14T06:54:52Z" grpc.time_ms=2.38 span.kind=server system=grpc
70

**Comment by cobexer** [comment]
I hit the same error with a different config:

`helm dependency build failed exit status 1: Error: could not find protocol handler for: alias`

my Chart.yaml looks like:
```yaml
apiVersion: v2
name: dependency-test-helm
description: Helm chart
type: application
version: 1.1.0
appVersion: 0.1.0
dependencies:
  - name: my-helm-library-chart
    repository: alias:myhelmrepo
    version: 0.0.1
```

this is a regression since this worked in 2.0 and below
