### ISSUE TITLE
[RFE] Git File Manifest Template Generator

### ISSUE THREAD

**Issue by williamcaban** [argoproj/argo-cd#7447]
## Summary

The current `Git File Generator` generates Applications template parameters using the contents of JSON files found within a specified repository.

This request for enhnacement (RFE) is to extend the `Git File Generator` (or create a new generator) to allow for the use of {{param}}-style parameters on source manifest from a Git repo and render them in-flight without requiring source modification. This is NOT to have a full templating system or DDL, it is for a simple variable substitution capability.

## Proposal

For example, consider the ability to support the following scenario:

```yaml
# Template with deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{values.basename}}'
  namespace: '{{values.namespace}}'
  labels:
    app: '{{values.basename}}'
spec:
  replicas: '{{values.replicas}}'
  selector:
    matchLabels:
      app: '{{values.basename}}'
  template:
    metadata:
      labels:
        app: '{{values.basename}}'
    spec:
      containers:
      - name: nginx
        image: '{{values.container.image}}'
        ports:
        - containerPort: '{{values.container.port}}'
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-from-template
spec:
  generators:
  - git:
      repoURL: https://repo/with/templates.git
      revision: HEAD
      templates:
        # eg: *, *.yaml, *.tmpl
        files: 'path/to/apps-from-template/deployment.yaml'
  template:
    metadata:
      name: '{{files.file-name}}'
    spec:
      project: default
      source:
        repoURL: git://git/with/templates-values.git
        targetRevision: HEAD
        # eg: *, *.json, values.json
        values: 'path/to/values-*.json'
      destination:
        server: '{{values.cluster}}'
        # Action: render `templates.files` with `source.values` to `destination.server`
```

With a `values-mytest.json` like
```json
{
    'basename':'mytest',
    'namespace':'mynamespace',
    'replicas':'3',
    'container': {
        'image':'path/to/image:abc',
        'port':'9090'
    }
}
```
