### ISSUE TITLE
Can't use ignoreDifference jqPathExpressions without jsonPointers

### ISSUE THREAD

**Issue by JrCs** [argoproj/argo-cd#7512]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

An application like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiosk
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kiosk
  ignoreDifferences:
    - kind: ClusterRole
      jqPathExpressions:
        - .rules
  project: default
  source:
    chart: mirrors/devspace/kiosk
    repoURL: harbor.example.com
    targetRevision: 0.2.9
```
is **refused** (because it said that jsonPointers key is required):

**To Reproduce**

```shell
$ kubectl -f kiosk.yaml
The Application "kiosk" is invalid: spec.ignoreDifferences.jsonPointers: Required value
```

**Expected behavior**

The manifest is accepted

**Version**

```shell
argocd-server: v2.1.5+a8a6fc8
  BuildDate: 2021-10-20T15:16:40Z
  GitCommit: a8a6fc8dda0e26bb1e0b893e270c1128038f5b0f
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```
