### ISSUE TITLE
DiffIgnoring the only annotation present leads to an empty annotation object which is still different

### ISSUE THREAD

**Issue by Rafaesp** [argoproj/argo-cd#7513]
I have the following diff in one of my applications:
![image](https://user-images.githubusercontent.com/437825/138269646-2bb42c6c-2585-4277-a88d-f1ceea0b8301.png)

I've added the following ignoreDifferences to my manifest:
```
ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
```
But the end result is still a difference:
![image](https://user-images.githubusercontent.com/437825/138269861-23f4e918-d9de-43aa-b076-6fbf4007b9da.png)

Is there a way ArgoCD can handle this case? Thank you

**Comment by nabadger** [comment]
This is causing us a few problems (especially when it happens on lots of apps). 

Are there any solutions from argo here (don't really like the idea of having a fake-annotation to work around this).

**Comment by guiguan** [comment]
Any update on this? This is so annoying

**Comment by cpmoore** [comment]
Ran into this issue today ignoring the same restarted at annotation

**Comment by Bak3y** [comment]
Ran into this today, workaround is clunky.

**Comment by alexrecuenco** [comment]
Do you have a reproducible example?

Have you tried adding the following? does it work?

```yaml
...
ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
      # ...
      - .spec.template. metadata.annotations | select( . == {} )

```
