### ISSUE TITLE
argocd app create -f apps.yaml does not create all apps.

### ISSUE THREAD

**Issue by m-yosefpor** [argoproj/argo-cd#7527]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If you have a k8s manifest with multiple `Application`s, separated with `---` (like other multiple k8s yaml definitions in 1 file) and try to create them with `argocd app create -f apps.yaml` only 1 of them is created.

**To Reproduce**

```
---
# Source: apps/templates/helm.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sth1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sth
    server: 'https://kubernetes.default.svc'
  project: sth
  source:
    repoURL: 'https://repo.git'
    targetRevision: HEAD
    path: charts1
    helm:
      valueFiles:
      - values.yaml
---
# Source: apps/templates/helm.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sth2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sth
    server: 'https://kubernetes.default.svc'
  project: sth
  source:
    repoURL: 'https://myrepo.git'
    targetRevision: HEAD
    path: charts/sth2
    helm:
      valueFiles:
      - values.yaml
```

then try:
```
$ argocd app create --upsert -f apps.yaml
application 'sth1' created
```

As you can see, only `sth1` app is created and `sth2` is not created.

**Expected behavior**

`argocd app create -f app.yaml` should create all `Application`s in the manifest.

**Version**

```shell
argocd: v2.1.2+7af9dfb.dirty
  BuildDate: 2021-09-02T21:28:55Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: dirty
  GoVersion: go1.17
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.0+d0b2d55
  BuildDate: 2021-08-20T05:30:54Z
  GitCommit: d0b2d55e3fb7fe8b17385d6687886de41651f31b
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```
