### ISSUE TITLE
ArgoCD doesn't allow using int value as array element

### ISSUE THREAD

**Issue by brsolomon-deloitte** [argoproj/argo-cd#7612]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

int values as part of an array break shit and don't allow an app to be created at all.

Related to

- https://github.com/argoproj/argo-cd/issues/4428
- https://github.com/argoproj/argo-cd/issues/7479

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  destination:
    name: ''
    namespace: adega
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/kafka
    repoURL: 'git@redacted'
    targetRevision: HEAD
    helm:
      parameters:
        - name: heapOpts
          value: '-Xmx4g -Xms4g'
        - name: livenessProbe.initialDelaySeconds
          value: '60'
        - name: persistence.size
          value: 32Gi
        - name: externalAccess.enabled
          value: 'true'
        - name: externalAccess.autoDiscovery.enabled
          value: 'true'
        - name: externalAccess.service.type
          value: NodePort
        - name: 'externalAccess.service.nodePorts[0]'
          value: 33336
        - name: rbac.create
          value: 'true'
        - name: serviceAccount.create
          value: 'true'
        - name: image.tag
          value: 2.8.1-debian-10-r31
          forceString: true
        - name: deleteTopicEnable
          value: 'true'
        - name: autoCreateTopicsEnable
          value: 'true'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

Try all of these too; same error:

```
        - name: 'externalAccess.service.nodePorts[0]'
          value: 33336
          forceString: true

        - name: 'externalAccess.service.nodePorts[0]'
          value: 33336
          forceString: false

        - name: 'externalAccess.service.nodePorts[0]'
          value: '33336'
          forceString: true
```

**Expected behavior**

I want to specify successfully `externalAccess.service.nodePorts` for kafka, https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml, but ArgoCD doesn't allow it at all.

**Screenshots**

**Version**

```shell
argocd: v2.1.3+d855831
  BuildDate: 2021-09-29T21:51:21Z
  GitCommit: d855831540e51d8a90b1006d2eb9f49ab1b088af
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```
