### ISSUE TITLE
Support "filters" in Project allow/deny lists

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#7636]
# Summary

Project allow/deny lists allows restricting resource group/kinds managed by the applications in the project. In addition to group/kinds admin should be able to specify resource level "filter" that allows filtering individual resources.

# Motivation

The allow/deny filters are required to solve the following use case:

The platform team provides Argo CD as a service to manage "addons" in multiple clusters. The end users are supposed to install custom resource definitions. Platform team wants to make sure end users  won't override accidentally pre-installed custom resource definitions in the cluster

# Proposal

Add `filter` field to the list item definition. The filter field can have `jq` expression that is used by Argo CD to check permission to manage particular resource.

```yaml
clusterResourceWhitelist:
  -group: extensions
    kind: CustomResourceDefinition
    filter:
      jq: (.spec.names.group == "argoproj.io") and .spec.names.kind == "Rollout"
```

**Comment by jessesuen** [comment]
Some comments I raised from the contributors meeting today:

1. I was questioning the choice and syntax of using jq expressions as the mechanism to validate and to see if there was something more explicit or idiomatic Kubernetes YAML based (e.g. like Kyverno).

After looking at Kyverno syntax, I feel it will be too verbose for what we are trying to do:
https://kyverno.io/docs/writing-policies/validate/

We are attempting to do something lighter weight, syntactically tight, and flexible so I think jq expressions will work great for this purpose.

2. @crenshaw-dev had suggested this be a list instead of a single item. We agreed that a list with **AND** semantics would be an improvement than a single validator.

3. I didn't bring this up in the meeting, but I think we should use the term `validation` instead of `filters`, since we are essentially performing validation and denying the sync operation, not filtering resources.

```yaml
clusterResourceWhitelist:
 - group: extensions
    kind: CustomResourceDefinition
    validation:
    - jq: (.spec.names.group == "argoproj.io") and .spec.names.kind == "Rollout"
```
