### ISSUE TITLE
Argocd ignoring serviceaccount removal from a deployment

### ISSUE THREAD

**Issue by sasikala-ks** [argoproj/argo-cd#7645]
**Describe the bug**

Argocd ignoring the change when the serviceaccountname is removed from the deployment.

**To Reproduce**
a) Apply this to the cluster using argocd.
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: nginx
  name: nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nginx-sa
  name: nginx-sa
  namespace: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-sa
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
```
b) Once it is synced, remove `serviceAccountName: nginx-sa` from the manifests, so that it will default service account by default. 

**Expected behavior**

Once the argocd synced, the live manifests should not be having `serviceAccountName: nginx-sa`

**Version**

```shell
v1.7.4 +f 
```
