### ISSUE TITLE
Add timestamp for pod logs

### ISSUE THREAD

**Issue by christianAckman** [argoproj/argo-cd#7663]
# Summary

I would like the ability to view timestamps for pod output in the logs viewer. Output would be similar to:
```
✗ kubectl logs --timestamps=true shop
2021-11-08T22:10:43.631552134Z Example app listening on port 3000!
```

# Motivation

This feature would be helpful for debugging/correlating application errors.

# Proposal

Add a button with similar functionality as _**Show pod names**_ on the log viewer to toggle timestamps on/off.

It looks like [the timestamp data already exists](https://github.com/argoproj/argo-cd/blob/0d4e40ed6a7c5f3854d47f11f30b6c0606548601/server/application/application.go#L1224).

Might need to refactor the UI to allow viewing both pod name & timestamp:

![image](https://user-images.githubusercontent.com/23055989/140963971-b53d35c8-35be-490f-9fb3-dccb4fd0da88.png)

**Comment by christianAckman** [comment]
> 

Hi @reginapizza,

Correct me if I'm wrong, but I believe those logs are from the application itself (GuestBook).

For example in my scenario I have a pod with two containers (one OpenResty sidecar). I can see the timestamp logs for the OpenResty container because they are outputted in stdout but not for the application container.

I was looking for a way to view the timestamps without having to modify the logging of the application.

**Comment by reginapizza** [comment]
hey @christianAckman! Tried reaching out to you via CNCF slack and email but maybe you haven't seen them, I was wondering if we could connect quick, I'm having some trouble finding an example of this in working environments. Lmk, thanks!

**Comment by christianAckman** [comment]
@reginapizza I found you an example for you to run. Here is an example manifest you can add to your GitOps repo:

Source Code: https://github.com/heroku/docker-nodejs-hello-world
Docker Image: https://hub.docker.com/r/heroku/nodejs-hello-world

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-hello-world
  template:
    metadata:
      labels:
        app: nodejs-hello-world
    spec:
      containers:
      - image: heroku/nodejs-hello-world
        name: nodejs-hello-world
        ports:
        - containerPort: 80
```

Results:
![image](https://user-images.githubusercontent.com/23055989/153622357-62570000-61c3-46c9-be93-b7c86546cc39.png)


Keep in mind I believe the whole source of this issue is that my application does not have structured logging with timestamps included. I understand that is standard practice and this is totally a workaround for this, but still may be a useful feature for some.
