### ISSUE TITLE
Unable to template helm charts with values.yaml or parameter

### ISSUE THREAD

**Issue by l1990790120** [argoproj/argo-cd#7667]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In my argocd, I've defined the manifest as following:

```yaml
project: xxx
source:
  repoURL: 'https://github.com/xxx.git'
  path: helm-charts/xxx
  targetRevision: xxx
  helm:
    parameters:
      - name: deployment.imageTag
        value: v1.2.3-rc
      - name: 'ingress.hosts[0].paths[0]'
        value: /
      - name: 'ingress.hosts[0].host'
        value: xxx
destination:
  server: 'https://kubernetes.default.svc'
  namespace: airflow-api
syncPolicy:
  syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  retry:
    limit: 4
    backoff:
      duration: 10s
      factor: 2
      maxDuration: 3m
```

However, when applied to actual helm chart, none of the fields in `parameters` gets used. I have also tried to pass in `valueFiles` and unable to replace the placeholder defined in the helm charts as well.

**To Reproduce**

My apologies but my repos aren't public. I haven't played with public repo just to replicate this. I have tried several days variating my manifest but unable to get the helm charts to honor my `values.yaml` or `parameters`.

**Expected behavior**

That the values in parameters can actually template in helm. If I do the same thing with `helm template ... --values ...` I was able to validate the result.

**Screenshots**

**Version**

```shell
❯ argocd version
argocd: v2.1.2+7af9dfb.dirty
  BuildDate: 2021-09-02T21:28:55Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: dirty
  GoVersion: go1.17
  Compiler: gc
  Platform: darwin/amd64
WARN[0003] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:52:04Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**

```
Paste any relevant application logs here.
```
