### ISSUE TITLE
sync errors when using jqPathExpressions (Diffing Customization)

### ISSUE THREAD

**Issue by shortsn** [argoproj/argo-cd#7683]
Hi,
unfortunately we are having trouble with the agro diff customization and did not find a working solution yet.

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

One of our Argo Deployments contains a CRD. That CRD includes certain fields that will automatically be stripped out by the kubernetes api when their values represent the default. This actually results in a difference between desired and live manifest and creates a sync loop.

example:
```
...
spec:
  versions:
    - additionalPrinterColumns:
        - description: foobar
          jsonPath: .spec.scaling.parallelism
          name: Parallelism
          priority: 0     // missing in live manifest
          type: integer          
...
```

According to the docs https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration
i was trying to exclude related fields from diffing for that very specific case using **jqPathExpressions** like:

```
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: mycustomresource.foobar.com
          jqPathExpressions:
            - .spec.versions[]?.additionalPrinterColumns[]?.priority | select(. == 0)
            - .spec.versions[]?.schema.openAPIV3Schema.properties.spec.properties.scaling.properties.parallelism.exclusiveMinimum | select(. == false)
```

This actually seems to work and does not longer complain about the diff but runs into a sync error on every second refresh:

```
Application.argoproj.io "temp-dev-test" is invalid: spec.ignoreDifferences.jsonPointers: Invalid value: "null": spec.ignoreDifferences.jsonPointers in body must be of type array: "null"
```

Unfortunately assigning jsonPointers with an empty array introduces another issue:

```
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: mycustomresource.foobar.com
          jqPathExpressions:
            - .spec.versions[]?.additionalPrinterColumns[]?.priority | select(. == 0)
            - .spec.versions[]?.schema.openAPIV3Schema.properties.spec.properties.scaling.properties.parallelism.exclusiveMinimum | select(. == false)
          jsonPointers: []
```

For some reason this is producing another sync loop on application level where the content of jqPathExpressions is constantly switching between the actual definition and nothing.

![ping-pong](https://user-images.githubusercontent.com/6273088/141296747-3a941f37-317d-436a-a1bc-d39ae04d8c57.gif)

**Expected behavior**

1. possibility to declare jqPathExpressions without jsonPointers
2. exclude fields from diff according to jqPathExpressions and stay in sync until an actual change occurs

**Version**

```shell
argocd: v2.0.1+33eaf11
  BuildDate: 2021-04-15T22:31:51Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.6+a346cf9
  BuildDate: 2021-10-28T19:59:40Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```
