### ISSUE TITLE
No matches for kind "ApplicationSet"

### ISSUE THREAD

**Issue by JimFran** [argoproj/argo-cd#7684]
Hello,

I'm trying to deploy an ApplicationSet but getting this message (I tried to deploy it several times):

```
kubectl apply -f applicationset.yml
error: unable to recognize "applicationset.yml": no matches for kind "ApplicationSet" in version "argoproj.io/v1alpha1"
```

applicationset.yml file:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      # Parameters are generated based on this cluster list, to be substituted
      # into the template below.
      elements:
      - cluster: test-aks01
        url: https://xx.94.14x.xx
      - cluster: test-aks02
        url: https://xx.171.22x.xx
  template:
    # An Argo CD Application template, with support for parameter substitution
    # with values from parameters generated above.
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/guestbook
        targetRevision: HEAD
        path: app/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
```

I also tried to install the application CRD, application-crd.yaml:

https://github.com/argoproj/argo-cd/blob/master/manifests/crds/application-crd.yaml

but seems that there is an error in the official yml file?

```
kubectl apply -f application-crd.yaml
error: error parsing application-crd.yaml: error converting YAML to JSON: yaml: line 140: mapping values are not allowed in this context
```
I have jq installed:

```
jq --version
jq-1.5-1-a5b5cbe
```

However even if i do not install that cdr it should not affect as i can see an application cdr installed in my cluster:

```
kubectl get crd -n argocd
NAME                                                        CREATED AT
applications.argoproj.io                                    2021-10-29T10:43:57Z
appprojects.argoproj.io                                     2021-10-29T10:43:58Z
azurekeyvaultsecrets.spv.no                                 2021-10-01T11:04:29Z
secretproviderclasses.secrets-store.csi.x-k8s.io            2021-09-20T14:29:45Z
secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io   2021-09-20T14:29:45Z
```

This is the manifest I used to install argoCD:

https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

Any idea?

Thanks.
