### ISSUE TITLE
Cannot sync same resource to multiple clusters

### ISSUE THREAD

**Issue by shibumi** [argoproj/argo-cd#7694]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I am managing two clusters with ArgoCD. On both of them I would like to run cert-manager.
Although I have two different application names + two different targets for both clusters, I see the following message:
![https://kurisu.shibumi.dev/share/img-2021-11-12-18-08-08.png](https://kurisu.shibumi.dev/share/img-2021-11-12-18-08-08.png)

**To Reproduce**

My two applications look like this (for the first cluster):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://CENSORED/helm-charts/cert-manager
    path: ./
    targetRevision: HEAD
    helm:
      valueFiles:
        - stage.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

For the second cluster:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://CENSORED/k8s/clusters/c-fdsvm
  project: default
  source:
    repoURL: https://CENSORED/helm-charts/cert-manager
    path: ./
    targetRevision: HEAD
    helm:
      releaseName: cert-manager
      valueFiles:
        - production.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

I should be able to install both applications on two distinct clusters.

**Version**

v2.0.5+4c94d88

**Logs**

```
time="2021-11-12T17:00:01Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: cert-manager)" application=cert-manager
time="2021-11-12T17:00:01Z" level=info msg="getRepoObjs stats" application=cert-manager build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=199 unmarshal_ms=199 version_ms=0
...... SNIP....
time="2021-11-12T17:11:41Z" level=info msg="Comparing app state (cluster: https://CENSORED/clusters/c-fdsvm, namespace: cert-manager)" application=cert-manager-production
time="2021-11-12T17:11:41Z" level=info msg="getRepoObjs stats" application=cert-manager-production build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=255 unmarshal_ms=255 version_ms=0
time="2021-11-12T17:11:41Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2021-11-12T17:00:13Z\",\"message\":\"CustomResourceDefinition/certificaterequests.cert-manager.io is part of applications cert-manager-production and cert-manager\",\"type\":\"SharedResourceWarning\"},{\"lastTransitionTime\":\"2021-11-12T17:11:41Z\",\"message\":\"CustomResourceDefinition/certificates.cert-manager.io is part of applications cert-manager-production and cert-manager\",\"type\":\"SharedResourceWarning\"},{\"lastTransitionTime\":\"2021-11-12T17:11:41Z\",\"message\":\"CustomResourceDefinition/challenges.acme.cert-manager.io is part of applications cert-manager-production and cert-manager\",\"type\":\"SharedResourceWarning\"},{\"lastTransitionTime\":\"2021-11-12T17:11:41Z\",\"message\":\"CustomResourceDefinition/clusterissuers.cert-manager.io is part of applications cert-manager-production and cert-manager\",\"type\":\"SharedResourceWarning\"},{\"lastTransitionTime\":\"2021-11-12T17:11:41Z\",\"message\":\"CustomResourceDefinition/issuers.cert-manager.io is part of applications cert-manager-production and cert-manager\",\"type\":\"SharedResourceWarning\"},{\"lastTransitionTime\":\"2021-11-12T17:11:41Z\",\"message\":\"CustomResourceDefinition/orders.acme.cert-manager.io is part of applications cert-manager-production and cert-manager\",\"type\":\"SharedResourceWarning\"},{\"lastTransitionTime\":\"2021-11-12T17:07:54Z\",\"message\":\"Failed sync attempt to d4122e89b270f7bf0a51119c5ff173be0daa472e: one or more objects failed to apply (retried 5 times).\",\"type\":\"SyncError\"}]}}" application=cert-manager-production
time="2021-11-12T17:11:42Z" level=warning msg="Skipping auto-sync: failed previous sync attempt to d4122e89b270f7bf0a51119c5ff173be0daa472e" application=cert-manager-production
time="2021-11-12T17:11:42Z" level=info msg="Update successful" application=cert-manager-production
```
