### ISSUE TITLE
Configurable download links on Help page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#7698]
# Summary

Argo CD image includes 3 binaries: linux, mac and window for x64 architecture.  The binaries can be downloaded by end-users using `download/argocd-linux-amd64` etc URLs. The URLs are discoverable using `/help` page. 

Instead of pre-bundling all kinds of binaries, it is proposed to keep only linux amd64/arm (depends on image type) and remove mac/windows. Support configuring downloadable binaries using Argo CD settings

# Motivation

Each `argocd` binary is ~100mb. With ARM we will end up having 6 binaries which is too much and not required to everyone. 

# Proposal

* The default image should have only `argocd-linux-amd64` or `argocd-linux-arm` binary as well as `/help` page should have only one link
* User should be able to configure additional binaries using `argocd-cm` ConfigMap:

```yaml
data
  # help.download. is a prefix; argocd-windows-amd64 is a downloaded file name and value is a URL
  help.download.argocd-windows-amd64: https://github.com/argoproj/argo-cd/releases/download/v2.1.6/argocd-windows-amd64.exe
  # value can be local path as well
  help.download.argocd-darwin-amd64: /additional_tools/argocd-darwin-amd64 
  # value can be prefixed with optional title
  help.download.argocd-darwin-arm: Windows ARM|/additional_tools/argocd-darwin-arm
```
