### ISSUE TITLE
Process working directory not set for invocation of `kustomize build`

### ISSUE THREAD

**Issue by lwille** [argoproj/argo-cd#7711]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When deploying `kustomize` applications, `kustomize build` is invoked using `executil.Run`.
Prior invocations do set the working directory to the path of the kustomization, however, `kustomize build` is executed within the parent processes Cwd (which defaults to `$HOME`).
This leads to problems when using [kustomize config functions](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/commands/run-fns.md).

**To Reproduce**

* The Argo CD ConfigMap contains a `kustomize.buildOptions` key with contents `--enable-alpha-plugins --enable-exec`
* The following files exist in a repository
  * kustomize/kustomization.yml
    ```yaml
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    generators:
    - ./plugin.yml
    ```
  * kustomize/plugin.yml
    ```yaml
    apiVersion: demo
    kind: CustomConfigGenerator
    metadata:
      name: my-generator
      annotations:
        config.kubernetes.io/function: |-
          exec:
            path: ./config-generator.sh
    ```
  * kustomize/config-generator.sh
    ```bash
    #!/bin/bash
    cat << YAML
    kind: ResourceList
    items:
    - kind: ConfigMap
      apiVersion: v1
      metadata:
        name: generated-config
      data:
        GENERATED_VALUE: 42
    YAML
    ```
* An Argo application is created according to the following example:
  ```yaml
  project: kustomize-plugin-demo
  repoUrl: <demo repository>
  path: ./kustomize
  source:
    kustomize: {}
  destination: # ...
  ```
**Expected behavior**

The application is synced and a ConfigMap with a key `GENERATED_VALUE` with value `42` is created.

**Actual behavior**

An error is produced, indicating that `config-generator.sh` cannot be found.

**Version**

```shell
argocd: v2.1.6+a346cf9
  BuildDate: 2021-10-28T19:59:40Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.6+c8437d4
  BuildDate: 2021-11-09T20:05:37Z
  GitCommit: c8437d465b74034a189f1061f075b89bd1cd244d
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**
couldn't execute function: fork/exec ./config-generator.sh: no such file or directory
```
Paste any relevant application logs here.
```
