### ISSUE TITLE
Mergable inline helm values

### ISSUE THREAD

**Issue by tiagomeireles** [argoproj/argo-cd#7724]
# Summary

I'd like to be able to merge inline helm values. Currently, `spec.sources.helm.values` is defined as a string which doesn't have this ability.

# Motivation

Using kustomize, I would like to have a base application with default values. Then patch cluster-specific values using overlays.

Take this example, today, I don't have a way to replace autoDiscovery.clusterName with a different value. Kustomize's patch will replace `spec.source.helm.values` entirely.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: cluster-autoscaler
      values: |
        autoDiscovery:
          clusterName: 'foo'
        extraArgs:
          balance-similar-node-groups: true
          skip-nodes-with-system-pods: false
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.9.2
```

# Proposal

How do you think this should be implemented?

I don't have strong opinions on implementations. I see three options: 
1. Introduce a new field.
1. Changing the existing field type.
1. Do nothing.

Each come with their own pro/cons.
