### ISSUE TITLE
Can not load json as helm parameters with kustomize 4.1.3 

### ISSUE THREAD

**Issue by Jojoooo1** [argoproj/argo-cd#7743]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

As I am trying to upgrage my argo to lastest version, but I came across a bug with a json params in my helm configuration that is preventing to do so.

Here is my yaml that is working fine on argo 2.0.4 but do not with the most recent kustomize version 4.1.3

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/argo/applications/rabbitmq/rabbitmq-helm.yaml
  - 
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: rabbitmq
      namespace: argocd
    patch: |-
      - op: add
        path: "/spec/source/helm/parameters"
        value:
          - name: extraSecrets.intelipoint-rabbitmq-load-definition.load_definition\.json
            value: "\n{\"rabbit_version\":\"3.8.17\",\"rabbitmq_version\":\"3.8.17\",\"product_name\":\"RabbitMQ\",\"product_version\":\"3.8.17\",\"users\":[{\"name\":\"user\",\"password_hash\":\"XXXX\",\"hashing_algorithm\":\"rabbit_password_hashing_sha256\",\"tags\":\"administrator\",\"limits\":{}}],\"vhosts\":[{\"name\":\"/\"}],\"permissions\":[{\"user\":\"user\",\"vhost\":\"/\",\"configure\":\".*\",\"write\":\".*\",\"read\":\".*\"}],\"topic_permissions\":[],\"parameters\":[],\"global_parameters\":[{\"name\":\"internal_cluster_id\",\"value\":\"rabbitmq-cluster-id-b2hMCW-7LGQ-SR8bf50jnQ\"}],\"policies\":[],\"queues\":[{\"name\":\"intelipoint_webhook_queue_dlx\",\"vhost\":\"/\",\"durable\":true,\"auto_delete\":false,\"arguments\":{\"x-queue-type\":\"classic\"}},{\"name\":\"intelipoint_webhook_queue\",\"vhost\":\"/\",\"durable\":true,\"auto_delete\":false,\"arguments\":{\"x-dead-letter-exchange\":\"intelipont_webhook_dlx\",\"x-max-length\":1000}}],\"exchanges\":[{\"name\":\"intelipoint_webhook\",\"vhost\":\"/\",\"type\":\"x-delayed-message\",\"durable\":true,\"auto_delete\":false,\"internal\":false,\"arguments\":{\"x-delayed-type\":\"direct\"}},{\"name\":\"intelipont_webhook_dlx\",\"vhost\":\"/\",\"type\":\"direct\",\"durable\":true,\"auto_delete\":false,\"internal\":false,\"arguments\":{}}],\"bindings\":[{\"source\":\"intelipoint_webhook\",\"vhost\":\"/\",\"destination\":\"intelipoint_webhook_queue\",\"destination_type\":\"queue\",\"routing_key\":\"intelipoint_webhook_external_api\",\"arguments\":{}},{\"source\":\"intelipont_webhook_dlx\",\"vhost\":\"/\",\"destination\":\"intelipoint_webhook_queue_dlx\",\"destination_type\":\"queue\",\"routing_key\":\"intelipoint_webhook_external_api\",\"arguments\":{}}]}"

```
when I try to run `kustomize build . --load-restrictor LoadRestrictionsNone`

it show the following error message: 
`kustomize build . --load-restrictor LoadRestrictionsNone
Error: accumulating resources: accumulation err='accumulating resources from 'argo': read /home/jonathan/external/intelipoint/intelipoint/argo/deploy/staging/overlays/stg/argo: is a directory': recursed accumulation of path '/home/jonathan/external/intelipoint/intelipoint/argo/deploy/staging/overlays/stg/argo': accumulating resources: accumulation err='accumulating resources from 'applications/rabbitmq': read /home/jonathan/external/intelipoint/intelipoint/argo/deploy/staging/overlays/stg/argo/applications/rabbitmq: is a directory': recursed accumulation of path '/home/jonathan/external/intelipoint/intelipoint/argo/deploy/staging/overlays/stg/argo/applications/rabbitmq': yaml: line 38: did not find expected key
`

Since it was not working I want for another type of patch:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  source:
    helm:
      parameters:
        - name: extraSecrets.intelipoint-rabbitmq-load-definition.load_definition\.json
          value: |
            {
              "rabbit_version": "3.8.17",
              "rabbitmq_version": "3.8.17",
              "product_name": "RabbitMQ",
              "product_version": "3.8.17",
              "users": [{
                "name": "user",
                "password_hash": "XXXX",
                "hashing_algorithm": "rabbit_password_hashing_sha256",
                "tags": "administrator",
                "limits": {}
              }],
              "vhosts": [{
                "name": "/"
              }],
              "permissions": [{
                "user": "user",
                "vhost": "/",
                "configure": ".*",
                "write": ".*",
                "read": ".*"
              }],
              "topic_permissions": [],
              "parameters": [],
              "global_parameters": [{
                "name": "internal_cluster_id",
                "value": "rabbitmq-cluster-id-b2hMCW-7LGQ-SR8bf50jnQ"
              }],
              "policies": [],
              "queues": [{
                "name": "intelipoint_webhook_queue_dlx",
                "vhost": "/",
                "durable": true,
                "auto_delete": false,
                "arguments": {
                  "x-queue-type": "classic"
                }
              }, {
                "name": "intelipoint_webhook_queue",
                "vhost": "/",
                "durable": true,
                "auto_delete": false,
                "arguments": {
                  "x-dead-letter-exchange": "intelipont_webhook_dlx",
                  "x-max-length": 1000
                }
              }],
              "exchanges": [{
                "name": "intelipoint_webhook",
                "vhost": "/",
                "type": "x-delayed-message",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {
                  "x-delayed-type": "direct"
                }
              }, {
                "name": "intelipont_webhook_dlx",
                "vhost": "/",
                "type": "direct",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {}
              }],
              "bindings": [{
                "source": "intelipoint_webhook",
                "vhost": "/",
                "destination": "intelipoint_webhook_queue",
                "destination_type": "queue",
                "routing_key": "intelipoint_webhook_external_api",
                "arguments": {}
              }, {
                "source": "intelipont_webhook_dlx",
                "vhost": "/",
                "destination": "intelipoint_webhook_queue_dlx",
                "destination_type": "queue",
                "routing_key": "intelipoint_webhook_external_api",
                "arguments": {}
              }]
            }

```

This worked but argo was not able to deploy it because of this errors:

![Screenshot from 2021-11-18 11-09-49(1)](https://user-images.githubusercontent.com/17641873/142431422-6309ddda-22df-434f-b209-de3f6d9b679c.png)

**To Reproduce**

download last version of Kustomize and try deploying using the yaml in this issue.

**Expected behavior**

Would deploy json as parameter in helm chart.

**Screenshots**

**Version**

```shell
not using argocd binary
```

**Logs**

```
Paste any relevant application logs here.
```
