### ISSUE TITLE
Add diff command option for application path

### ISSUE THREAD

**Issue by devholic77** [argoproj/argo-cd#7770]
# Summary
I'm using ```argocd app diff ``` command for verify argocd manifest in jenkins pipeline.
I checked the [argocd app diff documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_diff/), but there is no option for diff the live state and a helm app using new values.

For example, this application is in live state.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://my-repo.com'
    targetRevision: v0.0.1
    helm:
      parameters:
      - name: externalUrl
        value: http://example.com
  project: default
```

when changed as follows, ```argocd app diff``` command didn't catch the changes
```diff
    helm:
      parameters:
      - name: externalUrl
-      value: http://example.com
+      value: http://other-exmaple.com
```

# Motivation
 I added the code referring to [this code](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/app.go#L136-L159) for test, It worked what I want. : ) 
https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/cmd/argocd/commands/app.go#L834-L841

```diff
			if local != "" {
+ 	                        newApp, err := cmdutil.ConstructApps( {{ application_manifest_path }} , appName, labels, annotations, args, appOpts, nil)
				conn, clusterIf := clientset.NewClusterClientOrDie()
				defer argoio.Close(conn)
				cluster, err := clusterIf.Get(context.Background(), &clusterpkg.ClusterQuery{Name: app.Spec.Destination.Name, Server: app.Spec.Destination.Server})
				errors.CheckError(err)
-				localObjs := groupObjsByKey(getLocalObjects(app, local, localRepoRoot, argoSettings.AppLabelKey, cluster.ServerVersion, argoSettings.KustomizeOptions, argoSettings.ConfigManagementPlugins, argoSettings.TrackingMethod), liveObjs, app.Spec.Destination.Namespace)
+                               localObjs := groupObjsByKey(getLocalObjects(newApp, local, localRepoRoot, argoSettings.AppLabelKey, cluster.ServerVersion, argoSettings.KustomizeOptions, argoSettings.ConfigManagementPlugins, argoSettings.TrackingMethod), liveObjs, app.Spec.Destination.Namespace)
				items = groupObjsForDiff(resources, localObjs, items, argoSettings, appName)
			} else if revision != "" {
```

# Proposal

through the previous test, I think we need an option for this.
What if options like ```--local-app```are added?
