### ISSUE TITLE
Cannot read SSO issuer from different secret

### ISSUE THREAD

**Issue by MatteoJoliveau** [argoproj/argo-cd#7786]
Hello folks! I have an instance of ArgoCD that uses an external Dex (not the one bundled with ArgoCD) for SSO authentication. The Dex client configuration is stored in a Kubernetes Secret like this one:

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: dex-argocd-credentials
  namespace: argocd
type: Opaque
data:
  clientID: somethingsomething
  clientSecret: somethingsomething
  issuerURL: somethingsomething
```

The `argocd-cm` configmap references it like so:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: |
    name: SSO
    issuer: $dex-argocd-credentials:issuerURL
    clientID: $dex-argocd-credentials:clientID
    clientSecret: $dex-argocd-credentials:clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    requestedIDTokenClaims:
      email:
        essential: true
      groups:
        essential: true
  # other keys
```

I would expect ArgoCD to follow the reference to `$dex-argocd-credentials:issuerURL` and read the URL from there, instead it throws an error: 

`Failed to query provider "$dex-argocd-credentials:issuerURL": parse "$dex-argocd-credentials:issuerURL/.well-known/openid-configuration": first path segment in URL cannot contain colon`

**Version**

ArgoCD

```json
{
    "Version": "v2.1.3+d855831",
    "BuildDate": "2021-09-29T21:51:21Z",
    "GitCommit": "d855831540e51d8a90b1006d2eb9f49ab1b088af",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
time="2021-11-26T12:20:00Z" level=info msg="argocd v2.1.3+d855831 serving on port 8080 (url: https://cd.platform.emeras-solution.com, tls: false, namespace: argocd, sso: true)"
time="2021-11-26T12:20:00Z" level=info msg="0xc000b0ac00 subscribed to settings updates"
time="2021-11-26T12:20:00Z" level=info msg="Starting rbac config informer"
time="2021-11-26T12:20:00Z" level=info msg="RBAC ConfigMap 'argocd-rbac-cm' added"
time="2021-11-26T12:20:59Z" level=info msg="Initializing OIDC provider (issuer: $dex-argocd-credentials:issuerURL)"
time="2021-11-26T12:29:59Z" level=info msg="Alloc=17833 TotalAlloc=78171 Sys=74065 NumGC=12 Goroutines=141"
```

**Comment by lucianiz** [comment]
@MatteoJoliveau  did you find a workaround for this?

**Comment by tmacro** [comment]
I'm seeing the same thing with `v2.2.5+8f981cc`
```
time="2022-04-26T00:27:50Z" level=info msg="Initializing OIDC provider (issuer: $authelia-oidc-argocd-dex-client-secret:issuer)"
```

**Comment by bentocin** [comment]
I was also expecting it to work in generic and not just for `clientSecret`. Putting the issuer into the config map fixes the issue, but maybe you actually want to put the issuer into the secret.

**Comment by mewa** [comment]
@bentocin I also think this is the sane thing to do.

One thing worth pointing out is that the [documentation](https://argo-cd.readthedocs.io/en/release-2.4/operator-manual/user-management/#sensitive-data-and-sso-client-secrets) is currently wrong about it as well.
> ArgoCD knows to check the keys under data in the argocd-secret secret for a corresponding key **whenever a value in a configmap starts with $.**

**Comment by Enity** [comment]
Same thing. Cant beat it

<img width="432" alt="image" src="https://user-images.githubusercontent.com/2884517/192113834-eb98805d-8296-4c3c-99e9-360ef2826b8c.png">

**Comment by PhilStevenson** [comment]
Adding the label to secret worked for me: 

> NOTE: Secret must have label app.kubernetes.io/part-of: argocd

**Comment by stepanbaghdasaryan** [comment]
poor documentation, in values.yaml example stay nothing about label mandatory

```yaml
    # Dex configuration
    dex.config: |
      connectors:
        # GitHub example
         - type: github
           id: github
           name: GitHub
           config:
             clientID: aabbccddeeff00112233
             clientSecret: $dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
             orgs:
             - name: your-github-org
```

What is about to improve documentation?

**Comment by MasterExecuson** [comment]
Reposting from #13928, if you have the argo configMap with `$<k8s_secret_name>:<key>`, make sure your `secret` has two labels: 

```
app.kubernetes.io/part-of: argocd
app.kubernetes.io/name: <k8s_secret_name>
```

I was having a hard time having to figure this out with CSI driver secrets. Got the reference checking the existing labels on the default `argocd-secret`...

**Comment by mardonner** [comment]
Also having this issue. None of the above things fixed it. Deploying argocd via helm (7.8.2) and providing the secrets via external-secrets-operator.

**Comment by sunggun-yu** [comment]
```yaml
app.kubernetes.io/part-of: argocd
app.kubernetes.io/name: <k8s_secret_name>
```

not working for me on v2.14.10+5feb8c2

**Comment by denispeyrusaubes** [comment]
same issue, using v3.1.4+20dd73a (chart v8.3.5) : 

In argocd-server pod's logs : 

```
... msg="config referenced '$oidc-argocd-secret.oidc-okta-clientId', but key does not exist in secret"  
... msg="config referenced '$oidc-argocd-secret.oidc-okta-clientSecret', but key does not exist in secret"   
```

External Secret Operator's config :

```
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: okta-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore  
  target:
    name: oidc-argocd-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          app.kubernetes.io/name: oidc-argocd-secret
      type: Opaque
  data:

    - secretKey: oidc-okta-clientSecret
      remoteRef:
        key: admin
        property: argocd_okta_secret

    - secretKey: oidc-okta-clientId
      remoteRef:
        key: admin
        property: argocd_okta_client_id
```

Secret generated by ESO from previous defintion :

```
apiVersion: v1
kind: Secret
data:
  oidc-okta-clientId: thevalue
  oidc-okta-clientSecret: thevalue
metadata:
  name: oidc-argocd-secret
  namespace: argocd
  annotations:
    reconcile.external-secrets.io/data-hash: 1a21fa621b34ee81d7ac341056be0ccf8777affef1ab6d5280688db3
  labels:
    app.kubernetes.io/name: oidc-argocd-secret
    app.kubernetes.io/part-of: argocd
    reconcile.external-secrets.io/created-by: 6d2a58230de7d44905115db2eda1be9b419c50ddf1a4f89046f0a6a2
    reconcile.external-secrets.io/managed: "true"

type: Opaque
```


and using it in my values.yml file : 

```
...
      oidc.config: |
      name: Okta
      issuer: https://blah
      clientID: $oidc-argocd-secret.oidc-okta-clientId
      clientSecret: $oidc-argocd-secret.oidc-okta-clientSecret
...
```

All is ok if i hardcode both clientID et clientSecret in my values.yml file
