### ISSUE TITLE
Namespaces issue in ArgoCD

### ISSUE THREAD

**Issue by JimFran** [argoproj/argo-cd#7787]
Hi Team,

I am deploying two applications that originally where in different namespaces through ArgoCD Helm. Also ArgoCD will manage itself specifying argocd as a third application.

However after applying my override values yml file, when ArgoCD is being Syncing the applications appear in the dashboard and later on disappear from the ArgoCD dashboard. Most probably because I am trying to deploy them in different namespaces. Our organization needs to have those application in different namespaces.

ArgoCD deploy correctly the applications but they disappear from the ArgoCD Dashboard and also ArgoCD remains Out of Sync.

To deploy the applications I am using application files located i different folders.

This is my folder structure:

![image](https://user-images.githubusercontent.com/65667266/143418699-1954da22-70a5-4812-acb9-d50d9c70b3d1.png)

ArgoCD Helm is located in -->       argocd/argocd/argocd-helm
Override values yml file is located in -->  argocd/argocd/
application yml files --> argocd/applicationfiles/
applications --> argocd/applications/

This is my override values yml file:

```
## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
server:

##  extraArgs:
##    - --rootpath=/argocd

  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  configEnabled: true

  config:
    url: https://argocd.k8s.loandepotdev.io
    application.instanceLabelKey: argocd.argoproj.io/instance

    repositories: |
      - type: git
        url: https://xxx@dev.azure.com/xxx/xxx/_git/deployments
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
    
    oidc.config: |
      name: Azure
      issuer: https://login.microsoftonline.com/xxx/v2.0
      clientID: xxx
      clientSecret: $oidc.azuread.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

  additionalApplications: 

    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - ../override_values.yml
        path: argocd/argocd/argocd-helm
        repoURL: https://xxx@dev.azure.com/xxx/xxx/_git/deployments
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

    - name: sonarqube
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        path: argocd/applicationfiles/sonarqube
        repoURL: https://xx@dev.azure.com/xxx/xx/_git/deployments
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

    - name: prometheus
      namespace: argocd 
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        path: argocd/applicationfiles/prometheus
        repoURL: https://xx@dev.azure.com/xxxe/xx/_git/deployments
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

  rbacConfig:
    policy.csv: |
      g, "xxx", role:admin
      g, "xxx", role:admin
      g, "xxx", role:admin
      g, "xxx", role:admin
    policy.default: role:readonly
    
configs:
  credentialTemplates:
    https-creds:
      url: https://xxx@dev.azure.com/xxx/xxx/_git/deployments
      username: argocd
      password: xxx
```

and these are the application yml files for prometheus and sonarqube

sonarqube:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/applications/sonarqube
    repoURL: https://xxx@dev.azure.com/xxx/xxx/_git/adeployments
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
```

prometheus

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/applications/prometheus
    repoURL: https://xxx@dev.azure.com/xxx/xxx/_git/deployments
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
```

Any idea?

Thank you in advance.

### Related helm chart

argo-cd

### To Reproduce

1. Clone git repo from Azure
2. cd to ArgoCD helm repo
3. helm dependency update (for redis-ha dependency)
4. delete .tar from .helmignore
5. helm install argocd ./argocd-helm --namespace=argocd --create-namespace -f override_values.yml
6.  Sync manually ArgoCD

### Expected behavior

To have all the applications  in ArgoCD Dashboard.

### Screenshots

Folder structure:

![image](https://user-images.githubusercontent.com/65667266/143419258-3aad08a4-318c-48f0-9612-6657497e4cb4.png)

When I SYN first time ArgoCD:

![image](https://user-images.githubusercontent.com/65667266/143419409-270509ab-0958-4a7d-b341-9a2642d28d7d.png)

After SYNC (it remains in Out of Sync even if I try to SYN again)

![image](https://user-images.githubusercontent.com/65667266/143419486-ebb6a7d9-7762-4dc0-96b7-73c8fa1e7998.png)
