### ISSUE TITLE
dashboard login middleware needed?

### ISSUE THREAD

**Issue by APoniatowski** [argoproj/argo-cd#7810]
### Discussed in https://github.com/argoproj/argo-cd/discussions/7795

<div type='discussions-op-text'>

<sup>Originally posted by **APoniatowski** November 29, 2021</sup>
Hi there,

I was wondering, does the dashboard utilize the same secrets as the actual application? as I can login via the CLI client, but when trying to log into the UI/dashboard, the admin credentials do not work and neither does the newly created account (which I created via CLI successfully).

Does traefik need any additional auth middleware, by any chance?  I'm using traefik with let's encrypt via cert manager, also using argocd v2.1.7

edit:  by port-forwarding with kubectl, I managed to log in. This time it gave me the application's login and not the login prompt which doesn't log me in at all.  What changes should I make in my ingressroute, to not get the login prompt, but actually get to the application?

ingress yaml:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.mydomain.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.mydomain.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-cert
```
via ingress:
![image](https://user-images.githubusercontent.com/39518296/143875200-511003ea-bc96-44f1-b6ea-b4315ee733ab.png)

via port foward:
![image](https://user-images.githubusercontent.com/39518296/143875338-95548812-ee65-4a8a-8c53-0f62b8fb1102.png)
</div>
