### ISSUE TITLE
Support helm remote values from private repository

### ISSUE THREAD

**Issue by jmclean-starburst** [argoproj/argo-cd#7819]
# Summary

I would like to have the ability to reference a value file, from a remote private repository which uses an environment variable in the URL string. An example of this is below:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: my-application
    namespace: deploy
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: my-project
    source:
        repoURL: https://harbor.mycompany.net/chartrepo/infra
        targetRevision: 1.1.4
        chart: my-application
        helm:
            valueFiles:
                - https://${GITHUB_TOKEN}@raw.githubusercontent.com/org/repo/ref/path-to-values-file1.yml?uniq=51B9CF53-EC28-4311-8070-8C4F24ED655B
                - https://${GITHUB_TOKEN}@raw.githubusercontent.com/org/repo/ref/path-to-values-file2.yml?uniq=51B9CF53-EC28-4311-8070-8C4F24ED655B
    destination:
        name: control-plane
        namespace: my-ns
    syncPolicy:
        automated:
           prune: true
           selfHeal: true
        syncOptions:
            - CreateNamespace=true
```

This will currently not work as the `${GITHUB_TOKEN}` does not inject environment variables that are already present within the `argocd-repo-server` pod; rather ArgoCD will interpret `${GITHUB_TOKEN}` as a literal value.

NOTE: I have been able to get this working by using https://github.com/jkroepke/helm-secrets v3.11.0 by setting the env variable `HELM_SECRETS_URL_VARIABLE_EXPANSION` on the `argocd-repo-server`

More info: https://github.com/jkroepke/helm-secrets/blob/main/docs/Feature%20Flags.md

The one gotcha with the above, and not sure if this is just an error w/ remote helm values referencing in general or using `helm-secrets`, but I noticed the UI for the application CR details (parameter tab) does not show the values that were pulled in from the remote sources.

@jkroepke for FYI on the above

# Motivation

Be able to reference remote helm values from a private repository since there is currently no way to reference values local to a repository that is not the source of the helm chart (https://github.com/argoproj/argo-cd/issues/5826). A workaround to this pattern is to do helm dependent charts, where the Umbrella chart references a child chart dependency from a remote repo; this is more of a hack than a workaround

# Proposal

Allow the usage of GITHUB tokens to be injected into a remote URL reference within the `valueFiles` mapping.
