### ISSUE TITLE
Ignore Differences doesn't ignore differences 

### ISSUE THREAD

**Issue by zonnie** [argoproj/argo-cd#7820]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm want to integrate HPA and as a setup phase I want to add the `IgnoreDifferences`
Initially I'm only trying to modify the `Deployment` with `kubectl edit` and ArgoCD auto-syncs and terminates the new replicas.

**To Reproduce**

Application example

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bla-env
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  project: bla-1
  source:
    repoURL: git@github.com:bla
    targetRevision: HEAD
    path: path/to/helm/chart
    helm:
      releaseName: bla-1
```

Edit, using `kubectl edit`, a `Deployment` that is created as a result of the above `Application` and set `replicas` to `4`

ArgoCD immediately terminates the new replicas that resulted from the ⬆️ edit

**Expected behavior**

New replicas will not be terminated and ignored by ArgoCD

**Version**

```
argocd: v2.1.6+a346cf9.dirty
  BuildDate: 2021-11-01T02:05:06Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: dirty
  GoVersion: go1.17.2
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.1.6+a346cf9
```

**Logs**

No relevant logs that I know of, not sure where to look for relevant logs
