### ISSUE TITLE
Upgrade v2.0 to v2.1 causes Applications to enter Unknown status

### ISSUE THREAD

**Issue by Demonsthere** [argoproj/argo-cd#7831]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Upgrading Argo from 2.0 to 2.1 causes all of our running applications to enter Unknown status and be unusable (no changes detected, no actions performed on them). Upgrades within 2.0 do not cause any issue whatsoever. 

**To Reproduce**

In our setup we install Argo via a fluxcd HelmRelease and create our Applications using the ApplicationSet controller. 
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argocd
      version: '3.10.0'
      # version: '3.26.12'
  interval: 1m0s
  releaseName: argocd
  targetNamespace: gitops
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      metrics: 
        enabled: true
        serviceMonitor:
          enabled: true
    repoServer:
      metrics: 
        enabled: true
        serviceMonitor:
          enabled: true
    server:
      metrics: 
        enabled: true
        serviceMonitor:
          enabled: true
      config: 
        resource.customizations: |
          argoproj.io/Application:
            ignoreDifferences: |
              jqPathExpressions:
              - '/spec/syncPolicy'
    configs:
      argocdServerAdminPassword: REDACTED
```

**Expected behavior**

Upgrade of ArgoCD does not change the state of running Applications

**Logs**

```
time="2021-12-02T12:40:37Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=owc-bootstrap-foo
time="2021-12-02T12:40:37Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-12-02T12:40:37Z" level=info msg="Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions"
time="2021-12-02T12:40:37Z" level=info msg="Skipping auto-sync: application status is Unknown" application=owc-bootstrap-foo
time="2021-12-02T12:40:37Z" level=info msg="No status changes. Skipping patch" application=owc-bootstrap-foo
time="2021-12-02T12:40:37Z" level=info msg="Reconciliation completed" application=owc-bootstrap-foo dest-name= dest-namespace=gitops dest-server="https://REDACTED" fields.level=1 time_ms=2
```

**Version**

```shell
Paste the output from `argocd version` here.
```
