### ISSUE TITLE
OutOfSync for HPA, due not sorted yaml keys

### ISSUE THREAD

**Issue by knusperkrone** [argoproj/argo-cd#7846]
**Describe the bug**

When adding a HPA, with memory and cpu limits, then argoCD application appears `OutOfSync`.

This is because of not consequent sorting the `live` manifest and the `desired` manifest.

**To Reproduce**

Applying a hpa like:

```yaml
metrics:
  {{ if $root.Values.resources.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $root.Values.resources.hpa.targetCPUUtilizationPercentage }}
  {{ end }}
  {{ if $root.Values.resources.hpa.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $root.Values.resources.hpa.targetCPUUtilizationPercentage }}
  {{ end }}
```

**Expected behavior**

ArgoCd shoulnd't mark such projects `OutOfSync`

**Screenshots**

![Screenshot from 2021-12-03 10-57-26](https://user-images.githubusercontent.com/20244674/144583534-4a7349bb-47dd-417b-959d-ee97f4033a82.png)

**Version**

Argo CD
v2.1.7+a408e29
