### ISSUE TITLE
ArgoCD not respect (change) a resourece namespace already defined

### ISSUE THREAD

**Issue by lfdominguez** [argoproj/argo-cd#7857]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

A resource (RoleBinding) created with namespace changed (to the one where argocd is deployed), even when namespace is specified on that resource.

**To Reproduce**

1. Change `argocd-cm` ConfigMap to add `--enable-helm` to kustomize options, this works ok.
2. Create a kustomization.yaml application with  
```yaml
namespace: keycloak
helmCharts:
- name: keycloak
  repo: https://codecentric.github.io/helm-charts
  valuesFile: values.yaml
  releaseName: keycloak
```
3. That generate some resources (tested executing kustomization locally), one of them is 
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 12.0.1
    helm.sh/chart: keycloak-15.1.0
  name: keycloak
  namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak
subjects:
- kind: ServiceAccount
  name: keycloak
  namespace: keycloak
```
4. But ArgoCD change that namespace by the one where argocd is deployed (argocd)
![image](https://user-images.githubusercontent.com/5604131/144685083-27a75744-c4a2-4e07-9a50-d592c32a0435.png)
I changed directly using `kubectl edit` the current namespace to fix it and set the correct value (`keycloak`), but ArgoCD set in `OutOfSync` trying to change to the wrong namespace `argocd`  

**Expected behavior**

ArgoCD respect the namespace defined on resource

**Version**

```
2.1.7
```

**Comment by lfdominguez** [comment]
Workaround:

1. Create a RoleBinding identical to the generated by helm one:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak
subjects:
- kind: ServiceAccount
  name: keycloak
```
2. Create a patch on the kustomization.yaml:
```yaml
patchesStrategicMerge:
  - rbac/rolebinding.yaml
```
3. Now ArgoCD not change the namespace and the application is synced
![image](https://user-images.githubusercontent.com/5604131/144686985-1a42ce68-5d53-41be-8829-fd669d8b5917.png)

Why with this workaround that generate the same .yaml RoleBinding works? It's like kustomization command on argocd controller generate the RoleBinding helm yaml without namespace and without the patch merge then the current namespace is set.

**Comment by crankl** [comment]
We have the same issue in our cluster. 
When upgrading from 2.0.0 to 2.1.0 suddenly all namespaces were out of sync because namespace isolation was active.
After adding the label `argocd.argoproj.io/managed-by: argocd`, all the necessary roles were added to the project but the rolebindings were missing
```
NAME                                   CREATED AT
argocd-argocd-application-controller   2021-12-06T12:37:35Z
argocd-argocd-dex-server               2021-12-06T12:37:35Z
argocd-argocd-redis-ha                 2021-12-06T12:37:35Z
argocd-argocd-server                   2021-12-06T12:37:35Z
``` 

In the controller logs we found the following error 
```
2021-12-06T12:37:35.412Z        INFO    controller-runtime.manager.controller.argocd    Reconciling ArgoCD      {"reconciler group": "argoproj.io", "reconciler kind": "ArgoCD", "name": "argocd", "namespace": "argocd", "namespace": "argocd", "name": "argocd"}
2021-12-06T12:37:35.412Z        INFO    controller_argocd       reconciling status
2021-12-06T12:37:35.412Z        INFO    controller_argocd       reconciling roles
2021-12-06T12:37:35.450Z        INFO    controller_argocd       reconciling rolebindings
2021-12-06T12:37:35.456Z        ERROR   controller-runtime.manager.controller.argocd    Reconciler error        {"reconciler group": "argoproj.io", "reconciler kind": "ArgoCD", "name": "argocd", "namespace": "argocd", "error": "error reconciling roleBinding for \"argocd-application-controller\": roles.rbac.authorization.k8s.io \"argocd-argocd-application-controller\" already exists"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214
``` 

As far as I understood it, the rolebindings which are created here, are located in the argocd namespace (the one argocd is deployed into) but the rolebindings should be created in the target project, which was recently labeled with `argocd.argoproj.io/managed-by: argocd`.

**Comment by barzog** [comment]
I have the similar problem with following helm chart:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: awx-operator-1.0.0
  name: awx-operator-awx-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awx-operator-awx-manager-role
subjects:
  - kind: ServiceAccount
    name: awx-operator-controller-manager
    namespace: '{{ .Release.Namespace }}'
```

field 'namespace' in 'subjects' after argocd deploy have value 'argocd'. 
Solved it using [lfdominguez](https://github.com/lfdominguez) workaround, but slightly different (not rewrite rolebinding totally, but just replace namespace with following kustomize snippet:
```
patches:
- target:
    kind: RoleBinding
    name: awx-operator-awx-manager-rolebinding
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: awx
```
