### ISSUE TITLE
Can't delete `argocd` namespace when Argo CD is self-managed

### ISSUE THREAD

**Issue by dhess** [argoproj/argo-cd#7860]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When Argo CD is self-managed (i.e., there's an `Application` installed in the `argocd` namespace that's keeping Argo CD itself up-to-date), it doesn't seem possible to delete the `argocd` namespace cleanly. `kubectl delete namespace argocd` hangs indefinitely. The status of the delete always looks something like this:

```
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "creationTimestamp": "2021-12-05T21:13:26Z",
        "deletionTimestamp": "2021-12-05T21:55:36Z",
        "labels": {
            "kubernetes.io/metadata.name": "argocd"
        },
        "name": "argocd",
        "resourceVersion": "18950",
        "uid": "189daefa-db73-43bc-a9e6-c7c513e50f25"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2021-12-05T21:55:41Z",
                "message": "All resources successfully discovered",
                "reason": "ResourcesDiscovered",
                "status": "False",
                "type": "NamespaceDeletionDiscoveryFailure"
            },
            {
                "lastTransitionTime": "2021-12-05T21:55:41Z",
                "message": "All legacy kube types successfully parsed",
                "reason": "ParsedGroupVersions",
                "status": "False",
                "type": "NamespaceDeletionGroupVersionParsingFailure"
            },
            {
                "lastTransitionTime": "2021-12-05T21:55:41Z",
                "message": "All content successfully deleted, may be waiting on finalization",
                "reason": "ContentDeleted",
                "status": "False",
                "type": "NamespaceDeletionContentFailure"
            },
            {
                "lastTransitionTime": "2021-12-05T21:55:41Z",
                "message": "Some resources are remaining: applications.argoproj.io has 1 resource instances, pods. has 12 resource instances",
                "reason": "SomeResourcesRemain",
                "status": "True",
                "type": "NamespaceContentRemaining"
            },
            {
                "lastTransitionTime": "2021-12-05T21:55:41Z",
                "message": "Some content in the namespace has finalizers remaining: resources-finalizer.argocd.argoproj.io in 1 resource instances",
                "reason": "SomeFinalizersRemain",
                "status": "True",
                "type": "NamespaceFinalizersRemaining"
            }
        ],
        "phase": "Terminating"
    }
}
```

I've tried any number of ways of managing the installation, creating the `Application` resource, specifying a finalizer or not, and various `syncPolicy` settings. In every permutation I've tried so far, I'm unable to delete the `argocd` namespace cleanly, and once I do manage to find the magic `kubectl patch` command or whatever else it takes to actually cause the `argocd` namespace to disappear, once I recreate it, there is inevitably some leftover resource in the newly-created namespace from the previous instance.

Does anyone have a working example of a self-managed Argo CD installation that can be deleted cleanly?

**Version**

```shell
argocd: v2.1.6
  BuildDate: unknown
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: clean
  GitTag: v2.1.6
  GoVersion: go1.16.9
  Compiler: gc
  Platform: linux/amd64
```

**Comment by dhess** [comment]
Answering my own question, this seems to work:

`gitops/argocd/argocd.yaml`:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/argocd
    repoURL: https://github.com/your/repo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
```

`apps/argocd/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.7/manifests/ha/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.2.0/manifests/install.yaml
components:
  - https://github.com/argoproj-labs/argocd-extensions/manifests
namespace: argocd
```

Bootstrap Argo CD installation:

```sh
kubectl create namespace argocd
cd apps/argocd && kustomize build . | kubectl apply -n argocd -f -
```

Set up the repo creds for your `https://github.com/your/repo.git`.

Now use `kubectl` to apply the `Application` manifest above:

```sh
cd gitops/argocd/ && kubectl apply -f argocd.yaml -n argocd
```

Wait for the `argocd` app to sync and become healthy. Then you can safely delete the namespace:

```sh
$ kubectl delete namespace argocd 
namespace "argocd" deleted
```

I haven't tried this with other applications in the `argocd` namespace but presumably those can be deleted manually if necessary before deleting the `argocd` namespace and closing the door on the way out.

There may be other ways to achieve this, but this is the only thing I've gotten to work so far after hours of trying. It would be helpful to have this documented somewhere.
