### ISSUE TITLE
sync windows do not show inherited ones from global projects

### ISSUE THREAD

**Issue by KipsasJaujoj** [argoproj/argo-cd#7876]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Sync windows inherited from global projects are not shown on project's window view. They are also not printed when using `argocd proj windows list <project>` command.

Sync windows are actually working OK and denies/allows syncing but not being able to see until when they are active/inactive is a bad experience. Also, if there is local sync windows (defined in that particular project) it can cause even more confussion as application will not be able to sync even if one can see that `allow` window is present and active (and wise-versa).

**To Reproduce**

1. Create new project with any `syncWindows` definition which will be your global project. It's name can be `global-project-test`.
2. Create new project with any `label` you can refer to later (can be `a: b`). It's name can be `local-project-test`.
3. Add following `data` to `argocd-cm`:
```
  globalProjects: |-
    - labelSelector:
        matchExpressions:
          - key: a
            operator: In
            values:
              - b
      projectName: global-project-test
```
4. See if your `local-project-test` project shows same sync windows as `global-project-test`

**Expected behavior**

`local-project-test` project shows same sync windows as `global-project-test` (or more if it had some sync windows defined in it's own `spec`).

**Screenshots**

On application view, sync window is shown as active:
![image (3)](https://user-images.githubusercontent.com/8336391/145035889-6c5059fb-28ce-4f1d-935f-01c618eb2fdb.png)
However, going to project's window view, shows empty list with `Project has no sync windows`statement:
![image (4)](https://user-images.githubusercontent.com/8336391/145036036-6d0932cb-5ff4-46f6-82ea-cbbb9316bbe2.png)
If the project has local (not inherited) sync windows set up, you are able to see these.

**Version**

```shell
argocd-server: v2.1.6+a346cf9
  BuildDate: 2021-10-28T19:59:40Z
  GitCommit: a346cf933e10d872eae26bff8e58c5e7ac40db25
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0
```

**Logs**

n/a

**Comment by keithchong** [comment]
Hi @KipsasJaujoj , I can't seem to reproduce this.  Once I added the label a=b, and then I switched over to the WINDOWS tab, I see the sync window populated.

**Comment by KipsasJaujoj** [comment]
@keithchong Just to double check: you are not checking sync window on the global project, are you? I'll try this exercise on more time :)

**Comment by KipsasJaujoj** [comment]
Hi @keithchong I am not able to get WINDOWS tab populated. Could you clarify you checked that on your inheriting project? Also, which version did you use? I used `v2.1.6`.

Maybe second eyes on my projects will help. `projects.yaml` (stripped destination part):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global-project-sandbox1
  namespace: argocd
spec:
  syncWindows:
  - applications:
    - '*'
    duration: 0.5h
    kind: allow
    manualSync: true
    schedule: 0 5 * * 1-5
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local-inheriting-project-sandbox1
  namespace: argocd
  labels:
    a: b
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: ""
```
