### ISSUE TITLE
Secret issue in argoCD Helm deployment

### ISSUE THREAD

**Issue by JimFran** [argoproj/argo-cd#7878]
Hello team,

this is not really a bug but I was not sure how to ask about this issue.

When deploying ArgoCD through Helm I cannot find any way to specify the KeyVault (from Azure) for the secret needed when integratin ArgoCD with SSO. 

The secret is called **$oidc.azuread.clientSecret** and I should use KeyVault.
This variable is usually deployed inside argocd-secret.yml. However, when using Helm I am not sure how can I deploy this variable using Azure KeyVault.

This is the piece of the code inside vaued.yml from argocd helm that shows the variable name:

```
  config:
    # Argo CD's externally facing base URL (optional). Required when configuring SSO
    url: https://argocd.example.com
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance

    # DEPRECATED: Please instead use configs.credentialTemplates and configs.repositories
    # repositories: |
    #   - url: git@github.com:group/repo.git
    #     sshPrivateKeySecret:
    #       name: secret-name
    #       key: sshPrivateKey
    #   - type: helm
    #     url: https://charts.helm.sh/stable
    #     name: stable
    #   - type: helm
    #     url: https://argoproj.github.io/argo-helm
    #     name: argo

    # oidc.config: |
    #   name: AzureAD
    #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
    #   clientID: CLIENT_ID
    #   clientSecret: $oidc.azuread.clientSecret
    #   requestedIDTokenClaims:
    #     groups:
    #       essential: true
    #   requestedScopes:
    #     - openid
    #     - profile
    #     - email
```

Any advice would be really appreciated.

Thank you.

**Comment by alias-rahil** [comment]
Not sure if this is the best way but one way is to maintain the argocd-secret entirely yourself. For that you will need to disable the auto-generation of the secret:

```
# argocd values.yaml
configs:
    secret:
      createSecret: false
```

You can now create argocd-secret with the extra data keys that you'd like.

PS: `admin.password` and `server.secretkey` are mandatory keys that you will have to maintain with your other extra keys.
