### ISSUE TITLE
Unhelpful error message when a kind does not exist for some api version

### ISSUE THREAD

**Issue by bgolding355** [argoproj/argo-cd#7889]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When you add a yaml file with a kind that does not exist for your chosen api version you get an error of the form:

```
ComparisonError: rpc error: code = Unknown desc = failed to unmarshal manifest: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in <Uploaded YAML>
```

This message is confusing, and doesn't describe the actual problem. Namely that this value for the key `kind` does not exist in this api.

**To Reproduce**

1) Add the following `yaml`
```
apiVersion: v1
items:
  - apiVersion: batch/v1
    kind: kindThatDoesNotExistInBatchV1
    spec:
      someKey: someValue
```

2) Observe that the sync fails. 

3) Click on the red `X` in the "Last Sync Result" box

4) Observe the text corresponding to the key `Message`

**Expected behavior**

A error message that better reflects the problem.

**Screenshots**

![2021-12-08-151018_1026x94_scrot](https://user-images.githubusercontent.com/60831565/145279455-5b4b3d76-99be-4b70-a415-ff6531c82b69.png)

![2021-12-08-152844_1279x440_scrot](https://user-images.githubusercontent.com/60831565/145279645-47f67c29-c6de-4033-9031-623aed584682.png)

**Version**

```shell
{
    "Version": "v2.2.0+78e256e",
    "BuildDate": "2021-12-03T22:39:09Z",
    "GitCommit": "78e256eef3dc5fdb8553e58c024d234d8e354e20",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jsoref** [comment]
This can also happen if you create an argocd application that points to a nonexistent directory (because your directory and where you put the files for the application don't match).

**Comment by kuisathaverat** [comment]
An empty block between `---` delimiters causes the issue in my case. The manifest is completely valid for Kubernetes but not for argoCD

```yaml
---
# This block causes the issue
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  secret: YWRtaW4=
```

**Comment by KarBroden** [comment]
In my case I added an incorrect ignoreDifferencees which resulted in `"Object 'Kind' is missing in '{}'"`

```
- group: "rbac.authorization.k8s.io"
   kind: Role
   namespace: "utilities"
   jqPathExpressions:
     - .
```
