### ISSUE TITLE
Gitlab webhook does not work if targetRevision contains slash symbol

### ISSUE THREAD

**Issue by lienerieksta** [argoproj/argo-cd#7906]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
We have a naming scheme for our branches that follows the pattern `environment/cluster`. After upgrading ArgoCD from v2.0.0 to v2.1.5 the the gitlab webhook stopped to trigger the app refresh. When I check the argocd-server logs I see that the webhook is received but no further action is taken: 
```
time="2021-12-10T15:45:18Z" level=info msg="Received push event repo: https://git.private.tld/configuration/argocd, revision: environment/cluster, touchedHead: false"
```
Then I created a new git branch from the existing one and replaced the slash `/` with a dash `-` in the branch name to get `environment-cluster`. I also edited the existing Application manifest by changing the same one symbol in targetRevision field to match the freshly created branch. I pushed a commit and the app refresh was requested as expected:
```
time="2021-12-10T15:48:37Z" level=info msg="Received push event repo: https://git.private.tld/configuration/argocd, revision: environment-cluster, touchedHead: false"
time="2021-12-10T15:48:37Z" level=info msg="Requested app 'app-of-apps' refresh"
```
On clusters that are still on v2.0.0+f5119c0 webhooks from branches containing slash `/` work like a charm. 
Upgrading argocd to v2.1.7 did not solve the issue. 

**To Reproduce**
1. Create a GitLab repository with a branch name containing `/` i.e `environment/cluster`
2. Create Application that references that branch:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: app-of-apps
    repoURL: https://git.private.tld/configuration/argocd.git
    targetRevision: environment/cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
```
3. Configure a GitLab webhook to trigger on push 
4. Push a commit to fire the webhook. 

**Expected behavior**
Sync initiated. 
When checking argocd-server logs I should see:
```
time="2021-12-10T15:48:37Z" level=info msg="Received push event repo: https://git.private.tld/configuration/argocd, revision: environment/cluster, touchedHead: false"
time="2021-12-10T15:48:37Z" level=info msg="Requested app 'app-of-apps' refresh"
```

**Version**
Confirmed with both 2.1.5 and 2.1.7
![image](https://user-images.githubusercontent.com/42056862/145606845-691ef932-51e0-4d72-a3d5-d0c6895456ff.png)
![image](https://user-images.githubusercontent.com/42056862/145604075-19f62707-745d-459a-9d92-4db4e4e18d97.png)
