### ISSUE TITLE
Allow configuring system-wide ignore differences for managed fields managers for all resources

### ISSUE THREAD

**Issue by leoluz** [argoproj/argo-cd#7926]
# Summary

Provide the possibility for users to configure ArgoCD to ignore differences made by managed fields managers for all resources (api-group + kind) at the system level.

# Motivation

With the introduction of `Application.spec.ignoreDifferences.managedFieldsManagers` it is now possible to configure ArgoCD to trust specific managers which is how a controller is identified in `managedFields`. Kubernetes controllers can change the state of different resources living in the cluster. If the user wants to trust controllers for all Applications so it doesn't conflict with the desired state they have to configure it resource by resource.

# Proposal

Introduce a new configuration at the system level to allow the user to specify a list of managers that will be trusted for all resources:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations.ignoreDifferences.managedFieldsManagers: |
    - kube-controller-manager
```

**Comment by leoluz** [comment]
Resource override expects the 4th key split to refer to the resource identifier (GK) and the string value to be able to marshal into a `v1alpha1.OverrideIgnoreDiff{}` in case of `ignoreDifferences`. 

To accommodate the existing logic the updated proposal is to define the keys as:

```yaml
data:
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
    - kube-controller-manager
```
