### ISSUE TITLE
cli login using google sso not working (but works fine in UI)

### ISSUE THREAD

**Issue by GiGurra** [argoproj/argo-cd#7940]
Installed 2.2.0 using helm 

Our config (again, which works fine in the UI)

```yaml
server:
  ingress:
    enabled: true
  extraArgs:
    - --insecure # we terminate ssl ourselves
  config:
    oidc.config: |
      name: Google
      issuer: https://accounts.google.com
      clientID: **************
      clientSecret: $argo-google-sso-secret:clientSecret
      requestedScopes:
        - openid
        - profile
        - email
```

**Steps to reproduce**
1. Install argocd using helm (with google sso and also add localhost as valid redirect url for sso app)
2. verify it works logging through the ui
3. verify that local account cli logins work
4. try sso login through the cli

` argocd login *********:443 --grpc-web --name test --sso`

You get a callback to localhost

`http://localhost:8085/auth/callback?state=TqQMDCypqh&code=`

```
oauth2: cannot fetch token: 400 Bad Request
Response: {
  &#34;error&#34;: &#34;invalid_request&#34;,
  &#34;error_description&#34;: &#34;client_secret is missing.&#34;
}
```

![image](https://user-images.githubusercontent.com/1761299/146153245-4e65e8fb-eb6f-4279-b6e2-8d5d2d0b04aa.png)

FYI: I also did the same through a kubectl port-forward direct to the pod, just to bypass any proxy influence in between - but got the exact same error message

**A clear and concise description of what you expected to happen.**

sso should work for cli login :)

**argo-cd server logs**

```
time="2021-12-15T08:42:34Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2021-12-15T08:42:34Z" span.kind=server system=grpc
time="2021-12-15T08:42:34Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-12-15T08:42:34Z" level=info msg="Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions"
time="2021-12-15T08:42:34Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-12-15T08:42:34Z" grpc.time_ms=7.596 span.kind=server system=grpc
```
