### ISSUE TITLE
Service with allocateLoadBalancerNodePorts set are always OutOfSync

### ISSUE THREAD

**Issue by andrein** [argoproj/argo-cd#7941]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Starting with Kubernetes 1.20 there is alpha support to disable the nodePorts for LoadBalancer services using the allocateLoadBalancerNodePorts field. When using this field, the service resource is always OutOfSync.

**To Reproduce**

```
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  allocateLoadBalancerNodePorts: false
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
  sessionAffinity: None
  type: LoadBalancer
```

**Expected behavior**

allocateLoadBalancerNodePorts should not be displayed as OutOfSync

**Screenshots**

![image](https://user-images.githubusercontent.com/52871/146181260-e48159d3-a3d7-4805-804c-55b7eea7f324.png)

**Version**

```shell
argocd: v2.2.0+6da92a8.dirty
  BuildDate: 2021-12-15T02:09:11Z
  GitCommit: 6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.0+6da92a8
  BuildDate: 2021-12-14T18:09:18Z
  GitCommit: 6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Logs**

```
None
```
