### ISSUE TITLE
Unable to use Multiple Project Scoped Repositories from a single file

### ISSUE THREAD

**Issue by nathanwong91** [argoproj/argo-cd#7972]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Trying out the new feature released in v2.2.0 - Project Scoped Repositories.
Using the example in the docs works as intended, however when attempting to add more than 1 URL/Git Repo per file in the URL field it fails. Possibly others have tried this and had more success!

**To Reproduce**

I've tried different variations of adding to the URL from 
```yaml
  url: |
    https://charts.helm.sh/stable
    https://github.com/elastic/helm-charts
---
  url: |-
    https://charts.helm.sh/stable
    https://github.com/elastic/helm-charts
---
  url:
    - https://charts.helm.sh/stable
    - https://github.com/elastic/helm-charts
---
```
and more. They do apply with no issues but it appears like this 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/59549970/146458103-b92d5936-1161-4e15-82a1-1429fc167789.png">
with an error
`application repo https://charts.helm.sh/stable is not permitted in project 'test-project'`
I have also tried using `data` instead of `stringData`

If I create a separate file.
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-test-project-apps
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  project: test-project
  name: argocd-example
  url: https://charts.helm.sh/stable
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-test-project-apps-2
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  project: test-project
  name: argocd-example
  url: https://github.com/elastic/helm-charts
```
You get 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/59549970/146458315-d58acf71-88c8-4f98-b3f6-a2ef77199181.png">

And the app in question can access the repo

**Expected behavior**

This is a new feature so it could be by design or just a slight limitation. I would like to add more than 1 repo per file or it will become unmanageable. It could be fine adding 1 secret per repo per project as this feature was intended to bridge the gap between developers waiting for us to add the repo into the config map and a self service method.

**Version**

```shell
argocd version
argocd: v2.2.0+6da92a8.dirty
  BuildDate: 2021-12-15T02:09:11Z
  GitCommit: 6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/amd64
```
