### ISSUE TITLE
Argo syncing/healing on a "temporary" state state and fails

### ISSUE THREAD

**Issue by sebastien-coavoux** [argoproj/argo-cd#7982]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Hi there !

I've try to asked for insights on the [CNCF slack](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1639673227225000 ) and I feel like I might be experiencing an unexpected behavior. 

I have an Argo Application deploying a chart use to bootstrap a couple of namespaces. Typically the chart generate several Namespace objects and a couple of namespace related objects (LimitRange, ResourceQuota, RoleBinding). 
When deploying for the first time, or adding a new namespace everything is find but on a specific scenario, Argo sync fails and manual sync is needed. 

The use-case is the following : A tenant of the namespace wants to clean it up, and manually runs a `kubectl delete ns test-ns-0`. During the deletion phase (~10s), Argo is quick on detecting that an object is deleted. Most of the time it is one of the namespace related objects (LimitRange, ResourceQuota, RoleBinding).

Problem is : while argo resync to create the single missing object, deletion occurs and all objects are missing, including the namespace itself. This leads to failure to sync, then argo retry 5 times (default) to sync this specific object (not all of them) and get stuck in Sync Failure. 

I have tried the following : 
* sync wave -1 on the namespace
* createNamespace=True in sync option
* self heal in sync option
* hooks, but hooks are meant to get deleted, which I don't want 
* manual sync : works as expected but not automated

**To Reproduce**

I have reduced the issue to simply a bunch of K8s object in a big yaml file (remove the helm part) : 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns-0
 # I tried a couple of things to fix it, without luck
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: test-ns-0-default
  namespace: test-ns-0
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-ns-0-quota
  namespace: test-ns-0
spec:
  hard:
    limits.cpu: "10"
    limits.memory: 100Gi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-ns-0-view-rb
  namespace: test-ns-0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: test-group

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns-1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: test-ns-1-default
  namespace: test-ns-1
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-ns-1-quota
  namespace: test-ns-1
spec:
  hard:
    limits.cpu: "10"
    limits.memory: 100Gi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-ns-1-view-rb
  namespace: test-ns-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: test-group
```
* Add that into a git repo and let argocd sync it
* Delete one of the ns : `kubectl delete test-ns-0`
* Observe argo syncing on the LimitRange object (or any of the object in the NS)
* Observe argo keep on retrying on the exact same object, without realizing that there is more to sync on

**Expected behavior**

Argo could "extend" its retry scope / refresh its state and understand that there are more objects to fix / heal on. 
Argo to fix the problem itself and not require manual intervention

**Screenshots**

![Retry on single object](https://user-images.githubusercontent.com/60757725/146571804-ea02cee6-b149-4793-9d0f-0e4d937b724d.png)
![Sync failure](https://user-images.githubusercontent.com/60757725/146571805-2c156fad-6ac1-4c0f-9462-03ee81dc62cf.png)
![All objects missing](https://user-images.githubusercontent.com/60757725/146571806-cff1c713-5a4d-46cf-93fc-b46b40a46e1d.png)

**Version**

```json
{
    "Version": "v2.1.6+a346cf9",
    "BuildDate": "2021-10-28T19:59:40Z",
    "GitCommit": "a346cf933e10d872eae26bff8e58c5e7ac40db25",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```
