### ISSUE TITLE
Unnecessary pod restart following replicaSet downscale via values.yaml

### ISSUE THREAD

**Issue by joeynaor** [argoproj/argo-cd#8010]
**Describe the bug**

I'm deploying an Helm chart through Argo. The chart has a built in replicaSet in its values.yaml, where each replica is a single pod. When scaling down from 2 replicas to 1 by editing the values and pushing to git, I see pod 2 being terminated as expected. However, I then see pod 1 being terminated as well and started again. 

**To Reproduce**

1. Create the following Application YAML (app-artifactory.yaml) and push it to a Git repo:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-test
  namespace: argocd # the namespace of the ArgoCD deployment itself
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

  source:
    chart: 'artifactory'
    repoURL: 'https://charts.jfrog.io/'
    targetRevision: 107.27.9
    helm:
      #### Artifactory values.yaml ####
      values: |
        artifactory:
          joinKey: 011b61f5c6a5928d4489df5fe6f120569c29c9e9dafb01f720c61853a3d90e2b
          masterKey: ce2dcb873c3094d5dd8e7a7136158e4f31866d802435306c1855a7213853ee34
          replicaCount: 2

        databaseUpgradeReady: true
        unifiedUpgradeAllowed: true

        postgresql:
          postgresqlPassword: password
```
2. Create an App for the Git repo and point it to the directory (--path) where app-artifactory.yaml resides:
```
argocd app create joey-git --repo https://github.com/joeynaor/argo-tests.git --path jfrog --dest-server https://kubernetes.default.svc --dest-namespace default --sync-policy automated --self-heal
```
3. Wait for all pods to be ready. You should see 2 replica pods - **artifactory-test-0** and **artifactory-test-1**.
4. Change 'replicaCount' from 2 to 1 in app-artifactory.yaml and push it to Git.
5. Pay close attention to the pods
6. The "excess" pod (artifactory-test-1) is terminated successfully
7. The first pod (artifactory-test-0) is also terminated and started again, unnecessarily.

**Expected behavior**

When the same chart goes through downscaling using 'helm upgrade' or FluxCD, pod 1 is not restarted, resulting in the expected downscale behavior which preserves the purpose of high availability.

**Version**
```shell
argocd: v2.2.0+6da92a8.dirty
  BuildDate: 2021-12-15T02:41:44Z
  GitCommit: 6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/amd64
```
