### ISSUE TITLE
Improve `the server could not find the requested resource` message

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#8017]
# Summary

# Motivation

<details><summary>If a user has some static resources</summary>

https://raw.githubusercontent.com/cert-manager/website/af4632143ef001f4a4fa2c946504c462b760dc7b/content/en/docs/tutorials/acme/example/production-issuer.yaml

```
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: root@example.com
   privateKeySecretRef:
     name: letsencrypt-staging
   solvers:
   - http01:
       ingress:
         class:  nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: root@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class:  nginx
```
</details>

<details><summary>And they have an argocd helm managed system</summary>

from https://cert-manager.io/v1.5-docs/installation/helm/:
```yaml
name: cert-manager
apiVersion: v2
appVersion: "1.0"
description: Cert Manager
version: 1.5.2
dependencies:
  - name: cert-manager
    version: 1.5.2
    repository: https://charts.jetstack.io
```
</details>

<details>

Here's the after upgrade (which triggers the user unhelpful error message):
```
name: cert-manager
apiVersion: v2
appVersion: "1.0"
description: Cert Manager
version: 1.6.1
dependencies:
  - name: cert-manager
    version: 1.6.1
    repository: https://charts.jetstack.io
```

# Proposal

How do you think this should be implemented?
