### ISSUE TITLE
Documents around syncing options and selfHeal have non-obvious behavior

### ISSUE THREAD

**Issue by wimo7083** [argoproj/argo-cd#8040]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

A namespace that was created by argocd, through the app-of-app pattern, which is then deleted using kubectl will have the argocd UI show as "CURRENT SYNC STATUS: OutOfSync", and "LAST SYNC RESULT: "Sync OK". But will fail to sync if the application is synced to the current repo HEAD.

https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automated-sync-policy

> An automated sync will only be performed if the application is OutOfSync. Applications in a Synced or error state will not attempt automated sync.

https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-self-healing

> By default, changes that are made to the live cluster will not trigger automated sync.

These two statements appear to conflict, I am unsure if this "OutOfSync" for "Current Sync Status" is a bug, or this is a documentation error.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

0. obtain 2 clusters named `parent`, and `child`
1. Configure the parent cluster to be the argocd primary cluster, and obtain the child cluster IP values.
2. Add the child argocd cluster to the parent cluster
3. Apply the following manifests to the parent arogcd cluster.
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-gke-dev
  namespace: argocd
spec:
  description: DEV environment gke
  clusterResourceWhitelist:
  - group: ''
    kind: 'Namespace'
  - group: 'apiextensions.k8s.io'
    kind: 'CustomResourceDefinition'
  - group: 'rbac.authorization.k8s.io'
    kind: 'ClusterRole'
  - group: 'rbac.authorization.k8s.io'
    kind: 'ClusterRoleBinding'
  - group: 'storage.k8s.io'
    kind: 'CSIDriver'
  destinations:
  - namespace: 'gke'
    server: https://<HIDDEN>
  sourceRepos:
  - https://github.com/<HIDDEN>
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-gke-gke-dev
  namespace: argocd
spec:
  destination:
    name: dev-cluster-17c8db74
    namespace: gke
  project: cluster-gke-dev
  source:
    path: kubernetes/cluster/dev/gke
    repoURL: https://github.com/<HIDDEN>
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
...
```
Add files to repo:

```bash
# REPO:/kubernetes/airflow/dev/gke/gke.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: gke
...
```

4. Apply both manifests, and verify namespace exists
5. Delete the gke namespace from the child cluster. And "refresh"
   - CURRENT SYNC STATUS will show "OutOfSync"
   - LAST SYNC RESULT will show "Sync OK"
   

**Expected behavior**

Clarity around interactions of self-heal and automated syncing. If I push a commit to a repo that doesn't modify the manifests, there is different behavior than the controller watching for changes to the file.

**Screenshots**

**Version**

```shell
$ argocd version --server argocd.corp.apexclearing.com:443
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:04:04Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.2+7af9dfb
  BuildDate:
  GitCommit:
  GitTreeState:
  GoVersion:
  Compiler:
  Platform:
  Ksonnet Version:
  Kustomize Version:
  Helm Version:
  Kubectl Version:
```

**Logs**

```
Paste any relevant application logs here.
```
