### ISSUE TITLE
Application syncPolicy retry is backward incompatible between v2.1.x and v2.2.x in Declarative configuration

### ISSUE THREAD

**Issue by CarpathianUA** [argoproj/argo-cd#8055]
```
argocd-server: v2.2.1+122ecef
```

When defining a manifest for Applciation, we set a customized retry limit only, e.g.:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sample
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  source:
    repoURL: <REDACTED>
    chart: <REDACTED>
    targetRevision: <REDACTED>
    helm:
      valueFiles:
        - configs/sample-values.yaml
      values: |
        global:
          sample:
            image:
              repository: <REDACTED>
              tag: <REDACTED>

        ingress:
          web:
            host: sample.public.local
          external:
            web:
              host: sample.public.com

  # Sync policy
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
```

According to the docs and CLI, there are defaults for other retry parameters like:
```
 --retry-backoff-duration duration       Retry backoff base duration. Input needs to be a duration (e.g. 2m, 1h) (default 5s)
      --retry-backoff-factor int              Factor multiplies the base duration after each failed retry (default 2)
      --retry-backoff-max-duration duration   Max retry backoff duration. Input needs to be a duration (e.g. 2m, 1h) (default 3m0s)
```

This worked flawlessly in v2.1.x.

Today we've upgraded our ArgoCD to v2.2.1. After upgrade:
* App Details button produces a stack trace - I assume it can't render `Retry` fields.
* Manual Sync requires explicit values for `backoff`:
<img width="577" alt="Screenshot 2021-12-29 at 17 43 19" src="https://user-images.githubusercontent.com/5362436/147689313-76ea7f56-49ec-483f-aa00-ab349b2e5a1e.png">

Then we've set all retry-related values within all of Application's manifests:
```
...
    retry:
      limit: 2
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m0s"
...
```
BTW: There is nothing in documentation about `backoff` values - I had to went over Application CRD specs.

**To Reproduce**

* Define Application manifest in v2.1.x with retry limit only (without `backoff` section), apply it
* Upgrade ArgoCD to v2.2.x
* Go to ArgoCD UI and click App Details button
* Try to Sync App manually

**Expected behavior**

Such changes must be backward compatible

I assume it's related to https://github.com/argoproj/argo-cd/pull/7252/files

P.S. If there is retry values inheritance within App Of Apps concept? So we can set retry values just for root App instead of setting them for all child Apps.

Thanks in advance!
