### ISSUE TITLE
Can't use repocreds declarative way with ArgoCD v2.0.4

### ISSUE THREAD

**Issue by cheesimp** [argoproj/argo-cd#8061]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to add a [credentials template](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials) for my github app in a [declarative way](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#github-app-repositories).
I configured my resources as shown in the doc and I have 2 secret resources for:

- `argocd.argoproj.io/secret-type: repo-creds` containing my github app creds
- `argocd.argoproj.io/secret-type: repository` containing only the url of my repo

However, I don’t see any of these resources in the argocd UI, and when I try to create an app, I get the error Unable to create application: application spec is invalid: InvalidSpecError: repository not accessible: authentication required.
I cannot list them neither when using `argocd repocreds lis`

**To Reproduce**

I just deploy ArgoCD using the helm chart `3.7.0`.
I am using manifests as shown in the doc.

```
apiVersion: v1
data:
  githubAppID: 
  githubAppInstallationID: 
  githubAppPrivateKey: 
  url: 
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
    secrets-store.csi.k8s.io/managed: "true"
  name: argocd-secret-github-app
  namespace: argocd
type: Opaque
---
apiVersion: v1
data:
  url:
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: first-repo
  namespace: argocd
type: Opaque
```

**Expected behavior**

I should be able to  list the repocreds and use the repository to create an app.

**Screenshots**

**Version**

```shell
argocd: v2.2.1+122ecef.dirty
  BuildDate: 2021-12-17T18:11:03Z
  GitCommit: 122ecefc3abfe8b691a08d9f3cecf9a170cc8c37
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```
Paste any relevant application logs here.
```
