### ISSUE TITLE
keycloak documentation groupname syntax error 

### ISSUE THREAD

**Issue by edib** [argoproj/argo-cd#8074]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

**Describe the bug**

[In documentation / Configuring ArgoCD Policy](https://argo-cd.readthedocs.io/en/latest/operator-manual/user-management/keycloak/)
```
kubectl edit configmap argocd-rbac-cm 
```
must be like following, otherwise it does not work. 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, /ArgoCDAdmins, role:admin
```
