### ISSUE TITLE
Automate SBOM generation

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#8081]
# Summary

Automate [SBOM](https://www.linuxfoundation.org/blog/what-is-an-sbom/) generation and include it as part of release artifacts.

# Motivation

SBOM would be useful for end-users and partners to quickly find out which components are used by Argo CD and help to identify components that may be subject to security vulnerabilities, catch components with incompatible licenses etc.

# Proposal

Implement a script that would produce markdown document with the table that includes list of components, version and license. The release [workflow](https://github.com/argoproj/argo-cd/blob/master/.github/workflows/release.yaml) should use the script to generated SBOM document and attach it to the Github release.

**Comment by leoluz** [comment]
I did a quick investigation about how to implement this using existing tools. The SPDX format is the standard used for producing SBOM documents. I [this github action](https://github.com/philips-software/spdx-action) that will generate a SPDX file automatically inspecting the repository using [ORT](https://github.com/oss-review-toolkit/ort) which is compatible with go projects.

An example on how to use the github-action would be:
```yaml
  - uses: actions/checkout@v2
  - uses: actions/setup-java@v1
    with:
      java-version: '11.0.13'
  - name: Create spdx-file
    id: spdx-builder
    uses: philips-software/spdx-action@v0.9.1.1
    with:
      project: argocd
      mode: ort
  - uses: actions/upload-artifact@v2
    with:
      name: licenses
      path: ${{ steps.spdx-builder.outputs.spdx-file }}
```

**Comment by alexec** [comment]
Might be worthwhile looking into this:

https://github.com/kubernetes-sigs/bom

Used by Kubernetes and ISTIO

**Comment by leoluz** [comment]
I gave up on the philips-software/spdx-action idea as documentation is lacking and tooling is very complex. 
I'm currently giving `https://github.com/spdx/spdx-sbom-generator` a try as it is much simpler and is a community supported spdx generator in Go

**Comment by leoluz** [comment]
this is a similar github action job that uses sigs.k8s bom suggested by @alexec 
```yaml
jobs:
  spdx-sbom-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - run: pwd
      - name: Generate SBOM (spdx)
        id: spdx-builder
        run: |
          go install sigs.k8s.io/bom/cmd/bom@v0.2.1
          bom generate -o bom.spdx .
          echo "::set-output name=spdx-file::$(realpath bom.spdx)"
      - uses: actions/upload-artifact@v2
        with:
          name: licenses
          path: ${{ steps.spdx-builder.outputs.spdx-file }}
```
