### ISSUE TITLE
Issue with plugin and git-crypt

### ISSUE THREAD

**Issue by gevraud** [argoproj/argo-cd#8114]
Hello,

We are trying to use the new plugin management v2 with ArgoCD 2.2.0 on Openshift 4.8

We created a sidecar container containing git-crypt, gpg-agent and gpg. This image is called argocd-tools.

We use ansible + kustomize to deploy the argocd config.

Here is the config of the kustomize patching :  

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          image: argoproj/argocd:v{{ argocd_version }}
          command:
            - uid_entrypoint.sh
            - argocd-repo-server
            - --redis
            - argocd-redis:6379
            - --loglevel
            - debug
          env:
            - name: ARGOCD_EXEC_TIMEOUT
              value: 4m
          volumeMounts:
            - mountPath: /home/argocd
              name: gpg-key
            - mouuntPath: /tmp
              name: tmp
        - name: encrypted-yaml
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          image: repository.com/argocd-tools:8.5-214
          imagePullPolicy: Always
          command: [/var/run/argocd/argocd-cmp-server]
          volumeMounts:
            - mountPath: /home/argocd/gpg-keys
              name: gpg-key
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: encrypted-yaml-cm-plugin
            - mountPath: /tmp
              name: tmp`
      volumes:
        - name: tmp
        - name: gpg-key
          secret:
            secretName: argo-gpg-key
        - name: encrypted-yaml-cm-plugin
          configMap:
            name: encrypted-yaml-cm-plugin
```

The plugin.yaml config :

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: encrypted-yaml-cm-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: encrypted-yaml-cm-plugin
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args: ["export GNUPGHOME=/home/argocd/.gnupg; export HOME=/home/argocd; eval $(gpg-agent --daemon); gpg --import /home/argocd/gpg-keys/argo.key; git crypt unlock"]
      generate:
        command: [sh, -c]
        args: ["find . -name '*.yaml' -exec cat {} \\;"]
      discover:
        find:
          command: [ sh, -c, "ls ../../.git-crypt" ]
      allowConcurrency: false
      lockRepo: true
```

.gitattributes is encrypting every *secret.yaml.* 

The application we created in argo just checked a directory in the repository with a file secret.yaml file.

We got this error in ArgoCD GUI:

```
rpc error: code = Internal desc = Failed to checkout 18a25ed27811a5c6a4735164842154a504d338ad: `git checkout --force 18a25ed27811a5c6a4735164842154a504d338ad` failed exit status 128: "/usr/bin/git-crypt" clean: 1: /usr/bin/git-crypt: not found error: external filter '"/usr/bin/git-crypt" clean' failed 127 error: external filter '"/usr/bin/git-crypt" clean' failed fatal: src/clusteradmin/logstash-kafka-client-key.encr.txt: clean filter 'git-crypt' failed
```

If I connect to the sidecar pod and I move to the /tmp/repo_uri.git , I can see that the secret in uncrypted.
But the repo-server seems to use git-crypt every time we refresh the argo application.

I was expecting that only  the sidecar container uses git-crypt but it seems, the repo-server also uses it. As git-crypt is linked to git, I guess that each time the repo-server does a checkout, it needs the git-crypt to unlock the yaml files.

Any clue on this ?

Regards
