### ISSUE TITLE
when I am using ha-install it giving error for redis

### ISSUE THREAD

**Issue by rampatnaik** [argoproj/argo-cd#8122]
I have run

kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.2/manifests/ha/install.yaml

Warning  FailedScheduling  15s (x20 over 19m)  default-scheduler  0/2 nodes are available: 2 node(s) didn't match pod affinity/anti-affinity rules, 2 node(s) didn't match pod anti-affinity rules.

I have 2 nodes running .

This error for redis

argocd-redis-ha-haproxy-7bd6656877-zzss9   0/1     Pending
argocd-redis-ha-server-2                   0/2     Pending   0

**Comment by jgwest** [comment]
Hi @rampatnaik , the HA installation will require at least three different nodes due to pod anti-affinity roles in the specs: https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/

What is the configuration of the cluster you are attempting to install to?

**Comment by kgyovai** [comment]
I'm encountering a similar issue with 3 nodes.

Warning  FailedScheduling  0s (x8 over 6m45s)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity rules, 3 node(s) didn't match pod anti-affinity rules.

app.kubernetes.io/name=argocd-redis-ha-haproxy

**Comment by Rami-Y** [comment]
Any resolution or work around to fix this error?
I am also encountering the same issue/error after I upgraded to argocd2.3.2 version. redis ha proxy prod getting failed with the error. our Kubernetes environment is AWS EKS.
reason: FailedScheduling
message:  0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity rules, 3 node(s) didn't match pod anti-affinity rules.
Source: default-scheduler

**Comment by tooptoop4** [comment]
did u solve?

**Comment by ckazimie** [comment]
Same error here with 3 worker nodes trying to install argocd 2.4.10 og 2.4.12

**Comment by vhsantos** [comment]
Add one extra node (04 in total) fixed this issue for us !!!:-(

**Comment by warstrolo** [comment]
I have the same issue on 3 nodes deployement, but what is really wierd that with an other cluster with also 3 nodes I'm not having the issue.

**Comment by an-tex** [comment]
this happens during an argo update on a three node HA cluster. this is due to the (kubernetes) default setting of `maxUnavailable: 25%` on a `kind:Deployment` with `strategy/type:RollingUpdate`. thus the rolling update is not able to terminate any of the existing three pods due. a workaround could be to apply the following patch

```yaml
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-redis-ha-haproxy
    spec:
      strategy:
        rollingUpdate:
          # due to rolling update in combination with anti affinity rules and nodes count=replica count
          maxUnavailable: 34%
```

this allows to reduce the running pods to 2 and performing the rolling upgrade without being blocked by the anti affinity rules

**Comment by adjain131995** [comment]
This issue still persists on fresh installation as well. Did we find any solution to this?

**Comment by K3ndu** [comment]
Any updates about this?

**Comment by jcjveraa** [comment]
I would say that @an-tex's solution stands, although it might be nice for the argo team to include this in the default HA-setup helm chart? 

@an-tex style of patching is deprecated now in Kustomize. An updated snippet:

```yaml
patches:
  - patch:  |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ignored
      spec:
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1 # use an integer value, not a percentage - this is a lot more precise
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=argocd-redis-ha-haproxy"
```

**Comment by junsung-cho** [comment]
```
redis-ha:
  enabled: true
  # ...
  haproxy:
    enabled: true
    # ...
    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
```
If you using helm chart, add last 4 lines into `values.yaml`.
