### ISSUE TITLE
Cannot deploy kube-prometheus-stack helm chart (Prometheus Operator CRD). metadata.annotations: Too long: must have at most 262144 bytes,unable to recognize "/dev/shm/682053370"

### ISSUE THREAD

**Issue by shinebayar-g** [argoproj/argo-cd#8128]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD Cannot deploy [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) helm chart. Specially `prometheuses.monitoring.coreos.com` CRD is not installed.

**To Reproduce**

1. Install [ArgoCD](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd) by helm chart `v3.29.5`
2. Install [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) helm chart `v30.0.0` using ArgoCD helm chart's `server.additionalApplications[]` option.

**Expected behavior**

Deploy kube-prometheus-stack helm chart by ArgoCD

**Screenshots**

![image](https://user-images.githubusercontent.com/3091558/148792892-5e8861bf-19ae-4e62-9d82-8554cb16ca1a.png)
![image](https://user-images.githubusercontent.com/3091558/148794198-13c4d137-2dee-4673-af70-d658277a761d.png)

**Version**

```shell
❯ argocd version
argocd: v2.2.2+03b17e0
  BuildDate: 2022-01-01T06:27:52Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.2+03b17e0
```

**Logs**

```

Failed sync attempt to 30.0.0: one or more synchronization tasks completed unsuccessfully, reason: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes,unable to recognize "/dev/shm/682053370": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1" (retried 5 times).
```

Generated `Application` crd from helm values.

```yml
❯ kubectl get app kube-prometheus-stack -n argocd -o yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"finalizers":["resources-finalizer.argocd.argoproj.io"],"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"kube-prometheus-stack","namespace":"argocd"},"spec":{"destination":{"namespace":"monitoring","server":"https://kubernetes.default.svc"},"ignoreDifferences":[{"group":"apps","jsonPointers":["/spec/replicas"],"kind":"Deployment"}],"info":[{"name":"url","value":"https://prometheus-community.github.io/helm-charts"}],"project":"default","source":{"chart":"kube-prometheus-stack","helm":{"releaseName":"kube-prometheus-stack","values":"alertmanager:\n  alertmanagerSpec:\n    retention: 168h\n    storage:\n      volumeClaimTemplate:\n        spec:\n          storageClassName: gp2\n          accessModes: [\"ReadWriteOnce\"]\n          resources:\n            requests:\n              storage: 5Gi\n    resources:\n      limits:\n        cpu: 100m\n        memory: 400Mi\n      requests:\n        cpu: 100m\n        memory: 400Mi\ngrafana:\n  resources:\n    limits:\n      cpu: 100m\n      memory: 400Mi\n    requests:\n      cpu: 100m\n      memory: 400Mi\nprometheus:\n  prometheusSpec:\n    retention: 30d\n    retentionSize: 45GB\n    resources:\n      limits:\n        cpu: 250m\n        memory: 1000Mi\n      requests:\n        cpu: 250m\n        memory: 1000Mi\n    storageSpec:\n      volumeClaimTemplate:\n        spec:\n         storageClassName: gp2\n         accessModes: [\"ReadWriteOnce\"]\n         resources:\n           requests:\n             storage: 50Gi"},"repoURL":"https://prometheus-community.github.io/helm-charts","targetRevision":"30.0.0"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["Validate=true","CreateNamespace=true","PrunePropagationPolicy=foreground","PruneLast=true"]}}}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    kind: Deployment
  info:
  - name: url
    value: https://prometheus-community.github.io/helm-charts
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      values: |-
        alertmanager:
          alertmanagerSpec:
            retention: 168h
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp2
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
            resources:
              limits:
                cpu: 100m
                memory: 400Mi
              requests:
                cpu: 100m
                memory: 400Mi
        grafana:
          resources:
            limits:
              cpu: 100m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 400Mi
        prometheus:
          prometheusSpec:
            retention: 30d
            retentionSize: 45GB
            resources:
              limits:
                cpu: 250m
                memory: 1000Mi
              requests:
                cpu: 250m
                memory: 1000Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                 storageClassName: gp2
                 accessModes: ["ReadWriteOnce"]
                 resources:
                   requests:
                     storage: 50Gi
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 30.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
```

**Comment by jgwest** [comment]
https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes


For the CRD is invalid error, see the [Skip Dry Run for new custom resources types](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types), which describes the case where CRDs are . However, I would have thought that Argo CD would automatically skip dry run since the CRD is clearly contained within the set of Application resources.

You can also try disabling the validate sync option:
```
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
```

**Comment by jgwest** [comment]
Dupe of #820

**Comment by shinebayar-g** [comment]
That was correct. Regular `kubectl apply -f https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml` command fails with `The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes` error.

**Comment by shinebayar-g** [comment]
For reference:  Adding `Replace=true` fixers too large Prometheus CRD problem but breaks helm hooks.
![image](https://user-images.githubusercontent.com/3091558/148851824-d7eed6a1-7ce6-4878-b8ae-5c2f8e41177f.png)

![image](https://user-images.githubusercontent.com/3091558/148851736-f2238311-02f1-4489-9b48-13ee0b317c99.png)

Looks like I can't deal with this helm chart..

**Comment by dorroddorrod** [comment]
Same issue, any updates?

**Comment by VladoPortos** [comment]
Hmm tried today, same issue.

**Comment by goolzerg** [comment]
Same issue

**Comment by PaulWen** [comment]
The following article solved it for me: https://blog.ediri.io/kube-prometheus-stack-and-argocd-23-how-to-remove-a-workaround

**Comment by VladoPortos** [comment]
@PaulWen I have solved it for now by deploying the whole thing, waiting for it to fail and then clicking on the offending CRD and sync with replace. However, this is not a good solution, replace should not be used, it can be dangerous. It can cause issue (not in this case, but in DB deployment or something similar you can lose data)

**Comment by dnnnvx** [comment]
> @PaulWen I have solved it for now by deploying the whole thing, waiting for it to fail and then clicking on the offending CRD and sync with replace. However, this is not a good solution, replace should not be used, it can be dangerous. It can cause issue (not in this case, but in DB deployment or something similar you can lose data)

That's also the way to go for me, I always tried to replace everything (it was my first run so I wasn't worried of losing data) but it kept failing- a manual sync to CRDs only solve the problem... for now at least 👀

**Comment by outofrange** [comment]
For others that might come to this issue, this is what we ended up doing:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 37.2.0
  releaseName: prom
  namespace: prometheus-system
  valuesFile: "values.yaml"
  includeCRDs: true

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
```
