### ISSUE TITLE
5-second GRPC timeouts causing sync failure in sidecar plugin

### ISSUE THREAD

**Issue by gmalkov** [argoproj/argo-cd#8131]
**Describe the bug**
I'm trying to get [Tanka](https://tanka.dev/) working as a sidecar plugin, and I think I'm mostly there, but I'm getting the following error when trying to sync my app:
```
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
When I look at the logs of the Tanka container, I see that the init and generate commands are succeeding, but taking up to 30 seconds. I also see log messages like this one:
```
time="2022-01-10T16:07:36Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GenerateManifest grpc.request.deadline="2022-01-10T16:07:13Z" grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2022-01-10T16:07:08Z" grpc.time_ms=27908.912 span.kind=server system=grpc
```
I've googled around and tried changing application controller settings like `repo-server-timeout-seconds`, `operation-processors` and `status-processors`, but it seems to have no effect, the `grpc.request.deadline` in these logs is always 5 seconds after `grpc.start_time`...
Is there a way to avoid this timeout/failure?

I first [posted about this in the CNCF Slack's #argo-cd channel](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1641831516135400), and it was suggested I make this issue.

**To Reproduce**

My Tanka plugin config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tanka-cmp
  annotations:
    app.kubernetes.io/part-of: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: tanka
    spec:
      version: v1.0
      init:
        command: [jb, install]
      generate:
        command: [sh, -c]
        args: ["/usr/local/bin/tk show --dangerous-allow-redirect $TANKA_JSONNET_PATH"]
      discover:
        fileName: "./jsonnetfile.json"
      allowConcurrency: true
      lockRepo: false
```

**Expected behavior**

The app should sync, since I can see the init and generate commands are succeeding from the Tanka container logs.

**Version**

```shell
argocd version
argocd: v2.1.2+7af9dfb.dirty
  BuildDate: 2021-09-02T21:28:55Z
  GitCommit: 7af9dfb3524c13e941ab604e36e49a617fe47d2e
  GitTreeState: dirty
  GoVersion: go1.17
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.2+03b17e0
  BuildDate: 2022-01-01T06:27:52Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Comment by crenshaw-dev** [comment]
@alexmt I think [this line](https://github.com/argoproj/argo-cd/blob/3fe924ebd6ed1493a8e82b1394d6942f6cebcceb/util/app/discovery/discovery.go#L92) sets the timeout for the CMP client. Am I correct about that? If so, should we make that value configurable at either the repo-server level or (somehow) the CMP level?

**Comment by crenshaw-dev** [comment]
I'm convinced that this is the correct line. I've tested with `sleep 5` in the CMP, which fails. And then I've tested again after building a new image with timeout=60 and `sleep 30`, which succeeds.

I'll look at adding a parameter to configure a default timeout for all sidecar CMPs. I think we should consider making this configurable at the individual CMP level, but that can wait for later. One way to configure it would be to add a timeout field to the CMP config file. But the code making the call doesn't have ready access to that config file's values, so it would take some work to implement something that robust.

**Comment by lirlia** [comment]
i face same problems in helm chart.
so my workaround is to add a sync container

cmp-plugin

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  # see: https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      init:
        command: [sh, -c, "helm repo add $HELM_REPO_NAME $HELM_REPO_URL"]
      discover:
        fileName: "values.yaml"
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE --values values.yaml $ARGOCD_APP_NAME $HELM_REPO_NAME/$HELM_CHART_NAME --version $HELM_CHART_VERSION"]
      allowConcurrency: true
      lockRepo: false
```

Deployment.yaml(argo-repo-server)

```
      initContainers:
      - name: mkdir-helm-working-dir
        image: alpine/helm:latest
        command: ["sh", "-c", "-x"]
        args:
          - |-
              GCS_PLUGIN_VERSION="0.2.0"
              GCS_PLUGIN_REPO="https://github.com/viglesiasce/helm-gcs.git"
              helm plugin install ${GCS_PLUGIN_REPO} --version ${GCS_PLUGIN_VERSION}
              chown -R 999:999 /helm-working-dir

        env:
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
        volumeMounts:
          - mountPath: /helm-working-dir
            name: helm-working-dir

      # see: https://argo-cd.readthedocs.io/en/latest/proposals/config-management-plugin-v2/
      containers:
      - name: cmp-sidecar
        command: [/var/run/argocd/argocd-cmp-server]
        image: asia.gcr.io/xxx/helm-gcs:3.6.3-1
        securityContext:
          runAsNonRoot: true
          # see: https://argo-cd.readthedocs.io/en/latest/user-guide/config-management-plugins/#3-register-the-plugin-sidecar
          runAsUser: 999
        env:
          # - name: HELM_CACHE_HOME
          #   value: /helm-working-dir
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
            name: cmp-plugin
          - mountPath: /tmp
            name: tmp
          - mountPath: /helm-working-dir
            name: helm-working-dir

      # see: https://github.com/argoproj/argo-cd/issues/8131
      - name: helm-repo-reloader
        command: ["sh", "-c"]
        args:
          - |-
              while true
              do
                helm repo update
                sleep 5
              done

        image: asia.gcr.io/xxx/helm-gcs:3.6.3-1
        securityContext:
          runAsNonRoot: true
          # see: https://argo-cd.readthedocs.io/en/latest/user-guide/config-management-plugins/#3-register-the-plugin-sidecar
          runAsUser: 999
        env:
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
        volumeMounts:
          - mountPath: /helm-working-dir
            name: helm-working-dir

      volumes:
        - name: cmp-plugin
          configMap:
            name: cmp-plugin
        - name: helm-working-dir
          emptyDir: {}
```
