### ISSUE TITLE
ARGOCD_SESSION_MAX_FAIL_COUNT seems not working

### ISSUE THREAD

**Issue by rayshoo** [argoproj/argo-cd#8139]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ v ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ v ] I've included steps to reproduce the bug.
* [ v ] I've pasted the output of `argocd version`.

**Describe the bug**
I read [argocd document](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#failed-logins-rate-limiting) and find `ARGOCD_SESSION_MAX_FAIL_COUNT` environment value can change max fail count.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

```yaml
# kubectl get deployment -n argocd argocd-server -o yaml
...
      containers:
      - command:
        - argocd-server
        env:
        - name: ARGOCD_SESSION_MAX_FAIL_COUNT
          value: "10"
        - name: ARGOCD_SERVER_INSECURE
          valueFrom:
            configMapKeyRef:
...

# kubectl rollout restart deployment -n argocd argocd-server

# check new pod  running and old pod has terminated

# login fail attempt 5~6 times, then input correct password > can not login

# k exec -it -n argocd argocd-server-5d57d596cd-jqb6t -- /bin/bash
argocd@argocd-server-5d57d596cd-jqb6t:~$ echo $ARGOCD_SESSION_MAX_FAIL_COUNT
10
```
**Expected behavior**

new pod with new env ARGOCD_SESSION_MAX_FAIL_COUNT:10.
It was expected that I should have logged in despite 5 or 6 login failures, but it didn't.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.

argocd: v2.1.7+a408e29
  BuildDate: 2021-11-17T22:10:27Z
  GitCommit: a408e299ffa743213df3aa9135bf7945644ec936
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.1.7+a408e29
  BuildDate: 2021-11-17T22:10:27Z
  GitCommit: a408e299ffa743213df3aa9135bf7945644ec936
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.6.0+g7f2df64
  Kubectl Version: v0.21.0
  Jsonnet Version: v0.17.0

```

**Logs**

```sh
# Paste any relevant application logs here.
vagrant@m1:~$ k logs -n argocd -f argocd-server-5d57d596cd-jqb6t 
time="2022-01-11T04:49:21Z" level=info msg="Starting configmap/secret informers"
time="2022-01-11T04:49:22Z" level=info msg="Configmap/secret informer synced"
time="2022-01-11T04:49:22Z" level=info msg="argocd v2.1.7+a408e29 serving on port 8080 (url: , tls: true, namespace: argocd, sso: false)"
time="2022-01-11T04:49:22Z" level=info msg="0xc000be6720 subscribed to settings updates"
time="2022-01-11T04:49:22Z" level=info msg="Starting rbac config informer"
time="2022-01-11T04:49:22Z" level=info msg="RBAC ConfigMap 'argocd-rbac-cm' added"
time="2022-01-11T04:49:46Z" level=warning msg="User alice failed login 1 time(s)"
time="2022-01-11T04:49:47Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2022-01-11T04:49:46Z" grpc.time_ms=990.387 span.kind=server system=grpc
time="2022-01-11T04:49:48Z" level=warning msg="User alice failed login 2 time(s)"
time="2022-01-11T04:49:49Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2022-01-11T04:49:48Z" grpc.time_ms=660.653 span.kind=server system=grpc
time="2022-01-11T04:49:49Z" level=warning msg="User alice failed login 3 time(s)"
time="2022-01-11T04:49:50Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2022-01-11T04:49:49Z" grpc.time_ms=855.873 span.kind=server system=grpc
time="2022-01-11T04:49:50Z" level=warning msg="User alice failed login 4 time(s)"
time="2022-01-11T04:49:51Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2022-01-11T04:49:50Z" grpc.time_ms=715.974 span.kind=server system=grpc
time="2022-01-11T04:49:52Z" level=warning msg="User alice failed login 5 time(s)"
time="2022-01-11T04:49:52Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2022-01-11T04:49:51Z" grpc.time_ms=653.366 span.kind=server system=grpc
time="2022-01-11T04:50:02Z" level=warning msg="User alice had too many failed logins (5)"
time="2022-01-11T04:50:03Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = Invalid username or password" grpc.code=Unauthenticated grpc.method=Create grpc.service=session.SessionService grpc.start_time="2022-01-11T04:50:02Z" grpc.time_ms=625.022 span.kind=server system=grpc
time="2022-01-11T04:50:16Z" level=warning msg="User alice had too many failed logins (5)"
```
