### ISSUE TITLE
route.openshift.io/v1 resource Health stuck in "Progressing" with details "Route is still getting admitted"

### ISSUE THREAD

**Issue by w4rgrum** [argoproj/argo-cd#8144]
**Describe the bug**

Openshift Route resources stuck in `Progressing` Health status with details `Route is still getting admitted`

**To Reproduce**

Register your route on multiple routers to get more than 1 element in `.status.ingress[]`

Example:
```yaml
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2021-06-14T13:04:02Z'
          status: 'True'
          type: Admitted
      host: myroute.tnz.mydomain.net
      routerCanonicalHostname: tnz.mydomain.net
      routerName: tnz
      wildcardPolicy: None
    - conditions:
        - lastTransitionTime: '2021-06-14T13:04:02Z'
          status: 'True'
          type: Admitted
      host: myroute.default.mydomain.net
      routerCanonicalHostname: default.mydomain.net
      routerName: default
      wildcardPolicy: None
```

**Expected behavior**

2 ingresses are detected as admitted `"True"` thus status should be `Healthy` instead of `Progressing`

**Screenshots**

![image](https://user-images.githubusercontent.com/54102154/148941652-d70e85a5-6a47-4540-bd05-3c08e5801835.png)

**Version**

```shell
v2.2.2+03b17e0
```

**Remarks**

It seems this is coming from this code: https://github.com/argoproj/argo-cd/blob/b559bf88d1a033863cdd475f67a82a5f96aebd89/resource_customizations/route.openshift.io/Route/health.lua
Here the 2 sets of counters `numIngressRules` and `num[True|False]` are not reset on the same loop level, leading the count of `numIngressRules` to be correct in the above mentioned case and the count of `num[True|False]` to be reset between `.status.ingress[]` items.
