### ISSUE TITLE
Add `envFrom` and `env.valueFrom` to ApplicationSourcePlugin

### ISSUE THREAD

**Issue by karlschriek** [argoproj/argo-cd#8178]
# Summary

Instead of only being able to explicitly declare variables in the `env` field when using a `plugin` source, I would like to be able to read those vars from a Secret instead, using the typical `envFrom` and/or `valueFrom` syntax.

i.e. instead of using this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  ...
spec:
  ...
  source:
    plugin:
      env:
      - name: MY_VAR1
        value: foo
      - name: MY_VAR2
        value: bar
```

I would like to have this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  ...
spec:
  ...
  source:
    plugin:
      envFrom:
        secretRef: 
          name: my-secret2
      env:          
      - name: MY_VAR1
        valueFrom:
          secretKeyRef:
            name: my-secret1
            key: MY_VAR1
```

# Motivation
I am using the plugins interface (https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/) to create custom deployment workflows that depend on (sometimes sensitive) environment variables. I initially thought I might simply inject the ENV vars directly into the `argocd-repo-server` instead of defining them in the Application source, but the problem with that approach is that those ENV vars are not used when calculating the `cacheKey` (see  (https://github.com/argoproj/argo-cd/blob/502762acc0e55813030bf0c19452fedd5b1154dc/reposerver/cache/cache.go#L141), so if one of them changes, argocd doesn't know that it should invalidate the cache.

A hash of the Application spec is however included in the cacheKey, so changes to vars under the `env` field do invalidate the cache.

# Proposal

My proposal is to add `envFrom` and `env.valueFrom` to the ApplicationSource spec and ensure that any changes to the referenced Secrets are taken into account when the cacheKey is calculated.
