### ISSUE TITLE
Argo-CD SYNC in one directory, shows message of another directory in UI

### ISSUE THREAD

**Issue by abhinayguptapeoplegrove** [argoproj/argo-cd#8196]
We have deployed two components [A, B] in ArgoCD whose helms structure are show below

```
.
├── helm-deployments
│   ├── component-A
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   ├── NOTES.txt
│   │   │   ├── _helpers.tpl
│   │   │   ├── service.yaml
│   │   │   └── serviceaccount.yaml
│   │   ├── values.yaml
│   ├── component-B
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   ├── NOTES.txt
│   │   │   ├── _helpers.tpl
│   │   │   ├── serviceaccount.yaml
│   │   ├── values.yaml
```

**ArgoCD application yaml**
COMPONENT-A
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: component-A
  namespace: argocd
  annotations:
spec:
  project: dev
  source:
    repoURL: 'git@github.com:******.******.git
    path: helm-deployments/component-A/
    targetRevision: ***
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://**.**.**'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
  revisionHistoryLimit: 10
```
COMPONENT-B
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: component-B
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: dev
  source:
    repoURL: 'git@github.com:*********/***.git'
    path: helm-deployments/component-B/
    targetRevision: ***
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://**.**.**
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
  revisionHistoryLimit: 5
```

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq. [Done]
* [ ] I've included steps to reproduce the bug. [Done]
* [ ] I've pasted the output of `argocd version`. [Done]

**Describe the bug**

```Sometimes when there is commit in values.yaml in component A, ArgoCD application of component B starting syncing which is weird ```

**To Reproduce**

Not reproducible 

**Expected behaviour**

Syncing of both ArgoCD applications [component A and B] should works independently

**Screenshots**

**Version**

```shell
V2.1.7
```

**Logs**

```
NO LOGS
```
