### ISSUE TITLE
Stop self-heal between time periods 

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#8207]
# Summary

We want to implement a nightly downscale of our deployments and statefullsets. We have implemented a downscaler functionality which uses the kubectl scale command to downscale all non prd pods. This works good except for the ones that have self-heal enabled in the argocd application. Is it possible to create a self-heal window where the self heal temporaryly is disabled? This is the same functionality as the already existing syncwindow. 

# Motivation

We want to scale down unused resources. (linked issue: https://github.com/argoproj/argo-cd/issues/4038)

# Proposal

Add a selfheal window in the appproject. 
````
selfhealWindows:
    - applications:
      - '*'
      duration: 8h
      kind: deny
      manualSync: true
      schedule: 0 20 * * 1,2,3,4,5
    - applications:
      - '*'
      duration: 24h
      kind: deny
      manualSync: true
      schedule: 0 4 * * 0,6
````
