### ISSUE TITLE
Invalid Semantic Version when using KUBE_VERSION in configManagementPlugins in EKS 1.20

### ISSUE THREAD

**Issue by patrickjahns** [argoproj/argo-cd#8249]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

- Create EKS cluster with `1.20` 
- Add the following configManagementPlugin to ArgoCD (used the helm chart 3.31.0 for deployment)

```
argo-cd:
  repoServer:
    logLevel: debug
  server:
    config:
      configManagementPlugins: |-
        - name: kustomized-helm
          init:
            command: ["/bin/sh", "-c"]
            args: ["helm dependency build || true"]
          generate:
            command: ["/bin/sh", "-c"]
            args: ["printenv && eval helm template --debug $HELM_CHART_DIR --name-template ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE \"$(for file in $HELM_VALUE_FILES; do echo \"-f $file \" | tr -d '\n'; done)\" \"$(for val in $HELM_SET_VALUES; do echo \"--set \'$val\' \" | tr -d '\n'; done)\" \"$HELM_ARGS\" --kube-version $KUBE_VERSION --api-versions $KUBE_API_VERSIONS --include-crds > helm_template_build.yaml && kustomize build"]
```

- Create an argo application with the kustom plugin
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: ./platform/prometheus
    plugin:
      env:
      - name: HELM_CHART_DIR
        value: ./chart
      - name: HELM_VALUE_FILES
        value: |
          values.yaml
          values_staging-eks-cluster.yaml
      name: kustomized-helm
    repoURL: **redacted**
    targetRevision: HEAD
  syncPolicy:
    automated: {}
```

See the following error from helm:

```
argocd-repo-server-746f84465b-hdwcn repo-server time="2022-01-21T11:33:56Z" level=error msg="`/bin/sh -c printenv && eval helm template --debug $HELM_CHART_DIR --name-template ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE \"$(for file in $HELM_VALUE_FILES; do echo \"-f $file \" | tr -d '\n'; done)\" \"$(for val in $HELM_SET_VALUES; do echo \"--set '$val' \" | tr -d '\n'; done)\" \"$HELM_ARGS\" --kube-version $KUBE_VERSION --api-versions $KUBE_API_VERSIONS --include-crds > helm_template_build.yaml && kustomize build` failed exit status 1: Error: invalid kube version '1.20+': Invalid Semantic Version\nhelm.go:88: [debug] invalid kube version '1.20+': Invalid Semantic Version" execID=64cac
```

**Expected behavior**

- `KUBE_VERSION` containing a valid semantic version for helm or any other plugin when using EKS

**Screenshots**

![image](https://user-images.githubusercontent.com/6403243/150522108-b17d10c0-addb-4851-bb88-274417459cb2.png)

**Version**

```shell
v2.2.2+03b17e0
```

**Logs**

```
argocd-repo-server-746f84465b-hdwcn repo-server time="2022-01-21T11:33:56Z" level=error msg="`/bin/sh -c printenv && eval helm template --debug $HELM_CHART_DIR --name-template ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE \"$(for file in $HELM_VALUE_FILES; do echo \"-f $file \" | tr -d '\n'; done)\" \"$(for val in $HELM_SET_VALUES; do echo \"--set '$val' \" | tr -d '\n'; done)\" \"$HELM_ARGS\" --kube-version $KUBE_VERSION --api-versions $KUBE_API_VERSIONS --include-crds > helm_template_build.yaml && kustomize build` failed exit status 1: Error: invalid kube version '1.20+': Invalid Semantic Version\nhelm.go:88: [debug] invalid kube version '1.20+': Invalid Semantic Version" execID=64cac
```

**Proposed Fix**

The problem is in https://github.com/argoproj/argo-cd/blob/0dfc125d953277bf1e6c8e240a493a68c2f10cd6/reposerver/repository/repository.go#L1181 

```
env = append(env, "KUBE_VERSION="+q.KubeVersion)
```

The helm command uses explicit SemanticVersion to prevent this
```
KubeVersion: text.SemVer(q.KubeVersion),
```

see: https://github.com/argoproj/argo-cd/blob/0dfc125d953277bf1e6c8e240a493a68c2f10cd6/reposerver/repository/repository.go#L567

The problem is likely that EKS returns `1.20+` cluster version - and ArgoCD pushes this through directly

See output of `kubectl version` of an EKS 1.20 cluster
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
