### ISSUE TITLE
OCI helm chart with dependencies not picking helm repo secret

### ISSUE THREAD

**Issue by singhravinderlko** [argoproj/argo-cd#8266]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [y] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [y ] I've included steps to reproduce the bug.
* [ y] I've pasted the output of `argocd version`.

**Describe the bug**

i am using gcp artifact helm repository for storing OCI helm chart. when trying to create a application using oci helm chart with dependencies, it is failing during dependencies resoluton with authentication related errors(error pasted below). while if a just create a argocd app with no helm chart dependencies, it works fine. i am using credential template for authenticating to private GCP artifact helm repository. 

rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download oci://<helm OCI repo path>: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden

**To Reproduce**
1- create argocd application using below yaml which is trying to deploy chart.yaml which has been kept on github repo and in dependencies i am referring to gcp artifact repository which is a OCI helm repo-
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prismatesting
  namespace: argocd
spec:
  project: devops
  source:
    repoURL: https://<github-repo-url>
    targetRevision: HEAD
    path: clusters/devops/twistlock-defender
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: devops-clusterA
    namespace: twistlock
  syncPolicy:
    automated:
      prune: true
```
```
apiVersion: v1
description: Twistlock Defender Daemon Set Helm Chart
name: twistlock-defender
version: 21.08.520
dependencies:
- name: twistlock-defender
  version: 21.08.525
  repository: 'oci://<oci helm repo url>'
```
2- application crd gets deployed but fails to apply the dependencies chart with following error:

rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download oci://<oci helm repo path>: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden

**Expected behavior**

application should have been able to apply dependencies chart without authentication failure.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
argocd: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:52:31Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.2+03b17e0
```

**Logs**

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download oci://<repo path>: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```
