### ISSUE TITLE
Notifications slack template: invalid_attachments

### ISSUE THREAD

**Issue by NickLarsenNZ** [argoproj/argo-cd#8286]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to use a slack message template developed at <https://app.slack.com/block-kit-builder/> through the Attachments Preview.

This could be a Slack API issue, but don't see much about it. Wondering if other's have had experience sending attachments with `blocks` instead of `fields`?

**To Reproduce**

1. <https://app.slack.com/block-kit-builder/>
2. Click ***Clear Blocks*** (in the top right)
3. Choose ***Attachments Preview*** (from the dropdown above the preview column)
4. Add some components from the left column
5. Copy the JSON from inside the `attachments` list
6. Paste into a notification template (eg: `argocd-notifications-cm` ConfigMap), like so:
    > depending on your editor, you might need to replace each tab with two spaces
    ```yml
    template.example: |
      message: |
        From an example notification template.
      slack:
        attachments: |
          [
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": "Example plain text.",
                    "emoji": true
                  }
                }
              ]
            }
          ]
        groupingKey: ""
        notifyBroadcast: false
    ```
7. Run a test:
    ```sh
    argocd admin notifications template notify example my-app --recipient slack:my-slack-channe;
    ```

Notice the error:

```
DEBU[0000] Sending request: POST /api/chat.postMessage HTTP/1.1
Host: slack.com
Content-Type: application/x-www-form-urlencoded

attachments=%5B%7B%22color%22%3A%22%2388D8B0%22%2C%22text%22%3A%22%22%2C%22blocks%22%3A%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22Section+block+text+is+good%22%7D%7D%5D%7D%5D&channel=argocd-nonprod-notifications&text=From+an+example+notification+template.%0A&token=xoxb-xxxx-xxxx-xxxx  service=slack
DEBU[0000] Received response: HTTP/2.0 200 OK
Access-Control-Allow-Headers: slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-slack-req-id, retry-after
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Type: application/json; charset=utf-8
Date: Wed, 26 Jan 2022 12:55:22 GMT
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Pragma: no-cache
Referrer-Policy: no-referrer
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
Via: envoy-www-iad-lhiv, envoy-edge-syd-3hy7
X-Accepted-Oauth-Scopes: chat:write
X-Backend: main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow
X-Content-Type-Options: nosniff
X-Edge-Backend: envoy-www
X-Envoy-Upstream-Service-Time: 234
X-Oauth-Scopes: chat:write,chat:write.customize
X-Powered-By: HHVM/4.128.0
X-Server: slack-www-hhvm-main-iad-2rkb
X-Slack-Backend: r
X-Slack-Edge-Shared-Secret-Outcome: no-match
X-Slack-Req-Id: xxxxxxxx
X-Slack-Shared-Secret-Outcome: no-match
X-Xss-Protection: 0


{"ok":false,"error":"invalid_attachments","errors":["invalid_keys"],"response_metadata":{"messages":["[ERROR] invalid_keys"]}}  service=slack
failed to notify 'slack:argocd-nonprod-notifications': invalid_attachments
```

**Expected behavior**

A success message, and notification

**Screenshots**

**Version**

```shell
argocd: v2.3.0+96f95ca
  BuildDate: 2022-01-25T23:53:46Z
  GitCommit: 96f95ca1c1048c37f935f6f72ff54be641d92b60
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

**Comment by NickLarsenNZ** [comment]
I just tried it this way, which works:

```yml
message: |
  From an example notification template.
slack:
  blocks: |
    [
      {
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": "Section block text is good"
        }
      }
    ]
  groupingKey: ""
  notifyBroadcast: false

```

 but I'm now stuck trying to specify the block color. I have tried the following without success:

```yml
message: |
  From an example notification template.
slack:
  color: "#ff00ff"
  blocks: |
    [
      {
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": "Section block text is good"
        }
      }
    ]
  groupingKey: ""
  notifyBroadcast: false

```
