### ISSUE TITLE
EndPoint with multiple addresses causes false diff

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#8287]
**Describe the bug**

EndPoint with multiple addresses causes false diff

**To Reproduce**

Create Argo CD app that manages endpoint with several addresses

**Expected behavior**

The difference in addresses order should not case diff

**Screenshots**

![](https://user-images.githubusercontent.com/65038083/131903967-4be9cb48-fa84-427c-beca-24a97d21a0d6.png)

**Version**

```shell
v2.3.0+ecc3ab3
```

**Comment by kshamajain99** [comment]
@doyelese Will you be able to share some more details about your endpoint objects? Does it have non-empty targetRef ?

**Comment by doyelese** [comment]
> @doyelese Will you be able to share some more details about your endpoint objects? Does it have non-empty targetRef ?

Sure, it is a glusterfs endpoint for our shared storage.  What do you mean on-empty targetRef? I can get additional info. Here is our `desc endspoints` result

```
Name:         glusterfs-cluster
Namespace:    prod-images
Labels:       app.kubernetes.io/instance=prod-images
Annotations:  argocd.argoproj.io/sync-options: Validate=false
Subsets:
  Addresses:          192.168.90.203
  NotReadyAddresses:  <none>
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    <unset>  1     TCP

  Addresses:          192.168.90.201
  NotReadyAddresses:  <none>
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    <unset>  1     TCP

  Addresses:          192.168.90.202
  NotReadyAddresses:  <none>
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    <unset>  1     TCP

Events:  <none>

```

**Comment by doyelese** [comment]
`pv desc`

```
Name:            prod-images-volume
Labels:          app.kubernetes.io/instance=prod-images
Annotations:     pv.beta.kubernetes.io/gid: 0
                 pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:
Status:          Bound
Claim:           prod-images/gluster-claim
Reclaim Policy:  Retain
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        50Gi
Node Affinity:   <none>
Message:
Source:
    Type:                Glusterfs (a Glusterfs mount on the host that shares a pod's lifetime)
    EndpointsName:       glusterfs-cluster
    EndpointsNamespace:  <unset>
    Path:                /prod-images
    ReadOnly:            false
Events:                  <none>
```

**Comment by kshamajain99** [comment]
@doyelese Will you be able to share the raw yaml spec?

**Comment by doyelese** [comment]
> @doyelese Will you be able to share the raw yaml spec?

Redacted and without the deployments it connects to, but heres the service section of the yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: prod-images-http-service
  namespace: prod-images
spec:
  selector:
    app: prod-images-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-images-php-service
  namespace: prod-images
spec:
  selector:
    app: prod-images-php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-images-ingress
  namespace: prod-images
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "REDACTED"
    nginx.org/client-max-body-size: "REDACTED"
spec:
  rules:
  - host: "REDACTED"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prod-images-http-service
            port:
              number: 80
  tls:
  - hosts:
      - "REDACTED"
    secretName: REDACTED
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim
  namespace: prod-images
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: prod-images
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: prod-images
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
subsets:
  - addresses:
      - ip: 192.168.90.203
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.90.201
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.90.202
    ports:
      - port: 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: prod-images
  name: prod-images-volume
  annotations:
    pv.beta.kubernetes.io/gid: "0"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: /prod-images
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim2
  namespace: prod-images
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1000Gi
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster2
  namespace: prod-images
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster2
  namespace: prod-images
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
subsets:
  - addresses:
      - ip: 192.168.90.203
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.90.201
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.90.202
    ports:
      - port: 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: prod-images
  name: prod-images-storage
  annotations:
    pv.beta.kubernetes.io/gid: "0"
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster2
    path: /prod-images-storage
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
```
