### ISSUE TITLE
support for multiple rbac configmaps

### ISSUE THREAD

**Issue by bilalcaliskan** [argoproj/argo-cd#8324]
# Summary
Currently if we dont provide a config file with flag `--policy-file` argument, the ConfigMap `argocd-rbac-cm` from K8s is used as expressed in [here](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/admin/settings_rbac.go#L110). It will be great if we can provide multiple configmaps to increase maintainability of our RBAC configurations. If this is discussed earlier,  sorry for the duplicate issue.

# Motivation
Let's consider the case we are managing an environment with 100+ different teams. For each team, we should provide at least 3 lines of code in our configmap to be able to handle rbac over ldap. Managing a configmap which is that much huge is very difficult. Instead it would be better if we can create multiple configmaps per team and put a specific label on each configmap and then merge these proper labelled configmaps.

# Proposal
As mentioned in the **Summary** and **Motivation** sections, my proposal is somehow picking the properly labelled configmaps and then merging them somehow in the related [file](https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/admin/settings_rbac.go). Roughly we can provide something like below arguments to provide mentioned functionality;
```
--multiple-policy-configmaps             boolean, defaults to false
--policy-configmap-label                    string, defaults to 'argocd-policy-file=true'
```
If this is OK, i will be glad working on the implementation of this issue!

**Comment by lknite** [comment]
Also looking for this.  I use argocd and an applicationset that lets me install argocd on multiple clusters.  I have a default rbac in the applicationset which grants admin access to users in a group, but I'd like to also be able to grant specific access to an installed argocd instance, allowing team members full access to a specific application only.

**Comment by crenshaw-dev** [comment]
This has been mostly done. Would someone be willing to pick up the PR and apply apply the changes Jann requested? https://github.com/argoproj/argo-cd/pull/9976

**Comment by bilalcaliskan** [comment]
@crenshaw-dev missed that one, im on it!

**Comment by leoluz** [comment]
>  sorry for asking directly here, but we would also appreciate the same idea for the ArgoCD config map itself. It could merge the config by key similar how Helm would do value merging. This would improve composability I think. Would you appreciate a similar PR for that feature?

I agree with @neiser and think multiple keys in the same configmap is preferable since we wouldn't have to manage another configmap. I implemented a draft PR with that concept here: https://github.com/argoproj/argo-cd/pull/12511

`argocd-rbac-cm` could then be composed by multiple keys starting with `policy.csv.*` like in the example below:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    g, group-admins, role:admin
    g, kubernetes:argocd-readonly, role:readonly
  policy.csv.overlay1: |
    p, role:tester, applications, *, */*, allow
    p, role:tester, projects, *, *, allow
    g, kubernetes:argocd-readonly, role:tester
  policy.csv.overlay2: |
    p, role:devops, applications, *, */*, allow
    p, role:devops, projects, *, *, allow
    g, group-devops, role:devops
```

@bilalcaliskan would that approach address your use-case as well?
