### ISSUE TITLE
Make SSH keys available within multiple repo scopes

### ISSUE THREAD

**Issue by karlschriek** [argoproj/argo-cd#8342]
# Summary

Make it possible to pass an SSH key to multiple source repos, either by explicitly stating from which sources it is allowed to be used, or by making it possible to allow this generally for all repos (which would be a valid approach if one does not have a mutli-tenant setup).

See also https://github.com/argoproj/argo-cd/issues/6440

# Motivation

With reference also to this issue: https://github.com/argoproj/argo-cd/issues/6440, we use kustomize with remote (private) bases that are references from inside other (private) remote bases. These repos cannot be accessed with the same SSH key, mainly because they are often a combination of an upstream repo (ours) that is references from a downstream repo (a client's).

So we might have:

`github.com/our-org/our-repo.git//our-manifests:`
```yaml
resources:
- ../base
- some-resource.yaml
```

And then the client's repo (which the Application points to):

`github.com/client-org/client-repo.git//manifests`
```yaml
resources:
- git::ssh://git@github.com/our-org/our-repo.git//our-manifests:
```

In this case I was expecting that the client would be able to create two git repo secrets as follows, and would be able to execute the workflow above.

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: client-git-secret
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: github.com/client-org/client-repo.git
  sshPrivateKey: |
     ---START KEY---
     xcvxcv
     ---END KEY---
```

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: our-git-secret
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com/our-org/our-repo.git
  sshPrivateKey: |
     ---START KEY---
     asbxcv
     ---END KEY---
```

However, this does not appear to be the case, since (for security reasons in a multi-tenant setup) when the Application is built, only the ssh key for the specific repository wherein the source directory lies is passed to it.

# Proposal

In the simplest case, I would simply make this a setting that can be set in `argocd-cm`, whereby to allow all ssh keys to be used in all repos. This would be perfectly fine in my opinion if one is using a single-tenant setup.

Alternatively, make it possible to to define in the git repo secret which additional repositories are allowed to use this key.

**Comment by karlschriek** [comment]
If there are any known workarounds for now that would also be welcome info!

**Comment by blairdrummond** [comment]
In case anyone finds this helpful, the workaround I am using is to overwrite the repo-server's `/etc/gitconfig` file and rewrite the SSH url into an HTTPS url with a PAT in it. Like this:

```ini
[filter "lfs"]
    clean = git-lfs clean -- %f
    smudge = git-lfs smudge -- %f
    process = git-lfs filter-process
    required = true

# Name them as different hosts so that we can use ssh Host entries
[url "https://${USERNAME}:${PAT_TOKEN}@github.com/${ORG}/"]
    insteadOf = git@github.com:${ORG}/
```

(in the container the actual values are in there, there's no magic env vars)

Then you just make that content a secret and volumeMount it over the /etc/gitconfig. The kustomize files still have ssh urls in them but argo handles them using a PAT.

**Comment by laurivosandi** [comment]
I would like to stick to Git over SSH, but I am not going to create secret per Git repo as ArgoCD currently expects and  @blairdrummond suggested solution does not work for everybody

**Comment by blairdrummond** [comment]
I also prefer SSH over PATs usually, but you might want to check out github's new fine-grained access tokens if you're on Github. It's actually a decent solution imho

**Comment by laurivosandi** [comment]
For one usecase I already used to @blairdrummond suggested workaround. In another setup I use Gitea and it's not really applicable there. Universal solution with SSH keys is needed anyway

**Comment by laurivosandi** [comment]
@blairdrummond are you sure you didn't omit any details. If I open up shell from repo-server I can do successful `git clone` but Argo still complains. I am trying to dpeloy Helm chart from Git repo though if that matters?

**Comment by blairdrummond** [comment]
Hmm unfortunately I am using Kustomize not helm, so haven't tested that. I would double check the gitconfig in the pod to make sure it synced into the pod correctly, then I would maybe test a kustomize with private remote base to confirm the functionality is working. If it is, then it's a helm specific thing that I'd need to check out

**Comment by blairdrummond** [comment]
Oh, I think I was unclear --- this solves remote bases AFTER the repos have been cloned by Argo. You still need to pull the https helm repos with the pat at the argo level

**Comment by laurivosandi** [comment]
Not sure how I missed this but Argo docs actually specify how to share credentials between repos, it's called "credential templates" see https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials for more details.

Basically you just specify `repo-creds` secret type label. To make it work with PAT-s you do something like this:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/myorg
  password: github_pat_12312312312312312312
  username: we-just-use-foo-as-this-will-not-matter
```
