### ISSUE TITLE
add missing resources applicationsets to argocd-server role

### ISSUE THREAD

**Issue by ohauer** [argoproj/argo-cd#8380]
# Summary

give argocd-server role access to applicationsets

# Motivation

Managing Applicationsets in the argocd UI

# Proposal

```yaml
diff --git a/manifests/base/server/argocd-server-role.yaml b/manifests/base/server/argocd-server-role.yaml
index 60731407c..2c15e3187 100644
--- a/manifests/base/server/argocd-server-role.yaml
+++ b/manifests/base/server/argocd-server-role.yaml
@@ -24,6 +24,7 @@ rules:
   - argoproj.io
   resources:
   - applications
+  - applicationsets
   - appprojects
   verbs:
   - create
```

Not sure if the request is valid since I haven't installed 2.3.0-rxX until now, 
but this change was required in argocd 2.2.x in combination with the application-controller
