### ISSUE TITLE
CVE-2022-24348 fix broke Helm downloader plugins interface

### ISSUE THREAD

**Issue by Enrico204** [argoproj/argo-cd#8397]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The fix for `CVE-2022-24348` introduced a check for helm remote protocols (see `allowedHelmRemoteProtocols`, `isURLSchemeAllowed` and others in https://github.com/argoproj/argo-cd/commit/78c2084f0febd159039ff785ddc2bd4ba1cecf88 ). This check broke `helm secrets` integration with ArgoCD as `helm secrets` is using URL schemas like `secrets+age-import://` in `valueFiles` to indicate the tool to use (`age`, `gpg`, etc).

See https://github.com/jkroepke/helm-secrets/issues/185 

**To Reproduce**

Create an Application like:

```yaml
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  source:
    path: helm/mariadb/
    repoURL: 'git@gitlab.com:repo'
    targetRevision: HEAD
    helm:
      version: v3
      releaseName: mariadb
      valueFiles:
        - "secrets+age-import://argocd-age-key/keys.txt?secrets.yml"
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
```

A detailed example is here: https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration 

**Expected behavior**

To keep using `helm secrets`.

**Version**

```shell
argocd version
argocd: v2.2.4+78d749e
  BuildDate: 2022-02-03T20:41:00Z
  GitCommit: 78d749ec88bea5a5e851fc48b9404fdf067192b6
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

The error in ArgoCD is :`rpc error: code = Unknown desc = Manifest generation error (cached): the URL scheme 'secrets+age-import' is not allowed`
