### ISSUE TITLE
ignoreDifferences not ignoring `Secret.data` diff

### ISSUE THREAD

**Issue by brsolomon-deloitte** [argoproj/argo-cd#8403]
For a deployment of [jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/latest/), secret values change post-deployment and seem to be a good candidate for `ignoreDifferences`.

![Screen Shot 2022-02-07 at 7 22 34 AM](https://user-images.githubusercontent.com/81818815/152787630-267490ec-816b-47b7-8d94-8564b48287f9.png)

I use the following to attempt to ignore that diff:

```yaml
project: default
source:
  repoURL: 'git@github.com:redacted'
  path: charts/jupyterhub
  targetRevision: HEAD
  helm:
    valueFiles:
      - redacted.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: redacted
syncPolicy:
  syncOptions:
    - CreateNamespace=true
ignoreDifferences:
  - group: apps
    kind: Secret
    jsonPointers:
      - /data/hub.config.ConfigurableHTTPProxy.auth_token
      - /data/hub.config.CryptKeeper.keys
      - /data/hub.config.JupyterHub.cookie_secret
```

However, even after refresh/sync, the diff is still shown as a diff.

Do I have `jsonPointers` wrong or is there something else I'm missing here?
