### ISSUE TITLE
App gets stuck in "Unknown" state if referencing Helm charts are removed from its git repository

### ISSUE THREAD

**Issue by bentcoder** [argoproj/argo-cd#8417]
Hi,

Removing Helm Charts from git repository doesn't automatically delete the application from ArgoCD although auto-sync is enabled. Is this an expected behaviour or a bug? Currently I have to manually delete the app in UI.

Thanks

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-qa
  namespace: default

spec:
  project: myapp
  source:
    repoURL: https://github.com/me/infra
    path: helm/myapp
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: qa
    name: nonprod
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

`version: v2.2.4+78d749e`
