### ISSUE TITLE
helm ignoreMissingValueSet not part of ApplicationSet CRD in 2.3.x

### ISSUE THREAD

**Issue by dh-apporto** [argoproj/argo-cd#8418]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

2.3.0 includes support for ignoring missing values files for helm charts (see [PR 8003](https://github.com/argoproj/argo-cd/pull/8003)). This feature would be especially helpful for using helm with ApplicationSets which are also made mainline in 2.3.0.   However, it appears that the CRD for ApplicationSets will not let me specify the `ignoreMissingValueFiles` parameter.

**To Reproduce**

Create a ApplicationSet template that utilizes helm, and try to specify the `ignoreMissingValueFiles` parameter. 

For example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  generators:
    ...
  template:
    metadata:
      name: '{{tenant.name}}-{{appName}}'
    spec:
      project: tenant-appstore
      source:
        repoURL: git@github.com:somerepo/k8s-gitops.git
        targetRevision: '{{application.release_version}}'
        path: '{{helmBase}}/{{groupName}}/{{appName}}'
        helm:
          parameters:
          - name: tenant.name
            value: '{{tenant.name}}'
          - name: tenant.id
            value: '{{tenant.id}}'
          - name: tenant.region
            value: '{{path.basename}}'
          - name: application.release_version
            value: '{{application.release_version}}'
          # XXX NOTE: ignoreMissingValueFiles in v2.3 of argocd but not ApplicationSet?
          ignoreMissingValueFiles: true
          valueFiles:
          - 'values.yaml'
          - 'current_release_values.yaml'
          - '{{helmValuesPath}}/base/{{path.basename}}/values.yaml'
          - '{{helmValuesPath}}/base/{{path.basename}}/{{groupName}}/values.yaml'
          - '{{helmValuesPath}}/base/{{path.basename}}/{{groupName}}/{{appName}}/values.yaml'
          - '{{helmValuesPath}}/tenants/{{tenant.name}}/{{path.basename}}/values.yaml'
          - '{{helmValuesPath}}/tenants/{{tenant.name}}/{{path.basename}}/{{groupName}}/values.yaml'
          - '{{helmValuesPath}}/tenants/{{tenant.name}}/{{path.basename}}/{{groupName}}/{{appName}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'tenant-{{tenant.name}}'

```

**Expected behavior**

I expect an ApplicationSet Application Template to allow the same parameters that an ArgoCD Application defines and supports.  Namely, the `helm.ignoreMissingValueFiles` parameter.

**Screenshots**

**Version**

```shell
argocd: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-04T23:39:21Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
$ kubectl apply -f appset.yaml 
error: error validating "appset.yaml": error validating data: ValidationError(ApplicationSet.spec.template.spec.source.helm): unknown field "ignoreMissingValueFiles" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.source.helm; if you choose to ignore these errors, turn validation off with --validate=false

```
