### ISSUE TITLE
CMP 2 discover.find.command doesn't use exit code

### ISSUE THREAD

**Issue by jopit** [argoproj/argo-cd#8443]
**Describe the bug**

The CMP 2.0 documentation says

> If discover.fileName is not provided, the discover.find.command is executed in order to determine whether an application repository is supported by the plugin or not. The find command should return a non-error exit code when the application source type is supported.

but the argocd code actually expects the find command to write a non-empty string to stdout in order to indicate that the type is supported.
```
	log.Debugf("Going to try runCommand.")
	find, err := runCommand(bufferedCtx, config.Spec.Discover.Find.Command, q.Path, os.Environ())
	if err != nil {
		return &repoResponse, err
	}

	var isSupported bool
	if find != "" {
		isSupported = true
	}
	return &apiclient.RepositoryResponse{
		IsSupported: isSupported,
	}, nil
```
https://github.com/argoproj/argo-cd/blob/e01ab05d555b799cba08097710482afac3be601e/cmpserver/plugin/plugin.go#L201

**To Reproduce**

ConfigMap for plugin.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      generate:
        command: [sh, -c, 'echo "{\"kind\": \"ConfigMap\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"$ARGOCD_APP_NAME\", \"namespace\": \"$ARGOCD_APP_NAMESPACE\", \"annotations\": {\"Foo\": \"$FOO\", \"KubeVersion\": \"$KUBE_VERSION\", \"KubeApiVersion\": \"$KUBE_API_VERSIONS\",\"Bar\": \"baz\"}}}"']
      discover:
        find:
          command: [sh, -c, 'date >> /tmp/plugin-discover-has-run; exit 0']
      allowConcurrency: true
      lockRepo: true
```

Sidecar definition
```
    containers:
    - name: cmp
      command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
      image: busybox # This can be off-the-shelf or custom-built image
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp
        # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: plugin.yaml
          name: cmp-plugin
    volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
```

Application
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-0001
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jopit/argocd-0001'
    path: manifests
    targetRevision: HEAD
    plugin:
      env:
      - name: FOO
        value: myfoo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
```

**Version**

```
quay.io/argoproj/argocd:v2.3.0-rc5
```

**Logs**

repo-server
```
time="2022-02-09T15:39:02Z" level=info msg="manifest error cache miss: &ApplicationSource{RepoURL:https://github.com/jopit/argocd-0001,Path:manifests,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:&ApplicationSourcePlugin{Name:,Env:[]*EnvEntry{&EnvEntry{Name:FOO,Value:myfoo,},},},Chart:,}/417dea6866af6ec299b6c301a8692ac117cd36f3"
time="2022-02-09T15:39:02Z" level=error msg="finished unary call with code Unknown" error="plugin sidecar failed. Couldn't find cmp-server plugin supporting repository /tmp/https___github.com_jopit_argocd-0001/manifests" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2022-02-09T15:40:01Z" grpc.service=repository.RepoServerService grpc.start_time="2022-02-09T15:39:01Z" grpc.time_ms=379.61 span.kind=server system=grpc
```
