### ISSUE TITLE
ArgoCD doesn't delete resources it creates

### ISSUE THREAD

**Issue by MazenElzanaty** [argoproj/argo-cd#8444]
Argo v2.2.5+8

I have the following app in my repo but when I delete it from the repo, argocd removes it from the argocd namespace only, but the resources themselves are still there, deployment, ingress, etc

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    name: 'non-production'
    namespace: app1
  source:
    path: app1helm/
    repoURL: 'git@github.com:org/gitops.git'
    targetRevision: main
    helm:
      valueFiles:
      - ./values.yaml
  project: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
 ```
Checklist:

* [ yes ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ yes ] I've included steps to reproduce the bug.
* [ yes ] I've pasted the output of `argocd version`.

**Describe the bug**

The app itself is removed but the resources created by the app aren't

**To Reproduce**

Deploy an app with an application from a repo and delete the application manifest from the repo

**Expected behavior**

Deleting the app and its resources, deployments, namespace, etc

**Version**

Argo v2.2.5+8
