### ISSUE TITLE
Helm Parameters does not allow common annotations

### ISSUE THREAD

**Issue by derrickburns** [argoproj/argo-cd#8464]
I would like to pass an annotation via helm parameters in the Application CRD such as:
```
annotations:
      configmap.reloader.stakater.com/reload: "foo"
```

However, this does not work:

```
  source:
    helm:
      parameters:
      - name: annotations."configmap.reloader.stakater.com/reload"
        value: : "foo"
```

Is there another syntax?

**Comment by ishitasequeira** [comment]
I would like to work on this.

**Comment by zoltan-patchworks** [comment]
Try escaping the dot.

Example:
```
        - name: controller.podAnnotations."prometheus\.io/scrape"
          value: "true"
        - name: controller.podAnnotations."prometheus\.io/port"
          value: "10254"
```

**Comment by avifreege** [comment]
We are facing issues also with service account annotations:
`            - name: controller.serviceAccount.annotations."eks\\.amazonaws\\.com/role-arn"`
also this:
`            - name: controller.serviceAccount.annotations."eks\.amazonaws\.com\/role-arn"`
also this:
`            - name: controller.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"`

nothing seems to work, can you assist?

**Comment by k1rk** [comment]
@avifreege try
```
- name: controller.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
```

**Comment by hajdukd** [comment]
Added those params:

        - name: controller.metrics.service.annotations.prometheus\.io/port
          value: "10254"
        - name: controller.metrics.service.annotations.prometheus\.io/scrape
          value: "true"

Result is:

unable to decode "/dev/shm/2558446607": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string

None of the provided examples works.

**Comment by zen** [comment]
Anyone figured out what is a proper way to escape annotations? Example above does not seem to work for me, my case is:
```
name: argo-workflows.server.ingress.annotations.alb\.ingress\.kubernetes\.io/group.name
```

None of the variants worked

**Comment by dmitry-mightydevops** [comment]
### argo v2.8.2, worked for me this way:

```yaml
{{- if and (.Values.ingressNginx) (.Values.ingressNginx.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.argoNamespace | default "argo-cd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: config/addons/ingress-controllers/ingress-nginx
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        ingress-nginx:
          {{- omit .Values.ingressNginx "destinationNamespace" | toYaml | nindent 10 }}
      parameters:
      - name: ingress-nginx.controller.service.annotations.\external-dns\.alpha\.kubernetes\.io/hostname
        value: {{ .Values.hostname }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.ingressNginx.destinationNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}

```
