### ISSUE TITLE
is it possible that argocd manage multiple git branches?

### ISSUE THREAD

**Issue by Yejing0609** [argoproj/argo-cd#8504]
### Discussed in https://github.com/argoproj/argo-cd/discussions/8500

<div type='discussions-op-text'>

<sup>Originally posted by **Yejing0609** February 15, 2022</sup>
we have the below situation.
gitlab pipeline to build images and helm charts.
in github repo, we define the argocd managed application. The configuration is like below
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:workload
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: 'https://github.com/dev-cluster.git'
    targetRevision: HEAD
    path: argocd/workload
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

and under path `argocd/workload` we define again with the application's config
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: 'https://github.com/dev-cluster.git'
    targetRevision: HEAD
    path: argocd/workload/istio
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

and then the HEAD targetRevision will synced by argocd.

However in this case, if we want to test something like new images/new helm charts. we need to always modify the main branch's targetRevision. It is not convenient for developers to test app in k8s.
Do we have a way e.g. argocd can manage multiple git branches, and based on the settings in the git branch, it can deploy another application in the cluster?
or does someone have some other good solutions for it?
many thanks</div>
