### ISSUE TITLE
dex rundex cannot change logformat and loglevel

### ISSUE THREAD

**Issue by krrrr38** [argoproj/argo-cd#8524]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd-dex rundex` output both json and text log.

```
time="2022-02-16T08:39:44Z" level=info msg="Starting configmap/secret informers"
time="2022-02-16T08:39:46Z" level=info msg="Configmap/secret informer synced"
time="2022-02-16T08:39:46Z" level=info msg="0xc0000ec840 subscribed to settings updates"
{"level":"info","msg":"config using log level: debug","time":"2022-02-16T08:39:46Z"}
...
{"level":"info","msg":"listening (http) on 0.0.0.0:5556","time":"2022-02-16T08:40:02Z"}
{"level":"info","msg":"listening (grpc) on 0.0.0.0:5557","time":"2022-02-16T08:40:02Z"}
time="2022-02-16T08:43:22Z" level=info msg="Notifying 1 settings subscribers: [0xc0000ec840]"
time="2022-02-16T08:43:22Z" level=info msg="dex config unmodified"
```

Even if we add `logformat` option into `argocd-dex rundex`, we cannot use it. Because [dex can use logformat option](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-dex/) but, [dex rundex cannot use it](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-dex_rundex/).

```
Error: unknown flag: --logformat
Usage:
  argocd-dex rundex [flags]
Flags:
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
  -h, --help                           help for rundex
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to a kube config. Only required if out-of-cluster
  -n, --namespace string               If present, the namespace scope for this CLI request
      --password string                Password for basic authentication to the API server
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
      --server string                  The address and port of the Kubernetes API server
      --tls-server-name string         If provided, this name will be used to validate server certificate. If this is not provided, hostname used to contact the server is used.
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use
      --username string                Username for basic authentication to the API server
```

**To Reproduce**

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: argocd-dex-server-5b74fc996c-dw9ng
spec:
  containers:
  - command:
    - /shared/argocd-dex
    - rundex
    image: ghcr.io/dexidp/dex:v2.30.0
    name: dex-server
    ports:
    - containerPort: 5556
      name: http
    - containerPort: 5557
      name: grpc
    - containerPort: 5558
      name: metrics
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
  initContainers:
  - command:
    - cp
    - -n
    - /usr/local/bin/argocd
    - /shared/argocd-dex
    image: quay.io/argoproj/argocd:v2.2.5
    name: copyutil
  serviceAccountName: argocd-dex-server
```

**Expected behavior**

dex rundex can output `json` log by passing `logformat` option.

**Version**

- quay.io/argoproj/argocd:v2.2.5
- ghcr.io/dexidp/dex:v2.30.0

**Cause**

dex sub command cannot uses logformat/loglevel flags.

https://github.com/argoproj/argo-cd/blob/f1c972cae02e160fe19d86e389d7533e49ea5d5b/cmd/argocd-dex/commands/argocd_dex.go#L42-L43
