### ISSUE TITLE
ArgoCD: Upgrade from 2.1.9 to 2.2.4 or 2.3.0 issue with helm dependencies

### ISSUE THREAD

**Issue by s-u-b-h-a-k-a-r** [argoproj/argo-cd#8553]
facing this after upgrade from 2.1.9 to 2.2.4 or 2.3.0

rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download [https://repositories.cloud:443/artifactory/api/helm/sf-helm/mychart/mychart-1.0.4.tgz](https://repositories.cloud/artifactory/api/helm/sf-helm/mychart/mychart-1.0.4.tgz): failed to fetch [https://repositories.cloud:443/artifactory/api/helm/sf-helm/mychart/mychart-1.0.4.tgz](https://repositories.cloud/artifactory/api/helm/sf-helm/mychart/mychart-1.0.4.tgz) : 401 Unauthorized. 

My chart.yaml looks like below to pull dependency.
```
apiVersion: v2
description: Helm chart to deploy
name: main-chart
version: 1.0.0
dependencies:
- name: mychart
  version: 1.0.4
  repository: 'https://repositories.cloud/sf-helm'
```
Passing
passCredentials: true

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-helm-template-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/helm-demo.git'
    path: local/dev
    helm:
      passCredentials: true
      valueFiles:
        - values.yaml
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc/'
    namespace: poc
  syncPolicy:
    automated:
      prune: true
  project: poc
```
Added the credentials in argocd-cm
```
- url: 'https://repositories.cloud/sf-helm'
  type: helm
  name: sf-helm
  passwordSecret:
    name: argocd-repo-secrets
    key: token
  usernameSecret:
    name: argocd-repo-secrets
    key: user
```
