### ISSUE TITLE
Allow choosing which part (start/end) of a name will get truncated

### ISSUE THREAD

**Issue by dhirschfeld** [argoproj/argo-cd#8560]
In the application details view the names of the resources are truncated, making it impossible to understand the status of the resources at a glance - you have to hover over each resource to see it's name - e.g. what cron jobs are they?

![image](https://user-images.githubusercontent.com/881019/154619148-31ff4f14-991e-47cd-ab12-d06ab4de6829.png)

This becomes even more of an issue with larger applications. 

Since the important identifying information for my resources is at the *end* of the name I could improve the situation by monkey-patching the css to add a `direction: rtl`:
```css
.application-resource-tree__node-content {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    direction: rtl;
}
```

Which results in:

![image](https://user-images.githubusercontent.com/881019/154619073-e70169be-fd16-4fad-9701-5f4e26d0f4e5.png)

Maybe that's not ideal for all situations so it would be nice to be able to choose (perhaps initially as a global config) *which* side of the name will get truncated.
