### ISSUE TITLE
ignoreDifferences default group undocumented/leaving empty does not work on Ingress

### ISSUE THREAD

**Issue by Deaddy** [argoproj/argo-cd#8562]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have an ingress resource which I would like to ignore differences on certain json path fields, e.g. /spec/rules or /metadata/annotations, for the usual reasons we kubernetes people do not want to talk about, dirty hacks, special use cases, this and that, in this case we have some mechanism which temporarily changes backend service.

This ingress resource comes from a helm chart, though I do not believe this would be important to the issue.
I can not include the whole application YAML file, but here the part of the spec section I had to work with:

```
spec: 
  project: default

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: some-namespace
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true

  ignoreDifferences:
  - kind: "Ingress"
    jsonPointers:
    - /spec/rules
    - /metadata/annotations
 ```

Specifying it like this, does not lead to ignoring the annotations or rule changes; all changes made e.g. via `kubectl edit` or the editor in the webinterface or some kubectl are immediately reverted.

In the in-cluster `applications.argoproj.io` resources I do not see anything unexpected, so there is not an accidental `group: apps` directive (or leftover from first attempts using too much copypasta) or something like that.

Adding `group: "networking.k8s.io"` fixes my problem though, resulting in:
```
spec: 
  project: default

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: some-namespace
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true

  ignoreDifferences:
  - kind: "Ingress"
    group: "networking.k8s.io"
    jsonPointers:
    - /spec/rules
    - /metadata/annotations
```

**To Reproduce**

See above. Have an Ingress resource and try to ignore parts of it, without specifying the group explicitely. Possibly not-works with other resources not in the apps group as well, I have not tested this with other kinds.

**Expected behavior**

Documented behaviour of the `group` directive and its defaults, or leaving out the group object should default to match all resources with the correct kind, independent of group. For me I would totally be fine with some update to the documentation describing how it works, but as the group also did not 

All the examples and documentation use the `apps` group without further specifying what this refers to. I did find the correct group by inspecting the in-cluster `applications.argoproj.io` resource.

**Version**

Installed on k8s via manifests/install.yaml from release-2.3 branch.

```shell
argocd: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-04T23:39:21Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified   
```

**Logs**

I would not know what kind of logs would be useful here.
