### ISSUE TITLE
Registry login error with helm OCI private dependencies

### ISSUE THREAD

**Issue by jerousseau** [argoproj/argo-cd#8563]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Similar issue to this comment : https://github.com/argoproj/argo-cd/issues/8266#issuecomment-1027261191

When setting credentials templates that match a registry but that are not given as a repository (repocreds instead), the login fails because Argo CD [passes the schema oci:// as the registry URL](https://github.com/argoproj/argo-cd/blob/v2.3.0-rc1/reposerver/repository/repository.go#L487-L511), but helm (using oras-go) will fail because it does not support the oci:// schema, and so login command will fail

**To Reproduce**

1) Create an ArgoCD helm OCI repo-creds secret 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argoproj-gitlab-helm-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: registry.gitlab.com/test
  enableOCI: true
  type: helm
  password: my-password
  username: my-username
```

2) Use a chart with a dependencie that match the repo-creds url
```yaml
apiVersion: v2
name: test-chart
version: 1.0.0
dependencies:
- name: toto-spa
  version: 1.1.1
  repository: "oci://registry.gitlab.com/test/toto"
```

3) ArgoCD will try to login with oci scheme in url
```
helm registry login oci://registry.gitlab.com/test/toto --username ****** --password ******
```

**Expected behavior**
helm registry login without oci scheme in url

```shell
helm registry login registry.gitlab.com/test/toto --username ****** --password ******
```

**Version**

```shell
argocd: v2.2.5+8f981cc
  BuildDate: 2022-02-05T01:33:25Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64``
```

**Logs**

```
rpc error: code = Unknown desc = `helm registry login oci://registry.gitlab.com/test/toto --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin. time="2022-02-18T11:02:49Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get \"https://oci/v2/\": dial tcp: lookup oci on 10.32.0.10:53: no such host" Error: Get "https://oci/v2/": dial tcp: lookup oci on 10.32.0.10:53: no such host
```

**Comment by Exodus** [comment]
For reference, the configuration I'm using, that works, looks as such:

The credential template ends up as a secret in the same namespace as argocd:
```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-helm-foo
  namespace: argocd
data:
  name: foo
  enableOCI: true
  username: //redacted//
  password: //redacted//
  type: helm
  url: //redacted, looks like: foo.azurecr.io //
```

With an Application that looks like:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/foo/bar
    path: charts/foo-apps/testapp
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-testapp-dev.yaml
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
```

With a chart that looks like:
```
apiVersion: v2
name: testapp
description: Test chart
type: application
version: "0.1.0"
appVersion: "0.1.0"
dependencies:
  - name: testapp
    version: 1.2.41
    repository: oci://foo.azurecr.io/helm
```

**Comment by cippaciong** [comment]
@Exodus still not working for me, I can't understand what I'm missing.

This is my configuration:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: lab-helm-chart-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: dhl3
  url: datahow.azurecr.io/dhl/lab-helm-chart/chart-argocd
  type: helm
  enableOCI: "true"
  username: //redacted//
  password: //redacted//
```
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dhl-helm-oci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.switch.ch/t.sardelli/argocd-poc.git
    path: environments/dhl-helm-oci
    targetRevision: HEAD
  destination:
    namespace: dhl-helm-oci
    server: https://kubernetes.default.svc
```

```yaml
apiVersion: v2
name: dhl-helm-oci
description: Test Helm dependencies for ArgoCD
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: dhl3
  version: 0.5.0
  repository: oci://datahow.azurecr.io/dhl/lab-helm-chart/chart-argocd
```

This is the error I get with that configuration but I had different errors with different combinations of the configuration:
```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not retrieve list of tags for repository oci://datahow.azurecr.io/dhl/lab-helm-chart/chart-argocd: GET "https://datahow.azurecr.io/v2/dhl/lab-helm-chart/chart-argocd/dhl3/tags/list": unexpected status code 401: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```
