### ISSUE TITLE
argocd Application: Support kustomize  patch values 

### ISSUE THREAD

**Issue by mcbenjemaa** [argoproj/argo-cd#8579]
# Summary

What change you think needs making.

A new patching approach for arogcd Application with kustomize.

# Motivation

Please give examples of your use case, e.g. when would you use this.

Managing many platforms that essentially use almost the same applications is somehow cumbersome with apps of apps pattern or via a helm chart. (We want to avoid DRY as mush as possible!)
Using kustomize to build a common base for all platforms is really better and consistent.
All our members should know the Application manifests very well, and thus can apply patches more easily.

# Proposal

How do you think this should be implemented?

Adding a field to `ApplicationSourceHelm` so that kustomize users get the benifet of using it to apply patches.

**Comment by jsinme** [comment]
+1

**Comment by pc-tzimmerman** [comment]
Another use case:

If someone uses the PR generator & Git generator against the same Kustomize overlay, they may wish to `patch` the PR generator's Deployment name so that the PR container can be deployed alongside the normal container and otherwise use the same Service, ServiceAccount, etc. 

Currently you can do this by passing `nameSuffix` to the PR generator. But then, you duplicate all the other resources too. Including the Service, ServiceAccount, etc.

**Comment by r0bj** [comment]
Another use case is to use kustomize to change ingress host which is currently not possible without a patch (https://github.com/kubernetes-sigs/kustomize/issues/347).
For example:
```
$ cat ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              name: http

$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
patches:
- target:
    kind: Ingress
    name: test
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: new-host.example.com

$ kustomize build
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: new-host.example.com
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              name: http
        path: /
        pathType: Prefix
```

Note: Ingress host `test.example.com` was replaced with `new-host.example.com`.

**Comment by otherguy** [comment]
Similar usecase to @r0bj, I would like to add annotations to existing objects.

**Comment by crenshaw-dev** [comment]
> Adding a field to ApplicationSourceHelm so that kustomize users get the benifet of using it to apply patches.

I think I'd wanna do this at the top level so you can apply patches to more than just Helm sources.

**Comment by crenshaw-dev** [comment]
I could imagine something like this, basically borrowing [`patches`](https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_patchtransformer_) from Kustomize:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - pullRequest:
      github:
        owner: myorg
        repo: myrepository
  template:
    spec:
      patches:
      - patch: |
        - op: replace
          path: /spec/rules/0/host
          value: '{{branch}}.example.com'
        target:
          kind: Ingress
```
