### ISSUE TITLE
OutOfSync/Missing status for Job with ttl

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#8586]
I have below Job with ttl/backoff. ArgoCD deploys and runs the job fine at first but then it reports status 'OutOfSync' / Missing. 

```
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: auth
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
..............rest not relevant to this issue
```

![image](https://user-images.githubusercontent.com/33283496/155057133-b7754690-3f67-48ab-aefb-1e2312a18636.png)
![image](https://user-images.githubusercontent.com/33283496/155057190-e12513dd-22b2-4e37-9b5f-b0672e5e328c.png)

When i click details it shows live manifest (as empty) vs desired manifest (what is on git)

i'm on version 2.2.5

**Comment by danielhelfand** [comment]
Hey @tooptoop4,

There is a discussion [here](https://github.com/argoproj/argo-cd/discussions/8247) that looks related to Jobs with ttl. Maybe consider looking into [Resource Hooks](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies)?

**Comment by insider89** [comment]
Same for me. Hooks doesn't solve my issue, as we need to trigger job when image tag has changed in the job definitinon. Hooks don't trigger new sync when we update image version. Without hooks it works, but we need to remove Job somehow, we use ttlSecondsAfterFinished for it.

**Comment by danielhelfand** [comment]
@insider89 Can you provide more details on your set up? At what point does the Job run as part of a sync? 

My understanding is that Hooks aren't responsible for triggering a new sync but rather ordering of syncing resources and in this case when to clean up resources.

**Comment by insider89** [comment]
@danielhelfand  

My job definition looks like this one
```
apiVersion: batch/v1
kind: Job
metadata:
  name: something
spec:
  template:
    spec:
      containers:
      - name: say-something
        image: busybox:{{ .Values.busybox.image.tag }}
        command: ["echo", "Running a job"]
      restartPolicy: OnFailure
  backoffLimit: 2
```

Time to time we update image and need to redeploy job. When we use ArgoCD hooks, it's just ignore `.Values.busybox.image.tag` in Application definition.

Application definition:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databand-pubsub-test-pubsub-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test-project
  destination:
    server: https://kubernetes.default.svc
    namespace: test-project
  source:
    repoURL: https://gitlab.com/api/v4/projects/1234566/packages/helm/stable
    chart: say-something
    targetRevision: 0.1.50
    helm:
      values: |
        busybox:
          image:
            tag: unstable-musl
  # Sync policy
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
```

With ArgoCD hooks(Sync,PreSync,PostSync) in the job definition, I see that `busybox.image.tag` updated in Application definition, but it's not trigger new automated sync. I need to trigger sync manually. This is not what I want. I want that change in the `busybox.image.tag` trigger sync automatically. 

If I don't use ArgoCD hooks, image field cannot be updated, cause it's immutable. So I need to delete job somehow to update image tag. I tried to use [k8s](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) `ttlSecondsAfterFinished`, but when Job delete in TTL time, ArgoCD showed OutOfSync application. I tried to add `ignoreDifferences`, but it doesn't work:

```
spec:
  ignoreDifferences:
    - group: "batch"
      kind: "Job"
```

Any suggestion on how to overcome it?
