### ISSUE TITLE
Resources no longer in Git not deleted when using v2 ConfigManagementPlugin

### ISSUE THREAD

**Issue by timspeetjens** [argoproj/argo-cd#8611]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When using Configuration Management Plugin v2 sidecars, resources are no longer cleaned up if they no longer exist in git.

No label or annotation (`resourceTrackingMethod`) is added to track ArgoCD managed resources.

**To Reproduce**

Create a CM defining a simple ConfigManagementPlugin, for example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: concatenate-yaml-cm-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: concatenate-yaml-cm-plugin
    spec:
      version: v1.0
      generate:
        command: [sh, -c]
        args: ["find . -name '*.yaml' -exec cat {} \\;"]
      discover:
        fileName: ".concatenate-yaml"
```

Add a sidecar to configure the plugin for the argocd-repo-server deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    ...
    spec:
      containers:
      - command:
        - /var/run/argocd/argocd-cmp-server
        image: ...
        name: concatenate-yaml
        volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: concatenate-yaml-cm-plugin
          subPath: plugin.yaml
        - mountPath: /tmp
          name: tmp
    ...
```

Configure an application with a git repo, add one or more files to define CRDs to the git repo.

When adding the discover file (`.concatenate-yaml`) the label and/or annotation are not present after sync.
When removing a CRD or removing the application cleanup does not happen.

When removing the discover file, the label and/or annotation are present, and removing a CRD or removing the application cleans up correctly.

To make sure the plugin is activated, I changed the args to `args: ["find . -name '<required-prefix>*.yaml' -exec cat {} \\;"]`, so I know the plugin setup is correct (as CRDs defined in files not matching the prefix were deleted).

Changing `allowConcurrency` or `lockRepo` attributes don't seem to change behaviour.

**Expected behavior**

Resources should be deleted if they no longer exist in git, also for applications that make use of the ConfigManagementPlugin v2.

The default behaviour should be to use the `app.kubernetes.io/instance` label, but neither of the options for `resourceTrackingMethod` seem to be respected with CMP v2 active.

Not using a CMP v2 plugin at all results in correct behaviour, respecting the `resourceTrackingMethod`.

**Version**

```shell
$ argocd version
argocd: v2.2.5+8f981cc
  BuildDate: 2022-02-05T01:33:25Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.5+8f981cc
```
