### ISSUE TITLE
Helm values starting from dash are parsed wrong

### ISSUE THREAD

**Issue by okgolove** [argoproj/argo-cd#8636]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Passing helm parameters in values starting with dash are parsed wrong by ArgoCD. Instead of setting it `as is` ArgoCD adds new line. It seems it is parsed like yaml list element.

**To Reproduce**

* Create an app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  labels:
    app: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://sonarsource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: "2.0.0"
    helm:
      values: |
        fullnameOverride: sonarqube

        plugins:
          install:
            - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.10.0/sonarqube-community-branch-plugin-1.10.0.jar"
            - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.0.1/sonar-dependency-check-plugin-3.0.1.jar"

        jvmOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=web"
        jvmCeOpts: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=ce"

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
```

* Check app manifest in ArgoCD ui:
```yaml

      jvmOpts:
      '-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=web'

      jvmCeOpts:
      '-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=ce'
```
see screenshot

If I add a space before `-javaagent` everything works properly:
```
        jvmOpts: " -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=web"
        jvmCeOpts: " -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=ce"
```

**Expected behavior**

Application installed properly, jvmOpts and jvmCeOpts are parsed properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/36846182/156191291-95789d9a-9fb1-4b13-bd41-038fa5f43101.png)

**Version**

```shell
argocd: v2.2.5+8f981cc.dirty
  BuildDate: 2022-02-05T05:20:39Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: dirty
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64

  BuildDate: 2022-02-05T01:33:25Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
The newline doesn't appear in the manifests as stored by the cluster (`kubectl get app -oyaml`), even after editing in the UI. My guess is that this is a bug in the Monaco editor's YAML code. Can a UI person take a look?

**Comment by okgolove** [comment]
Doesn't it? I see there is a new line:

```yaml
  containers:
  - env:
    - name: SONAR_WEB_JAVAOPTS
      value: -javaagent:/opt/sonarqube/data/jmx_prometheus_javaagent.jar=8000:/opt/sonarqube/conf/prometheus-config.yaml
        -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=web
    - name: SONAR_CE_JAVAOPTS
      value: -javaagent:/opt/sonarqube/data/jmx_prometheus_javaagent.jar=8001:/opt/sonarqube/conf/prometheus-ce-config.yaml
        -javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.10.0.jar=ce
```


<img width="1381" alt="image" src="https://user-images.githubusercontent.com/36846182/156197202-dbf00a61-cf4b-472f-ba4b-305acff332fc.png">
