### ISSUE TITLE
Allow an application to include a resource that has been excluded in the configmap

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [argoproj/argo-cd#8662]
# Summary

The application resource can optionally include a resource that has been excluded in the centralized configmap.

# Motivation

In our case, we are excluding all `Secret` resources since we are not keeping `Secrets` in our repos. Instead we use the [`ExternalSecret`](https://github.com/external-secrets/kubernetes-external-secrets) resource to handle them.

But in some rare cases, we might have a secret in our repo for an application. Case in point is the argocd secret for handling a repository with credentials defined in the credential template. Here is an example of that secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/argoproj/private-repo
```
In this case, the `url` is not necessary a "secret" information and can be stored in our repo itself and hence an `ExternalSecret` resource is not needed. But, we can't reconcile the above secret resource since its excluded in our configmap.

# Proposal

I propose an additional property under `spec` in the same format as `resource.inclusion` which will merge-patch over the configmap setup. For example
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: myserver
  project: default
  source:
    path: path
    repoURL: repourl
    targetRevision: revision
  resource.inclusions: |
    - apiGroups:
      - "*"
      kinds:
      - Secret
      clusters:
      - "*"
```
This should allow the reconciliation of `Secret` resources only for this application
