### ISSUE TITLE
Argo CD notification does not work when error message contains `"`

### ISSUE THREAD

**Issue by czchen** [argoproj/argo-cd#8665]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The Argo CD notification template in [here](https://github.com/argoproj/argo-cd/blob/master/notifications_catalog/install.yaml#L70-L77) does not escape `{{$c.message}}`. So if the error message contains `"`, it becomes invalid json and notification cannot be sent.

**To Reproduce**

* In `argocd-cm`, use the following to setup a dummy plugin:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |-
    - name: dummy
      generate:
        command: ['sh', '-c']
        args: ['echo "\\"" && false']
```

* Use this dummy plugin to create an `Application`. The `$c.message` will be `"`.
* The Argo CD notification template which uses `$c.message` will break due to unescaped `"`.

**Expected behavior**

Notification shall be sent correctly when app status becomes unknown.

**Version**

```shell
argocd: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-04T23:39:21Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```
