### ISSUE TITLE
While creating New APP via UI if Retry is clicked it gets unchecked upon clicking else

### ISSUE THREAD

**Issue by rishabh625** [argoproj/argo-cd#8682]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Bug is related to UI, while creating app if Retry option is selected and after that if Edit as Yaml is clicked and then cancel it, retry shows unchecked but retryoption values are populated

**To Reproduce**

1) Click on Create New APP
2) Select Retry
3) Click on Edit as Yaml
4) Click on cancel
5) Retry is unchecked

**Expected behavior**

Retry options should be shown on UI

**Screenshots**

<img width="1648" alt="Screenshot 2022-03-04 at 8 08 14 PM" src="https://user-images.githubusercontent.com/43094970/156782969-520fa2a6-9b97-448a-847c-8ef6f7d0e1da.png">

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by keithchong** [comment]
Reproducible 

{
    "Version": "v2.3.0+637cee4",
    "BuildDate": "2022-03-04T18:55:16Z",
    "GitCommit": "637cee40170d67446c3fe2294b25dd4fd60a9ca4",
    "GitTreeState": "clean",
    "GoVersion": "go1.17.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.0+gd141386",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}

**Comment by keithchong** [comment]
Here's a related issue:

1. Click on Create New App
2. Edit Yaml
3. Add:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ''
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  project: ''
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 15s
        maxDuration: 5m0s
        factor: 3
```
4. Save
--> The Retry button is not check and the section is not populated with the correct values
