### ISSUE TITLE
Allow to define prune by default for manual sync applications

### ISSUE THREAD

**Issue by gaeljw** [argoproj/argo-cd#8686]
# Summary

For applications not defined with automated sync, I'd still like to define (declaratively in the YAML) that the manual sync should use pruning.

Currently pruning implies automated sync:
```
spec:
  syncPolicy:
    automated:
      prune: true
```

# Motivation

I have applications on which I don't want to enable automated sync for safety but still not have to check "prune" option each time a manual sync is done.

# Proposal

`prune` option could be moved outside of `automated`.

Not sure of the best way to not do a breaking change though.

**Comment by diclophis** [comment]
This would be a huge win in usability... would it work if we made a `syncPolicy.manual` sub-key?

**Comment by alexef** [comment]
I would suggest that automated is decoupled from `prune`, and we have a structure like this:

```
spec:
  syncPolicy:
     automated:
        enabled: <boolean>
        selfHeal: <boolean>
    prune: <boolean>
```
so that making changes to `syncPolicy.automated.enabled` does not change the desired value of `selfHeal`, while `prune` becomes a policy common to `automated` and non-automated (manual) modes.
