### ISSUE TITLE
Support recursive option with Kustomize

### ISSUE THREAD

**Issue by gaeljw** [argoproj/argo-cd#8695]
# Summary

It would be nice to support a recursive option with Kustomize so that a single ArgoCD application can refer to a directory that contains subdirectories containing themselves a `kustomization.yaml` file.

This is related to both:
- https://github.com/argoproj/applicationset/issues/530 for the use case (more below)
- https://github.com/argoproj/argo-cd/issues/3181

# Motivation

Imagine the following manifests structure in a GitOps repository:

```
- dev
    - instanceA
        - kustomization.yaml
    - instanceB
        - kustomization.yaml
- prod
    - instanceA
        - kustomization.yaml
    - instanceB
        - kustomization.yaml
    - instanceC
        - kustomization.yaml
    - instanceD
        - kustomization.yaml
```

I'm using ApplicationSet to define two ArgoCD applications: one for dev platform, the other one for prod platform.

I would like to be able to say to ArgoCD that my application source is `../prod` and to recurse in all subdirectories.

# Proposal

I would like to be able to have an option when defining an Application with either a recurse option or a glob pattern maybe?

Something like this:
```yaml
  spec:
      source:
        repoURL: yyy
        path: xxx/prod/instances
        kustomize:
          recurse: true # <-- new option
```

Or this:
```yaml
  spec:
      source:
        repoURL: yyy
        path: xxx/prod
        kustomize:
          patterns: 'instances/*' # <-- new option
```

:warning: The recursive option might be hard to implement though because of Kustomize principles: if a `kustomization.yaml` refers itself to a subdirectory, it makes no sense to deploy the subdirectory.

For instance:
```
- instances
  - instance1
    - kustomization.yaml # <-- refers to somesubdir
    - somesubdir
      - kustomization.yaml # <-- this file should not be considered then
```
