### ISSUE TITLE
Show manifests for target history id of a helm app

### ISSUE THREAD

**Issue by bruno-villa** [argoproj/argo-cd#8783]
# Summary

Given an ArgoCD app of type Helm, whose values are directly defined in the app
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    helm:
      releaseName: myrelease
      values: |-
        myvalue: demo
        ...
```
it is expected to have an app history where the revision (chart version) does not change but the values do. E.g.
```
$ argocd app history $APP_NAME
ID  DATE                           REVISION
0   2022-03-15 11:14:59 +0100 CET  0.2.16
1   2022-03-15 11:24:09 +0100 CET  0.2.16
```
Ideally it should be possible to compare manifests by running e.g.
```
argocd app manifests $APP_NAME --history-id 0
```
Currently `argocd app manifests` only supports the `--revision` flag, which corresponds to the chart version. Since the chart version does not change it is not possible to compare the detailed manifests for the two releases in the history. 

# Motivation

This would allow for quick comparison of versions at the manifest level. The same can be achieved with helm template and the original values which should be tracked in git regardless. Nevertheless, having access to this information from the ArgoCD CLI would simplify the process in addition to being consistent with the process for e.g. a kustomize app.

# Proposal

Given that the history already holds the values and chart version used it should be possible to run helm template on the server and return the yaml to the user.
