### ISSUE TITLE
Environment variables with "=" in their values ignored for sidecar CMPs

### ISSUE THREAD

**Issue by ilya-lesikov** [argoproj/argo-cd#8792]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Environment variables with "=" in their values passed to sidecar Config Management Plugins via Application CR are ignored and are not available in the CMP environment.

**To Reproduce**

Config Management Plugin running as a sidecar not receiving `$IGNORED` env var, only `$PASSED` env var, for ArgoCD Application like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  destination:
    namespace: werf-pull-ci-cd-demo-production
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: werf-pull-ci-cd-demo
    plugin:
      env:
      - name: PASSED
        value: val1
      - name: IGNORED
        value: key1=val1
    repoURL: registry.flant.com/werf
    targetRevision: 0.1.148272
```

**Expected behavior**

`$IGNORED` env var passed to the Config Management Plugin environment too, not only `$PASSED`.

**Version**

```shell
argocd: v2.2.4+78d749e
  BuildDate: 2022-02-03T20:41:00Z
  GitCommit: 78d749ec88bea5a5e851fc48b9404fdf067192b6
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0+969c7a1
  BuildDate: 2022-03-16T05:09:55Z
  GitCommit: 969c7a173519618cffbee9aa0b7d0e56e178fcda
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```
