### ISSUE TITLE
ApplicationSet either silently doesn't create app or errors when using hardcoded values

### ISSUE THREAD

**Issue by bentcoder** [argoproj/argo-cd#8826]
Hi,

As you can see below, the `template` content of `ApplicationSet` is an exact match to `Application` config, however I am unable to create app with `ApplicationSet` (_`Application` config creates app_). Is there anything wrong in my `ApplicationSet` config? I tried single quotes to wrap values but nothing changed.

Thanks

`$ argocd app create --file config.yaml`

---

This works fine.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-dev

spec:
  project: default
  source:
    repoURL: https://github.com/me/config
    path: infra/helm/hello
    targetRevision: HEAD
    helm:
      valueFiles:
        - dev.yaml
  destination:
    name: dev
    namespace: default
```

---

This doesn't create app and doesn't even output anything!

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello

spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://192.168.99.109:8443
  template:
    metadata:
      name: hello-{{cluster}}
    spec:
      project: default
      source:
        repoURL: https://github.com/me/config
        path: infra/helm/hello # tried `chart` instead of `path`
        targetRevision: HEAD
        helm:
          valueFiles:
            - {{cluster}}.yaml
      destination:
        name: {{cluster}}
        namespace: default
```

---

This doesn't create app but outputs error below.

```bash
FATA[0000] rpc error: code = InvalidArgument desc = application spec for hello is invalid: InvalidSpecError: repository not accessible: rpc error: code = Unknown desc = error testing repository connectivity: Repository '' cannot be initialized, because its root would be system temp at /tmp
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello

spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://192.168.99.109:8443
  template:
    metadata:
      name: hello-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/me/config
        path: infra/helm/hello # tried `chart` instead of `path`
        targetRevision: HEAD
        helm:
          valueFiles:
            - dev.yaml
      destination:
        name: dev
        namespace: default
```

**Version**

```shell
argocd version
argocd: v2.2.5+8f981cc.dirty
  BuildDate: 2022-02-05T05:39:12Z
  GitCommit: 8f981ccfcf942a9eb00bc466649f8499ba0455f5
  GitTreeState: dirty
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.4+78d749e
  BuildDate: 2022-02-03T20:41:00Z
  GitCommit: 78d749ec88bea5a5e851fc48b9404fdf067192b6
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```
