### ISSUE TITLE
Application OutOfSync foverver. Manifest rendered by argocd does not match the apiserver's version

### ISSUE THREAD

**Issue by juliohm1978** [argoproj/argo-cd#8833]
**Describe the bug**
The application status never reaches **Synced**, it stays forever in **OutOfSync**.

Clicking the APP DIFF button shows that the differences between the rendered manifest and the apiserver response:

![image](https://user-images.githubusercontent.com/4145456/159188720-5e0d4b97-f1eb-45a7-9fba-05ce939f0f49.png)

In this case, the differences are apparently meaningless:

* cpu limits compared as '1' (string) and 1 (int)
* probe initialDelaySeconds compared as 0 and `(nothing)`.

How can I make this work? Any application configuration I can use to make argocd ignore those differences?

**Comment by juliohm1978** [comment]
One way to workaround the issue is to define `ignoreDifferences` in the application spec.

```yaml
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].livenessProbe
        - .spec.template.spec.containers[].readinessProbe
        - .spec.template.spec.containers[].startupProbe
        - .spec.template.spec.containers[].resources
```

But I'm not sure this would be acceptable, because it prevents the application from updating these values via argocd.
