### ISSUE TITLE
App of apps cannot be deleted

### ISSUE THREAD

**Issue by przemolb** [argoproj/argo-cd#8841]
Checklist:

```
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-11T00:01:03Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.1+b65c169
  BuildDate: 2022-03-10T22:51:09Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0

```
**Describe the bug**

I had several simple (POC) applications deployed using app-of-apps approach. I wanted to delete all of them by deleteing the top one but it looks like it cannot be deleted:
```
> kubectl delete Application top-app -n argocd
application.argoproj.io "top-app" deleted

      <- no prompt here !!!

> kubectl get applications -A
NAMESPACE   NAME           SYNC STATUS   HEALTH STATUS
argocd      top-app        OutOfSync     Healthy
```

I manually deleted successfully all the other apps (non-top) but the top one still cannot be deleted.
How do I enforce its deletion ?

**Comment by gaeljw** [comment]
Can you share more details about how the "top-app" is registered into ArgoCD? Isn't it part of another app of apps that is this recreating it when you delete it?

**Comment by przemolb** [comment]
@gaeljw this is the top-app (app of apps):
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: top
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://ourgitrepo'
    targetRevision: master
    path: argocd/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```
It isn't part of another app - this is the real "top".
