### ISSUE TITLE
Allow yaml for helm values instead of, or additionally to string literals.

### ISSUE THREAD

**Issue by jeromewaibel** [argoproj/argo-cd#8850]
# Summary

I'd like to declare helm values as "real" yaml instead of string literals.

For example this

```
apiVersion: argoproj.io/v1alpha1
kind: Application
[...]
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    helm:
      values: |
        metrics:
          enabled: true
        global:
          storageClass: cinder-csi-testing
        master:
          persistence:
            size: 1Gi
```

should be possible to be declared like this (helm.values of type "map" instead of "string literal")

```
apiVersion: argoproj.io/v1alpha1
kind: Application
[...]
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    helm:
      values:
        metrics:
          enabled: true
        global:
          storageClass: cinder-csi
        master:
          persistence:
            size: 1Gi
```

For example, ansibles's [kubernetes.core.helm](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html) has this configuration syntax.

# Motivation

Helm values have to be declared as string literals, which makes it difficult to remove/update/add single lines with kustomize (see [this SO question](https://stackoverflow.com/questions/71560933/is-there-a-way-to-update-or-merge-string-literals-with-kustomize) for more details). I am well aware of the "helm.parameters" syntax, but find it cumbersome to read and not quite flexible to use as kustomize.

With my proposal implemented I could easily write a kustomize.yml

```
patchesJson6902:
-  patch: |-
    - op: replace
      path: /source/helm/values/master/persistence/size
      value: 50Gi
```
