### ISSUE TITLE
pod argocd-applicationset-controller: CreateContainerConfigError (missing securityContext?)

### ISSUE THREAD

**Issue by knweiss** [argoproj/argo-cd#8885]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The pod `argocd-applicationset-controller` of argocd-2.3.1 will not come up because of `CreateContainerConfigError`.

```
    NAME                                                    READY   STATUS                       RESTARTS   AGE
    pod/argocd-applicationset-controller-865b97c4c5-klsl4   0/1     CreateContainerConfigError   0          6h18m
```
The root cause seems to be a privilege issue as in this k8s cluster no privileged containers are allowed.

When I modify the deployment `argocd-applicationset-controller` and add the following `securityContext` section,
the pod will at least start (however I did not have the time to test the functionally yet):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd-applicationset
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
```

Both, `runAsNonRoot` and `runAsUser` are necessary for the pod to start without `CreateContainerConfigError` status.

**To Reproduce**

Standard installation of non-HA argocd-2.3.1 with `kubectl apply`.

**Expected behavior**

pod `argocd-applicationset-controller` starts.

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.3.2+ecc2af9
  BuildDate: 2022-03-23T02:04:18Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by ledroide** [comment]
The bug is still there in v2.3.2.

Alternative workarounds if you don"t want to fork from the standard manifests : 

1. Patch with Kustomize (my recommendation)
kustomization.yaml
```yaml
patches:
  - path: applicationset-controller.patch.yaml
    target:
      kind: Deployment
      name: argocd-applicationset-controller
```
applicationset-controller.patch.yaml
```yaml
- op: add
  path: /spec/template/spec/containers/0/securityContext
  value:
    runAsNonRoot: true
    runAsUser: 1000
```

2. OR create a specific PodSecurityPolicy that allows to run as root
```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hack-for-applicationset-controller
spec:
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - configMap
    - emptyDir
    - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-psp:applicationset-controller
  namespace: argocd
rules:
  - apiGroups:
      - policy
    resourceNames:
      - hack-for-applicationset-controller
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-psp:applicationset-controller-binding
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-psp:applicationset-controller
subjects:
  - kind: ServiceAccount
    name: argocd-applicationset-controller
    namespace: argocd
```
