### ISSUE TITLE
Custom tools envsubst binary can not be executed

### ISSUE THREAD

**Issue by Jojoooo1** [argoproj/argo-cd#8888]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After downloading the envsubst library and copy it to the argocd-repo-server it does not execute.

![Screenshot from 2022-03-24 09-02-45](https://user-images.githubusercontent.com/17641873/159912239-8d680235-92f4-4967-b7b5-659b765e0842.png)

```yaml
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
        - name: custom-tools
          emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
        - name: download-tools
          image: alpine:3.15.0
          command: [sh, -c]
          args:
            - apk --no-cache add gettext libintl && cp /usr/bin/envsubst /custom-tools/
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools

      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/envsubst
              name: custom-tools
              subPath: envsubst
```

**Expected behavior**

envsubst should be executed so i can use it a plugin.

**Version**
argoCD 2.3.2

```shell
Paste the output from `argocd version` here.
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-10T22:51:09Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
