### ISSUE TITLE
Argocd ignores ignoreMissingValueFiles flag in ApplicationSet resource

### ISSUE THREAD

**Issue by kokolight** [argoproj/argo-cd#8892]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I am trying to create a ApplicationSet resource and use the flag `ignoreMissingValueFiles` so ArgoCD will ignore value files that don't exist.
In my environment, I have env specific values files and cloud vendor specific values files, for example:
Sometimes my chart needs to apply values.aws.yaml and in some charts they it doesn't exist. But I need to option to have ArgoCD check if file exists so I can mention them all in the ApplicationSet resource file.

**To Reproduce**
- Install ArgoCD helm chart by running
```
helm upgrade --install argocd argo/argo-cd -n argocd --version "4.2.2"
```
- Create an appset - this is the yaml file I used.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://gitlab.com/<my_git_path>
        revision: HEAD
        directories:
          - path: state/*
  template:
    metadata:
      name: "{{"{{path.basename}}"}}"
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/<my_git_path>
        targetRevision: HEAD
        path: "{{"{{path}}"}}"
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - ../values.yaml
            - values.yaml
            - values.{{ .Values.envName }}.yaml
      syncPolicy: {}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
```
for this example the `.Values.envName` is `qa2`

**Expected behavior**
The applications will be created and the missing value files will be ignored.

**Actual Results**
ArgoCD shows an error on each application that it couldn't find one of the value files (although it should be ignored)

**Screenshots**

![image](https://user-images.githubusercontent.com/17180188/159961984-758d8e66-f3b4-47ad-92b3-620d7a768244.png)
I had to hide some details.
As you can see, ArgoCD is still complaining that the value file `values.qa2.yaml` doesn't exist although I specify the `ignoreMissingValueFiles` flag in the appset yaml file.

**Version**
```shell
argocd: v2.3.2+ecc2af9.dirty
  BuildDate: 2022-03-23T05:19:12Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.3.2+ecc2af9
  BuildDate: 2022-03-23T00:40:57Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**
```
Will add if needed
```
