### ISSUE TITLE
Can't sync app if all components have hook

### ISSUE THREAD

**Issue by EwdAger** [argoproj/argo-cd#8908]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have the following helm package:

- a pre-start job
- a deployment
- a post-start job

So I added weight hooks (some say sync-waves in argo-cd) to each component. Everything is perfect when creating an application with Argo-CD. But when i want to update my application. I found i can't choose any component in SYNCHRONIZE RESOURCES menu. 
meanwhile i can't click synchronize button.

Also, I found that argo-CD could not sync a component that had a weight-hook.

**To Reproduce**

1. create a app such as:

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-job
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": "pre-upgrade, pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: pre-job
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": "pre-upgrade, pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-job
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": "pre-upgrade, pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: post-job
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```
2. click Sync buttom in argo-cd 

**Expected behavior**

I think argo-cd should support Sync components with hooks. And can select each component with or without hooks in SYNCHRONIZE RESOURCES menu. 

**Screenshots**

![2c5c0e7b3ee063cf5f3c3363abb846a](https://user-images.githubusercontent.com/23358389/160399083-4957c44f-9aec-48d5-b7bf-a2017e3d63bc.jpg)

**Version**

```shell
Paste the output from `argocd version` here.
```
argocd: v2.1.4+d5c6608
  BuildDate: 2021-10-20T00:36:52Z
  GitCommit: d5c66088272c83e1b8b78562ce100006833c2d74
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.1+122ecef
**Logs**

```
Paste any relevant application logs here.
```
