### ISSUE TITLE
CLI sync takes ~1m every time

### ISSUE THREAD

**Issue by travisgroth** [argoproj/argo-cd#8910]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It seems that whenever I'm running `argocd app sync` - either with or without `--dry-run` enabled - the command always takes just over 1 minute to return.  This appears regardless of Application complexity.

**To Reproduce**

Create a basic application.  Eg:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-repositories
  namespace: argocd
spec:
  project: argocd

  source:
    repoURL: https://github.com/XXXXX/YYYYY.git
    targetRevision: HEAD
    path: sources/helm

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 10
```

`/sources/helm/sources.yaml`
```
apiVersion: v1
kind: Secret
metadata:
  name: bitnami
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  url: https://charts.bitnami.com/bitnami
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: grafana
  url: https://grafana.github.io/helm-charts
  type: helm
```

```bash
time argocd app sync helm-repositories --dry-run && date
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2022-03-28T11:14:18-04:00             Secret      argocd               bitnami    Synced
2022-03-28T11:14:18-04:00             Secret      argocd               grafana    Synced

Name:               helm-repositories
Project:            argocd
Server:             https://kubernetes.default.svc
Namespace:          argocd
URL:                https://XXXXXXX
Repo:               https://XXXXXXX
Target:             HEAD
Path:               sources/helm
SyncWindow:         Sync Allowed
Sync Policy:        Automated (Prune)
Sync Status:        Synced to HEAD (257f2d9)
Health Status:      Healthy

Operation:          Sync
Sync Revision:      257f2d9e1fb15dbfad453a9308e6d71efae96dd7
Phase:              Succeeded
Start:              2022-03-28 11:14:17 -0400 EDT
Finished:           2022-03-28 11:14:18 -0400 EDT
Duration:           1s
Message:            successfully synced (no more tasks)

GROUP  KIND    NAMESPACE  NAME                  STATUS  HEALTH  HOOK  MESSAGE
       Secret  argocd     bitnami               Synced                secret/bitnami configured (dry run)
       Secret  argocd     grafana               Synced                secret/grafana configured (dry run)
argocd app sync helm-repositories --dry-run  0.10s user 0.06s system 0% cpu 1:01.74 total
Mon Mar 28 11:15:18 EDT 2022
```

**Expected behavior**

Run time to be fairly linear with application complexity, _especially_ if it is already synced and we're in dry run mode.  

Sync in the UI for this same application runs almost instantly.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.3.2+ecc2af9.dirty
  BuildDate: 2022-03-23T05:13:28Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.3.2+ecc2af9
  BuildDate: 2022-03-23T00:40:57Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:17Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.claims="{\"at_hash\":\"n4EG4yd2G0LNOumsXXksxg\",\"aud\":\"argo-cd-cli\",\"c_hash\":\"nFl1LcjJfnSQUUK-AuKF-Q\",\"email\":\"ZZZZZ@XXXXXXXXXX\",\"email_verified\":true,\"exp\":1648566531,\"groups\":[\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\"],\"iat\":1648480131,\"iss\":\"https://argocd.YYYY.XXXXXXXXXX//api/dex\",\"name\":\"Travis Groth\",\"sub\":\"ChUxMTc4OTU5NjU3ODQ5OTc1MzE4ODQSBmdvb2dsZQ\"}" grpc.request.content= grpc.service=version.VersionService grpc.start_time="2022-03-28T15:23:17Z" span.kind=server system=grpc
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:17Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2022-03-28T15:23:17Z" grpc.time_ms=13.29 span.kind=server system=grpc
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:17Z" level=info msg="received unary call /application.ApplicationService/Sync" grpc.method=Sync grpc.request.claims="{\"at_hash\":\"n4EG4yd2G0LNOumsXXksxg\",\"aud\":\"argo-cd-cli\",\"c_hash\":\"nFl1LcjJfnSQUUK-AuKF-Q\",\"email\":\"ZZZZZ@XXXXXXXXXX\",\"email_verified\":true,\"exp\":1648566531,\"groups\":[\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\"],\"iat\":1648480131,\"iss\":\"https://argocd.YYYY.XXXXXXXXXX//api/dex\",\"name\":\"Travis Groth\",\"sub\":\"ChUxMTc4OTU5NjU3ODQ5OTc1MzE4ODQSBmdvb2dsZQ\"}" grpc.request.content="name:\"helm-repositories\" revision:\"\" dryRun:true prune:false strategy:<hook:<syncStrategyApply:<force:false > > > " grpc.service=application.ApplicationService grpc.start_time="2022-03-28T15:23:17Z" span.kind=server system=grpc
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:17Z" level=info msg="ZZZZZ@XXXXXXXXXX initiated sync to HEAD (257f2d9e1fb15dbfad453a9308e6d71efae96dd7)" application=helm-repositories dest-namespace=argocd dest-server="https://kubernetes.default.svc" reason=OperationStarted type=Normal
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:17Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Sync grpc.service=application.ApplicationService grpc.start_time="2022-03-28T15:23:17Z" grpc.time_ms=293.847 span.kind=server system=grpc
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:18Z" level=info msg="received unary call /application.ApplicationService/Get" grpc.method=Get grpc.request.claims="{\"at_hash\":\"n4EG4yd2G0LNOumsXXksxg\",\"aud\":\"argo-cd-cli\",\"c_hash\":\"nFl1LcjJfnSQUUK-AuKF-Q\",\"email\":\"ZZZZZ@XXXXXXXXXX\",\"email_verified\":true,\"exp\":1648566531,\"groups\":[\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\"],\"iat\":1648480131,\"iss\":\"https://argocd.YYYY.XXXXXXXXXX//api/dex\",\"name\":\"Travis Groth\",\"sub\":\"ChUxMTc4OTU5NjU3ODQ5OTc1MzE4ODQSBmdvb2dsZQ\"}" grpc.request.content="name:\"helm-repositories\" resourceVersion:\"\" selector:\"\" repo:\"\" " grpc.service=application.ApplicationService grpc.start_time="2022-03-28T15:23:18Z" span.kind=server system=grpc
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:18Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=application.ApplicationService grpc.start_time="2022-03-28T15:23:18Z" grpc.time_ms=11.649 span.kind=server system=grpc
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:23:18Z" level=info msg="received streaming call /application.ApplicationService/Watch" grpc.method=Watch grpc.request.claims="{\"at_hash\":\"n4EG4yd2G0LNOumsXXksxg\",\"aud\":\"argo-cd-cli\",\"c_hash\":\"nFl1LcjJfnSQUUK-AuKF-Q\",\"email\":\"ZZZZZ@XXXXXXXXXX\",\"email_verified\":true,\"exp\":1648566531,\"groups\":[\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\",\"ZZZZZ@XXXXXXXXXX\"],\"iat\":1648480131,\"iss\":\"https://argocd.YYYY.XXXXXXXXXX//api/dex\",\"name\":\"Travis Groth\",\"sub\":\"ChUxMTc4OTU5NjU3ODQ5OTc1MzE4ODQSBmdvb2dsZQ\"}" grpc.request.content="name:\"helm-repositories\" resourceVersion:\"419991028\" selector:\"\" repo:\"\" " grpc.service=application.ApplicationService grpc.start_time="2022-03-28T15:23:18Z" span.kind=server system=grpc
argocd-server-768489d658-x4zbj argocd-server time="2022-03-28T15:24:18Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=Watch grpc.service=application.ApplicationService grpc.start_time="2022-03-28T15:23:18Z" grpc.time_ms=60000.027 span.kind=server system=grpc
```
