### ISSUE TITLE
Application Details destination cluster is "in-cluster (undefined)"

### ISSUE THREAD

**Issue by wmgroot** [argoproj/argo-cd#8945]
Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**

When viewing the Application Details in the ArgoCD UI, the cluster destination appears as "in-cluster (undefined)".

**To Reproduce**

I'm not exactly sure when this became a problem, but it was not an issue while we were using version 2.2.5. We are observing this behavior on version 2.3.2.

We have 3 primary instances of ArgoCD running in our clusters, two with about 2000 Applications each, and one instance we use to install the other ArgoCD instances via GitOps with about 10 Applications. All instances exhibit this behavior.

If you stare at the Application Details long enough (maybe 10+ minutes), the text "in-cluster (undefined)" will eventually revert to the correct value showing the cluster name and server URL, without refreshing the page. After a short period of time the issue returns.

**Expected behavior**

In the Application Details view, I expect to see the correct cluster destination, with a name and server URL matching the cluster that the Application is configured to target in its `destination` field.

**Screenshots**

![Screenshot from 2022-03-30 12-10-45](https://user-images.githubusercontent.com/3124965/160892935-c743b1ec-b740-4c42-a6d4-210da1a3e1e7.png)

**Version**

```shell
$ argocd version
argocd-server: v2.3.2+ecc2af9

```

**Logs**

Example Application Spec that produces this issue.
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-package-general2
  annotations:
    # notifications.argoproj.io/subscribe.on-deployed.slack: cp-argo-notifications
    notifications.argoproj.io/subscribe.on-health-degraded.slack: cp-argo-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: cp-argo-notifications
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: cp-argo-notifications
spec:
  project: argo-cd

  destination:
    name: awscmhinfra2
    namespace: argo-cd-general

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

  source:
    repoURL: XXX (internal gitlab repo)
    targetRevision: master
    path: charts/argo-cd
    helm:
      releaseName: argo-cd-general
      valueFiles:
        - values-clusters.yaml
        - values-instance-general2.yaml
```

**Comment by EdwinPhilip** [comment]
To add more to it, we see the same behaviour when we choose cluster by name. If we choose by url, we see the cluster url, not in-cluster

**Comment by n888** [comment]
FYI observing same issue here, with 2 argocd-server replicas.
Seeing a 403 in browser-inspector while loading App Details -> 
`https://argocd.com/api/v1/clusters/?name=${CLUSTER_NAME}`

argocd-server logs:

Request
`[...] grpc.request.content="name:\"${CLUSTER_NAME}\" id:<> " grpc.service=cluster.ClusterService grpc.start_time="2022-03-30T18:16:22Z" span.kind=server system=grpc`

Permission Denied
`time="2022-03-30T18:16:22Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied" grpc.code=PermissionDenied grpc.method=Get grpc.service=cluster.ClusterService grpc.start_time="2022-03-30T18:16:22Z" grpc.time_ms=0.414 span.kind=server system=grpc`

**Comment by detox3r** [comment]
Same issue here. private cloud

**Comment by redox72** [comment]
Same here on version 2.3.3

**Comment by eundoosong** [comment]
Same here on 2.3.3

**Comment by sidewinder12s** [comment]
Also appears declarative setup fails when you try and use `in-cluster` with the following error:

```
InvalidSpecError: cluster 'in-cluster' has not been configured"
```

**Comment by m1mohamad** [comment]
so I updated my cert-manager , kes and ingress controller manifests with the cluster URL , and that worked fine before , it fails with errors like this when trying to re-sync the apps : 

Sync operation to failed: ComparisonError: rpc error: code = NotFound desc = cluster "https://xxxxx.gr7.eu-central-1.eks.amazonaws.com" not found;ComparisonError: rpc error: code = NotFound desc = cluster "https://xxxxx.gr7.eu-central-1.eks.amazonaws.com" not found;InvalidSpecError: cluster 'https://xxxxxx.gr7.eu-central-1.eks.amazonaws.com' has not been configured

**Comment by bardiharborow** [comment]
@sidewinder12s that error seems to happen when you pass `server: in-cluster` instead of `name: in-cluster`.

**Comment by sidewinder12s** [comment]
Yup, just realized that. I opened a separate issue around how restrictive project RBAC is, you must define server or name on your projects and apps. You cannot mix and match them.

**Comment by alexandervantrijffel** [comment]
I got rid of the error by defining both a cluster name and an empty value for server:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: enigma
  destination:
    namespace: enigma
    name: in-cluster
    server: ""
```
