### ISSUE TITLE
Traefik producing `error validating data: ValidationError(IngressRoute.spec.tls.options): missing required field "name" in us.containo.traefik.v1alpha1.IngressRoute.spec.tls.options`

### ISSUE THREAD

**Issue by jonashackt** [argoproj/argo-cd#8950]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Traefik producing error `error validating data: ValidationError(IngressRoute.spec.tls.options): missing required field "name" in us.containo.traefik.v1alpha1.IngressRoute.spec.tls.options` applying ArgoCD docs `IngressRoute` CRD from https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ingressroute-crd

**To Reproduce**

Simply apply ArgoCD docs `IngressRoute` CRD from https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ingressroute-crd

For later reference, here's the full CRD from the docs:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.example.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.example.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    certResolver: default
    options: {}
```

**Expected behavior**

`kubectl` should produce expected `ingressroute.traefik.containo.us/argocd-server configured`.

**Version**

```shell
$ argocd version
argocd: v2.3.0+fe42780.dirty
  BuildDate: 2022-03-07T05:19:43Z
  GitCommit: fe427802293b090f43f91f5839393174df6c3b3a
  GitTreeState: dirty
  GoVersion: go1.17.8
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.3.1+b65c169
```

**Logs**

```
$ kubectl apply -f ingress/argocd-dashboard.yml
error: error validating "ingress/argocd-dashboard.yml": error validating data: ValidationError(IngressRoute.spec.tls.options): missing required field "name" in us.containo.traefik.v1alpha1.IngressRoute.spec.tls.options; if you choose to ignore these errors, turn validation off with --validate=false
```
