### ISSUE TITLE
ArgoCD uses old  Helm Chart from dependencies.

### ISSUE THREAD

**Issue by rozdestvenskiy** [argoproj/argo-cd#9001]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have repository with values and Helm chart with one dependency. But when I'm trying to change chart from this dependency, ArgoCD still deploying applications with old charts. 
I'm updating chart from dependency without creating new version for it.

**To Reproduce**

Here is Chart.yaml from my repository:

```
apiVersion: v1
name: my-chart
version: 1.0
dependencies:
- name: base-chart
  version: "1.2"
  repository: "https://my-chart/url"
```

So, I'm changing something in base-chart and don't change version. But Argo still uses old base-chart.

**Expected behavior**

ArgoCD should use new chart, with changes.

**Version**

v2.3.0
