### ISSUE TITLE
Implement spec.source.helm.values as array to allow multiple 'values as blockfile'

### ISSUE THREAD

**Issue by xashr** [argoproj/argo-cd#9015]
# Summary

Currently only one 'values as value block file' can be provided via spec.source.helm.values (see https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml) . However, we need to provide multiple value files as block file - also with increasing precedence (i.e. file 2 can override values from file 1).

Current situation - only contents from one file can be specified:
```
spec:
  source:
    helm:
       values: |
         this: is
         one: file
```

# Motivation

We use this feature in combination with ApplicationSet and generators. The helm values are provided from different sources and have different priorities, e.g. there is a base configuration and a specialized configuration.

# Proposal

Implement spec.source.helm.values as array (probably still allowing single string type for backwards compatibility)

ApplicationSet example:
```
spec:
  generators:
    ...
  template:
    spec:
      source:
        helm:
          values:
            - '{{baseValues}}'
            - '{{specializedValues}}'
```

**Note:**
The workaround of merging helm values from different sources into one block file does not work if there are duplicate keys (e.g. image.repository in file 1 and image.tag in file 2 due to 'image' key occurring in both files.
```
       values: |
         '{{baseValues}}'
         '{{specializedValues}}'
```
So unfortunately we cannot use this.

Also, the workaround of using spec.source.helm.parameters is not really feasible due to the different syntax.
