### ISSUE TITLE
Getting Started demo app doesn't sync; "cannot list resource X in cluster scope"

### ISSUE THREAD

**Issue by kevin-hanselman** [argoproj/argo-cd#9025]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I recently installed “[core](https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#core)” ArgoCD and I created a project and application (from plain k8s manifests in a Git repo). Looking at the Application resource, I see its status is “Healthy”, but it’s experiencing consistent ComparisonErrors of different varieties. For example:

    User "system:serviceaccount:argocd:argocd-application-controller" cannot list resource "persistentvolumes" in API group "" at the cluster scope

These errors will occasionally change to different resources and API groups (e.g. "cannot list services", etc.), but it’s always happening, and it seems to be preventing the application from syncing.

I’ve checked the ArgoCD RBAC config and everything seems to be in order. The service account above is bound to a ClusterRole that allows everything, AFAICT.

**To Reproduce**

Install [ArgoCD core](https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#core).

    curl -Lo argo-cd.yaml https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/core-install.yaml
    kubectl create namespace argo-cd
    kubectl apply -n argo-cd -f argo-cd.yaml

Create a [demo app](https://argo-cd.readthedocs.io/en/stable/getting_started/#6-create-an-application-from-a-git-repository).

```
cat << EOF > guestbook.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argo-cd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
  syncPolicy:
    automated: {}

EOF

kubectl apply -f guestbook.yaml

kubectl describe application guestbook
```

`kubectl describe application` shows sync status "Unknown" and ComparisonError Conditions like:

```
Status:
  Conditions:
    Message:               failed to sync cluster ...: failed to load initial state of resource ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:argo-cd:argocd-application-controller" cannot list resource "serviceaccounts" in API group "" at the cluster scope
    Type:                  ComparisonError
```

I've also confirmed that `system:serviceaccount:argo-cd:argocd-application-controller` has the following role bindings:

```
$ kubectl describe -n argo-cd clusterrole argocd-application-controller
Name:         argocd-application-controller
Labels:       app.kubernetes.io/component=application-controller
              app.kubernetes.io/name=argocd-application-controller
              app.kubernetes.io/part-of=argocd
Annotations:  <none>
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
  *.*        []                 []              [*]
             [*]                []              [*]

$ kubectl describe -n argo-cd clusterrolebinding argocd-application-controller
Name:         argocd-application-controller
Labels:       app.kubernetes.io/component=application-controller
              app.kubernetes.io/name=argocd-application-controller
              app.kubernetes.io/part-of=argocd
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  argocd-application-controller
Subjects:
  Kind            Name                           Namespace
  ----            ----                           ---------
  ServiceAccount  argocd-application-controller  argocd
```

**Expected behavior**

The guestbook demo app should be deployed to the k8s cluster, and there are no ComparisonErrors.

**Version**

```
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:14:36Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:14:36Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/arm64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: v4.5.4 2022-03-28T23:06:20Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```
