### ISSUE TITLE
I can't enable SSO with Gitlab and dex

### ISSUE THREAD

**Issue by midestefanis** [argoproj/argo-cd#9034]
**Describe the bug**

I can't enable SSO with Gitlab and dex

Following the following documentation:

https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#dex
https://dexidp.io/docs/connectors/gitlab/

I'm trying to activate SSO with Gitlab but both the server and the dex always give me the following error:

time="2022-04-07T16:33:04Z" level=warning msg="invalid dex yaml config"

**To Reproduce**

What I did was just edit the configmap 'argocd-cm'

```
data:
  url: https://****.com.ar/
  dex.config: |
    connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
          baseURL: https://gitlab.com
          clientID: ****
          clientSecret: ****
          redirectURI: https://****/dex/callback
          orgs:
          - name: ***
  repository.credentials: |
    - passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://gitlab.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
  timeout.reconciliation: 15s
```

**Expected behavior**

Login with SOO

**Screenshots**

**Version**

```shell
argocd:v2.3.3
```

**Logs**

```
time="2022-04-07T18:18:11Z" level=info msg="Starting configmap/secret informers"
time="2022-04-07T18:18:11Z" level=info msg="Configmap/secret informer synced"
time="2022-04-07T18:18:11Z" level=info msg="0xc000b10cc0 subscribed to settings updates"
time="2022-04-07T18:18:11Z" level=warning msg="invalid dex yaml config"
time="2022-04-07T18:18:11Z" level=info msg="dex is not configured"
```

**Comment by sigi4** [comment]
I'm not sure if this is your issue, but this page https://dexidp.io/docs/connectors/gitlab/ indicates that name is not the parent of baseUrl...

I believe a config: is missing after name: but on the same level.

**Comment by midestefanis** [comment]
Probably among so many tests, it must have gone wrong, anyway I corrected it and it continues to throw the same error. @sigi4

**Comment by lucasff** [comment]
```
dex.config: |
  logger:
    level: debug
    format: json
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: <your ID>
      clientSecret: <your secret>
      orgs:
      - name: <your org>
```

I hope it helps, it might be very similar to GitLab, although I use GitHub. It works.

**Comment by jeunii** [comment]
I pointed redirectURI to my dex service

```
redirectURI: http://argocd-dex-server:5556/dex/callback
```

and now atleast the request goes to dex server. On gitlab I was asked to authorize my access to gitlab but then ArgoCD says "login failed"

Dex logs state

```
time="2022-08-18T16:32:28Z" level=error msg="Failed to authenticate: gitlab: get groups: gitlab: user \"FirstName.LastName\" is not in any of the required groups"
```

**Comment by jeunii** [comment]
I got this working.

So my final config looks like

```
  dex.config: |
    connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        baseURL: https://gitlab.com
        redirectURI: http://argocd-dex-server:5556/dex/callback # <---- Point to dex server
        config:
          clientID: <REDACTED> # <--- from gitlab app Application ID
          clientSecret:  <REDACTED> # <--- from gitlab app Secret
        groups:
        - "<GROUP_NAME>" # <--- name of group you are part of in gitlab
```

I was getting a 502 when redirected back so I added the following to the ingress

```
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
```

And to make sure that members of the gitlab group are admins on ArgoCD, added the following cm

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, <GROUP_NAME>, role:admin
```
