### ISSUE TITLE
Argo CD Notifications: the on-deployed trigger will trigger when Progressing instead of only Healthy

### ISSUE THREAD

**Issue by nickjj** [argoproj/argo-cd#9070]
I'm using Argo CD v2.3.3 (both client and server) which has the built in notifications functionality.

**Describe the bug**

When using the `on-deployed` trigger which has:

```yaml
- when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```

It will get triggered when progressing which is much different than healthy. Progressing can happen when something is unable to be deployed successfully (ie. not healthy).

**To Reproduce**

Deploy a sample manifest and change the `image:` tag to use `abc123` or any tag that you know won't exist.

**Expected behavior**

The `on-deployed` trigger wouldn't fire because while the app did sync successfully, this deploy is not healthy. Technically the "old" deploy is healthy. The deploy that triggered this event has a pod in an error state while the health is considered "Progressing" not "Healthy" since it can't start (which is expected) which feels like this trigger is giving out false information.

**Actual behavior**

The `on-deployed` trigger will fire and your notification will get sent out saying the app is synced and healthy.

A similar discussion was opened in the old notifications discussion at https://github.com/argoproj-labs/argocd-notifications/discussions/352 but it was never looked into. This feels more like a bug than a discussion in my opinion.

**Comment by muratakdeniz** [comment]
have you tried to use it like this?

```yml
  triggers:
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.operationState.syncResult.revision
        send:
        - app-sync-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status != 'OutOfSync'
```
