### ISSUE TITLE
Support GitHub App In ApplicationSet Pull Request generator

### ISSUE THREAD

**Issue by agaudreault-jive** [argoproj/argo-cd#9078]
# Summary

The Pull Request generator of the ApplicationSet only supports a Personal Access Token in the `tokenRef`. ArgoCD already have the logic to authenticate with a [GitHub App](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#github-app-credential). 

# Motivation

Using a GitHub App is more secure and allows for more rate limits

# Proposal

Reference to a secret containing the GitHub App information in the [format](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#github-app-repositories) already defined by ArgoCD

```yaml
  - pullRequest:
      github:
        owner: org
        repo: repo
        # Reference to a Secret containing github app information. (optional)
        appRef:
          secretName: github-app
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
          - preview
```
