### ISSUE TITLE
Custom health assessments for CRDs

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#911]
I was trying to set up cert-mananger and realized that Argo CD would benefit from being able to have some way of assessing health for custom CRD types.

In my case, my cert URL was invalid:
```
status:
  acme:
    uri: https://acme-staging-v02.api.letsencrypt.org/acme/acct/7529828
  conditions:
  - lastTransitionTime: "2018-12-08T09:24:29Z"
    message: Your ACME server URL is set to a v1 endpoint (https://acme-staging.api.letsencrypt.org/directory).
      You should update the spec.acme.server field to "https://acme-staging-v02.api.letsencrypt.org/directory"
    reason: InvalidConfig
    status: "False"
    type: Ready
```

I think we need a flexible way to allow users to provide some assess health heuristics of CRDs based on group/Kind. Maybe some jq expression

1. [x] implement custom health support
1. [x] health check for  argoproj.io/Rollout
1. [x] health check for certmanager.k8s.io/Issuer, certmanager.k8s.io/Certificate
1. [x] document custom health checks
