### ISSUE TITLE
argocd CLI uses wrong namespace

### ISSUE THREAD

**Issue by bfblog** [argoproj/argo-cd#9123]
The argocd CLI uses the kubernetes default namespace. For example, "argocd app list" will return an empty list, if current namespace is not set to argocd. The CLI offers "-n" or "--namespace" parameter, but when specifying it, it is detected as invalid option.

- v2.3.3

**Comment by nikhleshgoenka** [comment]
Did you try adding applications from UI and that works and gets deployed in expected namespace?

**Comment by bfblog** [comment]
Yes, I deployed several applications using the UI and some YAML resources. As result, any of them works as expected. As a next step I started using the argocd CLI. "argocd app list" returns an empty list. When switching the default namespace to "argocd" the tools finds the apps. So is switched the default back to a different namespace and tried to apply the namespace to argocd CLI. Bute here the it comes to invalid parameter (see above)

I

**Comment by danielhelfand** [comment]
The argocd app list command doesn't support the `--namespace` option: https://github.com/argoproj/argo-cd/blob/c7ff388b8476a85d10e888f457e35e050658a1c8/cmd/argocd/commands/app.go#L1159

None of the app commands do, which possibly means it was an intentional design choice. The only commands the support namespace option for apps are related to an Application's underlying resources (i.e. patch-resource, delete-resource).

This is probably something that requires further discussion to know if this is something to move forward with, but I would reclassify this as an enhancement, not a bug.

**Comment by bfblog** [comment]
I am very surprised that no one else has noticed this behavior. I have been dealing with ArgoCD for quite some time and now use it to bootstrap clusters. This works really well.
The ArgoCD CLI is - as far as my understanding goes - a wrapper around kubectl and can handle the argo CRD especially well. And with kubectl, you actually always have to specify the namespace. From experience, the active namespace is never the right one. Alternatively, the CLI could look at all namespaces, mutatis mutandis an --all-namespaces.

What I am actually looking for is an option to remove an application. More precisely, the Kubernetes objects should be removed, but the ArgoCD application should remain inactive. Background: I have defined many Argo applications (also app-of-apps), and would like to realize a function "enable/disable optional features" with Argo. I was hoping to be able to customize this feature through scripts.
My wish:
- a super configuration for all applications of a project
- via a setting, I can activate or deactivate an app
- deactivate removes all resources, but the app remains without auto-sync 
- enable corresponds to the behavior directly after the deploy, Kubernetes objects are created

**Comment by brunzefb** [comment]
I am not sure if this is a related issue or not, but I will mention it. I have an argocd app
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nca-dev-oom-api-pca-pcvg
  namespace: argocd   <-- must be argocd, otherwise the app does not load in the UI
```
If I specify the namespace as argocd (the ns where argocd is installed), the UI immediately updates, and the app starts to sync.
If I specify another namespace, this does not work.

If I have the 2 similar applications, where the deployment targets two separate namespaces, I am currently forced to name my application differently, eg: pcvg-dev and pcvg-qa for the argo Application name.  The argo ui allows viewing by namespace or by project, but that does not help; because there is one argocd namespace -- if I deploy 2 argo apps with the same name, the last one wins.

My workaround for now is just to name the apps differently, but its annoying.
I can file a different issue, if you think this is not related.

**Comment by bfblog** [comment]
I think it is not a related issue but a misunderstanding of Kubernetes resources:

- The section "metadata" is related to Kubernetes, it is not part of argocd.
- The combination of metadata.name and metadata.namespace is a unique identifier in the scope of Kubernetes. Creating several yaml with the same identifiers causes an overwriting of the existing yaml-resource. The last applied yaml wins.
- ArgoCD is running in namespace ArgoCD. Setting up an Argo-Application means, to add a further yaml resource of Kind Application to argocd namespace.
- ArgoCD only watches objects in its own namespace. In this way, any Application installed to a different namespace is not mentioned by ArgoCD

My recommendation is:

- install all applications to argocd namespace and use unique names.
- add labels to metadata and use the filter capabilities
```

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-qa
  namespace: argocd   <-- must be argocd, otherwise the app does not load in the UI with kubectl apply
  labels:
    app: my-app
    env: qa
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd   <-- must be argocd, otherwise the app does not load in the UI with kubectl apply
  labels:
    app: my-app
    env: dev
```
Now, set label filter "env=qa" to see resources from the qa-environment.

Please let me know, if this commend was helpful.
