### ISSUE TITLE
lowercase RFC 1123 subdomain required for applicationset.spec.template.metadata.name

### ISSUE THREAD

**Issue by soudaburger** [argoproj/argo-cd#9137]
Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**
https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/
According to the documentation, I should be able to use `{{cluster}}-something` as the `template.metadata.name`, but the application controller throws errors.

Deploying argocd via helm chart 4.5.3 with the following template added:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storageclass
spec:
  generators:
  - list:
      elements:
        - name: my-cluster
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-storageclass'
    spec:
      project: default
      source:
        targetRevision: HEAD
        repoURL: https://github.com/blah
        path: "charts/storageclass"
        helm:
          valueFiles: ['values/{{cluster}}.yaml']
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

Install helm chart using the YAML above.  Tail logs on applicationset-controller.
I would like to have a "dynamic" metadata.name so that it can have the reference to cluster in the name.

I would expect the controller to properly accept the interpolated values instead of the raw values.

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

**Logs**

```bash
time="2022-04-19T03:25:08Z" level=error msg="failed to unchanged Application" action=unchanged app="{{cluster}}-storageclass" appSet=storageclass error="Application.argoproj.io \"{{cluster}}-storageclass\" is invalid: metadata.name: Invalid value: \"{{cluster}}-storageclass\": a lowercase RFC 1123 subdomain must consist of lower case alphan │
│ 1.6503387089327996e+09    ERROR    controller.applicationset    Reconciler error    {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "storageclass", "namespace": "argocd", "error": "Application.argoproj.io \"{{cluster}}-storageclass\" is invalid: metadata.name: Invalid value: \"{{cluster}}-storageclass\": asigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
```

Maybe I'm missing something?  Feel free to point me to "proper" documentation if I shouldn't be using that example?  Thanks!

**Comment by crenshaw-dev** [comment]
The list generator, as written, isn't producing a variable called "cluster".

```yaml
  generators:
  - list:
      elements:
        - name: my-cluster
          url: https://kubernetes.default.svc
```

Try replacing `{{cluster}}` with `{{name}}` in your template.
