### ISSUE TITLE
[0.11.0] `argocd app diff` shows invalid differences

### ISSUE THREAD

**Issue by zx8** [argoproj/argo-cd#916]
```
$ argocd version
argocd: v0.11.0-dev-457e137+457e137.dirty
  BuildDate: 2018-12-10T10:54:41Z
  GitCommit: 457e137ddadde8b653d19c29422e082138fd17c6
  GitTreeState: dirty
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v0.11.0-dev-457e137+457e137.dirty
  BuildDate: 2018-12-10T10:54:18Z
  GitCommit: 457e137ddadde8b653d19c29422e082138fd17c6
  GitTreeState: dirty
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.0
```

Argo is claiming that my application is constantly "OutOfSync". I ran the following to figure out what Argo thinks is different between Git & Live:

```
$ argocd app diff foo-staging
```

And I see the same diff repeated for the `env` block in a lot of the Deployments specs, which seems bogus (sensitive info redacted). The diff lines are duplicated, which I also don't understand:

![image](https://user-images.githubusercontent.com/8544900/49740370-e8baa580-fc8b-11e8-9c97-689e75bec8db.png)

If I pick one of the deployments and manually `kubectl get deployment <name> -o yaml`, I can see the env vars are included both in the Live & Git manifests, so I don't understand why Argo thinks this difference exists.

**Comment by zx8** [comment]
I think I've figured out what caused this, but I'm not sure what Argo can do to fix it.

As stated in the OP, the diff that Argo was suggesting was invalid & the changes suggested had already been applied several syncs prior. The _actual_ diff that Argo was picking up was a completely different change that was manually made to the deployment spec.

I've been [this workaround](https://github.com/kubernetes/kubernetes/issues/27081#issuecomment-238078103) to force a "rolling update" of Pods, which causes the deployment to be updated with a "fake" environment variable. Obviously, Git/Argo know nothing about this, but it seems to be causing Argo issues calculating the diff.

After I edited all the deployments to delete the dummy environment variable, all the deployments synced correctly.

**Comment by jessesuen** [comment]
> The actual diff that Argo was picking up was a completely different change that was manually made to the deployment spec

@zx8 - so in this case, it seems that Argo CD is working by design and detecting a real configuration drift.

I think we need to document about what Argo CD can and cannot detect as a diff. Basically, Argo CD works the same way as `kubectl apply`, in that we calculate a json patch based on a 3-way merge of:
1. last-applied-configuration
2. new manifest
3. live manifest

If the patch is empty (i.e. `{}`) then the diff should be nothing. Otherwise, we will apply the calculated patch to the live object and present the difference in the UI/CLI.

The important thing to note is that Argo CD (as well as kubectl apply), cannot detect fields which have been either "defaulted" by some controller or manually added behind the scenes. It can only detect:
1. newly added fields (not present in the last-applied-configuration)
2. removed fields (removed from the last-applied-configuration)
3. changed fields (different from the last-applied-configuration)

**Comment by zx8** [comment]
> it seems that Argo CD is working by design and detecting a real configuration drift. Is that correct?

Yep, Argo CD is correctly _detecting_ a configuration drift, but the diff that's being displaying is invalid for two reasons:

1. The change detected is incorrect, i.e. the last-applied-configuration, new manifest & live manifest (I believe) contained the values displayed in the diff, so I'm not sure how it arrived at this conclusion.
2. Even though the diff is incorrect, it seems to be duplicating the diff lines for some reason?

**Comment by jessesuen** [comment]
I have seen nonsensical diffs happen due to bugs where the wrong side was used as the base (we used config as the base where we should have used live). But I thought we ironed out all those issues, specifically in https://github.com/argoproj/argo-cd/commit/c66b4442134e7ed8f623046b156277679c3431b1.

@zx8 does the incorrect diff show up in UI as well?

**Comment by zx8** [comment]
The web UI showed the same diff, but was only affected by the first point in my previous comment. It didn't the duplicate lines when using the CLI:

![image](https://user-images.githubusercontent.com/8544900/49798690-d0559400-fd3a-11e8-9ffc-d6b53b02a04f.png)

**Comment by alexmt** [comment]
@zx8 can you please share config and live manifest ( unless it has sensitive information ) ? 

Or describe which changes were applied manually to the deployment spec, so I could reproduce the issue.

**Comment by zx8** [comment]
@alexmt I'm unable to share the _exact_ manifests as they contain sensitive information, but here's a slightly modified version of the problematic deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: example
  name: foobar
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: foobar
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: d464781738ca7e2e6d0a59a71a911cf500075f3b24170726d8e80be0aa997df8
      labels:
        app: foobar
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: FOO
              value: BAR
            - name: BAZ
              value: BOO
            - name: PORT
              value: "8000"
            - name: IP_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: IP_ADDRESS_2
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: nginx
          imagePullPolicy: Always
          name: foobar
          ports:
            - containerPort: 8000
              name: app
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 200M
            requests:
              cpu: 50m
              memory: 100M
```

And, to force a rolling restart, the manual modification I made to the spec (outside of VCS / Argo CD) was:

```
$ kubectl patch deployment foobar -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"DUMMY\":\"$(date +'%s')\"}}}}}"
```
