### ISSUE TITLE
generateName for postSyncHook not unique and too long

### ISSUE THREAD

**Issue by jimmyjones2** [argoproj/argo-cd#9184]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If a helm chart has two Jobs as PostSyncHook it will generate the same name for both, so the 2nd will fail. Also the postfix that is generated is 27 characters long, compared to 5 when using `kubectl create`, which is almost half of the 63 character limit, so leaves little for the pod name.

eg. `inter-4nrrl` vs `linter-6ccfe74-postsync-1650650648`

**To Reproduce**

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: linter-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command: [ "/usr/bin/curl", "google.com" ]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: linter-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command: [ "/usr/bin/curl", "facebook.com" ]
      restartPolicy: Never
  backoffLimit: 0
```

**Expected behavior**

Two post sync hook jobs created, rather than one and an error. I'd also expect the pod names to be significantly shorter.

**Screenshots**

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:46:59Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.0+6da92a8
  BuildDate: 2021-12-14T18:09:18Z
  GitCommit: 6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```
