### ISSUE TITLE
Argo CD greedily uses all Github Action executors

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#9222]
Argo CD uses up all the Github executors, preventing other `argoproj` executors. This is worse, because Argo CD builds take a long time (20m for CodeQL for example, over 1h for other builds).

We make workflows builds faster by using Github Action concurrency which auto cancels duplicate builds:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
````
