### ISSUE TITLE
ApplicationSet deleting all Applications and K8s resources on Update

### ISSUE THREAD

**Issue by christophercutajar** [argoproj/argo-cd#9227]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Deploying a patch to an applicationset using `kubectl apply -f dev-demo.yaml -n argocd` ended up ArgoCD deleting the existing applications managed by the respective applicationset, together with all their respective k8s resources. This behaviour ended up in deleting most of our productions clusters and required us to perform a whole restore exercise.

From the applicationset-controller logs, I could see that it tried to re-create the application from scratch and was not able to do so. From the logs, it looks like it lost all sync with Git and could not read the cluster configs as from logs it was not able to get the necessary information `generator="{<nil> <nil> 0xc0006649c0 <nil> <nil> <nil> <nil> <nil>}"` . 

**To Reproduce**

- Deploy a ApplicationSet such as the one below (One can use helm)
- Perform a small change in the ApplicationSet
- Deploy the change using `kubectl apply -f dev-demo.yaml -n argocd`

**Expected behavior**

It was not expected that a small change would end up in deleting all ArgoCD applications and all K8s respective resources. At this stage, the only way to recover from such behavior is to delete the applicationset and create it from scratch  with `preserveResourcesOnDeletion: true`  in the sync policy.

**ApplicationSet Used**

<details>
<summary>ApplicationSet</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-demo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: <private repo>
      revision: master
      files:
      - path: 'kubernetes/dev/argocd-cluster-configs/**/config.json'
  template:
    metadata:
      name: '{{`{{cluster.name}}`}}'
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.slack: random
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: random
        notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: random
        notifications.argoproj.io/subscribe.on-sync-failed.slack: random
        notifications.argoproj.io/subscribe.on-health-degraded.slack: random
        notifications.argoproj.io/subscribe.on-deleted.slack: random
    spec:
      project: default
      source:
        repoURL: <private repo>
        targetRevision: master
        path: 'kubernetes/dev/{{`{{cluster.deployment_path}}`}}'
      destination:
        server: '{{`{{cluster.server}}`}}'
        namespace: default
```

</details>

**Version**

```json
{
    "Version": "v2.3.3+07ac038",
    "BuildDate": "2022-03-30T00:06:18Z",
    "GitCommit": "07ac038a8f97a93b401e824550f0505400a8c84e",
    "GitTreeState": "clean",
    "GoVersion": "go1.17.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.0+gd141386",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

Deleted Application:

```
ationset-controller 2022-04-27T01:54:00.435847934+02:00 time="2022-04-26T23:54:00Z" level=info msg="end reconcile" requeueAfter=3m0s
argo-cd-argocd-applicationset-controller-6d9cf4b84f-sccnt applicationset-controller 2022-04-27T01:54:00.436614334+02:00 1.651017240436438e+09   DEBUG   events  Normal  {"object": {"kind":"ApplicationSet","namespace":"argocd","name":"dev-demo","uid":"abe48c1f-3721-4f54-8768-5603430ebb0a","apiVersion":"argoproj.io/v1alpha1","resourceVersion":"87484898"}, "reason": "Deleted", "message": "Deleted Application \"chris-eck-test\""}
```

ApplicationSet Controller trying to create another application:

```
argo-cd-argocd-applicationset-controller-6d9cf4b84f-sccnt applicationset-controller 2022-04-27T01:56:40.217931988+02:00 time="2022-04-26T23:56:40Z" level=info msg="generated 1 applications" generator="{<nil> <nil> 0xc0006649c0 <nil> <nil> <nil> <nil> <nil>}"
argo-cd-argocd-applicationset-controller-6d9cf4b84f-sccnt applicationset-controller 2022-04-27T01:56:40.227779627+02:00 time="2022-04-26T23:56:40Z" level=error msg="validation error found during application validation: application spec is invalid: InvalidSpecError: cluster '{{`{{cluster.server}}`}}' has not been configured"
```

**Comment by crenshaw-dev** [comment]
Can you give a (redacted if necessary) before and after version of the AppSet manifest?

**Comment by christophercutajar** [comment]
> Can you give a (redacted if necessary) before and after version of the AppSet manifest?

Updated description to include `Working ApplicationSet Used` that is the one initially deployed. Then the `Updated ApplicationSet` is the one that was deployed via `kubectl`.

**Comment by jarrettprosser** [comment]
I've found this behaviour as well. I'm deploying Argo CD and the ApplicationsSet manually with Helm. When I update the ApplicationSet and push the change, all of my existing applications are deleted and recreated. I've observed this when I add an annotation, or modify the paths in the git generator configuration.

**Comment by ericblackburn** [comment]
I'm unable to re-create this when leveraging an Application Set, git generator type, that is being updated by Argo (I have an Argo App loading the App Set itself).  Argo Version: v2.5.1+504da42

Steps

1. Deploy an App Set (preserveResourcesOnDeletion: false) with the the annotation
```
  template:
    metadata:
      name:test
      annotations:
        test: test
        notifications.argoproj.io/subscribe.on-deployed.slack: random
``` 
2. Verify annotation synced
3. Deploy an App Set with the annotation removed
```
  template:
    metadata:
      name:test
      annotations:
        test: test
``` 
4. Hard Refresh (to get it to sync immediately) the Argo App that deploys the AppSet
5. Very update synced.  Observed that the Argo Apps, managed by the AppSet, and the resources they manage were not purged and re-created
6. Verified that Preserve is Off, by removing an instance from the App Set and syncing it.  Observed the Argo App and the resources managed by it are cleaned up.
