### ISSUE TITLE
Application sync is 'Unknown'

### ISSUE THREAD

**Issue by iben12** [argoproj/argo-cd#9278]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Sporadically my ArgoCD sends a bunch of notifications (from 1-2 to 10+ sometimes) that apps sync is 'Unknown'. This happens basically every day in different times, sometimes multiple times a day. Checking the UI every app seems to be fine. I could not recognize any pattern on what time to which apps does this happen.

The only thing I was able to find is that right before the notifications are delivered the `repo-server` spits out logs like the below:
```
"&{0xc0003ec820 0xc0007d0200 {} 0x517a60 true false false true 0 {0 0} 0xc0000afb80 {0xc0004c8460 map[] false false} map[] false 0 -1 503 false false [] 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0] [0 0 0] 0xc000fa6150 1} rpc error: code = Canceled desc = context canceled"
```
It seems the more of these lines appear in logs, the more apps get the Unknown sync notification.

**To Reproduce**
I have one cluster running Kubernetes v1.22.7 and a single ArgoCD instance running in the same cluster. It uses one GitHub repository to deploy 32 apps, most of them are using Kustomize and a few Helm. I have notifications enabled, the default triggers are:
- on-sync-status-unknown
- on-sync-succeeded
- on-sync-failed

**Expected behavior**
ArgoCD does not send many messages that apps are in unknown state sporadically.

**Screenshots**

![img](https://i.postimg.cc/3rvy4DxQ/SCR-20220427-nn8.png)

**Version**

```shell
v2.3.2+ecc2af9
```

**Logs**

```
"&{0xc001050b40 0xc0011da900 {} 0x517a60 true false false true 0 {0 0} 0xc000146ec0 {0xc0001649a0 map[] false false} map[] false 0 -1 503 false false [] 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0] [0 0 0] 0xc000fe6930 1} rpc error: code = Canceled desc = context canceled"



"&{0xc001050b40 0xc0011da900 {} 0x517a60 true false false true 0 {0 0} 0xc000146ec0 {0xc0001649a0 map[] false false} map[] false 0 -1 503 false false [] 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0] [0 0 0] 0xc000fe6930 1} rpc error: code = Canceled desc = context canceled"

```

**Comment by karlderkaefer** [comment]
One recommendation is to check [performance guide](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/). I have faced same issue some month ago. Also check resources limits of argocd containers, especially redis and if they get restarted. Argocd can not handle big mono-repos very well. I also tried argocd notification for alerting but I just gave up because it's very unreliable. Instead if you intend to alert on app status, I would recommend to use alertmanager, it's much better in terms of handle apps that flapping into unknown state for short period (30s). With alertmanager the apps needs to be in unknown state for at least 15m in this example.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
  name: argocd.rules
spec:
  groups:
    - name: argocdappsfailing.rules
      rules:
        - alert: ArgoCdAppFailing
          annotations:
            description: Argocd app {{`{{ $labels.name }}`}} is in {{`{{ $labels.health_status }}`}} state.
            summary: Argocd app is {{`{{ $labels.health_status }}`}} state.
          expr: sum by (health_status, name) (argocd_app_info{health_status="Degraded"}) > 0
          for: 5m
          labels:
            severity: warning

        - alert: ArgoCdAppFailedToSync
          annotations:
            description: Argocd app {{`{{ $labels.name }}`}} is in {{`{{ $labels.sync_status }}`}} state for longer than 15 minutes.
            summary: Argocd app is {{`{{ $labels.sync_status}}`}} state.
          expr: sum by (sync_status, name) (argocd_app_info{sync_status="Unknown"}) > 0
          for: 15m
          labels:
            severity: warning
            environment: {{ .Values.environment }}
```
