### ISSUE TITLE
AWS CodeCommit Repositories with ROLE ARN

### ISSUE THREAD

**Issue by andradedpg** [argoproj/argo-cd#9284]
# Summary
Today is possible to create repositories as a Secret k8s object. It's ok and great! 
But the username and password (or SSH Key), in other words, some authenticate way is always are expected. 

![Captura de Tela 2022-05-03 às 10 54 20](https://user-images.githubusercontent.com/17835049/166467010-daead000-2811-48ee-869f-a32e966f04a3.png)

In AWS CodeCommit repositories, for example, you can create a repository without any user and allow access by IAM Policies and IAM Roles.
 
# Motivation
For security reasons, some environments can not be able to share CodeCommit repositories with IAM Users and only allow access by IAM Roles and Policies. In this scenario, it's impossible to use SSH Keys or User/Pass to configure repositories in ArgoCD. 

# Proposal
If not exists any way to create a CodeCommit repository without IAM Users, the proposal is the following: 

```
  apiVersion: v1
  kind: Secret
  metadata:
    name: private-repo
    namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  stringData:
     type: git
     url: https://git-codecommit.us-east-1.amazonws.com/v1/repos/my-private-repo
     role-arn: arn:aws:iam::99999999:role/role-with-codecommit-permissions
  ```
  
  Cheers!
