### ISSUE TITLE
ApplicationSet not honoring sourceRepos and destinations from globalProjects

### ISSUE THREAD

**Issue by agaudreault-jive** [argoproj/argo-cd#9298]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using an ApplicationSet to generate applications, the `sourceRepos` and `destinations` that are configured on a global project are not working. For the application to be generated properly, the project specified in the `.spec.template.spec.project` of the ApplicationSet must have the sourceRepos configured directly. Even if the sourceRepos shows up in the ArgoCD as being inherited. 

**To Reproduce**

1. Create a project `project1`
2. Create a global project `project2` with `sourceRepos`
3. Add label to project1 to inherit from project2 and configure argoCD config map for globalProjects and destinations
4. Create an ApplicationSet using `project1` and using sources from a repo defined in `project2`. It must create at least one Application to generate the error.

**Expected behavior**

It should work if the sourceRepos are inherited 

**Screenshots**

The ApplicationSet has the following status:

```yaml
status:
  conditions:
    - lastTransitionTime: '2022-05-04T03:11:45Z'
      message: >-
        application spec is invalid: InvalidSpecError: application repo
        https://github.com/org/apps is not permitted in project 'project1'
      reason: ApplicationValidationError
      status: 'True'
      type: ErrorOccurred
    - lastTransitionTime: '2022-04-29T19:40:18Z'
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: 'True'
      type: ParametersGenerated
    - lastTransitionTime: '2022-05-04T03:11:45Z'
      message: >-
        application spec is invalid: InvalidSpecError: application repo
        https://github.com/org/apps is not permitted in project 'project1'
      reason: ApplicationValidationError
      status: 'False'
      type: ResourcesUpToDate
```

And for destinations
```
status:
  conditions:
    - lastTransitionTime: '2022-05-04T17:20:47Z'
      message: >-
        application spec is invalid: InvalidSpecError: application destination
        {https://domain.eks.amazonaws.com
        example-ns} is not permitted in project 'project1' (and 2 more)
      reason: ApplicationValidationError
      status: 'True'
      type: ErrorOccurred
    - lastTransitionTime: '2022-04-29T15:03:34Z'
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: 'True'
      type: ParametersGenerated
    - lastTransitionTime: '2022-05-04T17:20:47Z'
      message: >-
        application spec is invalid: InvalidSpecError: application destination
        {https://domain.eks.amazonaws.com
        example-ns} is not permitted in project 'project1' (and 2 more)
      reason: ApplicationValidationError
      status: 'False'
      type: ResourcesUpToDate

```

**Version**

ArgoCD version 2.3.3
ApplicationSet version 0.4.1
