### ISSUE TITLE
ArgoCD does sync apply updated custom resource object

### ISSUE THREAD

**Issue by tamalsaha** [argoproj/argo-cd#9303]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have a helm chart that included some CRDs and objects for those CRDs. First I deploy an old version of this chart. Then I have updated the version of this chart. In the updated version, one of the CRD definitions was updated. Now, ArgoCD will not sync/apply the modified CRO (CRD is updated). You can see a recording below.

**To Reproduce**

1. I created a kind cluster and deployed argocd.

```bash
kind create cluster

kubectl create namespace argocd
kubectl apply -n argocd -f https://github.com/argoproj/argo-cd/raw/stable/manifests/install.yaml
watch kubectl get pods -n argocd
```

2. Now, I deploy old version of a helm chart using the following application. It sync properly.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-catalog
  namespace: argocd
spec:
  project: default
  source:
    chart: kubedb-catalog
    repoURL: https://charts.appscode.com/stable
    targetRevision: v2021.11.24
    # targetRevision: v2022.03.28
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubedb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - ApplyOutOfSyncOnly=true
```

3. Now, I update the helm chart version to v2022.03.28

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-catalog
  namespace: argocd
spec:
  project: default
  source:
    chart: kubedb-catalog
    repoURL: https://charts.appscode.com/stable
    # targetRevision: v2021.11.24
    targetRevision: v2022.03.28
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubedb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # needed to avoid Sync Fail when CRD updates
      - Validate=false
      - ApplyOutOfSyncOnly=true
```

4. Now, the Sync Status stays in `OutOfSync` state. If you check the `App Diff`, you can see that the modified CRD is applied but the modified CRO is not applied. `selfHeal` can't fix this. If I manually delete this OutOfSync CRO, it goes back to sync state.

**Expected behavior**

I expected the sync to be successful without needing to delete the modified CRO.

**Screenshots**

https://youtu.be/GGz5Hj74KtU

**Version**

```shell
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:14:36Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.3.3+07ac038
```
