### ISSUE TITLE
Git Generator does NOT parameterize destination.name or destination.server

### ISSUE THREAD

**Issue by zbialik** [argoproj/argo-cd#9318]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

## Description

Our git repo is setup with kustomize overlays for each cluster that will deploy a given k8s application. The repo has a file structure represented like so:

```
app-x/
    base/
        deploy.yaml
        kustomization.yaml
    cluster-a/
        kustomization.yaml
    cluster-b/
        kustomization.yaml
app-y/
    base/
        deploy.yaml
        kustomization.yaml
    cluster-c/
        kustomization.yaml
    cluster-d/
        kustomization.yaml
```

I want to use the Git Directory Generator to generate the Application manifests for each cluster-specific overlay setup in the above repo. 

**Since the cluster names are used as the folder names, we should be able to use the `{{path.basename}}` parameter to templatize the `spec.destination.name` field in the `Application` manifest. However, this does not appear to be the case.**

## Steps to Reproduce

1. Setup 2 ArgoCD managed clusters and name them the following:
    - `cluster-a`
    - `cluster-b`
2. [Use the following mock repo to mimic the desired kustomize overlays/file structure](https://github.com/zbialik/mock-kustomize-repo.git).
    - Note the repo has an `app-x` with 2 overlays for `cluster-a` and `cluster-b`.
4. Create the following `ApplicationSet` like the following:

```
# Git Generator
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    argocd.argoproj.io/instance: applicationsets
  name: app-x
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: app-x/*
          - exclude: true
            path: app-x/base
        repoURL: 'https://github.com/zbialik/mock-kustomize-repo.git'
        revision: main
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      name: '{{path.basename}}-app-x'
      namespace: argocd
    spec:
      destination:
        name: '{{path.basename}}' # does NOT work
        namespace: default
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/zbialik/mock-kustomize-repo.git'
        targetRevision: main
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
```

## Result

The `ApplicationSet` does NOT generate any `Application` resources because the `destination.name` does NOT get parameterized. 

## Expected Behavior

The `ApplicationSet` should generate 2 `Application` manifests: `cluster-a-app-x` and `cluster-b-app-x`.

## Important Notes

1. The parameterization works for `destination.namespace`

If you change the `ApplicationSet`'s `spec.template` to be:
```
spec:
  template:
    spec:
      destination:
        namespace: '{{path.basename}}'
        name: cluster-a
```

You will see the `namespace` parameterize to the defined cluster names and observe 2 `Application` manifests generate. 

**Why would this parameterization work for the `destination.namespace` but NOT the `destination.name`?** 

2. Using a Git File Generator also produces the same results

As a test, I tried implementing this with a Git File Generator by storing a separate `cluster.json` in each overlay and referencing a variable from that json as my `destination.name`. This also did not work (yet parameterizing the `destination.namespace` does).

## Other Info

**Screenshots**

```
N/A
```

**Version**

```shell
v2.3.3
```

**Logs**

applicationset-controller:
```
level=debug msg="apps from generator: [{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:cluster-a-mock-git-dir-generator GenerateName: Namespace:argocd SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[resources-finalizer.argocd.argoproj.io] ClusterName: ManagedFields:[]} Spec:{Source:{RepoURL:https://github.com/zbialik/mock-kustomize-repo.git Path:app-x/cluster-a TargetRevision:main Helm:nil Kustomize:nil Ksonnet:nil Directory:nil Plugin:nil Chart:} Destination:{Server: Namespace:mock-git-dir-generator Name:cluster-a isServerInferred:false} Project:core SyncPolicy:&SyncPolicy{Automated:&SyncPolicyAutomated{Prune:true,SelfHeal:true,AllowEmpty:true,},SyncOptions:[],Retry:nil,} IgnoreDifferences:[] Info:[] RevisionHistoryLimit:<nil>} Status:{Resources:[] Sync:{Status: ComparedTo:{Source:{RepoURL: Path: TargetRevision: Helm:nil Kustomize:nil Ksonnet:nil Directory:nil Plugin:nil Chart:} Destination:{Server: Namespace: Name: isServerInferred:false}} Revision:} Health:{Status: Message:} History:[] Conditions:[] ReconciledAt:<nil> OperationState:nil ObservedAt:<nil> SourceType: Summary:{ExternalURLs:[] Images:[]}} Operation:nil} {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:cluster-b-mock-git-dir-generator GenerateName: Namespace:argocd SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[resources-finalizer.argocd.argoproj.io] ClusterName: ManagedFields:[]} Spec:{Source:{RepoURL:https://github.com/zbialik/mock-kustomize-repo.git Path:app-x/cluster-b TargetRevision:main Helm:nil Kustomize:nil Ksonnet:nil Directory:nil Plugin:nil Chart:} Destination:{Server: Namespace:mock-git-dir-generator Name:cluster-b isServerInferred:false} Project:core SyncPolicy:&SyncPolicy{Automated:&SyncPolicyAutomated{Prune:true,SelfHeal:true,AllowEmpty:true,},SyncOptions:[],Retry:nil,} IgnoreDifferences:[] Info:[] RevisionHistoryLimit:<nil>} Status:{Resources:[] Sync:{Status: ComparedTo:{Source:{RepoURL: Path: TargetRevision: Helm:nil Kustomize:nil Ksonnet:nil Directory:nil Plugin:nil Chart:} Destination:{Server: Namespace: Name: isServerInferred:false}} Revision:} Health:{Status: Message:} History:[] Conditions:[] ReconciledAt:<nil> OperationState:nil ObservedAt:<nil> SourceType: Summary:{ExternalURLs:[] Images:[]}} Operation:nil}]" generator="{<nil> <nil> 0xc000900d00 <nil> <nil> <nil>}"
```
