### ISSUE TITLE
[Bug] [Bug] Can't get `jqPathExpressions` based `ignoreDifferences` to work with  various WebhookConfigurations

### ISSUE THREAD

**Issue by spkane** [argoproj/argo-cd#9323]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Setting this `ignoreDifferences` block applies fine, but doesn't do anything.

```yaml
  ignoreDifferences:
  - kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jqPathExpressions:
    - '.webhooks[]?.failurePolicy'
```

**To Reproduce**

Applying this ArgoCD application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetrate-istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-add-ons
    path: add-ons/tetrate-istio
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  ignoreDifferences:
  - group: apps
    kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: apps
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jqPathExpressions:
    - '.webhooks[]?.failurePolicy'
```

Should install istio and then you get two webhook configs which show diffs that aren't ignored.

![CleanShot 2022-05-06 at 12 51 01](https://user-images.githubusercontent.com/129629/167207657-bc6752b2-c404-4095-ac17-37c29792a59c.png)

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: istiod-default-validator
```

![CleanShot 2022-05-06 at 14 12 27](https://user-images.githubusercontent.com/129629/167217227-7da55edd-7bfa-44d1-a9da-9580d83467e7.png)

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
```

![CleanShot 2022-05-06 at 14 19 10](https://user-images.githubusercontent.com/129629/167217894-6353eddf-518f-4efc-a43f-8a688b9e298c.png)

**Expected behavior**

I can ignore these expected diffs from the application manifest level.

**Screenshots**

**Version**

```shell

v2.3.3+07ac038
```

cc/ https://github.com/aws-samples/eks-blueprints-add-ons/issues/37

**Comment by spkane** [comment]
I also have set this in the ArgoCD ConfigMap and it does not work either. `ignoreAggregatedRoles` works fine, but the `admissionregistration.k8s.io/MutatingWebhookConfiguration` section does not appear to do anything.

```yaml
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  resource.compareoptions: |
    ignoreAggregatedRoles: true
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
```

**Comment by zostay** [comment]
I had some difficulty with this as well. I suspect it came down to the namespace setting. I haven't dug into the code for argocd, but based on behavior, I'd guess that all/most fields in the spec have to be given. I was specifically struggling to find a way to ignore the `failurePolicy` field you mentioned. I found that this works:

```yaml
  ignoreDifferences:                                                                                                                   
  - group: admissionregistration.k8s.io                                                                                                
    jqPathExpressions:                                                                                                                 
    - .webhooks[].failurePolicy                                                                                                        
    kind: ValidatingWebhookConfiguration                                                                                               
    name: istio-validator-istio-system   
```

I explicitly set `namespace: ""` when I edited the Application record, but I don't know if that was helpful or just a red herring. I don't really have time to dig further into it now. I hope that's helpful to someone.

**Comment by HenryXie1** [comment]
I use below to fix
```
ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy
 ```

**Comment by tyler-harpool** [comment]
To keep  istio-sidecar-injector in sync here is what you would need.
```
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    jqPathExpressions:
    - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
```
