### ISSUE TITLE
CI: Concurrency groups might be a bit to aggressive

### ISSUE THREAD

**Issue by 34fathombelow** [argoproj/argo-cd#9325]
# Summary

I would like to discuss the possibility of refactoring the concurrency groups implemented in #9223.  As @alexec pointed out, Argo CD was exhausting many of the executors that other Argo projects need.

# Motivation

1. During multiple push events, actions are being cancelled mostly leading to integration test not being completed.

![Screenshot_20220506_235405](https://user-images.githubusercontent.com/76892343/167242723-2ba7bf43-3610-403a-9b5c-0374e3d60e2c.png)

2. Codecov reports not being sent for commits
3. `Integration Tests` badge is red and failing till a commit is successful.
4.  Possible unwanted notifications
# Proposal

A hybrid approach is to cancel duplicate builds for pull request while allowing push events to complete.  `github.head_ref` is only available for workflow events that are triggered by pull request or pull_request_target. `github.run_id` is used as a fallback for other events.
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```
