### ISSUE TITLE
Support duplicate deployment naming

### ISSUE THREAD

**Issue by psimms-r7** [argoproj/argo-cd#9336]
# Summary

What change you think needs making.

Allow support for the same application to be deployed to several clusters with the application helm deployment name the same, remove the dependancy (or allow to deviate from) that the argocd application name is the helm deployment name.

When the application is defined in argocd the application name is used as the deployment name when deployed into the cluster and since the application name has to be unique in argocd then the deployment name as deployed in the cluster will always be unique also.

This adds unnecessary naming to applications in each cluster and means that deployments that are deployed pre argocd will not be picked up by argocd due to the naming being different.  The currently deployed applications (not deployed via argocd) will have to be handled outside of argocd.

Example errors when attempting same naming
```
external-dns is already owned by another ApplicationSet controller
ApplicationSet apps contains applications with duplicate name: external-dns
```

Example applicationset
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-suite
spec:
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/example/argocd-apps
            revision: master
            directories:
            - path: ApplicationSets/app-suite/apps/**/*
        - clusters:
            selector:
              matchLabels:
                app-suite: "true"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/example/argocd-apps
        targetRevision: master
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path[3]}}'
```

# Motivation

Please give examples of your use case, e.g. when would you use this.

We deploy a suite of auxiliary applications to every cluster, with the applications always being the same across all environments, all clusters currently have these installed prior to argocd, when argocd installs the applications unique deployments are created, creating duplicate application deployments, with the previously deployed applications needing to be handled outside of argocd.

For this to work we need to either have a unique name (name: '{{name}}-{{path.basename}}') per application or create the application under a unique namespace

# Proposal

How do you think this should be implemented?

Few suggestions:

- This ticket if implement could fix the issue - https://github.com/argoproj/argo-cd/issues/3474 - So that applications can be installed to their unique namespace (say name of cluster) which would mean the applications are contained to their namespace in question.
- Allow the argocd application name to be different to the helm deployment name - remove the dependancy and allow to deviate from the argocd application name = helm deployment name
- Have additional metadata per app tied to the cluster its deployed to which can be used to distinguish between apps preventing duplicate naming but still allow duplicate helm deployment name
- Use the default helm chart deployment name unless overwritten
