### ISSUE TITLE
ArgoCD doesn't see changes after Helm chart rebuild

### ISSUE THREAD

**Issue by yatakoi** [argoproj/argo-cd#9357]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After making changes to the chart and packaging in the Nexus, the old value records still remain.

**To Reproduce**

In values.yaml
```
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  ```

**Expected behavior**

I deleted all these entries and rebuilt the chart. Then in ArgoCD UI chose `NEW APP`. In `SOURCE` chose `Repository URL` and chose `https://nexus.domain/repository/helm-hosted`. In section `Chart` i chose my chart.

After that, there are still fields `nameOverride`, `fullnameOverride`, `serviceAccount.create` and `serviceAccount.name` in `HELM` section.

Even if I delete the chart from the Nexus repository and build it again, ArgoCD still does not see the changes.

And if I just rename the chart and commit it to the repository, then ArgoCD will see the new chart with the new changes.

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:46:59Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.2.1+122ecef
```
