### ISSUE TITLE
Add labels to the notifications-controller ServiceAccount manifest(s)

### ISSUE THREAD

**Issue by NickLarsenNZ** [argoproj/argo-cd#9359]
# Summary

Add labels to the notifications-controller ServiceAccount manifest(s)

# Motivation

All other ServiceAccounts have labels

https://github.com/argoproj/argo-cd/blob/f75e881d3038e8b8c770bbef9bacdb6267b1a0ac/manifests/install.yaml#L8993-L9001

While the notifications-controller ServiceAccount is inconsistent:

https://github.com/argoproj/argo-cd/blob/f75e881d3038e8b8c770bbef9bacdb6267b1a0ac/manifests/install.yaml#L9020-L9024

# Proposal

```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-controller
```
