### ISSUE TITLE
UI returns randomly: Unable to load data: Forbidden

### ISSUE THREAD

**Issue by antonionappi88** [argoproj/argo-cd#9362]
Checklist:

* [/] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [/] I've included steps to reproduce the bug.
* [/] I've pasted the output of `argocd version`.

**Describe the bug**

When I try to visualize the tree of an application via the UI, it doesn't work. The UI returns me `Unable to load data: Forbidden`

**To Reproduce**

Not sure how to reproduce

**Expected behavior**

I would expect that I'm able to visualize since via argocd command line it works.

**Screenshots**

**Version**

```shell
argocd-server: v2.3.2+ecc2af9
  BuildDate: 2022-03-23T00:40:57Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
```

**More info**

User-info
```
argocd account get-user-info
Logged In: true
Username: my_username@example.com
Issuer: https://jeedy-argocd-prod.example.com/api/dex
Groups: jeedy-admin
```
Can-i command

```
argocd account can-i get applications '*/*'
yes
```

Dex configuration:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  policy.csv: |
    p, role:jeedy-admin, *, *, *, allow
    p, role:jeedy-reader, *, get, */*, allow
    g, jeedy-reader, role:jeedy-reader
    g, jeedy-admin, role:jeedy-admin
  policy.default: ""
```
Any clue ?
