### ISSUE TITLE
RBAC Regex Validation Issues 

### ISSUE THREAD

**Issue by wesbrownfavor** [argoproj/argo-cd#9363]
From what I can see Regex support was added to ArgoCD in [v2.2.0](https://github.com/argoproj/argo-cd/releases/tag/v2.2.0) with PR [#7165](https://github.com/argoproj/argo-cd/pull/7165).  In practice though I'm having trouble getting it to work.  I've talked with folks in the Slack channel and it was recommended I make an Issue for this.

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I should be able to set `policy.matchMode: regex` in my RBAC ConfigMap data and use Regex instead of Glob based matching according to PR #7165.  As far as I can tell changing `policy.matchMode` makes no difference and only Glob based matching seems to work.

**To Reproduce**

Create the following config map to test a basic regex

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.matchMode: regex
  policy.csv: |
    p, role:engineer, applications, create, .+/.+, allow
    g, yourOrg:yourTeam, role:engineer
```

Attempt to verify the application create command using cli

```
$ argocd admin settings rbac can role:engineer create applications 'myapp/myapp' --policy-file argocd-rbac-cm.yaml
No
```

If you change the match rule to `*/*` the argocd admin command will return a **Yes** instead.

I have tried the following patterns to no avail:
```
\w+/\w+
\w+\/\w+
.+/.+
.+\/.+
```

**Expected behavior**

I would expect the argocd admin cli to return a **Yes** when a valid regex is used in the configmap along with `policy.matchMode: regex` being set.  I would equally expect it to return a **No** when a glob match pattern is used with `policy.matchMode: regex` set.

**Screenshots**

n/a

**Version**

```shell
 argocd version                                                                                                            
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:20:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
n/a
```
