### ISSUE TITLE
in-tree helm dependencies' dependency build order is wrong

### ISSUE THREAD

**Issue by aogier** [argoproj/argo-cd#9379]
Hi, I have a situation where the order of `helm dependency build` change the output, which can be invalid/miss stuff.

I'm having a simple application:

```yaml
  source:
    helm:
      valueFiles:
        - values.yaml
    path: manifests/main
    repoURL: git@github.com:aogier/istio-deps.git
    targetRevision: feature/dependencies-build
```

this application contains a big umbrella chart which include couple dependencies:

```yaml
dependencies:
  - name: kube-prometheus-stack
    version: 34.10.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: dependency
    version: 0.1.0
    repository: file://../dependency
    alias: prometheus-istio-gw
  - name: dependency
    version: 0.1.0
    repository: file://../dependency
    alias: alertmanager-istio-gw
```

Both remote and in-tree manifests in turn include dependencies. I version the `Chart.lock` as usual and push on my repo.

The problem is: dependency manifests from in-tree dependency does not get generated if `helm dependency build` is executed the way it currently is on my setup, and the big application miss pieces.

What I've observed is, if I connect to repo-server pod and make a `dep build` in the in-tree dep *first*, then I rebuild deps in including app, then everything is generated as expected.

I've created PoC with an application and charts here https://github.com/aogier/istio-deps

In my current setup, this application produce 3 Deployments:

* grafana
* prome-operator
* kube-state-metrics
 
from the `https://` dependency, but it is expected it produce two oauth2-proxy, included twice by `file://` dependency.

Now, if i open a shell on repo-server pod and I touch nothing, go in the proper dir and launch helm:

```shell
manifests/main$ helm template ciao . -f values.yaml | grep 'kind: Deployment'
kind: Deployment
kind: Deployment
kind: Deployment
```
which is indeed what I see in web ui. Now, if I rebuild dependencies in order, then I relaunch helm template:

```shell
manifests/dependency$ helm dependency build
[...]
manifests/main$ helm dependency build
[...]
manifests/main$ helm template ciao . -f values.yaml | grep 'kind: Deployment'
kind: Deployment
kind: Deployment
kind: Deployment
kind: Deployment
kind: Deployment
```

now they are 5, and I'd be happy to have them from the start :grimacing: 

versions:

```
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:46:59Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:46:59Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: v4.5.4 2022-03-28T23:12:45Z
  Helm Version: v3.8.2+g6e3701e
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

am I missing something to get what I consider to be the correct behavior, which is what generates 5 Deploy for me?

Thanks for everything, regards
