### ISSUE TITLE
Question: Helm repository with multible values files 

### ISSUE THREAD

**Issue by rpahli** [argoproj/argo-cd#938]
We are using helm for our deployments with multiple helm repositories. The directory structure looks like:
```
<ENV>/<APPLICATION_NAME>/values.yaml
```
It would be great to have a detection mechanism for this. Something like a argo.yaml which we can placed inside the directory.

Example:
```
type: helm
helm-repository: stable
chart: redis
version: 1.0.0
```

do you think this is useful?

**Comment by rpahli** [comment]
Ok that's what I'm looking for. But what I miss is the opportunity to use remote helm repositories with local values files.

**Comment by alexmt** [comment]
You might use URL. e.g. 

```
  source:
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/helm-guestbook/values-production.yaml
```

Unfortunately, Helm does not support URLs which require authentication.

**Comment by rpahli** [comment]
What I mean is I want to use remote helm chart (tgz files) for example from https://hub.helm.sh and only the values files are in a git repositories.

**Comment by rpahli** [comment]
Ok I'll check it if this works for us.

Thanks

**Comment by alexmt** [comment]
First class help charts without involving git is WIP. I think we can close this one. @rpahli please feel free to reopen if #1145 does not cover your use case

**Comment by omallo** [comment]
Hi @alexmt , I do have a similar requirement as @rpahli and I believe that #1145 is not really addressing this fully.

With the implementation in #1145, when using a Helm repository as a source, it is not possible to use the `source.helm.valueFiles` or `source.helm.fileParameters` elements since there is no reference to a Git repository in which those external files would be stored.

Would it make sense to still point to a Git repository in the source section and instead configure the Helm chart inside the `source.helm` element in order to provide such a support? Something like the following:

```yaml
source:
  # the Git repository in which the values files and other files required for Helm are stored
  repoURL: https://github.com/xxx/yyy.git
  targetRevision: master
  path: my-nginx
  helm:
    # the chart repository/name/version
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    chartVersion: 4.0.3
    # the following values files and other files are stored in the Git repository referenced above
    valueFiles:
      - values.yaml
    fileParameters:
      - name: certificate.content
        path: certificate.crt
```

I believe this would have the following important advantages:

- Complex values files can be externalized and don't have to be defined inside the Application manifest file.
- Arbitrary files (also binary files) can be referenced and passed to Helm.
- The Helm overlaying mechanism for values files can be used by specifying multiple values files.
- The deployment can also be done directly with Helm, w/o using ArgoCD, e.g. for local testing.

Would it make sense to re-consider having such a functionality?
