### ISSUE TITLE
ArgoCD CMP Sidecar Discover Find Command not working

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#9382]
ArgoCD v2.3.3

```
time="2022-05-11T19:27:29Z" level=info msg="bash -c echo finding; find . -type f -name kustomization.yaml | grep . && find . -type f -n
time="2022-05-11T19:27:29Z" level=info msg="bash -c echo finding; find . -type f -name kustomization.yaml | grep . && find . -type f -n
time="2022-05-11T19:27:29Z" level=error msg="finished unary call with code Unknown" error="fork/exec /usr/bin/bash: no such file or dir
time="2022-05-11T19:27:29Z" level=error msg="finished unary call with code Unknown" error="fork/exec /usr/bin/bash: no such file or dir
time="2022-05-11T19:27:58Z" level=info msg="bash -c echo finding; find . -type f -name kustomization.yaml | grep . && find . -type f -n
time="2022-05-11T19:27:58Z" level=error msg="finished unary call with code Unknown" error="fork/exec /usr/bin/bash: no such file or dir
time="2022-05-11T19:32:16Z" level=info msg="Alloc=6200 TotalAlloc=16958 Sys=20049 NumGC=9 Goroutines=23"
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin-kustomized-helm
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomized-helm
    spec:
      init:
        command: ["sh", "-c"]
        args: ["echo hello; helm repo add ${helm_dependency_name} ${helm_dependency_repo} && helm dependency update ${helm_base}"]
      generate:
        command: ["sh", "-c"]
        args: ["echo world; helm template --include-crds ${helm_dependency_name} ${helm_base} ${helm_args} > ${helm_base}/all.yaml && kustomize build . --enable-helm > all.yaml && argocd-vault-plugin generate all.yaml"]
      discover:
        find:
          command: ["bash", "-c", "echo finding; find . -type f -name kustomization.yaml | grep . && find . -type f -name Chart.yaml | grep ."]
```

Note this image gets overridden with a custom image. Dockerfile below.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  # replicas: 3
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: true
      containers:
        - name: argocd-vault-plugin-kustomized-helm
          command: [/var/run/argocd/argocd-cmp-server]
          image: quay.io/argoproj/argocd:v2.3.3
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: argocd-vault-plugin-kustomized-helm
      volumes:
        - configMap:
            name: argocd-vault-plugin-kustomized-helm
          name: argocd-vault-plugin-kustomized-helm
```

```
FROM quay.io/argoproj/argocd:v2.3.3
### https://github.com/argoproj/argo-cd/releases

USER root

### Install dependencies for gcloud
RUN apt-get update -y && apt-get install -y \
        curl \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

### Install gcloud
### https://cloud.google.com/sdk/docs/install#deb
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | \
    tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && \
    apt-get update -y && apt-get install -y \
        google-cloud-sdk \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

### Install argo vault plugin
### https://github.com/IBM/argocd-vault-plugin
### https://github.com/IBM/argocd-vault-plugin/releases
ARG ARGOCD_VAULT_PLUGIN_VERSION="1.10.1"
RUN curl -L -o argocd-vault-plugin https://github.com/IBM/argocd-vault-plugin/releases/download/v${ARGOCD_VAULT_PLUGIN_VERSION}/argocd-vault-plugin_${ARGOCD_VAULT_PLUGIN_VERSION}_linux_amd64
RUN chmod +x argocd-vault-plugin
RUN mv argocd-vault-plugin /usr/local/bin

# ### Install helm
# ARG HELM3_VERSION=v3.6.3
# RUN curl -fsSL https://get.helm.sh/helm-${HELM3_VERSION}-linux-amd64.tar.gz | tar -zx --strip-components=1 -C /usr/local/bin linux-amd64/helm

# Install ytt
ARG YTT_VERSION="0.40.1"
RUN curl -L -o ytt https://github.com/vmware-tanzu/carvel-ytt/releases/download/v${YTT_VERSION}/ytt-linux-amd64
RUN chmod +x ytt
RUN mv ytt /usr/local/bin

USER 999

### Install helm-gcs helm plugin
### https://github.com/hayorov/helm-gcs/releases
### https://github.com/hayorov/helm-gcs/releases/tag/0.3.18
ARG GCS_PLUGIN_VERSION="0.3.20"
ARG GCS_PLUGIN_REPO="https://github.com/hayorov/helm-gcs.git"

RUN helm plugin install ${GCS_PLUGIN_REPO} --version ${GCS_PLUGIN_VERSION}

RUN helm repo add argo-helm-charts gs://argo-helm-charts

ENV HELM_PLUGINS="/home/argocd/.local/share/helm/plugins/"
```

Slack Thread
https://cloud-native.slack.com/archives/C01TSERG0KZ/p1652280511474889

@crenshaw-dev
