### ISSUE TITLE
ArgoCD ApplicationSet SCM generator eats GitHub API Rate Limit

### ISSUE THREAD

**Issue by IvanovOleg** [argoproj/argo-cd#9413]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
I have an ApplicationSet with SCM generator configured to poll GitHub repositories. In my simple case I just poll one repo branch. This simple configuration reaches the GitHub API Request limit of 5000 requests in 10 minutes. This fact makes SCM generator completely unstable.

**To Reproduce**
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: scm-development
spec:
  generators:
    - scmProvider:
        cloneProtocol: ssh
        github:
          organization: my-org
          allBranches: true
          tokenRef:
            secretName: github-token
            key: token
        filters:
          - repositoryMatch: ^my-repo
            pathsExist: [kustomize/overlays/development]   
            branchMatch: ^deploy   
  template:
    metadata:
      name: '{{ repository }}'
    spec:
      source:
        repoURL: '{{ url }}'
        targetRevision: '{{ branch }}'
        path: kustomize/overlays/development
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ repository }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

**Expected behavior**
Modest API request usage

**Screenshots**

**Version**

```shell
v2.3.3
```

**Logs**

```
error listing repos: error listing pull requests for my-org/my-repo: GET https://api.github.com/repos/my-org/my-repo/pulls?per_page=100: 403 API rate limit exceeded for user ID 12345678. [rate reset in 31m51s]
```

**Comment by crenshaw-dev** [comment]
Are there a lot of repos in the organization. The SCM generator loops over repos to list branches.

**Comment by crenshaw-dev** [comment]
It should apply your `repositoryMatch` filter before listing branches, which should help some.

After listing and filtering repos by name, it'll loop over the remaining repos and list branches.

After listing branches, it will filter by the `branchMatch` filter.

Then for each remaining branch, it'll make an API call to filter by `pathsExist`.

The regex filters are your friends. They should help minimize the API calls by a lot.

**Comment by IvanovOleg** [comment]
@crenshaw-dev I my example, I select only one repository and a single branch, but it drains all 5000 requests in less then 10 minutes.

**Comment by crenshaw-dev** [comment]
Oh wait. I just noticed the error message is about the Pull Request Generator? Are you sure the SCM generator is the issue? It shouldn't be hitting the PR API.

**Comment by crenshaw-dev** [comment]
If I understand correctly, you have it filtered down to one repo.

How many branches match the branch pattern for that one repo?

**Comment by IvanovOleg** [comment]
@crenshaw-dev that repo contains main branch and deploy branch. That's all. It's a POC, not a real app

**Comment by crenshaw-dev** [comment]
Wow. I'd have to dig into the code to get a good sense what's going wrong here. The generator code needs more debug logging. There's really no way to debug this without seeing what calls are being made.

**Comment by rishabh625** [comment]
I did a bit of debugging , but some how I don't see much of calls or rate limit being although my org had only 2 repo and 4 branches.

I think Key to debug it successfully would be to have a large organization, @IvanovOleg : Can u share size of repo and number of branches , we could replicated and add filter

As in code I see that it filters once all repo's are listed

**Comment by IvanovOleg** [comment]
@rishabh625 ~1000 repositories with at least 10 branches in each

**Comment by IvanovOleg** [comment]
Any updates?

**Comment by rishabh625** [comment]
> Any updates?

Not yet @IvanovOleg , will post you soon

**Comment by jetersen** [comment]
Perhaps it would help if ApplicationSet SCM generator used the exist secrets so it could pick up the GitHub App secret?

Instead of having to reference a separate token secret.

https://github.com/argoproj/argo-cd/search?q=GithubAppInstallationId

**Comment by crenshaw-dev** [comment]
@jetersen I think that might be what this PR does: https://github.com/argoproj/argo-cd/pull/10092 

Hoping to review it today.

**Comment by jetersen** [comment]
@crenshaw-dev thanks for cross linking, I was searching for issues and PRs but found this one first and dropped my comment here 😅

**Comment by dllegru** [comment]
> @jetersen Perhaps it would help if ApplicationSet SCM generator used the existing repo secrets so it could pick up the GitHub App secret?

I think it would help in terms that using GitHub App secret may allow to make more api calls compared to PAT, although imo we're not fixing the root issue which is that we're overusing api calls when we have `scmProvider` regexed into a repo + branch.

**Comment by jdomag** [comment]
I'm having the same issue with Bitbucket Cloud SCM:
```
        - scmProvider:
            bitbucket:
              # The workspace id (slug).  
              owner: "my-bitbucket-org"
              # The user to use for basic authentication with an app password.
              user: "my-bot-user"
              # If true, scan every branch of every repository. If false, scan only the main branch. Defaults to false.
              allBranches: false
              # Reference to a Secret containing an app password.
              appPasswordRef:
                secretName: argocd-repo-creds-bitbucket
                key: password
```
We have around 100 repos with few branches in each and application-set controller gets 429 :( 
In my case filtering by repo name is not an option. Shouldn't app set controller have some parameter that controls the number of calls per second?

**Comment by XLordalX** [comment]
Maybe it would be a good idea to allow changing query parameters. For example github allows filtering on topic in the api request. This would drastically reduce the amount of calls for us.

**Comment by alen-z** [comment]
Proving to be serious issue for us. We'd like to use `branchMatch`...

**Comment by jastBytes** [comment]
We seem to have the same problem. Are there any news on this?

**Comment by ftmiro** [comment]
I'm also facing the problem. My org has around 800 repositories. 

```
GET https://api.github.com/orgs/<my org>/repos?per_page=100: 403 API rate limit exceeded for installation ID <ID>
```

Allowing adding the filtered topics to the query would help in short term until the organization has many repositories that must be discovered using the topic (`argocd-discoverable`, for example). Would be possible to create some delay between the iterations? Seems that there's no waiting between the calls made to GitHub.


Another possibility would be drop the branchMatch. I think the idea of branch belongs to Git and not to the SCM, since they don't provide an API that allow us to filter repositories that contains a list of branches. Maybe this could be achieved by using a matrix of SCM + Git generators.

**Comment by cyrus-mc** [comment]
So I ran into this problem and decided to dig into the code. I believe the issue is that there is no precedence and logical operation (AND) to the rules given in a filter.

I too had a similar filter:

```
        filters:
          - repositoryMatch: ^my-repo
            pathsExist: [kustomize/overlays/development]   
            branchMatch: ^deploy 
```

Looking at the code I determined that it evaluates each of the conditions individually. It doesn't look for repos that match `^my-repo` and then further filter by `pathsExist` and `branchMatch`. 

If I removed the `pathsExist` and `branchMatch` I did not experience 429s.

**Comment by crenshaw-dev** [comment]
@cyrus-mc I believe this may be the fix: https://github.com/argoproj/argo-cd/pull/14465

**Comment by totti339** [comment]
I'm facing the same issue. Can't we just control the polling interval and set something more than 60s ? I tried multiple option and looked into the code but didn't find any parameter that allows doing that.

**Comment by Jerrimikkihvatai** [comment]
Any updates here? I'm facing the same issue on v2.13.1 , this bug makes impossible one of the argocd's main feature - generate applications in respect of braches in the github repo

**Comment by bennesp** [comment]
Facing same issue with v2.14.2

**Comment by Jerrimikkihvatai** [comment]
For anyone, who is struggling with this problem, i have written a small [argocd generator plugin](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Generators-Plugin/) to overcome this issue
https://github.com/Jerrimikkihvatai/argocd-github-generator

**Comment by BadLiveware** [comment]
Still an issue as of 3.0.12

**Comment by voidlily** [comment]
To add another data point, I still see this on 3.3.4. My org has about 250 repos with a generator setup like this

```
  generators:
    - matrix:
        generators:
          - scmProvider:
              cloneProtocol: https
              github:
                organization: org-name
                appSecretName: secret-name
              filters:
                - pathsExist: ["k8s/clusters/"]
                  # https://github.com/argoproj/argo-cd/issues/18531
                  # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/#filters
                  pathsDoNotExist: ["disabledrepo.txt"]
          - git:
              repoURL: "{{ .url }}"
              revision: HEAD
              files:
                - path: "k8s/clusters/*/kustomization.yaml"
```

This results in around 40-45 repos that match out of the 250, but the appset is constantly being affected by rate limits so any new repos can take quite a long time to actually get picked up by the SCM generator and apps created for them.

Because allBranches defaults to false, it shouldn't be iterating over all branches (some of our larger repos have either lots of outstanding branches, or stale branches from merged PRs) and should just be hitting the default branch. Unless there's some interaction where pathsExist means it's looking across allBranches anyway now, but I'm grasping at straws and just throwing out an idea currently.

**Comment by roulettedares** [comment]
with about 100 repos, i'm getting

```
error failed to get params for first generator in matrix generator: child generator returned an error on parameter generation: error getting param sets from generators: error getting params from generator 1 of 2: child generator returned an error on parameter generation: error listing repos: error listing branches for foo/bar 429 Too Many Requests
```

with this applicationset
```
  apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: preview-environments
    namespace: argocd
  spec:
    goTemplate: true
    goTemplateOptions: ["missingkey=error"]
    generators:
      - matrix:
          generators:
            - merge:
                mergeKeys:
                  - repository
                generators:
                  - scmProvider:
                      bitbucket:
                        owner: <ORG>
                        user: username
                        appPasswordRef:
                          secretName: <CREDS_SECRET>
                          key: password
                      filters:
                        - branchMatch: "^(main|master)$"
                          pathsExist:
                            - preview
                  - scmProvider:
                      bitbucket:
                        owner: <ORG>
                        user: username
                        appPasswordRef:
                          secretName: <CREDS_SECRET>
                          key: password
                      filters:
                        - branchMatch: "^preview-bootstrap$"
                          pathsExist:
                            - preview
            - pullRequest:
                bitbucket:
                  owner: <ORG>
                  repo: "{{ .repository }}"
                  bearerToken:
                    tokenRef:
                      secretName: username
                      key: token
                requeueAfterSeconds: 1800
                filters:
                  - targetBranchMatch: "^(main|master)$"
    template:
      metadata:
        name: "preview-{{ .number }}-{{ .repository }}"
        namespace: argocd
        labels:
          preview.example.com/pr: "{{ .number }}"
          preview.example.com/repo: "{{ .repository }}"
        finalizers:
          - resources-finalizer.argocd.argoproj.io
      spec:
        project: preview
        sources:
          - repoURL: "https://bitbucket.org/{{ .organization }}/{{ .repository }}.git"
            targetRevision: "{{ .head_sha }}"
            path: "charts/{{ .repository }}"
            helm:
              releaseName: "{{ .repository }}"
              ignoreMissingValueFiles: true
              parameters:
                - name: image.tag
                  value: "0.0.0-PR-{{ .number }}"
                - name: podAnnotations.deploy/commit
                  value: "{{ .head_short_sha_7 }}"
                - name: ingress.host
                  value: "{{ .repository }}-pr{{ .number }}.<PREVIEW_DOMAIN>"
              valueFiles:
                - $gitops/clusters/<CLUSTER>/preview/values.yaml
                - ../../preview/preview-values.yaml
          - repoURL: https://bitbucket.org/<ORG>/<GITOPS_REPO>.git
            targetRevision: HEAD
            path: clusters/<CLUSTER>/preview/stacks/base
            helm:
              releaseName: "preview-{{ .number }}-{{ .repository }}-base"
              parameters:
                - name: pr
                  value: "{{ .number }}"
                - name: repo
                  value: "{{ .repository }}"
          - repoURL: https://bitbucket.org/<ORG>/<GITOPS_REPO>.git
            targetRevision: HEAD
            ref: gitops
        destination:
          name: <CLUSTER>
          namespace: "preview-{{ .number }}-{{ .repository }}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - ServerSideApply=true
            - ApplyOutOfSyncOnly=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
          retry:
            limit: 5
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m
```

is there a lighter fix than https://github.com/argoproj/argo-cd/pull/26086 that could make it in more easily?
