### ISSUE TITLE
Global values file that can feed into all values files

### ISSUE THREAD

**Issue by psimms-r7** [argoproj/argo-cd#9423]
# Summary

What change you think needs making.

When adding a cluster to argocd we can add several labels, cluster specific data that can be used later in the values file (or an additional cluster config file in git repo)
Example, region, aws account id, vpc id, subnet ids, hosted zones etc.

We can then pull this metadata from the cluster (or config file) and pass in as parameters (or fileParameters) into the helm values

What would be great if we could pass these into a global values file, then all apps / values files could use data from this global values file

Example
Application passing in global parameters (or instead use fileParameters)
```
      source:
        repoURL: https://github.com/example/argocd-apps
        targetRevision: example
        path: apps
        helm:
          parameters:
          - name: global.awsAccount
            value: '{{metadata.labels.awsAccount}}'
          - name: global.clusterName
            value: '{{metadata.labels.clusterName}}'
          - name: global.region
            value: '{{metadata.labels.region}}'
          - name: global.zoneIDs
            value: '{{metadata.labels.zoneIDs}}'
          - name: global.image.tag
            value: '{{metadata.labels.tag}}'
          - name: global.image.pullPolicy
            value: '{{metadata.labels.pullPolicy}}'
          releaseName: '{{path.basename}}'
          valueFiles:
            - globalValues.yaml
            - values.yaml
```

globalValues.yaml
```
global:
  awsAccount: null
  clusterName: null
  region: null
  zoneIDs: null
  image:
    tag: null
    pullPolicy: null
```

values.yaml for 1 app, however option to use same globals across several others
```
external-dns:
  image:
    tag: {{ .Values.global.image.tag }}
    pullPolicy: {{ .Values.global.image.pullPolicy }}
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn : "arn:aws:iam::{{ .Values.global.awsAccount }}:role/{{ .Values.global.region }}/external-dns"
  txtOwnerId: {{ .Values.global.clusterName }}
  zoneIdFilters: [{{ .Values.global.zoneIDs }}]
  aws:
    region: {{ .Values.global.region }}
```

However something like the above does not seem to work, I believe this is supported in helm and am wondering if this or something along these lines could work in argocd?

Example error
```
error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.global.image.tag":interface {}(nil)}
```
# Motivation

Please give examples of your use case, e.g. when would you use this.

The need to deploy the same application/helm chart to several clusters but only using the single values file per app and passing in cluster specific data into this single values file

# Proposal

How do you think this should be implemented?
I am not 100% if this is the best way to do this, or if there is a better way to achieve this or if this is possible already?
But ideally using the single values file per application and passing in per cluster data (which we can get from the cluster) into values file
