### ISSUE TITLE
CLI returns "certificate signed by unknown authority"

### ISSUE THREAD

**Issue by Yaytay** [argoproj/argo-cd#9429]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I am unable to establish a secure connection to ArgoCD:
```shell
$ argocd login argocd-server
WARNING: server certificate had error: x509: certificate signed by unknown authority. Proceed insecurely (y/n)? n
```

**To Reproduce**
On a clean installation of Docker Desktop:

1. Install nginx-ingress
```shell
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
```
2. Install argocd:
```shell
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```
3.  Create the ingress:
Save this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: argocd-server
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port: 
               number: 443
```
as argocd-ingress.yml and then apply:
```shell
kubectl apply -n argocd -f argocd-ingress.yml
```
4. Ensure that argocd-server is in localhost:
```shell
grep argocd-server /etc/hosts || echo '127.0.0.1     argocd-server' | sudo tee -a /etc/hosts
```
5. Test:
```shell
argocd login argocd-server
WARNING: server certificate had error: x509: certificate signed by unknown authority. Proceed insecurely (y/n)? n
``` 

Checking with openssl indicates that the cert is coming from ArgoCD:
```shell
$ echo quit | openssl s_client -showcerts -servername argocd-server -connect argocd-server:443 | head
depth=0 O = Argo CD
verify error:num=18:self signed certificate
verify return:1
depth=0 O = Argo CD
verify return:1
CONNECTED(00000003)
---
Certificate chain
 0 s:O = Argo CD
   i:O = Argo CD
-----BEGIN CERTIFICATE-----
MIIDYjCCAkqgAwIBAgIQXxa6rX0ZcIgeHI4opRxuyzANBgkqhkiG9w0BAQsFADAS
MRAwDgYDVQQKEwdBcmdvIENEMB4XDTIyMDUxNzEyMDc1M1oXDTIzMDUxNzEyMDc1
M1owEjEQMA4GA1UEChMHQXJnbyBDRDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAOhItSIG+Xa60BZQ+NupQ3TV7W1HPJbi3uH4Xk8hs3KBlIlGOlLgiPBt
DONE
```

I have also tried using the argocd-server-tls secret to validate that the certificate being used is not the nginx-ingress one, and that produces errors that include the valid names of the cert, so the cert is definitely coming from the argocd pod - but the argocd CLI doesn't accept it.

I cannot find any documentation about what the cert is _supposed_ to be.
At the moment the [FAQ entry for this](https://argo-cd.readthedocs.io/en/stable/faq/#why-am-i-getting-x509-certificate-signed-by-unknown-authority-when-using-the-cli) contains no more information than the CLI output.
It would be really helpful if that entry contained details on what the cert should be.

**Expected behavior**
Some sort of request for credentials, anything other than a cert error.

**Version**

```shell
$ argocd version
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:17:09Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```
Running on Windows 11 using WSL2.
