### ISSUE TITLE
Kubelogin support in ArgoCD

### ISSUE THREAD

**Issue by rphua** [argoproj/argo-cd#9460]
# Summary

It would be nice if ArgoCD could add support for the [Kubelogin plugin](https://github.com/Azure/kubelogin) for AKS clusters.

# Motivation

For security reasons we have enabled Azure AD RBAC for all of our clusters. However, right now it is not possible to use Kubelogin for ArgoCD. Instead it uses the cluster admin credentials which bypasses the Azure AD RBAC check. 

# Proposal

Add an option to enable the Kubelogin plugin. Kubelogin is based on the client-go credential plugin: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

**Comment by mmerrill3** [comment]
if this is not being worked on, I'll work on a PR for it.

**Comment by kgopi1** [comment]
waiting for this feature to be added to support AKS Clusters.

**Comment by GOVYANSONG** [comment]
This is an awesome feature. Thanks for the contribution. Just a minor question, does this new feature handles device code flow (an interactive auth. mode). or some other steps need to be taken e.g. mount the kubelogin auth credential cache file.

**Comment by nicholass-alcidion** [comment]
I have been able to get kubelogin working for our clusters by installing kubelogin via an init container, and then configuring the cluster with external login.

I am using kustomize for my argo-cd deployments, here are the overlays I am using install kubelogin. I am fairly sure I only to be adding kubelogin to the `argocd-application-controller` StatefulSet but have not tested this.

Once kubelogin is installed I was able to configure a cluster with execProviderConfig

`overlays/argocd-kubelogin.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - >-
            wget -qO- https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip |
            unzip -x bin/linux_amd64/kubelogin -p - > /custom-tools/kubelogin &&
            chmod a+x /custom-tools/kubelogin
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      containers:
      - name: argocd-server
        volumeMounts:
        - mountPath: /usr/local/bin/kubelogin
          name: custom-tools
          subPath: kubelogin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - >-
            wget -qO- https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip |
            unzip -x bin/linux_amd64/kubelogin -p - > /custom-tools/kubelogin &&
            chmod a+x /custom-tools/kubelogin
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      containers:
      - name: argocd-application-controller
        volumeMounts:
        - mountPath: /usr/local/bin/kubelogin
          name: custom-tools
          subPath: kubelogin
```

```json
    {
      "execProviderConfig": {
        "apiVersion": "client.authentication.k8s.io/v1beta1",
        "command": "/usr/local/bin/kubelogin",
        "args": [
          "get-token",
          "--login",
          "spn",
          "--server-id",
          "00000000-0000-0000-0000-000000000000",
          "--client-id",
          "00000000-0000-0000-0000-000000000000",
          "--tenant-id",
          "00000000-0000-0000-0000-000000000000",
          "--environment",
          "AzurePublicCloud"
        ],
        "env": {
          "AAD_SERVICE_PRINCIPAL_CLIENT_ID": "00000000-0000-0000-0000-000000000000",
          "AAD_SERVICE_PRINCIPAL_CLIENT_SECRET": "secret"
        },
        "installHint": "kubelogin missing"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "base64encodedCaDataAsNormal"
      }
    }
```
