### ISSUE TITLE
Rework local config to support multiple servers/credentials

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#95]
The local argocd config should to support multiple servers at the same time, switching between configuration contexts, as well as optionally storing self-signed certificates into the local ~/.argocd/config. In other words, ~/.argocd/config should look more like ~/.kube/config. 

The resulting change will be the following user experience:

```
$ argocd login my-argocd-server.example.com --context-name my-argocd
WARNING: this server uses a self-signed certificate. Store the certificate and proceed? (y/n) y
Username: admin
Password:
```

The resulting config will look like (up for discussion):
```
current-context: my-argocd

contexts:
- name: my-argocd
  server: my-argocd-server.example.com
  user: my-argocd-server.example.com

servers:
- server: my-argocd-server.example.com
  certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSU.......LS0tLQo=

users:
- name: my-argocd-server.example.com
  session-token: eyJhbGciOiJI....l-6XOUVAxy8
```

We would then introduce some commands for switching between contexts. e.g.
```
argocd config use-context CONTEXTNAME
```
