### ISSUE TITLE
Deploy one application to multiple namespaces within one cluster

### ISSUE THREAD

**Issue by storm1kk** [argoproj/argo-cd#9508]
Dear ArgoCD team,

I was wondering if there is a possibility to deploy one application to multiple namespaces. I would like to use one helm chart with different values files. I found only one issue about this matter - https://github.com/argoproj/argo-cd/issues/696 but probably, something changed since. I understand that ArgoCD uses 'kubectl apply -f manifest.yaml --namespace' but could this be executed multiple times with different namespace parameter each time, for example? Or could it be like ApplicationSet but with namespace generators?

I know I can use AppOfApps but it seems like a lot of work. I need to create like 10 root apps, one for each namespace, with 50 apps inside each of them. It is hard to manage such repo. It would be much nicer to have one application definition which uses one application helm chart with multiple values files for each environment.

Probably, there is another solution for my problem but I didn't find it yet.

Thanks in advance!

**Comment by crenshaw-dev** [comment]
If I recall correctly, Argo CD respects whatever is in the manifest, and only uses the `namespace` field from the Application manifest if the namespace isn't explicitly set in the generated manifest.

**Comment by wilsonwu** [comment]
Seems not a common use case.

**Comment by storm1kk** [comment]
It is actually. Imagine we have a bunch of apps we need to deploy to different environments like dev, sit, rc within one K8s cluster. Would be much easier if ArgoCD can accept multiple namespaces as parameter to deploy.

**Comment by rodrigo14miguel** [comment]
Another use case would be a multitenant cluster where you want to have multiple infra components like ingress controllers and prometheus in multiple namespaces.

I don't know if this is possible as I don't use ApplicationSet, assuming the base yaml files that are being applied do not specify a namespace, maybe by specifying a single target cluster, multiple target namespaces and some kind of dynamic prefix/sufix (like namespace name) in an ApplicationSet. Maybe this would address the issue.

I don't know if this is possible right now.

**Comment by storm1kk** [comment]
> Ah, my original comment doesn't make sense. I see you're trying to deploy multiple _copies_ of a set of manifests, but to different namespaces.

That's right.

> I'd definitely recommend ApplicationSets.

I already looked into ApplicationSet but I only found a way to deploy to multiple clusters not namespaces. 

> The idea of duplicating at the Application level is interesting. But it's unclear to me how you'd customize on a per-namespace basis. For example, if I want my dev namespace manifests to use my dev image repository, how would I specify that in the Application spec?

I would use different values.yaml files for different namespaces. 
For example, I have a helm repo with app definition files + values.yaml + values-dev.yaml + values-prod.yaml. I need to somehow tell ArgoCD that I want to deploy my app to dev and prod namespaces using values.yaml + values-dev.yaml and values.yaml + values-prod.yaml respectively. That is how I can control whatever parameter of my app including a different image repository.

**Comment by crenshaw-dev** [comment]
> I only found a way to deploy to multiple clusters not namespaces.

`namespace` is just a text field in the Application spec. If your manifests don't explicitly set namespaces, the App spec namespace will take precedence.

Alternatively, you could template the values file name in the Application spec and then use different namespace parameters in the different values files. 

There's no "namespace generator," but you could just use a list generator and hard-code the names of the namespaces.

**Comment by storm1kk** [comment]
@crenshaw-dev thanks for the hint! ApplicationSet works fine for me :)
This definition of ApplicationSet gives me what I want. It deploys my app to different namspaces us gin different values values. So cool 🚀 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-app
spec:
  generators:
  - list:
      elements:
      - namespace: argocd-poc-dev
        url: https://kubernetes.default.svc
      - namespace: argocd-poc-dev-next
        url: https://kubernetes.default.svc
      - namespace: argocd-poc-sit
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-poc-app'
    spec:
      project: default
      source:
        path: poc-app
        repoURL: https://tsnctc.visualstudio.com/argocd-poc/_git/helm-charts
        targetRevision: HEAD
        helm:
          releaseName: poc-app
          valueFiles:
            - values.yaml
            - values-{{"{{"}}namespace{{"}}"}}.yaml
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: '{{"{{"}}namespace{{"}}"}}'
```
