### ISSUE TITLE
Not clear what defines resource.inclusions/.exclusions with ArgoCD operator

### ISSUE THREAD

**Issue by flightofthunder** [argoproj/argo-cd#9514]
Checklist:

- [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of argocd version.

**Describe the bug**

I've spent a while trying to understand some very bizarre behaviour in which the values of `resource.inclusions` and `resource.exclusions` were blank in the `argocd-cm` configmap, despite defining them in my `argocd-cm.yaml`.

Here is an example of the `argocd-cm.yaml` that I installed via `helm` (based off of this documentation: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data
  resource.inclusions: |
    - apiGroups:
      - "*"
      kinds:
      - Deployment
      - DeploymentConfig
      - StatefulSet
      - ConfigMap
      - Service
      - Route
      - Application
      - Secret
      - PersistentVolumeClaim
      - ServiceAccount
      clusters:
      - "*"
```

However, whenever my app would start, the `resource.inclusions` would end up being blank.

After some more searching, I found this document, relating to the argocd-opertator: https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#resource-exclusions

I added the `resourceInclusions` to the spec and the configmap was no longer being reset.
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  resourceInclusions: |
    - apiGroups:
      - "*"
      kinds:
      - Deployment
      - DeploymentConfig
      - StatefulSet
      - ConfigMap
      - Service
      - Route
      - Application
      - Secret
      - PersistentVolumeClaim
      - ServiceAccount
      clusters:
      - "*"
```

However, whenever I run a `helm upgrade`, the behaviour is inconsistent. Sometimes it takes what is defined in the `argocd-operator.yaml` `spec.resourceInclusions`, sometime it takes what is defined in `argocd-cm.yaml` `data.resource.inclusions`.

Note: I tested with different values in the `argocd-operator.yaml` `spec.resourceInclusions` vs `argocd-cm.yaml` `data.resource.inclusions` to verify where the configuration was coming from.

**Expected behaviour**
ArgoCD with ArgoCD operator consistently assigns the value of `resource.inclusions` either from `argocd-operator.yaml` or from `argocd-cm.yaml`, and this is clearly indicated in the documentation linked in this issue.

**Version**
```
argocd: v2.3.4+unknown
  BuildDate: 2022-05-16T13:41:14Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.17.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.4+unknown
  BuildDate: 2022-05-16T13:41:14Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.17.7
  Compiler: gc
  Platform: linux/amd64
```
