### ISSUE TITLE
ArgoCD expects index.yaml for Helm Chart on OCI Registry when using SemVer Ranges

### ISSUE THREAD

**Issue by rowi1de** [argoproj/argo-cd#9528]
### Discussed in https://github.com/argoproj/argo-cd/discussions/9509

<div type='discussions-op-text'>

<sup>Originally posted by **rowi1de** May 25, 2022</sup>
- For Git based you are able to point an Application to a branch or ref
```yaml
  source:
    repoURL:  https://github.com/rowi1de/graphql-reactive
    targetRevision:  HEAD
```
- ArgoCD will always deploy the latest commit / revision

- For Helm in OCI you need to specify a fixed Version of the Helm Chart in the Application
 ```yaml
  project: my-helm-chart
  source:
    repoURL: ghcr.io/rowi1de/graphql-reactive
    targetRevision:  0.0.17
```

- For Classic Helm Registries you can use SemVer ranges: https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/
```yaml
  project: my-helm-chart
  source:
    repoURL: ghcr.io/rowi1de/graphql-reactive
    targetRevision: 0.0.*
```
- This doesn't work for Helm on OCI, as ArgoCD expect Index.yaml which is only available for classic helm repositories. https://github.com/argoproj/argo-cd/blob/7faae31ff6454d6a443c4e2a4d935c27447c0e96/reposerver/repository/repository.go#L1663 
- OCI doesn't allow discovering versions, but it can list tags: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery
- Also for helm pull, version ranges are supported

```shell
helm pull oci://ghcr.io/rowi1de/graphql-reactive/graphql-reactive --version '0.0.*'
Pulled: ghcr.io/rowi1de/graphql-reactive/graphql-reactive:0.0.17

helm pull oci://ghcr.io/rowi1de/graphql-reactive/graphql-reactive --version '0.1.*'
Pulled: ghcr.io/rowi1de/graphql-reactive/graphql-reactive:0.1.2
```

- My workflow is as follows
  - CI with GitHub Actions
     - [Tag & Push Docker Image with commit-id](https://github.com/rowi1de/graphql-reactive/actions/workflows/gradle-build-push-image.yml)
     - [Increment Patch Version of the Helm Chart based on SemVer](https://github.com/rowi1de/graphql-reactive/runs/6562238780?check_suite_focus=true#step:9:11)
     - [Publish new Helm Chart to Github Packages as OCI Image](https://github.com/rowi1de/graphql-reactive/runs/6562238780?check_suite_focus=true#step:12:40)
     - [Point Argo CD to the OCPI Image / Helm Chart](https://github.com/rowi1de/argocd/blob/main/services/graphql-reactive.yaml#L13)

- One Note: I'm currently not pushing the modified Chart.yaml from the GitHub Action Release workflow, so the committed Chart.yaml will always contain a wrong version
   
    
</div>

Or hoping for helm https://github.com/helm/helm/issues/11000
