### ISSUE TITLE
ArgoCD Notifications - Allow trigger conditions/when input as list

### ISSUE THREAD

**Issue by terbolous** [argoproj/argo-cd#9573]
# Summary

When your trigger has multiple conditions they need to be added to the `when` field. Allow those conditions to be sent as a list

# Motivation

I believe a change to list format would increase readability, reduce the chance of human error and in general be an improvement

# Proposal

Allow the `when` field to be a list.

Consider these two:

Current version:
```
trigger.foo: |
  - description: multiple conditions needed to trigger
     send: app-sync-succeeded
     when: app.status.operationState.phase in ['Succeeded', 'Running', 'Error', 'Failed'] and app.metadata.annotations["something"] == "bar" and context.something == "baz"
```

Proposed version:
```
trigger.foo: |
  - description: multiple conditions needed to trigger
     send: app-sync-succeeded
     when: 
     - app.status.operationState.phase in ['Succeeded', 'Running', 'Error', 'Failed']
     - app.metadata.annotations["something"] == "bar"
     - context.something == "baz"
```
