### ISSUE TITLE
Application set templating fails with arrays (Helm valueFiles)

### ISSUE THREAD

**Issue by sysarch-repo** [argoproj/argo-cd#9583]
Checklist:

* [ x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `argocd version`.

**Describe the bug**
Application set with Git file generator consuming a config JSON file that includes a parameter (valueFiles) with value being an array of strings cannot be applied using kubectl

**To Reproduce**
config.json:
```
{
  "releaseName": "nf1",
  "namespace": "ns1",
  "syncWave": "6",
  "valueFiles": [ "nf1-values.yaml", "nf1-config.yaml" ]
}
```
nf.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nf
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/<org>/cd
      revision: HEAD
      files:
      - path: "*/*/config.json"
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: '{{namespace}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: sysarch
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        helm:
          releaseName: '{{releaseName}}'
          valueFiles: '{{valueFiles}}'   <---- OPTION A
          valueFiles: {{valueFiles}}     <---- OPTION B
        path: '{{path}}'
        repoURL: https://github.com/<org>/<repo>
        targetRevision: HEAD
      destination:
        namespace: '{{namespace}}'
        name: '{{path[0]}}-cluster'
```
OPTION A:
```
error: error validating "nf.yaml": error validating data: ValidationError(ApplicationSet.spec.template.spec.source.helm.valueFiles): invalid type for io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.source.helm.valueFiles: got "string", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false
```
OPTION B:
`error: error parsing nf.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"valueFiles":interface {}(nil)}`

**Expected behavior**
Templating to work with arrays of string to support templating of Helm valueFiles defined as array of strings in the CRD

**Screenshots**

**Version**

```shell
argocd: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T13:06:25Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.4+ac8b7df
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment]
ApplicationSet does not currently support templating non-string fields (like arrays). There's been some work to add it, but nothing has made it across the finish line yet.

**Comment by sysarch-repo** [comment]
Thanks for the prompt reply. I am closing the ticket and will proceed with the static provisioning of the valueFiles.:
```
      source:
        helm:
          releaseName: '{{releaseName}}'
          valueFiles:
          - '{{path.basename}}-values.yaml'
          - '{{path.basename}}-config.yaml'
```

**Comment by barthy1** [comment]
Same problem. Are there any workaround?

**Comment by sysarch-repo** [comment]
@aarontavio , @barthy1 
As the helm task provides for a stringArray used as a value into the -f parameter, I have successfully tried out the following setup:

Application set (note, how the valuesFile is set):
```
      source:
        helm:
          releaseName: '{{releaseName}}'
          valueFiles:
          - '{{valueFiles}}'
        path: '{{path}}'
        repoURL: https://github.com/sysarch-repo/cd
        targetRevision: HEAD
```
 
The GIT file (JSON):
```
{
  "releaseName": "rel1",
  "namespace": "ns1",
  "syncWave": "6",
  "valueFiles": "values1.yaml,values2.yaml,values3.yaml,value4.yaml"
}
```

With this, you can define multiple values files to be used.
The applicationSet CR, the application CR and Argo CD seem to deal with this setup correctly, but just try and let me know.

@crenshaw-dev 
Could you pls confirm that this is a valid approach rather than exploiting a gap in ArgoCD?

**Comment by lsoica** [comment]
Just curious, is this still on the table or was it abandoned for another approach?

**Comment by bruceoutdoors** [comment]
Just wanna chime in to bump this up again. I'm also curious how this would be done if it does get implemented. In its current state, ApplicationSet parameters can only output strings. Although there's [go template support](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/), control keywords across fields is not supported - which would have made this easy.

**Comment by crenshaw-dev** [comment]
I plan to get some general fix for this issue into 2.9. I'm not exactly sure what form that fix will take yet.

**Comment by jessebot** [comment]
@crenshaw-dev Thanks for all the work you for the Argo project ❤️ I know you're really busy, but could you let us know if ApplicationSets work with multiple sources for helm now?

> I plan to get some general fix for this issue into 2.9. I'm not exactly sure what form that fix will take yet.

Also, just to clarify, when you said `2.9`, did you mean to type `2.7.9` or `2.8`?

**Comment by crenshaw-dev** [comment]
@jessebot I wish. :-) It's gonna be 2.9.0-rc1. @speedfl and I need to brainstorm some more to make sure we have the right design for more extensive templating support. We're hoping to hit a nice balance between solving the known use cases and avoiding full build-your-own-yaml type support, which is unnecessarily finicky, given that we have a known CR structure.

**Comment by jessebot** [comment]
Thanks for your response!

I was hoping the fix would follow the same beta spec as the app does for [multiple sources](https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/). I might be on the wrong issue though. There's a lot of overlapping search terms here :)

**Comment by innokgoldberg** [comment]
Hello. Is there any updates with this issue in the current/recent releases? Thank you.

**Comment by speedfl** [comment]
Hello this is currently implemented here https://github.com/argoproj/argo-cd/issues/9583
I just need to rebase and make it available for next release :)

**Comment by innokgoldberg** [comment]
> Hello this is currently implemented here #9583 I just need to rebase and make it available for next release :)

Good news!, thanks a lot. Can You provide a link to code or some docs to better understanding how to work with new functional of appset templating? (the link You provided goes to this page).

**Comment by speedfl** [comment]
Hello.
Wrong copy past 😅
https://github.com/argoproj/argo-cd/pull/14893

**Comment by jessebot** [comment]
> Hello. Wrong copy past 😅 #14893

@speedfl would this accommodate using a [`valuesObject`](https://argo-cd.readthedocs.io/en/latest/user-guide/helm/#values)?

**Comment by speedfl** [comment]
@jessebot you can also use [multi-sources](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/)

**Comment by jessebot** [comment]
Thank you for your reply! Does that still let you use templating in the values file? I will test this out!

**Comment by speedfl** [comment]
With same number of value files you can use the simple string templating:

```yaml
spec:
  source:
        repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: 5.51.2
        helm:
          releaseName: argo-cd
          valueFiles:
            - values.{{ ternary "default" "custom" .useCustom }}.yaml # Renders values.custom.yaml if generator returns .useCustom=true
            - {{ ternary "values.default.yaml" .overrideValueFile  .overrideValueFile }} # Renders values.mycustomvaluefile.yaml if generators returns .overrideValueFile=values.mycustomvaluefile.yaml
```

However if you need to add extra value files based on a variable then you have to wait for my MR on the patchTemplate.
