### ISSUE TITLE
v2.4.0-rc5 plz. update documentation about repo-creds (ssh rsa keys can no longer be used to access git repo)

### ISSUE THREAD

**Issue by ohauer** [argoproj/argo-cd#9598]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

argocd-2.4.0-rc5 no longer able to use ssh rsa keys to access git repos
Perhaps also note this in the 2.3 to 2.4 upgrade guide and the braking changes blog

within the update of the base image to ubuntu 22.04 LTS rsa keys can no longer be used to pull repos

create a ssh rsa repo-cred to access git repos

- ssh-keygen -t rsa -C argo-git-ssh
- give argocd read only access to the git repo via the generated ssh key
- create argocd repo-creds with git ssh url and id_rsa [1]
- update from argocd-v2.4.0-rc4 to rc5
-> repo no longer accessible 

[1]
```yaml
apiVersion: v1
type: Opaque
data:
  sshPrivateKey: ....
  url: ....
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: argocd-ssh-git-creds
  namespace: argocd
```

**Version**
```shell
argocd: v2.4.0-rc5+b84dd8b
  BuildDate: 2022-06-06T19:39:46Z
  GitCommit: b84dd8bbfab22426aaba4a509e0a5072724e4ff2
  GitTreeState: clean
  GoVersion: go1.18.2
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0-rc5+b84dd8b
  BuildDate: 2022-06-06T19:15:07Z
  GitCommit: b84dd8bbfab22426aaba4a509e0a5072724e4ff2
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```
