### ISSUE TITLE
argocd kustomize github ssh key

### ISSUE THREAD

**Issue by vvatlin** [argoproj/argo-cd#9631]
Hello. 

I don't know how to use GitHub public repo with argocd and kustomize. 

Here is an example:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongodb

resources:
# mongodb community operator
- github.com/mongodb/mongodb-kubernetes-operator/config/crd?ref=v0.7.3
- github.com/mongodb/mongodb-kubernetes-operator/config/rbac?ref=v0.7.3
- github.com/mongodb/mongodb-kubernetes-operator/config/manager?ref=v0.7.3
```

When I use just kustomize on my laptop - everything is ok, because I have ssh private key. 

But argocd failed with the error:
```
rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build .mongodb/overlays/test` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from 'github.com/mongodb/mongodb-kubernetes-operator/config/crd?ref=v0.7.3': evalsymlink failure on '.mongodb/overlays/test/github.com/mongodb/mongodb-kubernetes-operator/config/crd?ref=v0.7.3' : lstat .mongodb/overlays/test/github.com: no such file or directory': git cmd = '/usr/bin/git submodule update --init --recursive': exit status 1
```
I've tried to create Secrets for repo with url
```
  url: github.com/mongodb/mongodb-kubernetes-operator
  url: https://github.com/mongodb/mongodb-kubernetes-operator
  url: git@github.com:mongodb/mongodb-kubernetes-operator
```
and my private key 

Like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-kubernetes-operator1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/mongodb/mongodb-kubernetes-operator
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
```
But It didn't help. 

How can I fix this ?
