### ISSUE TITLE
server.config.rbacConfig should be map but expects string

### ISSUE THREAD

**Issue by jasperjonker** [argoproj/argo-cd#9658]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When I install Argo-CD using Helm I encounter the following issue when my  `values.yml` is:
```yaml
server:
  config:
    url: https://argocd.xxx.com
    rbacConfig:
      policy.default: role:admin
```

I get the following error:
```sh
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ConfigMap.data.rbacConfig): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"
```

When I use a string, as below, the values get added to the configmap `argocd-cm`, not to the correct `argocd-rbac-cm`.
```yaml
server:
  config:
    url: https://argocd.xxx.com
    rbacConfig: |
      policy.default: role:admin
```

**To Reproduce**
```sh
helm upgrade --install argocd argo/argo-cd -f values.yml -n argocd
```

**Expected behavior**
The values be added to added to the `argocd-rbac-cm` configmap

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:44:14Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
```
