### ISSUE TITLE
problem: ingress health check always be processing

### ISSUE THREAD

**Issue by k8sedu** [argoproj/argo-cd#968]
when i use traefik as ingress controller, it whill not update status.loadbalancer field, so as to argo-cd, the ingress object will be processing.See https://github.com/containous/traefik/issues/3377, they will fix it.
can we change the method for ingress health check, or expose it as a config

**Comment by k8sedu** [comment]
when use traefik as ingress controller, field u check is as below:
```
  "status": {
    "loadBalancer": {}
  }
```

**Comment by alexmt** [comment]
Custom health checks are not yet supported but we plan to work on it in next release. https://github.com/argoproj/argo-cd/issues/911

**Comment by k8sedu** [comment]
> but
ty. could u add one config that it can be skipped since that different ingress controllers make different behaviors

**Comment by jessesuen** [comment]
@k8sedu according to https://github.com/containous/traefik/issues/3377, it seems the v1.7.X of Traefik (which is already released), supports this.

Since the current version of Traefik has the desired behavior, I don't see the benefit of adding this, especially since the custom health assessment feature would immediately obsolete the config setting we add.

**Comment by jessesuen** [comment]
For the record, Heptio's Contour ingress controller suffers the same problem:
https://github.com/heptio/contour/issues/403

**Comment by jessesuen** [comment]
@k8sedu this appears to be an option that needs to configured. See:

https://docs.traefik.io/configuration/backends/kubernetes/

I think you need to use `publishedService` field:

```
# Enable IngressEndpoint configuration.
# This will allow Traefik to update the status section of ingress objects, if desired.
#
# Optional
#
# [kubernetes.ingressEndpoint]
#
# At least one must be configured.
# `publishedservice` will override the `hostname` and `ip` settings if configured.
#
# hostname = "localhost"
# ip = "127.0.0.1"
# publishedService = "namespace/servicename"
```

**Comment by ermazi** [comment]
it worked.but there are some wrong with traefik doc about this.:D
official config omitting rbac update~

step1. add config
```toml
    [kubernetes]
      [kubernetes.ingressEndpoint]
        hostname = "traefik"
```
step2. update clusterrole
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - update
```

**Comment by enys** [comment]
for anyone arriving here, the link is now : https://doc.traefik.io/traefik/providers/kubernetes-ingress/#publishedservice

**Comment by 0dragosh** [comment]
If anyone encounters this with Traefik ingress controller deployed via Helm, here's the `values.yaml` to fix it, at least for `v10.6.0`:

```yaml
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
```
