### ISSUE TITLE
ArgoCD 2.4.0 breaks CMP environment variable rendering in ArgoCD application

### ISSUE THREAD

**Issue by CCOLLOT** [argoproj/argo-cd#9688]
**Describe the bug**

After installing ArgoCD 2.4.0, CMP  is not properly rendering env variables from ArgoCD Application.

**To Reproduce**
I use this CMP plugin to post-render kustomize the helm chart

```yaml
data:
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template $HELM_OPTIONS . --include-crds > all.yaml && kustomize build"]
```

Then I use this plugin in applications like this:
```yaml
  source:
    path: path/to/kustomized-helm-config
    repoURL: git@git.domain.io:my/repo.git
    targetRevision: master
    plugin:
      name: kustomized-helm
      env:
        - name: HELM_OPTIONS
          value:  "--release-name foo --namespace bar"
```
The above application will render kubernetes resources with a proper release-name set to `foo` in argocd version 2.3.4
After installing version 2.4.0, the release name becomes `release-name` so resources are called like this : `release-name-my-deployment` instead of `foo-my-deployment`. Downgrading back to 2.3.4 solves the issue.

Hardcoding the release name in the plugin "solves" the issue. So the following will properly render a release name set to `foo`
```yaml
data:
  configManagementPlugins: |
    - name: kustomized-helm-hardcoded
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template --release-name foo --namespace bar . --include-crds > all.yaml && kustomize build"]
```

**Expected behavior**
I expect the plugin to render environment variables properly when using  `helm template $HELM_OPTIONS . --include-crds > all.yaml && kustomize build` so that the release-name stays `foo` in the above example just as it did in the 2.3.4 version of ArgoCD

I have tested this command locally and it works perfectly with Helm version `3.9.0`

Has anyone encountered the same issue? Is there anything in version 2.4.0 which could lead to such a behavior?

Thanks :)

**Comment by crenshaw-dev** [comment]
@CCOLLOT a security enhancement in 2.4 added prefixes to all user-supplied env vars before sending them to the plugin.  https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/#update-plugins-to-use-newly-prefixed-environment-variables

Your updated config would look like this:

```yaml
data:
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template $ARGOCD_ENV_HELM_OPTIONS . --include-crds > all.yaml && kustomize build"]
```
