### ISSUE TITLE
ClusterRole not permitted in project iloveu

### ISSUE THREAD

**Issue by k8sedu** [argoproj/argo-cd#970]
i have defined `iloveu` project with source A and destination k8s apiserver with namespace kube-system. and then when i deploy some app containing ClusterRole or ClusterRoleBinding those cluster-level resources, error ocurred.
```
ClusterRole is  not permitted in project iloveu
```
is that right?

if so, when i use cluster level object, i can only use project without namespace limitation?

**Comment by alexmt** [comment]
Manually created projects by default don't allow deploying cluster-wide resources. You might enable resources using UI or CLI: ```argocd proj  allow-cluster-resource iloveu "*" "*"``` . Please find more information at https://argoproj.github.io/docs/argo-cd/docs/projects.html

**Comment by k8sedu** [comment]
ty

**Comment by igaskin** [comment]
For others that may end up here.  You can also make this modification to your `AppProject` spec

```
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
```

**Comment by Adiii717** [comment]
The above fixed worked for me, encounter this issue today after upgrading from ArgoCD from `argocd-server: v1.7.6+b04c25e` to `argocd-server: v2.1.0+d0b2d55`
It seems hard to update each and every pipeline, is it something because of the new version?

Is there a way to set `AppProject spec` globally? 
```
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
```

**Comment by osoriano** [comment]
`clusterResourceWhitelist` now supports a `name` field
```
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    name: 'team1-*'
```
https://github.com/argoproj/argo-cd/pull/24674 ([doc](https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#restrict-cluster-scoped-resources-by-name))
