### ISSUE TITLE
Empty initiatedBy field when Rolling Back an Application

### ISSUE THREAD

**Issue by mvgmb** [argoproj/argo-cd#9712]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using Argo CD's Rollback functionality, the `initiatedBy` field is empty. It should contain the Username.

**To Reproduce**

In any Argo CD Application, syncing changes to your application should result in the following `operationState` informations:

```yaml
# application.yaml
...
status:
  operationState:
    finishedAt: "2022-06-17T18:19:58Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: mario.bezerra@example.com
      retry: {}
      sync:
        revision: 1e65e80b456d369aa7fdf8d48d3e5689b4fe9a83
        syncStrategy:
          hook: {}
...
```

When rolling back through Argo CD, the `initiatedBy` field is empty, even though a user is responsible for rolling back. 

```yaml
# application.yaml
...
status:
  operationState:
    finishedAt: "2022-06-17T18:23:08Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy: {}
      retry: {}
      sync:
        revision: 4e288d8adece219baf58488ffa1cf94402b1530d
        source:
          path: ./k8s/overlays/production
          repoURL: https://github.com/example/example.git
          targetRevision: HEAD
        syncStrategy:
          apply: {}
...
```

**Expected behavior**

The `status.operationState.operation.initiatedBy` field should not be empty, it should contain the username responsible for the rollback:
```yaml
# application.yaml
...
status:
  operationState:
    operation:
      initiatedBy:
        username: mario.bezerra@example.com
```

**Version**

```shell
argocd: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T11:41:37Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.10
  Compiler: gc
  Platform: linux/amd64
```
