### ISSUE TITLE
Weird behavior when running `Sync` hook, with "wave" setting, and deployments failed

### ISSUE THREAD

**Issue by ctron** [argoproj/argo-cd#9721]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I ran into the issue that ArgoCD reported the sync has failed, but did not show any causes.

**To Reproduce**

It turns out that I had a `Sync` hook, which also had a "helm weight" setting applied:

```yaml
kind: Job
apiVersion: batch/v1
metadata:
  name: post-install-keycloak
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    helm.sh/hook-weight: "5"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
```

And, some of the deployment had been failing.

I think what happens then is that the "wave 0" tries to complete, but cannot (due to the failing deployments) and so it didn't start the "wave 5" job. It was a bit weird that helm overrides the argocd setting, odd but not a bug I guess.

What I however do consider a bug is that ArgoCD doesn't communicate this to the user. I just fails, but doesn't give you any cause.

**Expected behavior**

I would expect that argocd tells me that the synchronization has failed due do failed deployments.

**Screenshots**

**Version**

```shell
argocd: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T13:06:25Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.9
  Compiler: gc
  Platform: linux/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.3.4+unknown
  BuildDate: 2022-05-27T01:53:39Z
  GitTreeState: clean
  GoVersion: go1.17.7
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: v4.4.1 1970-01-01T00:00:00Z
  Helm Version: v3.8.0+g7ddadb4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0

```

**Logs**

```
time="2022-06-20T10:12:14Z" level=info msg="Updating resource result, status: '' -> '', phase 'Running' -> 'Succeeded', message 'job.batch/migrate-database created' -> 'job.batch/migrate-databa
se created'" application=drogue-dev kind=Job name=migrate-database namespace=drogue-dev phase=Sync syncId=00066-zExBF
time="2022-06-20T10:12:14Z" level=info msg="Updating operation state. phase: Running -> Failed, message: 'waiting for completion of hook batch/Job/migrate-database' -> 'one or more synchronizat
ion tasks completed unsuccessfully'" application=drogue-dev syncId=00066-zExBF
time="2022-06-20T10:12:14Z" level=info msg="sync/terminate complete" application=drogue-dev duration=504.497177ms syncId=00066-zExBF
time="2022-06-20T10:12:14Z" level=info msg="updated 'drogue-dev' operation (phase: Failed)"
time="2022-06-20T10:12:14Z" level=info msg="Sync operation to c7b1e3368f3dc02ccb85dc53bb369ea8cbf8a803 failed: one or more synchronization tasks completed unsuccessfully" application=drogue-dev dest-namespace=drogue-dev dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning

```

**Comment by jessesuen** [comment]
I believe we should show this. Do you have a screenshot of the panel after clicking under `LAST SYNC RESULT` for a failed sync that fails to show it. e.g.:

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/12677113/176660718-dc8934af-de9f-4680-bcc6-c4427abf1207.png">

**Comment by ctron** [comment]
Right now, unfortunately not. I will post one when I run into this again.

**Comment by ctron** [comment]
Now I got one, it wasn't easy making a screenshot. I hope that works for you:

![Screen Shot 2022-07-04 at 10 22 13](https://user-images.githubusercontent.com/202474/177113794-d26d6c31-1363-4833-b6e7-18c169fe37bb.png)

**Comment by ctron** [comment]
Just running into this issue again today.

**Comment by mmazur-oloy** [comment]
I can see similar behavior of ArgoCD. Today I was synchronizing over 50 applications in batches (5 applications at once). 25 of them has failed with message "one or more synchronization tasks completed unsuccessfully", but actually everything has synchronized correctly. Basically it seems like for some reason ArgoCD is showing false-positive `SyncFailed` status. 

Application controller logs in Debug mode doesn't show anything more than the same message: `one or more synchronization tasks completed unsuccessfully`

Does anyone have any idea how to solve this?

**Comment by Demonsthere** [comment]
Run into the same issue. We deploy a App of Apps pattern with several waves. Basically something happens in sync wave 0 which prohibits Argo to continue with further waves. I have been able to trace it to to two apps:
```yaml
      - group: argoproj.io
        hookPhase: Failed
        kind: Application
        message: application.argoproj.io/cert-manager created
        name: cert-manager
        namespace: gitops
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      - group: argoproj.io
        hookPhase: Failed
        kind: Application
        message: application.argoproj.io/kube-prometheus-stack created
        name: kube-prometheus-stack
        namespace: gitops
        status: Synced
        syncPhase: Sync
        version: v1alpha1
```

Or rather their hooks. Looks like when a hook fails (even when it is retried and eventually successful) this will block argocd from continuing the sync. Interesting enough, this doesn't seem to matter when all objects are in the same wave, but the moment you have 2 waves, such a situation in wave n will block n+1.
As @ctron said the issue here is lack of transparency, what failed, especially as App1 fails because of a hook in App2. 
For us in the dashboard it looks like App 1 is failed with no visible reason as to why, and App 2 is synced and healthy, even though it is the culprit
