### ISSUE TITLE
ApplicationSet Cluster Generator: nameNormalized is not provided for local cluster

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-cd#9727]
# Summary

I'm trying to create a very simple application set that will generate an application for every cluster, including the local cluster. The problem is that the names of my remote clusters have slashes so I need to use `nameNormalized`. But then it always fails to generate the application for the local cluster. The logs show:
```
\"{{nameNormalized}}-my-app\" is invalid
```

Below is the `ApplicationSet`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
spec:
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: '{{nameNormalized}}-my-app'
    spec:
      project: default
      source:
        repoURL: ''
        targetRevision: HEAD
        path: .
      destination:
        server: '{{server}}'
        namespace: default
```

# Motivation

I would really rather avoid having to do what is suggested in https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#deploying-to-the-local-cluster, my case is very simple - I don't need to distinguish clusters from one another, I want the generator to work for local and remote clusters.

# Proposal

I had a look at the code and saw that `nameNormalized` is [provided for remote clusters](https://github.com/argoproj/argo-cd/blob/952230eaf86e580b5a7f88fcf61ac50d942651f0/applicationset/generators/cluster.go#L123) but [not for the local cluster](https://github.com/argoproj/applicationset/blob/c8fb714a35fc66805fdb184dd5e6455637d5a8b4/pkg/generators/cluster.go#L106). In my case I'd just want `nameNormalized` to equal `name` for the local cluster.
