### ISSUE TITLE
Unable to Authenticate Kustomize Plugin via argocd-k8s-auth

### ISSUE THREAD

**Issue by mvgmb** [argoproj/argo-cd#9730]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

## Describe the bug

Since "**refactor: replace aws CLI with argocd-k8s-auth**" (https://github.com/argoproj/argo-cd/pull/8032), when a Kustomize plugin needs to authenticate with a cluster, the K8s SDK tries to use the `argocd-git-ask-pass` binary instead of `argocd-k8s-auth`, causing it to fail:

<img width="562" alt="Screen Shot 2022-06-20 at 4 36 11 PM" src="https://user-images.githubusercontent.com/23530832/174804039-a73cd894-554d-44ef-aaf1-8ea149b573bc.png">

## To Reproduce

Use a Kustomize plugin to authenticate to a cluster.

## Workaround

After debugging the problem, I found that the environment variable `ARGOCD_BINARY_NAME` was set to `argocd-git-ask-pass`:

https://github.com/argoproj/argo-cd/blob/764b7a627d952ccc9b7724560eb4cddf640d0ade/util/git/creds.go#L72

After setting it to empty in my kubeconfig, the Kustomize plugin was successfully able to authenticate:

```yaml
users:
- name: example-cluster
   user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - aws
      - --cluster-name
      - example-cluster
      command: argocd-k8s-auth
      env:
      - name: ARGOCD_BINARY_NAME
        value: ""
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

## Logs

```shell
rpc error: code = Unknown desc = `kustomize build .kubernetes-clusters/overlays/production --enable-alpha-plugins` failed exit status 1: 2022/06/21 12:32:49 /tmp/kust-plugin-config-1737348185: Get "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxx.xxxxxxx.eks.amazonaws.com/api?timeout=32s": getting credentials: exec: executable aws not found It looks like you are trying to use a client-go credential plugin that is not installed. To learn more about this feature, consult the documentation available at: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins panic: /tmp/kust-plugin-config-1737348185: Get "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxx.xxxxxxx.eks.amazonaws.com/api?timeout=32s": getting credentials: exec: executable aws not found It looks like you are trying to use a client-go credential plugin that is not installed. To learn more about this feature, consult the documentation available at: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins goroutine 1 [running]: log.Panic(0xc00039dcd8, 0x3, 0x3) /opt/hostedtoolcache/go/1.16.15/x64/src/log/log.go:354 +0xae main.main() github.com/inloco/iac-kustomize-plugins/clusterroles/main.go:81 +0x7e8 Error: failure in plugin configured via /tmp/kust-plugin-config-1737348185; exit status 2: exit status 2
```

## Version

```shell
argocd@argocd-repo-server-xxxxxxxxxx-xxxxxx:~$ argocd version
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
```
