### ISSUE TITLE
Wrong detect drift based on resources field order AFTER applying

### ISSUE THREAD

**Issue by defaultbr** [argoproj/argo-cd#9759]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When applying resources (memory and cpu hpa), argocd keep detecting a drift compared to what is really applied

resources in generated manifests (from helm template)

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: testapplication-k8s
  namespace: testnamespace
  labels:
    helm.sh/chart: api-default-5
    app.kubernetes.io/name: testapplication-k8s
    app.kubernetes.io/instance: testapplication-k8s
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testapplication-k8s
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu         <----------------- this is the first
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory  <---------------------- this is the second
        targetAverageUtilization: 70
```

Look at the order, cpu is first and memory second position.

After argocd applies manifest to the cluster, it keep saying that there is a out of sync and enter in a loop

![image](https://user-images.githubusercontent.com/5432351/175086437-547e39bc-e2ad-4aa9-a214-ab3a9ff6754f.png)

when we search for the diff, it's just a order error 

![image](https://user-images.githubusercontent.com/5432351/175082310-35a8f18b-0da4-458d-960f-7b7f38bc2a57.png)

so after changing the order at the helm chart hpa yaml

from

```
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
```

TO

```
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
```

*CPU BLOCK IS THE SECOND AND MEMORY BLOCK IS THE FIRST NOW*

After reapplying the patched hpa config from helm chart, argocd stopped this weird behavior and now works ok  

**To Reproduce**

Just apply the generated hpa.yaml from `helm create new-chart` and enable autoscale at values.yaml

```
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
```

(I'm using helm template to generate a manifest and push it to a central manifests repository)

**Expected behavior**

To not complain about the field order, don't know if argo is ordering it or kubernetes order after applied, but argo complain about this 

**Screenshots**

added in the issue body

**Version**

```shell

argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T01:46:59Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0+91aefab
```
