### ISSUE TITLE
Failure to build dependency's from azure using OCI

### ISSUE THREAD

**Issue by mreinhartGopuff** [argoproj/argo-cd#9764]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When trying to add a chart as a dependency using oci, argo fails to authorize when pulling the dependency chart from azure container registry. The repo properly authenticates against images but fails when running helm dependency build. When running `argo app sync <app-name>` this error message is returned:

`time="2022-06-22T20:26:15Z" level=fatal msg="rpc error: code = InvalidArgument desc = application spec for <app-name> is invalid: InvalidSpecError: Unable to generate manifests in charts/<chart-name>: rpc error: code = Unknown desc = helm dependency build failed exit status 1: Error: could not download oci://<redacted>.azurecr.io/charts/<chart-name>: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized"`

**To Reproduce**
1.)  Push up a chart to ACR using helm command: `helm chart push`
This can be a basic helm create chart. No dependency's required. This chart will be used as a dependency for another chart.

2.) Create a repo that has another chart. This chart should have the chart pushed up to ACR as a dependency :
```yaml
apiVersion: v2
name: <name>
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: <chart-name>
    version: 0.0.1
    repository: "oci://<redacted>.azurecr.io/charts"
    condition: <name>.enabled
```

2.) Create an argo application targeting the chart with a dependency. Make sure to add the helm repo to argo as shown in the image below (with oci enabled).

3.)
**Expected behavior**
The chart is deployed successfully, and able to pull from azure container registry. 

**Screenshots**

![argo-repo](https://user-images.githubusercontent.com/79102675/175131309-74c6f621-63a2-4c07-b89f-fec49505a17b.png)

**Version**

```shell
argocd: v2.4.0+91aefab.dirty
  BuildDate: 2022-06-13T11:57:16Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: dirty
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
```

**Comment by mreinhartGopuff** [comment]
This was fixed by pinning the argo helm version to 3.9 
https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#using-initcontainers
```yaml

repoServer:
    initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
          - wget -qO- https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz | tar -xvzf - &&
            mv linux-amd64/helm /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    volumeMounts:
    - mountPath: /usr/local/bin/helm
      name: custom-tools
      subPath: helm
    volumes:
      - name: custom-tools
        emptyDir: {}
```
