### ISSUE TITLE
CMP bash -c command parameters not supported

### ISSUE THREAD

**Issue by rcarre** [argoproj/argo-cd#9775]
**Describe the bug**
Here is the manifest file to deployed via ArgoCD application:
```
---
apiVersion: v1
stringData:
  client-id: my_client_id
  client-secret: my_client_secret
  cookie-secret: my_cookie_secret
kind: Secret
metadata:
  annotations:
    argocd-target_appname: ${ARGOCD_APP_NAME}
  name: my-proxy-secret
```

Here is the extract from argocd-cm configmap about my plugin which trigger envsubst tool:
```shell
    - name: argocd-envsubst-plugin
      generate:
         command: ["bash", "-c"]
         args: ['envsubst $0 < deployment.yaml' '${ARGOCD_APP_NAME}']
```
**Error:** container argocd-repo-server-xxxxx is not able to parse the args command line. Here is the error message displayed in ArgoCD GUI coming from argocd-application-controller-xxxx container:
```shell
time="2022-06-23T12:51:33Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-06-23T12:51:33Z\",\"message\":\"error converting YAML to JSON: yaml: line 3: did not find expected ',' or ']'\",\"type\":\"ComparisonError\"}]}}" application=orange-connect
```

**Expected behavior**
As detailed in here enclosed bash man page, bash -c does support command string argument with extra arguments

```
bash -c        If the -c option is present, then commands are read from the first non-option argument command_string.  If there are argu‐
                 ments after the command_string, the first argument is assigned to $0 and any remaining arguments are assigned to the posi‐
                 tional parameters.  The assignment to $0 sets the name of the shell, which is used in warning and error messages.
```

When I run this command line from my Ubuntu laptop: `bash -c 'envsubst $0 < deployment.yaml' '${ARGOCD_APP_NAME}'`, I got the expected output:
```
---
apiVersion: v1
stringData:
  client-id: my_client_id
  client-secret: my_client_secret
  cookie-secret: my_cookie_secret
kind: Secret
metadata:
  annotations:
    argocd-target_appname: orange-connect
  name: my-proxy-secret
```

**Screenshots**

**Version**

```shell
{
    "Version": "v2.2.5+8f981cc",
    "BuildDate": "2022-02-05T01:33:25Z",
    "GitCommit": "8f981ccfcf942a9eb00bc466649f8499ba0455f5",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.11",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}
```

**Workaround**
I tried another syntax for argocd-cm configmap. But this one cannot be parsed by container argocd-repo-server since I do not find the way to escape the single quotes embracing ${ARGOCD_APP_NAME}
```shell
    - name: argocd-envsubst-plugin
      generate:
         command: ["bash", "-c"]
         args: ['envsubst '${ARGOCD_APP_NAME}' < deployment.yaml' ]
```

**Comment by rcarre** [comment]
> @rcarre might this work?
> 
> ```yaml
>     - name: argocd-envsubst-plugin
>       generate:
>          command: ["bash", "-c"]
>          args: ["envsubst '${ARGOCD_APP_NAME}' < deployment.yaml"]
> ```

Thanks for your reply. Even not working from my laptop:

```
bash -c "envsubst '${ARGOCD_APP_NAME}' < deployment.yaml"
---
apiVersion: v1
stringData:
  client-id: my_client_id
  client-secret: my_client_secret
  cookie-secret: my_cookie_secret
kind: Secret
metadata:
  annotations:
    argocd-target_appname: $ARGOCD_APP_NAME
  name: my-proxy-secret
```

**Comment by crenshaw-dev** [comment]
When running on your laptop, the environment variable substitution is happening too soon. The single-quotes, when embedded in double-quotes, do not protect your environment variable from substitution. Consider this demonstration:

```
$ echo "envsubst '$ARGOCD_APP_NAME' < /tmp/deployment.yaml"
envsubst 'test' < /tmp/deployment.yaml
```

So `envsubst` is receiving the wrong argument.

But there is a local test which should work:

```
echo 'envsubst '"'"'$ARGOCD_APP_NAME'"'"' < /tmp/deployment.yaml'
envsubst '$ARGOCD_APP_NAME' < /tmp/deployment.yaml
```

You can think of the `'"'"'` sequence as a gnarly escape for a single-quote character. (What's actually happening is you are concatenating a single-quoted string with a double-quoted string containing a single quote with another single-quoted string and so on.)

So, running locally, this would be the appropriate test:

```bash
bash -c 'envsubst '"'"'$ARGOCD_APP_NAME'"'"' < /tmp/deployment.yaml'
```

In the plugin YAML, the escaping is unnecessary. Since Argo CD is interpreting the YAML (not a shell), `${ARGOCD_APP_NAME}` will not be prematurely evaluated. `envsubst '${ARGOCD_APP_NAME}' < deployment.yaml` will be passed as a literal string to `bash -c`, and then BASH will _not_ evaluate `${ARGOCD_APP_NAME}` before passing it to `envsubst`, because the variable is protected by single-quotes.

**Comment by rcarre** [comment]
Thanks for you crystal clear last reply. Just tested in ArgoCD: no more parsing error but still unsuccessful. What would be the test to be performed to ensure ${ARGOCD_APP_NAME} is defined ?

**kubectl describe cm argocd-cm**
```
Name:         argocd-cm
Namespace:    argocd
Labels:       app.kubernetes.io/component=server
              app.kubernetes.io/instance=argocd
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=argocd-cm
              app.kubernetes.io/part-of=argocd
              helm.sh/chart=argo-cd-3.35.4
Annotations:  diod-gitlab-ci-branch: release
              diod-gitlab-ci-name: cluster-setup

Data
====
application.instanceLabelKey:
----
argocd.argoproj.io/instance
configManagementPlugins:
----
- name: argocd-envsubst-plugin
  generate:
     command: ["bash", "-c"]
     args: ["envsubst '${ARGOCD_APP_NAME}' < deployment.yaml"]
```


**Desired manifest**
```
apiVersion: v1
data:
  client-id: ++++++++
  client-secret: ++++++++
  cookie-secret: ++++++++
kind: Secret
metadata:
  annotations:
    argocd-target_appname: '${ARGOCD_APP_NAME}'
  labels:
    argocd.argoproj.io/instance: orange-connect
  name: my-proxy-secret
  namespace: oauth2
```
**LIve manifest**
```
apiVersion: v1
data:
  client-id: ++++++++
  client-secret: ++++++++
  cookie-secret: ++++++++
kind: Secret
metadata:
  annotations:
    argocd-target_appname: '${ARGOCD_APP_NAME}'
    kubectl.kubernetes.io/last-applied-configuration: >-
      {"apiVersion":"v1","data":{"client-id":"++++++++","client-secret":"++++++++","cookie-secret":"++++++++"},"kind":"Secret","metadata":{"annotations":{"argocd-target_appname":"${ARGOCD_APP_NAME}"},"labels":{"argocd.argoproj.io/instance":"orange-connect"},"name":"my-proxy-secret","namespace":"oauth2"}}
  creationTimestamp: '2022-06-23T13:04:08Z'
  labels:
    argocd.argoproj.io/instance: orange-connect
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:client-id': {}
          'f:client-secret': {}
          'f:cookie-secret': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:argocd-target_appname': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:argocd.argoproj.io/instance': {}
        'f:type': {}
      manager: argocd-application-controller
      operation: Update
      time: '2022-06-23T13:04:08Z'
  name: my-proxy-secret
  namespace: oauth2
  resourceVersion: '64100603'
  uid: 436eabb2-04b6-417d-8ce9-1d89c43cd72b
type: Opaque
```
