### ISSUE TITLE
notification service 'webhook' is not supported

### ISSUE THREAD

**Issue by SamuelRobotiq** [argoproj/argo-cd#9793]
**Describe the bug**
Following the notification webhook documentation (https://argocd-notifications.readthedocs.io/en/stable/services/webhook/)
does not work. The following error is logged in ``
```
level=error msg="Failed to notify recipient {webhook google-chat} defined in resource argocd/*******: notification service 'webhook' is not supported" resource=argocd/*******
```

**To Reproduce**

Have the `argocd-notifications-controller-cm` `ConfigMap` with the following:
```
data:
  service.webhook.google-chat:
    url: <YOUR URL>
    headers: 
    - name: Content-Type
      value: application/json
```

**Expected behavior**
No error in the log.
Webhook to work like described in documentation.

**Version**
```shell
v2.3.4+ac8b7df
```

Helm Chart version: `4.8.3`

**Logs**
```
level=error msg="Failed to notify recipient {webhook google-chat} defined in resource argocd/*******: notification service 'webhook' is not supported" resource=argocd/*******
```

**Comment by SamuelRobotiq** [comment]
@jessesuen Thx!

The problem come from the subscriptions configuration.
```
data:
  service.webhook.something: |
    url: MY_WEBHOOK_URL
  subscriptions: |
    - recipients:
-        - webhook:something
+       - something 
```

I find the documentation on argocd website misleading about this. Would be nice to specify to not set the `webhook:`.

**Comment by OpenGuidou** [comment]
It seems the configuration mentioned works for subscriptions in the configmap, but not when using the app annotation.

Using:
notifications.argoproj.io/subscribe.on-sync-succeeded.webhook: my-webhook

I'm still getting the "notification service 'webhook' is not supported"

Any workaround for that ? Or should it be fixed ?

**Comment by blakepettersson** [comment]
Closing since this has been resolved

**Comment by StianOvrevage** [comment]
For those who still stumble upon this issue. The documentation at https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/subscriptions/#default-subscriptions appears to be fixed:

> If you want to use webhook in subscriptions, you need to store the custom webhook name in the subscription's recipients field.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.<webhook-name>: |
    (snip)
  subscriptions: |
    - recipients:
      - <webhook-name>
      triggers:
      - on-sync-status-unknown
```
