### ISSUE TITLE
Initial sync of CRD + CRD instance installs resources into argocd namespace

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#981]
I installed prometheus-operator from helm chart. Somehow it ended up installing some CRDs into the argocd namespace:

```
$ argocd app get prometheus-operator | grep monitoring.coreos.com
apiextensions.k8s.io       CustomResourceDefinition  prometheus-operator  alertmanagers.monitoring.coreos.com                            OutOfSync  Healthy
apiextensions.k8s.io       CustomResourceDefinition  prometheus-operator  prometheuses.monitoring.coreos.com                             OutOfSync  Healthy
apiextensions.k8s.io       CustomResourceDefinition  prometheus-operator  prometheusrules.monitoring.coreos.com                          OutOfSync  Healthy
apiextensions.k8s.io       CustomResourceDefinition  prometheus-operator  servicemonitors.monitoring.coreos.com                          OutOfSync  Healthy
monitoring.coreos.com      Alertmanager              prometheus-operator  prometheus-operator-alertmanager                               OutOfSync  Missing
monitoring.coreos.com      Prometheus                prometheus-operator  prometheus-operator-prometheus                                 OutOfSync  Missing
monitoring.coreos.com      PrometheusRule            prometheus-operator  prometheus-operator                                            OutOfSync  Missing
monitoring.coreos.com      PrometheusRule            prometheus-operator  prometheus-operator-kube-etcd-rules                            OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-alertmanager                               OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-coredns                                    OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-apiserver                                  OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-kube-controller-manager                    OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-kube-etcd                                  OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-kube-scheduler                             OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-kube-state-metrics                         OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-kubelet                                    OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-node-exporter                              OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-operator                                   OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            prometheus-operator  prometheus-operator-prometheus                                 OutOfSync  Missing
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-kube-scheduler                             OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-operator                                   OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-kube-etcd                                  OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-kube-controller-manager                    OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-kube-state-metrics                         OutOfSync  Healthy
monitoring.coreos.com      PrometheusRule            argocd               prometheus-operator-kube-etcd-rules                            OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-prometheus                                 OutOfSync  Healthy
monitoring.coreos.com      Prometheus                argocd               prometheus-operator-prometheus                                 OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-node-exporter                              OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-coredns                                    OutOfSync  Healthy
monitoring.coreos.com      Alertmanager              argocd               prometheus-operator-alertmanager                               OutOfSync  Healthy
monitoring.coreos.com      PrometheusRule            argocd               prometheus-operator                                            OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-alertmanager                               OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-kubelet                                    OutOfSync  Healthy
monitoring.coreos.com      ServiceMonitor            argocd               prometheus-operator-apiserver                                  OutOfSync  Healthy
```

**Comment by jessesuen** [comment]
Here is what is produced by `helm template`:
```
# Source: prometheus-operator/templates/exporters/kube-controller-manager/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-kube-controller-manager
  labels:
    app: prometheus-operator-kube-controller-manager
    
    chart: prometheus-operator-1.5.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-operator-kube-controller-manager
      release: "prometheus-operator"
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

This is what is returned by `argocd app manifests prometheus-operator`, which is the same except for injected label `app.kubernetes.io/instance`:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-kube-controller-manager
    app.kubernetes.io/instance: prometheus-operator
    chart: prometheus-operator-1.5.0
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-kube-controller-manager
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: prometheus-operator-kube-controller-manager
      release: prometheus-operator
```
