### ISSUE TITLE
Add support for Azure Devops Webhook

### ISSUE THREAD

**Issue by mariusandersen** [argoproj/argo-cd#9824]
Trying to use the Azure Devops Webhook for git push event, we get error

Unknown webhook event

The code does not support webhooks from Azure Devops. https://github.com/argoproj/argo-cd/blob/b52476971425d396cfd63306d53193a3e9f54df6/util/webhook/webhook.go#L403

FYI, here is the Test hook that is being sent on a git.push event (no sensitive info):
```
Method: POST
URI: https://argocd.some.site/api/webhook
HTTP Version: 1.1
Headers:
{
  Content-Type: application/json; charset=utf-8
}
Content:
{
  "subscriptionId": "00000000-0000-0000-0000-000000000000",
  "notificationId": 37,
  "id": "03c164c2-8912-4d5e-8009-3707d5f83734",
  "eventType": "git.push",
  "publisherId": "tfs",
  "message": {
    "text": "Jamal Hartnett pushed updates to Fabrikam-Fiber-Git:master.",
    "html": "Jamal Hartnett pushed updates to Fabrikam-Fiber-Git:master.",
    "markdown": "Jamal Hartnett pushed updates to `Fabrikam-Fiber-Git`:`master`."
  },
  "detailedMessage": {
    "text": "Jamal Hartnett pushed a commit to Fabrikam-Fiber-Git:master.\n - Fixed bug in web.config file 33b55f7c",
    "html": "Jamal Hartnett pushed a commit to <a href=\"https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/\">Fabrikam-Fiber-Git</a>:<a href=\"https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/#version=GBmaster\">master</a>.\n<ul>\n<li>Fixed bug in web.config file <a href=\"https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/commit/33b55f7cb7e7e245323987634f960cf4a6e6bc74\">33b55f7c</a>\n</ul>",
    "markdown": "Jamal Hartnett pushed a commit to [Fabrikam-Fiber-Git](https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/):[master](https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/#version=GBmaster).\n* Fixed bug in web.config file [33b55f7c](https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/commit/33b55f7cb7e7e245323987634f960cf4a6e6bc74)"
  },
  "resource": {
    "commits": [
      {
        "commitId": "33b55f7cb7e7e245323987634f960cf4a6e6bc74",
        "author": {
          "name": "Jamal Hartnett",
          "email": "fabrikamfiber4@hotmail.com",
          "date": "2015-02-25T19:01:00Z"
        },
        "committer": {
          "name": "Jamal Hartnett",
          "email": "fabrikamfiber4@hotmail.com",
          "date": "2015-02-25T19:01:00Z"
        },
        "comment": "Fixed bug in web.config file",
        "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/commit/33b55f7cb7e7e245323987634f960cf4a6e6bc74"
      }
    ],
    "refUpdates": [
      {
        "name": "refs/heads/master",
        "oldObjectId": "aad331d8d3b131fa9ae03cf5e53965b51942618a",
        "newObjectId": "33b55f7cb7e7e245323987634f960cf4a6e6bc74"
      }
    ],
    "repository": {
      "id": "278d5cd2-584d-4b63-824a-2ba458937249",
      "name": "Fabrikam-Fiber-Git",
      "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/git/repositories/278d5cd2-584d-4b63-824a-2ba458937249",
      "project": {
        "id": "6ce954b1-ce1f-45d1-b94d-e6bf2464ba2c",
        "name": "Fabrikam-Fiber-Git",
        "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/projects/6ce954b1-ce1f-45d1-b94d-e6bf2464ba2c",
        "state": "wellFormed",
        "visibility": "unchanged",
        "lastUpdateTime": "0001-01-01T00:00:00"
      },
      "defaultBranch": "refs/heads/master",
      "remoteUrl": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git"
    },
    "pushedBy": {
      "displayName": "Jamal Hartnett",
      "id": "00067FFED5C7AF52@Live.com",
      "uniqueName": "fabrikamfiber4@hotmail.com"
    },
    "pushId": 14,
    "date": "2014-05-02T19:17:13.3309587Z",
    "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/git/repositories/278d5cd2-584d-4b63-824a-2ba458937249/pushes/14"
  },
  "resourceVersion": "1.0",
  "resourceContainers": {
    "collection": {
      "id": "c12d0eb8-e382-443b-9f9c-c52cba5014c2"
    },
    "account": {
      "id": "f844ec47-a9db-4511-8281-8b63f4eaf94e"
    },
    "project": {
      "id": "be9b3917-87e6-42a4-a549-2bc06a7a878f"
    }
  },
  "createdDate": "2022-06-29T11:32:27.006588Z"
}

```

**Comment by abhirampadala** [comment]
@jessesuen can i pick this one?

**Comment by jonathanirvin-ast** [comment]
Looks like a duplicate of #3937

**Comment by photosat-renovate** [comment]
It looks like ArgoCD expects an HTTP header "X-Vss-Activityid" with any arbitrary data for `git.push` events otherwise it will throw an "Unknown webhook event" error. It does not look like this is documented anywhere, and my instance of Azure DevOps does not add this header by default.

Even when the header is added to HTTP headers section in the webhook, it's completely ignored, maybe there is some backend parsing done by Azure to omit unknown headers?

To make it work I created a separate ingress for ArgoCD webhooks with ingress-nginx and added the header with `more_set_headers`. Then you can point the webhook to `argocd-azure-webhook.example.com`, example below:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-azure-webhook
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Vss-Activityid: push";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "argocd-azure-webhook.example.com"
    secretName: tls-secret
  rules:
  - host: argocd-azure-webhook.example.com
    http:
      paths:
      - path: "/api/webhook"
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
``` 

It would be beneficial to add some documentation to https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#azure-devops regarding this required header as I had to dig through the code to find it.

**Comment by lemker** [comment]
It looks like ArgoCD expects an HTTP header "X-Vss-Activityid" with any arbitrary data for `git.push` events otherwise it will throw an "Unknown webhook event" error. It does not look like this is documented anywhere, and my instance of Azure DevOps does not add this header by default.

Even when the header is added to HTTP headers section in the webhook, it's completely ignored, maybe there is some backend parsing done by Azure to omit unknown headers?

To make it work I created a separate ingress for ArgoCD webhooks with ingress-nginx and added the header with `more_set_input_headers`. Then you can point the webhook to `argocd-azure-webhook.example.com`, example below:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-azure-webhook
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Vss-Activityid: push";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "argocd-azure-webhook.example.com"
    secretName: tls-secret
  rules:
  - host: argocd-azure-webhook.example.com
    http:
      paths:
      - path: "/api/webhook"
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
``` 

It would be beneficial to add some documentation to https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#azure-devops regarding this required header as I had to dig through the code to find it.
