### ISSUE TITLE
Unable to add a supported helm repository with custom plugin (like helm-s3 or helm-gcs)

### ISSUE THREAD

**Issue by jmmclean** [argoproj/argo-cd#9840]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The documentation is a bit misleading since repository protocols, such as `s3://` or `gs://`, are not support and will error out

Doc reference - https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-plugins

**To Reproduce**

attempt to create a helm chart application that references a scheme having `s3://` or `gs://` after install ing the plugin per documentation above

**Expected behavior**

Repository is added and is able to be connected to

**DEBUG**
6902patch
```yaml
- op: add
  path: "/spec/template/spec/initContainers/-"
  value:
    name: install-helm-plugins
    image: alpine/helm:3.8.2
    volumeMounts:
      - mountPath: /helm
        name: helm
    env:
      - name: HELM_DATA_HOME
        value: /helm
      - name: HELM_CACHE_HOME
        value: /helm/cache
      - name: HELM_CONFIG_HOME
        value: /helm/config
    command: ["/bin/sh", "-c"]
    args:
      - apk --no-cache add curl bash;
        helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.11.0;
        chmod -R 777 $HELM_DATA_HOME;
- op: add
  path: "/spec/template/spec/volumes/-"
  value:
    name: helm
    emptyDir: {}
```

Repo Secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: repo-helm-redacted-s3
  namespace: argo-cd-dev
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: redacted-s3
  url: s3://redacted
```

**Version**

```shell
> argocd version
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:14:36Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: darwin/arm64
WARN[0002] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
> stern argocd-repo | grep s3
+ argocd-repo-server-8659f6c867-gvngv › argocd-repo-server
+ argocd-repo-server-8659f6c867-4g9b8 › argocd-repo-server
argocd-repo-server-8659f6c867-4g9b8 argocd-repo-server time="2022-06-30T18:53:53Z" level=error msg="finished unary call with code Unknown" error="error testing repository connectivity: Get \"s3://redacted/index.yaml\": unsupported protocol scheme \"s3\"" grpc.code=Unknown grpc.method=TestRepository grpc.request.deadline="2022-06-30T18:54:53Z" grpc.service=repository.RepoServerService grpc.start_time="2022-06-30T18:53:53Z" grpc.time_ms=0.104 span.kind=server system=grpc
```
