### ISSUE TITLE
ApplicationSet - BitBucket SCM Generator fails on empty repositories

### ISSUE THREAD

**Issue by georgblumenschein** [argoproj/argo-cd#9845]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It seems that filters are not applied before searching through the repositories when using an Applicationset with the Bitbucket SCM generator. This leads to a failure if a repository is empty, even if it should be filtered out anyway.
I have seen this issue already fixed for GitHub and GitLab but cannot find the issues anymore, sorry.

**To Reproduce**
Create an ApplicationSet with the BitBucket scmProvider:

```

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
  - scmProvider:
      filters:
      - repositoryMatch: -cd$
        pathsExist: [applications]
      cloneProtocol: https
      bitbucketServer:       
        project: ****
        api: ****
        basicAuth:
          username: ****
          passwordRef:
            secretName: ****
            key: ****
  template:
    metadata:
....

```
Create an empty repository in the BitBucket Project and try to sync the changes

**Expected behavior**

Empty Repositories should not even be considered when they do not match the filter
Bonus: Even if they match the filter, they should not lead to an error

**Version**

```shell
argocd: v2.4.2+c6d0c8b
  BuildDate: 2022-06-21T20:42:05Z
  GitCommit: c6d0c8baaa291cd68465acd7ad6bef58b2b6f942
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
error listing repos: EOF
```

**Extra Note**

Already synced applications are not destroyed, so an empty repository showing up is not the end of the world
