### ISSUE TITLE
Persistent volume claim are deleted automatically when deleting argocd app

### ISSUE THREAD

**Issue by anamaymane** [argoproj/argo-cd#9853]
When deleting an argocd app from the UI, PVC are deleted even if add the annotation **argocd.argoproj.io/sync-options: Prune=false** which prevents argocd from pruning the resource. Here is the yaml file of my persistent volume:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-snapshot-pvc
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-rw
```

For the app deletion operation, I use the UI with the foreground delete option:
![image](https://user-images.githubusercontent.com/46690914/176892222-1d654403-1762-4b30-b31e-656f9503ea62.png)
