### ISSUE TITLE
A repository URL with a trailing slash, and the same URL without a trailing slash, are treated as different repos

### ISSUE THREAD

**Issue by pclalv** [argoproj/argo-cd#9857]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Given a repo secret configured for a GitHub repo with url
`https://github.com/example-org/example-repo`, Argo CD will error if
an Application is submitted with a repo URL of
`https://github.com/example-org/example-repo/` (note the trailing
slash `/`).

The web UI definitely helps the user do the right thing by populating
a dropdown with valid repos when creating or updating apps. However,
this subtle issue still affects non-UI use cases, such as `kubectl
apply`ing an Argo App manifest.

**To Reproduce**

1. Define a GitHub repo secret, for example:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-3836087239
  namespace: argocd
data:
  type: Z2l0
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
  url: aHR0cHM6Ly9naXRodWIuY29tL2V4YW1wbGUtb3JnL2V4YW1wbGUtcmVwbw== # https://github.com/example-org/example-repo, note lack of trailing slash
```

2. In the Argo CD web UI, try to define an Argo Application that
   refers to the same repo with a trailing slash at the end of its
   repo URL, for example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-api
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: path/to/foo-api/kustomize/overlays/prod
    repoURL: https://github.com/example-org/example-repo/ # note trailing slash
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
```

3. Observe that the following error appears:
   
>Unable to create application: application spec for foo-api is
>invalid: InvalidSpecError: repository not accessible: rpc error: code
>= Unknown desc = error testing repository connectivity:
>authentication required

**Expected behavior**

I would expect Argo to find no meaningful difference between referring
to a repo with or without a trailing slash on its URL.

I think that this expected behavior could be a problem for Git forges
that accept `/` at the end of repo names.

GitHub, for one, does not seem to accept `/` anywhere in a repo
name. I tried to create repos name `test/test` and `test/`, and the
GitHub UI indicated that it'd create repos named `test-test` and
`test-` respectively.

**Version**

I'm not sure why the CLI version says 'dirty'; I installed the CLI
with Homebrew.

```yaml
argocd: v2.4.3+471685f.dirty
  BuildDate: 2022-06-28T02:03:12Z
  GitCommit: 471685feae063c1c2e36a5ff268c4da87c697b85
  GitTreeState: dirty
  GoVersion: go1.18.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.2.2+03b17e0
  BuildDate: 2022-01-01T06:27:52Z
  GitCommit: 03b17e0233e64787ffb5fcf65c740cc2a20822ba
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.2.0 2021-06-30T22:49:26Z
  Helm Version: v3.7.1+g1d11fcb
  Kubectl Version: v0.22.2
  Jsonnet Version: v0.17.0
```

**Logs**

```
(from the argo-repo-server pod)

time="2022-06-30T18:53:18Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=ListRefs grpc.request.deadline="2022-06-30T18:54:18Z" grpc.service=repository.RepoServerService grpc.start_time="2022-06-30T18:53:18Z" grpc.time_ms=84.558 span.kind=server system=grpc
time="2022-06-30T18:53:18Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=ListApps grpc.request.deadline="2022-06-30T18:54:18Z" grpc.service=repository.RepoServerService grpc.start_time="2022-06-30T18:53:18Z" grpc.time_ms=86.739 span.kind=server system=grpc
time="2022-06-30T18:53:18Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=GetAppDetails grpc.request.deadline="2022-06-30T18:54:18Z" grpc.service=repository.RepoServerService grpc.start_time="2022-06-30T18:53:18Z" grpc.time_ms=89.813 span.kind=server system=grpc
time="2022-06-30T18:53:22Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Check grpc.request.deadline="2022-06-30T18:54:22Z" grpc.service=grpc.health.v1.Health grpc.start_time="2022-06-30T18:53:22Z" grpc.time_ms=0.039 span.kind=server system=grpc
time="2022-06-30T18:53:24Z" level=error msg="finished unary call with code Unknown" error="error testing repository connectivity: authentication required" grpc.code=Unknown grpc.method=TestRepository grpc.request.deadline="2022-06-30T18:54:24Z" grpc.service=repository.RepoServerService grpc.start_time="2022-06-30T18:53:24Z" grpc.time_ms=63.423 span.kind=server system=grpc

---

(from the argo-server pod)

time="2022-06-30T18:53:18Z" level=info msg="received unary call /repository.RepositoryService/ListRefs" grpc.method=ListRefs grpc.request.claims="{\"at_hash\":\"REDACTED\",\"aud\":\"argo-cd\",\"c_hash\":\"REDACTED\",\"email\":\"username@example.com\",\"email_verified\":true,\"exp\":1656692695,\"groups\":[\"example-org:example-group\"],\"iat\":1656606295,\"iss\":\"https://argocd.example.com/api/dex\",\"name\":\"Firstname Lastname\",\"preferred_username\":\"username\",\"sub\":\"REDACTED\"}" grpc.request.content="repo:\"https://github.com/example-org/example-repo\" " grpc.service=repository.RepositoryService grpc.start_time="2022-06-30T18:53:18Z" span.kind=server system=grpc
time="2022-06-30T18:53:18Z" level=info msg="received unary call /repository.RepositoryService/GetAppDetails" grpc.method=GetAppDetails grpc.request.claims="{\"at_hash\":\"REDACTED\",\"aud\":\"argo-cd\",\"c_hash\":\"REDACTED\",\"email\":\"username@example.com\",\"email_verified\":true,\"exp\":1656692695,\"groups\":[\"example-org:example-group\"],\"iat\":1656606295,\"iss\":\"https://argocd.example.com/api/dex\",\"name\":\"Firstname Lastname\",\"preferred_username\":\"username\",\"sub\":\"REDACTED\"}" grpc.request.content="source:<repoURL:\"https://github.com/example-org/example-repo\" path:\"path/to/foo-api/kustomize/overlays/prod\" targetRevision:\"HEAD\" chart:\"\" > appName:\"foo-api\" " grpc.service=repository.RepositoryService grpc.start_time="2022-06-30T18:53:18Z" span.kind=server system=grpc
time="2022-06-30T18:53:18Z" level=info msg="received unary call /repository.RepositoryService/ListApps" grpc.method=ListApps grpc.request.claims="{\"at_hash\":\"REDACTED\",\"aud\":\"argo-cd\",\"c_hash\":\"REDACTED\",\"email\":\"username@example.com\",\"email_verified\":true,\"exp\":1656692695,\"groups\":[\"example-org:example-group\"],\"iat\":1656606295,\"iss\":\"https://argocd.example.com/api/dex\",\"name\":\"Firstname Lastname\",\"preferred_username\":\"username\",\"sub\":\"REDACTED\"}" grpc.request.content="repo:\"https://github.com/example-org/example-repo\" revision:\"HEAD\" " grpc.service=repository.RepositoryService grpc.start_time="2022-06-30T18:53:18Z" span.kind=server system=grpc
time="2022-06-30T18:53:18Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = authentication required" grpc.code=Unknown grpc.method=ListRefs grpc.service=repository.RepositoryService grpc.start_time="2022-06-30T18:53:18Z" grpc.time_ms=99.41 span.kind=server system=grpc
time="2022-06-30T18:53:18Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = authentication required" grpc.code=Unknown grpc.method=ListApps grpc.service=repository.RepositoryService grpc.start_time="2022-06-30T18:53:18Z" grpc.time_ms=99.809 span.kind=server system=grpc
time="2022-06-30T18:53:18Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = authentication required" grpc.code=Unknown grpc.method=GetAppDetails grpc.service=repository.RepositoryService grpc.start_time="2022-06-30T18:53:18Z" grpc.time_ms=103.682 span.kind=server system=grpc
time="2022-06-30T18:53:24Z" level=info msg="received unary call /application.ApplicationService/Create" grpc.method=Create grpc.request.claims="{\"at_hash\":\"REDACTED\",\"aud\":\"argo-cd\",\"c_hash\":\"REDACTED\",\"email\":\"username@example.com\",\"email_verified\":true,\"exp\":1656692695,\"groups\":[\"example-org:example-group\"],\"iat\":1656606295,\"iss\":\"https://argocd.example.com/api/dex\",\"name\":\"Firstname Lastname\",\"preferred_username\":\"username\",\"sub\":\"REDACTED\"}" grpc.request.content="%!v(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)" grpc.service=application.ApplicationService grpc.start_time="2022-06-30T18:53:24Z" span.kind=server system=grpc
time="2022-06-30T18:53:24Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec for foo-api is invalid: InvalidSpecError: repository not accessible: rpc error: code = Unknown desc = error testing repository connectivity: authentication required" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2022-06-30T18:53:24Z" grpc.time_ms=95.42 span.kind=server system=grpc
```
