### ISSUE TITLE
In application yaml, repoURL's last slash makes some error.

### ISSUE THREAD

**Issue by nauco** [argoproj/argo-cd#9875]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I use bitbucket private repo as config repo with kustomize.
And I have an application yaml.
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    name: ''
    namespace: abc
    server: 'https://kubernetes.default.svc'
  source:
    path: app1/overlay/qa
    repoURL: 'https://bitbucket.org/mycompany/myrepo/src/master/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```
In Argocd v2.3.3, that yaml apply, applied well.
But in Argocd v2.4.3, that yaml apply, error occur "ComparisonError rpc error: code = Unknown desc = authentication required".

Also I remove spec.source.repoURL's last slash, it works well.

**Logs**

```
Message:               rpc error: code = Unknown desc = authentication required
    Type:                  ComparisonError
```
