### ISSUE TITLE
No applications yet but app exists in url

### ISSUE THREAD

**Issue by Haebuk** [argoproj/argo-cd#9885]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
 
I use argocd with ALB(AWS Application Load Balancer) there is no problem to login, but some error occurs create a app.
`Unable to load data: error getting app by name: application.argoproj.io "guestbook" not found`
how to fix it? thank you. 

**To Reproduce**

**Expected behavior**

**Screenshots**
in /applications 

![image](https://user-images.githubusercontent.com/68543150/177516319-4a2ac1e8-c121-4041-8f1e-dad41fba4071.png)

there is no app

in applications/guestbook
![image](https://user-images.githubusercontent.com/68543150/177516273-d92ee4e1-a680-4896-8e23-84fd4cea6618.png)

**Version**

```shell
$ argocd version
argocd: v2.4.3+471685f
  BuildDate: 2022-06-27T21:34:16Z
  GitCommit: 471685feae063c1c2e36a5ff268c4da87c697b85
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: windows/amd64
time="2022-07-06T18:15:20+09:00" level=warning msg="Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web."
argocd-server: v2.4.3+471685f
  BuildDate: 2022-06-27T21:02:55Z
  GitCommit: 471685feae063c1c2e36a5ff268c4da87c697b85
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0```
```

**Logs**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: my acm arn
    alb.ingress.kubernetes.io/healthcheck-path: /login
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

  finalizers:
    - ingress.k8s.aws/resources
  labels:
    app: argocd-ingress
  name: argocd-ingress
  namespace: argocd
spec:
  defaultBackend:
    service:
      name: argocd-server
      port: 
        number: 80
  rules:
    - host: myhost
      http:
        paths:
          - path: /
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
            pathType: Prefix

```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default

```
