### ISSUE TITLE
ApplicationSet CRD should not validate `template` or `generators[].{generator}.template` fields

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#9919]
# Summary

The ApplicationSet CRD inherits validation rules from the Application spec. We should clear out the "required" validation rules for all the `template` fields (i.e. the generator templates and the main template).

# Motivation

The problem is that, if you want to provide part of the Application template in the main `template` field and the rest of it in a [generator template](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#generator-templates), you'll get validation errors. To pass validation, you have to provide a fully-specified, valid Application in each `template` field. For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/some/repo
        revision:e2e
        directories:
          - path: '*'
        template:
          metadata:
            name: '{{path.basenameNormalized}}'
          spec:
            project: "my-project"
            destination:
              server: https://kubernetes.default.svc
            source:
              targetRevision: "e2e"
              repoURL: https://github.com/some/repo
              path: '{{path.basenameNormalized}}'
    - git:
        repoURL: https://github.com/some/repo
        revision: release/prd
        directories:
          - path: '*'
        template:
          metadata:
            name: '{{path.basenameNormalized}}'
          spec:
            project: "my-project"
            destination:
              server: https://kubernetes.default.svc
            source:
              targetRevision: "prd"
              repoURL: https://github.com/some/repo
              path: '{{path.basenameNormalized}}'
  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: "my-project"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
      source:
        repoURL: https://github.com/some/repo
        path: '{{path.basenameNormalized}}'
        directory:
          jsonnet: {}
          recurse: true
```

The more generators you have, the more duplication there is. In my actual use case, I have four generators.

Ideally I'd like to be able to do this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/some/repo
        revision:e2e
        directories:
          - path: '*'
        template:
          metadata:
            name: '{{path.basenameNormalized}}'
          spec:
            source:
              targetRevision: "e2e"
    - git:
        repoURL: https://github.com/some/repo
        revision: release/prd
        directories:
          - path: '*'
        template:
          spec:
            source:
              targetRevision: "prd"
  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: "my-project"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
      source:
        repoURL: https://github.com/some/repo
        path: '{{path.basenameNormalized}}'
        directory:
          jsonnet: {}
          recurse: true
```

# Proposal

I think this would require a post-processor on the ApplicationSet CRD generation to remove "required" validation from the OpenAPI spec.

This pushes validation errors to runtime. I think it's worthwhile for the simplified spec.
