### ISSUE TITLE
gRPC upgrade in 2.4.x causes ENHANCE_YOUR_CALM error for gRPC streams taking longer than ~40s

### ISSUE THREAD

**Issue by notfromstatefarm** [argoproj/argo-cd#9924]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to 2.4.x, our CMP sidecars were mysteriously failing 100% of the time with an `ENHANCE_YOUR_CALM` error from the cmp-server to the repo-server.

Looking into gRPC documentation and everything I could find on the internet, the error itself is triggered when the client sends pings too early. We upgraded from gRPC v1.15 to v1.45 in https://github.com/argoproj/argo-cd/pull/8929. And in v1.35, gRPC merged this PR that adds throttling: https://github.com/grpc/grpc/pull/23313

It seems others ran into the same issue here: https://github.com/grpc/grpc-go/issues/5161

So far I've only reproduced this on CMPs.

It seems that we set the client timeout rate to 10 seconds, which is too low now that there is ping throttling. After four pings, the client is forcefully disconnected and the RPC cancelled. Settings have to be configured on the servers now as well.

https://github.com/argoproj/argo-cd/blob/10324a62162cf5c80ac8babd586ae370baa39f9a/util/grpc/grpc.go#L90

**To Reproduce**

Create a CMP that takes longer than ~40 seconds, i.e.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      generate:
        command: [sh, -c, 'sleep 45; echo "{\"kind\": \"ConfigMap\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"$ARGOCD_APP_NAME\", \"namespace\": \"$ARGOCD_APP_NAMESPACE\", \"annotations\": {\"Foo\": \"$FOO\", \"KubeVersion\": \"$KUBE_VERSION\", \"KubeApiVersion\": \"$KUBE_API_VERSIONS\",\"Bar\": \"baz\"}}}"']
      discover:
        find:
          command:
            [sh, -c, "date >> /tmp/plugin-discover-has-run; echo hello; exit 0"]
```

Attempt to run any refresh, sync, create and it will fail with the ENHANCE_YOUR_CALM error.

**Expected behavior**

gRPC request doesn't fail with this error

**Version**

2.4.x

**Logs**

```
rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: "too_many_pings"
```
