### ISSUE TITLE
Applicationset not refreshed after webhook event using matrix generator when using matrix generator references

### ISSUE THREAD

**Issue by ejhayes** [argoproj/argo-cd#9931]
@KojoRising @crenshaw-dev @sboschman

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It appears that the changes from #8998 are not compatible with the work done in #9080. This has been confirmed by the author of #8998

> @ejhayes , can you please open a new issue for this? This PR was merged before the implementation of the new feat of #9080. I had a quick glance at the code, and you are correct in your assumption that the webhook logic has not been updated to include the new #9080 feature.

**To Reproduce**

For example if I create an application set like this   and setup a webhook for pull requests they will not be refreshed when pull request events happen.
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appbundle-test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - scmProvider:
            cloneProtocol: https
            github: 
              organization: SOME_ORG
              tokenRef:
                secretName: github-token
                key: token
            filters:
              - repositoryMatch: ^argocd-test
        - pullRequest:
            github:
              owner: '{{ organization }}'
              repo: '{{ repository }}'
              labels:
              - preview
              tokenRef:
                secretName: github-token
                key: token
  template:
...
```

**Expected behavior**

However if I do not attempt to use `{{organization}}` and `{{repository}}` in the pull request generator then everything works as expected:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appbundle-test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - scmProvider:
            cloneProtocol: https
            github: 
              organization: SOME_ORG
              tokenRef:
                secretName: github-token
                key: token
            filters:
              - repositoryMatch: ^argocd-test
        - pullRequest:
            github:
              owner: 'SOME_ORG'
              repo: 'SOME_REPO'
              labels:
              - preview
              tokenRef:
                secretName: github-token
                key: token
  template:
...
```

I suspect there may be an issue with using the interpolated values that is causing the webhook event to be discarded.
