### ISSUE TITLE
Advanced templating for ApplicationSet

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-cd#9961]
# Summary

Currently ApplicationSet template is using https://github.com/valyala/fasttemplate. But it does not provide advanced templating feature which can be useful for inline helm values

# Motivation

When using inline helm values it could be nice to have templating capabilities such as loop, if etc

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj/argo-cd.git
      revision: HEAD
      files:
      - path: "applicationset/examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: "applicationset/examples/git-generator-files-discovery/apps/guestbook"
      destination:
        server: '{{cluster.address}}'
        namespace: guestbook
      helm:
        values: |
          fieldWithIf: {{#isOk}}{{myOkValue}}{{/isOk}}{{^isOk}}{{myNonOkValue}}{{/isOk}}
          fieldWithLoop
          {{#elements}}
            - name: {{elements.name}}
              value: {{elements.value}}
          {{/elements}}
```

# Proposal

Use Advanced templating such as Mustache. I am opened to work on a PR using https://github.com/hoisie/mustache
