### ISSUE TITLE
Status progressing when status.loadbalancer.ingress is non empty and does not have Hostname OR IP

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#997]
```
argocd app get grafana
Name:               grafana
Server:             https://k8s-api.test.appx.cloud
Namespace:          test-ops
URL:                https://localhost:8080/applications/grafana
Repo:               https://github.com/helm/charts.git
Target:
Path:               stable/grafana
Helm Values:        http://github-raw-content-service.demo:8080/k8s-test-cluster-config?filepath=grafana/helm-config.yaml
Sync Policy:        <none>
Sync Status:        Synced to  (722b19a)
Health Status:      Progressing

GROUP                      KIND                NAMESPACE  NAME                        STATUS  HEALTH
extensions                 PodSecurityPolicy   test-ops   grafana                     Synced  Healthy
                           Secret              test-ops   grafana                     Synced  Healthy
                           ConfigMap           test-ops   grafana                     Synced  Healthy
                           ServiceAccount      test-ops   grafana                     Synced  Healthy
rbac.authorization.k8s.io  ClusterRole         test-ops   grafana-clusterrole         Synced  Healthy
rbac.authorization.k8s.io  ClusterRoleBinding  test-ops   grafana-clusterrolebinding  Synced  Healthy
rbac.authorization.k8s.io  Role                test-ops   grafana                     Synced  Healthy
rbac.authorization.k8s.io  RoleBinding         test-ops   grafana                     Synced  Healthy
                           Service             test-ops   grafana                     Synced  Healthy
apps                       Deployment          test-ops   grafana                     Synced  Healthy
extensions                 Ingress             test-ops   grafana                     Synced  Progressing

```

Similarly, the ingress for grafana is likely empty for status.loadBalancer.ingress, so we consider this not healthy.

See:
https://github.com/argoproj/argo-cd/blob/master/docs/health.md

In our situation this status.loadBalancer.ingress is

  status:
    loadBalancer:
      ingress:
      - {}
For us this is a valid state, we do not have a hostname or IP in that field maybe thats the reason?

We do not use a loadbalancer so it is empty. I think this problem needs to be fixed right?

**Comment by k8sedu** [comment]
ingress not update it. if u use traefik and version above 1.7, it has config.

**Comment by jessesuen** [comment]
> For us this is a valid state. We do not use a loadbalancer so it is empty. I think this problem needs to be fixed right?

@peterbosalliandercom - which ingress controller are you running? Do you mind also providing the ingress object YAML? So far I know of the following ingress controllers which have issues with setting status. I would like to understand the logic & behavior of any other controller as well.

* contour - not yet supported - (see: https://github.com/heptio/contour/issues/403)
* traefik - disabled by default, but can be configured (see: https://github.com/argoproj/argo-cd/issues/968#issuecomment-451082913)

If your controller cannot be configured in a way that it updates `status.loadBalancer.ingress`, then I think the following workaround can be done, where Ingress objects are deployed using a placeholder value for `status.loadBalancer.ingress`:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
status:
  loadBalancer:
    ingress:
    - hostname: placeholder
```

The other point is that we will be implementing https://github.com/argoproj/argo-cd/issues/911#issuecomment-450029184 which will allow users the ability to override our built-in health assessments, including the ingress health assessment.

BTW, the Ingress health assessment logic is in-line with what is being proposed with sig-apps: https://github.com/kubernetes-sigs/application/issues/78

**Comment by peterbosalliandercom** [comment]
We use https://github.com/kubernetes/ingress-nginx

**Comment by peterbosalliandercom** [comment]
Hereby an example ingress object Yaml file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  labels:
    app: grafana
    app.kubernetes.io/instance: grafana
    chart: grafana-1.12.0
    heritage: Tiller
    release: grafana
  name: grafana
  namespace: test-ops
spec:
  rules:
  - host: ops-grafana.test.appx.cloud
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
        path: /
  tls:
  - hosts:
    - ops-grafana.test.appx.cloud
    secretName: wildcard-test-appx-cloud-cert
status:
  loadBalancer:
    ingress:
    - {}
```

**Comment by peterbosalliandercom** [comment]
Hereby an example ingress object Yaml file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  labels:
    app: grafana
    app.kubernetes.io/instance: grafana
    chart: grafana-1.12.0
    heritage: Tiller
    release: grafana
  name: grafana
  namespace: test-ops
spec:
  rules:
  - host: xxxx
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
        path: /
  tls:
  - hosts:
    - xxxx
    secretName: xxxx
status:
  loadBalancer:
    ingress:
    - {}
```

**Comment by lcostea** [comment]
The same thing happens for [kong ingress](https://github.com/Kong/kubernetes-ingress-controller)
Here is the ingress yaml which remains in Progressing status
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"po-xx"},"name":"po-xx-xxxx","namespace":"xxxx"},"spec":{"rules":[{"host":"*.dev.x.x.x","http":{"paths":[{"backend":{"serviceName":"po-xx-xxxx","servicePort":80},"path":"/api/v1/xxxxxxx[/]?$"}]}}]}}
  creationTimestamp: 2019-01-11T14:45:22Z
  generation: 1
  labels:
    app.kubernetes.io/instance: po-xx
  name: po-xx-xxxx
  namespace: xxxx
  resourceVersion: "11513131"
  selfLink: /apis/extensions/v1beta1/namespaces/xxxx/ingresses/po-xx-xxxx
  uid: 863e8068-15af-11e9-91f1-02fd02d95eb8
spec:
  rules:
  - host: '*.dev.x.x.x'
    http:
      paths:
      - backend:
          serviceName: po-xx-xxxx
          servicePort: 80
        path: /api/v1/xxxxxxx[/]?$
status:
  loadBalancer: {}
```

**Comment by peterbosalliandercom** [comment]
> 
BTW, the Ingress health assessment logic is in-line with what is being proposed with sig-apps: kubernetes-sigs/application#78
<

According to above it should be non empty and thats exactly what it is. The list is non empty. Shouldn't it be correct that way?

**Comment by jessesuen** [comment]
> According to above it should be non empty and thats exactly what it is. The list is non empty. Shouldn't it be correct that way?

I think you're right. I think we may have interpreted this incorrectly. I think the correct behavior should be:

Progressing:
```
status:
  loadBalancer: {}
```

Healthy:
```
status:
  loadBalancer:
    ingress:
    - {}
```
